[R][W]更新古代战争英文语言文件
CFPAOrg/Minecraft-Mod-Language-Package pull request #1012
Opened 2021-03-09 04:06 UTC by SettingDust

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16.1/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-03-14 07:10 UTC, 1478599553 commented on projects/1.12.2/assets/ancient-warfare-2/ancientwarfare/lang/zh_cn.lang
> +item.coin.ancient.tooltip=%1$s"米诺斯只余货币 - 因此，流通于于世"
这一句有待商榷

2021-03-14 07:11 UTC, SettingDust commented on projects/1.12.2/assets/ancient-warfare-2/ancientwarfare/lang/zh_cn.lang
> +item.coin.ancient.tooltip=%1$s"米诺斯只余货币 - 因此，流通于于世"
不好翻，原文含义就很模糊，不是英语

2021-03-14 07:12 UTC, 1478599553 commented on projects/1.12.2/assets/ancient-warfare-2/ancientwarfare/lang/zh_cn.lang
> +item.coin.ancient.tooltip=%1$s"米诺斯只余货币 - 因此，流通于于世"
起码两个于字应该改一下(确信

2021-03-14 07:13 UTC, SettingDust commented on projects/1.12.2/assets/ancient-warfare-2/ancientwarfare/lang/zh_cn.lang
> +item.coin.ancient.tooltip=%1$s"米诺斯只余货币 - 因此，流通于于世"
> 起码两个于字应该改一下(确信

确实：D

含义就是在世界上流通，但是怎么翻译，没想法

2021-03-14 07:17 UTC, SettingDust commented on projects/1.12.2/assets/ancient-warfare-2/ancientwarfare/lang/zh_cn.lang
> +item.coin.ancient.tooltip=%1$s"米诺斯只余货币 - 因此，流通于于世"
很久以前就询问过了，确认为上面那个翻译，这次修订我觉得流通于不太好理解，就修改了语序

2021-03-15 01:39 UTC, TUsama requested changes

2021-03-15 01:39 UTC, TUsama commented on projects/1.12.2/assets/ancient-warfare-2/ancientwarfare/lang/zh_cn.lang
>  item.scythe.name=Scythe
漏译？

2021-03-15 01:39 UTC, TUsama commented on projects/1.12.2/assets/ancient-warfare-2/ancientwarfare/lang/zh_cn.lang
> +item.coin.ancient.tooltip=%1$s"米诺斯只余货币 - 因此，流通于世"
```suggestion
item.coin.ancient.tooltip=%1$s"米诺斯，只余其货币 - 流通于世"
```
逗号是语气停顿，感觉这里是有点感叹的意思。

因此 我不知道你是咋翻出来的。

2021-03-15 01:39 UTC, TUsama commented on projects/1.12.2/assets/ancient-warfare-2/ancientwarfare/lang/zh_cn.lang
> +tile.decorative_flag.name=%s Banner
漏译？

2021-03-15 01:39 UTC, TUsama commented on projects/1.12.2/assets/ancient-warfare-2/ancientwarfare/lang/zh_cn.lang
> +
下方为何与上方完全一致？

2021-03-15 01:39 UTC, TUsama commented on projects/1.12.2/assets/ancient-warfare-2/ancientwarfare/lang/zh_cn.lang
> +gui.ancientwarfarenpc.no_chest_access_flag_not_claimed=在占领%s的旗帜前无法打开库存
```suggestion
gui.ancientwarfarenpc.no_chest_access_flag_not_claimed=在占领%s的旗帜前无法打开这一物品栏
```

2021-03-15 01:39 UTC, TUsama commented on projects/1.12.2/assets/ancient-warfare-2/ancientwarfare/lang/zh_cn.lang
> +ftbu_aw2.notification.townhall_neglected.tooltip.2=如果忽视它，%s分钟后将
```suggestion
ftbu_aw2.notification.townhall_neglected.tooltip.2=如果忽视它，%s分钟后它将
```

2021-03-15 01:39 UTC, TUsama commented on projects/1.12.2/assets/ancient-warfare-2/ancientwarfare/lang/zh_cn.lang
> +command.aw.structure.not_found=模板无法定位: %s
此处剩余英文标点。

2021-03-15 01:39 UTC, TUsama commented on projects/1.12.2/assets/ancient-warfare-2/ancientwarfare/lang/zh_cn.lang
>  route.fill.upto=填充至
请将文件内所有的“库存”统一至“物品栏”。

2021-03-15 01:39 UTC, TUsama commented on projects/1.12.2/assets/ancient-warfare-2/ancientwarfare/lang/zh_cn.lang
>  guistrings.npc.donotpursue=Stand Ground
漏译？

2021-03-15 01:39 UTC, TUsama commented on projects/1.12.2/assets/ancient-warfare-2/ancientwarfare/lang/zh_cn.lang
> +guistrings.npc.orders.add_position=按下 '%s' 添加目标点
```suggestion
guistrings.npc.orders.add_position=按下 '%s' 添加目标位置
```

如果没有下面那一行，用点也是可以的，只可惜下面那一行不是用“点”，为了统一就还是改成“位置”吧。

2021-03-15 01:39 UTC, TUsama commented on projects/1.12.2/assets/ancient-warfare-2/ancientwarfare/lang/zh_cn.lang
>  guistrings.npc.legs_slot=腿甲槽位
```suggestion
guistrings.npc.legs_slot=护腿槽位
```

原版词汇，下方的“靴”也是，统一为“靴子”

2021-03-15 01:39 UTC, TUsama commented on projects/1.12.2/assets/ancient-warfare-2/ancientwarfare/lang/zh_cn.lang
>  guistrings.spawner.custom_data_tip3=类型决定了值是什么（number，text，item，同样基于实体
```suggestion
guistrings.spawner.custom_data_tip3=类型决定了值是什么（number，text，item），同样基于实体
```

2021-03-15 03:02 UTC, SettingDust commented on projects/1.12.2/assets/ancient-warfare-2/ancientwarfare/lang/zh_cn.lang
>  item.scythe.name=Scythe
这里该怎么翻译？巨型镰刀？

2021-03-15 09:25 UTC, TUsama approved these changes

2021-03-15 15:11 UTC, merged