[R]CoFH的两个模组汉化
CFPAOrg/Minecraft-Mod-Language-Package pull request #1013
Opened 2021-03-11 08:36 UTC by Quaerere-Git

模组列表：
Archer's Paradox 1.16.3 - 1.1.1
Ensorcellation 1.16.3 - 1.1.2

- [ ] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [ ] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）
- [ ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16.1/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [ ] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [ ] 我已上传英文文件以供审查；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-03-11 08:37 UTC, Quaerere-Git commented
部分翻译参考自mcmod

2021-03-12 10:51 UTC, TUsama commented
请尽快学习如何将仓库拉取到本地（
这样可有效降低你反复删文件发文件的次数。

2021-03-12 11:20 UTC, TUsama requested changes

2021-03-12 11:20 UTC, TUsama commented on projects/1.16.1/assets/ensorcellation/ensorcellation/lang/zh_cn.json
> +  "enchantment.ensorcellation.trueshot.desc": "提升箭的精准度及速度，并允许箭穿透目标。",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

allow 一般翻译为“能让”“能使”这种功能的给予会更加的流畅，因为中文里很少会有“允许”某个非生物的 说法，但是 allow 是可以这样用的。

2021-03-12 11:20 UTC, TUsama commented on projects/1.16.1/assets/ensorcellation/ensorcellation/lang/zh_cn.json
> +  "enchantment.ensorcellation.smashing": "自动破碎",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

```suggestion
  "enchantment.ensorcellation.smashing": "自动粉碎",
```

2021-03-12 11:20 UTC, TUsama commented on projects/1.16.1/assets/ensorcellation/ensorcellation/lang/zh_cn.json
> +  "enchantment.ensorcellation.magic_edge.desc": "略微增加伤害并将其转化为魔法。",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "enchantment.ensorcellation.magic_edge.desc": "略微增加伤害，并将伤害转化为魔法伤害。",

```

2021-03-12 12:25 UTC, Quaerere-Git commented on projects/1.16.1/assets/archers-paradox/archers_paradox/lang/zh_cn.json
> +  "item.archers_paradox.glowstone_arrow.desc": "让东西亮一点。",
是的（

2021-03-14 14:59 UTC, TUsama approved these changes

2021-03-15 15:11 UTC, merged