[R]添加了环境科技的汉化
CFPAOrg/Minecraft-Mod-Language-Package pull request #1017
Opened 2021-03-12 16:30 UTC by Death-123

添加了环境科技的汉化

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16.1/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-03-13 02:21 UTC, TUsama requested changes

2021-03-13 02:21 UTC, TUsama commented on projects/1.16.1/assets/environmental-core/envirocore/lang/zh_cn.json
> +	"itemGroup.envirocore.resources": "环境科技:资源",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

请使用｜作为mod名称和组别的分隔符。
例如：环境科技｜资源

2021-03-13 02:21 UTC, TUsama commented on projects/1.16.1/assets/environmental-core/envirocore/lang/zh_cn.json
> +	"info.envirocore.rgb_controller.one": "潜行右键一个多方块组件以取色",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

虽然口语可以说“右键”一个东西，但在文本中，请使用“右键单击”或者“右击”。

2021-03-13 02:21 UTC, TUsama commented on projects/1.16.1/assets/environmental-core/envirocore/lang/zh_cn.json
> +	"component.envirocore.frame_tier_1.types": "框架(等级>=1)",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

若括号内文字为中文，推荐将括号改为中文括号，例如（等级>=1）。

这样会让看的人感觉字与字之间不那么挤。

2021-03-13 02:21 UTC, TUsama commented on projects/1.16.1/assets/environmental-energy/enviroenergy/lang/zh_cn.json
> +	"enviroenergy.ccu.solar.potential_per_tick2": "potential_per_tick * max_efficiency = 每个电池的最大 势能/t",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

这个空格？

2021-03-13 02:21 UTC, TUsama commented on projects/1.16.1/assets/environmental-materials/enviromats/lang/zh_cn.json
> +	"itemGroup.enviromats.blocks": "环境材料:方块",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

一样的分隔符问题。

2021-03-13 04:12 UTC, Death-123 commented
修了(

2021-03-14 14:57 UTC, TUsama approved these changes

2021-03-15 15:11 UTC, merged