[R]星辉大幅修正 Part1
CFPAOrg/Minecraft-Mod-Language-Package pull request #1023
Opened 2021-03-14 13:33 UTC by TUsama

- [ ] 我已确认文件路径正确，即 `project/assets/模组id/lang/zh_cn.lang`；
- [ ] 我已确认语言文件名大小写正确，所有的语言文件全为小写；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

“长夜漫漫”

2021-03-14 13:53 UTC, WuzgXY-GitHub requested changes
为防止撞车，先交一部分

2021-03-14 13:53 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/astral-sorcery/astralsorcery/lang/zh_cn.json
> +  "astralsorcery.journal.TOOLS.3.text": "若将受损的水晶石工具浸没到星光液中，那么当工具将星光液完全吸收之后，它们的耐久便会随之恢复。<NL>那些学识更丰富的学员甚至可以找到在使用过程中为这些工具提供外部星能的方法，来进一步增强它们的功能，或以其他的方式利用它们的属性。",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

```suggestion
  "astralsorcery.journal.TOOLS.3.text": "将受损的水晶石工具浸没到星光液中后，工具会完全吸收星光液，它们的耐久度也会随之恢复。<NL>那些学识更丰富的学员甚至可以找到在使用过程中为这些工具提供外部星能的方法，以进一步增强它们的功能，或用其他方式利用它们的属性。",

```

2021-03-14 13:53 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/astral-sorcery/astralsorcery/lang/zh_cn.json
> +  "astralsorcery.journal.WELCOME.2.text": "并且你还能自行掌握学习节奏，更好地适应自身的学习需要。<NL>但不要误以为你的学习会很轻松。在一众学习机构中，本学院极为注重毕业生的素质，而且你还需要向宝典证明你对于星光操纵基本原理的了解，才能获准从星光档案中获得更多的资源倾斜。<NL>愿你学习之路一帆风顺！<NL>——星辉学院全体教职员工。",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

```suggestion
  "astralsorcery.journal.WELCOME.1.text": "我们很高兴你能选择星辉学院进行本科魔法学习。你手上的宝典是本学院的讲师为你在学习期间特别准备的学习指南。所有宝典内容都链接到了我们的星光档案中，可用的学习资料会随着你的学习进度自动增加。<NL>如此的教学方法不再需要教授出面教导，",
  "astralsorcery.journal.WELCOME.2.text": "你还能自行掌握学习节奏，以符合自己的学习需求。<NL>但是，不要误以为你的学习会很轻松。在一众学习机构中，本学院较为注重毕业生的素质，而且你还需要向宝典证明你对星光操纵基本原理有了解，才能获准从星光档案中获得更多的资源倾斜。<NL>愿你学习之路一帆风顺！<NL>——星辉学院全体教职员工",
```
改不动了。

2021-03-14 13:53 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/astral-sorcery/astralsorcery/lang/zh_cn.json
> +  "astralsorcery.progress.missing.knowledge": "这上面似乎记载了什么，但以你当前的知识无法理解。",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "astralsorcery.progress.missing.knowledge": "这上面似乎记载了什么，但你以当前的知识尚无法理解。",

```

2021-03-14 13:53 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/astral-sorcery/astralsorcery/lang/zh_cn.json
> +  "astralsorcery.progress.switch.attunement": "星能力被巧妙地转换了...",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
  "astralsorcery.progress.switch.attunement": "星能力得到了巧妙的转换...",

```

2021-03-14 13:53 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/astral-sorcery/astralsorcery/lang/zh_cn.json
> +  "astralsorcery.progress.constellation.seen.track": "你在星芒宝典中加入了一个新的标签，方便自己随时跟进相关的内容。",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

```suggestion
  "astralsorcery.progress.constellation.seen.track": "你在星芒宝典中加入了一个标签，以便自己随时跟进相关内容。",

```

2021-03-14 13:53 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/astral-sorcery/astralsorcery/lang/zh_cn.json
> +  "astralsorcery.progress.perk_abilities": "星能力和工具能力现已为 %s",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

略生硬。我不确定我的建议是否合理，需要检查
```suggestion
  "astralsorcery.progress.perk_abilities": "星能力和工具能力现已变为 %s",

```

2021-03-14 13:53 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/astral-sorcery/astralsorcery/lang/zh_cn.json
> +  "astralsorcery.journal.SHRINES.3.text": "作为公共学习工具，浮动水晶的周围已被设置了特殊的结界，因而学员无法取走或修改它们。这保障了该区域所有学员的能够重复使用这一工具。<NL>本学院提醒所有学员，星光是无法穿透不透明的固体物料。当学院需要关闭时会加装屋顶遮蔽，以防止学区受到恶劣天气和敌对生物的影响，如果要使用神殿内部的浮动水晶，记得移除屋顶遮蔽。",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "astralsorcery.journal.SHRINES.1.text": "某些地域矗立着一些祭坛，学院认为这些祭坛对于精神方面的研究颇有益处。祭坛一般有两种变体：大型而精致的祭坛，其中内藏有能进行星光操纵的浮动水晶；和较小型的学员祭坛。这两种建筑内都存储有部分学习所必需的物资，当然这些物品也会因这一建筑的上次使用而有所变化。大型的神殿通常位于没有树木遮挡的空旷区域，比如沙漠或者高山顶部。",
  "astralsorcery.journal.SHRINES.2.text": "大型的神殿内含有可以用于聚焦和操纵星光的标准聚集水晶。所有人都能借此对五大“明亮级”的星座之一进行调和共鸣，这对学员的研究有极大的助益。<NL>这些水晶虽经精雕细琢，纯度却仍差一些火候，因此不要期望它所提供的星光量能与那些技术炉火纯青的水晶匠者制作的聚集水晶位于相同等级。也因如此，这些水晶无法在性能上更进一步了。",
  "astralsorcery.journal.SHRINES.3.text": "作为公共学习工具，浮动水晶的周围已被设置了特殊的结界，因而学员无法取走或修改它们。这保障了该区域所有学员的能够重复使用这一工具。<NL>本学院提醒所有学员，星光无法穿透不透明的固体物料。学院在需要时会加装屋顶遮蔽，以防止学区受到恶劣天气和敌对生物的影响，如果要使用神殿内部的浮动水晶，记得移除屋顶遮蔽。",
```

2021-03-14 14:21 UTC, TUsama commented
此次修改虽不是伤筋动骨，但却也更改了部分的译名。

我曾经略微思考过后续翻译者是否有必要将译名修正这件事。在我看来，译者的任务只有一个，那就是给玩家提供一个好的，便于理解的翻译，方便它们跨越语言障碍，更轻松愉悦地玩到自己想要玩的模组。

然而单单是在“好”这个字的定义上，就出现了诸多的疑难。任何思考过初版翻译和后续翻译之间的关系的译者，都会遇到这样的困境：初版译本很有可能在译名上出现了极为严重的错误，这大多是由于初版译者的水平有限。但在较长的时间后，玩家们已然接受了这样的译名，后续的译者在遇到这样的错误译名的时候，必须面临着一个抉择：到底是改，还是不改？一方面，改，可以修正错误，使得模组本身的逻辑更有一致性。“刷怪笼搅拌器”在逻辑上总是会引发人们的困惑，改掉之后可以使得玩家更好地知晓这一方块的作用，这是用途与名字之间的关系；而对于一些模组来说，模组的文本远不止于方块和提示文本，它们还有巨量的用于解释（或者从侧面解释）世界观的相关文本，这些文本一旦出了差错，对于一般玩家而言或许不会受太大的影响，但是对于模组自身而言，整体的逻辑与脉络都会被搅乱，改正之后，会让模组的世界观变得更为的清晰，喜欢钻研文本的玩家也能更好的理解世界观。

但另一方面，不改，玩家们就不再需要付出额外的学习成本，须知，若变更了译名，玩家同样是需要时间进行适应的，玩家得适应新的译名，并将之前的习惯逐渐改变，这是需要花费一定的时间成本。

从概念的层面上来谈，我们可以说：“好”这一个字，总是徘徊于译文正确性和玩家习惯黏性之间，我们到底应该依据哪一方，来判断一个翻译是不是好的翻译？

一种常见的论调是：反正不影响游玩，即便有错误，为啥要改？改了那不是讨人骂吗？在这种论调看来，除非是错误得非常离谱的“刷怪笼搅拌器”，否则完全没有必要改正那些译名，因为名字只是一个代号，只要不影响理解，叫啥都可以。这些人更为在意的是玩家的习惯黏性，这是当前化的”好“——因为它不用面对未来因为改变而带来的压力。

但是我们必须反思这样做带来的后果：一旦思考一下我们是以什么样的准则来要求自己，结果就显而易见了：如果认为“能用就行”，那么我们就没有必要去追求精确，追求雅，大概翻译一下就可以了，短文本机翻，长文本机翻润色，能看懂即可。这样的场景从来不是我们想要的，准确来说，是我们所拒斥的。我们厌恶机翻带来的坏文本，因为它会导致模组翻译的风气越来越浮躁，产出的文本会越来越差。然而，这种纯粹实用角度的看法，恰恰就是机翻有力（或许是潜在的）的支持者之一。

是的，如果修改了译名，玩家确实需要付出额外的成本进行学习。但是这不应该是改翻译的译者承担的责任，因为出现问题的不是改翻译的人，而是最初的错误的翻译。将修改错误翻译的责任放在了修改译名的译者身上，只会让追求正确的译者变得愈发畏手畏脚，最终剩下只能是那些“差不多就可以了”的译者，我想问，这样的模组翻译局面，是我们想要看到的吗？

我并不寄希望于这篇千字不到的小文能够对我所反对的人作出观念上的改变，尤其是因为限于篇幅，有很多的细节没有讨论清楚，没能展开。但是我的目标我确实已经说出来了，那就是译文的精确是所有译者的责任，译者不应当为了追求精确而要承担不顾用户习惯黏性的批评，因为如此的批评最后只会带来自身的毁灭，而不会带来任何的帮助。

以上。

2021-03-14 17:16 UTC, WuzgXY-GitHub requested changes

2021-03-14 17:16 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/astral-sorcery/astralsorcery/lang/zh_cn.json
> +﻿{
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

```suggestion
﻿{
```

2021-03-14 17:16 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/astral-sorcery/astralsorcery/lang/zh_cn.json
> +﻿{
理论上来说可以修复一些小问题

2021-03-14 17:17 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/astral-sorcery/astralsorcery/lang/zh_cn.json
> +﻿{
但实际上不能

2021-03-22 03:53 UTC, TUsama commented
我考虑了一下，还是得把之前仓库内进行过星辉翻译的人@出来，毕竟不能单人造轮子。

@yuanjie000 
@mcBegins2Snow 
@baka（算了）
@YueLengM 

我看了看@yuanjie000 仓库内的翻译。长文本进度还是差了不少，我专攻长文本，所以长文本上推进的量较多一些。

主要的分歧在于旧译名的保留问题，我个人持音译必须修改的意见，以及星光/星能的基本区分问题，至于仪式基座/光波增幅器之类的，如果坚持不改，那我也可以接受，但是至少要有充足的理由。

我不太愿意放弃掉版本迁移的机会，因为版本迁移实在是译名变更的大好时机。如果初代译本的翻译质量不高，那最好就是借着这个机会把文本以及译名重新修正一遍，这是对玩家，作者，社区的尊重，让错误的译名保留，不仅会让翻译者在翻译长文本时想着法子换掉原文的意思，而且还会让玩家搞不清楚为什么这个设备能这样用。

例如我一直不明白为什么光波增幅器能够用在五彩祭坛上。

对于音译的修改意见 ，请参看 https://github.com/LWHK/Passages/blob/master/Minecraft%20%E6%A8%A1%E7%BB%84%E7%BF%BB%E8%AF%91%EF%BC%9A%E3%80%8A%E7%A7%AF%E7%B4%AF%E3%80%8B/Markdown.md#%E8%87%AA%E9%80%A0%E8%AF%8D%E8%AF%AD 中对于词义的分析。此处不复述了。

2021-03-22 13:12 UTC, yuanjie000 commented
#https://github.com/HellFirePvP/AstralSorcery/issues/1769

2021-03-22 14:53 UTC, YueLengM commented
我只对星辉技能方面做了汉化修正，对其他部分不是很熟悉，所以就只看了下技能部分，其他部分还是交给更专业的人来吧。

`bleed` 目前翻译是撕裂，但有时候又翻译成了流血，个人建议还是统一成流血。
`phoenix` 目前翻译是凤凰。这个其实我也是最近才了解到是错误的，正确的应该是不死鸟。

854-855 行 ，`"perk.category.astralsorcery.epiphany.name": "稀有星能力"`
`epiphany` 在 1.12.2 那边还是翻译成顿悟，这个作者具体想表达什么我不太理解。
至于下一行的 `focus` 应该是 1.12.2 的定向更好（或者其他同义词），这些技能是对遥远的星座强化、定向、聚焦后才得以利用其效果，所以我认为这里的 focus 应该是聚焦之类的意思。

1116-1117 行，
`"perk.astralsorcery.key.damage_types.desc.1": "有几率在攻击时使敌人中毒、凋零"`
`"perk.astralsorcery.key.damage_types.desc.2": "或大大削弱。"`
翻译成 或使其被大大削弱 感觉会更好。

2021-03-23 01:07 UTC, TUsama commented
> 我只对星辉技能方面做了汉化修正，对其他部分不是很熟悉，所以就只看了下技能部分，其他部分还是交给更专业的人来吧。
> 
> `bleed` 目前翻译是撕裂，但有时候又翻译成了流血，个人建议还是统一成流血。
> `phoenix` 目前翻译是凤凰。这个其实我也是最近才了解到是错误的，正确的应该是不死鸟。
> 
> 854-855 行 ，`"perk.category.astralsorcery.epiphany.name": "稀有星能力"`
> `epiphany` 在 1.12.2 那边还是翻译成顿悟，这个作者具体想表达什么我不太理解。
> 至于下一行的 `focus` 应该是 1.12.2 的定向更好（或者其他同义词），这些技能是对遥远的星座强化、定向、聚焦后才得以利用其效果，所以我认为这里的 focus 应该是聚焦之类的意思。
> 
> 1116-1117 行，
> `"perk.astralsorcery.key.damage_types.desc.1": "有几率在攻击时使敌人中毒、凋零"`
> `"perk.astralsorcery.key.damage_types.desc.2": "或大大削弱。"`
> 翻译成 或使其被大大削弱 感觉会更好。

好的，十分感谢你提出的这几点问题和建议。以下是一些回复：
1. 关于“顿悟”星能力，作者可能是想表达，其中一种被学习后，其他几种“豁然开朗”“融会贯通”，此处使用“顿悟”或许可以。
2. 关于“focus”，我当初也觉得应该修正，但是最终还是没下的去手，因为我依然没有理解水晶石上的聚焦属性到底有什么用（
最后我发现好像是可以增加水晶石在聚集（能）效率？
3. “或使其被大大削弱"系原文，但我改成了现在的样子，如果需要使用原文，那必须得分句，否则句子中似出现两个主语，不妥当。

2021-03-23 11:19 UTC, yuanjie000 commented
`"perk.astralsorcery.key.damage_types.desc.1": "有几率在攻击时使敌人中毒、凋零"`
`"perk.astralsorcery.key.damage_types.desc.2": "或大大削弱。"`

这2句的最新原文已经改了
`"perk.astralsorcery.key.damage_types.desc.1": "Adds a chance to poison, wither ",
  "perk.astralsorcery.key.damage_types.desc.2": "or significantly weaken enemies on hit.",`
所以最新译文
`  "perk.astralsorcery.key.damage_types.desc.1": "在击中敌人时",
  "perk.astralsorcery.key.damage_types.desc.2": "增加中毒、凋零的几率",`

2021-03-23 11:23 UTC, TUsama commented
> `"perk.astralsorcery.key.damage_types.desc.1": "有几率在攻击时使敌人中毒、凋零"`
> `"perk.astralsorcery.key.damage_types.desc.2": "或大大削弱。"`
> 
> 这2句的最新原文已经改了
> `"perk.astralsorcery.key.damage_types.desc.1": "Adds a chance to poison, wither ", "perk.astralsorcery.key.damage_types.desc.2": "or significantly weaken enemies on hit.",`
> 所以最新译文
> ` "perk.astralsorcery.key.damage_types.desc.1": "在击中敌人时", "perk.astralsorcery.key.damage_types.desc.2": "增加中毒、凋零的几率",`
> 
> [可参考的文本内容](https://github.com/yuanjie000/AstralSorcery/blob/master/src/main/resources/assets/astralsorcery/lang/zh_cn.json?rgh-link-date=2021-03-23T11%3A19%3A26Z)

我就是按着这个来翻译的啊。。。

参照 https://github.com/HellFirePvP/AstralSorcery/blob/e8434f1a09356632babefee1925626dc3deefb2a/src/main/resources/assets/astralsorcery/lang/en_us.json#L1129

是有 significantly weaken enemies 字段的，在游戏中，实测为对目标添加长达10秒的虚弱2和缓慢2效果，是与中毒、凋零分开的。

2021-03-24 02:21 UTC, TUsama commented
作者是不是摸了啊（
怎么还不回复（

2021-03-24 02:26 UTC, TUsama commented
starlight 星光
starlight energy 星能
Ritual Pedestal 效应放大器 仪式基座 
Starlight Infuser 星能聚合器 星光灌注器
Astral Relay 光波增幅器 星辉中继器
Fosic 法斯刻 汇星
Domic 多米刻 穹域
Ichosic 艾克斯 液华
irradiant 辐射 灿芒 （辐射之星）
spectral 光谱 幻芒 （光谱之翼）
Ilium 伊利姆 烈阳
Fengarum （不记得了） 皎月

2021-03-24 16:00 UTC, TUsama commented
作者表示starlight和starlight energy是同一个东西，那现在所有的星光全部回滚为星能。
真好，原先我就其实挺忧虑这个改了会不会让人不习惯，现在没这个烦恼了（

2021-03-24 16:44 UTC, yuanjie000 commented
Ritual Pedestal 效应放大器（基台？）  Starlight Infuser 星能聚合器   Astral Relay 光波增幅器
这3个我觉得还是维持原先的比较好，虽然Ritual Pedestal直译的确是仪式基座，但不太适合，这个方块本来就是把水晶石的效果复现并施展出来的，所以用了效应放大的前缀，如果要提现出Pedestal的意思的话，加个基台？，Infuser -> 灌注器，这个画风不对，至于Astral Relay 是收集周围星能后向附近最近的耗能方块供能的，中继器的感觉是由其他方块发射能量经由中继器转发的，而且偏科技向的，不太适合。虽然在魔法mod里最好避免有“机、器”这样的字眼，但目前暂时想不出其他更好的了。
Fosic  聚星   Fosic Field  聚星界 
至于 Ilium  烈阳   （拉丁文译：脚？？？，英文音译：伊利姆）
Fengarum  皎月（希腊语译：月光，英文音译：芙荙姆）  
Ourium   天空（拉丁文译：欧留斯，英文音译：奥瑞尔）
这3个嘛emmmmmmmmmmmmmmmmmmmm，总感觉这样翻译的话，逼格降低了。。。。看着挺难受的，不如音译，你们自己感受一下。

2021-03-24 17:53 UTC, TUsama commented
我算是明白为啥你们当初能够把译名定的这么离谱了，原来文本都没有啃透啊。
1. 原文都有谈到，仪式基座的整个结构形成一个仪式，这个仪式的作用就是放大水晶石的魔法效果。你如果翻译成效应放大器，一方面擅自把译者的想法掺进了现有的原文，属于翻译的大忌；另一方面，你在翻译相关文本的时候你会觉得很别扭。因为你把仪式基座单独拿了出来，仪式的整个设定被你整个阉割了。你能顺畅翻译整个文本就怪了。
2. 原文中数次谈到，是将星能infuse到物品中，如此能够改变物质形态，增强物品对于星能的感受性。我不知道你这里翻译成聚合的意义在哪里，无论是从动画还是词意上都是“灌注”，“聚合”那不是纯粹的想当然？
3. 看原文。况且现在已无“光”的概念，只有星能，哪来的“光波”？这不是自相矛盾吗？astral 我不敢肯定指的是什么东西，但可以肯定的是，按照共鸣祭坛一章的内容，这个东西如果不翻译为“中继器”，就会出现巨大的理解困难。
4. 与聚星缸冲突，我原先也是想着“聚星”，但考虑了一下，为避免可能的冲突，遂改为“汇星”。
5. 音译乃是因为中文没有确切的词意进行翻译，所以需要进行音译。为了格调而采取音译，实在是莫名其妙。况且这还会给玩家造成理解困难，这也是我决定把音译给改掉的原因。三个词的词意均可在mcmod找到。

2021-03-24 23:13 UTC, WuzgXY-GitHub commented
感受不到啊。完全感受不到啊。

2021-03-25 00:44 UTC, yuanjie000 commented
灌注
1流泻；浇灌。
2引申指思想、知识等的输入。

聚合 
1结合，团聚。
2化学名词。单位结合成高分子化合物而不产生副产品。生成的高分子化合物叫聚合物。

2021-03-25 00:56 UTC, TUsama commented
我只问一句：你能不能在infuse的释义里找到“聚合”这个意思？

那我建议隔壁TC的注魔也别注了，直接改成”聚魔“，还可以碰一波怪猎的瓷。
植魔的符文祭坛也别”注入魔力“了，直接默认可以从周边的魔力池里面将魔力”聚合“过来，魔力发射器实在是太不”魔法“了。
巧工魔艺也别画织魔图样了，直接从周边”聚合“魔力，多省事，画画都不用画。
血魔法的祭坛也别把LP”灌注“到石头里了，建议直接远程”聚合“玩家身上的血，省了割腕的事。

2021-03-25 02:52 UTC, yuanjie000 commented
注入也比灌注好啊

2021-03-25 03:33 UTC, TUsama commented
我替你查了一查：灌注在1.12.2版本的仓库里，无论是魔法，科技，冒险类模组均有使用，注入也是如此。而且基本是三分天下，没有“只能是xx类模组可以使用灌注/注入”这个词的说法，这种说法完全缺乏事实上的根据。
我可以把灌注改成注入，但这不是因为灌注只能用在科技类模组，而是因为我不希望因为一个很无所谓的词来搅乱目前的翻译氛围。难听得话就不说了，还是希望能够遵循翻译的原则，也尊重客观的数据。

2021-04-16 02:53 UTC, fansi2020 commented on projects/1.16.1/assets/astral-sorcery/astralsorcery/lang/zh_cn.json
> +  "structure.astralsorcery.pattern_spectral_relay.name": "星辉转继器",
”转继器“是个专有名词吗

2021-04-16 03:01 UTC, fansi2020 commented on projects/1.16.1/assets/astral-sorcery/astralsorcery/lang/zh_cn.json
> +  "astralsorcery.journal.ILLUMINATION_WAND.1.text": "谈及照明，之前的方案是从荧石以及海蓝宝石内，或是从汇星之域中牵引出那些被动星能，借此星能创造光源。但在如今，与其这样做，不如换用个体共鸣的星能充能槽来充当星能供给源，如此，将星能稍加引导便可创造出辉光闪芒。将辉光星杖与染料进行合成，可以改变闪芒的颜色。用此杖为引导充能至洞穴照明器内，洞穴照明
惰性大多指物质反应 被动大多指社会自然关系 是不是应该用次级来修饰星能

2021-04-16 03:03 UTC, fansi2020 commented on projects/1.16.1/assets/astral-sorcery/astralsorcery/lang/zh_cn.json
> +  "astralsorcery.journal.CEL_CRYSTAL_GROW.1.text": "随着对水晶石内部结构的研究不断深入，其显示，随着水晶石自身的品质的增长，水晶石的生长大小会受此限制。纯铁要弱于掺杂了碳的铁，也就是钢，如此之道理或可用于水晶石之上，水晶石同样需要某种引导性杂质来改变它的内部结构，借此获得更为卓绝的效能。<NL>星尘充当了如此的杂质，但只有它还不够，水晶石的蜕变
”其显示“建议换成“我们发现”

2021-04-18 07:13 UTC, TUsama commented on projects/1.16.1/assets/astral-sorcery/astralsorcery/lang/zh_cn.json
> +  "structure.astralsorcery.pattern_spectral_relay.name": "星辉转继器",
不是。原先想要“中继器”，奈何原版中继器的单词不是 relay。

2021-04-18 07:14 UTC, TUsama commented on projects/1.16.1/assets/astral-sorcery/astralsorcery/lang/zh_cn.json
> +  "astralsorcery.journal.ILLUMINATION_WAND.1.text": "谈及照明，之前的方案是从荧石以及海蓝宝石内，或是从汇星之域中牵引出那些被动星能，借此星能创造光源。但在如今，与其这样做，不如换用个体共鸣的星能充能槽来充当星能供给源，如此，将星能稍加引导便可创造出辉光闪芒。将辉光星杖与染料进行合成，可以改变闪芒的颜色。用此杖为引导充能至洞穴照明器内，洞穴照明
此处之前校对已做更改，有两处文本使用到这个词。

2021-04-18 07:14 UTC, TUsama commented on projects/1.16.1/assets/astral-sorcery/astralsorcery/lang/zh_cn.json
> +  "astralsorcery.journal.CEL_CRYSTAL_GROW.1.text": "随着对水晶石内部结构的研究不断深入，其显示，随着水晶石自身的品质的增长，水晶石的生长大小会受此限制。纯铁要弱于掺杂了碳的铁，也就是钢，如此之道理或可用于水晶石之上，水晶石同样需要某种引导性杂质来改变它的内部结构，借此获得更为卓绝的效能。<NL>星尘充当了如此的杂质，但只有它还不够，水晶石的蜕变
也不是不行。

2021-04-18 07:26 UTC, closed without merging

2021-04-18 10:43 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/astral-sorcery/astralsorcery/lang/zh_cn.json
> +  "perk.astralsorcery.hybrid.armor_armor_toughness.name": "盔甲值与盔甲韧性",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

盔甲值和盔甲韧性