[R]添加 Ars Nouveau 汉化
CFPAOrg/Minecraft-Mod-Language-Package pull request #1042
Opened 2021-03-16 14:56 UTC by kappa-maintainer

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16.1/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)
几个疑难点：archwood -> 至高木，各类符号翻译和详细说明

2021-03-17 07:51 UTC, TUsama requested changes

2021-03-17 07:51 UTC, TUsama commented on projects/1.16.1/assets/ars-nouveau/ars_nouveau/lang/zh_cn.json
> +	"ars_nouveau.page.arcane_relay": "可在魔力罐和其它魔力中继器之间运输魔力。要从魔力罐中抽取魔力，需使用支配之杖先右击魔力罐，再右击魔力中继器。要从中继传输到另一个中继或魔力罐，先右击中继器，再右击传输的目标。一个中继器最多只能连接到 10 格远到目标。使用支配之杖潜行右击中继器可清空连接。",
```suggestion
	"ars_nouveau.page.arcane_relay": "可在魔力罐和其它魔力中继器之间运输魔力。要从魔力罐中抽取魔力，需使用支配之杖先右击魔力罐，再右击魔力中继器。要从中继传输到另一个中继或魔力罐，先右击中继器，再右击传输的目标。一个中继器最多只能连接到 10 格远的目标。使用支配之杖潜行右击中继器可清空连接。",
```

2021-03-17 07:51 UTC, TUsama commented on projects/1.16.1/assets/ars-nouveau/ars_nouveau/lang/zh_cn.json
> +	"ars_nouveau.page.enchanting_apparatus1": "附魔装置具利用基座和世界的魔力进行合成。要想使用附魔装置，请在附近放置任意数量的奥术基座并在其上放置物品。将你的试剂物品放置在附魔装置方块上，然后潜行与其互动以开始制作。附魔装置需要在其下方放置一个奥术核心才能运行。",
```suggestion
	"ars_nouveau.page.enchanting_apparatus1": "附魔装置能够利用基座和世界的魔力进行合成。要想使用附魔装置，请在附近放置任意数量的奥术基座并在其上放置物品。将你的试剂物品放置在附魔装置方块上，然后潜行与其互动以开始制作。附魔装置下方需要放置一个奥术核心，它才能运行。",
```

2021-03-17 07:51 UTC, TUsama commented on projects/1.16.1/assets/ars-nouveau/ars_nouveau/lang/zh_cn.json
> +	"item.ars_nouveau.ring_of_greater_discount": "高等节魔之戒",
两个戒指前缀统一一下，要不是级要不是等。

2021-03-17 07:51 UTC, TUsama commented on projects/1.16.1/assets/ars-nouveau/ars_nouveau/lang/zh_cn.json
> +	"ars_nouveau.page3.whelp_charm": "雏龙可以施放触摸或投射物开头的法术。你可以把法术写在法术羊皮纸上给它们。目前雏龙只会以其水晶附近的方块为目标。施法会消耗召唤水晶附近的魔力罐中的魔力。默认情况下，雏龙只会在§l所有§r法术效果都起作用时施法。比如收获只会对完全长成的树施放，生长只会对未成熟的作物施放。",
```suggestion
	"ars_nouveau.page3.whelp_charm": "雏龙可以施放以触摸或投射物开头的法术。你可以把法术写在法术羊皮纸上给它们。目前雏龙只会以其水晶附近的方块为目标。施法会消耗召唤水晶附近的魔力罐中的魔力。默认情况下，雏龙只会在§l所有§r法术效果都起作用时施法。比如收获只会对完全长成的树施放，生长只会对未成熟的作物施放。",
```

2021-03-17 07:51 UTC, TUsama commented on projects/1.16.1/assets/ars-nouveau/ars_nouveau/lang/zh_cn.json
> +	"ars_nouveau.page.reactive2": "将任何物品或盔甲放入附魔装置中可附上反应附魔。放在基座上的法术羊皮纸必须抄写有一个有效的法术。更多的信息请参见抄写台。反应附魔还需要在附魔装置附近放置魔力罐。第一级附魔大约消耗魔力罐所存储魔力的三分之一。",
请参见抄写台 指的是这一章吗？

2021-03-17 07:51 UTC, TUsama commented on projects/1.16.1/assets/ars-nouveau/ars_nouveau/lang/zh_cn.json
> +	"sylph.extremely_diverse": "家里的自然材料已经及其多样，但希尔芙永远不会拒绝添加新的自然方块！",
```suggestion
	"sylph.extremely_diverse": "家里的自然材料已经极其多样了，但希尔芙永远不会拒绝添加新的自然方块！",
```

2021-03-17 07:51 UTC, TUsama commented on projects/1.16.1/assets/ars-nouveau/ars_nouveau/lang/zh_cn.json
> +	"ars_nouveau.glyph_desc.intangible": "使方块暂时变成空气。可用强化增强以处理高挖掘等级方块。还能被范围效果、减少时效和延长时效增强。",
```suggestion
	"ars_nouveau.glyph_desc.intangible": "使方块暂时变成空气。使用强化增强效果后，便可用于处理高挖掘等级的方块。它还能被范围效果、减少时效和延长时效增强。",
```

本来不太想改你的语序的，一个是太多第二个是还能接受，但是这句实在是太紧凑了，不拆不行。

之前轩辕说过，一段翻译出来的字段最好不要超过25个字，这样可以最大限度的保证阅读流畅感。你现在其实有很多都超了，不过改也没必要，多看一遍还是能看懂的。

向这种 for 后面跟一串目的的，可以考虑把它拆成单个分句，这样可以明显提升译文流畅度。在日常用语中，我们也会有“若想...那么...”或者“为了...因此”这种表因果的连接词，不要总是用“以”把目的和行为全缩在一起，中文有这样的表达，但是还是拆句子用的更多。

2021-03-17 07:51 UTC, TUsama commented on projects/1.16.1/assets/ars-nouveau/ars_nouveau/lang/zh_cn.json
> +	"ars_nouveau.glyph_desc.projectile": "你的初始法术。召唤一个投射物，投射物命中目标或方块时会造成法术效果。",
projectile 原版词汇，弹射物。

2021-03-17 07:51 UTC, TUsama commented on projects/1.16.1/assets/ars-nouveau/ars_nouveau/lang/zh_cn.json
> +	"ars_nouveau.glyph_desc.redstone_signal": "在方块上创造一个红石信号脉冲，就像按钮一样。信号初始强度为 10，可通过强化提升，可通过抑制减少。脉冲时长可通过延长时效延长。",
```suggestion
	"ars_nouveau.glyph_desc.redstone_signal": "在方块上创造一道红石信号脉冲，就像按钮一样。信号初始强度为 10，可通过强化提升，可通过抑制减少。脉冲时长可通过延长时效延长。",
```

2021-03-17 07:58 UTC, kappa-maintainer commented on projects/1.16.1/assets/ars-nouveau/ars_nouveau/lang/zh_cn.json
> +	"item.ars_nouveau.ring_of_greater_discount": "高等节魔之戒",
greater 和 lesser 对照高等和次级是参考 dnd 的习惯翻译，不过也可以改成高级

2021-03-17 07:59 UTC, kappa-maintainer commented on projects/1.16.1/assets/ars-nouveau/ars_nouveau/lang/zh_cn.json
> +	"ars_nouveau.page.reactive2": "将任何物品或盔甲放入附魔装置中可附上反应附魔。放在基座上的法术羊皮纸必须抄写有一个有效的法术。更多的信息请参见抄写台。反应附魔还需要在附魔装置附近放置魔力罐。第一级附魔大约消耗魔力罐所存储魔力的三分之一。",
嗯，我把参见环节都改改

2021-03-17 08:01 UTC, kappa-maintainer commented on projects/1.16.1/assets/ars-nouveau/ars_nouveau/lang/zh_cn.json
> +	"ars_nouveau.glyph_desc.projectile": "你的初始法术。召唤一个投射物，投射物命中目标或方块时会造成法术效果。",
大意了

2021-03-17 11:34 UTC, kappa-maintainer commented
符号属于忘记审视的旧译，在部分语句处会有奇怪的歧义，而且感觉缺少韵味
要是觉得不行可revert

2021-03-18 07:23 UTC, TUsama approved these changes

2021-03-20 13:59 UTC, merged