[R]添加Woot汉化|1.16
CFPAOrg/Minecraft-Mod-Language-Package pull request #1049
Opened 2021-03-19 13:36 UTC by Death-123

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16.1/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-03-24 04:31 UTC, TUsama requested changes
长文本还是有很多问题，建议琢磨琢磨，我已经给了一些意见了。琢磨透了再改改。

2021-03-24 04:31 UTC, TUsama commented on projects/1.16.1/assets/woot/woot/lang/zh_cn.json
> +  "guide.woot.perks.slaughter.0": "这个升级插件生产工业先锋粉红史莱姆液体和肉汤于掉落物输出口旁的储罐。更高的等级提高生产的流体量。",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

长文本翻译超出 25 个字之后，若非必要，可以稍微拆句，可以降低“信息密度”，提高译文流畅性。

2021-03-24 04:31 UTC, TUsama commented on projects/1.16.1/assets/woot/woot/lang/zh_cn.json
> +  "guide.woot.perks.tier_shard.0": "为了制造更高等级的生物工厂，你需要使用精华碎片来制造一些方块。精华碎片只有在安装了这个升级插件的工厂才能生产。不同等级的升级插件决定碎片生成的判定次数，工厂等级决定碎片掉落几率和不同碎片种类的掉落权重。",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "guide.woot.perks.tier_shard.0": "想要制造更高等级的生物工厂，你需要使用精华碎片来制造一些方块。只有在安装了这个升级插件之后，工厂才能生产精华碎片。不同等级的升级插件决定碎片生成的判定次数，工厂等级决定碎片掉落几率和不同碎片种类的掉落权重。",
```

想想平常是如何说话的：先说状语/条件，再说句子/结果:
> 昨天中午，我吃的是鱼。
> 只有按时吃饭，才不会得胃病。

一旦见到英语中的状语，记得把它倒装到前面，这比较符合汉语习惯。

2021-03-24 04:31 UTC, TUsama commented on projects/1.16.1/assets/woot/woot/lang/zh_cn.json
> +  "guide.woot.tools.hammer.0": "$(item)YA锤子$(0)有两个主要用途。首先是在地狱铁砧上制造物品。其次是用于原版合成。$(item)YA锤子$(0)在配方中使用永远不会被消耗。",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

最后一句同样是未倒装，你可以先试试，发在评论区。

2021-03-24 04:31 UTC, TUsama commented on projects/1.16.1/assets/woot/woot/lang/zh_cn.json
> +  "guide.woot.tools.oracle.0": "$(item)迪的神谕$(0)允许你查看任何模拟的生物在每个抢夺等级的掉落。",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

"allow"我习惯翻译为“能够”，而不是“允许”因为中文很少这么使用允许一词。

```suggestion
  "guide.woot.tools.oracle.0": "$(item)迪的神谕$(0)可让你查看在不同的抢夺等级的情况下所有模拟的生物的掉落物以及掉落几率。",
```

2021-03-24 04:31 UTC, TUsama commented on projects/1.16.1/assets/woot/woot/lang/zh_cn.json
> +  "item.woot.guide.landing": "一本写给这大的，坏的，魔法多方块生物工厂的指南。就像烹饪锅一样，你会喜欢它或者讨厌它的--由你选择。",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
  "item.woot.guide.landing": "一本写给这既大又坏，还沾点魔法的多方块生物工厂的指南。就像马麦酱，要么你爱它爱得深沉，要么你恨它恨得要死--由你选择。",
```

系马麦酱的slogan，参见：https://www.secretfoodtours.com/blog/marmite-a-love-and-hate-story/

2021-03-24 04:31 UTC, TUsama commented on projects/1.16.1/assets/woot/woot/lang/zh_cn.json
> +  "item.woot.guide.name": "Woot指南",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
  "item.woot.guide.name": "Woot 指南",
```

2021-03-24 04:31 UTC, TUsama commented on projects/1.16.1/assets/woot/woot/lang/zh_cn.json
> +  "jei.woot.intern.1": "对着工厂核心使用以建造或检验",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

```suggestion
  "jei.woot.intern.1": "对着工厂核心使用，可以建造或检验工厂结构",
```
拆句，to do 意味着去做某些事情，这个时候只用“以”引导后面的句子，不是不可以，但是汉语中不常用这种表达，口语中习惯于拆句子，将要做的事情单独列出。
例如：
> 我把苹果削了皮，这样方便我吃苹果。

但不会说：

> 我把苹果先削了皮以方便我吃苹果。

2021-03-24 08:45 UTC, Death-123 commented on projects/1.16.1/assets/woot/woot/lang/zh_cn.json
> +  "guide.woot.perks.mass.0": "$(item)横冲直撞$(0)升级插件增加工厂生成的生物数量。更高等级生成更多数量。如果工厂包含多种生物，将使用质量最小的生物。",
这个升级插件的效果我测试的时候没发现比重这一说,铁傀儡和羊gui写的都是生成4只,掉落物也都有....

2021-03-24 08:46 UTC, Death-123 commented on projects/1.16.1/assets/woot/woot/lang/zh_cn.json
> +  "guide.woot.perks.mass.0": "$(item)横冲直撞$(0)升级插件增加工厂生成的生物数量。更高等级生成更多数量。如果工厂包含多种生物，将使用质量最小的生物。",
所以这个mass指的是啥我也不知道....

2021-03-24 08:46 UTC, TUsama commented on projects/1.16.1/assets/woot/woot/lang/zh_cn.json
> +  "guide.woot.perks.mass.0": "$(item)横冲直撞$(0)升级插件增加工厂生成的生物数量。更高等级生成更多数量。如果工厂包含多种生物，将使用质量最小的生物。",
那mc也没质量的说法啊。。。

2021-04-03 02:20 UTC, TUsama approved these changes

2021-04-03 02:20 UTC, TUsama commented on projects/1.16.1/assets/woot/woot/lang/zh_cn.json
> +  "advancements.woot.root.description": "战利品mod（对，这些是真的贴图）",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

如果保留mod，记得在英文与中文之间添加空格。
如果想要翻译，可以为“模组”。

2021-04-03 12:03 UTC, TUsama approved these changes

2021-04-04 09:12 UTC, merged