[R]补充洞穴2
CFPAOrg/Minecraft-Mod-Language-Package pull request #1096
Opened 2021-04-12 03:45 UTC by fansi2020

- [ ] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)

- [ ] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）
- [ ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16.1/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [ ] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [ ] 我已上传英文文件以供审查；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-04-12 03:46 UTC, fansi2020 commented
翻译仓促 如有遗漏 请多指教

2021-04-13 04:01 UTC, TUsama requested changes
错漏颇多，抓紧改正。

2021-04-13 04:01 UTC, TUsama commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +cavern.miningassist.toggle.failed.message=挖矿辅助无法改变直到你成为 %s
```suggestion
cavern.miningassist.toggle.failed.message=成为 %s 后方可切换挖矿辅助
```

2021-04-13 04:05 UTC, fansi2020 commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +advancements.cavern.magic_overload.description=发动过载魔法
超负荷是成就 超负荷魔法太拗口

2021-04-13 12:57 UTC, fansi2020 commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +cavern.miningassist.quick=Veinmine
不知道怎么翻译 我再看看吧

2021-04-13 13:00 UTC, fansi2020 commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +item.bowCavenic.torch=火把射击
有道理

2021-04-14 08:07 UTC, TUsama commented
按照中英标点规范，有：
> 汉语中的省略号是六个点，而且位置是居中的（……）。英语省略号是三个点，而且位置是居下的（…）。汉语的省略号要用中文字体，比如宋体、黑体，不能用西文字体，比如Times New Roman。英语的省略号要用西文字体，比如Times New Roman，不能用中文字体，比如宋体、黑体、楷体。
请再次修改一下你的 274、275 行两处标点符号问题。

2021-04-15 02:15 UTC, fansi2020 commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +cavern.config.biomes.terrainBlock=地形块
182-186行太生硬是吗

2021-04-15 02:30 UTC, TUsama commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +cavern.config.biomes.terrainBlock=地形块
block 应翻译为方块。不只是此处，其他的将方块翻译为“块”的 需全部改正。

2021-04-15 02:31 UTC, TUsama commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +cavern.miningassist.quick=Veinmine
veinmine 只要拆开一看就能明白了，矿脉挖掘。

2021-04-15 02:33 UTC, fansi2020 commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +cavern.miningassist.quick=Veinmine
哦

2021-04-15 02:33 UTC, fansi2020 commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +
参考的mod里自带的日文文件

2021-04-15 14:50 UTC, fansi2020 commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +
![图片](https://user-images.githubusercontent.com/65439944/114889480-bd888800-9e3c-11eb-9ab6-cb4690809e6c.png)
最下面的按键可以让手持的魔法书发动效果 过程中有一个咏唱的特效

2021-04-15 14:52 UTC, TUsama commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

”的咏唱“从何而来？

2021-04-15 14:53 UTC, TUsama commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +
那应该是“咏唱法术”吧...毕竟应该是动词打头。

2021-04-16 02:38 UTC, fansi2020 commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +entity.Beam.name=Beam
可能是横梁或者是光束之类的 我再看看吧

2021-04-16 02:41 UTC, TUsama commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +item.bowCavenic.torch=火把射击
那就用“火把射击”。

2021-04-17 09:14 UTC, TUsama commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +entity.Beam.name=Beam
此处？

2021-04-17 09:21 UTC, TUsama requested changes

2021-04-17 09:21 UTC, TUsama commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +cavern.config.dimension.autoVeins.tooltip=如果在此维度生成的矿脉被矿物字典自动收集。
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

If 应译为“是否”，引导的是从句。

2021-04-17 09:21 UTC, TUsama commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +cavern.config.veins.targetBlock.tooltip=目标方块的注册名。  此矿物方块将尝试在内部生成。
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

中文标点后无需空格。

2021-04-17 09:21 UTC, TUsama commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +cavern.config.veins.blockMeta.tooltip=矿方块的元数据。
|Feedback Priority|
|---|
|🌫 Dust / Non-blocking, “take it or leave it”|

```suggestion
cavern.config.veins.blockMeta.tooltip=矿物方块的元数据。
```

2021-04-17 09:21 UTC, TUsama commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +cavern.config.veins.size.tooltip=多么大的矿脉啊。
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

此处仍未更改？

2021-04-17 09:21 UTC, TUsama commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +cavern.config.select.oreDict.selected=%d 个被选择的矿石词典名称
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

专有名词，矿物词典。

2021-04-17 09:21 UTC, TUsama commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +cavern.config.select.entry.selected=%d 个被选择的入传送门
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

何为“入传送门”？

2021-04-17 09:21 UTC, TUsama commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +cavern.message.portal.mirage=必须拥有一本幻象世界的书。
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

此处仍缺主语。

2021-04-17 09:21 UTC, TUsama commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +cavern.message.portal.wait=还不能旅行。
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

传送还是旅行？

2021-04-20 07:14 UTC, TUsama requested changes

2021-04-24 02:03 UTC, merged

2021-04-24 09:55 UTC, fansi2020 commented on projects/1.12.2/assets/cavern2/cavern/lang/zh_cn.lang
> +cavern.regeneration.backup=%s 维度正在备份......
大佬的省略号是‘Shift+6“打的吗……