[R] 更新新生魔艺
CFPAOrg/Minecraft-Mod-Language-Package pull request #1098
Opened 2021-04-14 08:07 UTC by kappa-maintainer

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16.1/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

主要审查点在手册和lang的新内容

2021-04-14 13:18 UTC, baka-gourd commented on projects/1.16.1/assets/ars-nouveau/ars_nouveau/patchouli_books/worn_notebook/zh_cn/entries/machines/potion_jar.json
> +            "text": "A jar that stores up to 100 potions. Potion can be removed by using an Empty Bottle or Potion Flask on the jar. Wixies will use these jars during Potion Autocrafting. The jar may
没翻译完的标称draft

2021-04-14 13:19 UTC, kappa-maintainer commented on projects/1.16.1/assets/ars-nouveau/ars_nouveau/patchouli_books/worn_notebook/zh_cn/entries/machines/potion_jar.json
> +            "text": "A jar that stores up to 100 potions. Potion can be removed by using an Empty Bottle or Potion Flask on the jar. Wixies will use these jars during Potion Autocrafting. The jar may
好像拷错了

2021-04-14 13:19 UTC, baka-gourd requested changes
可以先标成draft

2021-04-14 13:22 UTC, kappa-maintainer commented
正常了

2021-04-14 13:35 UTC, baka-gourd commented
> 正常了

其实下面还有。。。可以全部看一遍？

2021-04-14 13:38 UTC, kappa-maintainer commented
我把en_us文件夹传了，有英文是很正常的
然后不少条目里面全是 translation key，所以看上去没中文
最后就是更新日志，这个确实没译

2021-04-17 13:20 UTC, kappa-maintainer commented
- [x] 我已确定中文文件中没有未翻译的文本，如有以删除

2021-04-18 16:17 UTC, closed without merging