crimson revelation 翻译修订及润色
CFPAOrg/Minecraft-Mod-Language-Package pull request #1100
Opened 2021-04-17 11:32 UTC by zmaj11

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [x] 我已确定中文文件中没有未翻译的文本，如有以删除
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16.1/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-04-18 02:00 UTC, TUsama commented
标题不合规 ，请尽快修正。

2021-04-18 02:15 UTC, Determancer commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.CRIMSON_ARMOR.text.stage.2=成功了！这其中的要领就是使用金属板而不是锭来做盔甲，并将血腥教徒旗帜直接整合到套装中。在防护力方面，血腥邪徒盔甲与铁制盔甲相似但耐久略高，也更时髦。血腥法袍比我的神秘使法袍的防御能力更为卓越，但在引导 Vis 方面却比凡俗的盔甲要好得多。<BR>它们似乎由比神秘学黑暗的多的魔法制成。长时
我就提一句吧，似乎在文本中存在大量关于【程度描写】的错误。
"The robes are significantly more protective than my Thaumaturge's Robes, but barely better than mundane armor when it comes to channeling vis."
barely better是几乎没好到哪去的意思，而非这里的好得多。需要加强一下这方面的准确性。

2021-04-18 02:17 UTC, Determancer commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.CRIMSON_ARMOR.text.stage.2=成功了！这其中的要领就是使用金属板而不是锭来做盔甲，并将血腥教徒旗帜直接整合到套装中。在防护力方面，血腥邪徒盔甲与铁制盔甲相似但耐久略高，也更时髦。血腥法袍比我的神秘使法袍的防御能力更为卓越，但在引导 Vis 方面却比凡俗的盔甲要好得多。<BR>它们似乎由比神秘学黑暗的多的魔法制成。长时
附：建议对所有改动做一番彻查，这种错误能够出现暗示着存在更广更深的问题。本人精力有限，不再参与。

2021-04-18 02:22 UTC, zmaj11 commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.CRIMSON_ARMOR.text.stage.2=成功了！这其中的要领就是使用金属板而不是锭来做盔甲，并将血腥教徒旗帜直接整合到套装中。在防护力方面，血腥邪徒盔甲与铁制盔甲相似但耐久略高，也更时髦。血腥法袍比我的神秘使法袍的防御能力更为卓越，但在引导 Vis 方面却比凡俗的盔甲要好得多。<BR>它们似乎由比神秘学黑暗的多的魔法制成。长时
这个还真没注意到。。其他地方应该还好吧，我也不只是一个人翻译，有歧义的地方也问了很多

2021-04-18 02:38 UTC, TUsama requested changes
修了几处误译，但是也引进了很多误译，若无必要，下次不可再开如此 PR，这算是重复造轮子了，只需修复原先问题即可。
建议投长文本之前先自检一遍，因为很容易出错。还有昨天在群内的讨论，定从修饰错位，无法准确界定人称代词指代对象，这些都是基础问题。多做点阅读题，把语感再提一提，再来弄长文本吧。

2021-04-18 02:38 UTC, TUsama commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.CRIMSON_REVELATIONS.text.stage.1=虽然血腥教团的书大多数都是用难以理解的文字书写的，但其图案内包含的符号却暗示着我能破译的内容也许比我最初所想的要多。然而这并不表示翻译工作将是一件容易的事，但我也许知道该从哪开始了。<BR>在一番仔细观察后，我发现血腥教徒旗帜上的符号与某个神秘学印记极其相似，也许在我更深入的
分句为何要整合成长句？若无必要，不建议将句子翻译为长度超出 25 个字的句子，此为维基百科的翻译经验。

句中错误的标点记得修正。

2021-04-18 02:38 UTC, TUsama commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.ERYTHURGY.title=血腥学
crimson 是血腥，这里也是血腥？如无特定的同一性需求，此处最好另起一词，避免文义混淆。

2021-04-18 02:38 UTC, TUsama commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.CRIMSON_BLADE.text.stage.2=我这把血腥之刃正如那些邪教徒描述的一样，我都不用蹒跚地穿行于外域寻找了。任何被此剑击中的目标都会感到疲劳不堪且痛苦难耐，因为剑刃吸取了他们的力量。<BR>与我最初的设想不同，我用这把剑攻击敌人并没有获得力量或生命力。 相反，是这把剑本身似乎抽干了被攻击者的生命。 一想到到它窃取生命力可能
标点符号空格。

2021-04-18 02:38 UTC, TUsama commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.CRIMSON_BLADE.text.stage.1=血腥仪式描绘了一把自虚空所铸造的剑，它可以从持有者的敌人身上汲取力量和养料。据推测它处在异域迷宫的中心，只能通过开眼仪式才能获得。<BR>我可能因为并不够深谙神秘学，无法去外域找到这个武器。但是我所学已经足以让我做一个复制品了。
```suggestion
crimsonrevelations.research.CRIMSON_BLADE.text.stage.1=血腥仪式描绘了一把自虚空所铸造的剑，它可以从持有者的敌人身上汲取力量和养料。据推测它处在异域迷宫的中心，只能通过开眼仪式才能获得。<BR>我可能因为并不够深谙神秘学，无法去外域找到这个武器。但是我所学的已经足以让我做一个复制品了。
```

2021-04-18 02:38 UTC, TUsama commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.CRIMSON_ARMOR.text.stage.2=成功了！这其中的要领就是使用金属板而不是锭来做盔甲，并将血腥教徒旗帜直接整合到套装中。在防护力方面，血腥邪徒盔甲与铁制盔甲相似但耐久略高，也更时髦。血腥法袍比我的神秘使法袍的防御能力更为卓越，但在引导 Vis 方面却比凡俗的盔甲要好得多。<BR>它们似乎由比神秘学黑暗的多的魔法制成。长时
句意错误，原本是对的你给改歪了。

一个是“但是”之后，二个是“unsettling”，不是不适之意，而是心追惴惴不安之意，一个为肉体感受，一个为心理感受。

2021-04-18 02:38 UTC, TUsama commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.ERYTHURGY.text.stage.2=至少可以说，血腥学是粗野的，是一种类似于神秘学中那些特别基础理论的魔法，甚至无需理解魔法原理就能付诸应用。与需要智慧和实践的神秘学不同，血腥学使用了暴力的方法：常常以极其浪费的方式把海量的元始要素注满整个物品以此发生转化。<BR>仅管血腥学很粗俗，但它似乎能够做出一些被我所忽视的趣事。 我对“原
“inelegant”意指 Erythurgy 的理论色彩不及那种思辨程度高理论，因而不太具备理论美感。此处翻译为“粗野”“粗俗”均是误译，两词均指具体实践层面的行为，而不是理论层次的。

直接译为”Erythurgy并不优雅“更为确切，此处将理论美感艺术化。

2021-04-18 02:38 UTC, TUsama commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.ENTROPIC_PROCESSING.text.stage.1=血腥学使用大量的混沌能量将材料分解为较小的碎片。据我观察，这并非简单到能用手工完成，而是在流程中使用了大量的混沌能量使该过程更加高效，这对处理昂贵的材料非常有用。<BR>我尝试用此流程从普通花和大型花朵中提取更多染料，但显然手动制取染料也已经足够高效了。何况类似的结果同样能以
以防日后派上用场。

2021-04-18 02:38 UTC, TUsama commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.QUARTZ_PURIFICATION.text.stage.2=关键的见解看着简单得让人难以置信：石英不是金属，因此我在纯化时通常使用的 Metallum 必须用 Vitreus 代替以赋予它结晶的性质。原 Ordo 也要将其塑造得略有不同，但从我对血腥学了解，这是完全不必要的。诚然，时运附魔的存在使得此过程有些鸡肋。 不过，作为对我能力
“deceptively simple”意指“看上去很简单，似乎很简单”，此处应强调“看似”，而不是简单程度，原文已经很贴切，此处系超译。

2021-04-18 02:38 UTC, TUsama commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.QUARTZ_PURIFICATION.text.stage.1=我对 Ordo 的有了新见解后，也许是时候回到我早期在炼金术方面的尝试：金属原矿簇 了。我对大多数金属进行的实验都取得了成功，尽管我知道可以形成石英原矿簇，但我仍无法以相同的方法复现它们。也许研究其他原矿簇可以为我提供一些见解。
空格。

2021-04-18 03:28 UTC, zmaj11 commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.CRIMSON_REVELATIONS.text.stage.1=虽然血腥教团的书大多数都是用难以理解的文字书写的，但其图案内包含的符号却暗示着我能破译的内容也许比我最初所想的要多。然而这并不表示翻译工作将是一件容易的事，但我也许知道该从哪开始了。<BR>在一番仔细观察后，我发现血腥教徒旗帜上的符号与某个神秘学印记极其相似，也许在我更深入的
因为本来英文是整句

2021-04-18 03:38 UTC, zmaj11 commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.QUARTZ_PURIFICATION.text.stage.2=关键的见解看着简单得让人难以置信：石英不是金属，因此我在纯化时通常使用的 Metallum 必须用 Vitreus 代替以赋予它结晶的性质。原 Ordo 也要将其塑造得略有不同，但从我对血腥学了解，这是完全不必要的。诚然，时运附魔的存在使得此过程有些鸡肋。 不过，作为对我能力
因为以前看到有把这个翻译成特别简单的，还有把这个翻译成看着简单其实很难的

2021-04-18 03:42 UTC, zmaj11 commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.QUARTZ_PURIFICATION.text.stage.1=我对 Ordo 的有了新见解后，也许是时候回到我早期在炼金术方面的尝试：金属原矿簇 了。我对大多数金属进行的实验都取得了成功，尽管我知道可以形成石英原矿簇，但我仍无法以相同的方法复现它们。也许研究其他原矿簇可以为我提供一些见解。
那个原矿簇后的空格应该可以吧，怕会有歧义空的

2021-04-18 03:47 UTC, zmaj11 commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.ERYTHURGY.title=血腥学
刚看了一下西方的red意很鲜明，如果是这种委婉的殷感觉有欠缺

2021-04-18 03:48 UTC, zmaj11 commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.ERYTHURGY.title=血腥学
我这暂时先改成赤

2021-04-18 03:50 UTC, zmaj11 commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.ERYTHURGY.title=血腥学
red在在翻译中翻译成血的确实挺多..

2021-04-18 03:51 UTC, zmaj11 commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.ENTROPIC_PROCESSING.text.stage.1=血腥学使用大量的混沌能量将材料分解为较小的碎片。据我观察，这并非简单到能用手工完成，而是在流程中使用了大量的混沌能量使该过程更加高效，这对处理昂贵的材料非常有用。<BR>我尝试用此流程从普通花和大型花朵中提取更多染料，但显然手动制取染料也已经足够高效了。何况类似的结果同样能以
这个是？一般直接翻译都是以防万一

2021-04-18 03:57 UTC, zmaj11 commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.ERYTHURGY.text.stage.2=至少可以说，血腥学是粗野的，是一种类似于神秘学中那些特别基础理论的魔法，甚至无需理解魔法原理就能付诸应用。与需要智慧和实践的神秘学不同，血腥学使用了暴力的方法：常常以极其浪费的方式把海量的元始要素注满整个物品以此发生转化。<BR>仅管血腥学很粗俗，但它似乎能够做出一些被我所忽视的趣事。 我对“原
他这句翻译“不过，尽管它相当粗野”这句也是要改成不优雅吗

2021-04-19 03:37 UTC, TUsama commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.QUARTZ_PURIFICATION.text.stage.1=我对 Ordo 的有了新见解后，也许是时候回到我早期在炼金术方面的尝试：金属原矿簇 了。我对大多数金属进行的实验都取得了成功，尽管我知道可以形成石英原矿簇，但我仍无法以相同的方法复现它们。也许研究其他原矿簇可以为我提供一些见解。
在中文中，这种情况可以换标点符号，将冒号换为破折号，此处系语言体系标点符号用法不同所致。在《中华人民共和国国家标准GB/T15834-2011标点符号用法》中，冒号的用法有两种：总结上文和提示下文（例如这里就是一个标准的提示下文用法）。用于引出上文所说词语或句子的意思的标点符号还有破折号，破折号更适用与这种情况，因为此句为句内词语解释，并未分隔出上下句，因而使用冒号会出现你所说的疑虑。可以参看此例句：
>一个矮小而结实的日本中年人──内山老板走了过来。

此处就是破折号用作句内词语解释的一个例子。

2021-04-19 03:41 UTC, TUsama commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.ERYTHURGY.text.stage.2=至少可以说，血腥学是粗野的，是一种类似于神秘学中那些特别基础理论的魔法，甚至无需理解魔法原理就能付诸应用。与需要智慧和实践的神秘学不同，血腥学使用了暴力的方法：常常以极其浪费的方式把海量的元始要素注满整个物品以此发生转化。<BR>仅管血腥学很粗俗，但它似乎能够做出一些被我所忽视的趣事。 我对“原
不要将 inelegant 译为“粗俗”“粗野”即可。

2021-04-19 03:49 UTC, TUsama commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.CRIMSON_REVELATIONS.text.stage.1=虽然血腥教团的书大多数都是用难以理解的文字书写的，但其图案内包含的符号却暗示着我能破译的内容也许比我最初所想的要多。然而这并不表示翻译工作将是一件容易的事，但我也许知道该从哪开始了。<BR>在一番仔细观察后，我发现血腥教徒旗帜上的符号与某个神秘学印记极其相似，也许在我更深入的
英文整局并不意味着中文需要整句，适当的拆分才能更好的发挥中文的优势。一味的将大段从句式结构的英文翻译为中文，只会让人难以理解。
以下为新东方的例句：
> The annual migrations of wildfowl and many other animals certainly cannot be regarded as a form of exploration， because such movements are actually only shifts from one habitat to another for the purpose of avoiding seasonal climatic variations.

野生禽类和许多其他动物每年的迁徙，当然不能被看做是一种探险行为，因为，这些迁徙活动实际上只是从一个栖息地转移到另一个栖息地，以躲避气候的季节性变化。

可以看到，原文只有一个逗号作为分隔，翻译中却有 4 个逗号，只有如此的分句才能够使得这种长句的结构得以清晰的表述。如果将其全部混在一起，理解难度将会直线上升。

2021-04-19 04:17 UTC, TUsama commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.ERYTHURGY.title=血腥学
red 被译为血色、血红这种与血有关的词语极为正常的，这是词语自身意义滑动的正常现象，没有出现如此的翻译才不正常。

但是真正的问题在于，不是所有的 red 都可以被翻译成与血相关。因为，不只有血是红色的，血只是红色的众多意象中的一种，而不是其全部。例如，我会说：这个苹果是红色的，但不会说，这个苹果血红血红的，因为第二种描述将苹果的颜色引向了一个不太好的意象，与我们一贯的对于苹果的印象相悖。

如果从纯粹意象上谈论红色，我们还可以举出极多的例子。例如，红润的脸庞，苹果红，红彤彤的太阳，红花绿叶：高原人的红色脸庞，腮红，桃红......等等，这些意象数不胜数，但是我所举的这些都和血没有什么关系。

从这个角度出发，你可以理解为什么当初 TC 的译者会将 crimson 翻译为血腥了，因为血确实是红色的，或者说深红色的意象。而且这种意象带有一种邪恶的气息，这种邪恶的气息扎根于我们耳濡目染的诸多有关妖魔鬼怪，山精魍魉的故事。故事里，见血就说明有人受伤，是有某种邪性之物在作祟。因而这里翻译为血腥是有一定的合理性的。

但是关键在于，“代表了邪恶的红色”不一定只能是“血红色”，尤其是据我所知，TC 的邪术体系里压根就没有和血沾边的东西，在这里将 crimson 翻译为血腥是**完完全全的超译**，就连作者都没有用猩红这一单词，而是只是用 crimson 这一含蓄的，让人联想到略带邪性、不详的词来描述它们。对于翻译者而言，我们的任务不是要去试图揭示、放大出（如果有的话）这其中的邪性和不详，而是应该用同样含蓄的中文词汇来将其表述出来，这才是翻译的正确方式。

从这一角度来说，殷和腥和赤要好的，因为赤距离血，或者说不详的意象实在是有点远了，很多东西都可以用到赤这一词，但是殷和腥在日常中的用法不多，不太受到日常用语的污染。但是若单一个腥字，恐生歧义，让人以为是腥味，故或可用殷，但我觉得应该还有更好的字。

2021-04-19 04:43 UTC, zmaj11 commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.ERYTHURGY.title=血腥学
殷本意就不是表达颜色的，而且用殷表颜色的很少，目前我是没看到现代会光用个殷表颜色。。而且这算是多音字，读yan的时候才表颜色，这样更容易歧义吧

2021-04-19 04:50 UTC, zmaj11 commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.QUARTZ_PURIFICATION.text.stage.1=我对 Ordo 的有了新见解后，也许是时候回到我早期在炼金术方面的尝试：金属原矿簇 了。我对大多数金属进行的实验都取得了成功，尽管我知道可以形成石英原矿簇，但我仍无法以相同的方法复现它们。也许研究其他原矿簇可以为我提供一些见解。
感谢

2021-04-19 04:56 UTC, zmaj11 commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.ERYTHURGY.title=血腥学
【杜註】血色久則殷。殷，音近煙。今人以赤黑爲殷色。（找到了疑似起源

2021-04-19 04:56 UTC, zmaj11 commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.CRIMSON_REVELATIONS.text.stage.1=虽然血腥教团的书大多数都是用难以理解的文字书写的，但其图案内包含的符号却暗示着我能破译的内容也许比我最初所想的要多。然而这并不表示翻译工作将是一件容易的事，但我也许知道该从哪开始了。<BR>在一番仔细观察后，我发现血腥教徒旗帜上的符号与某个神秘学印记极其相似，也许在我更深入的
懂了

2021-04-19 08:51 UTC, TUsama commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.QUARTZ_PURIFICATION.text.stage.2=关键的见解看着简单得让人难以置信：石英不是金属，因此我在纯化时通常使用的 Metallum 必须用 Vitreus 代替以赋予它结晶的性质。原 Ordo 也要将其塑造得略有不同，但从我对血腥学了解，这是完全不必要的。诚然，时运附魔的存在使得此过程有些鸡肋。 不过，作为对我能力
翻译的时候还是要考虑清楚的，“看上去很简单，似乎很简单”并不意味着“看着简单其实很难的”，就好像是你看着一口井，黑洞洞的“看上去很深”，但是具体深不深只有进去才知道，你才能说“看上去很深实际上不深”或者“确实很深”。此处没有这么强的断言语气，断言是建立在实践之上的。

2021-04-20 07:03 UTC, TUsama commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.ERYTHURGY.title=血腥学
你可以找一个日常不怎么用的，单字还能表达深红色的字放上去，如果放上去效果不错，我可以考虑采纳。但你至今所提出的都是反对性质的方案，没有建设意义的方案，唯一一个“赤”又实在是距离日常使用太多而被污染了。魔法类模组切忌采用过于流俗的字，来表述其中的学科、机制、物品等，尤其是原文在英文中就比较雅的情况，用过于流俗常用的字套上去，无疑是使这个模组蒙羞。之前在群里和我辩了一个下午的那个人就是妥妥的反例。原文雅的给翻译成俗的，原文俗的给翻译成烂的。人文素养低下却不自知，可悲可叹。

2021-04-20 08:30 UTC, zmaj11 commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.ERYTHURGY.title=血腥学
您先别说这套雅，我先问您光看译文会怎么读？反正我到现在看着都想读yīn。尤其是说要跟神秘学对比，所以要加个秘，这导致别人根本联想不到颜色这方面。除非神秘叫紫秘黄秘的，这还可能。再引用一下《说文》的：殷，作乐之盛称殷。按，殷者，舞之容，殳者，舞之器。

2021-04-20 08:32 UTC, zmaj11 commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.ERYTHURGY.title=血腥学
我说先说几个可以表红的，再详说。赫，绯，朱，丹，彤，绛，赭，茜，缇，緅，纁，赯

2021-04-20 08:58 UTC, zmaj11 commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.ERYTHURGY.title=血腥学
赫，火赤貌/赫如渥赭。赫这个是火红，一般引申义都是宏大，明亮的，确实不太行。
绯，帛赤色也。绯最早是表深红的，后来也能表浅红，红，而且与衣服颜色有关，这和血腥教徒衣服颜色有联系，是个可选字。
朱确实是不能选的，毕竟表示高贵。
丹彤主要是表色的。
绛，大赤也。这个字是很好的，后用来表深红，可以写成绛术学（说起来神秘学其实是早有翻译的叫奇术学）或者渥绛学。渥表示厚，表示风寒病人出的汗，表示刑罚wù）确实有隐隐的不好之意。
赭，一般光表颜色或者是罪人（罪人的衣服颜色），这字是不行的。
茜，有指深红有指浅红，但是一般表示秀美生动。
缇，橘红，是是古代武士衣服的颜色。（莫名加上去了）
纁，浅降也。纁玄(浅绛色或黑色。古代以为象征天地之色)，纁黄(黄昏)，略有可取之处。
緅，青赤色。黑中红，一般也指衣服的颜色。
赯，赤色。一般用作脸色，并不可取。

2021-04-20 09:38 UTC, zmaj11 commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.ERYTHURGY.title=血腥学
目前觉得绛术好点

2021-04-20 10:01 UTC, zmaj11 commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.ERYTHURGY.title=血腥学
乍一看是降，再一看是绛。邪也有了红也有了，不存在读错，看清字了也不存在理解错意思。

2021-04-20 13:52 UTC, TUsama commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.ERYTHURGY.title=血腥学
有点明白为什么高版本会把 crimson 翻译成绯红了，确实有可取之处。
绛字不错，这一番讨论也算是增进见识了。现在的讨论重点可以从颜色到词的后缀上。若直接加个术，或让人不知道“绛术”指的是什么，“研究红色的术”？这个疑问是必然的，因为此处没有和 TC 原版的“血腥”有字面上的对应，所以也许可以叫“绛邪”之类的。当然这可能不是很好的方案，但我时间确实不太充足，你可以拿一个比较成熟的方案。

2021-04-20 14:08 UTC, zmaj11 commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.ERYTHURGY.title=血腥学
感觉这个问题不大，作者这构词ery-是红，-thurgy是工作（问一个大佬说这构词其实是错的），后面还有个俗称red magic的，直接说成红色的术感觉也不突兀。
ps:他的原话：这个词看起来像是 eruthrós 和 -ougrós 拼起来的，“进行红色的工作”，*-ourgós。但正常拼的话应该是 erythrurgy。

2021-04-20 14:29 UTC, zmaj11 commented on projects/1.12.2/assets/crimson-revelations/crimsonrevelations/lang/zh_cn.lang
> +crimsonrevelations.research.ERYTHURGY.title=血腥学
他建议我直接翻译成猩红术，可能有更好的翻译，但毕竟作者也是硬拼的，也不需要作太多考虑。

2021-04-21 09:32 UTC, merged