[R] 更新新生魔艺
CFPAOrg/Minecraft-Mod-Language-Package pull request #1104
Opened 2021-04-19 01:38 UTC by kappa-maintainer

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [x] 我已确定中文文件中没有未翻译的文本，如有以删除
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16.1/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-04-21 09:58 UTC, TUsama requested changes
一点点，之后再说。

2021-04-21 12:53 UTC, kappa-maintainer commented on projects/1.16/assets/ars-nouveau/ars_nouveau/patchouli_books/worn_notebook/zh_cn/entries/getting_started/beginning_spells.json
> +			"text":"可用魔符压印器合成的一级法术效果。使目标获得速度状态。可以尝试自身 -> 速度"
原文如此，不过还是加上吧

2021-04-21 12:55 UTC, kappa-maintainer commented on projects/1.16/assets/ars-nouveau/ars_nouveau/patchouli_books/worn_notebook/zh_cn/entries/getting_started/beginning_spells.json
> +			"text":"可用魔符压印器合成的一级法术增强。能增加大多数法术的强度。可以尝试使用弹射物 -> 破坏 -> 强化 -> 强化来破坏黑曜石，也可用于伤害来提高输出。"
原文中会把魔符图标和名称挂在页面上方，所以能偷懒。我再改改

2021-04-23 02:51 UTC, TUsama requested changes

2021-04-23 02:51 UTC, TUsama commented on projects/1.16/assets/ars-nouveau/ars_nouveau/patchouli_books/worn_notebook/zh_cn/entries/getting_started/expanded_casting.json
> +            "text": "你的魔力池可以变大，方法有特殊的法师盔甲、附魔、学习新魔符或者饮用药水。一旦你获得了魔力花种子，你就能进一步合成初学者法袍。法袍会显著增加你的施法能力。各类法袍都能使用你的魔力自我修复，而且还有较好的附魔能力。法袍还有不错的护甲值。"
原版词汇：盔甲值。

2021-04-23 02:51 UTC, TUsama commented on projects/1.16/assets/ars-nouveau/ars_nouveau/patchouli_books/worn_notebook/zh_cn/entries/getting_started/resources.json
> +            "text": "新生魔艺会在世界中生成多种资源，它们都有自身的魔法属性。地下可以发现带有魔力的宝石，但这些宝石也可以用结晶器可再生地产生。至高木有几种装饰性的变体，可以用于合成施法法杖。能在针叶林发现的魔源浆果丛，是合成魔力再生药水的关键。"
最后一句病句。

2021-04-23 02:51 UTC, TUsama commented on projects/1.16/assets/ars-nouveau/ars_nouveau/patchouli_books/worn_notebook/zh_cn/entries/machines/volcanic_accumulator.json
> +            "text": "附近掉落的烈焰至高木物品会被燃烧，并产生一块魔力，还会产生中等数量的$(item)热$()。"
为啥不用热量而只用热？

2021-04-23 02:51 UTC, TUsama commented on projects/1.16/assets/ars-nouveau/ars_nouveau/patchouli_books/worn_notebook/zh_cn/entries/resources/wilden.json
> +            "text": "荒野族裔是精通变形魔法的古老种族，它们的成员常常能在晚上发现，而且它们属于敌对生物。荒野守卫者可以在寒冷生物群系发现，但伏击者和兽群猎手能在任何群系发现。"
将被动改为主动是好的，但是没有添加主语就很不好了。

除此之外还有很多句子也是这样，这次就先不细抠语法问题了。

2021-04-23 02:51 UTC, TUsama commented on projects/1.16/assets/ars-nouveau/ars_nouveau/patchouli_books/worn_notebook/book.json
> +{
所以这个留着是意味着你还想继续攻关 book.json 的加载？

2021-04-23 03:23 UTC, kappa-maintainer commented on projects/1.16/assets/ars-nouveau/ars_nouveau/patchouli_books/worn_notebook/zh_cn/entries/getting_started/expanded_casting.json
> +            "text": "你的魔力池可以变大，方法有特殊的法师盔甲、附魔、学习新魔符或者饮用药水。一旦你获得了魔力花种子，你就能进一步合成初学者法袍。法袍会显著增加你的施法能力。各类法袍都能使用你的魔力自我修复，而且还有较好的附魔能力。法袍还有不错的护甲值。"
wiki中主要用的护甲值
https://minecraft.fandom.com/zh/wiki/%E7%9B%94%E7%94%B2

2021-04-23 03:24 UTC, kappa-maintainer commented on projects/1.16/assets/ars-nouveau/ars_nouveau/patchouli_books/worn_notebook/zh_cn/entries/machines/volcanic_accumulator.json
> +            "text": "附近掉落的烈焰至高木物品会被燃烧，并产生一块魔力，还会产生中等数量的$(item)热$()。"
忘改了

2021-04-23 03:41 UTC, kappa-maintainer commented on projects/1.16/assets/ars-nouveau/ars_nouveau/patchouli_books/worn_notebook/zh_cn/entries/resources/wilden.json
> +            "text": "荒野族裔是精通变形魔法的古老种族，它们的成员常常能在晚上发现，而且它们属于敌对生物。荒野守卫者可以在寒冷生物群系发现，但伏击者和兽群猎手能在任何群系发现。"
被原文束缚了。

2021-04-23 06:41 UTC, TUsama commented on projects/1.16/assets/ars-nouveau/ars_nouveau/patchouli_books/worn_notebook/zh_cn/entries/getting_started/expanded_casting.json
> +            "text": "你的魔力池可以变大，方法有特殊的法师盔甲、附魔、学习新魔符或者饮用药水。一旦你获得了魔力花种子，你就能进一步合成初学者法袍。法袍会显著增加你的施法能力。各类法袍都能使用你的魔力自我修复，而且还有较好的附魔能力。法袍还有不错的护甲值。"
我服了，我又看了看 wiki，盔甲值护甲值盔甲护甲都有，简直是花样百出，唯一相同的就是盔甲韧性。
按照这个思路的话，盔甲值-盔甲韧性可能是要比护甲值-盔甲韧性要更具被形式上的统一性。

2021-04-23 08:33 UTC, kappa-maintainer commented on projects/1.16/assets/ars-nouveau/ars_nouveau/patchouli_books/worn_notebook/zh_cn/entries/getting_started/expanded_casting.json
> +            "text": "你的魔力池可以变大，方法有特殊的法师盔甲、附魔、学习新魔符或者饮用药水。一旦你获得了魔力花种子，你就能进一步合成初学者法袍。法袍会显著增加你的施法能力。各类法袍都能使用你的魔力自我修复，而且还有较好的附魔能力。法袍还有不错的护甲值。"
个人更倾向于约定俗成叫护甲值，毕竟目前资源包只有MA是盔甲值，其他全是护甲值
至于这里的翻译，最终决定放弃翻成xx值

2021-04-23 08:34 UTC, TUsama commented on projects/1.16/assets/ars-nouveau/ars_nouveau/patchouli_books/worn_notebook/zh_cn/entries/getting_started/expanded_casting.json
> +            "text": "你的魔力池可以变大，方法有特殊的法师盔甲、附魔、学习新魔符或者饮用药水。一旦你获得了魔力花种子，你就能进一步合成初学者法袍。法袍会显著增加你的施法能力。各类法袍都能使用你的魔力自我修复，而且还有较好的附魔能力。法袍还有不错的护甲值。"
我找人问问那帮写 wiki 的。

2021-04-23 08:46 UTC, merged