[WIP] 自然灵气重译
CFPAOrg/Minecraft-Mod-Language-Package pull request #1105
Opened 2021-04-19 01:39 UTC by kappa-maintainer

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [x] 我已确定中文文件中没有未翻译的文本，如有以删除
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16.1/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-04-24 07:25 UTC, TUsama requested changes

2021-04-24 08:34 UTC, kappa-maintainer commented on projects/1.16/assets/natures-aura/naturesaura/patchouli_books/book/zh_cn/categories/items.json
> +    "description": "大自然的思绪可能会引导你前往沙滩、森林或者平原，但是有时它也会将你引导至到与自然本身紧密交织的物品和饰品。在本章节，你能找到这些物品。",
这个点确实纠结了很久，明天再看看

2021-04-24 08:36 UTC, kappa-maintainer commented on projects/1.16/assets/natures-aura/naturesaura/patchouli_books/book/zh_cn/entries/creating/animal_generator.json
> +            "text": "此外，一只动物活得$(thing)越久$()，产生的$(#419600)灵气$()增加得越多——而且十分显著，使得建造设备，来让动物们在被屠宰前活得久一点，更有利可图，也更高效。要收集最完整的动物灵魂，在动物诞生后需要等待大概$(thing)一个半小时$()。"
贴合原句式的后果。我有空把句子拆掉

2021-05-04 14:27 UTC, kappa-maintainer commented
明天会发review重点，顺便我再检查一遍一致性

2021-05-05 02:52 UTC, kappa-maintainer commented
疑难点：
Reaper of Ender Heights 译为末影高花收割机
Skyseeker 译为探天者
奥秘放大镜的神秘提示语
tainted gold 译为污染黄金是否恰当
A load of chunks 的双关
Mobproofius Lampus
Offering to gods
还有疑似因作者不会说人话在手册使用的一堆长句，总感觉会有一两句没译好

2021-05-10 11:00 UTC, kappa-maintainer commented on projects/1.16/assets/natures-aura/naturesaura/patchouli_books/book/zh_cn/entries/devices/item_distributor.json
> +            "text": "很久以前，非植物的科学家曾创造了对世界的一大贡献：$(item)物品分配器$()。但在今天，它远称不上好用。通过用设计需要的强度进行材料灌注，使得物品以设计好的模式移动，$(#419600)灵气$()便可以一转之前的难用的窘境了。$(br)$(item)物品分配器$()会从它$(thing)顶部$()的容器内抽取任何物品，"
相信我，Back in the day 真不是今天的意思

2021-05-12 00:33 UTC, TUsama commented on projects/1.16/assets/natures-aura/naturesaura/patchouli_books/book/zh_cn/entries/devices/item_distributor.json
> +            "text": "很久以前，非植物的科学家曾创造了对世界的一大贡献：$(item)物品分配器$()。但在今天，它远称不上好用。通过用设计需要的强度进行材料灌注，使得物品以设计好的模式移动，$(#419600)灵气$()便可以一转之前的难用的窘境了。$(br)$(item)物品分配器$()会从它$(thing)顶部$()的容器内抽取任何物品，"
艹，想当年。

2021-05-12 00:35 UTC, TUsama commented on projects/1.16/assets/natures-aura/naturesaura/patchouli_books/book/zh_cn/entries/devices/item_distributor.json
> +            "text": "很久以前，非植物的科学家曾创造了对世界的一大贡献：$(item)物品分配器$()。但在今天，它远称不上好用。通过用设计需要的强度进行材料灌注，使得物品以设计好的模式移动，$(#419600)灵气$()便可以一转之前的难用的窘境了。$(br)$(item)物品分配器$()会从它$(thing)顶部$()的容器内抽取任何物品，"
不过句意上差距并没有很大，大抵上还是在说当初很好用现在拉了之类的。

2021-05-12 01:29 UTC, kappa-maintainer commented on projects/1.16/assets/natures-aura/naturesaura/patchouli_books/book/zh_cn/entries/devices/item_distributor.json
> +            "text": "很久以前，非植物的科学家曾创造了对世界的一大贡献：$(item)物品分配器$()。但在今天，它远称不上好用。通过用设计需要的强度进行材料灌注，使得物品以设计好的模式移动，$(#419600)灵气$()便可以一转之前的难用的窘境了。$(br)$(item)物品分配器$()会从它$(thing)顶部$()的容器内抽取任何物品，"
原文应该是说当年不好用，现在有灵气就好用了

2021-05-14 11:23 UTC, TUsama commented
你改一改那个Back in the day，我实在是进不去你的 PR。

2021-05-15 02:41 UTC, merged