[R]新增战术框架2
CFPAOrg/Minecraft-Mod-Language-Package pull request #1108
Opened 2021-04-23 16:16 UTC by CopyDoge

- [ ] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [ ] 我已确定中文文件中没有未翻译的文本，如有以删除
- [ ] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）
- [ ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16.1/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [ ] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [ ] 我已上传英文文件以供审查；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)
模组未被Curseforge收录，ModID为自起(tactical-frame-2)
额外上传日文文件以供审查(源语言)

2021-04-24 01:54 UTC, TUsama requested changes

2021-04-24 01:54 UTC, TUsama commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.shieldfire=副手装备时，降低15％的伤害，并具有火焰耐性
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

除却枪支名字，其余文本中非中文和中文的相接出请务必保持一个空格的距离。

还有请自查一下文本中的非中文标点符号问题。

2021-04-24 01:54 UTC, TUsama commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +advancement.craftMachinestation=这家伙・・・要动了！
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

这三个点不符合中文标点符号习惯，请使用小键盘下方的那个点，并输入六个点构成省略号。

2021-04-24 01:54 UTC, TUsama commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +gui.arsfurnace=Ars 炉
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

此处？

2021-04-24 01:54 UTC, TUsama commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +gui.mechadock.time=直到修理完成 %1$s:0%2$s
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

这是什么意思？

2021-04-24 06:05 UTC, CopyDoge commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +gui.mechadock.time=直到修理完成 %1$s:0%2$s
后面一串是绑定的时间，倒计时一类的

2021-04-24 06:06 UTC, CopyDoge commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +gui.arsfurnace=Ars 炉
游戏中尚未出现的东西，无从推测原意

2021-04-28 12:14 UTC, TUsama commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +gui.mechadock.time=直到修理完成 %1$s:0%2$s
那应为“剩余时间”之类的吧。

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.energydrink=越喝越有效果
建议改为“喝的越多，效果越好！”

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.shieldfire=副手装备时，降低 15% 的伤害，并具有火焰耐性
“火焰耐性”建议改为“防火效果”

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.stat.attackScore=攻击比分
Score 统一一下吧，要么全是比分，要么全是得分。

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +entity.TF80E.name=TF-80E Ego=θ 西塔
这上面几条后面的中文是干啥的= =

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +entity.mechaItem=变回物品
建议改为“回收机甲”

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +entity.mechaLevel=提升等级（消耗机甲等级一半的级数）
原文中好像并没有后面括号中的内容。

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +entity.gynoidTrade=完整
建议改为“完成”

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +entity.gynoidTrade=完整
建议改为“完成”

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +advancement.craftCFR12.desc=制作一个 a CFR-12
机翻痕迹（

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +death.attack.cheinsaw=%1$s电锯惊魂！%2$s
这样翻译游戏内显示效果不会是“A电锯惊魂！B”吗？改一改吧。

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.mission1.txt9=我欢迎你
不符合中文表达习惯，就一句“欢迎！”即可。

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.mission2.txt2=如你所知，我们与突然出现的神秘机器人陷入战争状态。
建议改为“我们正处于与突然出现且隶属不明的无人机交战的状态。”

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.mission2.txt3=军队有必要在城市的防御上花费大部分战斗力，没有进攻的战斗力
建议改为“军方目前正在评估情况并保卫设施，所以我们不能派太多的人过来。”

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.mission2.txt4=你们外援出场了想让你们以报酬为代价，成为游击的战斗力
这句与日语原文完全不符合，建议改为“所以，军方要求你们雇佣兵一起完成一项任务。”

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.mission2.txt7=开始作战吧
建议改为“打起精神，开始作战吧！”

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.mission2.txt9=在我的附近移动的话，就会得到恢复，请有效利用
建议改为“靠近我，以便我可以协助你。请有效利用。”

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.mission2.txt10=新手对不起，请您帮我看
日语原文：新手だ！気を付けてくれ！
前面的 新手だ！目前不知道是什么意思，但是后面的 気を付けてくれ！是小心！的意思。

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.mission2.txt11=敌军的增援似乎没有了，只剩下一点。
建议改为“撤退.....了？”

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.mission2.txt12=周边地区敌人部队无反应。作战成功了。
建议改为“......不对！”

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.mission2.txt15=我们前往那边的掩护!对不起，这边请!
上面几行的标点符号应该改成全角

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.mission3.txt8=所有单位，开始前进！不要错过一架飞机！
建议改为“所有单位，开始前进！不要错过任何一架飞机！”

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.mission3.txt7=不允许失败。我指望着你。
建议改为“不允许失败。拜托了。”

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.mission3.txt6=多平台通过操作来推翻发电厂内部。
不符合原文，但是以我的水平翻译不来，不好意思（

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.mission3.txt9=还有很多敌人。保持紧张。
“保持紧张。”建议改为“不要掉以轻心。”

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.mission3.txt11=确认敌人加固。
不符日语原文

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.mission3.txt10=就是这样。你会来的。
后面不符日语原文

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.mission3.txt12=这里的援军也来了。请忍受。
建议改为“我们的援军也快来了，坚持住！”

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.mission3.txt13=坦克小队，我们加入了。我们将开始支持。
与原文不符

2021-05-03 12:59 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.mission3.txt17=我完成了我的工作请求。你不介意我是否退却。
与原文不符

2021-05-09 10:23 UTC, baka-gourd commented
@CopyDoge

2021-05-09 11:20 UTC, CopyDoge commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +entity.TF80E.name=TF-80E Ego=θ 西塔
好念

2021-05-09 11:21 UTC, CopyDoge commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +entity.mechaItem=变回物品
在游戏中有表达不明确的缺点

2021-05-09 11:23 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +entity.TF80E.name=TF-80E Ego=θ 西塔
我个人建议要么保留 β 啥的，要么保留中文。

2021-05-09 11:23 UTC, liuseniubi commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +entity.mechaItem=变回物品
那就“将机甲变回物品”?

2021-05-09 11:25 UTC, CopyDoge commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +entity.mechaItem=变回物品
该按钮出现在机甲状态的GUI上

2021-05-09 11:33 UTC, CopyDoge commented
任务方面的文本大部分都未出现在游戏中，基本沿用第一稿翻译未加检查，这次改了一半使其更通顺，但并没有全部重新翻译，部分文本依然有明显的翻译体特征。

2021-05-10 01:20 UTC, TUsama commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +entity.mechaItem=变回物品
变回物品无问题。

2021-05-10 01:21 UTC, TUsama commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +entity.mechaLevel=提升等级（消耗机甲等级一半的级数）
移除括号内内容，译者没有义务也没有必要给原文添加一些可能会随着版本更替而改变的话。

2021-05-10 01:21 UTC, TUsama commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +entity.gynoidTrade=完整
此处没改是为何？

2021-05-10 01:22 UTC, TUsama commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.mission4.txt8=看起来没有更多的了。我们这里也很快就修理结束了
更改的译文更为准确。

2021-05-10 01:23 UTC, TUsama commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.mission2.txt1=你是协助这次作战的佣兵
建议无问题，且更符合中文语气。

2021-05-10 01:24 UTC, TUsama commented on projects/1.12.2/assets/tactical-frame-2/tf2/lang/lang/zh_cn.lang
> +tf.mission2.txt2=如你所知，我们与突然出现的神秘机器人陷入战争状态。
“神秘机器人”可能会发生歧义，如果确认这里指的是所属派系的不明确，那么使用“隶属不明”是最为准确的。

2021-05-10 01:25 UTC, TUsama commented
剩余最后几条，搞定之后就可以入库了。

2021-05-11 02:51 UTC, TUsama approved these changes

2021-05-11 02:51 UTC, merged