[R]1.16/整改气动工艺的翻译问题
CFPAOrg/Minecraft-Mod-Language-Package pull request #1112
Opened 2021-05-02 14:12 UTC by dovisutu

是整改还是肃清？
问题很有可能没找完.jpg

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [x] 我已确定中文文件中没有未翻译的文本，如有以删除
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16.1/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-05-02 15:10 UTC, WuzgXY-GitHub requested changes
LPG 还没改好呢。:(
星宇百分之两百机翻了，可以整体重制

2021-05-02 15:10 UTC, WuzgXY-GitHub commented on projects/1.16/assets/pneumaticcraft-repressurized/pneumaticcraft/lang/zh_cn.json
>      "gui.tooltip.block.pneumaticcraft.drone_interface": "一个允许使用 ComputerCraft 或 OpenComuputers 对无人机进行交互的方块。",
|Feedback Priority|
|---|
|🌫 Dust / Non-blocking, “take it or leave it”|

建议把所有模组名全翻译了

2021-05-02 15:10 UTC, WuzgXY-GitHub commented on projects/1.16/assets/pneumaticcraft-repressurized/pneumaticcraft/lang/zh_cn.json
>      "gui.tooltip.block.pneumaticcraft.flux_compressor": "将 FE能量（与RF和许多其他Mod的能量兼容）转换为压缩空气。其基础效率为 40%%，也即，消耗 100FE 才能产生 40mL 压缩空气。速度升级将略微降低这一效率。${br}此压缩机会产生热量，必须将其散热以避免效率损失。",
|Feedback Priority|
|---|
|🌫 Dust / Non-blocking, “take it or leave it”|

数值与单位间必须有空格；要么将《指北》贯彻到底，要么不要加空格

2021-05-02 15:10 UTC, WuzgXY-GitHub commented on projects/1.16/assets/pneumaticcraft-repressurized/pneumaticcraft/lang/zh_cn.json
>      "gui.tooltip.block.pneumaticcraft.refinery": "精炼厂用来将一种流体精炼为不同的流体；默认情况下，石油被处理为柴油、煤油、汽油和/或 LPG（液化石油气（。${br}${br}需要堆叠 2，3 或 4 个精炼厂输出端方块才可以工作；在堆叠 4 个时精炼的效果最好。施加的热量越多，精炼厂运行的速度越快。",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

所有 LPG 统一为液化石油气，不要保留这三个字母

2021-05-02 15:10 UTC, WuzgXY-GitHub commented on projects/1.16/assets/pneumaticcraft-repressurized/pneumaticcraft/lang/zh_cn.json
>      "pneumaticcraft.gui.logistics_frame.matchModId.tooltip": "勾选以将来自同一 mod 的物品视为等价",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

ＭＯＤ MOD Mod mod 模组
你选一个，然后全改好

2021-05-02 15:34 UTC, dovisutu commented on projects/1.16/assets/pneumaticcraft-repressurized/pneumaticcraft/lang/zh_cn.json
>      "pneumaticcraft.gui.logistics_frame.matchModId.tooltip": "勾选以将来自同一 mod 的物品视为等价",
全部修改为了模组（除非又找漏了）

2021-05-03 07:39 UTC, WuzgXY-GitHub approved these changes

2021-05-03 07:39 UTC, WuzgXY-GitHub commented on projects/1.16/assets/pneumaticcraft-repressurized/pneumaticcraft/lang/zh_cn.json
> +    "gui.tooltip.block.pneumaticcraft.electric_compressor": "将工业时代2的 EU 转化为压缩空气。像其他工业2的机器一样，可以用工业2的扳手正常交互。",
时代？

2021-05-03 07:39 UTC, WuzgXY-GitHub commented on projects/1.16/assets/pneumaticcraft-repressurized/pneumaticcraft/lang/zh_cn.json
> -    "gui.tooltip.item.pneumaticcraft.chips": "美味的小吃。如果你喜欢叫他们薯条。",
这行现在没了吗

2021-05-03 07:39 UTC, WuzgXY-GitHub commented on projects/1.16/assets/pneumaticcraft-repressurized/pneumaticcraft/lang/zh_cn.json
>      "pneumaticcraft.gui.tooltip.maxPressure": "最大气压:%s bar",
:：

2021-05-03 09:48 UTC, dovisutu commented on projects/1.16/assets/pneumaticcraft-repressurized/pneumaticcraft/lang/zh_cn.json
> -    "gui.tooltip.item.pneumaticcraft.chips": "美味的小吃。如果你喜欢叫他们薯条。",
原文似乎是英式英语与美式英语的差异，此处的翻译完全没有传达这一点；但是我没想到一个比较好的翻译，所以这里就先删掉了

2021-05-15 11:51 UTC, merged