[R] 为 Skinned Lanterns 添加翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #1135
Opened 2021-05-12 03:46 UTC by N-Wither

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [x] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [ ] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-05-12 05:12 UTC, TUsama requested changes

2021-05-12 05:12 UTC, TUsama commented on projects/1.16/assets/skinned-lanterns/skinnedlanterns/lang/zh_cn.json
> +  "block.skinnedlanterns.ghost_lantern_block": "Ghost 灯笼",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

这些为何没有翻译？

2021-05-12 06:31 UTC, Lyaiya commented
遵循原版颜色的翻译，浅灰色、浅蓝色的**浅**要改为**淡**

2021-05-12 08:41 UTC, N-Wither commented on projects/1.16/assets/skinned-lanterns/skinnedlanterns/lang/zh_cn.json
> +  "block.skinnedlanterns.ghost_lantern_block": "Ghost 灯笼",
Ghost, Blinky等等都是《吃豆人》里面小怪的名字，我没找到它们的翻译，所以保留了原文

2021-05-12 15:06 UTC, TUsama commented on projects/1.16/assets/skinned-lanterns/skinnedlanterns/lang/zh_cn.json
> +  "block.skinnedlanterns.ghost_lantern_block": "Ghost 灯笼",
还请麻烦展示一下这个模组和《吃豆人》之间的逻辑关联。如果这个是作者故意引入《吃豆人》中的材质的话，那么还请贴一下截图之类的。

2021-05-13 00:50 UTC, Lyaiya commented on projects/1.16/assets/skinned-lanterns/skinnedlanterns/lang/zh_cn.json
> +  "block.skinnedlanterns.ghost_lantern_block": "Ghost 灯笼",
![image](https://user-images.githubusercontent.com/9733114/118061609-d3e81c00-b3c7-11eb-9a73-72601a932b92.png)

维基上的资料

2021-05-13 02:04 UTC, Lyaiya commented on projects/1.16/assets/skinned-lanterns/skinnedlanterns/lang/zh_cn.json
> +  "block.skinnedlanterns.pinky_soul_lantern_block": "粉色鬼魂灵魂灯笼",
虽然这里不需要严格对应原版十六色，但我建议改为粉红色

2021-05-13 04:21 UTC, TUsama commented on projects/1.16/assets/skinned-lanterns/skinnedlanterns/lang/zh_cn.json
> +  "block.skinnedlanterns.pinky_soul_lantern_block": "粉色鬼魂灵魂灯笼",
是可以改，但是粉红色并无任何做修改的必要，这个离开了语境之后只是单纯的 taste 的问题，不能把这种 taste 的问题转化为原则或者类原则或者潜在原则意义上的规定问题。

2021-05-13 04:27 UTC, TUsama commented on projects/1.16/assets/skinned-lanterns/skinnedlanterns/lang/zh_cn.json
> +  "block.skinnedlanterns.pinky_soul_lantern_block": "粉色鬼魂灵魂灯笼",
你得把 taste 的问题和原则上的问题分清楚。不在mc原版语境下你任何的“建议”“要求”实际上都是或强或弱的干涉别人翻译风格的想法，这种想法是建基在mc原版翻译为任何模组的翻译的主心轴的预设之下。你自己也清楚这个观点的问题在哪里，你也不希望被别人干涉你的 taste，所以我建议在这种情况下你还是要考虑清楚要不要给别人建议。或者说，你给建议，你得把你的建议的理由一并给出来。

2021-05-13 04:47 UTC, Lyaiya commented on projects/1.16/assets/skinned-lanterns/skinnedlanterns/lang/zh_cn.json
> +  "block.skinnedlanterns.pinky_soul_lantern_block": "粉色鬼魂灵魂灯笼",
不是原则问题，因为其他三个词（Blinky, Inky, Clyde）在**英文原文不相关**的情况下向原版翻译靠拢了，而唯独与 pink 相近的 pinky 却翻译成**粉色**，不会显得有些奇怪吗？如果其他三个词不是原版译法，我当然不会提出这种建议，以后会注意提出建议时给出相应的理由。

2021-05-13 10:14 UTC, TUsama commented on projects/1.16/assets/skinned-lanterns/skinnedlanterns/lang/zh_cn.json
> +  "block.skinnedlanterns.pinky_soul_lantern_block": "粉色鬼魂灵魂灯笼",
这个解释不错，那我赞同你的建议。

2021-05-15 03:32 UTC, merged