[WIP] BuildCraft 小改｜1.12
CFPAOrg/Minecraft-Mod-Language-Package pull request #1161
Opened 2021-05-21 18:20 UTC by Lyaiya

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [x] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [ ] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

---

不知道这样删多余的语言文件会不会出问题。

基于原先**非 1UNKNOWN** 目录下的语言文件进行修改。

## 改动

- Transport Pipe：管道 -> 物品管道
- 去掉x质字段
- 小改成就文本
- 统一用词

2021-05-22 03:16 UTC, baka-gourd commented
1.12不建议改动了，没大量错误就不要动了。删除的可以另说

2021-05-22 04:05 UTC, Lyaiya commented
其实主要的就是删除多余的文件，翻译只是顺带的。

2021-05-23 04:39 UTC, TUsama requested changes

2021-05-23 04:39 UTC, TUsama commented on projects/1.12.2/assets/additional-pipes-for-buildcraft/additionalpipes/lang/zh_cn.lang
> +gui.teleport.ledger.title=已链接的管道
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

我不太确定这里用“链接”可不可以，你可以查一查链接的意思。

2021-05-23 05:06 UTC, Lyaiya commented on projects/1.12.2/assets/additional-pipes-for-buildcraft/additionalpipes/lang/zh_cn.lang
> +gui.teleport.ledger.title=已链接的管道
连接和链接的区别不太大，不过这里还是采用连接吧

2021-05-23 08:11 UTC, merged