[R] 更新新生魔艺至模组版本1.18｜1.16
CFPAOrg/Minecraft-Mod-Language-Package pull request #1165
Opened 2021-05-30 04:52 UTC by kappa-maintainer

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [x] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-05-31 04:43 UTC, TUsama requested changes

2021-05-31 04:43 UTC, TUsama commented on projects/1.16/assets/ars-nouveau/ars_nouveau/patchouli_books/worn_notebook/zh_cn/entries/resources/archwood.json
> +            "text": "至高木在任何生物群系都有小概率生成，而且有 4 种类型。在罕见情况下，你还可能会碰到一片充满魔法生物、自然光源和至高木的至高木森林。至高木可以用于装饰、仪式和制作法杖。"
我总觉得这个“充满了......”这一句是动词搭配不当，你要不拆句算了。

2021-05-31 15:46 UTC, kappa-maintainer commented on projects/1.16/assets/ars-nouveau/ars_nouveau/patchouli_books/worn_notebook/zh_cn/entries/resources/archwood.json
> +            "text": "至高木在任何生物群系都有小概率生成，而且有 4 种类型。在罕见情况下，你还可能会碰到一片充满魔法生物、自然光源和至高木的至高木森林。至高木可以用于装饰、仪式和制作法杖。"
我改改

2021-06-01 03:34 UTC, TUsama commented
这个“满是”用的很不错。

2021-06-01 03:34 UTC, TUsama approved these changes

2021-06-01 10:03 UTC, kappa-maintainer commented
爬虫居然干活了
需要我手动resolve吗

2021-06-01 15:42 UTC, baka-gourd commented
是的

2021-06-02 02:00 UTC, merged