[M] 更新 Create Crafts & Additions。
CFPAOrg/Minecraft-Mod-Language-Package pull request #1167
Opened 2021-05-30 13:44 UTC by liuseniubi

- [ ] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [ ] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [ ] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [ ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [ ] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [ ] 我已上传英文文件以供审查；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-05-31 04:30 UTC, TUsama requested changes

2021-05-31 04:30 UTC, TUsama commented on projects/1.16/assets/createaddition/createaddition/lang/zh_cn.json
> +	"deprecated.block.createaddition.rolling_mill.tooltip.summary": "一个用于_轧制_输入的_物品_的动力机器。能被侧面连接的传动杆驱动。产物必须从此机器提取出来。",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

> 产物必须从此机器提取出来

是什么意思？不提取出来就无法继续工作？

2021-05-31 04:30 UTC, TUsama commented on projects/1.16/assets/createaddition/createaddition/lang/zh_cn.json
> +	"deprecated.block.createaddition.rolling_mill.tooltip.condition2": "当右键时",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

“右击”不是“右键”，其他的自己改。

2021-05-31 04:30 UTC, TUsama commented on projects/1.16/assets/createaddition/createaddition/lang/zh_cn.json
> +	"block.createaddition.heater.engine_heating_disabled": "驱动熔炼引擎已在配置中被禁用。",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

本体中，为“熔炉引擎”。

2021-05-31 04:30 UTC, TUsama commented on projects/1.16/assets/createaddition/createaddition/lang/zh_cn.json
> +	"block.createaddition.connector.tooltip.summary": "用_线缆_连接 FE 方块来传输 _FE_。用_铜线轴_或_金线轴_右键两个_连接器_来建立_线缆连接_。",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

考虑到create可能的问题，你最好在游戏里看看，在 _ 前加上空格还会不会引发加粗失效的问题。这个问题在之前似乎讨论过，但是你最好再确认一次。

2021-05-31 04:30 UTC, TUsama commented on projects/1.16/assets/createaddition/createaddition/lang/zh_cn.json
> +	"block.createaddition.redstone_relay.tooltip.summary": "当接收到红石信号时，允许 _FE _从_输入端连接器_传递到_输出端连接器_。",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

此处为何只有一边有空格？

2021-05-31 04:30 UTC, TUsama commented on projects/1.16/assets/createaddition/createaddition/lang/zh_cn.json
> +	"create.ponder.alternator.text_1": "交流发电机需要至少 32 转/分的转速才能工作。",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

单位不建议翻译。

2021-05-31 04:54 UTC, liuseniubi commented on projects/1.16/assets/createaddition/createaddition/lang/zh_cn.json
> +	"block.createaddition.connector.tooltip.summary": "用_线缆_连接 FE 方块来传输 _FE_。用_铜线轴_或_金线轴_右键两个_连接器_来建立_线缆连接_。",
![image](https://user-images.githubusercontent.com/67419568/120141519-3be39280-c20f-11eb-8914-4f753e3bbeda.png)
加空格不会，但是转行会有问题。

2021-05-31 04:55 UTC, liuseniubi commented on projects/1.16/assets/createaddition/createaddition/lang/zh_cn.json
> +	"deprecated.block.createaddition.rolling_mill.tooltip.summary": "一个用于_轧制_输入的_物品_的动力机器。能被侧面连接的传动杆驱动。产物必须从此机器提取出来。",
已修改。

2021-05-31 04:56 UTC, liuseniubi commented on projects/1.16/assets/createaddition/createaddition/lang/zh_cn.json
> +	"deprecated.block.createaddition.rolling_mill.tooltip.condition2": "当右键时",
已修改。

2021-05-31 04:56 UTC, liuseniubi commented on projects/1.16/assets/createaddition/createaddition/lang/zh_cn.json
> +	"block.createaddition.heater.engine_heating_disabled": "驱动熔炼引擎已在配置中被禁用。",
已修改。

2021-05-31 04:57 UTC, liuseniubi commented on projects/1.16/assets/createaddition/createaddition/lang/zh_cn.json
> +	"block.createaddition.redstone_relay.tooltip.summary": "当接收到红石信号时，允许 _FE _从_输入端连接器_传递到_输出端连接器_。",
空格加错地方了（

2021-05-31 04:57 UTC, liuseniubi commented on projects/1.16/assets/createaddition/createaddition/lang/zh_cn.json
> +	"create.ponder.alternator.text_1": "交流发电机需要至少 32 转/分的转速才能工作。",
已修改。

2021-05-31 05:00 UTC, liuseniubi commented on projects/1.16/assets/createaddition/createaddition/lang/zh_cn.json
> +	"block.createaddition.connector.tooltip.summary": "用_线缆_连接 FE 方块来传输 _FE_。用_铜线轴_或_金线轴_右键两个_连接器_来建立_线缆连接_。",
已修改。

2021-05-31 05:22 UTC, TUsama commented on projects/1.16/assets/createaddition/createaddition/lang/zh_cn.json
> +	"block.createaddition.connector.tooltip.summary": "用_线缆_连接 FE 方块来传输 _FE_。用_铜线轴_或_金线轴_右键两个_连接器_来建立_线缆连接_。",
其他的换行检查过了吗？

2021-05-31 05:24 UTC, TUsama approved these changes

2021-05-31 05:30 UTC, liuseniubi commented
麻烦先别 merge，等晚上检查完换行后再 commit 一次。

2021-06-01 14:46 UTC, liuseniubi commented on projects/1.16/assets/createaddition/createaddition/lang/zh_cn.json
> +	"block.createaddition.connector.tooltip.summary": "用_线缆_连接 FE 方块来传输 _FE_。用_铜线轴_或_金线轴_右键两个_连接器_来建立_线缆连接_。",
最新的文件换行的地方检查过了，没问题。

2021-06-01 15:42 UTC, merged