[R] 军团要塞2模组汉化
CFPAOrg/Minecraft-Mod-Language-Package pull request #1173
Opened 2021-06-08 03:24 UTC by SummonHIM

- [X] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [ ] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [X] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [X] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [X] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [X] 我已上传英文文件以供审查；
- [X] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-06-09 09:27 UTC, TUsama requested changes

2021-06-09 09:38 UTC, SummonHIM commented
好的 多谢指教 我在去游戏里看看吧

2021-06-15 09:24 UTC, SummonHIM commented on projects/1.12.2/assets/tf2-stuff-mod/rafradek_tf2_weapons/lang/zh_cn.lang
> +container.currency=金钱： %1$s
已修改

2021-06-15 09:24 UTC, SummonHIM commented on projects/1.12.2/assets/tf2-stuff-mod/rafradek_tf2_weapons/lang/zh_cn.lang
> +gui.markedit=你就是了。使用近战武器攻击一位生物/玩家以通过。
已修改

2021-06-15 09:24 UTC, SummonHIM commented on projects/1.12.2/assets/tf2-stuff-mod/rafradek_tf2_weapons/lang/zh_cn.lang
> +gui.boss.statue=该物品必须在雕像上使用（杰克灯笼的头，黑曜石的身体，干草的胳膊和腿）
已修改

2021-06-15 09:41 UTC, SummonHIM commented on projects/1.12.2/assets/tf2-stuff-mod/rafradek_tf2_weapons/lang/zh_cn.lang
> +effect.it=It
查到现在也没查出是什么
我翻了翻[源代码](https://github.com/rafradek/Mods/blob/master/tf2/src/main/java/rafradek/TF2weapons/TF2weapons.java#L745)，似乎是激活了冲锋之后的效果。不过我怎么冲锋都调不出来。或许是crit?

2021-06-15 12:02 UTC, TUsama approved these changes

2021-06-16 01:09 UTC, merged