[R]Decocraft 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #1184
Opened 2021-06-23 06:20 UTC by mcBegins2Snow

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [x] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 是 1.12 翻译，应该是：`projects/1.12.2/assets/decocraft/props/lang/zh_cn.lang `
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

由于此次修改改动幅度很大，需要review。
其中“Quixy”和“Scalemate”找不到合适的译名，需要协助。

2021-06-25 07:01 UTC, TUsama requested changes

2021-06-25 07:01 UTC, TUsama commented on projects/1.12.2/assets/decocraft/props/lang/zh_cn.lang
> +item.props.couch_center_black.name=沙发（中间丨黑色）
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

但此处为（位置｜颜色），是否需要统一？

2021-06-25 07:08 UTC, TUsama commented on projects/1.12.2/assets/decocraft/props/lang/zh_cn.lang
> +item.props.borje_chair_light_black.name=博尔杰椅（浅色丨黑色）
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

这个“浅色”是何物？两个颜色并列是指椅子有两个分开的颜色吗？

2021-06-25 08:49 UTC, mcBegins2Snow commented on projects/1.12.2/assets/decocraft/props/lang/zh_cn.lang
> +item.props.borje_chair_light_black.name=博尔杰椅（浅色丨黑色）
浅色代表家具的木质部分的深浅，从深到浅分别是“黑色、深色、中色、浅色、沙滩色、白色”

2021-06-25 08:50 UTC, mcBegins2Snow commented on projects/1.12.2/assets/decocraft/props/lang/zh_cn.lang
> +item.props.couch_center_black.name=沙发（中间丨黑色）
当时是按照英文名各个单词从左到右翻译的，并不需要统一

2021-06-25 08:51 UTC, mcBegins2Snow commented on projects/1.12.2/assets/decocraft/props/lang/zh_cn.lang
> +item.props.canopy_bed_black_left.name=天篷床（黑色丨左）
绿色的修改后部分已经改了，审查有误？

2021-06-25 09:08 UTC, TUsama commented on projects/1.12.2/assets/decocraft/props/lang/zh_cn.lang
> +item.props.canopy_bed_black_left.name=天篷床（黑色丨左）
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

此处为（颜色｜位置）。

2021-06-25 09:09 UTC, TUsama commented on projects/1.12.2/assets/decocraft/props/lang/zh_cn.lang
> +item.props.canopy_bed_black_left.name=天篷床（黑色丨左）
此处是和下面那个问题连在一起的。

2021-06-25 09:59 UTC, mcBegins2Snow commented on projects/1.12.2/assets/decocraft/props/lang/zh_cn.lang
> +item.props.canopy_bed_black_left.name=天篷床（黑色丨左）
已修改

2021-06-25 10:00 UTC, mcBegins2Snow commented on projects/1.12.2/assets/decocraft/props/lang/zh_cn.lang
> +item.props.couch_center_black.name=沙发（中间丨黑色）
已把竖杠换成逗号，除了创造模式物品栏标题

2021-06-28 01:05 UTC, mcBegins2Snow commented
@TUsama 已完成修改，都等了好几天了。

2021-06-28 03:29 UTC, merged