[R]space-bosstools: 添加翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #1186
Opened 2021-06-25 09:12 UTC by paperchalice

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [x] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [ ] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-06-25 13:27 UTC, dovisutu requested changes
进行了一点极为粗略的审核，需要后续跟进
此外，还有模组的译名问题：
`space-bosstool`
说实话，看不出这里有什么“强力”的地方...考虑询问一下作者？

2021-06-25 13:27 UTC, dovisutu commented on projects/1.16/assets/space-bosstools/boss_tools/lang/zh_cn.json
> +  "advancements.workbench_advancement.descr": "§建造一个NASA工作台",
分节符标志的原版格式符不完整
此外，“建造”与“合成”的语义存在较大差异，从工作台/其余的各种机器得到产物应为合成/制造而非建造（后者多指搭建多方块结构

2021-06-25 13:27 UTC, dovisutu commented on projects/1.16/assets/space-bosstools/boss_tools/lang/zh_cn.json
> +  "biome.boss_tools.moon_biom": "Moon Biome",
为何该条目不进行翻译？是不可翻译的索引吗？
下面部分条目同理

2021-06-26 09:11 UTC, dovisutu requested changes

2021-06-26 09:11 UTC, dovisutu commented on projects/1.16/assets/space-bosstools/boss_tools/lang/zh_cn.json
> +  "entity.boss_tools.rocket": "Rocket",
此项还未补上翻译
```suggestion
  "entity.boss_tools.rocket": "火箭",
```

2021-06-26 09:11 UTC, dovisutu commented on projects/1.16/assets/space-bosstools/boss_tools/lang/zh_cn.json
> +  "block.boss_tools.block_of_blue_iron_plating": "蓝带镀层铁块",
为什么这里和下面都是`iron plating`，但实际翻译不一样（镀层铁块 <> 铁板块）？是游戏中性质完全不同吗？

2021-06-26 09:12 UTC, dovisutu commented
（还有，不用每次都 force push 上来，一个pr中含有多个 commit 是可以接受的）

2021-06-26 14:42 UTC, dovisutu commented on projects/1.16/assets/space-bosstools/boss_tools/lang/zh_cn.json
> +  "block.boss_tools.block_of_blue_iron_plating": "蓝带镀层铁块",
ping @paperchalice

2021-06-27 01:15 UTC, paperchalice commented on projects/1.16/assets/space-bosstools/boss_tools/lang/zh_cn.json
> +  "block.boss_tools.block_of_blue_iron_plating": "蓝带镀层铁块",
已修改

2021-06-27 07:25 UTC, dovisutu approved these changes
差不多可以了

2021-06-28 03:55 UTC, closed without merging

2021-06-28 04:03 UTC, TUsama commented on projects/1.16/assets/space-bosstools/boss_tools/lang/zh_cn.json
> +  "death.attack.oxygen": "%1$s 无法呼吸",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

原文   "death.attack.oxygen": "%1$s couldn't breathe anymore",
所以应为：再也无法呼吸了