[M]techreborn: 同步上游翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #1188
Opened 2021-06-26 11:08 UTC by paperchalice

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [x] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [ ] 我已上传英文文件以供审查；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-06-27 07:28 UTC, dovisutu commented
请问这个“上游”是哪里？是官库吗？

2021-06-27 07:29 UTC, paperchalice commented
> 请问这个“上游”是哪里？是官库吗？

见 https://github.com/TechReborn/TechReborn/blob/1.17/src/main/resources/assets/techreborn/lang/translations.txt

2021-06-28 03:42 UTC, TUsama commented
直接标 M 是？这个文本是 100% 没有问题吗？

2021-06-28 03:43 UTC, TUsama commented
下次同步官库翻译请自行校对问题。如果只是单纯的搬运，是没有任何意义的。

2021-06-28 03:45 UTC, closed without merging

2021-06-28 03:54 UTC, TUsama requested changes

2021-06-28 03:54 UTC, TUsama commented on projects/1.16/assets/techreborn/techreborn/lang/zh_cn.json
> +  "techreborn.tooltip.fusion_coil": "右键聚变控制计算机来自动安装",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

右击

2021-06-28 03:54 UTC, TUsama commented on projects/1.16/assets/techreborn/techreborn/lang/zh_cn.json
> +  "techreborn.message.coordsHaveBeen": "坐标以设置为",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "techreborn.message.coordsHaveBeen": "坐标已设置为",

```

2021-06-28 03:54 UTC, TUsama commented on projects/1.16/assets/techreborn/techreborn/lang/zh_cn.json
> +  "techreborn.message.info.block.techreborn.lv_transformer": "中低能量级",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

这里指的是电压转换吗？

2021-06-28 03:54 UTC, TUsama commented on projects/1.16/assets/techreborn/techreborn/lang/zh_cn.json
> +  "techreborn.message.info.block.techreborn.chemical_reactor": "用两种化学品构成新的产品",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "techreborn.message.info.block.techreborn.chemical_reactor": "用两种化学品相互反应，形成新产品。",

```

2021-06-28 03:54 UTC, TUsama commented
下次提交至少把这部分更正。