[R][W][WIP]以前弄的血魔法汉化
CFPAOrg/Minecraft-Mod-Language-Package pull request #1191
Opened 2021-06-29 07:35 UTC by xslingcn

大约二月份和朋友一起搞的汉化，第一次知道这么一个本地化仓库，提交一下， 请批判吸收XD
大部分名称对照mcmod物品名进行翻译。

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [ ] 我已确定中文文件中没有未翻译的文本，如有已删除；
- 共有四个物品名未翻译，依照仓库内现文件格式保留英文文本。
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-06-30 11:23 UTC, dovisutu commented
> 依照仓库内现文件格式保留英文文本

虽然不知道原文本怎么回事，但是实际上未翻译文本应当把翻译文件中的对应条目删去...当然，放在这里讨论一下也未尝不可
不过如果是没有合适的翻译而保留原文这种可以保留


此外，粗略地看了一下，请将翻译文本中的半角符号改为全角（这里有进行全角符号宽度的修复，所以一般而言格式不会乱掉）
当然，如果改掉后格式有问题或者观感不好的可以说明后保留

2021-07-02 04:20 UTC, xslingcn commented
> 虽然不知道原文本怎么回事，但是实际上未翻译文本应当把翻译文件中的对应条目删去...

> 此外，粗略地看了一下，请将翻译文本中的半角符号改为全角（这里有进行全角符号宽度的修复，所以一般而言格式不会乱掉）

Done.

2021-07-08 13:59 UTC, TUsama commented
冒昧问一下，你们之前玩mc是从来没用过自动汉化吗（

2021-07-08 14:07 UTC, TUsama requested changes
好像参照了我的放在仓库里的翻译。。。

2021-07-08 14:07 UTC, TUsama commented on projects/1.16/assets/blood-magic/bloodmagic/lang/zh_cn.json
> +    "ritual.bloodmagic.animalGrowthRitual.growing.info": "（成长） 该区域内的动物将成长得更快。",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

请统一标点符号。

2021-07-08 14:07 UTC, TUsama commented on projects/1.16/assets/blood-magic/bloodmagic/lang/zh_cn.json
> +    "ritual.bloodmagic.featheredKnifeRitual.vengeful.info": "将牺牲的最小生命值设为10%%.覆盖【坚毅】的效果",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

存留标点未更改为全角的情况，请自查。

2021-07-08 14:35 UTC, TUsama commented
上新了书籍的翻译，还麻烦你把lang里面的印记的tolltips和书籍里的统一一下（

2021-07-08 18:57 UTC, xslingcn commented on projects/1.16/assets/blood-magic/bloodmagic/lang/zh_cn.json
> +    "ritual.bloodmagic.animalGrowthRitual.growing.info": "（成长） 该区域内的动物将成长得更快。",
在 [1.12版本的官方仓库汉化](https://github.com/WayofTime/BloodMagic/blob/1.12/src/main/resources/assets/bloodmagic/lang/zh_CN.lang#L702) 中原译者采用了这种分别使用“【”和“（”的翻译方式，我们参考的时候就照搬下来了。
所以我再确认一下是否需要更改。

2021-07-08 18:59 UTC, xslingcn commented on projects/1.16/assets/blood-magic/bloodmagic/lang/zh_cn.json
> +    "ritual.bloodmagic.featheredKnifeRitual.vengeful.info": "将牺牲的最小生命值设为10%%.覆盖【坚毅】的效果",
Done at [7423df26c9e445eead3fc779521e15b23f370074](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1191/commits/7423df26c9e445eead3fc779521e15b23f370074)

2021-07-08 19:32 UTC, xslingcn commented
> 上新了书籍的翻译，还麻烦你把lang里面的印记的tolltips和书籍里的统一一下（

Done at [475349d](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1191/commits/475349d6c5da0f74c719ebe7b58094c615429126).



> 好像参照了我的放在仓库里的翻译。。。

是，在[93f7445](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1191/commits/93f7445d74b3d766c7b436c7fe0977b69e5c7814)中参照仓库里的翻译修改了一些我这自认为弄得比较生硬的条目。

2021-07-09 02:16 UTC, TUsama commented on projects/1.16/assets/blood-magic/bloodmagic/lang/zh_cn.json
> +    "ritual.bloodmagic.animalGrowthRitual.growing.info": "（成长） 该区域内的动物将成长得更快。",
英文文件如何处理，你如何处理就行了。

2021-07-09 02:24 UTC, TUsama commented
那个括号的问题我问一问当初的原译者，不急。

2021-07-09 02:38 UTC, TUsama requested changes

2021-07-09 02:38 UTC, TUsama commented on projects/1.16/assets/blood-magic/bloodmagic/lang/zh_cn.json
> +    "item.bloodmagic.ritualdivinerdusk": "仪式推测仗【薄暮】",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

错别字。

2021-07-09 02:38 UTC, TUsama commented on projects/1.16/assets/blood-magic/bloodmagic/lang/zh_cn.json
> +    "item.bloodmagic.ritualtinkerer": "仪式调整钳",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

这个在游戏里是钳子吗？

2021-07-09 02:38 UTC, TUsama commented on projects/1.16/assets/blood-magic/bloodmagic/lang/zh_cn.json
> +    "ritual.bloodmagic.lavaRitual.lavaRange.info": "（岩浆）仪式放置岩浆方块的区域。",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

按照mc原版译名，此处应为“熔岩”。

2021-07-09 02:38 UTC, TUsama commented on projects/1.16/assets/blood-magic/bloodmagic/lang/zh_cn.json
> +    "living_upgrade.bloodmagic.arrow_shot": "技巧弹射",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

请参考[mcmod页面中的](https://www.mcmod.cn/item/48727.html)译名进行更正。
同时还麻烦测试一下饿殍遍野的效果，我觉得这个译名很有可能是误译。

好像就只有这一个不是哎。。。能说说为啥你这个不沿用mcmod上的译名吗？

2021-07-09 06:59 UTC, xslingcn commented on projects/1.16/assets/blood-magic/bloodmagic/lang/zh_cn.json
> +    "item.bloodmagic.ritualtinkerer": "仪式调整钳",
大概是[这个样子](https://minecraftguides.net/BM/user/pages/07.tier-4/07.ritual-tinkerer/consume%20will.jpg)。

2021-07-09 07:21 UTC, xslingcn commented on projects/1.16/assets/blood-magic/bloodmagic/lang/zh_cn.json
> +    "item.bloodmagic.ritualdivinerdusk": "仪式推测仗【薄暮】",
Fixed in [8726c0d](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1191/commits/8726c0d852fc11156cc8f5a9b699005b6ffd81d0).

2021-07-09 07:22 UTC, xslingcn commented on projects/1.16/assets/blood-magic/bloodmagic/lang/zh_cn.json
> +    "ritual.bloodmagic.lavaRitual.lavaRange.info": "（岩浆）仪式放置岩浆方块的区域。",
Fixed in [53f18f6](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1191/commits/53f18f6b148526666b535f4f0810b5c31f64846c).

2021-07-09 07:40 UTC, TUsama commented on projects/1.16/assets/blood-magic/bloodmagic/lang/zh_cn.json
> +    "item.bloodmagic.ritualtinkerer": "仪式调整钳",
直接调整器比较好，因为原文确实没有体现出钳子的意思。

从形态上来看，除非这个东西是可以像钳子那样有闭合中间钳住东西的能力，否则说是钳子有点牵强了。

2021-07-09 07:45 UTC, xslingcn commented on projects/1.16/assets/blood-magic/bloodmagic/lang/zh_cn.json
> +    "living_upgrade.bloodmagic.arrow_shot": "技巧弹射",
已在 [ba46916](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1191/commits/ba469161350fd167a3881ec2fea04e9f79e71373) 中对照mcmod进行修正。
看了下应该是有五个都和mcmod里的翻译有些许差别，最开始我们也搞得比较随意，可能没查到对应的就自己造了一个安上去了（

> 同时还麻烦测试一下饿殍遍野的效果，我觉得这个译名很有可能是误译。

看了一下，[它的效果](https://minecraftguides.net/BM/tier-5/penance-of-the-leadened-soul-creates-downgrades)是每秒给一个exhaustion，表现出来就是更快地降低饱食度。

另外那个“针插”（Pin Cushion）应该也是望文生义出来的，有些莫名其妙，效果是[提供弓箭保护](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/projects/1.16/assets/blood-magic/bloodmagic/patchouli_books/guide/zh_cn/entries/alchemy_array/living_equipment/armor_upgrades/pin_cushion.json#L8)，可以讨论下换用什么翻译比较好。

2021-07-09 07:53 UTC, xslingcn commented on projects/1.16/assets/blood-magic/bloodmagic/lang/zh_cn.json
> +    "item.bloodmagic.ritualtinkerer": "仪式调整钳",
Ok.

2021-07-09 08:01 UTC, TUsama commented on projects/1.16/assets/blood-magic/bloodmagic/lang/zh_cn.json
> +    "living_upgrade.bloodmagic.arrow_shot": "技巧弹射",
Battle Hungry  涌动饥渴
Pin Cushion  箭芒消涣

2021-07-09 08:12 UTC, xslingcn commented on projects/1.16/assets/blood-magic/bloodmagic/lang/zh_cn.json
> +    "living_upgrade.bloodmagic.arrow_shot": "技巧弹射",
Done at commit [f214d76](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1191/commits/f214d76542563a41e2e7ad623195818ba411740a).

2021-07-16 11:17 UTC, xslingcn commented
> 那个括号的问题我问一问当初的原译者，不急。

想问下有后续了吗

2021-07-16 12:54 UTC, TUsama commented
没有（半恼）

2021-07-18 12:48 UTC, merged