[R] Add translation for Charcoal Pit 2, Advanced Rocketry, Project Rankine, Stone Age
CFPAOrg/Minecraft-Mod-Language-Package pull request #1193
Opened 2021-07-01 00:58 UTC by yuesha-yc

- [ ] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [ ] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [ ] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [ ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [ ] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [ ] 我已上传英文文件以供审查；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-07-08 13:59 UTC, TUsama requested changes
错漏较多，抓紧更正。这个是第一部分。

2021-07-08 13:59 UTC, TUsama commented on projects/1.16/assets/advanced-rocketry/advancedrocketry/lang/zh_cn.json
> +  "item.advancedrocketry.platetitaniumiridium": "钛铱合金 板",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

请移除多余空格。

2021-07-08 13:59 UTC, TUsama commented on projects/1.16/assets/advanced-rocketry/advancedrocketry/lang/zh_cn.json
> +  "achievement.feeltheheat": "感受热!",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

请检查文中标点符号是否为中文标点。如果你是从1.12.2的文件升级上来的，那么肯定是有一些漏网之鱼的。这个文件我最近几天也摸过。

2021-07-08 13:59 UTC, TUsama commented on projects/1.16/assets/charcoal_pit/lang/zh_cn.json
> +  "block.charcoal_pit.light_blue_pot": "浅蓝色陶罐",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

根据mc原版，此处应为“淡蓝色”。下方同理。

2021-07-08 13:59 UTC, TUsama commented on projects/1.16/assets/charcoal_pit/lang/zh_cn.json
> +  "item.charcoal_pit.nether_brick_item": "生下面的砖",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

错别字？并且 key 中也没有 unfire。

2021-07-08 13:59 UTC, TUsama commented on projects/1.16/assets/charcoal_pit/lang/zh_cn.json
> +  "item.charcoal_pit.alcohol_bottle.effect.chorus_cider": "Chorus苹果酒瓶",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

为原版的“紫颂”系列植物。

2021-07-08 13:59 UTC, TUsama commented on projects/1.16/assets/charcoal_pit/lang/zh_cn.json
> +  "item.charcoal_pit.alcohol_bottle.effect.sweetberry_wine": "甜莓酒瓶",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

请遵循原版译名。

2021-07-08 13:59 UTC, TUsama commented on projects/1.16/assets/charcoal_pit/lang/zh_cn.json
> +  "item.charcoal_pit.alcohol_bottle.effect.vodka": "伏特加瓶",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

此处为何没有“酒”字？

2021-07-08 13:59 UTC, TUsama commented on projects/1.16/assets/charcoal_pit/lang/zh_cn.json
> +  "item.charcoal_pit.alcohol_bottle.effect.honey_dewois": "蜂蜜Dewois瓶",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

此处存疑，留待考证。可用文本为：
> Vodka which gives resistance and Honey Dewois, the elixir of the Dwarves which grants haste.

[网址](https://www.curseforge.com/minecraft/mc-mods/charcoal-pit?__cf_chl_jschl_tk__=d787b08261510ad39d644e92c1cc58d0e1be3b95-1625751810-0-ASmoNKET-_AXDF0nSawvrpAE0d0ZZGm5JyNv496PHdYse4iGzoh3gTdyNXWunDm3OfF1fMjOaAuDHfT0-EoU4tUgKkxw_3juoOhijKGBUHUhFUNsyP6KDGP5EiPzf_XoN1cGZx30XsTyG2UtYZ14DKQ4lUUCpbRiCI9WXn6RK5pYXAxO4dhpFZxS2X_CE6fl9xtLhvAutDGAjWczw9m72uFL8Ii8MmV1ipLxVKPdlr-s9_y5tmZudHpDupL9P_LMz6IlqZKyotmSwo686HqjeZrX6q7YOiCc5HoeUjFVexodvSbR4aghKSROPTsc3kJ2z_xrmZi2xoG1bfTR1MNjaOTMbV-LiIclncFoqnre0HslpF7OfhWnzmfKnJ_4nW-h9us00BKLSisr2w_kg7TnHcKtgaGhFvqJToHsjro_hnhT3YThW5XuaHnJfuw5IxJAgSOPwWz2s8PODhsrtk2u3ZQ3lTIf0tGOeCf2Xih46CBmEOBQztcCO3CgmAb6UyPJyw)

2021-07-08 13:59 UTC, TUsama commented on projects/1.16/assets/charcoal_pit/lang/zh_cn.json
> +  "fluid.charcoal_pit.creosote_still": "杂酚油油",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

多字。

2021-07-08 13:59 UTC, TUsama commented on projects/1.16/assets/charcoal_pit/lang/zh_cn.json
> +  "effect.charcoal_pit.roulette": "随机药水效果",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

译名不妥当，请直译保留原文的象征意味。

2021-07-08 13:59 UTC, TUsama commented on projects/1.16/assets/charcoal_pit/lang/zh_cn.json
> +  "advancements.charcoal_pit.fire_starter.title": "猴子生火!",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

同样需要自查标点符号。

2021-07-08 13:59 UTC, TUsama commented on projects/1.16/assets/charcoal_pit/lang/zh_cn.json
> +  "advancements.charcoal_pit.aeternalis.title": "比Irene的还好",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

不确定这里是不是指的是和平女神。

2021-07-08 13:59 UTC, TUsama commented on projects/1.16/assets/charcoal_pit/lang/zh_cn.json
> +  "advancements.charcoal_pit.aeternalis.description": "如果你足够幸运，或者足够执着，就能在末地城里找到永恒遗迹",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

relic 在这里指代的是什么？

2021-07-08 13:59 UTC, TUsama commented on projects/1.16/assets/charcoal_pit/lang/zh_cn.json
> +  "advancements.charcoal_pit.cheese.title": "Gromit,奶酪!棒极了!",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

可以参照相关影视作品音译。

2021-07-08 13:59 UTC, TUsama commented on projects/1.16/assets/charcoal_pit/lang/zh_cn.json
> +  "advancements.charcoal_pit.kernels.title": "陈腔滥调",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

此处与它的 desc 我都不是很明白，能解释一下吗？

2021-07-08 13:59 UTC, TUsama commented on projects/1.16/assets/charcoal_pit/lang/zh_cn.json
> +  "advancements.charcoal_pit.fugu.title": "什么可能出错?",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "advancements.charcoal_pit.fugu.title": "啥东西可能会出错？",
```

2021-07-08 13:59 UTC, TUsama commented on projects/1.16/assets/charcoal_pit/lang/zh_cn.json
> +  "advancements.charcoal_pit.leek.description": "从一只鸡收集韭菜，鸭子也可?",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

这是什么意思？

2021-07-08 13:59 UTC, TUsama commented on projects/1.16/assets/charcoal_pit/lang/zh_cn.json
> +  "charcoal_pit.instruction.place_kiln": "拿着原料shift+右键在地上放置窑/花窑",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

请使用“右击”而不是“右键”。

2021-07-09 03:02 UTC, TUsama requested changes
标点问题自检，不标注了。

2021-07-09 03:02 UTC, TUsama commented on projects/1.16/assets/rankine/lang/zh_cn.json
> +  "enchantment.rankine.daze.desc": "使目标获得缓慢效果，完美攻击会增强效果",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

它这个指的是不是等待攻击冷却完了之后的挥击？

2021-07-09 03:02 UTC, TUsama commented on projects/1.16/assets/rankine/lang/zh_cn.json
> +  "itemGroup.rankine_world": "Project Rankine建筑",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

请使用标准格式。
```suggestion
  "itemGroup.rankine_world": "Project Rankine｜建筑",
```

2021-07-09 07:12 UTC, dovisutu requested changes

2021-07-09 07:12 UTC, dovisutu commented on projects/1.16/assets/advanced-rocketry/advancedrocketry/lang/zh_cn.json
> +  "death.attack.vacuum": "%1$s死于减压",
下列死亡信息中`死于xx`与`因xx而死亡`格式混杂，需要统一

2021-07-27 03:18 UTC, WuzgXY-GitHub commented on projects/1.16/assets/advanced-rocketry/advancedrocketry/lang/zh_cn.json
> +  "item.advancedrocketry.platetitaniumiridium": "钛铱合金 板",
对，1.16 这边高火不再需要这种空格了。旧版也能用某些方式修复。

2021-07-27 03:19 UTC, WuzgXY-GitHub commented on projects/1.16/assets/charcoal_pit/lang/zh_cn.json
> +  "charcoal_pit.instruction.place_kiln": "拿着原料shift+右键在地上放置窑/花窑",
「按住 Shift 右击」

2021-07-27 03:20 UTC, WuzgXY-GitHub commented on projects/1.16/assets/rankine/lang/zh_cn.json
> +  "itemGroup.rankine_world": "Project Rankine建筑",
模组名能翻译就翻译呗，兰金计划/项目什么的，结合模组内容

2021-08-17 12:44 UTC, closed without merging