[R] Inspirations 翻译补全及修改
CFPAOrg/Minecraft-Mod-Language-Package pull request #1203
Opened 2021-07-13 14:24 UTC by Lyaiya

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [x] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-07-16 13:03 UTC, TUsama requested changes

2021-07-16 13:03 UTC, TUsama commented on projects/1.16/assets/inspirations/inspirations/lang/zh_cn.json
> +  "jei.inspirations.cauldron.cool": "炼药锅不能沸腾",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

我总觉得有点怪，虽然在口语中好像是可以这么表达的。

2021-07-16 13:03 UTC, TUsama commented on projects/1.16/assets/inspirations/inspirations/lang/zh_cn.json
> +  "item.inspirations.dimension_compass.pos.tooltip": "%s 在 (%s, %s)",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

这里的语序可以修改吧。用%1$s排序。
还有标点记得改。

2021-07-17 10:11 UTC, Lyaiya commented on projects/1.16/assets/inspirations/inspirations/lang/zh_cn.json
> +  "block.inspirations.plain_mulch": "覆盖物",
能在上面种植物，但不能种树苗。

2021-07-17 10:19 UTC, Lyaiya commented on projects/1.16/assets/inspirations/inspirations/lang/zh_cn.json
> +  "item.inspirations.dimension_compass.pos.tooltip": "%s 在 (%s, %s)",
这里要修改语序吗，比如说下界位于（某坐标）。这词条实际游戏也没找到，找源码也没有。

2021-07-18 12:40 UTC, TUsama commented on projects/1.16/assets/inspirations/inspirations/lang/zh_cn.json
> +  "item.inspirations.dimension_compass.pos.tooltip": "%s 在 (%s, %s)",
那算了。

2021-07-18 12:41 UTC, merged