[R] RFTools子组件RFTools Power的汉化
CFPAOrg/Minecraft-Mod-Language-Package pull request #1206
Opened 2021-07-18 11:04 UTC by Lava-er

- [ ] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [ ] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [ ] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [ ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [ ] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [ ] 我已上传英文文件以供审查；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-07-18 12:45 UTC, TUsama approved these changes

2021-07-21 11:37 UTC, TUsama requested changes

2021-07-21 11:37 UTC, TUsama commented on projects/1.16/assets/rftools-power/rftoolspower/lang/zh_cn.json
> +  "message.rftoolspower.blazing_generator.gold": "加成：更多发电量",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

可以问一下这个到底是什么机制吗？是向机器注入能量还是搓升级卡插入之类的。

因为在 https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/26c4263b78e843d50af2295d6342d1d163818444#diff-e32427e3de5b508cb2fa450a9fa5dfd65e84a41024f65ed8277f9137d549b6a4R216 中也有类似的字段，这个 commit 的内容也是由其他玩家提供的。但是你们的翻译是完全不一样的，你这边是“加成”，那边是“注能升级”，所以我想知道到底这个机制是怎么工作的，搞清楚之后再统一用语。

还有，可能有一些是应该统一的，但是我没注意到的字段，还麻烦你也检查一下，因为我没怎么玩过 RFt。

2021-07-21 11:37 UTC, TUsama commented on projects/1.16/assets/rftools-power/rftoolspower/lang/zh_cn.json
> +  "message.rftoolspower.powercell_card.info": "链接： ",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

请修改为中文标点，并移除多余空格。

2021-07-23 08:36 UTC, Lava-er commented on projects/1.16/assets/rftools-power/rftoolspower/lang/zh_cn.json
> +  "message.rftoolspower.blazing_generator.gold": "加成：更多发电量",
是使用机器注能器（ https://www.mcmod.cn/item/9417.html ）对 RFt 中大部分机器进行一个加成（消耗空间碎片） 的确是“注能升级”更加准确 的确是我的疏忽

2021-07-27 01:27 UTC, merged