[WIP,W]更新了xaeros-minimap
CFPAOrg/Minecraft-Mod-Language-Package pull request #1209
Opened 2021-07-23 10:08 UTC by the-eric-kwok

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [x] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)
文件已提交到 xaero 的 repo （见[这里](https://github.com/thexaero/Better-PVP-Translations/pull/14#pullrequestreview-713384152)），正在等待 review。将根据作者的反馈及时进行调整，并将调整部分汇入此处。

2021-07-27 02:23 UTC, TUsama requested changes

2021-07-27 02:23 UTC, TUsama commented on projects/1.16/assets/xaeros-minimap/xaerobetterpvp/lang/zh_cn.json
> +  "gui.xaero_initial": "首字母",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

可以讲一下这个按钮有什么用吗？

2021-07-27 02:23 UTC, TUsama commented on projects/1.16/assets/xaeros-minimap/xaerobetterpvp/lang/zh_cn.json
> +  "gui.xaero_howto_select": "左键选择一个界面。",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

请将所有“左键”“右键”更改为“左击”“右击”。

2021-07-27 02:23 UTC, TUsama commented on projects/1.16/assets/xaeros-minimap/xaerobetterpvp/lang/zh_cn.json
> +  "gui.xaero_press_c": "(按下 C)",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

英文标点记得修改。

2021-07-27 02:23 UTC, TUsama commented on projects/1.16/assets/xaeros-minimap/xaerobetterpvp/lang/zh_cn.json
> +  "gui.xaero_hp_setting": "健康值低提醒",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

生命值。

2021-07-27 02:23 UTC, TUsama commented on projects/1.16/assets/xaeros-minimap/xaerobetterpvp/lang/zh_cn.json
> +  "gui.xaero_explosion_setting": "苦力怕预警",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

爬行者。

2021-07-27 02:23 UTC, TUsama commented on projects/1.16/assets/xaeros-minimap/xaerobetterpvp/lang/zh_cn.json
> +  "gui.xaero_being_shot_setting": "骷髅怪预警",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "gui.xaero_being_shot_setting": "骷髅预警",
```

2021-07-27 02:23 UTC, TUsama commented on projects/1.16/assets/xaeros-minimap/xaerobetterpvp/lang/zh_cn.json
> +  "gui.xaero_purple": "亮紫色",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
  "gui.xaero_purple": "浅紫色",
```

2021-07-27 02:23 UTC, TUsama commented on projects/1.16/assets/xaeros-minimap/xaerobetterpvp/lang/zh_cn.json
> +  "gui.xaero_used_seed": "使用种子:",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

标点。

2021-07-27 02:23 UTC, TUsama commented on projects/1.16/assets/xaeros-minimap/xaerobetterpvp/lang/zh_cn.json
> +  "gui.xaero_compass_scale": "地图上罗盘文字尺寸",
```suggestion
  "gui.xaero_compass_scale": "地图上指南针文字尺寸",
```

2021-08-25 00:03 UTC, the-eric-kwok commented on projects/1.16/assets/xaeros-minimap/xaerobetterpvp/lang/zh_cn.json
> +  "gui.xaero_initial": "首字母",
将列表内项目按首字母排序

2021-10-02 05:15 UTC, baka-gourd commented
因长期未活动，暂时关闭

2021-10-02 05:15 UTC, closed without merging