[R] AE2 官中搬运及修缮
CFPAOrg/Minecraft-Mod-Language-Package pull request #1214
Opened 2021-07-27 07:14 UTC by Lyaiya

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [x] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-07-27 13:14 UTC, TUsama requested changes

2021-07-27 13:14 UTC, TUsama commented on projects/1.16/assets/applied-energistics-2/appliedenergistics2/lang/zh_cn.json
> +  "gui.appliedenergistics2.SpatialAnchorAll": "正在分析：%d 个区块存在于 %d 世界",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

这两句能解释一下吗？空间锚我没有在mcmod上查到这个东西，所以也是不知道有什么用。

2021-07-27 13:14 UTC, TUsama commented on projects/1.16/assets/applied-energistics-2/appliedenergistics2/lang/zh_cn.json
> +  "gui.appliedenergistics2.StoredPower": "已存储能源：%s",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

能量还是能源？

2021-07-27 13:14 UTC, TUsama commented on projects/1.16/assets/applied-energistics-2/appliedenergistics2/lang/zh_cn.json
> +  "stat.appliedenergistics2.items_extracted": "物品已从ME存储取出",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

似为“已从ME存储中取出的物品”，这个是统计数据吧。

2021-07-27 13:14 UTC, TUsama commented on projects/1.16/assets/applied-energistics-2/appliedenergistics2/lang/zh_cn.json
> +  "theoneprobe.appliedenergistics2.p2p_unlinked": "未链接",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

我记得你上次查了资料，说链接连接均可，我自己又翻了一下，没找到相关的资料，能给个网址吗？

2021-07-27 13:14 UTC, TUsama commented on projects/1.16/assets/applied-energistics-2/appliedenergistics2/lang/zh_cn.json
> +  "waila.appliedenergistics2.Channels": "%1$d / %2$d 个频道",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

为何数字与/之间要空格？

2021-07-27 13:58 UTC, Lyaiya commented on projects/1.16/assets/applied-energistics-2/appliedenergistics2/lang/zh_cn.json
> +  "theoneprobe.appliedenergistics2.p2p_unlinked": "未链接",
connection 有“连接”意思，link 既有“链接”也有“连接”的意思，所以我就想着做一下区分。

但我再查了下[词典资料](http://www.chinabianjiao.com/info-100041.html)和[计算机方面的解释](https://bbs.csdn.net/topics/70386648)，可能是我理解错了，链接这种说法应该是更偏向于计算机语言的。

2021-07-27 14:00 UTC, Lyaiya commented on projects/1.16/assets/applied-energistics-2/appliedenergistics2/lang/zh_cn.json
> +  "waila.appliedenergistics2.Channels": "%1$d / %2$d 个频道",
漏看了，保留了之前的。

2021-07-27 14:30 UTC, Lyaiya commented on projects/1.16/assets/applied-energistics-2/appliedenergistics2/lang/zh_cn.json
> +  "gui.appliedenergistics2.SpatialAnchorAll": "正在分析：%d 个区块存在于 %d 世界",
[英文资料](https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/4998)，应该是个可以查看当前 ME 网络所占用区块情况的机器，包括量子链接后的网络的区块情况。这里可能是错的。

2021-07-27 14:41 UTC, Lyaiya commented on projects/1.16/assets/applied-energistics-2/appliedenergistics2/lang/zh_cn.json
> +  "stat.appliedenergistics2.items_extracted": "物品已从ME存储取出",
应该是了。

2021-07-28 04:11 UTC, TUsama commented on projects/1.16/assets/applied-energistics-2/appliedenergistics2/lang/zh_cn.json
> +  "theoneprobe.appliedenergistics2.p2p_unlinked": "未链接",
我相当怀疑原先是只有连接的，但是自从link在英文世界的互联网中开始有“超链接”的意思之后，链接一词才出现。这个词似乎就是近十几年以来才出现的。
所以我在我自己的文本里尽量避免链接一词的出现，因为这个词实际的含义要窄得多。但现在人们使用链接很明显是一种词语变化的趋势，在我审的文本里，很多人都在连接作名词的时候改换成链接。我也有点迷茫。

2021-07-28 05:18 UTC, Lyaiya commented on projects/1.16/assets/applied-energistics-2/appliedenergistics2/lang/zh_cn.json
> +  "theoneprobe.appliedenergistics2.p2p_unlinked": "未链接",
我个人是比较倾向于连接，要不这里还是统一为连接吧。

2021-07-29 06:14 UTC, TUsama commented
顺带一提，我自己现在是物品名称内不用空格分隔中文 非中文，因为我发现加了空格后JEI会搜不出来。比如“ME箱子”，如果你没加空格，搜“MExiang”就可以搜到了；但是加了空格“MExiang”是搜不出来的，只能搜“ME xiang”，相当影响游戏体验。
其余的非搜索文本我还是保持空格分开的操作。

2021-07-29 08:12 UTC, Lyaiya commented
> 顺带一提，我自己现在是物品名称内不用空格分隔中文 非中文，因为我发现加了空格后JEI会搜不出来。比如“ME箱子”，如果你没加空格，搜“MExiang”就可以搜到了；但是加了空格“MExiang”是搜不出来的，只能搜“ME xiang”，相当影响游戏体验。
> 其余的非搜索文本我还是保持空格分开的操作。

现在就是没用空格分隔

2021-07-30 14:38 UTC, merged

2022-04-27 08:52 UTC, DoremySwee commented
![image](https://user-images.githubusercontent.com/66953201/165480597-d1d558cb-7e50-4f10-8e21-34c8997f2f04.png)
您是想把中文名改成应用能量