[R] 汉化神秘学（occultism）
CFPAOrg/Minecraft-Mod-Language-Package pull request #1227
Opened 2021-08-04 15:42 UTC by kappa-maintainer

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [x] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

魔灵体系和眼镜基本是按照原作，其他都是作者自由发挥，故翻译也只有那部分有原作可参考
作者用词极不统一，魔法师、召唤师多次交替使用，考虑同一为原作的魔法师
book.json暂未处理

2021-08-05 02:34 UTC, TUsama commented
你给那边发PR了？

2021-08-05 02:48 UTC, kappa-maintainer commented
没，但多的这些没有坏影响
等这边merge了再给官方发

2021-08-13 10:10 UTC, TUsama commented on projects/1.16/assets/occultism/occultism/lang/zh_cn.json
> +    "ritual.occultism.book_not_bound": "§l召唤之书未绑定§r。开始仪式前，你必须将召唤之书与魔灵全典合成来绑定一个魔灵。。",
多一个句号。

2021-08-13 12:33 UTC, TUsama requested changes

2021-08-13 12:33 UTC, TUsama commented on projects/1.16/assets/occultism/occultism/patchouli_books/dictionary_of_spirits/zh_cn/entries/getting_started/next_steps.json
> +      "title": "Craft Golden Chalk",
漏译，还有萤石？

2021-08-13 12:33 UTC, TUsama commented on projects/1.16/assets/occultism/occultism/patchouli_books/dictionary_of_spirits/zh_cn/entries/pentacles/craft_djinni.json
> +      "title": "Uses",
1

2021-08-13 12:33 UTC, TUsama commented on projects/1.16/assets/occultism/occultism/patchouli_books/dictionary_of_spirits/zh_cn/entries/pentacles/craft_foliot.json
> +      "title": "Uses",
1

2021-08-13 12:33 UTC, TUsama commented on projects/1.16/assets/occultism/occultism/patchouli_books/dictionary_of_spirits/zh_cn/entries/rituals/familiars/familiar_parrot.json
> +      "text": "$(bold)提供$()：陪伴"
伙伴还是陪伴？

2021-08-13 12:33 UTC, TUsama commented on projects/1.16/assets/occultism/occultism/patchouli_books/dictionary_of_spirits/zh_cn/entries/rituals/familiars/familiars.json
> +      "title": "交换使魔",
此处作“交易使魔”未尝不可。

2021-08-13 14:14 UTC, kappa-maintainer commented on projects/1.16/assets/occultism/occultism/patchouli_books/dictionary_of_spirits/zh_cn/entries/rituals/familiars/familiar_parrot.json
> +      "text": "$(bold)提供$()：陪伴"
原文用的Company，现在想想是我想多了

2021-08-17 01:30 UTC, kappa-maintainer commented
上游更新了，等我跟进

2021-08-17 02:31 UTC, kappa-maintainer commented
打错了，1.80

2021-08-18 02:18 UTC, TUsama commented on projects/1.16/assets/occultism/occultism/patchouli_books/dictionary_of_spirits/zh_cn/entries/spirits/unbound_spirits.json
> +      "text": "一般来说，魔灵被召唤出来时是被$(thing)约束$()的，这种约束指的是逼迫它们处于魔法师控制下的环境。绑定类法术的一个副作用是魔灵的一部分仍留在$(thing)异世界$()，从而剥夺了魔灵大部分的力量。不过这也防止了它们的灵髓进入这个世界。"
绑定还是约束？

2021-08-18 02:19 UTC, TUsama commented
终于看完了（

2021-08-18 02:58 UTC, kappa-maintainer commented on projects/1.16/assets/occultism/occultism/patchouli_books/dictionary_of_spirits/zh_cn/entries/spirits/unbound_spirits.json
> +      "text": "一般来说，魔灵被召唤出来时是被$(thing)约束$()的，这种约束指的是逼迫它们处于魔法师控制下的环境。绑定类法术的一个副作用是魔灵的一部分仍留在$(thing)异世界$()，从而剥夺了魔灵大部分的力量。不过这也防止了它们的灵髓进入这个世界。"
这模组很多不同的东西都用bind，当时应该是搞混了

2021-08-18 03:02 UTC, TUsama commented
你再看看有没有绑定法术的这种说法的遗漏，没有的话，解决冲突就可以merge了。

2021-08-18 04:22 UTC, kappa-maintainer commented
我突然觉得有一致性问题……我再重新看看

2021-08-18 04:38 UTC, kappa-maintainer commented
剩下解决冲突了
是不是可以无脑 git merge branch -X theirs

2021-08-18 04:53 UTC, TUsama commented
你直接pull -r也行啊。

2021-08-18 05:38 UTC, kappa-maintainer commented
好了

2021-08-18 05:38 UTC, merged

2021-08-18 05:39 UTC, TUsama commented
记得reset，commit多了空指针他们会说我，我只能用squash了（

2021-08-18 05:40 UTC, kappa-maintainer commented
没事，我是reset强迫症