[R][WIP][P] Materialis汉化提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1229
Opened 2021-08-05 20:09 UTC by Dr-WeiAL

- [ ] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [ ] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [ ] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [ ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [ ] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [ ] 我已上传英文文件以供审查；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-08-09 09:43 UTC, TUsama requested changes

2021-08-09 09:43 UTC, TUsama commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "material.materialis.forgotten_metal.flavor": "这啊，这是。。。这是那啥，那啥来着。",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

省略号为......，六个小点。

2021-08-09 09:43 UTC, TUsama commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "material.materialis.forgotten_metal.format": "遗忆 %s",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

如果这是材料+工具种类，那么之间不要加空格。

2021-08-09 09:43 UTC, TUsama commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "material.materialis.invar.encyclopedia": "扑灭目标身上的火焰，并以每1.5秒的燃烧时间乘以属性等级造成1额外伤害",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "material.materialis.invar.encyclopedia": "扑灭目标身上的火焰，每1.5秒的燃烧时间会造成1的额外伤害，然后伤害量再乘以属性等级",
```

2021-08-09 09:43 UTC, TUsama commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "material.materialis.ivory_psimetal.encyclopedia": "最多可增加1个额外的采掘速度，可根据每级的Psi数量进行调整",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "material.materialis.ivory_psimetal.encyclopedia": "最多可增加1额外的采掘速度，并随着Psi等级进行变化",
```
1 个速度都出来了，下次这种语病切忌再犯。

2021-08-09 09:43 UTC, TUsama commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "material.materialis.osmium.encyclopedia": "每级增加0.5攻击伤害乘以已损失的生命值百分比的额外伤害",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

```suggestion
  "material.materialis.osmium.encyclopedia": "每级增加0.5攻击伤害，然后再乘以已损失的生命值百分比",
```

2021-08-09 09:43 UTC, TUsama commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "material.materialis.pink_slime.encyclopedia": "每级降低10%的采掘速度和攻击速度，并获得300乘以消耗的数据作为黏液覆层的额外容量",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "material.materialis.pink_slime.encyclopedia": "每级降低10%的采掘速度和攻击速度，并获得300乘以降低的数值的黏液覆层额外容量",
```
这个黏液覆层额外容量是什么东西？还有你确定是“降低”吗？最好进游戏测试一下。

2021-08-09 09:43 UTC, TUsama commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "material.materialis.platinum.encyclopedia": "每级额外提升100%耐久消耗速度",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "material.materialis.platinum.encyclopedia": "每级额外提升100%耐久度",
```

2021-08-09 09:43 UTC, TUsama commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "material.materialis.refined_obsidian.encyclopedia": "-20%接触距离",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

```suggestion
  "material.materialis.refined_obsidian.encyclopedia": "-20%触及距离",
```

2021-08-09 09:43 UTC, TUsama commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "material.materialis.tungsten.encyclopedia": "工具的耐久度越低，耐久度的消耗几率越低，最低为 1%",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

这个空格？

2021-08-09 09:43 UTC, TUsama commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.create_wrenching.description": "工具可以通过潜行右键来拆卸机械动力的组件",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

```suggestion
  "modifier.materialis.create_wrenching.description": "工具可以通过潜行右击来拆卸动力学组件",
```
右击，彻查文本中的“右键”“左键”问题。

2021-08-09 09:43 UTC, TUsama commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.short_sighted.description": "减少接触距离",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
  "modifier.materialis.short_sighted.description": "减少触及距离",
```

2021-08-09 09:50 UTC, Dr-WeiAL commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "material.materialis.forgotten_metal.format": "遗忆 %s",
这个模组的其他材料制成的工具也是材料中间有个空格然后工具类型，可能是作者那边问题，所以这个是跟着作者的空一个格还是跟着匠魂本体的不空格？

2021-08-09 09:51 UTC, baka-gourd requested changes
中英文间的空格还要再看下

2021-08-09 09:51 UTC, baka-gourd commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "block.materialis.molten_ebony_psimetal_block": "熔融乌金色Psi金属",
官方的汉化里，是亮色/暗色，这里是不是不太对

2021-08-09 09:51 UTC, baka-gourd commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "block.materialis.molten_ivory_psimetal_block": "熔融象白牙Psi金属",
同上，这个形容词是否有问题

2021-08-09 09:51 UTC, baka-gourd commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "item.materialis.wrench.description": "扳手是工程师常用的工具。它可以有效地拆除机器并且拥有更多的能力槽。\n右键单击: 旋转方块",
`它可以有效地拆除机器并且拥有更多的能力槽。`
这句可以在斟酌下，貌似有语病。

2021-08-09 09:51 UTC, baka-gourd commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.otherworldly.flavor": "来自另一个存在位面！",
和deepl翻译的极为相似。
虽然`From another plane of existence!`直译确实是这样，但是翻译成 来自已知的位面 是否更好。

2021-08-09 09:51 UTC, baka-gourd commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.half_life.description": "耐久度高的时候会更快地消耗耐久，耐久度低的时候则消耗得更慢",
在耐久度高的时候会更快地消耗耐久，耐久度低的时候耐久则消耗得更慢

2021-08-09 09:52 UTC, Dr-WeiAL commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "material.materialis.platinum.encyclopedia": "每级额外提升100%耐久消耗速度",
不是，这个是每级提升消耗速度，不是提升耐久度，也就是你本来使用一次消耗1点耐久，一级就消耗双倍，二级就消耗三倍

2021-08-09 09:52 UTC, Dr-WeiAL commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "material.materialis.tungsten.encyclopedia": "工具的耐久度越低，耐久度的消耗几率越低，最低为 1%",
啊，这个可能是删空格的时候漏删的一个

2021-08-09 09:54 UTC, Dr-WeiAL commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "block.materialis.molten_ebony_psimetal_block": "熔融乌金色Psi金属",
我是根据当时游戏内看到的文本来写的，应该是i18汉化库里面就是叫乌金色，所以我这边也写成了乌金色

2021-08-09 09:57 UTC, baka-gourd commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "material.materialis.forgotten_metal.flavor": "这啊，这是。。。这是那啥，那啥来着。",
……

2021-08-09 12:07 UTC, TUsama commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "material.materialis.forgotten_metal.format": "遗忆 %s",
不空格，作者空格是因为人家是英文，但我们不是英文。

2021-08-09 12:07 UTC, TUsama commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "material.materialis.platinum.encyclopedia": "每级额外提升100%耐久消耗速度",
那行。

2021-08-09 12:12 UTC, TUsama commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "material.materialis.ivory_psimetal.encyclopedia": "最多可增加1额外的采掘速度，并随着Psi等级进行变化",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

我又看了一下原文，它的意思好像是“最多加到一点，增加量取决于等级”？

2021-08-09 12:13 UTC, Dr-WeiAL commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "material.materialis.ivory_psimetal.encyclopedia": "最多可增加1额外的采掘速度，并随着Psi等级进行变化",
不清楚，没玩过psi，不知道怎么改这个了(

2021-08-09 12:15 UTC, TUsama commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "material.materialis.ivory_psimetal.encyclopedia": "最多可增加1额外的采掘速度，并随着Psi等级进行变化",
你进游戏看看，要是最多就加1点那就是我的这个意思了。

2021-08-11 10:12 UTC, Dr-WeiAL commented on projects/1.16/assets/materialis/materialis/lang/zh_cn.json
> +  "material.materialis.ivory_psimetal.encyclopedia": "最多可增加1额外的采掘速度，并随着Psi等级进行变化",
这玩意我搞不明白，工具装上psi绑定结并不会改变采掘速度，要不然就等懂psi的人反馈再编辑吧

2021-08-11 13:10 UTC, TUsama commented
材料和工具种类之间的空格删了，就可以merge了。

2021-08-13 09:56 UTC, merged