[R,P] 汉化红石控制2及其前置
CFPAOrg/Minecraft-Mod-Language-Package pull request #1230
Opened 2021-08-06 05:40 UTC by kappa-maintainer

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [x] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

前作也是我汉化的，部分因为难度未能实验的功能直接沿用的前作翻译
作者喜欢造一些术语，导致部分物品名看着别扭
一些文本提示十分迷惑，我也是参考游戏里的实际功能改写的

2021-08-07 10:31 UTC, dovisutu requested changes
为什么我审这个的时候需要对照 Java 的格式符...~然后还是没搞懂~
%s08X %ss %sd 这都是什么啊...（是的，即便查了我还是没看懂）

顺便问一下，部分条目后面附的 16 进制地址是什么意思？比如此处：
```
  "gui.rs_ctr2.item_placer.sneak0": "潜行：否\n§80x001000",
  "gui.rs_ctr2.item_placer.sneak1": "潜行：是\n§80x00§f1§8000",
```
这里的`0x001000`是代表该项配置对应的 bit 吗？

2021-08-07 10:31 UTC, dovisutu commented on projects/1.16/assets/redstone-control-2/rs_ctr2/lang/zh_cn.json
> +  "gui.rs_ctr2.fmt_w": "png 格式导出\n时为图像宽\nhex 格式导出\n§7时为每行字节数",
格式化代码（§7）不匹配。
游戏中这一段的显示效果是怎样的？看原文，似乎是`图像宽`部分与其余部分效果不同

2021-08-07 10:31 UTC, dovisutu commented on projects/1.16/assets/redstone-control-2/rs_ctr2/lang/zh_cn.json
> +  "item.rs_ctr2.constant.tip": "§a⏵§7 = GUI 中设置的数字（与方块互动打开设置界面）。",
与方块互动？右击吗？

2021-08-07 10:31 UTC, dovisutu commented on projects/1.16/assets/redstone-control-2/rs_ctr2/lang/zh_cn.json
> +  "item.rs_ctr2.nor_gate": "与或门",
```suggestion
  "item.rs_ctr2.nor_gate": "或非门",
```

2021-08-07 10:31 UTC, dovisutu commented on projects/1.16/assets/redstone-control-2/rs_ctr2/lang/zh_cn.json
> +  "item.rs_ctr2.item_cable.tip": "将§n一个§7§f物品存储§a使用者§7连接到\n§n一个§7§f物品存储§9提供者§7。",
这里的使用者、提供者是玩家/生物吗？如果不是，尽量不要使用“...者”

2021-08-07 10:31 UTC, dovisutu commented on projects/1.16/assets/redstone-control-2/rs_ctr2/lang/zh_cn.json
> +  "item.rs_ctr2.fluid_io.tip": "§b⏴§7 提供了一个外部方块的流体存储。",
这里并不是过去式。
```suggestion
  "item.rs_ctr2.fluid_io.tip": "§b⏴§7 提供一个外部方块的流体存储。",
```

2021-08-07 10:31 UTC, dovisutu commented on projects/1.16/assets/redstone-control-2/rs_ctr2/lang/zh_cn.json
> +  "item.rs_ctr2.power_io.tip": "§e⏴§7 提供了一个外部方块的能量存储。",
```suggestion
  "item.rs_ctr2.power_io.tip": "§e⏴§7 提供一个外部方块的能量存储。",
```

2021-08-07 10:31 UTC, dovisutu commented on projects/1.16/assets/redstone-control-2/rs_ctr2/lang/zh_cn.json
> +  "item.rs_ctr2.switch_array": "二进制开关队列",
队列？这不是`queue`啊...

2021-08-07 12:57 UTC, kappa-maintainer commented on projects/1.16/assets/redstone-control-2/rs_ctr2/lang/zh_cn.json
> +  "msg.rs_ctr2.decode_bmp": "§b正在作为位图解码文件……",
因为第一行确实是格式，下面三行说格式就有点怪

2021-08-07 12:58 UTC, kappa-maintainer commented on projects/1.16/assets/redstone-control-2/rs_ctr2/lang/zh_cn.json
> +  "msg.rs_ctr2.count_items": "正在计算物品数量。",
高速双拼副作用
等下改改

2021-08-07 12:59 UTC, kappa-maintainer commented on projects/1.16/assets/redstone-control-2/rs_ctr2/lang/zh_cn.json
> +  "msg.rs_ctr2.invisible": "§c区域设置为隐形。",
翻译时脑袋搜不到这个词系列

2021-08-07 13:00 UTC, kappa-maintainer commented on projects/1.16/assets/redstone-control-2/rs_ctr2/lang/zh_cn.json
> +  "gui.rs_ctr2.ram.layout": "共 %s2$d 字节，每字 %sd 位",
也是一时忘了字长这个词

2021-08-07 13:01 UTC, kappa-maintainer commented on projects/1.16/assets/redstone-control-2/rs_ctr2/lang/zh_cn.json
> +  "item.rs_ctr2.item_cable.tip": "将§n一个§7§f物品存储§a使用者§7连接到\n§n一个§7§f物品存储§9提供者§7。",
当时想不到其他的，现在看似乎xx端好一点

2021-08-07 13:03 UTC, kappa-maintainer commented on projects/1.16/assets/redstone-control-2/rs_ctr2/lang/zh_cn.json
> +  "item.rs_ctr2.switch_array": "二进制开关队列",
原文array，但是游戏里只能往一个方向摆……
不过非要叫阵列也没问题？

2021-08-07 13:04 UTC, kappa-maintainer commented
各种稀奇古怪的格式只有一个办法：进游戏
游戏里看还挺清楚的

2021-08-08 15:05 UTC, dovisutu requested changes

2021-08-08 15:05 UTC, dovisutu commented on projects/1.16/assets/redstone-control-2/rs_ctr2/lang/zh_cn.json
> +  "rs_ctr2.subtitle.switch_flip": "已切换开关",
字幕格式错误。原版的字幕格式为`声源：音效`（其中声源有时不出现），如：
```
拉杆：拉动
从蜂蜜块滑下
```
这里需要与原版格式统一。下面数项同理。
（这里我给的实际上就是参照上面第一条的；不过估计这个开关不是“拉动”的？如果觉得这样翻译也不合适，可以自行更改。）
```suggestion
  "rs_ctr2.subtitle.switch_flip": "开关：拨动",
```

2021-08-08 15:05 UTC, dovisutu commented on projects/1.16/assets/redstone-control-2/rs_ctr2/lang/zh_cn.json
> +  "rs_ctr2.subtitle.button_press": "已按下按钮",
不知道此处是否需要与原版的按钮做区分？
```suggestion
  "rs_ctr2.subtitle.button_press": "按钮：按下",
```

2021-08-08 15:05 UTC, dovisutu commented on projects/1.16/assets/redstone-control-2/rs_ctr2/lang/zh_cn.json
> +  "rs_ctr2.subtitle.button_release": "已松开按钮",
```suggestion
  "rs_ctr2.subtitle.button_release": "按钮：松开",
```

2021-08-08 15:05 UTC, dovisutu commented on projects/1.16/assets/redstone-control-2/rs_ctr2/lang/zh_cn.json
> +  "item.rs_ctr2.fluid_buffer.ext": "容量：煤单元 %sd mB",
typo.
```suggestion
  "item.rs_ctr2.fluid_buffer.ext": "容量：每单元 %sd mB",
```

2021-08-09 00:41 UTC, kappa-maintainer commented on projects/1.16/assets/redstone-control-2/rs_ctr2/lang/zh_cn.json
> +  "rs_ctr2.subtitle.switch_flip": "已切换开关",
还真没意识到是音效……

2021-08-09 09:18 UTC, TUsama commented on projects/1.16/assets/redstone-control-2/rs_ctr2/lang/zh_cn.json
> +  "rs_ctr2.subtitle.switch_flip": "已切换开关",
subtitle 就是字幕。

2021-08-09 09:19 UTC, TUsama commented
没问题就merge了？@dovisutu

2021-08-09 10:09 UTC, dovisutu approved these changes
基本上可以了

2021-08-09 13:27 UTC, merged