[R,W] 标点符号之省略号 (1/6)
CFPAOrg/Minecraft-Mod-Language-Package pull request #1242
Opened 2021-08-11 07:38 UTC by WuzgXY-GitHub

- [ ] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [ ] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [ ] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](../CONTRIBUTING.md)）；
- [ ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [ ] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [ ] 我已上传英文文件以供审查；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-08-11 13:11 UTC, TUsama commented
这个你自己看着来。

2021-08-11 16:31 UTC, WuzgXY-GitHub commented
我反正是尽可能确保了没有遗漏，也统一了格式，也没有动 1.12.2 那天杀的 Botania、Botania Tweaks 和 Psi。但是可能有误转换的，比如英文里不该转的可能不小心转了，所以需要审核。审核完尽快合并，否则 conflict 会多得要死

Vazkii 你不做分行，我去你的

一项遗漏，明天做好：`未彻查单独的全角省略号…`

2021-08-12 03:39 UTC, dovisutu commented
这也太多了......（补足六点省略号）
慢慢审吧。

2021-08-12 04:20 UTC, dovisutu requested changes
审核部分 1
at: file 91 elementaristics/patchouli_books/liber_elementium/zh_cn/entries/souls/story_souls.json

2021-08-12 04:20 UTC, dovisutu commented on projects/1.12.2/assets/bewitchment-legacy/bewitchment/patchouli_books/codex_infernalis/zh_cn/entries/devilish_oddities/infernal_tiles.json
> +	  "text": "无论周围气候如何，这种类似于石板且微泛红色的石头摸起来总是像夜晚那样清冷。将耳朵贴到石砖上，你可以惊恐地听到其尖叫以及哭泣的声音……人们认为恶魔就是用这种材料建造它们的处所，借以躲过时天使的搜查，and can be created using the Hellworld brew on Embittered Bricks, as well as follows:"
（虽然不是标点，仅作提示）
这后半段怎么没翻……（当然不用在这里改）

2021-08-12 04:20 UTC, dovisutu commented on projects/1.12.2/assets/botania/botania/lang/zh_cn.lang
> +botania.versioning.flavour21=这个植物魔法更新会自我销毁 3... 2...
格式/渲染要求？是采用/u2026会出问题吗？

2021-08-12 04:20 UTC, dovisutu commented on projects/1.12.2/assets/botania/botania/lang/zh_cn.lang
> +tile.botania:flower.heiseiDream.reference=平成，平成，崩坏...……
```suggestion
tile.botania:flower.heiseiDream.reference=平成，平成，崩坏……
```

2021-08-12 04:20 UTC, dovisutu commented on projects/1.12.2/assets/bwm-suite/betterwithmods/lang/zh_cn.lang
> +advancement.betterwithmods.turntable.desc=You Spin Me Right Round...
（虽然不是标点）
未翻译文本最好还是不要留在zh_cn里

2021-08-12 04:20 UTC, dovisutu commented on projects/1.12.2/assets/crossroads-mc/crossroads/lang/zh_cn.lang
> +info.crafttweaker=当前有7种配方有CraftTweaker支持：奥术提取器、热交换器、流体冷却室、融合光束、磨石、精细合成器和加热坩埚。当使用Add函数时所有形式的集成都会覆盖拥有相同输入的已存在配方。</n>奥术提取器的集成是“mods.crossroads.ArcaneExtractor”。addRecipe函数需要一个IItemStack和四个整型，按顺序是输出的能量、潜
这是句号打多了吧
```suggestion
info.crafttweaker=当前有7种配方有CraftTweaker支持：奥术提取器、热交换器、流体冷却室、融合光束、磨石、精细合成器和加热坩埚。当使用Add函数时所有形式的集成都会覆盖拥有相同输入的已存在配方。</n>奥术提取器的集成是“mods.crossroads.ArcaneExtractor”。addRecipe函数需要一个IItemStack和四个整型，按顺序是输出的能量、潜能、稳定性和虚空。removeRecipe函数只需要一个IItemStack。这两个函数都会忽略元数据，而且不能用矿辞。</n>热交换器在“mods.crossroads.EnvHeatSource”。addRecipe函数需要2个IBlocks和2个浮点数，按顺序分别是输入、输出、热量变化和温度限制。如果热量变化是负数，温度限制则被视为下界而不是上界。removeRecipe函数只需要一个IBlock输入。这两个函数都会忽略元数据，而且不能用矿辞。如果输入和输出都没有物品形式（例如大多数液体和火），使用IBlocks不会有任何作用！作为代替，你需要使用“mods.crossroads.AdvEnvHeatSource”里的函数，该函数接受IBlockStates输入而不是IBlocks。IBlockStates需要像这样指定：<block:minecraft:fire>，而不是<minecraft:fire>。使用IBlockStates需要先安装ContentTweaker（一个官方CraftTweaker拓展）。</n>流体冷却室位于“mods.crossroads.FluidCoolingChamber”。addRecipe函数需要的参数按顺序是作为输出的IItemStack，输入的ILiquidStack，浮点数的最大温度和浮点数的上升温度。removeRecipe只需要一个ILiquidStack输入。</n>融合光束位于“mods.crossroads.FusionBeam”。 addRecipe函数的输入为输入IItemStack input、整型minPower、输出IItemStack output、布尔型的voi。尽管输入输出都是IItemStacks，它们会被解释为对应的方块，方块的元数据等于堆叠的元数据。voi控制配方使用的光束是否必须为虚空-融合光束。removeRecipe函数需要输入 IItemStack的input，布尔型的voi。如果输入输出的两种方块没有物品形式（例如大多数流体和火），使用IItemStacks会无效！作为代替，你应该使用位于“mods.crossroads.AdvFusionBeam”的函数，该函数使用IBlockStates而不是IItemStacks。IBlockStates需要像这样指定：<block:minecraft:fire>，而不是<minecraft:fire>。注意，当使用addRecipe/removeRecipe函数的IBlockState版本的时候，在输入的IBlockState后有一个布尔型变量，用于控制是否忽略元数据。使用IBlockStates需要先安装ContentTweaker（一个官方CraftTweaker拓展）。</n>磨石的相关函数位于“mods.crossroads.Grindstone”。addRecipe函数需要IItemStack/IOreDictEntry输入，IIngredient的输出1，可选的IIngredient输出2，可选的IIngredient输出3。removeRecipe函数只需要一个IItemStack/IOreDict输入。当删除或重写配方时要小心匹配到使用ItemStack或OreDict的原有配方。</n>加热坩埚的函数位于“mods.crossroads.HeatingCrucible”。所有加热坩埚的配方都会在1000°C时激活，这一行为不能被改变。addRecipe函数需要IItemStack/IOreDict输入，ILiquidStack输出，及一个代表贴图的字符串。贴图字符串应该映射到一个方块的贴图，当加热坩埚收到该配方的输入时，会显示为此贴图。removeRecipe函数只需要一个IItemStack/IOreDict输入。再重复一次，当删除或重写配方时要小心匹配到使用ItemStack或OreDict的原有配方。</n>惊喜合成器的集成目前只能移除配方，而不能添加配方。向精细合成器添加配方的功能不会出现在MC1.12，但会在MC1.13+。精细合成器的集成位于mods.crossroads.DetailedCrafter。现在有两个函数：removeTechnoRecipe和removeAlcRecipe。二者都需要一个IItemStack参数，运行后会删除所有输出这个IItemStack的配方。removeTechnoRecipe只删除科技魔法配方，removeAlcRecipe只删除炼金术配方。
```

2021-08-12 04:20 UTC, dovisutu commented on projects/1.12.2/assets/deep-resonance/deepresonance/text/manual.txt
>  一些催化物品 (绿宝石,钻石, 红石, 荧石,
顺便改一下吧：并列列表（不完整）的最后一项与省略号间没有逗号\顿号。
```suggestion
一些催化物品 (绿宝石、钻石、红石、荧石
```

2021-08-12 04:20 UTC, dovisutu commented on projects/1.12.2/assets/elementaristics/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/alchemy/entry_wine.json
> +      "text": "殷红之酒可能是神秘学家们可以获得的最好的享乐之物了。$(br)酒的颜色殷红似血,其中闪烁的点点微光，好似万千星辰在其中游弋。$(br)它的味道……$(o)天啊，它的味道……！$()"
没有省略号后面加感叹号的用法

2021-08-12 04:20 UTC, dovisutu commented on projects/1.12.2/assets/elementaristics/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/energy/entry_passive_supplier.json
> +      "text": "$(o)zZ z zZzz ...... zZZ zZ Z ZzZz zzzz z zzz ZZzzZZ ...... zzz Z zz zZzz zZzz ZZzzZZ ...... zZ Zz Zzz ...... Z zzzz z ...... zzZz zzZ zZz Zz zZ ZzZz z ...... Zzzz zzZ zZz Zz zzz ZZzzZ
还原为英文似乎是三点的省略号？
使用`...`（3* \u002e）还是`…`（\u2026）？

2021-08-12 06:41 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/angry-pixel-the-betweenlands-mod/thebetweenlands/lang/zh_cn.lang
> +item.thebetweenlands.record.16612.desc=......
因为是英文

2021-08-12 06:42 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/automated-redstone/circuits/lang/zh_cn.lang
> +gui.cd4017be.bit.info1=§7使用文本字段，您可以为6个方块面中的每一个指定输入和输出带宽（0 = 未连接）。 \n§7你可以在所有要传输的信号上自由分配32位。每个信号应该给多少位，取决于它们可以携带的可能红石强度值的范围：n bits -> 0 ……. 2^n - 1 范围\n§7使用滑块，你可以定义总位模式中的位置应找到每个值（确保它们不重叠以防止干扰）。当然，有线网络
……这块是检查 ... 时因为是数字所以没转换，检查 .. 时没发现是数字所以转换了

2021-08-12 06:43 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/botania/botania/lang/zh_cn.lang
> +botania.versioning.flavour21=这个植物魔法更新会自我销毁 3... 2...
不是，是为了好看（？）

2021-08-12 06:45 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/deep-resonance/deepresonance/text/manual.txt
>  一些催化物品 (绿宝石,钻石, 红石, 荧石,
```suggestion
一些催化物品（绿宝石、钻石、红石、荧石）
```

2021-08-12 06:46 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/elementaristics/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/alchemy/entry_wine.json
> +      "text": "殷红之酒可能是神秘学家们可以获得的最好的享乐之物了。$(br)酒的颜色殷红似血,其中闪烁的点点微光，好似万千星辰在其中游弋。$(br)它的味道……$(o)天啊，它的味道……！$()"
确实没有，但或可保留，毕竟表达的情绪两者都无法脱离（？）

2021-08-12 06:46 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/elementaristics/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/energy/entry_passive_supplier.json
> +      "text": "$(o)zZ z zZzz ...... zZZ zZ Z ZzZz zzzz z zzz ZZzzZZ ...... zzz Z zz zZzz zZzz ZZzzZZ ...... zZ Zz Zzz ...... Z zzzz z ...... zzZz zzZ zZz Zz zZ ZzZz z ...... Zzzz zzZ zZz Zz zzz ZZzzZ
\u2026

2021-08-12 06:51 UTC, dovisutu commented on projects/1.12.2/assets/deep-resonance/deepresonance/text/manual.txt
>  一些催化物品 (绿宝石,钻石, 红石, 荧石,
这个好像是省略号和括号到下一行了...
应该把省略号和括号一起移上来，下一行的删掉

2021-08-13 05:21 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/elementaristics/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/alchemy/entry_wine.json
> +      "text": "殷红之酒可能是神秘学家们可以获得的最好的享乐之物了。$(br)酒的颜色殷红似血,其中闪烁的点点微光，好似万千星辰在其中游弋。$(br)它的味道……$(o)天啊，它的味道……！$()"
```suggestion
      "text": "殷红之酒可能是神秘学家们可以获得的最好的享乐之物了。$(br)酒的颜色殷红似血,其中闪烁的点点微光，好似万千星辰在其中游弋。$(br)它的味道……$(o)天啊，它的味道！$()"
```

2021-08-13 05:44 UTC, dovisutu requested changes
审核部分 2
at: file 203 projects/1.12.2/assets/statues/statues/lang/zh_cn.lang
此外，可以用 add suggestion to batch 打包更改。

WuzgXY：不用，到时候 squash 就行，此分支不必保留

2021-08-13 05:44 UTC, dovisutu commented on projects/1.12.2/assets/inductive-logistics/indlog/lang/zh_cn.lang
>  gui.cd4017be.filter.infoN3=§4...§e...§7 -> §4...§7 followed by §e...\n§4...§3|§e...§7 -> either §4...§7 or §e...\n§3(§4...§3)§7 -> §4...§7, as capturing group\n§3\\§en§7 -> whatever the §en§7-th capt
竟然是正则！（虽然好像也不完全是正则，至少我没见到过[a&&b]和\Q的用法）
但是翻译的时候完全翻乱了（甚至有一行没翻）
```suggestion
gui.cd4017be.filter.infoN1=§4x§7->§4x§7（对于非控制字符）\n§3\\§4x§7 -> §4x§7，控制字符转义\n§3[§4abc§3]§7->§4a§7、§4b§7或§4c\n§3[^§4abc§3]§7->除§4a§7、§4b§7或§4c外的任何字符\n§3[A-Za-z]§7->A-Z或a-z范围内的任何字符\n§3[§4...§3&&§E...§3]§7->任何同时匹配§4...§7和§E...§7的字符\n§3.§7->任何字符\n§3\\d§7->任何数字字符，即：§3[0-9]\n§3\\D§7->任何非数字字符，即：§3[^0-9]\n§3\\s§7->任何空白字符\n§3\\S§7->任何非空白字符\n§3 \\w§7->任何文本字符，即：§3[A-Za-z0-9_]\n§3\\W§7->任何非文本字符：§3[^\\w]
gui.cd4017be.filter.infoN2=§4x§3?§7 -> §4x§7出现一次或零次\n§4x§3*§7 -> §4x§7出现任意次，包括零次\n§4x§3+§7 -> §4x§7出现至少一次\n§4x§3{§en§3}§7 -> §4X§7出现恰好§en§7次\n§4x§3{§en§3,}§7 -> §4x§7出现至少§en§7次\n§4x§3{§en§3,§em§3}§7 -> §4x§7出现至少§en§7次，至多§em§7次
gui.cd4017be.filter.infoN3=§4...§e...§7 -> §4...§7与后接的§e...\n§4...§3|§e...§7 -> §4...§7或§e...\n§3(§4...§3)§7 -> §4...§7，作为捕获组\n§3\\§en§7 -> 匹配第§en§7个捕获组捕获的内容\n§3\\Q§4...§3\\E§7 -> 引用§4...中的所有字符
```

2021-08-13 05:44 UTC, dovisutu commented on projects/1.12.2/assets/ingame-info-xml/ingameinfo/lang/zh_cn.lang
> +ingameinfoxml.tag.abrfinedirection.desc=玩家当前精确朝向简写(南,西南,西,西北, ……).
不完整列表末项与省略号间没有逗号或顿号。
```suggestion
ingameinfoxml.tag.abrfinedirection.desc=玩家当前精确朝向简写（S、SW、W、NW……）。
```

2021-08-13 05:44 UTC, dovisutu commented on projects/1.12.2/assets/ingame-info-xml/ingameinfo/lang/zh_cn.lang
>  ingameinfoxml.tag.abrroughdirection.desc=玩家当前当前大致朝向简写(南,西,北,东).
```suggestion
ingameinfoxml.tag.abrroughdirection.desc=玩家当前当前大致朝向简写（S、W、N、E）。
```

2021-08-13 05:44 UTC, dovisutu commented on projects/1.12.2/assets/ingame-info-xml/ingameinfo/lang/zh_cn.lang
> +ingameinfoxml.tag.finedirection.desc=玩家当前精确朝向(南,西南,西,西北, ……).
```suggestion
ingameinfoxml.tag.finedirection.desc=玩家当前精确朝向（南、西南、西、西北……）。
```

2021-08-13 05:44 UTC, dovisutu commented on projects/1.12.2/assets/modular-diversity/modulardiversity/lang/zh_cn.lang
> +tooltip.mineral.result.none=没有改变……
这是句号打多了。
```suggestion
tooltip.mineral.result.none=没有改变。
```

2021-08-13 05:44 UTC, dovisutu commented on projects/1.12.2/assets/pneumaticcraft-repressurized/pneumaticcraft/lang/zh_cn.lang
> +gui.programmer.button.convertToRelative.noBaseCoordinate=§c-在起始程序下需要一个坐标算子以定义基坐标，这是玩家需要改变的唯一参数坐标……
句号打多了。
```suggestion
gui.programmer.button.convertToRelative.noBaseCoordinate=§c-在起始程序下需要一个坐标算子以定义基坐标。这是玩家需要改变的唯一参数坐标。
```

2021-08-13 05:44 UTC, dovisutu commented on projects/1.12.2/assets/pneumaticcraft-repressurized/pneumaticcraft/patchouli_books/book/zh_cn/entries/programming/block_right_click.json
> +      "text": "无人机将会对指定$(l:programming/area)区域/$内的每一个方块使用其物品栏内第一个物品$(thing)右击/$.这可以用来锄地，种下种子，施加骨粉，投掷药水，部署无人机，使用扳手旋转方块等……用它可以做到的可能性是无穷的。你可以通过放置一个指示某方块的$(l:programming/item_filter)物品过滤器/$来指定哪些方块应当被$(th
~自己修自己的错误~
（虽然不是省略号）
```suggestion
      "text": "无人机将会对指定$(l:programming/area)区域/$内的每一个方块使用其物品栏内第一个物品$(thing)右击/$。这可以用来锄地，种下种子，施加骨粉，投掷药水，部署无人机，使用扳手旋转方块等……用它可以做到的可能性是无穷的。你可以通过放置一个指示某方块的$(l:programming/item_filter)物品过滤器/$来指定哪些方块应当被$(thing)右击/$。"
```

2021-08-13 05:44 UTC, dovisutu commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/xml/chembook.zh_cn.xml
> +												<p>> 物品和流体的输入输出是全自动的，可以将反应器与物流、流体存储系统相连接……</p>
句号打多了。
```suggestion
												<p>> 物品和流体的输入输出是全自动的，可以将反应器与物流、流体存储系统相连接。</p>
```

2021-08-13 05:44 UTC, dovisutu commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/xml/chembook.zh_cn.xml
> +												<p>> 一共有两种物品输入：原料和催化剂。原料每次都会消耗，而催化剂每次只损失耐久……</p>
```suggestion
												<p>> 一共有两种物品输入：原料和催化剂。原料每次都会消耗，而催化剂每次只损失耐久。</p>
```

2021-08-13 05:44 UTC, dovisutu commented on projects/1.12.2/assets/roots/roots/patchouli_books/roots_guide/zh_cn/entries/rituals/ritual_heavy_storms.json
> +      "text": "唤起强烈的季风，从而引起$(warning)在仪式持续过程中无法被平息的疾风暴雨，停息暴雨的唯一手段就是用 $(l:basics/bucket_of_water)水桶$()将仪式柴堆浇熄。$(br2)同样地，暴雨亦可扑灭所有着火生物身上的火焰……"
```suggestion
      "text": "唤起强烈的季风，从而引起$(warning)在仪式持续过程中无法被平息的疾风暴雨，停息暴雨的唯一手段就是用 $(l:basics/bucket_of_water)水桶$()将仪式柴堆浇熄。$(br2)同样地，暴雨亦可扑灭所有着火生物身上的火焰。"
```

2021-08-13 06:54 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/hammer-lib/hammercore/lang/zh_cn.lang
> +hc.manual_desc.apengu=APengu以前(大约2017年)开发过很多优秀的模组，当然我也一样。他过的很开心,而且经常更新他的模组,加入新的想法,并为我添加更多的API,锤子核心。他是Minecraft社区里一个非常聪明的发明家。突然有一天,他看到一条淡蓝色的巨龙在漫无目的的盘旋,也许是在田野里迷失了方向。他走了出去,尝试着和龙会面,考虑到悬殊的体量。那只企鹅只好用扩音机才能让
是，但我懒得调了，实在太多了，后五次再调

2021-08-13 06:57 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/ingame-info-xml/ingameinfo/lang/zh_cn.lang
> +ingameinfoxml.tag.finedirection.desc=玩家当前精确朝向(南,西南,西,西北, ……).
不是英文缩写了？

2021-08-13 09:05 UTC, dovisutu commented on projects/1.12.2/assets/hammer-lib/hammercore/lang/zh_cn.lang
> +hc.manual_desc.apengu=APengu以前(大约2017年)开发过很多优秀的模组，当然我也一样。他过的很开心,而且经常更新他的模组,加入新的想法,并为我添加更多的API,锤子核心。他是Minecraft社区里一个非常聪明的发明家。突然有一天,他看到一条淡蓝色的巨龙在漫无目的的盘旋,也许是在田野里迷失了方向。他走了出去,尝试着和龙会面,考虑到悬殊的体量。那只企鹅只好用扩音机才能让
ok

2021-08-13 09:09 UTC, dovisutu commented on projects/1.12.2/assets/ingame-info-xml/ingameinfo/lang/zh_cn.lang
> +ingameinfoxml.tag.finedirection.desc=玩家当前精确朝向(南,西南,西,西北, ……).
原文里是这样的：
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/aaabdfb82e73d1426fb391605cdd13085c79bd2e/projects/1.12.2/assets/ingame-info-xml/ingameinfo/lang/en_us.lang#L232-L235
带abr的两条是缩写，不带的是全称
（这么说来估计`ingameinfoxml.tag.roughdirection.desc`也要改了）

2021-08-13 10:02 UTC, TUsama commented
解决冲突之后可以merge了？

2021-08-13 10:06 UTC, dovisutu commented
别，还没审完

2021-08-13 10:10 UTC, dovisutu requested changes
审核部分 3
at: file 243 projects/1.12.2/assets/yoyos/yoyos/lang/zh_cn.lang

2021-08-14 15:32 UTC, dovisutu requested changes
审核部分 4
所有文件审核完毕。（除开confilct的那些可能需要再来一次）
~有想再审一次的也可以（~

2021-08-14 15:32 UTC, dovisutu commented on projects/1.16/assets/integrated-dynamics/integrateddynamics/lang/zh_cn.json
> +  "info_book.integrateddynamics.manual.logic.value_types.fluid.text1": "对 &lMinecraft&r 流体的调用，例如 1000mB &8熔岩&0，3mB &8水&0，943mb &8酒石酸&0，3030mB &8门瑞欧树脂&0……",
> 943mb &8酒石酸&0
这谁翻的...原文里可没有这句（

2021-08-14 15:32 UTC, dovisutu commented on projects/1.16/assets/litematica/litematica/lang/zh_cn.json
> +  "Enables the schematic world pick block hotkeys.\nThere is also a hotkey for toggling this option to toggle those hotkeys……o.o": "启用投影原理图方块选择快捷键。\n还有一个热键来切换这个选项来切换这些热键的工作模式\n……o.o",
~以英文原文作key，也是服了~
key里面需要还原。
```suggestion
  "Enables the schematic world pick block hotkeys.\nThere is also a hotkey for toggling this option to toggle those hotkeys... o.o": "启用投影原理图方块选择快捷键。\n还有一个热键来切换这个选项来切换这些热键的工作模式\n……o.o",
```

2021-08-14 15:32 UTC, dovisutu commented on projects/1.16/assets/minecolonies/minecolonies/lang/zh_cn.json
> +  "com.minecolonies.command.rsreset.success": "在1.618秒后，它重新实例化为全新……",
句号打多了。
```suggestion
  "com.minecolonies.command.rsreset.success": "在1.618秒后，它重新实例化为全新。",
```

2021-08-14 15:32 UTC, dovisutu commented on projects/1.16/assets/mythicbotany/mythicbotany/lang/zh_cn.json
> +  "lexicon.mythicbotany.tools.page3": "这把剑的伤害更高，并且攻击速度更快……",
```suggestion
  "lexicon.mythicbotany.tools.page3": "这把剑的伤害更高，并且攻击速度更快。",
```

2021-08-14 15:32 UTC, dovisutu commented on projects/1.16/assets/psi/psi/lang/zh_cn.json
> +  "psi.book.page.trigonometry.0": "这章所包含的$(thing)运算符$(0)与三角函数有关。$(piece)常量：Pi$(0)顾名思义，返回π=3.1415……$(p)同样地这章还有基础的三角函数运算符：正弦、余弦函数，以及对应的反函数(反正弦，反余弦)。",
原文的确是句号。
```suggestion
  "psi.book.page.trigonometry.0": "这章所包含的$(thing)运算符$(0)与三角函数有关。$(piece)常量：Pi$(0)顾名思义，返回π=3.1415……。$(p)同样地，这章还有基础的三角函数运算符：正弦、余弦函数，以及对应的反函数（反正弦，反余弦）。",
```

2021-08-14 15:32 UTC, dovisutu commented on projects/1.16/assets/redstone-control-2/rs_ctr2/lang/zh_cn.json
> +  "gui.rs_ctr2.item_placer.slot": "装备物品：\n§7物品栏位置：§4%sd §8= bits[0……5]",
我不太确定这种位置是否可以进行这种更改...如果可以就不管了
（下文同理）

2021-08-14 15:57 UTC, dovisutu commented
等一下，我好像把industrial foregoing的空格又弄坏了...

2021-08-15 11:31 UTC, dovisutu commented
@WuzgXY-GitHub 审核处理一下，~毕竟我总不能自己commit自己的吧~

2021-08-15 13:00 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/wireless-redstone-cbe/wrcbe/lang/zh_cn.lang
> +wrcbe.command.usage=WR-CBE REther管理。用法：freq [参数 ...]
应该是有空格的

2021-08-15 13:01 UTC, WuzgXY-GitHub commented on projects/1.16/assets/integrated-dynamics/integrateddynamics/lang/zh_cn.json
> +  "info_book.integrateddynamics.manual.logic.value_types.fluid.text1": "对 &lMinecraft&r 流体的调用，例如 1000mB &8熔岩&0，3mB &8水&0，943mb &8酒石酸&0，3030mB &8门瑞欧树脂&0……",
算了，就这样吧（

2021-08-15 13:01 UTC, WuzgXY-GitHub commented on projects/1.16/assets/integrated-dynamics/integrateddynamics/lang/zh_cn.json
> +  "info_book.integrateddynamics.manual.logic.value_types.fluid.text1": "对 &lMinecraft&r 流体的调用，例如 1000mB &8熔岩&0，3mB &8水&0，943mb &8酒石酸&0，3030mB &8门瑞欧树脂&0……",
```suggestion
  "info_book.integrateddynamics.manual.logic.value_types.fluid.text1": "对 &lMinecraft&r 流体的调用，例如 1000 mB &8熔岩&0，3 mB &8水&0，943 mB &8酒石酸&0，3030 mB &8门瑞欧树脂&0……",
```

2021-08-15 13:05 UTC, WuzgXY-GitHub commented on projects/1.16/assets/litematica/litematica/lang/zh_cn.json
> +  "Enables the schematic world pick block hotkeys.\nThere is also a hotkey for toggling this option to toggle those hotkeys……o.o": "启用投影原理图方块选择快捷键。\n还有一个热键来切换这个选项来切换这些热键的工作模式\n……o.o",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

~以英文原文作key，也是服了~
key里面需要还原。
```suggestion
  "Enables the schematic world pick block hotkeys.\nThere is also a hotkey for toggling this option to toggle those hotkeys... o.o": "启用投影原理图方块选择快捷键。\n还有一个热键来切换这个选项来切换这些热键的工作模式\n……o.o",
```

2021-08-15 13:07 UTC, WuzgXY-GitHub commented on projects/1.16/assets/redstone-control-2/rs_ctr2/lang/zh_cn.json
> +  "gui.rs_ctr2.item_placer.slot": "装备物品：\n§7物品栏位置：§4%sd §8= bits[0……5]",
```suggestion
  "gui.rs_ctr2.item_placer.slot": "装备物品：\n§7物品栏位置：§4%sd §8= bits[0...5]",
```
疏漏

2021-08-15 13:11 UTC, TUsama commented
晕了，邮箱轰炸。

2021-08-15 13:14 UTC, WuzgXY-GitHub commented
> 
> 
> 晕了，邮箱轰炸。

没错，而且 Formatter 和别的一些检测器也快爆炸了。

2021-08-15 13:14 UTC, merged

2021-08-15 13:44 UTC, dovisutu commented
> 37 commits
天哪...
邮箱轰炸 +1