[M]沉浸原油 1.16.5 更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #1260
Opened 2021-08-16 08:51 UTC by mcBegins2Snow

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [x] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 是 1.15-1.16 翻译，应该是：`projects/1.16/assets/immersive-petroleum/immersivepetroleum/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-08-16 11:34 UTC, TUsama requested changes

2021-08-16 11:34 UTC, TUsama commented on projects/1.16/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/cokerunit.txt
> +<&cokerunit0>焦化器是一个§o非常大§r的多块结构，可将沥青进一步加工成石油焦和柴油作为副产品。它通过将沥青加热到其热裂解温度来实现这一点，这将重的长链烃分子裂解为石油焦和柴油。
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

1. 多方块
2. 可将沥青进一步加工成石油焦和柴油作为副产品 句式杂糅。

2021-08-16 11:34 UTC, TUsama commented on projects/1.16/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/lubricant.txt
> +<&lubricant1>润滑油罐可以手动将润滑油涂抹到机械上从而增加效率。其中，润滑油是最有效的；不过值得一提的是<link;squeezer;§n§o植物油§r>也可用做润滑。一旦油罐装满，只需简单地右击有效的方块即可对其进行润滑。加速时，机器会明显滴油。
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

润滑油罐可以手动将润滑油涂抹到机械上从而增加效率  润滑油罐有手？

2021-08-16 11:34 UTC, TUsama commented on projects/1.16/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/lubricant.txt
> +铁傀儡也可以被润滑，治疗它们并暂时增加它们的速度和力量。
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

两分句的主语明显不一致，但是第二分句并未重新声明主语。

2021-08-16 11:34 UTC, TUsama commented on projects/1.16/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/napalm.txt
> +凝固汽油是一种极易燃的物质，可在<link;mixer;§n§o混合器§r>中用<link;immersivepetroleum:distillationtower;§n§o汽油§r>和三个铝粉制得。它除了用来搞破坏，似乎没别的用。凝固汽油点燃时，火焰会立即向周围蔓延，这可以快速毁掉一片森林。另外，它还可以作为<link;chemthrower;§n§o化学喷射器§r>的高效燃料。
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
凝固汽油是一种极易燃的物质，可在<link;mixer;§n§o混合器§r>中用<link;immersivepetroleum:distillationtower;§n§o汽油§r>和三份铝粉制得。它除了用来搞破坏，似乎没别的用。凝固汽油点燃时，火焰会立即向周围蔓延，这可以快速毁掉一片森林。另外，它还可以作为<link;chemthrower;§n§o化学喷射器§r>的高效燃料。
```

2021-08-16 11:34 UTC, TUsama commented on projects/1.16/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/pumpjack.txt
> +钻井消耗<config;i;pumpjack_consumption>Flux/t以<config;i;pumpjack_speed>mB/t的速率泵送原油，抽出的原油可从侧面的两个带有橙色圆点的输出端自动输出。
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
钻井以<config;i;pumpjack_consumption>Flux/t以<config;i;pumpjack_speed>mB/t的速率泵送原油，抽出的原油可从侧面的两个带有橙色圆点的输出端自动输出。

```

2021-08-16 11:34 UTC, TUsama commented on projects/1.16/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/speedboat.txt
> +<&speedboat4>如果你寻求超越这个领域进行探索，或者只是想让你的汽艇更能抵抗各种元素，请考虑安装§6钢制船体§r。它提高了船的生命值和耐火性，允许在下界广阔的熔岩湖中航行。
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
<&speedboat4>如果你寻求超越这个领域进行探索，或者只是想让你的汽艇更能抵抗各种元素，请考虑安装§6钢制船体§r。它提高了船的生命值和耐火性，能让船只在下界广阔的熔岩湖中航行。

```

2021-08-17 00:35 UTC, mcBegins2Snow commented on projects/1.16/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/lubricant.txt
> +铁傀儡也可以被润滑，治疗它们并暂时增加它们的速度和力量。
我找不到有问题的句子，麻烦 @TUsama 指出具体位置，谢谢。

2021-08-17 00:42 UTC, TUsama commented on projects/1.16/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/lubricant.txt
> +铁傀儡也可以被润滑，治疗它们并暂时增加它们的速度和力量。
铁傀儡也可以被润滑，治疗它们并暂时增加它们的速度和力量。

此句按照分句结构，第二分句若未声明主语，则主语应跟随第一分句，例如：
> 我昨天吃了苹果，今天吃了梨子。
这句话单独成句应为：
>我昨天吃了苹果。
>我今天吃了梨子。
可以看到主语是分句继承的。

在本句中，“治疗它们并暂时增加它们的速度和力量”，语义正确的主语应为第一分句，即第一分句整句作为第二分句的主语。一般而言，你可以使用“这样”来指代前句，例如：
> 铁傀儡也可以被润滑，这样可以治疗它们，并暂时增加它们的速度和力量。

2021-08-18 00:49 UTC, mcBegins2Snow commented
@TUsama 之前发现的问题已得到全部解决，可根据情况进行二次审查或合并。

2021-08-18 00:50 UTC, merged