[R]把biomancy汉化同步到这边
CFPAOrg/Minecraft-Mod-Language-Package pull request #1266
Opened 2021-08-19 14:26 UTC by SlimeSB

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [x] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-08-20 03:47 UTC, TUsama requested changes

2021-08-20 03:47 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "item.biomancy.rejuvenating_mucus": "复原粘液",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "item.biomancy.rejuvenating_mucus": "复原黏液",

```
到底是“黏液”，还是“粘液”？如何取舍？_ni
https://www.sohu.com/a/295341566_681842

2021-08-20 03:47 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "enchantment.biomancy.attuned_bane": "共鸣克星",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

或可遵循原版命名规则。
节肢杀手 (Bane of Arthropods) - [MC]我的世界原版 (Minecraft) - MC百科|最大的Minecraft中文MOD百科
https://www.mcmod.cn/item/132459.html

2021-08-20 03:47 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "tooltip.biomancy.leech_claw": "攻击会回复造成伤害 50% 的生命。\n还会在重击时获得 15 秒的额外生命，最多可叠加 5 层。",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "tooltip.biomancy.leech_claw": "攻击会恢复造成伤害 50% 的生命值。\n还会在暴击时获得 15 秒的伤害吸收效果，效果强度最多叠加 5 层。",
```
伤害吸收 (Absorption) - [MC]我的世界原版 (Minecraft) - MC百科|最大的Minecraft中文MOD百科
https://www.mcmod.cn/item/9399.html

伤害 - Minecraft Wiki，最详细的官方我的世界百科
https://minecraft.fandom.com/zh/wiki/%E4%BC%A4%E5%AE%B3#.E6.9A.B4.E5.87.BB

回复虽有恢复之意，但为何不直接使用恢复？

2021-08-20 03:47 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "item.biomancy.single_item_bag": "物品胃囊",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

这里原文有个 small，为何翻译没有体现出来？

2021-08-20 03:47 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "item.biomancy.fleshborn_pickaxe": "血肉镐",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

fleshborn 翻译为“血肉”，有何考量？

2021-08-20 03:47 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "tooltip.biomancy.fleshborn_pickaxe": "可以同时挖掘3x3的方块（按住潜行禁用）只会挖掘相同的方块。",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "tooltip.biomancy.fleshborn_pickaxe": "可以同时挖掘 3x3 的方块（潜行时禁用），只会挖掘相同的方块。",

```

sneak to disable，直译即为潜行时禁用，“按住潜行禁用”句意不明，是指“按住潜行键禁用”，还是“保持潜行禁用”？只有后者是对的，前者在按下按键（无需长按）即可切换为潜行模式的情况下，是表述有问题的。

2021-08-20 03:47 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "tooltip.biomancy.oculus_key": "将所有者的血清与该钥匙合成之后，即可用来锁定方块。",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

句意有误，重译。这次直译。

2021-08-20 03:47 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "tooltip.biomancy.injection_device": "允许你将试剂注入生物或块中（有些试剂不能被注入任何东西中）\n潜行单击可以装填/卸载副手玻璃瓶或试管中的液体。\n未装载液体时，可以从生物中提取血样。",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "tooltip.biomancy.injection_device": "能让你将试剂强制注入生物或方块中（有些试剂不能被注入任何东西中）\n潜行状态下单击可以装填/卸载副手玻璃瓶或试管中的液体。\n未装载液体时，可以从生物中提取血样。",

```
表述遗漏。

2021-08-20 03:47 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "tooltip.biomancy.withershot": "射出小而致命的凋灵骷髅头。当击杀目标后回复持有者的生命。\n使用凋灵骷髅头作为弹药。",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

如果上文使用了恢复，那么这里也需换为恢复。

2021-08-20 03:47 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "tooltip.biomancy.boomling": "一种跟踪热源的药水装载生物。\n与喷溅型药水合成可以设置其药水效果。\n丢出后可以潜行右击收回。",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

全部错译，看错行了？

2021-08-20 03:47 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "tooltip.biomancy.growth_serum": "促进作物生长，包括甘蔗、仙人掌和地狱疣。",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "tooltip.biomancy.growth_serum": "促进作物生长，包括甘蔗、仙人掌和下界疣。",

```
原版词汇需要加强记忆。

2021-08-20 03:47 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "tooltip.biomancy.rejuvenation_serum": "还原植物或动物。",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "tooltip.biomancy.rejuvenation_serum": "还原植物或动物的生长状态。",

```
为啥你的句子总是缺斤少两？

2021-08-20 03:47 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "tooltip.biomancy.reagent": "注射后会复原生物或方块的奇异物质。",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

疑似错译？原文没有“还原”之意。

2021-08-20 03:47 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "tooltip.biomancy.cleansing_serum": "移除所有药水效果,移除肉块中所有遗传物质。",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

标点符号。其他地方也有，自查。

2021-08-20 03:47 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "tooltip.biomancy.insomnia_cure": "重置上次睡眠时间，你不再需要睡觉了……",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

这个是用来干嘛的。

2021-08-20 03:47 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "tooltip.biomancy.mining_bonus": "当挖掘 %1$s：",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
  "tooltip.biomancy.mining_bonus": "当挖掘%1$s时：",

```
如果占位符肯定是数字或英文，那么用空格，如果不是，比较建议不加空格。

2021-08-20 03:47 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "advancements.biomancy.root.description": "血肉非常有用……",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "advancements.biomancy.root.description": "生肉非常有用……",

```

2021-08-20 03:56 UTC, SlimeSB commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "item.biomancy.rejuvenating_mucus": "复原粘液",
了解了。顺便一提mucus在参考词典上有粘液，来源是morebees模组。

2021-08-20 04:08 UTC, SlimeSB commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "item.biomancy.fleshborn_pickaxe": "血肉镐",
听着比较badass。fleshborn译作血肉中诞生的？我想保留其带有一些生命的要素，这边把fleshborn都译作血肉了。

2021-08-20 04:09 UTC, SlimeSB commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "tooltip.biomancy.insomnia_cure": "重置上次睡眠时间，你不再需要睡觉了……",
失眠治疗剂是可以刷新睡眠计时器，幻翼就不再刷了。

2021-08-20 05:31 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "item.biomancy.fleshborn_pickaxe": "血肉镐",
但是很明显，flesh就已经是血肉了，born没体现出来。这个是怎么合成出来的？

2021-08-20 07:10 UTC, SlimeSB commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "item.biomancy.fleshborn_pickaxe": "血肉镐",
你有什么好的建议吗，如果非要把born加上我想不出什么好的名字。

2021-08-20 07:14 UTC, SlimeSB commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "tooltip.biomancy.boomling": "一种跟踪热源的药水装载生物。\n与喷溅型药水合成可以设置其药水效果。\n丢出后可以潜行右击收回。",
我去vsc看了没啊

2021-08-20 07:28 UTC, SlimeSB commented
我草，作者添东西了，怪我没细看，我先改改，好了和你说 @TUsama

2021-08-21 03:59 UTC, SlimeSB reviewed
@TUsama done了，请审查

2021-08-21 04:11 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "item.biomancy.long_range_claw": "细长指爪",
可

2021-08-21 04:18 UTC, TUsama requested changes

2021-08-21 04:18 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "tooltip.biomancy.absorption_boost": "提供可堆叠的吸收生命值。",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

不要让我把每个伤害吸收都标注出来吧。。。这个文本你应该比我熟。

2021-08-21 04:18 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "tooltip.biomancy.gulge": "可以储存32k相同物品，在被采集时保存其中物品。",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

上次忘记和你说了，中文和非中文之间最好是加空格，占位符只有在肯定是数字/英文的情况下才会加空格。物品名称内不加空格。

2021-08-21 04:18 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "enchantment.biomancy.attuned_bane_of": "%1$s 杀手",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

例如这里，占位符内容肯定是中文，所以就不用加空格了。

2021-08-21 04:19 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "item.biomancy.fleshborn_pickaxe": "血肉镐",
这个是怎么弄出来的？有生命吗？还是说仅仅是一种无生命材料？

2021-08-21 06:06 UTC, SlimeSB commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "enchantment.biomancy.attuned_bane_of": "%1$s 杀手",
还可以的player的

2021-08-21 06:10 UTC, SlimeSB commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "item.biomancy.fleshborn_pickaxe": "血肉镐",
用镐子、生物合金和荷尔蒙胆汁在进化池里合成的，没有像其他有生命物品的动画（如关刀）。
我觉得这应该是一种被改造的生物，改造成了镐子的形状。

2021-08-21 08:40 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "enchantment.biomancy.attuned_bane_of": "%1$s 杀手",
直接就是player杀手？怪，但也不保留，其他的都是中文了。

2021-08-21 08:46 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "item.biomancy.fleshborn_pickaxe": "血肉镐",
赋生血肉，如何？

2021-08-21 08:47 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "item.biomancy.fleshborn_pickaxe": "血肉镐",
想了几个都不太满意，就这个稍微好一些，要是不行就算了。

2021-08-21 13:32 UTC, SlimeSB commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "item.biomancy.fleshborn_pickaxe": "血肉镐",
叫复生血肉呢? @TUsama

2021-08-21 13:35 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "item.biomancy.fleshborn_pickaxe": "血肉镐",
这个赋字，我主要是想强调是玩家赋予的意思，你这个复则强调的是重新的意思，你看你喜欢哪个你就要哪个吧。

2021-08-21 13:54 UTC, SlimeSB commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "item.biomancy.fleshborn_pickaxe": "血肉镐",
我想了一下，觉得还是重生血肉或者重铸血肉比较好 @TUsama ，就是彻彻底底的变了一种形态，也和模组名血肉重铸相合

2021-08-21 13:55 UTC, TUsama commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "item.biomancy.fleshborn_pickaxe": "血肉镐",
重生可，重铸有点远了。

2021-08-21 14:05 UTC, SlimeSB commented on projects/1.16/assets/biomancy/biomancy/lang/zh_cn.json
> +  "item.biomancy.fleshborn_pickaxe": "血肉镐",
done@TUsama

2021-08-22 00:11 UTC, merged