[1.12.2/1.16.5] 星辉、神秘、打粉机革新
CFPAOrg/Minecraft-Mod-Language-Package pull request #1279
Opened 2021-08-29 15:44 UTC by WuzgXY-GitHub

2021-08-30 01:30 UTC, TUsama requested changes

2021-08-30 01:30 UTC, TUsama commented on projects/1.12.2/assets/1UNKNOWN/enderio/lang/zh_cn.lang
> +tile.block_decoration2.type08.name=半自磨机（装饰方块）
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

需要考量。

2021-08-30 01:30 UTC, TUsama commented on projects/1.12.2/assets/astral-sorcery/astralsorcery/lang/zh_cn.lang
> +astralsorcery.constellation.evorsio.ritual=经仪式基座发散的星辉仍然拥有其本源内蕴含的强大破坏力，将破坏附近的任意固体物质。
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

你改仪式基座，不如改星能力。跑一下脚本就能够迁移了，因为value都是一样的。

叫做效应放大器还是仪式基座不影响游玩，但是星能力机翻真的很影响游玩。

2021-08-30 01:30 UTC, TUsama commented on projects/1.12.2/assets/thaumcraft/thaumcraft/lang/zh_cn.lang
> +item.thaumostatic_harness.name=奥法背带
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

这部分的修改至少得等公示板出来以后才行，否则影响很大。

但是TC6不是没有这东西吗，为什么这里还是有键值对。

2021-08-30 01:31 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/astral-sorcery/astralsorcery/lang/zh_cn.lang
> +astralsorcery.constellation.evorsio.ritual=经仪式基座发散的星辉仍然拥有其本源内蕴含的强大破坏力，将破坏附近的任意固体物质。
哦对，星能力我忘了改了，你可以直接往这个 branch 里写入

2021-08-30 01:32 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/thaumcraft/thaumcraft/lang/zh_cn.lang
> +item.thaumostatic_harness.name=奥法背带
不知道，我批量替换的

2021-09-11 04:04 UTC, TUsama commented on projects/1.12.2/assets/astral-sorcery/astralsorcery/lang/zh_cn.lang
> +astralsorcery.constellation.evorsio.ritual=经仪式基座发散的星辉仍然拥有其本源内蕴含的强大破坏力，将破坏附近的任意固体物质。
星能力我搞定了。

2021-09-30 16:11 UTC, baka-gourd commented
改改就合了

2021-10-01 07:27 UTC, WuzgXY-GitHub commented
半自磨机怎么来

2021-10-02 05:24 UTC, baka-gourd commented
> 半自磨机怎么来

还是SAG吧，在同意的情况下无需更改

2021-10-02 06:25 UTC, merged

2021-12-18 14:51 UTC, WuzgXY-GitHub commented
两个月前的我好像不小心把 SAG 搞没了，变成半自磨机了。