[R]1.16沉浸工程翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #1295
Opened 2021-09-05 10:02 UTC by mc-kaishixiaxue

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [x] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

mod作者仓库也同步提交 https://github.com/BluSunrize/ImmersiveEngineering/pull/4955

2021-09-06 08:46 UTC, TUsama requested changes
多方块。

2021-09-06 08:46 UTC, TUsama commented on projects/1.16/assets/immersive-engineering/immersiveengineering/manual/zh_cn/fluid_transport.txt
> +你可以用工程师锤右键管道的连接部分，以防止它连接到另一边。
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

请使用“右击”“左击”，而不是“右键”“左键”。

2021-09-06 08:46 UTC, TUsama commented on projects/1.16/assets/immersive-engineering/immersiveengineering/manual/zh_cn/fluid_transport.txt
> +用你的锤子在泵的基座上右键将会在输入和输出之间切换。<np>
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
用你的锤子在泵的基座上右击，你可以切换基座的输入和输出。<np>
```

2021-09-06 08:46 UTC, TUsama commented on projects/1.16/assets/immersive-engineering/immersiveengineering/manual/zh_cn/logic_circuits.txt
> +有了<link;redstone_wire;红石线圈>的巨大速度和多功能性以及<link;components;真空管;tubes>的独特属性，现在可以大大减少复杂红石电路的占地面积。
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

我不太确定IE的这个link的语法，如果这里的这个语法是对的话，那请resolve这条review。

2021-09-06 08:46 UTC, TUsama commented on projects/1.16/assets/immersive-engineering/immersiveengineering/manual/zh_cn/logic_circuits.txt
> +可用的输入和输出是红石线的16个彩色频道，以及8个“寄存器”。这些允许在处理逻辑的块中临时存储一个值——稍后会有更多关于这个的内容。
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
可用的输入和输出是红石线的16个彩色频道，以及8个“寄存器”。这些频道与寄存器能够在处理逻辑的方块中临时存储一个值——稍后会有更多关于这个的内容。
```

2021-09-06 08:46 UTC, TUsama commented on projects/1.16/assets/immersive-engineering/immersiveengineering/manual/zh_cn/logic_circuits.txt
> +<&unit>逻辑单元是在其中插入已完成的逻辑电路板以供使用的方块。它有足够的空间容纳总共§210个电路板§r，并具有完整的§28个内置寄存器§r，允许它用于任何电路。
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
<&unit>逻辑单元是在其中插入已完成的逻辑电路板以供使用的方块。它有足够的空间容纳总共§210个电路板§r，并具有完整的§28个内置寄存器§r，它能用于任何电路。
```

2021-09-06 08:46 UTC, TUsama commented on projects/1.16/assets/immersive-engineering/immersiveengineering/manual/zh_cn/metal_press.txt
> +<&multiblock>金属冲压机可用于一些金属的自动化成型。它用一个高压活塞将模具压到金属锭上，将其成型为金属板材，金属杆或其他金属元件。
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
<&multiblock>金属冲压机可用于一些金属的自动化成型。它用一个高压活塞将模具压到金属锭上，将其成型为金属板材，金属棒或其他金属元件。
```
前段时间库里统一了金属棒的称呼。机械制造中用到的棒材统一为x棒，不再使用x杆。

2021-09-06 08:46 UTC, TUsama commented on projects/1.16/assets/immersive-engineering/immersiveengineering/manual/zh_cn/minerals.txt
> +在你的世界中发现的矿床分布对你来说并不新鲜.而如今我们一直忽略的是矿脉,其中混合着多种矿石的存在.由于它们细长的分布,普通的矿工难以发现它们,但一种<link;excavator;特殊机器>或许能够提供一些帮助.
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

标点符号问题。

2021-09-06 08:46 UTC, TUsama commented on projects/1.16/assets/immersive-engineering/immersiveengineering/manual/zh_cn/minerals.txt
> +<&survey_tools>要开始寻找矿脉，你需要使用§2矿物探测器§r。四处冒险并在自然土壤的各种块上使用该工具，你可以确定矿脉和找到他们的近似位置。
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
<&survey_tools>要开始寻找矿脉，你需要使用§2矿物探测器§r。四处冒险并在自然土壤的各种方块上使用该工具，你可以确定矿脉和找到他们的大概位置。
```

2021-09-06 08:46 UTC, TUsama commented on projects/1.16/assets/immersive-engineering/immersiveengineering/manual/zh_cn/mixer.txt
> +这台机器最常见的用途是将水、两份沙子、一份粘土和一份沙砾混合成流体混凝土，或用水和各种配料制造药水。
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
这台机器最常见的用途是将水、两份沙子、一份黏土和一份沙砾混合成流体混凝土，或用水和各种配料制造药水。
```

2021-09-06 08:46 UTC, TUsama commented on projects/1.16/assets/immersive-engineering/immersiveengineering/manual/zh_cn/multiblocks.txt
> +除非你有魔法或者缩小光线，否则在1x1x1大小的空间内搭建复杂的机器是一件极其艰难的任务。为了能搭建出拥有更为复杂的操作系统的机器，你需要用到组装块。那些最为常见的将在下面揭晓。
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
除非你有魔法或者缩小光线，否则在1x1x1大小的空间内搭建复杂的机器是一件极其艰难的任务。为了能搭建出拥有更为复杂的操作系统的机器，你需要用到组装方块。那些最为常见的将在下面揭晓。
```
为什么总是少个“方”？

2021-09-06 12:39 UTC, mc-kaishixiaxue commented on projects/1.16/assets/immersive-engineering/immersiveengineering/manual/zh_cn/logic_circuits.txt
> +有了<link;redstone_wire;红石线圈>的巨大速度和多功能性以及<link;components;真空管;tubes>的独特属性，现在可以大大减少复杂红石电路的占地面积。
这是在工程师手册跳转到特定资料的内部链接，就像网页的超链接一样。

2021-09-06 13:05 UTC, mc-kaishixiaxue commented on projects/1.16/assets/immersive-engineering/immersiveengineering/manual/zh_cn/minerals.txt
> +在你的世界中发现的矿床分布对你来说并不新鲜.而如今我们一直忽略的是矿脉,其中混合着多种矿石的存在.由于它们细长的分布,普通的矿工难以发现它们,但一种<link;excavator;特殊机器>或许能够提供一些帮助.
其他存在同样问题的文件也一并进行了彻底修改。

2021-09-06 13:46 UTC, mc-kaishixiaxue commented
第一次修改审查问题时，发现资源包的汉化内容和[IE官方的仓库](https://github.com/BluSunrize/ImmersiveEngineering)差别太大，为保险起见，需要二次审查。

2021-09-10 03:47 UTC, mc-kaishixiaxue commented
@TUsama 审查时发现的问题已全部修改，且好几天没有回复。

2021-09-10 11:46 UTC, TUsama requested changes

2021-09-10 11:46 UTC, TUsama commented on projects/1.16/assets/immersive-engineering/immersiveengineering/manual/zh_cn/bullets.txt
> +<&ap>§l穿甲弹§r可以使用“普通子弹”蓝图制作。它们能够造成同等伤害但却能用高动能穿透装甲。<np>
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

盔甲？

2021-09-10 11:46 UTC, TUsama commented on projects/1.16/assets/immersive-engineering/immersiveengineering/manual/zh_cn/hemp.txt
> +它们可以像皮革护甲一样被染色。
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

盔甲。

2021-09-10 11:46 UTC, TUsama commented on projects/1.16/assets/immersive-engineering/immersiveengineering/manual/zh_cn/revolver.txt
> +请注意，射击左轮手枪是相当嘈杂的，并将吸引在该地区敌对生物的注意！
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

```suggestion
请注意，左轮手枪射击会发出巨大的声响，并将吸引在该地区敌对生物的注意！
```
用词和表述过于古怪。

2021-09-10 11:46 UTC, TUsama commented on projects/1.16/assets/immersive-engineering/immersiveengineering/manual/zh_cn/squeezer.txt
> +物品可以通过蓝色点标记的后面的两个舱口输入到挤压机。带有橙色圆点的舱口作为物品输出，它下面的块输出流体。
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
物品可以通过蓝色点标记的后面的两个舱口输入到挤压机。带有橙色圆点的舱口作为物品输出，它下面的方块输出流体。
```

2021-09-10 11:46 UTC, TUsama commented on projects/1.16/assets/immersive-engineering/immersiveengineering/manual/zh_cn/skyhook.txt
> +当天钩到达一个交叉路口时，它将尽可能接近玩家所看到的方向继续移动。
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

还请回复一下这两句的原文，表述有点奇怪。

2021-09-10 11:46 UTC, TUsama commented on projects/1.16/assets/immersive-engineering/immersiveengineering/manual/zh_cn/tank.txt
> +储罐是一个多方块结构，为大量的液体提供了空间。它可以储存多达512桶的任何液体，这些液体可以用管道通过顶部或底部的方块输入。液体只能从底部中心块中提取。
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
储罐是一个多方块结构，为大量的液体提供了空间。它可以储存多达512桶的任何液体，这些液体可以用管道通过顶部或底部的方块输入。液体只能从底部中心方块中提取。
```

2021-09-10 11:46 UTC, TUsama commented on projects/1.16/assets/immersive-engineering/immersiveengineering/manual/zh_cn/tank.txt
> +将红石信号用于底部中心块将使储罐自动输出，放置在那里的比较器将发出与其满度相关的红石信号。将比较器附加到上面的层之一，可以产生与比较器的高度成比例的信号。例如，一个附在第二层的比较器不会发出任何信号，直到储罐是1/4满，并发出强度15的信号，如果储罐是半满或更多。
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

这句话是什么意思？最后的那个“如果”是句中的那一部分的条件？

2021-09-10 11:46 UTC, TUsama commented on projects/1.16/assets/immersive-engineering/immersiveengineering/manual/zh_cn/tesla_coil.txt
> +这台机器的维护成本很高，被动消耗256Flux，加上每次施加伤害时额外的512Flux。
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

原文的消耗单位就是这个吗？消耗能量的单位内没有时间，有点奇怪。

2021-09-10 11:46 UTC, TUsama commented on projects/1.16/assets/immersive-engineering/immersiveengineering/manual/zh_cn/turrets.txt
> +默认情况下，该列表是不可能被攻击的目标的黑名单。此列表使用生物名称，因此白名单动物是可能的。<np>
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

这句话在说什么？

2021-09-11 01:41 UTC, mc-kaishixiaxue commented on projects/1.16/assets/immersive-engineering/immersiveengineering/manual/zh_cn/tesla_coil.txt
> +这台机器的维护成本很高，被动消耗256Flux，加上每次施加伤害时额外的512Flux。
已查看原文，的确是Flux，不是Flux/t。

2021-09-11 03:58 UTC, TUsama approved these changes

2021-09-11 04:00 UTC, TUsama commented
若无修改，我就merge了。

2021-09-11 04:23 UTC, mc-kaishixiaxue commented
@TUsama 已完成修改，并做好merge的准备。

2021-09-11 04:23 UTC, merged