[WIP]做一下侏罗纪世界重生的汉化
CFPAOrg/Minecraft-Mod-Language-Package pull request #1320
Opened 2021-09-18 13:21 UTC by SlimeSB

- [ ] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [ ] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [ ] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [ ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [ ] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [ ] 我已上传英文文件以供审查；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-09-20 02:25 UTC, SlimeSB commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +tile.dna_combinator_hybridizer.name=DNA 混合提升器
直译是混合杂交，与装置功能不符。虽然我没看出来哪里可以混合或是杂交……只能提升DNA质量这样。

2021-09-20 02:26 UTC, SlimeSB commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +item.paleo_pad.name=Paleo Pad
咋办啊，古pad？太难听了

2021-09-20 02:27 UTC, SlimeSB commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +tile.tour_rail_slow.name=[速度缓慢]旅游车轨道
我觉得这个括号不太好，但是要改顺便也要把jurassicarft里同key的改了。是否有必要？

2021-09-20 06:09 UTC, SlimeSB commented
@TUsama 可以开始审了，draft状态等我做完或者事多了再转。

2021-09-21 09:15 UTC, TUsama commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +item.paleo_pad.name=Paleo Pad
用来干嘛的？

2021-09-21 09:17 UTC, TUsama commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +tile.dna_combinator_hybridizer.name=DNA 混合提升器
遇到这种事情，先想一想：为什么作者不改原文呢？除非是作者弃坑了，要不然持续更新且这个名字一直没变化，那么肯定是自己理解有问题，而不是原文有问题。

2021-09-21 09:17 UTC, TUsama commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +tile.tour_rail_slow.name=[速度缓慢]旅游车轨道
无。

2021-09-21 09:28 UTC, SlimeSB commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +tile.dna_combinator_hybridizer.name=DNA 混合提升器
@TUsama 那我就不动了，这个也是从jurassicraft同步过来的

2021-09-21 09:32 UTC, SlimeSB commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +tile.tour_rail_slow.name=[速度缓慢]旅游车轨道
ok

2021-09-21 09:35 UTC, TUsama requested changes

2021-09-21 09:35 UTC, TUsama commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +attraction_sign.aviary_plants.name=涵盖植物的鸟舍
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

我不太认为这里可以使用“涵盖”这一动词，以下摘录于百度百科：

>  B涵盖C是范畴关系上的，意思是B范畴的正反两个性质演绎了C范畴下所有外延的个体性质，即B的性质是C的本质。“涵盖”属于概念内涵意义上的概念。而B包含C说的是个体种类关系，意思为B是类而C是种。“包含”属于概念外延意义上的概念。

“植物”并不是作为后者概念上的内涵内容，甚至与后者之间不存在着必要的逻辑关系。况且，涵盖一词用于表述概念内涵之意表明，其后多接抽象概念，而不是具象概念。我更为建议这里直接使用“长有植物的鸟舍”。

2021-09-21 09:35 UTC, TUsama commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +item.tusk.name={dino} 象牙
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

自查忘删空格。

2021-09-21 09:35 UTC, TUsama commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +item.ingen_journal.name=基因日记
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

这个是模组的教程吗？你要对英文的大写敏感一些，名字类的单词都是大写的，这里的 InGen 就是如此。你可以考虑加一个书名号括起来，比如，医学类期刊《柳叶刀》的英文就是 The Lancet。

2021-09-21 09:35 UTC, TUsama commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +tile.araucaria_stairs.name=南洋杉木楼梯
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

不用加“木”，具体参考原版对应物品命名。

2021-09-21 09:35 UTC, TUsama commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +tile.calamites_stairs.name=芦木楼梯
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

但是这里不可少“木”。

2021-09-21 09:35 UTC, TUsama commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +plants.wild_potato.name=野生土豆
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

马铃薯。因为这个和原版的马铃薯有潜在的关联性。

那么其他文本里的土豆也要改了。

2021-09-21 09:35 UTC, TUsama commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +spawnegg.genderchange.name=这个蛋现在会生成一个{mode}生物。
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

注意量词。

2021-09-21 09:41 UTC, SlimeSB commented
@TUsama 擦，好多都是原来文本留下的。我以为入库已经审过一遍就没细审。看来那边也要重做一下。

2021-09-21 09:47 UTC, TUsama commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +item.paleo_pad.name=Paleo Pad
寻古平板？

2021-09-21 09:48 UTC, SlimeSB commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +item.paleo_pad.name=Paleo Pad
![HGYN6QS6J5}3F25624LJ)Q](https://user-images.githubusercontent.com/86453765/134149782-5cb4caf9-6e94-4d20-8641-ae8e2b62552a.png)
![ZV70_}BST TAG {NCV_)%M5](https://user-images.githubusercontent.com/86453765/134149846-9837fc33-6fd9-47ec-a4b5-1fa6693ba912.png)

这个古pad是可以追踪被打了标记的恐龙 @TUsama

2021-09-21 09:59 UTC, SlimeSB commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +spawnegg.genderchange.name=这个蛋现在会生成一个{mode}生物。
我觉得“一个雄性生物“没有什么不妥的，至少不是特别大的错误。我之后把”随机性别”改成“随机性别的” @TUsama 
话说我不带AT回复，你能收到通知吗？能我就不带了。

2021-09-21 12:14 UTC, SlimeSB commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +item.ingen_journal.name=基因日记
额，有必要吗？没见过几个guide book是加书名号的。
而且这里的基因日记也就是记录一些研究中的故事，所以我觉得不用加。

2021-09-21 13:26 UTC, SlimeSB commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +tile.araucaria_stairs.name=南洋杉木楼梯
是南洋杉楼梯吗，但金合欢木楼梯？

2021-09-21 15:04 UTC, SlimeSB commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +item.paleo_pad.name=Paleo Pad
@TUsama 改成远古生物平板电脑了，相关wiki上写是“恐龙平板电脑”的进化版

2021-09-21 15:06 UTC, SlimeSB commented
@TUsama 有时间再审一遍吧，后面长文本我不弄了。然后文件有什么格式需要注意吗，比如注释要删？

2021-09-22 04:41 UTC, TUsama commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +item.ingen_journal.name=基因日记
那是因为它们没大写啊，那这里有大写了你还和没大写一样处理，你觉得好吗？

2021-09-22 04:42 UTC, TUsama commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +tile.araucaria_stairs.name=南洋杉木楼梯
所以原版译名也很混乱，你可以看一下库里面的Abnormal系列翻译的译名，这些是我们统一过了的。

2021-09-22 04:43 UTC, TUsama commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +spawnegg.genderchange.name=这个蛋现在会生成一个{mode}生物。
可以收到。那就不带了，我还以为这里是“一只xx龙”。

2021-09-22 04:43 UTC, TUsama commented
最好删了。

2021-09-22 04:46 UTC, TUsama commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +item.ingen_journal.name=基因日记
考虑了一下，如果是日记类的文本的话，那实在是没有必要大写，那就这样吧。

2021-09-22 05:08 UTC, Lyaiya commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +tile.araucaria_stairs.name=南洋杉木楼梯
1.12 原版译名确实很不统一，而 1.16 会好很多。在 1.16，除了原版的 Wood、Log、Leaves/Sapling 这几个要斟酌一下，像是楼梯台阶之类的，前面一般都加上“木”字的。如果是用“南洋衫木板”做的话，我建议是“南洋杉木楼梯”。

2021-09-22 06:02 UTC, TUsama commented on projects/1.12.2/assets/jurassic-world-reborn-mod/rebornmod/lang/zh_cn.lang
> +tile.araucaria_stairs.name=南洋杉木楼梯
好，现在我也被弄晕了。

2021-09-22 07:44 UTC, SlimeSB commented
@TUsama 没问题就可以merge了

2021-09-22 07:46 UTC, merged