[W] 添加/修改汉化文件
CFPAOrg/Minecraft-Mod-Language-Package pull request #1329
Opened 2021-09-22 09:35 UTC by AtropsCooper

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [x] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [ ] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-09-22 12:42 UTC, TUsama requested changes

2021-09-22 12:42 UTC, TUsama commented on projects/1.16/assets/aiot-botania/aiotbotania/lang/zh_cn.json
> +  "itemGroup.aiotbotania": "植魔全能工具",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

在正文中，请勿使用模组中文缩写。

2021-09-22 12:42 UTC, TUsama commented on projects/1.16/assets/aiot-botania/aiotbotania/lang/zh_cn.json
> +  "aiotbotania.toggleMode": "\u00a76模式:",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

请自查英文标点符号问题。

2021-09-22 12:42 UTC, TUsama commented on projects/1.16/assets/aiot-botania/aiotbotania/lang/zh_cn.json
> +  "item.aiotbotania.livingwood_shovel": "活木铲",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "item.aiotbotania.livingwood_shovel": "活木锹",
```
原版译名。

2021-09-22 12:42 UTC, TUsama commented on projects/1.16/assets/aiot-botania/aiotbotania/lang/zh_cn.json
> +  "botania.page.livingwoodTools0": "若安装植魔全能工具模组，$(1)活木$(0)可以被制造成工具。<br>这些工具有着$(1)木头工具$(0)，不过在附魔和耐久上有较大优势。$(1)活木$(0)工具将会消耗4魔力来破坏方块，如果在背包中有$(4)储魔物品$(0)(就比如说一块$(1)魔力石板$(0))，就会优先消耗石板中的魔力。<br>除了伤害以外，他们和原版
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

```suggestion
  "botania.page.livingwoodTools0": "若安装植魔全能工具模组，$(1)活木$(0)可以被制造成工具。<br>这些工具的属性与$(1)木工具$(0)类似，不过在附魔和耐久上有较大优势。$(1)活木$(0)工具将会消耗4魔力来破坏方块，如果在背包中有$(4)储魔物品$(0)(就比如说一块$(1)魔力石板$(0))，就会优先消耗石板中的魔力。<br>除了伤害以外，他们和原版工具没什么两样。",
```
其余地方有类似的错误。

2021-09-22 12:42 UTC, TUsama commented on projects/1.16/assets/buildersaddition/buildersaddition/lang/zh_cn.json
> +  "block.buildersaddition.quartz_vertical_slab": "石英竖直台阶",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

遵循夸克译名统一。应为“竖直xx台阶”。

2021-09-22 12:42 UTC, TUsama commented on projects/1.16/assets/earth-reworked/earthworks/lang/zh_cn.json
> +  "block.earthworks.vertical_dark_oak_slab": "竖纹深色橡台阶",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "block.earthworks.vertical_dark_oak_slab": "竖直深色橡木台阶",
```
我不太确定这里是不是竖直，但是至少少了个木字。还麻烦进游戏检查一下，还有下面的竖纹楼梯也许要检查。

2021-09-22 12:42 UTC, TUsama commented on projects/1.16/assets/earth-reworked/earthworks/lang/zh_cn.json
> +  "item.earthworks.chalk_dust": "白垩岩粉末",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "item.earthworks.chalk_dust": "粉笔灰",
```

2021-09-22 12:42 UTC, TUsama commented on projects/1.16/assets/earth-reworked/earthworks/lang/zh_cn.json
> +  "item.earthworks.planer": "手刨",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

？

2021-09-22 12:42 UTC, TUsama commented on projects/1.16/assets/earth-reworked/earthworks/lang/zh_cn.json
> +  "item.earthworks.lime_plaster": "生石灰泥",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

此处这个“泥”是否为必须？

2021-09-22 12:42 UTC, TUsama commented on projects/1.16/assets/earth-reworked/earthworks/lang/zh_cn.json
> +  "item.earthworks.square": "矩",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

什么意思？

2021-09-22 12:42 UTC, TUsama commented on projects/1.16/assets/exotic-birds/exoticbirds/lang/zh_cn.json
> +  "cage.exoticbirds.health": "血量：%s",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
  "cage.exoticbirds.health": "生命值：%s",

```

2021-09-22 12:42 UTC, TUsama commented on projects/1.16/assets/exotic-birds/exoticbirds/lang/zh_cn.json
> +  "book.exoticbirds.log_new": "发现新的 %s 变体！",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

此处占位符在游戏中的显示应该为中文，所以两边的空格得删除。

2021-09-22 12:42 UTC, TUsama commented on projects/1.16/assets/exotic-birds/exoticbirds/lang/zh_cn.json
> +  "exoticbirds.species.budgerigar_blue": "虎皮鹦鹉 （蓝色）",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

中文前括号前无需空格。

2021-09-22 12:42 UTC, TUsama commented on projects/1.16/assets/fins-and-tails/fins/lang/zh_cn.json
> +  "fins.mudhorse.ambient": "泥海马咕哝",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

这个是字幕吗。。？

2021-09-22 13:19 UTC, SlimeSB commented on projects/1.16/assets/aiot-botania/aiotbotania/lang/zh_cn.json
> +  "botania.page.livingwoodTools0": "若安装植魔全能工具模组，$(1)活木$(0)可以被制造成工具。<br>这些工具有着$(1)木头工具$(0)，不过在附魔和耐久上有较大优势。$(1)活木$(0)工具将会消耗4魔力来破坏方块，如果在背包中有$(4)储魔物品$(0)(就比如说一块$(1)魔力石板$(0))，就会优先消耗石板中的魔力。<br>除了伤害以外，他们和原版
木制工具会更好吧

2021-09-22 13:20 UTC, TUsama commented on projects/1.16/assets/aiot-botania/aiotbotania/lang/zh_cn.json
> +  "botania.page.livingwoodTools0": "若安装植魔全能工具模组，$(1)活木$(0)可以被制造成工具。<br>这些工具有着$(1)木头工具$(0)，不过在附魔和耐久上有较大优势。$(1)活木$(0)工具将会消耗4魔力来破坏方块，如果在背包中有$(4)储魔物品$(0)(就比如说一块$(1)魔力石板$(0))，就会优先消耗石板中的魔力。<br>除了伤害以外，他们和原版
也可以，我基本上是混用。

2021-09-22 14:29 UTC, AtropsCooper commented on projects/1.16/assets/aiot-botania/aiotbotania/lang/zh_cn.json
> +  "itemGroup.aiotbotania": "植魔全能工具",
已修正

2021-09-22 14:30 UTC, AtropsCooper commented on projects/1.16/assets/aiot-botania/aiotbotania/lang/zh_cn.json
> +  "botania.page.livingwoodTools0": "若安装植魔全能工具模组，$(1)活木$(0)可以被制造成工具。<br>这些工具有着$(1)木头工具$(0)，不过在附魔和耐久上有较大优势。$(1)活木$(0)工具将会消耗4魔力来破坏方块，如果在背包中有$(4)储魔物品$(0)(就比如说一块$(1)魔力石板$(0))，就会优先消耗石板中的魔力。<br>除了伤害以外，他们和原版
已修正

2021-09-22 14:30 UTC, AtropsCooper commented on projects/1.16/assets/earth-reworked/earthworks/lang/zh_cn.json
> +  "item.earthworks.square": "矩",
已修正

2021-09-22 14:30 UTC, AtropsCooper commented on projects/1.16/assets/exotic-birds/exoticbirds/lang/zh_cn.json
> +  "cage.exoticbirds.health": "血量：%s",
已修正

2021-09-22 14:30 UTC, AtropsCooper commented on projects/1.16/assets/exotic-birds/exoticbirds/lang/zh_cn.json
> +  "exoticbirds.species.budgerigar_blue": "虎皮鹦鹉 （蓝色）",
已修正

2021-09-22 14:30 UTC, AtropsCooper commented on projects/1.16/assets/fins-and-tails/fins/lang/zh_cn.json
> +  "fins.mudhorse.ambient": "泥海马咕哝",
已修正

2021-09-22 14:31 UTC, AtropsCooper commented on projects/1.16/assets/exotic-birds/exoticbirds/lang/zh_cn.json
> +  "book.exoticbirds.log_new": "发现新的 %s 变体！",
已修正

2021-09-22 14:40 UTC, AtropsCooper commented on projects/1.16/assets/earth-reworked/earthworks/lang/zh_cn.json
> +  "block.earthworks.vertical_dark_oak_slab": "竖纹深色橡台阶",
已补充“木”字。
游戏内材质为竖纹，扁平形状台阶。

2021-09-22 14:41 UTC, AtropsCooper commented on projects/1.16/assets/earth-reworked/earthworks/lang/zh_cn.json
> +  "item.earthworks.chalk_dust": "白垩岩粉末",
游戏内为建材，用于制造泥墙方块

2021-09-22 14:41 UTC, AtropsCooper commented on projects/1.16/assets/earth-reworked/earthworks/lang/zh_cn.json
> +  "item.earthworks.planer": "手刨",
木匠工具

2021-09-22 14:42 UTC, AtropsCooper commented on projects/1.16/assets/earth-reworked/earthworks/lang/zh_cn.json
> +  "item.earthworks.lime_plaster": "生石灰泥",
游戏内材质和粘土一致，“泥”为必须。

2021-09-23 04:54 UTC, AtropsCooper commented
发现 neoelfeos-medieval-pub-decoration 模组中翻译错误较多，正在修正中。

2021-09-23 08:00 UTC, AtropsCooper commented
neoelfeos-medieval-pub-decoration 模组翻译已修正完成。

2021-09-23 14:28 UTC, baka-gourd commented
这边建议把内容往标题上写写

2021-09-24 02:52 UTC, closed without merging