Update zh_cn.json
CFPAOrg/Minecraft-Mod-Language-Package pull request #1331
Opened 2021-09-23 06:09 UTC by Michael18811380328

- [ ] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [ ] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [ ] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [ ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [ ] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [ ] 我已上传英文文件以供审查；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-09-23 06:45 UTC, TUsama requested changes
友情邀请额外援助 @lunareclipse-64

2021-09-23 06:45 UTC, TUsama commented on projects/1.16/assets/geolosys/geolosys/lang/zh_cn.json
> +  "item.geolosys.field_manual": "现场手册",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "item.geolosys.field_manual": "野外探矿手册",
```
若无必要，译名需与1.12一致。

2021-09-23 06:45 UTC, TUsama commented on projects/1.16/assets/geolosys/geolosys/lang/zh_cn.json
> +  "item.geolosys.field_manual.landing": "你通过 Geolosys 进行勘探的指南。$(br2)$(l)$(#f00) 这本书正在进行中 $()$(br2)$(o)$(#f59b42) 记住可用的岩体，可能与 modpack 创建者列出的不同。$()",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
    "item.geolosys.field_manual.landing": "这本指导手册将会伴随你一起踏上 Geolosys 的探索之旅。$(br2)$(l)$(#f00)本书尚未编写完成。$()$(br2)$(o)$(#f59b42)请牢记，有效的岩体种类会随着整合包的不同而变化，具体内容请参看整合包作者所给出的岩体列表。$()",

```

2021-09-23 06:45 UTC, TUsama commented on projects/1.16/assets/geolosys/geolosys/lang/zh_cn.json
> +  "item.geolosys.prospectors_pick": "探矿者之选",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "item.geolosys.prospectors_pick": "探矿镐",
```
若无必要，译名需与1.12一致。

2021-09-23 06:45 UTC, TUsama commented on projects/1.16/assets/geolosys/geolosys/lang/zh_cn.json
> +  "geolosys.pro_pick.tooltip.found": "从你这里找到 %s %s",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "geolosys.pro_pick.tooltip.found": "找到了%s，距离你 %s 远",
```

2021-09-23 06:45 UTC, TUsama commented on projects/1.16/assets/geolosys/geolosys/lang/zh_cn.json
> +  "geolosys.pro_pick.tooltip.mode.ores": "§6 找矿床",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "geolosys.pro_pick.tooltip.mode.ores": "§6勘探矿物储量",
```

2021-09-23 06:45 UTC, TUsama commented on projects/1.16/assets/geolosys/geolosys/lang/zh_cn.json
> +  "geolosys.pro_pick.tooltip.mode.stones": "§b 寻找岩石矿床",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "geolosys.pro_pick.tooltip.mode.stones": "§b勘探石头储量",
```

2021-09-23 06:45 UTC, TUsama commented on projects/1.16/assets/geolosys/geolosys/lang/zh_cn.json
> +  "geolosys.download.error.string": "geolosys.json 矿床的配置文件既找不到也找不能下载。\n如果你愿意，你可以在 https://raw.githubusercontent.com/oitsjustjose/Geolosys/1.14.x/geolosys_ores.json 下载文件，并手动将其放入你的配置文件夹（需要将其重命名为 \"geol
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "geolosys.download.error.string": "矿床的配置文件 geolosys.json 既无法找到也无法下载。\n如果你愿意，你可以在 https://raw.githubusercontent.com/oitsjustjose/Geolosys/1.14.x/geolosys_ores.json 处下载文件，并手动将其放入你的配置文件夹（需要将其重命名为 \"geolosys.json\"）。"
```

2021-09-23 06:45 UTC, TUsama commented on projects/1.16/assets/geolosys/geolosys/lang/zh_cn.json
> +  "item.geolosys.ancient_debris_cluster": "古代遗迹聚集",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

```suggestion
  "item.geolosys.ancient_debris_cluster": "远古残骸矿簇",
```

2021-09-23 06:45 UTC, TUsama commented on projects/1.16/assets/geolosys/geolosys/lang/zh_cn.json
> +  "item.geolosys.iron_cluster": "铁簇",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

根据 1.12 的文件，此处应为xx矿簇，为何矿字全都没了？

2021-09-23 06:45 UTC, TUsama commented on projects/1.16/assets/geolosys/geolosys/lang/zh_cn.json
> +  "block.geolosys.ancient_debris_ore": "古代遗迹",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

```suggestion
  "block.geolosys.ancient_debris_ore": "远古残骸",
```

2021-09-23 06:45 UTC, TUsama commented on projects/1.16/assets/geolosys/geolosys/lang/zh_cn.json
> +  "block.geolosys.lignite_ore": "褐煤",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

如果是矿石，请务必在后面添加“矿”字。

2021-09-23 14:02 UTC, lunareclipse-64 requested changes
发之前能不能花个半分钟看看交的东西有多离谱？

2021-09-24 11:01 UTC, TUsama commented
由于质量过低，close。

2021-09-24 11:01 UTC, closed without merging

2021-09-24 13:40 UTC, Michael18811380328 commented on projects/1.16/assets/geolosys/geolosys/lang/zh_cn.json
> +  "item.geolosys.zinc_nugget": "锌块",
我查到的确实是“天然金块，矿块；（某些食物）小圆块”

2021-09-24 13:42 UTC, Michael18811380328 commented on projects/1.16/assets/geolosys/geolosys/lang/zh_cn.json
> +  "block.geolosys.nether_gold_ore_sample": "贫金样品",
好的，我和 1.12.2 保持一致