[R,P] 提交 realistic-horse-genetics 模组译文
CFPAOrg/Minecraft-Mod-Language-Package pull request #1334
Opened 2021-09-24 11:59 UTC by AtropsCooper

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [x] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-09-24 13:53 UTC, TUsama commented
基因名称保留的话，后面加上括号中文又是什么意思？

2021-09-24 14:13 UTC, AtropsCooper commented
> 基因名称保留的话，后面加上括号中文又是什么意思？

请问是否应该删除？

2021-09-24 14:14 UTC, TUsama commented
原文有，你就有；原文没有，你就别加。你是做翻译，不是弄资料。

2021-09-25 05:01 UTC, SlimeSB commented on projects/1.16/assets/realistic-horse-genetics/horse_colors/lang/zh_cn.json
> +    "horse_colors.genes.gray.name": "Grey",
？check一下en里怎么写的

2021-09-25 07:48 UTC, AtropsCooper commented on projects/1.16/assets/realistic-horse-genetics/horse_colors/lang/zh_cn.json
> +    "horse_colors.genes.gray.name": "Grey",
已修正

2021-09-25 10:46 UTC, TUsama requested changes

2021-09-25 10:46 UTC, TUsama commented on projects/1.16/assets/realistic-horse-genetics/horse_colors/lang/zh_cn.json
> +    "horse_colors.genes.KIT.name": "KIT（白色）",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

此处？

2021-09-25 10:51 UTC, TUsama commented
我刚刚看了一下，好像基因的名字是可以翻译的，你试着在网上找一下，应该是可以找到的。比如 Leopard Complex 为豹斑纹，champagne 为香槟，这两个都在 https://zh.wikipedia.org/zh-hans/%E8%AE%BE%E5%BE%B7%E5%85%B0%E7%9F%AE%E7%A7%8D%E9%A9%AC 中有翻译。

2021-09-25 10:56 UTC, TUsama commented
我突然意识到，你为什么不直接翻译，而是在后面加括号？

2021-09-25 11:00 UTC, AtropsCooper commented
> 我突然意识到，你为什么不直接翻译，而是在后面加括号？

因为部分可以翻译，另一部分不可以翻译，出于一致性考虑全部保留了原文。
另一个原因是游玩时若想查找相关文献时中文资料较少，关于马匹花色的中文论文中也也都保留了英文原文。

2021-09-26 03:27 UTC, TUsama commented
那就保留吧。

2021-09-26 03:27 UTC, merged