[R] 提交 neoelfeos-medieval-pub-decoration 模组译文
CFPAOrg/Minecraft-Mod-Language-Package pull request #1336
Opened 2021-09-24 12:01 UTC by AtropsCooper

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [x] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-09-24 13:47 UTC, TUsama requested changes

2021-09-24 13:47 UTC, TUsama commented on projects/1.16/assets/neoelfeos-medieval-pub-decoration/nefdecomod/lang/zh_cn.json
> +  "entity.nefdecomod.illager_lady_entity": "厄运村妇实体",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

灾厄还是厄运？

2021-09-24 13:47 UTC, TUsama commented on projects/1.16/assets/neoelfeos-medieval-pub-decoration/nefdecomod/lang/zh_cn.json
> +  "block.nefdecomod.alex_plushie": "Alex 玩偶",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

史蒂夫翻译了，为什么 Alex 没翻译？

2021-09-24 13:47 UTC, TUsama commented on projects/1.16/assets/neoelfeos-medieval-pub-decoration/nefdecomod/lang/zh_cn.json
> +  "block.nefdecomod.asian_half_plushie": "AsianHalfSquat 玩偶",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

亚洲蹲？

2021-09-24 13:50 UTC, AtropsCooper commented on projects/1.16/assets/neoelfeos-medieval-pub-decoration/nefdecomod/lang/zh_cn.json
> +  "block.nefdecomod.asian_half_plushie": "AsianHalfSquat 玩偶",
Youtuber 名字

2021-09-24 13:54 UTC, AtropsCooper commented on projects/1.16/assets/neoelfeos-medieval-pub-decoration/nefdecomod/lang/zh_cn.json
> +  "entity.nefdecomod.illager_lady_entity": "厄运村妇实体",
已修正为灾厄

2021-09-24 13:55 UTC, AtropsCooper commented on projects/1.16/assets/neoelfeos-medieval-pub-decoration/nefdecomod/lang/zh_cn.json
> +  "block.nefdecomod.alex_plushie": "Alex 玩偶",
已翻译为艾利克斯

2021-09-24 15:00 UTC, AtropsCooper commented on projects/1.16/assets/neoelfeos-medieval-pub-decoration/nefdecomod/lang/zh_cn.json
> +  "block.nefdecomod.alex_plushie": "Alex 玩偶",
已将史蒂夫与艾利克斯改回原文

2021-09-25 11:07 UTC, TUsama commented on projects/1.16/assets/neoelfeos-medieval-pub-decoration/nefdecomod/lang/zh_cn.json
> +  "block.nefdecomod.fruit_box_pumpkin": "木盒（南瓜）",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

每次你觉得你应该加文本的时候，先问一下自己：为什么作者不加？为什么没有人提出在原文中加？或者说有人提出加但作者没有允许？你考虑了这些之后，你就知道，你的工作应该是忠于原文的进行翻译，而不是在翻译中添加自己觉得有必要的文本。这里的这一处添加其实还好，加不加不会引起太多的分歧。但是这种行为切不可养成习惯，时刻牢记：翻译是翻译，搞资料是搞资料。

2021-09-25 11:07 UTC, TUsama commented on projects/1.16/assets/neoelfeos-medieval-pub-decoration/nefdecomod/lang/zh_cn.json
> +  "advancements.battlefield_adv.descr": "你进入了一个冲突区域",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
  "advancements.battlefield_adv.descr": "你进入了一片冲突区域",
```

2021-09-25 11:07 UTC, TUsama commented on projects/1.16/assets/neoelfeos-medieval-pub-decoration/nefdecomod/lang/zh_cn.json
> +  "block.nefdecomod.solar_clock": "日晷",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

确定是日晷吗？

2021-09-25 11:34 UTC, AtropsCooper commented on projects/1.16/assets/neoelfeos-medieval-pub-decoration/nefdecomod/lang/zh_cn.json
> +  "block.nefdecomod.fruit_box_pumpkin": "木盒（南瓜）",
对不起，这篇是别人翻译的，检查的时候漏下了

2021-09-25 11:35 UTC, AtropsCooper commented on projects/1.16/assets/neoelfeos-medieval-pub-decoration/nefdecomod/lang/zh_cn.json
> +  "block.nefdecomod.solar_clock": "日晷",
确认，游戏内此物品靠外装 Shader 后阳光打下模型的投影工作

2021-09-26 03:25 UTC, merged