[R,W] 提交 macaws-roofs 模组译文
CFPAOrg/Minecraft-Mod-Language-Package pull request #1341
Opened 2021-09-24 12:09 UTC by AtropsCooper

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [x] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-09-24 13:35 UTC, TUsama requested changes

2021-09-24 13:35 UTC, TUsama commented on projects/1.16/assets/macaws-roofs/mcwroofs/lang/zh_cn.json
> +  "block.mcwroofs.pink_terracotta_attic_roof":"粉色陶瓦天窗屋顶",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

应为“粉红色”。

2021-09-24 13:35 UTC, TUsama commented on projects/1.16/assets/macaws-roofs/mcwroofs/lang/zh_cn.json
> +  "block.mcwroofs.cobblestone_roof":"原石屋顶",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "block.mcwroofs.cobblestone_roof":"圆石屋顶",
```

2021-09-24 14:01 UTC, AtropsCooper commented on projects/1.16/assets/macaws-roofs/mcwroofs/lang/zh_cn.json
> +  "block.mcwroofs.pink_terracotta_attic_roof":"粉色陶瓦天窗屋顶",
已修正

2021-09-24 14:01 UTC, AtropsCooper commented on projects/1.16/assets/macaws-roofs/mcwroofs/lang/zh_cn.json
> +  "block.mcwroofs.cobblestone_roof":"原石屋顶",
已修正

2021-09-26 03:32 UTC, TUsama requested changes

2021-09-26 03:32 UTC, TUsama commented on projects/1.16/assets/macaws-roofs/mcwroofs/lang/zh_cn.json
> +  "block.mcwroofs.oak_planks_roof":"橡木板屋顶",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "block.mcwroofs.oak_planks_roof":"橡木木板屋顶",
```
把这个修正之后，你检查一下其他的macaw系列，看还有没有这种木板/原木作为材料的家具。
如果是木板做的，就 xx木板xx，比如橡木木板椅子。
如果是原木做的，就 xx原木xx。
如果有改动，修改后整合在一个 PR 里。麻烦了。
你把这个改完之后我会merge，merge完你再改吧。

2021-09-26 09:59 UTC, AtropsCooper commented on projects/1.16/assets/macaws-roofs/mcwroofs/lang/zh_cn.json
> +  "block.mcwroofs.oak_planks_roof":"橡木板屋顶",
已修正。
其他macaw系列正在检查。

2021-09-27 00:25 UTC, merged