[R] 提交 earth-reworked 模组译文
CFPAOrg/Minecraft-Mod-Language-Package pull request #1348
Opened 2021-09-24 12:13 UTC by AtropsCooper

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [x] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-09-24 13:57 UTC, SlimeSB commented on projects/1.16/assets/earth-reworked/earthworks/lang/zh_cn.json
> +  "block.earthworks.daub_cob_箭头 0": "木框架秸秆泥 箭头 0",
注意一下key

2021-09-24 14:13 UTC, AtropsCooper commented on projects/1.16/assets/earth-reworked/earthworks/lang/zh_cn.json
> +  "block.earthworks.daub_cob_箭头 0": "木框架秸秆泥 箭头 0",
已修正

2021-09-25 11:13 UTC, TUsama requested changes

2021-09-25 11:13 UTC, TUsama commented on projects/1.16/assets/earth-reworked/earthworks/lang/zh_cn.json
> +  "block.earthworks.vertical_oak_planks": "竖纹橡木板",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

少字。

2021-09-26 10:00 UTC, AtropsCooper commented on projects/1.16/assets/earth-reworked/earthworks/lang/zh_cn.json
> +  "block.earthworks.vertical_oak_planks": "竖纹橡木板",
已修正

2021-09-27 00:25 UTC, merged