[R] 提交 Accurate Block Placement 模组译文
CFPAOrg/Minecraft-Mod-Language-Package pull request #1354
Opened 2021-09-26 15:13 UTC by TACGqwq

- [ x ] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [ x ] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [ x ] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [ x ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [ x ] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [ x ] 我已上传英文文件以供审查；
- [ x ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-09-27 00:28 UTC, TUsama requested changes

2021-09-27 00:28 UTC, TUsama commented on projects/1.16/assets/accurateblockplacement/accurateblockplacement/lang/zh_cn.json
> +    "net.clayborn.accurateblockplacement.modplacementmodemessage": "已启用精准放置方块模式!",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

标点符号应为中文标点。

2021-09-27 03:23 UTC, Lyaiya commented on projects/1.16/assets/enhancedblockentities/enhancedblockentities/zh_cn.json
> +    "text.ebe.shiftForDesc": "按住 Shift 进行描述",
这里是按住 Shift 就会出现描述吧，所以可以翻译为查看描述。

2021-10-02 06:14 UTC, baka-gourd commented
@TACGqwq

2021-10-02 06:20 UTC, TACGqwq commented
> @TACGqwq

啊，不好意思，在外地出差没法改，我直接取消这条PR后面重新交好了

2021-10-02 06:20 UTC, closed without merging