[WIP,W]鬼灭之刃汉化
CFPAOrg/Minecraft-Mod-Language-Package pull request #1364
Opened 2021-09-29 12:34 UTC by SlimeSB

- [ ] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [ ] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [ ] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [ ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [ ] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [ ] 我已上传英文文件以供审查；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-09-29 12:38 UTC, SlimeSB commented
。。。该mod真是混乱，貌似作者的github只更新到1.12，后面又被谁接手做了，尚不清楚项目存放在哪。百科的资料也一万年没有更新了。不过英日结合，而且又是二次元模组，难度应该不会很大。
（划掉）看见百科那么几个物品还以为词条很少，没想到新版居然921条。找到作者github前只好先用jar里的做了。

2021-09-29 13:09 UTC, SlimeSB commented
再次辱骂一下二次元！！！

2021-10-02 02:48 UTC, SlimeSB commented on projects/1.16/assets/demonslayer/kimetsunoyaiba/lang/zh_cn.json
> +  "item.kimetsunoyaiba.d_ice_steak_head_3": "骰子牛排前辈的头 3",
key简直了……接着辱骂一下二次元

2021-10-02 06:24 UTC, baka-gourd commented on projects/1.16/assets/demonslayer/kimetsunoyaiba/lang/zh_cn.json
> +  "entity.kimetsunoyaiba.demon_6": "Demon Yachan Brother",
https://kimetsunoyaibamod.game-info.wiki/d/%BF%CD%B4%D6
看樣子是路人

2021-10-02 06:43 UTC, SlimeSB commented on projects/1.16/assets/demonslayer/kimetsunoyaiba/lang/zh_cn.json
> +  "entity.kimetsunoyaiba.demon_6": "Demon Yachan Brother",
那就随便叫了

2021-10-03 01:37 UTC, SlimeSB commented
@TUsama 可以审了，没问题我把空行删了在merge

2021-10-03 01:57 UTC, baka-gourd commented
空着的是原文没有还是？
二刺螈浓度不足，如果都是照着wiki或者动画搬的就不用审了（

2021-10-03 02:02 UTC, SlimeSB commented
> 空着的是原文没有还是？ 如果是空着的最好删除。 还有同步一下上游更改 二刺螈浓度不足，如果都是照着wiki或者动画搬的就不用审了（

eh……什么是上游更改，sorry

2021-10-03 02:08 UTC, baka-gourd commented
就是把本仓库的更改拉到你的仓库，github页面上有的

2021-10-03 02:15 UTC, SlimeSB commented
这样就OK？

2021-10-03 02:53 UTC, baka-gourd requested changes

2021-10-03 02:53 UTC, baka-gourd commented on projects/1.16/assets/demonslayer/kimetsunoyaiba/lang/zh_cn.json
> +  "item.kimetsunoyaiba.item_sneak_leggings": "",
这样的空行最好删去，其他二刺螈我也不懂

2021-10-03 03:11 UTC, baka-gourd approved these changes

2021-10-03 04:01 UTC, merged