[WIP]Update zh_cn.json
CFPAOrg/Minecraft-Mod-Language-Package pull request #1367
Opened 2021-10-01 09:49 UTC by Rasilia

修改了一个错误的翻译，新增数个翻译

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [ ] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-10-01 10:11 UTC, dovisutu commented
为什么标的是[WIP]？是还没做完吗？

2021-10-01 10:33 UTC, Rasilia commented
> 
> 
> 为什么标的是[WIP]？是还没做完吗？

因为我群里有人翻译整合包任务的时候发现了物品的翻译错误然后我就来改了下，顺手把部分未汉化内容翻译了一点

2021-10-01 11:07 UTC, dovisutu commented
这个我感觉不算是wip啊...
不管了，直接审

2021-10-02 02:00 UTC, baka-gourd requested changes

2021-10-02 02:00 UTC, baka-gourd commented on projects/1.16/assets/draconic-evolution/draconicevolution/lang/zh_cn.json
> +  "itemGroup.draconicevolution.modules": "龙之研究 模块",
查阅规范并修改

2021-10-02 02:02 UTC, baka-gourd commented
确定是不会进行全部的汉化是吗

2021-10-03 08:56 UTC, baka-gourd commented
已合并

2021-10-03 08:56 UTC, closed without merging