[R] thecech12 作品翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #1370
Opened 2021-10-03 05:57 UTC by Lyaiya

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [x] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-10-03 06:38 UTC, baka-gourd requested changes

2021-10-03 06:38 UTC, baka-gourd commented on projects/1.16/assets/wooden-hopper/woodenhopper/lang/zh_cn.json
> +  "block.woodenhopper.wooden_hopper.desc.cannotAbsorbItemsFromWorld": "不能吸入上方的物品实体。",
这里可以采取意译，物品实体就是掉落的物品

2021-10-03 06:38 UTC, baka-gourd commented on projects/1.16/assets/wooden-hopper/woodenhopper/lang/zh_cn.json
> +  "block.woodenhopper.wooden_hopper.desc.cannotAbsorbItemsFromInventories": "不能吸入上方物品栏中的物品。"
是否缺少主语：容器

2021-10-03 06:38 UTC, baka-gourd commented on projects/1.16/assets/brick-hopper/brickhopper/lang/zh_cn.json
> +  "block.brickhopper.brick_hopper.desc.cannotAbsorbItemsFromInventories": "不能吸入上方物品栏中的物品。"
同下

2021-10-03 09:06 UTC, Lyaiya commented on projects/1.16/assets/wooden-hopper/woodenhopper/lang/zh_cn.json
> +  "block.woodenhopper.wooden_hopper.desc.cannotAbsorbItemsFromWorld": "不能吸入上方的物品实体。",
验证了一下，确实是这样，我还以为这个物品实体是什么特殊的物品形态。

2021-10-03 09:10 UTC, Lyaiya commented on projects/1.16/assets/wooden-hopper/woodenhopper/lang/zh_cn.json
> +  "block.woodenhopper.wooden_hopper.desc.cannotAbsorbItemsFromInventories": "不能吸入上方物品栏中的物品。"
上方前面加个漏斗？

2021-10-03 09:11 UTC, Lyaiya commented on projects/1.16/assets/wooden-hopper/woodenhopper/lang/zh_cn.json
> +  "block.woodenhopper.wooden_hopper.desc.cannotAbsorbItemsFromInventories": "不能吸入上方物品栏中的物品。"
原文本身没主语，但这里也不一定要补主语吧？

2021-10-03 10:06 UTC, baka-gourd approved these changes

2021-10-03 10:08 UTC, baka-gourd commented on projects/1.16/assets/wooden-hopper/woodenhopper/lang/zh_cn.json
> +  "block.woodenhopper.wooden_hopper.desc.cannotAbsorbItemsFromInventories": "不能吸入上方物品栏中的物品。"
确实

2021-10-04 09:22 UTC, dovisutu commented on projects/1.16/assets/ceramic-bucket/ceramicbucket/lang/zh_cn.json
> +  "item.ceramicbucket.ceramic_milk_bucket": "奶陶瓷桶",
`牛奶->奶`的更改是在`1.17`才实施的。如果本模组的适用版本低于`1.17`，请退回至`牛奶`。

2021-10-04 09:27 UTC, Lyaiya commented on projects/1.16/assets/ceramic-bucket/ceramicbucket/lang/zh_cn.json
> +  "item.ceramicbucket.ceramic_milk_bucket": "奶陶瓷桶",
冷知识：1.16 跟 1.17 的简中是同步的（如果不是， 可能是游戏实例的资源没更新，引用的还是旧语言文件）

2021-10-04 09:28 UTC, dovisutu commented on projects/1.16/assets/ceramic-bucket/ceramicbucket/lang/zh_cn.json
> +  "item.ceramicbucket.ceramic_milk_bucket": "奶陶瓷桶",
啊这
那应该没什么了。

2021-10-04 09:28 UTC, merged