[R] 珍奇鸟类：修缮翻译，整理格式
CFPAOrg/Minecraft-Mod-Language-Package pull request #1401
Opened 2021-10-30 03:07 UTC by DLM-BFC-DLM

- [ ] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [ ] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [ ] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [ ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
- [ ] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [ ] 我已上传英文文件以供审查；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-11-01 04:22 UTC, SlimeSB requested changes

2021-11-01 04:22 UTC, SlimeSB commented on projects/1.12.2/assets/exotic-birds/exoticbirds/lang/zh_cn.lang
> +book.exoticbirds.cassowary.info=食火鸡是在澳大利亚东北部和新几内亚发现的一类有领地意识的大型鸟类。它们集小群生活，远离人类，如果被激怒，它们将会变得异常危险。被称作“头盔”的外延骨骼长在头部，用于推开密集的植被。
参考197行“鹤鸵科”，是否需要统一，还是刻意为之

2021-11-01 04:22 UTC, SlimeSB commented on projects/1.12.2/assets/exotic-birds/exoticbirds/lang/zh_cn.lang
> +exoticbirds.subtitles.entity.vulture.ambient=秃鹫尖啸
```suggestion
exoticbirds.subtitles.entity.vulture.ambient=秃鹫：尖啸
```
后面也是如此

2021-11-01 04:22 UTC, SlimeSB commented on projects/1.12.2/assets/exotic-birds/exoticbirds/lang/zh_cn.lang
> +book.exoticbirds.phoenix.info=凤凰是浴火而生的大型神话生物。这些鸟只能从特殊的卵孵化出来，并且有能力飞翔。它们可以被骑乘，死后会掉落神奇的复活灰烬。据说环境可以改变凤凰的形态。
为何一会蛋一会卵

2021-11-01 04:22 UTC, SlimeSB commented on projects/1.12.2/assets/aquaculture/aquaculture/lang/zh_cn.lang
> +aquaculture.message29=五毛钱一个可乐瓶。
这个更改是干嘛的

2021-11-01 04:22 UTC, SlimeSB commented
开新坑的时候记得新建分支。不然记录会很乱

2021-11-03 09:37 UTC, SlimeSB commented
鸡蛋就可以了！禽类下蛋，昆虫产卵。

2021-11-03 09:48 UTC, DLM-BFC-DLM commented
鸟类产卵吧

2021-11-03 09:57 UTC, DLM-BFC-DLM commented
> 鸡蛋就可以了！禽类下蛋，昆虫产卵。
鸟类产卵吧

2021-11-03 09:58 UTC, SlimeSB commented
说鸡卵不是错误。但就本游戏来说，首先有鸡蛋、海龟蛋、龙蛋、刷怪蛋。但是没有卵。并且在其他模组翻译时，作禽类产的蛋/卵时，也一般用卵。

2021-11-03 13:10 UTC, DLM-BFC-DLM commented on projects/1.12.2/assets/exotic-birds/exoticbirds/lang/zh_cn.lang
> +book.exoticbirds.phoenix.info=凤凰是浴火而生的大型神话生物。这些鸟只能从特殊的卵孵化出来，并且有能力飞翔。它们可以被骑乘，死后会掉落神奇的复活灰烬。据说环境可以改变凤凰的形态。
已统一为“蛋”

2021-11-04 07:54 UTC, DLM-BFC-DLM commented on projects/1.12.2/assets/exotic-birds/exoticbirds/lang/zh_cn.lang
> +book.exoticbirds.cassowary.info=食火鸡是在澳大利亚东北部和新几内亚发现的一类有领地意识的大型鸟类。它们集小群生活，远离人类，如果被激怒，它们将会变得异常危险。被称作“头盔”的外延骨骼长在头部，用于推开密集的植被。
已统一

2021-11-04 07:55 UTC, DLM-BFC-DLM commented on projects/1.12.2/assets/exotic-birds/exoticbirds/lang/zh_cn.lang
> +exoticbirds.subtitles.entity.vulture.ambient=秃鹫尖啸
已修改

2021-11-04 07:55 UTC, DLM-BFC-DLM commented on projects/1.12.2/assets/aquaculture/aquaculture/lang/zh_cn.lang
> +aquaculture.message29=五毛钱一个可乐瓶。
无意义

2021-11-05 13:40 UTC, closed without merging