[R]披萨工艺原文和翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1412
Opened 2021-11-01 08:47 UTC by ChillirCR

- [ ] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [ ] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [ ] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [ ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [ ] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [ ] 我已上传英文文件以供审查；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)
- [ ] 标签/状态更新，滞后更新时点击

2021-11-01 13:07 UTC, SlimeSB requested changes

2021-11-01 13:07 UTC, SlimeSB commented on projects/1.16/assets/pizzacraft/lang/zh_cn.json
> +  "information.pizzacraft.hunger": "每片%s%s饱食度(共%s点)",
标点符号，应为全角。
后文也有相同问题。

2021-11-04 10:34 UTC, ChillirCR commented on projects/1.16/assets/pizzacraft/lang/zh_cn.json
> +  "information.pizzacraft.hunger": "每片%s%s饱食度(共%s点)",
已更改

2021-11-04 11:19 UTC, Lyaiya commented on projects/1.16/assets/pizzacraft/lang/zh_cn.json
> +  "information.pizzacraft.hunger": "每片%s%s饱食度（共%s点）",
注意区别 Hunger（饥饿值）和 Saturation（饱和度）。[相关资料](https://minecraft.fandom.com/zh/wiki/%E9%A5%A5%E9%A5%BF)

2021-11-04 11:28 UTC, ChillirCR commented on projects/1.16/assets/pizzacraft/lang/zh_cn.json
> +  "information.pizzacraft.hunger": "每片%s%s饱食度（共%s点）",
解决问题了

2021-11-04 11:29 UTC, Lyaiya commented on projects/1.16/assets/pizzacraft/lang/zh_cn.json
> +  "information.pizzacraft.hunger": "每片%s%s饱食度（共%s点）",
别忘了下面的。

2021-11-04 11:29 UTC, ChillirCR commented on projects/1.16/assets/pizzacraft/lang/zh_cn.json
> +  "information.pizzacraft.hunger": "每片%s%s饱食度（共%s点）",
刚发现

2021-11-04 11:31 UTC, ChillirCR commented on projects/1.16/assets/pizzacraft/lang/zh_cn.json
> +  "information.pizzacraft.hunger": "每片%s%s饱食度（共%s点）",
好了

2021-11-04 11:34 UTC, Lyaiya commented
路径错了，注意看第四条
> 如果是 1.15-1.16 翻译，应该是：projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json

2021-11-04 12:08 UTC, ChillirCR commented
不知道还有没有错误

2021-11-04 12:14 UTC, Lyaiya commented
...你是用网页操作的吗，把网页翻译关了再弄，这路径都包含中文了，还有注意大小写。

这里的“CurseForge 项目名称”指的是 <https://www.curseforge.com/minecraft/mc-mods/pizzacraft> 网址最后的 **pizzacraft**。

ModId 指的是模组本体里 lang 文件夹的上级文件夹，也是 **pizzacraft**。

所以最终路径应该是 `projects/1.16/assets/pizzacraft/pizzacraft/lang/zh_cn.json`。

2021-11-04 14:00 UTC, Lyaiya commented
现在 en_us 的文件名还是错的

2021-11-04 14:03 UTC, Lyaiya commented on projects/1.16/assets/pizzacraft/pizzacraft/zh_cn.json
> +  "pizzacraft.milk": "牛奶",
如果这里的 Milk 与原版的 Milk 是一个东西的话，请改成**奶**，因为现在 1.16 Milk 的译名为**奶**而不是**牛奶**。

2021-11-04 15:19 UTC, ChillirCR commented
审核员辛苦了啊，我太粗枝大叶了

2021-11-05 05:11 UTC, Lyaiya commented on projects/1.16/assets/pizzacraft/pizzacraft/zh_cn.json
> +  "information.pizzacraft.hunger_slice": "饥饿值： %s",
```suggestion
  "information.pizzacraft.hunger_slice": "饥饿值：%s",
```

符号与数字之间不需要空格

2021-11-05 05:13 UTC, Lyaiya commented on projects/1.16/assets/pizzacraft/pizzacraft/zh_cn.json
> +  "description.pizzacraft.hold_shift.title": "按下shift查看详细描述",
注意大小写！

2021-11-05 05:15 UTC, Lyaiya commented
规范问题都能在 [Minecraft 模组简体中文翻译规范与指南](https://rules.cfpa.team/) 得到解答，请认真阅读并进行修改。

2021-11-05 06:57 UTC, Lyaiya commented on projects/1.16/assets/pizzacraft/pizzacraft/zh_cn.json
> +  "description.pizzacraft.hold_shift.title": "按住 shift 查看详细描述",
之前说过了，这个 Shift 原文是**首字母大写**的就不要随意改成小写

2021-11-05 07:29 UTC, Lyaiya commented on projects/1.16/assets/pizzacraft/pizzacraft/zh_cn.json
> +  "description.pizzacraft.backstab.description": "如果从生物背后攻击，可以造成125%的伤害",
```suggestion
  "description.pizzacraft.backstab.description": "如果从生物背后攻击，可以造成 125% 的伤害",
```

2021-11-05 07:42 UTC, Lyaiya commented on projects/1.16/assets/pizzacraft/pizzacraft/zh_cn.json
> +  "advancements.pizzacraft.raw_pizza.description": "把擀面杖放在生面团上做成生比萨饼",
比萨还是披萨？注意用词统一

2021-11-05 07:42 UTC, Lyaiya commented on projects/1.16/assets/pizzacraft/pizzacraft/zh_cn.json
> +  "advancements.pizzacraft.cheese_block.description": "在盆里倒入牛奶再用发酵物发酵成奶酪块",
奶还是牛奶？

2021-11-05 07:42 UTC, Lyaiya commented on projects/1.16/assets/pizzacraft/pizzacraft/zh_cn.json
> +  "advancements.pizzacraft.oven.description": "制作个烤炉",
```suggestion
  "advancements.pizzacraft.oven.description": "制作一个烤炉",
```

个人建议，可改可不改

2021-11-05 07:46 UTC, ChillirCR commented on projects/1.16/assets/pizzacraft/pizzacraft/zh_cn.json
> +  "advancements.pizzacraft.oven.description": "制作个烤炉",
为了和整体协调已修改

2021-11-05 07:49 UTC, Lyaiya commented
> ...你是用网页操作的吗，把网页翻译关了再弄，这路径都包含中文了，还有注意大小写。
> 
> 这里的“CurseForge 项目名称”指的是 https://www.curseforge.com/minecraft/mc-mods/pizzacraft 网址最后的 **pizzacraft**。
> 
> ModId 指的是模组本体里 lang 文件夹的上级文件夹，也是 **pizzacraft**。
> 
> 所以最终路径应该是 `projects/1.16/assets/pizzacraft/pizzacraft/lang/zh_cn.json`。
> 
> 要是有疑惑的话可以先在 Q 群里问问，这里一般用来处理翻译问题。

等一下，路径怎么还是错的………

2021-11-05 07:53 UTC, Lyaiya approved these changes

2021-11-05 08:14 UTC, merged