[M]我的殖民地zh_cn.json更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #1418
Opened 2021-11-04 09:16 UTC by mc-kaishixiaxue

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [x] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 是 1.15-1.16 翻译，应该是：`projects/1.16/assets/minecolonies/minecolonies/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)
- [x] 标签/状态更新，滞后更新时点击

2021-11-04 11:07 UTC, Lyaiya commented on projects/1.16/assets/minecolonies/minecolonies/lang/zh_cn.json
> +  "com.minecolonies.coremod.info.composter.2": "现在让我们来介绍一些常见问题：\n\n问题 1.我可以使用其他MOD中的物品吗？\n 回答 1.可以，这些物品必须添加到游戏配置文件中的Minecolonies配置文件中。./config/minecolonies-common.toml",
MOD 应当翻译成模组

2021-11-05 01:32 UTC, mc-kaishixiaxue commented on projects/1.16/assets/minecolonies/minecolonies/lang/zh_cn.json
> +  "com.minecolonies.coremod.info.composter.2": "现在让我们来介绍一些常见问题：\n\n问题 1.我可以使用其他MOD中的物品吗？\n 回答 1.可以，这些物品必须添加到游戏配置文件中的Minecolonies配置文件中。./config/minecolonies-common.toml",
发现1.16.5版本的翻译有多处缺失，稍后会大规模修改。

2021-11-07 07:05 UTC, Lyaiya commented
这也太重量级了，我没怎么玩过这模组，可能审不来（

2021-11-08 04:08 UTC, TUsama requested changes
整体质量较好。

2021-11-08 04:08 UTC, TUsama commented on projects/1.16/assets/minecolonies/minecolonies/lang/zh_cn.json
> +  "com.minecolonies.coremod.info.miner.1": "让我们了解一些限制：\n\n 1. 矿工们使用的工具的等级由他们的小屋等级决定：\n   等级 0：木质/金质工具\n   等级 1：石头工具\n   等级 2：铁质工具\n   等级 4：钻石工具\n   等级 5：附魔工具",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
  "com.minecolonies.coremod.info.miner.1": "让我们了解一些限制：\n\n 1. 矿工们使用的工具的等级由他们的小屋等级决定：\n   等级 0：木制/金制工具\n   等级 1：石头工具\n   等级 2：铁制工具\n   等级 4：钻石工具\n   等级 5：附魔工具",
```
顺便看看其他地方有没有类似的。

2021-11-08 06:46 UTC, mc-kaishixiaxue commented on projects/1.16/assets/minecolonies/minecolonies/lang/zh_cn.json
> +  "com.minecolonies.coremod.job.bakery": "面包师",
部分物品他也会做。

2021-11-08 06:50 UTC, mc-kaishixiaxue commented on projects/1.16/assets/minecolonies/minecolonies/lang/zh_cn.json
> +  "com.minecolonies.coremod.ai.nohospital": "我得了 %s，需要用%s来治疗！请建造一个医院（或直接给我物品）。",
第一个%s在英文没有对应的翻译键，它始终是英文，硬编码。

2021-11-08 07:40 UTC, mc-kaishixiaxue commented on projects/1.16/assets/minecolonies/minecolonies/lang/zh_cn.json
> +  "com.minecolonies.coremod.gui.citizen.skills.intelligence": "智力",
已经确认英文没有%d

2021-11-08 12:47 UTC, baka-gourd commented
同步上游后合并

2021-11-08 14:36 UTC, merged