[R] 神秘学1.18.0
CFPAOrg/Minecraft-Mod-Language-Package pull request #1420
Opened 2021-11-04 12:46 UTC by kappa-maintainer

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [x] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [x] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [x] 我已上传英文文件以供审查；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)
- [] 标签/状态更新，滞后更新时点击

2021-11-05 12:59 UTC, SlimeSB requested changes

2021-11-05 12:59 UTC, SlimeSB commented on projects/1.16/assets/occultism/occultism/patchouli_books/dictionary_of_spirits/zh_cn/entries/getting_started/first_ritual.json
> +      "text": "第一步，在熔炉中烧炼异界石，并且在$(thing)灵火$()中灼烧异界原木。将产出物合成为含杂白色粉笔，再将其投入$(thing)灵火$()中再次进行净化。净化后的粉笔可用于画出组成五芒星的仪式符文。可选的五芒星可以在对应章节中找到。"
```suggestion
      "text": "第一步，在熔炉中烧炼异界石，并且在$(thing)灵火$()中灼烧异界原木。将产生的灰烬合成为含杂白色粉笔，接着将其再次投入$(thing)灵火$()中净化。净化后的粉笔可用于画出组成五芒星的仪式符文。可选的五芒星可以在对应章节中找到。"
```
这个木头是作燃料吗？如果是的话建议“灼烧”→“燃烧”或者“用异界原木作为灵火的燃料”

2021-11-05 12:59 UTC, SlimeSB commented on projects/1.16/assets/occultism/occultism/patchouli_books/dictionary_of_spirits/zh_cn/entries/rituals/familiars/familiar_chimera.json
> +      "text": "向奇美拉喂食（任何）肉类都会让它长大，同时增加它的伤害和速度。一定奇美拉长得足够大，你就可以骑乘它。向其喂食金苹果可以使奇美拉中的山羊分离出来，成为一个独立的使魔。"
```suggestion
      "text": "向奇美拉喂食（任何）肉类都会让它长大，同时增加它的伤害和速度。当奇美拉长得足够大的时候，你就可以骑乘它。向其喂食金苹果可以使奇美拉中的山羊分离出来，成为一个独立的使魔。"
```

2021-11-05 12:59 UTC, SlimeSB commented on projects/1.16/assets/occultism/occultism/patchouli_books/dictionary_of_spirits/zh_cn/entries/rituals/possession/possess_ghast.json
> +      "text": "本仪式利用$(thing)绵羊$()的生命能量生成了一只$(thing)恶魂$()，之后该恶魂立即被召唤出的$(thing)巨灵$()附身。$(thing)被附身的恶魂$()被杀死时总会掉落至少一个$(item)恶魂之泪$()。"
mark

2021-11-05 12:59 UTC, SlimeSB commented on projects/1.16/assets/occultism/occultism/lang/zh_cn.json
> +  "item.occultism.ritual_dummy.possess_ghast.tooltip": "杀死被附身的恶魂总会至少掉落一个恶魂之泪。",
$(thing)被附身的恶魂$()被杀死时总会掉落至少一个$(item)恶魂之泪$()。
参考一下这里。我觉得会更好

2021-11-05 13:01 UTC, SlimeSB commented on projects/1.16/assets/occultism/occultism/patchouli_books/dictionary_of_spirits/zh_cn/entries/rituals/familiars/familiar_chimera.json
> +      "text": "向奇美拉喂食（任何）肉类都会让它长大，同时增加它的伤害和速度。一定奇美拉长得足够大，你就可以骑乘它。向其喂食金苹果可以使奇美拉中的山羊分离出来，成为一个独立的使魔。"
错别字，但是我觉得这样比一旦好。

2021-11-05 13:15 UTC, kappa-maintainer commented on projects/1.16/assets/occultism/occultism/patchouli_books/dictionary_of_spirits/zh_cn/entries/getting_started/first_ritual.json
> +      "text": "第一步，在熔炉中烧炼异界石，并且在$(thing)灵火$()中灼烧异界原木。将产出物合成为含杂白色粉笔，再将其投入$(thing)灵火$()中再次进行净化。净化后的粉笔可用于画出组成五芒星的仪式符文。可选的五芒星可以在对应章节中找到。"
并不是燃料

2021-11-05 13:16 UTC, kappa-maintainer commented on projects/1.16/assets/occultism/occultism/lang/zh_cn.json
> +  "item.occultism.ritual_dummy.possess_ghast.tooltip": "杀死被附身的恶魂总会至少掉落一个恶魂之泪。",
帕秋莉里是有字体颜色我才敢这么译，不过各有各的问题就是了，改一下无妨

2021-11-05 13:39 UTC, SlimeSB requested changes

2021-11-05 13:39 UTC, SlimeSB commented on projects/1.16/assets/occultism/occultism/lang/zh_cn.json
> +  "item.occultism.ritual_dummy.possess_enderman.tooltip": "被附身的末影人被杀死总会至少掉落一个末影珍珠。",
```suggestion
  "item.occultism.ritual_dummy.possess_enderman.tooltip": "被附身的末影人在被杀死时总会至少掉落一个末影珍珠。",
```

2021-11-05 13:45 UTC, SlimeSB approved these changes

2021-11-08 02:39 UTC, kappa-maintainer commented
上游甚至又出新版了，既然approved了能不能先merge了

2021-11-08 06:23 UTC, merged