[R]VanillaCookbook中文与原文更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #1428
Opened 2021-11-07 10:14 UTC by ChillirCR

- [ ] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)；
- [ ] 我已确定中文文件中没有未翻译的文本，如有已删除；
- [ ] 我已对 PR 作出标记以便审查（见 [CONTRIBUTING.md](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）；
- [ ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/CurseForge 项目名称/ModID/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是：`projects/1.16/assets/CurseForge 项目名称/ModID/lang/zh_cn.json`
- [ ] 我已确认语言文件名大小写正确，所有的语言文件名称全为小写；
- [ ] 我已上传英文文件以供审查；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议（CC BY-NC-SA 4.0 协议）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)
- [ ] 标签/状态更新，滞后更新时点击

2021-11-07 14:07 UTC, SlimeSB requested changes

2021-11-07 14:07 UTC, SlimeSB commented on projects/1.16/assets/vanilla-cookbook/vanillacookbook/lang/zh_cn.json
> +	"advancements.more_balanced_diet.title": "一个更均衡的饮食",
显然 neta 原版进度名称 A Balanced Diet → 均衡饮食。没有“一个”
```suggestion
	"advancements.more_balanced_diet.title": "更均衡的饮食",
```
后面的描述建议和原版搭点边。

2021-11-07 14:17 UTC, SlimeSB requested changes

2021-11-07 14:17 UTC, SlimeSB commented on projects/1.16/assets/vanilla-cookbook/vanillacookbook/lang/zh_cn.json
> +	"block.vanillacookbook.book_cake": "蛋糕书",
```suggestion
	"block.vanillacookbook.book_cake": "书蛋糕",
```

2021-11-07 14:17 UTC, SlimeSB commented on projects/1.16/assets/vanilla-cookbook/vanillacookbook/lang/zh_cn.json
> +	"block.vanillacookbook.book_cake": "蛋糕书",
应该是蛋糕，进游戏看一下。

2021-11-07 14:20 UTC, SlimeSB commented
后面都带点双关，没有什么更好的译法就留着吧。

2021-11-07 14:29 UTC, SlimeSB requested changes

2021-11-07 14:29 UTC, SlimeSB commented on projects/1.16/assets/vanilla-cookbook/vanillacookbook/lang/zh_cn.json
> +	"advancements.more_balanced_diet.description": "再一次……吃可以吃的东西！",
```suggestion
	"advancements.more_balanced_diet.description": "尝遍天下食材…又一次！",
```

2021-11-07 14:49 UTC, SlimeSB requested changes

2021-11-07 14:49 UTC, SlimeSB commented on projects/1.16/assets/vanilla-cookbook/vanillacookbook/lang/zh_cn.json
> +	"advancements.cake.description": "合成一本书蛋糕,感謝你使用 Vanilla Cookbook！",
```suggestion
	"advancements.cake.description": "合成一个书蛋糕，感謝你使用 Vanilla Cookbook！",
```
注意一下标点，之前看漏了。然后量词的话wiki中用的是个。有特指的话和我解释一下，对一下电波。

2021-11-08 03:59 UTC, SlimeSB approved these changes

2021-11-08 06:08 UTC, Lyaiya commented
Berry 是浆果还是甜浆果，是否需要统一？

2021-11-17 04:54 UTC, Lyaiya commented on projects/1.16/assets/vanilla-cookbook/vanillacookbook/lang/zh_cn.json
> +	"advancements.more_balanced_diet.description": "尝遍天下食材…又一次！",
```suggestion
	"advancements.more_balanced_diet.description": "尝遍天下食材……又一次！",
```

注意中文语境下的省略号

2021-11-17 07:46 UTC, merged