[R]精妙背包翻译跟进
CFPAOrg/Minecraft-Mod-Language-Package pull request #1435
Opened 2021-11-12 06:27 UTC by PigeonNian

- [ ] 我已**仔细阅读**注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认提交文件的路径和名称均**正确**：
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [ ] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 标签/状态更新，滞后更新时点击；

2021-11-13 08:33 UTC, Lyaiya commented
这个路径其实是错的，麻烦切换到 `projects/1.16/assets/sophisticated-backpacks/sophisticatedbackpacks/lang` 进行翻译（见 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)），并把当前的文件夹删除。

2021-11-21 00:25 UTC, TUsama requested changes

2021-11-21 00:25 UTC, TUsama commented on projects/1.16/assets/sophisticatedbackpacks/sophisticatedbackpacks/lang/zh_cn.json
> +  "gui.sophisticatedbackpacks.upgrades.buttons.hunger_level_any": "当玩家稍微饥饿时立即喂食\n浪费食物提供的大量饱食度",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

根据标准译名，hunger points 应翻译为“饥饿值”。

2021-11-21 05:14 UTC, Lyaiya commented on projects/1.16/assets/sophisticatedbackpacks/sophisticatedbackpacks/lang/zh_cn.json
> +  "gui.sophisticatedbackpacks.upgrades.buttons.hunger_level_any": "当玩家稍微饥饿时立即喂食\n浪费食物提供的大量饱食度",
这地方我改过来着。

2021-11-24 04:05 UTC, closed without merging