[R] Twist模组 1.4.1 英文原文及中文翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #1439
Opened 2021-11-15 15:02 UTC by redswordman

- [x] 我已**仔细阅读**注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认提交文件的路径和名称均**正确**：
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [x] 标签/状态更新，滞后更新时点击；

2021-11-19 07:52 UTC, Lyaiya commented
翻译文件的拓展名错了，多了个空格。

2021-11-22 08:11 UTC, WuzgXY-GitHub requested changes

2021-11-22 08:11 UTC, WuzgXY-GitHub commented on projects/1.16/assets/twist/twist/lang/zh_cn.json
> +  "advancements.ripntear.title": "我！ 射！ 爆！",
必须修改。

2021-11-22 08:11 UTC, WuzgXY-GitHub commented on projects/1.16/assets/twist/twist/lang/zh_cn.json
> +  "advancements.excuseme.descr": "使用猪灵胃软着陆.",
```suggestion
  "advancements.excuseme.descr": "使用猪灵胃软着陆。",
```

2021-11-22 08:11 UTC, WuzgXY-GitHub commented on projects/1.16/assets/twist/twist/lang/zh_cn.json
> +  "entity.twist.groundedslug": "下界蛞蝓",
你确定要加“下界”二字么？

2021-11-22 12:20 UTC, redswordman commented on projects/1.16/assets/twist/twist/lang/zh_cn.json
> +  "advancements.ripntear.title": "我！ 射！ 爆！",
这个是neta毁灭战士（doom）的主题曲rip and tear。Rip and tear 在英语里是指横冲直撞的意思。这里作者把tear (apart) 换成slug，表达胡乱扫射的意思。所以我觉得除了这个翻译容易让一些小鬼误会之外，还是很合理的。
当然假如大佬看完我的解释之后觉得实在不合适，我会将翻译换成“毁灭战士”。

2021-11-22 12:22 UTC, redswordman commented on projects/1.16/assets/twist/twist/lang/zh_cn.json
> +  "entity.twist.groundedslug": "下界蛞蝓",
其实也没那么必要。
我是这样想的。这个怪物生成于下界，为了和其他mod里的蛞蝓区分开来，故加了下界两字。

2021-11-22 12:32 UTC, redswordman commented on projects/1.16/assets/twist/twist/lang/zh_cn.json
> +  "advancements.ripntear.title": "我！ 射！ 爆！",
我想了想，可能会有小孩子玩这个mod，还是把翻译改了。

2021-11-22 13:48 UTC, WuzgXY-GitHub reviewed
可以了，但其他部分我还没看，所以暂时先不给 approve，倒是问题应该不会太大了

2021-11-23 00:25 UTC, TUsama commented on projects/1.16/assets/twist/twist/lang/zh_cn.json
> +  "entity.twist.groundedslug": "下界蛞蝓",
万一作者只是生成写得有问题呢？万一作者实际上是故意不加 nether 呢？

2021-11-23 10:46 UTC, redswordman commented on projects/1.16/assets/twist/twist/lang/zh_cn.json
> +  "entity.twist.groundedslug": "下界蛞蝓",
生成没有问题，不过想了想确实没必要。

2021-11-23 10:51 UTC, redswordman commented on projects/1.16/assets/twist/twist/lang/zh_cn.json
> +  "entity.twist.groundedslug": "下界蛞蝓",
生成没有问题，不过问了下作者，确实没必要。

2021-11-23 13:42 UTC, merged