[R] solar-flux-reborn 日光通量：重制版 16.3.9 翻译添加
CFPAOrg/Minecraft-Mod-Language-Package pull request #1444
Opened 2021-11-16 06:57 UTC by ArgonCrystal

lang文件夹名称变更为langs，文本文件格式更换为hl，已测试可以通过资源包形式加载文本

- [x] 我已**仔细阅读**注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认提交文件的路径和名称均**正确**：
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [x] 标签/状态更新，滞后更新时点击；

2021-11-16 08:44 UTC, Lyaiya commented
@baka-gourd 这个路径和文件格式能被 Packer 打包进去吗？

2021-11-16 09:07 UTC, Lyaiya commented
注意使用中文标点符号

2021-11-16 09:24 UTC, baka-gourd commented
> @baka-gourd 这个路径和文件格式能被 Packer 打包进去吗？

理论上可以

2021-11-17 01:02 UTC, TUsama requested changes

2021-11-17 01:02 UTC, TUsama commented on projects/1.16/assets/solar-flux-reborn/solarflux/langs/zh_cn.hl
> +info.solarflux.upgrade.efficiency=提升FE 产能量 %.2f%%.
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
info.solarflux.upgrade.efficiency=提升 FE 产能量 %.2f%%。
```
注意标点，以及不要一边有空格一边没空格。

2021-11-17 01:41 UTC, ArgonCrystal commented
已修正

2021-11-17 04:50 UTC, Lyaiya commented on projects/1.16/assets/solar-flux-reborn/solarflux/langs/zh_cn.hl
> +info.solarflux.energy.stored1=储能: %,d FE
```suggestion
info.solarflux.energy.stored1=储能：%,d FE
```

中文标点符号呢，建议重新查一遍

2021-11-17 13:32 UTC, Lyaiya commented on projects/1.16/assets/solar-flux-reborn/solarflux/langs/zh_cn.hl
> +info.solarflux.sun.intensity=光照比率：%,d%%
这里的 Light Level 确定不是指**光照强度**？[相关资料](https://minecraft.fandom.com/zh/wiki/%E4%BA%AE%E5%BA%A6)

2021-11-17 13:32 UTC, Lyaiya commented on projects/1.16/assets/solar-flux-reborn/solarflux/langs/zh_cn.hl
> +info.solarflux.upgrade.traversal=分配能源以 %d 额外的连接机器。
这句话是不是有点不明所以？大概意思应该是将能量分配给另外 %d 台已连接的机器。

2021-11-17 13:32 UTC, Lyaiya commented on projects/1.16/assets/solar-flux-reborn/solarflux/langs/zh_cn.hl
> +item.solarflux.transfer_rate_upgrade=传输比率升级
Transfer Rate 上面是传输功率，这里又变成传输比率，注意统一问题，翻译完先自审一次，尽量减少低级错误。

2021-11-18 01:57 UTC, closed without merging