[R]新增模组scape-and-run-parasites-addon-by-nocube及翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #1455
Opened 2021-11-18 11:58 UTC by MaxwellYe0815

- [ ] 我已**仔细阅读**注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认提交文件的路径和名称均**正确**：
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [ ] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 标签/状态更新，滞后更新时点击；

2021-11-20 16:01 UTC, ChromaPIE requested changes
整体质量不佳，主要问题：
- 多处漏译
- 对原版术语执行较差
- 出现原文没有的表达

2021-11-20 16:57 UTC, MaxwellYe0815 commented on projects/1.12.2/assets/scape-and-run-parasites-addon-by-nocube/nocubessrpaddon/lang/zh_cn.lang
> +item.adaptivearmorbody.name=高等胸甲
此模组为SR:Parasites模组的附属模组,在SR:Parasites模组中,敌对生物种类Adapted被译为高等种,adaptive护甲由Adapted掉落物合成
为了维持译名统一所以译为高等

2021-11-20 17:45 UTC, MaxwellYe0815 commented on projects/1.12.2/assets/scape-and-run-parasites-addon-by-nocube/nocubessrpaddon/lang/zh_cn.lang
> +item.purpleblade.name=紫灵刃
玩家持有此武器时会被给予速度1效果
已多处类似翻译进行了修改

2021-11-20 17:53 UTC, MaxwellYe0815 commented on projects/1.12.2/assets/scape-and-run-parasites-addon-by-nocube/nocubessrpaddon/lang/zh_cn.lang
> +item.purpleblade.name=紫灵刃
> 原文没有“灵”的对应表达。

玩家持有此武器时会被给予速度1效果
已多处类似翻译进行了修改
所有由游戏内效果扩展的翻译均被移除

2021-11-20 17:54 UTC, MaxwellYe0815 commented on projects/1.12.2/assets/scape-and-run-parasites-addon-by-nocube/nocubessrpaddon/lang/zh_cn.lang
> +item.adaptivearmorbody.name=高等胸甲
> adaptive为什么译成“高等”

此模组为SR:Parasites模组的附属模组,在SR:Parasites模组中,敌对生物种类Adapted被译为高等种,adaptive护甲由Adapted掉落物合成
为了维持译名统一所以译为高等

2021-11-21 04:17 UTC, ChromaPIE commented on projects/1.12.2/assets/scape-and-run-parasites-addon-by-nocube/nocubessrpaddon/lang/zh_cn.lang
> +item.adaptivearmorbody.name=高等胸甲
请对SR:Parasites中Adapted的译文进行修改

2021-11-21 06:17 UTC, TUsama commented on projects/1.12.2/assets/scape-and-run-parasites-addon-by-nocube/nocubessrpaddon/lang/zh_cn.lang
> +item.adaptivearmorbody.name=高等胸甲
Adapted 系列的寄生兽我一直都不知道翻译成什么好。触发的机制为寄生兽击杀了特定数量的其他生物之后，由原始种变为 Adapted 种。译为“适应”有点让人摸不着头脑，但是译为“高等”“成熟”似乎又不是 Adapted 的本义。很纠结。

2021-11-21 10:46 UTC, MaxwellYe0815 commented on projects/1.12.2/assets/scape-and-run-parasites-addon-by-nocube/nocubessrpaddon/lang/zh_cn.lang
> +item.adaptivearmorbody.name=高等胸甲
> Adapted 系列的寄生兽我一直都不知道翻译成什么好。触发的机制为寄生兽击杀了特定数量的其他生物之后，由原始种变为 Adapted 种。译为“适应”有点让人摸不着头脑，但是译为“高等”“成熟”似乎又不是 Adapted 的本义。很纠结。

个人觉得作者的意思是，寄生虫是这个世界的外来者，适应了这个世界，就变得更强了。
但是依旧不知道怎么翻，"适应XX兽"和"适应遗骸"都变扭极了...

2021-11-21 13:44 UTC, TUsama commented on projects/1.12.2/assets/scape-and-run-parasites-addon-by-nocube/nocubessrpaddon/lang/zh_cn.lang
> +item.adaptivearmorbody.name=高等胸甲
你这边直译，适应性即可。本体那边我再想想。

2021-11-22 03:20 UTC, TUsama commented
本体那边我改成了适应xx兽，很古怪，但是作者用这个词确实就是这个意思。你要有兴趣你就问一下作者为什么不用evolved或者是mature吧。

2021-11-22 03:21 UTC, TUsama commented
还有你看一下我改的一些细节，注意跟进一下mcmod的资料。

2021-11-22 11:25 UTC, merged