[R] More Mekanism Processing 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1457
Opened 2021-11-20 21:20 UTC by CialloAlone

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2021-11-21 05:11 UTC, Lyaiya commented
路径错误，请认真查看提交文件路径的例子。

2021-11-22 08:22 UTC, WuzgXY-GitHub requested changes

2021-11-22 08:22 UTC, WuzgXY-GitHub commented on projects/1.16/assets/more-mekanism-processing/moremekanismprocessing/lang/zh_cn.json
> +  "statedMaterial.moremekanismprocessing._comment9": "    例如：) 'slurry.moremekanismprocessing.clean_cobalt' : '纯净蓝色金属浆液'",
```suggestion
  "statedMaterial.moremekanismprocessing._comment1": "===== 规则 =====",
  "statedMaterial.moremekanismprocessing._comment2": "",
  "statedMaterial.moremekanismprocessing._comment3": "%s 表示来自 materialType.xxxxx 的",
  "statedMaterial.moremekanismprocessing._comment4": "    材料类型（例如钴、银）",
  "statedMaterial.moremekanismprocessing._comment5": "",
  "statedMaterial.moremekanismprocessing._comment6": "可以通过声明该物品的翻译来覆盖此规则",
  "statedMaterial.moremekanismprocessing._comment7": "    例如：\"item.moremekanismprocessing.cobalt_ingot\": \"蓝色金属\"",
  "statedMaterial.moremekanismprocessing._comment8": "浆液亦然",
  "statedMaterial.moremekanismprocessing._comment9": "    例如：\"slurry.moremekanismprocessing.clean_cobalt\": \"纯净蓝色金属浆液\"",
```

2021-11-22 08:22 UTC, WuzgXY-GitHub commented on projects/1.16/assets/more-mekanism-processing/moremekanismprocessing/lang/zh_cn.json
> +  "statedMaterial.moremekanismprocessing.ore": "%s矿",
```suggestion
  "statedMaterial.moremekanismprocessing.ore": "%s矿石",
```

2021-11-23 13:43 UTC, merged