[R] feat(1.16/locks): 初次翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #1470
Opened 2021-12-01 01:56 UTC by SettingDust

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2021-12-01 04:34 UTC, ChromaPIE commented on projects/1.16/assets/locks/locks/lang/zh_cn.json
> +	"item.locks.wood_lock_mechanism": "木质锁芯",
```suggestion
	"item.locks.wood_lock_mechanism": "木锁芯",
```

2021-12-01 04:44 UTC, ChromaPIE requested changes

2021-12-01 04:44 UTC, ChromaPIE commented on projects/1.16/assets/locks/locks/lang/zh_cn.json
> +	"item.locks.wood_lock_mechanism": "木质锁芯",
```suggestion
	"item.locks.wood_lock_mechanism": "木锁芯",
```

2021-12-01 04:44 UTC, ChromaPIE commented on projects/1.16/assets/locks/locks/lang/zh_cn.json
> +	"item.locks.iron_lock_mechanism": "铁质锁芯",
```suggestion
	"item.locks.iron_lock_mechanism": "铁锁芯",
```

2021-12-01 04:44 UTC, ChromaPIE commented on projects/1.16/assets/locks/locks/lang/zh_cn.json
> +	"item.locks.steel_lock_mechanism": "钢质锁芯",
```suggestion
	"item.locks.steel_lock_mechanism": "钢锁芯",
```

2021-12-01 04:44 UTC, ChromaPIE commented on projects/1.16/assets/locks/locks/lang/zh_cn.json
> +	"item.locks.iron_lock_pick": "铁质撬锁器",
```suggestion
	"item.locks.iron_lock_pick": "铁撬锁器",
```

2021-12-01 04:44 UTC, ChromaPIE commented on projects/1.16/assets/locks/locks/lang/zh_cn.json
> +	"item.locks.steel_lock_pick": "钢质撬锁器",
```suggestion
	"item.locks.steel_lock_pick": "钢撬锁器",
```

2021-12-01 04:44 UTC, ChromaPIE commented on projects/1.16/assets/locks/locks/lang/zh_cn.json
> +	"item.locks.gold_lock_pick": "金质撬锁器",
```suggestion
	"item.locks.gold_lock_pick": "金撬锁器",
```

2021-12-01 04:44 UTC, ChromaPIE commented on projects/1.16/assets/locks/locks/lang/zh_cn.json
> +	"item.locks.master_key": "大师之钥",
```suggestion
	"item.locks.master_key": "大师钥匙",
```

2021-12-01 04:44 UTC, ChromaPIE commented on projects/1.16/assets/locks/locks/lang/zh_cn.json
> +	"locks.subtitle.key_ring": "钥匙：叮当响",
```suggestion
	"locks.subtitle.key_ring": "钥匙：叮当",
```

2021-12-01 04:44 UTC, ChromaPIE commented on projects/1.16/assets/locks/locks/lang/zh_cn.json
> +	"death.attack.locks.shock": "%1$s在撬开附有魔咒的锁失败后被电死",
```suggestion
	"death.attack.locks.shock": "%1$s在尝试撬开附有魔咒的锁失败后被电死了",
```

2021-12-01 04:44 UTC, ChromaPIE commented on projects/1.16/assets/locks/locks/lang/zh_cn.json
> +	"death.attack.locks.shock.player": "%1$s在与%2$s战斗的同时撬开附有魔咒的锁失败后被电死",
```suggestion
	"death.attack.locks.shock.player": "%1$s在一边攻击%2$s一边撬开附有魔咒的锁时被这把锁电死了",
```

2021-12-01 11:30 UTC, SettingDust commented on projects/1.16/assets/locks/locks/lang/zh_cn.json
> +	"death.attack.locks.shock.player": "%1$s在与%2$s战斗的同时撬开附有魔咒的锁失败后被电死",
`%1$s在一边攻击%2$s一边撬开附有魔咒的锁时被锁电死了`

2021-12-01 11:40 UTC, SettingDust commented on projects/1.16/assets/locks/locks/lang/zh_cn.json
> +	"death.attack.locks.shock.player": "%1$s在与%2$s战斗的同时撬开附有魔咒的锁失败后被电死",
```suggestion
	"death.attack.locks.shock.player": "%1$s在攻击%2$s的同时尝试撬开附有魔咒的锁失败后被锁电死了",
```

2021-12-02 02:20 UTC, ChromaPIE approved these changes

2021-12-02 02:20 UTC, merged