[R] fluid system 翻译添加
CFPAOrg/Minecraft-Mod-Language-Package pull request #1472
Opened 2021-12-01 06:29 UTC by ArgonCrystal

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [ ] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2021-12-02 08:12 UTC, TUsama requested changes

2021-12-02 08:12 UTC, TUsama commented on projects/1.16/assets/fluid-system/fluidsystem/lang/zh_cn.json
> +    "tooltip.fluidsystem.outputPipe": "允许从管道中输出流体",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

表述很奇怪。一般来说，允许的后面得加上人称代词，比如允许xx做xx，。但是在中文语境里，允许一根管道输出液体，从语义角度出发就已经很奇怪了。管道不需要别人允许，它自己就能工作，允许管道这一表述完全说不通。

看了看原文，你的翻译不仅表述有问题，而且和原文也有较大出入。建议做如下修改：
```suggestion
    "tooltip.fluidsystem.outputPipe": "该方块能够让你使用管道排出流体",
```
表述还是很奇怪，但是原文就很奇怪，所以一起奇怪吧。
顺便上面那句也得改。

2021-12-02 08:12 UTC, TUsama commented on projects/1.16/assets/fluid-system/fluidsystem/lang/zh_cn.json
> +    "tooltip.fluidsystem.inputPipe": "你可以从管道中输入流体，同时发出红石信号",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

这里是指放出红石信号，还是需要红石信号才能工作？

2021-12-02 08:12 UTC, TUsama commented on projects/1.16/assets/fluid-system/fluidsystem/lang/zh_cn.json
> +    "tooltip.fluidsystem.pipeController": "受到红石信号时会断开管道",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
    "tooltip.fluidsystem.pipeController": "接收到红石信号时会断开管道",
```

2021-12-02 08:12 UTC, TUsama commented on projects/1.16/assets/fluid-system/fluidsystem/lang/zh_cn.json
> +    "tooltip.fluidsystem.tankBlockInput": "允许流体通过管道的输入储罐",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
    "tooltip.fluidsystem.tankBlockInput": "该方块可以接收使用本模组管道运输而来的流体",
```

2021-12-02 08:12 UTC, TUsama commented on projects/1.16/assets/fluid-system/fluidsystem/lang/zh_cn.json
> +    "tooltip.fluidsystem.tankBlockInterface": "使你可以输出和输入流体到储罐"
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
    "tooltip.fluidsystem.tankBlockInterface": "你可以通过此方块对储罐进行输入输出操作"
```
原文直译太怪了。

2021-12-08 09:59 UTC, TUsama commented on projects/1.16/assets/fluid-system/fluidsystem/lang/zh_cn.json
> +    "tooltip.fluidsystem.inputPipe": "你可以从管道中输入流体，同时发出红石信号",
你进游戏测试了吗？

2021-12-08 12:31 UTC, ArgonCrystal commented on projects/1.16/assets/fluid-system/fluidsystem/lang/zh_cn.json
> +    "tooltip.fluidsystem.inputPipe": "你可以从管道中输入流体，同时发出红石信号",
> 你进游戏测试了吗？

我已经改过了，不知道怎么的没有同步成功，等下我再同步试试。

2021-12-08 12:33 UTC, TUsama commented on projects/1.16/assets/fluid-system/fluidsystem/lang/zh_cn.json
> +    "tooltip.fluidsystem.inputPipe": "你可以从管道中输入流体，同时发出红石信号",
不是，我是问它到底是不是通入红石信号qidong ，不是问文本。

2021-12-08 14:10 UTC, ArgonCrystal commented on projects/1.16/assets/fluid-system/fluidsystem/lang/zh_cn.json
> +    "tooltip.fluidsystem.inputPipe": "你可以从管道中输入流体，同时发出红石信号",
> 不是，我是问它到底是不是通入红石信号qidong ，不是问文本。

新文本就是根据游戏实际改的，游戏里该方块是可以接收红石信号，来断开或启用

2021-12-08 14:12 UTC, ArgonCrystal commented on projects/1.16/assets/fluid-system/fluidsystem/lang/zh_cn.json
> +    "tooltip.fluidsystem.inputPipe": "你可以从管道中输入流体，同时发出红石信号",
> 不是，我是问它到底是不是通入红石信号qidong ，不是问文本。

新文本就是根据游戏实际改的，游戏里该方块是可以接收红石信号，来断开或启用

2022-01-06 03:34 UTC, merged