[R] Projecte 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #1494
Opened 2022-01-03 11:23 UTC by ArgonCrystal

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [ ] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-01-09 08:11 UTC, TUsama requested changes

2022-01-09 08:11 UTC, TUsama commented on projects/1.16/assets/projecte/projecte/lang/zh_cn.json
> +	"advancements.projecte.description": "商务记者？",
此处不妥，它想说的是你不断把其他物质里的EMC抽出，转化为别的物质，就像是在两边来回跑一样。翻译为商务记者让人摸不着头脑。

2022-01-09 08:11 UTC, TUsama commented on projects/1.16/assets/projecte/projecte/lang/zh_cn.json
> +	"block.projecte.collector_mk1": "能量收集器MK1",
我印象没错的话，MK这样的表述好像在之前被肃清过一次，建议是直接译成“一级能量收集器”。

2022-01-09 08:11 UTC, TUsama commented on projects/1.16/assets/projecte/projecte/lang/zh_cn.json
> +	"block.projecte.nova_catalyst": "爆破新星",
这俩新星用来干啥的。

2022-01-09 09:30 UTC, ArgonCrystal commented on projects/1.16/assets/projecte/projecte/lang/zh_cn.json
> +	"block.projecte.collector_mk1": "能量收集器MK1",
实际上没有，因为我是直接扒的库里的1.12.2的库转换成json的然后再修改

2022-01-09 09:30 UTC, ArgonCrystal commented on projects/1.16/assets/projecte/projecte/lang/zh_cn.json
> +	"block.projecte.nova_catalyst": "爆破新星",
是更大的tnt，也是1.12.2的翻译

2022-01-09 09:31 UTC, ArgonCrystal commented on projects/1.16/assets/projecte/projecte/lang/zh_cn.json
> +	"advancements.projecte.description": "商务记者？",
都是1.12.2的遗留产物

2022-01-11 08:16 UTC, ChromaPIE commented
对于每个支持版本的新建案，提交者为直接责任人。再以“1.12.2遗留”等为由对审核人员提出的修改要求进行推托，相关PR会被直接关闭。

2022-01-13 02:20 UTC, merged