[R] Trinkets-and-Baubles 新增英文 新增中文汉化的修补文件（Rlcraft 2.9测试正常）
CFPAOrg/Minecraft-Mod-Language-Package pull request #1500
Opened 2022-01-12 09:17 UTC by StarryVoid

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [ ] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-01-12 09:26 UTC, StarryVoid commented
该组件中文汉化人员 502y 已悉知情况，如相关组件汉化修复，可撤销PR。
检查版本 Rlcraft v2.9 1.12.2 2020/01/12

2022-01-12 11:24 UTC, StarryVoid commented
疏忽了，- 和 _ 符号用错了，重新修改名字并pr

2022-01-12 11:41 UTC, Lyaiya commented on projects/1.12.2/assets/Trinkets-and-Baubles/xat/zh_cn.lang
> +splash_potion.effect.xat.sparkling=火花喷溅药水
```suggestion
splash_potion.effect.xat.sparkling=喷溅型火花药水
```
原版译法为xx型xx药水，下同。

2022-01-12 11:41 UTC, Lyaiya commented on projects/1.12.2/assets/Trinkets-and-Baubles/xat/zh_cn.lang
> +item.goblin_ring.0.tooltip5=#green:苦力怕会无视你
```suggestion
item.goblin_ring.0.tooltip5=#green:爬行者会无视你
```
1.12 Creeper 译名为爬行者。

2022-01-12 11:44 UTC, Lyaiya commented on projects/1.12.2/assets/Trinkets-and-Baubles/xat/zh_cn.lang
> +item.arcing_orb.0.tooltip1=#darkgreen:获得闪避能力(双击方向键) #darkaqua:$dodgecost:MP
括号换成全角，下同。另外有许多空格，是不是有必要清理一下。

2022-01-12 15:35 UTC, baka-gourd commented on projects/1.12.2/assets/Trinkets-and-Baubles/xat/zh_cn.lang
> +
```suggestion
#test dont reslove
```

2022-01-13 01:37 UTC, StarryVoid commented
改好了

2022-01-13 02:58 UTC, TUsama requested changes

2022-01-13 02:58 UTC, TUsama commented on projects/1.12.2/assets/Trinkets-and-Baubles/xat/zh_cn.lang
> +item.elf_ring.0.tooltip3=#gold:在森林生态中获得移动和攻击速度加成
此处应是省略“biome”一词，此词应翻译为“生物群系”，而非“生态”。

2022-01-13 02:58 UTC, TUsama commented on projects/1.12.2/assets/Trinkets-and-Baubles/xat/zh_cn.lang
> +item.mana_reagent.name=#gold:法力药水
到底是“魔力”还是“法力”？自身术语需统一。

2022-01-13 02:58 UTC, TUsama commented on projects/1.12.2/assets/Trinkets-and-Baubles/xat/zh_cn.lang
> +xat.config.attributes.stepheight=上坡高度
```suggestion
xat.config.attributes.stepheight=步行高度
```

2022-01-13 03:21 UTC, StarryVoid commented
修完了，为了考虑对照英文翻译和整体连贯，已整块翻译放入。

2022-01-13 11:50 UTC, 502y commented
我这里官方的zh_cn.lang似乎缺少了一些key，正在与en-us.lang核对。

2022-01-14 06:06 UTC, StarryVoid commented
> **~我这里官方的zh_cn.lang似乎缺少了一些key，正在与en-us.lang核对。~** 问题已解决。

官方中文的闪耀宝石是 2 级材料 （应该是 3 级）

2022-01-14 10:06 UTC, 502y commented
> > **~我这里官方的zh_cn.lang似乎缺少了一些key，正在与en-us.lang核对。~** 问题已解决。
> 
> 官方中文的闪耀宝石是 2 级材料 （应该是 3 级）

这个问题在新的官中语言文件里修复了，需要等到作者发布新版本才能看到修改后的语言文件。

2022-01-16 02:06 UTC, TUsama commented on projects/1.12.2/assets/Trinkets-and-Baubles/xat/zh_cn.lang
> +item.weightless_stone.0.tooltip2=<#yellow:左键#reset:>以#darkgreen:上升
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

此处应为左击，左键为鼠标的一个键位。
下面那一行同理。
右键也需修改。

2022-01-16 02:29 UTC, 502y commented on projects/1.12.2/assets/Trinkets-and-Baubles/xat/zh_cn.lang
> +item.weightless_stone.0.tooltip2=<#yellow:左键#reset:>以#darkgreen:上升
感谢指正，已在官中修改。Gihub 这边不是很明白如何操作，这个工作只能留给 @StarryVoid 了。

2022-01-16 03:34 UTC, TUsama commented
官中是没有翻译完是吗？差了700行左右。

2022-01-16 04:09 UTC, StarryVoid commented
所以官中到底涉及多少东西……要不让官中提交pr吧。我这实际使用rlcraft上的信息都有了，但是本身配置文件还有许多内容。那我先关了pr。

2022-01-16 04:09 UTC, closed without merging

2022-01-16 04:14 UTC, 502y commented
> 官中是没有翻译完是吗？差了700行左右。

现在官中主要没有汉化的部分是只有语言文件但未制作对应物品的饰品和模组设置中的文本。上次更新中，作者为模组添加了帕秋莉手册，目前主要精力是在翻译手册。

2022-01-21 04:43 UTC, StarryVoid commented
所以有没有一个官汉的定数，目前是外挂语言包，但是我这边不清楚到底有多少需要汉化的部分……
如果没什么意向，我会移除相关分支。如果认为需要使用该翻译暂时补充，我会重开pr。

2022-07-19 06:59 UTC, StarryVoid commented
@502y 咕咕咕……（看了一下没变化）