[R] lycanites mobs 1.12.2-2.0.8.4中文完全汉化（未完全合并i18n历史汉化内容）
CFPAOrg/Minecraft-Mod-Language-Package pull request #1507
Opened 2022-01-12 16:37 UTC by StarryVoid

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [ ] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-01-12 17:04 UTC, StarryVoid commented
原始数据优先参考官方 en_us 和 zh_cn 版本，未与旧版本 i18n 数据进行比对校正。
数据含机翻内容，保证阅读后可顺畅游玩全MOD
所有的鞍的介绍没有翻译，以英文落地

2022-01-12 17:37 UTC, StarryVoid commented
宙斯盾(Aegis) Byzz's Busy Armoury
Rlcraftr 关于前者 Aegis 已翻译成宙斯盾
后者在图鉴和村庄自动生成的部分始终为 Byzz's Busy Armoury
Ly官方英文没有发现该生物，暂时无法命名。

2022-01-13 03:06 UTC, TUsama commented on projects/1.12.2/assets/lycanites-mobs/lycanitesmobs/lang/zh_cn.lang
> +message.beastiary.rank=你进一步了解了%creature%解锁知识等级%rank%！
此处是否需要添加空格？

2022-01-13 03:07 UTC, TUsama commented on projects/1.12.2/assets/lycanites-mobs/lycanitesmobs/lang/zh_cn.lang
> +message.beastiary.study.full=完整生物知识:
标点符号问题。

2022-01-13 03:14 UTC, TUsama commented on projects/1.12.2/assets/lycanites-mobs/lycanitesmobs/lang/zh_cn.lang
>  #
288 行的改动是否在新版中被移除了？

2022-01-13 03:14 UTC, TUsama commented on projects/1.12.2/assets/lycanites-mobs/lycanitesmobs/lang/zh_cn.lang
> +lyc.version.newer=你目前正在使用的恐怖生物版本是 {current} 但现在发现有新版本 {latest}，建议你通过更新来获得更好的体验！
```suggestion
lyc.version.newer=你目前正在使用的恐怖生物版本是 {current}，但现在发现有新版本 {latest}，建议你通过更新来获得更好的体验！
```

2022-01-13 03:19 UTC, TUsama commented on projects/1.12.2/assets/lycanites-mobs/lycanitesmobs/lang/zh_cn.lang
> +equipment.slottype=格子类型：
```suggestion
equipment.slottype=物品槽类型：
```
inventory 为物品栏，后跟 slot 则为物品槽/槽位。

2022-01-13 03:20 UTC, TUsama commented on projects/1.12.2/assets/lycanites-mobs/lycanitesmobs/lang/zh_cn.lang
> +equipment.feature.slot=增加格子：
equipment.sharpness=Sharpness: 这些是在新版本中移除了？

建议是将仓库内的英文更新到你翻译的那个版本，否则review比较困难。

2022-01-13 03:22 UTC, TUsama commented on projects/1.12.2/assets/lycanites-mobs/lycanitesmobs/lang/zh_cn.lang
> +tile.equipmentforge_lesser.description=此锻造台可用于从1级生物身体部位创建新装备（如果可能，更高级别的部件将降级）。
比较推荐使用“制作”而不是“创建”，不符合汉语表达习惯。

2022-01-13 03:25 UTC, TUsama commented on projects/1.12.2/assets/lycanites-mobs/lycanitesmobs/lang/zh_cn.lang
>  tile.scorchfire.description=一种附带魔法的火焰，它不像传统的火焰那么炽热，但当贸然进入的实体穿过它时将会受到承重的伤害。
此处翻译似有误。

2022-01-13 03:27 UTC, StarryVoid commented on projects/1.12.2/assets/lycanites-mobs/lycanitesmobs/lang/zh_cn.lang
> +message.beastiary.rank=你进一步了解了%creature%解锁知识等级%rank%！
加和不加在游戏中都是屏幕中央下方浮现的小段文字……变量具体内容是数字
可以考虑增加空格。

2022-01-13 03:29 UTC, TUsama requested changes
1.13

老的翻译问题仍是存在的。

2022-01-13 03:40 UTC, StarryVoid commented on projects/1.12.2/assets/lycanites-mobs/lycanitesmobs/lang/zh_cn.lang
> +tile.equipmentforge_lesser.description=此锻造台可用于从1级生物身体部位创建新装备（如果可能，更高级别的部件将降级）。
源本项目旧翻译，已修

2022-01-13 03:50 UTC, StarryVoid commented
> 1.13
> 
> 老的翻译问题仍是存在的。

我没有动老翻译，先完成的全汉化……并不是精修，主要是补齐所有的英文翻译和语句翻译

2022-01-13 03:51 UTC, StarryVoid commented on projects/1.12.2/assets/lycanites-mobs/lycanitesmobs/lang/zh_cn.lang
>  tile.scorchfire.description=一种附带魔法的火焰，它不像传统的火焰那么炽热，但当贸然进入的实体穿过它时将会受到承重的伤害。
已修

2022-01-13 03:56 UTC, StarryVoid commented on projects/1.12.2/assets/lycanites-mobs/lycanitesmobs/lang/zh_cn.lang
> +equipment.feature.slot=增加格子：
误删，已修。

2022-01-13 03:59 UTC, StarryVoid commented on projects/1.12.2/assets/lycanites-mobs/lycanitesmobs/lang/zh_cn.lang
> +equipment.slottype=格子类型：
实际为一个指定工作台中拜访的格子，称呼物品槽更像是一种手持物品的感觉。所以意向修正为 槽位。
游戏中的内容为：拿出部件，打开L3大师锻造台的GUI，在上面的指定格子（栏位/槽位）摆放物品

2022-01-13 04:55 UTC, StarryVoid commented
游戏内的菜单结构为 

宠物 
- 宠物
- 坐骑
- 妖精

仆从
- 仆从

前者宠物无法和子项宠物做区分，考虑上下文修正为 宠物 坐骑 妖精 三块，不使用  宠物-坐骑 宠物-妖精

2022-01-13 07:56 UTC, StarryVoid commented
反馈上来的都修过了。

2022-01-14 03:42 UTC, StarryVoid commented
到这了，剩下的不弄了。
https://wwe.lanzouy.com/b020wv3yd 密码:3nej
PR合并前 封装的 单MOD 测试包，Rlcraft玩家可以挂材质最上面测试。

2022-01-18 02:36 UTC, TUsama commented on projects/1.12.2/assets/lycanites-mobs/lycanitesmobs/lang/zh_cn.lang
> +item.arachnidtreat.name=节肢的款待
我想问一下，这个到底是指代哪一类的生物？你这里我修改为蛛形，原先你这里是节肢，又和上方的节肢重复了。而根据官方 wiki，节肢用的词是Arthropods，所以应该是上面的那个用节肢。
而根据https://www.mcmod.cn/item/78102.html得知，这里指的应该是蛛形生物。那么文本中其他的arachnid应做统一修改。
若有什么疑虑可提出，因为我没玩过，可能对这些概念理解有误。

2022-01-21 01:11 UTC, StarryVoid commented on projects/1.12.2/assets/lycanites-mobs/lycanitesmobs/lang/zh_cn.lang
> +item.arachnidtreat.name=节肢的款待
游戏内这个类别是一大堆蜘蛛，不同属性的蜘蛛在这个栏目中，然后额外有个骑斗士，也是一堆腿。我翻译成节肢是用的原版词汇 节肢杀手 的节肢，因为这个类别是节肢杀手有效的类别。
早期确实是节肢动物，考虑整齐把这排类别缩减到两个字了。
蛛形确实是比较好一点的翻译，我会整体修掉。

2022-01-21 01:17 UTC, TUsama commented on projects/1.12.2/assets/lycanites-mobs/lycanitesmobs/lang/zh_cn.lang
> +item.arachnidtreat.name=节肢的款待
我改了，arachnid保留为蛛形，anthronian现译为类人。

2022-01-21 01:35 UTC, TUsama commented
不行，arthropod得是节肢，现在有两个蛛形灵魂石了。

2022-01-21 01:46 UTC, StarryVoid commented
> 不行，arthropod得是节肢，现在有两个蛛形灵魂石了。

在新版本这个类别已经被彻底换成arachnid了。所以同名是可行的。要不加个 （旧）呢

2022-01-21 01:46 UTC, TUsama commented
这样可以，那先保留。在上面加个注释之类的。

2022-01-21 02:24 UTC, StarryVoid commented
> 这样可以，那先保留。在上面加个注释之类的。

我意识到我评论review只会发给我自己……可以的话麻烦看一下网页，在上面有一些词汇讨论。

以及，网页一起改会来回撤销。这里如果还在修改。我以回复的方式先标记。
item.soulstone_arthropod.name=蛛形灵魂石（旧）
entity.joust.description=凶猛的蛛形生物，它们可以被繁殖，喜欢仙人掌绿！

2022-01-21 02:25 UTC, TUsama commented
我现在没在修改，你要改的现在可以改了。

2022-01-21 06:29 UTC, TUsama commented
最后挂两天然后入库了。

2022-01-23 13:31 UTC, merged