[R] 更新工业线缆 Industrial Wires ReEngineered
CFPAOrg/Minecraft-Mod-Language-Package pull request #1508
Opened 2022-01-13 10:26 UTC by kappa-maintainer

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [x] 刷新 PR 的标签/状态，有需要再点击；

该模组[老版本](https://www.curseforge.com/minecraft/mc-mods/industrial-wires)已停止维护（见[此处](https://github.com/malte0811/IndustrialWires/issues/84#issuecomment-568867100)），此PR将原文换成原作者建议使用的[fork](https://www.curseforge.com/minecraft/mc-mods/industrial-wires-reengineered)，并修正了之前的大量错译和机翻。
因为模组自制的排版（以及MC的排版）会造成中文显示效果奇差，难以阅读，还开发了修正模组，前置为MixinBooter：https://cloud.lilywhite.cc/s/7BLFA

2022-01-14 04:34 UTC, TUsama requested changes

2022-01-14 04:34 UTC, TUsama commented on projects/1.12.2/assets/industrial-wires-reengineered/industrialwires/lang/zh_cn.lang
> +ie.manual.entry.industrialwires.mech_mb_parts.commutator=<np><&5>整流器能转换同步交流电和直流电。只有在多方块结构转速超过 5 rad/s 时, 它才会工作, 超过 10 rad/s 的旋转速度才能让它的工作效率达到 100%%。上面的预览显示的是四相版本，单相版本只包含在轴位置放置的一个 IC2 动能发生器。它的能量传输速度只有相
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

标点。

2022-01-14 04:53 UTC, kappa-maintainer commented on projects/1.12.2/assets/industrial-wires-reengineered/industrialwires/lang/zh_cn.lang
> +ie.manual.entry.industrialwires.mech_mb_parts.commutator=<np><&5>整流器能转换同步交流电和直流电。只有在多方块结构转速超过 5 rad/s 时, 它才会工作, 超过 10 rad/s 的旋转速度才能让它的工作效率达到 100%%。上面的预览显示的是四相版本，单相版本只包含在轴位置放置的一个 IC2 动能发生器。它的能量传输速度只有相
是说改成“机械多方块结构：部件”还是啥

2022-01-15 11:05 UTC, kappa-maintainer commented
(转速 + 1) 是表达式，所以才决定不用中文标点，但也可以改

2022-01-15 15:08 UTC, TUsama commented on projects/1.12.2/assets/industrial-wires-reengineered/industrialwires/lang/zh_cn.lang
> +ie.manual.entry.industrialwires.mech_mb_parts=轴是你能想到的最简单的部件——它什么都不做。不过多方块中的轴可以用于区分多方块结构中不同的电气部分。它由一个多方块横截面中心的重型工程块组成。<np><&0>飞轮是另一个非常简单的部件：它唯一的功能是带来惯性以增加能量存储能力。飞轮可以使用多种材料搭建，包括在上面预览中使用的铅块。下页的表格显示了所有可用
我感觉原文说的是，它自己没啥用，必须配合别的部件才行的意思？

2022-01-15 15:10 UTC, kappa-maintainer commented on projects/1.12.2/assets/industrial-wires-reengineered/industrialwires/lang/zh_cn.lang
> +ie.manual.entry.industrialwires.mech_mb_parts=轴是你能想到的最简单的部件——它什么都不做。不过多方块中的轴可以用于区分多方块结构中不同的电气部分。它由一个多方块横截面中心的重型工程块组成。<np><&0>飞轮是另一个非常简单的部件：它唯一的功能是带来惯性以增加能量存储能力。飞轮可以使用多种材料搭建，包括在上面预览中使用的铅块。下页的表格显示了所有可用
是真的没用，摆出来最多也就给结构分个段，而且还是纯视觉

2022-01-15 15:12 UTC, TUsama commented on projects/1.12.2/assets/industrial-wires-reengineered/industrialwires/lang/zh_cn.lang
> +ie.manual.entry.industrialwires.mech_mb_parts=轴是你能想到的最简单的部件——它什么都不做。不过多方块中的轴可以用于区分多方块结构中不同的电气部分。它由一个多方块横截面中心的重型工程块组成。<np><&0>飞轮是另一个非常简单的部件：它唯一的功能是带来惯性以增加能量存储能力。飞轮可以使用多种材料搭建，包括在上面预览中使用的铅块。下页的表格显示了所有可用
那改成“它啥用没有”之类的会更好一点，一般中文里不会说不会动的东西会做动作。

2022-01-16 02:00 UTC, merged