[R] Etched 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1522
Opened 2022-01-29 17:59 UTC by ChuijkYahus

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [ ] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-02-07 03:15 UTC, baka-gourd requested changes

2022-02-07 03:15 UTC, baka-gourd commented on projects/1.16/assets/etched/etched/zh_cn.json
> +  "record.etched.downloadProgress": "已下载 (%s MB / %s MB)：%s",
这里是正在下载吧

2022-02-08 03:39 UTC, TUsama requested changes

2022-02-08 03:39 UTC, TUsama commented on projects/1.16/assets/etched/etched/zh_cn.json
> +  "item.etched.etched_music_disc.sound_cloud": "SoundCloud 提供",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

库内现要求英文与中文之间不添加空格，下方的唱片下载失败同理。

2022-02-08 08:34 UTC, ChuijkYahus commented on projects/1.16/assets/etched/etched/zh_cn.json
> +  "item.etched.etched_music_disc.sound_cloud": "SoundCloud 提供",
改动完成

2022-02-08 08:34 UTC, ChuijkYahus commented on projects/1.16/assets/etched/etched/zh_cn.json
> +  "record.etched.downloadProgress": "已下载 (%s MB / %s MB)：%s",
这样更好，之前看到两个MB就当已下载了
改动完成

2022-02-08 08:41 UTC, merged