[R] Tetranomicon 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1529
Opened 2022-02-09 15:42 UTC by ChuijkYahus

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [ ] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-02-09 15:43 UTC, ChuijkYahus commented
原模组中有英文键值缺失现象
按照源码放了一些上去，英文不做修改

2022-02-12 06:14 UTC, Lyaiya requested changes

2022-02-12 06:14 UTC, Lyaiya commented on projects/1.16/assets/tetranomicon/tetranomicon/lang/zh_cn.json
> +  "tetra.improvement.basic_handle/wrap_flamescale.description": "增加攻击、攻速与耐久，降低手柄负面效果。",
```suggestion
  "tetra.improvement.basic_handle/wrap_flamescale.description": "增加伤害、速度和耐久，降低手柄负面效果。",
```
遵循原文，且这里用“和”字更好，下面也一样。若用“与”字，速度加上耐久，才和伤害成并列关系，但这里应该是三者成并列关系。

2022-02-12 06:14 UTC, Lyaiya commented on projects/1.16/assets/tetranomicon/tetranomicon/lang/zh_cn.json
> +  "tetra.improvement.stave_grip/wrap_flamescale.description": "增加拉弓力量、拉弓速度与耐久。",
“与”字改动同上，且这里需要在“力量”前补充“拉弓”吗？

2022-02-12 06:14 UTC, Lyaiya commented on projects/1.16/assets/tetranomicon/tetranomicon/lang/zh_cn.json
> +  "tetra.variant.double_socket/cobalt_crystal": "镶嵌[§3钴蓝色水晶§r]",
```suggestion
  "tetra.variant.double_socket/cobalt_crystal": "镶嵌[§3钴蓝水晶§r]",
```
本库中的译名已去掉其中的“色”字，下同

2022-02-12 10:13 UTC, ChuijkYahus commented on projects/1.16/assets/tetranomicon/tetranomicon/lang/zh_cn.json
> +  "tetra.improvement.basic_handle/wrap_flamescale.description": "增加攻击、攻速与耐久，降低手柄负面效果。",
改动完成

2022-02-12 10:13 UTC, ChuijkYahus commented on projects/1.16/assets/tetranomicon/tetranomicon/lang/zh_cn.json
> +  "tetra.variant.double_socket/cobalt_crystal": "镶嵌[§3钴蓝色水晶§r]",
改动完成

2022-02-12 13:20 UTC, ChuijkYahus commented on projects/1.16/assets/tetranomicon/tetranomicon/lang/zh_cn.json
> +  "tetra.material.thallasium": "铊",
不做修改

2022-02-12 13:20 UTC, ChuijkYahus commented on projects/1.16/assets/tetranomicon/tetranomicon/lang/zh_cn.json
> +  "tetra.material.therium": "钍",
不做修改

2022-02-12 13:38 UTC, Lyaiya commented on projects/1.16/assets/tetranomicon/tetranomicon/lang/zh_cn.json
> +  "tetra.material.thallasium": "铊",
你现在不做修改，入库也会改掉的，而且在本库中这两个错译相关的条目也已保留原文。

2022-02-12 13:40 UTC, ChuijkYahus commented on projects/1.16/assets/tetranomicon/tetranomicon/lang/zh_cn.json
> +  "tetra.material.thallasium": "铊",
啊这，之前看错意思了，十分抱歉
已改动

2022-02-12 13:41 UTC, merged