[R] Essentials和交错道途 1.18
CFPAOrg/Minecraft-Mod-Language-Package pull request #1537
Opened 2022-02-15 04:15 UTC by kappa-maintainer

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [x] 刷新 PR 的标签/状态，有需要再点击；

改动集中于巫术的内容和适应1.18的粗矿
为避免错误不传手册

2022-02-15 06:15 UTC, Lyaiya commented on projects/1.18/assets/essentials/essentials/lang/zh_cn.json
> +	"block.essentials.multi_piston_sticky": "粘性倍能活塞",
Sticky Piston 黏性活塞

2022-02-15 06:15 UTC, Lyaiya commented on projects/1.18/assets/essentials/essentials/lang/zh_cn.json
> +	"block.essentials.wither_cannon": "凋零加农炮",
应该是凋灵吧，看后文介绍有个凋零之首（正确为凋灵之首）

2022-02-15 06:15 UTC, Lyaiya commented on projects/1.18/assets/essentials/essentials/lang/zh_cn.json
> +	"tt.essentials.equals_circuit": "当且仅当两个输入相等(差距在0.1%以内)时输出1",
中文标点符号

2022-02-17 15:23 UTC, SlimeSB requested changes

2022-02-17 15:23 UTC, SlimeSB commented on projects/1.18/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"block.crossroads.copshowium_creation_chamber": "锞灌注器",
想请求钶→锞的改动理由。

2022-02-17 15:23 UTC, SlimeSB commented on projects/1.18/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"item.crossroads.solid_eldrine": "凝固奥秘素",
```suggestion
	"item.crossroads.solid_eldrine": "固化奥秘素",
```
固化的话，可以说氮的固化、水泥的固化。而凝固只能用于液体，水的凝固。所以这里的奥秘素之类的我觉得更像气体一点，所以使用固化一词。

2022-02-17 15:23 UTC, SlimeSB commented on projects/1.18/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"block.crossroads.embryo_lab": "米勒-尤里仓",
```suggestion
	"block.crossroads.embryo_lab": "米勒-尤里实验仓",
```

2022-02-17 15:23 UTC, SlimeSB commented on projects/1.18/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"item.minecraft.potion.effect.transient": "灵魂无常药水",
可以描述一下药水效果吗

2022-02-17 15:23 UTC, SlimeSB commented on projects/1.18/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"tt.crossroads.firebox": "燃烧燃料的时候温度上升：%1$d °C/t",
这个我记得吃了统一性更改的，用这个 “℃” 应该

2022-02-17 15:23 UTC, SlimeSB commented on projects/1.18/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"tt.crossroads.blast_furnace.desc": "使用碳融化矿物碎块和矿砂",
ore一般译作矿石

2022-02-17 15:23 UTC, SlimeSB commented on projects/1.18/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"tt.crossroads.syringe.desc": "用于注射药水（效率为平时%1$f倍）或者取血样",
```suggestion
	"tt.crossroads.syringe.desc": "用于注射药水（%1$f倍效果）或者取血样",
```

2022-02-17 15:23 UTC, SlimeSB commented on projects/1.18/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"tt.crossroads.syringe.use": "右击已自己为目标，shift右击以指向的生物为目标",
```suggestion
	"tt.crossroads.syringe.use": "右击以自己为目标，shift右击以指向的生物为目标",
```

2022-02-17 15:23 UTC, SlimeSB commented on projects/1.18/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"crossroads.jei.beam_lens.energy": "能量: %1$d%%",
此行与后几行和1021-1024重复。且原文并无出现。

2022-02-17 15:31 UTC, SlimeSB requested changes

2022-02-18 05:59 UTC, SlimeSB requested changes

2022-02-18 05:59 UTC, SlimeSB commented on projects/1.18/assets/essentials/essentials/lang/zh_cn.json
> +	"tt.essentials.fluid_shifter_info": "将内含的流体从正面排除到相邻的流体容器中",
```suggestion
	"tt.essentials.fluid_shifter_info": "将内含的流体从正面排出到相邻的流体容器中",
```

2022-02-18 05:59 UTC, SlimeSB commented on projects/1.18/assets/essentials/essentials/lang/zh_cn.json
> +	"tt.essentials.item_splitter_formula": "分配比例由红石信号强度控制：(信号强度)/15",
依然是标点符号，需要使用全角括号

2022-02-18 07:51 UTC, kappa-maintainer commented on projects/1.18/assets/essentials/essentials/lang/zh_cn.json
> +	"tt.essentials.item_splitter_formula": "分配比例由红石信号强度控制：(信号强度)/15",
感觉算式不能用中文标点，有没有相关规范

2022-02-18 08:20 UTC, SlimeSB commented on projects/1.18/assets/essentials/essentials/lang/zh_cn.json
> +	"tt.essentials.item_splitter_formula": "分配比例由红石信号强度控制：(信号强度)/15",
暂时保留吧，是的数学这些领域的符号不是“标点符号”。

2022-02-18 08:26 UTC, SlimeSB commented on projects/1.18/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"block.crossroads.copshowium_creation_chamber": "锞灌注器",
同意更改，以后溯到源或者想到更好的翻译后再把锞改了。

2022-02-18 12:26 UTC, n0099 commented on projects/1.18/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"tt.crossroads.firebox": "燃烧燃料的时候温度上升：%1$d °C/t",
```suggestion
	"tt.crossroads.firebox": "燃烧燃料的时候温度上升：%1$d ℃/t",
```

2022-02-18 12:26 UTC, SlimeSB commented on projects/1.18/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"tt.crossroads.firebox": "燃烧燃料的时候温度上升：%1$d °C/t",
上面提出了

2022-02-18 12:28 UTC, n0099 commented on projects/1.18/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"tt.crossroads.firebox": "燃烧燃料的时候温度上升：%1$d °C/t",
我在这可以直接commit suggested change

2022-02-18 12:31 UTC, SlimeSB commented on projects/1.18/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"tt.crossroads.firebox": "燃烧燃料的时候温度上升：%1$d °C/t",
这个很多，得进vsc弄

2022-02-18 13:05 UTC, kappa-maintainer commented on projects/1.18/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"tt.crossroads.syringe.desc": "用于注射药水（效率为平时%1$f倍）或者取血样",
这个优先加的是持续时间，即时药水才会加效果，我看看该怎么表述

2022-02-18 13:11 UTC, n0099 commented
> 好家伙，忙了一天发现都commit了

gh网页上可以直接commit requested change

2022-02-18 13:11 UTC, kappa-maintainer commented on projects/1.18/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"item.minecraft.potion.effect.transient": "灵魂无常药水",
可以克隆出死后当场复活的生物，这些生物有该状态时被杀死不会复活
普通生物有这个状态时被杀会掉落结晶灵魂碎片，用于制作灵魂无常药水

2022-02-18 13:13 UTC, kappa-maintainer commented on projects/1.18/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"item.crossroads.solid_eldrine": "凝固奥秘素",
固化更多表达一个过程，现在是描述其性状
之前其实也是固化，后来我觉得不对才改的

2022-02-18 13:15 UTC, kappa-maintainer commented on projects/1.18/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"block.crossroads.copshowium_creation_chamber": "锞灌注器",
溯源的话我在1.12时就干过了，原文如下：
Copshowium: I have no good explanation for this one. Basically a real sounding fake element name (ends in -ium, like most things on the periodic table).

2022-02-18 13:16 UTC, kappa-maintainer commented
> > 好家伙，忙了一天发现都commit了
> 
> gh网页上可以直接commit requested change

我知道，但之前一般不会代办

2022-02-18 13:18 UTC, kappa-maintainer commented on projects/1.18/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"tt.crossroads.firebox": "燃烧燃料的时候温度上升：%1$d °C/t",
忘了这茬，复制了官库的那份

2022-02-18 13:39 UTC, SlimeSB commented on projects/1.18/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"block.crossroads.copshowium_creation_chamber": "锞灌注器",
脸滚键盘的话那就无所谓了

2022-02-18 13:58 UTC, SlimeSB commented on projects/1.18/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"tt.crossroads.syringe.desc": "用于注射药水（效率为平时%1$f倍）或者取血样",
用于描述状态效果的是等级和时间，所以在这里用效果我觉得没有问题。
改过了就不用继续改了。

2022-02-18 14:19 UTC, kappa-maintainer commented on projects/1.18/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"item.crossroads.solid_eldrine": "凝固奥秘素",
也对

2022-02-18 14:28 UTC, SlimeSB commented on projects/1.18/assets/essentials/essentials/lang/zh_cn.json
> +	"block.essentials.sin_circuit": "Sin电路",
```suggestion
	"block.essentials.sin_circuit": "正弦电路",
```
理由是：psi、betterfps都将sine直接译为正弦，后文也使用了正弦一词。其余三角函数同理。
（这行我记得发出来了，不知道为什么并没有）

2022-02-18 14:30 UTC, SlimeSB commented on projects/1.18/assets/essentials/essentials/lang/zh_cn.json
> +	"block.essentials.pulse_rising_circuit": "脉冲形成器电路[上升沿]",
```suggestion
	"block.essentials.pulse_rising_circuit": "脉冲形成器电路［上升沿］",
```
中文是有方括号的

2022-02-18 14:36 UTC, kappa-maintainer commented on projects/1.18/assets/essentials/essentials/lang/zh_cn.json
> +	"block.essentials.pulse_rising_circuit": "脉冲形成器电路[上升沿]",
电路哪来的专用

2022-02-18 14:42 UTC, merged