[R] 1.12mod：Guide-API/神秘复辟Thaumic-Restoration/神秘酿造学Thaumic-Brewing/神秘外饰ThaumicPeriphery/自然誓约NaturalPledge
CFPAOrg/Minecraft-Mod-Language-Package pull request #1559
Opened 2022-02-17 17:06 UTC by Dawnwalker666

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

分别适用于（没错，都是停更mod）：
Guide-API-1.12-2.1.8-63
thaumicperiphery-0.3.1
thaumicbrewing-1.0.2
ThaumicRestoration-1.5.0
NaturalPledge-r3.1.2

1.更新汉化，并更新了Thaumic-Restoration与Guide-API的文件名称（原mod包内名称格式为en_US.lang）
2.神秘外饰ThaumicPeriphery这里采用 @DYColdWind 的所汉化的汉化文件（即旧版本汉化）。在此基础上，对新版本内容进行汉化。谨此致谢。
3.NaturalPledge这里，诸位可能看起来有些奇怪。这个mod是植物魔法的附属，采用“植物魔法辞典”来显示内容。这本辞典有个弊病，它使用空格来当成每段的回车。对于汉语而言，没空格手册就会认为前面一整句话都是一个单词。只要我不加空格，游戏内文本就会不断延伸。因此必须人为的在每12个汉字字符后增添一个空格，作为在游戏内的分段回车。这里感谢 @WuzgXY-GitHub 提供对这个问题的解决办法。解决办法会放到下方，以供后来者使用。
4.神秘复辟这里考虑到mcmod已有相关此条，因之原有内容并未有太多改动。我知道这里已经有人汉化了，二者取其一便可。我只是把我的放到这里。
5.这些汉化我也在**好久好久**之前PR到mod作者那里去了，因为停更了，所以。。。
6.欢迎进行review，同时对以上帮助过我的人进行感谢。

解决方法如下：
使用VSCode打开。Ctrl+H，唤出替换界面。勾选上“在选定内容中查找（Alt+L）”与“使用正则表达式（Alt+R）”.
在手册内容部分用鼠标选择上。通常是“包名.page.词条名”这样的结构。
在查找的栏目里，输入
`((([\u2026-\u2027\uff01-\uff1b\u3000-\u303e\u4e00-\u9fa5])([\u0000-\u00b4])*){12})`
在替换的栏目里，输入（别忘了0后面还有个空格）
`$0 `

2022-02-18 15:56 UTC, SlimeSB requested changes

2022-02-19 09:04 UTC, SlimeSB requested changes

2022-02-19 12:29 UTC, mamaruo commented on projects/1.12.2/assets/guide-api/guideapi/lang/zh_CN.lang
> +text.book.warning=&c[警告] 删除这个物品, 它没有关联的书!
补充参考：国家标准 [标点符号用法 GB/T 15834-2011](http://www.gb688.cn/bzgk/gb/newGbInfo?hcno=22EA6D162E4110E752259661E1A0D0A8) 4.9.2 指出括号包括方括号“［］”，5.1.3 指出，括号应“占一个字位置”，故应用全角。

2022-02-19 12:34 UTC, SlimeSB commented on projects/1.12.2/assets/guide-api/guideapi/lang/zh_CN.lang
> +text.book.warning=&c[警告] 删除这个物品, 它没有关联的书!
规范内有引用

2022-02-19 12:51 UTC, mamaruo commented on projects/1.12.2/assets/guide-api/guideapi/lang/zh_CN.lang
> +text.book.warning=&c[警告] 删除这个物品, 它没有关联的书!
> 规范内有引用

规范并未强调，我也是刚知道这一回事，看到你 review 之后刚查的。看看库里的情况，难搞。
![image](https://user-images.githubusercontent.com/37480168/154801532-e07c7096-4de0-4401-aed6-59d9bbc7936b.png)

2022-02-19 13:29 UTC, Dawnwalker666 commented
> 解释解释，一是为什么把the bane丢了，二是为什么和deepl给的一样。

@SlimeSB
汉化有错误，那我肯定会虚心接受并改正。the bane确实是我的疏忽，但我认为并没有向你**解释**的必要。
第一点请你注意：你不是我上司，也不是我老板，更不是我的客户。我并不是你们i18n的成员，我只是个闲云野鹤罢了。你甚至把我可以当成子虚先生，一个根本不存在的人。我就是个社区汉化者，也就是力所能及的为游戏社区尽一份力，甚至还是个免费劳工。
第二点，我确实喜好帮助玩家帮助他人，因为我入坑minecraft也收到不少大佬的帮助，所以我以前也加入mcmod写了些条目写了些教程。但此种动机这并不是让别人在道德高地上指指点点我的理由。
这份汉化是我为了某个TC整合包来做的汉化。我当初承诺，他们需要我的时候，我一定会来帮助他们，即使现在我不太碰minecraft了。这些份汉化，以及我已经找不到的其他汉化（估计上传之后就在回收站删掉了），已经做成并供人使用了好久好久，历经数十次更新，可以说是身经百战也不为过。萌新很感激，也没有人来指责我，让我来解释这解释那的。我也坚持履行诺言，做好分内之事。
我既懒得上传bbs，也懒得上传mcmod。因为这些都是早早停更的mod，所以虽然我PR到作者那里，作者也没有更新。想着只供一小圈子内使用，也不太好。看CFPA出了事，才想起来有个i18n的组织，正巧还是个遵循CC协议，所以才上传到这里的。
这本身就是给一个TC魔法主题的整合包写的汉化。并不是非得上传到i18n这样。。。
我很随心的，并**不是求着**你们i18n收录的。。。所以你们回复的时候，我更希望你们能端正态度。社区上传汉化者本着雷锋的自我奉献精神来上传汉化，与i18n应该是**平等互助**的关系。并**不是上下级**的关系！我希望后来者能明白这一点。
上传这件事，可以但不必要。我翻译的地方有不妥或疏漏之处我可以修改，这些个地方的确是我的疏忽。但是我觉得没必要向任何人**解释**或者**道歉**。
***
至于除此人观点以外的其他人进行review回复的。待到几天后不忙了，我会逐一进行总结并改正。多谢诸位抽出时间来进行review。
另外，如若此人是你i18n之管理者当权者，那我对i18n的未来发展很担忧。如果某些人觉得我的观点偏激等等，建议**直接关闭PR**。关于此事之后续回复，我不会再关注以及进行回复。

2022-02-19 14:10 UTC, n0099 commented on projects/1.12.2/assets/guide-api/guideapi/lang/zh_CN.lang
> +text.book.warning=&c[警告] 删除这个物品, 它没有关联的书!
翻译规范里很多这样的细节都没具体规定

2022-02-19 15:05 UTC, SlimeSB commented
难得容您写篇小作文来声讨我。
关于态度问题，我和前朝元老一样，对机翻0容忍，不可能妥协。之所以以这种“傲慢”的说法，是希望给你提个醒，不要再使用以至滥用机器翻译。而对于其他的错漏之处，我一直尽量按清秋对我的指导那样，言之有理的给你提出来，对吧。
所以你也不要太激动，也不必给我扣上一个好大的官威的帽子。同时我也希望你能够认真对待翻译，而不是摆出一副爱审审的态度。

2022-02-19 15:54 UTC, n0099 commented
19年那会通过weblate提交的少数gtce翻译commit是机翻：
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/e69f1966835060a5027a71ad1ba1cbc3c814b08d#diff-fb52c743e6feb9f6914c669197ee6b4117b3e490d25a06ba2b5c3e08a9bad566R2812
![](https://user-images.githubusercontent.com/13030387/154808190-6c6699bb-8681-4dd6-95ca-bb2f10283cce.png)

https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/09bc850d75fea8d7dc9fc8d4e5cd819c718eaee6#diff-fb52c743e6feb9f6914c669197ee6b4117b3e490d25a06ba2b5c3e08a9bad566R2913
![](https://user-images.githubusercontent.com/13030387/154808269-3000f620-2163-4559-b96a-179b571b3b0c.png)
![](https://user-images.githubusercontent.com/13030387/154808267-a4646f7a-5046-4f06-a4a5-43c8f3bf3e0e.png)

2022-02-19 16:07 UTC, SlimeSB commented
@n0099 **首先哈，我不是给他们洗地的，不存在前朝元老就是我心中的神，我心中的偶像。**其次想请教你在此把矛头引向gtce居心何在？如果你和我一样反对机器翻译，大可不必特意回复我。否则我想知道你支持机翻的理由。
说到底，我不是来对线的，在pr下面发的无关内容也够多了，你对我的不满或讽刺或这个那个的，请转战频道或者与我私聊。

2022-02-19 16:10 UTC, n0099 commented
> @n0099 **首先哈，我不是给他们洗地的，不存在前朝元老就是我心中的神，我心中的偶像。**其次想请教你在此把矛头引向gtce居心何在？如果你和我一样反对机器翻译，大可不必特意回复我。否则我想知道你支持机翻的理由。 说到底，我不是来对线的，在pr下面发的无关内容也够多了，你对我的不满或讽刺或这个那个的，请转战频道或者与我私聊。

我没有支持gtce中部分使用机翻的意思，我也不在CFPAqq群或频道

2022-02-19 16:18 UTC, SlimeSB commented
@n0099 是否同意让我删除这几段comment。顺便一提，你负责的核科学仍存在客观的错误，和mamaruo一起re-review去吧

2022-02-19 16:21 UTC, mamaruo commented
Naquadah 事件中 ChromaPIE 遭到声讨至少原因是他说的话而不是做的事。

CFPA 还处在余波之中，能小心点就小心点吧。

核科学明天再战。

2022-02-19 16:25 UTC, EnderAvaritia commented
@SlimeSB 首先，我知道近期发生的事对双方影响都很大，但是工作还是得继续做下去的，不能因为情绪而影响到使用者，不然就真的成乐子了，其次，还是有些路人想要共享自己的翻译的，并不是每个人都会去看守则，有的人只是自己顺手翻译了，然后看着有用，就好心过来帮助我们，以我们的标准要求并不清楚的人，这本身就很过分。再者，这句话
> 解释解释，一是为什么把the bane丢了，二是为什么和deepl给的一样。

的语气委实很难让人接受。

2022-02-19 19:21 UTC, Cyl18 commented
关于文件名：感觉项目内都是采用的全小写zh_cn.lang及en_us.lang

2022-02-19 19:27 UTC, n0099 commented
> 关于文件名：感觉项目内都是采用的全小写zh_cn.lang及en_us.lang

可能那个mod读文件名时大小写敏感

2022-02-20 01:38 UTC, MikhailTapio commented
> 关于文件名：感觉项目内都是采用的全小写zh_cn.lang及en_us.lang

这个应该是根据模组的 pack_format 决定：
f = 2 -> xx_XX.lang;
f = 3 -> xx_xx.lang.

2022-02-20 08:47 UTC, TartaricAcid commented
@Dawnwalker666 非常抱歉，已经对维护者私下提出来批评和指正，也欢迎以后继续提交翻译，有问题可以随时 @TartaricAcid 我

2022-02-20 08:57 UTC, SlimeSB commented
@Dawnwalker666 我向你道歉，我在审核的时候确实语气过重。之后我会注意措辞，理性的进行修改建议。

2022-02-23 03:59 UTC, Dawnwalker666 commented
@TartaricAcid 这倒没什么，但是哈人的是，闲来无事，我翻了翻QQ好友未验证通过的通知.。发现已经有来源是硅岩社区的带佬，起着一个想要“教育”我的昵称，想要加好友。幸亏被好友验证拦下了。
果然应了群里某些人说的话
![图片](https://user-images.githubusercontent.com/49862610/155258305-41cb38ec-6348-4618-bb71-1c8bb9883897.png)

***
此事暂不提。我本人对机翻的态度并不像贵组织那样深恶痛绝。能用优秀的工具来节省人力节省时间是很有必要的。至于机翻来说，保证语句通顺，模组内专有名词一致即可。没有必要像论文降重一样，把机翻的语句重新打的跟原机翻的一点不一样。。查重率5%？
至于自然誓约。一部分是社区内已有的汉化（就像mcmod里的部分已经汉化出来的词条一样），我只不过对其进行明显错误的修改与未翻译的地方进行简译。本着约定俗成的原则，能不动就不动（鉴于最近风波考虑）。而其他的模组翻译我已经不记得多少时间以前弄出来的。
我深知自我检查一定会有疏漏之处，所以需要发到这里来，让专业人士进行审查和校对，没想到能搞出这种事情实在是不好意思。
如果觉得上面翻译，各位觉得万不可接受的话，直接关闭PR我也是没有意见的。如果各位暂且能接受，那过几天我再来看看review的情况。十分感谢。

2022-02-25 12:02 UTC, merged