[R] Electrodynamics
CFPAOrg/Minecraft-Mod-Language-Package pull request #1562
Opened 2022-02-18 00:38 UTC by MikhailTapio

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

标注和意见征询：

1. L105、L108、L163、L395、L399、L403、L404、L411、L412、L481-484 中内容未实现，不能确定相应翻译是否准确。
2. L229-247、L324-L335 中，使用了直译的 XX、二联XX、三联XX 来区分机器的等级，官翻则是 XX、XX厂、高级XX厂。**哪种译法更合理？**

2022-02-18 12:31 UTC, n0099 commented
> L229-247、L324-L335 中，使用了直译的 XX、二联XX、三联XX 来区分机器的等级，官翻则是 XX、XX厂、高级XX厂。哪种译法更合理？
后者好读，前者好搜索

2022-02-20 00:46 UTC, Cyl18 requested changes

2022-02-20 00:46 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.cobblestonegenerator" : "圆石温差发电机",
原文就圆石发电机
温差体现了作用
但是俩结合起来就好怪

2022-02-20 00:46 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.wirelogisticssuperconductive" : "超导物流导线",
官库里的话是 “物流锡线” “物流超导线”
导线怪怪的
我还没在游戏内找到这个线咋用的 等下看看

2022-02-20 00:46 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.seismicmarker" : "地质标记",
```suggestion
  "block.electrodynamics.seismicmarker" : "地质标记器",
```
没有在游戏内找到这个东西 但是看block的话应该是属于方块

2022-02-20 00:46 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "container.electricfurnace2" : "高级熔炼工厂",
最后统一一下是工厂还是双联

2022-02-20 00:46 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.chargerhv" : "480 V 充电器",
统一一下

2022-02-20 00:46 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "container.cobblestonegenerator" : "圆石温差发电机",
同上

2022-02-20 00:46 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "gui.motorcomplex.speed" : "Ticks per Block: %s",
```suggestion
  "gui.motorcomplex.speed" : "刻每方块: %s",
```

2022-02-20 00:46 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.itemwire.info.ceramic" : "电压 ≤ 480.0 V 时不发生触电",
```suggestion
  "tooltip.itemwire.info.insulated" : "在电压 ≤ 240.0V 时不会发生触电",
  "tooltip.itemwire.info.highlyinsulated" : "在电压 ≤ 960.0V 时不会发生触电",
  "tooltip.itemwire.info.ceramic" : "在电压 ≤ 480.0V 时不会发生触电",
```
怎么改都怪怪的

2022-02-20 00:46 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.info.capacityupgradevoltage" : "将机器最大通电电压升高到 %s",
```suggestion
  "tooltip.info.capacityupgradevoltage" : "会将机器最大通电电压提高到最大 %s 倍",
```

2022-02-20 00:46 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.info.dirlist" : "当前方向列表:",
```suggestion
  "tooltip.info.dirlist" : "当前方向列表：",
```

2022-02-20 00:46 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.info.xpusage" : "Shift + 右键点击以取出经验",
```suggestion
  "tooltip.info.nodirs" : "Shift + 右键点击以添加一个方向",
  "tooltip.info.cleardirs" : "Shift + 左击以清除选中方向",
  "tooltip.info.insmartmode" : "智能模式",
  "tooltip.info.togglesmart" : "右击以打开智能模式",
  "tooltip.info.guidebookuse" : "Shift + 右击以打开指南",
  "tooltip.info.guidebooktemp" : "敬请期待",
  "tooltip.info.concretejoke" : "万物之始",
  "tooltip.info.xpstored" : "经验储量: %s",
  "tooltip.info.xpusage" : "Shift + 右击以取出经验",
```

2022-02-20 00:46 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.seismicscanner.use" : "扫描以16格为基础半径的范围内的矿石",
```suggestion
  "tooltip.seismicscanner.use" : "扫描以 16 格为基础半径的范围内的矿石",
```

2022-02-20 00:46 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.seismicscanner.showuse" : "Shift + 右键点击以扫描",
```suggestion
  "tooltip.seismicscanner.opengui" : "右击以查看机器状态",
  "tooltip.seismicscanner.oncooldown" : "冷却中",
  "tooltip.seismicscanner.showuse" : "Shift + 右击以扫描",
```

2022-02-20 00:46 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.countdown.tickstillcheck" : "距下次检查还有：%s Tick",
```suggestion
  "tooltip.countdown.tickstillcheck" : "距下次检查还有：%s 刻",
```

2022-02-20 00:46 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.quarry.power" : "升级需要电能以运行",
有点别扭

2022-02-20 00:46 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "jei.info.item.upgradeitemoutput" : "自动弹出升级是自动化狂热者最好的伙伴之一。应用该升级的方块将会向用户所指定方向的临近方块弹出物品。该升级提供两种模式：默认模式与智能模式。默认模式中，该升级将尝试提取本机器中所有的输出槽（包括双产品槽），并将被提取的物品根据用户所指定的方向顺序，向相应方向弹出。在方向指定中重复指定同一个方向没有意义。在智能模式下，每个
```suggestion
  "jei.info.item.upgradeitemoutput" : "自动弹出升级是自动化狂热者最好的伙伴之一。应用该升级的方块会将用户所指定方向的临近方块弹出物品。该升级提供两种模式：默认模式与智能模式。默认模式下，该升级将尝试提取本机器中所有的输出槽（包括双产品槽），并将被提取的物品根据用户所指定的方向顺序，向相应方向弹出。在方向指定中重复指定同一个方向没有意义。在智能模式下，每个输出槽按顺序被映射到一个对应的方向。例如，假设一台机器有 2 个输出槽，而该升级中指定的方向是 \"北 \"和 \"南\"。以这个顺序，输出槽 1 将会向北方的方块弹出物品，而输出槽 2 将会向南方的方块弹出物品。 你也可以多次指定相同的弹出方向，如 \"北\" \"北\"。",
```

2022-02-20 00:46 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "key.electrodynamics.togglenvgs" : "打开/关闭 夜视护目镜",
切换夜视护目镜？
启用/关闭?

2022-02-20 00:46 UTC, Cyl18 commented
剩下的问题还是统一/纠结 `120V` 还是 `120 V`

2022-02-20 00:52 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "jei.info.fluid.combustionchamberfuel" : "燃烧室 燃料：\n    生产：%2$s kW\n    消耗：%1$s mb."
```suggestion
  "jei.info.fluid.combustionchamberfuel" : "燃烧室 燃料：\n    生产：%2$s kW\n    消耗：%1$s mB."
```

2022-02-20 00:56 UTC, Cyl18 commented
另外我从curseforge下的 Electrodynamics-1.18.1-0.5.9-0.jar en_us.json 只有 494 行 不知道你用的啥版本？

2022-02-20 01:10 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.rodtitaniumcarbide" : "碳化钛棒",
> 感觉杆和棒可以纠结一下

参考的是原版的 烈焰棒（Blaze Rod）

2022-02-20 01:13 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.seismicscanner.showuse" : "Shift + 右键点击以扫描",
这个再看看？ 我查了一下“右击”完全合理，但之前似乎有人认为应该改回 X键点击 这种格式

2022-02-20 01:14 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.seismicscanner.showuse" : "Shift + 右键点击以扫描",
看库里这几种混用（（

2022-02-20 01:15 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "jei.info.item.upgradeitemoutput" : "自动弹出升级是自动化狂热者最好的伙伴之一。应用该升级的方块将会向用户所指定方向的临近方块弹出物品。该升级提供两种模式：默认模式与智能模式。默认模式中，该升级将尝试提取本机器中所有的输出槽（包括双产品槽），并将被提取的物品根据用户所指定的方向顺序，向相应方向弹出。在方向指定中重复指定同一个方向没有意义。在智能模式下，每个
好像应该还是本方块弹出物品，输出到临近方块，那样改的话表意就变了😂

2022-02-20 01:16 UTC, MikhailTapio commented
> 另外我从curseforge下的 Electrodynamics-1.18.1-0.5.9-0.jar en_us.json 只有 494 行 不知道你用的啥版本？

我直接从仓库拉的语言文件

2022-02-20 01:37 UTC, Cyl18 commented
要改石盐的话我记得文本下方也有 另外还是可以讨论一下石盐和岩盐哪个好

2022-02-20 12:02 UTC, n0099 commented
> 要改石盐的话我记得文本下方也有 另外还是可以讨论一下石盐和岩盐哪个好

https://dict.mcmod.cn 里两个都搜不到

2022-02-20 12:03 UTC, n0099 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.seismicscanner.showuse" : "Shift + 右键点击以扫描",
建议 使用键

2022-02-20 12:04 UTC, n0099 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.rodtitaniumcarbide" : "碳化钛棒",
gt系用的杆

2022-02-20 12:05 UTC, n0099 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.upgradeadvancedspeed" : "高级效率升级",
蓄电升级？

2022-02-20 12:05 UTC, n0099 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.upgradeiteminput" : "自动抽取升级",
弹出对应吸入

2022-02-20 12:09 UTC, n0099 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.concretemix" : "预拌混凝土",
建议电子混凝土

2022-02-20 12:10 UTC, n0099 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.deepslateoresylvite" : "深层钾石盐矿石",
也就gt系喜欢前者，因为有多种混合矿物

2022-02-20 12:10 UTC, n0099 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.electricfurnacedoublerunning" : "双联电炉（运行中）",
双联

2022-02-20 12:11 UTC, n0099 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.cobblestonegenerator" : "圆石温差发电机",
那同位素温差算什么？

2022-02-20 12:11 UTC, n0099 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.wirelogisticssuperconductive" : "超导物流导线",
锡线只是合成材料？

2022-02-20 12:12 UTC, n0099 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.seismicmarker" : "地质标记",
建议用机

2022-02-20 12:12 UTC, n0099 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "container.electricfurnace2" : "高级熔炼工厂",
建议都用等级表达

2022-02-20 12:12 UTC, n0099 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "gui.motorcomplex.speed" : "Ticks per Block: %s",
每方块 %s 刻

2022-02-20 12:13 UTC, n0099 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "key.electrodynamics.togglenvgs" : "打开/关闭 夜视护目镜",
启用/禁用

2022-02-20 13:18 UTC, SlimeSB commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.seismicscanner.showuse" : "Shift + 右键点击以扫描",
统一使用：单击、右击

2022-02-20 13:52 UTC, SlimeSB commented
对石盐和岩盐，[Wikipedia](https://zh.wikipedia.org/wiki/%E7%9F%B3%E9%B9%BD)上解释称石盐为正称，岩盐为别称。而我在知网上检索相关论文，题目中则多用岩盐而非石盐。二者的关系我引用一段摘要中的文字予以说明。
> 含石膏、石盐、钾盐在内的岩盐由海水或者湖水经蒸发……
由此看来，岩盐不仅包含氯化钠，而是众多盐类都可统称岩盐。石盐则专指来自矿脉的氯化钠。

2022-02-20 13:57 UTC, MikhailTapio commented
> 对石盐和岩盐，[Wikipedia](https://zh.wikipedia.org/wiki/%E7%9F%B3%E9%B9%BD)上解释称石盐为正称，岩盐为别称。而我在知网上检索相关论文，题目中则多用岩盐而非石盐。二者的关系我引用一段摘要中的文字予以说明。
> 
> > 含石膏、石盐、钾盐在内的岩盐由海水或者湖水经蒸发……
> 
> 由此看来，岩盐不仅包含氯化钠，而是众多盐类都可统称岩盐。石盐则专指来自矿脉的氯化钠。

那就确定为石盐吗

2022-02-20 14:01 UTC, SlimeSB commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "jei.info.item.upgradeitemoutput" : "自动弹出升级是自动化狂热者最好的伙伴之一。应用该升级的方块将会向用户所指定方向的临近方块弹出物品。该升级提供两种模式：默认模式与智能模式。默认模式中，该升级将尝试提取本机器中所有的输出槽（包括双产品槽），并将被提取的物品根据用户所指定的方向顺序，向相应方向弹出。在方向指定中重复指定同一个方向没有意义。在智能模式下，每个
这里改不改都无妨。无明显语病。

2022-02-20 14:03 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.seismicscanner.showuse" : "Shift + 右键点击以扫描",
Okay

2022-02-21 04:47 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.quarry.power" : "升级需要电能以运行",
晚上我去开游戏再看一下，读起来确实怪

2022-02-21 07:40 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.deepslateoresylvite" : "深层钾石盐矿石",
这个就不改了（

2022-02-21 07:42 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.seismicmarker" : "地质标记",
> 建议用机

标记机，听上去不太妙（

2022-02-21 07:44 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "gui.motorcomplex.speed" : "Ticks per Block: %s",
这个是不是还没实现？我想先保留原文

2022-02-21 07:56 UTC, SlimeSB commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.itemwire.info.ceramic" : "电压 ≤ 480.0 V 时不发生触电",
电压≤480.0V时不会触电

> 向1.16仓库贡献的*新建案*不再需要在数字、英文字母等半角字符与汉字等全角字符之间添加空格。
> 后续汉化包版本将*要求*不在此种情况下添加空格。

2022-02-21 08:18 UTC, SlimeSB commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.info.capacityupgradevoltage" : "将机器最大通电电压升高到 %s",
原文中%s看起来代表的是电压，具体情况可以进游戏看看。

2022-02-21 12:45 UTC, SlimeSB commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.ceramicwet" : "未干陶瓷",
可能是“陶瓷坯体”（还挺严谨用的提土旁）。如果烧制后为陶瓷就用这个吧。

2022-02-21 12:46 UTC, SlimeSB commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.concretemix" : "预拌混凝土",
可能是“导电混凝土”

2022-02-21 13:13 UTC, SlimeSB commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.rodtitaniumcarbide" : "碳化钛棒",
使用杆更为合适。
我这样给出解释：
在语用中，杆更多用来当做工具的一部分，以支撑或者自身空心结构来发挥工具应有作用。比如旗杆、笔杆、枪杆、晾衣杆、大锤用的白蜡杆等。
而棒则多是发挥“棒或者棒材料”的功能，比如胶棒、打狗棒、或者工业中的分中棒，是棒本身发挥作用。

推及到烈焰棒上，其作为烈焰粉的原料，配得上“棒”字。而如果有个魔法扫帚以它为原料，就得用烈焰杆或者烈焰棒杆来描述了。

2022-02-21 13:28 UTC, SlimeSB commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.upgradeimprovedsolarcell" : "太阳能电池升级",
Improved更多强调相较于原本的“升级”，我认为使用“改良”或者类似的更好（可能需要与热力膨胀的“强化”避讳）。而将Solar Cell译作太阳能单元，欠考虑了光热发电时的“太阳能板”。Solar Cell一般译作太阳能电池是没有问题的。

2022-02-21 13:45 UTC, SlimeSB commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.wirelogisticstin" : "锡物流导线",
锡（制）物流传输线

2022-02-21 13:51 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.concretemix" : "预拌混凝土",
受其tooltip的影响，我仍然倾向于他是在玩梗😂

2022-02-21 13:51 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.ceramicwet" : "未干陶瓷",
Okay

2022-02-21 13:52 UTC, SlimeSB commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.seismicscanner.empty" : "[无]",
全角括号［ ］。现在输入法打所谓的全角方括号统统都是【】方头括号，日常使用很少。

2022-02-21 13:53 UTC, SlimeSB commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "gui.quarry.setup" : "部署中...",
中文省略号……

2022-02-21 13:54 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.wirelogisticstin" : "锡物流导线",
我把下面的也改了，看看有没有问题

2022-02-21 13:59 UTC, SlimeSB commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.wirelogisticstin" : "锡物流导线",
我的意思是“导线→传输线”，制为可要可不要，你听着好听就加上。

2022-02-21 14:01 UTC, SlimeSB commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "subtitles.electrodynamics.hydroelectricgenerator" : "水轮旋转",
水轮：旋转

2022-02-21 14:19 UTC, SlimeSB commented
你看下其他意见，长句子和文本格式我合并之后在库里弄吧。

2022-02-21 15:11 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.wirelogisticstin" : "锡物流导线",
啊这，我的眼睛多半是有点问题了

2022-02-21 15:14 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.rodtitaniumcarbide" : "碳化钛棒",
emmmmm，在电动力学里这几个 rod 的用法好像只是副手手持后当作弹药装载到轨道炮里发射出去，所以它到底算是一个工具还是一种原料？

2022-02-21 15:15 UTC, SlimeSB commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.rodtitaniumcarbide" : "碳化钛棒",
那就棒吧，没有问题。参考热熔胶棒。

2022-02-21 15:18 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.quarry.power" : "升级需要电能以运行",
找了一下电动力学的库，目前没有引用这句的代码，先保留不译吧 (

2022-02-21 15:21 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.upgradeadvancedspeed" : "高级效率升级",
Okay

2022-02-21 15:26 UTC, SlimeSB commented
你把中间hidden的打开，很多折叠了

2022-02-22 05:24 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.concretetile" : "加固混凝土瓦块",
这个就不改了罢（

2022-02-22 05:24 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "container.electricfurnace2" : "高级熔炼工厂",
那就按方块的翻译来了

2022-02-22 05:44 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.info.capacityupgradevoltage" : "将机器最大通电电压升高到 %s",
查了一下，cyl那样的是对的。但奇怪的是 %s 里面包含了 “x”，所以可能得把“倍”去掉

2022-02-22 07:38 UTC, SlimeSB commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "jei.info.item.upgradeitemoutput" : "自动弹出升级是自动化狂热者最好的伙伴之一。应用该升级的方块会向用户所指定方向的临近方块弹出物品。该升级提供两种模式：默认模式与智能模式。默认模式下，该升级会尝试提取本机器中所有的输出槽（包括输出槽2），并将被提取的物品根据用户所指定的方向顺序，向相应方向弹出。在方向指定中重复指定同一个方向没有意义。智能模式下，每个输出
向你确认一下，biproduct是否为副产品槽。

2022-02-22 07:42 UTC, SlimeSB commented
差不多了，挂个一天没问题提出就merge

2022-02-22 10:19 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "jei.info.item.upgradeitemoutput" : "自动弹出升级是自动化狂热者最好的伙伴之一。应用该升级的方块会向用户所指定方向的临近方块弹出物品。该升级提供两种模式：默认模式与智能模式。默认模式下，该升级会尝试提取本机器中所有的输出槽（包括输出槽2），并将被提取的物品根据用户所指定的方向顺序，向相应方向弹出。在方向指定中重复指定同一个方向没有意义。智能模式下，每个输出
输出槽2应该没问题）

2022-02-22 14:51 UTC, DawnDre-AM commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.ingothslasteel" : "高强度钢锭",
请问HSLA为什么不采用高强度低合金钢？

2022-02-22 14:56 UTC, DawnDre-AM commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.upgradeiteminput" : "自动抽取升级",
为什么injector对应抽取?注入是否更符合原意

2022-02-22 15:05 UTC, DawnDre-AM commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.slag" : "金属矿渣",
在游戏中非金属矿物似乎也能加工出slag，因此是否改为矿渣更为合适？

2022-02-22 15:09 UTC, SlimeSB commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.upgradeiteminput" : "自动抽取升级",
这里是机器的动作，机器主动的pull物品或者流体，注入一词则是外界主动给机器注入。

2022-02-22 15:23 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.slag" : "金属矿渣",
尊重原文

2022-02-22 17:16 UTC, mamaruo commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.wiremilldouble" : "双联线材轧机组",
想知道这里采用不与其他类似方块类似的译法，加了个“组”的用意。

2022-02-22 17:21 UTC, mamaruo commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.concretetile" : "加固混凝土瓦块",
我也想到原版的深板岩瓦（Deepslate Tiles）了

2022-02-22 17:24 UTC, mamaruo commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.motorcomplex" : "精密电动机",
complex 在后面怎么译成形容词精密了
盲猜“电机复合体”，肯定有更好的译法，也要看游戏内性能和纹理表现

2022-02-22 17:29 UTC, mamaruo commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "container.chargerlv" : "120 V 充电器",
```
"container.chargerlv" : "120V Charger",
"container.chargermv" : "240V Charger",
"container.chargerhv" : "480V Charger",
```
参考该[回复](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1563#discussion_r811929684)，并且上面有同样的译名却没加空格

2022-02-22 17:32 UTC, mamaruo commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.coolantresavoir" : "冷却液储存器",
```suggestion
  "block.electrodynamics.coolantresavoir" : "冷却液储罐",
```

2022-02-22 17:44 UTC, mamaruo commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.multimeterblock" : "万用表",
`Multimeter Block`
万用表方块？万用表盒？好别扭

2022-02-22 17:52 UTC, mamaruo commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "jei.info.fluid.combustionchamberfuel" : "燃烧室燃料：\n    生产：%2$s kW\n    消耗：%1$s mB."
```suggestion
  "jei.info.fluid.combustionchamberfuel" : "燃烧室燃料：\n    发电：%2$s kW\n    消耗：%1$s mB."
```

2022-02-22 17:52 UTC, mamaruo commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "jei.info.block.tank" : "最多能储存%s mB的任何流体。注意：流体储罐被破坏时流体也会消失！",
```suggestion
  "jei.info.block.tank" : "最多能储存%smB的任何流体。注意：流体储罐被破坏时流体也会消失！",
```
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1563#discussion_r811929684

2022-02-22 17:55 UTC, mamaruo commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "subtitles.electrodynamics.hydroelectricgenerator" : "水轮旋转",
`Hydroelectric generator spins`
```suggestion
  "subtitles.electrodynamics.hydroelectricgenerator" : "水力发电机：旋转",
```

2022-02-22 18:01 UTC, mamaruo commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "subtitles.electrodynamics.seismicscanner" : "地质扫描仪：运行",
`Seismic Scanner pings`
```suggestion
  "subtitles.electrodynamics.seismicscanner" : "地质扫描仪：轰鸣",
```

总觉得轰鸣这个词声音太大了，不符合 ping 的声音大小（[YouTube](https://www.youtube.com/watch?v=JA0cH_vRABg)：What Does Engine Pinging / Detonation Sound Like）。

2022-02-22 18:06 UTC, mamaruo commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "subtitles.electrodynamics.mineralcrusher" : "矿石粉碎机：运行",
```suggestion
  "subtitles.electrodynamics.mineralcrusher" : "矿石粉碎机：粉碎",
```

2022-02-22 18:14 UTC, mamaruo commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "subtitles.electrodynamics.windmill" : "扇叶摩擦空气",
`Air hitting windmill`
风力发电机：？？？
不会

2022-02-22 18:14 UTC, mamaruo commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "subtitles.electrodynamics.electricpump" : "电动泵：运行",
```suggestion
  "subtitles.electrodynamics.electricpump" : "电动泵：抽吸",
```

2022-02-22 22:24 UTC, SlimeSB commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.multimeterblock" : "万用表",
无需更改

2022-02-23 00:50 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.coolantresavoir" : "冷却液储存器",
这个我其实有点疑问，resavoir到底是啥（我是按照reservoir翻的）

2022-02-23 00:51 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.seismicscanner" : "地质扫描仪",
这个东西是你往里面放一个方块，他就能扫描相同的方块并在地图上标出。（反正不是地动仪什么的😂）

2022-02-23 00:52 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.wiremilldouble" : "双联线材轧机组",
这个删了应该没问题

2022-02-23 00:54 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "subtitles.electrodynamics.seismicscanner" : "地质扫描仪：运行",
“叮叮”或者“嘀嘀”怎么样

2022-02-23 00:55 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "subtitles.electrodynamics.windmill" : "扇叶摩擦空气",
不会了是吧😂所以一开始我就图省事统一译成运行了（

2022-02-23 01:15 UTC, EnderAvaritia commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.seismicscanner" : "地质扫描仪",
我想起来这个 [地震振动器/可控振源](https://www.mcmod.cn/item/40214.html) 东西。

2022-02-23 03:34 UTC, mamaruo commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.coolantresavoir" : "冷却液储存器",
我认为是 reservoir

2022-02-23 03:38 UTC, mamaruo commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "subtitles.electrodynamics.combustionchamber" : "燃烧室：运行",
```suggestion
  "subtitles.electrodynamics.combustionchamber" : "燃烧室：开始燃烧",
```

2022-02-23 04:06 UTC, mamaruo commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "subtitles.electrodynamics.windmill" : "扇叶摩擦空气",
```suggestion
  "subtitles.electrodynamics.windmill" : "空气：摩擦扇叶",
```

2022-02-23 04:24 UTC, SlimeSB commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "subtitles.electrodynamics.windmill" : "扇叶摩擦空气",
关于“声源：声音”的格式
在原版字幕文件中，有诸如“脚步声”、“获得经验”、“怪异的噪声”等未写出声源的文本。主要还是根据原文来决定的。
比如获得经验，严格来说是“玩家：获得经验”或者“经验：获得”。在这里并没有这么译，主要还是声源的不明确。

这里其实在原文中就没有明确写出。
所以我当时看见这个本来是准备改的，后来觉得没问题。

2022-02-23 05:25 UTC, mamaruo requested changes

2022-02-23 05:59 UTC, DawnDre-AM commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.motorcomplex" : "精密电动机",
目前来看该方块并未实装指游戏中...最新的electrodynamics1.18.1版本为0.5.9，en_us总条目495，而此项目拥有超500+条目，推测为作者下一个版本的更新内容（因为是直接从作者git库里拉出来的

2022-02-23 06:01 UTC, DawnDre-AM commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.seismicscanner" : "地质扫描仪",
是一种类似方块探测器的仪器，和地震并无关系（我一开始也错翻成地震了

2022-02-23 06:04 UTC, DawnDre-AM commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.multimeterblock" : "万用表",
该方块为万用表的方块形式，放置接入电路显示电压电流等信息..

2022-02-23 06:05 UTC, DawnDre-AM commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "subtitles.electrodynamics.seismicscanner" : "地质扫描仪：运行",
或者和研磨，粉碎等统一成扫描？

2022-02-23 06:07 UTC, DawnDre-AM commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "subtitles.electrodynamics.windmill" : "扇叶摩擦空气",
但是windmill作为声音来源有明确标出，所以这里是把windmill改成了扇叶吗

2022-02-23 06:11 UTC, DawnDre-AM commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.itemwire.info.insulated" : "电压≤240.0V时不发生触电",
```suggestion
  "tooltip.itemwire.info.insulated" : "电压≤240.0V时不发生触电",
```
不发生和不会，上下不一致

2022-02-23 06:28 UTC, DawnDre-AM commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.creativepowersource.joke" : "\"UNLIMITEDPOWER!\"-希夫·帕尔帕廷",
```suggestion
  "tooltip.creativepowersource.joke" : "\"无尽能源！\"-星际迷航中的巴克·罗杰斯",
```
 原文为"\"Unlimited Power\" - Buck Rogers from Star Trek",还是说另有典故？

2022-02-23 06:28 UTC, DawnDre-AM commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "death.attack.accelerated_bolt" : "%1$s被%2$s的箭矢洞穿了",
考虑由动力轨道炮也会造成该类死亡提示，箭矢是否为额外添加？

2022-02-23 06:28 UTC, DawnDre-AM commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "fluid.electrodynamics.sulfateiron" : "硫酸铁",
事实上工业中直接溶解铁矿的话获得的是硫酸亚铁
如果考虑到原文的话，那么上面的 vanadium oxide 被翻译成了实际的五氧化二钒而不是字面的氧化钒

2022-02-23 06:28 UTC, DawnDre-AM commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "subtitles.electrodynamics.combustionchamber" : "燃烧室：运行",
机器在运作中会一直发出声音字幕

2022-02-23 06:28 UTC, DawnDre-AM commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "subtitles.electrodynamics.ceramicplatebreaking" : "陶瓷板：破坏",
```suggestion
  "subtitles.electrodynamics.ceramicplatebreaking" : "陶瓷板：破碎",
```
收到大量伤害时，复合装甲胸甲的陶瓷板会吸收一部分伤害并破碎

2022-02-23 06:28 UTC, DawnDre-AM commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "subtitles.electrodynamics.rodhittingground" : "轨道炮弹丸：击中地面",
炮弹丸有些意义不明

2022-02-23 06:28 UTC, DawnDre-AM commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.nightvisiongoggles" : "夜视护目镜",
```suggestion
  "item.electrodynamics.nightvisiongoggles" : "夜视镜",
```
事实上“夜视镜”已经包涵了护目镜的功能，因此应该没必要多加护目
此外夜视镜的翻译就是night vision goggles

2022-02-23 06:38 UTC, DawnDre-AM requested changes

2022-02-23 06:38 UTC, DawnDre-AM commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.electricfurnacedouble" : "双联电炉",
```suggestion
  "block.electrodynamics.electricfurnacedouble" : "冶炼厂",
```
我先说我的理由
首先.1.16.5的译者采用了电炉-冶炼厂-高级冶炼厂的翻译
我认为主要是受container词条的影响
  "container.electricfurnace0" : "Electric Furnace",
  "container.electricfurnace1" : "Smelting Factory",
  "container.electricfurnace2" : "Advanced Smelting Factory",
此外，实际的机器在升级后速度并未明显提升，只是可以同时运行2/3个烧炼进程，因此n联电炉似乎也可以
不过我还是支持作者原文的工厂
  "container.electricarcfurnace0" : "Electric Arc Furnace",
  "container.electricarcfurnace1" : "Blasting Factory",
  "container.electricarcfurnace2" : "Advanced Blasting Factory",
在1.18.1新更新的电弧炉词条中也是和电炉一样采用了电弧炉-爆破厂-高级爆破厂的称呼

2022-02-23 08:25 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "subtitles.electrodynamics.kineticrailgun.noammo" : "动能轨道炮：未就绪",
这个我觉得得骂一骂原文，实际上有弹药但无电力/未冷却时也会发出这个声音，所以我翻成了未就绪😂

2022-02-23 08:27 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.creativepowersource.joke" : "\"UNLIMITEDPOWER!\"-希夫·帕尔帕廷",
先去查查这个梗到底来源于哪再说…另外不排除这是一种外文版的“指虎为刀”

2022-02-23 08:27 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "death.attack.accelerated_bolt" : "%1$s被%2$s的箭矢洞穿了",
感觉可以纠结一下

2022-02-23 08:28 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "subtitles.electrodynamics.rodhittingground" : "轨道炮弹丸：击中地面",
轨道炮 弹丸

2022-02-23 08:28 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.nightvisiongoggles" : "夜视护目镜",
这个我觉得可改可不改

2022-02-23 08:30 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.electricfurnacedouble" : "双联电炉",
我觉得尊重block name没有毛病，上面也讨论过一波了

2022-02-23 08:57 UTC, mamaruo commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "subtitles.electrodynamics.kineticrailgun.noammo" : "动能轨道炮：未就绪",
那么就OK，不要resolve本条，以后方便查

2022-02-23 09:33 UTC, mamaruo commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "item.electrodynamics.ingothslasteel" : "高强度钢锭",
[术语在线](https://www.termonline.cn/word/417192/1#s1)：高强度低合金钢
更早审定的为[低合金高强度钢](https://www.termonline.cn/word/271783/1#s1)。

2022-02-23 12:01 UTC, EnderAvaritia commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.creativepowersource.joke" : "\"UNLIMITEDPOWER!\"-希夫·帕尔帕廷",
感觉星际迷航中的这几个字有点小出戏。

2022-02-23 16:17 UTC, mamaruo commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.creativepowersource.joke" : "\"UNLIMITEDPOWER!\"-希夫·帕尔帕廷",
[“UNLIMITED POWER!” - YouTube](https://www.youtube.com/watch?v=SWwFogRQVnk)

2022-02-24 02:27 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "subtitles.electrodynamics.ceramicplatebreaking" : "陶瓷板：破坏",
Okay

2022-02-24 02:53 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.coolantresavoir" : "冷却液储存器",
翻译成储存器主要想和文件中的其他“储罐”区分一下，毕竟原文也不一致（

2022-02-24 02:54 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.motorcomplex" : "精密电动机",
这一行先空着吧

2022-02-24 10:06 UTC, mamaruo commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.coolantresavoir" : "冷却液储存器",
那行，我没考虑这一层。
另一个选择：蓄水库（来自 Ender IO）

2022-02-24 16:17 UTC, mamaruo commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "subtitles.electrodynamics.seismicscanner" : "地质扫描仪：运行",
[声音文件](https://github.com/aurilisdev/Electrodynamics/blob/1.18.1/src/main/resources/assets/electrodynamics/sounds/seismicscanner.ogg)，的确不是“轰鸣”。偏向尊重原文译法。

```suggestion
  "subtitles.electrodynamics.seismicscanner" : "地质扫描仪：叮叮",
```

2022-02-24 16:31 UTC, mamaruo commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "death.attack.accelerated_bolt" : "%1$s被%2$s的箭矢洞穿了",
```suggestion
  "death.attack.accelerated_bolt" : "%1$s被%2$s打穿了",
```

2022-02-24 16:32 UTC, mamaruo commented
没剩几个了，完工在望。请求 re-review。

2022-02-24 22:15 UTC, n0099 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "subtitles.electrodynamics.rodhittingground" : "轨道炮弹丸：击中地面",
轨道炮炮弹

2022-02-24 22:23 UTC, n0099 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.electricfurnacedouble" : "双联电炉",
建议n联

2022-02-25 10:06 UTC, SlimeSB approved these changes

2022-02-25 12:03 UTC, TartaricAcid approved these changes
没啥大问题了

2022-02-25 17:42 UTC, mamaruo approved these changes

2022-02-25 23:03 UTC, Cyl18 requested changes

2022-02-25 23:03 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "block.electrodynamics.deepslateorethorianite" : "深层方钍矿石",
```suggestion
  "block.electrodynamics.deepslateorethorianite" : "深层方钍石矿石",
```
和上方 `方钍石矿石` 统一

2022-02-25 23:03 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "container.chargerhv" : "480V 充电器",
这里和 L270-L272 不统一

2022-02-25 23:05 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.seismicscanner.currentore" : "当前矿石:%s",
```suggestion
  "tooltip.seismicscanner.currentore" : "当前矿石：%s",
```

2022-02-25 23:06 UTC, Cyl18 commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "jei.info.item.railgunplasma" : "伤害：\n    初始：40\n    1秒后:20",
```suggestion
  "jei.info.item.railgunplasma" : "伤害：\n    初始：40\n    1秒后：20",
```

2022-02-25 23:09 UTC, Cyl18 commented
![image](https://user-images.githubusercontent.com/14993992/155815061-621fa087-3110-43ec-981d-12a2b2fa2946.png)
空格问题还是没太统一

2022-02-26 02:26 UTC, MikhailTapio commented on projects/1.18/assets/electrodynamics/electrodynamics/lang/zh_cn.json
> +  "tooltip.itemwire.info.ceramic" : "电压≤480.0V时不会触电",
> ![image](https://user-images.githubusercontent.com/14993992/155815061-621fa087-3110-43ec-981d-12a2b2fa2946.png) 空格问题还是没太统一

按英文原文的空格来的

2022-02-26 13:24 UTC, mamaruo approved these changes

2022-02-27 02:43 UTC, n0099 approved these changes

2022-02-27 09:50 UTC, merged