[R] Nuclear Science
CFPAOrg/Minecraft-Mod-Language-Package pull request #1563
Opened 2022-02-18 10:25 UTC by MikhailTapio

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-02-18 12:21 UTC, n0099 requested changes

2022-02-18 12:21 UTC, n0099 commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "item.nuclearscience.lifthf4uf4" : "LiF-ThF4-UF4盐混合物",
这是化合物吗，如果是数字应该用下标的₄

2022-02-18 12:21 UTC, n0099 commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "item.nuclearscience.cellantimatterverylarge" : "反物质单元 12 g",
```suggestion
  "item.nuclearscience.cellantimattersmall" : "反物质单元 500mg",
  "item.nuclearscience.cellantimatterlarge" : "反物质单元 4g",
  "item.nuclearscience.cellantimatterverylarge" : "反物质单元 12g",
```

2022-02-18 12:21 UTC, n0099 commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "jei.guilabel.reactorcore.info.temp" : "温度范围：0 °C 至 1400 °C",
```suggestion
  "jei.guilabel.reactorcore.info.temp" : "温度范围：0 ℃ 至 1400 ℃",
```

2022-02-18 12:21 UTC, n0099 commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "jei.gui.gascentrifuge.info.power_usage" : "240 V 3 kW",
为什么一会是V一会是伏，下面也有这样的不一致

2022-02-18 12:21 UTC, n0099 commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "jei.gui.particalaccelerator.antimatter.info.power" : "电量：100% 速度 < 100%",
```suggestion
  "jei.gui.particalaccelerator.antimatter.info.power" : "电量：100% 速度 <100%",
```

2022-02-18 12:21 UTC, n0099 commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "jei.info.block.radioisotopegenerator" : "规格：铀-235 @ 一组:\n    最大电压：120V\n    最大功率：12.8 kW\n    最大电流：106.66A\n\n规格：铀-238 @ 一组\n    最大电压：120V\n    最大功率：6.4 kW\n    最大电流：53.33A\n是否已经厌倦到处都是的铀-238？与其去捣腾
```suggestion
  "jei.info.block.radioisotopegenerator" : "规格：铀-235 @ 一组:\n    最大电压：120 V\n    最大功率：12.8 kW\n    最大电流：106.66 A\n\n规格：铀-238 @ 一组\n    最大电压：120 V\n    最大功率：6.4 kW\n    最大电流：53.33 A\n是否已经厌倦到处都是的铀-238？与其去捣腾那危险的裂变反应堆，不如试着用更直接的能量转换方式。添加的颗粒越多，产能越多！",
```

2022-02-18 12:34 UTC, MikhailTapio commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "jei.gui.gascentrifuge.info.power_usage" : "240 V 3 kW",
> 为什么一会是V一会是伏，下面也有这样的不一致

这得问原文，一会是 V 一会是 Volts，不过我的倾向也是统一用缩写

2022-02-18 12:34 UTC, Cyl18 commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "item.nuclearscience.lifthf4uf4" : "LiF-ThF4-UF4盐混合物",
就GT来说 都是用普通数字 好搜索

2022-02-18 12:58 UTC, Cyl18 requested changes

2022-02-18 12:58 UTC, Cyl18 commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "item.nuclearscience.lifthf4uf4" : "LiF-ThF₄-UF₄盐混合物",
参照英文原文 以及易于搜索 我认为使用数字4更好

2022-02-18 13:10 UTC, n0099 commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "item.nuclearscience.lifthf4uf4" : "LiF-ThF₄-UF₄盐混合物",
随便

2022-02-19 13:02 UTC, mamaruo commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "item.nuclearscience.frequencycard" : "频率卡",
[Wikipedia](https://en.wikipedia.org/wiki/Radio-frequency_identification)（相关？）

2022-02-19 13:37 UTC, mamaruo requested changes

2022-02-19 13:37 UTC, mamaruo commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "item.nuclearscience.polonium210chunk" : "钋-210厚块",
据 <https://dict.mcmod.cn/>，检索到 68 个碎块和 0 个厚块。或许应该结合材质等游戏信息考量。

2022-02-19 13:37 UTC, mamaruo commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "death.attack.plasma" : "%s被电离了",
```suggestion
  "death.attack.plasma" : "%s被电离了！",
```
标点漏了。

2022-02-19 13:37 UTC, mamaruo commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "message.geigercounter.text" : "每小时 %s Rad",
```suggestion
  "message.geigercounter.text" : "每小时 %s 拉德",
```
[参考](https://www.termonline.cn/search?k=rad&r=1645276166351)。

2022-02-19 13:37 UTC, mamaruo commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "fluid.nuclearscience.ammonia" : "氨水",
有无可能是液氨？需要游戏信息验证。

2022-02-19 13:37 UTC, mamaruo commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "death.attack.radiation" : "%s刚刚速通了进化论",
```suggestion
  "death.attack.radiation" : "%s刚刚速通了进化论！",
```

2022-02-19 13:37 UTC, mamaruo commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "gui.reactorcore.warning" : "过 热！",
加空格恐怕不是中文正式的强调手段。

2022-02-19 13:37 UTC, mamaruo commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "item.nuclearscience.cellantimattersmall" : "反物质单元 500mg",
数字单位间留空格，下同

2022-02-19 13:37 UTC, mamaruo commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "item.nuclearscience.lifthf4uf4" : "LiF-ThF4-UF4盐混合物",
中英、数字中文间空格？下同

2022-02-19 14:04 UTC, n0099 commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "gui.reactorcore.warning" : "过 热！",
打 字 带 空 格

2022-02-19 14:33 UTC, MikhailTapio commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "item.nuclearscience.cellantimattersmall" : "反物质单元 500mg",
草，本来是有空格的，上面刚改回去。
你们(&& @n0099  )可能得再商量一下？当然我偏向于加空格

2022-02-19 14:35 UTC, MikhailTapio commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "death.attack.plasma" : "%s被电离了",
原版的死亡信息好像都是不加标点的...还是以英文原文为准？

2022-02-19 14:37 UTC, n0099 commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "item.nuclearscience.cellantimattersmall" : "反物质单元 500mg",
您也想加那就加吧，可以revert

2022-02-19 14:40 UTC, MikhailTapio commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "message.geigercounter.text" : "每小时 %s Rad",
我在其他地方使用的单位均为英文缩写，所以这个地方我觉得还是该用 Rad，不过有点不太好就是数学领域也有一个意义完全不同的 Rad 单位。

2022-02-19 14:41 UTC, n0099 commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "death.attack.plasma" : "%s被电离了",
以英文原文为准

2022-02-19 14:42 UTC, n0099 commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "message.geigercounter.text" : "每小时 %s Rad",
就是为了消歧义用中文

2022-02-19 14:46 UTC, mamaruo commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "death.attack.plasma" : "%s被电离了",
> 原版的死亡信息好像都是不加标点的...还是以英文原文为准？

新知识点get，我依然认为遵照原文。

2022-02-19 14:50 UTC, n0099 commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "death.attack.plasma" : "%s被电离了",
我就是说遵照原文啊

2022-02-19 14:50 UTC, MikhailTapio commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "fluid.nuclearscience.ammonia" : "氨水",
![image](https://user-images.githubusercontent.com/81358657/154805907-27ed1dc7-d338-4e60-8ca3-2f75fef9cfb3.png)
应该是氨水

2022-02-19 14:51 UTC, MikhailTapio commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "message.geigercounter.text" : "每小时 %s Rad",
Okay

2022-02-19 14:55 UTC, n0099 commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "fluid.nuclearscience.ammonia" : "氨水",
有无温度

2022-02-19 15:01 UTC, MikhailTapio commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "fluid.nuclearscience.ammonia" : "氨水",
> 有无温度

无，另外右边那个液柱名称用的也是这个键

2022-02-19 15:02 UTC, MikhailTapio commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "gui.reactorcore.warning" : "过 热！",
这个我在前面加了 §l，进游戏试了下没问题

2022-02-19 15:02 UTC, MikhailTapio commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "death.attack.plasma" : "%s被电离了",
Okay

2022-02-19 15:16 UTC, mamaruo commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "fluid.nuclearscience.ammonia" : "氨水",
氨水和液氨都是无色液体，看材质也看不出什么。

2022-02-19 15:32 UTC, mamaruo commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "fluid.nuclearscience.ammonia" : "氨水",
![image](https://user-images.githubusercontent.com/37480168/154807475-f33fe274-fc2a-4b57-93ee-70f1b26aa90c.png)
![image](https://user-images.githubusercontent.com/37480168/154807519-8075f1de-533b-47fe-991a-e36b4ae04aa7.png)
![image](https://user-images.githubusercontent.com/37480168/154807520-1eb8875f-85b3-4369-a1e7-e7ceac9e631c.png)
我多虑了。

2022-02-19 15:36 UTC, mamaruo approved these changes

2022-02-19 15:49 UTC, n0099 approved these changes

2022-02-19 16:32 UTC, n0099 requested changes

2022-02-19 16:32 UTC, n0099 commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "block.nuclearscience.freezeplug" : "防冻塞",
Core plugs, also called freeze plugs or Welch plugs, are used to fill the [sand casting](https://en.wikipedia.org/wiki/Sand_casting) [core](https://en.wikipedia.org/wiki/Core_(manufacturing)) holes found on water-cooled [internal combustion engines](https://en.wikipedia.org/wiki/Internal_combustion_engine).

2022-02-19 16:32 UTC, n0099 commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "block.nuclearscience.moltensaltpipevanadiumsteelceramic" : "钒钢-陶瓷熔融盐管道",
```suggestion
  "block.nuclearscience.moltensaltpipevanadiumsteelceramic" : "锻钢-陶瓷 熔融盐管道",
```

2022-02-20 00:37 UTC, MikhailTapio commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "block.nuclearscience.freezeplug" : "防冻塞",
The slang term "freeze plug" is derived from many years ago in situations where the water in an engine block could freeze (due to plain water being used in winter rather than anti-freeze coolant). The expansion of the water as it froze would cause the core plug to pop out of the engine, leading to the term "freeze plug".

刚刚看了一遍这个，也许可以叫[防冻裂塞](https://www.zhihu.com/question/282908393)？

2022-02-21 18:08 UTC, mamaruo requested changes

2022-02-21 18:08 UTC, mamaruo commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "subtitles.nuclearscience.gascentrifuge" : "气体离心机：运行",
```suggestion
  "subtitles.nuclearscience.gascentrifuge" : "气体离心机：旋转",
```

2022-02-21 18:08 UTC, mamaruo commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "subtitles.nuclearscience.turbine" : "蒸汽涡轮机：运行",
```suggestion
  "subtitles.nuclearscience.turbine" : "蒸汽涡轮机：旋转",
```

2022-02-21 18:08 UTC, mamaruo commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "subtitles.nuclearscience.nuclearboiler" : "核能锅炉：运行",
```suggestion
  "subtitles.nuclearscience.nuclearboiler" : "核能锅炉：沸腾",
```

2022-02-21 18:11 UTC, mamaruo commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "block.nuclearscience.heatexchanger" : "热交换机",
```suggestion
  "block.nuclearscience.heatexchanger" : "热交换器",
```
[术语在线](https://www.termonline.cn/search?k=Steam%20Turbine&r=1645465289053)

2022-02-22 05:16 UTC, MikhailTapio commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "container.radioisotopegenerator" : "放射性同位素温差发电机",
这一条是参考工业2的

2022-02-22 05:19 UTC, mamaruo commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "container.radioisotopegenerator" : "放射性同位素温差发电机",
但 IC2 的原名是全的
![image](https://user-images.githubusercontent.com/37480168/155067847-5ef3651f-db1a-425f-b4bd-c29ba2a68899.png)

2022-02-22 05:34 UTC, mamaruo commented
@SlimeSB 不知现在如何，如果我还是没找到您所说的“客观错误”的话，还请不吝赐教。

2022-02-22 05:46 UTC, TartaricAcid commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "container.radioisotopegenerator" : "放射性同位素温差发电机",
问题不大，反正一个意思，就这样吧

2022-02-22 05:54 UTC, TartaricAcid commented
我觉得没啥问题了

2022-02-22 05:54 UTC, TartaricAcid approved these changes

2022-02-22 06:03 UTC, MikhailTapio commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "container.radioisotopegenerator" : "放射性同位素温差发电机",
Okay

2022-02-22 07:40 UTC, SlimeSB requested changes

2022-02-22 07:40 UTC, SlimeSB commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "jei.gui.gascentrifuge.info.power_usage" : "240 V 3 kW",
"jei.gui.gascentrifuge.info.power_usage" : "240V 30kW",
此行

2022-02-22 08:07 UTC, MikhailTapio commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "jei.gui.gascentrifuge.info.power_usage" : "240 V 3 kW",
😢我的

2022-02-22 08:12 UTC, MikhailTapio commented
应该还有多处没删的空格，但我这边来活了，同志们有时间可以帮改一下嘛（

2022-02-22 08:14 UTC, SlimeSB commented
我晚上弄。不急。

2022-02-22 10:22 UTC, mamaruo commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "jei.gui.gascentrifuge.info.power_usage" : "240 V 3 kW",
> "jei.gui.gascentrifuge.info.power_usage" : "240V 30kW", 此行 @mamaruo ，审核还需更加细心。

我看到的通知是中英、中文数字间的空格不用加，但数字和单位间的？
虽然前两者都不加数字单位间加空格很突兀……

2022-02-22 10:40 UTC, SlimeSB commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "jei.gui.gascentrifuge.info.power_usage" : "240 V 3 kW",
压根不是格式问题，文本都抄错了

2022-02-22 10:40 UTC, SlimeSB commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "jei.gui.gascentrifuge.info.power_usage" : "240 V 3 kW",
压根不是格式问题，文本都抄错了

2022-02-22 11:06 UTC, mamaruo commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "jei.gui.gascentrifuge.info.power_usage" : "240 V 3 kW",
> 压根不是格式问题，文本都抄错了。 此时要是有QQ表情我要发一万个抓狂

我错了……以后一定小心

2022-02-22 13:11 UTC, SlimeSB commented on projects/1.18/assets/nuclearscience/nuclearscience/lang/zh_cn.json
> +  "jei.gui.gascentrifuge.info.power_usage" : "240 V 3 kW",
以原文为准，如：
> 120V Battery
译作：120V电池
> 120 V(Volt) Battery
译作：120 V电池
对于百分号、摄氏度，均不保留。

2022-02-22 13:21 UTC, TartaricAcid commented
没啥问题了吧，我接了

2022-02-22 13:21 UTC, merged

2022-02-22 13:24 UTC, SlimeSB commented
你merge了我也懒得弄了。建议之后审完贴个ready to merge标签，等个一天再合并。我删空格删正爽一看合并了。

2022-02-22 13:25 UTC, TartaricAcid commented
啊，这……我看有人已经发删空格的 commit 了，我就直接 merge 了

2022-02-22 13:44 UTC, MikhailTapio commented
943 特有的急切🤣