[R] GregTechCE
CFPAOrg/Minecraft-Mod-Language-Package pull request #1571
Opened 2022-02-21 12:24 UTC by HiddenCirno

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2022-02-21 13:09 UTC, iouter reviewed
大部分看起来都不错。

2022-02-21 13:09 UTC, iouter commented on projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang
> +material.primitive=primitive
不翻译吗？

2022-02-21 13:09 UTC, iouter commented on projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang
> +gregtech.machine.electric_blast_furnace.name=工业高炉
电力高炉

2022-02-21 13:19 UTC, Cyl18 commented on projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang
> +metaitem.wafer.glowstone.name=萤石掺杂的晶元
貌似是晶圆

2022-02-21 13:22 UTC, Cyl18 commented on projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang
> +gregtech.machine.electric_blast_furnace.name=工业高炉
1.7.10的话是工业高炉

2022-02-21 13:28 UTC, iouter commented on projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang
> +gregtech.machine.electric_blast_furnace.name=工业高炉
我记得gtce里一直是电力高炉？

2022-02-21 14:18 UTC, TartaricAcid requested changes

2022-02-21 14:18 UTC, TartaricAcid commented on projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang
> +cover.bucket.mode.milli_bucket=升/秒
同理，原文为 `mB/s`

2022-02-21 14:18 UTC, TartaricAcid commented on projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang
> +behavior.plunger.description=右击机器以清除 1000升 输出槽中的流体。/n潜行右击机器以清除 1000升 输入槽中的流体。/n输入槽流体清除功能仅限于 GTCE 机器！
`mB` 和`升`的问题

2022-02-21 14:18 UTC, TartaricAcid commented on projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang
> +achievement.smallparts.desc=制作NAND存储器芯片
中英文之间的空格

2022-02-21 14:18 UTC, TartaricAcid commented on projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang
> +gregtech.machine.fluid_tank.fluid=含有 %s 升 %s
同理，`mB` 和`升`的问题

2022-02-21 14:18 UTC, TartaricAcid commented on projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang
> +gregtech.universal.tooltip.amperage_out_till=最大输出电流: §§e%,d
多了一个格式符

2022-02-21 14:18 UTC, TartaricAcid commented on projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang
> +gregtech.universal.tooltip.fluid_storage_capacity=流体储量：%,d 升
同理，`mB` 和`升`的问题

2022-02-21 14:18 UTC, TartaricAcid commented on projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang
> +gregtech.recipe.eu=消耗功率：%,d EU/t(%s)
空格缺失

2022-02-21 14:18 UTC, TartaricAcid commented on projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang
> +gregtech.fluid.click_to_empty=§7 手持流体容器点击流体槽以倒出流体。
为什么加了空格？这是格式符吧

2022-02-21 14:18 UTC, TartaricAcid commented on projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang
> +gregtech.fluid_pipe.throughput=传输速率：§e%d 升/刻
同理，`mB` 和`升`的问题

2022-02-21 14:18 UTC, TartaricAcid commented on projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang
> +gregtech.multiblock.turbine.fuel_amount=燃料量：%s 升（%s）
同理，`mB` 和`升`的问题

2022-02-21 14:18 UTC, TartaricAcid commented on projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang
> +gregtech.command.util.hand.fluid=流体信息：%s %d / %d 升；可输入：%s；可输出：%s
同理，`mB` 和`升`的问题

2022-02-21 14:19 UTC, TartaricAcid commented
辛苦了，总体改动很不错，也很细心，只挑出了一点小毛病，改完后应该就可以入库了

2022-02-22 04:17 UTC, TartaricAcid commented on projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang
> +gregtech.machine.electric_blast_furnace.name=工业高炉
电力高炉吧，我记得 18 年我玩 GTCE 时候就是电力高炉

2022-02-22 05:15 UTC, TartaricAcid approved these changes

2022-02-22 05:18 UTC, merged

2022-02-22 16:55 UTC, n0099 commented on projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang
> +gregtech.fluid.click_to_empty=§7 手持流体容器点击流体槽以倒出流体。
我无脑正则查找替换给中英文加的空格没过滤掉§

2022-02-22 16:55 UTC, n0099 commented on projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang
> +gregtech.recipe.eu=消耗功率：%,d EU/t(%s)
`消耗功率：%,d EU/t （%s）`

2022-02-22 16:56 UTC, n0099 commented on projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang
> +metaitem.food.chum.on.stick.tooltip=Don't forget to try our Chum-balaya
来自gtce自带翻译文件的新增key

2022-02-22 16:56 UTC, n0099 commented on projects/1.12.2/assets/gregtechce/gregtech/lang/zh_cn.lang
> +metaitem.cover.solar.panel.lv.tooltip=LV 太阳能覆盖板
这是贴在机器6个面上的板，不能单独放置为方块