[R] 查了一遍不太合适的翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #1572
Opened 2022-02-22 04:33 UTC by EnderAvaritia

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-02-22 05:17 UTC, mamaruo commented
回退之前尽量了解清楚原本这些更改的缘由。

因为很多翻译确实有修正需要，应对社区质疑回退从长计议是一方面，另一方面也要做好记录，适时把确有必要修改的交给社区决定。由于这些 commit 提交者已多数离开，尽早分析记录原因，不然就真的消失在历史长河里去了。

另外建议只回退影响较大的翻译，如物品名，总是改来改去社区也不会满意的。

2022-02-22 05:42 UTC, TartaricAcid requested changes

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/1UNKNOWN/voidcraft/lang/zh_cn.lang
> +voidcraft.misc.pawn.desc=§4警告：即将爆炸!!!
标点符号没有改动的必要，本来就是全角的

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/1UNKNOWN/voidcraft/lang/zh_cn.lang
> +voidcraft.VadeMecum.recipe.macerator=打粉机配方
草，经典的 `打粉机` `磨粉机` 争论

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/thaumcraft/thaumcraft/lang/zh_cn.lang
> +golem.follow=吾主，我将追随您!
标点符号错误

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +label.rockhounding_chemistry:descr.insulation=绝缘升级
绝热和绝缘？这两词可不一样，`Insulation` 是绝热的意思吧？

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/thaumcraft/thaumcraft/lang/zh_cn.lang
> +item.elemental_shovel.name=后土铲
经典的 `铲` 和 `锹` 问题，还是建议保留成原来翻译，符合原版翻译

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/thaumcraft/thaumcraft/lang/zh_cn.lang
> +research.ARCANEEAR.stage.2=我成功了！ 奥术之耳是一个能够检测附近的音符盒发声的设备。当它检测到既定音符时会发出短的红石脉冲。 <BR>奥术之耳通过依附在不同材料上实现与不同音色的音符盒对应。 <BR>奥术之耳能够依附在任意方块的表面上。<LINE>我也制作了奥术之耳的另一种版本，当它检测到音符时，会切换脉冲的开启和关闭而不是发射脉冲。
空格？

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/thaumcraft/thaumcraft/lang/zh_cn.lang
> +research.BASEALCHEMY.stage.1=坩埚炼金指南 <BR>1） 将坩埚放在热源之上（火，岩浆， 闪耀之光或者其它类似的东西）。 <BR>2） 加入水并等待其沸腾. <BR>3） 加入含有所需源质的配料， 你可以直接丢进坩埚或者用配料右击坩埚的顶面。 <BR>4） 投入触媒。<PAGE>注意事项 <BR>- 空手按住shift右键可以清空坩埚 <BR>- 每次炼金操作都会消耗
很明显应该是熔岩啊

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/thaumcraft/thaumcraft/lang/zh_cn.lang
> +research.DIOPTRA.stage.1=如果能有个仪器来显示周围的灵气分布就好了。等等，似乎这并不难实现！
空格？

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/thaumcraft/thaumcraft/lang/zh_cn.lang
> +research.EldritchCrab.stage.1=邪术爪牙和爪牙头目是最不寻常和不自然的生物。我敢肯定这些生物是邪恶的魔法造物。 <BR>一对强大的爪子使它们在面对交战时变得非常危险，但是要知道他们如何使用这对爪子会让人觉得更可怕。 它们凶猛扑向敌人并企图斩杀掉敌人的头颅。 如果成功了，它们会侵入被害者的身体并控制剩下的驱壳。 它们的腹部看起来像一个戴着头盔的头，使它们在驱壳中伪装的更
空格？

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/thaumcraft/thaumcraft/lang/zh_cn.lang
> +research.FORTRESSMASK.stage.2=我草拟了几个魔法面具的设计用以替代神秘要塞兜鍪最基础的面部护甲。<PAGE>§n揭示之盔§r <BR>通常来说，神秘使需要在防护性与实用性间艰难地做出选择。再也不必如此了。！ <BR>这顶改装后的神秘要塞兜鍪虽然并不具有护目镜的魔力减免功能，但却能够为你提供揭示之护目镜所具有的其他所有功能。 <BR>这顶头盔也能加装其他面具。<PAGE
这个标点有点奇怪

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/thaumcraft/thaumcraft/lang/zh_cn.lang
> +tc.inst=风险：
全角冒号后面就不用加空格了

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/thaumcraft/thaumcraft/lang/zh_cn.lang
> +tc.invtoolarge=容器太大了，仅扫描前100个项目。
`items` 可不是项目的意思

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/thaumic-bases-unofficial/thaumicbases/lang/zh_cn.lang
> +tile.oldgravel.name=古老砂砾
Minecraft 原版为 `沙砾`

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/thaumic-bases-unofficial/thaumicbases/lang/zh_cn.lang
> +research_name.thaumicbases:tbadvmacerator=神秘基础学：高级打粉机
又是经典的 `打粉机` `磨粉机` 问题

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.16/assets/croparia/croparia/lang/zh_cn.json
> +  "item.croparia.seed_crop_hop_graphite": "HOP石墨种子",
空格缺失

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.16/assets/croparia/croparia/lang/zh_cn.json
> +  "item.croparia.fruit_hop_graphite": "HOP石墨果实",
空格缺失

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.16/assets/immersive-engineering/immersiveengineering/lang/zh_cn.json
> +  "item.immersiveengineering.ingot_hop_graphite": "HOP石墨锭",
空格缺失

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.16/assets/mystical-agriculture/mysticalagriculture/lang/zh_cn.json
> +  "crop.mysticalagriculture.hop_graphite": "HOP石墨粉",
空格缺失

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.16/assets/simple-grinder/simplegrinder/lang/zh_cn.json
> +  "itemGroup.simplegrinder": "简易打粉机"
经典的 `打粉机` `磨粉机` 问题

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/1UNKNOWN/voidcraft/lang/zh_cn.lang
> +tile.voidcraft.voidmacerator.name=虚空灌注打粉机
经典的 `打粉机` `磨粉机` 问题

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/1UNKNOWN/voidcraft/lang/zh_cn.lang
> +voidcraft.VadeMecum.docs.desc.voidDusts=虚空粉末是使用虚空打粉机处理矿物的结果。处理原矿可以获得四份对应的虚空粉末，而处理锭或者宝石只能得到一个对应粉末。可以处理成虚空粉末的类型有煤，铁，金，铜，锡，铅，石英，绿宝石，青金石和钻石。但是这些虚空粉末只有金属和钻石可以通过熔炼变成对应的锭或者宝石。这在一定程度上相当于四倍的矿物增产。(即石英，青金石，绿宝石，
经典的 `打粉机` `磨粉机` 问题

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/1UNKNOWN/voidcraft/lang/zh_cn.lang
> +voidcraft.gui.macerator.title=虚空灌注打粉机
经典的 `打粉机` `磨粉机` 问题

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/immersive-engineering/immersiveengineering/lang/zh_cn.lang
> +item.immersiveengineering.material.ingot_hop_graphite.name=HOP石墨锭
空格缺失

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/mystical-agriculture/mysticalagriculture/lang/zh_cn.lang
> +tile.ma.hop_graphite_crop.name=HOP石墨作物
空格缺失

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +tile.rockhounding_chemistry:pipeline_halt.name=堵住的流体管道
流体指代任何可以流动的，比如气体和液体。英文两个词（液体 `liquid`，流体 `fluid`）其实不一样
我看原文是 fluid。

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +tile.rockhounding_chemistry:pipeline_halt.name=堵住的流体管道
如果都改的话，你这漏了一个

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +container.gan_controller=GAN控制器
空格？

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +item.rockhounding_chemistry:silicone_cartridge.name=热熔胶筒
英文原文 `Silicone Cartridge`

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +item.rockhounding_chemistry:misc_items.deposition_insulation.name=绝缘升级
`Insulation` 是绝热的意思吧？

2022-02-22 05:42 UTC, TartaricAcid commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +item.rockhounding_chemistry:alloy_items_deco.shibuichi_nugget.name=朦胧银粒
这个改的好，之前我找过专业人士咨询过，确实是叫朦胧银

2022-02-22 05:48 UTC, SlimeSB commented on projects/1.16/assets/immersive-engineering/immersiveengineering/lang/zh_cn.json
> +  "item.immersiveengineering.ingot_hop_graphite": "HOP石墨锭",
1.16不用空格了

2022-02-22 05:50 UTC, SlimeSB commented on projects/1.12.2/assets/astral-sorcery/astralsorcery/lang/zh_cn.lang
> +item.itemskyresonator.liquid.name=艾克斯共振器
这个改动的时候理由很充足，不过不一定找得到存档了。

2022-02-22 08:04 UTC, EnderAvaritia commented on projects/1.12.2/assets/thaumcraft/thaumcraft/lang/zh_cn.lang
> +item.elemental_shovel.name=后土铲
这个我是想着沿用tc4的翻译。

2022-02-22 08:33 UTC, EnderAvaritia commented on projects/1.12.2/assets/1UNKNOWN/voidcraft/lang/zh_cn.lang
> +voidcraft.VadeMecum.recipe.macerator=打粉机配方
这个，要不还是放出去公投吧？我看到之前的翻译大多数都是打粉机，按之前的翻译，是打粉机的就退了一下，是磨粉机的也没动。

2022-02-22 08:39 UTC, EnderAvaritia commented on projects/1.16/assets/croparia/croparia/lang/zh_cn.json
> +  "item.croparia.seed_crop_hop_graphite": "HOP石墨种子",
我记得1.16之后把那个显示bug修复了，现在还需要加空格吗？

2022-02-22 08:43 UTC, EnderAvaritia commented on projects/1.12.2/assets/astral-sorcery/astralsorcery/lang/zh_cn.lang
> +item.itemskyresonator.liquid.name=艾克斯共振器
> 这个改动的时候理由很充足，不过不一定找得到存档了。

看着是比直接音译舒服多了，但是之前那个翻译用久了，我怕玩家找不到东西。

2022-02-22 08:44 UTC, EnderAvaritia commented on projects/1.16/assets/croparia/croparia/lang/zh_cn.json
> +  "item.croparia.seed_crop_hop_graphite": "HOP石墨种子",
> 空格缺失

我记得1.16之后把那个显示bug修复了，现在还需要加空格吗？

2022-02-22 08:44 UTC, EnderAvaritia commented on projects/1.12.2/assets/thaumcraft/thaumcraft/lang/zh_cn.lang
> +item.elemental_shovel.name=后土铲
> 经典的 `铲` 和 `锹` 问题，还是建议保留成原来翻译，符合原版翻译

这个我是想着沿用tc4的翻译。

2022-02-22 08:45 UTC, EnderAvaritia commented on projects/1.12.2/assets/1UNKNOWN/voidcraft/lang/zh_cn.lang
> +voidcraft.VadeMecum.recipe.macerator=打粉机配方
> 草，经典的 `打粉机` `磨粉机` 争论

这个，要不还是放出去公投吧？我看到之前的翻译大多数都是打粉机，按之前的翻译，是打粉机的就退了一下，是磨粉机的也没动。

2022-02-22 09:35 UTC, yuesha-yc commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +label.rockhounding_chemistry:descr.insulation=绝缘升级
这两个意思都有，得看具体游戏里的作用

2022-02-22 09:42 UTC, EnderAvaritia commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +item.rockhounding_chemistry:misc_items.deposition_insulation.name=绝缘升级
> `Insulation` 是绝热的意思吧？

百科上给的内容里面都是绝缘升级，我看着也像是绝热，但是那资料有一年没动了。

2022-02-22 09:58 UTC, EnderAvaritia commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +tile.rockhounding_chemistry:pipeline_halt.name=堵住的流体管道
> 如果都改的话，你这漏了一个

从游戏内容来看，的确应该是液体管道，但是相关的文字教程上面是流体。
查了一下，同一类管道翻译不同居然还是第一次翻译的时候发生的……我不知道怎么办了。

2022-02-22 10:34 UTC, TartaricAcid commented on projects/1.12.2/assets/astral-sorcery/astralsorcery/lang/zh_cn.lang
> +item.itemskyresonator.liquid.name=艾克斯共振器
这个翻译之前和 @yuanjie000 讨论过了，`液华共振器` 的翻译比音译舒服多了，我赞同更改

2022-02-22 10:35 UTC, TartaricAcid commented on projects/1.12.2/assets/astral-sorcery/astralsorcery/lang/zh_cn.lang
> +item.itemskyresonator.upgrade.structure.name=多米刻
同理，这些建议保留原翻译，改过音译反而不好

2022-02-22 10:36 UTC, Cyl18 commented on projects/1.12.2/assets/1UNKNOWN/voidcraft/lang/zh_cn.lang
> +voidcraft.VadeMecum.recipe.macerator=打粉机配方
但是得看是 IC2 的“打粉机”还是其它 mod

2022-02-22 10:50 UTC, baka-gourd commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +container.gan_controller=GAN控制器
不可重回缩写，具体要求是国家要求自己去找。折中方案是前面加[GAN]

2022-02-22 11:06 UTC, baka-gourd commented
[规范](http://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=4F2D9ACF302B1EAE813590EF8DB2A101)
看看你改回去违反了多少

2022-02-22 11:10 UTC, TartaricAcid commented on projects/1.12.2/assets/1UNKNOWN/voidcraft/lang/zh_cn.lang
> +voidcraft.VadeMecum.recipe.macerator=打粉机配方
可有可无的翻译就不要修改了吧，保持原样就行

2022-02-22 11:11 UTC, TartaricAcid commented on projects/1.12.2/assets/thaumcraft/thaumcraft/lang/zh_cn.lang
> +item.elemental_shovel.name=后土铲
可有可无的翻译就不要修改了吧，保持原样就行

2022-02-22 11:12 UTC, TartaricAcid commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +tile.rockhounding_chemistry:pipeline_halt.name=堵住的流体管道
那就恢复成原翻译吧，已有无大问题的翻译，尽量不改动了

2022-02-22 11:13 UTC, TartaricAcid commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +container.gan_controller=GAN控制器
我赞成保留原翻译

2022-02-22 11:13 UTC, TartaricAcid commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +item.rockhounding_chemistry:misc_items.deposition_insulation.name=绝缘升级
那就八成百科错了，改成原翻译吧

2022-02-22 11:15 UTC, TartaricAcid commented
原来翻译也有国标，挺好的，我去看看

2022-02-22 11:35 UTC, baka-gourd commented
> 原来翻译也有国标，挺好的，我去看看

改回去就一堆违反的。
不然闲着没事就改缩写刷业绩呢。
还有和原版统一。

2022-02-22 11:59 UTC, EnderAvaritia commented on projects/1.12.2/assets/astral-sorcery/astralsorcery/lang/zh_cn.lang
> +item.itemskyresonator.upgrade.structure.name=多米刻
> 同理，这些建议保留原翻译，改回音译反而不好

一个比较蛋疼的事情，我改回去的翻译是用了有较长时间的（大概有几年了），而被改动的那些翻译，最久的应该是去年10月开始用的。

2022-02-22 12:12 UTC, yuanjie000 commented
关于星辉的相关翻译，我已经在修了，目前只完成基础条目，剩下手册部分，你们先继续，我之后直接覆盖吧。

2022-02-22 12:27 UTC, EnderAvaritia commented
> > 原来翻译也有国标，挺好的，我去看看
> 
> 改回去就一堆违反的。 不然闲着没事就改缩写刷业绩呢。 还有和原版统一。

我倒是好奇这些东西改它干嘛，闲的没事刷业绩吗？和原版统一那个确实是我的问题，没注意版本更新不少译名变化了。
这些翻译毕竟不是要求标准翻译的东西，也没有谁会去纠结翻译是不是正确然后给你打个分，告诉你不及格，重修。还是得玩家用的舒服。
保留之前的翻译不动，也就不合标准，但这本身也不是什么规范性文件，大家看着舒服就行。按国标改，看着是舒服了，你还得看修改各个教程的成本，老玩家找不到东西，新玩家问问题两边都听不懂，那翻译这个是为了啥？

2022-02-22 12:27 UTC, LasmGratel requested changes
一些改动是好的，一些改动需要与其他属性统一。

2022-02-22 12:27 UTC, LasmGratel commented on projects/1.12.2/assets/1UNKNOWN/voidcraft/lang/zh_cn.lang
> +voidcraft.VadeMecum.progression.desc.dreams.pg1=这将是我给你的最后一个任务。这项任务的好处是相当大的。虚空侵蚀将不再减少您的生命，而是会增加它。现在的任务是什么？ 打败夏。
这里的区别是什么？

2022-02-22 12:27 UTC, LasmGratel commented on projects/1.12.2/assets/1UNKNOWN/voidcraft/lang/zh_cn.lang
> +voidcraft.gui.gen.title=虚空能发电机
`achievement.generator.desc` `voidcraft.VadeMecum.docs.desc.voidicAnchor.pg2` `voidcraft.VadeMecum.docs.desc.voidicCable.pg1` `voidcraft.VadeMecum.docs.desc.voidicCharger.pg2` 中使用的都是“虚空能发电机”，所以此项修改OK的

2022-02-22 12:27 UTC, LasmGratel commented on projects/1.12.2/assets/aquaculture/aquaculture/lang/zh_cn.lang
> +item.Fish.Perch.name=河鲈鱼
两个鲈鱼确实出了错误

2022-02-22 12:27 UTC, LasmGratel commented on projects/1.12.2/assets/immersive-engineering/immersiveengineering/lang/zh_cn.lang
> +item.immersiveengineering.material.ingot_hop_graphite.name=HOP石墨锭
类似 SAG 一样的问题

2022-02-22 12:27 UTC, LasmGratel commented on projects/1.12.2/assets/pams-harvestcraft/harvestcraft/lang/zh_cn.lang
> +item.akutuqitem.name=爱斯基摩冰淇淋
爱斯基摩冰激凌既正确又使用了很久。

2022-02-22 12:27 UTC, LasmGratel commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +tile.rockhounding_chemistry:machines_d.metal_alloyer_tank.name=合金炉罐
不明白为什么之前这里改成“膛”了。

2022-02-22 12:27 UTC, LasmGratel commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +container.gan_controller=GAN 控制器
这里应该不需要改回去，mcmod.cn上用的就叫“空气分馏塔控制器”

2022-02-22 12:27 UTC, LasmGratel commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +container.stirred_tank_top=电化学 CSTR
同理，mcmod上用的已经是“电化学连续搅拌釜反应器”了

2022-02-22 12:27 UTC, LasmGratel commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +jei.rockhounding_chemistry.gasifier_plant.name=气化装置
为什么只有这里改掉了“气化炉”，而气化炉水箱和气化炉燃烧室不改动呢？

2022-02-22 12:27 UTC, LasmGratel commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +jei.rockhounding_chemistry.gan_plant.name=低温蒸馏
已经出现了三种翻译了：GAN，空气分馏，低温蒸馏

2022-02-22 12:27 UTC, LasmGratel commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +item.rockhounding_chemistry:filter_items.base.name=基础沥滤升级
“升级支架”也是没谁了...

2022-02-22 12:27 UTC, LasmGratel commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +fluid.salt_brine=饱和盐水
为什么上面用“低密度”这里又用“饱和”？

2022-02-22 12:27 UTC, LasmGratel commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +tile.rockhounding_chemistry:fluid.refined_air.name=精制空气
精制是什么鬼...

2022-02-22 12:27 UTC, LasmGratel commented on projects/1.12.2/assets/thermal-expansion/thermalexpansion/lang/zh_cn.lang
> +item.thermalexpansion.augment.machineSecondaryNull.name=副产焚毁舱室
TE中还存在`混合烹饪仓室`和`副产焚毁仓室`，这里不应该改为舱室

2022-02-22 12:27 UTC, LasmGratel commented on projects/1.16/assets/jaopca/jaopca/lang/zh_cn.json
> +  "jaopca.material.hop_graphite": "HOP 石墨",
为什么之前的HOP没有空格而这里有空格？

2022-02-22 12:29 UTC, LasmGratel commented
> 看看你改回去违反了多少

我依稀记得这种问题已经讨论过了...

2022-02-22 12:32 UTC, EnderAvaritia commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +item.rockhounding_chemistry:misc_items.deposition_insulation.name=绝缘升级
> 那就八成百科错了，改成原翻译吧

百科错一般的情况都是用途不够完整或者具体参数错误，翻译都是照着当时的翻译抄的，不至于出错，而且结合文件的变动，当时的翻译确实是绝缘。

2022-02-22 12:33 UTC, EnderAvaritia commented on projects/1.12.2/assets/1UNKNOWN/voidcraft/lang/zh_cn.lang
> +voidcraft.VadeMecum.progression.desc.dreams.pg1=这将是我给你的最后一个任务。这项任务的好处是相当大的。虚空侵蚀将不再减少您的生命，而是会增加它。现在的任务是什么？ 打败夏。
> 这里的区别是什么？

翻译文件多了一个空格。

2022-02-22 12:35 UTC, EnderAvaritia commented on projects/1.12.2/assets/rockhounding-mod-chemistry/rockhounding_chemistry/lang/zh_cn.lang
> +container.gan_controller=GAN 控制器
> 这里应该不需要改回去，mcmod.cn上用的就叫“空气分馏塔控制器”

我是看的词条里面的介绍，因为不排除被改过之后重新导入了一遍。

2022-02-22 12:43 UTC, EnderAvaritia commented on projects/1.12.2/assets/thermal-expansion/thermalexpansion/lang/zh_cn.lang
> +item.thermalexpansion.augment.machineSecondaryNull.name=副产焚毁舱室
> TE中还存在`混合烹饪仓室`和`副产焚毁仓室`，这里不应该改为舱室

这个之前问了一下，舱室可以指代分隔出来的一个小隔间，感觉挺合适的。（不过主要问题还是之前写过的词条，虽然不会有人查到这个位置就是了）

2022-02-22 12:54 UTC, baka-gourd commented
哦，我只是放个国标的，放完我就走了

2022-02-22 13:12 UTC, EnderAvaritia commented
> 哦，我只是放个国标的，放完我就走了

啊这……

2022-02-23 00:50 UTC, Cyl18 commented on projects/1.12.2/assets/thaumcraft/thaumcraft/lang/zh_cn.lang
> +item.elemental_shovel.name=后土铲
> > 经典的 `铲` 和 `锹` 问题，还是建议保留成原来翻译，符合原版翻译
> 
> 这个我是想着沿用tc4的翻译。

可是这个是TC6来着

2022-02-23 01:06 UTC, EnderAvaritia commented on projects/1.12.2/assets/thaumcraft/thaumcraft/lang/zh_cn.lang
> +item.elemental_shovel.name=后土铲
> > > 经典的 `铲` 和 `锹` 问题，还是建议保留成原来翻译，符合原版翻译
> > 
> > 
> > 这个我是想着沿用tc4的翻译。
> 
> 可是这个是TC6来着

都是神秘时代。
这种按书锁阶段的其实还好一点，好歹多多少少还会去看一眼，有的不锁阶段的是真就一点都不知道翻译的变化，经常就是看都不看那种，然后来问找不到东西。

2022-03-14 15:11 UTC, closed without merging