Main chococraft
CFPAOrg/Minecraft-Mod-Language-Package pull request #1578
Opened 2022-02-23 16:48 UTC by ChuijkYahus

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

仅有Dead Pepper、Chocobo、Gysahl Greens三词在FF中能搜到，且Gysahl Greens汉化版本不一，取FF8汉化版本（也许是吧）。
手册因个人认为其原有风格较为随意，所以翻译时未逐字逐句对应，若有需要则更改。

2022-02-23 18:54 UTC, mamaruo requested changes

2022-02-23 18:54 UTC, mamaruo commented on projects/1.16/assets/chococraft/chococraft/lang/zh_cn.json
> +    "item.chococraft.chocobo_egg.tooltip.invalid_egg": "§c不合法的蛋",
```suggestion
    "item.chococraft.chocobo_egg.tooltip.invalid_egg": "§c无效的蛋",
```
`文件名不合法`（

2022-02-23 18:54 UTC, mamaruo commented on projects/1.16/assets/chococraft/chococraft/lang/zh_cn.json
> +    "command.chococraft.chocobo.invalid_set_parameters": "不合法的参数",
```suggestion
    "command.chococraft.chocobo.invalid_set_parameters": "无效的参数",

```

2022-02-23 18:55 UTC, mamaruo commented on projects/1.16/assets/chococraft/chococraft/lang/zh_cn.json
> +    "command.chococraft.chocobo.sprint": "可以冲刺：%s",
疾跑？

2022-02-23 19:15 UTC, mamaruo commented
总体很好，我白天再检查一遍。

2022-02-24 03:20 UTC, TartaricAcid approved these changes
总体没啥问题

2022-02-24 04:08 UTC, ChuijkYahus commented on projects/1.16/assets/chococraft/chococraft/lang/zh_cn.json
> +    "item.chococraft.chocobo_egg.tooltip.invalid_egg": "§c不合法的蛋",
修改完成

2022-02-24 04:08 UTC, ChuijkYahus commented on projects/1.16/assets/chococraft/chococraft/lang/zh_cn.json
> +    "command.chococraft.chocobo.invalid_set_parameters": "不合法的参数",
修改完成

2022-02-24 04:09 UTC, ChuijkYahus commented on projects/1.16/assets/chococraft/chococraft/lang/zh_cn.json
> +    "command.chococraft.chocobo.sprint": "可以冲刺：%s",
改掉了，sprint翻译为疾跑更好

2022-02-24 04:53 UTC, mamaruo commented on projects/1.16/assets/chococraft/chococraft/lang/zh_cn.json
> +    "chococraft.entity_chocobo.heal_fail": "§c生命值全恢复",
键值是`heal_fail`，但文本？

2022-02-24 04:56 UTC, ChuijkYahus commented on projects/1.16/assets/chococraft/chococraft/lang/zh_cn.json
> +    "chococraft.entity_chocobo.heal_fail": "§c生命值全恢复",
英文同键值下也是生命值全恢复的意思
已在游戏内确认过，确实是这个英文文本

2022-02-24 05:06 UTC, mamaruo approved these changes
陆行鸟手册的翻译是个亮点。

明天 13 点前没有新 review 就 merge。

2022-02-24 22:28 UTC, n0099 commented on projects/1.16/assets/chococraft/chococraft/lang/zh_cn.json
> +    "chococraft.entity_chocobo.heal_fail": "§c生命值全恢复",
建议 恢复至满生命值

2022-02-25 03:52 UTC, ChuijkYahus commented on projects/1.16/assets/chococraft/chococraft/lang/zh_cn.json
> +    "chococraft.entity_chocobo.heal_fail": "§c生命值全恢复",
@n0099 ok

2022-02-25 10:03 UTC, merged