[R] Fairy Lights 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1584
Opened 2022-02-25 15:46 UTC by ChuijkYahus

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

没有midi设备导致部分内容只能通过介绍视频和源码来填写

2022-02-25 16:40 UTC, MikhailTapio commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "commands.jingler.open.success": "成功链接%1$s",
链接 改成 连接 怎么样？（+ L93~95）

2022-02-25 16:40 UTC, MikhailTapio commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "commands.jingler.open.failure.no_hanging_lights": "未看向挂灯",
这个地方译为“看向”不难理解，但需不需要参考原文译成“选中”（或者有没有更好的译法）？

2022-02-25 16:42 UTC, ChuijkYahus commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "commands.jingler.open.success": "成功链接%1$s",
OK的，这里本来的意思是连上midi键盘一类的设备

2022-02-25 16:47 UTC, ChuijkYahus commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "commands.jingler.open.failure.no_hanging_lights": "未看向挂灯",
啊啊啊想不出来更好的想法了（
游戏内是需要把挂灯放出来并且看向其中一盏灯再打命令才行

2022-02-25 17:00 UTC, MikhailTapio commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "commands.jingler.open.failure.no_hanging_lights": "未看向挂灯",
问题应该不大😂等一波其他同志们的看法

2022-02-25 18:26 UTC, mamaruo requested changes

2022-02-25 18:26 UTC, mamaruo commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "subtitles.block.fairylights.jingleBell": "挂灯：鸣响",
```suggestion
    "subtitles.block.fairylights.jingleBell": "挂灯：叮当",
```
如果实际声音不是类似“叮当”的话就算了

2022-02-25 18:26 UTC, mamaruo commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "item.fairyLights.twinkle": "闪烁",
一个物品叫“闪烁”？需要检查

2022-02-25 18:26 UTC, mamaruo commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "format.fairylights.color_changing": "多色%1$s",
`Color Changing %1$s`
changing 指的是这个物品的颜色会轮换某几种颜色吗

2022-02-25 18:26 UTC, mamaruo commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "commands.jingler.open.failure.no_hanging_lights": "未看向挂灯",
```suggestion
    "commands.jingler.open.failure.no_hanging_lights": "未瞄准挂灯",
```
select 我觉得是没法硬翻了。

2022-02-25 18:26 UTC, mamaruo commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "commands.jingler.device.vendor": "供应商：%1$s",
有点突兀，需要确认

2022-02-25 18:26 UTC, mamaruo commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "itemGroup.fairylights": "Fairy Lights",
```suggestion
    "itemGroup.fairylights": "圣诞彩灯",
```
来自[官方语言文件](https://github.com/pau101/Fairy-Lights/blob/master/src/main/resources/assets/fairylights/lang/zh_cn.json)。

2022-02-25 18:27 UTC, ChuijkYahus commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "item.fairyLights.twinkle": "闪烁",
这是物品下面的说明

2022-02-25 18:28 UTC, ChuijkYahus commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "recipe.fairylights.hangingLights.light": "使用多种彩灯以自定义排列方式",
是在合成时加入多种彩灯
用加入感觉不通顺（

2022-02-25 18:29 UTC, ChuijkYahus commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "format.fairylights.color_changing": "多色%1$s",
是的，不知道应该怎么翻译更确切

2022-02-25 18:29 UTC, ChuijkYahus commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "itemGroup.fairylights": "Fairy Lights",
改动完成

2022-02-25 18:30 UTC, ChuijkYahus commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "commands.jingler.device.vendor": "供应商：%1$s",
原文是Vendor
可能是midi设备的供应商？源码中自己没能找到合理的对应解释
作者也是搞音乐的，所以就这样翻译了（

2022-02-25 18:47 UTC, mamaruo commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "format.fairylights.color_changing": "多色%1$s",
姑且“变色”？

2022-02-25 18:49 UTC, ChuijkYahus commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "format.fairylights.color_changing": "多色%1$s",
可以，改了

2022-02-25 18:51 UTC, ChuijkYahus commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "format.fairylights.color_changing": "多色%1$s",
也询问一下，dyed指的是类似皮革外套的染色法，只用“染色”会不会过于草率

2022-02-25 18:59 UTC, mamaruo commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "format.fairylights.color_changing": "多色%1$s",
> 也询问一下，dyed指的是类似皮革外套的染色法，只用“染色”会不会过于草率

我认为没啥问题

2022-02-25 19:00 UTC, ChuijkYahus commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "format.fairylights.color_changing": "多色%1$s",
好的，多谢指导

2022-02-26 00:32 UTC, Cyl18 commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "commands.jingler.device.vendor": "供应商：%1$s",
源码位置
https://github.com/pau101/Fairy-Lights/blob/ab32fe7c52bda6e9894e7ac2ee1256b0e6fb2af3/src/main/java/me/paulf/fairylights/client/command/JinglerCommand.java#L151

供应商没啥问题

2022-02-26 00:35 UTC, Cyl18 commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "recipe.fairylights.pennantBunting.pennant": "加入多种彩旗以自定义排列方式",
pattern 应该是 `图案` 而不是 `排序方式`?
或许可以参考下游戏内?

2022-02-26 00:37 UTC, Cyl18 requested changes
-

2022-02-26 01:57 UTC, n0099 commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "commands.jingler.open.failure.no_hanging_lights": "未看向挂灯",
不如`看着`

2022-02-26 04:46 UTC, ChuijkYahus commented on projects/1.16/assets/fairy-lights/fairylights/lang/zh_cn.json
> +    "recipe.fairylights.pennantBunting.pennant": "加入多种彩旗以自定义排列方式",
游戏内是不同类型不同颜色的彩灯彩旗的排列方式
毕竟是一条线上的，用图案感觉有点像平面的（

2022-02-26 12:47 UTC, TartaricAcid approved these changes

2022-02-26 16:33 UTC, MikhailTapio approved these changes
劳模啊👍

2022-02-26 17:20 UTC, Cyl18 approved these changes

2022-02-27 02:44 UTC, n0099 approved these changes

2022-02-27 05:50 UTC, mamaruo approved these changes

2022-02-27 09:51 UTC, merged