[R] Pane In The Glass 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1585
Opened 2022-02-25 18:20 UTC by ChuijkYahus

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-02-25 18:21 UTC, ChuijkYahus commented
_Ctrl+F2真好用_

2022-02-25 18:40 UTC, mamaruo commented on projects/1.16/assets/pane-in-the-glass/pitg/lang/zh_cn.json
> +  "item.pitg.glazing_tool": "玻璃刀",
`Glazing Tool`
看 [CurseForge](https://www.curseforge.com/minecraft/mc-mods/pane-in-the-glass) 这也不是打光工具啊，奇了怪。

2022-02-25 18:41 UTC, mamaruo commented on projects/1.16/assets/pane-in-the-glass/pitg/lang/zh_cn.json
> +  "itemGroup.pitg": "Pane In The Glass"
```suggestion
  "itemGroup.pitg": "门窗玻璃"
```
不是很好，想不出了

2022-02-25 18:42 UTC, ChuijkYahus commented on projects/1.16/assets/pane-in-the-glass/pitg/lang/zh_cn.json
> +  "itemGroup.pitg": "Pane In The Glass"
其实之前自己想了个“玻璃板之殇”（

2022-02-25 19:11 UTC, ChuijkYahus commented on projects/1.16/assets/pane-in-the-glass/pitg/lang/zh_cn.json
> +  "item.pitg.glazing_tool": "玻璃刀",
glaze 应该还有“安窗户，安玻璃”的意思，就这样翻了

2022-02-25 19:18 UTC, mamaruo commented
> _Ctrl+F2真好用_

请教一下，你是怎么 Ctrl+F2 避免把光标定位到键值上的

2022-02-25 19:19 UTC, ChuijkYahus commented
> > _Ctrl+F2真好用_
> 
> 请教一下，你是怎么 Ctrl+F2 避免把光标定位到键值上的

Alt+C大小写敏感，在我这个版本里选中后右上角最左边的按键也是

2022-02-26 00:46 UTC, Cyl18 commented on projects/1.16/assets/pane-in-the-glass/pitg/lang/zh_cn.json
> +  "itemGroup.pitg": "Pane In The Glass"
或者就暂时保持不译了（

2022-02-26 00:54 UTC, Cyl18 requested changes

2022-02-26 00:54 UTC, Cyl18 commented on projects/1.16/assets/pane-in-the-glass/pitg/lang/zh_cn.json
> +  "block.pitg.black_plain_dualglasspane": "黑色平滑玻璃板（边沿对齐）",
```suggestion
  "block.pitg.black_plain_dualglasspane": "黑色平滑双玻璃板（边沿对齐）",

```
和上文保持一致

2022-02-26 00:54 UTC, Cyl18 commented on projects/1.16/assets/pane-in-the-glass/pitg/lang/zh_cn.json
> +  "block.pitg.black_stained_dualglasspane": "黑色染色玻璃板（边沿对齐）",
```suggestion
  "block.pitg.black_stained_dualglasspane": "黑色染色双玻璃板（边沿对齐）",

```
和上文保持一致

2022-02-26 00:54 UTC, Cyl18 commented on projects/1.16/assets/pane-in-the-glass/pitg/lang/zh_cn.json
> +  "block.pitg.black_tinted_dualglasspane": "黑色浅色玻璃板（边沿对齐）",
```suggestion
  "block.pitg.black_tinted_dualglasspane": "黑色浅色双玻璃板（边沿对齐）",

```
和上文...

2022-02-26 04:47 UTC, ChuijkYahus commented on projects/1.16/assets/pane-in-the-glass/pitg/lang/zh_cn.json
> +  "block.pitg.black_plain_dualglasspane": "黑色平滑玻璃板（边沿对齐）",
这些怎么能掉的（
再全部检查一遍

2022-02-26 04:54 UTC, ChuijkYahus commented on projects/1.16/assets/pane-in-the-glass/pitg/lang/zh_cn.json
> +  "block.pitg.black_plain_dualglasspane": "黑色平滑玻璃板（边沿对齐）",
绝了英文部分也掉了，一并修改

2022-02-26 07:05 UTC, Cyl18 commented on projects/1.16/assets/pane-in-the-glass/pitg/lang/zh_cn.json
> +  "block.pitg.black_plain_dualglasspane": "黑色平滑玻璃板（边沿对齐）",
英文掉了也太怪了

2022-02-26 07:49 UTC, ChuijkYahus commented on projects/1.16/assets/pane-in-the-glass/pitg/lang/zh_cn.json
> +  "block.pitg.black_plain_dualglasspane": "黑色平滑玻璃板（边沿对齐）",
OK，那就改回去

2022-02-26 12:50 UTC, TartaricAcid approved these changes

2022-02-26 12:50 UTC, TartaricAcid commented on projects/1.16/assets/pane-in-the-glass/pitg/lang/zh_cn.json
> +  "itemGroup.pitg": "Pane In The Glass"
玻璃板之殇，感觉还挺不错的

2022-02-26 13:14 UTC, ChuijkYahus commented on projects/1.16/assets/pane-in-the-glass/pitg/lang/zh_cn.json
> +  "itemGroup.pitg": "Pane In The Glass"
那就先用玻璃板之殇了

2022-02-26 13:23 UTC, mamaruo approved these changes
Formatter 是不是寄了

2022-02-27 02:46 UTC, n0099 approved these changes

2022-02-27 13:29 UTC, merged