[R] Glasscutter 新增翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #1587
Opened 2022-02-25 19:32 UTC by mamaruo

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-02-26 00:21 UTC, Cyl18 approved these changes
切玻璃机总感觉怪怪的 但是考虑原版切石机也还行？

2022-02-26 00:24 UTC, Cyl18 requested changes

2022-02-26 00:24 UTC, Cyl18 commented on projects/1.16/assets/glass-cutter/glasscutter/lang/zh_cn.json
> +    "block.glasscutter.light_gray_stained_glass_stairs": "淡青色染色玻璃楼梯",
```suggestion
    "block.glasscutter.light_gray_stained_glass_stairs": "淡灰色染色玻璃楼梯",
```

2022-02-26 00:24 UTC, Cyl18 commented on projects/1.16/assets/glass-cutter/glasscutter/lang/zh_cn.json
> +    "block.glasscutter.light_gray_stained_glass_slab": "淡青色染色玻璃台阶",
```suggestion
    "block.glasscutter.light_gray_stained_glass_slab": "淡灰色染色玻璃台阶",
```

2022-02-26 00:27 UTC, Cyl18 requested changes

2022-02-26 00:27 UTC, Cyl18 commented on projects/1.16/assets/glass-cutter/glasscutter/lang/zh_cn.json
> +    "block.glasscutter.pink_stained_glass_slab": "粉色染色玻璃台阶",
```suggestion
    "block.glasscutter.pink_stained_glass_slab": "粉红色染色玻璃台阶",
```
参考原版

2022-02-26 00:27 UTC, Cyl18 commented on projects/1.16/assets/glass-cutter/glasscutter/lang/zh_cn.json
> +    "block.glasscutter.pink_stained_glass_stairs": "粉色染色玻璃楼梯",
```suggestion
    "block.glasscutter.pink_stained_glass_stairs": "粉红色染色玻璃楼梯",
```

2022-02-26 12:55 UTC, TartaricAcid approved these changes

2022-02-27 02:48 UTC, n0099 approved these changes

2022-02-27 13:25 UTC, merged