[R]buddycards帕秋莉手册
CFPAOrg/Minecraft-Mod-Language-Package pull request #1597
Opened 2022-02-27 09:37 UTC by xingmot

翻译时使用的模组版本是2.5.2
巴迪卡牌帕秋莉手册汉化进度100%，除首页无本地化键未进行汉化。
zh_cn官中语言文件，修改一处，将巴迪钢鱼刀修改为巴迪钢鱼片刀，与联动模组的鱼片刀翻译保持一致。
未进行细致检查，汉化时仅通过游戏内效果，确认无漏翻页面，可能存在部分翻译句子不通顺等问题。((不敢保证翻译的时候时刻清醒
实际原英文手册存在多出表述错误，如复制粘贴未修改等，作者可能在高版本1.17等中进行了修改，这些部分汉化时均已修复。

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [ ] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-02-27 15:51 UTC, mamaruo commented on projects/1.16/assets/buddycards/patchouli_books/buddycard_guidebook/zh_cn/entries/buddysteel/perfect_buddysteel.json
> +      "text": "为了制作完美巴迪钢，你首先需要制作完美巴迪钢粉。这个过程需要一点巴迪钢，紫砺和流光，以及它们的块版本。"
In order to make perfect buddysteel, you must first make perfect buddysteel blend. This requires a bit of buddysteel, zylex, and luminis, both in a **massive** amount and a more concentrated item form.
又是 massive 又是 a bit of 的，不能理解。
```suggestion
      "text": "要制作完美巴迪钢，你首先得制作完美巴迪钢粉。这需要一点巴迪钢，紫砺和流光，再多一个它们的块。"
```

2022-02-27 16:30 UTC, mamaruo requested changes

2022-02-27 16:30 UTC, mamaruo commented on projects/1.16/assets/buddycards/patchouli_books/buddycard_guidebook/zh_cn/entries/sets/end_set.json
> +      "text": "The end set packs, 同其它大多数卡牌包一样，总共会给予 4 张卡牌，它们之中只有一张会是闪卡。$(br2)卡牌按稀有度分为四个等级：普通的、常见的、罕见的和史诗的。你可以通过卡牌角落的颜色来区分它们。"
漏译

2022-02-27 16:30 UTC, mamaruo commented on projects/1.16/assets/buddycards/patchouli_books/buddycard_guidebook/zh_cn/entries/sets/end_set.json
> +      "text": "末地包大多在杀死末影龙时找到，末影龙总是会掉落几个。$(br2)在搜刮末地城时也能发现，箱子里找到或偶尔从潜影贝身上掉落。",
**End set packs** can be found most commonly by killing the dragon, as he is guaranteed to drop a few. $(br2)You can also find packs when raiding end cities, both in chests and **rarely** as a drop from shulkers.
一致性问题，rare 不太合适
```suggestion
      "text": "末地卡牌包大多在杀死末影龙时找到，末影龙总会掉落几个。$(br2)在搜刮末地城也能在箱子里找到它，它也是潜影贝的罕见掉落物。",
```

2022-02-27 16:30 UTC, mamaruo commented on projects/1.16/assets/buddycards/patchouli_books/buddycard_guidebook/zh_cn/entries/sets/byg_set.json
> +      "text": "巴迪卡牌的 你将去的生物群系（后文简称byg）包 获取比较棘手，你必须在世界各地找到三种不同的byg物品。byg包中一共有 27 张牌，此外还对应有闪卡与不同等级的卡片。$(br2)为了获取byg卡牌，你必须制作对应的byg卡牌包。"
建议大写

2022-02-27 16:30 UTC, mamaruo commented on projects/1.16/assets/buddycards/patchouli_books/buddycard_guidebook/zh_cn/entries/luminis/specialties.json
> +      "text": "我们不太清楚流光镐是如何制作的，但它能与『巴迪绑定』一起工作，并且与完美巴迪钢非常相似。"
一致性问题
上面的类似文本是这样翻的

`"text": "我们无从得知紫砺靴子是如何制作的，但是它支持『巴迪绑定』并且与完美巴迪钢十分相像。"`

2022-02-27 16:30 UTC, mamaruo commented on projects/1.16/assets/buddycards/patchouli_books/buddycard_guidebook/zh_cn/entries/luminis/deep_luminis.json
> +      "text": "就像普通的流光一样，当被熔炼时深层流光凝固并开始发出光芒。虽然这种流光并不能作用于巴迪卡牌，但因为它的流光浓度很高，它可以用来升级巴迪钢。"
```suggestion
      "text": "就像普通的流光一样，当被熔炼时深层流光凝固并开始发出光芒。虽然这种流光并不能作用于巴迪卡牌，但因为它的流光浓度很高，可以用来升级巴迪钢。"

```

2022-02-27 16:30 UTC, mamaruo commented on projects/1.16/assets/buddycards/patchouli_books/buddycard_guidebook/zh_cn/entries/items/mystery_pack.json
> +      "text": "神秘卡牌包收藏家们最好的朋友，将世界上生成的通常只有四张卡牌的卡包转化为一次包含 9 张卡牌的卡包。它们总是能开出9张卡牌，其中有两张是闪卡。稀有度与普通的卡包相同。$(br2)神秘卡牌包也是从卸载或停用的模组中获取卡组的唯一方式，因为它们从任意卡组中抽取卡牌。"
空格一致性问题，全部文件都需要检查
1.16 以上不再需要加空格

2022-02-27 16:30 UTC, mamaruo commented on projects/1.16/assets/buddycards/patchouli_books/buddycard_guidebook/zh_cn/entries/items/medal_token.json
> +      "text": "如果你有一个奖牌，通过勋章代币可以制作一个新的奖牌。 由于每套卡组只能获得一枚勋章，因此如果你的勋章上没有『巴迪绑定』附魔，这是确保你不会丢失它的最好方法。"
The medal token can be used to make a new medal, given you have the **original** medal. If you don't have Buddy Binding on a medal, this is the best way to make sure you don't lose it, as you only ever get 1 medal per set.
original 是漏了还是说没必要加？

2022-02-27 16:30 UTC, mamaruo commented on projects/1.16/assets/buddycards/patchouli_books/buddycard_guidebook/zh_cn/entries/items/grading_sleeve.json
> +      "text": "找到一张等级 A 的巴迪卡牌是一件值得骄傲的事情。$(br2)这些卡片质量几乎完美，它们都很难被找到。大约1/10的巴迪卡牌是 等级 A。"
一致性问题（与上一条）

2022-02-27 16:30 UTC, mamaruo commented on projects/1.16/assets/buddycards/patchouli_books/buddycard_guidebook/zh_cn/entries/items/grading_sleeve.json
> +      "text": "现在我已经提醒过你了！评级卡套不是为随意的巴迪卡牌收藏家准备的。$(br2)评级卡套允许你主手拿着一张未分级的卡，用副手的评级卡套给卡打分。你将获得 5 个等级中的 1 个。"
Grading Sleeves are not for the casual Buddycard collector. You have been warned. $(br2)Grading Sleeves allow you to grade cards by holding it in your offhand with an ungraded card in your main hand. It will get 1 of 5 grades.
```suggestion
      "text": "现在我已经提醒过你了！评级卡套不适合为休闲巴迪卡牌收藏家。$(br2)评级卡套允许你主手拿着一张未分级的卡，用副手的评级卡套给卡打分。未分级卡获得5个等级中的1个。"

```

2022-02-28 07:52 UTC, MikhailTapio commented on projects/1.16/assets/buddycards/patchouli_books/buddycard_guidebook/zh_cn/entries/sets/end_set.json
> +      "text": "末地包大多在杀死末影龙时找到，末影龙总是会掉落几个。$(br2)在搜刮末地城时也能发现，箱子里找到或偶尔从潜影贝身上掉落。",
> **End set packs** can be found most commonly by killing the dragon, as he is guaranteed to drop a few. $(br2)You can also find packs when raiding end cities, both in chests and **rarely** as a drop from shulkers. 一致性问题，rare 不太合适

考虑到谐音，建议 罕见 -> 稀有

2022-02-28 10:44 UTC, MikhailTapio requested changes

2022-02-28 10:44 UTC, MikhailTapio commented on projects/1.16/assets/buddycards/lang/zh_cn.json
> +  "advancements.buddycards.main.epic_card.desc": "获得一张史诗罕见卡",
Rarity 应为“稀有度”，这里我认为可以直接翻译为“获得一张史实卡”。
另外关于四种稀有度的翻译，Minecraft 中文 wiki 已有[标准](https://minecraft.fandom.com/zh/wiki/%E7%A8%80%E6%9C%89%E5%BA%A6)。
建议替换一下文件中的“罕见”等词。

2022-02-28 16:22 UTC, n0099 commented on projects/1.16/assets/buddycards/lang/zh_cn.json
> +  "item.buddycards.card.2.23.tooltip": "现在你在用维度思考!",
跨纬度？

2022-03-01 09:22 UTC, xingmot commented on projects/1.16/assets/buddycards/lang/zh_cn.json
> +  "advancements.buddycards.main.epic_card.desc": "获得一张史诗罕见卡",
ok，我改一下，zh_cn是官中，修改好会一起提交给作者

2022-03-01 09:50 UTC, xingmot commented on projects/1.16/assets/buddycards/lang/zh_cn.json
> +  "item.buddycards.card.2.5.tooltip": "他是一个真正的小队！绝对是个大家伙！",
我觉得官中没太大问题？

2022-03-01 09:53 UTC, xingmot commented on projects/1.16/assets/buddycards/lang/zh_cn.json
> +  "item.buddycards.card.2.23.tooltip": "现在你在用维度思考!",
这句话翻译没什么歧义吧，直译就是这个意思啊。
Now you're thinking with dimensions!
不然翻成 你正在多维度思考！ 这样？

2022-03-01 10:00 UTC, xingmot commented on projects/1.16/assets/buddycards/lang/zh_cn.json
> +  "item.buddycards.card.3.2.tooltip": "他们自己也是个收藏家。",
这里的盒子怪就是比喻的潜影贝，我觉得这句话带点比喻的味道，
就像是：他就像是一个收藏家。
老实说我机翻出来也还行的：他们本身就是个收藏家。
或者：他们其实也是收藏家。（纠结。。）

2022-03-01 10:11 UTC, xingmot commented on projects/1.16/assets/buddycards/patchouli_books/buddycard_guidebook/zh_cn/entries/items/medal_token.json
> +      "text": "如果你有一个奖牌，通过勋章代币可以制作一个新的奖牌。 由于每套卡组只能获得一枚勋章，因此如果你的勋章上没有『巴迪绑定』附魔，这是确保你不会丢失它的最好方法。"
我觉得没必要加吧。（把奖牌改成勋章就行了，这里我忘记改了）
因为下一页就是复制勋章的配方，我觉得可以不用加，机翻加了很别扭故意删了的。

然后这一页新版2.5.3 mod似乎删了，后面可能会选择两个版本分开提交官中。

2022-03-01 10:20 UTC, xingmot commented
这里统一说明一下吧。因为模组在1.16.5有两个版本的帕秋莉手册，分别是2.5.2的第8版和2.5.3的第9版，有部分页面的删除和修改。
帕秋莉手册改动见：（就是删了一页，另一页加了一句话）
https://github.com/wildcardgamez/BuddyCards/commit/326578f7eafe38286cb25e32b6fac7247a72f07f
所以最后还是想选择提交官中了

2022-03-01 15:33 UTC, mamaruo commented on projects/1.16/assets/buddycards/lang/zh_cn.json
> +  "item.buddycards.card.2.23.tooltip": "现在你在用维度思考!",
维度，不是纬度

2022-03-02 00:14 UTC, Cyl18 commented on projects/1.16/assets/buddycards/lang/zh_cn.json
> +  "block.buddycards.glacial_oak_card_display": "Glacial Oak Card Display",
这里没有翻译

2022-03-02 00:14 UTC, Cyl18 commented on projects/1.16/assets/buddycards/lang/zh_cn.json
> +  "item.buddycards.set.4": "你将去的生物群系包",
这个是咋翻译过来的呀

2022-03-02 01:49 UTC, MikhailTapio commented on projects/1.16/assets/buddycards/lang/zh_cn.json
> +  "item.buddycards.card.2.5.tooltip": "他是一个真正的小队！绝对是个大家伙！",
> 我觉得官中没太大问题？

不好说，但我觉得翻译成 单位 显然比 小队 合理得多😂
（有没有问题和是不是官中应该关系不大吧）

2022-03-02 01:50 UTC, MikhailTapio commented on projects/1.16/assets/buddycards/lang/zh_cn.json
> +  "item.buddycards.card.2.23.tooltip": "现在你在用维度思考!",
> 这句话翻译没什么歧义吧，直译就是这个意思啊。 Now you're thinking with dimensions! 不然翻成 你正在多维度思考！ 这样？

这样翻合理多了（

2022-03-02 04:35 UTC, xingmot commented on projects/1.16/assets/buddycards/lang/zh_cn.json
> +  "block.buddycards.glacial_oak_card_display": "Glacial Oak Card Display",
这玩意没合成表。byg mod的1.3.5版本，找半天只有贴图，方块都没的。

2022-03-02 04:36 UTC, xingmot commented on projects/1.16/assets/buddycards/lang/zh_cn.json
> +  "item.buddycards.set.4": "你将去的生物群系包",
byg就是联动mod，你将去的生物群系

2022-03-02 12:32 UTC, n0099 commented on projects/1.16/assets/buddycards/lang/zh_cn.json
> +  "item.buddycards.set.4": "你将去的生物群系包",
bop还叫超多生物群系呢

2022-03-08 01:42 UTC, xingmot commented
这两天一堆破事没什么时间，之前联系作者了，群里说过可能被刷掉很多人不清楚。作者表示不会更新旧版本（目前最新版是1.18.1）的模组文件，所以还是得走i18n，后面我把文件更新到2.5.3第九版的帕秋莉书，目前第八版的汉化我就分享一个汉化材质包链接到mcmod评论区算了。。

2022-03-08 13:09 UTC, TartaricAcid commented
进游戏大致浏览了一遍手册，翻译的挺不错，很用心。

仅对“你将去的生物群系（Oh The Biomes You'll Go）”这个翻译略感觉不合适，我暂时修改为 BYG 缩写。同时在手册内添加提示，这样应该也不会导致误解和歧义。

2022-03-08 13:10 UTC, TartaricAcid approved these changes

2022-03-08 14:36 UTC, mamaruo approved these changes

2022-03-09 02:39 UTC, xingmot commented
新版本2.5.3对应的手册汉化提交了，中间出了点小插曲。。一开始只是想试试vscode的git图形化提交，试了好几次各种报错，结果没改好突然就能用了，就后面又提交了一次。

2022-03-09 10:25 UTC, merged