[R] 添加 Craft and Hunt 模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #1600
Opened 2022-03-03 05:38 UTC by TartaricAcid

来自工单：CFPA-130761522939858
- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [ ] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-03 17:35 UTC, n0099 commented on projects/1.16/assets/craft-and-hunt/craftandhunt/lang/zh_cn.json
> +	"advancements.craftandhunt.root": "狩猎开始了...",
```suggestion
	"advancements.craftandhunt.root": "狩猎开始了……",
```

2022-03-09 18:05 UTC, mamaruo requested changes

2022-03-09 18:05 UTC, mamaruo commented on projects/1.16/assets/craft-and-hunt/craftandhunt/lang/zh_cn.json
> +	"item.craftandhunt.impact_slime": "黑曜石粘液磅",
```suggestion
	"item.craftandhunt.impact_slime": "黑曜石粘液杵",
```

2022-03-09 18:05 UTC, mamaruo commented on projects/1.16/assets/craft-and-hunt/craftandhunt/lang/zh_cn.json
> +	"craftandhunt.comment_one.desc": "装备与工具",
Armor 必须翻译成“盔甲”

2022-03-10 00:15 UTC, NianGuu commented on projects/1.16/assets/craft-and-hunt/craftandhunt/lang/zh_cn.json
> +	"death.attack.bleeding": "%1$s流血了，但他没有阻止它",
> 

上面两个应该是未实装的成就，底下那个应该是死亡信息

2022-03-10 00:17 UTC, NianGuu commented on projects/1.16/assets/craft-and-hunt/craftandhunt/lang/zh_cn.json
> +	"item.craftandhunt.u_wither_boots": "凋零之魂靴子",
> 凋灵之魂？

因为原文是wither soul

2022-03-10 00:24 UTC, NianGuu commented on projects/1.16/assets/craft-and-hunt/craftandhunt/lang/zh_cn.json
> +	"item.minecraft.tipped_arrow.effect.long_goatstrength": "山羊之箭",
> `Arrow of Inner Goat` inner 哪去了
Arrow of Inner Goat我想出来的比较通畅的解释就是内含山羊的箭/内含山羊力量的箭，所以就缩成了山羊之箭

2022-03-10 04:46 UTC, n0099 commented on projects/1.16/assets/craft-and-hunt/craftandhunt/lang/zh_cn.json
> +	"effect.craftandhunt.wither_resistance": "防凋零",
```suggestion
	"effect.craftandhunt.wither_resistance": "抗凋零",
```

2022-03-10 05:17 UTC, mamaruo commented on projects/1.16/assets/craft-and-hunt/craftandhunt/lang/zh_cn.json
> +	"death.attack.bleeding": "%1$s流血了，但他没有阻止它",
588行翻译很怪

2022-03-10 05:21 UTC, NianGuu commented on projects/1.16/assets/craft-and-hunt/craftandhunt/lang/zh_cn.json
> +	"death.attack.bleeding": "%1$s流血了，但他没有阻止它",
> 588行翻译很怪

流血了，但没来得及阻止？

2022-03-10 05:31 UTC, n0099 commented on projects/1.16/assets/craft-and-hunt/craftandhunt/lang/zh_cn.json
> +	"death.attack.bleeding": "%1$s流血了，但他没有阻止它",
```suggestion
	"death.attack.bleeding": "%1$s因失血过多而死",
```

2022-03-11 05:26 UTC, mamaruo commented on projects/1.16/assets/craft-and-hunt/craftandhunt/lang/zh_cn.json
> +	"item.craftandhunt.guide.landing": "本指南旨在帮助您了解所有可以狩猎以及从Craf and Hunt制作的装备！",
```suggestion
	"item.craftandhunt.guide.landing": "本指南助你了解狩猎工艺中所有你能猎取的盔甲，还有装备制作工艺！",
```
```suggestion
	"item.craftandhunt.guide.landing": "本指南旨在帮助你了解狩猎工艺中你能猎取什么盔甲，制作什么装备！",
```

This guide is here to help you learn about all the armor you can **hunt** for and gear you can **craft** from **Craft** and **Hunt**!

2022-03-11 05:44 UTC, Cyl18 commented on projects/1.16/assets/craft-and-hunt/craftandhunt/lang/zh_cn.json
> +	"item.craftandhunt.guide.landing": "本指南旨在帮助你了解所有可以狩猎以及从Craf and Hunt制作的装备！",
```suggestion
	"item.craftandhunt.guide.landing": "本指南旨在帮助你了解所有可以狩猎以及从Craft and Hunt制作的装备！",
```

2022-03-12 11:22 UTC, mamaruo approved these changes

2022-03-13 01:35 UTC, n0099 approved these changes

2022-03-13 06:03 UTC, merged