[R][WIP] add SimpleTomb
CFPAOrg/Minecraft-Mod-Language-Package pull request #1601
Opened 2022-03-03 06:09 UTC by mamaruo

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-03 17:33 UTC, n0099 requested changes

2022-03-03 17:33 UTC, n0099 commented on projects/1.18/assets/simple-tomb/simpletomb/lang/zh_cn.json
> +    "simpletomb.commands.null": "子命令错误，示例：/simpletomb latest",
```suggestion
    "simpletomb.commands.null": "子命令格式错误，示例：/simpletomb latest",
```

2022-03-03 17:33 UTC, n0099 commented on projects/1.18/assets/simple-tomb/simpletomb/lang/zh_cn.json
> +    "simpletomb.message.no_grave_location": "你的物品落了一地；这地方不适合坟墓",
```suggestion
    "simpletomb.message.no_grave_location": "你的物品落了一地！这地方不适合放置坟墓",
```

2022-03-03 17:33 UTC, n0099 commented on projects/1.18/assets/simple-tomb/simpletomb/lang/zh_cn.json
> +    "simpletomb.message.no_loot_for_grave": "没有墓碑出现，因为没物品可存",
```suggestion
    "simpletomb.message.no_loot_for_grave": "没有墓碑出现，因为死亡时物品栏为空",
```

2022-03-03 17:33 UTC, n0099 commented on projects/1.18/assets/simple-tomb/simpletomb/lang/zh_cn.json
> +    "simpletomb.message.new_grave": "坟墓已创建：: %s",
```suggestion
    "simpletomb.message.new_grave": "坟墓已创建：%s",
```

2022-03-03 17:33 UTC, n0099 commented on projects/1.18/assets/simple-tomb/simpletomb/lang/zh_cn.json
> +    "simpletomb.config.unhandled_beneficial_effects.tooltip": "Beneficial effects that can't used by certain features such as �nkh of pray, lollipop, scroll of preservation, alchemy perk and magic si
`�nkh` 这个unicode replacement char原文是什么

2022-03-03 17:39 UTC, mamaruo commented on projects/1.18/assets/simple-tomb/simpletomb/lang/zh_cn.json
> +    "simpletomb.config.unhandled_beneficial_effects.tooltip": "Beneficial effects that can't used by certain features such as �nkh of pray, lollipop, scroll of preservation, alchemy perk and magic si
[U+00E2](https://unicode-table.com/en/00E2/)
[Wikipedia](https://fr.wikipedia.org/wiki/%C3%82nkh)

2022-03-03 17:48 UTC, mamaruo commented on projects/1.18/assets/simple-tomb/simpletomb/lang/zh_cn.json
> +    "simpletomb.message.no_grave_location": "你的物品落了一地；这地方不适合坟墓",
已改；原文无叹号。

2022-03-03 18:02 UTC, n0099 commented on projects/1.18/assets/simple-tomb/simpletomb/lang/zh_cn.json
> +    "simpletomb.message.no_grave_location": "你的物品落了一地；这地方不适合坟墓",
为什么一定要遵循原文的标点，死亡掉落本就是应该引起玩家注意的事件，不然以为有坟墓就不/back了

2022-03-03 18:05 UTC, n0099 commented on projects/1.18/assets/simple-tomb/simpletomb/lang/zh_cn.json
> +    "simpletomb.config.unhandled_beneficial_effects.tooltip": "Beneficial effects that can't used by certain features such as �nkh of pray, lollipop, scroll of preservation, alchemy perk and magic si
这个物品是抄的Corail Tombstone吗https://www.reddit.com/r/feedthebeast/comments/j04llk/corail_tombstone_ankh_of_pray_effects/

2022-03-03 18:06 UTC, n0099 commented on projects/1.18/assets/simple-tomb/simpletomb/lang/zh_cn.json
> +    "simpletomb.config.unhandled_beneficial_effects.tooltip": "Beneficial effects that can't used by certain features such as �nkh of pray, lollipop, scroll of preservation, alchemy perk and magic si
https://www.curseforge.com/minecraft/mc-mods/simple-tomb的spoiler里说
> 这不是 Corails-tombstone 的翻拍或替代品。这有一个新的 modid 'simpletomb'，所以它不会碰撞。这是我自己的代码更改，删除了大多数功能，添加了其他功能。除钥匙外的所有物品都被移除，主要特征是墓碑与玩家物品一起生成。钥匙和墓碑现在的工作方式略有不同。这个模组是一个微型坟墓模组，但它是从 corails 墓碑分叉出来的，并且确实依赖于其中的代码和资产。所有许可证信息都在这里。这个简单的 tombstone mod 也是在相同的兼容 LGPL v2.1 下发布的，在根据许可证说明了这些更改之后。
> Tombstones mod 在历史上一直是封闭源代码。原作者 (Corail) 决定离开 Minecraft 社区并决定开源该模组。

2022-03-03 18:24 UTC, mamaruo commented
我有点怀疑作者根本没做某些功能，语言文件继承旧版，导致有些文本我游戏里找不到。

2022-03-04 13:59 UTC, n0099 commented
这mod开源吗

2022-03-04 14:05 UTC, mamaruo commented
https://github.com/Lothrazar/SimpleTomb

> 这mod开源吗

2022-03-05 19:14 UTC, mamaruo commented on projects/1.18/assets/simple-tomb/simpletomb/lang/zh_cn.json
> +    "simpletomb.config.unhandled_beneficial_effects.tooltip": "Beneficial effects that can't used by certain features such as �nkh of pray, lollipop, scroll of preservation, alchemy perk and magic si
```suggestion
    "simpletomb.config.unhandled_beneficial_effects.tooltip": "Beneficial effects that can't used by certain features such as �nkh of pray, lollipop, scroll of preservation, alchemy perk and magic siphon enchantment test",
```

2022-03-08 04:24 UTC, mamaruo commented
请求协助，剩的行不会了

2022-03-08 06:45 UTC, n0099 requested changes

2022-03-08 06:45 UTC, n0099 commented on projects/1.18/assets/simple-tomb/simpletomb/lang/zh_cn.json
> +    "simpletomb.config.unhandled_harmful_effects.tooltip": "Harmful effects that can't used by certain features such as tablet of cupidity and the enchantment plague bringer",
```suggestion
    "simpletomb.config.unhandled_harmful_effects": "忽略的负面效果",
    "simpletomb.config.unhandled_harmful_effects.tooltip": "无法被某些功能（如贪婪石板和瘟疫使者附魔）所使用的负面效果",
```

https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/5c3b62431da6d96156bf4573d9cf7642f84439b7/projects/1.16/assets/corail-tombstone/tombstone/lang/zh_cn.json#L58

https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/5c3b62431da6d96156bf4573d9cf7642f84439b7/projects/1.16/assets/corail-tombstone/tombstone/lang/zh_cn.json#L563

2022-03-08 06:45 UTC, n0099 commented on projects/1.18/assets/simple-tomb/simpletomb/lang/zh_cn.json
> +    "simpletomb.config.chance_mob_on_grave_recovery.tooltip": "The chance that creatures appear after the contents of a grave are retrieved",
```suggestion
    "simpletomb.config.chance_mob_on_grave_recovery.tooltip": "在取出坟墓物品后随机生成生物的概率",
```

2022-03-08 06:45 UTC, n0099 commented on projects/1.18/assets/simple-tomb/simpletomb/lang/zh_cn.json
> +    "simpletomb.config.unhandled_beneficial_effects.tooltip": "Beneficial effects that can't used by certain features such as �nkh of pray, lollipop, scroll of preservation, alchemy perk and magic si
```suggestion
    "simpletomb.config.unhandled_beneficial_effects": "忽略的正面效果",
    "simpletomb.config.unhandled_beneficial_effects.tooltip": "无法被某些功能（如安卡的祈祷、万圣节棒棒糖、保存卷轴、炼金术师和魔法虹吸附魔）所使用的正面效果",
```
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/5c3b62431da6d96156bf4573d9cf7642f84439b7/projects/1.16/assets/corail-tombstone/tombstone/lang/zh_cn.json#L99
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/5c3b62431da6d96156bf4573d9cf7642f84439b7/projects/1.16/assets/corail-tombstone/tombstone/lang/zh_cn.json#L104
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/5c3b62431da6d96156bf4573d9cf7642f84439b7/projects/1.16/assets/corail-tombstone/tombstone/lang/zh_cn.json#L28
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/5c3b62431da6d96156bf4573d9cf7642f84439b7/projects/1.16/assets/corail-tombstone/tombstone/lang/zh_cn.json#L303
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/5c3b62431da6d96156bf4573d9cf7642f84439b7/projects/1.16/assets/corail-tombstone/tombstone/lang/zh_cn.json#L562

2022-03-09 15:24 UTC, TartaricAcid approved these changes

2022-03-10 04:44 UTC, n0099 approved these changes

2022-03-10 05:13 UTC, merged