[R] Supplementaries 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #1603
Opened 2022-03-03 18:02 UTC by ChuijkYahus

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已确认有参照的英文原文，若无请上传或更新英文原文；
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

内含较多强行注释文本，仅为考证使用，merge前会删除

2022-03-03 18:09 UTC, n0099 commented on projects/1.16/assets/supplementaries/supplementaries/lang/zh_cn.json
> +  //bop = Biomes O' Plenty
您可以用不存在的key来表达注释
```suggestion
  "block.supplementaries.hanging_sign_imparius": "Imparius 挂牌",
  "_supplementaries.comment.hanging_sign_imparius": "官中未译"
  "item.supplementaries.sign_post_imparius": "Imparius 路标",
  "_supplementaries.comment.bop": "Biomes O' Plenty"
```
如果支持json5规划就可以直接注释了

2022-03-03 18:22 UTC, mamaruo commented
请更新 en_us
“我已确认有参照的英文原文，若无请上传或更新英文原文；”

2022-03-04 18:20 UTC, ChuijkYahus commented
后面应该会投给官中，所有reviewer署名为co-author
（不过由于supplementaries的更新频率，汉化很可能会很快过时

2022-03-04 18:52 UTC, ChuijkYahus commented
supplementaries 1.18 中挂牌和路标对 quark 新增的两种木材有兼容，且有正确翻译
在所有标为 en 的语言文件中均未发现对这两种木材兼容的文本
（不知道是不是硬编码

2022-03-05 07:12 UTC, TartaricAcid approved these changes

2022-03-05 14:45 UTC, mamaruo requested changes

2022-03-05 14:51 UTC, ChuijkYahus commented on projects/1.16/assets/supplementaries/supplementaries/lang/zh_cn.json
> +  "block.supplementaries.turn_table": "转盘",
原译转台，已全改为转台

2022-03-05 18:45 UTC, ChuijkYahus commented on projects/1.18/assets/supplementaries/supplementaries/lang/zh_cn.json
> +  "advancements.adventure.globe.title": "你抱着我旋转不止",
这首歌其实有一个比较那啥的梗，想了想还是就用歌词直翻

2022-03-05 18:45 UTC, ChuijkYahus commented on projects/1.18/assets/supplementaries/supplementaries/lang/zh_cn.json
> +  "block.supplementaries.laser_block": "末影激光座",
默认不开启，要到配置里打开

2022-03-05 18:55 UTC, ChuijkYahus commented on projects/1.18/assets/supplementaries/supplementaries/lang/zh_cn.json
> +  "itemGroup.jars": "广口瓶",
原译广口瓶，全部更改

2022-03-05 18:57 UTC, ChuijkYahus commented on projects/1.18/assets/supplementaries/supplementaries/lang/zh_cn.json
> +  "itemGroup.jars": "广口瓶",
所有为“瓶”且指玻璃罐的位置也更改。可能会有遗漏

2022-03-05 19:00 UTC, ChuijkYahus commented on projects/1.18/assets/supplementaries/supplementaries/lang/zh_cn.json
> +  "block.supplementaries.daub": "抹灰",
改译“粗灰泥”

2022-03-06 18:16 UTC, n0099 commented on projects/1.18/assets/supplementaries/supplementaries/lang/zh_cn.json
> +  "advancements.story.unenchanter.title": "怎么可以这样做！？",
```suggestion
  "advancements.story.unenchanter.title": "怎么可以这样做？！",

```

2022-03-07 07:14 UTC, mamaruo commented on projects/1.18/assets/supplementaries/supplementaries/lang/zh_cn.json
> +  "globe.supplementaries.flat": "地平说",
思考了一下，没有想到更好的译法，就这样吧

2022-03-07 09:55 UTC, mamaruo approved these changes
应该没有什么大问题了，1.16似乎差不多，我没review
预计 merge 时间：2022年3月8日 18点

2022-03-07 09:59 UTC, mamaruo commented on projects/1.18/assets/supplementaries/supplementaries/lang/zh_cn.json
> +  "fluid.supplementaries.jar_fluid": "瓶内液体",
是否和 jar 有关？

2022-03-07 11:09 UTC, ChuijkYahus commented on projects/1.18/assets/supplementaries/supplementaries/lang/zh_cn.json
> +  "fluid.supplementaries.jar_fluid": "瓶内液体",
改了

2022-03-08 11:29 UTC, merged