[R] Epic Fight 史诗战斗更新 #CFPA-990556711043227
CFPAOrg/Minecraft-Mod-Language-Package pull request #1619
Opened 2022-03-08 17:47 UTC by mamaruo

Co-authored-by: 拒绝山麻楂 <2269509324@qq.com>

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-10 10:36 UTC, Cyl18 requested changes

2022-03-10 10:36 UTC, Cyl18 commented on projects/1.16/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"gui.epicfight.auto_preparation.tooltip": "玩家收到攻击时自动切换至战斗模式",
```suggestion
	"gui.epicfight.auto_preparation.tooltip": "玩家受到攻击时自动切换至战斗模式",
```

2022-03-10 10:39 UTC, Cyl18 approved these changes

2022-03-10 10:40 UTC, Cyl18 commented on projects/1.16/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"epicfight.gui.to_mining_mode": "切换至采集(通常)模式",
```suggestion
	"epicfight.gui.to_mining_mode": "切换至采集（通常）模式",
```

2022-03-10 17:43 UTC, Cyl18 commented on projects/1.16/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"skill.epicfight.technician.tooltip": "闪避时，根据敌人的攻击时机不同增加耐力消耗",
增加耐力消耗...?

2022-03-10 19:38 UTC, n0099 commented on projects/1.16/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"skill.epicfight.technician.tooltip": "闪避时，根据敌人的攻击时机不同增加耐力消耗",
```suggestion
	"skill.epicfight.technician.tooltip": "如果您躲开了敌人的攻击时机可以避免消耗耐力",
```

2022-03-11 17:32 UTC, mamaruo commented on projects/1.16/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"skill.epicfight.technician.tooltip": "闪避时，根据敌人的攻击时机不同增加耐力消耗",
```suggestion
	"skill.epicfight.technician.tooltip": "如果你躲开了敌人的攻击时机可以避免消耗耐力",
```

2022-03-12 08:10 UTC, merged