[R] UNU Parts Pack [MTS] 新增 来自工单#CFPA-0600
CFPAOrg/Minecraft-Mod-Language-Package pull request #1626
Opened 2022-03-10 18:33 UTC by mamaruo

Co-Authored-By: Annijang <75552974+Annijang@users.noreply.github.com>

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-10 19:35 UTC, n0099 requested changes

2022-03-10 19:35 UTC, n0099 commented on projects/1.12.2/assets/unu-parts-pack/unuparts/lang/zh_cn.lang
> +item.unuparts.unuparts_instrument_unu_multi_1.name=§3UNU 多种规格
```suggestion
item.unuparts.unuparts_instrument_unu_multi_1.name=§3UNU 万用表™
```

2022-03-10 19:35 UTC, n0099 commented on projects/1.12.2/assets/unu-parts-pack/unuparts/lang/zh_cn.lang
> +item.unuparts.unuparts_decor_unu_paint_silver.name=银色油漆桶
```suggestion
item.unuparts.unuparts_decor_unu_paint_silver.name=淡灰色油漆桶
```
如果是原版16色那silver实际上是淡灰

2022-03-11 05:01 UTC, mamaruo commented
应工单提交者要求，转为 Draft。

2022-03-22 09:51 UTC, XiaoXin1113 requested changes

2022-03-22 09:51 UTC, XiaoXin1113 commented on projects/1.12.2/assets/unu-parts-pack/unuparts/lang/zh_cn.lang
> +item.unuparts.unuparts_decor_unu_container_spagetti.name=§3UNU 货箱 (Spaghetti) §7(装饰)
Spaghetti是意大利面（不管多离奇，他都是意大利面）

2022-03-22 09:51 UTC, XiaoXin1113 commented on projects/1.12.2/assets/unu-parts-pack/unuparts/lang/zh_cn.lang
> +item.unuparts.unuparts_part_unu_container_spagetti.name=§3UNU 货箱 (Spaghetti)
同上，意大利面

2022-03-22 09:51 UTC, XiaoXin1113 commented on projects/1.12.2/assets/unu-parts-pack/unuparts/lang/zh_cn.lang
> +item.unuparts.unuparts_instrument_unu_temp_f1.description=温度计 (Ferenhiet)
Ferenhiet 华氏度或者 ℉

2022-04-12 02:03 UTC, Rinko1231 reviewed
`Spaghetti`在交通方面有`立交桥`的寓意，这似乎是用面条来形容道路。
可能要游戏里看一下

2022-12-23 02:59 UTC, Annijang commented
> @Annijang这个pr怎么办......
> 
> （终于有一个理论可以联系起来工作了）

怎么了？

2022-12-23 03:59 UTC, dovisutu commented
如果我没看错的话，这个pr是你在工单上提交的吧......（虽然工单已经没了）
不过问题是估计你没有修改权限（因为不是用你的github库交的）

那么，是重新建一个pr，还是就用这个，还是干脆不提交了？

2022-12-23 09:50 UTC, Annijang commented
> 如果我没看错的话，这个pr是你在工单上提交的吧……（虽然工单已经没有了） 不过问题是估计你没有修改权限（因为不是用你的github库交的）
> 
> 那么，是重建一个pr，还是就用这个，还是干脆不提交了？

噢噢，记起来了，好久之前我做的汉化，现在我不想做模组汉化了，遇到一些硬编码的模组费时还不讨好，现在我都是汉化数据包。你要是想的话你可以去重建一个pr。

2022-12-24 01:26 UTC, dovisutu commented
那我把这个关了吧

2022-12-24 01:27 UTC, closed without merging