[R] Subterranean Wilderness 新增 #CFPA-0601
CFPAOrg/Minecraft-Mod-Language-Package pull request #1627
Opened 2022-03-10 18:41 UTC by mamaruo

Co-authored-by: 素雪飘零 <1347538547@qq.com>

- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-10 19:33 UTC, n0099 approved these changes

2022-03-11 05:00 UTC, Cyl18 requested changes
还有好多key和英文原文的大小写对不上

2022-03-11 05:29 UTC, Cyl18 commented on projects/1.16/assets/subterranean-wilderness/subwild/lang/zh_cn.json
> +	"block.subwild.granite_speleothem": "花岗石柱",
```suggestion
	"block.subwild.granite_speleothem": "花岗岩柱",
```

2022-03-11 05:39 UTC, Cyl18 requested changes

2022-03-11 05:39 UTC, Cyl18 commented on projects/1.16/assets/subterranean-wilderness/subwild/lang/zh_cn.json
> +	"block.subwild.granite_speleothem": "花岗石柱",
```suggestion
	"block.subwild.granite_speleothem": "花岗岩柱",
```

2022-03-11 05:39 UTC, Cyl18 commented on projects/1.16/assets/subterranean-wilderness/subwild/lang/zh_cn.json
> +	"block.subwild.molten_granite": "熔化花岗石",
```suggestion
	"block.subwild.molten_granite": "熔化花岗岩",
```

2022-03-11 05:39 UTC, Cyl18 commented on projects/1.16/assets/subterranean-wilderness/subwild/lang/zh_cn.json
> +	"block.subwild.hot_smooth_sandstone": "热光滑砂岩",
```suggestion
	"block.subwild.hot_smooth_sandstone": "热平滑砂岩",
```
和原版保持一致

2022-03-11 05:39 UTC, Cyl18 commented on projects/1.16/assets/subterranean-wilderness/subwild/lang/zh_cn.json
> +	"block.subwild.terracotta_emerald_ore": "红色陶瓦绿宝石矿石",
```suggestion
	"block.subwild.terracotta_emerald_ore": "陶瓦绿宝石矿石",
```
上下文一致

2022-03-11 05:39 UTC, Cyl18 commented on projects/1.16/assets/subterranean-wilderness/subwild/lang/zh_cn.json
> +	"block.subwild.light_gray_terracotta_emerald_ore": "浅灰色陶瓦绿宝石矿石",
```suggestion
	"block.subwild.light_gray_terracotta_coal_ore": "淡灰色陶瓦煤矿石",
	"block.subwild.light_gray_terracotta_iron_ore": "淡灰色陶瓦铁矿石",
	"block.subwild.light_gray_terracotta_gold_ore": "淡灰色陶瓦金矿石",
	"block.subwild.light_gray_terracotta_lapis_ore": "淡灰色陶瓦青金石矿石",
	"block.subwild.light_gray_terracotta_redstone_ore": "淡灰色陶瓦红石矿石",
	"block.subwild.light_gray_terracotta_diamond_ore": "淡灰色陶瓦钻石矿石",
	"block.subwild.light_gray_terracotta_emerald_ore": "淡灰色陶瓦绿宝石矿石",
```

2022-03-11 05:49 UTC, mamaruo commented
@Cyl18 有些明显错误可以直接 push，代交工单很多工单作者都不出面的。
![image](https://user-images.githubusercontent.com/37480168/157810003-82d7fba0-5310-4eab-8b00-e603eb67ea02.png)

2022-03-11 23:00 UTC, Cyl18 approved these changes

2022-03-12 04:34 UTC, n0099 approved these changes

2022-03-12 10:07 UTC, mamaruo commented
Self-approved

2022-03-12 17:33 UTC, mamaruo commented on projects/1.16/assets/subterranean-wilderness/subwild/lang/zh_cn.json
> +	"block.subwild.smooth_sandstone_coal_ore": "平滑砂岩煤矿",
这里矿与矿石不统一，用意为何

2022-03-12 19:03 UTC, mamaruo reviewed
太直球了有些翻译

2022-03-12 19:06 UTC, mamaruo commented on projects/1.16/assets/subterranean-wilderness/subwild/lang/zh_cn.json
> +	"itemGroup.subwild": "Subterranean Wilderness",
```suggestion
	"itemGroup.subwild": "地下荒野",
```

2022-03-13 01:52 UTC, n0099 commented on projects/1.16/assets/subterranean-wilderness/subwild/lang/zh_cn.json
> +	"block.subwild.stone_speleothem": "石柱",
这词意译太长，要不用quark里的吧：
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/14b1cc24dd37e10275266058a94c5110d3fbc55e/projects/1.12.2/assets/quark/quark/lang/zh_cn.lang#L601-L610
当然别的mod也有用这个意译的
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/da76b0f6fb604dca3c25160419982c7aa4d28522/projects/1.16/assets/darker-depths/darkerdepths/lang/zh_cn.json#L142-L145

2022-03-13 05:54 UTC, mamaruo commented on projects/1.16/assets/subterranean-wilderness/subwild/lang/zh_cn.json
> +	"block.subwild.stone_speleothem": "石柱",
我也在想太长的问题，不过，高强度低合金也算比较长的了。

2022-03-13 06:10 UTC, TartaricAcid commented
石柱没问题吧？
![1](https://user-images.githubusercontent.com/19620085/158047400-7308f8d2-fbff-4025-ae95-6cc8aec18c1a.png)

2022-03-13 12:01 UTC, n0099 commented on projects/1.16/assets/subterranean-wilderness/subwild/lang/zh_cn.json
> +	"block.subwild.stone_speleothem": "石柱",
[HSLA钢](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1616#issuecomment-1063895683)我不评价

2022-03-13 12:01 UTC, n0099 commented
> 石柱没问题吧？ ![1](https://user-images.githubusercontent.com/19620085/158047400-7308f8d2-fbff-4025-ae95-6cc8aec18c1a.png)

建议学quark的钟乳石

2022-03-13 16:12 UTC, mamaruo commented on projects/1.16/assets/subterranean-wilderness/subwild/lang/zh_cn.json
> +	"block.subwild.stone_speleothem": "石柱",
### 钟乳石
> 钟乳石由[碳酸钙](https://zh.wikipedia.org/wiki/%E7%A2%B3%E9%85%B8%E9%92%99)和其他矿物质的沉积形成。
[维基百科](https://zh.wikipedia.org/wiki/%E9%92%9F%E4%B9%B3%E7%9F%B3)

> 溶洞顶部向下增长的碳酸钙淀积物。
[术语在线](https://www.termonline.cn/word/239502/1#s1)

- 模组里面那么多种“钟乳石”不全是碳酸钙。
- 模组中不管从下往上长的[石笋](https://www.termonline.cn/word/239507/1#s1)，还是反过来长的钟乳石，还是两者合一的[石柱](https://www.termonline.cn/word/239513/1#s1)，都用的这个方块。我评论的图一中就有这三种形态的Speleothem，不过砂岩背景不太明显。

### 洞穴化学淀积物
> 英语名：	speleothem
定义：	溶洞裂隙渗流水作用造成的各种次生矿物淀积物的通称。
[术语在线](https://www.termonline.cn/word/239498/1#s1)
这一“通称”完美解决钟乳石的两个问题。

我的 suggested change 中删去了“化学”二字，以免冗长。其实连“洞穴”都能删了（Wzug 意见），毕竟这玩意不在洞穴还能在哪。

2022-03-13 17:55 UTC, n0099 commented on projects/1.16/assets/subterranean-wilderness/subwild/lang/zh_cn.json
> +	"block.subwild.stone_speleothem": "石柱",
只能说泛用的代价是抽象

2022-03-14 13:11 UTC, TartaricAcid commented
已经与 quark 统一翻译了

2022-03-14 15:28 UTC, mamaruo commented
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1627#discussion_r825470930
您的意见？
@TartaricAcid

2022-03-16 08:04 UTC, TartaricAcid commented
那就不和 quark 统一了，用 `淀积物` 这个简化的名称吧

2022-03-16 08:06 UTC, TartaricAcid approved these changes

2022-03-17 10:07 UTC, merged