[R]Epic Knights: Shields, Armor and Weapons 史诗骑士：盾牌，盔甲和武器 #CFPA-312491488332814
CFPAOrg/Minecraft-Mod-Language-Package pull request #1629
Opened 2022-03-11 06:30 UTC by TartaricAcid

Co-authored-by: 神烦熊 [1484743232@qq.com](mailto:1484743232@qq.com)

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-11 12:27 UTC, n0099 requested changes
需要在文内统一使用`铁制xx`还是`铁质xx`还是`铁xx`，我倾向最后一个

2022-03-11 12:27 UTC, n0099 commented on projects/1.12.2/assets/epic-knights-armor-and-weapons/magistuarmory/lang/zh_cn.lang
> +item.diamond_katzbalger.name=钻石斗剑
```suggestion
item.bronze_stylet.name=青铜制短剑
item.diamond_katzbalger.name=钻石制斗剑
```

2022-03-11 12:27 UTC, n0099 commented on projects/1.12.2/assets/epic-knights-armor-and-weapons/magistuarmory/lang/zh_cn.lang
> +item.netherite_stylet.name=下界合金短剑
```suggestion
item.netherite_stylet.name=下界合金制短剑
```

2022-03-11 12:27 UTC, n0099 commented on projects/1.12.2/assets/epic-knights-armor-and-weapons/magistuarmory/lang/zh_cn.lang
> +flamebladed.hurt=造成无法愈合的伤口（流血）
```suggestion
flamebladed.hurt=造成无法愈合的伤口（流血效果）
```

2022-03-11 12:27 UTC, n0099 commented on projects/1.12.2/assets/epic-knights-armor-and-weapons/magistuarmory/lang/zh_cn.lang
> +silvertools.hurt=+2对不死生物的伤害
```suggestion
silvertools.hurt=增加2点对亡灵生物的伤害
```

2022-03-11 14:37 UTC, mamaruo commented
按清秋的意思，直接“材料+物品类别”，不要制或质，直接规避。

必要时用制，坚决不用质。

2022-03-11 15:45 UTC, n0099 commented
> 按清秋的意思，直接“材料+物品类别”，不要制或质，直接规避。
> 
> 必要时用制，坚决不用质。

质的确是misued

2022-03-13 05:35 UTC, mamaruo requested changes

2022-03-13 05:35 UTC, mamaruo commented on projects/1.12.2/assets/epic-knights-armor-and-weapons/magistuarmory/lang/zh_cn.lang
> +item.diamond_stylet.name=钻石短剑
Review text

2022-03-13 11:55 UTC, n0099 commented on projects/1.12.2/assets/epic-knights-armor-and-weapons/magistuarmory/lang/zh_cn.lang
> +item.bronze_ranseur.name=青铜三叉戟
ranseur应该叫镋钯

2022-03-13 12:30 UTC, Rinko1231 commented on projects/1.12.2/assets/epic-knights-armor-and-weapons/magistuarmory/lang/zh_cn.lang
> +item.bronze_ranseur.name=青铜三叉戟
> ranseur应该叫镋钯

不妥，[镋钯]为中国古代兵器，由农具演变而来，虽然有几分相似，给西方中世纪武器用不免令人费解。如果你说百度的第一条就是[镋钯]，那搜狗第一条就是三叉矛（

2022-03-13 14:26 UTC, n0099 commented on projects/1.12.2/assets/epic-knights-armor-and-weapons/magistuarmory/lang/zh_cn.lang
> +item.bronze_ranseur.name=青铜三叉戟
[zhwiki](https://zh.wikipedia.org/wiki/%E9%92%82%E9%88%80)用的这个译名，这下中英对照了

2022-03-13 14:47 UTC, TartaricAcid commented on projects/1.12.2/assets/epic-knights-armor-and-weapons/magistuarmory/lang/zh_cn.lang
> +item.bronze_ranseur.name=青铜三叉戟
我赞同三叉矛，形象而且容易理解

2022-03-13 15:47 UTC, mamaruo commented on projects/1.12.2/assets/epic-knights-armor-and-weapons/magistuarmory/lang/zh_cn.lang
> +item.bronze_ranseur.name=青铜三叉戟
支持三叉矛。补充一点原因：<s>这字不好读。</s>

经查得如下信息：

“镋钯”我在知网寻得一篇论文：[苗族濒危体育文化遗产镋钯传承的人类学调查 - 中国知网](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2019&filename=QHMJ201804017&uniplatform=NZKPT&v=-Y4MYFdGAu4KNjZSof8APoVd4vaYRe013bq7maZ8h1tUHnlLIOpe4JXombJlfKpR)，而“三叉矛”没有。
<hr style="border:3 double" width="80%" align="left">
<details><summary>图片（点击展开/收起）</summary>
<hr style="border:3 double" width="30%" align="left">

![Screenshot_20220313-233851](https://user-images.githubusercontent.com/37480168/158067601-b1a02722-233e-4ea1-a283-0b843898de53.jpg)

![Screenshot_20220313-233851](https://user-images.githubusercontent.com/37480168/158067619-e41a8677-eab0-47ee-8725-40388d440d40.jpg)

![Screenshot_20220313-234026](https://user-images.githubusercontent.com/37480168/158067624-baf33d76-4637-4257-94ee-9ee78ddad1e2.jpg)

</details><hr style="border:3 double" width="80%" align="left">


[ranseur - Chinese Translation - 吕氏英汉字典](http://www.lexiconer.com/translate/ranseur#.Yi4O599ByCg)

2022-03-13 16:25 UTC, TartaricAcid commented
修改补充说明
- `stylet`：mcmod 百科为`匕首`，实际为非常细的剑，翻译成了`小剑`（好像`细剑`也可以，但是和`刺剑`是不是重复了？）
- `铠甲` -> `胸甲`：和原版翻译统一
- `链甲片` -> `锁子甲`：`锁子甲`这个称呼更常见吧？我没搜到叫`链甲片`这种称呼
- 旗帜图案部分我修改了原作者标点符号书写方式，引号总觉得很奇怪，还是冒号更加合适

2022-03-13 16:54 UTC, mamaruo commented
没时间细看，就不 approve 了

2022-03-13 18:00 UTC, n0099 commented on projects/1.12.2/assets/epic-knights-armor-and-weapons/magistuarmory/lang/zh_cn.lang
> +item.bronze_ranseur.name=青铜三叉戟
我是复制粘贴的，都打不出来
gt玩家还可能会把镋钯当作什么合金

2022-03-13 18:01 UTC, n0099 commented
没时间细看，就不发表意见了

2022-03-13 18:07 UTC, n0099 commented
stylet建议细剑（如果他长度也短）
原版旗帜图案用的是换行表达（https://minecraft.fandom.com/zh/wiki/%E6%97%97%E5%B8%9C%E5%9B%BE%E6%A1%88#.E5.90.88.E6.88.90 鼠标悬浮在物品图标上看tooltips），我们不能直接加tooltips，但可以写个\n进去吗？

2022-03-14 08:59 UTC, SFXiongod commented
啊，我是那个汉化文件的作者，就是我来说一下‘链甲片’，当初我翻译用链甲片制作的护具的时候用了批量修改，忘记删掉‘片’这个字了，所以看着就会很奇怪，正确的应该是链甲护具，若要改成锁子甲并不妥，锁子甲和链甲是两种护具，实际游戏中这套护具的设计的确是链甲。

2022-03-14 13:16 UTC, TartaricAcid commented
@n0099 原版文本换行都是代码实现的，仅语言文件强行塞换行符没用。

2022-03-14 13:20 UTC, TartaricAcid commented
@SFXiongod 我已经修改了全部问题，你再看看，没问题我就入库了

2022-03-14 14:10 UTC, SFXiongod commented
我这边是完全没问题了

2022-03-14 22:06 UTC, n0099 approved these changes

2022-03-16 08:07 UTC, merged