[R] Ancient Beasts #CFPA-597973352142162
CFPAOrg/Minecraft-Mod-Language-Package pull request #1630
Opened 2022-03-11 07:23 UTC by TartaricAcid

Co-authored-by: 奎木二哈 [silhouettelai@gmail.com](mailto:silhouettelai@gmail.com)
- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-11 12:16 UTC, n0099 requested changes

2022-03-11 12:16 UTC, n0099 commented on projects/1.12.2/assets/ancient-beasts/ancientbeasts/lang/zh_cn.lang
> +subtitles.damcell_idle=铁处女：被击打
```suggestion
subtitles.vessel_hurt=剧场人偶：受到伤害
subtitles.vessel_death=剧场人偶：死亡
subtitles.lil_v_hurt=小人偶：受到伤害
subtitles.lil_v_death=小人偶：死亡
subtitles.lil_v_activate=小人偶：开始巡逻
subtitles.lil_v_deactivate=小人偶：停止巡逻
subtitles.damcell_idle=铁处女：受到伤害
```

2022-03-12 15:20 UTC, mamaruo commented
官方PR（应该是同一人）：https://github.com/Un-Original1/AncientBeasts/pull/8

2022-03-12 15:56 UTC, mamaruo requested changes

2022-03-12 15:56 UTC, mamaruo commented on projects/1.12.2/assets/ancient-beasts/ancientbeasts/lang/zh_cn.lang
> +entity.Damcell.name=铁处女
铁处女是一种（疑为虚构的）刑具，作为实体名是否不妥

2022-03-12 15:56 UTC, mamaruo commented on projects/1.12.2/assets/ancient-beasts/ancientbeasts/lang/zh_cn.lang
> +item.sandmonster_scale.name=女妖鳞屑
“屑”字从何而来？

2022-03-12 15:56 UTC, mamaruo commented on projects/1.12.2/assets/ancient-beasts/ancientbeasts/lang/zh_cn.lang
> +item.charred_cloak.name=炭黑斗篷
两个 Charred 翻译不同用意为何？

2022-03-13 01:43 UTC, n0099 commented on projects/1.12.2/assets/ancient-beasts/ancientbeasts/lang/zh_cn.lang
> +item.sandmonster_scale.name=女妖鳞屑
人间之屑（迫真）

2022-03-13 03:25 UTC, KMEHSilhouette commented on projects/1.12.2/assets/ancient-beasts/ancientbeasts/lang/zh_cn.lang
> +entity.Damcell.name=铁处女
请到游戏中看一下Damcell的样子， 从各种角度来看个人认为翻译为铁处女比较妥当
![image](https://user-images.githubusercontent.com/101187977/158043677-be63a0aa-36e1-423a-9af5-32e8db76c37b.png)

2022-03-13 03:31 UTC, KMEHSilhouette commented on projects/1.12.2/assets/ancient-beasts/ancientbeasts/lang/zh_cn.lang
> +subtitles.damcell_idle=铁处女：被击打
收到， 现在调整

2022-03-13 03:33 UTC, KMEHSilhouette commented on projects/1.12.2/assets/ancient-beasts/ancientbeasts/lang/zh_cn.lang
> +item.charred_cloak.name=炭黑斗篷
收到，现在修改

2022-03-13 06:23 UTC, mamaruo commented on projects/1.12.2/assets/ancient-beasts/ancientbeasts/lang/zh_cn.lang
> +entity.Damcell.name=铁处女
OK

2022-03-13 11:51 UTC, TartaricAcid commented on projects/1.12.2/assets/ancient-beasts/ancientbeasts/lang/zh_cn.lang
> +item.sandmonster_scale.name=女妖鳞屑
改成 女妖鳞片 更加合适

2022-03-13 11:56 UTC, n0099 approved these changes

2022-03-14 02:23 UTC, KMEHSilhouette commented on projects/1.12.2/assets/ancient-beasts/ancientbeasts/lang/zh_cn.lang
> +item.sandmonster_scale.name=女妖鳞屑
已在原pr文件上修改

2022-03-14 13:26 UTC, merged