[R] More Crafting Tables for Forge! 新增 #CFPA-0603
CFPAOrg/Minecraft-Mod-Language-Package pull request #1633
Opened 2022-03-11 16:54 UTC by mamaruo

https://www.curseforge.com/minecraft/mc-mods/more-crafting-tables-for-forge

- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-12 16:06 UTC, Cyl18 approved these changes

2022-03-12 16:20 UTC, dovisutu requested changes
typo

2022-03-12 16:20 UTC, dovisutu commented on projects/1.16/assets/more-crafting-tables-for-forge/mctb/lang/zh_cn.json
> +  "block.mctb.jungle_crafting_table": "从林木工作台",
```suggestion
  "block.mctb.jungle_crafting_table": "丛林木工作台",
```

2022-03-12 16:20 UTC, dovisutu commented on projects/1.18/assets/more-crafting-tables-for-forge/mctb/lang/zh_cn.json
> +  "block.mctb.jungle_crafting_table": "从林木工作台",
```suggestion
  "block.mctb.jungle_crafting_table": "丛林木工作台",
```

2022-03-13 02:00 UTC, n0099 requested changes
如果这个mod联动了bop的木头并创建对应版本工作台
那应该同步使用cfpa译名

2022-03-13 05:59 UTC, mamaruo commented
大意了
确实想过联动译名统一问题，但只是想了想（

2022-03-13 10:36 UTC, merged

2022-03-13 11:53 UTC, n0099 commented
> 大意了 确实想过联动译名统一问题，但只是想了想（

主要是方便以后可能的查找替换