[R] Mob Battle Mod（怪物大乱斗） 更新en原文与翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #1638
Opened 2022-03-13 02:41 UTC by n0099

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-13 03:28 UTC, n0099 reviewed
文中所有实体原文是entity，也可以查找替换为生物（对应mod名字的mobbattle）

2022-03-13 03:28 UTC, n0099 commented on projects/1.12.2/assets/mob-battle-mod/mobbattle/lang/zh_CN.lang
> +item.mob_equip.name=生物拾取物品杖
mcmod.cn词条http://web.archive.org/web/20220313031733/https://www.mcmod.cn/item/list/1085-1.html 把Mob Enrager直接译为生物杖，因为物品id叫`mobbattle:mob_stick`，这估计是这mod作者第一个开发的功能
https://en.wiktionary.org/wiki/enrager 说 `First attested in Old French, corresponding to en- +‎ rage +‎ -er.`
![](https://user-images.githubusercontent.com/13030387/158043492-9312fa6e-dfe4-4653-84e6-182cf3f8c817.png)

盔甲编辑杖实际上是编辑这个实体的内部物品栏（当然也包括了盔甲栏）
https://www.curseforge.com/minecraft/mc-mods/mob-battle-mod上作者的图：
![](https://user-images.githubusercontent.com/13030387/158043583-d212da6c-4a18-46d6-81b2-2aa99cd19630.png)

2022-03-13 03:28 UTC, n0099 commented on projects/1.12.2/assets/mob-battle-mod/mobbattle/lang/zh_CN.lang
> +itemGroup.mobbattle=怪物大乱斗
怪物大乱斗是mcmod.cn的取名，我直接拿来用了

2022-03-13 03:28 UTC, n0099 commented on projects/1.18/assets/mob-battle-mod/mobbattle/lang/en_us.json
> +  "itemGroup.mobbattle.tab": "Mob Battle",
1.18跟1.16文件毫无区别，除了这多了个`.tab`

2022-03-13 03:28 UTC, n0099 commented on projects/1.16/assets/mob-battle-mod/mobbattle/lang/zh_cn.json
> +  "tooltip.army.first": "右击方块设定框选的第一个对角线角落方块，再次右击其他方块设定框选的第二个对角线角落方块以完成框选（类似 WorldEdit）",
原文是`Right click block to set first, and then second corner of the box`
我不知道如何简洁说明这个框选流程，其实这跟we的//pos1 //pos2命令（或用小木斧点击方块确定选区）的逻辑是一样的
下面的key `tooltip.equip.first`是相同的

2022-03-13 03:28 UTC, n0099 commented on projects/1.16/assets/mob-battle-mod/mobbattle/lang/zh_cn.json
> +  "tooltip.stick.add": "已选择实体，请选择其他实体作为其攻击目标"
这几句原文就缺少限定形容词，[cf上作者](https://www.curseforge.com/minecraft/mc-mods/mob-battle-mod)说Mob Enrager（`mobbattle:mob_stick`）这个物品的用途是`Make 2 mobs fight each other`

2022-03-13 03:35 UTC, n0099 commented on projects/1.16/assets/mob-battle-mod/mobbattle/lang/zh_cn.json
> +  "conf.mobbattle.addai": "自动添加队伍目标AI",
我不知道什么叫`Auto add team-target-ai`
查阅有关源码（感谢作者开源）：
https://github.com/Flemmli97/MobBattle/blob/e0cadce51aad37e4e270de0719333046768e0b80/forge/src/main/java/io/github/flemmli97/mobbattle/forge/Config.java#L30-L31 这里的文本说是`Auto target mobs from other teams (if e.g. done per command)`，应该是指在每个杖的操作完成后自动让杖操作的实体去攻击其他所有团队的实体（也就是立即认定其他实体都是敌对目标）

实际业务逻辑是
https://github.com/Flemmli97/MobBattle/blob/155b2ef9ac641dddd29b104de4bde59c68fe0979/forge/src/main/java/io/github/flemmli97/mobbattle/forge/handler/EventHandler.java#L51-L52
https://github.com/Flemmli97/MobBattle/blob/6bb1b026eef1054b68773c3b9aa1ce9cbf4b9621/common/src/main/java/io/github/flemmli97/mobbattle/handler/Utils.java#L80-L86

2022-03-13 03:35 UTC, n0099 commented on projects/1.16/assets/mob-battle-mod/mobbattle/lang/zh_cn.json
> +  "tooltip.mount.reset": "已重设选择实体",
文中所有的`*.reset`key我估计都是在重置操作完成后输出的，比如这个的源码是https://github.com/Flemmli97/MobBattle/blob/94a24e5ae5181b33bb9371569a0247c30eab7a6b/common/src/main/java/io/github/flemmli97/mobbattle/items/MobMount.java#L53

2022-03-13 03:42 UTC, n0099 commented on projects/1.16/assets/mob-battle-mod/mobbattle/lang/zh_cn.json
> +  "tooltip.effect.give.add": "已添加持续 %3$s tick 的 %2$s 倍率效果 %1$s",
原文是`Added effect %1$s with amplifier %2$s for %3$s ticks`
tick我觉得不用翻
amplifier译为倍率是根据mcwiki
https://minecraft.fandom.com/wiki/Effect
> Internally, in the /effect command, and in potion Amplifier NBT tags, the game stores an "amplifier" value, which is one less than the displayed level. For example, Strength II has an amplifier value of 1.
> Due to the way this amplifier is stored in NBT, amplifiers of 128 to 255 (levels 129 to 256) in NBT tags (e.g. on potions) are treated as if they were −128 to −1 (levels −127 to 0) respectively.‌[Java Edition only] The /effect command initially applies such amplifiers in their positive-valued sense but this is later converted to the negative-valued interpretation, leading to inconsistent results. In Bedrock Edition, amplifiers above 127 translate to positive levels, like other amplifiers.

> 在游戏内部、命令/effect与药水的修饰NBT标签，游戏保存的是“倍率”（amplifier）值而不是等级。倍率比等级小1，例如力量II的倍率为1。
> 根据NBT中存储倍率的方式，NBT标签（如药水的）中128至255倍率（129至256等级）会被分别识别为−128至−1（−127至0等级）。命令/effect内部应用倍率时会保存为正值的形式，但稍后会被以负值的形式处理，导致不同的结果。但在基岩版，所有效果的NBT标签均会按正值的形式处理，故使用命令/effect添加128至255倍率（129至256等级）的效果不会形成负等级的效果。

2022-03-13 03:59 UTC, n0099 commented
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1638#issuecomment-1066012925
更新的en_us.lang文件来自我刚从cf下的
MobBattleMod-1.12.2-2.3.4.jar
mobbattle-1.16.5-2.3.7.jar
mobbattle-1.18.1-2.4.0-forge.jar

2022-03-13 12:16 UTC, TartaricAcid approved these changes

2022-03-13 16:52 UTC, mamaruo requested changes
小问题

2022-03-13 16:52 UTC, mamaruo commented on projects/1.18/assets/mob-battle-mod/mobbattle/lang/zh_cn.json
> +  "tooltip.stick.add": "已选择实体，请选择其他实体作为其攻击目标"
```suggestion
  "tooltip.stick.add": "首个实体已选择，请选择其他实体作为其攻击目标"
```

2022-03-13 16:52 UTC, mamaruo commented on projects/1.18/assets/mob-battle-mod/mobbattle/lang/zh_cn.json
> +  "tooltip.equip.first": "右击方块设定框选的第一个对角线角落方块，再次右击其他方块设定框选的第二个对角线角落方块以完成框选（类似 WorldEdit）",
```suggestion
  "tooltip.equip.first": "右击方块设定框选的第一个对角线角落方块，再次右击其他方块设定框选的第二个对角线角落方块以完成框选",
```
想不到更好的了

2022-03-13 16:52 UTC, mamaruo commented on projects/1.18/assets/mob-battle-mod/mobbattle/lang/zh_cn.json
> +  "tooltip.spawnegg": "左击实体以存进刷怪蛋，按住潜行可以保存该实体 NBT 数据",
```suggestion
  "tooltip.spawnegg": "左击实体以存进刷怪蛋，按住潜行可以保存该实体NBT数据",
```
空格需要排查

2022-03-13 17:57 UTC, n0099 commented on projects/1.18/assets/mob-battle-mod/mobbattle/lang/zh_cn.json
> +  "tooltip.equip.first": "右击方块设定框选的第一个对角线角落方块，再次右击其他方块设定框选的第二个对角线角落方块以完成框选（类似 WorldEdit）",
有括号里那句可以让用过we的人一眼看懂

2022-03-13 17:57 UTC, n0099 commented on projects/1.18/assets/mob-battle-mod/mobbattle/lang/zh_cn.json
> +  "tooltip.spawnegg": "左击实体以存进刷怪蛋，按住潜行可以保存该实体 NBT 数据",
我不知道到底加不加空格，116和118文件都是加了的

2022-03-13 17:58 UTC, n0099 commented on projects/1.18/assets/mob-battle-mod/mobbattle/lang/zh_cn.json
> +  "tooltip.stick.add": "已选择实体，请选择其他实体作为其攻击目标"
```suggestion
  "tooltip.stick.add": "已选择第一个实体，请选择第二个实体作为其攻击目标"
```
这个杖只能选两个实体让他们互殴，不能选>2个（所以有多选版本和团队）

2022-03-13 17:59 UTC, mamaruo commented on projects/1.18/assets/mob-battle-mod/mobbattle/lang/zh_cn.json
> +  "tooltip.spawnegg": "左击实体以存进刷怪蛋，按住潜行可以保存该实体 NBT 数据",
1.16+不加

2022-03-13 18:53 UTC, n0099 commented on projects/1.18/assets/mob-battle-mod/mobbattle/lang/zh_cn.json
> +  "tooltip.spawnegg": "左击实体以存进刷怪蛋，按住潜行可以保存该实体 NBT 数据",
那就不加

2022-03-14 13:31 UTC, TartaricAcid commented
我看提出的意见都修改好了，我 merge 了

2022-03-15 05:44 UTC, mamaruo commented
我再次反对创世神的注释，其他大体没问题了。

2022-03-16 08:10 UTC, merged

2022-03-16 23:07 UTC, n0099 commented
> 我再次反对创世神的注释，其他大体没问题了。

加了至少可以提醒玩家这逻辑跟we一样，不然这么长一句谁初见读的清啊

2022-03-16 23:08 UTC, n0099 commented on projects/1.18/assets/mob-battle-mod/mobbattle/lang/zh_cn.json
> +  "tooltip.equip.first": "右击方块设定框选的第一个对角线角落方块，再次右击其他方块设定框选的第二个对角线角落方块以完成框选（类似 WorldEdit）",
> we不是一个左键一个右键吗

是