[R]
CFPAOrg/Minecraft-Mod-Language-Package pull request #1642
Opened 2022-03-13 05:49 UTC by mamaruo

Co-Authored-By: Rinko1231 <89371859+Rinko1231@users.noreply.github.com>

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-13 12:00 UTC, n0099 requested changes

2022-03-13 12:00 UTC, n0099 commented on projects/1.16/assets/epic-knights-armor-and-weapons/magistuarmory/lang/zh_cn.json
> +  "item.magistuarmory.bronze_ranseur": "青铜三叉矛",
根据@Rinko1231 的意见：https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1629#discussion_r825392440 ，ranseur应该叫镋钯

2022-03-14 14:29 UTC, TartaricAcid commented
已经多次检查，与 #1629 同步了翻译

2022-03-14 22:04 UTC, n0099 commented on projects/1.16/assets/epic-knights-armor-and-weapons/magistuarmory/lang/zh_cn.json
> +  "item.magistuarmory.two-headed_eagle_pattern": "旗帜图案"
为什么删了

2022-03-16 08:10 UTC, merged

2022-03-16 08:11 UTC, TartaricAcid commented on projects/1.16/assets/epic-knights-armor-and-weapons/magistuarmory/lang/zh_cn.json
> +  "item.magistuarmory.two-headed_eagle_pattern": "旗帜图案"
1.12 和 1.16 不一样，1.16 是作者代码加了 tooltips，和原版设计一致。