[R] Cultural Delights 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1644
Opened 2022-03-13 15:41 UTC by ChuijkYahus

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-13 15:56 UTC, ChuijkYahus commented
赞美新bot

2022-03-13 17:13 UTC, iouter approved these changes

2022-03-13 17:15 UTC, iouter commented
查了一下，有把avocado翻译成牛油果的，也有翻译成鳄梨的。不过这是否需要统一，统一成什么应另行讨论。

2022-03-13 18:04 UTC, n0099 commented
> 查了一下，有把avocado翻译成牛油果的，也有翻译成鳄梨的。不过这是否需要统一，统一成什么应另行讨论。

建议统一凤梨与菠萝

2022-03-13 18:08 UTC, n0099 requested changes

2022-03-13 18:08 UTC, n0099 commented on projects/1.16/assets/cultural-delights/culturaldelights/lang/zh_cn.json
> +  "block.culturaldelights.avocado_bundle": "牛油果捆",
```suggestion
  "block.culturaldelights.avocado_bundle": "捆装牛油果",

```

2022-03-13 18:19 UTC, iouter commented
> > 查了一下，有把avocado翻译成牛油果的，也有翻译成鳄梨的。不过这是否需要统一，统一成什么应另行讨论。
> 
> 建议统一凤梨与菠萝

这与凤梨/菠萝不同，只有5个mod的条目被翻译成了凤梨，而其他33个mod全部使用菠萝。鳄梨/牛油果的使用比例大致为四六开。

> 
> [百度百科词条](https://baike.baidu.com/item/%E9%B3%84%E6%A2%A8/1414596)说
> 
> > 注：鳄梨也是日常在沙拉、饮料中添加的“牛油果”。而山榄科牛油果属的植物[乳木果](https://baike.baidu.com/item/%E4%B9%B3%E6%9C%A8%E6%9E%9C/10019407)的提取物，作为化妆品添加剂在中国国家药监局的《已使用化妆品原料目录（2021年版）》中被称为“牛油果”，造成了这两种植物在概念上出现了混淆。[9]
> 
> [enwiki条目](https://en.wikipedia.org/wiki/Avocado)说：
> 
> > It is known as "butter fruit" in parts of India.[33]
> 
> 我认为用牛油果这个俗名更好

总之，让我们另开issue讨论。

2022-03-14 14:34 UTC, TartaricAcid approved these changes

2022-03-14 22:00 UTC, n0099 approved these changes

2022-03-16 08:12 UTC, merged