[R] Industrial Magic - Crossover IC2 #CFPA-0611
CFPAOrg/Minecraft-Mod-Language-Package pull request #1645
Opened 2022-03-13 17:24 UTC by mamaruo

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-13 17:29 UTC, mamaruo commented
与官方的简单对比：
![image](https://user-images.githubusercontent.com/37480168/158071666-7b601af5-85d2-45e5-a060-5abf0ed922f7.png)
![image](https://user-images.githubusercontent.com/37480168/158071689-a7585e9b-2afa-4af8-8a24-8f8068edc293.png)
![image](https://user-images.githubusercontent.com/37480168/158071706-f9370a71-9223-4046-a3ad-0339f9528e3a.png)
![image](https://user-images.githubusercontent.com/37480168/158071713-706b3adb-7a6b-4028-82f3-fc0234b422d6.png)
![image](https://user-images.githubusercontent.com/37480168/158071714-65fdec45-435d-46ea-97e6-41c0bba065f6.png)

2022-03-13 18:07 UTC, n0099 commented
> 与官方的简单对比

怎么差这么多，key都不同

2022-03-14 10:38 UTC, RuiXuqi commented
我来说一下吧
这个官方直接把1.7.10的汉化复制过来了
相当于没有汉化

2022-03-14 10:40 UTC, RuiXuqi commented
1.12.2的id和1.7.10是完全不同的
用官方汉化进游戏全是英文
官方汉化也有点问题

2022-03-14 22:07 UTC, n0099 commented
那就不管官方

2022-03-14 22:12 UTC, n0099 requested changes

2022-03-14 22:12 UTC, n0099 commented on projects/1.12.2/assets/im-crossover-ic2/emt/lang/zh_cn.lang
> +tooltip.EMT.hammer.electric=Greate Player 的雷神之锤。
```suggestion
tooltip.EMT.hammer.electric=Greate Player 的雷神之锤
```

2022-03-14 22:12 UTC, n0099 commented on projects/1.12.2/assets/im-crossover-ic2/emt/lang/zh_cn.lang
> +research_stage.emt:generator.2=是的，已经做完了。
原文的`Yes, It`s done and`后面还有别的文本吗

2022-03-14 22:12 UTC, n0099 commented on projects/1.12.2/assets/im-crossover-ic2/emt/lang/zh_cn.lang
> +research_stage.emt:ga.2=是的，已经做完了。我可以用 Aer 源质发电。
```suggestion
research_stage.emt:ga.2=是的，已经完成了。现在可以使用 Aer 源质发电。
```

2022-03-14 22:12 UTC, n0099 commented on projects/1.12.2/assets/im-crossover-ic2/emt/lang/zh_cn.lang
> +research_stage.emt:gf.2=是的，已经做完了。我可以用 Ignis 源质发电。
```suggestion
research_stage.emt:gf.2=是的，已经完成了。现在可以使用 Ignis 源质发电。
```

2022-03-14 22:12 UTC, n0099 commented on projects/1.12.2/assets/im-crossover-ic2/emt/lang/zh_cn.lang
> +research_stage.emt:gaur.2=是的，已经做完了。我可以用 Auram 源质发电。
```suggestion
research_stage.emt:gaur.2=是的，已经完成了。现在可以使用 Auram 源质发电。
```

2022-03-14 22:12 UTC, n0099 commented on projects/1.12.2/assets/im-crossover-ic2/emt/lang/zh_cn.lang
> +research_stage.emt:armor.1=新型盔甲。
```suggestion
research_stage.emt:armor.1=新型盔甲
```
原文没有.

2022-03-14 22:12 UTC, n0099 commented on projects/1.12.2/assets/im-crossover-ic2/emt/lang/zh_cn.lang
> +research_stage.emt:wings.2=我在做新型羽翼。
```suggestion
research_stage.emt:wings.2=我在做新型羽翼
```
原文没有.

2022-03-14 22:12 UTC, n0099 commented on projects/1.12.2/assets/im-crossover-ic2/emt/lang/zh_cn.lang
> +research_stage.emt:wings_b.1=我制造了新式羽翼。
```suggestion
research_stage.emt:wings_b.1=我制造了新式羽翼
```
原文没有.

2022-03-15 16:02 UTC, RuiXuqi commented on projects/1.12.2/assets/im-crossover-ic2/emt/lang/zh_cn.lang
> +research_stage.emt:generator.2=是的，已经做完了。
没了

2022-03-17 01:44 UTC, n0099 commented on projects/1.12.2/assets/im-crossover-ic2/emt/lang/zh_cn.lang
> +research_stage.emt:generator.2=是的，已经做完了。
```suggestion
research_stage.emt:generator.2=是的，已经做完了……
```

2022-03-17 01:44 UTC, n0099 commented on projects/1.12.2/assets/im-crossover-ic2/emt/lang/zh_cn.lang
> +research_stage.emt:wings_b.1=我制造了新式羽翼。
> 统一回复一下句号问题吧 这几个地方都是游戏内以句子的形式存在的 不是名字

是tooltips?

2022-03-17 23:30 UTC, mamaruo commented on projects/1.12.2/assets/im-crossover-ic2/emt/lang/zh_cn.lang
> +research_stage.emt:wings_b.1=我制造了新式羽翼。
> 统一回复一下句号问题吧 这几个地方都是游戏内以句子的形式存在的 不是名字

@RuiXuqi 尊重原文比较好。

2022-03-18 15:58 UTC, TartaricAcid approved these changes

2022-03-18 15:58 UTC, merged

2022-03-20 15:59 UTC, RuiXuqi commented on projects/1.12.2/assets/im-crossover-ic2/emt/lang/zh_cn.lang
> +research_stage.emt:gaur.2=是的，已经做完了。我可以用 Auram 源质发电。
ok，这样感觉更好一点

2022-03-20 16:04 UTC, n0099 commented on projects/1.12.2/assets/im-crossover-ic2/emt/lang/zh_cn.lang
> +research_stage.emt:gaur.2=是的，已经做完了。我可以用 Auram 源质发电。
都merge了

2022-10-11 08:53 UTC, mamaruo commented
官方的是3年前的老家伙了

n0099 ***@***.***> 于2022年3月14日周一 02:08写道：

> 与官方的简单对比
>
> 怎么差这么多，key都不同
>