[R]Upgraded Netherite : Creativerite的翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1664
Opened 2022-03-16 11:48 UTC by NianGuu

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-16 13:29 UTC, Cyl18 commented on projects/1.18/assets/upgraded-netherite-creativerite/upgradednetherite_creative/lang/zh_cn.json
> +  "upgradednetherite_creative.Creative_Bonus_Weapon.TT": "§7• §6瞬间秒杀§7.",
`瞬间秒杀` 很怪 `瞬`和`秒`语义上有重复
建议：`瞬间击杀`

2022-03-16 15:07 UTC, Cyl18 commented on projects/1.18/assets/upgraded-netherite-creativerite/upgradednetherite_creative/lang/zh_cn.json
> +  "upgradednetherite.SetBonus.TT": "§a§l套装增益",
原文的`(%1$s§a§l)`怎么被删了

2022-03-16 16:42 UTC, Cyl18 commented on projects/1.18/assets/upgraded-netherite-creativerite/upgradednetherite_creative/lang/zh_cn.json
> +  "upgradednetherite_creative.Creative_Bonus2.TT": "§7• §6无法损坏§7.",
这个有没有更好一点的译法呢

2022-03-16 16:43 UTC, Cyl18 approved these changes

2022-03-16 23:10 UTC, n0099 approved these changes

2022-03-16 23:10 UTC, n0099 commented on projects/1.18/assets/upgraded-netherite-creativerite/upgradednetherite_creative/lang/zh_cn.json
> +  "upgradednetherite_creative.Creative_Bonus2.TT": "§7• §6无法损坏§7.",
这是用于tooltips的吧，上下文应该没问题

2022-03-17 16:47 UTC, mamaruo requested changes

2022-03-17 16:47 UTC, mamaruo commented on projects/1.18/assets/upgraded-netherite-creativerite/upgradednetherite_creative/lang/zh_cn.json
> +  "upgradednetherite.WhenBlocking.TT": "§e§l格挡时"
1.18 还有格挡吗

2022-03-17 16:47 UTC, mamaruo commented on projects/1.18/assets/upgraded-netherite-creativerite/upgradednetherite_creative/lang/zh_cn.json
> +  "upgradednetherite.SetBonus.TT": "§a§l套装增益(%1$s§a§l)",
```suggestion
  "upgradednetherite.SetBonus.TT": "§a§l套装增益（%1$s§a§l）",
```

2022-03-17 16:47 UTC, mamaruo commented on projects/1.18/assets/upgraded-netherite-creativerite/upgradednetherite_creative/lang/zh_cn.json
> +  "upgradednetherite_creative.Creative_Bonus3.TT": "§7• §6免疫异常状态§7.",
`No Harmful Effect`
没理解这一个

2022-03-17 17:35 UTC, Cyl18 commented on projects/1.18/assets/upgraded-netherite-creativerite/upgradednetherite_creative/lang/zh_cn.json
> +  "upgradednetherite_creative.Creative_Bonus3.TT": "§7• §6免疫异常状态§7.",
直译 `免疫有害的状态效果` ?

2022-03-17 17:36 UTC, Cyl18 commented on projects/1.18/assets/upgraded-netherite-creativerite/upgradednetherite_creative/lang/zh_cn.json
> +  "upgradednetherite.WhenBlocking.TT": "§e§l格挡时"
参考一下游戏内这一条？

2022-03-17 19:07 UTC, n0099 commented on projects/1.18/assets/upgraded-netherite-creativerite/upgradednetherite_creative/lang/zh_cn.json
> +  "upgradednetherite_creative.Creative_Bonus3.TT": "§7• §6免疫异常状态§7.",
跟上面那条`No Damage`一样的排比

2022-03-18 16:02 UTC, TartaricAcid commented on projects/1.18/assets/upgraded-netherite-creativerite/upgradednetherite_creative/lang/zh_cn.json
> +  "upgradednetherite_creative.Creative_Bonus3.TT": "§7• §6免疫异常状态§7.",
简化下：`免疫有害效果` ，这比 `异常` 用词更加符合原意

2022-03-18 16:04 UTC, TartaricAcid approved these changes

2022-03-18 16:05 UTC, NianGuu commented on projects/1.18/assets/upgraded-netherite-creativerite/upgradednetherite_creative/lang/zh_cn.json
> +  "upgradednetherite_creative.Creative_Bonus3.TT": "§7• §6免疫异常状态§7.",
> 简化下：`免疫有害效果` ，这比 `异常` 用词更加符合原意

感觉上下文都是两个字的，就这个这么长，游戏内会不会显得太突兀不好看

2022-03-19 02:48 UTC, mamaruo approved these changes

2022-03-19 04:04 UTC, merged