[R]Upgraded Netherite : Items的翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1665
Opened 2022-03-16 11:52 UTC by NianGuu

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-16 13:31 UTC, Cyl18 commented on projects/1.18/assets/upgraded-netherite-items/upgradednetherite_items/lang/zh_cn.json
> +  "upgradednetherite_items.Disabled.TT": "§c§lDisabled"
未翻译

2022-03-16 13:33 UTC, NianGuu commented on projects/1.18/assets/upgraded-netherite-items/upgradednetherite_items/lang/zh_cn.json
> +  "upgradednetherite_items.Disabled.TT": "§c§lDisabled"
> 未翻译

因为我在游戏内找不到该文本。。

2022-03-16 23:11 UTC, n0099 commented on projects/1.18/assets/upgraded-netherite-items/upgradednetherite_items/lang/zh_cn.json
> +  "upgradednetherite_items.Disabled.TT": "§c§lDisabled"
那就保持en原文

2022-03-16 23:27 UTC, n0099 requested changes

2022-03-16 23:27 UTC, n0099 commented on projects/1.18/assets/upgraded-netherite-items/upgradednetherite_items/lang/zh_cn.json
> +  "upgradednetherite_items.EnderNotSelect.TT": "未选中任何实体!",
```suggestion
  "upgradednetherite_items.EnderRequire.TT": "需要末影珍珠！",
  "upgradednetherite_items.EnderNotSelect.TT": "未选中任何实体！",
```

2022-03-16 23:27 UTC, n0099 commented on projects/1.18/assets/upgraded-netherite-items/upgradednetherite_items/lang/zh_cn.json
> +  "upgradednetherite_items.Netherite_Apple6.TT": "§5§o下界合金幸运 %1$s §5(%2$s§5).",
```suggestion
  "upgradednetherite_items.Netherite_Apple1.TT": "§5§o饥饿 %1$s §5(%2$s§5)",
  "upgradednetherite_items.Netherite_Apple2.TT": "§5§o缓慢 %1$s §5(%2$s§5)",
  "upgradednetherite_items.Netherite_Apple3.TT": "§5§o防火 (%1$s§5)",
  "upgradednetherite_items.Netherite_Apple4.TT": "§5§o下界合金力量 %1$s §5(%2$s§5)",
  "upgradednetherite_items.Netherite_Apple5.TT": "§5§o下界合金抗性提升 %1$s §5(%2$s§5)",
  "upgradednetherite_items.Netherite_Apple6.TT": "§5§o下界合金幸运 %1$s §5(%2$s§5)",
```

2022-03-16 23:27 UTC, n0099 commented on projects/1.18/assets/upgraded-netherite-items/upgradednetherite_items/lang/zh_cn.json
> +  "upgradednetherite_items.Corrupt_Totem2.TT": "§5每一件腐化下界合金装备都可以提供%1$s§5的抗性提升.",
```suggestion
  "upgradednetherite_items.Gold_Totem.TT": "§7• %1$s §6对猪灵的抗性提升§7",
  "upgradednetherite_items.Fire_Totem.TT": "§7• %1$s §6对火焰敌人的抗性提升§7",
  "upgradednetherite_items.Ender_Totem.TT": "§7• %1$s §6对末地敌人的抗性提升§7",
  "upgradednetherite_items.Ender_Totem2.TT": "§7• §6能解救虚空中的人§7",
  "upgradednetherite_items.Water_Totem.TT": "§7• %1$s §6对水中敌人的抗性提升§7",
  "upgradednetherite_items.Wither_Totem.TT": "§7• %1$s §6对凋灵骷髅的抗性提升§7",
  "upgradednetherite_items.Poison_Totem.TT": "§7• %1$s §6对节肢动物的抗性提升§7",
  "upgradednetherite_items.Phantom_Totem.TT": "§7• %1$s §6对幻翼的抗性提升§7",
  "upgradednetherite_items.Feather_Totem.TT": "§7• %1$s §6对幼年敌人的抗性提升§7",
  "upgradednetherite_items.Corrupt_Totem.TT": "§7• %1$s §6抗性提升§7",
  "upgradednetherite_items.Corrupt_Totem2.TT": "§5每一件腐化下界合金装备都可以提供%1$s§5的抗性提升",
```

2022-03-17 00:34 UTC, NianGuu commented on projects/1.18/assets/upgraded-netherite-items/upgradednetherite_items/lang/zh_cn.json
> +  "upgradednetherite_items.Corrupt_Totem2.TT": "§5每一件腐化下界合金装备都可以提供%1$s§5的抗性提升.",
> 

你有没有想过这个§7是干嘛的。。

2022-03-17 01:02 UTC, n0099 commented on projects/1.18/assets/upgraded-netherite-items/upgradednetherite_items/lang/zh_cn.json
> +  "upgradednetherite_items.Corrupt_Totem2.TT": "§5每一件腐化下界合金装备都可以提供%1$s§5的抗性提升.",
> 你有没有想过这个§7是干嘛的。。

单独彩色一个.有什么用

2022-03-17 01:09 UTC, NianGuu commented on projects/1.18/assets/upgraded-netherite-items/upgradednetherite_items/lang/zh_cn.json
> +  "upgradednetherite_items.Corrupt_Totem2.TT": "§5每一件腐化下界合金装备都可以提供%1$s§5的抗性提升.",
> > 你有没有想过这个§7是干嘛的。。
> 
> 单独彩色一个.有什么用

我是指你没删干净哈哈哈

2022-03-17 04:05 UTC, Cyl18 approved these changes

2022-03-17 10:52 UTC, n0099 approved these changes

2022-03-18 16:05 UTC, TartaricAcid approved these changes

2022-03-19 03:57 UTC, mamaruo approved these changes

2022-03-19 04:04 UTC, merged