[R] L_Ender 's Cataclysm 翻译更新 #CFPA-0615
CFPAOrg/Minecraft-Mod-Language-Package pull request #1666
Opened 2022-03-16 17:59 UTC by mamaruo

Co-authored-by: Kasualix <670067575@qq.com>

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-16 23:11 UTC, n0099 requested changes

2022-03-16 23:11 UTC, n0099 commented on projects/1.16/assets/l_ender-s-cataclysm/cataclysm/lang/zh_cn.json
>    "block.cataclysm.witherite_block": "凋零合金块",
```suggestion
  "block.cataclysm.witherite_block": "凋灵合金块",
```

2022-03-17 07:00 UTC, Kasualix commented on projects/1.16/assets/l_ender-s-cataclysm/cataclysm/lang/zh_cn.json
>    "block.cataclysm.witherite_block": "凋零合金块",
cataclysm 的 discord 里有一位 zh_tw 译者，TA 译的也是“零”。
witherite 目前在模组内还是一种不可获得的材料，完成度也非常低，甚至9个 witherite ingot 无法与 witherite block 相互转换，没有什么别的可以参考的信息。

2022-03-17 08:29 UTC, Cyl18 commented on projects/1.16/assets/l_ender-s-cataclysm/cataclysm/lang/zh_cn.json
>    "block.cataclysm.witherite_block": "凋零合金块",
去...参考一下这位 zh_tw 译者的意见？

2022-03-17 09:01 UTC, Kasualix commented on projects/1.16/assets/l_ender-s-cataclysm/cataclysm/lang/zh_cn.json
>    "block.cataclysm.witherite_block": "凋零合金块",
在 discord 里找到作者以前说的话：
_The defiler and unmaker armor were originally powerful armor that could be made into witherite and enderite.
During development, the direction changed and it became a developer item.
As you know, modeling is derived from Thaumcraft.
If they add something officially,Even if I do it, the modeling will change.
There is a high possibility that it will be deleted altogether.
We still have no direction for them, so please give us a lot of opinions_
后来， defiler 和 unmaker 装备（果然）在模组的 0.0.9 版本被移除了。
那位译者 我已经问了，等 TA 回。

2022-03-17 09:25 UTC, Kasualix commented on projects/1.16/assets/l_ender-s-cataclysm/cataclysm/lang/zh_cn.json
>    "block.cataclysm.witherite_block": "凋零合金块",
![image](https://user-images.githubusercontent.com/76616758/158778656-4442e907-947e-4476-9ee4-e28d793f8775.png)

2022-03-17 09:26 UTC, Kasualix commented on projects/1.16/assets/l_ender-s-cataclysm/cataclysm/lang/zh_cn.json
>    "block.cataclysm.witherite_block": "凋零合金块",
这是那位译者的回应

2022-03-18 16:10 UTC, TartaricAcid approved these changes

2022-03-19 03:35 UTC, mamaruo commented
**Self-approved**

2022-03-19 04:05 UTC, merged