[R] Addendum 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1669
Opened 2022-03-17 01:14 UTC by XiaoXin1113

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-17 01:27 UTC, n0099 commented on projects/1.16/assets/addendum-fabric/addendum/lang/zh_cn.json
> +	"block.addendum.shulker_block": "潜匿之贝块",
潜匿之贝不是原版的shulker潜隐贝？

2022-03-17 01:28 UTC, XiaoXin1113 commented on projects/1.16/assets/addendum-fabric/addendum/lang/zh_cn.json
> +	"block.addendum.shulker_block": "潜匿之贝块",
潜匿之贝是原版的翻译

2022-03-17 01:28 UTC, XiaoXin1113 commented on projects/1.16/assets/addendum-fabric/addendum/lang/zh_cn.json
> +	"block.addendum.shulker_block": "潜匿之贝块",
算是比较正式的叫法

2022-03-17 01:29 UTC, XiaoXin1113 commented on projects/1.16/assets/addendum-fabric/addendum/lang/zh_cn.json
> +	"block.addendum.shulker_block": "潜匿之贝块",
当然潜影贝也是可以的

2022-03-17 01:34 UTC, n0099 requested changes

2022-03-17 01:34 UTC, n0099 commented on projects/1.16/assets/addendum-fabric/addendum/lang/zh_cn.json
> +	"block.addendum.chiseled_himmel_bricks": "錾制天蓝石砖",
https://en.wiktionary.org/wiki/himmel 丹麦语 低地德语中的himmel是指天空 天堂，这方块看起来是什么样的？

2022-03-17 01:37 UTC, n0099 commented on projects/1.16/assets/addendum-fabric/addendum/lang/zh_cn.json
> +	"block.addendum.chiseled_himmel_bricks": "錾制天蓝石砖",
openblocks也有个天空方块：https://www.mcmod.cn/item/7218.html

2022-03-17 01:49 UTC, XiaoXin1113 commented on projects/1.16/assets/addendum-fabric/addendum/lang/zh_cn.json
> +	"block.addendum.chiseled_himmel_bricks": "錾制天蓝石砖",
那好吧

2022-03-17 10:20 UTC, TartaricAcid commented
这是 fabric 的模组翻译吧？

2022-03-18 16:43 UTC, TartaricAcid commented
我有点犹豫该怎么办，fabric 的翻译……目前模组是不支持的……

2022-03-18 17:04 UTC, Cyl18 commented
但是手动下载汉化包应该是支持的…

2022-03-18 23:54 UTC, XiaoXin1113 commented
> 但是手动下载汉化包应该是支持的…

2022-03-19 03:34 UTC, mamaruo commented
如果 CFPA 有制作 Fabric 模组的意愿的话先入库，先积累一些，发 fabric 模组的时候也有底气。

另外 Fabric 需不需要什么单独的处理

2022-03-19 04:01 UTC, TartaricAcid approved these changes

2022-03-19 06:56 UTC, n0099 approved these changes

2022-03-20 16:59 UTC, mamaruo approved these changes
小问题

2022-03-20 16:59 UTC, mamaruo commented on projects/1.16/assets/addendum-fabric/addendum/lang/zh_cn.json
> +	"block.addendum.chorusy_end_stone_bricks": "紫颂果末地石砖",
```suggestion
	"block.addendum.chorusy_end_stone_bricks": "紫颂末地石砖",
```

2022-03-20 20:17 UTC, merged