[R] Gamestages 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1671
Opened 2022-03-17 10:58 UTC by XiaoXin1113

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-17 11:12 UTC, n0099 requested changes

2022-03-17 11:12 UTC, n0099 commented on projects/1.16/assets/game-stages/gamestages/lang/zh_cn.json
> +    "commands.gamestage.remove.sender": "%s 的游戏阶段 %s 已经移除！",
```suggestion
    "commands.gamestage.remove.sender": "%s 的游戏阶段 %s 已被移除！",
```

2022-03-17 16:39 UTC, mamaruo commented
要统一空格

2022-03-17 19:04 UTC, n0099 requested changes

2022-03-17 19:04 UTC, n0099 commented on projects/1.16/assets/game-stages/gamestages/lang/zh_cn.json
> +    "commands.gamestage.reloadfakes.info": "重新加载fake player游戏阶段。",
```suggestion
    "commands.gamestage.reloadfakes.info": "重新加载 fake player 游戏阶段。",
```

2022-03-18 12:46 UTC, n0099 approved these changes

2022-03-18 16:47 UTC, merged

2022-03-19 01:11 UTC, mamaruo commented
空格还是没统一
ready to merge 24 小时……

2022-03-19 01:13 UTC, XiaoXin1113 commented
> 空格还是没统一 ready to merge 24 小时……

收到，准备发起修正后的新PR