[R] Simply Cats 翻译提交 #CFPA-0616
CFPAOrg/Minecraft-Mod-Language-Package pull request #1674
Opened 2022-03-18 08:19 UTC by Cyl18

- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-18 08:21 UTC, Cyl18 commented
这个模组好奇怪 用的<当注释

2022-03-18 12:53 UTC, n0099 requested changes

2022-03-18 12:53 UTC, n0099 commented on projects/1.12.2/assets/simply-cats/simplycats/lang/zh_cn.lang
> +tooltip.certificate_release.desc=右键你拥有的宠物来放归他们。
```suggestion
tooltip.cat_book.usage=对着猫咪潜行+右击打开图鉴。
tooltip.certificate_adopt.desc=右击未驯服的宠物来领养他们。
tooltip.certificate_release.desc=右击你拥有的宠物来放归他们。
```

2022-03-18 12:53 UTC, n0099 commented on projects/1.12.2/assets/simply-cats/simplycats/lang/zh_cn.lang
> +tooltip.sterilization_potion.usage=潜行+右键将猫咪绝育，请注意，绝育是不可逆的!
```suggestion
tooltip.sterilization_potion.usage=潜行+右击将猫咪绝育，请注意，绝育是不可逆的！
```

2022-03-18 12:53 UTC, n0099 commented on projects/1.12.2/assets/simply-cats/simplycats/lang/zh_cn.lang
> +book.index_page.info=你好! 这是Simply Cats猫咪图鉴的索引页,试着对猫咪潜行+右键使用吧！
```suggestion
book.index_page.info=你好！这是Simply Cats猫咪图鉴的索引页，试着对猫咪潜行+右击使用吧！
```

2022-03-18 12:53 UTC, n0099 commented on projects/1.12.2/assets/simply-cats/simplycats/lang/zh_cn.lang
> +item.simplycats.pet_carrier.full.name=宠物笼(满)
```suggestion
item.simplycats.pet_carrier.empty.name=宠物笼（空）
item.simplycats.pet_carrier.full.name=宠物笼（满）
```

2022-03-18 12:53 UTC, n0099 commented on projects/1.12.2/assets/simply-cats/simplycats/lang/zh_cn.lang
> +tooltip.pet_carrier.adopt_dog=领养狗狗!
```suggestion
tooltip.pet_carrier.adopt_cat=领养猫咪！
tooltip.pet_carrier.adopt_dog=领养狗狗！
```

2022-03-18 17:05 UTC, TartaricAcid approved these changes
修正部分错误

2022-03-19 03:28 UTC, mamaruo requested changes

2022-03-19 03:28 UTC, mamaruo commented on projects/1.12.2/assets/simply-cats/simplycats/lang/zh_cn.lang
> +simplycats.subtitle.shake_treats=摇摇你的零食袋！
```suggestion
simplycats.subtitle.shake_treats=零食袋：摇动
```
Subtitle 格式太容易错了

2022-03-19 03:28 UTC, mamaruo commented on projects/1.12.2/assets/simply-cats/simplycats/lang/zh_cn.lang
> +cat.base.chocolate_not_red_caramelized.name=褐灰色（丁香底焦糖色）
？

2022-03-19 03:28 UTC, mamaruo commented on projects/1.12.2/assets/simply-cats/simplycats/lang/zh_cn.lang
> +cat.base.cinnamon_not_red_dilute.name=小鹿色
```suggestion
cat.base.cinnamon_not_red_dilute.name=鹿毛色
```
https://dictionary.cambridge.org/zhs/%E8%AF%8D%E5%85%B8/%E8%8B%B1%E8%AF%AD-%E6%B1%89%E8%AF%AD-%E7%AE%80%E4%BD%93/fawn

2022-03-19 04:07 UTC, TartaricAcid commented on projects/1.12.2/assets/simply-cats/simplycats/lang/zh_cn.lang
> +simplycats.subtitle.shake_treats=摇摇你的零食袋！
woc，都没注意到这块是 subtitle

2022-03-19 04:15 UTC, Sweetdubai commented on projects/1.12.2/assets/simply-cats/simplycats/lang/zh_cn.lang
> +cat.base.chocolate_not_red_caramelized.name=褐灰色（丁香底焦糖色）
这一部分是原有文件自带的，我并没有修改

2022-03-20 16:47 UTC, mamaruo commented on projects/1.12.2/assets/simply-cats/simplycats/lang/zh_cn.lang
> +cat.base.chocolate_not_red_caramelized.name=褐灰色（丁香底焦糖色）
@Sweetdubai 确认一下这个能不能删，很奇怪这里

2022-03-21 01:46 UTC, Sweetdubai commented on projects/1.12.2/assets/simply-cats/simplycats/lang/zh_cn.lang
> +cat.base.chocolate_not_red_caramelized.name=褐灰色（丁香底焦糖色）
这个地方应该是原来的翻译这搞错了吧，我并没有改啊。你们看着弄吧，我也不知道能不能删

2022-03-21 03:44 UTC, merged

2022-03-21 07:58 UTC, n0099 commented on projects/1.12.2/assets/simply-cats/simplycats/lang/zh_cn.lang
> +cat.base.chocolate_not_red_caramelized.name=褐灰色（丁香底焦糖色）
都已经merge了