[R] Yung's better mineshafts 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1682
Opened 2022-03-19 02:21 UTC by XiaoXin1113

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2022-03-19 04:27 UTC, n0099 commented
duplicated: #1673

2022-03-19 04:30 UTC, TartaricAcid commented on projects/1.16/assets/yungs-better-mineshafts-fabric/bettermineshafts/lang/zh_cn.json
> +    "text.autoconfig.bettermineshafts-fabric-1_16.option.spawnRates.zombieVillagerRoomSpawnChance.@Tooltip[1]": "矿工休息站的百分比概率。",
这一块很明显是一段话，所以按照中文语序做了调整

2022-03-19 04:30 UTC, TartaricAcid approved these changes

2022-03-19 04:40 UTC, n0099 approved these changes

2022-03-19 07:07 UTC, Cyl18 approved these changes

2022-03-19 09:58 UTC, n0099 approved these changes

2022-03-20 16:51 UTC, mamaruo commented
统一空格，1.16及以上非必要不加空格

2022-03-20 20:15 UTC, n0099 requested changes

2022-03-20 20:15 UTC, n0099 commented on projects/1.18/assets/yungs-better-mineshafts-fabric/bettermineshafts/lang/zh_cn.json
> +    "text.autoconfig.bettermineshafts-fabric-1_18.option.spawnRates.smallShaftPieceChainLength.@Tooltip[0]": "在一个单独的小矿道中 \"分支\" （比如直道、转弯等） 的数量。",
```suggestion
    "text.autoconfig.bettermineshafts-fabric-1_18.option.spawnRates.smallShaftPieceChainLength.@Tooltip[0]": "在一个单独的小矿道中\"分支\"（比如直道、转弯等）的数量。",
```

2022-03-20 20:15 UTC, n0099 commented on projects/1.18/assets/yungs-better-mineshafts-fabric/bettermineshafts/lang/zh_cn.json
> +    "text.autoconfig.bettermineshafts-fabric-1_18.option.ores.@Tooltip[1]": "保证所有数值的和是 100，",
```suggestion
    "text.autoconfig.bettermineshafts-fabric-1_18.option.ores.@Tooltip[1]": "保证所有数值的和是100，",
```

2022-03-20 20:15 UTC, n0099 commented on projects/1.18/assets/yungs-better-mineshafts-fabric/bettermineshafts/lang/zh_cn.json
> +    "text.autoconfig.bettermineshafts-fabric-1_18.title": "YUNG 的矿井优化",
```suggestion
    "text.autoconfig.bettermineshafts-fabric-1_18.title": "YUNG的矿井优化",
```

2022-03-21 03:45 UTC, merged