[R] 更新 Tool Leveling+ 模组翻译 #CFPA-0612
CFPAOrg/Minecraft-Mod-Language-Package pull request #1684
Opened 2022-03-19 08:28 UTC by TartaricAcid

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-19 10:00 UTC, n0099 requested changes

2022-03-19 10:00 UTC, n0099 commented on projects/1.18/assets/tool-leveling-plus/toolleveling/lang/zh_cn.json
> +  "container.toolleveling.tool_leveling_table.free_creative": "创造模式下附魔无花费",
```suggestion
  "container.toolleveling.tool_leveling_table.free_creative": "创造模式下附魔无需开销",
```

2022-03-19 15:13 UTC, Cyl18 commented on projects/1.18/assets/tool-leveling-plus/toolleveling/lang/zh_cn.json
> +  "container.toolleveling.tool_leveling_table.free_creative": "创造模式下附魔无花费",
为啥是无需开销

2022-03-19 19:11 UTC, n0099 commented on projects/1.18/assets/tool-leveling-plus/toolleveling/lang/zh_cn.json
> +  "container.toolleveling.tool_leveling_table.free_creative": "创造模式下附魔无花费",
原文就是`Leveling is free`

2022-03-21 07:59 UTC, n0099 approved these changes

2022-03-22 13:31 UTC, merged