填一下Silent先生的远古巨坑
CFPAOrg/Minecraft-Mod-Language-Package pull request #1685
Opened 2022-03-19 08:39 UTC by grumm9472

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-19 09:00 UTC, mamaruo commented
请在标题中包含模组英文名，见 CONTRIBUTING.md

2022-03-19 09:56 UTC, n0099 requested changes

2022-03-19 09:56 UTC, n0099 commented on projects/1.18/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.nc_radiation_protection.desc": "测试用属性，用来测试核电防护的NBT修改是否管用。",
```suggestion
  "trait.silentgear.nc_radiation_protection": "核电辐射防护",
  "trait.silentgear.nc_radiation_protection.desc": "测试用属性，用来测试核电防护的NBT修改是否管用。",
```

2022-03-19 09:56 UTC, n0099 commented on projects/1.18/assets/silent-gear/silentgear/lang/en_us.json
> +    "trait.silentgear.nc_radiation_protection.desc": "Not tested, just see if this NBT trait works. Protects you from radiation protection.",
```suggestion
  "trait.silentgear.nc_radiation_protection": "Nuclear Radiation Protection",
  "trait.silentgear.nc_radiation_protection.desc": "Not tested, just see if this NBT trait works. Protects you from radiation protection.",
```

2022-03-19 12:07 UTC, Cyl18 commented on projects/1.18/assets/silent-gear/silentgear/lang/en_us.json
> +    "trait.silentgear.nc_radiation_protection.desc": "Not tested, just see if this NBT trait works. Protects you from radiation protection.",
这个理论上无所谓 因为formatter会自动删

2022-03-19 12:43 UTC, n0099 commented on projects/1.18/assets/silent-gear/silentgear/lang/en_us.json
> +    "trait.silentgear.nc_radiation_protection.desc": "Not tested, just see if this NBT trait works. Protects you from radiation protection.",
您以前说“不要直接丶commit suggestion”

2022-03-19 12:46 UTC, mamaruo commented on projects/1.18/assets/silent-gear/silentgear/lang/en_us.json
> +    "trait.silentgear.nc_radiation_protection.desc": "Not tested, just see if this NBT trait works. Protects you from radiation protection.",
直接 commit 对 PR 提交者的提示作用很小，但格式等小问题上直接 commit 省时间。

2022-03-19 13:00 UTC, n0099 commented on projects/1.18/assets/silent-gear/silentgear/lang/en_us.json
> +    "trait.silentgear.nc_radiation_protection.desc": "Not tested, just see if this NBT trait works. Protects you from radiation protection.",
那为什么author可以丶我不能

2022-03-19 13:03 UTC, mamaruo commented on projects/1.18/assets/silent-gear/silentgear/lang/en_us.json
> +    "trait.silentgear.nc_radiation_protection.desc": "Not tested, just see if this NBT trait works. Protects you from radiation protection.",
可能是 author 把写入权关了

2022-03-19 13:08 UTC, n0099 commented on projects/1.18/assets/silent-gear/silentgear/lang/en_us.json
> +    "trait.silentgear.nc_radiation_protection.desc": "Not tested, just see if this NBT trait works. Protects you from radiation protection.",
我知道author可以创建pr时禁止allow repo maintainer edit，我是对@cyl18a 说

2022-03-19 13:11 UTC, n0099 commented on projects/1.18/assets/silent-gear/silentgear/lang/en_us.json
> +    "trait.silentgear.nc_radiation_protection.desc": "Not tested, just see if this NBT trait works. Protects you from radiation protection.",
![](https://user-images.githubusercontent.com/13030387/159122421-8331fe44-9b65-48bd-b5ad-f2163da54111.png)
![](https://user-images.githubusercontent.com/13030387/159122424-aa01ce30-7ec3-44ac-a5b5-c25d52d06a5a.png)
![](https://user-images.githubusercontent.com/13030387/159122426-74773dbb-9779-4de2-b861-ea1e5a4552fe.png)
![](https://user-images.githubusercontent.com/13030387/159122427-7fde70e3-ed01-4ecc-bd6d-194f0a145b81.png)
![](https://user-images.githubusercontent.com/13030387/159122429-5312747f-76bd-4476-82cf-ddb49b47bc33.png)

2022-03-19 13:14 UTC, mamaruo commented on projects/1.18/assets/silent-gear/silentgear/lang/en_us.json
> +    "trait.silentgear.nc_radiation_protection.desc": "Not tested, just see if this NBT trait works. Protects you from radiation protection.",
显然酒石酸入场之后整体速度拉得很快，他直接 commit 能省很多时间。但我也不是很赞同这样的做法。另开 issue 讨论吧。（话说 Discussion 是什么地位）

2022-03-19 14:36 UTC, n0099 commented on projects/1.18/assets/silent-gear/silentgear/lang/en_us.json
> +    "trait.silentgear.nc_radiation_protection.desc": "Not tested, just see if this NBT trait works. Protects you from radiation protection.",
我不喜欢github discussion

2022-03-19 15:01 UTC, Cyl18 commented on projects/1.18/assets/silent-gear/silentgear/lang/en_us.json
> +    "trait.silentgear.nc_radiation_protection.desc": "Not tested, just see if this NBT trait works. Protects you from radiation protection.",
![image](https://user-images.githubusercontent.com/14993992/159126351-e8839392-e65d-4dbd-9900-acd99e302774.png)
倒是可以讨论一下

2022-03-19 15:07 UTC, Cyl18 commented on projects/1.18/assets/silent-gear/silentgear/lang/en_us.json
> +    "trait.silentgear.nc_radiation_protection.desc": "Not tested, just see if this NBT trait works. Protects you from radiation protection.",
我很久以前指的不要直接commit都是有确切内容的修改 比如全角半角统一 需要讨论 但是这里的格式/非文本内容真的太无所谓了
无所谓到没第二个人知道都行
但是像一些 内容的问题比如文字前面多了个空格/淡灰色浅灰色这种 就感觉需要作者/第二个人知晓

> 不要截图几千年前的聊天记录 自己都不知道自己在说啥

2022-03-19 19:10 UTC, n0099 commented on projects/1.18/assets/silent-gear/silentgear/lang/en_us.json
> +    "trait.silentgear.nc_radiation_protection.desc": "Not tested, just see if this NBT trait works. Protects you from radiation protection.",
lg神最高指示：不要截图几千年前的聊天记录 自己都不知道自己在说啥

2022-03-20 17:00 UTC, mamaruo approved these changes

2022-03-20 20:19 UTC, n0099 approved these changes

2022-03-21 03:45 UTC, merged