[R] Advanced Hook Launchers 翻译更新 #CFPA-0623
CFPAOrg/Minecraft-Mod-Language-Package pull request #1687
Opened 2022-03-20 18:11 UTC by mamaruo

Co-authored-by: Tigercrl <tigercrl@icloud.com>

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-20 20:22 UTC, n0099 commented on projects/1.16/assets/advanced-hook-launchers/adhooks/lang/zh_cn.json
> +	"tooltip.adhooks.launcher.tarzan_jump": "%1$s大跳:%2$s 在空中时，双击 %1$s%3$s%2$s",
```suggestion
	"tooltip.adhooks.launcher.tarzan_jump": "%1$s大跳:%2$s 在空中时，双击 %1$s%3$s%2$s",
```
两段跳（但这并不一定是在空中双击空格）或泰山跳（字面意思）

2022-03-21 03:58 UTC, TartaricAcid commented on projects/1.16/assets/advanced-hook-launchers/adhooks/lang/zh_cn.json
> +	"tooltip.adhooks.launcher.tarzan_jump_strength": "大跳",
这里指的是类似于《人猿泰山》里泰山经典的拽着绳子跳吧？

2022-03-21 06:32 UTC, TartaricAcid commented
修正了这部分的翻译内容：
![2022-03-21_14 26 04](https://user-images.githubusercontent.com/19620085/159214229-983bda58-ab1e-4a7b-97b5-f88eac7ffa50.png)

2022-03-21 08:00 UTC, n0099 requested changes

2022-03-21 08:00 UTC, n0099 commented on projects/1.18/assets/advanced-hook-launchers/adhooks/lang/zh_cn.json
> +    "tooltip.adhooks.launcher.controls": "%1$s长按%2$sControl%1$s来查看更多操作键位",
```suggestion
    "tooltip.adhooks.launcher.controls": "%1$s长按%2$sCtrl%1$s来查看更多操作键位",
```

2022-03-21 12:36 UTC, Tigercrl commented on projects/1.18/assets/advanced-hook-launchers/adhooks/lang/zh_cn.json
> +    "tooltip.adhooks.launcher.controls": "%1$s长按%2$sControl%1$s来查看更多操作键位",
这个是键位，是那种不能调的，写死在里面的

2022-03-21 14:13 UTC, TartaricAcid approved these changes

2022-03-21 19:46 UTC, n0099 commented on projects/1.18/assets/advanced-hook-launchers/adhooks/lang/zh_cn.json
> +    "tooltip.adhooks.launcher.controls": "%1$s长按%2$sControl%1$s来查看更多操作键位",
mac还有command键呢

2022-03-22 02:00 UTC, Cyl18 commented on projects/1.18/assets/advanced-hook-launchers/adhooks/lang/zh_cn.json
> +    "tooltip.adhooks.launcher.controls": "%1$s长按%2$sControl%1$s来查看更多操作键位",
Minecraft Wiki 上面用的 `Ctrl`

2022-03-22 04:30 UTC, mamaruo commented on projects/1.18/assets/advanced-hook-launchers/adhooks/lang/zh_cn.json
> +    "key.categories.adhooks.main_hand": "钩爪发射器（主手）",
一致性问题

2022-03-22 04:30 UTC, mamaruo commented on projects/1.18/assets/advanced-hook-launchers/adhooks/lang/zh_cn.json
> +    "key.categories.adhooks.off_hand": "钩爪发射器（副手）",
一致性问题

2022-03-22 13:37 UTC, merged