[R] Advancement Plus 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1692
Opened 2022-03-21 07:41 UTC by XiaoXin1113

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-21 13:04 UTC, TartaricAcid commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +    "advancement.plus.all_diamond_tools.desc": "获得所有钻石工具、盔甲及马铠",
我记得统一翻译成 `护甲` 吧

2022-03-21 13:04 UTC, TartaricAcid commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +    "advancement.plus.all_netherite_tools.desc": "获得所有下界合金工具和盔甲",
同理，护甲

2022-03-21 13:08 UTC, TartaricAcid commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +    "advancement.plus.hot_topic.title": "火热的话题",
我记得原版好像翻译成 “热”门话题

2022-03-21 13:13 UTC, TartaricAcid commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +    "advancement.plus.silky_pickaxe.desc": "给任何一种工具附魔丝绸之触（精准采集）",
原版精准采集就是 `Silk Touch`，没必要加备注

2022-03-21 13:13 UTC, TartaricAcid commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +    "advancement.plus.sharpness_sword.desc": "给任何一种十字镐或斧附魔锋利",
Pickaxe？十字镐？

2022-03-21 13:14 UTC, XiaoXin1113 commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +    "advancement.plus.silky_pickaxe.desc": "给任何一种工具附魔丝绸之触（精准采集）",
那我写精准采集还是丝绸之触呢

2022-03-21 13:18 UTC, XiaoXin1113 commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +    "advancement.plus.all_the_stones.desc": "收集所有种类的石头。不包括蠹虫生怪蛋。",
已更改

2022-03-21 13:18 UTC, XiaoXin1113 commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +    "advancement.plus.all_diamond_tools.desc": "获得所有钻石工具、盔甲及马铠",
已更改

2022-03-21 13:19 UTC, XiaoXin1113 commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +    "advancement.plus.all_netherite_tools.desc": "获得所有下界合金工具和盔甲",
已更改

2022-03-21 13:20 UTC, XiaoXin1113 commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +    "advancement.plus.hot_topic.title": "火热的话题",
已更改

2022-03-21 13:57 UTC, TartaricAcid commented
依据原版翻译内容作了部分修改，部分用词我也做了修改

2022-03-21 13:57 UTC, TartaricAcid approved these changes

2022-03-21 15:46 UTC, mamaruo commented
https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96
原版词啊原版词，原版词翻成这样就不是一个纳夸达能解决的了

2022-03-21 15:51 UTC, mamaruo commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +    "advancement.plus.all_diamond_tools.desc": "获得所有钻石工具、盔甲及马铠",
查原版译名标准化得应译为盔甲

2022-03-21 19:44 UTC, n0099 requested changes

2022-03-21 19:44 UTC, n0099 commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +  "advancement.plus.who_is_raider_now.desc": "抢劫掠夺者前哨站内的箱子。这个成就每一个掠夺者前哨站只能一个人获取。",
```suggestion
  "advancement.plus.who_is_raider_now.desc": "抢劫掠夺者前哨站内的箱子。每个掠夺者前哨站只能有一个人获取本成就。",
```

2022-03-21 19:44 UTC, n0099 commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +  "advancement.plus.i_am_pirate.desc": "掠夺被埋藏的宝藏。这个成就中的宝藏只能被一个人获取。别的人要找其他的宝藏。",
```suggestion
  "advancement.plus.i_am_pirate.desc": "掠夺被埋藏的宝藏。这个成就中的宝藏只能被第一位玩家获取。其他玩家要找其他的宝藏。",
```

2022-03-21 19:44 UTC, n0099 commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +  "advancement.plus.loot_mineshaft.desc": "掠夺废弃矿井中的运输矿车。这个成就只能被一个人获取。别的人要找其他的废弃矿井。",
```suggestion
  "advancement.plus.loot_mineshaft.desc": "掠夺废弃矿井中的运输矿车。这个成就只能被第一位玩家获取。其他玩家要找其他的废弃矿井。",
```

2022-03-21 19:44 UTC, n0099 commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +  "advancement.plus.yes_im_the_raider.desc": "掠夺林地府邸中的一些物品。这个成就只能被一个人获取。别的人要找其他的。",
```suggestion
  "advancement.plus.yes_im_the_raider.desc": "掠夺林地府邸中的一些物品。这个成就只能被第一位玩家获取。其他玩家要找其他的。",
```

2022-03-21 19:44 UTC, n0099 commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +  "advancement.plus.tomb_raided.desc": "掠夺林地府邸中的一个箱子或陷阱箱。这个成就只能被一个人获取。别的人要找其他的。",
```suggestion
  "advancement.plus.tomb_raided.desc": "掠夺林地府邸中的一个箱子或陷阱箱。这个成就只能被第一位玩家获取。其他玩家要找其他的林地府邸。",
```

2022-03-21 19:44 UTC, n0099 commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +  "advancement.plus.isnt_this_map.desc": "打开一个沉船内的含有地图的箱子。这个成就只能被一个人获取。别的人要找其他的。",
```suggestion
  "advancement.plus.isnt_this_map.desc": "打开一个沉船内的含有地图的箱子。这个成就只能被第一位玩家获取。其他玩家要找其他的沉船。",
```

2022-03-21 19:44 UTC, n0099 commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +  "advancement.plus.i_am_rich.desc": "打开一个沉船内的含有稀有资源的箱子。这个成就只能被一个人获取。别的人要找其他的。"
```suggestion
  "advancement.plus.i_am_rich.desc": "打开一个沉船内的含有稀有资源的箱子。这个成就只能被第一位玩家获取。其他玩家要找其他的沉船。"
```

2022-03-22 01:54 UTC, XiaoXin1113 commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +    "advancement.plus.all_diamond_tools.desc": "获得所有钻石工具、盔甲及马铠",
> 查原版译名标准化得应译为盔甲

已更改回盔甲

2022-03-22 01:54 UTC, XiaoXin1113 commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +    "advancement.plus.all_netherite_tools.desc": "获得所有下界合金工具和盔甲",
已更改回盔甲

2022-03-22 02:26 UTC, Cyl18 commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +  "advancement.plus.lucky_pickaxe.desc": "给任意一种镐子或斧子附魔幸运",
```suggestion
  "advancement.plus.lucky_pickaxe.title": "幸运的镐",
  "advancement.plus.lucky_pickaxe.desc": "给任意一种镐或斧附魔幸运",
```
maybe?

2022-03-22 02:28 UTC, Cyl18 commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +  "advancement.plus.sharpness_sword.desc": "给任意一种镐子或斧子附魔锋利",
```suggestion
  "advancement.plus.sharpness_sword.desc": "给任意一种镐或斧附魔锋利",
```

2022-03-22 02:28 UTC, Cyl18 commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +  "advancement.plus.withering_sword.desc": "给任意一种镐子或斧子附魔亡灵杀手",
```suggestion
  "advancement.plus.withering_sword.desc": "给任意一种镐或斧附魔亡灵杀手",
```

2022-03-22 06:38 UTC, n0099 approved these changes

2022-03-22 08:55 UTC, mamaruo requested changes

2022-03-22 08:55 UTC, mamaruo commented on projects/1.16/assets/advancement-plus-vanilla/advancementplus/lang/zh_cn.json
> +  "advancement.plus.happy_new_year.desc": "制造能配合鞘翅使用的烟花",
```suggestion
  "advancement.plus.happy_new_year.desc": "合成能配合鞘翅使用的烟花",
```
原版词啊原版词

2022-03-24 10:58 UTC, merged