[R] All The Mods: Additions 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1695
Opened 2022-03-21 08:35 UTC by ZHAY10086

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2022-03-21 10:06 UTC, TartaricAcid commented on projects/1.16/assets/atm-additions/atmadditions/lang/zh_cn.json
> +    "item.atmadditions.nexium_emitter": "奈克修姆发射器",
这个词语我没找到来源，但是看词缀可能是作者生造的？`nex`+`ium`？

2022-03-21 10:07 UTC, TartaricAcid approved these changes

2022-03-21 19:38 UTC, n0099 requested changes

2022-03-21 19:38 UTC, n0099 commented on projects/1.16/assets/atm-additions/atmadditions/lang/zh_cn.json
> +    "item.atmadditions.nexium_emitter": "奈克修姆发射器",
```suggestion
    "item.atmadditions.nexium_emitter": "耐信发射器",
```
https://www.youtube.com/watch?v=Qb8Warb2ghY
https://www.reddit.com/r/allthemods/comments/ocamfc/what_does_the_nexium_emitter_do/
这是atm star的合成材料，没有任何实际用途
我atm6毕业有被atm star恶心到

2022-03-21 19:46 UTC, n0099 commented on projects/1.16/assets/atm-additions/atmadditions/lang/zh_cn.json
> +    "item.atmadditions.nexium_emitter": "奈克修姆发射器",
```suggestion
    "item.atmadditions.nexium_emitter": "耐信发射器",
```
这是做atm star的合成材料之一，毫无实际用途
我atm6为了毕业刷这些有被恶心到
https://www.youtube.com/watch?v=Qb8Warb2ghY
https://www.reddit.com/r/allthemods/comments/ocamfc/what_does_the_nexium_emitter_do/
![](https://i.imgur.com/UInV8aN.png)

2022-03-22 01:05 UTC, ZHAY10086 commented on projects/1.16/assets/atm-additions/atmadditions/lang/zh_cn.json
> +    "item.atmadditions.nexium_emitter": "奈克修姆发射器",
这里为了和耐信做区分，我特意选了不同的音译

2022-03-22 02:43 UTC, Cyl18 commented on projects/1.16/assets/atm-additions/atmadditions/lang/zh_cn.json
> +    "item.atmadditions.nexium_emitter": "奈克修姆发射器",
但是得 `ium`..?

2022-03-22 06:38 UTC, n0099 commented on projects/1.16/assets/atm-additions/atmadditions/lang/zh_cn.json
> +    "item.atmadditions.nexium_emitter": "奈克修姆发射器",
> 这里为了和耐信做区分，我特意选了不同的音译

atm6有别的耐信？

2022-03-22 06:40 UTC, ZHAY10086 commented on projects/1.16/assets/atm-additions/atmadditions/lang/zh_cn.json
> +    "item.atmadditions.nexium_emitter": "奈克修姆发射器",
和现实中的耐信做区分啊，这里Nexium肯定不是药的意思

2022-03-22 06:44 UTC, n0099 commented on projects/1.16/assets/atm-additions/atmadditions/lang/zh_cn.json
> +    "item.atmadditions.nexium_emitter": "奈克修姆发射器",
> 和现实中的耐信做区分啊，这里Nexium肯定不是药的意思

看看这玩意的合成

2022-03-22 08:34 UTC, ZHAY10086 commented on projects/1.16/assets/atm-additions/atmadditions/lang/zh_cn.json
> +    "item.atmadditions.nexium_emitter": "奈克修姆发射器",
1 * 充能棒（下界）+ 1 * 玩家供电仪（下界） + 2 * 铂块 + 1 * 压缩下界合金块（3x） + 1 * 量子缠绕奇点 + 1 * 无线终端
![图片](https://user-images.githubusercontent.com/34602681/159439789-751e40fd-e727-4b67-b434-5a689227d74b.png)

2022-03-22 09:07 UTC, n0099 commented on projects/1.16/assets/atm-additions/atmadditions/lang/zh_cn.json
> +    "item.atmadditions.nexium_emitter": "奈克修姆发射器",
那的确无关

2022-03-22 09:08 UTC, n0099 approved these changes

2022-03-22 13:39 UTC, merged