[R] Darkutils 翻译修正
CFPAOrg/Minecraft-Mod-Language-Package pull request #1700
Opened 2022-03-22 04:14 UTC by ZHAY10086

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2022-03-22 06:43 UTC, n0099 requested changes
请同步最新jar中的en_us.json中的key

2022-03-22 06:43 UTC, n0099 commented on projects/1.16/assets/dark-utilities/darkutils/lang/zh_cn.json
> +  "block.minecraft.banner.darkutils_vector_plate.white": "白色向量图案"
什么向量，有没有一种可能，我是说可能，这只是条线

2022-03-22 06:43 UTC, n0099 commented on projects/1.16/assets/dark-utilities/darkutils/lang/zh_cn.json
> +  "tooltip.darkutils.filter_boss.short": "只允许 Boss 生物通过。",
```suggestion
  "tooltip.darkutils.filter_boss.short": "只允许Boss生物通过。",
```

2022-03-22 08:26 UTC, ZHAY10086 commented on projects/1.16/assets/dark-utilities/darkutils/lang/zh_cn.json
> +  "block.minecraft.banner.darkutils_vector_plate.white": "白色向量图案"
确实是向量，原文就是vector，合成表里也有向量板，实际游戏里长这样
![图片](https://user-images.githubusercontent.com/34602681/159438435-b89e77f9-35c8-4ce7-bed3-da5765c983c4.png)

2022-03-22 09:26 UTC, XiaoXin1113 commented on projects/1.16/assets/dark-utilities/darkutils/lang/zh_cn.json
> +  "block.minecraft.banner.darkutils_vector_plate.white": "白色向量图案"
这个是旗子啊

2022-03-22 09:35 UTC, ZHAY10086 commented on projects/1.16/assets/dark-utilities/darkutils/lang/zh_cn.json
> +  "block.minecraft.banner.darkutils_vector_plate.white": "白色向量图案"
是旗子啊![图片](https://user-images.githubusercontent.com/34602681/159450564-00360b0c-13df-443e-86c0-001b36fec3ea.png)

2022-03-22 09:35 UTC, ZHAY10086 commented on projects/1.16/assets/dark-utilities/darkutils/lang/zh_cn.json
> +  "block.minecraft.banner.darkutils_vector_plate.white": "白色向量图案"
![图片](https://user-images.githubusercontent.com/34602681/159450607-ab710a52-c7e3-4fd8-9da6-181e5f855d4f.png)

2022-03-22 09:41 UTC, n0099 commented on projects/1.16/assets/dark-utilities/darkutils/lang/zh_cn.json
> +  "block.minecraft.banner.darkutils_vector_plate.white": "白色向量图案"
改成箭头

2022-03-22 09:41 UTC, n0099 commented on projects/1.16/assets/dark-utilities/darkutils/lang/zh_cn.json
> +  "block.minecraft.banner.darkutils_vector_plate.white": "白色向量图案"
您这堪比psi翻译的“向量”

2022-03-22 09:43 UTC, XiaoXin1113 commented on projects/1.16/assets/dark-utilities/darkutils/lang/zh_cn.json
> +  "block.minecraft.banner.darkutils_vector_plate.white": "白色向量图案"
我觉得向量是对的
因为key里面是vector

2022-03-22 10:05 UTC, ZHAY10086 commented on projects/1.16/assets/dark-utilities/darkutils/lang/zh_cn.json
> +  "block.minecraft.banner.darkutils_vector_plate.white": "白色向量图案"
![图片](https://user-images.githubusercontent.com/34602681/159456348-98bf2380-6a4e-4e51-ace7-739cfc683eeb.png)

2022-03-22 13:29 UTC, TartaricAcid commented on projects/1.16/assets/dark-utilities/darkutils/lang/zh_cn.json
> +  "block.minecraft.banner.darkutils_vector_plate.white": "白色向量图案"
我记得游戏内有个向量板吧？向量确实没错

2022-03-22 14:17 UTC, n0099 commented on projects/1.16/assets/dark-utilities/darkutils/lang/zh_cn.json
> +  "block.minecraft.banner.darkutils_vector_plate.white": "白色向量图案"
> 我觉得向量是对的 因为key里面是vector

psi也叫vector

2022-03-22 14:30 UTC, ZHAY10086 commented on projects/1.16/assets/dark-utilities/darkutils/lang/zh_cn.json
> +  "block.minecraft.banner.darkutils_vector_plate.white": "白色向量图案"
Psi 的"向量"翻译的有什么问题吗

2022-03-22 15:06 UTC, n0099 commented on projects/1.16/assets/dark-utilities/darkutils/lang/zh_cn.json
> +  "block.minecraft.banner.darkutils_vector_plate.white": "白色向量图案"
实际用途类似变量

2022-03-28 08:07 UTC, TartaricAcid approved these changes

2022-03-28 08:53 UTC, n0099 approved these changes

2022-03-29 15:33 UTC, merged