[R] Animalium 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1708
Opened 2022-03-25 01:42 UTC by XiaoXin1113

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2022-03-26 10:56 UTC, n0099 requested changes

2022-03-26 10:56 UTC, n0099 commented on projects/1.16/assets/animalium/animalium/lang/zh_cn.json
> +  "item.animalium.rat_spawn_egg": "生成老鼠",
```suggestion
  "item.animalium.piranha_spawn_egg": "食人鱼刷怪蛋",
  "item.animalium.wild_dog_spawn_egg": "野狗刷怪蛋",
  "item.animalium.bear_spawn_egg": "棕熊刷怪蛋",
  "item.animalium.bear_tamed_spawn_egg": "中立棕熊刷怪蛋",
  "item.animalium.rat_spawn_egg": "老鼠刷怪蛋",
```

2022-03-26 12:30 UTC, mamaruo commented on projects/1.16/assets/animalium/animalium/lang/zh_cn.json
> +  "tooltip.bear_claw_paxel": "最原始的多功能工具",
真的是这样吗

2022-03-26 15:59 UTC, GreyElaina commented on projects/1.16/assets/animalium/animalium/lang/zh_cn.json
> +  "tooltip.bear_claw_paxel": "最原始的多功能工具",
```
"tooltip.wild_dog_pelt_boots": "Jump High and Run Fast",
"tooltip.bear_claw_paxel": "The Original Multi-tool",
```

2022-03-27 08:45 UTC, XiaoXin1113 commented on projects/1.16/assets/animalium/animalium/lang/zh_cn.json
> +  "tooltip.bear_claw_paxel": "最原始的多功能工具",
Ln19 与原文对应
Ln18 与原文对应

2022-03-27 20:48 UTC, n0099 commented on projects/1.16/assets/animalium/animalium/lang/zh_cn.json
> +  "tooltip.bear_claw_paxel": "最原始的多功能工具",
```suggestion
  "tooltip.bear_claw_paxel": "最初的多功能工具",
```

2022-03-27 20:48 UTC, n0099 approved these changes

2022-03-28 05:20 UTC, mamaruo approved these changes

2022-03-29 15:33 UTC, merged