[R]Antighost 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1710
Opened 2022-03-25 02:18 UTC by XiaoXin1113

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-25 06:12 UTC, Cyl18 commented
> hint: 这个模组在curseforge页面上既有fabric也有forge，看起来好怪

2022-03-26 10:43 UTC, n0099 approved these changes

2022-03-26 12:33 UTC, mamaruo requested changes

2022-03-26 12:33 UTC, mamaruo commented on projects/1.16/assets/antighost/antighost/lang/zh_cn.json
> +  "msg.request": "请求重发你身边的方块数据"
```suggestion
  "msg.request": "正在请求重发你身边的方块数据"
```

2022-03-27 20:49 UTC, merged