[R] Glassential 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1717
Opened 2022-03-25 11:09 UTC by ChuijkYahus

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-26 10:42 UTC, n0099 requested changes

2022-03-26 10:42 UTC, n0099 commented on projects/1.16/assets/glassential/glassential/lang/zh_cn.json
> +    "tooltip.glassential.ghostly": "对实体而言不是固体",
```suggestion
    "tooltip.glassential.ethereal": "玩家不能穿过此玻璃（固体方块）",
    "tooltip.glassential.ethereal_reverse": "只有玩家可以穿过此玻璃（非固体方块）",
    "tooltip.glassential.ghostly": "所有实体都无法穿过此玻璃（固体方块）",
```
https://minecraft.fandom.com/wiki/Solid_block

2022-03-26 13:22 UTC, mamaruo requested changes

2022-03-26 13:22 UTC, mamaruo commented on projects/1.16/assets/glassential/glassential/lang/zh_cn.json
> +    "tooltip.glassential.dark": "阻光",
```suggestion
    "tooltip.glassential.dark": "挡光",
```
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/cc9c9dc025f0a45fa8b9bae637649108c75fb04b/projects/1.12.2/assets/1UNKNOWN/enderio/lang/zh_cn.lang#L695

2022-03-26 13:22 UTC, mamaruo commented on projects/1.16/assets/glassential/glassential/lang/zh_cn.json
> +    "tooltip.glassential.ghostly": "对实体而言不是固体",
```suggestion
    "tooltip.glassential.ethereal": "玩家可穿行",
    "tooltip.glassential.ethereal_reverse": "仅玩家无法穿行",
    "tooltip.glassential.ghostly": "所有实体皆可穿行",
```

2022-03-26 13:57 UTC, mamaruo commented on projects/1.16/assets/glassential/glassential/lang/zh_cn.json
> +    "tooltip.glassential.ghostly": "对实体而言不是固体",
@n0099 你怎么看这个译法

2022-03-27 20:36 UTC, n0099 commented on projects/1.16/assets/glassential/glassential/lang/zh_cn.json
> +    "tooltip.glassential.ghostly": "对实体而言不是固体",
good

2022-03-27 20:37 UTC, n0099 approved these changes

2022-03-28 05:18 UTC, mamaruo approved these changes

2022-03-29 15:37 UTC, merged