[R] Relics 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #1719
Opened 2022-03-25 18:53 UTC by ChuijkYahus

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

主要是搬运工作，修改了部分能力名和能力描述，增添新翻译

2022-03-26 13:11 UTC, mamaruo requested changes

2022-03-26 13:11 UTC, mamaruo commented on projects/1.16/assets/relics-mod/relics/lang/zh_cn.json
> +  "tooltip.relics.infinity_ham.ability.1.description": "每次使用回复%1$s点饥饿度的无限食物，最多充能%2$s点，每秒回复%3$s点",
```suggestion
  "tooltip.relics.infinity_ham.ability.1.description": "每次使用恢复%1$s点饥饿值的无限食物。最多充能%2$s点，每秒恢复%3$s点",
```

2022-03-26 13:11 UTC, mamaruo commented on projects/1.16/assets/relics-mod/relics/lang/zh_cn.json
> +  "tooltip.relics.slime_heart.ability.2.description": "免疫摔落伤害并使佩戴者弹起，按%1$s禁止能力发动",
```suggestion
  "tooltip.relics.slime_heart.ability.2.description": "免疫摔落伤害并在触地时弹起佩戴者。按住%1$s阻止触发该能力",
```

2022-03-26 13:11 UTC, mamaruo commented on projects/1.16/assets/relics-mod/relics/lang/zh_cn.json
> +  "tooltip.relics.wool_mitten.ability.1.description": "雪球撞击造成%1$s点伤害，雪球每飞行一秒造成的伤害增加%2$s",
```suggestion
  "tooltip.relics.wool_mitten.ability.1.description": "雪球撞击造成%1$s点伤害。雪球每多飞行一秒，造成的伤害增加%2$s",
```

2022-03-26 13:11 UTC, mamaruo commented on projects/1.16/assets/relics-mod/relics/lang/zh_cn.json
> +  "advancements.relics.ghost_skin_talisman.title": "Spooky Scary Skeletons",
语出 [Spooky Scary Skeletons Original Song Video - YouTube](https://www.youtube.com/watch?v=-1dSY6ZuXEY)

2022-03-26 13:52 UTC, ChuijkYahus commented on projects/1.16/assets/relics-mod/relics/lang/zh_cn.json
> +  "advancements.relics.ghost_skin_talisman.title": "Spooky Scary Skeletons",
找不到很好的歌名译法就保留了

2022-03-26 13:54 UTC, mamaruo commented
我没注意原来都用的逗号，commit suggestion 的时候要注意一下，或者一并统一成一个

@ChuijkYahus 快用 Add suggestion to batch 功能，邮箱要刷爆了

2022-03-26 13:55 UTC, ChuijkYahus commented
OK
一个个看过去就点了（

2022-03-26 13:55 UTC, mamaruo commented on projects/1.16/assets/relics-mod/relics/lang/zh_cn.json
> +  "advancements.relics.ghost_skin_talisman.title": "Spooky Scary Skeletons",
没问题

2022-03-26 14:01 UTC, mamaruo approved these changes

2022-03-27 20:53 UTC, n0099 approved these changes

2022-03-27 20:54 UTC, merged

2022-04-09 08:46 UTC, ChuijkYahus commented on projects/1.16/assets/relics-mod/relics/lang/zh_cn.json
> +  "advancements.relics.ghost_skin_talisman.title": "Spooky Scary Skeletons",
这个和原版的进度名重复了（

2022-04-09 13:02 UTC, mamaruo commented on projects/1.16/assets/relics-mod/relics/lang/zh_cn.json
> +  "advancements.relics.ghost_skin_talisman.title": "Spooky Scary Skeletons",
惊悚恐怖骷髅头