[R] Brewevolution 翻译添加
CFPAOrg/Minecraft-Mod-Language-Package pull request #1725
Opened 2022-03-27 06:16 UTC by Rinko1231

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-27 06:22 UTC, Rinko1231 commented
注：开胃菜是放在板子上的，可以一口口吃掉（阶段1、2、3）。

2022-03-27 07:51 UTC, mamaruo commented
机器人你怎么机器人

2022-03-27 07:53 UTC, Cyl18 commented
> 机器人你怎么机器人

提交路径有误

2022-03-27 21:11 UTC, n0099 commented
`：阶段x`全部改成`：已吃x块`

2022-03-27 21:24 UTC, n0099 requested changes

2022-03-27 21:24 UTC, n0099 commented on projects/1.16/assets/brewevolution/brewevolution/lang/zh_cn.json
> +  "block.brewevolution.calvados_bottle": "瓶装卡尔瓦多斯",
```suggestion
  "block.brewevolution.calvados_bottle": "瓶装苹果白兰地",

```

2022-03-27 21:24 UTC, n0099 commented on projects/1.16/assets/brewevolution/brewevolution/lang/zh_cn.json
> +  "block.brewevolution.calvados_glass": "杯装卡尔瓦多斯",
```suggestion
  "block.brewevolution.calvados_glass": "杯装苹果白兰地",

```

2022-03-27 21:24 UTC, n0099 commented on projects/1.16/assets/brewevolution/brewevolution/lang/zh_cn.json
> +  "item.brewevolution.calvados_bottle_item": "瓶装卡尔瓦多斯",
```suggestion
  "item.brewevolution.calvados_bottle_item": "瓶装苹果白兰地",

```

2022-03-27 21:24 UTC, n0099 commented on projects/1.16/assets/brewevolution/brewevolution/lang/zh_cn.json
> +  "block.brewevolution.planche_apero_stage_3": "开胃菜：阶段3",
```suggestion
  "block.brewevolution.planche_apero_stage_1": "开胃菜：已吃1块",
  "block.brewevolution.planche_apero_stage_2": "开胃菜：已吃2块",
  "item.brewevolution.crushed_apple": "碎苹果",
  "block.brewevolution.planche_apero_stage_3": "开胃菜：已吃3块",

```

2022-03-27 21:24 UTC, n0099 commented on projects/1.16/assets/brewevolution/brewevolution/lang/zh_cn.json
> +  "block.brewevolution.planche_apero": "开胃菜板"
```suggestion
  "block.brewevolution.planche_apero": "盘装开胃酒"
```
https://en.wikipedia.org/wiki/Ap%C3%A9ritif_and_digestif
> An apéritif is an alcoholic beverage usually served before a meal to stimulate the appetite, and is usually dry rather than sweet.

https://en.wikipedia.org/wiki/Platter_(dishware)
> A platter is a large type of dishware used for serving food.

2022-03-27 21:24 UTC, n0099 commented on projects/1.16/assets/brewevolution/brewevolution/lang/zh_cn.json
> +  "block.brewevolution.planche_apero_empty": "空的开胃菜板",
```suggestion
  "block.brewevolution.planche_apero_empty": "空盘装开胃酒",
```

2022-03-27 21:31 UTC, n0099 requested changes

2022-03-27 21:31 UTC, n0099 commented on projects/1.16/assets/brewevolution/brewevolution/lang/zh_cn.json
> +  "item.brewevolution.mead_horn": "角杯装蜜糖酒",
```suggestion
  "item.brewevolution.mead_horn": "角杯装蜂蜜酒",
```
mead跟上面那个molasses没有关系，molasses是用来做朗姆酒的

2022-03-27 21:31 UTC, n0099 commented on projects/1.16/assets/brewevolution/brewevolution/lang/zh_cn.json
> +  "block.brewevolution.mead_horn_block": "角杯装蜜糖酒",
```suggestion
  "block.brewevolution.mead_horn_block": "角杯装蜂蜜酒",
```

2022-03-27 21:31 UTC, n0099 commented
`大杯`按照原文是mug建议改成马克杯

2022-03-27 22:16 UTC, n0099 commented
关于calvados应该叫卡尔瓦多斯还是苹果白兰地根据这位法国人@kokoro-aya 的意见
![image](https://user-images.githubusercontent.com/13030387/160303270-1b16600a-9ae5-41a8-8082-b7f830b2a0b3.png)
![image](https://user-images.githubusercontent.com/13030387/160303259-71a12c86-0e26-48bc-9e80-6fd23b6ddaaf.png)
![image](https://user-images.githubusercontent.com/13030387/160303274-1ca77f80-5115-4b47-8201-8d4ed77fa419.png)
![image](https://user-images.githubusercontent.com/13030387/160303280-1dad8b77-8057-4176-8d4d-8ee13a3e1e29.png)

2022-03-28 09:56 UTC, n0099 requested changes

2022-03-28 09:56 UTC, n0099 commented on projects/1.16/assets/brewevolution/brewevolution/lang/zh_cn.json
> +  "block.brewevolution.planche_apero_stage_3": "开胃酒：已吃3块",
```suggestion
  "block.brewevolution.planche_apero_stage_1": "开胃酒：已喝1杯",
  "block.brewevolution.planche_apero_stage_2": "开胃酒：已喝2杯",
  "item.brewevolution.crushed_apple": "碎苹果",
  "block.brewevolution.planche_apero_stage_3": "开胃酒：已喝3杯",
```
您能进游戏截个图rwkk吗

2022-03-28 16:19 UTC, n0099 commented on projects/1.16/assets/brewevolution/brewevolution/lang/zh_cn.json
> +  "block.brewevolution.planche_apero_stage_3": "开胃酒：已吃3块",
法国人最高指示：![](https://user-images.githubusercontent.com/13030387/160442649-31d945fb-e0d4-4ba6-a58a-e40c59837a32.png)

2022-03-29 02:41 UTC, Rinko1231 commented on projects/1.16/assets/brewevolution/brewevolution/lang/zh_cn.json
> +  "block.brewevolution.planche_apero_stage_3": "开胃酒：已吃3块",
![Uploading Aperitif.png…]()
从左到右越吃越多，最后剩下一把虚空来的刀（
配方是台阶南瓜饼生牛肉，不含酒。

2022-03-30 11:54 UTC, TartaricAcid approved these changes

2022-04-01 08:31 UTC, merged