[R] Furnish 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1729
Opened 2022-03-27 10:00 UTC by Rinko1231

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-27 10:03 UTC, Rinko1231 commented
注：1.16的邮箱系统疑似没做好，邮箱打不开

2022-03-27 21:48 UTC, n0099 requested changes

2022-03-27 21:48 UTC, n0099 commented on projects/1.16/assets/furnish/furnish/lang/zh_cn.json
> +  "advancement.furnish.in_the_mail.name": "在邮件里！",
```suggestion
  "advancement.furnish.in_the_mail.name": "它在邮件里！",
```
原文有主语it

2022-03-27 21:48 UTC, n0099 commented on projects/1.16/assets/furnish/furnish/lang/zh_cn.json
> +  "block.furnish.oak_shutter": "橡木活动护窗",
建议活板窗，因为原版的trapdoor叫做活板门，下同

2022-03-27 21:48 UTC, n0099 commented on projects/1.16/assets/furnish/furnish/lang/zh_cn.json
> +  "msg.furnish.letter.attachment_added": "将%s附到信上",
```suggestion
  "msg.furnish.letter.attachment_added": "%s已被附加到信上",
```
原文是过去时动词

2022-03-27 21:48 UTC, n0099 commented on projects/1.16/assets/furnish/furnish/lang/zh_cn.json
> +  "subtitle.furnish.cymbal_plays": "Cymbal",
```suggestion
  "block.furnish.drum_tom": "筒鼓",
  "block.furnish.drum_snare": "小鼓",
  "block.furnish.cymbal": "钹",
  "subtitle.furnish.drum_plays": "鼓：作响",
  "subtitle.furnish.cymbal_plays": "钹：作响",
```

2022-03-28 09:51 UTC, Rinko1231 commented on projects/1.16/assets/furnish/furnish/lang/zh_cn.json
> +  "block.furnish.oak_shutter": "橡木活动护窗",
已修改

2022-03-28 09:57 UTC, n0099 approved these changes

2022-03-28 15:49 UTC, mamaruo requested changes

2022-03-30 12:07 UTC, TartaricAcid commented on projects/1.16/assets/furnish/furnish/lang/zh_cn.json
> +  "advancement.furnish.a_fine_gourmet.description": "收集来自世界各地的所有稀有餐盘。",
加个标点就能好很多：`收集所有的，来自世界各地的稀有餐盘`

2022-03-30 12:10 UTC, TartaricAcid approved these changes

2022-03-31 03:58 UTC, Tweven27 commented on projects/1.16/assets/furnish/furnish/lang/zh_cn.json
> +  "advancement.furnish.a_fine_gourmet.description": "收集来自世界各地的所有稀有餐盘。",
这个应该是个成就吧，简略一点会不会比较好？比如：集齐全部稀有餐盘

2022-03-31 04:24 UTC, mamaruo commented on projects/1.16/assets/furnish/furnish/lang/zh_cn.json
> +  "advancement.furnish.a_fine_gourmet.description": "收集来自世界各地的所有稀有餐盘。",
> 这个应该是个成就吧，简略一点会不会比较好？比如：集齐全部稀有餐盘

这是进度描述

2022-03-31 14:57 UTC, mamaruo approved these changes

2022-04-01 08:34 UTC, TartaricAcid commented
这个 PR 怎么回事，怎么把 Furnish 的翻译删了

2022-04-01 09:00 UTC, Rinko1231 commented
> 这个 PR 怎么回事，怎么把 Furnish 的翻译删了

我是铸币，改回来了

2022-04-01 11:49 UTC, TartaricAcid commented
此 PR 已经彻底弄坏了，我重新提交一份 PR 吧

2022-04-01 11:49 UTC, closed without merging