[R] Building Wands 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1739
Opened 2022-03-28 08:45 UTC by XiaoXin1113

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-03-28 08:54 UTC, XiaoXin1113 commented
本模组的英文与原作者Github仓库分支：1.16.1 中的英文相同。
中文翻译与英文相同。

2022-03-28 09:02 UTC, n0099 requested changes

2022-03-28 09:02 UTC, n0099 commented on projects/1.16/assets/building-wands/wands/lang/zh_cn.json
> +  "item.wands.iron_wand": "铁建筑之杖",
```suggestion
  "item.wands.stone_wand": "石制建筑之杖",
  "item.wands.iron_wand": "铁制建筑之杖",
```

2022-03-28 15:36 UTC, mamaruo commented
> 本模组的英文与原作者Github仓库分支：1.16.1 中的英文相同。 中文翻译与英文相同。

显然过时了，用模组文件内的

2022-03-28 15:36 UTC, mamaruo commented on projects/1.16/assets/building-wands/wands/lang/zh_cn.json
> +  "item.wands.diamond_wand": "钻石建筑之杖",
```suggestion
  "item.wands.diamond_wand": "钻石制建筑之杖",
```

2022-03-28 15:37 UTC, mamaruo commented on projects/1.16/assets/building-wands/wands/lang/zh_cn.json
> +  "item.wands.netherite_wand": "下界合金建筑之杖",
```suggestion
  "item.wands.netherite_wand": "下界合金制建筑之杖",
```
要么一起有，要么一起无

2022-03-28 23:59 UTC, XiaoXin1113 commented
> 1.18 同模组翻译请求

收到，马上开始翻译

2022-03-29 00:01 UTC, XiaoXin1113 commented
> > 本模组的英文与原作者Github仓库分支：1.16.1 中的英文相同。 中文翻译与英文相同。
> 
> 显然过时了，用模组文件内的

收到，正在更改

2022-03-30 12:27 UTC, merged