[R] TF2 stuff mod 修正 #CFPA-0614
CFPAOrg/Minecraft-Mod-Language-Package pull request #1771
Opened 2022-03-30 15:32 UTC by mamaruo

Co-authored-by: 有点懒的首长 <qinxaiogang@163.com>

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：`projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang`
  - 如果是 1.16 翻译，应该是：`projects/1.16/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
  - 如果是 1.18 翻译，应该是：`projects/1.18/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json`
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2022-03-30 16:16 UTC, mamaruo commented
已检查文件路径，没有问题

2022-04-01 21:36 UTC, n0099 requested changes

2022-04-01 21:36 UTC, n0099 commented on projects/1.12.2/assets/tf2-stuff-mod/rafradek_tf2_weapons/lang/zh_cn.lang
> +objective.kills_sentry=用一挺步哨枪进行五次击杀
能不能统一击杀和杀死

2022-04-01 21:36 UTC, n0099 commented on projects/1.12.2/assets/tf2-stuff-mod/rafradek_tf2_weapons/lang/zh_cn.lang
> +objective.destroy_building=摧毁一个建筑
```suggestion
objective.destroy_building=摧毁一栋建筑物
```

2022-04-01 21:36 UTC, n0099 commented on projects/1.12.2/assets/tf2-stuff-mod/rafradek_tf2_weapons/lang/zh_cn.lang
> +objective.destroy_sentry_uber=在 Uber 期间摧毁一挺步哨枪
```suggestion
objective.destroy_sentry_uber=在 ÜberCharge 期间摧毁一挺步哨枪
```

2022-04-01 21:36 UTC, n0099 commented on projects/1.12.2/assets/tf2-stuff-mod/rafradek_tf2_weapons/lang/zh_cn.lang
> +objective.advanced=(高级目标)
```suggestion
objective.advanced=（高级目标）
```

2022-04-01 21:36 UTC, n0099 commented on projects/1.12.2/assets/tf2-stuff-mod/rafradek_tf2_weapons/lang/zh_cn.lang
> +objective.kills=迅速的杀死 4 名雇佣兵
```suggestion
objective.kills=迅速地杀死 4 名雇佣兵
```

2022-04-01 21:36 UTC, n0099 commented on projects/1.12.2/assets/tf2-stuff-mod/rafradek_tf2_weapons/lang/zh_cn.lang
> +achievement.weaponUpgrade=更上一层
还不如修改前的`升级武器`

2022-04-01 21:36 UTC, n0099 commented on projects/1.12.2/assets/tf2-stuff-mod/rafradek_tf2_weapons/lang/zh_cn.lang
> +achievement.10Crates=十箱齐开
建议十连

2022-04-01 21:36 UTC, n0099 commented on projects/1.12.2/assets/tf2-stuff-mod/rafradek_tf2_weapons/lang/zh_cn.lang
> +achievement.doubleJumps.desc=在双重跳跃时杀死 20 个玩家。
```suggestion
achievement.doubleJumps.desc=在二段跳时杀死 20 个玩家。
```

2022-04-01 21:36 UTC, n0099 commented on projects/1.12.2/assets/tf2-stuff-mod/rafradek_tf2_weapons/lang/zh_cn.lang
> +gui.boss.night=boss只能在夜晚召唤
```suggestion
gui.boss.night=Boss 只能在夜晚召唤
```

2022-04-01 21:36 UTC, n0099 commented on projects/1.12.2/assets/tf2-stuff-mod/rafradek_tf2_weapons/lang/zh_cn.lang
> +tile.blockAustralium.name=澳金块
https://wiki.teamfortress.com/wiki/Australium/zh-hans 里叫澳元素
google搜索澳金根本没有tf2相关信息
要不就用`鐭`这个生僻字

2022-04-01 21:36 UTC, n0099 commented on projects/1.12.2/assets/tf2-stuff-mod/rafradek_tf2_weapons/lang/zh_cn.lang
> +effect.uber=ÜberCharge
https://wiki.teamfortress.com/wiki/%C3%9CberCharge/zh-hans
> ÜberCharge（超能冲锋）是[医生](https://wiki.teamfortress.com/wiki/Medic/zh-hans)的一项特殊技能。其在德语中的意思是“增压”或“过度充电”。

2022-04-01 21:37 UTC, n0099 commented
我建议统一使用https://wiki.teamfortress.com 上的中文译名，或者steam市场里有关物品的名称（也就是valve的游戏官译）

2022-04-03 07:40 UTC, Cyl18 commented
> 已检查文件路径，没有问题

检查了一下是我那用的API没有返回这个项目的数据，可能是因为CurseForge上面这个项目被标记为了abandoned

2022-04-10 11:29 UTC, TartaricAcid commented on projects/1.12.2/assets/tf2-stuff-mod/rafradek_tf2_weapons/lang/zh_cn.lang
> +objective.kills_sentry=用一挺步哨枪进行五次击杀
击杀和杀死意思有不同之处，我看了下没啥问题

2022-04-10 11:31 UTC, TartaricAcid commented on projects/1.12.2/assets/tf2-stuff-mod/rafradek_tf2_weapons/lang/zh_cn.lang
> +achievement.10Crates=十箱齐开
就这样吧

2022-04-10 11:37 UTC, TartaricAcid commented
看了下翻译内容，原翻译内容并无较大错误，我暂时不接受此 PR

2022-04-10 15:53 UTC, mamaruo commented on projects/1.12.2/assets/tf2-stuff-mod/rafradek_tf2_weapons/lang/zh_cn.lang
> +gui.build.exit传送装置出口
```suggestion
gui.build.exit=传送装置出口
```

2022-04-10 15:53 UTC, mamaruo commented on projects/1.12.2/assets/tf2-stuff-mod/rafradek_tf2_weapons/lang/zh_cn.lang
> +gui.command.1=1. 医生!
```suggestion
gui.command.1=1. 医生！
```

2022-04-10 15:53 UTC, mamaruo commented on projects/1.12.2/assets/tf2-stuff-mod/rafradek_tf2_weapons/lang/zh_cn.lang
> +gui.contracts.objectives_t=(需要 %1$s 武器)
```suggestion
gui.contracts.objectives_t=（需要 %1$s 武器）
```

2022-04-10 17:08 UTC, IDONTKNOWANDDONTASKME commented
酒石酸先生，您好：
     我是这篇翻译的作者。这篇翻译是我在基于TF2游戏本身方面修改的翻译。虽然本人翻译水平不精并且里面出现了例如澳金、Uber（TF2中文社区之间常用的熟语）之类的翻译，但是这篇翻译在之前i18n里的翻译修正了一些与TF2游戏本身相悖或是个人认为错误的翻译（例如sentry（步哨）翻译成战斗哨石等），希望酒石酸先生能够再考虑一下....
                                                                                                                                                                      有点懒的首长留。

2022-04-10 17:12 UTC, IDONTKNOWANDDONTASKME commented
> 酒石酸先生，您好： 我是这篇翻译的作者。这篇翻译是我在基于TF2游戏本身方面修改的翻译。虽然本人翻译水平不精并且里面出现了例如澳金、Uber（TF2中文社区之间常用的熟语）之类的翻译，但是这篇翻译在之前i18n里的翻译修正了一些与TF2游戏本身相悖或是个人认为错误的翻译（例如sentry（步哨）翻译成战斗哨石等），希望酒石酸先生能够再考虑一下.... 有点懒的首长留。

2022-04-11 04:02 UTC, TartaricAcid commented
@IDONTKNOWANDDONTASKME 
先说一声抱歉，我对 TF2 游戏一无所知，所以很多观点只是从翻译的角度去考虑的，所以结论有可能有失偏颇

但是相当一部分内容修改与 TF2 游戏用语并没有关系，改动让人非常迷惑，比如下面的：
```diff
- tf2boss.appear=Boss %1$s [等级 %2$s] 出现了
- tf2boss.death=Boss %1$s [等级 %2$s] 已击败
+ tf2boss.appear= %1$s [Level %2$s] 已苏醒
+ tf2boss.death=The %1$s [Level %2$s] 已被击败
```

```diff
- commands.cmodc.usage=/cmodc <配置文件> <目录> <属性> [value]
- commands.cmodc.success=属性 %s 已成功设置为 %s
+ commands.cmodc.usage=/cmodc <config file> <category> <property> [value]
+ commands.cmodc.success=Property %s is successfully set to %s
```
这修改的……怎么还有英文？

我的建议是，在已有中文文本基础上修改不合适的用词

2022-04-18 14:47 UTC, TartaricAcid commented
@IDONTKNOWANDDONTASKME 此前疑问仍没有修正与回复，暂时关闭此 PR

2022-04-23 09:39 UTC, closed without merging