[R] FTB Sluice 翻译提交 #CFPA-0636
CFPAOrg/Minecraft-Mod-Language-Package pull request #1772
Opened 2022-03-30 15:40 UTC by mamaruo

Co-authored-by: tweven27<tweven27@vip.qq.com>

- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-04-01 11:46 UTC, TartaricAcid approved these changes

2022-04-01 15:12 UTC, mamaruo commented
self-approved

2022-04-01 21:47 UTC, n0099 requested changes

2022-04-01 21:47 UTC, n0099 commented on projects/1.16/assets/ftb-sluice/ftbsluice/lang/zh_cn.json
> +  "block.ftbsluice.crushed_netherrack": "粉碎下界岩",
```suggestion
  "block.ftbsluice.crushed_basalt": "粉碎的玄武岩",
  "block.ftbsluice.crushed_endstone": "粉碎的末地石",
  "block.ftbsluice.crushed_netherrack": "粉碎的下界岩",
```

2022-04-02 08:49 UTC, TartaricAcid commented on projects/1.16/assets/ftb-sluice/ftbsluice/lang/zh_cn.json
> +  "block.ftbsluice.crushed_netherrack": "粉碎下界岩",
两种表达大差不差，就这样吧

2022-04-02 08:49 UTC, merged

2022-04-02 09:11 UTC, mamaruo commented on projects/1.16/assets/ftb-sluice/ftbsluice/lang/zh_cn.json
> +  "block.ftbsluice.crushed_netherrack": "粉碎下界岩",
查 https://dict.mcmod.cn/ 得不用“的”的居多