[R] Create: Alloyed 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1787
Opened 2022-04-03 10:50 UTC by Dr-WeiAL

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-04-03 10:55 UTC, Cyl18 commented on projects/1.18/assets/create-alloyed/alloyed/lang/zh_cn.json
> +  "alloyed.ponder.bronze_bell_decoration.text_4": "…或铁栅栏。",
```suggestion
  "alloyed.ponder.bronze_bell_decoration.text_2": "用锁链挂起来可以达到很好的效果…",
  "alloyed.ponder.bronze_bell_decoration.text_3": "…栅栏…",
  "alloyed.ponder.bronze_bell_decoration.text_4": "…或铁栏杆。",
```
同步原版

2022-04-03 10:56 UTC, Cyl18 commented on projects/1.18/assets/create-alloyed/alloyed/lang/zh_cn.json
> +  "alloyed.ponder.bronze_bell_decoration.text_4": "…或铁栅栏。",
这三行的英文原文看起来是连起来的..?

2022-04-03 12:29 UTC, Cyl18 commented on projects/1.18/assets/create-alloyed/alloyed/lang/zh_cn.json
> +  "item.alloyed.steel_sheet": "钢板",
翻译为`钢片`/`钢薄板`更好 这俩项目里都有用

2022-04-03 12:39 UTC, Cyl18 commented on projects/1.18/assets/create-alloyed/alloyed/lang/zh_cn.json
> +  "item.alloyed.steel_sheet": "钢板",
![image](https://user-images.githubusercontent.com/14993992/161428474-a1705dd4-3ec8-4d95-8fe7-1d125bbf5c06.png)
okay

2022-04-04 02:27 UTC, Rinko1231 commented on projects/1.18/assets/create-alloyed/alloyed/lang/zh_cn.json
> +  "alloyed.ponder.bronze_bell_instrument.header": "用青铜钟制作音乐",
```suggestion
  "alloyed.ponder.bronze_bell_instrument.header": "用青铜钟制造音乐",
```

2022-04-04 02:29 UTC, Rinko1231 commented on projects/1.18/assets/create-alloyed/alloyed/lang/zh_cn.json
> +  "alloyed.ponder.bronze_bell_instrument.header": "用青铜钟制作音乐",
“制作音乐”像是谱一整首曲子，比较Pro。
“制造音乐”则不会，参考“制造噪音”，单纯的动作。

2022-04-05 17:35 UTC, mamaruo requested changes

2022-04-05 17:35 UTC, mamaruo commented on projects/1.18/assets/create-alloyed/alloyed/lang/zh_cn.json
> +  "alloyed.ponder.bronze_bell_decoration.text_4": "…或铁栏杆。",
```suggestion
  "alloyed.ponder.bronze_bell_decoration.text_2": "用锁链挂起来可以达到很好的效果……",
  "alloyed.ponder.bronze_bell_decoration.text_3": "……还可以用栅栏……",
  "alloyed.ponder.bronze_bell_decoration.text_4": "……亦或是铁栏杆。",
```
语序变了，就只好这样了，不知道有没有更好的译法

2022-04-06 16:54 UTC, mamaruo approved these changes

2022-04-06 16:56 UTC, mamaruo commented on projects/1.18/assets/create-alloyed/alloyed/lang/zh_cn.json
> +  "advancements.alloyed.bronze_ingot.description": "获得一些青铜，一种具有装饰性并且很响亮的金属。",
“敲起来很响亮”
https://www.vedantu.com/question-answer/which-of-the-following-is-the-most-sonorous-class-10-chemistry-cbse-5f85413847799d16cf67ee4b

2022-04-08 05:21 UTC, GreyElaina commented on projects/1.18/assets/create-alloyed/alloyed/lang/zh_cn.json
> +  "advancements.alloyed.bronze_instruments.title": "金属音乐",
嗯。。不应该是 `重金属音乐` 么。。

2022-04-08 10:37 UTC, mamaruo commented on projects/1.18/assets/create-alloyed/alloyed/lang/zh_cn.json
> +  "advancements.alloyed.bronze_instruments.title": "金属音乐",
哦，我忘了看英维
`Heavy metal (or **simply metal**) is a genre of [rock music](https://en.wikipedia.org/wiki/Rock_music) that developed in the late 1960s and early 1970s, largely in the United Kingdom and United States.`

2022-04-08 11:40 UTC, GreyElaina approved these changes

2022-04-08 16:10 UTC, Cyl18 approved these changes

2022-04-10 11:10 UTC, merged