[R] Woot 翻译修改
CFPAOrg/Minecraft-Mod-Language-Package pull request #1790
Opened 2022-04-03 13:34 UTC by ZHAY10086

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2022-04-03 14:04 UTC, Cyl18 commented on projects/1.16/assets/woot/woot/lang/zh_cn.json
> +  "advancements.woot.rate_perk_1.description": "制造一个吞食鱼Ⅰ升级插件",
字母`I`?

2022-04-03 14:16 UTC, ZHAY10086 commented on projects/1.16/assets/woot/woot/lang/zh_cn.json
> +  "advancements.woot.rate_perk_1.description": "制造一个吞食鱼Ⅰ升级插件",
罗马数字Ⅰ

2022-04-04 16:14 UTC, mamaruo commented on projects/1.16/assets/woot/woot/lang/zh_cn.json
> +  "advancements.woot.rate_perk_1.description": "制造一个吞食鱼Ⅰ升级插件",
原版的附魔等级、状态效果等级都用的英文字母

2022-04-05 17:40 UTC, mamaruo requested changes
初略看了下，改得很好

2022-04-05 17:40 UTC, mamaruo commented on projects/1.16/assets/woot/woot/lang/zh_cn.json
> +  "advancements.woot.capture_mob.title": "此过程中所有生物均受到伤害",
```suggestion
  "advancements.woot.capture_mob.title": "众生皆伤",
```
是进度名

2022-04-05 17:40 UTC, mamaruo commented on projects/1.16/assets/woot/woot/lang/zh_cn.json
> +  "item.woot.xp_3": "智慧Ⅲ升级插件",
用英文字母

2022-04-05 17:54 UTC, ZHAY10086 commented on projects/1.16/assets/woot/woot/lang/zh_cn.json
> +  "advancements.woot.capture_mob.title": "此过程中所有生物均受到伤害",
这里原句梗的是No Animals Were Harmed，所以就翻成这样了

2022-04-05 18:03 UTC, mamaruo commented on projects/1.16/assets/woot/woot/lang/zh_cn.json
> +  "advancements.woot.capture_mob.title": "此过程中所有生物均受到伤害",
合理
原译是`没有动物受到伤害`，`此过程中`似乎用了 `No Animals Were Harmed in the Making of This Film` 的梗，不过模组里没有 `in the making of...`，所以
也许这样梗的辨识度会变低
```suggestion
  "advancements.woot.capture_mob.title": "所有生物均受到伤害",
```

2022-04-05 18:15 UTC, ZHAY10086 commented on projects/1.16/assets/woot/woot/lang/zh_cn.json
> +  "item.woot.xp_3": "智慧Ⅲ升级插件",
多谢提醒，已更换为英文字母

2022-04-05 18:17 UTC, mamaruo commented on projects/1.16/assets/woot/woot/lang/zh_cn.json
> +  "item.woot.xp_3": "智慧Ⅲ升级插件",
字母后还有一个空格，这样看着略难受

2022-04-05 18:23 UTC, ZHAY10086 commented on projects/1.16/assets/woot/woot/lang/zh_cn.json
> +  "item.woot.xp_3": "智慧Ⅲ升级插件",
已修改

2022-04-06 14:34 UTC, Cyl18 commented on projects/1.16/assets/woot/woot/lang/zh_cn.json
> +  "guide.woot.factory_blocks.perkslot.0": "升级插件是安装在$(item)升级插件插槽$(0)上的。一个$(item)升级插件插槽$(0)只能接受一种升级插件。一个空的$(item)升级插件插槽$(0)能够安装任意一种等级Ⅰ升级插件。安装高等级的升级插件之前必须安装所有同种的低等级升级插件。不同等级的工厂拥有不同的升级插件可接受最大等级。",
```suggestion
  "guide.woot.factory_blocks.perkslot.0": "升级插件是安装在$(item)升级插件插槽$(0)上的。一个$(item)升级插件插槽$(0)只能接受一种升级插件。一个空的$(item)升级插件插槽$(0)能够安装任意一种等级 I 升级插件。安装高等级的升级插件之前必须安装所有同种的低等级升级插件。不同等级的工厂拥有不同的升级插件可接受最大等级。",
```

2022-04-09 14:24 UTC, mamaruo requested changes

2022-04-09 14:24 UTC, mamaruo commented on projects/1.16/assets/woot/woot/lang/zh_cn.json
> +  "advancements.woot.flayed_1.title": "Skinned Alive（1990）",
电影名+年代，是否有先例
```suggestion
  "advancements.woot.flayed_1.title": "活剥",
```

2022-04-09 15:06 UTC, ZHAY10086 commented on projects/1.16/assets/woot/woot/lang/zh_cn.json
> +  "advancements.woot.flayed_1.title": "Skinned Alive（1990）",
IMDb上是这种格式，这电影国内没放过，我实在想不出怎么能把梗给表达出来，就直接这么搞了

2022-04-10 11:52 UTC, merged