[R] Corail's Tombstone 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #1791
Opened 2022-04-04 05:04 UTC by ChuijkYahus

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-04-10 19:29 UTC, n0099 requested changes

2022-04-10 19:29 UTC, n0099 commented on projects/1.16/assets/corail-tombstone/tombstone/lang/zh_cn.json
> +  "tombstone.item.fishing_rod_of_misadventure.use2": "坟墓的魔力将使这根鱼竿变得更快速且牢不可破",
```suggestion
  "tombstone.item.fishing_rod_of_misadventure.use2": "坟墓的魔力将使这根鱼竿钓的更快且牢不可破",
```

2022-04-10 19:29 UTC, n0099 commented on projects/1.16/assets/corail-tombstone/tombstone/lang/zh_cn.json
> +  "tombstone.item.soul_receptacle.use1": "处于物品栏中时，它可以抵消你的一次死亡",
```suggestion
  "tombstone.item.soul_receptacle.use1": "置于物品栏中时，它可以抵消你的一次死亡",
```

2022-04-10 19:29 UTC, n0099 commented on projects/1.16/assets/corail-tombstone/tombstone/lang/zh_cn.json
> +  "tombstone.item.familiar_receptacle.use1": "被囚禁的灵魂必须通过吸收你的生命能力才能恢复自己的生命",
```suggestion
  "tombstone.item.familiar_receptacle.use1": "被囚禁的灵魂必须通过吸收你的生命能力才能恢复他的生命",
```

2022-04-10 19:29 UTC, n0099 commented on projects/1.16/assets/corail-tombstone/tombstone/lang/zh_cn.json
> +  "tombstone.tooltip.more_info": "按住Shift键以获取更多信息",
为什么不跟前面一样用潜行

2022-04-10 19:29 UTC, n0099 commented on projects/1.16/assets/corail-tombstone/tombstone/lang/zh_cn.json
> +  "tombstone.advancement.use_home.title": "常回家看看",
什么本地化

2022-04-10 19:29 UTC, n0099 commented on projects/1.16/assets/corail-tombstone/tombstone/lang/zh_cn.json
> +  "tombstone.advancement.prevent_death_suffocation.title": "我不能呼吸",
疑似乔治弗洛伊德

2022-04-10 19:29 UTC, n0099 commented on projects/1.16/assets/corail-tombstone/tombstone/lang/zh_cn.json
> +  "tombstone.advancement.prevent_death_lightning.title": "闪络效应",
这是原文改了？

2022-04-10 19:29 UTC, n0099 commented on projects/1.16/assets/corail-tombstone/tombstone/lang/zh_cn.json
> +  "tombstone.config.allow_halloween_ghost": "允许万圣夜鬼魂",
```suggestion
  "tombstone.config.allow_halloween_ghost": "显示万圣夜鬼魂",
```

2022-04-10 19:29 UTC, n0099 commented on projects/1.16/assets/corail-tombstone/tombstone/lang/zh_cn.json
> +  "tombstone.config_cat.recovery.tooltip": "关系到恢复命令和自动备份的选项",
不如之前的

2022-04-10 19:29 UTC, n0099 commented on projects/1.16/assets/corail-tombstone/tombstone/lang/zh_cn.json
> +  "tombstone.config.chance_familiar_receptacle_on_boss.tooltip": "从亡灵BOSS身上获得挚友瓶的概率（输入的数值除以1000才是最终概率）",
```suggestion
  "tombstone.config.chance_grave_dust.tooltip": "亡灵生物掉落墓灰的概率（最终概率=输入值/1000）",
  "tombstone.config.chance_soul_receptacle_on_boss.tooltip": "从亡灵BOSS身上获得缚魂瓶的概率（最终概率=输入值/1000）",
  "tombstone.config.chance_random_scroll_on_boss.tooltip": "从亡灵BOSS身上获得随机卷轴的概率（最终概率=输入值/1000）",
  "tombstone.config.chance_voodoo_poppet_on_boss.tooltip": "从亡灵BOSS身上获得随机巫毒玩偶的概率（最终概率=输入值/1000）",
  "tombstone.config.chance_familiar_receptacle_on_boss.tooltip": "从亡灵BOSS身上获得挚友瓶的概率（最终概率=输入值/1000）",
```

2022-04-10 19:29 UTC, n0099 commented
不懂就问116时原版附魔就重命名为魔咒了吗

2022-04-10 19:34 UTC, n0099 commented
之前的pr #1601

2022-04-11 02:23 UTC, ChuijkYahus commented
> 不懂就问116时原版附魔就重命名为魔咒了吗

起码在1.15的时候看维基上就用魔咒了
1.16的时候附魔页面里已经称其为魔咒

2022-04-11 16:20 UTC, n0099 commented on projects/1.16/assets/corail-tombstone/tombstone/lang/zh_cn.json
> +  "tombstone.config_cat.recovery.tooltip": "关系到恢复命令和自动备份的选项",
建议换回原来的

2022-04-11 16:21 UTC, n0099 commented on projects/1.16/assets/corail-tombstone/tombstone/lang/zh_cn.json
> +  "tombstone.advancement.prevent_death_lightning.title": "闪络效应",
建议换回原来的

2022-04-11 16:26 UTC, n0099 approved these changes

2022-04-12 02:59 UTC, Cyl18 commented on projects/1.18/assets/corail-tombstone/tombstone/lang/zh_cn.json
> +  "tombstone.item.fishing_rod_of_misadventure.use2": "坟墓的魔力将使这根鱼竿钓的更快且牢不可破",
貌似有语法错误 `鱼竿` `钓的更快`

2022-04-12 03:02 UTC, n0099 commented on projects/1.18/assets/corail-tombstone/tombstone/lang/zh_cn.json
> +  "tombstone.item.fishing_rod_of_misadventure.use2": "坟墓的魔力将使这根鱼竿钓的更快且牢不可破",
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1791#discussion_r846830005
他怎么没改？

2022-04-12 03:02 UTC, n0099 commented on projects/1.18/assets/corail-tombstone/tombstone/lang/zh_cn.json
> +  "tombstone.item.fishing_rod_of_misadventure.use2": "坟墓的魔力将使这根鱼竿钓的更快且牢不可破",
```suggestion
  "tombstone.item.fishing_rod_of_misadventure.use2": "坟墓的魔力将使这根鱼竿钓的更快且牢不可破",
```

2022-04-19 05:06 UTC, TartaricAcid approved these changes

2022-04-19 05:50 UTC, n0099 approved these changes

2022-04-19 05:50 UTC, merged