[R] Biomes O' Plenty 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #1792
Opened 2022-04-04 11:29 UTC by ChuijkYahus

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-04-08 15:31 UTC, ChuijkYahus commented
译名征求：coniferous forest
针叶林已被原版taiga使用

2022-04-10 14:00 UTC, TartaricAcid commented on projects/1.16/assets/biomes-o-plenty/biomesoplenty/lang/zh_cn.json
> +  "item.biomesoplenty.hellbark_boat": "地狱皮船",
这几处改动不对，原版也是 `xx木船` 形式

2022-04-10 14:02 UTC, ChuijkYahus commented on projects/1.16/assets/biomes-o-plenty/biomesoplenty/lang/zh_cn.json
> +  "item.biomesoplenty.hellbark_boat": "地狱皮船",
Hellbark - 地狱皮木
原版的金合欢木不也是做出金合欢木船的吗

2022-04-10 14:02 UTC, TartaricAcid commented on projects/1.16/assets/biomes-o-plenty/biomesoplenty/lang/zh_cn.json
> +  "block.biomesoplenty.dried_salt": "干砂",
原文就是 `Dried Salt`，为什么翻译成 `干砂`

2022-04-10 14:03 UTC, TartaricAcid commented on projects/1.16/assets/biomes-o-plenty/biomesoplenty/lang/zh_cn.json
> +  "block.biomesoplenty.flowering_oak_sapling": "开花橡树树苗",
我觉得旧有翻译更加合适

2022-04-10 14:05 UTC, ChuijkYahus commented on projects/1.16/assets/biomes-o-plenty/biomesoplenty/lang/zh_cn.json
> +  "item.biomesoplenty.hellbark_boat": "地狱皮船",
这里忘记修改了

2022-04-10 14:05 UTC, TartaricAcid commented on projects/1.16/assets/biomes-o-plenty/biomesoplenty/lang/zh_cn.json
> +  "block.biomesoplenty.orange_autumn_sapling": "橙色秋天树苗",
`x秋` 这个名字是我当初敲定的翻译名，我认为全写感觉不对劲

2022-04-10 14:06 UTC, TartaricAcid requested changes
部分翻译修改需要在敲定敲定

2022-04-10 14:07 UTC, ChuijkYahus commented
Prairie 是否要翻译成“大草原”而非“草原”

2022-04-10 14:15 UTC, TartaricAcid commented
> 译名征求：coniferous forest
> 针叶林已被原版taiga使用

没必要区分，直接翻译成`针叶林`没有任何问题，如果非要作区分可以加一点修饰词？`大针叶林`？，感觉好像也没大多少

2022-04-10 14:28 UTC, ChuijkYahus commented on projects/1.16/assets/biomes-o-plenty/biomesoplenty/lang/zh_cn.json
> +  "block.biomesoplenty.dried_salt": "干砂",
这里主要是 Dried Salt 作为一种地质方块，“干盐”听上去不大对劲
原本译为干砂的是 Dried Sand（好像）

2022-04-10 19:57 UTC, n0099 requested changes

2022-04-10 19:57 UTC, n0099 commented on projects/1.16/assets/biomes-o-plenty/biomesoplenty/lang/zh_cn.json
> +  "biome.biomesoplenty.bamboo_blossom_grove": "樱桃竹林",
这里面有樱桃树？

2022-04-10 19:57 UTC, n0099 commented on projects/1.16/assets/biomes-o-plenty/biomesoplenty/lang/zh_cn.json
> +  "block.biomesoplenty.potted_sprout": "芽盆栽",
```suggestion
  "block.biomesoplenty.potted_sprout": "发芽盆栽",
```
或者用之前的

2022-04-11 04:27 UTC, TartaricAcid commented on projects/1.16/assets/biomes-o-plenty/biomesoplenty/lang/zh_cn.json
> +  "block.biomesoplenty.dried_salt": "干砂",
那也应该翻译成 `岩盐` 这样的矿石吧？而且这应该指的是水分干燥后生成的结晶盐矿物吧？`干砂` 怎么都不对

2022-04-11 05:11 UTC, ChuijkYahus commented on projects/1.16/assets/biomes-o-plenty/biomesoplenty/lang/zh_cn.json
> +  "block.biomesoplenty.dried_salt": "干砂",
好的，想问一下“干岩盐”合不合适，或者就保持原译“干盐”
一开始改是因为找不到合适译法用来标记的（

2022-04-11 06:14 UTC, ChuijkYahus commented on projects/1.16/assets/biomes-o-plenty/biomesoplenty/lang/zh_cn.json
> +  "biome.biomesoplenty.bamboo_blossom_grove": "樱桃竹林",
是的
[https://s1.ax1x.com/2022/04/11/LVS041.png](https://s1.ax1x.com/2022/04/11/LVS041.png)

2022-04-11 16:16 UTC, n0099 approved these changes

2022-04-11 16:20 UTC, n0099 approved these changes

2022-04-13 07:21 UTC, Rinko1231 commented on projects/1.18/assets/biomes-o-plenty/biomesoplenty/lang/zh_cn.json
> +  "advancements.biomesoplenty.all_biomes.title": "探索者",
```suggestion
  "advancements.biomesoplenty.all_biomes.title": "羁旅者",
```
原文`Wanderer`
我倾向贴合原文，毕竟这不是`Explorer`
如果要浪漫文雅些，羁旅（在外长期漂泊）或许更好。

2022-04-13 07:23 UTC, n0099 commented on projects/1.18/assets/biomes-o-plenty/biomesoplenty/lang/zh_cn.json
> +  "advancements.biomesoplenty.all_biomes.title": "探索者",
支持

2022-04-13 09:00 UTC, n0099 approved these changes

2022-04-19 05:25 UTC, TartaricAcid approved these changes

2022-04-19 05:52 UTC, n0099 approved these changes

2022-04-19 05:53 UTC, merged