[R] Editsign 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1794
Opened 2022-04-04 14:04 UTC by XiaoXin1113

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2022-04-05 17:47 UTC, mamaruo commented
sign，告示牌，原版词

2022-04-06 01:55 UTC, XiaoXin1113 commented
> sign，告示牌，原版词

收到，已修正

2022-04-08 22:11 UTC, Cyl18 commented on projects/1.16/assets/edit-sign/editsign/lang/zh_cn.json
> +  "text.autoconfig.editsign.option.requiredItemId.@Tooltip[2]": "一个告示牌。如果没有设置任何值的话",
```suggestion
  "text.autoconfig.editsign.option.requiredItemId.@Tooltip[0]": "用户要编辑一个告示牌",
  "text.autoconfig.editsign.option.requiredItemId.@Tooltip[1]": "需要手持的物品的ID。",
  "text.autoconfig.editsign.option.requiredItemId.@Tooltip[2]": "如果没有设置任何值的话",
```
改一下语序读起来好点

2022-04-08 22:12 UTC, Cyl18 commented
同时也可以更新一下另外3个版本的语言文件

2022-04-09 13:41 UTC, mamaruo approved these changes

2022-04-09 13:46 UTC, mamaruo requested changes

2022-04-09 13:46 UTC, mamaruo commented on projects/1.16/assets/edit-sign/editsign/lang/zh_cn.json
> +  "text.autoconfig.editsign.category.default": "总设置",
```suggestion
  "text.autoconfig.editsign.category.default": "常规",
```

2022-04-10 11:11 UTC, merged