[R] Endertendril 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1795
Opened 2022-04-04 14:04 UTC by XiaoXin1113

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-04-04 14:41 UTC, mamaruo requested changes

2022-04-04 14:41 UTC, mamaruo commented on projects/1.16/assets/ender-tendril/endertendril/lang/zh_cn.json
> +  "item.endertendril.tendril_pearl": "藤蔓珍珠"
```suggestion
  "block.endertendril.ender_tendril": "末影卷须",
  "block.endertendril.ender_tendril_plant": "末影卷须植株",
  "block.endertendril.flowering_ender_tendril": "开花的末影卷须",
  "item.endertendril.ender_tendril_seed": "末影卷须种子",
  "item.endertendril.tendril_pearl": "卷须珍珠"
```
L3是根据key来的
现在的问题是，[tendril](https://en.wikipedia.org/wiki/Tendril) 是[攀缘植物](https://en.wikipedia.org/wiki/Vine)的器官（茎），模组里是一种植物

2022-04-09 14:25 UTC, mamaruo approved these changes

2022-04-09 14:28 UTC, Cyl18 approved these changes

2022-04-10 11:14 UTC, merged