[R] FTB Mods（Fabric）翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1812
Opened 2022-04-09 02:26 UTC by TexBlock

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-04-09 19:55 UTC, Cyl18 requested changes
等下把forge版也更新下吧

2022-04-09 19:55 UTC, Cyl18 commented on projects/1.16-fabric/assets/ftb-chunks-fabric/ftbchunks/lang/zh_cn.json
> +  "ftbteamsconfig.ftbchunks.allow_fake_players": "允许伪装玩家",
```suggestion
  "ftbteamsconfig.ftbchunks.allow_fake_players": "允许 Fake Players",
```

2022-04-09 19:55 UTC, Cyl18 commented on projects/1.18-fabric/assets/ftb-chunks-fabric/ftbchunks/lang/zh_cn.json
> +  "ftbteamsconfig.ftbchunks.allow_fake_players": "允许伪装玩家",
```suggestion
  "ftbteamsconfig.ftbchunks.allow_fake_players": "允许 Fake Players",
```

2022-04-09 19:55 UTC, Cyl18 commented on projects/1.16-fabric/assets/ftb-library-fabric/ftblibrary/lang/zh_cn.json
> +  "ftblibrary.mb": "%d mB%s",
```suggestion
  "ftblibrary.mb": "%d mB %s",
```

2022-04-09 19:55 UTC, Cyl18 commented on projects/1.18-fabric/assets/ftb-library-fabric/ftblibrary/lang/zh_cn.json
> +  "ftblibrary.mb": "%d mB%s",
```suggestion
  "ftblibrary.mb": "%d mB %s",
```

2022-04-09 19:55 UTC, Cyl18 commented on projects/1.18-fabric/assets/ftb-quests-fabric/ftbquests/lang/zh_cn.json
> +  "ftbquests.quest.shape.diamond": "钻石形",
```suggestion
  "ftbquests.quest.shape.diamond": "菱形",
```

2022-04-09 19:55 UTC, Cyl18 commented on projects/1.16-fabric/assets/ftb-quests-fabric/ftbquests/lang/zh_cn.json
> +  "ftbquests.quest.shape.diamond": "钻石形",
```suggestion
  "ftbquests.quest.shape.diamond": "菱形",
```

2022-04-09 23:18 UTC, TexBlock commented on projects/1.16-fabric/assets/ftb-chunks-fabric/ftbchunks/lang/zh_cn.json
> +  "ftbteamsconfig.ftbchunks.allow_fake_players": "允许伪装玩家",
`Fake Players` 不翻译吗？

2022-04-10 00:03 UTC, n0099 commented on projects/1.16-fabric/assets/ftb-chunks-fabric/ftbchunks/lang/zh_cn.json
> +  "ftbteamsconfig.ftbchunks.allow_fake_players": "允许伪装玩家",
术语无法翻译

2022-04-10 00:31 UTC, n0099 requested changes

2022-04-10 00:31 UTC, n0099 commented on projects/1.18-fabric/assets/ftb-teams-fabric/ftbteams/lang/zh_cn.json
> +  "ftbteams.api_override": "在这个整合包中，你只能从物品栏的“我的团队”按钮中创建团队!",
```suggestion
  "ftbteams.api_override": "在这个整合包中，你只能从物品栏的“我的团队”按钮中创建团队！",

```

2022-04-10 00:31 UTC, n0099 approved these changes

2022-04-10 08:28 UTC, TexBlock commented
> 等下把forge版也更新下吧

pr #1817

2022-04-10 16:57 UTC, Cyl18 approved these changes

2022-04-10 16:58 UTC, mamaruo commented
review 中……

2022-04-10 17:06 UTC, mamaruo commented
FTB Chuck 的某些设置项非常不明所以，得修
比如，你能猜到“区域”（Zone）是开关小地图下方指示当前区块所有权的功能吗
![image](https://user-images.githubusercontent.com/37480168/162631050-f410b9f5-b5d5-47c2-a9c7-623559cf7704.png)
![image](https://user-images.githubusercontent.com/37480168/162631052-d7d075c2-397d-4e76-899c-8711e9a19707.png)
![image](https://user-images.githubusercontent.com/37480168/162631055-1707cb68-e365-44fa-adf0-d34edf0cbc89.png)

2022-04-10 18:32 UTC, mamaruo requested changes

2022-04-10 18:32 UTC, mamaruo commented on projects/1.16-fabric/assets/ftb-chunks-fabric/ftbchunks/lang/zh_cn.json
> +  "ftbchunks.minimap.enabled": "启用",
```suggestion
  "ftbchunks.minimap.enabled": "是否启用",
```

2022-04-10 18:32 UTC, mamaruo commented on projects/1.16-fabric/assets/ftb-chunks-fabric/ftbchunks/lang/zh_cn.json
> +  "wilderness": "野外",
这是玩家走出某个已被认领的区块时的弹出提示（快捷栏上方），如果进入某个已被认领的区块则会提示区块所有者的名称。

2022-04-10 18:32 UTC, mamaruo commented on projects/1.16-fabric/assets/ftb-chunks-fabric/ftbchunks/lang/zh_cn.json
> +  "key.ftbchunks.minimap.zoomIn": "FTB区块放大",
```suggestion
  "key.ftbchunks.minimap.zoomIn": "FTB区块地图放大",
```

2022-04-10 18:32 UTC, mamaruo commented on projects/1.16-fabric/assets/ftb-chunks-fabric/ftbchunks/lang/zh_cn.json
> +  "key.ftbchunks.minimap.zoomOut": "FTB区块缩小",
```suggestion
  "key.ftbchunks.minimap.zoomOut": "FTB区块地图缩小",
```

2022-04-10 18:32 UTC, mamaruo commented on projects/1.16-fabric/assets/ftb-chunks-fabric/ftbchunks/lang/zh_cn.json
> +  "ftbteamsconfig.ftbchunks.allow_fake_players": "允许 Fake Players",
```suggestion
  "ftbteamsconfig.ftbchunks.allow_fake_players": "允许 Fake Player",
```
中文没有复数，所以夹杂在中文里的英文也应该没有复数？

2022-04-10 18:32 UTC, mamaruo commented on projects/1.16-fabric/assets/ftb-chunks-fabric/ftbchunks/lang/zh_cn.json
> +  "ftbchunks.biome_blend.blend_15x15": "15x15（最慢）",
缺少 Blend

2022-04-10 18:32 UTC, mamaruo commented on projects/1.16-fabric/assets/ftb-chunks-fabric/ftbchunks/lang/en_us.json
> +  "ftbchunks.waypoint_fade_distance": "Waypoint dade distance",
```suggestion
  "ftbchunks.waypoint_fade_distance": "Waypoint fade distance",
```
怎么把英文给改了
![image](https://user-images.githubusercontent.com/37480168/162634134-9fc0cb28-b459-4a2c-924a-52ea6efb1cff.png)

2022-04-10 18:32 UTC, mamaruo commented on projects/1.16-fabric/assets/ftb-chunks-fabric/ftbchunks/lang/zh_cn.json
> +  "ftbchunks.minimap.zone": "区域",
```suggestion
  "ftbchunks.minimap.zone": "区块所有权提示",

```

2022-04-10 18:41 UTC, mamaruo commented on projects/1.16-fabric/assets/ftb-chunks-fabric/ftbchunks/lang/zh_cn.json
> +  "ftbchunks.minimap.xyz": "XYZ",
```suggestion
  "ftbchunks.minimap.xyz": "XYZ坐标",
```
```suggestion
  "ftbchunks.minimap.xyz": "坐标",
```

2022-04-10 18:53 UTC, mamaruo commented on projects/1.16-fabric/assets/ftb-chunks-fabric/ftbchunks/lang/zh_cn.json
> +  "ftbchunks.water_height_factor": "水面权重系数",
![image](https://user-images.githubusercontent.com/37480168/162635063-b12c0b67-946b-4329-b697-85a106e5868f.png)
![image](https://user-images.githubusercontent.com/37480168/162635011-2fbb778a-8314-418d-99fa-733fef68043a.png)
![image](https://user-images.githubusercontent.com/37480168/162635019-c13dfb83-25e5-48c2-900d-34a459b8b32e.png)
![image](https://user-images.githubusercontent.com/37480168/162635028-515bed34-cc33-4a11-aaf3-f6b72715c014.png)

2022-04-10 19:03 UTC, mamaruo commented on projects/1.18-fabric/assets/ftb-quests-fabric/ftbquests/lang/zh_cn.json
> +  "block.ftbquests.screen.fullscreen": "全屏",
怎么会有方块叫全屏

2022-04-10 19:22 UTC, mamaruo commented on projects/1.18-fabric/assets/ftb-quests-fabric/ftbquests/lang/zh_cn.json
> +  "ftbquests.task.ftbquests.item.nbt_mode": "NBT 模式",
```suggestion
  "ftbquests.task.ftbquests.item.nbt_mode": "NBT模式",
```

2022-04-10 19:22 UTC, mamaruo commented on projects/1.18-fabric/assets/ftb-quests-fabric/ftbquests/lang/zh_cn.json
> +  "ftbquests.gui.pin": "标记",
置顶？钉住？

2022-04-10 19:36 UTC, mamaruo requested changes

2022-04-10 19:36 UTC, mamaruo commented on projects/1.18-fabric/assets/ftb-quests-fabric/ftbquests/lang/zh_cn.json
> +  "ftbquests.task.ftbquests.location.d": "Z大小（D）",
```suggestion
  "ftbquests.task.ftbquests.location.w": "X大小（长）",
  "ftbquests.task.ftbquests.location.h": "Y大小（高）",
  "ftbquests.task.ftbquests.location.d": "Z大小（宽）",
```
Width Height Depth

2022-04-10 20:07 UTC, n0099 commented on projects/1.16-fabric/assets/ftb-chunks-fabric/ftbchunks/lang/zh_cn.json
> +  "ftbchunks.minimap.large_entities": "大型实体",
```suggestion
  "ftbchunks.minimap.large_entities": "大号实体标识",

```

2022-04-10 20:08 UTC, n0099 commented on projects/1.16-fabric/assets/ftb-chunks-fabric/ftbchunks/lang/zh_cn.json
> +  "ftbteamsconfig.ftbchunks.allow_fake_players": "允许 Fake Players",
无必要

2022-04-10 20:09 UTC, n0099 commented on projects/1.18-fabric/assets/ftb-quests-fabric/ftbquests/lang/zh_cn.json
> +  "ftbquests.gui.pin": "标记",
我记得这是置顶任务窗口的

2022-04-10 20:20 UTC, mamaruo commented on projects/1.16-fabric/assets/ftb-chunks-fabric/ftbchunks/lang/zh_cn.json
> +  "ftbteamsconfig.ftbchunks.allow_fake_players": "允许 Fake Players",
遗憾的是《中文出版物夹用英文的编辑规范》[CY T154—2017](http://sxqx.alljournal.cn/uploadfile/sxqx/20190304/CY%20T154%E2%80%942017%20%E4%B8%AD%E6%96%87%E5%87%BA%E7%89%88%E7%89%A9%E5%A4%B9%E7%94%A8%E8%8B%B1%E6%96%87%E7%9A%84%E7%BC%96%E8%BE%91%E6%A0%87%E5%87%86.pdf)对此没有规定。

2022-04-11 04:23 UTC, TartaricAcid approved these changes

2022-04-11 16:16 UTC, n0099 approved these changes

2022-04-11 16:19 UTC, merged