[R] Malum 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #1818
Opened 2022-04-10 14:49 UTC by ChuijkYahus

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；
其中未翻译的部分是还没在当前版本实装的

2022-04-10 15:31 UTC, mamaruo requested changes

2022-04-10 15:31 UTC, mamaruo commented on projects/1.18/assets/malum/malum/lang/zh_cn.json
> +  "itemGroup.malum_spirits": "灵灾 | 灵神",
```suggestion
  "itemGroup.malum_natural_wonders": "灵灾丨自然奇观",
  "itemGroup.malum_shaped_stones": "灵灾丨形制石头",
  "itemGroup.malum_spirits": "灵灾丨灵神",
```
[TransRules](https://github.com/CFPAOrg/TransRules/blob/master/file/rules.md#07mod-%E5%90%8D%E7%BF%BB%E8%AF%91)

2022-04-10 15:48 UTC, mamaruo commented
跟官中[差别好大](https://cfpa.cyan.cafe/static/966AFA-B99392.html)

2022-04-10 16:03 UTC, ChuijkYahus commented
> 跟官中[差别好大](https://cfpa.cyan.cafe/static/966AFA-B99392.html)

这份官中是库里的吗

2022-04-10 16:55 UTC, ChuijkYahus commented
- Soul -> 灵魂
- Spirit -> 灵神，其在游戏内设定为灵魂的组成部分，故保留“灵”字
- Runewood -> 符文木
- Soulwood -> 灵魂木
- Tinted Stone -> 附圣石，其在游戏内由 Sacred 灵神制作，我初步翻译也是“污秽石”，但个人认为其与游戏内合成方式不符所以改了
- Ether -> 灵火，从灵神而来
- 由于游戏内 arcana 和 magic 互相混着用，一开始就统一为了秘术。不过由于原版“魔法伤害”这个还要再考虑
- 澄空，碧水，大地，狱火，神圣，邪恶，秘术，邪术八个名字没有特别的取名缘由，前四种是由于原文并不完全是西方四元素的对应形容词，就选了这四个词
- Magebane -> 巫灾，是在查了百度之后找到的“流浪武僧/巫师灾星”译名，为保持与护卫腰带的对应，缩为两个字。原译“折射”是从其反弹伤害的效用来的，并无原文依据

2022-04-10 20:11 UTC, n0099 commented
名字以结尾`tiles`的建筑方块能不能从`方砖`改成`砖块`

2022-04-10 20:12 UTC, n0099 approved these changes

2022-04-11 06:40 UTC, ChuijkYahus commented
> 名字以结尾`tiles`的建筑方块能不能从`方砖`改成`砖块`

可以的，原版 deepslate tiles 翻译为“深板岩瓦”，这里“方砖”是对其材质上的概括

2022-04-12 01:42 UTC, Rinko1231 commented on projects/1.18/assets/malum/malum/lang/zh_cn.json
> +  "item.malum.encyclopedia_arcana": "秘术百科",
```suggestion
  "item.malum.encyclopedia_arcana": "秘术全典",
```
我觉得这样魔法或者说中二一些

2022-04-12 01:42 UTC, Rinko1231 commented on projects/1.18/assets/malum/malum/lang/zh_cn.json
> +  "malum.gui.book.entry.page.text.totem_corruption_a": "秘术灵神通常被用于增强其他秘 术的能力，一般作为灵神仪式的 起点。但假如我们激活一个完全 由秘术灵神构成的仪式，累积起 的秘术能量会变成什么呢？答案 是“腐化”。",
```suggestion
  "malum.gui.book.entry.page.text.spirit_magics_c": "狩猎灵魂时要注意的是不要遗漏。 遗漏的灵神会慢慢消散注入并转变周围环境，这种不受控制的灵 神魔法是非常不稳定且危险的。",
  "malum.gui.book.entry.page.text.spirit_plunder": "灵神劫掠魔咒使得镰刀的灵魂石使用更多的秘术能量，任何这把镰刀击碎的灵魂都会分裂纹出额外灵神。这也会损耗灵魂石，对镰刀造成更多耐久值损耗。",
  "malum.gui.book.entry.page.text.spirit_pouch": "如果你曾想要过一个灵神背包之类的，灵神布袋就是你想要的。 这件物品使你能储存大量灵神， 所有身上的与收割的灵神都会自 动进入灵神布袋。",
  "malum.gui.book.entry.page.text.spirit_trinkets_a": "护符是能给予你有益效果的装饰品，也有人将它们称为“饰品” （Baubles）或是“奇异品” （Curios）。神圣金和魂染钢都 能被制成两种基础护符，以此作为灵神注入的主物品来得到高级 护符。",
  "malum.gui.book.entry.page.text.spirit_trinkets_b": "镀金护符给予护甲值加成，而华丽护符提供盔甲韧性提升。",
  "malum.gui.book.entry.page.text.tainted_rock": "将秘术灵神和神圣灵神注入圆石就得到了一种多用的建筑用石。 附圣石是一种有若干用途的简单 的秘术建筑方块，它也能被制成 物品台与物品基座。",
  "malum.gui.book.entry.page.text.totem_corruption_a": "秘术灵神通常被用于增强其他秘术的能力，一般作为灵神仪式的 起点。但假如我们激活一个完全由秘术灵神构成的仪式，累积起的秘术能量会变成什么呢？答案 是“腐化”。",

```

2022-04-12 01:42 UTC, Rinko1231 commented on projects/1.18/assets/malum/malum/lang/zh_cn.json
> +  "malum.gui.book.entry.page.text.totem_corruption_a": "秘术灵神通常被用于增强其他秘 术的能力，一般作为灵神仪式的 起点。但假如我们激活一个完全 由秘术灵神构成的仪式，累积起 的秘术能量会变成什么呢？答案 是“腐化”。",
空格忘删了

2022-04-12 01:42 UTC, Rinko1231 commented on projects/1.18/assets/malum/malum/lang/zh_cn.json
> +  "item.malum.cracked_vitric_impetus": "碎裂纹的钻石炼金促符",
直接`裂纹`会不会好些

2022-04-12 01:42 UTC, Rinko1231 commented on projects/1.18/assets/malum/malum/lang/zh_cn.json
> +  "malum.subtitle.tainted_rock_place": "秘术石：被放置",
```suggestion
  "malum.subtitle.arcane_charcoal_block_break": "秘术木炭块：破坏",
  "malum.subtitle.arcane_charcoal_block_hit": "秘术木炭块：损坏中",
  "malum.subtitle.arcane_charcoal_block_place": "秘术木炭块：放置",
  "malum.subtitle.arcane_charcoal_block_step": "脚步声",
  "malum.subtitle.blazing_quartz_block_break": "烈焰石英块：破坏",
  "malum.subtitle.blazing_quartz_block_hit": "烈焰石英块：损坏中",
  "malum.subtitle.blazing_quartz_block_place": "烈焰石英块：放置",
  "malum.subtitle.blazing_quartz_block_step": "脚步声",
  "malum.subtitle.blazing_quartz_ore_break": "烈焰石英矿石：破坏",
  "malum.subtitle.blazing_quartz_ore_place": "烈焰石英矿石：放置",
  "malum.subtitle.crucible_craft": "灵神坩埚：合成完成",
  "malum.subtitle.crucible_loop": "灵神坩埚：循环吸收",
  "malum.subtitle.deepslate_soulstone_break": "深层灵魂石矿石：破坏",
  "malum.subtitle.deepslate_soulstone_hit": "深层灵魂石矿石：损坏中",
  "malum.subtitle.deepslate_soulstone_place": "深层灵魂石矿石：放置",
  "malum.subtitle.deepslate_soulstone_step": "脚步声：深层灵魂石",
  "malum.subtitle.ether_break": "灵火：破坏",
  "malum.subtitle.ether_place": "灵火：放置",
  "malum.subtitle.hallowed_gold_break": "神圣金块：破坏",
  "malum.subtitle.hallowed_gold_hit": "神圣金块：损坏中",
  "malum.subtitle.hallowed_gold_place": "神圣金块：放置",
  "malum.subtitle.hallowed_gold_step": "脚步声：神圣金块",
  "malum.subtitle.heart_of_stone_grow": "Heart Of Stone Grow",
  "malum.subtitle.heart_of_stone_hit": "Heart Of Stone Hit",
  "malum.subtitle.holy_equip": "神圣护符：装备",
  "malum.subtitle.scythe_cut": "镰刀：挥砍",
  "malum.subtitle.sinister_equip": "魂染护符：装备",
  "malum.subtitle.soul_stained_steel_break": "魂染钢块：破坏",
  "malum.subtitle.soul_stained_steel_hit": "魂染钢块：损坏中",
  "malum.subtitle.soul_stained_steel_place": "魂染钢块：放置",
  "malum.subtitle.soul_stained_steel_step": "脚步声：魂染钢块",
  "malum.subtitle.soul_ward_charge": "灵魂护盾：恢复",
  "malum.subtitle.soul_ward_grow": "灵魂护盾：增加",
  "malum.subtitle.soul_ward_hit": "灵魂护盾：损失",
  "malum.subtitle.soulstone_break": "灵魂石块：破坏",
  "malum.subtitle.soulstone_hit": "灵魂石块：损坏中",
  "malum.subtitle.soulstone_place": "灵魂石块：放置",
  "malum.subtitle.soulstone_step": "脚步声：灵魂石",
  "malum.subtitle.spirit_harvest": "灵魂收割",
  "malum.subtitle.suspicious_sound": "可疑的声音",
  "malum.subtitle.tainted_rock_break": "秘术石：破坏",
  "malum.subtitle.tainted_rock_hit": "秘术石：损坏中",
  "malum.subtitle.tainted_rock_place": "秘术石：放置",
```
应该是不用`被`的。

2022-04-12 01:52 UTC, n0099 commented on projects/1.18/assets/malum/malum/lang/zh_cn.json
> +  "item.malum.cracked_vitric_impetus": "碎裂纹的钻石炼金促符",
那`的`也要去掉

2022-04-12 03:13 UTC, ChuijkYahus commented on projects/1.18/assets/malum/malum/lang/zh_cn.json
> +  "item.malum.cracked_vitric_impetus": "碎裂纹的钻石炼金促符",
咦这里没改回去
原文是`碎裂的`

2022-04-12 03:15 UTC, ChuijkYahus commented on projects/1.18/assets/malum/malum/lang/zh_cn.json
> +  "malum.gui.book.entry.page.text.totem_corruption_a": "秘术灵神通常被用于增强其他秘 术的能力，一般作为灵神仪式的 起点。但假如我们激活一个完全 由秘术灵神构成的仪式，累积起 的秘术能量会变成什么呢？答案 是“腐化”。",
这本书不带空格换不了行
每14个字敲个空格，标点符号看着改

2022-04-12 04:06 UTC, n0099 approved these changes

2022-04-16 12:51 UTC, mamaruo commented
第一行及其相关的行没翻译是为什么

2022-04-16 12:52 UTC, ChuijkYahus commented
> 第一行及其相关的行没翻译是为什么

未实装
（没在游戏内测试出来）

2022-04-19 05:35 UTC, TartaricAcid commented on projects/1.18/assets/malum/malum/lang/zh_cn.json
> +  "attribute.name.malum.heart_of_stone_strength": "Heart Of Stone Strength",
这几个怎么没有翻译？还是说保留词？

2022-04-19 05:36 UTC, TartaricAcid commented on projects/1.18/assets/malum/malum/lang/zh_cn.json
> +  "malum.subtitle.heart_of_stone_hit": "Heart Of Stone Hit",
缺失翻译？

2022-04-19 05:36 UTC, TartaricAcid approved these changes

2022-04-19 05:50 UTC, n0099 approved these changes

2022-04-19 05:53 UTC, merged