提交suppergerrie2s-drone模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #1825
Opened 2022-04-11 09:10 UTC by HGinGitHub

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2022-04-11 16:11 UTC, n0099 requested changes

2022-04-11 16:11 UTC, n0099 commented on projects/1.12.2/assets/sdrones/lang/zh_cn.lang
> +sdrones.subtitle.drone_driving=无人机正在开车
```suggestion
sdrones.subtitle.drone_bleep=无人机：哔哔
sdrones.subtitle.drone_driving=无人机：正在行驶
```

2022-04-11 16:11 UTC, n0099 commented on projects/1.12.2/assets/sdrones/lang/zh_cn.lang
> +dronestick.message.sethome=右键单击“方块”设置为原点。
```suggestion
dronestick.message.select=右击以选择无人机。
dronestick.message.deselect=Shift+右击空中以取消选择无人机。
dronestick.message.kill=Shift+右击无人机以回收它。
dronestick.message.sethome=右击“方块”设置为原点。
```
为什么home要叫原点？

2022-04-11 16:11 UTC, n0099 commented on projects/1.12.2/assets/sdrones/lang/zh_cn.lang
> +item.item_hauler_drone.name=搬运工无人机
```suggestion
item.item_hauler_drone.name=搬运无人机
```

2022-04-11 16:11 UTC, n0099 commented on projects/1.12.2/assets/sdrones/lang/zh_cn.lang
> +item.item_crop_farm_drone.name=农作物无人机
```suggestion
item.item_crop_farm_drone.name=农场无人机
```

2022-04-11 16:11 UTC, n0099 commented on projects/1.12.2/assets/sdrones/lang/zh_cn.lang
> +item.item_archer_drone.name=弓箭手无人机
```suggestion
item.item_archer_drone.name=弓箭无人机
```

2022-04-11 16:11 UTC, n0099 commented on projects/1.12.2/assets/sdrones/lang/zh_cn.lang
> +entity.archer_drone.name=弓箭手无人机
```suggestion
entity.hauler_drone.name=搬运无人机
entity.fighter_drone.name=战斗无人机
entity.tree_farm_dron=树场无人机
entity.crop_farm_drone.name=农场无人机
entity.archer_drone.name=弓箭无人机
```

2022-04-11 16:11 UTC, n0099 commented on projects/1.12.2/assets/sdrones/lang/zh_cn.lang
> +entity.drone_arrow.name=Arrow
游戏里是什么

2022-04-11 20:10 UTC, Cyl18 commented
提交路径有误 没有 CurseForge 项目名

2022-04-19 05:39 UTC, TartaricAcid approved these changes

2022-04-19 05:50 UTC, n0099 approved these changes

2022-04-19 05:52 UTC, merged