[R][WIP]提交Dimensional Pockets II模组的翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #1826
Opened 2022-04-11 12:55 UTC by LiuQiYu671

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2022-04-11 16:06 UTC, n0099 requested changes

2022-04-11 16:06 UTC, n0099 commented on projects/1.12.2/assets/dimensional-pockets-ii/dimensionalpocketsii/lang/zh_cn.lang
> +tile.block_dimensional_pocket_wall_fluid_display.name=Dimensional Fluid Display
没有翻译？

2022-04-11 16:06 UTC, n0099 commented on projects/1.12.2/assets/dimensional-pockets-ii/dimensionalpocketsii/lang/zh_cn.lang
> +command.dimshift.usage=/dimshift <目标维度>（输入一个数字，例如：0 [主世界]）
```suggestion
command.dimshift.usage=/dimshift <目标维度>（输入维度ID，例如0代表主世界）

```

2022-04-11 16:06 UTC, n0099 commented on projects/1.12.2/assets/dimensional-pockets-ii/dimensionalpocketsii/lang/zh_cn.lang
> +command.recoverpocket.creative=当使用此指令时你必须处于创造模式。
```suggestion
command.recoverpocket.usage=/recoverpocket <要进入的口袋编号>/ “长度”（显示注册表中有多少口袋）
command.recoverpocket.too.usage=指定的口袋编号大于注册表中的口袋数量。
command.recoverpocket.wrong_name=你不能进入这个口袋，因为它不属于你。
command.recoverpocket.creative=当使用此指令时你必须处于创造模式。
```

2022-04-20 06:02 UTC, LiuQiYu671 commented
> 模组	🆔 Mod Domain	🎨 相关文件	🟩 mcmod	🔍 源代码	📁 对比
> <img alt="" width="32" src="https://camo.githubusercontent.com/3c6b2fc9dae637b035044f223940d5020abe597e5beb9047f52fd04a1993f3c1/68747470733a2f2f636670612e6379616e2e636166652f7374617469632f3633373533353331333334313732313038382e706e67">	[**Dimensional Pockets II**](https://www.curseforge.com/minecraft/mc-mods/dimensional-pockets-ii)	_dimensionalpocketsii_	
> 最新模组文件
> 语言文件链接
> [百度](https://www.baidu.com/s?wd=site:mcmod.cn%20Dimensional+Pockets+II)	[链接](https://github.com/TheRealZeher/DimensionalPockets-II)	[链接](https://cfpa.cyan.cafe/Compare/PR/1826/dimensional-pockets-ii/dimensionalpocketsii)
> <img alt="" width="32" src="https://camo.githubusercontent.com/6f9792c654f3963a2dbffd8e75e76737767f23bafcc99dbb513210ef273d956e/68747470733a2f2f636670612e6379616e2e636166652f7374617469632f3633373733373933343530333836303833312e706e67">	依赖-[_Cosmos Library_](https://www.curseforge.com/minecraft/mc-mods/cosmos-library)	*	
> 最新模组文件
> [百度](https://www.baidu.com/s?wd=site:mcmod.cn%20Cosmos+Library)	[链接](https://github.com/TheRealZeher/TRZCore)	*
> 💾 你可以在 [这里](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1826/checks) 点击 PR Packer>Artifacts 下载基于此 PR 所打包的最新资源包。
> 
> ✔ `dimensionalpocketsii` Mod Domain 验证通过。 ⚠ 警告：PR 中 dimensionalpocketsii-1.12.2 的中英文语言文件不对应。
> 
> * 中文语言文件有 1 个 Key 多于英文语言文件。例如：
>   
>   * 行 9-`item.dimensional_core.name`
> 
> ℹ dimensionalpocketsii-1.12.2 模组内语言文件验证通过。
> 
> 详细检查报告
> 报告也可以在 [这里](https://cfpa.cyan.cafe/static/1826-ea00ffe.txt) 查看。在 PR 更新时这里的检查也会自动更新。
> 
> * [ ]  🔄 勾选这个复选框来强制刷新

请注意，还需要一个RedstoneFlux作为前置（原因是使用了RF作为能量单位）（悲

2022-04-20 07:11 UTC, TartaricAcid approved these changes

2022-04-20 15:33 UTC, merged