[R] ProjectEX 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #1830
Opened 2022-04-12 04:59 UTC by DSLM

旧版文本：https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/projects/1.12.2/assets/project-ex/projectex/lang/en_us.lang
有几行GUI提示未在游戏中出现，故未翻译

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-04-12 05:09 UTC, n0099 requested changes

2022-04-12 05:09 UTC, n0099 commented on projects/1.16/assets/projectex-forge/projectex/lang/zh_cn.json
> +	"block.projectex.blue_relay": "蓝物质反物质继电器「MK8」",
别用中文符号「」，输入法都打不出来，建议直接写`MK1`

2022-04-12 05:14 UTC, DSLM commented on projects/1.16/assets/projectex-forge/projectex/lang/zh_cn.json
> +	"block.projectex.blue_relay": "蓝物质反物质继电器「MK8」",
删了

2022-04-12 05:14 UTC, n0099 commented
@cyl18a 根据之前tusama的意思https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1829#issuecomment-1096048063 认为MK1应该跟projecte同步改成1型

2022-04-12 06:19 UTC, n0099 approved these changes

2022-04-12 10:19 UTC, n0099 commented
> 为什么这里颜色不带色，pink不叫粉红叫粉？

因为这不是直接对应色彩，dark matter您能叫暗黑色物质吗

2022-04-12 10:50 UTC, Cyl18 commented
> 为什么这里颜色不带色，pink不叫粉红叫粉？

貌似 projecte 有个经典物品叫 `红物质`

2022-04-13 02:24 UTC, n0099 commented
支持反绿物质

2022-04-13 21:52 UTC, DSLM commented
已改成反X物质

2022-04-14 00:47 UTC, n0099 approved these changes

2022-04-15 05:37 UTC, Rinko1231 commented on projects/1.16/assets/projectex-forge/projectex/lang/zh_cn.json
> +	"block.projectex.refined_link.tooltip": "与个人EMC接口相似，但它拥有1个输入槽和9个输出槽。用来做一个像精致存储一样的系统。它也从学习放入输入槽的物品。",
```suggestion
	"block.projectex.refined_link.tooltip": "与个人EMC接口相似，但它拥有1个输入槽和9个输出槽。用来做一个像精致存储一样的系统。它也学习从输入槽放入的物品。",
```

2022-04-15 19:53 UTC, n0099 requested changes

2022-04-15 19:53 UTC, n0099 commented on projects/1.16/assets/projectex-forge/projectex/lang/zh_cn.json
> +	"block.projectex.collector.tooltip": "对服务器的TPS很友善。每秒生产EMC一次。",
```suggestion
	"block.projectex.collector.tooltip": "对服务器的TPS很友善。每秒只生产一次EMC。",
```

2022-04-15 19:53 UTC, n0099 commented on projects/1.16/assets/projectex-forge/projectex/lang/zh_cn.json
> +	"block.projectex.collector.emc_produced": "已产生EMC：%s/s",
```suggestion
	"block.projectex.collector.emc_produced": "EMC生产速度：%s/s",
```
建议进游戏看是不是每秒速度

2022-04-15 19:53 UTC, n0099 commented on projects/1.16/assets/projectex-forge/projectex/lang/zh_cn.json
> +	"block.projectex.relay.tooltip": "对服务器TPS很友善。每秒只传输EMC一次。",
```suggestion
	"block.projectex.relay.tooltip": "对服务器TPS很友善。每秒只传输一次EMC。",
```

2022-04-16 00:58 UTC, Cyl18 commented on projects/1.16/assets/projectex-forge/projectex/lang/zh_cn.json
> +	"block.projectex.collector.tooltip": "对服务器的TPS很友善。每秒只生产一次EMC。",
```suggestion
	"block.projectex.collector.tooltip": "对服务器的TPS很友善。每秒只产生一次EMC。",
```

2022-04-16 08:05 UTC, n0099 approved these changes

2022-04-16 12:24 UTC, mamaruo requested changes
原译的长文本问题很大，需要修改
短文本没啥问题了。

2022-04-16 12:24 UTC, mamaruo commented on projects/1.16/assets/projectex-forge/projectex/lang/zh_cn.json
> +	"item.projectex.violet_matter": "紫罗兰物质",
```suggestion
	"item.projectex.violet_matter": "蓝紫物质",
```

2022-04-16 12:24 UTC, mamaruo commented on projects/1.16/assets/projectex-forge/projectex/lang/zh_cn.json
> +	"item.projectex.final_star.tooltip": "在台座旁边放置一个箱子，并在台座上方掉落物品以无限复制其物品。",
```suggestion
	"item.projectex.final_star.tooltip": "在台座旁边放个箱子，然后在台座上方丢物品来无限复制物品。",
```

2022-04-16 12:24 UTC, mamaruo commented on projects/1.16/assets/projectex-forge/projectex/lang/zh_cn.json
> +	"block.projectex.refined_link.tooltip": "与个人EMC接口相似，但它拥有1个输入槽和9个输出槽。用来做一个像精致存储一样的系统。它也学习从输入槽放入的物品。",
这个学习是什么意思，查MC百科没查到相关信息

2022-04-16 12:24 UTC, mamaruo commented on projects/1.16/assets/projectex-forge/projectex/lang/zh_cn.json
> +	"block.projectex.personal_link.tooltip": "与能量EMC接口相似，但也能允许你放入与取出物品。",
```suggestion
	"block.projectex.personal_link.tooltip": "与基础能量EMC接口相似，还能存入和取出物品。",
```
```suggestion
	"block.projectex.personal_link.tooltip": "比基础能量EMC接口多了存入和取出物品的功能",
```
应为 not only... but also...，的省略。“但也”？

[物品/方块] 基础能量EMC接口 (Basic Energy EMC Link) - Project EX 
https://www.mcmod.cn/item/216852.html

2022-04-16 12:24 UTC, mamaruo commented on projects/1.16/assets/projectex-forge/projectex/lang/zh_cn.json
> +	"block.projectex.basic_power_flower": "基础力量花盆栽罐1型",
盆栽罐是怎么翻出来的

2022-04-16 22:13 UTC, DSLM commented on projects/1.16/assets/projectex-forge/projectex/lang/zh_cn.json
> +	"item.projectex.violet_matter": "紫罗兰物质",
紫罗兰全改蓝紫？

2022-04-16 22:16 UTC, DSLM commented on projects/1.16/assets/projectex-forge/projectex/lang/zh_cn.json
> +	"block.projectex.basic_power_flower": "基础力量花盆栽罐1型",
前人留下来的翻译，应该是基于游戏内造型加的，我没感觉有问题就继续用了，要删吗

2022-04-16 22:18 UTC, DSLM commented on projects/1.16/assets/projectex-forge/projectex/lang/zh_cn.json
> +	"block.projectex.refined_link.tooltip": "与个人EMC接口相似，但它拥有1个输入槽和9个输出槽。用来做一个像精致存储一样的系统。它也学习从输入槽放入的物品。",
这个是指的等价交换的转化桌记录新东西的功能，也就是说这个输入新东西会记录到转化桌里面

2022-04-16 22:18 UTC, DSLM commented on projects/1.16/assets/projectex-forge/projectex/lang/zh_cn.json
> +	"block.projectex.refined_link.tooltip": "与个人EMC接口相似，但它拥有1个输入槽和9个输出槽。用来做一个像精致存储一样的系统。它也学习从输入槽放入的物品。",
不过1.16这些东西都是WIP状态

2022-04-17 04:49 UTC, mamaruo commented on projects/1.16/assets/projectex-forge/projectex/lang/zh_cn.json
> +	"item.projectex.violet_matter": "紫罗兰物质",
没必要改，新翻译我建议用蓝紫

2022-04-17 05:45 UTC, DSLM commented on projects/1.16/assets/projectex-forge/projectex/lang/zh_cn.json
> +	"item.projectex.violet_matter": "紫罗兰物质",
那这个mod就不动了吧

2022-04-17 06:34 UTC, mamaruo commented
长文本还是有点问题，你看着改一下

2022-04-17 06:35 UTC, mamaruo commented on projects/1.16/assets/projectex-forge/projectex/lang/zh_cn.json
> +	"block.projectex.refined_link.tooltip": "与个人EMC接口相似，但它拥有1个输入槽和9个输出槽。用来做一个像精致存储一样的系统。它也学习从输入槽放入的物品。",
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1830#discussion_r851622354
跟上一个更改统一一下

2022-04-22 09:35 UTC, n0099 approved these changes

2022-04-22 14:33 UTC, mamaruo commented on projects/1.16/assets/projectex-forge/projectex/lang/zh_cn.json
> +	"block.projectex.personal_link.tooltip": "与基础能量EMC接口相似，还能存入和取出物品",
```suggestion
	"block.projectex.personal_link.tooltip": "与基础能量EMC接口相似， 并能存入和取出物品。",
```

2022-04-22 14:33 UTC, mamaruo approved these changes

2022-04-22 14:34 UTC, mamaruo commented on projects/1.16/assets/projectex-forge/projectex/lang/zh_cn.json
> +	"block.projectex.personal_link.tooltip": "与基础能量EMC接口相似，还能存入和取出物品",
```suggestion
	"block.projectex.personal_link.tooltip": "与基础能量EMC接口相似，并能存入和取出物品。",
```

2022-04-22 14:34 UTC, mamaruo approved these changes

2022-04-23 09:37 UTC, merged