[R] BYG 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1831
Opened 2022-04-12 05:26 UTC by ChuijkYahus

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

现在正处于向作者咨询某些词源的阶段，WIP
https://github.com/AOCAWOL/BYG/pull/704

2022-04-12 06:20 UTC, n0099 requested changes

2022-04-12 06:20 UTC, n0099 commented on projects/1.16/assets/oh-the-biomes-youll-go/byg/lang/zh_cn.json
> +  "biome.byg.imparius_clearing": "Imparius Clearing",
没翻译

2022-04-12 06:23 UTC, ChuijkYahus commented on projects/1.16/assets/oh-the-biomes-youll-go/byg/lang/zh_cn.json
> +  "biome.byg.imparius_clearing": "Imparius Clearing",
啊这这确实还没完成啊
不会设draft（

2022-04-21 16:47 UTC, ChuijkYahus commented
作者好久没回，自作主张了一些译名（
Embur Pedu -> 余烬菌柄，保持原译
Phylium & Phycelium -> 藻石，菌藻石（从希腊文fyki/fykos而来，原译可能也有这块的考虑）
Imparius -> 异蓝（从拉丁文impar而来，蓝色取其外表）
1.18分另外的PR

2022-04-21 19:41 UTC, n0099 commented
支持

2022-04-22 13:04 UTC, n0099 approved these changes

2022-04-23 08:10 UTC, ChuijkYahus commented
https://github.com/CorgiTaco/BYG-Translations/pull/2

2022-04-24 06:02 UTC, TartaricAcid commented
游戏内检查了一遍翻译，没发现什么问题，翻译的很不错。

`Therium` 是 `Ther` + `ium` 的组合词么？我查到的 `Ther` 词缀有 `野兽` 的意思：<https://www.etymonline.com/word/ther-#etymonline_v_24710>

2022-04-24 06:02 UTC, TartaricAcid approved these changes

2022-04-24 07:07 UTC, ChuijkYahus commented
@TartaricAcid `Therium`是`Ether`去了`E`再加`ium`
所以有`空灵晶`的想法
库中其他模组的`Therium`都没译所以暂且保留
不过BYG的Therium明确有水晶的造型

2022-04-24 07:11 UTC, TartaricAcid commented
既然知道来源了，直接敲定一个翻译吧，其他的都可以一并改了

2022-04-24 07:13 UTC, ChuijkYahus commented
在BYG里我是提议`空灵晶`，这东西还能造玻璃
不过其他模组的`Therium`造型有所不同，例如`BetterEnd`里是个锭，那些不知道应该如何处理了

2022-04-24 07:14 UTC, TartaricAcid commented
啊，这……这些作者怎么都不约而同的想到了同一个合成词？

2022-04-24 07:16 UTC, ChuijkYahus commented
也许有借鉴关系吧（
不过怎么说原本那个`钍`是不能用的

2022-04-24 11:24 UTC, n0099 requested changes

2022-04-24 11:24 UTC, n0099 commented on projects/1.16/assets/oh-the-biomes-youll-go/byg/lang/zh_cn.json
> +  "block.byg.therium_glass_pane": "Therium玻璃板",
```suggestion
  "block.byg.therium_crystal": "空灵晶晶体",
  "block.byg.therium_block": "空灵晶块",
  "block.byg.therium_lantern": "空灵晶灯笼",
  "block.byg.therium_lamp": "空灵晶灯",
  "block.byg.chiseled_therium": "錾制空灵晶块",
  "block.byg.chiseled_therium_stairs": "錾制空灵晶楼梯",
  "block.byg.chiseled_therium_slab": "錾制空灵晶台阶",
  "block.byg.chiseled_therium_wall": "錾制空灵晶墙",
  "block.byg.shiny_chiseled_therium": "闪亮的錾制空灵晶块",
  "block.byg.shiny_chiseled_therium_stairs": "闪亮的錾制空灵晶楼梯",
  "block.byg.shiny_chiseled_therium_slab": "闪亮的錾制空灵晶台阶",
  "block.byg.shiny_chiseled_therium_wall": "闪亮的錾制空灵晶墙",
  "block.byg.therium_glass": "空灵晶玻璃",
  "block.byg.therium_glass_pane": "空灵晶玻璃板",
```

2022-04-24 11:24 UTC, n0099 commented on projects/1.16/assets/oh-the-biomes-youll-go/byg/lang/zh_cn.json
> +  "item.byg.therium_lamp": "Therium灯",
```suggestion
  "item.byg.therium_shard": "空灵晶碎片",
  "item.byg.therium_crystal": "空灵晶晶体",
  "item.byg.therium_block": "空灵晶块",
  "item.byg.chiseled_therium": "錾制空灵晶块",
  "item.byg.chiseled_therium_stairs": "錾制空灵晶楼梯",
  "item.byg.chiseled_therium_slab": "錾制空灵晶台阶",
  "item.byg.chiseled_therium_wall": "錾制空灵晶墙",
  "item.byg.shiny_chiseled_therium": "闪亮的錾制空灵晶块",
  "item.byg.shiny_chiseled_therium_stairs": "闪亮的錾制空灵晶楼梯",
  "item.byg.shiny_chiseled_therium_slab": "闪亮的錾制空灵晶台阶",
  "item.byg.shiny_chiseled_therium_wall": "闪亮的錾制空灵晶墙",
  "item.byg.therium_glass": "空灵晶玻璃",
  "item.byg.therium_glass_pane": "空灵晶玻璃板",
  "item.byg.therium_lantern": "空灵晶灯笼",
  "item.byg.therium_lamp": "空灵晶灯",
```

2022-04-24 11:26 UTC, ChuijkYahus commented
如果要改的话可以1.18也改下吗（

2022-04-24 11:34 UTC, merged

2022-04-24 11:40 UTC, n0099 commented
> 如果要改的话可以1.18也改下吗（

d0e915dadead61ba52e5e9ca915bf5bf253e9aa6