[R] Gregicailty 补充翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1833
Opened 2022-04-12 10:27 UTC by mczph

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-10 21:25 UTC, n0099 commented on projects/1.12.2/assets/gregicality/gtadditions/lang/zh_cn.lang
> +metaitem.crude_hexanitrohexaaxaisowurtzitane.name=粗制六硝基六氧杂纤锌烷
这就是GT化学

2022-05-11 12:06 UTC, mczph commented
我看了一下，gi把gtce原本的框架（如隔热机械框架），gtce英文原文Heat Proof Casing，gi则改成了Heat Proof Invar Casing（可能是为了跟他们加的其他框架外壳统一），因此我统一格式[(描述)(材料)机械外壳]的样式是否可行

2022-05-11 21:53 UTC, n0099 commented
> gtce英文原文Heat Proof Casing，gi则改成了Heat Proof Invar Casing

invar哪来的

2022-05-12 03:35 UTC, mczph commented
因为这个外壳是由殷钢(invar)制成的

2022-05-12 21:58 UTC, n0099 commented
那为啥gtce英文原文是Heat Proof Casing

2022-05-13 02:09 UTC, mczph commented
不太清楚，可能是因为种类也不太多，没必要体现出来是啥做的

2022-05-13 10:10 UTC, n0099 requested changes

2022-05-13 10:10 UTC, n0099 commented on projects/1.12.2/assets/gregicality/gtadditions/lang/zh_cn.lang
> +fluid.polyamic_acid=聚酰胺酸(PAA)
```suggestion
fluid.polyamic_acid=聚酰胺酸（PAA）
```

2022-06-12 08:51 UTC, mczph commented
怎样把缺失的条目英文原文统一找出来，那个插件我一直用不了，另外还有排序

2022-06-12 13:56 UTC, n0099 commented
cc @Cyl18

2022-06-30 16:44 UTC, mamaruo commented
/diff
我不熟 GT，可能得您@n0099 来看

2022-07-02 13:38 UTC, n0099 commented
> /diff 我不熟 GT，可能得您@n0099 来看

我GTNH才杠到EV

2022-07-08 13:31 UTC, dovisutu commented
很久没玩GT了（况且在GT层面我还是1710遗民），所以只能大概的看一下

------

key | ENG | CHI
--- | --- | ---
fluid.lithiumcyclopentadienide | Lithium Cyclopentadienide | 环戊二烯锂
fluid.californiumcyclopentadienide | Californium Cyclopentadienide | 环戊二烯化锎
metaitem.titanium_cyclopentadienyl.name | Cyclopentadienyl Titanium Trichloride | 钛环戊二烯基

都是环戊二烯负离子夹金属离子为什么差异这么大 ~（希望后面不会再出来个`二茂xxx`）~
*此外，第三项是不是把`trichloride`翻掉了*

key | ENG | CHI
--- | --- | ---
fluid.trioctylphosphine | Tricotylphosphine | 三轴膦

猜测是 *tri*__*octyl*__*phosphine* *三*__*辛基*__*膦*？(按照粗略搜索的结果）

key | ENG | CHI
--- | --- | ---
metaitem.chromium_iii_oxide.name | Chromium (III) Oxide | 三氧化铬

明明是Cr(III)为什么是(VI)CrO3啊？是模组里如此吗？

key | ENG | CHI
--- | --- | ---
metaitem.ferromagnetic_residues.name | Ferromagnetic Residues | 强磁性残渣
metaitem.heavy_ferromagnetic_residues.name | Heavy Ferromagnetic Residues | 重强磁性残渣

铁磁性 != 强磁性

key | ENG | CHI
--- | --- | ---
fluid.nitryl_fluoride | Nitryl Fluoride | 氟化硝酰

硝酰氟？

key | ENG | CHI
--- | --- | ---
item.polyimide.dustTiny | Tiny Pile of 4,4'-Oxydianiline-Pyromellitimide Pulp | 小搓聚酰亚胺末

小撮？（如果按照曾经旧版本的翻译；不清楚这个改了没有）

2022-08-24 08:44 UTC, dovisutu commented
`右键`是名词，`右击`才可以用作谓语。这里好像有好几处出现了这样的问题。
此外，我愈发觉得我是在审化学名词而不是审GT翻译（

-------

key | ENG | CHI
-- | -- | --
metaitem.large.fluoride.battery.empty.name | Large Fluoride Battery Hull | 大型氟化物电池外壳🔽大型氟化物电池

看原文`外壳`不应该被删吧。是翻译标准改了吗？

-------
key | ENG | CHI
-- | -- | --
fluid.periodicium_molten | Molten Periodicium | 熔融錭錤錶

这个名字......如果需要的话可以在这边做专门字体+替换把繁体的金字旁解决掉（虽然流程有一点麻烦）

-------
key | ENG | CHI
-- | -- | --
metaitem.palladium_bisdibenzylidieneacetone.name | Palladium Bisdibenzylidieneacetone | 双（二亚苄基二丙酮）钯🔽钯双二苄基二烯丙酮

似乎旧译名才是符合配合物命名标准的？（有点记不清了，这个需要考证）

-------
key | ENG | CHI
-- | -- | --
metaitem.lithiumthiinediselenide.name | Lithiumthiinediselenide | 噻吩二烯酸锂

居然查不到这是什么.....
*Lithium* _**thi**ine_ _di**sele**nide_
- 第一部分没什么好说的
- 第三部分：`sele` -> selenium 硒
在网上可以查到`lithium indium diselenide`二硒醚合锂铟（推测是这个译名？），一种中子检测剂，以及`diphenyl diselenide`二苯基二硒醚等，估计这一部分应该是**二硒醚**（的一种？）
- 第二部分：`thi(o)` -> 硫代物？但是是什么没搞清楚（搜索直接认为是古英语的thine）

-------
key | ENG | CHI
metaitem.diaminostilbenedisulfonic_acid.name | Diaminostilbenedisulfonic Acid | 二氨基二苯二磺酸

_(di**amino** stil**bene**) di**sulfonic acid**_
查到的译名：
4,4'-二氨基二苯乙烯-2,2'-二磺酸（系统命名（但好像没完全系统），估计与GT目前翻译习惯不符）
二氨基芪二磺酸（但这个`芪`是什么......不会是远古的芳环化合物命名吧）
目前的翻译掉了两个苯环之间的乙烯基（双键）

2022-08-24 08:45 UTC, dovisutu commented
~解完这个干脆直接合了算了 这个审核太折磨人了~

2022-08-24 11:37 UTC, mczph commented
周期表那个还是不处理算了

2022-08-27 03:54 UTC, dovisutu commented on projects/1.12.2/assets/gregicality/gtadditions/lang/zh_cn.lang
> +metaitem.diaminostilbenedisulfonic_acid.name=4,4'-二氨基二苯乙烯-2,2'-二磺酸
把基团编号去了吧
比如`二氨基二苯乙烯二磺酸`这种就可以了，GT又不需要看到名字可以写出结构简式（

2022-08-27 03:54 UTC, dovisutu commented on projects/1.12.2/assets/gregicality/gtadditions/lang/zh_cn.lang
> +metaitem.lithiumthiinediselenide.name=二硒醚合锂铟
我举例举的又不是这个物质......这里面没有铟啊
我是说`diselenide`估计是二硒醚，`thiine`不知道是硫相关的什么东西，`lithium`是锂
在查不到的情况下估计可以`二硒醚合硫锂`凑合一下（虽说好像也没什么人看这玩意）

2022-09-21 10:17 UTC, merged