[R] 提交Odd Water Mobs 模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #1834
Opened 2022-04-12 12:12 UTC by MuMu-5528

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-04-13 01:55 UTC, Rinko1231 commented on projects/1.16/assets/odd-water-mobs/oddwatermobs/lang/zh_cn.json
> +  "block.oddwatermobs.smooth_deep_sandstone_stairs": "光滑的深层砂岩楼梯",
```suggestion
  "block.oddwatermobs.smooth_deep_sandstone": "平滑深层砂岩",
  "block.oddwatermobs.smooth_deep_sandstone_slab": "平滑深层砂岩台阶",
  "block.oddwatermobs.smooth_deep_sandstone_stairs": "平滑深层砂岩楼梯",
```
与原版`平滑砂岩`一致。

2022-04-13 01:55 UTC, Rinko1231 commented on projects/1.16/assets/odd-water-mobs/oddwatermobs/lang/zh_cn.json
> +  "death.attack.seapigpoison": "%1$s 觉得海猪很好吃.",
```suggestion
  "death.attack.horseshoe": "%1$s一直在惹马蹄蟹没停下来。",
  "death.attack.seapigpoison": "%1$s觉得海猪很好吃。",
```
中文句号。
不用空格。

2022-04-13 01:55 UTC, Rinko1231 commented on projects/1.16/assets/odd-water-mobs/oddwatermobs/lang/zh_cn.json
> +  "subtitles.coelacanth_hurt": "腔棘鱼受伤"
```suggestion
  "subtitles.anglerfish_hurt": "琵琶鱼：受伤",
  "subtitles.coelacanth_hurt": "腔棘鱼：受伤"
```

2022-04-13 02:29 UTC, n0099 commented on projects/1.16/assets/odd-water-mobs/oddwatermobs/lang/zh_cn.json
> +  "block.oddwatermobs.angler_bucket_block": "一桶琵琶鱼",
可以改成桶装xxx

2022-04-13 05:57 UTC, n0099 approved these changes

2022-04-13 06:30 UTC, wwowowwww commented
原版有个buff叫防火Fire Resistance，所以防毒会不会好点
弹涂鱼药水
原版好像也有生物桶好像是直接叫x桶

2022-04-13 06:55 UTC, n0099 commented
> 原版有个buff叫防火Fire Resistance，所以防毒会不会好点

但这的原文是protection而不是resistance

> 弹涂鱼药水

啥？

> 原版好像也有生物桶好像是直接叫x桶

原版的就叫`xx鱼桶`

2022-04-13 09:00 UTC, n0099 approved these changes

2022-04-13 13:16 UTC, Cyl18 commented on projects/1.16/assets/odd-water-mobs/oddwatermobs/lang/zh_cn.json
> +  "item.minecraft.potion.effect.potion_of_mudskipping_plus": "弹涂药水",
```suggestion
  "item.minecraft.potion.effect.potion_of_mudskipping": "弹涂鱼药水",
  "item.minecraft.potion.effect.potion_of_mudskipping_plus": "弹涂鱼药水",
```
统一

2022-04-16 15:59 UTC, mamaruo requested changes

2022-04-16 15:59 UTC, mamaruo commented on projects/1.16/assets/odd-water-mobs/oddwatermobs/lang/zh_cn.json
> +  "advancements.overkill.title": "赶尽杀绝",
```suggestion
  "advancements.overkill.title": "适得其反",
```
原版曾有有一成就（不是进度）叫赶尽杀绝（Overkill），目标为一次攻击伤害达到9点。但这里不应该是。

2022-04-16 15:59 UTC, mamaruo commented on projects/1.16/assets/odd-water-mobs/oddwatermobs/lang/zh_cn.json
> +  "advancements.overkill.descr": "在熔岩中身具下沉效果",
“身具”？虽然哦也想不出什么好词。
```suggestion
  "advancements.overkill.descr": "带着下沉效果在熔岩中游泳",
```

2022-04-16 15:59 UTC, mamaruo commented on projects/1.16/assets/odd-water-mobs/oddwatermobs/lang/zh_cn.json
> +  "death.attack.horseshoe": "%1$s一直在惹马蹄蟹没停下来。",
```suggestion
  "death.attack.horseshoe": "%1$s沉迷于摆弄马蹄蟹。",
```
```suggestion
  "death.attack.horseshoe": "%1$s沉迷于招惹马蹄蟹。",
```

2022-04-16 16:03 UTC, mamaruo commented on projects/1.16/assets/odd-water-mobs/oddwatermobs/lang/zh_cn.json
> +  "advancements.my_little_slimy_friend.title": "当猪游泳时",
原版成就 当猪飞的时候 When Pigs Fly

2022-04-16 16:07 UTC, mamaruo commented on projects/1.16/assets/odd-water-mobs/oddwatermobs/lang/zh_cn.json
> +  "advancements.on_the_nose.title": "鼻子上",
On the nose 有 exactly 之意

2022-04-16 16:08 UTC, mamaruo commented on projects/1.16/assets/odd-water-mobs/oddwatermobs/lang/zh_cn.json
> +  "advancements.gotcha.title": "弹无虚发！",
出处？

2022-04-16 16:10 UTC, n0099 commented on projects/1.16/assets/odd-water-mobs/oddwatermobs/lang/zh_cn.json
> +  "advancements.overkill.title": "赶尽杀绝",
那是112的，这是116的

2022-04-16 16:10 UTC, mamaruo requested changes

2022-04-16 16:10 UTC, mamaruo commented on projects/1.16/assets/odd-water-mobs/oddwatermobs/lang/zh_cn.json
> +  "item.oddwatermobs.seapig_record.desc": "baggu - 海猪",
唱片描述似乎是不翻译？

2022-04-16 16:11 UTC, n0099 commented on projects/1.16/assets/odd-water-mobs/oddwatermobs/lang/zh_cn.json
> +  "item.oddwatermobs.seapig_record.desc": "baggu - 海猪",
可以跟这mod的鱼类对应

2022-04-17 13:47 UTC, Rinko1231 commented on projects/1.16/assets/odd-water-mobs/oddwatermobs/lang/zh_cn.json
> +  "death.attack.horseshoe": "%1$s一直在惹马蹄蟹没停下来。",
赞成

> 相关：[#1834 (comment)](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1834#discussion_r849003092) @Rinko1231

2022-04-19 05:58 UTC, TartaricAcid commented on projects/1.16/assets/odd-water-mobs/oddwatermobs/lang/zh_cn.json
> +  "advancements.overkill.descr": "在熔岩中身具下沉效果",
原翻译缺失难理解

2022-04-19 06:00 UTC, TartaricAcid commented on projects/1.16/assets/odd-water-mobs/oddwatermobs/lang/zh_cn.json
> +  "advancements.on_the_nose.title": "鼻子上",
没什么好的翻译文本，先这样吧

2022-04-19 06:03 UTC, TartaricAcid approved these changes

2022-04-19 06:03 UTC, TartaricAcid approved these changes

2022-04-19 06:03 UTC, n0099 approved these changes

2022-04-19 06:05 UTC, TartaricAcid commented on projects/1.16/assets/odd-water-mobs/oddwatermobs/lang/zh_cn.json
> +  "item.oddwatermobs.seapig_record.desc": "baggu - 海猪",
这个唱片名字有特殊意思，可以翻译

2022-04-19 08:56 UTC, merged