提交corundum-meadows翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #1836
Opened 2022-04-13 15:53 UTC by tooberbios

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2022-04-13 15:56 UTC, Cyl18 commented
文件路径有误，少了 CurseForge 项目名；
标题有误，在前面加个 [R]

可以参考其它 PR

2022-04-14 01:10 UTC, Rinko1231 reviewed
`针和线`是什么翻译？
请将所有的`生成蛋`改为`刷怪蛋`。
另外`馑`是什么生物可以描述下吗。
建议：补习原版译名。

2022-04-14 01:10 UTC, Rinko1231 commented on projects/1.16/assets/corundum-meadows/zh_cn.json
> +  "item.corundum_meadows.dead_head_caterpillar_spawn_egg": "骷髅毛毛虫蛋",
```suggestion
  "item.corundum_meadows.dead_head_caterpillar_spawn_egg": "骷髅毛毛虫刷怪蛋",
```

2022-04-14 01:10 UTC, Rinko1231 commented on projects/1.16/assets/corundum-meadows/zh_cn.json
> +  "gamerule.earedSnifferSpawn.description": "针和线生成",
`针和线`又是怎么翻译出来的？

2022-04-14 01:10 UTC, Rinko1231 commented on projects/1.16/assets/corundum-meadows/zh_cn.json
> +  "item.corundum_meadows.cooked_white_catfish_meat": "煮熟的白鲶鱼肉",
```suggestion
  "item.corundum_meadows.cooked_white_catfish_meat": "熟白鲶鱼肉",
```
`熟XX`即可

2022-04-14 01:10 UTC, Rinko1231 commented on projects/1.16/assets/corundum-meadows/zh_cn.json
> +  "item.corundum_meadows.anluka_wishes.desc": "安卢卡 - 愿望",
唱片曲名应该是不翻译的。

2022-04-14 01:10 UTC, Rinko1231 commented on projects/1.16/assets/corundum-meadows/zh_cn.json
> +  "item.corundum_meadows.bucket_with_small_white_catfish": "桶装小白鲶鱼",
```suggestion
  "item.corundum_meadows.bucket_with_small_white_catfish": "小白鲶鱼桶",
```

2022-04-14 01:10 UTC, Rinko1231 commented on projects/1.16/assets/corundum-meadows/zh_cn.json
> +  "item.corundum_meadows.heated_thermal_stone": "加热热石",
有点怪。

2022-04-14 01:10 UTC, Rinko1231 commented on projects/1.16/assets/corundum-meadows/zh_cn.json
> +  "advancements.furious_rodeo.title": "愤怒的牛仔的演出",
```suggestion
  "advancements.furious_rodeo.title": "激情的牛仔表演",
```

2022-04-14 01:31 UTC, n0099 commented on projects/1.16/assets/corundum-meadows/zh_cn.json
> +  "item.corundum_meadows.heated_thermal_stone": "加热热石",
```suggestion
  "item.corundum_meadows.heated_thermal_stone": "已加热的热石",
```

2022-04-15 02:53 UTC, ZHAY10086 commented on projects/1.16/assets/corundum-meadows/zh_cn.json
> +  "gamerule.fruti_spawn.description": "黑远古黑暗草甸巨鼠生成",
黑远古黑暗草甸？打错字了吧

2022-04-15 02:57 UTC, ZHAY10086 commented on projects/1.16/assets/corundum-meadows/zh_cn.json
> +  "item.corundum_meadows.heated_thermal_stone": "加热热石",
饥荒里的 Thermal Stone 叫恒温石

2022-04-15 19:50 UTC, n0099 requested changes

2022-04-15 19:50 UTC, n0099 commented on projects/1.16/assets/corundum-meadows/zh_cn.json
> +  "item.corundum_meadows.heated_thermal_stone": "已加热的热石",
```suggestion
  "item.corundum_meadows.heated_thermal_stone": "已加热的恒温石",
```

2022-04-18 07:41 UTC, n0099 approved these changes

2022-04-18 07:47 UTC, n0099 commented
> 警告：Mod Domain 验证不通过。文件 Mod Domain 为 corundum_meadows；而 PR 所提供的 Mod Domain 为 corundum-meadows。

@Cyl18

2022-04-20 19:23 UTC, mamaruo requested changes
生成蛋还没改
<s>乱序的key整得我脑壳痛</s>

2022-04-20 19:24 UTC, mamaruo commented on projects/1.16/assets/corundum-meadows/corundum_meadows/lang/zh_cn.json
> +  "block.corundum_meadows.blooming_mossy_stone": "盛开的苔藓块",
苔藓能“盛开”？

2022-04-20 20:52 UTC, n0099 commented on projects/1.16/assets/corundum-meadows/corundum_meadows/lang/zh_cn.json
> +  "block.corundum_meadows.blooming_mossy_stone": "盛开的苔藓块",
原文如此

2022-04-24 06:05 UTC, TartaricAcid commented
我一看到乱序的语言文件就感觉不太对劲，去发布地址一看，这……

![image](https://user-images.githubusercontent.com/19620085/164958982-ac7ac925-0cba-4f74-af8d-2999e758a205.png)

https://www.curseforge.com/minecraft/mc-mods/corundum-meadows#:~:text=Mod%20created%20with%20MCreator.

2022-04-24 11:14 UTC, n0099 approved these changes

2022-04-24 11:16 UTC, n0099 commented
https://gist.github.com/thebrightspark/6d2bc3ca824fe2198b8979b070c4c943

2022-04-29 10:41 UTC, mamaruo commented
已重排
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1836/commits/37469356ce778dfa8bc96c68cf93c920b374e2b9

2022-04-29 13:06 UTC, n0099 approved these changes

2022-04-30 15:55 UTC, Cyl18 requested changes
刷怪蛋/生成蛋
另外还有一堆gamerule根本不是刷怪蛋的东西被翻译为了生成蛋

2022-12-21 00:34 UTC, dovisutu commented
之前居然一直没看到这种没挂标签的pr......
7+7挂上

-------

- 7+7时限进入第一阶段。从该评论发出的时间开始计时。

ping @tooberbios

2023-02-05 19:23 UTC, Ricky-fight commented
ping @tooberbios 迟到的第二阶段开始计时。该PR若未及时回复可能会被暂时关闭。

2023-03-11 07:18 UTC, DrIceTea123 commented
ping @tooberbios 7+7已超时
ping @Ricky-fight 此pr依据7+7可暂时关闭

2023-04-01 07:35 UTC, ChuijkYahus commented
* 7+7时限已到，如需提交可自行reopen

@tooberbios

2023-04-01 07:35 UTC, closed without merging