[R]添加avartiaaddons翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #1839
Opened 2022-04-14 10:17 UTC by mczph

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-04-14 10:19 UTC, n0099 commented
请修正路径

2022-04-14 17:14 UTC, Cyl18 commented on projects/1.12.2/assets/avaritiaddons/avaritiaddons/lang/zh_CN.lang
> +avaritiaddons.compressor.to.set.desc.2=是一个配方的材料。
原文：
avaritiaddons.compressor.to.set.desc.1=Click this "?" with an Item that is
avaritiaddons.compressor.to.set.desc.2=an Ingredient for some Recipe.
不对

2022-04-14 17:16 UTC, Cyl18 commented on projects/1.12.2/assets/avaritiaddons/avaritiaddons/lang/zh_CN.lang
> +avaritiaddons.compressor.usage.2=输入/输出的自动化。
应该是：只能通过输入输出自动化来使用

2022-04-14 17:18 UTC, Cyl18 commented on projects/1.12.2/assets/avaritiaddons/avaritiaddons/lang/zh_CN.lang
> +avaritiaddons.compressor.clear.warning=所有进度会清空。
```suggestion
avaritiaddons.compressor.clear.warning=所有进度都会丢失。
```

2022-04-15 02:17 UTC, n0099 commented on projects/1.12.2/assets/avaritiaddons/avaritiaddons/lang/zh_CN.lang
> +avaritiaddons.compressor.to.set.desc.2=是一个配方的材料。
他用的意译不是直译

2022-04-15 02:18 UTC, n0099 commented on projects/1.12.2/assets/avaritiaddons/avaritiaddons/lang/zh_CN.lang
> +avaritiaddons.compressor.to.set.desc.2=是一个配方的材料。
```suggestion
avaritiaddons.compressor.to.set.desc.1=点击”？“图标当该物品
avaritiaddons.compressor.to.set.desc.2=是某个配方使用的材料。
```

2022-04-15 12:15 UTC, Cyl18 commented on projects/1.12.2/assets/avaritiaddons/avaritiaddons/lang/zh_CN.lang
> +avaritiaddons.compressor.to.set.desc.2=是一个配方的材料。
还是不太对呀

2022-04-15 19:55 UTC, n0099 approved these changes

2022-04-16 12:23 UTC, Cyl18 requested changes

2022-04-16 12:23 UTC, Cyl18 commented on projects/1.12.2/assets/avaritiaddons/avaritiaddons/lang/zh_CN.lang
> +avaritiaddons.compressor.to.set.desc.2=是某个配方使用的材料。
with 是用一个物品来点击这个“？”还是想表达啥
具体怎么样进游戏测试一下

另外引号不对

2022-04-16 12:34 UTC, n0099 commented on projects/1.12.2/assets/avaritiaddons/avaritiaddons/lang/zh_CN.lang
> +avaritiaddons.compressor.to.set.desc.2=是某个配方使用的材料。
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1839#discussion_r850647109

2022-04-17 04:53 UTC, Cyl18 commented on projects/1.12.2/assets/avaritiaddons/avaritiaddons/lang/zh_CN.lang
> +avaritiaddons.compressor.trashcan=启用垃圾桶模式?
```suggestion
avaritiaddons.compressor.to.set.desc.1=使用某个配方使用的材料点击"？"
avaritiaddons.compressor.to.set.desc.2=来选择该配方。
avaritiaddons.compressor.no.recipe.set=没有配方选择
avaritiaddons.compressor.clear.note=提示：
avaritiaddons.compressor.clear.warning=所有进度都会丢失。
avaritiaddons.compressor.trashcan=启用垃圾桶模式？
```

2022-04-17 04:54 UTC, Cyl18 approved these changes

2022-04-19 07:00 UTC, TartaricAcid commented
文件名大小写都不对

2022-04-19 07:14 UTC, TartaricAcid commented
已有翻译：https://github.dev/CFPAOrg/Minecraft-Mod-Language-Package/pull/1865
鉴于此文件大小写错误，保留 #1865，关闭此 PR

2022-04-19 07:14 UTC, closed without merging