[WIP] [R] potion descriptions 翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #1845
Opened 2022-04-16 02:12 UTC by DSLM

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-04-16 08:09 UTC, n0099 requested changes

2022-04-16 08:09 UTC, n0099 commented on projects/1.16/assets/potion-descriptions/potiondescriptions/lang/zh_cn.json
> +    "description.effect.minecraft.water_breathing": "氧气不消耗。",
```suggestion
    "description.effect.minecraft.water_breathing": "在水中不消耗氧气。",
```

2022-04-16 08:09 UTC, n0099 commented on projects/1.16/assets/potion-descriptions/potiondescriptions/lang/zh_cn.json
> +    "description.effect.minecraft.nausea": "导致视野晃动扭曲。",
```suggestion
    "description.effect.minecraft.nausea": "使画面晃动扭曲。",
```

2022-04-16 08:09 UTC, n0099 commented on projects/1.16/assets/potion-descriptions/potiondescriptions/lang/zh_cn.json
> +    "description.effect.upgrade_aquatic.restfulness": "重置幻翼生成的失眠计时器。",
```suggestion
    "description.effect.upgrade_aquatic.insomnia": "增加生成幻翼的失眠计时器。",
    "description.effect.upgrade_aquatic.restfulness": "重置生成幻翼的失眠计时器。",
```

2022-04-16 08:09 UTC, n0099 commented on projects/1.16/assets/potion-descriptions/potiondescriptions/lang/zh_cn.json
> +    "description.effect.quark.danger_sight": "高亮显示可产生敌对生物的位置。",
```suggestion
    "description.effect.quark.danger_sight": "高亮显示可能生成敌对生物的位置。",
```

2022-04-16 09:07 UTC, n0099 approved these changes

2022-04-16 12:08 UTC, Cyl18 commented on projects/1.16/assets/potion-descriptions/potiondescriptions/lang/zh_cn.json
> +    "description.effect.minecraft.blindness": "削弱视野，无法疾跑与暴击。",
```suggestion
    "description.effect.minecraft.blindness": "削弱视野，且无法疾跑与暴击。",
```

2022-04-16 12:09 UTC, Cyl18 commented on projects/1.16/assets/potion-descriptions/potiondescriptions/lang/zh_cn.json
> +    "description.effect.minecraft.night_vision": "调亮视野。",
怪

2022-04-16 12:11 UTC, Cyl18 commented on projects/1.16/assets/potion-descriptions/potiondescriptions/lang/zh_cn.json
> +    "description.effect.minecraft.hunger": "增加饥饿等级。",
```suggestion
    "description.effect.minecraft.hunger": "加快饥饿值的降低速度。",
```

2022-04-16 12:13 UTC, Cyl18 commented on projects/1.16/assets/potion-descriptions/potiondescriptions/lang/zh_cn.json
> +    "description.effect.minecraft.absorption": "增加生命值。",
```suggestion
    "description.effect.minecraft.absorption": "临时增加一些额外的生命值。",
```

2022-04-16 12:33 UTC, n0099 commented on projects/1.16/assets/potion-descriptions/potiondescriptions/lang/zh_cn.json
> +    "description.effect.minecraft.night_vision": "调亮视野。",
```suggestion
    "description.effect.minecraft.night_vision": "调亮视野（增加伽马值）。",
```

2022-04-16 22:11 UTC, DSLM commented on projects/1.16/assets/potion-descriptions/potiondescriptions/lang/zh_cn.json
> +    "description.effect.minecraft.night_vision": "调亮视野。",
> 怪

都是从中文wiki抄的（）

2022-04-17 01:04 UTC, Cyl18 commented on projects/1.16/assets/potion-descriptions/potiondescriptions/lang/zh_cn.json
> +    "description.effect.minecraft.resistance": "减少伤害。",
```suggestion
    "description.effect.minecraft.resistance": "减少受到的伤害。",
```

2022-04-17 19:23 UTC, n0099 approved these changes

2022-04-19 08:00 UTC, TartaricAcid approved these changes

2022-04-19 09:01 UTC, n0099 approved these changes

2022-04-19 09:01 UTC, merged