[R] Funores 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1847
Opened 2022-04-16 05:01 UTC by XiaoXin1113

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-04-16 08:04 UTC, n0099 approved these changes

2022-04-16 12:40 UTC, mamaruo commented on projects/1.16/assets/fans-mod/fansmod/lang/zh_cn.json
> +  "block.fansmod.sticky_fan": "粘性风扇",
```suggestion
  "block.fansmod.sticky_fan": "黏性风扇",
```

2022-04-16 12:48 UTC, mamaruo requested changes

2022-04-16 12:48 UTC, mamaruo commented on projects/1.16/assets/fans-mod/fansmod/lang/zh_cn.json
> +  "item.fansmod.sticky_boots": "粘液靴子",
```suggestion
  "item.fansmod.sticky_boots": "黏性靴子",
```

2022-04-16 12:48 UTC, mamaruo commented on projects/1.16/assets/fans-mod/fansmod/lang/zh_cn.json
> +  "item.fansmod.leaf_blower": "树叶风扇",
Blower 怎么翻成风扇的

2022-04-16 12:48 UTC, mamaruo commented on projects/1.16/assets/fun-ores/funores/lang/zh_cn.json
> +  "block.funores.bat_ore": "蝙蝠矿",
[原版](https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96)！

ore 统一译为矿石

2022-04-16 13:02 UTC, Cyl18 commented on projects/1.16/assets/fun-ores/funores/lang/zh_cn.json
> +  "block.funores.bat_ore": "蝙蝠矿",
```suggestion
  "block.funores.bat_ore": "蝙蝠矿石",
```

2022-04-17 01:49 UTC, XiaoXin1113 commented on projects/1.16/assets/fans-mod/fansmod/lang/zh_cn.json
> +  "item.fansmod.leaf_blower": "树叶风扇",
吹风机？吹气机？那不就是风扇吗

2022-04-17 01:51 UTC, XiaoXin1113 commented on projects/1.16/assets/fun-ores/funores/lang/zh_cn.json
> +  "block.funores.bat_ore": "蝙蝠矿",
全改喽

2022-04-17 04:52 UTC, mamaruo commented on projects/1.16/assets/fans-mod/fansmod/lang/zh_cn.json
> +  "item.fansmod.leaf_blower": "树叶风扇",
你看过模组的风扇吗……这模组的风扇是个方块。

而此blower是物品，手持使用的。

2022-04-17 04:53 UTC, mamaruo approved these changes

2022-04-17 13:43 UTC, Rinko1231 commented on projects/1.16/assets/fish-traps/fishtraps/lang/zh_cn.json
> +  "block.fishtraps.iron_fish_trap": "铁制渔网",
```suggestion
  "block.fishtraps.wooden_fish_trap": "木渔网",
  "block.fishtraps.iron_fish_trap": "铁渔网",
```
要么就`钻石制渔网`统一一下

2022-04-17 13:43 UTC, Rinko1231 commented on projects/1.16/assets/fun-ores/funores/lang/zh_cn.json
> +  "block.funores.cow_ore": "奶牛矿石",
```suggestion
  "block.funores.cow_ore": "牛矿石",
```
原版`牛`

2022-04-18 07:39 UTC, n0099 approved these changes

2022-04-18 15:13 UTC, mamaruo commented on projects/1.16/assets/fans-mod/fansmod/lang/zh_cn.json
> +  "item.fansmod.leaf_blower": "树叶风扇",
```suggestion
  "item.fansmod.leaf_blower": "树叶鼓风机",
```

2022-04-18 15:14 UTC, mamaruo approved these changes

2022-04-18 18:26 UTC, Cyl18 approved these changes

2022-04-18 20:03 UTC, merged