[R] Simply Light 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #1849
Opened 2022-04-16 08:02 UTC by ZHAY10086

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2022-04-16 09:07 UTC, n0099 approved these changes

2022-04-16 11:46 UTC, mamaruo reviewed
没什么问题。
风格问题你自己判断。

2022-04-16 11:46 UTC, mamaruo commented on projects/1.16/assets/simply-light/simplylight/lang/zh_cn.json
> +  "block.simplylight.edge_light.info2": "非常适合安装在走廊。",
风格问题，无伤大雅
```suggestion
  "block.simplylight.edge_light.info2": "非常适合在走廊安装。",
```
```suggestion
  "block.simplylight.edge_light.info2": "很适合走廊。",
```

2022-04-16 11:46 UTC, mamaruo commented on projects/1.16/assets/simply-light/simplylight/lang/zh_cn.json
> +  "block.simplylight.illuminant_panel.info2": "可向任意方向放置。",
风格
```suggestion
  "block.simplylight.illuminant_panel.info2": "可朝任意方向放置。",
```

2022-04-16 11:46 UTC, mamaruo commented on projects/1.16/assets/simply-light/simplylight/lang/zh_cn.json
>    "block.simplylight.wall_lamp": "发光灯具",
灯具本身就是发光的，这有点怪异。
可原文就是 Illuminant Fixture

2022-04-16 12:08 UTC, ZHAY10086 commented on projects/1.16/assets/simply-light/simplylight/lang/zh_cn.json
>    "block.simplylight.wall_lamp": "发光灯具",
合理怀疑作者是嗯凑 Illuminant

2022-04-16 12:17 UTC, Cyl18 approved these changes

2022-04-16 12:19 UTC, Cyl18 requested changes

2022-04-16 12:19 UTC, Cyl18 commented on projects/1.16/assets/simply-light/simplylight/lang/zh_cn.json
> +  "block.simplylight.illuminant_slab.info2": "可向任意方向放置。",
```suggestion
  "block.simplylight.illuminant_slab.info2": "可朝任意方向放置。",

```

2022-04-16 12:19 UTC, Cyl18 commented on projects/1.16/assets/simply-light/simplylight/lang/zh_cn.json
> +  "block.simplylight.lightbulb.info2": "可向任意方向放置。",
```suggestion
  "block.simplylight.lightbulb.info2": "可朝任意方向放置。",

```

2022-04-16 12:19 UTC, Cyl18 commented on projects/1.16/assets/simply-light/simplylight/lang/zh_cn.json
> +  "block.simplylight.rodlamp.info2": "可向任意方向放置。",
```suggestion
  "block.simplylight.rodlamp.info2": "可朝任意方向放置。",

```

2022-04-16 12:32 UTC, mamaruo approved these changes

2022-04-16 12:36 UTC, n0099 commented on projects/1.16/assets/simply-light/simplylight/lang/zh_cn.json
>    "block.simplylight.wall_lamp": "发光灯具",
原版红石灯还可以关闭呢

2022-04-16 12:36 UTC, n0099 commented
我局的`可向`比`可朝`更好
折中一下`可朝向`

2022-04-17 02:15 UTC, Cyl18 approved these changes

2022-04-17 05:04 UTC, mamaruo commented
> 我局的`可向`比`可朝`更好 折中一下`可朝向`

`朝向任意方向放置。`
我总觉得两个`向`字看起来不对劲

2022-04-17 06:11 UTC, n0099 commented
> > 我局的`可向`比`可朝`更好 折中一下`可朝向`
> 
> `朝向任意方向放置。` 我总觉得两个`向`字看起来不对劲

建议任何面

2022-04-17 06:12 UTC, n0099 approved these changes

2022-04-17 06:12 UTC, merged