[R] Fabrictools 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1857
Opened 2022-04-17 05:02 UTC by XiaoXin1113

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-04-17 05:15 UTC, mamaruo requested changes

2022-04-17 05:15 UTC, mamaruo commented on projects/1.16/assets/glass-cutter/glasscutter/lang/zh_cn.json
> +  "item.glasscutter.glasscutter_strong": "黑曜石玻璃切割器"
建议与 #1587 统一

2022-04-17 05:59 UTC, n0099 commented on projects/1.16/assets/glass-cutter/glasscutter/lang/zh_cn.json
> +  "item.glasscutter.glasscutter_strong": "黑曜石玻璃切割器"
都不是同一个mod

2022-04-17 07:08 UTC, Rinko1231 commented on projects/1.16/assets/iap-mekanism/iapmekanism/lang/zh_cn.json
> +  "crop.industrialagriculture.refined_obsidian": "精炼黑曜石",
```suggestion
  "crop.industrialagriculture.refined_glowstone": "强化荧石",
  "crop.industrialagriculture.refined_obsidian": "强化黑曜石",
```
mek译名如此，理应一致。

2022-04-17 07:14 UTC, XiaoXin1113 commented on projects/1.16/assets/glass-cutter/glasscutter/lang/zh_cn.json
> +  "item.glasscutter.glasscutter_strong": "黑曜石玻璃切割器"
草了

2022-04-17 07:31 UTC, mamaruo commented on projects/1.16/assets/glass-cutter/glasscutter/lang/zh_cn.json
> +  "item.glasscutter.glasscutter_strong": "黑曜石玻璃切割器"
我大意了，这个cutter是手持的物品

2022-04-17 07:37 UTC, mamaruo approved these changes

2022-04-17 11:28 UTC, Cyl18 approved these changes

2022-04-17 11:28 UTC, Cyl18 commented on projects/1.16/assets/giselbaers-durability-viewer/fabrictools/lang/zh_cn.json
> +  "de.guntram.mcmod.fabrictools.false": "关",
这里确定是开关吗

2022-04-18 03:45 UTC, XiaoXin1113 commented on projects/1.16/assets/glass-cutter/glasscutter/lang/zh_cn.json
> +  "item.glasscutter.glasscutter_strong": "黑曜石玻璃切割器"
啊对对对

2022-04-18 03:45 UTC, XiaoXin1113 commented on projects/1.16/assets/giselbaers-durability-viewer/fabrictools/lang/zh_cn.json
> +  "de.guntram.mcmod.fabrictools.false": "关",
不确定，但总不能翻成“真”“假”吧

2022-04-18 05:01 UTC, mamaruo commented on projects/1.16/assets/giselbaers-durability-viewer/fabrictools/lang/zh_cn.json
> +  "de.guntram.mcmod.fabrictools.false": "关",
进游戏看

2022-04-18 12:37 UTC, n0099 commented on projects/1.16/assets/giselbaers-durability-viewer/fabrictools/lang/zh_cn.json
> +  "de.guntram.mcmod.fabrictools.false": "关",
官中比这还谔谔 https://github.com/gbl/DurabilityViewer/blob/forge_1_16_2/src/main/resources/assets/fabrictools/lang/zn_ch.json

2022-04-18 12:42 UTC, n0099 approved these changes

2022-04-18 17:14 UTC, merged