[R]增加ringsofascension翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #1859
Opened 2022-04-17 06:17 UTC by Wulian233

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-04-17 06:28 UTC, mamaruo commented
仍然是路径问题。

2022-04-17 07:05 UTC, Rinko1231 reviewed
一些戒指的译名虽然确实有几分魔幻气息，奈何原文的用词跟原版一致。

2022-04-17 07:05 UTC, Rinko1231 commented on projects/1.16-fabric/assets/respawnable-pets/respawnablepets/lang/zh_cn.json
> +    "respawnablepets.tooltip.etheric_gem": "允许你通过打击切换宠物重生",
`打击`，怪怪的。

2022-04-17 07:05 UTC, Rinko1231 commented on projects/1.16-fabric/assets/ringsofascension/zh_cn.json
> +    "item.ringsofascension.ring_slow_falling": "羽落戒指",
```suggestion
    "item.ringsofascension.ring_slow_falling": "缓降戒指",
```
原文slow falling在原版中是`缓降`

2022-04-17 07:05 UTC, Rinko1231 commented on projects/1.16-fabric/assets/ringsofascension/zh_cn.json
> +    "item.ringsofascension.ring_jump_boost": "灵跃戒指",
```suggestion
    "item.ringsofascension.ring_jump_boost": "跳跃提升戒指",
```

2022-04-18 07:37 UTC, n0099 commented
没必要一定改成原版译名

2022-04-18 15:23 UTC, mamaruo commented
respawnable-pets 缺少 en_us
建议分开提交这两个模组

2022-04-20 07:24 UTC, TartaricAcid commented
rings of ascension 的文件结构全都不对，我已经修改好了

2022-04-20 07:30 UTC, TartaricAcid commented
respawnable-pets 模组最新版语言文件都是全覆盖的，我删掉了它

2022-04-20 12:17 UTC, mamaruo commented on projects/1.16-fabric/assets/fabric-rings-of-ascension/ringsofascension/lang/zh_cn.json
> +    "itemGroup.ringsofascension.rings": "提升戒指",
我表示怀疑

2022-04-20 14:18 UTC, Rinko1231 commented on projects/1.16-fabric/assets/fabric-rings-of-ascension/ringsofascension/lang/zh_cn.json
> +    "itemGroup.ringsofascension.rings": "提升戒指",
```suggestion
    "itemGroup.ringsofascension.rings": "飞升之戒",
```

2022-04-20 18:47 UTC, mamaruo requested changes

2022-04-20 18:47 UTC, mamaruo commented on projects/1.16-fabric/assets/fabric-rings-of-ascension/ringsofascension/lang/zh_cn.json
> +    "tooltip.ringsofascension.hungerless": "维持满饥饿度",
```suggestion
    "tooltip.ringsofascension.hungerless": "维持满饥饿值",

```

2022-04-20 18:47 UTC, mamaruo commented on projects/1.16-fabric/assets/fabric-rings-of-ascension/ringsofascension/lang/zh_cn.json
> +    "tooltip.ringsofascension.undying_cooldown": "冷却： secondsHere秒",
```suggestion
    "tooltip.ringsofascension.undying_cooldown": "冷却：secondsHere秒",

```

2022-04-20 18:48 UTC, mamaruo commented
1.18 模组名还没改……
PR 提交者也没见人，在暗中观察吗

2022-04-21 06:29 UTC, Rinko1231 reviewed
统一`飞升之戒`？

2022-04-21 06:29 UTC, Rinko1231 commented on projects/1.16/assets/rings-of-ascension/ringsofascension/lang/zh_cn.json
> +    "itemGroup.ringsofascension.rings": "提升戒指",
```suggestion
    "itemGroup.ringsofascension.rings": "飞升之戒",

```

2022-04-21 06:29 UTC, Rinko1231 commented on projects/1.18-fabric/assets/fabric-rings-of-ascension/ringsofascension/lang/zh_cn.json
> +    "itemGroup.ringsofascension.rings": "提升戒指",
```suggestion
    "itemGroup.ringsofascension.rings": "飞升之戒",

```

2022-04-21 06:29 UTC, Rinko1231 commented on projects/1.18/assets/rings-of-ascension/ringsofascension/lang/zh_cn.json
> +    "itemGroup.ringsofascension.rings": "提升戒指",
```suggestion
    "itemGroup.ringsofascension.rings": "飞升之戒",

```

2022-04-24 06:56 UTC, TartaricAcid approved these changes

2022-04-24 11:19 UTC, merged