[WIP][R] 3个模组翻译（未完成）
CFPAOrg/Minecraft-Mod-Language-Package pull request #1860
Opened 2022-04-17 08:42 UTC by DSLM

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-04-18 20:01 UTC, n0099 approved these changes

2022-04-18 20:01 UTC, n0099 commented on projects/1.16/assets/entangled/entangled/lang/zh_cn.json
> +  "entangled.entangled_block.info.ranged_other_dimension": "可以绑定同一维度内至多%d格远的方块或其他维度的方块",
```suggestion
  "entangled.entangled_block.info.ranged_same_dimension": "可以绑定同一维度内至远%d格的方块",
  "entangled.entangled_block.info.infinite_same_dimension": "可以绑定同一维度内的方块",
  "entangled.entangled_block.info.ranged_other_dimension": "可以绑定同一维度内最远%d格的方块或其他维度的方块",
```

2022-04-18 20:01 UTC, n0099 commented on projects/1.16/assets/entangled/entangled/lang/zh_cn.json
> +  "entangled.waila.bound_other_dimension": "绑定至位于%5$s维度（%2$d，%3$d，%4$d）的%1$s",
要不要加已前缀（过去完成时）

2022-04-18 20:48 UTC, DSLM commented on projects/1.16/assets/entangled/entangled/lang/zh_cn.json
> +  "entangled.waila.bound_other_dimension": "绑定至位于%5$s维度（%2$d，%3$d，%4$d）的%1$s",
加了

2022-04-18 21:43 UTC, n0099 requested changes

2022-04-18 21:43 UTC, n0099 commented on projects/1.16/assets/entangled/entangled/lang/zh_cn.json
> +  "entangled.entangled_block.info.ranged_same_dimension": "可以绑定同一维度内至远%d格的方块",
```suggestion
  "entangled.entangled_block.info.ranged_same_dimension": "可以绑定同一维度内最远%d格的方块",
```

2022-04-18 21:44 UTC, n0099 approved these changes

2022-04-19 00:02 UTC, DSLM commented on projects/1.16/assets/entangled/entangled/lang/zh_cn.json
> +  "entangled.entangled_block.info.ranged_same_dimension": "可以绑定同一维度内至远%d格的方块",
为啥要用同素维度这种写法

2022-04-19 05:29 UTC, Rinko1231 commented on projects/1.16/assets/corail-woodcutter/corail_woodcutter/lang/zh_cn.json
> +  "block.corail_woodcutter.cherry_woodcutter": "樱花木锯木机",
```suggestion
  "block.corail_woodcutter.cherry_woodcutter": "樱桃木锯木机",
```
这应该是BOP的联动吧，BOP的是樱桃木

2022-04-19 05:50 UTC, n0099 commented on projects/1.16/assets/entangled/entangled/lang/zh_cn.json
> +  "entangled.entangled_block.info.ranged_same_dimension": "可以绑定同一维度内至远%d格的方块",
什么同素维度

2022-04-19 06:06 UTC, DSLM commented on projects/1.16/assets/entangled/entangled/lang/zh_cn.json
> +  "entangled.entangled_block.info.ranged_same_dimension": "可以绑定同一维度内至远%d格的方块",
啊这，之前我这边显示的是同素维度，不知道出了什么问题

2022-04-19 08:57 UTC, n0099 commented
您还在WIP吗

2022-04-19 09:12 UTC, DSLM commented
> 您还在WIP吗

![Screenshot_20220419-051052_QQ.jpg](https://user-images.githubusercontent.com/12635058/163970881-57bd9de0-926d-40fe-b745-9b1e3b90c676.jpg)
WIP不是表示有东西没做完不想做吗，我之前还特意问了一下来着

2022-04-19 11:13 UTC, n0099 commented
所以我问您做完了没，要不要merge

2022-04-19 13:18 UTC, DSLM commented
@n0099 可以merge了

2022-04-19 23:17 UTC, Cyl18 approved these changes

2022-04-20 01:38 UTC, mamaruo commented
根据 #1770，建议每 200 行切分一个 PR，可以根据相关性来切分。

2022-04-20 07:13 UTC, TartaricAcid approved these changes

2022-04-20 19:04 UTC, mamaruo approved these changes

2022-04-20 19:04 UTC, mamaruo commented on projects/1.16/assets/entangled/entangled/lang/zh_cn.json
> +  "entangled.entangled_block.info.infinite_other_dimension": "可以绑定其他方块",
```suggestion
  "entangled.entangled_block.info.ranged_same_dimension": "可以绑定到同一维度内最远%d格的方块",
  "entangled.entangled_block.info.infinite_same_dimension": "可以绑定到同一维度内的方块",
  "entangled.entangled_block.info.ranged_other_dimension": "可以绑定到同一维度内最远%d格的方块或其他维度的方块",
  "entangled.entangled_block.info.infinite_other_dimension": "可以绑定到其他方块",
```
因为原文是`Can be bound to blocks`，不知道现在的译法会不会产生歧义。

2022-04-20 20:18 UTC, DSLM commented on projects/1.16/assets/entangled/entangled/lang/zh_cn.json
> +  "entangled.entangled_block.info.infinite_other_dimension": "可以绑定其他方块",
![image](https://user-images.githubusercontent.com/12635058/164315339-70006d3f-9879-4034-9baa-4bf9f7af6447.png)
歧义应该不会，但改一下好像看起来更通顺些

2022-04-20 20:48 UTC, merged