[R] 星辉附加等四个模组汉化
CFPAOrg/Minecraft-Mod-Language-Package pull request #1861
Opened 2022-04-17 10:45 UTC by mczph

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-04-18 07:39 UTC, n0099 requested changes

2022-04-18 07:39 UTC, n0099 commented on projects/1.12.2/assets/filing-cabinets-refurbished/filcabref/lang/zh_cn.lang
> +filcabref.misc.notif.capacity_upgrade.success=安装容量升级。
```suggestion
filcabref.misc.notif.capacity_upgrade.success=容量升级已安装。

```

2022-04-18 07:39 UTC, n0099 commented on projects/1.12.2/assets/filing-cabinets-refurbished/filcabref/lang/zh_cn.lang
> +filcabref.misc.tooltip.capacity_upgrade=提升文档柜容量。
```suggestion
filcabref.misc.tooltip.capacity_upgrade=可提升文档柜容量。

```

2022-04-18 12:41 UTC, n0099 approved these changes

2022-04-20 02:16 UTC, Cyl18 commented on projects/1.12.2/assets/filing-cabinets-refurbished/filcabref/lang/zh_cn.lang
> +filcabref.misc.tooltip.filing_cabinet.basic=可以储存同ID的方块/物品。
原文`Stores variants of one type of item.`
不太好

2022-04-20 05:13 UTC, mczph commented on projects/1.12.2/assets/filing-cabinets-refurbished/filcabref/lang/zh_cn.lang
> +filcabref.misc.tooltip.filing_cabinet.basic=可以储存同ID的方块/物品。
这个是看的
https://www.mcmod.cn/item/33454.html

2022-04-20 06:01 UTC, Cyl18 commented on projects/1.12.2/assets/astral-additions/astraladditions/lang/zh_cn.lang
> +tile.block_marble_chiseled_wall.name=雕纹大理石墙
```suggestion
tile.block_marble_chiseled_wall.name=錾制大理石墙
```

2022-04-20 06:01 UTC, Cyl18 commented on projects/1.12.2/assets/astral-additions/astraladditions/lang/zh_cn.lang
> +tile.block_black_marble_chiseled_wall.name=熏黑雕纹大理石墙
```suggestion
tile.block_black_marble_chiseled_wall.name=熏黑錾制大理石墙
```

2022-04-20 15:36 UTC, n0099 approved these changes

2022-04-23 04:29 UTC, mamaruo commented on projects/1.12.2/assets/filing-cabinets-refurbished/filcabref/lang/zh_cn.lang
> +tile.filcabref:filing_cabinet1.name=文档柜（高级）
为何用括号

2022-04-23 09:05 UTC, n0099 commented on projects/1.12.2/assets/filing-cabinets-refurbished/filcabref/lang/zh_cn.lang
> +tile.filcabref:filing_cabinet1.name=文档柜（高级）
毕竟112

2022-04-23 09:36 UTC, merged