[R] Caged Mobs 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1864
Opened 2022-04-18 03:12 UTC by Rinko1231

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-04-18 12:33 UTC, n0099 requested changes

2022-04-18 12:33 UTC, n0099 commented on projects/1.16/assets/caged-mobs/cagedmobs/lang/zh_cn.json
> +	"item.cagedmobs.dnasampler.makeEmpty": "Shift右击以清空DNA采样器",
```suggestion
	"item.cagedmobs.dnasampler.makeEmpty": "Shift+右击以清空DNA采样器",
```

2022-04-18 12:33 UTC, n0099 commented on projects/1.16/assets/caged-mobs/cagedmobs/lang/zh_cn.json
> +	"block.cagedmobs.starinfusednetheriteblock.beacon": "可作为信标底座方块。",
```suggestion
	"block.cagedmobs.starinfusednetheriteblock.beacon": "可作为信标基座方块。",
```

2022-04-18 13:36 UTC, n0099 approved these changes

2022-04-18 16:12 UTC, mamaruo commented on projects/1.16/assets/caged-mobs/cagedmobs/lang/zh_cn.json
> +	"item.cagedmobs.arrowupgrade": "笼子升级：箭升级",
有没有必要重复“升级”二字？

2022-04-18 16:12 UTC, mamaruo commented on projects/1.16/assets/caged-mobs/cagedmobs/lang/zh_cn.json
> +	"HWYLA.tooltip.cagedmobs.cage.entity": "生物：",
```suggestion
	"HWYLA.tooltip.cagedmobs.cage.entity": "实体：",

```

2022-04-18 16:12 UTC, mamaruo commented on projects/1.16/assets/caged-mobs/cagedmobs/lang/zh_cn.json
> +	"jei.tooltip.cagedmobs.entity.colorItem": "仅由被染色的生物掉落",
```suggestion
	"jei.tooltip.cagedmobs.entity.colorItem": "仅由染过色生物掉落",
```
本条是瞎提的意见

2022-04-18 16:12 UTC, mamaruo commented on projects/1.16/assets/caged-mobs/cagedmobs/lang/zh_cn.json
> +	"block.cagedmobs.mobcage.hoppingCagesDisabled1": "自动收获已被禁用。",
```suggestion
	"block.cagedmobs.mobcage.hoppingCagesDisabled1": "自动收获已禁用。",

```

2022-04-18 20:06 UTC, n0099 commented on projects/1.16/assets/caged-mobs/cagedmobs/lang/zh_cn.json
> +	"jei.tooltip.cagedmobs.entity.colorItem": "仅由被染色的生物掉落",
这不一个意思？

2022-04-18 22:50 UTC, Cyl18 commented on projects/1.16/assets/caged-mobs/cagedmobs/lang/zh_cn.json
> +	"jei.tooltip.cagedmobs.entity.colorItem": "仅由被染色的生物掉落",
或者`只有染色生物才会掉落`

2022-04-18 22:53 UTC, Cyl18 commented on projects/1.16/assets/caged-mobs/cagedmobs/lang/zh_cn.json
> +	"item.cagedmobs.arrowupgrade": "笼子升级：箭升级",
`笼子升级：箭`
`笼子：箭升级`

2022-04-19 05:47 UTC, n0099 commented on projects/1.16/assets/caged-mobs/cagedmobs/lang/zh_cn.json
> +	"jei.tooltip.cagedmobs.entity.colorItem": "仅由被染色的生物掉落",
```suggestion
	"jei.tooltip.cagedmobs.entity.colorItem": "只有染色生物才会掉落",
```

2022-04-19 05:47 UTC, n0099 approved these changes

2022-04-20 02:09 UTC, Cyl18 commented on projects/1.16/assets/caged-mobs/cagedmobs/lang/zh_cn.json
> +	"item.cagedmobs.dnasampler.not_sufficient": "该DNA采样器不足以对该生物进行取样",
```suggestion
	"item.cagedmobs.dnasampler.not_sufficient": "该DNA采样器的等级不足以对该生物进行取样",

```

2022-04-20 02:36 UTC, Cyl18 approved these changes

2022-04-20 15:29 UTC, merged