更新 productivebees 汉化文件
CFPAOrg/Minecraft-Mod-Language-Package pull request #1874
Opened 2022-04-21 08:08 UTC by yanxisi

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-04-21 09:12 UTC, n0099 requested changes

2022-04-21 09:12 UTC, n0099 commented on projects/1.16/assets/productivebees/productivebees/lang/zh_cn.json
> +    "block.productivebees.expansion_box_bop_cherry": "樱木扩容盒",
```suggestion
    "block.productivebees.expansion_box_bop_cherry": "樱桃木扩容盒",
```

2022-04-21 09:12 UTC, n0099 commented on projects/1.16/assets/productivebees/productivebees/lang/zh_cn.json
> +    "block.productivebees.advanced_bop_cherry_beehive": "高级樱木蜂巢",
```suggestion
    "block.productivebees.advanced_bop_cherry_beehive": "高级樱桃木蜂巢",
```

2022-04-21 09:12 UTC, n0099 commented on projects/1.16/assets/productivebees/productivebees/lang/zh_cn.json
> +    "productivebees.information.nestlocator.unconfigured": "未调谐。Shift+右键单击要寻找的蜂巢的同种方块。",
```suggestion
    "productivebees.information.nestlocator.configured": "可以找到%s类巢穴。右击以搜索附近区域。",
    "productivebees.information.nestlocator.unconfigured": "未调谐。Shift+右击要寻找的蜂巢的同种方块。",
```

2022-04-21 09:12 UTC, n0099 commented on projects/1.16/assets/productivebees/productivebees/lang/zh_cn.json
> +    "productivebees.information.upgrade.upgrade_filter_empty": "右键单击蜜蜂来将其添加到过滤器。",
```suggestion
    "productivebees.information.upgrade.upgrade_filter_empty": "右击蜜蜂来将其添加到过滤器。",
```

2022-04-21 09:12 UTC, n0099 commented on projects/1.16/assets/productivebees/productivebees/lang/zh_cn.json
> +    "productivebees.ingredient.description.bumble_bee": "一种在平原上自然发现的大型可骑行蜜蜂。装上鞍，拿着蜂蜜小食钓竿就可以在周围滑翔。右键单击来激励它。",
```suggestion
    "productivebees.ingredient.description.bumble_bee": "一种在平原上自然发现的大型可骑行蜜蜂。装上鞍，拿着蜂蜜小食钓竿就可以在周围滑翔。右击来激励它。",
```

2022-04-21 15:04 UTC, Rinko1231 commented on projects/1.16/assets/productivebees/productivebees/lang/zh_cn.json
> +    "block.productivebees.comb_magmatic": "熔岩蜜脾块",
magma应为`岩浆`

2022-04-21 15:04 UTC, Rinko1231 commented on projects/1.16/assets/productivebees/productivebees/lang/zh_cn.json
> +    "item.productivebees.honeycomb_blizz": "暴雪蜜脾",
前面是烈焰人岩石人狂风人，这里为何不带“人”

2022-04-21 22:43 UTC, Exroia commented on projects/1.16/assets/productivebees/productivebees/lang/zh_cn.json
> +    "block.productivebees.comb_draconic": "末影龙蜜脾块",
不是龙研的，这个蜜脾的离心产出是用来做龙蛋的

2022-04-21 22:52 UTC, Exroia commented on projects/1.16/assets/productivebees/productivebees/lang/zh_cn.json
> +    "item.productivebees.honeycomb_blizz": "暴雪蜜脾",
已修改

2022-04-22 09:36 UTC, n0099 approved these changes

2022-04-22 13:49 UTC, mamaruo commented
与有参考清秋版的汉化吗
详见https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/4108052e6a448108fa950e046c8f5b75f9dfaf07

2022-04-22 14:17 UTC, Exroia commented
> 与有参考清秋版的汉化吗 详见[4108052](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/4108052e6a448108fa950e046c8f5b75f9dfaf07)

没，参考的MCmod上的缤纷蜜蜂Resourceful Bees与资源蜜蜂Productive Bees

2022-04-24 07:02 UTC, TartaricAcid commented on projects/1.16/assets/productivebees/productivebees/lang/zh_cn.json
> +    "productivebees.information.attribute.behavior.metaturnal": "Metaturnal",
这个翻译缺失，之前清秋翻译的是 `不特定时间`

2022-04-24 07:07 UTC, TartaricAcid commented on projects/1.16/assets/productivebees/productivebees/lang/zh_cn.json
> +    "productivebees.information.attribute.behavior.diurnal": "日行性",
`昼行性` 感觉更好点？

2022-04-24 07:09 UTC, TartaricAcid commented on projects/1.16/assets/productivebees/productivebees/lang/zh_cn.json
> +    "productivebees.ingredient.description.reed_bee": "在芦苇中筑巢...",
应该使用中文全角省略号？

2022-04-24 07:09 UTC, TartaricAcid approved these changes

2022-04-24 07:19 UTC, DSLM commented on projects/1.16/assets/productivebees/productivebees/lang/zh_cn.json
> +    "productivebees.information.attribute.behavior.metaturnal": "Metaturnal",
全日性之类的？

2022-04-24 10:29 UTC, Exroia commented on projects/1.16/assets/productivebees/productivebees/lang/zh_cn.json
> +    "productivebees.information.attribute.behavior.diurnal": "日行性",
已更改

2022-04-24 10:29 UTC, Exroia commented on projects/1.16/assets/productivebees/productivebees/lang/zh_cn.json
> +    "productivebees.ingredient.description.reed_bee": "在芦苇中筑巢...",
已更改

2022-04-24 10:30 UTC, Exroia commented on projects/1.16/assets/productivebees/productivebees/lang/zh_cn.json
> +    "productivebees.information.attribute.behavior.metaturnal": "Metaturnal",
已更改为昼夜双行性

2022-04-24 11:33 UTC, n0099 approved these changes

2022-04-24 11:33 UTC, merged