[R][WIP]提交EnderIO Alloys 翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #1877
Opened 2022-04-22 14:16 UTC by Cactusstudent

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-04-22 14:41 UTC, mamaruo requested changes

2022-04-22 14:41 UTC, mamaruo commented on projects/1.16/assets/enderio-alloys/enderioalloys/zh_cn.json
> +    "item.enderioalloys.item_material_skull_guardian_diode": "守卫者电子二极管",
```suggestion
    "item.enderioalloys.item_material_skull_guardian_diode": "守卫者二极管",

```

2022-04-22 14:41 UTC, mamaruo commented on projects/1.16/assets/enderio-alloys/enderioalloys/zh_cn.json
> +    "item.enderioalloys.item_alloy_ingot_vibrant_alloy": "脉冲合金锭",
```suggestion
    "block.enderioalloys.block_alloy_vibrant_alloy": "Vibrant Alloy块",
    "item.enderioalloys.item_alloy_nugget_vibrant_alloy": "Vibrant Alloy粒",
    "item.enderioalloys.item_alloy_ingot_vibrant_alloy": "Vibrant Alloy锭",
```

2022-04-22 14:41 UTC, mamaruo commented on projects/1.16/assets/enderio-alloys/enderioalloys/zh_cn.json
> +    "item.enderioalloys.item_alloy_ingot_end_steel": "End Steel 锭",
```suggestion
    "block.enderioalloys.block_alloy_end_steel": "末地钢块",
    "item.enderioalloys.item_alloy_nugget_end_steel": "末地钢粒",
    "item.enderioalloys.item_alloy_ingot_end_steel": "末地钢锭",
```

2022-04-22 14:42 UTC, mamaruo commented on projects/1.16/assets/enderio-alloys/enderioalloys/zh_cn.json
> +    "itemGroup.enderioalloys": "末影接口 | 合金",
```suggestion
    "itemGroup.enderioalloys": "末影接口丨合金"
```
汉字丨，gun3

2022-04-22 14:44 UTC, mamaruo commented
草，都是争议译名，直接就commit了吗……

2022-04-22 14:48 UTC, Cactusstudent commented
> 草，都是争议译名，直接就commit了吗……

我主要当时整的时候就想是留原文还是先用现有译名，但是我刚去瞅了瞅之前的那个汉化用词和wiki来着，还是commit吧（主要我没啥主意了）

2022-04-22 14:50 UTC, Cactusstudent commented
但是我记得之前不是改了好几次，最后叫做脉冲合金

2022-04-22 15:11 UTC, mamaruo commented
我在一个多月前MC百科编辑员群得到的多数意见是脉冲合金不对，振动合金（ChromaPIE 译）也不对。

2022-04-22 15:24 UTC, mamaruo requested changes

2022-04-22 15:24 UTC, mamaruo commented on projects/1.16/assets/enderio-alloys/enderioalloys/zh_cn.json
> +    "item.enderioalloys.item_alloy_ingot_electrical_steel": "磁钢锭",
```suggestion
    "block.enderioalloys.block_alloy_electrical_steel": "电工钢块",
    "item.enderioalloys.item_alloy_nugget_electrical_steel": "电工钢粒",
    "item.enderioalloys.item_alloy_ingot_electrical_steel": "电工钢锭",
```
我的 1.18 译名草案（未公开）如是说

2022-04-22 15:24 UTC, mamaruo commented on projects/1.16/assets/enderio-alloys/enderioalloys/zh_cn.json
> +    "item.enderioalloys.item_alloy_ingot_crystalline_pink_slime": "晶化粉红粘液锭",
```suggestion
    "block.enderioalloys.block_alloy_crystalline_pink_slime": "晶化粉红黏液块",
    "item.enderioalloys.item_alloy_nugget_crystalline_pink_slime": "晶化粉红黏液粒",
    "item.enderioalloys.item_alloy_ingot_crystalline_pink_slime": "晶化粉红黏液锭",
```
[Minecraft Wiki:译名标准化/历史 - Minecraft Wiki，最详细的我的世界百科](https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96/%E5%8E%86%E5%8F%B2)
![image](https://user-images.githubusercontent.com/37480168/164744944-32262e47-c5b6-44bc-bb16-efac5d1712dd.png)

2022-04-22 16:23 UTC, mamaruo commented on projects/1.16/assets/enderio-alloys/enderioalloys/zh_cn.json
> +    "item.enderioalloys.item_material_gear_vibrant": "脉冲合金齿轮",
```suggestion
    "item.enderioalloys.item_material_gear_darksteel": "玄钢双金属齿轮",
    "item.enderioalloys.item_material_gear_energized": "充能合金双金属齿轮",
    "item.enderioalloys.item_material_gear_iron": "铁齿轮",
    "item.enderioalloys.item_material_gear_stone": "石头复合齿轮",
    "item.enderioalloys.item_material_gear_vibrant": "Vibrant Alloy双金属齿轮",
```

2022-04-22 16:23 UTC, mamaruo commented on projects/1.16/assets/enderio-alloys/enderioalloys/zh_cn.json
> +    "item.enderioalloys.item_material_skull_zombie_controller": "Z-逻辑控制器",
```suggestion
    "item.enderioalloys.item_material_skull_zombie_controller": "僵尸逻辑控制器",

```

2022-04-22 17:01 UTC, n0099 commented on projects/1.16/assets/enderio-alloys/enderioalloys/zh_cn.json
> +    "item.enderioalloys.item_material_skull_zombie_controller": "Z-逻辑控制器",
112时不是叫z逻辑吗

2022-04-22 17:07 UTC, mamaruo commented on projects/1.16/assets/enderio-alloys/enderioalloys/zh_cn.json
> +    "item.enderioalloys.item_material_skull_zombie_controller": "Z-逻辑控制器",
依据是本地化键写的 zombie，推测 Z-指僵尸。

2022-04-22 18:55 UTC, 1048139283 commented
最好能找作者问个明白

2022-04-22 19:02 UTC, Cyl18 commented
路径应为 projects/1.16/assets/enderio-alloys/enderioalloys/**lang**/en_us.json

2022-04-22 19:05 UTC, Cyl18 commented on projects/1.16/assets/enderio-alloys/enderioalloys/zh_cn.json
> +    "item.enderioalloys.item_material_skull_zombie_controller": "Z-逻辑控制器",
![image](https://user-images.githubusercontent.com/14993992/164778278-94353797-8c4d-40ec-a2a1-4ec9c62b5768.png)
![image](https://user-images.githubusercontent.com/14993992/164778296-f29b2ddf-3370-4dde-908d-70df92ea2a3d.png)

2022-04-22 21:50 UTC, n0099 commented on projects/1.16/assets/enderio-alloys/enderioalloys/zh_cn.json
> +    "item.enderioalloys.item_material_skull_zombie_controller": "Z-逻辑控制器",
我只能说别像之前把eio `SAG磨机`改成半自磨机那样

2022-04-23 04:25 UTC, mamaruo commented on projects/1.16/assets/enderio-alloys/enderioalloys/zh_cn.json
> +    "item.enderioalloys.item_material_skull_zombie_controller": "Z-逻辑控制器",
最难改的译名……半自磨机早在 2017 年 MCBBS 搬运贴楼主就提出了。

个人认为由于多方面原因，Z-逻辑控制器 和 SAG磨粉机 最后不改的可能性较大。

2022-04-23 05:54 UTC, Cactusstudent commented
路径已经更改（应该没错误吧）

2022-04-23 05:57 UTC, Cactusstudent commented on projects/1.16/assets/enderio-alloys/enderioalloys/zh_cn.json
> +    "item.enderioalloys.item_material_skull_zombie_controller": "Z-逻辑控制器",
这翻译可真让人头大，那等着EIO1.18官方译名出来再进行更改？

2022-04-23 08:04 UTC, mamaruo requested changes

2022-04-23 08:04 UTC, mamaruo commented on projects/1.16/assets/enderio-alloys/enderioalloys/lang/zh_cn
> +    "item.enderioalloys.item_material_glazed_nether_brick": "釉制地狱砖",
```suggestion
    "item.enderioalloys.item_material_glazed_nether_brick": "釉面下界砖",

```

2022-04-24 17:09 UTC, mamaruo commented on projects/1.16/assets/enderio-alloys/enderioalloys/zh_cn.json
> +    "item.enderioalloys.item_material_skull_zombie_controller": "Z-逻辑控制器",
官译很大可能是我定……

2022-04-24 17:10 UTC, n0099 commented on projects/1.16/assets/enderio-alloys/enderioalloys/zh_cn.json
> +    "item.enderioalloys.item_material_skull_zombie_controller": "Z-逻辑控制器",
那请 SAG磨机 Z-逻辑

2022-04-24 18:44 UTC, mamaruo requested changes

2022-04-24 18:44 UTC, mamaruo commented on projects/1.16/assets/enderio-alloys/enderioalloys/lang/zh_cn
> +    "item.enderioalloys.item_alloy_ingot_energetic_silver": "脉冲银锭",
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/e0408ae0e59607ea5995363bb53e32657f4a65be/projects/1.12.2/assets/1UNKNOWN/enderio/lang/zh_cn.lang#L330

2022-04-24 18:45 UTC, mamaruo commented on projects/1.16/assets/enderio-alloys/enderioalloys/zh_cn.json
> +    "item.enderioalloys.item_alloy_ingot_electrical_steel": "磁钢锭",
https://github.com/SleepyTrousers/EnderIO/commit/5e724beaebd3202e065db848892ca6bb10823e91
最开始其实是正确的。
我只能说，我佛了

2022-04-24 18:50 UTC, n0099 approved these changes

2022-04-24 18:56 UTC, mamaruo commented on projects/1.16/assets/enderio-alloys/enderioalloys/lang/zh_cn
> +    "item.enderioalloys.item_alloy_ingot_construction_alloy": "铁合金锭",
construction alloy 又是怎么翻成铁合金的
我的译名草案没涉及到这个东西，所以之前看漏了

2022-04-24 19:00 UTC, mamaruo commented on projects/1.16/assets/enderio-alloys/enderioalloys/lang/zh_cn
> +    "item.enderioalloys.item_alloy_ingot_construction_alloy": "铁合金锭",
<s>construction alloy 又是怎么翻成铁合金的</s> 
原来确实叫 Iron Alloy，现在改了，见
https://github.com/SleepyTrousers/EnderIO-Rewrite/blob/66822c355de322da7031e3a8bb8035255150d4e9/enderio-base/src/generated/resources/assets/enderio/lang/en_us.json#L330

2022-04-24 19:03 UTC, mamaruo approved these changes

2022-04-25 05:01 UTC, Cyl18 commented on projects/1.16/assets/enderio-alloys/enderioalloys/lang/zh_cn.json
> +    "itemGroup.enderioalloys": "末影接口丨合金"
```suggestion
    "itemGroup.enderioalloys": "末影接口丨合金",
```

2022-04-25 15:02 UTC, n0099 approved these changes

2022-04-27 02:32 UTC, mamaruo commented
没什么问题我就合了

2022-04-27 12:22 UTC, merged