[R] manaita-plus 翻译提交 来自工单#CFPA-0643
CFPAOrg/Minecraft-Mod-Language-Package pull request #1881
Opened 2022-04-22 16:56 UTC by mamaruo

Co-Authored-By: RuiXuqi <90179819+RuiXuqi@users.noreply.github.com>

原工单备注：咸鱼模组一带的汉化一直都挺混乱的，看到了就顺手改改吧。。。有几处地方是tooltip，改了下更贴合点

- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-04-22 17:02 UTC, n0099 requested changes

2022-04-22 17:02 UTC, n0099 commented on projects/1.12.2/assets/manaita-plus/manaita_plus/lang/zh_cn.lang
> +key.always_brewing_manaita=凭空打开砧板酿造台
```suggestion
key.always_crafting_manaita=一键打开砧板工作台
key.always_furnace_manaita=一键打开砧板熔炉
key.always_brewing_manaita=一键打开砧板酿造台
```

2022-04-22 17:02 UTC, n0099 commented on projects/1.12.2/assets/manaita-plus/manaita_plus/lang/zh_cn.lang
> +advancements.full_of_diamond.desc=物品栏里满是钻石！（裸着而且很高兴）
？

2022-04-23 09:08 UTC, n0099 commented
建议改成`xx制`

2022-04-24 07:58 UTC, TartaricAcid approved these changes

2022-04-24 11:32 UTC, n0099 approved these changes

2022-04-24 11:32 UTC, merged