[R] AgriCraft 1.16 汉化添加(修正版)
CFPAOrg/Minecraft-Mod-Language-Package pull request #1904
Opened 2022-04-27 13:09 UTC by fenglbl

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-04-27 13:42 UTC, n0099 commented
#1899

2022-04-28 11:12 UTC, Cyl18 commented
请删除.DS_Store

2022-05-07 13:22 UTC, mamaruo requested changes

2022-05-07 13:22 UTC, mamaruo commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "block.agricraft.grate": "木格栅",
应使用木制、铁制等或不用zhi。
1.12译名木质浇灌水道
  "block.agricraft.crop_sticks_wood": "木质作物架",
  原文没有 Wooden，建议遵循原文

2022-05-07 13:22 UTC, mamaruo commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "item.agricraft.debugger": "漏洞测试器",
```suggestion
  "item.agricraft.debugger": "调试器",
```

2022-05-07 13:22 UTC, mamaruo commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "item.agricraft.agri_journal": "农业研究笔记",
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/86b0f46d74ec5042118ac261e960e80b669ffa19/projects/1.12.2/assets/agricraft/agricraft/lang/zh_cn.lang#L80

2022-05-07 13:22 UTC, mamaruo commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "item.agricraft.agri_seed_bag": "精确的（？）的种子分类袋",
？

2022-05-07 13:24 UTC, mamaruo requested changes
请自行检查与 [1.12 汉化](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/projects/1.12.2/assets/agricraft/agricraft/lang/zh_cn.lang) 的差异，若有更改的请列出并说明更改理由。

2022-05-07 18:28 UTC, mamaruo commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "agricraft.plant.niccissus.desc": "虽然关于哪种植物最好还有很多争论，我们都认同镍粉藤是最自私的植物。",
```suggestion
  "agricraft.plant.niccissus.desc": "虽然关于哪种植物最适合“自私”的称号还有很多争论，但直到现在，我们都认同镍水仙是最自私的。",
```
  "agricraft.plant.niccissus.desc": "While there is much debate over which is the best plant, we can all agree that the Niccissus plant is by far the most self-absorbed.",

2022-05-07 18:28 UTC, mamaruo commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "agricraft.plant.nitorwart.seed": "闪耀犹孢子",
```suggestion
  "agricraft.plant.nitorwart.name": "闪耀疣",
  "agricraft.plant.nitorwart.seed": "闪耀疣孢子",
```
Nitor Wart，产荧石

2022-05-07 18:28 UTC, mamaruo commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "agricraft.plant.mysticalagriculture.hop_graphite": "HOP石墨种子",
```suggestion
  "agricraft.plant.mysticalagriculture.hop_graphite": "高定向热解石墨种子",
```
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/2038b5fdd9bf8fa831d950cce1a765fc18f9b008/projects/1.16/assets/immersive-engineering/immersiveengineering/lang/zh_cn.json#L1018-L1019

2022-05-07 18:28 UTC, mamaruo commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "agricraft.tooltip.growth_req.season.general": "这种植物不能在当前的季节中生长",
```suggestion
  "agricraft.tooltip.growth_req.fluid.general": "这种植物不能在当前的流体中生长",
```

2022-05-07 18:28 UTC, mamaruo commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "agricraft.message.trowel_weed": "我无法提升到好的水平，我应该先除杂草。",
怪怪的
  "agricraft.message.trowel_weed": "I can not reach well, I should remove the weeds first.",

2022-05-07 18:28 UTC, mamaruo commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "item.agricraft.agri_nugget_emerald": "绿宝石粒",
```suggestion
  "item.agricraft.agri_nugget_diamond": "钻石粒",
  "item.agricraft.agri_nugget_emerald": "绿宝石粒",
```
原文Shard
但key里写的nugget，奇怪

2022-05-08 02:31 UTC, n0099 commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "agricraft.tooltip.humidity.flooded": "涝灾",
快进到1.13 waterlogging

2022-05-08 07:40 UTC, mamaruo commented
我只能说我review了半天（约5个小时）你这给关了很搞我心态
要修正不能在PR基础上修吗

2022-05-08 08:05 UTC, AnzhiZhang commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "agricraft.tooltip.humidity.flooded": "涝灾",
个人想法，改成通俗易懂的 `淹了`，还能精准表达被动语态
```suggestion
  "agricraft.tooltip.humidity.flooded": "淹了",
```

2022-05-08 08:28 UTC, mamaruo reviewed
**仅供参考**

| **矿石植物名** | **矿石植物译名1** | **矿石植物译名2** | **来源植物原名** | **来源矿物原名** | **来源植物译名** | **种植产物** |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| Aurigold | 金光花 |  | marigold | aurum | 金盏花 | 金 |
| Carbonation | 碳石竹 |  | carnation | carbon | 青石竹 | 煤炭 |
| Cuprosia | ？ |  | ？ | cuprum | ？ | 铜 |
| Diamahlia | 金刚大丽 | 钻石大丽 | dahlia | diamond | 大丽 | 钻石 |
| Emeryllis | 翠顶绿 |  | amaryllis | emerald | 朱顶红 | 绿宝石 |
| Ferranium | 天竺铁 |  | geranium | ferrum | 天竺葵 | 铁 |
| Jaslumine | 茉莒 | 铝茉莉 | jasmine | aluminium | 茉莉 | 铝 |
| Lapender | 薰衣青 | 青金薰衣草 | lavender | lapis | 薰衣草 | 青金石 |
| Niccissus | 镍水仙 |  | narcissus | nickel | 水仙 | 镍 |
| Nitor_Wart | 荧火疣？ | 闪耀疣 | nitro? | nitre? | 火？ | 荧石 |
| Osmonium | 补锇草 |  | limonium | osmium | 补血草 | 锇 |
| Petinia | 锡冬茄 |  | petunia | tin | 矮牵牛 | 锡 |
| Platiolus | 铂菖蒲 |  | gladiolus | platinum | 唐菖蒲 | 铂 |
| Plombean | 铅豆？／铅牛花？ |  | blooming_bean?/ipomoea? | plumbum | 绽放豆？／番薯？ | 铅 |
| Quartzanthemum | 石英菊 |  | chrysanthemum | quartz | 菊花 | 石英 |
| Redstodendron | 蔓红绒 |  | philodendron | redstone | 蔓绿绒 | 红石 |

2022-05-08 09:33 UTC, Cyl18 commented
另：#1868 #1899 请不要一直关闭PR

2022-05-08 10:09 UTC, mamaruo commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "agricraft.plant.jaslumine.desc": "茉莉赠予人，茉莉随我身。灼灼如银华，草木意深深。",
```suggestion
  "agricraft.plant.jaslumine.desc": "彼之茉莉，吾之茉莒。光耀如银，比之翠植更似金玉。",
```

2022-05-08 10:24 UTC, fenglbl commented
好的

2022-05-08 10:47 UTC, fenglbl commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "item.agricraft.agri_nugget_emerald": "绿宝石粒",
那就按Shard翻译吧

2022-05-08 10:52 UTC, fenglbl commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "agricraft.message.trowel_weed": "我无法提升到好的水平，我应该先除杂草。",
百度翻译是：我够不着井，我应该先除草。

2022-05-08 11:07 UTC, fenglbl commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "block.agricraft.grate": "木格栅",
有争议，去掉质，直接“木作物架”，“铁作物架”，这样？

2022-05-08 11:08 UTC, fenglbl commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "item.agricraft.agri_seed_bag": "精确的（？）的种子分类袋",
这是怎么了

2022-05-08 12:18 UTC, AnzhiZhang commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "block.agricraft.grate": "木格栅",
CFPA已同意，使用木制
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1528#issuecomment-1034408861

2022-05-08 13:43 UTC, n0099 commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "agricraft.message.trowel_weed": "我无法提升到好的水平，我应该先除杂草。",
well一眼副词
没有上下文的话只能理解为“我无法达到”

2022-05-08 13:46 UTC, n0099 commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "agricraft.journal.growth_reqs.nutrients.desc": "有些土壤含有比其他土壤更多的养分。",
疑似1984 ref

2022-05-08 13:47 UTC, n0099 commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "agricraft.plant.bluet.desc": "窈窕淑女，君子好逑。",
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1958#discussion_r867446420

2022-05-08 13:47 UTC, n0099 commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "agricraft.plant.melon.desc": "甜美\u0026多汁。",
```suggestion
  "agricraft.plant.melon.desc": "甜美&多汁。",
```

2022-05-08 13:52 UTC, n0099 commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "agricraft.plant.sea_grass.desc": "草，3000年前的草啊。",
草（中日双语）

2022-05-08 15:41 UTC, mamaruo commented
> 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；

QQ群中有昵称为“哒！哒！哒！”（QQ号15******25）的人以 @fenglbl 的语气解释此 PR 的作者是 @LiuQiYu671，@fenglbl 是来代交的。可是你不署名是怎么回事。要不是#1868可以按剽窃算。

我疑惑为什么 @LiuQiYu671 不来自己PR，另外 @LiuQiYu671 麻烦来看下 review。另外，长文本[翻译腔](https://zh.wikipedia.org/wiki/Wikipedia:%E7%BF%BB%E8%AF%91%E8%85%94)略重。我还没有review完。

2022-05-08 16:13 UTC, n0099 commented
> QQ群中有昵称为“哒！哒！哒！”（QQ号15******25）的人以 @fenglbl 的语气解释此 PR 的作者是 @LiuQiYu671，@fenglbl 是来代交的。可是你不署名是怎么回事。要不是 #1868 这个 PR 可以按剽窃算。

而我早已被驱逐出cfpa群，令人感叹

2022-06-07 20:00 UTC, mamaruo commented on projects/1.16/assets/agricraft/agricraft/lang/zh_cn.json
> +  "item.agricraft.agri_seed_bag": "精确的（？）的种子分类袋",
为什么多了问号

2022-06-25 18:01 UTC, mamaruo commented
/diff

2022-08-13 13:40 UTC, merged