[R] Intotheomega等共5个模组翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1910
Opened 2022-04-29 11:10 UTC by XiaoXin1113

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-04-29 12:30 UTC, mamaruo requested changes

2022-04-29 12:30 UTC, mamaruo commented on projects/1.16/assets/into-the-omega/intotheomega/lang/zh_cn.json
> +  "item.intotheomega.omega_shovel": "Omega铲",
```suggestion
  "item.intotheomega.omega_shovel": "Omega锹",
```
原 版 译 名 ！

2022-04-29 12:30 UTC, mamaruo commented on projects/1.16/assets/into-the-omega/intotheomega/lang/zh_cn.json
> +  "item.wolveswitharmor.omega_wolf_armor": "§dOmega狼盔甲",
```suggestion
  "item.wolveswitharmor.omega_wolf_armor": "§dOmega狼铠",
```
https://github.com/Draylar/wolves-with-armor/blob/1378a06b4e804ea57654920e74585e388cd2737d/src/main/resources/assets/wolveswitharmor/lang/zh_cn.json#L2

2022-04-29 13:10 UTC, n0099 approved these changes

2022-04-29 13:14 UTC, n0099 commented on projects/1.16/assets/long-fall-boots/longfallboots/lang/zh_cn.json
> +  "item.longfallboots.longfallboots": "掉落长靴"
建议去portal2游戏中找valve钦定译名

2022-04-29 17:55 UTC, mamaruo commented on projects/1.16/assets/long-fall-boots/longfallboots/lang/zh_cn.json
> +  "item.longfallboots.longfallboots": "掉落长靴"
有没有知道这玩意在什么时候出场的，看实况视频也可以

2022-04-29 19:03 UTC, n0099 commented on projects/1.16/assets/long-fall-boots/longfallboots/lang/zh_cn.json
> +  "item.longfallboots.longfallboots": "掉落长靴"
https://www.reddit.com/r/Portal/comments/mwhctm/do_we_know_how_chell_got_the_long_fall_boots_most/

2022-04-29 19:05 UTC, n0099 commented on projects/1.16/assets/long-fall-boots/longfallboots/lang/zh_cn.json
> +  "item.longfallboots.longfallboots": "掉落长靴"
https://www.bilibili.com/video/av93639961?p=9

2022-04-30 06:00 UTC, Cyl18 commented on projects/1.16/assets/long-fall-boots/longfallboots/lang/zh_cn.json
> +  "item.longfallboots.longfallboots": "掉落长靴"
![image](https://user-images.githubusercontent.com/14993992/166093662-4b7adff9-f04e-4813-b49e-ae931976d705.png)

2022-04-30 13:38 UTC, TartaricAcid commented on projects/1.16/assets/into-the-omega/intotheomega/lang/zh_cn.json
> +}
我建议把所有的 `Omega` 翻译成 `Ω` 或者直接音译，这块直接有标准的音译表可参考。
![Uploading image.png…]()

2022-04-30 19:09 UTC, n0099 commented on projects/1.16/assets/into-the-omega/intotheomega/lang/zh_cn.json
> +}
xi

2022-05-08 05:22 UTC, mamaruo commented on projects/1.16/assets/into-the-omega/intotheomega/lang/zh_cn.json
> +}
我比较疑惑为什么[奥密克戎（新冠病毒新变异株）_百度百科](https://baike.baidu.com/item/%E5%A5%A5%E5%AF%86%E5%85%8B%E6%88%8E/59308513?fr=aladdin)没有采用此表规范

2022-06-06 06:32 UTC, n0099 approved these changes

2022-06-06 06:32 UTC, n0099 commented on projects/1.16/assets/into-the-omega/intotheomega/lang/zh_cn.json
> +  "block.intotheomega.omega_block": "Omega块"
替换为Ω：
```suggestion
  "item.intotheomega.omega_crystal": "Ω水晶",
  "item.intotheomega.omega_enchanted_book": "附魔书",
  "item.intotheomega.omega_sword": "Ω剑",
  "item.intotheomega.omega_pickaxe": "Ω镐",
  "item.intotheomega.omega_hoe": "Ω锄",
  "item.intotheomega.omega_shovel": "Ω锹",
  "item.intotheomega.omega_axe": "Ω斧",
  "item.intotheomega.omega_helmet": "Ω头盔",
  "item.intotheomega.omega_chestplate": "Ω胸甲",
  "item.intotheomega.omega_leggings": "Ω护腿",
  "item.intotheomega.omega_boots": "Ω靴子",
  "item.wolveswitharmor.omega_wolf_armor": "§dΩ狼铠",
  "block.intotheomega.omega_crystal_ore": "Ω水晶矿石",
  "block.intotheomega.conquest_forge": "征服锻造台",
  "block.intotheomega.omega_block": "Ω块"
```
替换为奥米伽：
```suggestion
  "item.intotheomega.omega_crystal": "奥米伽水晶",
  "item.intotheomega.omega_enchanted_book": "附魔书",
  "item.intotheomega.omega_sword": "奥米伽剑",
  "item.intotheomega.omega_pickaxe": "奥米伽镐",
  "item.intotheomega.omega_hoe": "奥米伽锄",
  "item.intotheomega.omega_shovel": "奥米伽锹",
  "item.intotheomega.omega_axe": "奥米伽斧",
  "item.intotheomega.omega_helmet": "奥米伽头盔",
  "item.intotheomega.omega_chestplate": "奥米伽胸甲",
  "item.intotheomega.omega_leggings": "奥米伽护腿",
  "item.intotheomega.omega_boots": "奥米伽靴子",
  "item.wolveswitharmor.omega_wolf_armor": "§d奥米伽狼铠",
  "block.intotheomega.omega_crystal_ore": "奥米伽水晶矿石",
  "block.intotheomega.conquest_forge": "征服锻造台",
  "block.intotheomega.omega_block": "奥米伽块"
```
替换为欧米伽：
```suggestion
  "item.intotheomega.omega_crystal": "欧米伽水晶",
  "item.intotheomega.omega_enchanted_book": "附魔书",
  "item.intotheomega.omega_sword": "欧米伽剑",
  "item.intotheomega.omega_pickaxe": "欧米伽镐",
  "item.intotheomega.omega_hoe": "欧米伽锄",
  "item.intotheomega.omega_shovel": "欧米伽锹",
  "item.intotheomega.omega_axe": "欧米伽斧",
  "item.intotheomega.omega_helmet": "欧米伽头盔",
  "item.intotheomega.omega_chestplate": "欧米伽胸甲",
  "item.intotheomega.omega_leggings": "欧米伽护腿",
  "item.intotheomega.omega_boots": "欧米伽靴子",
  "item.wolveswitharmor.omega_wolf_armor": "§d欧米伽狼铠",
  "block.intotheomega.omega_crystal_ore": "欧米伽水晶矿石",
  "block.intotheomega.conquest_forge": "征服锻造台",
  "block.intotheomega.omega_block": "欧米伽块"
```

2022-06-06 11:34 UTC, mamaruo commented on projects/1.16/assets/into-the-omega/intotheomega/lang/zh_cn.json
> +  "block.intotheomega.omega_block": "Omega块"
由于奥密克戎变异株采用的音译法符合《中学数学用表》（1983年版，2019年印刷），采用欧米茄

2022-06-06 11:34 UTC, mamaruo approved these changes

2022-06-06 12:03 UTC, merged