[R]Tips 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1916
Opened 2022-05-01 07:21 UTC by AnzhiZhang

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-01 16:23 UTC, n0099 requested changes

2022-05-01 16:23 UTC, n0099 commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.poison_immune": "僵尸、骷髅和蜘蛛免疫中毒药水。",
```suggestion
  "tips.tip.poison_immune": "僵尸、骷髅和蜘蛛免疫剧毒药水。",
```

2022-05-01 16:23 UTC, n0099 commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.dog_health": "狼的尾巴越低，它们剩下的血量就越少。",
```suggestion
  "tips.tip.dog_health": "狼的尾巴越低，它的剩余血量就越少。",
```

2022-05-01 16:23 UTC, n0099 commented on projects/1.18/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.poison_immune": "僵尸、骷髅和蜘蛛免疫中毒药水。",
```suggestion
  "tips.tip.poison_immune": "僵尸、骷髅和蜘蛛免疫剧毒药水。",
```

2022-05-01 16:23 UTC, n0099 commented on projects/1.18/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.dog_health": "狼的尾巴越低，它们剩下的血量就越少。",
```suggestion
  "tips.tip.dog_health": "狼的尾巴越低，它的剩余血量就越少。",
```

2022-05-01 18:14 UTC, n0099 approved these changes

2022-05-02 04:39 UTC, Rinko1231 reviewed
语序有点怪

2022-05-02 04:39 UTC, Rinko1231 commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.wooden_tool_fuel": "不再使用的木制工具能够为熔炉燃料使用。",
```suggestion
  "tips.tip.wooden_tool_fuel": "不再使用的木制工具能够作为熔炉燃料使用。",
```

2022-05-02 04:39 UTC, Rinko1231 commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.lure_animals": "你可以在主手/副手拿上动物喜欢食物来引诱动物跟随你。",
```suggestion
  "tips.tip.lure_animals": "你可以在主手/副手拿上动物喜欢的食物来引诱动物跟随你。",
```

2022-05-02 04:39 UTC, Rinko1231 commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.cooked_drops": "燃烧死亡的动物有时会掉落熟肉。",
```suggestion
  "tips.tip.cooked_drops": "因火焰伤害而死的动物有时会掉落熟食。",
```
原文`Animals killed by fire damage will sometimes drop cooked food.`

2022-05-02 04:39 UTC, Rinko1231 commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.note_block_instrument": "一个音符块的播放的乐器是由它下方的方块决定的。",
```suggestion
  "tips.tip.note_block_instrument": "一个音符盒播放的乐器是由它下方的方块决定的。",
```

2022-05-02 04:39 UTC, Rinko1231 commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.villager_sweat": "村民在突袭中试图与他们交易时会出汗（粒子）。",
```suggestion
  "tips.tip.villager_sweat": "在突袭中试图与村民交易时他们会出汗（粒子）。",
```

2022-05-02 04:39 UTC, Rinko1231 commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.coarse_to_dirt": "砂土可以使用锄头转化为普通泥土。",
```suggestion
  "tips.tip.coarse_to_dirt": "砂土可以用锄头来转化为普通泥土。",
```

2022-05-02 04:39 UTC, Rinko1231 commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.portal_trick": "通过使用水桶和熔岩桶，你可以制作一个简单的下界传送门。",
```suggestion
  "tips.tip.portal_trick": "通过使用水桶和熔岩桶，你可以轻松建造一个下界传送门。",
```
这里的easy是表示“建造此下界门很方便很轻松（不用镐子挖半天）”。

2022-05-02 07:21 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.villager_sweat": "村民在突袭中试图与他们交易时会出汗（粒子）。",
应当为`在袭击中`，参考[袭击](https://minecraft.fandom.com/zh/wiki/%E8%A2%AD%E5%87%BB?variant=zh)

2022-05-03 11:01 UTC, mamaruo commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "gui.tips.list.entry.copied": "收到！",
```suggestion
  "gui.tips.list.entry.copied": "已复制！",
```
原文`Copied!`
收到一般说 copy that
下一行是
`"gui.tips.list.entry.click_to_copy": "单击以复制ID",`

2022-05-03 11:15 UTC, mamaruo commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.undead_damage": "像骷髅这样的亡灵生物会被治疗药水伤害，会被伤害药水治疗。",
```suggestion
  "tips.tip.undead_damage": "像骷髅这样的亡灵生物会被治疗药水伤害，被伤害药水治疗。",
```

2022-05-03 11:15 UTC, mamaruo commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.poison_immune": "僵尸、骷髅和蜘蛛免疫剧毒药水。",
**Zombies, Skeletons, and Spiders are all immune to poison damage.**
药水不知道哪翻出来的，译后编辑直接不看原文？
```suggestion
  "tips.tip.poison_immune": "僵尸、骷髅和蜘蛛都免疫中毒",
```
```suggestion
  "tips.tip.poison_immune": "僵尸、骷髅和蜘蛛都免疫中毒的伤害",
```
```suggestion
  "tips.tip.poison_immune": "僵尸、骷髅和蜘蛛都免疫中毒效果的伤害",
```
```suggestion
  "tips.tip.poison_immune": "僵尸、骷髅和蜘蛛都免疫中毒效果带来的伤害",
```

2022-05-03 11:15 UTC, mamaruo commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.nether_lava": "熔岩在下界的流动速度会更快。",
```suggestion
  "tips.tip.nether_lava": "熔岩在下界的流动速度更快。",
```

2022-05-03 11:15 UTC, mamaruo commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.deflect_ghast_fireballs": "你能够通过攻击恶魂发出的火焰弹来改变它的运动方向。",
```suggestion
  "tips.tip.deflect_ghast_fireballs": "攻击恶魂火球可以改变它的运动方向。",
```
[恶魂/火球 - Minecraft Wiki，最详细的我的世界百科](https://minecraft.fandom.com/zh/wiki/%E6%81%B6%E9%AD%82?so=search#.E7.81.AB.E7.90.83)

2022-05-03 13:14 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.nether_lava": "熔岩在下界的流动速度会更快。",
```suggestion
  "tips.tip.nether_lava": "熔岩在下界流动得更快。",
```

2022-05-03 14:04 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.string_wool": "4个线可以合成羊毛。",
```suggestion
  "tips.tip.string_wool": "线以2x2的形状可以合成羊毛。",
```

2022-05-03 14:23 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.barrel": "木桶比箱子更划算，它比箱子少用一个木板，同时可以无限地放在一起。",
```suggestion
  "tips.tip.barrel": "木桶比箱子更好，它不需要头顶预留一个方块的空间，同时可以无限地放在一起。",
```

2022-05-03 14:24 UTC, Cyl18 commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.barrel": "木桶比箱子更划算，它比箱子少用一个木板，同时可以无限地放在一起。",
参考了一下其它语言文件
![image](https://user-images.githubusercontent.com/14993992/166472001-548150f0-aa20-4af8-b15d-cbf412147829.png)

2022-05-03 14:26 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.barrel": "木桶比箱子更划算，它比箱子少用一个木板，同时可以无限地放在一起。",
参考：[官方维基](https://minecraft.fandom.com/zh/wiki/%E6%9C%A8%E6%A1%B6?variant=zh)
![image](https://user-images.githubusercontent.com/37402126/166472282-05032563-e129-411f-b7a4-043a32aeed1c.png)

2022-05-03 14:26 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.barrel": "木桶比箱子更划算，它比箱子少用一个木板，同时可以无限地放在一起。",
```suggestion
  "tips.tip.barrel": "木桶比箱子更好，它不需要预留顶部空间，同时可以无限地放在一起。",
```

2022-05-03 19:02 UTC, mamaruo commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.barrel": "木桶比箱子更划算，它比箱子少用一个木板，同时可以无限地放在一起。",
```suggestion
  "tips.tip.barrel": "木桶比箱子更好，它不需要在顶部预留一个方块空间，同时可以不受限地毗邻放置。",
```
另外吹毛求疵：Minecraft Wiki 不是官方 Wiki ，前些日子被微软[解约](https://card.weibo.com/article/m/show/id/2309404688987645411518)了。

2022-05-03 21:55 UTC, n0099 commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.blaze_fuel": "烈焰棒是熔炉的好燃料。",
高炉不能烧？

2022-05-03 21:56 UTC, n0099 commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.barrel": "木桶比箱子更划算，它比箱子少用一个木板，同时可以无限地放在一起。",
至少以前是

2022-05-04 00:58 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.blaze_fuel": "烈焰棒是熔炉的好燃料。",
对炉子来说，烈焰棒是一种不错的燃料。
有点奇怪，说熔炉应该可以通用理解吧

2022-05-04 22:06 UTC, n0099 commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.blaze_fuel": "烈焰棒是熔炉的好燃料。",
高炉不是熔炉？

2022-05-04 22:06 UTC, n0099 approved these changes

2022-05-05 15:03 UTC, mamaruo commented
别合，我还没审完

2022-05-05 15:29 UTC, Cyl18 commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.note_block_instrument": "一个音符盒播放的乐器是由它下方的方块决定的。",
```suggestion
  "tips.tip.note_block_instrument": "音符盒放出的乐器声取决于音符盒下方的方块材料。",
```

2022-05-05 15:29 UTC, Cyl18 commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.undead_helmet": "带着头盔的亡灵生物在白天不会燃烧。",
```suggestion
  "tips.tip.undead_helmet": "戴着头盔的亡灵生物在白天不会燃烧。",
```

2022-05-05 15:43 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.note_block_instrument": "一个音符盒播放的乐器是由它下方的方块决定的。",
```suggestion
  "tips.tip.note_block_instrument": "音符盒放出的乐器声取决于音符盒下方的方块。",
```

2022-05-05 15:47 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.fortress_triangulation": "你可以通过从两个不同的位置使用末影之眼并通过对要塞位置进行三角定位来寻找它们相交的位置。",
```suggestion
  "tips.tip.fortress_triangulation": "你可以在两个不同的位置使用末影之眼来三角定位要塞位置。",
```

2022-05-05 16:05 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.dog_rotten_flesh": "你可以通过喂狼吃腐肉来恢复它的血量。",
来自MC Wiki
![image](https://user-images.githubusercontent.com/37402126/166965176-db9ebbb0-5068-4e09-9a44-b6d32a56952f.png)
```suggestion
  "tips.tip.dog_rotten_flesh": "你可以通过喂狼吃腐肉来治疗它。",
```

2022-05-05 16:07 UTC, mamaruo commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.zombie_armor": "即使僵尸没有穿戴任何护甲，他们也拥有两点基础护甲值。",
```suggestion
  "tips.tip.zombie_armor": "即使僵尸没有穿戴任何盔甲，他们也拥有两点基础护甲值。",
```
为何一个armor两译？
清秋：护甲值包括马铠提供的，马铠不是盔甲，盔甲就是盔甲。

2022-05-05 16:10 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.creeper_cat": "苦力怕害怕猫，如果太靠近猫会逃跑。",
```suggestion
  "tips.tip.creeper_cat": "苦力怕害怕猫，如果太靠近猫，苦力怕会逃跑。",
```

2022-05-05 16:12 UTC, mamaruo commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.boat_passenger": "船只能承载两人。",
原文carry，故此译

2022-05-05 16:12 UTC, AnzhiZhang commented
有些觉得可以就直接commit resolve吧，处理完之后1.18也需要更新，别直接合并

2022-05-05 16:17 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.zombie_armor": "即使僵尸没有穿戴任何护甲，它们也拥有两点基础护甲值。",
![image](https://user-images.githubusercontent.com/37402126/166967384-9f2fe9a3-0cb8-4d25-84d2-1546a9a7bd2f.png)
![image](https://user-images.githubusercontent.com/37402126/166967419-91edf781-52e7-4e53-ab3d-1ebd1ed3e62c.png)
```suggestion
  "tips.tip.zombie_armor": "即使僵尸没有穿戴任何盔甲，他们也拥有两点基础盔甲值。",
```

2022-05-05 16:19 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.zombie_armor": "即使僵尸没有穿戴任何护甲，它们也拥有两点基础护甲值。",
连mc wiki的翻译都是混乱的
![image](https://user-images.githubusercontent.com/37402126/166967832-6dd51a5c-8104-4768-b0df-9bdde2cd1af1.png)

2022-05-05 16:36 UTC, mamaruo reviewed
review 完毕

2022-05-05 16:36 UTC, mamaruo commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.gravity_torch": "如果你手速够快，可以通过放火把在受重力影响的方块下面来破坏一串的这些方块。",
If you quickly put a torch under blocks affected by gravity, they will break in chain.
```suggestion
  "tips.tip.gravity_torch": "如果你迅速把火把插到受重力影响的方块下方，你就会看到它们接连被破坏。",
```
```suggestion
  "tips.tip.gravity_torch": "如果你迅速把火把插到受重力影响的方块下方，它们会被接火把连破坏。",
```

2022-05-05 16:36 UTC, mamaruo commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.villager_sweat": "在袭击时试图与村民交易，他们会出汗。",
```suggestion
  "tips.tip.villager_sweat": "在袭击时试图与村民交易，它们会冒汗。",
```
[Minecraft Wiki:书面汉语指导 - Minecraft Wiki，最详细的我的世界百科](https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:%E4%B9%A6%E9%9D%A2%E6%B1%89%E8%AF%AD%E6%8C%87%E5%AF%BC#.E4.BA.BA.E7.A7.B0.E4.BB.A3.E8.AF.8D.E7.9A.84.E9.80.89.E6.8B.A9)

2022-05-05 16:36 UTC, mamaruo commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.fortress_triangulation": "你可以通过从两个不同的位置使用末影之眼并通过对要塞位置进行三角定位来寻找它们相交的位置。",
"tips.tip.fortress_triangulation": "You can triangulate stronghold locations by summoning eyes of ender from two different locations and tracking where they intersect.",
```suggestion
  "tips.tip.fortress_triangulation": "你可以通过从两个不同的位置使用末影之眼并通过对要塞位置进行三角定位来寻找它们相交的位置。",
```

2022-05-05 16:36 UTC, mamaruo commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.bed_explode": "试图在其他维度睡觉会很糟糕。",
will end poorly.
```suggestion
  "tips.tip.bed_explode": "试图在其他维度睡觉会不会有好下场。",
```

2022-05-05 16:36 UTC, mamaruo commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.fall_damage_blocks": "一些像水和干草块这样的方块可以减少摔落伤害。",
"tips.tip.fall_damage_blocks": "Some blocks like water and hay can reduce fall damage.",

```suggestion
  "tips.tip.fall_damage_blocks": "水、干草块等方块可以减少摔落伤害。",
```

2022-05-05 16:36 UTC, mamaruo commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.portal_trick": "通过使用水桶和熔岩桶，你可以轻松建造一个下界传送门。",
```suggestion
  "tips.tip.portal_trick": "使用水桶和熔岩桶，你可以轻松建造一个下界传送门。",
```
虽然原文有个 by，读着确实怪

2022-05-05 16:36 UTC, mamaruo commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.title.tip": "提示",
```suggestion
  "tips.title.tip": "小窍门",
```
不成熟的建议

2022-05-05 16:40 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.title.tip": "提示",
虽然内容有很多窍门，但是还是保持大家熟悉的 `a small piece of advice about sth practical 指点；实用的提示` 意思吧

2022-05-05 16:47 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.gravity_torch": "如果你手速够快，可以通过放火把在受重力影响的方块下面来破坏一串的这些方块。",
```suggestion
  "tips.tip.gravity_torch": "如果你迅速把火把插到受重力影响的方块下方，它们会被火把接连破坏。",
```

2022-05-05 16:54 UTC, mamaruo commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.zombie_armor": "即使僵尸没有穿戴任何护甲，它们也拥有两点基础护甲值。",
我认同清秋的观点，所以wiki我改了，四件套四个页面

2022-05-05 16:59 UTC, mamaruo commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.fortress_triangulation": "你可以通过从两个不同的位置使用末影之眼并通过对要塞位置进行三角定位来寻找它们相交的位置。",
```suggestion
  "tips.tip.fortress_triangulation": "你可以在两个不同的地方使用末影之眼，利用两次轨迹交点，用三角学求出要塞位置。",
```

2022-05-05 17:01 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.fortress_triangulation": "你可以通过从两个不同的位置使用末影之眼并通过对要塞位置进行三角定位来寻找它们相交的位置。",
triangulate是专业术语，译名三角测量 [Triangulation](https://en.wikipedia.org/wiki/Triangulation)

2022-05-05 17:04 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.zombie_armor": "即使僵尸没有穿戴任何护甲，它们也拥有两点基础护甲值。",
```suggestion
  "tips.tip.zombie_armor": "即使僵尸没有穿戴任何盔甲，他们也拥有两点基础护甲值。",
```

2022-05-05 17:12 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.fortress_triangulation": "你可以在两个不同的位置使用末影之眼来三角定位要塞。",
You can triangulate stronghold locations by summoning eyes of ender from two different locations and tracking where they intersect.
```suggestion
  "tips.tip.fortress_triangulation": "在两个不同的位置使用末影之眼，并跟踪计算它们的相交点，可以三角测量要塞位置。",
```

2022-05-05 18:15 UTC, Cyl18 commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.scrap_nuggets": "金制与铁制的工具、盔甲能够冶炼成粒",
```suggestion
  "tips.tip.scrap_nuggets": "金制与铁制的工具、盔甲能够冶炼成粒。",
```

2022-05-05 23:24 UTC, n0099 requested changes

2022-05-05 23:24 UTC, n0099 commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.dog_health": "狼的尾巴越低，它剩的生命值就越少。",
```suggestion
  "tips.tip.dog_health": "狼的尾巴越低，它剩余的生命值就越少。",
```

2022-05-05 23:24 UTC, n0099 commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.bed_explode": "试图在其他维度睡觉会不会有好下场。",
```suggestion
  "tips.tip.bed_explode": "试图在其他维度睡觉不会有好下场。",
```

2022-05-05 23:37 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.bed_explode": "试图在其他维度睡觉会不会有好下场。",
还多了个字。。

2022-05-05 23:46 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.scrap_nuggets": "金制与铁制的工具、盔甲能够冶炼成粒。",
![image](https://user-images.githubusercontent.com/37402126/167044416-44c74f6a-3688-4d5e-9f70-2c969230f8b3.png)
```suggestion
  "tips.tip.scrap_nuggets": "金质与铁质的工具和盔甲能够冶炼成粒。",
```

2022-05-05 23:46 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.lure_animals": "你可以在主手/副手拿上动物喜欢的食物来引诱动物跟随你。",
```suggestion
  "tips.tip.lure_animals": "你可以在主手或副手拿上动物喜欢的食物来引诱动物跟随你。",
```

2022-05-06 00:09 UTC, AnzhiZhang reviewed
改了一些细节和错别字，可以的话直接commit就行，我更新1.18

2022-05-06 00:09 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.swamp_slime": "史莱姆会在满月时的沼泽中生成。",
原文 `Slimes can spawn in swamps during a full moon.`
维基说不是必须满月
```suggestion
  "tips.tip.swamp_slime": "史莱姆可以在满月时的沼泽中生成。",
```

2022-05-06 00:09 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.wooden_tool_fuel": "不再使用的木制工具能够作为熔炉燃料使用。",
```suggestion
  "tips.tip.wooden_tool_fuel": "不再使用的木质工具能够作为熔炉燃料使用。",
```

2022-05-06 00:09 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.wandering_invis": "流浪商人在晚上喝隐形药水。",
```suggestion
  "tips.tip.wandering_invis": "流浪商人在晚上会喝隐形药水。",
```

2022-05-06 00:11 UTC, n0099 commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.wandering_invis": "流浪商人在晚上喝隐形药水。",
```suggestion
  "tips.tip.wandering_invis": "流浪商人会在晚上喝隐形药水。",
```

2022-05-06 00:13 UTC, AnzhiZhang commented
发现这个mod根本没有1.18，仓库里的1.18语言文件是1.16复制的吧

2022-05-06 00:14 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.swamp_slime": "史莱姆会在满月时的沼泽中生成。",
![image](https://user-images.githubusercontent.com/37402126/167046627-3f0fcc4a-1139-499a-9174-ef33acc4d1c2.png)

2022-05-06 00:57 UTC, n0099 commented
是

2022-05-06 01:35 UTC, mamaruo commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.wooden_tool_fuel": "不再使用的木制工具能够作为熔炉燃料使用。",
木制工具
虽然原版用的木质工具

2022-05-06 01:41 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.wooden_tool_fuel": "不再使用的木制工具能够作为熔炉燃料使用。",
这个质是材质的意思
![image](https://user-images.githubusercontent.com/37402126/167053011-b9e03d9f-6361-429e-8831-dcb07fd2c6ca.png)

2022-05-06 01:58 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.wooden_tool_fuel": "不再使用的木制工具能够作为熔炉燃料使用。",
如果木制，指的意思“木头制造的工具”，还是木头材质的
查了下词典，木制应该是不能作形容词使用的
![image](https://user-images.githubusercontent.com/37402126/167054388-c34dcdcb-ff73-40f8-abf6-d27061e6513a.png)

2022-05-06 02:00 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.wooden_tool_fuel": "不再使用的木制工具能够作为熔炉燃料使用。",
与这个相关的还有19行的那条

2022-05-06 03:47 UTC, n0099 approved these changes

2022-05-06 07:11 UTC, mamaruo commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.wooden_tool_fuel": "不再使用的木制工具能够作为熔炉燃料使用。",
关于用X制还是X质，CFPA 近期的一次讨论的共识是使用前者或不用 zhi，规避它，比如“钻石工具”。

在这次讨论前，CFPA前管理的共识基本也是这样，可以从 commit 记录中看出。

另见清秋观点：https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1528#issuecomment-1034408861

有待进一步讨论。

2022-05-06 07:32 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.wooden_tool_fuel": "不再使用的木制工具能够作为熔炉燃料使用。",
这次提交的`zhi工具`，不适用不用zhi的方式，查询了一下质的意思和用法
![image](https://user-images.githubusercontent.com/37402126/167085528-8be6d08e-f1a2-44aa-b225-233b5e0ce477.png)

2022-05-06 07:48 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.wooden_tool_fuel": "不再使用的木制工具能够作为熔炉燃料使用。",
我看了一下两个字的历史和说文解字解释
[说文解字](https://drive.google.com/file/d/144oI-Hpub9le4TMcommVv_N3ezwatO7x/view?usp=sharing)
## 制
卷四，刀部
![image](https://user-images.githubusercontent.com/37402126/167088555-90f100aa-6c57-4dc2-baa5-f35af36f92c6.png)
裁也。从 刀、从 未。未，物成，有滋味，可裁斷。一曰止也。𠝁，古文制如此。
## 质
卷六，贝部
![image](https://user-images.githubusercontent.com/37402126/167089330-068f88b2-2de7-4c3c-952a-b6954ad25d2b.png)
以物相贅。从貝，从斦。闕。
---
由此得知，质没有制造的意思，材质的意思是现代引申的，而制本意的制造是合适的。

2022-05-06 15:48 UTC, AnzhiZhang commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.wooden_tool_fuel": "不再使用的木制工具能够作为熔炉燃料使用。",
目前已修改为`制`，以上仅为原理解释

2022-05-06 15:52 UTC, mamaruo commented on projects/1.16/assets/tips/tips/lang/zh_cn.json
> +  "tips.tip.wooden_tool_fuel": "不再使用的木制工具能够作为熔炉燃料使用。",
一个简易论证：
[铁质_百度搜索](https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&ch=&tn=baidu&bar=&wd=%E9%93%81%E8%B4%A8&oq=%25E9%2593%2581%25E5%2588%25B6&rsv_pq=cd16319b0005db73&rsv_t=6adeJ5tTJ2lyuKc%2FLLPQHg5zzSvFLj4aqfyOUjxTrPumaaK9D21gtsvc7fI&rqlang=cn&rsv_enter=1&rsv_btype=t&rsv_dl=tb&inputT=1161)丨[铁质 - Google 搜索](https://www.google.com/search?q=%E9%93%81%E8%B4%A8&newwindow=1&sxsrf=ALiCzsbqYYqGT1_MsMuuve7juGGIISdGYw%3A1651852272777&ei=8EN1YrmPL8-R-Ab1zJSwDA&ved=0ahUKEwi5x8Kfncv3AhXPCN4KHXUmBcYQ4dUDCA4&uact=5&oq=%E9%93%81%E8%B4%A8&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEIAEMgUIABCABDIFCAAQgAQyBwgAEIAEEAwyBQgAEIAEMgUIABCABDIHCAAQgAQQDDIFCAAQgAQyBQgAEIAEMgUIABCABDoHCAAQRxCwAzoECCMQJzoFCC4QgAQ6CwguEIAEELEDEIMBOgsILhCABBDHARDRAzoICC4QgAQQ1AJKBAhBGABKBAhGGABQ4wNY3BJg1xNoAXABeACAAasBiAGSBZIBAzAuNJgBAKABAcgBCsABAQ&sclient=gws-wiz)
[铁制_百度搜索](https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&ch=&tn=baidu&bar=&wd=%E9%93%81%E5%88%B6)丨[铁制 - Google 搜索](https://www.google.com/search?q=%E9%93%81%E5%88%B6&newwindow=1&sxsrf=ALiCzsb-LWRj7iih81qJUDcx6g7pOV0hTQ%3A1651852264287&ei=6EN1YpKfEc7g-Abx5pmABw&ved=0ahUKEwiSs7ybncv3AhVOMN4KHXFzBnAQ4dUDCA4&uact=5&oq=%E9%93%81%E5%88%B6&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEOgQIABBHOgQIIxAnOhEILhCABBCxAxCDARDHARDRAzoLCAAQgAQQsQMQgwE6CAgAEIAEELEDOhEILhCABBCxAxDHARDRAxDUAjoLCC4QgAQQxwEQowI6CwguEIAEEMcBENEDOgUILhCABDoICC4QgAQQ1AI6CwguEIAEELEDEIMBOgUIABDLAToHCCMQ6gIQJ0oECEEYAEoECEYYAFDqFVirL2CsMGgHcAJ4AYABtAGIAbAKkgEDMC44mAEAoAEBsAEKyAEKwAEB&sclient=gws-wiz)

恕我实在不是很能看懂《说文解字》，而且我今天想摆烂。

2022-05-06 16:04 UTC, mamaruo approved these changes

2022-05-07 04:07 UTC, n0099 approved these changes

2022-05-07 04:09 UTC, merged