[R] （Draft，先别管）
CFPAOrg/Minecraft-Mod-Language-Package pull request #1918
Opened 2022-05-01 09:29 UTC by driver1748

- [X] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [X] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [X] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [X] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [X] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-01 16:17 UTC, n0099 requested changes

2022-05-01 16:17 UTC, n0099 commented on projects/1.18-fabric/assets/anvil-fix/anvil_fix/lang/zh_cn.json
> +  "text.autoconfig.anvil_fix.option.removeIncrementalRepairCost": "移除维修费用的递增",
```suggestion
  "text.autoconfig.anvil_fix.option.removeIncrementalRepairCost": "禁用递增的维修费用",
```
边际效益递减

2022-05-02 07:38 UTC, n0099 approved these changes

2022-05-02 07:43 UTC, Cyl18 commented on projects/1.18-fabric/assets/anvil-fix/anvil_fix/lang/zh_cn.json
> +  "text.autoconfig.anvil_fix.option.stopAnvilBreaking": "制止铁砧损毁"
why

2022-05-02 07:43 UTC, Cyl18 commented
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/projects/1.16-fabric/assets/anvil-fix/anvil_fix/lang/zh_cn.json

2022-05-03 20:13 UTC, mamaruo approved these changes

2022-05-03 22:12 UTC, merged