Create Animania Cats & Dogs
CFPAOrg/Minecraft-Mod-Language-Package pull request #1923
Opened 2022-05-02 14:57 UTC by GhostWinds

可能有一些翻译不正确，欢迎大家指正

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-02 16:22 UTC, GhostWinds commented
> 模组	🔗 链接	🎨 相关文件
> * [ ]  🔄 勾选这个复选框来强制刷新



> 模组	🔗 链接	🎨 相关文件
> * [ ]  🔄 勾选这个复选框来强制刷新
Animania Cats & Dogs
https://www.curseforge.com/minecraft/mc-mods/animania-cats-dogs

2022-05-02 18:34 UTC, Cyl18 commented
/mv "Animania Cats & Dogs" "1.12/assets/animania-cats-dogs/catsdogs/lang/zh_cn.lang"

2022-05-02 18:38 UTC, Cyl18 commented
/mv "Animania Cats & Dogs" "projects/1.12/assets/animania-cats-dogs/catsdogs/lang/zh_cn.lang"

2022-05-02 18:59 UTC, Cyl18 commented
/mv "./Animania Cats & Dogs" "projects/1.12.2/assets/animania-cats-dogs/catsdogs/lang/zh_cn.lang"

2022-05-02 19:09 UTC, Cyl18 commented
/mv "./Animania Cats & Dogs" "projects/1.12.2/assets/animania-cats-dogs/catsdogs/lang/zh_cn.lang"

2022-05-02 20:30 UTC, Cyl18 commented
/update-en animania-cats-dogs 1.12.2

2022-05-02 21:02 UTC, n0099 approved these changes

2022-05-03 08:38 UTC, mamaruo requested changes

2022-05-03 08:38 UTC, mamaruo commented on projects/1.12.2/assets/animania-cats-dogs/catsdogs/lang/zh_cn.lang
> +entity.animania:kitten_tabby.name=幼虎斑猫
> A male cat is called a tom or tomcat[29] (or a gib,[30] if neutered). An unspayed female is called a queen,[31] (or a molly,[32] if spayed), especially in a cat-breeding context. A juvenile cat is referred to as a kitten.

from [Cat - Wikipedia](https://en.wikipedia.org/wiki/Cat)

2022-05-03 21:51 UTC, n0099 commented on projects/1.12.2/assets/animania-cats-dogs/catsdogs/lang/zh_cn.lang
> +entity.animania:kitten_tabby.name=幼虎斑猫
那就给key带tom前缀的那些猫加个公-前缀

2022-05-07 18:57 UTC, mamaruo commented on projects/1.12.2/assets/animania-cats-dogs/catsdogs/lang/zh_cn.lang
> +manual.felids.general.1=所有猫科动物的行为方式都相似。它们攻击小鸡、豌豆鸡、青蛙、仓鼠、雪貂和刺猬等小动物。驯服的动物不会攻击。猫科动物在世界上自然繁殖。这些是它们的食物：
```suggestion
manual.felids.general.1=所有猫科动物的行为方式都相似。它们攻击小鸡、幼孔雀、青蛙、仓鼠、雪貂和刺猬等小动物。驯服的动物不会攻击。猫科动物在世界上自然繁殖。这些是它们的食物：
```
可这些动物哪来的，我没看到这模组加了 啊

2022-05-08 02:32 UTC, n0099 approved these changes

2022-05-08 02:32 UTC, n0099 commented on projects/1.12.2/assets/animania-cats-dogs/catsdogs/lang/zh_cn.lang
> +manual.felids.general.1=所有猫科动物的行为方式都相似。它们攻击小鸡、豌豆鸡、青蛙、仓鼠、雪貂和刺猬等小动物。驯服的动物不会攻击。猫科动物在世界上自然繁殖。这些是它们的食物：
原版有一部分

2022-07-10 18:01 UTC, mamaruo approved these changes

2022-07-10 18:02 UTC, mamaruo commented
/diff

2022-07-12 15:20 UTC, merged