Create [R]Lush Caves
CFPAOrg/Minecraft-Mod-Language-Package pull request #1926
Opened 2022-05-02 15:48 UTC by GhostWinds

可能一些不对，欢迎大家指正

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-02 19:16 UTC, Cyl18 commented
/mv "[R]Lush Caves" "projects/1.12/assets/glymworld-lush-caves/gwlushcaves/lang/zh_cn.lang"

2022-05-02 19:18 UTC, Cyl18 commented
/mv "projects/1.12/assets/glymworld-lush-caves/gwlushcaves/lang/zh_cn.lang" "projects/1.12.2/assets/glymworld-lush-caves/gwlushcaves/lang/zh_cn.lang"

2022-05-02 20:29 UTC, Cyl18 commented
/update-en glymworld-lush-caves 1.12.2

2022-05-02 21:04 UTC, n0099 approved these changes

2022-05-03 08:49 UTC, mamaruo requested changes
建议背熟[标准译名列表 - Minecraft Wiki，最详细的我的世界百科](https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96)

2022-05-03 08:49 UTC, mamaruo commented on projects/1.12.2/assets/glymworld-lush-caves/gwlushcaves/lang/zh_cn.lang
> +tile.mossblock.name=苔藓
block 呢

2022-05-03 08:49 UTC, mamaruo commented on projects/1.12.2/assets/glymworld-lush-caves/gwlushcaves/lang/zh_cn.lang
> +tile.mossslab.name=苔藓板
slab……原版译名
```suggestion
tile.mossslab.name=苔藓台阶
```

2022-05-03 08:49 UTC, mamaruo commented on projects/1.12.2/assets/glymworld-lush-caves/gwlushcaves/lang/zh_cn.lang
> +tile.bigdripleaf.name=大型垂低叶
```suggestion
tile.bigdripleaf.name=大型垂滴叶
```
原版译名

2022-05-03 08:49 UTC, mamaruo commented on projects/1.12.2/assets/glymworld-lush-caves/gwlushcaves/lang/zh_cn.lang
> +tile.dripleaf.name=小型垂低叶
```suggestion
tile.dripleaf.name=小型垂滴叶
```

2022-05-03 08:49 UTC, mamaruo commented on projects/1.12.2/assets/glymworld-lush-caves/gwlushcaves/lang/zh_cn.lang
> +tile.azaleaslab.name=杜鹃花板
slab

2022-05-03 08:52 UTC, GhostWinds commented on projects/1.12.2/assets/glymworld-lush-caves/gwlushcaves/lang/zh_cn.lang
> +tile.mossblock.name=苔藓
苔藓和苔藓块感觉也差不多，不过可以改

2022-05-03 09:38 UTC, mamaruo approved these changes

2022-05-03 21:53 UTC, merged