[R]Xaero's World Map
CFPAOrg/Minecraft-Mod-Language-Package pull request #1927
Opened 2022-05-02 15:55 UTC by GhostWinds

可能一些不对，欢迎指正

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-02 19:40 UTC, Cyl18 commented
/mv "zh_CN.lang" "projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang"

2022-05-02 21:08 UTC, n0099 requested changes

2022-05-02 21:08 UTC, n0099 commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_requires_reload=需要重新加载才能生效! 较低=更好的性能.
```suggestion
gui.xaero_requires_reload=需要重新加载才能生效! 较低=更好的性能。
```

2022-05-02 21:08 UTC, n0099 commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_map_unconfirmed=世界地图需要确认!
```suggestion
gui.xaero_map_zoom_in=放大 (替代）
gui.xaero_map_zoom_out=缩小 (替代）
gui.xaero_map_unconfirmed=世界地图需要确认！
```

2022-05-02 21:08 UTC, n0099 commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_map_selection_box=Manual - 每次切换世界或维度时，你都被要求选择并确认地图. \n \n 世界生成 - 世界地图是根据游戏客户端所知道的世界刷新的自动确认和选择的 \n \n 单一 - 如果服务器在自定义函数中使用普通的指南针项目，可以中断.每个维度都有一个自动确认的世界地图.适用于单一世界的简单服务器.
```suggestion
gui.xaero_map_selection_box=Manual - 每次切换世界或维度时，你都被要求选择并确认地图。\n \n 世界生成 - 世界地图是根据游戏客户端所知道的世界刷新的自动确认和选择的 \n \n 单一——如果服务器在自定义函数中使用普通的指南针项目，可以中断。每个维度都有一个自动确认的世界地图。适用于单一世界的简单服务器。
```
这是机翻吗

2022-05-02 21:08 UTC, n0099 commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_wm_box_ignore_heightmaps=一些服务器在世界高度贴图中放置自定义值，这可能会导致错误渲染贴图。有时，这种情况甚至可以发生在高度改装的单人游戏世界中。这个选项应该以牺牲一点性能为代价来解决这些问题。
```suggestion
gui.xaero_wm_box_ignore_heightmaps=某些服务器在世界高度贴图中放置自定义值，这可能会导致错误渲染贴图。有时，这种情况甚至可以发生在mod较多的单人游戏世界中。这个选项应该以牺牲一点性能为代价来解决这些问题。
```

2022-05-02 21:08 UTC, n0099 commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_wm_ignore_heightmaps=Ignore服务器高度映射
```suggestion
gui.xaero_wm_ignore_heightmaps=忽略服务器高度映射
```

2022-05-02 21:08 UTC, n0099 commented
请把全半角符号统一一下

2022-05-03 08:58 UTC, mamaruo commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_block_colours=区块颜色
block 怎么翻成区块的？

2022-05-03 09:00 UTC, GhostWinds commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_block_colours=区块颜色
我现在才发现

2022-05-03 09:04 UTC, mamaruo commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_block_colours=区块颜色
我不理解你不改翻译然后把review给resolve了是干嘛

2022-05-03 09:05 UTC, GhostWinds commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_block_colours=区块颜色
你不能帮我改的吗？

2022-05-03 09:20 UTC, Cyl18 commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_wm_legacy_color=遗产
really?

2022-05-03 09:20 UTC, mamaruo commented
/update en [xaeros-world-map] [1.12.2]

2022-05-03 09:21 UTC, mamaruo commented
/update-en [xaeros-world-map] [1.12.2]

2022-05-03 09:23 UTC, mamaruo commented
/update-en xaeros-world-map 1.12.2

2022-05-03 09:28 UTC, mamaruo commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_wm_legacy_color=遗产
不合理
传承？

2022-05-03 21:52 UTC, n0099 requested changes

2022-05-03 21:52 UTC, n0099 commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_terrain_slopes=地形斜坡
这到底是啥

2022-05-04 05:00 UTC, Rinko1231 commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_terrain_slopes=地形斜坡
斜坡感觉更错（

2022-05-04 05:14 UTC, mamaruo requested changes
半角英文句号，应为全角中文

2022-05-04 22:08 UTC, n0099 commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_terrain_slopes=地形斜坡
得看游戏里是什么

2022-05-07 10:52 UTC, Cyl18 commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_map_zoom_out=缩小 (替代）
what is this

2022-05-07 10:52 UTC, Cyl18 commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_right_click_map_cant_teleport=§8(传送) 含糊不清……
原文还有个Y

2022-05-07 11:16 UTC, mamaruo commented
需要游戏内验证

2022-05-07 13:26 UTC, n0099 commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_map_zoom_out=缩小 (替代）
可能alternate

2022-05-07 13:26 UTC, n0099 commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_right_click_map_cant_teleport=§8(传送) 含糊不清……
```suggestion
gui.xaero_right_click_map_cant_teleport=§8（传送）含糊不清……
```

2022-07-04 14:13 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_mw_spawn=世界生成
这里原文是“World Spawn”，实测是“世界重生点”的意思，请问修改原因？

2022-07-04 14:24 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_wm_box_ignore_heightmaps=某些服务器在世界高度贴图中放置自定义值，这可能会导致错误渲染贴图。有时，这种情况甚至可以发生在mod较多的单人游戏世界中。这个选项应该以牺牲一点性能为代价来解决这些问题。
```suggestion
gui.xaero_wm_box_ignore_heightmaps=某些服务器在世界高度贴图中放置自定义值，这可能会导致错误渲染贴图。有时，这种情况甚至可以发生在mod较多的单人游戏世界中。这个选项应该以牺牲一点性能为代价来解决这些问题。除非需要，否则不要使用。切换选项后重新进入世界！
```

2022-07-04 14:24 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_wm_box_ignore_heightmaps=某些服务器在世界高度贴图中放置自定义值，这可能会导致错误渲染贴图。有时，这种情况甚至可以发生在mod较多的单人游戏世界中。这个选项应该以牺牲一点性能为代价来解决这些问题。
漏掉了一些翻译

2022-07-04 14:26 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_open_map_animation=开放式动画
原文“Animation On Open”，翻译成开放式动画也太草了

2022-07-04 14:27 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_open_map_animation=开放式动画
```suggestion
gui.xaero_open_map_animation=打开时显示动画
```

2022-07-04 14:30 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_box_zoom_in=放大 \n（或者用鼠标滚轮）
```suggestion
gui.xaero_box_zoom_in=放大 \n （或者用鼠标滚轮）
```

2022-07-04 14:30 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_box_zoom_out=缩小 \n（或者用鼠标滚轮）
```suggestion
gui.xaero_box_zoom_out=缩小 \n （或者用鼠标滚轮）
```

2022-07-04 14:34 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_no_world_map_message=该地图已经禁用药水效果。
原文“The map is disabled with a potion effect.”
```suggestion
gui.xaero_no_world_map_message=该地图已被药水效果禁用。
```

2022-07-04 14:44 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_box_controls_minimap=\n 路径点控制：\n §2%s§r 创建一个新路径 \n §2%s§r 快速创建临时路径点 \n §2%s§r 改变路径点设置 \n §2%s§r 切换所有路径点设置 \n §2%s§r 打开路径点菜单 \n \n \n
原文比较长：
> gui.xaero_box_controls_minimap=\n Waypoint controls: \n §2%s§r to create a new waypoint. \n §2%s§r to create a quick temporary waypoint. \n §2%s§r to switch the waypoint set. \n §2%s§r to toggle rendering all waypoint sets. \n §2%s§r to open the full waypoint menu. \n Right-click an existing waypoint for more waypoint controls. \n \n 
```suggestion
gui.xaero_box_controls_minimap=\n 路径点控制： \n §2%s§r 创建一个新路径点 \n §2%s§r 快速创建临时路径点 \n §2%s§r 切换路径点集 \n §2%s§r 切换渲染所有路径点集 \n §2%s§r 打开路径点菜单。 \n 右键点击现有的路径点以获得更多路径点控制。 \n \n 
```

2022-07-04 14:50 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_box_open_waypoints=路径
```suggestion
gui.xaero_box_open_waypoints=路径点
```

2022-07-04 14:50 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_box_close_waypoints=关闭路径
```suggestion
gui.xaero_box_close_waypoints=关闭路径点
```

2022-07-04 14:51 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_box_rendering_all_sets=§2%s§r 渲染所有路径点设置
> %s Rendering All Waypoint Sets
```suggestion
gui.xaero_box_rendering_all_sets=§2%s§r 渲染所有路径点集
```

2022-07-04 14:52 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_box_rendering_current_set=§2%s§r 只渲染当前设置
> %s Rendering Only The Current Set
```suggestion
gui.xaero_box_rendering_current_set=§2%s§r 只渲染当前路径点集
```

2022-07-04 14:55 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_box_waypoints_disabled=在世界地图设置中禁用路径点！
> Waypoints are disabled in the world map settings!
```suggestion
gui.xaero_box_waypoints_disabled=路径点在世界地图设置中被禁用！
```

2022-07-04 14:55 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_right_click_waypoint_edit=§2%s§r 编辑路径
```suggestion
gui.xaero_right_click_waypoint_edit=§2%s§r 编辑路径点
```

2022-07-04 14:58 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_right_click_waypoint_disable=§2%s§r 关闭路径点
```suggestion
gui.xaero_right_click_waypoint_disable=§2%s§r 禁用路径点
```

2022-07-04 14:59 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_right_click_waypoint_enable=§2%s§r 开启路径点
```suggestion
gui.xaero_right_click_waypoint_enable=§2%s§r 启用路径点
```

2022-07-04 15:00 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_waypoint_backgrounds=渲染地图背景
> Render Waypoint Backgrounds
问号？
```suggestion
gui.xaero_waypoint_backgrounds=渲染路径点背景
```

2022-07-04 15:05 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_wm_arrow_colour=箭头演示
> Arrow Color
你的输入法？
```suggestion
gui.xaero_wm_arrow_colour=箭头颜色
```

2022-07-04 15:11 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_box_only_current_map_waypoints=只显示与当前世界地图的绑定。
> Displaying only the waypoints bound to the current world map, even if another waypoint sub-world is selected for the minimap using the full waypoint menu.
```suggestion
gui.xaero_box_only_current_map_waypoints=仅显示绑定到当前世界地图的航点，即使通过路径点菜单为小地图选择了另一个路径点子世界。
```

2022-07-04 15:14 UTC, Demonese commented
我蚌埠住了，怎么这么多问题

2022-07-04 15:19 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_box_waypoints_selected_by_minimap=从你在游戏和小地图中看到的同一路径点分离。
？
> Displaying waypoints from the same waypoint sub-world that you are viewing in game and on the minimap. The sub-world can be switched in the full waypoint menu.
```suggestion
gui.xaero_box_waypoints_selected_by_minimap=显示您在游戏和小地图上查看的同一路径点子世界的路径点。子世界可以在路径点菜单中切换。
```

2022-07-04 15:26 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_wm_box_adjust_height_for_carpetlike_blocks=短地毯状块的高度值中减去1，例如地毯、1层雪等。这可以防止此类区块在地图上造成严重阴影。路径点在这些区块上的远程传送应该会带来更多好处
```suggestion
gui.xaero_wm_box_adjust_height_for_carpetlike_blocks=矮地毯状方块的高度值减去 1，例如地毯、1 层雪、睡莲等。这可以防止这些方块像一个完整的方块一样在地图上造成较重的阴影。在这些方块上的路径点和传送位置也应该更合理。
```

2022-07-04 15:29 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_wm_adjust_height_for_carpetlike_blocks=调整短块
根据这个选项的英文原文
> Adjust Y For Short Blocks
以及下面对这个选项的解释，应该修改为：
```suggestion
gui.xaero_wm_adjust_height_for_carpetlike_blocks=为矮的方块调整 Y 值
```

2022-07-04 15:39 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_wm_box_detect_ambiguous_y= 地图上的一个像素可以包含多个透明层及其下的不透明块。在较旧的非缓存地图数据文件中，在这种情况下，仅存储不透明块的Y级别（高度），这通常会导致盲目传送到存储区不安全Y坐标。启用此设置后，mod会像对待未发现的块一样对待此类贴图像素。它默认为2D航路点，并禁止直接传送到此类像素。禁用此功能的风险自负！
> A single pixel on the map can contain multiple transparent layers and an opaque block under them. In older non-cache map data files, only the Y level (height) of the opaque block is stored in such cases, which often makes it unsafe to blindly teleport to the stored Y coordinate. When this setting is ON, the mod treats such map pixels as it would undiscovered chunks. It defaults to 2D waypoints and disables direct teleportation to such pixels. Disable this at your own risk!
```suggestion
gui.xaero_wm_box_detect_ambiguous_y=地图上的一个像素可以包含多个透明层和它们下面的不透明方块。 在较旧的非缓存地图数据文件中，在这种情况下仅存储不透明方块的 Y 级别（高度），这通常会导致盲目地传送到存储的 Y 坐标是不安全的。启用此设置后，mod会将此类地图像素视为未发现的区块。它默认为 2D 路径点并禁用直接传送到此类像素。禁用此功能的风险自负！
```

2022-07-04 15:41 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_wm_detect_ambiguous_y=在发现的数据中检测不明确
> Detect Ambiguous Y In Discovered
根据该选项的解释（见下面），可以翻译为：
```suggestion
gui.xaero_wm_detect_ambiguous_y=在已发现的区块中检测不明确的 Y 值
```

2022-07-04 15:43 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_box_closing_menu_when_hopping=当跳转到一个路径点时关闭菜单 (左击切换)
```suggestion
gui.xaero_box_closing_menu_when_hopping=当跳转到一个路径点时关闭菜单（左击切换）
```

2022-07-04 15:43 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_box_not_closing_menu_when_hopping=当跳转到一个路径点时不要关闭菜单 (左击切换)
```suggestion
gui.xaero_box_not_closing_menu_when_hopping=当跳转到一个路径点时不要关闭菜单（左击切换）
```

2022-07-04 15:43 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_right_click_map_cant_teleport_world=§8(Teleport) 未确认的……
```suggestion
gui.xaero_right_click_map_cant_teleport_world=§8（传送）未确认的……
```

2022-07-04 15:44 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_right_click_map_cant_teleport=§8(传送) 含糊不清……
```suggestion
gui.xaero_right_click_map_cant_teleport=§8（传送）不明确的 Y 值……
```

2022-07-04 15:56 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_terrain_slopes=地形斜坡
斜坡是没问题的，像这种有高度变化的地方会渲染阴影：
<img width="793" alt="image" src="https://user-images.githubusercontent.com/57629614/177188390-5ea6bf71-68cb-4fe4-887a-74a0af7da28c.png">
关掉后就变成这样：
<img width="497" alt="image" src="https://user-images.githubusercontent.com/57629614/177188334-d90a3570-4c4e-4056-87ac-2635dd9a0314.png">

2022-07-04 18:14 UTC, Demonese commented
@mamaruo 解决完上面那两条建议就可以标记为 ready to merge 了，游戏内实测后修了很多错误错误。
方便的话也可以看看我修正过的部分。

2022-07-04 19:27 UTC, mamaruo commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_map_zoom_out=缩小 (替代）
这应该是类似于某些游戏的按键绑定每个功能可以绑两个键

2022-07-04 19:34 UTC, Demonese commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_map_zoom_out=缩小 (替代）
> 可以绑两个键

是这么个意思，但是语言匮乏，不知道怎么简短表达

2022-07-23 17:38 UTC, mamaruo commented
准备合并

2022-07-23 17:39 UTC, mamaruo commented on projects/1.12.2/assets/xaeros-world-map/xaeroworldmap/lang/zh_cn.lang
> +gui.xaero_terrain_slopes=地形斜坡
好

2022-08-07 11:56 UTC, dovisutu commented
还有几个关于`alternate`的review暂未处理（
等处理完（或者确认可以忽略）就合吧

2022-10-23 16:10 UTC, Demonese commented
我认为alternate的讨论一直拖着也不太好，先合并，进一步的讨论就开个新pr

2022-10-23 16:10 UTC, Demonese approved these changes

2022-10-23 16:12 UTC, ChuijkYahus approved these changes

2022-10-23 16:12 UTC, merged