Main
CFPAOrg/Minecraft-Mod-Language-Package pull request #1945
Opened 2022-05-04 07:18 UTC by MrZhang21626

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-04 22:15 UTC, n0099 requested changes

2022-05-04 22:15 UTC, n0099 commented on projects/1.16/assets/dynamic-trees-byg/dtbyg/lang/zh_cn.json
> +    "species.dtbyg.sparse_tapered_withering_oak": "稀疏的锥型凋零橡树",
```suggestion
    "species.dtbyg.withering_oak": "凋零橡木",
    "species.dtbyg.sparse_withering_oak": "稀疏的凋零橡木",
    "species.dtbyg.tapered_withering_oak": "锥型凋零橡木",
    "species.dtbyg.sparse_tapered_withering_oak": "稀疏的锥型凋零橡木",
```

2022-05-04 22:15 UTC, n0099 commented on projects/1.16/assets/dynamic-trees-byg/dtbyg/lang/zh_cn.json
> +    "block.dtbyg.oddity_cactus_branch": "子实体仙人掌",
为啥oddity叫子实体

2022-05-04 22:15 UTC, n0099 commented on projects/1.16/assets/dynamic-trees-byg/dtbyg/lang/zh_cn.json
> +    "block.dtbyg.lament_branch": "哀叹树",
有没有可能是引用的
https://bof.fandom.com/wiki/Lament_Woods
https://www.youtube.com/watch?v=NfNLc4Q3Ms4

2022-05-05 09:52 UTC, MrZhang21626 commented on projects/1.16/assets/dynamic-trees-byg/dtbyg/lang/zh_cn.json
> +    "species.dtbyg.sparse_tapered_withering_oak": "稀疏的锥型凋零橡树",
BYG里面就是这样翻译的

2022-05-06 10:04 UTC, MrZhang21626 commented on projects/1.16/assets/dynamic-trees-byg/dtbyg/lang/zh_cn.json
> +    "block.dtbyg.lament_branch": "哀叹树",
但是BYG里面就是这样翻译的

2022-05-06 13:40 UTC, ChuijkYahus commented on projects/1.16/assets/dynamic-trees-byg/dtbyg/lang/zh_cn.json
> +    "block.dtbyg.oddity_cactus_branch": "子实体仙人掌",
byg的汉化更新过了

2022-05-06 13:47 UTC, ChuijkYahus commented on projects/1.16/assets/dynamic-trees-byg/dtbyg/lang/zh_cn.json
> +    "block.dtbyg.witch_hazel_branch": "金缕梅",
```suggestion
    "block.dtbyg.witch_hazel_branch": "金缕梅树",
```

2022-05-06 13:47 UTC, ChuijkYahus commented on projects/1.16/assets/dynamic-trees-byg/dtbyg/lang/zh_cn.json
> +    "block.dtbyg.skyris_branch": "天际木",
```suggestion
    "block.dtbyg.skyris_branch": "天际树",
```

2022-05-06 13:47 UTC, ChuijkYahus commented on projects/1.16/assets/dynamic-trees-byg/dtbyg/lang/zh_cn.json
> +    "block.dtbyg.ebony_branch": "乌木树",
```suggestion
    "block.dtbyg.ebony_branch": "乌木",
```
这个我也没法确定

2022-05-06 13:47 UTC, ChuijkYahus commented on projects/1.16/assets/dynamic-trees-byg/dtbyg/lang/zh_cn.json
> +    "block.dtbyg.mangrove_branch": "红树林木",
```suggestion
    "block.dtbyg.mangrove_branch": "红树",
```

2022-05-06 13:47 UTC, ChuijkYahus commented on projects/1.16/assets/dynamic-trees-byg/dtbyg/lang/zh_cn.json
> +    "block.dtbyg.oddity_cactus_branch": "子实体仙人掌",
```suggestion
    "block.dtbyg.oddity_cactus_branch": "奇异仙人掌",
```

2022-05-06 13:47 UTC, ChuijkYahus commented on projects/1.16/assets/dynamic-trees-byg/dtbyg/lang/zh_cn.json
> +    "species.dtbyg.joshua": "约书亚",
```suggestion
    "species.dtbyg.joshua": "短叶丝兰树",
```

2022-05-06 13:47 UTC, ChuijkYahus commented on projects/1.16/assets/dynamic-trees-byg/dtbyg/lang/zh_cn.json
> +    "species.dtbyg.aspen": "山杨",
```suggestion
    "species.dtbyg.aspen": "白杨",
```
下同，也要验证一下语境里要不要“木”这个字

2022-05-06 13:47 UTC, ChuijkYahus commented on projects/1.16/assets/dynamic-trees-byg/dtbyg/lang/zh_cn.json
> +    "species.dtbyg.palo_verde": "帕洛佛得角",
```suggestion
    "species.dtbyg.palo_verde": "扁轴",
```

2022-05-06 13:47 UTC, ChuijkYahus commented on projects/1.16/assets/dynamic-trees-byg/dtbyg/lang/zh_cn.json
> +    "block.dtbyg.oddity_cactus_branch": "子实体仙人掌",
下面类似的问题也改一下吧

2022-05-07 11:14 UTC, mamaruo commented
request 收到，但我不熟悉这模组，而且有太多既有术语要对照了

2022-05-07 13:26 UTC, n0099 commented
跟byg同步就行了

2022-06-06 11:38 UTC, mamaruo approved these changes

2022-06-06 12:05 UTC, merged