[R] 1.18.2植物魔法翻译大改
CFPAOrg/Minecraft-Mod-Language-Package pull request #1946
Opened 2022-05-04 11:50 UTC by mc-kaishixiaxue

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 是 1.16 及以上的翻译，应该是：projects/1.18/assets/botania/botania/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

1.18.2的现有翻译有太多过时内容，从作者那边导入翻译并加以改进。
为确保万无一失，需要做审查，尽可能一次性找出所有有问题的地方。

2022-05-04 14:52 UTC, AnzhiZhang reviewed
对比了下原文，发现了一些有意思的内容

2022-05-04 14:52 UTC, AnzhiZhang commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "stat.botania.corporea_items_requested": "从多媒体索引获得物品数",
原文 `Items Requested via Corporea Index`，语态不一致

2022-05-04 14:52 UTC, AnzhiZhang commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "botania.landing": "魔法，自然也是科技。$(br2)植物魔法是一个以自然魔法为主题的科技模组，主要通过使用魔法花朵和装置来运用大地之中的$(thing)魔力$()。",
后半段原文 `utilizing the power of the earth, in the form of $(thing)Mana$().`

2022-05-04 14:52 UTC, AnzhiZhang commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "botaniamisc.inputtingPower": "接收来自物品的能量",
同上，Mana翻译成能量

2022-05-04 14:52 UTC, AnzhiZhang commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "botaniamisc.getALife": "你难道没有现实生活吗？",
原文 `Get a Life`，这是自创中文烂梗？

2022-05-04 15:17 UTC, AnzhiZhang commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "botaniamisc.getALife": "你难道没有现实生活吗？",
还有这个意思，但是和此处`现实生活`的翻译没有太大关系，Get a life 似乎并没有对 `现实` 的强调或对比

2022-05-04 16:19 UTC, mamaruo commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "botaniamisc.outputtingPower": "给物品输送能量",
![image](https://user-images.githubusercontent.com/37480168/166725827-03d3b37c-37bd-4221-a0ad-03a6a8699e8d.png)

2022-05-04 16:25 UTC, AnzhiZhang commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "botaniamisc.getALife": "你难道没有现实生活吗？",
看代码是给泰拉粉碎者充魔力升级到Java最大整数的时候会加一句吐槽，意思是“你闲得没事吗”
```suggestion
  "botaniamisc.getALife": "你闲得没事吗？",
```
```suggestion
  "botaniamisc.getALife": "过你自己的生活",
```

2022-05-04 22:23 UTC, n0099 commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "botaniamisc.outputtingPower": "给物品输送能量",
```suggestion
  "botaniamisc.outputtingPower": "给物品输送魔力",
```

2022-05-04 22:23 UTC, n0099 commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "botaniamisc.inputtingPower": "接收来自物品的能量",
```suggestion
  "botaniamisc.inputtingPower": "接收来自物品的魔力",
```

2022-05-04 22:24 UTC, n0099 commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "stat.botania.corporea_items_requested": "从多媒体索引获得物品数",
```suggestion
  "stat.botania.corporea_items_requested": "从多媒体索引获得物品",
```

2022-05-05 14:27 UTC, n0099 approved these changes

2022-05-05 15:38 UTC, AnzhiZhang reviewed
改了一些细节

2022-05-05 15:38 UTC, AnzhiZhang commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "botania.page.welcome1": "$(o)剥开其光鲜的外表，植物魔法的本质却是“科技模组”，因为对于科技模组的每一个环节来说，你都需要心灵手巧、深思熟虑、还有红石电路，方能不断推进科技前进。将这句话铭记在心，会很有用的。$(p)$(o)当然啦，不要担心，你同时还会得到一些酷炫的新玩具、方块还有装备。",
中文不在and之前加逗号，原文 `it requires you to put to use ingenuity, thought, and redstone to create and progress`
```suggestion
  "botania.page.welcome1": "$(o)剥开其光鲜的外表，植物魔法的本质却是“科技模组”，因为对于科技模组的每一个环节来说，你都需要聪明才智、细心思考和红石技术才能不断推进科技前进。将这句话铭记在心，会很有用的。$(p)$(o)当然啦，不要担心，你同时还会得到一些酷炫的新玩具、方块还有装备。",

```

2022-05-05 15:38 UTC, AnzhiZhang commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "botania.page.gardenOfGlass6": "除此之外，有些东西在植物魔法中调整得更适合空岛游戏：$(l:functional_flowers/orechid)$(item)凝矿兰$(0)$(/l)将更容易制作，速度更快并且更魔力消耗更低。$(l:devices/cocoon)$(item)随想之茧$(0)$(/l)以及$(l:mana/spreader)$(item)魔力
![image](https://user-images.githubusercontent.com/37402126/166954901-bd07d7f1-35ab-47ef-abf1-7b8ba005179e.png)
```suggestion
  "botania.page.gardenOfGlass6": "除此之外，有些东西在植物魔法中调整得更适合空岛游戏：$(l:functional_flowers/orechid)$(item)凝矿兰$(0)$(/l)将更容易制作，速度更快并且更魔力消耗更低。$(l:devices/cocoon)$(item)随想之茧$(0)$(/l)以及$(l:mana/spreader)$(item)魔力发射器$(0)$(/l)的配方也有所改变。用来制作$(item)黑曜石$(0)的$(l:misc/blaze_block)$(item)烈焰网$(0)$(/l)，改为用烈焰粉而不是烈焰棒合成；西瓜种子和南瓜种子可以通过打掉高草掉落；每份原料可以制作更多的花肥。同时，还加入了$(item)甘蔗$(0)和$(item)黏液球$(0)的制作配方。",

```

2022-05-05 15:38 UTC, AnzhiZhang commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
>    "botania.page.gardenOfGlass12": "最后，制作$(item)末地传送门$(0)的配方",
![image](https://user-images.githubusercontent.com/37402126/166955100-9e020294-b736-4837-92ab-01b268769049.png)
```suggestion
  "botania.page.gardenOfGlass12": "最后，制作$(item)末地传送门框架$(0)的配方",

```

2022-05-05 15:38 UTC, AnzhiZhang commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
>    "botania.page.pool11": "制作$(item)魔力玻璃$(0)，透明且无缝的玻璃。",
原文 `"botania.page.pool11": "Infusing $(item)Managlass$(0): clear seamless glass",` 没有句号，且上下文统一
![image](https://user-images.githubusercontent.com/37402126/166956244-56971d70-3fd5-4fb2-bb6a-3cb886fd1b37.png)
```suggestion
  "botania.page.pool11": "制作$(item)魔力玻璃$(0)，透明且无缝的玻璃",

```

2022-05-05 15:38 UTC, AnzhiZhang commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "botania.page.sparks1": "将两个$(item)火花$(0)分别放置于一个$(l:mana/pool)$(item)魔力池$(0)$(/l)和另一个能接受火花魔力的方块上方便组成了$(item)火花魔力网$(0)。只要它们不要离得太远，后者在需要能量时就能直接使用存储于该$(l:mana/pool)$(item)魔力池$(0)$(/l)中的魔力。$(p)要移除$(ite
感觉还是原来的好些，原文没有提到火花魔力网这个概念，增加概念可能会导致混淆

2022-05-05 15:38 UTC, AnzhiZhang commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "botania.page.redstoneSpreader1": "只要撒一点红石粉",
![image](https://user-images.githubusercontent.com/37402126/166957472-bd08c2bd-133a-4054-a690-83134b11e08a.png)
合成来的，还是加点比较好
```suggestion
  "botania.page.redstoneSpreader1": "只要加点红石粉",

```

2022-05-05 15:38 UTC, AnzhiZhang commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "botania.page.orechid1": "$(o)不太神奇的人会说这是一个筛子$(0)。",
```suggestion
  "botania.page.orechid1": "$(o)不那么魔法地说，这是巫术$(0)。",

```

2022-05-05 15:38 UTC, AnzhiZhang commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "botania.page.exoflame0": "不像火红莲，$(item)冶炼火$(0)将$(thing)魔力$(0)用于产生热量。$(p)邻近的$(item)熔炉$(0)都会被$(item)冶炼火$(0)加热，提高效率的同时消耗一些$(thing)魔力$(0)。",
`Conversely to its $(thing)Generating$(0) counterpart`
```suggestion
  "botania.page.exoflame0": "与火红莲相反，$(item)冶炼火$(0)将$(thing)魔力$(0)用于产生热量。$(p)邻近的$(item)熔炉$(0)都会被$(item)冶炼火$(0)加热，提高效率的同时消耗一些$(thing)魔力$(0)。",

```

2022-05-05 15:38 UTC, AnzhiZhang commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "botania.page.endoflame3": "由于$(item)火红莲$(0)通常是植物魔法师们在自动化$(thing)主动产能花$(0)的道路上迈出的第一步，这里不建议一直手动管理火红莲.因为火红莲只会燃烧掉落物，使用$(l:devices/open_crate)$(item)花格箱$(0)$(/l)（相关介绍可在$(thing)自然装置$(0)部分找到）搭配一些其他控制掉落物的
```suggestion
  "botania.page.endoflame3": "由于$(item)火红莲$(0)通常是植物魔法师们在自动化$(thing)主动产能花$(0)的道路上迈出的第一步，这里不建议一直手动管理火红莲。因为火红莲只会燃烧掉落物，使用$(l:devices/open_crate)$(item)花格箱$(0)$(/l)（相关介绍可在$(thing)自然装置$(0)部分找到）搭配一些其他控制掉落物的装置（计时器、压力板等等）进行自动化会是理想的选择。",

```

2022-05-05 15:42 UTC, AnzhiZhang commented
关于苔活木板和苔活石砖的问题，这是官方翻译，改成覆苔活木板和覆苔活石砖的话需要统一一下

2022-05-06 00:33 UTC, mc-kaishixiaxue commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
>    "block.botania.mossy_livingwood_planks": "苔活木板",
参考原版的苔石、苔石砖，去掉“覆苔”前面的“覆”。

2022-05-06 00:35 UTC, AnzhiZhang commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
>    "block.botania.mossy_livingwood_planks": "苔活木板",
去掉的话，有几处需要修改

2022-05-06 00:57 UTC, n0099 approved these changes

2022-05-08 08:26 UTC, AnzhiZhang reviewed
@CFPABot 的一些检查

2022-05-08 08:26 UTC, AnzhiZhang commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "botania.page.ghostRail0": "使用$(l:devices/spectral_platform)$(item)幻影平台$(0)$(/l)作为$(item)铁轨$(0)元件会产生$(item)幻影铁轨$(0)，这使得从它上面经过的$(item)矿车$(0)会做一些有趣的事情：当从$(item)幻影铁轨$(0)上发射时，矿车会漂浮一小段距离并短暂地获得穿墙的能力。$(p)
![image](https://user-images.githubusercontent.com/37402126/167287982-06848d6f-fc31-4226-bb25-922373ee3b8b.png)
确认漂浮是对的

2022-05-08 08:26 UTC, AnzhiZhang commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
>    "botania.page.pollidisiac1": "$(o)地狱厨房$(0)。",
确认地狱是对的，原文 `Hell's Kitchen`

2022-05-08 21:14 UTC, Cyl18 commented
> @CFPABot 的一些检查
> 
> `粉色` 和 `合成台` 已修复，建议刷新一下机器人

合成台修了俩 还有一个没修

2022-05-08 22:27 UTC, n0099 requested changes

2022-05-08 22:27 UTC, n0099 commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "botania.page.keepIvy0": "每个人都知道，死了东西会洒一地，通常是个极大的麻烦。解决办法十分简单：通过将$(item)坚毅之藤$(0)与物品在合成台合成，该物品就会在死亡的时候保留在物品栏。不幸的是，藤蔓在死亡一次之后就会枯死，必须重新手动添加。",
```suggestion
  "botania.page.keepIvy0": "每个人都知道，死了东西会洒一地，通常是个极大的麻烦。解决办法十分简单：通过将$(item)坚毅之藤$(0)与物品在工作台合成，该物品就会在死亡的时候保留在物品栏。不幸的是，藤蔓在死亡一次之后就会枯死，必须重新手动添加。",
```

2022-05-10 00:06 UTC, n0099 approved these changes

2022-05-10 01:31 UTC, n0099 commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "entity.botania.pink_wither": "粉红色凋灵",
是

2022-05-22 00:24 UTC, n0099 approved these changes

2022-09-25 09:11 UTC, closed without merging