[R] Sea Dwellers 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1951
Opened 2022-05-05 10:56 UTC by H0lyDiana

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-05 13:53 UTC, Cyl18 commented
/sort-keys projects/1.16/assets/nocubes-sea-dwellers/seadwellers/lang/en_us.json
/sort-keys projects/1.16/assets/nocubes-sea-dwellers/seadwellers/lang/zh_cn.json

2022-05-05 14:28 UTC, n0099 requested changes

2022-05-06 03:47 UTC, n0099 approved these changes

2022-05-07 19:05 UTC, mamaruo approved these changes

2022-05-07 19:11 UTC, mamaruo commented on projects/1.16/assets/nocubes-sea-dwellers/seadwellers/lang/zh_cn.json
> +  "gamerule.seaTraderCooldown": "海洋交易冷却时间",
```suggestion
  "gamerule.seaTraderCooldown": "海洋交易冷却",
```

2022-05-07 19:12 UTC, mamaruo commented on projects/1.16/assets/nocubes-sea-dwellers/seadwellers/lang/zh_cn.json
> +  "entity.seadwellers.biome_mermorph": "群系海灵",
Biome mermorph，我不理解

2022-05-08 02:42 UTC, merged

2022-05-08 04:43 UTC, mamaruo commented on projects/1.16/assets/nocubes-sea-dwellers/seadwellers/lang/zh_cn.json
> +  "entity.seadwellers.biome_mermorph": "群系海灵",
我其实想问这名字我想不到对应什么东西

2022-05-08 05:57 UTC, n0099 commented on projects/1.16/assets/nocubes-sea-dwellers/seadwellers/lang/zh_cn.json
> +  "entity.seadwellers.biome_mermorph": "群系海灵",
经典生造词