[R] /tank/null 翻译提交及维护
CFPAOrg/Minecraft-Mod-Language-Package pull request #1955
Opened 2022-05-06 09:16 UTC by AnzhiZhang

Co-authored-by: mudapi <dabo12315@qq.com>

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-06 09:49 UTC, AnzhiZhang commented
提供一下游戏内的界面方便审核
![image](https://user-images.githubusercontent.com/37402126/167108788-0771a396-ed0f-43e4-a7c2-93466b143500.png)

2022-05-07 04:19 UTC, n0099 requested changes

2022-05-07 04:19 UTC, n0099 commented on projects/1.16/assets/tank-null/tanknull/lang/zh_cn.json
> +  "item.tanknull.6_to_7": "6级到7级",
```suggestion
  "item.tanknull.1_to_2": "1级到2级升级",
  "item.tanknull.2_to_3": "2级到3级升级",
  "item.tanknull.3_to_4": "3级到4级升级",
  "item.tanknull.4_to_5": "4级到5级升级",
  "item.tanknull.5_to_6": "5级到6级升级",
  "item.tanknull.6_to_7": "6级到7级升级",
```

2022-05-07 13:26 UTC, n0099 approved these changes

2022-05-07 18:40 UTC, mamaruo commented on projects/1.16/assets/tank-null/tanknull/lang/zh_cn.json
> +  "text.tanknull.mode.empty": "空置",
这干什么用的

2022-05-08 01:41 UTC, AnzhiZhang commented on projects/1.16/assets/tank-null/tanknull/lang/zh_cn.json
> +  "text.tanknull.mode.empty": "空置",
这个储罐可以装或者倒流体，采用了和热力的大桶一样的名称

2022-05-08 02:19 UTC, AnzhiZhang commented on projects/1.16/assets/tank-null/tanknull/lang/zh_cn.json
> +  "text.tanknull.mode.empty": "空置",
![image](https://user-images.githubusercontent.com/37402126/167279019-22a3e47a-f128-4ada-8b0e-b8cde6a9915c.png)
![image](https://user-images.githubusercontent.com/37402126/167279022-10662783-ff16-46f6-8d9a-76f4989818ba.png)

2022-05-08 02:42 UTC, merged