[R] Iron Furnaces 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #1956
Opened 2022-05-06 10:22 UTC by AnzhiZhang

Co-authored-by: 奈 <58922212@qq.com>

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-07 04:21 UTC, n0099 commented on projects/1.16/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
> +    "tooltip.ironfurnaces.gui_redstone_high": "红石控制-高",
信号强度？

2022-05-07 04:24 UTC, n0099 requested changes

2022-05-07 04:24 UTC, n0099 commented on projects/1.16/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
> +    "item.ironfurnaces.upgrade_netherite": "熔炉升级：黑曜石-下界合金",
```suggestion
    "item.ironfurnaces.upgrade_iron": "熔炉升级：石->铁",
    "item.ironfurnaces.upgrade_gold": "熔炉升级：铁->金",
    "item.ironfurnaces.upgrade_diamond": "熔炉升级：金->钻石",
    "item.ironfurnaces.upgrade_emerald": "熔炉升级：钻石->绿宝石",
    "item.ironfurnaces.upgrade_obsidian": "熔炉升级：绿宝石->黑曜石",
    "item.ironfurnaces.upgrade_crystal": "熔炉升级：钻石->水晶",
    "item.ironfurnaces.upgrade_obsidian2": "熔炉升级：水晶->黑曜石",
    "item.ironfurnaces.upgrade_netherite": "熔炉升级：黑曜石->下界合金",
```

2022-05-07 04:24 UTC, n0099 commented on projects/1.16/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
> +    "item.ironfurnaces.upgrade_gold2": "熔炉升级：银-金",
```suggestion
    "item.ironfurnaces.upgrade_copper": "熔炉升级：石->铜",
    "item.ironfurnaces.upgrade_silver": "熔炉升级：铜->银",
    "item.ironfurnaces.upgrade_silver2": "熔炉升级：铁->银",
    "item.ironfurnaces.upgrade_iron2": "熔炉升级：铜->铁",
    "item.ironfurnaces.upgrade_gold2": "熔炉升级：银->金",
```

2022-05-07 04:24 UTC, n0099 commented on projects/1.16/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
> +    "item.ironfurnaces.upgrade_unobtainium": "熔炉升级：振金-难得素",
```suggestion
    "item.ironfurnaces.upgrade_allthemodium": "熔炉升级：下界合金->ATM",
    "item.ironfurnaces.upgrade_vibranium": "熔炉升级：ATM->振金",
    "item.ironfurnaces.upgrade_unobtainium": "熔炉升级：振金->难得素",
```
ATM6里有合金叫`atm-vibranium` `vibranium-unobtainium`

2022-05-07 04:24 UTC, n0099 commented on projects/1.18/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
> +    "item.ironfurnaces.upgrade_netherite": "熔炉升级：黑曜石-下界合金",
```suggestion
    "item.ironfurnaces.upgrade_iron": "熔炉升级：石->铁",
    "item.ironfurnaces.upgrade_gold": "熔炉升级：铁->金",
    "item.ironfurnaces.upgrade_diamond": "熔炉升级：金->钻石",
    "item.ironfurnaces.upgrade_emerald": "熔炉升级：钻石->绿宝石",
    "item.ironfurnaces.upgrade_obsidian": "熔炉升级：绿宝石->黑曜石",
    "item.ironfurnaces.upgrade_crystal": "熔炉升级：钻石->水晶",
    "item.ironfurnaces.upgrade_obsidian2": "熔炉升级：水晶->黑曜石",
    "item.ironfurnaces.upgrade_netherite": "熔炉升级：黑曜石->下界合金",
```

2022-05-07 04:24 UTC, n0099 commented on projects/1.18/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
> +    "item.ironfurnaces.upgrade_gold2": "熔炉升级：银-金",
```suggestion
    "item.ironfurnaces.upgrade_copper": "熔炉升级：石->铜",
    "item.ironfurnaces.upgrade_silver": "熔炉升级：铜->银",
    "item.ironfurnaces.upgrade_silver2": "熔炉升级：铁->银",
    "item.ironfurnaces.upgrade_iron2": "熔炉升级：铜->铁",
    "item.ironfurnaces.upgrade_gold2": "熔炉升级：银->金",
```

2022-05-07 04:24 UTC, n0099 commented on projects/1.18/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
> +    "item.ironfurnaces.upgrade_unobtainium": "熔炉升级：振金-难得素",
```suggestion
    "item.ironfurnaces.upgrade_allthemodium": "熔炉升级：下界合金->ATM",
    "item.ironfurnaces.upgrade_vibranium": "熔炉升级：ATM->振金",
    "item.ironfurnaces.upgrade_unobtainium": "熔炉升级：振金->难得素",
```

2022-05-07 12:27 UTC, AnzhiZhang commented on projects/1.16/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
> +    "tooltip.ironfurnaces.gui_redstone_high": "红石控制-高",
如果是高，即为有信号时工作，如果是低，即为无信号时工作
![image](https://user-images.githubusercontent.com/37402126/167254384-ddd7d4f4-288a-49c7-b18a-a137e1319fa5.png)
这个位置有要按住 shift 才能显示低，为一个熄灭的红石火把，截不到图

别的模组使用 `有红石信号时启用` 之类的表述，这里的翻译能否提供个建议？

2022-05-07 13:27 UTC, n0099 approved these changes

2022-05-07 13:28 UTC, n0099 commented on projects/1.16/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
> +    "tooltip.ironfurnaces.gui_redstone_high": "红石控制-高",
支持`有红石信号时启用`
或者`红石信号反转`

2022-05-07 14:10 UTC, AnzhiZhang commented on projects/1.16/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
> +    "tooltip.ironfurnaces.gui_redstone_high": "红石控制-高",
这个翻译是来源于热力的红石控制，在这个界面可能有歧义
以下名称来自Refined Storage
```suggestion
    "tooltip.ironfurnaces.gui_redstone_low": "有红石信号时工作",
    "tooltip.ironfurnaces.gui_redstone_high": "无红石信号时工作",
```

2022-05-07 18:44 UTC, mamaruo commented on projects/1.16/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
> +    "tooltip.ironfurnaces.gui_redstone_high": "红石控制-高",
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/2038b5fdd9bf8fa831d950cce1a765fc18f9b008/projects/1.12.2/assets/1UNKNOWN/enderio/lang/zh_cn.lang#L1200-L1203
末影接口

2022-05-08 02:32 UTC, n0099 approved these changes

2022-05-08 20:12 UTC, Cyl18 commented on projects/1.16/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
> +    "item.ironfurnaces.item_linker": "彩虹连接器",
好奇 链接/连接的区别

2022-05-08 20:15 UTC, Cyl18 approved these changes

2022-05-08 22:28 UTC, n0099 commented on projects/1.16/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
> +    "item.ironfurnaces.item_linker": "彩虹连接器",
名词/动词

2022-05-08 22:28 UTC, merged