[R] Zerocore 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #1957
Opened 2022-05-06 10:37 UTC by AnzhiZhang

Co-authored-by: 奈 <58922212@qq.com>

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-07 04:18 UTC, n0099 requested changes

2022-05-07 04:18 UTC, n0099 commented on projects/1.16/assets/zerocore/zerocore/lang/zh_cn.json
> +    "gui.zerocore.base.control.energybar.line3b": "% full",
```suggestion
    "gui.zerocore.base.control.energybar.line3b": "% 满",
```

2022-05-07 04:18 UTC, n0099 commented on projects/1.18/assets/zerocore/zerocore/lang/zh_cn.json
> +    "gui.zerocore.base.control.energybar.line3b": "% full",
```suggestion
    "gui.zerocore.base.control.energybar.line3b": "% 满",
```

2022-05-07 04:18 UTC, n0099 commented on projects/1.18/assets/zerocore/zerocore/lang/zh_cn.json
> +    "zerocore:api.multiblock.validation.machine_too_small": "机器太小，在 %2$s 轴最少有 %1$d 个方块",
```suggestion
    "zerocore:api.multiblock.validation.machine_too_large": "机器太大，在%2$s轴最多只能有%1$d个方块",
    "zerocore:api.multiblock.validation.machine_too_small": "机器太小，在%2$s轴至少得有%1$d个方块",
```

2022-05-07 04:18 UTC, n0099 commented on projects/1.16/assets/zerocore/zerocore/lang/zh_cn.json
> +    "zerocore:api.multiblock.validation.machine_too_small": "机器太小，在 %2$s 轴最少有 %1$d 个方块",
```suggestion
    "zerocore:api.multiblock.validation.machine_too_large": "机器太大，在%2$s轴最多只能有%1$d个方块",
    "zerocore:api.multiblock.validation.machine_too_small": "机器太小，在%2$s轴至少得有%1$d个方块",
```

2022-05-07 13:28 UTC, n0099 approved these changes

2022-05-07 19:28 UTC, mamaruo requested changes

2022-05-07 19:28 UTC, mamaruo commented on projects/1.16/assets/zerocore/zerocore/lang/zh_cn.json
> +    "gui.zerocore.base.control.fluidbar.line4b": "% 已满"
Ln 34 和 Ln 39 不统一。
以及为什么空格变多了
>     "gui.zerocore.base.control.energybar.line2a": "  @0",
    "gui.zerocore.base.control.energybar.line2b": " / %1$s",
    "gui.zerocore.base.control.energybar.line3a": "  @1",
    "gui.zerocore.base.control.energybar.line3b": "% full",
    "gui.zerocore.base.control.fluidbar.line2": "  @0",
    "gui.zerocore.base.control.fluidbar.line3a": "  @1",
    "gui.zerocore.base.control.fluidbar.line3b": " / %1$s",
    "gui.zerocore.base.control.fluidbar.line4a": "  @2",
    "gui.zerocore.base.control.fluidbar.line4b": "% full"

2022-05-08 02:39 UTC, n0099 commented on projects/1.16/assets/zerocore/zerocore/lang/zh_cn.json
> +    "gui.zerocore.base.control.fluidbar.line4b": "% 已满"
L34是我改的，他原本没翻译

2022-05-08 02:48 UTC, AnzhiZhang commented on projects/1.16/assets/zerocore/zerocore/lang/zh_cn.json
> +    "gui.zerocore.base.control.fluidbar.line4b": "% 已满"
```suggestion
    "gui.zerocore.base.control.energybar.line2a": "    @0",
    "gui.zerocore.base.control.energybar.line2b": " / %1$s",
    "gui.zerocore.base.control.energybar.line3a": "    @1",
    "gui.zerocore.base.control.energybar.line3b": "% 已满",
    "gui.zerocore.base.control.fluidbar.line2": "    @0",
    "gui.zerocore.base.control.fluidbar.line3a": "    @1",
    "gui.zerocore.base.control.fluidbar.line3b": " / %1$s",
    "gui.zerocore.base.control.fluidbar.line4a": "    @2",
    "gui.zerocore.base.control.fluidbar.line4b": "% 已满"

```

2022-05-08 02:49 UTC, AnzhiZhang commented on projects/1.18/assets/zerocore/zerocore/lang/zh_cn.json
> +    "gui.zerocore.base.control.energybar.line3b": "% 满",
```suggestion
    "gui.zerocore.base.control.energybar.line3b": "% 已满",

```

2022-05-08 03:04 UTC, n0099 approved these changes

2022-05-08 04:45 UTC, mamaruo commented on projects/1.16/assets/zerocore/zerocore/lang/zh_cn.json
> +    "gui.zerocore.base.control.fluidbar.line4b": "% 已满"
还有莫名其妙的空格变多

2022-05-08 05:06 UTC, AnzhiZhang commented on projects/1.16/assets/zerocore/zerocore/lang/zh_cn.json
> +    "gui.zerocore.base.control.fluidbar.line4b": "% 已满"
![image](https://user-images.githubusercontent.com/37402126/167282673-0364ffb3-f9ea-4a3c-9588-45cf76680b0b.png)
已满应该是这里

2022-05-08 05:12 UTC, AnzhiZhang commented on projects/1.16/assets/zerocore/zerocore/lang/zh_cn.json
> +
```suggestion
    "gui.zerocore.base.control.energybar.line2a": "  @0",
    "gui.zerocore.base.control.energybar.line2b": " / %1$s",
    "gui.zerocore.base.control.energybar.line3a": "  @1",
    "gui.zerocore.base.control.energybar.line3b": "%已满",
    "gui.zerocore.base.control.fluidbar.line2": "  @0",
    "gui.zerocore.base.control.fluidbar.line3a": "  @1",
    "gui.zerocore.base.control.fluidbar.line3b": " / %1$s",
    "gui.zerocore.base.control.fluidbar.line4a": "  @2",
    "gui.zerocore.base.control.fluidbar.line4b": "%已满"


```

2022-05-08 05:13 UTC, AnzhiZhang commented on projects/1.18/assets/zerocore/zerocore/lang/zh_cn.json
> +    "gui.zerocore.base.control.fluidbar.line4b": "% 已满"
```suggestion
    "gui.zerocore.base.control.energybar.line2a": "  @0",
    "gui.zerocore.base.control.energybar.line2b": " / %1$s",
    "gui.zerocore.base.control.energybar.line3a": "  @1",
    "gui.zerocore.base.control.energybar.line3b": "%已满",
    "gui.zerocore.base.control.fluidbar.line2": "  @0",
    "gui.zerocore.base.control.fluidbar.line3a": "  @1",
    "gui.zerocore.base.control.fluidbar.line3b": " / %1$s",
    "gui.zerocore.base.control.fluidbar.line4a": "  @2",
    "gui.zerocore.base.control.fluidbar.line4b": "%已满"
```

2022-05-08 05:59 UTC, n0099 commented on projects/1.16/assets/zerocore/zerocore/lang/zh_cn.json
> +    "gui.zerocore.base.control.fluidbar.line4b": "% 已满"
这个已满是啥意思

2022-05-08 07:04 UTC, mamaruo commented on projects/1.16/assets/zerocore/zerocore/lang/zh_cn.json
> +    "gui.zerocore.base.control.fluidbar.line4b": "% 已满"
表示数量的话可能这么翻不对

2022-05-08 07:16 UTC, AnzhiZhang commented on projects/1.16/assets/zerocore/zerocore/lang/zh_cn.json
> +    "gui.zerocore.base.control.fluidbar.line4b": "% 已满"
![image](https://user-images.githubusercontent.com/37402126/167285975-4a9b8819-8205-44d7-bf11-111b3a5c3282.png)
看样子需要改成一个表达 `已填充部分` 的意思

2022-05-08 07:39 UTC, mamaruo commented on projects/1.16/assets/zerocore/zerocore/lang/zh_cn.json
> +    "gui.zerocore.base.control.fluidbar.line4b": "% 已满"
这东西在数字后面有点难搞

2022-05-08 08:01 UTC, AnzhiZhang commented on projects/1.16/assets/zerocore/zerocore/lang/zh_cn.json
> +    "gui.zerocore.base.control.fluidbar.line4b": "% 已满"
把已满前面的空格删了好像还不行，下面的枯竭是有空格的
图中mod为 [Extreme Reactors](https://www.curseforge.com/minecraft/mc-mods/extreme-reactors)，作者和 Zero Core 2 是同一个作者
![image](https://user-images.githubusercontent.com/37402126/167287185-b5efc261-bc47-45a1-9371-604c8f591f50.png)

2022-05-08 08:02 UTC, AnzhiZhang commented on projects/1.16/assets/zerocore/zerocore/lang/zh_cn.json
> +    "gui.zerocore.base.control.fluidbar.line4b": "% 已满"
补一张能量部分的截图
![image](https://user-images.githubusercontent.com/37402126/167287239-15550710-031e-42e8-ab53-e04d73c67f1e.png)

2022-05-08 08:13 UTC, AnzhiZhang reviewed
![image](https://user-images.githubusercontent.com/37402126/167287563-c49e3118-29f8-49c1-be6d-5438a82043ae.png)
不会随着燃料棒枯竭降低，燃料棒性质的转换该数值不变，考虑改为 `已用`

2022-05-08 08:13 UTC, AnzhiZhang commented on projects/1.16/assets/zerocore/zerocore/lang/zh_cn.json
> +    "gui.zerocore.base.control.fluidbar.line4b": "%已满"
```suggestion
    "_comment": "GUI",
    "gui.zerocore.base.generic.empty": "空",
    "gui.zerocore.base.screen.ioport.mode": "操作模式：",
    "gui.zerocore.base.control.energybar.line1": "内部能量缓存",
    "gui.zerocore.base.control.energybar.line2a": "  @0",
    "gui.zerocore.base.control.energybar.line2b": " / %1$s",
    "gui.zerocore.base.control.energybar.line3a": "  @1",
    "gui.zerocore.base.control.energybar.line3b": "% 已用",
    "gui.zerocore.base.control.fluidbar.line2": "  @0",
    "gui.zerocore.base.control.fluidbar.line3a": "  @1",
    "gui.zerocore.base.control.fluidbar.line3b": " / %1$s",
    "gui.zerocore.base.control.fluidbar.line4a": "  @2",
    "gui.zerocore.base.control.fluidbar.line4b": "% 已用"
```

2022-05-08 08:13 UTC, AnzhiZhang commented on projects/1.18/assets/zerocore/zerocore/lang/zh_cn.json
> +    "gui.zerocore.base.control.fluidbar.line4b": "%已满"
```suggestion
    "_comment": "GUI",
    "gui.zerocore.base.generic.empty": "空",
    "gui.zerocore.base.screen.ioport.mode": "操作模式：",
    "gui.zerocore.base.control.energybar.line1": "内部能量缓存",
    "gui.zerocore.base.control.energybar.line2a": "  @0",
    "gui.zerocore.base.control.energybar.line2b": " / %1$s",
    "gui.zerocore.base.control.energybar.line3a": "  @1",
    "gui.zerocore.base.control.energybar.line3b": "% 已用",
    "gui.zerocore.base.control.fluidbar.line2": "  @0",
    "gui.zerocore.base.control.fluidbar.line3a": "  @1",
    "gui.zerocore.base.control.fluidbar.line3b": " / %1$s",
    "gui.zerocore.base.control.fluidbar.line4a": "  @2",
    "gui.zerocore.base.control.fluidbar.line4b": "% 已用"
```

2022-05-08 10:03 UTC, mamaruo commented on projects/1.18/assets/zerocore/zerocore/lang/zh_cn.json
> +    "gui.zerocore.base.control.fluidbar.line4b": "%已满"
支持

2022-05-08 11:23 UTC, Cyl18 approved these changes

2022-05-08 13:41 UTC, n0099 approved these changes

2022-05-08 13:41 UTC, merged