[R] VanillaTweaks 官中拉取及改进
CFPAOrg/Minecraft-Mod-Language-Package pull request #1958
Opened 2022-05-06 11:04 UTC by AnzhiZhang

Co-authored-by: 奈 <58922212@qq.com>

1. 删除1.18，因为有官方完整翻译
2. 1.16使用官方翻译，缺失部分词条使用1.18的官方翻译 

缺失的Key均为罗马数字

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-06 11:07 UTC, Cyl18 commented on projects/1.16/assets/vanillatweaks/vanillatweaks/lang/zh_cn.json
> +  "enchantment.vanillatweaks.homing.desc": "作用于弓上,你的箭会自动瞄准你的目标",
全角 还少了句号

2022-05-06 11:11 UTC, AnzhiZhang commented on projects/1.16/assets/vanillatweaks/vanillatweaks/lang/zh_cn.json
> +  "enchantment.vanillatweaks.homing.desc": "作用于弓上,你的箭会自动瞄准你的目标",
官方翻的，1.18的完整翻译就是这样

2022-05-07 04:11 UTC, n0099 commented on projects/1.16/assets/vanillatweaks/vanillatweaks/lang/zh_cn.json
> +  "enchantment.vanillatweaks.homing.desc": "作用于弓上,你的箭会自动瞄准你的目标",
在同一个文件里应该统一全半角

2022-05-07 19:25 UTC, mamaruo requested changes
官中都是（  ）

2022-05-07 19:25 UTC, mamaruo commented on projects/1.16/assets/vanillatweaks/vanillatweaks/lang/zh_cn.json
> +  "enchantment.vanillatweaks.homing.desc": "作用于弓上，你的箭会自动瞄准你的目标",
缺少句号，还有“作用于XX上”是从哪里翻出来的。
  "enchantment.vanillatweaks.nimble.desc": "Each level adds a bit to your movement speed.",
  "enchantment.vanillatweaks.hops.desc": "Each level adds a bit to your jump height.",
  "enchantment.vanillatweaks.vigor.desc": "Grants the wearer a one heart max health increase per level.",
  "enchantment.vanillatweaks.veteran.desc": "Attract all experience orbs in a 32-block radius towards you.",
  "enchantment.vanillatweaks.blazing.desc": "Automatically smelts everything the block drops.",
  "enchantment.vanillatweaks.siphon.desc": "All mined block drops instantly go into your inventory.",
  "enchantment.vanillatweaks.homing.desc": "Your arrows will aim right at your target.",

2022-05-08 02:11 UTC, AnzhiZhang commented on projects/1.16/assets/vanillatweaks/vanillatweaks/lang/zh_cn.json
> +  "enchantment.vanillatweaks.homing.desc": "作用于弓上，你的箭会自动瞄准你的目标",
作用于xx是官中的
```suggestion
  "enchantment.vanillatweaks.nimble.desc": "作用于靴子上，每一级都会增加一些移动速度。",
  "enchantment.vanillatweaks.hops.desc": "作用于靴子上，每一级都会增加一些跳跃高度。",
  "enchantment.vanillatweaks.vigor.desc": "作用于胸甲上，每一级都会增加一颗心的生命上限。",
  "enchantment.vanillatweaks.veteran.desc": "作用于头盔上，可以吸引以你为中心的32格半径球体以内的经验。",
  "enchantment.vanillatweaks.blazing.desc": "作用于工具上，自动熔炼矿物。",
  "enchantment.vanillatweaks.siphon.desc": "所有掉落的矿物会立即进入你的物品栏。",
  "enchantment.vanillatweaks.homing.desc": "作用于弓上，你的箭会自动瞄准你的目标。",
```

2022-05-08 02:11 UTC, AnzhiZhang commented on projects/1.16/assets/vanillatweaks/vanillatweaks/lang/zh_cn.json
> +  "enchantment.vanillatweaks.homing.desc": "作用于弓上，你的箭会自动瞄准你的目标",
游戏内看了一下，这些内容好像没用到

2022-05-08 04:35 UTC, mamaruo commented on projects/1.16/assets/vanillatweaks/vanillatweaks/lang/zh_cn.json
> +  "enchantment.vanillatweaks.homing.desc": "作用于弓上，你的箭会自动瞄准你的目标",
这是给[附魔描述](https://github.com/Darkhax-Minecraft/Enchantment-Descriptions)模组用的。

**官中都是（    ）**——仙人掌
![image](https://user-images.githubusercontent.com/37480168/167281874-3c64074e-259b-44ac-8f1f-dbb7fd197b1d.png)

2022-05-08 04:50 UTC, AnzhiZhang commented on projects/1.16/assets/vanillatweaks/vanillatweaks/lang/zh_cn.json
> +  "enchantment.vanillatweaks.homing.desc": "作用于弓上，你的箭会自动瞄准你的目标",
官中1.16.5的中文文件是有 `作用于xxx` 上的

2022-05-08 05:03 UTC, AnzhiZhang commented on projects/1.16/assets/vanillatweaks/vanillatweaks/lang/zh_cn.json
> +  "enchantment.vanillatweaks.homing.desc": "作用于弓上，你的箭会自动瞄准你的目标",
![image](https://user-images.githubusercontent.com/37402126/167282579-4198166b-6fe3-4899-ad18-ce43b581033e.png)
确实是附魔描述mod的

2022-05-08 07:12 UTC, mamaruo commented on projects/1.16/assets/vanillatweaks/vanillatweaks/lang/zh_cn.json
> +  "enchantment.vanillatweaks.homing.desc": "作用于弓上，你的箭会自动瞄准你的目标",
>《译者的任务》中，在首段本雅明就振臂高呼：“没有哪首诗是为了读者而写，也没有哪幅画是为了观赏者而作，更没有哪部交响乐是为了听众而谱。”这是对作者和读者的二元对立的关系的消解，是对作者主体自由能动性的大大提升，作者不需要再考虑读者的因素而进行自由创作，写作的目的也不再是迎合市场或者读者，这对传统的创作理念以及读者与作者的关系都是一种很大的反叛。接着本雅明谈论了原作和译作的关系，给传统的翻译理论当头一棒，<strong>在传统的翻译理论中，“忠实”作为一大翻译标准长期存在，译作并不是独立存在的，他依附于原作基础上，并以尽量准确完整的表达原作的意义和思想为己任。</strong>译者犹如是作者的影子，牢牢的和作者连在一起。而到了本雅明的翻译世界里，译作和译者成了独立于原作和作者的存在，他们的地位甚至高过原作和作者而且拥有了完整的鲜活的生命。“译作因为原作而产生——<strong>然而却不是原作的现世，而是原作的来世……译作总是标志着原作生命的延续……原作的生命之花在其译作中不断获取活力，并以最新、最繁盛的姿态永远盛开下去。</strong>”作为“先锋”的翻译理论，它瞄准传统翻译理论中二元对立的思想，消解作者和译者，原文和译文的对立关系，从而把译者和译作从传统翻译中的依附地位中解放了出来。

[《译者的任务》中的解构主义翻译观 - 科学猫](http://www.scicat.cn/8/wenxuelunwen/20191102/3002823.html)

2022-05-08 07:32 UTC, mamaruo approved these changes

2022-05-08 07:44 UTC, AnzhiZhang commented on projects/1.16/assets/vanillatweaks/vanillatweaks/lang/zh_cn.json
> +  "enchantment.vanillatweaks.homing.desc": "作用于弓上，你的箭会自动瞄准你的目标",
很有启发性的观点

2022-05-08 13:35 UTC, n0099 commented on projects/1.16/assets/vanillatweaks/vanillatweaks/lang/zh_cn.json
> +  "enchantment.vanillatweaks.homing.desc": "作用于弓上，你的箭会自动瞄准你的目标",
*哲学的上升*

2022-05-08 13:35 UTC, merged