[M]Nethers delight 1.18.2
CFPAOrg/Minecraft-Mod-Language-Package pull request #1966
Opened 2022-05-08 02:45 UTC by ieofws

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-08 02:49 UTC, n0099 requested changes

2022-05-08 02:49 UTC, n0099 commented on projects/1.18/assets/nethers-delight/nethers_delight/lang/zh_cn.json
> +  "nethersdelight.jei.composition.accelerators": "周围有以下催化物时加快",
```suggestion
  "nethersdelight.jei.composition.accelerators": "周围有下列催化物时会加快速度",
```

2022-05-08 02:49 UTC, n0099 commented on projects/1.18/assets/nethers-delight/nethers_delight/lang/zh_cn.json
> +  "nethersdelight.jei.composition.fluid": "周围有熔岩时加快",
加快什么？

2022-05-08 03:04 UTC, n0099 requested changes

2022-05-08 03:04 UTC, n0099 commented on projects/1.18/assets/nethers-delight/nethers_delight/lang/zh_cn.json
> +  "item.nethersdelight.magma_gelatin": "熔岩吉利丁"
原文是magma而不是lava

2022-05-08 07:37 UTC, ChuijkYahus commented on projects/1.18/assets/nethers-delight/nethers_delight/lang/zh_cn.json
> +  "nethersdelight.jei.composition": "成分",
```suggestion
  "nethersdelight.jei.composition": "堆肥",
```

2022-05-14 22:26 UTC, Cyl18 commented
/mv "projects/1.18/assets/nethers-delight/nethers_delight/" "projects/1.18/assets/nethers-delight/nethersdelight/"

2022-05-15 02:44 UTC, AnzhiZhang reviewed
这个模组有1.16，建议保持译名统一

2022-05-18 23:02 UTC, n0099 commented
支持与116统一

2022-06-01 16:36 UTC, mamaruo commented
作者多日未回应，且有人有意接手，打算关闭本PR

2022-06-07 18:19 UTC, closed without merging