[M]Create Confectionery 1.18.2 更新汉化提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1967
Opened 2022-05-08 04:24 UTC by ieofws

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-08 06:01 UTC, n0099 requested changes

2022-05-08 06:01 UTC, n0099 commented on projects/1.18/assets/create-confectionery/create_confectionery/lang/zh_cn.json
> +  "item.create_confectionery.little_gingerbread_man_spawn_egg": "姜饼人刷怪蛋",
```suggestion
  "item.create_confectionery.little_gingerbread_man_spawn_egg": "小姜饼人刷怪蛋",  
```

2022-05-08 11:13 UTC, Cyl18 commented
建议分PR提交

2022-05-08 13:42 UTC, n0099 requested changes

2022-05-08 13:42 UTC, n0099 commented on projects/1.18/assets/little-logistics/zh_cn.json
> +  "item.littlelogistics.creative_capacitor": "创造电容器",
```suggestion
  "item.littlelogistics.creative_capacitor": "创造模式电容器",
```

2022-05-10 08:57 UTC, ChuijkYahus commented
话说现在这个pr是littlelogistics的翻译吗

2022-05-10 09:47 UTC, ChuijkYahus requested changes
粗略看了一下
还需要再改改

2022-05-10 09:47 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/zh_cn.json
> +  "block.littlelogistics.rapid_hopper": "快速料斗",
```suggestion
  "block.littlelogistics.rapid_hopper": "快速漏斗",
```

2022-05-10 09:47 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/zh_cn.json
> +  "item.littlelogistics.tug_route": "拖船航线",
```suggestion
  "item.littlelogistics.tug_route": "航线存储器",
```

2022-05-10 09:47 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/zh_cn.json
> +  "item.littlelogistics.locomotive_route": "机车路线",
```suggestion
  "item.littlelogistics.tug_route": "船舶航线存储器",
  "item.littlelogistics.locomotive_route": "铁路线路存储器",
```
实际上是长得像遥控器一样，用于存储经停站点的物品

2022-05-10 09:47 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/zh_cn.json
> +  "item.littlelogistics.spring": "车链",
```suggestion
  "item.littlelogistics.spring": "连接链条",
```
船和矿车都可以链接
没什么好翻译（

2022-05-10 09:47 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/zh_cn.json
> +  "item.littlelogistics.energy_tug": "能源拖船",
```suggestion
  "item.littlelogistics.energy_tug": "电力拖船",
```
此处没有好翻译（）
下方`Energy`部分也应相应做出修改

2022-05-10 09:47 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/zh_cn.json
> +  "item.littlelogistics.energy_locomotive": "能源火车头",
```suggestion
  "item.littlelogistics.steam_locomotive": "蒸汽机车",
  "item.littlelogistics.energy_locomotive": "电力机车",
```
```suggestion
  "item.littlelogistics.steam_locomotive": "蒸汽火车头",
  "item.littlelogistics.energy_locomotive": "电力火车头",
```
`蒸汽`还是`蒸气`？
`电力`可能会好一点，`火车头`还需再讨论

2022-05-10 09:47 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/zh_cn.json
> +  "item.littlelogistics.energy_locomotive": "能源火车头",
entity部分也应相应做出修改

2022-05-10 09:47 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/zh_cn.json
> +  "block.littlelogistics.vessel_charger": "车载充电器",
```suggestion
  "block.littlelogistics.vessel_charger": "交通工具充电器",
```
电力机车和电力拖船均需
此处没有好翻译（）

2022-05-10 09:47 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/zh_cn.json
> +  "subtitle.littlelogistics.tug_undocking": "拖船驶离"
```suggestion
  "subtitle.littlelogistics.steam_tug_whistle": "蒸汽拖船：鸣笛",
  "subtitle.littlelogistics.tug_docking": "拖船：停泊",
  "subtitle.littlelogistics.tug_undocking": "拖船：驶离"
```

2022-05-10 09:47 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/zh_cn.json
> +  "item.littlelogistics.tug_route.node": "%s. 节点",
```suggestion
  "item.littlelogistics.tug_route.node": "节点%s",
```

2022-05-10 09:47 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/zh_cn.json
> +  "screen.littlelogistics.tug_route.confirm": "存储",
```suggestion
  "screen.littlelogistics.tug_route.confirm": "保存",
```

2022-05-10 09:47 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/zh_cn.json
> +  "block.littlelogistics.vessel_detector": "车辆检测器",
疑似仅适用于船舶

2022-05-10 09:47 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/zh_cn.json
> +  "screen.littlelogistics.tug_route": "拖船航线配置器",
```suggestion
  "screen.littlelogistics.tug_route": "拖船航线配置",
```

2022-05-10 10:33 UTC, n0099 commented
> 警告：你没有启用“维护者可修改 PR 文件”（Allow edits from maintainers）。这可能会对维护者造成不便，请在此页面右方勾选此选项。

2022-05-10 10:53 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/zh_cn.json
> +  "item.littlelogistics.conductors_wrench": "导体扳手",
这里忘记检验对船舶有没有效了（

2022-05-10 21:40 UTC, n0099 commented on projects/1.18/assets/little-logistics/zh_cn.json
> +  "item.littlelogistics.energy_locomotive": "能源火车头",
> “蒸汽机”是利用蒸汽在汽缸内膨胀，推动活塞运动而产生动力的一种发动机，使用的是水蒸气，“蒸汽机”中的“汽”不宜写成“气”。

> “蒸汽锤”指靠水蒸气产生动力的机器锤。“蒸汽锤”也简称为“汽锤”。“汽锤”跟“气锤”不同，“气锤”也叫“空气锤”，指利用压缩空气产生动力的机器锤。(《语言文字报》原主编 杜永道)

http://www.hwjyw.com/resource/content/2011/12/27/22947.shtml

2022-05-10 21:41 UTC, n0099 commented on projects/1.18/assets/little-logistics/zh_cn.json
> +  "item.littlelogistics.energy_locomotive": "能源火车头",
火车头建议改成机车

2022-05-10 21:41 UTC, n0099 commented
> 话说现在这个pr是littlelogistics的翻译吗

是缝合怪

2022-05-12 18:09 UTC, ChuijkYahus requested changes

2022-05-12 18:09 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/zh_cn.json
> +  "block.littlelogistics.car_dock_rail": "列车停靠轨",
```suggestion
  "block.littlelogistics.junction_rail": "接合铁轨",
  "block.littlelogistics.switch_rail": "转辙铁轨",
  "block.littlelogistics.automatic_switch_rail": "自动转辙铁轨",
  "block.littlelogistics.tee_junction_rail": "T形转辙铁轨",
  "block.littlelogistics.automatic_tee_junction_rail": "自动T形转辙铁轨",
  "block.littlelogistics.locomotive_dock_rail": "机车停靠铁轨",
  "block.littlelogistics.car_dock_rail": "列车停靠铁轨",
```

2022-05-12 18:09 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/zh_cn.json
> +  "block.littlelogistics.car_dock_rail": "列车停靠轨",
`铁轨`什么的还是应该和原版统一，除非合成不用铁（个人看法）
`接合铁轨`的实际用途是十字路口，热力中同功能方块`Crossover Rail`译为`渡线铁轨`，RC1.16中没有对应功能铁轨
`T形转辙铁轨`在RC1.16中有`Wye Track`对应功能
`转辙铁轨`在RC1.16中有`Turnout Track`对应功能

2022-05-12 22:01 UTC, n0099 commented on projects/1.18/assets/little-logistics/zh_cn.json
> +  "block.littlelogistics.car_dock_rail": "列车停靠轨",
支持

2022-05-13 07:12 UTC, ChuijkYahus commented
再等2天吧
作者如果没来处理little logistics，我也来弄一份（
我在频道里占过的坑要负责（

2022-05-17 10:42 UTC, ChuijkYahus commented
az
作者还不来
那我就开始 little logistics 和它的附属的翻译了

2022-07-12 04:59 UTC, mamaruo commented on projects/1.18/assets/little-logistics/zh_cn.json
> +  "block.littlelogistics.car_dock_rail": "列车停靠轨",
渡线铁轨 不是十字铁轨，热力的翻译恐不妥

2022-07-12 05:01 UTC, mamaruo commented
PR作者再不来的话就按CC再次分发到其他PR去了

2022-08-24 07:44 UTC, dovisutu commented
`projects/1.18/assets/little-logistics/zh_cn.json` 这路径就......


> PR作者再不来的话就按CC再次分发到其他PR去了

“[on 12 Jul](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1967#issuecomment-1181316341)”
ping @mamaruo

2022-08-27 04:08 UTC, closed without merging