[M]create-cafe 1.18.2 汉化更新，修正汉化文件名及更新部分未汉化完的物品
CFPAOrg/Minecraft-Mod-Language-Package pull request #1970
Opened 2022-05-08 10:59 UTC by ieofws

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-08 13:39 UTC, n0099 requested changes

2022-05-08 13:39 UTC, n0099 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "item.createcafe.oreo_half_raw": "一半的奥利奥生面团",
```suggestion
    "item.createcafe.oreo_half": "半块奥利奥",
    "item.createcafe.oreo_incomplete": "未加工的奥利奥",
    "item.createcafe.oreo_half_raw": "半块奥利奥生面团",
```

2022-05-08 13:39 UTC, n0099 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "tooltip.createcafe.super": "防火 (0:13), 速度 (0:13), 力量 (0:13), 重生 (0:13)",
```suggestion
    "tooltip.createcafe.res": "防火 （0:12）",
    "tooltip.createcafe.regen": "重生 （0:13）",
    "tooltip.createcafe.strength": "力量 （0:10）",
    "tooltip.createcafe.speed": "速度 （0:13）",
    "tooltip.createcafe.super": "防火 （0:13）, 速度 （0:13）, 力量 （0:13）, 重生 （0:13）",
```

2022-05-09 07:49 UTC, Rinko1231 reviewed
请去除所有的“味”。
sweetberry是原版的甜浆果哦。

2022-05-09 07:49 UTC, Rinko1231 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "item.createcafe.cassava_root": "木薯根部",
```suggestion
    "item.createcafe.cassava_root": "木薯根",
```

2022-05-09 07:49 UTC, Rinko1231 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "item.createcafe.tapioca_flour": "木薯粉末",
```suggestion
    "item.createcafe.tapioca_flour": "木薯淀粉",
```

2022-05-09 07:49 UTC, Rinko1231 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "block.createcafe.filling": "填充",
```suggestion
    "block.createcafe.filling": "奥利奥夹心",
```
游戏内是填入奥利奥的流体，这是它唯一的用途。

2022-05-09 07:49 UTC, Rinko1231 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "itemGroup.createCafeTab": "创意咖啡馆模组",
```suggestion
    "itemGroup.createCafeTab": "机械动力：奶茶店",
```
嘛我知道cafe一般是`咖啡馆`，不过cafe广义是指“街边贩售饮料和甜点的小店”，显然这个mod里90%以上的饮品都是奶茶而非咖啡。
创意咖啡馆就更离谱了。

2022-05-09 07:49 UTC, Rinko1231 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "block.createcafe.mana_tea": "充满蓝量的奶茶",
```suggestion
    "item.createcafe.mana_berry_milk_tea": "魔力浆果奶茶",
    "block.createcafe.mana_tea": "魔力浆果奶茶",
```
植物魔法联动物品魔力浆果。

2022-05-09 07:49 UTC, Rinko1231 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "block.createcafe.sweetberry_tea": "甜的蓝莓味奶茶",
```suggestion
    "item.createcafe.sweetberry_milk_tea": "甜浆果奶茶",
    "block.createcafe.sweetberry_tea": "甜浆果奶茶",
```
给我整乐了。

2022-05-09 07:49 UTC, Rinko1231 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "block.createcafe.tamarind_tea": "罗望子果味奶茶",
```suggestion
    "item.createcafe.tamarind_milk_tea": "酸角奶茶",
    "block.createcafe.tamarind_tea": "酸角奶茶",
```

2022-05-09 07:49 UTC, Rinko1231 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "block.createcafe.avocado_tea": "鳄梨味奶茶",
```suggestion
    "item.createcafe.avocado_milk_tea": "牛油果奶茶",
    "block.createcafe.avocado_tea": "牛油果奶茶",
```

2022-05-09 07:49 UTC, Rinko1231 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "item.createcafe.raw_boba": "未加工的珍珠",
```suggestion
    "item.createcafe.boba": "波霸",
    "item.createcafe.raw_boba": "未加工的波霸",
```

2022-05-09 07:49 UTC, Rinko1231 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "item.createcafe.cassava_seeds": "木薯籽",
```suggestion
    "item.createcafe.cassava_seeds": "木薯种子",
```

2022-05-09 07:49 UTC, Rinko1231 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "item.createcafe.mana_tea_bucket": "充满蓝量的奶茶桶",
```suggestion
    "item.createcafe.mana_tea_bucket": "魔力浆果奶茶桶",

```

2022-05-09 07:49 UTC, Rinko1231 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "item.createcafe.filling_bucket": "填充桶",
```suggestion
    "item.createcafe.filling_bucket": "奥利奥夹心桶",
```

2022-05-10 00:06 UTC, n0099 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "block.createcafe.filling": "填充",
扭一扭

2022-05-10 00:07 UTC, n0099 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "itemGroup.createCafeTab": "创意咖啡馆模组",
塘埔冰室

2022-05-10 00:07 UTC, n0099 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "item.createcafe.raw_boba": "未加工的珍珠",
其实差不多

2022-05-10 00:13 UTC, n0099 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "block.createcafe.avocado_tea": "鳄梨味奶茶",
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/1646

2022-05-10 00:19 UTC, n0099 requested changes

2022-05-10 00:19 UTC, n0099 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "block.createcafe.tamarind_tea": "罗望子果奶茶",
```suggestion
    "item.createcafe.tamarind_milk_tea": "酸角奶茶",
    "block.createcafe.tamarind_tea": "酸角奶茶",
```
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1970#discussion_r867725820

2022-05-10 00:19 UTC, n0099 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "item.createcafe.tamarind_tea_bucket": "罗望子果奶茶桶",
```suggestion
    "item.createcafe.tamarind_tea_bucket": "酸角奶茶桶",
```

2022-05-10 09:49 UTC, ChuijkYahus commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "tooltip.createcafe.super": "防火（0:13）, 速度（0:13）, 力量（0:13）, 重生（0:13）",
```suggestion
    "tooltip.createcafe.super": "防火（0:13）, 速度（0:13）, 力量（0:13）, 生命恢复（0:13）",
```
“重生”是怎么弄出来的

2022-05-10 10:32 UTC, n0099 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "tooltip.createcafe.super": "防火（0:13）, 速度（0:13）, 力量（0:13）, 重生（0:13）",
疑似机翻regeneration

2022-05-10 16:37 UTC, mamaruo commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "item.createcafe.mana_tea_bucket": "充满蓝量的奶茶桶",
也许是[魔法值 - Dota 2 Wiki，刀塔百科](https://dota2.fandom.com/zh/wiki/%E9%AD%94%E6%B3%95%E5%80%BC)

2022-05-10 16:41 UTC, mamaruo reviewed
[Minecraft Wiki:译名标准化 - Minecraft Wiki，最详细的我的世界百科](https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96)
建议看看

2022-05-10 21:22 UTC, n0099 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "tooltip.createcafe.regen": "重生（0:13）",
喵 呜 机 是 希 望

2022-05-11 05:48 UTC, Cyl18 commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +    "tooltip.createcafe.regen": "重生（0:13）",
复 读 机 是 希 望

2022-07-19 18:41 UTC, mamaruo commented
/diff

2022-11-17 10:25 UTC, ChuijkYahus commented
同模组pr已入库

2022-11-17 10:25 UTC, closed without merging