提交 pretty-pipes 模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #1972
Opened 2022-05-09 11:37 UTC by creederyj

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-09 15:09 UTC, creederyj commented
这个荧石...官方旧版翻译是萤石

2022-05-10 00:12 UTC, n0099 requested changes

2022-05-10 00:12 UTC, n0099 commented on projects/1.18/assets/pretty-pipes/prettypipes/lang/zh_cn.json
> +  "info.prettypipes.hold_alt": "按住 Alt 请求",
```suggestion
  "info.prettypipes.hold_alt": "按住Alt请求",
```

2022-05-10 00:12 UTC, n0099 commented on projects/1.18/assets/pretty-pipes/prettypipes/lang/zh_cn.json
> +  "info.prettypipes.limit_to_max_off": "不要限制于一堆",
```suggestion
  "info.prettypipes.limit_to_max_off": "不限制堆叠数",
```

2022-05-10 00:12 UTC, n0099 commented on projects/1.18/assets/pretty-pipes/prettypipes/lang/zh_cn.json
> +  "info.prettypipes.shift": "按住 Shift 查看更多信息",
```suggestion
  "info.prettypipes.shift": "按住Shift查看更多信息",

```

2022-05-10 00:12 UTC, n0099 commented on projects/1.18/assets/super-circuit-maker/supercircuitmaker/lang/zh_cn.json
> +  "item.supercircuitmaker.tiny_rgb_redstone": "小撮 RGB 红石",
```suggestion
  "item.supercircuitmaker.tiny_rgb_redstone": "小撮RGB红石",

```

2022-05-10 00:12 UTC, n0099 commented on projects/1.18/assets/super-circuit-maker/supercircuitmaker/lang/zh_cn.json
> +  "item.supercircuitmaker.rgb_redstone_stick": "RGB 红石涂层棒",
```suggestion
  "item.supercircuitmaker.rgb_redstone_stick": "RGB红石涂层棒",

```

2022-05-10 00:12 UTC, n0099 commented on projects/1.18/assets/super-circuit-maker/supercircuitmaker/lang/zh_cn.json
> +  "msg.supercircuitmaker.inspector.mode_block": "选择模式:匹配方块类型"
```suggestion
  "msg.supercircuitmaker.inspector.mode_state": "选择模式：匹配方块状态",
  "msg.supercircuitmaker.inspector.mode_block": "选择模式：匹配方块类型"
```

2022-05-10 00:12 UTC, n0099 commented on projects/1.18/assets/super-circuit-maker/supercircuitmaker/lang/zh_cn.json
> +  "subtitles.supercircuitmaker.place": "BOOP",
字幕的主语是什么

2022-05-10 00:12 UTC, n0099 commented on projects/1.18/assets/wireless-chargers/wirelesschargers/lang/zh_cn.json
> +  "wirelesschargers.screen.stored_energy": "储存的能量: %1$d / %2$d"
```suggestion
  "wirelesschargers.charger.info.blocks": "只能在 %1$dx%1$dx%1$d 的范围给方块充电.",
  "wirelesschargers.charger.info.players": "只能在 %1$dx%1$dx%1$d 的范围给玩家物品充电.",
  "wirelesschargers.charger.info.redstone_mode": "红石模式：%s",
  "wirelesschargers.charger.info.stored_energy": "储存的能量：%1$d / %2$d",
  "wirelesschargers.charger.info.transfer_rate_blocks": "充电速率：每个方块%d",
  "wirelesschargers.charger.info.transfer_rate_players": "充电速率：每个玩家%d",
  "wirelesschargers.screen.highlight_area": "显示区域：%s",
  "wirelesschargers.screen.redstone": "红石模式：%s",
  "wirelesschargers.screen.redstone_disabled": "关闭",
  "wirelesschargers.screen.redstone_high": "红石模式：高",
  "wirelesschargers.screen.redstone_low": "红石模式：低",
  "wirelesschargers.screen.stored_energy": "储存的能量：%1$d / %2$d"
```

2022-05-10 00:35 UTC, creederyj commented on projects/1.18/assets/super-circuit-maker/supercircuitmaker/lang/zh_cn.json
> +  "subtitles.supercircuitmaker.place": "BOOP",
一个红石电路的小型音符盒吧，BOOP因该是拟声词，音符盒是booper

2022-05-10 00:44 UTC, n0099 commented on projects/1.18/assets/super-circuit-maker/supercircuitmaker/lang/zh_cn.json
> +  "subtitles.supercircuitmaker.place": "BOOP",
```suggestion
  "subtitles.supercircuitmaker.place": "小型音符盒：BOOP",
```

2022-05-10 00:46 UTC, n0099 approved these changes

2022-05-10 00:54 UTC, creederyj commented on projects/1.18/assets/super-circuit-maker/supercircuitmaker/lang/zh_cn.json
> +  "subtitles.supercircuitmaker.place": "BOOP",
不确定（再说我音符盒也没翻译）

2022-05-10 01:31 UTC, n0099 approved these changes

2022-05-10 04:37 UTC, n0099 approved these changes

2022-05-10 10:33 UTC, n0099 approved these changes

2022-05-10 16:29 UTC, mamaruo requested changes

2022-05-10 16:29 UTC, mamaruo commented on projects/1.16/assets/framedblocks/framedblocks/lang/zh_cn.json
> +    "block.framedblocks.framed_double_slab": "双半砖框架",
台阶

2022-05-10 16:29 UTC, mamaruo commented on projects/1.18/assets/pretty-pipes/prettypipes/lang/zh_cn.json
> +  "info.prettypipes.limit_to_max_off": "不限制堆叠数",
"info.prettypipes.limit_to_max_on": "Limit to one stack",
  "info.prettypipes.limit_to_max_off": "Don't limit to one stack",
stack 指一“组”物品，这里应该不是指堆叠数
原来的翻译是“堆”，机翻常见词

2022-05-10 16:29 UTC, mamaruo commented on projects/1.18/assets/super-circuit-maker/supercircuitmaker/lang/en_us.json
> +  "key.supercircuitmaker.component_placement_modifier": "Component Placement Modifier",
[修饰键 - 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/%E4%BF%AE%E9%A5%B0%E9%94%AE)

2022-05-10 21:23 UTC, n0099 commented on projects/1.18/assets/wireless-chargers/wirelesschargers/lang/zh_cn.json
> +  "wirelesschargers.advancement.no_more_cables.description": "打造先进的无线充电器",
先 进 太 阳 能

2022-05-10 23:54 UTC, creederyj commented on projects/1.18/assets/wireless-chargers/wirelesschargers/lang/zh_cn.json
> +  "wirelesschargers.advancement.no_more_cables.description": "打造先进的无线充电器",
啊，这个不是我翻译的，是我帮忙搬一下评论区里别人的翻译，我也没看

2022-05-11 00:13 UTC, creederyj commented on projects/1.18/assets/wireless-chargers/wirelesschargers/lang/zh_cn.json
> +  "wirelesschargers.advancement.no_more_cables.description": "打造先进的无线充电器",
让我反工一下

2022-05-11 03:52 UTC, mamaruo commented
> 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；

![image](https://user-images.githubusercontent.com/37480168/167765633-36102fea-9376-4bd9-8bdc-2e55f3a22520.png)
![image](https://user-images.githubusercontent.com/37480168/167765711-226b74fa-683d-4e96-be33-838558a4c088.png)


### 未见任何版权声明，**剽窃，拒收**。

2022-05-11 04:25 UTC, creederyj commented
我跟他说过了呀

2022-05-11 04:28 UTC, creederyj commented
第二遍我又翻了一遍，怎么翻也是这么说，那怎么办，这个mod我不能翻了？

2022-05-11 04:33 UTC, creederyj commented
剽窃也是得看字数的，字数太少了，而且这还只是翻译而已（我现在和那个人沟通一下，不是有意的）

2022-05-11 05:13 UTC, creederyj commented
我先去掉了，这些过了就行

2022-05-11 05:20 UTC, mamaruo commented
提醒：无特殊情况请Edit评论而不是连发，这会导致垃圾邮件。
![image](https://user-images.githubusercontent.com/37480168/167774225-5a9d9a25-1fdc-4438-9868-3af239a45873.png)

> 第二遍我又翻了一遍
我跟他说过了呀
剽窃也是得看字数的，字数太少了

所以你到底看没看[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)。

> 我给自己找活干

我也是，给自己找活干来反侵权。而且我还是MC百科管理员。

> 我让那个人同意一下行了吧

还是算了，他说`是我自己汉化的，使用deepl和谷歌翻译，然后人工润色，保证了翻译可信度`，用机翻还保证可信度。

2022-05-11 05:40 UTC, creederyj commented
我自己翻的除了个别几个实在不行的都不是机翻，特别是framedblocks，机翻是不会翻成那样的，我已经把无线充电器的文件去掉了
| |
palida
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年5月11日 13:22 |
| 收件人 | ***@***.******@***.***> |
| 主题 | 回复： [CFPAOrg/Minecraft-Mod-Language-Package] [R] FramedBlocks 等4个模组 翻译提交 (PR #1972) |
OK，不过先过了行吗，我血压有点高😓


| |
palida
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年5月11日 13:21 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [CFPAOrg/Minecraft-Mod-Language-Package] [R] FramedBlocks 等4个模组 翻译提交 (PR #1972) |

提醒：无特殊情况请Edit评论而不是连发，这会导致垃圾邮件。


第二遍我又翻了一遍
我跟他说过了呀
剽窃也是得看字数的，字数太少了

所以你到底看没看知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议。

我给自己找活干

我也是，给自己找活干来反侵权。而且我还是MC百科管理员。

我让那个人同意一下行了吧

还是算了，他说是我自己汉化的，使用deepl和谷歌翻译，然后人工润色，保证了翻译可信度，用机翻还保证可信度。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-05-11 05:44 UTC, closed without merging

2022-05-11 08:37 UTC, n0099 commented
#1978