[R][WIP] forgotten treasures 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1975
Opened 2022-05-11 03:09 UTC by MrFlight233

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2022-05-12 06:42 UTC, MrFlight233 commented
Daminst 这个效果我不是很清楚应该如何翻译

2022-05-12 21:59 UTC, n0099 commented
游戏内是什么样的

2022-06-10 17:18 UTC, mamaruo requested changes

2022-06-10 17:18 UTC, mamaruo commented on projects/1.16/assets/forgotten-treasures/forgotten_treasures/lang/zh_cn.json
> +  "item.forgotten_treasures.inviball_spawn_egg": "入侵球蛋",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   原版标准译名   |
```suggestion
  "item.forgotten_treasures.inviball_spawn_egg": "入侵球刷怪蛋",
```

2022-06-10 17:18 UTC, mamaruo commented on projects/1.16/assets/forgotten-treasures/forgotten_treasures/lang/zh_cn.json
> +  "item.forgotten_treasures.ancient_golem_spawn_egg": "古代傀儡蛋",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |
```suggestion
  "item.forgotten_treasures.ancient_golem_spawn_egg": "古代傀儡刷怪蛋",
```

2022-06-10 17:18 UTC, mamaruo commented on projects/1.16/assets/forgotten-treasures/forgotten_treasures/lang/zh_cn.json
> +  "block.forgotten_treasures.urn": "骨灰翁",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  别字 |
```suggestion
  "block.forgotten_treasures.urn": "骨灰瓮",
```

2022-06-10 17:18 UTC, mamaruo commented on projects/1.16/assets/forgotten-treasures/forgotten_treasures/lang/zh_cn.json
> +  "item.forgotten_treasures.broken_urn_piece": "骨灰翁碎片",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  别字  |
```suggestion
  "item.forgotten_treasures.broken_urn_piece": "骨灰瓮碎片",
```

2022-06-10 17:18 UTC, mamaruo commented on projects/1.16/assets/forgotten-treasures/forgotten_treasures/lang/zh_cn.json
> +  "item.forgotten_treasures.golden_bull_spawn_egg": "金牛蛋",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |
```suggestion
  "item.forgotten_treasures.golden_bull_spawn_egg": "金牛刷怪蛋",
```

2022-06-10 21:57 UTC, n0099 commented on projects/1.16/assets/forgotten-treasures/forgotten_treasures/lang/zh_cn.json
> +  "block.forgotten_treasures.urn": "骨灰翁",
骨灰翁我的我的https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/2008#discussion_r878400266

2022-10-01 03:53 UTC, merged