Pedestals
CFPAOrg/Minecraft-Mod-Language-Package pull request #1976
Opened 2022-05-11 03:32 UTC by Exroia

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-11 08:38 UTC, n0099 approved these changes

2022-05-15 01:18 UTC, n0099 approved these changes

2022-05-15 18:15 UTC, Cyl18 commented
> ❌ pedestals-1.16 的语言文件中有 JSON 语法错误：'"' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 1291 | BytePositionInLine: 2.

2022-05-15 21:46 UTC, n0099 requested changes

2022-05-15 21:46 UTC, n0099 commented on projects/1.16/assets/pedestals/pedestals/lang/zh_cn.json
>    "not.actually.a.thing": "忽视我"
```suggestion
  "not.actually.a.thing": "忽视我",
```

2022-07-26 13:24 UTC, RCqaq requested changes
原翻译有 `燃料发电机` 和 `迪斯尼附魔发电机`（这个翻译属于是哄堂大笑了）
原文：`Energy Generator Upgrade` 和 `Dis Enchantment Generator Upgrade`
建议翻译为：`能量发电升级` 和 `祛魔发电升级`

2022-11-24 04:41 UTC, dovisutu commented on projects/1.16/assets/pedestals/pedestals/lang/zh_cn.json
> +  "jei.pedestals.upgradetool.desc": "配方合成制作，或用标签工具潜行右击空气，直到它转换到升级工具。使用：右击已安装升级的基座来获取关于升级的信息。在副手持有本物品时，点击可从基座上移除升级。",
```suggestion
  "jei.pedestals.upgradetool.desc": "合成制作，或用标签工具潜行右击空气，直到它转换到升级工具。使用：右击已安装升级的基座来获取关于升级的信息。在副手持有本物品时，点击可从基座上移除升级。",
```
按照前面的译法似乎是这样的？

2022-11-24 04:41 UTC, dovisutu commented on projects/1.16/assets/pedestals/pedestals/lang/zh_cn.json
> +  "item.pedestals.bookmagnet": "专一魔咒书(磁引)",
```suggestion
  "item.pedestals.bookmagnet": "专一魔咒书（磁引）",
```
不知道还有没有其他标点不对的

2022-11-24 04:41 UTC, dovisutu commented on projects/1.16/assets/pedestals/pedestals/lang/zh_cn.json
>    "pedestals.upgrade_tooltips.speed_x": "超频：x",
这里是否需要与前面统一？

2022-11-24 04:41 UTC, dovisutu commented on projects/1.16/assets/pedestals/pedestals/lang/zh_cn.json
> +  "jei.pedestals.attack.desc": "攻击基座区域内的实体，在基座下放置一块下界合金块/绿宝石块/钻石块/金块/铁块会改变被攻击的对象。将一把剑放入基座会增加伤害，剑上的锋利/截肢杀手/亡灵杀手附魔都会增加攻击力。（磁性)（可过滤）",
```suggestion
  "jei.pedestals.attack.desc": "攻击基座区域内的实体，在基座下放置一块下界合金块/绿宝石块/钻石块/金块/铁块会改变被攻击的对象。将一把剑放入基座会增加伤害，剑上的锋利/截肢杀手/亡灵杀手附魔都会增加攻击力。（磁性）（可过滤）",
```
~杂交括号......~

2022-11-24 04:41 UTC, dovisutu commented on projects/1.16/assets/pedestals/pedestals/lang/zh_cn.json
> +  "death.attack.pedestal13": "%1$s，变得有洞了，然后就升天了！",
死亡信息末尾要不要加标点？（我印象中原版是没有的，不知道是否要统一）

2022-11-24 04:41 UTC, dovisutu commented on projects/1.16/assets/pedestals/pedestals/lang/zh_cn.json
> +  "jei.pedestals.xpmagnet.desc": "会吸收附近区域内的经验并存储在升级内。也会吸收贴着该基座的玩家的经验。当连接了另一个具有经验升级的基座时，它会把传输经验。",
`它会把传输经验`？

2023-07-30 10:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=1976) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=1976) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Exroia<br/>:x: n0099<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=1976) it.</sub>

2023-08-14 06:25 UTC, Cactusstudent commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

2023-08-27 13:44 UTC, closed without merging