[R] Timeless and classic guns 汉化词条补充提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1979
Opened 2022-05-11 09:21 UTC by MrFlight233

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-11 21:48 UTC, n0099 requested changes

2022-05-11 21:48 UTC, n0099 commented on projects/1.16/assets/timeless-and-classic-guns/tac/lang/zh_cn.json
> +    "item.tac.9mm_box_block": "9mm口径子弹盒",
```suggestion
    "item.tac.nato_556_box_block": "5.56 口径子弹盒",
    "item.tac.9mm_box_block": "9mm 口径子弹盒",
```

2022-05-11 21:48 UTC, n0099 commented on projects/1.16/assets/timeless-and-classic-guns/tac/lang/zh_cn.json
> +    "item.tac.walther_ppk": "沃尔特PPK",
```suggestion
    "item.tac.walther_ppk": "沃尔特 PPK",
```

2022-05-11 21:48 UTC, n0099 commented on projects/1.16/assets/timeless-and-classic-guns/tac/lang/zh_cn.json
> +    "item.tac.m1911_nether": " 地狱1911",
```suggestion
    "item.tac.m1911_nether": " 地狱 M1911",
```
https://en.wikipedia.org/wiki/M1911_pistol

2022-05-11 21:48 UTC, n0099 commented on projects/1.16/assets/timeless-and-classic-guns/tac/lang/zh_cn.json
> +    "item.tac.ar_10": "AR-10射手步枪",
```suggestion
    "item.tac.ar_10": "AR-10 射手步枪",
```

2022-05-11 21:48 UTC, n0099 commented on projects/1.16/assets/timeless-and-classic-guns/tac/lang/zh_cn.json
> +    "minecraft.crosshair.default": "原版",
？

2022-05-11 21:48 UTC, n0099 commented on projects/1.16/assets/timeless-and-classic-guns/tac/lang/zh_cn.json
> +    "perk.tac.vol": "% \u00e6\u017e\u00aa\u00e5\u00a3\u00b0",
```suggestion
    "perk.tac.vol": "% æžªå£°",
```
解码结果

2022-05-11 21:48 UTC, n0099 commented on projects/1.16/assets/timeless-and-classic-guns/tac/lang/zh_cn.json
> +    "block.tac.10_gauge_box_block": "10号霰弹 子弹盒 (x12)",
```suggestion
    "block.tac.box45": ".45 ACP 子弹盒（x16）",
    "block.tac.magnumbox": "马格南子弹盒（x12）",
    "block.tac.win30-30box": ".30 步枪子弹盒（x10）",
    "block.tac.box_308-block": ".308 子弹盒（x50）",
    "block.tac.timeless_workbench": "土制枪械工作台",
    "block.tac.nato_556_box_block": "5.56 子弹盒（x50）",
    "block.tac.9mm_box_block": "9mm 子弹盒（x24）",
    "block.tac.10_gauge_box_block": "10号霰弹 子弹盒（x12）",
```

2022-05-11 21:48 UTC, n0099 commented on projects/1.16/assets/timeless-and-classic-guns/tac/lang/zh_cn.json
> +    "subtitle.tac.fire_dbfire": "霰弹枪开火",
```suggestion
    "subtitle.tac.fire_1911fire": ".45 手枪：开火 ",
    "subtitle.tac.fire_1911fires": "45 手枪消音：开火",
    "subtitle.tac.fire_mosin-nagantfire": "莫辛纳甘步枪：开火",
    "subtitle.tac.fire_30-30fire": ".30 步枪：开火",
    "subtitle.tac.fire_ak74fire": "AK-74：开火",
    "subtitle.tac.fire_ak74fires": "AK-74 消音：开火",
    "subtitle.tac.fire_ak47fire": "AK-47：开火",
    "subtitle.tac.fire_ak47fires": "AK-47 消音：开火",
    "subtitle.tac.fire_dp28fire": "DP-28：开火",
    "subtitle.tac.fire_glockfire": "格洛克：开火",
    "subtitle.tac.fire_glockfires": "格洛克消音：开火",
    "subtitle.tac.fire_m16fire": "AR步枪：开火",
    "subtitle.tac.fire_m16fires": "AR步枪 消音：开火",
    "subtitle.tac.fire_m60fire": "M60：开火",
    "subtitle.tac.fire_m92fsfires": "M9：开火",
    "subtitle.tac.fire_m92fsfire": "M9：开火",
    "subtitle.tac.fire_m1851fire": "M1851 消音：开火",
    "subtitle.tac.fire_tompsonfire": "汤普森冲锋枪：开火",
    "subtitle.tac.fire_dbfire": "霰弹枪：开火",
```

2022-05-12 15:49 UTC, mamaruo reviewed
只是随便看了下，没有认真review

2022-05-12 15:49 UTC, mamaruo commented on projects/1.16/assets/timeless-and-classic-guns/tac/lang/zh_cn.json
> +    "item.minecraft.lingering_potion.effect.deafening": "滞留型 失聪药水",
不要空格

2022-05-12 15:49 UTC, mamaruo commented on projects/1.16/assets/timeless-and-classic-guns/tac/lang/zh_cn.json
> +    "death.attack.tac.bullet.eliminated": "%1$s 抹除了 %2$s",
```suggestion
    "death.attack.tac.bullet.eliminated": "%1$s 干掉了 %2$s",

```

2022-05-12 15:49 UTC, mamaruo commented on projects/1.16/assets/timeless-and-classic-guns/tac/lang/zh_cn.json
> +    "tac.crosshair.dynamic_default": "动态准星",
原文没有 Crosshair，请确认游戏内效果如何

2022-05-12 15:49 UTC, mamaruo commented on projects/1.16/assets/timeless-and-classic-guns/tac/lang/zh_cn.json
> +    "subtitle.tac.grenade.pin": "手雷拔栓",
subtitle 是显示在游戏右下角指示声音的文字，尽量翻译成“声源：声音”，当然并不强求，有些字幕难以做成这个形式。
请检查其他类似的行。

2022-05-12 22:02 UTC, n0099 commented on projects/1.16/assets/timeless-and-classic-guns/tac/lang/zh_cn.json
> +    "death.attack.tac.bullet.eliminated": "%1$s 抹除了 %2$s",
eliminated是军事术语

2022-05-12 22:02 UTC, n0099 commented on projects/1.16/assets/timeless-and-classic-guns/tac/lang/zh_cn.json
> +    "death.attack.tac.bullet.eliminated": "%1$s 抹除了 %2$s",
```suggestion
    "death.attack.tac.bullet.eliminated": "%1$s 清除了 %2$s",
```

2022-05-12 22:03 UTC, n0099 commented
> 另外我不理解随处可见的空格以及n0099上方提出的加空格suggestion

他要加空格那就统一空格，药水同步原版不加空格

2022-07-02 13:37 UTC, n0099 commented
别等pr作者了

2022-11-24 04:58 UTC, dovisutu submitted a review, later dismissed
看起来没有什么问题...？

2022-11-27 11:37 UTC, ChuijkYahus commented on projects/1.16/assets/timeless-and-classic-guns/tac/lang/zh_cn.json
> +    "death.attack.tac.bullet.killed": "%1$放倒了%2$s ",
```suggestion
    "death.attack.tac.bullet.killed": "%1$放倒了%2$s",
```

2022-12-05 10:00 UTC, merged