[R] 提交 Dustrial Decor 模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #1986
Opened 2022-05-13 15:03 UTC by WitherRedstone

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-13 16:56 UTC, n0099 requested changes

2022-05-13 16:56 UTC, n0099 commented on projects/1.18/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.hook": "钩",
```suggestion
    "block.dustrial_decor.hook": "钩子",
```

2022-05-13 16:57 UTC, n0099 approved these changes
锈蚀可以改成生锈的

2022-05-14 09:28 UTC, mamaruo commented
/update-en dustrial-decor 1.18

少了一行，请一并更新中文语言文件

2022-05-14 12:50 UTC, dovisutu reviewed
大致看来没有多大问题
倒不敢说可以Approve，因为还没有细看

2022-05-16 05:25 UTC, Cyl18 commented on projects/1.18/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.large_glow_lantern": "大型辉光灯笼 ",
```suggestion
    "block.dustrial_decor.large_glow_lantern": "大型辉光灯笼",
```

2022-05-16 05:25 UTC, Cyl18 commented on projects/1.18/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "death.attack.sting.player": "{Player} 被刺死"
```suggestion
    "death.attack.sting.player": "{Player} 被刺死了"
```

2022-06-04 04:37 UTC, dovisutu commented on projects/1.18/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.black_light": "黑灯",
怎么感觉有点怪......
估计是我先入为主了（毕竟暂时还没去看游戏效果）
如果这个没有问题的话就可以merge了（？）

2022-06-04 20:17 UTC, n0099 commented on projects/1.18/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.black_light": "黑灯",
```suggestion
    "block.dustrial_decor.black_light": "黑色灯",
```

2022-06-06 11:51 UTC, mamaruo approved these changes

2022-06-06 11:53 UTC, mamaruo commented on projects/1.18/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.sheet_metal_treading_stairs": "钣金踏面楼梯",
这个有点怪
Sheet Metal Treading

2022-06-06 12:00 UTC, n0099 commented on projects/1.18/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.sheet_metal_treading_stairs": "钣金踏面楼梯",
字面意思

2022-06-06 12:05 UTC, merged