[R] Pam's HarvestCraft 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #1987
Opened 2022-05-13 16:51 UTC by ChuijkYahus

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-13 16:52 UTC, ChuijkYahus commented
/update-en pams-harvestcraft-2-food-extended 1.16

2022-05-13 16:56 UTC, n0099 requested changes

2022-05-13 16:56 UTC, n0099 commented on projects/1.16/assets/pams-harvestcraft-2-trees/pamhc2trees/lang/zh_cn.json
> +  "block.pamhc2trees.paperbark_sapling": "千层树苗 ",
```suggestion
  "block.pamhc2trees.paperbark_sapling": "千层树苗",
```

2022-05-13 16:57 UTC, n0099 approved these changes

2022-05-19 10:23 UTC, ChuijkYahus commented
正计划在周末和 PHC 1 mcmod 翻译贡献者进行讨论
暂时不要 merge

2022-06-23 05:37 UTC, ChuijkYahus commented on projects/1.16/assets/pams-harvestcraft-2-food-core/pamhc2foodcore/lang/zh_cn.json
> +  "item.pamhc2foodcore.cookiesandmilkitem": "饼干配牛奶",
`xx配xx`这类译名有必要改一下吗

2022-06-23 05:41 UTC, n0099 commented on projects/1.16/assets/pams-harvestcraft-2-food-core/pamhc2foodcore/lang/zh_cn.json
> +  "item.pamhc2foodcore.cookiesandmilkitem": "饼干配牛奶",
就用xx配xx吧

2022-06-23 13:56 UTC, ChuijkYahus reviewed
第一部分校对 foodextended到300行，其余全部
Co-authored-by: 非公认precure cure vapou <513953903@qq.com>

2022-07-03 03:56 UTC, ChuijkYahus commented
译名统一征求：`Walnut`
潘马斯处原译`胡桃`，作物盛景处原译`核桃`
植物智中查得两者为同一物种：http://www.iplant.cn/info/%E8%83%A1%E6%A1%83
@HaloSense 在QQ群中提议树名为`胡桃`，果实为`核桃`，有维基百科为支撑

2022-07-03 15:47 UTC, n0099 approved these changes

2022-10-22 14:23 UTC, Cactusstudent submitted a review, later dismissed
貌似真的没什么问题呢，但是Food ex是怎么办呢？

2022-10-22 15:12 UTC, ChuijkYahus commented
> 貌似真的没什么问题呢，但是Food ex是怎么办呢？

这个是啥（）

2022-10-27 13:23 UTC, Cactusstudent commented on projects/1.16/assets/pams-harvestcraft-2-food-extended/pamhc2foodextended/lang/zh_cn.json
> +  "item.pamhc2foodextended.stuffedchilipeppersitem": "填馅辣椒",
游戏内做法体现不了“酿”这一做法，所以暂时不选择更改。

2022-10-27 13:23 UTC, Cactusstudent submitted a review, later dismissed

2022-10-27 13:26 UTC, HaloSense commented on projects/1.16/assets/pams-harvestcraft-2-food-extended/pamhc2foodextended/lang/zh_cn.json
> +  "item.pamhc2foodextended.stuffedchilipeppersitem": "填馅辣椒",
“酿，即指在一种原料中夹进、塞进、涂上、包进另一种或几种其他原料，然后加热成菜的方法。”
出自[这里](https://www.xuehua.us/a/5eb52e8786ec4d6195a0a611)

2022-10-27 13:41 UTC, Cyl18 approved these changes

2022-11-10 15:32 UTC, dovisutu approved these changes
这文本量......
最后一次commit的更改应该没有问题，前面的我没法看（

2022-11-10 15:35 UTC, dovisutu commented
可以合了，只要想办法把那两个**coauthor**也加上

2022-11-11 09:12 UTC, merged