[R] Croptopia 和 Croptopia's Chocolaterie 翻译提交与更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #1992
Opened 2022-05-15 12:15 UTC by ChuijkYahus

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-15 21:50 UTC, n0099 approved these changes

2022-05-15 21:50 UTC, n0099 commented on projects/1.18/assets/croptopias-chocolaterie-forge/cacao/lang/zh_cn.json
> +  "item.cacao.nutella" : "能多益",
> 费雷罗的新改进和传播与最初的是不同的，以至于它需要一个新的名字。由于这种传播的主要成分是榛子，费列罗只是在“坚果”一词上加上了拉丁后缀“-ella”顺便说一句，后缀可以翻译为“甜蜜的”、“心爱的”或是一种积极氛围，就这样Nutella诞生了。

2022-06-22 17:05 UTC, Cyl18 commented
/diff

2022-06-23 05:04 UTC, ChuijkYahus commented on projects/1.18/assets/croptopia-fabric/croptopia/lang/zh_cn.json
> +  "info.croptopia.seed": "这种种子会在\n以下生物群系中掉落："
```suggestion
  "info.croptopia.seed": "该种子会在\n以下生物群系中掉落："

```

2022-06-23 05:04 UTC, ChuijkYahus commented on projects/1.18/assets/croptopia-fabric/croptopia/lang/zh_cn.json
> +  "item.croptopia.pecan": "山核桃",
要换回碧根果吗

2022-06-23 05:42 UTC, n0099 commented on projects/1.18/assets/croptopia-fabric/croptopia/lang/zh_cn.json
> +  "item.croptopia.pecan": "山核桃",
改回

2022-10-13 11:19 UTC, IdealNightOcean commented
(<ゝω·)诶嘿

2022-10-14 02:06 UTC, ChuijkYahus commented
> (<ゝω·)诶嘿

话说觉得怎么样，有哪里要改的吗

2022-10-14 02:39 UTC, IdealNightOcean requested changes

2022-10-14 02:40 UTC, IdealNightOcean commented
傻了，昨天就改好了，现在才发现没提交review

2022-10-14 02:43 UTC, ChuijkYahus commented
话说其他译名应该没问题吧（心虚）
这个再放到周日merge
倒是还有一个等了好久的翻译，Create Confectionary（~~*进一步劝诱*~~）

2022-10-14 02:49 UTC, IdealNightOcean commented
没，我看不出别的问题。这版翻译比现在的官译改进了很多，我想是没问题了。
Create Confectionary我中午再看吧，一般我是中午12点和下午17点抽空翻译~~放松~~

2022-10-14 02:51 UTC, ChuijkYahus commented
/mv-recursive "projects/1.18/assets/croptopia-fabric" "projects/1.18/assets/croptopia"

2022-10-14 02:52 UTC, ChuijkYahus commented
> 没，我看不出别的问题。这版翻译比现在的官译改进了很多，我想是没问题了。 Create Confectionary我中午再看吧，一般我是中午12点和下午17点抽空翻译~放松~

多谢
~~*看来我劝诱成功了*~~

2022-10-15 14:26 UTC, Cactusstudent reviewed
看了一遍，没啥问题，专有名词……那我选择摆烂（交给bot万事大吉）

2022-10-16 08:25 UTC, merged