[R]Dustrial Decor 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #1995
Opened 2022-05-18 08:12 UTC by WitherRedstone

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-18 08:12 UTC, WitherRedstone commented
/update-en dustrial-decor 1.16

2022-05-18 08:30 UTC, Cyl18 commented
related: #1986

2022-05-18 09:48 UTC, n0099 approved these changes

2022-06-10 05:28 UTC, RCqaq reviewed
我之前翻译了这个模组，结果发现已经有PR了，但是觉得你的翻译有些地方**可能**需要修改。

2022-06-10 05:28 UTC, RCqaq commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.large_ice_chain": "大型冰链",
```suggestion
    "block.dustrial_decor.large_ice_chain": "粗冰链",
```
这里应该统一名称吧，之前是`粗铁链` `粗金链`

2022-06-10 05:28 UTC, RCqaq commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.black_light": "黑灯",
```suggestion
    "block.dustrial_decor.black_light": "紫外线灯",
```
```suggestion
    "block.dustrial_decor.black_light": "黑光灯",
```
`Black Light` 黑光灯，指不可见光，我游戏内看过应该是`紫外线灯`，或者和原文对应叫`黑光灯`

2022-06-10 05:28 UTC, RCqaq commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.anchor": "锚索",
```suggestion
    "block.dustrial_decor.anchor": "锚",
```

`锚索`（`Anchor Cable`）是指在吊桥中在边孔将主缆进行[锚](https://baike.baidu.com/item/%E9%94%9A)固时，要将主缆分为许多股钢束分别锚于[锚锭](https://baike.baidu.com/item/%E9%94%9A%E9%94%AD/2244789)内，这些钢束便称之为锚索。（摘自百度百科）
这里的`Anchor`就是`锚`

2022-06-10 05:28 UTC, RCqaq commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "item.dustrial_decor.industrial_iron_billet": "工业铁锭",
```suggestion
    "item.dustrial_decor.industrial_iron_billet": "工业铁坯",
```

这里`Billet`应该是`坯`吧，同时也与`Ingot`区分

2022-06-10 05:28 UTC, RCqaq commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "item.dustrial_decor.cast_iron_billet": "铸铁锭",
```suggestion
    "item.dustrial_decor.cast_iron_billet": "铸铁坯",
```

同上

2022-06-10 05:28 UTC, RCqaq commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.chain_link_fence": "链环围栏",
```suggestion
    "block.dustrial_decor.chain_link_fence": "铁丝网围栏",
```

A chain-link fence (also referred to as wire netting, wire-mesh fence, chain-wire fence, cyclone fence, hurricane fence, or diamond-mesh fence) is a type of [woven](https://en.wikipedia.org/wiki/Woven) [fence](https://en.wikipedia.org/wiki/Fence) usually made from [galvanized](https://en.wikipedia.org/wiki/Galvanization) or [LLDPE](https://en.wikipedia.org/wiki/Linear_low-density_polyethylene)-coated [steel](https://en.wikipedia.org/wiki/Steel) wire. （来自英文Wiki）
所以应该是`铁丝网`

2022-06-10 05:28 UTC, RCqaq commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.barbed_chain_link_fence": "带刺链环围栏",
```suggestion
    "block.dustrial_decor.barbed_chain_link_fence": "带刺铁丝网围栏",
```

2022-06-10 05:28 UTC, RCqaq commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.chain_trapdoor": "链环活板门",
```suggestion
    "block.dustrial_decor.chain_trapdoor": "铁丝网活板门",
```

2022-06-10 05:28 UTC, RCqaq commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.chain_door": "链环门",
```suggestion
    "block.dustrial_decor.chain_door": "铁丝网门",
```

2022-06-10 05:28 UTC, RCqaq commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.mini_padded_block": "迷你填充方块",
```suggestion
    "block.dustrial_decor.mini_padded_block": "小方格填充方块",
```

这里**谨慎**修改
游戏内是有小方格图案的方块，看起来像是由小型的填充方块组成的，但`迷你填充方块`可能有歧义

2022-06-10 05:28 UTC, RCqaq commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.mini_padded_vertical_slab": "迷你填充竖直台阶",
```suggestion
    "block.dustrial_decor.mini_padded_vertical_slab": "小方格填充竖直台阶",
```

2022-06-10 05:28 UTC, RCqaq commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.mini_padded_stairs": "迷你填充楼梯",
```suggestion
    "block.dustrial_decor.mini_padded_stairs": "小方格填充楼梯",
```

2022-06-10 05:28 UTC, RCqaq commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.mini_padded_slab": "迷你填充台阶",
```suggestion
    "block.dustrial_decor.mini_padded_slab": "小方格填充台阶",
```

2022-06-10 05:28 UTC, RCqaq commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "death.attack.sting.player": "{Player} 被刺死了"
```suggestion
    "death.attack.barb": "{Player} 被刺死了"
```

模组的key有问题，我在1.16测试的时候key应该是这个

2022-06-10 05:31 UTC, RCqaq commented
@n0099 这模组1.18的PR好像已经merge了，你看看这些有没有必要修改

2022-06-10 07:44 UTC, n0099 commented
#1986 #2034

2022-06-11 16:42 UTC, mamaruo requested changes
> @n0099 这模组1.18的PR好像已经merge了，你看看这些有没有必要修改

都可以改，这边改了同步过去就是

2022-06-11 16:42 UTC, mamaruo commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.cinder_bricks": "煤渣砖",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  原版红砖块 Bricks 下界砖块 Nether Bricks  |
```suggestion
    "block.dustrial_decor.cinder_bricks": "煤渣砖块",
```
原文：**Cinder Bricks**

2022-06-29 08:21 UTC, Demonese commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.wrapped_ice_chains": "包裹的冰链",
游戏内测试时发现找不到对应的物品，但是有可以参考的铁版本，外观如下：
<img width="552" alt="image" src="https://user-images.githubusercontent.com/57629614/176388057-d023ed5c-6667-4b88-afb8-97c2d525a861.png">
应取“缠绕”或“卷起来的”

2022-06-29 08:22 UTC, Demonese commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.wrapped_chains": "包裹的锁链",
游戏内测试时发现其外观如下：
<img width="552" alt="image" src="https://user-images.githubusercontent.com/57629614/176388057-d023ed5c-6667-4b88-afb8-97c2d525a861.png">
应取“缠绕”或“卷起来的”

2022-06-29 08:22 UTC, Demonese commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.wrapped_gold_chains": "包裹的金链",
游戏内测试时发现其外观如下：
![image](https://user-images.githubusercontent.com/57629614/176388653-1dac4aee-2b82-41de-86c3-d97e1f295fec.png)
应取“缠绕”或“卷起来的”

2022-06-29 08:31 UTC, Demonese commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.black_light": "黑灯",
考虑到这是个装饰mod外加对应原文，应使用“黑光灯”
<img width="779" alt="image" src="https://user-images.githubusercontent.com/57629614/176390474-9aa68a33-be57-437d-b6f4-b1d1a3777cc0.png">
<img width="483" alt="image" src="https://user-images.githubusercontent.com/57629614/176390513-e99578b6-14c6-4603-b75f-556a0debe0b4.png">

2022-06-29 08:32 UTC, Demonese commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.anchor": "锚索",
游戏内实测，该物品只能挂在链的末端且只能挂一个，没有“索”
<img width="485" alt="image" src="https://user-images.githubusercontent.com/57629614/176390639-1eb1c3a6-f13c-44d6-ba20-0f7640e4a872.png">

2022-06-29 08:35 UTC, Demonese commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "item.dustrial_decor.industrial_iron_billet": "工业铁锭",
同意换成“坯”
<img width="122" alt="image" src="https://user-images.githubusercontent.com/57629614/176391341-cb8c7ee9-963d-418a-8647-8ff568b10a6c.png">

2022-06-29 08:36 UTC, Demonese commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "item.dustrial_decor.cast_iron_billet": "铸铁锭",
同上

2022-06-29 08:53 UTC, Demonese commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.chain_trapdoor": "链环活板门",
同上

2022-06-29 08:53 UTC, Demonese commented on projects/1.16/assets/dustrial-decor/dustrial_decor/lang/zh_cn.json
> +    "block.dustrial_decor.chain_door": "链环门",
同上

2022-06-29 09:16 UTC, Demonese commented
关于“Padded Block”：
翻译为“填充”有点偏向计算机方面的了，该物品游戏内外观：
<img width="565" alt="image" src="https://user-images.githubusercontent.com/57629614/176399677-bb6c83ac-af0e-40d0-b0b5-6e847a2cd09a.png">
合成方式：
<img width="355" alt="image" src="https://user-images.githubusercontent.com/57629614/176399716-288a6475-e6aa-4809-8afb-eed6547568da.png">
高空摔落下来有弹性，不掉血。
综上所述，应该翻译成软垫。
参考图片：
![image](https://user-images.githubusercontent.com/57629614/176400045-bf233a03-d9f9-4f13-91db-0bb45329009e.png)
至于为什么“Mini”不翻译成“迷你”，是为了避免歧义。

2022-06-29 09:31 UTC, Demonese commented
游戏内测试全部通过，可以合并。
有一些物品在游戏内找不到，怀疑是作者没做完或者要安装联动的mod，但是目前找不到是哪些mod，作者也没写出来。

2022-06-29 09:32 UTC, merged