[R] Chem Lib 汉化更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #1996
Opened 2022-05-18 08:24 UTC by AnzhiZhang

Co-authored-by: 疯子 <1161326997@qq.com>
Co-authored-by: yyq252517 <2352824849@qq.com>

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-19 10:26 UTC, n0099 commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.compound_cocaine_family": "三无可乐",
泛型可乐（迫真）

2022-06-06 18:12 UTC, mamaruo commented
https://github.com/CFPAOrg/TransRules/blob/011ab87f89d3567849ccfb2b806d7ae38322a85d/file/rules.md#08-%E7%89%B9%E6%AE%8A%E5%AD%97%E7%AC%A6

2022-06-06 18:27 UTC, mamaruo requested changes
没有认真看，看着不顺眼就查

2022-06-06 18:27 UTC, mamaruo commented on projects/1.16/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "\u9feb",
https://github.com/CFPAOrg/TransRules/blob/011ab87f89d3567849ccfb2b806d7ae38322a85d/file/rules.md#08-%E7%89%B9%E6%AE%8A%E5%AD%97%E7%AC%A6

2022-06-06 18:27 UTC, mamaruo commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.compound_carbonate": "碳酸",
```suggestion
  "item.chemlib.compound_carbonate": "碳酸盐",
```

2022-06-06 18:27 UTC, mamaruo commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.compound_kaolinite": "高岭土",
```suggestion
  "item.chemlib.compound_kaolinite": "高岭石",
```
https://www.termonline.cn/word/569980/1#s1

2022-06-06 18:27 UTC, mamaruo commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.compound_ammonium": "氨",
```suggestion
  "item.chemlib.compound_ammonium": "铵",
```

2022-06-06 19:26 UTC, n0099 requested changes

2022-06-06 19:26 UTC, n0099 commented on projects/1.16/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "\u9feb",
```suggestion
  "item.chemlib.element_tennessine": "石田",
  "item.chemlib.element_oganesson": "奥气",
```

2022-06-06 19:26 UTC, n0099 commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "\u9feb",
```suggestion
  "item.chemlib.element_tennessine": "石田",
  "item.chemlib.element_oganesson": "奥气",
```

2022-06-06 19:50 UTC, mamaruo commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "\u9feb",
https://github.com/CFPAOrg/TransRules/blob/011ab87f89d3567849ccfb2b806d7ae38322a85d/file/rules.md#08-%E7%89%B9%E6%AE%8A%E5%AD%97%E7%AC%A6

2022-06-06 19:55 UTC, n0099 commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "\u9feb",
您的意思是要加上[[]]？
其实可以不把私有CP（也就是\u9xxx）替换成表中的“翻译文本”，翻译文本的目的是让人类可读的（因为我们自己给私有CP定义的语义在网上也搜不到，脱离了cfpa资源包这个环境这些私有CP就是完全未知的字符）

2022-06-07 04:00 UTC, AnzhiZhang commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "\u9feb",
> https://github.com/CFPAOrg/TransRules/blob/011ab87f89d3567849ccfb2b806d7ae38322a85d/file/rules.md#08-%E7%89%B9%E6%AE%8A%E5%AD%97%E7%AC%A6

我看这部分理解的，是跟我说填 unicode 就可以显示

2022-06-07 04:58 UTC, AnzhiZhang commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "\u9feb",
我的理解是正确的，就是填写unicode
![image](https://user-images.githubusercontent.com/37402126/172299346-7110e56b-1cd9-4412-8678-c38ceb7a6345.png)
![image](https://user-images.githubusercontent.com/37402126/172299386-59507087-82ca-4400-84c5-d9b40a68b285.png)

2022-06-07 05:00 UTC, AnzhiZhang reviewed
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1996#discussion_r890766549

2022-06-07 05:00 UTC, AnzhiZhang commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "奥气",
```suggestion
  "item.chemlib.element_tennessine": "\u9fec",
  "item.chemlib.element_oganesson": "\u9feb",
```

2022-06-07 07:38 UTC, n0099 commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "\u9feb",
@Cyl18 打包系统是不是坏了，他应该在发布release时自动查找替换掉这些

2022-06-07 07:44 UTC, AnzhiZhang commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "\u9feb",
我没用打包的测，直接填的文件

2022-06-07 07:58 UTC, n0099 commented
assign @Cyl18  https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1996#discussion_r890867158

2022-06-07 08:15 UTC, n0099 commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "\u9feb",
改成\u9xxx的私有CP肯定是能正确显示的，除非cfpa以后又改了资源包里的自定义字体图片映射范围
我上面说了改成人类可读的是为了能不进游戏就知道是什么字

2022-06-07 08:17 UTC, n0099 commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "\u9feb",
哦私有CP是\uexxx，9xxx反而是高版本unicode中更新的给这些新字安排的正式CP

2022-06-07 08:19 UTC, n0099 commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "\u9feb",
![](https://user-images.githubusercontent.com/13030387/172331614-43b52987-dc86-4568-afac-358b75863b2f.png)
因此脱离cfpa资源包的环境无法在其他地方被任何字体正确渲染或被人类正确理解为这些字的CP只有标绿色的这些

2022-06-07 08:28 UTC, n0099 commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "\u9feb",
根据文中链接到的943此前写的b站专栏文章的评论区中943的回复：https://www.bilibili.com/read/cv8362858
![](https://user-images.githubusercontent.com/13030387/172332485-6f67e9fe-fd58-42a5-b61d-4f9baa4566e1.png)
我认为使用U+Exxx的私有CP来表达这些字是为了解决mc这套字体图片渲染系统只支持utf-16字符集范围（也就是最大到U+FFFF），比如说𫟼是U+2B7FC https://www.fileformat.info/info/unicode/char/2b7fc/index.htm ，超出了BMP，所以需要我们使用自己定义的私有CP来指代他，而繁体的鐽是U+943D，所以不需要用私有CP指代

2022-06-07 08:36 UTC, n0099 commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "\u9feb",
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/1908
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/cbfb7b6d12658c5b61b847c8c701f948e7dc8e78/src/Packer/Utils.cs#L30-L42
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/22a953dc7814a39090dbf61f8cb3cde296e8efe5/config/fontmap.txt#L1-L16

2022-06-07 08:48 UTC, AnzhiZhang commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "\u9feb",
所以如此麻烦的论证，应该怎么填呢，是否可以把文档改的清晰一些

2022-06-07 09:18 UTC, Cyl18 commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "\u9feb",
看现有库里的怎么填的呗（

2022-06-07 13:01 UTC, n0099 commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "\u9feb",
此系列suggestion已：
**回顾**有关此前设立`cfpa私有unicode CP`的[历史意义](https://www.bilibili.com/read/cv8362858)
**注意到**在chemlib的有关汉化中直接使用了`cfpa私有unicode CP`而非[*翻译规则文档*](https://github.com/CFPAOrg/TransRules/blob/011ab87f89d3567849ccfb2b806d7ae38322a85d/file/rules.md#08-%E7%89%B9%E6%AE%8A%E5%AD%97%E7%AC%A6)中的“翻译文本”
**确认**直接使用`cfpa私有unicode CP`可以在游戏内正确渲染为对应字体图片切片
**认识到**目前译者并不清楚应使用`cfpa私有unicode CP`还是*翻译规则文档*中定义的“翻译文本”
**重申***翻译规则文档*具有权威性引导性，大多数译者都会以此文档作为参考依据
**铭记**943与bakaground在过去4年时间内编写packer，制作资源包自定义字体图片及字宽文件https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/1521#issuecomment-1032332863
**欢迎**包括译者与cfpa新老成员在内的各方对此实现方式提出意见建议
**赞赏地注意到** @AnzhiZhang 所提出的`是否可以把文档改得清晰一些`
**申明**应对*翻译规则文档*做出修订，确认是否需要在汉化文本内使用何种表达形式
**强调**翻译规范文档的映射表中不是以U+Exxx开头的CP不属于`cfpa私有unicode CP`
**重申**不属于`cfpa私有unicode CP`的CP可以直接输入在汉化文本中而不需要以\u开头的转义形式表达（因为如果按照json规范要求，任何非ascii字符包括常用中文汉字都应该\u转义，但译者从未这样做过，这间接证明了读取这些汉化文本的json解析库支持*非转义文本序列*）
**吁请** @Cyl18 重新确认[packer](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/src/Packer/Utils.cs)是否能够继续正常执行替换工作

2022-06-07 13:34 UTC, AnzhiZhang commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "\u9feb",
怎么还有。。。

2022-06-07 13:52 UTC, n0099 requested changes

2022-06-07 13:52 UTC, n0099 commented on projects/1.16/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "奥气",
```suggestion
  "item.chemlib.element_tennessine": "[[石田]]",
  "item.chemlib.element_oganesson": "[[奥气]]",
```

2022-06-07 13:52 UTC, n0099 commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "奥气",
```suggestion
  "item.chemlib.element_tennessine": "[[石田]]",
  "item.chemlib.element_oganesson": "[[奥气]]",
```

2022-06-10 17:01 UTC, mamaruo requested changes
又看了一遍，竟有重大错误

2022-06-10 21:49 UTC, n0099 commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.compound_cocaine_family": "三无可乐",
```suggestion
  "item.chemlib.compound_cocaine_family": "三无仿制可乐",
```

2022-06-12 15:57 UTC, mamaruo requested changes

2022-06-12 15:57 UTC, mamaruo commented on projects/1.16/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.compound_aluminum_nitrate": "硝酸锂",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |
```suggestion
  "item.chemlib.compound_aluminum_nitrate": "硝酸铝",
```

2022-06-12 15:57 UTC, mamaruo commented on projects/1.16/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.compound_han_purple": "硅酸铜钡",
```suggestion
  "item.chemlib.compound_han_purple": "汉紫",
```

2022-06-12 15:57 UTC, mamaruo commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.compound_aluminum_nitrate": "硝酸锂",
```suggestion
  "item.chemlib.compound_aluminum_nitrate": "硝酸铝",
```

2022-06-12 18:46 UTC, n0099 commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.compound_aluminum_nitrate": "硝酸锂",
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/2062#issuecomment-1153243246

2022-06-15 15:48 UTC, n0099 approved these changes

2022-06-15 15:50 UTC, n0099 commented
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/2062#issuecomment-1153243246 都合了这个怎么还没合

2022-06-15 16:04 UTC, mamaruo approved these changes

2022-06-15 17:21 UTC, n0099 commented on projects/1.18/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "\u9feb",
根据6-7时在硅岩社区群与@cyl18a达成的共识：
![image](https://user-images.githubusercontent.com/13030387/173887710-f380b4d6-493f-4973-b96a-9cd2bf4b7627.png)
![image](https://user-images.githubusercontent.com/13030387/173887642-c55ade20-046a-4fd7-827d-4ad5132ba46b.png)
此问题已得到解决

2022-06-15 17:21 UTC, merged