[R] Little Logistics 和 Little Contraptions 1.18 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2001
Opened 2022-05-18 18:52 UTC by ChuijkYahus

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-18 19:31 UTC, n0099 requested changes

2022-05-18 19:31 UTC, n0099 commented on projects/1.18/assets/little-logistics/littlelogistics/lang/zh_cn.json
> +  "screen.littlelogistics.locomotive.route": "已到访：",
已到达？

2022-05-18 19:31 UTC, n0099 commented on projects/1.18/assets/little-logistics/littlelogistics/lang/zh_cn.json
> +  "item.littlelogistics.tug_route.description": "右击将当前位置加入到航线末尾，在同位置再次右击移除节点。潜行时右击打开配置菜单。",
```suggestion
  "item.littlelogistics.tug_route.description": "右击将当前位置加入到航线末尾，在同一位置再次右击移除节点。潜行时右击打开配置菜单。",
```

2022-05-18 19:31 UTC, n0099 commented on projects/1.18/assets/little-logistics/littlelogistics/lang/zh_cn.json
> +  "item.littlelogistics.tug_route.node": "%s. 节点",
```suggestion
  "item.littlelogistics.tug_route.node": "%s 节点",
```

2022-05-18 19:31 UTC, n0099 commented on projects/1.18/assets/little-logistics/littlelogistics/lang/zh_cn.json
> +  "item.littlelogistics.tug_route.removed": "移除节点 X:%s Z:%s",
```suggestion
  "item.littlelogistics.tug_route.added": "添加节点X：%s Z:%s",
  "item.littlelogistics.tug_route.removed": "移除节点X：%s Z:%s",
```

2022-05-18 19:31 UTC, n0099 commented on projects/1.18/assets/little-logistics/littlelogistics/lang/zh_cn.json
> +  "item.littlelogistics.locomotive_route.removed": "移除节点 X:%s Y:%s Z:%s",
```suggestion
  "item.littlelogistics.locomotive_route.added": "添加节点X：%s Y:%s Z:%s",
  "item.littlelogistics.locomotive_route.removed": "移除节点X：%s Y:%s Z:%s",
```

2022-05-18 19:31 UTC, n0099 commented on projects/1.18/assets/little-logistics/littlelogistics/lang/zh_cn.json
> +  "item.littlelogistics.spring.noLoops": "不可将载具连成环状",
```suggestion
  "item.littlelogistics.spring.noLoops": "不能将载具连成环状",
```

2022-05-19 02:18 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/littlelogistics/lang/zh_cn.json
> +  "item.littlelogistics.tug_route.node": "%s. 节点",
这个是序号

2022-05-19 02:21 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/littlelogistics/lang/zh_cn.json
> +  "screen.littlelogistics.locomotive.route": "已到访：",
应该也可以

2022-05-19 15:25 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/littlelogistics/lang/zh_cn.json
> +  "screen.littlelogistics.locomotive.route": "已到访：",
冒号后方显示的是`数字`/`数字`，是在当前循环中已经到达的节点个数/总个数

2022-06-06 18:39 UTC, mamaruo commented on projects/1.18/assets/little-logistics/littlelogistics/patchouli_books/guide/zh_cn/categories/blocks.json
> +  "description": "本模组共有两种方块：码头和导轨。码头用于向船舶装货或从船舶卸货，导轨则应在狭窄的水域使用以防止船舶卡住。",
```suggestion
  "description": "本模组共有两种方块：码头和导轨。码头用于向船舶装货或从船舶卸货，导轨则应在狭窄的水域使用以防止船舶卡住。",
```
guide rail 术语不统一

2022-06-07 00:42 UTC, ChuijkYahus commented
/update-en littlelogistics 1.18
/update-en littlecontraptions 1.18

2022-06-07 00:44 UTC, ChuijkYahus commented
/update-en little-logistics 1.18
/update-en little-contraptions 1.18

2022-06-07 00:55 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/littlelogistics/patchouli_books/guide/zh_cn/categories/blocks.json
> +  "description": "本模组共有两种方块：码头和导轨。码头用于向船舶装货或从船舶卸货，导轨则应在狭窄的水域使用以防止船舶卡住。",
动力的那种放在一格深的水下，相当于给船用的动力铁轨
转向的那种是防止直角转弯卡实体用的
两者都不是原版铁轨的模型
问一下，这里是应该翻译成`导向轨`更佳吗

2022-06-07 07:43 UTC, n0099 commented on projects/1.18/assets/little-logistics/littlelogistics/patchouli_books/guide/zh_cn/categories/blocks.json
> +  "description": "本模组共有两种方块：码头和导轨。码头用于向船舶装货或从船舶卸货，导轨则应在狭窄的水域使用以防止船舶卡住。",
建议继续导轨

2022-06-07 07:44 UTC, n0099 commented on projects/1.18/assets/little-logistics/littlelogistics/patchouli_books/guide/zh_cn/categories/blocks.json
> +  "description": "本模组共有两种方块：码头和导轨。码头用于向船舶装货或从船舶卸货，导轨则应在狭窄的水域使用以防止船舶卡住。",
```suggestion
  "description": "本模组共有两种方块：码头和导轨。码头用于向船舶装货或从船舶卸货，导轨则用在狭窄的水域使用以防止船舶卡住。",
```

2022-06-07 14:38 UTC, ChuijkYahus commented
OK我近期找时间同步回去
@RCqaq

2022-06-08 05:01 UTC, mamaruo requested changes
试试我的review模板，模仿@清秋（例如#1481）制作

2022-06-08 05:01 UTC, mamaruo commented on projects/1.18/assets/little-contraptions/littlecontraptions/lang/zh_cn.json
> +  "littlecontraptions.ponder.tug_dock.text_2": "所有码头都需要有一个拖船码头和排成直线的一排驳船码头",
```suggestion
  "littlecontraptions.ponder.tug_dock.text_2": "所有码头都需要有一个拖船码头方块和排成直线的一排驳船码头方块",
```
码头需要码头？
原文：**Every docking station needs to have one tug dock block and a direct line of barge docks blocks**
| 严重程度         | 备注 |
|--------------|----|
| ⚪ 轻微 / 不阻止合并但需三思  |  歧义  |

2022-06-08 07:46 UTC, n0099 commented
review模板又不能直接选（要手动复制粘贴）

2022-06-08 09:40 UTC, ChuijkYahus commented on projects/1.18/assets/little-contraptions/littlecontraptions/lang/zh_cn.json
> +  "littlecontraptions.ponder.loco_dock.text_4": "在铁轨侧面放置漏斗来给列车装载物品",
[https://imgtu.com/i/XrHmzF](url)
确实如此

2022-06-08 12:00 UTC, ChuijkYahus commented on projects/1.18/assets/little-contraptions/littlecontraptions/lang/zh_cn.json
> +  "littlecontraptions.ponder.loco_dock.text_4": "在铁轨侧面放置漏斗来给列车装载物品",
其实个人一直无来由地觉得作者可能是dock和station混用的（

2022-06-10 14:07 UTC, mamaruo commented on projects/1.18/assets/little-contraptions/littlecontraptions/lang/zh_cn.json
> +  "littlecontraptions.ponder.loco_dock.text_4": "在铁轨侧面放置漏斗来给列车装载物品",
dock是由两种铁轨组成的对吗

2022-06-10 14:09 UTC, ChuijkYahus commented on projects/1.18/assets/little-contraptions/littlecontraptions/lang/zh_cn.json
> +  "littlecontraptions.ponder.loco_dock.text_4": "在铁轨侧面放置漏斗来给列车装载物品",
是的，如上图

2022-06-10 21:40 UTC, n0099 commented
挺好

2022-06-11 12:16 UTC, mamaruo commented on projects/1.18/assets/little-contraptions/littlecontraptions/lang/zh_cn.json
> +  "littlecontraptions.ponder.loco_dock.text_4": "在铁轨侧面放置漏斗来给列车装载物品",
支持译为站点

2022-06-26 14:31 UTC, RCqaq reviewed
我来review了
有没有想法给这两个模组取个中文译名
`小小物流` / `小型物流`？
翻译水平比我高多了

2022-06-26 14:31 UTC, RCqaq commented on projects/1.18/assets/little-logistics/littlelogistics/lang/zh_cn.json
> +  "entity.littlelogistics.seater_car": "车厢",
```suggestion
  "entity.littlelogistics.seater_car": "坐式车厢",
```

和`坐式驳船`统一

2022-06-26 14:31 UTC, RCqaq commented on projects/1.18/assets/little-logistics/littlelogistics/lang/zh_cn.json
> +  "entity.littlelogistics.spring": "载具链条",
同步1.16的时候注意，1.16没有机车，这个应该还叫`船舶链条`

2022-06-26 14:31 UTC, RCqaq commented on projects/1.18/assets/little-logistics/littlelogistics/lang/zh_cn.json
> +  "block.littlelogistics.vessel_charger": "载具充能器",
同步1.16的时候注意一下1.16还是`船舶充能器`

2022-06-26 14:31 UTC, RCqaq commented on projects/1.18/assets/little-logistics/littlelogistics/lang/zh_cn.json
> +  "block.littlelogistics.vessel_detector": "船舶传感器",
```suggestion
  "block.littlelogistics.vessel_detector": "载具传感器",
```

`Vehicle` `载具`？

2022-06-26 14:31 UTC, RCqaq commented on projects/1.18/assets/little-logistics/littlelogistics/lang/zh_cn.json
> +  "entity.littlelogistics.spring": "载具链条",
作者1.18没改成`Vehicle`也很神秘

2022-06-26 14:31 UTC, RCqaq commented on projects/1.18/assets/little-logistics/littlelogistics/lang/zh_cn.json
> +  "entity.littlelogistics.spring": "载具链条",
作者1.18没改成`Vehicle`也很神秘

2022-06-26 14:31 UTC, RCqaq commented on projects/1.18/assets/little-logistics/littlelogistics/patchouli_books/guide/zh_cn/categories/vessels.json
> +  "description": "本模组共有两种船舶：驳船（用于完成具体任务）和拖船（用于拖动驳船）。可用钓鱼竿挪开被卡住的船舶（和其他实体类似）。拖船也可用栓绳拖动。请务必在急转弯处使用$(l:vessel_corner_rail)船舶转角导轨$()以防止堵塞。",
```suggestion
  "description": "本模组共有两种船舶：驳船（用于完成具体任务）和拖船（用于拖动驳船）。可用钓鱼竿挪开被卡住的船舶（和其他实体类似）。拖船也可用栓绳拖动。请务必在急转弯处使用$(l:vessel_corner_rail)船舶转角导轨$()以防止船舶卡住。",
```

与上文统一

2022-06-26 14:31 UTC, RCqaq commented on projects/1.18/assets/little-logistics/littlelogistics/patchouli_books/guide/zh_cn/entries/vessel_detector.json
> +      "text": "有船舶处于某给定方向3格以内时发出红石信号。其前方需要有一条直水道。"
```suggestion
      "text": "有船舶处于给定方向3格以内时发出红石信号。其前方需要有一条直水道。"
```

感觉这样更符合中文习惯

2022-06-26 14:35 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/littlelogistics/lang/zh_cn.json
> +  "entity.littlelogistics.seater_car": "车厢",
原文确实没有`Seater`
不过应该也可以吧

2022-06-26 14:37 UTC, ChuijkYahus commented
> 我来review了 有没有想法给这两个模组取个中文译名 `小小物流` / `小型物流`？ 翻译水平比我高多了

中文名完全没有想法（）
感谢审核

2022-07-11 08:41 UTC, ChuijkYahus commented
1.16翻译会另开pr

2022-07-17 17:19 UTC, mamaruo approved these changes
帕秋莉稍微看了下，应该不错，不看了，摆烂

2022-07-17 17:19 UTC, mamaruo commented on projects/1.18/assets/little-logistics/littlelogistics/patchouli_books/guide/zh_cn/entries/fishing_barge.json
> +      "text": "只会在开阔水域放网。加长其航线以防止“水深过浅”和“过度捕捞”现象出现。"
原文有 penalty，是否意味着这两种现象会照成“减产”之类的debuff，现在的翻译没有明确体现这个意思

2022-07-17 17:20 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/littlelogistics/patchouli_books/guide/zh_cn/entries/fishing_barge.json
> +      "text": "只会在开阔水域放网。加长其航线以防止“水深过浅”和“过度捕捞”现象出现。"
游戏内测试效果倒没什么区别，补一句去

2022-07-17 17:24 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/littlelogistics/patchouli_books/guide/zh_cn/entries/fishing_barge.json
> +      "text": "只会在开阔水域放网。加长其航线以防止“水深过浅”和“过度捕捞”现象出现。"
```suggestion
      "text": "只会在开阔水域放网。加长其航线以防水域过浅或过度捕捞导致的减产。"
```

2022-07-17 17:43 UTC, ChuijkYahus reviewed
看着不舒服的句子改了下

2022-07-17 17:43 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/littlelogistics/patchouli_books/guide/zh_cn/categories/blocks.json
> +  "description": "本模组共有两种方块：码头和导轨。码头用于向船舶装货或从船舶卸货，导轨则用在狭窄的水域使用以防止船舶卡住。",
```suggestion
  "description": "本模组共有两种方块：码头和导轨。码头用于向船舶装货或从船舶卸货，导轨则用在狭窄的水域以防止船舶卡住。",
```

2022-07-17 17:43 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/littlelogistics/patchouli_books/guide/zh_cn/categories/trains.json
> +  "description": "各类车厢与矿车类似，不同在于车厢可用$(l:spring)载具链条$()相连。每列列车最多只能有一节机车。",
```suggestion
  "description": "各类车厢与矿车类似，两者不同之处在于车厢可用$(l:spring)载具链条$()相连。每列列车最多只能有一节机车。",
```

2022-07-17 17:43 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/littlelogistics/patchouli_books/guide/zh_cn/entries/chest_barge.json
> +      "text": "该驳船需与拖船相连并在码头停泊以与漏斗交互。"
```suggestion
      "text": "该驳船需与拖船相连，并需在码头停泊以与漏斗交互。"
```

2022-07-17 17:43 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/littlelogistics/patchouli_books/guide/zh_cn/entries/chest_car.json
> +      "text": "该车厢需与机车相连并在装卸铁轨停车以与漏斗交互。"
```suggestion
      "text": "该车厢需与机车相连，并需在装卸铁轨停车以与漏斗交互。"
```

2022-07-17 17:43 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/littlelogistics/patchouli_books/guide/zh_cn/entries/docking_rails.json
> +      "text": "共有两类装卸铁轨：机车装卸铁轨和车厢装卸铁轨。任何装卸站点中必须包含机车装卸铁轨，车厢装卸铁轨则在其后方依次排列。这些铁轨本身不具备物流功能，但它们会识别是否有要装卸的物品并使列车停车等候。也可给予红石信号强制停车。"
```suggestion
      "text": "共有两类装卸铁轨：机车装卸铁轨和车厢装卸铁轨。任何装卸站点中必须包含机车装卸铁轨，车厢装卸铁轨则在其后方依次排列。这些铁轨本身不具备物流功能，但它们会识别有无需要装卸的物品，并依此使列车停车等候。也可给予其红石信号强制停车。"
```

2022-07-17 17:43 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/littlelogistics/patchouli_books/guide/zh_cn/entries/docks.json
> +      "text": "共有两类码头方块：驳船码头和拖船码头。任何码头中必须包含拖船码头。拖船码头和驳船码头所指方向必须一致，由此能建成一座连缀的线形码头。这些码头本身不具备物流功能，但它们会识别是否有要装卸的物品并使船舶停泊等候。也可给予红石信号强制停泊。"
```suggestion
      "text": "共有两类码头方块：驳船码头和拖船码头。任何码头中必须包含一个拖船码头方块。拖船码头和驳船码头所指方向必须一致，从而建成一座连缀的线形码头。这些码头本身不具备物流功能，但它们会识别有无需要装卸的物品，并依此使船舶停泊等候。也可给予红石信号强制停泊。"
```

2022-07-17 17:43 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/littlelogistics/patchouli_books/guide/zh_cn/entries/fluid_barge.json
> +      "text": "使用这类驳船运输流体，可用$(l:fluid_hopper)流体漏斗$()装载卸载。"
```suggestion
      "text": "可用这类驳船运输流体，用$(l:fluid_hopper)流体漏斗$()装载或卸载。"
```

2022-07-17 17:43 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/littlelogistics/patchouli_books/guide/zh_cn/entries/fluid_car.json
> +      "text": "使用这类车厢运输流体，可用$(l:fluid_hopper)流体漏斗$()装载卸载。"
```suggestion
      "text": "可用这类车厢运输流体，用$(l:fluid_hopper)流体漏斗$()装载或卸载。"
```

2022-07-17 17:43 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/littlelogistics/patchouli_books/guide/zh_cn/entries/fluid_hopper.json
> +      "text": "专为流体设计的漏斗，可从上方输入并从四周输出。手持桶右击装入流体。可用于对船舶和列车装载/卸载流体。"
```suggestion
      "text": "专为流体设计的漏斗，可从上方输入并向四周输出。手持桶右击装入流体。可用于给船舶和列车装载/卸载流体。"
```

2022-07-17 17:43 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/littlelogistics/patchouli_books/guide/zh_cn/entries/train_car.json
> +  "name": "车厢",
```suggestion
  "name": "坐式车厢",
```

2022-07-17 17:43 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/littlelogistics/patchouli_books/guide/zh_cn/entries/vessel_charger.json
> +      "text": "$(l:energy_tug)电力拖船$()和$(l:energy_locomotive)电力机车$()的充能器，与任何FE导线相连以接收能量。放置于码头上方或装卸铁轨侧边以充能。"
```suggestion
      "text": "$(l:energy_tug)电力拖船$()和$(l:energy_locomotive)电力机车$()的充能器，与任何FE导线相连以接收能量。放置于码头上方或装卸铁轨侧边以给载具充能。"
```

2022-07-17 17:43 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/littlelogistics/lang/zh_cn.json
> +  "item.littlelogistics.energy_tug": "电力拖船",
此处原文`Energy`，官译那边用的是`能量xx`
如果`电力xx`不妥我这里就改掉吧

2022-07-17 17:51 UTC, mamaruo approved these changes

2022-07-17 17:52 UTC, mamaruo commented on projects/1.18/assets/little-logistics/littlelogistics/lang/zh_cn.json
> +  "item.littlelogistics.energy_tug": "电力拖船",
支持电力

2022-08-24 08:50 UTC, dovisutu approved these changes

2022-08-24 08:51 UTC, merged

2022-08-24 15:51 UTC, iamliuzy commented on projects/1.18/assets/little-logistics/littlelogistics/lang/zh_cn.json
> +  "item.littlelogistics.seater_barge": "坐式驳船",
这里建议改为座椅驳船。

2022-08-24 16:13 UTC, iamliuzy reviewed
整体还可以，但“坐式车厢”和“坐式驳船”建议修改，看起来有点怪。建议改为“载客”。

2022-08-24 16:13 UTC, iamliuzy commented on projects/1.18/assets/little-logistics/littlelogistics/patchouli_books/guide/zh_cn/entries/seater_barge.json
> +  "name": "坐式驳船",
同上，建议改为“载客驳船”

2022-08-24 16:13 UTC, iamliuzy commented on projects/1.18/assets/little-logistics/littlelogistics/patchouli_books/guide/zh_cn/entries/train_car.json
> +  "name": "坐式车厢",
同上，建议改为“载客车厢”

2022-08-24 16:19 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/littlelogistics/lang/zh_cn.json
> +  "item.littlelogistics.seater_barge": "坐式驳船",
啊这，都merge了
新开个pr

2022-08-25 02:34 UTC, iamliuzy commented on projects/1.18/assets/little-logistics/littlelogistics/lang/zh_cn.json
> +  "item.littlelogistics.seater_barge": "坐式驳船",
az

2022-08-25 02:35 UTC, ChuijkYahus commented on projects/1.18/assets/little-logistics/littlelogistics/lang/zh_cn.json
> +  "item.littlelogistics.seater_barge": "坐式驳船",
新pr已经开了