[R] Corail's Tombstone 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #2002
Opened 2022-05-19 03:36 UTC by ChuijkYahus

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-19 03:36 UTC, ChuijkYahus commented
/update-en corail-tombstone 1.16
/update-en corail-tombstone 1.18

2022-05-19 10:27 UTC, n0099 requested changes

2022-05-19 10:27 UTC, n0099 commented on projects/1.16/assets/corail-tombstone/tombstone/lang/zh_cn.json
> +  "tombstone.config.max_xp_lost_page.tooltip": "厄尔多思的遗失之页中所能获取的最大经验",
```suggestion
  "tombstone.config.max_xp_lost_page.tooltip": "从厄尔多思的遗失之页中所能获取的最大经验",
```

2022-05-19 10:27 UTC, n0099 commented on projects/1.18/assets/corail-tombstone/tombstone/lang/zh_cn.json
> +  "tombstone.config.max_xp_lost_page.tooltip": "厄尔多思的遗失之页中所能获取的最大经验",
```suggestion
  "tombstone.config.max_xp_lost_page.tooltip": "从厄尔多思的遗失之页中所能获取的最大经验",
```

2022-05-19 12:28 UTC, n0099 approved these changes

2022-05-21 14:20 UTC, Cyl18 approved these changes

2022-05-21 14:20 UTC, merged