[R] Applied Botanics 和 Applied Mekanistics 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2003
Opened 2022-05-19 04:57 UTC by ChuijkYahus

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-19 04:59 UTC, ChuijkYahus commented
/mv "projects/1.18/assets/applied-botanics/" "projects/1.18/assets/applied-botanics-addon/"

2022-05-19 10:28 UTC, n0099 approved these changes

2022-05-19 10:28 UTC, n0099 commented on projects/1.18/assets/applied-mekanistics/appmek/lang/en_us.json
> +  "itemGroup.appmek": "应用能源丨通用机械附属",
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1989#discussion_r873190287

2022-05-19 12:28 UTC, n0099 commented on projects/1.18/assets/applied-mekanistics/appmek/lang/en_us.json
> +  "itemGroup.appmek": "应用能源丨通用机械附属",
改一下之前ae infinity booster的

2022-05-19 12:31 UTC, n0099 commented on projects/1.18/assets/applied-mekanistics/appmek/lang/en_us.json
> +  "itemGroup.appmek": "应用能源丨通用机械附属",
哦之前已经改了

2022-06-10 18:02 UTC, mamaruo requested changes

2022-06-10 18:02 UTC, mamaruo commented on projects/1.18/assets/applied-mekanistics/appmek/lang/en_us.json
> +  "item.appmek.chemical_storage_cell_256k": "256k-ME化学品储存元件",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   存储   |

https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/bbe42d8fe26ab553960d1e71d90e396fb7a2db80/projects/1.16/assets/applied-energistics-2/appliedenergistics2/lang/zh_cn.json#L677-L680

2022-06-10 18:02 UTC, mamaruo commented on projects/1.18/assets/applied-mekanistics/appmek/lang/en_us.json
> +  "item.appmek.chemical_p2p_tunnel": "P2P通道-化学品",
| **审查级别**    | 备注 |
|--------------|----|
| ⚪ 轻微 / 不阻止合并但需三思  |    |
```suggestion
  "item.appmek.chemical_p2p_tunnel": "P2P通道 - 化学品",
```

2022-06-10 18:02 UTC, mamaruo commented on projects/1.18/assets/applied-botanics-addon/applied-botanics/appbot/lang/zh_cn.json
> +  "item.appbot.mana_p2p_tunnel": "P2P通道-魔力"
| **审查级别**    | 备注 |
|--------------|----|
| ⚪ 轻微 / 不阻止合并但需三思  |    |
```suggestion
  "item.appbot.mana_p2p_tunnel": "P2P通道 - 魔力"
```

2022-06-10 18:04 UTC, ChuijkYahus commented on projects/1.18/assets/applied-mekanistics/appmek/lang/en_us.json
> +  "item.appmek.creative_chemical_cell": "创造型ME化学品储存元件",
完全参照1.18AE2译名

2022-06-10 18:04 UTC, ChuijkYahus commented on projects/1.18/assets/applied-mekanistics/appmek/lang/en_us.json
> +  "item.appmek.chemical_storage_cell_256k": "256k-ME化学品储存元件",
完全参照1.18AE2译名

2022-06-10 18:05 UTC, ChuijkYahus commented on projects/1.18/assets/applied-botanics-addon/applied-botanics/appbot/lang/zh_cn.json
> +  "item.appbot.mana_p2p_tunnel": "P2P通道-魔力"
完全参照1.18AE2译名

2022-06-10 18:10 UTC, ChuijkYahus commented on projects/1.18/assets/applied-mekanistics/appmek/lang/en_us.json
> +  "item.appmek.chemical_storage_cell_256k": "256k-ME化学品储存元件",
悲才发现是另一个问题，改了

2022-06-10 18:19 UTC, ChuijkYahus commented on projects/1.18/assets/applied-mekanistics/appmek/lang/en_us.json
> +  "item.appmek.creative_chemical_cell": "创造型ME化学品储存元件",
也是，不过物品和流体存储元件有“型”
看这个也是实际存东西的就把“型”加上去了

2022-06-10 18:20 UTC, mamaruo commented on projects/1.18/assets/applied-mekanistics/appmek/lang/en_us.json
> +  "item.appmek.creative_chemical_cell": "创造型ME化学品储存元件",
那就这样吧

2022-06-10 18:21 UTC, mamaruo approved these changes

2022-06-10 21:52 UTC, n0099 approved these changes

2022-06-10 21:54 UTC, merged