语言翻译增加
CFPAOrg/Minecraft-Mod-Language-Package pull request #2026
Opened 2022-05-24 03:26 UTC by swk438349194

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2022-05-24 03:48 UTC, n0099 requested changes
所有标点符号都是半角符号

2022-05-24 03:48 UTC, n0099 commented on projects/1.16/assets/kingdom-keys-re-coded/kingdomkeys/lang/zh_cn.json
> +	"item.kingdomkeys.fair_game": "Fair Game",
这些都是引用的塔罗牌名称，可以直接照搬译名

2022-06-04 19:21 UTC, n0099 requested changes

2022-06-04 19:21 UTC, n0099 commented on projects/1.16/assets/kingdom-keys-re-coded/kingdomkeys/lang/zh_cn.json
> +	"key.kingdomkeys.scrolldown": "命令菜单down",
```suggestion
	"key.kingdomkeys.scrollup": "命令菜单上翻",
	"key.kingdomkeys.scrolldown": "命令菜单下翻",
```

2022-06-04 19:21 UTC, n0099 commented on projects/1.16/assets/kingdom-keys-re-coded/kingdomkeys/lang/zh_cn.json
> +	"key.kingdomkeys.scrollactivator": "命令菜单鼠标控制键",
```suggestion
	"key.kingdomkeys.scrollactivator": "命令菜单鼠标控制",
```
因为其他的没有-键后缀

2022-06-04 19:21 UTC, n0099 commented on projects/1.16/assets/kingdom-keys-re-coded/kingdomkeys/lang/zh_cn.json
> +	"itemGroup.kingdomkeys_org_weapons": "王国之心:XIII机关武器",
```suggestion
	"itemGroup.kingdomkeys_misc": "王国之心：杂项",
	"itemGroup.kingdomkeys_keyblades": "王国之心：键刃",
	"itemGroup.kingdomkeys_org_weapons": "王国之心：XIII机关武器",
```

2022-06-04 19:28 UTC, n0099 requested changes

2022-06-04 19:28 UTC, n0099 commented on projects/1.16/assets/kingdom-keys-re-coded/kingdomkeys/lang/zh_cn.json
> +	"gui.menu.accept": "Accept",
```suggestion
	"gui.menu.accept": "接受",
```

2022-06-04 19:28 UTC, n0099 commented on projects/1.16/assets/kingdom-keys-re-coded/kingdomkeys/lang/zh_cn.json
> +	"gui.menu.config.hp_scale": "HP条大小",
```suggestion
	"gui.menu.config.y_dist": "Y 间距",
	"gui.menu.config.sub_x_offset": "子菜单 X 偏移距离",
	"gui.menu.config.header_title": "标题显示",
	"gui.menu.config.text_x_offset": "文本 X 偏移距离",
	"gui.menu.config.hp_scale": "HP 条大小",
```

2022-06-04 19:28 UTC, n0099 commented on projects/1.16/assets/kingdom-keys-re-coded/kingdomkeys/lang/zh_cn.json
> +	"gui.menu.config.hp_per_bar": "HP Per Bar",
```suggestion
	"gui.menu.config.hp_per_bar": "HP/Bar",
```

2022-06-04 19:28 UTC, n0099 commented on projects/1.16/assets/kingdom-keys-re-coded/kingdomkeys/lang/zh_cn.json
> +	"gui.menu.config.show_hearts": "Show hearts on HUD",
```suggestion
	"gui.menu.config.show_hearts": "在 HUD 中显示❤",
```

2022-06-04 19:28 UTC, n0099 commented on projects/1.16/assets/kingdom-keys-re-coded/kingdomkeys/lang/zh_cn.json
> +	"gui.commandmenu.limit": "极限技",
为啥多个-技

2022-06-04 19:28 UTC, n0099 commented on projects/1.16/assets/kingdom-keys-re-coded/kingdomkeys/lang/zh_cn.json
> +	"gui.proofofheart.desc": "使用它离开XIII机关",
```suggestion
	"gui.proofofheart.desc": "使用它以离开 XIII 机关",
```

2022-06-04 19:28 UTC, n0099 commented on projects/1.16/assets/kingdom-keys-re-coded/kingdomkeys/lang/zh_cn.json
> +	"gui.proofofheart.desc2": "你穿着组织的服装是无法使用此物品的",
```suggestion
	"gui.proofofheart.desc2": "当你穿着组织的服装时无法使用此物品",
```

2022-06-04 19:28 UTC, n0099 commented on projects/1.16/assets/kingdom-keys-re-coded/kingdomkeys/lang/zh_cn.json
> +	"gui.org.line1": "穿上了黑色长袍,你现在已经是XIII机关的成员了.",
```suggestion
	"gui.org.line1": "穿上了黑色长袍，你现在已经是 XIII 机关的成员了.",
```

2022-06-04 19:28 UTC, n0099 commented on projects/1.16/assets/kingdom-keys-re-coded/kingdomkeys/lang/zh_cn.json
> +	"gui.org.line4": "你希望成为 %1$s?",
```suggestion
	"gui.org.line4": "你希望成为 %1$s？",
```

2022-06-04 19:28 UTC, n0099 commented on projects/1.16/assets/kingdom-keys-re-coded/kingdomkeys/lang/zh_cn.json
> +	"gui.org.line5": "在你成为组织的一员后,离开组织需要付出一些代价(打倒末影龙获取离开机关的徽章).",
```suggestion
	"gui.org.line5": "在你成为组织的一员后，离开组织需要付出一些代价（打倒末影龙获取离开机关的徽章）。",
```

2022-06-04 19:46 UTC, n0099 requested changes

2022-06-04 19:46 UTC, n0099 commented on projects/1.16/assets/kingdom-keys-re-coded/kingdomkeys/lang/zh_cn.json
> +	"magic.magic_reflect0.name": "防护",
建议加个`：小`后缀

2022-06-04 19:46 UTC, n0099 commented on projects/1.16/assets/kingdom-keys-re-coded/kingdomkeys/lang/zh_cn.json
> +	"reactioncommand.rc_auto_final.name": "Auto Final",
未翻译，建议参考https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/2026/files#diff-3058141838b238d2f1f4802338df67e4906b1764eae52702c5c6bf000a379c28R425-R429

2022-06-04 19:52 UTC, n0099 requested changes

2022-06-04 19:52 UTC, n0099 commented on projects/1.16/assets/kingdom-keys-re-coded/kingdomkeys/lang/zh_cn.json
> +	"disc.duration.desc": "Duration",
```suggestion
	"disc.duration.desc": "时长",
```

2022-06-04 19:52 UTC, n0099 commented on projects/1.16/assets/kingdom-keys-re-coded/kingdomkeys/lang/zh_cn.json
> +	"item.kingdomkeys.xemnas_boots": "杰姆那斯的靴子",
建议不加-的-中缀

2022-06-04 19:52 UTC, n0099 commented on projects/1.16/assets/kingdom-keys-re-coded/kingdomkeys/lang/zh_cn.json
> +	"item.kingdomkeys.ira_boots": "Ira 靴子",
未翻译

2022-06-04 19:52 UTC, n0099 commented on projects/1.16/assets/kingdom-keys-re-coded/kingdomkeys/lang/zh_cn.json
> +	"message.magnet_blox.range": "现在的范围是: %s 格",
```suggestion
	"message.magnet_blox.range": "现在的范围是：%s 格",
```

2022-06-04 19:52 UTC, n0099 commented on projects/1.16/assets/kingdom-keys-re-coded/kingdomkeys/lang/zh_cn.json
> +	"soa.choice.intro.2": "如果你选择其中一个..。",
```suggestion
	"soa.choice.intro.2": "如果你选择了其中一个……",
```

2022-06-04 19:54 UTC, n0099 commented on projects/1.16/assets/kingdom-keys-re-coded/kingdomkeys/lang/zh_cn.json
> +	"key.kingdomkeys.scrolldown": "命令菜单 down",
```suggestion
	"key.kingdomkeys.scrollup": "命令菜单上翻",
	"key.kingdomkeys.scrolldown": "命令菜单下翻",
```

2022-06-25 17:31 UTC, mamaruo commented
/diff

2022-12-22 14:58 UTC, dovisutu commented
- 7+7时限进入第一阶段。从该评论发出的时间开始计时。

ping @swk438349194

2023-07-30 10:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2026) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2026) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: n0099<br/>:x: swk438349194<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2026) it.</sub>

2023-08-15 07:24 UTC, closed without merging