[R] Furnish mod 汉化提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2028
Opened 2022-05-27 18:51 UTC by ChillirCR

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [ ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-05-28 07:16 UTC, n0099 requested changes

2022-05-28 07:16 UTC, n0099 commented on projects/1.18/assets/furnish/furnish/lang/zh_cn.json
> +  "msg.furnish.furniture_too_big": "大小不适合这",
```suggestion
  "msg.furnish.furniture_too_big": "大小不适合放在这",
```

2022-05-28 07:16 UTC, n0099 commented on projects/1.18/assets/furnish/furnish/lang/zh_cn.json
> +  "subtitle.furnish.use_curtain": "窗帘",
```suggestion
  "subtitle.furnish.furniture_open": "家具：打开",
  "subtitle.furnish.furniture_close": "家具：关闭",
  "subtitle.furnish.locker_open": "储物柜：打开",
  "subtitle.furnish.locker_close": "储物柜：关闭",
  "subtitle.furnish.furniture_open_drawers": "抽屉：打开",
  "subtitle.furnish.furniture_close_drawers": "抽屉：关闭",
  "subtitle.furnish.amphora_open": "双耳瓶：打开",
  "subtitle.furnish.amphora_close": "双耳瓶：关闭",
  "subtitle.furnish.door_knock": "某人：敲门",
  "subtitle.furnish.door_knock_iron": "某人：敲铁门",
  "subtitle.furnish.use_curtain": "窗帘：使用",
```

2022-05-29 14:27 UTC, ChillirCR commented
怎么还没过

2022-05-29 14:27 UTC, ChillirCR commented
我俩汉化的都卡住了

2022-05-29 14:33 UTC, ChillirCR commented
改完了怎么不过呢？

2022-05-30 11:24 UTC, n0099 approved these changes

2022-06-10 17:56 UTC, mamaruo requested changes

2022-06-10 17:56 UTC, mamaruo commented on projects/1.18/assets/furnish/furnish/lang/zh_cn.json
> +  "msg.furnish.letter.attachment_removed": "删除附件",
| **审查级别**    | 备注 |
|--------------|----|
| ⚪ 轻微 / 不阻止合并但需三思  |    |
```suggestion
  "msg.furnish.letter.attachment_added": "已把 %s 附到信中",
  "msg.furnish.letter.attachment_removed": "附件已删除",
```
请确认这个massage是不是在这两个操作之后显示的

2022-06-10 17:56 UTC, mamaruo commented on projects/1.18/assets/furnish/furnish/lang/zh_cn.json
> +  "block.furnish.warped_wardrobe": "诡异立柜",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |
我觉得得把“木”加上

2022-06-10 17:56 UTC, mamaruo commented on projects/1.18/assets/furnish/furnish/lang/zh_cn.json
> +  "furnish.furniture_inventory": "家具库存",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   原版标准译名   |
```suggestion
  "furnish.furniture_inventory": "家具物品栏",
```

2022-06-10 21:56 UTC, n0099 commented on projects/1.18/assets/furnish/furnish/lang/zh_cn.json
> +  "block.furnish.warped_wardrobe": "诡异立柜",
```suggestion
  "block.furnish.crimson_drawers": "绯红木抽屉",
  "block.furnish.crimson_cabinet": "绯红木柜",
  "block.furnish.crimson_wardrobe": "绯红木立柜",
  "block.furnish.crimson_chair": "绯红木椅",
  "block.furnish.crimson_stool": "绯红木凳",
  "block.furnish.crimson_table": "绯红木桌",
  "block.furnish.crimson_square_table": "绯红木方桌",
  "block.furnish.crimson_pedestal_table": "绯红木柱脚桌",
  "block.furnish.crimson_shutter": "绯红木百叶窗",
  "block.furnish.crimson_crate": "绯红木板条箱",
  "block.furnish.crimson_bench": "绯红木长椅",
  "block.furnish.crimson_ladder": "绯红木梯子",
  "block.furnish.crimson_log_bench": "绯红木菌柄椅",
  "block.furnish.crimson_shelf": "绯红木架",

  "block.furnish.warped_bench": "诡异木长椅",
  "block.furnish.warped_log_bench": "诡异木菌柄椅",
  "block.furnish.warped_crate": "诡异木板条箱",
  "block.furnish.warped_ladder": "诡异木梯子",
  "block.furnish.warped_cabinet": "诡异木柜",
  "block.furnish.warped_chair": "诡异木椅",
  "block.furnish.warped_drawers": "诡异木抽屉",
  "block.furnish.warped_pedestal_table": "诡异木柱脚桌",
  "block.furnish.warped_shelf": "诡异木架",
  "block.furnish.warped_shutter": "诡异木百叶窗",
  "block.furnish.warped_square_table": "诡异木方桌",
  "block.furnish.warped_stool": "诡异木凳",
  "block.furnish.warped_table": "诡异木桌",
  "block.furnish.warped_wardrobe": "诡异木立柜",
```

2022-06-11 12:13 UTC, mamaruo approved these changes
大体没问题了

2022-06-11 18:02 UTC, merged

2022-06-11 18:29 UTC, mamaruo commented
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/commit/20f7d1dc2577ca212dfe08a4104703728090f818