[R] zensummoning 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2044
Opened 2022-06-05 02:03 UTC by jocemod

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-06-05 04:19 UTC, n0099 requested changes

2022-06-05 04:19 UTC, n0099 commented on projects/1.16/assets/zen-summoning/zensummoning/lang/zh_cn.json
> +  "jei.zensummoning.catalyst.lore": "{\"text\":\"Shift-rightclick with the catalyst once all items are in the altar to begin\", \"color\":\"dark_aqua\"}",
```suggestion
  "jei.zensummoning.catalyst.lore": "{\"text\":\"待所有祭品都在祭坛上后按住Shift并右击水晶即可开始\", \"color\":\"dark_aqua\"}",
```

2022-06-05 04:19 UTC, n0099 commented on projects/1.16/assets/zen-summoning/zensummoning/lang/zh_cn.json
> +  "jei.zensummoning.recipe.altar.weight": "概率: %f",
```suggestion
  "jei.zensummoning.recipe.altar.isCatalystConsumed": "消耗物品：%1$s",
  "jei.zensummoning.recipe.altar.weight": "概率：%f",
```

2022-06-06 12:01 UTC, mamaruo requested changes

2022-06-06 12:01 UTC, mamaruo commented on projects/1.16/assets/zen-summoning/zensummoning/lang/zh_cn.json
> +  "chat.zensummoning.invalid_ingredient": "这不是有效的合成表。",
```suggestion
  "chat.zensummoning.invalid_ingredient": "材料无效。",

```

2022-06-06 12:01 UTC, mamaruo commented on projects/1.16/assets/zen-summoning/zensummoning/lang/zh_cn.json
> +  "chat.zensummoning.unknown_error": "出现未知错误，无法再执行预期的召唤。",
```suggestion
  "chat.zensummoning.unknown_error": "出现未知错误，无法执行预期的召唤。",

```

2022-06-11 12:39 UTC, mamaruo approved these changes

2022-06-11 18:02 UTC, merged