[R] Energy Meter 等多个模组翻译提交&更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #2047
Opened 2022-06-05 07:41 UTC by RCqaq

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

Compact Crafting 翻译更新
Energy Meter 英文语言文件、翻译提交
Immersive Posts 翻译更新
Iron Jetpacks 翻译更新（吐槽一下背包前面的种类没法翻译）
Portality 翻译更新
RFTools Storage 翻译更新
Shrink 翻译更新
Trofers 英语语言文件、翻译提交
Mining Gadgets 翻译更新

2022-06-05 08:44 UTC, n0099 approved these changes

2022-06-05 08:44 UTC, n0099 commented on projects/1.16/assets/compact-crafting/compactcrafting/lang/zh_cn.json
> +  "tooltip.compactcrafting.proxy_unbind_hint": "Shift+右键空气以解除微缩力场绑定。"
```suggestion
  "tooltip.compactcrafting.proxy_bind_hint": "Shift+右击投影仪以绑定微缩力场。",
  "tooltip.compactcrafting.proxy_unbind_hint": "Shift+右击空气以解除微缩力场绑定。"
```

2022-06-05 11:17 UTC, RCqaq commented
/update-en mining-gadgets 1.16

2022-06-05 11:21 UTC, RCqaq commented
/update-en trofers 1.16

2022-06-06 11:16 UTC, mamaruo requested changes
另外，请检查空格：
![image](https://user-images.githubusercontent.com/37480168/172145590-5bf27c30-b3a2-465d-bb60-22bceec9d4a5.png)

2022-06-06 11:16 UTC, mamaruo commented on projects/1.16/assets/portality/portality/lang/zh_cn.json
> +    "portality.gui.portals.page": "页数：",
```suggestion
    "portality.gui.portals.page": "页码：",
```
原文：**PAGE:**

2022-06-06 11:16 UTC, mamaruo commented on projects/1.16/assets/portality/portality/lang/zh_cn.json
> +    "portality.gui.controller.link_active": "活跃",
```suggestion
    "portality.gui.controller.link_active": "激活",
```
1.12.2如此译
原文：**Active**

2022-06-06 11:16 UTC, mamaruo commented on projects/1.16/assets/portality/portality/lang/zh_cn.json
> +    "portality.display.show_name": "显示名称显示",
```suggestion
    "portality.display.hide_name": "隐藏名称",
    "portality.display.show_name": "显示名称",
```
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/f96ab8a3b30d898cf24e9b80615772b5d2b55c6c/projects/1.12.2/assets/portality/portality/lang/zh_cn.lang#L13
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/f96ab8a3b30d898cf24e9b80615772b5d2b55c6c/projects/1.12.2/assets/portality/portality/lang/zh_cn.lang#L18
原文：
  "portality.display.hide_name": "Hide Name Display",
  "portality.display.show_name": "Show Name Display",

2022-06-06 11:56 UTC, n0099 commented on projects/1.16/assets/energymeter/energymeter/lang/zh_cn.json
> +  "label.energymeter.threshold": "T",
可能太长

2022-06-06 12:09 UTC, n0099 commented on projects/1.16/assets/mining-gadgets/mininggadgets/lang/zh_cn.json
> +  "item.mininggadgets.mininggadget_simple":"挖掘小帮手 MK1",
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1829#issuecomment-1096048063

2022-06-06 14:22 UTC, RCqaq commented on projects/1.16/assets/energymeter/energymeter/lang/zh_cn.json
> +  "tooltip.energymeter.number_desc_1": "决定传输速率的显示格式为短整型还是长整型。",
确实，属于是我编程学魔怔了

2022-06-06 14:34 UTC, RCqaq commented on projects/1.16/assets/mining-gadgets/mininggadgets/lang/zh_cn.json
> +  "item.mininggadgets.mininggadget_simple":"挖掘小帮手 MK1",
如Modular Routers里面也有MK1，是否要统一呢（我晚点会交一份这个模组的PR）

2022-06-06 14:44 UTC, n0099 approved these changes

2022-06-06 14:48 UTC, RCqaq commented on projects/1.16/assets/iron-jetpacks/ironjetpacks/lang/zh_cn.json
> +  "tooltip.ironjetpacks.change_throttle": "功率设置为 %s",
引擎和悬停后面接的都是开/关
我觉得可以换成 `引擎 开/关` 和 `悬停模式 开/关` 
功率后面接的百分比所以不需要改：比如说 `功率设置为 80%`

2022-06-06 14:57 UTC, RCqaq commented on projects/1.16/assets/energymeter/energymeter/lang/zh_cn.json
> +  "label.energymeter.threshold": "T",
![`B%@2W~M6LSE 3_)_H{%{7I](https://user-images.githubusercontent.com/52515616/172186666-d2561573-eb8a-496b-be38-aca60d31db8b.png)

我本来就是这么翻译的，但是进游戏看到后面空间不够了，才保留了原文

2022-06-06 17:00 UTC, mamaruo commented on projects/1.16/assets/energymeter/energymeter/lang/zh_cn.json
> +  "label.energymeter.threshold": "T",
OK

2022-06-06 17:03 UTC, mamaruo commented on projects/1.16/assets/mining-gadgets/mininggadgets/lang/zh_cn.json
> +  "item.mininggadgets.mininggadget_simple":"挖掘小帮手 MK1",
统一

2022-06-12 20:36 UTC, Cyl18 approved these changes

2022-06-12 20:36 UTC, Cyl18 commented on projects/1.16/assets/energymeter/energymeter/lang/zh_cn.json
> +  "tooltip.energymeter.action_click": "左键",
原文 Click

2022-06-12 22:22 UTC, n0099 commented on projects/1.16/assets/energymeter/energymeter/lang/zh_cn.json
> +  "tooltip.energymeter.action_click": "左键",
进游戏看看

2022-06-12 22:56 UTC, n0099 requested changes

2022-06-12 22:56 UTC, n0099 commented on projects/1.16/assets/energymeter/energymeter/lang/zh_cn.json
> +  "tooltip.energymeter.action_click": "左键",
```suggestion
  "tooltip.energymeter.action_click": "点击",
```

2022-06-12 22:57 UTC, merged