[R] Allthemodium patchouli 手册
CFPAOrg/Minecraft-Mod-Language-Package pull request #2052
Opened 2022-06-07 05:55 UTC by elementsplayer

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-06-07 07:57 UTC, n0099 requested changes

2022-06-07 07:57 UTC, n0099 commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/dimensions/teleport_pad.json
> +            "text": "传送垫被用于传送到$(l:dimensions/miningdim)挖矿维度$(/c)和$(l:dimensions/otherdim)异界$(/c)。你需要在主副手均为空的状态下对其潜行右击。$(br2)作为说明，$(l:dimensions/miningdim)挖矿维度$(/c)在 ATM6: To The Sky 整合包中被禁用。"
```suggestion
            "text": "传送垫被用于传送到$(l:dimensions/miningdim)挖矿维度$(/c)和$(l:dimensions/otherdim)异界$(/c)。你需要在主副手均为空的状态下对其潜行右击。$(br2)注意$(l:dimensions/miningdim)挖矿维度$(/c)在 ATM6: To The Sky 整合包中已被禁用。"

```

2022-06-07 07:57 UTC, n0099 commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/links/discord.json
> +        "text": "我们的每个整合包都有其单独的 Discord 聊天室，以帮助和一般的讨论。"
```suggestion
        "text": "我们的每个整合包都有其单独的 Discord 聊天室，以进行帮助和一般讨论。"
```

2022-06-07 07:57 UTC, n0099 commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/ore/allthemodium.json
> +        "text": "ATM矿石在海洋生物群系的 Y 5-45 中生成，然而可以挖矿维度中生成在相同高度的任何生物群系。"
```suggestion
        "text": "ATM矿石在海洋生物群系的 Y 5-45 中生成，也可以生成在挖矿维度相同高度范围的任意生物群系中。"
```

2022-06-07 07:57 UTC, n0099 commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/ore/unobtainium.json
> +        "text": "难得素矿石可以在末地高岛生物群系中找到。它在 Y 78 下生成。"
```suggestion
        "text": "难得素矿石可以在末地高岛生物群系中找到。它在 Y 78 以下生成。"
```

2022-06-07 18:01 UTC, Cyl18 commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/ore/unobtainium.json
> +        "text": "难得素矿石可以在末地高岛生物群系中找到。它在 Y 78 下生成。"
有空统一 `Y` `Y坐标` `Y轴` `Y值`...

2022-06-07 18:08 UTC, n0099 commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/ore/unobtainium.json
> +        "text": "难得素矿石可以在末地高岛生物群系中找到。它在 Y 78 下生成。"
那可太多了

2022-06-08 07:10 UTC, mamaruo commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/categories/links.json
> +	"description": "这里有几个链接如果你需要帮助。$(li)Github 适合解决整合包的问题。$(li)Discord 适合与其他人讨论整合包。$(li)Reddit 适合展示建筑和提问问题。",
奇怪的语序和用词，`提问问题`

2022-06-08 07:10 UTC, mamaruo commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/categories/food.json
> +	"description": "allthemodium 中的食品",
大写

2022-06-08 07:40 UTC, n0099 commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/categories/links.json
> +	"description": "这里有几个链接如果你需要帮助。$(li)Github 适合解决整合包的问题。$(li)Discord 适合与其他人讨论整合包。$(li)Reddit 适合展示建筑和提问问题。",
```suggestion
	"description": "这里有几个链接如果你需要帮助。$(li)Github 适合解决整合包的问题。$(li)Discord 适合与其他人讨论整合包。$(li)Reddit 适合展示建筑和提出问题。",
```

2022-06-08 07:40 UTC, n0099 commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/categories/food.json
> +	"description": "allthemodium 中的食品",
```suggestion
	"description": "Allthemodium 中的食品",
```

2022-06-09 10:54 UTC, n0099 approved these changes

2022-06-09 14:16 UTC, mamaruo commented
我只是随便看了两眼，merge还得等等

2022-06-09 18:33 UTC, n0099 commented
我都看完了

2022-06-10 14:45 UTC, Cyl18 requested changes
还没看完，各种不通顺..

2022-06-10 14:45 UTC, Cyl18 commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/categories/dimensions.json
> +	"description": "这将向你显示不同维度的信息。",
```suggestion
	"description": "这将向你显示不同维度的信息",
```

2022-06-10 14:45 UTC, Cyl18 commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/categories/links.json
> +	"description": "这里有几个链接如果你需要帮助。$(li)Github 适合解决整合包的问题。$(li)Discord 适合与其他人讨论整合包。$(li)Reddit 适合展示建筑和提出问题。",
```suggestion
	"description": "如果你需要帮助，这里有几个链接。$(li)GitHub 适合解决整合包的问题。$(li)Discord 适合与其他人讨论整合包。$(li)Reddit 适合展示建筑和提出问题。",
```

2022-06-10 14:45 UTC, Cyl18 commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/categories/misc.json
> +	"description": "杂项物品对于特定类别没有足够的信息",
`Miscellaneous items that don't have enough info for one specific category`

2022-06-10 14:45 UTC, Cyl18 commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/alloys/vibranium_allthemodium.json
> +            "text": "振金-ATM合金是三个合金中最弱的,它是在龙炎锻炉中锻造的。$(br)左槽是振金$(br)右槽是ATM"
```suggestion
            "text": "振金-ATM合金是三个合金中最弱的，它是在龙炎锻炉中锻造的。$(br)左槽是振金$(br)右槽是ATM"
```

2022-06-10 14:45 UTC, Cyl18 commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/food/atmapple.json
> +            "text": "ATM苹果提供 20 点饥饿值和 80 点饱和度。此苹果有以下效果:$(li)快吃$(li)随时可食用$(li)30 秒的伤害吸收 X$(li)30 秒的回复 X"
```suggestion
            "text": "ATM苹果提供 20 点饥饿值和 80 点饱和度。此苹果有以下效果：$(li)快吃$(li)随时可食用$(li)30 秒的伤害吸收 X$(li)30 秒的回复 X"

```

2022-06-10 14:45 UTC, Cyl18 commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/links/github.json
> +        "text": "在 Github 中，你可以查看当前的问题和整合包更新。"
```suggestion
        "text": "在 GitHub 中，你可以查看当前的问题和整合包更新。"
```

2022-06-10 14:45 UTC, Cyl18 commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/links/github.json
> +        "link_text": "Github 链接",
```suggestion
        "link_text": "GitHub 链接",
```

2022-06-10 14:45 UTC, Cyl18 commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/ore/unobtainium.json
> +        "text": "难得素矿石可以在末地高岛生物群系中找到。它在 Y轴坐标 78 以下生成。"
```suggestion
        "text": "难得素矿石可以在末地高岛生物群系中找到。它在 Y 轴坐标 78 以下生成。"
```

2022-06-10 21:42 UTC, n0099 commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/categories/misc.json
> +	"description": "杂项物品对于特定类别没有足够的信息",
信息不足以单独建立类别的杂项物品

2023-07-30 10:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2052) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2052) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: elementsplayer<br/>:x: Cyl18<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2052) it.</sub>

2023-09-12 18:38 UTC, ChuijkYahus reviewed
好多修改其实都是乱改弄出来的
长句的修改可作为参考，不一定要完全按照suggestion来

2023-09-12 18:38 UTC, ChuijkYahus commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/ore/allthemodium.json
> +        "text": "ATM矿石在海洋生物群系的 Y 轴坐标 5-45 中生成，也可以生成在挖矿维度相同高度范围的任意生物群系中。"
```suggestion
        "text": "ATM 矿石在海洋生物群系的 Y 轴坐标 5-45 中生成，也可以生成在挖矿维度相同高度范围的任意生物群系中。"
```

2023-09-12 18:38 UTC, ChuijkYahus commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/misc/tools.json
> +            "text": "镐尖斧有一些独特的作用$(li)制作草径$(li)剥离原木皮$(li)把黑曜石变成哭泣的黑曜石"
```suggestion
            "text": "镐尖斧有一些独特的作用$(li)制作草径$(li)给原木剥皮$(li)把黑曜石变成哭泣的黑曜石"
```

2023-09-12 18:38 UTC, ChuijkYahus commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/misc/barter.json
> +            "text": "和猪灵以物易物对于在游戏早期获得一些好东西很有用。你可以通过丢出金锭与他们进行交易，或者使用金锭右击他们。$(br2)关于添加的交易，请见下一页"
```suggestion
            "text": "猪灵以物易物是游戏早期获得好东西的重要方式。你可以通过丢出金锭与他们进行交易，或者使用金锭右击他们。$(br2)新增的交易请见下一页"
```

2023-09-12 18:38 UTC, ChuijkYahus commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/links/github.json
> +        "text": "在 GitHub 中，你可以查看当前的问题和整合包更新。"
```suggestion
        "text": "在 GitHub 中，你可以查看当前的议题和整合包更新信息。"
```
```suggestion
        "text": "在 GitHub 中，你可以查看当前的 issue 和整合包更新信息。"
```
issue在github自己的文档里都有`问题`和`议题`两种叫法（）

2023-09-12 18:38 UTC, ChuijkYahus commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/food/atmcarrot.json
> +            "text": "ATM胡萝卜提供 40 点饥饿值和 320 点饱和度。此胡萝卜有以下效果：$(li)快吃$(li)随时可食用$(li)30 秒的伤害吸收 X$(li)30 秒的回复 X"
```suggestion
            "text": "ATM胡萝卜提供 40 点饥饿值和 320 点饱和度。此胡萝卜有以下特点：$(li)食用速度快$(li)随时可食用$(li)30 秒的伤害吸收 X$(li)30 秒的生命恢复 X"
```

2023-09-12 18:38 UTC, ChuijkYahus commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/food/atmapple.json
> +            "text": "ATM苹果提供 20 点饥饿值和 80 点饱和度。此苹果有以下效果：$(li)快吃$(li)随时可食用$(li)30 秒的伤害吸收 X$(li)30 秒的回复 X"
```suggestion
            "text": "ATM苹果提供 20 点饥饿值和 80 点饱和度。此苹果有以下效果：$(li)食用速度快$(li)随时可食用$(li)30 秒的伤害吸收 X$(li)30 秒的生命恢复 X"
```

2023-09-12 18:38 UTC, ChuijkYahus commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/dimensions/teleport_pad.json
> +            "text": "传送垫被用于传送到$(l:dimensions/miningdim)挖矿维度$(/c)和$(l:dimensions/otherdim)异界$(/c)。你需要在主副手均为空的状态下对其潜行右击。$(br2)注意，$(l:dimensions/miningdim)挖矿维度$(/c)在 ATM6: To The Sky 整合包中被禁用。"
```suggestion
            "text": "传送垫可将事物传送到$(l:dimensions/miningdim)挖矿维度$(/c)和$(l:dimensions/otherdim)异界$(/c)。在主副手均为空时对其潜行右击才可起效。$(br2)注意，$(l:dimensions/miningdim)挖矿维度$(/c)在 ATM6: To The Sky 整合包中被禁用。"
```

2023-09-12 18:38 UTC, ChuijkYahus commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/dimensions/otherdim.json
> +        "text": "异界是一个非常不友好的维度。所有冰火传说的生物都生成在那里，包括被增强的龙。这里还具有特殊的矿石，与主世界或挖矿维度中的矿石相比，它们会掉落额外的资源。要传送到此维度，请在下界中使用$(l:dimensions/teleport_pad)传送垫$(/c)。"
```suggestion
        "text": "异界是一个非常不友好的维度。所有冰火传说的生物都生成在那里，包括被增强的龙。相较于主世界或挖矿维度中的矿石，这里出现的特殊矿石会掉落额外资源。要传送到此维度，请在下界中使用$(l:dimensions/teleport_pad)传送垫$(/c)。"
```

2023-09-12 18:38 UTC, ChuijkYahus commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/dimensions/miningdim.json
> +        "text": "采矿维度可用于设置矿场进行挖掘。它也可用作测试区域，因为它是一个超平坦的维度。要传送到此维度，请在主世界中使用$(l:dimensions/teleport_pad)传送垫$(/c)。"
```suggestion
        "text": "挖矿维度便于采石场进行挖掘工作。由于其地貌为超平坦，它也可用作测试场所。要传送到此维度，请在主世界中使用$(l:dimensions/teleport_pad)传送垫$(/c)。"
```

2023-09-12 18:38 UTC, ChuijkYahus commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/armour/vibranium.json
> +            "text": "振金盔甲具有与ATM盔甲相同的所有效果，但有显着提高的护甲值，韧性和击退抗性，它还增加了：$(li)免疫凋零$(li)魔法抗性$(li)免疫反胃$(li)升级时会保留其附魔"
```suggestion
            "text": "振金盔甲具有与ATM盔甲相同的所有效果，但其护甲值，盔甲韧性和击退抗性明显较高，它还具有如下特性：$(li)凋零保护$(li)魔法抗性$(li)免疫反胃$(li)升级时会保留其魔咒"
```

2023-09-12 18:38 UTC, ChuijkYahus commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/armour/unobtainium.json
> +            "text": "难得素盔甲具有与振金盔甲相同的所有效果，但有显着提高的护甲值，韧性和击退抗性，它还增加了：$(li)抵御潜影贝漂浮攻击"
```suggestion
            "text": "难得素盔甲具有与振金盔甲相同的所有效果，但其护甲值，盔甲韧性和击退抗性明显较高，它还具有如下特性：$(li)抵御潜影贝飘浮攻击"

```

2023-09-12 18:38 UTC, ChuijkYahus commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/entries/armour/allthemodium.json
> +            "text": "ATM盔甲除了护甲值、韧性和击退抗性之外还有一些效果：$(li)水下呼吸$(li)免疫鞘翅碰撞伤害$(li)免疫所有来自火焰/熔岩的伤害$(li)免疫掉落伤害$(li)当你从下界合金盔甲升级时，它会保留其附魔"
```suggestion
            "text": "除提供护甲值，盔甲韧性和击退抗性之外，ATM盔甲还有一些额外效果：$(li)水下呼吸$(li)免疫鞘翅碰撞伤害$(li)免疫火焰伤害$(li)免疫摔落伤害$(li)从下界合金盔甲升级后保留魔咒"
```

2023-09-12 18:38 UTC, ChuijkYahus commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/categories/alloys.json
> +    "description": "这将向你显示不同合金的信息",
```suggestion
    "description": "此部分主要介绍各种合金的信息",
```

2023-09-12 18:38 UTC, ChuijkYahus commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/categories/armour.json
> +    "description": "这将向你显示不同盔甲的信息",
```suggestion
    "description": "此部分主要介绍各种盔甲的信息",
```

2023-09-12 18:38 UTC, ChuijkYahus commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/categories/dimensions.json
> +	"description": "这将向你显示不同维度的信息",
```suggestion
	"description": "此部分主要介绍各维度的信息",
```

2023-09-12 18:38 UTC, ChuijkYahus commented on projects/1.16/assets/allthemodium/allthemodium/patchouli_books/allthemodium/zh_cn/categories/ore.json
> +	"description": "这将告诉你在哪里可以找到 Allthemodium 模组的特定矿石。$(br2)ATM、振金和难得素是非常稀有的矿石，很难找到。",
```suggestion
	"description": "此部分主要介绍在哪里可以找到 Allthemodium 模组的特定矿石。$(br2)ATM，振金和难得素是非常稀有的矿石，很难找到。",
```

2023-09-30 06:44 UTC, ChuijkYahus commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@elementsplayer

2023-10-08 08:07 UTC, closed without merging