[R] 添加Chem Lib和Dynamic Trees - Quark的汉化，并修正Dynamic Trees - Oh The Biomes You'll Go的汉化
CFPAOrg/Minecraft-Mod-Language-Package pull request #2062
Opened 2022-06-12 08:51 UTC by MrZhang21626

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-06-12 10:34 UTC, Cyl18 commented
related: #1996

2022-06-12 14:01 UTC, n0099 requested changes

2022-06-12 14:01 UTC, n0099 commented on projects/1.16/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.element_oganesson": "Oganesson",
```suggestion
  "item.chemlib.element_tennessine": "[[石田]]",
  "item.chemlib.element_oganesson": "[[奥气]]",
```
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1996#discussion_r891195304

2022-06-12 14:01 UTC, n0099 commented on projects/1.16/assets/chemlib/chemlib/lang/zh_cn.json
> +  "item.chemlib.ingot_oganesson": "Oganesson锭",
```suggestion
  "item.chemlib.ingot_tennessine": "[[石田]]锭",
  "item.chemlib.ingot_oganesson": "[[奥气]]锭",
```
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/1996#discussion_r891195304

2022-06-12 17:39 UTC, mamaruo commented
请删除 ChemLib，#1996 即将合并

对比了你和他的翻译，发现 #1996 中` "item.chemlib.compound_aluminum_nitrate": "硝酸锂"`一行译错，感谢贡献。

2022-06-13 06:44 UTC, mamaruo approved these changes

2022-06-13 06:44 UTC, mamaruo commented on projects/1.16/assets/dynamic-trees-byg/dtbyg/lang/zh_cn.json
> +    "item.dtbyg.joshua_seed": "短叶丝兰种子",
| **审查级别** |
|--------------|
| ℹ️ 信息 / 不阻止合并  |
[短叶丝兰 - 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/%E7%9F%AD%E8%91%89%E7%B5%B2%E8%98%AD)
[Yucca brevifolia - Wikipedia](https://en.wikipedia.org/wiki/Yucca_brevifolia)
```suggestion
    "item.dtbyg.joshua_seed": "短叶丝兰种子",
```
原文：**约书亚种子**

2022-06-13 14:48 UTC, n0099 commented on projects/1.16/assets/dynamic-trees-byg/dtbyg/lang/zh_cn.json
> +    "item.dtbyg.joshua_seed": "短叶丝兰种子",
反正约书亚种子是错的

2022-06-15 15:30 UTC, merged