[R]多个模组的汉化及更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #2063
Opened 2022-06-12 09:28 UTC by mczph

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-06-12 13:58 UTC, n0099 requested changes

2022-06-12 13:58 UTC, n0099 commented on projects/1.12.2/assets/zen-summoning/zensummoning/lang/zh_cn.lang
>  jei.zensummoning.catalyst.lore=将其他需要的物品都放入祭坛之后，手持这个物品Shift右击祭坛开始召唤
重复的key`jei.zensummoning.catalyst.lore`
```suggestion
jei.zensummoning.catalyst.lore=将其他需要的物品都放入祭坛之后，手持这个物品潜行右击祭坛开始召唤
jei.zensummoning.recipe.altar.isCatalystConsumed=消耗催化剂：%1$s
jei.zensummoning.recipe.altar.weight=重量：%f
jei.zensummoning.recipe.altar.entity=%1$dx%2$s
```

2022-06-12 13:58 UTC, n0099 commented on projects/1.12.2/assets/zenscroll/zenscroll/lang/zh_cn.lang
> +zenscroll.jei.notBound=无ZenScroll滚动按键绑定
```suggestion
zenscroll.jei.notBound=未设置ZenScroll滚动按键绑定
```

2022-06-13 06:20 UTC, mamaruo requested changes

2022-06-13 06:20 UTC, mamaruo commented on projects/1.12.2/assets/zen-summoning/zensummoning/lang/zh_cn.lang
> +itemGroup.zensummoning=禅宗召唤
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |
这里的 Zen 应指魔改用的是 ZenScript 脚本
```suggestion
itemGroup.zensummoning=Zen 召唤祭坛
```
原文：**Zen Summoning**

2022-06-13 06:20 UTC, mamaruo commented on projects/1.12.2/assets/zen-summoning/zensummoning/lang/zh_cn.lang
>  tile.altar.name=召唤祭坛
请检查本文件与[1.16](https://github.com/project-interactions/minecraft-mod-language-package/blob/04f50d4dcbff9b985398f09fe26880e2958963ce/projects/1.16/assets/zen-summoning/zensummoning/lang/zh_cn.json)的差异，以便统一翻译（并非必须照搬1.16，给出你的想法即可）。

2022-06-13 06:20 UTC, mamaruo commented on projects/1.12.2/assets/zenscroll/zenscroll/lang/zh_cn.lang
> +zenscroll.config.modifierKey=修改按键
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   既有术语   |
```suggestion
zenscroll.config.modifierKey=修饰键
```
原文：**Modifier Key**

2022-06-13 06:20 UTC, mamaruo commented on projects/1.12.2/assets/zenscroll/zenscroll/lang/zh_cn.lang
> +zenscroll.options.modifier_key=修改滚动按键
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |
```suggestion
zenscroll.options.modifier_key=滚动修饰键
```
原文：**Scroll Modifier Key**

2022-06-13 06:20 UTC, mamaruo commented on projects/1.12.2/assets/zenscroll/zenscroll/lang/zh_cn.lang
> +zenscroll.jei.notBound=无ZenScroll滚动按键绑定
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |
```suggestion
zenscroll.jei.notBound=未绑定ZenScroll修饰键
```

2022-06-13 10:36 UTC, mczph commented on projects/1.12.2/assets/zen-summoning/zensummoning/lang/zh_cn.lang
>  tile.altar.name=召唤祭坛
1.16的水晶是没看出来为啥

2022-06-13 10:42 UTC, mczph commented on projects/1.12.2/assets/tinker-toolcasts/tinkertoolcasts/lang/zh_cn.lang
> +tile.tank_creative.name=§d创造焦黑储罐
![QQ截图20220613184422](https://user-images.githubusercontent.com/103164772/173336751-9d86976c-c355-4447-9e9b-8ce18ea97bbf.png)
是由匠魂的焦黑储罐升级而来，或者说还是叫燃料罐

2022-06-13 10:44 UTC, mczph commented on projects/1.12.2/assets/tinker-toolcasts/tinkertoolcasts/lang/zh_cn.lang
> +tile.tank.tooltip=§7储罐容量： §6%s§7 (§e%d§7/§e%d§7)
![QQ截图20220613184616](https://user-images.githubusercontent.com/103164772/173337038-c6b4a2c5-d2dc-4404-8149-203e989ccefa.png)
显示的是储存的量和总量

2022-06-13 10:49 UTC, mamaruo commented on projects/1.12.2/assets/tinker-toolcasts/tinkertoolcasts/lang/zh_cn.lang
> +tile.tank_creative.name=§d创造焦黑储罐
尊重原文

2022-06-13 10:53 UTC, mamaruo commented on projects/1.12.2/assets/tinker-toolcasts/tinkertoolcasts/lang/zh_cn.lang
> +tile.tank.tooltip=§7储罐容量： §6%s§7 (§e%d§7/§e%d§7)
> 显示的是储存的量和总量

我倾向于`尊重原文`。
当然翻储罐确实有点突兀。
那冒号后面写的是储罐内容物，也不是“容量”吧。
真要意译建议换一个译法。

2022-06-14 10:14 UTC, mczph commented
/update-en zen-summoning 1.12.2

2022-06-14 11:23 UTC, n0099 commented
/update-en zen-summoning 1.12.2

2022-06-14 11:24 UTC, n0099 approved these changes

2022-06-14 11:26 UTC, Cyl18 commented
这是什么神秘fork

2022-06-14 11:28 UTC, n0099 commented
https://github.com/Project-Interactions 看起来是ftbi包的q群的org的repo

2022-06-14 16:12 UTC, mamaruo approved these changes

2022-06-14 18:35 UTC, merged