[R] Beyond Earth 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2092
Opened 2022-06-15 11:57 UTC by Longtianmu

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2022-06-15 14:13 UTC, n0099 commented
/update-en beyond-earth 1.18

2022-06-22 00:31 UTC, Cyl18 commented
/diff

2022-06-23 05:30 UTC, n0099 approved these changes

2022-06-23 05:31 UTC, n0099 commented
> 在执行命令时遇到了问题：Object reference not set to an instance of an object.

2022-07-08 12:20 UTC, Kasualix commented
标点可以改改，很多半角的，包括但不限于[这里](https://github.com/Longtianmu/Minecraft-Mod-Language-Package/blob/67d130b152fd86446ca4fee2856585bf2c673c55/projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json#L76)、[这里](https://github.com/Longtianmu/Minecraft-Mod-Language-Package/blob/67d130b152fd86446ca4fee2856585bf2c673c55/projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json#L289)和[这里](https://github.com/Longtianmu/Minecraft-Mod-Language-Package/blob/67d130b152fd86446ca4fee2856585bf2c673c55/projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json#L225)

2022-07-08 13:38 UTC, Demonese commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "block.beyond_earth.flag_lime": "石灰色旗帜",
```suggestion
  "block.beyond_earth.flag_lime": "黄绿色旗帜",
```

2022-07-08 13:39 UTC, Demonese commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "block.beyond_earth.flag_pink": "粉色旗帜",
```suggestion
  "block.beyond_earth.flag_pink": "粉红色旗帜",
```

2022-07-08 13:47 UTC, Demonese commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "block.beyond_earth.oxygen_bubble_distributor": "氧气泡发生机r",
```suggestion
  "block.beyond_earth.oxygen_bubble_distributor": "氧气泡发生机",
```

2022-07-08 13:51 UTC, Demonese commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "block.beyond_earth.coal_lantern": "煤灯",
这个物品用打火石点燃后会变成原版灯笼，所以“煤灯笼”可能更合适？
```suggestion
  "block.beyond_earth.coal_lantern": "煤灯笼",
```

2022-07-08 13:56 UTC, AnzhiZhang requested changes

2022-07-08 13:56 UTC, AnzhiZhang commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "block.beyond_earth.nasa_workbench": "§dCNSA工作台",
原文 `§dNASA Workbench`，直接改名 `CNSA`
强烈谴责篡改翻译的行为

2022-07-08 14:35 UTC, Demonese commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "container.beyond_earth.coal_generator": "火力发电机",
JEI 查看这个设备，只能给煤炭。
另外你术语能不能统一啊兄弟？
```suggestion
  "container.beyond_earth.coal_generator": "煤炭发电机",
```

2022-07-08 14:37 UTC, Demonese commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "container.beyond_earth.oxygen_bubble_distributor": "供氧仪",
```suggestion
  "container.beyond_earth.oxygen_bubble_distributor": "氧气泡发生机",
```

2022-07-09 11:52 UTC, Cactusstudent reviewed
没开游戏，随便看了看，大概找到了一些问题，以及找出来一些与1.16.5已有翻译不统一的地方（谁翻译的，你现在过来，我一匠魂劈就上去了）
请求审核人员去除ready to merge标签，如果实在不行了，就ready to reject吧

2022-07-09 11:52 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.rocket_t4": "四阶火箭",
请考虑与1.16仓库中的翻译相统一，1.16中的翻译为`级`，而并非`阶`

2022-07-09 11:52 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.netherite_space_boots": "下界合金制太空靴",
考虑到`质`与`制`目前区分尚不明确，请考虑删去此处的`制`

2022-07-09 11:52 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "itemGroup.tab_materials": "超越地平: 材料",
模组是否有官方译名，这`超越地平`多少有点草率
顺带改点东西
```suggestion
  "itemGroup.tab_normal": "超越地平",
  "itemGroup.tab_flags": "超越地平丨旗帜",
  "itemGroup.tab_globes": "超越地平丨星球仪",
  "itemGroup.tab_blocks": "超越地平丨方块",
  "itemGroup.tab_basics": "超越地平丨基本",
  "itemGroup.tab_machines": "超越地平丨机器",
  "itemGroup.tab_spawn_eggs": "超越地平丨刷怪蛋",
  "itemGroup.tab_materials": "超越地平丨材料",
```

2022-07-09 11:52 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "block.beyond_earth.coal_torch": "煤火把",
```suggestion
  "block.beyond_earth.coal_torch": "煤炭火把",
```
此处沿用1.16.5库中翻译

2022-07-09 11:52 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "block.beyond_earth.glacio_lapis_ore": "霜原青金石矿石",
SO，能告诉我霜原是啥星吗？

2022-07-09 11:52 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "fluid.oil": "原油",
```suggestion
  "fluid.beyond_earth.oil": "石油",
  "fluid.oil": "石油",
```
与1.16.5库内翻译保持一致

2022-07-09 11:52 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "entity.beyond_earth.rocket_t4": "四阶火箭",
请考虑与1.16仓库中的翻译相统一，1.16中的翻译为`级`，而并非`阶`

2022-07-09 11:52 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "biome.beyond_earth.glacio_ice_spikes": "霜原冰刺之地",
没搞懂，`Glacio`译作`霜原`是否合适

2022-07-09 11:52 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "advancements.rocket_tier_4_advancement.descr": "§b 最为先进的火箭! 好耶!",
请考虑与1.16仓库中的翻译相统一，1.16中的翻译为`级`，而并非`阶`

2022-07-09 11:52 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "container.entity.beyond_earth.rocket_t4": "四阶火箭",
请考虑与1.16仓库中的翻译相统一，1.16中的翻译为`级`，而并非`阶`

2022-07-09 11:56 UTC, Cactusstudent commented
顺带说一句，别听bot在那瞎胡说，mod domain是对的，boos_tools是1.16.5，在1.18版本早改成beyond_earth了

2022-07-09 12:06 UTC, Cactusstudent reviewed
此次更改大多数标点

2022-07-09 12:06 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "message.beyond_earth.no_fuel": "§c燃油耗尽! §7请为火箭装载§c燃油§7. (§6潜行并右键§7)",
```suggestion
  "message.beyond_earth.no_fuel": "§c燃油耗尽！§7请为火箭装载§c燃油§7。（§6潜行并右键§7）",
```

2022-07-09 12:06 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "message.beyond_earth.hold_space": "§7按住§c空格键减速!",
```suggestion
  "message.beyond_earth.hold_space": "§7按住§c空格键减速！",
```

2022-07-09 12:06 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "gui.beyond_earth.oxygen_bubble_distributor.workingarea.text": "工作范围: %1$sx%2$sx%3$s",
```suggestion
  "gui.beyond_earth.oxygen_bubble_distributor.workingarea.text": "工作范围：%1$sx%2$sx%3$s",
```

2022-07-09 12:06 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "jei.tooltip.beyond_earth.space_station": "建造\n一个空间站需要: ",
```suggestion
  "jei.tooltip.beyond_earth.space_station": "建造\n一个空间站需要：",
```

2022-07-09 12:06 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "gauge_text.beyond_earth.transfer": "%1$s 转换: %2$s",
```suggestion
  "gauge_text.beyond_earth.using": "%1$s 使用：%2$s",
  "gauge_text.beyond_earth.using2": "%1$s 使用：%2$s/%4$s tick",
  "gauge_text.beyond_earth.generating": "%1$s 生成：%2$s",
  "gauge_text.beyond_earth.maxgeneration": "最大:%1$s 生成：%2$s",
  "gauge_text.beyond_earth.total": "总量%1S：%2$s",
  "gauge_text.beyond_earth.stored": "已存储%1$s：%2$s",
  "gauge_text.beyond_earth.capacity": "%1$s 功率: %2$s",
  "gauge_text.beyond_earth.transfer": "%1$s 转换: %2$s",
```

2022-07-09 12:15 UTC, Cactusstudent reviewed
三审

2022-07-09 12:15 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.ice_shard": "冰刺",
```suggestion
  "item.beyond_earth.ice_shard": "冰碎片",
```
此为1.16仓库翻译

2022-07-09 12:15 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.netherite_space_boots": "下界合金制太空靴",
请考虑套装名称译法，个人偏向于`航天XX`

2022-07-09 12:23 UTC, ArgonCrystal commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.martian_raptor_spawn_egg": "火星凶兽刷怪蛋",
"item.beyond_earth.mogler_spawn_egg": "莫格洛刷怪蛋",
  "item.beyond_earth.martian_raptor_spawn_egg": "火星凶兽刷怪蛋",
如果进游戏看过就知道应该是
“item.beyond_earth.mogler_spawn_egg”： “外星疣猪兽刷怪蛋”，
“item.beyond_earth.martian_raptor_spawn_egg”： “火星迅猛龙刷怪蛋”，

2022-07-09 12:25 UTC, ArgonCrystal commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.pygro_brute_spawn_egg": "残暴派格洛刷怪蛋",
"item.beyond_earth.pygro_spawn_egg": "派格洛刷怪蛋",
  "item.beyond_earth.pygro_brute_spawn_egg": "残暴派格洛刷怪蛋",
这个也是同样，进游戏看就知道
“item.beyond_earth.pygro_spawn_egg”： “外星猪灵刷怪蛋”，
“item.beyond_earth.pygro_brute_spawn_egg”： “外星猪灵蛮兵刷怪蛋”，

2022-07-09 12:32 UTC, Cactusstudent commented
zh_cn多出的key……我游戏里翻烂了都没找到，得考虑删去了

2022-07-09 12:37 UTC, ArgonCrystal commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.star_crawler_spawn_egg": "星辰爬行者刷怪蛋",
实际游戏里模型有点像蠹虫，我是翻成"星际爬虫刷怪蛋"，或者你想翻"星际爬行者刷怪蛋"，但是你翻成"星辰爬行者刷怪蛋"

2022-07-09 12:38 UTC, ArgonCrystal commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.ostrum_tank": "紫金燃油罐",
ostrum这系列的key翻成紫金是什么依据。

2022-07-09 12:39 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "block.beyond_earth.glacio_lapis_ore": "霜原青金石矿石",
我惊了，glacio这个星球居然有大气……

2022-07-09 12:41 UTC, ArgonCrystal commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "block.beyond_earth.raw_calorite_block": "粗炽金块",
同理calorite=炽金是怎么来的。

2022-07-09 12:45 UTC, ArgonCrystal commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "gui.beyond_earth.planet_selection.glacio": "霜原星",
glacio这个词我查bing词典，多数词条解释都是冰川，还有一个指向一家冰淇淋供应商，glacio=霜原，是看游戏里的表现来的吗？

2022-07-09 13:07 UTC, Cactusstudent commented
征名：`Beyond Earth`（也就是模组名称）有啥好名字可以提出来

2022-07-09 13:13 UTC, ArgonCrystal commented
> 征名：（也就是模组名称）有啥好名字可以提出来`Beyond Earth`

超越地球

2022-07-09 15:54 UTC, mamaruo commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "itemGroup.tab_materials": "超越地平: 材料",
飞越寰宇丨地球之外

2022-07-09 15:55 UTC, mamaruo commented
审核时注意参考 #2113 和 1.16 的汉化

2022-07-09 15:58 UTC, mamaruo commented
/diff

2022-07-10 02:28 UTC, Cactusstudent reviewed
更新一些未更改的半角符号

2022-07-10 02:28 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "gauge_text.beyond_earth.transfer": "%1$s 转换: %2$s",
```suggestion
  "gauge_text.beyond_earth.capacity": "%1$s 功率：%2$s",
  "gauge_text.beyond_earth.transfer": "%1$s 转换：%2$s",
```

2022-07-10 02:28 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "advancements.rocket_tier_4_advancement.descr": "§b 最为先进的火箭! 好耶!",
```suggestion
  "advancements.workbench_advancement.title": "NASA工作台",
  "advancements.workbench_advancement.descr": "§b制造了一个万物的起源",
  "advancements.rocket_advancement.title": "一阶火箭",
  "advancements.rocket_advancement.descr": "§b 一个钢制火箭——真的能用？",
  "advancements.rocket_tier_2_advancement.title": "二阶火箭",
  "advancements.rocket_tier_2_advancement.descr": "§b 比钢制火箭多少好些……",
  "advancements.rocket_tier_3_advancement.title": "三阶火箭",
  "advancements.rocket_tier_3_advancement.descr": "§b 多么先进的科技！",
  "advancements.rocket_tier_4_advancement.title": "四阶火箭",
  "advancements.rocket_tier_4_advancement.descr": "§b 最为先进的火箭！好耶！",
```

2022-07-10 02:35 UTC, Cactusstudent commented
顺带一提，译文中多次提到`制`一字，考虑到目前质与制区分尚不明确，能否考虑根据实际情况来进行替换或删去

2022-07-10 03:17 UTC, Cactusstudent reviewed
小小看了一遍

2022-07-10 03:17 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "block.beyond_earth.ostrum_block": "紫金块",
ostrum好像是指一种染料名字，叫泰尔紫

2022-07-10 03:17 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "block.beyond_earth.raw_calorite_block": "粗炽金块",
![image](https://user-images.githubusercontent.com/97865546/178129620-d890338c-ace1-4d7d-8895-6f72b2ad9f34.png)
这名字多少有点长

2022-07-10 03:17 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "block.beyond_earth.raw_calorite_block": "粗炽金块",
个人认为简单翻译为`耐热合金`即可

2022-07-10 03:41 UTC, Longtianmu commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "biome.beyond_earth.glacio_ice_spikes": "霜原冰刺之地",
Glacio我看了，那边主要是大范围的冰刺群系，所以我就意译为霜原了

2022-07-10 03:41 UTC, Longtianmu commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "gui.beyond_earth.planet_selection.glacio": "霜原星",
是的

2022-07-10 04:12 UTC, Longtianmu commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.ostrum_tank": "紫金燃油罐",
看形状意译的

2022-07-10 04:12 UTC, Longtianmu commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "block.beyond_earth.raw_calorite_block": "粗炽金块",
炽金是因为本意是耐热合金，生成地点是金星岩浆池子旁边，就意译为炽金了

2022-07-10 04:15 UTC, Cactusstudent commented
[#2175 ](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/2175)

2022-07-10 04:23 UTC, Longtianmu commented
已修正

2022-07-10 04:31 UTC, Longtianmu commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.ostrum_tank": "紫金燃油罐",
并且是一种紫色染料名称emm

2022-07-10 04:32 UTC, Longtianmu commented
> zh_cn多出的key……我游戏里翻烂了都没找到，得考虑删去了

我搞错把别的版本的挪过来了 已经rm了

2022-07-10 06:31 UTC, Cactusstudent reviewed
听取群友建议，`级`->`阶`

2022-07-10 06:31 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.rocket_t4": "四级火箭",
```suggestion
  "item.beyond_earth.rocket_t1": "一阶火箭",
  "item.beyond_earth.rocket_t2": "二阶火箭",
  "item.beyond_earth.rocket_t3": "三阶火箭",
  "item.beyond_earth.rocket_t4": "四阶火箭",
```

2022-07-10 06:31 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "entity.beyond_earth.rocket_t4": "四级火箭",
```suggestion
  "entity.beyond_earth.rocket_t1": "一阶火箭",
  "entity.beyond_earth.rocket_t2": "二阶火箭",
  "entity.beyond_earth.rocket_t3": "三阶火箭",
  "entity.beyond_earth.rocket_t4": "四阶火箭",
```

2022-07-10 06:31 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "advancements.rocket_tier_4_advancement.descr": "§b已制作了一个四级火箭",
```suggestion
  "advancements.workbench_advancement.title": "NASA工作台",
  "advancements.workbench_advancement.descr": "§b已制作了一个NASA工作台",
  "advancements.rocket_advancement.title": "一阶火箭",
  "advancements.rocket_advancement.descr": "§b已制作了一个一阶火箭",
  "advancements.rocket_tier_2_advancement.title": "二阶火箭",
  "advancements.rocket_tier_2_advancement.descr": "§b已制作了一个二阶火箭",
  "advancements.rocket_tier_3_advancement.title": "三阶火箭",
  "advancements.rocket_tier_3_advancement.descr": "§b已制作了一个三阶火箭",
  "advancements.rocket_tier_4_advancement.title": "四阶火箭",
  "advancements.rocket_tier_4_advancement.descr": "§b已制作了一个四阶火箭",
```

2022-07-10 06:31 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "container.entity.beyond_earth.rocket_t4": "四级火箭",
```suggestion
  "container.entity.beyond_earth.rocket_t1": "一阶火箭",
  "container.entity.beyond_earth.rocket_t2": "二阶火箭",
  "container.entity.beyond_earth.rocket_t3": "三阶火箭",
  "container.entity.beyond_earth.rocket_t4": "四阶火箭",
```

2022-07-10 06:53 UTC, Cactusstudent reviewed
小修小改*n

2022-07-10 06:53 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "block.beyond_earth.wall_coal_torch": "煤火把",
```suggestion
  "block.beyond_earth.wall_coal_torch": "煤碳火把",
```

2022-07-10 06:53 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "block.beyond_earth.glacio_globe": "霜原仪",
```suggestion
  "block.beyond_earth.glacio_globe": "霜原星仪",
```

2022-07-10 06:53 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "entity.beyond_earth.star_crawler": "星爬行者",
```suggestion
  "entity.beyond_earth.star_crawler": "星辰爬行者",
```

2022-07-10 06:53 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "gui.beyond_earth.planet_selection.oxygen": "可呼吸大气",
```suggestion
  "gui.beyond_earth.planet_selection.oxygen": "氧气",
```

2022-07-10 06:53 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "gui.beyond_earth.planet_selection.oxygen.false": "不可呼吸",
```suggestion
  "gui.beyond_earth.planet_selection.oxygen.true": "有",
  "gui.beyond_earth.planet_selection.oxygen.false": "无",
```

2022-07-10 06:53 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "gui.beyond_earth.planet_selection.item_requirement": "需求物品",
```suggestion
  "gui.beyond_earth.planet_selection.item_requirement": "所需物品",
```

2022-07-10 07:26 UTC, Cactusstudent commented
建议一下，pr的提交者将原先的文本删去。文件路径应该是是project/1.18/assets/boss_tools/lang

2022-07-10 07:32 UTC, Longtianmu commented
> 建议一下，pr的提交者将原先的文本删去。文件路径应该是是project/1.18/assets/boss_tools/lang

新版modid已经更改为beyond_earth了

2022-07-10 07:33 UTC, Cactusstudent commented
> > 建议一下，pr的提交者将原先的文本删去。文件路径应该是是project/1.18/assets/boss_tools/lang
> 
> 新版modid已经更改为beyond_earth了

并不是，因为1.18的项目立项的时候是1.16的移动过来的，所以会导致有boss_tools的文件夹存在

2022-07-10 07:33 UTC, Cactusstudent commented
所以bot就会误判了

2022-07-10 07:58 UTC, Cactusstudent reviewed
估计是最后一个大问题了

2022-07-10 07:58 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "death.attack.venus.acid": "%1$s 在酸雨中化为灰烬",
```suggestion
  "death.attack.oxygen": "%1$s无法再呼吸了",
  "death.attack.venus.acid": "%1$s在酸雨中化为灰烬",
```

2022-07-10 07:58 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "message.beyond_earth.speed": "%s速度",
游戏内看着特别怪，大概是这样：-XXX 速度

2022-07-10 07:58 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "message.beyond_earth.speed": "%s速度",
能否考虑整一个稍微看着差不多的名字

2022-07-10 07:58 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "message.beyond_earth.no_fuel": "§c燃油耗尽！§7请为火箭装载§c燃油§7。（§6潜行并右键§7）",
```suggestion
  "message.beyond_earth.no_fuel": "§c燃油耗尽！§7请为火箭装载§c燃油§7。（§6潜行状态下右键火箭§7）",
```

2022-07-10 07:58 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "gauge.beyond_earth.oxygenloading": "装载中",
这一大串建议根据游戏内容重新更改下

2022-07-10 17:30 UTC, mamaruo commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "block.beyond_earth.wall_coal_torch": "煤火把",
```suggestion
  "block.beyond_earth.wall_coal_torch": "煤炭火把",
```

输入法该打死了

2022-07-10 17:40 UTC, mamaruo commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "advancements.moon_advancement.descr": "§b一览月球真貌，不到月球非好汉！",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |

原文：`Has entered the Moon`
加戏太多

```suggestion
  "advancements.moon_advancement.descr": "§b进入月球",
```
```suggestion
  "advancements.moon_advancement.descr": "§b抵达月球",
```

2022-07-10 17:43 UTC, mamaruo commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "advancements.rocket_tier_4_advancement.descr": "§b已制作了一个四阶火箭",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |

原：Has crafted a Tier X Rocket

```suggestion
  "advancements.rocket_advancement.descr": "§b制作一阶火箭",
  "advancements.rocket_tier_2_advancement.title": "二阶火箭",
  "advancements.rocket_tier_2_advancement.descr": "§b制作二阶火箭",
  "advancements.rocket_tier_3_advancement.title": "三阶火箭",
  "advancements.rocket_tier_3_advancement.descr": "§b制作三阶火箭",
  "advancements.rocket_tier_4_advancement.title": "四阶火箭",
  "advancements.rocket_tier_4_advancement.descr": "§b制作四阶火箭",
```
```suggestion
  "advancements.rocket_advancement.descr": "§b制作一个一阶火箭",
  "advancements.rocket_tier_2_advancement.title": "二阶火箭",
  "advancements.rocket_tier_2_advancement.descr": "§b制作一个二阶火箭",
  "advancements.rocket_tier_3_advancement.title": "三阶火箭",
  "advancements.rocket_tier_3_advancement.descr": "§b制作一个三阶火箭",
  "advancements.rocket_tier_4_advancement.title": "四阶火箭",
  "advancements.rocket_tier_4_advancement.descr": "§b制作一个四阶火箭",
```

2022-07-10 17:44 UTC, mamaruo commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "block.beyond_earth.coal_lantern": "煤灯笼",
| **审查级别**    | 备注 |
|--------------|----|
| ⚪ 轻微 / 不阻止合并但需三思  |    |

```suggestion
  "block.beyond_earth.coal_lantern": "煤炭灯笼",
```

2022-07-10 17:46 UTC, mamaruo commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "block.beyond_earth.raw_calorite_block": "粗炽金块",
建议`耐热合金`
不过自然生成？多少有点离谱

2022-07-10 17:51 UTC, mamaruo commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "entity.beyond_earth.martian_raptor": "火星迅猛龙",
really? 史前生物

2022-07-11 00:18 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "entity.beyond_earth.martian_raptor": "火星迅猛龙",
貌似是真的，因为长得样子也有点像，只不过长得特别丑

2022-07-11 00:24 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "advancements.moon_advancement.descr": "§b一览月球真貌，不到月球非好汉！",
```suggestion
  "advancements.moon_advancement.descr": "§b登上月球",
```

2022-07-11 00:30 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "block.beyond_earth.coal_lantern": "煤灯笼",
已确定仓库中1.16版本翻译为`煤炭灯笼`

2022-07-11 00:31 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "entity.beyond_earth.martian_raptor": "火星迅猛龙",
![image](https://user-images.githubusercontent.com/97865546/178168640-68712413-ded8-4a96-b886-d509ae741e48.png)
大概zhang长这个鬼样子

2022-07-13 02:06 UTC, Cactusstudent reviewed
一行一行的写了点东西，你问我为啥不直接选中多行……那一定是因为这玩意太过复杂，必须要一个个的弄

2022-07-13 02:07 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "gauge_text.beyond_earth.stored": "已存储%1$s：%2$s",
第329行游戏内没找到，所以空着没变

2022-07-13 05:00 UTC, Longtianmu commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "message.beyond_earth.speed": "%s速度",
这玩意能翻译成下降速度吗

2022-07-13 05:01 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "message.beyond_earth.speed": "%s速度",
貌似也行？我不大确定

2022-07-13 05:07 UTC, Longtianmu commented
以上已经修正了（除了下降速度/登陆速度）
然后似乎应该敲定一个译名？
目前有
飞越寰宇
超越地球
飞向苍穹
地外之境
地球之上

2022-07-13 05:08 UTC, Cactusstudent commented
> 

要不发到群里问问他们比较赞同哪一个

2022-07-13 05:10 UTC, Longtianmu commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "block.beyond_earth.raw_calorite_block": "粗炽金块",
自然生成合金确实比较 魔法
耐热金属/高温金属？

2022-07-13 05:10 UTC, Cactusstudent commented
实在不行就回退，直接写成Beyond Earth

2022-07-13 05:10 UTC, Cactusstudent commented
等有好的译名的时候再发个PR改

2022-07-13 05:19 UTC, Cactusstudent reviewed
`超越地球`->`Beyond Earth`（暂无较好译名）

2022-07-13 05:19 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "itemGroup.tab_materials": "超越地球丨材料",
```suggestion
  "itemGroup.tab_normal": "Beyond Earth",
  "itemGroup.tab_flags": "Beyond Earth丨旗帜",
  "itemGroup.tab_globes": "Beyond Earth丨星球仪",
  "itemGroup.tab_blocks": "Beyond Earth丨方块",
  "itemGroup.tab_basics": "Beyond Earth丨基本",
  "itemGroup.tab_machines": "Beyond Earth丨机器",
  "itemGroup.tab_spawn_eggs": "Beyond Earth丨刷怪蛋",
  "itemGroup.tab_materials": "Beyond Earth丨材料",
```

2022-07-13 05:23 UTC, Cactusstudent reviewed
`炽金`->`耐热金属`

2022-07-13 05:23 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "block.beyond_earth.raw_calorite_block": "粗炽金块",
```suggestion
  "block.beyond_earth.venus_calorite_ore": "金星耐热金属矿石",
  "block.beyond_earth.calorite_block": "耐热金属块",
  "block.beyond_earth.raw_calorite_block": "粗耐热金属块",
```

2022-07-13 05:23 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.molten_calorite_bucket": "熔融炽金桶",
```suggestion
  "block.beyond_earth.molten_calorite_fluid": "熔融耐热金属",
  "fluid.beyond_earth.molten_calorite": "熔融耐热金属",
  "fluid.beyond_earth.flowing_molten_calorite": "流动的熔融耐热金属",
  "item.beyond_earth.molten_calorite_bucket": "熔融耐热金属桶",
```

2022-07-13 05:23 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.calorite_tank": "炽金罐",
```suggestion
  "item.beyond_earth.calorite_ingot": "耐热金属锭",
  "item.beyond_earth.compressed_calorite": "致密耐热金属",
  "item.beyond_earth.calorite_nugget": "耐热金属粒",
  "item.beyond_earth.raw_calorite": "粗耐热金属",
  "item.beyond_earth.calorite_engine": "耐热金属引擎",
  "item.beyond_earth.calorite_tank": "耐热金属罐",
```

2022-07-13 05:24 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.calorite_tank": "炽金罐",
`耐热金属`这一译名还有待商榷

2022-07-13 05:26 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.calorite_tank": "炽金罐",
行了，我的任务完成了（）

2022-07-13 05:26 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.calorite_tank": "炽金罐",
别忘了#2184

2022-07-13 05:28 UTC, Longtianmu commented
速度一词是 下降速度还是登陆速度好（

2022-07-13 05:29 UTC, Cactusstudent commented
> 速度一词是 下降速度还是登陆速度好（

我认为都可以

2022-07-13 05:30 UTC, Cactusstudent commented
让我看看1.16的有没有

2022-07-13 05:32 UTC, Cactusstudent commented
> 让我看看1.16的有没有

没找到，那你就看着翻吧，我先溜了

2022-07-13 05:45 UTC, Longtianmu commented
速度我照抄星系翻译为登陆速度了

2022-07-13 18:25 UTC, mamaruo commented
> 实在不行就回退，直接写成Beyond Earth

我超，你可以一个comment说完的，说不完还能编辑上一个comment，SPAM了啊

2022-07-15 13:53 UTC, Cactusstudent approved these changes
小修小补

2022-07-15 13:53 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.pygro_spawn_egg": "僵尸猪灵刷怪蛋",
```suggestion
  "item.beyond_earth.pygro_spawn_egg": "外星僵尸猪灵刷怪蛋",
```

2022-07-15 13:53 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.oxygen_gear": "氧气套装",
```suggestion
  "item.beyond_earth.oxygen_gear": "氧气计",
```
稍微想了想，原文是`Oxygen Gear`，改成了这个（1.16库内已有翻译为`氧气计`）

2022-07-15 13:53 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.iron_stick": "铁棍",
```suggestion
  "item.beyond_earth.iron_stick": "铁棒",
```
1.16库内已有翻译为`铁棒`

2022-07-15 13:53 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.wheel": "轮子",
```suggestion
  "item.beyond_earth.wheel": "车轮",
```
太过口语化，1.16仓库内已有翻译为`车轮`

2022-07-15 13:53 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "gauge_text.beyond_earth.generating": "%1$s 生成：%2$s",
```suggestion
  "gauge_text.beyond_earth.generating": "%1$s生成：%2$s",
```

2022-07-15 13:53 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "key.categories.beyond_earth": "超越地球",
```suggestion
  "key.categories.beyond_earth": "Beyond Earth",
```

2022-07-15 13:54 UTC, Cactusstudent commented
> 小修小补

我认为已经没有了，所以……摆烂了

2022-07-15 14:21 UTC, Longtianmu commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.pygro_spawn_egg": "僵尸猪灵刷怪蛋",
这怪物我记得是因为在地球上会直接变成僵尸猪灵所以就不外星了

2022-07-15 14:38 UTC, Longtianmu commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.pygro_spawn_egg": "僵尸猪灵刷怪蛋",
草 是这么一回事 他们会退化 退化为僵尸疣猪兽之类的

2022-07-15 14:39 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.pygro_spawn_egg": "僵尸猪灵刷怪蛋",
那翻译就改成`外星僵尸猪灵刷怪蛋`

2022-07-15 14:39 UTC, Longtianmu commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.pygro_spawn_egg": "僵尸猪灵刷怪蛋",
所有Pygro在地球上十来秒都会退化成僵尸猪灵......
什么鬼设定

2022-07-15 14:40 UTC, Longtianmu commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.pygro_spawn_egg": "僵尸猪灵刷怪蛋",
还是加外星前缀便于区分？毕竟只有在地球上一定时间才会退化

2022-07-15 14:41 UTC, Longtianmu commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.oxygen_gear": "氧气套装",
参照星系4翻译为供氧设备了

2022-07-15 17:13 UTC, mamaruo commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "item.beyond_earth.pygro_spawn_egg": "僵尸猪灵刷怪蛋",
支持加外星

2022-07-15 17:42 UTC, mamaruo reviewed
我也来

2022-07-15 17:42 UTC, mamaruo commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "container.beyond_earth.oxygen_bubble_distributor": "氧气泡发生机",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |

查阅[术语在线](https://www.termonline.cn/search?k=distributor)、CNKI翻译助手发现 distributor 无“发生机”之译名。

查阅星系发现同名物品译为“[氧气释放机](https://www.mcmod.cn/item/55124.html)”
但其英文文本有带 Bubble 和不带两种：[eg1](https://github.com/TeamGalacticraft/Galacticraft-Legacy/blob/63df53c543aae5991f4f8761246b91488c007215/src/main/resources/assets/galacticraftcore/lang/en_US.lang#L641) [eg2](https://github.com/TeamGalacticraft/Galacticraft-Legacy/blob/63df53c543aae5991f4f8761246b91488c007215/src/main/resources/assets/galacticraftcore/lang/en_US.lang#L30)

根据[气体分配器](https://www.termonline.cn/word/181402/1#s1)，考虑：


```suggestion
  "container.beyond_earth.oxygen_bubble_distributor": "氧气泡分配器",
```

2022-07-15 17:42 UTC, mamaruo commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "death.attack.oxygen": "%1$s无法再呼吸了",
怪，但不知道哪里怪了
原文%1$s couldn\u0027t breathe anymore

2022-07-15 17:42 UTC, mamaruo commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "gauge_text.beyond_earth.using2": "%1$s使用：%2$s/%4$s tick",
```suggestion
  "gauge_text.beyond_earth.using2": "%1$s使用：%2$s/%4$s刻",
```

2022-07-16 03:28 UTC, Longtianmu commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "gauge_text.beyond_earth.using2": "%1$s使用：%2$s/%4$s tick",
tick这个要翻么emmm

2022-07-16 03:29 UTC, Longtianmu commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "death.attack.oxygen": "%1$s无法再呼吸了",
直译emm
改为xxx缺氧窒息而亡？

2022-07-16 03:32 UTC, Cactusstudent commented on projects/1.18/assets/beyond-earth/beyond_earth/lang/zh_cn.json
> +  "death.attack.oxygen": "%1$s无法再呼吸了",
```suggestion
  "death.attack.oxygen": "%1$s窒息而亡",
```

2022-07-16 10:55 UTC, Longtianmu commented
76 resolved conversations.jpg
应该没有要修改的了吧

2022-07-16 11:24 UTC, Cactusstudent commented
> 76 resolved conversations.jpg 应该没有要修改的了吧

或许吧，看审核怎么说

2022-08-24 07:34 UTC, dovisutu approved these changes
估计是最后一次了
@mamaruo 还有什么问题吗？没有干脆合了

2022-08-27 03:57 UTC, dovisutu commented
准备merge
还有问题后面再建pr

2022-08-27 03:57 UTC, merged