[R] Galosphere 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2093
Opened 2022-06-15 13:06 UTC by ChuijkYahus

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-06-15 13:06 UTC, ChuijkYahus commented
@Cyl18 
请求处理该问题（）

2022-06-18 17:19 UTC, mamaruo approved these changes

2022-06-22 00:21 UTC, Cyl18 commented
/add-mapping galosphere 631098

2022-06-22 00:27 UTC, Cyl18 commented
/diff

2022-06-22 00:28 UTC, Cyl18 requested changes
![image](https://user-images.githubusercontent.com/14993992/174918090-aa8b4b3a-7b03-4fe1-8df0-f663b0e1f642.png)

2022-06-22 04:24 UTC, ChuijkYahus commented
> ![image](https://user-images.githubusercontent.com/14993992/174918090-aa8b4b3a-7b03-4fe1-8df0-f663b0e1f642.png)

@Cyl18 
该物品合成原料为幽蓝晶和银，全为主世界物品，与下界和诡异木不存在任何联系
此方块效果为在周围16格内着陆的末影珍珠会将投掷者传送至其上

其实本来想把`Allurite`翻译为`诱蓝晶`的，但后来想想觉得名字不大好就改成现在的样子了

2022-06-22 06:40 UTC, Cyl18 approved these changes

2022-06-22 10:00 UTC, merged