[R] Macaw's Doors 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #2103
Opened 2022-06-17 14:01 UTC by ChuijkYahus

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-06-18 13:39 UTC, mamaruo requested changes
key 有点小问题，另请简述修改理由

2022-06-18 13:49 UTC, ChuijkYahus commented
key的问题如果是bot里提到的那个
是由于bot读了Fabric版本的语言文件

字幕部分是为统一翻译风格和格式，版画印花部分是与Macaw's Trapdoors统一，其余未作改动

2022-06-18 17:41 UTC, mamaruo commented
> key的问题如果是bot里提到的那个 是由于bot读了Fabric版本的语言文件

@Cyl18

2022-06-18 17:41 UTC, mamaruo approved these changes

2022-06-22 00:19 UTC, Cyl18 approved these changes

2022-06-23 05:22 UTC, n0099 approved these changes

2022-06-23 05:22 UTC, merged