[R] Every Compat 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2106
Opened 2022-06-17 16:23 UTC by ChuijkYahus

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

不知道这个模组对中文有没有用

2022-06-17 16:42 UTC, ChuijkYahus commented
@Cyl18
请求解决该问题

2022-06-18 16:39 UTC, mamaruo approved these changes

2022-06-18 16:43 UTC, mamaruo requested changes

2022-06-18 16:43 UTC, mamaruo commented on projects/1.18/assets/every-compat/everycomp/lang/zh_cn.json
> +  "block_type.mcwdoors.bark_glass_door": "%s玻璃谷仓门",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  与原文不符  |
```suggestion
  "block_type.mcwdoors.bark_glass_door": "%s玻璃谷仓门",
```
原文：**%s Bark Glass Door**

2022-06-22 00:58 UTC, Cyl18 commented
/add-mapping every-compat 628539

2022-06-22 00:59 UTC, Cyl18 commented
/diff

2022-06-23 05:28 UTC, n0099 approved these changes

2022-06-23 05:28 UTC, merged