[R] enderthing 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2115
Opened 2022-06-19 10:22 UTC by ranl-8417

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-06-21 22:46 UTC, Cyl18 commented
/diff

2022-06-22 00:29 UTC, Cyl18 commented
/diff

2022-06-22 00:30 UTC, Cyl18 requested changes
![image](https://user-images.githubusercontent.com/14993992/174918286-ca3bd728-ad57-4372-8009-6dbc4f4424ef.png)

2022-06-23 05:31 UTC, n0099 commented on projects/1.18/assets/enderthing/enderthing/lang/zh_cn.json
> +    "container.enderthing.private": "私人存储空间",
我觉得可以叫空间，因为他不是指的玩家背包物品栏

2022-06-25 15:09 UTC, mamaruo commented on projects/1.18/assets/enderthing/enderthing/lang/zh_cn.json
> +    "container.enderthing.private": "私人存储空间",
```suggestion
    "container.enderthing.global": "公共末影存储空间",
    "container.enderthing.private": "私人末影存储空间",
```
```suggestion
    "container.enderthing.global": "公共末影物品栏",
    "container.enderthing.private": "私人末影物品栏",
```

2022-06-28 06:28 UTC, Demonese commented on projects/1.18/assets/enderthing/enderthing/lang/zh_cn.json
> +    "block.enderthing.key_chest": "末影钥匙箱子",
```suggestion
    "block.enderthing.key_chest": "末影钥匙箱",
```

2022-06-28 06:28 UTC, Demonese commented on projects/1.18/assets/enderthing/enderthing/lang/zh_cn.json
> +    "block.enderthing.key_chest_private": "私人末影箱",
```suggestion
    "block.enderthing.key_chest_private": "私人末影钥匙箱",
```

2022-07-02 13:36 UTC, n0099 requested changes

2022-07-02 13:36 UTC, n0099 commented on projects/1.18/assets/enderthing/enderthing/lang/zh_cn.json
> +    "tooltip.enderthing.ender_card.right_click2": "按住Shift键右键单击私人箱子以绑定箱了并允许自动输入输出。",
```suggestion
    "tooltip.enderthing.ender_key_chest.right_click": "合成一个末影锁并按住Shift键右击一个原版的末影箱。",
    "tooltip.enderthing.ender_key.right_click": "按住Shift键右击原版末影箱以打开对应的存储空间。",
    "tooltip.enderthing.ender_lock.right_click": "按住Shift键右击一个末影箱来设置或更改密码。",
    "tooltip.enderthing.ender_pack.right_click": "右击以打开对应的存储空间。",
    "tooltip.enderthing.ender_card.right_click1": "按住Shift键右击空气以将其绑定到您。",
    "tooltip.enderthing.ender_card.right_click2": "按住Shift键右击私人箱子以绑定箱了并允许自动输入输出。",
```
右击更短一些

2022-07-03 15:48 UTC, n0099 approved these changes

2022-07-04 05:39 UTC, mamaruo approved these changes

2022-07-04 10:55 UTC, merged