[R]rebornstorage 1.18.2 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2122
Opened 2022-06-22 13:35 UTC by ArgonCrystal

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-06-23 05:56 UTC, n0099 requested changes

2022-06-23 05:56 UTC, n0099 commented on projects/1.18/assets/rebornstorage/rebornstorage/lang/zh_cn.json
> +    "gui.rebornstorage.advanced_wireless_transmitter": "高级无线发射器r",
```suggestion
    "gui.rebornstorage.advanced_wireless_transmitter": "高级无线发射器",
```

2022-06-23 05:56 UTC, n0099 commented on projects/1.18/assets/rebornstorage/rebornstorage/lang/zh_cn.json
> +    "item.rebornstorage.larger_fluid_disk_part": "1048M流体存储元件",
是否需要跟118ae统一 https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/2003#discussion_r894779330

2022-06-23 05:59 UTC, n0099 commented on projects/1.18/assets/rebornstorage/rebornstorage/lang/zh_cn.json
> +    "item.rebornstorage.larger_fluid_disk_part": "1048M流体存储元件",
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/b5f813183767e18d195a48fc11746d589fe12707/projects/1.16/assets/refined-storage/refinedstorage/lang/zh_cn.json#L223-L243

2022-06-23 05:59 UTC, n0099 approved these changes

2022-06-23 11:40 UTC, Cyl18 commented
/diff

2022-06-24 13:24 UTC, merged

2022-06-24 20:45 UTC, Cyl18 commented
没对呀
- 是否需要和AE统一译名
- `16384k存储元件` `16384K流体存储元件` K大小写不统一