魔法艺术3：巧工魔艺 翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #2139
Opened 2022-06-30 14:21 UTC by Pinkhai

- [ ] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x ] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-07-01 01:51 UTC, Pinkhai commented
/diff

2022-07-02 13:42 UTC, n0099 commented
> This branch has conflicts that must be resolved

2022-07-02 14:20 UTC, Pinkhai commented
我把缺失的条目增加了一下，改了几处过去不正确的翻译

2022-07-02 14:50 UTC, n0099 commented
> > This branch has conflicts that must be resolved


请您merge一下upstream（执行git pull）

2022-07-02 15:53 UTC, Pinkhai commented
/git pull

2022-07-03 14:42 UTC, Pinkhai commented
现在呢

2022-07-03 15:32 UTC, n0099 commented
good

2022-07-04 12:24 UTC, Pinkhai commented
所以什么时候能合并呢

2022-07-04 13:18 UTC, n0099 commented
> +3,552 −2,983

我不好说我擦

2022-07-05 12:18 UTC, TUsama reviewed
此次审核我不代表任何组织，纯粹是作为本人，作为此模组的前任译者提出的意见与建议。其中的任何 suggestion 都请不要直接 commit，否则我会在所有意见提出完毕后手动清除自己的信息。

谈回此新增翻译，就我目前看到的内容而言，整体质量不过关，但是考虑到目前提交者为新手，情有可原。一般来说我从不建议新手碰大案子，一来若是犯错，极易被人钉在耻辱柱上，轻易不能翻身，二则是大案子对于新手来说不符合循序渐进的道理，不利于新人逐步上手翻译，进一步感受翻译的乐趣所在。比如这一PR就是一个典型的例子：新人在没有熟悉 mc 原版标准译名的情况下翻译模组文本，很容易自己加戏，脱离了 mc 的语境要求，更别谈一些过往模组的惯用译名、国内其他游戏文本惯用译名这些问题了，这些问题处理起来更是要耐心谨慎，一定要把资料查得通透到位，否则就是译者的失职。

以上的意见只是一部分，剩下的我还没看。我曾跟某人承诺，我不会再在此仓库作出任何贡献，哪怕是 MA 也是如此。我向来遵守诺言，这次也不打算反悔。这次来看纯粹是表明一下我的态度：我曾说星辉像是我的二儿子，但我似乎从未提及我的大儿子——那就是 MA，MA 从刚刚面世时我便着手翻译，一直到前段时间的变故才停下，然而我对 MA 的喜爱并不会因为这一些小事情而变化。同时我也有承诺在身，这趟浑水我是不会再参与了，所以我才会要求不要 commit 任何我和 suggestion，若是执意如此，那我也会采取一定手段，来确保这一承诺不被打破。

至于新人，很抱歉你被卷入这些腌臜破事之中，上面这些话大多不是说给你听的，你只管做好翻译即可。你愿意花时间做翻译，说明你对 MA 上心，有为 MA 贡献的想法，有这样想法的人乃是我的同道，自然不会对你出言不逊。但是我也得提醒你，MA 的体量大，如果想做好，非得修炼一段时日才行，要不然就变成好心办坏事了，这样的结尾你我都不想看到。所以若你遇到不懂的，在群里多问多想，在网上多查多看，努力不会辜负你，你也不会辜负 MA。

以上。

2022-07-05 12:35 UTC, mamaruo commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"itemGroup.mna.constructs": "巧工魔艺：构装",
抓住清秋！
没改

2022-07-05 13:07 UTC, mamaruo commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"item.mna.torn_journal_page.learned.suffix": " 已经提升",
简单地挪一下
前缀：你的
后缀：知识提升了！
组合：你的 某 知识提升了！

2022-07-06 15:49 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"itemGroup.mna.constructs": "巧工魔艺：构装",
这个听你们的

2022-07-06 15:49 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"item.mna.faction_horn_demons": "束缚号角",
因为考虑到束缚是chain相较于锁链更为文学化的意义，当然翻译成锁链也可以。但是我拿到的旧版是炼狱号角，总感觉有些怪，不知道这里有没有什么规范

2022-07-08 00:06 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"item.mna.animated_quill": "有生命的羽毛",
好的

2022-07-08 00:56 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"item.mna.book_of_rote": "博诵之书",
这个是mcmod里面有个教程把这个写成博诵，因为考虑到很多人都是从mcmod接触到这个模组入门的，所以给旧版做了保留

2022-07-09 14:02 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"item.mna.herbalist_pouch": "草药医师之袋",
这个直译为此，或许可以改为药草术士之袋？

2022-07-09 14:06 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"item.mna.runic_malus": "符文偏振锤",
如果直译的话只能翻译成符文马吕斯，跟这个唯一有关的百科意向就是马吕斯定理，用于描述光的偏振现象，再加上这个物品本身是个锤子的形状。当时考虑到作者在GitHub上回复速度较慢，暂时翻译成这样。

2022-07-10 06:00 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"item.mna.torn_journal_page.contains": "似乎写着些支离破碎的东西",
这个东西用在研究桌上，介绍里写可以提升上面提及到的法术精通

2022-07-10 13:58 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"item.mna.component_pouch": "符文组件袋",
打开会有几个随机雕符

2022-07-10 14:07 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"item.mna.herbalist_pouch.desc": "包含各种有用的魔力组件，右击打开",
这个地方改正了

2022-07-10 14:10 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"item.mna.staff_phylactery": "呼唤法杖",
可以打开放置某些东西（类似于魔导书，但是打开后的界面不同，里面的格子布局奇异）但是应该不是放置法术。指导书和网络教程都没有详细的解释。

2022-07-10 14:18 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"item.mna.astro_blade": "星之时无阔剑",
当时考虑的是准确时间无法获知，现在看来背离了信原则。考虑到这个词条好像有一定的意大利文化背景，也许“阔剑”改为意大利人使用这个词时多指代的“双手剑”似乎更好？

2022-07-10 14:22 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"mna:multiblock/undead_circle": "不死者圣所",
以前不知道有标准词库

2022-07-10 14:37 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"item.mna.torn_journal_page.contains": "似乎写着些支离破碎的东西",
![image](https://user-images.githubusercontent.com/107166389/178149424-00886d16-0838-4918-bbb3-8fb322b7dabc.png)

2022-07-10 14:55 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"item.mna.torn_journal_page.contains": "似乎写着些支离破碎的东西",
![image](https://user-images.githubusercontent.com/107166389/178150137-6fb25bf9-5513-4039-b48a-18e420c50c57.png)

2022-07-10 14:56 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"item.mna.staff_phylactery": "呼唤法杖",
![image](https://user-images.githubusercontent.com/107166389/178150171-f8d7b717-aa86-4608-9a38-4795b7f9ddfe.png)

2022-07-10 14:58 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"item.mna.spell_part_thesis.contains": "似乎写着些详细的东西",
和日记残页的用途有重合之处

2022-07-14 14:33 UTC, TUsama commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"item.mna.book_of_rote": "博诵之书",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

这个是mcmod里面有个教程把这个写成博诵，因为考虑到很多人都是从mcmod接触到这个模组入门的，所以给旧版做了保留

2022-07-14 14:38 UTC, TUsama commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"item.mna.herbalist_pouch": "草药医师之袋",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

这个直译为此，或许可以改为药草术士之袋？

2022-07-14 14:52 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"item.mna.herbalist_pouch": "草药医师之袋",
是的，受教

2022-07-14 15:03 UTC, TUsama commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"itemGroup.mna.constructs": "巧工魔艺：构装",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

| **审查级别** |
|--------------|
| ℹ️ 信息 / 不阻止合并  |

抓住清秋！
没改，但原文是冒号，这种情况也处理成丨吗

2022-07-14 15:05 UTC, TUsama commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"item.mna.faction_horn_demons": "束缚号角",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

如果你觉得是否原文具有某种隐喻意义，这个时候问一问自己，为什么作者不用 bound 而是用 chain，你就能知道你思考的所谓隐喻含义其实只是自己的加戏罢了。

2022-07-14 15:32 UTC, TUsama requested changes
第二部分，问题比较严重。

2022-07-14 15:32 UTC, TUsama commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +  "item.mna.icarian_flight": "冒险飞行卷轴",
文不达义，应译为伊卡洛斯之翔。具体请查原文典故。

2022-07-14 15:32 UTC, TUsama commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +  "block.mna.illusion_block": "幻想方块",
此处乃是 AM2 中的幻象方块。

2022-07-14 15:32 UTC, TUsama commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +  "block.mna.seer_stone": "预言石",
先知即为先知，预言即为预言，怎会混淆？

2022-07-14 15:32 UTC, TUsama commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +  "block.mna.seer_stone.blacklist": "黑名单自定义物品，可选玩家护符和水晶符咒",
此两处请贴出实际使用中的图片，并且务必截图出文本，不要只是放上一张莫名其妙的图。

并且此两句肯定是错译的。

2022-07-14 15:32 UTC, TUsama commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +  "block.mna.seer_stone.area": "自定义搜寻物品的范围。 可选boundinb box的一角必须在预言之石的32格以内。",
译名不统一。

怀疑原文错字，等作者修正。

2022-07-14 15:32 UTC, TUsama commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +  "block.mna.transitory_tunnel": "临时隧道",
请说一说此处将短时改为临时的理由？

2022-07-14 15:32 UTC, TUsama commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +  "gui.mna.construct.buoyancy": "浮力 (允许一个以上漂浮)",
错译。

2022-07-16 15:10 UTC, SakurashimaYuzu commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"itemGroup.mna.constructs": "巧工魔艺：构装",
问下大佬
为什么i18n自动汉化的汉化包中还是mana-and-artifice，手动改成mna才能用。。。。

2022-07-17 04:04 UTC, Pinkhai commented
为什么我现在打开在线VScode这个文件看不到comment了？

2022-07-17 08:52 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"itemGroup.mna.constructs": "巧工魔艺：构装",
不太清楚，我之前交了一个issue说过这个，应该已经改了？

2022-07-17 08:53 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"itemGroup.mna.constructs": "巧工魔艺：构装",
这个符号改了

2022-07-17 08:54 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"item.mna.faction_horn_demons": "束缚号角",
反过来一想确实是这样的，已经改成锁链号角了

2022-07-17 08:55 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +	"item.mna.torn_journal_page": "撕下的日记页面",
这里改过了

2022-07-17 15:41 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +  "gui.mna.arcane-sentry.fuel": "能源",
改为非攻如何？

2022-07-17 15:42 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +  "block.mna.spell_infusion": "转录桌",
好的

2022-07-17 15:42 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +  "block.mna.transitory_tile": "临时瓷砖",
好的

2022-07-17 15:46 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +  "block.mna.transitory_tunnel": "临时隧道",
这个地方考虑少了，词义和实用来讲短时确实更好

2022-07-17 15:53 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +  "block.mna.seer_stone.area": "自定义搜寻物品的范围。 可选boundinb box的一角必须在预言之石的32格以内。",
行，我有空的时候往那里交个issue

2022-07-17 15:55 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +  "block.mna.seer_stone": "预言石",
是的

2022-07-18 03:38 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +  "block.mna.illusion_block": "幻想方块",
改正了

2022-07-18 03:38 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +  "item.mna.icarian_flight": "冒险飞行卷轴",
改正了

2022-07-18 03:38 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +  "block.mna.lodestar.logic_restored": "逻辑流动已经恢复！",
改正了

2022-07-18 03:39 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +  "helptip.mna.pretty_models": "你知道吗？  有一个 forge 配置选项可以让魔法艺术的模型看上去更好，我推荐你打开它。 它在 forge-client.toml 然后这个选项是 'experimentalForgeLightPipelineEnabled'.  把它设定到“true”来开启它",
改正了

2022-07-18 03:39 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +  "gui.mna.wizard_lab.xp_cost": "执行此操作将消耗你 %d 经验 (现有经验： %d).",
改正了

2022-07-18 04:59 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +  "gui.mna.mastery_increased": "你对 %s 的掌握已经提升! 这一部件产生的魔法冷却已经降低了 %d%%.",
改正了

2022-07-20 15:39 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +  "block.mna.seer_stone.blacklist": "黑名单自定义物品，可选玩家护符和水晶符咒",
我发现前面的charms这个词翻译成了符咒，然而原意似乎是护符，在这里和水晶符咒又冲突了，要把前面的符咒一次全部换为护符吗？

2022-07-20 15:45 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +  "gui.mna.arcane-sentry.fuel": "能源",
改过了一次请斧正

2022-07-21 10:25 UTC, mamaruo commented
> 为什么我现在打开在线VScode这个文件看不到comment了？

 Resolve 了的 comment 不会显示。另外不用一个个回复`已改正`。

2022-07-21 15:53 UTC, Pinkhai commented on projects/1.18/assets/mana-and-artifice/mna/lang/zh_cn.json
> +  "block.mna.seer_stone.area": "自定义搜寻物品的范围。 可选boundinb box的一角必须在预言之石的32格以内。",
![4W2NQUN6IGFCUN(P{MGC7RV](https://user-images.githubusercontent.com/107166389/180258605-1e53d50f-6c59-4dea-bb99-8d82028d598e.png)

2022-07-23 06:23 UTC, Pinkhai reviewed
ok...?

2022-07-24 09:25 UTC, TUsama commented
后面的我就不审了，错误也有，语序问题也有，改起来很麻烦，我直接就在我之前没有做完的新版本翻译里继续弄了。这边你先把你文本里的机翻改掉（物品翻译成项目），然后检查一下标点符号，应该就差不多了。到时候我直接把我的版本merge到官方里，这个就先用作过渡。

2022-07-24 09:44 UTC, Pinkhai commented
期待新作

2022-08-04 02:27 UTC, StarryNeverFall commented
问一下，你们有计划翻译guide文件么

2023-02-11 03:41 UTC, closed without merging