[R] LazierAE2 1.18.2版本翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2143
Opened 2022-07-02 07:27 UTC by ArgonCrystal

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-07-02 08:12 UTC, Cyl18 commented
/diff

2022-07-02 13:54 UTC, n0099 approved these changes

2022-07-08 12:31 UTC, dovisutu requested changes
粗查了一下
一个问题：`raw material`是否就是简单的`原材料`？
例如，合成逻辑处理器时你可以说金锭就是原材料，也可以说逻辑电路板是原材料，但`raw material`指的恐怕是前者（否则何谈节省加工时间？）

2022-07-08 12:31 UTC, dovisutu commented on projects/1.18/assets/lazierae2/lazierae2/lang/zh_cn.json
> +  "tooltip.lazierae2.etcher.description": "本质上是一个高级压印器，但可通过使用原材料进行升级且速度更快。",
> *upgradable* **and** *faster by making use of raw materials*

个人认为正确的语句分割是这样的。

```suggestion
  "tooltip.lazierae2.etcher.description": "本质上是一个高级压印器，但可安装升级，并且由于材料无需中间工序，速度更快。",
```

2022-07-09 00:47 UTC, ArgonCrystal commented on projects/1.18/assets/lazierae2/lazierae2/lang/zh_cn.json
> +  "tooltip.lazierae2.extended_numbers": "对于扩展数字",
> 

我在游戏里也没找到这个key提现在哪

2022-07-09 00:53 UTC, ArgonCrystal commented on projects/1.18/assets/lazierae2/lazierae2/lang/zh_cn.json
> +  "tooltip.lazierae2.focus.switch.action": "切换焦点",
> 

这个改了

2022-07-09 00:58 UTC, ArgonCrystal commented on projects/1.18/assets/lazierae2/lazierae2/lang/zh_cn.json
> +  "tooltip.lazierae2.batch.description": "当发出合成请求时，请求者将使用请求数量的多少。 使用更多的次数将提高储存物品的速度，但需要更多的合成存储空间。",
> 

1、出现空格是原文有空格，翻译的时候没注意保留了下来
2、稍微修改了一下
3、请求者游戏里就是侦测me网络里的物品数量，根据设置发送合成请求，我参考隔壁rs的一个同类附属模组的翻译为请求者。

2022-07-09 01:00 UTC, ArgonCrystal commented on projects/1.18/assets/lazierae2/lazierae2/lang/zh_cn.json
> +  "tooltip.lazierae2.extract.description": "定义输出槽中的物品是否自动转移到相邻的存储中。",
> `inventory`很少直接翻译成`存储`的

我查bing词典
inventory
n.库存；财产清单；（建筑物里的物品、家具等的）清单
v.开列清单
Web存货；详细目录；存货清单
那改成库存？

2022-07-09 01:06 UTC, ArgonCrystal commented on projects/1.18/assets/lazierae2/lazierae2/lang/zh_cn.json
> +  "tooltip.lazierae2.aggregator.description": "通过使用晶体生长加速器来加速晶体在世界中的合成。 通过使用原材料授予晶体合成的访问权限并具有充能功能。",
> 

晶体是根据AE2的晶体催生器的翻译来的。直译和意译的区别，改成后者更信息更清晰一些，毕竟是说明信息。

2022-07-09 01:09 UTC, ArgonCrystal commented
> 



> 粗查了一下 一个问题：`raw material`是否就是简单的`原材料`？ 例如，合成逻辑处理器时你可以说金锭就是原材料，也可以说逻辑电路板是原材料，但`raw material`指的恐怕是前者（否则何谈节省加工时间？）

改成合成材料了

2022-07-09 04:22 UTC, dovisutu commented on projects/1.18/assets/lazierae2/lazierae2/lang/zh_cn.json
> +  "tooltip.lazierae2.extract.description": "定义输出槽中的物品是否自动转移到相邻的存储中。",
一般在MC的语境里`inventory`指的是`（玩家/实体的）物品栏；（方块形式的）物品容器`
可以直接翻成`容器`

2022-07-09 15:38 UTC, mamaruo commented on projects/1.18/assets/lazierae2/lazierae2/lang/zh_cn.json
> +  "tooltip.lazierae2.extract.description": "定义输出槽中的物品是否自动转移到相邻的存储中。",
我建议物品栏

2022-07-09 15:42 UTC, mamaruo commented on projects/1.18/assets/lazierae2/lazierae2/lang/zh_cn.json
> +  "tooltip.lazierae2.extended_numbers": "对于扩展数字",
```suggestion
  "tooltip.lazierae2.extended_numbers": "显示扩展数字",
```
应该是和上几个键拼成“按住某键显示 Extended Numbers”

2022-07-09 15:47 UTC, mamaruo commented on projects/1.18/assets/lazierae2/lazierae2/lang/zh_cn.json
> +  "itemGroup.lazierae2": "懒人AE2",
```suggestion
  "itemGroup.lazierae2": "懒人AE2 1.16+",
```
MC百科译法，我不是很赞同，或者不译
懒人AE2是 Lazy AE2 的译名，lazier ae2 不建议沿用

2022-07-09 15:47 UTC, mamaruo commented on projects/1.18/assets/lazierae2/lazierae2/lang/zh_cn.json
> +  "block.lazierae2.requester": "ME请求者",
| **审查级别**    | 备注 |
|--------------|----|
| ⚪ 轻微 / 不阻止合并但需三思  |    |

```suggestion
  "block.lazierae2.requester": "ME请求器",
```

2022-07-09 15:47 UTC, mamaruo commented on projects/1.18/assets/lazierae2/lazierae2/lang/zh_cn.json
> +  "tooltip.lazierae2.io.title": "I/O 配置",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |

```suggestion
  "tooltip.lazierae2.io.title": "I/O配置",
```

2022-07-10 16:52 UTC, mamaruo commented on projects/1.18/assets/lazierae2/lazierae2/lang/zh_cn.json
> +  "tooltip.lazierae2.extract.description": "定义输出槽中的物品是否自动转移到相邻的存储中。",
失误了，这里还是翻成“容器”较妥当

2022-07-27 08:08 UTC, mamaruo commented
/diff

2022-11-21 15:36 UTC, Cactusstudent commented on projects/1.18/assets/lazierae2/lazierae2/lang/zh_cn.json
> +  "itemGroup.lazierae2": "懒人AE2 1.16+",
```suggestion
  "itemGroup.lazierae2": "Lazier AE2",
```

2023-01-23 18:50 UTC, mamaruo approved these changes

2023-02-02 06:09 UTC, merged