industrial-foregoing-1.18.2-3.3.1.4-8版本翻译更新提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2146
Opened 2022-07-03 04:44 UTC by ArgonCrystal

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-07-04 05:42 UTC, mamaruo commented
为什么会包含[Sully's Mod](https://www.curseforge.com/minecraft/mc-mods/sullys-mod)的改动

2022-07-04 06:11 UTC, ArgonCrystal commented
> 为什么会包含[Sully's Mod](https://www.curseforge.com/minecraft/mc-mods/sullys-mod)的改动

我查看分支历史，不知道怎么多了个[Sully's Mod](https://www.curseforge.com/minecraft/mc-mods/sullys-mod)的改动，我撤销了。

2022-07-04 07:03 UTC, mamaruo requested changes

2022-07-04 07:03 UTC, mamaruo commented on projects/1.18/assets/industrial-foregoing/industrialforegoing/lang/zh_cn.json
> +  "tooltip.titanium.facing_handler.disenchantment.input_0": "输入附魔",
```suggestion
  "tooltip.titanium.facing_handler.disenchantment.input_0": "附魔物品输入",
```
这一串翻译成 XX 输入/输入端 是否更好？看起来这是配置机器侧面功能的语句，Input 应为名词

2022-07-10 16:48 UTC, mamaruo approved these changes

2022-08-15 12:31 UTC, dovisutu commented on projects/1.18/assets/industrial-foregoing/industrialforegoing/lang/zh_cn.json
> +  "tooltip.titanium.facing_handler.disenchantment.input_0": "输入附魔",
ping @ArgonCrystal

2022-12-03 12:54 UTC, closed without merging