[R]Macaw's Fences - Oh The Biomes You'll Go 模组翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2152
Opened 2022-07-04 11:55 UTC by liminyu233

- [x] 我已**仔细**阅读注意事项 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已对 PR 作出 [标记](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意许可协议：[知识共享 署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-07-09 10:38 UTC, WJXhhh commented on projects/1.18/assets/macaws-fences-oh-the-biomes-youll-go/mcwfencesbyg/lang/en_us.json
> +	"itemGroup.tab_mfbyg": "Macaw的栅栏和墙 - BYG",
en_us里有中文……

2022-07-09 10:40 UTC, WJXhhh requested changes

2022-07-09 10:40 UTC, WJXhhh commented on projects/1.18/assets/macaws-fences-oh-the-biomes-youll-go/mcwfencesbyg/lang/en_us.json
> +	"itemGroup.tab_mfbyg": "Macaw的栅栏和墙 - BYG",
这里不应该出现中文吧

2022-07-09 10:41 UTC, WJXhhh approved these changes

2022-07-09 10:45 UTC, WJXhhh reviewed
.

2022-07-09 10:45 UTC, WJXhhh commented on projects/1.18/assets/macaws-fences-oh-the-biomes-youll-go/mcwfencesbyg/lang/en_us.json
> +	"itemGroup.tab_mfbyg": "Macaw的栅栏和墙 - BYG",
这里不应该有中文吧……

2022-07-09 10:45 UTC, WJXhhh commented on projects/1.18/assets/macaws-fences-oh-the-biomes-youll-go/mcwfencesbyg/lang/en_us.json
> +	"itemGroup.tab_mfbyg": "Macaw的栅栏和墙 - BYG",
这里不应该有中文吧……

2022-07-09 10:48 UTC, liminyu233 commented on projects/1.18/assets/macaws-fences-oh-the-biomes-youll-go/mcwfencesbyg/lang/en_us.json
> +	"itemGroup.tab_mfbyg": "Macaw的栅栏和墙 - BYG",
确实，不过现在我没有电脑改不了了。

2022-07-09 10:48 UTC, liminyu233 commented on projects/1.18/assets/macaws-fences-oh-the-biomes-youll-go/mcwfencesbyg/lang/en_us.json
> +	"itemGroup.tab_mfbyg": "Macaw的栅栏和墙 - BYG",
> 这里不应该有中文吧……

确实，不过现在我没有电脑改不了了。

2022-09-22 13:24 UTC, ChuijkYahus commented on projects/1.18/assets/macaws-fences-oh-the-biomes-youll-go/mcwfencesbyg/lang/zh_cn.json
> +	"block.mcwfencesbyg.palm_picket_fence":"Palm Picket Fence",
```suggestion
	"block.mcwfencesbyg.palm_picket_fence":"棕榈木篱栅",
```

2022-09-23 23:21 UTC, closed without merging