Every Compat 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2156
Opened 2022-07-04 14:26 UTC by ChuijkYahus

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-07-04 14:26 UTC, ChuijkYahus commented
/update-en every-compat 1.18

2022-07-08 11:03 UTC, WJXhhh commented
@ChuijkYahus 粗略审了一遍 ，有以下翻译建议：

1. 将**提基火把**和**灵魂提基火把**分别改成**栅栏火把**和**灵魂栅栏火把**（提基并无实际含义，在这里有更好的替代翻译（都由相应材料的栅栏合成））
2. ……杆翻译成……柱子（谷歌翻译结果，游戏里也是柱子模样）
3. 将分割……杆，改为四分之一（分数表示形式自定）……柱子（因为在游戏里，此种物品由对应材料的柱子和斧子在工作台内合成，变成了原来的四分之一长，然后将此物品放在地上再叠加四次就会复原）
4. ……桥梯翻译成……桥楼梯（因为游戏中此物品和楼梯一样）
5. ……索桥翻译成……绳索桥（更通顺些，游戏内也是用绳索连接）
6. ……索桥梯翻译成……绳索桥楼梯（相比起桥楼梯来多了几段绳索）

2022-09-05 09:18 UTC, Dr-WeiAL requested changes

2022-09-05 09:18 UTC, Dr-WeiAL commented on projects/1.18/assets/every-compat/everycomp/lang/zh_cn.json
>    "wood_type.twilightforest.dark": "黑木"
```suggestion
  "wood_type.twilightforest.dark": "黑木",
  "wood_type.biomesoplenty.fir": "杉木",
  "wood_type.biomesoplenty.redwood": "红木",
  "wood_type.biomesoplenty.cherry": "樱桃木",
  "wood_type.biomesoplenty.mahogany": "桃花心木",
  "wood_type.biomesoplenty.jacaranda": "蓝花楹木",
  "wood_type.biomesoplenty.palm": "棕榈木",
  "wood_type.biomesoplenty.willow": "柳木",
  "wood_type.biomesoplenty.dead": "枯死木",
  "wood_type.biomesoplenty.magic": "魔法木",
  "wood_type.biomesoplenty.umbran": "暗影木",
  "wood_type.biomesoplenty.hellbark": "地狱皮木",
  "wood_type.botania.livingwood": "活木",
  "wood_type.botania.dreamwood": "梦之木",
  "wood_type.blue_skies.bluebright": "蓝辉木",
  "wood_type.blue_skies.starlit": "星荧木",
  "wood_type.blue_skies.frostbright": "霜耀木",
  "wood_type.blue_skies.lunar": "明月木",
  "wood_type.blue_skies.dusk": "暮光木",
  "wood_type.blue_skies.maple": "枫木",
  "wood_type.blue_skies.cherry": "樱桃木",
  "wood_type.aether.skyroot": "天根木",
  "wood_type.twilightforest.twilight_oak": "暮色橡木",
  "wood_type.twilightforest.canopy": "苍穹木",
  "wood_type.twilightforest.mangrove": "红木",
  "wood_type.twilightforest.dark": "黑木",
  "wood_type.twilightforest.time": "时光木",
  "wood_type.twilightforest.transformation": "变化木",
  "wood_type.twilightforest.mining": "矿石木",
  "wood_type.twilightforest.sorting": "分类木",
  "wood_type.quark.blossom": "花木",
  "wood_type.quark.azalea": "杜鹃木",
  
  "leaves_type.biomesoplenty.fir": "杉树",
  "leaves_type.biomesoplenty.redwood": "红树",
  "leaves_type.biomesoplenty.mahogany": "桃花心",
  "leaves_type.biomesoplenty.jacaranda": "蓝花楹",
  "leaves_type.biomesoplenty.palm": "棕榈",
  "leaves_type.biomesoplenty.willow": "柳树",
  "leaves_type.biomesoplenty.dead": "枯死",
  "leaves_type.biomesoplenty.magic": "魔法",
  "leaves_type.biomesoplenty.umbran": "暗影",
  "leaves_type.biomesoplenty.hellbark": "地狱皮",
  "leaves_type.biomesoplenty.origin": "起源",
  "leaves_type.biomesoplenty.flowering_oak": "花橡",
  "leaves_type.biomesoplenty.rainbow_birch": "彩虹白桦",
  "leaves_type.biomesoplenty.yellow_autumn": "黄秋",
  "leaves_type.biomesoplenty.orange_autumn": "橙秋",
  "leaves_type.biomesoplenty.maple": "枫树",
  "leaves_type.biomesoplenty.white_cherry": "白色樱桃",
  "leaves_type.biomesoplenty.pink_cherry": "粉红色樱桃",
  "leaves_type.blue_skies.bluebright": "蓝辉",
  "leaves_type.blue_skies.starlit": "星荧",
  "leaves_type.blue_skies.frostbright": "霜耀",
  "leaves_type.blue_skies.lunar": "明月",
  "leaves_type.blue_skies.dusk": "暮光",
  "leaves_type.blue_skies.maple": "枫树",
  "leaves_type.blue_skies.cherry": "樱桃",
  "leaves_type.blue_skies.crescent_fruit": "新月果",
  "leaves_type.aether.skyroot": "天根",
  "leaves_type.aether.golden_oak": "金琥珀",
  "leaves_type.aether.crystal": "水晶",
  "leaves_type.aether.crystal_fruit": "结实的水晶",
  "leaves_type.aether.holiday": "节庆",
  "leaves_type.aether.decorated_holiday": "节庆装饰",
  "leaves_type.twilightforest.twilight_oak": "暮色橡",
  "leaves_type.twilightforest.canopy": "苍穹",
  "leaves_type.twilightforest.mangrove": "红树",
  "leaves_type.twilightforest.dark": "黑树",
  "leaves_type.twilightforest.time": "时光",
  "leaves_type.twilightforest.transformation": "变化",
  "leaves_type.twilightforest.mining": "矿石",
  "leaves_type.twilightforest.sorting": "分类",
  "leaves_type.twilightforest.thorn": "荆棘",
  "leaves_type.twilightforest.beanstalk": "豆茎",
  "leaves_type.twilightforest.rainbow_oak": "彩虹橡",
  "leaves_type.croptopia.cinnamon": "肉桂",
  "leaves_type.quark.blue_blossom": "雪霜花",
  "leaves_type.quark.lavender_blossom": "幽静花",
  "leaves_type.quark.orange_blossom": "温暖花",
  "leaves_type.quark.pink_blossom": "甜蜜花",
  "leaves_type.quark.yellow_blossom": "阳光花",
  "leaves_type.quark.red_blossom": "火热花"
```

2022-09-05 09:18 UTC, Dr-WeiAL commented on projects/1.18/assets/every-compat/everycomp/lang/zh_cn.json
>    "wood_type.twilightforest.dark": "黑木"
部分mod木材名添加

2022-09-05 09:19 UTC, ChuijkYahus commented on projects/1.18/assets/every-compat/everycomp/lang/zh_cn.json
>    "wood_type.twilightforest.dark": "黑木"
非常感谢！

2022-09-05 09:20 UTC, ChuijkYahus commented on projects/1.18/assets/every-compat/everycomp/lang/zh_cn.json
>    "wood_type.twilightforest.dark": "黑木"
话说这个`leaves_type`有效吗

2022-09-05 09:23 UTC, Dr-WeiAL requested changes
删除多余条目(

2022-09-05 09:23 UTC, Dr-WeiAL commented on projects/1.18/assets/every-compat/everycomp/lang/zh_cn.json
> +  "wood_type.twilightforest.dark": "黑木",
```suggestion

```

2022-09-05 10:48 UTC, Dr-WeiAL requested changes

2022-09-05 10:48 UTC, Dr-WeiAL commented on projects/1.18/assets/every-compat/everycomp/lang/zh_cn.json
> +  "wood_type.quark.azalea": "杜鹃木",
```suggestion
  "wood_type.quark.azalea": "杜鹃木",
  "wood_type.byg.aspen": "白杨木",
  "wood_type.byg.baobab": "猴面包木",
  "wood_type.byg.blue_enchanted": "蓝色魔法木",
  "wood_type.byg.cherry": "樱桃木",
  "wood_type.byg.cika": "锡卡木",
  "wood_type.byg.cypress": "柏木",
  "wood_type.byg.ebony": "乌木",
  "wood_type.byg.fir": "冷杉木",
  "wood_type.byg.green_enchanted": "绿色魔法木",
  "wood_type.byg.holly": "冬青木",
  "wood_type.byg.jacaranda": "蓝花楹木",
  "wood_type.byg.mahogany": "桃花心木",
  "wood_type.byg.mangrove": "红木",
  "wood_type.byg.maple": "枫木",
  "wood_type.byg.pine": "松木",
  "wood_type.byg.rainbow_eucalyptus": "彩虹桉木",
  "wood_type.byg.redwood": "红杉木",
  "wood_type.byg.skyris": "天际木",
  "wood_type.byg.willow": "柳木",
  "wood_type.byg.witch_hazel": "金缕梅木",
  "wood_type.byg.zelkova": "榉木",
  "wood_type.byg.sythian": "斯基泰木",
  "wood_type.byg.palm": "棕榈木",
  "wood_type.byg.lament": "哀叹木",
  "wood_type.byg.bulbis": "灯状菇木",
  "wood_type.byg.nightshade": "夜影木",
  "wood_type.byg.ether": "以太木",
  "wood_type.byg.imparius": "异蓝木",
```

2022-09-05 10:48 UTC, Dr-WeiAL commented on projects/1.18/assets/every-compat/everycomp/lang/zh_cn.json
> +  "leaves_type.quark.red_blossom": "火热花"
```suggestion
  "leaves_type.quark.red_blossom": "火热花",
  "leaves_type.byg.aspen": "白杨",
  "leaves_type.byg.baobab": "猴面包",
  "leaves_type.byg.blue_enchanted": "蓝色魔法",
  "leaves_type.byg.cika": "锡卡",
  "leaves_type.byg.cypress": "柏树",
  "leaves_type.byg.ebony": "乌树",
  "leaves_type.byg.fir": "冷杉",
  "leaves_type.byg.green_enchanted": "绿色魔法",
  "leaves_type.byg.holly": "冬青",
  "leaves_type.byg.jacaranda": "蓝花楹",
  "leaves_type.byg.mahogany": "桃花心",
  "leaves_type.byg.mangrove": "红树",
  "leaves_type.byg.maple": "枫树",
  "leaves_type.byg.pine": "松树",
  "leaves_type.byg.rainbow_eucalyptus": "彩虹桉",
  "leaves_type.byg.redwood": "红杉",
  "leaves_type.byg.skyris": "天际",
  "leaves_type.byg.willow": "柳树",
  "leaves_type.byg.witch_hazel": "金缕梅",
  "leaves_type.byg.zelkova": "榉树",
  "leaves_type.byg.palm": "棕榈",
  "leaves_type.byg.lament": "哀叹",
  "leaves_type.byg.nightshade": "夜影",
  "leaves_type.byg.ether": "以太",
  "leaves_type.byg.araucaria": "南洋杉",
  "leaves_type.byg.blooming_witch_hazel": "盛开的金缕梅",
  "leaves_type.byg.blue_spruce": "蓝色云杉",
  "leaves_type.byg.brown_birch": "棕色白桦",
  "leaves_type.byg.brown_oak": "棕色橡树",
  "leaves_type.byg.brown_zelkova": "棕色榉树",
  "leaves_type.byg.flowering_orchard": "盛开的果树",
  "leaves_type.byg.flowering_palo_verde": "盛开的扁轴",
  "leaves_type.byg.holly_berry": "结果的冬青",
  "leaves_type.byg.indigo_jacaranda": "靛青蓝花楹",
  "leaves_type.byg.flowering_jacaranda": "盛开的蓝花楹",
  "leaves_type.byg.flowering_indigo_jacaranda": "盛开的靛青蓝花楹",
  "leaves_type.byg.joshua": "短叶丝兰",
  "leaves_type.byg.ripe_joshua": "成熟的短叶丝兰",
  "leaves_type.byg.orange_birch": "橙色白桦",
  "leaves_type.byg.orange_oak": "橙色橡树",
  "leaves_type.byg.orange_spruce": "橙色云杉",
  "leaves_type.byg.orchard": "果树",
  "leaves_type.byg.palo_verde": "扁轴",
  "leaves_type.byg.pink_cherry": "粉红色樱桃",
  "leaves_type.byg.red_birch": "红色白桦",
  "leaves_type.byg.red_maple": "红色枫树",
  "leaves_type.byg.red_oak": "红色橡树",
  "leaves_type.byg.red_spruce": "红色云杉",
  "leaves_type.byg.ripe_orchard": "成熟的果树",
  "leaves_type.byg.silver_maple": "银色枫树",
  "leaves_type.byg.green_apple_skyris": "青苹果天际",
  "leaves_type.byg.white_cherry": "白色樱桃",
  "leaves_type.byg.yellow_birch": "黄色白桦",
  "leaves_type.byg.yellow_spruce": "黄色云杉",
  "leaves_type.byg.withering_oak": "凋零橡树",
  "leaves_type.byg.flowering_nightshade": "盛开的夜影",
  "leaves_type.byg.firecracker": "鸟尾花"
```

2022-09-05 15:03 UTC, ChuijkYahus commented
目前支持一览：

1. Aether 天境 由@Dr-WeiAL 提供
2. Architect's Palette
3. Ars Nouveau
4. Ars Elemental 目前无翻译
5. Better End #2246 
6. Biome Makeover #2213 
7. Biomes O' Plenty 由@Dr-WeiAL 提供
8. Blue Skies  由@Dr-WeiAL 提供
9. Botania  由@Dr-WeiAL 提供
10. BYG  由@Dr-WeiAL 提供
11. Caupona
12. Cultural Delights
13. Darker Depths
14. Ecologics
15. Enhanced Mushrooms
16. Extended Mushrooms
17. Forbidden & Arcanus
18. Greek Fantasy
19. Hexerei
20. Integrated Dynamics
21. Hexcasting
22. Malum
23. Mystical World
24. Occultism
25. Premium Wood
26. Pyromancer
27. Quark 由@Dr-WeiAL 提供
28. Structurize
29. Tinker's Construct
30. Terra Incognita
31. Terraqueous
32. TofuCraft
33. Twigs
34. Twilight Forest 由@Dr-WeiAL 提供
35. Undergarden

其中 5,6,16,17,18,23,25,28,30,31 未经测试，基本上是到源码（如果有）里面尽量扒出来的

2022-09-22 13:13 UTC, merged