Darker Depths 翻译提交与更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #2157
Opened 2022-07-04 14:54 UTC by ChuijkYahus

部分物品未译，原因同#1583
作者有够摸的（）

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-07-04 15:01 UTC, ChuijkYahus commented
/update-en darker-depths 1.16

2022-07-04 15:03 UTC, ChuijkYahus commented
1.16英文拉取错了

2022-07-09 10:32 UTC, WJXhhh commented
51,52行的“红石簇”和“红石簇块”中的簇是否可以改为晶簇（矿物的聚合体，红石应该也算是宝石矿物，而且这个mod和地下也有关系不是吗）

2022-07-10 14:36 UTC, ChuijkYahus commented
> 51,52行的“红石簇”和“红石簇块”中的簇是否可以改为晶簇（矿物的聚合体，红石应该也算是宝石矿物，而且这个mod和地下也有关系不是吗）

可以的，已经改了
不过这个物品根本没在游戏内出现过

2022-09-23 13:47 UTC, Cactusstudent commented on projects/1.16/assets/darker-depths/darkerdepths/lang/zh_cn.json
> +  "block.darkerdepths.grimestone_speleothem": "沉垢岩钟乳石",
这里的`Shale Speleothem`……`Speleothem`是洞穴沉积物没错，钟乳石也是其中的一种，但我觉得这里多少有点以偏概全（可能说的不太对？）或许可能找个其他的翻译替代下？

2022-09-23 16:04 UTC, ChuijkYahus commented on projects/1.16/assets/darker-depths/darkerdepths/lang/zh_cn.json
> +  "block.darkerdepths.grimestone_speleothem": "沉垢岩钟乳石",
这里的这些在方块形式上与quark在1.16的钟乳石差不多
而且quark的`钟乳石`就是`Speleothem`（）

2022-12-26 18:33 UTC, Ricky-fight commented on projects/1.16/assets/darker-depths/darkerdepths/lang/zh_cn.json
>    "block.darkerdepths.cracked_shale_bricks": "裂页岩砖",
```suggestion
  "block.darkerdepths.cracked_shale_bricks": "裂纹页岩砖",

```

2022-12-27 01:52 UTC, ChuijkYahus commented on projects/1.16/assets/darker-depths/darkerdepths/lang/zh_cn.json
>    "block.darkerdepths.cracked_shale_bricks": "裂页岩砖",
看了一眼1165游戏内表现
虽然是1.17更新的，但是1165没有同步，仍为`裂石砖`
但其余`裂纹`已同步，那就同步吧

2023-01-17 00:57 UTC, Cactusstudent commented
1.18版本的 L147 L156 未汉化

2023-01-17 04:03 UTC, ChuijkYahus commented
> 1.18版本的 L147 L156 未汉化

理由同#1583
这两个东西从未出现在游戏内过，give也没有
模组也是闭源

2023-03-04 17:40 UTC, DrIceTea123 requested changes
这个pr还要吗（）
大概看了下，没啥别的问题了

2023-03-04 17:40 UTC, DrIceTea123 commented on projects/1.16/assets/darker-depths/darkerdepths/lang/zh_cn.json
>    "block.darkerdepths.cracked_limestone_bricks": "裂石灰岩砖",
L41改了这里也改了吧

2023-03-04 17:40 UTC, DrIceTea123 commented on projects/1.16/assets/darker-depths/darkerdepths/lang/zh_cn.json
>    "block.darkerdepths.elytrine_ore": "翔翱水晶矿石",
是`翱翔水晶`还是`翔翱水晶`，原文如此吗？
同步修改L48和1.18

2023-03-05 03:37 UTC, ChuijkYahus commented on projects/1.16/assets/darker-depths/darkerdepths/lang/zh_cn.json
>    "block.darkerdepths.elytrine_ore": "翔翱水晶矿石",
原文如此

2023-03-05 03:37 UTC, ChuijkYahus commented on projects/1.16/assets/darker-depths/darkerdepths/lang/zh_cn.json
>    "block.darkerdepths.cracked_limestone_bricks": "裂石灰岩砖",
也行

2023-03-05 03:38 UTC, ChuijkYahus commented
darkerdepth这么长时间过去都出1192了

2023-03-05 03:38 UTC, ChuijkYahus commented
darkerdepth这么长时间过去都出1192了
紧急更新一下

2023-03-11 07:00 UTC, DrIceTea123 approved these changes

2023-07-08 09:46 UTC, mamaruo approved these changes

2023-07-14 19:51 UTC, merged

2023-08-03 02:47 UTC, dovisutu commented
> ⚠ 检测到了一个语言文件，但是提交的路径不正常。请检查你的提交路径：projects/1.19/darker-depths/darkerdepths/lang/zh_cn.json

~bot的悲鸣~
ping @ChuijkYahus

2023-08-03 02:57 UTC, dovisutu commented
* 好像看错commit历史了......抱歉