EnderIO 1.19 翻译新增
CFPAOrg/Minecraft-Mod-Language-Package pull request #2160
Opened 2022-07-05 10:52 UTC by mamaruo

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
<s>- [] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；</s> 亲爱的Bot你一定会帮我检查的
- [x 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-07-06 05:06 UTC, RCqaq commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "item.enderio.enderface_conduits": "Enderface 导管",
```suggestion
  "item.enderio.enderface_conduits": "末影接口导管",
```

2022-07-06 05:06 UTC, RCqaq commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "item.enderio.enderface_conduits": "Enderface 导管",
涉及`Enderface`的都没翻译？

2022-07-06 05:06 UTC, RCqaq commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "block.enderio.alloy_smelter": "Alloy Smelter",
```suggestion
  "block.enderio.alloy_smelter": "合金炉",
```

2022-08-28 12:36 UTC, Cactusstudent commented
提示，最新的官方英文增加了一个新key`"block.enderio.impulse_hopper": "Impulse Hopper",`

2023-02-20 15:57 UTC, ZHAY10086 commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "message.enderio.soul_vial.error_boss": "想得美，Boss 可不喜欢瓶子。",
```suggestion
  "message.enderio.soul_vial.error_boss": "想得美，Boss可不喜欢瓶子。",
```

2023-02-20 15:57 UTC, ZHAY10086 commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "description.enderio.enchantment.repellent": "有几率将攻击者传送走\n附魔等级越高，传送几率越大，传送得越远",
```suggestion
  "description.enderio.enchantment.repellent": "有概率将攻击者传送走\n魔咒等级越高，传送概率越大，传送距离越远",
```

2023-02-20 15:57 UTC, ZHAY10086 commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "description.enderio.enchantment.soulbound": "使物品免于死亡掉落。\n注意：多数墓碑模组非常愚蠢，导致该附魔无法正常工作！",
```suggestion
  "description.enderio.enchantment.soulbound": "使物品免于死亡掉落。\n注意：多数墓碑模组非常愚蠢，会导致该魔咒无法正常工作！",
```

2023-02-20 15:57 UTC, ZHAY10086 commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "gui.enderio.grinding_ball": "剩余量：%s%%\\n半自磨机磨珠\\n主产品产量：%s%%\\n副产品产量：%s%%\\n能量消耗：%s%%",
```suggestion
  "gui.enderio.grinding_ball": "剩余量：%s%%\\n半自磨机磨珠\\n主产物产量：%s%%\\n副产物产量：%s%%\\n能量消耗：%s%%",
```

2023-02-20 15:57 UTC, ZHAY10086 commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "item.enderio.location_printout": "位置记录",
这个是不是有一点问题？

2023-03-04 17:30 UTC, DrIceTea123 requested changes
这个pr还改吗（）
帮忙查了一点小问题，此外可能因为版本更新，中间有些内容有点不符，看着改一下吧
还有就是Enderface相关的内容还没翻译

2023-03-04 17:30 UTC, DrIceTea123 commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "info.enderio.darksteel.upgrade.empowered.absorption": "%s%% 的耐久损耗被能量吸收",
既然L802已经描述成μI了，这里也加上μI会不会好一点
原文：`%s%% damage absorbed by µI`

2023-03-04 17:30 UTC, DrIceTea123 commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "info.enderio.darksteel.upgrade.spoon.description": "有了叉子，谁还要锹？",
这里是勺子

2023-03-04 17:30 UTC, DrIceTea123 commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "item.enderio.cake_base": "蛋糕底座",
是不是`蛋糕胚`

2023-03-04 17:30 UTC, DrIceTea123 commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "item.enderio.dark_steel_upgrade_penetration_2": null,
这里为什么是null？是因为之前这里没更新吗？
下文也有相同问题

2023-03-04 17:30 UTC, DrIceTea123 commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "item.enderio.ender_crystal_powder": "末影水晶粉",
这里名字改了，原文是`Grains of the End`

2023-03-04 17:30 UTC, DrIceTea123 commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "item.enderio.enderios": "“末影麦片”",
？为什么是末影麦片
原文：`\"Enderios\"`

2023-03-04 17:30 UTC, DrIceTea123 commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "item.enderio.withering_powder": "天气水晶粉",
这好像是`凋零粉`不是`天气水晶粉`

2023-03-05 16:28 UTC, mamaruo commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "block.enderio.end_steel_machine_chassis": "末地钢机器框架",
![image](https://user-images.githubusercontent.com/37480168/222973034-09c9618b-b321-47d3-a217-71faf1b358bc.png)
我也很难办啊

mark 一个，之后给作者发pr

2023-03-05 16:33 UTC, mamaruo commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "item.enderio.cake_base": "蛋糕底座",
[物品/方块] [蛋糕底座 (Cake Base)](https://www.mcmod.cn/item/154991.html) - [EIO]末影接口 (Ender IO) 

没必要吧

2023-03-05 16:38 UTC, mamaruo commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "item.enderio.ender_crystal_powder": "末影水晶粉",
并未改名，想把作者刀了
[物品/方块] 末影水晶 (Ender Crystal) - [EIO]末影接口 (Ender IO) 
https://www.mcmod.cn/item/11501.html
[物品/方块] 末影水晶粉 (Grains of the End) - [EIO]末影接口 (Ender IO) 
https://www.mcmod.cn/item/53338.html

2023-03-05 16:40 UTC, mamaruo commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "item.enderio.enderios": "“末影麦片”",
我也不知啊，这是沿用了初代翻译
[物品/方块] “末影麦片” ("Enderios") - [EIO]末影接口 (Ender IO) 
https://www.mcmod.cn/item/11528.html

2023-03-05 16:43 UTC, mamaruo commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "item.enderio.enderios": "“末影麦片”",
我也不知啊，这是沿用了初代翻译
[物品/方块] “末影麦片” ("Enderios") - [EIO]末影接口 (Ender IO) 
https://www.mcmod.cn/item/11528.html

2023-03-05 16:44 UTC, mamaruo commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "item.enderio.ender_crystal_powder": "末影水晶粉",
并未改名，想把作者刀了
[物品/方块] 末影水晶 (Ender Crystal) - [EIO]末影接口 (Ender IO) 
https://www.mcmod.cn/item/11501.html
[物品/方块] 末影水晶粉 (Grains of the End) - [EIO]末影接口 (Ender IO) 
https://www.mcmod.cn/item/53338.html

2023-07-01 08:40 UTC, mamaruo commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "block.enderio.end_steel_machine_chassis": "末地钢机器框架",
现在没这个物品了

2023-07-08 06:23 UTC, mamaruo commented on projects/1.18/assets/ender-io/enderio/lang/zh_cn.json
> +  "item.enderio.enderface_conduits": "Enderface 导管",
废键，直到现在都没有实现

2023-07-09 05:42 UTC, Js23333 commented
半自磨机能否继续沿用“SAG磨粉机”

2023-07-09 07:38 UTC, Js23333 commented
淬凋之刃/箭以及淬凋弩箭的淬凋能否改成凋亡或者凋零

2023-07-10 16:07 UTC, mamaruo commented
> 淬凋之刃/箭以及淬凋弩箭的淬凋能否改成凋亡或者凋零

理由？

2023-08-13 07:40 UTC, Cactusstudent commented
那这个PR是关还是继续维护呢？

2023-08-13 16:37 UTC, mamaruo commented
> 淬凋之刃/箭以及淬凋弩箭的淬凋能否改成凋亡或者凋零

这些魔咒又合并了，沿用原译“凋亡”

2023-08-13 16:37 UTC, closed without merging