immersive weathering 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2172
Opened 2022-07-09 02:18 UTC by zizunsi

- [ ] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [ ] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-10-24 09:30 UTC, Cactusstudent requested changes
还好标点不多

2022-10-24 09:55 UTC, Cactusstudent requested changes
记得用update-en

2022-10-24 09:55 UTC, Cactusstudent commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_ch.json
> +  "block.immersive_weathering.exposed_iron_trapdoor": "斑驳的铁活版门",
后面author或者maintain用replace把这个换了

2022-10-24 09:55 UTC, Cactusstudent commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_ch.json
> +  "block.immersive_weathering.cryosol": "冷冻剂",
```suggestion
  "block.immersive_weathering.cryosol": "冻土",
```

2022-10-24 09:55 UTC, Cactusstudent commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_ch.json
> +  "block.immersive_weathering.vertisol": "迷迭香",
```suggestion
  "block.immersive_weathering.vertisol": "变性土",
```

2022-10-24 09:55 UTC, Cactusstudent commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_ch.json
> +  "block.immersive_weathering.fluvisol": "膨转土",
```suggestion
  "block.immersive_weathering.fluvisol": "冲积土",
```

2022-10-24 09:57 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_ch.json
> +  "advancements.immersive_weathering.fulgurite.description": "找到一个雷击岩,这是一个罕见的方块,只在闪电击中沙子的地方出现",
漏了一个

2022-10-24 09:57 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_ch.json
> +  "block.immersive_weathering.fluvisol": "膨转土",
冲击土（应该）

2022-10-25 05:56 UTC, Cactusstudent commented
/replace 活版门 活板门

2022-11-16 09:49 UTC, ChuijkYahus reviewed
粗看了一下

2022-11-16 09:49 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_ch.json
> +  "block.immersive_weathering.cracked_brick_vertical_slab": "裂石竖直台阶",
```suggestion
  "block.immersive_weathering.cracked_brick_vertical_slab": "裂纹红砖竖直台阶",
```

2022-11-16 09:49 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_ch.json
> +  "block.immersive_weathering.cracked_stone_brick_vertical_slab": "裂石砖竖直台阶",
```suggestion
  "block.immersive_weathering.cracked_stone_brick_vertical_slab": "裂纹石砖竖直台阶",
```

2022-11-16 09:49 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_ch.json
> +  "block.immersive_weathering.cracked_nether_brick_vertical_slab": "裂纹下界砖块竖直台阶",
```suggestion
  "block.immersive_weathering.cracked_nether_brick_vertical_slab": "裂纹下界砖竖直台阶",
```

2022-11-16 09:49 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_ch.json
> +  "advancements.immersive_weathering.eat_azalea_flower.description": "吃一些杜鹃花，你知道你想",
```suggestion
  "advancements.immersive_weathering.eat_azalea_flower.description": "吃一些杜鹃花，你知道你想这么做",
```

2022-11-16 09:49 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_ch.json
> +  "advancements.immersive_weathering.fulgurite.description": "找到一个雷击岩，这是一个罕见的方块，只在闪电击中沙子的地方出现",
```suggestion
  "advancements.immersive_weathering.fulgurite.description": "找到一个雷击岩，这是一种罕见的方块，只在闪电击中沙子的地方出现",
```

2022-11-16 09:49 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_ch.json
> +  "advancements.immersive_weathering.rust_on.description": "用湿海绵擦拭铁块!",
```suggestion
  "advancements.immersive_weathering.rust_off.description": "铁一旦锈得太厉害, 就不可能刮掉 :(",
  "advancements.immersive_weathering.rust_on.title": "生锈",
  "advancements.immersive_weathering.rust_on.description": "用湿海绵擦拭铁块！",
```
上面那个是颜文字

2022-11-16 09:49 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_ch.json
> +  "advancements.immersive_weathering.rust_off.title": "擦掉——在等什么？？",
```suggestion
  "advancements.immersive_weathering.rust_off.title": "除锈——等下你在说啥？",
```

2022-11-16 09:49 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_ch.json
> +  "advancements.immersive_weathering.bark_on.description": "在去皮原木上放树皮",
```suggestion
  "advancements.immersive_weathering.bark_on.description": "往去皮原木上放上树皮",
```

2022-11-16 09:49 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_ch.json
> +  "advancements.immersive_weathering.moss.description": "你吃下了苔藓，尝起来……藓藓的，你的生命值被藓翻了",
```suggestion
  "advancements.immersive_weathering.moss.description": "你吃下了苔藓，尝起来……藓甜爽口，你的生命值被藓翻了",
```

2022-12-21 07:05 UTC, dovisutu commented
见鬼了，中文文件路径居然是错的......

/mv projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_ch.json projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_cn.json

2022-12-21 13:52 UTC, dovisutu commented
/mv projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_ch.json projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_cn.json

2022-12-21 13:54 UTC, dovisutu commented
```
immersive_weathering-1.18 中文语言文件共有 236 个 Key； 英文语言文件共有 236 个 Key
immersive_weathering-1.18 模组内语言文件共有 364 个 Key；
```
坏 可能拖的太久，模组更新了:rofl:

2022-12-26 17:44 UTC, Ricky-fight commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_cn.json
> +  "item.immersive_weathering.oak_bark": "橡树皮",
```suggestion
  "item.immersive_weathering.oak_bark": "橡树树皮",
```

2022-12-26 17:44 UTC, Ricky-fight commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_cn.json
> +  "item.immersive_weathering.dark_oak_bark": "深色橡树皮",
```suggestion
  "item.immersive_weathering.dark_oak_bark": "深色橡树树皮",
```

2022-12-26 17:44 UTC, Ricky-fight commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_cn.json
> +  "advancements.immersive_weathering.fulgurite.title": "震惊的发现",
```suggestion
  "advancements.immersive_weathering.fulgurite.title": "令人震惊的发现",
```

2023-07-08 09:45 UTC, mamaruo commented
我对比了“官方中文”和“本PR”的翻译，结果如下：

### 两者皆有且中文有差异

<details><summary>点击展开/收起</summary>
<p>

| **键** | **英文** | **官方中文** | **本PR** |
|---|---|---|---|
| advancements.immersive_weathering.moss.title | Perpetuate the Cycle? | 延续生命存在的循环？ | 延续生命的循环？ |
| advancements.immersive_weathering.moss.description | \(You ate the moss\.\), \(Tastes\.\.\. mossy\.\), \(Your HP was mossed out\.\) | （你吃掉了苔藓。），（尝起来…藓藓的。），（你的HP苔高到了极藓。） | 你吃下了苔藓，尝起来……藓甜爽口，你的生命值被藓翻了 |
| advancements.immersive_weathering.ice_sickle.title | Chill Out | 冷静一下 | 冷静下来 |
| advancements.immersive_weathering.ice_sickle.description | Slay a Blaze using its greatest fear, an Ice Sickle | 用烈焰人最害怕的东西——冰镰来杀死它 | 用烈焰人最大的恐惧——冰镰杀死它 |
| advancements.immersive_weathering.mulch.title | Mulch Better | 化作春泥更护根 | 更好的土壤 |
| advancements.immersive_weathering.mulch.description | Craft some Mulch, it stays hydrated, weeds cant grow on it and crops grow fast\! | 合成一些护根。护根可以保持湿润，还能防止野草生长并提升农作物的生长速度！ | 制作一些沃土, 这是敬业的农民最好的朋友 |
| advancements.immersive_weathering.flower_crown.title | Flower Power | 花之力 | 花之力量 |
| advancements.immersive_weathering.flower_crown.description | Put on a Flower Crown, the bees think you look cute in it | 戴上花冠，蜜蜂们觉得你戴着很可爱 | 戴上花冠，蜜蜂觉得你戴着很可爱 |
| advancements.immersive_weathering.eat_azalea_flower.title | Flower Devour | 花朵吞噬者 | 吃花 |
| advancements.immersive_weathering.eat_azalea_flower.description | Eat some Azalea Flowers, you know you want to | 吃些杜鹃花吧，你知道你想尝尝的 | 吃一些杜鹃花，你知道你想这么做 |
| advancements.immersive_weathering.fulgurite.title | Shocking Discovery | 雷人的发现 | 令人震惊的发现 |
| advancements.immersive_weathering.fulgurite.description | Find a Fulgurite, a rare block that only occurs where lightning strikes sand | 找到雷击石——一种只能在被闪电击中的沙子上找到的稀有方块 | 找到一个雷击岩，这是一种罕见的方块，只在闪电击中沙子的地方出现 |
| advancements.immersive_weathering.dirts.title | Soil Superfan | 土壤发烧友 | 土壤相聚 |
| advancements.immersive_weathering.bark_off.title | Bark Off | 去皮 | 树皮 |
| advancements.immersive_weathering.bark_off.description | Scrape Bark off a Log | 给原木削皮 | 从木头上刮下树皮！ |
| advancements.immersive_weathering.bark_on.title | Bark On | 裹皮 | 放上树皮 |
| advancements.immersive_weathering.bark_on.description | Apply Bark to a Stripped Log | 把树皮裹到去皮原木上 | 往去皮原木上放上树皮 |
| advancements.immersive_weathering.rust_off.title | Rust Off\-\- Wait what?? | 除锈——等下什么？？ | 除锈——等下你在说啥？ |
| advancements.immersive_weathering.rust_off.description | Once iron has rusted too much, its impossible to scrape the rust off :pensive: | 铁若是锈得太厉害，就不可能把锈刮掉了:pensive: | 铁一旦锈得太厉害, 就不可能刮掉 :\( |
| advancements.immersive_weathering.rust_on.title | Rust On | 增锈 | 生锈 |
| advancements.immersive_weathering.rust_on.description | Apply a Wet Sponge to blocks made of Iron | 对铁制方块使用湿海绵 | 用湿海绵擦拭铁块！ |
| death.attack.icicle.player | %1$s was impaled on an icicle whilst fighting %2$s | %1$s在与%2$s战斗时被冰凌刺穿了 | %1$s在与%2$s战斗时中被冰凌刺穿了 |
| death.attack.fallingIcicle | %1$s was skewered by a falling icicle | %1$s被坠落的冰凌刺穿了 | %1$s被落下的冰凌刺穿了 |
| death.attack.fallingIcicle.player | %1$s was skewered by a falling icicle whilst fighting %2$s | %1$s在与%2$s战斗时被坠落的冰凌刺穿了 | %1$s在与%2$s战斗时被落下的冰凌刺穿了 |
| subtitles.block.icicle.land | Icicle crashes down | 冰凌：塌落 | 冰凌坠落 |
| block.immersive_weathering.fulgurite | Fulgurite | 雷击石 | 雷击岩 |
| block.immersive_weathering.soot | Soot | 烟灰 | 灰烬 |
| block.immersive_weathering.sand_layer_block | Sand Pile | 沙堆 | 沙子 |
| block.immersive_weathering.red_sand_layer_block | Red Sand Pile | 红沙堆 | 红沙 |
| block.immersive_weathering.ash_layer_block | Ash Pile | 灰烬堆 | 灰烬 |
| item.immersive_weathering.tallow | Tallow | 油脂 | 动物脂油 |
| block.immersive_weathering.fluvisol | Fluvisol | 冲积土 | 冲击土 |
| block.immersive_weathering.cracked_mud | Cracked Mud | 裂纹泥巴 | 开裂的泥土 |
| block.immersive_weathering.permafrost | Permafrost | 永久冻土 | 永冻土 |
| block.immersive_weathering.mulch_block | Mulch | 护根 | 沃土 |
| block.immersive_weathering.nulch_block | Nulch | 下界护根 | 下界沃土 |
| block.immersive_weathering.charred_slab | Charred Slab | 烧焦的木台阶 | 烧焦的台阶 |
| block.immersive_weathering.charred_stairs | Charred Stairs | 烧焦的木楼梯 | 烧焦的楼梯 |
| block.immersive_weathering.charred_fence | Charred Fence | 烧焦的木栅栏 | 烧焦的栅栏 |
| block.immersive_weathering.charred_fence_gate | Charred Fence Gate | 烧焦的木栅栏门 | 烧焦的栅栏门 |
| block.immersive_weathering.rotten_log | Rotten Log | 腐烂原木 | 腐烂的原木 |
| block.immersive_weathering.rotten_planks | Rotten Planks | 腐烂木板 | 腐烂的木板 |
| block.immersive_weathering.rotten_slab | Rotten Slab | 腐烂木台阶 | 腐烂的台阶 |
| block.immersive_weathering.rotten_stairs | Rotten Stairs | 腐烂木楼梯 | 腐烂的楼梯 |
| block.immersive_weathering.rotten_fence | Rotten Fence | 腐烂木栅栏 | 腐烂的栅栏 |
| block.immersive_weathering.rotten_fence_gate | Rotten Fence Gate | 腐烂木栅栏门 | 腐烂的栅栏门 |
| block.immersive_weathering.mossy_brick_vertical_slab | Mossy Brick Vertical Slab | 覆苔红砖竖直台阶 | 苔石砖竖直台阶 |
| block.immersive_weathering.mossy_stone_stairs | Mossy Stone Stairs | 覆苔石头楼梯 | 覆苔石楼梯 |
| block.immersive_weathering.mossy_stone_slab | Mossy Stone Slab | 覆苔石头台阶 | 覆苔石台阶 |
| block.immersive_weathering.mossy_stone_vertical_slab | Mossy Stone Vertical Slab | 覆苔石头竖直台阶 | 覆苔圆石竖直台阶 |
| block.immersive_weathering.mossy_stone_wall | Mossy Stone Wall | 覆苔石头墙 | 覆苔石墙 |
| block.immersive_weathering.stone_wall | Stone Wall | 石头墙 | 石墙 |
| item.immersive_weathering.deepslate_tile | Deepslate Tile | 深板岩瓦 | 深板岩瓦片 |
| block.immersive_weathering.exposed_iron_trapdoor | Exposed Iron Trapdoor | 斑驳的铁活版门 | 斑驳的铁活板门 |
| block.immersive_weathering.weathered_iron_trapdoor | Weathered Iron Trapdoor | 锈蚀的铁活版门 | 锈蚀的铁活板门 |
| block.immersive_weathering.rusted_iron_trapdoor | Rusted Iron Trapdoor | 氧化的铁活版门 | 氧化的铁活板门 |
| block.immersive_weathering.waxed_iron_trapdoor | Waxed Iron Trapdoor | 涂蜡铁活版门 | 涂蜡铁活板门 |
| block.immersive_weathering.waxed_exposed_iron_trapdoor | Waxed Exposed Iron Trapdoor | 斑驳的涂蜡铁活版门 | 斑驳的涂蜡铁活板门 |
| block.immersive_weathering.waxed_weathered_iron_trapdoor | Waxed Weathered Iron Trapdoor | 锈蚀的涂蜡铁活版门 | 锈蚀的涂蜡铁活板门 |
| block.immersive_weathering.waxed_rusted_iron_trapdoor | Waxed Rusted Iron Trapdoor | 氧化的涂蜡铁活版门 | 氧化的涂蜡铁活板门 |

</p>
</details>

### 只在 官方中文 中有

<details><summary>点击展开/收起</summary>
<p>

| **键** | **英文** | **官方中文** | **本PR** |
|---|---|---|---|
| itemGroup.immersive_weathering.immersive_weathering | Immersive Weathering | 沉浸式风化 | 🚫 |
| advancements.immersive_weathering.weeds.title | Weed Wacker | 斩草除根 | 🚫 |
| advancements.immersive_weathering.weeds.description | Pick some Weeds\. Weeds only grow on Farmland near tall grass | 清理一些野草。野草只会生长在高草丛附近的耕地上。 | 🚫 |
| advancements.immersive_weathering.pond_water.title | Why would you do this??? | 你为什么要这么做？？？ | 🚫 |
| advancements.immersive_weathering.pond_water.description | Silica\. | 二氧化硅。 | 🚫 |
| advancements.immersive_weathering.sands.title | Coarse and Rough | 沙气腾腾 | 🚫 |
| advancements.immersive_weathering.sands.description | Obtain every Sandy block | 获得所有积沙的方块 | 🚫 |
| advancements.immersive_weathering.crack_on.title | Crack On | 开裂 | 🚫 |
| advancements.immersive_weathering.crack_on.description | Crack a brick block using any pickaxe | 用任意镐把砖块凿裂 | 🚫 |
| advancements.immersive_weathering.crack_off.title | Crack Off | 除裂 | 🚫 |
| advancements.immersive_weathering.crack_off.description | Repair a cracked block using its matching brick item | 用一块砖修补与其对应的裂纹砖块 | 🚫 |
| advancements.immersive_weathering.moss_on.title | Moss On | 覆苔 | 🚫 |
| advancements.immersive_weathering.moss_on.description | Apply a Moss Clump to Stone, Stone Bricks, Cobblestone or Bricks | 把苔藓丛覆盖到石头、石砖、圆石或红砖块上 | 🚫 |
| advancements.immersive_weathering.moss_off.title | Moss Off | 除苔 | 🚫 |
| advancements.immersive_weathering.moss_off.description | Scrape moss off a mossy block using Shears | 用剪刀刮掉覆苔方块上的苔藓 | 🚫 |
| advancements.immersive_weathering.moss_off_2.title | I said, MOSS OFF | 我说了，除苔！ | 🚫 |
| advancements.immersive_weathering.moss_off_2.description | Burn the moss off a mossy block and prevent it from growing back by using a Flint and Steel | 用打火石烧掉覆苔方块上的苔藓，防止其再次生长 | 🚫 |
| advancements.immersive_weathering.sand_off.title | Sand Off | 除沙 | 🚫 |
| advancements.immersive_weathering.sand [...]

2023-07-30 10:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2172) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2172) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: Cactusstudent<br/>:white_check_mark: mamaruo<br/>:x: zizunsi<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2172) it.</sub>

2023-09-09 03:43 UTC, ChuijkYahus commented
大概这模组的翻译是需要更新了

2023-09-09 03:43 UTC, ChuijkYahus commented
大概这模组更新了，翻译也需要更新

2024-01-23 06:19 UTC, closed without merging