Project expansion 1.18版本 英语文本和翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2194
Opened 2022-07-12 08:47 UTC by ArgonCrystal

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-07-12 15:13 UTC, mamaruo reviewed
检查半角符号
you 建议一律使用“你”

2022-07-13 18:08 UTC, mamaruo requested changes
随便看了看。问题有点多。

另外：是否要统一EMC的大小写？

2022-07-13 18:08 UTC, mamaruo commented on projects/1.18/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"gui.projectexpansion.config.format_emc.desc": "如果EMC应该格式化为M/B/T/etc",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |

If EMC should be formatted as M/B/T/etc

```suggestion
	"gui.projectexpansion.config.format_emc.desc": "EMC值是否应格式化为M、B、T等形式",
```

2022-07-13 18:08 UTC, mamaruo commented on projects/1.18/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"gui.projectexpansion.config.full_number_names.desc": "如果应该使用完整的数字名称（百万/十亿/万亿）而不是缩写",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |

这个数字名是硬编码的吧，既然游戏内显示无法汉化，这里的说明也不应汉化

```suggestion
	"gui.projectexpansion.config.full_number_names.desc": "是否应使用完整的数字名（Million/Billion/Trillion）而不是缩写",
```

2022-07-13 18:08 UTC, mamaruo commented on projects/1.18/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"gui.projectexpansion.config.notify_command_changes.desc": "通过/emc通知用户有关他们的某些更改。",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |

不是很好翻这句。但是只能说好好看清楚句子结构。
Notify users something is changed about them via /emc.

```suggestion
	"gui.projectexpansion.config.notify_command_changes.desc": "通知用户由/emc产生的变更。",
```
```suggestion
	"gui.projectexpansion.config.notify_command_changes.desc": "在使用/emc产生变更后，通知相关用户。",
```

2022-12-22 14:59 UTC, dovisutu commented
- 7+7时限进入第一阶段。从该评论发出的时间开始计时。

ping @ArgonCrystal

2023-01-01 03:51 UTC, dovisutu commented on projects/1.18/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"command.projectexpansion.emc.remove.negative": "无法从%s中移除%s emc，因为这会使它们的emc为负数。",
暴力译法：不管对象是什么都译成“其”
这里的their似乎是无性别的第三人称单数代词？

2023-01-01 03:52 UTC, dovisutu commented
- 7+7时限进入第二阶段。从该评论发出的时间开始计时。

ping @ArgonCrystal

2023-01-01 12:09 UTC, Ricky-fight commented on projects/1.18/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"command.projectexpansion.emc.remove.negative": "无法从%s中移除%s emc，因为这会使它们的emc为负数。",
这个命令是服务器用的，作用是%s(Player1)被移除%s（数量的）EMC，这么译到时候显示出来会有点怪。可以参考下面#2762提到的个人译法。
```suggestion
	"command.projectexpansion.emc.remove.negative": "无法移除%2%s的%1%sEMC，因为这会让他的EMC为负。",
```

2023-01-10 04:19 UTC, dovisutu commented
- 7+7时限已到。根据处理未相应提交的[试行]处理方案，关闭本提交。若可继续进行更改，可重新打开本提交，或创建新提交。

2023-01-10 04:19 UTC, closed without merging