Interstellar exoplanets  翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #2199
Opened 2022-07-13 10:37 UTC by FuBangkun

- [x'] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-07-13 18:14 UTC, mamaruo commented
#2072 我建议没有中译的星体保留英文

/diff

2022-07-14 01:08 UTC, WJXhhh commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +information.dev.exoplanets:beta.1=继续您同意您将要遵守的条款
这里怎么读起来怪怪的

2022-07-14 17:46 UTC, mamaruo requested changes
问题有点多

2022-07-14 17:46 UTC, mamaruo commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +exoplanets.versions.startingDownload=[{"text":"正在开始下载。请不要卸下硬盘。 享受 ","color":"aqua"},{"text":"星际：系外行星？","color":"green"}]
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |

英文中用来分隔单词的空格可以删去了

```suggestion
exoplanets.versions.startingDownload=[{"text":"正在开始下载……请不要卸下硬盘。喜欢玩","color":"aqua"},{"text":"星际：系外行星？","color":"green"}]
```
原文：**Starting download . . . . . Please do not remove your hard disk. Enjoying **

2022-07-14 17:46 UTC, mamaruo commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +exoplanets.versions.startingDownload2=[{"text":" 考虑在 ","color":"aqua"},{"text":"Patreon","color":"gold","hoverEvent":{"action":"show_text","value":{"text":"点击此处进入ROMVoid95的Patreon","color":"light_pur
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |

仍然是空格问题
总觉得这句很怪，能在游戏内截一个图吗

```suggestion
exoplanets.versions.startingDownload2=[{"text":"考虑在","color":"aqua"},{"text":"Patreon","color":"gold","hoverEvent":{"action":"show_text","value":{"text":"点击此处进入ROMVoid95的Patreon","color":"light_purple"}},"clickEvent":{"action":"open_url","value":"http://www.patreon.com/romvoid95"}},{"text":"上支持[","color":"aqua"},{"text":"ROMVoid95","color":"light_purple"},{"text":"]!","color":"aqua"}]
```
原文：** Consider supporting **

2022-07-14 17:46 UTC, mamaruo commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +exoplanets.versions.doneDownloading=已完成下载。请删除旧的星际：系外行星，再重新加载游戏以进行更新。
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |
```suggestion
exoplanets.versions.doneDownloading=已完成下载……请删除旧的星际：系外行星JAR文件，再重新加载游戏来更新。
```
原文：**Finished downloading . . . . . Delete your old Exoplanets jar and reload your game to update.**

2022-07-14 17:46 UTC, mamaruo commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +exoplanets.versions.downloadedAlready=您已经下载好了最新版本。请关闭你的游戏，从你的mods文件夹中删除旧版本，并再次加载更新！
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |
```suggestion
exoplanets.versions.downloadedAlready=您已经下载最新版本。关闭游戏，在mods文件夹中删除旧版本，再启动游戏来更新！
```
原文：**You already downloaded the latest version. Close your game, delete the old version from your mods folder and load it again to update!**

2022-07-14 17:46 UTC, mamaruo commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +exoplanets.gui.failed=尝试打开链接时出现问题
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |

这翻得什么玩意

原文：
exoplanets.gui.discordLink=Discord Invite
exoplanets.gui.failed=There was a problem while trying to open Discord Invite Link

2022-07-14 17:46 UTC, mamaruo commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +information.exoplanets:beta.3=因为它可能没有完成或优化。
| **审查级别**    | 备注 |
|--------------|----|
| ⚪ 轻微 / 不阻止合并但需三思  |    |
```suggestion
information.exoplanets:beta.3=因为它可能没做完成或优化好。
```
原文：**as it may not be finished and/or optimized.**

2022-07-14 17:46 UTC, mamaruo commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +information.dev.exoplanets:beta.3=§c权限由模组开发者授予§r
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |

一句话你给拆成了3句译
**另外这个Continue大写了，需要验证是不是点一个按钮叫“Continue”**

```suggestion
information.dev.exoplanets:beta.1=§c通过继续，你同意如下条款：
information.dev.exoplanets:beta.2=§c你不能分发此开发版本，
information.dev.exoplanets:beta.3=§c除非得到开发者的事先许可§r
```
原文：
information.dev.exoplanets:beta.1=§cBy Continuing you agree on the terms that you will
information.dev.exoplanets:beta.2=§cnot distribute this development build unless prior
information.dev.exoplanets:beta.3=§cpermissions are by the mod developer§r

2022-07-14 17:46 UTC, mamaruo commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +planet.kepler1649c=Kepler 1649c
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |
```suggestion
planet.kepler1649b=开普勒1649 b
planet.kepler1649c=开普勒1649 c
```
原文：

galaxy.wormhole=§eWormhole

2022-07-14 17:46 UTC, mamaruo commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +planet.wolf1061d=Wolf 1061 D
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |
```suggestion
planet.wolf1061b=沃夫1061 B
planet.wolf1061c=沃夫1061 C
planet.wolf1061d=沃夫1061 D
```

2022-07-14 17:46 UTC, mamaruo commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +tile.exoplanets.stand_console.name=控制台支架
| **审查级别**    | 备注 |
|--------------|----|
| ⚪ 轻微 / 不阻止合并但需三思  |    |

这什么东西，存疑

原文：
tile.exoplanets.stand_console.name=Console Stand
tile.exoplanets.metaldecoration.name=Floor Grating

2022-07-14 17:46 UTC, mamaruo commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +tile.exoplanets.metalore9.name=锌矿
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   原版标准译名   |

矿石

2022-07-15 05:21 UTC, FuBangkun commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +exoplanets.versions.startingDownload2=[{"text":" 考虑在 ","color":"aqua"},{"text":"Patreon","color":"gold","hoverEvent":{"action":"show_text","value":{"text":"点击此处进入ROMVoid95的Patreon","color":"light_pur
连起来是“考虑在Patreon上支持ROMVoid95”，“点击此处进入ROMVoid95的Patreon”是悬停在”Patreon“上显示的文字

2022-07-15 05:28 UTC, FuBangkun commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +planet.kepler1649c=Kepler 1649c
上面的mamaruo建议我保留英文名称，现在保留了，又叫我翻译成中文

2022-07-15 05:31 UTC, FuBangkun commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +planet.wolf1061d=Wolf 1061 D
上面的mamaruo建议我保留英文名称，现在保留了，又叫我翻译成中文

2022-07-15 17:00 UTC, mamaruo commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +planet.kepler1649c=Kepler 1649c
> 上面的mamaruo建议我保留英文名称，现在保留了，又叫我翻译成中文

我就是mamaruo，也是“上面的mamaruo”。

[我说的是](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/2199#issuecomment-1183532398)：
建议**没有中译**的星体保留英文。

开普勒显然是广泛使用的中文译名，媒体和普罗大众都在使用。另见：['Kepler' | Astrodict | NADC](https://nadc.china-vo.org/astrodict/q?word=Kepler)。

2022-07-15 17:11 UTC, mamaruo commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +exoplanets.versions.startingDownload2=[{"text":" 考虑在 ","color":"aqua"},{"text":"Patreon","color":"gold","hoverEvent":{"action":"show_text","value":{"text":"点击此处进入ROMVoid95的Patreon","color":"light_pur
好我知道哪里怪了。
`"light_purple"},{"text":"]!","color":"aqua"}]`
最后这里的叹号改成全角

2022-07-16 07:46 UTC, FuBangkun commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +planet.wolf1061d=Wolf 1061 D
[](https://baike.baidu.com/item/%E6%B2%83%E5%A4%AB1061/51148705)
[](https://baike.baidu.com/item/%E6%B2%83%E5%B0%94%E5%A4%AB%201061c/19227678)
这两个哪个对，第一个英文名就是Wolf1061，第二个是你说的中文名

2022-07-17 16:53 UTC, mamaruo commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +planet.wolf1061d=Wolf 1061 D
> https://baike.baidu.com/item/%E6%B2%83%E5%A4%AB1061/51148705 https://baike.baidu.com/item/%E6%B2%83%E5%B0%94%E5%A4%AB%201061c/19227678 这两个哪个对，第一个英文名就是Wolf1061，第二个是你说的中文名

我认为是沃尔夫：https://www.termonline.cn/search?k=wolf&r=1658076682058

2022-07-18 00:57 UTC, FuBangkun commented
可以了吗？所有问题都解决了

2022-07-20 09:54 UTC, mczph commented
> 

你搞好的点一下resolved

2022-07-20 16:30 UTC, mamaruo commented
> 可以了吗？所有问题都解决了

并没有

另外我上次 review 没有看完全部的行，问题肯定还有的

2022-12-22 15:00 UTC, dovisutu commented
- 7+7时限进入第一阶段。从该评论发出的时间开始计时。

ping @FuBangkun

2023-01-05 06:09 UTC, dovisutu commented
- 7+7时限进入第二阶段。从该评论发出的时间开始计时。

ping @FuBangkun

2023-01-16 05:16 UTC, closed without merging