提交翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #2208
Opened 2022-07-15 13:32 UTC by dyinjin

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2022-07-15 14:09 UTC, dyinjin commented
发现撞车了，ChuijkYahus大佬烬壳龟的翻译好，小䴙䴘的翻译我因为太生僻没有这样来，走路莲感觉不够可爱欸（笑)

2022-07-15 17:44 UTC, mamaruo commented
#2185

/diff

2022-07-16 06:49 UTC, ChuijkYahus commented
诶，话说走路莲有什么更好的翻译方法吗
不是大佬，不是大佬

2022-07-16 07:12 UTC, dyinjin commented
> 诶，话说走路莲有什么更好的翻译方法吗 不是大佬，不是大佬
我翻译的是百合子，也不一定吧，莲宝，荷精灵什么的也可以考虑

2022-07-16 07:17 UTC, ChuijkYahus commented
> > 诶，话说走路莲有什么更好的翻译方法吗 不是大佬，不是大佬
>
> 我翻译的是百合子，也不一定吧，莲宝，荷精灵什么的也可以考虑

我想的是和`走路草`一个命名方式来着

2022-07-16 07:30 UTC, dyinjin commented
> > > 诶，话说走路莲有什么更好的翻译方法吗 不是大佬，不是大佬
> > 
> > 
> > 我翻译的是百合子，也不一定吧，莲宝，荷精灵什么的也可以考虑
> 
> 我想的是和`走路草`一个命名方式来着

哦，也不错，不是宝可梦厨的反应不过来（笑），搜了下确实样子挺像

2022-07-17 16:11 UTC, mamaruo commented
建议你二位讨论讨论，把两个PR合并了

2022-07-17 16:31 UTC, mamaruo requested changes

2022-07-17 16:31 UTC, mamaruo commented on projects/1.16/assets/creatures-and-beasts/cnb/lang/zh_cn.json
> +    "entity.sporeling_warped.hurt":"中性诡异孢子：受伤",
中立

2022-07-17 16:31 UTC, mamaruo commented on projects/1.16/assets/creatures-and-beasts/cnb/lang/zh_cn.json
> +    "entity.yeti.ambient":"雪人：生长",
```suggestion
    "entity.yeti.ambient":"雪人：生长",
```
看成growth了吗

2022-07-17 16:56 UTC, dyinjin commented on projects/1.16/assets/creatures-and-beasts/cnb/lang/zh_cn.json
> +    "entity.yeti.ambient":"雪人：生长",
整体看下来基本那位的还是好一点
第一次翻译确实有些地方太粗心(>﹏<)
采用他的PR吧，我close了，搞其它模组去了

2022-07-17 16:57 UTC, dyinjin commented on projects/1.16/assets/creatures-and-beasts/cnb/lang/zh_cn.json
> +    "entity.yeti.ambient":"雪人：生长",
整体看下来基本那位的还是好一点
第一次翻译确实有些地方太粗心(>﹏<)
采用他的PR吧，我close了，搞其它模组去了

2022-07-17 16:57 UTC, dyinjin commented on projects/1.16/assets/creatures-and-beasts/cnb/lang/zh_cn.json
> +    "entity.yeti.ambient":"雪人：生长",
整体看下来基本那位的还是好一点
第一次翻译确实有些地方太粗心(>﹏<)
采用他的PR吧，我close了，搞其它模组去了

2022-07-17 16:57 UTC, closed without merging

2022-07-17 16:58 UTC, dyinjin commented
撞车 #2185