Create Cafe 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2230
Opened 2022-07-18 13:01 UTC by zerodegress

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-07-18 13:05 UTC, zerodegress commented
/update-en create-cafe 1.18

2022-07-18 13:07 UTC, ChuijkYahus commented
#1970

2022-07-19 18:41 UTC, mamaruo commented
/diff

2022-07-19 18:42 UTC, mamaruo reviewed
把Advanced Chimneys删一下

与 #1970 的差异（#1970的质量较差，酌情修改）：
![image](https://user-images.githubusercontent.com/37480168/179826110-a41992a6-c0e8-42d1-b41e-531bdecad2da.png)

2022-07-19 23:34 UTC, zerodegress commented
/diff

2022-07-19 23:41 UTC, zerodegress commented
/diff

2022-10-18 05:00 UTC, ChuijkYahus reviewed
大致看了一下

2022-10-18 05:00 UTC, ChuijkYahus commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +  "tooltip.createcafe.super": "抗性提升 (0:13), 速度 (0:13), 力量 (0:13), 生命恢复 (0:13)",
```suggestion
  "tooltip.createcafe.res": "抗性提升（0:12）",
  "tooltip.createcafe.regen": "生命恢复（0:13）",
  "tooltip.createcafe.strength": "力量（0:10）",
  "tooltip.createcafe.speed": "速度（0:13）",
  "tooltip.createcafe.super": "抗性提升（0:13），速度（0:13），力量（0:13），生命恢复（0:13）",
```

2022-10-18 05:00 UTC, ChuijkYahus commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +  "block.createcafe.avocado_tea": "鳄梨味奶茶",
```suggestion
  "item.createcafe.avocado_milk_tea": "牛油果味奶茶",
  "block.createcafe.avocado_tea": "牛油果味奶茶",
```

2022-10-18 05:00 UTC, ChuijkYahus commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +  "block.createcafe.vanilla_tea": "奶茶",
```suggestion
  "item.createcafe.vanilla_milk_tea": "香草味奶茶",
  "block.createcafe.vanilla_tea": "香草味奶茶",
```
没看原文（）
不过应该是兼容Neapolitan的Vanilla（香草）

2022-10-18 05:00 UTC, ChuijkYahus commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +  "item.createcafe.avocado_tea_bucket": "鳄梨味奶茶桶",
```suggestion
  "item.createcafe.avocado_tea_bucket": "牛油果味奶茶桶",
```

2022-10-18 05:00 UTC, ChuijkYahus commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +  "item.createcafe.filling_bucket": "填满的桶",
```suggestion
  "item.createcafe.filling_bucket": "馅料桶",
```
这个游戏内具体是什么

2022-10-18 05:00 UTC, ChuijkYahus commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +  "item.createcafe.vanilla_tea_bucket": "奶茶桶",
```suggestion
  "item.createcafe.vanilla_tea_bucket": "香草味奶茶桶",
```

2022-10-18 05:00 UTC, ChuijkYahus commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +  "item.createcafe.raspberry_tea_bucket": "山莓味奶茶桶",
```suggestion
  "item.createcafe.raspberry_tea_bucket": "树莓味奶茶桶",
```

2022-10-18 05:00 UTC, ChuijkYahus commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +  "block.createcafe.raspberry_tea": "山莓味奶茶",
```suggestion
  "item.createcafe.raspberry_milk_tea": "树莓味奶茶",
  "block.createcafe.raspberry_tea": "树莓味奶茶",
```

2022-10-18 05:00 UTC, ChuijkYahus commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +  "block.createcafe.filling": "填充",
```suggestion
  "block.createcafe.filling": "馅料",
```
游戏内具体是什么

2022-11-16 08:38 UTC, ChuijkYahus commented
呼叫pr作者前来看下（）

2022-11-16 13:45 UTC, zerodegress commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +  "item.createcafe.vanilla_tea_bucket": "奶茶桶",
这个vanilla我觉得是指“原味”的意思。

2022-11-16 13:57 UTC, zerodegress commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +  "item.createcafe.filling_bucket": "填满的桶",
貌似mod更新后没有这一项了

2022-11-17 01:15 UTC, ChuijkYahus commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +  "block.createcafe.vanilla_tea": "奶茶",
看了眼源码
支持`forge:crops/vanillabean`和`neapolitan:dried_vanilla_pods`
第一个应该是潘马斯的香草，第二个是那不勒斯风情的干香草荚
以第二个为参照（主要是由于里面有一大堆香草味的食物），一般都会把香草留着，这里这样应该好一些

2022-11-17 09:18 UTC, ChuijkYahus commented
/update-en create-cafe 1.18

2022-11-17 09:46 UTC, ChuijkYahus commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +  "item.createcafe.tapioca_flour": "木薯粉末",
```suggestion
  "item.createcafe.tapioca_flour": "木薯粉",
```

2022-11-17 09:46 UTC, ChuijkYahus commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +  "item.createcafe.grapefruit_tea_bucket": "柚子味奶茶桶",
```suggestion
  "item.createcafe.grapefruit_tea_bucket": "西柚味奶茶桶",
```

2022-11-17 09:46 UTC, ChuijkYahus commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +  "block.createcafe.grapefruit_tea": "柚子味奶茶",
```suggestion
  "item.createcafe.grapefruit_milk_tea": "西柚味奶茶",
  "block.createcafe.grapefruit_tea": "西柚味奶茶",
```

2022-11-17 09:46 UTC, ChuijkYahus commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +  "block.createcafe.jackfruit_tea": "菠萝蜜味奶茶",
```suggestion
  "item.createcafe.jackfruit_milk_tea": "波罗蜜味奶茶",
  "block.createcafe.jackfruit_tea": "波罗蜜味奶茶",
```

2022-11-17 09:46 UTC, ChuijkYahus commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +  "item.createcafe.jackfruit_tea_bucket": "菠萝蜜味奶茶桶",
```suggestion
  "item.createcafe.jackfruit_tea_bucket": "波罗蜜味奶茶桶",
```

2022-11-17 09:46 UTC, ChuijkYahus commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +  "block.createcafe.oreo_tea": "奥利奥味奶茶",
```suggestion
  "block.createcafe.oreo_tea": "奥利奥味奶茶",
  "item.createcafe.citron_milk_tea": "香橼味奶茶",
  "block.createcafe.citron_tea": "香橼味奶茶",
  "item.createcafe.redlove_milk_tea": "红心果味奶茶",
  "block.createcafe.redlove_tea": "红心果味奶茶",
  "item.createcafe.pomelo_milk_tea": "柚子味奶茶",
  "block.createcafe.pomelo_tea": "柚子味奶茶",
  "item.createcafe.mandarin_milk_tea": "橘子味奶茶",
  "block.createcafe.mandarin_tea": "橘子味奶茶",
  "item.createcafe.barberry_milk_tea": "小檗果味奶茶",
  "block.createcafe.barberry_tea": "小檗果味奶茶"
```
barberry这个口味来自 https://www.curseforge.com/minecraft/mc-mods/powder-more-remastered
推测为物种 _Berberis nummularia_ 的浆果

2022-11-17 09:46 UTC, ChuijkYahus commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +  "item.createcafe.yucca_tea_bucket": "丝兰味奶茶桶"
```suggestion
  "item.createcafe.yucca_tea_bucket": "丝兰味奶茶桶",
  "item.createcafe.citron_tea_bucket": "香橼味奶茶桶",
  "item.createcafe.pomelo_tea_bucket": "柚子味奶茶桶",
  "item.createcafe.redlove_tea_bucket": "红心果味奶茶桶",
  "item.createcafe.mandarin_tea_bucket": "橘子味奶茶桶",
  "item.createcafe.barberry_tea_bucket": "小檗果味奶茶桶"
```

2022-11-17 09:52 UTC, ChuijkYahus approved these changes

2022-11-17 09:54 UTC, ChuijkYahus requested changes

2022-11-17 09:54 UTC, ChuijkYahus commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +  "block.createcafe.barberry_tea": "小檗果味奶茶"
```suggestion
  "block.createcafe.barberry_tea": "小檗果味奶茶",
```

2022-11-17 09:57 UTC, ChuijkYahus commented on projects/1.18/assets/create-cafe/createcafe/lang/zh_cn.json
> +  "tooltip.createcafe.res": "抗性提升（0:12）",
```suggestion
  "tooltip.createcafe.res": "抗性提升（0:12）",
  "tooltip.createcafe.fire_res": "防火（0:12）",
```
作者啥时候加了行这个

2022-11-17 09:57 UTC, ChuijkYahus approved these changes

2022-11-17 10:20 UTC, ChuijkYahus approved these changes

2022-11-17 10:25 UTC, merged