Deep Resonance 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2254
Opened 2022-07-20 11:50 UTC by TexBlock

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-07-22 17:42 UTC, mamaruo commented
/diff

2022-07-22 17:54 UTC, mamaruo commented on projects/1.16/assets/deep-resonance/deepresonance/lang/zh_cn.json
> +    "message.deepresonance.no_tank": "这不是坦克!",
?

2022-07-22 17:54 UTC, mamaruo commented on projects/1.16/assets/deep-resonance/deepresonance/lang/zh_cn.json
> +    "message.deepresonance.generator_part.header": "多方块发电机的一部分。 您可以将它们放在任何配置中。",
configuration 应该取的是 `the particular arrangement or pattern of a group of related things` 的意思
Part of a generator multi-block. You can place these in any configuration.

2022-07-22 17:54 UTC, mamaruo commented on projects/1.16/assets/deep-resonance/deepresonance/lang/zh_cn.json
> +    "item.deepresonance.radiation_monitor": "辐射显示器",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |

[术语在线—权威的术语知识服务平台](https://www.termonline.cn/word/395031/1#s1)

```suggestion
    "item.deepresonance.radiation_monitor": "辐射监测仪",
```

2022-07-23 00:19 UTC, TexBlock commented on projects/1.16/assets/deep-resonance/deepresonance/lang/zh_cn.json
> +    "message.deepresonance.no_tank": "这不是坦克!",
原文貌似在玩双关

2022-07-24 16:39 UTC, mamaruo commented on projects/1.18/assets/deep-resonance/deepresonance/lang/zh_cn.json
> +    "message.deepresonance.laser.liquid": "流体："
```suggestion
    "message.deepresonance.laser.liquid": "液体："
```
fluid 和 liquid

2022-07-24 16:39 UTC, mamaruo approved these changes

2022-07-25 16:58 UTC, mamaruo requested changes
二审

2022-07-25 16:58 UTC, mamaruo commented on projects/1.18/assets/deep-resonance/deepresonance/lang/zh_cn.json
> +    "block.deepresonance.resonating_ore_deepslate": "共振矿石",
键里 deepslate，要不让作者修复一下这个名字

2022-07-25 16:58 UTC, mamaruo commented on projects/1.18/assets/deep-resonance/deepresonance/lang/zh_cn.json
> +    "message.deepresonance.tank.header": "这个罐子可以容纳16桶液体。它还能够混合液态水晶的特性。在这个储罐旁边放一个比较器来检测储罐的装满程度",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  术语不统一  |
```suggestion
    "message.deepresonance.tank.header": "这个储罐可以容纳16桶液体。它还能够混合液态水晶的特性。在这个储罐旁边放一个比较器来检测储罐的装满程度",
```
原文：**This tank can hold up to 16 buckets of liquid. It is also capable of mixing the characteristics of liquid crystal. Place a comparator next to this tank to detect how full the tank is**

2022-07-25 16:58 UTC, mamaruo commented on projects/1.18/assets/deep-resonance/deepresonance/lang/zh_cn.json
> +    "message.deepresonance.smelter.header": "这台机器冶炼共振矿石，并在机器上面的储罐里生产液态水晶。在下面放置一个装有熔岩的储罐",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |

半满啥意思我没懂

```suggestion
    "message.deepresonance.smelter.header": "这台机器冶炼共振矿石来生产液态水晶，并将其置于到机器顶部的储罐中。在下面放置一个装有半满熔岩的储罐",
```
原文：This machine smelts resonating ore and produces liquid crystal in a tank placed on top of this. Place a tank below the smelter about **half-filled** with lava

2022-07-25 16:58 UTC, mamaruo commented on projects/1.18/assets/deep-resonance/deepresonance/lang/zh_cn.json
> +    "message.deepresonance.crystallizer.header": "这台机器将使它下面储罐里的液态水晶结晶，最终产生晶体。",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  术语不统一  |

水晶还是晶体

原文：**This machine will crystallize the liquid crystal from the tank below it and eventually produce a crystal.**

2022-07-25 16:58 UTC, mamaruo commented on projects/1.18/assets/deep-resonance/deepresonance/lang/zh_cn.json
> +    "message.deepresonance.energy_collector.header": "多方块发电机的一部分。把它放在附近有水晶的发电机上面。",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |

仍然不确定，需要游戏内验证
```suggestion
    "message.deepresonance.energy_collector.header": "多方块发电机的一部分。把它放在发电机顶部，且与水晶毗邻。",
```
原文：**Part of a generator multi-block. Place this on top of a generator with crystals nearby.**

2022-07-25 16:58 UTC, mamaruo commented on projects/1.18/assets/deep-resonance/deepresonance/lang/zh_cn.json
> +    "message.deepresonance.crystal_power": "你可以感受到这块水晶中存在的能量。",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  漏译 latent  |
```suggestion
    "message.deepresonance.crystal_power": "你可以感受到这块水晶中潜藏的能量。",
```
原文：**You can feel the latent power present in this crystal.**

2022-07-26 01:04 UTC, TexBlock commented on projects/1.18/assets/deep-resonance/deepresonance/lang/zh_cn.json
> +    "block.deepresonance.resonating_ore_deepslate": "共振矿石",
> 键里 deepslate，要不让作者修复一下这个名字

一会给作者发个issue

2022-07-26 11:45 UTC, mamaruo approved these changes

2022-08-07 12:25 UTC, dovisutu commented on projects/1.16/assets/deep-resonance/deepresonance/lang/zh_cn.json
> +    "message.deepresonance.liquid_injector.header": "唯一将100mB的液态水晶注入到储罐中的物品。",
`Creative only item`
_**`Creative`**_ 被丢了......

2022-08-15 11:42 UTC, dovisutu commented on projects/1.16/assets/deep-resonance/deepresonance/lang/zh_cn.json
> +    "message.deepresonance.liquid_injector.header": "唯一将100mB的液态水晶注入到储罐中的物品。",
_**`Creative only`**_`item`
这句话的意思恐怕是该物品仅在`创造模式`中可以被使用

2022-11-12 15:15 UTC, dovisutu approved these changes

2022-11-16 07:55 UTC, merged