Dimensional-Dungeons 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2263
Opened 2022-07-21 07:08 UTC by DoloSaber

添加汉化

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-07-26 02:46 UTC, DoloSaber commented
[向原作者提交汉化，并已通过合并！](https://github.com/AllenSeitz/DimDungeons/blob/master/src/main/resources/assets/dimdungeons/lang/zh_cn.json)

2023-07-22 11:53 UTC, luoxueyasha requested changes
这么久才审实在是有点不好意思（

2023-07-22 11:53 UTC, luoxueyasha commented on projects/1.16/assets/dimensional-dungeons/dimdungeons/lang/zh_cn.json
> +	"item.dimdungeons.item_portal_key_basic": "基础维度密钥",
如何翻译出`密钥`的？
`portal key`上下文不一致，此类问题请全文通查

2023-07-22 11:53 UTC, luoxueyasha commented on projects/1.16/assets/dimensional-dungeons/dimdungeons/lang/zh_cn.json
> +	"item.dimdungeons.item_trophy_2": "大师剑",
```suggestion
	"item.dimdungeons.item_trophy_2": "大师之剑",
```
塞尔达系列官译

2023-07-22 11:53 UTC, luoxueyasha commented on projects/1.16/assets/dimensional-dungeons/dimdungeons/lang/zh_cn.json
> +	"item.dimdungeons.item_trophy_4": "泰拉瑞亚",
```suggestion
	"item.dimdungeons.item_trophy_4": "泰拉悠悠球",
```
参考自[泰拉瑞亚wiki](https://terraria.fandom.com/zh/wiki/%E6%B3%B0%E6%8B%89%E6%82%A0%E6%82%A0%E7%90%83)，具体应视游戏内内容而定

2023-07-22 11:53 UTC, luoxueyasha commented on projects/1.16/assets/dimensional-dungeons/dimdungeons/lang/zh_cn.json
> +	"item.dimdungeons.item_trophy_8": "奥尔特罗斯绘画",
```suggestion
	"item.dimdungeons.item_trophy_8": "奥尔特罗斯画像",
```
常用搭配

2023-07-22 11:53 UTC, luoxueyasha commented on projects/1.16/assets/dimensional-dungeons/dimdungeons/lang/zh_cn.json
> +	"item.dimdungeons.item_trophy_5": "物质操纵枪",
确定在《Starbound》里的表现是`操纵枪`吗

2023-07-22 11:53 UTC, luoxueyasha commented on projects/1.16/assets/dimensional-dungeons/dimdungeons/lang/zh_cn.json
> +	"npart.dimdungeons.struct_5": "钥匙",
这些`Key XXX`有什么区别？

2023-07-22 11:53 UTC, luoxueyasha commented on projects/1.16/assets/dimensional-dungeons/dimdungeons/lang/zh_cn.json
> +	"npart.dimdungeons.struct_4": "与",
与`npart.dimdungeons.struct_2`的`and`如何区分？
实际游戏表现？

2023-07-22 11:53 UTC, luoxueyasha commented on projects/1.16/assets/dimensional-dungeons/dimdungeons/lang/zh_cn.json
> +	"npart.dimdungeons.noun_0": "<未来>",
实际游戏显示场景与效果？

2023-07-22 11:53 UTC, luoxueyasha commented on projects/1.16/assets/dimensional-dungeons/dimdungeons/lang/zh_cn.json
> +	"npart.dimdungeons.struct_7": "高级钥匙",
与L51翻译不一致，可以解释一下吗

2023-07-30 10:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2263) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2263) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2263) it.</sub>

2023-08-25 01:19 UTC, Cactusstudent commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@DoloSaber

2023-09-02 08:07 UTC, closed without merging