Tinkers' Reforged 翻译新增
CFPAOrg/Minecraft-Mod-Language-Package pull request #2267
Opened 2022-07-22 00:55 UTC by GelmanSparrow

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-07-22 12:51 UTC, Cactusstudent commented
删多余空格，Please！

2022-10-03 04:30 UTC, Cactusstudent requested changes
大概瞅了一眼

2022-10-03 04:30 UTC, Cactusstudent commented on projects/1.18/assets/tinkers-reforged/tinkers_reforged/book/reforging_guide/zn_ch/tools/frying_pan.json
> +      "text": "煎锅是一种多功能武器，伤害平庸，可以让你点燃敌人，同时保持另一只手自由。（左键攻击点燃敌人，与副手毫无关系——译者注）"
```suggestion
      "text": "平底锅是一种多功能武器，伤害平庸，可以让你点燃敌人，同时保持另一只手自由。"
```
最好不要留这个

2022-10-03 04:30 UTC, Cactusstudent commented on projects/1.18/assets/tinkers-reforged/tinkers_reforged/lang/zn_ch.json
> +  "item.tinkers_reforged.cast_broad_axe_head": "板斧刃铝铸件",
```suggestion
  "item.tinkers_reforged.cast_broad_axe_head": "板斧刃铝铸模",
```

2022-10-03 04:30 UTC, Cactusstudent commented on projects/1.18/assets/tinkers-reforged/tinkers_reforged/lang/zn_ch.json
> +  "item.tinkers_reforged.frying_pan": "煎锅",
```suggestion
  "item.tinkers_reforged.frying_pan": "平底锅",
```

2022-10-03 04:30 UTC, Cactusstudent commented on projects/1.18/assets/tinkers-reforged/tinkers_reforged/lang/zn_ch.json
> +  "item.tinkers_reforged.great_blade": "Great Blade",
```suggestion
  "item.tinkers_reforged.great_blade": "大剑刃",
```

2022-10-03 04:30 UTC, Cactusstudent commented on projects/1.18/assets/tinkers-reforged/tinkers_reforged/lang/zn_ch.json
> +  "item.tinkers_reforged.great_blade_cast_gold": "大剑刃黄金铸模",
```suggestion
  "item.tinkers_reforged.great_blade_cast_gold": "大剑刃金质铸模",
```

2022-10-03 04:30 UTC, Cactusstudent commented on projects/1.18/assets/tinkers-reforged/tinkers_reforged/lang/zn_ch.json
> +  "item.tinkers_reforged.large_round_plate_cast_gold": "大圆盘黄金铸模",
```suggestion
  "item.tinkers_reforged.large_round_plate_cast_gold": "大圆盘金质铸模",
```

2022-10-03 04:30 UTC, Cactusstudent commented on projects/1.18/assets/tinkers-reforged/tinkers_reforged/lang/zn_ch.json
> +  "material.tinkers_reforged.duralumin.flavor": "最早的时效硬化（合金在在一定温度下，保持一段时间时产生的硬度与强度上升的现象。）铝合金之一",
```suggestion
  "material.tinkers_reforged.duralumin.flavor": "最早的时效硬化铝合金之一",
```

2022-10-03 04:30 UTC, Cactusstudent commented on projects/1.18/assets/tinkers-reforged/tinkers_reforged/lang/zn_ch.json
> +  "material.tinkers_reforged.durasteel.encyclopedia": "末影材料和远古残骸的合金",
```suggestion
  "material.tinkers_reforged.durasteel.encyclopedia": "末影材料和残骸的合金",
```

2022-10-03 04:30 UTC, Cactusstudent commented on projects/1.18/assets/tinkers-reforged/tinkers_reforged/lang/zn_ch.json
> +  "material.tinkers_reforged.felsteel.encyclopedia": "来自下届深处",
```suggestion
  "material.tinkers_reforged.felsteel.encyclopedia": "来自下界深处",
```

2022-10-03 04:30 UTC, Cactusstudent commented on projects/1.18/assets/tinkers-reforged/tinkers_reforged/lang/zn_ch.json
> +  "modifier.tinkers_reforged.fel_debris.description": "对下届生物造成更多伤害但对",
```suggestion
  "modifier.tinkers_reforged.fel_debris.description": "对下界生物造成更多伤害但对",
```

2022-10-03 04:30 UTC, Cactusstudent commented on projects/1.18/assets/tinkers-reforged/tinkers_reforged/lang/zn_ch.json
> +  "modifier.tinkers_reforged.giant_cells.description": "生命越低，挖掘速度越快。",
```suggestion
  "modifier.tinkers_reforged.giant_cells.description": "生命越低，采掘速度越快。",
```

2022-10-03 04:30 UTC, Cactusstudent commented on projects/1.18/assets/tinkers-reforged/tinkers_reforged/lang/zn_ch.json
> +  "modifier.tinkers_reforged.giant_cells.mining_speed": "巨细胞 挖掘速度加成",
```suggestion
  "modifier.tinkers_reforged.giant_cells.mining_speed": "巨细胞 采掘速度加成",
```

2022-10-03 04:30 UTC, Cactusstudent commented on projects/1.18/assets/tinkers-reforged/tinkers_reforged/lang/zn_ch.json
> +  "modifier.tinkers_reforged.arid_zone.mining_speed": "当前生物群系 挖掘速度加成",
```suggestion
  "modifier.tinkers_reforged.arid_zone.mining_speed": "当前生物群系 采掘速度加成",
```

2022-10-03 04:30 UTC, Cactusstudent commented on projects/1.18/assets/tinkers-reforged/tinkers_reforged/lang/zn_ch.json
> +  "modifier.tinkers_reforged.arid_zone.description": "在干旱以及高温的区域增加伤害和挖掘速度",
```suggestion
  "modifier.tinkers_reforged.arid_zone.description": "在干旱以及高温的区域增加伤害和采掘速度",
```

2022-10-03 04:30 UTC, Cactusstudent commented on projects/1.18/assets/tinkers-reforged/tinkers_reforged/lang/zn_ch.json
> +  "modifier.tinkers_reforged.adapting.mining_speed": "适应 挖掘速度加成",
```suggestion
  "modifier.tinkers_reforged.adapting.mining_speed": "适应 采掘速度加成",
```

2022-12-16 15:04 UTC, dovisutu commented
- 7+7时限进入第一阶段。从该评论发出的时间开始计时。

ping @GelmanSparrow

2022-12-22 14:14 UTC, Cactusstudent commented
- 7+7时限进入第二阶段。从该评论发出的时间开始计时。

ping @GelmanSparrow

2022-12-28 12:09 UTC, ChuijkYahus commented
* 由于7+7的时间已过，故本PR关闭，随后若PR作者上线，可以自行Reopen此PR

ping @GelmanSparrow

2022-12-28 12:09 UTC, closed without merging

2022-12-28 12:14 UTC, ChuijkYahus commented
#2664