Oreganized 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2269
Opened 2022-07-22 04:51 UTC by zizunsi

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-07-22 17:37 UTC, mamaruo commented
/diff

2022-07-22 17:42 UTC, mamaruo requested changes
有术语不统一的情况，请检查（可借助Bot打的表）

2022-07-26 14:23 UTC, mamaruo commented on projects/1.18/assets/oreganized-mod/oreganized/lang/zh_cn.json
> +  "death.attack.molten_lead": "%1$s 试图在熔化的铅上行走",
```suggestion
  "death.attack.molten_lead": "%1$s 试图在熔融铅上行走",
```

2022-07-26 14:33 UTC, mamaruo requested changes
二审

2022-07-26 14:33 UTC, mamaruo commented on projects/1.18/assets/oreganized-mod/oreganized/lang/zh_cn.json
> +  "block.oreganized.waxed_green_concrete_powder": "涂蜡绿色混凝土粉末",
```suggestion
  "block.oreganized.waxed_black_concrete_powder": "黑色涂蜡混凝土粉末",
  "block.oreganized.waxed_red_concrete_powder": "红色涂蜡混凝土粉末",
  "block.oreganized.waxed_green_concrete_powder": "绿色涂蜡混凝土粉末",
```
下同

2022-07-26 14:33 UTC, mamaruo commented on projects/1.18/assets/oreganized-mod/oreganized/lang/zh_cn.json
> +  "block.oreganized.blasted_iron_block": "爆破铁块",
Blasted Iron
这是什么东西，高炉铁？

2022-12-13 03:50 UTC, dovisutu commented
- 7+7时限进入第一阶段。从该评论发出的时间开始计时。

ping @zizunsi

2022-12-22 14:14 UTC, Cactusstudent commented
- 7+7时限进入第二阶段。从该评论发出的时间开始计时。

ping @zizunsi

2022-12-28 12:09 UTC, ChuijkYahus commented
* 由于7+7的时间已过，故本PR关闭，随后若PR作者上线，可以自行Reopen此PR

ping @zizunsi

2022-12-28 12:09 UTC, closed without merging

2022-12-28 12:14 UTC, ChuijkYahus commented
* 由于7+7的时间已过，故本PR关闭，随后若PR作者上线，可以自行Reopen此PR

ping @zizunsi