Thaumic Augmentation 和 Thaumic Additions: Reconstructed 汉化更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #2274
Opened 2022-07-23 06:10 UTC by mczph

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-07-23 15:01 UTC, CubeSugarCheese commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.void_recharge_pedestal.1=元动充能基座已经可以开始建造了，比起我目前只能使用的元动弥散仪，它应该能更高效地为单个物品补充元动能量。我采用了普通充能基座的基本设计，并将原有的一般魔法组件替换为与虚空联系更为密切的组件，同时对顶板进行了微调，以使其更好地传输蕴变元动能量。<BR>当元动充能基座建造完毕并被放置好后，我可
`全功率信号`建议改为`最高强度的信号`，见 wiki 红石一章<https://minecraft.fandom.com/zh/wiki/%E7%BA%A2%E7%9F%B3%E7%94%B5%E8%B7%AF>

2022-07-23 15:01 UTC, CubeSugarCheese commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.thaumostatic_gyroscope.1=这件为奥法背带准备的全新增强组件大幅提高了飞行的稳定性，避免在我停止时发生漂移。这些回转仪稳定器会细微地调节背带输出的速度，确保我可以随时停下。就像其他的增强组件一样，这一升级组件可以通过合成格位与奥法背带组合到一起，单独将装备组件的奥法背带放入合成格位则可以移除组件。<BR>可惜的是，稳
感觉`向下动力`改为`下降势头`读起来更流畅些

2022-07-23 15:02 UTC, CubeSugarCheese requested changes
部分用词可以换一下

2022-07-31 10:51 UTC, mczph commented
不小心重命名了，明天把两个模组分开

2022-08-02 04:36 UTC, closed without merging