ravage and cabbage 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2275
Opened 2022-07-23 11:52 UTC by ranl-8417

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-07-23 12:00 UTC, ranl-8417 commented on projects/1.16/assets/ravage-and-cabbage/ravageandcabbage/lang/zh_cn.json
> +	"item.ravageandcabbage.netherite_horn_armor": "下界合金护角",
`护角`，原文为`Horn Armor`

2022-07-23 14:44 UTC, CubeSugarCheese approved these changes

2022-07-23 15:04 UTC, mamaruo commented
/diff

2022-07-23 15:10 UTC, mamaruo requested changes

2022-07-23 15:10 UTC, mamaruo commented on projects/1.16/assets/ravage-and-cabbage/ravageandcabbage/lang/zh_cn.json
> +	"entity.ravageandcabbage.cabbager": "卷心菜农",
认真的的吗，敌对生物欸
Cabbagers! These new hostile mobs are a type of Pillager that you find at Cabbager Barns. They will throw cabbages at villagers and players.
[Ravage & Cabbage - Mods - Minecraft - CurseForge](https://www.curseforge.com/minecraft/mc-mods/ravage-and-cabbage)

2022-07-23 15:10 UTC, mamaruo commented on projects/1.16/assets/ravage-and-cabbage/ravageandcabbage/lang/zh_cn.json
> +	"entity.ravageandcabbage.cabbage": "被投掷的卷心菜",
| **审查级别**    | 备注 |
|--------------|----|
| ⚪ 轻微 / 不阻止合并但需三思  |    |
```suggestion
	"entity.ravageandcabbage.cabbage": "扔出的卷心菜",
```
原文：**Thrown Cabbage**

2022-07-25 15:30 UTC, mamaruo commented
/diff

2022-07-25 15:39 UTC, mamaruo commented
与 #2288 的主要差异：

| English          | 本PR（@ranl-8417） | \#2288（@zizunsi） |
|:----------------:|:---------------:|:----------------:|
| Horn Armor       | 角甲              | 护角               |
| Ravage & Cabbage | （未译）            | 劫掠 & 卷心菜         |

2022-07-27 08:36 UTC, mamaruo commented
@ranl-8417 你的意见如何。

> 与 #2288 的主要差异：
> 
> English	本PR（@ranl-8417）	#2288（@zizunsi）
> Horn Armor	角甲	护角
> Ravage & Cabbage	（未译）	劫掠 & 卷心菜
> Cabbager	卷心菜射手	卷心菜农

2022-08-07 12:06 UTC, dovisutu commented on projects/1.16/assets/ravage-and-cabbage/ravageandcabbage/lang/zh_cn.json
> +	"item.ravageandcabbage.netherite_horn_armor": "下界合金护角",
感觉在没有前例的情况下，这个译名还是可行的
先这样吧

2022-08-07 12:07 UTC, dovisutu approved these changes
应该没什么问题了
（此外，打着ready to merge结果request change还没解可还行（

2022-08-07 12:08 UTC, merged