Lava tech 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2301
Opened 2022-07-27 07:37 UTC by zizunsi

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-07-27 08:26 UTC, mamaruo commented
/diff

2022-11-16 11:24 UTC, ChuijkYahus reviewed
随便看了看

2022-11-16 11:24 UTC, ChuijkYahus commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.blockburner":"将方块转化为能量，每块产生 160FE。",
```suggestion
  "message.blockburner":"将方块转化为能量，每块产生160 FE。",
```

2022-11-16 11:24 UTC, ChuijkYahus commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.healer":"自动在上面治疗玩家，每10/Tick 使用 1000FE恢复半颗心。",
```suggestion
  "message.healer":"自动治疗其上方的玩家，每10游戏刻使用1000 FE恢复半颗心。",
```

2022-11-16 11:24 UTC, ChuijkYahus commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.reinforcedframe":"用于最终技术的更坚固、更耐用的机器框架。",
```suggestion
  "message.reinforcedframe":"用于游戏末期的更坚固、更耐用的机器框架。",
```

2022-11-16 11:24 UTC, ChuijkYahus commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.lavavent":"用于为基于热的机器提供动力。通过围绕熔岩源、加热的岩浆或电加热器来增加热量，最多 4 个。更多的热量意味着更快的机器，但更快的能源消耗。放置机器在上面",
```suggestion
  "message.lavavent":"用于为基于热的机器提供动力。通过围绕熔岩源、过热岩浆块或电加热器来增加热量，最多4个。更多的热量意味着机器运转速度更快，但能源消耗也更快。在其上放置机器。",
```

2022-11-16 11:24 UTC, ChuijkYahus commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.coalinfuser":"用熔岩注入煤炭，使其燃烧时间更长。",
```suggestion
  "message.coalinfuser":"将熔岩注入煤炭，使其燃烧时间更长。",
```

2022-11-16 11:24 UTC, ChuijkYahus commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.lavagenerator":"在被熔岩喷口加热时产生能量。每层热量产生 40FE/t",
```suggestion
  "message.lavagenerator":"在被熔岩喷口加热时产生能量。每级热量产生40 FE/t",
```

2022-11-16 11:24 UTC, ChuijkYahus commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.copperdrill":"在提供能量时在下方 1x1 区域内钻孔。由于铜钻头的弱采掘特性，钻头无法开采深部岩层。",
```suggestion
  "message.copperdrill":"提供能量时能在下方1x1区域内钻孔。由于铜钻头本身硬度不高，钻头无法开采深板岩。",
```

2022-11-16 11:24 UTC, ChuijkYahus commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.hydroponics":"在有电的情况下白天种植植物",
```suggestion
  "message.hydroponics":"在有电的情况下能在白天使其中植物生长。",
```

2022-11-16 11:24 UTC, ChuijkYahus commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.basicconduit":"一个简单的木制能量导管。不能放在其他基本管道旁边。",
```suggestion
  "message.basicconduit":"一个简单的木制能量导管。不能放在其他基础管道旁边。",
```

2022-11-16 11:24 UTC, ChuijkYahus commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.basicframe":"用于基本机器的原始框架。",
```suggestion
  "message.basicframe":"用于基础机器的原始框架。",
```

2022-11-16 11:24 UTC, ChuijkYahus commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.conduit":"用于在机器之间以 2000FE/t 传输功率",
```suggestion
  "message.conduit":"用于在机器之间以2000 FE/t传输能量。",
```

2022-11-16 11:24 UTC, ChuijkYahus commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.battery":"用于储存能量。只有在给定红石信号时才会输出。",
```suggestion
  "message.battery":"用于储存能量。只有在给予红石信号时才会输出。",
```

2022-11-16 11:24 UTC, ChuijkYahus commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.compressor":"压缩材料和方块，将它们变成更有价值的。",
```suggestion
  "message.compressor":"压缩材料和方块，将它们变成更有价值的物品。",
```

2022-11-16 11:24 UTC, ChuijkYahus commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.upgrader":"使用炼狱锭将下界合金 工具和盔甲升级为更好的。还可以用 下界合金和熔岩砖制造狱火锭。",
```suggestion
  "message.upgrader":"使用狱火锭将下界合金工具和盔甲升级。还可以用下界合金锭和熔岩砖制造狱火锭。",
```

2022-11-16 11:24 UTC, ChuijkYahus commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +    "message.heater":"使用 60FE/t 为熔岩喷口产生热量。产生与4个熔岩源或2个过热岩浆块一样多的热量。",
```suggestion
    "message.heater":"使用60 FE/t为熔岩喷口产生热量。产生与4个熔岩源或2个过热岩浆块一样多的热量。",
```

2022-11-16 11:24 UTC, ChuijkYahus commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.crank":"产生 18FE/t 的手动曲柄。",
```suggestion
  "message.crank":"产生18 FE/t的手动曲柄。",
```

2022-11-16 11:24 UTC, ChuijkYahus commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.simplebeacon":"使用 50FE/t 在 10 格半径内产生药水效果，一次只能对一名玩家施加。",
```suggestion
  "message.watermill":"被流动的水包围时产生能量。每边产生5 FE/t，最高可达20 FE/t",

  "block.lavaplus.carboninfuser": "碳灌注机",
  "message.carboninfuser":"这台机器使用纯碳（煤）来生产各种材料，以及将其他形式的碳，如木炭和生物物质净化成煤。",

  "block.lavaplus.simplebeacon": "机械信标",
  "message.simplebeacon":"使用50 FE/t在10格半径内产生药水效果，一次只能对一名玩家施加。",
```

2022-11-16 11:24 UTC, ChuijkYahus commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.fuelprocessor":"顶部需要 2 个燃料处理器组件来完成多方块结构。根据食物价值将食物转化为营养燃料电池。",
```suggestion
  "message.garden":"进阶版的生长室，水培花园使用30 FE/t来种植植物。不像它的前代，它不消耗种子，也不需要阳光",

  "block.lavaplus.fuelprocessor": "营养燃料处理室",
  "message.fuelprocessor":"顶部需要2个燃料处理器组件来完成多方块结构。根据食物价值将食物转化为营养燃料电池。",
```

2022-11-16 11:24 UTC, ChuijkYahus commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.advancedbeacon":"升级版的机械信标，在更大的区域内同时为多人提供 3 种更强的效果",
```suggestion
  "message.irondrill":"铜钻头的升级版，可在3x3区域内开采且速度更快。",

  "block.lavaplus.advancedbeacon": "高级机械信标",
  "message.advancedbeacon":"升级版的机械信标，能在更大的区域内同时为多人提供3种更强的效果。",
```

2022-11-16 11:24 UTC, ChuijkYahus commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.beaconcomp":"创建高级机械信标的必要组件。放置在高级信标下方的 3x3 区域中。",
```suggestion
  "message.beaconcomp":"创建高级机械信标的必要组件。放置在高级信标下方的3x3区域中。",
```

2022-12-16 15:03 UTC, dovisutu commented
- 7+7时限进入第一阶段。从该评论发出的时间开始计时。

ping @zizunsi

2022-12-22 02:10 UTC, ChuijkYahus reviewed
除了这个应该没问题了吧（没仔细看）
等候其他审核

2022-12-22 02:10 UTC, ChuijkYahus commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "block.lavaplus.benblock": "Ben 方块",
```suggestion
  "block.lavaplus.benblock": "Ben方块",
```

2022-12-22 08:52 UTC, mamaruo commented
[magma](http://www.youdao.com/w/magma/#keyfrom=E2Ctranslation) 系列翻译成“岩浆”，lava 系列翻译成熔岩。

2022-12-22 11:53 UTC, mamaruo requested changes
有些建议不可直接 apply，务必先阅读我的说明

2022-12-22 11:53 UTC, mamaruo commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.basicconduit":"一个简单的木制能量导管。不能放在其他基础管道旁边。",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |
```suggestion
  "block.lavaplus.basicconduit": "基础管道",
  "message.basicconduit":"一个简单的木制能量导管。不能放在其他基础管道旁边。",
```

导管还是管道

原文：
    "block.lavaplus.basicconduit": "Basic Conduit",
    "message.basicconduit":"A Simple wooden energy conduit. Cannot be placed next to other basic conduits.",

2022-12-22 11:53 UTC, mamaruo commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.infernalcharm":"一条强大的项链，可以提升你的健康和伤害。",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |
```suggestion
  "message.infernalcharm":"一条强大的项链，可以提升你的生命值和伤害。",
```
原文：**A powerful necklace that boosts your health and damage.**

2022-12-22 11:53 UTC, mamaruo commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.conduit":"用于在机器之间以2000 FE/t传输能量。",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  翻译腔太严重  |
```suggestion
  "message.conduit":"用于在机器之间传输能量，速度为2000 FE/t。",
```
原文：**Used to transfer power between machines at 2000FE/t**

2022-12-22 11:53 UTC, mamaruo commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.upgrader":"使用狱火锭将下界合金工具和盔甲升级。还可以用下界合金锭和熔岩砖制造狱火锭。",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  翻译腔  |
```suggestion
  "message.upgrader":"使用狱火锭升级下界合金工具和盔甲。还可以用下界合金锭和熔岩砖制造狱火锭。",
```
原文：**Upgrades Netherrite tools and armor into better ones using Infernal Ingots. Also creates infernal ingots out of netherite and lava bricks**

2022-12-22 11:53 UTC, mamaruo commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +    "message.heater":"使用60 FE/t为熔岩喷口产生热量。产生与4个熔岩源或2个过热岩浆块一样多的热量。",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  翻译腔  |
```suggestion
    "message.heater":"给熔岩喷口产生热，耗能速率为60 FE/t。产热量相当于4个熔岩源或两个过热岩浆块。",
```
原文：**Uses 60FE/t to create heat for the Lava Vent. Generates as much heat as 4 lava sources or 2 superheated magma blocks.**

2022-12-22 11:53 UTC, mamaruo commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.garden":"进阶版的生长室，水培花园使用30 FE/t来种植植物。不像它的前代，它不消耗种子，也不需要阳光",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   术语不一致   |
```suggestion
"block.lavaplus.garden": "水培生长室",
  "message.garden":"进阶版的生长室，水培花园使用30 FE/t来种植植物。不像它的前代，它不消耗种子，也不需要阳光",
```
原文：
  "message.garden":"The advanced version of the growth chamber, the Hydroponic Garden uses 30FE/t to grow plants. Unlike its predecessor, it doesn't consume seeds and doesn't require sunlight",

2022-12-22 11:53 UTC, mamaruo commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.fuelprocessor":"顶部需要2个燃料处理器组件来完成多方块结构。根据食物价值将食物转化为营养燃料电池。",
| **审查级别**    | 备注 |
|--------------|----|
| ⚪ 轻微 / 不阻止合并但需三思  |    |
```suggestion
  "message.fuelprocessor":"顶部需要2个燃料处理器组件来完成多方块结构。根据食物价值将食物转化为营养燃料电池。",
```

食物价值？

原文：**Needs 2 Fuel Processor components on top to complete the multiblock. Turns food into Nutritional Fuel Cells based on their food value. **

2022-12-26 19:18 UTC, Ricky-fight commented
/diff

2022-12-27 17:06 UTC, mamaruo commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.fuelprocessor":"顶部需要2个燃料处理器组件来完成多方块结构。根据食物的饱食度将食物转化为营养燃料电池。",
饥饿值

2022-12-27 17:09 UTC, mamaruo commented
> @Ricky-fight ⚠ 你没有执行此命令的权限。

[cfpa-bot](https://github.com/apps/cfpa-bot) 的回复里现在自带diff了

2022-12-27 17:09 UTC, mamaruo reviewed
熔岩喷口肯定是有问题的

2023-07-30 10:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2301) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2301) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2301) it.</sub>

2023-08-01 04:30 UTC, luoxueyasha requested changes

2023-08-01 04:30 UTC, luoxueyasha commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.magmacoal":"燃烧时间是煤炭的两倍。在煤炭再加工机中制造。可用作焦煤的替代品。",
```suggestion
  "message.magmacoal":"燃烧时间是煤炭的两倍。可在煤炭再加工机中制造，并用于替代焦煤。",
```
全文都有这种[翻译腔](https://zh.wikipedia.org/wiki/Wikipedia:%E7%BF%BB%E8%AF%91%E8%85%94)的细节问题，建议自行修改，全文通查

2023-08-01 04:30 UTC, luoxueyasha commented on projects/1.18/assets/lavatech/lavaplus/lang/zh_cn.json
> +  "message.copperpickaxe":"虽然青铜镐比铁更坚固耐用，但仍然比钻石镐弱。",
```suggestion
  "message.copperpickaxe":"虽然比铁镐更坚固耐用，但还是比钻石镐弱。",
```
`青铜镐比铁弱`这个句子本身存在歧义

2023-08-22 05:26 UTC, Cactusstudent commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

2023-08-30 14:03 UTC, closed without merging