Miniature power plant 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2303
Opened 2022-07-27 07:49 UTC by zizunsi

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-07-27 07:50 UTC, mamaruo commented
你已经是个成熟译员的了，该学会自己 /diff 了。
/diff

2022-07-27 08:06 UTC, mamaruo requested changes

2022-07-27 08:06 UTC, mamaruo commented on projects/1.18/assets/miniature-power-plant/miniaturepowerplant/lang/zh_cn.json
> +  "item.miniaturepowerplant.accumulator_enhanced": "3级电容",
蓄电池

2022-07-27 08:06 UTC, mamaruo commented on projects/1.18/assets/miniature-power-plant/miniaturepowerplant/lang/zh_cn.json
> +  "item.miniaturepowerplant.eco_plus_upgrade": "生态升级+",
生态+升级 好呢还是这个好

2022-07-27 08:06 UTC, mamaruo commented on projects/1.18/assets/miniature-power-plant/miniaturepowerplant/lang/zh_cn.json
> +  "container.miniaturepowerplant.carrier.hover.depletion": "耗尽率: %d%%",
```suggestion
  "container.miniaturepowerplant.carrier.hover.energy.wasted": "损耗：%d FE/t",
  "container.miniaturepowerplant.carrier.hover.depletion": "损耗率：%d%%",
```

2022-07-27 08:06 UTC, mamaruo commented on projects/1.18/assets/miniature-power-plant/miniaturepowerplant/lang/zh_cn.json
> +  "item.miniaturepowerplant.solar_module_netherite": "太阳能模块(下界合金锭)",
无中生锭

2022-11-16 11:12 UTC, ChuijkYahus commented on projects/1.18/assets/miniature-power-plant/miniaturepowerplant/lang/zh_cn.json
> +  "item.miniaturepowerplant.depletable.desc.depletion": "已消耗: %s%%",
```suggestion
  "item.miniaturepowerplant.depletable.desc.depletion": "已消耗：%s%%",
```

2022-11-16 11:12 UTC, ChuijkYahus commented on projects/1.18/assets/miniature-power-plant/miniaturepowerplant/lang/zh_cn.json
> +  "item.miniaturepowerplant.solar_module_netherite": "太阳能模块(下界合金)",
```suggestion
  "item.miniaturepowerplant.solar_module_stone": "太阳能模块（石）",
  "item.miniaturepowerplant.solar_module_gold": "太阳能模块（金）",
  "item.miniaturepowerplant.solar_module_iron": "太阳能模块（铁）",
  "item.miniaturepowerplant.solar_module_lapis": "太阳能模块（青金石）",
  "item.miniaturepowerplant.solar_module_redstone": "太阳能模块（红石）",
  "item.miniaturepowerplant.solar_module_diamond": "太阳能模块（钻石）",
  "item.miniaturepowerplant.solar_module_netherite": "太阳能模块（下界合金）",
```

2022-11-16 11:12 UTC, ChuijkYahus commented on projects/1.18/assets/miniature-power-plant/miniaturepowerplant/lang/zh_cn.json
> +  "item.miniaturepowerplant.solar_module.penalty.thunder": "打雷",
```suggestion
  "item.miniaturepowerplant.solar_module.penalty.thunder": "雷雨",
```

2022-11-16 11:12 UTC, ChuijkYahus commented on projects/1.18/assets/miniature-power-plant/miniaturepowerplant/lang/zh_cn.json
> +  "item.miniaturepowerplant.water_module.production.water_level": "水位@ %s",
```suggestion
  "item.miniaturepowerplant.water_module.production.water_level": "水位处于%s",
```
@ = at（猜测）
懒得打字属于是（）

2022-11-16 11:12 UTC, ChuijkYahus commented on projects/1.18/assets/miniature-power-plant/miniaturepowerplant/lang/zh_cn.json
> +  "item.miniaturepowerplant.wind_module.desc.range": "范围: %d",
```suggestion
  "item.miniaturepowerplant.wind_module.penalty.height": "Y坐标",
  "item.miniaturepowerplant.wind_module.boost.height": "Y坐标",
  "item.miniaturepowerplant.wind_module.desc.production": "产量：%d FE/t",
  "item.miniaturepowerplant.wind_module.desc.range": "范围：%d",
```

2022-11-16 11:12 UTC, ChuijkYahus commented on projects/1.18/assets/miniature-power-plant/miniaturepowerplant/lang/zh_cn.json
> +  "item.miniaturepowerplant.eco_plus_upgrade": "生态+ 升级",
```suggestion
  "item.miniaturepowerplant.eco_plus_upgrade": "生态+升级",
```

2022-11-16 11:12 UTC, ChuijkYahus commented on projects/1.18/assets/miniature-power-plant/miniaturepowerplant/lang/zh_cn.json
> +  "item.miniaturepowerplant.accumulator.desc.stored": "存储能量: %d/%d FE",
```suggestion
  "item.miniaturepowerplant.accumulator.desc.transfer": "传输效率：%d FE/t",
  "item.miniaturepowerplant.accumulator.desc.stored": "存储能量：%d/%d FE",
```

2022-11-16 11:12 UTC, ChuijkYahus commented on projects/1.18/assets/miniature-power-plant/miniaturepowerplant/lang/zh_cn.json
> +  "container.miniaturepowerplant.carrier.hover.empty_ground_slot": "发电模块下槽",
```suggestion
  "container.miniaturepowerplant.carrier.hover.empty_solar_slot": "发电模块顶部",
  "container.miniaturepowerplant.carrier.hover.empty_core_slot": "发电模块中部",
  "container.miniaturepowerplant.carrier.hover.empty_ground_slot": "发电模块底部",
```

2022-11-16 11:12 UTC, ChuijkYahus commented on projects/1.18/assets/miniature-power-plant/miniaturepowerplant/lang/zh_cn.json
> +  "container.miniaturepowerplant.carrier.hover.boost_self": "%d%%: %s"
```suggestion
  "container.miniaturepowerplant.carrier.hover.empty_upgrade_slot": "将升级物品放入此槽以获得提升",
  "container.miniaturepowerplant.carrier.hover.energy.internal_stored": "内部: %d/%d FE",
  "container.miniaturepowerplant.carrier.hover.energy.additional_stored": "额外: %d/%d FE",
  "container.miniaturepowerplant.carrier.hover.energy.produced": "产出: %d FE/t",
  "container.miniaturepowerplant.carrier.hover.energy.wasted": "损耗：%d FE/t",
  "container.miniaturepowerplant.carrier.hover.depletion": "损耗率：%d%%",
  "container.miniaturepowerplant.carrier.hover.producer": "来源：",
  "container.miniaturepowerplant.carrier.hover.producer_self": "%d FE：%s",
  "container.miniaturepowerplant.carrier.hover.penalty": "惩罚：",
  "container.miniaturepowerplant.carrier.hover.penalty_self": "%d%%：%s",
  "container.miniaturepowerplant.carrier.hover.boost": "提升：",
  "container.miniaturepowerplant.carrier.hover.boost_self": "%d%%：%s"
```

2022-12-16 15:03 UTC, dovisutu commented
- 7+7时限进入第一阶段。从该评论发出的时间开始计时。

ping @zizunsi

2022-12-22 02:08 UTC, ChuijkYahus commented on projects/1.18/assets/miniature-power-plant/miniaturepowerplant/lang/zh_cn.json
> +  "item.miniaturepowerplant.depletable.desc.new": "全新的",
```suggestion
  "item.miniaturepowerplant.depletable.desc.new": "全新",
```

2022-12-22 02:08 UTC, ChuijkYahus commented on projects/1.18/assets/miniature-power-plant/miniaturepowerplant/lang/zh_cn.json
> +  "item.miniaturepowerplant.solar_module.desc.energy_multiplier": "能量产生: %s%%",
```suggestion
  "item.miniaturepowerplant.solar_module.desc.energy_multiplier": "能量产生：%s%%",
```

2022-12-22 02:08 UTC, ChuijkYahus commented on projects/1.18/assets/miniature-power-plant/miniaturepowerplant/lang/zh_cn.json
> +  "container.miniaturepowerplant.carrier.hover.energy.produced": "产出: %d FE/t",
```suggestion
  "container.miniaturepowerplant.carrier.hover.energy.internal_stored": "内部：%d/%d FE",
  "container.miniaturepowerplant.carrier.hover.energy.additional_stored": "额外：%d/%d FE",
  "container.miniaturepowerplant.carrier.hover.energy.produced": "产出：%d FE/t",
```

2023-04-01 07:29 UTC, ChuijkYahus commented on projects/1.18/assets/miniature-power-plant/miniaturepowerplant/lang/zh_cn.json
> +  "item.miniaturepowerplant.solar_module.desc.energy_multiplier": "能量产生：%s%%",
```suggestion
  "item.miniaturepowerplant.solar_module.desc.energy_multiplier": "产能：%s%%",
```

2023-04-02 05:18 UTC, ChuijkYahus approved these changes

2023-04-03 07:48 UTC, merged