Metallum 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2323
Opened 2022-07-30 04:52 UTC by ChuijkYahus

Malum pr #2319

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-09-10 05:38 UTC, ChuijkYahus commented
目前和最新版灵灾在手册上冲突
打开手册就会卡崩（）

2022-10-16 05:29 UTC, IdealNightOcean requested changes

2022-10-16 05:29 UTC, IdealNightOcean commented on projects/1.18/assets/metallum/metallum/lang/zh_cn.json
> +  "malum.gui.book.entry.page.text.cluster_tools_a": "将工具和对应的金属结点调谐似 乎能给工具带来一些奇妙的效果。 在工具内流动的炼金能量不仅让 其更经久耐用，也改变了它们的 外形。这些工具在挖掘和战斗中 都非常有用。",
```suggestion
  "malum.gui.book.entry.page.text.cluster_tools_a": "将工具和对应的金属结点调谐似乎能给工具带来一些奇妙的效果。在工具内流动的炼金能量不仅让其更经久耐用，也改变了它们的外形。这些工具在挖掘和战斗中都非常有用。",
```

2022-10-16 05:29 UTC, IdealNightOcean commented on projects/1.18/assets/metallum/metallum/lang/zh_cn.json
> +  "malum.gui.book.entry.page.text.reagent_pendant_a": "将炼金粉和咒灰混合就能制成一 种反应活性极高的混合物。它能 和灵神剧烈反应，但可以通过镀 金吊坠稳定存放。在这种状态下， 它只会在接触外界灵神时激活， 并用澄空灵神的能量提供速度增 益。",
```suggestion
  "malum.gui.book.entry.page.text.reagent_pendant_a": "将炼金粉和咒灰混合就能制成一种反应活性极高的混合物。它能和灵神剧烈反应，但可以通过镀金吊坠稳定存放。在这种状态下，它只会在接触外界灵神时激活，并用澄空灵神的能量提供速度增益。",
```

2022-10-16 05:29 UTC, IdealNightOcean commented on projects/1.18/assets/metallum/metallum/lang/zh_cn.json
> +  "malum.gui.book.entry.page.text.alchemical_blocks_a": "炼金粉可被压缩为炼金砖。裂纹、 瓦形、錾制、台阶、楼梯等等的 合成方式与岩石类似。",
```suggestion
  "malum.gui.book.entry.page.text.alchemical_blocks_a": "炼金粉可被压缩为炼金砖。炼金砖和石砖类似，可以用同样的方式合成为裂纹、瓦、錾制、台阶、楼梯等不同的形式。",
```
`stone counterparts`是炼金砖对应的石头物品，那就是石砖了。

2022-10-16 05:30 UTC, IdealNightOcean commented on projects/1.18/assets/metallum/metallum/lang/zh_cn.json
> +  "malum.gui.book.entry.page.text.cluster_tools_a": "将工具和对应的金属结点调谐似 乎能给工具带来一些奇妙的效果。 在工具内流动的炼金能量不仅让 其更经久耐用，也改变了它们的 外形。这些工具在挖掘和战斗中 都非常有用。",
只是删掉空格

2022-10-16 05:30 UTC, IdealNightOcean commented on projects/1.18/assets/metallum/metallum/lang/zh_cn.json
> +  "malum.gui.book.entry.page.text.reagent_pendant_a": "将炼金粉和咒灰混合就能制成一 种反应活性极高的混合物。它能 和灵神剧烈反应，但可以通过镀 金吊坠稳定存放。在这种状态下， 它只会在接触外界灵神时激活， 并用澄空灵神的能量提供速度增 益。",
只是删掉空格

2022-10-16 07:56 UTC, ChuijkYahus commented on projects/1.18/assets/metallum/metallum/lang/zh_cn.json
> +  "malum.gui.book.entry.page.text.cluster_tools_a": "将工具和对应的金属结点调谐似 乎能给工具带来一些奇妙的效果。 在工具内流动的炼金能量不仅让 其更经久耐用，也改变了它们的 外形。这些工具在挖掘和战斗中 都非常有用。",
这里的空格均用于换行

2022-10-16 10:23 UTC, IdealNightOcean commented on projects/1.18/assets/metallum/metallum/lang/zh_cn.json
> +  "malum.gui.book.entry.page.text.cluster_tools_a": "将工具和对应的金属结点调谐似 乎能给工具带来一些奇妙的效果。 在工具内流动的炼金能量不仅让 其更经久耐用，也改变了它们的 外形。这些工具在挖掘和战斗中 都非常有用。",
了解了

2023-08-09 04:08 UTC, dovisutu approved these changes

2023-08-09 04:14 UTC, dovisutu commented on projects/1.18/assets/metallum/metallum/lang/zh_cn.json
> +  "block.metallum.cracked_alchemical_bricks": "裂纹炼金砖",
单独的bricks好像是`砖块`？

2023-08-09 04:42 UTC, ChuijkYahus commented on projects/1.18/assets/metallum/metallum/lang/zh_cn.json
> +  "block.metallum.cracked_alchemical_bricks": "裂纹炼金砖",
当石砖这些来翻的，没有对应砖物品
~~这模组都停更不知道多久了（）~~

2023-08-09 04:43 UTC, ChuijkYahus commented on projects/1.18/assets/metallum/metallum/lang/zh_cn.json
> +  "malum.gui.book.entry.reagent_pendant.description": "秘术把戏",
```suggestion
  "malum.gui.book.entry.reagent_pendant.description": "奥术把戏",
```

2023-08-09 04:43 UTC, ChuijkYahus commented on projects/1.18/assets/metallum/metallum/lang/zh_cn.json
> +  "malum.gui.book.entry.page.text.reagent_pendant_a": "将炼金粉和咒灰混合就能制成一 种反应活性极高的混合物。它能 和灵神剧烈反应，但可以通过镀 金吊坠稳定存放。在这种状态下， 它只会在接触外界灵神时激活， 并用澄空灵神的能量提供速度增 益。",
```suggestion
  "malum.gui.book.entry.page.text.reagent_pendant_a": "将炼金粉和咒灰混合就能制成一 种反应活性极高的混合物。它能 和精魂剧烈反应，但可以通过镀 金吊坠稳定存放。在这种状态下， 它只会在接触外界精魂时激活， 并用澄空精魂的能量提供速度增 益。",
```

2023-08-09 05:30 UTC, dovisutu approved these changes

2023-08-10 03:40 UTC, merged