The Abyss II 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #2345
Opened 2022-08-08 17:49 UTC by VillagerKingdom

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-01-25 10:39 UTC, DrIceTea123 requested changes
是不是误把`Mystical World`的文件传到这个branch里了
`Mystical World`的汉化文件我没看，只看了`The Abyss II`的，说实话看的有点头疼
有些地方我没有重复标记，记得改一处就把关联的地方也改了

还有，不知道是我的语言文件的问题，还是距离pr太久语言文件更新了，有几处地方的文本和英文文本对应不上，我都标出来了
没有看特别细，打算等这些先修改完再看一遍

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "block.theabyss.saturnia_versa": "Versa土星",
土星是`Saturn`，而且这是株蓝色植物
可以音译

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "advancements.magic_adv.title": "神奇的音乐剧!",
半角感叹号要改成全角
```suggestion
  "advancements.magic_adv.title": "神奇的音乐剧！",
```

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "advancements.somnium_adv.descr": "比mana更强的能源",
```suggestion
  "advancements.somnium_adv.descr": "比魔力更强的能源",

```

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "item.theabyss.nosaj_sword": "杰森之 §b剑",
```suggestion
  "item.theabyss.nosaj_sword": "杰森之§b剑",

```

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "item.theabyss.lumus_fruit_food": "卢姆斯水果",
```suggestion
  "item.theabyss.lumus_fruit_food": "卢姆斯果",
```

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "effect.tantrum": "发脾气",
有点口语化，我想改成`发怒`，你决定要不要改

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "entity.netherhorse.name": "下界马",
原文是`Death Horse`
在L873译为`亡灵马`

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "item.theabyss.ring_of_ring": "戒",
我想改成`戒指`

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "item.theabyss.artifact_of_after_life": "来世神器",
`After Life`的翻译要与同名状态效果保持一致

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "tile.darkoak.name": "暗橡木",
原版译名为`深色橡木`

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "block.theabyss.infected_grass": "被污染的草",
原文为`Grass Block`

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "block.theabyss.young_exolius_plant": "年轻的埃索利斯极",
植物用”年轻“不合适

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "item.theabyss.nightblade_boss_spawn_egg": "夜刃BOSS刷怪蛋",
原文为`Nightblade Spawn Egg`

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "item.poisondiamond.name": "毒钻",
```suggestion
  "item.poisondiamond.name": "毒钻石",
```

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "item.theabyss.tenebris_powder": "黄粉",
为什么叫黄粉，是因为黄粉虫吗，但是黄粉虫是`tenebrio`不是`Tenebris`
纹理是深紫色粉团，建议音译

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "entity.testhrse.name": "测试马",
别看着键名翻译啊
原文是`Death Horse`

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "block.theabyss.stone_brick_broken": "破裂石砖",
`Cracked Stone Brick`原版叫`裂纹石砖`

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "item.theabyss.dimensional_crack_spawn_egg": "次元裂缝刷怪蛋",
dimension一般译为`维度`

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "item.theabyss.shuriken_explosive": "深渊手里剑炸药",
原文为`Abyss Shuriken`，没有”炸药“

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "block.theabyss.roma_mud_2": "罗马泥 (诅咒)",
不一定非得要括号
```suggestion
  "block.theabyss.roma_mud_2": "被诅咒的罗马泥",
```

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "lingering_potion.effect.ghostvision": "挥之不去的幽灵视角",
应该是`滞留型幽灵视角药水`

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "advancements.unlockthebook.descr": "你需要去阅读深渊向导",
这里是解锁引导书的成就吗，我没找到
但是应该译成`现在你可以阅读深渊引导书了`

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "item.mutatedendereye.name": "变种眼",
原文为`Fire Orb`

2023-01-25 10:39 UTC, DrIceTea123 commented on projects/1.16/assets/the-abyss-chapter-ii/theabyss/lang/zh_cn.json
> +  "death.attack.freeze": "%1$s 被冻死",
作为死亡提示消息，最后面加个”了“比较好

2023-07-30 10:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2345) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2345) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2345) it.</sub>

2023-08-11 02:13 UTC, Cactusstudent commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@VillagerKingdom

2023-08-20 21:04 UTC, closed without merging