Useless Sword 翻译新增
CFPAOrg/Minecraft-Mod-Language-Package pull request #2404
Opened 2022-09-02 09:09 UTC by SeaInNight

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2022-10-11 09:08 UTC, Rinko1231 requested changes

2022-10-11 09:08 UTC, Rinko1231 commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.useless_sword.elderguardiansword": "§e古典守卫者之剑",
```suggestion
  "item.useless_sword.elderguardiansword": "§e远古守卫者之剑",
```

2022-10-15 14:49 UTC, IdealNightOcean commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "block.useless_sword.invisibleglowstone": "Invisible Glowstone",
这是作者为了照明效果添加的幽灵方块 ~~明明原版就有光源方块的~~。个人认为不需要翻译。

2022-10-23 06:38 UTC, ChuijkYahus commented
/sort-keys projects/1.18/assets/useless-sword/useless_sword/lang/en_us.json
/sort-keys projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json

2022-10-23 06:39 UTC, ChuijkYahus commented
/diff

2022-10-23 07:34 UTC, ChuijkYahus reviewed
先随便看了下
今晚或者明天游戏内实测

2022-10-23 07:34 UTC, ChuijkYahus commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.magmaticstonesword.name": "熔岩石剑",
```suggestion
  "item.magmarock.name": "岩浆石",
  "item.magmasword.name": "岩浆块剑",
  "item.magmaticrock.name": "岩浆石",
  "item.magmaticstonesword.name": "岩浆石剑",
```

2022-10-23 07:34 UTC, ChuijkYahus commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.minecraft.tipped_arrow.effect.witherrage": "灵怒之箭",
要不上面也都改成灵怒？
原版里这些应该都统一的

2022-10-23 07:34 UTC, ChuijkYahus commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.sandstonesword.name": "砂石剑",
```suggestion
  "item.redsandstonesword.name": "红砂岩剑",
  "item.sandstonesword.name": "砂岩剑",
```

2022-10-23 07:34 UTC, ChuijkYahus commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.useless_sword.bugged_diamond": "§b谬误钻石",
不知道这里是不是指出bug的那个bug
如果是可能`故障钻石`会更好？也看材质不过

2022-10-23 07:34 UTC, ChuijkYahus commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.useless_sword.copper_jigsaw_slicer": "铜制动力切割刃",
```suggestion
  "item.useless_sword.copper_jigsaw_slicer": "铜制动力切割刀",
```

2022-10-23 07:34 UTC, ChuijkYahus commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.useless_sword.endcrystalsword": "§d末影水晶剑",
```suggestion
  "item.useless_sword.end_crystal_sword": "§d末地水晶剑",
  "item.useless_sword.endcrystalsword": "§d末地水晶剑",
```

2022-10-23 07:34 UTC, ChuijkYahus commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.useless_sword.magmaticstonesword": "熔岩石剑",
```suggestion
  "item.useless_sword.magmarock": "岩浆石",
  "item.useless_sword.magmasword": "岩浆块剑",
  "item.useless_sword.magmatic_rock": "岩浆石",
  "item.useless_sword.magmatic_sword": "岩浆石剑",
  "item.useless_sword.magmaticrock": "岩浆石",
  "item.useless_sword.magmaticstonesword": "岩浆石剑",
```

2022-10-23 07:34 UTC, ChuijkYahus commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.useless_sword.hemolymph_broadsword": "血淋阔剑",
这里是和Alex's Mobs联动的吗

2022-10-23 07:34 UTC, ChuijkYahus commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.useless_sword.uselesswordicon": "OldUselesswordicon",
```suggestion
  "item.useless_sword.useless_sword_compatibility_icon": "朴华之剑丨联动旧标志",
  "item.useless_sword.uselesswordicon": "朴华之剑旧标志",
```

2022-10-23 07:34 UTC, ChuijkYahus commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.uselessswordicon.name": "Useless.Sword_Icon.item",
```suggestion
  "item.uselessswordicon.name": "朴华之剑标志",
```

2022-10-23 09:52 UTC, IdealNightOcean commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.useless_sword.bugged_diamond": "§b谬误钻石",
应该就是，材质故意含有`贴图错误`的表现。
这东西是合成材料，用于合成`"item.useless_sword.bugged_diamond_sword": "谬误钻石剑"`,
这东西的特殊效果是：每次攻击都有概率变回普通的钻石剑

2022-10-23 09:57 UTC, IdealNightOcean commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.minecraft.tipped_arrow.effect.witherrage": "灵怒之箭",
OK

2022-10-23 09:58 UTC, IdealNightOcean commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.useless_sword.hemolymph_broadsword": "血淋阔剑",
是的

2022-10-23 11:01 UTC, IdealNightOcean commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.magmaticstonesword.name": "熔岩石剑",
`magma_rock`我翻译成`岩浆石`了，因为它的合成材料是岩浆块；
这个`magmatic_rock`，我认为还是保留`熔岩石`，因为它的合成材料是熔岩桶+石头。

~~部分翻译成`熔岩石`的`magma_rock`已经改了~~

2022-10-26 03:33 UTC, IdealNightOcean commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.minecraft.splash_potion.effect.spider_trap_effect": "喷溅型网缚药水",
改成`蛛缚`了，算是保留原意

2022-11-07 04:39 UTC, ChuijkYahus reviewed
貌似没啥问题？
晚上实测一下

2022-11-07 04:39 UTC, ChuijkYahus commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.useless_sword.brass_head_turner": "黄铜头槌",
```suggestion
  "item.useless_sword.brass_head_turner": "黄铜头槌",
```
游戏内材质貌似是个~~手钻~~，不过应该没问题吧，晚上再来看

2022-11-07 04:39 UTC, ChuijkYahus commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.useless_sword.hemolymph_broadsword": "血淋阔剑",
```suggestion
  "item.useless_sword.hemolymph_broadsword": "血淋巴阔剑",
```

2022-11-07 04:39 UTC, ChuijkYahus commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.useless_sword.tooth_glaive": "齿阔剑",
```suggestion
  "item.useless_sword.tooth_glaive": "利齿阔剑",
```

2022-11-07 04:39 UTC, ChuijkYahus commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.useless_sword.ironslimesword": "铁制史莱姆剑",
```suggestion
  "item.useless_sword.ironslimesword": "铁制黏液剑",
```

2022-11-07 04:39 UTC, ChuijkYahus commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.useless_sword.slime_sword": "史莱姆之剑",
```suggestion
  "item.useless_sword.slime_sword": "黏液剑",
```

2022-11-07 08:49 UTC, ChuijkYahus commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.useless_sword.dimensional_breacher": "§d维度阔剑",
```suggestion
  "item.useless_sword.dimensional_breacher": "§d维度斩裂剑",
```

2022-11-07 08:51 UTC, ChuijkYahus commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.useless_sword.nether_striker": "§c下界剑刺",
```suggestion
  "item.useless_sword.nether_striker": "§c下界刺剑",
```

2022-11-07 08:52 UTC, ChuijkYahus commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.useless_sword.guardianspikes": "守卫者之刺",
```suggestion
  "item.useless_sword.guardian_spikes": "守卫者刺",
  "item.useless_sword.guardian_sword": "§7守卫者之剑",
  "item.useless_sword.guardianspikes": "守卫者刺",
```

2022-11-07 08:56 UTC, ChuijkYahus commented on projects/1.18/assets/useless-sword/useless_sword/lang/zh_cn.json
> +  "item.useless_sword.brass_head_turner": "黄铜头槌",
```suggestion
  "item.useless_sword.brass_head_turner": "黄铜旋转器",
```

2022-11-07 11:49 UTC, ChuijkYahus approved these changes
应该没啥问题了

2022-11-07 11:50 UTC, IdealNightOcean commented
高强度工作，我真的o(╥﹏╥)o

2022-11-16 09:53 UTC, merged