alexs-mobs 翻译修正
CFPAOrg/Minecraft-Mod-Language-Package pull request #2407
Opened 2022-09-02 16:15 UTC by WingBai

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2022-09-02 16:31 UTC, WingBai commented
alexsmobs-1.16 中文语言文件共有 658 个 Key； 英文语言文件共有 658 个 Key
alexsmobs-1.16 模组内语言文件共有 606 个 Key；
--------------------------------------------------------------------------------------------
“模组内语言文件共有 606 个 Key”这个数据不对吧，我与1.16.5 此模组最新版本中的语言文件比对显示英文语言文件没有问题

2022-10-23 15:57 UTC, Demonese requested changes
请解释为什么把中文省略号替换为了英文省略号

2022-10-27 14:44 UTC, Cactusstudent commented
这没道理啊？为什么要更改？

2022-10-29 05:09 UTC, ChuijkYahus commented
可能是因为mui下省略号无法正常显示？
现在有兼容字体就可以了

2022-10-29 06:40 UTC, closed without merging