Wilds 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2422
Opened 2022-09-06 19:10 UTC by ChuijkYahus

1.18版本还好多没做完

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-09-06 19:11 UTC, ChuijkYahus commented
语言文件已用升序排过一次
原本是乱序

2022-09-08 15:46 UTC, ChuijkYahus commented
/diff

2023-08-04 04:49 UTC, luoxueyasha requested changes

2023-08-04 04:49 UTC, luoxueyasha commented on projects/1.18/assets/wilds/wilds/lang/zh_cn.json
> +  "advancements.beer_adv.descr": "将九个大麦和一个酒杯放进小桶来酿造一杯啤酒",
`Keg`前后文不统一，请仔细检查

2023-10-05 01:00 UTC, luoxueyasha commented on projects/1.18/assets/wilds/wilds/lang/zh_cn.json
> +  "block.wilds.watercress": "水田芥",
学名`豆瓣菜`
考虑要不要改一下

2023-10-06 07:12 UTC, luoxueyasha approved these changes

2023-11-20 22:08 UTC, luoxueyasha approved these changes

2023-11-22 08:45 UTC, merged