luckytnt 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2445
Opened 2022-09-16 09:43 UTC by BigFacedOx

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-10-05 10:31 UTC, Cactusstudent reviewed
稍微看了看一些简单的，细致的交给真正的审核们

2022-10-05 10:31 UTC, Cactusstudent commented on projects/1.16/assets/luckytnt/luckytnt/lang/zh_cn.json
> +  "itemGroup.normal_tnt": "\"普通\"TNT",
```suggestion
  "itemGroup.normal_tnt": "“普通”TNT",
```

2022-10-05 10:31 UTC, Cactusstudent commented on projects/1.16/assets/luckytnt/luckytnt/lang/zh_cn.json
> +  "gui.tnt.midas": "放置大量金块，并给予玩家\"点石成金\"",
```suggestion
  "gui.tnt.midas": "放置大量金块，并给予玩家“点石成金”",
```

2022-10-05 10:31 UTC, Cactusstudent commented on projects/1.16/assets/luckytnt/luckytnt/lang/zh_cn.json
> +  "luckytntmod.grande_finale.descr": "§7§o*Community TNT* 感谢十万下载!",
```suggestion
  "luckytntmod.grande_finale.descr": "§7§o*社区TNT* 感谢十万下载!",
```
仅供参考

2022-10-05 10:31 UTC, Cactusstudent commented on projects/1.16/assets/luckytnt/luckytnt/lang/zh_cn.json
> +  "gui.guide.page2.info": "Lucky TNT 是一个模组，灵感来自不再更新的模组 TooMuchTNT，并添加了 100 多种新的 TNT 和可投掷的炸药来摧毁你的世界。 本指南旨在让您更深入地了解我们的模组是如何工作的！",
```suggestion
  "gui.guide.page2.info": "Lucky TNT 是一个模组，灵感来自不再更新的模组TooMuchTNT，并添加了100多种新的TNT和可投掷的炸药来摧毁你的世界。本指南旨在让您更深入地了解我们的模组是如何工作的！",
```

2022-10-05 10:31 UTC, Cactusstudent commented on projects/1.16/assets/luckytnt/luckytnt/lang/zh_cn.json
> +  "luckytntmod.entity_firework.descr": "§7§o仅创造模式!",
```suggestion
  "luckytntmod.entity_firework.descr": "§7§o仅创造模式！",
```

2022-10-05 10:31 UTC, Cactusstudent commented on projects/1.16/assets/luckytnt/luckytnt/lang/zh_cn.json
> +  "gui.entity.evillekoopa": "邪恶LeKoopa会攻击玩家并有概率燃放TNT，如TNT、TNT烟花、僵尸启示录、攻击TNT等......",
```suggestion
  "gui.entity.evillekoopa": "邪恶LeKoopa会攻击玩家并有概率燃放TNT，如TNT、TNT烟花、僵尸启示录、攻击TNT等……",
```

2022-10-05 10:31 UTC, Cactusstudent commented on projects/1.16/assets/luckytnt/luckytnt/lang/zh_cn.json
> +  "gui.guide.page1.disclaimer": "如果您是创作者并且想要使用我们的模组（例如 视频）请加上我们curseforge页面的链接！ 不要搬运个模组！",
```suggestion
  "gui.guide.page1.disclaimer": "如果您是创作者并且想要使用我们的模组（例如 视频）请加上我们CurseForge页面的链接！不要搬运这个模组！",
```

2022-10-05 10:31 UTC, Cactusstudent commented on projects/1.16/assets/luckytnt/luckytnt/lang/zh_cn.json
> +  "block.luckytntmod.silk_touch_tnt": "精准采掘TNT",
```suggestion
  "block.luckytntmod.silk_touch_tnt": "精准采集TNT",
```

2022-10-05 10:31 UTC, Cactusstudent commented on projects/1.16/assets/luckytnt/luckytnt/lang/zh_cn.json
> +  "luckytntmod.custom_tnt.descr": "§7§o使用luckytnt法杖右键选择模式，左键配置参数",
```suggestion
  "luckytntmod.custom_tnt.descr": "§7§o使用LuckyTNT法杖右键选择模式，左键配置参数",
```

2022-10-05 10:31 UTC, Cactusstudent commented on projects/1.16/assets/luckytnt/luckytnt/lang/zh_cn.json
> +  "item.luckytntmod.configuration_wand": "luckytnt法杖",
```suggestion
  "item.luckytntmod.configuration_wand": "LuckyTNT法杖",
```

2022-10-05 10:31 UTC, Cactusstudent commented on projects/1.16/assets/luckytnt/luckytnt/lang/zh_cn.json
> +  "gui.tnt.toxic_clouds": "开始灾难 \"毒云\"",
```suggestion
  "gui.tnt.toxic_clouds": "开始灾难“毒云”",
```

2022-10-18 03:49 UTC, ChuijkYahus commented
/diff

2022-10-18 12:29 UTC, Cactusstudent commented on projects/1.16/assets/luckytnt/luckytnt/lang/zh_cn.json
> +  "gui.guide.page1.disclaimer": "如果您是创作者并且想要使用我们的模组（例如 视频）请加上我们curseforge页面的链接！ 不要搬运这个模组！",
```suggestion
  "gui.guide.page1.disclaimer": "如果您是创作者并且想要使用我们的模组（例如 视频）请加上我们CurseForge页面的链接！ 不要搬运这个模组！",
```

2022-10-18 12:29 UTC, Cactusstudent commented on projects/1.16/assets/luckytnt/luckytnt/lang/zh_cn.json
> +  "luckytntmod.structure_tnt.descr": "§7§o使用luckytnt法杖右键更改结构",
```suggestion
  "luckytntmod.structure_tnt.descr": "§7§o使用LuckyTNT法杖右键更改结构",
```

2022-10-18 12:30 UTC, Cactusstudent commented on projects/1.16/assets/luckytnt/luckytnt/lang/zh_cn.json
> +  "gui.tnt.helix": "发射\"公转TNT\"",
```suggestion
  "gui.tnt.helix": "发射“公转TNT”",
```

2022-10-18 12:31 UTC, Cactusstudent commented on projects/1.16/assets/luckytnt/luckytnt/lang/zh_cn.json
> +  "gui.guide.page2.infoheadline": "§lLucky TNT什么是？",
```suggestion
  "gui.guide.page2.infoheadline": "§l什么是Lucky TNT？",
```

2022-10-18 12:31 UTC, Cactusstudent commented on projects/1.16/assets/luckytnt/luckytnt/lang/zh_cn.json
> +  "gui.tnt.solar_eruption": "发射大量TNT并生成大量岩浆",
```suggestion
  "gui.tnt.solar_eruption": "发射大量TNT并生成大量熔岩",
```

2022-10-20 04:37 UTC, ChuijkYahus commented
/sort-keys projects/1.16/assets/luckytnt/luckytnt/lang/zh_cn.json
/sort-keys projects/1.16/assets/luckytnt/luckytnt/lang/en_us.json

2023-07-30 10:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2445) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2445) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2445) it.</sub>

2023-08-22 04:59 UTC, Cactusstudent commented
/diff

2023-08-22 05:02 UTC, Cactusstudent requested changes
请阐述添加译注的原因，如`（弹射器）`

2023-09-12 16:59 UTC, ChuijkYahus commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@BigFacedOx

2023-09-12 17:00 UTC, ChuijkYahus commented
请注意，提出审阅意见后，若并未 Submit Review，审阅意见则均为 Pending 状态且仅自己可见

2023-09-20 20:07 UTC, closed without merging