Botania 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #2472
Opened 2022-09-29 06:27 UTC by IdealNightOcean

- [ ] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [ ] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

作者是真滴喜欢ACG文化，很多东西根本没得翻译，一些梗可能翻译有误，望指正

2022-09-29 08:30 UTC, IdealNightOcean commented
中文翻译大多来自官方翻译，修改了一些错误落后与游戏版本的内容，补充了一些更新内容的翻译

2022-10-01 03:24 UTC, dovisutu reviewed
进度：+L1734以前（也就是手册以前）
对比采用[这里](https://cfpa.cyan.cafe/static/CD5E4C-FC0F1C.html)，在这里是L1677以前

-----

- github的diff居然是全文件标红......<br>有可能是换行符问题吧，虽然对文件没什么影响，但是审核就有点麻烦
- 格式符顺序有没有乱掉？<br>看起来有的翻译在库里的和这里的格式符顺序不一样，估计至少一边是错的
- 进度的翻译<br>或许需要考虑一下梗翻译用日语梗源是否合理（我没法做出评价，但是最好在这里讨论清楚，以免*后顾之忧*）
- 全角标点大筛查<br>至少看到有好几处标点还是半角的（有的标出来了）<br>最好自查一下，一次性改掉，要不然commit可能会乱掉

2022-10-01 03:24 UTC, dovisutu commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "botaniamisc.command.skyblock.help.1": "/gardenofglass island <玩家名称> - 为这个玩家创建一个新的空岛，或传送至他的空岛若已存在",
好像不太通顺？

2022-10-01 03:24 UTC, dovisutu commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "botania.challenge.flowerFarm.desc": "建造一个有着十六种颜色的植物魔法花的自动化农场，如果花朵分类分布奖励积分。",
“分类分布”？个人猜测是将不同颜色的花分类存储

此外，在没有`积分`的情况下将`bonus point`译成`奖励积分`是否合适？

2022-10-01 03:24 UTC, dovisutu commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "botania.challenge.entropinnyumSetup.desc": "建造一套自动合成TNT并且安全喂食$(l:generating_flowers/entropinnyum)热爆花$(/l)来生产魔力的系统.如果TNT需求的沙子和火药不需要手动放置奖励积分。",
火药能被“手动**放置**”？个人猜测是外界供应（也可能是我太久没玩bot了呢......）

2022-10-01 03:24 UTC, dovisutu commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "block.botania.redstone_spreader": "红石魔力发射器",
可能需要考虑一下。
与下面的两个不同，这又不是利用红石工作的，只是被红石控制的（如果我没记错），采用同形式翻译是否可能导致误会？

2022-10-01 03:24 UTC, dovisutu commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "block.botania.brown_double_flower": "褐色高神秘花",
颜色术语错误？

2022-10-01 03:24 UTC, dovisutu commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "block.botania.corporea_block": "多媒体块",
怎么莫名其妙感觉原翻译要通顺一些？

2022-10-01 03:24 UTC, dovisutu commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "block.botania.shulk_me_not.reference": "哦，这感觉...",
本库里对省略号显示做了一定修改，可能需要将省略号改用`……`（两个字符那个）
（似乎不止这一处）

2022-10-01 03:24 UTC, dovisutu commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "item.botania.lens_flare": "魔力透镜:闪耀",
全角标点？

2022-10-01 03:24 UTC, dovisutu commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "item.botania.brew_flask": "大瓶%s精酿 (%s)",
全角标点？

2022-10-01 05:58 UTC, IdealNightOcean commented
暂时忽略这个pull吧，官译我越看越不对劲，诡异的地方太多了，改不动。现在打算以i18库里的为基础修改，估计要一段时间了。

2022-10-01 11:43 UTC, IdealNightOcean commented
大改完毕，现在方便检查多了

2022-10-02 13:09 UTC, dovisutu reviewed
先点一下
patchouli等会儿再放上来

~（我甚至直到现在都没开游戏......）~

2022-10-02 13:09 UTC, dovisutu commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "_comment6": "请翻译者注意替换全半角标点，包括“,”和“，”、“.”和“。”、“?”和“？”、以及“!”和“！”等。同时，请注意将排列句式中的英文逗号改为顿号。感谢您的贡献。",
这个......行吧，放这里也可以。

2022-10-02 13:09 UTC, dovisutu commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "block.botania.azulejo_0": "蓝彩瓷砖",
看这个译法估计词根是`azure`了
个人认为没什么问题，但是还是顺便点出来，以免*后顾之忧*~（指改译名问题把这稿翻译又炸了）~

2022-10-02 13:51 UTC, dovisutu reviewed
先审一点点
目前位置：L2055

2022-10-02 13:51 UTC, dovisutu commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "botania.page.runeAltar21": "制作符文是植物魔法发展的一个重要而复杂的部分。读到这里的读你应已掌握一些$(thing)魔力运用$(0)的知识。在进一步学习前，阅览完$(item)植物魔法辞典$(0)中那些重要的条目（$(o)斜体$(0)书写）)或许能给你启发。",
`$(o)斜体$(0)书写`好像看起来不太通顺......
`以斜体显示`？或者别的译法？

2022-10-02 13:51 UTC, dovisutu commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
>    "botania.page.flowerBag0": "众所周知，$(thing)物品栏$(0)的空间是有限的，这样一来带着各种颜色的花就变成了一个难题。幸运的是，$(item)采花袋$(0)考虑到了这些问题。每种颜色的$(item)神秘花$(0)最多能储存1组，除此之外，它还会主动将持有者捡起的花装入其中。",
不知道这样翻是否更通顺一点？
```suggestion
  "botania.page.flowerBag0": "众所周知，$(thing)物品栏$(0)的空间是有限的，这样一来带着各种颜色的花就变成了一个难题。幸运的是，$(item)采花袋$(0)考虑到了这些问题。$(item)采花袋$(0)能够存储每种颜色的$(item)神秘花$(0)最多1组；除此之外，它还会主动将持有者捡起的花装入其中。",
```

2022-10-02 13:51 UTC, dovisutu commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
>    "botania.page.pool0": "$(item)魔力池$(0)简单说就是储存$(thing)魔力$(0)的地方。$(p)魔力能通过使用$(item)魔力发射器$(0)输入，与魔力池相邻的$(item)魔力发$(0)$(item)射器$(0)会自动从中抽取魔力增加内部缓存。$(p)所有$(thing)功能花$(0)需要一个相邻的$(item)魔力池$(0)提供能量。",
这格式化怎么了......是原文分单词加两个格式符结果没删？
（这个可能需要大范围筛查）
```suggestion
  "botania.page.pool0": "$(item)魔力池$(0)简单说就是储存$(thing)魔力$(0)的地方。$(p)魔力能通过使用$(item)魔力发射器$(0)输入，与魔力池相邻的$(item)魔力发射器$(0)会自动从中抽取魔力增加内部缓存。$(p)所有$(thing)功能花$(0)需要一个相邻的$(item)魔力池$(0)提供能量。",
```
下面一行也是，但是在修改范围以外我点不到（并且那句话好像也不太通顺）

2022-10-02 13:51 UTC, dovisutu commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
>    "botania.page.pool2": "将一些材料投入普通的$(item)魔力$(0)$(item)池$(0)会使它们被注入$(thing)魔力$(0)，将其变为更富能量的形式。$(p)比如$(item)铁锭$(0)和$(item)神秘花瓣$(0)。$(p)该方块的$(thing)魔力$(0)同$(item)魔力发射器$(0)。$(item)红石比较器$(0)也能根据其中的魔力量输出信
`$(p)该方块的$(thing)魔力$(0)同$(item)魔力发射器$(0)`
魔力容量吗？

2022-10-02 13:51 UTC, dovisutu commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
>    "botania.page.flowerBag1": "内部也有相同的大小（任意颜色均可）",
似乎不太通顺？（我这边不方便看原文，等会儿发出去再对照）

2022-10-02 13:51 UTC, dovisutu commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
>    "botania.page.sparks0": "$(item)火花$(0)是种有趣的实体。它由纯粹的能量与$(thing)魔力$(0)结合而生，能被置于少部分容纳或是接收$(thing)魔力$(0)的方块上方，当然主要还是$(item)魔力池$(0)。$(p)有些方块能利用来自$(item)火花$(0)的魔力，当它们的用途现在仍是十分有限的样子。",
最后一部分似乎顺序乱了/语句不通？（还是看不到原文）

2022-10-02 13:51 UTC, dovisutu commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
>    "botania.page.lens0": "为了发掘$(item)魔力发射器$(0)的潜力，需要$(item)魔力透镜$(0)。最基础的魔力透镜没有任何效果。$(p)透镜能被$(thing)染成$(0)十六种颜色中的一种，或使用$(item)魔力珍珠$(0)做成$(item)彩虹透镜$(0)。这些会改变魔力脉冲的颜色。",
完了L1944点不到......只能往这里放
`有时，尽管，`这个看起来就是`Sometimes, however, ...`的遗留机翻，可以一路改了

2022-10-02 13:51 UTC, dovisutu commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
>    "botania.page.bellows1": "$(item)魔源风箱$(0)另一个关注度不高的能力是让$(item)熔炉$(0)的火烧的更旺$(p)通过右击来手动使用$(item)魔源风箱$(0)，并将风向口对准一个正在使用$(item)熔炉$(0)并鼓动他们能够使得$(item)熔炉$(0)烧东西变得更有效率且更为迅速。",
```suggestion
  "botania.page.bellows1": "$(item)魔源风箱$(0)另一个关注度不高的能力是让$(item)熔炉$(0)的火烧的更旺。$(p)通过右击来手动使用$(item)魔源风箱$(0)，将风向口对准一个工作中的$(item)熔炉$(0)，并鼓动风箱即可使$(item)熔炉$(0)的冶炼速率更高。
```
大致改了一下这个句子，可能改的并不是很好

2023-07-30 10:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2472) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2472) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2472) it.</sub>

2023-08-24 12:31 UTC, luoxueyasha requested changes

2023-08-24 12:31 UTC, luoxueyasha commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
> +  "botania.page.marimorphosis05": "$(item)Solite$(0) will generate in deserts and savannas. $(item)Fuchsite$(0) appears in forest biomes (including taigas). $(item)Mycelite$(0) generates in mushroom
漏翻

2023-08-24 12:31 UTC, luoxueyasha commented on projects/1.18/assets/botania/botania/lang/zh_cn.json
>    "advancement.botania:rankSSPick": "六兆年と一夜物語",
请确定所有的歌名neta是否全都翻译（例如L452的`里表情人`而非`裏表ラバーズ`）
另外我注意到现汉化版本行数与英文文本不完全对应，可以解释一下吗

2023-11-05 00:20 UTC, luoxueyasha commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。
@IdealNightOcean

2023-11-12 02:20 UTC, closed without merging