Spirit 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2479
Opened 2022-10-04 12:13 UTC by aaron-yang2009

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-10-04 14:59 UTC, Cactusstudent commented
#2458 可供参考

2022-10-15 13:40 UTC, IdealNightOcean requested changes

2022-10-15 13:40 UTC, IdealNightOcean commented on projects/1.18/assets/spirit/spirit/lang/zh_cn.json
> +  "block.spirit.shiftkey.tooltip": "按住 [SHIFT] 来显示更多信息",
```suggestion
  "block.spirit.shiftkey.tooltip": "按住[SHIFT]来显示更多信息",
```

2022-10-15 13:40 UTC, IdealNightOcean commented on projects/1.18/assets/spirit/spirit/lang/zh_cn.json
> +  "spirit.item.soul_crystal_shard.tooltip": "包含: %s",
```suggestion
  "spirit.item.soul_crystal_shard.tooltip": "包含：%s",
```

2022-10-15 13:40 UTC, IdealNightOcean commented on projects/1.18/assets/spirit/spirit/lang/zh_cn.json
> +  "spirit.item.soul_steel_tool.empowered": "§7按下 §8[%s§8]§7 释能§r",
```suggestion
  "spirit.item.soul_steel_tool.empowered": "§7按下§8[%s§8]§7以释能§r",
```

2022-10-15 13:40 UTC, IdealNightOcean commented on projects/1.18/assets/spirit/spirit/lang/zh_cn.json
> +  "spirit.item.soul_steel_tool.unpowered": "§7按下 §8[%s§8]§7 充能§r",
```suggestion
  "spirit.item.soul_steel_tool.unpowered": "§7按下§8[%s§8]§7以充能§r",
```

2022-10-15 13:40 UTC, IdealNightOcean commented on projects/1.18/assets/spirit/spirit/lang/zh_cn.json
> +  "spirit.jei.soul_engulfing.duration": "所需时间: %ss",
```suggestion
  "spirit.jei.soul_engulfing.duration": "所需时间：%ss",
```

2022-10-15 14:03 UTC, IdealNightOcean commented
这个要比 #2458  好些，那个的机翻痕迹很足。

2022-10-25 04:35 UTC, Cactusstudent commented on projects/1.18/assets/spirit/spirit/lang/zh_cn.json
> +  "block.spirit.broken_spawner.tooltip": "被摧毁的刷怪笼<br>查看归魂手册以获取更多信息",
```suggestion
  "block.spirit.broken_spawner.tooltip": "被摧毁的刷怪笼\n查看归魂手册以获取更多信息",
```
这tooltip里面还是用\n保险一点

2022-10-25 04:35 UTC, Cactusstudent commented on projects/1.18/assets/spirit/spirit/lang/zh_cn.json
> +  "spirit.jei.soul_cage_info.spawn_delay": "生成间隔从%s到%s ticks",
```suggestion
  "spirit.jei.soul_cage_info.spawn_delay": "生成间隔从%s到%sticks",
```

2022-10-25 04:35 UTC, Cactusstudent commented on projects/1.18/assets/spirit/spirit/lang/zh_cn.json
> +  "spirit.tooltip.chipped_loaded": "安装 Chipped 来正确地使用",
```suggestion
  "spirit.tooltip.chipped_loaded": "安装Chipped来正确地使用",
```

2022-11-08 15:16 UTC, ChuijkYahus commented on projects/1.18/assets/spirit/spirit/lang/zh_cn.json
> +  "spirit.soul_cage.tier_4": "Vier",
```suggestion
  "spirit.soul_cage.tier_0": "零",
  "spirit.soul_cage.tier_1": "一",
  "spirit.soul_cage.tier_2": "二",
  "spirit.soul_cage.tier_3": "三",
  "spirit.soul_cage.tier_4": "四",
```
德语（作者难道是讲德语的？）

2022-11-08 15:16 UTC, ChuijkYahus commented on projects/1.18/assets/spirit/spirit/lang/zh_cn.json
> +  "spirit.item.crude_soul_crystal.tooltip": "灵魂: ",
```suggestion
  "spirit.item.crude_soul_crystal.tooltip": "灵魂：",
```

2022-11-08 15:16 UTC, ChuijkYahus commented on projects/1.18/assets/spirit/spirit/lang/zh_cn.json
> +  "spirit.tooltip.chipped_loaded": "安装Chipped来正确地使用",
```suggestion
  "spirit.tooltip.chipped_loaded": "安装Chipped以正确使用",
```
推销一下Chipped #2500

2022-11-08 15:20 UTC, ChuijkYahus commented on projects/1.18/assets/spirit/spirit/lang/zh_cn.json
> +  "enchantment.spirit.soul_reaper.desc": "每增加一级附魔，将在每次击杀后给予额外的一个灵魂",
```suggestion
  "enchantment.spirit.soul_reaper.desc": "魔咒等级每增加一级，每次击杀后额外给予一个灵魂",
```

2022-11-08 15:20 UTC, ChuijkYahus commented on projects/1.18/assets/spirit/spirit/lang/zh_cn.json
> +  "spirit.jei.soul_cage_info.spawn_count": "每回生成%s只生物",
```suggestion
  "spirit.jei.soul_cage_info.spawn_count": "每次生成%s只生物",
```

2022-11-14 14:26 UTC, dovisutu commented
> _**504 Gateway Time-out**_

~bot奇观~


-------
key | ENG | CHI
-- | -- | --
spirit.soul_cage.tier_0 | Null | 零
spirit.soul_cage.tier_1 | Eins | 一
spirit.soul_cage.tier_2 | Zwei | 二
spirit.soul_cage.tier_3 | Drei | 三
spirit.soul_cage.tier_4 | Vier | 四

原文用的似乎是德文以示区分，是否要考虑换一个抽象点的数字记号？

2023-02-10 00:45 UTC, Ricky-fight commented
ping @aaron-yang2009 这个还要吗?
- 7+7时限进入第一阶段。从该评论发出的时间开始计时。

2023-04-01 07:26 UTC, ChuijkYahus commented
* 7+7时限已到，若需提交可自行reopen

@aaron-yang2009

2023-04-01 07:26 UTC, closed without merging