Atlantis 1.12.2 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2481
Opened 2022-10-04 17:06 UTC by Ginsway

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-10-04 17:07 UTC, Ginsway commented
原作者：mc_Edwin

2022-10-05 03:49 UTC, CatastropheChou commented
撕烤
这个海蓝"宝石""锭"
总感觉是和[合金矿石](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2437)一样的错误呢
也许按卓伦星系翻译成[蓝晶](https://www.mcmod.cn/item/322561.html)也不错？

2022-10-05 12:25 UTC, CatastropheChou requested changes

2022-10-06 14:40 UTC, Ginsway commented on projects/1.12.2/assets/atlantis/atlantis/lang/zh_cn.lang
> +tile.atlantis.ancient_jungle_wood_moss.name=遍布苔藓的古老丛林木
已修改

2022-10-06 14:54 UTC, CatastropheChou commented on projects/1.12.2/assets/atlantis/atlantis/lang/zh_cn.lang
> +tile.atlantis.ancient_jungle_wood_moss.name=遍布苔藓的古老丛林木
在[原branch](https://github.com/Ginsway/Minecraft-Mod-Language-Package/blob/atlantis/projects/1.12.2/assets/atlantis/atlantis/lang/zh_cn.lang)对此进行修改，然后回pr这点左下角的resolve conversation就行了

2022-12-03 12:42 UTC, dovisutu commented
> 蓝晶

~那这有没有与`big reactor`的那个`cyanite`蓝晶冲突的嫌疑......~

不过海蓝宝石锭肯定是不太好的

2023-07-30 10:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2481) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2481) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2481) it.</sub>

2023-09-14 06:03 UTC, ChuijkYahus reviewed
其他应该没啥问题了

2023-09-14 06:03 UTC, ChuijkYahus commented on projects/1.12.2/assets/atlantis/atlantis/lang/zh_cn.lang
> +item.atlantis.shovel_aquamarine.name=海蓝宝石铲
```suggestion
item.atlantis.shovel_aquamarine.name=海蓝宝石锹
```

2023-09-14 06:03 UTC, ChuijkYahus commented on projects/1.12.2/assets/atlantis/atlantis/lang/zh_cn.lang
> +item.atlantis.atlantean_shield.name=亚特兰蒂斯盾
```suggestion
item.atlantis.atlantean_shield.name=亚特兰蒂斯盾牌
```

2023-09-14 06:03 UTC, ChuijkYahus commented on projects/1.12.2/assets/atlantis/atlantis/lang/zh_cn.lang
> +tile.atlantis.underwater_flower.name=亚特兰蒂斯花卉
```suggestion
tile.atlantis.underwater_flower.name=亚特兰蒂斯之花
```

2023-09-30 06:42 UTC, ChuijkYahus commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@Ginsway

2023-10-04 15:14 UTC, ChuijkYahus approved these changes

2023-10-06 13:03 UTC, merged