Pyromancer 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #2523
Opened 2022-10-22 05:00 UTC by ChuijkYahus

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-10-22 05:04 UTC, ChuijkYahus commented
/diff

2022-10-22 05:59 UTC, ChuijkYahus commented
部分翻译来源：
键名|英文名|中文名|来源推测
-|-|-|-
`advancements.blazing_journal_goal.title`|Burn O Flame!|火焰啊，吞噬一切！|艾尔登法环
`advancements.brimstone_goal.title`|Like Breathing In Sulfur|就像在硫磺里难以呼吸|Sulfur - Slipknot
`advancements.court_of_embers_achievment.title`|Return of the Fire Witch|火焰女巫的归来|The Court of the Crimson King - King Crimson
`advancements.forest_of_rot_goal.title`|Let your flesh be consumed|用你的身体牢牢记住吧……（感谢@RCqaq）|艾尔登法环，玛莲尼亚
`advancements.hoglin_hide_goal.title`|Leatherman|Leather Man|噶七姆七
`advancements.hogwhip_achievment.title`|Dungeon Master|Dungeon Master|噶七姆七
`advancements.marauders_armor_achievment.title`|Boss of this Gym|拨器至今（感谢@Rinko1231）|噶七姆七
`advancements.mercury_goal.title`|Heavy metal, son|重金属，小子|胳膊壮（疑似）
`advancements.nitropowder_achievment.title`|Exuprosion!|爆裂魔法！|为美好的世界献上祝福！，惠惠
`advancements.pigmen_legion_goal.title`|In the first age, in the first battle...|在最初的时代，最初的战斗中……|DOOM，I. Dogma - Mick Gordon
`advancements.rotten_bombsack_achievment.title`|Plaguebringer|瘟疫使者|泰拉瑞亚，灾厄mod
`advancements.schmelzstern_achievment.title`|St. Anger|圣气凌人|St. Anger - Metallica

来自WuZG的考据：
键名|英文名|中文名|来源推测
-|-|-|-
`entity.pyromancer.borov`|Borov|疣狜兽|Боров 是俄语未采用的疣猪兽的错误翻译，意为骟猪；取狜，流髑之属，当即扬弃，一是设定中它是疣猪兽的古老祖先，二是牯有骟牛之意
`enchantment.pyromancer.yatagarasu`|Yatagarasu|八咫踆乌|八咫烏／八咫ガラス，日本传说中的一种太阳鸟，这里转化为中国传说中的踆乌（太阳黑子）。其实八咫乌传说的来源据《超级大辞林》就是踆乌

摸不着头脑的：
键名|英文名|中文名|来源推测
-|-|-|-
`item.pyromancer.eordums_judgement`|Eordum's Judgement|欧尔达的判决|能找到的最接近这名字的单词是古英语[eorþum](https://en.wiktionary.org/wiki/eor%C3%BEum#Old_English)，又拼eorðum，意为“土地；泥土；地球”（复数与格）。游戏内除give无法获得

2023-01-23 17:22 UTC, mamaruo reviewed
太硬核，受不了了。
水平有限

2023-01-23 17:22 UTC, mamaruo commented on projects/1.18/assets/pyromancer/pyromancer/lang/zh_cn.json
>    "enchantment.pyromancer.ashen_pages": "书页付灰",
| **审查级别** |
|--------------|
| ℹ️ 信息 / 不阻止合并  |
```suggestion
  "enchantment.pyromancer.ashen_pages": "书页付灰",
```

没看懂

原文：**Ashen Pages**

2023-01-23 17:22 UTC, mamaruo commented on projects/1.18/assets/pyromancer/pyromancer/lang/zh_cn.json
> +  "enchantment.pyromancer.traction.desc": "疣猪鞭能以更大力将目标拖拽过来。",
| **审查级别**    | 备注 |
|--------------|----|
| ⚪ 轻微 / 不阻止合并但需三思  |    |
```suggestion
  "enchantment.pyromancer.traction.desc": "疣猪鞭能以更大的力量拖拽目标。",
```

原文：**Hogwhip pulls enemies with greater strength **

2023-01-23 17:22 UTC, mamaruo commented on projects/1.18/assets/pyromancer/pyromancer/lang/zh_cn.json
> +  "enchantment.pyromancer.yatagarasu.desc": "剑的攻击会对着火的目标周边的目标造成伤害。",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |
```suggestion
  "enchantment.pyromancer.yatagarasu.desc": "剑的攻击会对着火的目标周边的目标造成伤害。",
```

这个地方是否有把施加给着火目标的伤害会被“分散”到周围目标的含义？

原文：**Attacks with a sword landed on a burning enemy spread damage dealt to it**

2023-01-23 17:22 UTC, mamaruo commented on projects/1.18/assets/pyromancer/pyromancer/lang/zh_cn.json
> +  "item.pyromancer.cooling_coating.tooltip.line1": "§c你的武器能给予缓慢，并对抗火的生物造成额外伤害",
| **审查级别**    | 备注 |
|--------------|----|
| ⚪ 轻微 / 不阻止合并但需三思  |    |
```suggestion
  "item.pyromancer.cooling_coating.tooltip.line1": "§c你的武器能给目标施加缓慢效果，并对抗火的生物造成额外伤害",
```
原文：**§cMakes your weapons apply Slowness and deal extra damage to fire-resistant mobs**

2023-01-23 17:22 UTC, mamaruo commented on projects/1.18/assets/pyromancer/pyromancer/lang/zh_cn.json
> +  "item.pyromancer.fiery_coating.tooltip.line1": "§c你的武器能给予焚化，并将攻击力的10%变为火焰伤害",
同上

2023-01-24 04:03 UTC, ChuijkYahus commented on projects/1.18/assets/pyromancer/pyromancer/lang/zh_cn.json
> +  "item.pyromancer.fiery_coating.tooltip.line1": "§c你的武器能给予焚化，并将攻击力的10%变为火焰伤害",
```suggestion
  "item.pyromancer.fiery_coating.tooltip.line1": "§c你的武器能给目标施加焚化效果，并将攻击力的10%变为火焰伤害",
```

2023-01-24 04:03 UTC, ChuijkYahus commented on projects/1.18/assets/pyromancer/pyromancer/lang/zh_cn.json
> +  "item.pyromancer.slingshot_brimstone_projectile": "debug",
之前一直以为没有术语（）

这些基本上可以看做占位符

2023-01-24 04:07 UTC, ChuijkYahus commented on projects/1.18/assets/pyromancer/pyromancer/lang/zh_cn.json
>    "enchantment.pyromancer.ashen_pages": "书页付灰",
这个魔咒适用于烈焰日志，参见`item.pyromancer.blazing_journal.tooltip.line1`这些键

觉得名称大概还行就没改

2023-01-24 04:25 UTC, ChuijkYahus commented on projects/1.18/assets/pyromancer/pyromancer/lang/zh_cn.json
> +  "enchantment.pyromancer.yatagarasu.desc": "剑的攻击会对着火的目标周边的目标造成伤害。",
测试了一下
现版本剑对直接目标造成的伤害没有减小，只是同时能对周围的实体造成伤害

2023-01-24 04:28 UTC, mamaruo commented on projects/1.18/assets/pyromancer/pyromancer/lang/zh_cn.json
> +  "enchantment.pyromancer.yatagarasu.desc": "剑的攻击会对着火的目标周边的目标造成伤害。",
收到

2023-01-24 04:29 UTC, mamaruo submitted a review, later dismissed

2023-01-24 04:31 UTC, ChuijkYahus commented
再标记一下#2589（）

2023-02-05 18:14 UTC, Ricky-fight requested changes

2023-02-05 18:14 UTC, Ricky-fight commented on projects/1.18/assets/pyromancer/pyromancer/lang/zh_cn.json
> +  "advancements.brimstone_goal.descr": "开采硫磺矿石并获取硫磺石",
```suggestion
  "advancements.brimstone_goal.descr": "开采硫磺石矿石并获取硫磺石",
```

2023-02-05 18:14 UTC, Ricky-fight commented on projects/1.18/assets/pyromancer/pyromancer/lang/zh_cn.json
> +  "advancements.hogwhip_achievment.title": "Dungeon Master",
这个保留你是故意的还是不小心的（（（

2023-02-05 18:26 UTC, ChuijkYahus commented on projects/1.18/assets/pyromancer/pyromancer/lang/zh_cn.json
> +  "advancements.hogwhip_achievment.title": "Dungeon Master",
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/2523#issuecomment-1287640899
是故意的（）

2023-02-05 19:12 UTC, Ricky-fight approved these changes

2023-02-05 19:30 UTC, ChuijkYahus commented
再次标记同模组pr#2859（）

2023-08-05 06:47 UTC, Cactusstudent commented
那这个PR现在是什么状态？

2023-08-05 06:53 UTC, ChuijkYahus commented
> 那这个PR现在是什么状态？

不知道

2023-08-06 10:44 UTC, merged