tiny-pipes翻译新增
CFPAOrg/Minecraft-Mod-Language-Package pull request #2528
Opened 2022-10-22 12:58 UTC by JumpSteve2008

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-10-22 13:32 UTC, Cactusstudent commented
请将所有半角符号更改为全角符号

2022-10-22 13:33 UTC, Cactusstudent commented on projects/1.18/assets/tiny-pipes/tinypipes/lang/zh_cn.json
> +    "message.item.tinypipes.energy_pipe": "可以把Forge能量从输入端传输到接收端.\n用一把红石扳手去用鼠标右键点击来改变输入输出面.\n用空手右键点击可使用桶装液体设置过滤器.",
```suggestion
    "message.item.tinypipes.energy_pipe": "可以把FE从输入端传输到接收端.\n用一把红石扳手去用鼠标右键点击来改变输入输出面.\n用空手右键点击可使用桶装液体设置过滤器.",

```

2022-10-22 13:36 UTC, JumpSteve2008 commented on projects/1.18/assets/tiny-pipes/tinypipes/lang/zh_cn.json
> +    "message.item.tinypipes.energy_pipe": "可以把Forge能量从输入端传输到接收端.\n用一把红石扳手去用鼠标右键点击来改变输入输出面.\n用空手右键点击可使用桶装液体设置过滤器.",
好的

2022-11-08 12:52 UTC, ChuijkYahus reviewed
不是很懂作者口中的红石扳手是个啥

2022-11-08 12:52 UTC, ChuijkYahus commented on projects/1.18/assets/tiny-pipes/tinypipes/lang/zh_cn.json
> +  "tinypipes.gui.pipe_config.msg.disabled":"Disabled: 不允许连接,不会输出/输入"
```suggestion
  "tinypipes.gui.pipe_config.msg.enabled": "开启：允许输出并且连接其他的管道",
  "tinypipes.gui.pipe_config.msg.pulling": "拉取：允许输入",
  "tinypipes.gui.pipe_config.msg.disabled": "禁用：不允许连接，不会输出/输入"
```
三个原本是英文的地方拗的中文名

2022-11-08 12:52 UTC, ChuijkYahus commented on projects/1.18/assets/tiny-pipes/tinypipes/lang/zh_cn.json
> +  "message.item.tinypipes.item_pipe": "可以在容器之间传输物品。\n用一把红石扳手去用鼠标右键点击来改变输入输出面。\n空手用鼠标右键点击以打开GUI。",
```suggestion
  "message.item.tinypipes.item_pipe": "可以在容器之间传输物品。\n手持红石扳手右击改变输入输出面。\n空手右击以打开GUI。",
```

2022-11-08 12:52 UTC, ChuijkYahus commented on projects/1.18/assets/tiny-pipes/tinypipes/lang/zh_cn.json
> +  "message.item.tinypipes.item_filter_pipe": "可以在容器之间传输被允许的物品。\n空手用鼠标右键点击以打开过滤器。\n用一把红石扳手去用鼠标右键点击来改变输入输出面。",
```suggestion
  "message.item.tinypipes.item_filter_pipe": "可以在容器之间传输被允许的物品。\n空手右击以打开过滤器。\n手持红石扳手右击改变输入输出面。",
```

2022-11-08 12:52 UTC, ChuijkYahus commented on projects/1.18/assets/tiny-pipes/tinypipes/lang/zh_cn.json
> +  "message.item.tinypipes.fluid_pipe": "可以在流体储罐之间传输物品。\n用一把红石扳手去用鼠标右键点击来改变输入输出面。\n空手用鼠标右键点击以打开GUI。",
```suggestion
  "message.item.tinypipes.fluid_pipe": "可以在流体储罐之间传输流体。\n手持红石扳手右击改变输入输出面。\n空手右击以打开GUI。",
```

2022-11-08 12:52 UTC, ChuijkYahus commented on projects/1.18/assets/tiny-pipes/tinypipes/lang/zh_cn.json
> +  "message.item.tinypipes.fluid_filter_pipe": "可以在流体储罐之间传输被允许的流体。\n用空手右键点击可使用桶装液体设置过滤器。\n用一把红石扳手去用鼠标右键点击来改变输入输出面。",
```suggestion
  "item.tinypipes.fluid_filter_pipe": "迷你流体过滤管道",
  "message.item.tinypipes.fluid_filter_pipe": "可以在流体储罐之间传输被允许的流体。\n空手右击可使用桶装液体设置过滤器。\n手持红石扳手右击改变输入输出面。",
```

2022-11-08 12:52 UTC, ChuijkYahus commented on projects/1.18/assets/tiny-pipes/tinypipes/lang/zh_cn.json
> +  "message.item.tinypipes.redstone_pipe": "可以将多个红石信号无损传输。\n用染料去用鼠标右键点击连接处来改变颜色频率。\n输出将只输出匹配的彩色频率信号。\n用一把红石扳手去用鼠标右键点击来改变输入输出面。\n空手用鼠标右键点击以打开GUI。",
```suggestion
  "message.item.tinypipes.energy_pipe": "可以把FE从输入端传输到接收端。\n手持红石扳手右击改变输入输出面。\n空手右击可使用流体桶设置过滤器。",
  "item.tinypipes.redstone_pipe": "迷你红石能量管道",
  "message.item.tinypipes.redstone_pipe": "可以将多个红石信号无损传输。\n手持染料右击连接处来改变颜色频道。\n将只输出至颜色一致的端口处。\n手持红石扳手右击改变输入输出面。\n空手右击以打开GUI。",
```

2022-11-11 13:54 UTC, Cactusstudent commented on projects/1.18/assets/tiny-pipes/tinypipes/lang/zh_cn.json
> +  "item.tinypipes.item_filter_pipe": "迷你物品过滤管",
```suggestion
  "item.tinypipes.item_filter_pipe": "迷你物品过滤管道",

```

2022-11-11 13:54 UTC, Cactusstudent commented on projects/1.18/assets/tiny-pipes/tinypipes/lang/zh_cn.json
> +  "tinypipes:fluid_filter": "液体过滤名单",
这两句不知道游戏内是体现为一个名单还是和一般的过滤器一样，如果一样，那应该是
```suggestion
  "tinypipes:item_filter": "物品过滤器",
  "tinypipes:fluid_filter": "液体过滤器",
```
以此保证前后文统一

2022-11-21 15:24 UTC, mamaruo commented
/diff

2022-11-21 15:35 UTC, mamaruo requested changes

2022-11-21 15:35 UTC, mamaruo commented on projects/1.18/assets/tiny-pipes/tinypipes/lang/zh_cn.json
> +  "item.tinypipes.energy_pipe": "迷你能量管道",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   能量何处来？   |
```suggestion
  "item.tinypipes.redstone_pipe": "迷你红石能量管道",
```
原文：**Tiny Redstone Pipe**

2022-12-03 12:51 UTC, dovisutu commented on projects/1.18/assets/tiny-pipes/tinypipes/lang/zh_cn.json
> +  "item.tinypipes.redstone_pipe": "迷你红石能量管道",
```suggestion
  "item.tinypipes.redstone_pipe": "迷你红石管道",
```
既然有`能量`管道，似乎这里就是单纯传输红石信号的管道。

2022-12-03 12:52 UTC, dovisutu commented
~完了，mamaruo的审核现在是错位的了~
~难怪我看着有点奇怪~

预计改完这个就可以approve了？

2022-12-06 14:59 UTC, dovisutu commented
~随机挑选一位幸运审核来re-review~

2022-12-12 17:32 UTC, ChuijkYahus approved these changes

2022-12-13 03:22 UTC, merged