提交Xaero's Minimap英文文件
CFPAOrg/Minecraft-Mod-Language-Package pull request #2537
Opened 2022-10-23 14:41 UTC by Annijang

- [ x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；
- [ ] 我已使用`/diff`指令检查`zh_cn`术语使用

2022-10-23 14:52 UTC, Annijang commented
第一次跟着酒妈的pr教程学的，不清楚有什么问题qwq

2022-10-23 14:56 UTC, Cactusstudent commented
> 第一次跟着酒妈的pr教程学的，不清楚有什么问题qwq

（可以输入/diff来获得术语检查， 就直接在下面发/diff就好）

2022-10-23 14:57 UTC, Annijang commented
/diff

2022-10-23 14:58 UTC, Cactusstudent commented
还有就是这个路modid怎么怪怪的……不应该是xaerominimap嘛？（模组作者也是，里面加了一堆modid）

2022-10-23 15:10 UTC, Annijang commented
> 还有就是这个路modid怎么怪怪的……不应该是xaerominimap嘛？（模组作者也是，里面加了一堆modid）

不知道，我是直接将1.19.2版本的文件复制到1.18上，词条会有多余但是格式没问题

2022-10-23 15:11 UTC, Cactusstudent commented
> > 还有就是这个路modid怎么怪怪的……不应该是xaerominimap嘛？（模组作者也是，里面加了一堆modid）
> 
> 不知道，我是直接将1.19.2版本的文件复制到1.18上，词条会有多余但是格式没问题

我咋觉得这三个的语言文件都一毛一样……

2022-10-23 15:12 UTC, Annijang commented
> > > > 还有就是这个路modid怎么怪怪的……不应该是xaerominimap嘛？（模组作者也是，里面加了一堆modid）
> > > 
> > > 
> > > 不知道，我是直接将1.19.2版本的文件复制到1.18上，词条会有多余但是格式没问题
> > 
> > 
> > 我咋觉得这三个的语言文件都一毛一样……要不还是改一下路径吧……
> 
> 可以用move命令

第一次尝试pr，不熟悉qwq

2022-10-23 15:16 UTC, Cactusstudent commented
/mv "projects/1.18/assets/xaeros-minimap/xaerobetterpvp/" "projects/1.18/assets/xaeros-minimap/xaerominimap/"
（应该是这一串子，你一输就好了，我不是maintain也不是author所以用不了）

2022-10-23 15:27 UTC, Demonese requested changes
请 **按1.18.2版mod** 来翻译和提交文件

2022-10-23 15:46 UTC, Demonese commented
/update–en xaeros-minimap 1.18

2022-10-24 08:27 UTC, Cactusstudent commented
> /update–en xaeros-minimap 1.18
–应该改成-

2022-11-16 13:02 UTC, Cactusstudent commented
官方有汉化了，这里的要不就关了？

2022-11-21 17:15 UTC, closed without merging