Music-duration-reducer 1.18 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2538
Opened 2022-10-24 07:47 UTC by XiaoXin1113

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x] 刷新 PR 的标签/状态，有需要再点击；
- [x] 我已使用`/diff`指令检查`zh_cn`术语使用

2022-10-24 07:55 UTC, Cactusstudent commented
啊啊啊啊啊，检查单别全都勾上啊……

2022-10-24 08:08 UTC, ChuijkYahus commented
/diff

2022-10-24 09:09 UTC, Cactusstudent approved these changes
时间用长短没啥问题

2022-10-24 16:45 UTC, Demonese commented
有没有在游戏内实测过是“除以长度”还是不明所以的“分割长度”？

2022-10-24 16:49 UTC, Demonese requested changes
修改分割为除以

2022-10-24 16:55 UTC, Demonese approved these changes

2022-10-25 09:33 UTC, Cyl18 requested changes
![image](https://user-images.githubusercontent.com/14993992/197738467-9b531356-f81e-4b40-9fc0-987623772f59.png)
我挺好奇的 这个模组forge版本没有assets文件夹 只有fabric有

2022-10-25 09:36 UTC, Demonese commented
难不成是作者忘记加assets了，不过最好还是测试一下。
另外，你没投错位置吧？比如应该提交到fabric版。

2022-10-25 09:37 UTC, Cactusstudent commented
![image](https://user-images.githubusercontent.com/97865546/197739429-03a8aeee-9292-43b1-85e2-2d1662cbbb1c.png)
那话说这些破玩意咋扒出来的

2022-10-25 09:43 UTC, Cyl18 commented
> ![image](https://user-images.githubusercontent.com/97865546/197739429-03a8aeee-9292-43b1-85e2-2d1662cbbb1c.png) 那话说这些破玩意咋扒出来的

这个是扒的是仓库里main分支的语言文件

2022-10-25 09:45 UTC, Cactusstudent commented
> > ![image](https://user-images.githubusercontent.com/97865546/197739429-03a8aeee-9292-43b1-85e2-2d1662cbbb1c.png) 那话说这些破玩意咋扒出来的
> 
> 这个是扒的是仓库里main分支的语言文件

找到原因了，扒的文件是从quilt的仓库来的……

2022-11-10 14:31 UTC, dovisutu commented
等等，这玩意forge居然是硬编码......
https://github.com/LudoCrypt/Music-Duration-Reducer-For-Forge/blob/170400f1769e5c39d3d0bad6c203371442344b98/src/main/java/net/ludocrypt/musicdr/MusicDr.java#L41-L76

但是fabric的 _**1.19**_ 是上了assets的
（别问我为什么是1.19，fabric库上面的分支过了117就是119）
https://github.com/LudoCrypt/Music-Duration-Reducer/blob/f4578dabbbb751aa37679fe07b88d48f25ffcc95/src/main/resources/assets/musicdr/lang/en_us.json

什么情况......

-------

不过，如果forge是硬编码那这边forge的语言文件怎么来的......（

-------

/mv "projects/1.18/assets/music-duration-reducer/musicdr/zh_cn.lang" "projects-fabric/1.18/assets/music-duration-reducer/musicdr/zh_cn.lang"

2022-12-06 14:53 UTC, dovisutu commented
ping @XiaoXin1113

2022-12-13 03:40 UTC, dovisutu commented
- 两个阶段的7天时限均已过去。

2022-12-13 03:40 UTC, closed without merging