random-loot-mod 1.18 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2547
Opened 2022-10-26 10:45 UTC by XiaoXin1113

- [ ] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-10-26 10:45 UTC, XiaoXin1113 commented
/diff

2022-10-26 10:46 UTC, XiaoXin1113 commented
/diff

2022-10-26 10:47 UTC, XiaoXin1113 commented
此处有一个不太会翻译的东西就是这个Random Paxel. Paxel这个词，是不是写错了？应为Pixel?

2022-10-26 10:49 UTC, XiaoXin1113 commented
而且，源代码的gh仓库里并没有1.18版本的模组，所以对此模组抱怀疑态度……

2022-10-26 15:34 UTC, ChuijkYahus commented
> 此处有一个不太会翻译的东西就是这个Random Paxel. Paxel这个词，是不是写错了？应为Pixel?

一般叫`镐尖斧`

2022-10-27 14:20 UTC, Cactusstudent commented on projects/1.18/assets/random-loot-mod/randomloot/lang/zh_cn.json
> +    "item.randomloot.axe": "随即斧",
```suggestion
    "item.randomloot.axe": "随机斧",
```

2022-10-27 14:20 UTC, Cactusstudent commented on projects/1.18/assets/random-loot-mod/randomloot/lang/zh_cn.json
> +    "item.randomloot.paxel": "Random Paxel",
```suggestion
    "item.randomloot.paxel": "随机镐尖斧",
```

2022-10-28 13:00 UTC, Cactusstudent commented
> 而且，源代码的gh仓库里并没有1.18版本的模组，所以对此模组抱怀疑态度……

那……你这语言文件那里来的？

2022-10-28 13:02 UTC, Cactusstudent requested changes
CF上都没有1.18版本……这哪里来的？

2022-10-28 13:07 UTC, NFLSmathCircle commented
> CF上都没有1.18版本……这哪里来的？

MMLP仓库里1.18文件夹里找的……当时好像更新备注是cp 1.16 to 1.18之类的

2022-10-28 13:08 UTC, NFLSmathCircle commented
sorry, 这是我@XiaoXin1113另一个号

2022-10-28 13:08 UTC, Cactusstudent commented
> sorry, 这是我@XiaoXin1113另一个号

好家伙（）

2022-10-28 13:09 UTC, XiaoXin1113 commented
对对对 先搁着先搁着

2023-04-01 07:26 UTC, ChuijkYahus commented
这搁了多久了（）

2023-07-16 10:39 UTC, closed without merging