[R] 提交 Security Craft 模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #2573
Opened 2022-11-02 02:14 UTC by comrg

- [ ] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-11-02 08:52 UTC, ChuijkYahus commented
#1835

2022-11-02 11:41 UTC, iamliuzy requested changes
### 有明显机翻痕迹，强烈建议：
1. 把**所有符号**换成**英文半角**符号；
2. 根据所给的建议修改，同时检查是否**还有翻译错误**。

今天我暂时看到33行，过两天继续来看

2022-11-02 11:41 UTC, iamliuzy commented on projects/1.16/assets/security-craft/securitycraft/lang/zh_cn.json
> +    “block.securitycraft.reinforced_iron_trapdoor”：的“强化铁闸板门”，
```suggestion
    “block.securitycraft.reinforced_iron_trapdoor”：“强化铁活板门”，
```

2022-11-02 11:41 UTC, iamliuzy commented on projects/1.16/assets/security-craft/securitycraft/lang/zh_cn.json
> +    “block.securitycraft.reinforced_cobweb”：“强化织网”，
```suggestion
    “block.securitycraft.reinforced_cobweb”：“强化蜘蛛网”，
```

2022-11-02 11:41 UTC, iamliuzy commented on projects/1.16/assets/security-craft/securitycraft/lang/zh_cn.json
> +    “block.securitycraft.username_logger”：“用户名记录器”，
```suggestion
    “block.securitycraft.username_logger”：“用户名记录仪”，

```

2022-11-02 11:41 UTC, iamliuzy commented on projects/1.16/assets/security-craft/securitycraft/lang/zh_cn.json
> +    “block.securitycraft.mine”：“我的”，
```suggestion
    “block.securitycraft.mine”：“矿物”，
```

2022-11-02 11:41 UTC, iamliuzy commented on projects/1.16/assets/security-craft/securitycraft/lang/zh_cn.json
> +    “block.securitycraft.dirt_mine”：“我的泥土”，
```suggestion
    “block.securitycraft.dirt_mine”：“泥土矿”，
```

2022-11-02 11:41 UTC, iamliuzy commented on projects/1.16/assets/security-craft/securitycraft/lang/zh_cn.json
> +    “block.securitycraft.diamond_mine”：“钻石矿矿”，
```suggestion
    “block.securitycraft.diamond_mine”：“钻石矿”，
```

2022-11-02 11:41 UTC, iamliuzy commented on projects/1.16/assets/security-craft/securitycraft/lang/zh_cn.json
> +    “block.securitycraft.furnace_mine”：“炉矿”，
```suggestion
    “block.securitycraft.furnace_mine”：“熔炉矿”，
```

2022-11-02 11:41 UTC, iamliuzy commented on projects/1.16/assets/security-craft/securitycraft/lang/zh_cn.json
> +    “block.securitycraft.smoker_mine”：“吸烟者矿井”，
```suggestion
    “block.securitycraft.smoker_mine”：“烟熏炉矿”，
```

2022-11-02 11:41 UTC, iamliuzy commented on projects/1.16/assets/security-craft/securitycraft/lang/zh_cn.json
> +    “block.securitycraft.blast_furnace_mine”：“我的高炉”，
```suggestion
    “block.securitycraft.blast_furnace_mine”：“高炉矿”，
```

2022-11-02 11:41 UTC, iamliuzy commented on projects/1.16/assets/security-craft/securitycraft/lang/zh_cn.json
> +    “block.securitycraft.keypad”：“小键盘”，
```suggestion
    “block.securitycraft.keypad”：“密码盘”，
```

2022-11-02 11:41 UTC, iamliuzy commented on projects/1.16/assets/security-craft/securitycraft/lang/zh_cn.json
> +    “block.securitycraft.laser_active”：“主动激光”，
```suggestion
    “block.securitycraft.laser_active”：“激活的激光”，
```

2022-11-02 11:41 UTC, iamliuzy commented on projects/1.16/assets/security-craft/securitycraft/lang/zh_cn.json
> +    “block.securitycraft.bouncing_betty”：“跳跃的贝蒂”，
翻译有点怪，建议查查是不是什么梗。

2022-11-02 11:41 UTC, iamliuzy commented on projects/1.16/assets/security-craft/securitycraft/lang/zh_cn.json
> +    “block.securitycraft.track_mine”：“铁路矿”，
```suggestion
    “block.securitycraft.track_mine”：“铁轨矿”，
```

2022-11-02 11:41 UTC, iamliuzy commented on projects/1.16/assets/security-craft/securitycraft/lang/zh_cn.json
> +    “block.securitycraft.keypad_chest”：“有密码保护的胸部”，
```suggestion
    “block.securitycraft.keypad_chest”:“密码锁箱子”,
```

2022-11-02 11:41 UTC, iamliuzy commented on projects/1.16/assets/security-craft/securitycraft/lang/zh_cn.json
> +    “block.securitycraft.keypad_chest_double”：“大密码保护胸”，
```suggestion
    “block.securitycraft.keypad_chest_double”：“密码锁大箱子”，

```

2022-11-02 11:41 UTC, iamliuzy commented on projects/1.16/assets/security-craft/securitycraft/lang/zh_cn.json
> +    “block.securitycraft.reinforced_chain”：“强化链”，
```suggestion
    “block.securitycraft.reinforced_chain”：“强化锁链”，
```

2022-11-02 13:14 UTC, Cactusstudent commented
请注意，json中存在重大错误，请将所有中文引号改为英文引号

2022-11-03 12:04 UTC, iamliuzy requested changes
大量译名需按照[官方译名](https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96)校对翻译，“reinforced”一律翻译为“强化”，去除所有冒号后面的“的”

2022-11-04 05:46 UTC, closed without merging