controllable翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #2635
Opened 2022-11-26 10:15 UTC by StarryYurnu

- [x ] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x ] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x ] 刷新 PR 的标签/状态，有需要再点击；

2022-11-26 10:42 UTC, Cactusstudent commented
/mv projects/1.12.2/assets/controllable/controllable/zh_cn.lang projects/1.12.2/assets/controllable/controllable/lang/zh_cn.lang

2022-11-26 10:43 UTC, Cactusstudent commented
/update-en controllable 1.12.2

2022-11-26 10:52 UTC, StarryYurnu commented
/update-en controllable 1.12.2

2022-11-26 13:15 UTC, Demonese commented on projects/1.12.2/assets/controllable/controllable/lang/zh_cn.lang
> +controllable.gui.layout.info=使用此虚拟控制器以测试按钮和游戏杆是否与实际控制器匹配。如果按下了错误的按钮，则可以通过点击虚拟控制器上的按钮来重新映像它。如果在按钮上方显示感叹号图标，则表示它没有映射到实际控制器。
```suggestion
controllable.gui.layout.info=使用此虚拟控制器以测试按钮和游戏杆是否与实际控制器匹配。如果按下了错误的按钮，则可以通过点击虚拟控制器上的按钮来重新映射它。如果在按钮上方显示感叹号图标，则表示它没有映射到实际控制器。
```

2022-11-26 13:16 UTC, Demonese commented on projects/1.12.2/assets/controllable/controllable/lang/zh_cn.lang
> +controllable.gui.layout.thumbsticks=游戏杆设置
一般 thumbsticks 会翻译成摇杆（手柄摇杆）比较多，是否考虑一下？

2022-11-26 13:17 UTC, Demonese commented on projects/1.12.2/assets/controllable/controllable/lang/zh_cn.lang
> +controllable.gui.title.thumbstick_settings=游戏杆设置
同上

2022-11-26 13:18 UTC, Demonese requested changes
没翻译完，请及时更新翻译

2022-11-26 15:50 UTC, dovisutu commented
明天我试着给这提交补一个en_us.lang上去

2022-11-27 15:25 UTC, dovisutu reviewed
帮忙译了一下
有一处没看懂原文......

2022-11-27 15:25 UTC, dovisutu commented on projects/1.12.2/assets/controllable/controllable/lang/zh_cn.lang
> +controllable.key.debugInfo=Show Debug Info
```suggestion
controllable.key.debugInfo=显示调试信息
```

2022-11-27 15:25 UTC, dovisutu commented on projects/1.12.2/assets/controllable/controllable/lang/zh_cn.lang
> +controllable.options.autoSelect.desc=If enabled, controller will be automatically selected on start up or when plugged in
```suggestion
controllable.options.autoSelect.desc=启用后，将在启动游戏或插入控制手柄时自动选择该手柄
```
不知道对不对

2022-11-27 15:25 UTC, dovisutu commented on projects/1.12.2/assets/controllable/controllable/lang/zh_cn.lang
> +controllable.options.consoleHotbar.desc=If enabled, hotbar will render closer to the center of the screen like on console.
```suggestion
controllable.options.consoleHotbar.desc=启用后，快捷栏的显示位置将更靠近中心，与主机上类似
```
`console`->`主机`？

2022-11-27 15:25 UTC, dovisutu commented on projects/1.12.2/assets/controllable/controllable/lang/zh_cn.lang
> +controllable.options.consoleHotbar=控制台快捷栏
```suggestion
controllable.options.consoleHotbar=主机式快捷栏
```

2022-11-27 15:25 UTC, dovisutu commented on projects/1.12.2/assets/controllable/controllable/lang/zh_cn.lang
> +controllable.options.controllerIcons.desc=The controller icons to use in game to display actions
```suggestion
controllable.options.controllerIcons.desc=用以显示手柄操作的图示
```

2022-11-27 15:25 UTC, dovisutu commented on projects/1.12.2/assets/controllable/controllable/lang/zh_cn.lang
> +controllable.options.cursorType.desc=The image to use for the cursor. This only applies if virtual mouse is enabled!
```suggestion
controllable.options.cursorType.desc=游标使用的图标。只有启用了虚拟鼠标，该功能才可用！
```

2022-11-27 15:25 UTC, dovisutu commented on projects/1.12.2/assets/controllable/controllable/lang/zh_cn.lang
> +controllable.options.deadZone.desc=The distance you have to move the thumbstick before it's input is registered. This fixes drifting as some thumbsticks don't center to zero.
```suggestion
controllable.options.deadZone.desc=手柄产生输入所需的最小拨动距离。可以修复由于手柄不归零导致的持续漂移。
```

2022-11-27 15:25 UTC, dovisutu commented on projects/1.12.2/assets/controllable/controllable/lang/zh_cn.lang
> +controllable.options.forceFeedback.desc=If enabled, some actions will cause the controller to vibrate
```suggestion
controllable.options.forceFeedback.desc=启用后，部分操作将使手柄震动
```

2022-11-27 15:25 UTC, dovisutu commented on projects/1.12.2/assets/controllable/controllable/lang/zh_cn.lang
> +controllable.options.invertLook.desc=If enabled, inverts the controls on the Y axis for the camera
```suggestion
controllable.options.invertLook.desc=启用后，反转Y轴上视角的控制方向
```

2022-11-27 15:25 UTC, dovisutu commented on projects/1.12.2/assets/controllable/controllable/lang/zh_cn.lang
> +controllable.options.mouseSpeed.desc=The speed which the cursor or virtual mouse moves around the screen
```suggestion
controllable.options.mouseSpeed.desc=游标或虚拟鼠标在屏幕上移动的速度
```

2022-11-27 15:25 UTC, dovisutu commented on projects/1.12.2/assets/controllable/controllable/lang/zh_cn.lang
> +controllable.options.quickCraft=Quick Craft
```suggestion
controllable.options.quickCraft=快速合成
```

2022-11-27 15:25 UTC, dovisutu commented on projects/1.12.2/assets/controllable/controllable/lang/zh_cn.lang
> +controllable.options.quickCraft.desc=If enabled, allows you to craft quickly when clicking an item in the recipe book
```suggestion
controllable.options.quickCraft.desc=启用后，点击配方书中的物品可以快速合成该物品
```

2022-11-27 15:25 UTC, dovisutu commented on projects/1.12.2/assets/controllable/controllable/lang/zh_cn.lang
> +controllable.options.renderMiniPlayer.desc=If enabled, the player will render in the top left corner likes Bedrock Edition
```suggestion
controllable.options.renderMiniPlayer.desc=启用后，左上角将显示玩家的模型，与基岩版的行为类似
```

2022-11-27 15:25 UTC, dovisutu commented on projects/1.12.2/assets/controllable/controllable/lang/zh_cn.lang
> +controllable.options.rotationSpeed.desc=The speed which the camera turns in game
```suggestion
controllable.options.rotationSpeed.desc=玩家视角转动的速度
```

2022-11-27 15:25 UTC, dovisutu commented on projects/1.12.2/assets/controllable/controllable/lang/zh_cn.lang
> +controllable.tooltip.craft=Click to Craft Item
```suggestion
controllable.tooltip.craft=点击以合成物品
```

2022-11-27 15:25 UTC, dovisutu commented on projects/1.12.2/assets/controllable/controllable/lang/zh_cn.lang
> +controllable.options.virtualMouse.desc=If enabled, the game will use a virtual cursor instead of the real cursor. This must be turned on to be able to run multiple instances!
```suggestion
controllable.options.virtualMouse.desc=启用后，游戏将会使用虚拟游标而非电脑的真实游标。如果要正常运行多个游戏示例，必须启用该功能!
```

2022-12-21 15:31 UTC, dovisutu commented
- 7+7时限进入第一阶段。从该评论发出的时间开始计时。

ping @StarryYurnu

2022-12-28 12:25 UTC, ChuijkYahus commented
* 7+7时限进入第二阶段。从该评论发出的时间开始计时。

ping @StarryYurnu

2023-01-10 09:29 UTC, dovisutu commented
~居然又过了14天~
- 7+7时限已到。根据处理未相应提交的[试行]处理方案，关闭本提交。若可继续进行更改，可重新打开本提交，或创建新提交。

2023-01-10 09:29 UTC, closed without merging