Basic Shields[Fabric] 和 Trinkets(Fabric) 和 Doodads[Fabric] 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2641
Opened 2022-11-27 17:57 UTC by ErrorPower2001

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

### 描述
[Basic Shields](https://www.curseforge.com/minecraft/mc-mods/basic-shields-fabric) 作者github项目上说不更新了，就不向作者提交了，模组名翻译为基础盾牌。  
基础盾牌中有大量的其他模组的联动材料盾牌、盾牌颜色，颜色名按照Wiki翻译，联动材料名字按照mcmod百科的 **[模组翻译参考词典](https://dict.mcmod.cn)** 查询根据其他模组较多的名字翻译，也存在冲突比如 **Tourmaline** 有 **电气石** 和 **碧玺** 两种，选择了碧玺作为翻译。  
其中有一种材料名为Carbonado，我没查到词典，但是找到了这个[Carbonado](https://www.mcmod.cn/class/4763.html)，暂时不作翻译，有待商讨/

[Trinkets (Fabric)](https://www.curseforge.com/minecraft/mc-mods/trinkets) 的CurseForge链接已由/trinkets-fabric导向/trinkets，我翻译时没查看Minecraft-Mod-Language-Package，上传发现之前已有的翻译发现已经不全了，我直接删除换上了我的翻译文件。

[Doodads [Fabric]](https://www.curseforge.com/minecraft/mc-mods/doodads-fabric)  
原文`"item.doodads.bendy_straw": "Bendy Straw"`应该是指派对上的那种卷起来的吹管（游戏里的纹理是这样的），吹气会伸直发声，我想不到这东西叫什么名字，翻译为**卷起来的吸管**有待商讨

---

### 疑问
描述性的地方说到斧是应该说**斧**、**斧头**还是**斧子**？
`"item.doodads.loggers_glove.tooltip.shift": "防止斧将原木去皮"`

2022-11-27 18:11 UTC, ErrorPower2001 commented
/add-mapping doodads-fabric 649882

2022-11-27 18:12 UTC, ErrorPower2001 commented
/add-mapping trinkets 341284

2022-11-27 18:18 UTC, ErrorPower2001 commented
/diff

2022-11-28 04:41 UTC, ErrorPower2001 commented
Doodads已经有人向官方提交了其他的翻译[zh_cn.json](https://github.com/ArcanePigeon/Doodads/blob/1.19/src/main/resources/assets/doodads/lang/zh_cn.json)

2022-12-11 11:05 UTC, DrIceTea123 commented
`Basic Shields`的联动模组`More Gems`有官方汉化文件（虽然不全但大多数都有）
`More Gems`中有名为`Carbonado`的物品，官译为`黑金刚石`；
此外也有名为`Tourmaline`的物品，官译为`碧玺`。
像这种有大量联动模组的模组翻译最好同时参照联动模组的译文。
（以上内容仅供参考）

2023-01-19 10:31 UTC, DrIceTea123 requested changes
简单看了一下（没开游戏的那种），部分内容需要考虑上下文一致性
记得不要单改一处，后文中同样的问题我没有二次标记

2023-01-19 10:31 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "item.doodads.magic_plum.tooltip.shift": "一个消耗性的图腾",
```suggestion
  "item.doodads.magic_plum.tooltip.shift": "一个一次性的图腾",
```

2023-01-19 10:31 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "item.doodads.paintbrush.tooltip2.shift": "或者主手拿着水桶时洗净方块",
```suggestion
  "item.doodads.paintbrush.tooltip.shift": "副手拿着画笔时，主手拿着染料可以给方块染色",
  "item.doodads.paintbrush.tooltip2.shift": "或主手拿着水桶可以洗净方块",
```

2023-01-19 10:31 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "item.doodads.duct_tape": "管状胶带",
```suggestion
  "item.doodads.duct_tape": "强力胶布",
```

2023-01-19 10:31 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "item.doodads.sun_ring.tooltip.shift": "在白天为你提供更高伤害",
```suggestion
  "item.doodads.sun_ring.tooltip.shift": "在白天为你提供伤害提升",
```

2023-01-19 10:31 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "item.doodads.moon_ring.tooltip.shift": "在夜晚为你提供更高伤害",
```suggestion
  "item.doodads.moon_ring.tooltip.shift": "在夜晚为你提供伤害提升",
```

2023-01-19 10:31 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "item.doodads.celestial_ring.tooltip.shift": "全天都为你提供更高伤害",
```suggestion
  "item.doodads.celestial_ring.tooltip.shift": "全天都为你提供更高的伤害提升",
```

2023-01-19 10:31 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "item.doodads.cactus_ring.tooltip": "对攻击者造成伤害",
```suggestion
  "item.doodads.cactus_ring.tooltip": "对攻击你的生物造成伤害",
```

2023-01-19 10:31 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "item.doodads.glare_plushie": "怒目怪毛绒玩具",
这个翻译……“怒目怪”可能不太合适，需要再斟酌一下
<del>我也没想好该怎么改</del>

2023-01-19 10:31 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "item.doodads.doodad_bundle.tooltip": "随机获得一些 Doodad",
```suggestion
  "item.doodads.doodad_bundle.tooltip": "随机获得一个小玩意",
```

2023-01-19 10:31 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "death.attack.rubber_band.item": "%1$s 被 %2$s 用 %3$s 弹死",
加个“了”会不会好一点

2023-01-19 10:31 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "death.attack.scissors.item": "%1$s 乱玩 %2$s",
两个同类通知消息格式最好相同
```suggestion
  "death.attack.scissors": "%1$s 带着剪刀乱跑",
  "death.attack.scissors.item": "%1$s 带着 %2$s 乱跑",
```

2023-01-19 10:31 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "text.autoconfig.doodads.option.doodadTrinkets": "Trinkets",
```suggestion
  "text.autoconfig.doodads.option.doodadTrinkets": "饰品",
```

2023-01-19 10:31 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "text.autoconfig.doodads.option.doodadTrinkets.enableSlimeyShoes": "启用黏糊糊的靴子",
注意上下文相同物品翻译一致
```suggestion
  "text.autoconfig.doodads.option.doodadTrinkets.enableSlimeyShoes": "启用史莱姆靴",
```

2023-01-19 10:31 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "text.autoconfig.doodads.option.doodadWorldGen.enableDoodadSpawnsInVillages": "启用 Doodads 在村庄箱子生成",
```suggestion
  "text.autoconfig.doodads.option.doodadWorldGen.enableDoodadSpawnsInVillages": "允许Doodad物品在村庄箱子生成",
```

2023-01-19 10:31 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/trinkets/trinkets/lang/zh_cn.json
> +	"trinkets.tooltip.slots.single" : "可装备在 %d 饰品槽中",
这里需要空格吗？按游戏内实际表现来
我的理解是中间插入的是饰品槽的名称，这些在下文中已翻译成中文，无需空格

2023-01-19 10:31 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/trinkets/trinkets/lang/zh_cn.json
> +	"trinkets.slot.offhand.ring": "副手戒指"
此处最好符合原文，只有`手套` `戒指`二字就够了

2023-01-19 10:31 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/trinkets/trinkets/lang/zh_cn.json
> +	"trinkets.slot.feet.shoes": "靴",
都是两个字，要不改成`靴子`吧

2023-01-20 10:05 UTC, ErrorPower2001 commented on projects/1.18-fabric/assets/basic-shields-fabric/basicshields/lang/zh_cn.json
> +  "text.autoconfig.basicshields.option.adabranium_nether_shield_enchantability":"下界戈伯岩盾牌反弹范围",
太久之前提交的翻译了，我也很久没玩这个模组了，不记得是不是有这么一个矿石叫做`下届戈伯岩`

2023-01-20 10:05 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/basic-shields-fabric/basicshields/lang/zh_cn.json
> +  "item.basicshields.gobber_nether_shield": "下界戈伯岩盾牌",
要看盾牌的合成配方
应该是用`下界戈伯`合成的，不是`下界岩`

2023-01-20 10:56 UTC, ErrorPower2001 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "item.doodads.sun_ring.tooltip.shift": "在白天为你提供更高伤害",
我现在也没法开游戏，我记得并没有为玩家增加`伤害提升`的药水效果，为了避免歧义描述为`提供更高伤害`。待新年后详细测试

2023-01-20 10:58 UTC, ErrorPower2001 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "item.doodads.sun_ring.tooltip.shift": "在白天为你提供更高伤害",
> 我现在也没法开游戏，我记得并没有为玩家增加`伤害提升`的药水效果，为了避免歧义描述为`提供更高伤害`。待新年后详细测试

或是MC术语就是`提供伤害提升`？

2023-01-20 11:02 UTC, ErrorPower2001 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "item.doodads.glare_plushie": "怒目怪毛绒玩具",
> 这个翻译……“怒目怪”可能不太合适，需要再斟酌一下 ~我也没想好该怎么改~

毕竟是官方投票落选生物，并没有正式命名，我参考的是公布投票时WuGuangYao大佬的翻译

2023-01-20 11:31 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "item.doodads.sun_ring.tooltip.shift": "在白天为你提供更高伤害",
没有`伤害提升`的药水效果，只有`力量`
我只是感觉`提供更高伤害`听起来怪怪的所以才改
你如果觉得`提供更高伤害`足够合适就不用管我这个

2023-01-20 13:36 UTC, ErrorPower2001 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "text.autoconfig.doodads.option.doodadTrinkets": "Trinkets",
Trinket是模组名称，目前未进行翻译（功能是饰品API，译作`饰品``饰品栏``饰品槽`都可），决定保留

2023-01-20 13:36 UTC, ErrorPower2001 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "item.doodads.doodad_bundle.tooltip": "随机获得一些 Doodad",
因为我没有翻译模组名，将修改为`随机获得一些 Doodad 的小玩意`

2023-01-20 13:54 UTC, ErrorPower2001 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "item.doodads.doodad_bundle.tooltip": "随机获得一些 Doodad",
最后确定为`随机获得一些 Doodad 的物品`，与后文其他修改一致

2023-01-20 14:34 UTC, ErrorPower2001 commented on projects/1.18-fabric/assets/basic-shields-fabric/basicshields/lang/zh_cn.json
> +  "text.autoconfig.basicshields.option.vanilla_wooden_shield_enchantability":"木制盾牌反弹范围",
先直译作「附魔能力」吧，目前这个选项还找不到怎么用

2023-01-20 15:44 UTC, DrIceTea123 requested changes
有点小失误，别的应该没啥了……吧

2023-01-20 15:44 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/basic-shields-fabric/basicshields/lang/zh_cn.json
> +  "text.autoconfig.basicshields.option.unbreakable_gobber_end_shield":"使 末影戈伯盾牌不可破坏？",
多个空格
```suggestion
  "text.autoconfig.basicshields.option.unbreakable_gobber_end_shield":"使末影戈伯盾牌不可破坏？",
```

2023-01-20 15:44 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "item.doodads.bendy_straw": "卷起来的吸管",
这个有没有想好怎么翻译合适

2023-01-20 15:44 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "text.autoconfig.doodads.option.doodadItems.enableDuctTape": "启用管状胶带",
上面改了这里没改，上面是`强力胶布`

2023-01-20 15:44 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "text.autoconfig.doodads.option.doodadItems.enableGlareStaff": "启用怒目怪杖",
上下文不一致，上面是`怒目怪法杖`

2023-01-20 15:44 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/doodads-fabric/doodads/lang/zh_cn.json
> +  "text.autoconfig.doodads.option.doodadTrinkets": "Trinkets",
这里下文是有关饰品的配置选项，翻译成`饰品`是合适的
不翻译的情况是确定此处作为模组名称使用时，而此处应该不是作为模组名称使用的，应当翻译

2023-01-20 15:44 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/trinkets/trinkets/lang/zh_cn.json
> +	"trinkets.slot.offhand.ring": "手戒指"
“手戒指”啊这

2023-01-20 15:53 UTC, DrIceTea123 submitted a review, later dismissed
好快的改（）
那应该是没啥问题了

2023-01-20 15:55 UTC, ErrorPower2001 commented
> 好快的改（） 那应该是没啥问题了

##### 有邮件提醒嘛，你发了我就看见了，反正也在做整合包，手头也是闲着

2023-05-01 09:22 UTC, closed without merging