[R] 补全Geolosys的汉化
CFPAOrg/Minecraft-Mod-Language-Package pull request #2652
Opened 2022-12-02 00:40 UTC by MrZhang21626

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-12-02 14:22 UTC, Cactusstudent commented
请删除.vscode文件夹及其中所有文件

2022-12-03 12:09 UTC, dovisutu reviewed
补充一处点不上去的：
L2 一个（看起来是）矿物模组居然有杜鹃**花**......有点怀疑是不是指的别的。
就算不是，好像也有点和`azalea` -> `杜鹃花丛`撞车的嫌疑，是否要考虑改掉？

2022-12-03 12:09 UTC, dovisutu commented on projects/1.18/assets/geolosys/geolosys/lang/zh_cn.json
> +  "block.geolosys.nether_gold_ore": "贫瘠黄金",
按key而言，这个好像是`nether gold ore` -> `下界金矿石`的贫瘠变种？是否要把这一点放进去？
（当然，看实际情况；如果的确不太一致，或者真的是`poor gold`矿的话也不用改）

2022-12-03 12:09 UTC, dovisutu commented on projects/1.18/assets/geolosys/geolosys/lang/zh_cn.json
> +  "block.geolosys.deepslate_malachite_ore": "深板岩孔雀石",
这些条目是否要加`矿`？
（孔雀石确实可以算是矿物......只不过说金伯利岩是矿物好像就有点怪了？）

2022-12-03 12:09 UTC, dovisutu commented on projects/1.18/assets/geolosys/geolosys/lang/zh_cn.json
> +  "item.geolosys.zinc_nugget": "锌块",
`nugget` -> `粒`

2022-12-03 12:09 UTC, dovisutu commented on projects/1.18/assets/geolosys/geolosys/lang/zh_cn.json
> +  "geolosys.pro_pick.tooltip.found": "你找到了 %s 在你的 %s 方向",
不知道第二个%s具体内容是什么.....
如果是[方向+距离]或者[方向]：
```suggestion
  "geolosys.pro_pick.tooltip.found": "在%2$s处发现%1$s",
```
如果是[距离]：
```suggestion
  "geolosys.pro_pick.tooltip.found": "在距你%2$s处发现%1$s",
```
应该是可以用`n$`标记来换顺序的。

2022-12-06 14:56 UTC, dovisutu commented on projects/1.18/assets/geolosys/geolosys/lang/zh_cn.json
> +  "block.geolosys.lapis_ore": "青金岩",
**Un**resolved. 要么给出这里采用非原版译名的理由（如实质物品不同等），要么规范译名。

2022-12-18 13:52 UTC, dovisutu commented
- 7+7时限进入第二阶段。从该评论发出的时间开始计时。

ping @MrZhang21626

2022-12-21 15:20 UTC, dovisutu commented on projects/1.18/assets/geolosys/geolosys/lang/zh_cn.json
> +  "geolosys.download.error.string": "Geolosys无法找到或下载json-ore配置文件。您可以在此处下载该文件：https://raw.githubusercontent.com/oitsjustjose/Geolosys/1.14.x/geolosys_ores.json 如果需要，请手动将其放入config文件夹中（需要将其重命名为“geolosys
```suggestion
  "geolosys.download.error.string": "Geolosys无法找到或下载geolosys.json矿物配置文件。您可以在此处下载该文件：https://raw.githubusercontent.com/oitsjustjose/Geolosys/1.14.x/geolosys_ores.json；如果需要，请手动将其放入config文件夹中（需要将其重命名为“geolosys.json”）."
```

2022-12-21 15:22 UTC, dovisutu commented
> 在一般情况下，面对询问，选择将其静默并不是一个好的选择，进行恰当的解释才是。

如果我的记忆没有出现偏差的话，在上面的审核中有一条我多次接触resolve状态，结果等到想起来的时候又被resolve了，且没有做出任何解释。

诚然，这个世界上有无法解答的问题，但我想这个不是。

-------

当然，也许这里出了一点误会；比如出于某种原因，我在里面追加的问题并没有被看到；如果是这样的话，解释一下就好。不过，至少现在应该看得到那一条了吧。

-------

顺便又发了一条审核意见。大概这个是可以看到的吧。

2023-01-23 18:40 UTC, mamaruo commented on projects/1.18/assets/geolosys/geolosys/lang/zh_cn.json
> +  "block.geolosys.lapis_ore": "青金岩",
https://www.mcmod.cn/item/157452.html 可以认为是不同的

2023-01-23 18:42 UTC, mamaruo commented
惜字如金呐，烦请回复审查者提出的问题……不然审核真的没法进行下去

2023-06-27 00:25 UTC, luoxueyasha requested changes

2023-06-27 00:25 UTC, luoxueyasha commented on projects/1.18/assets/geolosys/geolosys/lang/zh_cn.json
> +  "block.geolosys.nether_gold_ore_sample": "贫瘠金矿样本",
此处与L26的`Poor Gold`的关系？若无差别的话请前后文统一

2023-07-30 10:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2652) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2652) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2652) it.</sub>

2023-08-05 07:16 UTC, Cactusstudent commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

@MrZhang21626

2023-08-05 09:52 UTC, mamaruo commented
> - [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。
> 
> @MrZhang21626 

标签打迷糊了？

2023-08-05 10:10 UTC, Cactusstudent commented
> 标签打迷糊了？

改了，我的问题

2023-08-11 02:13 UTC, Cactusstudent commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@MrZhang21626

2023-08-19 21:03 UTC, closed without merging