Empatic
CFPAOrg/Minecraft-Mod-Language-Package pull request #2665
Opened 2022-12-05 08:48 UTC by 3453890470

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2022-12-08 11:03 UTC, ChuijkYahus commented
> * 为何为`draft`状态？是模组翻译尚未完工，还是其他原因？

貌似用dev开默认是draft（之前开一次是这样，就是不知道是不是默认）

2022-12-08 14:43 UTC, 3453890470 commented
忘记改了，回头改一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月8日(周四) 晚上7:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CFPAOrg/Minecraft-Mod-Language-Package] EmpaTiC 翻译提交 (PR #2665)




   
为何为draft状态？是模组翻译尚未完工，还是其他原因？
   
貌似用dev开默认是draft（之前开一次是这样，就是不知道是不是默认）
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2022-12-10 12:31 UTC, ChuijkYahus reviewed
看得不深入

2022-12-10 12:31 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "fluid.empatic.molten_ironwood": "熔融铁树",
```suggestion
  "fluid.empatic.molten_ironwood": "熔融铁木",
```

2022-12-10 12:31 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "fluid.empatic.fiery_essence": "熔融三化螟精华",
```suggestion
  "fluid.empatic.fiery_essence": "炽热精华",
```
来自暮色官方语言文件

2022-12-10 12:31 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "item.empatic.ironwood_bucket": "熔融铁树",
```suggestion
  "item.empatic.ironwood_bucket": "熔融铁木桶",
```

2022-12-10 12:31 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "item.empatic.steeleaf_bucket": "熔融钢叶",
```suggestion
  "item.empatic.steeleaf_bucket": "熔融钢叶桶",
```

2022-12-10 12:31 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "item.empatic.fiery_essence_bucket": "熔融三化螟精华桶",
```suggestion
  "item.empatic.fiery_essence_bucket": "炽热精华桶",
```

2022-12-10 12:31 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.manasteel.flavor": "钢，粘液钢，魔力钢-你说出来我们就知道了。",
```suggestion
  "material.empatic.manasteel.flavor": "钢，黏钢，魔力钢——随便报，全能拿出来",
```

2022-12-10 12:31 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.elementium.flavor": "源自阿尔夫海姆的纪念品！精灵贸易专属。",
```suggestion
  "material.empatic.elementium.flavor": "源自亚尔夫海姆的纪念品！精灵贸易专属",
```

2022-12-10 12:31 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.terrasteel.flavor": "纯魔法的最高值",
```suggestion
  "material.empatic.terrasteel.flavor": "纯净魔力的最完美形态",
```

2022-12-10 12:31 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.ironwood": "铁树",
```suggestion
  "material.empatic.ironwood": "铁木",
```

2022-12-10 12:31 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.steeleaf.flavor": "玫瑰金一些竞争！",
```suggestion
  "material.empatic.steeleaf.flavor": "玫瑰金的竞争对手！",
```

2022-12-10 12:31 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.knightmetal.flavor": "普通金属没有骑士精神。",
```suggestion
  "material.empatic.knightmetal.flavor": "普通金属没有骑士精神",
```

2022-12-10 12:31 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.fiery.flavor": "火的化身。",
```suggestion
  "material.empatic.fiery.flavor": "火的化身",
```

2022-12-10 12:31 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.froststeel.flavor": "心爱的tomboish钢",
```suggestion
  "material.empatic.froststeel.flavor": "心爱的顽皮钢",
```
疑似tomboyish

2022-12-10 12:31 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.concrete.flavor": "可能是最便宜的2级材料，除了血骨",
```suggestion
  "material.empatic.concrete.flavor": "可能是最便宜的2级材料，除了血之骨",
```

2022-12-10 12:31 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.treatedwood.flavor": "杂酚油不仅是一种很好的燃料。",
```suggestion
  "material.empatic.treatedwood.flavor": "杂酚油不只是一种很好的燃料",
```

2022-12-10 12:31 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.manaadept": "法力专家",
```suggestion
  "modifier.empatic.manaadept": "魔力专家",
```
Mana，植物魔法术语

2022-12-10 12:31 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.manainfused.flavor": "驾驭法力之力。",
```suggestion
  "modifier.empatic.manainfused.flavor": "驾驭魔力",
```

2022-12-10 12:31 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.rotkiller": "腐烂者",
```suggestion
  "modifier.empatic.rotkiller": "腐衰杀手",
```

2022-12-10 12:31 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.ascending": "上升的",
```suggestion
  "modifier.empatic.ascending": "升空",
```

2022-12-10 12:31 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.voidcalling.flavor": "结束",
```suggestion
  "modifier.empatic.voidcalling.flavor": "末影之献",
```

2022-12-10 12:31 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.thin.flavor": "而不是粘液",
```suggestion
  "modifier.empatic.thin": "细薄",
  "modifier.empatic.thin.flavor": "苗条，但不消瘦",
```

2022-12-10 12:31 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.graphite": "高定向热解石墨锭",
```suggestion
  "material.empatic.graphite": "高定向热解石墨",
```

2022-12-11 00:45 UTC, Cactusstudent reviewed
大概看了下，可能还有没看到的

2022-12-11 00:45 UTC, Cactusstudent commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.caramelcomposite.encyclopedia": "每级+25%机会在日光下再生粘液覆层，并增加其少量上限",
```suggestion
  "material.empatic.caramelcomposite.encyclopedia": "每级+25%机会在日光下再生黏液覆层，并增加其少量上限",

```

2022-12-11 00:45 UTC, Cactusstudent commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.caramelcomposite.encyclopedia": "每级+25%机会在日光下再生粘液覆层，并增加其少量上限",
后半句有点怪，看着改吧。~~（其实本体的汉化也有很多这种问题）~~

2022-12-11 00:45 UTC, Cactusstudent commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.hauntedbrass.encyclopedia": "每级+10.5%攻击速度，每级在命中实体时10%概率你获得虚弱3~6秒。",
```suggestion
  "material.empatic.hauntedbrass.encyclopedia": "每级+10.5%攻击速度，每级在命中实体时10%概率你获得3~6秒的虚弱。",

```

2022-12-11 00:45 UTC, Cactusstudent commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.frail.description": "以牺牲一些耐久增加采掘速度",
```suggestion
  "modifier.empatic.frail.description": "牺牲一些耐久以增加采掘速度",

```

2022-12-11 00:45 UTC, Cactusstudent commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.unreliable.description": "消耗随机耐久度，范围0~3，平均消耗更少耐久。",
这里的语序很奇怪，推荐再捯饬一下。（如果不改其实也无伤大雅）
原文：Consumes random durability, ranging from 0 to 3. Consumes less durability on average

2022-12-11 00:45 UTC, Cactusstudent commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.gloomy.description": "对所有与地下城生物无关的东西的额外采矿速度和攻击伤害",
```suggestion
  "modifier.empatic.gloomy.description": "对所有与地下城生物无关的东西的额外采掘速度和攻击伤害",

```

2022-12-11 00:45 UTC, Cactusstudent commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.overlight.description": "暴露在阳光下会重新产生粘液覆层",
```suggestion
  "modifier.empatic.overlight.description": "暴露在阳光下会重新产生黏液覆层",

```

2022-12-12 17:26 UTC, ChuijkYahus reviewed
末尾标点和读起来感觉不那么顺的地方全部没改
不过这些也都不重要

2022-12-12 17:26 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.manasteel.encyclopedia": "给予魔力专家 Ⅱ而非魔力专家 Ⅰ，用魔力修复时降低魔力消耗。",
```suggestion
  "material.empatic.manasteel.encyclopedia": "给予魔力专家 II而非魔力专家 I，用魔力修复时降低魔力消耗。",
```
倒是不需要用Unicode里的罗马数字

2022-12-12 17:26 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.elementium.encyclopedia": "工具有25%的几率召唤小精灵，小精灵造成2+等级/2伤害",
```suggestion
  "material.empatic.elementium.encyclopedia": "工具有25%的几率召唤小精灵，小精灵造成（2+等级/2）点伤害。",
```
公式括号就暂时放个全角在这里吧

2022-12-12 17:26 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.falsite.encyclopedia": "（70+5*等级）%几率不消耗耐久，否则消耗3倍耐久",
```suggestion
  "material.empatic.horizonite.encyclopedia": "每次命中实体会使其获得燃烧3~7秒",
  "material.empatic.falsite": "缪铁",
  "material.empatic.falsite.flavor": "我找到你了，骗子！",
  "material.empatic.falsite.encyclopedia": "（70+5*等级）%几率不消耗耐久度，否则消耗3倍耐久度。",
```

2022-12-12 17:26 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.refinedradiance.flavor": "到天空，甚至更远。",
怀疑这里其实是在指Above and Beyond（机械动力官方整合包）

2022-12-12 17:26 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.shadowsteel.encyclopedia": "在足够暗的地方每级有20%概率不消耗耐久。",
```suggestion
  "material.empatic.shadowsteel.encyclopedia": "在足够暗的地方每级有20%概率不消耗耐久度。",
```

2022-12-12 17:26 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.forestenergy.description": "砍树叶增加",
未翻译全

2022-12-12 17:26 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.fiery2.description": "攻击随机敌人敌人一段时间。",
这是啥

2022-12-12 17:26 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.manainfused.description": "使用法力提高攻击力和采掘速度。",
```suggestion
  "modifier.empatic.manainfused.description": "使用魔力提高攻击力和采掘速度。",
```
推荐再找找有没有`法力`

2022-12-14 11:35 UTC, Rinko1231 requested changes

2022-12-14 11:35 UTC, Rinko1231 commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.froststeel.flavor": "心爱的顽皮钢",
此处原文nete的东方Project中琪露诺的主题曲《おてんば恋娘》（Beloved Tomboyish Girl），即《活泼的纯情小姑娘》，建议为`活泼的纯情小钢铁`。

2022-12-14 11:38 UTC, Rinko1231 commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.fiery2.flavor": "永不熄灭！",
```suggestion
  "modifier.empatic.fiery2.flavor": 薪炎永燃！",
```

2022-12-21 15:01 UTC, dovisutu commented
流程还是要走一下的

- 7+7时限进入第一阶段。从该评论发出的时间开始计时。

ping @3453890470

2022-12-28 03:11 UTC, 3453890470 commented
.

2023-01-07 03:57 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.milkonstantan.encyclopedia": "当完全受到负面效果的影响时，每级+12.5%的采掘速度（当拥有正面效果时取消该特性）",
```suggestion
  "material.empatic.milkonstantan.encyclopedia": "受到负面效果的影响时，每级+12.5%采掘速度（当拥有正面效果时取消该特性）。",
```

2023-01-07 03:57 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.terrasteel.encyclopedia": "消耗法力使攻击伤害+1，采掘速度+2.5。等级越高魔力消耗越低",
```suggestion
  "material.empatic.terrasteel.encyclopedia": "消耗魔力使攻击伤害+1，采掘速度+2.5。等级越高魔力消耗越低。",
```

2023-01-07 03:57 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.ventium.encyclopedia": "每级-8%耐久度和+12%的采掘速度。",
```suggestion
  "material.empatic.ventium.encyclopedia": "每级-8%耐久度和+12%采掘速度。",
```

2023-01-07 03:57 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.falsite.encyclopedia": "（70+5*等级）%几率不消耗耐久度，否则消耗3倍耐久度",
```suggestion
  "material.empatic.horizonite.encyclopedia": "每次命中实体会使其获得燃烧3~7秒。",
  "material.empatic.falsite": "缪铁",
  "material.empatic.falsite.flavor": "我找到你了，骗子！",
  "material.empatic.falsite.encyclopedia": "（70+5*等级）%概率不消耗耐久度，其余情况消耗3倍耐久度。",
```

2023-01-07 03:57 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.fiery.encyclopedia": "以炽热为基础，每级使被命中的实体获得5秒燃烧",
```suggestion
  "material.empatic.fiery.encyclopedia": "以炽热为基础，每级使被命中的实体获得5秒燃烧。",
```

2023-01-07 03:57 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.utherium.encyclopedia": "攻击腐衰生物时造成伤害+25%",
```suggestion
  "material.empatic.cloggrum.encyclopedia": "每级+15%的采掘速度，比平时快了100%。",
  "material.empatic.utherium": "御腐",
  "material.empatic.utherium.flavor": "御腐，卸腐，卸府……",
  "material.empatic.utherium.encyclopedia": "攻击腐衰生物时造成伤害+25%。",
```

2023-01-07 03:57 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.forgotten.flavor": "重新发现，重建，复仇。",
```suggestion
  "material.empatic.forgotten.flavor": "重新发现，重建，复仇",
```

2023-01-07 03:57 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.forgotten.encyclopedia": "对非BOSS深园生物造成的伤害+33%，每级对深园的方块+33%的采掘速度",
```suggestion
  "material.empatic.forgotten.encyclopedia": "对非BOSS深园生物造成的伤害+33%，每级对深园方块+33%采掘速度。",
```

2023-01-07 03:57 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.graphite.encyclopedia": "在奔跑时累计能量，每级每点能量+9%攻击伤害，最多存储30点能量",
```suggestion
  "material.empatic.concrete.encyclopedia": "每级在每第6次命中实体造成伤害+3。",
  "material.empatic.graphite": "高定向热解石墨",
  "material.empatic.graphite.flavor": "煤炭工具！……大概是吧",
  "material.empatic.graphite.encyclopedia": "在奔跑时累计能量，每级每点能量+9%攻击伤害，最多存储30点能量。",
```

2023-01-07 03:57 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.caramelcomposite.encyclopedia": "每级+25%机会在日光下再生黏液覆层，并增加其少量上限",
```suggestion
  "material.empatic.caramelcomposite.encyclopedia": "每级+25%机会在日光下再生黏液覆层，并增加其少量上限。",
```

2023-01-07 03:57 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.refinedradiance.flavor": "到天空，甚至更远。",
```suggestion
  "material.empatic.refinedradiance.flavor": "到天空，甚至更远",
```

2023-01-07 03:57 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "material.empatic.shadowsteel.flavor": "哇！边缘。",
```suggestion
  "material.empatic.shadowsteel.flavor": "哇！边缘",
```

2023-01-07 03:57 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.unreliable.description": "随机消耗0~3点耐久度，平均消耗减少",
```suggestion
  "modifier.empatic.unreliable.description": "每次使用随机消耗0~3点耐久度，平均消耗减少",
```

2023-01-07 03:57 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.manainfused.description": "使用法力提高攻击力和采掘速度。",
这里别忘了

2023-01-07 03:57 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.underborn.description": "目标在这个世界上的位置越低，对其造成伤害越高。",
```suggestion
  "modifier.empatic.arid.description": "对沙子和砂岩有额外采掘速度",
  "modifier.empatic.clearing": "清除",
  "modifier.empatic.clearing.flavor": "负面影响吸收。",
  "modifier.empatic.clearing.description": "只有在负面效果影响的状态下，获得额外采掘速度",
  "modifier.empatic.underborn": "地心引力",
  "modifier.empatic.underborn.flavor": "来自虚空的力量",
  "modifier.empatic.underborn.description": "目标在这个世界上的位置越低，对其造成伤害越高",
```

2023-01-07 03:57 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.pixie.description": "可能会在命中时召唤一个小精灵，小精灵会帮你攻击你的敌人。",
```suggestion
  "modifier.empatic.pixie.description": "可能会在命中时召唤一个小精灵，小精灵会帮你攻击你的敌人",
```

2023-01-07 03:57 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.fiery2.description": "攻击使敌人随机燃烧一段时间。",
```suggestion
  "modifier.empatic.fiery2.description": "攻击使敌人随机燃烧一段时间",
```

2023-01-07 03:57 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.forestknockback.description": "消耗森林能量增加额外击退。",
```suggestion
  "modifier.empatic.forestknockback.description": "消耗森林能量增加额外击退",
```

2023-01-07 03:57 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.rotkiller.description": "对腐衰生物造成额外伤害。",
```suggestion
  "modifier.empatic.rotkiller.description": "对腐衰生物造成额外伤害",
```

2023-01-07 03:57 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.tornapart.description": "每攻击5次，第6次会造成额外伤害。",
```suggestion
  "modifier.empatic.tornapart.description": "每攻击5次，第6次会造成额外伤害",
```

2023-01-07 03:57 UTC, ChuijkYahus commented on projects/1.18/assets/empatic/empatic/lang/zh_cn.json
> +  "modifier.empatic.dynamic.description": "使用累积速度获得额外的采掘速度。在移动中积累",
```suggestion
  "modifier.empatic.dynamic.description": "使用累积速度获得额外的采掘速度，移动时进行累积",
```

2023-07-30 10:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2665) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2665) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Cactusstudent<br/>:x: 3453890470<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2665) it.</sub>

2023-08-14 02:54 UTC, Cactusstudent requested changes
根据匠魂3的翻译，对于`每级+10%攻击伤害`这类的翻译应当统一为`每级攻击伤害+10%`

2023-09-01 02:17 UTC, closed without merging