Every Compat 累积更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #2705
Opened 2022-12-16 14:51 UTC by ChuijkYahus

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

S P E E D

2022-12-16 15:31 UTC, Ricky-fight requested changes

2022-12-16 15:39 UTC, ChuijkYahus commented on projects/1.18/assets/every-compat/everycomp/lang/zh_cn.json
> +  "leaves_type.terrestria.dark_japanese_maple": "日本红枫",
@Ricky-fight 话说这里后来改了吗

2022-12-16 15:40 UTC, Ricky-fight commented on projects/1.18/assets/every-compat/everycomp/lang/zh_cn.json
> +  "leaves_type.terrestria.dark_japanese_maple": "日本红枫",
我这统一都改了

2022-12-16 15:48 UTC, ChuijkYahus commented on projects/1.18/assets/every-compat/everycomp/lang/zh_cn.json
> +  "leaves_type.terrestria.dark_japanese_maple": "日本红枫",
是统一叫日本红枫了吗
这两者的原文有区别的话还是应该区分一下

2022-12-16 15:54 UTC, Ricky-fight commented on projects/1.18/assets/every-compat/everycomp/lang/zh_cn.json
> +  "leaves_type.terrestria.dark_japanese_maple": "日本红枫",
统一为日本红枫了。
在Terrestria里目前只有这一种日本枫树。

2022-12-16 16:32 UTC, ChuijkYahus commented on projects/1.18/assets/every-compat/everycomp/lang/zh_cn.json
> +  "leaves_type.terrestria.dark_japanese_maple": "日本红枫",
不过我觉得这块可能`暗色日本红枫`会好一点
原文也有`dark`在
而且下一行的灌木有改过吗

2022-12-17 11:49 UTC, Ricky-fight commented on projects/1.18/assets/every-compat/everycomp/lang/zh_cn.json
> +  "leaves_type.terrestria.japanese_maple_shrub": "日本枫木灌木",
```suggestion
  "leaves_type.terrestria.japanese_maple_shrub": "日本红枫灌木",
```

2022-12-17 11:49 UTC, Ricky-fight commented on projects/1.18/assets/every-compat/everycomp/lang/zh_cn.json
> +  "leaves_type.terrestria.dark_japanese_maple": "日本红枫",
```suggestion
  "leaves_type.terrestria.dark_japanese_maple": "暗色日本红枫",
```
那就按你的来吧。我想的是深色，但是怕深色有“深色橡树”的误导向。暗色也许确实好一点？

2022-12-17 11:56 UTC, Ricky-fight commented
已同步修改至#2704

2022-12-17 12:52 UTC, dovisutu approved these changes

2022-12-22 14:55 UTC, dovisutu approved these changes
后继更改应该也没有问题

2022-12-22 15:50 UTC, mamaruo approved these changes

2022-12-24 09:11 UTC, ChuijkYahus commented
当然这里需要说明的是1.18版本中兼容的木制品数量并没有这么多，也就是说部分木制品的键是多余的
不知道需不需要去掉

2022-12-31 06:38 UTC, dovisutu commented
> 不知道需不需要去掉

看情况吧 如果作者后续也不准备加这些兼容那可以删掉

2023-01-05 08:31 UTC, ChuijkYahus commented
> > 不知道需不需要去掉
> 
> 看情况吧 如果作者后续也不准备加这些兼容那可以删掉

确实也不准备加（目前来看是这样）
不过已经懒得删了（）

2023-01-05 09:31 UTC, merged