提交模组 fuze relics 翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #2711
Opened 2022-12-18 13:03 UTC by mangke01

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-12-18 13:06 UTC, mangke01 commented
坏了好像不小心多加了一个s

2022-12-19 05:24 UTC, mamaruo commented
由CurseForge可知本模组作者是法国人，由法语来翻译更准确。

2022-12-19 05:24 UTC, mamaruo commented
/mv-recursive "projects/1.18/assets/fuzes-relics/fuze-relics/" "projects/1.18/assets/fuzes-relics/fuze_relics/

2022-12-19 05:32 UTC, mamaruo commented
/sort-keys CFPAOrg/Minecraft-Mod-Language-Package/projects/1.18/assets/fuzes-relics/fuze_relics/lang/zh_cn.json
/sort-keys CFPAOrg/Minecraft-Mod-Language-Package/projects/1.18/assets/fuzes-relics/fuze_relics/lang/en_us.json

2022-12-19 05:34 UTC, mamaruo commented
/sort-keys projects/1.18/assets/fuzes-relics/fuze_relics/lang/zh_cn.json
/sort-keys projects/1.18/assets/fuzes-relics/fuze_relics/lang/en_us.json

2022-12-19 06:54 UTC, mangke01 commented
> 由CurseForge可知本模组作者是法国人，由法语来翻译更准确。

作者确实是法国人，但这个模组语言就是en_us。只有唱片名称和“Fuze qui chante”有法文。你指的是哪个地方要用法语翻译呢

2022-12-19 06:57 UTC, mamaruo requested changes
总体还不错，那几句法语属实看不懂

2022-12-19 06:57 UTC, mamaruo commented on projects/1.18/assets/fuzes-relics/fuze_relics/lang/zh_cn.json
> +  "item.fuze_relics.slide_boots": "滑靴",
| **审查级别**    | 备注 |
|--------------|----|
| ⚪ 轻微 / 不阻止合并但需三思  |    |
```suggestion
  "item.fuze_relics.slide_boots": "滑雪靴",
```
和下方的胸甲等一致
原文：**Slide Boots**

2022-12-19 06:57 UTC, mamaruo commented on projects/1.18/assets/fuzes-relics/fuze_relics/lang/zh_cn.json
> +  "subtitles.coffee_machine_sound": "咖啡机震耳欲聋的工作",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |
```suggestion
  "subtitles.coffee_machine_sound": "咖啡机震耳欲聋的工作声",
```
```suggestion
  "subtitles.coffee_machine_sound": "咖啡机：震耳欲聋",
```
原文：**coffee machine kill my ears**

2022-12-19 06:57 UTC, mamaruo commented on projects/1.18/assets/fuzes-relics/fuze_relics/lang/zh_cn.json
> +  "key.fuze_relics.special_ability": "特殊生物能力使用",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |
```suggestion
  "key.fuze_relics.special_ability": "特殊能力",
```
原文：**Special Ability**

2022-12-19 07:03 UTC, mangke01 reviewed
几处修改

2022-12-19 07:08 UTC, mangke01 commented
150行那个是把一张特定唱片放入唱片机时的那个声音的字幕，实在不懂，不知道是歌名还是什么

2022-12-19 16:29 UTC, mamaruo commented
没事了

> This comment was marked as outdated.

2022-12-21 14:58 UTC, dovisutu commented on projects/1.18/assets/fuzes-relics/fuze_relics/lang/zh_cn.json
> +  "subtitles.walkie_talkie_sound": "对讲机音效"
我还是感觉字幕条目有的格式对不上......有些是认为无主体了吗
比如那个coffee_macine_sound

至于那几个Fuze的...看Fuze是什么了，现在这种按照无主体处理也可以
主要问题是原版对唱片机的字幕是缺失的，也没有参照

2022-12-21 15:37 UTC, mangke01 commented on projects/1.18/assets/fuzes-relics/fuze_relics/lang/zh_cn.json
> +  "subtitles.walkie_talkie_sound": "对讲机音效"
是我搞错了，我还以为只有实体的声音才是……：……的形式，我又看看了原版，原来工作方块也是这样……我改一下

2022-12-21 15:46 UTC, mangke01 commented on projects/1.18/assets/fuzes-relics/fuze_relics/lang/zh_cn.json
> +  "subtitles.walkie_talkie_sound": "对讲机音效"
fuze是一个作者名吧，那个ninjaxx也是个人（youtuber）

> 我还是感觉字幕条目有的格式对不上......有些是认为无主体了吗 比如那个coffee_macine_sound
> 
> 至于那几个Fuze的...看Fuze是什么了，现在这种按照无主体处理也可以 主要问题是原版对唱片机的字幕是缺失的，也没有参照

fuze是一个作者名吧，那个ninjaxx也是个人（youtuber）

2022-12-21 15:54 UTC, dovisutu commented on projects/1.18/assets/fuzes-relics/fuze_relics/lang/zh_cn.json
> +  "subtitles.walkie_talkie_sound": "对讲机音效"
那行，这几个人名的就这样也可以

2022-12-21 17:39 UTC, mamaruo approved these changes

2022-12-28 04:12 UTC, merged