Zettai Psi汉化提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2728
Opened 2022-12-24 08:49 UTC by mczph

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-01-22 06:16 UTC, dovisutu commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +stat.psi_cast=施法（Psi）
这里的应该是统计次数
“Psi 施法次数”？

2023-01-22 06:16 UTC, dovisutu commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.operatorLimit=运算符：极限
这个概念感觉跟数学概念“极限”不太匹配？
感觉“界”的说法更合适？

2023-01-22 06:16 UTC, dovisutu commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.operatorVectorLimit.desc=如果矢量的值大于极限值，或者值小于负极限值，那么它将这个值设置为极限值/负极限值
矢量的“值”？  $\mathrm{R}^3$ 好像不是全序集？

2023-01-22 10:47 UTC, mczph commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.operatorLimit=运算符：极限
经群内商讨改为“限制”

2023-02-11 11:27 UTC, mczph commented
需要帮助（）

2023-05-09 07:55 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.operatorRangeLimit.desc=如果给定的数字大于/小于正/负限制值，则返回正/负限制值，否则返回数字
```suggestion
psi.spellpiece.operatorRangeLimit.desc=如果给定的数字大于正限制值或小于负限制值，则返回正/负限制值，否则返回数字
```

2023-05-09 07:55 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.operatorVectorLimit.desc=如果矢量的值大于限制值，或者值小于负限制值，那么它将这个值设置为限制值/负限制值
```suggestion
psi.spellpiece.operatorVectorLimit.desc=如果矢量的模大于正限制值或小于负限制值，则将其模设置为正/负限制值
```

2023-05-09 07:55 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.operatorFindPotion.desc=扫描实体以查找是否被给予了/应用了任何效果，如果是则返回1，否则返回0
```suggestion
psi.spellpiece.operatorFindPotion.desc=扫描实体以查找其是否拥有状态效果，如果是则返回1，否则返回0
```
原句确实没看懂

2023-05-09 07:55 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.trickMassMark.desc=在给定的时间内标记给定的大量实体（以秒为单位）
```suggestion
psi.spellpiece.trickMassMark=启动式：批量标记
psi.spellpiece.trickMassMark.desc=在给定的时间内标记给定的多个实体（以秒为单位）
```

2023-05-09 07:55 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.trickMassDetection.desc=如果可能的话，解除指定大量实体的隐身状态
```suggestion
psi.spellpiece.trickMassDetection=启动式：批量探测
psi.spellpiece.trickMassDetection.desc=如果可能的话，解除指定多个实体的隐身状态
```

2023-05-09 07:55 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.trickMagicAttack.desc=用纯正的Psi能量攻击实体
```suggestion
psi.spellpiece.trickMagicAttack.desc=用纯粹的Psi能量攻击实体
```

2023-05-09 07:55 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.trickSatiety.desc=如果可能的话，让目标身体得到饱食，但同时也会增加负面效果
```suggestion
psi.spellpiece.trickSatiety.desc=如果可能的话，给予目标一定饥饿值，但同时也会增加负面效果
```
这个是饱和效果？

2023-05-09 07:55 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.trickNegateFall.desc=否定目标下风盘的坠落伤害，但只在应用时
```suggestion
psi.spellpiece.trickNegateFall.desc=以旋风盘取消目标的坠落伤害，但只在应用时生效
```

2023-05-12 14:56 UTC, mczph commented
@ChuijkYahus 已处理完毕（）

2023-05-12 16:09 UTC, ChuijkYahus reviewed
这作者英语怪怪的

2023-05-12 16:09 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.trickLogComment.desc=将你所做术式评论的信息发送给你，或目标的大脑
```suggestion
psi.spellpiece.trickLogComment.desc=将你所做术式评论的信息发送给你的或你目标的大脑
```

2023-05-12 16:09 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +zettai_psi.spellerror.no_comment=错误：术式中没有评论!
```suggestion
zettai_psi.spellerror.no_comment=错误：术式中没有评论！
```

2023-05-12 16:09 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +zettai_psi.spellparam.undead=不死
```suggestion
zettai_psi.spellparam.undead=亡灵生物
```

2023-05-12 16:09 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.piecegroup.alchemy_code.desc=通过手动控制应用效果的魔力路径，我们可以用几乎所有可能的东西来影响实体！<br><br>但是，魔力路径不能是负的，它不能处理不同的值，而且在某些时候它的值会结束。<br><br>用这种方法产生的效果不能有高于2的强度，它们只是不减损而已！
```suggestion
psi.piecegroup.alchemy_code.desc=手动控制效果的魔力路径，就几乎能用任何事物影响实体！<br><br>但是，魔力路径不能是负的，它不能处理不同的值，而且在某些时候它的值会结束。<br><br>用这种方法产生的效果不能有高于2的强度，它们只是不减损而已！
```
怪怪的

2023-05-12 16:09 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.piecegroup.alchemy_code=炼金术守则
```suggestion
psi.piecegroup.alchemy_code=炼金编码
```

2023-05-12 16:09 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.piecegroup.elemental_arts_two.desc=你可以以不同的方式使用Psi整合产生的元素能量<br><br>你可以用启动式：魔法攻击来试试，它用魔法伤害实体，但是，在此基础上应用了修改：<br>1）目标生命值。<br>2）目标是亡灵吗？<br>3）实体看到你了吗？<br><br>其他元素攻击也有不同的效果和小东西，你只能通过实验来发现！
```suggestion
psi.piecegroup.elemental_arts_two.desc=你可以以不同的方式使用Psi整合产生的元素能量<br><br>可以用启动式：魔法攻击来试试，它会用魔法伤害实体。但是，它会受若干事物调整：<br>1）目标生命值。<br>2）目标是亡灵吗？<br>3）实体看到你了吗？<br><br>其他元素攻击也有不同的效果和细微差别，只能通过实验发现！
```

2023-05-12 16:09 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.piecegroup.teleportation.desc=真实和困难的艺术——传送…… 通过使用Psi创造魔力护盾，并转换目标周围的空间，我们可以准确地传送到我们想去的地方。有了它，我们就不会像闪现那样被自己的视野所限制
```suggestion
psi.piecegroup.teleportation=传送
psi.piecegroup.teleportation.desc=纯正又困难的魔法艺术——传送……使用 Psi 创造魔力护盾，并转换目标周围的空间，我们可以准确地传送到我们想去的地方。由此就不会像闪现那样被自己的视野所限制了。
```

2023-05-12 17:26 UTC, ChuijkYahus commented
修正，Conjure应该翻译成构筑

2023-05-13 04:43 UTC, mczph commented
已将所有Conjure翻译为构筑（但是会不会有点怪）

2023-05-13 04:45 UTC, ChuijkYahus commented
感觉就只有构筑粒子合适点（）

2023-05-13 04:52 UTC, mczph commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.trickRangedNotEqual.desc=检查数是否在布尔值的数值范围内，如果不是则停止施法！（如果数没有被定义则等于最小值）
那个最小值我没搞懂（）

2023-05-13 05:03 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.trickRangedNotEqual.desc=检查数是否在布尔值的数值范围内，如果不是则停止施法！（如果数没有被定义则等于最小值）
实际测试效果如何

2023-05-13 07:51 UTC, mczph commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.trickRangedNotEqual.desc=检查数是否在布尔值的数值范围内，如果不是则停止施法！（如果数没有被定义则等于最小值）
我等一下开游戏测试一下

2023-05-14 03:07 UTC, mczph commented
研究了一下，大概是这样的：
这个块的配置
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/103164772/634dc8f9-cd49-42d5-9df0-2c6b724a173b)
最下面那个停止循环似乎没什么用（毕竟是可选，难道是展示用，或者是我没测试出来？）
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/103164772/f759abf3-cac8-491a-aa7b-824f66980ad7)
1,2,3,4,5,6,7,8,9执行，10不执行
测试了一下是向下可以去等向上不行，小数支持不知道
总之它英文的描述就有点问题

2023-05-16 04:43 UTC, ChuijkYahus commented
> 研究了一下，逆向范围相等大概是这样的： 这个块的配置 ![image](https://user-images.githubusercontent.com/103164772/238165153-634dc8f9-cd49-42d5-9df0-2c6b724a173b.png) 最下面那个停止循环似乎没什么用（毕竟是可选，难道是展示用，或者是我没测试出来？） ![image](https://user-images.githubusercontent.com/103164772/238165174-f759abf3-cac8-491a-aa7b-824f66980ad7.png) 1,2,3,4,5,6,7,8,9执行，10不执行，而范围相等就刚好反过来 测试了一下是向下可以去等向上不行，小数支持不知道 总之它英文的描述就有点问题

那这里尽量改得和实际像一点吧（）
这个停止循环可以设点最大最小范围内和范围外的数，也许有用（）

2023-05-16 04:48 UTC, ChuijkYahus reviewed
之后记得加全半角空格

作者的英语总体都怪怪的，看能不能稍微改通顺一点吧

2023-05-16 04:48 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.operatorInvertBoolean.desc=如果数字小于0，则返回1，如果数字大于0，也返回1（数字为0时返回0）
```suggestion
psi.spellpiece.operatorInvertBoolean.desc=如果数字小于 0，则返回 1，如果数字大于 0，也返回 1（数字为 0 时返回 0）
```

2023-05-16 04:48 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.operatorFindPotion.desc=扫描实体，如果其有状态效果则返回1，否则返回0
```suggestion
psi.spellpiece.operatorFindPotion.desc=扫描实体，如果其有状态效果则返回 1，否则返回 0
```

2023-05-16 04:48 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.trickApplyPotion.desc=对给定的实体施加效果，但成本加倍，效果的强度不稳定，且不能大于2
```suggestion
psi.spellpiece.trickApplyPotion.desc=对给定的实体施加效果，但成本加倍，效果的强度不稳定，且不能大于 2
```

2023-05-16 04:48 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.trickSwitchWandMode.desc=如果布尔值为1（默认为1），则通过添加+1来切换施法模式，最多可达到最大值
```suggestion
psi.spellpiece.trickSwitchWandMode.desc=如果布尔值为 1（默认为 1），则通过添加 +1 来切换施法模式，最多可达到最大值
```

2023-05-16 04:48 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.trickStopLoopcast.desc=如果值在0和1的范围内，或者在给定值的范围内（从负值到值），则停止循环
```suggestion
psi.spellpiece.trickStopLoopcast.desc=如果数值在 0 和 1 的范围内，或者在给定值的范围内（负值与正值之间），则停止循环
```

2023-05-16 04:48 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.trickBreakArmor.desc=使魔法盔甲破裂，因此魔法护盾有几率将被打破，几率：10%+（强度*2）
```suggestion
psi.spellpiece.trickBreakArmor.desc=使魔法盔甲破裂，因此魔法护盾有几率将被打破，几率：10%+（强度 * 2）
```

2023-05-16 04:48 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.piecegroup.elemental_arts_two.desc=你可以以不同的方式使用Psi整合产生的元素能量<br><br>可以用启动式：魔法攻击来试试，它会用魔法伤害实体。但是，它会受若干事物调整：<br>1）目标生命值。<br>2）目标是亡灵吗？<br>3）实体看到你了吗？<br><br>其他元素攻击也有不同的效果和细微差别，只能通过实验发现！
```suggestion
psi.piecegroup.elemental_arts_two.desc=你可以以不同的方式使用 Psi 整合产生的元素能量<br><br>可以用启动式：魔法攻击来试试，它会用魔法伤害实体。但是，它会受若干事物调整：<br>1）目标生命值。<br>2）目标是亡灵吗？<br>3）实体看到你了吗？<br><br>其他元素攻击也有不同的效果和细微差别，只能通过实验发现！
```

2023-05-16 04:48 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.piecegroup.alchemy_code.desc=手动控制效果的魔力路径，就几乎能用任何事物影响实体！<br><br>但是，魔力路径不能是负的，它不能处理不同的值，而且在某些时候它的值会结束。<br><br>用这种方法产生的效果不能有高于2的强度，它们只是不减损而已！
```suggestion
psi.piecegroup.alchemy_code.desc=手动控制效果的魔力路径，就几乎能用任何事物影响实体！<br><br>但是，魔力路径不能是负的，它不能处理不同的值，而且在某些时候它的值会结束。<br><br>用这种方法产生的效果的强度不能高于 2，它们只是不减损而已！
```

2023-06-28 11:05 UTC, luoxueyasha commented
作者母语是俄语（见[作者的Twitch](https://www.twitch.tv/zettasword/about)），但是翻了一圈没有俄语语言文件……
要不要打上俄语tag？

2023-06-28 13:25 UTC, ChuijkYahus commented
> 作者母语是俄语（见[作者的Twitch](https://www.twitch.tv/zettasword/about)），但是翻了一圈没有俄语语言文件…… 要不要打上俄语tag？

没有俄语文件还是算了
也难怪这个英文文件比较难搞

2023-07-30 10:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2728) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2728) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2728) it.</sub>

2023-08-14 13:28 UTC, dovisutu reviewed
我在想，我们是否需要帮模组作者**润色**......
下面的有些条目是基于这个想法的，如果认为不妥，那就算了。

~妈呀，看着脑袋疼~

2023-08-14 13:28 UTC, dovisutu commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.operatorLimit.desc=如果给定的数字大于限制值，则返回限制值，否则返回数字
考量：微调方案
如果觉得不合适就算了
```suggestion
psi.spellpiece.operatorLimit=运算符：上截断
psi.spellpiece.operatorLimit.desc=如果传入的数字大于限制值，则返回限制值，否则返回该数
```
不知道psi里有没有“传递”参数的说法

2023-08-14 13:28 UTC, dovisutu commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.operatorInvertBoolean.desc=如果数字小于 0，则返回 1，如果数字大于 0，也返回 1（数字为 0 时返回 0）
感觉还是太啰嗦了，虽然是原文如此...

2023-08-14 13:28 UTC, dovisutu commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.trickNotEqual=启动式：逆向相等
```suggestion
psi.spellpiece.trickNotEqual=启动式：不等
```

2023-11-23 15:50 UTC, ChuijkYahus commented
这个PR放好久了……
明天再进游戏看一遍吧

作者原文如果稍加修改能看得懂的就不动了

2023-11-24 04:45 UTC, ChuijkYahus requested changes

2023-11-24 04:45 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.operatorInvertBoolean.desc=如果数字小于 0，则返回 1，如果数字大于 0，也返回 1（数字为 0 时返回 0）
这作者的描述不对

$$\begin{cases}
1,&x=0\\\\0,&x\neq0
\end{cases}$$

这个才对

2023-11-24 04:45 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +potion.zettai_psi:magic_shielding.desc=阻止一些试图传送的行为，并减少魔法伤害
```suggestion
potion.zettai_psi:magic_shielding.desc=阻止某些试图传送的行为，并减少受到的魔法伤害
```

2023-11-24 04:45 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.selectorVectorUp=选择符：矢量向上
```suggestion
psi.spellpiece.selectorVectorUp=选择符：上方向矢量
```

2023-11-24 04:45 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.selectorVectorDown=选择符：矢量向下
```suggestion
psi.spellpiece.selectorVectorDown=选择符：下方向矢量
```

2023-11-24 04:45 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.spellpiece.operatorRangeLimit.desc=如果给定的数字大于正限制值或小于负限制值，则返回正/负限制值，否则返回数字
```suggestion
psi.spellpiece.operatorRangeLimit.desc=如果给定的数字大于正限制值或小于负限制值，则返回正/负限制值，否则返回该数
```

2023-11-24 04:45 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.piecegroup.undead.desc=通过用Psi影响亡灵生物，我们可以操纵它们。<br><br>使用亡灵运动控制将它们中的一个移动到你想要的地方。<br><br>也可以使用腐肉将僵尸变出来，但它仍然只是僵尸，不是你的奴仆。<br><br>使用选择符：附近亡灵，你可以快速找到区域内的所有亡灵。
```suggestion
psi.piecegroup.undead.desc=用Psi影响亡灵生物就可以操纵它们。<br><br>使用亡灵运动控制将它们中的一个移动到你想要的地方。<br><br>也可以使用腐肉将僵尸变出来，但它仍然只是僵尸，不是你的奴仆。<br><br>使用选择符：附近亡灵就可以快速找到区域内的所有亡灵。
```

2023-11-24 04:45 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.piecegroup.elemental_arts_two=元素艺术2
```suggestion
psi.piecegroup.elemental_arts_two=元素艺术 2
```

2023-11-24 04:45 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.piecegroup.elemental_arts_two.desc=你可以以不同的方式使用 Psi 整合产生的元素能量<br><br>可以用启动式：魔法攻击来试试，它会用魔法伤害实体。但是，它会受若干事物调整：<br>1）目标生命值。<br>2）目标是亡灵吗？<br>3）实体看到你了吗？<br><br>其他元素攻击也有不同的效果和细微差别，只能通过实验发现！
```suggestion
psi.piecegroup.elemental_arts_two.desc=你可以以不同的方式使用 Psi 整合产生的元素能量<br><br>可以用启动式：魔法攻击来试试，它会用魔法伤害实体。但是其效果会受若干事物影响：<br>1）目标生命值。<br>2）目标是否是亡灵？<br>3）实体是否看到你？<br><br>其他元素攻击的效果有所不同，并且有只能通过实验发现的细微差别！
```

2023-11-24 04:45 UTC, ChuijkYahus commented on projects/1.12.2/assets/zettai-psi/zettai_psi/lang/zh_cn.lang
> +psi.piecegroup.alchemy_code.desc=手动控制效果的魔力路径，就几乎能用任何事物影响实体！<br><br>但是，魔力路径不能是负的，它不能处理不同的值，而且在某些时候它的值会结束。<br><br>用这种方法产生的效果的强度不能高于 2，它们只是不减损而已！
```suggestion
psi.piecegroup.alchemy_code.desc=手动控制效果的魔力路径，就几乎能用任何事物影响实体！<br><br>但是，魔力路径不能是负的，它不能处理多个值，而且这种值的个数有限。<br><br>用这种方法产生的效果的强度不能高于 2，它们只是不减损而已！
```

2023-11-24 04:45 UTC, ChuijkYahus commented
这个结束就合并吧

2023-11-24 11:46 UTC, mczph commented
@ChuijkYahus 已修改

2023-11-25 05:43 UTC, ChuijkYahus approved these changes

2023-11-26 03:40 UTC, merged