提交 bosses of mass destruction 模组翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #2742
Opened 2022-12-28 09:15 UTC by IceDragonFla

- [ ] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-12-28 12:42 UTC, ChuijkYahus approved these changes
搬运一下：
应该没什么问题吧（）

2023-01-07 03:52 UTC, Rinko1231 reviewed
建议还是考虑一下原文（

2023-01-07 03:52 UTC, Rinko1231 commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +    "entity.bosses_of_mass_destruction.blue_fireball": "幽焰弹",
虽然比较雅，但是`Lich`和`Blue`都扔了啊（

2023-01-07 03:52 UTC, Rinko1231 commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +    "advancements.adventure.night_lich_defeat.title": "夜之颂歌",
`Vanquisher`也没了（

2023-01-07 03:52 UTC, Rinko1231 commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +    "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.missile" : "霜星",
```suggestion
    "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.missile" : "霜弹",
```
原文就一个missile啊（

2023-01-07 07:37 UTC, IceDragonFla commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +    "entity.bosses_of_mass_destruction.blue_fireball": "幽焰弹",
lich直接翻译成光什么的感觉不太好。。。这是一个夜间boss类似于巫妖王内种的

2023-01-07 07:38 UTC, IceDragonFla commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +    "advancements.adventure.night_lich_defeat.title": "夜之颂歌",
好像没找到这个。。。

2023-01-07 07:39 UTC, IceDragonFla commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +    "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.missile" : "霜星",
是的。。。

2023-07-30 10:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2742) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2742) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2742) it.</sub>

2023-08-01 05:10 UTC, luoxueyasha commented
@IceDragonFla 
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

2023-08-01 08:59 UTC, IceDragonFla commented
解决了一月份遗留的问题，如果还有情况请维护者联系，辛苦。

2023-08-01 10:48 UTC, luoxueyasha requested changes
加戏有点多
部分译名更胜#3597 一筹，但是整体用力过猛，偏离原意

2023-08-01 10:48 UTC, luoxueyasha commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +    "entity.bosses_of_mass_destruction.lich": "夜歌",
为何翻译为`夜歌`？有什么原因吗

2023-08-01 10:48 UTC, luoxueyasha commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +    "entity.bosses_of_mass_destruction.obsidilith" : "龙晶结构体",
`龙`是哪里来的？

2023-08-01 10:48 UTC, luoxueyasha commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +    "entity.bosses_of_mass_destruction.petal_blade" : "落英",
没翻译出原文`Blade`

2023-08-01 10:48 UTC, luoxueyasha commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +    "block.bosses_of_mass_destruction.sealed_blackstone" : "密封的黑石",
原文带`Bricks`，请确定是否是`黑石砖`

2023-08-01 10:48 UTC, luoxueyasha commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +    "block.bosses_of_mass_destruction.void_blossom_block" : "虚空之花刷怪笼",
原文带`Boss`，请不要漏译

2023-08-01 10:48 UTC, luoxueyasha commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +    "block.bosses_of_mass_destruction.void_lily" : "空无百合",
和虚空之花的关系？

2023-08-01 10:48 UTC, luoxueyasha commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +    "item.bosses_of_mass_destruction.crystal_fruit.tooltip" : "获得短暂的再生和抗性提升效果",
```suggestion
    "item.bosses_of_mass_destruction.crystal_fruit.tooltip" : "获得短暂的生命恢复和抗性提升效果",
```
详见[译名标准化](https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96)

2023-08-01 10:48 UTC, luoxueyasha commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +    "block.bosses_of_mass_destruction.levitation_block" : "反重力装置",
确定是`装置`？前文`Amplifier`和这里的`Table`我认为有区分的必要

2023-08-01 10:48 UTC, luoxueyasha commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +    "advancements.end.obsidilith_defeat.description" : "击败龙晶结构体（黑曜石古称龙晶）",
```suggestion
    "advancements.end.obsidilith_defeat.description" : "击败龙晶结构体",
```
没必要加注释

2023-08-01 10:48 UTC, luoxueyasha commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +    "advancements.adventure.night_lich_defeat.title": "夜之颂歌",
`Vanquisher`没翻译出来

2023-08-01 10:48 UTC, luoxueyasha commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +    "subtitles.bosses_of_mass_destruction.gauntlet_cast" : "下界巨拳：投掷",
`Cast`是投掷？

2023-08-01 10:48 UTC, luoxueyasha commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +    "text.autoconfig.bosses_of_mass_destruction.title" : "需要重启游戏",
游戏中的显示效果是？

2023-08-01 23:52 UTC, IceDragonFla commented
> @IceDragonFla 哥们来商量商量协作（

好的。。。要不直接把我的并到你的pr里面吧。。。

2023-08-01 23:53 UTC, IceDragonFla commented
@nageih 那我这边就直接close了（应该在群里找得到我吧）

2023-08-04 06:12 UTC, closed without merging