Girlsfrontline
CFPAOrg/Minecraft-Mod-Language-Package pull request #2753
Opened 2022-12-30 06:11 UTC by 323193901

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2022-12-30 06:36 UTC, dovisutu commented
> ⚠ 检测到了一个语言文件，但是提交的路径不正常。缺少了 {ModDomain} 或 {CurseForge 项目名} 文件夹。请检查你的提交路径：projects/1.12.2/assets/hmggirlfront/lang/zh_CN.lang；

2022-12-30 07:13 UTC, 323193901 reviewed
重新提交

2022-12-30 07:25 UTC, A-Black-Fish commented
[模组链接](https://forum.civa.jp/viewtopic.php?f=3&t=36)

2022-12-30 07:32 UTC, ChuijkYahus commented
请注意更新英文文件
并请将除英文和简体中文之外的其他文件删除

2022-12-30 08:39 UTC, A-Black-Fish commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.string.pad.mission1_2.name=[达成条件：召唤1个人偶]
翻译统一下？

2022-12-30 08:39 UTC, A-Black-Fish commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.string.pad.mission1_2.name=[达成条件：召唤1个人偶]
下面人形，这里就人偶

2022-12-30 08:39 UTC, A-Black-Fish commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.string.pad.doll_explanation0_1.name=-如何制作战术人偶-
```suggestion
hmggirlfront.string.pad.doll_explanation0_1.name=-如何制作战术人形-
```

2022-12-30 08:39 UTC, A-Black-Fish commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.string.pad.gun_explanation0_2.name=召唤一个战术娃娃
```suggestion
hmggirlfront.string.pad.gun_explanation0_2.name=召唤一个战术人形
```

2022-12-30 08:57 UTC, A-Black-Fish commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.order.stay.name=全体待命！
待命可能会好一些吧，在游戏中只是让她站在那

2022-12-30 12:49 UTC, A-Black-Fish approved these changes

2022-12-30 13:43 UTC, A-Black-Fish commented
> ⚠ 警告：PR 中 hmggirlfront-1.12.2 的中英文语言文件不对应。
> 
> * 英文语言文件有 4 个 Key 多于中文语言文件。例如：
>   
>   * 行 29-`hmggirlfront.cor.level2.name`
>   * 行 61-`hmggirlfront.string.pad.mission5_2.name`
>   * 行 334-`hmggirlfront.bdoll_base_containership.name`
>   * 行 346-`hmggirlfront.bdoll_base_sea_launch_em.name`
> * 中文语言文件有 93 个 Key 多于英文语言文件。例如：
>   
>   * 行 28-`hmggirlfront.base.world_level1.name`
>   * 行 29-`hmggirlfront.base.world_level2.name`
>   * 行 32-`hmgirfront.cor.level2.name`
>   * 行 34-`hmggirlfront.cor.level4.name`
解决一下

2022-12-30 13:47 UTC, dovisutu reviewed
_如无排版需要等特殊要求，请将翻译文本中的**标点**（不包括`%3$s` `§r`等标记符和JSON格式的半角引号等）全部改为**全角**标点。_
至少有好几处全角冒号和半角冒号混杂的情况。以及，可以考虑是否需要使用\u2026作为省略号；如果不需要，至少应该统一省略号的点数。

2022-12-30 13:47 UTC, dovisutu commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.cor.level11.name=[==已达成==目标3：占领据点]
* 翻译似乎不太统一？以及9和11似乎都是“目标3”

2022-12-30 13:59 UTC, A-Black-Fish commented
该pr应该转草案吧（

2023-02-07 14:33 UTC, 323193901 commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.string.pad.gun_explanation0_2.name=召唤一个战术娃娃
已修改

2023-02-09 13:04 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.cor.level10.name=[==已达成==目标10：夺回海上发射平台]
上面已实现下面已达成，统一一下
此外原文里好像没有这些strings（？

2023-02-09 13:23 UTC, Ricky-fight requested changes

2023-02-09 13:23 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.mission2.doll.break_u1.name=M1014:.....什么！?这个能量反应是.....！？
```suggestion
hmggirlfront.mission2.doll.break_u1.name=M1014：……什么！？这个能量反应是……！？
```
还请统一检查一下（）
![image](https://user-images.githubusercontent.com/13982778/217822730-950e844d-7245-4b53-aa6f-f43f35312659.png)

2023-02-09 14:20 UTC, mamaruo commented
日语文件需保留以供校对

2023-02-16 05:15 UTC, luoxueyasha reviewed
看了大概一百行
只能说咱们是翻译，可以改写，但是原文语义不能乱改啊（

2023-02-16 05:15 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.mission2.inf.clear.name=[胜利条件]敌方运输部队全灭
```suggestion
hmggirlfront.mission2.inf.clear.name=[胜利条件]击破敌方运输部队
```
现代汉语里没有`全灭`这个词，请使用`击破`，`全歼`等相近词语代替。此外日语里的`撃破`和`全滅`也有程度上的差别。
此外，“敌方运输部队全灭”这个表达听着怪怪的，如果用被字句的话是不是好一点？

2023-02-16 05:15 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.mission2.gaiyou4.name=赫丽安：而此次任务是歼灭一处的铁血运输部队，该部队极为可能是要前往预计量产木星的工厂。
```suggestion
hmggirlfront.mission2.gaiyou4.name=赫丽安：而此次任务需要歼灭一处铁血运输部队，该部队似乎要前往生产木星的工厂。
```
原文`今回の任務はジュピター生産工場に運び込むためと思われる輸送部隊への強襲だ`

1. 没有`极为`这种程度上的描述
2. `预计`是描述运输部队的
3. 原文是`生产`而不是`量产`（万一前往的是原型机所在的工厂呢？）

2023-02-16 05:15 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +<<<<<<< HEAD
这个head似乎是merge的时候复制出现的问题？还有line 106也是

2023-02-16 06:10 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.mission2.gaiyou2.name=赫丽安：它的名字是「木星」、是铁血在军方技术的基础上改良后制造的要塞火炮。
```suggestion
hmggirlfront.mission2.gaiyou2.name=赫丽安：它的名字是「木星」、是铁血在窃取的军方技术的基础上改良后制造的要塞火炮。
```
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/3020#discussion_r1108045507

2023-02-28 09:38 UTC, Ricky-fight commented
ping @323193901

2023-03-11 04:51 UTC, closed without merging