提交 minecraft-earth-mod 模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #2763
Opened 2023-01-01 11:46 UTC by JohnnyTheTiger

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-01-08 23:49 UTC, Cyl18 commented on projects/1.16/assets/minecraft-earth-mod/minecraft_earth_mod/lang/zh_cn.json
> +  "block.minecraft_earth_mod.ruby_ore": "红宝石矿",
```suggestion
  "block.minecraft_earth_mod.ruby_ore": "红宝石矿石",
```

2023-01-10 15:04 UTC, JohnnyTheTiger commented
感谢帮助修改，第一次上传，没什么经验。(汗

2023-07-04 02:29 UTC, luoxueyasha requested changes
部分问题请全文通查

2023-07-04 02:29 UTC, luoxueyasha commented on projects/1.16/assets/minecraft-earth-mod/minecraft_earth_mod/lang/zh_cn.json
> +  "gamerule.waterproofGolems.description": "熔炉傀儡在水中会受到伤害吗？",
```suggestion
  "gamerule.waterproofGolems.description": "熔炉傀儡在水中是否会受到伤害？",
```
具体应结合实际游戏内容及显示；就键名来看这是一条gamerule的提示

2023-07-04 02:29 UTC, luoxueyasha commented on projects/1.16/assets/minecraft-earth-mod/minecraft_earth_mod/lang/zh_cn.json
> +  "gamerule.doEarthDimension.description": "启用 / 禁用地球模组维度！禁用此项将无法使您找到拥有大量酷炫生物的新世界:(",
```suggestion
  "gamerule.doEarthDimension.description": "启用 / 禁用地球模组维度！禁用此项将无法进入拥有大量酷炫生物的新世界:(",
```
此处`找到`为虚指，即禁止玩家进入该维度；英语中的`you`翻译到汉语中一般略过不译

2023-07-04 02:29 UTC, luoxueyasha commented on projects/1.16/assets/minecraft-earth-mod/minecraft_earth_mod/lang/zh_cn.json
> +  "fluid.mud": "泥浆",
```suggestion
  "fluid.mud": "泥",
```

2023-07-04 02:29 UTC, luoxueyasha commented on projects/1.16/assets/minecraft-earth-mod/minecraft_earth_mod/lang/zh_cn.json
> +  "block.minecraft_earth_mod.buttercup": "金凤花",
```suggestion
  "block.minecraft_earth_mod.buttercup": "毛茛",
```
https://minecraft.fandom.com/zh/wiki/Minecraft_Earth:%E6%AF%9B%E8%8C%9B

2023-07-04 02:29 UTC, luoxueyasha commented on projects/1.16/assets/minecraft-earth-mod/minecraft_earth_mod/lang/zh_cn.json
> +  "block.minecraft_earth_mod.grass_tappable": "草可点击物",
有点生硬，可以进行如下考虑
```suggestion
  "block.minecraft_earth_mod.grass_tappable": "草（可点击物）",
```

2023-07-04 02:29 UTC, luoxueyasha commented on projects/1.16/assets/minecraft-earth-mod/minecraft_earth_mod/lang/zh_cn.json
> +  "block.minecraft_earth_mod.boulder_zombie_climbing_block": "攀岩僵尸正爬的方块",
是`正在爬`还是`可爬`？

2023-07-04 02:29 UTC, luoxueyasha commented on projects/1.16/assets/minecraft-earth-mod/minecraft_earth_mod/lang/zh_cn.json
> +  "advancements.place_ruby_block.title": "♫Red Like Roses♪",
为何加入音乐符号

2023-07-04 02:29 UTC, luoxueyasha commented on projects/1.16/assets/minecraft-earth-mod/minecraft_earth_mod/lang/zh_cn.json
> +  "advancements.hogsmeade.descr": "“真想给你带些黄油啤酒，真正能让你暖和起来。”",
```suggestion
  "advancements.hogsmeade.descr": "“多么希望能给你带一些黄油啤酒啊，真是让你感到全身热乎乎的——”",
```
（英）罗琳（Rowling, J.K.）. 哈利·波特与阿兹卡班囚徒[M]. 马爱农, 马爱新. 北京：人民文学出版社, 2009.

2023-07-04 02:29 UTC, luoxueyasha commented on projects/1.16/assets/minecraft-earth-mod/minecraft_earth_mod/lang/zh_cn.json
> +  "advancements.get_horn.descr": "（不要吹响号角）",
没有翻译出原文的`spam`

2023-07-04 02:29 UTC, luoxueyasha commented on projects/1.16/assets/minecraft-earth-mod/minecraft_earth_mod/lang/zh_cn.json
> +  "advancements.get_dimension_key.descr": "远古的光与暗之魂已经被释放了（沉声）……我去，搞错游戏了",
```suggestion
  "advancements.get_dimension_key.descr": "古老的光明与黑暗之魂已经释放……我去，搞错游戏了",
```
https://terraria.wiki.gg/zh/wiki/%E8%A1%80%E8%82%89%E5%A2%99
别乱给译文加戏

2023-07-11 04:14 UTC, luoxueyasha commented
@ChuijkYahus 申请7+7

2023-07-11 04:41 UTC, ChuijkYahus commented
* 7+7时限进入第一阶段，请注意查看各审核意见

@JohnnyTheTiger

2023-07-30 10:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2763) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2763) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Cyl18<br/>:x: JohnnyTheTiger<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2763) it.</sub>

2023-08-01 09:47 UTC, Cactusstudent commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@JohnnyTheTiger

2023-08-08 02:03 UTC, Cactusstudent commented
- 该提交由于[7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)将被关闭，请知晓。若仍想维护可选择Reopen此提交或重新打开新提交，并查看本提交内的审查意见并进行更改。

2023-08-09 21:05 UTC, closed without merging