Nyx + Ore excavation: integration + The summoner + Ancient Beasts 翻译更新 & Athelas + Betweenlands Storage + Blocklings + Camels + Demonic scythe + Farlanders + SCP附属全家桶 + Lootr + Macaw's Wall + Materialis + Nether Hexed Kingdom + Rope Ladders + The Abyss + Weeping Angels + Zonko's Monster 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2765
Opened 2023-01-01 18:37 UTC by BeiWu6

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2023-01-02 05:33 UTC, BeiWu6 reviewed
Ancient Beasts + The Abyssm 翻译修正

2023-01-02 05:35 UTC, BeiWu6 commented
/mv-recursive "projects/1.12.2/assets/nether-hexed-kingdom/netherhexedkingfommod/" "projects/1.12.2/assets/nether-hexed-kingdom/netherhexedkingdommod/"

2023-01-02 05:38 UTC, BeiWu6 commented
/update-en weeping-angels-mod 1.12.2
/mv-recursive "projects/1.12.2/assets/nether-hexed-kingdom/netherhexedkingfommod/" "projects/1.12.2/assets/nether-hexed-kingdom/netherhexedkingdommod/
/update-en the-hordes 1.12.2
/add-mapping beast-slayer 518157
/add-mapping blocklings 264856
/add-mapping demonic-scythe 628849

2023-01-02 05:55 UTC, BeiWu6 reviewed
修正标点符号

2023-01-02 06:08 UTC, BeiWu6 reviewed
二次修正标点符号

2023-01-02 06:18 UTC, BeiWu6 reviewed
三次修正标点符号

2023-01-03 14:59 UTC, mamaruo commented
/add-mapping beast-slayer 518157
/add-mapping blocklings 264856
/add-mapping demonic-scythe 628849

2023-01-04 09:15 UTC, A-Black-Fish requested changes
大概看了下 Farlanders 那 lang 机翻味有点大，部分 lang 有英文部分，emm我就不做评价了（我的建议是不合并）(rope  ladders 后面的lang我就大概地看一下

2023-01-04 09:15 UTC, A-Black-Fish commented on projects/1.12.2/assets/betweenlands-storage/bsb/lang/zh_cn.lang
> +tile.angler_tooth_block.name=安康牙齿块
```suggestion
tile.angler_tooth_block.name=鮟鱇牙齿块
```

2023-01-05 09:56 UTC, dovisutu reviewed
只看到nether-hexed-kingdom这个位置
farlander暂时没看
有些长一点的只是大致看了一下

-------

部分可以采用的或许可以`cherry-pick`进主库，就是不知道git魔法好不好操作......

-------

看起来应该还可以的：
- blocklings
- camels
- demonic scythe

疑问：
- 1.12/mcw-bridges为何删除？

2023-01-05 09:56 UTC, dovisutu commented on projects/1.12.2/assets/athelas/athelas/lang/zh_cn.lang
> +tile.athelas.name=王叶草
kingsfoil <=> athelas
现在这个译法怎么感觉像是把译名弄反了一样......

2023-01-05 09:56 UTC, dovisutu commented on projects/1.12.2/assets/beast-slayer/ancientbeasts/lang/zh_cn.lang
> +advancements.ancientbeasts.kill_fox.title=你禽兽
省略号请使用`/u2026/u2026`。打包后的文件使用的`/ue908/ue909`是为调整省略号渲染而在打包过程中**自动更改**的，不需要手动进行更改。
（事实上这么更改甚至加大了提供*不替换*选项的难度......）

2023-01-05 09:56 UTC, dovisutu commented on projects/1.12.2/assets/lootr/lootr/lang/zh_cn.lang
> +lootr.message.refresh_start=The container will refresh with new contents in %s seconds!
* 这一部分大幅度缺失翻译。是有特殊原因吗？

2023-01-05 09:56 UTC, dovisutu commented on projects/1.12.2/assets/materialis/materialis/lang/zh_cn.lang
> +modifier.unlimited.desc=§o做大事的感觉 §r\或许它能让你免疫一些效果 但是谁知道呢
- 严重夹带私货，与原文有较大偏差。出于各种原因（比如受众等），本库大概难以接受这样有偏差的翻译。

2023-01-05 09:56 UTC, dovisutu commented on projects/1.12.2/assets/nether-hexed-kingdom/netherhexedkingdommod/lang/zh_cn.lang
> +tile.human_skeleton_bottom.name=人体骨架 （底部）
```suggestion
tile.human_skeleton_top.name=人体骨架（顶部）
tile.human_skeleton_bottom.name=人体骨架（底部）
```

2023-01-06 06:06 UTC, A-Black-Fish commented on projects/1.12.2/assets/athelas/athelas/lang/zh_cn.lang
> +tile.athelas.name=王叶草
没反，你上mcmod一看就知道

2023-01-07 13:20 UTC, BeiWu6 commented on projects/1.12.2/assets/lootr/lootr/lang/zh_cn.lang
> +lootr.message.refresh_start=The container will refresh with new contents in %s seconds!
Lootr这部分确实是不大好翻译，所以就出现了语言文件中汉化大量缺失的情况。

2023-01-07 13:21 UTC, BeiWu6 commented on projects/1.12.2/assets/materialis/materialis/lang/zh_cn.lang
> +modifier.unlimited.desc=§o做大事的感觉 §r\或许它能让你免疫一些效果 但是谁知道呢
materialis部分并非我本人负责，但我会按照要求重新汉化。

2023-01-07 13:22 UTC, BeiWu6 commented on projects/1.12.2/assets/betweenlands-storage/bsb/lang/zh_cn.lang
> +tile.angler_tooth_block.name=安康牙齿块
Farlanders部分并非为我本人汉化，但我会安装要求进行修订。

2023-01-07 13:23 UTC, BeiWu6 commented on projects/1.12.2/assets/betweenlands-storage/bsb/lang/zh_cn.lang
> +tile.angler_tooth_block.name=安康牙齿块
BBS模组的汉化名称标准来源于最新版的The Betweenlands汉化，如有问题请联系该项目负责人。

2023-01-07 13:27 UTC, closed without merging