Additional Lanterns 1.18 汉化
CFPAOrg/Minecraft-Mod-Language-Package pull request #2789
Opened 2023-01-11 04:33 UTC by IAMJJJJJ

Additional Lanterns（更多灯笼）1.18汉化

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2023-01-11 05:14 UTC, ChuijkYahus commented
/mv-recursive "projects/1.18/assets/additional-lanterns/additionallanterns" "projects/1.18/assets/additional-lanterns/additionallanterns/lang"

2023-01-24 16:43 UTC, DrIceTea123 requested changes
这中文语言文件是怎么排的序，给我审头晕了
就只有译名和原版保持一致的问题，我都标出来了，记得改不要只改一处，16色的版本全都要改掉

2023-01-24 16:43 UTC, DrIceTea123 commented on projects/1.18/assets/additional-lanterns/additionallanterns/lang/zh_cn.json
> +  "block.additionallanterns.lime_bricks_lantern": "黄绿色砖块灯笼",
原版译名为`红砖块`
```suggestion
  "block.additionallanterns.lime_bricks_lantern": "黄绿色红砖块灯笼",
```

2023-01-24 16:43 UTC, DrIceTea123 commented on projects/1.18/assets/additional-lanterns/additionallanterns/lang/zh_cn.json
> +  "block.additionallanterns.green_red_nether_bricks_lantern": "绿色红下界砖灯笼",
原版译名为`红色下界砖块`
虽然`绿色红色下界砖块灯笼`和`红色红色下界砖块灯笼`很怪，但只能这么译了
```suggestion
  "block.additionallanterns.green_red_nether_bricks_lantern": "绿色红色下界砖块灯笼",
```

2023-01-24 16:43 UTC, DrIceTea123 commented on projects/1.18/assets/additional-lanterns/additionallanterns/lang/zh_cn.json
> +  "block.additionallanterns.normal_nether_bricks_chain": "下界砖锁链",
原版译名为`下界砖块`
```suggestion
  "block.additionallanterns.normal_nether_bricks_chain": "下界砖块锁链",
```

2023-01-24 16:43 UTC, DrIceTea123 commented on projects/1.18/assets/additional-lanterns/additionallanterns/lang/zh_cn.json
> +  "block.additionallanterns.smooth_stone_chain": "平滑石锁链",
原版译名为`平滑石头`
```suggestion
  "block.additionallanterns.smooth_stone_chain": "平滑石头锁链",
```

2023-02-07 17:38 UTC, ChuijkYahus commented
* 7+7时限进入第一阶段。从该评论发出的时间开始计时。

ping @IAMJJJJJ

2023-02-21 05:06 UTC, ChuijkYahus commented
- 7+7时限进入第二阶段。从该评论发出的时间开始计时。

ping @IAMJJJJJ

2023-03-29 14:05 UTC, ChuijkYahus commented
* 7+7时限已到，可自行reopen PR以提交翻译。

@IAMJJJJJ

2023-03-29 14:05 UTC, closed without merging