assemblylinemachines 装配线 物品汉化
CFPAOrg/Minecraft-Mod-Language-Package pull request #2808
Opened 2023-01-14 13:16 UTC by jiayu233

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-01-15 09:15 UTC, dovisutu commented
~_您可能是浏览器自动翻译的受害者_~

/mv "项目/1.18/资产/装配线机器/装配线机器/朗/zh_cn.json" "projects/1.18/assets/assemblylinemachines/assemblylinemachines/lang/zh_cn.json"

2023-01-15 09:20 UTC, jiayu233 commented
没看懂 怎么修改

2023-01-15 09:23 UTC, dovisutu requested changes
* _存在多处文本未翻译/未完全翻译。_
* _如无排版需要等特殊要求，请将翻译文本中的**标点**（不包括`%3$s` `§r`等标记符和JSON格式的半角引号等）全部改为**全角**标点。_

2023-01-15 09:23 UTC, dovisutu commented
> 没看懂 怎么修改

不用了 已经修复了

2023-01-15 09:37 UTC, jiayu233 commented
修改腐化外壳为腐化尸壳 其他部分文本没有翻译计划

2023-01-15 11:38 UTC, dovisutu commented on projects/1.18/assets/assemblylinemachines/assemblylinemachines/lang/zh_cn.json
> +	"sound.assemblylinemachines.assembly_required": "需要组装"
原版中的字幕（右下角那个）是有格式的：
 - `主体：行为`，其中`主体`有时略去

如：
 - `美西螈：啾啾`
*美西螈的静息音效*
 - `怪异的噪声`
*洞穴音效*

2023-01-15 17:39 UTC, jiayu233 commented on projects/1.18/assets/assemblylinemachines/assemblylinemachines/lang/zh_cn.json
> +	"sound.assemblylinemachines.assembly_required": "需要组装"
格式已修改 最后一项暂时恢复英文原文

2023-01-16 01:44 UTC, jiayu233 commented
![image](https://user-images.githubusercontent.com/30435589/212581391-dfb700d8-536e-447d-952e-b07d65fc44e6.png)

2023-02-06 01:03 UTC, Ricky-fight commented
#2959 这闹得……
那这个怎么办（）

2023-02-06 07:43 UTC, LanceLeviathan commented
> #2959 这闹得...... 那这个怎么办（）

你有翻译帕秋莉手册吗，我在翻译那个，要不交给我好了

2023-02-07 17:37 UTC, ChuijkYahus commented
已在#2959 入库，close

2023-02-07 17:37 UTC, closed without merging