Tough As Nails 官中拉取、更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #2823
Opened 2023-01-17 13:03 UTC by Cactusstudent

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

1.19的第一个中文本地化PR，希望别出什么大问题

2023-01-17 13:47 UTC, Cactusstudent commented
/diff

2023-01-17 14:18 UTC, Cactusstudent commented
等bot好了之后再合并吧

2023-01-18 17:05 UTC, xfl03 requested changes

2023-01-18 17:05 UTC, xfl03 commented on projects/1.19/assets/tough-as-nails/toughasnails/lang/zh_cn.json
> +  "death.attack.toughasnails.hyperthermia": "%1$s中暑而死。",
%1$s因中暑而死
（没有句号）

2023-01-18 17:05 UTC, xfl03 commented on projects/1.19/assets/tough-as-nails/toughasnails/lang/zh_cn.json
> +  "desc.toughasnails.cooling": "制冷",
冷却

2023-01-18 17:05 UTC, xfl03 commented on projects/1.19/assets/tough-as-nails/toughasnails/lang/zh_cn.json
> +  "death.attack.toughasnails.hyperthermia.player": "%1$s在试图逃离%2$s时中暑而死",
%1$s在试图逃离%2$s时因中暑而死

2023-01-18 17:05 UTC, xfl03 commented on projects/1.19/assets/tough-as-nails/toughasnails/lang/zh_cn.json
> +  "enchantment.toughasnails.thermal_tuning": "自动调温",
自动控温

2023-01-18 17:05 UTC, xfl03 commented on projects/1.19/assets/tough-as-nails/toughasnails/lang/zh_cn.json
> +  "item.toughasnails.tan_icon": "TAN 图标",
（TAN不用翻译？）

2023-01-19 01:54 UTC, Cactusstudent commented on projects/1.19/assets/tough-as-nails/toughasnails/lang/zh_cn.json
> +  "item.toughasnails.tan_icon": "TAN 图标",
这个是作者习惯，喜欢把自己模组的图标做成这样，这条不必翻译

2023-01-19 02:05 UTC, Cactusstudent commented on projects/1.19/assets/tough-as-nails/toughasnails/lang/zh_cn.json
> +  "desc.toughasnails.cooling": "制冷",
去看了下1.12.2的，heating并未提及，但是cooling被翻译为清凉

2023-01-19 03:17 UTC, xfl03 approved these changes

2023-01-19 14:53 UTC, mamaruo approved these changes

2023-01-20 14:22 UTC, merged