No Chat Reports 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2828
Opened 2023-01-18 14:00 UTC by dovisutu

> 要进入1.19，应当要了解关于1.19的聊天举报机制的缺陷与漏洞。

大部分技术性内容参照B站 @账号己注销 翻译的 Aizistral 的有关视频，应该没弄错。

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2023-01-18 14:01 UTC, dovisutu commented
/mv-recursive projects/1.19/assets/no-chat-reports/nochatreports projects/1.19/assets/no-chat-reports/nochatreports/lang

2023-01-18 17:40 UTC, xfl03 commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"modmenu.descriptionTranslation.nochatreports": "将玩家消息中的用户签名去除，以使得其余玩家无法将此信息与玩家的Mojang/Microsoft账号关联，进而无法对其进行聊天举报。",
去除玩家聊天消息中的签名，使得其余玩家无法将该消息关联到你的Mojang/Microsoft账号，进而无法举报该消息。

2023-01-18 17:40 UTC, xfl03 commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"gui.nochatreports.secure_chat": "由于安装有No Chat Reports模组，该选项无法实现，因为聊天消息中的签名已被移除。",
由于No Chat Reports模组移除了聊天消息中的签名，无法使用此选项。

2023-01-18 17:40 UTC, xfl03 commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"gui.nochatreports.no_reporting": "由于在服务端安装有No Chat Reports，该服务器上无法进行聊天举报。",
由于此服务器安装了No Chat Reports，无法举报聊天消息。

2023-01-18 17:40 UTC, xfl03 commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"disconnect.nochatreports.client": "模组被配置为要求所连接的服务器安装No Chat Reports模组，但该服务器并未安装。",
模组配置中设定了“需要服务器同时安装No Chat Reports模组”，但服务器未安装本模组。

2023-01-18 17:43 UTC, mamaruo requested changes

2023-01-18 17:43 UTC, mamaruo commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"option.NoChatReports.convertToGameMessage": "转换未系统消息",
```suggestion
	"option.NoChatReports.convertToGameMessage": "转换为系统消息",
```

2023-01-18 17:43 UTC, mamaruo commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"gui.nochatreports.safety_status.secure": "该服务器安装了No Chat Reports模组，或者以其余可识别的方式禁用了聊天举报。在此可以安全地进行聊天。",
| **审查级别**    | 备注 |
|--------------|----|
| ⚪ 轻微 / 不阻止合并但需三思  |     |

**不要“进行”，能用动词就用**

known 翻译成“可识别的”有什么讲究吗

```suggestion
	"gui.nochatreports.safety_status.secure": "该服务器安装了No Chat Reports模组，或者用其他可识别的方式禁用了聊天举报。在此可以安全地聊天。",
```
原文：**This server has No Chat Reports installed, or prevents your messages from being reportable in some other known way. You can chat safely.**

2023-01-18 17:43 UTC, mamaruo commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"gui.nochatreports.safety_status.singleplayer": "在单人游戏中，总是可以安全地发送消息，无需担心聊天举报。",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   suggestion 中对 always 的翻译有点生硬  |
```suggestion
	"gui.nochatreports.safety_status.singleplayer": "在单人游戏中发送消息总是安全。",
```
原文：**You can always chat safely in singleplayer.**

2023-01-18 17:43 UTC, mamaruo commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"algorithm.nochatreports.caesar": "§l凯撒密码§r\n梗级密码。使用这个算法相当于期望入侵者看了加密消息就被吓跑。不过，对于很多人而言，的确如此，因此使用该算法的可行度取决于所处环境。\n蜜月应当为从1到1024的整数。字符位移按照编码位点而非字母顺序移进行，以保持多语种兼容性。",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  蜜月？芈月！  |

另外这句话的中英逻辑都不明确？

```suggestion
	"algorithm.nochatreports.caesar": "§l凯撒密码§r\n梗级密码。使用这个算法相当于期望入侵者看了加密消息就被吓跑。不过，对于很多人而言，的确如此，因此使用该算法的可行度取决于所处环境。\n密钥应当为从1到1024的整数。字符位移按照字符编码而非字母顺序移进行，以保证多语种兼容性。",
```
原文：**§lCaesar§r\nMeme cipher. With this you're basically hoping that people will give up without even trying to decrypt your messages. That might be true in many cases, so viability of using it depends on your threat model.\nKey should be integer from 1 to 1024. Shift is done by character code instead of alphabetically, to ensure compatibility with any language.**

2023-01-18 17:43 UTC, mamaruo commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"gui.nochatreports.realms_warning.contents": "Realms服务器并非私有的服务器。Realm服务器的所有着无法关闭聊天举报；此外，Mojang还会进行自动的聊天筛选，识别出潜在的“网络暴力”信息，并将其交予人工审核。如果人工审核认为消息违反了Minecraft社区规范——即便聊天的参与者未受冒犯——游戏账号将从所有多人游戏中被禁用，暂时禁用或者永久
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |

另外我觉得 monitor 翻不出“筛选”
```suggestion
	"gui.nochatreports.realms_warning.contents": "Realms服务器并非私有的服务器。Realm服务器的所有者无法关闭聊天举报；此外，Mojang还会进行自动的聊天筛选，识别出潜在的“网络暴力”信息，并将其交予人工审核。如果人工审核认为消息违反了Minecraft社区规范——即便聊天的参与者未受冒犯——游戏账号将从所有多人游戏中被禁用，暂时禁用或者永久禁用都有可能。强烈建议使用聊天加密。",
```
原文：**Realms servers are not private. Realm owners cannot disable chat reporting, and Mojang applies additional chat monitoring to identify potential \"online harms\" and escalate them to human review. If you are then found to violate Minecraft's Community Standards - even if chat participants did not get offended - you will be banned, temporarily or permanently, from all multiplayer services. Use of encryption is highly advised.**

2023-01-19 03:21 UTC, xfl03 commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"gui.nochatreports.safety_status.secure": "该服务器安装了No Chat Reports模组，或者以其余可识别的方式禁用了聊天举报。在此可以安全地进行聊天。",
该服务器使用了No Chat Reports模组或其他已知方式禁用了聊天举报，可以在此放心聊天。

2023-01-19 03:25 UTC, xfl03 commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"gui.nochatreports.safety_status.singleplayer": "在单人游戏中，总是可以安全地发送消息，无需担心聊天举报。",
可以放心地在单人游戏中随时随地发送消息。

2023-01-19 03:27 UTC, xfl03 commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"modmenu.descriptionTranslation.nochatreports": "将玩家消息中的用户签名去除，以使得其余玩家无法将此信息与玩家的Mojang/Microsoft账号关联，进而无法对其进行聊天举报。",
```suggestion
	"modmenu.descriptionTranslation.nochatreports": "去除玩家聊天消息中的签名，使得其余玩家无法将该消息关联到你的Mojang/Microsoft账号，进而无法举报该消息。",
```

2023-01-19 03:27 UTC, xfl03 commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"gui.nochatreports.secure_chat": "由于安装有No Chat Reports模组，该选项无法实现，因为聊天消息中的签名已被移除。",
```suggestion
	"gui.nochatreports.secure_chat": "由于No Chat Reports模组移除了聊天消息中的签名，无法使用此选项。",
```

2023-01-19 03:27 UTC, xfl03 commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"gui.nochatreports.no_reporting": "由于在服务端安装有No Chat Reports，该服务器上无法进行聊天举报。",
```suggestion
	"gui.nochatreports.no_reporting": "由于此服务器安装了No Chat Reports，无法举报聊天消息。",
```

2023-01-19 03:28 UTC, xfl03 commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"disconnect.nochatreports.client": "模组被配置为要求所连接的服务器安装No Chat Reports模组，但该服务器并未安装。",
```suggestion
	"disconnect.nochatreports.client": "模组设置中设定了“需要服务器同时安装No Chat Reports模组”，但服务器未安装本模组。",
```

2023-01-19 03:28 UTC, xfl03 commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"gui.nochatreports.safety_status.secure": "该服务器安装了No Chat Reports模组，或者以其余可识别的方式禁用了聊天举报。在此可以安全地进行聊天。",
```suggestion
	"gui.nochatreports.safety_status.secure": "该服务器使用了No Chat Reports模组或其他已知方式禁用了聊天举报，可以在此放心聊天。",
```

2023-01-19 03:29 UTC, xfl03 commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"gui.nochatreports.safety_status.singleplayer": "在单人游戏中，总是可以安全地发送消息，无需担心聊天举报。",
```suggestion
	"gui.nochatreports.safety_status.singleplayer": "可以放心地在单人游戏中随时随地发送消息。",
```

2023-01-19 03:41 UTC, xfl03 commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"algorithm.nochatreports.caesar": "§l凯撒密码§r\n梗级密码。使用这个算法相当于期望入侵者看了加密消息就被吓跑。不过，对于很多人而言，的确如此，因此使用该算法的可行度取决于所处环境。\n蜜月应当为从1到1024的整数。字符位移按照编码位点而非字母顺序移进行，以保持多语种兼容性。",
> **审查级别**	备注
> 🔵 一般 / **阻止合并**	蜜月？芈月！
> 另外这句话的中英逻辑都不明确？
> 
> 原文：**§lCaesar§r\nMeme cipher. With this you're basically hoping that people will give up without even trying to decrypt your messages. That might be true in many cases, so viability of using it depends on your threat model.\nKey should be integer from 1 to 1024. Shift is done by character code instead of alphabetically, to ensure compatibility with any language.**

(GitHub居然不支持LaTeX)
单字符替换的密码算法，会建立一个满射`f`，使得所有字符`A`都有一个对应的字符`f(A)`用于替换，一般来说，`A!=f(A)`。
凯撒密码是一种简单的单字符替换的密码算法，传统的凯撒密码用于字母表（26个字母），选定一个偏移量d（1到25），将字符`A`替换为`A`后面的第d个字符（如果到字母表结尾了就回到开头，例如Z的后1个字母是A），将其推广到Unicode中，就是将字符编码进行对应的偏移。

2023-01-19 03:46 UTC, xfl03 commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"gui.nochatreports.realms_warning.contents": "Realms服务器并非私有的服务器。Realm服务器的所有着无法关闭聊天举报；此外，Mojang还会进行自动的聊天筛选，识别出潜在的“网络暴力”信息，并将其交予人工审核。如果人工审核认为消息违反了Minecraft社区规范——即便聊天的参与者未受冒犯——游戏账号将从所有多人游戏中被禁用，暂时禁用或者永久
```suggestion
	"gui.nochatreports.realms_warning.contents": "Realms服务器并非私有的服务器，Realm服务器的所有者无法关闭聊天举报。此外，Mojang还会主动审查聊天消息，尝试识别出潜在的“网络暴力”信息，并将其交予人工审核。如果人工审核认为消息违反了Minecraft社区规范，即便聊天的参与者未受冒犯，游戏账号也将禁止游玩多人游戏，这一禁令分为暂时禁止与永久禁止。强烈建议在Realm服务器中使用聊天加密。",
```

2023-01-19 03:52 UTC, xfl03 commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"algorithm.nochatreports.caesar": "§l凯撒密码§r\n梗级密码。使用这个算法相当于期望入侵者看了加密消息就被吓跑。不过，对于很多人而言，的确如此，因此使用该算法的可行度取决于所处环境。\n蜜月应当为从1到1024的整数。字符位移按照编码位点而非字母顺序移进行，以保持多语种兼容性。",
```suggestion
	"algorithm.nochatreports.caesar": "§l凯撒密码§r\n梗级密码。这是一个极易被破解的算法，使用这个算法相当于期望其他人看到加密消息就会被吓跑。在大部分情况下确实如此，因此使用该算法的安全性取决于所处环境。\n密钥应当为从1到1024的整数。为保证兼容多语种，将根据字符编码而非字母顺序进行偏移。",
```

2023-01-19 14:43 UTC, mamaruo reviewed
审完了

2023-01-19 14:43 UTC, mamaruo commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"gui.nochatreports.signing_mode.never_forced.tooltip": "该模式下，聊天消息无法签名。可能是玩家在使用离线账号，或者是客户端无法从Mojang服务器拉取签名密钥对。",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |
```suggestion
	"gui.nochatreports.signing_mode.never_forced.tooltip": "该模式下，聊天消息无法签名。可能是玩家在使用离线账号，或者是客户端无法从Mojang服务获取取签名密钥。",
```
原文：**This mode indicates that your messages cannot be signed at all, either because you are using an offline account or client failed to fetch your signing keys from Mojang's service.**

2023-01-19 14:43 UTC, mamaruo commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"option.NoChatReports.showReloadButton.tooltip": "在多人游戏界面添加一个按钮，在此可以控制重连选项。",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |
```suggestion
	"option.NoChatReports.showReloadButton": "显示重载按钮",
	"option.NoChatReports.showReloadButton.tooltip": "在“多人游戏”菜单添加一个按钮，用于配置重载。",
```
原文：
	"option.NoChatReports.showReloadButton": "Show reload button",
	"option.NoChatReports.showReloadButton.tooltip": "Adds a button for config reloading to multiplayer menu.",

2023-01-19 14:43 UTC, mamaruo commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"option.NoChatReports.showEncryptionButton.tooltip": "若配置为false，仅会在聊天界面中隐藏加密按钮。注意：加密选项本身并不会随之关闭。",
| **审查级别**    | 备注 |
|--------------|----|
| ⚪ 轻微 / 不阻止合并但需三思  |    |
```suggestion
	"option.NoChatReports.showEncryptionButton.tooltip": "若配置为false，仅会在聊天屏幕中隐藏加密按钮。注意：加密选项本身并不会随之关闭。",
```
原文：**Setting this to false will simply prevent encryption button from being displayed in the chat screen. Be aware that encryption itself will not be automatically disabled along with the button.**

2023-01-19 14:43 UTC, mamaruo commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"option.NoChatReports.hideWarningToast.tooltip": "移除在连接到禁用§oenforce-secure-profile§r的服务器时，在右上角弹出的提示框。",
| **审查级别**    | 备注 |
|--------------|----|
| ⚪ 轻微 / 不阻止合并但需三思  |    |
```suggestion
	"option.NoChatReports.hideWarningToast.tooltip": "连接到禁用§oenforce-secure-profile§r的服务器时，移除右上角弹出的提示框。",
```
原文：**Removes a warning toast that is displayed when entering servers with disabled §oenforce-secure-profile§r.**

2023-01-19 14:43 UTC, mamaruo commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"option.NoChatReports.demandOnServer.tooltip": "阻止客户端登入未使用No Chat Reports模组的服务器。",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |
```suggestion
	"option.NoChatReports.demandOnServer.tooltip": "阻止客户端登入未安装No Chat Reports模组的服务器。",
```
原文：**Prevents the client from joining servers that don't have No Chat Reports installed.**

2023-01-20 03:10 UTC, dovisutu commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"option.NoChatReports.showEncryptionButton.tooltip": "若配置为false，仅会在聊天界面中隐藏加密按钮。注意：加密选项本身并不会随之关闭。",
mcwiki 相关内容：

> 在多人游戏中，玩家可以通过按T与其他玩家聊天。聊天功能包括：
> 
> 历史记录 - 使用聊天框的右侧的滚动条可以查看历史聊天消息，也可上下滚动鼠标滚轮、或使用PAGEUP和PAGEDOWN。聊天框保存最近的100行消息。
> 在输入聊天文字时使用↑和↓可以调出自己的已发送消息。
> 可以点击聊天中出现的链接。
> 在聊天中使用复制（CTRL + C）和粘贴（CTRL + V）功能（部分Mac中使用⌘ Cmd代替Ctrl）。使用⇧ Shift + ↑、↓、←、→选择文本。
> 格式化字体：玩家可以使用分节符（§）更改文字样式。详见[格式化代码](https://minecraft.fandom.com/zh/wiki/%E6%A0%BC%E5%BC%8F%E5%8C%96%E4%BB%A3%E7%A0%81)。
> 注：分节符作为非法字符，本身无法在原版[客户端](https://minecraft.fandom.com/zh/wiki/%E5%AE%A2%E6%88%B7%E7%AB%AF)中输入。若将§复制粘贴到聊天框中发送，玩家会被自动踢出服务器，并提示“Illegal characters in chat（聊天消息出现非法字符）”，服务端则会报错disconnect.endOfStream。[仅[Java版](https://minecraft.fandom.com/zh/wiki/Java%E7%89%88)]
> 玩家也可以在聊天框中输入[命令](https://minecraft.fandom.com/zh/wiki/%E5%91%BD%E4%BB%A4)。命令由服务器解析，并以斜杠（/）作为开头。
> 
> 在聊天框外，/可作为命令输入键——按下后会出现预先输入/开头的聊天框。
> 输入/后按下Tab ↹会列出当前可用的命令，与执行/[help](https://minecraft.fandom.com/zh/wiki/%E5%91%BD%E4%BB%A4/help)命令类似。
> 在输入命令时，按下Tab ↹会根据已输入内容自动补全第一个可能的命令或用户名。若已输入内容可对应多个命令或用户名，聊天框中会显示所有可能结果的列表；再次按下Tab ↹会在输入栏内枚举这个列表。
> 
> 某些命令的一些额外参数也可能可以通过Tab ↹自动补全。
> 某些处理方块的命令（/[data](https://minecraft.fandom.com/zh/wiki/%E5%91%BD%E4%BB%A4/data)、/[fill](https://minecraft.fandom.com/zh/wiki/%E5%91%BD%E4%BB%A4/fill)等等）会要求提供目标方块的x、y、z轴[坐标](https://minecraft.fandom.com/zh/wiki/%E5%9D%90%E6%A0%87)。此时使用Tab ↹可将玩家当前正对方块的坐标自动填进去。
> 通过更改[聊天设置](https://minecraft.fandom.com/zh/wiki/%E9%80%89%E9%A1%B9#%E8%81%8A%E5%A4%A9%E8%AE%BE%E7%BD%AE)，聊天框的尺寸可以缩小，透明度也可以调节，甚至可以完全隐藏。

> 命令/locate
> < [命令](https://minecraft.fandom.com/zh/wiki/%E5%91%BD%E4%BB%A4)
> [编辑](https://minecraft.fandom.com/zh/wiki/%E5%91%BD%E4%BB%A4/locate?action=edit)
> locate
> 需要的[权限等级](https://minecraft.fandom.com/zh/wiki/%E5%91%BD%E4%BB%A4#%E6%9D%83%E9%99%90%E7%AD%89%E7%BA%A7)	
> [Java版](https://minecraft.fandom.com/zh/wiki/Java%E7%89%88)：2
> [基岩版](https://minecraft.fandom.com/zh/wiki/%E5%9F%BA%E5%B2%A9%E7%89%88)：1
> 
> [限制条件](https://minecraft.fandom.com/zh/wiki/%E5%91%BD%E4%BB%A4#%E9%99%90%E5%88%B6%E6%9D%A1%E4%BB%B6)	
> 启用作弊[仅[基岩版](https://minecraft.fandom.com/zh/wiki/%E5%9F%BA%E5%B2%A9%E7%89%88)]
> 在聊天框中为命令执行者显示给定类型结构、[生物群系](https://minecraft.fandom.com/zh/wiki/%E7%94%9F%E7%89%A9%E7%BE%A4%E7%B3%BB)或[兴趣点](https://minecraft.fandom.com/zh/wiki/%E5%85%B4%E8%B6%A3%E7%82%B9%E6%96%87%E4%BB%B6%E6%A0%BC%E5%BC%8F)[仅[Java版](https://minecraft.fandom.com/zh/wiki/Java%E7%89%88)]的最近坐标和距离。在[Java版](https://minecraft.fandom.com/zh/wiki/Java%E7%89%88)中，返回的坐标可以点击以自动在聊天框中输入/[tp](https://minecraft.fandom.com/zh/wiki/%E5%91%BD%E4%BB%A4/tp) `@s `坐标。

那看起来应该是“聊天框”

2023-01-20 05:55 UTC, mamaruo commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"option.NoChatReports.showEncryptionButton.tooltip": "若配置为false，仅会在聊天界面中隐藏加密按钮。注意：加密选项本身并不会随之关闭。",
Here

https://github.com/CFPAOrg/Glossary/blob/104816b3d8ff6520dccdba9ab5a8a51b68c31546/Minecraft%20Vanilla%201.18.2.csv#L2013

2023-01-20 10:20 UTC, dovisutu commented on projects/1.19/assets/no-chat-reports/nochatreports/lang/zh_cn.json
> +	"option.NoChatReports.showEncryptionButton.tooltip": "若配置为false，仅会在聊天界面中隐藏加密按钮。注意：加密选项本身并不会随之关闭。",
confirmed
那估计聊天框是下面那个文本框.......

2023-01-20 10:21 UTC, dovisutu commented
/replace "聊天框" "聊天屏幕"

2023-01-20 15:41 UTC, mamaruo approved these changes

2023-01-21 08:59 UTC, dovisutu commented
[1.19.3](https://minecraft.fandom.com/zh/wiki/Java%E7%89%881.19.3)
> 调整了聊天消息信任状态的标识：
> 仅被服务器改动样式的消息不再显示“被修改”标识。
> “被修改”标识的图标和指示色块的颜色改为深灰色。
> “不安全”标识的指示色块的颜色改为淡灰色，并取消了其对应的图标。

......离谱 看来还得把那几个色块改回去，毕竟资源包的目标版本是1193

2023-01-21 10:23 UTC, mamaruo approved these changes

2023-01-23 17:32 UTC, merged