NoFog 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2843
Opened 2023-01-21 04:55 UTC by zkitefly

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-01-21 10:10 UTC, mamaruo requested changes

2023-01-21 10:10 UTC, mamaruo commented on projects/1.19/assets/nofog/no_fog/lang/zh_cn.json
> +  "text.no_fog.config.category.biomes": "生物特征设置",
什tm生物特征

2023-01-21 10:10 UTC, mamaruo commented on projects/1.19/assets/nofog/no_fog/lang/zh_cn.json
> +  "text.no_fog.config.darkness_fog": "启用黑暗烟雾"
为什么突然冒出个“烟”

2023-01-21 15:40 UTC, zkitefly commented on projects/1.19/assets/nofog/no_fog/lang/zh_cn.json
> +  "text.no_fog.config.category.biomes": "生物特征设置",
已改成“生物群系设置”

2023-01-21 15:40 UTC, zkitefly commented on projects/1.19/assets/nofog/no_fog/lang/zh_cn.json
> +  "text.no_fog.config.darkness_fog": "启用黑暗烟雾"
输入法问题（

2023-01-21 15:41 UTC, zkitefly commented on projects/1.19/assets/nofog/no_fog/lang/zh_cn.json
> +  "text.no_fog.config.darkness_fog": "启用黑暗烟雾"
但感觉“启用黑暗雾”感觉太别扭了（

要不我改成“启用黑暗效果雾”？

2023-01-21 15:48 UTC, zkitefly commented
感觉“启用黑暗雾”感觉太别扭了（

要不我改成“启用黑暗效果雾”？

2023-01-21 15:54 UTC, mamaruo submitted a review, later dismissed

2023-02-05 17:05 UTC, Ricky-fight reviewed
这`darkness`和[原版](https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96)里的黑暗效果是否有联系？

2023-02-05 17:08 UTC, Ricky-fight requested changes

2023-02-05 17:08 UTC, Ricky-fight commented on projects/1.19/assets/nofog/no_fog/lang/zh_cn.json
> +  "text.no_fog.config.thick_fog.tooltip": "（例如 boss 雾或下界雾）",
```suggestion
  "text.no_fog.config.thick_fog.tooltip": "（例如Boss雾或下界雾）",
```

2023-02-05 17:08 UTC, Ricky-fight commented on projects/1.18/assets/nofog/no_fog/lang/zh_cn.json
> +  "text.no_fog.config.thick_fog.tooltip": "（例如 boss 雾或下界雾）",
```suggestion
  "text.no_fog.config.thick_fog.tooltip": "（例如Boss雾或下界雾）",
```

2023-02-05 17:08 UTC, Ricky-fight commented on projects/1.16/assets/nofog/no_fog/lang/zh_cn.json
> +  "text.no_fog.config.thick_fog.tooltip": "（例如 boss 雾或下界雾）",
```suggestion
  "text.no_fog.config.thick_fog.tooltip": "（例如Boss雾或下界雾）",
```

2023-04-01 07:23 UTC, ChuijkYahus commented
* 7+7时限进入第二阶段，请注意查收各审核意见

@zkitefly

2023-04-08 03:22 UTC, ChuijkYahus commented
* 7+7时限进入第二阶段，请注意查收各审核意见

@zkitefly

2023-05-20 05:19 UTC, closed without merging