Iron Furnaces 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #2844
Opened 2023-01-21 08:57 UTC by mamaruo

Credit: https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/projects/1.18/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json 

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-01-22 06:53 UTC, DrIceTea123 requested changes
除了这些，有关`熔炉升级->熔炉升级件` `熔炉组件->强化件`的更改可能还是要再斟酌一下
一方面是原译名已经用惯了（只对我自己而言），另一方面（比较重要的）是单一个`件`字感觉怪怪的，从我个人角度来说叫`组件`更合适一点
当然还是要看看其他人的意见

2023-01-22 06:53 UTC, DrIceTea123 commented on projects/1.16/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
> +  "tooltip.ironfurnaces.gui_redstone_comparator_sub": "带作差功能的比较器",
直接叫`作差模式比较器`或者`作差比较器`或者`比较器（作差模式）`怎么样

2023-01-22 06:53 UTC, DrIceTea123 commented on projects/1.16/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
> +  "ironfurnaces.update.speech": "[{\"text\":\"更多熔炉（Iron Furnaces）\",\"color\":\"dark_green\"},{\"text\":\"更多熔炉\"},{\"text\":\"可用！\",\"color\":\"none\"}]",
更新说明被吃掉里（）

2023-01-22 06:53 UTC, DrIceTea123 commented on projects/1.16/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
> +  "ironfurnaces.update.failed": "[{\"text\":\"更多熔炉（Iron Furnaces）\",\"color\":\"dark_green\"},{\"text\":\"更多熔炉\"},{\"text\":\"失败！查看日志以获取更多信息！\",\"color\":\"none\"}]"
这里`检测更新失败`也被吃掉了

2023-01-22 06:53 UTC, DrIceTea123 commented on projects/1.16/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
> +  "container.ironfurnaces.wireless_energy_heater": "无线加热器",
使用环境为L45的GUI界面，要不要用一样的名字
如果`无线热能供应器->无线加热器`成立，L11`无线热能接收器`要不要改

2023-01-23 03:27 UTC, mamaruo commented
> 除了这些，有关`熔炉升级->熔炉升级件` `熔炉组件->强化件`的更改可能还是要再斟酌一下 一方面是原译名已经用惯了（只对我自己而言），另一方面（比较重要的）是单一个`件`字感觉怪怪的，从我个人角度来说叫`组件`更合适一点 当然还是要看看其他人的意见

`组件`二字没有把原词的`提升强化`的意义表现出来，而且它和component有歧义。

`升级`不是名词。

折衷的话可以用`强化组件` `升级组件`来代替

2023-01-23 05:27 UTC, DrIceTea123 commented
> > 除了这些，有关`熔炉升级->熔炉升级件` `熔炉组件->强化件`的更改可能还是要再斟酌一下 一方面是原译名已经用惯了（只对我自己而言），另一方面（比较重要的）是单一个`件`字感觉怪怪的，从我个人角度来说叫`组件`更合适一点 当然还是要看看其他人的意见
> 
> `组件`二字没有把原词的`提升`、`强化`的意义表现出来，而且它和 component（可被组装或被重新组装的几个部件之一）有歧义。
> 
> `升级`不是名词。
> 
> 折衷的话可以用`强化组件` `升级组件`来代替

我觉得可以，`强化组件` `升级组件`很合适
另外的话，有一些mod比如`精致存储` `应用能源2` `Storage Drawers`中也有类似的翻译`upgrade->升级`，可能也需要修改

2023-01-24 09:14 UTC, mamaruo commented on projects/1.16/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
> +  "container.ironfurnaces.wireless_energy_heater": "无线加热器",
原文如此，两处原文不一样，这个地方是作者的bug，1.18就改正确了

2023-01-24 09:21 UTC, DrIceTea123 commented on projects/1.16/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
> +  "container.ironfurnaces.wireless_energy_heater": "无线加热器",
那不一样也行

2023-01-24 13:08 UTC, DrIceTea123 requested changes
我没啥别的建议了
关于`升级->升级组件`在其他模组中的修改也要考虑一下

2023-01-24 13:08 UTC, DrIceTea123 commented on projects/1.18/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
> +  "tooltip.ironfurnaces.gui_redstone_comparator_sub": "带作差功能的比较器",
1.16改成`比较器（作差模式）`了，这里没改

2023-01-24 13:08 UTC, DrIceTea123 commented on projects/1.19/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
> +  "tooltip.ironfurnaces.gui_redstone_comparator_sub": "带作差功能的比较器",
这里同上，要改成`比较器（作差模式）`了

2023-01-24 15:15 UTC, DrIceTea123 commented
`比较器（作差模式）`还是`比较器作差模式`
1.19的更改又把括号删了

2023-01-25 05:13 UTC, DrIceTea123 approved these changes
那应该没什么问题了吧

2023-02-09 13:33 UTC, Ricky-fight approved these changes

2023-02-09 13:33 UTC, Ricky-fight commented on projects/1.16/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
>    "item.ironfurnaces.augment_blasting": "强化组件：高炉",
那这里需要去掉吗？

2023-02-18 10:17 UTC, mamaruo commented on projects/1.16/assets/iron-furnaces/ironfurnaces/lang/zh_cn.json
>    "item.ironfurnaces.augment_blasting": "强化组件：高炉",
去掉什么

2023-04-02 10:10 UTC, merged