提交千里冰封（Frozen Up）模组汉化，it_it.json语言文件为mod自带
CFPAOrg/Minecraft-Mod-Language-Package pull request #2851
Opened 2023-01-23 06:38 UTC by qyyyy09315

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-01-23 07:12 UTC, TexBlock commented
翻译pr中不应包含除英语（en_us.json）和简体中文（zh_cn.json）的其他本地化文件

2023-01-23 07:14 UTC, xfl03 commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "advancements.frozenup.retrieve_item_from_tamed_chilloo.title" : "挖开吧！",
能解释一下为什么是挖开？挖开寒猹的身体/战利品吗？

2023-01-23 07:14 UTC, xfl03 commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "advancements.frozenup.drink_mug.description" : "用马克杯来喝",
喝后面可以补充一下宾语

2023-01-23 07:14 UTC, xfl03 commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "advancements.frozenup.obtain_truffle.title" : "从没有松露",
是“从没有松露到有松露”还是“从来没有松露”，请补充成分

2023-01-23 07:14 UTC, xfl03 commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "advancements.frozenup.cloud_jumper_boost.title": "冲过……天空？",
为什么是“冲过”而不是“冲向”？

2023-01-23 07:14 UTC, xfl03 commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "item.frozenup.mug_of_milk": "杯装奶",
为什么上面两个没有“杯装”，翻译不统一

2023-01-23 07:14 UTC, xfl03 commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "block.frozenup.compacted_snow_brick_vertical_slab": "压实雪砖竖半砖",
竖台阶？我也不确定这个要怎么翻译

2023-01-23 07:14 UTC, xfl03 commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "block.frozenup.mug_of_truffle_hot_chocolate": "松露热巧克力",
同上，翻译不统一

2023-01-23 07:14 UTC, xfl03 commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "subtitles.entity.frozenup.reindeer.angry": "驯鹿：不安",
不是愤怒？

2023-01-23 07:14 UTC, xfl03 commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "subtitles.frozenup.block.chilloo_feather_lamp.toggle_on": "灯打开",
开灯

2023-01-23 07:14 UTC, xfl03 commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "subtitles.frozenup.block.chilloo_feather_lamp.toggle_off": "灯熄灭",
关灯

2023-01-23 07:44 UTC, qyyyy09315 commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "advancements.frozenup.retrieve_item_from_tamed_chilloo.title" : "挖开吧！",
这个地方原文为mine now，我重新写一下这项

2023-01-23 08:02 UTC, qyyyy09315 commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "block.frozenup.compacted_snow_brick_vertical_slab": "压实雪砖竖半砖",
这些物品在游戏中并没有找到，这是按照一般译法

2023-01-23 08:15 UTC, qyyyy09315 commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "block.frozenup.compacted_snow_brick_vertical_slab": "压实雪砖竖半砖",
“竖半砖”这一类物品只有在语言文件里的名字而没有在游戏里的对应方块

2023-01-23 08:21 UTC, TexBlock commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "block.frozenup.compacted_snow_brick_vertical_slab": "压实雪砖竖半砖",
> “竖半砖”这一类物品只有在语言文件里的名字而没有在游戏里的对应方块

这好像是与夸克的联动

![image](https://user-images.githubusercontent.com/65154269/213993672-f5068694-70ec-40f1-b6dd-9d50ae12b59a.png)

2023-01-23 08:54 UTC, qyyyy09315 commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "block.frozenup.compacted_snow_brick_vertical_slab": "压实雪砖竖半砖",
我看了一下联动的那个方块内容，确实是竖起来的半砖。夸克mod对于这种方块采用“竖直台阶”的译法，此处沿用。

2023-01-23 10:41 UTC, ChuijkYahus commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "subtitles.item.block.mug.drink": "喝"
```suggestion
  "subtitles.frozenup.block.chilloo_feather_lamp.toggle_on": "灯：打开",
  "subtitles.frozenup.block.chilloo_feather_lamp.toggle_off": "灯：关闭",
  "subtitles.item.block.mug.drink": "饮用"
```
当然最后一项看声音整成`啜饮`应该也没有问题
https://minecraft.fandom.com/zh/wiki/%E5%AD%97%E5%B9%95

2023-01-23 10:41 UTC, ChuijkYahus commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "frozenup.commands.locate.revamped_igloo": "使用 /locate structure frozenup:revamped_igloo",
```suggestion
  "frozenup.commands.locate.revamped_igloo": "使用/locate structure frozenup:revamped_igloo",
```

2023-01-23 10:41 UTC, ChuijkYahus commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "block.frozenup.cut_ice_cube_wall": "切冰块墙",
```suggestion
  "block.frozenup.cut_ice": "切制冰",
  "block.frozenup.cut_ice_stairs": "切制冰楼梯",
  "block.frozenup.cut_ice_slab": "切制冰台阶",
  "block.frozenup.cut_ice_cubes": "切制冰块",
  "block.frozenup.cut_ice_cube_stairs": "切制冰块楼梯",
  "block.frozenup.cut_ice_cube_slab": "切制冰块台阶",
  "block.frozenup.cut_ice_cube_wall": "切制冰块墙",
```

2023-01-23 10:41 UTC, ChuijkYahus commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "block.frozenup.cut_ice_cube_vertical_slab": "切冰块竖直台阶",
```suggestion
  "block.frozenup.cut_ice_vertical_slab": "切制冰竖直台阶",
  "block.frozenup.cut_ice_cube_vertical_slab": "切制冰块竖直台阶",
```

2023-01-23 15:02 UTC, qyyyy09315 commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "subtitles.item.block.mug.drink": "喝"
这一处开灯/关灯是一开始一位维护者提出，暂时保留
“喝”这一项我觉得“啜饮”更好
其他建议我都赞同并修改完毕
谢谢你的建议！

2023-01-23 17:37 UTC, mamaruo commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "subtitles.item.block.mug.drink": "喝"
字幕采用 `发声主体：声音` 格式，这里的建议更好。

`灯：开灯` 显然不行

2023-01-23 18:26 UTC, mamaruo requested changes

2023-01-23 18:26 UTC, mamaruo commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "advancements.frozenup.retrieve_item_from_tamed_chilloo.title" : "挖开吧！",
[anders x Kevin Rolly - Mine Now (Official Audio) - YouTube](https://www.youtube.com/watch?v=vPtZC9NEijI)

2023-01-23 18:26 UTC, mamaruo commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "subtitles.entity.frozenup.reindeer.cloud_jump": "驯鹿：云跃",
| **审查级别** |
|--------------|
| ℹ️ 信息 / 不阻止合并  |
```suggestion
  "subtitles.entity.frozenup.reindeer.cloud_jump": "驯鹿：云跃",
```

这个 elevate 属实没看懂，它也没有直接的“跳跃”含义，哪跟哪啊

`云跃` 就突出一个云里雾里

原文：**Reindeer elevates**

2023-01-23 18:26 UTC, mamaruo commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "subtitles.entity.frozenup.penguin.idle": "企鹅：尖锐地叫",
| **审查级别**    | 备注 |
|--------------|----|
| ⚪ 轻微 / 不阻止合并但需三思  |    |
```suggestion
  "subtitles.entity.frozenup.penguin.idle": "企鹅：嘶鸣",
```

总觉得在说马叫，看着办吧

原文：**Penguin squawks**

2023-01-23 18:26 UTC, mamaruo commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "subtitles.frozenup.entity.chilloo.ambient": "寒猹：啾啾叫",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |
```suggestion
  "subtitles.frozenup.entity.chilloo.ambient": "寒猹：高兴地啾啾叫",
```

原版：
https://github.com/CFPAOrg/Glossary/blob/104816b3d8ff6520dccdba9ab5a8a51b68c31546/Minecraft%20Vanilla%201.18.2.csv#L4620

原文：**Chilloo chirps happily**

2023-01-24 04:07 UTC, qyyyy09315 commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "subtitles.item.block.mug.drink": "喝"
如果使用灯:打开或者灯:被打开呢
参见我的世界wiki“活板门:打开”
[]()https://minecraft.fandom.com/zh/wiki/%E5%AD%97%E5%B9%95

2023-01-24 04:13 UTC, qyyyy09315 commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "subtitles.entity.frozenup.penguin.idle": "企鹅：尖锐地叫",
这个位置就是企鹅在一般情况下的叫声

2023-01-24 04:16 UTC, qyyyy09315 commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "advancements.frozenup.drink_mug.title" : "你得到了马克杯",
这一位置感觉是英语中的谐音梗

2023-01-24 04:21 UTC, mamaruo commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "subtitles.item.block.mug.drink": "喝"
> 如果使用灯:打开或者灯:被打开呢 参见我的世界wiki“活板门:打开” https://minecraft.fandom.com/zh/wiki/%E5%AD%97%E5%B9%95

那就是chuijk 的建议

2023-01-24 04:21 UTC, qyyyy09315 commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "subtitles.entity.frozenup.reindeer.cloud_jump": "驯鹿：云跃",
elevate （formal)使情绪高昂；使精神振奋；使兴高采烈 to improve a person's mood, so that they feel happy

2023-01-24 04:49 UTC, qyyyy09315 commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "subtitles.entity.frozenup.reindeer.jump": "驯鹿：跳跃",
游戏中的动作更接近“抬起前腿”

2023-01-24 04:51 UTC, mamaruo commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "subtitles.entity.frozenup.reindeer.jump": "驯鹿：跳跃",
那么第一个和第三个建议都还行，看着办

2023-01-24 04:54 UTC, qyyyy09315 commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "item.frozenup.empty_mug": "空马克杯",
“马克杯”。鉴于原版中对于碗（bowl）没有强调“空”碗

2023-01-24 04:56 UTC, qyyyy09315 commented on projects/1.19/assets/frozen-up/frozenup/lang/zh_cn.json
> +  "subtitles.entity.frozenup.reindeer.jump": "驯鹿：跳跃",
“抬起前腿”。游戏中驯鹿并没有站的动作，或者说只是抬起腿，短时间后就放下

2023-01-24 09:44 UTC, mamaruo approved these changes

2023-01-26 09:03 UTC, merged