The Farlanders 汉化提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #2876
Opened 2023-01-25 01:35 UTC by Ecdcaeb

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x] 刷新 PR 的标签/状态，有需要再点击；

#2875错误提交了main。

2023-01-25 04:21 UTC, mamaruo commented
不要再发 PR 了…… 先封你一天冷静冷静

2023-07-22 11:56 UTC, luoxueyasha requested changes

2023-07-22 11:56 UTC, luoxueyasha commented on projects/1.12.2/assets/farlanders/farlanders/lang/zh_cn.lang
> +advancement.cleaning_the_dust.desc=拿着沙子或泥土，杀死的经典末影人。
```suggestion
advancement.cleaning_the_dust.desc=拿着沙子或泥土，杀死一只经典末影人。
```
语句不通顺
此类问题请全文通查

2023-07-22 11:56 UTC, luoxueyasha commented on projects/1.12.2/assets/farlanders/farlanders/lang/zh_cn.lang
> +advancement.abra_kadabra=好的，勇基拉
原梗：https://en.wikipedia.org/wiki/Abra_Kadabra_(character)
请再考虑一下译文

2023-07-30 10:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2876) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2876) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2876) it.</sub>

2023-08-04 07:45 UTC, luoxueyasha commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。
@Ecdcaeb

2023-08-10 03:38 UTC, Cactusstudent commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@Ecdcaeb

2023-08-13 00:31 UTC, luoxueyasha commented
- 该提交由于[7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)将被关闭，请知晓。若仍想维护可选择Reopen此提交或重新打开新提交，并查看本提交内的审查意见并进行更改。
@Ecdcaeb

2023-08-14 03:49 UTC, closed without merging