AE2 部分附属更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #2892
Opened 2023-01-26 15:43 UTC by ChuijkYahus

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

多出的键已经测试可以使用

2023-03-23 10:52 UTC, DrIceTea123 commented
为啥Mega Cells的语言文件zh_cn比en_us多……

2023-03-23 14:52 UTC, ChuijkYahus commented
> 为啥Mega Cells的语言文件zh_cn比en_us多……

游戏内实测是有这些物品存在的，但是英文里不知道为什么没有
中文经测试可以正常显示，但英文环境没测试过

那些化学品的键是MEGACells和AppMek的联动，对应Mekanism
魔力的键是和AppBot的联动，对应Botania

2023-03-23 18:14 UTC, DrIceTea123 requested changes
Mega Cells多的几个键还是得看一下英文语言环境下的游戏表现
<del>（要是英文直接显示的是键名就不急着翻译了）</del>
别的问题应该没啥

2023-03-23 18:14 UTC, DrIceTea123 commented on projects/1.19/assets/mega-cells/megacells/lang/zh_cn.json
> +  "item.megacells.radioactive_chemical_cell": "MEGA放射性化学品存储元件",
这两行应该对应的是差不多的物品，是不是名字也统一一下

2023-03-24 01:20 UTC, ChuijkYahus commented on projects/1.19/assets/mega-cells/megacells/lang/zh_cn.json
> +  "item.megacells.radioactive_chemical_cell": "MEGA放射性化学品存储元件",
为漏改，已修正

2023-03-25 17:27 UTC, ChuijkYahus commented
> Mega Cells多的几个键还是得看一下英文语言环境下的游戏表现 ~（要是英文直接显示的是键名就不急着翻译了）~ 别的问题应该没啥

已经测试，都是键名
但是这些键插进去是正常显示中文的（）

2023-03-27 07:25 UTC, DrIceTea123 approved these changes
那没啥问题了吧
<del>（英文都没有的键为啥要翻译）</del>

2023-05-31 10:04 UTC, dovisutu approved these changes

2023-05-31 10:04 UTC, merged