Mekanism 翻译修补
CFPAOrg/Minecraft-Mod-Language-Package pull request #2914
Opened 2023-01-28 03:41 UTC by ZHAY10086

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-03-23 10:38 UTC, DrIceTea123 commented
mek真是个大模组……
因为这是个高版本向低版本的同步，我花了一下午把库里新版本的译文和本pr的译文比对了一下，列了个表，你可以先按照下面这些改一下
没提到的就是译文完全一致/没有异议的内容

**原文一致-译文不同的列表：**
<img width="1038" alt="1" src="https://user-images.githubusercontent.com/111784151/227177609-f9b913e6-64af-4fe5-90a5-feb41bf6c35c.png">

**原文相似-译文不同的列表（相似的原文和译文仅供参考）：**
<img width="1586" alt="2" src="https://user-images.githubusercontent.com/111784151/227177774-893ec8d7-0bc5-49ec-b264-4f89c790edbc.png">

**yua原文未找到列表：**
<img width="954" alt="3" src="https://user-images.githubusercontent.com/111784151/227177838-bec115ac-4f34-49ce-833f-540547cf6fa4.png">

注：原文未找到的部分里我看很多都是发电机的内容，好像是在高版本做成单独的模组了，我看哪天有空再去比对一下

2023-03-25 04:34 UTC, ZHAY10086 commented
个人见解：
1.12.2使用`矿典转换器`，高版本使用`标签转换器`。原因：1.12.2没有标签系统。

2023-04-01 10:36 UTC, DrIceTea123 requested changes
再次审了一下，顺便把高版本的三个扩展模组`Mekanism Additions` `Mekanism Generators` `Mekanism Tools`也导了进来做对比
既然高版本已经做了修改，高版本的翻译问题我就顺便也标上了（）

顺便，`Mekanism Generators`和`Mekanism Tools`的翻译已经过时，如果有时间的话可以顺便把这两个模组也焊了（）

2023-04-01 10:36 UTC, DrIceTea123 commented on projects/1.12.2/assets/mekanism/mekanism/lang/zh_cn.lang
> +item.WalkieTalkie.name=步话机
高版本译名为`对讲机`，来自Mekanism Additions模组，键名`item.mekanismadditions.walkie_talkie`

2023-04-01 10:36 UTC, DrIceTea123 commented on projects/1.12.2/assets/mekanism/mekanism/lang/zh_cn.lang
> +gui.turbineStats=涡轮数据
高版本译名`涡轮参数`，来自Mekanism Generators模组，键名`turbine.mekanismgenerators.stats`

2023-04-01 10:36 UTC, DrIceTea123 commented on projects/1.12.2/assets/mekanism/mekanism/lang/zh_cn.lang
> +tooltip.walkie_disabled=声音服务器已禁用。
高版本译名`语音服务器已禁用。`，来自Mekanism Additions模组，键名`walkie.mekanismadditions.disabled`

2023-04-01 10:36 UTC, DrIceTea123 commented on projects/1.12.2/assets/mekanism/mekanism/lang/zh_cn.lang
>  tooltip.readyForReaction=已准备好反应
高版本译名`反应已就绪！`，来自Mekanism Generators模组，键名`tooltip.mekanismgenerators.hohlraum.ready_for_reaction`

2023-04-01 10:36 UTC, DrIceTea123 commented on projects/1.12.2/assets/mekanism/mekanism/lang/zh_cn.lang
> +tooltip.WindGenerator=一种利用风的强度产生能量的发电机, 在较高的地方效率更高。
高版本译名如下，来自Mekanism Generators模组，原文完全相同，键名`description.mekanismgenerators.wind_generator`
```suggestion
tooltip.WindGenerator=一种利用风力产生能量的发电机, 在较高的地方效率更高。
```

2023-04-01 10:36 UTC, DrIceTea123 commented on projects/1.12.2/assets/mekanism/mekanism/lang/zh_cn.lang
> +tooltip.TurbineRotor=放置在工业涡轮中的钢质转子。
高版本译名如下，来自Mekanism Generators模组，原文完全相同，键名`description.mekanismgenerators.turbine_rotor`
```suggestion
tooltip.TurbineRotor=放置在工业涡轮中的钢制转子。
```

2023-04-01 10:36 UTC, DrIceTea123 commented on projects/1.12.2/assets/mekanism/mekanism/lang/zh_cn.lang
> +tooltip.SaturatingCondenser=一块可以将工业涡轮机产生的蒸汽处理成水的方块。 可以放置在复杂旋钮装置上任意位置。
高版本译名如下，来自Mekanism Generators模组，原文完全相同，键名`description.mekanismgenerators.saturating_condenser`
```suggestion
tooltip.SaturatingCondenser=一个可以将工业涡轮机产生的蒸汽处理成水的方块。可以放置在复杂旋钮装置上任意位置。
```

2023-04-01 10:36 UTC, DrIceTea123 commented on projects/1.12.2/assets/mekanism/mekanism/lang/zh_cn.lang
> +sideData.Infuse=注入
可能是`灌注类型`，高版本可能的键名`transmission.mekanism.infuse_types`

2023-04-01 10:36 UTC, DrIceTea123 commented on projects/1.12.2/assets/mekanism/mekanism/lang/zh_cn.lang
>  cmd.mek.chunk.watch=区块 %d，已将 %d 添加到监视列表
依据高版本译名的推荐译文如下，相关键名`command.mekanism.chunk.watch`
```suggestion
cmd.mek.chunk.watch=区块 %d 和 %d 已添加到监视列表中
```

2023-04-01 10:36 UTC, DrIceTea123 commented on projects/1.18/assets/mekanism/mekanism/lang/zh_cn.json
> +  "multiblock.mekanism.formed.chat": "多方块结构已成形",
此处更改未在1.16同步，1.16文件对应行为L1148

2023-04-01 14:09 UTC, ZHAY10086 commented on projects/1.18/assets/mekanism/mekanism/lang/zh_cn.json
> +  "multiblock.mekanism.formed.chat": "多方块结构已成形",
抱歉抱歉，改的时候版本看晕了，有些没同步更改

2023-04-01 14:33 UTC, ZHAY10086 commented on projects/1.12.2/assets/mekanism/mekanism/lang/zh_cn.lang
> +gui.lastItem=下个物品
草，还真是，都没注意看

2023-04-01 15:00 UTC, ZHAY10086 commented on projects/1.12.2/assets/mekanism/mekanism/lang/zh_cn.lang
> +gui.usage=消耗
1.18那里应该是翻错了

2023-04-01 15:11 UTC, ZHAY10086 commented on projects/1.18/assets/mekanism/mekanism/lang/zh_cn.json
> +  "description.mekanism.induction_provider": "一种先进的冷却系统、导体和变压器组合方块，能够提高输导矩阵的最大能量转移速度。",
此处是批量替换时误替换了，原文是Energised Induction Matrix

2023-04-02 06:08 UTC, DrIceTea123 approved these changes
我这应该没啥问题了

如果有时间的话顺便把Mekanism Generators和Mekanism Additions的汉化更新了吧（）

2023-04-02 07:41 UTC, ZHAY10086 commented
我之后看看有没有时间吧

2023-04-17 16:44 UTC, ChuijkYahus approved these changes

2023-04-19 01:44 UTC, merged