RFTools 修补
CFPAOrg/Minecraft-Mod-Language-Package pull request #2929
Opened 2023-01-29 13:04 UTC by ZHAY10086

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-08 06:44 UTC, DrIceTea123 requested changes
差不多就这些……？

2023-02-08 06:44 UTC, DrIceTea123 commented on projects/1.12.2/assets/rftools/rftools/lang/zh_cn.lang
> +advancements.rftools.builder.description=建筑工人鲍勃！
`Bob The Builder`：中文名`巴布工程师`，著名卡通节目<del>（我的童年）</del>

2023-02-08 06:44 UTC, DrIceTea123 commented on projects/1.12.2/assets/rftools/rftools/lang/zh_cn.lang
> +advancements.rftools.firstteleport.title=世界移动了！ @todo
全角标点与其他符号间不留空格

2023-02-08 06:44 UTC, DrIceTea123 commented on projects/1.12.2/assets/rftools/rftools/lang/zh_cn.lang
> +item.storage_module2.name=终级储存舱
`Storage Module`是不是应该翻译成`存储模块`而不是`储存舱`

2023-02-08 06:44 UTC, DrIceTea123 commented on projects/1.12.2/assets/rftools/rftools/lang/zh_cn.lang
> +item.peace_essence.name=和平要素
`Peace Essence`是否是`和平元素`或者`和平精华`

2023-02-08 06:44 UTC, DrIceTea123 commented on projects/1.12.2/assets/rftools/rftools/lang/zh_cn.lang
> +    @f一些机器节流（甚至禁用）。
似乎有点不通顺
```suggestion
message.rftools.relay=\
    @f这台设备可以（基于红石信号）\n\
    @f限制通过它的 RF 量。\n\
    @f当能量不足时，你可以用它减速\n\
    @f（甚至禁用）一部分机器。
```

2023-02-08 06:44 UTC, DrIceTea123 commented on projects/1.12.2/assets/rftools/rftools/lang/zh_cn.lang
> +    @f来进行不同的逻辑操作
加个“的”似乎会通顺一点
```suggestion
message.rftools.threelogic=\
    @f该逻辑方块能利用它的三个输入\n\
    @f来进行不同的逻辑操作
```

2023-02-08 07:07 UTC, ZHAY10086 commented on projects/1.12.2/assets/rftools/rftools/lang/zh_cn.lang
> +advancements.rftools.builder.description=建筑工人鲍勃！
感谢感谢

2023-02-08 07:25 UTC, ZHAY10086 commented on projects/1.12.2/assets/rftools/rftools/lang/zh_cn.lang
> +item.peace_essence.name=和平要素
`和平精华`应该更好些

2023-02-16 05:41 UTC, DrIceTea123 requested changes

2023-02-16 05:41 UTC, DrIceTea123 commented on projects/1.12.2/assets/rftools/rftools/lang/zh_cn.lang
> +    @e提升工作速率
这里的内容是不是应该用顿号

2023-02-16 10:00 UTC, ZHAY10086 commented on projects/1.12.2/assets/rftools/rftools/lang/zh_cn.lang
> +    @e提升工作速率
已改

2023-02-20 15:17 UTC, DrIceTea123 approved these changes
应该没啥问题了吧……

2023-03-12 17:08 UTC, mamaruo commented on projects/1.12.2/assets/rftools/rftools/lang/zh_cn.lang
> +    @f并当达到固定数值时发出红石信号
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |

原文：****
```suggestion
    @f该逻辑方块对红石脉冲进行计数\n\
    @f并当达到某一特定数值时发出红石信号
```

2023-04-07 15:17 UTC, mamaruo approved these changes
看完了

2023-04-07 15:17 UTC, mamaruo commented on projects/1.12.2/assets/rftools/rftools/lang/zh_cn.lang
> +    @来生产 RF (%s RF/t)\n\
| **审查级别**    | 备注 |
|--------------|----|
| ⚪ 轻微 / 不阻止合并但需三思  |    |

原文：****
```suggestion
    @f这台机器使用煤炭或木炭\n\
    @来生产 RF（%s RF/t）\n\
```

2023-04-07 15:17 UTC, mamaruo commented on projects/1.12.2/assets/rftools/rftools/lang/zh_cn.lang
> +    @6测量过的物质传输器来扫描
| **审查级别**    | 备注 |
|--------------|----|
| ⚪ 轻微 / 不阻止合并但需三思  |    |

原文：** dialed matter transmitter which should be\n\
    located above it**
    
确定是测量过的？

2023-04-07 15:17 UTC, mamaruo commented on projects/1.12.2/assets/rftools/rftools/lang/zh_cn.lang
> +    @a内容：%s 堆\n\
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |

原文：**    @aContents: %s stacks\n\**

？

2023-04-08 01:34 UTC, ZHAY10086 commented on projects/1.12.2/assets/rftools/rftools/lang/zh_cn.lang
> +    @来生产 RF (%s RF/t)\n\
感谢

2023-04-08 01:40 UTC, ZHAY10086 commented on projects/1.12.2/assets/rftools/rftools/lang/zh_cn.lang
> +    @a内容：%s 堆\n\
感谢纠误

2023-04-08 01:49 UTC, ZHAY10086 commented on projects/1.12.2/assets/rftools/rftools/lang/zh_cn.lang
> +    @6测量过的物质传输器来扫描
改成`已建立链接`了

2023-04-09 07:29 UTC, merged