wonderful-enchantments 1.16 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #2940
Opened 2023-01-31 09:37 UTC by Summe-rsnow

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-01 04:57 UTC, DrIceTea123 requested changes
注意：本pr存在部分机翻嫌疑。本项目对机翻并不友好，若为机翻，请自行关闭pr，或进行人工润色调整。
> 本pr的机翻嫌疑包括但不仅限于：
> - pillager（掠夺者）->抢劫者 [L9]
> - Guardian（守卫者）->守护者 [L38]
> - inventory（物品栏）->库存 [L50,51]
> - Absorption（伤害吸收）->吸收 [L65,66]
> - blocks（方块）->区块 [L70,71]
> - owner（所有者）->主人 [L88,89]
> - Crafting Table（工作台）->合成栏 [L96]

鉴于该作者为第一次提交pr，若不是机翻，请先对以上内容进行修改，并对其他未提到的内容进行翻译润色，使其不会过于生硬。如有疑问，可以加入我们的qq群进行讨论：630943368

2023-02-02 18:53 UTC, DrIceTea123 requested changes
行，大半夜赶来看一眼
> - 不要望文生义，有些看起来十分离谱的东西可能是正确的。

有些地方有点过度翻译，我都把原文复制过来了，你大概看着改，<del>因为我自己水平也不高</del>

2023-02-02 18:53 UTC, DrIceTea123 commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.phoenix_dive.desc": "从高处坠落会释放火焰冲击波，造成范围伤害，并点燃附近的敌人。触发后如果立刻使用潜行，将可以跳得更高，但靴子会消耗更多的耐久度。",
原文：`Fall from a height causes the release of a wave of fire which damages and sets nearby enemies on fire. Also while you hold the sneak key (def. SHIFT) you will jump higher!`
前半段没啥问题，后半段是不是译多了

2023-02-02 18:53 UTC, DrIceTea123 commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.immortality.desc": "手持带有该附魔的盾牌时死亡将免除死亡，但盾牌会被立刻摧毁。",
原文：`You will cheat death on fatal hit.`
`会立刻摧毁`要不要翻译我不知道，但至少没有提到盾牌

2023-02-02 18:53 UTC, DrIceTea123 commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.smelter.desc": "采集矿石时会自动冶炼成锭。",
原文：`When the block is destroyed it is automatically smelted.`
矿石(x) 方块(√)

2023-02-02 18:53 UTC, DrIceTea123 commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.leech.desc": "每次攻击都有概率窃取目标的随机正面效果或1点生命值。",
原文：`Gives a chance to steal positive effects or health from enemies.`
是“1点”吗？即使是也不一定要译出来

2023-02-02 18:53 UTC, DrIceTea123 commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.swiftness.desc": "提高坐骑的移动速度。",
原文：`Increases the horse's movement speed.`
游戏中坐骑还有可能是猪或炽足兽，有测试过吗

2023-02-02 18:53 UTC, DrIceTea123 commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.horse_protection.desc": "减少坐骑受到的伤害。",
这里也是，L43的原文是`Horse Protection`，L44的原文是`Reduces the amount of damage received by the horse.`，都是`马`
后面还有我就不标了

2023-02-02 18:53 UTC, DrIceTea123 commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.telekinesis.desc": "破坏物品时，直接将物品添加到物品栏中。",
原文：`Adds the item directly to the inventory if possible when destroying blocks.`
似乎只说了方块，译文中说`破坏物品`有点奇怪

2023-02-02 18:53 UTC, DrIceTea123 commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.hunter.desc": "增加你获得的物品数量，当敌人离你越远，你造成的伤害越大。",
意思是不是`增加掉落物的数量`
不是的话别改

2023-02-02 18:53 UTC, DrIceTea123 commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.harvester.desc": "右击收割作物时，有概率加速附近作物的生长。",
原文：`Gives the option of right-click harvesting and the chance to grow nearby crops.`
前一半是`提供右击收获作物的能力`，后一半才是`右击收割时有概率加速附近作物的生长`。

2023-02-02 18:53 UTC, DrIceTea123 commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.mithridatism.desc": "减少部分负面效果的伤害（中毒，凋零等），并给予伤害吸收效果。",
原文：`Reduces the damage from certain negative effects and gives Absorption whenever negative effect is applied.`
这个`is applied`没译出来，可以译成`受到部分负面效果时，减少其伤害并给予伤害吸收效果。`

2023-02-02 18:53 UTC, DrIceTea123 commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.fuse_cutter.desc": "使附近的爆炸无效化。",
原文：`Makes nearby explosions do not destroy blocks and not deal any damage.`
如果是想简化的话可以把“化”字去掉

2023-02-02 18:53 UTC, DrIceTea123 commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.corrosion_curse.desc": "当与水接触时，逐渐破坏盔甲并伤害所有者。",
不是必须的，看着改吧
```suggestion
	"enchantment.wonderful_enchantments.corrosion_curse.desc": "当与水接触时，逐渐损坏盔甲并伤害所有者。",
```

2023-02-02 18:53 UTC, DrIceTea123 commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"item.wonderful_enchantments.wonderful_book.enchanting_energy_max": "最大附魔能量！",
改成`附魔能量已达最大值！`？

2023-02-02 18:53 UTC, DrIceTea123 commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"item.wonderful_enchantments.wonderful_book.hint": "你可以在合成栏上用青金石增加附魔能量。",
原文：`You can increase enchanting energy with Lapis Lazuli in Crafting Table.`
首字母大写的`Crafting Table`是工作台（给我都整不自信了）

2023-02-02 18:53 UTC, DrIceTea123 commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"item.wonderful_enchantments.wonderful_book.transmute": "手持并右击以将其转化为附魔书\ue908\ue909"
这里请直接用省略号。用转义符号`\ue908\ue909`可能会在游戏内显示错误
```suggestion
	"item.wonderful_enchantments.wonderful_book.transmute": "手持并右击以将其转化为附魔书……"
```

2023-02-03 12:07 UTC, Summe-rsnow commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.phoenix_dive.desc": "从高处坠落会释放火焰冲击波，造成范围伤害，并点燃附近的敌人。触发后如果立刻使用潜行，将可以跳得更高，但靴子会消耗更多的耐久度。",
很感谢你的检查 这个是游戏测试出来的 不过考虑到原版的荆棘附魔触发也会额外消耗耐久 但是没有写在上面 我等一下取消这个

2023-02-03 12:07 UTC, Summe-rsnow commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.immortality.desc": "手持带有该附魔的盾牌时死亡将免除死亡，但盾牌会被立刻摧毁。",
因为jei查到只能附魔在盾牌上

2023-02-03 12:07 UTC, Summe-rsnow commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.smelter.desc": "采集矿石时会自动冶炼成锭。",
因为只有矿石才能被冶炼成锭 感觉这样合适点

2023-02-03 12:07 UTC, Summe-rsnow commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.leech.desc": "每次攻击都有概率窃取目标的随机正面效果或1点生命值。",
好的 这个我会修改

2023-02-03 12:09 UTC, Summe-rsnow commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"item.wonderful_enchantments.wonderful_book.enchanting_energy_max": "最大附魔能量！",
这个是原来的翻译 我选择维持

2023-02-03 12:09 UTC, Summe-rsnow commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"item.wonderful_enchantments.wonderful_book.hint": "你可以在合成栏上用青金石增加附魔能量。",
因为是两个物品就能合成 所以工作台和合成栏都可以

2023-02-03 12:09 UTC, Summe-rsnow commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"item.wonderful_enchantments.wonderful_book.transmute": "手持并右击以将其转化为附魔书\ue908\ue909"
这个是原翻译 那我改吧

2023-02-03 12:16 UTC, Summe-rsnow commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.swiftness.desc": "提高坐骑的移动速度。",
这个是附魔在马铠的  对冰与火之歌上的坐骑也有用

2023-02-03 12:16 UTC, Summe-rsnow commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.telekinesis.desc": "破坏物品时，直接将物品添加到物品栏中。",
这个我会改的

2023-02-03 12:17 UTC, Summe-rsnow commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.hunter.desc": "增加你获得的物品数量，当敌人离你越远，你造成的伤害越大。",
是的我会改的

2023-02-03 12:17 UTC, Summe-rsnow commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.mithridatism.desc": "减少部分负面效果的伤害（中毒，凋零等），并给予伤害吸收效果。",
好的

2023-02-03 12:17 UTC, Summe-rsnow commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.harvester.desc": "右击收割作物时，有概率加速附近作物的生长。",
好的

2023-02-03 12:19 UTC, Summe-rsnow commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.horse_protection.desc": "减少坐骑受到的伤害。",
我还是改成马匹吧

2023-02-03 12:23 UTC, DrIceTea123 commented
不用每条都回复，会产生垃圾邮件。要表示看过了的话贴个表情就好
改完之后记得把前面的commit都resolve掉，然后我再来看

2023-02-03 12:33 UTC, DrIceTea123 commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.immortality.desc": "手持带有该附魔的盾牌时死亡将免除死亡，但盾牌会被立刻摧毁。",
大多数时候没有必要按照游戏内实际的详细情况翻译，只需要按照英文语义正确翻译即可，尽量避免过度翻译
遇到英文原文无法准确翻译时，才会在尊重原文的基础上进行部分内容的意译
此处翻译我的建议是可以保留`会立刻摧毁`的部分，但是最好还是删去`盾牌`的描述

2023-02-03 12:41 UTC, Summe-rsnow commented
> 不用每条都回复，会产生垃圾邮件。如果仅仅要表示看过了的话贴个表情就好 改完之后记得把前面的commit都resolve掉，然后我再来看

非常抱歉 第一次提交翻译真的有一堆不足 浪费了你的时间 而且也不懂github这个工具  给你带来了麻烦

2023-02-03 12:50 UTC, DrIceTea123 commented
没事，没有责备的意思，大家都是这么过来的（）
有什么翻译上的问题可以来我们的qq群参加讨论：630943368

2023-02-03 17:42 UTC, DrIceTea123 commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.smelter.desc": "采集矿石时会自动冶炼成锭。",
但是我记得这个附魔似乎还能把圆石烧成石头、把原木烧成木炭
如果是我记错了那当我没说（）

2023-02-03 17:49 UTC, DrIceTea123 requested changes
那应该差不多了，还有一点要改

2023-02-03 17:49 UTC, DrIceTea123 commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.smelter.desc": "采集矿石时会自动冶炼成锭。",
但是我记得这个附魔似乎还能把圆石烧成石头、把原木烧成木炭
如果是我记错了那当我没说（）

2023-02-03 17:49 UTC, DrIceTea123 commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.horse_protection.description": "减少坐骑马匹的伤害。",
这里没删干净

2023-02-03 17:49 UTC, DrIceTea123 commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.hunter.description": "增加你获得的物品数量，当敌人离你越远，你造成的伤害越大。",
这里跟上一行应该是同步修改的

2023-02-04 13:33 UTC, Summe-rsnow commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.smelter.desc": "采集矿石时会自动冶炼成锭。",
好像有这个功能 我玩的时候确实没注意到 已经修改了翻译了

2023-02-08 06:50 UTC, DrIceTea123 approved these changes
似乎没啥问题了

2023-05-28 10:23 UTC, ChuijkYahus commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"item.wonderful_enchantments.wonderful_book.transmute": "手持并右击以将其转化为附魔书......"
```suggestion
	"item.wonderful_enchantments.wonderful_book.transmute": "手持并右击以将其转化为附魔书……"

```

2023-05-28 11:47 UTC, ChuijkYahus commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.immortality.description": "手持带有该附魔的盾牌时死亡将免除死亡，但盾牌会被立刻摧毁。",
```suggestion
	"enchantment.wonderful_enchantments.immortality.desc": "手持带有该魔咒的盾牌时死亡将免除死亡，但盾牌会被立刻摧毁。",
	"enchantment.wonderful_enchantments.immortality.description": "手持带有该魔咒的盾牌时死亡将免除死亡，但盾牌会被立刻摧毁。",
```

2023-05-28 11:47 UTC, ChuijkYahus commented on projects/1.16/assets/wonderful-enchantments/wonderful_enchantments/lang/zh_cn.json
> +	"enchantment.wonderful_enchantments.vampirism_curse.description": "当玩家在阳光下时变得虚弱且着火，但会增强蛭吸附魔。",
```suggestion
	"enchantment.wonderful_enchantments.vampirism_curse.desc": "当玩家在阳光下时变得虚弱且着火，但会增强蛭吸魔咒。",
	"enchantment.wonderful_enchantments.vampirism_curse.description": "当玩家在阳光下时变得虚弱且着火，但会增强蛭吸魔咒。",
```

2023-07-20 18:58 UTC, mamaruo requested changes
你似乎是从头开始翻译的。你的翻译和库内内容冲突且只是表达方式有略微差异，且库内内容没有问题的，请修改到与原有的一致。

2023-07-30 10:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2940) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2940) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=2940) it.</sub>

2023-08-23 15:26 UTC, Cactusstudent commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@Summe-rsnow

2023-09-01 02:17 UTC, closed without merging