Prehistoric Fauna 翻译修正&更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #2954
Opened 2023-02-02 11:24 UTC by Kasualix

此版本未在 CurseForge 上放出，我们是用它 GitHub 里的源码自己编译成 jar 再翻译的。
手册没同步更新，只是按照新的翻译修正了一些现有的错误。
主要的译者是 [71262酱](https://center.mcmod.cn/71262/)（[GitHub](https://github.com/1mtwtfss1)）和[这位人兄](https://center.mcmod.cn/127151/)，我只是个工具人，帮忙改了改手册和 Dramatic Doors 的联动然后就来投 PR了。
- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-02 13:27 UTC, ChuijkYahus commented
等这些译名敲定之后我和官方那边同步一下吧

2023-02-02 15:54 UTC, Ricky-fight requested changes
木制品大部分都存在和标准译名不一致的情况，比如`xx压力板`-`xx木压力板`、`xx书架`-`xx木书架`。要改起来工作量比较大木制品大部分都存在和标准译名不一致的情况，比如`xx压力板`-`xx木压力板`、`xx书架`-`xx木书架`。要改起来工作量比较大

2023-02-02 15:54 UTC, Ricky-fight commented on projects/1.16/assets/prehistoric-fauna/prehistoricfauna/lang/zh_cn.json
> +  "entity.prehistoricfauna.velociraptor.following": "在跟随",
这三个文本是在哪里出现的？时态其实可以不译出来

2023-02-02 15:54 UTC, Ricky-fight commented on projects/1.16/assets/prehistoric-fauna/prehistoricfauna/lang/zh_cn.json
> +  "mi": "伊斯基瓜拉斯托组，莫里逊组",
其实[wiki](https://zh.wikipedia.org/wiki/%E4%BC%8A%E6%B2%99%E7%93%9C%E6%8B%89%E6%96%AF%E6%89%98)词条主名是前面那个，不过随意吧

2023-02-02 19:09 UTC, DrIceTea123 commented
> 木制品大部分都存在和标准译名不一致的情况，比如`xx压力板`-`xx木压力板`、`xx书架`-`xx木书架`。要改起来工作量比较大，辛苦了（）

补充一下，原木和木板要看树种情况翻译，例如`橡木木板` `白桦木板` `深色橡木原木` `金合欢原木`；
但是木制品都要带“木”字，例如`橡木按钮` `云杉木告示牌` `白桦木压力板`

2023-02-02 19:57 UTC, ChuijkYahus commented
![图片](https://user-images.githubusercontent.com/94828194/216435570-8b88974e-7029-4890-85a9-6e9db4113aa1.png)
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/2715#discussion_r1056901664 经典再放送（）
不过里面用作讨论的范例沼泽柏已经发现是错误翻译了（还是在整另一个模组的everycomp兼容的时候发现的）

2023-02-03 03:08 UTC, Kasualix commented on projects/1.16/assets/prehistoric-fauna/prehistoricfauna/lang/zh_cn.json
> +  "entity.prehistoricfauna.velociraptor.following": "在跟随",
是恐龙驯服相关的，问了问71262改好了

2023-02-03 03:09 UTC, Kasualix commented on projects/1.16/assets/prehistoric-fauna/prehistoricfauna/lang/zh_cn.json
> +  "mi": "伊斯基瓜拉斯托组，莫里逊组",
我改回来吧

2023-02-03 03:54 UTC, Kasualix commented
> 要改起来工作量比较大，辛苦了（）

![2WPPPRS@D@C%26QRO5G8Y56](https://user-images.githubusercontent.com/110756250/216508868-10660c67-82a1-4faf-bdfb-0db0c4e0fbb2.jpg)

2023-02-09 18:39 UTC, Kasualix commented
慢慢来吧，每天一点，总能改完的

> 要改起来工作量比较大，辛苦了（）

2023-02-10 16:27 UTC, Ricky-fight requested changes
这些整完应该差不多了（）

2023-02-10 16:27 UTC, Ricky-fight commented on projects/1.16/assets/prehistoric-fauna/prehistoricfauna/lang/zh_cn.json
> +  "advancements.prehistoricfauna.fragile.title": "'Fragile', Must Be Italian!",
这是漏的还是有意为之？

2023-02-10 16:27 UTC, Ricky-fight commented on projects/1.16/assets/prehistoric-fauna/prehistoricfauna/lang/zh_cn.json
> +  "block.prehistoricfauna.heidiphyllum_vertical_slab": "海蒂叶杉竖直台阶",
这是否缺一个木？

2023-02-10 16:27 UTC, Ricky-fight commented on projects/1.16/assets/prehistoric-fauna/prehistoricfauna/lang/zh_cn.json
> +  "block.prehistoricfauna.ginkgo_vertical_slab": "银杏竖直台阶",
L1267-L1342

2023-02-10 16:27 UTC, Ricky-fight commented on projects/1.16/assets/prehistoric-fauna/prehistoricfauna/lang/zh_cn.json
> +  "block.prehistoricfauna.neocalamites_beehive": "新芦木蜂箱",
1

2023-02-10 20:26 UTC, Kasualix commented
应该没问题了吧
![31eff39fb4474269](https://user-images.githubusercontent.com/110756250/218190984-32914fc2-cb0e-4f00-a608-33c458914aef.jpg)

2023-02-12 14:30 UTC, Ricky-fight approved these changes
辛苦辛苦

2023-02-13 15:12 UTC, merged

2023-02-14 08:02 UTC, ChuijkYahus commented on projects/1.18/assets/dramatic-doors/dramaticdoors/lang/zh_cn.json
> +  "block.dramaticdoors.tall_protopiceoxylon_door": "原始云杉型木门",
突然发现这里前面的`高`没了
话说这两种树种是加了一个`型`吗

2023-02-14 08:04 UTC, Kasualix commented on projects/1.18/assets/dramatic-doors/dramaticdoors/lang/zh_cn.json
> +  "block.dramaticdoors.tall_protopiceoxylon_door": "原始云杉型木门",
“原始云杉型木“是一种木头
类比“橡木”：“原始云杉型”→“橡”

2023-02-14 08:05 UTC, ChuijkYahus commented on projects/1.18/assets/dramatic-doors/dramaticdoors/lang/zh_cn.json
> +  "block.dramaticdoors.tall_protopiceoxylon_door": "原始云杉型木门",
OK
我去官方更新一下