更新机械动力：矿石开掘 [Create ore excavation] 的翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #2956
Opened 2023-02-02 17:18 UTC by Catchmons

- [ ] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已确认标题符合`{模组英文全名} {简述}`的格式，如`Ender IO 翻译新增/更新/修正/删除`；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已确认提交文件的**路径**和**名称**均**正确**（[例子](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#提交文件路径的例子)）；
  - 如果是 1.12 翻译，应该是：projects/1.12.2/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.lang
  - 如果是 1.16 及以上的翻译，应该是：projects/{版本}/assets/{CurseForge 项目名称}/{ModID}/lang/zh_cn.json
- [ ] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-02 17:32 UTC, mamaruo commented
/add-mapping create-ore-excavation 649832

2023-02-02 17:34 UTC, Ricky-fight requested changes

2023-02-02 17:34 UTC, Ricky-fight commented on projects/1.18/assets/create-ore-excavation/createoreexcavation/lang/zh_cn.json
> +  "chat.coe.veinFinder.nearby": "探测到周围 %s",
```suggestion
  "chat.coe.veinFinder.far": "探测到%s的痕迹",
  "chat.coe.veinFinder.found": "在区块中探测到%s",
  "chat.coe.veinFinder.info": "探矿杖探测结果：",
  "chat.coe.veinFinder.nearby": "探测到周围%s",
```

2023-02-02 17:34 UTC, Ricky-fight commented on projects/1.18/assets/create-ore-excavation/createoreexcavation/lang/zh_cn.json
> +  "createoreexcavation.ponder.find_ores.text_8": "一些矿脉开采时还额外需要钻浆",
```suggestion
  "createoreexcavation.ponder.find_ores.text_8": "一些矿脉开采时还额外需要钻井液",
```

2023-02-02 17:34 UTC, Ricky-fight commented on projects/1.18/assets/create-ore-excavation/createoreexcavation/lang/zh_cn.json
> +  "info.coe.drill.noFluid": "钻井需要钻浆",
```suggestion
  "info.coe.drill.noFluid": "钻井需要钻井液",
```

2023-02-02 17:34 UTC, Ricky-fight commented on projects/1.18/assets/create-ore-excavation/createoreexcavation/lang/zh_cn.json
> +  "tooltip.coe.finiteVeins": "有限的矿脉尺寸：%s - %s",
```suggestion
  "tooltip.coe.finiteVeins": "有限的矿脉尺寸：%s-%s",
```

2023-02-02 17:34 UTC, Ricky-fight commented on projects/1.18/assets/create-ore-excavation/createoreexcavation/lang/zh_cn.json
> +  "tooltip.coe.page": "页数：%s/%s",
```suggestion
  "tooltip.coe.page": "%s/%s页",
```

2023-02-02 17:34 UTC, Ricky-fight commented on projects/1.18/assets/create-ore-excavation/createoreexcavation/lang/zh_cn.json
> +  "tooltip.coe.processTime": "花费 %s 刻",
```suggestion
  "tooltip.coe.processTime": "花费%s刻",
```

2023-02-03 02:16 UTC, Catchmons commented on projects/1.18/assets/create-ore-excavation/createoreexcavation/lang/zh_cn.json
> +  "tooltip.coe.processTime": "花费 %s 刻",
没有空格的话游戏内排版看起来会很挤的说

2023-02-03 02:46 UTC, Ricky-fight commented on projects/1.18/assets/create-ore-excavation/createoreexcavation/lang/zh_cn.json
> +  "tooltip.coe.processTime": "花费 %s 刻",
这好像是CFPA目前的统一格式要求，可以问问在修订新的贡献指南的@mamaruo

2023-02-03 16:50 UTC, mamaruo commented on projects/1.18/assets/create-ore-excavation/createoreexcavation/lang/zh_cn.json
> +  "tooltip.coe.processTime": "花费 %s 刻",
是这样的

2023-02-09 13:18 UTC, komeiji-koyomi commented on projects/1.18/assets/create-ore-excavation/createoreexcavation/lang/zh_cn.json
> +  "info.coe.drill.err_no_vein": "目标区块中无可采矿脉",
无“可开采”矿脉吧
现在读起来怪怪的

2023-02-27 15:46 UTC, mamaruo commented on projects/1.18/assets/create-ore-excavation/createoreexcavation/lang/zh_cn.json
> +  "config.coe.maxExtractorsPerVein": "每个矿脉的最大矿井数量，设置为0表示无限",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |

原文：**Max number of extractor per ore vein, Set to 0 for infinite**
```suggestion
  "config.coe.maxExtractorsPerVein": "每个矿脉的最大矿井数量，设置为0表示无限",
```

extractor 术语不一致，另见 20、29 行等

2023-02-27 15:46 UTC, mamaruo commented on projects/1.18/assets/create-ore-excavation/createoreexcavation/lang/zh_cn.json
> +  "info.coe.drill.installed": "已安装 %s",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |

原文：**Installed drill: %s**
```suggestion
  "info.coe.drill.installed": "已安装钻头：%s",
```
我不能理解这个翻译稿为什么要**把几乎所有原文的冒号给去掉**

2023-03-12 01:36 UTC, Catchmons commented on projects/1.18/assets/create-ore-excavation/createoreexcavation/lang/zh_cn.json
> +  "chat.coe.veinFinder.nearby": "探测到周围%s",
%s 是矿脉名称

2023-03-12 05:09 UTC, mamaruo approved these changes

2023-03-14 07:37 UTC, ChuijkYahus commented
这是冲突了？（）

2023-03-26 07:33 UTC, merged