[R] 提交 Assemblylinemachines 模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #2959
Opened 2023-02-03 13:18 UTC by LanceLeviathan

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-05 18:19 UTC, Ricky-fight commented
/format projects/1.19/assets/assemblylinemachines/assemblylinemachines/lang/en_us.json

2023-02-05 19:10 UTC, Ricky-fight requested changes
#2808已经有提交，但该PR整体上明显好于#2808

2023-02-05 19:10 UTC, Ricky-fight commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/lang/zh_cn.json
> +	"block.assemblylinemachines.mkii_lumber_mill": "MKII锯木机",
```suggestion
	"block.assemblylinemachines.mkii_pneumatic_compressor": "MK II压缩机",
	"block.assemblylinemachines.mkii_lumber_mill": "MK II锯木机",
```

2023-02-05 19:10 UTC, Ricky-fight commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/lang/zh_cn.json
> +	"itemGroup.assemblylinemachines":"装配线",
```suggestion
	"itemGroup.assemblylinemachines":"装配线机器",
```

2023-02-05 19:10 UTC, Ricky-fight commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/lang/zh_cn.json
> +	"death.attack.interactor.item":"%2$s 的交互器对 %1$s 使用了 %3$s ，效果拔群！",
```suggestion
	"death.attack.interactor":"%1$s被撕碎了，凶手是%2$s的交互器",
	"death.attack.interactor.item":"%2$s的交互器对%1$s使用了%3$s，效果拔群！",
```

2023-02-05 19:10 UTC, Ricky-fight commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/lang/zh_cn.json
> +	"commands.assemblylinemachines.makecreative.error": "Block at %1$s is not a compatible block with this command.",
```suggestion
	"commands.assemblylinemachines.guide.missing_mod": "Patchouli is not installed.",
	"commands.assemblylinemachines.guide.success": "Gave a copy of Assembly Lines & You to %1$s player(s).",
	"commands.assemblylinemachines.chunkfluid.error": "An unexpected error occurred while interfacing with the chunk fluid.",
	"commands.assemblylinemachines.chunkfluid.get.success": "There is %1$s mB of %2$s in the chunk at %3$s.",
	"commands.assemblylinemachines.chunkfluid.get.success_empty": "The chunk at %1$s is empty.",
	"commands.assemblylinemachines.chunkfluid.set.success": "Updated fluid in chunk at %1$s to %2$s mB of %3$s.",
	"commands.assemblylinemachines.chunkfluid.remove.success": "Removed fluid from chunk at %1$s.",
	"commands.assemblylinemachines.errors.missing_fluid": "Unknown fluid \"%1$s\"",
	"commands.assemblylinemachines.errors.flowing_fluid": "The fluid given must be a source fluid.",
	"commands.assemblylinemachines.makecreative.success": "Successfully made the %1$s at %2$s creative.",
	"commands.assemblylinemachines.makecreative.error": "Block at %1$s is not a compatible block with this command.",
```
命令交互也是游玩体验的一部分，请尽量翻一下吧，辛苦了（）
#2808有翻译过

2023-02-05 19:10 UTC, Ricky-fight commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/lang/zh_cn.json
> +	"sound.assemblylinemachines.assembly_required": "Assembly Required"
1

2023-02-05 19:10 UTC, Ricky-fight requested changes
#2808已经有提交，但该PR整体上明显好于#2808

2023-02-06 07:58 UTC, LanceLeviathan commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/lang/zh_cn.json
> +	"item.assemblylinemachines.polished_rock":"抛光石头",
游戏内贴图类似小石子，使用岩石作为翻译有些违和，因为岩石总给人一种大的感觉

2023-02-06 08:02 UTC, LanceLeviathan commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/lang/zh_cn.json
> +	"block.assemblylinemachines.teleportation_pad":"Teleportation Pad",
此物品未在游戏中找到，不知道是没有实装还是高版本已经删除，因为没见过，所以就不乱翻了

2023-02-06 08:04 UTC, LanceLeviathan commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/lang/zh_cn.json
> +	"block.assemblylinemachines.mkii_furnace": "MKII电力炉",
MKII是英文原本的写法，翻译也就不加空格了

2023-02-06 08:04 UTC, LanceLeviathan commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/lang/zh_cn.json
> +	"block.assemblylinemachines.mkii_lumber_mill": "MKII锯木机",
同上，保留

2023-02-06 08:05 UTC, LanceLeviathan commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/lang/zh_cn.json
> +	"itemGroup.assemblylinemachines":"装配线",
装配线是模组名称，由mc百科提供，不做修改

2023-02-06 08:14 UTC, LanceLeviathan commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/lang/zh_cn.json
> +	"sound.assemblylinemachines.assembly_required": "Assembly Required"
assembly required是唱片音乐名，不做翻译

2023-02-06 08:53 UTC, LanceLeviathan commented
> #2808已经有提交，但该PR整体上明显好于#2808

该模组的帕秋莉手册翻译文件位于mod文件/data/文件夹而非mod文件/assets/文件夹中，似乎没办法用资源包的形式提供翻译？有什么解决办法吗？

2023-02-06 13:29 UTC, Ricky-fight commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/lang/zh_cn.json
> +	"sound.assemblylinemachines.assembly_required": "Assembly Required"
指的是上面的字幕（）

2023-02-06 13:47 UTC, Ricky-fight commented
> > #2808已经有提交，但该PR整体上明显好于#2808
> 
> 该模组的帕秋莉手册翻译文件位于mod文件/data/文件夹而非mod文件/assets/文件夹中，似乎没办法用资源包的形式提供翻译？有什么解决办法吗？

帕秋莉可以汉化，提交路径可以参见#2052 #1897 #1526

2023-02-06 14:30 UTC, Ricky-fight commented
![_G``5YJRT%IBY H%4U9)0_K](https://user-images.githubusercontent.com/13982778/216998044-999ad8bb-290c-4511-93bf-b05270f913a6.png)

2023-02-06 14:51 UTC, Ricky-fight commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/lang/zh_cn.json
> +	"block.assemblylinemachines.mkii_furnace": "MKII电力炉",
如果游戏内看上去不会难受的话也行（）

2023-02-06 14:52 UTC, Ricky-fight approved these changes

2023-02-07 17:30 UTC, merged

2023-02-07 17:36 UTC, ChuijkYahus commented
嘶才发现有重复pr
有机会可以加上`Co-authored-by: jiayu233 <https://github.com/jiayu233>`这一条