提交tinkers-archery模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #2968
Opened 2023-02-04 06:05 UTC by wanji404

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-06 09:28 UTC, wanji404 commented
辛苦审核大大了：）

2023-02-24 11:17 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "item.tinkersarchery.crossbow.description": "弩可以蓄存箭。拉动弩弦虽然很困难，但之后的射击却能让人倍感舒适。",
```suggestion
  "item.tinkersarchery.crossbow.description": "弩可以蓄存箭。拉动弩弦虽然很困难，但之后的射击却能让人倍感舒适。",
```

2023-03-01 17:49 UTC, ChuijkYahus requested changes

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "modifier.tinkersarchery.chaining.flavor": "连杀奖励",
```suggestion
  "modifier.tinkersarchery.chaining": "连锁",
  "modifier.tinkersarchery.chaining.attack_damage": "连锁伤害",
  "modifier.tinkersarchery.chaining.description": "击杀敌人后，对后一敌人造成成倍伤害",
  "modifier.tinkersarchery.chaining.flavor": "连杀奖励",
```

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "modifier.tinkersarchery.clean.flavor": "简单",
```suggestion
  "modifier.tinkersarchery.clean": "彻底",
  "modifier.tinkersarchery.clean.accuracy": "满弦精确度",
  "modifier.tinkersarchery.clean.description": "弓拉得越满，箭矢就射得越准",
  "modifier.tinkersarchery.clean.flavor": "简捷",
```

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "modifier.tinkersarchery.finishing.flavor": "朽木凋零 / 寒风刺骨 / 命染黄沙",
```suggestion
  "modifier.tinkersarchery.finishing": "终结",
  "modifier.tinkersarchery.finishing.attack_damage": "低于半血时伤害",
  "modifier.tinkersarchery.finishing.description": "对血量低的敌人造成更多伤害",
  "modifier.tinkersarchery.finishing.flavor": "落叶正飘散/雪花飞舞落至地/汝命已凋零",
```
无主之地，零，原文为五七五音节排布，应为俳句
大致依照https://tieba.baidu.com/p/3572754813 修改了一下（~~完全找不到对应的中文译法~~）

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "modifier.tinkersarchery.gravity_trajectory.flavor": "像牛顿和苹果",
```suggestion
  "modifier.tinkersarchery.gravity_trajectory.description": "箭矢的行为符合规律，以抛物线轨迹出射并坠地。",
  "modifier.tinkersarchery.gravity_trajectory.flavor": "像牛顿和苹果",
```

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "modifier.tinkersarchery.groovy.flavor": "跟上这节奏",
```suggestion
  "modifier.tinkersarchery.groovy": "节律",
  "modifier.tinkersarchery.groovy.description": "发射得越多，拉弓速度就越快",
  "modifier.tinkersarchery.groovy.draw_speed": "节律拉弓速度",
  "modifier.tinkersarchery.groovy.flavor": "跟上节奏",
```

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "modifier.tinkersarchery.haste.description": "神奇的红尘使弓拉得更快!",
```suggestion
  "modifier.tinkersarchery.haste": "急迫",
  "modifier.tinkersarchery.haste.1": "急迫",
  "modifier.tinkersarchery.haste.2": "急迫+",
  "modifier.tinkersarchery.haste.3": "急迫++",
  "modifier.tinkersarchery.haste.4": "急迫+++",
  "modifier.tinkersarchery.haste.5": "急迫++++",
  "modifier.tinkersarchery.haste.description": "神奇红色粉尘，让弓弩拉弦疾如风！",
```

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "modifier.tinkersarchery.haste.flavor": "科学!",
```suggestion
  "modifier.tinkersarchery.haste.flavor": "科学！",
```

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "modifier.tinkersarchery.highlander.description": "箭在高处能射得更远",
```suggestion
  "modifier.tinkersarchery.highlander": "高地",
  "modifier.tinkersarchery.highlander.1": "高地",
  "modifier.tinkersarchery.highlander.2": "高地+",
  "modifier.tinkersarchery.highlander.3": "高地++",
  "modifier.tinkersarchery.highlander.4": "高地+++",
  "modifier.tinkersarchery.highlander.5": "高地++++",
  "modifier.tinkersarchery.highlander.description": "箭矢在高处能射得更远",
```
不知道`高地居民`和`高地住民`怎么样

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "modifier.tinkersarchery.launching.flavor": "跑！巴里！跑！",
```suggestion
  "modifier.tinkersarchery.launching": "迸射",
  "modifier.tinkersarchery.launching.1": "迸射",
  "modifier.tinkersarchery.launching.2": "迸射+",
  "modifier.tinkersarchery.launching.3": "迸射++",
  "modifier.tinkersarchery.launching.4": "迸射+++",
  "modifier.tinkersarchery.launching.5": "迸射++++",
  "modifier.tinkersarchery.launching.description": "箭矢的出射速度更快",
  "modifier.tinkersarchery.launching.flavor": "给箭矢加速",
```
这个flavor应该老久了（），原文的梗应该是闪电侠
迸射本身有其他意思，不知道这里合不合适

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "modifier.tinkersarchery.looping_trajectory.flavor": "哇哦... 哇哦",
```suggestion
  "modifier.tinkersarchery.looping_trajectory": "环形轨迹",
  "modifier.tinkersarchery.looping_trajectory.description": "箭矢会先空中盘旋一圈，然后直线飞行，最后再次盘旋",
  "modifier.tinkersarchery.looping_trajectory.flavor": "哇哦……哇哦",
```

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "modifier.tinkersarchery.multishot.description": "弓射击时附加更多箭",
```suggestion
  "modifier.tinkersarchery.multishot.description": "弓弩同时射出更多箭矢",
```
看实际情况

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "modifier.tinkersarchery.pinpointer.description": "弓射击时更精准",
```suggestion
  "modifier.tinkersarchery.pinpointer": "精准",
  "modifier.tinkersarchery.pinpointer.1": "精准+",
  "modifier.tinkersarchery.pinpointer.2": "精准++",
  "modifier.tinkersarchery.pinpointer.3": "精准+++",
  "modifier.tinkersarchery.pinpointer.4": "精准++++",
  "modifier.tinkersarchery.pinpointer.5": "超越精准++++",
  "modifier.tinkersarchery.pinpointer.description": "弓弩射击时更为精准",
```

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "modifier.tinkersarchery.power.flavor": "怎么做到的?",
```suggestion
  "modifier.tinkersarchery.power": "力量",
  "modifier.tinkersarchery.power.1": "力量",
  "modifier.tinkersarchery.power.2": "力量+",
  "modifier.tinkersarchery.power.3": "力量++",
  "modifier.tinkersarchery.power.4": "力量+++",
  "modifier.tinkersarchery.power.5": "力量++++",
  "modifier.tinkersarchery.power.description": "箭矢造成更多伤害",
  "modifier.tinkersarchery.power.flavor": "怎么做到的？",
```
应该是匠魂2的flavor吧，还没考证

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "modifier.tinkersarchery.slicing.flavor": "削铁如泥",
```suggestion
  "modifier.tinkersarchery.slicing": "切割",
  "modifier.tinkersarchery.slicing.description": "箭矢总会暴击",
  "modifier.tinkersarchery.slicing.flavor": "削铁如泥",
```

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "modifier.tinkersarchery.superslime.flavor": "Duang Duang的",
```suggestion
  "modifier.tinkersarchery.superslime": "黏液被层",
  "modifier.tinkersarchery.superslime.description": "弓弩上的黏液覆层越多，拉弓速度就越快，箭矢也飞得越远",
  "modifier.tinkersarchery.superslime.draw_speed": "黏液被层拉弓速度",
  "modifier.tinkersarchery.superslime.elasticity": "黏液被层拉力",
  "modifier.tinkersarchery.superslime.flavor": "啵嘤~",
```
怀疑是将over-替换成super-而来，但没有确实依据
后面拟声词大概是随便找的（）

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "modifier.tinkersarchery.swiftstrike.flavor": "放轻松~",
```suggestion
  "modifier.tinkersarchery.swiftstrike": "迅捷射击",
  "modifier.tinkersarchery.swiftstrike.attack_damage": "移动时伤害",
  "modifier.tinkersarchery.swiftstrike.description": "移动速度越快，箭矢伤害越高",
  "modifier.tinkersarchery.swiftstrike.flavor": "放轻松，我们坐下来谈谈吧",
```

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "modifier.tinkersarchery.twirling_trajectory.flavor": "做一个飞行特技表演",
```suggestion
  "modifier.tinkersarchery.twirling_trajectory": "旋转轨迹",
  "modifier.tinkersarchery.twirling_trajectory.description": "箭矢会在空中旋转",
  "modifier.tinkersarchery.twirling_trajectory.flavor": "做个桶滚",
```
什么gta5毒图（）
虽然我貌似用滚桶多些，但不够正规
这个轨迹应该是前进的同时箭矢会绕飞行方向上某轴公转（从桶滚推的）
这里找到确切用词后上方树叶一栏也需要更改

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "modifier.tinkersarchery.uplifting.flavor": "举头望明月",
```suggestion
  "modifier.tinkersarchery.uplifting": "仰倾",
  "modifier.tinkersarchery.uplifting.description": "箭矢出射方向会略偏上，以辅助瞄准",
  "modifier.tinkersarchery.uplifting.flavor": "飞向长空",
```

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "modifier.tinkersarchery.weighty.flavor": "芝麻稳定",
```suggestion
  "modifier.tinkersarchery.weighty": "稳定",
  "modifier.tinkersarchery.weighty.description": "使箭头更稳定，使其飞出更讨喜的轨迹",
  "modifier.tinkersarchery.weighty.flavor": "先稳后动",
```
只找到nilu以及Brandon Heath的歌曲

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "tool_stat.tinkersarchery.accuracy.description": "射击有多准确。\n这受弓和箭的共同影响。",
```suggestion
  "tool_stat.tinkersarchery.accuracy": "精确度：",
  "tool_stat.tinkersarchery.accuracy.description": "射击有多准确。\n同时受弓弩和箭矢的影响。",
```

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "tool_stat.tinkersarchery.count": "数量: ",
```suggestion
  "tool_stat.tinkersarchery.count": "箭数：",
```

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "tool_stat.tinkersarchery.draw_speed.description": "拉弓速度有多快。\n箭的射出速度与拉弓程度不是线性关系。",
```suggestion
  "tool_stat.tinkersarchery.draw_speed": "拉弓速度：",
  "tool_stat.tinkersarchery.draw_speed.description": "拉弓速度有多快。\n箭矢的出射速度与拉弓程度不成线性关系。",
```

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "tool_stat.tinkersarchery.accuracy.multiplier_description": "弓具的总精度将乘以此值。",
```suggestion
  "tool_stat.tinkersarchery.accuracy.multiplier_description": "弓弩的总精确度将乘以此值。",
```

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "tool_stat.tinkersarchery.count.multiplier_description": "射出箭的总数将与此相乘。",
```suggestion
  "tool_stat.tinkersarchery.count.description": "射出箭矢的数目。",
  "tool_stat.tinkersarchery.count.multiplier_description": "射出箭矢的总数将乘以此值。",
```

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "tool_stat.tinkersarchery.draw_speed.multiplier_description": "弓具的拉弓速度将乘以此值。",
```suggestion
  "tool_stat.tinkersarchery.draw_speed.multiplier_description": "弓弩的拉弓速度将乘以此值。",
```

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "tool_stat.tinkersarchery.elasticity.multiplier_description": "弓具的总磅数将乘以此值。",
```suggestion
  "tool_stat.tinkersarchery.elasticity": "拉力：",
  "tool_stat.tinkersarchery.elasticity.description": "弓弩射出的箭有多快。\n箭的速度参与伤害计算。",
  "tool_stat.tinkersarchery.elasticity.multiplier_description": "弓弩的总拉力将乘以此值。",
```
官库已全部修改为Elasticity（弹性）

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "tool_stat.tinkersarchery.stability": "稳定性: ",
```suggestion
  "tool_stat.tinkersarchery.stability": "稳定性：",
```

2023-03-01 17:49 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-archery/tinkersarchery/lang/zh_cn.json
> +  "tool_stat.tinkersarchery.weight.multiplier_description": "弓具的总重量将乘以此值。"
```suggestion
  "tool_stat.tinkersarchery.stability.description": "箭矢的飞行轨迹有多稳定。",
  "tool_stat.tinkersarchery.stability.multiplier_description": "箭矢的总稳定性将乘以此值。",
  "tool_stat.tinkersarchery.weight": "重量：",
  "tool_stat.tinkersarchery.weight.description": "箭矢有多重。\n轻质箭矢比重质箭矢飞得更远。",
  "tool_stat.tinkersarchery.weight.multiplier_description": "弓弩的总重量将乘以此值。"
```
不知道最后一个是啥意思（）

2023-04-01 07:13 UTC, ChuijkYahus commented
* 7+7时限进入第二阶段，请注意查看各审核意见

@wanji404

2023-04-01 07:21 UTC, closed without merging

2023-04-01 07:49 UTC, ChuijkYahus commented
还是直接关了啊