提交ticbc模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #2969
Opened 2023-02-04 06:15 UTC by wanji404

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-06 09:28 UTC, wanji404 commented
：）辛苦审核大大了

2023-02-22 14:53 UTC, ChuijkYahus requested changes
所有半角感叹号需改为全角感叹号

2023-02-22 14:53 UTC, ChuijkYahus commented on projects/1.16/assets/ticbc/bettercompat/lang/zh_cn.json
> +"modifier.bettercompat.obsidianified.description": "根据流体，水或熔岩，你的工具效率会有所不同。也坚不可摧！",
```suggestion
"modifier.bettercompat.obsidianified": "黑耀化",
"modifier.bettercompat.obsidianified.flavor": "极限抵抗！",
"modifier.bettercompat.obsidianified.description": "根据身处的流体（水或熔岩），你的工具效率会有所不同。同时工具坚不可摧！",
```
源码：
持有者眼部位于水中时，采掘速度 = 原采掘速度 \* (属性等级 * 1.5)
持有者眼部位于熔岩中时，采掘速度 = 原采掘速度 -  (属性等级 * 1.5)
其余情况没有加成

2023-02-22 14:53 UTC, ChuijkYahus commented on projects/1.16/assets/ticbc/bettercompat/lang/zh_cn.json
> +"modifier.bettercompat.superheated.description": "对免疫火焰的怪物造成额外的伤害，让非免疫的怪物着火，并提高下界中的采矿速度",
```suggestion
"modifier.bettercompat.superheated.flavor": "过热！",
"modifier.bettercompat.superheated.description": "对免疫火焰的生物造成额外伤害，其余生物则会着火，并提高下界中的采掘速度",
```

2023-02-22 14:53 UTC, ChuijkYahus commented on projects/1.16/assets/ticbc/bettercompat/lang/zh_cn.json
> +"modifier.bettercompat.rising.description": "击中时将怪物从地上提起",
```suggestion
"modifier.bettercompat.rising.flavor": "振奋人心！",
"modifier.bettercompat.rising.description": "击中时将生物从地上提起",
```

2023-02-22 14:53 UTC, ChuijkYahus commented on projects/1.16/assets/ticbc/bettercompat/lang/zh_cn.json
> +"modifier.bettercompat.mana.flavor": "如有神助!",
```suggestion
"modifier.bettercompat.mana.flavor": "魔力十足！",
```

2023-02-22 14:53 UTC, ChuijkYahus commented on projects/1.16/assets/ticbc/bettercompat/lang/zh_cn.json
> +"modifier.bettercompat.greater_mana_burst.description": "向你的敌人发出更强的魔法爆发，造成额外的伤害",
```suggestion
"modifier.bettercompat.lesser_mana_burst": "魔力爆发（弱）",
"modifier.bettercompat.lesser_mana_burst.flavor": "魔力十足！（第二部分）",
"modifier.bettercompat.lesser_mana_burst.description": "向你的敌人射出一束魔力，造成额外的伤害",
"modifier.bettercompat.greater_mana_burst": "魔力爆发（强）",
"modifier.bettercompat.greater_mana_burst.flavor": "魔力十足！（第三部分）",
"modifier.bettercompat.greater_mana_burst.description": "向你的敌人射出更强力的魔力束，造成额外的伤害",
```
怎么前后不统一呢

2023-02-22 14:53 UTC, ChuijkYahus commented on projects/1.16/assets/ticbc/bettercompat/lang/zh_cn.json
> +"modifier.bettercompat.miners_luck.description": "采矿时小概率给玩家一份礼物",
```suggestion
"modifier.bettercompat.miners_luck": "矿工之运",
"modifier.bettercompat.miners_luck.flavor": "幸运日！",
"modifier.bettercompat.miners_luck.description": "采矿时小概率给玩家一份礼物",
```

2023-02-22 14:53 UTC, ChuijkYahus commented on projects/1.16/assets/ticbc/bettercompat/lang/zh_cn.json
> +"modifier.bettercompat.anti_armor.description": "对目标造成相当于护甲等级的伤害，但移除武器的横扫能力",
```suggestion
"modifier.bettercompat.anti_armor.flavor": "无从抵抗！",
"modifier.bettercompat.anti_armor.description": "对目标额外造成与其护甲值有关的伤害，但武器不再能进行横扫攻击",
```

2023-02-22 14:53 UTC, ChuijkYahus commented on projects/1.16/assets/ticbc/bettercompat/lang/zh_cn.json
> +"modifier.bettercompat.bone_shard.description": "有机会将骨头碎片嵌入一个怪物体内，持续造成伤害",
```suggestion
"modifier.bettercompat.bone_shard.description": "有概率将骨头碎片嵌入一个生物体内，持续造成伤害",
```

2023-02-22 14:53 UTC, ChuijkYahus commented on projects/1.16/assets/ticbc/bettercompat/lang/zh_cn.json
> +"modifier.bettercompat.sentient.description": "当你的库存中有灵魂宝石时，吸取怪物的灵魂",
```suggestion
"modifier.bettercompat.sentient.description": "当物品栏中有气血宝珠时，吸取怪物的灵魂",
```
推测是血魔法的气血宝珠

2023-02-22 14:53 UTC, ChuijkYahus commented on projects/1.16/assets/ticbc/bettercompat/lang/zh_cn.json
> +"modifier.bettercompat.voodoo.description": "用巫术的力量伤害你的敌人",
```suggestion
"modifier.bettercompat.voodoo": "巫毒",
"modifier.bettercompat.voodoo.flavor": "蛊惑！",
"modifier.bettercompat.voodoo.description": "用巫毒的力量伤害你的敌人",
```
灵灾模组的内容

2023-02-22 14:53 UTC, ChuijkYahus commented on projects/1.16/assets/ticbc/bettercompat/lang/zh_cn.json
> +"modifier.bettercompat.shadow_rage.description": "杀死一个敌人后使你潜入暗影",
```suggestion
"modifier.bettercompat.shadow_rage.flavor": "可怕的黑影！",
"modifier.bettercompat.shadow_rage.description": "击杀敌人后使你潜入暗影",
```

2023-02-22 14:53 UTC, ChuijkYahus commented on projects/1.16/assets/ticbc/bettercompat/lang/zh_cn.json
> +"recipe.bettercompat.modifier.lunge_level_3": "在Lv2的冲刺的基础上增加",
```suggestion
"modifier.bettercompat.lunge.flavor": "推力！",
"modifier.bettercompat.lunge.description": "给你的工具增加一个冲刺功能，类似于匠魂2的长剑",
"recipe.bettercompat.modifier.lunge_level_2": "“冲刺 II”需要“冲刺 I”作为前置",
"recipe.bettercompat.modifier.lunge_level_3": "“冲刺 III”需要“冲刺 II”作为前置",
```
前面都冲刺了这里怎么不是冲刺

2023-02-22 14:53 UTC, ChuijkYahus commented on projects/1.16/assets/ticbc/bettercompat/lang/zh_cn.json
> +"modifier.bettercompat.angelic.description": "（这里从一开始就什么都没有，不要问我为什么没有翻译）"
```suggestion
"modifier.bettercompat.angelic.description": ""
```
一开始就没有那你这里为什么要有

2023-02-22 14:53 UTC, ChuijkYahus commented on projects/1.16/assets/ticbc/bettercompat/lang/zh_cn.json
> +"modifier.bettercompat.angelic.flavor": "神圣天堂!",
```suggestion
"modifier.bettercompat.angelic.flavor": "神圣天堂！",
```

2023-02-22 14:53 UTC, ChuijkYahus commented on projects/1.16/assets/ticbc/bettercompat/lang/zh_cn.json
> +"modifier.bettercompat.prospect.description": "采矿时，玩家会随机获得短暂的加速效果",
```suggestion
"modifier.bettercompat.prospect.flavor": "采矿！",
"modifier.bettercompat.prospect.description": "挖掘时，玩家会随机获得短暂的急迫效果",
```
原版用词

2023-02-22 14:53 UTC, ChuijkYahus commented on projects/1.16/assets/ticbc/bettercompat/lang/zh_cn.json
> +"modifier.bettercompat.reflect.description": "当错过一次攻击时，有机会反射你对自己造成的伤害",
```suggestion
"modifier.bettercompat.reflect.flavor": "镜面！",
"modifier.bettercompat.reflect.description": "当未攻击中时，有概率将本应对自身造成的伤害反射出去",
```

2023-02-25 04:44 UTC, Ricky-fight commented on projects/1.16/assets/ticbc/bettercompat/lang/zh_cn.json
> +"modifier.bettercompat.reflect.description": "当错过一次攻击时，有机会反射你对自己造成的伤害",
`攻击未命中`好一些

2023-02-25 05:30 UTC, ChuijkYahus commented on projects/1.16/assets/ticbc/bettercompat/lang/zh_cn.json
> +"modifier.bettercompat.reflect.description": "当错过一次攻击时，有机会反射你对自己造成的伤害",
感谢，当时连续审核脑子昏掉了（）
之前有看过[源码](https://github.com/ianm1647/bettercompat/blob/main/src/main/java/com/bettercompat/main/modifiers/trait/ReflectModifier.java)，确实是attacker未命中的时候触发的
不过那个self_hurt作为伤害来源有点怪

推测是没命中就打自己一下，然后把这个反弹出去（）
可能和BetterNether里的红宝石特性有关吧

2023-04-01 07:13 UTC, ChuijkYahus commented
* 7+7时限进入第二阶段，请注意查看审核意见

@wanji404

2023-04-01 07:21 UTC, closed without merging