提交goblins-dungeons模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #2971
Opened 2023-02-04 06:25 UTC by wanji404

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-04 15:57 UTC, Ricky-fight commented
/format projects/1.16/assets/goblins-dungeons/goblinsanddungeons/lang/en_us.json

2023-02-04 16:10 UTC, Ricky-fight requested changes
除了下列的建议，还需要注意一下全角符号的问题：`,`->`，`,':'->'：'等

2023-02-04 16:10 UTC, Ricky-fight commented on projects/1.16/assets/goblins-dungeons/goblinsanddungeons/lang/zh_cn.json
> +  "block.goblinsanddungeons.chiseled_scoria_bricks": "裂纹火山岩砖",
```suggestion
  "block.goblinsanddungeons.chiseled_scoria_bricks": "裂纹火山岩砖块",

```

2023-02-04 16:10 UTC, Ricky-fight commented on projects/1.16/assets/goblins-dungeons/goblinsanddungeons/lang/zh_cn.json
> +  "item.minecraft.tipped_arrow.effect.ogres_might": "魔兽箭",
```suggestion
  "item.minecraft.tipped_arrow.effect.ogres_might": "魔兽之箭",
```

2023-02-04 16:10 UTC, Ricky-fight commented on projects/1.16/assets/goblins-dungeons/goblinsanddungeons/lang/zh_cn.json
> +  "goblin_crown": "戴在头上时，附近所有的哥布林会获得虚弱II效果,并使其他的敌对生物获得虚弱I效果。它还将所有哥布林对佩戴者的检测范围减少50%",
```suggestion
  "goblin_crown": "戴在头上时，附近所有的哥布林会获得虚弱 II效果,并使其他的敌对生物获得虚弱 I效果。它还将所有哥布林对佩戴者的感知范围减少50%",
```

2023-02-04 16:10 UTC, Ricky-fight commented on projects/1.16/assets/goblins-dungeons/goblinsanddungeons/lang/zh_cn.json
> +  "goblinsanddungeons.subtitle.gobber_snoring": "哥布林守卫: 打鼾",
```suggestion
  "goblinsanddungeons.subtitle.gobber_snoring": "哥布林守卫：打鼾",
```
其他字幕亦同此修改

2023-02-06 12:15 UTC, ChuijkYahus commented on projects/1.16/assets/goblins-dungeons/goblinsanddungeons/lang/zh_cn.json
> +  "block.goblinsanddungeons.scoria": "火山岩",
这东西倒是老被叫做`熔渣`
也有叫`熔渣石`的
不过正式名称应该是`火山渣`
可以考虑然后改下（）

2023-02-06 12:49 UTC, ChuijkYahus commented on projects/1.16/assets/goblins-dungeons/goblinsanddungeons/lang/zh_cn.json
> +  "block.goblinsanddungeons.cracked_scoria_bricks": "裂纹火山岩砖块",
```suggestion
  "block.goblinsanddungeons.scoria_bricks": "火山岩砖",
  "block.goblinsanddungeons.cracked_scoria_bricks": "裂纹火山岩砖",
```
原版没有对应砖物品的Bricks方块应该是统一不用`块`的

2023-02-07 17:04 UTC, ChuijkYahus approved these changes

2023-02-10 07:03 UTC, merged