提交Haunted-harvest模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #2972
Opened 2023-02-04 06:28 UTC by wanji404

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-04 06:49 UTC, ChuijkYahus commented
此模组已有官译，还请参照修改

2023-02-04 15:38 UTC, ChuijkYahus requested changes

2023-02-04 15:38 UTC, ChuijkYahus commented on projects/1.16/assets/haunted-harvest/hauntedharvest/lang/zh_cn.json
> +  "item.hauntedharvest.bundle": "Bundle"
```suggestion
	"item.hauntedharvest.grim_apple": "诡戾苹果",
    "item.hauntedharvest.rotten_apple": "烂苹果",
  "item.hauntedharvest.bundle": "纸袋"
```

2023-02-06 08:12 UTC, wanji404 commented on projects/1.16/assets/haunted-harvest/hauntedharvest/lang/zh_cn.json
> +  "item.hauntedharvest.bundle": "Bundle"
已修改

2023-02-06 08:52 UTC, ChuijkYahus approved these changes

2023-02-07 08:27 UTC, merged