提交hunterillager模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #2973
Opened 2023-02-04 07:07 UTC by wanji404

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-04 17:22 UTC, Ricky-fight requested changes

2023-02-04 17:22 UTC, Ricky-fight commented on projects/1.16/assets/hunterillager/hunterillager/lang/zh_cn.json
> +  "item.hunterillager.quiver.desc": "您可以同时拿着箭袋和箭头右键单击来存储箭头.",
```suggestion
  "item.hunterillager.quiver.desc": "你可以同时拿着箭袋和箭右键单击来存储箭。",

```

2023-02-04 17:22 UTC, Ricky-fight commented on projects/1.16/assets/hunterillager/hunterillager/lang/zh_cn.json
> +  "subtitles.hunterillager.laugh": "邪猎者笑声",
```suggestion
  "subtitles.hunterillager.laugh": "邪猎者：暗笑",

```

2023-02-04 17:22 UTC, Ricky-fight commented on projects/1.16/assets/hunterillager/hunterillager/lang/zh_cn.json
> +  "death.attack.hunterillager.boomerang": "%1$s 被回旋镖击中了",
```suggestion
  "death.attack.hunterillager.boomerang": "%1$s被回旋镖击中了",

```

2023-02-04 17:22 UTC, Ricky-fight commented on projects/1.16/assets/hunterillager/hunterillager/lang/zh_cn.json
> +  "death.attack.hunterillager.boomerang.player": "%1$s 被 %2$s 的回旋镖击中了",
```suggestion
  "death.attack.hunterillager.boomerang.player": "%1$s被%2$s的回旋镖击中了",
```

2023-02-04 17:22 UTC, Ricky-fight commented on projects/1.16/assets/hunterillager/hunterillager/lang/zh_cn.json
> +  "hunterillager.config.generateHunterHouse": "generate HunterHouse In OverWorld",
```suggestion
  "hunterillager.config.generateHunterHouse": "在主世界生成邪猎者小屋",
```

2023-02-04 17:22 UTC, Ricky-fight commented on projects/1.16/assets/hunterillager/hunterillager/lang/zh_cn.json
> +  "hunterillager.config.spawnHunterIllagerOnPatrol": "Spawn HunterIllager On Patrol",
```suggestion
  "hunterillager.config.spawnHunterIllagerOnPatrol": "生成邪猎者巡逻队",
```
这里需要看实际游戏内表现

2023-02-06 09:20 UTC, wanji404 commented on projects/1.16/assets/hunterillager/hunterillager/lang/zh_cn.json
> +  "hunterillager.config.spawnHunterIllagerOnPatrol": "Spawn HunterIllager On Patrol",
这样翻译就行，谢谢：）

2023-02-06 09:20 UTC, wanji404 commented on projects/1.16/assets/hunterillager/hunterillager/lang/zh_cn.json
> +  "hunterillager.config.generateHunterHouse": "generate HunterHouse In OverWorld",
已修改

2023-02-06 09:20 UTC, wanji404 commented on projects/1.16/assets/hunterillager/hunterillager/lang/zh_cn.json
> +  "death.attack.hunterillager.boomerang": "%1$s 被回旋镖击中了",
已修改

2023-02-06 09:20 UTC, wanji404 commented on projects/1.16/assets/hunterillager/hunterillager/lang/zh_cn.json
> +  "subtitles.hunterillager.laugh": "邪猎者笑声",
已修改

2023-02-06 12:36 UTC, ChuijkYahus commented on projects/1.16/assets/hunterillager/hunterillager/lang/zh_cn.json
> +  "hunterillager.config.spawnHunterIllagerOnPatrol": "Spawn HunterIllager On Patrol",
这个该不会是指在灾厄巡逻队中生成邪猎者吧
https://minecraft.fandom.com/zh/wiki/%E7%81%BE%E5%8E%84%E5%B7%A1%E9%80%BB%E9%98%9F

2023-02-06 15:13 UTC, wanji404 commented on projects/1.16/assets/hunterillager/hunterillager/lang/zh_cn.json
> +  "hunterillager.config.spawnHunterIllagerOnPatrol": "Spawn HunterIllager On Patrol",
有~道~理~

2023-02-06 15:14 UTC, ChuijkYahus approved these changes

2023-02-06 16:15 UTC, Ricky-fight approved these changes

2023-02-07 09:48 UTC, merged