提交Illagers模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #2974
Opened 2023-02-04 07:14 UTC by wanji404

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-04 16:53 UTC, Ricky-fight requested changes
配置也是模组游玩体验的一部分，辛苦了（）
最好也翻译一下（）

2023-03-13 16:13 UTC, mamaruo commented on projects/1.16/assets/illagers/illagers_plus/lang/zh_cn.json
> +  "illagers_plus.advancements.spawn_reinforcements.description": "迫使一名掠夺将军在掠夺要塞中派出援兵",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |

原文：**Force an Illager General to Spawn Reinforcements in an Illager Fort**
```suggestion
  "illagers_plus.advancements.spawn_reinforcements.description": "迫使灾厄要塞中的灾厄将军派出援兵",
```

2023-03-13 16:13 UTC, mamaruo commented on projects/1.16/assets/illagers/illagers_plus/lang/zh_cn.json
> +  "illagers_plus.advancements.find_ice_castle.title": "冰冠堡垒",
| **审查级别**    | 备注 |
|--------------|----|
| ⚪ 轻微 / 不阻止合并但需三思  |    |

原文：**Ice Castle**
为什么有“冠”？

2023-04-01 07:15 UTC, ChuijkYahus commented
* 7+7时限进入第二阶段，请注意查看各审核意见

@wanji404 

其实真要说的话，三个星期过去都可以直接关了

2023-04-01 07:21 UTC, closed without merging