提交Progressive-bosses模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #2977
Opened 2023-02-04 08:32 UTC by wanji404

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-04 09:11 UTC, mamaruo commented
我早年在 MCBBS 搬运过这个模组，还做过翻译来着

2023-02-05 14:55 UTC, Ricky-fight requested changes
1.19有[官译](https://www.curseforge.com/minecraft/mc-mods/progressive-bosses/files/4366382)了可以去参照，目前这个没官译整得漂亮（）

2023-02-06 12:46 UTC, ChuijkYahus requested changes

2023-02-06 12:46 UTC, ChuijkYahus commented on projects/1.16/assets/progressive-bosses/progressivebosses/lang/zh_cn.json
> +  "entity.progressivebosses.wither_minion": "凋零爪牙",
```suggestion
  "entity.progressivebosses.wither_minion": "凋灵爪牙",
```

2023-02-06 12:46 UTC, ChuijkYahus commented on projects/1.16/assets/progressive-bosses/progressivebosses/lang/zh_cn.json
> +  "progressivebosses:command.player_get_wither_difficulty": "%s已经召唤了%d只凋零",
```suggestion
  "progressivebosses:command.player_get_wither_difficulty": "%s已经召唤了%d只凋灵",
```

2023-02-06 12:46 UTC, ChuijkYahus commented on projects/1.16/assets/progressive-bosses/progressivebosses/lang/zh_cn.json
> +  "wither.first_summon": "你生成了第一只凋零。请注意，每生成一只凋零，都将让下一只更加强大。",
```suggestion
  "wither.first_summon": "你生成了第一只凋灵。请注意，每生成一只凋灵，都将让下一只更加强大。",
```

2023-02-06 12:46 UTC, ChuijkYahus commented on projects/1.16/assets/progressive-bosses/progressivebosses/lang/zh_cn.json
> +  "progressivebosses:command.summoned_entity": "在难度%d下生成了%s",
```suggestion
  "progressivebosses:command.summoned_entity": "在难度%2$d下生成了%1$s",
```

2023-02-06 12:46 UTC, ChuijkYahus commented on projects/1.16/assets/progressive-bosses/progressivebosses/lang/zh_cn.json
> +  "progressivebosses:command.player_add_boss_difficulty": "增加了%d %s的难度至%s（当前为%d）",
原文的参数安排真没看懂（）

2023-02-15 07:43 UTC, ChuijkYahus commented
* 7+7时限进入第一阶段。从该评论发出的时间开始计时。

ping @wanji404

2023-02-16 03:58 UTC, wanji404 commented on projects/1.16/assets/progressive-bosses/progressivebosses/lang/zh_cn.json
> +  "entity.progressivebosses.wither_minion": "凋零爪牙",
已修改

2023-02-16 03:58 UTC, wanji404 commented on projects/1.16/assets/progressive-bosses/progressivebosses/lang/zh_cn.json
> +  "progressivebosses:command.player_get_wither_difficulty": "%s已经召唤了%d只凋零",
已修改

2023-02-16 03:58 UTC, wanji404 commented on projects/1.16/assets/progressive-bosses/progressivebosses/lang/zh_cn.json
> +  "progressivebosses:command.player_add_boss_difficulty": "增加了%d %s的难度至%s（当前为%d）",
已修改

2023-02-16 03:58 UTC, wanji404 commented on projects/1.16/assets/progressive-bosses/progressivebosses/lang/zh_cn.json
> +  "progressivebosses:command.summoned_entity": "在难度%d下生成了%s",
已修改

2023-02-16 03:58 UTC, wanji404 commented on projects/1.16/assets/progressive-bosses/progressivebosses/lang/zh_cn.json
> +  "wither.first_summon": "你生成了第一只凋零。请注意，每生成一只凋零，都将让下一只更加强大。",
已修改

2023-04-01 07:16 UTC, ChuijkYahus approved these changes

2023-04-01 07:21 UTC, closed without merging