提交restored-earth模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #2978
Opened 2023-02-04 09:01 UTC by wanji404

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-04 16:35 UTC, Ricky-fight requested changes
可能有漏的（）
最好自己再检查检查

2023-02-04 16:35 UTC, Ricky-fight commented on projects/1.16/assets/restored-earth/restored_earth/lang/zh_cn.json
> +  "entity.restored_earth.cluckshroom": "坤菇",
```suggestion
  "entity.restored_earth.cluckshroom": "咯咯菇",
```
这个用语是上不得台面的，请注意一下

2023-02-04 16:35 UTC, Ricky-fight commented on projects/1.16/assets/restored-earth/restored_earth/lang/zh_cn.json
> +  "entity.restored_earth.rainbow_sheep": " 彩虹羊",
```suggestion
  "entity.restored_earth.rainbow_sheep": "彩虹绵羊",
```

2023-02-04 16:35 UTC, Ricky-fight commented on projects/1.16/assets/restored-earth/restored_earth/lang/zh_cn.json
> +  "entity.restored_earth.moobloom": "哞茛",
能说明一下译名的来源吗？没有理解用这个字背后的意图

2023-02-04 16:35 UTC, Ricky-fight commented on projects/1.16/assets/restored-earth/restored_earth/lang/zh_cn.json
> +  "item.restored_earth.viler_witch_spawn_egg": "邪恶女巫刷怪蛋",
```suggestion
  "item.restored_earth.viler_witch_spawn_egg": "卑鄙女巫刷怪蛋",
```

2023-02-04 16:35 UTC, Ricky-fight commented on projects/1.16/assets/restored-earth/restored_earth/lang/zh_cn.json
> +  "entity.restored_earth.viler_witch": "邪恶女巫",
```suggestion
  "entity.restored_earth.viler_witch": "卑鄙女巫",
```

2023-02-04 16:35 UTC, Ricky-fight commented on projects/1.16/assets/restored-earth/restored_earth/lang/zh_cn.json
> +  "item.restored_earth.cluckshroom_spawn_egg": "坤菇刷怪蛋",
```suggestion
  "item.restored_earth.cluckshroom_spawn_egg": "咯咯菇刷怪蛋",
```

2023-02-04 16:35 UTC, Ricky-fight commented on projects/1.16/assets/restored-earth/restored_earth/lang/zh_cn.json
> +  "block.restored_earth.mud": "泥土",
```suggestion
  "block.restored_earth.mud": "泥巴",
```

2023-02-04 16:35 UTC, Ricky-fight commented on projects/1.16/assets/restored-earth/restored_earth/lang/zh_cn.json
> +  "block.restored_earth.rainbow_carpet": "彩虹毯",
```suggestion
  "block.restored_earth.rainbow_carpet": "彩虹色地毯",
```

2023-02-04 16:35 UTC, Ricky-fight commented on projects/1.16/assets/restored-earth/restored_earth/lang/zh_cn.json
> +  "block.restored_earth.rainbow_bed": "彩虹床",
```suggestion
  "block.restored_earth.rainbow_bed": "彩虹色床",
```

2023-02-04 16:35 UTC, Ricky-fight commented on projects/1.16/assets/restored-earth/restored_earth/lang/zh_cn.json
> +  "block.restored_earth.rainbow_wool": "彩虹羊毛",
```suggestion
  "block.restored_earth.rainbow_wool": "彩虹色羊毛",
```

2023-02-04 16:35 UTC, Ricky-fight commented on projects/1.16/assets/restored-earth/restored_earth/lang/zh_cn.json
> +  "block.restored_earth.carved_melon": "雕刻西瓜",
```suggestion
  "block.restored_earth.carved_melon": "雕刻过的西瓜",
```

2023-02-04 16:35 UTC, Ricky-fight commented on projects/1.16/assets/restored-earth/restored_earth/lang/zh_cn.json
> +  "block.restored_earth.pink_daisy": "粉色雏菊",
```suggestion
  "block.restored_earth.pink_daisy": "粉红色雏菊",
```

2023-02-04 16:35 UTC, Ricky-fight commented on projects/1.16/assets/restored-earth/restored_earth/lang/zh_cn.json
> +  "subtitles.entity.bone_spider.death": "骨蜘蛛死亡",
```suggestion
  "subtitles.entity.skeleton_wolf.idle": "骷髅狼：喘息",
  "subtitles.entity.skeleton_wolf.hurt": "骷髅狼：受伤",
  "subtitles.entity.skeleton_wolf.death": "骷髅狼：死亡",
  "subtitles.entity.bone_spider.idle": "骨蜘蛛：嘶嘶",
  "subtitles.entity.bone_spider.death": "骨蜘蛛：死亡",
```

2023-02-06 12:39 UTC, ChuijkYahus commented on projects/1.16/assets/restored-earth/restored_earth/lang/zh_cn.json
> +  "entity.restored_earth.moobloom": "哞茛",
https://minecraft.fandom.com/zh/wiki/Minecraft_Earth:%E5%93%9E%E8%8A%B1
```suggestion
  "entity.restored_earth.moobloom": "哞花",
```
这里的`茛`应该是指毛茛，毕竟都是黄色的（）

2023-02-06 12:58 UTC, ChuijkYahus commented
![图片](https://user-images.githubusercontent.com/94828194/216977320-2a1268a1-7483-4975-aa8f-fa9257ae2546.png)
https://minecraft.fandom.com/zh/wiki/Minecraft_Earth
照这个改吧

2023-02-06 15:06 UTC, Ricky-fight commented
为我的阅历贫瘠抱歉，之前的review涉及到Minecraft Earth相关的译名建议作废

2023-02-06 15:08 UTC, ChuijkYahus commented
查这个之前我也不知道earth加了这么多~~有的没的~~东西（）
还是看pr后才知道的

2023-02-22 07:55 UTC, Ricky-fight commented
@wanji404 上面没解决的suggestion还是要改的

2023-04-01 07:17 UTC, ChuijkYahus commented
* 7+7时限进入第二阶段，请注意查看各审核意见

@wanji404

2023-04-01 07:21 UTC, closed without merging