提交simply-hot-springs模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #2983
Opened 2023-02-04 09:49 UTC by wanji404

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-04 13:28 UTC, ChuijkYahus requested changes
后面怎么没翻啊

2023-02-04 13:55 UTC, wanji404 commented
后面大部分都是模组设置了，不大会翻译这个

2023-02-04 18:13 UTC, ChuijkYahus commented
> 后面大部分都是模组设置了，不大会翻译这个

模组配置也是游戏体验的一部分，最好还是翻下吧，辛苦

2023-02-22 07:45 UTC, Ricky-fight commented
- 7+7时限进入第一阶段。从该评论发出的时间开始计时。

    ping @wanji404

2023-04-01 07:12 UTC, ChuijkYahus commented
* 7+7时限已到，如需提交可自行reopen

2023-04-01 07:12 UTC, closed without merging