提交snail-mail模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #2986
Opened 2023-02-04 11:23 UTC by wanji404

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-04 13:54 UTC, Ricky-fight requested changes
除了下列建议，还需要注意：统一一下全角符号，比如`!`->`！`,`.`->`。`等等；以及统一一下到底是`信箱`还是`邮箱`，做到模组内统一就好，具体取哪个我没意见（）

2023-02-04 13:54 UTC, Ricky-fight commented on projects/1.16/assets/snail-mail/snailmail/lang/zh_cn.json
> +    "itemGroup.snailmail.main": "蜗牛信箱",
```suggestion
    "itemGroup.snailmail.main": "蜗牛邮政",
```
看看有没有更有意思的译法？

2023-02-04 13:54 UTC, Ricky-fight commented on projects/1.16/assets/snail-mail/snailmail/lang/zh_cn.json
> +    "item.snailmail.envelope_closed": "信封 (未拆)",
```suggestion
    "item.snailmail.envelope_open": "信封（已拆）",
    "item.snailmail.envelope_closed": "信封（未拆）",
```

2023-02-04 13:54 UTC, Ricky-fight commented on projects/1.16/assets/snail-mail/snailmail/lang/zh_cn.json
> +    "tooltip.snailmail.from": "来自: %s",
```suggestion
    "tooltip.snailmail.to": "送往：%s",
    "tooltip.snailmail.from": "来自：%s",
```

2023-02-04 13:54 UTC, Ricky-fight commented on projects/1.16/assets/snail-mail/snailmail/lang/zh_cn.json
> +    "modal.snailmail.no_envelope": "服务器上的插槽中没有信封...可能发生了错误?",
```suggestion
    "modal.snailmail.no_envelope": "服务器上的邮件槽中没有信封……可能发生了错误？",
```
请使用`……`(中文输入法下shift+6)表示省略号（

2023-02-04 13:54 UTC, Ricky-fight commented on projects/1.16/assets/snail-mail/snailmail/lang/zh_cn.json
> +    "modal.snailmail.located": "位于: %s in %s",
```suggestion
    "modal.snailmail.located": "位于：%s在%s",
```
```suggestion
    "modal.snailmail.located": "位于: %2$s的%1$s",
```
需要看实际游戏测试效果择其一

2023-02-04 13:54 UTC, Ricky-fight commented on projects/1.16/assets/snail-mail/snailmail/lang/zh_cn.json
> +    "modal.snailmail.no_location": "私人地址",
```suggestion
    "modal.snailmail.no_location": "该地址为私有",
```

2023-02-04 13:54 UTC, Ricky-fight commented on projects/1.16/assets/snail-mail/snailmail/lang/zh_cn.json
> +    "message.snailmail.noperm": "您无权打开此邮箱。",
```suggestion
    "message.snailmail.noperm": "您无权打开此蜗牛邮箱。",
```

2023-02-04 13:54 UTC, Ricky-fight commented on projects/1.16/assets/snail-mail/snailmail/lang/zh_cn.json
> +    "config.snailmail": "Snail Mail 设置",
```suggestion
    "config.snailmail": "蜗牛邮政设置",
```
注意一下这边需要和上面最后敲定的译名同步，不一定就是这个（）

2023-02-04 13:54 UTC, Ricky-fight commented on projects/1.16/assets/snail-mail/snailmail/lang/zh_cn.json
> +    "config.snailmail.lock_boxes": "锁蜗牛信箱？",
```suggestion
    "config.snailmail.lock_boxes": "锁定蜗牛信箱？",
```
怎么没有解锁蜗牛信箱（）

2023-02-06 07:00 UTC, wanji404 commented on projects/1.16/assets/snail-mail/snailmail/lang/zh_cn.json
> +    "itemGroup.snailmail.main": "蜗牛信箱",
那就“蜗牛邮政”吧，我也没什么好主意了，哈哈：）

2023-02-06 07:00 UTC, wanji404 commented on projects/1.16/assets/snail-mail/snailmail/lang/zh_cn.json
> +    "item.snailmail.envelope_closed": "信封 (未拆)",
已修改

2023-02-06 07:00 UTC, wanji404 commented on projects/1.16/assets/snail-mail/snailmail/lang/zh_cn.json
> +    "tooltip.snailmail.from": "来自: %s",
已修改

2023-02-06 07:00 UTC, wanji404 commented on projects/1.16/assets/snail-mail/snailmail/lang/zh_cn.json
> +    "modal.snailmail.no_envelope": "服务器上的插槽中没有信封...可能发生了错误?",
已修改，感谢指教

2023-02-06 07:00 UTC, wanji404 commented on projects/1.16/assets/snail-mail/snailmail/lang/zh_cn.json
> +    "modal.snailmail.located": "位于: %s in %s",
已修改

2023-02-06 07:00 UTC, wanji404 commented on projects/1.16/assets/snail-mail/snailmail/lang/zh_cn.json
> +    "modal.snailmail.no_location": "私人地址",
已修改

2023-02-06 07:01 UTC, wanji404 commented on projects/1.16/assets/snail-mail/snailmail/lang/zh_cn.json
> +    "message.snailmail.noperm": "您无权打开此邮箱。",
已修改

2023-02-06 07:01 UTC, wanji404 commented on projects/1.16/assets/snail-mail/snailmail/lang/zh_cn.json
> +    "config.snailmail.lock_boxes": "锁蜗牛信箱？",
哈哈哈：）

2023-02-06 12:17 UTC, ChuijkYahus commented on projects/1.16/assets/snail-mail/snailmail/lang/zh_cn.json
> +    "modal.snailmail.invalid_address": "找不到与该地址名称匹配的用户： %s",
```suggestion
    "modal.snailmail.invalid_address": "找不到与该地址名称匹配的用户：%s",
```

2023-02-06 12:17 UTC, ChuijkYahus commented on projects/1.16/assets/snail-mail/snailmail/lang/zh_cn.json
> +    "modal.snailmail.no_boxes": "%s 没有任何蜗牛信箱",
```suggestion
    "modal.snailmail.no_boxes": "%s没有任何蜗牛信箱",
```

2023-02-06 12:17 UTC, ChuijkYahus commented on projects/1.16/assets/snail-mail/snailmail/lang/zh_cn.json
> +    "modal.snailmail.located": "位于：%s在%s",
```suggestion
    "modal.snailmail.located": "位于：%s，%s",
```
↑这个算是地址写法？（）
```suggestion
    "modal.snailmail.located": "位于：%2$s维度中%1$s处",
```
```suggestion
    "modal.snailmail.located": "位于：%2$s中%1$s处",
```

2023-02-06 14:43 UTC, wanji404 commented on projects/1.16/assets/snail-mail/snailmail/lang/zh_cn.json
> +    "modal.snailmail.located": "位于：%s在%s",
已修改

2023-02-06 14:44 UTC, wanji404 commented on projects/1.16/assets/snail-mail/snailmail/lang/zh_cn.json
> +    "modal.snailmail.no_boxes": "%s 没有任何蜗牛信箱",
已修改

2023-02-06 14:48 UTC, Ricky-fight approved these changes

2023-02-07 09:45 UTC, merged