提交wandering-bag模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #2987
Opened 2023-02-04 11:30 UTC by wanji404

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-04 14:31 UTC, Ricky-fight requested changes

2023-02-04 14:31 UTC, Ricky-fight commented on projects/1.16/assets/wandering-bag/wandering_bag/lang/zh_cn.json
> +  "entity.wandering_bag.tamed_ravager": "驯服的掠夺兽",
```suggestion
  "entity.wandering_bag.tamed_ravager": "驯服的劫掠兽",
```

2023-02-04 14:31 UTC, Ricky-fight commented on projects/1.16/assets/wandering-bag/wandering_bag/lang/zh_cn.json
> +  "item.wandering_bag.hammer_from_farlands": "§e边境之锤",
该不会是和farlands有py吧（）

2023-02-04 14:31 UTC, Ricky-fight commented on projects/1.16/assets/wandering-bag/wandering_bag/lang/zh_cn.json
> +  "item.wandering_bag.wither_bone_meal": "§d凋零骨粉",
```suggestion
  "item.wandering_bag.wither_bone_meal": "§d凋灵骨粉",
```

2023-02-04 14:31 UTC, Ricky-fight commented on projects/1.16/assets/wandering-bag/wandering_bag/lang/zh_cn.json
> +  "item.wandering_bag.spell_pr": "Spell Pr",
这个是什么

2023-02-04 14:31 UTC, Ricky-fight commented on projects/1.16/assets/wandering-bag/wandering_bag/lang/zh_cn.json
> +  "item.wandering_bag.spices_from_elsewhere": "§e异地香料",
```suggestion
  "item.wandering_bag.spices_from_elsewhere": "§e异域香料",
```
这样如何

2023-02-04 14:31 UTC, Ricky-fight commented on projects/1.16/assets/wandering-bag/wandering_bag/lang/zh_cn.json
> +  "item.wandering_bag.ravager_horn": "§b掠夺号角",
```suggestion
  "item.wandering_bag.ravager_horn": "§b劫掠兽角",
```

2023-02-04 14:31 UTC, Ricky-fight commented on projects/1.16/assets/wandering-bag/wandering_bag/lang/zh_cn.json
> +  "subtitles.ravager_horn": "掠夺号角",
```suggestion
  "subtitles.ravager_horn": "劫掠兽角：吹奏",
```
是不是和[山羊角](https://minecraft.fandom.com/zh/wiki/%E5%B1%B1%E7%BE%8A%E8%A7%92)类似的吹奏声音字幕？

2023-02-04 14:31 UTC, Ricky-fight commented on projects/1.16/assets/wandering-bag/wandering_bag/lang/zh_cn.json
> +  "item.wandering_bag.sword_from_elsewhere": "§e异地之剑"
```suggestion
  "item.wandering_bag.sword_from_elsewhere": "§e异域之剑"
```
同上，如需改动这里需要同步一下

2023-02-06 07:13 UTC, wanji404 commented on projects/1.16/assets/wandering-bag/wandering_bag/lang/zh_cn.json
> +  "item.wandering_bag.dagger_of_traitor": "§b背叛之刃",
还是 背叛之刃 吧，像 背叛之剑 和 背叛之刃 这样子来区分剑与匕首就行

2023-02-06 07:13 UTC, wanji404 commented on projects/1.16/assets/wandering-bag/wandering_bag/lang/zh_cn.json
> +  "item.wandering_bag.hammer_from_farlands": "§e边境之锤",
嘿嘿

2023-02-06 07:14 UTC, wanji404 commented on projects/1.16/assets/wandering-bag/wandering_bag/lang/zh_cn.json
> +  "item.wandering_bag.hammer_from_farlands": "§e边境之锤",
：）

2023-02-06 07:15 UTC, wanji404 commented on projects/1.16/assets/wandering-bag/wandering_bag/lang/zh_cn.json
> +  "item.wandering_bag.spices_from_elsewhere": "§e异地香料",
好听！

2023-02-06 07:15 UTC, wanji404 commented on projects/1.16/assets/wandering-bag/wandering_bag/lang/zh_cn.json
> +  "subtitles.ravager_horn": "掠夺号角",
是的，感谢指教

2023-02-06 07:16 UTC, wanji404 commented on projects/1.16/assets/wandering-bag/wandering_bag/lang/zh_cn.json
> +  "item.wandering_bag.sword_from_elsewhere": "§e异地之剑"
已修改

2023-02-06 07:16 UTC, wanji404 commented on projects/1.16/assets/wandering-bag/wandering_bag/lang/zh_cn.json
> +  "entity.wandering_bag.tamed_ravager": "驯服的掠夺兽",
已修改

2023-02-06 07:16 UTC, wanji404 commented on projects/1.16/assets/wandering-bag/wandering_bag/lang/zh_cn.json
> +  "item.wandering_bag.wither_bone_meal": "§d凋零骨粉",
已修改

2023-02-06 07:30 UTC, wanji404 commented on projects/1.16/assets/wandering-bag/wandering_bag/lang/zh_cn.json
> +  "item.wandering_bag.spell_pr": "Spell Pr",
不清楚呢，似乎没有实装

2023-02-06 08:54 UTC, ChuijkYahus commented on projects/1.16/assets/wandering-bag/wandering_bag/lang/zh_cn.json
> +  "entity.wandering_bag.tamed_ravager": "驯服的掠夺兽",
貌似没改上

2023-02-06 11:42 UTC, ChuijkYahus commented on projects/1.16/assets/wandering-bag/wandering_bag/lang/zh_cn.json
> +  "item.wandering_bag.spell_pr": "Spell Pr",
总感觉是未定符咒发出的子弹？
可以试试看能不能发出弹射物（）

2023-02-06 14:08 UTC, Ricky-fight commented on projects/1.16/assets/wandering-bag/wandering_bag/lang/zh_cn.json
> +  "item.wandering_bag.spell_pr": "Spell Pr",
可以用give命令拿几个出来看看

2023-02-06 14:13 UTC, Ricky-fight approved these changes
应该没大问题了，还有一个spell pr最好用give命令看看是什么（）

2023-02-11 08:23 UTC, ChuijkYahus commented on projects/1.16/assets/wandering-bag/wandering_bag/lang/zh_cn.json
> +  "item.wandering_bag.spell_pr": "Spell Pr",
ping一下 @wanji404

2023-02-22 07:34 UTC, Ricky-fight commented
ping @wanji404

2023-02-28 10:18 UTC, Ricky-fight commented
ping @wanji404

2023-04-01 07:11 UTC, closed without merging

2023-04-01 07:12 UTC, ChuijkYahus commented
* 7+7时限已到，如需提交可自行reopen

@wanji404