提交 weaponmaster 模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #2991
Opened 2023-02-04 16:07 UTC by MuMu-5528

- [x ] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x ] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-04 16:11 UTC, Ricky-fight commented
`[x ]`的空格需要删去

2023-02-07 14:40 UTC, Cactusstudent commented
/add-mapping weapon-master 782886

2023-02-09 11:16 UTC, StarryCamile reviewed
152 行 fel低应该是fellow吧（

2023-02-09 12:18 UTC, Ricky-fight requested changes
这份交上来的只能叫机翻半成品（）
如果确实是半成品请设为draft

2023-02-10 20:10 UTC, Kasualix requested changes
机翻真是太酸爽了

2023-02-10 20:10 UTC, Kasualix commented on projects/1.18/assets/weapon-master/weaponmaster/lang/zh_cn.json
> +    "gui.weaponmaster.page1_5": "您将使用它兑换您的武器选择以及升级/定制。",
```suggestion
    "gui.weaponmaster.page1_5": "你将使用它来丰富你的武器选择，并对它们进行升级/自定义。",
```

2023-02-10 20:10 UTC, Kasualix commented on projects/1.18/assets/weapon-master/weaponmaster/lang/zh_cn.json
> +	"gui.weaponmaster.page1_7": "(它会复制你的底部方块！)",
其实是“它会复制自身底部方块的纹理！”

2023-02-10 20:10 UTC, Kasualix commented on projects/1.18/assets/weapon-master/weaponmaster/lang/zh_cn.json
> +    "gui.weaponmaster.page2_3": "3-长柄武器",
```suggestion
    "gui.weaponmaster.page2_3": "3-长柄刀",
```

2023-02-10 20:10 UTC, Kasualix commented on projects/1.18/assets/weapon-master/weaponmaster/lang/zh_cn.json
> +    "gui.weaponmaster.page2_5": "这些被分为敏捷和超重、横扫和精密",
```suggestion
    "gui.weaponmaster.page2_5": "它们被分为敏捷和超重、横扫和精密四类",
```

2023-02-10 20:10 UTC, Kasualix commented on projects/1.18/assets/weapon-master/weaponmaster/lang/zh_cn.json
> +    "gui.weaponmaster.page4_2": "确认项目",
```suggestion
    "gui.weaponmaster.page4_2": "确认应用到物品上",

```

2023-02-10 20:10 UTC, Kasualix commented on projects/1.18/assets/weapon-master/weaponmaster/lang/zh_cn.json
> +    "gui.weaponmaster.page9_1": "ForsetCabiri: 艺术、设计、宣传/页面和概念。",
```suggestion
    "gui.weaponmaster.page9_1": "ForsetCabiri:美术 、设计、宣传/页面和概念。",
```

2023-02-10 20:14 UTC, Kasualix commented
我曾经译过这模组两次，都因为部件种类实在过多然后不了了之，文件随手删除后也找不到了。
但你这抽象的机翻属实给我燃起来了，这 pr 我劝是 close 得了，我回头再译一版交上来。

2023-02-13 23:49 UTC, FERRIJianyue commented on projects/1.18/assets/weapon-master/weaponmaster/lang/zh_cn.json
> +    "gui.weaponmaster.page2_1": "1-轻剑",
长剑

2023-02-14 11:25 UTC, Ricky-fight commented
ping @MuMu-5528

2023-02-22 05:31 UTC, Ricky-fight commented
再ping @MuMu-5528 
按7+7第二阶段处理了

2023-02-28 10:16 UTC, closed without merging

2023-02-28 10:17 UTC, Ricky-fight commented
作者7日后仍未回复，该PR被暂时关闭，若需继续提交可届时重新开启PR。