提交Heat and Climate热量与气候的翻译文件（模组内置翻译有误，自行修改了部分条目，但不保证全部修订完毕）
CFPAOrg/Minecraft-Mod-Language-Package pull request #2996
Opened 2023-02-05 12:12 UTC by komeiji-koyomi

特别说明：作者是日本人，原生语言文件应该是日文与英语，因为不确定是哪个所以都传上来了。
日语里部分条目（是工具的tooltips）原文就很中二，可能有部分个人发挥在内，是正常现象。

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2023-02-05 14:04 UTC, Ricky-fight commented
括号里的放在pr描述里就行，不用写在标题里（）

2023-02-07 08:08 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +item.dcs_tinder_fire.name=点燃的引火物
这里为了方便游戏内辨识没有一一对应翻译

2023-02-07 08:09 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +item.dcs_gem_tsavorite.name=沙弗莱石
这里在考虑到底要不要带上“石”字

2023-02-07 08:10 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +item.dcs_gem_opal.name=黑蛋白石
在考虑是否要用“欧泊”这一翻译

2023-02-07 08:12 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +item.dcs_reagent_bottle_aromatic_compound.name=芳香族化合物
游戏内难以通过合成配方推断出具体是哪种或哪类化合物，只能采用直译（如果有更好的建议希望在下面评论）

2023-02-07 08:13 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +item.dcs_coating_tool_plastic.name=镀塑剂
这些镀xx剂我个人感觉不妥，但是暂时想不到更好的方案

2023-02-07 08:14 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +## flavor texts
这个分类的文本原文就较为……嗯……中二？
部分采用了意译，并且有部分条目仍然不够符合中文语法（个人观点），等待建议。

2023-02-07 08:16 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +dcs.gui.device.shitirin=日式炭炉
原文“七轮”经过查找资料确定为错误翻译，实际应当为“七厘炭炉”，为了游戏内方便查找使用“日式炭炉”翻译，并将“七厘”相关知识写在了tooltip内（原文没有）

2023-02-07 08:19 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +dcs.gui.message.brewing.badclimate=周围状态要求 COOL~HOT 温度, NORMAL~WET 湿度, TIGHT~NORMAL 通风
之前给原作者提交翻译的人把三个条件均翻译为NORMAL，但是根据游戏内实际情况，得出原文的含义是“不那么极端”的气候条件，而非精确限定在“NORMAL”这一环境，所以按照游戏内的实际情况翻译了

2023-02-07 08:33 UTC, Ricky-fight requested changes
大致看了看（）
标点符号首先批量修改一下（）

2023-02-07 08:33 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +item.dcs_adapter_card_item_input.name=传输卡片(物品/输入)
> 请与原版 Minecraft 保持统一，使用中文的标点符号。如果是保留不翻译的英文中的标点符号，则仍保留英文的标点符号（[Minecraft 模组简体中文翻译规范与指南](https://cfpa.site/TransRules/)）

2023-02-07 08:33 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +item.dcs_oreitem_green_1.name=锡矿石
```suggestion
item.dcs_oreitem_green_1.name=锡矿
```
```suggestion
item.dcs_oreitem_green_1.name=锡石
```
下面还有`Cassiterite`，注意一下统一

2023-02-07 08:33 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +tile.dcs_ore_stone_2.name=蓝色玉髓矿
```suggestion
tile.dcs_ore_stone_2.name=蓝色玉髓矿石
```
注意一下`Ore`有没有译出来，下面看到好几个漏的

2023-02-07 08:33 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +tile.dcs_ore2_stone_6.name=蛇纹岩
```suggestion
tile.dcs_ore2_stone_6.name=蛇纹石
```

2023-02-07 08:33 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +item.dcs_miscdust_mica.name=云母
```suggestion
item.dcs_miscdust_mica.name=云母粉
```

2023-02-07 08:33 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +dcs.comment.flavor.color_gauntlet2.4=走到哪儿,光就照到哪儿,她所到之地,处处是光明.
> 请与原版 Minecraft 保持统一，使用中文的标点符号。如果是保留不翻译的英文中的标点符号，则仍保留英文的标点符号（[Minecraft 模组简体中文翻译规范与指南](https://cfpa.site/TransRules/)）

2023-02-07 08:35 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +item.dcs_gem_opal.name=黑蛋白石
opal我记得群内讨论过结论是蛋白石（）

2023-02-07 08:38 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +item.dcs_creative_drill_normal.name=(创造模式专用)乌鸦钻
突然开始心累了咋办（原翻译者留了一堆烂摊子）

2023-02-07 08:40 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +item.dcs_oreitem_green_1.name=锡矿石
非常要命的是，这模组有好多个不同的锡矿石（有的是旧版本物品即将弃用），而且使用的名字各不相同
心累

2023-02-07 08:42 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +tile.dcs_ore2_stone_6.name=蛇纹岩
这里的确不能使用“蛇纹石”作为翻译，因为这里的蛇纹岩是放置在世界中的矿物类方块，后续的“蛇纹石”是挖掘得到的宝石类物品。

2023-02-07 08:43 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +item.dcs_miscdust_mica.name=云母
嗯……模组自己有且只有这一个和云母有关的物品，并且好像并没有作为“云母粉”的矿辞注册，材质也并不是粉而是几颗小颗粒的云母……大概不用强调“粉”的属性吧

2023-02-07 08:46 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +tile.dcs_ore_stone_2.name=蓝色玉髓矿
#old往下的是之前翻译者留下的……奇妙遗留？
多数已经在上方有所体现并且已经从游戏内移除了，但是因为下方的留言仍然留着这段……我在想到底该不该删除

2023-02-07 08:52 UTC, Ricky-fight requested changes
还有半角逗号句号感叹号没改

2023-02-07 08:52 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +dcs.comment.card4.1=生成矽卡岩矿脉（占地5x5 区块）
```suggestion
dcs.comment.card4.1=生成矽卡岩矿脉（占地5x5区块）
```
还有下面3x3

2023-02-07 08:52 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
>  dcs.comment.card4_2=!!注意由于大面积地形覆盖造成的方块与物品损失!!
```suggestion
dcs.comment.card4_2=！！注意由于大面积地形覆盖造成的方块与物品损失！！
```
不知道其他地方还有没有

2023-02-07 08:57 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
>  dcs.comment.card4_2=!!注意由于大面积地形覆盖造成的方块与物品损失!!
我恨修烂摊子（这部分是之前的翻译者遗留的）

2023-02-07 08:58 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +item.dcs_gem_opal.name=黑蛋白石
那就不改了

2023-02-07 09:03 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +tile.dcs_ore2_stone_6.name=蛇纹岩
那
> tile.dcs_layer_stone_new_6.name=蛇纹石矿石

这里呢

2023-02-07 09:05 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +tile.dcs_ore2_stone_6.name=蛇纹岩
等会我打开游戏看一眼，我记得是几个矿石中有一个是“不止掉落蛇纹石”这种，需要翻译为蛇纹岩，其他的仍然是“蛇纹石矿石”

2023-02-07 09:05 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +tile.dcs_ore2_stone_6.name=蛇纹岩
就……日站模组，拍脑门写物品，愁坏翻译、魔改、附属作者（）

2023-02-07 09:07 UTC, Ricky-fight reviewed
看到一处算一处吧……

2023-02-07 09:07 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +tile.dcs_sofa_rattan_white_0.name=沙发（白色 藤制）
```suggestion
tile.dcs_sofa_rattan_white_0.name=沙发（白色藤制）
```

2023-02-07 09:07 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +tile.dcs_stool_rattan_white_0.name=高脚凳（白色 藤制）
```suggestion
tile.dcs_stool_rattan_white_0.name=高脚凳（白色藤制）
```

2023-02-07 09:14 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +tile.dcs_heatingmetal_steel_fail.name=易碎钢块
嗯……易碎？
还是说……失败品？
之前的翻译者到底留下多少坑啊

2023-02-07 09:16 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +tile.dcs_build_selenite_crystal.name=熔合石英玻璃
在透石膏分类，但它的合成表与透石膏无关，应该是作者的锅

2023-02-07 09:29 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +tile.dcs_device_shaft_s_0.name=黄铜轴（I型）
这里为了和他的附属保持同步修改了一下

2023-02-07 09:30 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +tile.dcs_device_shaft_l_sus_0.name=不锈钢轴（L型）
同上面的黄铜轴

2023-02-07 09:34 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +tile.dcs_leaves_dates_0.name=枣椰树叶
这里没作区分是因为树叶不会结果，果实方块是下面的条目

2023-02-08 07:44 UTC, Ricky-fight approved these changes
看不出什么问题了（）

2023-02-08 13:32 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +item.dcs_gem_serpentine.name=蛇纹石
https://baike.baidu.com/item/%E8%9B%87%E7%BA%B9%E7%8E%89 看看要不要参考

2023-02-08 13:32 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +item.dcs_gem_almandine.name=石榴石
我记得石榴石叫garnet吧（
https://baike.baidu.com/item/%E9%93%81%E9%93%9D%E6%A6%B4%E7%9F%B3

2023-02-08 13:32 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +item.dcs_gem_bauxite.name=铝土矿
```suggestion
item.dcs_gem_bauxite.name=铝矾石
```
https://baike.baidu.com/item/%E9%93%9D%E7%9F%BE%E7%9F%B3
虽说颜色不太一样（）

2023-02-08 13:43 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +item.dcs_gem_almandine.name=石榴石
铁铝榴石是石榴石中红色的一种，英文的确是这个，但是铁铝榴石是矿物名，这里打算用宝石名
并且其他模组都是“红色”的石榴石，方便记忆的话还是就用石榴石吧

2023-02-08 13:43 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +item.dcs_gem_serpentine.name=蛇纹石
我觉得行，改了

2023-02-08 13:44 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +item.dcs_gem_bauxite.name=铝土矿
我的天哪作者你啥时候加的这玩意折磨人

2023-02-09 07:56 UTC, Ricky-fight requested changes
一些格式问题需要全文检查一下，辛苦（）

2023-02-09 07:56 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +item.dcs_food_microbe_coliformes.name=大肠菌
```suggestion
item.dcs_food_microbe_coliformes.name=大肠杆菌
```

2023-02-09 07:56 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +item.dcs_food_microbe_mushroom.name=蘑菇菌
```suggestion
item.dcs_food_microbe_mushroom.name=真菌
```

2023-02-09 07:56 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +tile.dcs_ore2_stone_11.name=金红石石英矿石
这里与上面统一一下

2023-02-09 07:56 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +tile.dcs_build_awning.name=木质屋檐
```suggestion
tile.dcs_build_awning.name=木屋檐
```

2023-02-09 07:56 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +dcs.tip.right_click_wrench=使用黄铜扳手右键
```suggestion
dcs.tip.right_click=右击
dcs.tip.right_click_wrench=使用黄铜扳手右击
```

2023-02-09 07:56 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +dcs.tip.r_click_remove=右键单击：移除
```suggestion
dcs.tip.r_click_pos=右击方块：标记坐标
dcs.tip.r_click_use=右击方块：放置目标到该坐标
dcs.tip.r_click_remove=右击目标：移除
```

2023-02-09 07:56 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +dcs.tip.portal1= 温度或液氮
```suggestion
dcs.tip.portal1=温度或液氮
```

2023-02-09 07:56 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +dcs.tip.crusher=合成需要刀盘（刀盘不会被消耗）
（提醒）

2023-02-09 07:56 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +dcs.comment.color_picture.gu=在范围内产生WIND级别的气流，并赋予鸟之祝福效果
```suggestion
dcs.comment.color_picture.gu=在范围内产生 WIND 级别的气流，并赋予鸟之祝福效果
```

2023-02-09 07:56 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +dcs.potion.projectile_resistant=远程抗性
```suggestion
dcs.potion.projectile_resistant=弹射物抗性
```
下方也请更改（）

2023-02-09 07:56 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +dcs.creativetab.building=热量与气候：建筑
![image](https://user-images.githubusercontent.com/13982778/217749399-d60fa5a9-c4ba-47e2-bc44-a34049d7239d.png)
最好是这样，随意吧（）

2023-02-09 07:56 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +advancements.dcs_climate.core.title=Heat and Climate
这里为何不翻了

2023-02-09 07:56 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +advancements.dcs_climate.metal_brass2.description=在温度为KILN，通风为TIGHT的情况下等待黄铜粉块变化
```suggestion
advancements.dcs_climate.metal_brass2.description=在温度为 KILN，通风为 TIGHT 的情况下等待黄铜粉块变化
```
推荐再检查一下

2023-02-09 07:56 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +dcs.info.title.spade_earth=大地之铲
到底是`锹`还是`铲`？

2023-02-09 07:56 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +dcs.info.desc.cube_black=黑魔方需要放在y11以下的黑暗中激活
```suggestion
dcs.info.desc.cube_black=黑魔方需要放在 Y=11 以下的黑暗中激活
```

2023-02-09 08:15 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +tile.dcs_build_awning.name=木质屋檐
为了凑四个字特地加上的制字（）（）（）

2023-02-09 08:19 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-climate/dcs_climate/lang/zh_cn.lang
> +advancements.dcs_climate.core.title=Heat and Climate
嘶，真没发现

2023-02-09 09:04 UTC, Ricky-fight approved these changes
差不多了应该……

2023-02-14 11:38 UTC, merged