heat and processing翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3001
Opened 2023-02-06 13:52 UTC by komeiji-koyomi

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-07 07:47 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-processing/hap/lang/zh_cn.lang
> +tile.reactor_storage.name=反应室物流接口
这也是个port吗

2023-02-07 07:47 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-processing/hap/lang/zh_cn.lang
> +hap.tip.heat=热量等级 : %s
> 请与原版 Minecraft 保持统一，使用中文的标点符号。如果是保留不翻译的英文中的标点符号，则仍保留英文的标点符号（[Minecraft 模组简体中文翻译规范与指南](https://cfpa.site/TransRules/)）

2023-02-07 07:47 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-processing/hap/lang/zh_cn.lang
> +tile.shaft_bifurcated_steel.name=无损钢轴 (分流)
> 请与原版 Minecraft 保持统一，使用中文的标点符号。如果是保留不翻译的英文中的标点符号，则仍保留英文的标点符号（[[Minecraft 模组简体中文翻译规范与指南](https://cfpa.site/TransRules/)](https://cfpa.site/TransRules/)）

2023-02-07 07:47 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-processing/hap/lang/zh_cn.lang
> +hap.tip.reactor_fluidport2=用扳手shift右键来设置输入/输出
```suggestion
hap.tip.reactor_fluidport2=用扳手Shift右键来设置输入/输出
```

2023-02-07 07:49 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-processing/hap/lang/zh_cn.lang
> +tile.reactor_storage.name=反应室物流接口
是的这两个接口都是作为反应室的附加部件的，翻译成一致的估计更易懂一点

2023-02-09 12:53 UTC, Ricky-fight requested changes

2023-02-09 12:53 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-processing/hap/lang/zh_cn.lang
> +hap.tip.reactor_fluidport2=用扳手Shift右键来设置输入/输出
```suggestion
hap.tip.reactor_fluidport2=用扳手 Shift 右键来设置输入/输出
```

2023-02-09 12:53 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-processing/hap/lang/zh_cn.lang
> +hap.tip.smelting_plate3=没有气候配方的食物也可以在OVEN+的温度下被烹饪，无论气流情况如何
```suggestion
hap.tip.smelting_plate3=没有气候配方的食物也可以在 OVEN+ 的温度下烹饪，无论气流情况如何
```

2023-02-09 12:53 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-processing/hap/lang/zh_cn.lang
> +hap.config.hud=自动隐藏HUD
```suggestion
hap.config.hud=自动隐藏 HUD
```

2023-02-09 12:53 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-processing/hap/lang/zh_cn.lang
> +hap.config.asm_enderman=Enderman ASM
```suggestion
hap.config.asm_charm=饰品 ASM
hap.config.asm_enderman=末影人 ASM
```
这个ASM是什么？

2023-02-09 12:54 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-processing/hap/lang/zh_cn.lang
> +hap.config.asm_enderman=Enderman ASM
不知道，游戏内找了好久没找到对应的原文位置，也不清楚是干啥用的，所以暂时不翻译了

2023-02-09 12:55 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-processing/hap/lang/zh_cn.lang
> +hap.config.asm_enderman=Enderman ASM
那先翻译能翻译的地方吧，charm我看前面有饰品，应该是这个

2023-02-09 12:57 UTC, komeiji-koyomi commented on projects/1.12.2/assets/heat-and-processing/hap/lang/zh_cn.lang
> +hap.config.asm_enderman=Enderman ASM
暂且不翻译，我怀疑是和游戏内两个饰品的功能有关的接口名，乱改怕出事（你懂得日站mod）

2023-02-09 13:00 UTC, Ricky-fight commented on projects/1.12.2/assets/heat-and-processing/hap/lang/zh_cn.lang
> +hap.config.asm_enderman=Enderman ASM
吼啊（）

2023-02-09 13:27 UTC, Ricky-fight approved these changes

2023-02-14 11:39 UTC, merged