提交create-connected-block-textures翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #3007
Opened 2023-02-07 08:42 UTC by JZjzh

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-07 08:53 UTC, Ricky-fight commented
/add-mapping create-connected-block-textures 678956

2023-02-07 09:44 UTC, ChuijkYahus requested changes
这个文件排序（）

2023-02-07 09:44 UTC, ChuijkYahus commented on projects/1.18/assets/create-connected-block-textures/create_connected_blocks/lang/zh_cn.json
> +  "item.create_connected_blocks.incomplete_zinc_reinforcement": "不完整的锌加固",
```suggestion
  "item.create_connected_blocks.incomplete_brass_reinforcement": "黄铜加固材（半成品）",
  "item.create_connected_blocks.incomplete_copper_reinforcement": "铜加固材（半成品）",
  "item.create_connected_blocks.incomplete_diamond_reinforcement": "钻石加固材（半成品）",
  "item.create_connected_blocks.incomplete_emerald_reinforcement": "绿宝石加固材（半成品）",
  "item.create_connected_blocks.incomplete_golden_reinforcement": "黄金加固材（半成品）",
  "item.create_connected_blocks.incomplete_iron_reinforcement": "铁加固材（半成品）",
  "item.create_connected_blocks.incomplete_lapis_reinforcement": "青金石加固材（半成品）",
  "item.create_connected_blocks.incomplete_netherite_reinforcement": "下界合金加固材（半成品）",
  "item.create_connected_blocks.incomplete_zinc_reinforcement": "锌加固材（半成品）",
```
请仔细对照create本身的语言文件以及做好上下文统一

2023-02-07 09:44 UTC, ChuijkYahus commented on projects/1.18/assets/create-connected-block-textures/create_connected_blocks/lang/zh_cn.json
> +  "item.create_connected_blocks.netherite_reinforcement": "下界合金加固",
```suggestion
  "item.create_connected_blocks.netherite_reinforcement": "下界合金加固材",
```

2023-02-07 09:44 UTC, ChuijkYahus commented on projects/1.18/assets/create-connected-block-textures/create_connected_blocks/lang/zh_cn.json
> +  "block.create_connected_blocks.andesite": "连接磨制安山岩",
这里原文貌似并没有`连接`或者`connected`出现啊

2023-02-07 09:44 UTC, ChuijkYahus commented on projects/1.18/assets/create-connected-block-textures/create_connected_blocks/lang/zh_cn.json
> +  "block.create_connected_blocks.stone": "连接光滑石",
```suggestion
  "block.create_connected_blocks.stone": "平滑石头",
```
原版用词

2023-02-07 12:41 UTC, ChuijkYahus commented
重复pr

2023-02-14 11:40 UTC, Ricky-fight commented
ping @JZjzh

2023-02-21 05:04 UTC, ChuijkYahus commented
- 7天时限已到，close，如有需要可以re-open或重新提交汉化文件。

ping @JZjzh

2023-02-21 05:04 UTC, closed without merging