提交 create:slice-and-dice 翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #3018
Opened 2023-02-09 12:57 UTC by TomTuych

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-09 13:17 UTC, luoxueyasha commented on projects/1.18/assets/slice-and-dice/sliceanddice/lang/zh_cn.json
> +    "sliceanddice.gui.contraptions.wrong_direction": "好像这个%s正在向_错误的方向_旋转."
_wrong direction_是不是游戏预留字符串？不需要翻译吧

2023-02-09 13:21 UTC, TomTuych commented on projects/1.18/assets/slice-and-dice/sliceanddice/lang/zh_cn.json
> +    "sliceanddice.gui.contraptions.wrong_direction": "好像这个%s正在向_错误的方向_旋转."
这是个粗体效果

2023-02-09 13:26 UTC, Ricky-fight commented
标记一下（）
#3010 #3011

2023-02-09 13:40 UTC, ChuijkYahus commented on projects/1.18/assets/slice-and-dice/sliceanddice/lang/zh_cn.json
> +    "sliceanddice.gui.contraptions.wrong_direction": "好像这个%s正在向_错误的方向_旋转."
```suggestion
    "sliceanddice.gui.contraptions.wrong_direction": "好像这个%s正在向_错误的方向_旋转。"
```
请使用中文标点

2023-02-09 13:55 UTC, TomTuych commented on projects/1.18/assets/slice-and-dice/sliceanddice/lang/zh_cn.json
> +    "sliceanddice.gui.contraptions.wrong_direction": "好像这个%s正在向_错误的方向_旋转."
啊，没注意，下次多看一遍

2023-02-16 16:53 UTC, ChuijkYahus requested changes

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
>    "modifier.materialis.arcane.flavor": "魔法 *哼*",
```suggestion
  "modifier.materialis.arcane.flavor": "魔法*嘿嘿*",
```
出处居然是憨豆（）
https://www.youtube.com/watch?v=DM-UnV9TEzY
拟声词应该随便选都行吧

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
>    "modifier.materialis.brittle.flavor": "脆得跟粉笔一样",
```suggestion
  "modifier.materialis.brittle.flavor": "化作粉尘",
```
```suggestion
  "modifier.materialis.brittle.flavor": "化作白垩",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.capacitor.description": "工具的能量容量增加 10000RF",
```suggestion
  "modifier.materialis.capacitor.description": "工具的能量容量增加10000RF",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.capacitor.flavor": "RF 电容，使时间旅行变成可能",
```suggestion
  "modifier.materialis.capacitor.flavor": "通量电容，使时间旅行变成可能",
```
叫通量应该也没问题吧（）
毕竟全称就是红石通量

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.cataclysmic.description": "增加 5 个升级槽和 1 个能力槽",
```suggestion
  "modifier.materialis.cataclysmic.description": "增加5个升级槽和1个能力槽",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.cosmic_luck.description": "挖掘方块或击杀生物时，能提升获得高品质战利品的概率！",
```suggestion
  "modifier.materialis.cosmic_luck.description": "采掘方块或击杀生物时，获得好东西的概率大幅提升！",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.cosmic_unbreakable.description": "工具不会消耗耐久",
```suggestion
  "modifier.materialis.cosmic_unbreakable.description": "工具不会消耗耐久度",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.crystalline.description": "增加 50% 额外挖掘速度和攻击伤害",
```suggestion
  "modifier.materialis.crystalline.description": "采掘速度+50%，攻击伤害+50%",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
>    "modifier.materialis.decay.description": "你的工具不会在使用的时候消耗耐久，而是会随着时间消耗耐久",
```suggestion
  "modifier.materialis.decay.description": "你的工具不会在使用的时候消耗耐久度，而是会随着时间消耗耐久度",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.engineers_goggles.description": "当看向动能装置时展示额外信息",
```suggestion
  "modifier.materialis.engineers_goggles.description": "看向动力学组件时展示额外信息",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.fluxripper.flavor": "64核心！",
```suggestion
  "modifier.materialis.fluxripper.flavor": "64核！",
```
64核CPU（）

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
>    "modifier.materialis.freezing.description": "对目标造成减速",
```suggestion
  "modifier.materialis.freezing.description": "给予目标缓慢",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.half_life.4": "半衰期II：第II章",
```suggestion
  "modifier.materialis.half_life.3": "半条命II：第I章",
  "modifier.materialis.half_life.4": "半条命II：第II章",
```
半条命可还行
不过这个不好翻译

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
>    "modifier.materialis.half_life.description": "在耐久度高的时候会更快地消耗耐久，耐久度低的时候耐久则消耗得更慢",
```suggestion
  "modifier.materialis.half_life.description": "在耐久度高的时候会更快地消耗耐久度，耐久度低的时候耐久则消耗得更慢",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
>    "modifier.materialis.half_life.flavor": "闻到了灰烬的味道",
```suggestion
  "modifier.materialis.half_life.flavor": "醒来闻灰",
```
语出半条命系列

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.immersive_wrenching.flavor": "普蒂斯·斯宾塞在此！",
```suggestion
  "modifier.materialis.immersive_wrenching.flavor": "在这放个补给七！",
```
来自TF2机枪手语音

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.lesser_psionizing_radiation.description": "你的工具对psi离子有很强的传导性，适合施放术式",
```suggestion
  "modifier.materialis.lesser_psionizing_radiation.description": "你的工具对Psi子有很强的传导性，适合施放术式",
```
psion倒不一定是指离子，应该就是指一种粒子（尤其有可能是借用轻子的后缀？）
比如μ子（muon）和τ子（tauon）
不过ψ子不大符合psi这个模组本身，还是不推荐，但真的觉得这个可以的话应该也行？（）

下面这个是Psi模组灵感来源，《魔法科高校的劣等生》里的翻译法，也可以用作参考
```suggestion
  "modifier.materialis.lesser_psionizing_radiation.description": "你的工具对想子有很强的传导性，适合施放术式",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.lesser_spell_casting.description": "获得右击使用术式的能力，但失去使用方块破坏和攻击术式的能力",
```suggestion
  "modifier.materialis.lesser_spell_casting.description": "允许右击施放术式，但无法在破坏方块和攻击时施法",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.manaripper.attack_damage": "有魔力时的攻击速度",
```suggestion
  "modifier.materialis.manaripper.attack_damage": "有魔力时的攻击伤害",
```
```suggestion
  "modifier.materialis.manaripper.attack_damage": "魔力协助攻击伤害",
```
前面部分可以不改，仅作参考

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.manaburner.mining_speed": "有魔力时的采掘速度",
```suggestion
  "modifier.materialis.manaburner.mining_speed": "魔力协助采掘速度",
```
仅作参考

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
>    "modifier.materialis.nocturnal": "夜曲",
```suggestion
  "modifier.materialis.nocturnal": "夜行",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
>    "modifier.materialis.old_timer": "旧钟",
```suggestion
  "modifier.materialis.old_timer": "老手",
```
看了源码，应该是遗忆对应的强化

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
>    "modifier.materialis.old_timer.flavor": "锈桶！",
```suggestion
  "modifier.materialis.old_timer.flavor": "铁锈水桶！",
```
找来找去只找到Nitrome的游戏（）

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
>    "modifier.materialis.otherworldly.flavor": "来自另一个已知的位面！",
```suggestion
  "modifier.materialis.otherworldly.flavor": "来自另一位面！",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.overeating.description": "你工具上的黏液覆层效果突然变得诱人起来",
```suggestion
  "modifier.materialis.overeating.description": "你工具上的黏液覆层突然变得诱人起来",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.pipe_wrenching.flavor": "Pretty!",
Pretty Pipes通用译名放在这里不合适
留英文应该也行吧（）

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.power_hungry.description": "每级每损失1点耐久值消耗100RF。不充能的话工具看起来就没那么好用",
```suggestion
  "modifier.materialis.power_hungry.description": "每级每损失1点耐久度消耗100RF。不充能的话工具看起来就没那么好用",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.power_hungry.flavor": "自大狂！",
```suggestion
  "modifier.materialis.power_hungry.flavor": "狂妄之人！",
```
也算是UT吧？（）

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
>    "modifier.materialis.psicho_digger.description": "拥有的Psi越多，采掘速度越快",
```suggestion
  "modifier.materialis.psicho_digger.description": "拥有的Psi能量越多，采掘速度越快",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.psicho_killer.description": "拥有的psi越多，攻击伤害越高",
```suggestion
  "modifier.materialis.psicho_killer.description": "拥有的Psi能量越多，攻击伤害越高",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.psionizing_radiation.description": "你的工具对psi离子有很强的传导性，适合施放术式，+1术式插槽",
```suggestion
  "modifier.materialis.psionizing_radiation.description": "你的工具对Psi子有很强的传导性，适合施放术式，术式插槽+1",
```
```suggestion
  "modifier.materialis.psionizing_radiation.description": "你的工具对想子有很强的传导性，适合施放术式，+1术式插槽",
```
同上

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.psishield.description": "有概率消耗psi使你的工具不损失耐久度",
```suggestion
  "modifier.materialis.psishield.description": "有概率消耗Psi能量使你的工具不损失耐久度",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.reactive.description": "有几率在工具被使用或玩家受伤时施放抄写的法术。",
```suggestion
  "modifier.materialis.reactive.description": "有概率在工具被使用或玩家受伤时施放抄写的法术",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.terrabeam.flavor": "用激光束传我上去！",
```suggestion
  "modifier.materialis.terrabeam.flavor": "用激光束传送我吧！",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.spell_socket.flavor": "比Lime Sockets更耐用！",
```suggestion
  "modifier.materialis.spell_socket.flavor": "比青柠插座更耐用！",
```
完全没找到出处

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.spell_casting.description": "工具可以单击右击使用术式，但无法在采掘和攻击的时候施法，同时术式插槽+1",
```suggestion
  "modifier.materialis.spell_casting.description": "允许右击施放术式，但无法在破坏方块和攻击的时候施法，同时术式插槽+1",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.underlord.description": "对深暗之园的非BOSS生物造成更多伤害，并且可以快速采掘深暗之园的方块",
```suggestion
  "modifier.materialis.underlord.description": "对非Boss深园生物造成更多伤害，并且可以快速采掘深园方块",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "recipe.materialis.modifier.casting_requirements": "施法需要Psi离辐射或Psi衰变才能附加",
```suggestion
  "recipe.materialis.modifier.casting_requirements": "“施法”需要“Psi离辐射”或“Psi衰变”作为前置",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.immersive_wrenching": "沉浸捶打",
```suggestion
  "modifier.materialis.immersive_wrenching": "沉浸扳手",
```
统一性

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.pipe_wrenching": "拧管道",
```suggestion
  "modifier.materialis.pipe_wrenching": "管道扳手",
```
统一性

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
>    "recipe.materialis.modifier.thermal_wrenching_requirements": "热力扳手只能附加在扳手上",
```suggestion
  "recipe.materialis.modifier.create_wrenching_requirements": "“机械扳手”只能加持于扳手",
  "recipe.materialis.modifier.immersive_wrenching_requirements": "“沉浸扳手”只能加持于扳手",
  "recipe.materialis.modifier.pipe_wrenching_requirements": "“管道扳手”只能加持于扳手",
  "recipe.materialis.modifier.reactive_requirements": "“反应”的合成每一级都不同",
  "recipe.materialis.modifier.runed_requirements": "“符文”需要“闪亮”作为前置",
  "recipe.materialis.modifier.skullfire_requirements": "“炽焰之啄颅”需要“肢解 V”作为前置",
  "recipe.materialis.modifier.thermal_wrenching_requirements": "“热力扳手”只能加持于扳手",
```

2023-02-16 16:53 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "tooltip.materialis.stored_enegry": "能量：%s / %s RF"
```suggestion
  "tooltip.materialis.stored_enegry": "能量：%s/%s RF"
```

2023-02-16 16:55 UTC, ChuijkYahus commented
如果觉得`消耗耐久度`有点怪，可以在处理完所有suggestion后统一改为`消耗耐久`

2023-02-16 17:12 UTC, ChuijkYahus commented
以及所有键名中带有`encyclopedia`的键的末尾都应加上一个句号`。`，而带有`description`的则不能带有不表意符号
请在处理完所有suggestion后统一修改，辛苦
当然不修改也可以（）

2023-02-17 14:54 UTC, TomTuych commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
>    "block.materialis.molten_pink_slime_block": "熔融粉色黏液合金",
谢谢帮忙检查。我对很多mod不熟，多有疏漏了。修改辛苦了

2023-02-17 15:16 UTC, TomTuych commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
>    "material.materialis.starmetal.flavor": "不要与星形切割金属混淆。",
长见识了！

2023-02-17 15:27 UTC, TomTuych commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.cosmic_luck.description": "挖掘方块或击杀生物时，能提升获得高品质战利品的概率！",
这其实是官方对幸运的翻译
![image](https://user-images.githubusercontent.com/106566753/219695444-ff8e0c21-0b15-4a30-ab3e-4f35ce4895c7.png)
绝不是我懒（

2023-02-17 16:06 UTC, TomTuych commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
>    "modifier.materialis.old_timer.flavor": "锈桶！",
等等，什么童年回忆？（

2023-02-17 16:48 UTC, ChuijkYahus commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
>    "modifier.materialis.old_timer.flavor": "锈桶！",
草
这个如果不是nitrome游戏的话我也不知道来源是啥了（）

2023-02-17 19:03 UTC, ChuijkYahus reviewed
应该差不多了吧

2023-02-17 19:03 UTC, ChuijkYahus commented on projects/1.18/assets/slice-and-dice/sliceanddice/lang/zh_cn.json
> +    "sliceanddice.ponder.slicer.text_1": "使用有效刀具右键点击切片机主体",
```suggestion
    "sliceanddice.ponder.slicer.text_1": "使用有效刀具右击切片机主体",
```

2023-02-17 19:03 UTC, ChuijkYahus commented on projects/1.18/assets/slice-and-dice/sliceanddice/lang/zh_cn.json
> +    "sliceanddice.gui.contraptions.wrong_direction": "好像这个%s正在向_错误的方向_旋转。"
```suggestion
    "sliceanddice.gui.contraptions.wrong_direction": "好像这个%s正以_错误的方向_旋转。"
```

2023-02-18 05:03 UTC, TomTuych commented on projects/1.18/assets/materialis/materialis/lang/zh_cn.json
> +  "modifier.materialis.otherworld_goggles.description": "使你能看到彼岸的方块，潜行并按下“头盔交互”键以开关",
我看神秘学还没翻译（1.18）之后我再看看

2023-02-18 05:39 UTC, ChuijkYahus approved these changes

2023-02-19 18:35 UTC, merged