Girls' Frontline 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3020
Opened 2023-02-09 14:01 UTC by CoalGlage

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-09 14:31 UTC, mamaruo commented
#2753

2023-02-16 06:08 UTC, luoxueyasha requested changes
浅看了一百多行，麻烦修一下

2023-02-16 06:08 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.mission2.gaiyou4.name=赫丽安：而此次的任务是歼灭一处的铁血运输部队，该部队极为可能是要前往预计量产木星炮的工厂。
```suggestion
hmggirlfront.mission2.gaiyou4.name=赫丽安：而此次的任务是歼灭一处铁血运输部队，该部队似乎要前往生产木星炮的工厂。
```
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/2753/files#r1108016055

2023-02-16 06:08 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.mission2.doll.talk4.name=[歼灭铁血运输部队]
```suggestion
hmggirlfront.mission2.doll.talk4.name=[歼灭铁血运输单位]
```
原文`[敵輸送型を破壊せよ]`，和下方的`M1014:やりました！輸送型を撃破です！`对应

2023-02-16 06:08 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.mission2.doll.break_u2.name=M1014：快点离开那里！！！好像有什么东西要出来了！！！
```suggestion
hmggirlfront.mission2.doll.break_u2.name=M1014：快点离开那里！好像有什么东西要出来了！
```
原文`離れてください！何か出てきます！`
<s>你吼辣么大声干嘛！！！</s>
原文只用了一个叹号，个人认为最好还是保持一致

2023-02-16 06:12 UTC, luoxueyasha commented
这一版不仅比#2753 的原文新一些，翻译的质量（个人感官上）也更好一点
你们两个pr提交者协商一下（？

2023-02-17 02:37 UTC, luoxueyasha requested changes
大体上对完了，麻烦修复，辛苦了

2023-02-17 02:37 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +tile.base_antennabase.name=信号站据点生成方块
```suggestion
tile.base_antennabase.name=基站据点生成方块
```
[基地局 - Wikipedia](https://ja.wikipedia.org/wiki/%E5%9F%BA%E5%9C%B0%E5%B1%80)，[基站 - 术语在线](https://www.termonline.cn/word/263635/1#s1)

2023-02-17 02:37 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +tile.bdoll_base_headquarters_em.name=敌方司令部
原文有`大型拠点`，个人感觉不要漏译比较好，方便创造模式的查找

2023-02-17 02:37 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +tile.b_block_collapse.name=受到坍塌污染的泥土
```suggestion
tile.b_block_collapse.name=被坍塌污染的泥土
```
[Minecraft Wiki:译名标准化](https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96)
参照原版命名风格

2023-02-17 02:37 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +tile.b_block_rcc_df.name=基础宿舍墙壁
```suggestion
tile.b_block_rcc_df.name=宿舍墙壁
```
原文没有`基础`

2023-02-17 02:37 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +tile.b_block_at_obstacles2.name=拒马
```suggestion
tile.b_block_at_obstacles2.name=反坦克拒马
```
或
```suggestion
tile.b_block_at_obstacles2.name=铁拒马
```

2023-02-17 02:37 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +tile.b_block_odunit_df.name=冷凝器外挂机
更通俗的说法是`室外机`或`空调室外机`

2023-02-17 02:37 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +tem.idoll_pad.name=指挥操作系统
```suggestion
item.idoll_pad.name=指挥操作系统
```

2023-02-17 02:37 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.idoll_pledge.text1.name=你可以与等级不低于50级的人形缔结契约
```suggestion
hmggirlfront.idoll_pledge.text1.name=可以与等级不低于50级的人形缔结契约
```

2023-02-17 02:37 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.idoll_pledge.text3.name=测试进行中
```suggestion
hmggirlfront.idoll_pledge.text3.name=测试道具
```

2023-02-17 02:37 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.dollgun_stechkin.name=斯捷奇金
此处为何翻译`Stechkin`？
其他英语翻中文的人形名称也请给出理由，如`Astra`，`DesrtEagle`，`Thunder`，`TYPE100`，`Suomi`，`Vz61`，`STEN_Mk2`，`Galil`，`TYPE95`
太多了我不列举了

2023-02-17 02:37 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.dollgun_gr_g36c.name=Gr_G36C
下划线很怪异，真的要这么翻译吗

2023-02-17 02:37 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.item_drone.name=妖精基座
原文`妖精用ドローン`，妖精用无人机？

2023-02-17 02:37 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.idoll_drone.text1.name=将此物品装备于主手将随机获得一种妖精
```suggestion
hmggirlfront.idoll_drone.text1.name=将此物品置于主手将随机获得一种妖精
```

2023-02-17 06:04 UTC, CoalGlage commented
已收到，十分感谢。近期会进行修改。
另外关于人形和武器的名称，是直接根据少前游戏进行的翻译，这一处我并不觉得有什么问题。

2023-02-19 12:03 UTC, CoalGlage commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.string.pad.doll_explanation11_6.name=手持红石粉时右击可切换誓约效果的开关。
是的。经实机测试，红石粉确实可以切换誓约人形对玩家的增益开关。

2023-02-19 12:18 UTC, CoalGlage commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.dollgun_stechkin.name=斯捷奇金
少前游戏原文如此，此处我觉得没有什么不妥

2023-02-19 12:21 UTC, CoalGlage commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.item_drone.name=妖精基座
妖精的无人机部分。

2023-02-19 12:28 UTC, CoalGlage commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.string.pad.mission10_1.name=[目标10：夺回海上发射基地]
已确认，不是。

2023-02-19 12:37 UTC, CoalGlage commented
修复已完成。

2023-02-20 07:11 UTC, luoxueyasha requested changes
指挥官，还不能休息哦

2023-02-20 07:11 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.frontlinebase.4.name=P.S. 行李的装卸就都交给指挥官了哦~
```suggestion
hmggirlfront.frontlinebase.4.name=P.S. 行李的装卸就都交给指挥官了哦～
```
使用全角浪纹线

2023-02-20 07:11 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.ibc10turret.name=生成 钢狮·改
确定少前原文用的是英文句点`.`而不是连接号`·`吗
如果要改请全文通查

2023-02-20 07:11 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.idoll_pledge.text2.name=誓约人形将会给予自身及其指挥官永久的增益效果
原文没提到`永久的`，模组实际内容是这样的吗

2023-02-22 14:45 UTC, CoalGlage commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.idoll_pledge.text2.name=誓约人形将会给予自身及其指挥官永久的增益效果
是这样的

2023-02-22 14:46 UTC, CoalGlage commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.ibc10turret.name=生成 钢狮·改
少前甚至没这东西XD

2023-02-22 14:55 UTC, CoalGlage commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.ibc10turret.name=生成 钢狮·改
原文在这里是burstliner
少前里更接近“改”的钢狮的强化版是Nemeum_SWAP
而隔壁军方里面与钢狮长得像的牝鹿是Cerynitis

2023-02-22 14:56 UTC, CoalGlage commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.ibc10turret.name=生成 钢狮·改
查到些别的资料了
钢狮改这个名字肯定也是不准确的了..

2023-02-22 14:58 UTC, CoalGlage commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.idoll_pledge.text2.name=誓约人形将会给予自身及其指挥官永久的增益效果
效果是在誓约后，人形会给玩家一个五秒的buff，如果buff计时结束则重置计时

2023-02-22 15:05 UTC, CoalGlage commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.ibc10turret.name=生成 钢狮·改
这个大概是从高达里面弄出来的了....

2023-02-22 15:22 UTC, CoalGlage commented
晚些再来看看吧（瘫）

2023-02-23 14:48 UTC, CoalGlage commented
ibc01turret和ibc10turret
这两个在模组里面一个叫Defender一个叫Burstliner
在少前里面均不存在，很有可能是作者原创
不仅如此，此模组的部分榴弹发射器与对应人形也不存在于少前内，亦可能为作者原创

2023-02-23 15:09 UTC, luoxueyasha commented
> ibc01turret和ibc10turret 这两个在模组里面一个叫Defender一个叫Burstliner 在少前里面均不存在，很有可能是作者原创 不仅如此，此模组的部分榴弹发射器与对应人形也不存在于少前内，亦可能为作者原创

按少前风格翻译即可，Burstliner感觉确实是高达梗

2023-03-01 11:33 UTC, luoxueyasha approved these changes
我个人看着没事了，@Ricky-fight 作为审核层麻烦看一眼？

2023-03-03 02:30 UTC, Ricky-fight requested changes
作为一个外行我只能看看typo和模组本身无关的问题了（）

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.mission1.doll.talk3.name=M1014：我们必须将情报带回格里芬才行…
```suggestion
hmggirlfront.mission1.doll.talk3.name=M1014：我们必须将情报带回格里芬才行……
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.mission1.failed.name=［任务失败：小队已被歼灭…］
```suggestion
hmggirlfront.mission1.failed.name=［任务失败：小队已被歼灭……］
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.mission1.failed_player_dead.name=［任务失败：我方指挥官已被击杀…］
```suggestion
hmggirlfront.mission1.failed_player_dead.name=［任务失败：我方指挥官已被击杀……］
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.string.pad.doll_explanation01_4.name=在START槽里放入人形制造契约即可开始制造人形，
```suggestion
hmggirlfront.string.pad.doll_explanation01_4.name=在 START 槽里放入人形制造契约即可开始制造人形，
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.string.pad.doll_explanation01_5.name=而在QUICK槽内放入快速制造契约则会立刻完成制造，
```suggestion
hmggirlfront.string.pad.doll_explanation01_5.name=而在 QUICK 槽内放入快速制造契约则会立刻完成制造，
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.string.pad.doll_explanation2_5.name=在ALL指挥下对所有人形进行统一指示。
```suggestion
hmggirlfront.string.pad.doll_explanation2_5.name=在 ALL 指挥下对所有人形进行统一指示。

```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.mission1.doll.talk1.name=M1014：得救了…这里是M1014！
```suggestion
hmggirlfront.mission1.doll.talk1.name=M1014：得救了……这里是M1014！
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +tile.b_block_hesco_df.name=HESCO防爆墙
```suggestion
tile.b_block_hesco_df.name=HESCO 防爆墙
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +tile.b_block_sincgars_df.name=SINCGAR通讯机
```suggestion
tile.b_block_sincgars_df.name=SINCGAR 通讯机
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +tile.b_block_box1_iop.name=IOP产纸箱
```suggestion
tile.b_block_box1_iop.name=IOP 产纸箱
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.dollam_acog.name=ACOG 4X瞄准镜
```suggestion
item.dollam_acog.name=ACOG 4X 瞄准镜
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.dollam_coyote.name=Coyote红点瞄准镜
```suggestion
item.dollam_coyote.name=Coyote 红点瞄准镜
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.dollam_kobra.name=Kobra反射式瞄准镜
```suggestion
item.dollam_kobra.name=Kobra 反射式瞄准镜
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.dollam_m1903onlyscope.name=春田M1903专用倍镜
```suggestion
item.dollam_m1903onlyscope.name=春田 M1903 专用倍镜
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.dollam_an_peq15.name=AN/PEQ-15战术镭射指示器
```suggestion
item.dollam_an_peq15.name=AN/PEQ-15 战术镭射指示器
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.dollam_eot_exps3.name=EXPS3全息瞄准镜
```suggestion
item.dollam_eot_exps3.name=EXPS3 全息瞄准镜
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.dollam_eot_exps3_416.name=HK416专用 EXPS3全息瞄准镜
```suggestion
item.dollam_eot_exps3_416.name=HK416 专用 EXPS3 全息瞄准镜
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.dollam_lam_unit.name=MK23专用 镭射指示器
```suggestion
item.dollam_lam_unit.name=MK23 专用镭射指示器
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.subarm_ak12prt.name=AK-12废土型
```suggestion
item.subarm_ak12prt.name=AK-12 废土型
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.dollgun_m1928a1.name=汤姆森M1928A1
```suggestion
item.dollgun_m1928a1.name=汤姆森 M1928A1
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.ve_heli.name=生成 UH黑鹰运输直升机
```suggestion
item.ve_heli.name=生成 UH 黑鹰运输直升机
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +entity.EntityVe_HMMWV.name=悍马吉普车HMMWV
```suggestion
entity.EntityVe_HMMWV.name=悍马吉普车 HMMWV
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.ve_hmmwv.name=生成 悍马吉普车HMMWV
```suggestion
item.ve_hmmwv.name=生成 悍马吉普车 HMMWV
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.ve_rhib.name=生成 RHIB刚性充气艇
```suggestion
entity.EntityVe_RHIB.name=RHIB 刚性充气艇
item.ve_rhib.name=生成 RHIB 刚性充气艇
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.armor_pmc_feet.name=PMC军靴
```suggestion
item.armor_pmc_head.name=PMC 头盔
item.armor_pmc_chest.name=PMC 防弹衣
item.armor_pmc_legs.name=PMC 护膝
item.armor_pmc_feet.name=PMC 军靴
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.dollgun_ibc14sw.name=铁血工造SW
```suggestion
item.dollgun_ibc04smg.name=铁血工造 SMG
item.dollgun_ibc05ar.name=铁血工造 AR
item.dollgun_ibc06rf.name=铁血工造 RF
item.dollgun_ibc07hg.name=铁血工造 HG
item.dollgun_ibc07sd.name=铁血工造 SD
item.dollgun_ibc08sw.name=铁血工造 SW
item.dollgun_ibc08sd.name=铁血工造 SD
item.dollgun_ibc13glg.name=铁血工造 GLG
item.dollgun_ibc14sw.name=铁血工造 SW
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +item.core_ags30.name=AGS-30心智核心
```suggestion
item.core_ags30.name=AGS-30 心智核心
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.string.pad.doll_explanation2_4.name=摁下→←键进行人形选择，摁下↑键下达直接指示。
```suggestion
hmggirlfront.string.pad.doll_explanation2_4.name=摁下 →← 键进行人形选择，摁下 ↑ 键下达直接指示。
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.string.pad.doll_explanation0_5.name=右击以打开其GUI，
```suggestion
hmggirlfront.string.pad.doll_explanation0_5.name=右击以打开其 GUI，
```

2023-03-03 02:30 UTC, Ricky-fight commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.mission1.gaiyou5.name=赫丽安：突袭小队由M1014、M10、M1911三位人形组成，
```suggestion
hmggirlfront.mission1.gaiyou5.name=赫丽安：突袭小队由 M1014、M10、M1911 三位人形组成，
```

2023-03-03 06:47 UTC, luoxueyasha commented on projects/1.12.2/assets/1UNKNOWN/hmggirlfront/lang/zh_cn.lang
> +hmggirlfront.string.pad.doll_explanation2_4.name=摁下→←键进行人形选择，摁下↑键下达直接指示。
```suggestion
hmggirlfront.string.pad.doll_explanation2_4.name=按下 →← 键进行人形选择，按下 ↑ 键下达直接指示。
```
`摁`是口语表述

2023-07-22 11:20 UTC, luoxueyasha approved these changes
我觉得可了
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/2f5cec1a-3345-4c47-9adf-e3a77075f65d)

2023-07-22 11:57 UTC, CoalGlage commented
> 我觉得可了 ![image](https://user-images.githubusercontent.com/38830216/255326666-2f5cec1a-3345-4c47-9adf-e3a77075f65d.png)
啊 作者大概一个多月前更新了模组来着
晚些我更一下
![QQ图片20230722195501](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/117024879/e1d834d5-2b79-4442-a389-878bd6d98368)

2023-07-22 14:29 UTC, CoalGlage commented
2023/7/22
`HMGDollsFrontLine`模组于`β.23.1`版本拥有了官方汉化。故而我决定关闭此pr。
感谢各位的陪伴。
![QQ图片20230722222900](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/117024879/fb27059f-9042-445f-9041-a540685eba5c)这个是官译的其中一段截图。

2023-07-22 14:29 UTC, closed without merging

2023-07-22 23:00 UTC, luoxueyasha commented
看了下官译，虽然（暂时）没赶上最新版本，也塞了一堆注释私货，但是还是很厉害的……
辛苦了