Chatsounds Mod 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3024
Opened 2023-02-10 08:00 UTC by Jack253-png

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2023-02-10 10:58 UTC, Ricky-fight requested changes

2023-02-10 10:58 UTC, Ricky-fight commented on projects/1.19/assets/chat-sounds/chatsounds/lang/zh_cn.json
> +    "text.autoconfig.chatsounds.option.message": "其他, 包括正常信息",
```suggestion
    "text.autoconfig.chatsounds.option.message": "包括普通消息的其他消息",
```

2023-02-10 10:58 UTC, Ricky-fight commented on projects/1.19/assets/chat-sounds/chatsounds/lang/zh_cn.json
> +    "text.autoconfig.chatsounds.option.join.sound": "音效 ID",
```suggestion
    "text.autoconfig.chatsounds.option.join.sound": "音效ID",
```
下方也请统一更改。

2023-02-10 10:58 UTC, Ricky-fight commented on projects/1.19/assets/chat-sounds/chatsounds/lang/zh_cn.json
> +    "text.autoconfig.chatsounds.option.leave": "离线信息",
```suggestion
    "text.autoconfig.chatsounds.option.leave": "退出消息",
```
原版`%s left the game`：`%s退出了游戏`

2023-02-10 10:58 UTC, Ricky-fight commented on projects/1.19/assets/chat-sounds/chatsounds/lang/zh_cn.json
> +    "text.autoconfig.chatsounds.option.join": "上线信息",
```suggestion
    "text.autoconfig.chatsounds.option.join": "加入消息",
```
原版`%s joined the game`：`%s加入了游戏`

2023-02-10 10:58 UTC, Ricky-fight commented on projects/1.19/assets/chat-sounds/chatsounds/lang/zh_cn.json
> +    "text.autoconfig.chatsounds.option.death": "死亡信息",
```suggestion
    "text.autoconfig.chatsounds.option.death": "死亡消息",
```

2023-02-10 10:58 UTC, Ricky-fight commented on projects/1.19/assets/chat-sounds/chatsounds/lang/zh_cn.json
> +    "text.autoconfig.chatsounds.option.pm": "私聊信息",
```suggestion
    "text.autoconfig.chatsounds.option.pm": "私聊消息",
```

2023-02-10 10:58 UTC, Ricky-fight commented on projects/1.19/assets/chat-sounds/chatsounds/lang/zh_cn.json
> +    "text.autoconfig.chatsounds.option.advancement": "成就信息",
```suggestion
    "text.autoconfig.chatsounds.option.advancement": "进度信息",
```

2023-02-11 00:45 UTC, Jack253-png reviewed
Done

2023-02-11 18:18 UTC, Ricky-fight requested changes
抱歉漏了一个（）

2023-02-11 18:18 UTC, Ricky-fight commented on projects/1.19/assets/chat-sounds/chatsounds/lang/zh_cn.json
> +	"text.autoconfig.chatsounds.option.advancement": "进度信息",
```suggestion
	"text.autoconfig.chatsounds.option.advancement": "进度消息",
```

2023-02-12 03:31 UTC, Ricky-fight approved these changes

2023-02-13 15:11 UTC, merged