Aquaculture 翻译修正丨1.18→1.19
CFPAOrg/Minecraft-Mod-Language-Package pull request #3029
Opened 2023-02-12 15:16 UTC by mamaruo

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-22 16:08 UTC, mamaruo commented
自审通过

2023-02-28 14:05 UTC, DrIceTea123 requested changes
鱼名没有仔细核对，其他的大概看了一下
如果修改麻烦同步到所有版本

2023-02-28 14:05 UTC, DrIceTea123 commented on projects/1.16/assets/aquaculture/aquaculture/lang/zh_cn.json
> +  "aquaculture.subtitles.fish_mount_removed": "鱼：从鱼架上移除",
`从鱼架上取下`会不会好一点

2023-02-28 14:05 UTC, DrIceTea123 commented on projects/1.16/assets/aquaculture/aquaculture/lang/zh_cn.json
>    "entity.aquaculture.dark_oak_fish_mount": "深色橡木鱼架",
虽然不知道实际效果，但是我有点想叫他`晾鱼架`
还是看实际表现，如果不合适就当我没说

2023-02-28 16:53 UTC, mamaruo commented on projects/1.16/assets/aquaculture/aquaculture/lang/zh_cn.json
> +  "aquaculture.fishWeight.juvenile": "微小",
是重量
那么该用什么呢

2023-02-28 17:01 UTC, mamaruo commented on projects/1.16/assets/aquaculture/aquaculture/lang/zh_cn.json
> +  "block.aquaculture.fish_trap": "捕鱼陷阱",
未使用的废键

2023-02-28 17:03 UTC, mamaruo commented on projects/1.16/assets/aquaculture/aquaculture/lang/zh_cn.json
> +  "item.aquaculture.pollock": "绿青鳕",
不需要
绿青鳕见 main comment 中给的来源

[粉红鲑 - 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/%E7%B2%89%E7%B4%85%E9%AE%AD)

2023-02-28 17:05 UTC, mamaruo commented on projects/1.16/assets/aquaculture/aquaculture/lang/zh_cn.json
> +  "aquaculture.neptunium_hoe.tooltip.desc": "犁过的地会保持湿润",
[Minecraft Wiki](https://minecraft.fandom.com/zh/wiki/%E8%80%95%E5%9C%B0#%E9%94%84:~:text=%E5%AF%B9%E7%9D%80%E6%B3%A5%E5%9C%9F%E3%80%81%E8%8D%89%E6%96%B9%E5%9D%97%E6%88%96%E5%9C%9F%E5%BE%84%E4%BD%BF%E7%94%A8%E9%94%84%E5%8F%AF%E5%B0%86%E5%85%B6%E7%8A%81%E6%88%90%E8%80%95%E5%9C%B0%E3%80%82) 上有此类表达

2023-03-11 06:57 UTC, DrIceTea123 commented on projects/1.16/assets/aquaculture/aquaculture/lang/zh_cn.json
> +  "aquaculture.fishWeight.juvenile": "微小",
确实比较难想（）
`幼小`或者`幼年`怎么样

2023-03-11 06:57 UTC, DrIceTea123 commented on projects/1.16/assets/aquaculture/aquaculture/lang/zh_cn.json
> +  "item.aquaculture.pollock": "绿青鳕",
那这个resolve掉吧

2023-03-11 06:57 UTC, DrIceTea123 commented on projects/1.16/assets/aquaculture/aquaculture/lang/zh_cn.json
>    "entity.aquaculture.dark_oak_fish_mount": "深色橡木鱼架",
那要不要改掉（）

2023-04-17 17:02 UTC, ChuijkYahus approved these changes
感觉应该没什么问题了
就是那两个conversation还要再看下

2023-04-22 13:59 UTC, mamaruo commented on projects/1.16/assets/aquaculture/aquaculture/lang/zh_cn.json
>    "entity.aquaculture.dark_oak_fish_mount": "深色橡木鱼架",
倾向不改，它没有晾干效果，就是另类物品展示框

2023-04-22 15:57 UTC, ChuijkYahus commented on projects/1.16/assets/aquaculture/aquaculture/lang/zh_cn.json
>    "entity.aquaculture.dark_oak_fish_mount": "深色橡木鱼架",
感觉还是不改比较好

2023-06-20 09:02 UTC, ChuijkYahus approved these changes

2023-06-25 04:33 UTC, merged