提交monsters and girls翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #3048
Opened 2023-02-18 08:45 UTC by Athurrender

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-18 08:52 UTC, Athurrender commented
bot检测有问题啊，1.18.2最新版已经是1.2.9了。不过作者确实留了一堆游戏里没有的在里面，因为mod是Mcreator制作的，不清楚意图。

2023-07-30 10:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3048) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3048) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3048) it.</sub>

2023-09-02 11:27 UTC, ChuijkYahus commented
/sort-keys projects/1.18/assets/monsters-girls-mushroom-update/monsters_and_girls/lang/en_us.json
/sort-keys projects/1.18/assets/monsters-girls-mushroom-update/monsters_and_girls/lang/zh_cn.json

2023-09-02 11:37 UTC, ChuijkYahus reviewed
其他貌似没啥问题了……
拉其他审核来看一眼

2023-09-02 11:37 UTC, ChuijkYahus commented on projects/1.18/assets/monsters-girls-mushroom-update/monsters_and_girls/lang/zh_cn.json
> +  "block.monsters_and_girls.huge_magma_fungus": "巨大的熔融真菌",
```suggestion
  "block.monsters_and_girls.huge_magma_fungus": "巨大的熔融菌",
```
和绯红菌诡异菌翻译格式统一
此处更改则下方也一起更改

2023-09-02 11:37 UTC, ChuijkYahus commented on projects/1.18/assets/monsters-girls-mushroom-update/monsters_and_girls/lang/zh_cn.json
> +  "block.monsters_and_girls.inkcap_3": "淡灰色墨汁鬼伞块",
```suggestion
  "block.monsters_and_girls.inkcap_1": "墨汁鬼伞方块",
  "block.monsters_and_girls.inkcap_2": "灰色墨汁鬼伞方块",
  "block.monsters_and_girls.inkcap_3": "淡灰色墨汁鬼伞方块",
```
和棕色蘑菇方块翻译格式统一
此处更改则下方类似处也一起更改

2023-09-02 11:37 UTC, ChuijkYahus commented on projects/1.18/assets/monsters-girls-mushroom-update/monsters_and_girls/lang/zh_cn.json
> +  "subtitles.vexiskill": "恼鬼被放逐到了暗影领域",
```suggestion
  "subtitles.vexiskill": "恼鬼：被放逐至暗影领域",
```

2023-09-02 11:37 UTC, ChuijkYahus commented on projects/1.18/assets/monsters-girls-mushroom-update/monsters_and_girls/lang/zh_cn.json
> +  "block.monsters_and_girls.huge_green": "巨大的罕见诡异菌",
```suggestion
  "block.monsters_and_girls.huge_green": "巨大的稀有诡异菌",
```
此处更改则下方也一起更改

2023-09-02 12:33 UTC, luoxueyasha requested changes

2023-09-02 12:33 UTC, luoxueyasha commented on projects/1.18/assets/monsters-girls-mushroom-update/monsters_and_girls/lang/zh_cn.json
> +  "block.monsters_and_girls.huge_inky_cap": "巨大的墨汁鬼伞",
在想要不要遵从统一原则将`mushroom`也译出来

2023-09-02 12:33 UTC, luoxueyasha commented on projects/1.18/assets/monsters-girls-mushroom-update/monsters_and_girls/lang/zh_cn.json
> +  "entity.monsters_and_girls.brown_mandragora": "褐色曼德拉草",
有没有考虑过统一为`棕色`

2023-09-02 12:33 UTC, luoxueyasha commented on projects/1.18/assets/monsters-girls-mushroom-update/monsters_and_girls/lang/zh_cn.json
> +  "entity.monsters_and_girls.brown_mandragora": "褐色曼德拉草",
有没有考虑过统一为`棕色`

2023-09-02 12:44 UTC, Athurrender commented on projects/1.18/assets/monsters-girls-mushroom-update/monsters_and_girls/lang/zh_cn.json
> +  "entity.monsters_and_girls.brown_mandragora": "褐色曼德拉草",
好，因为作者有更新我顺便一起改了

2023-09-02 12:48 UTC, Athurrender commented on projects/1.18/assets/monsters-girls-mushroom-update/monsters_and_girls/lang/zh_cn.json
> +  "block.monsters_and_girls.huge_green": "巨大的罕见诡异菌",
罕见和稀有没啥区别吧，这里为啥要改，不太懂

2023-09-02 12:50 UTC, Athurrender commented on projects/1.18/assets/monsters-girls-mushroom-update/monsters_and_girls/lang/zh_cn.json
> +  "block.monsters_and_girls.huge_inky_cap": "巨大的墨汁鬼伞",
作者专门分了菌（fungus）和菇（mushroom），还是遵从原版吧

2023-09-02 12:53 UTC, Athurrender commented on projects/1.18/assets/monsters-girls-mushroom-update/monsters_and_girls/lang/zh_cn.json
> +  "entity.monsters_and_girls.brown_mandragora": "褐色曼德拉草",
不过因为两个颜色不是很一样，我本来想做点分别

2023-09-02 14:23 UTC, ChuijkYahus commented on projects/1.18/assets/monsters-girls-mushroom-update/monsters_and_girls/lang/zh_cn.json
> +  "block.monsters_and_girls.huge_green": "巨大的罕见诡异菌",
https://minecraft.fandom.com/zh/wiki/%E7%A8%80%E6%9C%89%E5%BA%A6
不改也没问题的，主要是考虑这里

2023-09-02 14:25 UTC, ChuijkYahus commented on projects/1.18/assets/monsters-girls-mushroom-update/monsters_and_girls/lang/zh_cn.json
> +  "item.monsters_and_girls.peach_spawn_egg": "幽灵 (桃色) 刷怪蛋",
```suggestion
  "item.monsters_and_girls.peach_spawn_egg": "幽灵（桃色）刷怪蛋",
```
注意改为全角符号

2023-09-02 15:59 UTC, ChuijkYahus commented on projects/1.18/assets/monsters-girls-mushroom-update/monsters_and_girls/lang/zh_cn.json
> +  "entity.monsters_and_girls.peach": "幽灵 (桃色)",
```suggestion
  "entity.monsters_and_girls.peach": "幽灵（桃色）",
```

2023-09-02 16:25 UTC, Athurrender commented on projects/1.18/assets/monsters-girls-mushroom-update/monsters_and_girls/lang/zh_cn.json
> +  "entity.monsters_and_girls.peach": "幽灵 (桃色)",
还是你仔细，竟然忘了这里也要改

2023-09-12 16:55 UTC, ChuijkYahus approved these changes
感觉没什么问题了

2023-09-12 23:01 UTC, luoxueyasha approved these changes

2023-09-13 16:44 UTC, merged