Harder farther
CFPAOrg/Minecraft-Mod-Language-Package pull request #3050
Opened 2023-02-18 12:45 UTC by Gjg5

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2023-02-19 16:29 UTC, mamaruo requested changes
……

2023-02-19 16:29 UTC, mamaruo commented on projects/1.19/assets/HarderFarther-/harder-farther/lang/zh_cn.json
> +	"item.harderfarther.grim_boots.lore" : "给爷死！",
？

2023-02-19 16:29 UTC, mamaruo commented on projects/1.19/assets/HarderFarther-/harder-farther/lang/zh_cn.json
> +	"item.harderfarther.burnishing_stone.lore" : "修理手边的物品.",
```suggestion
	"item.harderfarther.burnishing_stone.lore" : "修理副手上的物品.",
```

2023-02-19 16:29 UTC, mamaruo commented on projects/1.19/assets/HarderFarther-/harder-farther/lang/zh_cn.json
> +	"item.harderfarther.burnishing_stone" : "磨光石材",
```suggestion
	"item.harderfarther.burnishing_stone" : "抛光石头",
```

2023-02-19 16:29 UTC, mamaruo commented on projects/1.19/assets/HarderFarther-/harder-farther/lang/zh_cn.json
> +	"item.harderfarther.ancient_bow.lore" : "几个世纪前的失落",
？

2023-02-19 16:29 UTC, mamaruo commented on projects/1.19/assets/HarderFarther-/harder-farther/lang/zh_cn.json
> +	"item.harderfarther.ancient_shovel.name" : "山丘平整机"
工具叫这名合适吗

2023-02-20 05:18 UTC, Gjg5 commented on projects/1.19/assets/HarderFarther-/harder-farther/lang/zh_cn.json
> +	"item.harderfarther.ancient_bow.lore" : "几个世纪前的失落",
我也不知道这是啥（）

2023-02-23 14:58 UTC, luoxueyasha reviewed
NO COMMENT

2023-02-23 14:58 UTC, luoxueyasha commented on projects/1.19/assets/HarderFarther-/harder-farther/lang/zh_cn.json
> +	"item.harderfarther.burnishing_stone.lore" : "修理副手上的物品.",
```suggestion
	"item.harderfarther.burnishing_stone.lore" : "修理副手上的物品。",
```

2023-02-23 14:58 UTC, luoxueyasha commented on projects/1.19/assets/HarderFarther-/harder-farther/lang/zh_cn.json
> +	"item.harderfarther.grim_boots.lore" : "快去死吧",
```suggestion
	"item.harderfarther.grim_boots.lore" : "快速奔向下一次死亡",
```
质疑译者水平

2023-02-23 14:58 UTC, luoxueyasha commented on projects/1.19/assets/HarderFarther-/harder-farther/lang/zh_cn.json
> +	"item.harderfarther.ancient_axe.name" : "木材切割机",
切割`机`？确定它是一台机器而不是键值里的`axe`？

2023-03-06 13:50 UTC, Gjg5 commented on projects/1.19/assets/HarderFarther-/harder-farther/lang/zh_cn.json
> +	"item.harderfarther.ancient_axe.name" : "木材切割机",
这个我不知道怎么搞

2023-03-09 05:46 UTC, luoxueyasha commented
路径不对，机翻严重，没打开模组就翻译，连自己都不知道自己翻译的是啥  
我对这个commit进行一个downvote
引用群友的话：“推荐还是精进一下语言功底再来吧”

2023-03-26 06:40 UTC, closed without merging