Nightvision
CFPAOrg/Minecraft-Mod-Language-Package pull request #3052
Opened 2023-02-18 12:47 UTC by Gjg5

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x} 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [X] 刷新 PR 的标签/状态，有需要再点击；

2023-02-19 06:42 UTC, xfl03 approved these changes

2023-02-19 06:49 UTC, Ricky-fight commented on projects/1.19/assets/night-vision-enchantment-forge/night-vision-enchantment-/night-vision-enchantment-forge/zh_cn.json
> +    "enchantment.nightvision.nightvision.desc": "给玩家夜视效果."
```suggestion
    "enchantment.nightvision.nightvision.desc": "给予玩家夜视效果"

```

2023-02-20 15:14 UTC, ChuijkYahus requested changes

2023-02-20 15:14 UTC, ChuijkYahus commented on projects/1.19/assets/night-vision-enchantment-forge/night-vision-enchantment-/night-vision-enchantment-forge/zh_cn.json
> +    "enchantment.nightvision.nightvision.desc": "给予玩家夜视效果."
```suggestion
    "enchantment.nightvision.nightvision.desc": "给予玩家夜视效果。"
```

2023-02-22 05:53 UTC, ChuijkYahus approved these changes

2023-02-22 15:54 UTC, mamaruo commented
什么鬼路径

2023-02-22 15:57 UTC, ChuijkYahus commented
ping @Gjg5

2023-02-22 16:13 UTC, xfl03 requested changes
路径不太对

2023-02-28 10:30 UTC, Ricky-fight commented
/mv projects/1.19/assets/night-vision-enchantment-forge/night-vision-enchantment-/night-vision-enchantment-forge/en_us.json projects/1.19/assets/night-vision-enchantment-forge/nightvision/lang/en_us.json
/mv projects/1.19/assets/night-vision-enchantment-forge/night-vision-enchantment-/night-vision-enchantment-forge/zh_cn.json projects/1.19/assets/night-vision-enchantment-forge/nightvision/lang/zh_cn.json

2023-03-02 05:44 UTC, merged