Amethyst-tools
CFPAOrg/Minecraft-Mod-Language-Package pull request #3055
Opened 2023-02-19 03:34 UTC by Gjg5

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-19 04:01 UTC, mamaruo requested changes
请务必熟悉原版译名再翻译，如铲子、裤子、缓落，药水箭的格式

CONTRIBUTING 里明确规定了标题格式，请遵守！

> 我已仔细阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；

2023-02-19 07:01 UTC, Ricky-fight requested changes
～32

请完整阅读一遍原版译名以及贡献指南

2023-02-19 16:31 UTC, mamaruo commented
@Ricky-fight 网页 review 的 suggestion 填充会自动整出一个空行，如果说用户使用 commit suggestion 的话就灾难了

2023-02-19 16:34 UTC, mamaruo requested changes
还有标题！药水箭的格式`XX之箭`，我之前都提到了……………………

2023-02-19 16:34 UTC, mamaruo commented on projects/1.19/assets/amethysttoolsmod-/amethyst-tools-mod/lang/zh_cn.json
> +	"item.amethysttoolsmod.amethyst_cluster_lv2": "紫水晶簇(Lv. 2)",
半角符号，lv 要翻译出来

2023-02-19 16:34 UTC, mamaruo commented on projects/1.19/assets/amethysttoolsmod-/amethyst-tools-mod/lang/zh_cn.json
> +14	"item.amethysttoolsmod.iron_boots_amethyst": "紫水晶铁鞋子",
？

2023-02-20 12:08 UTC, Ricky-fight commented
> @Ricky-fight 网页 review 的 suggestion 填充会自动整出一个空行，如果说用户使用 commit suggestion 的话就灾难了
> 
> @Gjg5 一字一句地读：[模组简体中文翻译规范与指南](https://cfpa.site/TransRules/)

甚至iOS上review根本看不出有没有多空行（）

2023-02-23 15:02 UTC, luoxueyasha commented on projects/1.19/assets/amethysttoolsmod-/amethyst-tools-mod/lang/zh_cn.json
> +	"item.amethysttoolsmod.amethyst_cluster_lv2": "紫水晶簇(等级. 2)",
```suggestion
	"item.amethysttoolsmod.amethyst_cluster_lv2": "紫水晶簇（等级2）",
```
![image](https://user-images.githubusercontent.com/38830216/220944134-2d9ccffb-55ea-4981-9978-5624aed32023.png)

2023-02-25 04:25 UTC, Ricky-fight requested changes

2023-02-25 04:25 UTC, Ricky-fight commented on projects/1.19/assets/amethysttoolsmod-/amethyst-tools-mod/lang/zh_cn.json
> +	"item.amethystoolsmod.amethyst_tipped_arrow": "紫水晶尖箭",
![image](https://user-images.githubusercontent.com/13982778/221337409-40b5a6c6-a694-41c3-a004-db47971cefd1.png)

2023-02-25 18:28 UTC, mamaruo commented
/mv projects/1.19/assets/amethysttoolsmod-/amethyst-tools-mod/lang/en_us.json projects/1.19/assets/amethyst-tools-mod/amethysttoolsmod/lang/en_us.json
/mv projects/1.19/assets/amethysttoolsmod-/amethyst-tools-mod/lang/zh_cn.json projects/1.19/assets/amethyst-tools-mod/amethysttoolsmod/lang/zh_cn.json

2023-03-08 00:30 UTC, Ricky-fight requested changes

2023-03-08 00:30 UTC, Ricky-fight commented on projects/1.19/assets/amethyst-tools-mod/amethysttoolsmod/lang/zh_cn.json
> +	"item.amethystoolsmod.amethyst_tipped_arrow": "紫水晶约箭",
```suggestion
	"item.amethystoolsmod.amethyst_tipped_arrow": "紫水晶药箭",
```

2023-03-08 00:30 UTC, Ricky-fight commented on projects/1.19/assets/amethyst-tools-mod/amethysttoolsmod/lang/zh_cn.json
>  	"item.amethysttoolsmod.amethyst_tipped_arrow.effect.empty": "不可制作的紫水晶尖箭",
```suggestion
	"item.amethysttoolsmod.amethyst_tipped_arrow.effect.empty": "不可制作的紫水晶药箭",
```

2023-03-08 00:30 UTC, Ricky-fight commented on projects/1.19/assets/amethyst-tools-mod/amethysttoolsmod/lang/zh_cn.json
>  	"item.amethysttoolsmod.amethyst_tipped_arrow.effect.mundane": "紫水晶尖箭",
```suggestion
	"item.amethysttoolsmod.amethyst_tipped_arrow.effect.mundane": "紫水晶药箭",
```

2023-03-26 06:53 UTC, ChuijkYahus requested changes

2023-03-26 06:53 UTC, ChuijkYahus commented on projects/1.19/assets/amethyst-tools-mod/amethysttoolsmod/lang/zh_cn.json
> +	"item.amethysttoolsmod.amethyst_spectral_arrow": "紫水晶光谱箭头",
```suggestion
	"item.amethysttoolsmod.amethyst_spectral_arrow": "紫水晶光灵箭",
```

2023-03-26 06:53 UTC, ChuijkYahus commented on projects/1.19/assets/amethyst-tools-mod/amethysttoolsmod/lang/zh_cn.json
> +	"entity.amethysttoolsmod.amethyst_spectral_arrow_entity": "紫水晶光谱箭头",
```suggestion
	"entity.amethysttoolsmod.amethyst_spectral_arrow_entity": "紫水晶光灵箭",
```

2023-03-26 06:53 UTC, ChuijkYahus commented on projects/1.19/assets/amethyst-tools-mod/amethysttoolsmod/lang/zh_cn.json
> +	"item.amethysttoolsmod.amethyst_tipped_arrow.effect.turtle_master": "乌龟大师的紫水晶箭",
```suggestion
	"item.amethysttoolsmod.amethyst_tipped_arrow.effect.turtle_master": "紫水晶神龟之箭",
```
牛的

2023-03-26 06:53 UTC, ChuijkYahus commented on projects/1.19/assets/amethyst-tools-mod/amethysttoolsmod/lang/zh_cn.json
> +	"item.amethysttoolsmod.amethyst_tipped_arrow.effect.empty": "不可制作的紫水晶药箭",
```suggestion
	"item.amethysttoolsmod.amethyst_tipped_arrow.effect.empty": "不可合成的紫水晶药箭",
```

2023-03-26 06:53 UTC, ChuijkYahus commented on projects/1.19/assets/amethyst-tools-mod/amethysttoolsmod/lang/zh_cn.json
> +	"item.amethysttoolsmod.amethyst_tipped_arrow.effect.slow_falling": "紫水晶虚弱之箭",
```suggestion
	"item.amethysttoolsmod.amethyst_tipped_arrow.effect.slow_falling": "紫水晶缓降之箭",
```
更牛了

2023-03-26 06:53 UTC, ChuijkYahus commented on projects/1.19/assets/amethyst-tools-mod/amethysttoolsmod/lang/zh_cn.json
> +	"item.amethysttoolsmod.amethyst_tipped_arrow.effect.levitation": "紫水晶缓降之箭",
```suggestion
	"item.amethysttoolsmod.amethyst_tipped_arrow.effect.levitation": "紫水晶飘浮之箭",
```

2023-03-26 06:53 UTC, ChuijkYahus commented on projects/1.19/assets/amethyst-tools-mod/amethysttoolsmod/lang/zh_cn.json
> +	"item.amethysttoolsmod.iron_boots_amethyst": "紫水晶铁鞋子",
```suggestion
	"item.amethysttoolsmod.iron_boots_amethyst": "紫水晶铁靴子",
```

2023-03-26 06:55 UTC, ChuijkYahus approved these changes

2023-03-27 04:52 UTC, merged