Urushi 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3056
Opened 2023-02-19 06:54 UTC by luoxueyasha

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

---

总之先占个坑。
文本已经翻译完毕可以校对了（原文是ja_jp.json），i18n这边我会传一份翻译挂轴贴图的版本上来（不确定作者那边会不会做多语言贴图，总之做了再说）

2023-02-19 06:55 UTC, luoxueyasha commented
/add-mapping urushi-mod 585890

2023-02-19 07:01 UTC, luoxueyasha commented
@Cyl18 麻烦看一下是什么问题（

2023-02-20 03:36 UTC, luoxueyasha commented
目前在进行日语专有名词自查，这个和#3047 先转成draft了

2023-02-20 12:41 UTC, luoxueyasha commented
自查结束，欢迎审核

2023-02-25 12:32 UTC, Ricky-fight requested changes

2023-02-25 12:32 UTC, Ricky-fight commented on projects/1.18/assets/urushi-mod/urushi/lang/zh_cn.json
> +  "block.urushi.lycoris": "石蒜",
国内应该还是`曼珠沙华`或`彼岸花`比较广为人知

2023-02-25 12:32 UTC, Ricky-fight commented on projects/1.18/assets/urushi-mod/urushi/lang/zh_cn.json
> +  "block.urushi.fallen_sakura_leaves": "樱花树落叶",
最好加个`堆`，下面可以不加

2023-02-25 12:32 UTC, Ricky-fight commented on projects/1.18/assets/urushi-mod/urushi/lang/zh_cn.json
> +  "block.urushi.kakuriyo_grass_block": "繁茂的幽世土",
```suggestion
  "block.urushi.kakuriyo_grass_block": "幽世草方块",
```
下面还有

2023-02-25 12:32 UTC, Ricky-fight commented on projects/1.18/assets/urushi-mod/urushi/lang/zh_cn.json
> +  "block.urushi.black_urushi_shitamiita_slab": "黑漆外墙挂板台阶",
`下見板`->`外墙挂板`范畴差的有点点大，而且到下面处理为`台阶`更是概念混乱了

2023-02-25 13:29 UTC, luoxueyasha commented on projects/1.18/assets/urushi-mod/urushi/lang/zh_cn.json
> +  "block.urushi.black_urushi_shitamiita_slab": "黑漆外墙挂板台阶",
主要是没找到`下見板`对应的翻译，就美国`house`的外墙板的感觉……

2023-02-25 13:40 UTC, luoxueyasha commented on projects/1.18/assets/urushi-mod/urushi/lang/zh_cn.json
> +  "block.urushi.women_onsen_noren": "女澡堂门帘",
诶，`お湯`和`澡堂`居然有区别吗？

2023-02-25 13:40 UTC, luoxueyasha commented on projects/1.18/assets/urushi-mod/urushi/lang/zh_cn.json
> +  "block.urushi.lycoris": "石蒜",
那就`彼岸花`了

2023-02-25 13:41 UTC, luoxueyasha commented on projects/1.18/assets/urushi-mod/urushi/lang/zh_cn.json
> +  "block.urushi.kakuriyo_grass_block": "繁茂的幽世土",
唔……这玩意原文是`繫茂した幽世土`，我去和作者确认一下

2023-02-25 13:48 UTC, luoxueyasha commented on projects/1.18/assets/urushi-mod/urushi/lang/zh_cn.json
> +  "block.urushi.rice_crop": "稻谷",
![image](https://user-images.githubusercontent.com/38830216/221360427-b1cffa90-6b27-4f4d-a04c-7f6d15302a22.png)
 游戏里它又是植株又是种子

2023-02-25 13:51 UTC, luoxueyasha commented on projects/1.18/assets/urushi-mod/urushi/lang/zh_cn.json
> +  "block.urushi.blue_sayagata_fusuma": "青空色丝绫纹纸拉门",
原文是`空色`，游戏截图：
![image](https://user-images.githubusercontent.com/38830216/221360553-c256bf44-a03f-49ca-90f5-425fc5943229.png)
右侧羊毛从下向上：青色，淡蓝色，蓝色；游戏中使用淡蓝色染料合成

2023-02-25 14:03 UTC, luoxueyasha commented on projects/1.18/assets/urushi-mod/urushi/lang/zh_cn.json
> +  "block.urushi.kakuriyo_grass_block": "繁茂的幽世土",
![image](https://user-images.githubusercontent.com/38830216/221361098-663435cc-9b3b-4a1e-89a0-281a20a00e55.png)
作者方的意见是，虽然和“幽世草方块”没有任何区别，但是不想用“ブロック”（方块）这个词

2023-02-25 14:21 UTC, Ricky-fight commented on projects/1.18/assets/urushi-mod/urushi/lang/zh_cn.json
> +  "block.urushi.kakuriyo_grass_block": "繁茂的幽世土",
那英文呢

2023-02-25 14:24 UTC, Ricky-fight commented on projects/1.18/assets/urushi-mod/urushi/lang/zh_cn.json
> +  "block.urushi.rice_crop": "稻谷",
贴图也是稻穗

2023-02-25 14:28 UTC, Ricky-fight commented on projects/1.18/assets/urushi-mod/urushi/lang/zh_cn.json
> +  "block.urushi.blue_sayagata_fusuma": "青空色丝绫纹纸拉门",
那感觉空色->天蓝色比较合适，原版有青色，最好避免有误导性的描述

2023-02-25 14:32 UTC, luoxueyasha commented on projects/1.18/assets/urushi-mod/urushi/lang/zh_cn.json
> +  "block.urushi.kakuriyo_grass_block": "繁茂的幽世土",
作者英文水平并不高，不建议参考英文

2023-02-25 14:50 UTC, luoxueyasha commented on projects/1.18/assets/urushi-mod/urushi/lang/zh_cn.json
> +  "block.urushi.cupric_oxide_kawara_roof_225": "台阶用氧化的铜瓦屋顶",
![image](https://user-images.githubusercontent.com/38830216/221363427-a7151be3-62d7-47cc-9780-6349edbb23ac.png)
见图，左边是“台阶用”，右边是“楼梯用”
作者本意就是“这玩意是搭在楼梯/台阶当屋顶的”，甚至会有模型bug
![image](https://user-images.githubusercontent.com/38830216/221363479-34809dad-d7c5-4b95-84a2-14da3de6e8ec.png)

2023-02-25 14:53 UTC, luoxueyasha commented on projects/1.18/assets/urushi-mod/urushi/lang/zh_cn.json
> +  "block.urushi.chiseled_lacquer_log": "錾制漆木原木",
`有切口的`？

2023-02-25 15:05 UTC, luoxueyasha commented on projects/1.18/assets/urushi-mod/urushi/lang/zh_cn.json
> +  "block.urushi.cupric_oxide_kawara_roof_225": "台阶用氧化的铜瓦屋顶",
![image](https://user-images.githubusercontent.com/38830216/221364253-e65d43c0-6a4b-44b9-bc90-d8692bb7c51d.png)
补充：单块的是这样的

2023-02-26 11:44 UTC, Ricky-fight commented on projects/1.18/assets/urushi-mod/urushi/lang/zh_cn.json
> +  "block.urushi.kakuriyo_grass_block": "繁茂的幽世土",
了解了

2023-02-26 13:17 UTC, Ricky-fight reviewed
我个人看不出什么大问题了，唯一依旧不太满意的地方还是`下见板`的处理（）

2023-02-26 13:17 UTC, Ricky-fight commented on projects/1.18/assets/urushi-mod/urushi/lang/zh_cn.json
> +  "block.urushi.oak_shitamiita": "橡木壁板",
`壁板`依旧是也没有体现出`下见板`的纹理，昨天稍微想了想
```suggestion
  "block.urushi.oak_shitamiita": "橡木楔纹板",
```
```suggestion
  "block.urushi.oak_shitamiita": "橡木楔纹壁板",
```
这个方块是只有一面有楔纹是吗
<img width="529" alt="image" src="https://user-images.githubusercontent.com/13982778/221411819-a93c4f8b-d4b6-4466-8862-058702cee122.png">

2023-02-27 06:20 UTC, luoxueyasha commented on projects/1.18/assets/urushi-mod/urushi/lang/zh_cn.json
> +  "block.urushi.oak_shitamiita": "橡木壁板",
![image](https://user-images.githubusercontent.com/38830216/221489220-2db8d886-7a9c-4911-8783-7a62ce4bc549.png)
三面都有，很显然作者偷懒了

2023-02-28 04:06 UTC, Ricky-fight approved these changes
应该问题不大了……？

2023-02-28 04:40 UTC, luoxueyasha commented
> 应该问题不大了……？

根据 #2996 的pr作者，他赞同将`七輪`翻译为`日式炭炉`，而我采用的翻译是`泥炉`，这点我们先内部协商一下

2023-02-28 08:20 UTC, luoxueyasha commented
和隔壁译者商量过了，`七輪`我这边根据名称来源`能装七厘炭`翻译为`七厘烤炉`，隔壁因为要坚持`日式`所以作`日式炭炉`。`泥炉`、`炭炉`、`烧烤炉`均为可用的译名。
@Ricky-fight 有什么意见吗？

2023-02-28 09:16 UTC, Ricky-fight commented
如果加日式的话这种mod里大多数物品都要加个`日式`了

2023-02-28 09:19 UTC, Ricky-fight approved these changes

2023-03-03 19:02 UTC, merged