Reusable rockets 汉化
CFPAOrg/Minecraft-Mod-Language-Package pull request #3060
Opened 2023-02-19 13:21 UTC by Gjg5

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [] 刷新 PR 的标签/状态，有需要再点击；

2023-02-19 16:19 UTC, mamaruo requested changes
怀疑水平了我要

2023-02-19 16:19 UTC, mamaruo commented on projects/1.19/assets/reusable_rockets-/reusable-rockets/lang/zh_cn.json
> +  "item.reusable_rockets.reusable_rocket_tier_3": "可重复使用的火箭层 3",
```suggestion
  "item.reusable_rockets.reusable_rocket_tier_1": "1级可复用火箭",
  "item.reusable_rockets.reusable_rocket_tier_2": "2级可复用火箭",
  "item.reusable_rockets.reusable_rocket_tier_3": "3级可复用火箭",
```

2023-02-19 16:19 UTC, mamaruo commented on projects/1.19/assets/reusable_rockets-/reusable-rockets/lang/zh_cn.json
> +  "tooltip.reusable_rockets.uses": "%s 的剩余使用量",
占位符给你吃了一个

2023-02-19 16:19 UTC, mamaruo commented on projects/1.19/assets/reusable_rockets-/reusable-rockets/lang/zh_cn.json
> +  "message.reusable_rockets.set_flight_duration": "飞行持续时间设置为%s的%s"
我打出问号

2023-02-20 12:29 UTC, Ricky-fight requested changes

2023-02-20 12:29 UTC, Ricky-fight commented on projects/1.19/assets/reusable_rockets-/reusable-rockets/lang/zh_cn.json
>    "message.reusable_rockets.set_flight_duration": "飞行持续时间设置为%s的%s"
请注意翻译一致性
机翻嫌疑

2023-02-25 12:41 UTC, closed without merging