Mahogany
CFPAOrg/Minecraft-Mod-Language-Package pull request #3065
Opened 2023-02-20 14:10 UTC by Gjg5

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-21 06:23 UTC, ChuijkYahus commented on projects/1.19/assets/mahogany/mahogany/lang/zh_cn.json
> +  "block.mahogany.stripped_mahogany_log": "去皮桃花心木原木",
```suggestion
  "block.mahogany.mahogany_log": "桃花心原木",
  "block.mahogany.stripped_mahogany_log": "去皮桃花心原木",
```

2023-02-21 06:31 UTC, ChuijkYahus requested changes

2023-02-21 06:31 UTC, ChuijkYahus commented on projects/1.19/assets/mahogany/mahogany/lang/zh_cn.json
> +  "block.mahogany.mahogany_planks": "桃花心木木板",
```suggestion
  "block.mahogany.mahogany_planks": "桃花心木板",
```

2023-02-21 06:31 UTC, ChuijkYahus commented on projects/1.19/assets/mahogany/mahogany/lang/zh_cn.json
> +  "block.mahogany.mahogany_leaves": "桃花心木树叶",
```suggestion
  "block.mahogany.mahogany_leaves": "桃花心树叶",
```

2023-02-21 06:31 UTC, ChuijkYahus commented on projects/1.19/assets/mahogany/mahogany/lang/zh_cn.json
> +  "block.mahogany.potted_mahogany_sapling": "盆栽桃花心木树苗",
```suggestion
  "block.mahogany.mahogany_sapling": "桃花心树苗",
  "block.mahogany.potted_mahogany_sapling": "桃花心树苗盆栽",
```

2023-02-21 06:31 UTC, ChuijkYahus commented on projects/1.19/assets/mahogany/mahogany/lang/zh_cn.json
> +  "block.mahogany.mahogany_wall_sign": "桃花心木告示牌墙"
```suggestion
  "block.mahogany.mahogany_wall_sign": "桃花心木告示牌"
```
不是很懂为啥这么翻
推荐进游戏看下

2023-02-21 06:31 UTC, ChuijkYahus commented on projects/1.19/assets/mahogany/mahogany/lang/zh_cn.json
> +  "block.mahogany.mahogany_blossom": "桃花心木孢子花",
```suggestion
  "block.mahogany.mahogany_blossom": "桃花心花簇",
```
这是个啥东西

2023-02-22 00:51 UTC, Ricky-fight approved these changes

2023-02-22 04:32 UTC, ChuijkYahus approved these changes

2023-02-25 07:24 UTC, merged