Yungs better nether fortresses
CFPAOrg/Minecraft-Mod-Language-Package pull request #3066
Opened 2023-02-20 14:15 UTC by Gjg5

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-22 05:02 UTC, ChuijkYahus reviewed
这个1.19fabric的键名放在forge版本下可行吗

2023-02-22 05:02 UTC, ChuijkYahus commented on projects/1.19/assets/Yungs-Better-NetherFortresses/YungsBetterNetherFortresses-/lang/zh_cn.json
> +  "text.autoconfig.betterfortresses-fabric-1_19.title": "YUNG's Better Nether Fortresses",
```suggestion
  "text.autoconfig.betterfortresses-fabric-1_19.title": "YUNG的下界要塞优化",
```
这个不知道要不要改
是根据mcmod上对同系列模组的翻译来的

2023-02-22 05:30 UTC, ChuijkYahus commented on projects/1.19/assets/Yungs-Better-NetherFortresses/YungsBetterNetherFortresses-/lang/zh_cn.json
> +  "text.autoconfig.betterfortresses-fabric-1_19.option.general.disableVanillaFortresses.@Tooltip": "是否禁用原版下界要塞."
```suggestion
  "text.autoconfig.betterfortresses-fabric-1_19.option.general.disableVanillaFortresses.@Tooltip": "是否禁用原版下界要塞。"
```

2023-02-22 05:34 UTC, Ricky-fight approved these changes

2023-02-22 05:40 UTC, Ricky-fight commented
/mv projects/1.19/assets/Yungs-Better-NetherFortresses/YungsBetterNetherFortresses-/lang/en_us.json projects/1.19/assets/yungs-better-nether-fortresses/betterfortresses/lang/en_us.json
/mv projects/1.19/assets/Yungs-Better-NetherFortresses/YungsBetterNetherFortresses-/lang/zh_cn.json projects/1.19/assets/yungs-better-nether-fortresses/betterfortresses/lang/zh_cn.json

2023-02-22 05:45 UTC, ChuijkYahus commented
这里面的键名没问题吗
我下个forge版本看下

2023-02-22 05:47 UTC, ChuijkYahus commented
> 这里面的键名没问题吗 我下个forge版本看下

没问题
~~YUNG的更好键名优化~~

2023-02-22 05:52 UTC, ChuijkYahus approved these changes

2023-02-22 16:06 UTC, mamaruo requested changes

2023-02-23 05:23 UTC, mamaruo commented on projects/1.19/assets/yungs-better-nether-fortresses/betterfortresses/lang/zh_cn.json
> +  "Use /locate structure betterfortresses:fortress instead!": "改用/locate structure betterfortresses:fortress!",
为什么要把我的全角符号改成半角的……

2023-02-25 04:00 UTC, Ricky-fight commented on projects/1.19/assets/yungs-better-nether-fortresses/betterfortresses/lang/zh_cn.json
> +  "Use /locate structure betterfortresses:fortress instead!": "改用/locate structure betterfortresses:fortress!",
这人就是自说自话

2023-02-25 04:00 UTC, Ricky-fight requested changes

2023-02-25 04:00 UTC, Ricky-fight commented on projects/1.19/assets/yungs-better-nether-fortresses/betterfortresses/lang/zh_cn.json
> +  "Use /locate structure betterfortresses:fortress instead!": "改用/locate structure betterfortresses:fortress!",
```suggestion
  "Use /locate structure betterfortresses:fortress instead!": "改用/locate structure betterfortresses:fortress！",
```

2023-02-27 10:34 UTC, Ricky-fight approved these changes

2023-02-27 15:16 UTC, mamaruo approved these changes

2023-03-02 05:42 UTC, merged