Fantasy Mounts 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3068
Opened 2023-02-23 11:43 UTC by AsteriaGrace

第一次做翻译 必然存在不少问题 我会努力改正（）

- [x ] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x ] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-23 15:25 UTC, AsteriaGrace commented on projects/1.16/assets/fantasy-mounts/fantasy/lang/zh_cn.json
> +  "fantasy.whistle.registered": "标记到 %s, 将在使用口哨时跟随你 (必须拿着口哨)",
已通查 规范完毕（）

2023-02-24 04:32 UTC, luoxueyasha commented on projects/1.16/assets/fantasy-mounts/fantasy/lang/zh_cn.json
> +  "item.fantasy.diamond_carrot.desc": "可用于繁殖独角兽",
原文`"item.fantasy.diamond_carrot.desc": "Can be used to breed rare Unicorns.",`
这里rare是不是没有翻译出来？
下文还有同类问题

2023-02-24 04:33 UTC, luoxueyasha commented on projects/1.16/assets/fantasy-mounts/fantasy/lang/zh_cn.json
> +  "fantasy.whistle.registered": "标记到 %s, 将在使用口哨时跟随你 (必须拿着口哨)",
行，记得点一下resolve（

2023-02-24 08:06 UTC, AsteriaGrace commented on projects/1.16/assets/fantasy-mounts/fantasy/lang/zh_cn.json
> +  "item.fantasy.diamond_carrot.desc": "可用于繁殖独角兽",
翻译时考虑过这一点 但是mod的独角兽是没有（类似抽卡的）品质这一说的 也就是说原文里的rare意思只是用于表达独角兽少见的意思 如果汉化成“可用于繁殖稀有的独角兽”类似的意思可能不符合中文使用习惯（有点赘余）还会产生歧义 因此不翻译rare会更符合中文语境的同时不影响原意 是否 省略掉rare更合适些呢（

2023-02-24 09:50 UTC, luoxueyasha commented on projects/1.16/assets/fantasy-mounts/fantasy/lang/zh_cn.json
> +  "item.fantasy.diamond_carrot.desc": "可用于繁殖独角兽",
那确实，感觉可以省略（

2023-02-24 17:25 UTC, mamaruo requested changes

2023-02-24 17:25 UTC, mamaruo commented on projects/1.16/assets/fantasy-mounts/fantasy/lang/zh_cn.json
> +  "effect.fantasy.glowing_vision": "发光视野"
| **审查级别** |
|--------------|
| ℹ️ 信息 / 不阻止合并  |

![image](https://user-images.githubusercontent.com/37480168/221242309-24276e87-c480-48ad-be44-b65193f6c5c7.png)

2023-02-24 17:25 UTC, mamaruo commented on projects/1.16/assets/fantasy-mounts/fantasy/lang/zh_cn.json
> +  "item.fantasy.golden_whistle.tagged": "%s 听从于 %s 的命令。 独角兽只会在你拿着口哨时听从你",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |

漏译，指代错误。后一个前一个占位符是独角兽或者北极熊，后一个是玩家名。 use 在这里指按下右键（该键名为“使用”）。

```suggestion
  "item.fantasy.golden_whistle.tagged": "使用后%s会听从%s的命令。只有玩家手持口哨时它们才会听命。",
```
```suggestion
  "item.fantasy.golden_whistle.tagged": "%s会听从%s的命令。右击使用。只有玩家手持口哨时它们才会听命。",
```

2023-02-24 17:25 UTC, mamaruo commented on projects/1.16/assets/fantasy-mounts/fantasy/lang/zh_cn.json
> +  "item.fantasy.golden_whistle.staying": "休息中",
| **审查级别**    | 备注 |
|--------------|----|
| ⚪ 轻微 / 不阻止合并但需三思  |    |
```suggestion
  "item.fantasy.golden_whistle.staying": "原地不动中",
```

2023-02-25 12:28 UTC, AsteriaGrace commented on projects/1.16/assets/fantasy-mounts/fantasy/lang/zh_cn.json
> +  "item.fantasy.golden_carrot_stew.desc": "可用于定位独角兽，据说在接近时会使他们发光",
已补全 应该没有遗漏的标点符号了（）

2023-02-25 12:29 UTC, AsteriaGrace commented on projects/1.16/assets/fantasy-mounts/fantasy/lang/zh_cn.json
> +  "effect.fantasy.glowing_vision": "发光视野"
没太懂这一条 只是用于展示buff的效果吗

2023-02-25 12:35 UTC, AsteriaGrace commented on projects/1.16/assets/fantasy-mounts/fantasy/lang/zh_cn.json
> +  "item.fantasy.golden_whistle.tagged": "%s 听从于 %s 的命令。 独角兽只会在你拿着口哨时听从你",
已更正 同时考虑到英文原文中使用的是“will” 因此我将“使用后%s会听从%s的命令。”一句中的“会”替换为了“将” 若仍有欠缺烦请指出（

2023-02-25 12:41 UTC, Ricky-fight commented on projects/1.16/assets/fantasy-mounts/fantasy/lang/zh_cn.json
> +  "item.fantasy.golden_whistle.not_tagged": "没有标记到任何坐骑。右击标记。",
```suggestion
  "item.fantasy.golden_whistle.not_tagged": "没有标记到任何坐骑。持有该物品右击标记坐骑。",
```

2023-02-25 12:46 UTC, AsteriaGrace commented on projects/1.16/assets/fantasy-mounts/fantasy/lang/zh_cn.json
> +  "item.fantasy.golden_whistle.staying": "休息中",
斟酌了一下 因为Mod中的独角兽用处与原版mc中的马等生物类似 因此将状态设为Staying的场景大多是骑乘独角兽结束后 结合现实考虑独角兽（？）此时有可能会感到劳累 所以翻译成“休息中”似乎更符合使用场景且不会有生硬的感觉 再加上原模组文件内的繁中译本对这一条的翻译也是“休息中” 所以自认“休息中”已是比较合适的译名 故这条如果没有更合适的我就先不打算更改了（）

2023-02-25 18:17 UTC, mamaruo commented on projects/1.16/assets/fantasy-mounts/fantasy/lang/zh_cn.json
> +  "item.fantasy.golden_whistle.staying": "休息中",
结合 stay 的词义和游戏内表现（发出该指令后坐骑确实是一动不动），我认为不需要翻译成“休息”。

> [intransitive](North American English also)to continue to be in a particular place for a period of time without moving away
> \+ adv./prep. **Stay** there and don't move!
> *Oxford Learner's Dictionary*

2023-02-25 18:22 UTC, mamaruo commented on projects/1.16/assets/fantasy-mounts/fantasy/lang/zh_cn.json
> +  "item.fantasy.golden_whistle.tagged": "%s 听从于 %s 的命令。 独角兽只会在你拿着口哨时听从你",
其实 will 翻译成“能”“会”没问题：

used to [talk](https://dictionary.cambridge.org/zhs/%E8%AF%8D%E5%85%B8/%E8%8B%B1%E8%AF%AD-%E6%B1%89%E8%AF%AD-%E7%AE%80%E4%BD%93/talk) about what someone or something is [able](https://dictionary.cambridge.org/zhs/%E8%AF%8D%E5%85%B8/%E8%8B%B1%E8%AF%AD-%E6%B1%89%E8%AF%AD-%E7%AE%80%E4%BD%93/able) or willing to do
《剑桥词典》

不过此处“将”也许更好。
无伤大雅

2023-02-25 18:24 UTC, mamaruo approved these changes
除了上面的那个问题需要斟酌，其他没问题了

2023-02-26 08:08 UTC, AsteriaGrace commented on projects/1.16/assets/fantasy-mounts/fantasy/lang/zh_cn.json
> +  "item.fantasy.golden_whistle.staying": "休息中",
言之有理的 已修改

2023-02-26 13:21 UTC, Ricky-fight approved these changes

2023-02-26 13:22 UTC, merged