Sonorama 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3069
Opened 2023-02-23 14:41 UTC by chunye-shanhui

* create files

* translate

* fix

* fix

* fix

* 修正modid

* refresh

* update to v0.7

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-03-12 04:53 UTC, mamaruo requested changes
只看了前三十行
建议仔细检查原文译文不对应的情况

2023-03-12 04:53 UTC, mamaruo commented on projects/1.19/assets/combat-enchantments/cenchants/lang/zh_cn.json
> +  "enchantment.cenchants.lifesteal.desc": "攻击敌人会回复生命值",
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |

原文：**Lifesteal┃Steal health from nearby foes**
```suggestion
  "enchantment.cenchants.lifesteal": "生命窃取",
  "enchantment.cenchants.lifesteal.desc": "从附近敌人身上窃取生命值",
```

2023-03-12 04:53 UTC, mamaruo commented on projects/1.19/assets/combat-enchantments/cenchants/lang/zh_cn.json
> +  "enchantment.cenchants.lifeline.desc": "在半血一下获得吸收的效果，血量越低，效果越显著",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |

原文：**Shielding┃Gain absorption when out of combat┃Lifeline┃Gain absorption when low**

Absorption 是`抗性提升`，[原版术语](https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96)有待加强

2023-03-12 04:53 UTC, mamaruo commented on projects/1.19/assets/combat-enchantments/cenchants/lang/zh_cn.json
> +  "effect.cenchants.lifesteal_cooldown": "生命值冷却时间",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |

原文：**Lifesteal Cooldown**
```suggestion
  "effect.cenchants.lifesteal_cooldown": "生命窃取冷却",
```
```suggestion
  "effect.cenchants.lifesteal_cooldown": "生命窃取冷却时间",
```

2023-03-12 04:58 UTC, mamaruo commented on projects/1.19/assets/combat-enchantments/cenchants/lang/zh_cn.json
> +  "enchantment.cenchants.darkness.desc": "在夜晚获得强化增益，但在白天会被燃烧",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |

原文：**Curse of Darkness┃Gain buffs in the shadows, but burn in the light**
```suggestion
  "enchantment.cenchants.darkness": "黑暗诅咒",
  "enchantment.cenchants.darkness.desc": "在阴影中获得正面效果，但在阳光下会燃烧",
```

2023-04-02 10:35 UTC, ChuijkYahus commented
* 7+7时限已到，如需提交可自行reopen

@chunye-shanhui

2023-04-02 10:35 UTC, closed without merging