Geckolib 1.12.2翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3074
Opened 2023-02-25 05:22 UTC by StarryCamile

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-02-25 13:17 UTC, Ricky-fight requested changes

2023-02-25 13:17 UTC, Ricky-fight commented on projects/1.12.2/assets/geckolib/geckolib3/lang/zh_cn.lang
> +tile.geckolib3.botariumblock.name=肉毒杆菌
这是啥？

2023-02-28 02:40 UTC, luoxueyasha commented on projects/1.12.2/assets/geckolib/geckolib3/lang/zh_cn.lang
> +tile.geckolib3.botariumblock.name=肉毒杆菌
额，好像确实能和en_us对的上？

2023-07-14 19:18 UTC, mamaruo commented
请回应审阅意见，否则该pr将被关闭。

2023-07-24 02:22 UTC, closed without merging