添加了 Advanced Rifles 模组的翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #3092
Opened 2023-03-09 10:30 UTC by wfan-os

- [x ] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x ] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-03-13 16:33 UTC, mamaruo commented on projects/1.12.2/assets/advanced-rifles/advancedrifles/lang/zh_cn.lang
> +item.advancedrifles.mp5stockclosed.name=MP5 (售罄)
```suggestion
item.advancedrifles.mp5stockclosed.name=MP5（枪托收起）
```

![image](https://user-images.githubusercontent.com/37480168/224766090-5067b1eb-ccc8-4717-898a-5e72f9b70a1b.png)

结合纹理：[MP5 (Closed Stock) - MC百科](https://www.mcmod.cn/item/497303.html)

2023-03-14 02:32 UTC, wfan-os commented on projects/1.12.2/assets/advanced-rifles/advancedrifles/lang/zh_cn.lang
> +item.advancedrifles.mp5stockclosed.name=MP5 (售罄)
好的，更改了

2023-03-18 06:28 UTC, ChuijkYahus commented on projects/1.12.2/assets/advanced-rifles/advancedrifles/lang/zh_cn.lang
> +item.advancedrifles.mp5stockclosed.name=MP5 (售罄)
怎么改成半角的括号了呢？

2023-03-18 06:29 UTC, ChuijkYahus commented on projects/1.12.2/assets/advanced-rifles/advancedrifles/lang/zh_cn.lang
> +item.advancedrifles.mp5stockclosed.name=MP5 (枪托收起)
```suggestion
item.advancedrifles.mp5stockclosed.name=MP5（枪托收起）
```

2023-04-05 02:04 UTC, luoxueyasha commented on projects/1.12.2/assets/advanced-rifles/advancedrifles/lang/zh_cn.lang
> +itemGroup.advancedrifles=高级步枪
上文`Advanced`为`先进`，怎么这里就翻译成`高级`了

2023-04-05 05:13 UTC, wfan-os commented on projects/1.12.2/assets/advanced-rifles/advancedrifles/lang/zh_cn.lang
> +item.advancedrifles.crossbow_dart.name=弩镖
确定就是镖，因为外观上确实是镖；但跟一般意义上的飞镖不同的是，这个仅仅只是 crossbow 的弹药，单独拿出来没有任何作用的（也就是自己不能单独扔出去造成伤害）

2023-04-05 05:25 UTC, wfan-os commented on projects/1.12.2/assets/advanced-rifles/advancedrifles/lang/zh_cn.lang
> +item.advancedrifles.crossbow.name=弩弓
1. 外观上不同：原版的弩更像是古代的弩，也是木制品；而本mod里面的是显然是枪+弩，为现代科技金属制品

2. 发射效果不同：原版的弩发射出来是“xiu”的一声，发射一根有轨迹的实体箭矢，动画效果是弩缓缓张开而后箭被射出去；而本mod里面发射则是枪一样“pa”的一声，动画效果仅仅是枪口冒出火光，没有弩张开的动画；

所以，综上所述，翻译成“弩枪”最为合适。

PS：关于明明发射的是弩镖（Crossbow Dart），并且无论是crossbow还是crossbow dart，合成材料仅仅包括铁锭和Gray Concrete，并没有火药，但却发出枪械声音并冒出火光这件事；在这里应该理解为作者并没有好好做mod，懒得给本应该是冷兵器的Crossbow添加自身相应的声音和动画素材，而仅仅简单地用热兵器（枪械）替代了而已（毕竟这个mod仅仅只是 MyCrayFish's Gun 的一个小小的附属mod而已，作者没好好做很正常）

2023-04-05 10:02 UTC, luoxueyasha commented on projects/1.12.2/assets/advanced-rifles/advancedrifles/lang/zh_cn.lang
> +item.advancedrifles.crossbow.name=弩弓
那就`弩枪`呗，没有`弓`的要素了都

2023-07-14 19:12 UTC, mamaruo submitted a review, later dismissed
Mk II 是否需要改为 `X型`？
这个help wanted是为什么打的

2023-07-15 14:20 UTC, ChuijkYahus commented
> Mk II 是否需要改为 `X型`？ 这个help wanted是为什么打的

不会武器名的翻译

2023-07-17 02:59 UTC, luoxueyasha requested changes

2023-07-17 02:59 UTC, luoxueyasha commented on projects/1.12.2/assets/advanced-rifles/advancedrifles/lang/zh_cn.lang
> +item.advancedrifles.rifle_advanced.name=高级步枪
```suggestion
item.advancedrifles.rifle_advanced.name=先进步枪
```
`Advanced`的通用译名即`先进`，此问题请全文通查
另：早在4月就指出了上下不一致的问题，结果全改成`高级`了

2023-07-17 03:01 UTC, luoxueyasha commented
> Mk II 是否需要改为 `X型`？ 

`Mark X`没有统一的译法，一般译作`Mk X`、`Mk.X`、`X型`
我个人建议是保留为`Mk II`，或者以维基百科之类的为准

2023-07-22 11:31 UTC, luoxueyasha approved these changes

2023-07-22 11:32 UTC, luoxueyasha approved these changes
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/58bbf447-fd17-416d-94af-8ff8d3e3c8ac)

2023-07-25 12:20 UTC, merged