添加了 Hostile Craft 模组的翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #3093
Opened 2023-03-09 10:35 UTC by wfan-os

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-03-13 16:26 UTC, mamaruo requested changes

2023-03-13 16:26 UTC, mamaruo commented on projects/1.12.2/assets/hostile-craft/hostilecraft/lang/zh_cn.lang
> +item.piece_of_nether.name=下界碎片
统一一下

2023-03-14 02:34 UTC, wfan-os commented on projects/1.12.2/assets/hostile-craft/hostilecraft/lang/zh_cn.lang
> +tile.niter.name=硝石矿石
已修改

2023-03-14 02:35 UTC, wfan-os commented on projects/1.12.2/assets/hostile-craft/hostilecraft/lang/zh_cn.lang
> +tile.evaporite.name=蒸发盐矿石
已修改

2023-03-14 02:35 UTC, wfan-os commented on projects/1.12.2/assets/hostile-craft/hostilecraft/lang/zh_cn.lang
> +item.sulfur.name=硫
已修改

2023-03-14 02:45 UTC, wfan-os commented on projects/1.12.2/assets/hostile-craft/hostilecraft/lang/zh_cn.lang
> +item.piece_of_nether.name=下界碎片
更改了

2023-03-14 16:55 UTC, mamaruo approved these changes

2023-03-18 06:28 UTC, ChuijkYahus commented on projects/1.12.2/assets/hostile-craft/hostilecraft/lang/zh_cn.lang
> +tile.evaporite.name=蒸发盐
```suggestion
tile.evaporite.name=蒸发岩
```
https://www.termonline.cn/search?k=Evaporite&r=1679120865579

2023-04-02 10:39 UTC, ChuijkYahus approved these changes

2023-04-03 13:10 UTC, merged