添加了 Howling Moon 模组的翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #3094
Opened 2023-03-09 10:39 UTC by wfan-os

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-03-14 00:59 UTC, luoxueyasha requested changes

2023-03-14 00:59 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +ability.Howl.desc=大声嚎叫并召唤狼魂，强度和持续时间随等级增加   冷却: 1 分钟
```suggestion
ability.Howl.desc=大声嚎叫并召唤狼魂，强度和持续时间随等级增加   冷却：1 分钟
```

2023-03-14 00:59 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +attribute.Resistance.desc=每点抗性都会赋予对以下负面效果的免疫值: 1. 虚弱，2. 中毒，3. 缓慢，4. 挖掘疲劳，5. 凋零
```suggestion
attribute.Resistance.desc=每点抗性都会赋予对以下负面效果的免疫值：1. 虚弱，2. 中毒，3. 缓慢，4. 挖掘疲劳，5. 凋零

```

2023-03-14 00:59 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.config.dimID=甚至本模组中的维度的ID
```suggestion
werewolf.config.dimID=设置本模组中的维度的ID
```

2023-03-14 00:59 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.config.setLevelCap=为狼人设置最高等级，我强烈建议你不要设置超过默认值
```suggestion
werewolf.config.setLevelCap=为狼人设置最高等级，强烈建议不要设置超过默认值
```

2023-03-14 00:59 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +commands.wereprogress.failure=不能将进度设置为 0 以下
```suggestion
commands.wereprogress.failure=不能将狼人进度设置为 0 以下
```
和原版的进度区分一下

2023-03-14 00:59 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +skills.reset.desc=消耗10个等级
```suggestion
skills.reset.desc=消耗 10 个等级
```
![image](https://user-images.githubusercontent.com/38830216/224864309-0f8ccc9c-4da2-4474-bf53-7e631592f25d.png)

2023-03-14 00:59 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.config.spawnSilverOre=在世界中设置银矿
？

2023-03-14 00:59 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +tile.howlingmoon.wolfsbane.name=附子草
```suggestion
tile.howlingmoon.wolfsbane.name=乌头
```
学名和俗名都是`乌头`

2023-03-14 00:59 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.message.sleep=体内的兽性是你无法平静!
```suggestion
werewolf.message.sleep=体内的兽性使你无法平静！
```

2023-03-14 00:59 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.message.antiimmune=附子草被从你的身体中排除出去了，你现在变得易于感染变狼症了!
```suggestion
werewolf.message.antiimmune=乌头从你的身体中被排出去了，你现在更容易感染变狼症了！
```
好好地重新读一下你的译文，减少[翻译腔](https://zh.wikipedia.org/wiki/Wikipedia:%E7%BF%BB%E8%AF%91%E8%85%94)

2023-03-14 00:59 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.message.calmingcure=你的身体冷静了下来，变狼症消退了
```suggestion
werewolf.message.calmingcure=你的身体冷静了下来，变狼症消退了。
```
```suggestion
werewolf.message.calmingcure=你的身体冷静了下来，变狼症的效果消退了。
```
```suggestion
werewolf.message.calmingcure=你的身体冷静了下来，变狼症的症状消退了。
```

2023-03-14 02:56 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +ability.Howl.desc=大声嚎叫并召唤狼魂，强度和持续时间随等级增加   冷却: 1 分钟
已修改

2023-03-14 02:56 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +attribute.Resistance.desc=每点抗性都会赋予对以下负面效果的免疫值: 1. 虚弱，2. 中毒，3. 缓慢，4. 挖掘疲劳，5. 凋零
已修改

2023-03-14 02:57 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.config.dimID=甚至本模组中的维度的ID
已修改

2023-03-14 02:58 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +commands.wereprogress.failure=不能将进度设置为 0 以下
已修改

2023-03-14 02:59 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.config.setLevelCap=为狼人设置最高等级，我强烈建议你不要设置超过默认值
已修改

2023-03-14 02:59 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +skills.reset.desc=消耗10个等级
已修改

2023-03-14 03:02 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.message.sleep=体内的兽性是你无法平静!
已修改

2023-03-14 03:03 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.message.calmingcure=你的身体冷静了下来，变狼症消退了
已修改

2023-03-14 03:04 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.config.spawnSilverOre=在世界中设置银矿
已修改

2023-03-14 03:07 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.message.antiimmune=附子草被从你的身体中排除出去了，你现在变得易于感染变狼症了!
已修改

2023-03-14 03:29 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +tile.howlingmoon.wolfsbane.name=附子草
但我查了下百科，附子草属于乌头类植物中250个分支之一。因此，我认为翻译成乌头是不准确的，乌头这个范围太大了。
还有，在mcmod上给出的官方翻译在，wolfbane也被翻译成“附子草”。
事实上，附子草还有一个俗称叫“狼毒草”，我觉得结合起英文 wolfbane 来说，狼毒草更加生动通俗，因为玩家一看名字就知道这个植物是用来干什么的了。
注：在游戏中这个草可以驱赶狼人，和酿造克制狼人的药水，用途比较广泛，不是单纯的装饰用植物。

2023-03-14 14:42 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +tile.howlingmoon.wolfsbane.name=附子草
# 关于“wolfsbane”的译名争议
`Wolfsbane`（或作`wolf's-bane`）的学名为`Aconitum`（[乌头属 - 维基百科](https://zh.wikipedia.org/wiki/%E4%B9%8C%E5%A4%B4%E5%B1%9E)，[Aconitum - Wikipedia](https://en.wikipedia.org/wiki/Aconitum)），泛指所有的乌头属植物，并不特指某一种乌头。如果能明确mod中这种植物的种名的话，麻烦指正。
`附子`为乌头的子根加工品（[附子 - 药素网](http://zyc.yaosuce.com/fuzi/index.html)），不能作为这种植物的称呼，就如不能用`阿胶`称呼`驴`一样。此外，在该引用源中出现的乌头种学名（`Aconitum carmichaelii`）也译作`乌头`（[乌头 - 植物科学数据中心](https://www.plantplus.cn/cn/sp/Aconitum%20carmichaelii)）。
除此之外，中药中还存在与乌头无关的`白附子`、`土附子`、`蛇附子`，容易造成混淆。

# 关于“狼毒草”这一译名的不准确性
`狼毒草`虽然看上去合情合理，字面意义上有“治疗狼人症状的草药”这层含义，但是中文语境中存在与乌头几乎无亲缘关系的`狼毒花`（[狼毒花 - Wikipedia](https://zh.wikipedia.org/wiki/%E7%8B%BC%E6%AF%92%E8%8A%B1)，学名`钩吻`（`Gelsemium elegans`，[狼毒草 - 药素网](http://zyc.yaosuce.com/langducao/index.html)）又称`狼毒草`、`断肠草`）、`狼毒大戟`（[狼毒大戟  - Wikipedia](https://zh.wikipedia.org/wiki/%E7%8B%BC%E6%AF%92%E5%A4%A7%E6%88%9F)）和`海芋`（[海芋 - Wikipedia](https://zh.wikipedia.org/wiki/%E6%B5%B7%E8%8A%8B)）。
因此，基本可以排除`狼毒草`和`wolfsbane`的关系。

# 关于其他来源的翻译文本问题
MCMOD的翻译并非是最准确的，也并非是最新的，全靠爱好者手动维护。MCMOD那边会挑选受众更广，更为准确的翻译，其中有不少是从i18n仓库中搬运过去的。既然要自己做一份翻译，那么就不要以同一语素衍生的译名作为参考要素。
官方中文也不一定是准确的，有许多mod作者并不懂除了母语和英文外的其他语言，因此他们也无法掌握管库中翻译版本的准确性。尽管可以作为参考，但是有错误还是要修改的。
库中现存的翻译也不一定准确，例如远古时期的错译问题、某一指名模组导致扩展mod的译名的将错就错等等。
除此之外，我没有见到mod中包含zh_cn文件，因此MCMOD上的现有译名也并非官方译名。和这个mod联动的[Vampirism](https://www.mcmod.cn/class/930.html)中也未见到`wolfsbane`的相关内容。

综上所述，库中现存的`狼毒草`和`附子草`，都不是wolfsbane的准确译名。其准确译名就是`乌头`。

2023-03-14 15:43 UTC, DrIceTea123 commented
给你们看个像的（）
![模组中的Wolfsbane](https://user-images.githubusercontent.com/111784151/225046398-d42cdfec-5a8e-404e-96a3-7a776848d013.png)
这是模组中的`Wolfsbane`
![image](https://user-images.githubusercontent.com/111784151/225052123-96f5637a-7133-4b21-9c16-0ba724ee7854.png)
这是`舟形乌头`，乌头属的一种（图片来源[百度百科](https://baike.baidu.com/item/%E8%88%9F%E5%BD%A2%E4%B9%8C%E5%A4%B4/111472)）

**以下为个人观点：**
- 用属名称呼一个植物似乎略欠妥当，用`附子草`或者用`舟形乌头`或其别名`欧乌头`更加准确，如上图；
- “乌头”一词用作种名，与“乌头”（学名川乌头，多年生草本植物，用作中药）冲突；
- 在各种和狼人有关的作品（电影、游戏等）中多用`附子草`这一译名；我自己在百度搜索“附子草 狼人”能搜出相关结果，搜“乌头 狼人”少有相关内容；
- 关于`附子为乌头的子根加工品，不能作为这种植物的称呼，就如不能用阿胶称呼驴一样`，我认为`附子`和`附子草`不是同一种东西，正如`乌头`和[乌头碱](https://baike.baidu.com/item/%E4%B9%8C%E5%A4%B4%E7%A2%B1/8666389)不是同一种东西一样。

综上，我赞成`附子草`

2023-03-14 15:43 UTC, DrIceTea123 commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +tile.howlingmoon.wolfsbane.name=附子草
给你们看个像的（）
![模组中的Wolfsbane](https://user-images.githubusercontent.com/111784151/225046398-d42cdfec-5a8e-404e-96a3-7a776848d013.png)
这是模组中的`Wolfsbane`
![image](https://user-images.githubusercontent.com/111784151/225052123-96f5637a-7133-4b21-9c16-0ba724ee7854.png)
这是`舟形乌头`，乌头属的一种（图片来源[百度百科](https://baike.baidu.com/item/%E8%88%9F%E5%BD%A2%E4%B9%8C%E5%A4%B4/111472)）

**以下为个人观点：**
- 用属名称呼一个植物似乎略欠妥当，用`附子草`或者用`舟形乌头`或其别名`欧乌头`更加准确，如上图；
- “乌头”一词用作种名，与“乌头”（学名川乌头，多年生草本植物，用作中药）冲突；
- 在各种和狼人有关的作品（电影、游戏等）中多用`附子草`这一译名；我自己在百度搜索“附子草 狼人”能搜出相关结果，搜“乌头 狼人”少有相关内容；
- 关于`附子为乌头的子根加工品，不能作为这种植物的称呼，就如不能用阿胶称呼驴一样`，我认为`附子`和`附子草`不是同一种东西，正如`乌头`和[乌头碱](https://baike.baidu.com/item/%E4%B9%8C%E5%A4%B4%E7%A2%B1/8666389)不是同一种东西一样。

综上，我赞成`附子草`

2023-03-14 16:07 UTC, mamaruo commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +tile.howlingmoon.wolfsbane.name=附子草
甚至还有一个[Howling Moon - Rebooted ](https://www.mcmod.cn/class/5844.html)本模组的重制版，该模组使用的是`狼毒`，然后我再一看，这[官译](https://github.com/YoaanYT/howlingmoon-rebooted-Forge/blob/d3420dea71d7651f23b5dc6fd611dee0f0bb7b59/src/main/resources/assets/howlingmoon_rebooted/lang/zh_CH.json)简直逆大天：

MC百科不会审查译名的准确性，只审查译名来源，严格要求译名来自官方或CFPA（本仓库）。但是，由于整个网站的条目过多（近70万），无法保证在共笔过程中不出差错，所以MC百科不能视作可靠信源。

另外，不需要每个 conversation 都回复 `已修改`，`mark as resolve` 和 `Outdated` 都能让我们识别到你已经做出修改。

2023-03-15 00:15 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +tile.howlingmoon.wolfsbane.name=附子草
利用英文翻译法：wolfsbane --(Google搜索)--> [Aconitum](https://en.wikipedia.org/wiki/Aconitum) --（baidu搜索)--> 乌头，所以，单就 Wolfsbane 来说应该是翻译成 乌头 的。

2023-03-15 00:23 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +tile.howlingmoon.wolfsbane.name=附子草
可还有两个问题：
1. 游戏里存在一种药品，叫 Wolfsbane Potion，该药水的作用是减轻变狼症的症状，甚至使得玩家完全从变狼症中康复过来，甚至是使玩家对此免疫；那么，基于上述功能，以及此时该药水已经是Wolfsbane处理（酿造）后的产物，该药水应该译作什么？乌头药水？还是附子草药水？还是狼毒药水？个人感觉此时译作“狼毒药水”更合理，或者叫“克狼药水”。因为，现实中乌头不能酿造出能对抗变狼症药水，因为现实中一来没有狼人，二来即使是神话传说中也不存在用乌头酿药以克制狼人的说法。
2. 游戏中有类似如下的 message （此类message有很多，就不一一列举了）：
The wolfsbane cures your infection!
比如这句话，出现在玩家喝下1.中所提到的 Wolfsbane Potion 以后，变狼症被完全消除的情况。
那么这里应该翻译成什么好呢，如果仅仅是根据原文，那么就是“乌头治愈了你的感染！”
可问题是玩家不是直接把乌头给吃了，而是喝下了用乌头酿造的 Wolfsbane Potion，那么，这应该如何翻译？
还是翻译成“狼毒药水治愈了你的感染！”还是翻译成“克狼药水治愈了你的感染！”呢？

2023-03-15 00:54 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +tile.howlingmoon.wolfsbane.name=附子草
抱歉，之前回复的语气有点冲。稍微整理了一下关于`乌头`的资料，希望能帮助讨论：
* **川乌头**：学名为`Aconitum carmichaelii`，正名为`乌头`，即“乌头属乌头种”：
![image](https://user-images.githubusercontent.com/38830216/225171621-630c9232-91bb-4349-a12c-cab461998d05.png)
* **狼毒乌头**：学名为`Aconitum lycoctonum`，但是花为黄绿色：
![image](https://user-images.githubusercontent.com/38830216/225171579-2a83dffb-a06d-4406-baaa-95cdd397be25.png)
* **舟形乌头**：学名为`Aconitum fischeri`，异名为`Aconitum napellus`，正名为`薄叶乌头`：
![image](https://user-images.githubusercontent.com/38830216/225171563-a81a53ae-79be-482c-82f7-a40426deb1ac.png)
* **紫花高乌头**：学名为`Aconitum septentrionale`，异名为`Aconitum excelsum`，与模组贴图的花色相近，但是花型存在差别：
![image](https://user-images.githubusercontent.com/38830216/225175520-8bba40ab-5b9f-4404-84de-d102bf872c52.png)

（资料来源：https://www.plantplus.cn/cn ，图片版权归中国植物图像库以及拍摄者所有）

没有找到以`附子草`作为学名的植物，但是根据现有的一些创作作品中的`附子草`：
* 《权力的游戏》（Game of Thrones）：附子草（Wolfsbane），是金雀花的远亲，有着蓝色或黄色的散落花朵。（https://asoiaf.huijiwiki.com/wiki/%E9%99%84%E5%AD%90%E8%8D%89 ）
  * 这里`附子草`即`乌头`（但不确定是哪一种），“金雀花的远亲”这一描述在现实中并不妥当，尽管两者花型相似。
* 《巫师》（The Witcher）系列：可以在洞穴或狼人的巢穴中找到，亦可以从大多数的药品商人处购买。没有太多的物品描述，但是就昆特牌的插画来说，和现实中的`Aconitum carmichaelii`（乌头）相近，花色相对更深。（https://witcher.fandom.com/wiki/Wolfsbane ）
*  《模拟人生4》（The Sims 4）：根据游戏截图，这种植物长相形似`Aconitum carmichaelii`（乌头），花色偏蓝艳。（https://www.ggrecon.com/guides/sims4-werewolves-wolfsbane/ ）
* 《月光嘉年华》（月光のカルネヴァーレ）：抵抗人狼的人偶部队名，日文写作`鳥兜`，即日文的`Aconitum`（乌头属）（https://ja.wikipedia.org/wiki/%E3%83%88%E3%83%AA%E3%82%AB%E3%83%96%E3%83%88 ），注音为`ルパーリヤ`，即意大利语的`Aconitum lycoctonum`（狼毒乌头）（https://en.wiktionary.org/wiki/luparia ）。（https://zh.wikipedia.org/wiki/%E6%9C%88%E5%85%89%E5%98%89%E5%B9%B4%E8%8F%AF ）

另：`乌头属`也称`附子属`。中药中将`Aconitum`的母根称为`乌头`，将子根称为`附子`，去除子根的块根又称为`天雄`。（https://ja.wikipedia.org/wiki/%E3%83%88%E3%83%AA%E3%82%AB%E3%83%96%E3%83%88#%E5%8C%BB%E7%99%82%E7%94%A8 ，百度百科）


* 个人观点：
由于大量的影视资料说明，`附子草`即`Aconitum carmichaelii`（乌头）或`Aconitum lycoctonum`（狼毒乌头），就植物生态而言不存在太大变动。由于本模组中的花色为蓝紫色，故个人认为译作`乌头`最为合适。

2023-03-15 01:03 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +tile.howlingmoon.wolfsbane.name=附子草
原版中的酿造素材和酿造效果也不是一一对应的，例如河豚→水肺药水→水下呼吸效果，甚至`水肺`和`水下呼吸`对应的都是`Water Breathing`。
至于各种带`wolfsbane`的句子，以`The wolfsbane cures your infection!`为例：
* 乌头治愈了你的变狼症！
* 乌头的效果治愈了你的病症！
* 用乌头酿造的药水治愈了你的感染！
* XX药水治愈了你的感染！（此处XX为药水名）

2023-03-15 01:05 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +tile.howlingmoon.wolfsbane.name=附子草
> 1. 二来即使是神话传说中也不存在用乌头酿药以克制狼人的说法。

这句有失妥当，欧洲民间确实有这样的说法，也被用入了影视游戏作品当中；但是人们后来发现这东西对普通人也有效，鉴别不出狼人之后，就变得没啥作用了。

2023-03-15 01:13 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +tile.howlingmoon.wolfsbane.name=附子草
或者翻译成“克狼药水”我觉得也很贴切

2023-03-15 02:15 UTC, luoxueyasha reviewed
错译和翻译腔痕迹太多了……
请**仔细**阅读 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)，确保自己提交的是一份合标准的翻译文件。其中的《模组简体中文规范和指南》的最新版可[在此](https://cfpa.site/TransRules/)阅读。

2023-03-15 02:15 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +ability.Climbing.desc=允许你在某些方块的表面垂直攀爬，允许攀爬的距离随等级增加
```suggestion
ability.Climbing.desc=可在某些方块的表面垂直攀爬，可攀爬的方块种类随等级增加
```
游戏效果如此

2023-03-15 02:15 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +ability.Leap.desc=允许你用难以置信的速度向前跳跃
```suggestion
ability.Leap.desc=以难以置信的速度向前跳跃
```

2023-03-15 02:15 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +ability.Ram.desc=冲刺时，与你碰撞的实体被击退并镇住
```suggestion
ability.Ram.desc=眩晕并击退疾跑时相撞的实体
```

2023-03-15 02:15 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +ability.Lift.desc=允许你将实体抬起并携带，前提是爪子上没有携带别的东西
```suggestion
ability.Lift.desc=可以抬起并携带实体，前提是爪子上没有携带其他物品
```

2023-03-15 02:15 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +ability.Bite.desc=撕咬对方并让对方感染上你的变狼症
```suggestion
ability.Bite.desc=撕咬其他玩家并使其感染上变狼症
```

2023-03-15 02:17 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +ability.ScentTracking=气味追踪
好的，这个mod是我人工翻译的，只是我翻得没文采，比较机械

2023-03-15 02:27 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +tile.howlingmoon.wolfsbane.name=附子草
个人观点：
`Wolfsbane`→`乌头`，`乌头毒`（作为药水效果）
`Wolfsbane Potion`→`狼毒药水`
`克狼药水`有一种说不出来的怪

2023-03-15 02:31 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +ability.ScentTracking=气味追踪
多读读[翻译腔 - 维基百科](https://zh.wikipedia.org/wiki/Wikipedia:%E7%BF%BB%E8%AF%91%E8%85%94)
**本项目对机翻、生硬翻译并不友好，还请在提交具有这些特征的文件时深思熟虑。** - [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)
如果你的母语是中文的话，建议在提交之前自己阅读一下自己的译文，或者拿给母语为中文的人帮忙看看

2023-03-15 02:59 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +ability.ScentTracking=气味追踪
第一，我的母语是中文；
第二，我确实是自己翻译的，没用机翻，最多查查字典；
第三，因为不是文学专业或者翻译专业，很多情况下我自己都不太能说出来什么才算“文雅”，比如你给的翻译，我总觉得你给的翻译比我的好，可我就是死活想不到可以这么翻，我只能做到“信”和“达”，就是把我阅读得到的原文的意思（反正尽我能力了）表示出来；
第四，我看到很多人有时过于追求“雅”，比如网易云我听音乐的时候经常看到歌词翻译得过于文雅，将原文朴素的语言弄得非常高深莫测，不好读懂，我认为这样卖弄文采之嫌，个人倾向于翻译得尽可能朴素易懂（但“易懂”这里显然是指我认为我能轻易读懂译文和get到里面的意思，毕竟我也不可能统计其它玩家的意见，毕竟我也不是专业的翻译人士，我也没有接受过专业的翻译训练）；
第五，综上，这就是我认为译文需要审查的原因，同时非专业人士存在翻译腔也是在所难免的（其实你不指出来我都不知道我这叫翻译腔，我凭借自己感觉认为没任何问题），但请你不要误解我的一片热枕，也不要认为我是拿垃圾机翻来凑数的，因为我知道这是开源项目，你们也不会付费给我，因此这是我出于个人兴趣的奉献！请谅解！

2023-03-15 03:24 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +ability.Mastery=精通
有的，在这里
![Untitled](https://user-images.githubusercontent.com/72018068/225198122-bb2a10cf-bc3b-4bb8-8237-8c15f8824885.png)

2023-03-15 03:27 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +ability.Mastery=精通
我也没看到。。。可问题是英文原文件里有这个，所以只能翻译了。
我怀疑是作者没做完，弃坑了。

2023-03-15 03:29 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +tile.howlingmoon.wolfsbane.name=附子草
那统一成这么翻吧：
Wolfsbane 作为一种植物时翻译成“乌头”；
wolfsbane 在 message 体现时，是对玩家的某种药水效果，就翻译成“乌头毒”；
Wolfsbane Potion 就翻译成“狼毒药水”。

2023-03-15 03:38 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +ability.ScentTracking=气味追踪
以下是**我个人的意见**，不代表CFPA群体的意见：
要审查自己的文本其实很简单，假装这份文本是不认识的人翻的，把它丢入游戏里自己跑一遍，便能看出在翻译的不太恰当的情况。
有热情是好的，但是译文禁不住推敲则是另一说了，不要以一腔热忱作为自己能力不足的挡箭牌。生搬硬套的翻译并不能体现你对原文的深厚感情。
以及多推敲多考虑，例如大多数模组中含有`You`这一指代，指代的是什么呢？`你`本人？`玩家`这个实际存在的人？`玩家角色`这个被操控的对象？还是省略主语？不同语言具有不同的美感，翻译也不是两个语言之间的的完全映射关系。
除此之外我个人，以及为i18n做出贡献的译者们也不是文学或者翻译专业的，只是平时多注意这些细微差别罢了。

> 译事三难：信、达、雅。求其信已大难矣，顾信矣不达，虽译犹不译也，则达尚焉。

严复先生提出的“信、达、雅”只是一种翻译方法的个人心得，它不是什么圣经，也不是什么必须遵守的条例，但是确实值得学习。
这三者并不是递进关系，而是并列关系。
* `信`即译文不偏离原意，不随意增减意思；
* `达`即译文通顺明白，不拘泥于原文形式；
* `雅`则“简明优雅”，选词得体。
翻译不偏离原意，观众能读懂，选词恰当，即可称为一篇合格的译文。

2023-03-15 03:39 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +tile.howlingmoon.wolfsbane.name=附子草
再次议论以下，个人觉得“乌头毒”听起来怪怪的，因为乌头酿造的药水是 cure （治好了）狼人症，那么不应该翻译成某种“毒性”，应该翻译成某种“药性”才对。
同时 Wolfsbane Potion 的作用就是某种药物，即治好玩家身上的狼人症，那应当翻译为“乌头草药药水”，或者“乌头药水”才对。
因为，Wolfsbane Potion 如果翻译成“狼毒药水”的话，很容易被理解成这个东西是不是还有个喷溅型药水，喷到狼人身上可造成巨额伤害的那种，但实际上游戏里并不存在喷溅型。

2023-03-15 03:46 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +tile.howlingmoon.wolfsbane.name=附子草
“是药三分毒”，并且这东西喝下去会中毒+反胃，高等级狼人喝下去副作用更强
乌头本身也是一种毒草，既然都要体现`Wolf`这一侧了，那么`狼毒`显然比`乌头`更易懂
没有喷溅型药水、滞留型药水等，完全不影响它被译作`狼毒药水`；如果真有喷溅型的药水，我会更偏向于翻译为`毒狼药水`

2023-03-15 03:47 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +ability.Mastery=精通
感觉`聪慧`不像是描述技能等级的词语……`通晓`？

2023-03-15 03:48 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +ability.Mastery=精通
对，这个更好些，那就选择“知晓”吧

2023-03-15 03:50 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +tile.howlingmoon.wolfsbane.name=附子草
这么说也是。。。那就按你给的来吧

2023-03-15 03:52 UTC, wfan-os commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +tile.howlingmoon.wolfsbane.name=附子草
哦还有一个成就：
enchantment.Wolfsbane=Wolfsbane （狼人杀手）
我给这么翻译的，虽然按原意（其实我在游戏里一直找不到这个mod的进度在哪）应该翻译成“乌头”，但我觉得按照 Wolf + Bane 拆成狼人杀手更好，因为乌头自己不就是狼人杀手么

2023-07-30 10:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3094) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3094) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3094) it.</sub>

2023-08-19 23:41 UTC, luoxueyasha requested changes
这堆guide.message有大量翻译腔问题
请自行修正

2023-08-19 23:41 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +guide.message.welcome0=欢迎狼仔，来和我谈谈，你有很多东西要学。
```suggestion
guide.message.welcome0=欢迎啊，小狼仔。来和我谈谈，你还有很多东西要学。
```
原文
`Welcome pup. Come talk with me. You have much to learn.`

2023-08-19 23:41 UTC, luoxueyasha commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +guide.message.welcome1=使用你的狼形到达下一个区域继续训练。
```suggestion
guide.message.welcome1=使用狼形态到达下一个区域以继续进行训练。
```
```suggestion
guide.message.welcome1=使用狼形态到达下一个区域。
```
```suggestion
guide.message.welcome1=使用狼形态到达下一个区域以进行后续的训练。
```
原文
`Use your wolf form to reach the next area to continue your training.`

2023-08-27 03:29 UTC, luoxueyasha commented
@wfan-os 
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

2023-08-27 22:04 UTC, luoxueyasha commented
请记得签署CLA

2023-09-09 00:47 UTC, luoxueyasha approved these changes
还是有一堆翻译腔问题
但是PR拖得太久了，就这样吧……
需要其他的审核过来看一眼

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +ability.Feral.desc=你已经舍弃了你的人性，彻底与野兽为伍；无论是你的属性还是弱点都增强了，即便处于人类形态下依然如此；护甲和工具对变身后的你毫无作用，而即使处于人类形态下，这些东西的效用还是下降了
```suggestion
ability.Feral.desc=你已经舍弃了你的人性，彻底与野兽为伍；无论是你的属性还是弱点都增强了，即便处于人类形态下依然如此；护甲和工具对变身后的你毫无作用，即使处于人类形态下，这些东西的效率也下降了
```
微调

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +attribute.Regeneration=再生
`生命恢复`不知道怎么样

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +attribute.Fall.desc=增加不承担摔落伤害的下落距离
```suggestion
attribute.Fall.desc=增加不受摔落伤害的下落距离
```

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +attribute.Exhilarating.desc=变身时给予暂时的增益，增加饱和度并给予正面药水效果，振奋功能至多只能每5分钟启动一次
```suggestion
attribute.Exhilarating.desc=变身时给予暂时的增益，增加饱和度并给予正面药水效果，振奋属性至多只能每 5 分钟启动一次
```

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +attribute.Exhilarating=振幅
```suggestion
attribute.Exhilarating=振奋
```

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +attribute.Dexterity.desc=增加爪子的效果
```suggestion
attribute.Dexterity.desc=增强爪子的效果
```

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +skills.reset.inclination2=进度会被重置到选择前的阶段
```suggestion
skills.reset.inclination2=进度会被重置到选择前的状态
```

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +skills.broke=错误
```suggestion
skills.broke=错误。真是相当“毛”糊的问题，干得不错。
```
补个垃圾谐音双关

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +commands.werelevel.usage=/werelevel <amount> or /werelevels <amount>
```suggestion
commands.werelevel.usage=/werelevel <数量> 或 /werelevels <数量>
```

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +commands.wereprogress.success=将 %s 的狼人进度设置为 (%d, %s)
```suggestion
commands.wereprogress.success=将 %3$s 的狼人进度设置为 (%1$d, %2$s)
```
这里不加顺序显示会出问题吗

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +commands.wereprogress.usage=/wereprogress <0-8> [-1, 0 , 1] or /werequests <0-8> [-1, 0, 1]
```suggestion
commands.wereprogress.usage=/wereprogress <0-8> [-1, 0, 1] 或 /werequests <0-8> [-1, 0, 1]
```

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.config.spawnSilverOre.name=生成银矿
```suggestion
werewolf.config.spawnSilverOre.name=生成银矿石
```

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.config.dimID.name=维度ID
```suggestion
werewolf.config.dimID.name=维度 ID
```

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.config.setLevelCap=为狼人设置最高等级，强烈建议不要设置超过默认值
```suggestion
werewolf.config.setLevelCap=为狼人设置最高等级，强烈建议不要超过默认值
```

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.config.spawnSilverOre=在世界中生成银矿
```suggestion
werewolf.config.spawnSilverOre=在世界中生成银矿石
```

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.config.dimID=设置本模组中的维度的ID
```suggestion
werewolf.config.dimID=设置本模组中的维度的 ID
```

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.message.infected=你被变狼症感染了！
```suggestion
werewolf.message.infected=你染上了变狼症！
```

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.message.night=体内的躁动的兽性支配了你的身体！
```suggestion
werewolf.message.fullmoon=满月升起了！体内躁动的兽性支配了你的身体！
werewolf.message.night=体内躁动的兽性支配了你的身体！
```
删个的

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.message.immune=乌头毒在你周身流淌，你对变狼症免疫了！
```suggestion
werewolf.message.immune=乌头毒在你周身流淌，你免疫变狼症了！
```

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.message.exitmoon=体内的兽性变得无力了！
```suggestion
werewolf.message.exitmoon=体内的兽性躁动不安！
```
虽然和实际触发的条件不符

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.message.sleep=体内的兽性使你无法平静！
```suggestion
werewolf.message.sleep=体内的兽性躁动不安！
```
或此句不改，上方那句和它统一

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.message.wake=你似乎梦到你再遥远的地方捕猎。
```suggestion
werewolf.message.wake=你似乎梦到你在遥远的地方捕猎。
```

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +guide.message.welcome0=欢迎啊，小狼仔。来和我谈谈，你还有很多东西要学。
```suggestion
guide.message.welcome0=欢迎啊，小狼崽。来和我谈谈，你还有很多东西要学。
```
应该是这个`崽`字？

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +guide.message.welcome5=测试野兽形态并尝试疾跑穿过隧道，当心墙壁。
```suggestion
guide.message.welcome5=试试野兽形态，尝试疾跑穿过隧道，当心墙壁。
```

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +guide.message.level8=你已经完成了你的训练，并向我们证明了你的精通；无论你选择控制你体内的兽性还是选择拥抱它，我们都很自豪我们的天赋在你的血液里流淌。
```suggestion
guide.message.level8=你已经完成了你的训练，并向我们证明了你的精通；无论你选择压制你体内的兽性还是选择欣然接受它，你的血液里流淌着我们的礼物，我们永远引以为豪。
```
微调

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.menu.texture.timber=木材质地
```suggestion
werewolf.menu.texture.timber=木质
```

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.menu.sprintClimb.climb=只能在攀爬时按疾跑键
```suggestion
werewolf.menu.sprintClimb.climb=只会在按住疾跑键时攀爬
```

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.menu.sprintClimb.no=不要在攀爬时按疾跑键
```suggestion
werewolf.menu.sprintClimb.no=按住疾跑键时不会攀爬
```

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.menu.sprintClimb.clamp2=向前：向上，向后：向下
```suggestion
werewolf.menu.sprintClimb.clamp2=向前：上方向键，向后：下方向键
```
算是妥协

2023-09-18 16:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/howling-moon/howlingmoon/lang/zh_cn.lang
> +werewolf.menu.ram.key=仅在疾跑时
```suggestion
werewolf.menu.ram.key=仅按住疾跑键时
```

2023-09-30 06:44 UTC, ChuijkYahus commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@wfan-os

2023-10-08 08:07 UTC, closed without merging