添加了 Scape and Run: Parasites Survival Addon (by NoCube) 模组的翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #3099
Opened 2023-03-09 11:13 UTC by wfan-os

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-03-12 01:28 UTC, luoxueyasha reviewed
看了一半，感觉翻译的没原文的味道

2023-03-12 01:28 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advordercheeseburgerplease.descr=制作一个芝士汉堡...有点
```suggestion
advancements.advordercheeseburgerplease.descr=制作一个芝士汉堡……大概吧
```
```suggestion
advancements.advordercheeseburgerplease.descr=应该是制作了一个芝士汉堡
```
再看看这种错译问题

2023-03-12 01:28 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +tile.hardenedfleshslab.name=硬化肉快台阶
```suggestion
tile.hardenedfleshslab.name=硬化肉块台阶
```

2023-03-12 01:28 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +tile.mossyparasitebrick.name=苔藓寄生石砖
```suggestion
tile.mossyparasitebrick.name=生苔的寄生石砖
```
```suggestion
tile.mossyparasitebrick.name=寄生苔石砖
```
![image](https://user-images.githubusercontent.com/38830216/224519012-b404b072-27bd-4588-9736-e1e3f8cb8cef.png)
![image](https://user-images.githubusercontent.com/38830216/224519013-02d1eb33-05e7-4d8a-839b-dd71f9b5d688.png)

https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96

2023-03-12 01:28 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advabominabledinner.descr=速食烤块
和line 79的同一原文不对应

2023-03-12 01:28 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advbutcherbakerundertaker.title=屠夫、面包师、送葬者
https://en.wikipedia.org/wiki/Rub-a-dub-dub

2023-03-12 03:35 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advbutcherbakerundertaker.title=屠夫、面包师、送葬者
可是我基本找不到这首歌的中文翻译，所以这该怎么翻译呢？还是干脆不要翻译
唯一找到的中文翻译：
（歌词）The butcher, the baker, the candlestick maker
（中文翻译）肉铺老板，面包店老板，蜡烛店老板
如果是按照这样来翻译的话，那就是：
肉铺老板，面包店老板，殡仪店老板

主要是国内这首歌流传度根本不高，也找不到类似的

2023-03-12 06:02 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advbutcherbakerundertaker.title=屠夫、面包师、送葬者
其它的我再次看了一遍，已经更新好了

2023-03-12 06:13 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advbutcherbakerundertaker.title=屠夫、面包师、送葬者
然后关于第28行的翻译：
Left for bread
我给翻译成了“面包之路”
这是因为有个很著名的叫 Left for dead （求生之路），我很怀疑作者在这里玩了这个梗
考虑到这一点，我就翻译成面包之路了

2023-03-12 07:12 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advbutcherbakerundertaker.title=屠夫、面包师、送葬者
[暴牙震颤者](https://hs.fbigame.com/?mini=&collectible=1&search=%E6%9A%B4%E7%89%99%E9%9C%87%E9%A2%A4%E8%80%85)
想不到吧，是暴雪的亡语

2023-03-12 07:16 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advbutcherbakerundertaker.title=屠夫、面包师、送葬者
从没玩过炉石，根本想不到，也根本猜不到。。。

2023-03-12 07:19 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advbutcherbakerundertaker.title=屠夫、面包师、送葬者
好的，找你给的翻译改好了

2023-03-12 08:01 UTC, luoxueyasha reviewed
剩下的不想看了，再好好品品原文，查查出典吧

2023-03-12 08:01 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advsliceanddice.title=骰子与砍杀
```suggestion
advancements.advsliceanddice.title=大卸八块
```
啊？

2023-03-12 08:04 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advbutcherbakerundertaker.title=暴牙震颤者
？
我让你看的是这张卡的风味描述里的翻译，不是这个卡名

2023-03-12 08:43 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +block.nocubessrpsurvival.veinstairs=寄生草脉楼梯
但是根据mcmod上给出的官方翻译，srparasite模组原版的一种物品就翻译成“草脉”或“寄染草脉”（Infested Veins），而这里原文是 Parasitic Veins，所以自然就应当翻译成“寄生草脉”了

2023-03-12 08:44 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advbonecrusher.title=碎骨机
这个我真不知道啊，我也没怎么看过变形金刚，话说你们都是怎么找这些梗出处的？我用词典，谷歌，百度搜都是什么“碎骨机”

2023-03-12 08:46 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +item.toxicstew.name=毒肺汤
这里是因为我看合成表要用到“Toxic Lung”，也就是“有毒肺脏”（根据mcmod上的官方翻译），所以我就把这个翻译成“毒肺汤”了。
所以这里应该是用“毒肺汤”，还是“毒汤”，还是“有毒的汤”呢？

2023-03-12 08:47 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advabominabledinner.descr=糟糕的晚餐
这里是我的问题，条目有点多眼花了

2023-03-12 08:47 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advinsatiablehunger.descr=制作吞噬者胸甲并戴上头盔以抵消饥饿buff
ok，我以为buff这个词够正式了…

2023-03-12 08:50 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +item.pestbread.name=虫骨面包
这里是mcmod上搜索这个物品，我发现已经有人给出了“虫骨面包”这个翻译了。再加上这个面包用到的是用寄生虫部件制作的骨粉做的（用骨粉做的面包），那么自然就应该翻译成“虫骨面包”了。
不然，若按照原文 Pest Bread 翻译成“害虫面包”，“寄生虫面包”，总感觉太奇怪了；如果翻译成“虫肉面包”，那也与合成方法不一致。

2023-03-12 08:52 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +tile.infestedstonebrickcracked.name=感染的裂石砖
这个跟蠹虫没半毛钱关系，就是英文名一样的，按照这个模组就应该这么翻译，因为寄生虫具有感染其它原版普通方块的能力。

2023-03-12 08:53 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advmediumrare.title=中等稀有
嗷嗷嗷感谢，不知道这个有特定说法

2023-03-12 08:54 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advtasteslikechicken.title=它尝齐来像鸡的味道
又是梗是吧 X_X

2023-03-12 08:54 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advtheygrowinside.title=他们在里面生长
ok

2023-03-12 08:55 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advinsatiablehunger.title=无法满足的饥饿
确实，我选择“饥不可遏”吧，这个更文艺些

2023-03-12 08:56 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advsliceanddice.title=骰子与砍杀
这个原文 Slice and Dice，我搜到有个游戏就叫“骰子与砍杀”，我不知道这是不是在玩梗…

2023-03-12 09:11 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advbonecrusher.title=碎骨机
不要带`翻译`两个字去搜内容，不要开浏览器页面翻译
一旦看到某些东西可疑就要搜一下

2023-03-12 09:12 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +block.nocubessrpsurvival.veinstairs=寄生草脉楼梯
也行，标记为resolved吧

2023-03-12 09:12 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +item.toxicstew.name=毒肺汤
都行，建议是`毒汤`

2023-03-12 09:13 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +item.pestbread.name=虫骨面包
也行吧

2023-03-12 09:15 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advsliceanddice.title=骰子与砍杀
应该不是玩梗，[slice and dice](https://www.oxfordlearnersdictionaries.com/definition/english/slice_2#slice_idmg_2)是俚语

2023-03-12 09:17 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advbutcherbakerundertaker.title=屠夫、面包师、送葬者
![image](https://user-images.githubusercontent.com/38830216/224535586-94e16bcd-8174-4b3b-9e92-800ef013e02c.png)
我让你看的是这张卡的风味描述里的翻译，不是这个卡名

2023-03-12 09:20 UTC, luoxueyasha commented
顺带一提你提交的几个pr的标题格式都不太对，改一下？

2023-03-12 10:47 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advbutcherbakerundertaker.title=屠夫、面包师、送葬者
这个有点难翻译，因为原文是 Butcher, Baker and Undertaker
如果要按照卡里面的style来翻译的话，那就得翻译成3个2字词语
可问题是，Butcher尚可以翻译成“屠夫”或者“肉店”，Undertaker可以翻译成“送葬”，可是Baker该怎么翻译？Baker我查词典只能翻译成”面包师“、”糕点师“或者”面包房“，没办法翻译成2字词语。
可如果翻译成：屠夫、面包师和送葬的话，那感觉又不怎么朗朗上口了。

2023-03-12 10:48 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advbonecrusher.title=碎骨机
好的，翻译成”碎骨魔“了

2023-03-12 10:49 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +item.toxicstew.name=毒肺汤
好的，改为”毒汤“了

2023-03-12 11:08 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +tile.infestedstonebrickcracked.name=感染的裂石砖
这里是翻译成”寄染的裂石砖“、”被寄生的裂石砖“还是”被感染的裂石砖“呢？
个人觉得都可以，但不知道会不会引起歧义，因为原版的那个蠹虫的叫”[被虫蚀的裂纹石砖](https://www.mcmod.cn/item/11039.html)“，个人感觉这三种翻译都不会引起歧义的，因为都与这个不一样。

2023-03-12 11:17 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +tile.crateparasiticlump.name=寄生刺突箱
修正了

2023-03-12 13:04 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advthewallofflesh.descr=用漂亮的墙包围你的房子
这里我查了nice有个很生僻的意思是”令人不愉快的“、”坏的“，我觉得这样可能更接近一些
但这里 nice 的意思是不是更接近于 weird, 毕竟血肉做的墙确实挺古怪的

不然，翻译成 ”令人不适的“，你看如何？

2023-03-13 04:50 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advbutcherbakerundertaker.title=屠夫、面包师、送葬者
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/3110#discussion_r1133220704
另一个mod也有讨论

2023-03-13 04:51 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +tile.infestedstonebrickcracked.name=感染的裂石砖
不用改，`感染的`就行

2023-03-13 04:53 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +tile.infestedstonebrickcracked.name=感染的裂石砖
```suggestion
tile.infestedstonebrickcracked.name=感染裂石砖
```
```suggestion
tile.infestedstonebrickcracked.name=被感染的裂石砖
```
不管采取哪种翻译，请保持全文用语一致

2023-03-13 06:12 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advbutcherbakerundertaker.title=暴牙震颤者
```suggestion
advancements.advbutcherbakerundertaker.title=待宰羔羊
```
```suggestion
advancements.advbutcherbakerundertaker.title=割韭菜
```
```suggestion
advancements.advbutcherbakerundertaker.title=人为鱼肉，我为刀俎
```
```suggestion
advancements.advbutcherbakerundertaker.title=送葬大厨
```
```suggestion
advancements.advbutcherbakerundertaker.title=煮豆燃豆萁
```
遇到这种玩文化梗的，最好的方法就是看其他人怎么处理类似的情况

2023-03-18 03:26 UTC, wfan-os commented
有人来看一看吗？

2023-03-19 13:38 UTC, luoxueyasha requested changes
建议优先**自查**而不是让审核擦屁股
有很多问题一搜原文一读翻译就能看出来，为什么不去自己看看呢

2023-03-19 13:38 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advinsatiablehunger.descr=制作吞噬者胸甲并戴上头盔以抵消饥饿效果
这里确定是饥饿效果吗，有其他的food debuffs吗

2023-03-19 13:38 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advmolderedpie.descr=准备一份发霉的馅饼
```suggestion
advancements.advmolderedpie.descr=筹备一份发霉的馅饼
```
```suggestion
advancements.advmolderedpie.descr=制备一份发霉的馅饼
```
`准备餐品`感觉太怪了，而且牛排那里也是把`prepare`翻成了`制作`

2023-03-19 13:38 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +itemGroup.tabnocubessrpsurvivaltab=逃逸寄生体: 生存附属 (by NoCube)
```suggestion
itemGroup.tabnocubessrpsurvivaltab=逃逸寄生体: 生存附属（by NoCube）
```

2023-03-19 13:38 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advparasitesurvivalroot.title=逃逸寄生体: 生存附属 (by NoCube)
```suggestion
advancements.advparasitesurvivalroot.title=逃逸寄生体: 生存附属（by NoCube）
```

2023-03-19 13:38 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advthewallofflesh.descr=用令人不适的墙包围你的房子
问过好多次了，这个进度该在游戏里的获得方式是什么
我需要相关的触发条件、相关的贴图等信息来核对这个句子在原文中的语义

2023-03-19 13:38 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advordercheeseburgerplease.title=点餐？请吃芝士汉堡！
这句话翻译的显然有问题，也找到原meme出处了（https://www.youtube.com/watch?v=SwSmlODXik0 ），但是这个双关让我想不到怎么翻

2023-03-20 02:31 UTC, luoxueyasha requested changes

2023-03-20 02:31 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +tile.plankspurple.name=枯木板
```suggestion
tile.plankspurple.name=枯木木板
```
原库翻译有问题，一会修

2023-03-20 02:31 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +tile.crackedparasitebrick.name=开裂的寄生石砖
```suggestion
tile.crackedparasitebrick.name=裂纹寄生石砖
```

2023-03-20 02:31 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +tile.infestedstonebrickcracked.name=开裂的感染石砖
```suggestion
tile.infestedstonebrickcracked.name=裂纹感染石砖
```

2023-04-05 04:34 UTC, ChuijkYahus commented
* 7+7时限进入第二阶段，请注意查看审核意见

@wfan-os

2023-04-05 04:54 UTC, wfan-os commented
> * 7+7时限进入第二阶段，请注意查看审核意见
> 
> @wfan-os

可luoxueyasha对于很多我在conversation里提出的问题并没有给出答复，这该怎么办呢？
还有，7+7时限是什么意思？

@ChuijkYahus

2023-04-05 05:49 UTC, ChuijkYahus commented
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658

@luoxueyasha 拉来（）

2023-04-05 05:51 UTC, wfan-os commented
@luoxueyasha 能看一下 conversation 吗？我都逐一做了回复了

2023-04-05 05:52 UTC, ChuijkYahus commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advmolderedpie.descr=准备一份发霉的馅饼
难说所有都有回复

2023-04-05 10:05 UTC, luoxueyasha commented
![image](https://user-images.githubusercontent.com/38830216/230049624-03db33bd-f1a5-4f14-bac7-59dc39cca182.png)

2023-04-05 10:11 UTC, wfan-os commented
> ![image](https://user-images.githubusercontent.com/38830216/230049624-03db33bd-f1a5-4f14-bac7-59dc39cca182.png)

![Screenshot 2023-04-05 181044](https://user-images.githubusercontent.com/72018068/230051006-9b433ca4-e4fb-4953-8370-350f97d4c39f.png)
我明明回答了啊

2023-04-05 10:14 UTC, wfan-os commented
@luoxueyasha 

![Screenshot 2023-04-05 181329](https://user-images.githubusercontent.com/72018068/230051552-a67d71a9-cbb0-411e-8aa8-5663c16fb927.png)

我明明在下面回复了你好多东西，为什么你没有收到呢？

2023-04-05 10:15 UTC, luoxueyasha commented
![image](https://user-images.githubusercontent.com/38830216/230051733-08fcb636-93d6-40bd-878c-e6de7c3471f4.png)
![image](https://user-images.githubusercontent.com/38830216/230051786-148c9b48-60a7-4f6a-b0d7-facb91f4373b.png)
我这里并没有收到你的回复，邮件里也没有相关内容
需要一个第三方看一眼（

2023-04-05 10:16 UTC, DrIceTea123 commented
《Pending》

2023-04-05 10:16 UTC, luoxueyasha commented
![image](https://user-images.githubusercontent.com/38830216/230052090-ebabfdd9-7d02-459e-a69f-38db77ea3b1d.png)
https://github.com/orgs/community/discussions/10369

2023-04-05 10:19 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +tile.cratevileshell.name=肮脏壳甲箱
#3128 原文更新

2023-04-05 10:22 UTC, wfan-os commented
@luoxueyasha 

好的，感谢，我已经全部将我的 reviews 给 submit 了

2023-04-05 10:28 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advmolderedpie.descr=准备一份发霉的馅饼
因为汉语里`晚餐准备好了`是来自英语的`Dinner is ready`，并非地道的中文；同时`准备+菜名`在汉语里会引申歧义：
* 指餐品已经在后厨备好了，等待上桌；
* 指餐品已经上齐了，等待食用；
* 指餐品已经打包好了，等待日后拿出来（例如带饭到食堂）

同样是表示`制作完成，等待食用`，可以用`配制一份`、`制作一份`

2023-04-05 10:29 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advthewallofflesh.descr=用令人不适的墙包围你的房子
```suggestion
advancements.advthewallofflesh.descr=你房子的墙真不错啊
```
```suggestion
advancements.advthewallofflesh.descr=你审美真不错啊
```

2023-04-05 10:34 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advordercheeseburgerplease.title=点餐？请吃芝士汉堡！
首先这里只取`Cheeseburger`的意，和它`提醒`的内容完全无关；所以`马冬梅`并不适合，玩家看到了只会一头雾水：你马冬梅和我汉堡有啥关系
由于原梗是法庭笑话，所以我本来想翻译成`一斤鸭梨`的，但是和`马冬梅`一样，鸭梨和汉堡没有任何关联
同时你翻译的也错的太荒唐了，`Order`是法官说的，`Cheeseburger please`是小男孩说的，你这翻译成了一个人自顾自的自顾自呢

2023-04-05 10:39 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advordercheeseburgerplease.title=点餐？请吃芝士汉堡！
这确实，但又要体现出汉堡，又要把原文那种听错了以及对听者心不在焉的讥讽（至少chatGPT给出的这个梗的内涵是这样）给表达出来，这真的太难了。因为中文圈根本就没有任何有关的梗啊

2023-04-05 10:42 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +tile.cratevileshell.name=肮脏壳甲箱
> vile shell 目前的官方译名就是“肮脏壳甲”
对应的模组版本是？

> Crate
`箱`就行，它是不是`箱`和它能不能打开没有必然联系，大量库内的`Crate`也是`箱`
`压缩`有对应的`Compressed`，不要擅自修改

> Parastic Lump
srp内的名称已经更新成了`Grotesque Lump` （#3128 ，1.19.11）
考虑到库内` Parasitic Lump`现有对应译文是不准确的`寄生刺突`，我保留意见

2023-04-05 10:45 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advordercheeseburgerplease.title=点餐？请吃芝士汉堡！
有没有大神能看看这个？实在想不出来什么好点子了，提供点灵感也行！

2023-04-05 10:46 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advordercheeseburgerplease.title=点餐？请吃芝士汉堡！
@ChuijkYahus label:help wanted

2023-04-05 11:00 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +tile.cratevileshell.name=肮脏壳甲箱
肮脏壳甲是寄生虫 1.9.10 以及这之后的所有新版本（截止至2023.4.5，也就是 1.9.10 和 1.9.11 版本）的官方译名。要注意的是，寄生虫在 1.9.9 到 1.9.10 之间进行了一次较大的更新，添加了很多实体和物品，译名也大幅更改了。

2023-04-05 11:02 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advinfestation.descr=将裂兽的碎块同生肉混合在一起，以养殖虫灵
都行
描述虫子用`增殖`更合适

2023-04-05 11:02 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +tile.cratevileshell.name=肮脏壳甲箱
而至于 Grotesque Lump，在 1.9.10 和 1.9.11 都使用这个名字；而本mod里的食物也是用 Grotesque Lump 制作的

PS：要注意的是，这个mod制作的时间比较早，也就是在 1.9.10 发布之前，因此作者那个时候很有可能 Grotesque Lump 还叫 Parasitic Lump

2023-04-05 11:07 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advinfestation.descr=将裂兽的碎块同生肉混合在一起，以养殖虫灵
那我还是用养殖吧，因为SRP存在高玩会故意养寄生虫的（为了炫耀实力、好奇、刷怪或者控制寄生点数），对于他们来说，应该就是养殖。

而且这个mod居然吃寄生虫的血肉，显然是比较变态的，另一方面也说明玩家在这个mod里把寄生虫当成了食物。就像养殖家畜一样，应该也是养殖。

PS：现实中也有饲养昆虫用作食物或者药品的，比如就有人会去大批养殖蟑螂，对这个人的事迹的报道所用的词也是“养殖”

2023-04-05 11:15 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +tile.cratevileshell.name=肮脏壳甲箱
那就`寄生肿囊`

另：善用edit，少说废话，我不想上升到人身攻击
![image](https://user-images.githubusercontent.com/38830216/230062703-ffe4bd4e-b0be-49ae-a319-520245152766.png)

顺带帮你缩句了
![image](https://user-images.githubusercontent.com/38830216/230064674-bd9ed873-5724-4162-9341-1a6675187f12.png)

2023-04-05 11:16 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advinfestation.descr=将裂兽的碎块同生肉混合在一起，以养殖虫灵
确定是像原版生物的`养殖`吗

2023-04-05 11:18 UTC, wfan-os commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +tile.cratevileshell.name=肮脏壳甲箱
我这怎么就废话了？？？

2023-04-05 11:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +tile.cratevileshell.name=肮脏壳甲箱
非常抱歉，我的回答引起了您的不愉快。
这里是对您的语言风格被我不恰当地称呼为”废话“而做出的一些解释，希望能帮助到您。
根据[废话 - 维基百科](https://zh.wikipedia.org/wiki/%E5%BB%A2%E8%A9%B1)的”废话的种类“一节：

> [重言句](https://zh.wikipedia.org/wiki/%E9%87%8D%E8%A8%80%E5%8F%A5)或极为基础的事实： 这类话并非没有意义，但在日常交流中没有给予任何有用的信息。例如“您的母亲为一名女性”，由于根据普遍的定义，只有女人才可以生育，因此生出您的母亲，必为女人。另外，像“十进制下1+1=2”亦常被理解为废话，这是由于根据我们对数字和加法的基本了解，而且所有描述都是事实，重复描述并没有产出任何实际意义，所以被归类为废话。

由于前后文中交流对话的双方人员都已经了解了某一特定词语在这种语言环境下的关系，不具有再次叙述或者解释、说明的必要，也没有需要强调所以需要重复，因此认为这些语句是不必要的，不恰当的，以带有攻击性的话语来说，是偏向于”废话“的语义的。

此外，您的叙述中也带有一定程度量的翻译腔问题。根据[维基百科:翻译腔 - 维基百科](https://zh.wikipedia.org/wiki/Wikipedia:%E7%BF%BB%E8%AF%91%E8%85%94)的描述，您似乎更喜欢或者更偏向于使用不符合中文语法或偏离中文语义的短句，并且对这些语言要素进行进一步的不必要的自我阐述。例如：

> 所以，如果是意译的话，个人觉得翻译成“压缩XXX”更合理，不知道你是什么看法？

这句话的语义是，`我觉得意译成”压缩XXX“更好一些`。这句话中出现了维基百科:翻译腔中所叙述的”尽量直白“、”能用短语概括时，尽量用短语概括“、和”……不管怎么样，中文就是不会这么说“等翻译腔问题，也就是不符合汉语的表述模式的问题。这种行为会导致对话者在沟通时难以提取文中的含义，从而降低两者之间进行沟通的效率。尽管，在汉语口语中往往并不会注意这种情况，也不会对这种内容进行指责，但是在一次模组翻译的交接工作中，这种行为往往是不被对方认可的，可能会引起对方的不愉悦。这里并不是对您的语言模式进行攻击，而是提供一种更好的，更快捷的，更优质的交流思路，用来提高对话双方之间的沟通效率。

如果话语困扰到了，十分抱歉。这里会尽量对说话节奏与说话风进行调整以满足。期待您的回复呢。

2023-04-06 00:30 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang
> +advancements.advordercheeseburgerplease.title=点餐？请吃芝士汉堡！
想太多了，就只是个`Cheeseburger`相关的梗
要不是[翻译规范](https://cfpa.site/TransRules/)里特意提了不能玩烂梗，我都想翻译成`老八秘制小汉堡`

```suggestion
advancements.advordercheeseburgerplease.title=三点几了，吔汉堡先啊
```
出自饮茶哥的“三点几了，饮茶先啊”

```suggestion
advancements.advordercheeseburgerplease.title=你会记得你吃过多少个汉堡吗
```
出自JOJO系列

```suggestion
advancements.advordercheeseburgerplease.title=汉堡不能没有芝士，就像……
```
出自《我的1919》中`就像西方不能失去耶路撒冷`一段

```suggestion
advancements.advordercheeseburgerplease.title=大郎，该吃汉堡了
```
出自《水浒传》（应该是99版电视剧）

```suggestion
advancements.advordercheeseburgerplease.title=来人，喂两位公子吃汉堡
```
出自《九品芝麻官》

2023-04-06 03:06 UTC, luoxueyasha approved these changes
你提交的其他几个pr也有生硬翻译的问题，建议转draft并自行修订

2023-04-14 00:29 UTC, luoxueyasha commented
嗯？怎么7+7流程还在运行
拉个 @ChuijkYahus 过来看一圈

2023-04-14 10:40 UTC, ChuijkYahus commented
/add-mapping scape-and-run-parasites-survival-addon-by-nocube 693318

2023-04-14 10:41 UTC, ChuijkYahus commented
居然是乱序（）

2023-04-14 10:42 UTC, ChuijkYahus commented
/sort-keys projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/en_us.lang
/sort-keys projects/1.12.2/assets/scape-and-run-parasites-survival-addon-by-nocube/nocubessrpsurvival/lang/zh_cn.lang

2023-04-29 21:04 UTC, closed without merging

2023-09-07 13:41 UTC, wfan-os commented
hello