Apples-plus翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3102
Opened 2023-03-11 02:06 UTC by liujia1306

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-03-11 02:46 UTC, mamaruo commented
批量替换注意把区分大小写打开
> 英文语言文件有 2 个 Key 多于中文语言文件。例如：
行 143-tile.rubyore.name
行 145-tile.bedrockore.name
中文语言文件有 2 个 Key 多于英文语言文件。例如：
行 143-tile.ruby矿.name
行 145-tile.bedrock矿.name

2023-03-11 03:28 UTC, mamaruo requested changes

2023-03-11 03:28 UTC, mamaruo commented on projects/1.12.2/assets/apples-plus/applesplus/lang/zh_cn.lang
> +item.itemapplenog.name=苹果诺格酒
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |

原文：**Apple Nog**
```suggestion
item.itemapplenog.name=苹果蛋奶酒
```
[蛋奶酒 - 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/%E8%9B%8B%E5%A5%B6%E9%85%92)
[蛋奶酒（圣诞节传统饮品）_百度百科](https://baike.baidu.com/item/%E8%9B%8B%E5%A5%B6%E9%85%92/5719421)

2023-03-11 03:28 UTC, mamaruo commented on projects/1.12.2/assets/apples-plus/applesplus/lang/zh_cn.lang
> +item.itemapplecookie.name=饼干苹果
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   原版术语   |

原文：**Cookie Apple**
```suggestion
item.itemapplecookie.name=曲奇苹果
```

2023-03-11 03:28 UTC, mamaruo commented on projects/1.12.2/assets/apples-plus/applesplus/lang/zh_cn.lang
> +item.itemapplebone.name=骨苹果
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   原版术语   |

原文：**Bone Apple**
```suggestion
item.itemapplebone.name=骨头苹果
```

2023-03-11 03:28 UTC, mamaruo commented on projects/1.12.2/assets/apples-plus/applesplus/lang/zh_cn.lang
> +item.itemapplegravel.name=砂砾苹果
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |

原文：**Gravel Apple**
```suggestion
item.itemapplegravel.name=沙砾苹果
```

2023-03-11 03:28 UTC, mamaruo commented on projects/1.12.2/assets/apples-plus/applesplus/lang/zh_cn.lang
> +item.itemapplewood.name=木苹果
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |

原文：**Wood Apple**
```suggestion
item.itemapplewood.name=木头苹果
```

2023-03-18 06:22 UTC, ChuijkYahus commented
* 7+7进入第一阶段，请注意查看审核

@liujia1306

2023-03-26 04:57 UTC, mamaruo submitted a review, later dismissed

2023-03-26 06:29 UTC, ChuijkYahus commented
一击脱离啊……

2023-03-26 07:46 UTC, ChuijkYahus requested changes
查了源码
大概改了一下

2023-03-26 07:46 UTC, ChuijkYahus commented on projects/1.12.2/assets/apples-plus/applesplus/lang/zh_cn.lang
> +item.itemapplesugarcane.name=蔗糖拐杖糖苹果
```suggestion
item.itemapplesugarcane.name=甘蔗苹果
```
已查证

2023-03-26 07:46 UTC, ChuijkYahus commented on projects/1.12.2/assets/apples-plus/applesplus/lang/zh_cn.lang
> +item.itemapplemilk.name=奶苹果
```suggestion
item.itemapplemilk.name=牛奶苹果
```
1122应该还没改，不过随意了

2023-03-26 07:46 UTC, ChuijkYahus commented on projects/1.12.2/assets/apples-plus/applesplus/lang/zh_cn.lang
> +item.itemapplebrick.name=砖块苹果
```suggestion
item.itemapplebrick.name=红砖苹果
```

2023-03-26 07:46 UTC, ChuijkYahus commented on projects/1.12.2/assets/apples-plus/applesplus/lang/zh_cn.lang
> +item.itemapplenetherbrick.name=地狱砖块苹果
```suggestion
item.itemapplenetherbrick.name=地狱砖苹果
```

2023-04-17 13:17 UTC, ChuijkYahus commented
这个还合吗

2023-04-22 14:07 UTC, mamaruo approved these changes

2023-04-24 14:30 UTC, ChuijkYahus approved these changes

2023-04-24 14:31 UTC, merged