Industrial Renewal Port 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3103
Opened 2023-03-11 15:28 UTC by HehCrashes

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-03-12 01:53 UTC, mamaruo requested changes

2023-03-12 01:53 UTC, mamaruo commented on projects/1.16/assets/industrial-renewal-port/industrialrenewal/lang/zh_cn.json
> +  "item.industrialrenewal.cartridge_half" : "红石配线盒½",
看过游戏内表现吗

2023-03-12 01:53 UTC, mamaruo commented on projects/1.16/assets/industrial-renewal-port/industrialrenewal/lang/zh_cn.json
> +  "item.industrialrenewal.steam_locomotive" : "蒸汽机车(未完成)",
半角符号，请检查整个文件

2023-03-12 01:53 UTC, mamaruo commented on projects/1.16/assets/industrial-renewal-port/industrialrenewal/lang/zh_cn.json
> +  "item.industrialrenewal.record_royal_entrance.des0" : "Royal Entrance，由Visager作曲",
```suggestion
  "item.industrialrenewal.record_royal_entrance" : "音乐唱片",
  "item.industrialrenewal.record_royal_entrance.des0" : "Royal Entrance by Visager",
```
原版翻译格式

2023-03-12 03:59 UTC, HehCrashes commented on projects/1.16/assets/industrial-renewal-port/industrialrenewal/lang/zh_cn.json
> +  "item.industrialrenewal.cartridge_half" : "红石配线盒½",
红石配线盒还没实装
½可以正常显示
![2023-03-12_11 57 10](https://user-images.githubusercontent.com/85434067/224523515-71cd0506-5cea-4e79-83ab-6e847296d11e.png)

2023-07-08 09:50 UTC, mamaruo approved these changes
抱歉

2023-07-10 05:25 UTC, merged