热量与气候1.19.2汉化提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3105
Opened 2023-03-12 01:16 UTC by komeiji-koyomi

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-03-12 02:38 UTC, luoxueyasha reviewed
我来挑刺咯！（

2023-03-12 02:38 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "item.dcs_climate.food.pack_cream":"奶油盒",
```suggestion
  "item.dcs_climate.food.pack_cream":"稀奶油盒",
```
```suggestion
  "item.dcs_climate.food.pack_cream":"动物奶油盒",
```
（烘培用的）奶油一般分为两种：`稀奶油`（`鲜奶油`、`动物奶油`）和`淡奶油`（`植物奶油`），也有用`鲜奶油`统称两种奶油的。
`动物奶油`对应日文`生クリーム`，`植物奶油`对应日文`ホイップクリーム`。

2023-03-12 02:38 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "item.dcs_climate.food.bread_square_raw":"方面团",
```suggestion
  "item.dcs_climate.food.bread_square_raw":"吐司面团",
```
建议做一下对应关系

2023-03-12 02:38 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "item.dcs_climate.food.plate_meat_raw":"生肉排",
```suggestion
  "item.dcs_climate.food.plate_meat_raw":"生切肉排",
```
原文`生のカットステーキプレート`，至少要把`カット`翻译出来吧

2023-03-12 02:38 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "item.dcs_climate.food.salad_melon":"西瓜沙拉",
```suggestion
  "item.dcs_climate.food.salad_melon":"西瓜番茄沙拉",
```
原文`スイカとトマトのサラダ`<s>什么黑暗料理</s>
但是居然真的是意式菜（[菜谱](https://cooking.nytimes.com/recipes/1014851-tomato-and-watermelon-salad)）

2023-03-12 02:38 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "block.dcs_climate.main.dustblock_tool_steel":"工具钢粉块",
同上，ja_jp没有对应行

2023-03-12 02:38 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "block.dcs_climate.food.sapling_beech_rare":"白橡木树苗",
```suggestion
  "block.dcs_climate.food.sapling_beech_rare":"白橡树苗",
```
```suggestion
  "block.dcs_climate.food.sapling_beech_rare":"白橡树树苗",
```
见原版深色橡木/深色橡树的处理，不过群里讨论过了所以`白橡`作为种名，或者`白橡树`作为种名都可以

2023-03-12 02:38 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "block.dcs_climate.food.sapling_camellia_rare":"茶树苗",
```suggestion
  "block.dcs_climate.food.sapling_camellia_rare":"茶树树苗",
```

2023-03-12 02:38 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "entity.dcs_climate.plate_big_steak":"烤蒜香牛排",
```suggestion
  "entity.dcs_climate.plate_big_steak":"大块烤牛排",
```
原文是`大きなステーキプレート`，作者误植？

2023-03-12 02:38 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "entity.dcs_climate.stick_beef":"牛肉串",
```suggestion
  "entity.dcs_climate.stick_beef":"烤肉串",
```
①两种肉串的原文均为`串焼き`，不存在差别
②上文是`烤牛肉串` `烤猪肉串`等，如果需要做区分请和上文一致

除此之外这里键顺序也和日文不一致，建议实际去游戏里跑一跑（因为下文存在键名不一致的问题，顺手提出来了

2023-03-12 02:38 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "dcs.climate.tip.checker":"可以检测右击坐标的气候",
```suggestion
  "dcs.climate.tip.checker":"右击以检测该点的气候",
```
随你了（
此外日文键名是`dcs.tip.checker`

2023-03-12 02:38 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "dcs.name.shift":"按下左shift：展开工具提示",
这里日语键名是`dcs.tip.shift`
还有上方的`右击以`和`按下某键：`，统一一下吧

2023-03-12 02:38 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "dcs.smelting":"气候冶炼",
这些文本是显示在哪些位置的？

2023-03-12 02:38 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "death.attack.dcs_machine":"%1$s被卷进了机器",
原文`%1$sは労働災害に遭った。ご安全に!`
……能翻译的比较日式地狱笑话吗？

2023-03-12 02:38 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "dcs.gui.jei.smelting_tip3":"对地上的掉落物生效",
```suggestion
  "dcs.gui.jei.smelting_tip3":"对掉落物生效",
```
`掉落物`包含`在地上`这层含义吧？

2023-03-12 02:38 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "dcs.gui.jei.crop_tip2":"“野生”等级的作物在施肥耕地上成长时有概率变异",
```suggestion
  "dcs.gui.jei.crop_tip2":"“野生”等级的作物在施肥耕地上成长时，有概率变异成更高级的作物",
```
原文`WILD作物は、施肥された耕地の上で育てると、Tierの高い作物に変異する可能性があります。`

2023-03-12 02:38 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "dcs.gui.jei.tree_flower":"开花季节",
```suggestion
  "dcs.gui.jei.tree_flower":"花期",
```
https://www.termonline.cn/word/1356267339632431106/1#s1

2023-03-12 02:38 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "dcs.gui.jei.tree_crop":"收获季节",
```suggestion
  "dcs.gui.jei.tree_crop":"收获期",
```
```suggestion
  "dcs.gui.jei.tree_crop":"收割期",
```
没找到对应的专业名词

2023-03-12 02:38 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "dcs.enum.arctic":"极点",
```suggestion
  "dcs.enum.arctic":"极区",
```
```suggestion
  "dcs.enum.arctic":"寒带",
```

2023-03-12 02:38 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "dcs.enum.heat.kiln":"灼热",
```suggestion
  "dcs.enum.heat.kiln":"灼烧",
```
上方有`炎热`了，不想重字

2023-03-12 02:46 UTC, komeiji-koyomi commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "item.dcs_climate.food.food_oat":"燕麦",
因为这玩意能做“麦片”（）
所以连夜删掉了所有的“粉”字

2023-03-12 02:48 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "item.dcs_climate.food.pack_cream":"奶油盒",
顺带一提安利一下[这位](https://space.bilibili.com/1976715)的视频，里面把西点相关的知识讲的很详细（虽然也不是啦

2023-03-12 09:19 UTC, luoxueyasha approved these changes

2023-03-19 10:47 UTC, luoxueyasha reviewed
基本没啥问题了

2023-03-19 10:47 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "item.dcs_climate.food.crop_erica_wild":"帚石南花",
能看一下游戏贴图吗？

2023-03-19 10:47 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "block.dcs_climate.food.sapling_erica_wild":"帚石南树苗",
这个也是，看一眼贴图

2023-03-23 01:28 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "item.dcs_climate.food.crop_erica_wild":"帚石南花",
resolved

2023-03-23 01:29 UTC, luoxueyasha approved these changes
感觉没问题了，at青羽

2023-04-13 12:22 UTC, luoxueyasha submitted a review, later dismissed
看不出什么问题了

2023-04-18 09:06 UTC, luoxueyasha commented
![image](https://user-images.githubusercontent.com/38830216/232729335-00d1a802-b69b-4481-99fc-a18e554bc4b9.png)
不是， 你ping我没用啊，你ping个有写权限的审核吧（

2023-05-19 03:03 UTC, luoxueyasha requested changes
部分问题仅指出一处

2023-05-19 03:03 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "advancements.dcs_climate.main.wood.desc":"要致富，先撸树，木头是一切的开端",
```suggestion
  "advancements.dcs_climate.main.wood.desc":"要致富，先撸树",
```
```suggestion
  "advancements.dcs_climate.main.wood.desc":"木头是一切的开端",
```
加私活可以，但是语义重复了

2023-05-19 03:03 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "advancements.dcs_climate.main.table.title":"这又是？工作台！",
```suggestion
  "advancements.dcs_climate.main.table.title":"这是？工作台！",
```
要考虑到没玩过mc的玩家

2023-05-19 03:03 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "advancements.dcs_climate.main.table.desc":"使用四个木板合成工作台，就像你早就熟练的那样",
```suggestion
  "advancements.dcs_climate.main.table.desc":"打开背包，用四个木板合成工作台",
```

2023-05-20 03:49 UTC, komeiji-koyomi commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "death.attack.dcs_water":"%1$s被淹成了泡菜",
这里要在设置里打开气候相关伤害然后处于非水下的“水下”湿度才能触发
就……挺要命的

2023-05-20 03:51 UTC, komeiji-koyomi commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "item.dcs_climate.main.chain_mail_bronze":"合金护腿",
这里我也很纠结
模组内同时存在两个配方（青铜、黄铜），盔甲颜色介于两者之间

2023-05-20 04:20 UTC, komeiji-koyomi commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/en_gb.json
> +{
嘶……比较麻烦，这文件不好删

2023-05-20 04:22 UTC, komeiji-koyomi commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "dcs.tip.ring_s.name.blue":"抗寒",
免疫所有低温效果，是抗寒

2023-05-20 04:22 UTC, komeiji-koyomi commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "dcs.tip.ring_s.name.red":"抗热",
嗯……就是抗火，原名抗热（）

2023-05-20 04:24 UTC, komeiji-koyomi commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "dcs.tip.ring_g.name.green":"占卜",
直接“占矿”吧（）

2023-05-23 03:44 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "item.dcs_climate.main.chain_mail_bronze":"合金护腿",
不，这句是问题是它原文是chainmail（锁链）的胸甲，而不是合金护腿
需要截图

2023-05-23 03:45 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "dcs.tip.ring_g.name.green":"占卜",
可

2023-05-23 03:46 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "death.attack.dcs_water":"%1$s被淹成了泡菜",
行吧，虽然偏离原文了但合理

2023-07-23 00:13 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/en_gb.json
> +{
可以解释一下为什么不好删吗

2023-07-23 10:28 UTC, komeiji-koyomi commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/en_gb.json
> +{
不知道为什么我的视角没法看到删除按键，可能需要管理员来帮帮删掉它

2023-07-23 10:38 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/en_gb.json
> +{
管理员也没法删，因为是在你自己的仓库的fork里开的……
你试试github.dev？

2023-07-23 10:38 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "item.dcs_climate.main.chain_mail_bronze":"合金护腿",
需要截图（催促

2023-07-23 10:55 UTC, komeiji-koyomi commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/en_gb.json
> +{
嘶……

2023-07-23 10:55 UTC, komeiji-koyomi commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "item.dcs_climate.main.chain_mail_bronze":"合金护腿",
马上马上（
这台电脑上没现成的mod，等我一会

2023-07-23 11:10 UTC, komeiji-koyomi commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "item.dcs_climate.main.chain_mail_bronze":"合金护腿",
看了一下配方和材质，是错译，马上改

2023-07-30 07:23 UTC, luoxueyasha requested changes

2023-07-30 07:23 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "block.dcs_climate.build.chandelier_fluorite":"氟石吊灯",
确定是`氟石`而非`萤石`吗

2023-07-30 10:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3105) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3105) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3105) it.</sub>

2023-07-31 01:13 UTC, komeiji-koyomi commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "block.dcs_climate.build.chandelier_fluorite":"氟石吊灯",
确定，此处是模组新添加的矿石，为了与原版荧石作出读音上的区分选用了“氟石”的称呼

2023-07-31 08:41 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "block.dcs_climate.build.chandelier_fluorite":"氟石吊灯",
那L62，L504的`萤石`呢？
如果没记错的话1.12.2应该也有类似问题，建议全文通查

2023-08-10 07:12 UTC, komeiji-koyomi commented
嗯……对jei的标题部分进行了一些修改
并不遵循原文，不过个人认为应该可以让游戏内观感更好一点

2023-08-10 07:18 UTC, komeiji-koyomi commented
此处保留一条疑问：在季节部分有两条未被使用的名称，我暂时写为了“温带”“寒带”，但实际测试时它们并不会在任何地方被成功判定。
如果我猜测正确的话它们有可能本来是作为地狱与末地的特殊季节情况，不过不能确定，暂时维持原样

2023-08-13 00:39 UTC, luoxueyasha approved these changes
好像没啥问题

2023-08-13 00:40 UTC, luoxueyasha requested changes

2023-08-13 00:40 UTC, luoxueyasha commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "item.dcs_climate.main.gem_fluorite":"萤石",
`氟石`还是`萤石`？
**请全文通查**

2023-08-21 07:26 UTC, komeiji-koyomi commented on projects/1.19/assets/heat-and-climate/dcs_climate/lang/zh_cn.json
> +  "item.dcs_climate.main.gem_fluorite":"萤石",
已修改

2023-08-22 05:00 UTC, luoxueyasha approved these changes
我觉得可了
你自己再和1.12的对一下术语

2023-08-28 17:06 UTC, merged