Amethyst Tools Mod 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3116
Opened 2023-03-13 01:37 UTC by Huantanhua

- [ ] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-03-13 01:44 UTC, Huantanhua commented
不知道为什么前两个总是拉取之后出来，请问我该如何删除？

2023-03-13 06:24 UTC, luoxueyasha commented
建议在你fork的仓库里进行如下操作：
①切换到main branch，并检查是否与cfpa的主仓库完全同步；
![image](https://user-images.githubusercontent.com/38830216/224622662-baecbd97-4f56-4a30-8fbc-dd0c8b7524ed.png)
②以你的main branch为source，新建一条branch：
![image](https://user-images.githubusercontent.com/38830216/224622828-07dc2946-1c98-43dc-98c1-f9feee97ea9f.png)
③在新的branch里进行对应的commit操作。

好像你提的几个pr都有butchercraft的提交记录，可以顺带检查一下你的main branch的同步状态。
删除的话应该需要本地的git命令行了，网页端似乎没有回滚commit的入口（至少我没发现有

2023-03-13 08:31 UTC, Huantanhua commented
git命令在哪里打呢请问
&nbsp;


花鳥風月
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月13日(星期一) 下午2:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CFPAOrg/Minecraft-Mod-Language-Package] Amethyst Tools Mod 翻译提交 (PR #3116)





 
建议在你fork的仓库里进行如下操作：
 ①切换到main branch，并检查是否与cfpa的主仓库完全同步；
 
 ②以你的main branch为source，新建一条branch：
 
 ③在新的branch里进行对应的commit操作。
 
好像你提的几个pr都有butchercraft的提交记录，可以顺带检查一下你的main branch的同步状态。
 删除的话应该需要本地的git命令行了，网页端似乎没有回滚commit的入口（至少我没发现有
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-03-13 15:36 UTC, mamaruo commented
建议给出当前操作环境以便我们给出解决方案，在以下项中选择：在线VSCode（github.dev），本地VSCode，GitHub Desktop，纯网页GitHub。在线VSCode的解决办法已在这里给出：https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/3111#issuecomment-1465227772

另外我注意到你没有阅读[CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)，请阅读。
![image](https://user-images.githubusercontent.com/37480168/224750725-feaf3b17-dcdf-4ce5-bdc8-6af01fc4458c.png)

2023-03-17 10:20 UTC, ChuijkYahus commented on projects/1.18/assets/amethyst-tools-mod/amethysttoolsmod/lang/zh_cn.json
> +	"item.amethysttoolsmod.amethyst_dust": "紫水晶粉尘",
```suggestion
	"item.amethysttoolsmod.amethyst_dust": "紫水晶粉",
```
倒是一般`粉`就OK的

2023-03-17 10:20 UTC, ChuijkYahus commented on projects/1.18/assets/amethyst-tools-mod/amethysttoolsmod/lang/zh_cn.json
> +	"item.amethysttoolsmod.amethyst_tipped_arrow.effect.levitation": "漂浮紫晶箭",
```suggestion
	"item.amethysttoolsmod.amethyst_tipped_arrow.effect.levitation": "飘浮紫晶箭",
```

2023-03-17 10:20 UTC, ChuijkYahus commented on projects/1.19/assets/amethyst-tools-mod/amethysttoolsmod/lang/zh_cn.json
> +	"item.amethysttoolsmod.amethyst_tipped_arrow.effect.levitation": "漂浮紫晶箭",
```suggestion
	"item.amethysttoolsmod.amethyst_tipped_arrow.effect.levitation": "飘浮紫晶箭",
```

2023-03-17 10:20 UTC, ChuijkYahus commented on projects/1.19/assets/amethyst-tools-mod/amethysttoolsmod/lang/zh_cn.json
> +	"item.amethysttoolsmod.amethyst_dust": "紫水晶粉尘",
```suggestion
	"item.amethysttoolsmod.amethyst_dust": "紫水晶粉",
```

2023-03-19 14:18 UTC, ChuijkYahus commented on projects/1.18/assets/amethyst-tools-mod/amethysttoolsmod/lang/zh_cn.json
> +	"item.amethysttoolsmod.amethyst_tipped_arrow.effect.levitation": "漂浮紫晶箭",
这改完了吗

2023-03-19 14:18 UTC, ChuijkYahus commented on projects/1.18/assets/amethyst-tools-mod/amethysttoolsmod/lang/zh_cn.json
> +	"item.amethysttoolsmod.amethyst_dust": "紫水晶粉尘",
这里决定不要改吗

2023-03-31 20:12 UTC, ChuijkYahus requested changes

2023-03-31 20:12 UTC, ChuijkYahus commented on projects/1.19/assets/amethyst-tools-mod/amethysttoolsmod/lang/zh_cn.json
> +	"item.amethysttoolsmod.amethyst_dust": "紫水晶粉尘",
这里确定不改吗

2023-03-31 20:15 UTC, ChuijkYahus commented
#3055 已入库
抱歉未能及时通知

2023-04-01 07:04 UTC, ChuijkYahus commented
由于已有同模组pr入库
此pr不再接受

2023-04-02 10:10 UTC, closed without merging