Chipped 1.19.2 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3120
Opened 2023-03-16 17:30 UTC by ChuijkYahus

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-03-26 07:45 UTC, DrIceTea123 commented
这可真是个大工程……我在excel里把整个pr排查了一遍，花了三天，做了译名对应表，做了格式替换，总算是查完了
一点一点来，先放一个`译名错误-与其他相关行格式不同-建议修改`的表格：
<img width="887" alt="无标题" src="https://user-images.githubusercontent.com/111784151/227762310-1069ee2e-09c5-44bf-b90b-5cb6f088a833.png">

2023-03-26 10:33 UTC, ChuijkYahus commented
> 这可真是个大工程……我在excel里把整个pr排查了一遍，花了三天，做了译名对应表，做了格式替换，总算是查完了 一点一点来，先放一个`译名错误-与其他相关行格式不同-建议修改`的表格：

辛苦了，目前还剩`石头`和`平滑石头`没有更改

2023-03-27 04:10 UTC, DrIceTea123 commented on projects/1.19/assets/chipped/chipped/lang/zh_cn.json
> +  "block.chipped.inscribed_crying_obsidian": "纂刻哭泣的黑曜石",
根据其他行对于Inscribed的翻译，这里应该是`篆刻`
```suggestion
  "block.chipped.inscribed_crying_obsidian": "篆刻哭泣的黑曜石",
```

2023-03-27 04:49 UTC, ChuijkYahus commented on projects/1.19/assets/chipped/chipped/lang/zh_cn.json
> +  "block.chipped.inscribed_crying_obsidian": "纂刻哭泣的黑曜石",
应该是没有剩余的了

2023-03-27 05:11 UTC, DrIceTea123 commented
然后是语序的小问题：
<img width="1111" alt="无标题" src="https://user-images.githubusercontent.com/111784151/227845753-31da75a4-d754-403e-a737-7a27279d66d4.png">

还有顺便提一下，可能是原文问题的几行：
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/DrIceTea/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/DrIceTea/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:.75in .7in .75in .7in;
	mso-header-margin:.3in;
	mso-footer-margin:.3in;}
.font5
	{color:windowtext;
	font-size:9.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:等线;
	mso-generic-font-family:auto;
	mso-font-charset:134;}
tr
	{mso-height-source:auto;
	mso-ruby-visibility:none;}
col
	{mso-width-source:auto;
	mso-ruby-visibility:none;}
br
	{mso-data-placement:same-cell;}
td
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:等线;
	mso-generic-font-family:auto;
	mso-font-charset:134;
	mso-number-format:General;
	text-align:general;
	vertical-align:middle;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
ruby
	{ruby-align:left;}
rt
	{color:windowtext;
	font-size:9.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:等线;
	mso-generic-font-family:auto;
	mso-font-charset:134;
	mso-char-type:none;
	display:none;}
-->

</head>

<body link="#0563C1" vlink="#954F72">



行数 | 键名 | 英文 | 估计格式 | pr内译文
-- | -- | -- | -- | --
210 | block.chipped.blank_lodestone_side | Blank Lodestone Side | Blank Lodestone Carving | 空白式刻徽磁石
2659 | block.chipped.lead_woven_glass | Lead Woven Glass | Woven Leaded Glass | 编织纹衬铅玻璃
2681 | block.chipped.lead_woven_glass_pane | Lead Woven Glass Pane | Woven Leaded Glass Pane | 编织纹衬铅玻璃板



</body>

</html>
第一个是Side的问题，后面两个是Lead的问题

2023-03-27 08:29 UTC, ChuijkYahus commented
苦力怕和蜘蛛的两种主要是从材质方面考量的，苦力怕徽的材质独步天下（），蜘蛛雕徽的材质风格和其他雕徽是一致的
![2023-03-27_16 25 48](https://user-images.githubusercontent.com/94828194/227884825-83faed08-8fcf-41c7-abe3-634e71bdfdd6.png)
左：苦力怕徽
中：空白式雕徽，欢愉雕徽，疑惑雕徽（征求更好翻译），不悦雕徽，悲伤雕徽，蜘蛛雕徽
右：空白式刻徽，符文刻徽

---
小型砖和微型砖算是和create等模组的翻译方式以及其自身的小型瓦做出的让步

---
Slabs那个可见此
![2023-03-27_16 21 34](https://user-images.githubusercontent.com/94828194/227883819-f3905548-dc09-4537-b7fd-9a76d92f23f9.png)
左为密层xx砖，右为细层xx砖

---
当然这些如果觉得不妥都可以改（）

2023-03-27 08:34 UTC, ChuijkYahus commented
柱拱形的话，一开始是为避免出现`玻璃板柱`和`玻璃柱板`这两种才如此处理的

2023-03-27 08:52 UTC, DrIceTea123 commented
那就按实际表现译吧
`柱拱形`有图吗

2023-03-27 08:56 UTC, ChuijkYahus commented
Chipped各合成台对应方块列表（只是想做）：

**学者工作台**：
紫水晶块、煤炭块、哭泣的黑曜石、磁石、青金石块、钻石块、铁块、金块、绿宝石块、下界合金块、海绵、荧石、四种涂蜡铜块

**植物学家工作台**：（其中真正的植物部分有许多是从其实际材质表现出发取名的，如有不妥会立刻更改）
冰、浮冰、蓝冰、雪块、泥土、黏土块、沙砾、沙子、灵魂沙、泥巴、泥坯、各种树叶、三种蛙明灯、骨块、棕色蘑菇方块、红色蘑菇方块、蘑菇柄、棕色蘑菇、红色蘑菇、西瓜、南瓜、雕刻南瓜、南瓜灯、藤蔓、睡莲、干草块、干海带块、苔藓块、蜘蛛网、菌光体、绯红菌索、诡异菌索、下界苗、下界疣块、诡异疣块、绯红菌、诡异菌

**木匠工作台**：
九种木板、七种原木、七种去皮原木、两种菌柄、两种去皮菌柄、木桶、书架、梯子、木门、木活板门、火把

**玻璃匠工作台**：
玻璃、玻璃板、十六色染色玻璃、十六色染色玻璃板

**牧羊人工作台**：
十六色羊毛、十六色地毯

**石匠工作台**：
石头、平滑石头、圆石、苔石、深板岩、安山岩、闪长岩、花岗岩、凝灰岩、方解石、滴水石块、滴水石锥、粗铜块、粗铁块、粗金块、砂岩、红砂岩、陶瓦、十六色陶瓦、十六色带釉陶瓦、十六色混凝土、红砖块、泥砖、海晶石、暗海晶石、岩浆块、黑曜石、下界岩、下界砖块、红色下界砖块、黑石、镶金黑石、玄武岩、石英块、远古残骸、末地石、紫珀块

**工匠工作台**：
铁栏杆、海晶灯、红石灯、红石块、灯笼、灵魂灯笼、红石火把

2023-03-27 08:57 UTC, ChuijkYahus commented
> 那就按实际表现译吧 `柱拱形`有图吗

![2023-03-27_16 56 57](https://user-images.githubusercontent.com/94828194/227893127-0ef119be-15f4-415a-8cc9-d42bb2f9d556.png)
其实就是上半圆形的窗户（）

2023-03-27 09:06 UTC, DrIceTea123 requested changes
补一个我这边的漏网之鱼
原因同`哭泣的黑曜石`，`雕刻南瓜`整体作为材料名

2023-03-27 09:06 UTC, DrIceTea123 commented on projects/1.19/assets/chipped/chipped/lang/zh_cn.json
> +  "block.chipped.end_carved_pumpkin": "雕刻末地南瓜",
```suggestion
  "block.chipped.end_carved_pumpkin": "末地雕刻南瓜",
```

2023-03-27 09:06 UTC, DrIceTea123 commented on projects/1.19/assets/chipped/chipped/lang/zh_cn.json
> +  "block.chipped.end_purple_carved_pumpkin": "雕刻末地紫南瓜",
```suggestion
  "block.chipped.end_purple_carved_pumpkin": "末地紫雕刻南瓜",
```

2023-03-27 09:06 UTC, DrIceTea123 commented on projects/1.19/assets/chipped/chipped/lang/zh_cn.json
> +  "block.chipped.nether_carved_pumpkin": "雕刻下界南瓜",
```suggestion
  "block.chipped.nether_carved_pumpkin": "下界雕刻南瓜",
```

2023-04-02 05:59 UTC, DrIceTea123 commented
这应该是我这的最后一个了
<img width="675" alt="无标题" src="https://user-images.githubusercontent.com/111784151/229334471-48b67b3a-ed6c-46a8-bfe6-ea84b8681d4a.png">

顺便提一下，L6785-6797，`Pointed Dripstone`这个系列按原版应该是`滴水石锥`，pr里全部是按`锥`翻译的，可以处理一下

2023-04-02 06:37 UTC, ChuijkYahus commented
`破裂的`已在上一轮全局替换

---
粗砂、珍珠砂、焦油砂、白沙靠拢原版砂土、红沙命名方式，如不妥则改

---
灵魂纸灯笼算是为读得顺改成这样的，不过可以改

---
桶相关（不改）：
![2023-04-02_14 35 06](https://user-images.githubusercontent.com/94828194/229336673-6a094470-41ba-455b-8126-ae118dca190d.png)

---
其余均已替换

2023-04-02 07:12 UTC, DrIceTea123 commented
那应该没啥问题了
列一下现在征求翻译的标准词汇
| 方块类型 | 词类型 | 英文 | 现用译文 | 参考 |
| --- | --- | --- | --- | ------ |
| 玻璃-染色玻璃 | 前缀 | Small | 厚沿纹 |  |
| 混凝土 | 前缀 | Wired | 装线 | 饰线？ |
| 活板门 | 前缀 | Overgrown | 富植 | 门/原木的同名前缀译为“缠蔓” |
| 活板门 | 前缀 | Pointless | 不设防 |  |
| 活板门 | 前缀 | Suspicious | 可疑的 |  |
| 木板 | 前缀 | Fine | 精纹 | 泥方块/石质方块的同名前缀译为“精细” |
| 木板 | 前缀 | Fine Vertical | 竖精纹 | 同上 |

2023-04-19 16:27 UTC, ChuijkYahus commented
感谢@Cactusstudent 提出的`精刻`意见

附个图
![2023-04-20_00 05 52](https://user-images.githubusercontent.com/94828194/233139538-de0d253b-aa9a-4cdb-a19a-1027f9b7d3b4.png)

2023-08-05 13:00 UTC, DrIceTea123 reviewed
返回来看了一眼，根据我个人的角度看可以打approve了
可能还得拉其他审核来看一眼

2023-08-05 13:02 UTC, DrIceTea123 approved these changes

2023-08-08 17:34 UTC, ChuijkYahus commented
明天拉个审核来看一眼（）

2023-08-14 03:06 UTC, Cactusstudent approved these changes
啊……我的眼睛

2023-08-14 03:19 UTC, qznfbnj commented
看到本PR即将合并，我去看了下官译（我去，鹅卵石
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/100760086/866b4332-4a34-4b25-8afd-fcd495ac234c)

2023-08-15 03:02 UTC, merged

2023-09-14 09:14 UTC, Catcatpigeon commented
> 看到本PR即将合并，我去看了下官译（我去，鹅卵石 ![image](https://user-images.githubusercontent.com/100760086/260349971-866b4332-4a34-4b25-8afd-fcd495ac234c.png)

官翻基本上可以鉴定为都是机翻，同一个原版用词它能有至少3种不同翻译（改得我气死了）。