generic ecosphere模组汉化
CFPAOrg/Minecraft-Mod-Language-Package pull request #3123
Opened 2023-03-18 16:43 UTC by jackychen2005

- [ ] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-03-18 18:15 UTC, mamaruo requested changes

2023-03-18 18:15 UTC, mamaruo commented on projects/1.16/assets/generic-ecosphere/genericeco/lang/zh_cn.json
> +  "death.attack.genericeco.quagmire.player": "%1$s 在试图逃跑时深陷泥潭 %2$s",
语序有问题，参考https://minecraft.fandom.com/zh/wiki/%E6%AD%BB%E4%BA%A1%E6%B6%88%E6%81%AF

2023-03-18 18:15 UTC, mamaruo commented on projects/1.16/assets/generic-ecosphere/genericeco/lang/zh_cn.json
> +  "biome.genericeco.snowy_muskeg": "白雪皑皑的麝香",
```suggestion
  "biome.genericeco.muskeg": "泥岩沼泽",
  "biome.genericeco.snowy_muskeg": "覆雪泥岩沼泽",
```

2023-03-19 09:41 UTC, ChuijkYahus requested changes
每一条suggestion都要看过去，不要改岔了

2023-03-19 09:41 UTC, ChuijkYahus requested changes
每一条suggestion都要看过去，不要改岔了

2023-03-21 16:17 UTC, ChuijkYahus requested changes
![图片](https://user-images.githubusercontent.com/94828194/226664862-4f4d6aab-6d51-4f5c-85ca-d8ee37e37eb2.png)
https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96
附原版樱花木译法，樱花也是单独的物品吧，可以参照原版的译法

2023-03-21 16:17 UTC, ChuijkYahus commented on projects/1.16/assets/generic-ecosphere/genericeco/lang/zh_cn.json
> +  "block.genericeco.stripped_cherry_log": "去皮樱桃木原木",
```suggestion
  "block.genericeco.cherry_leaves": "樱桃树叶",
  "block.genericeco.cherry_sapling": "樱桃树苗",
  "block.genericeco.cherry_log": "樱桃原木",
  "block.genericeco.cherry_wood": "樱桃木",
  "block.genericeco.stripped_cherry_log": "去皮樱桃原木",
```

2023-03-21 16:17 UTC, ChuijkYahus commented on projects/1.16/assets/generic-ecosphere/genericeco/lang/zh_cn.json
> +  "biome.genericeco.apple_orchard": "苹果园",
```suggestion
  "biome.genericeco.apple_orchard": "苹果果林",
```
可能这样稍好一些

2023-03-21 16:17 UTC, ChuijkYahus commented on projects/1.16/assets/generic-ecosphere/genericeco/lang/zh_cn.json
> +  "biome.genericeco.dying_wooded_hills": "垂死的繁茂森林丘陵",
```suggestion
  "biome.genericeco.dying_forest": "垂死森林",
  "biome.genericeco.dying_swamp": "垂死沼泽",
  "biome.genericeco.dying_swamp_hills": "垂死沼泽丘陵",
  "biome.genericeco.dying_wooded_hills": "垂死密林丘陵",
```

2023-03-31 20:16 UTC, ChuijkYahus commented
* 7+7期限进入第一阶段，请注意查看各审核意见

ping @jackychen2005

2023-04-15 11:33 UTC, ChuijkYahus commented
* 7+7时限已到，如有需要可自行reopen

@jackychen2005

2023-04-15 11:33 UTC, closed without merging

2023-04-15 12:28 UTC, mamaruo commented
![image](https://user-images.githubusercontent.com/37480168/232223541-3c8fb10b-5fe9-4fc1-a8bd-6185496c7f12.png)

投入如此精力审核的内容真的舍得关吗

2023-04-15 13:34 UTC, ChuijkYahus commented
后续如果作者愿意再来看再说吧
如果有其他人再投直接让来这里照着改应该OK