更新 Slashblade 模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #3126
Opened 2023-03-19 16:50 UTC by Arcomit

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-03-19 17:43 UTC, mamaruo commented
/diff

2023-03-19 18:07 UTC, Arcomit commented
1.12.2拔刀剑本身的本土化翻译文件存在问题：
1.历史遗留问题较多，保留了1.12.2之前MC版本的本土化（原版的日英均保留了），但相当大一部分的内容在1.12.2已被删除。提交的中翻去除掉了历史遗留下来的1.12.2不存在的内容
2.拔刀剑作者是日本人，在某一段时间内，他在日文本土化文件上写了很大功夫，而英文的内容对比日文是缺乏了很多的细节的，然而在那之后的更新，作者均只写了英文的本土化。故提交的中翻基本是日文有的内容就翻译日文，而日文没有的就翻译英文，所以单看一个对照可能对照不上。
3.我们除了翻译了日英已写的本土化，我们还翻译了部分尚未有官方但国内有称号的实体名称，如幻影刃与幻影剑entity.Drive.name，entity.SummonedBlade.name，故对比原版的本土化可能会多出一些key。（此外我们还保留了MMLP现有的拔刀翻译中的附魔1-99等级的罗马字母本土化翻译）
4.本PR中把日文盖到en_us同时上传ja_jp本意是想通过bot生成diff，然后再将正常的英译放回en_us，好合并出中日英的对照表，但bot似乎罢工了......

2023-03-20 03:12 UTC, luoxueyasha commented
我超！是拔刀剑！我来审了
![image](https://user-images.githubusercontent.com/38830216/226237827-94e27994-b201-4bb6-a3e3-ea65bc34e408.png)

什么？怎么这么多日文和英文对不上的key？怎么中文里一堆日文和英文没有的key？作者是日本人但是一直更新的是英文文本？那咋审核啊……
![image](https://user-images.githubusercontent.com/38830216/226237970-1071872f-a729-46f1-a161-5202f40aabac.png)

爱谁审谁审去吧，我溜了
![image](https://user-images.githubusercontent.com/38830216/226238009-eb4e9524-4572-4bfc-ab78-df8044831be3.png)

2023-03-20 03:33 UTC, ChuijkYahus commented
同种pr标记 #2766

2023-03-20 06:25 UTC, luoxueyasha requested changes
仅指出显著的，无足轻重的问题
有些太离谱的常用错译实在没法改

2023-03-20 06:25 UTC, luoxueyasha commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +item.flammpfeil.slashblade.proudsoul.steel_ingot.name=耀魂钢锭
这几行没有在日/英文本中见到，怎么翻译出来的
放在游戏里能够被读取吗
相同问题不再标注

2023-03-20 06:25 UTC, luoxueyasha commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +item.flammpfeil.slashblade.named.fox.black.name=狐月刀「黒狐」
```suggestion
item.flammpfeil.slashblade.named.fox.black.name=狐月刀「黑狐」
```

2023-03-20 06:25 UTC, luoxueyasha commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +item.flammpfeil.slashblade.named.muramasa.name=千鶴「村正」
```suggestion
item.flammpfeil.slashblade.named.muramasa.name=「千鶴」村正
```

2023-03-20 06:25 UTC, luoxueyasha commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +flammpfeil.sweapon.info.hfeffect.trunon=开启 : 按 快速转身 + 特殊行动 键
```suggestion
flammpfeil.sweapon.info.hfeffect.trunon=开启：快速转身+特殊行动 键
```
```suggestion
flammpfeil.sweapon.info.hfeffect.trunon=开启：按 快速转身+特殊行动 键
```
没必要在加号两遍加空格
除此之外，标点符号问题请全文通查
![image](https://user-images.githubusercontent.com/38830216/226262257-3e1356df-250c-45b2-b384-09d1bbdc33ca.png)

2023-03-20 06:25 UTC, luoxueyasha commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +enchantment.level.127=∞
原文没有罗马数字，为什么要加上？
“历史遗留”部分的原文，既然存在在语言文件里，为什么不翻译？

2023-03-20 07:19 UTC, luoxueyasha requested changes

2023-03-20 07:19 UTC, luoxueyasha commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +achievement.flammpfeil.slashblade.slashWoodenSword.desc=只斩一刀敌人的剑<br>拔刀术开始的第一步<br>§8§l§o斩钉截铁的意志才是真正的利刃
```suggestion
achievement.flammpfeil.slashblade.slashWoodenSword.desc=只斩一刀敌人的木剑%1$s§8§l§o斩杀敌人的觉悟才是真正的利刃
```
`<br>`在游戏中无法换行，但是好像`%1$s`可以
既然修了翻译那我就一并说了
①原文加戏太多，多了许多叙述性文本
②原文后半句的`切伏す`的意思是`人を切って倒す`，是带有杀意的；来源是古代刀剑砍人开光，后期才变为砍家畜或砍草席等代替物

2023-03-20 07:19 UTC, luoxueyasha commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +achievement.flammpfeil.slashblade.brokenWhiteSheath.desc=§8§l§o断面之意的代表
```suggestion
achievement.flammpfeil.slashblade.brokenWhiteSheath.desc=§8§l§o寄宿着切裂之意之物
```
```suggestion
achievement.flammpfeil.slashblade.brokenWhiteSheath.desc=§8§l§o切裂之意的象征
```
此处`切裂く`同时表示斩断敌人和折断刀刃，`代`为信物、寄托之物的意思

2023-03-20 10:32 UTC, Arcomit commented
翻译工作参考文件：拔刀剑Github(https://github.com/flammpfeil/SlashBlade/tree/1.12.2)仓库中的1.12.2日英本土化翻译文件（优先为日）

提问：为何中翻比起官方发布中的日英缺少了很多成就KEY
答：拔刀剑官方发布的版本中的日英本土化翻译存在历史遗留问题，由拔刀仓库内的成就JSON(https://github.com/flammpfeil/SlashBlade/tree/1.12.2/src/main/resources/assets/flammpfeil.slashblade/advancements)可知1.12.2仅存5个成就，但过去版本存在的成就的KEY仍保留了，翻译这些历史遗留下来而游戏内没有的内容我们认为是浪费精力与时间的便去除掉了这些KEY，如果未来拔刀剑1恢复更新（目前处于停更状态，仅拔刀剑2（为另一个模组）在更新）并将此类内容补全，我们将重新补充翻译。

提问：为何中翻会比官方发布中日英多出一部分的KEY
答：这是因为1.12.2内一部分内容确实存在，官方却没有写KEY的又或是因为某些原因导致KEY的格式已经更改官方却没有修正，如刀挂台实体的KEY因版本的迁移已经发生改变（由entity.flammpfeil.slashblade.BladeStand.name变为了entity.BladeStand.name）。而中翻修正了这点，其他新增的KEY也是如此。（中翻填写的key为代码中类或变量命名的翻译）

2023-03-20 12:44 UTC, luoxueyasha requested changes

2023-03-20 12:44 UTC, luoxueyasha commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +#zh_cn
记得把原文的游戏里没实装的key改回去

2023-03-20 12:44 UTC, luoxueyasha commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +achievement.flammpfeil.slashblade.buildWoodenBlade.desc=§8§l§o配置了鞘的普通木刀%1$s已初见拔刀术的冰山一角
```suggestion
achievement.flammpfeil.slashblade.buildWoodenBlade.desc=§8§l§o配制了鞘的普通木刀%1$s但这只是拔刀术的冰山一角
```
```suggestion
achievement.flammpfeil.slashblade.buildWoodenBlade.desc=§8§l§o一把配好鞘的普通木刀%1$s但这才刚踏入拔刀术的门槛
```
`配置`偏向`置放`，而`誂えた`偏向`订制`、`配制`
日语里会省略部分语素（例如第二人称和定语），翻译的时候要加回去
`なれど`表转折
`足懸り`此处表`第一步`、`刚入门`，主要针对某一目标刚开始时的描述

2023-03-20 12:44 UTC, luoxueyasha commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +achievement.flammpfeil.slashblade.buildWhiteSheath.desc=§8§l§o刀刃已经换成了铁制%1$s但这还不足以满足需求
```suggestion
achievement.flammpfeil.slashblade.buildWhiteSheath.desc=§8§l§o将刀刃换成了铁制的%1$s积攒的成果还是远远不够
```
```suggestion
achievement.flammpfeil.slashblade.buildWhiteSheath.desc=§8§l§o换上了铁制的刀刃%1$s但是还是不能被满足
```
原文前半句太翻译腔了，修一下
后半句`業には不十分`比较难懂，结合上一个进度，个人认为一是`（刀的）修行还不足，还不够快`；一是`斩杀敌人的业（佛教概念）积累的还不够`

2023-03-20 12:44 UTC, luoxueyasha commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +achievement.flammpfeil.slashblade.buildSlashBlade.desc=§8§l§o无铭无名的大太刀
此处`大業物`翻译从疑
`大業物`的含义：〘[名](https://kotobank.jp/word/%E5%90%8D-586865)〙 [切れ味](https://kotobank.jp/word/%E5%88%87%E3%82%8C%E5%91%B3-480542)の非常によい[刀](https://kotobank.jp/word/%E5%88%80-44955)剣。
即，`异常锋利的刀`，`業`即刀的锋利程度。
而结合之前成就的`業には不十分`，是否保留`业`字就值得商榷了
不一定需要改，但是建议拿出来讨论一下

2023-03-20 12:44 UTC, luoxueyasha commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +death.attack.directMagic=%1$s 被 %2$s 切成碎片！
```suggestion
death.attack.directMagic=%1$s 被 %2$s 一刀两断
```
首先原文没有感叹号，也不必加感叹号
其次，`切（り）裂く`既有`拦腰截断、一刀两断`的含义，又有`切成碎片`的含义
建议结合实际游戏体验（指鬼泣系列）定含义

2023-03-20 12:44 UTC, luoxueyasha commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +flammpfeil.swaepon.info.needlevel.msg=§8你需要更多经验。 至少需要等级：%1$s
```suggestion
flammpfeil.swaepon.info.needlevel.msg=§8至少需要 %1$s 级经验才能使用。
```
一种提议，可以不接受

2023-03-20 12:44 UTC, luoxueyasha commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +slashblade.seffect.name.HFCustom=HF量级
HF指？

2023-03-20 12:44 UTC, luoxueyasha commented
改好的comment记得点一下resolved

2023-03-20 14:06 UTC, Arcomit commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +slashblade.seffect.name.HFCustom=HF量级
应该是High Frequency（高频），拔刀剑作者曾自己做一个附属千鹤「村雨」源自合金装备崛起复仇，里面的高频村雨英文名字就是HF Murasama

2023-03-20 15:13 UTC, Arcomit commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +achievement.flammpfeil.slashblade.buildWhiteSheath.desc=§8§l§o刀刃已经换成了铁制%1$s但这还不足以满足需求
换上了铁制的刀刃，但仍不够锋利

2023-03-21 03:51 UTC, luoxueyasha commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +flammpfeil.slashblade.specialattack.slashdimension_spiral=次元斩・疾旋
原文为`次元斬・旋`，修改这处会引起拔刀剑玩家的不满吗

2023-03-21 03:51 UTC, luoxueyasha commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +flammpfeil.slashblade.specialattack.circleslash=元刃
日文`円`字对应的汉字应是`圆`（例：`円環`→`圆环`，`5000兆円`→`5000兆圆`），改动会引起玩家的不满吗

2023-03-21 03:51 UTC, luoxueyasha commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +achievement.flammpfeil.slashblade.buildWoodenBlade.desc=§8§l§o一把配好鞘的普通木刀%1$s§8§l§o但这才刚踏入拔刀术的门槛
```suggestion
achievement.flammpfeil.slashblade.buildWoodenBlade.desc=§8§l§o配好了鞘的普通木刀%1$s§8§l§o但这才刚踏入拔刀术的门槛
```
![image](https://user-images.githubusercontent.com/38830216/226511624-b67f3dcd-56d1-4a23-b226-9d137d09dda3.png)
实际游戏里会显示成这样，看来还是得缩句

2023-03-21 03:51 UTC, luoxueyasha commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +#日翻为刀の薄魂片（漂浮的刀魂结晶）,英翻为TinyProudSoul（小荣耀之魂），但国内译名破碎的耀魂流传已久不宜更改#
注释的错译改一下

2023-03-21 03:51 UTC, luoxueyasha commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +achievement.flammpfeil.slashblade.slashWoodenSword.desc=用木剑作战%1$s§8§l§o斩杀敌人的觉悟才是真正的利刃
```suggestion
achievement.flammpfeil.slashblade.slashWoodenSword.desc=持木剑作战%1$s§8§l§o斩杀敌人的觉悟才是真正的利刃
```
小建议

2023-03-21 03:51 UTC, luoxueyasha commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +entity.LumberManager.name=伐木实体
问下这个实体什么情况下才会生成

2023-03-21 05:03 UTC, Arcomit commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +flammpfeil.slashblade.specialattack.circleslash=元刃
円刃被翻译成元刃算是个拔刀剑官译的历史遗留问题（与物品名类似），因为SA在拔刀剑中占据的位置很高，不太适宜更改

2023-03-21 05:22 UTC, Arcomit commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +flammpfeil.slashblade.specialattack.slashdimension_spiral=次元斩・疾旋
次元斬・旋是1.12.2新增的SA，官中无翻译，中译名可以讨论。
尽管带有次元斩，但鬼泣中没有找到相关内容。英文处被命名为SlashDimension S，从KEY：slashdimension_spiral可以得出这个S是指spiral（螺旋）。
据该key翻译者所言，sprial亦有急剧的意思故译成了疾旋。
但据我刚才观察游戏内该SA与正常次元斩的区别：在释放后会有螺旋状的幻影刃发射，我个人更倾向于直接翻译成次元斩·螺旋。
亦可根据日文翻译为次元斩·旋。

2023-03-21 05:24 UTC, Arcomit commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +entity.LumberManager.name=伐木实体
使用拔刀剑砍树产生的用于连锁砍树的实体（无渲染，但F3+B砍树可查看碰撞箱）

2023-03-21 05:24 UTC, Arcomit commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +flammpfeil.slashblade.specialattack.circleslash=元刃
> 

円刃被翻译成元刃算是个拔刀剑官译的历史遗留问题（与物品名类似），因为SA在拔刀剑中占据的位置很高，不太适宜更改

2023-03-21 06:07 UTC, luoxueyasha commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +flammpfeil.slashblade.specialattack.slashdimension_spiral=次元斩・疾旋
我觉得这里`spiral`没有`加剧`、`急剧`的意思，`螺旋`和`旋`都是可用的译名
个人而言更喜欢`次元斩·旋`
顺带一提标准的书面间隔号是`·`

2023-03-21 06:15 UTC, Arcomit commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +flammpfeil.slashblade.specialattack.slashdimension_spiral=次元斩・疾旋
> 

那就继续以日文优先翻译为次元斩·旋，符号已修改

2023-03-24 07:47 UTC, luoxueyasha approved these changes
语义没有问题，几个广流传的错译也不好动，所以approve了
但是还是需要注意以下问题
1. 改拔刀剑的翻译，玩家群体的态度如何
2. 如果拔刀剑1后续真的有官库更新，那么这一版的排版格式就是对官库更新的不匹配，后人很难进行维护；建议将所有的注释丢到conversation里而非原文文件里，github可以按照时间流查到对应的pr
3. 其他审核/CFPA的管理员对此pr是否同意

就我个人而言，我是非常不满意这份pr的，提交者自我主张太重
提交approve是为了让其他审核确认工作进度

2023-03-24 09:06 UTC, Arcomit commented
> approved

十分感谢能得到approved。

> 改拔刀剑的翻译，玩家群体的态度如何

在PR之前，我们就已制作了相关的资源包并发布在拔刀剑附属作者的群及拔刀剑玩家的讨论组中
我们得到的反馈是诸如“文件汉化挺全的谢谢”的反馈，同样我们也得到过”为什么要改物品译名“，”修改物品译名会让部分人无法找到百科资料“的反馈，因此我们吸取了教训，故PR的版本物品的译名并没有改动（将译名改回去之后其也对该汉化表示称赞），**此外我们没有收到更多的负面反馈，若后续有新的负面反馈，我们吸取有用的信息继续更进。**

> 如果拔刀剑1后续真的有官库更新，那么这一版的排版格式就是对官库更新的不匹配，后人很难进行维护；建议将所有的注释丢到conversation里而非原文文件里，github可以按照时间流查到对应的pr

目前的排版是针对目前官库的排版混乱，可能会对审核造成影响而进行的。（此前您也要求排序方法和中文一致）
我们有与英翻格式相同无注释的版本，如有必要我们亦可以上传。

十分感谢[luoxueyasha](https://github.com/luoxueyasha)对我们错译的指出以及相关的建议，我承认我的水平有限，我本人也只是因为看到了拔刀剑官库一些明显错译（如快速转身被翻译成快速锁定等）而无人更正【i18n目前的拔刀剑翻译也存在该问题】而脑子一热，靠着一腔热血去进行的翻译修正，但很显然，我的实力不足以完成此项任务，与拔刀剑官库的翻译者犯了相同错误，但好在有[luoxueyasha](https://github.com/luoxueyasha)的指出与协助，让修正拔刀剑官库错译与填补空缺翻译的工作更加顺利，再次感谢[luoxueyasha](https://github.com/luoxueyasha)。

2023-03-24 10:51 UTC, Arcomit commented
> 我觉得可能是交流的时候产生了分歧： 库里需要留一份原文格式的原文，或者能从原文通过简单的生成（例如升序排序）得到的语言，以便于后人维护 而上传方的做法是往库里扔了自己人工排序后的原文，以至于如果有后来版本，那么对照键名会相当麻烦 这种大幅改变格式的参考，我个人建议是扔到pr的comment里，而不是上传到库里 同样的，中文的key格式理论上也应该与原文一致

已push与原文顺序一致版本

2023-03-24 10:55 UTC, Arcomit commented
人工排序版本：https://github.com/Arcomit/SlashBladeTranslation

2023-03-24 11:03 UTC, luoxueyasha requested changes
英文忘传了

2023-03-24 11:03 UTC, luoxueyasha commented on projects/1.12.2/assets/slashblade/flammpfeil.slashblade/lang/zh_cn.lang
> +item.flammpfeil.slashblade.named.muramasa.name=「千鶴」村正
```suggestion
item.flammpfeil.slashblade.named.muramasa.name=「千鹤」村正
```

2023-03-24 11:09 UTC, Arcomit commented
> 

英文有上传。鹤字确实存在错误，已修正。

2023-03-26 07:00 UTC, ChuijkYahus approved these changes
确实名字没法审核（）
但看上去应该是没什么问题了吧

2023-03-29 07:12 UTC, luoxueyasha approved these changes

2023-03-31 19:30 UTC, merged