Dungeons Mobs 汉化提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3134
Opened 2023-03-22 09:36 UTC by Annijang

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-03-25 06:09 UTC, luoxueyasha requested changes
部分问题仅指出其中一处

2023-03-25 06:09 UTC, luoxueyasha commented on projects/1.19/assets/dungeons-mobs/dungeons_mobs/lang/zh_cn.json
> +  "mobEnchantment.dungeons_mobs.quick": "快速",
```suggestion
  "mobEnchantment.dungeons_mobs.quick": "疾速",
```
可以参考[wiki的相关资料](https://minecraft.fandom.com/zh/wiki/Minecraft_Dungeons:%E9%99%84%E9%AD%94)

2023-03-25 06:09 UTC, luoxueyasha commented on projects/1.19/assets/dungeons-mobs/dungeons_mobs/lang/zh_cn.json
> +  "subtitles.entity.geomancer.bomb_spawn": "爆炸石柱墙：生成",
```suggestion
  "subtitles.entity.geomancer.bomb_spawn": "爆炸石柱：生成",  
```
同上，要改请全部修改

2023-03-25 06:09 UTC, luoxueyasha commented on projects/1.19/assets/dungeons-mobs/dungeons_mobs/lang/zh_cn.json
> +  "subtitles.entity.squall_golem.step": "呼啸傀儡：行走",
```suggestion
"subtitles.entity.squall_golem.step": "呼啸傀儡：脚步声",
```
参考[wiki的字幕翻译](https://minecraft.fandom.com/zh/wiki/%E5%AD%97%E5%B9%95)

2023-03-25 06:09 UTC, luoxueyasha commented on projects/1.19/assets/dungeons-mobs/dungeons_mobs/lang/zh_cn.json
> +  "subtitles.entity.redstone_golem.summon_mines": "红石傀儡：召唤矿井",
上面`redstone mine`是地雷

2023-07-04 01:34 UTC, luoxueyasha commented
@Annijang 请对参考意见进行回复

2023-07-30 10:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3134) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3134) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3134) it.</sub>

2023-08-01 05:30 UTC, luoxueyasha commented
@Annijang 
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

2023-08-08 02:01 UTC, Cactusstudent commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@Annijang

2023-08-15 07:23 UTC, closed without merging