Chilean Craft翻译提交 （WIP）
CFPAOrg/Minecraft-Mod-Language-Package pull request #3136
Opened 2023-03-23 06:23 UTC by CoalGlage

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-03-23 06:43 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +
注释：此语言文件中存在配方缺失/无法被jei查询和查无此物现象。

2023-03-23 06:43 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "item.chilecraft_reworked.semilla_de_uva_pais": "派斯葡萄种子",
注释：此葡萄品种的原文是Uva País

2023-03-23 06:43 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "block.chileancraft.madera_de_araucaria": "南美杉木",
注释：Madera对应“XX木”，Tronco对应“XX原木”，Hoja对应“XX树叶”，Brote对应“XX树苗”

2023-03-23 06:43 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "block.chileancraft.acab": "镐子",
注释：查无此物+1

2023-03-23 06:43 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "item.chileancraft.armadura_cargada_leggings": "护甲填充护腿",
注释：看起来这个模组像是通过mccreator制作的...

2023-03-23 06:43 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "block.chilecraft_reworked.pipa_de_rauli": "山毛榉酒桶",
注释：不清楚此方块功能，也许是酿酒用。配方缺失+1

2023-03-23 06:43 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "block.chileancraft.hoja_de_espino": "山楂树树叶",
注释：搜到的结果是espino是指山楂，或者鼠李。 因为模组内没有对应果实，译者也见不到对应的植株结构，所以这里暂取“山楂”意。

2023-03-23 06:43 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "item.chilecraft_reworked.pinones_de_oro": "金松子",
注释：oro，西语“黄金”（隔壁Orokin就是用这个词和日语的kin（也是“黄金”意）合成的）。

2023-03-23 06:43 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "biome.chileancraft.araucania": "阿劳卡尼亚地区",
注释：原文Araucanía。

2023-03-23 06:43 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "block.chileancraft.pico": "镐子",
注释：查无此物+1

2023-03-23 06:43 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "item.chileancraft.panoleta_helmet": "领巾",
注释：原文Pañoleta。

2023-03-23 06:43 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "item.chileancraft.vendedor_de_la_ligua_spawn_egg": "拉利瓜小贩刷怪蛋",
注释：拉利瓜（La Ligua）是智利一城镇。

2023-03-23 06:43 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "item.chileancraft.sopadiguene": "迪圭涅菇汤",
注释：原文Sopa De Digueñe，Digueñe是一种智利当地特有的食用菌类，没有中文名所以我只能音译了...

2023-03-23 06:43 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "block.chileancraft.troncos_de_espino_pelados": "山楂树原木块",
注释：在要不要加量词上做出的取舍（不是）

2023-03-23 06:43 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "item.chileancraft.pipeno_tinto": "红派皮尼奥酒",
注释：酒的原文是Pipeño，“派皮尼奥”系个人音译。
Vino Tinto，即红葡萄酒。下文的Vine Blanco为白葡萄酒。

2023-03-23 06:43 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "block.chileancraft.diente_de_leon": "智利蒲公英",
注释：可是游戏本体里已经有蒲公英了...

2023-03-23 06:43 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "item.chileancraft.pipeno_uva_pais": "派斯佩皮尼奥酒",
注释：该酒使用派斯葡萄酿造。

2023-03-23 06:43 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "block.chilecraft_reworked.ananuca": "阿纳努卡",
注释：原文Añañuca，一种智利植物。

2023-03-23 06:43 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "item.chileancraft.machas_parmesanas": "帕尔玛森焗蛤",
注释：搜到的全称应该是Machas a la parmesana。

2023-03-23 06:43 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "item.chileancraft.san_pedro_trago": "圣佩德罗酒",
注释：这个是个瓶装饮料。trago有酒的意思。

2023-03-23 06:43 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "item.chileancraft.trompo_cordel_1": "绳子和陀螺",
注释：这个投掷出的是默认颜色的陀螺，是非被动生物。但别的是被动型。。。

2023-03-23 06:43 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "item.chileancraft.pico_de_culebron": "大蛇之口",
注释：虽然是pico但是这个不作“镐子”意，物品外观是一张嘴。

2023-03-23 07:21 UTC, CoalGlage commented
注：此语言文件中存在配方缺失/无法被jei查询和查无此物现象。

2023-03-23 07:36 UTC, CoalGlage commented
另，有无西语校对（）

2023-03-23 08:10 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "item.chileancraft.pebre": "Pebre",
注释：搜到的一个翻译是“蒜味麻辣醋”，而从外观和维基百科的解释来看更像是一种sauce而非vinegar

2023-03-23 09:02 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "block.chileancraft.olla_de_greda": "Olla De Greda",
以下，XX de greda暂译“陶土XX”，XX de greda cocida暂译“陶制XX”

2023-03-23 09:05 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "item.chileancraft.bola_de_greda": "Bola De Greda",
注释：合成相关方块的原料

2023-03-23 09:10 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "block.chilecraft_reworked.bloque_de_greda_seca": "Bloque De Greda Seca",
注释：查无此物+1

2023-03-23 09:25 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "block.chileancraft.chanchito_de_greda_cruda": "Chnachito De Greda ",
注释：chanchito是智利当地用来庆祝某个节日会用到的小猪外观的装饰品。

2023-03-23 09:33 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "block.chileancraft.bloque_de_greda_cocida": "Bloque De Greda Cocida",
注释：这里要是用“陶制块”未免过于奇怪了...

2023-03-23 09:34 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "block.chileancraft.ladrillos_de_greda": "Ladrillos De Greda ",
注释：这个物品是用陶土球（bola de greda）烧制而成的。

2023-03-23 09:35 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "advancements.fundandopomaire.title": "建造波麦雷镇",
注释：pomaire也是智利的城镇，以陶艺而闻名。

2023-03-23 09:48 UTC, CoalGlage commented
西语和英语文件中有时会出现一长串乱码
乱码有两种，分别对应西语字母í和ñ

2023-03-23 14:27 UTC, luoxueyasha reviewed
更新：
排了一下string语序
如果可以的话还请将修复后的文件提交commit，替换原文

---

修了一下源文件的乱码，使用了以下的python脚本
```python
import ftfy

oldFile = open("es_cl.json",  "r", encoding="utf-8")
newFile = open("es_cl_new.json",  "w", encoding="utf-8")
while  True:
    line = oldFile.readline()
    if not line  :
        break
    fline = ftfy.fix_text(line.strip())
    newFile.write(fline + '\n')

oldFile.close()
newFile.close()
```
（需要：python 3.6+，ftfy 4.1+）
不过乱码处理后还会有部分的字母显示为`�`，这个我手动对键名了

顺带一提ftfy有`fix_file()`函数，但是没找到相关的文档

2023-03-23 14:27 UTC, luoxueyasha commented on projects/1.18/assets/chileancraft/chileancraft/lang/en_us.json
> +{
```
{
"item.chileancraft.armadura_cargada_leggings": "Armadura Cargada Leggings",
"item.chilecraft_reworked.semilla_de_uva_pais": "Semilla De Uva País",
"item.chileancraft.copper_nugget": "Copper Nugget",
"block.chilecraft_reworked.parra_11": "Parra ",
"block.chilecraft_reworked.parra_10": "Parra ",
"item.chilecraft_reworked.cazuela": "Cazuela",
"item.chilecraft_reworked.cuchillo_de_cocina": "Cuchillo De Cocina",
"item.chileancraft.palo_de_lluvia": "Palo De Lluvia",
"entity.chileancraft.trompo_verde": "Trompo",
"entity.chileancraft.codorniz": "Codorniz",
"item.chileancraft.jaiba_spawn_egg": "Jaiba Spawn Egg",
"item.chileancraft.ropa_mapuche_1_boots": "Poncho Mapuche Boots",
"item.chileancraft.lanza_lacrimogena": "Lanza Lacrimogena",
"block.chileancraft.aji_2": "Aji Verde ",
"block.chileancraft.aji_3": "Aji Verde ",
"block.chileancraft.madera_de_araucaria": "Madera De Araucaria",
"block.chileancraft.acab": "Grafitti",
"item.chileancraft.trompoverde_spawn_egg": "Trompo Spawn Egg",
"block.chileancraft.aji_4": "Aji Verde ",
"block.chileancraft.aji_5": "Aji Verde ",
"block.chileancraft.aji_0": "Aji Verde ",
"block.chileancraft.aji_1": "Aji Verde ",
"block.chilecraft_reworked.hierba_de_san_juan": "Hierba De San Juan",
"block.chilecraft_reworked.pipa_de_rauli": "Pipa De Rauli",
"item.chilecraft_reworked.aji_cacho_de_cabra_ahumado": "Aji Cacho De Cabra Ahumado",
"item.chilecraft_reworked.codorniz_bebe_spawn_egg": "Codorniz Bebe Spawn Egg",
"item.chileancraft.macha_cruda": "Macha Cruda",
"item.chileancraft.pebre": "Pebre",
"item.chilecraft_reworked.carne_de_caballo": "Carne De Caballo",
"item.chileancraft.semilla_de_uva_pais": "Semilla De Uva País",
"block.chileancraft.olla_de_greda": "Olla De Greda",
"item.chileancraft.choclo": "Choclo",
"item.chilecraft_reworked.sopaipilla": "Sopaipilla",
"block.chileancraft.mena_desalitre": "Mena De Salitre",
"block.chileancraft.hoja_de_espino": "Hoja De Espino",
"item.chileancraft.pepita_cargada": "Pepita Cargada",
"item.chileancraft.reineta_spawn_egg": "Merluza Spawn Egg",
"item.chilecraft_reworked.espada_de_cobre": "Espada De Cobre",
"item.chileancraft.bola_de_greda": "Bola De Greda",
"block.chilecraft_reworked.taza_de_greda": "Taza De Greda",
"item.chilecraft_reworked.pinones_de_oro": "Piñones De Oro",
"block.chilecraft_reworked.bloque_de_greda_seca": "Bloque De Greda Seca",
"item.chileancraft.piel_de_coipo": "Piel De Coipo",
"item.chileancraft.cuchuflis": "Cuchuflis",
"item.chileancraft.carne_de_caballo": "Carne De Caballo",
"block.chileancraft.tablones_de_araucaria": "Tablones De Arbol Nativo",
"block.chileancraft.loza_de_combarbalita": "Loza De Combarbalita",
"subtitles.kuku4": "",
"subtitles.kuku3": "",
"item.chileancraft.bolsa_del_dylan_helmet": "Bolsa Del Dylan ",
"item.chileancraft.pelota_spawn_egg": "Pelota Spawn Egg",
"subtitles.kuku2": "",
"item.chilecraft_reworked.jugo_de_manzana": "Jugo De Manzana",
"subtitles.kuku1": "",
"biome.chileancraft.desierto_florido": "Desierto Florido",
"item.chileancraft.mano_elastica": "Mano Elastica",
"item.chilecraft_reworked.moneda_de_50": "Moneda De 50",
"item.chileancraft.plato_hondo_de_greda_item": "Plato Hondo De Greda ",
"item.chilecraft_reworked.tomate_limachino": "Tomate Limachino",
"item.chileancraft.cabra_spawn_egg": "Cabra Spawn Egg",
"advancements.hahahaaaa.title": "HAHAHAAAA",
"item.chilecraft_reworked.chupalla_chestplate": "Chupalla Body",
"item.chileancraft.espada_de_arturo_prat": "Espada De Arturo Prat",
"block.chileancraft.tinaja_de_greda_cocida": "Tinaja De Greda Cocida",
"entity.chilecraft_reworked.codorniz": "Codorniz",
"block.chileancraft.tierra_arcillosa": "Tierra Arcillosa",
"block.chilecraft_reworked.ladrillos_de_adobe": "Ladrillos De Adobe",
"item.chilecraft_reworked.copper_nugget": "Copper Nugget",
"item.chileancraft.spray": "Spray",
"item.chilecraft_reworked.armadura_de_puma_helmet": "Gorro De Puma ",
"block.chileancraft.escalera_de_greda": "Escalera De Greda",
"item.chileancraft.codorniz_bebe_spawn_egg": "Codorniz Bebe Spawn Egg",
"item.chileancraft.pastel_de_choclo_cocido": "Pastel De Choclo Cocido",
"block.chilecraft_reworked.tierra_seca": "Tierra Seca",
"block.chilecraft_reworked.tinaja_de_greda_chica_cocida": "Tinaja De Greda Chica Cocida",
"item.chileancraft.armadura_puma_2_boots": "Botas De Puma ",
"item.chileancraft.macha_cocida": "Macha Cocida",
"item.chileancraft.pinones_de_oro": "Piñones De Oro",
"item.chileancraft.uva_red_glob": "Uva Red Globe",
"item.chileancraft.aji_relleno_rojo": "Aji Relleno ",
"item.chileancraft.cuajo": "Cuajo",
"itemGroup.tabchilecraft": "Chileancraft Foods",
"block.chilecraft_reworked.tinaja_de_greda": "Tinaja De Greda ",
"item.chileancraft.pico_de_cobre": "Pico De Cobre",
"biome.chileancraft.araucania": "Araucania",
"block.chileancraft.pico": "Grafitti",
"item.chileancraft.hoz_de_cobre": "Hacha De Cobre",
"block.chileancraft.tomate_9": "Tomate ",
"item.chileancraft.trompo_rojo_spawn_egg": "Trompo Spawn Egg",
"item.chilecraft_reworked.huevo": "Huevo",
"entity.chileancraft.aldeano_de_fonda": "Aldeano De Fonda",
"item.chilecraft_reworked.bola_de_greda": "Bola De Greda",
"item.chileancraft.panoleta_helmet": "Pañoleta ",
"item.chileancraft.cachito": "Cachito",
"entity.chileancraft.paco": "Paco",
"entity.chileancraft.vendedor_de_la_ligua": "Vendedor De La Ligua",
"item.chileancraft.choripan": "Choripan",
"block.chileancraft.tomate_3": "Tomate ",
"item.chileancraft.trompo_spawn_egg": "Trompo Spawn Egg",
"block.chileancraft.tomate_2": "Tomate ",
"block.chileancraft.tomate_1": "Tomate ",
"block.chileancraft.tomate_0": "Tomate ",
"block.chileancraft.aji_6": "Aji Verde ",
"block.chileancraft.tomate_4": "Tomate ",
"entity.chileancraft.aldeano_huaso": "Aldeano Huaso",
"block.chilecraft_reworked.loza_de_greda": "Loza De Greda",
"item.chileancraft.lanza_lautaro": "Lanza De Lautaro",
"item.chileancraft.pico_cargado": "Pico De Cobre Cargado",
"item.chileancraft.vaso": "Vaso",
"item.chilecraft_reworked.aji_verde": "Aji Verde",
"block.chileancraft.rama_san_pedro": "Rama San Pedro",
"item.chilecraft_reworked.huevo_de_codorniz": "Huevo De Codorniz",
"item.chilecraft_reworked.jugo_de_uva_red_globe": "Jugo De Uva Red Globe",
"item.chilecraft_reworked.moneda_de_10": "Moneda De 10",
"item.chileancraft.alicanto_spawn_egg": "Alicanto Spawn Egg",
"biome.chileancraft.desierto_de_atacama_montanoso": "Desierto de atacama Montañoso",
"item.chilecraft_reworked.aji_cacho_de_cabra": "Aji Cacho De Cabra",
"block.chilecraft_reworked.parra_9": "Parra ",
"block.chileancraft.bloque_de_paja": "Bloque De Paja",
"item.chileancraft.bolsa_del_dylan_chestplate": "Bolsa Del Dylan Body",
"item.chileancraft.aldeano_haitiano_spawn_egg": "Aldeano Haitiano Spawn Egg",
"block.chilecraft_reworked.parra_8": "Parra ",
"entity.chileancraft.trompo_rojo": "Trompo",
"block.chilecraft_reworked.parra_7": "Parra ",
"block.chileancraft.banderadark": "Bandera De Chile Negra",
"block.chilecraft_reworked.parra_2": "Parra ",
"block.chilecraft_reworked.parra_1": "Parra ",
"block.chilecraft_reworked.parra_0": "Parra ",
"block.chilecraft_reworked.parra_6": "Parra ",
"block.chilecraft_reworked.parra_5": "Parra ",
"block.chilecraft_reworked.parra_4": "Parra ",
"block.chilecraft_reworked.parra_3": "Parra ",
"item.chileancraft.curanto": "Curanto",
"item.chileancraft.leche_de_cabra": "Leche De Cabra",
"entity.chilecraft_reworked.puma": "Puma",
"item.chileancraft.vendedor_de_la_ligua_spawn_egg": "Vendedor De La Ligua Spawn Egg",
"block.chileancraft.puerta_de_valla_de_araucaria": "Puerta De Arbol Nativo",
"advancements.millonario.descr": "Obten una palta",
"entity.chileancraft.basilisco": "Basilisco",
"item.chileancraft.chaleco_reflectante_helmet": "Chaleco Reflectante Helmet",
"item.chileancraft.bote_de_pesca_item": "Bote De Pesca ",
"item.chileancraft.armadura_de_cobre_chestplate": "Peto De Cobre",
"block.chileancraft.tronco_de_espino_pelado": "Tronco De Espino Pelado",
"entity.chileancraft.jaiba": "Jaiba",
"item.chileancraft.marraqueta": "Marraqueta",
"item.chileancraft.moneda_de_100": [...]

2023-03-23 14:27 UTC, luoxueyasha commented on projects/1.18/assets/chileancraft/chileancraft/lang/es_cl.json
> +{
```
{
"item.chileancraft.armadura_cargada_leggings": "Armadura Cargada Leggings",
"item.chilecraft_reworked.semilla_de_uva_pais": "Semilla De Uva País",
"item.chileancraft.copper_nugget": "Copper Nugget",
"block.chilecraft_reworked.parra_11": "Parra ",
"block.chilecraft_reworked.parra_10": "Parra ",
"item.chilecraft_reworked.cazuela": "Cazuela",
"item.chilecraft_reworked.cuchillo_de_cocina": "Cuchillo De Cocina",
"item.chileancraft.palo_de_lluvia": "Palo De Lluvia",
"entity.chileancraft.trompo_verde": "Trompo",
"entity.chileancraft.codorniz": "Codorniz",
"item.chileancraft.jaiba_spawn_egg": "Jaiba Spawn Egg",
"item.chileancraft.ropa_mapuche_1_boots": "Poncho Mapuche Boots",
"item.chileancraft.lanza_lacrimogena": "Lanza Lacrimogena",
"block.chileancraft.aji_2": "Aji Verde ",
"block.chileancraft.aji_3": "Aji Verde ",
"block.chileancraft.madera_de_araucaria": "Madera De Araucaria",
"block.chileancraft.acab": "Pico",
"item.chileancraft.trompoverde_spawn_egg": "Trompo Spawn Egg",
"block.chileancraft.aji_4": "Aji Verde ",
"block.chileancraft.aji_5": "Aji Verde ",
"block.chileancraft.aji_0": "Aji Verde ",
"block.chileancraft.aji_1": "Aji Verde ",
"block.chilecraft_reworked.hierba_de_san_juan": "Hierba De San Juan",
"block.chilecraft_reworked.pipa_de_rauli": "Pipa De Rauli",
"item.chilecraft_reworked.aji_cacho_de_cabra_ahumado": "Aji Cacho De Cabra Ahumado",
"item.chilecraft_reworked.codorniz_bebe_spawn_egg": "Codorniz Bebe Spawn Egg",
"item.chileancraft.macha_cruda": "Macha Cruda",
"item.chileancraft.pebre": "Pebre",
"item.chilecraft_reworked.carne_de_caballo": "Carne De Caballo",
"item.chileancraft.semilla_de_uva_pais": "Semilla De Uva País",
"block.chileancraft.olla_de_greda": "Olla De Greda",
"item.chileancraft.choclo": "Choclo",
"item.chilecraft_reworked.sopaipilla": "Sopaipilla",
"block.chileancraft.mena_desalitre": "Mena De Salitre",
"block.chileancraft.hoja_de_espino": "Hoja De Espino",
"item.chileancraft.pepita_cargada": "Pepita Cargada",
"item.chileancraft.reineta_spawn_egg": "Reineta Spawn Egg",
"item.chilecraft_reworked.espada_de_cobre": "Espada De Cobre",
"item.chileancraft.bola_de_greda": "Bola De Greda",
"block.chilecraft_reworked.taza_de_greda": "Taza De Greda",
"item.chilecraft_reworked.pinones_de_oro": "Piñones De Oro",
"block.chilecraft_reworked.bloque_de_greda_seca": "Bloque De Greda Seca",
"item.chileancraft.piel_de_coipo": "Piel De Coipo",
"item.chileancraft.cuchuflis": "Cuchuflis",
"item.chileancraft.carne_de_caballo": "Carne De Caballo",
"block.chileancraft.tablones_de_araucaria": "Tablones De Araucaria",
"block.chileancraft.loza_de_combarbalita": "Escalera De Combarbalita",
"subtitles.kuku4": "",
"subtitles.kuku3": "",
"item.chileancraft.bolsa_del_dylan_helmet": "Bolsa Del Dylan ",
"item.chileancraft.pelota_spawn_egg": "Pelota Spawn Egg",
"subtitles.kuku2": "",
"item.chilecraft_reworked.jugo_de_manzana": "Jugo De Manzana",
"subtitles.kuku1": "",
"biome.chileancraft.desierto_florido": "Desierto Florido",
"item.chileancraft.mano_elastica": "Mano Elastica",
"item.chilecraft_reworked.moneda_de_50": "Moneda De 50",
"item.chileancraft.plato_hondo_de_greda_item": "Plato Hondo De Greda ",
"item.chilecraft_reworked.tomate_limachino": "Tomate Limachino",
"item.chileancraft.cabra_spawn_egg": "Cabra Spawn Egg",
"advancements.hahahaaaa.title": "HAHAHAAAA",
"item.chilecraft_reworked.chupalla_chestplate": "Chupalla Body",
"item.chileancraft.espada_de_arturo_prat": "Espada De Arturo Prat",
"block.chileancraft.tinaja_de_greda_cocida": "Tinaja De Greda Cocida",
"entity.chilecraft_reworked.codorniz": "Codorniz",
"block.chileancraft.tierra_arcillosa": "TIerra Arcillosa",
"block.chilecraft_reworked.ladrillos_de_adobe": "Ladrillos De Adobe",
"item.chilecraft_reworked.copper_nugget": "Copper Nugget",
"item.chileancraft.spray": "Spray",
"item.chilecraft_reworked.armadura_de_puma_helmet": "Gorro De Puma ",
"block.chileancraft.escalera_de_greda": "Escalera De Greda",
"item.chileancraft.codorniz_bebe_spawn_egg": "Codorniz Bebe Spawn Egg",
"item.chileancraft.pastel_de_choclo_cocido": "Pastel De Choclo Cocido",
"block.chilecraft_reworked.tierra_seca": "Tierra Seca",
"block.chilecraft_reworked.tinaja_de_greda_chica_cocida": "Tinaja De Greda Chica Cocida",
"item.chileancraft.armadura_puma_2_boots": "Botas De Puma ",
"item.chileancraft.macha_cocida": "Macha Cocida",
"item.chileancraft.pinones_de_oro": "Piñones De Oro",
"item.chileancraft.uva_red_glob": "Uva Red Globe",
"item.chileancraft.aji_relleno_rojo": "Aji Relleno ",
"item.chileancraft.cuajo": "Cuajo",
"itemGroup.tabchilecraft": "Chileancraft Foods",
"block.chilecraft_reworked.tinaja_de_greda": "Tinaja De Greda ",
"item.chileancraft.pico_de_cobre": "Pico De Cobre",
"biome.chileancraft.araucania": "Araucania",
"block.chileancraft.pico": "Pico",
"item.chileancraft.hoz_de_cobre": "Hacha De Cobre",
"block.chileancraft.tomate_9": "Tomate ",
"item.chileancraft.trompo_rojo_spawn_egg": "Trompo Spawn Egg",
"item.chilecraft_reworked.huevo": "Huevo",
"entity.chileancraft.aldeano_de_fonda": "Aldeano Huaso",
"item.chilecraft_reworked.bola_de_greda": "Bola De Greda",
"item.chileancraft.panoleta_helmet": "Pañoleta ",
"item.chileancraft.cachito": "Cachito",
"entity.chileancraft.paco": "Paco",
"entity.chileancraft.vendedor_de_la_ligua": "Aldeano Haitiano",
"item.chileancraft.choripan": "Choripan",
"block.chileancraft.tomate_3": "Tomate ",
"item.chileancraft.trompo_spawn_egg": "Trompo Spawn Egg",
"block.chileancraft.tomate_2": "Tomate ",
"block.chileancraft.tomate_1": "Tomate ",
"block.chileancraft.tomate_0": "Tomate ",
"block.chileancraft.aji_6": "Aji Verde ",
"block.chileancraft.tomate_4": "Tomate ",
"entity.chileancraft.aldeano_huaso": "Aldeano Huaso",
"block.chilecraft_reworked.loza_de_greda": "Loza De Greda",
"item.chileancraft.lanza_lautaro": "Lanza ",
"item.chileancraft.pico_cargado": "Pico De Cobre Cargado",
"item.chileancraft.vaso": "Vaso",
"item.chilecraft_reworked.aji_verde": "Aji Verde",
"block.chileancraft.rama_san_pedro": "Rama San Pedro",
"item.chilecraft_reworked.huevo_de_codorniz": "Huevo De Codorniz",
"item.chilecraft_reworked.jugo_de_uva_red_globe": "Jugo De Uva Red Globe",
"item.chilecraft_reworked.moneda_de_10": "Moneda De 10",
"item.chileancraft.alicanto_spawn_egg": "Alicanto Spawn Egg",
"biome.chileancraft.desierto_de_atacama_montanoso": "Desierto de atacama Montañoso",
"item.chilecraft_reworked.aji_cacho_de_cabra": "Aji Cacho De Cabra",
"block.chilecraft_reworked.parra_9": "Parra ",
"block.chileancraft.bloque_de_paja": "Bloque De Paja",
"item.chileancraft.bolsa_del_dylan_chestplate": "Bolsa Del Dylan Body",
"item.chileancraft.aldeano_haitiano_spawn_egg": "Aldeano Vendedor Spawn Egg",
"block.chilecraft_reworked.parra_8": "Parra ",
"entity.chileancraft.trompo_rojo": "Trompo",
"block.chilecraft_reworked.parra_7": "Parra ",
"block.chileancraft.banderadark": "Bandera De Chile",
"block.chilecraft_reworked.parra_2": "Parra ",
"block.chilecraft_reworked.parra_1": "Parra ",
"block.chilecraft_reworked.parra_0": "Parra ",
"block.chilecraft_reworked.parra_6": "Parra ",
"block.chilecraft_reworked.parra_5": "Parra ",
"block.chilecraft_reworked.parra_4": "Parra ",
"block.chilecraft_reworked.parra_3": "Parra ",
"item.chileancraft.curanto": "Curanto",
"item.chileancraft.leche_de_cabra": "Leche De Cabra",
"entity.chilecraft_reworked.puma": "Puma",
"item.chileancraft.vendedor_de_la_ligua_spawn_egg": "Aldeano Haitiano Spawn Egg",
"block.chileancraft.puerta_de_valla_de_araucaria": "Puerta De Valla De Araucaria",
"advancements.millonario.descr": "Obten una palta",
"entity.chileancraft.basilisco": "Basilisco",
"item.chileancraft.chaleco_reflectante_helmet": "Chaleco Reflectante Helmet",
"item.chileancraft.bote_de_pesca_item": "Bote De Pesca ",
"item.chileancraft.armadura_de_cobre_chestplate": "Peto De Cobre",
"block.chileancraft.tronco_de_espino_pelado": "Tronco De Espino",
"entity.chileancraft.jaiba": "Jaiba",
"item.chileancraft.marraqueta": "Marraqueta",
"item.chileancraft.moneda_de_100": "Moneda De 100",
"item.chileancraf [...]

2023-03-23 14:51 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "item.chilecraft_reworked.carne_de_caballo": "生马肉",
注释：L31，搜到的一个翻译是“蒜味麻辣醋”，而从外观和维基百科的解释来看更像是一种sauce而非vinegar；
L32，但是我没见过击杀马会掉落这个...

2023-03-23 14:53 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "item.chileancraft.bola_de_greda": "陶土球",
注释：L42，此物品是合成相关方块的原料

2023-03-23 14:58 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "item.chilecraft_reworked.pinones_de_oro": "金松子",
注释：L44，<code>oro</code>即西语“黄金”（隔壁Orokin就是用这个词和日语的kin（也是“黄金”意）合成的）；
L45，查无此物+1.

2023-03-23 15:02 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "itemGroup.tabchilecraft": "Chileancraft Foods",
注释：L88，生物群系的原文是<code>Araucanía</code>；
L89，查无此物+1

2023-03-23 15:02 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "block.chilecraft_reworked.tinaja_de_greda": "陶土瓮",
注释：L88，生物群系的原文是<code>Araucanía</code>；
L89，查无此物+1

2023-03-23 15:03 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "block.chileancraft.tomate_9": "Tomate ",
注释：L96，原文<code>Pañoleta</code>。

2023-03-23 15:05 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "block.chileancraft.parra_0": "葡萄藤",
注释：L200，在要不要加量词上做出的取舍（不是）

2023-03-23 15:06 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "item.chileancraft.semilla_de_aji_verde": "青椒种子",
注释：L284，但是游戏本体里已经有蒲公英了...

2023-03-23 15:07 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "block.chilecraft_reworked.mena_de_cobre_oxidado": "铜矿石",
注释：L291，该酒使用派斯葡萄酿造。

2023-03-23 15:08 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "block.chilecraft_reworked.choclo_8": "Choclo ",
注释：L363，原文<code>Añañuca</code>，一种智利植物。

2023-03-23 15:09 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "block.chilecraft_reworked.cebolla_2": "洋葱",
注释：L469，<code>pomaire</code>也是智利的城镇之一，以其陶艺而闻名。

2023-03-24 03:59 UTC, luoxueyasha commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "advancements.alabordaje.title": "上船吧，孩子!",
```suggestion
  "advancements.alabordaje.title": "上船吧，孩子！",
```

2023-03-24 03:59 UTC, luoxueyasha commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +{
建议用vscode排一遍原文和译文的键的顺序，选中→Ctrl+Shift+P→升序排列

2023-03-24 03:59 UTC, luoxueyasha commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "advancements.leche_papu_logro.descr": "适用于Papus",
这种在中文语言圈内没有对应文化元素的，可以酌情考虑用近似的内容替代（除非游戏内容相关）
例如原版进度`Return to Sender`（退还寄件人）→`见鬼去吧`

2023-03-24 06:00 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "advancements.leche_papu_logro.descr": "适用于Papus",
这个进度的名字是<code>Leche Papu, La leche de los papus</code>，是一个西语圈的meme但是我看不太明白。。。
这个meme相关的视频：https://www.youtube.com/watch?v=AdplMN7Sm9g

2023-03-24 07:01 UTC, luoxueyasha commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "advancements.leche_papu_logro.descr": "适用于Papus",
这里papu没有实意，主要是他的原梗创作者`tomiii 11`在西语圈很知名（下文称Tommy）
Tommy于2009年生人，于2020年～2021年间确诊脑癌，但自己并不知道自己得的是什么病
2021年，他开设了自己的油管频道并上传了不少自己玩mc的视频，并且很快爆火，获得了油管的1kw订阅奖杯（虽然视频质量也就只是一个普通12岁小孩的水平）
其中`leche papu`也是他提出来的虚构牛奶品牌，喝了能让人壮，这个梗在西语圈广泛传播，也有人后续做一些remix或者鬼畜
Tommy于2021年8月30日因病离世，享年12岁

至于Tommy的粉丝群体我没怎么考据，不太确定是否是正常人还是比较抽象，但是这个梗确实是西语Minecraft玩家群体中比较火的梗了

2023-03-24 07:04 UTC, luoxueyasha commented
记得把原文乱码和排列顺序改一下，这些mcr导致的问题是可以在这里的仓库中修复的

2023-03-24 10:00 UTC, CoalGlage commented
![杯子](https://user-images.githubusercontent.com/117024879/227490460-b20ce0cf-c616-43f2-b26d-b041c6f470be.png)
![花盆](https://user-images.githubusercontent.com/117024879/227490467-2b78e902-b957-4dba-979b-b2c4fd715786.png)
![浅盘](https://user-images.githubusercontent.com/117024879/227490470-83f96be3-1bfb-4b7e-8259-4e56bcdba773.png)
![砂锅](https://user-images.githubusercontent.com/117024879/227490474-3cff7b2b-c6ee-400b-9725-bea4b2e89a97.png)
![深盘](https://user-images.githubusercontent.com/117024879/227490479-45b30feb-5fc6-464d-a9b4-841e93485282.png)
![小瓮](https://user-images.githubusercontent.com/117024879/227490485-4867eb3b-53be-46f1-a9b7-3d95d4118190.png)
![小猪](https://user-images.githubusercontent.com/117024879/227490494-b0dcaea0-0900-4b18-9686-6cb68214fa00.png)
这些是本人摸索出的一些陶土物件的合成方式。需要用模组内的木工台。

2023-03-26 14:58 UTC, luoxueyasha requested changes

2023-03-26 14:58 UTC, luoxueyasha commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "advancements.alabordaje.title": "上船吧，孩子！",
```suggestion
  "advancements.alabordaje.title": "孩子们，登船！",
```
https://colegioingles.cl/arturo-prat-combate-naval-de-iquique-en-1879/
https://en.wikipedia.org/wiki/Arturo_Prat

该语句来源于智利将领Arturo Prat于硝石战争（War of the Pacific）中的遗言。

此外，你可能需要一本[西语词典](https://www.esdict.cn/)。西语和英语有很多近似的地方，例如原文的`muchachos`是`muchacho`的复数形式。

2023-03-27 01:44 UTC, luoxueyasha reviewed
文化冲击太大了，太难审了

2023-03-27 01:44 UTC, luoxueyasha commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "advancements.estamos_bien_los_33.title": "他大概33岁",
```suggestion
  "advancements.estamos_bien_los_33.title": "我们33个人都很好",
```
https://www.infobae.com/2010/10/12/1008539-33-el-numero-del-milagro-chileno/

2023-03-27 01:44 UTC, luoxueyasha commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "advancements.fundandopomaire.descr": "放置一台陶工车床",
```suggestion
  "advancements.fundandopomaire.descr": "放置一台陶轮",
```
https://es.wikipedia.org/wiki/Torno_de_alfarero

2023-03-27 01:44 UTC, luoxueyasha commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "advancements.fursuit.descr": "穿上全套的智利美洲狮套装",
```suggestion
  "advancements.fursuit.descr": "穿上一整套美洲狮盔甲",
```
不确定是`盔甲`还是`装备`，具体得看游戏贴图

2023-03-27 09:41 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "advancements.alabordaje.title": "上船吧，孩子！",
啊 ecsidt的话翻译的时候我倒是一直在用的

2023-03-27 14:25 UTC, luoxueyasha requested changes
文化捏他太多了，<s>我哪天翻翻智利大使馆的微博吧（</s>
翻过了，没啥有效信息
这个pr是不是可以用一下封存已久的`label:laborious`

2023-03-27 14:25 UTC, luoxueyasha commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "advancements.pisco_a_lo_macho.title": "给男人的皮斯可酒",
```suggestion
  "advancements.pisco_a_lo_macho.title": "感情深一口闷",
```
仅建议，修改了原意

2023-03-27 14:25 UTC, luoxueyasha commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "advancements.tikitikiti.descr": "穿上农民的衣服",
```suggestion
  "advancements.tikitikiti.descr": "打扮得像个乡下人一样",
```
```suggestion
  "advancements.tikitikiti.descr": "穿得像个养牛户一样",
```
`huaso`指牛户、马户、乡下人等
`tikitikiti`舞的装扮如下图
![image](https://user-images.githubusercontent.com/38830216/227967915-edde0602-5a1f-4da7-a27d-71ab3a902e3c.png)

2023-03-27 14:56 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "advancements.pisco_a_lo_macho.descr": "获得一瓶纯净的皮斯可酒",
好吧 这里确实是我的问题
游戏中的表现确实是喝下皮斯可酒（给予玩家防火20秒）。

2023-03-27 15:06 UTC, CoalGlage commented on projects/1.18/assets/chileancraft/chileancraft/lang/zh_cn.json
> +  "advancements.millonario.title": "百万富翁",
Soy MILLONARIO, tengo PALTAS...
按照机翻字幕，这个视频里有一句“只有百万富翁才能每天吃牛油果”...

2023-03-27 16:07 UTC, closed without merging