Wizarding World Of Harry Potter 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3169
Opened 2023-04-02 09:15 UTC by DrIceTea123

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

来自翻译请求，参见#2702 
语言文件为最新，1.18与1.19语言文件完全相同

2023-04-02 10:07 UTC, ChuijkYahus commented
推荐拉哈迷来审（）
咒语之类的翻译应该都是和译本对应的

2023-04-04 12:41 UTC, luoxueyasha requested changes
主参考源：
* 李爽主编. "哈利·波特百科全书". 北京理工大学出版社(2019).

副参考源：
* [哈利·波特维基](https://harrypotter.fandom.com/)
* [Harry Potter Wiki](https://harrypotter.fandom.com/)
* （英）J.K.罗琳著；马爱农，马爱新译.哈利·波特系列[M].北京：人民文学出版社,2021 
  * 下称`马版七部`（指《魔法石》～《死亡圣器》全7部8本）

又到了痛苦的“错译传千古，修订不被待见”环节了
除此之外，有不少马版七部内没有对应语料的，例如衍生小说啊前传啊后传啊衍生游戏啊，这个建议自行发挥

2023-04-04 12:41 UTC, luoxueyasha commented on projects/1.18/assets/ydms-wizarding-world-of-harry-potter/harrypotter/lang/zh_cn.json
> +"screen.harrypotter.spellbook": "法术书",
```suggestion
"screen.harrypotter.spellbook": "魔法书",
```
```suggestion
"screen.harrypotter.spellbook": "咒语书",
```
一般来说，哈利波特里不使用`法术`一词，而是用`符咒`或`魔咒`对应`spell`  
不过也没有太严格的对应关系，`魔法书`也是可以接受的

2023-04-04 12:41 UTC, luoxueyasha commented on projects/1.18/assets/ydms-wizarding-world-of-harry-potter/harrypotter/lang/zh_cn.json
> +"screen.harrypotter.accio": "飞来咒",
```suggestion
"screen.harrypotter.accio": "飞来飞去",
```
`Accio`仅作`飞来`，前（后）接名词；但如果将`Accio`视作咒文整体的话，就应当译作`飞来飞去`
例：`Accio Broomstick` = `扫帚飞来`

2023-04-04 12:41 UTC, luoxueyasha commented on projects/1.18/assets/ydms-wizarding-world-of-harry-potter/harrypotter/lang/zh_cn.json
> +"screen.harrypotter.ascendo": "上升咒",
槽点蛮多的
首先正确拼写应该是`Ascendio`
然后这是个咒文，不是咒语名，所以不能被翻译为`XX咒`
其次这个咒语只在第四部电影版里出现过，因此没有马版翻译
不过有个对应的`应声落地`（`Descendo`）可以考虑一下

2023-04-04 13:24 UTC, luoxueyasha requested changes

2023-04-04 13:24 UTC, luoxueyasha commented on projects/1.18/assets/ydms-wizarding-world-of-harry-potter/harrypotter/lang/zh_cn.json
> +"screen.harrypotter.accio.description": "将一个物品拉过来。",
```suggestion
"screen.harrypotter.accio.description": "将一个物品拉到施咒者旁。",
```
原文既然有`caster`，那么要译就全翻译了；L36的`自己`反而在人称上不统一

2023-04-04 13:24 UTC, luoxueyasha commented on projects/1.18/assets/ydms-wizarding-world-of-harry-potter/harrypotter/lang/zh_cn.json
> +"screen.harrypotter.avada_kedavra.description": "瞬间死亡。",
```suggestion
"screen.harrypotter.avada_kedavra.description": "令目标瞬间死亡。",
```
这里原文有“带来瞬间的死亡”的意思，但是实在不知道怎么润色
仅仅是“瞬间死亡”的话，感觉是对自己用/kill 一样

2023-04-04 13:24 UTC, luoxueyasha commented on projects/1.18/assets/ydms-wizarding-world-of-harry-potter/harrypotter/lang/zh_cn.json
> +"screen.harrypotter.expelliarmus.description": "缴械对手。",
```suggestion
"screen.harrypotter.expelliarmus.description": "缴械目标。",
```
其他地方都是`目标`，请全文统一

2023-04-04 13:24 UTC, luoxueyasha commented on projects/1.18/assets/ydms-wizarding-world-of-harry-potter/harrypotter/lang/zh_cn.json
> +"screen.harrypotter.mobilicorpus.description": "移动实体。",
```suggestion
"screen.harrypotter.mobilicorpus.description": "移动生物。",
```
这里原文不是`entities`，除非它能移动下落中的沙子（

2023-04-04 13:24 UTC, luoxueyasha commented on projects/1.18/assets/ydms-wizarding-world-of-harry-potter/harrypotter/lang/zh_cn.json
> +"entity.harrypotter.accio": "飞来咒",
这些同上
如果是`咒文内容`（要喊出来的中二语句），则不可以加`咒`
如果是`咒文名`（名称，或某些咒文召唤出来的咒文实体），则需要考察对应的咒文名

例如漂浮咒：
指这种咒语：`漂浮咒`
咏唱时的咒文：`羽加迪姆 勒维奥萨`
咒文产生的实体（如果有）：`漂浮咒` 或 `漂浮咒实体`

2023-04-04 13:32 UTC, luoxueyasha requested changes

2023-04-05 04:17 UTC, DrIceTea123 commented on projects/1.18/assets/ydms-wizarding-world-of-harry-potter/harrypotter/lang/zh_cn.json
> +"item.harrypotter.apprentice_wand": "学徒魔杖",
合成与贴图：
![image](https://user-images.githubusercontent.com/111784151/229979598-180ea53a-458c-45ed-81bf-44e97b10068a.png)
用途：
手持Apprentice Wand默认按B键进入战斗姿态（L72），可以开始施法；手持其他物品按B键没有任何反应

2023-04-05 04:21 UTC, DrIceTea123 commented on projects/1.18/assets/ydms-wizarding-world-of-harry-potter/harrypotter/lang/zh_cn.json
> +"screen.harrypotter.ascendo": "上升咒",
首先虽然缺了个i，但是实际效果确实是类似上升咒，效果是把自己 _弹射_ 上天，但是不免疫摔落伤害（只能对自己使用）
其次，游戏内这几行内容的表现形式如下：
![image](https://user-images.githubusercontent.com/111784151/229980103-5697a597-e301-4e7c-b3f4-660cbcf2cb1d.png)
是游戏内默认按H键打开咒语书（L73）的界面
依我个人所见应当是咒语名，其他地方也没有出现过这些行的内容（字幕里也没有）

2023-04-05 04:30 UTC, DrIceTea123 commented on projects/1.18/assets/ydms-wizarding-world-of-harry-potter/harrypotter/lang/zh_cn.json
> +"entity.harrypotter.patronus_deer": "守护神鹿",
![image](https://user-images.githubusercontent.com/111784151/229981351-88782045-611c-4671-936c-16a63f75bf68.png)
这个比较像什么（）

2023-04-05 04:35 UTC, DrIceTea123 commented on projects/1.18/assets/ydms-wizarding-world-of-harry-potter/harrypotter/lang/zh_cn.json
> +"screen.harrypotter.alarte_ascandare.description": "使目标迅速飞天。",
此处为L29（现用译名`烟消云散升天去`）的对应效果
效果等同于L10`Ascendo`，只不过这个是对其他生物使用的

2023-04-05 04:38 UTC, DrIceTea123 commented on projects/1.18/assets/ydms-wizarding-world-of-harry-potter/harrypotter/lang/zh_cn.json
> +"screen.harrypotter.avada_kedavra.description": "瞬间死亡。",
效果（源码）上来说确实类似/kill，是瞬间造成999点伤害
并且实测打生命值高于999的生物（测试用十万血铁傀儡）没有一击杀死

2023-04-05 04:42 UTC, DrIceTea123 commented on projects/1.18/assets/ydms-wizarding-world-of-harry-potter/harrypotter/lang/zh_cn.json
> +"screen.harrypotter.accio": "飞来咒",
但是实际效果来讲是打到什么就让什么`飞来`，所以`飞来飞去`应该不合适，不符合实际表现

2023-04-05 09:40 UTC, luoxueyasha commented on projects/1.18/assets/ydms-wizarding-world-of-harry-potter/harrypotter/lang/zh_cn.json
> +"screen.harrypotter.accio": "飞来咒",
实际上`飞来飞去`也是个传统错译了（因为没有`飞去`这部分）
我是坚持`飞来飞去`的，妥协一下的话`速速飞来`也可以

2023-04-05 09:43 UTC, luoxueyasha commented on projects/1.18/assets/ydms-wizarding-world-of-harry-potter/harrypotter/lang/zh_cn.json
> +"screen.harrypotter.ascendo": "上升咒",
那96行开始的那些是效果实体名？那还是根据原文写咒文吧
```suggestion
"screen.harrypotter.ascendo": "应声腾空",
```

2023-04-05 09:45 UTC, luoxueyasha commented on projects/1.18/assets/ydms-wizarding-world-of-harry-potter/harrypotter/lang/zh_cn.json
> +"screen.harrypotter.avada_kedavra.description": "瞬间死亡。",
```suggestion
"screen.harrypotter.avada_kedavra.description": "瞬间赐予死亡。",
```
```suggestion
"screen.harrypotter.avada_kedavra.description": "赐予瞬间的死亡。",
```
原文不加`目标`或相关描述的话，翻译时也可不加

2023-04-05 09:48 UTC, luoxueyasha commented on projects/1.18/assets/ydms-wizarding-world-of-harry-potter/harrypotter/lang/zh_cn.json
> +"screen.harrypotter.alarte_ascandare.description": "使目标迅速飞天。",
就原作来说：
`Ascendo`相当于将自己垂直lift起来
这玩意相当于将目标抬升/抬射上天

不过作为笑点的`迅速飞天`也太口语化了（

2023-04-05 09:49 UTC, luoxueyasha commented on projects/1.18/assets/ydms-wizarding-world-of-harry-potter/harrypotter/lang/zh_cn.json
> +"item.harrypotter.apprentice_wand": "学徒魔杖",
那就这样了

2023-04-05 09:52 UTC, luoxueyasha commented on projects/1.18/assets/ydms-wizarding-world-of-harry-potter/harrypotter/lang/zh_cn.json
> +"entity.harrypotter.patronus_deer": "守护神鹿",
这个没有角，是`牝鹿`
不过如果和玩家模型是steve还是alex有关就另说了（

2023-04-05 09:54 UTC, luoxueyasha commented on projects/1.18/assets/ydms-wizarding-world-of-harry-potter/harrypotter/lang/zh_cn.json
> +"screen.harrypotter.alarte_ascandare": "烟消云散升天去",
```suggestion
"screen.harrypotter.alarte_ascandare": "羽化升天",
```
仅作参考

2023-04-05 09:58 UTC, luoxueyasha commented on projects/1.18/assets/ydms-wizarding-world-of-harry-potter/harrypotter/lang/zh_cn.json
> +"screen.harrypotter.fire_storm": "火焰风暴",
```suggestion
"screen.harrypotter.fire_storm": "暴风骤炎",
```
仅做参考

2023-04-05 12:43 UTC, luoxueyasha approved these changes
![image](https://user-images.githubusercontent.com/38830216/230083715-ba4f1219-1137-44ef-830f-344806c3bb53.png)

2023-04-19 02:33 UTC, ChuijkYahus approved these changes

2023-04-20 11:56 UTC, merged