提交 simple-diving-gear 模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #3171
Opened 2023-04-02 13:59 UTC by sj19854825671

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-04-03 04:25 UTC, ChuijkYahus commented
/sort-keys projects/1.16/assets/spheric/spheric/lang/en_us.json

2023-04-03 13:15 UTC, ChuijkYahus requested changes
推荐将Spheric中的`Larks`改为`拉克斯`
这个蘑菇一样的树种和云雀应该没啥关系

2023-04-03 13:15 UTC, ChuijkYahus commented on projects/1.16/assets/spheric/spheric/lang/zh_cn.json
> +  "block.spheric.lar_pressure_plate": "拉尔压力板",
```suggestion
  "block.spheric.lar_pressure_plate": "拉尔木压力板",
```

2023-04-03 13:15 UTC, ChuijkYahus commented on projects/1.16/assets/spheric/spheric/lang/zh_cn.json
> +  "block.spheric.antreza_pressure_plate": "安特雷萨压力板",
```suggestion
  "block.spheric.antreza_pressure_plate": "安特雷萨木压力板",
```

2023-04-03 13:15 UTC, ChuijkYahus commented on projects/1.16/assets/spheric/spheric/lang/zh_cn.json
> +  "block.spheric.antreza_table": "安特雷萨桌子",
```suggestion
  "block.spheric.antreza_table": "安特雷萨木桌",
```

2023-04-03 13:15 UTC, ChuijkYahus commented on projects/1.16/assets/spheric/spheric/lang/zh_cn.json
> +  "block.spheric.lar_table": "拉尔桌子",
```suggestion
  "block.spheric.lar_table": "拉尔木桌",
```

2023-04-03 13:15 UTC, ChuijkYahus commented on projects/1.16/assets/spheric/spheric/lang/zh_cn.json
> +  "block.spheric.antreza_trap_door": "安特雷萨活板门",
```suggestion
  "block.spheric.antreza_trap_door": "安特雷萨木活板门",
```

2023-04-03 13:15 UTC, ChuijkYahus commented on projects/1.16/assets/spheric/spheric/lang/zh_cn.json
> +  "block.spheric.lar_trap_door": "拉尔活板门",
```suggestion
  "block.spheric.lar_trap_door": "拉尔木活板门",
```

2023-04-03 13:15 UTC, ChuijkYahus commented on projects/1.16/assets/spheric/spheric/lang/zh_cn.json
> +  "block.spheric.larkser_shroom": "云雀蘑菇",
```suggestion
  "block.spheric.larks_button": "拉克斯木按钮",
  "block.spheric.larks_chair": "拉克斯木椅",
  "block.spheric.larks_door": "拉克斯木门",
  "block.spheric.larks_fence_gate": "拉克斯木栅栏门",
  "block.spheric.larks_fence": "拉克斯木栅栏",
  "block.spheric.larks_log": "拉克斯原木",
  "block.spheric.larks_planks": "拉克斯木板",
  "block.spheric.larks_pressure_plate": "拉克斯木压力板",
  "block.spheric.larks_shroom_block": "拉克斯菇方块",
  "block.spheric.larks_slab": "拉克斯木台阶",
  "block.spheric.larks_stairs": "拉克斯木楼梯",
  "block.spheric.larks_table": "拉克斯木桌",
  "block.spheric.larks_trap_door": "拉克斯木活板门",
  "block.spheric.larks_vera": "拉克斯叶簇",
  "block.spheric.larks_vines": "拉克斯藤蔓",
  "block.spheric.larkser_shroom": "拉克斯菇",
```
`vera`疑似来自`Aloe vera`，aloe单独也用于称呼芦荟
可能是错将种加词vera（意为“真”）当做是叶簇的意思了吧（）
可根据实际形象改译

2023-04-03 13:15 UTC, ChuijkYahus commented on projects/1.16/assets/spheric/spheric/lang/zh_cn.json
> +  "item.spheric.ascenda_armor_boots": "阿桑达靴子",
这东西的矿石难道是反重力的？
~~居然一眼称为阿申达了（）~~

2023-04-05 15:59 UTC, sj19854825671 commented on projects/1.16/assets/spheric/spheric/lang/zh_cn.json
> +  "item.spheric.ascenda_armor_boots": "阿桑达靴子",
然而这玩意一点用没有，甚至不算矿石

2023-04-05 16:06 UTC, sj19854825671 commented on projects/1.16/assets/simple-diving-gear/simpledivegear/lang/zh_cn.json
> +    "item.simpledivegear.netherdivehelmetlighted": "熔岩潜水头盔（前照灯）",
是的但是我认为这样会过于复杂

2023-04-05 16:20 UTC, sj19854825671 commented
> 合作

如何结束

2023-04-05 16:33 UTC, ChuijkYahus approved these changes

2023-04-09 07:29 UTC, merged