Dimensional Doors 1.19 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3177
Opened 2023-04-04 09:52 UTC by CharamitasSaMa

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-04-04 10:39 UTC, ChuijkYahus reviewed
这没翻译完吧

一般检查单不需勾选第四项

2023-04-17 07:46 UTC, ChuijkYahus commented
* 7+7时限进入第二阶段，请注意查看剩余未翻译条目进行翻译，如选择不翻译请给出理由

@CharamitasSaMa

2023-04-17 07:52 UTC, ChuijkYahus requested changes

2023-04-17 07:52 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "block.dimdoors.white_fabric": "白色染色变化之壁",
```suggestion
  "block.dimdoors.white_fabric": "白色变化之壁",
```
原文没有`Stained`，请注意全局修改

2023-04-17 07:52 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "block.dimdoors.wood_dimensional_trapdoor": "橡木次元活板门",
```suggestion
  "block.dimdoors.iron_dimensional_door": "铁质维度门",
  "block.dimdoors.gold_dimensional_door": "金质维度门",
  "block.dimdoors.quartz_dimensional_door": "私人维度门",
  "block.dimdoors.unstable_dimensional_door": "不稳定维度门",
  "block.dimdoors.oak_dimensional_door": "橡木维度门",
  "block.dimdoors.wood_dimensional_trapdoor": "橡木维度活板门",
```
根据库内1122同模组修改，请全文通查

2023-04-17 07:52 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "block.dimdoors.dimensional_portal": "次元传送门",
```suggestion
  "block.dimdoors.dimensional_portal": "维度传送门",
```
请全文通查

2023-04-17 07:52 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "item.dimdoors.creepy_record.desc": "诡异之声-次元监牢的回响",
```suggestion
  "item.dimdoors.creepy_record.desc": "Creepy - The sound of Limbo",
```
歌曲名不需翻译

2023-04-17 07:52 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "biome.dimdoors.white_void": "私人口袋次元空岛（纯白色虚空）",
与原文括号内外相反

2023-04-19 19:49 UTC, CharamitasSaMa reviewed
已修正所有问题
已为全部配置文件添加汉化

2023-04-19 19:58 UTC, CharamitasSaMa commented
> * 7+7时限进入第二阶段，请注意查看剩余未翻译条目进行翻译，如选择不翻译请给出理由
> 
> @CharamitasSaMa



> * 7+7时限进入第二阶段，请注意查看剩余未翻译条目进行翻译，如选择不翻译请给出理由
> 
> @CharamitasSaMa

因为不明原因上周无法登入Github网页编辑器，现已全部修复

2023-04-19 19:59 UTC, CharamitasSaMa commented
因为不明原因上周无法登入Github网页编辑器，现已全部修正
@ChuijkYahus

2023-04-20 02:26 UTC, luoxueyasha requested changes
部分问题仅指出一处，请全文通查

2023-04-20 02:26 UTC, luoxueyasha commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "dimdoors.virtualTarget.dimdoors.id_marker": "Id标记",
这里的`Id`指？

2023-04-20 02:26 UTC, luoxueyasha commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "rifts.destinations.escape.cannot_escape_limbo": "很好的尝试，但你必须找到永恒源质才能逃离维度监牢",
```suggestion
  "rifts.destinations.escape.cannot_escape_limbo": "想的挺不错，但你必须找到永恒源质才能逃离维度监牢",
```
`Nice try`实际是一种对失败情况的反讽

2023-04-20 02:26 UTC, luoxueyasha commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "rifts.destinations.escape.did_not_use_rift": "你没有使用维度门或裂痕离开口袋维度，所以你坠入了维度监牢!",
```suggestion
  "rifts.destinations.escape.did_not_use_rift": "你没有使用维度门或裂痕离开口袋维度，你坠入了维度监牢!",
```
```suggestion
  "rifts.destinations.escape.did_not_use_rift": "因为没有使用维度门或裂痕离开口袋维度，你坠入了维度监牢!",
```
一个句子里同时出现两个`你`（特别是游戏里的`You`一般有虚指成分）实在太怪了

2023-04-20 02:26 UTC, luoxueyasha commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "text.autoconfig.dimdoors.option.doors.doorList.mode.@Tooltip": "启用：仅生成这些维度门对应的变种维度，禁用：禁止生成这些维度门对应的变种维度。",
上文为`启用时`，此处为`启用`，请保持统一
此外，启用/禁用之间的句子由于是并列关系，应该用分号割开
```suggestion
  "text.autoconfig.dimdoors.option.doors.doorList.mode.@Tooltip": "启用：仅生成这些维度门对应的变种维度；禁用：禁止生成这些维度门对应的变种维度。",
```

2023-04-20 02:26 UTC, luoxueyasha commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "text.autoconfig.dimdoors.option.doors.placeRiftsInCreativeMode": "创造模式裂痕生成",
```suggestion
  "text.autoconfig.dimdoors.option.doors.placeRiftsInCreativeMode": "创造模式下生成裂痕",
```
经典的口语倒装（

2023-04-20 02:26 UTC, luoxueyasha commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "text.autoconfig.dimdoors.option.pockets.maxPocketSize.@Tooltip": "设置全部口袋维度的最大房间大小。若数值为x，则大小为(x + 1) * (x + 1) 区块.",
```suggestion
  "text.autoconfig.dimdoors.option.pockets.maxPocketSize.@Tooltip": "设置全部口袋维度的最大房间大小。若数值为x，则大小为(x + 1) * (x + 1) 区块。",
```
若要往句子后面加句号，则请全文统一

2023-04-20 02:26 UTC, luoxueyasha commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "text.autoconfig.dimdoors.option.pockets.privatePocketSize.@Tooltip": "设置新生成的私人口袋维度的空间大小。如果此数值大于“最大口袋维度大小”，则将会按照”最大口袋维度大小“来处理",
```suggestion
  "text.autoconfig.dimdoors.option.pockets.privatePocketSize.@Tooltip": "设置新生成的私人口袋维度的空间大小。如果此数值大于“最大口袋维度大小”，则将会按照“最大口袋维度大小”来处理",
```
引号反了，可以考虑换个字体，方便检查

2023-04-20 02:26 UTC, luoxueyasha commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "text.autoconfig.dimdoors.option.pockets.publicPocketSize.@Tooltip": "设置新生成的私人口袋维度的空间大小。如果此数值大于“私人口袋维度大小”，则将会按照”私人口袋维度大小“来处理",
```suggestion
  "text.autoconfig.dimdoors.option.pockets.publicPocketSize.@Tooltip": "设置新生成的私人口袋维度的空间大小。如果此数值大于“私人口袋维度大小”，则将会按照“私人口袋维度大小”来处理",
```

2023-04-20 02:26 UTC, luoxueyasha commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "dimdoors.pocket.pocketHasBeenDyed": "此口袋维度已被为%s。",
？

2023-04-20 02:26 UTC, luoxueyasha commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "argument.dimdoors.schematic.invalidNamespace": "未知的结构命名空间，应为%s中的一个，找到于%s。",
实际游戏内显示？

2023-04-20 02:26 UTC, luoxueyasha commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "dimdoors.advancement.dark_ostiology": "逃出生天",
原文直译为`暗黑骨学`，能解释一下原文在游戏中有什么实际联系吗

2023-04-20 02:26 UTC, luoxueyasha commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "dimdoors.advancement.darklight": "暗光源",
疑似参考https://www.imdb.com/title/tt0395512/

2023-04-20 02:26 UTC, luoxueyasha commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "dimdoors.advancement.home_away_from_home": "离家很远的家",
```suggestion
  "dimdoors.advancement.home_away_from_home": "另一个家",
```
```suggestion
  "dimdoors.advancement.home_away_from_home": "家外之家",
```
俚语

2023-04-20 02:26 UTC, luoxueyasha commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "dimdoors.advancement.world_unfurled": "世界崩解",
原文`World Unfurled`，疑似参考空间折叠理论
具体需要参考`破碎之壁`的生成与获取方法

2023-04-20 02:26 UTC, luoxueyasha commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "biome.dimdoors.white_void": "纯白色虚空（私人口袋维度空间）",
存在这之外的`白色虚空`吗？

2023-04-20 02:26 UTC, luoxueyasha commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.fell.accident.ladder": "%1$s从梯子上摔了下来，并且坠入了维度监牢",
```suggestion
  "limbo.death.fell.accident.ladder": "%1$s从梯子上摔了下来，并坠入了维度监牢",
```
```suggestion
  "limbo.death.fell.accident.ladder": "%1$s从梯子上摔入了维度监牢",
```
总之无论怎么翻译，请保证上下统一；并参考https://minecraft.fandom.com/zh/wiki/%E6%AD%BB%E4%BA%A1%E6%B6%88%E6%81%AF

2023-04-20 03:22 UTC, CharamitasSaMa commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "biome.dimdoors.white_void": "纯白色虚空（私人口袋维度空间）",
不存在，此维度仅用于生成私人口袋空间

2023-04-20 11:25 UTC, CharamitasSaMa commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "dimdoors.advancement.dark_ostiology": "逃出生天",
无实际联系，此成就获取方式是使用“橡木维度门”逃离“地牢维度空间/黑色虚空”获得

2023-04-20 11:38 UTC, ChuijkYahus requested changes
死亡消息可以参照下这个
https://minecraft.fandom.com/zh/wiki/%E6%AD%BB%E4%BA%A1%E6%B6%88%E6%81%AF

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "item.dimdoors.world_thread_chestplate": "世界纤维织物外套",
这里原文采用了原版`铁头盔` `铁胸甲` `铁护腿` `铁靴子`的命名，推荐依照原文
如需采用原版`皮革帽子` `皮革外套` `皮革裤子` `皮革靴子`也请将靴子一条进行修改

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "block.dimdoors.iron_dimensional_door.info0": "放置在裂痕核心下方的方块",
```suggestion
  "block.dimdoors.iron_dimensional_door.info0": "放置在裂痕核心下方的方块上",
```
感觉读起来顺一点（）

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "block.dimdoors.dungeon_door.info0": "放置在裂痕核心下方的方块",
```suggestion
  "block.dimdoors.dungeon_door.info0": "放置在裂痕核心下方的方块上",
```
同上

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "block.dimdoors.iron_dimensional_door.info1": "以进入裂痕对应的地方",
```suggestion
  "block.dimdoors.iron_dimensional_door.info1": "以激活此裂痕",
```
原文大概是这个意思
这里是按照实际表现翻译的吗

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "item.dimdoors.mask_shard": "Mask Shard",
这两条是

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "item.dimdoors.dimensional_eraser.desc": "瞬间擦除生物，不会掉落任何物品。§8§n轰炸空间！",
```suggestion
  "item.dimdoors.dimensional_eraser.desc": "瞬间抹除生物",
```
依照原文

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "commands.dimteleport.usage": "/dimteleport <维度> <x> <y> <z> [左右角度] [上下角度]",
```suggestion
  "commands.dimteleport.usage": "/dimteleport <维度> <x> <y> <z> [水平角度] [垂直角度]",
```
看游戏内实际表现

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "commands.generic.dimdoors.not_in_pocket_dim": "你只能在口袋维度维度使用此命令",
```suggestion
  "commands.generic.dimdoors.not_in_pocket_dim": "你只能在口袋维度中使用此命令",
```

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "commands.generic.unknownValue": "错误：未知的值'%s'",
```suggestion
  "commands.generic.unknownValue": "错误：未知值“%s”",
```

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "commands.pocket.unknownPocketTemplate": "错误：未知的模板'%s'",
```suggestion
  "commands.pocket.unknownPocketTemplate": "错误：未知模板“%s”",
```

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "commands.pocket.placedSchem": "已放置口袋维度模板%s于%s位置，维度%s",
```suggestion
  "commands.pocket.placedSchem": "已将口袋维度模板%1$s放置于维度%3$s内%2$s处",
```

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "commands.pocket.loadedSchem": "已加载口袋维度模板%s至剪贴板，使用//paste粘贴",
```suggestion
  "commands.pocket.loadedSchem": "已将口袋维度模板%s加载至剪贴板，使用//paste粘贴",
```

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "commands.pocket.log.creation.off": "已禁用口袋维度创建日志.",
```suggestion
  "commands.pocket.log.creation.off": "已禁用口袋维度创建日志",
```

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "commands.pocket.log.creation.generating": "从'%s'模板生成口袋维度于位置 %s %s %s",
```suggestion
  "commands.pocket.log.creation.generating": "正于位置%2$s %3$s %4$s处依照“%1$s”模板生成口袋维度",
```

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "rifts.destinations.private_pocket_exit.rift_has_closed": "用于进入口袋维度的裂痕已经关闭，所以你坠入了维度监牢!",
```suggestion
  "rifts.destinations.escape.did_not_use_rift": "因为没有使用维度门或裂痕离开口袋维度，你坠入了维度监牢！",
  "rifts.destinations.escape.rift_has_closed": "由于用于进入口袋维度的裂痕已经关闭，你坠入了维度监牢！",
  "rifts.destinations.private_pocket_exit.did_not_use_rift": "你没有使用维度门或裂痕离开口袋维度，所以你坠入了维度监牢！",
  "rifts.destinations.private_pocket_exit.rift_has_closed": "用于进入口袋维度的裂痕已经关闭，所以你坠入了维度监牢！",
```
请使用全角标点符号，请全文通查

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "dimdoors.advancement.dark_ostiology": "逃出生天",
骨学是`Osteology`
这里疑似用“门径、孔洞”（ostium）加上-logy强行造出来的词汇
不过具体是不是这样还得看作者

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "dimdoors.advancement.world_unfurled": "崩坏的维度……",
原文此处并无省略号，是为了表现某种风格吗

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.cactus": "%1$s被仙人掌扎的昏了过去，醒来后发现自己处于维度监牢",
```suggestion
  "limbo.death.attack.cactus": "%1$s被仙人掌扎得昏了过去，醒来后发现自己处于维度监牢",
```
的地得警察出警（）

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.sweetBerryBush.player": "%1$s在试图逃离%2$s时被浆果丛缠进了维度监牢",
```suggestion
  "limbo.death.attack.sweetBerryBush": "%1$s被甜浆果丛缠进了维度监牢",
  "limbo.death.attack.sweetBerryBush.player": "%1$s在试图逃离%2$s时被甜浆果丛缠进了维度监牢",
```

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "text.autoconfig.dimdoors.option.general.depthSpreadFactor.@Tooltip": "逃离口袋维度或维度监牢后Y轴的扩散范围, 单位为方块/深度。次元监牢的默认深度为50。",
```suggestion
  "text.autoconfig.dimdoors.option.general.depthSpreadFactor.@Tooltip": "逃离口袋维度或维度监牢后Y轴的扩散范围, 以格每单位深度计。次元监牢的默认深度为50。",
```
所有未指出处需统一单位说明格式

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "text.autoconfig.dimdoors.option.general.riftCloseSpeed.@Tooltip": "在使用裂痕移除器之后裂痕闭合的速度，以每个游戏刻的裂痕大小为单位。",
```suggestion
  "text.autoconfig.dimdoors.option.general.riftCloseSpeed.@Tooltip": "在使用裂痕移除器之后裂痕闭合的速度，以单位裂痕大小每游戏刻。",
```
类似m/s吧

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "text.autoconfig.dimdoors.option.doors.doorList.doors.@Tooltip": "可用于制作维度门的门类方块的ID列表。如果一个门类物品的物品id和方块id不对应，可手动在此添加。",
```suggestion
  "text.autoconfig.dimdoors.option.doors.doorList.doors.@Tooltip": "可用于制作维度门的门类方块的ID列表。如果一个门类物品的物品ID和方块ID不对应，可手动在此添加。",
```

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "text.autoconfig.dimdoors.option.pockets.maxPocketSize.@Tooltip": "设置全部口袋维度的最大房间大小。若数值为x，则大小为(x + 1) * (x + 1) 区块。",
```suggestion
  "text.autoconfig.dimdoors.option.pockets.maxPocketSize.@Tooltip": "设置全部口袋维度的最大房间大小。若数值为x，则大小为(x + 1) * (x + 1)区块。",
```
表达式中间的空格就留着吧

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "text.autoconfig.dimdoors.option.pockets.defaultWeightEquation.@Tooltip": "当口袋生成器json中有不存在/无效的权重方程时，设置用于计算权重的方程。",
```suggestion
  "text.autoconfig.dimdoors.option.pockets.defaultWeightEquation.@Tooltip": "当口袋生成器json中没有或仅有无效的权重方程时，设置用于计算权重的方程。",
```

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "dimdoors.pocket.remainingNeededDyes": "此口袋维度需要%s/%s个染料才能被为%s。",
```suggestion
  "dimdoors.pocket.remainingNeededDyes": "此口袋维度已吸收%s/%s个染料才能被染为%s。",
```

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "command.dimdoors.schematicv2.unknownSchematic": "未知的结构\"%s\"于命名空间\"%s\"。",
```suggestion
  "command.dimdoors.schematicv2.unknownSchematic": "未知命名空间“%2$s”中结构“%1$s”。",
```

2023-04-20 11:38 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "argument.dimdoors.schematic.invalidNamespace": "未知的结构命名空间，应为%s中%s的一个。",
```suggestion
  "argument.dimdoors.schematic.invalidNamespace": "未知的结构命名空间，应为%s中的一个，实际则是%s。",
```

2023-04-20 11:47 UTC, CharamitasSaMa commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "item.dimdoors.mask_shard": "Mask Shard",
创造物品栏无法找到，且无实际用途，疑似为未完成物品

2023-04-20 11:51 UTC, CharamitasSaMa commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "item.dimdoors.world_thread_chestplate": "世界纤维织物外套",
此物品合成配方需要皮革套装，故作此更改

2023-04-20 11:55 UTC, CharamitasSaMa commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "dimdoors.autogen_item_prefix": "%s制成的维度门",
实际表现以白桦木举例，为“Dimensional 白桦木门”，若更改为%s维度门，则将会变为“白桦木门维度门”

2023-04-20 11:56 UTC, CharamitasSaMa commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "block.dimdoors.detached_rift": "裂痕气泡",
无实际体现，已删除

2023-04-20 11:57 UTC, CharamitasSaMa commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "block.dimdoors.eternal_fluid": "永恒源质",
block.dimdoors.rift在游戏内并无对应的方块，故删除

2023-04-20 11:58 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "dimdoors.autogen_item_prefix": "%s制成的维度门",
作者奇妙命名了属于是
自己都是写的`Oak Dimensional Door`

2023-04-20 12:11 UTC, CharamitasSaMa commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "dimdoors.advancement.world_unfurled": "崩坏的维度……",
表达维度监牢的荒凉，想了下还是算了

2023-04-20 12:11 UTC, CharamitasSaMa commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "dimdoors.advancement.dark_ostiology": "逃出生天",
此外，此成就可通过进入自然生成的门获得，故修改其注释

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "text.autoconfig.dimdoors.option.general.teleportOffset.@Tooltip": "传送后玩家距离次元门的距离（以方块为单位）。",
```suggestion
  "text.autoconfig.dimdoors.option.general.riftCloseSpeed.@Tooltip": "在使用裂痕移除器之后裂痕闭合的速度，以单位裂痕大小每游戏刻计。",
  "text.autoconfig.dimdoors.option.general.riftGrowthSpeed": "裂痕成长速度",
  "text.autoconfig.dimdoors.option.general.riftGrowthSpeed.@Tooltip": "裂痕扩大的速度，以单位裂痕大小每游戏刻计。",
  "text.autoconfig.dimdoors.option.general.teleportOffset": "传送修正",
  "text.autoconfig.dimdoors.option.general.teleportOffset.@Tooltip": "传送后玩家距离次元门的距离，以格计。",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "text.autoconfig.dimdoors.option.pockets.pocketGridSize.@Tooltip": "设置口袋维度的房间生成间隔，单位为区块（16方块）。",
```suggestion
  "text.autoconfig.dimdoors.option.pockets.pocketGridSize.@Tooltip": "设置口袋维度的房间生成间隔，以区块（16格）计。",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "dimdoors.pocket.remainingNeededDyes": "此口袋维度已吸收%s/%s个染料才能被染为%s。",
```suggestion
  "dimdoors.pocket.remainingNeededDyes": "此口袋维度需吸收%2$s个染料（已吸收%1$s个）才能被染为%3$s。",
```
```suggestion
  "dimdoors.pocket.remainingNeededDyes": "此口袋维度染为%3$s染料吸收进度：%1$s/%2$s。",
```
总感觉哪里不对（）

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.fell.accident.other_climbable": "%1$s在攀爬时失足摔入了维度监牢",
```suggestion
  "limbo.death.fell.accident.other_climbable": "%1$s在攀爬时摔入了维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.fell.finish.item": "%1$s摔成了重伤并且被%2$s使用%3$s送进了维度监牢",
```suggestion
  "limbo.death.fell.finish": "%1$s摔伤得太重并被%2$s送进了维度监牢",
  "limbo.death.fell.finish.item": "%1$s摔伤得太重并被%2$s用%3$s送进了维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.onFire.player": "%1$s在与%2$s战斗时重度烧伤，醒来后发现自己处于维度监牢",
```suggestion
  "limbo.death.attack.onFire": "%1$s被烤的酥脆，醒来后发现自己处于维度监牢",
  "limbo.death.attack.onFire.player": "%1$s在与%2$s战斗时被烤的酥脆，醒来后发现自己处于维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.inFire.player": "%1$s在与%2$s战斗时不慎走入了火中并升入了维度监牢",
```suggestion
  "limbo.death.attack.inFire.player": "%1$s在与%2$s战斗时踏入了火中并升入了维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.lava.player": "%1$s逃离%2$s时试图在熔岩里游泳并沉入了维度监牢",
```suggestion
  "limbo.death.attack.lava.player": "%1$s在逃离%2$s时试图在熔岩里游泳并沉入了维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.hotFloor.player": "%1$s在与%2$s战斗时走入了危险区域并沉入了维度监牢",
```suggestion
  "limbo.death.attack.hotFloor.player": "%1$s因%2$s而步入危险之地并沉入了维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.inWall.player": "%1$s因为%2$s卡进了维度监牢",
```suggestion
  "limbo.death.attack.inWall": "%1$s卡进了维度监牢",
  "limbo.death.attack.inWall.player": "%1$s在与%2$s战斗时卡进了维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.cramming.player": "%1$s被%2$s砸进了维度监牢",
```suggestion
  "limbo.death.attack.cramming": "%1$s因被过度挤压而被送入了维度监牢",
  "limbo.death.attack.cramming.player": "%1$s被%2$s挤扁而被送入了维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.drown.player": "%1$s在与%2$s战斗时溺水了并沉入了维度监牢",
```suggestion
  "limbo.death.attack.drown": "%1$s淹死了并沉入了维度监牢",
  "limbo.death.attack.drown.player": "%1$s在试图逃离%2$s时淹死了并沉入了维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.cactus.player": "%1$s在与%2$s战斗时一头撞进了仙人掌丛，醒来后发现自己处于维度监牢",
```suggestion
  "limbo.death.attack.cactus": "%1$s撞上了仙人掌，醒来后发现自己处于维度监牢",
  "limbo.death.attack.cactus.player": "%1$s在试图逃离%2$s时撞上了仙人掌，醒来后发现自己处于维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.even_more_magic": "%1$s被巨量的魔法淹没了，醒来后发现自己处于维度监牢",
```suggestion
  "limbo.death.attack.even_more_magic": "%1$s被不为人知的魔法淹没了，醒来后发现自己处于维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.fallingBlock.player": "%1$s在与%2$s战斗时被坠落的方块砸进了维度监牢",
```suggestion
  "limbo.death.attack.fallingBlock": "%1$s被下落的方块砸进了维度监牢",
  "limbo.death.attack.fallingBlock.player": "%1$s在与%2$s战斗时被下落的方块砸进了维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.stalagmite.player": "%1$s在与%2$s战斗时摔在了滴水石锥上，穿越进了维度监牢",
```suggestion
  "limbo.death.attack.stalagmite": "%1$s摔在了石笋上，穿越进了维度监牢",
  "limbo.death.attack.stalagmite.player": "%1$s在与%2$s战斗时摔在了石笋上，穿越进了维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.arrow.item": "%1$s被%2$s使用%3$s射进了维度监牢",
```suggestion
  "limbo.death.attack.mob.item": "%1$s被%2$s用%3$s送进了维度监牢",
  "limbo.death.attack.player": "%1$s被%2$s送进了维度监牢",
  "limbo.death.attack.player.item": "%1$s被%2$s用%3$s送进了维度监牢",
  "limbo.death.attack.arrow": "%1$s被%2$s射进了维度监牢",
  "limbo.death.attack.arrow.item": "%1$s被%2$s用%3$s射进了维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.fireball.item": "%1$s被%2$s使用%3$s发射的火球炸进了维度监牢",
```suggestion
  "limbo.death.attack.fireball.item": "%1$s被%2$s用%3$s发射的火球炸进了维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.thrown.item": "%1$s被%2$s使用%3$s砸进了维度监牢",
```suggestion
  "limbo.death.attack.thrown.item": "%1$s被%2$s用%3$s砸进了维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.indirectMagic.item": "%1$s被%2$s使用%3$s施放的魔法送进了维度监牢",
```suggestion
  "limbo.death.attack.indirectMagic.item": "%1$s被%2$s用%3$s送进了维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.trident.item": "%1$s被%2$s使用%3$s叉进了维度监牢",
```suggestion
  "limbo.death.attack.trident.item": "%1$s被%2$s用%3$s叉进了维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.outOfWorld": "%1$s坠入了维度监牢",
```suggestion
  "limbo.death.attack.outOfWorld": "%1$s掉入了维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.dragonBreath.player": "%1$s被%2$s的龙息重度烧伤，醒来后发现自己处于维度监牢",
```suggestion
  "limbo.death.attack.dragonBreath": "%1$s被龙息烤熟了，醒来后发现自己处于维度监牢",
  "limbo.death.attack.dragonBreath.player": "%1$s被%2$s的龙息烤熟了，醒来后发现自己处于维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.fireworks.item": "%1$s被%2$s使用%3$s发射的烟花炸进了维度监牢",
```suggestion
  "limbo.death.attack.fireworks.item": "%1$s随着%2$s用%3$s发射的烟花发出的巨响进入了维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.badRespawnPoint.message": "%1$s因为%2$s注定要进入维度监牢",
```suggestion
  "limbo.death.attack.badRespawnPoint.message": "%1$s被%2$s送入了维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.sweetBerryBush": "%1$s被甜果丛缠进了维度监牢",
```suggestion
  "limbo.death.attack.sweetBerryBush": "%1$s被甜浆果丛缠进了维度监牢",
```

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.sting.player": "%1$s被%2$s蜂号了并且扔进了维度监牢",
```suggestion
  "limbo.death.attack.sting": "%1$s被蛰昏了并被扔进了维度监牢",
  "limbo.death.attack.sting.player": "%1$s被%2$s蛰昏了并被扔进了维度监牢",
```
原文的bugged确实难翻

2023-04-20 12:51 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "limbo.death.attack.freeze.player": "%1$s在与%2$s战斗时被冰封了，我们在维度监牢发现了ta",
```suggestion
  "limbo.death.attack.freeze.player": "%1$s被%2$s冰封了，我们在维度监牢发现了ta",
```

2023-04-20 15:10 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "block.dimdoors.silver_ancient_fabric": "浅灰色远古之壁",
```suggestion
  "block.dimdoors.light_blue_ancient_fabric": "淡蓝色远古之壁",
  "block.dimdoors.yellow_ancient_fabric": "黄色远古之壁",
  "block.dimdoors.lime_ancient_fabric": "黄绿色远古之壁",
  "block.dimdoors.pink_ancient_fabric": "粉红色远古之壁",
  "block.dimdoors.gray_ancient_fabric": "灰色远古之壁",
  "block.dimdoors.silver_ancient_fabric": "淡灰色远古之壁",
```

2023-04-20 15:10 UTC, ChuijkYahus commented on projects/1.19/assets/dimensional-doors/dimdoors/lang/zh_cn.json
> +  "dimdoors.pocket.remainingNeededDyes": "此口袋维度染为%3$s染料吸收进度：%1$s/%2$s。",
```suggestion
  "dimdoors.pocket.remainingNeededDyes": "将此口袋维度染为%3$s的染料吸收进度：%1$s/%2$s。",
```
超级乱改

2023-04-21 01:30 UTC, ChuijkYahus approved these changes

2023-04-22 09:29 UTC, merged