iron-shulker-boxes 翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #3180
Opened 2023-04-05 09:03 UTC by wywllin

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2023-04-05 10:01 UTC, A-Black-Fish commented
请更新标题为“Iron Shulker Boxes 翻译提交”

2023-04-05 12:58 UTC, luoxueyasha requested changes
部分问题仅指出一处，请全文通查

2023-04-05 12:58 UTC, luoxueyasha commented on projects/1.16/assets/iron-shulker-boxes/ironshulkerbox/lang/zh_cn.json
> +    "_comment": "铁",
`_comment`如果不在游戏内显示的话，不需要翻译

2023-04-05 12:58 UTC, luoxueyasha commented on projects/1.16/assets/iron-shulker-boxes/ironshulkerbox/lang/zh_cn.json
> +    "block.ironshulkerbox.iron_shulker_box_pink": "粉色铁质潜影盒",
```suggestion
    "block.ironshulkerbox.iron_shulker_box_pink": "粉红色铁质潜影盒",
```

2023-04-05 12:58 UTC, luoxueyasha commented on projects/1.16/assets/iron-shulker-boxes/ironshulkerbox/lang/zh_cn.json
> +    "ironshulkerbox.upgrade.tooltip": "用于将 %s 潜影盒升级为 %s 潜影盒.",
上文为`升级成`，请全文统一

2023-04-05 12:58 UTC, luoxueyasha commented on projects/1.16/assets/iron-shulker-boxes/ironshulkerbox/lang/zh_cn.json
> +    "ironshulkerbox.color.tooltip": "潜影盒的颜色保持不变",
```suggestion
    "ironshulkerbox.color.tooltip": "潜影盒的颜色将保持不变",
```
加个介词的话读起来会好一点

2023-04-05 16:14 UTC, mamaruo requested changes
部分建议仅提出一处，请连带修改其他

2023-04-05 16:14 UTC, mamaruo commented on projects/1.16/assets/iron-shulker-boxes/ironshulkerbox/lang/zh_cn.json
> +    "block.ironshulkerbox.iron_shulker_box_green": "深绿色铁质潜影盒",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |

原文：**Lime Iron Shulker Box┃……┃Green Iron Shulker Box**
```suggestion
    "block.ironshulkerbox.iron_shulker_box_lime": "黄绿色铁质潜影盒",
    "block.ironshulkerbox.iron_shulker_box_pink": "粉红色铁质潜影盒",
    "block.ironshulkerbox.iron_shulker_box_gray": "灰色铁质潜影盒",
    "block.ironshulkerbox.iron_shulker_box_light_gray": "淡灰色铁质潜影盒",
    "block.ironshulkerbox.iron_shulker_box_cyan": "青色铁质潜影盒",
    "block.ironshulkerbox.iron_shulker_box_purple": "紫色铁质潜影盒",
    "block.ironshulkerbox.iron_shulker_box_blue": "蓝色铁质潜影盒",
    "block.ironshulkerbox.iron_shulker_box_brown": "棕色铁质潜影盒",
    "block.ironshulkerbox.iron_shulker_box_green": "绿色铁质潜影盒",
```

原版16色名。原版名词请严格遵照原版译法：[译名标准化](https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96)

2023-04-05 16:14 UTC, mamaruo commented on projects/1.16/assets/iron-shulker-boxes/ironshulkerbox/lang/zh_cn.json
> +    "item.ironshulkerbox.iron_to_gold_shulker_box_upgrade": "将铁质潜影盒升级成金质潜影盒",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |

原文：**Iron to Gold Shulker Box Upgrade**
```suggestion
    "item.ironshulkerbox.iron_to_gold_shulker_box_upgrade": "潜影盒升级：铁-金",
```
```suggestion
    "item.ironshulkerbox.iron_to_gold_shulker_box_upgrade": "潜影盒升级：铁->金",
```
```suggestion
    "item.ironshulkerbox.iron_to_gold_shulker_box_upgrade": "潜影盒升级：铁>金",
```

2023-04-05 16:14 UTC, mamaruo commented on projects/1.16/assets/iron-shulker-boxes/ironshulkerbox/lang/zh_cn.json
> +    "itemGroup.ironshulkerbox": "更多潜影盒"
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |

原文：**Iron Shulker Boxes**
```suggestion
    "itemGroup.ironshulkerbox": "Iron Shulker Boxes"
```
与 Iron Chests 一样，存在争议

2023-04-05 16:14 UTC, mamaruo commented on projects/1.16/assets/iron-shulker-boxes/ironshulkerbox/lang/zh_cn.json
> +    "_comment": "项目组",
| **审查级别**   | **备注** |
|-------------|--------|
| 🔴 严重 / **阻止合并，刻不容缓** |   /   |

原文：**Item Groups**
```suggestion
    "_comment": "Item Groups",
```
不会译咱就别译

2023-04-06 16:02 UTC, mamaruo requested changes
### 部分建议仅提出一处，请连带修改其他

详情见上，包括色名和升级物品的名字

该 comment 提到的问题仍未修改：https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/3180#issuecomment-1497230531。conversation 的修改在“**右上三点**”>“**Edit**”，标题的修改在标题右侧。

有什么问题请直接发送 comment 提出，我们鼓励相互交流促进。

2023-04-13 13:09 UTC, wywllin commented
> ### 部分建议仅提出一处，请连带修改其他
> 详情见上，包括色名和升级物品的名字
> 
> 该 comment 提到的问题仍未修改：[#3180 （comment）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/3180#issuecomment-1497230531)。conversation 的修改在“**右上三点**”>“**Edit**”，标题的修改在标题右侧。
> 
> 有什么问题请直接发送 comment 提出，我们鼓励相互交流促进。
已更改

2023-04-13 13:09 UTC, wywllin commented
> ### 部分建议仅提出一处，请连带修改其他
> 详情见上，包括色名和升级物品的名字
> 
> 该 comment 提到的问题仍未修改：[#3180 （comment）](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/3180#issuecomment-1497230531)。conversation 的修改在“**右上三点**”>“**Edit**”，标题的修改在标题右侧。
> 
> 有什么问题请直接发送 comment 提出，我们鼓励相互交流促进。

已更改

2023-04-13 15:34 UTC, mamaruo requested changes

2023-04-13 15:34 UTC, mamaruo commented on projects/1.16/assets/iron-shulker-boxes/ironshulkerbox/lang/zh_cn.json
> +    "ironshulkerbox.upgrade.tooltip": "用于将 %s 潜影盒升级为 %s 潜影盒.",
```suggestion
    "ironshulkerbox.upgrade.tooltip": "用于将%s潜影盒升级为%s潜影盒。",
```
没必要

另外下面一行缺句号。

2023-04-17 07:43 UTC, ChuijkYahus commented
这个应该和Iron Chest这个模组的翻译风格统一吧
那不应该出现`质`，箭头这个持保留意见

2023-04-18 03:16 UTC, wywllin commented
很抱歉这是我第一次使用github,也是第一次做正规的汉化

2023-04-18 03:22 UTC, ChuijkYahus commented on projects/1.16/assets/iron-shulker-boxes/ironshulkerbox/lang/zh_cn.json
> +    "block.ironshulkerbox.iron_shulker_box_white": "白色铁质潜影盒",
这里和后面`金质``铜质``银质`要不也和Iron Chest一样把`质`删除？

2023-04-18 03:31 UTC, ChuijkYahus approved these changes

2023-04-20 14:37 UTC, Ricky-fight approved these changes

2023-04-22 05:58 UTC, mamaruo approved these changes

2023-04-22 09:29 UTC, merged