more villagers翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3192
Opened 2023-04-08 18:02 UTC by sj19854825671

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-04-09 07:46 UTC, ChuijkYahus commented on projects/1.16/assets/more-villagers/morevillagers/lang/zh_cn.json
> +  "Obtain every villager workstation.": "获取每个村民的工作方块。",
```suggestion
  "Obtain every villager workstation.": "获取每个村民的工作方块",
```
请删除所有进度描述最后的句号

2023-04-09 07:46 UTC, ChuijkYahus commented on projects/1.16/assets/more-villagers/morevillagers/lang/zh_cn.json
> +  "Kill a baby villager...": "杀死一个小村民......",
```suggestion
  "Kill a baby villager...": "杀死一个小村民……",
```
请使用中文省略号（中文输入法下`Shift`+`6`）

2023-04-09 07:46 UTC, ChuijkYahus commented on projects/1.16/assets/more-villagers/morevillagers/lang/zh_cn.json
> +  "Use an End City Explorer Map from the Enderologist to find an End City.": "用从末地学家买的末地城探险家地图来找到一个末地城。",
```suggestion
  "Use a Bastion Explorer Map from the Netherologist to find a Bastion Remnant.": "用向下界学家买的堡垒探险家地图找到堡垒遗迹",
  "End City Explorer Map": "末地城探险家地图",
  "Use an End City Explorer Map from the Enderologist to find an End City.": "用向末地学家买的末地城探险家地图找到末地城",
```

2023-04-09 07:46 UTC, ChuijkYahus commented on projects/1.16/assets/more-villagers/morevillagers/lang/zh_cn.json
> +  "entity.minecraft.villager.morevillagers.hunter": "捕猎人",
```suggestion
  "entity.minecraft.villager.morevillagers.florist": "花匠",
  "entity.minecraft.villager.morevillagers.hunter": "猎手",
```

2023-04-09 12:32 UTC, sj19854825671 commented on projects/1.16/assets/more-villagers/morevillagers/lang/zh_cn.json
> +  "Obtain every villager workstation.": "获取每个村民的工作方块。",
感觉这是没有必要的，我的很多模组进度描述里都有标点符号

2023-04-09 12:37 UTC, sj19854825671 commented on projects/1.16/assets/more-villagers/morevillagers/lang/zh_cn.json
> +  "entity.minecraft.villager.morevillagers.hunter": "捕猎人",
此为官方繁体翻译就不作更改了

2023-04-09 12:39 UTC, sj19854825671 commented on projects/1.16/assets/more-villagers/morevillagers/lang/zh_cn.json
> +  "Kill a baby villager...": "杀死一个小村民......",
游戏中进度显示正常，更密集会不好看

2023-04-09 13:23 UTC, ChuijkYahus commented on projects/1.16/assets/more-villagers/morevillagers/lang/zh_cn.json
> +  "Kill a baby villager...": "杀死一个小村民......",
来源：GB/T 15834-2011
![图片](https://user-images.githubusercontent.com/94828194/230775139-7f5eb125-4be7-4bf9-91a9-bd68a6e9ac5c.png)

来源：库内CONTRIBUTING
![图片](https://user-images.githubusercontent.com/94828194/230775241-19c8de50-31d8-4edd-a395-f5dd3ab86ee6.png)
![图片](https://user-images.githubusercontent.com/94828194/230775262-395f99e0-6e75-439d-9513-11b51c3f1c87.png)
![图片](https://user-images.githubusercontent.com/94828194/230775269-72bb27d6-0fba-45a3-8dee-37dfcce41b42.png)

请修改，辛苦

2023-04-09 13:49 UTC, ChuijkYahus commented on projects/1.16/assets/more-villagers/morevillagers/lang/zh_cn.json
> +  "Kill a baby villager...": "杀死一个小村民......",
中文的省略号在打包时会进行替换，最终显示效果会在字符格内均匀显示，与原版的小点不同

2023-04-09 15:23 UTC, sj19854825671 commented on projects/1.16/assets/more-villagers/morevillagers/lang/zh_cn.json
> +  "Obtain every villager workstation.": "获取每个村民的工作方块。",
1.翻译库中许多模组翻译的成就都有标点符号
2.原版无标点符号是因为他的许多英文lang文件无标点符号罢
3.原版成就可能没有句号但也有其他标点符号
3.我认为需要尊重mod原作者添加的标点符号
3.这并不强制要求吧

2023-04-09 15:28 UTC, ChuijkYahus commented on projects/1.16/assets/more-villagers/morevillagers/lang/zh_cn.json
> +  "Obtain every villager workstation.": "获取每个村民的工作方块。",
OK

2023-04-09 15:29 UTC, ChuijkYahus approved these changes

2023-04-09 16:47 UTC, mamaruo commented
1. 两岸用语差异需要考虑，我不清楚这个方法是否科学：
<details><summary>百度结果数</summary>
<p>

![image](https://user-images.githubusercontent.com/37480168/230785328-d2c30bb9-3d9e-4985-8843-b3f631cd8ed3.png)
![image](https://user-images.githubusercontent.com/37480168/230785337-e0723821-435f-4b68-85a1-bb0c4ce21d81.png)
![image](https://user-images.githubusercontent.com/37480168/230785396-5ad09765-71dd-4d71-bc72-dc1951bab220.png)
![image](https://user-images.githubusercontent.com/37480168/230785403-1af0c254-a7d5-4e16-acbb-35a5caeb941a.png)


</p>
</details> 

2. 省略号不美观的问题老生常谈了，Chuijk 提到的替换已因显示 BUG [删除](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2721#issuecomment-1408864103)。可在此提出讨论：
- https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2721

3. 标点符号等问题以原文为准。

2023-04-10 10:10 UTC, sj19854825671 commented
> 1. 两岸用语差异需要考虑，我不清楚这个方法是否科学：
> 
> 百度结果数
> 2. 省略号不美观的问题老生常谈了，Chuijk 提到的替换已因显示 BUG [删除](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2721#issuecomment-1408864103)。可在此提出讨论：
> 
> * [[其他]：关于取消常用字符（省略号）替换的提议 #2721](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2721)
> 
> 3. 标点符号等问题以原文为准。
> 4. 我对 Forester 译作，Forestry Bench 译作表示怀疑。`木匠``锯木台`
> 
> > 森林人牛津：在森林里工作，照顾树木，种植新树等的人。 剑桥：负责看管森林的人
> 
> 5. 我认为[官译](https://github.com/samedifferent/morevillagers/blob/forge-1.16.5/src/main/resources/assets/morevillagers/lang/zh_cn.json)已足够好，甚至比本 PR 更好，所以是否接受本 PR 有待商榷。如：
> 
> 英语	官译	本公关
> 让我们开始工作	该上班了	让我们开始工作
> 林务官	林业员	木匠
> 参观所有5种村庄类型！	造访全部5种村庄！	访问所有5种类型的村庄！

1.此模组我是从pcl2上下载的1.16.5Forge最新版本，里面只有台湾语言的翻译文件，并且只翻译了寥寥几行，不明白为什么所谓“”官方翻译“”文件并不内置在模组里面，没有内置进去的文件也能算是官译吗？
2.此模组大部分翻译是我手动翻译和修辞，如果觉得“官方翻译”更好的话我可以替换掉我的翻译文件。
3.我认为提交翻译文件进库能方便大量的1.16.5玩家不需要再自行寻找汉化文件并塞入模组里，我提交此请求的原因也是因为在此之前我并不了解有所谓的“官译”，早知道我也就不干这活了，给自己找麻烦

2023-04-10 11:45 UTC, CoalGlage commented
事实上1.18.2和1.19.2有官方提供的简中翻译，但1.16.5并没有。很迷惑。
那么在有官译且官译质量不错的情况下1165的翻译要和较高版本的官译进行同步吗....

2023-04-10 13:26 UTC, sj19854825671 commented
> 事实上1.18.2和1.19.2有官方提供的简中翻译，但1.16.5并没有。很迷惑。 那么在有官译且官译质量不错的情况下1165的翻译要和较高版本的官译进行同步吗....

是的，我不明白1.16.5版本为什么没有简中翻译，现在我就想知道我提供的翻译能不能上传，如果是因为质量原因我可以跟高版本的官译进行对比更改，或者直接驳回我这个提交，但我觉得在1.16.5模组里本就没有翻译文件的情况下提交翻译无可厚非

2023-04-10 16:29 UTC, mamaruo commented
> 我认为提交翻译文件进库能方便大量的1.16.5玩家不需要再自行寻找汉化文件并塞入模组里，我提交此请求的原因也是因为在此之前我并不了解有所谓的“官译”，早知道我也就不干这活了，给自己找麻烦

> ……现在我就想知道我提供的翻译能不能上传……

很抱歉之前没有仔细调查此模组的情况，解决这种“假官译”正是我们的[目标](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package#:~:text=%E8%AF%A5%E9%A1%B9%E7%9B%AE%E7%9A%84%E7%9B%AE%E7%9A%84%E6%98%AF%E8%A7%A3%E5%86%B3%E6%A8%A1%E7%BB%84%E4%BD%9C%E8%80%85%E4%B8%8D%E6%8E%A5%E6%94%B6%E7%BF%BB%E8%AF%91%E3%80%81%E7%BF%BB%E8%AF%91%E6%9B%B4%E6%96%B0%E9%80%9F%E5%BA%A6%E6%85%A2%E7%AD%89%E8%AF%B8%E5%A4%9A%E9%97%AE%E9%A2%98%E3%80%82)之一。

> 此模组我是从pcl2上下载的1.16.5Forge最新版本，里面只有台湾语言的翻译文件，并且只翻译了寥寥几行，不明白为什么所谓“”官方翻译“”文件并不内置在模组里面，没有内置进去的文件也能算是官译吗？

>是的，我不明白1.16.5版本为什么没有简中翻译……

模组的简体中文官方翻译于 2022 年 6 月提交（<https://github.com/samedifferent/morevillagers/commit/a686692b67103596b0ae7f8b2af09bda28fa6690>），作者最后一次发布 1.16.5 模组文件的日期在 2021 年 9 月。繁体中文（台湾）的翻译主要都在 2021 年 9 月之前提交（[改动历史](https://github.com/samedifferent/morevillagers/commits/forge-1.16.5/src/main/resources/assets/morevillagers/lang/zh_tw.json)）。这就是造成目前官译现状的原因。

我认为理论上只要被作者承认（Merge 了 PR），那么就可以算作“官方翻译”。另外此模组的更高版本的官方中文翻译都是**同一份文件**，同一人提交。你可以访问[该文件](https://github.com/samedifferent/morevillagers/blob/1.16.5-crossplatform/common/src/main/resources/assets/morevillagers/lang/zh_cn.json)，然后在左上角切换分支（带`crossplatform`字样）确认这一点。

> 此模组大部分翻译是我手动翻译和修辞，如果觉得“官方翻译”更好的话我可以替换掉我的翻译文件。

我们审查的是翻译，不审查来源（存在版权争议时除外）。当然，鉴于官方的 1.18+ 翻译已使用了十月余，不宜存在类似 `花匠` → `园艺匠` 的“可有可无”的差异。

当然，官译并非无可挑剔，Purpur Altar 官译讹为 `紫颂坛`，与 Chorus 混淆。而本 PR 的处理正确。

我明白这是你独立翻译的作品，但不必要的翻译差异的存在会造成玩家不便，所以我建议在官译的基础上修改，在本 PR 入库。也请日后翻译时检查是否已存在翻译避免做不必要的工作。

2023-04-15 08:25 UTC, DrIceTea123 requested changes

2023-04-15 08:25 UTC, DrIceTea123 commented on projects/1.16/assets/more-villagers/morevillagers/lang/zh_cn.json
> +  "block.morevillagers.blueprint_table": "绘图站",
这个物品的实际表现是什么，是“使用蓝图制作物品的工作台”还是“用于绘制蓝图的桌子”？如果是前者，应译为`蓝图桌`或者`蓝图工作台`；如果是后者，应该是`绘图桌`或者`绘图台`或`绘图站`。
请参考：方块模型，能否交互与交互界面，对应的村民职业设定，等等。

2023-04-15 08:25 UTC, DrIceTea123 commented on projects/1.16/assets/more-villagers/morevillagers/lang/zh_cn.json
> +  "Emeralds to the Moon!": "月之翡翠！",
Emerald是`绿宝石`没错
根据描述`和末地的末地学家交易`，原译`绿宝石上月球！`似乎更为恰当

2023-04-15 08:25 UTC, DrIceTea123 commented on projects/1.16/assets/more-villagers/morevillagers/lang/zh_cn.json
> +  "Sponsored Voyage": "赞助航行",
个人认为官译`远航支援`更为恰当

2023-04-15 08:25 UTC, DrIceTea123 commented on projects/1.16/assets/more-villagers/morevillagers/lang/zh_cn.json
> +  "Use a Bastion Explorer Map from the Netherologist to find a Bastion Remnant.": "用向下界学家买的堡垒探险家地图找到堡垒遗迹",
在L9已译为`堡垒遗迹探险家地图`
请修改L9或修改这两行

2023-05-03 08:04 UTC, ChuijkYahus commented
* 7+7时限进入第一阶段，请注意查看各审核意见

@sj19854825671

2023-05-14 16:40 UTC, mamaruo commented
在此接手，6月中旬处理

2023-07-14 18:00 UTC, mamaruo commented on projects/1.16/assets/more-villagers/morevillagers/lang/zh_cn.json
> +  "block.morevillagers.blueprint_table": "绘图站",
没有交互界面，对应村民是工程师，卖红石材料和红石器件。

2023-07-14 18:40 UTC, mamaruo commented
我对比了“官方翻译”和“本PR”的翻译，结果如下：

### 两者皆有且中文有差异

<details><summary>点击展开/收起</summary>
<p>

| **键** | **英文** | **官方翻译** | **本PR** |
|---|---|---|---|
| block.morevillagers.oceanography_table | Oceanography Table | 海洋研究站 | 海洋研究台 |
| block.morevillagers.purpur_altar | Purpur Altar | 紫颂坛 | 紫珀祭坛 |
| block.morevillagers.blueprint_table | Blueprint Table | 绘图桌 | 绘图站 |
| Trade with every villager profession | Trade with every villager profession | 与所有职业的村民进行交易。 | 与所有村民职业进行交易 |
| Visit all 5 village types! | Visit all 5 village types\! | 造访全部5种村庄！ | 造访全部5种类型的村庄！ |
| Obtain every villager workstation. | Obtain every villager workstation\. | 获得所有的村民工作站。 | 获取每个村民的工作站。 |
| Sponsored Voyage | Sponsored Voyage | 远航支援 | 赞助航行 |
| Buy an Explorer Map from a villager. | Buy an Explorer Map from a villager\. | 向村民购买一张探险地图。 | 向村民购买一张探险家地图。 |
| Trade with the Enderologist in the End dimension. | Trade with the Enderologist in the End dimension\. | 在末地与末地学家进行交易。 | 和末地的末地学家交易。 |
| First Trade | First Trade | 第一桶金 | 首次交易 |
| Make your first villager trade. | Make your first villager trade\. | 与村民进行一次交易。 | 进行你的第一次村民交易。 |
| First Village | First Village | 新手村 | 第一个村庄 |
| Find a village. | Find a village\. | 造访一座村庄。 | 找到一个村庄。 |
| Even Badder Deal | Even Badder Deal | 更糟糕的生意 | 更糟糕的交易 |
| Kill a baby villager... | Kill a baby villager\.\.\. | 杀死一个幼年村民…… | 杀死一个小村民…… |
| Bad Deal | Bad Deal | 糟糕的生意 | 糟糕的交易 |
| Bastion Explorer Map | Bastion Explorer Map | 垒遗迹探险家地图 | 堡垒探险家地图 |
| Use a Bastion Explorer Map from the Netherologist to find a Bastion Remnant. | Use a Bastion Explorer Map from the Netherologist to find a Bastion Remnant\. | 用下界学家售卖的探险家地图找到下界堡垒遗迹。 | 用向下界学家买的堡垒探险家地图找到堡垒遗迹 |
| Use an End City Explorer Map from the Enderologist to find an End City. | Use an End City Explorer Map from the Enderologist to find an End City\. | 用末地学家售卖的探险家地图找到末地城。 | 用向末地学家买的末地城探险家地图找到末地城 |
| Ace Trainer | Ace Trainer | 王牌训练师 | 王牌教练 |
| Level up a villager to Master and make a grand purchase. | Level up a villager to Master and make a grand purchase\. | 提升村民等级到大师级并进行一次盛大的采购。 | 提升一个村民的等级到大师级并进行一次大量购买。 |
| Trade with the Netherologist in the Nether dimension. | Trade with the Netherologist in the Nether dimension\. | 在下界维度与下界学家进行交易。 | 在下界和下界学家交易。 |
| Tame a cat in a village. | Tame a cat in a village\. | 驯服一只村庄里的猫。 | 驯服一只村庄里的猫 |

</p>
</details>

### 只在 官方翻译 中有

| **键** | **英文** | **官方翻译** | **本PR** |
|---|---|---|---|
| itemGroup.morevillagers.tab | 🚫 | 更多村民 | 🚫 |
| entity.minecraft.villager.oceanographer | Oceanographer | 海洋学家 | 🚫 |
| entity.minecraft.villager.netherian | Netherologist | 下界学家 | 🚫 |
| entity.minecraft.villager.woodworker | Forester | 林业员 | 🚫 |
| entity.minecraft.villager.enderian | Enderologist | 末地学家 | 🚫 |
| entity.minecraft.villager.engineer | Engineer | 工程师 | 🚫 |
| entity.minecraft.villager.florist | Florist | 花匠 | 🚫 |
| entity.minecraft.villager.hunter | Hunter | 猎人 | 🚫 |

### 只在 本PR 中有

| **键** | **英文** | **官方翻译** | **本PR** |
|---|---|---|---|
| itemGroup.morevillagers | More Villagers | 🚫 | 更多村民 |

2023-07-21 13:54 UTC, ChuijkYahus approved these changes

2023-07-22 12:50 UTC, merged