Ars Elemental 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3201
Opened 2023-04-11 14:36 UTC by goutouyu

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-04-12 04:18 UTC, ChuijkYahus commented
#2717

2023-07-21 05:38 UTC, ChuijkYahus commented
可以参照一下#2717 看看有没有什么需要讨论的

2023-07-21 05:38 UTC, ChuijkYahus commented
en_us.json未提交，请注意提交

2023-07-23 10:57 UTC, Cyl18 commented
/mv "projects/1.19/assets/ars_elemental/" "projects/1.19/assets/ars-elemental/"

2023-07-23 11:02 UTC, Cyl18 commented
/update-en ars_elemental 1.19

2023-07-23 11:06 UTC, Cyl18 commented
/update-en ars-elemental 1.19

2023-07-24 07:50 UTC, Junson-Chiang commented
#2717 接手，大概三个月完成

2023-07-24 09:06 UTC, Junson-Chiang commented
#3559 接手

2023-07-30 07:08 UTC, luoxueyasha commented
@Junson-Chiang @goutouyu 关于接手上，两边已经协商过了吗？

2023-07-30 10:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3201) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3201) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: goutouyu<br/>:x: Cyl18<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3201) it.</sub>

2023-07-30 14:38 UTC, Junson-Chiang commented
@luoxueyasha 并没有，但即便我想沟通，我完全见不到这个人在这个pr多说一句话，很有可能这个pr已经被挂在这不管了，作为这一模组1.18版本的翻译提交者，我认为由我接受更合适不过，当然，如果@goutouyu 依然想回来维护这一PR我也不会说什么，但关于他的翻译质量方面我不敢保证

2023-07-31 08:56 UTC, luoxueyasha requested changes

2023-07-31 08:56 UTC, luoxueyasha commented on projects/1.19/assets/ars-elemental/ars_elemental/lang/zh_cn.json
> +    "block.ars_elemental.spore_blossom_up": "孢子花(地面)",
```suggestion
    "block.ars_elemental.spore_blossom_up": "孢子花（地面）",
```
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/00161cc7-66f8-4973-8dd6-05522c857c78)

2023-08-01 00:52 UTC, luoxueyasha commented
@goutouyu 
- [3+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，请及时更新简体中文、翻译源语言的语言文件。若在3天内仍未做出任何实质性回应，则3+7时限自动进入下一阶段。

2023-08-25 01:13 UTC, Cactusstudent commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@goutouyu

2023-09-03 02:13 UTC, closed without merging