Hunter illager 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3202
Opened 2023-04-12 17:31 UTC by mamaruo

作者母语为日语
本 PR 以作者写的英语为基础翻译，需要以日语为源语言日语审阅。

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-04-13 08:10 UTC, luoxueyasha requested changes
![image](https://user-images.githubusercontent.com/38830216/231695963-f470ee91-6c0a-4930-925a-b4a4cb15b142.png)
えっ？校对是オレ？

另：这个模组还有低版本，不知道库内有没有翻译

2023-04-13 15:38 UTC, mamaruo commented on projects/1.19/assets/hunterillager/hunterillager/lang/zh_cn.json
> +  "item.hunterillager.quivers": "箭袋",
没有，只有一种箭袋

2023-04-13 15:42 UTC, mamaruo commented
> 另：这个模组还有低版本，不知道库内有没有翻译

有，但内容有一定差异，且是以英文为基础翻译的（虽然我也是（））
- #2973

2023-04-14 00:34 UTC, luoxueyasha commented on projects/1.19/assets/hunterillager/hunterillager/lang/zh_cn.json
> +  "item.hunterillager.quivers": "箭袋",
`箭袋`或`大箭袋`都行

2023-04-14 00:34 UTC, luoxueyasha commented on projects/1.19/assets/hunterillager/hunterillager/lang/zh_cn.json
> +  "death.attack.hunterillager.boomerang.player": "%1$s被%2$s的回旋镖击中了",
既然L12改成了`击毙`，有考虑过统一L13-14吗

2023-04-15 01:11 UTC, luoxueyasha approved these changes
![image](https://user-images.githubusercontent.com/38830216/232175828-5f51166b-9e58-4989-87e7-23a9ddf4d50b.png)

2023-04-15 10:24 UTC, mamaruo commented
@luoxueyasha 
请求按日语审阅 1.12.2 的翻译。
另请问魔咒`弾力`的译文是否合适？效果是：
> 新しいエンチャント バウンスは新しいブーメランのエンチャントです
ブーメランを当てると壁に跳ね返ります

2023-04-15 16:02 UTC, luoxueyasha commented
> @luoxueyasha 请求按日语审阅 1.12.2 的翻译。 另请问魔咒`弾力`的译文是否合适？效果是：
> 
> > 新しいエンチャント バウンスは新しいブーメランのエンチャントです
> > ブーメランを当てると壁に跳ね返ります

效果翻译：
新附魔 （片假名bounce）是新的回旋镖附魔  
回旋镖命中目标以及打到墙上时会弹回来

因此“弹力”没有任何问题

2023-04-22 14:28 UTC, mamaruo commented
> 因此“弹力”没有任何问题 脑袋清醒了再看一遍这个原文，感觉描述上好奇怪，需要游戏内测试

不附魔仍然可以弹跳，但附魔后弹得更高，弹跳次数更多

2023-04-24 23:39 UTC, luoxueyasha commented
> 不附魔仍然可以弹跳，但附魔后弹得更高，弹跳次数更多

`弹力`没问题

2023-07-04 01:24 UTC, luoxueyasha requested changes

2023-07-04 01:24 UTC, luoxueyasha commented on projects/1.19/assets/hunterillager/hunterillager/lang/zh_cn.json
> +  "subtitles.hunterillager.laugh": "邪猎者：暗笑",
确定是`暗笑`而不是`大笑`吗

2023-07-04 01:24 UTC, luoxueyasha commented on projects/1.19/assets/hunterillager/hunterillager/lang/zh_cn.json
> +  "enchantment.hunterillager.bounce": "弹跳"
少两行config没翻

2023-07-04 01:24 UTC, luoxueyasha commented on projects/1.19/assets/hunterillager/hunterillager/lang/zh_cn.json
> +  "enchantment.hunterillager.bounce": "弹跳"
```suggestion
  "enchantment.hunterillager.bounce": "弹力"
```

2023-08-01 05:33 UTC, luoxueyasha commented
@mamaruo 我来执行7+7了
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/01d572be-3fcf-4020-a9a1-15561066fdb8)

2023-08-08 02:00 UTC, Cactusstudent commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@mamaruo 是不是忘了这里的提交了

2023-08-11 12:46 UTC, luoxueyasha commented on projects/1.19/assets/hunterillager/hunterillager/lang/zh_cn.json
> +  "enchantment.hunterillager.bounce": "弹跳"
额，直接移除了那两行？具体是什么情况

2023-08-12 02:58 UTC, mamaruo commented on projects/1.19/assets/hunterillager/hunterillager/lang/zh_cn.json
> +  "enchantment.hunterillager.bounce": "弹跳"
那两个是[世界生成的关键字](https://minecraft.fandom.com/zh/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%96%E7%95%8C%E7%94%9F%E6%88%90/structure_set#:~:text=%E3%80%82-,spacing,-%EF%BC%9A%E4%B8%A4%E4%B8%AA%E7%BB%93%E6%9E%84)，我没有想出较好的翻译，故直接移除。

2023-08-12 03:02 UTC, mamaruo commented on projects/1.19/assets/hunterillager/hunterillager/lang/zh_cn.json
> +  "subtitles.hunterillager.laugh": "邪猎者：暗笑",
[src_main_resources_assets_hunterillager_sounds_mob_hunterillager_hunter_laugh.zip](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/files/12326314/src_main_resources_assets_hunterillager_sounds_mob_hunterillager_hunter_laugh.zip)

听听

2023-08-12 10:50 UTC, luoxueyasha approved these changes

2023-08-14 02:36 UTC, merged