Interactic & blur 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3205
Opened 2023-04-15 08:29 UTC by A-Black-Fish

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-04-15 08:34 UTC, A-Black-Fish commented
以下是“玩家”被“玩家”对应物品砸死时的死亡信息（暂不知怎么翻译好...）
`"death.attack.thrown_item": "%1$s was pummeled by %2$s using %3$s"`对应方块
`"death.attack.thrown_item.sword": "%1$s was executed by %2$s using %3$s"`对应剑
`"death.attack.thrown_item.axe": "%1$s felt a trickshot %2$s performed using %3$s"`对应斧
`"death.attack.thrown_item.shovel": "%1$s was whacked by %2$s using %3$s"`对应铲
`"death.attack.thrown_item.pickaxe": "%1$s was pierced by %2$s using %3$s"`对应镐
`"death.attack.thrown_item.hoe": "%1$s was reaped by %2$s using %3$s"`对应锄

2023-04-15 10:36 UTC, A-Black-Fish commented
关于
平放物品渲染（渲染物品）的翻译
![javaw_tI1hWjOXRO](https://user-images.githubusercontent.com/101028476/232208903-489be67f-1bd2-4020-84b1-bb81161c23bb.gif)

2023-04-19 02:06 UTC, ChuijkYahus requested changes

2023-04-19 02:06 UTC, ChuijkYahus commented on projects/1.18-fabric/assets/blur-fabric/blur/lang/zh_cn.json
> +  "blur.midnightconfig.fadeTimeMillis": "淡入时间(毫秒)",
请使用全角符号

2023-04-19 02:06 UTC, ChuijkYahus commented on projects/1.18-fabric/assets/interactic/interactic/lang/zh_cn.json
> +  "text.autoconfig.interactic.option.renderItemTooltips": "渲染物品工具提示框",
```suggestion
  "text.autoconfig.interactic.option.renderItemTooltips": "渲染物品提示框",
```
https://minecraft.fandom.com/zh/wiki/%E6%8F%90%E7%A4%BA%E6%A1%86
不需要把Tool单独翻译出来

2023-04-19 02:06 UTC, ChuijkYahus commented on projects/1.18-fabric/assets/interactic/interactic/lang/zh_cn.json
> +  "text.autoconfig.interactic.option.itemsActAsProjectiles": "物品抛掷可造成伤害",
这里是照实际表现翻的吗

2023-04-19 02:06 UTC, ChuijkYahus commented on projects/1.18-fabric/assets/interactic/interactic/lang/zh_cn.json
> +  "death.attack.thrown_item.hoe": "%1$s was reaped by %2$s using %3$s",
暂未翻译

2023-04-19 06:05 UTC, A-Black-Fish commented on projects/1.18-fabric/assets/interactic/interactic/lang/zh_cn.json
> +  "text.autoconfig.interactic.option.itemsActAsProjectiles": "物品抛掷可造成伤害",
的确按实际表现翻的

2023-04-19 06:05 UTC, A-Black-Fish commented on projects/1.18-fabric/assets/interactic/interactic/lang/zh_cn.json
> +  "death.attack.thrown_item.hoe": "%1$s was reaped by %2$s using %3$s",
见https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/3205#issuecomment-1509638410

2023-04-20 11:55 UTC, ChuijkYahus commented on projects/1.18-fabric/assets/interactic/interactic/lang/zh_cn.json
> +  "death.attack.thrown_item.hoe": "%1$s was reaped by %2$s using %3$s",
```suggestion
  "death.attack.thrown_item": "%1$s被%2$s用%3$s砸死了",
  "death.attack.thrown_item.sword": "%1$s被%2$s用%3$s处决了",
  "death.attack.thrown_item.axe": "%1$s感受到了来自%2$s用%3$s做出的花式射击",
  "death.attack.thrown_item.shovel": "%1$s被%2$s用%3$s捶扁了",
  "death.attack.thrown_item.pickaxe": "%1$s被%2$s用%3$s击穿了",
  "death.attack.thrown_item.hoe": "%1$s被%2$s用%3$s收割了",
```
乱翻

2023-04-22 06:34 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/interactic/interactic/lang/zh_cn.json
> +  "death.attack.thrown_item.hoe": "%1$s was reaped by %2$s using %3$s",
我觉得Chuijk这个挺合适的（）

2023-04-30 11:09 UTC, ChuijkYahus approved these changes

2023-05-03 08:02 UTC, merged