Ars Nouveau: GEARs 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3228
Opened 2023-04-27 15:09 UTC by ChuijkYahus

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-06-21 16:03 UTC, ChuijkYahus commented
/add-mapping ars-nouveau-gears 664411

2024-03-31 14:41 UTC, SlimeSB requested changes

2024-03-31 14:41 UTC, SlimeSB commented on projects/1.16/assets/ars-nouveau-gears/ars_gears/patchouli_books/worn_notebook/zh_cn/entries/ars_gears/combat_gear.json
> +      "text": "对于比石高的等级：$(br2)每级获得1个法术槽（起始2个，总计4个）。$(br2)每级获得2个构件槽（起始6个，总计10个）。$(br2)每级增强构件堆叠数增加1（起始1层，总计3层）。"
```suggestion
      "text": "对高于石等级的装备：$(br2)每级额外获得1个法术槽（起始2个，总计4个）。$(br2)每级额外获得2个构件槽（起始6个，总计10个）。$(br2)每级额外增加1层增强构件堆叠数（起始1层，总计3层）。"

```

2024-03-31 14:41 UTC, SlimeSB commented on projects/1.16/assets/ars-nouveau-gears/ars_gears/patchouli_books/worn_notebook/zh_cn/entries/ars_gears/combat_gear.json
> +      "text": "用于包含法术书的合成配方：$(br2)潜行时按下“循环装备”键（$(k:ars_nouveau.open_book)）。"
```suggestion
      "text": "作为法术书用于合成配方：$(br2)潜行时按下“循环装备”键（$(k:ars_nouveau.open_book)）。"

```

2024-03-31 14:41 UTC, SlimeSB commented on projects/1.16/assets/ars-nouveau-gears/ars_gears/patchouli_books/worn_notebook/zh_cn/entries/ars_gears/combat_gear.json
> +      "text": "使用方法：$(br2)剑：$(br)右击激活法术。$(br2)再次右击以对生物或方块施法，或是对空气右击以取消激活。$(br2)也可左击施法法术（仅对生物有效）。"
```suggestion
      "text": "使用方法：$(br2)剑：$(br)右击激活法术。$(br2)对生物或方块再次右击以施法，或是对空气右击以取消激活。$(br2)也可左击施法法术（仅对生物有效）。"

```

2024-03-31 14:41 UTC, SlimeSB commented on projects/1.16/assets/ars-nouveau-gears/ars_gears/patchouli_books/worn_notebook/zh_cn/entries/ars_gears/combat_gear.json
> +      "text": "弓：$(br)拉弓时左击激活法术。$(br2)再次左击以取消激活。$(br2)发射箭矢以施法（带有法术的箭矢的基础伤害为0）。"
```suggestion
      "text": "弓：$(br)蓄力时左击激活法术。$(br2)再次左击以取消激活。$(br2)发射箭矢以施法（带有法术的箭矢的基础伤害为0）。"

```

2024-03-31 14:41 UTC, SlimeSB commented on projects/1.16/assets/ars-nouveau-gears/ars_gears/patchouli_books/worn_notebook/zh_cn/entries/ars_gears/starting_ars_gears.json
> +      "text": "$(bold)修复：$()需打开多效工具的物品栏（$(k:ars_gears.gear_inventory)）并在其中放置食物。$(br2)食物的品质会影响回复的耐久度。$(br2)（$(bold)注意：$()饱和度和食物中毒不造成影响）"
```suggestion
      "text": "$(bold)修复：$()需打开多效工具的物品栏（$(k:ars_gears.gear_inventory)）并在其中放置食物。$(br2)食物的品质会影响回复的耐久度。$(br2)（$(bold)注意：$()饱和和食物负面效果不会影响）"

```
可能指的是饱和这个药水效果，和饥饿、中毒。如果你有时间进游戏看一下……我没配环境。

2024-03-31 14:41 UTC, SlimeSB commented on projects/1.16/assets/ars-nouveau-gears/ars_gears/patchouli_books/worn_notebook/zh_cn/entries/ars_gears/starting_ars_gears.json
> +      "text": "$(bold)等级：$()多效装备有5个等级（木、石、铁、钻石、奥术）。$(br2)耐久度、伤害、采掘等级，速度等均会随等级上升而增加。"
```suggestion
      "text": "$(bold)等级：$()多效装备有5个等级（木、石、铁、钻石、奥术）。$(br2)耐久度、伤害、采掘等级、速度等均会随等级上升而增加。"

```

2024-03-31 14:41 UTC, SlimeSB commented on projects/1.16/assets/ars-nouveau-gears/ars_gears/patchouli_books/worn_notebook/zh_cn/entries/ars_gears/starting_ars_gears.json
> +      "text": "$(bold)附魔：$()为多效装备附魔需手持之并右击抄写台。"
```suggestion
      "text": "$(bold)附魔：$()手持多效装备右击抄写台以附魔"

```

2024-03-31 14:59 UTC, ChuijkYahus commented on projects/1.16/assets/ars-nouveau-gears/ars_gears/patchouli_books/worn_notebook/zh_cn/entries/ars_gears/starting_ars_gears.json
> +      "text": "$(bold)修复：$()需打开多效工具的物品栏（$(k:ars_gears.gear_inventory)）并在其中放置食物。$(br2)食物的品质会影响回复的耐久度。$(br2)（$(bold)注意：$()饱和度和食物中毒不造成影响）"
```suggestion
      "text": "$(bold)修复：$()需打开多效工具的物品栏（$(k:ars_gears.gear_inventory)）并在其中放置食物。$(br2)食物的品质会影响回复的耐久度。$(br2)（$(bold)注意：$()饱和度和食物负面效果不会影响）"
```
源码里只取了食物回的饥饿值

2024-03-31 15:06 UTC, SlimeSB commented on projects/1.16/assets/ars-nouveau-gears/ars_gears/patchouli_books/worn_notebook/zh_cn/entries/ars_gears/starting_ars_gears.json
> +      "text": "$(bold)修复：$()需打开多效工具的物品栏（$(k:ars_gears.gear_inventory)）并在其中放置食物。$(br2)食物的品质会影响回复的耐久度。$(br2)（$(bold)注意：$()饱和度和食物中毒不造成影响）"
同意

2024-04-03 09:15 UTC, SlimeSB submitted a review, later dismissed

2024-04-23 13:44 UTC, SlimeSB commented
还是给描述中提到的符魔加点关注吧。包括以前的

2024-04-24 12:02 UTC, SlimeSB approved these changes

2024-04-27 09:07 UTC, merged