pymtech 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3269
Opened 2023-05-08 12:51 UTC by BayunL

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2023-05-09 17:52 UTC, A-Black-Fish commented on projects/1.12.2/assets/pymtech/pymtech/lang/zh_cn.lang
> +pymtech.info.not_enough_grow_pp=禮c你没有足够的放大皮姆粒子!
```suggestion
pymtech.info.not_enough_shrink_pp=§c你没有足够的缩小皮姆粒子!
pymtech.info.not_enough_grow_pp=§c你没有足够的放大皮姆粒子!
```

2023-05-09 17:52 UTC, A-Black-Fish commented on projects/1.12.2/assets/pymtech/pymtech/lang/zh_cn.lang
> +pymtech.info.bounding_box=边界框: %s
```suggestion
pymtech.info.bounding_box=边界框：%s
```

2023-05-09 17:52 UTC, A-Black-Fish commented on projects/1.12.2/assets/pymtech/pymtech/lang/zh_cn.lang
> +pymtech.info.size_display=尺寸: %sx
```suggestion
pymtech.info.size_display=尺寸：%sx

```

2023-05-09 17:54 UTC, A-Black-Fish commented on projects/1.12.2/assets/pymtech/pymtech/lang/zh_cn.lang
> +commands.quantumrealm.usage=/量子领域 <实体>
```suggestion
commands.quantumrealm.usage=/quantumrealm <实体>

```

2023-06-16 03:57 UTC, mamaruo requested changes
不了解漫威的东西，仅作参考

2023-06-16 03:57 UTC, mamaruo commented on projects/1.12.2/assets/pymtech/pymtech/lang/zh_cn.lang
> +item.ant_antenna.name=蚂蚁天线
| **审查级别**    |
|--------------|
| ⚪ 轻微 / 不阻止合并但需三思  |

原文：**Ant Antenna**
```suggestion
item.ant_antenna.name=蚂蚁触须
```
？？？我也不知道

2023-06-16 03:57 UTC, mamaruo commented on projects/1.12.2/assets/pymtech/pymtech/lang/zh_cn.lang
> +item.emp_communication_device.name=EMP通讯装置
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

原文：**EMP Communication Device**
```suggestion
item.emp_communication_device.name=电磁脉冲通信装置
```

2023-06-16 03:57 UTC, mamaruo commented on projects/1.12.2/assets/pymtech/pymtech/lang/zh_cn.lang
> +pymtech.suit.ant_man.desc=初代
| **审查级别**    |
|--------------|
| ⚪ 轻微 / 不阻止合并但需三思  |

原文：**Tier 1**
```suggestion
pymtech.suit.ant_man.desc=一阶
```

2023-06-16 03:57 UTC, mamaruo commented on projects/1.12.2/assets/pymtech/pymtech/lang/zh_cn.lang
> +pymtech.suit.ant_man_2.desc=二代
| **审查级别**    |
|--------------|
| ⚪ 轻微 / 不阻止合并但需三思  |

原文：**Tier 2**
```suggestion
pymtech.suit.ant_man_2.desc=二阶
```

2023-06-16 03:57 UTC, mamaruo commented on projects/1.12.2/assets/pymtech/pymtech/lang/zh_cn.lang
> +pymtech.suit.ant_man_3.desc=三代
| **审查级别**    |
|--------------|
| ⚪ 轻微 / 不阻止合并但需三思  |

原文：**Tier 3**
```suggestion
pymtech.suit.ant_man_3.desc=三阶5
```

2023-06-16 03:57 UTC, mamaruo commented on projects/1.12.2/assets/pymtech/pymtech/lang/zh_cn.lang
> +item.ant_man_3_boots.name=蚁人鞋子
| **审查级别**   |
|-------------|
| 🔴 严重 / **阻止合并，刻不容缓** |

原文：**Ant-Man's Boots**
```suggestion
item.ant_man_3_boots.name=蚁人靴子
```

2023-06-16 03:57 UTC, mamaruo commented on projects/1.12.2/assets/pymtech/pymtech/lang/zh_cn.lang
> +pymtech.suit.wasp.desc=二代
| **审查级别**    |
|--------------|
| ⚪ 轻微 / 不阻止合并但需三思  |

原文：**Tier 2**
```suggestion
pymtech.suit.wasp.desc=二阶
```

2023-06-16 03:57 UTC, mamaruo commented on projects/1.12.2/assets/pymtech/pymtech/lang/zh_cn.lang
> +item.wasp_boots.name=黄蜂女鞋子
| **审查级别**   |
|-------------|
| 🔴 严重 / **阻止合并，刻不容缓** |

原文：**Wasp's Boots**
```suggestion
item.wasp_boots.name=黄蜂女靴子
```

2023-06-16 03:57 UTC, mamaruo commented on projects/1.12.2/assets/pymtech/pymtech/lang/zh_cn.lang
> +commands.quantumrealm.success.other=将%s传送进量子领域
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

原文：**Sent himself into the Quantum Realm┃Sent %s into the Quantum Real**
```suggestion
commands.quantumrealm.success.self=已将自己传送进量子领域
commands.quantumrealm.success.other=已将%s传送进量子领域
```

这是命令执行成功之后的提示

2023-06-16 03:57 UTC, mamaruo commented on projects/1.12.2/assets/pymtech/pymtech/lang/zh_cn.lang
> +pymtech.abilities.shrink_suit.name=缩小制服
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

原文：**Shrink Suit**
```suggestion
pymtech.abilities.shrink_suit.name=缩小套装
```

2023-06-16 03:57 UTC, mamaruo commented on projects/1.12.2/assets/pymtech/pymtech/lang/zh_cn.lang
> +pymtech.info.not_enough_grow_pp=§c你没有足够的放大皮姆粒子！
| **审查级别**    |
|--------------|
| ⚪ 轻微 / 不阻止合并但需三思  |

原文：**§cYou don't have enough Shrink Pym Particles!┃§cYou don't have enough Grow Pym Particles**
```suggestion
pymtech.info.not_enough_shrink_pp=§c你的缩小皮姆粒子不够！
pymtech.info.not_enough_grow_pp=§c你的放大皮姆粒子不够！
```

2023-06-16 03:57 UTC, mamaruo commented on projects/1.12.2/assets/pymtech/pymtech/lang/zh_cn.lang
> +pymtech.info.reset=重启
| **审查级别**   |
|-------------|
| 🔴 严重 / **阻止合并，刻不容缓** |

原文：**Reset**
```suggestion
pymtech.info.reset=重置
```
```suggestion
pymtech.info.reset=恢复默认
```

2023-06-16 03:57 UTC, mamaruo commented on projects/1.12.2/assets/pymtech/pymtech/lang/zh_cn.lang
> +death.attack.suffocate=%s 太小而窒息
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

原文：**%s suffocated while being small**
```suggestion
death.attack.suffocate=%s在小的时候窒息而死
```
```suggestion
death.attack.suffocate=%s在变小的时候窒息而死
```

原译应该是错的，不过我的提议都有歧义，希望有更好的建议：
- 在变小的（过程中）时候窒息而死
- 在（年龄）小的时候窒息而死

2023-06-29 16:51 UTC, mamaruo commented
@BayunL 请关注一下审阅意见，若迟迟未回应，PR将被关闭

2023-07-10 05:20 UTC, ChuijkYahus commented
* 7+7时限已到，请注意查看审核意见，如有需要可reopen

@BayunL

2023-07-10 05:20 UTC, closed without merging