speedsterheroes 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #3270
Opened 2023-05-08 13:05 UTC by BayunL

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2023-05-09 11:20 UTC, ChuijkYahus reviewed
请注意全文以及全PR修改
不要遗留标点问题，除非是表情、坐标、程序等特殊情况

2023-05-09 11:20 UTC, ChuijkYahus commented on projects/1.12.2/assets/speedster-heroes/speedsterheroes/lang/zh_cn.lang
> +speedsterheroes.suitsets.cw_flash.name=闪电侠(电视剧)
```suggestion
speedsterheroes.suitsets.cw_flash.name=闪电侠（电视剧）
```
所有括号均改为全角括号

2023-05-09 11:20 UTC, ChuijkYahus commented on projects/1.12.2/assets/speedster-heroes/speedsterheroes/lang/zh_cn.lang
> +speedsterheroes.info.createdtimeremnant=ß4%s创建了一个时间残余!
这里模组内原文如此吗

2023-05-09 11:20 UTC, ChuijkYahus commented on projects/1.12.2/assets/speedster-heroes/speedsterheroes/lang/zh_cn.lang
> +advancement.blackFlash=这不是谁...这是什么...
```suggestion
advancement.blackFlash=这不是谁……这是什么……
```

2023-05-09 11:20 UTC, ChuijkYahus commented on projects/1.12.2/assets/speedster-heroes/speedsterheroes/lang/zh_cn.lang
> +advancement.savitarBlade=我是未来(,)闪电侠!
这个在漫威作品里有原文吗

2023-05-09 12:30 UTC, BayunL commented on projects/1.12.2/assets/speedster-heroes/speedsterheroes/lang/zh_cn.lang
> +speedsterheroes.info.createdtimeremnant=ß4%s创建了一个时间残余!
是的

2023-06-17 01:33 UTC, luoxueyasha commented on projects/1.12.2/assets/speedster-heroes/speedsterheroes/lang/zh_cn.lang
> +speedsterheroes.suitsets.cw_flash.name=闪电侠（电视剧）
这一行文本在游戏内哪里显示

2023-06-17 01:46 UTC, luoxueyasha requested changes

2023-06-17 01:46 UTC, luoxueyasha commented on projects/1.12.2/assets/speedster-heroes/speedsterheroes/lang/zh_cn.lang
> +speedsterheroes.suitsets.cw_flash.name=闪电侠（电视剧）
这一行在游戏内哪里显示

2023-06-17 01:46 UTC, luoxueyasha commented on projects/1.12.2/assets/speedster-heroes/speedsterheroes/lang/zh_cn.lang
> +speedsterheroes.suitsets.comic_speed.name=Speed （漫画）
`Speed`有译名吗

2023-06-17 01:46 UTC, luoxueyasha commented on projects/1.12.2/assets/speedster-heroes/speedsterheroes/lang/zh_cn.lang
> +speedsterheroes.suitsets.comic_speed.name=Speed （漫画）
```suggestion
speedsterheroes.suitsets.comic_speed.name=Speed（漫画）
```

2023-06-17 01:46 UTC, luoxueyasha commented on projects/1.12.2/assets/speedster-heroes/speedsterheroes/lang/zh_cn.lang
> +speedsterheroes.suitsets.cw_flash_season_1.name=闪电侠（电视剧S1）
```suggestion
speedsterheroes.suitsets.cw_flash_season_1.name=闪电侠（电视剧 S1）
```
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/0f53000e-2814-4be2-9705-be2c109c647e)
（https://cfpa.site/TransRules/ ）
此问题请全文通查

2023-06-17 01:46 UTC, luoxueyasha commented on projects/1.12.2/assets/speedster-heroes/speedsterheroes/lang/zh_cn.lang
> +speedsterheroes.abilities.super_speed.desc=允许用户进入超级速度
如何解释`进入超级速度`
```suggestion
speedsterheroes.abilities.super_speed.desc=令使用者进入超级速度
```

2023-06-17 01:46 UTC, luoxueyasha commented on projects/1.12.2/assets/speedster-heroes/speedsterheroes/lang/zh_cn.lang
> +speedsterheroes.abilities.water_running.desc=让你在水上跑步
```suggestion
speedsterheroes.abilities.water_running.desc=可以在水上行走
```
```suggestion
speedsterheroes.abilities.water_running.desc=令使用者能够在水上行走
```
此类生硬机翻请全文通查，并自行修正

2023-06-17 01:46 UTC, luoxueyasha commented on projects/1.12.2/assets/speedster-heroes/speedsterheroes/lang/zh_cn.lang
> +speedsterheroes.info.createdtimeremnant=ß4%s创建了一个时间残余!
```suggestion
speedsterheroes.info.createdtimeremnant=ß4%s创建了一处时间残余！
```

2023-06-17 01:46 UTC, luoxueyasha commented on projects/1.12.2/assets/speedster-heroes/speedsterheroes/lang/zh_cn.lang
> +advancement.savitarBlade=我是未来（,）闪电侠!
```suggestion
advancement.savitarBlade=我就是未来 闪电侠！
```
看了下语境，这个双关翻的有点生硬了

2023-06-24 22:45 UTC, luoxueyasha commented
@ChuijkYahus 请求对此pr进入7+7流程

2023-06-25 04:29 UTC, ChuijkYahus commented
* 7+7时限进入第一阶段，请注意查看审核意见

@BayunL

2023-07-09 21:06 UTC, closed without merging