Architects Palette 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #3273
Opened 2023-05-08 18:23 UTC by ChuijkYahus

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-07-21 08:57 UTC, mamaruo reviewed
一波混

2023-07-21 08:57 UTC, mamaruo commented on projects/1.18/assets/architects-palette/architects_palette/lang/zh_cn.json
> +  "block.architects_palette.spruce_board_wall": "云杉木宽板墙",
| **审查级别** |
|--------------|
| ⚪ 轻微 / 不阻止合并但需三思 |



原文：**Spruce Board Wall**
```suggestion
  "block.architects_palette.spruce_board_wall": "云杉宽木板墙",
```

2023-07-21 08:57 UTC, mamaruo commented on projects/1.18/assets/architects-palette/architects_palette/lang/zh_cn.json
> +  "block.architects_palette.stone_nub": "石小块",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

原文：**Stone Nub**
```suggestion
  "block.architects_palette.stone_nub": "石头小块",
```

2023-07-21 08:57 UTC, mamaruo commented on projects/1.18/assets/architects-palette/architects_palette/lang/zh_cn.json
> +  "block.architects_palette.oracle_lamp": "紫谕 Lamp",
| **审查级别**   |
|-------------|
| 🔴 严重 / **阻止合并，刻不容缓** |

原文：**Oracle Lamp**
```suggestion
  "block.architects_palette.oracle_lamp": "紫谕灯",
```

2023-07-21 12:23 UTC, ChuijkYahus commented on projects/1.18/assets/architects-palette/architects_palette/lang/zh_cn.json
> +  "block.architects_palette.spruce_board_wall": "云杉木宽板墙",
算是对everycomp的妥协？
改了

2023-07-24 06:47 UTC, DrIceTea123 requested changes
大概看了一眼

2023-07-24 06:47 UTC, DrIceTea123 commented on projects/1.19/assets/architects-palette/architects_palette/lang/zh_cn.json
> +  "block.architects_palette.chiseled_basalt_tiles": "錾制玄武岩瓦",
1.19是`雕纹`吧

2023-07-24 06:47 UTC, DrIceTea123 commented on projects/1.18/assets/architects-palette/architects_palette/lang/zh_cn.json
> +  "tag.c.withered_bones": "Withered Bones",
漏译吗

2023-07-24 07:36 UTC, ChuijkYahus commented on projects/1.19/assets/architects-palette/architects_palette/lang/zh_cn.json
> +  "block.architects_palette.chiseled_basalt_tiles": "錾制玄武岩瓦",
1192及以下为錾制，1193及以上为雕纹
这模组是1192的

2023-07-24 09:50 UTC, DrIceTea123 requested changes

2023-07-24 09:50 UTC, DrIceTea123 commented on projects/1.19/assets/architects-palette/architects_palette/lang/zh_cn.json
> +  "tag.c.withered_bones": "凋灵骨",
哈？怎么是`凋灵`
你考虑是改L234还是这一行

2023-07-24 10:08 UTC, ChuijkYahus commented on projects/1.19/assets/architects-palette/architects_palette/lang/zh_cn.json
> +  "tag.c.withered_bones": "凋灵骨",
寄
输入法打错了，改这一行
这个算是所有此类方块的全称，`头`不加

2023-07-24 10:54 UTC, DrIceTea123 approved these changes

2023-08-05 06:46 UTC, merged