Statues 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3304
Opened 2023-05-19 20:40 UTC by a5161655

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-05-19 20:44 UTC, a5161655 commented
直接修改官中进行的翻译，可能要检查的地方挺多

2023-05-20 03:31 UTC, A-Black-Fish commented
> ❌ 警告：检测到可能的错误译名：`浅灰色`，原版译名采用`淡灰色`。例如行 ` "block.statues.sheep_statue_light_gray": "浅灰色咩咩雕像",`。 ℹ 注意：检测到可能的争议译名：`粉色`，原版译名采用`粉红色`，**如果上下文中有原版的 16 色才需要更改**。例如行 ` "block.statues.sheep_statue_pink": "粉色咩咩雕像",`。 ❌ 警告：检测到可能的错误译名：`爬行者`，`爬行者`在 1.15 后更名为`苦力怕`。例如行 ` "entity.statues.fake_creeper.name": "爬行者",`。

2023-05-20 03:52 UTC, A-Black-Fish commented on projects/1.16/assets/statues/statues/lang/zh_cn.json
> +	"gui.statue.fill": "装填交互",
奇怪的句子增加了

2023-05-20 03:52 UTC, A-Black-Fish commented on projects/1.16/assets/statues/statues/lang/zh_cn.json
> +	"block.statues.pebble": "卵石",
```suggestion
	"block.statues.pebble": "鹅卵石",
```

2023-05-20 03:52 UTC, A-Black-Fish commented on projects/1.16/assets/statues/statues/lang/zh_cn.json
> +	"entity.statues.fake_creeper.name": "爬行者",
```suggestion
	"entity.statues.fake_creeper.name": "苦力怕",
```

2023-05-20 04:00 UTC, luoxueyasha requested changes
只审了一半，疑似机翻润色
建议阅读 [Minecraft Wiki:译名标准化](https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96)
部分问题仅指出一处，请全文通查

2023-05-20 06:14 UTC, a5161655 commented on projects/1.16/assets/statues/statues/lang/zh_cn.json
> +	"block.statues.sheep_statue_lime": "酸橙咩咩雕像",
部分是官中
我要不要重新来过

2023-05-20 06:25 UTC, closed without merging