pams-breadcraft翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3321
Opened 2023-05-24 05:44 UTC by Lulilaya

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-05-24 18:20 UTC, ChuijkYahus requested changes
之前绝对在群里讨论过这个模组
推荐还是找了解烘焙的人来再审核一遍

顺便PR名称需要按照CONTRIBUTING进行修改，这样的PR名称是不行的（虽然也没啥大问题）

2023-05-24 18:20 UTC, ChuijkYahus commented on projects/1.12.2/assets/pams-breadcraft/pamsbreadcraft/lang/zh_cn.lang
> +item.macandcheese.name=起司通心粉
```suggestion
item.macandcheese.name=奶酪通心粉
```
```suggestion
item.macandcheese.name=芝士通心粉
```
这东西真是，奶酪、干酪、芝士、起司

2023-05-24 18:20 UTC, ChuijkYahus commented on projects/1.12.2/assets/pams-breadcraft/pamsbreadcraft/lang/zh_cn.lang
> +item.molasses.name=糖浆
```suggestion
item.molasses.name=糖蜜
```
感觉糖浆syrup多点

2023-05-24 18:20 UTC, ChuijkYahus commented on projects/1.12.2/assets/pams-breadcraft/pamsbreadcraft/lang/zh_cn.lang
> +item.obwarzanekkrakowski.name=波兰面包圈
```suggestion
item.obwarzanekkrakowski.name=克拉科夫面包圈
```
krakowski

2023-05-24 18:20 UTC, ChuijkYahus commented on projects/1.12.2/assets/pams-breadcraft/pamsbreadcraft/lang/zh_cn.lang
> +item.panecasereccio.name=卡塞雷西奥窗格面包
意大利语中casereccio指“自制的；家常的”

2023-05-24 18:20 UTC, ChuijkYahus commented on projects/1.12.2/assets/pams-breadcraft/pamsbreadcraft/lang/zh_cn.lang
> +item.panettone.name=托尼甜面包
```suggestion
item.panettone.name=意大利面包
```
https://baike.baidu.com/item/%E6%84%8F%E5%A4%A7%E5%88%A9%E9%9D%A2%E5%8C%85/11029360?fr=aladdin
https://zh.wikipedia.org/zh-cn/%E6%84%8F%E5%A4%A7%E5%88%A9%E9%BA%B5%E5%8C%85
其实不改也没啥问题

2023-05-24 18:20 UTC, ChuijkYahus commented on projects/1.12.2/assets/pams-breadcraft/pamsbreadcraft/lang/zh_cn.lang
> +item.pretzelbread.name=法式咸香小面包
```suggestion
item.pretzelbread.name=椒盐卷饼
```
虽然这东西最常和德国联系起来（每日乳法），单词的发音也是德式的

2023-05-24 18:20 UTC, ChuijkYahus commented on projects/1.12.2/assets/pams-breadcraft/pamsbreadcraft/lang/zh_cn.lang
> +item.rosette.name=意大利经典面包
```suggestion
item.rosette.name=意大利玫瑰面包
```
属于是意译rosette了
这种面包还有一个称呼是michetta

2023-05-25 05:44 UTC, Lulilaya commented on projects/1.12.2/assets/pams-breadcraft/pamsbreadcraft/lang/zh_cn.lang
> +item.pretzelbread.name=法式咸香小面包
Pretzel查询得到德式碱水面包，和椒盐卷饼不是一个玩意了。
可是游戏里这玩意也不是特别像传统那样碱水结啊……色泽和切口倒是符合碱水面包的样子就是了。

2023-05-25 10:53 UTC, ChuijkYahus commented on projects/1.12.2/assets/pams-breadcraft/pamsbreadcraft/lang/zh_cn.lang
> +item.pretzelbread.name=德式碱水面包
![图片](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/1f9173e5-02ae-4d21-84c9-141494b997b9)
![图片](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/ed25b3bb-dfbb-4c23-9213-c183289b529f)
貌似椒盐卷饼会常用些，不过随意

2023-05-25 10:53 UTC, ChuijkYahus commented on projects/1.12.2/assets/pams-breadcraft/pamsbreadcraft/lang/zh_cn.lang
> +item.panecasereccio.name=卡塞雷西奥窗格面包
```suggestion
item.panecasereccio.name=卡塞雷乔窗格面包
```

2023-05-26 00:32 UTC, Lulilaya commented on projects/1.12.2/assets/pams-breadcraft/pamsbreadcraft/lang/zh_cn.lang
> +item.pretzelbread.name=德式碱水面包
烘焙方面现在更常用的是碱水面包这一说法，表皮棕红色口感劲道，但不是很好吃（个人感觉）。
常见的是碱水结，就是图片里那样的形状，但是在游戏里则是面包形式（窗格面包那样）。

2023-05-26 00:40 UTC, ChuijkYahus approved these changes

2023-05-27 03:59 UTC, merged