mythicmetals 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3325
Opened 2023-05-26 03:58 UTC by geyuhao1235

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-05-31 20:04 UTC, ChuijkYahus requested changes

2023-05-31 20:04 UTC, ChuijkYahus commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "entity.mythicmetals.star_platinum_arrow": "星之白金箭",
```suggestion
  "entity.mythicmetals.star_platinum_arrow": "星辰铂金箭",
```

2023-05-31 20:04 UTC, ChuijkYahus commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "effect.mythicmetals.wormhole_special": "虫洞特效",
请上下保持一致

2023-05-31 20:04 UTC, ChuijkYahus commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "block.mythicmetals.banglum_tnt": "聚爆石岩TNT",
```suggestion
  "block.mythicmetals.banglum_anvil": "聚爆石砧",
  "block.mythicmetals.banglum_block": "聚爆石块",
  "block.mythicmetals.banglum_nuke_core": "聚爆石岩芯块",
  "block.mythicmetals.banglum_ore": "聚爆石矿石",
  "block.mythicmetals.banglum_tnt": "聚爆石TNT",
```
这个nuke core是什么

2023-05-31 20:04 UTC, ChuijkYahus commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "block.mythicmetals.nether_banglum_ore": "下界聚爆石岩矿石",
```suggestion
  "block.mythicmetals.nether_banglum_ore": "下界聚爆石矿石",
```

2023-06-01 10:54 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "block.mythicmetals.deepslate_runite_ore": "深层粗符石块",
已修订

2023-06-01 10:55 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "item.mythicmetals.banglum_helmet": "聚爆石岩头盔",
无，错误翻译。已修订。

2023-06-01 10:55 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "item.mythicmetals.celestium_boots": "倚天胸甲",
已修订。

2023-06-01 10:55 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "item.mythicmetals.raw_aquarium": "粗破浪岩",
已修订。

2023-06-01 10:57 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "item.mythicmetals.raw_stormyx": "粗飓霆岩",
已修订。

2023-06-01 10:57 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "item.mythicmetals.tipped_runite_arrow": "涂层符文箭",
已修订。

2023-06-01 10:57 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "item.mythicmetals.tipped_runite_arrow.effect.slow_falling": "缓降的涂层符石箭",
已修订。

2023-06-01 10:58 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "item.mythicmetals.white_aegis_sword": "神盾之剑",
已采取。

2023-06-01 10:58 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "text.config.mythicmetals.category.deepslateRunite": "深板岩符石矿石设置",
已修订。

2023-06-01 10:58 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "text.config.mythicmetals.category.overworldNetherOres": "主世界地狱矿石设置",
已修订。

2023-06-01 10:58 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "text.config.mythicmetals.option.adamantite.offset": "精金矿石的生成范围应该位移吗?",
已修订。

2023-06-01 10:59 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "text.config.mythicmetals.option.adamantite.trapezoid": "精金矿石的生成范围应该成梯形状吗?",
已修订。

2023-06-01 10:59 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "text.config.mythicmetals.option.deepslateRunite.veinSize": "深板岩符石矿脉的最大大小",
已修订。

2023-06-01 10:59 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "text.config.mythicmetals.option.enableNuggets": "启用块",
已修订。

2023-06-01 10:59 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "text.config.mythicmetals.option.endStarrite.veinSize": "末地星辰的最大大小",
已修订。

2023-06-01 10:59 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "subtitles.mythicmetals.equip_runite": "熟悉的盔甲哗啦声",
已采取。

2023-06-01 10:59 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.aquarium.description": "在汪洋的大海之下开采破浪岩",
已修订。

2023-06-01 10:59 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.adamantite.description": "在暗黑深渊的最底层开采精金",
已修订。

2023-06-01 10:59 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.aquarium_pearl.title": "如同以太龙一般耀眼",
已修订。

2023-06-01 11:00 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.banglum.description": "开采聚爆石石，其他所有矿产的奠基石",
已修订。

2023-06-01 11:00 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "entity.mythicmetals.banglum_nuke": "已引爆的核弹",
已采取反应堆翻译。

2023-06-01 11:01 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "block.mythicmetals.nether_banglum_ore": "下界聚爆石岩矿石",
已修订。

2023-06-01 11:01 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "item.mythicmetals.runite_boots": "靴子",
已修订。

2023-06-01 11:01 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "item.mythicmetals.steel_pickaxe": "钢稿",
已修订。

2023-06-01 11:02 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "text.config.mythicmetals.option.blacklist": "Biome Blacklist",
已修订。

2023-06-01 11:02 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "text.config.mythicmetals.enum.shieldPosition": "点金石盾牌 HUD 位置",
已修订。

2023-06-01 11:02 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "itemGroup.mythicmetals.main.button.discord": "需要帮助请加入Wraith Coding Sesh的Discord服务器.",
已修订。

2023-06-01 11:02 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.adamantite.title": "天堂制造",
已采取。

2023-06-01 11:02 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.banglum_chunk.description": "罕见的伴生矿，具有异常优秀防爆抗性",
已修订。

2023-06-01 11:03 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "item.mythicmetals.carmot_staff": "点金石剑",
已采取点金权杖翻译。

2023-06-01 11:04 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.carmot_staff.description": "使用点金石来制作点金法杖，其能力取决于内部的方块",
已采取点金权杖翻译。

2023-06-01 11:04 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.durasteel.title": "很久以前来自一个遥远的星系……",
已修订。

2023-06-01 11:05 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.durasteel.description": "用兆金锭与锰锭锻造出韧钢：一块更比六块强",
已修订。

2023-06-01 11:05 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "block.alloy_forgery.adamantite_block_forge_controller": "精金熔炉控制器",
已修订。

2023-06-01 11:05 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.forgery.title": "我以为这是一座熔炉",
已修订。

2023-06-01 11:05 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "item.mythicmetals.gilded_midas_gold_sword": "镀金迈达斯黄金剑",
已修订。

2023-06-01 11:06 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.gilded_midas_gold_sword.description": "制作一把镀金的迈达斯黄金剑，一种更强大的黄金武器",
已修订。

2023-06-01 11:06 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.hallowed.title": "出淤泥而不染",
已修订。

2023-06-01 11:06 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.hallowed.description": "用高等级锻造台加工来自暗黑深渊的矿物，锻造出神圣锭",
已修订。

2023-06-01 11:07 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.maxed_midas_gold_sword.description": "将迈达斯黄金剑的等级提升至最高",
已修订。

2023-06-01 11:07 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.mythril.description": "在暗黑深渊的上层开采秘银",
已修订。

2023-06-01 11:07 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.orichalcum.description": "在暗黑深渊的四处开采山铜",
已修订。

2023-06-01 11:07 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.orichalcum_hammer.description": "制作奥利哈刚锤子，可以更快地开凿长隧道",
已修订。

2023-06-01 11:07 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.palladium.description": "在地狱的熔岩海洋下通常可以找到钯",
已修订。

2023-06-01 11:07 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.palladium.title": "茄汁焗黄豆——打一矿物",
已修订。

2023-06-01 11:08 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.runite.title": "恰逢其时......",
已修订。

2023-06-01 11:08 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.starrite.description": "开采在末地里常见的星辰矿",
已修订。

2023-06-01 11:08 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.steel.description": "锻造钢铁，一种由铁和锰混合的简单合金",
已修订。

2023-06-01 11:08 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.steel.title": "但是钢比...更重",
已修订。

2023-06-01 11:08 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.stormyx.description": "在下界岩与黑石的庇护下开采飓霆矿",
已修订。

2023-06-01 11:09 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.unobtainium.description": "在层层的深板岩中开采叵得素",
已修订。

2023-06-01 11:10 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "effect.mythicmetals.heat": "热能",
已修订。

2023-06-01 11:13 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.intentional_combusting_mechanics.description": "滥用有意的游戏机制，在自己身上施加燃烧效果",
已修订。

2023-06-01 11:13 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.superhot.description": "尝试同时承受热和燃烧，而不成为木炭",
已修订。

2023-06-01 11:13 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.intentional_combusting_mechanics.title": "基于原理",
已修订。

2023-06-01 11:13 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "tooltip.midas_gold.level.0": "可以在铁匠台上使用中黄金块强化",
已修订。

2023-06-01 11:13 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "tooltip.midas_gold.level.1": "你需要相当数量的中黄金块才能解锁其真正的力量...",
已修订。

2023-06-01 11:13 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "tooltip.midas_gold.level.2": "超过一百个块。令人印象深刻！继续加油！",
已修订。

2023-06-01 11:14 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "tooltip.midas_gold.level.3": "你为什么要制造这么多块？只需制造普通黄金即可...",
已修订。

2023-06-01 11:14 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "tooltip.midas_gold.level.4": "剑感觉更强大了...还能再进一步吗？",
已修订。

2023-06-01 11:14 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "tooltip.midas_gold.level.5": "国王米达斯会为这件武器感到骄傲",
已修订。

2023-06-01 11:14 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +    {"text": "fuser", "color": "#512FC2"}
已修订。

2023-06-01 11:14 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "tooltip.carmot_staff.stormyx": "独特能力 - 投射物屏障",
已修订。

2023-06-01 11:15 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "tooltip.carmot_staff.command_block": "创造力之力 - 右键单击升天",
已修订。

2023-06-01 11:15 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "tooltip.carmot_staff.empty_staff": "右键单击插入块",
已修订。

2023-06-01 11:15 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "tooltip.carmot_staff.unobtainium": "ONE PIECE 真的存在!",
已修订。

2023-06-01 11:15 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "death.attack.banglum_nuke.player": "%2$s引爆了%1$s",
已修订。

2023-06-01 11:15 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "entity.mythicmetals.star_platinum_arrow": "星之白金箭",
已修订。

2023-06-03 18:18 UTC, ChuijkYahus reviewed
其余感觉差不多了

2023-06-03 18:18 UTC, ChuijkYahus commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "text.config.mythicmetals.option.enableNuggets": "启用块",
```suggestion
  "text.config.mythicmetals.option.enableDusts": "启用粉",
  "text.config.mythicmetals.option.enableNuggets": "启用粒",
```
莫名错位（）

2023-06-03 18:18 UTC, ChuijkYahus commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "text.config.mythicmetals.enum.shieldPosition": "点金石盾牌HUD位",
```suggestion
  "text.config.mythicmetals.enum.shieldPosition": "点金石盾牌HUD位置",
```

2023-06-03 18:18 UTC, ChuijkYahus commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "subtitles.mythicmetals.equip_runite": "熟悉的盔甲：铿锵",
话说这里原文的familiar有来由吗（）

2023-06-03 18:18 UTC, ChuijkYahus commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "advancement.mythicmetals.stormyx_shell.description": "获得一枚飓霆贝壳，它很少从飓霆矿石中掉落",
```suggestion
  "advancement.mythicmetals.stormyx_shell.description": "获得一枚飓霆贝壳，它偶尔会从飓霆矿石中掉落",
```

2023-06-03 18:18 UTC, ChuijkYahus commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "tooltip.carmot_staff.midas_gold": "独特能力 - 范围幸运2",
```suggestion
  "tooltip.carmot_staff.midas_gold": "独特能力 - 范围幸运 II",
```
这里看下是不是MC原版的幸运状态效果

2023-06-03 18:18 UTC, ChuijkYahus commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "tooltip.carmot_staff.gold": "独特能力 - 幸运1",
```suggestion
  "tooltip.carmot_staff.gold": "独特能力 - 幸运 I",
```

2023-06-04 14:06 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "subtitles.mythicmetals.equip_runite": "熟悉的盔甲：铿锵",
我并没有在模组菜单里找到这个设置选项，我个人认为这个设置选项也许不翻译为好。

2023-06-04 16:24 UTC, ChuijkYahus commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "subtitles.mythicmetals.equip_runite": "熟悉的盔甲：铿锵",
这个是字幕啊
不能不翻的

2023-06-04 16:25 UTC, ChuijkYahus commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "subtitles.mythicmetals.equip_runite": "熟悉的盔甲：铿锵",
推荐实际测试一下是穿上什么盔甲的时候发出的音效，不能直接删除
@geyuhao1235

2023-06-05 09:22 UTC, geyuhao1235 commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "subtitles.mythicmetals.equip_runite": "熟悉的盔甲：铿锵",
已经查明是穿戴符石装备所发出的“咔嗒”声，与穿戴该模组的其他装备音效不同，可视为是致敬向物品。
其中符石（Runite）是源自《runescape》这款和《魔兽世界》相提并论的游戏中的物品，我本人并未玩过该游戏，并不知晓穿戴《runescape》游戏中的符石装备会不会有该音效，但是因为神话金属模组中的符石（Runite）图标和《runescape》游戏中的符石一模一样，因此我认为他们直接存在致敬的关系。
根据原文"Familiar armor clank"我将其修改为更贴近语境的 "熟悉的盔甲咔嗒声"。

2023-06-05 10:50 UTC, ChuijkYahus reviewed
可以再看下模组最新版有没有还需要更新的键

2023-06-05 10:50 UTC, ChuijkYahus commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "text.config.mythicmetals.option.kyber.trapezoid": "凯伯矿石应该以梯形状分布吗?",
```suggestion
  "text.config.mythicmetals.option.kyber.trapezoid": "凯伯矿石应该以梯形状分布吗？",
```
请全文通查

2023-06-05 10:50 UTC, ChuijkYahus commented on projects/1.19/assets/mythicmetals/mythicmetals/lang/zh_cn.json
> +  "subtitles.mythicmetals.equip_runite": "熟悉的盔甲咔嗒声",
```suggestion
  "subtitles.mythicmetals.equip_runite": "盔甲：熟悉的铿锵声",
```
对应音效疑似RuneScape里穿戴盔甲的音效，搜了油管和相关维基也没能找到完全符合的音效（）
以及原版的字幕是有既定格式的，请注意遵守
![图片](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/eae4b92c-b839-4cde-831b-9fead5fa3754)
![图片](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/c11dc30a-cf51-4dd1-a54c-080b0094c78d)

2023-06-06 07:32 UTC, ChuijkYahus approved these changes

2023-06-08 04:34 UTC, merged