黑暗之魂mod翻译-修改2
CFPAOrg/Minecraft-Mod-Language-Package pull request #3339
Opened 2023-06-01 09:07 UTC by tukuai332

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2023-06-01 09:22 UTC, komeiji-koyomi commented on projects/1.18/assets/minecraft-dark-souls/darksouls/lang/zh_cn.json
> +	"gui.darksouls.estus_heal_level_tooltip": "原素瓶恢复量 \n\u00A77燃烧不死人遗骨来提升原素瓶的恢复量",
这两行丢词了，没玩过黑魂系列的看不懂具体的使用方法
这首先是一个Minecraft的模组，不能默认所有玩家均了解模组本身的背景

2023-06-01 09:27 UTC, komeiji-koyomi commented on projects/1.18/assets/minecraft-dark-souls/darksouls/lang/zh_cn.json
> +	"tooltip.darksouls.ashen_estus_flask.extended": "这个灰瓶能将营火的热转冷，\n是与无火的余灰相符的物品",
与游戏原文不符，也不能正确表达原文含义

2023-06-01 09:29 UTC, komeiji-koyomi commented
只随意抽查了几个片段，但是已经发现大量意义不明且与游戏原文不符的翻译
建议从头自查，不要急于上传自己的翻译

2023-06-01 22:53 UTC, A-Black-Fish commented
请更新标题为`MC: Dark Souls 翻译提交`

2023-06-06 07:58 UTC, Rinko1231 requested changes

2023-06-06 07:58 UTC, Rinko1231 commented on projects/1.18/assets/minecraft-dark-souls/darksouls/lang/zh_cn.json
> +	"item.darksouls.estus_flask": "元素瓶",
```suggestion
	"item.darksouls.estus_flask": "原素瓶",
```

2023-06-06 07:58 UTC, Rinko1231 commented on projects/1.18/assets/minecraft-dark-souls/darksouls/lang/zh_cn.json
> +	"item.darksouls.estus_shard": "元素碎片",
```suggestion
	"item.darksouls.estus_shard": "原素碎片",
```

2023-06-11 11:37 UTC, luoxueyasha commented
请更新PR标题为 `MC: Dark Souls 翻译提交` 。
点击PR页面右侧的“Edit”按钮即可修改PR标题，如下图红圈内所示。
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/22f2b292-6982-410c-8204-b510fbcc206e)

2023-07-30 10:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3339) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3339) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3339) it.</sub>

2023-09-02 11:03 UTC, ChuijkYahus commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

请注意签署CLA

@tukuai332

2023-09-09 03:10 UTC, ChuijkYahus commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@tukuai332

2023-09-10 08:07 UTC, closed without merging