TIS Advanced物品及手册翻译上传
CFPAOrg/Minecraft-Mod-Language-Package pull request #3346
Opened 2023-06-03 14:09 UTC by HfSrJun

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-06-03 14:17 UTC, HfSrJun commented
手册内多余空格是为了解决游戏内markdown渲染的错误换行问题，并非文本错误

2023-06-04 10:59 UTC, ChuijkYahus commented
/add-mapping tis-advanced 833240

2023-06-04 11:12 UTC, ChuijkYahus commented on projects/1.18/assets/tis-advanced/tisadvanced/lang/zh_cn.json
> +    "item.tisadvanced.seven_segment_display" : "七段显示门",
```suggestion
    "item.tisadvanced.seven_segment_display" : "七段数码管",
```

2023-06-04 11:12 UTC, ChuijkYahus commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/asic_module.md
> +所有三角函数计算都以角度而不是弧度进行
```suggestion
所有三角函数计算都以角度而不是弧度进行。
```

2023-06-04 11:12 UTC, ChuijkYahus commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/radar_module.md
> +- PROJ：发射物，此过滤器匹配发射物，例如箭和火焰 弹。
```suggestion
- PROJ：弹射物，此过滤器匹配弹射物，例如箭和火焰 弹。
```

2023-06-04 11:12 UTC, ChuijkYahus commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/radio_module.md
> +无线电模块相较于红外模块能够以更远的距离和不受直线限制传输数值。无线电传输的数值会被发送到*所有*距 离在256米以内的活动的无线电模块。
```suggestion
无线电模块相较于红外模块能够以更远的距离和不受直线限制传输数值。无线电传输的数值会被发送到*所有*距 离在256m以内的活动的无线电模块。
```

2023-06-04 11:12 UTC, ChuijkYahus commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/seven_segment_display.md
> +# 七段显示门
```suggestion
# 七段数码管
```

2023-06-04 11:12 UTC, ChuijkYahus commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/seven_segment_display.md
> +七段显示门模块是一个简化的显示模块，能够很容易地显示数字。向此模块写入一个16位二进制值就会激活设置为为1的二进制位对应的显示段。16个二进制位中的每一个都可以根据下面的示意图激活一个显示段：
```suggestion
七段数码管模块是一个简化的显示模块，能够很容易地显示数字。向此模块写入一个16位二进制值就会激活设置为1的二进制位对应的显示段。16个二进制位中的每一个都可以根据下面的示意图激活一个显示段：
```

2023-06-04 11:12 UTC, ChuijkYahus commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/tape_storage.md
> +- `4`：将磁带向后卷动，比特位数等于附加数据值
```suggestion
- `1`：将磁带向前卷动一字节，附加数据值会被丢弃
- `2`：将磁带向后卷动一字节，附加数据值会被丢弃
- `3`：将磁带向前卷动，字节数等于附加数据值
- `4`：将磁带向后卷动，字节数等于附加数据值
```

2023-06-04 11:12 UTC, ChuijkYahus commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/tape_storage.md
> +读取操作会返回读写头当前所在比特位的数值。写入操作可以用来覆写磁头当前位置的数据，或者卷动磁带到另一个位置。写入操作接收一个16位二进制值，其高8位被理解为操作码，指示磁带的动作。其低8位是操作码使用的附加数据。下面是各个操作码的文档：
```suggestion
读取操作会返回读写头当前所在字节的数值。写入操作可以用来覆写磁头当前位置的数据，或者卷动磁带到另一个位置。写入操作接收一个16位二进制值，其高8位被理解为操作码，指示磁带的动作。其低8位是操作码使用的附加数据。下面是各个操作码的文档：
```

2023-06-04 11:12 UTC, ChuijkYahus commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/tisadvanced.md
> +*译注：Msb即Most-Significant-Bit，最高有效位*
这行需要保留吗

2023-06-04 11:12 UTC, ChuijkYahus commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/tisadvanced.md
> +- [七段显示门](modules/seven_segment_display.md)
```suggestion
- [七段数码管](modules/seven_segment_display.md)
```

2023-06-04 11:39 UTC, HfSrJun commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/radar_module.md
> +- PROJ：发射物，此过滤器匹配发射物，例如箭和火焰 弹。
因为这里的projectile指的是射出的箭和射出的火焰弹，发射物或者抛射物这种更能体现“射”的翻译是不是会更好
https://dictionary.cambridge.org/zhs/%E8%AF%8D%E5%85%B8/%E8%8B%B1%E8%AF%AD-%E6%B1%89%E8%AF%AD-%E7%AE%80%E4%BD%93/projectile

2023-06-04 11:41 UTC, HfSrJun commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/tape_storage.md
> +- `4`：将磁带向后卷动，比特位数等于附加数据值
我的锅，通宵翻译翻到快要昏古七了，连字节和位都分不清了

2023-06-04 11:43 UTC, HfSrJun commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/tisadvanced.md
> +*译注：Msb即Most-Significant-Bit，最高有效位*
其实都可。我的考虑是在bing上搜索msb0结果太乱不能一眼找到msb0的解释，所以添加了注释。

2023-06-04 11:54 UTC, ChuijkYahus commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/radar_module.md
> +- PROJ：发射物，此过滤器匹配发射物，例如箭和火焰 弹。
https://minecraft.fandom.com/zh/wiki/%E5%BC%B9%E5%B0%84%E7%89%A9
mc术语

2023-06-04 11:56 UTC, ChuijkYahus commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/tisadvanced.md
> +*译注：Msb即Most-Significant-Bit，最高有效位*
随意

2023-06-10 16:39 UTC, ChuijkYahus commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/radar_module.md
> +![有时候最好在它击中你之前知道是什么东西过来了](item:tisadvanced:radar_module)
```suggestion
![有时候最好在它击中你之前就知道是什么东西过来了](item:tisadvanced:radar_module)
```

2023-06-10 16:39 UTC, ChuijkYahus commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/seven_segment_display.md
> +![七段显示门示意图](../img/seven_segment_display_diagram.png)
```suggestion
![七段数码管示意图](../img/seven_segment_display_diagram.png)
```

2023-06-11 13:31 UTC, luoxueyasha requested changes
就看了两处，结论是机翻味太浓，文本不够书面化
参考资料：

2023-06-11 13:31 UTC, luoxueyasha commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/seven_segment_display.md
> +七段数码管模块是一个简化的显示模块，能够很容易地显示数字。向此模块写入一个16位二进制值就会激活设置为1的二进制位对应的显示段。16个二进制位中的每一个都可以根据下面的示意图激活一个显示段：
```suggestion
七段数码管模块是能便捷显示数字的简易显示模块。向此模块写入一个16位数据将会激活置为1的位所对应的数码管。16位输入与各数码管的映射关系如下图所示：
```

2023-06-11 13:31 UTC, luoxueyasha commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/seven_segment_display.md
> +用染料右键安装好的模块可以把激活的显示段颜色改变为染料的颜色。
```suggestion
手持染料右击安装好的模块可以将激活的数码管颜色改变为染料的颜色。
```

2023-06-11 14:02 UTC, HfSrJun commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/seven_segment_display.md
> +用染料右键安装好的模块可以把激活的显示段颜色改变为染料的颜色。
“数码管”指的是整个元件，这里的segment指的是上面的笔画。因为这东西叫“七段数码管”所以我翻译为显示段
也有人翻译为字段，指的都是一个东西。或许可以翻译成笔画更加易于理解
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/96952179/d5c47963-8461-4071-aaad-59a8e980d6e3)

2023-06-12 00:28 UTC, luoxueyasha requested changes

2023-06-12 00:28 UTC, luoxueyasha commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/radar_module.md
> +雷达模块可以用来探测周围的实体，并记录其信息。写入操作控制模块的设置，读取操作返回目标实体的信息。模块设置的描述如下：
```suggestion
雷达模块可以用来探测并记录周围的实体信息。通过写入操作可以修改模块的设置，通过读取操作可以返回目标实体的数据。对模块的设置值格式如下所示：
```

2023-06-12 00:28 UTC, luoxueyasha commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/radar_module.md
> +第0位：如果最高位为1，那后续的读取操作会从离雷达模块最远的实体开始选择目标，而不是最近的。参阅下面的索引参数获取更多信息。
```suggestion
第0位：如果最高有效位被置为1，那后续的读取操作会从距离雷达模块最远（而非最近）的实体开始选择目标。详见后文的索引参数格式。
```
看到下方也对最高有效位进行译注了，感觉所有文档的这个问题统一一下比较好

2023-06-12 00:28 UTC, luoxueyasha commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/radar_module.md
> +第1-2位：1和2位表示应该计算实体与雷达模块在哪条 轴上的距离。0是个特殊的值，会返回实体与雷达之间的直线距离。把这个值设定为1会让读取操作返回雷达与实体在X轴上的距离。把这个值设定为2或3会让读取操作分别返回Y或者Z轴距离。
```suggestion
第1-2位：该两位用于设定实体与雷达模块在在各轴上的偏移量计算模式。将值置为特殊值0时，模块将返回实体与雷达之间的直线距离（欧几里得距离）。将值置为1时，模块将通过读取操作返回雷达与实体在X轴上的偏移量。同理，将值置为2或3会让模块通过读取操作分别返回Y轴上或Z轴上的偏移量。
```

2023-06-12 00:28 UTC, luoxueyasha commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/radar_module.md
> +第3-15位：剩下的位对应目标实体的索引。把这个值设 定为0会选择离雷达模块最近的实体为目标（如果第0位设为1那么就是最远的）。把这个值设定为1或者更大那就会选择离雷达第几近（或远）的实体成为雷达模块的目标。
```suggestion
第3-15位：其余各位用于设置对目标实体的索引。将值置为0会令模块选择距离最近的实体为目标（如果第0位被置为1，则会选择最远的实体）。将该值置为n（n≥1）会令模块选择距离雷达第n近（或远）的实体为目标。
```

2023-06-12 00:28 UTC, luoxueyasha commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/radar_module.md
> +另外，手持并且右键（或者潜行右键）雷达模块可以控制实体过滤器。下面是可用的过滤器：
```suggestion
另外，手持并右击（或潜行右击）雷达模块可以设置实体过滤器模式。可用的过滤器如下所示：
```
此问题请全文通查

2023-06-12 00:28 UTC, luoxueyasha commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/radar_module.md
> +- MONSTER：怪物，此过滤器匹配敌对生物和BOSS生物。
这行和下方的`与`、`和`，你选一个做统一吧

2023-06-12 00:28 UTC, luoxueyasha commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/radar_module.md
> +模块右上角的指示灯代表上次扫描有无实体匹配设置的过滤器，如果灯为绿色，则代表找到了匹配的实体。如果灯为红色，则代表未找到匹配的实体。
```suggestion
模块右上角的指示灯代表上次扫描中有无实体与设置的过滤器所匹配；如果灯为绿色，则代表存在匹配的实体。如果灯为红色，则代表不存在匹配的实体。
```
这里还是把前半句的`匹配`后置比较好，否则容易看乱

2023-06-12 16:53 UTC, HfSrJun commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/radar_module.md
> +另外，手持并且右键（或者潜行右键）雷达模块可以控制实体过滤器。下面是可用的过滤器：
因为自己习惯把右键单击直接说成是右键所以翻译的时候就这么打了...

2023-06-13 01:39 UTC, luoxueyasha requested changes

2023-06-13 01:39 UTC, luoxueyasha commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/radio_module.md
> +# 无线电模块
确定是`无线电模块`而非`广播模块`、`无线通信模块`吗
要修改请所有文档全文通查

2023-06-13 01:39 UTC, luoxueyasha commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/asic_module.md
> +若要计算这些功能的输出值，则需要把输入数据写入模块，此时模块会向它的全部四个端口写入输出数据。一个输出值只会被转移到一个端口，不会重复。**所有的输入输出值均为IEEE-754半精度浮点数。**
```suggestion
若要计算这些功能的输出值，则需要把输入数据写入模块，此时模块会向所有四个端口写入输出数据。一个输出值只会被传输到一个端口。**所有的输入输出值均为IEEE-754半精度浮点数。**
```

2023-06-13 01:39 UTC, luoxueyasha commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/radio_module.md
> +无线电模块在内部有一个小的队列，容纳收到的数据包的列表。这个列表的具体长度由供应商指定。如果在列表已满时收到数据包，此数据包会被忽略。此列表会以数据包被接收到的时间顺序写入到无线电模块的端口。先发出的数据包会被先接收到，但是同时发出的数据包可能会以未知顺序到达。
```suggestion
无线电模块具有一个小型队列，用于保存最近接收到的数据包的值的列表。队列的长度由供应方指定。每当模块接收到一个数据包时，如果队列已满，则会忽略该数据包。数据包的值将按照接收的顺序依次写入无线电模块的端口。先发送的数据包会被优先接收，但同时发送的数据包可能以不定的顺序到达模块。
```

2023-06-13 01:39 UTC, luoxueyasha commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/radio_module.md
> +上述列表中的一个值永远只能被发送到一个端口，也就是说值永远不能被重复读取；就算一个控制器周期内发生了多次读取，也只有一个会成功。
```suggestion
队列中的一个值只会被发送到一个端口，即值不会被复制；即使一个控制器周期内发生多次读取操作，最终也只会有一次操作成功。
```

2023-06-13 01:39 UTC, luoxueyasha commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/radio_module.md
> +另外，无线电模块在其正面的右上角有两个指示灯来帮助调试。当模块的内部缓存中有数据包需要读取，左侧的绿色指示灯会变为红色。当数据包被发送时，右侧的指示灯会以蓝色闪动一小段时间。
```suggestion
此外，无线电模块在其正面的右上角有两个用于辅助调试的指示灯。当模块的内部缓存中存在需要被读取的数据包时，左侧的绿色指示灯会变为红色。当有数据包被发送时，右侧的蓝色指示灯会短时间闪烁。
```

2023-06-13 02:10 UTC, HfSrJun commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/radio_module.md
> +无线电模块相较于红外模块能够以更远的距离和不受直线限制传输数值。无线电传输的数值会被发送到*所有*距离在256m以内的活动的无线电模块。
语境上data泛指数据，value更多指单个数据吧。就主体模组的手册来讲，用value更多。
这里的”long range“指的就是空间上的距离不是数据的值域（大小）。因为这个模组的单个数据都是16位二进制数（RAM和ROM模块除外）
范围我没有亲自测试过，原文为”within 256 meters“，在256m之内。我的理解是距离小于等于256m，即半径为256的圆。不过”距离在x以内相当于范围是半径x的圆“应该不用注释一遍吧。

2023-06-14 01:52 UTC, luoxueyasha requested changes

2023-06-14 01:52 UTC, luoxueyasha commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/tisadvanced.md
> +- [七段显示门](modules/seven_segment_display.md)
```suggestion
- [七段数码管](modules/seven_segment_display.md)
```

2023-06-14 02:16 UTC, HfSrJun commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/tisadvanced.md
> +- [七段显示门](modules/seven_segment_display.md)
我的锅，复制了我本地的文件，漏了这个改动

2023-06-16 03:31 UTC, luoxueyasha requested changes
原先的渲染空格帮你删掉了，你自己处理一下

2023-06-16 03:31 UTC, luoxueyasha commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/tisadvanced.md
> +作用与它们的整数版本一样。但是它们对`ACC`寄存器进行操作时，会认为里面的值是一个IEEE-754标准的半精 度浮点数。
```suggestion
作用与它们分别对应的整数版本相同。但是它们对`ACC`寄存器进行操作时，会认为里面的值是一个IEEE-754标准的半精度浮点数。
```

2023-06-16 03:31 UTC, luoxueyasha commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/tisadvanced.md
> +要注意，在`ACC`寄存器中存储一个整数然后对它进行浮点运算是可行的，反之亦然。但这有可能会得到错误的数值。用户应当确保操作进行于正确的数据类型。
```suggestion
需要注意的是，在`ACC`寄存器中存储一个整数再对它进行浮点运算是可行的，反之亦然。但这种操作有可能会产生错误的值。用户应当确保操作只对正确的数据类型执行操作。
```

2023-06-16 03:31 UTC, luoxueyasha commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/tisadvanced.md
> +另外，当存储在`ACC`寄存器中的值是一个IEEE-754半精 度浮点数标准中的`NaN`（非数字）值，`JIN`指令才会 跳转到给定的标签。`JNN`指令的作用相反，在`ACC`不是`NaN`值时跳转到给定的标签。
```suggestion
此外，如果存储于`ACC`寄存器中的值是IEEE-754半精度浮点数标准中的`NaN`（非数字）值，则`JIN`指令将会跳转到给定的标签。`JNN`指令的作用与`JIN`相反，在`ACC`不是`NaN`值时才会跳转到给定的标签。
```
上下文里没有提到`JIN`、`JNN`两个指令，上面两处将指令单独提到一行是不是有点问题

2023-06-16 03:31 UTC, luoxueyasha commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/tisadvanced.md
> +`FLT`会把`ACC`寄存器中存储的整数转换为用IEEE-754半 精度浮点数表示。`INT`会把存储在`ACC`寄存器中的浮点数转换为标准TIS-3D算术运算操作使用的16位有符号补码 整数来表示。转化为整数表示时会把浮点数近似取整为最接近的整数，并且是向上取整。
```suggestion
`FLT`指令可将`ACC`寄存器中存储的整数值转换为用IEEE-754半精度浮点数表示。`INT`指令可将存储于`ACC`寄存器中的浮点数转换为标准TIS-3D算术运算操作使用的16位有符号补码整数表示。转化为整数表示时会把浮点数向上取整到最接近的整数。
```

2023-06-16 03:31 UTC, luoxueyasha commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/tisadvanced.md
> +`MOV`指令的功能被扩展为能够支持处理浮点数。例如，`MOV 0.25 ACC`这条指令不再会导致编译错误了，现在它可以如期把浮点数`0.25`装载到`ACC`寄存器当中。
```suggestion
`MOV`指令已被扩展，以支持处理浮点直接值。例如，`MOV 0.25 ACC`这条指令不再被认为是编译错误了，现在它可以如期把浮点数`0.25`装载到`ACC`寄存器当中。
```

2023-06-16 03:33 UTC, luoxueyasha commented
术语与措辞检查完毕，可能会有不通顺的地方，还需要再抓个审核看一眼
#3347 #3348 #3349 具有和本PR一样的术语错译、前后文不统一、机翻和措辞不够学术腔的问题，建议要不然close要不然转draft

2023-06-16 03:41 UTC, HfSrJun commented on projects/1.18/assets/tis-advanced/tisadvanced/doc/zh_cn/modules/tape_storage.md
> +磁带存储模块提供了一个用于存储数据的8KB（8K字节）磁带。磁带为可读写，而且数据和磁头位置在计算机重启后会保存。它也可以被移除然后安装到另一台计算机上，其状态也会被保存。
重启显然是指TIS-3D模组的计算机，这本手册本来也是讨论的这种计算机。
模块和磁带并不能分开，或者说根本就没有磁带，这只不过是个模拟磁带机原理的存储模块。It指的就是整个模块

2023-06-27 00:16 UTC, luoxueyasha approved these changes
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/63901edd-82f5-4785-b2a3-3ae6ce3e11be)
大体上可了

2023-07-01 09:36 UTC, ChuijkYahus approved these changes

2023-07-07 04:35 UTC, merged