Clear F3 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3361
Opened 2023-06-07 23:47 UTC by A-Black-Fish

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-06-07 23:53 UTC, A-Black-Fish commented on projects/1.18-fabric/assets/0-modrinth-mod/clean-debug/lang/zh_cn.json
> +  "clean-debug.midnightconfig.hideActiveRenderer": "隐藏活动渲染器",
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/101028476/eb66a23a-202c-4cba-95cd-fd9328a39d05)

2023-06-08 17:49 UTC, mamaruo reviewed
把您统一成你，或尽量不适用第二人称代词

2023-06-09 06:11 UTC, A-Black-Fish commented
> 把`您`统一成`你`，或尽量不适用第二人称代词

机翻时忘了改了（）

2023-06-11 10:53 UTC, MikhailTapio requested changes

2023-06-11 10:53 UTC, MikhailTapio commented on projects/1.18-fabric/assets/0-modrinth-mod/clean-debug/lang/zh_cn.json
> +  "clean-debug.midnightconfig.hardwareMode.tooltip": "全部显示有关你的电脑的所有信息，减少只显示内存使用情况并没有隐藏一切。",
```suggestion
  "clean-debug.midnightconfig.hardwareMode.tooltip": "“全部”模式显示所有硬件信息，“部分”模式仅显示内存使用情况，“禁用”模式不显示任何硬件信息",
```

2023-06-11 10:53 UTC, MikhailTapio commented on projects/1.18-fabric/assets/0-modrinth-mod/clean-debug/lang/zh_cn.json
> +  "clean-debug.midnightconfig.enum.HardwareMode.ALL": "全部",
```suggestion
  "clean-debug.midnightconfig.enum.HardwareMode.ALL": "“全部”模式",
```

2023-06-11 10:53 UTC, MikhailTapio commented on projects/1.18-fabric/assets/0-modrinth-mod/clean-debug/lang/zh_cn.json
> +  "clean-debug.midnightconfig.enum.HardwareMode.REDUCED": "部分",
```suggestion
  "clean-debug.midnightconfig.enum.HardwareMode.REDUCED": "“部分”模式",
```

2023-06-11 10:53 UTC, MikhailTapio commented on projects/1.18-fabric/assets/0-modrinth-mod/clean-debug/lang/zh_cn.json
> +  "clean-debug.midnightconfig.enum.HardwareMode.NONE": "禁用",
```suggestion
  "clean-debug.midnightconfig.enum.HardwareMode.NONE": "“禁用”模式",
```

2023-06-11 10:53 UTC, MikhailTapio commented on projects/1.19/assets/0-modrinth-mod/clean-debug/lang/zh_cn.json
> +  "clean-debug.midnightconfig.hardwareMode.tooltip": "全部显示有关你的电脑的所有信息，减少只显示内存使用情况并没有隐藏一切。",
请见 1.18-fabric 同位置评论（

2023-06-11 11:00 UTC, MikhailTapio requested changes

2023-06-12 03:23 UTC, MikhailTapio commented on projects/1.18-fabric/assets/0-modrinth-mod/clean-debug/lang/zh_cn.json
> +  "clean-debug.midnightconfig.hardwareMode": "显示硬件模式",
根据原文这样翻好像是没问题的，不过翻成“硬件信息显示模式”会不会更好？

2023-06-12 04:10 UTC, MikhailTapio approved these changes
好耶

2023-06-15 17:03 UTC, mamaruo commented on projects/1.19/assets/0-modrinth-mod/clean-debug/lang/zh_cn.json
> +  "clean-debug.midnightconfig.enum.HardwareMode.NONE": "“禁用”",
| **审查级别**    |
|--------------|
| ❓疑问 / 需要作者确认 |

原文：**All┃Reduced┃None**

为什么加引号？

2023-06-15 18:07 UTC, mamaruo commented on projects/1.19/assets/0-modrinth-mod/clean-debug/lang/zh_cn.json
> +  "clean-debug.midnightconfig.enum.HardwareMode.NONE": "“禁用”",
```suggestion
  "clean-debug.midnightconfig.enum.HardwareMode.ALL": "全部",
  "clean-debug.midnightconfig.enum.HardwareMode.REDUCED": "部分",
  "clean-debug.midnightconfig.enum.HardwareMode.NONE": "禁用",

```

2023-06-16 02:57 UTC, mamaruo submitted a review, later dismissed

2023-06-21 19:00 UTC, Slow-Witted-Fish commented on projects/1.19/assets/0-modrinth-mod/clean-debug/lang/zh_cn.json
> +  "clean-debug.midnightconfig.hideSodium": "隐藏钠的调试信息",
emm没检查所以就漏了这一地方

2023-06-22 04:24 UTC, dovisutu approved these changes

2023-06-24 12:05 UTC, ChuijkYahus approved these changes

2023-06-24 12:06 UTC, merged