Dungeons Enhanced翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3372
Opened 2023-06-11 02:46 UTC by kuguaboss

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-06-11 11:51 UTC, luoxueyasha requested changes

2023-06-11 11:51 UTC, luoxueyasha commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.thats_a_dungeon": "这是个地牢!",
```suggestion
    "advancements.dungeons_enhanced.thats_a_dungeon": "这是个地牢！",
```

2023-06-11 11:51 UTC, luoxueyasha commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.hidden_under_the_roots.desc": "寻找怪物迷宫",
实际游戏内触发方法是？

2023-06-11 11:51 UTC, luoxueyasha commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.wars_and_kingdoms": "被遗忘的国家",
原文为`Forgotten Wars and Kingdoms`，请解释一下不译出`war`的理由

2023-06-11 11:51 UTC, luoxueyasha commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.rarest_structure": "游戏中最稀有的结构?",
```suggestion
    "advancements.dungeons_enhanced.rarest_structure": "游戏中最稀有的结构？",
```

2023-06-11 11:51 UTC, luoxueyasha commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.chilled_halls.desc": "寻找冰川天坑",
可以提供这里的`Ice Pit`的外观、结构描述或截图吗

2023-06-11 11:51 UTC, luoxueyasha commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.in_the_air.desc": "寻找一个空中的海盗船",
```suggestion
    "advancements.dungeons_enhanced.in_the_air.desc": "找到飞翔的荷兰人号",
```

2023-06-11 11:51 UTC, luoxueyasha commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.sunken_deeps.desc": "寻找海底神殿",
解释一下为何将`Elder's Temple`这么翻译

2023-06-11 11:51 UTC, luoxueyasha commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.root": "地下城增强",
这个模组添加的是`地下城`还是`地牢`？

2023-06-11 11:51 UTC, luoxueyasha commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.ahoy": "海盗船长",
```suggestion
    "advancements.dungeons_enhanced.ahoy": "嘿！船长！",
```
```suggestion
    "advancements.dungeons_enhanced.ahoy": "嗨！船长！",
```
```suggestion
    "advancements.dungeons_enhanced.ahoy": "船长好！",
```

2023-06-11 11:51 UTC, luoxueyasha commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.in_the_air": "在空中飞行",
```suggestion
    "advancements.dungeons_enhanced.in_the_air": "在空中翱翔",
```
仅建议，可不修改

2023-06-11 13:59 UTC, kuguaboss commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.hidden_under_the_roots.desc": "寻找怪物迷宫",
这算进度，你到达结构所在区域就触发了

2023-06-11 14:02 UTC, kuguaboss commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.wars_and_kingdoms": "被遗忘的国家",
机翻的意思应该是被遗忘的战争和王国，我理解为被战争摧毁的王国，实际这个结构是在地下，我觉得称为被遗忘（埋藏）的国家可行，这大概有点像楼兰古国

2023-06-11 14:39 UTC, kuguaboss commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.root": "地下城增强",
有地牢和部分原版建筑的修改，还有部分是随机分布在地面上，我原本想翻译成地牢，但考虑到游戏内添加的不只是地牢，我就按照原文翻译成地下城

2023-06-11 14:42 UTC, kuguaboss commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.wars_and_kingdoms": "被遗忘的国家",
因为从游戏实际来看，你并不能看war的痕迹，可能作者的想法是“被战争摧毁的国家”，这个结构在游戏内的表现是一个破旧的城堡，大概是像玛雅文明一样，所以我就不把war翻译出来了

2023-06-11 14:51 UTC, kuguaboss commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.sunken_deeps.desc": "寻找海底神殿",
因为作者只是单纯的修改了部分海底神殿的结构，结构大部分和原版一样

2023-06-11 23:32 UTC, luoxueyasha commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.hidden_under_the_roots.desc": "寻找怪物迷宫",
那就将译文里所有的这样的`Find`改为`找到`

2023-06-12 02:33 UTC, kuguaboss commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.chilled_halls.desc": "寻找冰川天坑",
![2023-06-11_22 12 00](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/136167084/c4c7a9d2-fe4d-4b9b-b84f-aae8bc0e128b)

2023-06-12 14:21 UTC, luoxueyasha approved these changes
大体上可以了，别的审核看一眼细节吧

2023-06-15 17:27 UTC, mamaruo commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.sunken_deeps.desc": "探访海底神殿",
原文Find an Elder's Temple
这玩意跟原版的海底神殿（Ocean Monument）有关系吗。

2023-06-16 02:50 UTC, kuguaboss commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.sunken_deeps.desc": "探访海底神殿",
![2023-06-11_22 10 51](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/136167084/17d89076-14c3-4042-ae2b-95173c3ccda0)

2023-06-16 02:51 UTC, kuguaboss commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.sunken_deeps.desc": "探访海底神殿",
在游戏里面他和海底神殿长相类似

2023-06-16 03:02 UTC, mamaruo commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.sunken_deeps.desc": "探访海底神殿",
那就是说它们不是同一个[结构](https://minecraft.fandom.com/zh/wiki/%E7%94%9F%E6%88%90%E7%BB%93%E6%9E%84)咯？

不是同一对象不能翻译为同一译名，何况原文差异那么大。

2023-06-16 03:43 UTC, kuguaboss commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.ancient_civilizations.desc": "探访丛林纪念碑",
![Uploading 2023-06-16_11.01.09.png…]()

2023-06-16 03:44 UTC, kuguaboss commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.ancient_civilizations.desc": "探访丛林纪念碑",
![2023-06-16_11 01 09](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/136167084/abb3dddb-c581-4b21-97b1-dbfe7f928f47)

2023-06-16 03:45 UTC, kuguaboss commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.ancient_civilizations.desc": "探访丛林纪念碑",
我感觉这个和那个Elder's Temple类似，也是原版的修改，感觉可以改成丛林神庙

2023-06-16 04:11 UTC, kuguaboss commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.sunken_deeps.desc": "探访海底神殿",
翻译成“更古老的海底神殿”怎么样

2023-06-16 04:14 UTC, kuguaboss commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.ancient_civilizations.desc": "探访丛林纪念碑",
这个是丛林神庙的变种

2023-06-16 04:39 UTC, Lulilaya commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.sunken_deeps.desc": "探访海底神殿",
远古（上古、古老、老式）海底神殿？仅供参考

2023-06-19 11:10 UTC, mamaruo commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.sunken_deeps.desc": "探访海底神殿",
我认为 Elder 实指 Elder Guardian。不过还需参考游戏内表现。
```suggestion
    "advancements.dungeons_enhanced.sunken_deeps.desc": "探访远古守卫者的神庙",
```

2023-06-27 00:09 UTC, luoxueyasha requested changes

2023-06-27 00:09 UTC, luoxueyasha commented on projects/1.16/assets/dungeonsenhanced/dungeons_enhanced/lang/zh_cn.json
> +    "advancements.dungeons_enhanced.thats_a_dungeon": "好大一个地牢!",
```suggestion
    "advancements.dungeons_enhanced.thats_a_dungeon": "好大一个地牢！",
```
全角符号

2023-06-28 02:57 UTC, mamaruo commented
基本上没什么问题了，可以考虑给1.18、1.19复制一份，然后我给approval

2023-07-03 09:52 UTC, mamaruo approved these changes

2023-07-07 04:36 UTC, merged