trash-cans 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #3374
Opened 2023-06-12 15:19 UTC by jiusun

- [ x ] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ x ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ x ] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ x ] 刷新 PR 的标签/状态，有需要再点击；

2023-06-13 14:56 UTC, dovisutu submitted a review, later dismissed
看起来没有什么问题...？

2023-06-14 04:50 UTC, mamaruo commented
检查单勾选有问题，应写作 `- [x]`

2023-06-14 04:55 UTC, mamaruo requested changes

2023-06-14 04:55 UTC, mamaruo commented on projects/1.16/assets/trash-cans/trashcans/lang/zh_cn.json
[数字汉字间不留空格](https://cfpa.site/TransRules/#:~:text=%E8%8B%B1%E6%96%87%E5%AD%97%E6%AF%8D%E3%80%81%E9%98%BF%E6%8B%89%E4%BC%AF%E6%95%B0%E5%AD%97%E7%AD%89%E9%9D%9E%E4%B8%AD%E6%96%87%E5%AD%97%E7%AC%A6%EF%BC%8C%E4%B8%8D%E5%BA%94%E5%8A%A0%E7%A9%BA%E6%A0%BC%E4%B8%8E%E4%B8%AD%E6%96%87%E6%96%87%E6%9C%AC%E5%88%86%E5%BC%80)

2023-06-14 04:55 UTC, mamaruo commented on projects/1.16/assets/trash-cans/trashcans/lang/zh_cn.json
> +  "trashcans.ultimate_trash_can.info": "用于销毁物品、流体、气体和能源",
多了个气体

2023-06-14 06:02 UTC, jiusun commented on projects/1.16/assets/trash-cans/trashcans/lang/zh_cn.json
> +  "trashcans.ultimate_trash_can.info": "用于销毁物品、流体、气体和能源",
终极垃圾桶包含其他三种垃圾桶的所有功能。原文中没有写气体，但实际使用确实是可以销毁气体的。

2023-06-14 06:06 UTC, mamaruo commented on projects/1.16/assets/trash-cans/trashcans/lang/zh_cn.json
> +  "trashcans.ultimate_trash_can.info": "用于销毁物品、流体、气体和能源",
不管，原文写什么译什么

2023-06-14 06:11 UTC, jiusun commented on projects/1.16/assets/trash-cans/trashcans/lang/zh_cn.json
> +  "trashcans.ultimate_trash_can.info": "用于销毁物品、流体、气体和能源",
已提交修改

2023-06-14 06:33 UTC, mamaruo approved these changes

2023-06-15 12:49 UTC, merged