提交 Upgraded Netherite 模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #3377
Opened 2023-06-14 02:53 UTC by miehhhhh

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-06-15 17:39 UTC, mamaruo reviewed
请将中文文本中的所有半角符号改为全角

2023-06-15 17:39 UTC, mamaruo commented on projects/1.19/assets/upgraded-netherite/upgradednetherite/lang/zh_cn.json
> +  "upgradednetherite.Echo_Shield.TT": "§7• 将主手装备的§b回响§7系近战武器下一次对§6监守者§7造成的§6伤害§a增加§7%1$s§7 (up to %2$s§7).",
未译完整

2023-06-20 08:04 UTC, mamaruo commented
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/3377/commits/e2c0df73262f1db9526f8be6e642b27dd663b8b6 这个 commit 又把符号问题倒回去了

2023-06-20 13:04 UTC, mamaruo commented
我对比了“库内1.18”和“本PR”的翻译，结果如下：

<details><summary>点我展开</summary>
<p>


### 两者皆有

| **键** | **英文** | **库内1.18** | **本PR** |
|---|---|---|---|
| upgradednetherite.Gold_Horse_Bonus.TT | §7• Increase the §6Looting Level§7 of the rider by §61§7. | §7• 提升§61§7点骑乘者的§6抢夺等级§7。 | §7• 提升§61§7§6抢夺等级§7． |
| upgradednetherite.Fire_Bonus.TT | §7• §6Fire§7 damage §6Immune§7. | §7• 对§6火焰§7伤害§6免疫§7。 | §7• §6免疫§7§6火焰及岩浆§7伤害． |
| upgradednetherite.Fire_Bonus2.TT | §7• Increased §6Movement Speed§7 in lava. | §7• 提升在熔岩中的§6移动速度§7。 | §7• 提升在岩浆中的§6移动速度§7． |
| upgradednetherite.Ender_Bonus.TT | §7• §6Saves§7 from the §6Void§7. | §7• §6避免§7落入§6虚空§7。 | §7• 掉落§6虚空§7时会§6传送§7到最近的方块上． |
| upgradednetherite.Ender_Bonus2.TT | §7• Prevent §6Enderman Anger§7. | §7• 避免§6激怒末影人§7。 | §7• 对视不会激怒§6末影人§7． |
| upgradednetherite.Water_Bonus.TT | §7• §6Water Breathing§7. | §7• §6水下呼吸§7。 | §7• 提供§6水下呼吸§7效果． |
| upgradednetherite.Water_Bonus2.TT | §7• Increased §6Movement Speed§7 in water. | §7• 提升在水下的§6移动速度§7。 | §7• 提升水下§6移动速度§7． |
| upgradednetherite.Wither_Bonus.TT | §7• §6Wither§7 effect §6Immune§7. | §7• 对§6凋零§7效果§6免疫§7。 | §7• §6凋零§7效果§6免疫§7． |
| upgradednetherite.Poison_Bonus.TT | §7• §6Poison§7 effect §6Immune§7. | §7• 对§6中毒§7效果§6免疫§7。 | §7• §6免疫中毒§7效果． |
| upgradednetherite.Poison_Bonus2.TT | §7• §6Climbs Walls§7. | §7• 获得§6爬墙§7能力。 | §7• 获得§6攀岩§7能力． |
| upgradednetherite.Phantom_Bonus.TT | §7• §6Fall§7 damage §6Immune§7. | §7• 对§6摔落§7伤害§6免疫§7。 | §7• §6免疫摔落§7伤害． |
| upgradednetherite.Phantom_Bonus2.TT | §7• Increased §6Step Height§7. | §7• 提升§6步伐高度§7。 | §7• 玩家可直接走上一格高的§6方块§7． |
| upgradednetherite.Feather_Bonus.TT | §7• §6Water§7 & §6Lava Walking§7. | §7• 获得§6缓降§7效果。 | §7• 可以在§6水§7和§6岩浆§7上行走． |
| upgradednetherite.Feather_Bonus3.TT | §7• §6Fall§7 damage §6Reduction§7. | §7• §7减少§6摔落§7伤害。 | §7• §6减少§7§6摔落§7伤害． |
| upgradednetherite.Corrupt_Bonus2.TT | §7• §6Absorbs host energy§7. | §7• §6吸收穿戴者的能量§7。 | §7• §6吸取玩家经验§7． |
| upgradednetherite.Gold_Bow.TT | §5Can be enchanted with §3Looting§5. | §5能够附上§3抢夺§5. | §5允许附魔§3抢夺§5魔咒． |
| upgradednetherite.Ender_Weapon.TT | §7• §6Prevent Teleporting§7 for §610s§7. | §7• 在§610秒§7内§6阻止传送§7。 | §7• 在§610秒§7内§6阻止传送§7． |
| upgradednetherite.Ender_ToolTar.TT | Hold §b§nShift§r§f for target infos. | 按住 §b§nShift§r§f 键查看目标详情。 | 按住§b§nShift§r§f键获取目标信息． |
| upgradednetherite.Ender_Dim.TT | §7• §cTarget chest is in another dimension. | §7• §c目标容器位于另一维度。 | §7• §c绑定容器不在本维度． |
| upgradednetherite.Water_Tool.TT | §7• Increased §6Mining Speed§7 underwater. | §7• 提升在水下的§6采掘速度§7。 | §7• 提升§6水下采矿§7速度． |
| upgradednetherite.Phantom_Tool2.TT | §7• Increased §6Reach§7 by §62§7. | §7• 提升§62§7格§6触及范围。 | §7• 提升§6触碰范围§7§62§7格． |
| upgradednetherite.Feather_Shield.TT | §7• Chance to §6Push§7 all nearby enemies. | §7• 有几率§6排斥§7周围所有的敌对目标。 | §7• 有几率§6推开§7附近的所有敌人． |
| upgradednetherite.Feather_Bow.TT | §7• Apply §6Attraction§7 effect. | §7• 施加§6诱惑§7效果。 | §7• 命中目标获得§6吸引§7效果． |
| upgradednetherite.Corrupt_Enchant.TT | §5Can't be enchanted with §3Mending§5. | §5无法附上§3经验修补§5。 | §5无法附上§3经验修补§5． |
| upgradednetherite.HoldShift.TT | Hold §b§nShift§r§f for infos. | 按住§b§nShift§r§f键查看详情。 | 按住§b§nShift§r§f键查看详情． |
| upgradednetherite.Malus.TT | §c§lMalus | §c§l苹果 | §c§l减益 |

### 只在 库内1.18 中有

🚫未找到

### 只在 本PR 中有

| **键** | **英文** | **库内1.18** | **本PR** |
|---|---|---|---|
| item.upgradednetherite.echo_upgraded_netherite_ingot | Echorite Ingot | 🚫 | 回响下界合金锭 |
| item.upgradednetherite.gold_essence | Golderite Essence | 🚫 | 嵌金精华 |
| item.upgradednetherite.fire_essence | Blazerite Essence | 🚫 | 烈焰精华 |
| item.upgradednetherite.ender_essence | Enderite Essence | 🚫 | 末影精华 |
| item.upgradednetherite.water_essence | Prismarite Essence | 🚫 | 海晶精华 |
| item.upgradednetherite.wither_essence | Witherite Essence | 🚫 | 凋灵精华 |
| item.upgradednetherite.poison_essence | Spiderite Essence | 🚫 | 蛛毒精华 |
| item.upgradednetherite.phantom_essence | Phanterite Essence | 🚫 | 幻翼精华 |
| item.upgradednetherite.feather_essence | Featherite Essence | 🚫 | 飘羽精华 |
| item.upgradednetherite.corrupt_essence | Corrupterite Essence | 🚫 | 腐化精华 |
| item.upgradednetherite.echo_essence | Echorite Essence | 🚫 | 回响精华 |
| item.upgradednetherite.echo_upgraded_netherite_helmet | Echorite Helmet | 🚫 | 回响下界合金头盔 |
| item.upgradednetherite.echo_upgraded_netherite_chestplate | Echorite Chestplate | 🚫 | 回响下界合金胸甲 |
| item.upgradednetherite.echo_upgraded_netherite_leggings | Echorite Leggings | 🚫 | 回响下界合金护腿 |
| item.upgradednetherite.echo_upgraded_netherite_boots | Echorite Boots | 🚫 | 回响下界合金靴子 |
| item.upgradednetherite.echo_upgraded_netherite_horse_armor | Echorite Horse Armor | 🚫 | 回响下界合金马凯 |
| item.upgradednetherite.echo_upgraded_netherite_sword | Echorite Sword | 🚫 | 回响下界合金剑 |
| item.upgradednetherite.echo_upgraded_netherite_pickaxe | Echorite Pickaxe | 🚫 | 回响下界合金镐 |
| item.upgradednetherite.echo_upgraded_netherite_shovel | Echorite Shovel | 🚫 | 回响下界合金锹 |
| item.upgradednetherite.echo_upgraded_netherite_axe | Echorite Axe | 🚫 | 回响下界合金 斧 |
| item.upgradednetherite.echo_upgraded_netherite_bow | Echorite Bow | 🚫 | 回响下界合金弓 |
| item.upgradednetherite.echo_upgraded_netherite_crossbow | Echorite Crossbow | 🚫 | 回响下界合金弩 |
| item.upgradednetherite.echo_upgraded_netherite_shield | Echorite Shield | 🚫 | 回响下界合金盾牌 |
| item.upgradednetherite.echo_upgraded_netherite_shield.black | Black Echorite Shield | 🚫 | 黑色回响下界合金盾牌 |
| item.upgradednetherite.echo_upgraded_netherite_shield.red | Red Echorite Shield | 🚫 | 红色回响下界合金盾牌 |
| item.upgradednetherite.echo_upgraded_netherite_shield.green | Green Echorite Shield | 🚫 | 绿色回响下界合金盾牌 |
| item.upgradednetherite.echo_upgraded_netherite_shield.brown | Brown Echorite Shield | 🚫 | 棕色回响下界合金盾牌 |
| item.upgradednetherite.echo_upgraded_netherite_shield.blue | Blue Echorite Shield | 🚫 | 蓝色回响下界合金盾牌 |
| item.upgradednetherite.echo_upgraded_netherite_shield.purple | Purple Echorite Shield | 🚫 | 紫色回响下界合金盾牌 |
| item.upgradednetherite.echo_upgraded_netherite_shield.cyan | Cyan Echorite Shield | 🚫 | 青色回响下界合金盾牌 |
| item.upgradednetherite.echo_upgraded_netherite_shield.light_gray | Light Gray Echorite Shield | 🚫 | 淡灰色回响下界合金盾牌 |
| item.upgradednetherite.echo_upgraded_netherite_shield.gray | Gray Echorite Shield | 🚫 | 灰色回响下界合金盾牌 |
| item.upgradednetherite.echo_upgraded_netherite_shield.pink | Pink Echorite Shield | 🚫 | 粉红色回响下界合金盾牌 |
| item.upgradednetherite.echo_upgraded_netherite_shield.lime | Lime Echorite Shield | 🚫 | 黄绿色回响下界合金盾牌 |
| item.upgradednetherite.echo_upgraded_netherite_shield.yellow | Yellow Echorite Shield | 🚫 | 黄色回响下界合金盾牌 |
| item.upgradednetherite.echo_upgraded_netherite_shield.light_blue | Light Blue Echorite Shield | 🚫 | 淡蓝色回响下界合金盾牌 |
| item.upgradednetherite.echo_upgraded_netherite_shield.magenta | Magenta Echorite Shield | 🚫 | 品红色回响下界合金盾牌 |
| item.upgradednetherite.echo_upgraded_netherite_shield.orange | Orange Echorite Shield | 🚫 | 橙色回响下界合金盾牌 |
| item.upgradednetherite.echo_upgraded_netherite_shield.white | White Echorite Shield | 🚫 | 白色回响下界合金盾牌 |
| upgradednetherite.Gold_Bonus2.TT | §7• Increased §9Luck§7 by %1$s§7. | 🚫 | §7• 使§6时运§7附魔等级+%1$s§7． |
| upgradednetherite.Water_Bonus3.TT | §7• Prevents §6Elder Guardian§7 from inflicting the §6Mining Fatigue§7 effect. | 🚫 | §7• 免疫来自§6远古守护者§7的§6挖掘疲劳§7效果． |
| upgradednetherite.Feather_Bonus2.TT | §7• §6Multi Jump§7. | 🚫 | §7• §6三段跳§7． |
| upgradednetherite.Feather_Bonus4.TT | §7• §6Levitation§7 effect §6Immune§7. | 🚫 | §7• §6免疫漂浮§7效果． |
| upgradednetherite.Corrupt_Bonus.TT | §7• Reduce §9Max Health§7 by %1$s§7. | 🚫 | §7• 减少%1$s§7§9最大生命值§7． |
| upgradednetherite.Corrupt_Horse_Bonus.TT | §7• Reduce rider §9Max Health§7 by %1$s§7. | 🚫 | §7• 减少骑乘玩家%1$s§7§9最大生命值§7． |
| upgradednetherite.Corrupt_Horse_Bonus2.TT | §7• Counts as a §dCorrupterite Armor§7 bonus for the rider. | 🚫 | §7• 算作骑乘玩家的§d腐化盔甲§7效果叠加． |
| upgradednetherite.Echo_Bonus.TT | §7• Your items have a %1$s§7 chance of remaining in your inventory when you die. | 🚫 | §7• 死亡时你的物品有%1$s§7的几率保留下来． |
| upgradednetherite.Echo_Bonus2.TT | §7• Reduces §6Damage§7 of §6Warden§7's §6Sonic Boom§7 by %1$s§7. | 🚫 | §7• 降低§6监守者§7%1$s§7§6音波§7§6伤害§ [...]

2023-06-21 06:13 UTC, miehhhhh commented
为什么报目录不存在，还有1.18的本身翻译就有点不太准确，1.19后mod功能更新与之前的差异较大目前翻译都是根据英文源文件结合游戏实际效果翻译的

2023-06-21 16:33 UTC, mamaruo requested changes
纰漏很多……但毕竟你是第一次提交，慢慢来……

### 审阅意见

**注**：仅审阅了与库内1.18相比新增的键

| **键** | **英文** | **中文** | 审阅意见 |
|---|---|---|---|
| item.upgradednetherite.echo_upgraded_netherite_horse_armor | Echorite Horse Armor | 回响下界合金马凯 | 是马铠 |
| item.upgradednetherite.echo_upgraded_netherite_axe | Echorite Axe | 回响下界合金 斧 | 多了空格 |
| upgradednetherite.Water_Bonus3.TT | §7• Prevents §6Elder Guardian§7 from inflicting the §6Mining Fatigue§7 effect. | §7• 免疫来自§6远古守护者§7的§6挖掘疲劳§7效果． | 远古守卫者 |
| upgradednetherite.Feather_Bonus4.TT | §7• §6Levitation§7 effect §6Immune§7. | §7• §6免疫漂浮§7效果． | 原版译名，飘浮 |
| upgradednetherite.Corrupt_Bonus.TT | §7• Reduce §9Max Health§7 by %1$s§7. | §7• 减少%1$s§7§9最大生命值§7． | 猜测占位符是数字，最好带上单位“点”，下同 |
| upgradednetherite.Corrupt_Horse_Bonus.TT | §7• Reduce rider §9Max Health§7 by %1$s§7. | §7• 减少骑乘玩家%1$s§7§9最大生命值§7． | 点 |
| upgradednetherite.Corrupt_Horse_Bonus2.TT | §7• Counts as a §dCorrupterite Armor§7 bonus for the rider. | §7• 算作骑乘玩家的§d腐化盔甲§7效果叠加． | 存疑 |
| upgradednetherite.Echo_Bonus.TT | §7• Your items have a %1$s§7 chance of remaining in your inventory when you die. | §7• 死亡时你的物品有%1$s§7的几率保留下来． | 仅建议：§7• 死亡时你的物品有%1$s§7的几率不掉落 |
| upgradednetherite.Echo_Bonus3.TT | §7• Heals when in §6Deep Dark§7. | §7• 再§6黑暗环境§7中缓慢回复耐久． | Deep Dark 深暗之域 |
| upgradednetherite.Gold_Weapon.TT | §7• Increased §6Damage§7 dealt to §6Piglin Brute§7 by %1$s§7. | §7• 对§6猪灵§7造成§6伤害§a提升§7%1$s§7． | Piglin Brute 猪灵蛮兵 |
| upgradednetherite.Gold_Weapon3.TT | §3Looting III§5(or more) increase §dLooting Level §abonus§5 by %1$s§5. | §3抢夺III§5（或更多）将额外再§a提升§5%1$s§5级§d抢夺． | 或更高，看看这句游戏内的效果？ |
| upgradednetherite.Gold_Tool2.TT | §3Fortune III§5(or more) increase §dFortune Level §abonus§5 by %1$s§5. | §3时运III§5（或更多）将额外再§a提升§5%1$s§5级§d时运． | 或更高 |
| upgradednetherite.Gold_Shield.TT | §7• §6Piglin Brute§7 increases the §6Damage §abonus§7 of the next attack of your §6Golderite§7 melee weapon equipped in your main hand by %1$s§7 (up to %2$s§7). | §7• 主手装备的§c镶金系§7近战武器下一次对§6猪灵§7造成§6伤害§a提升§7%1$s§7（上限%2$s§7）． | Piglin Brute 猪灵蛮兵 |
| upgradednetherite.Fire_Weapon2.TT | §3Fire Aspect II§5(or more) increase §dDamage §abonus§5 dealt by %1$s§5. | 拥有§3火焰附加II§5（或更多）将额外§a提升§5%1$s§5§d伤害． | 或更高，这一句和 upgradednetherite.Gold_Weapon3.TT 等类似句子译法不一样，请统一 |
| upgradednetherite.Fire_Weapon3.TT | §5Can be enchanted with §3Fire Aspect§5. | §5允许附魔§3火焰附加§5魔咒． | 仅建议：§5可附上§3火焰附加§5魔咒。 |
| upgradednetherite.Fire_Tool.TT | %1$s§6Auto-smelting§7. | %1$s§6自动冶炼§7． | 自动烧炼；冶炼一般专指烧炼矿石 |
| upgradednetherite.Fire_Bow.TT | §3Flame§5 increase §dDamage §abonus§5 dealt by %1$s§5. | 对§3着火目标§5造成§d伤害§a提升§5%1$s§5． | 这句跟 upgradednetherite.Fire_Weapon.TT 一样？ |
| upgradednetherite.Fire_CrossBow.TT | §5Can be enchanted with §3Flame§5. | §5允许附魔§3火夭§5魔咒． | 建议同upgradednetherite.Fire_Weapon3.TT |
| upgradednetherite.Wither_Weapon2.TT | §7• Increased §6Damage§7 dealt to §6targets affected by wither effect§7 by %1$s§7. | §7• 对带有§6受凋零效果§7影响的目标造成§6伤害§a提升§7%1$s§7． | 这样更好：§7• 对带有§6凋零效果§7的目标造成§6伤害§a提升§7%1$s§7． |
| upgradednetherite.Phantom_Tool_Detect.TT | §cYou feel %1$s§c enemy near you. | §c你感应到身边%1$s§c敌对生物． | §c你能察觉到身边的%1$s§c敌对生物。 |
| upgradednetherite.Phantom_Tool_Detect2.TT | §cYou feel %1$s§c enemies near you. | §c你感应到身边%1$s§c敌对生物.． | 这句是复数，上句是单数，游戏内表现？ |
| upgradednetherite.Phantom_Shield.TT | §7• §6Phantom§7 increases the §6Damage §abonus§7 of the next attack of your §7Phanterite§7 melee weapon equipped in your main hand by %1$s§7 (up to %2$s§7). | §7• 每装备一件§d幻翼系装备§5主手使用的§d幻翼系§7近战武器下一次§6伤害§a提升§7%1$s§7（上限%2$s§7） | 这一句和其他类似条目翻译得不一样，请统一 |
| upgradednetherite.Feather_Tool.TT | %1$s§6Attracts Items§7 near you. | %1$s§6吸引物品§7． | %1$s§6吸引附近物品§7． |
| upgradednetherite.Corrupt_Weapon.TT | §5Increased §dLooting Level §abonus§5 by %1$s§5 for every §dCorrupterite Armor§5 equipped. | 每装备一件§5腐化系装备§d抢夺等级§a提升§5%1$s§5级． | 装备 -> 盔甲，下同 |
| upgradednetherite.Corrupt_Weapon4.TT | §7• Increased §6Looting Level§7 by %1$s§7. | §7• 提升§6抢夺等级§7%1$s§7． | 这不通吧……抢夺等级提升%s |
| upgradednetherite.Corrupt_Tool2.TT | §7• Increased §6Fortune Level§7 by %1$s§7. | §7• 提升§6时运§7%1$s§7． | 同上 |
| upgradednetherite.SetBonus.TT | §a§lSet Bonus (%1$s§a§l) | §a§l套装效果（%1$s§a§l） | 套装加成 |
| upgradednetherite.Disabled.TT | §c§lDisabled | §c§l死亡时 | 这怎么翻出来的？禁用 |

2023-06-28 09:17 UTC, ChuijkYahus commented
* 7+7进入第一阶段，请注意查看各审核意见

@miehhhhh

2023-07-10 05:19 UTC, ChuijkYahus commented
* 7+7时限已到，请注意查看审核意见，如有需要可reopen

@miehhhhh

2023-07-10 05:19 UTC, closed without merging