[R] 提交beachparty模组翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #3381
Opened 2023-06-16 14:41 UTC by Takiaaa

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-06-17 00:39 UTC, luoxueyasha commented
请将PR标题修改为 
`Let's Do Beachparty 翻译更新`

2023-06-19 11:34 UTC, mamaruo commented
麻烦中英文对齐一下，不然不好审

2023-06-28 09:20 UTC, ChuijkYahus approved these changes
需要其他审核再看一眼

2023-06-28 09:57 UTC, luoxueyasha commented on .vscode/settings.json
> +{
这个文档是不是多余了……？

2023-06-28 10:01 UTC, ChuijkYahus commented on .vscode/settings.json
> +{
是的
应该又是进dev时候点了忽略已有pr

2023-06-28 10:02 UTC, ChuijkYahus requested changes

2023-06-28 10:02 UTC, ChuijkYahus commented on .vscode/settings.json
> +{
请注意删除.vscode文件夹

2023-07-01 05:23 UTC, mamaruo commented on projects/1.19/assets/beachparty/beachparty/lang/zh_cn.json
> +   "block.beachparty.palm_wall_torch": "棕榈木火炬",
游戏内表现是否和原版火把十分相似？如果是，考虑 `火把`，如果否，现有翻译可行。

2023-07-01 05:23 UTC, mamaruo commented on projects/1.19/assets/beachparty/beachparty/lang/zh_cn.json
> +   "beachparty.sound.radio_beachparty": "收音机：播放《飞越彩虹》",
歌名不译，见102行

2023-07-01 05:23 UTC, mamaruo commented on projects/1.19/assets/beachparty/beachparty/lang/zh_cn.json
> +   "tooltip.beachparty.cactusicecream": "这款仙人掌雪糕能让你尝到好运的味道，但不要太高兴——它可能会让你感到有点刺痛",
```suggestion
   "tooltip.beachparty.cactusicecream": "这款仙人掌雪糕能让你尝到好运的味道，但别太高兴——它可能有点扎人",
```
仅建议

2023-07-01 05:23 UTC, mamaruo commented on projects/1.19/assets/beachparty/beachparty/lang/zh_cn.json
> +   "tooltip.beachparty.swimwearleggings": "-[裤子]",
"tooltip.beachparty.swimwearboots": "Swimwear Boots",
 "tooltip.beachparty.swimwearbreastplate": "Swimwear Breastplate",
 "tooltip.beachparty.swimwearhelmet": "Swimwear Helmet",
 "tooltip.beachparty.swimwearleggings": "Swimwear Leggings",

原文译文格式为什么不一样

2023-07-04 02:16 UTC, Takiaaa commented on projects/1.19/assets/beachparty/beachparty/lang/zh_cn.json
> +   "block.beachparty.palm_wall_torch": "棕榈木火炬",
工作原理一致，但高火把并不好听，且不如“高火炬”更常见，形制上也更接近火炬而不是火把，所以统一为火炬。如果只有棕榈木火炬或许改成火把会好点，但还有个高火炬……这是我不得不考量进去的。

2023-07-04 02:20 UTC, Takiaaa commented on projects/1.19/assets/beachparty/beachparty/lang/zh_cn.json
> +   "tooltip.beachparty.swimwearleggings": "-[裤子]",
为了贴切该作者另一款同系列已汉化模组 “葡园酒香” 的服装格式。也是为了美观与整齐。

2023-07-04 02:26 UTC, Takiaaa commented on projects/1.19/assets/beachparty/beachparty/lang/zh_cn.json
> +   "tooltip.beachparty.cactusicecream": "这款仙人掌雪糕能让你尝到好运的味道，但不要太高兴——它可能会让你感到有点刺痛",
按照原文的直译，意思有了就好。

2023-07-22 12:07 UTC, luoxueyasha reviewed
感觉基本上差不多了

2023-07-22 12:07 UTC, luoxueyasha commented on projects/1.19/assets/beachparty/beachparty/lang/zh_cn.json
> +   "block.beachparty.notimplemented": "（这个方块有尚未完全实现的功能。请继续关注！）",
```suggestion
   "block.beachparty.notimplemented": "（这个方块有尚未完全实现的功能。敬请期待！）",
```
仅个人建议，读上去更自然点

2023-07-30 10:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3381) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3381) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3381) it.</sub>

2023-08-01 04:15 UTC, luoxueyasha commented
@Takiaaa 
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

2023-08-10 03:35 UTC, Cactusstudent commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@Takiaaa

2023-08-14 06:29 UTC, Cactusstudent submitted a review, later dismissed
应该没啥问题了？

2023-08-14 06:37 UTC, ChuijkYahus submitted a review, later dismissed
应该没问题了

2023-08-17 12:25 UTC, ChuijkYahus commented
嘶这模组更新键名了貌似

2023-08-19 17:05 UTC, ChuijkYahus commented
话说键名需要更新吗
如果不想更新就合并了

2023-08-20 17:54 UTC, Takiaaa commented
> 话说键名需要更新吗 如果不想更新就合并了

暂时先这样合并吧，等攒一波再更新。

2023-08-20 22:43 UTC, luoxueyasha approved these changes

2023-08-21 02:12 UTC, merged