Additional bars 3.0.1 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #3389
Opened 2023-06-22 03:34 UTC by sea-turtle0

- [x ] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x ] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-06-28 09:25 UTC, ChuijkYahus requested changes

2023-06-28 09:25 UTC, ChuijkYahus commented on projects/1.18/assets/additional-bars/additionalbars/lang/zh_cn.json
> +  "block.additionalbars.warped_bars": "诡异菌核栏杆",
```suggestion
  "block.additionalbars.crimson_bars": "绯红木栏杆",
  "block.additionalbars.warped_bars": "诡异木栏杆",
```
请全文修改

2023-06-28 09:25 UTC, ChuijkYahus commented on projects/1.18/assets/additional-bars/additionalbars/lang/zh_cn.json
> +  "tooltip.gamma1772.regular": "有规则的",
```suggestion
  "tooltip.gamma1772.regular": "普通",
```

2023-06-28 09:25 UTC, ChuijkYahus commented on projects/1.18/assets/additional-bars/additionalbars/lang/zh_cn.json
> +  "block.additionalbars.crossed_warped_bars": "诡异菌核栏杆（交叉）",
原文没有这些括号
这些应该是用文档末尾的tooltip实现的，请全文删除

2023-06-28 22:40 UTC, sea-turtle0 commented on projects/1.18/assets/additional-bars/additionalbars/lang/zh_cn.json
> +  "block.additionalbars.warped_bars": "诡异菌核栏杆",
修改完毕

2023-06-28 22:40 UTC, sea-turtle0 commented on projects/1.18/assets/additional-bars/additionalbars/lang/zh_cn.json
> +  "tooltip.gamma1772.regular": "有规则的",
修改完毕

2023-06-28 22:41 UTC, sea-turtle0 commented on projects/1.18/assets/additional-bars/additionalbars/lang/zh_cn.json
> +  "block.additionalbars.crossed_warped_bars": "诡异菌核栏杆（交叉）",
修改完毕

2023-06-29 04:38 UTC, ChuijkYahus commented
貌似删到了其他模组的东西，请注意补回以消除影响

2023-06-29 04:46 UTC, sea-turtle0 commented
> 貌似删到了其他模组的东西，请注意补回以消除影响

啊哈哈，批量的时候貌似改到其他mod了，sry

2023-06-29 04:48 UTC, ChuijkYahus commented on projects/1.18/assets/additional-bars/additionalbars/lang/zh_cn.json
> +  "block.additionalbars.crossed_copper_bars": "铜栏杆 ",
```suggestion
  "block.additionalbars.crossed_copper_bars": "铜栏杆 ",
```
注意删除多余空格，全文修改

2023-06-29 04:48 UTC, ChuijkYahus commented on projects/1.18/assets/additional-bars/additionalbars/lang/zh_cn.json
> +  "block.additionalbars.crossed_warped_bars": "诡异菌核栏杆",
```suggestion
  "block.additionalbars.crossed_crimson_bars": "绯红木栏杆",
  "block.additionalbars.crossed_warped_bars": "诡异木栏杆",
```
全文修改

2023-06-29 05:09 UTC, sea-turtle0 commented on projects/1.18/assets/additional-bars/additionalbars/lang/zh_cn.json
> +  "block.additionalbars.crossed_copper_bars": "铜栏杆 ",
抱歉，替换完忘删了

2023-06-29 05:10 UTC, sea-turtle0 commented on projects/1.18/assets/additional-bars/additionalbars/lang/zh_cn.json
> +  "block.additionalbars.crossed_warped_bars": "诡异菌核栏杆",
又傻了，没注意，抱歉

2023-06-29 05:13 UTC, ChuijkYahus commented on projects/1.18/assets/additional-bars/additionalbars/lang/zh_cn.json
> +  "block.additionalbars.horizontal_crossed_warped_bars": "诡异菌核栏杆",
```suggestion
  "block.additionalbars.horizontal_crossed_crimson_bars" :"绯红木栏杆",
  "block.additionalbars.horizontal_crossed_warped_bars": "诡异木栏杆",
```

2023-06-29 05:15 UTC, sea-turtle0 commented on projects/1.18/assets/additional-bars/additionalbars/lang/zh_cn.json
> +  "block.additionalbars.horizontal_crossed_warped_bars": "诡异菌核栏杆",
抱歉啊抱歉，又双叒叕漏看了

2023-06-29 05:18 UTC, ChuijkYahus commented
貌似改错了

2023-06-29 05:21 UTC, ChuijkYahus commented on projects/1.18/assets/additional-bars/additionalbars/lang/zh_cn.json
> +  "block.additionalbars.horizontal_crossed_warped_bars": "诡异菌核栏杆",
你这也没改上啊

2023-06-29 05:24 UTC, sea-turtle0 commented
> 貌似改错了

啊咧，现在呢

2023-06-29 05:25 UTC, sea-turtle0 commented
> 貌似改错了

我这里看着没问题了（？）

2023-06-29 05:26 UTC, ChuijkYahus commented on projects/1.18/assets/additional-bars/additionalbars/lang/zh_cn.json
> +  "block.additionalbars.horizontal_crossed_oxidized_copper_bars": "氧化的铜栏",
```suggestion
  "block.additionalbars.horizontal_crossed_oxidized_copper_bars": "氧化的铜栏杆",
```

2023-06-29 05:26 UTC, ChuijkYahus commented on projects/1.18/assets/additional-bars/additionalbars/lang/zh_cn.json
> +  "block.additionalbars.horizontal_crossed_oxidized_copper_bars": "氧化的铜栏",
不好评价

2023-06-29 05:28 UTC, ChuijkYahus commented on projects/1.18/assets/additional-bars/additionalbars/lang/zh_cn.json
> +  "block.additionalbars.horizontal_crossed_oxidized_copper_bars": "氧化的铜栏",
改好就OK了

2023-06-29 05:29 UTC, ChuijkYahus approved these changes

2023-06-29 05:29 UTC, sea-turtle0 commented
我的加速器可能出了点问题（

2023-06-29 05:30 UTC, sea-turtle0 commented
幸亏有邮箱，对话刷新真的慢（

2023-06-29 05:31 UTC, ChuijkYahus commented
> 幸亏有邮箱，对话刷新真的慢（

确实（）

2023-06-29 16:42 UTC, mamaruo approved these changes

2023-06-30 05:02 UTC, merged