Magnum Torch 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3392
Opened 2023-06-22 12:12 UTC by Huantanhua

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-06-26 23:39 UTC, luoxueyasha requested changes

2023-06-26 23:39 UTC, luoxueyasha commented on projects/1.19/assets/magnum-torch-forge/magnumtorch/lang/zh_cn.json
> +  "block.magnumtorch.diamond_magnum_torch": "钻石卓越火炬",
确定是`火炬`而非`火把`吗

2023-06-26 23:39 UTC, luoxueyasha commented on projects/1.19/assets/magnum-torch-forge/magnumtorch/lang/zh_cn.json
> +  "block.magnumtorch.magnum_torch.info.shape_type": "形状种类：%s",
游戏内实际显示效果？

2023-06-26 23:39 UTC, luoxueyasha commented on projects/1.19/assets/magnum-torch-forge/magnumtorch/lang/zh_cn.json
> +  "block.magnumtorch.magnum_torch.info": "阻止生物大范围生成。",
```suggestion
  "block.magnumtorch.magnum_torch.info": "阻止生物在大范围内生成。",
```
嗯……只能说改前有种说不上来的怪异，理论上不改也行？

2023-06-26 23:39 UTC, luoxueyasha commented on projects/1.19/assets/magnum-torch-forge/magnumtorch/lang/zh_cn.json
> +  "block.magnumtorch.diamond_magnum_torch": "钻石卓越火炬",
`magnum torch`的实际游戏贴图及模型？如何解释`magnum`译为`卓越`？

2023-06-26 23:46 UTC, Huantanhua commented
本模组有官方的zh_cn文件，但汉化不完全，缺少了最后一行模组组名的翻译。Magnum Torch 是在复刻更多实用设备里的 MagnumTorch：https://www.mcmod.cn/item/2401.html。更多实用设备里的Magnum Torch 翻译就是卓越火炬。

&nbsp;


花鳥風月
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月27日(星期二) 上午7:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CFPAOrg/Minecraft-Mod-Language-Package] Magnum Torch 翻译提交 (PR #3392)





 
@luoxueyasha requested changes on this pull request.
 
 
In projects/1.19/assets/magnum-torch-forge/magnumtorch/lang/zh_cn.json:
 &gt; @@ -0,0 +1,15 @@ +{ +  "block.magnumtorch.diamond_magnum_torch": "钻石卓越火炬",  
确定是火炬而非火把吗
 
 
In projects/1.19/assets/magnum-torch-forge/magnumtorch/lang/zh_cn.json:
 &gt; @@ -0,0 +1,15 @@ +{ +  "block.magnumtorch.diamond_magnum_torch": "钻石卓越火炬", +  "block.magnumtorch.emerald_magnum_torch": "绿宝石卓越火炬", +  "block.magnumtorch.amethyst_magnum_torch": "紫水晶卓越火炬", +  "block.magnumtorch.magnum_torch.info": "阻止生物大范围生成。", +  "block.magnumtorch.magnum_torch.info.more": "长按 %s 查看更多信息", +  "block.magnumtorch.magnum_torch.info.shift": "Shift", +  "block.magnumtorch.magnum_torch.info.mob_types": "生物种类：%s", +  "block.magnumtorch.magnum_torch.info.blacklist": "黑名单：%s", +  "block.magnumtorch.magnum_torch.info.whitelist": "白名单：%s", +  "block.magnumtorch.magnum_torch.info.shape_type": "形状种类：%s",  
游戏内实际显示效果？
 
 
In projects/1.19/assets/magnum-torch-forge/magnumtorch/lang/zh_cn.json:
 &gt; @@ -0,0 +1,15 @@ +{ +  "block.magnumtorch.diamond_magnum_torch": "钻石卓越火炬", +  "block.magnumtorch.emerald_magnum_torch": "绿宝石卓越火炬", +  "block.magnumtorch.amethyst_magnum_torch": "紫水晶卓越火炬", +  "block.magnumtorch.magnum_torch.info": "阻止生物大范围生成。",  ⬇️ Suggested change -  "block.magnumtorch.magnum_torch.info": "阻止生物大范围生成。", +  "block.magnumtorch.magnum_torch.info": "阻止生物在大范围内生成。",  
嗯……只能说改前有种说不上来的怪异，理论上不改也行？
 
 
In projects/1.19/assets/magnum-torch-forge/magnumtorch/lang/zh_cn.json:
 &gt; @@ -0,0 +1,15 @@ +{ +  "block.magnumtorch.diamond_magnum_torch": "钻石卓越火炬",  
magnum torch的实际游戏贴图及模型？如何解释magnum译为卓越？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-07-04 17:54 UTC, mamaruo requested changes
官译并非圭臬

2023-07-04 17:54 UTC, mamaruo commented on projects/1.19/assets/magnum-torch-forge/magnumtorch/lang/zh_cn.json
> +  "block.magnumtorch.magnum_torch.info": "阻止生物大范围生成。",
原文：**Prevents mob spawns in a huge area.**

```suggestion
  "block.magnumtorch.magnum_torch.info": "在一个很大的范围内阻止生物生成。",
```

2023-07-04 17:54 UTC, mamaruo commented on projects/1.19/assets/magnum-torch-forge/magnumtorch/lang/zh_cn.json
> +  "block.magnumtorch.magnum_torch.info.more": "长按 %s 查看更多信息",
```suggestion
  "block.magnumtorch.magnum_torch.info.more": "长按%s查看更多信息",
```

2023-07-15 07:07 UTC, mamaruo approved these changes

2023-07-19 05:02 UTC, merged