SecurityCraft翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #3406
Opened 2023-06-25 02:51 UTC by MCTF-Alpha-27

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-06-25 02:56 UTC, MCTF-Alpha-27 commented
/update-en security-craft 1.12.2

2023-06-26 23:35 UTC, luoxueyasha requested changes
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/0b311ef1-d263-4c2d-96d5-d979f9d35809)

英文文件应与中文文件逐行对应

2023-06-30 10:31 UTC, DrIceTea123 commented
#2689

2023-07-27 16:03 UTC, Cactusstudent submitted a review, later dismissed

2023-07-30 10:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3406) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3406) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3406) it.</sub>

2023-08-04 07:08 UTC, Cactusstudent approved these changes

2023-08-04 08:07 UTC, luoxueyasha requested changes
翻译上看不出问题了，但是为什么中文文件和英文文件的行数还是不一致？

2023-08-06 03:04 UTC, MCTF-Alpha-27 commented
> 翻译上看不出问题了，但是为什么中文文件和英文文件的行数还是不一致？

作者在新版本改了一些物品的注册名，现在对不上行数是因为我先删除了这一部分

2023-11-19 08:48 UTC, ChuijkYahus commented
这个PR可以合并吗

2023-11-19 10:00 UTC, luoxueyasha approved these changes

2023-11-19 10:01 UTC, merged