Terraincognita翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #3407
Opened 2023-06-25 04:10 UTC by LonelyPrime

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-06-26 01:31 UTC, ChuijkYahus requested changes

2023-06-26 01:31 UTC, ChuijkYahus commented on projects/1.18/assets/terraincognita/terraincognita/lang/zh_cn.json
> +  "block.terraincognita.potted_heather": "石楠花盆栽",
```suggestion
  "block.terraincognita.heather": "帚石南",
  "block.terraincognita.potted_heather": "帚石南盆栽",
```
http://www.iplant.cn/info/Calluna%20vulgaris

2023-06-26 01:31 UTC, ChuijkYahus commented on projects/1.18/assets/terraincognita/terraincognita/lang/zh_cn.json
> +  "block.terraincognita.potted_fireweed": "火草盆栽",
```suggestion
  "block.terraincognita.fireweed": "柳兰",
  "block.terraincognita.potted_fireweed": "柳兰盆栽",
```
文档里其他部分还叫柳兰，这里改成火草不大合适，注意文档统一

2023-06-26 01:31 UTC, ChuijkYahus commented on projects/1.18/assets/terraincognita/terraincognita/lang/zh_cn.json
> +  "block.terraincognita.potted_water_flag": "沼泽鸢尾盆栽",
```suggestion
  "block.terraincognita.water_flag": "黄菖蒲",
  "block.terraincognita.potted_water_flag": "黄菖蒲盆栽",
```
http://www.iplant.cn/info/Iris%20pseudacorus

2023-06-26 01:31 UTC, ChuijkYahus commented on projects/1.18/assets/terraincognita/terraincognita/lang/zh_cn.json
> +  "block.terraincognita.apple_cabinet": "苹果柜",
```suggestion
  "block.terraincognita.apple_cabinet": "苹果木厨柜",
```
农夫乐事兼容，请遵循农夫乐事译法

2023-06-26 01:31 UTC, ChuijkYahus commented on projects/1.18/assets/terraincognita/terraincognita/lang/zh_cn.json
> +  "block.terraincognita.ginkgo_vertical_slab": "银杏木垂直台阶",
```suggestion
  "block.terraincognita.ginkgo_vertical_slab": "银杏木竖直台阶",
```

2023-06-26 01:31 UTC, ChuijkYahus commented on projects/1.18/assets/terraincognita/terraincognita/lang/zh_cn.json
> +  "block.terraincognita.ginkgo_cabinet": "银杏柜",
```suggestion
  "block.terraincognita.ginkgo_hedge": "银杏树篱",
  "block.terraincognita.ginkgo_leaf_carpet": "银杏树叶地毯",
  "block.terraincognita.ginkgo_beehive": "银杏木蜂箱",
  "block.terraincognita.ginkgo_cabinet": "银杏木厨柜",
```

2023-06-26 01:31 UTC, ChuijkYahus commented on projects/1.18/assets/terraincognita/terraincognita/lang/zh_cn.json
> +  "block.terraincognita.hazel_cabinet": "榛木柜",
```suggestion
  "block.terraincognita.hazel_cabinet": "榛木厨柜",
```

2023-06-26 01:31 UTC, ChuijkYahus commented on projects/1.18/assets/terraincognita/terraincognita/lang/zh_cn.json
> +  "block.terraincognita.larch_vertical_slab": "落叶松木垂直台阶",
```suggestion
  "block.terraincognita.larch_vertical_slab": "落叶松木竖直台阶",
```

2023-06-26 01:31 UTC, ChuijkYahus commented on projects/1.18/assets/terraincognita/terraincognita/lang/zh_cn.json
> +  "block.terraincognita.larch_cabinet": "落叶松柜",
```suggestion
  "block.terraincognita.larch_hedge": "落叶松树篱",
  "block.terraincognita.larch_leaf_carpet": "落叶松树叶地毯",
  "block.terraincognita.larch_beehive": "落叶松木蜂箱",
  "block.terraincognita.larch_cabinet": "落叶松木厨柜",
```

2023-06-26 01:31 UTC, ChuijkYahus commented on projects/1.18/assets/terraincognita/terraincognita/lang/zh_cn.json
> +  "block.minecraft.banner.ti_butterfly.lime": "亮绿色蝴蝶",
```suggestion
  "block.minecraft.banner.ti_butterfly.lime": "黄绿色蝴蝶",
```
请注意参考原版16色用语，不要自造词

2023-06-26 01:31 UTC, ChuijkYahus commented on projects/1.18/assets/terraincognita/terraincognita/lang/zh_cn.json
> +  "block.minecraft.banner.ti_butterfly.light_blue": "浅蓝色蝴蝶",
```suggestion
  "block.minecraft.banner.ti_butterfly.light_blue": "淡蓝色蝴蝶",
```

2023-06-26 16:22 UTC, ChuijkYahus commented on projects/1.18/assets/terraincognita/terraincognita/lang/zh_cn.json
> +  "_comment": "每级减半进食速度。在食用太妃糖时生效。",
这里也可以换回英文

2023-06-26 16:33 UTC, ChuijkYahus submitted a review, later dismissed
感觉应该没问题了？

2023-06-26 16:33 UTC, ChuijkYahus commented on projects/1.18/assets/terraincognita/terraincognita/lang/zh_cn.json
> +  "_comment": "每级减半进食速度。在食用太妃糖时生效。",
改完可自己resolve conversation

2023-06-27 16:43 UTC, ChuijkYahus commented
请注意更新中文文件

2023-06-27 16:45 UTC, LonelyPrime commented
> 请注意更新中文文件

中文也一起更新了

2023-06-27 16:50 UTC, ChuijkYahus commented
> > 请注意更新中文文件
> 
> 中文也一起更新了

![图片](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/297184b6-0539-4eaa-a345-81057125523b)
还是对一下

2023-06-27 17:59 UTC, ChuijkYahus commented on projects/1.18/assets/terraincognita/terraincognita/lang/zh_cn.json
> +  "block.terraincognita.vertical_hazel_planks": "竖纹榛木板",
```suggestion
  "block.terraincognita.vertical_hazel_planks": "竖纹榛木木板",
```
采用橡木木板翻译方法，具体相关规则可以去看群里的精华消息，欢迎提出意见

2023-06-28 07:13 UTC, ChuijkYahus approved these changes

2023-06-29 15:04 UTC, merged