Better-azalea翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3409
Opened 2023-06-25 06:06 UTC by LonelyPrime

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-06-25 06:11 UTC, mamaruo commented
> ⚠ 警告：Mod Domain 验证不通过。文件 Mod Domain 为 betterazalea；而 PR 所提供的 Mod Domain 为 azalea。

瞎扯的，已确认模组文件中的命名空间为 azalea

标题已代为修改

2023-06-25 06:21 UTC, mamaruo requested changes
XX Wall Sign 墙上的XX告示牌
Planks 木板

> "block.azalea.moss": "表面苔藓",
"block.azalea.moss_layer": "苔藓层",

这两行所指方块什么特征，需要确认。它和原版的覆地苔藓（Moss Carpet，1.18时译为“苔藓地毯”）有什么区别和联系？

"block.azalea.azalea_flower": "杜鹃木", 这翻译的啥，flower呢

提示：
- 请认真阅读，随时查阅该列表：[Minecraft Wiki:译名标准化 - Minecraft Wiki，最详细的我的世界百科](https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96)
commit message (提交消息) 不等同于 Pull Request 的标题，不需要符合“模组英文名+空格+简述”的格式。请在 commit message 中总结当前修改的内容，以便审查。`按审阅意见修改` `修正 Wall Sign 翻译` `补充遗漏翻译`，诸如此类

2023-06-25 07:11 UTC, LonelyPrime commented
> XX Wall Sign 墙上的XX告示牌 Planks 木板
> 
> > "block.azalea.moss": "表面苔藓",
> > "block.azalea.moss_layer": "苔藓层",
> 
> 这两行所指方块什么特征，需要确认。它和原版的覆地苔藓（Moss Carpet，1.18时译为“苔藓地毯”）有什么区别和联系？
> 
> "block.azalea.azalea_flower": "杜鹃木", 这翻译的啥，flower呢
> 
> 提示：
> 
> * 请认真阅读，随时查阅该列表：[Minecraft Wiki:译名标准化 - Minecraft Wiki，最详细的我的世界百科](https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96)
> * commit message (提交消息) 不等同于 Pull Request 的标题，不需要符合“模组英文名+空格+简述”的格式。请在 commit message 中总结当前修改的内容，以便审查。`按审阅意见修改` `修正 Wall Sign 翻译` `补充遗漏翻译`，诸如此类

苔藓层更像原版的雪(Sonw)而不是苔藓地毯，能多层叠加，单层高度一样，无法站在单层苔藓层上。表面苔藓则是能放置在方块的六个表面，非常薄，像是一层贴图。

2023-06-25 07:29 UTC, ChuijkYahus commented on projects/1.18/assets/better-azalea/azalea/lang/zh_cn.json
> +"block.azalea.azalea_planks": "杜鹃木材",
```suggestion
"block.azalea.azalea_planks": "杜鹃木板",
```

2023-06-25 07:29 UTC, ChuijkYahus commented on projects/1.18/assets/better-azalea/azalea/lang/zh_cn.json
> +"block.azalea.flowering_azalea_wood": "盛开的杜鹃花木",
```suggestion
"block.azalea.flowering_azalea_fence": "盛开的杜鹃木栅栏",
"block.azalea.flowering_azalea_fence_gate": "盛开的杜鹃木栅栏门",
"block.azalea.flowering_azalea_log": "盛开的杜鹃原木",
"block.azalea.flowering_azalea_planks": "盛开的杜鹃木板",
"block.azalea.flowering_azalea_slab": "盛开的杜鹃木台阶",
"block.azalea.flowering_azalea_stairs": "盛开的杜鹃木楼梯",
"block.azalea.flowering_azalea_trapdoor": "盛开的杜鹃木活板门",
"block.azalea.flowering_azalea_wood": "盛开的杜鹃木",
```
这也没改完啊

2023-06-25 07:29 UTC, ChuijkYahus commented on projects/1.18/assets/better-azalea/azalea/lang/zh_cn.json
> +"block.azalea.flowering_azalea_wall_sign": "墙上的盛开的杜鹃花木告示牌"
```suggestion
"block.azalea.flowering_azalea_sign": "盛开的杜鹃木告示牌",
"block.azalea.flowering_azalea_wall_sign": "墙上的盛开的杜鹃木告示牌"
```

2023-06-25 07:36 UTC, LonelyPrime commented on projects/1.18/assets/better-azalea/azalea/lang/zh_cn.json
> +"block.azalea.flowering_azalea_wood": "盛开的杜鹃花木",
我错了，我对着模组作者将内容搬迁后那个mod（丰富的生态 (Ecologics)）的mod百科词条改的

2023-06-25 11:42 UTC, ChuijkYahus commented on projects/1.18/assets/better-azalea/azalea/lang/zh_cn.json
> +"block.azalea.flowering_azalea_wood": "盛开的杜鹃花木",
可以看下库里的Ecologics翻译

2023-06-26 01:35 UTC, ChuijkYahus commented on projects/1.18/assets/better-azalea/azalea/lang/zh_cn.json
> +"block.azalea.moss": "表面苔藓",
```suggestion
"block.azalea.moss": "苔藓薄层",
```
仅建议

2023-06-26 02:14 UTC, LonelyPrime commented on projects/1.18/assets/better-azalea/azalea/lang/zh_cn.json
> +"block.azalea.moss": "表面苔藓",
确实更好听

2023-06-26 08:35 UTC, ChuijkYahus approved these changes

2023-06-30 06:25 UTC, merged