Productive Villagers翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3415
Opened 2023-06-25 14:22 UTC by LonelyPrime

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-06-25 14:23 UTC, LonelyPrime commented
/add-mapping productive-villagers 664389

2023-06-26 00:53 UTC, luoxueyasha approved these changes

2023-06-26 09:01 UTC, mamaruo requested changes
请留意文本所处位置，感觉有些文本是村民职业，处理并不到位。

2023-06-26 09:01 UTC, mamaruo commented on projects/1.18/assets/productive-villagers/productivevillagers/lang/zh_cn.json
> +  "tooltip.productivevillagers.job_process_stack": "处理多余废料",
Exceed materials 一定是废料吗

2023-06-26 15:57 UTC, LonelyPrime commented
> 请留意文本所处位置，感觉有些文本是村民职业，处理并不到位。

村民的任务是根据原版的职业及更多村民模组增加的两个职业来的，而且我在游戏中。。。找不到这些信息在哪里，只能找到一个工作站仓库方块，找不到tooltip

2023-06-26 23:25 UTC, luoxueyasha commented on projects/1.18/assets/productive-villagers/productivevillagers/lang/zh_cn.json
> +  "tooltip.productivevillagers.job_repair_tools": "工具修复",
游戏内实际显示效果？

2023-06-27 17:47 UTC, LonelyPrime commented on projects/1.18/assets/productive-villagers/productivevillagers/lang/zh_cn.json
> +  "tooltip.productivevillagers.job_repair_tools": "工具修复",
没有显示，或者说找不到

2023-07-20 07:11 UTC, mamaruo commented on projects/1.18/assets/productive-villagers/productivevillagers/lang/zh_cn.json
> +  "tooltip.productivevillagers.job_repair_tools": "工具修复",
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/37480168/1c4dd4b2-9756-4671-a914-86a06b538b02)
把 Depot 放在村民的工作方块旁边，Depot 旁的图标的提示框。

2023-07-20 07:13 UTC, mamaruo approved these changes

2023-07-21 14:58 UTC, merged