ScalingGUIs 汉化提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3420
Opened 2023-06-28 03:30 UTC by mczph

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-06-28 10:52 UTC, luoxueyasha requested changes

2023-06-28 10:52 UTC, luoxueyasha commented on projects/1.12.2/assets/scalingguis/scalingguis/lang/zh_cn.lang
> +scalingguis.config.main.title=GUI 缩放大小配置
```suggestion
scalingguis.config.main.title=ScalingGUIs 配置
```
原译在操作界面上可能会有割裂感，具体请以实际游戏效果进行修改

2023-06-28 10:52 UTC, luoxueyasha commented on projects/1.12.2/assets/scalingguis/scalingguis/lang/zh_cn.lang
> +scalingguis.config.individual.add.title=新的个体条目
前后`Individual`翻译不一致（独立、单个、个体），实际游戏效果？

2023-06-28 10:52 UTC, luoxueyasha commented on projects/1.12.2/assets/scalingguis/scalingguis/lang/zh_cn.lang
> +scalingguis.config.add.classname.tooltip=新 GUI 条目的完整类名。 例如：’net.minecraft.client.gui.GuiMainMenu‘。
```suggestion
scalingguis.config.add.classname.tooltip=新 GUI 条目的完整类名。 例如：“net.minecraft.client.gui.GuiMainMenu”。
```
见 https://cfpa.site/TransRules/
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/ba9de234-dcd8-495b-adc6-5ec577676e9c)
如果存在使用单引号的必要的话，请说明

2023-06-28 10:52 UTC, luoxueyasha commented on projects/1.12.2/assets/scalingguis/scalingguis/lang/zh_cn.lang
> +scalingguis.config.add.displayname.tooltip=新 GUI 条目的显示名称。 例如：‘Main Menu’。
```suggestion
scalingguis.config.add.displayname.tooltip=新 GUI 条目的显示名称。 例如：“Main Menu”。
```

2023-06-28 10:52 UTC, luoxueyasha commented on projects/1.12.2/assets/scalingguis/scalingguis/lang/zh_cn.lang
> +scalingguis.config.main.tooltipscale=工具提示缩放大小
`Tooltip`的翻译有待商榷，详见[提示框 - Minecraft Wiki](https://minecraft.fandom.com/zh/wiki/%E6%8F%90%E7%A4%BA%E6%A1%86)
可以参考[模组翻译词典](https://dict.mcmod.cn/)以查看其他模组对该词语的翻译

2023-06-28 10:52 UTC, luoxueyasha commented on projects/1.12.2/assets/scalingguis/scalingguis/lang/zh_cn.lang
> +scalingguis.config.main.persistentlog=单独的持久化日志
实际显示效果，以及功能？

2023-06-28 10:52 UTC, luoxueyasha commented on projects/1.12.2/assets/scalingguis/scalingguis/lang/zh_cn.lang
> +scalingguis.config.main.persistentlog.tooltip=跟踪配置文件中打开的 GUI 类名称。 /n启动 Minecraft 时将重新加载跟踪的名称。
```suggestion
scalingguis.config.main.persistentlog.tooltip=跟踪配置文件中打开的 GUI 类名称。/n启动 Minecraft 时将重新加载跟踪的名称。
```
这里似乎没必要加入空格，除非真的存在换行符失效问题
此类问题请全文通查

2023-06-28 17:47 UTC, mamaruo commented on projects/1.12.2/assets/scalingguis/scalingguis/lang/zh_cn.lang
> +scalingguis.config.main.tooltipscale=工具提示缩放大小
- #908 
- #909

如有必要可以再次讨论。

2023-06-28 20:57 UTC, mamaruo commented on projects/1.12.2/assets/scalingguis/scalingguis/lang/zh_cn.lang
> +scalingguis.config.individual.add.title=新的个体条目
Custom Individual GUI Scales provides a menu to set the scales for individual GUIs.

2023-06-28 23:17 UTC, mczph commented on projects/1.12.2/assets/scalingguis/scalingguis/lang/zh_cn.lang
> +scalingguis.config.main.persistentlog=单独的持久化日志
记录名称就是记录打开过的GUI的类名，持久化日志这个我也不懂，不过persistentlog网上查了一下是这个

2023-06-28 23:24 UTC, mczph commented on projects/1.12.2/assets/scalingguis/scalingguis/lang/zh_cn.lang
> +scalingguis.config.main.persistentlog=单独的持久化日志
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/103164772/1ca4bc4e-8658-4efc-85cd-b17dce6ad339)

2023-06-28 23:30 UTC, mczph commented on projects/1.12.2/assets/scalingguis/scalingguis/lang/zh_cn.lang
> +scalingguis.config.main.persistentlog.tooltip=跟踪配置文件中打开的 GUI 类名称。 /n启动 Minecraft 时将重新加载跟踪的名称。
经游戏内测时，出现了换行符失效，故保留

2023-06-29 15:47 UTC, ChuijkYahus commented on projects/1.12.2/assets/scalingguis/scalingguis/lang/zh_cn.lang
> +scalingguis.config.add.classname.tooltip=新 GUI 条目的完整类名。 例如：“net.minecraft.client.gui.GuiMainMenu”。
```suggestion
scalingguis.config.add.classname.tooltip=新 GUI 条目的完整类名。例如：“net.minecraft.client.gui.GuiMainMenu”。
```

2023-06-30 00:33 UTC, mczph commented on projects/1.12.2/assets/scalingguis/scalingguis/lang/zh_cn.lang
> +scalingguis.config.add.classname.tooltip=新 GUI 条目的完整类名。 例如：“net.minecraft.client.gui.GuiMainMenu”。
这个地方游戏内如果删掉了换行，
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/103164772/f0c3f17a-895c-4149-ac4f-0acdb4e94131)

2023-06-30 05:00 UTC, ChuijkYahus commented on projects/1.12.2/assets/scalingguis/scalingguis/lang/zh_cn.lang
> +scalingguis.config.add.classname.tooltip=新 GUI 条目的完整类名。 例如：“net.minecraft.client.gui.GuiMainMenu”。
没问题了

2023-06-30 05:00 UTC, ChuijkYahus submitted a review, later dismissed

2023-07-01 04:49 UTC, mamaruo requested changes
一般遵循settings翻译成设置，options翻译成选项，configuration/config翻译成配置。

Select/new 建议是否应译为 选取/新建。

2023-07-01 10:38 UTC, mczph commented
加的一点“的”避免歧义，前面几个改称“新建”了，这里因为
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/103164772/afc53e7c-1726-4653-9aa4-6d5b96fd759c)
所以ba保留“新”

2023-07-01 11:21 UTC, mamaruo approved these changes

2023-07-06 17:49 UTC, merged