[R] 提交 VoluminousEnergy 模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #3426
Opened 2023-06-29 11:13 UTC by xiaohuigehhy

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-06-29 14:27 UTC, mamaruo commented
你看的哪里的远古教程提交的 PR
标题有误，请修改。

详见：https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#github-pr

2023-07-27 15:49 UTC, Cactusstudent requested changes

2023-07-27 15:49 UTC, Cactusstudent commented on projects/1.16/assets/voluminous-energy/voluminousenergy/lang/zh_cn.json
> +    "text.voluminousenergy.multiblock.distillation_unit.requirements": "需要 3x3x3 的铝机外壳在此方块的后面",
```suggestion
    "text.voluminousenergy.multiblock.distillation_unit.requirements": "此方块的后面需要3x3x3大小的铝机外壳",

```

2023-07-27 15:49 UTC, Cactusstudent commented on projects/1.16/assets/voluminous-energy/voluminousenergy/lang/zh_cn.json
> +    "text.voluminousenergy.multiblock.blast_furnace.requirements": "需要 3x3x3 钛机外壳在此方块的后面",
```suggestion
    "text.voluminousenergy.multiblock.blast_furnace.requirements": "此方块的后面需要3x3x3大小的钛机外壳",

```

2023-07-27 15:49 UTC, Cactusstudent commented on projects/1.16/assets/voluminous-energy/voluminousenergy/lang/zh_cn.json
> +    "text.voluminousenergy.percent_complete": "完成了",
了不太合适，可以使用xx百分比，下同

2023-07-27 15:49 UTC, Cactusstudent commented on projects/1.16/assets/voluminous-energy/voluminousenergy/lang/zh_cn.json
> +    "block.voluminousenergy.carbon_shielded_aluminum_machine_frame": "碳防护的铝机架",
需要考证

2023-07-27 15:49 UTC, Cactusstudent commented on projects/1.16/assets/voluminous-energy/voluminousenergy/lang/zh_cn.json
> +    "block.voluminousenergy.aluminum_machine_casing": "铝机外壳",
应翻译为xx机壳，建议全文清查

2023-07-30 10:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3426) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3426) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3426) it.</sub>

2023-08-08 10:58 UTC, xiaohuigehhy reviewed
翻译修正

2023-08-10 03:34 UTC, Cactusstudent commented on projects/1.16/assets/voluminous-energy/voluminousenergy/lang/zh_cn.json
> +    "text.voluminousenergy.multiblock.blast_furnace.requirements": "此方块的后面需要 3x3x3 大小的钛质机壳",
```suggestion
    "text.voluminousenergy.multiblock.distillation_unit.requirements": "此方块的后面需要3x3x3大小的铝质机壳",
    "text.voluminousenergy.multiblock.blast_furnace.requirements": "此方块的后面需要3x3x3大小的钛质机壳",
```

2023-08-14 06:27 UTC, Cactusstudent approved these changes

2023-08-15 07:24 UTC, merged