提交Compat Makeover翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #3427
Opened 2023-06-29 21:31 UTC by Music0Kirby

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-06-30 12:28 UTC, mamaruo commented
标题格式不对

2023-07-22 23:33 UTC, luoxueyasha commented
请将标题修改为`Compat Makeover 翻译提交`

2023-07-22 23:35 UTC, luoxueyasha requested changes

2023-07-22 23:35 UTC, luoxueyasha commented on projects/1.19/assets/compat-makeover/compat_makeover/lang/zh_cn.json
> +    "block.compat_makeover.polished_illunite": "磨制伊鲁尼特块",
在库中现存的`illunite`翻译为`幻靛晶`。（biomemakeover 1.18）
请问`伊鲁尼特`是现存的官译或社区推崇的译名吗？
若不是，请全文通查

2023-07-30 07:13 UTC, luoxueyasha commented
@Music0Kirby 
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

2023-07-30 07:16 UTC, Music0Kirby commented
那个好像是https://github.com/Lemonszz/Biome-Makeover/pull/214/files版本里的翻译

落雪鸦杀 ***@***.***> 于2023年7月23日周日 07:36写道：

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In projects/1.19/assets/compat-makeover/compat_makeover/lang/zh_cn.json
> <https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/3427#discussion_r1271359133>
> :
>
> > +    "block.compat_makeover.willow_railing": "柳木扶手",
> +    "block.compat_makeover.ww_willow_boards": "柳木宽木板",
> +    "block.compat_makeover.willow_leaf_pile": "柳木树叶堆",
> +
> +
> +    "block.compat_makeover.mesmerite_bricks": "磨制迷魂石",
> +    "block.compat_makeover.mesmerite_bricks_slab": "磨制迷魂石台阶",
> +    "block.compat_makeover.mesmerite_bricks_wall": "磨制迷魂石墙",
> +    "block.compat_makeover.mesmerite_bricks_vertical_slab": "磨制迷魂石竖直台阶",
> +    "block.compat_makeover.mesmerite_pillar": "磨制迷魂石柱",
> +    "block.compat_makeover.polished_mesmerite_vertical_slab": "磨制迷魂石竖直台阶",
> +    "block.compat_makeover.mesmerite_vertical_slab": "迷魂石竖直台阶",
> +    "block.compat_makeover.chiseled_mesmerite_bricks": "錾制磨制迷魂石",
> +    "block.compat_makeover.mesmerite_bricks_stairs": "磨制迷魂石楼梯",
> +
> +    "block.compat_makeover.polished_illunite": "磨制伊鲁尼特块",
>
> 在库中现存的illunite翻译为幻靛晶。（biomemakeover 1.18）
> 请问伊鲁尼特是现存的官译或社区推崇的译名吗？
> 若不是，请全文通查
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/3427#pullrequestreview-1542161132>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANOJPWPPN4KT2ZMDVITARX3XRRPWBANCNFSM6AAAAAAZZBMWE4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> .com>
>

2023-07-30 07:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3427) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3427) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3427) it.</sub>

2023-07-30 07:23 UTC, Music0Kirby reviewed
（补充）

2023-07-30 07:23 UTC, Music0Kirby commented on projects/1.19/assets/compat-makeover/compat_makeover/lang/zh_cn.json
> +    "block.compat_makeover.polished_illunite": "磨制伊鲁尼特块",
好像是https://github.com/Lemonszz/Biome-Makeover/pull/214/files版本里的翻译（biomemakeover 1.19）

2023-08-26 04:44 UTC, Cactusstudent commented on projects/1.19/assets/compat-makeover/compat_makeover/lang/zh_cn.json
> +  "block.compat_makeover.swamp_cypress_hedge": "沼泽柏木 叶篱",
```suggestion
  "block.compat_makeover.swamp_cypress_hedge": "沼泽柏木叶篱",
```

2023-08-27 07:10 UTC, Music0Kirby reviewed
大致应该修正好了（？）

2023-08-27 07:19 UTC, Music0Kirby commented on projects/1.19/assets/compat-makeover/compat_makeover/lang/zh_cn.json
> +    "block.compat_makeover.polished_illunite": "磨制伊鲁尼特块",
检查过在1.19.x版本的biomemakeover为官译

2023-09-02 07:52 UTC, luoxueyasha requested changes

2023-09-02 07:52 UTC, luoxueyasha commented on projects/1.19/assets/compat-makeover/compat_makeover/lang/zh_cn.json
> +  "block.compat_makeover.ancient_oak_leaf_pile": "古橡木树叶堆",
请问是`古橡树树叶堆`还是`古橡木树叶堆`？

2023-09-02 07:52 UTC, luoxueyasha commented on projects/1.19/assets/compat-makeover/compat_makeover/lang/zh_cn.json
> +  "block.compat_makeover.mesmerite_bricks": "磨制迷魂石",
可以看一下材质吗（原文有`bricks`，如果是石砖则需要改动`）

2023-09-02 20:56 UTC, Music0Kirby commented on projects/1.19/assets/compat-makeover/compat_makeover/lang/zh_cn.json
> +  "block.compat_makeover.mesmerite_bricks": "磨制迷魂石",
![mesmerite_bricks](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/56399833/c466f712-bbe1-4700-ac68-24edf2eb4de4)
是石砖（现在就去改）

2023-09-02 21:04 UTC, Music0Kirby commented on projects/1.19/assets/compat-makeover/compat_makeover/lang/zh_cn.json
> +  "block.compat_makeover.ancient_oak_leaf_pile": "古橡木树叶堆",
已修正为`古橡木树叶堆`

2023-10-27 13:57 UTC, luoxueyasha reviewed
基本没什么问题了

2023-10-27 13:57 UTC, luoxueyasha commented on projects/1.19/assets/compat-makeover/compat_makeover/lang/zh_cn.json
> +  "block.compat_makeover.fairy_ring_mushroom_brick": "仙环菇砖",
贴图？
现实中的fairy ring mushroom的学名为`Marasmius oreades`（硬柄小皮伞），请根据游戏内容确定是否需要改

2023-10-27 14:07 UTC, Music0Kirby commented on projects/1.19/assets/compat-makeover/compat_makeover/lang/zh_cn.json
> +  "block.compat_makeover.fairy_ring_mushroom_brick": "仙环菇砖",
Fairy ring mushroom的译名取自：[Habitat汉化提交](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/2029)
[Habitat / Bloom and Gloom](https://www.mcmod.cn/class/7701.html)
这个蘑菇是另一个模组的联动内容所以故用了那边的翻译
贴图：
![fairy_ring_mushroom_brick](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/56399833/6f1d0ef5-7110-4ef9-be1a-8a46e514a436)
![fairy_ring_mushroom_stem_brick](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/56399833/e2a56036-a2c2-459b-9173-85584e90ba18)

2023-10-29 03:04 UTC, luoxueyasha approved these changes

2023-10-29 18:39 UTC, merged

2023-10-30 00:28 UTC, ChuijkYahus commented
官译这段时间也更新了
不过后面再改吧