Arcane Archives 翻译补充1.12.2
CFPAOrg/Minecraft-Mod-Language-Package pull request #3435
Opened 2023-07-01 15:04 UTC by meishibiezb

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-07-02 11:18 UTC, mamaruo requested changes
关于空格问题需要全文通查
我不很了解魔法模组，术语翻译不能作参考

2023-07-02 11:18 UTC, mamaruo commented on projects/1.12.2/assets/arcane-archives/arcanearchives/xml/tome.xml
> +	            如果你不能说服村民们自愿分开，消除孩子的记忆然后带走他。不用担心他会反抗或者是精神受到伤害，因为他的记忆会被消除然后以更方便的记忆替换之。这是万不得已的方法，多余的举动会使你在招聘部的地位严重受损。            </p><space height="4"/>
消除的应该是村民的记忆吧。

2023-07-02 11:18 UTC, mamaruo commented on projects/1.12.2/assets/arcane-archives/arcanearchives/xml/tome.xml
> +                永恒大学让所有学徒都有机会接触到这些简单符咒。在这个符咒的嘴里的是一个在很多方面都与下界传送门类似的传送门，只不过它是单向的。
真的是“嘴”？

2023-07-02 11:18 UTC, mamaruo commented on projects/1.12.2/assets/arcane-archives/arcanearchives/xml/tome.xml
> +                如果你发现你需要处理 <span bold="true">异常</span> 大量的杂物，你也可以用你老师的信，在其他两位教员的允许下申请使用一个包含吞噬符咒，直径约80块的房间。
```suggestion
                如果你发现你需要处理的杂物数量<span bold="true">庞大</span>，你可以凭你老师的信，在其他两位老师的许可下，申请使用一个包含吞噬符咒，直径约80格的房间。
```
block 作单位翻译成格或“个方块”。master 翻译成老师吗？

2023-07-05 15:32 UTC, meishibiezb commented
本当にすみません😔



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月2日(周日) 晚上7:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CFPAOrg/Minecraft-Mod-Language-Package] Arcane Archives 翻译补充1.12.2 (PR #3435)




 
@mamaruo requested changes on this pull request.
 
关于空格问题需要全文通查
 我不很了解魔法模组，术语翻译不能作参考

 
In projects/1.12.2/assets/arcane-archives/arcanearchives/xml/tome.xml:
 &gt; @@ -678,7 +678,7 @@                  <stack item="arcanearchives:devouring_charm"/&gt; 可选升级，加装<link ref="Items:DevouringCharm"&gt;吞噬符咒</link&gt;能够销毁超出辉耀宝盒容量的物品。              </p&gt;              <p&gt; -            <stack item="arcanearchives:radiant_key"/&gt; If used as an upgrade, a <link ref="Items:RadiantKey"&gt;Radiant Key</link&gt; locks the type of item in the trove. Once the trove reaches 0 stored items, it will still reserve its storage for the type of item it once held. +                <stack item="arcearchives:radiat_key"/&gt;如果用作升级，<link ref="Items:RadiatKey"&gt;radiant key</link&gt;将锁定宝藏中的项目类型。一旦储存物归零，它仍将为其所持有的项目类型保留存储空间。              
为什么会有多出来的空格
 radiant key 其中的 radiant key 需要翻译。 
用作升级时，radiant key会锁定trove中的物品类型。即使trove中存有的物品数为零，它也将保持锁定其之前存有的物品类型。
 
 
In projects/1.12.2/assets/arcane-archives/arcanearchives/xml/tome.xml:
 &gt;              </p&gt;<space height="4"/&gt;              <p bold="true"&gt; -                The Apprentice's Panoply +                学生全体  
全体放前面，全体学生
 1365行用的是学徒，考一为一种说法
 
 
In projects/1.12.2/assets/arcane-archives/arcanearchives/xml/tome.xml:
 &gt;              </p&gt;              <horizontal_rule/&gt;              <p&gt; -                <stack item="arcanearchives:gemcutters_table" /&gt; Radiant Keys can be crafted on a <link ref="Blocks:GemCuttersTable"&gt;Gem Cutter's Table</link&gt;. +                <stack item="arcanearchives:gemcutters_table" /&gt; 辉之钥可以用 <link ref="Blocks:GemCuttersTable"&gt;宝石切割台</link&gt;制作。  
多了个空格
 
 
In projects/1.12.2/assets/arcane-archives/arcanearchives/xml/tome.xml:
 &gt;              </p&gt;              <p&gt; -                ……Form letter given to all Apprentices of the Eternal University +                ……至永恒大学全体学生的一封信  
是否是“节选自给永恒大学全体学生的一封信”？
 
 
In projects/1.12.2/assets/arcane-archives/arcanearchives/xml/tome.xml:
 &gt; @@ -1079,22 +1079,22 @@                  预言家们相信有一个带有魔法天赋的孩子居住在一个名叫 Brightmeadow 的村庄里。负责招聘部的你有责任把这个孩子带到永恒大学进行测验评估。              </p&gt;<space height="4"/&gt;              <p italics="true"&gt; -                According to their divinations, the child has begun performing magical workings beyond the scope of the hedge magic that the peasantry usually practices. See if you can convince the child to show you its workings. Feign interest, no matter how primitive its spellcraft is. +                根据他们的占卜，这个孩子已经看是表现出了超出农民们常用的结界魔法范围的魔法能力。试着说服这个孩子向你展示他的魔法能力。不管他的法术多么简陋，你都要假装感兴趣。              
长句还有改善空间。
 
他们的占卜显示，这个孩子魔艺高超，他所施展的魔法，已超出一般农民能施展的结界魔法的范畴。
 
magical workings、hedge magic 我乱翻的，我不知道术语。
 
 
In projects/1.12.2/assets/arcane-archives/arcanearchives/xml/tome.xml:
 &gt;              </p&gt;<space height="4"/&gt;              <p italics="true"&gt; -                If you cannot convince the village to willingly part，eliminate the child from their memories and take it anyway. Do not worry about resistance or traumatizing it，as its memories will be eliminated and replaced with more convenient ones. This method is to be considered a last resort，the additional work it will incur will significantly damage your standing with the Ministry of Recruitment. +	            如果你不能说服村民们自愿分开，消除孩子的记忆然后带走他。不用担心他会反抗或者是精神受到伤害，因为他的记忆会被消除然后以更方便的记忆替换之。这是万不得已的方法，多余的举动会使你在招聘部的地位严重受损。            </p&gt;<space height="4"/&gt;  
消除的应该是村民的记忆吧。
 
 
In projects/1.12.2/assets/arcane-archives/arcanearchives/xml/tome.xml:
 &gt; @@ -1362,25 +1362,25 @@                  <title&gt;吞噬符咒</title&gt;              </page_title_shorter&gt;              <p italics="true"&gt; -                The Eternal University makes these simple charms available to all apprentices. Inside the mouth of the charm is a portal similar in many ways to a portal to the Nether，save that the connection is one-way. +                永恒大学让所有学徒都有机会接触到这些简单符咒。在这个符咒的嘴里的是一个在很多方面都与下界传送门类似的传送门，只不过它是单向的。  
真的是“嘴”？
 
 
In projects/1.12.2/assets/arcane-archives/arcanearchives/xml/tome.xml:
 &gt;              </p&gt;<space height="4"/&gt;              <p italics="true"&gt; -                If you find yourself with a case of an <span bold="true"&gt;exceptionally</span&gt; large mess，a room containing a 吞噬符咒 approximately eighty blocks in diameter can be signed out with a letter from your Master and the permission of at least two other Masters. +                如果你发现你需要处理 <span bold="true"&gt;异常</span&gt; 大量的杂物，你也可以用你老师的信，在其他两位教员的允许下申请使用一个包含吞噬符咒，直径约80块的房间。  ⬇️ Suggested change -                如果你发现你需要处理 <span bold="true"&gt;异常</span&gt; 大量的杂物，你也可以用你老师的信，在其他两位教员的允许下申请使用一个包含吞噬符咒，直径约80块的房间。 +                如果你发现你需要处理的杂物数量<span bold="true"&gt;庞大</span&gt;，你可以凭你老师的信，在其他两位老师的许可下，申请使用一个包含吞噬符咒，直径约80格的房间。  
block 作单位翻译成格或“个方块”。master 翻译成老师吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-07-06 04:29 UTC, mamaruo commented
> 本当にすみません

咋了。不用道歉。

如果你认为我的翻译可行，那么就照做；如果不行，你也可以提出异议；如果是我提出疑问的评论，正常回复即可。

2023-07-14 19:44 UTC, mamaruo commented
@meishibiezb 请回应相关审阅，否则 PR 将被接管或关闭。若遇到技术上的困难请提出。

2023-07-21 15:50 UTC, dovisutu commented
- 7+7时限进入第二阶段。从该评论发出的时间开始计时。<br>如仍希望在此提交上工作，应当即时做出反馈，或说明无法及时反馈的理由。

ping @meishibiezb

2023-07-21 16:14 UTC, meishibiezb commented
哦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月21日(周五) 晚上11:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CFPAOrg/Minecraft-Mod-Language-Package] Arcane Archives 翻译补充1.12.2 (PR #3435)




  
7+7时限进入第二阶段。从该评论发出的时间开始计时。
如仍希望在此提交上工作，应当即时做出反馈，或说明无法及时反馈的理由。
  
ping @meishibiezb
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2023-07-30 10:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3435) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3435) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3435) it.</sub>

2023-08-01 09:43 UTC, Cactusstudent commented
由于7+7，您的PR即将被关闭。若仍想维护此PR，请Reopen或重开新PR

2023-08-01 09:43 UTC, closed without merging