Relics 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3436
Opened 2023-07-02 02:30 UTC by 2818554750

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2023-07-08 13:05 UTC, nageih commented on projects/1.19/assets/relics/relics/lang/zh_cn.json
> +  "tooltip.relics.infinity_ham.leveling": "每从 “再生 ”能力中消耗 1 点充能，+1 XP。",
```suggestion
  "tooltip.relics.infinity_ham.leveling": "每从 “再生 ”能力中消耗1点充能，+1XP。",

```

2023-07-27 15:36 UTC, Cactusstudent requested changes
问题很大，包括但不限于全半角符号的使用，语序，句子是否通顺，建议优先自查。参照：https://cfpa.site/TransRules/

2023-07-30 10:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3436) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3436) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Cactusstudent<br/>:x: 2818554750<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3436) it.</sub>

2023-08-04 07:01 UTC, Cactusstudent commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

@2818554750

2023-08-10 03:31 UTC, Cactusstudent commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@2818554750

2023-08-19 21:03 UTC, closed without merging