Thermal: Extra 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3437
Opened 2023-07-02 04:02 UTC by fgt1t5y

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

升级组件的翻译全部参照mc百科...

~~由于对GitHub的不熟练，把之前的pr不小心关了，现在再开一次~~

2023-07-02 12:03 UTC, Slow-Witted-Fish commented
旧pr#3430

2023-07-16 13:46 UTC, fgt1t5y commented
怎么这么久还没合并...

2023-07-16 13:57 UTC, Slow-Witted-Fish commented
> 怎么这么久还没合并...

因为没有人审嘛，几个月不合并成正常现象了

2023-07-27 15:25 UTC, Cactusstudent requested changes
部分生造词翻译还需考证

2023-07-27 15:25 UTC, Cactusstudent commented on projects/1.19/assets/thermal_extra/thermal_extra/lang/zh_cn.json
> +  "item.thermal_extra.av_item_filter_augment": "机器物品过滤升级 Plus",
```suggestion
  "item.thermal_extra.av_item_filter_augment": "高级机器物品过滤升级,
```
随便翻的，没看游戏内情况

2023-07-27 23:14 UTC, fgt1t5y commented
> 部分生造词翻译还需考证

合理，就用你建议的吧

2023-07-28 11:15 UTC, Slow-Witted-Fish requested changes
处分+1 @Cactusstudent 
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/101028476/2e526229-4600-42a9-ae7a-2aae0b677de8)

2023-07-28 11:15 UTC, Slow-Witted-Fish commented on projects/1.19/assets/thermal_extra/thermal_extra/lang/zh_cn.json
> +  "item.thermal_extra.av_item_filter_augment": "高级机器物品过滤升级,
```suggestion
  "item.thermal_extra.av_item_filter_augment": "高级机器物品过滤升级",
```

2023-07-30 10:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3437) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3437) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3437) it.</sub>

2023-08-04 06:59 UTC, Cactusstudent commented
> 处分+1 @Cactusstudent ![image](https://user-images.githubusercontent.com/101028476/256806475-2e526229-4600-42a9-ae7a-2aae0b677de8.png)

我的问题，我道歉

2023-08-10 06:31 UTC, fgt1t5y commented
还不合？人都死了？

2023-08-10 06:37 UTC, Cactusstudent commented
合并与否取决于该PR是否有一个Approval审查，没有则无法合并。请耐心等待，非常抱歉，另外在交谈中请注意[礼仪](https://share.weiyun.com/LRvx1omf)

2023-08-10 06:38 UTC, fgt1t5y commented
> 合并与否取决于该PR是否有一个Approval审查，没有则无法合并。请耐心等待，非常抱歉，另外在交谈中请注意[礼仪](https://share.weiyun.com/LRvx1omf)

你点一下“Approval”不就完事了？

2023-08-10 06:42 UTC, CoalGlage commented
我知道你很急，但你先别急（

2023-08-10 06:46 UTC, Cactusstudent commented
非常抱歉，目前的译文中仍旧存在问题，无法给出Approval审查，具体问题出在多个生造词的确切翻译中，我们试图找到一种更贴切原文的翻译方法。对于您的翻译恕我不敢完全苟同。以及对您的翻译中存在部分我无法完全参透的部分我感到非常惭愧。我将不再对您的翻译进行审阅，鄙人自认为审阅质量不高，恳请您给予指点，或是另寻高人指点翻译。非常抱歉浪费了您的时间。

2023-08-10 06:58 UTC, dovisutu reviewed
我对这模组不太了解，所以不能给出一个确定的审核；但是看起来结构上没有什么问题。生造词译名上的考量就只能交予其他审核了，如果也没有问题，那就可以approve了。

（对审核周期过长表示歉意，但是我们确实审核人手不够了。）

2023-08-10 06:58 UTC, fgt1t5y commented
> 非常抱歉，目前的译文中仍旧存在问题，无法给出Approval审查，具体问题出在多个生造词的确切翻译中，我们试图找到一种更贴切原文的翻译方法。对于您的翻译恕我不敢完全苟同。以及对您的翻译中存在部分我无法完全参透的部分我感到非常惭愧。我将不再对您的翻译进行审阅，鄙人自认为审阅质量不高，恳请您给予指点，或是另寻高人指点翻译。非常抱歉浪费了您的时间。

不是 针对我？ 那些升级组件的翻译都是参照mcmod的 你不服mcmod的资料？ 那些生造词我也是根据它的合成配方得出的恰当的表达，你进游戏看了配方吗？没有吧。“Dragonsteel”翻译成“龙钢”哪错了？“Soul Infused”翻译成“灵魂灌注哪错了”哪错了？ 其他模组这么翻译你就Approval，我就不行？

2023-08-10 07:00 UTC, fgt1t5y commented
> 我对这模组不太了解，所以不能给出一个确定的审核；但是看起来结构上没有什么问题。生造词译名上的考量就只能交予其他审核了，如果也没有问题，那就可以approve了；如果有问题，那可能还要继续修改。
> 
> （对审核周期过长表示歉意，但是我们确实审核人手不够了。）

哎 抱歉 我性子也急

2023-08-10 07:07 UTC, Cactusstudent commented
我这里指的是“部分生造词”，例如`twinite`和`shellite`，这两者的翻译确实需要进行讨论，译作粉钢与潜影合金确实有些许不合适。
另外，CFPA的审阅者不存在无端针对某位译者的情况，如果确实从我的话语之中您读出了哪怕一丝的针对，我在这里诚挚的向您道歉
非常对不起！我的问题

2023-08-10 07:14 UTC, fgt1t5y commented
> 我这里指的是“部分生造词”，例如`twinite`和`shellite`，这两者的翻译确实需要进行讨论，译作粉钢与潜影合金确实有些许不合适。 另外，CFPA的审阅者不存在无端针对某位译者的情况，如果确实从我的话语之中您读出了哪怕一丝的针对，我在这里诚挚的向您道歉 非常对不起！我的问题

潜影合金(Shellite)的配方如下图:
![图片](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/20389033/68a01850-24b4-4c89-bdfc-ed3fd75959fa)
使用潜影壳、磷灰石粉与青铜粉合成，我认为翻译成潜影（成品的主要组成物质）合金（与其他物质一起合成）挺恰当的。

至于粉钢 我确实得想个更好的翻译...

2023-08-10 09:47 UTC, Cactusstudent commented
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/97865546/9a72852b-d47f-41c8-bb7a-755508fba672)

2023-08-10 09:57 UTC, fgt1t5y commented
> ![image](https://user-images.githubusercontent.com/97865546/259699310-9a72852b-d47f-41c8-bb7a-755508fba672.png)

潜影合金可以是吧？那twinite该怎么改，twin就没有恰当的翻译

2023-08-10 10:21 UTC, fgt1t5y commented
@Cactusstudent “粉钢”改成了“双子物质”你看怎么样

2023-08-10 10:24 UTC, Cactusstudent commented
我看可以，不过物质/钢/合金可以再斟酌

2023-08-10 10:38 UTC, fgt1t5y commented
> 我看可以，不过物质/钢/合金可以再斟酌

我又进游戏看了下配方 它是由紫水晶尘、磷灰石粉和末影粉合成的，三种原料都不是金属，所以我认为“合金”和“钢”就不恰当了，这三者“物质”最恰当了吧（

2023-08-10 10:40 UTC, Cactusstudent commented
> 我又进游戏看了下配方 它是由紫水晶尘、磷灰石粉和末影粉合成的，三种原料都不是金属，所以我认为“合金”和“钢”就不恰当了，这三者“物质”最恰当了吧（

这里不是原版配方，原版配方是：紫水晶碎片，磷灰石，末影锭

2023-08-10 10:42 UTC, fgt1t5y commented
> > 我又进游戏看了下配方 它是由紫水晶尘、磷灰石粉和末影粉合成的，三种原料都不是金属，所以我认为“合金”和“钢”就不恰当了，这三者“物质”最恰当了吧（
> 
> 这里不是原版配方，原版配方是：紫水晶碎片，磷灰石，末影锭

确实我看的是尘的配方... 不过我后半句没错吧？

2023-08-10 10:45 UTC, Cactusstudent commented
物质也可，考虑到-ite是金属的后缀，一般都是这么整的，不过如果不太想改的话也没啥问题

2023-08-10 10:58 UTC, dovisutu commented
> 考虑到-ite是金属的后缀

矿物都叫-ite吧，不一定是金属矿（

2023-08-10 11:24 UTC, fgt1t5y commented
> 物质也可，考虑到-ite是金属的后缀，一般都是这么整的，不过如果不太想改的话也没啥问题

好 没其他问题就决定merge了吧

2023-08-10 11:55 UTC, fgt1t5y commented
> 我对这模组不太了解，所以不能给出一个确定的审核；但是看起来结构上没有什么问题。生造词译名上的考量就只能交予其他审核了，如果也没有问题，那就可以approve了；如果有问题，那可能还要继续修改。
> 
> （对审核周期过长表示歉意，但是我们确实审核人手不够了。）

没人手不会招人？我看readme连个贡献者群都没有，是不是要贡献一辈子翻译才能成为collaborator？

2023-08-10 12:10 UTC, Cactusstudent approved these changes

2023-08-10 12:12 UTC, Cactusstudent commented
> 连个贡献者群都没有

https://cfpa.site/joinus.html#:~:text=%E9%80%9A%E8%BF%87-,QQ,-%E5%8A%A0%E5%85%A5%E6%88%91%E4%BB%AC

2023-08-10 12:15 UTC, fgt1t5y commented
> > 连个贡献者群都没有
> 
> https://cfpa.site/joinus.html#:~:text=%E9%80%9A%E8%BF%87-,QQ,-%E5%8A%A0%E5%85%A5%E6%88%91%E4%BB%AC

还是写在readme更醒目吧

2023-08-10 12:32 UTC, dovisutu commented
* 审核通过的提交（标上“即将合并”的）需要等待一天；如果没有人提出改动项目，即可合并。这一条主要是避免有漏掉的问题。
不过，如果比较紧急（比如修复文件格式），经过说明，也可以提前合并。

不出意外，明天应该就可以合并了。
（如果没问题的话，我明天早上就过来合吧。）

再次为审核和反馈过程的不便表示歉意。

2023-08-10 12:36 UTC, fgt1t5y commented
> * 审核通过的提交（标上“即将合并”的）需要等待一天；如果没有人提出改动项目，即可合并。这一条主要是避免有漏掉的问题。
>       不过，如果比较紧急（比如修复文件格式），经过说明，也可以提前合并。
> 
> 
> 不出意外，明天应该就可以合并了。 （如果没问题的话，我明天早上就过来合吧。）
> 
> 再次为审核和反馈过程的不便表示歉意。

没事：）

2023-08-11 00:58 UTC, merged