将 Advanced NBT Tooltips 翻译移植到 1.19
CFPAOrg/Minecraft-Mod-Language-Package pull request #3445
Opened 2023-07-03 16:34 UTC by Slow-Witted-Fish

- [ ] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-07-04 17:49 UTC, mamaruo requested changes
中英没对齐

2023-07-04 17:49 UTC, mamaruo commented on projects/1.19/assets/advanced-nbt-tooltips/advancednbttooltips/lang/zh_cn.json
> +  "text.advancednbttooltip.tooltip.book.pages": "页数：%页",
```suggestion
  "text.advancednbttooltip.tooltip.book.pages": "页数：%s页",
```

2023-07-07 06:25 UTC, MikhailTapio requested changes

2023-07-07 06:25 UTC, MikhailTapio commented on projects/1.19/assets/advanced-nbt-tooltips/advancednbttooltips/lang/zh_cn.json
> +  "text.advancednbttooltip.toggle.axolotl": "显示美西螈桶的颜色",
```suggestion
  "text.advancednbttooltip.toggle.axolotl": "显示桶内美西螈的变种",
```

2023-07-07 06:25 UTC, MikhailTapio commented on projects/1.19/assets/advanced-nbt-tooltips/advancednbttooltips/lang/zh_cn.json
> +  "text.autoconfig.advancednbttooltip.option.general.hideflagOverrides.overrideAttributeModifiers.@Tooltip": "无视隐藏信息标签直接显示属性修饰符信息",
```suggestion
  "text.autoconfig.advancednbttooltip.option.general.hideflagOverrides.overrideAttributeModifiers.@Tooltip": "无视隐藏信息的标签直接显示属性修饰符信息",
```

格式统一

2023-07-07 06:25 UTC, MikhailTapio commented on projects/1.19/assets/advanced-nbt-tooltips/advancednbttooltips/lang/zh_cn.json
> +  "text.autoconfig.advancednbttooltip.option.misc.showAxolotlVariant": "显示美西螈桶的颜色",
```suggestion
  "text.autoconfig.advancednbttooltip.option.misc.showAxolotlVariant": "显示桶内美西螈的变种",
```

2023-07-07 16:21 UTC, mamaruo requested changes
没细看，明天再说

2023-07-07 16:21 UTC, mamaruo commented on projects/1.19/assets/advanced-nbt-tooltips/advancednbttooltips/lang/zh_cn.json
> +  "text.advancednbttooltip.tooltip.foodstats.saturation": "饱和值：%s",
```suggestion
  "text.advancednbttooltip.tooltip.foodstats.saturation": "饱和度：%s",
```

2023-07-07 16:21 UTC, mamaruo commented on projects/1.19/assets/advanced-nbt-tooltips/advancednbttooltips/lang/zh_cn.json
> +  "text.autoconfig.advancednbttooltip.option.misc.showLightLevel.@Tooltip": "添加一行指定光源的光照等级.",
```suggestion
  "text.autoconfig.advancednbttooltip.option.misc.showLightLevel.@Tooltip": "添加一行指定光源的光照等级。",
```

2023-07-08 10:57 UTC, mamaruo commented on projects/1.19/assets/advanced-nbt-tooltips/advancednbttooltips/lang/zh_cn.json
清一下多余的键

2023-07-08 10:57 UTC, mamaruo commented on projects/1.19/assets/advanced-nbt-tooltips/advancednbttooltips/lang/zh_cn.json
> +  "text.advancednbttooltip.tooltip.custommodeldata": "自定义模型：",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

这是个关键字吧 https://minecraft.fandom.com/zh/wiki/%E6%A8%A1%E5%9E%8B#:~:text=%E5%86%85%E7%9A%84%C2%A0tag.-,CustomModelData,-%E3%80%82%E8%BF%99%E4%B8%AA%E6%95%B0%E5%AD%97%E5%9C%A8

原文：**CustomModelData: **
```suggestion
  "text.advancednbttooltip.tooltip.custommodeldata": "CustomModelData：",
```

2023-07-09 02:55 UTC, Slow-Witted-Fish commented on projects/1.19/assets/advanced-nbt-tooltips/advancednbttooltips/lang/zh_cn.json
> +  "text.autoconfig.advancednbttooltip.option.misc.showLightLevel.@Tooltip": "添加一行指定光源的光照等级.",
修复于 b8a7b30

2023-07-09 04:06 UTC, mamaruo approved these changes

2023-07-09 08:10 UTC, MikhailTapio approved these changes

2023-07-09 15:13 UTC, merged