untamedwilds 模组 1.16.5 1.18.2 1.19.2 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3448
Opened 2023-07-04 02:33 UTC by sea-turtle0

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-07-04 02:36 UTC, sea-turtle0 commented
1.18.2语言文件与1.19.2语言文件文本一致

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.large_snake_anaconda": "绿水蚺",
```suggestion
  "entity.untamedwilds.large_snake_anaconda": "森蚺",
```
[百度](https://baike.baidu.com/item/%E7%BB%BF%E6%A3%AE%E8%9A%BA/793681?fr=ge_ala)，iNaturalist和维基百科将其直接称作森蚺

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.monitor_bengal": "孟加拉巨蜥 ",
```suggestion
  "entity.untamedwilds.monitor_bengal": "孟加拉巨蜥",
```

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.monitor_desert": "沙漠巨蜥",
```suggestion
  "entity.untamedwilds.monitor_desert": "荒漠巨蜥",
```
```suggestion
  "entity.untamedwilds.monitor_desert": "浅灰巨蜥",
```
维基百科和百度称呼是荒漠巨蜥，iNaturalist是浅灰巨蜥

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.monitor_komodo": "科莫多巨蜥 ",
```suggestion
  "entity.untamedwilds.monitor_komodo": "科莫多巨蜥",
```

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.monitor_rock": "非洲巨蜥",
```suggestion
  "entity.untamedwilds.monitor_rock": "白喉巨蜥",
```

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.monitor_water": "圆鼻巨蜥 ",
```suggestion
  "entity.untamedwilds.monitor_water": "圆鼻巨蜥",
```

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "item.untamedwilds.ownership_deed_desc_6": "由%签署s",
```suggestion
  "item.untamedwilds.ownership_deed_desc_6": "由%s签署",
```

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "item.untamedwilds.hide_bigcat_leopard": "金钱豹皮",
上面花豹如果改这里也要改

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.newt_crested": "冠北螈",
```suggestion
  "entity.untamedwilds.newt_crested": "大冠蝾螈",
```

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.newt_ribbed": "西班牙肋突螈",
```suggestion
  "entity.untamedwilds.newt_ribbed": "欧非肋突螈",
```

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.newt_tiger": "虎纹蝾螈",
```suggestion
  "entity.untamedwilds.newt_tiger": "虎纹钝口螈",
```

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.anemone_sand": "沙海葵",
这个名称好像比较泛
能查到的有`念珠海葵`（*Heteractis aurora*）和`夏威夷异辐海葵`（*Heteractis malu*）两种

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.flora_orchid_red": "绯红色树兰花",
```suggestion
  "block.untamedwilds.flora_orchid_magenta": "品红色凤兰",
  "block.untamedwilds.flora_orchid_pink": "粉红色凤兰",
  "block.untamedwilds.flora_orchid_purple": "紫色凤兰",
  "block.untamedwilds.flora_orchid_red": "绯红色凤兰",
```
https://en.wikipedia.org/wiki/Cymbidium_dayanum
http://www.iplant.cn/info/Cymbidium%20dayanum
https://www.inaturalist.org/taxa/493638-Cymbidium-dayanum

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.flora_common_reed": "普通芦苇",
```suggestion
  "block.untamedwilds.flora_common_reed": "芦苇",
```

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.flora_amazon_sword": "刺果泽泻",
```suggestion
  "block.untamedwilds.flora_amazon_sword": "肋果慈姑",
```
https://en.wikipedia.org/wiki/Echinodorus
http://www.iplant.cn/info/Echinodorus

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.flora_eelgrass": "鳗草",
```suggestion
  "block.untamedwilds.flora_eelgrass": "大叶藻",
```
```suggestion
  "block.untamedwilds.flora_eelgrass": "苦草",
```
https://en.wikipedia.org/wiki/Eelgrass
http://www.iplant.cn/info/Zostera
http://www.iplant.cn/info/Vallisneria

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.flora_bush_creosote": "三齿拉雷亚灌木",
```suggestion
  "block.untamedwilds.flora_bush_creosote": "三齿团香木",
```
http://www.iplant.cn/info/Larrea%20tridentata

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.flora_titan_arum": "泰坦魔芋",
```suggestion
  "block.untamedwilds.flora_titan_arum": "巨魔芋",
```
http://www.iplant.cn/info/Amorphophallus%20titanum

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.flora_zimbabwe_aloe": "津巴布韦芦荟",
```suggestion
  "block.untamedwilds.flora_zimbabwe_aloe": "高芦荟",
```
http://www.iplant.cn/info/Aloe%20excelsa

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "item.untamedwilds.flora_water_hyacinth_item": "凤眼蓝",
```suggestion
  "block.untamedwilds.flora_water_hyacinth": "凤眼莲",
  "item.untamedwilds.flora_water_hyacinth_item": "凤眼莲",
```
http://www.iplant.cn/info/Eichhornia%20crassipes

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.flora_junegrass": "草地早熟禾",
植物智里叫这个`𫈰草`，也有直接写`洽草`的
http://www.iplant.cn/info/Koeleria

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.flora_canola": "蓖麻 ",
```suggestion
  "block.untamedwilds.flora_canola": "油菜",
```
大概是产菜籽油的作物？

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.block_pearl": "珍珠快",
```suggestion
  "block.untamedwilds.block_pearl": "珍珠块",
```

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.block_lard": "油脂块",
```suggestion
  "block.untamedwilds.block_lard": "猪油块",
```
看实际表现

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.carpet_bigcat_leopard": "花豹皮地毯",
这里怎么已经是花豹了（）

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.tarantula_cobalt": "泰国金属蓝",
```suggestion
  "entity.untamedwilds.tarantula_cobalt": "金属蓝蛛",
```
https://baike.baidu.com/item/%E9%87%91%E5%B1%9E%E8%93%9D%E8%9B%9B/2250000?fr=ge_ala

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.tarantula_regalis": "印度华丽雨林蜘蛛",
```suggestion
  "item.untamedwilds.bottle_tarantula_regalis": "瓶装印度华丽雨林蛛",
  "entity.untamedwilds.tarantula_regalis": "印度华丽雨林蛛",
```

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.tarantula_rose": "智利红玫瑰蜘蛛",
也有叫`智利火玫瑰蛛`的

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.butterfly_birdwing": "亚历山大鸟翼凤蝶",
有`亚历山德拉鸟翼凤蝶` `亚历山大女皇鸟翼凤蝶`好几种叫法
现在这个没啥问题（）

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.butterfly_cabbage": "菜白蝶",
```suggestion
  "item.untamedwilds.bottle_butterfly_cabbage": "瓶装菜粉蝶",
  "entity.untamedwilds.butterfly_cabbage": "菜粉蝶",
```

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.butterfly_malachite": "孔雀石蝴蝶",
```suggestion
  "item.untamedwilds.bottle_butterfly_malachite": "瓶装绿帘蛱蝶",
  "entity.untamedwilds.butterfly_malachite": "绿帘蛱蝶",
```
https://www.inaturalist.org/taxa/50336-Siproeta-stelenes
不过也有`孔雀石蝶`的称呼

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.butterfly_orange_tip": "橙尖粉蝶",
```suggestion
  "item.untamedwilds.bottle_butterfly_orange_tip": "瓶装红襟粉蝶",
  "entity.untamedwilds.butterfly_orange_tip": "红襟粉蝶",
```

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.butterfly_peacock": "孔雀蝴蝶",
```suggestion
  "item.untamedwilds.bottle_butterfly_peacock": "瓶装孔雀蛱蝶",
  "entity.untamedwilds.butterfly_peacock": "孔雀蛱蝶",
```

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.butterfly_red_admiral": "大西洋赤蛱蝶",
```suggestion
  "item.untamedwilds.bottle_butterfly_red_admiral": "瓶装优红蛱蝶",
  "entity.untamedwilds.butterfly_red_admiral": "优红蛱蝶",
```

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.butterfly_tiger_swallowtail": "东方虎凤蝶 ",
```suggestion
  "item.untamedwilds.bottle_butterfly_tiger_swallowtail": "瓶装东方虎凤蝶",
  "entity.untamedwilds.butterfly_tiger_swallowtail": "东方虎凤蝶",
```

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "advancements.untamedwilds.clam_digger.description": "用铲子挖出一只巨大的砗磲",
```suggestion
  "advancements.untamedwilds.clam_digger.description": "用锹挖出一只巨大的砗磲",
```

2023-07-04 17:54 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "tetra.variant.single_socket/pristine_pearl.description": "一颗宝石镶嵌在剑刃与剑柄相接的位置。宝石已经附魔，为所有者提供魔法加持。\n\n这颗宝石是原始品质，提供比低等宝石更好的效果。"
```suggestion
  "tetra.variant.sword_socket/pearl": "镶嵌[§3珍珠§r]",
  "tetra.variant.sword_socket/pristine_pearl": "镶嵌[§3珍珠+§r]",
  "tetra.variant.sword_socket/pristine_pearl.description": "一颗宝石，被装进剑刃与剑柄的连接处。这颗宝石附有魔咒，会为持有者提供魔法增益\n \n这颗宝石质地无瑕，能提供更好的效果",
  "tetra.variant.double_socket/pearl": "镶嵌[§3珍珠§r]",
  "tetra.variant.double_socket/pristine_pearl": "镶嵌[§3珍珠+§r]",
  "tetra.variant.double_socket/pristine_pearl.description": "一颗宝石，被装进工具的顶端。这颗宝石附有魔咒，会为持有者提供魔法增益\n \n这颗宝石质地无瑕，能提供更好的效果",
  "tetra.variant.single_socket/pearl": "镶嵌[§3珍珠§r]",
  "tetra.variant.single_socket/pristine_pearl": "镶嵌[§3珍珠+§r]",
  "tetra.variant.single_socket/pristine_pearl.description": "一颗宝石，被装进头部与手柄的连接处。这颗宝石附有魔咒，会为持有者提供魔法增益\n \n这颗宝石质地无瑕，能提供更好的效果"
```
Tetra兼容，谢谢审核
#2243 #3179 #3328 #3148
多谢

2023-07-04 17:56 UTC, ChuijkYahus commented
请全文通查，辛苦

2023-07-04 17:56 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "tetra.variant.single_socket/pristine_pearl.description": "一颗宝石镶嵌在剑刃与剑柄相接的位置。宝石已经附魔，为所有者提供魔法加持。\n\n这颗宝石是原始品质，提供比低等宝石更好的效果。"
还有一个#2815 差点忘了

2023-07-05 07:44 UTC, nageih commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.rhino_indian": "印度犀牛",
学名应该是 印度犀 吧，后面的也是

2023-07-05 07:52 UTC, nageih commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.boar_red_river": "红河野猪",
学名貌似是红河猪
https://zh.wikipedia.org/zh-cn/%E7%B4%85%E6%B2%B3%E8%B1%AC

2023-07-05 12:13 UTC, sea-turtle0 commented
为辛苦查看的审核员表示感谢！！！容我稍微斟酌一下，可能不会特别快的给出答复

2023-07-05 12:13 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "tetra.variant.single_socket/pristine_pearl.description": "一颗宝石镶嵌在剑刃与剑柄相接的位置。宝石已经附魔，为所有者提供魔法加持。\n\n这颗宝石是原始品质，提供比低等宝石更好的效果。"
谢谢！tetra我实在不太熟悉，感谢捉虫

2023-07-05 12:36 UTC, sea-turtle0 commented
容我先找找为什么github反应慢以至于连github.dev都打不开的问题整好再看吧（

2023-07-05 12:54 UTC, sea-turtle0 commented
代码库好像出问题了（悲）

2023-07-05 13:32 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.hippo_common": "普通河马",
雀食没有，但英文加了"common“，不过应该还是直接叫”河马“比较好

2023-07-05 13:35 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "item.untamedwilds.food_aardvark_cucumber": "土豚黄瓜",
直译的，我也没找到中文译名，就这样吧（话说**Commit suggestion**还可以用，能修改的我先修一下吧）

2023-07-05 13:47 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.hyena_shortface": "桑氏硕鬣狗",
又查了一遍，抱歉，没查仔细，bing给的是桑氏硕鬣狗，但实际上二名法命名的桑氏硕鬣狗应该是 Pachycrocuta licenti Pei，我的我的！

2023-07-05 14:01 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.boar_peccary": "白唇西貒",
这里疑似_Tayassu_指西猯属，而peccary指西貒（？）

2023-07-05 14:02 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.boar_peccary": "白唇西貒",
这里疑似 _Tayassu_ 指西猯属，而peccary指西貒（？）

2023-07-05 14:12 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "item.untamedwilds.food_cetacean_cooked": "熟鲸肉",
感觉认为可加可不加吧，只是感觉这么读着顺口而已

2023-07-05 14:12 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "item.untamedwilds.food_cetacean_cooked": "熟鲸肉",
感觉可加可不加吧，只是感觉这么读着顺口而已

2023-07-05 14:18 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "item.untamedwilds.bucket_king_crab_spiny": "桶装刺鲎",
抱歉，译的时候未注意

2023-07-06 09:25 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.rhino_indian": "印度犀牛",
感谢

2023-07-06 09:25 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.boar_red_river": "红河野猪",
感谢，貌似是的

2023-07-06 11:39 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.butterfly_orange_tip": "橙尖粉蝶",
了解

2023-07-06 11:56 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.butterfly_tiger_swallowtail": "东方虎凤蝶 ",
东方虎凤蝶 or 北美大黄凤蝶？

2023-07-06 12:10 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.trevally_golden": "黄金鲹",
是的，头疼，不过可能无齿鲹和黄鹂无齿鲹比黄金鲹好点（？）

2023-07-06 12:13 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.triggerfish_picasso": "红海毕加索",
不过这里原文 Picasso 貌似有”毕加索“的意思（？）

2023-07-06 13:04 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.tortoise_gopher": "哥法地鼠龟",
我找到的资料大部分都是哥法地鼠龟（

2023-07-06 13:07 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.tortoise_sulcata": "苏卡达龟",
qs

2023-07-06 13:10 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.snake_coral": "德州珊瑚蛇",
抱歉，这里貌似译错了

2023-07-07 03:24 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.snake_coral_blue": "蓝长腺丽纹蛇",
确实有，不过 蓝长腺丽纹蛇 可能更贴近英文原文（？）

2023-07-07 03:29 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.large_snake_anaconda": "绿水蚺",
iNaturalist[https://www.inaturalist.org/taxa/32213-Eunectes-murinus]有叫绿水蚺的（？）
百度给出的是绿森蚺、森蚺和绿水蟒的，还有叫亚马逊森蚺的

2023-07-07 03:29 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.large_snake_anaconda": "绿水蚺",
i

2023-07-07 03:30 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.large_snake_anaconda": "绿水蚺",
iNaturalist [https://www.inaturalist.org/taxa/32213-Eunectes-murinus] 有叫绿水蚺的（？） 百度给出的是绿森蚺、森蚺和绿水蟒的，还有叫亚马逊森蚺的

2023-07-07 03:31 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.large_snake_anaconda": "绿水蚺",
iNaturalist https://www.inaturalist.org/taxa/32213-Eunectes-murinus 有叫绿水蚺的（？） 
百度给出的是绿森蚺、森蚺和绿水蟒的，还有叫亚马逊森蚺的

2023-07-07 03:33 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "entity.untamedwilds.monitor_desert": "沙漠巨蜥",
bing给出的是沙漠巨蜥/荒漠巨蜥

2023-07-07 04:11 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.anemone_sand": "沙海葵",
**斑点岸海葵** （_Oulactis muscosa_）和 **砂海葵** （_Sand anemone_）也有查到，这里的生物没给学名，查证起来非常困难T A T

2023-07-07 04:14 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.flora_orchid_red": "绯红色树兰花",
thanks

2023-07-07 04:16 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.flora_amazon_sword": "刺果泽泻",
肋果慈姑貌似只是属名，皇冠草会不会更好（

2023-07-07 04:26 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.flora_bush_creosote": "三齿拉雷亚灌木",
这里百度和inaturalist给的都是**三齿拉雷亚灌木**

2023-07-07 04:29 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.flora_bush_creosote": "三齿拉雷亚灌木",
就看你认为植物智这个算不算权威了

2023-07-07 04:29 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.flora_amazon_sword": "刺果泽泻",
应该没啥问题吧（）

2023-07-07 04:32 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.flora_junegrass": "草地早熟禾",
thanks，百度、inaturalist好像都叫 洽草

2023-07-07 04:38 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.block_pearl": "珍珠快",
感谢！

2023-07-07 04:38 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.carpet_bigcat_leopard": "花豹皮地毯",
可能大概也许是crtl+c复制错了（

2023-07-07 04:49 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.block_lard": "油脂块",
实际上应该就是油脂块，mod中合成配方为4个动物脂肪，这个动物脂肪大部分生物都会掉，应该不是单指猪油（

2023-07-07 05:14 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.flora_bush_creosote": "三齿拉雷亚灌木",
这个感觉好听一点，就它了（感觉好随便）

2023-07-08 18:01 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "advancements.untamedwilds.yee_haw.title": "驾",
```suggestion
  "advancements.untamedwilds.yee_haw.title": "咿哈！",
```
这个语气词确实难整，先留着吧

2023-07-08 18:01 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "advancements.untamedwilds.hog_wild.title": "发疯",
```suggestion
  "advancements.untamedwilds.hog_wild.title": "狂若野猪",
```

2023-07-08 23:57 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "block.untamedwilds.flora_canola": "油菜 ",
crtl+c的时候又多加了个空格（恼）

2023-07-09 00:00 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "advancements.untamedwilds.hog_wild.title": "发疯",
这个双关处理的好啊，我就没想起来（

2023-07-09 00:01 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "advancements.untamedwilds.yee_haw.title": "驾",
我第一个想到的是《牛仔很忙》里那个（

2023-07-09 00:02 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "advancements.untamedwilds.basic_baiter.title": "老兄",
qs

2023-07-09 00:16 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "item.untamedwilds.ownership_deed_desc_3": "右键此契约来高亮相关生物，右键相关生物来声明所有权",
右击生物，右键物品吧（

2023-07-09 11:27 UTC, qznfbnj commented
话说 Untamed Wilds 官方接受翻译提交吗

2023-07-10 18:15 UTC, ChuijkYahus commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "advancements.untamedwilds.basic_baiter.title": "老兄",
```suggestion
  "advancements.untamedwilds.basic_baiter.title": "以饵会友",
```
感谢 @CoalGlage 的意见

2023-07-11 02:19 UTC, sea-turtle0 commented on projects/1.18/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "advancements.untamedwilds.basic_baiter.title": "老兄",
> ```suggestion
>   "advancements.untamedwilds.basic_baiter.title": "以饵会友",
> ```
> 感谢 @CoalGlage 的意见

感谢

2023-07-11 04:40 UTC, ChuijkYahus submitted a review, later dismissed

2023-07-11 19:25 UTC, mamaruo requested changes
随便看看，晚上审的不保证质量

2023-07-11 19:29 UTC, ChuijkYahus commented on projects/1.16/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "tetra.variant.single_socket/pristine_pearl.description": "一颗宝石，被装进头部与手柄的连接处。这颗宝石附有魔咒，会为持有者提供魔法增益\n \n这颗宝石质地无瑕，能提供更好的效果"
这里算是按Tetra那边的翻译来的，看Tetra原文的话三种（剑、双头工具、单头工具）用的原文确实不同
这边相同就随便了吧

2023-07-12 14:45 UTC, sea-turtle0 commented on projects/1.16/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "untamedwilds.subtitles.bear.baby.cry": "熊崽：尖叫",
感谢，熊崽是在叫

2023-07-12 16:23 UTC, mamaruo commented on projects/1.16/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "tetra.variant.single_socket/pristine_pearl.description": "一颗宝石，被装进头部与手柄的连接处。这颗宝石附有魔咒，会为持有者提供魔法增益\n \n这颗宝石质地无瑕，能提供更好的效果"
@sea-turtle0 你怎么看

2023-07-12 22:46 UTC, sea-turtle0 commented on projects/1.16/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "tetra.variant.single_socket/pristine_pearl.description": "一颗宝石，被装进头部与手柄的连接处。这颗宝石附有魔咒，会为持有者提供魔法增益\n \n这颗宝石质地无瑕，能提供更好的效果"
> @sea-turtle0 你怎么看

我没玩过tetra，我也不是特清楚（

2023-07-12 22:48 UTC, sea-turtle0 commented on projects/1.16/assets/untamedwilds/untamedwilds/lang/zh_cn.json
> +  "tetra.variant.single_socket/pristine_pearl.description": "一颗宝石，被装进头部与手柄的连接处。这颗宝石附有魔咒，会为持有者提供魔法增益\n \n这颗宝石质地无瑕，能提供更好的效果"
跟现有翻译契合就行

2023-07-14 00:08 UTC, mamaruo approved these changes

2023-07-14 19:38 UTC, mamaruo commented
我对比了“#2342”和“#3448”的翻译，结果如下：

### 两者皆有且中文有差异

<details><summary>点击展开/收起</summary>
<p>

| **键** | **英文** | **#2342** | **#3448** |
|---|---|---|---|
| entity.untamedwilds.command.0 | This mob is now Wandering | 生物行为：徘徊 | 这个生物正在闲逛 |
| entity.untamedwilds.command.1 | This mob is now Protecting you | 生物行为：护主 | 这个生物正在保护你 |
| entity.untamedwilds.command.2 | This mob is now Sitting | 生物行为：坐下 | 这个生物正坐着 |
| entity.untamedwilds.command.3 | This mob is now Guarding the area | 生物行为：保护附近区域 | 这个生物正在守护这片领地 |
| entity.untamedwilds.hippo_common | Common Hippo | 普通河马 | 河马 |
| entity.untamedwilds.bison_plains | Plains Bison | 平原野牛 | 美洲平原野牛 |
| untamedwilds.subtitles.bison.ambient | Bison ruts | Bison ruts | 野牛：发情 |
| untamedwilds.subtitles.aardvark.ambient | Aardvark grunts | 土豚：发出呼噜声 | 土豚：呼噜 |
| entity.untamedwilds.hyena_shortface | Giant Short\-Faced Hyena | 巨鬣狗 | 短吻硕鬣狗 |
| untamedwilds.subtitles.hyena.ambient | Hyena whoops | 鬣狗：叫喊 | 鬣狗：吼叫 |
| entity.untamedwilds.boar_eurasian | Wild Boar | 野猪 | 欧亚野猪 |
| entity.untamedwilds.boar_peccary | Peccary | 矛牙野猪 | 白唇西貒 |
| entity.untamedwilds.boar_red_river | Red River Hog | 红河野猪 | 红河猪 |
| untamedwilds.subtitles.boar.ambient | Boar grunts | 野猪：发出呼噜声 | 野猪：呼噜 |
| entity.untamedwilds.camel_bactrian | Bactrian Camel | 双峰驼 | 双峰骆驼 |
| entity.untamedwilds.camel_dromedary | Dromedary | 单峰驼 | 单峰骆驼 |
| entity.untamedwilds.camel_wild_bactrian | Wild Bactrian Camel | 野生双峰驼 | 野骆驼 |
| untamedwilds.subtitles.camel.spit | Camel spits | 骆驼：唾 | 骆驼：吐口水 |
| untamedwilds.subtitles.camel.ambient | Camel grunts | 骆驼：发出呼噜声 | 骆驼：呼噜 |
| entity.untamedwilds.manatee_steller | Steller's Sea Cow | 北海牛 | 大海牛 |
| untamedwilds.subtitles.manatee.ambient | Manatee grunts | 海牛：发出呼噜声 | 海牛：呼噜 |
| entity.untamedwilds.bear_black | Black Bear | 黑熊 | 美洲黑熊 |
| entity.untamedwilds.bear_blind | Blind Cave Bear | 盲洞穴熊 | 盲洞熊 |
| entity.untamedwilds.bear_cave | Cave Bear | 洞穴熊 | 洞熊 |
| untamedwilds.subtitles.bear.ambient | Bear growls | 熊：咆哮 | 熊：吼叫 |
| untamedwilds.subtitles.bear.warning | Bear roars | 熊：怒吼 | 熊：咆哮 |
| entity.untamedwilds.big_cat_cave_lion | Cave Lion | 穴狮 | 洞狮 |
| entity.untamedwilds.big_cat_marsupial_lion | Marsupial Lion | 袋狮 | 刽子手袋狮 |
| entity.untamedwilds.big_cat_sabertooth | Sabertooth | 剑齿虎 | 毁灭刃齿虎 |
| untamedwilds.subtitles.big_cat.ambient | Big Cat roars | 大猫：怒吼 | 大猫：咆哮 |
| item.untamedwilds.bottle_tarantula_black | Black Tarantula in a Bottle | 黑狼蛛瓶 | 瓶装巴西黑丝绒 |
| entity.untamedwilds.tarantula_black | Black Tarantula | 黑狼蛛 | 巴西黑丝绒 |
| item.untamedwilds.bottle_tarantula_black_and_white | Black & White Tarantula in a Bottle | 黑白狼蛛瓶 | 瓶装巴西黑白脚 |
| entity.untamedwilds.tarantula_black_and_white | Black & White Tarantula | 黑白狼蛛 | 巴西黑白脚 |
| item.untamedwilds.bottle_tarantula_cobalt | Cobalt Tarantula in a Bottle | 钴蓝狼蛛瓶 | 瓶装金属蓝蛛 |
| entity.untamedwilds.tarantula_cobalt | Cobalt Tarantula | 钴蓝狼蛛 | 金属蓝蛛 |
| item.untamedwilds.bottle_tarantula_king | King Baboon Spider in a Bottle | 东非狼蛛瓶 | 瓶装皇帝巴布 |
| entity.untamedwilds.tarantula_king | King baboon Spider  | 东非狼蛛 | 皇帝巴布 |
| item.untamedwilds.bottle_tarantula_red_knee | Red Knee Tarantula in a Bottle | 墨西哥红膝狼蛛瓶 | 瓶装墨西哥红膝鸟蛛 |
| entity.untamedwilds.tarantula_red_knee | Red Knee Tarantula | 墨西哥红膝狼蛛 | 墨西哥红膝鸟蛛 |
| item.untamedwilds.bottle_tarantula_regalis | Ornamental Tree Spider in a Bottle | 蓝宝石华丽雨林蜘蛛瓶 | 瓶装印度华丽雨林蛛 |
| entity.untamedwilds.tarantula_regalis | Ornamental Tree Spider | 蓝宝石华丽雨林蜘蛛 | 印度华丽雨林蛛 |
| item.untamedwilds.bottle_tarantula_rose | Rose Hair Tarantula in a Bottle | 智利红玫瑰蜘蛛瓶 | 瓶装智利火玫瑰 |
| entity.untamedwilds.tarantula_rose | Rose Hair Tarantula | 智利红玫瑰蜘蛛 | 智利火玫瑰 |
| item.untamedwilds.bottle_tarantula_tiger | Tiger Rump Tarantula in a Bottle | 哥斯达黎加老虎尾蜘蛛瓶 | 瓶装哥斯达黎加老虎尾蜘蛛 |
| item.untamedwilds.sunfish_spawn_egg | Ocean Sunfish Spawn Egg | 翻车鲀刷怪蛋 | 翻车鱼刷怪蛋 |
| item.untamedwilds.egg_sunfish | Ocean Sunfish Roe | 翻车鲀卵 | 翻车鱼卵 |
| entity.untamedwilds.sunfish | Ocean Sunfish | 翻车鲀 | 翻车鱼 |
| entity.untamedwilds.sunfish_sunfish | Ocean Sunfish | 翻车鲀 | 翻车鱼 |
| entity.untamedwilds.sunfish_southern | Southern Sunfish | 南部翻车鲀 | 拉氏翻车鱼 |
| entity.untamedwilds.trevally_bigeye | Bigeye Trevally | 大眼鲹 | 六带鲹 |
| item.untamedwilds.bucket_trevally_bigeye | Bucket of Bigeye Trevally | 大眼鲹桶 | 六带鲹桶 |
| item.untamedwilds.arowana_spawn_egg | Arowana Spawn Egg | 龙鱼刷怪蛋 | 骨舌鱼刷怪蛋 |
| item.untamedwilds.egg_arowana | Arowana Roe | 龙鱼卵 | 骨舌鱼卵 |
| entity.untamedwilds.arowana | arowana | 龙鱼 | 骨舌鱼 |
| entity.untamedwilds.arowana_black | Black Arowana | 黑龙鱼 | 黑骨舌鱼 |
| entity.untamedwilds.arowana_dragon | Super Red Arowana | 红龙鱼 | 利氏硬仆骨舌鱼 |
| entity.untamedwilds.arowana_golden | Golden Arowana | 金龙鱼 | 金色硬仆骨舌鱼 |
| entity.untamedwilds.arowana_green | Green arowana | 亚洲龙鱼 | 美丽硬仆骨舌鱼 |
| entity.untamedwilds.arowana_jardini | Jardini Arowana | 珍珠龙鱼 | 澳洲硬仆骨舌鱼 |
| entity.untamedwilds.arowana_silver | Silver Arowana | 银龙鱼 | 双须骨舌鱼 |
| item.untamedwilds.bucket_arowana_black | Bucket of Black Arowana | 黑龙鱼桶 | 黑骨舌鱼桶 |
| item.untamedwilds.bucket_arowana_dragon | Bucket of Super Red Arowana | 红龙鱼桶 | 利氏硬仆骨舌鱼桶 |
| item.untamedwilds.bucket_arowana_golden | Bucket of Golden Arowana | 金龙鱼桶 | 金色硬仆骨舌鱼桶 |
| item.untamedwilds.bucket_arowana_green | Bucket of Green Arowana | 亚洲龙鱼桶 | 美丽硬仆骨舌鱼桶 |
| item.untamedwilds.bucket_arowana_jardini | Bucket of Jardini Arowana | 珍珠龙鱼桶 | 澳洲硬仆骨舌鱼桶 |
| item.untamedwilds.bucket_arowana_silver | Bucket of Silver Arowana | 银龙鱼桶 | 双须骨舌鱼桶 |
| entity.untamedwilds.triggerfish_clown | Clown Triggerfish | 小丑炮弹 | 花斑拟鳞鲀 |
| entity.untamedwilds.triggerfish_grey | Grey Triggerfish | 灰炮弹 | 灰鳞鲀 |
| entity.untamedwilds.triggerfish_orangelined | Orange\-Lined Triggerfish | 橙纹炮弹 | 波纹钩鳞鲀 |
| entity.untamedwilds.triggerfish_picasso | Picasso Triggerfish | 毕加索鳞鲀 | 阿氏锉鳞鲀 |
| entity.untamedwilds.triggerfish_titan | Titan Triggerfish | 泰坦扳机鱼 | 褐拟鳞鲀 |
| item.untamedwilds.bucket_triggerfish_clown | Bucket of Clown Triggerfish | 桶装小丑炮弹 | 花斑拟鳞鲀桶 |
| item.untamedwilds.bucket_triggerfish_grey | Bucket of Grey Triggerfish | 桶装灰炮弹 | 灰鳞鲀桶 |
| item.untamedwilds.bucket_triggerfish_orangelined | Bucket of Orange\-Lined Triggerfish | 桶装橙纹炮弹 | 波纹钩鳞鲀桶 |
| item.untamedwilds.bucket_triggerfish_picasso | Bucket of Picasso Triggerfish | 桶装毕加索鳞鲀 | 阿氏锉鳞鲀桶 |
| item.untamedwilds.bucket_triggerfish_redtooth | Bucket of Redtooth Triggerfish | 桶装红牙鳞鲀 | 红牙鳞鲀桶 |
| item.untamedwilds.bucket_triggerfish_reef | Bucket of Reef Triggerfish | 桶装斜带吻棘鲀 | 斜带吻棘鲀桶 |
| item.untamedwilds.bucket_triggerfish_titan | Bucket of Titan Triggerfish | 桶装泰坦扳机鱼 | 褐拟鳞鲀桶 |
| entity.untamedwilds.catfish_blue | Blue Catfish | 长鳍叉尾鲶 | 蓝鲶 |
| entity.untamedwilds.catfish_channel | Channel Catfish | 斑点叉尾鲶 | 斑点叉尾鮰 |
| entity.untamedwilds.catfish_redtail | Redtail Catfish | 红尾护头鲶 | 红尾鲶 |
| entity.untamedwilds.catfish_shovelnose | Shovelnose Catfish | 拟宽口鲶 | 虎皮鸭嘴鲶 |
| item.untamedwilds.bucket_catfish_blue | Bucket of Blue Catfish | 桶装长鳍叉尾鲶 | 蓝鲶桶 |
| item.untamedwilds.bucket_catfish_channel | Bucket of Channel Catfish | 桶装斑点叉尾鲶 | 斑点叉尾鮰桶 |
| item.untamedwilds.bucket_catfish_redtail | Bucket of Redtail Catfish | 桶装红尾护头鲶 | 红尾鲶桶 |
| entity.untamedwilds.shark_goblin | Goblin Shark | 欧氏尖吻鲛 | 剑吻鲨 |
| entity.untamedwilds.shark_greenland | Greenland Shark | 格陵兰鲨 | 格陵兰睡鲨 |
| entity.untamedwilds.shark_lemon | Lemon Shark | 柠檬鲨 | 短吻柠檬鲨 |
| entity.untamedwilds.shark_tiger | Tiger Shark | 虎鲨 | 鼬鲨 |
| item.untamedwilds.football_fish_spawn_egg | Football Fish Spawn Egg | 鞭冠鮟鱇刷怪蛋 | 鞭冠鮟鱇鱼刷怪蛋 |
| item.untamedwilds.egg_football_fish | Football Fish Roe | 鞭冠鮟鱇卵 | 鞭冠鮟鱇鱼卵 |
| entity.untamedwilds.football_fish | football fish | 鞭冠鮟鱇 | 鞭冠鮟鱇鱼 |
| entity.untamedwilds.football_fish_atlantic | Atlantic Football Fish | 多指鞭冠鮟鱇 | 多指鞭冠鮟鱇鱼 |
| item.untamedwilds.bucket_football_fish_atlantic | Bucket of Football Fish | 鞭冠鮟鱇桶 | 多指鞭冠鮟鱇鱼桶 |
| item.untamedwilds.food_turtle_raw | Raw Turtle Meat | 生龟肉 | 生鳖肉 |
| item.untamedwilds.food_turtle_cooked | Cooked Turtle Meat | 熟龟肉 | 熟鳖肉 |
| item.untamedwilds.food_turtle_soup | Turtle Soup | 龟肉汤 | 鳖肉汤 |
| entity.untamedwilds.softshell_turtle_black | Black Softshell Turtle | 黑鳖 | 恒河鳖 |
| entity.untamedwilds.sof [...]

2023-07-15 00:19 UTC, sea-turtle0 commented
> @sea-turtle0 大概看一下，如果没问题请在 PR 主对话里另起一行写 `resolved #2342`
> 
> 我对比了“#2342”和“#3448”的翻译，结果如下：
> 
> ### 两者皆有且中文有差异
> 
> <details><summary>点击展开/收起</summary>
> <p>
> 
> | **键** | **英文** | **#2342** | **#3448** |
> |---|---|---|---|
> | entity.untamedwilds.command.0 | This mob is now Wandering | 生物行为：徘徊 | 这个生物正在闲逛 |
> | entity.untamedwilds.command.1 | This mob is now Protecting you | 生物行为：护主 | 这个生物正在保护你 |
> | entity.untamedwilds.command.2 | This mob is now Sitting | 生物行为：坐下 | 这个生物正坐着 |
> | entity.untamedwilds.command.3 | This mob is now Guarding the area | 生物行为：保护附近区域 | 这个生物正在守护这片领地 |
> | entity.untamedwilds.hippo_common | Common Hippo | 普通河马 | 河马 |
> | entity.untamedwilds.bison_plains | Plains Bison | 平原野牛 | 美洲平原野牛 |
> | untamedwilds.subtitles.bison.ambient | Bison ruts | Bison ruts | 野牛：发情 |
> | untamedwilds.subtitles.aardvark.ambient | Aardvark grunts | 土豚：发出呼噜声 | 土豚：呼噜 |
> | entity.untamedwilds.hyena_shortface | Giant Short\-Faced Hyena | 巨鬣狗 | 短吻硕鬣狗 |
> | untamedwilds.subtitles.hyena.ambient | Hyena whoops | 鬣狗：叫喊 | 鬣狗：吼叫 |
> | entity.untamedwilds.boar_eurasian | Wild Boar | 野猪 | 欧亚野猪 |
> | entity.untamedwilds.boar_peccary | Peccary | 矛牙野猪 | 白唇西貒 |
> | entity.untamedwilds.boar_red_river | Red River Hog | 红河野猪 | 红河猪 |
> | untamedwilds.subtitles.boar.ambient | Boar grunts | 野猪：发出呼噜声 | 野猪：呼噜 |
> | entity.untamedwilds.camel_bactrian | Bactrian Camel | 双峰驼 | 双峰骆驼 |
> | entity.untamedwilds.camel_dromedary | Dromedary | 单峰驼 | 单峰骆驼 |
> | entity.untamedwilds.camel_wild_bactrian | Wild Bactrian Camel | 野生双峰驼 | 野骆驼 |
> | untamedwilds.subtitles.camel.spit | Camel spits | 骆驼：唾 | 骆驼：吐口水 |
> | untamedwilds.subtitles.camel.ambient | Camel grunts | 骆驼：发出呼噜声 | 骆驼：呼噜 |
> | entity.untamedwilds.manatee_steller | Steller's Sea Cow | 北海牛 | 大海牛 |
> | untamedwilds.subtitles.manatee.ambient | Manatee grunts | 海牛：发出呼噜声 | 海牛：呼噜 |
> | entity.untamedwilds.bear_black | Black Bear | 黑熊 | 美洲黑熊 |
> | entity.untamedwilds.bear_blind | Blind Cave Bear | 盲洞穴熊 | 盲洞熊 |
> | entity.untamedwilds.bear_cave | Cave Bear | 洞穴熊 | 洞熊 |
> | untamedwilds.subtitles.bear.ambient | Bear growls | 熊：咆哮 | 熊：吼叫 |
> | untamedwilds.subtitles.bear.warning | Bear roars | 熊：怒吼 | 熊：咆哮 |
> | entity.untamedwilds.big_cat_cave_lion | Cave Lion | 穴狮 | 洞狮 |
> | entity.untamedwilds.big_cat_marsupial_lion | Marsupial Lion | 袋狮 | 刽子手袋狮 |
> | entity.untamedwilds.big_cat_sabertooth | Sabertooth | 剑齿虎 | 毁灭刃齿虎 |
> | untamedwilds.subtitles.big_cat.ambient | Big Cat roars | 大猫：怒吼 | 大猫：咆哮 |
> | item.untamedwilds.bottle_tarantula_black | Black Tarantula in a Bottle | 黑狼蛛瓶 | 瓶装巴西黑丝绒 |
> | entity.untamedwilds.tarantula_black | Black Tarantula | 黑狼蛛 | 巴西黑丝绒 |
> | item.untamedwilds.bottle_tarantula_black_and_white | Black & White Tarantula in a Bottle | 黑白狼蛛瓶 | 瓶装巴西黑白脚 |
> | entity.untamedwilds.tarantula_black_and_white | Black & White Tarantula | 黑白狼蛛 | 巴西黑白脚 |
> | item.untamedwilds.bottle_tarantula_cobalt | Cobalt Tarantula in a Bottle | 钴蓝狼蛛瓶 | 瓶装金属蓝蛛 |
> | entity.untamedwilds.tarantula_cobalt | Cobalt Tarantula | 钴蓝狼蛛 | 金属蓝蛛 |
> | item.untamedwilds.bottle_tarantula_king | King Baboon Spider in a Bottle | 东非狼蛛瓶 | 瓶装皇帝巴布 |
> | entity.untamedwilds.tarantula_king | King baboon Spider  | 东非狼蛛 | 皇帝巴布 |
> | item.untamedwilds.bottle_tarantula_red_knee | Red Knee Tarantula in a Bottle | 墨西哥红膝狼蛛瓶 | 瓶装墨西哥红膝鸟蛛 |
> | entity.untamedwilds.tarantula_red_knee | Red Knee Tarantula | 墨西哥红膝狼蛛 | 墨西哥红膝鸟蛛 |
> | item.untamedwilds.bottle_tarantula_regalis | Ornamental Tree Spider in a Bottle | 蓝宝石华丽雨林蜘蛛瓶 | 瓶装印度华丽雨林蛛 |
> | entity.untamedwilds.tarantula_regalis | Ornamental Tree Spider | 蓝宝石华丽雨林蜘蛛 | 印度华丽雨林蛛 |
> | item.untamedwilds.bottle_tarantula_rose | Rose Hair Tarantula in a Bottle | 智利红玫瑰蜘蛛瓶 | 瓶装智利火玫瑰 |
> | entity.untamedwilds.tarantula_rose | Rose Hair Tarantula | 智利红玫瑰蜘蛛 | 智利火玫瑰 |
> | item.untamedwilds.bottle_tarantula_tiger | Tiger Rump Tarantula in a Bottle | 哥斯达黎加老虎尾蜘蛛瓶 | 瓶装哥斯达黎加老虎尾蜘蛛 |
> | item.untamedwilds.sunfish_spawn_egg | Ocean Sunfish Spawn Egg | 翻车鲀刷怪蛋 | 翻车鱼刷怪蛋 |
> | item.untamedwilds.egg_sunfish | Ocean Sunfish Roe | 翻车鲀卵 | 翻车鱼卵 |
> | entity.untamedwilds.sunfish | Ocean Sunfish | 翻车鲀 | 翻车鱼 |
> | entity.untamedwilds.sunfish_sunfish | Ocean Sunfish | 翻车鲀 | 翻车鱼 |
> | entity.untamedwilds.sunfish_southern | Southern Sunfish | 南部翻车鲀 | 拉氏翻车鱼 |
> | entity.untamedwilds.trevally_bigeye | Bigeye Trevally | 大眼鲹 | 六带鲹 |
> | item.untamedwilds.bucket_trevally_bigeye | Bucket of Bigeye Trevally | 大眼鲹桶 | 六带鲹桶 |
> | item.untamedwilds.arowana_spawn_egg | Arowana Spawn Egg | 龙鱼刷怪蛋 | 骨舌鱼刷怪蛋 |
> | item.untamedwilds.egg_arowana | Arowana Roe | 龙鱼卵 | 骨舌鱼卵 |
> | entity.untamedwilds.arowana | arowana | 龙鱼 | 骨舌鱼 |
> | entity.untamedwilds.arowana_black | Black Arowana | 黑龙鱼 | 黑骨舌鱼 |
> | entity.untamedwilds.arowana_dragon | Super Red Arowana | 红龙鱼 | 利氏硬仆骨舌鱼 |
> | entity.untamedwilds.arowana_golden | Golden Arowana | 金龙鱼 | 金色硬仆骨舌鱼 |
> | entity.untamedwilds.arowana_green | Green arowana | 亚洲龙鱼 | 美丽硬仆骨舌鱼 |
> | entity.untamedwilds.arowana_jardini | Jardini Arowana | 珍珠龙鱼 | 澳洲硬仆骨舌鱼 |
> | entity.untamedwilds.arowana_silver | Silver Arowana | 银龙鱼 | 双须骨舌鱼 |
> | item.untamedwilds.bucket_arowana_black | Bucket of Black Arowana | 黑龙鱼桶 | 黑骨舌鱼桶 |
> | item.untamedwilds.bucket_arowana_dragon | Bucket of Super Red Arowana | 红龙鱼桶 | 利氏硬仆骨舌鱼桶 |
> | item.untamedwilds.bucket_arowana_golden | Bucket of Golden Arowana | 金龙鱼桶 | 金色硬仆骨舌鱼桶 |
> | item.untamedwilds.bucket_arowana_green | Bucket of Green Arowana | 亚洲龙鱼桶 | 美丽硬仆骨舌鱼桶 |
> | item.untamedwilds.bucket_arowana_jardini | Bucket of Jardini Arowana | 珍珠龙鱼桶 | 澳洲硬仆骨舌鱼桶 |
> | item.untamedwilds.bucket_arowana_silver | Bucket of Silver Arowana | 银龙鱼桶 | 双须骨舌鱼桶 |
> | entity.untamedwilds.triggerfish_clown | Clown Triggerfish | 小丑炮弹 | 花斑拟鳞鲀 |
> | entity.untamedwilds.triggerfish_grey | Grey Triggerfish | 灰炮弹 | 灰鳞鲀 |
> | entity.untamedwilds.triggerfish_orangelined | Orange\-Lined Triggerfish | 橙纹炮弹 | 波纹钩鳞鲀 |
> | entity.untamedwilds.triggerfish_picasso | Picasso Triggerfish | 毕加索鳞鲀 | 阿氏锉鳞鲀 |
> | entity.untamedwilds.triggerfish_titan | Titan Triggerfish | 泰坦扳机鱼 | 褐拟鳞鲀 |
> | item.untamedwilds.bucket_triggerfish_clown | Bucket of Clown Triggerfish | 桶装小丑炮弹 | 花斑拟鳞鲀桶 |
> | item.untamedwilds.bucket_triggerfish_grey | Bucket of Grey Triggerfish | 桶装灰炮弹 | 灰鳞鲀桶 |
> | item.untamedwilds.bucket_triggerfish_orangelined | Bucket of Orange\-Lined Triggerfish | 桶装橙纹炮弹 | 波纹钩鳞鲀桶 |
> | item.untamedwilds.bucket_triggerfish_picasso | Bucket of Picasso Triggerfish | 桶装毕加索鳞鲀 | 阿氏锉鳞鲀桶 |
> | item.untamedwilds.bucket_triggerfish_redtooth | Bucket of Redtooth Triggerfish | 桶装红牙鳞鲀 | 红牙鳞鲀桶 |
> | item.untamedwilds.bucket_triggerfish_reef | Bucket of Reef Triggerfish | 桶装斜带吻棘鲀 | 斜带吻棘鲀桶 |
> | item.untamedwilds.bucket_triggerfish_titan | Bucket of Titan Triggerfish | 桶装泰坦扳机鱼 | 褐拟鳞鲀桶 |
> | entity.untamedwilds.catfish_blue | Blue Catfish | 长鳍叉尾鲶 | 蓝鲶 |
> | entity.untamedwilds.catfish_channel | Channel Catfish | 斑点叉尾鲶 | 斑点叉尾鮰 |
> | entity.untamedwilds.catfish_redtail | Redtail Catfish | 红尾护头鲶 | 红尾鲶 |
> | entity.untamedwilds.catfish_shovelnose | Shovelnose Catfish | 拟宽口鲶 | 虎皮鸭嘴鲶 |
> | item.untamedwilds.bucket_catfish_blue | Bucket of Blue Catfish | 桶装长鳍叉尾鲶 | 蓝鲶桶 |
> | item.untamedwilds.bucket_catfish_channel | Bucket of Channel Catfish | 桶装斑点叉尾鲶 | 斑点叉尾鮰桶 |
> | item.untamedwilds.bucket_catfish_redtail | Bucket of Redtail Catfish | 桶装红尾护头鲶 | 红尾鲶桶 |
> | entity.untamedwilds.shark_goblin | Goblin Shark | 欧氏尖吻鲛 | 剑吻鲨 |
> | entity.untamedwilds.shark_greenland | Greenland Shark | 格陵兰鲨 | 格陵兰睡鲨 |
> | entity.untamedwilds.shark_lemon | Lemon Shark | 柠檬鲨 | 短吻柠檬鲨 |
> | entity.untamedwilds.shark_tiger | Tiger Shark | 虎鲨 | 鼬鲨 |
> | item.untamedwilds.football_fish_spawn_egg | Football Fish Spawn Egg | 鞭冠鮟鱇刷怪蛋 | 鞭冠鮟鱇鱼刷怪蛋 |
> | item.untamedwilds.egg_football_fish | Football Fish Roe | 鞭冠鮟鱇卵 | 鞭冠鮟鱇鱼卵 |
> | entity.untamedwilds.football_fish | football fish | 鞭冠鮟鱇 | 鞭冠鮟鱇鱼 |
> | entity.untamedwilds.football_fish_atlantic | Atlantic Football Fish | 多指鞭冠鮟鱇 | 多指鞭冠鮟鱇鱼 |
> | item.untamedwilds.bucket_football_fish_atlantic | Bucket of Football Fish | 鞭冠鮟鱇桶 | 多指鞭冠鮟鱇鱼桶 |
> | item.untamedwilds.food_turtle_raw | Raw T [...]

2023-07-15 14:18 UTC, merged