Valkyrien Skies/Valkyrien Warfare 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3462
Opened 2023-07-07 09:12 UTC by blibilijojo

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2023-07-07 12:11 UTC, Slow-Witted-Fish commented
> ⚠ 检测到了一个语言文件，但是提交的路径不正常。缺少了 {ModDomain} 或 {CurseForge 项目名} 文件夹。请检查你的提交路径：`projects/1.19/assets/valkyrienskies/lang/zh_cn.json`； 无法找到该模组的 Mod Domain。

路径错误，正确路径应为 ./assets/ {CurseForge ID} / {命名空间} /lang/

2023-07-11 16:03 UTC, mamaruo requested changes
路径不对，缺少英文文件，占位符前后不要空格，请认真阅读CONTRIBUTING

2023-07-14 19:50 UTC, mamaruo commented
请及时回应审阅意见，否则 PR 将被关闭。

2023-07-21 15:48 UTC, dovisutu commented
- 7+7时限进入第二阶段。从该评论发出的时间开始计时。

ping @blibilijojo

2023-07-29 01:39 UTC, closed without merging