playerrevive 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3468
Opened 2023-07-09 06:16 UTC by OldFishKog

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-07-11 15:53 UTC, mamaruo commented
参考 库内 1.12 的统一一下
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/projects/1.12.2/assets/playerrevive/playerrevive/lang/zh_cn.lang

2023-07-11 17:37 UTC, mamaruo requested changes

2023-07-11 17:37 UTC, mamaruo commented on projects/1.19/assets/playerrevive/playerrevive/lang/zh_cn.json
> +	"playerrevive.revive.item": "你得救了 "
```suggestion
	"playerrevive.revive.item": "你需要"
```

2023-07-11 17:37 UTC, mamaruo commented on projects/1.19/assets/playerrevive/playerrevive/lang/zh_cn.json
> +	"playerrevive.gui.label.time_left": "剩余时间：%s 秒",
```suggestion
	"playerrevive.gui.label.time_left": "剩余时间：%s 秒",
```
请求确认占位符的内容，万一它会是“1分2秒”这个格式就不好了

2023-07-12 05:39 UTC, OldFishKog commented
同时增加了之前漏掉的按键持续秒数的占位符；而item条目我并未在游戏内看到过，根据you require在此模组的语义应该是得救

2023-07-12 05:44 UTC, OldFishKog commented
实际上成功救援并没有任何提示；同时，附上汉化后的截图
![2023-07-12_13 34 01](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/121704835/9cf42b4e-1197-4626-953b-1d09d742a295)

2023-07-12 06:22 UTC, mamaruo commented
> 同时增加了之前漏掉的按键持续秒数的占位符；而item条目我并未在游戏内看到过，根据you require在此模组的语义应该是得救

看了下代码，结合本地化键，这是个可选功能，可以配置为施救者需要携带某个物品才能救援，且救援后物品消失。如果施救者身上没有带该物品，则会发送这条消息说“你需要……”
```java
    @SubscribeEvent(priority = EventPriority.HIGH)
    public void playerInteract(PlayerInteractEvent.EntityInteract event) {
        if (event.getTarget() instanceof Player && !event.getEntity().level().isClientSide) {
            Player target = (Player) event.getTarget();
            Player helper = event.getEntity();
            IBleeding revive = PlayerReviveServer.getBleeding(target);
            if (revive.isBleeding()) {
                event.setCanceled(true);
                if (PlayerRevive.CONFIG.revive.needReviveItem) {
                    if (PlayerRevive.CONFIG.revive.consumeReviveItem && !revive.isItemConsumed()) {
                        if (!PlayerRevive.CONFIG.revive.reviveItem.is(helper.getMainHandItem())) {
                            if (!helper.isCreative())
                                helper.getMainHandItem().shrink(1);
                            revive.setItemConsumed();
                        } else {
                            helper.sendSystemMessage(Component.translatable("playerrevive.revive.item").append(PlayerRevive.CONFIG.revive.reviveItem.description()));
                            return;
                        }
                    } else if (!PlayerRevive.CONFIG.revive.reviveItem.is(helper.getMainHandItem()))
                        return;
                }
                
                PlayerReviveServer.removePlayerAsHelper(helper);
                revive.revivingPlayers().add(helper);
                PlayerRevive.NETWORK.sendToClient(new HelperPacket(target.getUUID(), true), (ServerPlayer) helper);
            }
        }
    }
```

2023-07-12 07:54 UTC, mamaruo approved these changes

2023-07-13 23:50 UTC, merged