添加Silent-Gear寂静装备1.20汉化
CFPAOrg/Minecraft-Mod-Language-Package pull request #3471
Opened 2023-07-10 05:44 UTC by AnECanSaiTin

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-07-10 13:23 UTC, ChuijkYahus commented
这个路径还是有误，请注意参照CONTRIBUTING中例子进行修改

2023-07-10 18:17 UTC, ChuijkYahus commented
/mv projects/1.20/silent-gear/assets/silentgear/lang/en_us.json projects/1.20/assets/silent-gear/silentgear/lang/en_us.json
/mv projects/1.20/silent-gear/assets/silentgear/lang/zh_cn.json projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json

2023-07-10 18:18 UTC, ChuijkYahus commented
还请注意阅读CONTRIBUTING中有关文件路径的部分
~~这是改三次了吧~~

2023-07-22 15:46 UTC, ChuijkYahus reviewed
迟来的审核

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "item.silentgear.starmetal_dust": "星辉粉",
不知道到时候星辉魔法会不会更新上来

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "item.silentgear.wide_plate_upgrade.desc": "使锤与开掘铲的作用范围提升 1 格（不可叠加）",
```suggestion
    "item.silentgear.wide_plate_upgrade.desc": "使锤与开掘铲的作用范围提升1格（不可叠加）",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "material.silentgear.amethyst": "紫晶",
```suggestion
    "material.silentgear.amethyst": "紫水晶",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "material.silentgear.fluffy_string": "蓬松线",
```suggestion
    "material.silentgear.fluffy_string": "毛绒线",
```
建议全文件通查`毛绒`和`蓬松`的统一

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "material.silentgear.refined_glowstone": "精制荧石",
```suggestion
    "material.silentgear.refined_glowstone": "强化荧石",
```
应该是Mekanism的材料兼容吧

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "misc.silentgear.graderCatalyst": "分级催化剂（等级 %d）",
```suggestion
    "misc.silentgear.graderCatalyst": "分级催化剂（等级%d）",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "misc.silentgear.spaceBrackets": " (%s)",
```suggestion
    "misc.silentgear.spaceBrackets": "（%s）",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "misc.silentgear.starlightChargerCataylst": "星光充能仪催化剂（等级 %d）",
```suggestion
    "misc.silentgear.starlightChargerCataylst": "星光充能仪催化剂（等级%d）",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "misc.silentgear.tier": "层级 %d",
```suggestion
    "misc.silentgear.tier": "层级%d",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "misc.silentgear.tooltip.ctrlForStats": "参数 §8<按下Ctrl>",
```suggestion
    "misc.silentgear.tooltip.ctrlForStats": "参数§8<按下Ctrl>",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "part.silentgear.gradeOnPart": "品级: %s",
```suggestion
    "part.silentgear.gradeOnPart": "品级：%s",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "part.silentgear.misc.road_maker": "路标升级",
```suggestion
    "part.silentgear.misc.road_maker": "造路升级",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "part.silentgear.type.fletching": "尾羽",
记得与上文统一

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "stat.silentgear.armorFormat": "%1$s (%2$s)",
```suggestion
    "stat.silentgear.armorFormat": "%1$s（%2$s）",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "stat.silentgear.armor_durability": "装甲耐久",
```suggestion
    "stat.silentgear.armor_durability": "装甲耐久度",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "stat.silentgear.displayFormat": "%1$s §r§8:§r %2$s",
```suggestion
    "stat.silentgear.displayFormat": "%1$s§r§8：§r%2$s",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "part.silentgear.type.cord": "线",
这个是弓弦？

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "stat.silentgear.projectile_speed": "抛射速度",
```suggestion
    "stat.silentgear.projectile_accuracy": "弹射准度",
    "stat.silentgear.projectile_speed": "弹射速度",
```
原版术语

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.bastion": "壁垒",
原版有个堡垒遗迹是bastion，不改也没问题

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.bending.desc": "装备有几率增加耐久度消耗（与【灵活】相抵消）",
```suggestion
    "trait.silentgear.bending.desc": "装备有概率增加耐久度消耗（与“柔韧”相抵消）",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.brittle.desc": "装备有几率增加耐久度消耗（与【可塑】相抵消）",
```suggeation
    "trait.silentgear.brittle.desc": "装备有概率增加耐久度消耗（与“可塑”相抵消）",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.crackler.desc": "以耐久值为代价放置玄武岩",
```suggestion
    "trait.silentgear.crackler.desc": "以耐久度为代价放置玄武岩",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.cure_wither": "唤生",
这个原文和唤生好像不是很对得上，不知道`解凋`怎么样

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.eroded.desc": "工具受损时提升采掘速度并减缓攻击伤害",
```suggestion
    "trait.silentgear.eroded.desc": "工具受损时提升采掘速度并减少攻击伤害",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.flexible.desc": "装备有几率减少耐久度消耗（与【易碎】相抵消）",
```suggestion
    "trait.silentgear.flexible": "柔韧",
    "trait.silentgear.flexible.desc": "装备有概率减少耐久度消耗（与“易碎”相抵消）",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.gold_digger.desc": "有几率在采掘时增加粒掉落量",
```suggestion
    "trait.silentgear.gold_digger.desc": "有概率在采掘时增加粒掉落量",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.hard.desc": "工具受损时加快其采掘速度（与【柔软】相抵消）",
```suggestion
    "trait.silentgear.hard.desc": "工具受损时加快其采掘速度（与“柔软”相抵消）",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.imperial": "帝国宝藏",
要不直接`帝国`？

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.jabberwocky.desc": "是滑菱鲆在缓慢滑动/时而翻转时而平衡",
可以看下这个
https://baike.baidu.com/item/JABBERWOCKY/16217899?fr=ge_ala
不知道能不能取

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.lucky.desc.long": "“幸运”是一种原版中提升运气的状态效果，在某些情况下会影响箱子战利品产出，与“时运”附魔毫无干系！“幸运”无法影响矿物出产！",
```suggestion
    "trait.silentgear.lucky.desc.long": "“幸运”是一种原版中提升运气的状态效果，在某些情况下会影响箱子战利品产出，与“时运”魔咒毫无干系！“幸运”无法影响矿物出产！",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.magmatic": "熔岩",
```suggestion
    "trait.silentgear.magmatic": "岩浆",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.malleable.desc": "装备有几率降低耐久度消耗（与【易碎】相抵消）",
```suggestion
    "trait.silentgear.malleable.desc": "装备有几率降低耐久度消耗（与“易碎”相抵消）",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.soft.desc": "工具受损时减缓其采掘速度（与【坚硬】相抵消）",
```suggestion
    "trait.silentgear.soft.desc": "工具受损时减缓其采掘速度（与“坚硬”相抵消）",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.rustic.desc": "数值小于或等于100%时获得协调度增益",
```suggestion
    "trait.silentgear.rustic.desc": "协调度小于或等于100%时获得协调度增益",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "advancements.silentgear.kachink2.description": "在一件拥有【易碎】属性的装备上损耗一点额外耐久度",
```suggestion
    "advancements.silentgear.kachink2.description": "在一件拥有“易碎”属性的装备上损耗一点额外耐久度",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "advancements.silentgear.moonwalker.description": "装备一双具有【月行者】属性的靴子然后猛地一跳！",
```suggestion
    "advancements.silentgear.moonwalker.description": "装备一双具有“月行者”属性的靴子然后猛地一跳！",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "advancements.silentgear.sickle.title": "作物收割者",
```suggestion
    "advancements.silentgear.sickle.title": "植物毁灭者",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "advancements.silentgear.sickle.description": "制作一把镰刀，它能够一次性收割大范围的作物",
```suggestion
    "advancements.silentgear.sickle.description": "制作一把镰刀，它能够一次性收割大范围的植物",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "advancements.silentgear.salvager.description": "当你不再需要那些老玩意儿……",
```suggestion
    "advancements.silentgear.salvager.description": "当你不再需要那些老装备……",
```

2023-07-22 15:46 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "advancements.silentgear.nether.description": "我往深处去……",
怎么感觉像某首Yogscast的mc金曲
见https://www.bilibili.com/video/BV1sx411T7Ua 的4:40

```suggestion
    "advancements.silentgear.nether.description": "我要搬到下界去……",
```

2023-07-23 10:05 UTC, Cactusstudent requested changes
建议通篇查看术语

2023-07-23 10:05 UTC, Cactusstudent commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.mighty.desc": "提供力量和/或急迫增益，增益强度与特性等级成正比",
这表述怎么这么怪呢

2023-07-23 10:05 UTC, Cactusstudent commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.racker.desc": "以耐久值为代价放置下界岩",
```suggestion
    "trait.silentgear.racker.desc": "以耐久度为代价放置下界岩",
```

2023-07-23 10:28 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "item.silentgear.blueprint.paxel.desc": "全能工具",
这个地方原文真的是AIOT

2023-07-23 10:29 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.mighty.desc": "提供力量和/或急迫增益，增益强度与特性等级成正比",
经典and/or，其实感觉就是AnotB+BnotA+AB这种意思

2023-07-29 18:30 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.road_maker.desc": "将泥土类方块转化为草径",
```suggestion
    "trait.silentgear.road_maker.desc": "将泥土类方块转化为土径",
```

2023-07-29 18:33 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.flame_ward.desc": "装备整套盔甲时提供火焰抗性效果",
```suggestion
    "trait.silentgear.flame_ward.desc": "装备整套盔甲时提供抗火效果",
```

2023-07-29 18:34 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.stellar.desc": "盔甲：提供移动速度与跳跃高度增益；工具：缓慢修复自身耐久",
```suggestion
    "trait.silentgear.stellar.desc": "盔甲：提供速度和跳跃提升；工具：缓慢修复自身耐久",
```
可以游戏内验证

2023-07-29 18:39 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "stat.silentgear.magic_armor": "魔法抗性",
这个原文比较麻烦

2023-07-30 00:57 UTC, AnECanSaiTin commented
还以为从1.18的文本移植上来不会有什么错误，结果这么多问题。

2023-07-30 01:56 UTC, AnECanSaiTin commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "block.silentgear.refabricator": "缝纫机",
有这几个方块不就要翻译吗🤔

2023-07-30 02:28 UTC, AnECanSaiTin commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "part.silentgear.type.cord": "线",
不能说是弓弦，因为所有工具武器里，只要用到类似线的东西都是这个，像是鱼竿

2023-07-30 02:37 UTC, AnECanSaiTin commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.cure_wither": "唤生",
这句从1.18抄过来，我认为是体现与凋零这一词相反含义

2023-07-30 02:40 UTC, AnECanSaiTin commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.imperial": "帝国宝藏",
只有帝国感觉与掉落数量增加没什么关联

2023-07-30 02:46 UTC, AnECanSaiTin commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.magmatic": "熔岩",
因为原版是熔岩，我觉得可以不变

2023-07-30 02:53 UTC, AnECanSaiTin commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "jei.silentgear.hammer.desc": "一次性采掘3x3范围内适配镐类工具的方块。默认情况下，仅在准心指向矿石时范围挖掘才会波及矿石方块。",
“一次性采掘3x3范围内可被镐挖掘的方块”这样更顺口

2023-07-30 03:02 UTC, AnECanSaiTin commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.stellar.desc": "盔甲：提供移动速度与跳跃高度增益；工具：缓慢修复自身耐久",
速度没有药水效果，跳跃有

2023-07-30 03:04 UTC, AnECanSaiTin commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "block.silentgear.refabricator": "缝纫机",
理解错了，缝纫机方块可以合成线、布、织物这些东西，而且从外观上看也是缝纫机。不知道为什么老的翻译是材料再造机

2023-07-30 03:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3471) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3471) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3471) it.</sub>

2023-07-30 03:19 UTC, AnECanSaiTin commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "material.category.silentgear.sheet": "薄片",
改为“板”

2023-07-30 04:54 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.magmatic": "熔岩",
原版也有`岩浆块`/`Magma Block`
推荐改下，不过不改应该也没太大问题

2023-07-31 04:30 UTC, ChuijkYahus submitted a review, later dismissed
等另一位审核人员来看吧

2023-08-01 07:47 UTC, Cactusstudent submitted a review, later dismissed

2023-08-01 07:47 UTC, Cactusstudent commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "item.silentgear.starmetal_dust": "星辉粉",
更上来再说吧，这个暂时先不变或者保留原文？

2023-08-04 06:24 UTC, ChuijkYahus commented on projects/1.20/assets/silent-gear/silentgear/lang/zh_cn.json
> +    "trait.silentgear.magmatic": "熔岩",
原版对`熔岩`/`Lava`和`岩浆`/`Magma`有统一
再次建议修改

2023-08-09 10:27 UTC, ChuijkYahus approved these changes

2023-08-11 02:49 UTC, merged