Puzzle 1.20/1.18 汉化提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3493
Opened 2023-07-12 12:15 UTC by Ginsway

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-07-13 22:21 UTC, mamaruo requested changes

2023-07-13 22:21 UTC, mamaruo commented on projects/1.18-fabric/assets/puzzle/puzzle/lang/zh_cn.json
> +	"config.dynamicfps.run_gc_on_unfocus.tooltip": "当 Minecraft窗口 没有焦点时\n运行垃圾收集器\n来释放一些内存",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

垃圾回收器 来自 Microsoft Terminology Search

原文：
- **Run a garbage collector while\nMinecraft is not focused to\nfree up some RAM**
```suggestion
	"config.dynamicfps.run_gc_on_unfocus.tooltip": "Minecraft窗口没有焦点时\n运行垃圾回收器\n来释放一些内存",
```

2023-07-13 22:21 UTC, mamaruo commented on projects/1.18-fabric/assets/puzzle/puzzle/lang/zh_cn.json
> +	"cullleaves.puzzle.option.enabled": "树叶剔除",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

cull 是选择性扑杀动物。游戏内表现如何？剔除有“不显示树叶”的意思。suggestion 是乱写的。

原文：**Cull Leaves**
```suggestion
	"cullleaves.puzzle.option.enabled": "弱化树叶显示",
```

2023-07-13 22:21 UTC, mamaruo commented on projects/1.18-fabric/assets/puzzle/puzzle/lang/zh_cn.json
> +	"lambdabettergrass.option.better_snow.tooltip": "在被雪/苔藓包围的不完整方块中添加雪/覆地苔藓的视觉效果",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

版本差异，覆地苔藓是1.19.4改的

原文：
- **Adds a purely visual snow/moss layer\nto non-full blocks that\nare surrounded by snow/moss**
```suggestion
	"lambdabettergrass.option.better_snow.tooltip": "在被雪/苔藓地毯环绕的不完整方块上添加雪/苔藓地毯的视觉效果",
```

2023-07-16 13:06 UTC, Ginsway commented on projects/1.18-fabric/assets/puzzle/puzzle/lang/zh_cn.json
> +	"cullleaves.puzzle.option.enabled": "树叶剔除",
这里是跟据 https://github.com/TeamMidnightDust/CullLeaves/blob/main/common/src/main/resources/assets/cullleaves/lang/zh_cn.json 来汉化的

2023-07-17 03:40 UTC, Ginsway commented on projects/1.18-fabric/assets/puzzle/puzzle/lang/zh_cn.json
> +	"cullleaves.puzzle.option.enabled": "树叶剔除",
也就是官中

2023-07-18 11:43 UTC, Ginsway commented on projects/1.18-fabric/assets/puzzle/puzzle/lang/zh_cn.json
> +	"cullleaves.puzzle.option.enabled": "树叶剔除",
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/106016532/ffb75126-c791-43c1-b5d0-a3266a0e5e17)
另外钠也是这么翻译的
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/106016532/65f88c39-5c81-46de-a902-bd399209e4f1)

2023-07-18 13:23 UTC, Ginsway commented on projects/1.18-fabric/assets/puzzle/puzzle/lang/zh_cn.json
已解决

2023-07-21 05:55 UTC, mamaruo submitted a review, later dismissed
我对比了“官方翻译”和“本pr”的翻译，结果如下：

### 两者皆有且中文有差异

| **键** | **英文** | **官方翻译** | **本pr** |
|---|---|---|---|
| puzzle.text.update_available | An update is available\! | 更新可用\! | 有更新可用！ |
| puzzle.screen.title | Puzzle Settings | Puzzle 设置 | Puzzle设置 |
| puzzle.page.graphics | Graphics | 图像设置 | 图像 |
| puzzle.page.resources | Resource | 资源设置 | 资源 |
| puzzle.page.performance | Performance | 性能设置 | 性能 |
| puzzle.page.misc | Miscellaneous | 杂项设置 | 杂项 |
| puzzle.option.show_version_info | Show Puzzle version info | 显示 Puzzle 版本信息 | 显示Puzzle版本信息 |
| puzzle.option.unlimited_model_rotations | Unlimited Model Rotations | 无限制模型旋转 | 模型旋转无限制 |
| puzzle.midnightconfig.title | Puzzle Advanced Config | Puzzle 高级设置 | Puzzle高级配置 |

### 只在 官方翻译 中有

| **键** | **英文** | **官方翻译** | **本pr** |
|---|---|---|---|
| puzzle.option.disable_splash_screen_blend | 🚫 | 禁用闪烁标语闪烁 | 🚫 |
| puzzle.option.emissive_textures | 🚫 | 发光纹理 | 🚫 |
| puzzle.option.render_layer_overrides | 🚫 | 渲染层覆盖 | 🚫 |

### 只在 本pr 中有

<details><summary>点击展开/收起</summary>
<p>

| **键** | **英文** | **官方翻译** | **本pr** |
|---|---|---|---|
| puzzle.option.check_for_updates.tooltip | Enables Puzzle's built\-in update checker | 🚫 | 启用Puzzle的内置更新检查器 |
| puzzle.option.show_version_info.tooltip | Show information about the current\\nPuzzle version and update status on\\nthe Title Screen and F3 Menu | 🚫 | 在标题屏幕和F3菜单上\\n显示当前Puzzle版本和更新状态的信息 |
| puzzle.option.resourcepack_splash_screen.tooltip | Enables resourcepacks to change the look\\nof Minecraft's loading/splash\\nscreen using the OptiFine format | 🚫 | 使资源包能够使用OptiFine格式\\n更改Minecraft加载/启动屏幕的外观 |
| puzzle.option.better_splash_screen_blend | Better splash screen logo blending | 🚫 | 更好的闪烁标语与徽标混合 |
| puzzle.option.better_splash_screen_blend.tooltip | Changes the type of blending used\\nby the logo on the splash screen\\nto work better with custom colored logos | 🚫 | 更改启动屏幕上徽标使用的混合类型\\n以便更好地使用自定义颜色的徽标 |
| puzzle.option.unlimited_model_rotations.tooltip | Unlocks full 360° rotation on custom block/item models | 🚫 | 解锁自定义方块/物品模型的 360° 旋转 |
| puzzle.option.bigger_custom_models.tooltip | Increases the limit of\\ncustom block/item model sizes\\nfrom 3x3x3 to 5x5x5 | 🚫 | 将自定义方块/物品模型大小的限制从3x3x3增加到5x5x5 |
| puzzle.midnightconfig.tooltip | Options for advanced users only | 🚫 | 仅适用于高级用户的选项 |
| cullleaves.puzzle.option.enabled | Cull Leaves | 🚫 | 树叶剔除 |
| cullleaves.puzzle.option.enabled.tooltip | Enable the culling of leaves to enhance performance | 🚫 | 启用树叶剔除以提高性能 |
| iris.puzzle.option.enableShaders | Enable Shaders | 🚫 | 启用光影 |
| iris.puzzle.option.enableShaders.tooltip | Whether or not to enable shaderpacks | 🚫 | 是否启用光影包 |
| iris.puzzle.option.open | OPEN | 🚫 | 打开 |
| options.iris.shaderPackSelection.tooltip | Open a screen to select\\nshaderpacks and configure them | 🚫 | 打开界面选择\\n光影包并进行配置 |
| lambdabettergrass.option.mode.tooltip | Makes the sides of\\ngrass blocks connect to\\nadjacent grass blocks | 🚫 | 使草方块的侧面\\n连接到附近的草方块 |
| lambdabettergrass.option.better_snow.tooltip | Adds a purely visual snow/moss layer\\nto non\-full blocks that\\nare surrounded by snow/moss | 🚫 | 在被雪/覆地苔藓包围的不完整方块中添加雪/覆地苔藓的视觉效果 |
| config.dynamicfps.reduce_when_unfocused.tooltip | Reduces Minecraft's FPS when unfocused\\n\(i\.e\. another window is focused or the game is hidden\)\\nto save power and system resources | 🚫 | 在未聚焦时（如另一个窗口聚焦或游戏隐藏）\\n降低Minecraft的FPS\\n以节省电量和系统资源 |
| config.dynamicfps.unfocused_fps.tooltip | The amount of frames per second\\nMinecraft is allowed to\\nrender at while unfocused | 🚫 | 在未聚焦时的帧数上限 |
| config.dynamicfps.restore_when_hovered.tooltip | Whether or not to stop the\\nFPS limiting while Minecraft is previewed\\n\(i\.e\. hovered on task bar or dock\) | 🚫 | 在预览 Minecraft窗口时\\n是否停止 FPS 限制\\n（即悬停在任务栏上） |
| config.dynamicfps.run_gc_on_unfocus.tooltip | Run a garbage collector while\\nMinecraft is not focused to\\nfree up some RAM | 🚫 | Minecraft窗口没有焦点时\\n运行垃圾回收器\\n来释放一些内存 |
| config.dynamicfps.unfocused_volume.tooltip | The volume the game should play\\nsound at while unfocused\\n\(i\.e\. another window is selected\) | 🚫 | 未聚焦时（如选择另一个窗口）\\n游戏的音量大小 |
| config.dynamicfps.hidden_volume.tooltip | The volume the game should play\\nsound at while not visible\\n\(i\.e\. minimized, covered by other windows\\nor on another virtual desktop\) | 🚫 | 在不可见的情况下（如最小化，被其他窗口覆盖或在另一个虚拟桌面上）\\n游戏的音量大小 |
| entity_texture_features.puzzle.emissive_type.brighter | §eBrighter | 🚫 | §e更亮 |
| entity_texture_features.puzzle.emissive_type.default | §6Default | 🚫 | §6默认 |

</p>
</details>

2023-07-21 15:43 UTC, dovisutu commented on projects/1.18-fabric/assets/puzzle/puzzle/lang/zh_cn.json
> +	"puzzle.option.unlimited_model_rotations.tooltip": "解锁自定义方块/物品模型的 360° 旋转",
似乎这里的空格没删？

2023-07-21 15:43 UTC, dovisutu commented on projects/1.18-fabric/assets/puzzle/puzzle/lang/zh_cn.json
> +	"config.dynamicfps.restore_when_hovered.tooltip": "在预览 Minecraft窗口时\n是否停止 FPS 限制\n（即悬停在任务栏上）",
同上。

2023-07-27 12:44 UTC, ChuijkYahus approved these changes

2023-07-28 11:47 UTC, merged