Chaos Awakens 模组翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3501
Opened 2023-07-14 08:29 UTC by ManXiangTAS

- [ ] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [ ] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-07-14 08:38 UTC, nageih commented
标题什么鬼

2023-07-14 08:47 UTC, nageih commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"itemGroup.chaosawakens.blocks": "混沌起源: 方块",
此模组的流行译名是**混沌觉醒**吧，而且格式推荐是混沌觉醒丨方块这样

2023-07-14 08:47 UTC, nageih commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"advancements.chaosawakens.root.description": "看看混沌从你的世界灰烬中诞生！",
全篇标点都是半角，应使用全角

2023-07-14 08:47 UTC, nageih commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"advancements.chaosawakens.shiny_pigs.description": "两种不同的金胡萝卜猪[暂定].",
暂定是什么鬼

2023-07-14 08:47 UTC, nageih commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"item.chaosawakens.amethyst_shovel": "紫水晶铲",
是锹不是铲

2023-07-14 08:47 UTC, nageih commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"advancements.chaosawakens.ruby_armor.title": "如此多的岩浆...",
原文是lava，应翻译成熔岩

2023-07-14 08:47 UTC, nageih commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.netherrack_ruby_ore": "地狱岩红宝石矿石",
下界岩

2023-07-14 08:47 UTC, nageih commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"item.chaosawakens.pig_critter_cage": "笼-猪",
```suggestion
	"item.chaosawakens.pig_critter_cage": "猪笼",
```

2023-07-14 08:47 UTC, nageih commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"item.chaosawakens.miners_dream": "即时挖掘",
与原文不符吧

2023-07-14 08:47 UTC, nageih commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.pink_crystal_flower": "粉色水晶花",
粉红色

2023-07-14 08:47 UTC, nageih commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.daisy": "Daisy",
漏译

2023-07-15 04:47 UTC, mczph commented
连接到#3387有什么特殊的含义吗（）

2023-07-15 04:48 UTC, sea-turtle0 commented
> 连接到#3387有什么特殊的含义吗（）

貌似只是pr提交者弄错了，也没改回来（

2023-07-15 09:10 UTC, luoxueyasha commented
请正确填写检查单（#2539 ），并按照其他PR的格式修改首条回复

2023-07-15 09:11 UTC, nageih commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"tooltip.chaosawakens.dev_item1": "这是一个开发项目！",
```suggestion
	"tooltip.chaosawakens.dev_item1": "这是一个开发物品！",
```

2023-07-15 09:11 UTC, nageih commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"tooltip.chaosawakens.dev_item16": "这是一个开发项目！",
```suggestion
	"tooltip.chaosawakens.dev_item16": "这是一个开发物品！",
```

2023-07-15 09:11 UTC, nageih commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"tooltip.chaosawakens.fossilised_wtf": "这是一个未完成项目",
物品

2023-07-15 09:11 UTC, nageih commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"itemGroup.chaosawakens.blocks": "混沌起源丨方块",
这模组普遍译名是混沌觉醒吧

2023-07-15 09:11 UTC, nageih commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.robo_block_l": "机器人块",
robo感觉可以换个译名，_机器人块_，_机器人台阶_ 感觉好怪，**机械**是不是会好一点

2023-07-15 09:11 UTC, nageih commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.mossy_marble_bricks": "苔大理石砖",
```suggestion
	"block.chaosawakens.mossy_marble_bricks": "覆苔大理石砖",
```

2023-07-15 09:11 UTC, nageih commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.mossy_marble_bricks": "苔大理石砖",
得参考游戏内的形态

2023-07-15 09:12 UTC, nageih commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"item.chaosawakens.platinum_shovel": "铂铲",
```suggestion
	"item.chaosawakens.platinum_shovel": "铂锹",
```

2023-07-15 09:12 UTC, nageih commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"item.chaosawakens.platinum_shovel": "铂铲",
其他的也是

2023-07-15 09:23 UTC, mamaruo commented
/add-mapping chaos-awakens 475414

2023-07-15 09:32 UTC, sea-turtle0 commented
> <!--
> 要勾选下面的复选框，可以将文本[ ]改为[x]，注意别误删前后的空格。
> 务必认真阅读并完成此检查单。如有其他需说明的事项请写在检查单之前。
> 若对检查单有疑惑，请查看Issues列表的 #2539 “检查单”使用说明 & 错误“检查单”使用情况报告
> -->
> 
> - [ ] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
> - [ ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
> - [ ] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
> - [ ] 刷新 PR 的标签/状态，有需要再点击；

你这也没打勾啊（

2023-07-15 09:33 UTC, mamaruo commented
> > * [ ]  我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
> > * [ ]  我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
> > * [ ]  我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
> > * [ ]  刷新 PR 的标签/状态，有需要再点击；
> 
> 你这也没打勾啊（

这我刚加的，你看编辑历史。

2023-07-15 09:34 UTC, sea-turtle0 commented
> > > * [ ]  我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
> > > * [ ]  我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
> > > * [ ]  我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
> > > * [ ]  刷新 PR 的标签/状态，有需要再点击；
> > 
> > 你这也没打勾啊（
> 
> 这我刚加的，你看编辑历史。

az，没事了，我说怎么只改了检查单（

2023-07-15 13:49 UTC, mamaruo requested changes

2023-07-16 13:25 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.fossilised_enderman_netherrack": "生物化石-末影人 (下界岩)",
| **审查级别**   |
|-------------|
| 🔴 严重 / **阻止合并，刻不容缓** |

原文：**Fossilised Enderman (Netherrack)**

全角括号

2023-07-16 13:25 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"death.attack.ignition.item": "%1$s 被烧死在试图攻击 %2$s",
| **审查级别**   |
|-------------|
| 🔴 严重 / **阻止合并，刻不容缓** |

原文：**%1$s was ignited trying to hurt %2$s┃%1$s was ignited while attempting to hurt %2$s**

语序，空格

2023-07-16 13:25 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"misc.chaosawakens.inaccessible_dimension": "这个维度还在开发中",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

原文：**This anthill requires an empty inventory!┃This anthill seems to have not been implemented yet!**
```suggestion
	"misc.chaosawakens.empty_inventory": "进入此维度需要清空物品栏！",
	"misc.chaosawakens.inaccessible_dimension": "这个维度还在开发中！",
```

2023-07-16 13:25 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.rhinestone_pillar": "竖纹莱茵石",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

原文：**Rhinestone Pillar**
```suggestion
	"block.chaosawakens.rhinestone_pillar": "莱茵石柱",
```
其他 pillar 类似

2023-07-16 13:25 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.paeonia": "青色玫瑰",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

原文：**Paeonia**

这不对吧

2023-07-16 13:25 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.termite_infested_ore": "白蚁引诱方块",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

原文：**Red Ant Infested Ore┃Termite Infested Ore**

虫蚀矿石

2023-07-16 13:51 UTC, Slow-Witted-Fish commented
喵？解决问题不关闭 conversation 吗

2023-07-17 03:03 UTC, luoxueyasha commented
如果这篇pr没有与他人合作，请移除检查单里的“Coauthored”信息。

2023-07-17 08:42 UTC, ManXiangTAS commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"item.chaosawakens.pig_critter_cage": "笼-猪",
否决

2023-07-17 08:42 UTC, ManXiangTAS commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.apple_gate_block": "苹果木消失方块",
没做出来呢

2023-07-17 08:43 UTC, ManXiangTAS commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"advancements.chaosawakens.pink_tourmaline_armor.title": "粉红色，但透明！",
否决，觉得更有惊讶的意思

2023-07-17 08:44 UTC, ManXiangTAS commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"advancements.chaosawakens.robo_slayer.description": "杀死过所以种类的机器人。",
否决，添加"混沌觉醒中的"无实际意义

2023-07-17 08:44 UTC, ManXiangTAS commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"advancements.chaosawakens.go_fish.description": "取得过所有种类的鱼。",
同上

2023-07-17 09:01 UTC, ManXiangTAS commented
> 如果这篇pr没有与他人合作，请移除检查单里的“Coauthored”信息。

与别人合作了

2023-07-17 12:38 UTC, Slow-Witted-Fish commented
> 如果这篇pr没有与他人合作，请移除检查单里的“Coauthored”信息。

群里来说了，这个 Coauthored 似乎没起到作用

2023-07-18 07:03 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"dimension.chaosawakens.danger_isles": "不稳定世界",
不接受“沿用”。这是一个词都没对上。

2023-07-18 07:22 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.apple_gate_block": "苹果木消失方块",
看起来是右击进入某个维度的方块，目前右击只会凭空消失，没有什么表现。你这翻译成“消失”方块是否太离谱了点。

2023-07-18 07:26 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.duplication_log": "复制树原木",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

原文：**Duplication Tree Log**
```suggestion
	"block.chaosawakens.duplication_log": "复制原木",
```
后面的类似，一般以 复制木 为词头，不加“树”

2023-07-18 07:32 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.light_gray_terracotta_brick_slab": "亮灰色陶瓦砖台阶",
| **审查级别**   |
|-------------|
| 🔴 严重 / **阻止合并，刻不容缓** |

原文：**Light Blue Terracotta Brick Slab┃Light Gray Terracotta Brick Slab**
```suggestion
	"block.chaosawakens.light_blue_terracotta_brick_slab": "淡蓝色陶瓦砖台阶",
	"block.chaosawakens.light_gray_terracotta_brick_slab": "淡灰色陶瓦砖台阶",
```

2023-07-18 07:36 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.pink_crystal_sapling": "粉红色水晶树树苗",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

原文：**Red Crystal Leaves┃Green Crystal Leaves┃Yellow Crystal Leaves┃Pink Crystal Leaves┃Blue Crystal Leaves┃Orange Crystal Leaves┃Red Crystal Sapling┃Green Crystal Sapling┃Yellow Crystal Sapling┃Blue Crystal Sapling┃Orange Crystal Sapling┃Pink Crystal Sapling**

删掉叠“树”

2023-07-18 07:36 UTC, Cactusstudent commented
注：该Pull Request的协作存在问题，在合并时将**不会**自动添加写在PR信息中的协作。即 `Co-authored-by: hunlingmo <h6l6m6@163.com>`

2023-07-18 07:55 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"entity.chaosawakens.warped_ent": "树妖–诡异树",
| **审查级别**   |
|-------------|
| 🔴 严重 / **阻止合并，刻不容缓** |

原文：**Acacia Ent┃Apple Ent┃Birch Ent┃Cherry Ent┃Crimson Ent┃Dark Oak Ent┃Jungle Ent┃Oak Ent┃Peach Ent┃Skywood Ent┃Spruce Ent┃Warped Ent**

格式不统一，诡异/绯红不是树，是菌

2023-07-18 08:09 UTC, mamaruo requested changes
麻烦你不要resolve未解决的conversation，所有你未按审阅人做修改的conversation原则上都要审阅者来resolve

2023-07-18 08:09 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"item.chaosawakens.tin_lump": "锡锭",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

虽然它的合成上的地位和锭相同，但锭指的是人加工过的具有一定外观规格的金属。lump 是不定形的。结合游戏内纹理。其他 lump 同理

原文：**Lump of Tin**
```suggestion
	"item.chaosawakens.tin_lump": "锡碎块",
```

2023-07-18 08:09 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"item.chaosawakens.tin_boots": "锡制靴子",
| **审查级别**   |
|-------------|
| 🔴 严重 / **阻止合并，刻不容缓** |

原文：**Tin Helmet┃Tin Chestplate┃Tin Leggings┃Tin Boots**
```suggestion
	"item.chaosawakens.tin_helmet": "锡头盔",
	"item.chaosawakens.tin_chestplate": "锡胸甲",
	"item.chaosawakens.tin_leggings": "锡护腿",
	"item.chaosawakens.tin_boots": "锡靴子",
```

2023-07-18 08:09 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"item.chaosawakens.silver_boots": "银制头盔",
| **审查级别**   |
|-------------|
| 🔴 严重 / **阻止合并，刻不容缓** |

原文：**Silver Helmet┃Silver Chestplate┃Silver Leggings┃Silver Boots**

remove 制

2023-07-18 08:48 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"advancements.chaosawakens.carrot_vision.description": "繁殖两种不同品种的胡萝卜猪。",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

原文：**Breed 2 Carrot Pigs.**
```suggestion
	"advancements.chaosawakens.carrot_vision.description": "繁殖一对胡萝卜猪。",
```

2023-07-18 08:53 UTC, mamaruo requested changes

2023-07-18 09:40 UTC, ManXiangTAS commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"tooltip.chaosawakens.fossilised_wtf": "这是一个未完成物品",
已修改

2023-07-18 09:41 UTC, ManXiangTAS commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"advancements.chaosawakens.pink_tourmaline_armor.title": "粉红色，但透明！",
已修改

2023-07-18 09:41 UTC, ManXiangTAS commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"advancements.chaosawakens.lava_eel_armor.title": "一条鳗鱼！",
已修改为:它有一条鳗鱼

2023-07-18 09:42 UTC, ManXiangTAS commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"dimension.chaosawakens.danger_isles": "不稳定世界",
已修改

2023-07-18 09:42 UTC, ManXiangTAS commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"entity.chaosawakens.warped_ent": "树妖–诡异树",
已修改

2023-07-18 09:42 UTC, ManXiangTAS commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"entity.chaosawakens.unstable_ant": "衰变蚂蚁",
已修改为:不稳定的

2023-07-18 09:59 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.random_teleport_block": "随机远程传输块",
你确定不是传送？

2023-07-18 10:08 UTC, mamaruo approved these changes
除了 gate block 那个抽象玩意应该差不多了

2023-07-18 10:16 UTC, ManXiangTAS commented
> 标题什么鬼

麻烦完成您的审查

2023-07-18 13:17 UTC, ChuijkYahus reviewed
仅针对树种名及相关木制品审核

2023-07-18 13:17 UTC, ChuijkYahus commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.stripped_apple_log": "去皮苹果木原木",
```suggestion
	"block.chaosawakens.stripped_apple_log": "去皮苹果原木",
```

2023-07-18 13:17 UTC, ChuijkYahus commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.stripped_cherry_log": "去皮樱桃木原木",
```suggestion
	"block.chaosawakens.stripped_cherry_log": "去皮樱桃原木",
```

2023-07-18 13:17 UTC, ChuijkYahus commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.cherry_planks": "樱桃木木板",
```suggestion
	"block.chaosawakens.cherry_planks": "樱桃木板",
```

2023-07-18 13:17 UTC, ChuijkYahus commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.duplication_log": "复制木原木",
```suggestion
	"block.chaosawakens.duplication_log": "复制原木",
```

2023-07-18 13:17 UTC, ChuijkYahus commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.stripped_dead_duplication_wood": "去皮失活复制木",
```suggestion
	"block.chaosawakens.dead_duplication_log": "失活复制原木",
	"block.chaosawakens.dead_duplication_wood": "失活复制木",
	"block.chaosawakens.stripped_dead_duplication_log": "去皮失活复制原木",
	"block.chaosawakens.stripped_dead_duplication_wood": "去皮失活复制木",
```

2023-07-18 13:17 UTC, ChuijkYahus commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.ginkgo_log": "银杏木原木",
```suggestion
	"block.chaosawakens.ginkgo_log": "银杏原木",
```

2023-07-18 13:17 UTC, ChuijkYahus commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.stripped_ginkgo_log": "去皮银杏木原木",
```suggestion
	"block.chaosawakens.stripped_ginkgo_log": "去皮银杏原木",
```

2023-07-18 13:17 UTC, ChuijkYahus commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.peach_sapling": "桃树苗",
```suggestion
	"block.chaosawakens.peach_sapling": "桃树树苗",
```

2023-07-18 13:17 UTC, ChuijkYahus commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.peach_leaves": "桃树叶",
```suggestion
	"block.chaosawakens.peach_leaves": "桃树树叶",
```

2023-07-18 13:17 UTC, ChuijkYahus commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.peach_leaf_carpet": "桃树叶地毯",
```suggestion
	"block.chaosawakens.peach_leaf_carpet": "桃树树叶地毯",
```

2023-07-18 13:17 UTC, ChuijkYahus commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.skywood_gate_block": "天空木消失方块",
```suggestion
	"block.chaosawakens.skywood_gate_block": "天界木消失方块",
```
上下文不统一

2023-07-18 13:17 UTC, ChuijkYahus commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"item.chaosawakens.skywood_boat": "天空木船",
```suggestion
	"item.chaosawakens.skywood_boat": "天界木船",
```

2023-07-18 13:17 UTC, ChuijkYahus commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.crystal_planks": "水晶木木板",
```suggestion
	"block.chaosawakens.crystal_planks": "水晶木板",
```

2023-07-18 13:17 UTC, ChuijkYahus commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"entity.chaosawakens.warped_ent": "树妖–诡异菌",
请统一格式

2023-07-20 09:46 UTC, mamaruo reviewed
二审 133-684

2023-07-20 09:46 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"dimension.chaosawakens.village_mania": "村庄维度",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

原文：**Village Mania**
```suggestion
	"dimension.chaosawakens.village_mania": "千村之地",
```
```suggestion
	"dimension.chaosawakens.village_mania": "千村万落",
```

2023-07-20 09:46 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"dimension.chaosawakens.mining_paradise": "矿业维度",
| **审查级别**   |
|-------------|
| 🔴 严重 / **阻止合并，刻不容缓** |

原文：**Mining Paradise**
```suggestion
	"dimension.chaosawakens.mining_paradise": "采矿天堂",
```

2023-07-20 09:46 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"death.attack.burns": "%1$s烧毁了",
| **审查级别** |
|--------------|
| ℹ️ 信息 / 不阻止合并  |

原文：**%1$s burned up on the inside**

https://www.dictionary.com/browse/insides

2023-07-20 09:46 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"entity.chaosawakens.screen_shake": "屏幕抖动",
| **审查级别**    |
|--------------|
| ❓疑问 / 需要作者确认 |

原文：**Screen Shake**

这啥？

https://github.com/ChaosAwakens/ChaosAwakens/blob/1.16.5-forge/src/main/java/io/github/chaosawakens/common/entity/nonliving/CAScreenShakeEntity.java

2023-07-20 09:46 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"entity.chaosawakens.explosive_ball": "爆破球",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

具体看游戏内表现

原文：**Thunder Charge┃Explosive Charge**
```suggestion
	"entity.chaosawakens.thunder_ball": "雷电弹",
	"entity.chaosawakens.explosive_ball": "爆炸弹",
```

2023-07-20 09:46 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"entity.chaosawakens.acacia_ent": "树妖-金合欢",
| **审查级别**    |
|--------------|
| ⚪ 轻微 / 不阻止合并但需三思  |

原文：**Acacia Ent**
```suggestion
	"entity.chaosawakens.acacia_ent": "树妖—金合欢树",
```

2023-07-20 09:46 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"enchantment.chaosawakens.ignition.description": "当应用到盔甲上时，攻击者使用的任何东西都会在短时间内受到燃烧效果的影响。",
| **审查级别**   |
|-------------|
| 🔴 严重 / **阻止合并，刻不容缓** |

建议写得不好。

原文：**When applied onto an armor piece, anything that attacks the user will be afflicted with the burns effect for a short period of time.**
```suggestion
	"enchantment.chaosawakens.ignition.description": "穿戴了附了该魔咒的盔甲受到攻击时，攻击者会获得一小会儿的燃烧效果。",
```
```suggestion
	"enchantment.chaosawakens.ignition.description": "可附在盔甲上。穿戴盔甲后，攻击自己的实体都会被施加一小会儿的燃烧效果。",
```

2023-07-20 09:46 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"item.minecraft.tipped_arrow.effect.long_burns": "燃烧之矢",
| **审查级别**   |
|-------------|
| 🔴 严重 / **阻止合并，刻不容缓** |

原文：**Arrow of Paralysis┃Arrow of Paralysis┃Arrow of Burning┃Arrow of Burning**

之箭

2023-07-20 09:46 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"dungeon.chaosawakens.jer.village_cherry_house": "村民 - 樱桃楼",
| **审查级别**    |
|--------------|
| ⚪ 轻微 / 不阻止合并但需三思  |

原文：**Ent Dungeon - Acacia Loot┃Ent Dungeon - Birch Loot┃Ent Dungeon - Crimson Loot┃Ent Dungeon - Dark Oak Loot┃Ent Dungeon - Jungle Loot┃Ent Dungeon - Jungle Trap┃Ent Dungeon - Oak Loot┃Ent Dungeon - Spruce Loot┃Ent Dungeon - Warped Loot┃Wasp Dungeon - Loot┃Giant Wasp Dungeon - Loot┃Village - Cherry House**

建议不加空格

2023-07-21 07:36 UTC, Rinko1231 commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"advancements.chaosawakens.platinum_armor.description": "获得全套铂盔甲。",
考虑到前面玩了银色战车的梗，这个 铂金+时间我有理由怀疑也是白金之星的梗，或许这个成就名里的platinum该译为白金，其他的platinum还是铂。

2023-07-21 07:36 UTC, Rinko1231 commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"advancements.chaosawakens.shiny_cows.description": "繁殖一对金苹果苹果牛。",
```suggestion
	"advancements.chaosawakens.shiny_cows.description": "繁殖一对金苹果牛。",
```

2023-07-21 12:05 UTC, ManXiangTAS commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"advancements.chaosawakens.shiny_cows.description": "繁殖一对金苹果苹果牛。",
金苹果牛那一条改了，考虑到原文以及译名统一，白金时间没有采用

2023-07-21 12:06 UTC, ManXiangTAS commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"advancements.chaosawakens.platinum_armor.description": "获得全套铂盔甲。",
考虑到原文以及译名统一，不采用。

2023-07-22 07:30 UTC, Cyl18 commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"item.minecraft.tipped_arrow.effect.burns": "燃烧之箭",:
```suggestion
	"item.minecraft.tipped_arrow.effect.burns": "燃烧之箭",
```

2023-07-22 09:39 UTC, mamaruo reviewed
二审完毕

2023-07-22 09:39 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.dense_dirt": "密钝泥土",
| **审查级别**    |
|--------------|
| ⚪ 轻微 / 不阻止合并但需三思  |

原文：**Dense Dirt**

钝是什么

2023-07-22 09:39 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"item.chaosawakens.dead_irukandji": "死亡的水母",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

原文：**Dead Irukandji**
```suggestion
	"item.chaosawakens.dead_irukandji": "死亡的伊鲁坎吉水母",
```
https://www.mcmod.cn/item/50296.html

2023-07-22 09:39 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.mobzilla_scale_block": "莫比兹拉鳞片块",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

原文：**Mobzilla Scale Block**
```suggestion
	"block.chaosawakens.mobzilla_scale_block": "莫布斯拉鳞片块",
```

2023-07-22 09:39 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"tooltip.chaosawakens.sunstone": "传说中这是被后羿射下太阳的残骸。",
| **审查级别**    |
|--------------|
| ⚪ 轻微 / 不阻止合并但需三思  |

原文：**Legends say it is the remains of fallen suns from ancient times.**

后羿？

2023-07-22 09:39 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"tooltip.chaosawakens.amethyst": "具有有趣光折射的紫色宝石。",
| **审查级别**    |
|--------------|
| ⚪ 轻微 / 不阻止合并但需三思  |

原文：**Purple gem with interesting light manipulation properties.**

manipulation？

2023-07-22 09:39 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"block.chaosawakens.nest_block": "巢穴块",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

指示其性质的时候用`方块`，粒/锭/块用`块`

原文：**Nest Block**
```suggestion
	"block.chaosawakens.nest_block": "巢穴方块",
```

2023-07-22 09:39 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"item.chaosawakens.irukandji_arrow": "水母箭",
| **审查级别** |
|--------------|
| ℹ️ 信息 / 不阻止合并  |

原文：**Irukandji Arrow**

注意一起改

2023-07-22 09:39 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"item.chaosawakens.prismatic_reaper": "末影收割者",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

原文：**Prismatic Reaper**
```suggestion
	"item.chaosawakens.prismatic_reaper": "末影收割者",
```

prismatic 也不是末影啊

2023-07-22 09:39 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"subtitles.chaosawakens.entity.warped_ent.hurt": "树妖-诡异菌咆哮",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

原文：**Warped Ent roars**
```suggestion
	"subtitles.chaosawakens.entity.warped_ent.hurt": "树妖-诡异菌：咆哮",
```

2023-07-22 09:39 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"subtitles.chaosawakens.entity.dark_oak_ent.hurt": "树妖-深色橡树树：咆哮",
| **审查级别**   |
|-------------|
| 🔴 严重 / **阻止合并，刻不容缓** |

原文：**Dark Oak Ent roars**
```suggestion
	"subtitles.chaosawakens.entity.dark_oak_ent.hurt": "树妖-深色橡树：咆哮",
```

2023-07-22 09:39 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"dungeon.chaosawakens.jer.ent_dungeon.warped_loot": "树妖地牢-诡异战利品",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

原文：**Ent Dungeon - Acacia Loot┃Ent Dungeon - Birch Loot┃Ent Dungeon - Crimson Loot┃Ent Dungeon - Dark Oak Loot┃Ent Dungeon - Jungle Loot┃Ent Dungeon - Jungle Trap┃Ent Dungeon - Oak Loot┃Ent Dungeon - Spruce Loot┃Ent Dungeon - Warped Loot**

加`树`

2023-07-22 09:46 UTC, ManXiangTAS commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"itemGroup.chaosawakens.development": "混沌觉醒丨进度",
已改为提升

2023-07-22 10:25 UTC, mamaruo commented on projects/1.16/assets/chaos-awakens/chaosawakens/lang/zh_cn.json
> +	"tooltip.chaosawakens.amethyst": "具有有趣流明的紫色宝石。",
能与光产生有趣反应的紫色宝石。

2023-07-22 10:38 UTC, mamaruo approved these changes

2023-07-23 12:49 UTC, Cactusstudent approved these changes

2023-07-23 12:49 UTC, merged