神秘农业及其拓展2次修复
CFPAOrg/Minecraft-Mod-Language-Package pull request #3507
Opened 2023-07-15 10:21 UTC by mczph

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

**主要内容**：空格+星辉矿->星辉

2023-07-15 14:45 UTC, Slow-Witted-Fish commented
> **主要内容**：空格+很多种子的名称

空格没必要
另外改一下标题

2023-07-18 10:28 UTC, mczph commented
@Slow-Witted-Fish 这个标题要改成啥（
）

2023-07-19 10:58 UTC, mczph commented
@mamaruo 请求审核（）

2023-07-19 13:59 UTC, mamaruo requested changes

2023-07-19 13:59 UTC, mamaruo commented on projects/1.12.2/assets/mystical-agriculture/mysticalagriculture/lang/zh_cn.lang
> +desc.ma.charm_absorption=每 8 分钟提供 10 个伤害吸收心。
伤害吸收心是什么

2023-07-19 13:59 UTC, mamaruo commented on projects/1.12.2/assets/mystical-agriculture/mysticalagriculture/lang/zh_cn.lang
> +desc.ma.charm_attack_aoe=将你的剑的攻击范围提高到 5x5 。
所有乘号统一成×

2023-07-19 13:59 UTC, mamaruo commented on projects/1.12.2/assets/mystical-agriculture/mysticalagriculture/lang/zh_cn.lang
> +desc.ma.charm_resistance=降低 20% 的伤害。
对它人造成的伤害还是受到的伤害

2023-07-19 13:59 UTC, mamaruo commented on projects/1.12.2/assets/mystical-agriculture/mysticalagriculture/lang/zh_cn.lang
> +desc.ma.charm_triple_shot=让你的弓射 3 箭。
什么射3箭

2023-07-19 13:59 UTC, mamaruo commented on projects/1.12.2/assets/mystical-agriculture/mysticalagriculture/lang/zh_cn.lang
> +desc.tile.ma.glowstone_lamp=一个看起来像是工业制品的荧石灯……在一个魔法模组里？……什么情况？？？\n\n制作这个灯很简单，只需要拿着荧石右键§8神秘机械框架§0就可以得到了。\n\n你随时可以 Shift+ 右键取出荧石，将方块还原。
```suggestion
desc.tile.ma.glowstone_lamp=一个看起来像是工业制品的荧石灯……在一个魔法模组里？……什么情况？？？\n\n制作这个灯很简单，只需要拿着荧石右键§8神秘机械框架§0就可以得到了。\n\n你随时可以 Shift + 右击取出荧石，将方块还原。
```

2023-07-20 00:49 UTC, mczph commented on projects/1.12.2/assets/mystical-agriculture/mysticalagriculture/lang/zh_cn.lang
> +desc.tile.ma.glowstone_lamp=一个看起来像是工业制品的荧石灯……在一个魔法模组里？……什么情况？？？\n\n制作这个灯很简单，只需要拿着荧石右键§8神秘机械框架§0就可以得到了。\n\n你随时可以 Shift+ 右键取出荧石，将方块还原。
此处原文好像更新了，一并修改

2023-07-20 01:16 UTC, mamaruo requested changes
萤石还能改错？

2023-07-20 04:33 UTC, mamaruo approved these changes

2023-07-20 08:38 UTC, Slow-Witted-Fish commented
基本没问题，除了标题

2023-07-21 05:15 UTC, merged