Skyblock Builder 翻译增加
CFPAOrg/Minecraft-Mod-Language-Package pull request #3525
Opened 2023-07-17 04:00 UTC by xyz8848

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2023-07-19 17:53 UTC, mamaruo requested changes

2023-07-19 17:53 UTC, mamaruo commented on projects/1.16/assets/skyblock-builder/skyblockbuilder/lang/zh_cn.json
> +    "skyblockbuilder.command.success.remove_multiple_players": "成功从队伍%s中移除了%s名玩家。",
```suggestion
    "skyblockbuilder.command.success.remove_multiple_players": "成功从队伍%2$s中移除了%1$s名玩家。",
```

2023-07-19 17:53 UTC, mamaruo commented on projects/1.16/assets/skyblock-builder/skyblockbuilder/lang/zh_cn.json
所有的您改为你

2023-07-20 14:38 UTC, mamaruo commented
看一下bot的报错是不是误报

2023-07-30 10:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3525) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3525) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3525) it.</sub>

2023-07-31 04:53 UTC, ChuijkYahus commented on projects/1.16/assets/skyblock-builder/skyblockbuilder/lang/zh_cn.json
> +    "skyblockbuilder.command.success.remove_multiple_players": "成功从队伍%s中移除了%s名玩家。",
这个部分貌似没更新

2023-07-31 05:35 UTC, mamaruo submitted a review, later dismissed
你可以选择是否签署CLA。7月27日前的pr可不签署

2023-08-06 11:03 UTC, Cactusstudent commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

@xyz8848

2023-08-10 03:31 UTC, Cactusstudent approved these changes

2023-08-11 02:49 UTC, merged