提交Bundled delight汉化
CFPAOrg/Minecraft-Mod-Language-Package pull request #3532
Opened 2023-07-17 14:50 UTC by sungas444

- [x ] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x ] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x ] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x ] 刷新 PR 的标签/状态，有需要再点击；

2023-07-18 09:02 UTC, Rinko1231 commented on projects/1.18/bundled-delight/bundledelight/lang/zh_cn.json
> +    "item.bundledelight.carrot_cake_slice": "一块胡萝卜蛋糕",
```suggestion
    "item.bundledelight.carrot_cake_slice": "胡萝卜蛋糕切片",
```

2023-07-18 09:02 UTC, Rinko1231 commented on projects/1.18/bundled-delight/bundledelight/lang/zh_cn.json
> +    "item.bundledelight.carrot_cake_slice": "一块胡萝卜蛋糕",
农夫乐事是xx蛋糕切片

2023-07-20 02:15 UTC, seaseii commented on projects/1.18/bundled-delight/bundledelight/lang/zh_cn.json
> +    "block.bundledelight.black_tea_leaf_crate": "箱装红茶",
红茶 or 红茶叶 ？

2023-07-20 02:49 UTC, seaseii commented
浅看了几眼，需要改正的话记得全文通改

2023-07-20 05:09 UTC, sungas444 commented
> 浅看了几眼，需要改正的话记得全文通改
我感觉不用改啊。正常说话感觉不会说红茶叶，都是直接说红茶的。

2023-07-20 05:15 UTC, seaseii commented
> > 浅看了几眼，需要改正的话记得全文通改
> > 我感觉不用改啊。正常说话感觉不会说红茶叶，都是直接说红茶的。

看原mod内表现了（

2023-07-20 19:01 UTC, mamaruo requested changes
怎么把 assets 文件夹吃了。

2023-07-23 10:41 UTC, ChuijkYahus commented
/mv projects/1.18/bundled-delight/bundledelight/lang projects/1.18/assets/bundled-delight/bundledelight/lang

2023-07-23 10:44 UTC, ChuijkYahus commented
/add-mapping bundled-delight 836984

2023-07-23 10:56 UTC, ChuijkYahus commented on projects/1.18/assets/bundled-delight/bundledelight/lang/zh_cn.json
> +    "block.bundledelight.black_tea_leaf_crate": "箱装红茶",
```suggestion
    "block.bundledelight.black_tea_leaf_crate": "箱装红茶叶",
```
Farmer's Respite/农夫暇事兼容存储方块，名称遵照库内农夫暇事译名

2023-07-23 10:56 UTC, ChuijkYahus commented on projects/1.18/assets/bundled-delight/bundledelight/lang/zh_cn.json
> +    "block.bundledelight.green_tea_leaf_crate": "箱装绿茶",
```suggestion
    "block.bundledelight.green_tea_leaf_crate": "箱装绿茶叶",
```

2023-07-23 10:56 UTC, ChuijkYahus commented on projects/1.18/assets/bundled-delight/bundledelight/lang/zh_cn.json
> +    "block.bundledelight.yellow_tea_leaf_crate": "箱装黄茶",
```suggestion
    "block.bundledelight.yellow_tea_leaf_crate": "箱装黄茶叶",
```

2023-07-23 10:56 UTC, ChuijkYahus commented on projects/1.18/assets/bundled-delight/bundledelight/lang/zh_cn.json
> +    "item.bundledelight.mocha_coffee_cup": "小杯抹茶咖啡",
```suggestion
    "item.bundledelight.mocha_coffee_cup": "小杯摩卡咖啡",
```
可以游戏内看下有没有加抹茶粉

2023-07-23 10:56 UTC, ChuijkYahus commented on projects/1.18/assets/bundled-delight/bundledelight/lang/zh_cn.json
> +    "brewinandchewin.tooltip.dread_nog_swig": "不祥之兆 (10:00)",
```suggestion
    "brewinandchewin.tooltip.dread_nog_glass": "不祥之兆（10:00）",
    "brewinandchewin.tooltip.dread_nog_swig": "不祥之兆（10:00）",
```

2023-07-23 10:56 UTC, ChuijkYahus commented on projects/1.18/assets/bundled-delight/bundledelight/lang/zh_cn.json
> +    "block.bundledelight.adzuki_powder_basket": "箱装红豆粉",
```suggestion
    "block.bundledelight.adzuki_powder_basket": "筐装红豆粉",
```
原文为basket，请注意全文修改

2023-07-29 17:42 UTC, ChuijkYahus commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

@sungas444

2023-07-30 10:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3532) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3532) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3532) it.</sub>

2023-08-04 06:01 UTC, Cactusstudent commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@sungas444

2023-08-10 03:28 UTC, Cactusstudent approved these changes

2023-08-10 03:29 UTC, Cactusstudent commented
- 该提交由于[7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)将被关闭，请知晓。若仍想维护可选择Reopen此提交或重新打开新提交，并查看本提交内的审查意见并进行更改。

@sungas444

2023-08-11 02:10 UTC, closed without merging