提交Sound Physics Remastered翻译即部分其他语言
CFPAOrg/Minecraft-Mod-Language-Package pull request #3551
Opened 2023-07-22 02:45 UTC by flemon-y

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-07-22 02:46 UTC, flemon-y commented
目前该翻译使用ChatGPT和谷歌翻译，如有一些问题或者意见，我尽可能回复以及改正。

2023-07-22 03:38 UTC, dovisutu commented
这模组的源文件是什么语言？如果是英文，就不需要把其他语种的本地化搬过来。

2023-07-22 03:44 UTC, flemon-y commented
> 这模组的源文件是什么语言？如果是英文，就不需要把其他语种的本地化搬过来。

英语

2023-07-22 07:13 UTC, Cyl18 commented
/mv "projects/1.20-fabric/assets/sound_physics_remastered/" "projects/1.20-fabric/assets/sound-physics-remastered/"

2023-07-22 08:35 UTC, Cyl18 commented
路径重了三份

2023-07-22 23:29 UTC, luoxueyasha requested changes

2023-07-22 23:29 UTC, luoxueyasha commented on projects/1.20-fabric/assets/sound-physics-remastered/sound_physics_remastered/sound_physics_remastered/lang/zh_cn.json
> +  "cloth_config.sound_physics_remastered.simple_voice_chat_integration.description": "启用或禁用对SVC的音效.",
```suggestion
  "cloth_config.sound_physics_remastered.simple_voice_chat_integration.description": "启用或禁用对SVC的音效。",
```

![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/2ea80ba9-cd61-4a51-95f6-46384c591ea1)
[模组简体中文翻译规范与指南](https://cfpa.site/TransRules/)
[《标点符号用法》](http://people.ubuntu.com/~happyaron/l10n/GB(T)15834-2011.html)

此类问题请全文通查

2023-07-22 23:29 UTC, luoxueyasha commented on projects/1.20-fabric/assets/sound-physics-remastered/sound_physics_remastered/sound_physics_remastered/lang/zh_cn.json
> +  "cloth_config.sound_physics_remastered.attenuation_factor.description": "根据距离影响声音变得多么安静.较小的值意味着远处的声音更响亮.此设置要求您处于单人游戏模式,或者在服务器上安装了该模组.1.0 是物理上正确的值.",
哦我上帝啊，这句子不顺，有可能。请全文通查。

2023-07-23 10:29 UTC, Cactusstudent requested changes
不审了，作者请注意，本仓库对生硬的机器翻译并不友好。机器也没人这么灵活，所以请慎用

2023-07-23 10:29 UTC, Cactusstudent commented on projects/1.20-fabric/assets/sound-physics-remastered/sound_physics_remastered/sound_physics_remastered/lang/zh_cn.json
> +  "cloth_config.sound_physics_remastered.settings": "物理声效设置",
```suggestion
  "cloth_config.sound_physics_remastered.settings": "Sound Physics设置",
```

2023-07-23 10:29 UTC, Cactusstudent commented on projects/1.20-fabric/assets/sound-physics-remastered/sound_physics_remastered/sound_physics_remastered/lang/zh_cn.json
> +  "cloth_config.sound_physics_remastered.category.reflectivity": "区块反射性",
显然，生草机们不懂原版术语：Block->方块

2023-07-23 10:40 UTC, ManXiangTAS commented
噢，我的上帝啊！居然会有这么蹩脚的翻译，这简直就像萨莉舅妈烤糊了的苹果派一样糟糕！我发誓如果叫托马斯舅舅看见了这个pr，他准会气的用靴子狠狠地踢这个发起者的屁股！

2023-07-23 11:46 UTC, qznfbnj commented
是的，[即便是最熟练的译者，也可能会使用机器翻译的方式来对这些条目进行***初步处理***](https://www.bilibili.com/video/BV1E4411z79u)，但是你得修改并润色啊
我想起我之前准备做这个，也是先机器翻译一遍，结果鸽了，只做了一行（L29），其他还是机器翻译的
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/100760086/2e2e4fc9-0cdf-45cb-8887-ed18d4a606e0)
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/100760086/f480e8cd-32e4-477e-a47c-64ae13f89531)

2023-07-24 00:18 UTC, closed without merging

2023-07-24 00:18 UTC, flemon-y commented
删了吧