[R] 提交 More beautiful plates 模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #3557
Opened 2023-07-23 16:58 UTC by Susanlynna

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2023-07-23 23:45 UTC, dovisutu commented
> 请再次检查以下事项：
> 标题是否正确丨**翻译文件的路径是否正确**丨检查单是否勾选了前三项。

此外，请再次检查**原版术语**。

2023-07-24 04:47 UTC, ChuijkYahus commented on projects/1.19/assets/more-beautiful-plates/morebeautifulplates/lang/zh_cn.json
> +  "block.morebeautifulplates.birch_log_plate": "白桦木原木压力板",
```suggestion
  "block.morebeautifulplates.birch_log_plate": "白桦原木压力板",
```

2023-07-24 04:47 UTC, ChuijkYahus commented on projects/1.19/assets/more-beautiful-plates/morebeautifulplates/lang/zh_cn.json
> +  "block.morebeautifulplates.chiseled_stone_bricks_plate": "錾制石砖压力板",
```suggestion
  "block.morebeautifulplates.chiseled_quartz_block_plate": "雕纹石英块压力板",
  "block.morebeautifulplates.chiseled_red_sandstone_plate": "雕纹红砂岩压力板",
  "block.morebeautifulplates.chiseled_sandstone_plate": "雕纹砂岩压力板",
  "block.morebeautifulplates.chiseled_stone_bricks_plate": "雕纹石砖压力板",
```
如果是以1193或1194翻译的话，此处需要更改

2023-07-24 04:47 UTC, ChuijkYahus commented on projects/1.19/assets/more-beautiful-plates/morebeautifulplates/lang/zh_cn.json
> +  "block.morebeautifulplates.block_of_quartz_plate": "石英压力板",
```suggestion
  "block.morebeautifulplates.block_of_quartz_plate": "石英块压力板",
```

2023-07-24 04:47 UTC, ChuijkYahus commented on projects/1.19/assets/more-beautiful-plates/morebeautifulplates/lang/zh_cn.json
> +  "block.morebeautifulplates.diamond_ore_plate": "钻石矿压力板",
```suggestion
  "block.morebeautifulplates.diamond_ore_plate": "钻石矿石压力板",
```

2023-07-24 04:47 UTC, ChuijkYahus commented on projects/1.19/assets/more-beautiful-plates/morebeautifulplates/lang/zh_cn.json
> +  "block.morebeautifulplates.hay_block_plate": "干草块压力板",
```suggestion
  "block.morebeautifulplates.hay_block_plate": "干草捆压力板",
```
若参照1194版本翻译，则需更改

2023-07-24 04:47 UTC, ChuijkYahus commented on projects/1.19/assets/more-beautiful-plates/morebeautifulplates/lang/zh_cn.json
> +  "block.morebeautifulplates.mycelium_plate": "菌丝压力板",
```suggestion
  "block.morebeautifulplates.mycelium_plate": "菌丝体压力板",
```
若参照1194版本翻译，则需更改

2023-07-24 04:47 UTC, ChuijkYahus commented on projects/1.19/assets/more-beautiful-plates/morebeautifulplates/lang/zh_cn.json
> +  "block.morebeautifulplates.slime_plate": "粘液块压力板",
```suggestion
  "block.morebeautifulplates.slime_plate": "黏液块压力板",
```

2023-07-25 02:23 UTC, Cactusstudent commented on projects/1.19/assets/more-beautiful-plates/morebeautifulplates/lang/zh_cn.json
> +  "block.morebeautifulplates.yellow_shulker_box_plate": "黄色潜影盒压板",
```suggestion
  "block.morebeautifulplates.yellow_shulker_box_plate": "黄色潜影盒压力板",
```

2023-07-25 02:23 UTC, Cactusstudent commented on projects/1.19/assets/more-beautiful-plates/morebeautifulplates/lang/zh_cn.json
> +  "block.morebeautifulplates.lapis_ore_plate": "青金石矿压力板",
```suggestion
  "block.morebeautifulplates.lapis_ore_plate": "青金石矿石压力板",
```

2023-07-27 07:05 UTC, mamaruo requested changes
去 bot 给的 diff 看看，原版术语都没整明白

2023-07-30 10:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3557) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3557) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3557) it.</sub>

2023-08-01 07:32 UTC, dovisutu commented
- 7+7时限进入第一阶段。从该评论发出的时间开始计时。
请注意查收审核信息，并及时做出相应更改，或说明不应如此更改的理由。

ping @Susanlynna

2023-08-07 09:39 UTC, Cactusstudent commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@Susanlynna

2023-08-07 09:48 UTC, Cactusstudent approved these changes

2023-08-10 11:06 UTC, dovisutu commented
~结果点错了~
我感觉没什么问题了，但是github限制，approve自己的更改没有用（

2023-08-12 11:02 UTC, mamaruo requested changes
压力**版**？
请pr作者关注审阅意见。

2023-08-14 06:35 UTC, Cactusstudent reviewed
二阶段了，直接应用确定性意见，也都是些原版术语的

2023-08-14 06:35 UTC, Cactusstudent commented on projects/1.19/assets/more-beautiful-plates/morebeautifulplates/lang/zh_cn.json
> +  "block.morebeautifulplates.acacia_log_plate": "金合欢原木压力版",
```suggestion
  "block.morebeautifulplates.acacia_log_plate": "金合欢原木压力板",
```

2023-08-15 07:34 UTC, Cactusstudent submitted a review, later dismissed
应该没啥问题，术语的组合

2023-08-26 15:22 UTC, mamaruo approved these changes

2023-08-26 15:22 UTC, merged