Oil Refinery 翻译修正
CFPAOrg/Minecraft-Mod-Language-Package pull request #3566
Opened 2023-07-25 06:54 UTC by xiaohoa232

由 CFPA-Helper 提交。
作者已阅读贡献指南并同意 CC 协议。

2023-07-25 13:28 UTC, luoxueyasha requested changes

2023-07-25 13:28 UTC, luoxueyasha commented on projects/1.19/assets/oil-refinery/oil_refinery/lang/zh_cn.json
> +  "block.oil_refinery.tarmac": "柏油路",
是`柏油路`还是`铺路柏油`？

2023-07-25 14:01 UTC, Slow-Witted-Fish commented
请加群以等侍进一步通知 → 630943368

2023-07-25 14:36 UTC, xiaohoa232 commented on projects/1.19/assets/oil-refinery/oil_refinery/lang/zh_cn.json
> +  "block.oil_refinery.active_distiller": "AStil",
> 物品合成方式以及用途？

除了astil，都可以从原油分馏出来

2023-07-25 14:37 UTC, xiaohoa232 commented on projects/1.19/assets/oil-refinery/oil_refinery/lang/zh_cn.json
> +  "block.oil_refinery.fractioning_casing": "分馏塔壳体",
机翻是叫套管，不过我觉得可以叫壳体或者外壳

2023-07-25 14:51 UTC, xiaohoa232 commented on projects/1.19/assets/oil-refinery/oil_refinery/lang/zh_cn.json
> +  "block.oil_refinery.tarmac": "柏油路",
我不确定应该叫什么

2023-07-25 23:15 UTC, luoxueyasha commented on projects/1.19/assets/oil-refinery/oil_refinery/lang/zh_cn.json
> +  "block.oil_refinery.active_distiller": "AStil",
那`AStill`的合成方式、用途、贴图与模型？

2023-07-25 23:15 UTC, luoxueyasha commented on projects/1.19/assets/oil-refinery/oil_refinery/lang/zh_cn.json
> +  "block.oil_refinery.tarmac": "柏油路",
截图或贴图？

2023-07-25 23:26 UTC, luoxueyasha commented on projects/1.19/assets/oil-refinery/oil_refinery/lang/zh_cn.json
> +  "block.oil_refinery.fractioning_casing": "分馏塔壳体",
有截图和用途吗

2023-07-30 10:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3566) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3566) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3566) it.</sub>

2023-08-01 05:34 UTC, luoxueyasha commented
@xiaohoa232 
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

2023-08-15 07:22 UTC, closed without merging