Mine Cells翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3572
Opened 2023-07-27 10:43 UTC by seaseii

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-07-27 10:46 UTC, seaseii commented
> System.InvalidOperationException: The requested operation requires an element of type 'String', but the target element has type 'Array'.
>    at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
>    at System.Text.Json.JsonDocument.GetString(Int32 index, JsonTokenType expectedType)
>    at CFPABot.DiffEngine.LangFile.<>c.<LoadJson>b__3_1(JsonProperty o) in /src/CFPABot/DiffEngine/LangFile.cs:line 41
>    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
>    at System.Linq.Enumerable.DistinctByIterator[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)+MoveNext()
>    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
>    at CFPABot.DiffEngine.LangFile.LoadJson(String content) in /src/CFPABot/DiffEngine/LangFile.cs:line 38
>    at CFPABot.DiffEngine.LangFile.FromString(String content, LangFileType langFileType) in /src/CFPABot/DiffEngine/LangFile.cs:line 28
>    at CFPABot.DiffEngine.LangFileFetcher.FromPR(Int32 prid, List`1 outExceptions) in /src/CFPABot/DiffEngine/LangFileFetcher.cs:line 31

这是什么玩意儿（

2023-07-27 10:47 UTC, seaseii commented
> ℹ 无法找到 `minecells` 的 Mod Domain。这很可能是因为 CurseForge API 没有返回这个模组的数据。
> ⚠ Mod Domain 验证失败：Value cannot be null. (Parameter 'source')
> ℹ minecells-1.19 语言文件验证通过。

我还以为我的CF项目名称填错了（

2023-08-05 07:22 UTC, DrIceTea123 requested changes

2023-08-05 07:22 UTC, DrIceTea123 commented on projects/1.19/assets/minecells/minecells/lang/zh_cn.json
> +    "chat.minecells.version_mismatch.promenade": "-重置”minecells:promenade“维度",
这里引号反了？

2023-08-06 11:08 UTC, Cactusstudent commented on projects/1.19/assets/minecells/minecells/lang/zh_cn.json
> +    "item.minecells.health_flask.tooltip": "回复%s颗心，并消除流血和中毒效果",
```suggestion
    "item.minecells.health_flask.tooltip": "回复%s颗红心，并消除流血和中毒效果",
```

2023-08-08 13:12 UTC, seaseii commented on projects/1.19/assets/minecells/minecells/lang/zh_cn.json
> +    "block.minecells.putrid_boards": "腐烂原木",
啊，容我看一下
我记得我翻这 Mod 时是开着游戏翻的，应该是吧（）

2023-08-08 13:19 UTC, seaseii commented on projects/1.19/assets/minecells/minecells/lang/zh_cn.json
> +    "block.minecells.putrid_boards": "腐烂木材板",
我傻了，应该是我看错了（
（然后还成功的理解错了T A T）

2023-08-10 03:28 UTC, merged