The Binding Of Isaac | Useful items 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3574
Opened 2023-07-27 11:42 UTC by 502y

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2023-07-28 02:56 UTC, ZHAY10086 commented on projects/1.19/assets/the-binding-of-isaac-by-suzu/tboi_suzu/lang/zh_cn.json
> +  "subtitles.item.holy_mantle": "神圣屏障破碎",
```suggestion
  "subtitles.item.holy_mantle": "神圣屏障：破碎",
```

2023-07-30 10:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3574) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3574) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3574) it.</sub>

2023-08-01 00:25 UTC, luoxueyasha requested changes
怎么又一个MCR模组（望天

2023-08-01 00:25 UTC, luoxueyasha commented on projects/1.19/assets/the-binding-of-isaac-by-suzu/tboi_suzu/lang/zh_cn.json
> +  "entity.tboi_suzu.blue_baby": "???",
```suggestion
  "entity.tboi_suzu.blue_baby": "？？？",
```
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/e98f74a8-dd8b-4e66-8e53-c8e7e58d3b81)
此问题请全文通查
除非小蓝人名字真的存在显示上的问题，否则绝大多数情况下全角字符比半角字符效果更好

2023-08-01 00:47 UTC, 502y commented on projects/1.19/assets/the-binding-of-isaac-by-suzu/tboi_suzu/lang/zh_cn.json
> +  "entity.tboi_suzu.blue_baby": "???",
根据以撒游戏内表现、解包文件及中文wiki规定，小蓝人的名字使用半角问号。

2023-08-01 01:29 UTC, luoxueyasha commented
/sort-keys projects/1.19/assets/the-binding-of-isaac-by-suzu/tboi_suzu/lang/en_us.json

2023-08-01 01:30 UTC, luoxueyasha commented
/sort-keys projects/1.19/assets/the-binding-of-isaac-by-suzu/tboi_suzu/lang/zh_cn.json

2023-08-01 01:40 UTC, luoxueyasha requested changes

2023-08-01 01:40 UTC, luoxueyasha commented on projects/1.19/assets/the-binding-of-isaac-by-suzu/tboi_suzu/lang/zh_cn.json
> +  "block.tboi_suzu.angel_chest": "永恒箱子",
和天使房箱子的区别？（该不会是作者英文名填漏了吧

2023-08-01 01:40 UTC, luoxueyasha commented on projects/1.19/assets/the-binding-of-isaac-by-suzu/tboi_suzu/lang/zh_cn.json
> +  "block.tboi_suzu.angel_chest": "永恒箱子",
`箱子`类方块和原版`箱子`是否存在区别？

2023-08-01 01:40 UTC, luoxueyasha commented on projects/1.19/assets/the-binding-of-isaac-by-suzu/tboi_suzu/lang/zh_cn.json
> +  "effect.tboi_suzu.angels_blessing": "天使：祝福",
```suggestion
  "effect.tboi_suzu.angels_blessing": "天使祝福",
```
具体效果是？

2023-08-01 01:40 UTC, luoxueyasha commented on projects/1.19/assets/the-binding-of-isaac-by-suzu/tboi_suzu/lang/zh_cn.json
> +  "key.tboi_suzu.tears_shot": "Tears Shot",
未翻译

2023-08-01 01:40 UTC, luoxueyasha commented on projects/1.19/assets/the-binding-of-isaac-by-suzu/tboi_suzu/lang/zh_cn.json
> +  "itemGroup.tabsoundtrack": "原声集",
上方soundtrack被翻译为`原声带`

2023-08-01 01:40 UTC, luoxueyasha commented on projects/1.19/assets/the-binding-of-isaac-by-suzu/tboi_suzu/lang/zh_cn.json
> +  "itemGroup.tabbombs": "炸弹",
游戏内效果？怀疑是创造模式物品栏

2023-08-01 01:42 UTC, 502y commented on projects/1.19/assets/the-binding-of-isaac-by-suzu/tboi_suzu/lang/zh_cn.json
> +  "block.tboi_suzu.angel_chest": "永恒箱子",
完全不同，用的是以撒的模型，逻辑也不一样，但是它就叫这个

2023-08-01 01:43 UTC, 502y commented on projects/1.19/assets/the-binding-of-isaac-by-suzu/tboi_suzu/lang/zh_cn.json
> +  "effect.tboi_suzu.angels_blessing": "天使：祝福",
不知道，游戏内未出现，和其他一部分key一样

2023-08-01 01:44 UTC, 502y commented on projects/1.19/assets/the-binding-of-isaac-by-suzu/tboi_suzu/lang/zh_cn.json
> +  "itemGroup.tabbombs": "炸弹",
确实是创造模式物品栏，里面确实只有炸弹

2023-08-01 01:45 UTC, 502y commented on projects/1.19/assets/the-binding-of-isaac-by-suzu/tboi_suzu/lang/zh_cn.json
> +  "block.tboi_suzu.angel_chest": "永恒箱子",
天使房的箱子就是白箱子

2023-08-01 01:46 UTC, 502y commented on projects/1.19/assets/the-binding-of-isaac-by-suzu/tboi_suzu/lang/zh_cn.json
> +  "itemGroup.tabsoundtrack": "原声集",
统一根据wiki修改为原声集

2023-08-01 02:00 UTC, 502y commented on projects/1.19/assets/the-binding-of-isaac-by-suzu/tboi_suzu/lang/zh_cn.json
> +  "key.tboi_suzu.tears_shot": "Tears Shot",
游戏内未出现，猜测翻译为泪弹射击

2023-08-01 03:54 UTC, luoxueyasha commented on projects/1.19/assets/the-binding-of-isaac-by-suzu/tboi_suzu/lang/zh_cn.json
> +  "key.tboi_suzu.tears_shot": "Tears Shot",
可以看看是不是在按键编辑界面

2023-08-01 03:56 UTC, luoxueyasha commented on projects/1.19/assets/the-binding-of-isaac-by-suzu/tboi_suzu/lang/zh_cn.json
> +  "itemGroup.tabbombs": "炸弹",
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/3568a43d-90b8-40e3-9671-efba51943b4e)
```suggestion
  "itemGroup.tabbombs": "以撒的结合道具丨炸弹",
```
最好进行这样的修改，模组名翻译请自行定夺

2023-08-01 04:11 UTC, 502y commented on projects/1.19/assets/the-binding-of-isaac-by-suzu/tboi_suzu/lang/zh_cn.json
> +  "key.tboi_suzu.tears_shot": "Tears Shot",
模组没有按键绑定和设置

2023-08-01 04:16 UTC, luoxueyasha commented on projects/1.19/assets/the-binding-of-isaac-by-suzu/tboi_suzu/lang/zh_cn.json
> +  "key.tboi_suzu.tears_shot": "Tears Shot",
那就先这样吧（

2023-08-01 04:19 UTC, 502y commented on projects/1.19/assets/the-binding-of-isaac-by-suzu/tboi_suzu/lang/zh_cn.json
> +  "itemGroup.tabbombs": "炸弹",
嗯...样例带模组名，这个原文不带，但是改了

2023-08-01 04:43 UTC, luoxueyasha approved these changes
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/f409a108-9ee4-49bd-81bb-e1ce8e810bfa)

2023-08-04 02:07 UTC, merged