epic samurais 模组汉化提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3586
Opened 2023-07-29 12:14 UTC by maxinglo

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [x] 刷新 PR 的标签/状态，有需要再点击；

2023-07-29 12:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3586) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3586) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3586) it.</sub>

2023-07-29 19:20 UTC, ChuijkYahus commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.netherite_samurai_leggings": "下界合金护腿",
```suggestion
    "item.epicsamurai.netherite_samurai_chestplate": "下界合金武士胸甲",
    "item.epicsamurai.netherite_samurai_leggings": "下界合金武士护腿",
```

2023-07-29 19:20 UTC, ChuijkYahus commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.green_samurai_boots": "玉制武士靴",
这个要不还是和铁、金、银一样不加`制`？

2023-07-29 19:20 UTC, ChuijkYahus commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.oni_spawn_egg": "生成鬼怪物蛋 [WIP]",
```suggestion
    "item.epicsamurai.akaname_spawn_egg": "垢尝刷怪蛋",
    "item.epicsamurai.enenra_spawn_egg": "烟烟罗刷怪蛋",
    "item.epicsamurai.oni_spawn_egg": "鬼刷怪蛋",
```
根据原文修改

2023-07-29 19:20 UTC, ChuijkYahus commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.onyx": "玛瑙",
```suggestion
    "item.epicsamurai.onyx": "缟玛瑙",
```
请全文通查

2023-07-29 19:20 UTC, ChuijkYahus commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.quartz_ingot": "石英涂层钢锭",
```suggestion
    "item.epicsamurai.amethyst_ingot": "紫水晶覆层钢锭",
    "item.epicsamurai.quartz_ingot": "石英覆层钢锭",
```
仅建议

2023-07-29 19:20 UTC, ChuijkYahus commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.shuriken": "飞镖",
```suggestion
    "item.epicsamurai.shuriken": "手里剑",
```

2023-07-29 19:20 UTC, ChuijkYahus commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.steel_boots": "钢武士靴",
```suggestion
    "item.epicsamurai.steel_helmet": "钢头盔",
    "item.epicsamurai.steel_chestplate": "钢胸甲",
    "item.epicsamurai.steel_leggings": "钢护腿",
    "item.epicsamurai.steel_boots": "钢靴子",
```
仅根据原文判断，还是要在游戏内实测
同时推荐所有的`武士靴`都改为`武士靴子`

2023-07-29 19:20 UTC, ChuijkYahus commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.tyr_samurai_boots": "战神泰勒武士靴子",
```suggestion
    "item.epicsamurai.tyr_samurai_helmet": "战神提尔武士头盔",
    "item.epicsamurai.tyr_samurai_chestplate": "战神提尔武士胸甲",
    "item.epicsamurai.tyr_samurai_leggings": "战神提尔武士护腿",
    "item.epicsamurai.tyr_samurai_boots": "战神提尔武士靴子",
```
根据FAA官库

2023-07-29 19:20 UTC, ChuijkYahus commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.draco_samurai_boots": "天龙神秘武士靴子",
可以在游戏里看下是不是武士系列的外形（虽然应该是的）

2023-07-29 19:20 UTC, ChuijkYahus commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "block.epicsamurai.jade_block": "玉石块",
```suggestion
    "block.epicsamurai.jade_block": "玉块",
```

2023-07-29 19:20 UTC, ChuijkYahus commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "tooltip.epicsamurai.brass_helmet.summary": "§8按住【§7Shift§8】查看详情",
```suggestion
    "tooltip.epicsamurai.brass_helmet.summary": "§8按住[§7Shift§8]查看详情",
```

2023-07-29 19:20 UTC, ChuijkYahus commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "tooltip.epicsamurai.shuriken_damage": "攻击距离：6格",
```suggestion
    "tooltip.epicsamurai.kunai_damage": " 6 远程伤害",
    "tooltip.epicsamurai.shuriken_damage": " 6 远程伤害",
```

2023-07-29 19:20 UTC, ChuijkYahus commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "block.epicsamurai.deepslate_onyx_ore": "深板岩玛瑙矿",
```suggestion
    "block.epicsamurai.deepslate_ruby_ore": "深层红宝石矿石",
    "block.epicsamurai.aquamarine_ore": "海蓝宝石矿石",
    "block.epicsamurai.deepslate_aquamarine_ore": "深层海蓝宝石矿石",
    "block.epicsamurai.silver_ore": "银矿石",
    "block.epicsamurai.deepslate_silver_ore": "深层银矿石",
    "block.epicsamurai.jade_ore": "玉矿石",
    "block.epicsamurai.deepslate_jade_ore": "深层玉矿石",
    "block.epicsamurai.onyx_ore": "缟玛瑙矿石",
    "block.epicsamurai.deepslate_onyx_ore": "深层缟玛瑙矿石",
```

2023-07-29 19:20 UTC, ChuijkYahus commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.oni_maask": "般若面具",
这个和原文貌似不一样？

2023-07-29 19:20 UTC, ChuijkYahus commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.brass_repair_kit": "机械武士铠甲维修构件",
```suggestion
    "item.epicsamurai.brass_repair_kit": "机械武士盔甲维修构件",
```

2023-07-30 01:37 UTC, maxinglo commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.oni_maask": "般若面具",
般若之面（般若の面），又简称为般若或般若面，是一种使用于日本能乐的能面造型。
这种面具外型是一个有角的、嘴巴张得很大且皱眉头的鬼女，其代表的意思是遭受忌妒与怨恨缠身而堕入魔道的女子。般若虽然看起来比较丑，但是不同的般若也有好看的。
--来自维基百科
这是个日本武士模组，所以我觉得在这里oni mask翻译成般若面具比较合适。

2023-07-30 01:38 UTC, maxinglo commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.draco_samurai_boots": "天龙神秘武士靴子",
在游戏中暂无对应的物品

2023-07-30 01:56 UTC, maxinglo commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.green_samurai_boots": "玉制武士靴",
那读起来有点奇怪，要不然jade翻译成翡翠？

2023-07-30 04:49 UTC, ChuijkYahus commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.draco_samurai_boots": "天龙神秘武士靴子",
需安装[FAA](https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus)

2023-07-30 04:50 UTC, ChuijkYahus commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.oni_maask": "般若面具",
但是般若不是hannya嘛
不过这个还是等更了解的人来再看

2023-07-30 04:50 UTC, ChuijkYahus commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.steel_boots": "钢武士靴",
注意修改

2023-07-30 05:42 UTC, luoxueyasha requested changes

2023-07-30 05:42 UTC, luoxueyasha commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.straw_hat": "草帽",
是`草帽`还是`斗笠`？

2023-07-30 05:42 UTC, luoxueyasha commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.onyx": "缟玛瑙",
上文中`onyx`对应的是`玛瑙`，请视情况全文统一

2023-07-30 05:42 UTC, luoxueyasha commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.katana": "武士刀",
是`打刀`还是`太刀`？

2023-07-30 05:42 UTC, luoxueyasha commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.kama": "忍者镰刀",
怎么确定`忍者`这部分的？

2023-07-30 05:42 UTC, luoxueyasha commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.sai": "十手",
截图？`さい`不是钗吗

2023-07-30 05:42 UTC, luoxueyasha commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.oni_maask": "般若面具",
原文带WIP，为何不保留？

2023-07-30 05:42 UTC, luoxueyasha commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "tooltip.epicsamurai.throwable": "可扔出的物品：",
```suggestion
    "tooltip.epicsamurai.throwable": "可投掷的物品：",
```

2023-07-30 06:09 UTC, maxinglo commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.sai": "十手",
翻译有：十手 叉 钗 铁尺 --来自百科

2023-07-30 06:12 UTC, maxinglo commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.kama": "忍者镰刀",
全篇为日本武士背景，并且游戏中该物品不具有收获作物的功能。

2023-07-30 06:13 UTC, maxinglo commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.oni_maask": "般若面具",
另一位审查人员认为不需要，并且我是第一次提交汉化，因此遵循审查人员建议。

2023-07-30 06:20 UTC, maxinglo commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.straw_hat": "草帽",
根据我找到的资料来看，有的说斗笠是草帽的俗称
https://zhuanlan.zhihu.com/p/39750722?utm_id=0
有的认为斗笠为竹子编织
https://zh-yue.wikipedia.org/wiki/%E6%96%97%E7%AC%A0
而游戏中该物品的配方使用小麦制作，故翻译为草帽。

2023-07-30 06:25 UTC, luoxueyasha commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.kama": "忍者镰刀",
我不认为需要加入`忍者`进行补充或强调武器的部分
而且古代大多是农民军，使用镰刀（长或短）作为武器参战很常见
```suggestion
    "item.epicsamurai.kama": "镰刀",
```

2023-07-30 06:31 UTC, maxinglo commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.katana": "武士刀",
**Katana**是**打刀**的一种，但不一定是**太刀**。因此使用更泛的翻译**武士刀**

2023-07-30 06:34 UTC, luoxueyasha commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.straw_hat": "草帽",
草帽可以是`牛仔帽`等其他帽种，不够贴切。
`笠の材質は檜板・竹・藺草・菅製で、`（`笠`的材质由扁柏木版、竹子、灯芯草、薹草制成，）（[笠 - Wikipedia](https://ja.wikipedia.org/wiki/%E7%AC%A0)）
不仅如此，我国也有使用秸秆、麦秆等编织斗笠的习惯。
个人认为`笠`指这种尖帽帽型，而非其材质。

2023-07-30 06:38 UTC, maxinglo commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.onyx": "缟玛瑙",
在[dict.mcmod.cn](dict.mcmod.cn)中，无特殊前缀和特定场景的翻译为缟玛瑙，因此全文统一为缟玛瑙。

2023-07-30 06:44 UTC, luoxueyasha commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.sai": "十手",
`十手`（实手）和`铁尺`（笔架叉）是两个东西。
1. 十手往往一侧有短叉且靠近主刃；铁尺则是两侧均有靠外的叉。
2. 十手和铁尺的使用方法、格斗技术都有所不同，其中区别最大的是十手是单手棍、铁尺是一对单手叉。
`十手のような形をしたものが多いが、中には卍形のまんじ釵と呼ばれるものもある。見た目からよく十手と見誤られる事がある。`（[釵 - Wikipedia](https://ja.wikipedia.org/wiki/%E9%87%B5)）

2023-07-30 06:45 UTC, luoxueyasha commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.oni_maask": "般若面具",
```suggestion
    "item.epicsamurai.oni_maask": "般若面具 - WIP",
```
```suggestion
    "item.epicsamurai.oni_maask": "般若面具 - 开发中",
```

2023-07-30 06:46 UTC, maxinglo commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.oni_maask": "般若面具",
确实翻译的不对，应该翻译为魔鬼之面。般若之面为日本能剧道具，而游戏中该物品为oni的掉落物。

2023-07-30 06:50 UTC, luoxueyasha commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.oni_maask": "般若面具",
`般若面具`我认为无不妥，和Chuijk沟通过了

2023-07-30 06:55 UTC, maxinglo commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.draco_samurai_boots": "天龙神秘武士靴子",
是武士系列的外形

2023-07-30 06:57 UTC, luoxueyasha requested changes

2023-07-30 06:57 UTC, luoxueyasha commented on projects/1.18/assets/epic-samurais/epicsamurai/lang/zh_cn.json
> +    "item.epicsamurai.oni_maask": "般若面具 - 开发中",
```suggestion
    "item.epicsamurai.oni_maask": "厉鬼面具 - 开发中",
```
仔细看了一下，`Oni Mask`还真不是般若面具，般若是女鬼。（打脸了
同理，可以考虑将上方的`Oni`也翻译作`厉鬼`，日语里`鬼`这个形象是一种高大严厉的形象。

2023-07-30 07:04 UTC, luoxueyasha approved these changes
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/059e24be-feb4-4876-ac12-2c985bd5adef)

2023-08-01 01:55 UTC, merged