Silent Gems 翻译更新与提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3587
Opened 2023-07-29 18:54 UTC by ChuijkYahus

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

同系列模组PR #3471

2023-08-01 04:49 UTC, Cactusstudent commented on projects/1.18/assets/silents-gems/silentgems/lang/zh_cn.json
> +  "gem.silentgems.alexandrite": "变石",
这里游戏内是是啥个样子

2023-08-01 04:49 UTC, Cactusstudent commented on projects/1.18/assets/silents-gems/silentgems/lang/zh_cn.json
> +  "gem.silentgems.heliodor": "金绿柱石",
这里其实两个名字应该都有，这里的更改原因？

2023-08-01 04:54 UTC, ChuijkYahus commented on projects/1.18/assets/silents-gems/silentgems/lang/zh_cn.json
> +  "gem.silentgems.heliodor": "金绿柱石",
算是常用点的矿物名？
~~看的这个https://www.bilibili.com/video/BV1sX4y1E7Ab~~

2023-08-01 04:56 UTC, ChuijkYahus commented on projects/1.18/assets/silents-gems/silentgems/lang/zh_cn.json
> +  "gem.silentgems.alexandrite": "变石",
![图片](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/127f2cde-3a03-44be-a430-e9ccaeccf36f)
https://www.bilibili.com/video/BV1sX4y1E7Ab 10:42

2023-08-04 06:25 UTC, Cactusstudent commented on projects/1.18/assets/silents-gems/silentgems/lang/zh_cn.json
> +  "gem.silentgems.alexandrite": "变石",
挺好

2023-08-04 06:25 UTC, Cactusstudent approved these changes

2023-08-05 06:37 UTC, Cactusstudent commented on projects/1.18/assets/silents-gems/silentgems/lang/zh_cn.json
> +  "misc.silentgems.harvestLevel": "挖掘等级：%d（%s）",
hmm，这地方是采掘还是挖掘，得对下本体

2023-08-05 07:24 UTC, DrIceTea123 requested changes

2023-08-05 07:24 UTC, DrIceTea123 commented on projects/1.18/assets/silents-gems/silentgems/lang/zh_cn.json
>    "item.silentgems.lolinomicon": "Lolinomicon",
漏译吗？

2023-08-05 07:47 UTC, Cactusstudent commented on projects/1.18/assets/silents-gems/silentgems/lang/zh_cn.json
>    "item.silentgems.lolinomicon": "Lolinomicon",
游戏内体现为一本粉色的书，没有配方，用处不详，不翻译了

2023-08-05 07:48 UTC, ChuijkYahus commented on projects/1.18/assets/silents-gems/silentgems/lang/zh_cn.json
>    "item.silentgems.lolinomicon": "Lolinomicon",
游戏内没有合成表和用途，材质是个粉色的书
就很怪
~~萝莉宝典~~

2023-08-05 07:48 UTC, Cactusstudent approved these changes

2023-08-05 12:51 UTC, DrIceTea123 approved these changes

2023-08-06 10:41 UTC, merged