Maturi Delight翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3588
Opened 2023-07-30 07:24 UTC by seaseii

2023-07-30 08:29 UTC, Cactusstudent commented
请一并提交英语语言文件

2023-07-30 09:26 UTC, ChuijkYahus commented on projects/1.20/assets/maturi-delight/maturidelight/lang/zh_cn.json
> +    "item.maturidelight.suspicious_item": "这个章鱼烧上放了什么东西……",
```suggestion
    "item.maturidelight.suspicious_item": "这个章鱼烧里貌似加了什么东西……",
```
纯意译

2023-07-30 09:35 UTC, luoxueyasha requested changes

2023-07-30 09:35 UTC, luoxueyasha commented on projects/1.20/assets/maturi-delight/maturidelight/lang/zh_cn.json
> +    "block.maturidelight.takoyaki_maker": "章鱼烧器",
某宝一般叫`章鱼烧机`或`章鱼小丸子机`

2023-07-30 09:35 UTC, luoxueyasha commented on projects/1.20/assets/maturi-delight/maturidelight/lang/zh_cn.json
> +    "itemGroup.maturidelight": "祭祀乐事",
```suggestion
    "itemGroup.maturidelight": "祭典乐事",
```
全文通查

2023-07-30 09:35 UTC, luoxueyasha commented on projects/1.20/assets/maturi-delight/maturidelight/lang/zh_cn.json
> +    "advancements.maturidelight.root.description": "认识祭祀活动的食物！",
```suggestion
    "advancements.maturidelight.root.description": "来一起了解祭典上的食物吧！",
```
经典的`～学ぼう`系，常见于各类教程视频标题

2023-07-30 09:35 UTC, luoxueyasha commented on projects/1.20/assets/maturi-delight/maturidelight/lang/zh_cn.json
> +    "advancements.maturidelight.extra_topping.title": "添加调料",
```suggestion
    "advancements.maturidelight.extra_topping.title": "添加蘸料",
```
`トッピング`即英语`topping`，可译作`蘸料`、`浇头`

2023-07-30 09:35 UTC, luoxueyasha commented on projects/1.20/assets/maturi-delight/maturidelight/lang/zh_cn.json
> +    "advancements.maturidelight.you_got_poison_me.description": "吃下有毒花朵制成的食物"
```suggestion
    "advancements.maturidelight.you_got_poison_me.description": "吃下由有毒花朵制成的食物"
```

2023-07-30 09:35 UTC, luoxueyasha commented on projects/1.20/assets/maturi-delight/maturidelight/lang/zh_cn.json
> +    "item.maturidelight.takoyaki_raw": "生章鱼烧",
国内更常见的叫法是`章鱼小丸子`（台湾传过来的）
可不改

2023-07-30 09:37 UTC, luoxueyasha requested changes

2023-07-30 09:37 UTC, luoxueyasha commented on projects/1.20/assets/maturi-delight/maturidelight/lang/zh_cn.json
> +    "advancements.maturidelight.you_got_poison_me.title": "从某种意义上说，中了大奖……",
```suggestion
    "advancements.maturidelight.you_got_poison_me.title": "也算是中大奖了……",
```
日本语翻译腔，不要比较好，是这么认为的捏

2023-07-30 09:37 UTC, seaseii commented on projects/1.20/assets/maturi-delight/maturidelight/lang/zh_cn.json
> +    "block.maturidelight.takoyaki_maker": "章鱼烧器",
雀食本来我也想译章鱼烧机的，不过mod里的必须放在火源上才能使用，感觉译成`机`怪怪的（

2023-07-30 09:38 UTC, seaseii commented on projects/1.20/assets/maturi-delight/maturidelight/lang/zh_cn.json
> +    "advancements.maturidelight.you_got_poison_me.title": "从某种意义上说，中了大奖……",
大概率是我这么说话习惯了，原来我也有翻译腔吗（

2023-07-30 09:39 UTC, seaseii commented on projects/1.20/assets/maturi-delight/maturidelight/lang/zh_cn.json
> +    "item.maturidelight.takoyaki_raw": "生章鱼烧",
最开始是百度百科找的（

2023-07-30 09:44 UTC, luoxueyasha commented on projects/1.20/assets/maturi-delight/maturidelight/lang/zh_cn.json
> +    "block.maturidelight.takoyaki_maker": "章鱼烧器",
`章鱼烧盘`
某宝也有叫这个的

2023-07-30 09:45 UTC, seaseii commented on projects/1.20/assets/maturi-delight/maturidelight/lang/zh_cn.json
> +    "block.maturidelight.takoyaki_maker": "章鱼烧器",
![QQ截图20230730174709](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/114800774/9243290f-e962-443b-a324-c9c388f6bce3)

2023-07-30 09:45 UTC, seaseii commented on projects/1.20/assets/maturi-delight/maturidelight/lang/zh_cn.json
> +    "block.maturidelight.takoyaki_maker": "章鱼烧器",
我觉得章鱼烧盘可能好一点（

2023-07-30 10:04 UTC, luoxueyasha commented on projects/1.20/assets/maturi-delight/maturidelight/lang/zh_cn.json
> +    "block.maturidelight.takoyaki_maker": "章鱼烧器",
Then `章鱼烧盘` shall it be

2023-07-30 10:06 UTC, seaseii commented on projects/1.20/assets/maturi-delight/maturidelight/lang/zh_cn.json
> +    "block.maturidelight.takoyaki_maker": "章鱼烧器",
Yes,`章鱼烧盘` is better

2023-07-30 10:15 UTC, luoxueyasha commented
你检查单呢……？

2023-07-30 10:15 UTC, seaseii commented
> 你检查单呢……？

昂？不是删了吗（

2023-07-30 10:17 UTC, seaseii commented
嘶，我检查单呢（？）

2023-07-30 10:20 UTC, seaseii commented
> 你检查单呢……？


https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/114800774/73a6653f-61c6-463e-826b-4f6f8606b6d0

是这个吗（

2023-07-30 10:25 UTC, luoxueyasha approved these changes
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/9eda2f1d-7a9e-4d87-99bc-7afc9bd3082c)

2023-07-30 11:16 UTC, seaseii commented
> ![image](https://user-images.githubusercontent.com/38830216/257045531-9eda2f1d-7a9e-4d87-99bc-7afc9bd3082c.png)

kawaii nye

2023-08-03 13:13 UTC, Cactusstudent approved these changes
对着英文的看着没问题

2023-08-03 13:13 UTC, merged