Aer's More Foods 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3589
Opened 2023-07-30 10:21 UTC by FriksD

由 CFPA-Helper 提交。
作者已阅读贡献指南并同意 CC 协议。

2023-07-30 10:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3589) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3589) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3589) it.</sub>

2023-07-30 11:15 UTC, seaseii commented
大致看了几眼

2023-08-01 07:18 UTC, Rinko1231 commented on projects/1.18-fabric/assets/aers-more-foods/more_drugs_mod/lang/zh_cn.json
> +  "block.more_drugs_mod.strawberry_plant": "草莓树",
```suggestion
  "block.more_drugs_mod.strawberry_plant": "草莓植株",
```

2023-08-01 07:18 UTC, Rinko1231 commented on projects/1.18-fabric/assets/aers-more-foods/more_drugs_mod/lang/zh_cn.json
> +  "block.more_drugs_mod.strawberry_plant": "草莓树",
草莓是蔷薇科草本植物不能称树，况且另有一种植物叫草莓树，但是是杜鹃花科

2023-08-01 13:07 UTC, ChuijkYahus commented on projects/1.18-fabric/assets/aers-more-foods/more_drugs_mod/lang/zh_cn.json
> +  "item.more_drugs_mod.donuts": "粉色甜甜圈",
```suggestion
  "item.more_drugs_mod.donuts": "粉红色甜甜圈",
```
~~十六色强迫症犯了~~

2023-08-04 04:42 UTC, luoxueyasha commented
@FriksD 
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

2023-08-04 06:44 UTC, CoalGlage commented on projects/1.18-fabric/assets/aers-more-foods/more_drugs_mod/lang/zh_cn.json
> +  "block.more_drugs_mod.tomatoes_plant": "番茄植株",
```suggestion
  "block.more_drugs_mod.strawberry_plant": "草莓",
  "block.more_drugs_mod.tomatoes_plant": "番茄",
```

2023-08-04 06:44 UTC, CoalGlage commented on projects/1.18-fabric/assets/aers-more-foods/more_drugs_mod/lang/zh_cn.json
> +  "block.more_drugs_mod.lettuce_plant": "生菜植株",
```suggestion
  "block.more_drugs_mod.lettuce_plant": "生菜",
```

2023-08-04 06:44 UTC, CoalGlage commented on projects/1.18-fabric/assets/aers-more-foods/more_drugs_mod/lang/zh_cn.json
> +  "block.more_drugs_mod.riceplant": "稻子",
```suggestion
  "block.more_drugs_mod.riceplant": "水稻",
```

2023-08-05 07:31 UTC, DrIceTea123 requested changes

2023-08-05 07:31 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/aers-more-foods/more_drugs_mod/lang/zh_cn.json
> +  "item.more_drugs_mod.jalapeno": "墨西哥辣椒",
是`墨西哥辣椒`还是`墨西哥胡椒` ~~还是`火爆辣椒`~~

2023-08-05 07:31 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/aers-more-foods/more_drugs_mod/lang/zh_cn.json
> +  "item.more_drugs_mod.empanadas": "恩潘纳达",
为啥是个音译？能搜出来的

2023-08-05 08:32 UTC, FriksD commented on projects/1.18-fabric/assets/aers-more-foods/more_drugs_mod/lang/zh_cn.json
> +  "item.more_drugs_mod.soup": "鸡汤",
是的

2023-08-05 08:35 UTC, FriksD commented on projects/1.18-fabric/assets/aers-more-foods/more_drugs_mod/lang/zh_cn.json
> +  "item.more_drugs_mod.jalapeno": "墨西哥辣椒",
查了一下，这两个翻译应该都可以，都是指Jalapeño

2023-08-05 08:42 UTC, FriksD commented on projects/1.18-fabric/assets/aers-more-foods/more_drugs_mod/lang/zh_cn.json
> +  "item.more_drugs_mod.empanadas": "恩潘纳达",
一般empanadas直接可以音译为恩潘纳达，意译也许可以翻译为西班牙炸饺？我认为两种翻译方式都ok，但惯例上似乎用音译的人会更多。

2023-08-05 08:46 UTC, FriksD commented on projects/1.18-fabric/assets/aers-more-foods/more_drugs_mod/lang/zh_cn.json
> +  "block.more_drugs_mod.tomatoes_plant": "番茄植株",
游戏中xxx_plant的物品指可以生产出xxx的植物。为了与果实做一个区分，我认为加一个“植株”来限定一下更好。

2023-08-05 08:46 UTC, FriksD commented on projects/1.18-fabric/assets/aers-more-foods/more_drugs_mod/lang/zh_cn.json
> +  "block.more_drugs_mod.lettuce_plant": "生菜植株",
游戏中xxx_plant的物品指可以生产出xxx的植物。为了与果实做一个区分，我认为加一个“植株”来限定一下更好。

2023-08-05 08:56 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/aers-more-foods/more_drugs_mod/lang/zh_cn.json
> +  "item.more_drugs_mod.empanadas": "恩潘纳达",
但是音译对于不知道这是什么东西的人来说就是看不懂，是译者的偷懒行为
你不说我就不知道`恩潘纳达`是`西班牙炸饺`，因为它们没有任何联系

2023-08-05 09:00 UTC, ChuijkYahus commented on projects/1.18-fabric/assets/aers-more-foods/more_drugs_mod/lang/zh_cn.json
> +  "item.more_drugs_mod.empanadas": "恩潘纳达",
要不恩潘纳达炸饺

2023-08-05 09:01 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/aers-more-foods/more_drugs_mod/lang/zh_cn.json
> +  "item.more_drugs_mod.empanadas": "恩潘纳达",
> 要不恩潘纳达炸饺

你认真的？

2023-08-05 09:03 UTC, FriksD commented on projects/1.18-fabric/assets/aers-more-foods/more_drugs_mod/lang/zh_cn.json
> +  "item.more_drugs_mod.empanadas": "恩潘纳达",
> 

嗯

2023-08-05 09:03 UTC, DrIceTea123 commented on projects/1.18-fabric/assets/aers-more-foods/more_drugs_mod/lang/zh_cn.json
> +  "item.more_drugs_mod.empanadas": "恩潘纳达",
主要是这东西交给翻译软件都不是音译，是`肉馅卷饼`
看实际模型吧，`西班牙炸饺`和`肉馅卷饼`选一个（或者再想个类似的）

2023-08-05 09:05 UTC, ChuijkYahus commented on projects/1.18-fabric/assets/aers-more-foods/more_drugs_mod/lang/zh_cn.json
> +  "item.more_drugs_mod.empanadas": "恩潘纳达",
> > 要不恩潘纳达炸饺
> 
> 你认真的？

之前群里貌似讨论过这东西的译法
主要这个也不是只在西班牙出现，南美洲和中美洲也很多，直接叫`西班牙炸饺`有些不妥

2023-08-05 09:31 UTC, CoalGlage commented on projects/1.18-fabric/assets/aers-more-foods/more_drugs_mod/lang/zh_cn.json
> +  "item.more_drugs_mod.empanadas": "恩潘纳达",
> 主要是这东西交给翻译软件都不是音译，是`肉馅卷饼` 看实际模型吧，`西班牙炸饺`和`肉馅卷饼`选一个（或者再想个类似的）
[https://zh.wikipedia.org/zh-my/%E6%81%A9%E6%BD%98%E7%B4%8D%E9%81%94](url)
维基百科是写作`恩潘纳达`的，而且此物外观上与卷饼并不相同；关于`西班牙炸饺`则如上面所述，这个不仅只在西班牙有。

2023-08-05 09:40 UTC, CoalGlage commented on projects/1.18-fabric/assets/aers-more-foods/more_drugs_mod/lang/zh_cn.json
> +  "block.more_drugs_mod.tomatoes_plant": "番茄植株",
这个的话...
![2023-08-05_17 37 19](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/117024879/a46e6c39-d0b0-420c-853f-386573f83cf0)
![2023-08-05_17 37 53](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/117024879/1ed260d2-3c91-44b0-9f37-fc52f58b5c27)
游戏内的话其实不做限定倒也没事

2023-08-05 11:39 UTC, ChuijkYahus commented on projects/1.18-fabric/assets/aers-more-foods/more_drugs_mod/lang/zh_cn.json
> +  "item.more_drugs_mod.empanadas": "恩潘纳达",
`炸饺` `炸馅饼`之类的（`炸盒`莫名中式）肯定是要加的，不常用的纯音译不好理解
前面部分`西班牙` `拉美` `恩潘纳达`的说法都有

~~上为QQ群内讨论结果的过度简化概括~~

---
~~下为私货（）~~

个人支持`恩潘纳达`，译名中允许原名+类型这种出现
不是特别支持`西班牙`，这种食物出现范围比较广（并且这模组里大概率应该是墨西哥）
`拉美`个人感觉也可以

2023-08-06 11:02 UTC, Cactusstudent approved these changes
基本没啥问题了

2023-08-07 09:27 UTC, merged