Jade 🔍 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #3591
Opened 2023-07-30 17:27 UTC by LockBac

由 CFPA-Helper 提交。
作者已阅读贡献指南并同意 CC 协议。

2023-07-31 06:12 UTC, mamaruo commented
@Snownee 你要的Jade中文来了，来看看？

2023-07-31 06:37 UTC, Snownee requested changes
谢谢翻译。1.20版本文本更新比较大，希望可以跟进。

2023-07-31 06:37 UTC, Snownee commented on projects/1.19/assets/jade/jade/lang/zh_cn.json
> +  "gui.jade.server_features": "*{0} {0,选择,1#服务器功能|1<服务器功能}",
“选择”不能被翻译

2023-07-31 06:37 UTC, Snownee commented on projects/1.19/assets/jade/jade/lang/zh_cn.json
> +  "gui.jade.server_features.tip": "此页面包含 {0} {0,选择,1#服务器功能|1<服务器功能}.\n在服务器上安装Jade以完全启用它们.",
“选择”不能被翻译

2023-07-31 06:37 UTC, Snownee commented on projects/1.19/assets/jade/jade/lang/zh_cn.json
> +  "config.jade.boss_bar_overlap": "Boss 条形图重叠",
正式翻译为Boss栏

2023-07-31 06:37 UTC, Snownee commented on projects/1.19/assets/jade/jade/lang/zh_cn.json
> +  "config.jade.boss_bar_overlap_hide_boss_bar": "隐藏Boss 条形图",
正式翻译为Boss栏

2023-07-31 06:37 UTC, Snownee commented on projects/1.19/assets/jade/jade/lang/zh_cn.json
> +  "config.jade.item_mod_name": "项目Mod名称",
项目 -> 物品

2023-07-31 06:37 UTC, Snownee commented on projects/1.19/assets/jade/jade/lang/zh_cn.json
> +  "config.jade.boss_bar_overlap_push_down": "按工具提示",
错误的翻译

2023-07-31 06:37 UTC, Snownee commented on projects/1.19/assets/jade/jade/lang/zh_cn.json
> +  "config.jade.hide_from_tab_list": "选项卡列表中隐藏",
正式翻译为玩家列表

2023-07-31 06:37 UTC, Snownee commented on projects/1.19/assets/jade/jade/lang/zh_cn.json
> +  "jade.ench_power": "Ench Power: %s",
未翻译

2023-07-31 06:37 UTC, Snownee commented on projects/1.19/assets/jade/jade/lang/zh_cn.json
> +  "config.jade.plugin_minecraft.energy_storage.detailed": "仅详细信息",
仅详细信息时

2023-07-31 06:37 UTC, Snownee commented on projects/1.19/assets/jade/jade/lang/zh_cn.json
> +  "config.jade.plugin_minecraft.fluid.detailed": "仅详细信息",
仅详细信息时

2023-07-31 06:37 UTC, Snownee commented on projects/1.19/assets/jade/jade/lang/zh_cn.json
> +  "jade.error": "<来自错误 %s 模组, 请报告>",
不通顺

2023-07-31 11:47 UTC, LockBac commented on projects/1.19/assets/jade/jade/lang/zh_cn.json
> +  "gui.jade.server_features": "*{0} {0,选择,1#服务器功能|1<服务器功能}",
已经修改完重新上传了

2023-07-31 12:22 UTC, Snownee commented on projects/1.19/assets/jade/jade/lang/zh_cn.json
> +  "gui.jade.server_features": "*{0} {0,选择,1#服务器功能|1<服务器功能}",
> 已经修改完重新上传了

这个系统不支持在同一PR里修改吗？这样看起来有点麻烦。

2023-07-31 13:47 UTC, mamaruo commented on projects/1.19/assets/jade/jade/lang/zh_cn.json
> +  "gui.jade.server_features": "*{0} {0,选择,1#服务器功能|1<服务器功能}",
> 已经修改完重新上传了

请不要重复提交 PR，这会造成 SPAM。

> 这个系统不支持在同一PR里修改吗？这样看起来有点麻烦。

第一次提交已经帮用户做完了，仁至义尽了都，还做后续修改吗。

2023-07-31 20:15 UTC, LockBac commented on projects/1.19/assets/jade/jade/lang/zh_cn.json
> +  "gui.jade.server_features": "*{0} {0,选择,1#服务器功能|1<服务器功能}",
> > 已经修改完重新上传了
> 
> 请不要重复提交 PR，这会造成 SPAM。
> 
> > 这个系统不支持在同一PR里修改吗？这样看起来有点麻烦。
> 
> 不支持。用户自己通过任一 git 客户端或网页都可以做修改。辅助系统总归是辅助系统。之后考虑让开发做检测直接杜绝用提交器（CFPA-Helper）做重复提交。

主要是第一次翻译  也是第一次用这个  不是很熟练 抱歉

2023-07-31 20:15 UTC, LockBac commented on projects/1.19/assets/jade/jade/lang/zh_cn.json
> +  "gui.jade.server_features": "*{0} {0,选择,1#服务器功能|1<服务器功能}",
> > 已经修改完重新上传了
> 
> 这个系统不支持在同一PR里修改吗？这样看起来有点麻烦。

刚才在cf上发现你做的MOD了  哈哈哈哈

2023-07-31 20:28 UTC, Snownee commented on projects/1.19/assets/jade/jade/lang/zh_cn.json
> +  "gui.jade.server_features": "*{0} {0,选择,1#服务器功能|1<服务器功能}",
你改完了就行了，不用给我看了

2023-08-06 11:00 UTC, Cactusstudent commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

@LockBac

2023-08-14 21:05 UTC, closed without merging