Croparia v4 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3593
Opened 2023-07-30 19:58 UTC by LockBac

由 CFPA-Helper 提交。
作者已阅读贡献指南并同意 CC 协议。

2023-07-30 19:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3593) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3593) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3593) it.</sub>

2023-08-01 00:21 UTC, luoxueyasha requested changes
翻译中有借助哪些工具？是否有游玩过这个模组？

2023-08-01 00:21 UTC, luoxueyasha commented on projects/1.19/assets/croparia/croparia/lang/zh_cn.json
> +  "block.croparia.block_crop_glowstone": "萤石作物",
```suggestion
  "block.croparia.block_crop_glowstone": "荧石作物",
```
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/02c9d17a-cc9b-4f6e-bed6-e7dcfdc22ee5)

 此问题请全文通查

2023-08-01 00:21 UTC, luoxueyasha commented on projects/1.19/assets/croparia/croparia/lang/zh_cn.json
> +  "item.croparia.greenhouse_light_gray": "浅灰色温室",
```suggestion
  "item.croparia.greenhouse_light_gray": "淡灰色温室",
```
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/657e66e8-f8ad-4ace-9e79-26aa98df88a3)

此问题请全文通查

2023-08-01 00:21 UTC, luoxueyasha commented on projects/1.19/assets/croparia/croparia/lang/zh_cn.json
> +  "item.croparia.seed_crop_sugar": "糖类种子",
`糖类`？确定吗？

2023-08-01 00:21 UTC, luoxueyasha commented on projects/1.19/assets/croparia/croparia/lang/zh_cn.json
> +  "container.soul_spawner": "灵魂重生者",
此物品在游戏中的效果、贴图？
`spawner`一般对应的是`刷怪笼`，具体请以游戏内容为准

2023-08-01 00:21 UTC, luoxueyasha commented on projects/1.19/assets/croparia/croparia/lang/zh_cn.json
> +  "itemGroup.croparia_crop": "魔种 : 植物",
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/6dea8f64-443c-43d8-9485-79599ce855b3)
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/0a5c977f-1e6d-4df6-bb14-994c69ee56ef)

```suggestion
  "itemGroup.croparia_crop": "魔咏之种丨植物",
```

2023-08-07 09:33 UTC, Cactusstudent commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

@LockBac

2023-08-13 00:37 UTC, luoxueyasha commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@LockBac

2023-08-13 21:10 UTC, LockBac commented
> 翻译中有借助哪些工具？ 是否有游玩过这个模组？

游玩过  甚至现在还在玩

2023-08-13 21:11 UTC, LockBac commented on projects/1.19/assets/croparia/croparia/lang/zh_cn.json
> +  "item.croparia.seed_crop_sugar": "糖类种子",
因为是糖  我觉得试做糖类种子更好一点

2023-08-13 22:46 UTC, luoxueyasha commented on projects/1.19/assets/croparia/croparia/lang/zh_cn.json
> +  "item.croparia.seed_crop_sugar": "糖类种子",
请问可以种出除了原版糖之外的糖吗

2023-08-14 07:59 UTC, LockBac commented
我记得好像是不太行&nbsp; &nbsp; 但是糖种子和糖类种子相比 糖类种子会更好听点



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月14日(星期一) 上午6:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CFPAOrg/Minecraft-Mod-Language-Package] Croparia v4 翻译提交 (PR #3593)





 
@luoxueyasha commented on this pull request.
 
 
In projects/1.19/assets/croparia/croparia/lang/zh_cn.json:
 &gt; +  "item.croparia.seed_crop_rawporc": "生猪排种子", +  "item.croparia.seed_crop_rawrabbit": "生兔肉种子", +  "item.croparia.seed_crop_red": "红色种子", +  "item.croparia.seed_crop_redstone": "红石种子", +  "item.croparia.seed_crop_salmon": "生鲑鱼种子", +  "item.croparia.seed_crop_scute": "鳞甲种子", +  "item.croparia.seed_crop_sea": "海洋种子", +  "item.croparia.seed_crop_shard": "海晶碎种子", +  "item.croparia.seed_crop_shell": "潜影种子", +  "item.croparia.seed_crop_silver": "淡灰色种子", +  "item.croparia.seed_crop_slime": "粘液球种子", +  "item.croparia.seed_crop_snowball": "雪球种子", +  "item.croparia.seed_crop_spruce": "云杉种子", +  "item.croparia.seed_crop_star": "下界之星种子", +  "item.croparia.seed_crop_string": "线种子", +  "item.croparia.seed_crop_sugar": "糖类种子",  
请问可以种出除了原版糖之外的糖吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2023-08-19 23:33 UTC, luoxueyasha commented
@LockBac 
那还是请翻译为`糖种子`，并及时在 Github 仓库里提交修正
它种出来的就是`糖`，而不是`糖类`

2023-08-26 04:33 UTC, Cactusstudent commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@LockBac

2023-09-03 09:36 UTC, ChuijkYahus commented
- 该提交由于[7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)将被关闭，请知晓。若仍想维护可选择Reopen此提交或重新打开新提交，并查看本提交内的审查意见并进行更改。

@LockBac

2023-09-03 09:36 UTC, closed without merging