Bosses of Mass Destruction 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3597
Opened 2023-08-01 00:50 UTC by nageih

2023-08-01 04:11 UTC, luoxueyasha requested changes

2023-08-01 04:11 UTC, luoxueyasha commented on projects/1.16-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +  "entity.bosses_of_mass_destruction.comet": "彗星",
1.16的中文与英文key不对应，可以解释一下原因吗

2023-08-01 04:19 UTC, nageih commented on projects/1.16-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +  "entity.bosses_of_mass_destruction.comet": "彗星",
1.16直接用的1.18的语言文件，我对比了下，1.18的语言文件已经包含了1.16的所有key，而且内容一样，所以就偷懒了

2023-08-01 04:21 UTC, luoxueyasha commented on projects/1.16-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +  "entity.bosses_of_mass_destruction.comet": "彗星",
行吧，记得改的时候三个版本都改

2023-08-01 04:41 UTC, luoxueyasha requested changes

2023-08-01 04:41 UTC, luoxueyasha commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +  "item.bosses_of_mass_destruction.earthdive_spear.tooltip" : "可以短距离传送穿过固体方块",
读起来有点怪
```suggestion
  "item.bosses_of_mass_destruction.earthdive_spear.tooltip" : "可以传送穿过一定厚度的固体方块",
```

2023-08-01 04:41 UTC, luoxueyasha commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +  "subtitles.bosses_of_mass_destruction.spike" : "冰霜：",
？

2023-08-01 04:41 UTC, luoxueyasha commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +  "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.summonMechanic" : "灵魂之星凋落",
是`掉落`还是`凋落`？

2023-08-01 04:41 UTC, luoxueyasha commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +  "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.summonMechanic.entitiesThatCountToSummonCounter" : "可掉落的生物",
可掉落……？

2023-08-01 04:56 UTC, nageih commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +  "subtitles.bosses_of_mass_destruction.spike" : "冰霜：",
已修复

2023-08-01 04:56 UTC, nageih commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +  "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.summonMechanic" : "灵魂之星凋落",
是`掉落`，已修复

2023-08-01 04:57 UTC, nageih commented on projects/1.18-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +  "text.autoconfig.bosses_of_mass_destruction.option.lichConfig.summonMechanic.entitiesThatCountToSummonCounter" : "可掉落的生物",
已改为`可掉落灵魂之星的生物`

2023-08-01 05:36 UTC, luoxueyasha submitted a review, later dismissed
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/dcb6ad3d-3e82-4d70-9829-d4aeacba6e35)
 一佰昏！特别是那几个成就名翻得拍手叫绝

2023-08-01 06:09 UTC, nageih commented
需不需要resolve老旧pr

2023-08-01 06:11 UTC, luoxueyasha commented
> 需不需要resolve老旧pr

走正常7+7流程就行

2023-08-01 06:12 UTC, nageih commented
ok

2023-08-01 09:36 UTC, Cactusstudent commented on projects/1.16-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +  "block.bosses_of_mass_destruction.chiseled_stone_altar" : "錾制石祭坛",
```suggestion
  "block.bosses_of_mass_destruction.chiseled_stone_altar" : "錾制石头祭坛",
```
原版的石xx已经在很早之前改为了石头xx

2023-08-01 09:36 UTC, Cactusstudent commented on projects/1.16-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +  "block.bosses_of_mass_destruction.chiseled_stone_altar" : "錾制石祭坛",
```suggestion
  "block.bosses_of_mass_destruction.chiseled_stone_altar" : "錾制石头祭坛",
```
原版的石xx已经在很早之前改为了石头xx

2023-08-01 09:36 UTC, Cactusstudent commented on projects/1.16-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +  "item.bosses_of_mass_destruction.mob_ward.tooltip" : "放置后，周围64格将不再生成生物",
原文：**When placed, mobs won't spawn in any 64 block direction**

这里游戏内考证一下？

2023-08-01 09:36 UTC, Cactusstudent commented on projects/1.16-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +  "subtitles.bosses_of_mass_destruction.petal_blade" : "花瓣利刃",
这里需要一个原文

2023-08-01 09:36 UTC, Cactusstudent commented on projects/1.16-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +  "subtitles.bosses_of_mass_destruction.petal_blade" : "花瓣利刃",
这里需要一个原文

2023-08-01 09:49 UTC, nageih commented on projects/1.16-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +  "subtitles.bosses_of_mass_destruction.petal_blade" : "花瓣利刃",
原文`Petals`

2023-08-01 09:54 UTC, nageih commented on projects/1.16-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +  "item.bosses_of_mass_destruction.mob_ward.tooltip" : "放置后，周围64格将不再生成生物",
试完了，功能确实与描述不符，实测是只会禁止怪物生成，但原文又是mob而不是monster，是遵照原文还是改了

2023-08-01 09:57 UTC, Cactusstudent commented on projects/1.16-fabric/assets/bosses-of-mass-destruction/bosses_of_mass_destruction/lang/zh_cn.json
> +  "item.bosses_of_mass_destruction.mob_ward.tooltip" : "放置后，周围64格将不再生成生物",
可以改

2023-08-02 04:45 UTC, mamaruo commented
我对比了“#3597”和“#2742”的翻译，结果如下：

### 两者皆有且中文有差异

<details><summary>点击展开/收起</summary>
<p>

| **键** | **英文** | **#3597** | **#2742** |
|---|---|---|---|
| entity.bosses_of_mass_destruction.comet | Comet | 彗星 | 坠星 |
| entity.bosses_of_mass_destruction.lich | Night Lich | 暗夜巫妖 | 夜歌 |
| entity.bosses_of_mass_destruction.blue_fireball | Blue Fireball | 蓝色火球 | 幽焰弹 |
| entity.bosses_of_mass_destruction.soul_star | Soul Star | 灵魂之星 | 魂星 |
| entity.bosses_of_mass_destruction.obsidilith | Obsidilith | 黑曜石柱 | 龙晶结构体 |
| entity.bosses_of_mass_destruction.gauntlet | Nether Gauntlet | 下界铁掌 | 下界巨拳 |
| entity.bosses_of_mass_destruction.petal_blade | Petal Blade | 花瓣利刃 | 落英 |
| block.bosses_of_mass_destruction.sealed_blackstone | Sealed Blackstone Bricks | 尘封黑石砖 | 密封的黑石 |
| block.bosses_of_mass_destruction.gauntlet_blackstone | Ancient Carved Blackstone | 远古雕刻黑石 | 錾制远古黑石 |
| block.bosses_of_mass_destruction.void_blossom_block | Void Blossom Boss Spawner | 虚空之花Boss刷怪笼 | 虚空之花刷怪笼 |
| block.bosses_of_mass_destruction.void_lily | Void Lily | 虚空百合 | 空无百合 |
| block.bosses_of_mass_destruction.void_lily.tooltip | Where does the pollen lead? | 花粉将带你到何处？ | 它的花粉将指引你至何方？ |
| block.bosses_of_mass_destruction.vine_wall | Bramble Wall | 灌木墙 | 灌木屏障 |
| item.bosses_of_mass_destruction.soul_star.tooltip | Where does it lead? | 它将带你到何处？ | 它将带你至何方？ |
| item.bosses_of_mass_destruction.ancient_anima | Ancient Anima | 上古灵魂 | 古代灵魂 |
| item.bosses_of_mass_destruction.crystal_fruit.tooltip | Grants brief regen and resistance | 获得短暂的生命恢复与抗性提升效果 | 获得短暂的再生和抗性提升效果 |
| item.bosses_of_mass_destruction.charged_ender_pearl | Charged Ender Pearl | 充能末影珍珠 | 充能完毕的末影珍珠 |
| item.bosses_of_mass_destruction.charged_ender_pearl.tooltip2 | resistance after teleport | 传送后给予短暂的抗性提升效果 | 传送后获得短暂的抗性提升效果 |
| item.bosses_of_mass_destruction.crafting_material.tooltip | Crafting material | 制作材料 | 用于制作的材料 |
| item.bosses_of_mass_destruction.brimstone_nectar.tooltip | Resets nearby boss structures on use | 使用后重置附近的Boss结构 | 使用后重置附近的boss生成结构 |
| block.bosses_of_mass_destruction.mob_ward | Staff of Suppression | 镇压之杖 | 威压之杖 |
| item.bosses_of_mass_destruction.mob_ward.tooltip | When placed, mobs won't spawn in any 64 block direction | 放置后，周围64格将不再生成怪物 | 放置后，64格范围内将不再生成怪物 |
| block.bosses_of_mass_destruction.monolith_block | Blast Amplifier | 爆破增幅器 | 激化装置 |
| item.bosses_of_mass_destruction.monolith_block.tooltip_0 | When placed, increases explosion power by 30% in any | 放置后，周围64格的爆炸威力将增加30% | 使周围一切爆炸威力提高30% |
| item.bosses_of_mass_destruction.monolith_block.tooltip_1 | 64 block direction\. This effect cannot stack | 效果不可叠加 | 激化范围：64格，无法叠加 |
| block.bosses_of_mass_destruction.levitation_block | Table of Elevation | 飞腾台座 | 反重力装置 |
| item.bosses_of_mass_destruction.levitation_block.tooltip | When placed, grants creative flight in a 7x7 column | 放置后，在7x7范围内获得创造飞行效果 | 使7x7范围内的玩家能够自由飞行 |
| item.bosses_of_mass_destruction.earthdive_spear.tooltip | Grants short range teleport through solid blocks | 可以传送穿过一定厚度的固体方块 | 能够带使用者短距离穿过实体方块 |
| item.bosses_of_mass_destruction.earthdive_spear | Earthdive Spear | 潜地矛 | 地心投矛 |
| advancements.nether.gauntlet_defeat.title | Through the Gauntlet | 击穿掌眼 | 打得一拳开 |
| advancements.nether.gauntlet_defeat.description | Defeat the Nether Gauntlet Boss | 击败下界铁掌Boss | 击败下界巨拳 |
| advancements.end.obsidilith_defeat.title | Obsidian Obliterator | 黑曜石毁灭者 | 返璞归真 |
| advancements.end.obsidilith_defeat.description | Defeat the Obsidilith Boss | 击败黑曜石柱Boss | 击败龙晶结构体（黑曜石古称龙晶） |
| advancements.adventure.night_lich_defeat.title | Night Vanquisher | 暗夜消退 | 夜之颂歌 |
| advancements.adventure.night_lich_defeat.description | Defeat the Night Lich Boss | 击败暗夜巫妖Boss | 击败夜歌 |
| advancements.adventure.void_blossom_defeat.title | Extreme Weeding | 寸草不生 | 极限除草 |
| advancements.adventure.void_blossom_defeat.description | Defeat the Void Blossom Boss | 击败虚空之花Boss | 击败虚空之花 |
| subtitles.bosses_of_mass_destruction.gauntlet_idle | Gauntlet Breathes | 下界铁掌：呼吸 | 下界巨拳：呼吸 |
| subtitles.bosses_of_mass_destruction.gauntlet_hurt | Gauntlet Hurts | 下界铁掌：受伤 | 下界巨拳：受伤 |
| subtitles.bosses_of_mass_destruction.gauntlet_cast | Gauntlet Casts | 下界铁掌：施法 | 下界巨拳：投掷 |
| subtitles.bosses_of_mass_destruction.gauntlet_spin_punch | Gauntlet Spins | 下界铁掌：旋转 | 下界巨拳：转体 |
| subtitles.bosses_of_mass_destruction.gauntlet_laser_charge | Gauntlet Charges Up | 下界铁掌：充能 | 下界巨拳：充能 |
| subtitles.bosses_of_mass_destruction.gauntlet_death | Gauntlet Dies | 下界铁掌：死亡 | 下界巨拳：死亡 |
| subtitles.bosses_of_mass_destruction.gauntlet_clink | Gauntlet Clinks | 下界铁掌：叮当 | 下界巨拳：叮当 |
| subtitles.bosses_of_mass_destruction.soul_star | Soul Star Falls | 灵魂之星：下落 | 魂星：下落 |
| subtitles.bosses_of_mass_destruction.energy_shield | Obsidilith Shields | 黑曜石柱：开启护盾 | 龙晶结构体：开启护盾 |
| subtitles.bosses_of_mass_destruction.obsidilith_prepare_attack | Obsidilith Charges Up | 黑曜石柱：充能 | 龙晶结构体：充能 |
| subtitles.bosses_of_mass_destruction.spike | Frost Erupts | 冰霜：聚爆 | 冰霜能量：震爆 |
| subtitles.bosses_of_mass_destruction.spike_indicator | Frost Gathers | 冰霜：汇聚 | 冰霜能量：汇聚 |
| subtitles.bosses_of_mass_destruction.wave_indicator | Fire Gathers | 火焰：汇聚 | 火焰能量：汇聚 |
| subtitles.bosses_of_mass_destruction.obsidilith_burst | Energy Erupts | 能量：聚爆 | 能量：泄露 |
| subtitles.bosses_of_mass_destruction.obsidilith_teleport | Obsidilith Teleports | 黑曜石柱：传送 | 龙晶结构体：传送 |
| subtitles.bosses_of_mass_destruction.obsidilith_death | Obsidilith Dies | 黑曜石柱：死亡 | 龙晶结构体：死亡 |
| subtitles.bosses_of_mass_destruction.obsidilith_hurt | Obsidilith Hurts | 黑曜石柱：受伤 | 龙晶结构体：受损 |
| subtitles.bosses_of_mass_destruction.obsidilith_wave | Fire Erupts | 火焰：聚爆 | 火焰能量：爆裂 |
| subtitles.bosses_of_mass_destruction.lich_death | Lich Dies | 暗夜巫妖：死亡 | 夜歌：死亡 |
| subtitles.bosses_of_mass_destruction.lich_hurt | Lich Hurts | 暗夜巫妖：受伤 | 夜歌：受伤 |
| subtitles.bosses_of_mass_destruction.lich_teleport | Lich Teleport | 暗夜巫妖：传送 | 夜歌：传送 |
| subtitles.bosses_of_mass_destruction.rage_prepare | Lich Rages | 暗夜巫妖：愤怒 | 夜歌：发怒 |
| subtitles.bosses_of_mass_destruction.minion_summon | Phantom Appears | 幻翼：出现 | 幻翼：被召唤 |
| subtitles.bosses_of_mass_destruction.minion_rune | Rune Appears | 符文：出现 | 符文：被召唤 |
| subtitles.bosses_of_mass_destruction.teleport_prepare | Lich Prepares Teleport | 暗夜巫妖：准备传送 | 夜歌：准备传送 |
| subtitles.bosses_of_mass_destruction.missile_prepare | Lich Prepares Iceballs | 暗夜巫妖：准备发射霜星 | 夜歌：准备发射霜星 |
| subtitles.bosses_of_mass_destruction.missile_shoot | Lich Shoots Iceballs | 暗夜巫妖：发射霜星 | 夜歌：发射霜星 |
| subtitles.bosses_of_mass_destruction.comet_prepare | Lich Prepares Comet | 暗夜巫妖：准备发射彗星 | 夜歌：准备发射坠星 |
| subtitles.bosses_of_mass_destruction.comet_shoot | Lich Launches Comet | 暗夜巫妖：发射彗星 | 夜歌：发射坠星 |
| subtitles.bosses_of_mass_destruction.void_blossom_burrow | Blossom Burrows | 虚空之花：钻洞 | 虚空之花：挖掘 |
| subtitles.bosses_of_mass_destruction.void_blossom_spike | Spikes | 突刺：伸出 | 虚空之花：刺击 |
| subtitles.bosses_of_mass_destruction.spore_impact | Poison Explodes | 毒素：爆裂 | 毒药：聚爆 |
| subtitles.bosses_of_mass_destruction.petal_blade | Petals | 花瓣利刃 | 落英：下落 |
| subtitles.bosses_of_mass_destruction.spore_prepare | Poison Bubbling | 毒素：酝酿 | 毒药攻击：准备 |
| subtitles.bosses_of_mass_destruction.spike_wave_indicator | Ground Trembles | 大地：震动 | 大地：震颤 |
| subtitles.bosses_of_mass_destruction.spore_ball_land | Poison Lands | 药水：着地 | 毒药：落地 |
| subtitles.bosses_of_mass_destruction.void_spike_indicator | Spikes Gather | 突刺：集聚 | 尖刺：聚拢 |
| subtitles.bosses_of_mass_destruction.void_blossom_fall | Blossom Falls | 虚空之花：凋落 | 虚空之花：陨落 |
| subtitles.bosses_of_mass_destruction.earthdive_spear_throw | Spear Throws | 潜地矛：掷出 | 投矛：投掷 |
| subtitles.bosses_of_mass_destruction.charged_ender_pearl | Pearl Lands | 充能末影珍珠：着地 | 珍珠：落地 |
| subtitles.bosses_of_mass_destruction.brimstone | Brimstone releases | 硫磺：喷出 | 硫磺：释放而出 |
| text.autoconfig.bosses_of_mass_destruction.title | All changes require mc restart | 所有的更改都需要重启MC | 需要重启游戏 |
| text.autoconfig.bosses_of_mass_destruction.category.Lich | Lich | 暗夜巫妖 | 夜歌 |
| text.autoconfig.bosses_of_mass_destruction.option.lichConfig.eternalNighttime | Apply Eternal Nightime | 启用永夜 | 激活永夜 |
|  [...]

2023-08-02 12:06 UTC, luoxueyasha requested changes

2023-08-02 13:12 UTC, nageih commented
@luoxueyasha 已与#2742作者协商完成，决定使用我这个pr，并resovle他的，有一些新的更新看commit就好，那个commit消息的pr号打错了，问题应该不大（

2023-08-02 13:16 UTC, IceDragonFla commented
#2742 作者报道，使用本pr，部分译名已经协商完成。

2023-08-04 06:12 UTC, merged