Wizards 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #3612
Opened 2023-08-03 14:40 UTC by sillymoon

- [x] 我已**仔细**阅读贡献指南 [CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)；
- [x] 我已确认英文原文（如 en_us.json）存在且完整，内容与中文对应；
- [x] 我已阅读并同意按 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 协议发布我的作品；
- [ ] 刷新 PR 的标签/状态，有需要再点击；

2023-08-05 07:12 UTC, DrIceTea123 requested changes
暂时就是这些

2023-08-05 07:12 UTC, DrIceTea123 commented on projects/1.20-fabric/assets/wizards/wizards/lang/zh_cn.json
> +  "item.wizards.staff_smaragdant_frost": "寒冰翡翠权杖",
这里按照前面的统一格式，应该把`奥秘权杖` `火焰权杖` `寒冰权杖`视为整体词
而且Ruby怎么是音译

2023-08-05 07:12 UTC, DrIceTea123 commented on projects/1.20-fabric/assets/wizards/wizards/lang/zh_cn.json
> +  "item.wizards.wizard_robe_legs": "魔法师下身袍",
参考植物魔法的处理方法：
```suggestion
  "item.wizards.wizard_robe_chest": "魔法师长袍",
  "item.wizards.wizard_robe_legs": "魔法师长袍（下半身）",
```

2023-08-05 07:12 UTC, DrIceTea123 commented on projects/1.20-fabric/assets/wizards/wizards/lang/zh_cn.json
> +  "spell.wizards.frost_nova.description": "使周围的目标冻结 {effect_duration} 秒，造成 {damage} 点寒冰法术伤害并阻碍其行动。处于冻结状态的敌人更容易受到寒冰法术的伤害。",
关于`blocking their movement`和`are vulnerable to frost magic`，提供我自己的译法
```suggestion
  "spell.wizards.frost_nova.description": "使周围的目标冻结 {effect_duration} 秒，造成 {damage} 点寒冰法术伤害并阻止其移动。处于冻结状态的敌人受到的寒冰法术伤害增加。",
```

2023-08-05 07:12 UTC, DrIceTea123 commented on projects/1.20-fabric/assets/wizards/wizards/lang/zh_cn.json
> +  "spell.wizards.frost_shield.description": "在 {effect_duration} 秒内保护使用者不被攻击，弹射物或火焰的伤害，但使用者的移动速度会降低。",
```suggestion
  "spell.wizards.frost_shield.description": "在 {effect_duration} 秒内保护使用者不受到攻击、弹射物或火焰的伤害，但使用者的移动速度会降低。",
```

2023-08-05 07:38 UTC, sillymoon commented on projects/1.20-fabric/assets/wizards/wizards/lang/zh_cn.json
> +  "item.wizards.staff_smaragdant_frost": "寒冰翡翠权杖",
讲个笑话 这是之前有人交给官方的一份汉化文件 没仔细看已翻译部分
（喵的要帮忙修改的东西变多了）

2023-08-06 05:48 UTC, sillymoon commented on projects/1.20-fabric/assets/wizards/wizards/lang/zh_cn.json
> +  "item.wizards.staff_smaragdant_frost": "寒冰翡翠权杖",
已修正

2023-08-06 05:49 UTC, sillymoon commented on projects/1.20-fabric/assets/wizards/wizards/lang/zh_cn.json
> +  "item.wizards.wizard_robe_legs": "魔法师下身袍",
已修正

2023-08-06 05:49 UTC, sillymoon commented on projects/1.20-fabric/assets/wizards/wizards/lang/zh_cn.json
> +  "spell.wizards.frost_nova.description": "使周围的目标冻结 {effect_duration} 秒，造成 {damage} 点寒冰法术伤害并阻碍其行动。处于冻结状态的敌人更容易受到寒冰法术的伤害。",
已修正

2023-08-06 05:49 UTC, sillymoon commented on projects/1.20-fabric/assets/wizards/wizards/lang/zh_cn.json
> +  "spell.wizards.frost_shield.description": "在 {effect_duration} 秒内保护使用者不被攻击，弹射物或火焰的伤害，但使用者的移动速度会降低。",
已修正

2023-08-06 06:12 UTC, DrIceTea123 commented
不用每条都回复，会产生垃圾邮件。提交修正内容时我会收到邮件的
修完的内容Resolve掉就行了

2023-08-06 06:13 UTC, DrIceTea123 commented on projects/1.20-fabric/assets/wizards/wizards/lang/zh_cn.json
> +  "item.wizards.staff_smaragdant_frost": "寒冰翡翠权杖",
这里还是有问题，按照前面的格式，这里应该类似为`结晶奥秘权杖`而不是`奥秘结晶权杖`，以此类推
看你自己的意思改吧

2023-08-06 06:27 UTC, sillymoon commented on projects/1.20-fabric/assets/wizards/wizards/lang/zh_cn.json
> +  "item.wizards.staff_smaragdant_frost": "寒冰翡翠权杖",
> 这里还是有问题，按照前面的格式，这里应该类似为`结晶奥秘权杖`而不是`奥秘结晶权杖`，以此类推 看你自己的意思改吧

ok

2023-08-09 09:58 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/wizards/wizards/lang/zh_cn.json
> +  "item.wizards.staff_smaragdant_frost": "翠玉寒冰权杖",
这个在游戏内是怎么合成的

2023-08-09 09:58 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/wizards/wizards/lang/zh_cn.json
> +  "spell.wizards.fire_breath.description": "焚烧前方目标，每秒造成{damage}点火焰法术伤害。",
```suggestion
  "spell.wizards.fire_breath.description": "焚烧前方目标，每秒最多造成{damage}点火焰法术伤害。",
```

2023-08-09 09:58 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/wizards/wizards/lang/zh_cn.json
> +  "spell.wizards.fire_meteor.description": "向目标坠落陨石，在{impact_range}格范围内造成{damage}点火焰法术伤害。",
```suggestion
  "spell.wizards.fire_meteor.description": "向目标坠落陨石，在{impact_range}格范围内最多造成{damage}点火焰法术伤害。",
```

2023-08-09 09:58 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/wizards/wizards/lang/zh_cn.json
> +  "advancements.rpg_classes.obtain_wizard_robes.title": "魔法师永不迟到！",
甘道夫台词

2023-08-09 12:34 UTC, sillymoon commented on projects/1.20-fabric/assets/wizards/wizards/lang/zh_cn.json
> +  "spell.wizards.fire_breath.description": "焚烧前方目标，每秒造成{damage}点火焰法术伤害。",
是这样的，原文中`{damage}`所给出的是一个数值范围，这里添加`最多`不太妥当，下面那个同理

2023-08-09 12:45 UTC, sillymoon commented on projects/1.20-fabric/assets/wizards/wizards/lang/zh_cn.json
> +  "advancements.rpg_classes.obtain_wizard_robes.title": "魔法师永不迟到！",
这个改了，但是标题`Wizard`已选取mc百科标题一译，所以对此已作部分更改
下文是哈利波特的一句话，也进行了修正

2023-08-09 12:49 UTC, sillymoon commented on projects/1.20-fabric/assets/wizards/wizards/lang/zh_cn.json
> +  "item.wizards.staff_smaragdant_frost": "翠玉寒冰权杖",
这个mod是和BetterNether联动的，里面的`Smaragdant`所用的是`翡翠`一译
（此物品用的是`翡翠晶`这个东西，为了字数一致就直接用了翡翠晶）

2023-08-10 07:04 UTC, ChuijkYahus approved these changes

2023-08-10 07:58 UTC, Cyl18 commented
/format *

2023-08-10 08:03 UTC, Cyl18 commented
/format *

2023-08-10 08:08 UTC, Cyl18 commented
用这个PR测试一下 很抱歉

2023-08-10 08:17 UTC, Cyl18 commented
/format *

2023-08-10 08:26 UTC, Cyl18 commented
/format *

2023-08-10 08:29 UTC, Cyl18 commented
今天不写了 算法太难了

2023-08-10 09:18 UTC, Cyl18 approved these changes

2023-08-10 12:01 UTC, dovisutu reviewed
基本上没什么问题

2023-08-10 12:01 UTC, dovisutu commented on projects/1.20-fabric/assets/wizards/wizards/lang/zh_cn.json
> +  "item.wizards.staff_crystal_arcane": "结晶奥秘权杖",
这个crystal具体是什么材料？还是说什么效果？

2023-08-10 13:24 UTC, sillymoon commented on projects/1.20-fabric/assets/wizards/wizards/lang/zh_cn.json
> +  "item.wizards.staff_crystal_arcane": "结晶奥秘权杖",
和better end联动的部分，已修正

2023-08-11 01:03 UTC, dovisutu approved these changes

2023-08-11 11:21 UTC, merged