Miner's Lung 翻译修正
CFPAOrg/Minecraft-Mod-Language-Package pull request #3621
Opened 2023-08-05 02:51 UTC by zerodegress

2023-08-05 06:28 UTC, Cactusstudent requested changes

2023-08-05 06:28 UTC, Cactusstudent commented on projects/1.18/assets/miners-lung/minerslung/lang/zh_cn.json
> +  "advancement.minerslung:soul.desc": "呼吸灵魂火释放的生命力来维持你的空气（但并不会增加它！）",
？需要求证这里的Air与原版的Air/Oxygen是否为一个东西

2023-08-05 06:28 UTC, Cactusstudent commented on projects/1.18/assets/miners-lung/minerslung/lang/zh_cn.json
> +  "advancement.minerslung:lantern": "我们的第一优先级",
更改原因？从字面上看明显当务之急更顺口，也基本符合原文
原文：**Our Number One Priority**

2023-08-05 06:47 UTC, zerodegress commented on projects/1.18/assets/miners-lung/minerslung/lang/zh_cn.json
> +  "advancement.minerslung:soul.desc": "呼吸灵魂火释放的生命力来维持你的空气（但并不会增加它！）",
模组内的文本所说的air应该与原版的air不是同一个东西，从窒息有一个专门的死亡信息看是单独的模组机制而非借用原版机制

2023-08-05 06:59 UTC, zerodegress commented on projects/1.18/assets/miners-lung/minerslung/lang/zh_cn.json
> +  "advancement.minerslung:lantern": "我们的第一优先级",
原文这里是"Our Number One Priority"（字面翻译为第一优先级），对应的成就描述是提着安全灯检查周围空气。


"当务之急"是指当前需要**立刻**处理的、最为**迫切**的任务或问题。它通常强调**紧急性**和**迅速**行动的重要性。这个词组常用于强调解决当前面临的**紧急**情况，避免出现更严重的后果。


"第一优先级"是指在一系列任务或事项中，**排在第一位**、**最重要的**事项。它并不一定强调紧急性，而更注重优先级的排序。这个词组用于决定执行计划或工作时，确认哪个任务在重要性上应该首先得到处理，以保证资源的合理分配和最大效益。


但是该成就获得情境应该是在洞穴某一区域里使用安全灯做检查，并不能说明玩家正身处险境急需处理什么事项，而且身处险境时“当务之急”恐怕也不是拿安全灯了。


这么看来应该是在刚进入洞穴某个区域时**优先**使用安全灯检查空气质量而非**当务之急**（毕竟这时候不是很急）


不过也许翻译成“我们的头等大事”会更顺嘴？

2023-08-05 11:11 UTC, zerodegress commented on projects/1.18/assets/miners-lung/minerslung/lang/zh_cn.json
> +  "advancement.minerslung:soul.desc": "呼吸灵魂火释放的生命力来维持你的空气（但并不会增加它！）",
> ？需要求证这里的Air与原版的Air/Oxygen是否为一个东西

呃，不过和原版的氧气条是共用的，但死亡信息是独立的

2023-08-05 11:11 UTC, zerodegress commented on projects/1.18/assets/miners-lung/minerslung/lang/zh_cn.json
> +  "advancement.minerslung:lantern": "我们的第一优先级",
> 更改原因？从字面上看明显当务之急更顺口，也基本符合原文 原文：**Our Number One Priority**

翻译暂时修改为“我们的头等大事”

2023-08-06 11:04 UTC, Cactusstudent approved these changes

2023-08-07 09:28 UTC, merged