FoodExpansion 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3645
Opened 2023-08-10 14:41 UTC by FuAwake

2023-08-10 14:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3645) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3645) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3645) it.</sub>

2023-08-11 02:53 UTC, Cactusstudent commented
感谢您的提交，在合并之前，您需要签署CLA（Contributor License Agreement），否则我们将拒收您的翻译。
@FuAwake 

---

签署方法是，在由 @CLAassistant 发出的评论中，点击带链接的 Contributor License Arrgement，按照网页提示操作。
操作以后，稍等一段时间；如果状态仍未改变，可以点击 recheck 链接以刷新；如等待后仍未改变，则可联系我们。

注意：这一过程需要验证Github账号！访问时请确保可以较为稳定地连接至Github网页（至少在验证时）；如有需要，可以使用特殊工具。

2023-08-11 11:18 UTC, dovisutu approved these changes
看起来没有什么问题...？

2023-08-11 12:41 UTC, luoxueyasha requested changes

2023-08-11 12:41 UTC, luoxueyasha commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.cooked_bacon": "脆皮培根",
```suggestion
    "item.foodexpansion.cooked_bacon": "香脆培根",
```
一般来说描述`烤的酥脆的培根`不用`脆皮`，培根是不带皮的
`脆皮五花肉`则是真的把皮做脆了

2023-08-11 12:41 UTC, luoxueyasha commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.nether_wart_soup": "下界疣靓汤",
可以解释一下`stew`在这里为何作`靓汤`吗？（例如制作工艺有区别？

2023-08-11 12:41 UTC, luoxueyasha commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.blaze_cream": "烈焰乳皮汤",
`乳皮汤`是怎么翻出来的？合成方法、实际贴图与使用效果？

2023-08-11 12:41 UTC, luoxueyasha commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.wolf_meat": "生犬肉",
```suggestion
    "item.foodexpansion.wolf_meat": "生狼肉",
```
此问题请全文通查

2023-08-11 12:41 UTC, luoxueyasha commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.veggie_stew": "大乱炖",
合成方式、贴图、使用效果？

2023-08-11 12:41 UTC, luoxueyasha commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.bat_soup": "蝙蝠炖汤",
`炖汤`可以被解释为动词和名词，具有二义性。
```suggestion
    "item.foodexpansion.bat_soup": "蝙蝠汤",
```

2023-08-13 00:26 UTC, FuAwake commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.nether_wart_soup": "下界疣靓汤",
游戏中是一个碗两个下界疣与一个糖合成，我当时下意识想到的是靓汤，但貌似对这个词对理解不恰当。已修改为“下界疣炖菜”。

2023-08-13 00:30 UTC, FuAwake commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.blaze_cream": "烈焰乳皮汤",
原版是由烈焰粉加牛奶合成，cream奶油它不能只是一点牛奶就可以制成的，而炼乳又有些不恰当，因此我选择了一个我理解的更“中式”的词汇：“奶皮”。而奶皮，也正是牛奶熬制而成的。附上一张合成表。
![20230813082721](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/78325969/027f6425-c157-4cd1-ad67-846becd3041b)

2023-08-13 00:35 UTC, FuAwake commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.veggie_stew": "大乱炖",
食用后恢复五颗鸡腿的饱食度，无其他效果例如生命恢复等buff。
同样地，我也是想使用一些我自己理解的“中式”的名词，但貌似起到了反效果，我会更谨慎地，依照更通俗、更易为人接受的方式翻译。
![QQ截图20230813083033](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/78325969/c0b24716-7052-4284-9452-45b712d5cfd3)

2023-08-13 01:15 UTC, luoxueyasha requested changes

2023-08-13 01:15 UTC, luoxueyasha commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.spider_soup": "蛛眼炖汤",
```suggestion
    "item.foodexpansion.spider_soup": "蛛眼浓汤",
```
既然`蝙蝠炖汤`改了，那么上下文应一致
此问题请全文通查，尽量是保持`Soup`在模组内的翻译一致

2023-08-13 01:15 UTC, luoxueyasha commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.nether_wart_soup": "下界疣炖菜",
```suggestion
    "item.foodexpansion.nether_wart_soup": "下界疣煲",
```
`Stew`应对应`煲`，见[原版译名标准化](https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96)
此问题请全文通查

2023-08-13 01:15 UTC, luoxueyasha commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.blaze_cream": "烈焰香奶汤",
```suggestion
    "item.foodexpansion.blaze_cream": "烈焰奶油汤",
```
没必要多此一举，[奶油汤](https://zh.wikipedia.org/zh-cn/%E5%BF%8C%E5%BB%89%E6%B9%AF)就是奶油汤
同样的，如果`Soup`有其他对应，请包括这里进行全文通查

2023-08-13 01:15 UTC, luoxueyasha commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +{
请保留原文的空行，以便于校对与后续更新

2023-08-13 01:15 UTC, luoxueyasha commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.golden_feast": "黄金盛餐",
```suggestion
    "item.foodexpansion.golden_feast": "黄金盛宴",
```
```suggestion
    "item.foodexpansion.golden_feast": "黄金大餐",
```
`盛餐`……总感觉不如`盛宴`常用
仅建议，可以不用改

2023-08-20 04:00 UTC, ChuijkYahus submitted a review, later dismissed
可以在中文文件里补充下空行
另外Golden Feast一行需要更改吗，其余应该没什么问题

2023-08-21 05:33 UTC, luoxueyasha requested changes

2023-08-21 05:33 UTC, luoxueyasha commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.compressed_flesh": "腊肉",
原文`Dried Flesh`
确定是`腊制`（xi4）的肉吗

2023-08-26 04:24 UTC, Cactusstudent approved these changes

2023-08-26 04:24 UTC, Cactusstudent commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.compressed_flesh": "腊肉",
答案是否
```suggestion
    "item.foodexpansion.compressed_flesh": "肉干",
```

2023-08-26 15:19 UTC, luoxueyasha commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.compressed_flesh": "腊肉",
最好进游戏看一眼

2023-08-27 03:00 UTC, luoxueyasha requested changes

2023-08-27 03:00 UTC, luoxueyasha commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.squid": "生鱿鱼片",
为什么改为`片`，有贴图吗

2023-08-27 03:00 UTC, luoxueyasha commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.chocolate_bar": "巧克力",
为什么去掉`棒`，有贴图吗

2023-08-27 03:00 UTC, luoxueyasha commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.bat_wing": "生蝙蝠翼",
```suggestion
    "item.foodexpansion.bat_wing": "生蝙蝠翅",
```
原译其实没什么问题……例如`鸡翅`这种措辞是不是更好一点

2023-08-27 03:00 UTC, luoxueyasha commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.veggie_stew": "蔬菜汤",
`stew`应当为`煲`（见蘑菇煲）

2023-08-27 03:00 UTC, luoxueyasha commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "itemGroup.foodexpansion_tab": "食物拓展：重构想"
和原文不对应，`重构想`是怎么译出来的

2023-08-27 03:57 UTC, FuAwake commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.squid": "生鱿鱼片",
![squid](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/78325969/64ddd98d-2210-43af-9f8b-860cb73b5b0d)
私认为更恰当

2023-08-27 03:57 UTC, FuAwake commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.chocolate_bar": "巧克力",
![chocolate](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/78325969/540b846d-62dd-4b7d-8b5c-5a22ac2a211a)
 私认为更恰当

2023-08-27 04:01 UTC, FuAwake commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "itemGroup.foodexpansion_tab": "食物拓展：重构想"
![reimage](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/78325969/9a41a5aa-d81d-4828-91cc-e9191faf8a5e)
因为这是食物拓展（Food Expansion）的高版本，Food Expansion：Reimagined。

2023-08-27 05:48 UTC, luoxueyasha commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.squid": "生鱿鱼片",
怎么感觉是`鱿鱼腿`

2023-09-02 04:58 UTC, ChuijkYahus commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.bat_wing": "生蝙蝠翼",
这条如果要改则下面的`蝙蝠翼汤`也要改

话说剩余的这两条还要改吗
不改就可以合并了

2023-09-11 05:31 UTC, ChuijkYahus commented
如果已经回复可以看下自己评论上有没有Pending这个标记
带有这个标记的评论仅自己可见
可在Files changed页面Review changes按钮提交评论，就会实际发出来了

2023-11-19 08:47 UTC, ChuijkYahus commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.bat_wing": "生蝙蝠翼",
这两条还要改吗

2023-11-19 10:03 UTC, luoxueyasha commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.bat_wing": "生蝙蝠翼",
这条commit后合了吧

2023-11-19 10:03 UTC, luoxueyasha commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.bat_soup": "蝙蝠翼汤",
```suggestion
    "item.foodexpansion.bat_soup": "蝙蝠翅汤",
```

2023-11-19 10:04 UTC, luoxueyasha commented on projects/1.20/assets/food-expansion-reimagined/foodexpansion/lang/zh_cn.json
> +    "item.foodexpansion.cooked_bat_wing": "熟蝙蝠翼",
```suggestion
    "item.foodexpansion.cooked_bat_wing": "熟蝙蝠翅",
```

2023-11-19 10:04 UTC, luoxueyasha approved these changes

2023-11-19 10:04 UTC, merged