提交dense-ores-refabricated的汉化
CFPAOrg/Minecraft-Mod-Language-Package pull request #3646
Opened 2023-08-10 17:14 UTC by MikuVivy

2023-08-10 17:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3646) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3646) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3646) it.</sub>

2023-08-11 01:11 UTC, mamaruo commented
> 这个咋改成Fabric啊，视频教程没有这一步QAQ

酒石酸的视频过时咯。请查看贡献方针。注意标题格式

1.19的是混着放的，没有区分Forge和Fabric

2023-08-11 01:11 UTC, dovisutu commented
1.19版本的fabric和forge是放在一起的，不用分开

2023-08-11 02:08 UTC, Cactusstudent requested changes

2023-08-11 02:08 UTC, Cactusstudent commented on projects/1.19/assets/dense-ores-refabricated/denseores/lang/zh_cn.json
> +  "itemGroup.denseores.item_group": "致密矿石: Fabric版",
```suggestion
  "itemGroup.denseores.item_group": "致密矿石：Fabric版",

```

2023-08-11 02:08 UTC, Cactusstudent commented on projects/1.19/assets/dense-ores-refabricated/denseores/lang/zh_cn.json
> +  "configOption.denseores.canGenerate.tooltip.2": "此矿石在原版中不会生成，请勿启用，除非您使用了自定义世界生成。",
```suggestion
  "configOption.denseores.canGenerate.tooltip.2": "此矿石在原版中不会生成，请勿启用，除非你使用了自定义世界生成。",

```

2023-08-11 02:08 UTC, Cactusstudent commented on projects/1.19/assets/dense-ores-refabricated/denseores/lang/zh_cn.json
> +  "configOption.denseores.maxHeight.tooltip": "此矿石能够生成的最高 Y 坐标",
```suggestion
  "configOption.denseores.minHeight.tooltip": "此矿石能够生成的最低Y坐标",
  "configOption.denseores.maxHeight.tooltip": "此矿石能够生成的最高Y坐标",
```

2023-08-11 02:08 UTC, Cactusstudent commented on projects/1.19/assets/dense-ores-refabricated/denseores/lang/zh_cn.json
> +  "configOption.denseores.chunkOdds.tooltip": "此矿石在一个区块内生成的几率。数值越高，生成几率越大",
```suggestion
  "configOption.denseores.chunkOdds.tooltip": "此矿石在一个区块内生成的概率。数值越高，生成概率越大",
```
建议全文通查

2023-08-11 02:08 UTC, Cactusstudent commented on projects/1.19/assets/dense-ores-refabricated/denseores/lang/zh_cn.json
> +  "configOption.denseores.coalVeinSize": "致密煤矿石的簇尺寸",
原文是vein，使用矿脉更合适，建议全文通查，https://minecraft.fandom.com/zh/wiki/%E5%9C%B0%E5%BD%A2%E7%89%B9%E5%BE%81#%E7%9F%BF%E8%84%89

2023-08-11 05:08 UTC, ChuijkYahus commented on projects/1.19/assets/dense-ores-refabricated/denseores/lang/zh_cn.json
> +  "configOption.denseores.coalChunkOdds": "致密煤矿石在每个区块中的几率",
```suggestion
  "configOption.denseores.coalChunkOdds": "致密煤矿石在每个区块中的概率",
```
建议通查

2023-08-11 05:08 UTC, ChuijkYahus commented on projects/1.19/assets/dense-ores-refabricated/denseores/lang/zh_cn.json
> +  "configOption.denseores.coalMaxHeight": "致密煤矿石的最大高度",
```suggestion
  "configOption.denseores.coalMaxHeight": "致密煤矿石的最高高度",
```
属于是强行对齐了（）
如果更改则全文通查

2023-08-11 07:23 UTC, ChuijkYahus approved these changes

2023-08-12 01:41 UTC, merged