Hostile Delight 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3647
Opened 2023-08-11 03:49 UTC by seaseii

2023-08-11 03:52 UTC, seaseii commented
英文语言文件感觉像机翻的（

2023-08-11 04:06 UTC, seaseii commented on projects/1.19/assets/hostile-delight/hostiledelight/lang/zh_cn.json
> +    "item.hostiledelight.soda": "苏大",
不是饮品（

2023-08-11 04:07 UTC, seaseii commented
> > 英文语言文件感觉像机翻的（
> 
> 感觉像机翻的话，那就看游戏实际物品吧

基本上是韩语+游戏内贴图和配方译的（）

2023-08-11 12:32 UTC, luoxueyasha requested changes

2023-08-11 12:32 UTC, luoxueyasha commented on projects/1.19/assets/hostile-delight/hostiledelight/lang/zh_cn.json
> +    "effect.hostiledelight.dioxide": "二氧化物",
获取方式、图标、实际效果？

2023-08-13 00:06 UTC, seaseii commented on projects/1.19/assets/hostile-delight/hostiledelight/lang/zh_cn.json
> +    "effect.hostiledelight.dioxide": "二氧化物",
抱歉，昨天身体抱恙，没有及时给出答复
池一些守卫者肉或其衍生食品会给予玩家此效果
实际效果是效果持续期间在水中无需呼吸，但玩家的氧气槽无法积蓄氧气（也就是效果结束后会立即受到溺水伤害）
![QQ截图20230813080553](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/114800774/e3c964de-9356-4cb5-bf67-90649f2bc4db)

2023-08-13 01:35 UTC, luoxueyasha requested changes

2023-08-13 01:35 UTC, luoxueyasha commented on projects/1.19/assets/hostile-delight/hostiledelight/lang/zh_cn.json
> +    "effect.hostiledelight.dioxide": "二氧化物",
唔……倒是感觉`二氧化物`不适合作为效果名
此外作者应该想表达的是`低氧化`（Suboxide）[아산화물 - Wikipedia](https://ko.wikipedia.org/wiki/%EC%95%84%EC%82%B0%ED%99%94%EB%AC%BC)
```suggestion
    "effect.hostiledelight.dioxide": "低氧化",
```

2023-08-13 01:38 UTC, seaseii commented on projects/1.19/assets/hostile-delight/hostiledelight/lang/zh_cn.json
> +    "effect.hostiledelight.dioxide": "二氧化物",
雀食感觉`二氧化物`不太适合（
感谢建议

2023-08-13 03:08 UTC, luoxueyasha submitted a review, later dismissed

2023-08-19 18:27 UTC, ChuijkYahus approved these changes

2023-08-21 02:19 UTC, Cactusstudent requested changes

2023-08-21 02:19 UTC, Cactusstudent commented on projects/1.19/assets/hostile-delight/hostiledelight/lang/zh_cn.json
> +    "item.hostiledelight.suspiciousbaconandaggs": "迷之培根加鸡蛋",
`迷`还是`谜`？原版对此做过更改，请查证是否应该更改

2023-08-23 06:27 UTC, seaseii commented on projects/1.19/assets/hostile-delight/hostiledelight/lang/zh_cn.json
> +    "item.hostiledelight.suspiciousbaconandaggs": "迷之培根加鸡蛋",
chuijk不是看过这里了吗（？）

2023-08-25 01:02 UTC, Cactusstudent approved these changes

2023-08-26 02:52 UTC, merged