Apotheosis 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #3648
Opened 2023-08-11 08:56 UTC by MrHengyin

2023-08-11 08:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3648) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3648) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3648) it.</sub>

2023-08-12 23:22 UTC, luoxueyasha requested changes

2023-08-12 23:22 UTC, luoxueyasha commented on projects/1.16/assets/apotheosis/apotheosis/lang/zh_cn.json
> +  "enchantment.apotheosis.earths_boon": "地球的恩惠",
确定`Earth`是`地球`？

2023-08-12 23:22 UTC, luoxueyasha commented on projects/1.16/assets/apotheosis/apotheosis/lang/zh_cn.json
> +  "enchantment.apotheosis.spearfishing": "捕鱼矛",
原文`Spearfishng`
这是个附魔，我不认为`捕鱼矛`的翻译足够好
```suggestion
  "enchantment.apotheosis.spearfishing": "捕鱼之矛",
```
```suggestion
  "enchantment.apotheosis.spearfishing": "鱼叉",
```
```suggestion
  "enchantment.apotheosis.spearfishing": "鱼获之矛",
```

2023-08-12 23:22 UTC, luoxueyasha commented on projects/1.16/assets/apotheosis/apotheosis/lang/zh_cn.json
> +  "enchantment.apotheosis.spearfishing.desc": "用投掷的三叉戟杀人可能会抓到一条鱼。",
杀其他动物呢？

2023-08-12 23:22 UTC, luoxueyasha commented on projects/1.16/assets/apotheosis/apotheosis/lang/zh_cn.json
> +  "enchantment.apotheosis.chainsaw.desc": "将树砍倒。",
翻译的怪怪的，建议改改

2023-08-18 01:53 UTC, MrHengyin commented on projects/1.16/assets/apotheosis/apotheosis/lang/zh_cn.json
> +  "enchantment.apotheosis.earths_boon": "地球的恩惠",
我觉得地球的恩惠好听一点，或者改成大地的恩惠或者土地的恩惠？

2023-08-18 01:58 UTC, MrHengyin commented on projects/1.16/assets/apotheosis/apotheosis/lang/zh_cn.json
> +  "enchantment.apotheosis.spearfishing": "捕鱼矛",
这个我在翻译的时候完全忘了有鱼叉这么个词

2023-08-18 02:04 UTC, MrHengyin commented on projects/1.16/assets/apotheosis/apotheosis/lang/zh_cn.json
> +  "enchantment.apotheosis.spearfishing.desc": "用投掷的三叉戟杀人可能会抓到一条鱼。",
是的，只要是生物就有效，包括中立被动敌对

2023-08-18 02:08 UTC, MrHengyin commented on projects/1.16/assets/apotheosis/apotheosis/lang/zh_cn.json
> +  "enchantment.apotheosis.chainsaw.desc": "将树砍倒。",
效果就是连锁砍倒整棵树，但是连锁是个非原版概念，如果用白话就会很长，不用白话就会怎么翻译怎么怪

2023-08-18 02:11 UTC, MrHengyin commented on projects/1.16/assets/apotheosis/apotheosis/lang/zh_cn.json
> +  "enchantment.apotheosis.spearfishing": "捕鱼矛",
这个我在翻译的时候完全忘了有鱼叉这个词

2023-08-19 23:26 UTC, luoxueyasha commented on projects/1.16/assets/apotheosis/apotheosis/lang/zh_cn.json
> +  "enchantment.apotheosis.earths_boon": "地球的恩惠",
```suggestion
  "enchantment.apotheosis.earths_boon": "大地的恩惠",
```
minecraft里大概没有`地*球*`这个概念

2023-08-19 23:27 UTC, luoxueyasha commented on projects/1.16/assets/apotheosis/apotheosis/lang/zh_cn.json
> +  "enchantment.apotheosis.spearfishing.desc": "用投掷的三叉戟杀人可能会抓到一条鱼。",
```suggestion
  "enchantment.apotheosis.spearfishing.desc": "投掷三叉戟杀死生物时可能会抓到一条鱼。",
```

2023-08-19 23:29 UTC, luoxueyasha commented on projects/1.16/assets/apotheosis/apotheosis/lang/zh_cn.json
> +  "enchantment.apotheosis.chainsaw.desc": "将树砍倒。",
```suggestion
  "enchantment.apotheosis.chainsaw.desc": "砍倒整颗树。",
```

2023-08-26 04:18 UTC, Cactusstudent commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@MrHengyin

2023-09-03 09:36 UTC, ChuijkYahus commented
- 该提交由于[7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)将被关闭，请知晓。若仍想维护可选择Reopen此提交或重新打开新提交，并查看本提交内的审查意见并进行更改。

@MrHengyin

2023-09-03 09:36 UTC, closed without merging