提交 varied-adventure 模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #3649
Opened 2023-08-11 12:09 UTC by HellXFraud

2023-08-11 12:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3649) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3649) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3649) it.</sub>

2023-08-12 05:59 UTC, ChuijkYahus commented
/sort-keys projects/1.19/assets/varied-adventure/va/lang/en_us.json
/sort-keys projects/1.19/assets/varied-adventure/va/lang/zh_cn.json

2023-08-13 00:26 UTC, luoxueyasha commented
请将 PR 标题改为`Varied Adventure 翻译提交`

2023-08-13 00:27 UTC, luoxueyasha requested changes

2023-08-13 00:27 UTC, luoxueyasha commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "itemGroup.tabvaried_adventure_bosses": "多样化的冒险——Boss",
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/a1fa2c3f-7da1-4914-a021-7d7a00342d3a)
```suggestion
  "itemGroup.tabvaried_adventure_bosses": "多样化的冒险丨Boss",
```
此问题请全文通查

2023-08-18 13:56 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "advancements.cursed_gear.title": "诅咒齿轮",
```suggestion
  "advancements.cursed_gear.title": "诅咒装备",
```

2023-08-18 13:56 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "advancements.give_me_your_soul.descr": "获得灵魂之光.",
```suggestion
  "advancements.give_me_your_soul.descr": "获得灵魂之光。",
```

2023-08-18 13:56 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "advancements.make_scale_armor.title": "海怪装甲",
```suggestion
  "advancements.make_scale_armor.title": "鳞板装甲",
```
原文貌似没有海怪？

2023-08-18 13:56 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "advancements.snake.descr": "杀死一只巴兹里斯克蛇。",
这个貌似有`鸡蛇`的常见称呼
可以看看游戏内是怎么样的

2023-08-18 13:56 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "block.v_a.raw_moerolite_block": "莫洛利特原矿块",
```suggestion
  "block.v_a.raw_moerolite_block": "粗莫洛利特块",
```
见原版`粗铁`/`Raw Iron`
话说moreolite有啥词源吗（）

2023-08-23 03:03 UTC, HellXFraud commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "block.v_a.raw_moerolite_block": "莫洛利特原矿块",
moreolite是音译的，没有找到词源

2023-08-23 03:07 UTC, HellXFraud commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "advancements.snake.descr": "杀死一只巴兹里斯克蛇。",
游戏内是长条蛇（类似娜迦），这个名字能查到现实生物名，巴兹里斯克（毒蜥科），现实中是爬行类动物不是蛇那样的，skull是他发射的实体的射弹（有但是是个生物实体），是个绿色骷髅头，就以原版流浪者曾经的名字参考用髑一字（指骷髅头），可能是成就标题名取得不算好？

2023-08-23 03:09 UTC, HellXFraud commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "advancements.make_scale_armor.title": "海怪装甲",
合成物中有个掉落物是生物“海怪”的，这个是成就标题，就想表达是“海怪的装甲”

2023-08-23 05:56 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "advancements.snake.descr": "杀死一只巴兹里斯克蛇。",
现实生物名是从神话生物来的（或者同源但神话生物的起名早于现实生物的命名）
不过随意吧，巴兹里斯克OK的，也准确些

---
不是成就名的问题

2023-09-02 04:49 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "entity.v_a.meadow_runner_spawner": "草原猎手 刷怪笼",
```suggestion
  "entity.v_a.meadow_runner_spawner": "草原猎手刷怪笼",
```

2023-09-02 04:49 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "item.va.basilisk_poison_ball": "鬣蜥毒气",
```suggestion
  "item.va.basilisk_poison_ball": "巴兹里斯克蛇毒气",
```

2023-09-02 04:49 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "item.va.copperolite_hoe": "铜橄榄锄头",
```suggestion
  "item.va.copperolite_hoe": "铜橄榄锄",
```
这个copperolite是铜和moerolite的合金吗
这两种材料分别都长什么样

2023-09-02 04:49 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "item.va.raw_moerolite": "粗莫洛利特矿",
```suggestion
  "item.va.raw_moerolite": "粗莫洛利特",
```

2023-09-02 04:49 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "item.va.main_soul_ball": "灵魂球首",
```suggestion
  "item.va.main_soul_ball": "主要灵魂球",
```
与下方次要灵魂球统一

2023-09-02 04:49 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "item.va.saurian_scales": "巨蜥鳞片",
```suggestion
  "item.va.saurian_scales": "恐蜥鳞片",
```

2023-09-02 04:49 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "item.va.scale_armor_helmet": "鳞板胄",
```suggestion
  "item.va.scale_armor_helmet": "鳞板头盔",
```

2023-09-02 04:49 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "item.v_a.raw_moerolite": "粗莫洛利特矿",
```suggestion
  "item.v_a.raw_moerolite": "粗莫洛利特",
```

2023-09-02 04:49 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "entity.va.swamp_rune": "沼气水晶",
```suggestion
  "entity.va.swamp_rune": "沼泽水晶",
```
这个在游戏内是什么样的

2023-09-02 04:49 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "entity.va.nightmarish_rune": "噩梦水晶",
推荐统一噩梦和梦魇

2023-09-02 04:51 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "item.va.execution_blade": "裁决之刃",
```suggestion
  "item.va.execution_blade": "行刑剑",
```

2023-09-02 04:52 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "item.va.emerald_skull": "翡翠颅骨",
这里为什么不使用绿宝石

2023-09-02 06:11 UTC, HellXFraud commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "item.va.emerald_skull": "翡翠颅骨",
这样翻译更模组化，有一种冒险的风味
```suggestion
  "item.va.emerald_skull": "翡翠颅骨",
```

2023-09-02 06:12 UTC, HellXFraud commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "entity.va.swamp_rune": "沼气水晶",
和下方的梦魇水晶一样，是个自然生成的互动方块

2023-09-02 06:16 UTC, HellXFraud commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "item.va.copperolite_hoe": "铜橄榄锄头",
是这俩的合金，偏绿色，配合翻译工具给出的橄榄色结合翻译为铜橄榄

2023-09-02 06:33 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "item.va.emerald_skull": "翡翠颅骨",
这个物品和原版绿宝石没啥关系就OK（）

2023-09-02 06:37 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "item.va.nightmarish_ashes": "噩梦余烬",
这个叫`梦魇余烬`不知道会不会听上去很怪

2023-09-02 06:37 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "block.v_a.moerolite_ore": "莫洛利特矿石",
这些方块长什么样
copperolite应当和这个的翻译统一

---
-ite一般是矿物等的后缀，建议音译不译，改为`xx石`或`xx金属`等

2023-09-02 06:41 UTC, HellXFraud commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "item.va.emerald_skull": "翡翠颅骨",
对的，没有关联，没有合成配方，是个掉落物

2023-09-02 06:41 UTC, HellXFraud commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "item.va.nightmarish_ashes": "噩梦余烬",
就当是梦魇掉的灰吧（）

2023-09-02 06:45 UTC, HellXFraud commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "block.v_a.moerolite_ore": "莫洛利特矿石",
-ite是矿物后缀的话，那moerolite前面的moerol貌似无从翻译（本人确实找不到对应的参照物），只能音译。copperol由谷歌翻译出来是铜醇，百度无解，也找不到参照物，等我去游戏上看看

2023-09-02 06:57 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "item.va.nightmarish_ashes": "噩梦余烬",
那
```suggestion
  "item.va.nightmarish_ashes": "梦魇余烬",
```
不知道这个怎么样

2023-09-02 06:58 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "block.v_a.moerolite_ore": "莫洛利特矿石",
moerol看游戏内表现
copperolite是**copper**和moer**olite**的组合词，不能拆开-ite来看

---
_-ol确实是醇的后缀（）_

2023-09-02 07:08 UTC, HellXFraud commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "block.v_a.moerolite_ore": "莫洛利特矿石",
moerolite这个矿物的锭本身不能合成对应的工具武器和盔甲，是scale_armor系列和copperolite这个金属锭的材料之一，直接音译不影响就当做是这个模组特有的名词材料。copperolite_ingot合成的盔甲和工具呈黄铜的颜色,copperolite_ingot合成配方是两个铜锭+一个moerolite_ingot。copperolite被百度翻译识别为**斯洛文尼亚语**，就叫铜矿，不知下一步如何翻译

2023-09-02 07:20 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "block.v_a.moerolite_ore": "莫洛利特矿石",
这个moerolite的材质是怎样的

2023-09-02 07:25 UTC, HellXFraud commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "block.v_a.moerolite_ore": "莫洛利特矿石",
绿色。有一点沼泽风格，像是被青苔包裹的样子，我不知道能不能提交图片

2023-09-02 07:30 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "block.v_a.moerolite_ore": "莫洛利特矿石",
把图片拖进对话框就行

2023-09-02 07:33 UTC, HellXFraud commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "block.v_a.moerolite_ore": "莫洛利特矿石",
![1](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/52532723/eedccd13-03c7-46d8-af88-c8e304447b05)
![2](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/52532723/fa44d31b-66e9-4568-8028-42c7627a2a4a)
![3](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/52532723/1f800858-f550-4008-8660-da429dbbfe93)
图1：copperolite_ingot全套
图2：copperolite_ingot合成
图3：moerolite矿石、粗矿块、金属锭块，第二行：moerolite粗矿、金属锭、copperolite_ingot

2023-09-02 08:01 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "block.v_a.moerolite_ore": "莫洛利特矿石",
这个是金属的话直接`莫洛金属`吧
然后copperolite就`铜莫合金`或者`铜莫洛合金`？

2023-09-02 08:16 UTC, HellXFraud commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "block.v_a.moerolite_ore": "莫洛利特矿石",
其实moerolite并不像是金属我也不能确定是不是金属，用金属锭是方便理解（但是他的粗矿烧制和原版那些金属铜铁金一样，掉落模式也一样），锭块踩上去的声音是石头的（就和石头一样不确定是不是作者没改加音效），copperolite没有九合一的块，但是能确定是金属

2023-09-02 08:22 UTC, ChuijkYahus commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "block.v_a.moerolite_ore": "莫洛利特矿石",
那就莫洛石吧
毕竟是虚构材料

2023-09-02 08:40 UTC, ChuijkYahus approved these changes
拉个审核来看

2023-09-09 15:04 UTC, luoxueyasha requested changes

2023-09-09 15:04 UTC, luoxueyasha commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +{
成就描述的译文里有的带句号有的不带句号
建议统一

2023-09-09 15:04 UTC, luoxueyasha commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "block.v_a.stone_tiles": "暗石砖",
额，stone tile在游戏中的样子？
确定是`暗石`吗

2023-09-09 15:04 UTC, luoxueyasha commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "advancements.call_a_monster.descr": "获得一个蛇笛。",
```suggestion
  "advancements.call_a_monster.descr": "获得一支蛇笛。",
```
`一根`之类的应该也行
善用量词，此类问题请全文通查

2023-09-10 01:33 UTC, HellXFraud commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "block.v_a.stone_tiles": "暗石砖",
就是颜色偏暗的石砖，但是既然机器翻译能翻译成 石瓦 ，是我疏忽了，我改一下

2023-09-10 08:04 UTC, luoxueyasha commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "block.v_a.stone_tiles": "暗石砖",
我需要游戏内对应方块的截图
`瓦`不一定是最优解

2023-09-12 12:54 UTC, HellXFraud commented on projects/1.19/assets/varied-adventure/va/lang/zh_cn.json
> +  "block.v_a.stone_tiles": "暗石砖",
![Uploading 暗石.png…]()

2023-09-27 06:26 UTC, HellXFraud commented
审核大大不再来看一下吗？

2023-09-27 21:53 UTC, luoxueyasha approved these changes

2023-09-27 21:55 UTC, luoxueyasha commented
> 审核大大不再来看一下吗？

抱歉，最近比较忙忘了看了
已经approved了，等合并就好

2023-09-30 04:13 UTC, merged