laser-mod 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3653
Opened 2023-08-12 15:56 UTC by mounod

2023-08-12 16:11 UTC, mounod reviewed
原有语法错误更正

2023-08-13 00:24 UTC, luoxueyasha requested changes

2023-08-13 00:24 UTC, luoxueyasha commented on projects/1.16/assets/laser-mod/lasermod/lang/en_us.json
> +	"container.lasermod.laser.button.options"="Options",
原文是否如此（使用等于号而非半角冒号）？

2023-08-13 00:24 UTC, luoxueyasha commented on projects/1.18/assets/laser-mod/lasermod/lang/zh_cn.json
> +	"block.lasermod.laser_catcher": "激光传感器",
实际游戏效果？确定是`传感器`（可以接收输入并提供输出）吗

2023-08-13 00:24 UTC, luoxueyasha commented on projects/1.18/assets/laser-mod/lasermod/lang/zh_cn.json
> +	"death.block.laser": "%s已被激光烧毁",
```suggestion
	"death.block.laser": "%s被激光烧毁了",
```
见 https://minecraft.fandom.com/zh/wiki/%E6%AD%BB%E4%BA%A1%E6%B6%88%E6%81%AF

2023-08-13 00:24 UTC, luoxueyasha commented on projects/1.18/assets/laser-mod/lasermod/lang/zh_cn.json
> +	"death.armor.laser": "%1$s已被%2$s的激光护甲烧毁",
```suggestion
	"death.armor.laser": "%1$s被%2$s的激光护甲烧毁了",
```

2023-08-13 00:24 UTC, luoxueyasha commented on projects/1.18/assets/laser-mod/lasermod/lang/zh_cn.json
> +	"itemGroup.tabLaserMod": "激光模组",
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/f4d2ff03-5c7a-4434-b660-96b4ba2f0939)

不必翻译模组名，不过如果你认为有需要的话，可以忽略这条

2023-08-13 00:24 UTC, luoxueyasha commented on projects/1.18/assets/laser-mod/lasermod/lang/zh_cn.json
> +	"itemGroup.tabLaserMod.upgrades": "激光升级模块",
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/d1014700-ab41-4cdd-a36c-bf54190cec43)
```suggestion
	"itemGroup.tabLaserMod.upgrades": "Laser Mod丨激光升级模块",
```

2023-08-13 00:24 UTC, luoxueyasha commented on projects/1.18/assets/laser-mod/lasermod/lang/zh_cn.json
> +	"key.categories.lasermod": "激光模组",
同上，如果要保留模组名原文请上下统一

2023-08-13 00:24 UTC, luoxueyasha commented on projects/1.18/assets/laser-mod/lasermod/lang/zh_cn.json
> +	"subtitle.lasermod.laser_activate": "激光激活",
```suggestion
	"subtitle.lasermod.laser_activate": "激光：激活",
```
https://minecraft.fandom.com/zh/wiki/%E5%AD%97%E5%B9%95
此类问题请全文通查

2023-08-13 00:24 UTC, luoxueyasha commented on projects/1.18/assets/laser-mod/lasermod/lang/zh_cn.json
> +	"block.lasermod.device_hub": "激光集束器（§4WIP§r）",
具体功能？
原文`Device Hub`

2023-08-13 00:25 UTC, luoxueyasha requested changes

2023-08-13 00:25 UTC, luoxueyasha commented on projects/1.16/assets/laser-mod/lasermod/lang/zh_cn.json
> +	"itemGroup.tabLaserMod.upgrades" : "Laser Mod Upgrades"
？

2023-08-13 03:32 UTC, mounod commented on projects/1.16/assets/laser-mod/lasermod/lang/en_us.json
> +	"container.lasermod.laser.button.options"="Options",
是的，仅在1.16版本下en_us.json这部分作者使用了等于号

2023-08-13 03:36 UTC, mounod commented on projects/1.16/assets/laser-mod/lasermod/lang/en_us.json
> +	"container.lasermod.laser.button.options"="Options",
> 原文是否如此（使用等于号而非半角冒号）？

是的，仅在1.16版本下en_us.json这部分作者使用了等于号

2023-08-13 03:41 UTC, mounod commented on projects/1.18/assets/laser-mod/lasermod/lang/zh_cn.json
> +	"block.lasermod.laser_catcher": "激光传感器",
> 实际游戏效果？确定是`传感器`（可以接收输入并提供输出）吗

是的
![2023-08-13_11 35 26](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/69347062/b22f389e-d0cd-4d8c-afaf-bb52d1e1ea66)

2023-08-13 03:45 UTC, mounod commented on projects/1.18/assets/laser-mod/lasermod/lang/zh_cn.json
> +	"block.lasermod.device_hub": "激光集束器（§4WIP§r）",
目前来说没有实装

2023-08-13 04:08 UTC, mounod commented on projects/1.18/assets/laser-mod/lasermod/lang/zh_cn.json
> +	"block.lasermod.device_hub": "激光集束器（§4WIP§r）",
原文为Device Hub (§4WIP§r)
但暂未在游戏中实装

2023-08-13 04:11 UTC, mounod reviewed
错误修正

2023-08-13 04:22 UTC, mounod commented on projects/1.18/assets/laser-mod/lasermod/lang/zh_cn.json
> +	"block.lasermod.device_hub": "激光集束器（§4WIP§r）",
> 原文为Device Hub (§4WIP§r)
> 但暂未在游戏中实装

原文为Device Hub (§4WIP§r)
但暂未在游戏中实装

2023-08-13 04:23 UTC, mounod commented on projects/1.18/assets/laser-mod/lasermod/lang/zh_cn.json
> +	"block.lasermod.device_hub": "激光集束器（§4WIP§r）",
> 具体功能？ 原文`Device Hub`

原文为Device Hub (§4WIP§r)
但暂未在游戏中实装

2023-08-13 06:28 UTC, luoxueyasha commented on projects/1.18/assets/laser-mod/lasermod/lang/zh_cn.json
> +	"block.lasermod.device_hub": "激光集束器（§4WIP§r）",
感觉是设备的hub（集线器）
具体建议翻翻作者动态之类的（？

2023-08-13 06:31 UTC, luoxueyasha requested changes

2023-08-13 06:31 UTC, luoxueyasha commented on projects/1.18/assets/laser-mod/lasermod/lang/zh_cn.json
> +	"subtitle.lasermod.laser_activate": "激光：激活",
`激光`是怎么被`激活`的？

2023-08-13 07:00 UTC, mounod commented on projects/1.18/assets/laser-mod/lasermod/lang/zh_cn.json
> +	"subtitle.lasermod.laser_activate": "激光：激活",
> `激光`是怎么被`激活`的？ 感觉像是`启动`，不过具体还得以游戏为准

是红石激活，在启用的一刻是`subtitle.lasermod.laser_activate`
之后如果没装静音模块的话一直会有`subtitle.lasermod.laser_active`
在停止时会有`subtitle.lasermod.laser_deactivate`

2023-08-13 07:07 UTC, mounod commented on projects/1.18/assets/laser-mod/lasermod/lang/zh_cn.json
> +	"block.lasermod.device_hub": "激光集束器（§4WIP§r）",
作者并没有透露过多，暂译为`激光集线器（§4WIP§r）`吧

2023-08-13 12:55 UTC, dovisutu commented on projects/1.16/assets/laser-mod/lasermod/lang/zh_cn.json
> +	"container.lasermod.laser.blue": "蓝(B)"
> 回复模板：_如无排版需要等特殊要求，请将翻译文本中的**标点**（不包括`%3$s` `§r`等标记符和JSON格式的半角引号等）全部改为**全角**标点。_

2023-08-13 17:02 UTC, mamaruo reviewed
### 翻译建议：

另外不必频繁请求review。

Tier %s	%s级
Laser Armor | 激光盔甲
Printed Circuit Board 印制电路板

2023-08-13 17:02 UTC, mamaruo commented on projects/1.18/assets/laser-mod/lasermod/lang/zh_cn.json
> +	"subtitle.lasermod.laser_activate": "激光：激活",
那么建议 laser_active 译作“激光：正在照射”“激光：运行中”

2023-08-15 09:00 UTC, mounod commented
> ### 翻译建议：
> 另外不必频繁请求review。
> 
> Tier %s %s级 Laser Armor | 激光盔甲 Printed Circuit Board 印制电路板

1.模组中大多数模块都只有1级，我觉得1级不如等级1来的好听
23已更改

2023-08-19 23:25 UTC, luoxueyasha requested changes
个人感觉没问题了
可能需要另一位审核协助

2023-08-19 23:28 UTC, luoxueyasha approved these changes

2023-08-20 01:28 UTC, dovisutu approved these changes

2023-08-21 02:21 UTC, merged