Ultimate-Solar-Panels 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3658
Opened 2023-08-13 09:43 UTC by mounod

2023-08-14 03:38 UTC, Cactusstudent requested changes
请全文通查

2023-08-14 03:38 UTC, Cactusstudent commented on projects/1.16/assets/ultimate-solar-panels/ultimatesolarpanels/lang/zh_cn.json
> +  "block.ultimatesolarpanels.advanced_solar_panel": "§7高级太阳能发电机",
原文：**Advanced Solar Panel**，“机”恐怕不太对吧？

2023-08-14 03:38 UTC, Cactusstudent commented on projects/1.16/assets/ultimate-solar-panels/ultimatesolarpanels/lang/zh_cn.json
> +  "item.ultimatesolarpanels.basic_solar_array": "基础太阳能板",
原文：**Basic Solar Array**

2023-08-14 04:12 UTC, mounod commented on projects/1.16/assets/ultimate-solar-panels/ultimatesolarpanels/lang/zh_cn.json
> +  "block.ultimatesolarpanels.advanced_solar_panel": "§7高级太阳能发电机",
作者想把工业2中高级太阳能移植到高版本，所以延续了原有译名

2023-08-14 04:12 UTC, mounod commented on projects/1.16/assets/ultimate-solar-panels/ultimatesolarpanels/lang/zh_cn.json
> +  "block.ultimatesolarpanels.advanced_solar_panel": "§7高级太阳能发电机",
> 原文：**Advanced Solar Panel**，“机”恐怕不太对吧？

作者想把工业2中高级太阳能移植到高版本，所以延续了原有译名
https://www.mcmod.cn/class/23.html

2023-08-15 07:30 UTC, Cactusstudent submitted a review, later dismissed
看起来没什么问题了？

2023-08-19 17:03 UTC, ChuijkYahus commented on projects/1.16/assets/ultimate-solar-panels/ultimatesolarpanels/lang/zh_cn.json
> +  "block.ultimatesolarpanels.machine_block_improved": "§e机器外壳 (硬化)",
```suggestion
  "block.ultimatesolarpanels.machine_block_improved": "§e机器外壳（硬化）",
```

2023-08-19 17:03 UTC, ChuijkYahus commented on projects/1.18/assets/ultimate-solar-panels/ultimatesolarpanels/lang/zh_cn.json
> +  "block.ultimatesolarpanels.quantum_solar_panel": "量子太阳能发电机",
```suggestion
  "block.ultimatesolarpanels.quantum_solar_panel": "§d量子太阳能发电机",
```
原文貌似有颜色代码？

2023-08-22 04:59 UTC, ChuijkYahus approved these changes
个人感觉没啥问题了
拉个审核看一眼

2023-08-22 05:01 UTC, Cactusstudent approved these changes

2023-08-23 06:12 UTC, merged