Mythic mobs 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3663
Opened 2023-08-14 15:29 UTC by Neotritium

2023-08-14 15:45 UTC, Neotritium commented
我该如何上传/assets/mythicmobs/patchouli_book/下的帕秋莉手册汉化？

2023-08-14 16:36 UTC, mamaruo commented
> 我该如何上传/assets/mythicmobs/patchouli_book/下的帕秋莉手册汉化？

patchouli_book 文件夹与 lang 同级对吧，所以 文件夹下的语言文件怎么加，帕秋莉就怎么加

2023-08-14 18:55 UTC, Neotritium commented
我明白了，感谢！

2023-08-15 07:28 UTC, Cactusstudent requested changes

2023-08-15 07:28 UTC, Cactusstudent commented on projects/1.20-fabric/assets/mythic-mobs/mythicmobs/lang/zh_cn.json
> +  "advancements.mythicmobs.description": "一个神话世界!",
```suggestion
  "advancements.mythicmobs.description": "一个神话世界！",
```
除patchouli格式符号外，应使用全角符号，请全文通查

2023-08-19 18:25 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-mobs/mythicmobs/lang/zh_cn.json
> +  "advancements.kobold_trade.description": "和你的朋友亲近,更要和你的敌人“亲近”！",
```suggestion
  "advancements.kobold_trade.description": "和你的朋友亲近，更要和你的敌人“亲近”！",
```

2023-08-19 18:25 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-mobs/mythicmobs/lang/zh_cn.json
> +  "entity.mythicmobs.mushroom_thing": "孢苗",
```suggestion
  "entity.mythicmobs.mushroom_thing": "孢灵",
```
可能这样更好听些，仅建议

2023-08-19 18:25 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-mobs/mythicmobs/lang/zh_cn.json
> +  "mythicmobs.midnightconfig.koboldWarriorArmor": "寇伯战士防御值",
```suggestion
  "mythicmobs.midnightconfig.koboldWarriorArmor": "寇伯战士护甲值",
```
需游戏内实测

2023-08-19 18:25 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-mobs/mythicmobs/lang/zh_cn.json
> +  "mythicmobs.midnightconfig.brownMushroomLines": "棕色蘑菇对话"
其中Sporeling需与上方统一

2023-08-19 18:25 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-mobs/mythicmobs/patchouli_books/mythical_guide_book/zh_cn/entries/mobs/drake.json
> +      "text": "无翼龙是可以被驯服的小型生物，它会向它的主人表达最大的忠诚，并心甘情愿在主人的一声令下献出生命。请注意让它们远离家畜，特别是鸡。无翼龙还天生热衷于食用卓柏卡布拉肉串。"
```suggestion
      "text": "无翼龙是可以被驯服的小型生物，它会向它的主人表达极致的忠诚，并心甘情愿为主人的一句命令而献出生命。请注意让它们远离家畜，特别是鸡。无翼龙还天生热衷于食用卓柏卡布拉肉串。"
```
微调

2023-08-19 18:25 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-mobs/mythicmobs/patchouli_books/mythical_guide_book/zh_cn/entries/mobs/kobold.json
> +      "text": "寇伯是一种被动生物，考虑到玩家对它们没有恶意，它们不会主动伤害玩家。它们以狡诈和自私著称，并且可以和玩家交易。但是，交易者应该记住，寇伯的报价非常挑剔。"
```suggestion
      "text": "寇伯是一种被动生物，假如玩家对它们没有恶意，它们便不会主动伤害玩家。它们以狡诈和自私著称，并且可以和玩家交易。但是，交易者应该记住，寇伯的报价非常挑剔。"
```

2023-08-19 18:25 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-mobs/mythicmobs/patchouli_books/mythical_guide_book/zh_cn/entries/mobs/kobold_warrior.json
> +      "text": "寇伯战士是寇伯一族的保护者。它们尖利的牙齿和敏捷的腿脚使他们可以让任何找寇伯麻烦的人付出代价。但是，如果有人试图击败寇伯，他就有了获得轻便而强大的寇伯长矛作为战利品的机会。"
```suggestion
      "text": "寇伯战士是寇伯一族的保护者。它们尖利的长矛和敏捷的腿脚使他们可以让任何找寇伯麻烦的人付出代价。但是，如果有人成功击败寇伯，他就有机会获得轻便而强大的寇伯长矛以作战利品。"
```
微调

2023-08-19 18:25 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-mobs/mythicmobs/lang/zh_cn.json
> +  "book.mythicmobs.description": "走进神话生物的领域，那里有许多传说中的生物等待着你的发现。你将遇到一系列神秘的生物，开始惊险的冒险，其中一些是盟友，而另一些可能会带来挑战。把这本书放在手边，当你想要深入研究那些迎面走过的生物所拥有的引人入胜的故事时，它将会提供一个迷人的纲要。",
```suggestion
  "book.mythicmobs.description": "走进神话生物的领域，许多传说生物等待着你的发现。你将遇到一系列神秘的生物，开始惊险的冒险，其中一些是盟友，而另一些可能会造成威胁。把这本书放在手边，当你想要深入研究那些所遭遇生物的引人入胜的故事时，它会是一本极具魅力的纲要。",
```
属于是乱改了（）

2023-08-20 05:20 UTC, Neotritium commented on projects/1.20-fabric/assets/mythic-mobs/mythicmobs/lang/zh_cn.json
> +  "entity.mythicmobs.mushroom_thing": "孢苗",
挺好的，谢谢建议

2023-08-20 05:21 UTC, Neotritium commented on projects/1.20-fabric/assets/mythic-mobs/mythicmobs/lang/zh_cn.json
> +  "advancements.kobold_trade.description": "和你的朋友亲近,更要和你的敌人“亲近”！",
居然还有半角，真是抱歉了……

2023-08-20 05:24 UTC, Neotritium commented on projects/1.20-fabric/assets/mythic-mobs/mythicmobs/lang/zh_cn.json
> +  "book.mythicmobs.description": "走进神话生物的领域，那里有许多传说中的生物等待着你的发现。你将遇到一系列神秘的生物，开始惊险的冒险，其中一些是盟友，而另一些可能会带来挑战。把这本书放在手边，当你想要深入研究那些迎面走过的生物所拥有的引人入胜的故事时，它将会提供一个迷人的纲要。",
很好的改动，流畅了许多，谢谢！

2023-08-20 10:56 UTC, ChuijkYahus reviewed
也请注意查看帕秋莉部分的审核

2023-08-20 10:56 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-mobs/mythicmobs/patchouli_books/mythical_guide_book/zh_cn/entries/mobs/mushroom.json
> +  "name": "孢苗",
```suggestion
  "name": "孢灵",
```
统一

2023-08-21 14:50 UTC, Neotritium commented on projects/1.20-fabric/assets/mythic-mobs/mythicmobs/patchouli_books/mythical_guide_book/zh_cn/entries/mobs/mushroom.json
> +  "name": "孢苗",
这两天有点忙，忘了改…谢谢提醒

2023-08-21 14:51 UTC, Neotritium commented on projects/1.20-fabric/assets/mythic-mobs/mythicmobs/lang/zh_cn.json
> +  "mythicmobs.midnightconfig.koboldWarriorArmor": "寇伯战士防御值",
已实测，翻译应该无误

2023-08-21 16:35 UTC, ChuijkYahus approved these changes

2023-08-22 04:56 UTC, Cactusstudent approved these changes

2023-08-23 06:12 UTC, merged