Scroll of Harvests 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3690
Opened 2023-08-20 05:13 UTC by ChuijkYahus

2023-08-20 05:15 UTC, ChuijkYahus commented
/mv-recursive "projects/1.18/assets/scroll-of-harvests/harvest/" "projects/1.18/assets/scroll-of-harvests/harvests/"
/mv-recursive "projects/1.19/assets/scroll-of-harvests/harvest/" "projects/1.19/assets/scroll-of-harvests/harvests/"
/mv-recursive "projects/1.20/assets/scroll-of-harvests/harvest/" "projects/1.20/assets/scroll-of-harvests/harvests/"

2023-08-20 05:17 UTC, ChuijkYahus commented
此模组1.18.2最新版为1.3.0

2023-08-21 02:42 UTC, Cactusstudent commented on projects/1.18/assets/scroll-of-harvests/harvests/lang/zh_cn.json
> +    "harvests.material.tooltip": "修复该等级工具所需的材料，通常这些材料也用于该等级工具的合成配方",
考虑吧“该等级”改为“该品质”吗？

2023-08-21 06:48 UTC, ChuijkYahus commented on projects/1.18/assets/scroll-of-harvests/harvests/lang/zh_cn.json
> +    "harvests.material.tooltip": "修复该等级工具所需的材料，通常这些材料也用于该等级工具的合成配方",
那样需要把全文的几乎所有等级一词全部换成品质
也就是Tier这个词的翻译

2023-08-26 03:55 UTC, Cactusstudent requested changes

2023-08-26 03:55 UTC, Cactusstudent commented on projects/1.18/assets/scroll-of-harvests/harvests/lang/zh_cn.json
> +    "harvests.material.tooltip": "修复该等级工具所需的材料，通常这些材料也用于该等级工具的合成配方",
建议换，毕竟这属于原版用词了

2023-08-26 09:14 UTC, Cactusstudent approved these changes

2023-08-27 13:42 UTC, merged