MTR Addon Sign 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3691
Opened 2023-08-20 07:19 UTC by iamliuzy

2023-08-20 07:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3691) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3691) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3691) it.</sub>

2023-08-21 06:19 UTC, iamliuzy commented
/mv-recursive "projects/1.18/assets/mrt-addon-sign/mtr_addon_sign_fabric_/" "projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/

2023-08-21 07:26 UTC, dovisutu commented
* 似乎有些位置未译？是有意如此吗？

2023-08-21 18:51 UTC, ChuijkYahus requested changes

2023-08-21 18:51 UTC, ChuijkYahus commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.towhundredmetre": "Switch in 200m",
```suggestion
  "block.mtr_addon_sign_fabric_.towhundredmetre": "200米后变轨",
```
瞎猜的（）
需游戏内查证并全文通查

2023-08-21 18:51 UTC, ChuijkYahus commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.tunnelwithshortborder": "Tunnel with short border",
```suggestion
  "block.mtr_addon_sign_fabric_.tunnelwithshortborder": "窄距隧道",
```
不知道是否是术语

2023-08-21 18:51 UTC, ChuijkYahus commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.wheezing": "Wheez",
这个是鸣笛吗

2023-08-22 05:13 UTC, iamliuzy commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.towhundredmetre": "Switch in 200m",
好，我进游戏看看

2023-08-22 06:15 UTC, iamliuzy commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.down": "One way not authorised",
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/59107734/1b9c01a0-aef0-4f27-9023-096ffde2c95f)

2023-08-22 06:15 UTC, iamliuzy commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.down": "One way not authorised",
是不是反向通行的意思？

2023-08-22 06:16 UTC, iamliuzy commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.wheezing": "Wheez",
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/59107734/13d8ba7a-8228-4bd7-bf54-408455fd265d)

可能吧

2023-08-22 06:17 UTC, iamliuzy commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.turnback": "Turnback",
前方铁轨终点？
![Uploading image.png…]()

2023-08-22 06:20 UTC, iamliuzy commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.turnback": "Turnback",
是不是折返的意思？

2023-08-22 06:23 UTC, iamliuzy commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.wheezing": "Wheez",
但是英语没有`Wheez`这个词，只有`Wheeze`，不知是不是作者打错了。
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/59107734/6c0fe36c-3d13-4e52-bc68-54a07fba8d5d)

2023-08-22 19:47 UTC, ChuijkYahus commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.wheezing": "Wheez",
怪（）
要问下对这方面了解的人了

2023-08-26 04:20 UTC, ChuijkYahus commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.wheezing": "Wheez",
经查证，确为法国铁路鸣笛标志
![R`P%WK%HNR2~UE2@N(8R1R3](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/93b7b482-22c0-4d8f-a1f5-e375a87b860d)
https://en.wikipedia.org/wiki/French_railway_signalling

2023-08-26 08:54 UTC, dovisutu commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.towhundredmetre": "Switch in 200m",
switch有可能是道岔？虽然据我所指MTR没有专门的道岔，都是直接暴力接轨的（

2023-08-26 09:01 UTC, ChuijkYahus commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.towhundredmetre": "Switch in 200m",
没能在法国铁路标找到完全一致的（）
有图像类似但意义不大一样的
![PM24JVA%%5XI3G`%S``HEK](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/bd06ec01-14c4-4c6e-ace9-bbb98ffbc5a5)

2023-08-27 05:15 UTC, dovisutu commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.towhundredmetre": "Switch in 200m",
查了一下，国铁里面这种斜杠好像是画在车站前1/2个信号灯柱子上的，好像更不一样了...
![snapshot_2023-08-27-13-15-38.png](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/40313014/73d73615-0967-4680-8487-65526df118b6)

2023-09-01 12:33 UTC, iamliuzy commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.wheezing": "Wheez",
好的

2023-09-01 12:43 UTC, iamliuzy commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.towhundredmetre": "Switch in 200m",
是不是距离前方道岔的距离？

2023-09-01 12:48 UTC, iamliuzy commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.towhundredmetre": "Switch in 200m",
```suggestion
  "block.mtr_addon_sign_fabric_.towhundredmetre": "前方200米道岔",
```

2023-09-01 12:51 UTC, iamliuzy commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.threhundredmtre": "Switch in 300m",
```suggestion
  "block.mtr_addon_sign_fabric_.threhundredmtre": "前方300米道岔",
```

2023-09-01 12:51 UTC, iamliuzy commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.hundredmetre": "Switch in 100m",
前方300米道岔

2023-09-01 15:43 UTC, ChuijkYahus commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.towhundredmetre": "Switch in 200m",
就先按这个来吧
*貌似一般是拿来标记多少米后有个信号的*

2023-09-02 04:57 UTC, iamliuzy commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.towhundredmetre": "Switch in 200m",
行

2023-09-02 05:00 UTC, iamliuzy commented
改过了，重新看一遍吧。

2023-09-02 05:13 UTC, ChuijkYahus commented on projects/1.18/assets/mrt-addon-sign/addon_mtr_signal_sign/lang/zh_cn.json
> +  "block.mtr_addon_sign_fabric_.hundredmetre": "距信号100米",
```suggestion
  "block.mtr_addon_sign_fabric_.hundredmetre": "距信号机100米",
```
上下统一

2023-09-02 05:14 UTC, ChuijkYahus reviewed
其他应该没什么问题了

2023-09-02 06:31 UTC, ChuijkYahus approved these changes

2023-09-02 10:50 UTC, dovisutu approved these changes

2023-09-03 09:20 UTC, merged