assemblylinemachines 翻译修正以及帕秋莉手册翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3692
Opened 2023-08-20 08:06 UTC by NianGuu

2023-08-20 08:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3692) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3692) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3692) it.</sub>

2023-08-20 08:08 UTC, NianGuu commented
/update-en assemblylinemachines 1.19

2023-08-29 12:51 UTC, Cyl18 commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/age4.json
> +			"text": " 此外你也可以通过熵反应堆制造世界腐化来获取$(3)棱镜玫瑰$()。只需要将一些小花，比如虞美人或者蒲公英，放置在熵反应堆附近即可获取棱镜玫瑰。$(p)将棱镜玫瑰在磨粉机中制成$(item)棱镜粉$()。"
```suggestion
			"text": "此外你也可以通过熵反应堆制造世界腐化来获取$(3)棱镜玫瑰$()。只需要将一些小花，比如虞美人或者蒲公英，放置在熵反应堆附近即可获取棱镜玫瑰。$(p)将棱镜玫瑰在磨粉机中制成$(item)棱镜粉$()。"
```

2023-08-29 12:53 UTC, Cyl18 commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/age4.json
> +			"title": "Further Reading",
未翻译

2023-08-29 12:54 UTC, Cyl18 commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/age3.json
> +			"text": "你拥有了黑色花岗岩，现在你可以制作$(item)基础能量管道$()，一个$(item)曲柄引擎$()还有一个$(item)电力净化仓。$()曲柄引擎从齿轮箱的动能中产生能量。$()$(p)$(l:blocks/pipes)点击这个连接以了解更多关于管道的信息。$(/l)"
```suggestion
			"text": "你拥有了黑色花岗岩，现在你可以制作一些$(item)基础能量管道$()，一个$(item)曲柄引擎$()还有一个$(item)电力净化仓。$()曲柄引擎从齿轮箱的动能中产生能量。$()$(p)$(l:blocks/pipes)点击这个链接以了解更多关于管道的信息。$(/l)"
```

2023-08-29 12:59 UTC, Cyl18 commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/age2.json
> +			"text": "你可以像使用曲柄一样，将它对准一个简易机器来使用$(item)齿轮箱$()。加入燃料，齿轮箱就会自己转动。$(p)$(item)简易曲柄充能器$()是较为独特的，他只接受齿轮箱而不接受曲柄。$(br)$(c)齿轮箱需要用充能煤炭来运行。$(2)想要改变它吗？插入一个$(l:items/upgrades#gearboxcompatability)升级$(/l)使他可以使用任
```suggestion
			"text": "你可以像使用曲柄一样，将它对准一个简易机器来使用$(item)齿轮箱$()。加入燃料，齿轮箱就会自己转动。$(p)$(item)简易曲柄充能器$()是较为独特的，他只接受齿轮箱而不接受曲柄。$(br)$(c)齿轮箱需要用充能煤炭来运行。$(2)想要改变它吗？插入一个$(l:items/upgrades#gearboxcompatability)升级$(/l)使它可以使用任何燃料。"
```

2023-08-29 13:04 UTC, Cyl18 commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/blocks/quantum_link.json
> +			"text": "一旦量子连接器成功连接，传送门动画会显示在正方形上。太棒了！$(p)现在你可以设置你的能量、流体以及物品传输方式。它可以设置成输入（Send）模式、输出（Receive）模式或者禁用(Disable)模式。一旦配置完成，物品会像变魔术一样在连接之间传输。$(p)$(c)警告：量子连接器不会加载区块，因此你需要自己确保区块加载以使量子连接器保持运行。"
```suggestion
			"text": "一旦量子连接器成功连接，传送门动画会显示在正方形上。太棒了！$(p)现在你可以设置你的能量、流体以及物品传输方式。它可以设置成输入（Send）模式、输出（Receive）模式或者禁用（Disable）模式。一旦配置完成，物品会像变魔术一样在连接之间传输。$(p)$(c)警告：量子连接器不会加载区块，因此你需要自己确保区块加载以使量子连接器保持运行。"
```

2023-08-29 13:04 UTC, Cyl18 commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/blocks/quantum_link.json
> +			"text": "一旦量子连接器成功连接，传送门动画会显示在正方形上。太棒了！$(p)现在你可以设置你的能量、流体以及物品传输方式。它可以设置成输入（Send）模式、输出（Receive）模式或者禁用(Disable)模式。一旦配置完成，物品会像变魔术一样在连接之间传输。$(p)$(c)警告：量子连接器不会加载区块，因此你需要自己确保区块加载以使量子连接器保持运行。"
正方形？

2023-08-29 13:05 UTC, Cyl18 commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/blocks/generators.json
> +			"text": "这个装置最多能储存2.5MFE。$(p)它也能自动从周围的方块中输入/输出能量，最高速度可达2FKFE/t。"
```suggestion
			"text": "这个装置最多能储存2.5MFE。$(p)它也能自动从周围的方块中输入/输出能量，最高速度可达2KFE/t。"
```

2023-08-29 13:08 UTC, Cyl18 commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/blocks/item_processing.json
> +			"text": "这个方块可以存储最多十个配方（需要升级），并且都可以递归处理。$(p)物品可以适当地放置在合成网格中填充为一根幽灵配方。一旦配方合适，按下复选框来完成设置。"
```suggestion
			"text": "这个方块可以存储最多十个配方（需要升级），并且都可以递归处理。$(p)物品可以适当地放置在合成网格中填充为一个幽灵配方。一旦配方合适，按下复选框来完成设置。"
```

2023-08-29 13:09 UTC, Cyl18 commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/blocks/mkii_machines.json
> +			"text": "MKII气动压缩机有一个特性,它的内部存储了所有可用的模具，可以简单快速地热插拔。"
```suggestion
			"text": "MKII气动压缩机有一个特性，它的内部存储了所有可用的模具，可以简单快速地热插拔。"
```

2023-08-29 13:10 UTC, Cyl18 commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/blocks/corrupting_basin.json
> +			"text": "现在你拥有了$(l:age4#novasteel)新星钢锭,$()你可以用一种更简单的方式来制造鈇锭：腐化盆。"
```suggestion
			"text": "现在你拥有了$(l:age4#novasteel)新星钢锭，$()你可以用一种更简单的方式来制造鈇锭：腐化盆。"
```

2023-08-29 13:11 UTC, Cyl18 commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/blocks/liquids.json
> +			"text": "浓缩虚空在末地中探测发现，这种剧烈的液体极其不稳定,一旦被放置，将是致命的、具有破坏性的、令人不快的。它会分解所有的石头并且彻底破坏所有的天然材料。$(p)$(c)使用者后果自负。"
```suggestion
			"text": "浓缩虚空在末地中探测发现，这种剧烈的液体极其不稳定，一旦被放置，将是致命的、具有破坏性的、令人不快的。它会分解所有的石头并且彻底破坏所有的天然材料。$(p)$(c)使用者后果自负。"
```

2023-08-29 13:13 UTC, Cyl18 commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/blocks/experience_handling.json
> +			"text": "这个方块有如下几个选项：$(li)附魔模式,这将会应用一个随机的附魔到工具或物品上，$(li)铁砧模式，这将结合物品以修复耐久或结合附魔，$(li)书模式，这将消耗一个催化物品与一本普通的书，并且制作一本附魔书作为产物！$(br)此外，还需要一个独特的升级来增加机器的功率。"
```suggestion
			"text": "这个方块有如下几个选项：$(li)附魔模式，这将会应用一个随机的附魔到工具或物品上，$(li)铁砧模式，这将结合物品以修复耐久或结合附魔，$(li)书模式，这将消耗一个催化物品与一本普通的书，并且制作一本附魔书作为产物！$(br)此外，还需要一个独特的升级来增加机器的功率。"
```

2023-08-29 13:15 UTC, Cyl18 commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/blocks/entropy_reactor.json
> +			"text": "当然，避免低效的产能并非维持高$(6)多样化评级$()的唯一原因。$(br)长期维持较低的$(6)多样化评级$()将使你的堆芯充满$(c)熵（Entropty）$()，这是一种危险的化合物，含量越高越容易产生负面影响。$(br)$(c)如果堆芯完全饱和，反应堆将会爆炸。$()$(p)通过提高$(6)多样化评级$()，熵含量会再次变低。"
```suggestion
			"text": "当然，避免低效的产能并非维持高$(6)多样化评级$()的唯一原因。$(br)长期维持较低的$(6)多样化评级$()将使你的堆芯充满$(c)熵（Entropy）$()，这是一种危险的化合物，含量越高越容易产生负面影响。$(br)$(c)如果堆芯完全饱和，反应堆将会爆炸。$()$(p)通过提高$(6)多样化评级$()，熵含量会再次变低。"
```

2023-08-29 13:15 UTC, Cyl18 commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/blocks/entropy_reactor.json
> +			"text": "$(2)熵约束器升级$()会使反应堆只产生$(c)熵$()而非FE,并且只会产生$(d)世界腐化（World Corruption）$()而非其他负面影响。"
```suggestion
			"text": "$(2)熵约束器升级$()会使反应堆只产生$(c)熵$()而非FE，并且只会产生$(d)世界腐化（World Corruption）$()而非其他负面影响。"
```

2023-08-29 13:16 UTC, Cyl18 commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/blocks/pipes.json
> +			"text": "一旦你能够制作管道，它将是一种到处运输能量、液体以及物品的好办法。$(p)首先用管道SHIFT并右键你想连接的两个方块,即可将它们连接起来。然后你可以右击连接处配置它们。"
```suggestion
			"text": "一旦你能够制作管道，它将是一种到处运输能量、液体以及物品的好办法。$(p)用管道SHIFT并右键你想连接的两个方块，即可将它们连接起来。然后你可以右击连接处配置它们。"
```

2023-08-29 13:18 UTC, Cyl18 commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/items/novasteel_tools.json
> +			"text": "$(item)石墨烯锭$()是制作新星钢工具需要用到的一种合金。$(p)首先，你需要制造液态碳。将一份煤炭和$(9)1,000mB水$()放入精炼厂可以制作100mB液态碳。然后，你需要将$(b)钻石粉$()和4000mB液态碳通入加成反应精炼厂以制作一个石墨烯锭。"
```suggestion
			"text": "$(item)石墨烯锭$()是制作新星钢工具需要用到的一种合金。$(p)首先，你需要制造液态碳。将一份煤炭和$(9)1000mB水$()放入精炼厂可以制作100mB液态碳。然后，你需要将$(b)钻石粉$()和4000mB液态碳通入加成反应精炼厂以制作一个石墨烯锭。"
```

2023-08-29 13:19 UTC, Cyl18 commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/items/internal_water_generator.json
> +			"text": "$(item)内置无限水单元$()可以在任意储罐上SHIFT右键安装。一旦装上升级并且倒入一桶水，储罐内将会$(6)变得无限$()。"
有点不通顺

2023-08-29 13:20 UTC, Cyl18 commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/items/enchantments.json
> +			"text": "这是一些可获得的附魔，可以使新加入的物品变得更有用。所有附魔都可以在一个普通的附魔台中获得，并且支持到$(d)附魔 Level 10$()。"
英文原文：
` and support up to $(d)Enchantment Level X`
需要修改

2023-08-29 13:23 UTC, Cyl18 requested changes
感谢你的提交~
通读了一遍改了改病句和标点，没有什么大问题了

2023-08-30 09:40 UTC, NianGuu commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/blocks/quantum_link.json
> +			"text": "一旦量子连接器成功连接，传送门动画会显示在正方形上。太棒了！$(p)现在你可以设置你的能量、流体以及物品传输方式。它可以设置成输入（Send）模式、输出（Receive）模式或者禁用(Disable)模式。一旦配置完成，物品会像变魔术一样在连接之间传输。$(p)$(c)警告：量子连接器不会加载区块，因此你需要自己确保区块加载以使量子连接器保持运行。"
> 正方形？

确实是个正方形，挺大的 ，就摆在ui中间

2024-09-05 01:51 UTC, dovisutu reviewed
抱歉很久没有审核
后面会过一遍手册，过完应该就可以合并了

2024-09-05 01:51 UTC, dovisutu commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/lang/zh_cn.json
> +	"item.assemblylinemachines.greenhouse_upgrade_interdimensional_specialization": "温室升级：跨纬度的专精",
纬度 -or- 维度？

2024-09-05 04:21 UTC, dovisutu commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/categories/blocks.json
> +	"description": "本文将深入介绍一些在概览中未涉及到的机器。$(p)强烈建议安装$(l:https://www.curseforge.com/minecraft/mc-mods/jei)Just Enough Items$()模组，本章节只会涉及部分相关合成。",
```suggestion
	"description": "本文将深入介绍一些在概览中未涉及到的机器。$(p)强烈建议安装$(l:https://www.curseforge.com/minecraft/mc-mods/jei)Just Enough Items$()模组，因为本章节不会详细介绍相关合成。",
```

2024-09-05 04:27 UTC, dovisutu commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/age1.json
> +			"text": "尝试将液缸中的沙砾和沙子与水混合以得到$(item)淤泥$()。配方完成后将会改变颜色！然后就可以开始搅拌了。$(c)错误的配方会变成黑色。SHIFT并右键可以清除它。$(thing)你可以通过这种方式获得污泥！$()$(p)你需要12个淤泥以发展后续。当你制作完成后，你可以制作淤泥砖以及手工操作的磨石。"
```suggestion
			"text": "尝试在液缸中将沙砾和沙子与水混合以得到$(item)淤泥$()。配方完成后将会改变颜色！然后就可以开始搅拌了。$(c)错误的配方会变成黑色。SHIFT并右键可以清除它。$(thing)你可以通过这种方式获得淤泥！$()$(p)你需要12个淤泥以发展后续。当你制作完成后，你可以制作淤泥砖以及手工操作的磨石。"
```

2024-09-05 04:53 UTC, dovisutu reviewed
* “译者注”？个人认为指导类的文本中准确度比忠实原文更重要。
  * 同样的，文字的流畅往往需要牺牲与原文的一一对应。
* 部分句子读起来不流畅，有头没尾，等等。建议重新看一遍译文并自行改正。

先看到这里，后面再说

2024-09-05 04:53 UTC, dovisutu commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/age1.json
> +			"text": "你还需要三个$(item)钛刀片碎片..."
考量：用来组装的叫碎片吗？

2024-09-05 04:53 UTC, dovisutu commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/age2.json
> +			"text": "$(7)$(o)就像上一个机器那样，与之不同的是动力搅拌机下方需要一个木制或钢制的储罐。"
```suggestion
			"text": "$(7)$(o)布局与上一个机器类似，但动力搅拌机下方需要一个木制或钢制的储罐。"
```

2024-09-05 04:53 UTC, dovisutu commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/age2.json
> +			"text": "就像液缸一样，将两个物品放入机器，将流体放入下方的储罐中。加以曲柄，产物将被放置在箱子中！$(p)你需要用这台机器进行的第一个配方是$(item)充能煤炭$()。将$(thing)煤粉$()与$(thing)红石粉$()在动力搅拌机中与熔岩混合..$(br)$(6)提示：你可以在动力搅拌机中执行液缸的所有配方。"
```suggestion
			"text": "该机器的用法与液缸类似：将两个物品放入机器，将流体放入下方的储罐中。加以曲柄，产物将被放置在箱子中！$(p)你需要用这台机器进行的第一个配方是$(item)充能煤炭$()。将$(thing)煤粉$()与$(thing)红石粉$()在动力搅拌机中与熔岩混合..$(br)$(6)提示：你可以在动力搅拌机中执行液缸的所有配方。"
```

2024-09-05 04:53 UTC, dovisutu commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/age2.json
> +			"text": "$(2)这种方块只有自然生成的才会有这种限制，所以你可以将它用于建筑。"
```suggestion
			"text": "$(2)只有自然生成的这种方块才会有这种限制，所以你可以将它用于建筑。"
```

2024-09-05 04:53 UTC, dovisutu commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/age2.json
> +			"text": "你可以像使用曲柄一样，将它对准一个简易机器来使用$(item)齿轮箱$()。加入燃料，齿轮箱就会自己转动。$(p)$(item)简易曲柄充能器$()是较为独特的，他只接受齿轮箱而不接受曲柄。$(br)$(c)齿轮箱需要用充能煤炭来运行。$(2)想要改变它吗？插入一个$(l:items/upgrades#gearboxcompatability)升级$(/l)使它可以使用任
```suggestion
			"text": "$(item)齿轮箱$()的用法与曲柄一样：将它对准一个简易机器以驱动机器。加入燃料，齿轮箱就会自己转动。$(p)$(item)简易曲柄充能器$()比较特殊：它只接受齿轮箱驱动而不接受曲柄。$(br)$(c)齿轮箱需要用充能煤炭来运行。$(2)想用其他燃料？插入一个$(l:items/upgrades#gearboxcompatability)升级$(/l)使它可以使用任何燃料。"
```

2024-09-05 04:53 UTC, dovisutu commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/age3.json
> +			"text": "现在我们可以通过你已知的方式获得钢板，我们可以制作一系列机器，其中包括$(item)合金炉$()。$(p)关于其他机器的信息，请查看方块章节。"
```suggestion
			"text": "在通过熟悉的办法合成了钢板后，我们可以制作一系列机器，其中包括$(item)合金炉$()。$(p)关于其他机器的信息，请查看方块章节。"
```

2024-09-05 04:53 UTC, dovisutu commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/age3.json
> +			"text": "$(item)充能金锭$()通过在合金炉中混合金板与红石粉获得。它的板也可以用你已知的方式合成。$(7)$(p)译者注：此处描述可能并不准确，但原文确是如此。"
```suggestion
			"text": "$(item)充能金锭$()通过在合金炉中混合金板与红石粉获得。它的板也可以用熟悉的方式合成。$(7)$(p)译者注：此处描述可能并不准确，但原文确是如此。"
```

2024-09-05 04:53 UTC, dovisutu commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/age3.json
> +			"text": "$(o)$(7)秘稀和铬板可以用你已知的方式合成。$()$(p)在这之后，你应该还剩下探测棒，泵还有泵轴。$(7)$(p)译者注：此处描述可能并不准确，但原文确是如此。"
```suggestion
			"text": "$(o)$(7)秘稀和铬板可以用你已知的方式合成。$()$(p)在这之后，你应该得到探测棒，泵还有泵轴。$(7)$(p)译者注：此处描述可能并不准确，但原文确是如此。"
```

2024-09-05 04:53 UTC, dovisutu commented on projects/1.19/assets/assemblylinemachines/assemblylinemachines/patchouli_books/assembly_lines_and_you/zh_cn/entries/age3.json
> +			"text": "当在一个区块中使用探测棒时，如果探测出了什么，它会告诉你有什么流体。你能找到水，熔岩，石油甚至更多流体！$(p)石油能在主世界中找到，它的含量较少。一旦找到，在区块的任意位置放置泵，如右图所示，提供能量然后看石油产生，直到区块内的含量耗尽。$(7)$(p)提示：储罐被打破后会保留其中内容。"
```suggestion
			"text": "当在一个区块中使用探测棒时，它会告诉你该区块内有什么流体。你能找到水，熔岩，石油甚至更多流体！$(p)石油能在主世界中找到，它的含量较少。一旦找到，在区块的任意位置放置泵，如右图所示，提供能量，随后便可抽取石油，直到区块内的含量耗尽。$(7)$(p)提示：储罐被打破后会保留其中内容。"
```

2024-12-12 00:11 UTC, dovisutu commented
[7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

ping @NianGuu

2024-12-20 08:11 UTC, closed without merging