Mine and Slash 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3697
Opened 2023-08-20 14:00 UTC by Rinorsi

由 CFPA-Helper 提交。

2023-08-20 16:54 UTC, mamaruo commented
**不要反复关闭pr，记住，所有“错误”都能通过关闭pr以外的方式解决。**

2023-08-21 07:42 UTC, Rinorsi commented
> **不要反复关闭pr，记住，所有“错误”都能通过关闭pr以外的方式解决。**

好的非常感谢qwq,主要是没用过github,老是出问题也不知道怎么回事qwq,很抱歉

2023-08-26 03:50 UTC, Cactusstudent requested changes
存在众多问题，有部分表述不通顺的情况，请优先自查

2023-08-26 03:50 UTC, Cactusstudent commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"death.attack.mmorpg": "%1$s 被 %2$s 杀死",
```suggestion
	"death.attack.mmorpg": "%1$s被%2$s杀死",
```

2023-08-26 03:50 UTC, Cactusstudent commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"itemGroup.mmorpg.tab": "开掘与劈砍",
注：本模组MC百科名称：挖矿与砍杀

2023-08-26 03:50 UTC, Cactusstudent commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"death.attack.death_potion": "%1$s 认为喝带“死亡”的药水是个好主意。",
```suggestion
	"death.attack.death_potion": "%1$s认为喝带“死亡”的药水是个好主意。",
```

2023-08-27 03:20 UTC, luoxueyasha requested changes
官译的事情暂且放一边，PR整体还是需要再精炼的

2023-08-27 03:20 UTC, luoxueyasha commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.tooltip.player_levelup": "如果你的经验条已满,使用此物品升级!",
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/22de3c89-4b6a-46d3-9957-dae8b566a65d)
```suggestion
	"mmorpg.tooltip.player_levelup": "如果你的经验条已满，可以使用此物品升级！",
```
原译文有点怪

2023-08-27 03:20 UTC, luoxueyasha commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"item.mmorpg.potions.reset_all_perks": "天赋全重置药水",
```suggestion
	"item.mmorpg.potions.reset_all_perks": "全部天赋重置药水",
```
```suggestion
	"item.mmorpg.potions.reset_all_perks": "天赋重置药水",
```

2023-08-27 03:20 UTC, luoxueyasha commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.support_gem.health_on_hit": "命中获得生命支援宝石",
`On Hit`类的实际效果？
是击打他人获得相应资源，还是受到击打时获得相应资源？

2023-08-27 03:20 UTC, luoxueyasha commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.affix.mana_thief": "法力小偷的",
游戏内实际显示效果？

2023-08-27 03:20 UTC, luoxueyasha commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.one_of_a_kind.arrow_barrage_mod": "箭矢弹幕修饰词",
有没有考虑过`词缀`

2023-08-27 03:25 UTC, mamaruo commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.one_of_a_kind.arrow_barrage_mod": "箭矢弹幕修饰词",
我见到的中文语境下多用“词条”，虽然我也不知道是怎么传开的这个用法。

2023-08-27 03:28 UTC, luoxueyasha commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.one_of_a_kind.arrow_barrage_mod": "箭矢弹幕修饰词",
广为流传的应该是《暗黑破坏神》的词缀系统（Magic Prefixes and Suffixes）

2023-08-27 03:28 UTC, Rinorsi commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.one_of_a_kind.arrow_barrage_mod": "箭矢弹幕修饰词",
我知道您现在还在气头上，我也知道自己不成熟，这件事情我向您道歉，但是请您相信我做这些事情绝非出于恶意……
我也很感激您指出我的问题，有关于翻译相关方面是我不够成熟，如果您觉得有必要我可以进行修改重新发布pr供以审核。
如果您觉得是我多管闲事，我会删除分支，不再进行挖矿与砍杀模组的任何翻译事项。
经过这次教训我也不觉得自己还有脸能在你，CFPA还有作者的面前出现……
但是请您相信，我本意绝非出于恶意提交pr……
qq3144995399，如果您愿意指点我，我洗耳恭听。
如果觉得没必要，我会自行离开

2023-08-27 03:30 UTC, Rinorsi commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.one_of_a_kind.arrow_barrage_mod": "箭矢弹幕修饰词",
但是无论如何，我都希望你可以原谅我这次不成熟的行为，真的，我意识到自己犯错了……

2023-08-27 03:31 UTC, luoxueyasha commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.one_of_a_kind.arrow_barrage_mod": "箭矢弹幕修饰词",
@Rinorsi 
发错pr了吧（？
平复一下心情再说吧，能搞完这么大工作量还是不错的

2023-08-27 03:31 UTC, Rinorsi commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.one_of_a_kind.arrow_barrage_mod": "箭矢弹幕修饰词",
我也深刻认识到了自己不该刚刚接触就对大型模组进行翻译工作

2023-08-27 03:33 UTC, Rinorsi commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.one_of_a_kind.arrow_barrage_mod": "箭矢弹幕修饰词",
> @Rinorsi 发错pr了吧（甚至看错人了？ 平复一下心情再说吧，能搞完这么大工作量还是不错的

不好意思……我有点乱了……这里的pr和官库不同，我目前也在进行优化，但是我不敢做了

2023-08-27 03:36 UTC, luoxueyasha commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.one_of_a_kind.arrow_barrage_mod": "箭矢弹幕修饰词",
@Rinorsi 
新手犯错不是正常情况嘛，能力不足学就是了
先把心态稳好再说，那之后再说和官译沟通进度，修这边PR等问题，不着急

当然就译者个人角度来讲，看到一篇水平不够的译文确实会比较生气……慢慢来吧

2023-08-27 09:44 UTC, mamaruo commented
我对比了“官方1.16.5”和“本PR”的翻译，结果如下：

结果由机器生成，程序有诸多不足，仅能作大概参考。

### 两者皆有且中文有差异

<details><summary>点击展开/收起</summary>
<p>

| **键** | **英文** | **官方1.16.5** | **本PR** |
|---|---|---|---|
| _comment |  \[CATEGORY\]: SPELLS \- DESCRIPTIONS |  \[CATEGORY\]: STATS \- DESCRIPTIONS |  \[CATEGORY\]: SPELLS \- DESCRIPTIONS |
| death.attack.mmorpg.custom_damage | Tons of Damage\! | 巨量伤害！ | 巨量伤害\! |
| mmorpg.tooltip.item_modifiable_in_station | Can be used inside Gear Modify Station | 可以在装备强化台中使用 | 可在装备修改站中使用 |
| mmorpg.tooltip.lootbox | What could be inside? | 基于大小获得不同数量的物品 | 里面可能有什么? |
| mmorpg.tooltip.player_levelup | If your experience bar is full, use this item to levelup\! | 如果你的砍杀经验已满，右键此物品突破等级吧\! | 如果你的经验条已满,使用此物品升级\! |
| mmorpg.tooltip.capacitor | Put Inside Repair Station to decrease fuel consumption\. | 放在装备修理台中以减少燃料的消耗\. | 放入修理站可减少燃料消耗。 |
| mmorpg.tooltip.capacitor2 | Fuel Multiplier | 燃料消耗比率 | 燃料乘数 |
| mmorpg.tooltip.socketable_item | This Gem can be inserted into a Socket slot | 这个宝石可以插入插槽 | 这个宝石可以插在插槽中 |
| item.mmorpg.currency_bag | Currency Bag | 通货袋 | 货币袋 |
| item.mmorpg.tutorial_book | Age of Exile Tutorial | 流放时代教程 | 流亡时代教程 |
| item.mmorpg.map_back_portal | Map Leave Pearl | 回城珍珠 | 地图回程珍珠 |
| item.mmorpg.level_nearest_entity | Level Nearest Entity | 提升最近1个生物的等级 | 升级最近实体 |
| item.mmorpg.increase_rarity_nearest_entity | Increase Rarity Nearest Entity | 提升最近1个生物的品级 | 提高最近实体稀有度 |
| item.mmorpg.mat.infused_iron | Infused Iron | 注魔铁锭 | 聚能铁 |
| item.mmorpg.mat.crystallized_essence | Crystalized Essence | 源质结晶 | 结晶精华 |
| item.mmorpg.mat.golden_orb | Golden Orb | 金质宝珠 | 金色宝珠 |
| item.mmorpg.mat.mythic_essence | Mythic Essence | 神秘源质 | 神话精华 |
| item.mmorpg.awaken_runeword | Awaken RuneWord | 觉醒符文之语 | 唤醒符文 |
| item.mmorpg.identify_tome | Identify Tome | 鉴定卷册 | 鉴定古卷 |
| item.mmorpg.custom_crate | Gear Crate | 板条箱 | 装备箱 |
| mmorpg.name.map | Adventure Map | 冒险地图 | 探险地图 |
| mmorpg.tooltip.press_shift_more_info | \[Alt\]: Desc, \[Ctrl\]: Hide | \[Shift\]: 信息，\[Alt\]: 描述，\[Ctrl\]: 附魔 | \[Alt\]: 描述, \[Ctrl\]: 隐藏 |
| mmorpg.tooltip.affix_rarity_lootbonus | Affix Rarity Loot Bonus | 词缀品级战利品奖励 | 词缀稀有度战利品奖励 |
| entity.mmorpg.boss_golem | Corrupted Golem | 堕落铁傀儡 | 腐化魔像 |
| effect.mmorpg.food_health_regen | Health Regen | 生命回复 | 生命恢复 |
| effect.mmorpg.food_mana_regen | Mana Regen | 魔力回复 | 魔力恢复 |
| effect.mmorpg.food_magic_shield_regen | Magic Regen | 魔法盾回复 | 魔法恢复 |
| item.mmorpg.loot_crate.common | Common Item Loot Crate | 常见战利品箱 | 普通物品战利品箱 |
| item.mmorpg.loot_crate.magic | Magic Item Loot Crate | 魔法战利品箱 | 魔法物品战利品箱 |
| item.mmorpg.loot_crate.rare | Rare Item Loot Crate | 稀有战利品箱 | 稀有物品战利品箱 |
| item.mmorpg.loot_crate.relic | Relic Item Loot Crate | 遗物战利品箱 | 圣物战利品箱 |
| item.mmorpg.loot_crate.unique | Unique Item Loot Crate | 珍品战利品箱 | 独特物品战利品箱 |
| mmorpg.mob_affix.vampire | §c❁ | 吸血鬼 | §c❁吸血鬼 |
| item.mmorpg.gems.amethyst.0 | Cracked Amethyst | 下品紫水晶 | 破碎紫水晶 |
| item.mmorpg.gems.amethyst.1 | Chipped Amethyst | 中品紫水晶 | 裂缝紫水晶 |
| item.mmorpg.gems.amethyst.2 | Flawed Amethyst | 上品紫水晶 | 有缺陷紫水晶 |
| item.mmorpg.gems.amethyst.3 | Regular Amethyst | 精品紫水晶 | 普通紫水晶 |
| item.mmorpg.gems.amethyst.4 | Grand Amethyst | 珍品紫水晶 | 宏伟紫水晶 |
| item.mmorpg.gems.azurite.0 | Cracked Azurite | 下品青水晶 | 破碎青金石 |
| item.mmorpg.gems.azurite.1 | Chipped Azurite | 中品青水晶 | 裂缝青金石 |
| item.mmorpg.gems.azurite.2 | Flawed Azurite | 上品青水晶 | 有缺陷青金石 |
| item.mmorpg.gems.azurite.3 | Regular Azurite | 精品青水晶 | 普通青金石 |
| item.mmorpg.gems.azurite.4 | Grand Azurite | 珍品青水晶 | 宏伟青金石 |
| item.mmorpg.gems.emerald.0 | Cracked Emerald | 下品绿水晶 | 破碎绿宝石 |
| item.mmorpg.gems.emerald.1 | Chipped Emerald | 中品绿水晶 | 裂缝绿宝石 |
| item.mmorpg.gems.emerald.2 | Flawed Emerald | 上品绿水晶 | 有缺陷绿宝石 |
| item.mmorpg.gems.emerald.3 | Regular Emerald | 精品绿水晶 | 普通绿宝石 |
| item.mmorpg.gems.emerald.4 | Grand Emerald | 珍品绿水晶 | 宏伟绿宝石 |
| item.mmorpg.gems.garnet.0 | Cracked Garnet | 下品黄绿水晶 | 破碎石榴石 |
| item.mmorpg.gems.garnet.1 | Chipped Garnet | 中品黄绿水晶 | 裂缝石榴石 |
| item.mmorpg.gems.garnet.2 | Flawed Garnet | 上品黄绿水晶 | 有缺陷石榴石 |
| item.mmorpg.gems.garnet.3 | Regular Garnet | 精品黄绿水晶 | 普通石榴石 |
| item.mmorpg.gems.garnet.4 | Grand Garnet | 珍品黄绿水晶 | 宏伟石榴石 |
| item.mmorpg.gems.opal.0 | Cracked Opal | 下品橙水晶 | 破碎蛋白石 |
| item.mmorpg.gems.opal.1 | Chipped Opal | 中品橙水晶 | 裂缝蛋白石 |
| item.mmorpg.gems.opal.2 | Flawed Opal | 上品橙水晶 | 有缺陷蛋白石 |
| item.mmorpg.gems.opal.3 | Regular Opal | 精品橙水晶 | 普通蛋白石 |
| item.mmorpg.gems.opal.4 | Grand Opal | 珍品橙水晶 | 宏伟蛋白石 |
| item.mmorpg.gems.ruby.0 | Cracked Ruby | 下品红水晶 | 破碎红宝石 |
| item.mmorpg.gems.ruby.1 | Chipped Ruby | 中品红水晶 | 裂缝红宝石 |
| item.mmorpg.gems.ruby.2 | Flawed Ruby | 上品红水晶 | 有缺陷红宝石 |
| item.mmorpg.gems.ruby.3 | Regular Ruby | 精品红水晶 | 普通红宝石 |
| item.mmorpg.gems.ruby.4 | Grand Ruby | 珍品红水晶 | 宏伟红宝石 |
| item.mmorpg.gems.sapphire.0 | Cracked Sapphire | 下品蓝水晶 | 破碎蓝宝石 |
| item.mmorpg.gems.sapphire.1 | Chipped Sapphire | 中品蓝水晶 | 裂缝蓝宝石 |
| item.mmorpg.gems.sapphire.2 | Flawed Sapphire | 上品蓝水晶 | 有缺陷蓝宝石 |
| item.mmorpg.gems.sapphire.3 | Regular Sapphire | 精品蓝水晶 | 普通蓝宝石 |
| item.mmorpg.gems.sapphire.4 | Grand Sapphire | 珍品蓝水晶 | 宏伟蓝宝石 |
| item.mmorpg.gems.topaz.0 | Cracked Topaz | 下品黄水晶 | 破碎黄玉 |
| item.mmorpg.gems.topaz.1 | Chipped Topaz | 中品黄水晶 | 裂缝黄玉 |
| item.mmorpg.gems.topaz.2 | Flawed Topaz | 上品黄水晶 | 有缺陷黄玉 |
| item.mmorpg.gems.topaz.3 | Regular Topaz | 精品黄水晶 | 普通黄玉 |
| item.mmorpg.gems.topaz.4 | Grand Topaz | 珍品黄水晶 | 宏伟黄玉 |
| item.mmorpg.gems.tourmaline.0 | Cracked Tourmaline | 下品粉水晶 | 破碎碧玺 |
| item.mmorpg.gems.tourmaline.1 | Chipped Tourmaline | 中品粉水晶 | 裂缝碧玺 |
| item.mmorpg.gems.tourmaline.2 | Flawed Tourmaline | 上品粉水晶 | 有缺陷碧玺 |
| item.mmorpg.gems.tourmaline.3 | Regular Tourmaline | 精品粉水晶 | 普通碧玺 |
| item.mmorpg.gems.tourmaline.4 | Grand Tourmaline | 珍品粉水晶 | 宏伟碧玺 |
| item.mmorpg.potions.add_reset_perk_points | Single Talent Reset Potion | 技能反悔药水 | 单点天赋重置药水 |
| item.mmorpg.potions.reset_all_perks | Talent Reset Potion | 技能洗点药水 | 天赋全重置药水 |
| item.mmorpg.runes.ano | Ano Rune | Ano \- 符文 | 安诺符文 |
| item.mmorpg.runes.cen | Cen Rune | Cen \- 符文 | 岑符文 |
| item.mmorpg.runes.dos | Dos Rune | Dos \- 符文 | 多斯符文 |
| item.mmorpg.runes.eno | Eno Rune | Eno \- 符文 | 伊诺符文 |
| item.mmorpg.runes.har | Har Rune | Har \- 符文 | 哈尔符文 |
| item.mmorpg.runes.ita | Ita Rune | Ita \- 符文 | 伊塔符文 |
| item.mmorpg.runes.mos | Mos Rune | Mos \- 符文 | 摩斯符文 |
| item.mmorpg.runes.nos | Nos Rune | Nos \- 符文 | 诺斯符文 |
| item.mmorpg.runes.oru | Oru Rune | Oru \- 符文 | 奥鲁符文 |
| item.mmorpg.runes.toq | Toq Rune | Toq \- 符文 | 托克符文 |
| item.mmorpg.runes.wir | Wir Rune | Wir \- 符文 | 威尔符文 |
| item.mmorpg.runes.xer | Xer Rune | Xer \- 符文 | 泽尔符文 |
| item.mmorpg.runes.yun | Yun Rune | Yun \- 符文 | 云符文 |
| mmorpg.spell.awaken_mana | Inspiration | 魔力唤醒 | 苏醒魔法 |
| mmorpg.spell.fireball | Fire Ball | 火球术 | 火球 |
| mmorpg.spell.frostball | Ice Ball | 冰球术 | 冰球 |
| mmorpg.spell.healing_aura | Healing Aura | 回复光环 | 治疗光环 |
| mmorpg.spell.heart_of_ice | Heart of Ice | 冰霜新星 | 冰心 |
| mmorpg.spell.magma_flower | 🚫 | 熔岩之花 | 熔火兰 |
| mmorpg.spell.nature_balm | Nature's Balm | 自然之息 | 自然馈赠 |
| mmorpg.spell.poison_ball | Poison Ball | 毒球术 | 毒球 |
| mmorpg.spell.recoil_shot | Recoil Shot | 激退射杀 | 后坐力射击 |
| mmorpg.affix.archeologists | Archeologist's | 考古学家的 | 考古家的 |
| mmorpg.affix.azure | Azure | 蔚蓝的 | 湛蓝 |
| mmorpg.affix.fire_ele_dmg_jewelry | Of Embers | 之余烬 | 余烬 |
| mmorpg.affix.fire_res | Of the Drake | 巨龙之 | 火龙的 |
| mmorpg.affix.fire_wep_dmg | Scorched | 焦灼的 | 灼烧 |
| mmorpg.affix.glimmering | Glimmering | 闪闪发光的 | 闪烁 |
| mmorpg.affix.of_affluence | Of Affluence | 之富裕 | 繁荣 |
| mmorpg.affix.of_brutality | Of Brutality | 之残暴 | 野蛮 |
| mmorpg.affix.of_consumption | Of Consumption | 之消耗 | 消耗 |
| mmorpg.affix.of_gluttony | Of Gluttony | 之暴食 | 暴食 |
| mmorpg.affix.of_spirit_markings | Of Spirit Markings | 之灵魂标记 | 灵魂标记 |
| mmorpg.affix.of_the_philosopher | Of the Philosopher | 之哲学家 | 哲人的 |
| mmorpg.affix.of_the_sky | Of the Sky | 之天空 | 天空的 |
| mmorpg.affix.of_the_titan | Of the Titan | 之泰坦 | 泰坦的 |
| mmorpg.affix.of_the_troll | Of The Troll | 之巨魔 | 巨魔的 |
| mmorpg.affix.of_the_wind | Of the Wind | 之风 | 风之 |
| mmorpg.affix.o [...]

2023-08-27 10:19 UTC, mamaruo commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.one_of_a_kind.arrow_barrage_mod": "箭矢弹幕修饰词",
已私下沟通了相关情况。

2023-08-28 04:33 UTC, Rinorsi commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.one_of_a_kind.arrow_barrage_mod": "箭矢弹幕修饰词",
> 有没有考虑过`词缀`

有关「modifier」方面我询问了模组作者,得到的结果是这部分直接无视即可,是冗余代码

2023-08-30 03:49 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"item.mmorpg.teleport_scroll": "回城卷轴",
参考原文

2023-08-30 03:49 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.affix.mana_thief": "法力小偷的",
mana steal，打中回蓝

2023-08-30 03:49 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.support_gem.health_on_hit": "命中获得生命支援宝石",
打中别人

2023-08-30 04:48 UTC, TUsama requested changes
下面还有极多的问题，先把这些考虑清楚再说吧。

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"item.mmorpg.loot_table_chest": "等级奖励袋",
参照原文。

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.one_of_a_kind.start": "开始",
这里应该是天赋的始点的tooltips。

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"item.mmorpg.backpack.5": "§5神话背包",
注意品级的统一性，这是基础的翻译统一性问题，除非另有缘由。

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"item.mmorpg.gems.amethyst.6": "神圣紫水晶",
这里的定语基本是用于描述宝石的rank（作者原话），当然按照我们面对的文本来说，它用的词语Cracked Chipped之类的，基本都是描述它的外形/完整度。基于此，我给出我自己的一套方案：破碎 缺损 露瑕 完整 硕大 华美 神圣。

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"item.mmorpg.gems.azurite.6": "神圣青金石",
此处名称需要改动，与原版青金石撞名字了。

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"item.mmorpg.gems.tourmaline.6": "神圣的红玛瑙",
自查玛瑙与碧玺的区别。以及这里怎么会多一个“的”？仔细一点。

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"item.mmorpg.chest.harvest_blue": "流明采集宝箱",
lucid翻译为“流明”，有何依据？

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"item.mmorpg.projectile.snowball": "投掷物",
Projectile 应为“弹射物”，原版词汇。

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"item.mmorpg.salvage_hammer": "拆解锤",
参照原文。

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"item.mmorpg.soul_extractor.uncommon": "下品装备魂印",
此处译为“魂印”，与原文较大区别，可有依据？

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.aura.chaos_ailment": "混沌附魔光环",
我不确定ailment在游戏内的机制是什么，同时这里使用了原版的词汇，恐有混淆之嫌。
在原游戏中，Status Ailments译为“负面状态”，可作为线索来参考。

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.spell.chain_lightning": "链状闪电",
用常规的“闪电链”即可。

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.spell.dash": "闪现",
游戏里测一下。

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.spell.charged_bolt": "充能箭矢",
此处译得不好。技能名字不在于忠实原文（但不是随意改编），也不在于使用花俏字词，而在于达意、传神。如果你有自己在游玩rpg类游戏时对比过技能的原文以及翻译，你很快就能理解这件事。如果原文直接翻译过来很传神，那就用直译，如果翻译过来差点意思，那稍作修改无不可。其中的度量需要译者自行掌控，写出自己的风格，译出自己的特色。但是记住，不要为了炫技而挑选一些怪字，组一些怪词，那样只会让人困惑。

以上为一些经验之见。回到这里，我建议是改为“蓄力射击”，原因参照技能描述。

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.spell.nature_balm": "自然之息",
1.15.2版本，此处改为了“自然香膏”

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.spell.minion_explosion": "爆炸扈从",
进游戏实测再翻译。

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.spell.quickdraw": "快手",
快手含义过于宽泛，此处直译即可，此技能为加快拉弓的速度。

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.spell.recoil_shot": "激退射杀",
只是后撤一小步，怎么“激退”都出来了。

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.spell.return_summons": "召回召唤兽",
“兽”？

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.spell.song_of_vigor": "能量赞歌",
vigor和energy能不混淆尽量别混淆。

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.spell.power_chord": "音爆",
这个比较难评。

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.support_gem.ailment_damage_less_hit_dmg": "异常伤害增益宝石",
参照原游戏，此处应为“辅助宝石”

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.support_gem.magic_shield_on_hit": "命中获得魔护增益宝石",
此处参照“击中回血”，所有的“xx on hit”同意按照这个格式来翻译。

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.affix.armored_mobs": "装甲",
词缀基本都是“xx的”以及“之xx”。

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.affix.item_perc_ms": "坚固魔护",
格式？Reinforced译为强化护甲？
自己进游戏实测看看什么效果。

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"effect.mmorpg.negative.9": "绝望诅咒",
注意，如果修改了上面的法术名，这边的对应效果名也得酌情更改。

2023-08-30 04:48 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.talent.all_all_damage_big": "全伤害强化",
major译为“强化”，欠考虑。major一词是为了区分小天赋和大天赋，大天赋加得更多，小天赋加得更少。若你翻为“强化”，那小天赋就不是强化了？此处的major应从数量上考虑。我自己的译本译为“大量”。当然常规来说major描述的是重要性，不过我在译的时候没有找到很好的词能够融进这里面，所以用了“大量”。

2023-08-31 06:17 UTC, TUsama requested changes

2023-08-31 06:17 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"item.mmorpg.jewel.unique_crafted": "符文工艺神话宝石",
unique怎么就变成神话了呢？

2023-08-31 06:17 UTC, TUsama commented on projects/1.20/assets/mine-and-slash-reloaded/mmorpg/lang/zh_cn.json
> +	"mmorpg.affix.of_fast_cast": "快速施法的",
看原文。

2023-08-31 06:19 UTC, TUsama commented
更新一下语言文件，新版挖砍少了500行的冗余。
具体更新方法你问CFPA群的人。

2023-08-31 11:17 UTC, Rinorsi commented
> 更新一下语言文件，新版挖砍少了500行的冗余。 具体更新方法你问CFPA群的人。

好的我这两天处理好

2023-11-25 00:58 UTC, luoxueyasha commented
嗯……所以官库接了（https://github.com/RobertSkalko/Mine-And-Slash-Rework/pull/5），这边是不是可以close了？
@Rinorsi

2023-11-25 01:01 UTC, TUsama commented
现在这边到底支持1.20没有

2023-11-25 11:56 UTC, luoxueyasha commented
> 现在这边到底支持1.20没有

这边照常收译文，但是程序上还暂且不支持
具体需要见#3875 的进度

2023-11-25 12:03 UTC, TUsama commented
你们加紧吧。
这个PR我来负责，平时怕打扰可以先unsubscribe。

2023-11-27 05:09 UTC, Rinorsi commented
> 你们加紧吧。 这个PR我来负责，平时怕打扰可以先unsubscribe。

大佬负责的话也行，我这边主要是发在了百科的评论区里面，上个月没有更新因为要考试，最近准备继续更新翻译，不过感觉质量不太过关，也不太敢往这发了

2023-11-27 05:15 UTC, TUsama commented
主要看你的意愿。如果你觉得发在那边评论区就行，那你就发。这玩意无所谓负责不负责，我用我自己的译本，你用你自己的译本，都开心。但是发送到公共平台，那确实是得考量质量。

2024-01-07 09:52 UTC, luoxueyasha commented
@TUsama 这边正式支持1.20了。
我看官库那边更新的比这边频繁，你们那边是怎么打算的？

2024-01-07 10:39 UTC, closed without merging

2024-01-07 10:39 UTC, TUsama commented
close了