Thaumic Energistics Extended Life 翻译新增
CFPAOrg/Minecraft-Mod-Language-Package pull request #3713
Opened 2023-08-23 08:46 UTC by RuiXuqi

[#2453](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/2453#)
https://www.curseforge.com/minecraft/mc-mods/thaumic-energistics-extended-life
换个比较库，之前那个很久之前交的，当时还不会用Github，而且这个修改版也没有登录curseforge

2023-08-23 09:00 UTC, RuiXuqi commented
构建出来的包里面的lang好像一半是新的一半是旧的...

2023-09-02 08:27 UTC, luoxueyasha requested changes

2023-09-02 08:27 UTC, luoxueyasha commented on projects/1.12.2/assets/thaumic-energistics-extended-life/thaumicenergistics/lang/zh_cn.lang
> +card.tinkerae.text=尝试将源质转化为能量，类似于你现在的ME网络所做的。获得 10-25 能源学。
“获得能源学”指？
怎么感觉能源学不应该是个单位的名字呢

2023-09-02 13:27 UTC, RuiXuqi commented on projects/1.12.2/assets/thaumic-energistics-extended-life/thaumicenergistics/lang/zh_cn.lang
> +card.tinkerae.text=尝试将源质转化为能量，类似于你现在的ME网络所做的。获得 10-25 能源学。
> “获得能源学”指？ 怎么感觉能源学不应该是个单位的名字呢

已改为“获得10到25点 能源学 进度。”

2023-09-06 15:35 UTC, ChuijkYahus commented on projects/1.12.2/assets/thaumic-energistics-extended-life/thaumicenergistics/lang/zh_cn.lang
> +item.thaumicenergistics.arcane_inscriber.name=奥术记录仪
```suggestion
item.thaumicenergistics.arcane_inscriber.name=奥术压印器
```
这个和ae的压印器功能一样吗

2023-09-06 15:35 UTC, ChuijkYahus commented on projects/1.12.2/assets/thaumic-energistics-extended-life/thaumicenergistics/lang/zh_cn.lang
> +research.digisentia.stage.2=§l扩散核心§r<BR>液态源质具有相对较高的波动性和巨大的能量，这使得需先将其扩散稀释，然后再数位化。这时候就需要某种缓冲器来容纳这些扩散的源质。<PAGE><LINE>§l聚集核心§r<BR>压缩并将分散的源质重塑凝为原先的液态。很可能也需要这样一个缓冲器。
```suggestion
research.digisentia.stage.2=§l扩散核心§r<BR>液态源质具有相对较高的挥发性和巨大的能量，这使得需先将其扩散稀释，然后再数位化。这时候就需要某种缓冲器来容纳这些扩散的源质。<PAGE><LINE>§l聚集核心§r<BR>压缩并将分散的源质重塑凝为原先的液态。很可能也需要这样一个缓冲器。
```

2023-09-06 15:35 UTC, ChuijkYahus commented on projects/1.12.2/assets/thaumic-energistics-extended-life/thaumicenergistics/lang/zh_cn.lang
> +research.arcaneassembler.stage.2=一切都应是正常的——它可以获得物品、Vis、 魔力水晶碎片和能量。然而，它甚至没有尝试合成！我发明的不过是一个沉重的镇纸，一个可以使用几张加速卡强化的镇纸。这令我非常失望。
```suggestion
research.arcaneassembler.stage.2=一切都应是正常的——它可以获得物品、Vis、魔力水晶碎片和能量。然而，它甚至没有尝试合成！我发明的不过是一个沉重的镇纸，一个可以使用几张加速卡强化的镇纸。这令我非常失望。
```

2023-09-06 16:00 UTC, RuiXuqi commented on projects/1.12.2/assets/thaumic-energistics-extended-life/thaumicenergistics/lang/zh_cn.lang
> +item.thaumicenergistics.arcane_inscriber.name=奥术记录仪
> 这个和ae的压印器功能一样吗

不一样的，类似样板终端，知识核心是样板

2023-09-06 16:03 UTC, RuiXuqi commented
得找个时间把神秘能源原版处理下，如果要的话先别合并（）

2023-09-06 17:10 UTC, ChuijkYahus commented
> 得找个时间把神秘能源原版处理下，如果要的话先别合并（）

没问题，需要我审核时候at我就行

2023-09-08 13:37 UTC, RuiXuqi commented
> > 得找个时间把神秘能源原版处理下，如果要的话先别合并（）
> 
> 没问题，需要我审核时候at我就行

搞好了，发现也没多少（

2023-09-09 03:15 UTC, ChuijkYahus approved these changes

2023-09-09 14:58 UTC, luoxueyasha approved these changes

2023-09-10 08:22 UTC, merged