ReAuth 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #3716
Opened 2023-08-23 17:14 UTC by DrIceTea123

2023-08-26 15:08 UTC, mamaruo commented
账号/账户 术语须统一，建议看一下 微软 和 游戏内 咋翻译的。

Screen 确实翻译为 `屏幕`，见译名标准化/Minecraft Wiki/游戏内。

2023-08-26 15:20 UTC, DrIceTea123 commented
微软、Mojang和游戏内均为`账户`，原译文中“账号”是手误

2023-08-29 11:05 UTC, Cyl18 commented on projects/1.16/assets/reauth/reauth/lang/zh_cn.json
> +  "reauth.msauth.step.microsoft.device.poll": "请输入密码\n$%2$s\n在%1$s",
原文是`code` 记得修改1.18和1.19的
```suggestion
  "reauth.msauth.step.microsoft.device.poll": "请输入代码\n$%2$s\n在%1$s",
```

2023-08-29 13:46 UTC, mamaruo requested changes
注意剿灭`进行`
注意连带更改

2023-08-30 03:51 UTC, mamaruo approved these changes

2023-09-01 06:14 UTC, merged