AHZNB's Naruto ShinobiCraft 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3722
Opened 2023-08-25 09:13 UTC by xuhuanGhost

由 CFPA-Helper 提交。

2023-08-25 09:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3722) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3722) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3722) it.</sub>

2023-08-27 03:00 UTC, luoxueyasha requested changes
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/60f31ef6-218f-43fb-adca-abaff3c66be6)
请确认中文与英文key是否一一对应

2023-08-27 15:36 UTC, xuhuanGhost reviewed
修正好了

2023-08-29 11:52 UTC, Cyl18 commented
/sort-keys projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/en_us.lang
/sort-keys projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang

2023-08-31 02:42 UTC, Cyl18 commented
@xuhuanGhost 文件用GitHub上的改 我这重排了一下键序 方便审核

>
/sort-keys projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/en_us.lang
/sort-keys projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang

2023-08-31 02:50 UTC, Cyl18 commented
/sort-keys projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/en_us.lang
/sort-keys projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang

2023-08-31 02:53 UTC, Cyl18 commented
/sort-keys projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang

2023-09-06 14:31 UTC, ChuijkYahus commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

@xuhuanGhost

2023-09-06 14:32 UTC, ChuijkYahus commented
抱歉，为时间误判，但仍请注意查看审核意见

2023-09-10 11:18 UTC, ChuijkYahus commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

@xuhuanGhost

2023-09-10 11:19 UTC, ChuijkYahus commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@xuhuanGhost

2023-10-08 13:07 UTC, luoxueyasha commented
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/5da25d52-4b6c-42ad-8a25-d48dd1498326)
 请确认key之间是否一一对应

2023-10-08 13:31 UTC, luoxueyasha requested changes
看了几行实在是看不下去了，错译和生硬翻译太多
请自行修正

2023-10-08 13:31 UTC, luoxueyasha commented on projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang
> +advancements.achievementmedicalgenin.descr=恭喜你，你现在可以使用一些医疗忍术了
```suggestion
advancements.achievementmedicalgenin.descr=你现在可以施放一些医疗忍术了
```
原文没有“恭喜”
不确定火影忍者里“忍术”是否对应“施放”，具体请以社群常用翻译为准

2023-10-08 13:31 UTC, luoxueyasha commented on projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang
> +advancements.achievementmedicalgenin.title=成为一名医疗忍者
游戏内实际显示效果？
怎么感觉没有“成为”的意思呢

2023-10-08 13:31 UTC, luoxueyasha commented on projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang
> +advancements.bakuton_acquired.descr=爆遁是一种只能由血缘关系借由基因来继承的术，由土遁和雷遁所结合，爆遁持有者可以在战斗中释放爆炸忍术
```suggestion
advancements.bakuton_acquired.descr=爆遁是血继限界的一种，由土遁和雷遁性质变化所结合而成。爆遁持有者可以在战斗中释放爆炸忍术。
```
原文`nature transformation`（性质变化）、`kekkei genkai`（血继限界）两个专有名词没能翻译出来

2023-10-08 13:31 UTC, luoxueyasha commented on projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang
> +advancements.byakuganopened.descr=白眼被认为是“三大瞳术”之一，其他则是写轮眼和轮回眼。
```suggestion
advancements.byakuganopened.descr=白眼乃“三大瞳术”之一，与写轮眼、轮回眼并列。
```
```suggestion
advancements.byakuganopened.descr=白眼是与写轮眼、轮回眼并列的“三大瞳术”之一。
```
机翻嫌疑

2023-10-08 13:31 UTC, luoxueyasha commented on projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang
> +advancements.eternalmangekyoachieved.descr=永恒万花筒写轮眼证明了宇智波一族在遭受惨痛的经历后，依旧继续前进着。
```suggestion
advancements.eternalmangekyoachieved.descr=永恒万花筒写轮眼是一名宇智波族人在经历巨大悲痛后，依旧继续前行的证明。
```
这句话明显说的是佐助吧，宇智波不是被灭族了吗（只看了剧情概括
机翻嫌疑

2023-10-08 15:33 UTC, xuhuanGhost commented
> ![image](https://user-images.githubusercontent.com/38830216/273450383-5da25d52-4b6c-42ad-8a25-d48dd1498326.png) 请确认key之间是否一一对应

这个后面是对应的，我加了

2023-10-14 09:38 UTC, luoxueyasha requested changes

2023-10-14 09:38 UTC, luoxueyasha commented on projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang
> +advancements.hyoton_acquired.descr=冰遁是一种只能由血缘关系借由基因来继承的术，是水遁与风遁性质变化所结合，可以在战斗中释放具有冰的忍术。
依旧是`血继限界`专有名词的问题，**请全文通查**

2023-10-14 09:46 UTC, luoxueyasha requested changes

2023-10-14 09:46 UTC, luoxueyasha commented on projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang
> +advancements.kekkei_tota_awakened.descr=血继淘汰是一个比血继限界更为强大且稀有的遁术，目前已知的例子只有尘遁，由土，风，火的性质变化所结合。
```suggestion
advancements.kekkei_tota_awakened.descr=血继淘汰是一类比血继限界更为强大且稀有的遁术。目前已知的例子只有尘遁，由土，风，火的性质变化所结合。
```
① 请检查量词而非全部使用`个`，此问题请全文通查
② 请检查标点的运用，此问题请全文通查

2023-10-14 09:54 UTC, luoxueyasha requested changes

2023-10-14 09:54 UTC, luoxueyasha commented on projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang
> +advancements.rinnesharinganactivated.title=轮回写轮眼已觉醒
`XX Awakened`对应的是`觉醒XX`还是`XX已觉醒`？
请全文统一

2023-10-14 09:54 UTC, luoxueyasha commented on projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang
> +advancements.achievementmedicalgenin.title=医疗忍者
```suggestion
advancements.achievementmedicalgenin.title=医疗下忍
```
原文`Medical Genin`

2023-10-14 09:54 UTC, luoxueyasha commented on projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang
> +advancements.byakuganopened.title=觉醒白眼
原文是`Opened`而不是`Awakened`，国内火影圈对于这两个词用的翻译都是`觉醒`吗

2023-10-14 09:54 UTC, luoxueyasha commented on projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang
> +advancements.bakuton_acquired.title=爆遁忍者
`XX Acquired`翻译成`XX忍者`……
不太清楚火影的具体设定，但是动画/漫画里一个人可以同时使用多种`遁`吗？
如果可以的话，那么感觉还是得翻译为`获得XX`、`习得XX`之类的比较好；否则就有点角色只会一种遁术的感觉

2023-10-14 09:54 UTC, luoxueyasha commented on projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang
> +advancements.tenseigan_achieved.descr=转生眼是白眼的进化（字面意思上，这也属于轮回眼。）
解释一下空格里的意思

2023-10-14 09:54 UTC, luoxueyasha commented on projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang
> +advancements.shikotsumyaku_acquired.title=§f§l尸骨脉
原文没有改变字体，问一下修改字体的理由？

2023-10-14 10:56 UTC, luoxueyasha requested changes

2023-10-14 10:56 UTC, luoxueyasha commented on projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang
> +advancements.learned_1st_jutsu.title=掌握你的第一个忍术
```suggestion
advancements.learned_1st_jutsu.title=掌握第一个忍术
```
忍术的量词是不是`个`我不太确定……`门`？`种`？
`你的`在这里有机翻嫌疑，可以导入游戏里看一眼效果

2023-10-14 11:01 UTC, luoxueyasha commented
你的回复可能在Pending状态（如下图所示），这种状态下我们无法看到你对conversation的回复。
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/3247006e-632b-4d8f-864d-90175449a2bb)

你需要在右上角点击“Finish your Review”以发送处于Pending状态的回复。
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/a583b259-238d-49d7-93f2-3a994d72030b)

2023-10-30 00:18 UTC, luoxueyasha commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

@xuhuanGhost

2023-11-18 07:18 UTC, ChuijkYahus commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@xuhuanGhost

2023-11-18 09:37 UTC, xuhuanGhost reviewed
我最终认为还是种比较好，正在修改

2023-11-18 09:42 UTC, xuhuanGhost reviewed
均已经回复，现在做修改

2023-11-18 09:42 UTC, xuhuanGhost commented on projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang
> +advancements.learned_1st_jutsu.title=掌握你的第一个忍术
我最近认为还是种比较好，正在修改

2023-11-18 09:42 UTC, xuhuanGhost commented on projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang
> +chattext.mightguy.arrival=木叶高傲的苍蓝猛兽来了！这就是青春的力量！哈哈哈
感觉不合适，我现在给删了

2023-11-18 09:42 UTC, xuhuanGhost commented on projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang
> +advancements.shikotsumyaku_acquired.title=§f§l尸骨脉
这个做保留，如果确实不妥我将会删除

2023-11-18 09:42 UTC, xuhuanGhost commented on projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang
> +advancements.bakuton_acquired.title=爆遁忍者
还是叫忍者吧，毕竟直接写忍者不代表一定就会一个遁术

2023-11-18 09:46 UTC, luoxueyasha commented on projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang
> +advancements.bakuton_acquired.title=爆遁忍者
既然是进度名，我觉得还是应该显示为`获得XX`
其一是遵循原文
其二是一整个进度菜单里并排显示`获得X遁`、`X遁持有者`、`X遁忍者`来说，我个人偏好是1>2>3的

2023-11-18 09:48 UTC, luoxueyasha commented on projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang
> +advancements.shikotsumyaku_acquired.title=§f§l尸骨脉
先这么保持unresolved，回头探讨
因为之前给拔刀剑译者加字体修饰擦屁股所以有ptsd

2023-11-18 09:49 UTC, luoxueyasha commented on projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang
> +advancements.tenseigan_achieved.descr=转生眼是白眼的进化（字面意思上，这也属于轮回眼。）
**括号** 里的意思

2023-11-18 11:27 UTC, luoxueyasha requested changes

2023-11-18 11:27 UTC, luoxueyasha commented on projects/1.12.2/assets/ahznbs-naruto-mod/narutomod/lang/zh_cn.lang
> +advancements.tenseigan_achieved.descr=转生眼是白眼的进化（字面意思上，这也属于轮回眼。）
已经沟通后确认机翻了
```suggestion
advancements.tenseigan_achieved.descr=转生眼乃白眼的进化形态。
```

原文：
`The Tenseigan (literally meaning: Reincarnation Eye), is the next evolution of the Byakugan.`
直译：`Tenseigan（字面意思：复活之眼），是Byakugan的下一种进化（形态）。`
Tenseigan（转生眼）、Byakugan（白眼）都不是英语词语，因此需要一个`literally meaning`去解释Tenseigan是什么东西。
`Reincarnation`单独拿出来是转生、转世的意思。轮回确实是一种转世，所以机翻在不考虑专有名词的情况下确实可能会因为各种原因翻成这种东西

2023-11-18 12:19 UTC, luoxueyasha commented
群里沟通了，因为译者能力问题所以close issue
如果有需要的话可以重新open

2023-11-18 12:19 UTC, closed without merging