All Bark,All Bite模组翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3733
Opened 2023-08-28 18:09 UTC by ShaoZhige

添加All Bark, All Bite模组的翻译与英语原语言文件

2023-08-28 18:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3733) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3733) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3733) it.</sub>

2023-08-28 18:34 UTC, ShaoZhige commented
英文原文件被我放到lang外面了，我是蠢货

2023-08-28 18:39 UTC, ShaoZhige commented
> 英文原文件被我放到lang外面了，我好傻。

第一次用github提交翻译，更改了这么多次请原谅我。

2023-08-29 02:40 UTC, KlparetlR commented
你可以看到，你没有签CLA协议，这是pr合并前你必须签署的，可以提前把它签了

2023-08-29 08:26 UTC, ShaoZhige commented
> 你可以看到，你没有签CLA协议，这是pr合并前你必须签署的，可以提前把它签了
谢谢你，这是我不知道的，非常感谢

2023-08-29 10:58 UTC, Cyl18 approved these changes

2023-08-29 12:36 UTC, Cyl18 requested changes

2023-08-29 12:36 UTC, Cyl18 commented on projects/1.19/assets/all-bark-all-bite/all_bark_all_bite/lang/zh_cn.json
> +  "entity.all_bark_all_bite.dog": "狗狗",
```suggestion
  "entity.all_bark_all_bite.dog": "狗",
```
虽然我很想留一点发挥空间，但是
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/14993992/8b5cb30d-1d10-4d5d-b162-ce86e0c5561d)

2023-08-30 02:20 UTC, Cyl18 submitted a review, later dismissed

2023-08-31 18:38 UTC, mamaruo requested changes

2023-08-31 18:38 UTC, mamaruo commented on projects/1.19/assets/all-bark-all-bite/all_bark_all_bite/lang/zh_cn.json
> +  "instrument.all_bark_all_bite.go_whistle": "去",
| **审查级别** |
|--------------|
| ⚪ 轻微 / 不阻止合并但需三思 |

有没有更好的译法

原文：**Go**

2023-08-31 18:38 UTC, mamaruo commented on projects/1.19/assets/all-bark-all-bite/all_bark_all_bite/lang/zh_cn.json
> +  "item.all_bark_all_bite.adjustable_instrument.secondary_use": "潜行来调整",
| **审查级别** |
|--------------|
| 🔴 严重 / **阻止合并，刻不容缓** |

漏译。Use 即 使用 键，默认鼠标右键

原文：**Sneak & Use to Adjust**
```suggestion
  "item.all_bark_all_bite.adjustable_instrument.secondary_use": "潜行时按下“使用”键来调整",
```

2023-08-31 18:38 UTC, mamaruo commented on projects/1.19/assets/all-bark-all-bite/all_bark_all_bite/lang/zh_cn.json
> +  "instrument.all_bark_all_bite.sit_whistle.description": "宠物将会坐下",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

### 类似问题请全文通查

原文：**Pets will sit down\.**
```suggestion
  "instrument.all_bark_all_bite.sit_whistle.description": "宠物将会坐下。",
```

2023-09-08 14:22 UTC, ShaoZhige commented on projects/1.19/assets/all-bark-all-bite/all_bark_all_bite/lang/zh_cn.json
> +  "instrument.all_bark_all_bite.go_whistle": "去",
我也不想这样，但我实在想不到咋样更好......

2023-09-09 03:07 UTC, ChuijkYahus commented on projects/1.19/assets/all-bark-all-bite/all_bark_all_bite/lang/zh_cn.json
> +  "instrument.all_bark_all_bite.go_whistle": "去",
`前去`？
也比较怪

2023-10-01 03:20 UTC, ChuijkYahus submitted a review, later dismissed

2023-10-25 00:21 UTC, mamaruo approved these changes

2023-10-25 01:30 UTC, ChuijkYahus commented on projects/1.19/assets/all-bark-all-bite/all_bark_all_bite/lang/zh_cn.json
> +  "item.all_bark_all_bite.whistle.bound_to": "绑定到: %s"
```suggestion
  "item.all_bark_all_bite.whistle.bound_to": "绑定到：%s"
```
请注意使用全角冒号

2023-10-28 00:48 UTC, ShaoZhige reviewed
更改冒号

2023-10-28 04:50 UTC, ChuijkYahus approved these changes

2023-10-28 05:08 UTC, merged