Immersive Weathering 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3741
Opened 2023-08-30 11:50 UTC by ZHAY10086

慢慢来吧，这配置项看得头疼，部分选项连个描述都无

2023-09-01 16:02 UTC, ChuijkYahus commented
这东西总算有新pr了（）
路径貌似错了

2023-09-03 06:48 UTC, ZHAY10086 commented
草，竟然把路径搞错了

2023-09-03 06:48 UTC, ZHAY10086 commented
/mv-recursive "projects/1.18/assets/immersive-weathering-forge/lang/" "projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/

2023-09-12 17:39 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_cn.json
> +    "block.immersive_weathering.oak_leaf_pile": "橡树叶堆",
```suggestion
    "block.immersive_weathering.oak_leaf_pile": "橡树树叶堆",
```

2023-09-12 17:39 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_cn.json
> +    "block.immersive_weathering.dark_oak_leaf_pile": "深色橡树叶堆",
```suggestion
    "block.immersive_weathering.dark_oak_leaf_pile": "深色橡树树叶堆",
```

2023-09-12 17:39 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_cn.json
> +    "item.immersive_weathering.oak_bark": "橡树皮",
```suggestion
    "item.immersive_weathering.oak_bark": "橡树树皮",
```

2023-09-12 17:39 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_cn.json
> +    "item.immersive_weathering.dark_oak_bark": "深色橡树皮",
```suggestion
    "item.immersive_weathering.dark_oak_bark": "深色橡树树皮",
```

2023-09-12 17:39 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_cn.json
> +    "block.immersive_weathering.leaf_pile": "%s落叶堆",
```suggestion
    "particle.immersive_weathering.leaf_pile": "%s树叶堆",
    "block.immersive_weathering.leaf_pile": "%s树叶堆",
```
与上方树叶堆统一

2023-09-12 17:39 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_cn.json
> +    "block.immersive_weathering.rusted_cut_iron": "氧化的切制铁块",
这个rusted也不能用锈蚀的，比较难整

2023-09-19 06:49 UTC, ZHAY10086 commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_cn.json
> +    "block.immersive_weathering.rusted_cut_iron": "氧化的切制铁块",
官库把词定好了，有点尴尬

2023-09-19 06:56 UTC, ZHAY10086 commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_cn.json
> +    "block.immersive_weathering.leaf_pile": "%s落叶堆",
感谢感谢

2023-09-19 06:58 UTC, ZHAY10086 commented
这周末应该能开搞，挂这么久也说不过去了🥲

2024-01-21 08:43 UTC, ChuijkYahus requested changes

2024-01-21 08:43 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_cn.json
> +    "advancements.immersive_weathering.icicle.description": "咔哧咔哧咔哧 ",
```suggestion
    "advancements.immersive_weathering.icicle.description": "咔哧咔哧咔哧",
```

2024-01-21 08:43 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_cn.json
> +    "item.immersive_weathering.enchanted_golden_moss_clump": "附魔金苔藓丛",
```suggestion
    "item.immersive_weathering.golden_moss_clump": "金苔藓团",
    "item.immersive_weathering.enchanted_golden_moss_clump": "附魔金苔藓团",
```

2024-01-21 08:43 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_cn.json
> +    "sound.immersive_weathering.yummy": "poidobioq eats an apple sticker",
这是啥啊（）

2024-01-21 08:43 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_cn.json
> +    "block.immersive_weathering.rusted_iron_trapdoor": "氧化的铁活版门",
```suggestion
    "block.immersive_weathering.exposed_iron_trapdoor": "斑驳的铁活板门",
    "block.immersive_weathering.weathered_iron_trapdoor": "锈蚀的铁活板门",
    "block.immersive_weathering.rusted_iron_trapdoor": "氧化的铁活板门",
```
请全文通查

2024-01-21 17:10 UTC, ZHAY10086 commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_cn.json
> +    "sound.immersive_weathering.yummy": "poidobioq eats an apple sticker",
没查到，感觉不怎么重要所以直接原文了😶‍🌫️

2024-01-21 17:26 UTC, ZHAY10086 commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_cn.json
> +    "block.immersive_weathering.rusted_iron_trapdoor": "氧化的铁活版门",
草，我是怎么打成活版门的

2024-01-22 06:47 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-weathering-forge/immersive_weathering/lang/zh_cn.json
> +    "sound.immersive_weathering.yummy": "poidobioq eats an apple sticker",
貌似是作者之一的名字，大概又是在玩什么梗吧

2024-01-22 06:50 UTC, ChuijkYahus approved these changes
其他应该没问题了吧

2024-01-23 06:19 UTC, merged