Sophisticated Storage 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3750
Opened 2023-09-02 19:11 UTC by DrIceTea123

本来是想交[官库](https://github.com/P3pp3rF1y/SophisticatedStorage)的，但是想想自己的水平还没到能直接交官库，就先交这边审一下

2023-09-03 09:24 UTC, ChuijkYahus commented
可以拉ZY和炜尔来看

2023-11-18 10:32 UTC, dovisutu approved these changes
粗看了一下，没多大问题吧

2024-04-22 08:04 UTC, SlimeSB commented on projects/1.18/assets/sophisticated-storage/sophisticatedstorage/lang/zh_cn.json
> +  "block.sophisticatedstorage.barrel": "%s桶",
**原文: %s%sBarrel**

```suggestion
  "block.sophisticatedstorage.barrel": "%s桶",
```

2024-04-22 08:08 UTC, SlimeSB commented on projects/1.18/assets/sophisticated-storage/sophisticatedstorage/lang/zh_cn.json
> +  "block.sophisticatedstorage.iron_barrel": "%s铁桶",
**原文: %s%sIron Barrel**

```suggestion
  "block.sophisticatedstorage.iron_barrel": "%s铁桶",
```

2024-04-22 08:16 UTC, SlimeSB requested changes

2024-04-22 08:16 UTC, SlimeSB commented on projects/1.18/assets/sophisticated-storage/sophisticatedstorage/lang/zh_cn.json
> +  "block.sophisticatedstorage.iron_barrel": "%s铁桶",
橡木铁桶 和 铁橡木桶 我还是倾向于“铁橡木桶”
如果这里占位符是木材的话

2024-04-22 08:23 UTC, SlimeSB commented
这个搁置太久了，以至于上游已经有人上传了1.18.2的中文文件
[here](https://github.com/P3pp3rF1y/SophisticatedStorage/blob/1.18.x/src/main/resources/assets/sophisticatedstorage/lang/zh_cn.json)继续维护还是就此作罢

2024-05-01 04:28 UTC, SlimeSB commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。
@DrIceTea123

2024-05-09 08:09 UTC, closed without merging