Rad Enchants 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3751
Opened 2023-09-02 19:22 UTC by xy5485

2023-09-03 14:14 UTC, Cactusstudent requested changes
1.16 版本半角字符与汉字之间**不再需要**空格
请区分魔咒与附魔，具体请查阅Wiki。

2023-09-04 09:03 UTC, ChuijkYahus commented on projects/1.16/assets/rad-enchants/radenchants/lang/zh_cn.json
> +    "tooltip.radenchants.sockets.info.enhance":" > 增强 (升级层数 %s):",
```suggestion
    "tooltip.radenchants.sockets.info.upgrade":" > 升级（提升%s数值）：",
    "tooltip.radenchants.sockets.info.wipe":" > 拆除（取下镶嵌物）：:",
    "tooltip.radenchants.sockets.info.etch":" > 蚀刻（填充空镶嵌槽）：",
    "tooltip.radenchants.sockets.info.enhance":" > 增强（升级层数%s）：",
```
最后一行在游戏中显示的是什么

2023-09-04 09:03 UTC, ChuijkYahus commented on projects/1.16/assets/rad-enchants/radenchants/lang/zh_cn.json
> +    "tooltip.radenchants.sockets.enhance_pending":"+层数!",
```suggestion
    "tooltip.radenchants.sockets.etch_pending":" + 新的镶嵌槽！",
    "tooltip.radenchants.sockets.enhance_pending":" + 层数！",
```

2023-09-04 09:03 UTC, ChuijkYahus commented on projects/1.16/assets/rad-enchants/radenchants/lang/zh_cn.json
> +    "tooltip.radenchants.sockets.upgrade_value":"升级数量: %s, %s - %s, %s%%",
```suggestion
    "tooltip.radenchants.sockets.original_value":"原始随机：%s，%s - %s，%s%%",
    "tooltip.radenchants.sockets.upgrade_value":"升级数量：%s，%s - %s，%s%%",
```
这里的roll指的是什么

2023-09-05 16:59 UTC, ChuijkYahus commented on projects/1.16/assets/rad-enchants/radenchants/lang/zh_cn.json
> +    "enchantment.radenchants.deep_pockets.desc":"死亡时保留快捷栏的物品,二级时可以保留护腿本身和饰品栏",
```suggestion
    "enchantment.radenchants.deep_pockets.desc":"死亡时保留快捷栏的物品，二级时可以保留护腿本身和饰品",
```

2023-09-05 16:59 UTC, ChuijkYahus commented on projects/1.16/assets/rad-enchants/radenchants/lang/zh_cn.json
> +    "enchantment.radenchants.seventh.desc":"当命中计数器为七时,造成的伤害翻倍",
```suggestion
    "enchantment.radenchants.seventh.desc":"当命中计数器为七时，造成的伤害翻倍",
```

2023-09-05 16:59 UTC, ChuijkYahus commented on projects/1.16/assets/rad-enchants/radenchants/lang/zh_cn.json
> +    "enchantment.radenchants.paladin":"舍己为人",
这个和上面那个gunner还是遵照原文吧

2023-09-05 16:59 UTC, ChuijkYahus commented on projects/1.16/assets/rad-enchants/radenchants/lang/zh_cn.json
> +    "message.radenchants:snitch.fail":" 无效目标！",
```suggestion
    "message.radenchants:snitch.fail":"无效目标！",
```
缩进跟原文来吧

2023-09-05 16:59 UTC, ChuijkYahus commented on projects/1.16/assets/rad-enchants/radenchants/lang/zh_cn.json
> +    "tooltip.radenchants.sockets.info.enhance":" > 破限 (增强武器的属性上限（每个词条限一次）%s):",
```suggestion
    "tooltip.radenchants.sockets.info.upgrade":" > 升级（增加单个词条属性并添加已升级标识 %s）：",
    "tooltip.radenchants.sockets.info.wipe":" > 重铸（刷新强化词条，有概率减少词条！）：",
    "tooltip.radenchants.sockets.info.etch":" > 蚀刻（填充空词条位(词条数量对应魔咒当前等级）：",
    "tooltip.radenchants.sockets.info.enhance":" > 破限（增强武器的属性上限（每个词条限一次）%s）：",
```

2023-09-05 16:59 UTC, ChuijkYahus commented on projects/1.16/assets/rad-enchants/radenchants/lang/zh_cn.json
> +    "tooltip.radenchants.sockets.original_value":"初始属性: %s, 属性范围:%s - %s, 收益:%s%%",
```suggestion
    "tooltip.radenchants.sockets.original_value":"初始属性：%s，属性范围：%s - %s，收益：%s%%",
```

2023-09-05 16:59 UTC, ChuijkYahus commented on projects/1.16/assets/rad-enchants/radenchants/lang/zh_cn.json
> +    "tooltip.radenchants.sockets.upgrade_value":"升级属性: %s, 属性范围：%s - %s, 收益:%s%%",
```suggestion
    "tooltip.radenchants.sockets.upgrade_value":"升级属性：%s，属性范围：%s - %s，收益：%s%%",
```

2023-09-05 16:59 UTC, ChuijkYahus commented on projects/1.16/assets/rad-enchants/radenchants/lang/zh_cn.json
> +    "enchantment.radenchants.earplugs.desc":"使用“/earplugs”命令来减弱声音。除减弱单个声音外，还可减弱声音路径中所有升级，如“minecraft:entity.cow”。",
```suggestion
    "enchantment.radenchants.earplugs.desc":"使用“/earplugs”命令来减弱声音。除减弱单个声音外，还可减弱声音路径中所有声音，如“minecraft:entity.cow”。",
```

2023-09-05 17:59 UTC, ChuijkYahus commented on projects/1.16/assets/rad-enchants/radenchants/lang/zh_cn.json
> +    "enchantment.radenchants.deep_pockets.desc":"死亡时保留快捷栏的物品,二级时可以保留护腿本身和饰品栏",
`饰品栏`不改没问题，半角逗号需要改成全角逗号

2023-09-06 05:18 UTC, ChuijkYahus submitted a review, later dismissed

2023-09-07 04:46 UTC, ChuijkYahus commented on projects/1.16/assets/rad-enchants/radenchants/lang/zh_cn.json
> +    "key.radenchants.sockets_info":"显示强化信息",
别啊
这两个的原文就是socket，是插槽的意思

2023-09-09 02:53 UTC, ChuijkYahus reviewed
socket为什么译作强化而不是镶嵌

2023-09-09 03:35 UTC, ChuijkYahus commented
Sockets这个魔咒有需要消耗物品的镶嵌操作吗
不过还是推荐遵照原文

2023-09-09 11:43 UTC, ChuijkYahus commented
如果已经回复可以看下自己评论上有没有`Pending`这个标记
带有这个标记的评论仅自己可见
可在Files changed页面Review changes按钮提交评论，就会实际发出来了

2023-09-09 12:55 UTC, Cactusstudent approved these changes
看的粗，看起来问题不大

2023-09-09 15:57 UTC, Flowingtime2002 commented
> 如果已经回复可以看下自己评论上有没有`Pending`这个标记 带有这个标记的评论仅自己可见 可在Files changed页面Review changes按钮提交评论，就会实际发出来了

感情我一直在自言自语，哭了

2023-09-09 15:57 UTC, Flowingtime2002 commented
> > 如果已经回复可以看下自己评论上有没有`Pending`这个标记 带有这个标记的评论仅自己可见 可在Files changed页面Review changes按钮提交评论，就会实际发出来了
> 
> 感情我一直在自言自语，哭了

@ChuijkYahus

2023-09-09 15:59 UTC, Flowingtime2002 commented
> Sockets这个魔咒有需要消耗物品的镶嵌操作吗 不过还是推荐遵照原文

有的，按shift加alt就可以看到需要的材料和信息，上面有个问题导致材料显示为物品标签，拜托帮忙看看，请教请教

2023-09-09 16:00 UTC, Flowingtime2002 commented on projects/1.16/assets/rad-enchants/radenchants/lang/zh_cn.json
> +    "tooltip.radenchants.sockets.info":" %sx %s + %s 等级",
> 这个中间本来改显示强化材料的，但是现在却显示的是物品标签，咋汉化这里 比如升级 游戏里现在显示是: 升级（增加单个词条属性并添加已升级标识 %s）：5x forge/games/emerald + 10等级 应该是：升级（增加单个词条属性并添加已升级标识 %s）：5x 绿宝石 + 10等级 才对

就是这个问题 @ChuijkYahus

2023-09-09 16:01 UTC, ChuijkYahus commented on projects/1.16/assets/rad-enchants/radenchants/lang/zh_cn.json
> +    "enchantment.radenchants.void_bane.desc":"将一部分伤害转化为虚空伤害,同时伤害持有者和武器",
只要不是红色名字就不是诅咒（）
虽然这么说，神化还有些其他颜色，比较难评，按原文有没有`Curse of`来吧

2023-09-09 16:02 UTC, ChuijkYahus commented on projects/1.16/assets/rad-enchants/radenchants/lang/zh_cn.json
> +    "enchantment.radenchants.gluttony.desc":"吃的更快,但回复的饥饿值变低",
代码上注册事物的时候饱和度写的是一个比值，最终结果是饥饿值乘上这个比值，大概就是这个`nutritional value`吧
不过直接`饱和度`应该也行吧

2023-09-09 16:04 UTC, ChuijkYahus commented on projects/1.16/assets/rad-enchants/radenchants/lang/zh_cn.json
> +    "enchantment.radenchants.seventh.desc":"当命中计数器为七时,造成的伤害增加",
真就777幸运暴击

2023-09-09 16:05 UTC, ChuijkYahus commented on projects/1.16/assets/rad-enchants/radenchants/lang/zh_cn.json
> +    "enchantment.radenchants.one_with_the_blade.desc":"背包里只有这把武器时才会提升造成的伤害",
狂战士是吧

2023-09-09 16:06 UTC, ChuijkYahus commented on projects/1.16/assets/rad-enchants/radenchants/lang/zh_cn.json
> +    "tooltip.radenchants.sockets.info":" %sx %s + %s 等级",
算是模组作者的问题了，保留就行
%s里的东西是代码决定的，看作者怎么写了，汉化没法改这块

2023-09-09 16:07 UTC, ChuijkYahus commented on projects/1.16/assets/rad-enchants/radenchants/lang/zh_cn.json
> +    "tooltip.radenchants.sockets.info.enhance":" > 破限（增强武器的属性上限（每个词条限一次）%s）：",
按原文来就行，不用单独就改（）
%s里的东西是代码决定的，看作者怎么写了，汉化没法改这块

2023-09-09 16:08 UTC, ChuijkYahus commented
标签直接拷打作者就是了（）
如果英文环境下还是显示成标签就不用管了

2023-09-09 16:09 UTC, ChuijkYahus commented
Socketed有消耗材料还是建议翻译成`镶嵌`

2023-09-09 17:03 UTC, ChuijkYahus approved these changes

2023-09-10 08:23 UTC, merged