Immersive Petroleum 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #3762
Opened 2023-09-05 16:53 UTC by ChuijkYahus

2023-10-04 14:56 UTC, Cactusstudent commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/cokerunit.txt
>  在前面的控制面板上通入红石信号将停止机器的进程，可以用工程师螺丝刀来反转。
红石信号这个前面的动词该用啥？通入个人认为不规范，Wiki有“提供”这样的字眼

2023-10-04 14:56 UTC, Cactusstudent commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/cokerunit.txt
> +沥青进入焦化仓室。装载完成后，给仓室加高温，从而将沥青转化为石油焦和含硫柴油。
“加高温”其实就是指“升高温度”之类的吧，如果是的话后者怕是好些

2023-10-04 14:56 UTC, Cactusstudent commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/cokerunit.txt
> +焦化室未满时也可开始加工，且在焦化循环的第一阶段还可中途加入沥青。但输出和排空阶段开始后，需先等待循环结束才可再次输入。
```suggestion
焦化室未满时也可开始加工，且在焦化循环的第一阶段中还可输入沥青。但输出和排空阶段开始后，需先等待循环结束才可再次输入。

```

2023-10-04 14:56 UTC, Cactusstudent commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/oiltank.txt
> +储油罐是能自动平均分配的流体储罐，容量比<link;tank;§o§n流体储罐§r>稍大，其侧面、顶部和底部均有流体输入输出舱口。它能存储最多1024B的非气态流体。<np>
```suggestion
储油罐是能自动平均分配的流体储罐，容量比<link;tank;§o§n流体储罐§r>稍大，其侧面、顶部和底部均有流体输入输出舱口。它最多能存储1024B的非气态流体。<np>
```

2023-10-04 14:56 UTC, Cactusstudent commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/oiltank.txt
> +储油罐会和与其相邻的未经配置的储油罐自动平均分配其中流体，因此所有相连的储油罐的流体含量都将大致相同。
好怪，这句定语太多读着好别扭
```suggestion
储油罐会与未经配置的毗邻储油罐平均分配其中流体，因此所有毗邻的储油罐中的流体含量都大致相同。
```

2023-10-04 14:56 UTC, Cactusstudent commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/oiltank.txt
> +例如，一个附在第二层的比较器，在储油罐1/3满之前不会发出任何信号；如果储油罐是2/3满或更多，则发出强度为15的信号。
```suggestion
例如，一个附在第二层的比较器，在储油罐1/3满之前不会发出任何信号；如果储油罐是2/3满或更多，则发出强度为15的红石信号。

```

2023-10-04 14:56 UTC, Cactusstudent commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/plastics.txt
>  而利用全新开发的裂解工艺，这重要一环就被补上了：通过高温综合加工工艺处理<link;immersivepetroleum:fluids;§n§o石脑油§r;naphtha>，将其裂解为各烃组分，就能进一步制得酚醛树脂。
```suggestion
而利用全新开发的裂解工艺，就将这重要一环补上了：通过高温综合加工工艺处理<link;immersivepetroleum:fluids;§n§o石脑油§r;naphtha>，将其裂解为各烃组分，就能进一步制得酚醛树脂。
```
还是应当避免被动，咱不太这么说话

2023-10-04 14:56 UTC, Cactusstudent commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/plastics.txt
>  而利用全新开发的裂解工艺，这重要一环就被补上了：通过高温综合加工工艺处理<link;immersivepetroleum:fluids;§n§o石脑油§r;naphtha>，将其裂解为各烃组分，就能进一步制得酚醛树脂。
```suggestion
而利用全新开发的裂解工艺，就将这重要一环补上了：通过高温综合加工工艺处理<link;immersivepetroleum:fluids;§n§o石脑油§r;naphtha>，将其裂解为各烃组分，就能进一步制得酚醛树脂。
```
还是应当避免被动，咱不太这么说话

2023-10-04 14:56 UTC, Cactusstudent commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/portablegenerator.txt
> +便携式发电机在燃烧<link;immersivepetroleum:fluids;§n§o汽油§r;gasoline>、<link;immersivepetroleum:fluids;§n§o石脑油§r;naphtha>，<link;immersivepetroleum:fluids;§n§o苯§r;naphtha_derivates>等燃料时能产生最多<config;i;portablegen
```suggestion
便携式发电机在燃烧<link;immersivepetroleum:fluids;§n§o汽油§r;gasoline>、<link;immersivepetroleum:fluids;§n§o石脑油§r;naphtha>，<link;immersivepetroleum:fluids;§n§o苯§r;naphtha_derivates>等燃料时能产生最多<config;i;portablegenerator_flux>IF/t，且具有100000IF的能量缓存。
```
原文如此

2023-10-04 14:56 UTC, Cactusstudent commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/portablegenerator.txt
> +高质量燃料的燃烧时间更长，给予红石信号会停止其运作，不会损失燃料。
同上文“提供”“红石信号”

2023-10-04 14:56 UTC, Cactusstudent commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/speedboat.txt
> +§2扩展油箱§r将允许汽艇承载两倍的油量。
```suggestion
§2扩展油箱§r将允许汽艇装载两倍的油量。
```

2023-10-04 14:56 UTC, Cactusstudent commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/speedboat.txt
> +<&speedboat4>如果你想要探索维度之外的领域，或者只是想让汽艇能抵御各种自然危险，请考虑安装§2强化船体§r。它提高了汽艇的生命值和耐火性，能让船只在下界广阔的熔岩湖中航行。
```suggestion
<&speedboat4>如果你想要探索维度之外的领域，或者只是想让汽艇能抵御各种自然危险，请考虑安装§2强化船体§r。它提高了汽艇的生命值和耐火性，能让船只在下界广阔的熔岩海中航行。
```
好像是熔岩海来着？

2023-10-04 14:58 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/cokerunit.txt
>  在前面的控制面板上通入红石信号将停止机器的进程，可以用工程师螺丝刀来反转。
这里其实是ie本体的译法

2023-10-04 15:01 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/speedboat.txt
> +<&speedboat4>如果你想要探索维度之外的领域，或者只是想让汽艇能抵御各种自然危险，请考虑安装§2强化船体§r。它提高了汽艇的生命值和耐火性，能让船只在下界广阔的熔岩湖中航行。
只能说原文如此

2023-10-04 15:03 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/cokerunit.txt
> +沥青进入焦化仓室。装载完成后，给仓室加高温，从而将沥青转化为石油焦和含硫柴油。
```suggestion
沥青进入焦化仓室。装载完成后，升高仓室的温度，从而将沥青转化为石油焦和含硫柴油。
```

2023-10-04 15:03 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/portablegenerator.txt
> +高质量燃料的燃烧时间更长，给予红石信号会停止其运作，不会损失燃料。
```suggestion
高质量燃料的燃烧时间更长，提供红石信号会停止其运作，不会损失燃料。
```

2023-10-04 15:04 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/cokerunit.txt
> +
```suggestion
```

2023-10-04 15:06 UTC, Cactusstudent commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/speedboat.txt
> +<&speedboat4>如果你想要探索维度之外的领域，或者只是想让汽艇能抵御各种自然危险，请考虑安装§2强化船体§r。它提高了汽艇的生命值和耐火性，能让船只在下界广阔的熔岩湖中航行。
那就原文为准吧

2023-10-04 15:09 UTC, Cactusstudent approved these changes

2023-10-05 00:30 UTC, Cactusstudent submitted a review, later dismissed

2023-10-05 01:39 UTC, luoxueyasha reviewed
看的脑袋疼（ptsd犯了
这个真得找石油钻井业内的资料了，互联网上可能比较难找
脑袋里都是俗称所以不好确定译名

2023-10-05 01:39 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/derrick.txt
> +第一阶段是强化钻探阶段，此时钻头位于基岩层上方，且必须用<link;immersiveengineering:mixer;§o§n液态混凝土§r>强化并稳定流体管道。管道被破坏则必须重新铺设所有管道。<np>
```suggestion
第一阶段是固井钻探阶段，此时钻头位于基岩层上方，且必须用<link;immersiveengineering:mixer;§o§n液态混凝土§r>对管道进行固井。管道被破坏则必须重新铺设所有管道。<np>
```
这个`第一阶段`、`第二阶段`应该指的是`一次开钻`、`二次开钻`（俗称一开、二开；也有三开四开等）
指先钻到一定深度后用水泥固定管道防止井喷（固井）；再钻入固定好的管道后达到指定深度
要改的话上下文都得改对应描述

2023-10-05 01:39 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/derrick.txt
> +钻孔中的正压力会将流体压到地表，进入钻井内部储罐或是外部流体储罐（如<link;immersivepetroleum:oiltank;§o§n储油罐§r>）内。如果钻井内部储罐已满且无输出能力，释压阀会打开，钻出的流体就将冲出钻井顶部，造成浪费。
这段描述的应该是指井喷
原文`the pressure relief valve will blow`应该是指释压阀被冲破的那种情况，用`打开`不太合适（起码用`被打开`）

2023-10-05 06:47 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/derrick.txt
> +钻孔中的正压力会将流体压到地表，进入钻井内部储罐或是外部流体储罐（如<link;immersivepetroleum:oiltank;§o§n储油罐§r>）内。如果钻井内部储罐已满且无输出能力，释压阀会打开，钻出的流体就将冲出钻井顶部，造成浪费。
这里`fluid`是泛指流体，还是特指排出的某种液体？

2023-10-05 07:01 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/derrick.txt
> +钻孔中的正压力会将流体压到地表，进入钻井内部储罐或是外部流体储罐（如<link;immersivepetroleum:oiltank;§o§n储油罐§r>）内。如果钻井内部储罐已满且无输出能力，释压阀会打开，钻出的流体就将冲出钻井顶部，造成浪费。
实际流程是钻井钻开之后，流体（水、熔岩、原油）会先喷出一些，如果钻井没接上流体存储设施就会井喷
喷完后换磕头机抽

应该是指钻出的液体吧
```suggestion
钻孔中的正压力会将流体压到地表，进入钻井内部储罐或是外部流体储罐（如<link;immersivepetroleum:oiltank;§o§n储油罐§r>）内。如果钻井内部储罐已满且无输出能力，释压阀会打开，钻出的液体就将冲出钻井顶部，造成浪费。
```

2023-10-05 07:16 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/flarestack.txt
> +<&flarestack0>焚油烟囱可以燃烧掉从底部输入舱口泵入的可燃性流体，并产生一道火舌。
这个`port`必须是`舱口`吗？

2023-10-05 07:17 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/derrick.txt
> +钻孔中的正压力会将流体压到地表，进入钻井内部储罐或是外部流体储罐（如<link;immersivepetroleum:oiltank;§o§n储油罐§r>）内。如果钻井内部储罐已满且无输出能力，释压阀会打开，钻出的流体就将冲出钻井顶部，造成浪费。
那不限定为minecraft中的fluid就行
一会等全译完看群吧

2023-10-05 07:24 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/flarestack.txt
>  焚油烟囱
这玩意学名就叫`烟囱`（或者`火炬`）（原文：`flarestack`）
要不要考虑改一下

2023-10-05 07:28 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/en_us/fluids.txt
> +It can be burned in the flare stack or cracked into <link;immersivepetroleum:fluids;§n§odiesel§r;diesel> and <link;immersivepetroleum:fluids;§n§okerosene§r;kerosene> if such activities are not useful
此处是`flare stack`和下文的`flarestack`是否为同一方块？

2023-10-05 07:30 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/flarestack.txt
> +<&flarestack0>焚油烟囱可以燃烧掉从底部输入舱口泵入的可燃性流体，并产生一道火舌。
鉴定为IE本体翻译

2023-10-05 07:32 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/flarestack.txt
>  焚油烟囱
也OK，不知道直接缩减为烟囱或者火炬会不会与chimney和torch搞混
不过这个译名用很长时间了（）

2023-10-05 08:31 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/oiltank.txt
> +例如，一个附在第二层的比较器，在储油罐1/3满之前不会发出任何信号；如果储油罐是2/3满或更多，则发出强度为15的红石信号。
原文分别对应的是1/4、1/2，存疑

2023-10-05 08:32 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/cokerunit.txt
> +能量需从机器前面的两个强电流连接器输入，沥青和水需从前面带有蓝色圆点的舱口输入。含硫柴油会从前面带有橙色圆点的舱口输出，而石油焦则会从仓室溜槽下方输出。
```suggestion
能量需从机器前面的两个强电流连接器输入，沥青和水需从前面带有蓝色圆点的舱口输入。含硫柴油会从前面带有橙色圆点的舱口输出，而石油焦则会从焦炭塔下方的两个漏斗输出。
```
原文的two hoppers指？

2023-10-05 08:33 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/flarestack.txt
> +<&flarestack0>焚油烟囱可以燃烧掉从底部输入舱口泵入的可燃性流体，并产生一道火舌。
那`输入口` `输出口`吧，`舱口`感觉一股机翻味
请全文通查

2023-10-05 08:33 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/derrick.txt
>  钻井
```suggestion
井架
```
讨论之后的结果，看看要不要改

2023-10-05 08:34 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/derrick.txt
> +第一阶段是强化钻探阶段，此时钻头位于基岩层上方，且必须用<link;immersiveengineering:mixer;§o§n液态混凝土§r>强化并稳定流体管道。管道被破坏则必须重新铺设所有管道。<np>
```suggestion
第一阶段是预制钻探阶段，此时钻头位于基岩层上方，且必须用<link;immersiveengineering:mixer;§o§n液态混凝土§r>固化并稳定流体管道。如流体管道被破坏则必须重新预制所有管道。<np>
```
不确定ie对应的术语是否正确，建议查一下

2023-10-05 08:35 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/derrick.txt
> +钻至基岩层后，第二阶段开始，此时需供给冷却水而非混凝土。钻井将开始钻过基岩层并钻至设定好的一或多个目标位置，过程中会消耗水和流体管道。<np>
```suggestion
钻至基岩层后，第二阶段开始，此时需供给冷却水而非混凝土。井架将开始钻过基岩层并钻至设定好的一或多个目标位置，过程中会消耗水和流体管道。<np>
```

2023-10-05 08:35 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/derrick.txt
> +钻孔完成且井口开放后，钻探设备会被下方的流体压力推出井口。
```suggestion
完井且井口开放后，钻探设备会被下方的流体压力推出井口。
```

2023-10-05 08:35 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/derrick.txt
> +钻孔中的正压力会将流体压到地表，进入钻井内部储罐或是外部流体储罐（如<link;immersivepetroleum:oiltank;§o§n储油罐§r>）内。如果钻井内部储罐已满且无输出能力，释压阀会打开，钻出的流体就将冲出钻井顶部，造成浪费。
```suggestion
井口中的正压力会将流体压到地表，进入井架储罐或是外部流体储罐（如<link;immersivepetroleum:oiltank;§o§n储油罐§r>）内。如果井架储罐已满且无输出能力，减压阀会打开，钻出的流体就将冲出井架顶部，造成浪费。
```

2023-10-05 08:36 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/derrick.txt
>  流体储层的液压差降至零后，钻井就可以拆除了，后续的流体抽取过程交由<link;immersivepetroleum:pumpjack;§o§n抽油机§r>执行。
```suggestion
流体储层的液压差降至零后，井架就可以拆除了，后续的流体抽取过程交由<link;immersivepetroleum:pumpjack;§o§n抽油机§r>执行。
```

2023-10-05 08:36 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/derrick.txt
> +钻井会向基岩下方包含<link;immersivepetroleum:reservoir;§o§n流体储层§r>的多孔地层中铺设强化管道，以此搭建井口装置。<np>
```suggestion
井架会向基岩下方包含<link;immersivepetroleum:reservoir;§o§n流体储层§r>的多孔地层中铺设预制管，以此搭建井口装置。<np>
```

2023-10-05 08:36 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/derrick.txt
> +流体需从带有蓝色圆点的流体舱口输入，钻得的流体则会从带有橙色圆点的流体舱口输出。管道则必须手动放入。
```suggestion
流体需从带有蓝色圆点的流体舱口输入，钻得的流体则会从带有橙色圆点的流体舱口输出。钻管则必须手动放入。
```
涉及`port`注意
`钻管`是专业术语，考虑ie的话是不是可以不用改

2023-10-05 08:37 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/derrick.txt
> +钻井的钻采过程分为两个阶段，且无法在水位线以下进行，否则水会进入未完成的钻孔并侵蚀孔壁。
```suggestion
井架的钻采过程分为两个阶段，且无法在水位线以下进行，否则水会进入未完成的井中并侵蚀井壁。
```

2023-10-05 08:38 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/cokerunit.txt
>  焦化器
```suggestion
焦炭塔
```
术语
请全文通查

2023-10-05 08:38 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/cokerunit.txt
> +沥青进入焦化仓室。装载完成后，升高仓室的温度，从而将沥青转化为石油焦和含硫柴油。
```suggestion
沥青进入焦炭塔。装载完成后，升高塔的温度，从而将沥青转化为石油焦和含硫柴油。
```

2023-10-05 08:38 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/cokerunit.txt
> +转换完成后，需排空仓室内的含硫柴油，并注入水以冷却仓室，为下一批沥青做好准备。<np>
```suggestion
转换完成后，需排空焦炭塔内的含硫柴油，并注入水以冷却塔室，为下一批沥青做好准备。<np>
```

2023-10-05 08:38 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/cokerunit.txt
> +焦化室未满时也可开始加工，且在焦化循环的第一阶段中还可输入沥青。但输出和排空阶段开始后，需先等待循环结束才可再次输入。
```suggestion
焦炭塔未满时也可开始加工，且在焦化循环的第一阶段中还可输入沥青。但输出和清洗阶段开始后，需先等待循环结束才可再次输入。
```

2023-10-05 08:39 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/distillationtower.txt
>  精馏塔
```suggestion
蒸馏塔
```
refinary才是精馏，请全文通查

2023-10-05 08:40 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/flarestack.txt
>  焚油烟囱
那就保留（

2023-10-05 08:47 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/cokerunit.txt
> +能量需从机器前面的两个强电流连接器输入，沥青和水需从前面带有蓝色圆点的舱口输入。含硫柴油会从前面带有橙色圆点的舱口输出，而石油焦则会从仓室溜槽下方输出。
看到了，那记得翻译出来two
hoppers因为不是原版漏斗所以……看着办吧

2023-10-06 08:27 UTC, luoxueyasha requested changes

2023-10-06 08:27 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/lang/zh_cn.json
> +	"block.immersivepetroleum.coker_unit": "焦化器",
```suggestion
	"block.immersivepetroleum.coker_unit": "焦炭塔",
```
请全文通查

2023-10-06 08:37 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/lang/zh_cn.json
> +	"block.immersivepetroleum.coker_unit": "焦化器",
怪，这里怎么没交上去

2023-10-08 13:01 UTC, luoxueyasha requested changes

2023-10-08 13:01 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/pumpjack.txt
> +抽油机的管道头部必须对准井口，才可将阀门组件放入井口以正常工作。<np>
```suggestion
抽油机的前管必须对准井口，才可将阀门组件放入井口以正常工作。<np>
```

2023-10-08 18:43 UTC, ChuijkYahus commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/hydrotreater.txt
>  高压精炼单元
![2023-10-09_02 42 27](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/78e4282c-6f66-43de-ba1f-b97042c41a69)
![2023-10-09_02 42 32](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/597e3556-ccb7-4fee-9a58-3cc24d2a4051)
![2023-10-09_02 42 37](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/d16652eb-04c7-4b3f-8cbd-e726e8b070ab)
![2023-10-09_02 42 55](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/ed1b9164-62a8-42d9-b983-0b9c8e6ce155)

2023-10-09 04:02 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/hydrotreater.txt
>  高压精炼单元
术语上更偏向译为`装置`
如果IE有对unit统一的翻译的话那就按IE那边走

2023-10-09 05:00 UTC, luoxueyasha commented on projects/1.18/assets/immersive-petroleum/immersivepetroleum/manual/zh_cn/hydrotreater.txt
>  高压精炼单元
术语上更偏向译为`装置`
如果IE有对unit统一的翻译的话那就按IE那边走

2023-10-10 02:20 UTC, luoxueyasha approved these changes

2023-10-14 09:41 UTC, merged