Tome Of Blood Rebirth 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3774
Opened 2023-09-12 13:28 UTC by ChuijkYahus

2023-09-16 03:55 UTC, DrIceTea123 requested changes
新生魔艺的附属……
没啥大问题

2023-09-16 03:55 UTC, DrIceTea123 commented on projects/1.20/assets/tome-of-blood-rebirth/tomeofblood/lang/zh_cn.json
> +  "item.tomeofblood.novice_tome_of_blood": "初学者血之宝典",
参考前置模组 #3133
```suggestion
  "item.tomeofblood.novice_tome_of_blood": "学徒血之宝典",
```

2023-09-16 06:09 UTC, ChuijkYahus commented on projects/1.20/assets/tome-of-blood-rebirth/tomeofblood/lang/zh_cn.json
> +  "item.tomeofblood.novice_tome_of_blood": "初学者血之宝典",
新生魔艺这三个等级在1192改名字了
从原来的Novice、Mage、Archmage改成了Novice、Apprentice、Archmage
直接这么改会和Apprentice冲突，就和L5一样了

2023-09-16 06:22 UTC, DrIceTea123 commented on projects/1.20/assets/tome-of-blood-rebirth/tomeofblood/lang/zh_cn.json
> +  "item.tomeofblood.novice_tome_of_blood": "初学者血之宝典",
approved

2023-09-27 12:44 UTC, luoxueyasha approved these changes

2023-09-30 04:14 UTC, merged