Project Expansion 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3786
Opened 2023-09-17 05:36 UTC by eciv-oN

第288行"text.projectexpansion.provider_error"在源码中仅单次出现于lang文件中，游戏内也无对应文本，故未进行翻译

由 CFPA-Helper 提交。

2023-09-17 10:31 UTC, eciv-oN commented
在已翻译的ProjectE与FTB Project EX模组中MK均未翻译，但原文中均有出现MK；
此模组原文未出现MK，请问是应该删除MK描述还是改成...型呢？

2023-09-22 17:07 UTC, DrIceTea123 requested changes
基本通查了一遍

2023-09-22 17:07 UTC, DrIceTea123 commented on projects/1.18/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"command.projectexpansion.emc.add.success": "成功将%sEMC添加到%s，他现在有%s。",
这里似乎是给玩家？需要看下实际效果，如果是给玩家的话，翻译为“添加到”显然不合语境
下文同

2023-09-22 17:07 UTC, DrIceTea123 commented on projects/1.18/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"gui.projectexpansion.config.tick_delay.desc": "模组物品每次工作之间的延迟（以游戏刻为单位，默认为 20）。这将因舍入导致产生的EMC数量受到略微影响。如果发现卡顿，请增加此延迟时间。",
```suggestion
	"gui.projectexpansion.config.tick_delay.desc": "模组物品每次工作之间的延迟（以游戏刻为单位，默认为20）。会因四舍五入导致产生的EMC数量受到略微影响。如果发现卡顿，请增加此延迟时间。",
```

2023-09-22 17:07 UTC, DrIceTea123 commented on projects/1.18/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"text.projectexpansion.alchemical_collection": "炼金采集: %s",
请修改半角标点

2023-11-18 07:38 UTC, ChuijkYahus approved these changes
应该问题不大了，需要另一位审核再看一眼

2023-11-25 00:31 UTC, luoxueyasha approved these changes
没什么太大的问题

2023-11-25 00:35 UTC, luoxueyasha requested changes
强烈建议与1.16版本的Project Expansion（#2762）进行对比和译名同步

2023-11-25 00:39 UTC, luoxueyasha commented
我对比了本PR（#3786 ）和#2762 ，以下是对比结果：
<details><summary>格式说明</summary>

| Key | 英文 | 中文 |
| - | --: | :------------- |
|  `key名` | 英文原文 | #2762 的译文<br>🔽<br>本PR的译文 |
</details>

<details><summary>对比结果</summary>

| Key | 英文 | 中文 |
| - | --: | :------------- |
|  `block.projectexpansion.advanced_alchemical_chest.color_set` |The color has been set to %s. | 已设置颜色为：%s。<br>🔽<br>颜色已被设置为%s。 |
|  `block.projectexpansion.advanced_alchemical_chest.invalid_item` |You must be holding a %s to set the color. | 你必须按住%s来设置颜色。<br>🔽<br>你必须手持一个%s来改变颜色。 |
|  `block.projectexpansion.advanced_alchemical_chest.tooltip` |Just like the alchemical bag, but in a chest form. Shift click with a bag to set the color. | 和炼金术之袋很像，只是换成了箱子。手持袋子Shift右击设置颜色。<br>🔽<br>就像炼金术之袋一样，不过是箱子的形式。手持炼金术之袋Shift右击箱子可设置颜色。 |
|  `block.projectexpansion.blue_advanced_alchemical_chest` |Blue Advanced Alchemical Chest | 蓝色高级炼金术之箱<br>🔽<br>蓝色炼金术之箱 |
|  `block.projectexpansion.brown_advanced_alchemical_chest` |Brown Advanced Alchemical Chest | 棕色高级炼金术之箱<br>🔽<br>棕色炼金术之箱 |
|  `block.projectexpansion.green_advanced_alchemical_chest` |Green Advanced Alchemical Chest | 绿色高级炼金术之箱<br>🔽<br>绿色炼金术之箱 |
|  `block.projectexpansion.red_advanced_alchemical_chest` |Red Advanced Alchemical Chest | 红色高级炼金术之箱<br>🔽<br>红色炼金术之箱 |
|  `block.projectexpansion.black_advanced_alchemical_chest` |Black Advanced Alchemical Chest | 黑色高级炼金术之箱<br>🔽<br>黑色炼金术之箱 |
|  `block.projectexpansion.collector.tooltip` |Generates EMC once per second. | 每秒只会计算一次EMC的产生。<br>🔽<br>每秒产生一次EMC。 |
|  `block.projectexpansion.collector.emc` |Produced EMC: %s/s | EMC产生速度：%s/s<br>🔽<br>EMC生产速度：%s/s |
|  `block.projectexpansion.dark_collector` |Dark Collector [MK 2] | 黑物质收集器[2型]<br>🔽<br>黑暗收集器[2型] |
|  `block.projectexpansion.red_collector` |Red Collector [MK 3] | 红物质收集器[3型]<br>🔽<br>红色收集器[3型] |
|  `block.projectexpansion.magenta_collector` |Magenta Collector [MK 4] | 品红物质收集器[4型]<br>🔽<br>品红色收集器[4型] |
|  `block.projectexpansion.pink_collector` |Pink Collector [MK 5] | 粉红物质收集器[5型]<br>🔽<br>粉红色收集器[5型] |
|  `block.projectexpansion.purple_collector` |Purple Collector [MK 6] | 紫物质收集器[6型]<br>🔽<br>紫色收集器[6型] |
|  `block.projectexpansion.violet_collector` |Violet Collector [MK 7] | 紫罗兰物质收集器[7型]<br>🔽<br>蓝紫色收集器[7型] |
|  `block.projectexpansion.blue_collector` |Blue Collector [MK 8] | 蓝物质收集器[8型]<br>🔽<br>蓝色收集器[8型] |
|  `block.projectexpansion.cyan_collector` |Cyan Collector [MK 9] | 青物质收集器[9型]<br>🔽<br>青色收集器[9型] |
|  `block.projectexpansion.green_collector` |Green Collector [MK 10] | 绿物质收集器[10型]<br>🔽<br>绿色收集器[10型] |
|  `block.projectexpansion.lime_collector` |Lime Collector [MK 11] | 黄绿物质收集器[11型]<br>🔽<br>黄绿色收集器[11型] |
|  `block.projectexpansion.yellow_collector` |Yellow Collector [MK 12] | 黄物质收集器[12型]<br>🔽<br>黄色收集器[12型] |
|  `block.projectexpansion.orange_collector` |Orange Collector [MK 13] | 橙物质收集器[13型]<br>🔽<br>橙色收集器[13型] |
|  `block.projectexpansion.white_collector` |White Collector [MK 14] | 白物质收集器[14型]<br>🔽<br>白色收集器[14型] |
|  `block.projectexpansion.fading_collector` |Fading Collector [MK 15] | 渐消物质收集器[15型]<br>🔽<br>渐消收集器[15型] |
|  `block.projectexpansion.final_collector` |Final Collector [MK 16] | 终极能量收集器[16型]<br>🔽<br>终极收集器[16型] |
|  `block.projectexpansion.emc_link.tooltip` |Can be used to import emc & items, and export items & fluids. | 与基础能量EMC接口相似，并能存入和取出物品。<br>🔽<br>可用于输入EMC或物品，并输出物品和流体。 |
|  `block.projectexpansion.emc_link.limit_items` |Item Import/Export Limit: %s/s | 输入/输出上限：%s/s<br>🔽<br>物品输入/输出限制：%s/s |
|  `block.projectexpansion.emc_link.limit_fluids` |Fluid Export Limit: %s mB/s | 流体输出上限：%smB/秒<br>🔽<br>流体输出限制：%smB/s |
|  `block.projectexpansion.emc_link.fluid_export_efficiency` |Fluid Export Efficiency: %s | 流体输出效率%s<br>🔽<br>流体输出效率：%s |
|  `block.projectexpansion.emc_link.limit_emc` |EMC Limit: %s/s | EMC上限：%s/秒<br>🔽<br>EMC限制：%s/s |
|  `block.projectexpansion.emc_link.not_set` |An export item has not been set. | 没有设置输出物品。<br>🔽<br>输出物品未设置。 |
|  `block.projectexpansion.emc_link.empty_hand` |Empty your hand to retrieve items. | 空手取出物品。<br>🔽<br>用空手来取回物品。 |
|  `block.projectexpansion.emc_link.cleared` |Export item has been cleared. | 输出物品已清除。<br>🔽<br>输出物品已被清除 |
|  `block.projectexpansion.emc_link.not_enough_emc` |You do not have enough emc to purchase this, you need %s. | 您没有足够的EMC，您需要%s。<br>🔽<br>你的EMC不足以购买这个，你仍需%s。 |
|  `block.projectexpansion.emc_link.set` |Export item has been set to %s. | 输出物品已设置为%s。<br>🔽<br>输出物品已被设置为%s。 |
|  `block.projectexpansion.emc_link.no_emc_value` |%s does not have an emc value. | %s没有EMC值。<br>🔽<br>%s没有EMC |
|  `block.projectexpansion.emc_link.no_export_remaining` |Export limit has been reached, please wait a second. | 已达到输出上限，请稍候。<br>🔽<br>输出物品速度已达上限，请稍等。 |
|  `block.projectexpansion.basic_emc_link` |Basic EMC Link [MK 1] | 基础EMC接口[1型]<br>🔽<br>基础EMC链接器[1型] |
|  `block.projectexpansion.dark_emc_link` |Dark EMC Link [MK 2] | 黑物质EMC接口[2型]<br>🔽<br>黑暗EMC链接器[2型] |
|  `block.projectexpansion.red_emc_link` |Red EMC Link [MK 3] | 红物质EMC接口[3型]<br>🔽<br>红色EMC链接器[3型] |
|  `block.projectexpansion.magenta_emc_link` |Magenta EMC Link [MK 4] | 品红物质EMC接口[4型]<br>🔽<br>品红色EMC链接器[4型] |
|  `block.projectexpansion.pink_emc_link` |Pink EMC Link [MK 5] | 粉红物质EMC接口[5型]<br>🔽<br>粉红色EMC链接器[5型] |
|  `block.projectexpansion.purple_emc_link` |Purple EMC Link [MK 6] | 紫物质EMC接口[6型]<br>🔽<br>紫色EMC链接器[6型] |
|  `block.projectexpansion.violet_emc_link` |Violet EMC Link [MK 7] | 紫罗兰物质EMC接口[7型]<br>🔽<br>蓝紫色EMC链接器[7型] |
|  `block.projectexpansion.blue_emc_link` |Blue EMC Link [MK 8] | 蓝物质EMC接口[8型]<br>🔽<br>蓝色EMC链接器[8型] |
|  `block.projectexpansion.cyan_emc_link` |Cyan EMC Link [MK 9] | 青物质EMC接口[9型]<br>🔽<br>青色EMC链接器[9型] |
|  `block.projectexpansion.green_emc_link` |Green EMC Link [MK 10] | 绿物质EMC接口[10型]<br>🔽<br>绿色EMC链接器[10型] |
|  `block.projectexpansion.lime_emc_link` |Lime EMC Link [MK 11] | 黄绿物质EMC接口[11型]<br>🔽<br>黄绿色EMC链接器[11型] |
|  `block.projectexpansion.yellow_emc_link` |Yellow EMC Link [MK 12] | 黄物质EMC接口[12型]<br>🔽<br>黄色EMC链接器[12型] |
|  `block.projectexpansion.orange_emc_link` |Orange EMC Link [MK 13] | 橙物质EMC接口[13型]<br>🔽<br>橙色EMC链接器[13型] |
|  `block.projectexpansion.white_emc_link` |White EMC Link [MK 14] | 白物质EMC接口[14型]<br>🔽<br>白色EMC链接器[14型] |
|  `block.projectexpansion.fading_emc_link` |Fading EMC Link [MK 15] | 渐消物质EMC接口[15型]<br>🔽<br>渐消EMC链接器[15型] |
|  `block.projectexpansion.final_emc_link` |Final EMC Link [MK 16] | 终极EMC接口[16型]<br>🔽<br>终极EMC链接器[16型] |
|  `block.projectexpansion.magenta_fuel_block` |Magenta Fuel Block | 品红燃料块<br>🔽<br>品红色燃料块 |
|  `block.projectexpansion.pink_fuel_block` |Pink Fuel Block | 粉红燃料块<br>🔽<br>粉红色燃料块 |
|  `block.projectexpansion.purple_fuel_block` |Purple Fuel Block | 紫燃料块<br>🔽<br>紫色燃料块 |
|  `block.projectexpansion.violet_fuel_block` |Violet Fuel Block | 紫罗兰燃料块<br>🔽<br>蓝紫色燃料块 |
|  `block.projectexpansion.blue_fuel_block` |Blue Fuel Block | 蓝燃料块<br>🔽<br>蓝色燃料块 |
|  `block.projectexpansion.cyan_fuel_block` |Cyan Fuel Block | 青燃料块<br>🔽<br>青色燃料块 |
|  `block.projectexpansion.green_fuel_block` |Green Fuel Block | 绿燃料块<br>🔽<br>绿色燃料块 |
|  `block.projectexpansion.lime_fuel_block` |Lime Fuel Block | 黄绿燃料块<br>🔽<br>黄绿色燃料块 |
|  `block.projectexpansion.yellow_fuel_block` |Yellow Fuel Block | 黄燃料块<br>🔽<br>黄色燃料块 |
|  `block.projectexpansion.orange_fuel_block` |Orange Fuel Block | 橙燃料块<br>🔽<br>橙色燃料块 |
|  `block.projectexpansion.white_fuel_block` |White Fuel Block | 白燃料块<br>🔽<br>白色燃料块 |
|  `block.projectexpansion.arcane_table` |Arcane Table | 炼金术接口<br>🔽<br>奥术桌 |
|  `block.projectexpansion.transmutation_interface` |Transmutation Interface | 交换接口<br>🔽<br>转化接口 |
|  `block.projectexpansion.transmutation_interface.tooltip` |This can be used with compatible mods like Applied Energistics to access your transmutation inventory. | 可以通过AE、RS等模组的存储总线将归属者的转化桌与合成网络交互（包括使用终端或自动合成），通过消耗所有者的EMC取出物品或将放入物品转化为所有者的EMC，可以同时学习进入接口的新物品。右键点击可以显示所有者。<br>🔽<br>你可以将它接入与之兼容的模组（如应用能源2），便可从中等价获取已学习的物品。 |
|  `block.projectexpansion.power_flower.tooltip` |Generates EMC once per %s tick%s. (20/second) | 每%s游戏刻%s生成一次EMC。（20/秒）<br>🔽<br>每%stick产生一次EMC。（20tick/秒） |
|  `block.projectexpansion.power_flower.emc` |Produced [...]

2023-11-25 14:35 UTC, eciv-oN commented
我去 那直接等update了 开摆（

2023-11-25 14:35 UTC, closed without merging