Mystical Agriculture 翻译修正
CFPAOrg/Minecraft-Mod-Language-Package pull request #3792
Opened 2023-09-23 09:12 UTC by ChuijkYahus

2023-09-23 14:29 UTC, DrIceTea123 requested changes
我是觉得1.12的这几行和1.16+的这几行虽然是同一个东西，但是原文不同，1.12原文是没有Ingot字样的，所以是否1.12也一起修改有待商议
别的地方没啥问题了

2023-09-23 14:33 UTC, ChuijkYahus commented
1.12修改是因为还有一个直接用精华合成的块把`精华块`这个名字占了
必须加`锭`才能区分，详情见群上周日的聊天记录（）

2023-10-28 14:13 UTC, Cactusstudent reviewed
这个是老问题了，命名问题有点难解决，我个人赞同新译法，要不就一个PR把涉及到的全改了？

2023-10-28 16:20 UTC, ChuijkYahus commented
也行，不过不保证能改全

2023-11-04 12:09 UTC, ChuijkYahus commented
之后有需要新开pr吧还是

2024-03-16 07:42 UTC, 502y approved these changes

2025-01-16 17:38 UTC, mamaruo commented
意见？关闭？合并？

2025-01-17 02:35 UTC, ChuijkYahus commented
晚上来处理

2025-01-19 19:06 UTC, mamaruo approved these changes

2025-01-31 10:53 UTC, merged