提交Decoration Delight: Refurbished [装饰乐事] 中文翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #3793
Opened 2023-09-23 13:32 UTC by sfgd147

2023-09-23 14:00 UTC, ChuijkYahus commented
/sort-keys projects/1.18/assets/decoration-delight/decoration_delight/lang/en_us.json
/sort-keys projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json

2023-09-23 14:06 UTC, ChuijkYahus commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "advancements.decoration_101_advancement.descr": "欢迎来到装饰乐事!",
```suggestion
  "advancements.checkmate_advancement.title": "将军！",
  "advancements.decoration_101_advancement.descr": "欢迎来到装饰乐事！",
```

2023-09-23 14:06 UTC, ChuijkYahus commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "advancements.sink_advancement.descr": "使用洗碗槽.",
```suggestion
  "advancements.sink_advancement.descr": "使用洗碗槽",
```

2023-09-23 14:06 UTC, ChuijkYahus commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "block.decoration_delight.acacia_mosaic": "金合欢马赛克",
```suggestion
  "block.decoration_delight.acacia_mosaic": "金合欢木马赛克",
```
建议这样

2023-09-23 14:06 UTC, ChuijkYahus commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "block.decoration_delight.andesite_tiles": "安山岩瓷砖",
```suggestion
  "block.decoration_delight.andesite_tiles": "安山岩瓦",
```
见原版`深板岩瓦`/`Deepslate Tiles`

2023-09-23 14:06 UTC, ChuijkYahus commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "block.decoration_delight.birch_stool": "桦木凳",
```suggestion
  "block.decoration_delight.birch_counter": "白桦木柜台",
  "block.decoration_delight.birch_counter_bend": "白桦木柜台转角",
  "block.decoration_delight.birch_counter_corner": "白桦木柜台角落",
  "block.decoration_delight.birch_countertop": "白桦木台面",
  "block.decoration_delight.birch_mosaic": "白桦木马赛克",
  "block.decoration_delight.birch_stool": "白桦木凳",
```
见原版birch翻译

2023-09-23 14:06 UTC, ChuijkYahus commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "block.decoration_delight.granite_tiles": "花岗岩瓷砖",
```suggestion
  "block.decoration_delight.diorite_tiles": "闪长岩瓦",
  "block.decoration_delight.granite_tiles": "花岗岩瓦",
```

2023-09-23 14:06 UTC, ChuijkYahus commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "block.decoration_delight.quartz_and_blackstone_tiles": "黑白瓷砖",
```suggestion
  "block.decoration_delight.quartz_and_blackstone_tiles": "石英黑石瓦",
```

2023-09-23 14:06 UTC, ChuijkYahus commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "block.decoration_delight.stone_tiles": "石头瓷砖",
```suggestion
  "block.decoration_delight.stone_tiles": "石头瓦",
```

2023-09-23 14:06 UTC, ChuijkYahus commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "block.decoration_delight.warped_mosaic": "诡异马赛克",
```suggestion
  "block.decoration_delight.warped_mosaic": "诡异木马赛克",
```

2023-09-23 14:06 UTC, ChuijkYahus commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "entity.decoration_delight.stool_entity": "凳子",
可以把上方的所有`xx凳`全部改为`xx凳子`

2023-09-23 14:06 UTC, ChuijkYahus commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "gui.decoration_delight.cabinet_storage.label_inventory": "库存",
```suggestion
  "gui.decoration_delight.cabinet_storage.label_inventory": "物品栏",
```
需要游戏内测试

2023-09-23 14:06 UTC, ChuijkYahus commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "item.decoration_delight.cookin_disc.desc": "烹饪之声",
```suggestion
  "item.decoration_delight.cookin_disc.desc": "Morkovka - cookin",
```
唱片曲目不翻译

2023-09-23 14:18 UTC, DrIceTea123 requested changes
整个看了一遍

2023-09-23 14:18 UTC, DrIceTea123 commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "block.decoration_delight.quartz_and_blackstone_tiles": "黑白瓷砖",
所以为啥`Quartz and Blackstone Tile`翻译成`黑白瓷砖`

2023-09-23 14:18 UTC, DrIceTea123 commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "advancements.sink_advancement.descr": "使用洗碗槽.",
有个不应该有的点

2023-09-23 14:18 UTC, DrIceTea123 commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "advancements.sink_advancement.title": "水花四溅",
原文：`Splish Splash`，是歌名
所以翻译的话可以直接本地化成`嘻唰唰`？

2023-09-23 14:18 UTC, DrIceTea123 commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "advancements.trash_bin_advancement.title": "果皮啊，垃圾啊，一定要丢进垃圾桶里面",
原文：`Bin There, Done That`
`Been There, Done That`也是歌名，同时也是英文俗语，大概是指经历的事多了而司空见惯的意思
这里可能要考虑一下怎么翻译比较合适

2023-09-23 14:18 UTC, DrIceTea123 commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "block.decoration_delight.birch_stool": "桦木凳",
Birch -> 白桦木，标准译名

2023-09-23 14:18 UTC, DrIceTea123 commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "block.decoration_delight.warped_mosaic": "诡异马赛克",
```suggestion
  "block.decoration_delight.warped_mosaic": "诡异木马赛克",
```

2023-09-23 14:18 UTC, DrIceTea123 commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "gui.decoration_delight.cabinet_storage.label_inventory": "库存",
`Inventory`在这里怎么处理好一点
```suggestion
  "gui.decoration_delight.cabinet_storage.label_inventory": "物品栏",
```

2023-09-23 14:18 UTC, DrIceTea123 commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "item.decoration_delight.cookin_disc.desc": "烹饪之声",
原文：`Morkovka - cookin`
音乐唱片的音乐信息无需翻译

2023-09-23 14:20 UTC, sfgd147 commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "block.decoration_delight.quartz_and_blackstone_tiles": "黑白瓷砖",
因为是厨房用的棋盘地砖，成就也是捏他国际象棋的棋盘

2023-09-23 14:21 UTC, sfgd147 commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "advancements.trash_bin_advancement.title": "果皮啊，垃圾啊，一定要丢进垃圾桶里面",
这个是作者那边本来就有的翻译，也没想好怎么改

2023-09-23 14:21 UTC, sfgd147 commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "block.decoration_delight.birch_stool": "桦木凳",
OK

2023-09-23 14:22 UTC, sfgd147 commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "gui.decoration_delight.cabinet_storage.label_inventory": "库存",
游戏内用于gui的玩家背包一栏，确实是物品栏合适

2023-09-23 14:24 UTC, sfgd147 commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "block.decoration_delight.andesite_tiles": "安山岩瓷砖",
用于厨房地板的装饰方块，此处用瓷砖可能更合适

2023-09-23 17:34 UTC, ChuijkYahus commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "entity.decoration_delight.stool_entity": "凳子",
实体和物品名统一
请注意将`凳`和`凳子`统一

2023-09-23 17:34 UTC, ChuijkYahus commented on projects/1.18/assets/decoration-delight/decoration_delight/lang/zh_cn.json
> +  "block.decoration_delight.quartz_and_blackstone_tiles": "黑白瓷砖",
建议材料名保留，依照原文

2023-09-23 18:37 UTC, sfgd147 commented
修改了bin there, done that的原翻译，XX凳统一改为XX凳子，Quartz and Blackstone Tile改为石英黑石瓷砖，Splish Splash改为嘻唰唰

2023-09-23 19:06 UTC, ChuijkYahus approved these changes

2023-09-24 05:22 UTC, DrIceTea123 approved these changes

2023-09-24 15:46 UTC, merged