更新 Italian delights [意大利乐事] 中文翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #3794
Opened 2023-09-23 20:18 UTC by sfgd147

2023-09-24 05:10 UTC, ChuijkYahus commented
Decoration Delights重复提交，请注意删除

2023-09-24 05:18 UTC, ChuijkYahus commented on projects/1.18/assets/italian-delights-add-on-for-farmers-delight/italian_delight/lang/zh_cn.json
> +"advancements.awkward.descr": "喝下一杯未完成的'拙'酒",
```suggestion
  "advancements.awkward.descr": "喝下一杯未完成的“拙”酒",
```
全角引号

2023-09-24 05:18 UTC, ChuijkYahus commented on projects/1.18/assets/italian-delights-add-on-for-farmers-delight/italian_delight/lang/zh_cn.json
> +  "advancements.awkward.title": "等等...这太尴尬了",
```suggestion
  "advancements.awkward.title": "等等……这太尴尬了",
```
中文省略号，`Shift`+`6`

2023-09-24 05:18 UTC, ChuijkYahus commented on projects/1.18/assets/italian-delights-add-on-for-farmers-delight/italian_delight/lang/zh_cn.json
> +  "advancements.xmas_achivment.descr": "制作一份潘多酪！",
```suggestion
  "advancements.xmas_achivment.descr": "制作一份潘多洛！",
```
貌似找到的一般是这么音译的
本身是个面板，用`酪`总感觉怪怪的

2023-09-24 05:18 UTC, ChuijkYahus commented on projects/1.18/assets/italian-delights-add-on-for-farmers-delight/italian_delight/lang/zh_cn.json
> +  "block.italian_delight.pandoro_block": "潘多酪",
```suggestion
  "block.italian_delight.pandoro_block": "潘多洛",
```
统一

2023-09-24 05:18 UTC, ChuijkYahus commented on projects/1.18/assets/italian-delights-add-on-for-farmers-delight/italian_delight/lang/zh_cn.json
> +  "item.italian_delight.iron_pizza_peel": "披萨铲",
```suggestion
  "item.italian_delight.iron_pizza_peel": "铁披萨铲",
```
遵照原文

2023-09-24 05:18 UTC, ChuijkYahus commented on projects/1.18/assets/italian-delights-add-on-for-farmers-delight/italian_delight/lang/zh_cn.json
> +  "item.italian_delight.prewine_substance": "'拙'酒",
```suggestion
  "item.italian_delight.prewine_substance": "“拙”酒",
```

2023-09-24 05:18 UTC, ChuijkYahus commented on projects/1.18/assets/italian-delights-add-on-for-farmers-delight/italian_delight/lang/zh_cn.json
> +  "item.italian_delight.salami_pieces": "切片萨拉米香肠",
```suggestion
  "item.italian_delight.salami_pieces": "萨拉米香肠切片",
```
虽然原文和农夫乐事系列的蛋糕切片不同（）

2023-09-24 05:18 UTC, ChuijkYahus commented on projects/1.18/assets/italian-delights-add-on-for-farmers-delight/italian_delight/lang/zh_cn.json
> +  "item.italian_delight.pandoro": "潘多酪",
```suggestion
  "item.italian_delight.pandoro_dough": "潘多洛面团",
  "item.italian_delight.pandoro_slice": "潘多洛切片",
  "item.italian_delight.pandoro": "潘多洛",
```

2023-09-24 06:47 UTC, sfgd147 commented
> 装饰乐趣重复提交，请注意删除
不太懂这块要怎么操作，可以说明一下吗

2023-09-24 07:45 UTC, ChuijkYahus commented
一般是删除文件即可
如果main分支内已经有对应文件，则需将文件恢复至main分支版本

~~或者使用git魔法~~

2023-09-24 07:54 UTC, ChuijkYahus commented on projects/1.18/assets/italian-delights-add-on-for-farmers-delight/italian_delight/lang/zh_cn.json
> +  "item.italian_delight.berrieddelight": "莓葬光明",
查了一下，貌似是一种草莓蛋糕之类的东西
不知道`莓藏之喜`怎么样（）

2023-09-27 12:57 UTC, luoxueyasha requested changes
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/9d035059-1f5f-4df9-a3c4-c25e82eaefc1)
If you want it, then you'll have to fix it……

2023-09-27 12:57 UTC, luoxueyasha commented on projects/1.18/assets/italian-delights-add-on-for-farmers-delight/italian_delight/lang/zh_cn.json
> +  "block.italian_delight.dantes_special_block": "但丁特制披萨",
原文带`Block`（方块），可以适当考虑一下要不要都译出来
（不译应该也可以？）

2023-09-28 22:23 UTC, luoxueyasha approved these changes
我觉得应该没事了

2023-09-29 08:19 UTC, ChuijkYahus approved these changes

2023-09-30 04:14 UTC, merged