Physics Mod 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3833
Opened 2023-10-07 10:33 UTC by ItIsNotAPlayer

fabric 的把 Mod Menu 中显示的 description 也翻译了

2023-10-22 07:22 UTC, ItIsNotAPlayer commented
怎么没人来审我的捏😢

2023-11-21 14:36 UTC, ItIsNotAPlayer commented
个人认为已经没有需要改的了

2023-11-23 19:40 UTC, ItIsNotAPlayer commented
个人觉得没有再要改的了，不知道空格有没有影响

2023-11-25 16:28 UTC, ChuijkYahus requested changes
fabric为何多出两个键

2023-11-25 16:28 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.gui.back": "返 回",
```suggestion
	"physicsmod.gui.back": "返回",
```

2023-11-25 16:28 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.gui.search": "搜索…",
```suggestion
	"physicsmod.gui.search": "搜索……",
```
中文使用六点省略号，请注意修改

2023-11-25 16:28 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.menu.physics.ocean.error": "海洋物理与Immersive Portals和Farsight不兼容。请使用Iris + Sodium (Fabric)或Oculus + Rubidium (Forge)代替。",
```suggestion
	"physicsmod.menu.physics.ocean.error": "海洋物理与Immersive Portals和Farsight不兼容。请使用Iris + Sodium（Fabric）或Oculus + Rubidium（Forge）代替。",
```

2023-11-25 16:28 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.menu.physics.snow.error": "雪物理与Immersive Portals和Farsight不兼容。请使用Iris + Sodium (Fabric)或Oculus + Rubidium (Forge)代替。",
```suggestion
	"physicsmod.menu.physics.collapse.error": "你只能在服务器配置中更改崩塌设置，除非是单人游戏（config/physicsmod/physics_server_config.json）。",
	"physicsmod.menu.physics.snow.error": "雪物理与Immersive Portals和Farsight不兼容。请使用Iris + Sodium（Fabric）或Oculus + Rubidium（Forge）代替。",
```

2023-11-25 16:28 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.menu.main.support": "支 持 模 组 开 发",
```suggestion
	"physicsmod.menu.main.update": "更新",
	"physicsmod.menu.main.support": "支持模组开发",
```

2023-11-25 16:28 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.menu.gravity.buoyancyz": "浮力 Z",
```suggestion
	"physicsmod.menu.gravity.gravityx": "重力X",
	"physicsmod.menu.gravity.gravityy": "重力Y",
	"physicsmod.menu.gravity.gravityz": "重力Z",
	"physicsmod.menu.gravity.buoyancyx": "浮力X",
	"physicsmod.menu.gravity.buoyancyy": "浮力Y",
	"physicsmod.menu.gravity.buoyancyz": "浮力Z",
```

2023-11-25 16:28 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.menu.general.title.main": "通 用",
```suggestion
	"physicsmod.menu.general.title.main": "通用",
```
全文删除此类空格

2023-11-25 16:28 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.menu.liquid.warning": "这是液体物理的测试版本，所以你可以多多尝试和测试他们。要生成无限液体源头，破坏一个附魔台（你可以通过在源头上放置一个方块来停止水流，一切都只发生在客户端）。可以生成有限液体源头的方块：西瓜、湿海绵、南瓜、仙人掌、装水的炼药锅。",
```suggestion
	"physicsmod.menu.liquid.warning": "这是液体物理的测试版本，所以你可以多多尝试和测试他们。要生成无限液体源头，破坏一个附魔台（你可以通过在源头上放置一个方块来停止水流，一切都只发生在客户端）。可以生成有限液体源头的方块：西瓜、湿海绵、南瓜、仙人掌、装有水的炼药锅。",
```

2023-11-25 16:28 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.prop.particle.velocityz": "矢量速度 Z",
```suggestion
	"physicsmod.prop.particle.velocityx": "矢量速度X",
	"physicsmod.prop.particle.velocityy": "矢量速度Y",
	"physicsmod.prop.particle.velocityz": "矢量速度Z",
```

2023-11-26 06:26 UTC, ItIsNotAPlayer commented
> fabric为何多出两个键

Fabric上装了Mod Menu后，会在模组详情页显示`fabric.mod.json`中的`"description"`，可以通过语言文件修改，我把这个也翻译了

2023-11-29 14:44 UTC, ItIsNotAPlayer commented
可惜这几个空格是删不掉的
<img width="629" alt="唉" src="https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/102716584/3b648e13-ce59-4813-80d7-a2dacd304199">

2023-11-29 14:46 UTC, ChuijkYahus commented
> 可惜这几个空格是删不掉的 <img alt="唉" width="629" src="https://private-user-images.githubusercontent.com/102716584/286632661-3b648e13-ce59-4813-80d7-a2dacd304199.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjk0MTksIm5iZiI6MTcwMTI2OTExOSwicGF0aCI6Ii8xMDI3MTY1ODQvMjg2NjMyNjYxLTNiNjQ4ZTEzLWNlNTktNDgxMy04MGQ3LWEyZGFjZDMwNDE5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOVQxNDQ1MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjcxZjk2MTFiYmIxMjcyMTJkN2VjYzcyNWY5M2M2M2YyYjdkYmM2NWZiZTI5NTZiNWRiNzY2YTZkOTU0ZTdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jEGAZEyvpln5LUcRKlFJGlm6wQ1YMmKPa4N8hFrwm8U">

这也是删空格的原因，MC本体在非强制Unicode时会自动在半角字符和全角字符之间加上空格

2023-11-29 14:47 UTC, ChuijkYahus commented
> 可惜这几个空格是删不掉的 <img alt="唉" width="629" src="https://private-user-images.githubusercontent.com/102716584/286632661-3b648e13-ce59-4813-80d7-a2dacd304199.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjk0MTksIm5iZiI6MTcwMTI2OTExOSwicGF0aCI6Ii8xMDI3MTY1ODQvMjg2NjMyNjYxLTNiNjQ4ZTEzLWNlNTktNDgxMy04MGQ3LWEyZGFjZDMwNDE5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOVQxNDQ1MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjcxZjk2MTFiYmIxMjcyMTJkN2VjYzcyNWY5M2M2M2YyYjdkYmM2NWZiZTI5NTZiNWRiNzY2YTZkOTU0ZTdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jEGAZEyvpln5LUcRKlFJGlm6wQ1YMmKPa4N8hFrwm8U">

这也是删空格的原因，MC本体在非强制Unicode时会自动在半角字符和全角字符之间加上空格
从1.13及以上版本开始就没有加空格的必要了，如果投的是这边则会要求删去文件中的空格，具体参见[CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)

2023-12-02 03:57 UTC, ChuijkYahus requested changes
其余应该没什么问题了

2023-12-02 03:57 UTC, ChuijkYahus commented on projects/1.20/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.menu.main.title": "物理设置…",
```suggestion
	"physicsmod.menu.main.title": "物理设置……",
```

2023-12-02 03:57 UTC, ChuijkYahus commented on projects/1.20/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.menu.block.blockphysicsrange.info": "描述距离玩家多远（以方块为单位）应该停止激活方块物理。",
```suggestion
	"physicsmod.menu.block.blockphysicsrange.info": "描述距离玩家多远（以格为单位）应该停止激活方块物理。",
```
注意全文修改

2023-12-02 03:57 UTC, ChuijkYahus commented on projects/1.20/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.menu.ocean.weather.thunder": "雷雨",
```suggestion
	"physicsmod.menu.ocean.weather.thunder": "雷暴",
```
换用mcwiki名称（）

2023-12-02 03:57 UTC, ChuijkYahus commented on projects/1.20/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.menu.cloth.downloading.title": "下载布料…",
```suggestion
	"physicsmod.menu.cloth.downloading.title": "下载布料……",
```

2023-12-02 03:57 UTC, ChuijkYahus commented on projects/1.20/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.menu.weather.rainstrength.info": "总风力强度的计算方法如下：晴朗天气强度 + 降雨天气强度（雨天/雷雨时）+ 雷暴天气强度（雷雨时）",
```suggestion
	"physicsmod.menu.weather.rainstrength.info": "总风力强度的计算方法如下：晴天天气强度 + 降雨天气强度（雨天/雷雨时）+ 雷暴天气强度（雷雨时）",
```

2023-12-02 03:57 UTC, ChuijkYahus commented on projects/1.20/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.menu.ocean.weather.rain": "雨天",
```suggestion
	"physicsmod.menu.ocean.weather.rain": "降雨",
```

2023-12-02 03:57 UTC, ChuijkYahus commented on projects/1.20/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.prop.particle.velocityz": "矢量速度Z",
这个可以改成`速度`吗

2023-12-02 03:57 UTC, ChuijkYahus commented on projects/1.20/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.menu.weather.clearstrength": "晴朗天气",
```suggestion
	"physicsmod.menu.weather.clearstrength": "晴天天气",
```

2023-12-02 03:57 UTC, ChuijkYahus commented on projects/1.20/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.menu.weather.particlesamountthunder.info": "每个露天方块生成X数量额外的雨滴粒子。这对性能有很大的影响。",
```suggestion
	"physicsmod.menu.weather.particlesamountthunder.info": "每个露天方块生成X个额外的雨滴粒子。这对性能有很大的影响。",
```

2023-12-02 06:59 UTC, ItIsNotAPlayer commented on projects/1.20/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.menu.main.title": "物理设置…",
这里要改成“……”吗
<img width="330" alt="214" src="https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/102716584/e7e20a14-5285-4333-b604-7c8f21e094a1">
改完后看着有点奇怪，其他选项都只有一个“…”

2023-12-02 07:03 UTC, ItIsNotAPlayer commented on projects/1.20/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.menu.block.blockphysicsrange.info": "描述距离玩家多远（以方块为单位）应该停止激活方块物理。",
“（方块数）”是不是也要改成“（格）”

2023-12-02 07:05 UTC, ChuijkYahus commented on projects/1.20/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.menu.block.blockphysicsrange.info": "描述距离玩家多远（以方块为单位）应该停止激活方块物理。",
作为单位应该都需要

2023-12-02 07:08 UTC, ChuijkYahus commented on projects/1.20/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.menu.block.blockphysicsrange.info": "描述距离玩家多远（以方块为单位）应该停止激活方块物理。",
等下，应该是距离面积体积之类需要
如果形容的是一个一个方块本身就不需要

2023-12-02 07:16 UTC, ChuijkYahus commented on projects/1.20/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.menu.main.title": "物理设置…",
OK
那就统一三点，请全文通查

2023-12-02 07:29 UTC, ItIsNotAPlayer commented on projects/1.20/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.prop.particle.velocityz": "矢量速度Z",
感觉可以

2023-12-02 07:29 UTC, ItIsNotAPlayer commented on projects/1.20/assets/physics-mod/physicsmod/lang/zh_cn.json
> +	"physicsmod.menu.block.blockphysicsrange.info": "描述距离玩家多远（以方块为单位）应该停止激活方块物理。",
行

2023-12-02 12:50 UTC, ChuijkYahus approved these changes

2023-12-07 05:19 UTC, merged