Extra Utilities Reborn翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3851
Opened 2023-10-15 11:58 UTC by meishiffx

2023-10-20 08:05 UTC, ChuijkYahus commented
\sort-keys projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/en_us.json
\sort-keys projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json

2023-10-20 08:06 UTC, ChuijkYahus commented
/sort-keys projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/en_us.json
/sort-keys projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json

2023-10-20 08:17 UTC, ChuijkYahus commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.creative_spikes": "创造锥刺方块",
```suggestion
  "block.extrautilitiesrebirth.creative_spikes": "创造锥刺",
```
统一`锥刺`和`锥刺方块`

2023-10-20 08:17 UTC, ChuijkYahus commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.wood_spike": "木质锥刺",
```suggestion
  "block.extrautilitiesrebirth.wood_spike": "木锥刺",
```

2023-10-20 08:17 UTC, ChuijkYahus commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.ineffable_inverted_glass": "超凡玻璃(反向)",
```suggestion
  "block.extrautilitiesrebirth.ineffable_inverted_glass": "超凡玻璃（反向）",
```
请注意使用全角括号

2023-10-20 08:17 UTC, ChuijkYahus commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.fe_transmitter": "Fe传输器",
这个是传输能量的吗

2023-10-21 01:44 UTC, Cactusstudent requested changes
浅浅看了一下，问题不少

2023-10-21 01:44 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.fe_transmitter": "Fe传输器",
看起来是，FE保留就行

2023-10-21 01:44 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.ender_quarry_silk_touch_upgrade": "末影采石场精准升级",
`精准`可以考虑改成`精准采集`，推测译者是为了简短

2023-10-21 01:44 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.halitosis_generator": "龙息发电机",
```suggestion
  "block.extrautilitiesrebirth.halitosis_generator": "口臭发电机",
```
原文如此

2023-10-21 01:44 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.rainbow_generator": "彩虹发电机!",
```suggestion
  "block.extrautilitiesrebirth.rainbow_generator": "彩虹发电机！",
```

2023-10-21 01:44 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.rainbow_stone": "彩虹石",
```suggestion
  "block.extrautilitiesrebirth.rainbow_stone": "彩虹石头",
```

2023-10-21 01:44 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.redstone_clock_off": "红石钟(关)",
```suggestion
  "block.extrautilitiesrebirth.redstone_clock_off": "红石钟（关）",
```

2023-10-21 01:44 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.slimey_generator": "史莱姆发电机",
```suggestion
  "block.extrautilitiesrebirth.slimey_generator": "黏液发电机",
```
**待议**

2023-10-21 01:44 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.trash_can_energy": "垃圾桶 (能源)",
```suggestion
  "block.extrautilitiesrebirth.trash_can_energy": "垃圾桶（能源）",
```

2023-10-21 01:44 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.trash_can_fluid": "垃圾桶(流体)",
```suggestion
  "block.extrautilitiesrebirth.trash_can_fluid": "垃圾桶（流体）",
```

2023-10-21 01:44 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "itemGroup.tabtab": "更多实用设备 重生"
```suggestion
  "itemGroup.tabtab": "更多实用设备：重生"
```

2023-10-21 01:44 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "item.extrautilitiesrebirth.opinium_core_amazing": "Opinium核心(让人诧异的)",
```suggestion
  "item.extrautilitiesrebirth.opinium_core_amazing": "Opinium核心（让人诧异的）",
```

2023-10-21 01:44 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "item.extrautilitiesrebirth.super_speed_upgrade": "速度升级(极限)",
```suggestion
  "item.extrautilitiesrebirth.super_speed_upgrade": "速度升级（极限）",
```

2023-10-22 07:27 UTC, meishiffx reviewed
感谢各位dalao

2023-10-22 07:41 UTC, meishiffx commented
> 浅浅看了一下，问题不少

AWA

2023-10-22 07:48 UTC, Cactusstudent requested changes

2023-10-22 07:48 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.fe_transmitter": "Fe传输器",
```suggestion
  "block.extrautilitiesrebirth.fe_transmitter": "FE传输器",
```
这里是Forge Energy的缩写，均需大写

2023-10-22 07:48 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.creative_energy_storage": "创造模式能量源",
```suggestion
  "block.extrautilitiesrebirth.creative_energy_storage": "创造能源",
```
习惯性翻译，不过改不改均可

2023-10-22 07:48 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.creative_harvest": "创造模式收割者",
这个游戏内具体体现为什么

2023-10-22 07:48 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.double_compressed_cobblestone": "双重压缩圆石",
`二重`即可，统一性

2023-10-22 07:48 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.ender_core": "末影之核",
```suggestion
  "block.extrautilitiesrebirth.ender_core": "末影核心",
```

2023-10-22 07:48 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.ender_infused_obsidian": "末影黑曜石",
```suggestion
  "block.extrautilitiesrebirth.ender_infused_obsidian": "末影灌注黑曜石",
```

2023-10-22 07:48 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.gold_spike": "黄金锥刺",
```suggestion
  "block.extrautilitiesrebirth.gold_spike": "金锥刺",
```

2023-10-22 07:48 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.magical_wood": "魔法木头",
```suggestion
  "block.extrautilitiesrebirth.magical_wood": "魔法木",
```

2023-10-23 01:09 UTC, meishiffx commented
非常抱歉前面时间不是很宽裕，我尽量和Extra Utilities 2保持一致

2023-10-24 15:05 UTC, ChuijkYahus commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.trash_can_energy": "垃圾桶（能源）",
这个应该`能量`更合适？
不过其实改不改随便

2023-10-24 15:05 UTC, ChuijkYahus commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "item.extrautilitiesrebirth.erosion_shovel": "侵蚀之铲",
这个需要`铲`改成`锹`吗（）
看使用情况，个人感觉没有必要

2023-10-24 15:05 UTC, ChuijkYahus commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.wood_spike": "木锥刺",
同上，请注意各锥刺方块的格式统一

2023-10-25 09:13 UTC, ChuijkYahus requested changes

2023-10-25 09:13 UTC, ChuijkYahus commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.wood_spike": "木锥刺",
| 行号 | 英文名 | 中文译名 |
| ---- | ------ | -------- |
| 24 | Creative Spikes | 创造锥刺方块 |
| 32 | Diamond Spike | 钻石锥刺方块 |
| 72 | Gold Spike | 金锥刺 |
| 80 | Iron Spike | 铁锥刺方块 |
| 120 | Stone Spike | 石锥刺方块 |
| 131 | Wood Spike | 木锥刺 |

请注意统一各锥刺方块的格式，统一为`锥刺`或`锥刺方块`

2023-11-03 15:17 UTC, meishiffx commented
抱歉我错了。我尝试直接改动，导致两次工程叠在一起。我已经删除改动，但是英文文件还是被标记了（

2023-11-12 14:46 UTC, Cactusstudent requested changes
还是有些小问题，请注意：模组原先译文**可以**作为参考但**不是**唯一参考

2023-11-12 14:46 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.ender_thermic_pump": "末影熔岩泵",
原文：**Ender Thermic Pump** Thermic 显然不是 Lava

2023-11-12 14:46 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.ineffable_inverted_glass": "奇妙玻璃（反向）",
```suggestion
  "block.extrautilitiesrebirth.ineffable_inverted_glass": "反向奇妙玻璃",
```

2023-11-12 14:46 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.magma_generator": "熔岩发电机",
```suggestion
  "block.extrautilitiesrebirth.magma_generator": "岩浆发电机",
```

2023-11-12 14:46 UTC, Cactusstudent commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "item.extrautilitiesrebirth.super_speed_upgrade": "速度升级（极限）",
```suggestion
  "item.extrautilitiesrebirth.super_speed_upgrade": "极限速度升级",
```

2023-11-19 08:43 UTC, ChuijkYahus requested changes

2023-11-19 08:43 UTC, ChuijkYahus commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.chisled_stone_bricks": "雕刻石砖",
```suggestion
  "block.extrautilitiesrebirth.chisled_stone_bricks": "錾制石砖",
```

2023-11-19 08:43 UTC, ChuijkYahus commented on projects/1.18/assets/extra-utilities-reborn/extrautilitiesrebirth/lang/zh_cn.json
> +  "block.extrautilitiesrebirth.ender_thermic_pump": "末影熔岩泵",
请注意检验此问题

2023-12-03 04:04 UTC, ChuijkYahus commented
其余应该没有问题了

2023-12-03 06:02 UTC, ChuijkYahus approved these changes

2023-12-03 06:03 UTC, ChuijkYahus commented
后续若还有需提交的翻译，请注意新开分支并在该分支上进行修改

@meishiffx

2023-12-13 14:38 UTC, Cactusstudent approved these changes

2023-12-13 14:38 UTC, merged