Interstellar: Exoplanets 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #3859
Opened 2023-10-22 04:16 UTC by FuBangkun

2023-10-22 04:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3859) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3859) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3859) it.</sub>

2023-11-18 09:07 UTC, Don-Trueno commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +information.exoplanets:beta.1=§b目前的星际：系外行星版本是在早期测试！§r
星系：系外行星（或者直接用英文名）模组尚处于早期测试版本！

2023-11-18 09:11 UTC, Don-Trueno commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +tile.exoplanets.trap1e_dirt.name=(§a特拉比斯特-1 E§r) 污垢
确定是“污垢”，而不再是原版的“泥土”吗

2023-11-18 09:18 UTC, Don-Trueno commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +jei.exoplanets.desc.metal_furnace=矿石烧得更慢，燃料更多，但除了通常的铸锭外，还会产生灰尘。
也许能考虑一下：
需要更多燃料且矿石熔炼的速度减慢，但在原本矿物锭的基础上还会产生一些矿物粉。
Ores cook more slowly and with more fuel, but will produce dust in addition to the usual ingot.

2023-11-18 09:18 UTC, Don-Trueno commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +information.exoplanets:beta.1=§b目前的星际：系外行星版本是在早期测试！§r
同时接下来的段落也希望能用更通顺一些的表达

2023-11-18 09:23 UTC, FuBangkun commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +tile.exoplanets.trap1e_dirt.name=(§a特拉比斯特-1 E§r) 污垢
确实是泥土，上次提交(https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/2199)就写这个的，然后那个提交关闭了，这次就只把上次没处理的错误改了

2023-11-19 08:41 UTC, ChuijkYahus requested changes

2023-11-19 08:41 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +solarsystem.trappist1=特拉比斯特-1
这个貌似一般直接叫`Trappist-1`
不过都随便了

2023-11-19 08:41 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +information.dev.exoplanets:beta.1=§c通过继续，你同意如下条款：
```suggestion
information.dev.exoplanets:beta.1=§c继续意味着你同意如下条款：
```

2023-11-19 08:41 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +information.dev.exoplanets:beta.3=§c除非得到开发者的事先许可§r
```suggestion
information.dev.exoplanets:beta.2=§c除非得到开发者的事先许可，
information.dev.exoplanets:beta.3=§c你不得分发此开发版本§r
```
语序

2023-11-19 08:41 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +exoplanets.versions.outdated2=§6*§a最新更新v§9%s
```suggestion
exoplanets.versions.outdated2=§6*§a最新更新.........v§9%s
```
遵照原文格式

2023-11-19 08:41 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +exoplanets.versions.updateMessage=["Click To... [",{"text":"下载","color":"green","hoverEvent":{"action":"show_text","value":{"text":"单击此按钮可自动下载最新版本","color":"green"}},"clickEvent":{"action":"run_comma
```suggestion
exoplanets.versions.updateMessage=["点击以[",{"text":"下载","color":"green","hoverEvent":{"action":"show_text","value":{"text":"点击此按钮可自动下载最新版本","color":"green"}},"clickEvent":{"action":"run_command","value":"/download-latest-exoplanets %version%"}},"]"]
```

2023-11-19 08:41 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +exoplanets.versions.startingDownload=[{"text":"正在开始下载......请不要卸下硬盘。喜欢玩 ","color":"aqua"},{"text":"星际：系外行星？","color":"green"}]
```suggestion
exoplanets.versions.startingDownload=[{"text":"正在开始下载……请不要卸下硬盘。","color":"aqua"},{"text":"星际：系外行星","color":"green"},{"text":"还玩得开心吗？","color":"aqua"}]
```
中文省略号，语序微调

2023-11-19 08:41 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +exoplanets.versions.startingDownload2=[{"text":"考虑在","color":"aqua"},{"text":"Patreon","color":"gold","hoverEvent":{"action":"show_text","value":{"text":"点击此处进入ROMVoid95的Patreon","color":"light_purpl
```suggestion
exoplanets.versions.startingDownload2=[{"text":"请考虑在","color":"aqua"},{"text":"Patreon","color":"gold","hoverEvent":{"action":"show_text","value":{"text":"点击此处进入ROMVoid95的Patreon","color":"light_purple"}},"clickEvent":{"action":"open_url","value":"http://www.patreon.com/romvoid95"}},{"text":"上支持[","color":"aqua"},{"text":"ROMVoid95","color":"light_purple"},{"text":"！","color":"aqua"}]
```
微调

2023-11-19 08:41 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +exoplanets.versions.downloadedAlready=您已经下载最新版本。关闭游戏，在mods文件夹中删除旧版本，再启动游戏来更新！
```suggestion
exoplanets.versions.downloadedAlready=你已经下载最新版本。关闭游戏，在mods文件夹中删除旧版本，再启动游戏来更新！
```

2023-11-19 08:41 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +exoplanets.versions.downloadingAlready=更新文件已经在下载了，请给点时间，好吗？
```suggestion
exoplanets.versions.downloadingAlready=更新文件已经在下载了，请给点时间。
```
微调
不知道语气是否符合

2023-11-19 08:41 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +exoplanets.configgui.category.systier=太阳系系统等级要求
```suggestion
exoplanets.configgui.category.systier=太阳系等级要求
```

2023-11-19 08:41 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +itemGroup.items=§e星际：系外行星物品§r
```suggestion
itemGroup.decoration=§6星际：系外行星丨装饰品§r
itemGroup.terrain=§a星际：系外行星丨地形§r
itemGroup.items=§e星际：系外行星丨物品§r
```
模组名与各分栏名间使用`丨`（gun3）进行隔断

2023-11-19 08:41 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +## tile.exoplanets..name=星际：系外行星
这个已经是注释了，没必要补充，不过写上也没有太大问题，仍推荐与英文文件保持一致

2023-11-19 08:41 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +tile.exoplanets.yzb_loose_sediment.name=(§e鲸鱼座YZ B§r) 松散沉积物
```suggestion
tile.exoplanets.yzb_loose_sediment.name=（§e鲸鱼座YZ B§r）松散沉积物
```
所有括号均改为全角括号，请全文通查

2023-11-19 08:41 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +tile.exoplanets.lower_raidcontroller.name=下层RAID磁盘阵列控制器
```suggestion
tile.exoplanets.raidcluster.name=RAID 磁盘阵列群集
tile.exoplanets.raidcontroller.name=RAID 磁盘阵列控制器
tile.exoplanets.lower_raidcontroller.name=下层 RAID 磁盘阵列控制器
```
1.12.2中半角字母数字字符与全角字符之间需留有空格
建议星系名与全文通查

2023-11-19 08:41 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +tile.exoplanets.trap1e_cobblestone.name=(§a特拉比斯特-1 1E§r)
```suggestion
tile.exoplanets.trap1e_cobblestone.name=（§a特拉比斯特-1 E§r）
```
格式统一

2023-11-19 08:41 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +tile.exoplanets.trap1_dark_hot.name=§c火山冷却块
```suggestion
tile.exoplanets.trap1_dark_hot.name=§c火山冷却岩块
```
仅作方便理解考虑补充

2023-11-19 08:41 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +tile.exoplanets.roof_stairs.name=斜屋顶
```suggestion
tile.exoplanets.roof_stairs.name=倾斜屋顶
```
仅作术语统一考虑
不改也可

2023-11-19 08:41 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +tile.exoplanets.metal_lamp_lit.name=金属灯座
```suggestion
tile.exoplanets.metal_lamp_lit.name=金属块灯
```
上下统一

2023-11-19 08:41 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +item.exoplanets.sheeta2219.name=2219-铝合金板
```suggestion
item.exoplanets.sheeta2219.name=2219 铝合金板
```
建议统一为`2219 铝`，中间用空格隔断

2023-11-19 08:41 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +item.exoplanets.twopersonrocket.name=EXO1行星火箭
```suggestion
item.exoplanets.twopersonrocket.name=EXO1 行星火箭
```

2023-11-19 08:41 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +jei.exoplanets.desc.alloy_refinery=正在烧制
```suggestion
jei.exoplanets.desc.alloy_refinery=WIP
```
WIP=work in progress=未完成，一般不译

2023-11-19 08:41 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +jei.exoplanets.desc.metal_furnace=需要更多燃料且矿石熔炼的速度减慢，但在原本矿物锭的基础上还会产生一些矿物粉。
```suggestion
jei.exoplanets.desc.metal_furnace=需要更多燃料且矿石烧炼的速度减慢，但在原本矿物锭的基础上会额外产出一些矿物粉。
```

2023-11-19 14:47 UTC, ChuijkYahus requested changes
半角拉丁字母与数字和全角汉字之间需留有空格，请注意修改

2023-11-19 14:47 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +exoplanets.versions.outdated2=§6*§a最新更新……v§9%s
加载中和最新更新这两句在游戏内是怎么显示的，有无截图

2023-11-20 13:45 UTC, FuBangkun commented
![屏幕截图 2023-11-20 214006](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/109213800/ebbf82ec-f11a-4fee-b439-254e25b59d6b)
![屏幕截图 2023-11-20 214108](https://github.com
![屏幕截图 2023-11-20 214138](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/109213800/9cc1cdf5-f581-4f14-ad18-7bf6e065cd50)
/CFPAOrg/Minecraft-Mod-Language-Package/assets/109213800/c7257dd3-a1cf-4477-a313-bf7f6cd6467c)
![屏幕截图 2023-11-20 214117](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/109213800/5191bdc4-15d5-4e05-a721-2dababc85aff)
星系和星空的译名，都没有留空格，还有额外行星和更多行星等等附属也都没有留空格，为什么这个就不能不留空格

2023-11-20 15:16 UTC, ChuijkYahus commented
> ![屏幕截图 2023-11-20 214006](https://user-images.githubusercontent.com/109213800/284283331-ebbf82ec-f11a-4fee-b439-254e25b59d6b.png) ![屏幕截图 2023-11-20 214108](https://user-images.githubusercontent.com/109213800/284284168-c7257dd3-a1cf-4477-a313-bf7f6cd6467c.png) ![屏幕截图 2023-11-20 214138](https://user-images.githubusercontent.com/109213800/284284192-9cc1cdf5-f581-4f14-ad18-7bf6e065cd50.png) ![屏幕截图 2023-11-20 214117](https://user-images.githubusercontent.com/109213800/284284184-5191bdc4-15d5-4e05-a721-2dababc85aff.png) 星系和星空的译名，都没有留空格，还有额外行星和更多行星等等附属也都没有留空格，为什么这个就不能不留空格 @ChuijkYahus

有被兼容模组里的格式来源即可，遵照原模组

2023-11-20 15:17 UTC, ChuijkYahus commented on projects/1.12.2/assets/interstellar-exoplanets/exoplanets/lang/zh_cn.lang
> +exoplanets.versions.outdated2=§6*§a最新更新……v§9%s
这两句有无实际截图

2024-04-05 04:56 UTC, closed without merging