Bundled delight
CFPAOrg/Minecraft-Mod-Language-Package pull request #3864
Opened 2023-10-22 10:42 UTC by prossionalthief

2023-10-22 12:19 UTC, prossionalthief commented
en_us中没有模组包名不对应，在zh_cn中加上了

2023-10-23 01:05 UTC, Rinko1231 commented
不同的特殊杯子还是翻译一下吧。
查了一下有以下叫法
tankard：坦卡德杯
swig：随行杯，企鹅杯，蛋壳杯

2023-10-23 14:20 UTC, prossionalthief commented
明白了

2023-11-18 06:46 UTC, ChuijkYahus requested changes

2023-11-18 06:46 UTC, ChuijkYahus commented on projects/1.18/assets/bundled-delight/bundledelight/lang/zh_cn.json
> +  "brewinandchewin.tooltip.dread_nog_swig": "不祥之兆 (10:00)",
```suggestion
  "brewinandchewin.tooltip.dread_nog_glass": "不祥之兆（10:00）",
  "brewinandchewin.tooltip.dread_nog_swig": "不祥之兆（10:00）",
```

2023-11-18 06:46 UTC, ChuijkYahus commented on projects/1.18/assets/bundled-delight/bundledelight/lang/zh_cn.json
> +  "item.bundledelight.carrot_cake_slice": "胡萝卜蛋糕块",
```suggestion
  "item.bundledelight.carrot_cake_slice": "胡萝卜蛋糕切片",
```

2023-11-18 06:46 UTC, ChuijkYahus commented on projects/1.18/assets/bundled-delight/bundledelight/lang/zh_cn.json
> +  "item.bundledelight.white_strawberry_cake_slice": "白草莓蛋糕块",
```suggestion
  "item.bundledelight.white_strawberry_cake_slice": "白草莓蛋糕切片",
```

2023-11-25 16:18 UTC, ChuijkYahus commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@prossionalthief

2023-12-02 20:06 UTC, closed without merging