Entity Model Features 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3872
Opened 2023-10-28 06:48 UTC by Ginsway

2023-10-28 07:15 UTC, Ginsway commented
麻烦审核审完之后先让我将翻译复制到1.19，1.18再合并，谢谢

2023-11-19 08:18 UTC, ChuijkYahus requested changes
中英文行数不对应

2023-11-19 08:18 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/entity-model-features/entity_model_features/lang/zh_cn.json
> +	"entity_model_features.config.substitute_vanilla.tooltip": "EMF将尝试用原版文件替换 .jem\n 模型文件中缺失的部分",
```suggestion
	"entity_model_features.config.substitute_vanilla.tooltip": "EMF将尝试用原版文件替换.jem\n模型文件中缺失的部分",
```

2023-11-19 08:18 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/entity-model-features/entity_model_features/lang/zh_cn.json
> +	"entity_model_features.config.log_models.tooltip": "打印模型的创建调试数据到日志中",
```suggestion
	"entity_model_features.config.log_models.tooltip": "将模型的创建调试数据打印到日志中",
```
微调

2023-11-19 08:18 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/entity-model-features/entity_model_features/lang/zh_cn.json
> +	"entity_model_features.config.vanilla_render.tooltip": "尝试将原版模型与自定义模型一起渲染以进行比较\n它不会有动画，因此一些位置可能会有些奇怪。",
```suggestion
	"entity_model_features.config.vanilla_render.tooltip": "尝试将原版模型与自定义模型一起渲染以进行比较\n该模型不会有动画，因此它的位置与姿态可能会有些奇怪。",
```

2023-11-19 08:18 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/entity-model-features/entity_model_features/lang/zh_cn.json
> +	"entity_model_features.config.log_math.tooltip": "将动画计算调试数据打印到日志中\n警告：会导致极大的滞后！",
```suggestion
	"entity_model_features.config.log_math.tooltip": "将动画计算调试数据打印到日志中\n警告：会导致极大的卡顿！",
```

2023-11-19 08:18 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/entity-model-features/entity_model_features/lang/zh_cn.json
> +	"entity_model_features.config.force_models.tooltip": "将尝试并强制实体渲染器使用EMF设置的模型\n这可以覆盖其他模组更改的普通模型\n这不适用于所有模组",
```suggestion
	"entity_model_features.config.force_models.tooltip": "将尝试并强制实体渲染器使用EMF设置的模型\n会覆盖其他模组对原版模型的更改\n并非适用于所有模组",
```

2023-11-19 08:18 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/entity-model-features/entity_model_features/lang/zh_cn.json
> +	"entity_model_features.config.physics.tooltip": "如果启用物理模组，将只在死亡时渲染原版模型部件\n这部分是有效的，但不是完美的解决方案",
```suggestion
	"entity_model_features.config.physics.tooltip": "如果启用物理模组，将只在死亡时渲染原版模型部件\n基本能正常工作，但不是完美的解决方案",
```

2023-11-19 08:18 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/entity-model-features/entity_model_features/lang/zh_cn.json
> +	"entity_model_features.config.texture_override_mode.iris": "先试用Iris",
```suggestion
	"entity_model_features.config.texture_override_mode.iris": "尝试使用Iris",
```

2023-11-19 08:18 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/entity-model-features/entity_model_features/lang/zh_cn.json
> +	"entity_model_features.config.texture_override_mode.tooltip": "这控制EMF如何处理具有覆盖纹理集的渲染子模型例如，如果苦力怕模型的头部子模型具有单独的纹理\n有两种方法可以做到这一点，依靠我的代码，或者依靠Iris模组的一个怪癖\n我的代码“有效”，但我不是渲染缓冲区的专家，这可能会导致问题\nIris怪癖使用了一种非常简单且看似
```suggestion
	"entity_model_features.config.texture_override_mode.tooltip": "控制EMF如何处理具有覆盖纹理集的渲染子模型\n例如，如果苦力怕模型的头部子模型具有单独的纹理，应如何处理\n有两种方法可以做到这一点，依靠我的代码，或者依靠Iris模组的某种奇妙的特性\n我的代码“有效”，但我不是渲染缓冲区的专家，可能会导致问题\nIris的奇妙特性使用了一种非常简单且看似安全而稳定的方法，但我被告知这并非Iris的本意\n如果未安装Iris，Iris选项将默认为EMF代码\n除了调试子模型中的纹理重写外，此选项推荐保持默认状态",
```

2023-11-19 08:18 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/entity-model-features/entity_model_features/lang/zh_cn.json
> +	"entity_model_features.config.render.tooltip": "更改自定义模型部件的渲染方式，这不会影响普通模型部件。\n正常=正常渲染\n绿色闪烁=自定义部件渲染成绿色并闪烁\n边框=将渲染模型部件的轮廓\n禁用=自定义模型部件将不呈现",
```suggestion
	"entity_model_features.config.render.tooltip": "更改自定义模型部件的渲染方式，不会影响原版模型部件。\n正常=正常渲染\n绿色闪烁=自定义部件渲染成绿色并闪烁\n边框=将渲染模型部件的轮廓\n禁用=自定义模型部件将不呈现",
```

2023-11-19 08:18 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/entity-model-features/entity_model_features/lang/zh_cn.json
> +	"entity_model_features.config.animate_once.tooltip": "默认情况下打开\n该设置使实体模型对每个渲染的实体仅设置一次动画\n这在游戏中是完全正常的，但是可能会在物品栏界面中看到的生物奇怪地闪烁\n尤其是如果它代表了你已经看到的世界上真正的生物",
```suggestion
	"entity_model_features.config.animate_once.tooltip": "默认情况下启用\n该设置使实体模型对每个渲染的实体仅设置一次动画\n实际游戏中表现完全正常，但是在物品栏界面中看到的生物会奇怪地闪烁\n所见模型对应世界上你已经看到的真实的生物时尤甚",
```

2023-11-25 13:31 UTC, Ginsway commented
> 中英文行数不对应

`modmenu.nameTranslation.entity_model_features` 与 `modmenu.descriptionTranslation.entity_model_features` 
这两个键用于在 ModMenu 中翻译模组名与模组描述（[来源](https://github.com/TerraformersMC/ModMenu/wiki/API#translatable-metadata)）

2023-11-25 16:18 UTC, ChuijkYahus approved these changes

2023-11-25 16:28 UTC, Don-Trueno commented on projects/1.20-fabric/assets/entity-model-features/entity_model_features/lang/zh_cn.json
> +	"entity_model_features.config.log_models.tooltip": "将模型的创建调试数据打印到日志中",
程序上一般不用输出，后文如有的话同理，建议改为”输出“

2023-11-25 16:54 UTC, ChuijkYahus requested changes

2023-11-25 16:54 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/entity-model-features/entity_model_features/lang/zh_cn.json
> +	"entity_model_features.config.unknown_model_print_mode.tooltip": "这将打印出信息或完整的.jem文件\n对于任何未知或修改过的模型，EMF都可以访问\n注意：.jem文件还不完美，但会给你一个起点",
```suggestion
	"entity_model_features.config.unknown_model_print_mode.tooltip": "这将打印出信息或完整的.jem文件\n对于任何未知或修改过的模型，EMF都可以访问\n注意：.jem文件还不完美，但作为基础已算足够",
```
推荐改下

2023-11-25 16:54 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/entity-model-features/entity_model_features/lang/zh_cn.json
> +	"entity_model_features.config.physics.tooltip": "如果启用物理模组，将只在死亡时渲染原版模型部件\n这部分是有效的，但不是完美的解决方案",
推荐改下

2023-11-27 18:26 UTC, ChuijkYahus approved these changes

2023-11-27 18:27 UTC, merged