Create Ore Excavation[机械动力：矿石开掘]翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #3873
Opened 2023-10-28 08:09 UTC by Catchmons

2023-11-18 06:44 UTC, ChuijkYahus requested changes
键名确认最新吗
![P~SEDPLB } $QF${YDK{)33](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/905d4f8e-b724-4049-9946-74388b6cb611)

2023-11-18 06:44 UTC, ChuijkYahus commented on projects/1.19/assets/create-ore-excavation/createoreexcavation/lang/zh_cn.json
> +  "createoreexcavation.ponder.find_ores.text_3": "探测到：粗铜",
这里原文是铜矿石，为何修改

2023-11-19 09:19 UTC, Catchmons commented on projects/1.19/assets/create-ore-excavation/createoreexcavation/lang/zh_cn.json
> +  "createoreexcavation.ponder.find_ores.text_3": "探测到：粗铜",
因为游戏中矿脉的就是叫粗铜

2023-11-19 09:19 UTC, Catchmons commented
文件确实是最新的

2023-11-19 14:43 UTC, ChuijkYahus approved these changes
应该没什么大问题了
需要拉其他审核来看一下

2023-11-22 11:25 UTC, luoxueyasha approved these changes

2023-11-22 11:25 UTC, merged