SCP: Lockdown 翻译更新与修正，更新 en_us.lang 文件
CFPAOrg/Minecraft-Mod-Language-Package pull request #3877
Opened 2023-10-28 16:10 UTC by Sym601ETH

2023-11-18 05:39 UTC, luoxueyasha reviewed
粗看了一些，感觉翻的很粗糙

2023-11-18 05:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scptile.reinforcedwallc.name=加固墙 C
请解释一下为什么对所有的建材都进行了诸如此类的修改

2023-11-18 05:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scptile.one_way_glass_0.name=白色单面玻璃板
```suggestion
scptile.one_way_glass_0.name=白色单向玻璃板
```
请全文通查

2023-11-18 05:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scpitem.syringe.name=SCP-008 (丧尸病毒)
```suggestion
scpitem.syringe.name=SCP-008 (丧尸病毒）
```
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/95afe84b-e40d-46d8-a3b6-fdf82c4f32a7)

全角标点问题，请全文通查

2023-11-18 05:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +translationKey.category.scp=控制 收容 保护
官译有规定这条的标点吗？

2023-11-18 05:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
>  #Death messages:
* 这条是针对下方578～599行的审阅

 请参考原版的[死亡信息](https://zh.minecraft.wiki/w/%E6%AD%BB%E4%BA%A1%E6%B6%88%E6%81%AF?variant=zh-cn)格式修改内容

2023-11-18 05:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
>  death.attack.shuck_gaze=%1$s 死于黑煞星
原文：`%1$s died from seeing SCP-023`
不是很了解scp的具体设定，编号和名称可以互换吗

2023-11-18 05:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scp.plague.doctor.talk3=哦天哪，又是一个受疾病困扰的人
```suggestion
scp.plague.doctor.talk3=哦天哪，又一个得了瘟疫的人
```
翻了下原文和scp中文站的译文，感觉这句还有后面几句的意思翻的都不太对
建议重翻

2023-11-18 05:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scp.hole_in_the_wall.name=墙的上一个洞
？

2023-11-18 10:50 UTC, Sym601ETH commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scp.hole_in_the_wall.name=墙的上一个洞
这个是我打错的翻译，等我回来改

2023-11-18 10:51 UTC, Sym601ETH commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
>  death.attack.shuck_gaze=%1$s 死于黑煞星
可以，而且之前的翻译也是如此

2023-11-18 10:52 UTC, Sym601ETH commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +translationKey.category.scp=控制 收容 保护
没有顿号

2023-11-18 10:52 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
>  death.attack.shuck_gaze=%1$s 死于黑煞星
ok，这条先挂在这

2023-11-18 10:52 UTC, Sym601ETH commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scpitem.syringe.name=SCP-008 (丧尸病毒)
没打完整（

2023-11-18 10:53 UTC, Sym601ETH commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scptile.reinforcedwallc.name=加固墙 C
原文是这样，如 xx A

2023-11-18 10:56 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scptile.reinforcedwallc.name=加固墙 C
从实用角度上来说还是建议改为`X型建材`
不如说日文pr有很多这种格式的全被这么改了（

2023-11-25 02:44 UTC, Sym601ETH commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scptile.one_way_glass_0.name=白色单面玻璃板
这个是针对表现效果而翻译的

2023-11-25 02:58 UTC, Sym601ETH commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scpitem.syringe.name=SCP-008 (丧尸病毒)
emm我这里显示正常

2023-11-25 03:00 UTC, Sym601ETH commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scptile.reinforcedwallc.name=加固墙 C
个人感觉 xx A 这种可读性更好点
不过如果按照惯例来的话我还是改回去罢

2023-11-25 03:07 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scptile.one_way_glass_0.name=白色单面玻璃板
表现效果是指？可以说的具体些吗

2023-11-25 03:09 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scpitem.syringe.name=SCP-008 (丧尸病毒)
我这里显示很多右括号均为半角右括号`)`而非全角右括号`）`
请全文通查

2023-11-25 03:12 UTC, Sym601ETH commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scptile.one_way_glass_0.name=白色单面玻璃板
差不多就是 1能看到2 2却看不到1

说实话单面和单向没有什么区别，只不过是我自己的个人习惯翻译的（

2023-11-25 03:23 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scptile.one_way_glass_0.name=白色单面玻璃板
考虑到库内对同一原文有`单向玻璃板`
此外，`单面`一般是描述`镜子`的，如果指玻璃本身的话一般称为`单向`

2023-11-25 03:33 UTC, Sym601ETH commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +translationKey.category.scp=控制 收容 保护
已改

2023-11-25 03:34 UTC, Sym601ETH commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scptile.one_way_glass_0.name=白色单面玻璃板
ok

2023-11-25 03:48 UTC, Sym601ETH commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scpitem.syringe.name=SCP-008 (丧尸病毒)
已改

2023-11-25 06:39 UTC, luoxueyasha requested changes
注意：
由于模组语言文件年久失修+圈子内有自己的特殊规定，
**一切非格式层面的改动均需考量圈子内的人群意见**

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scptile.1074.dialogue1.1=卧槽！这画居然这么巧夺天工！
这9句对话的触发条件？
看了[1074](https://scp-wiki-cn.wikidot.com/scp-1074)大概知道在讲啥了倒是，但是如果玩家没有过任何杀生行为，会触发dialogue3那组对话吗

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
>  scpitem.processed_log.name=锻制刃木木条
原文`Processed Log`
确定是`木条`吗

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scpitem.level1card.name=ONE 级钥匙卡
[安保许可等级 - SCP基金会](https://scp-wiki-cn.wikidot.com/security-clearance-levels)
```suggestion
scpitem.level1card.name=1 级钥匙卡
```

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scpitem.info_tablet.name=档案查询平板
游戏内贴图，使用效果？

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scpitem.npctool.name=指挥棒
实际效果，获取方式？
感觉像是`指挥杖`，具体应视游戏内容而定

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scpitem.scp020vial.name=SCP-020 瓶装（隐形霉菌）
```suggestion
scpitem.scp020vial.name=瓶装 SCP-020（隐形霉菌）
```
```suggestion
scpitem.scp020vial.name=SCP-020 瓶（隐形霉菌）
```
这么读着更通顺

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
>  scpitem.scp_2295.name=缝心的熊
这条是不是也需要改成
```suggestion
scpitem.scp_2295.name=SCP-2295（缝心的熊）
```

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +item.dragoneggblobworm.name=绿龙蜗牛蛋（黄瞳）
```suggestion
item.dragoneggblobworm.name=团团虫龙蜗牛蛋
```
[SCP-111](https://scp-wiki-cn.wikidot.com/scp-111)
请全文通查

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +entity.scp.living_armor.name=SCP-912（自主型SWAT装甲）
```suggestion
entity.scp.living_armor.name=SCP-912（自主型 SWAT 装甲）
```
特别的，1.12版本需要用半角空格将字母与汉字区分开
详见《[翻译规范](https://cfpa.site/TransRules/)》，此问题请全文通查

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +entity.scp.scp143_fr.name=SCP-143-FR-1 (Pyroraptor)
漏翻

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +translationKey.category.scp=控制 收容 保护
```suggestion
translationKey.category.scp=控制，收容，保护
```
中文站用的分隔符是逗号（好像英文站也是
属于作者不讲武德的一环

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scp.plague.doctor.talk4=你并非是名医生
```suggestion
scp.plague.doctor.talk4=你并非一名医生
```
`并非是名`……读起来很怪
这里doctor还玩了博士和医生的双关……可以问一下触发条件吗

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scp.plague.doctor.talk5=我感觉到了深藏你身体的病症
同上，`瘟疫`

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scp.plague.doctor.talk6=我是你的救星
```suggestion
scp.plague.doctor.talk6=我就是你的解药
```
`cure`可以作`解药`用

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scp.plague.doctor.attacked2=停止抵抗，没有我你将时日无多！
这两句纯属前译者加戏了，建议对照原文自己翻
考虑到模组的年代，作者应该参考的是[重写前的049](https://scp-wiki-cn.wikidot.com/scp-049-arc)

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scp.invisible_mold.name=（隐形霉菌）
原文没有括号

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scp.card_reader=钥匙卡读取器
确定是`钥匙卡`吗
原文没有提及卡的种类

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scp.coffee.machine.invalid.item=您所选定的对象无效或无法盛装于当前容器
？
翻的不对吧
原文`You are holding invalid item for selected object`

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scp.document.unfinished=该SCP的收容设施仍在制作中
```suggestion
scp.document.unfinished=该 SCP 的收容设施仍在制作中
```

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scp.cant.replace=无法生成
触发条件？

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scp.card.required= 访问被禁止
触发条件，游戏内显示情况？
需要截图

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scp.gold.needed=出售失败！需要金锭
触发条件？确定是`出售`而不是`购买吗`

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scp.you.found.nothing=你手伸了进去，里面却空无一物
```suggestion
scp.you.found.nothing=你把手伸了进去，里面却空无一物
```

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scp.no.associated.file.found=无法找到与游戏语言相对应的文本文件，请暂时将游戏语言设置为英语（en_us）来显示当前文档
模组会自动将游戏语言切为英语吗？
还是说这个文本文件是游戏外的内容（例如直接连接到scp中文站）？

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
> +scp.shift.click.for.preview=潜行+右击地面显示结构预览，右击地面地面直接生成对应收容设施
```suggestion
scp.shift.click.for.preview=潜行+右击地面显示结构预览，右击地面将直接生成对应收容设施
```

2023-11-25 06:39 UTC, luoxueyasha commented on projects/1.12.2/assets/scp-lockdown/scp/lang/zh_cn.lang
>  scp.start.by.000j=请制作SCP官方物品目录和档案查询电脑以悉知玩法及更多信息
```suggestion
scp.start.by.000j=请制作 SCP 官方物品目录和档案查询电脑以悉知玩法及更多信息
```

2023-12-03 08:32 UTC, Sym601ETH commented
这周实在没时间改，且待会要返校了，下周更改

2023-12-20 10:54 UTC, luoxueyasha commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。 

@Sym601ETH

2023-12-28 20:06 UTC, closed without merging