The Graveyard 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #3892
Opened 2023-11-03 08:01 UTC by GypsoZ

2023-11-03 13:31 UTC, nageih commented on projects/1.20/assets/the-graveyard-forge/graveyard/lang/zh_cn.json
> +  "advancements.graveyard.lich_prison.description": "找到巫妖的祭坛。",
这里的lich似乎和Corrupted Champion指代的是同一个生物，是否要统一一下

2023-11-18 06:50 UTC, ChuijkYahus reviewed
如有必要可以参考库内已有的the graveyard（虽然内容没有1201多就是了）

2023-11-18 06:50 UTC, ChuijkYahus commented on projects/1.20/assets/the-graveyard-forge/graveyard/lang/zh_cn.json
> +  "block.graveyard.white_urn": "白色釉瓮",
这个叫`带釉瓮`怎么样（）

2023-11-18 07:21 UTC, GypsoZ commented on projects/1.20/assets/the-graveyard-forge/graveyard/lang/zh_cn.json
> +  "block.graveyard.white_urn": "白色釉瓮",
这部分是完全参考的之前版本的翻译 没在意x
不过进游戏看了下，改成`带釉瓮`确实更好，然后为了顺口感觉可以把`瓮`改成`陶瓮`？

2023-11-18 07:24 UTC, ChuijkYahus commented on projects/1.20/assets/the-graveyard-forge/graveyard/lang/zh_cn.json
> +  "block.graveyard.white_urn": "白色釉瓮",
挺好的（），不过这个改不改还是看是否合适

2023-11-18 07:28 UTC, GypsoZ commented on projects/1.20/assets/the-graveyard-forge/graveyard/lang/zh_cn.json
> +  "block.graveyard.white_urn": "白色釉瓮",
带釉陶瓦→带釉陶瓮，陶瓦→陶瓮，应该没啥问题

2023-11-18 10:24 UTC, ChuijkYahus requested changes

2023-11-18 10:24 UTC, ChuijkYahus commented on projects/1.20/assets/the-graveyard-forge/graveyard/lang/zh_cn.json
> +  "subtitles.entity.graveyard.ghouling.ambient": "食尸灵：呻吟",
```suggestion
  "subtitles.entity.graveyard.ghouling.ambient": "食尸灵：低吼",
```
是根据僵尸的字幕修改的，可以看下是否合适

2023-11-18 10:24 UTC, ChuijkYahus commented on projects/1.20/assets/the-graveyard-forge/graveyard/lang/zh_cn.json
> +  "subtitles.entity.graveyard.revenant.ambient": "亡魂 ：咯咯声",
```suggestion
  "subtitles.entity.graveyard.revenant.ambient": "亡魂：咯咯声",
```

2023-11-18 10:24 UTC, ChuijkYahus commented on projects/1.20/assets/the-graveyard-forge/graveyard/lang/zh_cn.json
> +  "subtitles.entity.graveyard.corrupted_illager.ambient": "堕落的刌民：呼吸",
```suggestion
  "subtitles.entity.graveyard.corrupted_illager.ambient": "堕落的灾厄村民：呼吸",
```
全文通查

2023-11-18 10:24 UTC, ChuijkYahus commented on projects/1.20/assets/the-graveyard-forge/graveyard/lang/zh_cn.json
> +  "subtitles.block.graveyard.urn.close": "瓮：关闭",
```suggestion
  "subtitles.block.graveyard.urn.open": "陶瓮：开启",
  "subtitles.block.graveyard.urn.close": "陶瓮：关闭",
```

2023-11-18 10:24 UTC, ChuijkYahus commented on projects/1.20/assets/the-graveyard-forge/graveyard/lang/zh_cn.json
> +  "subtitles.entity.graveyard.lich.theme_01": "播放 “Incarnated Evil”",
```suggestion
  "subtitles.entity.graveyard.lich.theme_01": "播放“Incarnated Evil”",
```

2023-11-18 10:24 UTC, ChuijkYahus commented on projects/1.20/assets/the-graveyard-forge/graveyard/lang/zh_cn.json
> +  "subtitles.item.graveyard.vial.splash": "血液滴下",
```suggestion
  "subtitles.item.graveyard.vial.splash": "血液：滴下",
```

2023-11-18 16:36 UTC, ChuijkYahus requested changes
其余应该问题不大了
拖个审核再看一眼

2023-11-18 16:36 UTC, ChuijkYahus commented on projects/1.20/assets/the-graveyard-forge/graveyard/lang/zh_cn.json
> +  "advancements.graveyard.visit_at_night.description": "睡在墓园上。",
```suggestion
  "advancements.graveyard.visit_at_night.description": "在墓园中睡觉。",
```

2023-11-18 16:36 UTC, ChuijkYahus commented on projects/1.20/assets/the-graveyard-forge/graveyard/lang/zh_cn.json
> +  "advancements.graveyard.haunted_house.description": "接受邀请前往森林中的房子。",
```suggestion
  "advancements.graveyard.haunted_house.description": "受邀前往森林中的房子。",
```

2023-11-18 16:36 UTC, ChuijkYahus commented on projects/1.20/assets/the-graveyard-forge/graveyard/lang/zh_cn.json
> +  "advancements.graveyard.root.description": "找到一个小型坟墓",
```suggestion
  "advancements.graveyard.root.description": "找到一个小型坟墓。",
```

2023-11-18 17:09 UTC, ChuijkYahus approved these changes
~~如果愿意也可以修库内1182和1165的翻译（）~~

2023-11-22 12:58 UTC, merged