Lopy's More Materials翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3895
Opened 2023-11-04 05:36 UTC by LogyFox

2023-11-18 06:17 UTC, ChuijkYahus requested changes
好多生造词啊……

2023-11-18 06:17 UTC, ChuijkYahus commented on projects/1.18/assets/morematerials/mmt/lang/zh_cn.json
> +  "item.mmt.jade": "翡翠",
```suggestion
  "item.mmt.jade": "玉",
```
推荐叫`玉`，涵盖范围广些

2023-11-18 06:17 UTC, ChuijkYahus commented on projects/1.18/assets/morematerials/mmt/lang/zh_cn.json
> +  "item.mmt.tourmaline": "电气石",
```suggestion
  "item.mmt.tourmaline": "碧玺",
```
宝石名

2023-11-18 06:17 UTC, ChuijkYahus commented on projects/1.18/assets/morematerials/mmt/lang/zh_cn.json
> +  "item.mmt.sunstone": "日长石",
```suggestion
  "item.mmt.sunstone": "日光石",
```
宝石名

2023-11-18 06:17 UTC, ChuijkYahus commented on projects/1.18/assets/morematerials/mmt/lang/zh_cn.json
> +  "item.mmt.moonstone": "月长石",
```suggestion
  "item.mmt.moonstone": "月光石",
```
宝石名

2023-11-18 11:19 UTC, LogyFox reviewed
修订翻译

2024-07-01 15:42 UTC, closed without merging

2024-07-01 15:43 UTC, ChuijkYahus commented
已在#4422 中统一比对审核并加上协作，感谢翻译