提交create-sifting1.20.1版本翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #3906
Opened 2023-11-09 08:52 UTC by Ballon-zzx

2023-11-09 08:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3906) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3906) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3906) it.</sub>

2023-11-18 05:11 UTC, luoxueyasha requested changes

2023-11-18 05:11 UTC, luoxueyasha commented on projects/1.20/assets/create-sifting/createsifter/lang/zh_cn.json
> +  "create.recipe.sifting": "筛选配方",
```suggestion
  "create.recipe.sifting": "筛子配方",
```
具体应以游戏内内容为准

2023-11-18 05:11 UTC, luoxueyasha commented on projects/1.20/assets/create-sifting/createsifter/lang/zh_cn.json
> +  "createsifter.ponder.sifter.header": "方块筛",
在游戏内的显示位置，其作用？

2023-11-18 05:11 UTC, luoxueyasha commented on projects/1.20/assets/create-sifting/createsifter/lang/zh_cn.json
> +  "createsifter.ponder.sifter.text_5": "输出也可以通过自动化提取",
这五句话漏译、生硬翻译过多，请自行检查

2023-11-18 05:11 UTC, luoxueyasha commented on projects/1.20/assets/create-sifting/createsifter/lang/zh_cn.json
> +  "createsifter.recipe.sifting.waterlogged": "浸满水",
```suggestion
  "createsifter.recipe.sifting.waterlogged": "含水的",
```
`Waterlogging` 的原版译名为`含水`
译文应以具体实际游戏内容进行翻译

2023-11-18 05:11 UTC, luoxueyasha commented on projects/1.20/assets/create-sifting/createsifter/lang/zh_cn.json
> +  "createsifter.recipe.sifting": "筛选配方",
```suggestion
  "createsifter.recipe.sifting": "筛子配方",
```
同上
不知道create类的recipe抬头有没有什么标准

2023-11-18 05:11 UTC, luoxueyasha commented on projects/1.20/assets/create-sifting/createsifter/lang/zh_cn.json
> +  "itemGroup.createsifter:main": "机械动力-筛子"
```suggestion
  "itemGroup.createsifter:main": "机械动力：筛子"
```

2023-11-18 06:21 UTC, Ballon-zzx commented on projects/1.20/assets/create-sifting/createsifter/lang/zh_cn.json
> +  "createsifter.ponder.sifter.header": "方块筛",
"block.createsifter.sifter"和"createsifter.ponder.sifter.header"暂未看见，剩下的一个在jei显示，一个是工程师护目镜的转速显示

2023-11-18 06:22 UTC, Ballon-zzx commented on projects/1.20/assets/create-sifting/createsifter/lang/zh_cn.json
> +  "createsifter.ponder.sifter.text_5": "输出也可以通过自动化提取",
额，这五个都是在上一个版本的汉化修正过后的

2024-01-16 09:03 UTC, closed without merging