paragliders 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3908
Opened 2023-11-10 03:00 UTC by CupOfBread

paragliders 滑翔伞模组 翻译提交

2023-11-11 10:10 UTC, nageih commented on projects/1.20-fabric/assets/paragliders/paraglider/lang/zh_cn.json
> +	"advancement.paraglider.desc": "这是滑翔伞模组的成就！",
```suggestion
	"advancement.paraglider.desc": "这是滑翔伞模组的进度！",
```

2023-11-12 15:00 UTC, Cactusstudent requested changes
请全文通查空格

2023-11-12 15:00 UTC, Cactusstudent commented on projects/1.20-fabric/assets/paragliders/paraglider/lang/zh_cn.json
> +	"paragliderSettings.openFolder.tooltip": "查找名为 '§eparagliderSettings.nbt§r'的文件。 您可以将其复制到其他实例中，也可以覆盖当前实例。\n（覆盖后，请务必重新加载设置。）",
```suggestion
	"paragliderSettings.openFolder.tooltip": "查找名为'§eparagliderSettings.nbt§r'的文件。 您可以将其复制到其他实例中，也可以覆盖当前实例。\n（覆盖后，请务必重新加载设置。）",
```

2023-11-12 15:00 UTC, Cactusstudent commented on projects/1.20-fabric/assets/paragliders/paraglider/lang/zh_cn.json
> +	"commands.paraglider.get.heart_container.result": "%1$s 拥有 %2$s 个心之容器。",
下方的英文字符与汉字之间的空格需要全部删去

2023-11-18 02:09 UTC, CupOfBread commented on projects/1.20-fabric/assets/paragliders/paraglider/lang/zh_cn.json
> +	"tooltip.paraglider.anti_vessel.1": "§5§k§oasdfasdfasdfas dfasdfasdfasfd sfn §c§k§o가나다§5§k§ofdadff§r",
这就是一段乱码，没办法翻译的

2023-11-18 02:11 UTC, CupOfBread commented on projects/1.20-fabric/assets/paragliders/paraglider/lang/zh_cn.json
> +	"bargain.dialog.goddess_statue.initial.1": "告诉我，你所欲为何？",
有几种说法，如欲何为、所欲何为、何为汝欲。但是没有何为汝欲。

2023-11-18 06:03 UTC, ChuijkYahus requested changes
真没实际玩过塞尔达，没法验证里面的物品翻译是否准确

2023-11-18 06:03 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/paragliders/paraglider/lang/zh_cn.json
> +	"commands.paraglider.bargain.start.no_bargain": "%s类型和%s位置无交易可用。",
```suggestion
	"commands.paraglider.bargain.start.no_bargain": "%1$s在%2$s类型和%3$s位置下无交易可用。",
```

2023-11-18 06:03 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/paragliders/paraglider/lang/zh_cn.json
> +	"paragliderSettings.openFolder.tooltip": "查找名为'§eparagliderSettings.nbt§r'的文件。 您可以将其复制到其他实例中，也可以覆盖当前实例。\n（覆盖后，请务必重新加载设置。）",
```suggestion
	"paragliderSettings.openFolder.tooltip": "查找名为'§eparagliderSettings.nbt§r'的文件。你可以将其复制到其他实例中，也可以覆盖当前实例。\n（覆盖后，请务必重新加载设置。）",
```

2023-11-18 06:03 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/paragliders/paraglider/lang/zh_cn.json
> +	"tooltip.paraglider.anti_vessel.1": "§5§k§oasdfasdfasdfas dfasdfasdfasfd sfn §c§k§o가나다§5§k§ofdadff§r",
这韩语辅音表怎么不打全（）

2023-11-18 06:03 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/paragliders/paraglider/lang/zh_cn.json
> +	"commands.paraglider.give.essence.success": "给予 %2$s%1$s个精华。",
```suggestion
	"commands.paraglider.give.essence.success": "给予%2$s%1$s个精华。",
```

2023-11-18 08:21 UTC, CupOfBread commented on projects/1.20-fabric/assets/paragliders/paraglider/lang/zh_cn.json
> +	"tooltip.paraglider.anti_vessel.1": "§5§k§oasdfasdfasdfas dfasdfasdfasfd sfn §c§k§o가나다§5§k§ofdadff§r",
哈哈哈

2023-11-18 09:53 UTC, ChuijkYahus requested changes

2023-11-18 09:53 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/paragliders/paraglider/lang/zh_cn.json
> +	"commands.paraglider.give.essence.success": "给予%2$s%1$s个精华。",
```suggestion
	"commands.paraglider.give.essence.success": "给予了%1$s%2$s个精华。",
```

2023-11-18 09:53 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/paragliders/paraglider/lang/zh_cn.json
> +	"commands.paraglider.take.essence.success": "减少%1$s%2$s个精华。",
```suggestion
	"commands.paraglider.take.stamina_vessel.success": "将%1$s的耐力容器减少%2$s个。",
	"commands.paraglider.take.essence.success": "将%1$s的精华减少%2$s个。",
```

2023-11-18 09:53 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/paragliders/paraglider/lang/zh_cn.json
> +	"commands.paraglider.set.essence.too_low": "%s的精华太低了。",
```suggestion
	"commands.paraglider.set.stamina_vessel.too_high": "%s对于耐力容器数量来说太多了。",
	"commands.paraglider.set.essence.too_high": "%s对于精华数量来说太多了。",
	"commands.paraglider.set.heart_container.too_low": "%s对于心之容器数量来说太少了。",
	"commands.paraglider.set.stamina_vessel.too_low": "%s对于耐力容器数量来说太少了。",
	"commands.paraglider.set.essence.too_low": "%s对于精华数量来说太少了。",
```

2023-11-18 09:53 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/paragliders/paraglider/lang/zh_cn.json
> +	"bargain.dialog.horned_statue.initial.1": "要修改你的§b精华§r，是吗？",
```suggestion
	"bargain.dialog.horned_statue.initial.1": "要调整你的§b精华§r，是吗？",
```

2023-11-18 10:15 UTC, ChuijkYahus submitted a review, later dismissed
Spirit Orb以及其他物品等名称还需要熟悉塞尔达系列的人来再看
其他应该问题不大了

2023-11-21 13:10 UTC, Cactusstudent approved these changes
问题不大

2023-11-21 13:10 UTC, Cactusstudent commented on projects/1.20-fabric/assets/paragliders/paraglider/lang/zh_cn.json
> +	"paragliderSettings.windParticleFreq.tooltip": "调整上升风产生的粒子效果的频率。（0%% ~ 100%%）",
```suggestion
	"paragliderSettings.windParticleFreq.tooltip": "调整上升风产生的粒子效果的频率。（0%%~100%%）",
```

2023-11-25 05:43 UTC, ChuijkYahus approved these changes

2023-11-26 03:43 UTC, merged