Thermal: Extra 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3909
Opened 2023-11-10 03:43 UTC by QiuShui1012

将不知道哪个版本传下来的古老翻译和原文更新了一下。

由 CFPA-Helper 提交。

2023-11-10 03:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3909) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3909) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3909) it.</sub>

2023-11-12 14:48 UTC, Cactusstudent reviewed
可参考本库中其他版本的Thermal: Extra翻译

2023-11-13 03:07 UTC, QiuShui1012 commented
我不认同1.19的翻译里将soul_infused译为灵魂灌注，此译名并没有体现它的金属属性。

2023-11-25 18:13 UTC, ChuijkYahus requested changes

2023-11-25 18:13 UTC, ChuijkYahus commented on projects/1.18/assets/thermal_extra/thermal_extra/lang/zh_cn.json
> +    "item.thermal_extra.area_radius_augment_4": "双子物质范围增强",
```suggestion
    "item.thermal_extra.area_radius_augment_1": "注灵钢径向范围拓展",
    "item.thermal_extra.area_radius_augment_2": "末影径向范围拓展",
    "item.thermal_extra.area_radius_augment_3": "潜影合金径向范围拓展",
    "item.thermal_extra.area_radius_augment_4": "双子物质径向范围拓展",
```
thermal原文

2023-11-25 18:13 UTC, ChuijkYahus commented on projects/1.18/assets/thermal_extra/thermal_extra/lang/zh_cn.json
> +    "item.thermal_extra.av_item_filter_augment": "高级物品过滤器",
```suggestion
    "item.thermal_extra.av_item_filter_augment": "高级物品过滤规则",
```

2023-11-25 18:13 UTC, ChuijkYahus commented on projects/1.18/assets/thermal_extra/thermal_extra/lang/zh_cn.json
> +    "item.thermal_extra.machine_output_augment_3": "潜影合金辅助过程筛",
```suggestion
    "item.thermal_extra.machine_output_augment_1": "注灵钢辅助处理筛",
    "item.thermal_extra.machine_output_augment_2": "末影辅助处理筛",
    "item.thermal_extra.machine_output_augment_3": "潜影合金辅助处理筛",
```
？

2023-11-25 18:13 UTC, ChuijkYahus commented on projects/1.18/assets/thermal_extra/thermal_extra/lang/zh_cn.json
> +    "item.thermal_extra.potion_duration_augment_5": "龙钢炼金延时器",
```suggestion
    "item.thermal_extra.potion_duration_augment_1": "注灵钢炼金延长器",
    "item.thermal_extra.potion_duration_augment_2": "末影炼金延长器",
    "item.thermal_extra.potion_duration_augment_3": "潜影合金炼金延长器",
    "item.thermal_extra.potion_duration_augment_4": "双子物质炼金延长器",
    "item.thermal_extra.potion_duration_augment_5": "龙钢炼金延长器",
```

2023-11-25 18:13 UTC, ChuijkYahus commented on projects/1.18/assets/thermal_extra/thermal_extra/lang/zh_cn.json
> +    "item.thermal_extra.rf_coil_xfer_augment_5": "龙钢通量通量线圈",
```suggestion
    "item.thermal_extra.rf_coil_xfer_augment_1": "注灵钢强导通量线圈",
    "item.thermal_extra.rf_coil_xfer_augment_2": "末影强导通量线圈",
    "item.thermal_extra.rf_coil_xfer_augment_3": "潜影合金强导通量线圈",
    "item.thermal_extra.rf_coil_xfer_augment_4": "双子物质强导通量线圈",
    "item.thermal_extra.rf_coil_xfer_augment_5": "龙钢强导通量线圈",
```

2023-11-26 05:08 UTC, Cactusstudent requested changes

2023-11-26 05:08 UTC, Cactusstudent commented on projects/1.18/assets/thermal_extra/thermal_extra/lang/zh_cn.json
> +    "item.thermal_extra.dynamo_fuel_augment_1": "注灵钢多环泵注器",
请简述翻译为**器**的根本原因

2023-11-26 05:08 UTC, Cactusstudent commented on projects/1.18/assets/thermal_extra/thermal_extra/lang/zh_cn.json
> +    "block.thermal_extra.soul_infused_block": "注灵钢块",
原文：**Soul Infused Block**，**应当**以原文为准，另请简单解释将 `Soul Infused` 翻译为 `注灵` 的原因

2023-11-26 05:09 UTC, ChuijkYahus commented on projects/1.18/assets/thermal_extra/thermal_extra/lang/zh_cn.json
> +    "item.thermal_extra.dynamo_fuel_augment_1": "注灵钢多环泵注器",
![E0I}Z~RPLWP~57DO9PTZDIA](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/80b0c990-42ea-4ec9-a33f-e1f9c8f85404)

2023-11-26 05:11 UTC, Cactusstudent commented on projects/1.18/assets/thermal_extra/thermal_extra/lang/zh_cn.json
> +    "block.thermal_extra.soul_infused_block": "注灵钢块",
> 原文：**Soul Infused Block**，**应当**以原文为准，另请简单解释将 `Soul Infused` 翻译为 `注灵（钢）` 的原因

2023-11-26 05:14 UTC, ChuijkYahus commented on projects/1.18/assets/thermal_extra/thermal_extra/lang/zh_cn.json
> +    "item.thermal_extra.dynamo_fuel_augment_1": "注灵钢多环泵注器",
1.19.2，装有i18n

2023-11-26 07:52 UTC, QiuShui1012 commented on projects/1.18/assets/thermal_extra/thermal_extra/lang/zh_cn.json
> +    "block.thermal_extra.soul_infused_block": "注灵钢块",
原版合成配方为磷灰石+灵魂沙碎末+铁锭，将`Soul Infused`的直译`灵魂灌注`转换语序，就得到了`注灵`；
为了突出金属性质，就再加入`钢`，因为是将其它原料+铁在感应炉里烧制而成的

2023-11-26 07:54 UTC, QiuShui1012 commented on projects/1.18/assets/thermal_extra/thermal_extra/lang/zh_cn.json
> +    "item.thermal_extra.dynamo_fuel_augment_1": "注灵钢多环泵注器",
热力系列原文就为多环泵注器

2023-11-26 14:48 UTC, QiuShui1012 commented on projects/1.18/assets/thermal_extra/thermal_extra/lang/zh_cn.json
> +    "block.thermal_extra.soul_infused_block": "注灵钢块",
> 原版合成配方为磷灰石+灵魂沙碎末+铁锭，将`Soul Infused`的直译`灵魂灌注`转换语序，就得到了`注灵`； 为了突出金属性质，就再加入`钢`，因为是将其它原料+铁在感应炉里烧制而成的

（XK's deco中的钢就是铁烧制而成的）

2023-11-29 12:35 UTC, Cactusstudent approved these changes

2023-12-01 17:40 UTC, merged