nvidium 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3915
Opened 2023-11-13 08:37 UTC by 771835

nvidium-0.2.3-beta+1.20.1
参考：https://github.com/MCRcortex/nvidium/pull/89

2023-11-14 08:27 UTC, qznfbnj reviewed
除了【为啥要根据显存限制“内存”？】、【英文半角符号】、【复数】，都只是建议
（小声bb：其实你可以直接修改文件路径的（即使是网页版也可以）

2023-11-14 08:27 UTC, qznfbnj commented on projects/1.20-fabric/assets/0-modrinth-mod/nvidium/lang/zh_cn.json
> +}
被参考的版本有这么一条，应该是模组菜单显示的信息，你看需要加么
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/100760086/789f279a-0278-4e4e-8c06-2b9fca421126)

2023-11-14 08:27 UTC, qznfbnj commented on projects/1.20-fabric/assets/0-modrinth-mod/nvidium/lang/zh_cn.json
> +  "nvidium.options.async_bfs.tooltip" : "启用异步广度优先搜索（Async BFS）算法区域加载，大大减少了转动视角时两帧之间的渲染耗时，在更高的渲染距离下更为明显。"
区域（sections）可能是指 `子区块`
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/100760086/97f72db2-19a9-4a48-83ae-e66009241ef8)
`moving` 是 `转动视角` 吗？
`两帧之间的渲染耗时` 挺长的，要不直接 `帧渲染时间/耗时` 吧

2023-11-14 08:27 UTC, qznfbnj commented on projects/1.20-fabric/assets/0-modrinth-mod/nvidium/lang/zh_cn.json
> +  "nvidium.options.statistics_level.tooltip" : "统计记录级别，跟踪删减图层的可见度计数",
直译如何？
`统计日志记录级别` -> `统计数据级别`
`统计记录级别` -> `统计数据的记录级别`
然后，`删减图层` 是什么？

2023-11-14 10:15 UTC, 771835 commented
我把把改了一下

2023-11-14 10:37 UTC, qznfbnj commented
> 我把把改了一下

好的，不过，为啥要根据显存限制“内存”？
还有，L13的 `区段` (Section) 是哪的翻译？
L25的 `moving` 为什么是 `转动视角`？L10的 `turning around` 也是 `转动视角`，确认了这两个一样吗？

2023-11-15 09:54 UTC, 771835 commented
根据显存限制内存的目的可能是为了防止超出显存限制。我没怎么了解java.

2023-11-15 09:58 UTC, qznfbnj commented
> 根据显存限制内存的目的可能是为了防止超出显存限制。我没怎么了解java.

到底是显存还是内存？

2023-11-16 09:09 UTC, 771835 commented
这和翻译提交有神马关系，我又不是作者

2023-11-16 09:19 UTC, qznfbnj commented
> 这和翻译提交有神马关系，我又不是作者

你是翻译作者，就必须理解自己翻译的东西都是什么
![S31116-17132168_com android chrome](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/100760086/9825775d-f34a-4a32-a2ad-e9a83084c293)
我认为，6行的 Memory 指的应该是显存（也就是红框标出来的 vram），你觉得呢？
还有，25行的末尾忘记补上逗号了

2023-11-16 09:36 UTC, 771835 commented
我改改

2023-11-16 09:38 UTC, 771835 commented
握草，改错了，改成en_us.json了

2023-11-16 09:39 UTC, qznfbnj commented
啊这

2023-11-17 09:51 UTC, 771835 commented
话说这个翻译提交什么时后合并

2023-11-17 10:00 UTC, qznfbnj commented
> 话说这个翻译提交什么时后合并

可以加群问。review是任何人都可以review的，但合并需要approving review
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/100760086/63c8f0e3-aab7-4e21-bd13-868b251b8353)

2023-11-17 10:05 UTC, 771835 commented
哦

2023-11-18 04:50 UTC, ChuijkYahus requested changes
请注意删除半角字符与全角字符之间的空格

2023-11-18 04:50 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/0-modrinth-mod/nvidium/lang/zh_cn.json
> +  "modmenu.modmenu.descriptionTranslation.modmenu.nvidium": "替代 Sodium 的渲染引擎"
```suggestion
  "modmenu.modmenu.descriptionTranslation.modmenu.nvidium": "替代Sodium的渲染引擎"
```
请注意删除半角字符与全角字符之间的空格

2023-11-18 04:50 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/0-modrinth-mod/nvidium/lang/zh_cn.json
> +  "nvidium.options.translucency_sorting.tooltip" : "透明度排序级别，每个级别对性能影响和视觉质量都不同。\nNone: 没有透明度排序，无影响，但可能看起来很糟糕。\nSection: 截面透明度排序，使透明度达到与钠相同的水平，影响最小。\nQuads: 增量排序，在多帧上正确排序几何体，但在排序时可能会导致视觉上的怪异现象。",
```suggestion
  "nvidium.options.translucency_sorting.tooltip" : "透明度排序级别，每个级别对性能影响和视觉质量都不同。\nNone：没有透明度排序，无影响，但可能看起来很糟糕。\nSection：截面透明度排序，使透明度达到与钠相同的水平，影响最小。\nQuads：增量排序，在多帧上正确排序几何体，但在排序时可能会导致视觉上的怪异现象。",
```
全角冒号

2023-11-18 04:50 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/0-modrinth-mod/nvidium/lang/zh_cn.json
> +  "nvidium.options.enable_temporal_coherence.tooltip" : "消除转动视角时的图像伪影（伪影：在图像处理后，表现为不自然的，能让人看出瑕疵等。）",
```suggestion
  "nvidium.options.enable_temporal_coherence.tooltip" : "消除转动视角时的图像伪影（伪影：在图像处理后能让人看出瑕疵的不自然视效。）",
```
微调

2023-11-18 16:41 UTC, ChuijkYahus requested changes
其余应该问题不大了

2023-11-18 16:41 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/0-modrinth-mod/nvidium/lang/zh_cn.json
> +  "nvidium.options.translucency_sorting.quads" : "Quads 模式",
```suggestion
  "nvidium.options.translucency_sorting.sections" : "Sections模式",
  "nvidium.options.translucency_sorting.quads" : "Quads模式",
```

2023-11-18 16:41 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/0-modrinth-mod/nvidium/lang/zh_cn.json
> +  "nvidium.options.statistics_level.quads" : "Quads 模式",
```suggestion
  "nvidium.options.statistics_level.frustum" : "Frustum模式",
  "nvidium.options.statistics_level.regions" : "Regions模式",
  "nvidium.options.statistics_level.sections" : "Sections模式",
  "nvidium.options.statistics_level.quads" : "Quads模式",
```

2023-11-18 16:41 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/0-modrinth-mod/nvidium/lang/zh_cn.json
> +  "nvidium.options.translucency_sorting.none" : "None",
```suggestion
  "nvidium.options.translucency_sorting.none" : "禁用",
```
与L19保持统一

2023-11-18 16:41 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/0-modrinth-mod/nvidium/lang/zh_cn.json
> +  "nvidium.options.translucency_sorting.tooltip" : "透明度排序级别，每个级别对性能影响和视觉质量都不同。\nNone：没有透明度排序，无影响，但可能看起来很糟糕。\nSection：截面透明度排序，使透明度达到与钠相同的水平，影响最小。\nQuads：增量排序，在多帧上正确排序几何体，但在排序时可能会导致视觉上的怪异现象。",
```suggestion
  "nvidium.options.translucency_sorting.tooltip" : "透明度排序级别，每个级别对性能影响和视觉质量都不同。\n禁用：没有透明度排序，无影响，但可能看起来很糟糕。\nSection：截面透明度排序，使透明度达到与钠相同的水平，影响最小。\nQuads：增量排序，在多帧上正确排序几何体，但在排序时可能会导致视觉上的怪异现象。",
```
与L19保持统一

2023-11-20 09:09 UTC, 771835 commented
这个mod有1.19的版本，可是Minecraft-Mod-Language-Package/projects中没有1.19-fabric,是不要加到1.19里

2023-11-20 09:52 UTC, ChuijkYahus commented
> 这个mod有1.19的版本，可是Minecraft-Mod-Language-Package/projects中没有1.19-fabric,是不是要加到1.19里

对的，1.19文件夹forge和fabric都放

2023-11-20 09:52 UTC, ChuijkYahus requested changes

2023-11-20 09:52 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/0-modrinth-mod/nvidium/lang/zh_cn.json
> +  "nvidium.options.translucency_sorting.tooltip" : "透明度排序级别，每个级别对性能影响和视觉质量都不同。\禁用：没有透明度排序，无影响，但可能看起来很糟糕。\nSection：截面透明度排序，使透明度达到与钠相同的水平，影响最小。\nQuads：增量排序，在多帧上正确排序几何体，但在排序时可能会导致视觉上的怪异现象。",
```suggestion
  "nvidium.options.translucency_sorting.tooltip" : "透明度排序级别，每个级别对性能影响和视觉质量都不同。\n禁用：没有透明度排序，无影响，但可能看起来很糟糕。\nSection：截面透明度排序，使透明度达到与钠相同的水平，影响最小。\nQuads：增量排序，在多帧上正确排序几何体，但在排序时可能会导致视觉上的怪异现象。",
```

2023-11-25 05:45 UTC, ChuijkYahus approved these changes

2023-11-26 03:44 UTC, merged