提交betterarcheology翻译文件
CFPAOrg/Minecraft-Mod-Language-Package pull request #3916
Opened 2023-11-14 10:42 UTC by Tibsalta-IC

2023-11-18 04:54 UTC, ChuijkYahus requested changes
库内已有Better Archeology的1.20 Fabric版本，请注意参照修改

2023-11-18 04:54 UTC, ChuijkYahus commented on projects/1.20/assets/better-archeology/betterarcheology/lang/zh_cn.json
> +  "block.betterarcheology.cracked_mud_brick_stairs": "破裂的泥砖楼梯",
```suggestion
  "block.betterarcheology.cracked_mud_bricks": "裂纹泥砖",
  "block.betterarcheology.cracked_mud_brick_slab": "裂纹泥砖台阶",
  "block.betterarcheology.cracked_mud_brick_stairs": "裂纹泥砖楼梯",
```
见原版术语`裂纹`/`Cracked`

2023-11-18 04:54 UTC, ChuijkYahus commented on projects/1.20/assets/better-archeology/betterarcheology/lang/zh_cn.json
> +  "block.betterarcheology.villager_fossil_head_tooltip": "它们似乎没有演化很多...",
```suggestion
  "block.betterarcheology.villager_fossil_head_tooltip": "它们似乎没有演化很多……",
```
请注意使用中文省略号，一般在输入法中按下`Shift`+`6`即可

2023-11-18 04:54 UTC, ChuijkYahus commented on projects/1.20/assets/better-archeology/betterarcheology/lang/zh_cn.json
> +  "block.betterarcheology.infested_mud_bricks": "感染的泥砖",
```suggestion
  "block.betterarcheology.infested_mud_bricks": "虫蚀泥砖",
```
参见原版术语`虫蚀`/`Infested`

2023-11-18 04:54 UTC, ChuijkYahus commented on projects/1.20/assets/better-archeology/betterarcheology/lang/zh_cn.json
> +  "block.betterarcheology.rotten_fence_gate": "腐朽的围栏门",
```suggestion
  "block.betterarcheology.rotten_fence": "腐朽的栅栏",
  "block.betterarcheology.rotten_fence_gate": "腐朽的栅栏门",
```
参见原版术语`栅栏`/`Fence`以及`栅栏门`/`Fence Gate`

2023-11-18 07:01 UTC, ChuijkYahus requested changes
请注意与库内已有的Better Archeology 1.20.1 Fabric版本的语言文件相互对照并统一

2023-11-18 07:01 UTC, ChuijkYahus commented on projects/1.20/assets/better-archeology/betterarcheology/lang/zh_cn.json
> +  "block.betterarcheology.sheep_fossil_body_tooltip": "不再那么蓬松...",
```suggestion
  "block.betterarcheology.sheep_fossil_body_tooltip": "不再那么蓬松……",
```
中文省略号

2023-11-18 07:36 UTC, ChuijkYahus requested changes
建议对照https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/projects/1.20-fabric/assets/better-archeology/betterarcheology/lang/zh_cn.json
此处各suggestion旨在**提供对照**，若认为fabric版本译文不好，欢迎提出建议或直接修改

2023-11-18 07:36 UTC, ChuijkYahus commented on projects/1.20/assets/better-archeology/betterarcheology/lang/zh_cn.json
> +  "block.betterarcheology.rotten_door": "腐朽的门",
```suggestion
  "block.betterarcheology.rotten_log": "腐烂原木",
  "block.betterarcheology.rotten_planks": "腐烂木板",
  "block.betterarcheology.rotten_slab": "腐烂木台阶",
  "block.betterarcheology.rotten_stairs": "腐烂木楼梯",
  "block.betterarcheology.rotten_fence": "腐烂木栅栏",
  "block.betterarcheology.rotten_fence_gate": "腐烂木栅栏门",
  "block.betterarcheology.rotten_trapdoor": "腐烂木活板门",
  "block.betterarcheology.rotten_door": "腐烂木门",
```

2023-11-18 07:36 UTC, ChuijkYahus commented on projects/1.20/assets/better-archeology/betterarcheology/lang/zh_cn.json
> +  "block.betterarcheology.creeper_fossil_body_tooltip": "所以这是它力量的来源！",
```suggestion
  "block.betterarcheology.fossiliferous_dirt": "含化石的泥土",
  "block.betterarcheology.fossiliferous_dirt_tooltip": "也许其中有什么东西等待着发掘？",
  "block.betterarcheology.villager_fossil": "村民化石",
  "block.betterarcheology.villager_fossil_tooltip": "它变为化石的手臂或许可以展示什么东西",
  "block.betterarcheology.villager_fossil_head": "村民颅骨化石",
  "block.betterarcheology.villager_fossil_head_tooltip": "他们看起来还没进化到位……",
  "block.betterarcheology.villager_fossil_body": "村民躯干化石",
  "block.betterarcheology.villager_fossil_body_tooltip": "这个可怖的东西提醒着人们曾有一座村庄消失在时间之中",
  "block.betterarcheology.ocelot_fossil": "豹猫化石",
  "block.betterarcheology.ocelot_fossil_tooltip": "苦力怕害怕这个更甚于害怕活猫",
  "block.betterarcheology.ocelot_fossil_head": "豹猫颅骨化石",
  "block.betterarcheology.ocelot_fossil_head_tooltip": "不同于它们的后裔，这群豹猫有着长长的利齿",
  "block.betterarcheology.ocelot_fossil_body": "豹猫躯干化石",
  "block.betterarcheology.ocelot_fossil_body_tooltip": "看起来它们牺牲敏捷换来了力量",
  "block.betterarcheology.sheep_fossil": "绵羊化石",
  "block.betterarcheology.sheep_fossil_tooltip": "它的角让你想起了山羊的。也许这个也能吹得响？",
  "block.betterarcheology.sheep_fossil_head": "绵羊颅骨化石",
  "block.betterarcheology.sheep_fossil_head_tooltip": "也许它能撞出比山羊更深刻的凹痕",
  "block.betterarcheology.sheep_fossil_body": "绵羊躯干化石",
  "block.betterarcheology.sheep_fossil_body_tooltip": "这只羊蓬松松的毛没了",
  "block.betterarcheology.chicken_fossil": "鸡化石",
  "block.betterarcheology.chicken_fossil_tooltip": "靠近它的时候你感觉身体变轻了",
  "block.betterarcheology.chicken_fossil_head": "鸡颅骨化石",
  "block.betterarcheology.chicken_fossil_head_tooltip": "它的喙比你熟知的鸡更大",
  "block.betterarcheology.chicken_fossil_body": "鸡躯干化石",
  "block.betterarcheology.chicken_fossil_body_tooltip": "它的翅膀上也长有利爪；看起来这个种群也可能曾有过更长的尾巴",
  "block.betterarcheology.creeper_fossil": "苦力怕化石",
  "block.betterarcheology.creeper_fossil_tooltip": "它比真的苦力怕看着还吓人……",
  "block.betterarcheology.creeper_fossil_head": "苦力怕颅骨化石",
  "block.betterarcheology.creeper_fossil_head_tooltip": "这张脸曾让你陷入无休止的战栗之中",
  "block.betterarcheology.creeper_fossil_body": "苦力怕躯干化石",
  "block.betterarcheology.creeper_fossil_body_tooltip": "所以这就是它力量的源头！",
```
来源：https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/projects/1.20-fabric/assets/better-archeology/betterarcheology/lang/zh_cn.json

2023-11-18 07:36 UTC, ChuijkYahus commented on projects/1.20/assets/better-archeology/betterarcheology/lang/zh_cn.json
> +  "item.betterarcheology.artifact_shards": "神秘碎片",
```suggestion
  "item.betterarcheology.artifact_shards": "文物碎片",
```

2023-11-18 07:36 UTC, ChuijkYahus commented on projects/1.20/assets/better-archeology/betterarcheology/lang/zh_cn.json
> +  "item.betterarcheology.identified_artifact": "已鉴定的神秘物品",
```suggestion
  "item.betterarcheology.unidentified_artifact": "未经鉴定的文物",
  "item.betterarcheology.identified_artifact": "已鉴定的文物",
```

2023-11-18 07:36 UTC, ChuijkYahus commented on projects/1.20/assets/better-archeology/betterarcheology/lang/zh_cn.json
> +  "item.betterarcheology.bomb": "生锈的炸弹",
```suggestion
  "item.betterarcheology.bomb": "锈蚀炸弹",
```

2023-11-18 07:36 UTC, ChuijkYahus commented on projects/1.20/assets/better-archeology/betterarcheology/lang/zh_cn.json
> +  "item.betterarcheology.tunneling_tooltip": "挖掘方块下面的方块"
```suggestion
  "enchantment.betterarcheology.penetrating_strike": "穿刺打击",
  "item.betterarcheology.penetrating_strike_tooltip": "攻击时可无视保护魔咒的部分效果",
  "enchantment.betterarcheology.seas_bounty": "海之馈赠",
  "item.betterarcheology.seas_bounty_tooltip": "在海洋深处可获得更多种类的宝藏",
  "enchantment.betterarcheology.soaring_winds": "借风",
  "item.betterarcheology.soaring_winds_tooltip": "使用鞘翅时可利用风力获得初始加速",
  "enchantment.betterarcheology.tunneling": "开掘",
  "item.betterarcheology.tunneling_tooltip": "破坏方块时会连带破坏下方的一些方块"
```

2023-11-18 07:36 UTC, ChuijkYahus commented on projects/1.20/assets/better-archeology/betterarcheology/lang/zh_cn.json
> +  "advancements.artifact.description": "用碎片制作一件未知的神秘物品。现在开始鉴定吧！",
```suggestion
  "advancements.artifact.description": "使用文物碎片合成未经鉴定的文物，现在开始鉴定吧！",
```

2023-11-18 07:36 UTC, ChuijkYahus commented on projects/1.20/assets/better-archeology/betterarcheology/lang/zh_cn.json
> +  "advancements.vase.description": "通过打破花瓶获得战利品",
```suggestion
  "advancements.vase": "击碎成功",
  "advancements.vase.description": "打碎花瓶以获得战利品",
```

2023-11-18 07:36 UTC, ChuijkYahus commented on projects/1.20/assets/better-archeology/betterarcheology/lang/zh_cn.json
> +  "advancements.all_fossils_found": "古生物学家的骄傲",
```suggestion
  "advancements.all_fossils_found": "古生物学家的荣耀",
```

2023-11-18 10:13 UTC, ChuijkYahus requested changes
建议不要频繁request review

2023-11-18 10:13 UTC, ChuijkYahus commented on projects/1.20/assets/better-archeology/betterarcheology/lang/zh_cn.json
> +  "block.betterarcheology.rotten_slab": "腐朽台阶",
```suggestion
  "block.betterarcheology.rotten_slab": "腐朽木台阶",
```

2023-11-23 07:27 UTC, TUsama commented
有一处地方需要修改，已经把该处的review unresolve 了，更改后就merge

2023-11-26 13:40 UTC, TUsama approved these changes

2023-11-26 13:57 UTC, TUsama commented
按照他们现在的工作流，可能是第二天早上才上传新资源包吧。

2023-11-26 14:49 UTC, ChuijkYahus approved these changes

2023-11-27 17:39 UTC, merged