Slimy Stuff翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3920
Opened 2023-11-14 11:56 UTC by Tibsalta-IC

2023-11-18 05:36 UTC, ChuijkYahus commented
/sort-keys projects/1.20/assets/slimy-stuff/slimy_stuff/lang/en_us.json
/sort-keys projects/1.20/assets/slimy-stuff/slimy_stuff/lang/zh_cn.json

2023-11-18 05:42 UTC, ChuijkYahus requested changes
请注意，除生物名使用`史莱姆`外，其余推荐使用`黏液`
见原版`史莱姆`/`Slime`以及`黏液球`/`Slime Ball`之间的区别

2023-11-18 05:42 UTC, ChuijkYahus commented on projects/1.20/assets/slimy-stuff/slimy_stuff/lang/zh_cn.json
> +  "block.slimy_stuff.jug_bubble_coral": "泡泡珊瑚罐子",
```suggestion
  "block.slimy_stuff.jug_bubble_coral": "气泡珊瑚罐子",
```
参见原版名称

2023-11-18 05:42 UTC, ChuijkYahus commented on projects/1.20/assets/slimy-stuff/slimy_stuff/lang/zh_cn.json
> +  "block.slimy_stuff.jug_fire_coral": "火纹珊瑚罐子",
```suggestion
  "block.slimy_stuff.jug_fire_coral": "火珊瑚罐子",
```

2023-11-18 05:42 UTC, ChuijkYahus commented on projects/1.20/assets/slimy-stuff/slimy_stuff/lang/zh_cn.json
> +  "item.slimy_lands.suspicious_jam_blindness_1": "可疑果酱",
```suggestion
  "item.slimy_lands.suspicious_jam_blindness_1": "谜之果酱",
```
参见原版`谜之炖菜`/`Suspicious Stew`，请全文修改

2023-11-18 05:42 UTC, ChuijkYahus commented on projects/1.20/assets/slimy-stuff/slimy_stuff/lang/zh_cn.json
> +  "item_group.slimy_stuff.slimy_lands_tab": "史莱姆小玩意",
确定模组名要翻译为这个吗

2023-11-18 05:42 UTC, ChuijkYahus commented on projects/1.20/assets/slimy-stuff/slimy_stuff/lang/zh_cn.json
> +  "item.slimy_lands.slimy_leggings": "史莱姆绑腿",
```suggestion
  "item.slimy_lands.slimy_leggings": "史莱姆护腿",
```
注意原版术语

2023-11-18 06:29 UTC, Tibsalta-IC commented on projects/1.20/assets/slimy-stuff/slimy_stuff/lang/zh_cn.json
> +  "item_group.slimy_stuff.slimy_lands_tab": "史莱姆小玩意",
史莱姆实用物品感觉正式一点

2023-11-18 06:58 UTC, ChuijkYahus requested changes
还是这句
请注意，除生物名使用`史莱姆`外，其余推荐使用`黏液`
见原版`史莱姆`/`Slime`以及`黏液球`/`Slime Ball`之间的区别

推荐查看https://zh.minecraft.wiki/

2023-11-18 06:58 UTC, ChuijkYahus commented on projects/1.20/assets/slimy-stuff/slimy_stuff/lang/zh_cn.json
> +  "block.slimy_stuff.jug_brain_coral": "脑珊瑚罐子",
```suggestion
  "block.slimy_stuff.jug_brain_coral": "脑纹珊瑚罐子",
```

2023-11-18 06:58 UTC, ChuijkYahus commented on projects/1.20/assets/slimy-stuff/slimy_stuff/lang/zh_cn.json
> +  "block.slimy_stuff.jug_horn_coral": "角珊瑚罐子",
```suggestion
  "block.slimy_stuff.jug_horn_coral": "鹿角珊瑚罐子",
```

2023-11-18 10:12 UTC, ChuijkYahus requested changes
我的建议是，与原版的用法统一

2023-11-18 10:12 UTC, ChuijkYahus commented on projects/1.20/assets/slimy-stuff/slimy_stuff/lang/zh_cn.json
> +  "item.slimy_stuff.ender_gum_leggings": "§d末影胶质绑腿",
```suggestion
  "item.slimy_stuff.ender_gum_leggings": "§d末影胶质护腿",
```
建议提出的suggestion全文通查

2023-11-18 10:12 UTC, ChuijkYahus commented on projects/1.20/assets/slimy-stuff/slimy_stuff/lang/zh_cn.json
> +  "item.slimy_stuff.slimy_hammer": "史莱姆锤子 ",
```suggestion
  "item.slimy_stuff.slimy_hammer": "史莱姆锤子",
```

2023-11-18 10:12 UTC, ChuijkYahus commented on projects/1.20/assets/slimy-stuff/slimy_stuff/lang/zh_cn.json
> +  "itemGroup.tabslimy_lands_tab": "史莱姆质"
确定模组名翻译成这个吗

2023-11-25 16:15 UTC, ChuijkYahus commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@Tibsalta-IC

2023-12-01 17:42 UTC, ChuijkYahus commented
- 该提交由于[7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)将被关闭，请知晓。若仍想维护可选择Reopen此提交或重新打开新提交，并查看本提交内的审查意见并进行更改。

@Tibsalta-IC

2023-12-02 20:06 UTC, closed without merging