Risk of Rain Mod 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3925
Opened 2023-11-15 07:39 UTC by CSOLYOO

由 CFPA-Helper 提交。

2023-11-15 07:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3925) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3925) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3925) it.</sub>

2023-11-18 04:39 UTC, ChuijkYahus commented
请注意签署CLA协议，否则PR无法合并

@CSOLYOO

2023-11-18 04:56 UTC, luoxueyasha requested changes

2023-11-18 04:56 UTC, luoxueyasha commented on projects/1.20/assets/riskofrainmod/riskofrain_mobs/lang/zh_cn.json
> +  "message.riskofrain_mobs.not_gold": "NOT GOLD!"
未翻译

2023-11-18 09:36 UTC, Cactusstudent commented
> 请注意签署CLA协议，否则PR无法合并

未签CLA的情况用的是“需要作者操作”

2023-12-13 23:23 UTC, luoxueyasha commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@CSOLYOO

2023-12-22 08:08 UTC, closed without merging