Main
CFPAOrg/Minecraft-Mod-Language-Package pull request #3930
Opened 2023-11-18 15:25 UTC by mlbhc

2023-11-19 00:28 UTC, luoxueyasha commented
豆腐官汉有 射命丸政（@0999312 ）接手，建议先和那边沟通，再考虑要不要投过来

2023-11-26 06:06 UTC, mlbhc commented
上周就发了邮件但没有收到回复,我也没有办法

2023-11-26 06:26 UTC, luoxueyasha commented
建议直接b站或者qq找过去（？

2023-11-27 09:04 UTC, baguchan commented
I heard you guys are working on a Chinese pullrequest for tofucraftreload
(sorry for english)

2023-11-27 09:16 UTC, mlbhc commented
> I heard you guys are working on a Chinese pullrequest for tofucraftreload (sorry for english) As the current author of Tofu Craft Reload, is there anything I can do to help?
They said TofuCraftReload have an official Chinese translator
If I want pullrequest should I ask his permission?

2023-11-27 09:18 UTC, mlbhc commented
> I heard you guys are working on a Chinese pullrequest for tofucraftreload (sorry for english) As the current stuff of Tofu Craft Reload, is there anything I can do to help?

They said TofuCraftReload have an official Chinese translator
If I want pullrequest should I ask his permission?

2023-11-27 09:25 UTC, baguchan commented
> They said TofuCraftReload have an official Chinese translator If I want pullrequest should I ask his permission?

no need permission! go ahead!
Also, Mr.射命丸政 is currently entrusting the development to me.

2023-11-27 10:36 UTC, luoxueyasha commented
So as @baguchan replied, this pull request will sooooooon be reviewed.
既然豆腐（原&现）作者baguchan回复了，这边也会尽快开始对应的review工作。

虽然我们更推荐直接投官库，无论是对接也好审核周期也好，那边都会更方便一些。

2023-11-27 10:58 UTC, luoxueyasha requested changes

2023-11-27 10:58 UTC, luoxueyasha commented on projects/1.20/assets/tofucraftreload/tofucraft/lang/zh_cn.json
> +  "advancements.tofucraft.sniffed_revenge.description": "为了报复嗅觉灵敏的监守者,把辣椒扔向它吧！",
```suggestion
  "advancements.tofucraft.sniffed_revenge.description": "为了报复嗅觉灵敏的监守者，把辣椒扔向它吧！",
```
我们遵循《标点符号规范》，需要全文使用中文全角符号。
https://cfpa.site/TransRules/
此类问题请全文通查

2023-11-27 11:47 UTC, luoxueyasha requested changes

2023-11-27 11:47 UTC, luoxueyasha commented on projects/1.20/assets/tofucraftreload/tofucraft/lang/zh_cn.json
> +  "itemGroup.tofucraft.tofu_foods.main_tab" : "豆腐工艺:食物",
请仔细阅读《[翻译规范与指南](https://cfpa.site/TransRules/)》，这些相关规范与资料库在我们的readme和CONTRIBUTING里都有介绍

对于创造模式物品栏分栏，我们一般使用`丨`（汉字，gun3）进行分割
如果没有特殊情况，此类问题请全文通查

```suggestion
  "itemGroup.tofucraft.tofu_foods.main_tab" : "豆腐工艺丨食物",
```

2023-11-30 03:10 UTC, luoxueyasha commented
我最近加班，没时间，并且不要总是request review
可以去qq群里喊一声，找一下其他有空的审核

2023-11-30 03:18 UTC, closed without merging

2023-11-30 03:19 UTC, mlbhc commented
投官库了