Ars Nouveau - Extended Glyphs 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3936
Opened 2023-11-19 14:05 UTC by ChuijkYahus

2023-11-25 14:15 UTC, dovisutu commented on projects/1.19/assets/ars-nouveau-extended-glyphs/ars_extended_glyphs/lang/zh_cn.json
> +	"ars_extended_glyphs.glyph_desc.glyph_saturate": "给予目标饥饿值和饱和度。强化可给予更多饱和度。",
`hunger satuation`会不会就是`satuation`？还是说实测如此？

2023-11-25 14:15 UTC, dovisutu commented on projects/1.19/assets/ars-nouveau-extended-glyphs/ars_extended_glyphs/lang/zh_cn.json
> +	"ars_extended_glyphs.glyph_desc.glyph_returnhome": "将受影响的玩家传送回他们的重生点。对其他生物和为设置过重生点的玩家无效。",
```suggestion
	"ars_extended_glyphs.glyph_desc.glyph_returnhome": "将受影响的玩家传送回他们的重生点。对其他生物和未设置过重生点的玩家无效。",
```

2023-11-25 16:12 UTC, ChuijkYahus commented on projects/1.19/assets/ars-nouveau-extended-glyphs/ars_extended_glyphs/lang/zh_cn.json
> +	"ars_extended_glyphs.glyph_desc.glyph_saturate": "给予目标饥饿值和饱和度。强化可给予更多饱和度。",
```suggestion
	"ars_extended_glyphs.glyph_desc.glyph_saturate": "给予目标饱和度。强化可给予更多饱和度。",
```

2024-03-31 13:18 UTC, SlimeSB approved these changes
修改后同意合并

2024-03-31 13:18 UTC, SlimeSB commented on projects/1.19/assets/ars-nouveau-extended-glyphs/ars_extended_glyphs/lang/zh_cn.json
> +	"ars_extended_glyphs.glyph_desc.glyph_summonhostile": "召唤三个常见敌对生物。强化或抑制两次后可改变召唤的数量。以极端增强会生成苦力怕，以敏感增强会减少少见生物的生成量。",
```suggestion
	"ars_extended_glyphs.glyph_desc.glyph_summonhostile": "召唤三个常见敌对生物。召唤的数量可被强化或抑制两次。以极端增强会生成苦力怕，以敏感增强会减少罕见生物的生成率。",

```
我没进游戏看。我现在弄新生魔艺所以把既往的pr弄了。

2024-03-31 13:18 UTC, SlimeSB commented on projects/1.19/assets/ars-nouveau-extended-glyphs/ars_extended_glyphs/lang/zh_cn.json
> +	"tooltip.aeg.tablet_f.earth": "装备时会消耗魔力抵消窒息、鞘翅动能，以及地表灼热造成的伤害。",
```suggestion
	"tooltip.aeg.tablet_f.earth": "装备时会消耗魔力抵消窒息、鞘翅动能，以及灼热方块造成的伤害。",

```
指的大概是岩浆块，我不确定营火能否伤害。

2024-03-31 13:56 UTC, ChuijkYahus commented on projects/1.19/assets/ars-nouveau-extended-glyphs/ars_extended_glyphs/lang/zh_cn.json
> +	"ars_extended_glyphs.glyph_desc.glyph_summonhostile": "召唤三个常见敌对生物。强化或抑制两次后可改变召唤的数量。以极端增强会生成苦力怕，以敏感增强会减少少见生物的生成量。",
```suggestion
	"ars_extended_glyphs.glyph_desc.glyph_summonhostile": "召唤三个常见敌对生物。召唤的数量可被强化或抑制两次。以极端增强会生成苦力怕，以敏感增强会减少少见生物的生成量。",
```
![MO7W(NSCGV8W3 G7N~F$AC9](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/177e7476-170a-4e1a-a745-e0d6a35e6d77)
`少见`是故意的，库内之前也做过一次`罕见`到`少见`的改动，不过确实是很久之前的了

2024-03-31 14:05 UTC, ChuijkYahus commented on projects/1.19/assets/ars-nouveau-extended-glyphs/ars_extended_glyphs/lang/zh_cn.json
> +	"tooltip.aeg.tablet_f.earth": "装备时会消耗魔力抵消窒息、鞘翅动能，以及地表灼热造成的伤害。",
营火不防

2024-03-31 14:50 UTC, SlimeSB commented on projects/1.19/assets/ars-nouveau-extended-glyphs/ars_extended_glyphs/lang/zh_cn.json
> +	"ars_extended_glyphs.glyph_desc.glyph_summonhostile": "召唤三个常见敌对生物。强化或抑制两次后可改变召唤的数量。以极端增强会生成苦力怕，以敏感增强会减少少见生物的生成量。",
同意

2024-04-13 13:34 UTC, SlimeSB approved these changes

2024-04-23 13:42 UTC, SlimeSB commented
还是给描述中所提到的魔符加一下引号吧。包括先前的

2024-04-24 11:51 UTC, SlimeSB requested changes

2024-04-24 11:51 UTC, SlimeSB commented on projects/1.19/assets/ars-nouveau-extended-glyphs/ars_extended_glyphs/lang/zh_cn.json
> +	"ars_extended_glyphs.glyph_desc.glyph_atrophy": "致使目标受到一定时间的虚弱。",
```suggestion
	"ars_extended_glyphs.glyph_desc.glyph_atrophy": "使目标受到一段时间的虚弱效果。",

```

2024-04-24 11:51 UTC, SlimeSB commented on projects/1.19/assets/ars-nouveau-extended-glyphs/ars_extended_glyphs/lang/zh_cn.json
> +	"ars_extended_glyphs.ritual_desc.ritual_difficulty_increase": "将世界难度提升一级。使用羽毛增强可换为降低。",
```suggestion
	"ars_extended_glyphs.ritual_desc.ritual_difficulty_increase": "将世界难度提升一级。使用“羽毛”增强可换为降低。",

```
我不清楚是不是魔符

2024-04-24 11:51 UTC, SlimeSB commented on projects/1.20/assets/ars-nouveau-extended-glyphs/ars_extended_glyphs/lang/zh_cn.json
> +	"ars_extended_glyphs.glyph_desc.glyph_atrophy": "致使目标受到一定时间的虚弱。",
```suggestion
	"ars_extended_glyphs.glyph_desc.glyph_atrophy": 使目标受到一段时间的虚弱效果。",

```

2024-04-24 11:51 UTC, SlimeSB commented on projects/1.20/assets/ars-nouveau-extended-glyphs/ars_extended_glyphs/lang/zh_cn.json
> +	"ars_extended_glyphs.ritual_desc.ritual_difficulty_increase": "将世界难度提升一级。使用羽毛增强可换为降低。",
```suggestion
	"ars_extended_glyphs.ritual_desc.ritual_difficulty_increase": "将世界难度提升一级。使用“羽毛”增强可换为降低。",

```
如果上面改了这里同意就好了

2024-04-25 14:37 UTC, ChuijkYahus commented on projects/1.19/assets/ars-nouveau-extended-glyphs/ars_extended_glyphs/lang/zh_cn.json
> +	"ars_extended_glyphs.ritual_desc.ritual_difficulty_increase": "将世界难度提升一级。使用羽毛增强可换为降低。",
羽毛物品

2024-04-26 06:51 UTC, SlimeSB approved these changes

2024-04-27 09:07 UTC, merged