Ex-deourum 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3937
Opened 2023-11-20 13:21 UTC by WQMYH

2023-11-20 13:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3937) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3937) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3937) it.</sub>

2023-11-20 14:06 UTC, luoxueyasha commented
若想提交翻译、贡献代码，请**仔细**阅读[贡献方针](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)。

请根据贡献方针逐一进行以下操作：
* 修改PR标题
* 更改文件路径
* 签署CLA
* 将缩成一行的语言文件展开为原格式
* 修复机翻痕迹和错译

2023-11-20 14:39 UTC, CoalGlage commented on projects/1.20/assets/exdeorum/lang/zh_cn.json
> +{"advancements.exdeorum.core.barrel.description":"使用木桶将有机物料堆肥成泥土","advancements.exdeorum.core.barrel.title":"那是绿色垃圾","advancements.exdeorum.core.crook.description":"制作一个钩子，用它从树叶上收获更多的树苗，更重要的是获得蚕！（蚕可以
在VSCode里，Shift+Alt+F可以快速将文件格式化。也就是能让这一大坨东西转变成一个对眼睛更友好（？）的形式。
键"advancements.exdeorum.core.crook.description"和"advancements.exdeorum.core.string_mesh.description"这两处有不属于原文的内容，是怎么回事？此外后者译文末的括号部分应考虑删去，如果是吐槽的话可以发在这边的评论区里。
最后，
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/117024879/504578e9-1916-4f5a-afd7-a4e53f0decf7)
不知道你那里有没有收到过这样的提示，如果有也可以改一下。

2023-11-20 14:39 UTC, CoalGlage commented on projects/1.20/assets/exdeorum/lang/en_us.json
> +{"advancements.exdeorum.core.barrel.description":"Use a barrel to compost organic material into dirt","advancements.exdeorum.core.barrel.title":"That Goes in the GreenWaste","advancements.exdeorum.co
键"advancements.exdeorum.core。silk_worm.title"和"advancements.exdeorum.core.string_mesh。description"
为什么键名和键值里会出现中文字符啊...（）

2023-11-21 03:35 UTC, WQMYH commented on projects/1.20/assets/exdeorum/lang/zh_cn.json
> +{"advancements.exdeorum.core.barrel.description":"使用木桶将有机物料堆肥成泥土","advancements.exdeorum.core.barrel.title":"那是绿色垃圾","advancements.exdeorum.core.crook.description":"制作一个钩子，用它从树叶上收获更多的树苗，更重要的是获得蚕！（蚕可以
哦哦，这是我对一个整合包的补充汉化哈哈哈，然后就是源代码就是这样的，我以为那个要求里的保留原样是这个意思哈哈哈。最后不属于原文的可能是我忘删了，因为我是为了我朋友翻译的，想要让他更好的理解，，，然后发现汉化包里没有就跑来上传哩，可能忘记删掉了，OK，我改一下。

2023-11-21 03:37 UTC, WQMYH commented on projects/1.20/assets/exdeorum/lang/zh_cn.json
> +{"advancements.exdeorum.core.barrel.description":"使用木桶将有机物料堆肥成泥土","advancements.exdeorum.core.barrel.title":"那是绿色垃圾","advancements.exdeorum.core.crook.description":"制作一个钩子，用它从树叶上收获更多的树苗，更重要的是获得蚕！（蚕可以
这个提示没有收到诶，我没看到。

2023-11-21 03:40 UTC, WQMYH commented on projects/1.20/assets/exdeorum/lang/zh_cn.json
> +{"advancements.exdeorum.core.barrel.description":"使用木桶将有机物料堆肥成泥土","advancements.exdeorum.core.barrel.title":"那是绿色垃圾","advancements.exdeorum.core.crook.description":"制作一个钩子，用它从树叶上收获更多的树苗，更重要的是获得蚕！（蚕可以
我才发现，我把巫水翻成了核污水，可以保留不🤣

2023-11-21 04:36 UTC, WQMYH commented
> 在VSCode里，Shift+Alt+F可以快速将文件格式化。也就是能让这一大坨东西转变成一个对眼睛更友好（？）的形式。
键"advancements.exdeorum.core.crook.description"和"advancements.exdeorum.core.string_mesh.description"这两处有不属于原文的内容，是怎么回事？此外后者译文末的括号部分应考虑删去，如果是吐槽的话可以发在这边的评论区里。
最后，
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/117024879/504578e9-1916-4f5a-afd7-a4e53f0decf7)
不知道你那里有没有收到过这样的提示，如果有也可以改一下。 

为什么我修改不了我的pull request？？？出了啥问题吗。。。没有提交按钮啊。。。

2023-11-21 04:49 UTC, CoalGlage commented
> > 在VSCode里，Shift+Alt+F可以快速将文件格式化。也就是能让这一大坨东西转变成一个对眼睛更友好（？）的形式。
> > 键"advancements.exdeorum.core.crook.description"和"advancements.exdeorum.core.string_mesh.description"这两处有不属于原文的内容，是怎么回事？此外后者译文末的括号部分应考虑删去，如果是吐槽的话可以发在这边的评论区里。
> > 最后，
> > ![image](https://user-images.githubusercontent.com/117024879/284296895-504578e9-1916-4f5a-afd7-a4e53f0decf7.png)
> > 不知道你那里有没有收到过这样的提示，如果有也可以改一下。
> 
> 为什么我修改不了我的pull request？？？出了啥问题吗。。。没有提交按钮啊。。。

你提交了commit就行...然后pr页面里摁句号键能打开网页编辑器。

2023-11-21 04:50 UTC, WQMYH commented
>  

要不我还是新建一个吧。。。

2023-11-21 04:50 UTC, WQMYH commented
> 在VSCode里，Shift+Alt+F可以快速将文件格式化。也就是能让这一大坨东西转变成一个对眼睛更友好（？）的形式。
键"advancements.exdeorum.core.crook.description"和"advancements.exdeorum.core.string_mesh.description"这两处有不属于原文的内容，是怎么回事？此外后者译文末的括号部分应考虑删去，如果是吐槽的话可以发在这边的评论区里。
最后，
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/117024879/504578e9-1916-4f5a-afd7-a4e53f0decf7)
不知道你那里有没有收到过这样的提示，如果有也可以改一下。 

要不我还是新建一个吧。。。

2023-11-21 04:52 UTC, CoalGlage commented
> > 
> 
> 要不我还是新建一个吧。。。

那啥，仓库主页是有教程的，你可以看一下。其中视频教程的内容有一部分是过期了的。

2023-11-21 04:56 UTC, WQMYH commented
> > > 
> > 
> > 
> > 要不我还是新建一个吧。。。
> 
> 那啥，仓库主页是有教程的，你可以看一下。其中视频教程的内容有一部分是过期了的。

视频吗？已经看过了，但是改不了，，，不知道是啥问题，，，不能提交

2023-11-21 05:09 UTC, WQMYH commented
> > > 
> > 
> > 
> > 要不我还是新建一个吧。。。
> 
> 那啥，仓库主页是有教程的，你可以看一下。其中视频教程的内容有一部分是过期了的。

不知道发生了什么，，，好像又好了。。。🤦‍♂️

2023-11-21 05:26 UTC, luoxueyasha commented
请修改PR标题为形如“模组英文名 翻译提交”的格式，可以参考其他pr

2023-11-21 05:39 UTC, CoalGlage commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.silk_worm.description": "获得一个蚕，然后用它感染一棵树，得到线",
```suggestion
    "advancements.exdeorum.core.silk_worm.description": "获得一个蚕，然后让它寄生在一棵树上来得到线",
```

2023-11-21 05:39 UTC, CoalGlage commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.string_mesh.description": "制作一个线网，将它放在筛子上以使用。",
```suggestion
    "advancements.exdeorum.core.string_mesh.description": "制作一个用于筛子上的线网。",
```
`string mesh`这个是怎么用于`sieve`的？

2023-11-21 05:39 UTC, CoalGlage commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "block.exdeorum.acacia_crucible": "金合欢坩埚",
```suggestion
    "block.exdeorum.acacia_crucible": "金合欢木坩埚",
```
下行同。

2023-11-21 05:39 UTC, CoalGlage commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "info.exdeorum.sculk_core": "用一个幽匿核心在一个幽匿尖啸者上，可以使其能够生成守卫者。通常，玩家放置的幽匿尖啸者无法生成守卫者，所以这个物品对于在空岛世界中获取幽匿物品很有用。",
这里的确定是`守卫者`而不是`坚守者`？

2023-11-21 05:40 UTC, CoalGlage commented on projects/1.20/assets/exdeorum/lang/zh_cn.json
> +{"advancements.exdeorum.core.barrel.description":"使用木桶将有机物料堆肥成泥土","advancements.exdeorum.core.barrel.title":"那是绿色垃圾","advancements.exdeorum.core.crook.description":"制作一个钩子，用它从树叶上收获更多的树苗，更重要的是获得蚕！（蚕可以
> 我才发现，我把巫水翻成了核污水，可以保留不🤣

emmmmm 你还是改一下吧（

2023-11-21 05:44 UTC, luoxueyasha requested changes
看到L10，建议自己全文通查一遍

2023-11-21 05:44 UTC, luoxueyasha commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.crook.description": "制作一个钩子，用它从树叶上收获更多的树苗。",
```suggestion
    "advancements.exdeorum.core.crook.description": "合成一把钩子，用它从树叶上收获更多的树苗。",
```
craft 必须翻译为合成

原文存在 double sapling drops，实际游戏内容是双倍掉落概率还是双倍掉落？

2023-11-21 05:44 UTC, luoxueyasha commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.crook.title": "给他钩子",
俚语双关，还有解雇某人的意思

2023-11-21 05:44 UTC, luoxueyasha commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.root.description": "在虚空世界中诞生，眼前只有一座小岛",
这条在游戏中的出现位置？
感觉直译出来没这么诗意

2023-11-21 05:44 UTC, luoxueyasha commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.root.title": "别往下看...",
```suggestion
    "advancements.exdeorum.core.root.title": "别往下看……",
```
请遵守标点符号用法

2023-11-21 05:44 UTC, luoxueyasha commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.silk_worm.description": "获得一个蚕，然后用它感染一棵树，得到线",
```suggestion
    "advancements.exdeorum.core.silk_worm.description": "获得一只蚕，然后用它感染一棵树，以获得线",
```

2023-11-21 05:44 UTC, luoxueyasha commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.string_mesh.description": "制作一个线网，将它放在筛子上以使用。",
```suggestion
    "advancements.exdeorum.core.string_mesh.description": "合成一张筛子用的线网",
```

```suggestion
    "advancements.exdeorum.core.string_mesh.description": "合成一张用在筛子上的线网",
```


`string mesh`库里（或者以前版本的无中生有）有其他译法吗
语序优化详见[维基百科：翻译腔](https://zh.m.wikipedia.org/wiki/Wikipedia:%E7%BF%BB%E8%AF%91%E8%85%94)，请全文通查
句末是否加标点请保持全文一致，请全文通查

2023-11-21 05:46 UTC, WQMYH commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.string_mesh.description": "制作一个线网，将它放在筛子上以使用。",
呃，不是说了放在筛子上。。还是说要写用右键放在？

2023-11-21 05:47 UTC, WQMYH commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.crook.description": "制作一个钩子，用它从树叶上收获更多的树苗。",
我自己玩的时候感觉是双倍掉落概率所以翻译成了收获更多的树苗

2023-11-21 05:49 UTC, WQMYH commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.crook.title": "给他钩子",
不清楚，我是在任务里看到的这句话，，，所以我就直接翻译成给他一个钩子。。。

2023-11-21 05:50 UTC, WQMYH commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.root.description": "在虚空世界中诞生，眼前只有一座小岛",
我一开始翻译的是生于虚空，，，但是后来要提交好像是说要尊重原文，，，我就给他直译了

2023-11-21 05:50 UTC, WQMYH commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.root.title": "别往下看...",
呃，不是省略号吗？

2023-11-21 05:53 UTC, CoalGlage commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.string_mesh.description": "制作一个线网，将它放在筛子上以使用。",
我是说，是用于合成/铁砧，还是右键使用

2023-11-21 05:53 UTC, WQMYH commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.silk_worm.description": "获得一个蚕，然后用它感染一棵树，得到线",
呃，我是觉得寄生太可怕而且真正的寄生应该是基于树体的吧，，，与其说是寄生更像是在一种感染可以在树叶上繁殖的那种，而且无中生有里好像就是翻译成了感染？

2023-11-21 05:54 UTC, WQMYH commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.silk_worm.description": "获得一个蚕，然后用它感染一棵树，得到线",
应该是感染，，，我打开1.16.5看看

2023-11-21 05:55 UTC, WQMYH commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.string_mesh.description": "制作一个线网，将它放在筛子上以使用。",
ok，我写清楚点。

2023-11-21 05:56 UTC, CoalGlage commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.silk_worm.description": "获得一个蚕，然后用它感染一棵树，得到线",
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/117024879/7dca6c22-ec42-404d-b868-c4832a137e59)
infest with的意思貌似是寄生。

2023-11-21 05:56 UTC, WQMYH commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.string_mesh.description": "制作一个线网，将它放在筛子上以使用。",
翻译的是丝网，，，我自己用在整合包里用的是丝网没想到昨天上传的是之前的版本，，，

2023-11-21 05:57 UTC, WQMYH commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "block.exdeorum.acacia_crucible": "金合欢坩埚",
主要是太长了，，，而且我觉得叫这个挺好的，，，哈哈哈

2023-11-21 05:57 UTC, ChuijkYahus commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.root.title": "别往下看...",
用中文省略号

2023-11-21 06:00 UTC, ChuijkYahus commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "block.exdeorum.jacaranda_crucible": "蓝花楹坩埚",
```suggestion
    "block.exdeorum.jacaranda_crucible": "蓝花楹木坩埚",
```

2023-11-21 06:00 UTC, WQMYH commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.string_mesh.description": "制作一个线网，将它放在筛子上以使用。",
呃，确实有的时候记得，有的时候不记得，，，而且我都是按照平常说话的习惯翻的，，，这么严格的吗，，，

2023-11-21 06:01 UTC, WQMYH commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "block.exdeorum.acacia_crucible": "金合欢坩埚",
OK，第一次上传翻译，，，不太清楚哈哈哈。

2023-11-21 06:02 UTC, WQMYH commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "block.exdeorum.cherry_sieve": "樱桃木筛子",
啊？啥意思？我应该提交的就是这个哇。

2023-11-21 06:03 UTC, qznfbnj commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "info.exdeorum.sculk_core": "用一个幽匿核心在一个幽匿尖啸者上，可以使其能够生成守卫者。通常，玩家放置的幽匿尖啸者无法生成守卫者，所以这个物品对于在空岛世界中获取幽匿物品很有用。",
是 [`监守者`](https://zh.minecraft.wiki/w/%E7%9B%91%E5%AE%88%E8%80%85) 啦不是 `坚守者`

2023-11-21 06:03 UTC, WQMYH commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "block.exdeorum.jungle_sieve": "丛林筛子",
啊，这些我没有提交吗？？？我github又出问题了，，，

2023-11-21 06:03 UTC, ChuijkYahus commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "block.exdeorum.cherry_sieve": "樱桃木筛子",
![ZV $B5)}J8U$V2~)BY66XW6](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/09096abe-e921-4300-996b-601c3b3f259c)
https://zh.minecraft.wiki/w/%E5%8E%9F%E6%9C%A8?variant=zh-cn
原版用语，建议多看wiki

2023-11-21 06:04 UTC, WQMYH commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "block.exdeorum.mangrove_sieve": "红树筛子",
我再提交一遍看看。

2023-11-21 06:06 UTC, WQMYH commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "info.exdeorum.sculk_core": "用一个幽匿核心在一个幽匿尖啸者上，可以使其能够生成守卫者。通常，玩家放置的幽匿尖啸者无法生成守卫者，所以这个物品对于在空岛世界中获取幽匿物品很有用。",
我也不太确定，因为之前在游戏里试的时候啥也没发生。。。消耗了物品发出了尖叫然后就没了。

2023-11-21 06:08 UTC, WQMYH commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.root.title": "别往下看...",
呃，哦，哈哈，我平常都是这样打省略号的

2023-11-21 06:21 UTC, WQMYH commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.silk_worm.description": "获得一个蚕，然后用它感染一棵树，得到线",
![0M1RME_VG9J2W@VXI46(KTK](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/138088516/7a870544-d5b2-44d9-a531-85854c48e0af)
![K5VKA5F$H$C61}1L9% ` %N](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/138088516/667468e2-0dc1-4612-8e20-126cab1738be)
呃，我看牛津应该是侵染，侵扰，大批出现，要不翻译成侵染？

2023-11-21 06:23 UTC, ChuijkYahus commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.silk_worm.description": "获得一个蚕，然后用它感染一棵树，得到线",
遵循exnihilo本体即可

2023-11-21 06:25 UTC, WQMYH commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "block.exdeorum.cherry_sieve": "樱桃木筛子",
我知道呀，，，有些我以为可以按照比较简单的方式翻译哈哈，下次注意。。。而且我记得我提交的就是这个，，所以才这么说，，，

2023-11-21 06:26 UTC, WQMYH commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.silk_worm.description": "获得一个蚕，然后用它感染一棵树，得到线",
那就是感染？

2023-11-21 06:27 UTC, WQMYH commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.silk_worm.description": "获得一个蚕，然后用它感染一棵树，得到线",
我在1.16.5看到的都是感染

2023-11-21 06:30 UTC, CoalGlage commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "block.exdeorum.cherry_sieve": "樱桃木筛子",
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/117024879/3b47e0d6-bad5-4d87-b9e6-50f3fbbf3812)

2023-11-21 13:34 UTC, luoxueyasha commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.silk_worm.description": "获得一个蚕，然后用它感染一棵树，得到线",
感染ok

2023-11-21 13:37 UTC, luoxueyasha commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.string_mesh.description": "制作一个线网，将它放在筛子上以使用。",
我们的翻译准则详见[CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)，请一定要认真阅读
有明显的翻译腔痕迹是会被狠狠拷打的

另外查了一下，库里的`string mesh`在exnihilo里（1.12/1.16/1.18）译为`线筛网`

2023-11-21 13:38 UTC, CoalGlage commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "info.exdeorum.sculk_core": "用一个幽匿核心在一个幽匿尖啸者上，可以使其能够生成守卫者。通常，玩家放置的幽匿尖啸者无法生成守卫者，所以这个物品对于在空岛世界中获取幽匿物品很有用。",
Ln 102。刚才看了一眼wiki，应为`幽匿尖啸体`。

2023-11-21 13:45 UTC, luoxueyasha commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.root.description": "在虚空世界中诞生，眼前只有一座小岛",
确实不好直译，但是别离开语义太猛了
原文`Spawn into a SkyBlock void world`
`一睁眼，自己在虚空中的空岛上`
`进入一个SkyBlock虚空世界`
SkyBlock都基本译为空岛了，不过我记得hypixel那边是禁止翻译小游戏名的？具体得看了

2023-11-21 13:56 UTC, luoxueyasha requested changes

2023-11-21 13:56 UTC, luoxueyasha commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.barrel.title": "那些只是绿色废品。",
这条怎么加上句号了
在游戏中的显示位置？需要截图

2023-11-21 13:56 UTC, luoxueyasha commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.silk_worm.description": "你获得了一个蚕，然后用它感染一棵树的树叶，之后等待它滋生以获得线。",
```suggestion
    "advancements.exdeorum.core.silk_worm.description": "获得一只蚕，并用它感染一整颗树的树叶以获得线。",
```

```suggestion
    "advancements.exdeorum.core.silk_worm.description": "获得一只蚕，并用它感染一棵树以获得线。",
```


`一个蚕`不觉得别扭吗
原文没给那么多信息，最好不要加戏
我知道你想给不熟悉exnihilo的玩家做引导，但是咱还是尽量贴着原文走

2023-11-21 13:56 UTC, luoxueyasha commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.string_mesh.title": "所有的小齿轮",
见[这段台词](https://zhidao.baidu.com/question/35439426/answer/123016406.html)
可以考虑找一下有没有院线版译文

2023-11-22 03:52 UTC, WQMYH commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.barrel.title": "那些只是绿色废品。",
是的，一时脑抽，看错地方了，以为这是描述，这个是进度的内容。

2023-11-22 08:11 UTC, luoxueyasha requested changes
我们的[CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)里写到了，我们拒收机械翻译（含gpt等生成式ai）和生硬翻译。
《[翻译规范和指南](https://cfpa.site/TransRules/)》中第一条为“以原文为准”。
我发现您提交的文字有文不对意现象、忽略部分conversation的情况，并怀疑您提交的文字含有gpt生成成分。
请仔细阅读CONTRIBUTING等文档的内容，并修改您的提交内容；否则您的PR可能会被长期搁置甚至强制关闭。

2023-11-22 08:11 UTC, luoxueyasha commented on projects/1.20/assets/ex-deorum/exdeorum/lang/zh_cn.json
> +    "advancements.exdeorum.core.silk_worm.description": "你发现了一只蚕，做好用它感染一棵树的树叶准备，然后获得线！",
请解释原文`Obtain a silk worm, then infest a tree with it to get string`
以及为什么翻成历史这几个版本的理由

2023-11-22 11:06 UTC, closed without merging