Rechiseled: Create 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3951
Opened 2023-11-25 20:31 UTC by QiuShui1012

石质类物品翻译全用的原文，窗户材质也全用的原文。
修饰词基本全是意译，因为不意译就可能跟游戏里大相径庭，看起来会像机翻

由 CFPA-Helper 提交。

2023-11-25 20:34 UTC, QiuShui1012 commented
例如：
![E0D629510EFD383CA3C66BA66B2DA5A2](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/150409561/7a79d9be-d755-4ec2-9ac1-763b1cb06390)
原文：Crushed Rose Quartz
直译：粉碎玫瑰石英
意译：雕刻玫瑰石英块

2023-11-26 03:34 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/rechiseled-create/rechiseledcreate/lang/zh_cn.json
> +  "rechiseledcreate.item_group": "Rechiseled:机械动力",
```suggestion
  "rechiseledcreate.item_group": "Rechiseled：机械动力",
```

2023-11-26 03:39 UTC, ChuijkYahus requested changes
同类译名需统一修改
参见库内Rechiseled的1.20与1.20-fabric版本

2023-11-26 03:39 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/rechiseled-create/rechiseledcreate/lang/zh_cn.json
> +  "rechiseledcreate.block.acacia_window_diagonal_connecting": "斜纹金合欢木窗户",
```suggestion
  "rechiseledcreate.block.acacia_window_diagonal": "对角纹金合欢木窗户",
  "rechiseledcreate.block.acacia_window_diagonal_connecting": "对角纹金合欢木窗户",
```

2023-11-26 03:39 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/rechiseled-create/rechiseledcreate/lang/zh_cn.json
> +  "rechiseledcreate.block.acacia_window_panes_connecting": "金合欢木窗户板方块",
```suggestion
  "rechiseledcreate.block.acacia_window_panes": "金合欢木窗户板",
  "rechiseledcreate.block.acacia_window_panes_connecting": "金合欢木窗户板",
```
方块原文没有，从何而来

2023-11-26 03:39 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/rechiseled-create/rechiseledcreate/lang/zh_cn.json
> +  "rechiseledcreate.block.acacia_window_tiles_connecting": "砖纹金合欢木窗户",
```suggestion
  "rechiseledcreate.block.acacia_window_tiles": "瓦纹金合欢木窗户",
  "rechiseledcreate.block.acacia_window_tiles_connecting": "瓦纹金合欢木窗户",
```
遵照原版对tiles的译法

2023-11-26 03:39 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/rechiseled-create/rechiseledcreate/lang/zh_cn.json
> +  "rechiseledcreate.block.ochrum_cut_small_brick_connecting": "赭金沙小砖块",
```suggestion
  "rechiseledcreate.block.ochrum_cut_polished_connecting": "磨制切制赭金砂",
  "rechiseledcreate.block.ochrum_cut_small_brick_connecting": "赭金砂小砖块",
```

2023-11-26 04:23 UTC, QiuShui1012 commented on projects/1.20-fabric/assets/rechiseled-create/rechiseledcreate/lang/zh_cn.json
> +  "rechiseledcreate.block.acacia_window_panes_connecting": "金合欢木窗户板方块",
但是Create自己就有窗户板了（

2023-11-26 04:27 UTC, QiuShui1012 commented
还是不注意本体导致的（
wssb

2023-11-26 04:53 UTC, ChuijkYahus approved these changes

2023-11-27 10:30 UTC, merged