BetterThanBunnies 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3957
Opened 2023-11-26 11:35 UTC by 771835

2023-11-26 12:53 UTC, ChuijkYahus requested changes

2023-11-26 12:53 UTC, ChuijkYahus commented on projects/1.16-fabric/assets/better-than-bunnies-fabric/betterthanbunnies/lang/zh_cn.json
> +  "config.betterthanbunnies.prop.fancyChance.desc": "兔子穿着衣服的几率，以百分比（0％-100％）为单位。",
```suggestion
  "config.betterthanbunnies.prop.fancyChance.desc": "兔子穿着衣服的几率，以百分比（0%-100%）为单位。",
```
这个用半角百分号会出问题吗

2023-11-27 06:40 UTC, qznfbnj commented on projects/1.16-fabric/assets/better-than-bunnies-fabric/betterthanbunnies/lang/zh_cn.json
> +  "config.betterthanbunnies.prop.fancyChance.desc": "兔子穿着衣服的几率，以百分比（0％-100％）为单位。",
如果是会提示 `Format error` 的话，可以试试 `%%`，我夸克的配置项就是这个错误

2023-11-27 09:20 UTC, 771835 commented on projects/1.16-fabric/assets/better-than-bunnies-fabric/betterthanbunnies/lang/zh_cn.json
> +  "config.betterthanbunnies.prop.fancyChance.desc": "兔子穿着衣服的几率，以百分比（0％-100％）为单位。",
我试试

2023-11-27 09:21 UTC, 771835 commented on projects/1.16-fabric/assets/better-than-bunnies-fabric/betterthanbunnies/lang/zh_cn.json
> +  "config.betterthanbunnies.prop.fancyChance.desc": "兔子穿着衣服的几率，以百分比（0％-100％）为单位。",
我上传错了，fabric1.16没有BetterThanBunnies

2023-11-27 10:28 UTC, ChuijkYahus commented on projects/1.16-fabric/assets/better-than-bunnies-fabric/betterthanbunnies/lang/zh_cn.json
> +  "config.betterthanbunnies.prop.fancyChance.desc": "兔子穿着衣服的几率，以百分比（0％-100％）为单位。",
百分号建议还是不要用全角（）

2023-11-29 09:37 UTC, 771835 commented on projects/1.16-fabric/assets/better-than-bunnies-fabric/betterthanbunnies/lang/zh_cn.json
> +  "config.betterthanbunnies.prop.fancyChance.desc": "兔子穿着衣服的几率，以百分比（0％-100％）为单位。",
我改了

2023-11-29 11:51 UTC, ChuijkYahus approved these changes
确定显示不会出现Format Error就行

2023-12-01 17:40 UTC, merged