[R]提交Born in chaos [生于混沌]模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #3959
Opened 2023-11-27 06:26 UTC by Takiaaa

2023-11-27 06:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3959) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3959) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=3959) it.</sub>

2023-12-14 08:52 UTC, luoxueyasha commented
请将pr标题修改为如“模组英文名 翻译提交”格式，可以参考其他pr是怎么做的

2024-01-10 10:03 UTC, luoxueyasha commented
@Takiaaa 
没 只是人手真的不够
修改pr名称能保证你的pr从列表上起码看着规范一些，能够让审核有审的欲望
如果比较急的话我去拉点人看

2024-02-28 07:02 UTC, Takiaaa reviewed
校正并更新1.2版本内容

2024-03-31 12:26 UTC, SlimeSB requested changes

2024-03-31 12:26 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.armor_plate_from_dark_metal": "暗金属板",
```suggestion
  "item.born_in_chaos_v1.armor_plate_from_dark_metal": "暗金属盔甲板",
```

2024-03-31 12:26 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.bloody_gadfly_spawn_egg": "血腥马蝇刷怪蛋",
如果上面改了这里也要改

2024-03-31 12:26 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.ethereal_spirit": "灵魂",
```suggestion
  "item.born_in_chaos_v1.ethereal_spirit": "永恒灵魂",
```

2024-03-31 12:26 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.felsteed_spawn_egg": "恶魔马刷怪蛋",
```suggestion
  "item.born_in_chaos_v1.felsteed_spawn_egg": "恶魔战马刷怪蛋",
```

2024-03-31 12:26 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.intoxicating_dagger": "§6巫毒匕首",
```suggestion
  "item.born_in_chaos_v1.intoxicating_dagger": "§6淬酒匕首",
```

2024-03-31 12:26 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.intoxicating_decoction": "毒酒",
大概是醉人之酿这样的意思，这样也可以，不要求更改。

2024-03-31 12:26 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.magical_holiday_candy": "§b神圣节日糖果",
打败南瓜领主后给你的，译作神圣不太好。神奇可以，或者蕴魔之类的。

2024-03-31 12:26 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.shy_spirit_spawn_egg": "羞羞幽灵刷怪蛋",
```suggestion
  "item.born_in_chaos_v1.shy_spirit_spawn_egg": "害羞幽灵刷怪蛋",
```

2024-03-31 12:26 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.staffof_magic_arrows": "§6暗血法杖",
原文是魔法箭，译作暗血的理由是？

2024-03-31 12:26 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.spiritual_sword": "§6心灵剑",
灵魂分割之剑？

2024-03-31 12:26 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.thread_on_the_bone": "线骨",
我没看见这个，原文是被捆的骨头，可能译作骨头捆？和上面一样？

2024-03-31 12:26 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.shattered_skull": "头骨",
```suggestion
  "item.born_in_chaos_v1.shattered_skull": "破碎头骨",
```

2024-03-31 12:30 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "block.born_in_chaos_v1.fragile_scorched_boards": "裂纹焦炭木板",
scorched要不要再考虑一下，译作焦木呢

2024-04-01 09:31 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "itemGroup.tabblock_borin_chaos": "生于混沌：方块",
```suggestion
  "itemGroup.tabblock_borin_chaos": "生于混沌丨方块",
```
汉字丨 “滚”音

2024-04-08 14:26 UTC, SlimeSB commented
请于2024.4.14前回复。或者我接管，直接在上面改。

2024-04-08 15:00 UTC, luoxueyasha commented
@Takiaaa 
ping一下

2024-04-08 15:02 UTC, luoxueyasha commented
> 请于2024.4.14前回复。或者我接管，直接在上面改。

这是要走7+7流程还是要直接改？
7+7的话我们有专门的话术和bot工作流

2024-04-08 23:45 UTC, SlimeSB commented
我接管，不关闭。

2024-04-12 03:50 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "block.born_in_chaos_v1.pile_of_skulls": "头骨方块",
头骨方块是自带的翻译，我认为以玩家视角来看这并不是一“堆”而是一“块”，其实这无伤大雅，但头骨是对的，是由头骨合成所以是头骨方块。

2024-04-12 03:57 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "block.born_in_chaos_v1.scarlet_stained_glass": "红色花窗玻璃",
如此一来绿色、黄色、紫色花窗玻璃也需要对称性更换用词，否则就失去了系统性。我不认为这样会让文本更加简洁易懂。

2024-04-12 03:59 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.born_in_chaos_v1.dogtruce": "看在骨头的份上",
喂食骇狼骨头会让骇狼获得一定时间的“对玩家中立”效果，所以是“看在骨头的份上”

2024-04-12 04:01 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.born_in_chaos_v1.fish_breath": "氧气要没了…",
模组中的鱼类离开水后的窒息状态

2024-04-12 04:14 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.born_in_chaos_v1.furious_rampage": "暴怒猖獗",
这部分一直用的是模组自带的翻译，确实没注意

2024-04-12 04:17 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.born_in_chaos_v1.intoxication": "酒中毒",
不是的，这个酒是带有毒性的，所以是酒中毒，而且intoxication有中毒的意思。

2024-04-12 04:21 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.born_in_chaos_v1.soul_stratification": "灵魂出窍",
是这样没错，但它确实是灵魂出窍的意思，分离同样有种灵魂完好脱离躯壳的感觉，如果要改可以改成“灵魂逸散”或“灵魂离析”。

2024-04-12 04:22 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.born_in_chaos_v1.living_bomb": "§a自爆",
用于效果上还是自爆合适，如果用在外物倒是可以用活体炸弹，毕竟活体炸弹是个物

2024-04-12 04:39 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.magic_depletion": "魔法衰减",
有道理

2024-04-12 04:40 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.born_in_chaos_v1.dogtruce": "看在骨头的份上",
> 啥意思啥效果……我没试出来也没找到

喂食骇狼骨头会让骇狼获得一定时间的“对玩家中立”效果，所以是“看在骨头的份上”

2024-04-12 04:41 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.magic_depletion": "魔法衰减",
但衰魔药水和衰魔之箭就不能使用“衰魔”这个名称了，虽然这些东西无法生存获取

2024-04-12 04:47 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "entity.born_in_chaos_v1.controlled_baby_skeleton": "小骷髅",
玩家和骷髅召唤师召唤的

2024-04-12 04:56 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "entity.born_in_chaos_v1.riding_felsteed": "恶魔马",
恶魔马和恶魔战马只是为了区分 伯爵马 与 领主马 的不同，其实他们只是差了领主“lords”这个词，但加上会显得繁杂。而且伯爵马没有“伯爵”二字，会显得……不对称

2024-04-12 05:00 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.armor_plate_from_dark_metal": "暗金属板",
板就足以了，合成而得的材料，用于升级盔甲，如果盔甲板会像盔甲的掉落物。这部分自带的翻译我觉得可以。

2024-04-12 05:02 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.ethereal_spirit": "灵魂",
这是个基础掉落物，“永恒”就太高调了。而且它并不永恒，飘渺差不多，但，这只是个基础掉落物。

2024-04-12 05:05 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.intoxicating_dagger": "§6巫毒匕首",
淬毒比淬酒要好，无论是实际应用还是字面意思。淬毒、巫毒，个人喜好吧。

2024-04-12 05:12 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.magical_holiday_candy": "§b神圣节日糖果",
有道理，当初翻译作神圣单纯是好读，但这个东西其实没什么能力，只是回复的饱食度更多，蕴魔……b格很高不适合，奇异的可以。

2024-04-12 05:14 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.staffof_magic_arrows": "§6暗血法杖",
因为这是暗血法杖发射的弹射物……

2024-04-12 05:16 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.spiritual_sword": "§6心灵剑",
这没必要，如果觉得心灵不合适倒是可以改用别的词语

2024-04-12 05:18 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.thread_on_the_bone": "线骨",
只是线缠绕着一根骨头，这个没有问题

2024-04-12 05:21 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.shattered_skull": "头骨",
其实是裂纹吧，没碎，贴图上头骨有裂痕，但这过于繁杂，不利于游戏界面的简洁性，如果觉得这个有必要那我就添加上。

2024-04-12 05:26 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "itemGroup.tabblock_borin_chaos": "生于混沌：方块",
有竖杠|这个符号，冒号也一样，都是为了分隔和确定从属关系，没必要，而且无论是|还是丨都容易看成I或l，对“生于混沌：DEBUG物品”就容易误导。

2024-04-12 11:31 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "block.born_in_chaos_v1.pile_of_skulls": "头骨方块",
skull在原版中译作头颅，例如凋灵骷髅头颅。简单来说就是术语。
译作堆的原因是没见block。故按原文译。而且这不是难以翻译的词语。
总而言之我需要指出与原文不一致的地方。在这里我坚持"头颅堆"的译名。

2024-04-12 11:37 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.born_in_chaos_v1.dogtruce": "看在骨头的份上",
同意，可以更简短，可以不修改。

2024-04-12 11:38 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.born_in_chaos_v1.fish_breath": "氧气要没了…",
同意，有更好时可以修改。

2024-04-12 11:41 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "entity.born_in_chaos_v1.riding_felsteed": "恶魔马",
如果不是同一生物可以不修改

2024-04-12 11:43 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.ethereal_spirit": "灵魂",
同样的，是由于原文的问题。ethereal
并非高调与否，而是作者本来就想表达

2024-04-12 11:46 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.shattered_skull": "头骨",
尽可能忠实原文。

2024-04-12 11:48 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "itemGroup.tabblock_borin_chaos": "生于混沌：方块",
库内格式同步，不再赘述。固定搭配

2024-04-12 11:52 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "itemGroup.tabblock_borin_chaos": "生于混沌：方块",
库内规范，固定搭配。

2024-04-12 12:01 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.born_in_chaos_v1.soul_stratification": "灵魂出窍",
主要在于对stratification的翻译，并希望尽可能贴近原文

> [stratification (n.)](https://www.quword.com/etym/s/stratification)
> 1610s, from Medieval Latin stratificationem (nominative stratificatio), noun of action from past participle stem of stratificare "to form strata," from stratum "thing spread out" (see [stratum](https://www.quword.com/etym/s/stratum)) + root of facere "to make" (see [factitious](https://www.quword.com/etym/s/factitious)). In sociology from 1879.

to make thing spread out 同时用于形容阶级的形成、极化。
故这里改为相对贴近的“分离”。如有更好请补充。至于逸散和离析意思稍微有些远。
对于先前的“灵魂出窍”则是因为意义太过固定了，且由其他词“享有”。

2024-04-12 12:05 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "block.born_in_chaos_v1.pile_of_skulls": "头骨方块",
头颅有异议，头颅在游戏中一般用作头部模型，在玩家的固定思维中头颅就是可以放置的，比如你说的凋骷头颅，但这个skull是item，是物品，不是方块不是实体，这不能一概而论。
堆或块都是可以的，这个无所谓。

2024-04-12 12:05 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "block.born_in_chaos_v1.black_argillite": "粘板岩",
请把“色”加上。这种岩石的名字就叫黑色粘板岩。

2024-04-12 12:10 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.magic_depletion": "魔法衰减",
可译作泄魔药水、之箭，或者其他类似表达。

2024-04-12 12:11 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.intoxicating_dagger": "§6巫毒匕首",
此处按你的意思修改，总之不使用巫毒。

2024-04-12 12:31 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "block.born_in_chaos_v1.pile_of_skulls": "头骨方块",
同意头骨，不在于方块与否，而是头颅除了指白骨那样的头，也指被完整砍下来的带肉的头（或活着的）。头骨则特指骨头。

2024-04-12 12:32 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.born_in_chaos_v1.soul_stratification": "灵魂出窍",
离析也有分离的含义，用哪一个都是可以的。我需要询问一下作者的意见。

2024-04-12 12:33 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.born_in_chaos_v1.furious_rampage": "暴怒猖獗",
我先打开，记得改。

2024-04-12 12:34 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.magic_depletion": "魔法衰减",
魔尽，好名字。

2024-04-12 12:40 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.born_in_chaos_v1.furious_rampage": "暴怒猖獗",
完毕

2024-04-12 12:44 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.magic_depletion": "魔法衰减",
还是用动词短语好一些。魔尽形容词短语。

2024-04-12 12:47 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.ethereal_spirit": "灵魂",
ethereal取飘渺之意，完毕。

2024-04-12 12:47 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.staffof_magic_arrows": "§6暗血法杖",
话说这个有名字叫魔血法杖。

2024-04-12 12:54 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.staffof_magic_arrows": "§6暗血法杖",
之前的名字是魔血，但实际上直译就是魔法杖，选个好听的前缀罢了，如果你觉得不合适，我可以改成魔法法杖。

2024-04-12 12:56 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.staffof_magic_arrows": "§6暗血法杖",
我倾向维持原先魔血法杖

2024-04-12 12:59 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "item.born_in_chaos_v1.staffof_magic_arrows": "§6暗血法杖",
了解

2024-04-12 13:08 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.magic_depletion": "魔法衰减",
魔力耗尽是自身的魔力自然耗尽，泄魔属于外力作用下的本不应发生的流失，比如泄洪、泄露。魔尽可以理解为“令……魔力耗尽”，实际上这些药水药箭不会存在实际游玩中。

2024-04-12 13:15 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.magic_depletion": "魔法衰减",
你都说外力了……丢药水射箭还不是外力吗……

2024-04-12 13:23 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.magic_depletion": "魔法衰减",
令……魔力耗尽，也是使动吧？再说depletion也没有泄漏的意思。尽魔可以，泄魔不可以。

2024-04-12 13:30 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.magic_depletion": "魔法衰减",
枯竭、缺乏、un-fill
实际上是有的。
> [depletion (n.)](https://www.quword.com/etym/s/depletion)
1650s, from Late Latin depletionem (nominative depletio) "blood-letting," noun of action from past participle stem of Latin deplere "to empty," literally "to un-fill," from de- "off, away" (see [de-](https://www.quword.com/etym/s/de-)) + plere "to fill" (see [pleio-](https://www.quword.com/etym/s/pleio-)).

2024-04-12 13:34 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "entity.born_in_chaos_v1.bone_imp": "恶魔小骷髅",
这个地方没有争议还真不习惯

2024-04-12 13:35 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.born_in_chaos_v1.soul_stratification": "灵魂出窍",
重新思考，魂不守舍

2024-04-12 13:56 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.born_in_chaos_v1.soul_stratification": "灵魂出窍",
--This effect slows down the target underneath it, and when the effect wears off, it deals damage proportional to the health of the entity, the higher the health, the higher the damage, and also removes all other effects from the entity when triggered.
--So I can think of it as a painful tear, not just a simple separation, right?
--yeah
作者原话是这样，和我游戏体验一致，这是个不好的效果，是强行剥离灵魂，会带来疼痛，所以分离的程度太轻了。以作者的角度来说，并不是单纯的分离，而是种痛苦的灵魂撕扯。

2024-04-12 13:57 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.born_in_chaos_v1.soul_stratification": "灵魂出窍",
既然如此，剥离，善。

2024-04-12 14:05 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.magic_depletion": "魔法衰减",
魔尽或尽魔吧，这是在使用法杖之后玩家也会出现的一种状态，就是蓝条耗尽。而且原版的药箭都是这样的，XX之箭 = 令……XX的箭，这个模板下，魔尽也是一样的。

2024-04-12 14:07 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.born_in_chaos_v1.soul_stratification": "灵魂出窍",
完毕

2024-04-12 14:07 UTC, SlimeSB commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "effect.magic_depletion": "魔法衰减",
不再赘述，尊重你的意愿。

2024-04-12 14:13 UTC, Takiaaa commented on projects/1.20/assets/born-in-chaos/born_in_chaos_v1/lang/zh_cn.json
> +  "itemGroup.tabblock_borin_chaos": "生于混沌：方块",
完毕

2024-04-12 14:17 UTC, SlimeSB commented
ethereal看错了……真是抱歉……

2024-04-12 14:17 UTC, SlimeSB approved these changes

2024-04-15 08:53 UTC, Takiaaa commented
@SlimeSB 似乎是我在自己库里进行编写新文件的时候不小心提交到了这个pr里（对githud还是不熟），错误文件已经删除了，请求重新审核一下

2024-04-19 09:57 UTC, SlimeSB approved these changes

2024-04-19 10:23 UTC, merged