Mythic charms 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3966
Opened 2023-11-27 19:46 UTC by Rxstar-sq

2023-11-28 00:24 UTC, Rxstar-sq commented
> ⚠ 无法找到 mythic_charms-fabric 的 CurseForge 项目名到 CurseForge ID 的映射。请检查此[链接](https://www.curseforge.com/minecraft/mc-mods/mythic_charms-fabric)是否可以正常打开，如果不能，或者网页被重定向，请修改你的文件路径。如果可以，请联系 [Cyl18](https://github.com/Cyl18) 解决。可以在上面的链接中右方找到 About Project -> Project ID 然后使用命令 `/add-mapping mythic_charms-fabric [CURSEFORGE_PROJECT_ID]`. 如果路径有误则使用 `/mv-recursive "projects/[GAME_VERSION]/assets/mythic_charms-fabric/" "projects/[GAME_VERSION]/assets/[NEW_DIR]/"`。 ℹ 此 PR 没有检测到 CurseForge 模组修改。
> 
> ℹ 此 PR 没有更改语言文件或者 PR-Packer 出现了问题。
> 
> ⚠ 检测到了一个语言文件，但是提交的路径不正常。缺少了 {modDomain} 和 lang 文件夹。请检查你的提交路径：`projects/1.20-fabric/assets/mythic_charms-fabric/zh_cn.json`； 无法找到该模组的 Mod Domain。
> 
> * [x]  🔄 勾选这个复选框来强制刷新

2023-11-28 14:59 UTC, ChuijkYahus commented
少了一层文件夹，请注意参照[CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)进行修改

2023-11-30 03:12 UTC, Rxstar-sq commented
【路径已修正】


⚠ 无法找到 mythic_charms-fabric 的 CurseForge 项目名到 CurseForge ID 的映射。请检查此[链接](https://www.curseforge.com/minecraft/mc-mods/mythic_charms-fabric)是否可以正常打开，如果不能，或者网页被重定向，请修改你的文件路径。如果可以，请联系 [Cyl18](https://github.com/Cyl18) 解决。可以在上面的链接中右方找到 About Project -> Project ID 然后使用命令 /add-mapping mythic_charms-fabric [CURSEFORGE_PROJECT_ID]. 如果路径有误则使用 /mv-recursive "projects/[GAME_VERSION]/assets/mythic_charms-fabric/" "projects/[GAME_VERSION]/assets/[NEW_DIR]/"。 ℹ 此 PR 没有检测到 CurseForge 模组修改。

ℹ 此 PR 没有更改语言文件或者 PR-Packer 出现了问题。

⚠ 检测到了一个语言文件，但是提交的路径不正常。缺少了 {modDomain} 和 lang 文件夹。请检查你的提交路径：projects/1.20-fabric/assets/mythic_charms-fabric/zh_cn.json； 无法找到该模组的 Mod Domain。

 🔄 勾选这个复选框来强制刷新

2023-11-30 03:13 UTC, Rxstar-sq commented
> 少了一层文件夹，请注意参照[CONTRIBUTING](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)进行修改

已修正

2023-11-30 03:22 UTC, ChuijkYahus commented
![D1D7)O$CF83KIJQFM) 8LLP](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/2e6c9055-c596-45e0-bc26-45e6096ce060)
请注意更新语言文件

2023-12-01 04:03 UTC, Rxstar-sq commented
> ![D1D7)O$CF83KIJQFM) 8LLP](https://private-user-images.githubusercontent.com/94828194/286806582-2e6c9055-c596-45e0-bc26-45e6096ce060.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MDI1NzAsIm5iZiI6MTcwMTQwMjI3MCwicGF0aCI6Ii85NDgyODE5NC8yODY4MDY1ODItMmU2YzkwNTUtYzU5Ni00NWUwLWJjMjYtNDVlNjA5NmNlMDYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDAzNDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NTcyZDRkYTMwMjc3OGIxNTYzOTUwMWRhZTdjYzY4MTQzMmEyNWQ0Yjc1MzgwZTZlMmNlNWY4OGM1YWU5YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bzhpl9qUDokucy2wOD5tKYuIEPHkMKOWWqtNc-iHeKc) 请注意更新语言文件

已更新

2023-12-02 03:21 UTC, ChuijkYahus requested changes

2023-12-02 03:21 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"item.mythic_charms.feathered_grace.tooltip": "为佩戴者在坠落半秒后且没有潜行的情况下给予两秒缓降效果",
```suggestion
	"item.mythic_charms.feathered_grace.tooltip": "在坠落半秒后且没有潜行的情况下，给予佩戴者两秒缓降效果",
```
微调

2023-12-02 03:21 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"item.mythic_charms.blazing_embrace.tooltip": "永久给予佩戴者耐火效果，但只有当佩戴者没有着火时，持续时间才会延长",
```suggestion
	"item.mythic_charms.blazing_embrace.tooltip": "永久给予佩戴者抗火效果，但只有当佩戴者没有着火时，持续时间才会延长",
```
原版术语

2023-12-02 03:21 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"item.mythic_charms.earths_order.tooltip": "使佩戴者能够仅用徒手破坏任何可破坏的方块",
```suggestion
	"item.mythic_charms.earths_order.tooltip": "使佩戴者能够徒手破坏任何可破坏的方块",
```
微调

2023-12-02 03:21 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"item.mythic_charms.high_bounds.tooltip": "提高佩戴者的跳跃高度和安全落地高度，使他们在一格内不会受到伤害，但会额外消耗饱食度",
```suggestion
	"item.mythic_charms.high_bounds.tooltip": "将佩戴者的跳跃高度和不会受到伤害的安全落地高度提高一格，但会额外消耗饱食度",
```
注意原文语义

2023-12-02 03:21 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"item.mythic_charms.weightless_flow.tooltip": "锁定佩戴者周围的重力使其可以站在空中或跃上天空，同时无法潜行",
```suggestion
	"item.mythic_charms.weightless_flow.tooltip": "锁定佩戴者周围的重力，使其不潜行时可以站在空中或跃上天空",
```
注意原文语义

2023-12-02 03:21 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"item.mythic_charms.climbers_path.tooltip": "使佩戴者可以额外跨越一格的高度以轻松越过障碍物，但是会额外消耗饱食度",
```suggestion
	"item.mythic_charms.climbers_path.tooltip": "使佩戴者可以跨越一格的高度，以此轻松越过障碍物，但是会额外消耗饱食度",
```
注意原文语义

2023-12-02 03:21 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"item.mythic_charms.enchanted_whispers.tooltip": "每次佩戴者与附魔台互动时都会随机化一个1级的附魔效果",
```suggestion
	"item.mythic_charms.enchanted_whispers.tooltip": "每次佩戴者与附魔台互动时都会重新随机魔咒，但魔咒等级会下降1级",
```
这里需要到游戏内验证是魔咒的等级还是附魔时候右下角数字的最大值
注意原文语义

2023-12-02 03:21 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"item.mythic_charms.barters_pact.tooltip": "佩戴者打开箱子时有70%的几率不会引发猪灵的攻击",
```suggestion
	"item.mythic_charms.barters_pact.tooltip": "佩戴者打开箱子时有70%的概率不会引发猪灵的攻击",
```
统一全文的`概率`和`几率`

2023-12-02 03:21 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"item.mythic_charms.mountains_strength.tooltip": "使佩戴者无视击退和挤压，但受到的伤害增加25%",
```suggestion
	"item.mythic_charms.mountains_strength.tooltip": "使佩戴者无视击退和推动，但受到的伤害增加25%",
```
这个挤压容易联想到单个方块内实体过多造成的挤压伤害，请注意查证

2023-12-02 03:21 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"item.mythic_charms.quiet_presence.tooltip": "使佩戴者能够在行走时不被幽匿探测器感知",
```suggestion
	"item.mythic_charms.quiet_presence.tooltip": "佩戴者在行走时不会被幽匿感测体感知",
```
原版物品术语，微调

2023-12-02 03:21 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"item.mythic_charms.glowstone_nugget": "萤石块",
```suggestion
	"item.mythic_charms.glowstone_nugget": "荧石粒",
```
一定注意原版术语的用字

2023-12-02 03:21 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"item.mythic_charms.deepslate_fragment.tooltip": "有小几率从深板岩上掉落",
```suggestion
	"item.mythic_charms.deepslate_fragment.tooltip": "有小概率从深板岩上掉落",
```

2023-12-02 03:21 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"util.mythic_charms.shift_tooltip": "按住§eSHIFT§r 了解更多信息",
```suggestion
	"util.mythic_charms.shift_tooltip": "按住§eSHIFT§r了解更多信息",
```
删去多余空格

2023-12-02 03:21 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"category.mythic_charms.resonance.ingredient": "成分",
```suggestion
	"category.mythic_charms.resonance.ingredient": "原材料",
```
原版用词

2023-12-02 03:21 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"tag.item.mythic_charms.resonance_ingredients": "共鸣成分",
```suggestion
	"tag.item.mythic_charms.resonance_ingredients": "共鸣原材料",
```

2023-12-02 03:21 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"category.mythic_charms.resonance.output": "结果",
推荐改成`产物`

2023-12-02 03:21 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"advancements.mythic_charms.story.first_charm.title": "《护符的魅力》101节",
```suggestion
	"advancements.mythic_charms.story.first_charm.title": "护符制造101",
```
101一般指“入门教程”，不是书中具体某一节

2023-12-02 03:21 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"text.config.mythic-charms-config.option.experienceNuggetMobCap": "周围的小怪数量，超过该数量将不再掉落经验金块",
```suggestion
	"text.config.mythic-charms-config.option.experienceNuggetMobCap": "周围的生物数量，超过该数量将不再掉落经验粒",
```

2023-12-02 03:21 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"item.mythic_charms.echoing_wrath.tooltip": "当佩戴者受到伤害时，将该伤害的50%反弹给附近的小怪，最多造成3颗心的伤害；佩戴者受到的伤害增加25%",
```suggestion
	"item.mythic_charms.echoing_wrath.tooltip": "当佩戴者受到伤害时，将该伤害的50%反弹给附近的生物，最多造成3颗心的伤害；佩戴者受到的伤害增加25%",
```
mob是原版术语，注意统一

2023-12-02 03:21 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"item.mythic_charms.experience_nugget": "经验金块",
```suggestion
	"item.mythic_charms.experience_nugget": "经验粒",
```

2023-12-02 12:43 UTC, Rxstar-sq commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"item.mythic_charms.weightless_flow.tooltip": "锁定佩戴者周围的重力使其可以站在空中或跃上天空，同时无法潜行",
这里这么翻译是因为发现直接翻译原文的话不符合游戏内表现，游戏中佩戴之后角色是完全无法潜行，相对的潜行行为变成了类似创造模式的“下降”。

2023-12-02 12:48 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"item.mythic_charms.weightless_flow.tooltip": "锁定佩戴者周围的重力使其可以站在空中或跃上天空，同时无法潜行",
贴地的时候也不能潜行吗

2023-12-02 12:56 UTC, Rxstar-sq commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"item.mythic_charms.enchanted_whispers.tooltip": "每次佩戴者与附魔台互动时都会随机化一个1级的附魔效果",
这里说实话我没有搞明白具体作用，因为游戏内实际操作发现是否佩戴该护符似乎不会影响到附魔结果【很奇妙】

2023-12-02 13:01 UTC, Rxstar-sq commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"item.mythic_charms.mountains_strength.tooltip": "使佩戴者无视击退和挤压，但受到的伤害增加25%",
已查证，是免疫生物来源的击退和推动；诸如爆炸，水流等自然因素导致的击退和推动仍然有效

2023-12-02 13:15 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"item.mythic_charms.weightless_flow.tooltip": "锁定佩戴者周围的重力使其可以站在空中或跃上天空，同时无法潜行",
OK

2023-12-02 13:15 UTC, ChuijkYahus requested changes

2023-12-02 13:15 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"item.mythic_charms.blazing_embrace.tooltip": "永久给予佩戴者耐火效果，但只有当佩戴者没有着火时，持续时间才会延长",
原版术语未修改

2023-12-02 13:17 UTC, Rxstar-sq commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"item.mythic_charms.blazing_embrace.tooltip": "永久给予佩戴者耐火效果，但只有当佩戴者没有着火时，持续时间才会延长",
已更正

2023-12-02 13:19 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"advancements.mythic_charms.story.first_charm.title": "《护符的魅力》101节",
或者可以把101放到书名号里面去（）

2023-12-02 13:29 UTC, ChuijkYahus requested changes

2023-12-02 13:29 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/mythic-charms/mythic_charms/lang/zh_cn.json
> +	"advancements.mythic_charms.story.first_charm.title": "《护符的魅力》101",
```suggestion
	"advancements.mythic_charms.story.first_charm.title": "《护符的魅力101》",
```
一般101就是名称的一部分

2023-12-03 02:43 UTC, ChuijkYahus approved these changes

2023-12-05 03:30 UTC, ChuijkYahus commented
重复提交，请注意删除Obsidian Equipment的内容

2023-12-07 00:03 UTC, Rxstar-sq commented
> 重复提交，请注意删除Obsidian Equipment的内容

遇到技术性问题了，不知为何我这里无法从fork删除，求助。

2023-12-07 00:20 UTC, Rxstar-sq commented
> 重复提交，请注意删除Obsidian Equipment的内容

已删除

2023-12-07 05:18 UTC, ChuijkYahus approved these changes

2023-12-07 05:18 UTC, merged