添加observable翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #3986
Opened 2023-12-03 13:06 UTC by scattered-leaves

2023-12-03 13:18 UTC, ChuijkYahus requested changes
请不要随意closePR

2023-12-03 13:18 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/observable/observable/lang/zh_cn.json
> +  "text.observable.profile_fps": "FPS 占用显示",
```suggestion
  "text.observable.profile_tps": "TPS占用显示",
  "text.observable.profile_fps": "FPS占用显示",
```

2023-12-03 13:18 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/observable/observable/lang/zh_cn.json
> +  "text.observable.no_permissions": "您没有权限运行",
```suggestion
  "text.observable.no_permissions": "你没有权限运行",
```
请注意全部用`你`

2023-12-03 13:18 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/observable/observable/lang/zh_cn.json
> +  "text.observable.get_field": "输入配置文件 URL/哈希...",
```suggestion
  "text.observable.get_field": "输入配置文件URL或哈希……",
```
请注意使用中文省略号
这里的profile是指什么

2023-12-03 14:14 UTC, ChuijkYahus requested changes

2023-12-03 14:14 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/observable/observable/lang/zh_cn.json
> +  "screen.observable.profile": "轮廓",
模组中的Profile到底指的是什么

2023-12-03 14:14 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/observable/observable/lang/zh_cn.json
> +  "text.observable.donate": "Donate",
未翻译

2023-12-03 14:14 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/observable/observable/lang/zh_cn.json
> +  "text.observable.profile_started": "Observable 正在分析 %d 秒之内的游戏...",
```suggestion
  "text.observable.profile_started": "Observable正在分析%d秒之内的游戏……",
```
你这全文改了吗

2023-12-03 14:14 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/observable/observable/lang/zh_cn.json
> +  "text.observable.suggest": "您的服务器似乎运行得有点慢（%s tps） ，%s 查找滞后源。",
```suggestion
  "text.observable.suggest": "你的服务器似乎运行得有点慢（%s tps）。%s以查找卡顿源。",
```
这里在游戏内是怎么显示的

---
若使用翻译辅助，请注意译后编辑修正
直接提交未经修正的版本会被拒收

2023-12-03 14:56 UTC, scattered-leaves commented
非常抱歉，我没有仔细检查全文，我会在修改并仔细检查后再提交



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月3日(周日) 晚上10:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CFPAOrg/Minecraft-Mod-Language-Package] Observable 翻译提交 (PR #3986)




 
@ChuijkYahus requested changes on this pull request.
 
 
In projects/1.20-fabric/assets/observable/observable/lang/zh_cn.json:
 &gt; @@ -0,0 +1,34 @@ +{ +  "screen.observable.profile": "轮廓",  
模组中的Profile到底指的是什么
 
 
In projects/1.20-fabric/assets/observable/observable/lang/zh_cn.json:
 &gt; +  "category.observable.keybinds": "Observable", +  "text.observable.profile_tps": "TPS占用显示", +  "text.observable.profile_fps": "FPS占用显示", +  "text.observable.sampler": "加载采样器的配置文件（增加性能消耗）", +  "text.observable.unimplemented": "未完成！", +  "text.observable.unavailable": "服务器上未安装Observable", +  "text.observable.no_permissions": "你没有权限运行", +  "text.observable.error": "执行操作时出错：%s", +  "text.observable.report": "请在github.com/tasgon/observable/issues上报告错误", +  "text.observable.entity_not_found": "在%s中找不到实体，他可能死了或者被移走了？", +  "text.observable.get_field": "输入配置文件URL或哈希……", +  "text.observable.get_btn": "Get!", +  "text.observable.overlay": "显示", +  "text.observable.docs": "Wiki", +  "text.observable.discord": "Discord", +  "text.observable.donate": "Donate",  
未翻译
 
 
In projects/1.20-fabric/assets/observable/observable/lang/zh_cn.json:
 &gt; +  "text.observable.profile_tps": "TPS占用显示", +  "text.observable.profile_fps": "FPS占用显示", +  "text.observable.sampler": "加载采样器的配置文件（增加性能消耗）", +  "text.observable.unimplemented": "未完成！", +  "text.observable.unavailable": "服务器上未安装Observable", +  "text.observable.no_permissions": "你没有权限运行", +  "text.observable.error": "执行操作时出错：%s", +  "text.observable.report": "请在github.com/tasgon/observable/issues上报告错误", +  "text.observable.entity_not_found": "在%s中找不到实体，他可能死了或者被移走了？", +  "text.observable.get_field": "输入配置文件URL或哈希……", +  "text.observable.get_btn": "Get!", +  "text.observable.overlay": "显示", +  "text.observable.docs": "Wiki", +  "text.observable.discord": "Discord", +  "text.observable.donate": "Donate", +  "text.observable.profile_started": "Observable 正在分析 %d 秒之内的游戏...",  ⬇️ Suggested change -  "text.observable.profile_started": "Observable 正在分析 %d 秒之内的游戏...", +  "text.observable.profile_started": "Observable正在分析%d秒之内的游戏……",  
你这全文改了吗
 
 
In projects/1.20-fabric/assets/observable/observable/lang/zh_cn.json:
 &gt; +  "text.observable.no_permissions": "你没有权限运行", +  "text.observable.error": "执行操作时出错：%s", +  "text.observable.report": "请在github.com/tasgon/observable/issues上报告错误", +  "text.observable.entity_not_found": "在%s中找不到实体，他可能死了或者被移走了？", +  "text.observable.get_field": "输入配置文件URL或哈希……", +  "text.observable.get_btn": "Get!", +  "text.observable.overlay": "显示", +  "text.observable.docs": "Wiki", +  "text.observable.discord": "Discord", +  "text.observable.donate": "Donate", +  "text.observable.profile_started": "Observable 正在分析 %d 秒之内的游戏...", +  "text.observable.profile_uploaded": "分析结果已上传到 %s", +  "text.observable.upload_failed": "无法上传分析结果", +  "text.observable.profile_saved": "分析结果已保存到 %s", +  "text.observable.after_save": "在 %s 处打开此文件", +  "text.observable.suggest": "您的服务器似乎运行得有点慢（%s tps） ，%s 查找滞后源。",  ⬇️ Suggested change -  "text.observable.suggest": "您的服务器似乎运行得有点慢（%s tps） ，%s 查找滞后源。", +  "text.observable.suggest": "你的服务器似乎运行得有点慢（%s tps）。%s以查找卡顿源。",  
这里在游戏内是怎么显示的
 
 
若使用翻译辅助，请注意译后编辑修正
 直接提交未经修正的版本会被拒收
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-12-07 12:16 UTC, qznfbnj commented on projects/1.20-fabric/assets/observable/observable/lang/zh_cn.json
> +  "screen.observable.profile": "轮廓",
体检档案（bushi

2024-01-10 02:34 UTC, luoxueyasha commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。
@scattered-leaves

2024-01-18 20:06 UTC, closed without merging