保存more-bows-restrung的翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #3993
Opened 2023-12-09 09:16 UTC by ErwinWVHenry

2023-12-10 03:21 UTC, ChuijkYahus commented
请注意给文件分行
若使用VSCode，可直接全选并在右键菜单中使用格式化文件
若使用GitHubWeb，也可直接全选并在右键菜单中使用格式化文件

2023-12-11 16:17 UTC, ChuijkYahus commented
英文文件也需分行

2023-12-12 03:37 UTC, ChuijkYahus requested changes

2023-12-12 03:37 UTC, ChuijkYahus commented on projects/1.16/assets/more-bows-restrung/more-bows-restrung/lang/zh_cn.json
> +    "morebows.confBowDamageMult.tooltip": "弓的基础伤害倍数越高伤害越大。",
```suggestion
    "morebows.confBowDamageMult.tooltip": "弓的基础伤害倍数，越高伤害越大。",
```

2023-12-12 03:37 UTC, ChuijkYahus commented on projects/1.16/assets/more-bows-restrung/more-bows-restrung/lang/zh_cn.json
> +    "morebows.confBowDrawbackDiv.tooltip": "弓的攻击间隔，越小攻速越快.",
```suggestion
    "morebows.confBowDrawbackDiv.tooltip": "弓的攻击间隔，越小攻速越快。",
```
请注意使用中文标点

2023-12-12 03:37 UTC, ChuijkYahus commented on projects/1.16/assets/more-bows-restrung/more-bows-restrung/lang/zh_cn.json
> +    "morebows.confBowDurability": "耐久性",
```suggestion
    "morebows.confBowDurability": "耐久度",
```
原版术语

2023-12-12 03:37 UTC, ChuijkYahus commented on projects/1.16/assets/more-bows-restrung/more-bows-restrung/lang/zh_cn.json
> +    "morebows.confGenFrostCold": "冰霜箭矢是寒冷的",
```suggestion
    "morebows.confGenFrostCold": "寒冷冰霜箭",
```

2023-12-12 03:37 UTC, ChuijkYahus commented on projects/1.16/assets/more-bows-restrung/more-bows-restrung/lang/zh_cn.json
> +    "morebows.confGenFrostCold.tooltip": "如果启用，冰霜箭将对火属性生灵造成三倍伤害，并灭火。\n启用这个也可以防止冰霜箭着火。",
```suggestion
    "morebows.confGenFrostCold.tooltip": "如果启用，冰霜箭将对烈焰人造成三倍伤害，并会熄灭实体身上的火。\n启用这个也可以防止冰霜箭着火。",
```
火属性生灵是什么

2023-12-12 03:37 UTC, ChuijkYahus commented on projects/1.16/assets/more-bows-restrung/more-bows-restrung/lang/zh_cn.json
> +    "morebows.confGenOldRendering.tooltip": "如果启用了这个选项，冰霜箭将被渲染成箭头。",
```suggestion
    "morebows.confGenOldRendering.tooltip": "如果启用，冰霜箭将被渲染成箭。",
```

2023-12-12 03:37 UTC, ChuijkYahus commented on projects/1.16/assets/more-bows-restrung/more-bows-restrung/lang/zh_cn.json
> +    "morebows.confGenOldRendering": "旧的冰霜箭矢渲染",
```suggestion
    "morebows.confGenOldRendering": "旧版冰霜箭渲染",
```

2023-12-12 03:37 UTC, ChuijkYahus commented on projects/1.16/assets/more-bows-restrung/more-bows-restrung/lang/zh_cn.json
> +    "morebows.confGenOldSlowdown": "冰霜箭矢减速",
```suggestion
    "morebows.confGenOldSlowdown": "旧版冰霜箭减速",
```
`旧版`未译出

2023-12-12 03:37 UTC, ChuijkYahus commented on projects/1.16/assets/more-bows-restrung/more-bows-restrung/lang/zh_cn.json
> +    "morebows.confGenOldSlowdown.tooltip": "如果启用，冰霜箭矢将会通过将实体放入一个网中1tick的方法减速实体\n如果禁用，冰霜箭矢会在命中时使用等同于减速药剂的效果减速实体.",
```suggestion
    "morebows.confGenOldSlowdown.tooltip": "如果启用，冰霜箭减速实体的方式类似于将其放入蜘蛛网中1tick。\n如果禁用，冰霜箭会在命中时给予缓慢效果。",
```

2023-12-12 03:37 UTC, ChuijkYahus commented on projects/1.16/assets/more-bows-restrung/more-bows-restrung/lang/zh_cn.json
> +    "morebows.confBowDurability.tooltip": "弓的耐久值，越高越耐用.",
```suggestion
    "morebows.confBowDurability.tooltip": "弓的耐久值，越高越耐用。",
```

2023-12-12 03:37 UTC, ChuijkYahus commented on projects/1.16/assets/more-bows-restrung/more-bows-restrung/lang/zh_cn.json
> +    "morebows.confMultiShotAmmo.UseAmountShot": "使用尽可能多的箭射击",
```suggestion
    "morebows.confMultiShotAmmo.UseAmountShot": "使用多支箭矢射击",
```

2023-12-12 03:37 UTC, ChuijkYahus commented on projects/1.16/assets/more-bows-restrung/more-bows-restrung/lang/zh_cn.json
> +    "morebows.confMultiShotAmmo.tooltip": "改变多发弓发射额外箭的方式。可选的选项:\n使用一支箭，发射多支特殊箭\n使用一支箭，射出多支普通箭\n使用尽可能多的箭，射出用过的箭头",
```suggestion
    "morebows.confMultiShotAmmo.tooltip": "改变多发弓发射额外箭的方式。选项如下：\n使用一支箭，射出多支特殊箭\n使用一支箭，射出多支普通箭\n使用尽可能多的箭，射出用过的箭",
```
最后的used arrow在游戏中实际表现如何

2023-12-12 03:37 UTC, ChuijkYahus commented on projects/1.16/assets/more-bows-restrung/more-bows-restrung/lang/zh_cn.json
> +    "morebows.confTitle": "更多设置"
```suggestion
    "morebows.confTitle": "更多弓设置"
```

2023-12-20 10:51 UTC, luoxueyasha commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。 

@ErwinWVHenry

2023-12-28 20:06 UTC, closed without merging