plantable-ores 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #3999
Opened 2023-12-11 15:57 UTC by SerkentZ

2023-12-11 16:14 UTC, ChuijkYahus commented
路径错误，请注意修改

2023-12-12 03:25 UTC, ChuijkYahus requested changes
请注意全文通查

2023-12-12 03:25 UTC, ChuijkYahus commented on projects/1.19/assets/plantable-ores/plantable_ores/lang/zh_cn.json
> +  "block.plantable_ores.redstone_ore_stage_3": "红石矿植株(成熟)",
```suggestion
  "block.plantable_ores.redstone_ore_stage_3": "红石矿石植株",
```
注意原版名称，原文没有不需注释

2023-12-12 03:25 UTC, ChuijkYahus commented on projects/1.19/assets/plantable-ores/plantable_ores/lang/zh_cn.json
> +  "block.plantable_ores.diamond_ore_stage_3": "钻石矿植株(成熟)",
```suggestion
  "block.plantable_ores.diamond_ore_stage_3": "钻石矿石植株",
```

2023-12-12 18:32 UTC, ChuijkYahus requested changes
注意原版术语，请全文统一修改

2023-12-12 18:32 UTC, ChuijkYahus commented on projects/1.19/assets/plantable-ores/plantable_ores/lang/zh_cn.json
> +  "block.plantable_ores.redstone_ore_stage_3": "红石矿植株",
```suggestion
  "block.plantable_ores.redstone_ore_stage_3": "红石矿石植株",
```

2023-12-12 18:32 UTC, ChuijkYahus commented on projects/1.19/assets/plantable-ores/plantable_ores/lang/zh_cn.json
> +  "block.plantable_ores.diamond_ore_stage_3": "钻石矿植株",
```suggestion
  "block.plantable_ores.diamond_ore_stage_3": "钻石矿石植株",
```

2023-12-13 12:41 UTC, ChuijkYahus submitted a review, later dismissed

2023-12-20 11:08 UTC, mamaruo submitted a review, later dismissed

2023-12-20 11:22 UTC, mamaruo approved these changes

2023-12-24 11:14 UTC, merged