Ube's Delight [Fabric] 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4014
Opened 2023-12-16 21:55 UTC by QiuShui1012

这模组添加curseforge了

由 CFPA-Helper 提交。

2023-12-16 21:59 UTC, QiuShui1012 commented
> 这模组添加curseforge了
> 
> 由 CFPA-Helper 提交。

还顺便更新版本到了0.1.5

2023-12-20 11:37 UTC, mamaruo commented
#### 供审阅人员查阅

我对比了“此前版本”和“目前版本”的翻译，结果如下：

### 两者皆有且中文有差异

| **键** | **英文** | **此前版本** | **目前版本** |
|---|---|---|---|
| block.ubesdelight.kalan | Kalan | 烤炉 | 卡兰炉 |

### 只在 中文1 中有

| **键** | **英文** | **此前版本** | **目前版本** |
|---|---|---|---|
| item.ubesdelight.halo_halo | 🚫 | 哈喽哈喽刨冰 | 🚫 |

### 只在 中文2 中有

<details><summary>点击展开/收起</summary>
<p>

| **键** | **英文** | **此前版本** | **目前版本** |
|---|---|---|---|
| block.ubesdelight.baking_mat_bamboo | Bamboo Baking Mat | 🚫 | 竹烤垫 |
| block.ubesdelight.glass_cup_halo_halo | Halo Halo | 🚫 | 哈喽哈喽刨冰 |
| item.ubesdelight.ensaymada | Ensaymada | 🚫 | 蜗牛面包 |
| item.ubesdelight.ensaymada_raw | Raw Ensaymada | 🚫 | 生蜗牛面包 |
| item.ubesdelight.ensaymada_stage0 | Ensaymada Stage 0 | 🚫 | 蜗牛面包（阶段0） |
| item.ubesdelight.ensaymada_stage1 | Ensaymada Stage 1 | 🚫 | 蜗牛面包（阶段1） |
| item.ubesdelight.ensaymada_stage2 | Ensaymada Stage 2 | 🚫 | 蜗牛面包（阶段2） |
| item.ubesdelight.ensaymada_stage3 | Ensaymada Stage 3 | 🚫 | 蜗牛面包（阶段3） |
| item.ubesdelight.ensaymada_ube | Ube Ensaymada | 🚫 | 香芋蜗牛面包 |
| item.ubesdelight.ensaymada_ube_raw | Raw Ube Ensaymada | 🚫 | 生香芋蜗牛面包 |
| item.ubesdelight.ensaymada_ube_stage0 | Ube Ensaymada Stage 0 | 🚫 | 香芋蜗牛面包（阶段0） |
| item.ubesdelight.ensaymada_ube_stage1 | Ube Ensaymada Stage 1 | 🚫 | 香芋蜗牛面包（阶段1） |
| item.ubesdelight.ensaymada_ube_stage2 | Ube Ensaymada Stage 2 | 🚫 | 香芋蜗牛面包（阶段2） |
| item.ubesdelight.ensaymada_ube_stage3 | Ube Ensaymada Stage 3 | 🚫 | 香芋蜗牛面包（阶段3） |
| item.ubesdelight.hopia_munggo | Hopia Munggo | 🚫 | 绿豆霍皮饼 |
| item.ubesdelight.hopia_munggo_raw | Raw Hopia Munggo | 🚫 | 生绿豆霍皮饼 |
| item.ubesdelight.hopia_munggo_stage0 | Hopia Munggo Stage 0 | 🚫 | 绿豆霍皮饼（阶段0） |
| item.ubesdelight.hopia_munggo_stage1 | Hopia Munggo Stage 1 | 🚫 | 绿豆霍皮饼（阶段1） |
| item.ubesdelight.hopia_munggo_stage2 | Hopia Munggo Stage 2 | 🚫 | 绿豆霍皮饼（阶段2） |
| item.ubesdelight.hopia_ube | Hopia Ube | 🚫 | 香芋霍皮饼 |
| item.ubesdelight.hopia_ube_raw | Raw Hopia Ube | 🚫 | 生香芋霍皮饼 |
| item.ubesdelight.hopia_ube_stage0 | Hopia Ube Stage 0 | 🚫 | 香芋霍皮饼（阶段0） |
| item.ubesdelight.hopia_ube_stage1 | Hopia Ube Stage 1 | 🚫 | 香芋霍皮饼（阶段1） |
| item.ubesdelight.hopia_ube_stage2 | Hopia Ube Stage 2 | 🚫 | 香芋霍皮饼（阶段2） |
| item.ubesdelight.pandesal | Pandesal | 🚫 | 菲律宾面包卷 |
| item.ubesdelight.pandesal_raw | Raw Pandesal | 🚫 | 生菲律宾面包卷 |
| item.ubesdelight.pandesal_stage0 | Pandesal Stage 0 | 🚫 | 菲律宾面包卷（阶段0） |
| item.ubesdelight.pandesal_stage1 | Pandesal Stage 1 | 🚫 | 菲律宾面包卷（阶段1） |
| item.ubesdelight.pandesal_stage2 | Pandesal Stage 2 | 🚫 | 菲律宾面包卷（阶段2） |
| item.ubesdelight.pandesal_ube | Ube Pandesal | 🚫 | 香芋菲律宾面包卷 |
| item.ubesdelight.pandesal_ube_raw | Raw Ube Pandesal | 🚫 | 生香芋菲律宾面包卷 |
| item.ubesdelight.pandesal_ube_stage0 | Ube Pandesal Stage 0 | 🚫 | 香芋菲律宾面包卷（阶段0） |
| item.ubesdelight.pandesal_ube_stage1 | Ube Pandesal Stage 1 | 🚫 | 香芋菲律宾面包卷（阶段1） |
| item.ubesdelight.pandesal_ube_stage2 | Ube Pandesal Stage 2 | 🚫 | 香芋菲律宾面包卷（阶段2） |
| item.ubesdelight.polvorone_cc_stage0 | 曲奇奶油味Polvorone Stage 0 | 🚫 | 曲奇奶油味西班牙酥饼（阶段0） |
| item.ubesdelight.polvorone_cc_stage1 | 曲奇奶油味Polvorone Stage 1 | 🚫 | 曲奇奶油味西班牙酥饼（阶段1） |
| item.ubesdelight.polvorone_cc_stage2 | 曲奇奶油味Polvorone Stage 2 | 🚫 | 曲奇奶油味西班牙酥饼（阶段2） |
| item.ubesdelight.polvorone_pinipig_stage0 | Pinipig Polvorone Stage 0 | 🚫 | 绿糯米味西班牙酥饼（阶段0） |
| item.ubesdelight.polvorone_pinipig_stage1 | Pinipig Polvorone Stage 1 | 🚫 | 绿糯米味西班牙酥饼（阶段1） |
| item.ubesdelight.polvorone_pinipig_stage2 | Pinipig Polvorone Stage 2 | 🚫 | 绿糯米味西班牙酥饼（阶段2） |
| item.ubesdelight.polvorone_stage0 | Polvorone Stage 0 | 🚫 | 西班牙酥饼（阶段0） |
| item.ubesdelight.polvorone_stage1 | Polvorone Stage 1 | 🚫 | 西班牙酥饼（阶段1） |
| item.ubesdelight.polvorone_stage2 | Polvorone Stage 2 | 🚫 | 西班牙酥饼（阶段2） |
| item.ubesdelight.polvorone_ube_stage0 | Ube Polvorone Stage 0 | 🚫 | 香芋味西班牙酥饼（阶段0） |
| item.ubesdelight.polvorone_ube_stage1 | Ube Polvorone Stage 1 | 🚫 | 香芋味西班牙酥饼（阶段1） |
| item.ubesdelight.polvorone_ube_stage2 | Ube Polvorone Stage 2 | 🚫 | 香芋味西班牙酥饼（阶段2） |
| item.ubesdelight.rolling_pin_wood | Wood Rolling Pin | 🚫 | 木擀面杖 |
| ubesdelight.advancement.craft_baking_mat | Baking Mat | 🚫 | 烤垫 |
| ubesdelight.advancement.craft_baking_mat.desc | Surround honeycomb with bamboo to craft a Baking Mat | 🚫 | 用竹子围绕蜜脾制作烤垫 |
| ubesdelight.advancement.craft_rolling_pin | Rolling Pin | 🚫 | 擀面杖 |
| ubesdelight.advancement.craft_rolling_pin.desc | Use sticks and a fence to make a new tool for the kitchen | 🚫 | 用木棍和栅栏为厨房制作一个新工具 |
| ubesdelight.advancement.get_ud_seed | Crops of the Tropics | 🚫 | 热带作物 |
| ubesdelight.advancement.get_ud_seed.desc | Adventure to find four new crops, only found in jungles and some village chests\. | 🚫 | 通过冒险来寻找四种新作物，它们只能在丛林和一些村庄里发现。 |
| ubesdelight.advancement.master_baker | Master Baker | 🚫 | 特级面包师 |
| ubesdelight.advancement.master_baker.desc | Craft all varieties of Filipino bread\! | 🚫 | 制作所有种类的菲律宾面包！ |
| ubesdelight.advancement.place_drinkable_feast | Punch Bowl | 🚫 | 潘趣碗 |
| ubesdelight.advancement.place_drinkable_feast.desc | Drinks can be combined and placed\. Grab a bottle and have a sip\! | 🚫 | 饮料可以组合放置。拿一瓶喝一口吧！ |
| ubesdelight.advancement.place_kalan | Take the Kitchen Outside\! | 🚫 | 把厨房放在外面！ |
| ubesdelight.advancement.place_kalan.desc | The Kalan is a traditional Filipino terracotta stove\. Perfect for an outdoor kitchen\! | 🚫 | 卡兰炉是一种传统的菲律宾陶土炉。非常适合户外厨房！ |
| ubesdelight.advancement.plant_all_crops | Master Farmer of the Tropics | 🚫 | 特级热带农民 |
| ubesdelight.advancement.plant_all_crops.desc | Cultivate every new crop found in the Jungle\! | 🚫 | 培育在丛林中发现的每一种新作物！ |
| ubesdelight.advancement.root | Ube's Delight | 🚫 | 香芋乐事 |
| ubesdelight.advancement.root.desc | Cuisine from the Phillipines\! | 🚫 | 来自菲律宾的美食！ |
| ubesdelight.advancement.ube_master | Ube Enthusiast | 🚫 | 香芋爱好者 |
| ubesdelight.advancement.ube_master.desc | Eat every Ube specific dish | 🚫 | 食用每一道含有香芋的食物 |
| ubesdelight.advancement.ud_master | Ube's Delight Master | 🚫 | 香芋乐事大师 |
| ubesdelight.advancement.ud_master.desc | Try all the new food and drink items from Ube's Delight | 🚫 | 尝试了香芋乐事的所有新食品和饮料 |
| ubesdelight.advancement.use_baking_mat | Ube's Baking | 🚫 | 香芋的烘焙 |
| ubesdelight.advancement.use_baking_mat.desc | Add baking ingredients to the Baking Mat then use the Rolling Pin to craft baked goods in a new way\! | 🚫 | 将烘焙原料添加到烘焙垫中，然后使用擀面杖以一种新的方式制作烘焙食品！ |
| ubesdelight.rei.baking_mat | Baking Mat | 🚫 | 烤垫 |
| ubesdelight.rei.chance | %1$s%% chance | 🚫 | %1$s%% 概率 |
| ubesdelight.rei.info.rolling_pin | Explain Rolling Pin | 🚫 | 擀面杖说明 |
| ubesdelight.subtitles.block_baking_mat.add | Item added | 🚫 | 添加物品 |
| ubesdelight.subtitles.block_baking_mat.remove | Item Removed | 🚫 | 拿取物品 |
| ubesdelight.subtitles.block_baking_mat.rolling_pin | Rolling Pin rolls | 🚫 | 擀面杖擀 |
| ubesdelight.subtitles.block_drinkable_feast.add | Drink Added | 🚫 | 添加饮品 |
| ubesdelight.subtitles.block_drinkable_feast.remove | Drink Removed | 🚫 | 拿取饮品 |
| ubesdelight.subtitles.block_lumpia_feast.remove | Lumpia Removed | 🚫 | 拿取菲律宾润饼 |
| ubesdelight.tooltip.baking_mat.invalid_item | Invalid Items | 🚫 | 无效的物品 |
| ubesdelight.tooltip.baking_mat.invalid_tool | Invalid Tool | 🚫 | 无效的工具 |

</p>
</details>

2024-05-02 06:15 UTC, SlimeSB requested changes

2024-05-02 06:15 UTC, SlimeSB commented on projects/1.20-fabric/assets/ubes-delight/ubesdelight/lang/zh_cn.json
> +  "ubesdelight.advancement.get_ud_seed.desc": "通过冒险来寻找四种新作物，它们只能在丛林和一些村庄里发现。",
```suggestion
  "ubesdelight.advancement.get_ud_seed.desc": "通过冒险来寻找四种新作物，它们只能在丛林和村庄的一些宝箱里发现。",
```

2024-05-02 06:15 UTC, SlimeSB commented on projects/1.20-fabric/assets/ubes-delight/ubesdelight/lang/zh_cn.json
> +  "ubesdelight.subtitles.block_lumpia_feast.remove": "拿取菲律宾润饼",
```suggestion
  "ubesdelight.subtitles.block_baking_mat.add": "物品：添加",
  "ubesdelight.subtitles.block_baking_mat.remove": "物品：拿取",
  "ubesdelight.subtitles.block_baking_mat.rolling_pin": "擀面杖：擀",
  "ubesdelight.subtitles.block_drinkable_feast.add": "饮品：添加",
  "ubesdelight.subtitles.block_drinkable_feast.remove": "饮品：拿取",
  "ubesdelight.subtitles.block_lumpia_feast.remove": "菲律宾润饼：拿取",
```

2024-05-02 06:15 UTC, SlimeSB commented on projects/1.20-fabric/assets/ubes-delight/ubesdelight/lang/zh_cn.json
> +  "ubesdelight.tooltip.kalan": "一种菲律宾传统的黏土烤炉。",
```suggestion
  "ubesdelight.tooltip.baking_mat.invalid_tool": "无效的工具",
  "ubesdelight.tooltip.halo_halo": "用刀右击以旋转，用刀破坏以拾取。",
  "ubesdelight.tooltip.kalan": "一种菲律宾传统的黏土烤炉。",
```

2024-05-04 09:51 UTC, SlimeSB approved these changes

2024-05-04 09:52 UTC, SlimeSB commented
@QiuShui1012 如有问题回退即可，或之后重新另开pr修改

2024-05-04 10:45 UTC, QiuShui1012 commented
> @QiuShui1012 如有问题回退即可，或之后重新另开pr修改

我测我忘记close了，我已经在模组官库同步过了（）
我现在直接close？还是说等你来

2024-05-04 10:54 UTC, QiuShui1012 commented
@SlimeSB 顺便感谢你的修改，我在官库内的翻译已经同步commit，并标注了你的名字

2024-05-04 14:16 UTC, luoxueyasha commented
那这边合了还是关了？

2024-05-04 14:44 UTC, merged