[Let's Do] NetherVinery 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4020
Opened 2023-12-19 16:46 UTC by QiuShui1012

由 CFPA-Helper 提交。

2023-12-20 12:39 UTC, qznfbnj commented on projects/1.20-fabric/assets/lets-do-nethervinery/nethervinery/lang/zh_cn.json
> +  "item.vinery.grape.tooltip.item.nethervinery.warped_grape": "可以在诡异森林里的岩浆湖边找到",
是湖还是海？
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/100760086/4aefd324-854c-4b09-8652-d4157684349d)
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/100760086/e4d64c51-48f0-4b3d-8b52-bf27d331791a)

2023-12-20 12:42 UTC, QiuShui1012 commented on projects/1.20-fabric/assets/lets-do-nethervinery/nethervinery/lang/zh_cn.json
> +  "item.vinery.grape.tooltip.item.nethervinery.warped_grape": "可以在诡异森林里的岩浆湖边找到",
海

2023-12-20 12:43 UTC, qznfbnj commented on projects/1.20-fabric/assets/lets-do-nethervinery/nethervinery/lang/zh_cn.json
> +  "item.vinery.grape.tooltip.item.nethervinery.warped_grape": "可以在诡异森林里的岩浆湖边找到",
找了半天可算找到了，感觉这不能叫湖吧……
![2023-12-20_20 38 58](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/100760086/b7dfd41a-87c4-42bd-9c5f-44b1ea0eff15)
![2023-12-20_20 39 10](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/100760086/bfb27008-44a3-4777-a777-f3bc545e122c)

2023-12-20 12:44 UTC, qznfbnj commented on projects/1.20-fabric/assets/lets-do-nethervinery/nethervinery/lang/zh_cn.json
> +  "item.vinery.grape.tooltip.item.nethervinery.warped_grape": "可以在位于诡异森林群系中的岩浆海边找到",
```suggestion
  "item.vinery.grape.tooltip.item.nethervinery.crimson_grape": "可以在位于绯红森林群系中的熔岩海边找到",
  "item.vinery.grape.tooltip.item.nethervinery.warped_grape": "可以在位于诡异森林群系中的熔岩海边找到",
```

2023-12-22 06:27 UTC, ChuijkYahus requested changes

2023-12-22 06:27 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/lets-do-nethervinery/nethervinery/lang/zh_cn.json
> +  "block.nethervinery.crimson_fermentation_barrel": "绯红陈化桶",
这里的Crimson如果指的是材质，推荐使用`绯红木`

2023-12-22 06:27 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/lets-do-nethervinery/nethervinery/lang/zh_cn.json
> +  "block.nethervinery.nether_fizz": "下界香槟",
非法国香槟产区生产的气泡酒不能叫“香槟”
建议还是改成`气泡酒`

2023-12-22 06:27 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/lets-do-nethervinery/nethervinery/lang/zh_cn.json
> +  "block.nethervinery.warped_fermentation_barrel": "诡异陈化桶",
同上方Crimson，如为材质，建议改为`诡异木`

2023-12-22 06:27 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/lets-do-nethervinery/nethervinery/lang/zh_cn.json
> +  "item.vinery.wine.block.nethervinery.nether_fizz": "将你传送至最近一次睡觉的坐标。\n\u00A74仅在主世界生效。\n\u00A7r不保证在下界或末地中使用是否有效-我们拒绝承担任何责任",
```suggestion
  "item.vinery.wine.block.nethervinery.nether_fizz": "将你传送至最近一次睡觉的坐标。\n\u00A74仅在主世界生效。\n\u00A7r不保证在下界或末地中使用是否有效，我们拒绝承担任何责任",
```
通查

2023-12-22 06:27 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/lets-do-nethervinery/nethervinery/lang/zh_cn.json
> +  "item.vinery.wine.block.nethervinery.netherite_nectar": "以高价换取一个短暂的生命提升",
```suggestion
  "item.vinery.wine.block.nethervinery.netherite_nectar": "昂贵但短暂的生命提升",
```
微调

2023-12-22 08:34 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/lets-do-nethervinery/nethervinery/lang/zh_cn.json
> +  "block.nethervinery.nether_fizz": "下界气泡酒",
话说这两种酒在游戏内是怎么制作的

2023-12-22 09:05 UTC, ChuijkYahus approved these changes
可以看下是否与库内的Vinery翻译一致

2023-12-23 04:03 UTC, qznfbnj commented
🌿，L34还真是增长率+10%（指每次遇到随机刻有10%几率额外生长）
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/100760086/f51ba962-13af-484a-b50f-f835e5a72f4b)

![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/100760086/a64ab08a-0398-4994-b7c4-9b4d11ff131a)

2023-12-30 23:57 UTC, merged