Sword Parry 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4024
Opened 2023-12-22 15:28 UTC by misaka15273

2023-12-23 07:48 UTC, ChuijkYahus requested changes
模组中的block和parry是否为同一操作
请注意检查汉化文件中block和parry的翻译，并统用词

2023-12-23 07:48 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/sword-parry/frycparry/lang/zh_cn.json
> +  "key.frycparry.key_parry": "格挡(设为空即为右键格挡)",
```suggestion
  "key.frycparry.key_parry": "格挡（设为空即为右键格挡）",
```
请注意使用全角标点，全文通查

2023-12-23 12:55 UTC, misaka15273 commented
> 模组中的block和parry是否为同一操作 请注意检查汉化文件中block和parry的翻译，并统用词

block和parry不是同一操作。block为格挡，仅有免伤作用；parry为招架，如果在格挡后的前某些刻（可设定）受到攻击可触发招架，招架除了有格挡的免伤作用还可以击退攻击者，并赋予攻击者虚弱和缓慢效果。

2024-01-01 13:58 UTC, ChuijkYahus requested changes

2024-01-01 13:58 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/sword-parry/frycparry/lang/zh_cn.json
> +  "key.frycparry.key_dont_parry": "禁用格挡",
```suggestion
  "key.frycparry.key_parry": "招架（设为空即为右键招架）",
  "key.frycparry.key_dont_parry": "禁用招架",
```
请注意统一block和parry的翻译用词

2024-01-01 13:58 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/sword-parry/frycparry/lang/zh_cn.json
> +  "enchantment.frycparry.parry_enchantment": "强化招架",
```suggestion
  "enchantment.frycparry.parry_enchantment": "招架",
```

2024-01-01 13:58 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/sword-parry/frycparry/lang/zh_cn.json
> +  "text.autoconfig.frycparry.option.enableBlockingWhenDualWielding.@Tooltip": "0 - 副手为空时能； 1 - 双持武器时也能；2 - 副手持有任何物品都能；",
```suggestion
  "text.autoconfig.frycparry.option.enableBlockingWhenDualWielding": "双持选项【需要重启】",
  "text.autoconfig.frycparry.option.enableBlockingWhenDualWielding.@Tooltip": "0 - 副手为空时能；1 - 双持武器时也能；2 - 副手持有任何物品都能；",
```
删去多余空格

2024-01-31 08:37 UTC, luoxueyasha commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。
@misaka15273

2024-02-02 01:56 UTC, luoxueyasha requested changes

2024-02-02 01:56 UTC, luoxueyasha commented on projects/1.20-fabric/assets/sword-parry/frycparry/lang/zh_cn.json
> +  "text.autoconfig.frycparry.option.disableBlockAfterParryingAxeAttack": "格挡来自斧头的攻击后禁用格挡",
原文`Disable block action after parrying axe attack`
根据你的描述，我的理解是：block=格挡，parry=招架，且输入时间窗口为 格挡-招架（瞬间）-格挡，即“招架是一种特殊的格挡”
那么这句的意思是“在parry了斧子攻击后禁用block操作”，如果前后都翻译成格挡的话是否会引起歧义？还是作者混用了两个词？

2024-02-02 06:43 UTC, misaka15273 commented on projects/1.20-fabric/assets/sword-parry/frycparry/lang/zh_cn.json
> +  "text.autoconfig.frycparry.option.disableBlockAfterParryingAxeAttack": "格挡来自斧头的攻击后禁用格挡",
招架也可以理解为弹反

2024-02-02 08:10 UTC, luoxueyasha commented on projects/1.20-fabric/assets/sword-parry/frycparry/lang/zh_cn.json
> +  "text.autoconfig.frycparry.option.disableBlockAfterParryingAxeAttack": "格挡来自斧头的攻击后禁用格挡",
建议这类混用问题全文查一下，防止有遗漏

2024-02-03 05:35 UTC, luoxueyasha commented on projects/1.20-fabric/assets/sword-parry/frycparry/lang/zh_cn.json
> +  "text.autoconfig.frycparry.option.shieldDisarmAfterParry": "被该物品招架后导致的缴械时间（只对玩家有用）",
```suggestion
  "text.autoconfig.frycparry.option.shieldDisarmAfterParry": "被该物品招架后导致的缴械时间（只对玩家生效）",
```
`有用`有些口语化了

2024-02-10 10:16 UTC, luoxueyasha approved these changes

2024-02-11 05:55 UTC, luoxueyasha commented
ping @ChuijkYahus

2024-02-12 13:35 UTC, ChuijkYahus commented
这个方头括号OK就没问题

2024-02-12 13:36 UTC, ChuijkYahus approved these changes

2024-02-12 23:55 UTC, merged