提交exblades的翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #4033
Opened 2023-12-27 16:45 UTC by RuafuMan-Obs

2023-12-30 23:55 UTC, luoxueyasha commented
请将pr标题修改为形如“ex-blades 翻译提交”的格式

2024-01-02 11:15 UTC, luoxueyasha commented
为什么中文语言文件和英文语言文件行数不一致？尤其是1.20下差别较大

2024-01-02 12:17 UTC, RuafuMan-Obs commented
> 为什么中文语言文件和英文语言文件行数不一致？尤其是1.20下差别较大

作为该mod的重置发布者我将进度树进行了彻底重写，英文文件内涉及进度的翻译已经不再需要，但没动，因为依旧能用

2024-01-03 11:06 UTC, luoxueyasha commented
> 作为该mod的重置发布者我将进度树进行了彻底重写，英文文件内涉及进度的翻译已经不再需要，但没动，因为依旧能用

重置发布的链接？好像没翻到
而且拔刀日系附属不是国人做的吗（

2024-01-03 15:16 UTC, RuafuMan-Obs commented
> > 作为该mod的重置发布者我将进度树进行了彻底重写，英文文件内涉及进度的翻译已经不再需要，但没动，因为依旧能用
> 
> 重置发布的链接？好像没翻到 而且拔刀日系附属不是国人做的吗（ 还有，mod撞curseforgeid了

https://www.curseforge.com/minecraft/mc-mods/slashblade-japanese-addon-pack-reforked
也挺无奈的，因为我的技术力仅限于做数值和配方与进度树的修复优化，没本事直接把命名空间整个大改

2024-01-04 02:32 UTC, luoxueyasha commented
> 也挺无奈的，因为我的技术力仅限于做数值和配方与进度树的修复优化，没本事直接把命名空间整个大改

没太理解，所以说这个pr是你自己的模组的汉化？
请问您的第一语言/母语是中文吗？如果是的话，我觉得将这些语言文件放在你自己的模组里就行了，没必要丢到i18n库里
因为i18n本质上是通过加载资源包的方式完成汉化的，如果你的模组后续有更新或命名改动，那么i18n的旧版语言文件会优先覆盖你的模组语言显示

2024-01-04 03:46 UTC, RuafuMan-Obs commented
> > 也挺无奈的，因为我的技术力仅限于做数值和配方与进度树的修复优化，没本事直接把命名空间整个大改
> 
> 没太理解，所以说这个pr是你自己的模组的汉化？ 请问您的第一语言/母语是中文吗？如果是的话，我觉得将这些语言文件放在你自己的模组里就行了，没必要丢到i18n库里 因为i18n本质上是通过加载资源包的方式完成汉化的，如果你的模组后续有更新或命名改动，那么i18n的旧版语言文件会优先覆盖你的模组语言显示

因为，现在i18n里所带的语言文件会覆盖我的，所以在这上头提交一个我的版本

2024-01-04 08:12 UTC, luoxueyasha commented
> 因为该模组是基于一个已停更且没有curseforge官网的简陋旧版进行的修正重做并在curseforge发布，现在i18n里所带的旧版语言文件存在名称错漏，描述错漏而且会覆盖我的，所以在这上头提交一个我的版本

感觉越说越迷糊了，咱先整理一下信息（
1. 旧模组（旧版，无curseforge）是哪个模组，其发布地址是哪里，其名空间是什么，对应哪些个Minecraft版本？
2. 目前我看你上传的语言文件路径如`projects/版本号/assets/exblades/exblades/lang/zh_cn.json`。根据bot的提示，Curseforge ID为`exblades`的模组是[另一个模组](https://www.curseforge.com/minecraft/mc-mods/exblades)，而你的项目的Curseforge ID为`slashblade-japanese-addon-pack-reforked
`。感觉应该移动文件路径至如`projects/版本号/assets/slashblade-japanese-addon-pack-reforked/exblades/lang/zh_cn.json` 的路径上。
3. 然后再说说撞命名空间的问题。根据你的描述，你的能力不足以修改模组的命名空间，所以目前命名空间是和有冲突的吗？是和1.里的“旧模组”冲突，还是和2.里的exblades上冲突？
* 顺带一提解决命名空间冲突一般只要修改java包名与工程路径即可，可能需要把gradle/maven的构建配置文件一并改掉。
4. 原则上我们不收中文为第一语言的pr（因为没有翻译的必要）。虽然原因不明，我看库里是有以前版本的语言文件的，如果有需要的话我们可以协助删除。

2024-01-04 08:18 UTC, luoxueyasha commented
> @RuafuMan-Obs 
看了一下文件历史，库里的拔刀剑日系附属内容来源于上古时期，感觉可以删（？

2024-01-04 08:21 UTC, RuafuMan-Obs commented
> > @RuafuMan-Obs
> 
> 看了一下文件历史，库里的拔刀剑日系附属内容来源于上古时期，感觉可以删（？

可以，我解包了curseforge上的同名模组，是个仅有1.16.5一个版本的貌似不会再更新的模组，但同命名空间的问题确实存在，要不就把库里旧版的都删掉吧，如果我能搞清楚命名空间的问题，也会在后续版本重写命名

2024-01-04 11:27 UTC, luoxueyasha commented
最新调查结果：
exblades的作者是拔刀剑本体作者flammpfeil
但是并没有在cf上发布
发布地址：https://w.atwiki.jp/slashblade/pages/49.html

所以文件不能删除，pr提交者的版本属于是撞名空间了
不过flammpfeil的这个版本可能需要移动到1UNKNOWN下？

2024-01-04 15:43 UTC, RuafuMan-Obs commented
重新提交了修正翻译以替换主库里存在的错漏翻译，无论是原版还是修正版均运作良好

2024-01-04 22:32 UTC, luoxueyasha requested changes

2024-01-04 22:32 UTC, luoxueyasha commented on projects/1.18/assets/exblades/exblades/lang/zh_cn.json
> -  "exblades.desc": "更高版本的附属！",
1. 鉴于作者是日本人，请一并上传附带的ja_jp文件以供审阅
2. 由于这个模组的分发并非通过curseforge，请将此文件夹下的所有内容一并移动至`projects/1.18/assets/1UNKNOWN/exblades/lang/`下，并删除现在的这个文件夹

2024-01-05 15:21 UTC, luoxueyasha reviewed
neta太多了 先放着一个一个看

2024-01-06 00:29 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.wanderer.material": "刀拵-风来",
#4036
建议商量一下

2024-01-06 10:11 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.zephyr": "龍太刀「西風」",
来自MH3U/MHGen（欧美那边的代号）的Zephyr太刀
https://github.com/flammpfeil/SlashBladeZephyr
作者甚至做了个独立的附属

2024-01-06 10:53 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.murasamablade": "高频震动刀「村雨」",
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/ab324e2a-62be-4990-ac9e-7dd53cb27c05)
 *Let's Dance.*
出自《合金装备崛起 复仇》，山姆的爱刀

2024-01-06 10:53 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.vanilla.wooden": "「击柝」露台",
这五个对应原版的木、石、铁、金、钻石
`露台`是怎么翻出来的？

2024-01-06 12:09 UTC, luoxueyasha reviewed
备考：https://minecraftjapan.miraheze.org/wiki/MOD%E8%A7%A3%E8%AA%AC/SlashBladeMod/%E3%82%A2%E3%83%89%E3%82%AA%E3%83%B3_1.7.10

2024-01-06 12:09 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.wa.katana": "名刀-「红梅」",
这些除了苍梅有个`利刃「苍梅」`之外，没有找到别的
备考：
苍梅来自[CustomStuff2でオリジナル抜刀剣を作るキット](https://web.archive.org/web/20190628162025/http://forum.minecraftuser.jp/download/file.php?id=48759)
是CustomStuff2的拔刀剑自定义教程的范例

2024-01-06 12:09 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "exblades.name": "拔刀剑 秘传",
原发布帖（老ja论坛）：https://forum.minecraftuser.jp/viewtopic.php?f=13&t=2150

2024-01-06 12:09 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.yamato": "阎魔刀",
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/9352deb6-33a0-4784-88fa-f842e6b7179a)
出自《鬼泣》系列的阎魔刀
……不过作者开发的时候只有《鬼泣4》

2024-01-06 13:04 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.kamuy.water": "神威刀-「乌卡」",
实为错考，应该没有这个延伸
但是读法还是瓦卡
```suggestion
  "item.slashblade.ex.kamuy.water": "神威刀-「瓦卡」",
```

2024-01-06 13:04 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.frostwolf.cold": "冻樱刃-「雪花苍月」",
https://twitter.com/wiluga/status/620634910974324737
https://twitter.com/nagisahayate/status/1141043928285581312
是wiluga自家的看板娘
设定上还有两刀合一的`霊獣刃「天瑞花桜」`，不过似乎没有做进去

2024-01-06 14:11 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.wanderer.material": "刀拵-风来",
群里商量了
```suggestion
  "item.slashblade.ex.wanderer.material": "刀组件「风来」",
```

2024-01-06 14:27 UTC, luoxueyasha requested changes

2024-01-06 14:27 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.agito.rf.material": "刀组件-蓝绳",
原文：`刀剣の素材箱「赤紐」`

2024-01-06 14:28 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.agito.rt.material": "刀组件-红绳",
原文`刀剣の素材箱「青紐」`

2024-01-07 05:17 UTC, luoxueyasha requested changes

2024-01-07 05:17 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.wanderer.material": "刀组件-风来",
```suggestion
  "item.slashblade.ex.wanderer.material": "刀组件「风来」",
```
全文的刀组件都需以此格式翻译（`刀组件「XX」`，XX为刀组件自身的名字），我们在群里讨论过了
请以原文为准并全文通查

2024-01-07 05:22 UTC, luoxueyasha requested changes

2024-01-07 05:22 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.wa.daitou.desc": "朴实无华的刚刀\n其锋锐之刃能斩穿躯体砍入大地",
还是翻的和我的理解有偏差
请你解释你对这句的翻译思路
`名の通りを能うる称号\n同でも太でもない無銘の大業物`

2024-01-07 09:05 UTC, luoxueyasha requested changes

2024-01-07 09:05 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.zephyr": "龍太刀「西風」",
```suggestion
  "item.slashblade.ex.zephyr": "龙太刀「西风」",
```
请使用简体汉字
此问题请全文通查

2024-01-07 09:05 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.terra.material": "刀组件「泰拉」",
原文`刀剣の素材箱「大地」`
```suggestion
  "item.slashblade.ex.terra.material": "刀组件「大地」",
```
**请遵循原文**，此类问题请全文通查

2024-01-07 09:30 UTC, luoxueyasha reviewed
你的回复可能在pending状态，我看不见
记得每次批量回复都检查一下，有没有成功公开
 pending状态的回复如下
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/6f191dca-4c4b-4aeb-8528-b193d0260cdc)

2024-01-07 09:30 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.yamato": "阎魔刀",
阎魔刀对应的key到底是哪个？

2024-01-07 09:30 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.wa.daitou.desc": "名副其实的刚刀\n能斩穿躯体砍入大地的锋锐之刃",
句义漏翻
原文`名の通りを能うる称号\n同でも太でもない無銘の大業物`
请解释`同でも太でもない`

2024-01-07 09:30 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.agito.rt.material": "刀组件「青柄」",
实际玩了一下，感觉是作者瞎填key，红绳和蓝绳填反了
红绳才能合大蛇鄂门
和柄半点关系没有

2024-01-07 09:38 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> -  "item.slashblade.ex.agito.rt.desc": "刀身被铁锈所覆盖,传承了众星之力的刀,其仿作多如牛毛",
麻烦解释一下真鄂门锈和假鄂门锈的描述的区别
真：`錆びに埋もれた`
假：`錆び付いた`

2024-01-07 09:38 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.yukari.desc": "EX 因缘",
?
解释一下

2024-01-07 09:42 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.witherblade.desc": "凋灵之力",
为什么改成`凋灵`而非`凋零`？有什么原因吗？
需要pr提交者进行回复并解释，而非直接进行commit

2024-01-10 10:22 UTC, luoxueyasha requested changes

2024-01-10 10:22 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.fluorescentbar.desc": "于星间穿梭时随兴制作的刀\n与原型不同,十分坚固",
```suggestion
  "item.slashblade.ex.fluorescentbar.desc": "于星间穿梭时随兴制作的刀\n与原型不同，十分坚固",
```
全角标点问题
全文通查

2024-01-10 10:22 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.yukari.desc": "秘剑 结月缘",
不能这么翻，这里是个结月缘ex的双关
https://www.ah-soft.com/voiceroid/yukari_ex/

2024-01-10 10:43 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.fluorescentbar.desc": "于星间穿梭时随兴制作的刀\n与原型不同,十分坚固",
```suggestion
  "item.slashblade.ex.fluorescentbar.desc": "于星间穿梭时随兴制作的刀\n与原型不同，十分坚固",
```
？

2024-01-12 13:46 UTC, luoxueyasha reviewed
很气 但还是要保持微笑
真的很想自己重译一份了

2024-01-12 13:46 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.fluorescentbar.desc": "于星间穿梭时随兴制作的刀\n与原型不同，十分坚固",
ja文件没有这行描述，确定要加吗
要加就所有的刀都加

2024-01-12 13:46 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.toyako.desc": "白夜叉",
同上

2024-01-12 13:46 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.kamuy.base.material": "刀组件「虎杖丸」",
原文`刀剣の素材箱「神威」`
全文通查

2024-01-12 14:39 UTC, RuafuMan-Obs commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.fluorescentbar.desc": "于星间穿梭时随兴制作的刀\n与原型不同，十分坚固",
啥，是说要让这行缺着吗

2024-01-12 14:40 UTC, RuafuMan-Obs commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.toyako.desc": "白夜叉",
因为作者疏忽没有任何一种语言的描述游戏中直接key外露（

2024-01-12 14:45 UTC, RuafuMan-Obs commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.kamuy.base.material": "刀组件「虎杖丸」",
更正四把神威组件名

2024-01-12 15:00 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.fluorescentbar.desc": "于星间穿梭时随兴制作的刀\n与原型不同，十分坚固",
en有ja没有，以en为原文
那是翻不出前面这半句的

2024-01-13 23:24 UTC, luoxueyasha commented on projects/1.18/assets/1UNKNOWN/exblades/lang/zh_cn.json
> +  "item.slashblade.ex.toyako.desc": "白夜叉",
那就先留空吧

2024-01-14 09:25 UTC, luoxueyasha commented
| 刀中文名 | 描述 | 修改理由 | 备注 |
|---|---|---|---|
| 荧光灯管 | 十分的坚固 | 主要是删去上一版的1710描述，由于已分在PSO2分类里故不标明原型 | PSO2的荧光灯在攻击时会带有灯泡破碎的特效 |
| 洞爷湖 | 白夜叉 | 出自《银魂》对主角坂田银时的称呼，**洞爷湖**为其武器。文本继承自1710的描述，不然游戏内会直接显示key名 |  |
| 风来之剑 | 来自沙漠之魔城深处的刀 | 原型为《风来的西林GB2 **沙漠之魔城**》，并且日语/英语文件中提及原型 |  |
| 次元拔刀 | 某名学园的炼金术士剑士的爱刀 | 原型为《玛娜传奇～**学园里的炼金术士**们～》（炼金工房系列第9作）中角色安娜·蕾姆莉的初始武器，并且日语/英语文件中提及原型 | 原名幻魔炼金拵，为该角色的毕业武器，现与日文原文一并修改 |
| 泰拉刃 | 来自泰拉大地的利刃 | 原型为《泰拉瑞亚》的武器**泰拉刃**，原文上下文玩了terra的音译和意译双关 |  |
| 神威刀「虎杖丸」 | 神威之力寄宿之器 | 原型为日本阿伊努族的神话，且日语的**神威**（カムイ）也来源于该族的阿伊努语，不需特意标注 | 刀名与模型来自这个视频的附属，不过感觉不好往里加内容（https://www.nicovideo.jp/watch/sm26300274 ） |
| 神威刀「瓦卡」 | 流水之神威 | 三把刀均为阿伊努语的词汇，分别对应其描述的日文汉字，不需特意标注 |  |
| 神威刀「阿贝」 | 火焰之神威 | 同上 |  |
| 神威刀「坎那」 | 天雷之神威 | 同上 |  |
| 西风 | 打猎时用的龙太刀 | 原型为MH3U/MHGen的Zephyr太刀，国内MHG官译为“**西风**” |  |
| 村雨 | 高周波震动刀，小子 | "原型为《合金装备崛起：复仇》的刀。“**高周波**”即高频，继承社区对该类武器一贯的称呼<br />“，小子”出自同作品的“纳米装甲，小子”梗，也与这把刀有关" |  |
| 击柝 | 带鞘的木剑 | 与原版命名一致 |  |
| 锐岩 | 带鞘的石剑 | 同上 |  |
| 黑铁 | 带鞘的铁剑 | 同上 |  |
| 山吹 | 带鞘的金剑 | 同上 |  |
| 金刚 | 带鞘的钻石剑 | 同上 |  |
| 圣幸刀「绿乃雾」 | （自称）剑圣的杰作 \-幸\- | "出自《【Minecraft】**（自称）剣聖**ゆかりの異世界一周の旅　十一振り目【MystCraft】》，观众投稿的三把刀的名字<br />原版的圣幸刀是随机附魔的村正\+锋利5、耐久2、投射物伤害1，确实很欧；炎水是预定村正\+火焰附加、水下呼吸、掉落物增加；<br />吹雪是预定不死杀手、荆棘、爆炸抗性" | https://www.nicovideo.jp/watch/sm25006287 |
| 侍月刀「炎水薄斩」 | （自称）剑圣的杰作 \-合\- | 同上 |  |
| 月光樱「吹雪一闪」 | （自称）剑圣的杰作 \-雪\- | 同上 |  |
| 冻樱刃「雪花苍月」 | 冰狼之爪 |  @wiluga （水石雪斗）的看板娘的武器，desc直接翻译的日文 | 设定上还有两刀合一的霊獣刃「天瑞花桜」，不过似乎没有做进去<br />（https://twitter.com/wiluga/status/620634910974324737 ） |
| 明兽刃「阳牙冰狼」 | 冰狼之牙 |  |  |
| 妖刀「似蛭」 | 黑暗 | 出自手冢治虫的《多罗罗》，里面的武器就叫**妖刀“似蛭”**，会不断**嗜血**最终吞噬使用者<br />流传度还算广（搜似蛭能查到），就不作标注了 | 日文原文每条就1个汉字 |
| 血刀「似蛭」 | 嗜血 | 同上 |  |
| 狱刀「似蛭」 | 深渊 | 同上 |  |
| 妖刀「紅樱」 | 殷红 | 同上 |  |
| 炼狱刀「死念」 | 终焉 | 同上 |  |
| 枯石太刀 | 凋灵之力 | 1\.12\.2通过**凋灵**的生成爆炸波及挂有无铭的刀挂台获得，模型继承自西风太刀，但与怪猎无关<br />现版本改为使用下界之星合成 |  |
| 大蛇鄂门 | 杰作 | 均为PSO2的鄂门，甚至玩了PSO的真假鄂门锈刀梗，由于已分在PSO2分类里故不标明原型<br />均为日文直译<br />假鄂门的描述为“习作”是因为需要与拔刀剑本体的银纸竹光的“仿作”区分，两个是不同的方向 |  |
| 鄂门 | 真品 | 同上 |  |
| 锈蚀鄂门 | 被锈迹掩盖 | 同上 |  |
| 鄂门 | 习作 | 同上 |  |
| 锈蚀鄂门 | 锈迹斑斑 | 同上 |  |
| 木刀「铁刀木」 | 坚硬如铁的木刀 | 原型为同名植物铁刀木（Senna siamea/タガヤサン） |  |
| 守墓人 | 接着，星期天神舍弃了世界 | 原型为《神不在的星期天》，日语/英语均已提及原型<br />原句出自动画版第1集，作品设定为“**神在第七天舍弃了世界**，人们无法真正地死去，只能通过 **守墓人/墓守** 埋葬死者以获得安息”<br />武器为主角的铲子，但作品中仅将这把铲子叫做铲子 |  |
| 红梅 | 红花 | 苍梅出自作者1\.7\.10时期的拔刀剑附属制作教程（CustomStuff2でオリジナル抜刀剣を作るキット）中的demo，只有一把“利刃「苍梅」”<br />揣测作者的意图为对demo的轻度修改，故仅保留原文最小意思 | 其实日语和英语原文都是XX flower，我甚至都想不翻译 |
| 黄梅 | 黄花 | 同上 |  |
| 苍梅 | 蓝花 | 同上 |  |
| 锈刀 | 腐朽的刀 | 也是PSO的鄂门锈刀梗，但是模组里并没有与鄂门相关<br />1\.12\.2为野生僵尸随机持有，现在为棕色蘑菇参与合成 |  |
| 刚剑「胴田贯」 | "名副“贯穿胴体直至田地”其实的\\n反出其形、刀身匀称的无铭之大业物""" | 日语直译<br />原文`名の通りを能うる称号\\n同でも太でもない無銘の大業物`<br />`胴田贯`的本意（之一）即能切穿胴体直至下面的田地的刀（另一说是地名）<br />现实的胴田贯的刀身粗大厚重，这里也说了是与现实反而行之，刀身不厚<br />大业物即异常锋利的刀，但是感觉可以专有名词了\+内容太长了 |  |
| 暗鸦 | 黑暗的鸦之太刀 | 原型为PSO2的刀，但名字是读音片假名，描述是英文，刀组件的名字是汉字写法，只能拆文解释 |  |
| 雪鸦 | 雪白的鸦之太刀 | 同暗鸦 |  |
| 结月刀「因缘」 | 结月之缘的EX形态 | 原型是结月缘，同时玩了当时刚发售的声库《Voiceroid EX\+ 结月缘》的梗，同时又是结月刀的升级形态；并且没有完整提到过结月缘的全名 |  |
| 散华 | 传说的四刀之一 | 原型为PSO的传说四刀，作者直接名字用读音片假名、描述汉字，只能用PSO的资料填上 |  |
| 夜叉 | 传说的四刀之一 | 同散华 |  |
| 天丛云 | 集纯粹救世之愿于一身的神剑 | 同散华，直接挪用PSO2NGS的`全てを救いたいという純粋なお願いの形`和PSO2NGS的剧情称呼“神代三剑之一” |  |
| 魔剑「阎魔刀」 | YAMATOOooo！ | 原型出自《鬼泣》系列。描述暂时挪用日文/英文文件，梗源在向作者询问，推测为海贼王角色“大和”（Yamato）与远古老梗“YOOOOO”的结合 | 想替换成“嘿维吉尔，你动不动打开传送门的日子结束了” |
| 碎龙太刀 | 粉碎猎物的龙太刀 | 原型为《怪猎》的碎龙太刀，在原作中确实是以爆炸为攻击手段 |  |

2024-01-15 10:58 UTC, luoxueyasha requested changes
详见上一条评论

2024-02-01 06:04 UTC, luoxueyasha commented
时间：北京2024年2月1日14：00
目前投票已截止，最后 原文（鬼泣4）：更改（鬼泣5） 的投票数为4：11，将对译文进行修改。
阎魔刀的进度描述将采用鬼泣5里的梗（且很可能是与那两个男人和那个椅子mod相关的梗）。
@RuafuMan-Obs 你定一下采用哪句吧

2024-02-01 06:06 UTC, RuafuMan-Obs commented
> 时间：北京2024年2月1日14：00 目前投票已截止，最后 原文（鬼泣4）：更改（鬼泣5） 的投票数为4：11，将对译文进行修改。 阎魔刀的进度描述将采用鬼泣5里的梗（且很可能是与那两个男人和那个椅子mod相关的梗）。 @RuafuMan-Obs 你定一下采用哪句吧

那就用刻在大病区众人dna里的那个场景对白罢，至于细节要不在群里问问？

2024-02-12 09:48 UTC, luoxueyasha approved these changes

2024-10-13 03:00 UTC, luoxueyasha commented
已公示：https://bbs.mcmod.cn/forum.php?mod=viewthread&tid=19893
可于14+7日（2024.11.4 0点后）合并

2024-11-05 08:01 UTC, merged