提交翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #4036
Opened 2023-12-29 11:42 UTC by Lmy1503

2023-12-30 23:54 UTC, luoxueyasha commented
请修改pr标题形如“模组英文名 游戏版本号 翻译提交”的格式，可以参考其他pr
以及，拔刀剑的作者母语为日语，因此我们需要您同时上传一份日文原文以作审阅

2024-01-03 11:09 UTC, luoxueyasha reviewed
可以先看一下 #3126 的拔刀剑1翻译

2024-01-03 11:11 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "attribute.name.generic.reachDistance":"触及距离",
其效果是？是所谓的“攻击范围”吗？

2024-01-03 11:13 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "itemGroup.slashblade.desc": "抵达修罗之境",
这个itemgroup里面包括什么？
一般情况下，我们对创造模式工具栏的命名格式为`模组名丨其他内容`（中间的是汉字丨（滚3）），例如`拔刀剑丨修罗之境`

2024-01-03 11:14 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "slashblade.tooltip.material.enchantments": "附魔",
原文`必要エンチャント`
请问这里是“必需带有这种附魔属性才能合成”吗

2024-01-03 11:16 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "item.slashblade.simple.wood.desc": "赋予刀鞘的木剑",
```suggestion
  "item.slashblade.simple.wood.desc": "带鞘的木刀",
```

```suggestion
  "item.slashblade.simple.wood.desc": "带刀鞘的木刀",
```
看原文是木刀而不是原版的木剑
具体请以游戏内贴图为准

2024-01-03 11:17 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "item.slashblade.simple.white.desc": "铁制的刀身",
```suggestion
  "item.slashblade.simple.white.desc": "铁制刀身",
```

```suggestion
  "item.slashblade.simple.white.desc": "铁刀身",
```

至于是`铁质`还是`铁制`，这个建议讨论一下，然后模组内全文统一

2024-01-03 11:18 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "item.slashblade.simple.white.material": "刀组件「白鞘」",
```suggestion
  "item.slashblade.simple.white.material": "刀组件「白」",
```
原文`刀剣の材料箱「白」`
此类问题请全文通查

2024-01-03 11:23 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "item.slashblade.simple.bamboo.desc": "未完成的仿刀",
枪械有个说法叫`仿真枪`
原文`模造刀`是二战后日本的枪炮管理法，根据杀伤力区分`真剣`和`模造刀`
总之“仿刀”/“仿造刀”感觉不太行（因为原意确实不是模仿），国内交流也有使用汉字直译“模造刀”的
无论采用哪种说法，请全文统一

2024-01-03 11:27 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "item.slashblade.simple.silverbamboo.desc": "仿造刀，但是竹刀",
原文`模造刀`
不建议这么塞私货，除非真的需要和人解释
塞私货会给审查、后续译文更新和玩家带来不少困扰

2024-01-03 11:30 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "item.slashblade.ex.fox.white.desc": "招来幸运的白狐",
原文`幸運の標`
这类desc建议整理成表，说明一下译者思路
以及它们在游戏中的显示方式是什么样的？

2024-01-04 13:27 UTC, luoxueyasha commented
你最新做出的修改很奇怪，但是我并没有看到你的回复
你的回复可能在pending状态，这种情况下需要在github网页端的审阅意见右上角处点击提交才能显示

2024-01-05 06:14 UTC, Lmy1503 reviewed
翻译修正

2024-01-05 07:36 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "attribute.name.generic.reachDistance":"触及距离",
1.16.5也可能需要一次大修，因为可能不是以日文为原文进行的翻译
请尽量不要参考那个版本的译文

2024-01-05 07:36 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "itemGroup.slashblade.desc": "抵达修罗之境",
游戏中的显示情况？看key名像是创造模式标签

2024-01-05 07:38 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "slashblade.tooltip.material.enchantments": "附魔",
我记得1.12白鞘的附魔（还是啥来着）会影响下一步的产品，1.16及更高版本有继承这个合成表吗

2024-01-05 07:39 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "item.slashblade.simple.white.material": "刀组件「白鞘」",
请问在qq群里吗？感觉这个得讨论一下

2024-01-05 07:40 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "item.slashblade.simple.bamboo.desc": "未完成的仿刀",
同上，1.16.5的翻译可能并不准确，请尽量不要参考那个版本

2024-01-05 11:32 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "slashblade.tooltip.material.enchantments": "附魔",
从1.14.4开始拔刀剑2,，想对之前的版本重做了。拔刀剑2的合成方式完全发生了变化，必须要做个箱子，然后收集资源和箱子合成刀组件，然后刀组件上会显示锻刀条件，满足条件之后在铁砧上把刀组件敲到刀上完成新的刀

2024-01-05 11:35 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "item.slashblade.simple.white.material": "刀组件「白鞘」",
群号能发一下吗，我每天也就晚上有时间就会看看翻译

2024-01-05 11:36 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "item.slashblade.simple.bamboo.desc": "未完成的仿刀",
好的

2024-01-05 12:51 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "item.slashblade.simple.white.material": "刀组件「白鞘」",
已经加入qq群了，昵称梦眠未央

2024-01-06 05:02 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "slashblade.tooltip.killcount": "杀敌数：%1$s",
幻影剑实体命名，这里是补充

2024-01-06 05:19 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "item.slashblade.simple.silverbamboo.desc": "仿虽是竹光的完成型，但终究是竹刀",
去查了下模造刀然后根据游戏mod的意思就是表示这是把仿造刀

2024-01-06 06:52 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +
这个暂时保持后一段不变，我不太知道这个是不是有梗

2024-01-06 06:57 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "item.slashblade.bladestand_s": "立式短刀挂",
对刀挂实体的补充

2024-01-06 08:52 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +
暂定，肯定有问题

2024-01-06 09:25 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.combo_a.desc": "使用按键\n攻击 ♠:%s\n在地上\n♠-♠-♠-♠",
原文
```
使用ボタン
攻撃 ♠:%s
地上で
♠-♠-♠-♠
```
这个黑桃在游戏中的显示情况是？
然后`使用按键`、`在地上`读着有点怪

2024-01-06 09:25 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.aerial_a": "剑技 -御空刀舞 A-       ",
应该全是鬼泣5的技能译名
建议核对

2024-01-06 09:25 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "slashblade.tooltip.material.requiredobjects.anvil": "合成要求场所：铁砧",
```suggestion
  "slashblade.tooltip.material.requiredobjects.anvil": "合成场所：铁砧",
```

2024-01-06 09:25 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "slashblade.tooltip.material.killcount": "%1$s <= 杀敌数",
```suggestion
  "slashblade.tooltip.material.killcount": "杀敌数 不小于 %1$s",
```
或者使用`≥`、`≤`
以下也是，不过建议看看游戏内能否正常显示

2024-01-06 09:25 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.spiral_swords.desc": "消耗5经验值在自身周围形成幻影剑圆阵。\n使用按键\n%s ♠:%s\n♠ 按住",
这里是消耗5经验值还是5经验等级？

2024-01-06 09:25 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.exeffect": "附魔效果",
```suggestion
  "adv.slashblade.exeffect": "附魔增效",
```
这个的具体“增强”是指？

2024-01-06 09:25 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.exeffect.soul_speed.desc": "格挡的指令输入时间会随着灵魂疾行的等级提升延长1tick。",
```suggestion
  "adv.slashblade.exeffect.soul_speed.desc": "格挡指令的输入时间会随着灵魂疾行的等级提升，每1级延长1tick。",
```
原文`ジャスト入力の受付時間がSoulSpeedのレベル1毎に1tick延長されます`
感觉有点怪

2024-01-06 09:25 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.exeffect.feather_falling.desc": "缓降的等级对应空中行动中缓降速度。"
？

2024-01-06 09:40 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "slashblade.tooltip.material.killcount": "%1$s <= 杀敌数",
这里显示是正常的

2024-01-06 09:40 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "slashblade.tooltip.material.enchantments": "附魔",
![QQ截图20240106173643](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/113871962/f46b65d4-ac55-4e5f-9283-ce68841210a7)
这种，并不需要jei，可以直接在刀组件上看到

2024-01-06 09:40 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "item.slashblade.proudsoul_tiny.dark":"正在孕育中的破碎的耀魂",
有用的试了，
![Uploading QQ截图20240106174009.png…]()

2024-01-06 09:41 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "item.slashblade.proudsoul_tiny.dark":"正在孕育中的破碎的耀魂",
有用的
![Uploading QQ截图20240106174009.png…]()

2024-01-06 09:42 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "item.slashblade.proudsoul_tiny.dark":"正在孕育中的破碎的耀魂",
有用的
![QQ截图20240106174009](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/113871962/69fe88cf-17ad-47c0-91e9-fa58fcc14ef8)
![QQ截图20240106174054](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/113871962/56622302-8fb9-4a63-9c44-7b7a644a89f5)

2024-01-06 09:44 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.combo_a.desc": "使用按键\n攻击 ♠:%s\n在地上\n♠-♠-♠-♠",
这个显示没有问题
![QQ截图20240106174335](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/113871962/4088aa84-8478-43eb-be40-2fc9ce31274f)
![QQ截图20240106174347](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/113871962/2f487801-60d9-48b8-b8d0-aa2e2a6ed8b1)
![QQ截图20240106174355](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/113871962/df8eb079-188c-4aab-ad45-838b41d55960)

2024-01-06 09:45 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.spiral_swords.desc": "消耗5经验值在自身周围形成幻影剑圆阵。\n使用按键\n%s ♠:%s\n♠ 按住",
消耗的是经验值

2024-01-06 09:47 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.exeffect": "附魔效果",
目前只有下边两个附魔对游戏内有一点点的提升效果，一个是灵魂疾行给予的拔刀剑格挡弹射物，一个是缓降效果影响滞空

2024-01-06 09:48 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.exeffect.feather_falling.desc": "缓降的等级对应空中行动中缓降速度。"
这个暂时没在游戏试出来==，也找不到对应的效果

2024-01-06 14:14 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.combo_a.desc": "使用按键\n攻击 ♠:%s\n在地上\n♠-♠-♠-♠",
搓招表的表述有点奇怪
咱换个表达方式……？

2024-01-06 14:14 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.spiral_swords.desc": "消耗5经验值在自身周围形成幻影剑圆阵。\n使用按键\n%s ♠:%s\n♠ 按住",
```suggestion
  "adv.slashblade.spiral_swords.desc": "消耗5点经验值，在自身周围形成幻影剑圆阵。\n使用按键\n%s ♠:%s\n♠ 按住",
```

2024-01-06 14:14 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.exeffect.feather_falling.desc": "缓降的等级对应空中行动中缓降速度。"
装一下exblades，然后拿一下`Kamuy-tempest-`（神威刀-「坎那」 ）试试

2024-01-06 14:16 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "slashblade.tooltip.material.killcount": "%1$s <= 杀敌数",
还是建议像我这么写比较好，要不然看着容易猛

2024-01-06 14:20 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "entity.slashblade.blade_stand_entity": "刀挂",
旧版本是叫刀挂台吧

2024-01-06 14:25 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.proudsoul": "强化限制=50\n利刃易折\n折断后被继承的骄傲灵魂",
原文`折れど継がれる誇り高き魂`
麻烦讲一下翻译思路吧，我怎么感觉和我想的不太一致
例如`誇り高き`是高傲、孤高的意思，还有“易折”是哪来的

以下这些到L84都是，需要解释你的翻译思路，建议使用markdown表格

2024-01-06 14:25 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.bladestand.desc":"刀剑安息之处",
？
安息是不是有点

2024-01-06 14:25 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.imitation_broken": "赝品",
这个进度是指？
模造刀吗

2024-01-07 05:02 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "slashblade.tooltip.material.killcount": "%1$s <= 杀敌数",
好的

2024-01-07 05:11 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "entity.slashblade.blade_stand_entity": "刀挂",
好的

2024-01-07 05:38 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "item.slashblade.proudsoul_tiny.dark":"破碎的耀魂之茧",
襁褓中的破碎的耀魂和破碎的耀魂之茧
我感觉可以搞后者

2024-01-07 05:52 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.bladestand.desc":"刀剑安息之处",
暂歇吧

2024-01-07 06:06 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.combo_a.desc": "使用按键\n攻击 ♠:%s\n在地上\n♠-♠-♠-♠",
原文就是这个意思
先把使用的按键列出来，然后每个按键标上符号
然后下边是出招表类似的
不过可以在下边补一下“出招表：”

2024-01-07 07:59 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "attribute.name.generic.reachDistance":"触及距离",
这个我保持原文把

2024-01-07 08:28 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.exeffect.feather_falling.desc": "缓降的等级对应空中行动中缓降速度。"
疑似并未实装

2024-01-07 09:42 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.proudsoul_activated":"摇动他们的代价是无底的饥饿\n耀偏方三八面魂会在潜行使用中活性化\n拿在手边会被饥饿侵袭\n饥饿中会更加饥饿换取刀剑的耐久值恢复",
这个直接按照原意翻吧

2024-01-07 10:05 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "item.slashblade.proudsoul_tiny.dark":"破碎的耀魂之茧",
赞同

2024-01-07 10:08 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +
| 利刃易折\n断刃之中的高傲灵魂之炎                                               | 指耀魂碎片，其获取方式为断刀时掉落的刀刃，所以翻译断刃中的灵魂之炎                 |   |   |
|-----------------------------------------------------------------|---------------------------------------------------|---|---|
| 幽微闪烁的灵魂之炎                                                       | 指破碎的耀魂，四个破碎的耀魂合成一个耀魂碎片，比整个耀魂碎片要微弱，幽微我觉得很合适        |   |   |
| 以高傲灵魂紫炎锻造的灵铁                                                    | 指耀魂铁锭，两个耀魂碎片加一个铁锭合成，在灵魂之火中煅烧的灵铁                   |   |   |
| 熔炉冶炼\n缭绕着虚幻灵魂之炎的宝珠                                              | 指耀魂宝珠，第一行是合成条件，灵魂宝珠（灵铁煅烧成灵钢）                      |   |   |
| 高炉精炼\n灵魂钢铁的核心                                                   |  指耀魂结晶，第一行是合成条件，我理解是宝珠（灵钢）的结晶                     |   |   |
| 烟熏炉熏烤\n摇摇欲坠的骄傲的末路                                               |  指耀偏方三八面魂，第一行是合成条件，直接照着原意翻译的，因为感觉最终的刀魂这种确实不太合适    |   |   |
| 唤醒它的代价是无尽的饥饿\n潜行并右键使用以激活耀偏方三八面魂\n放在快捷栏时会被饥饿所侵袭\n饥饿状态下将继续以饥饿修复刀剑 | 潜行右键使用三八面魂，会获得饥饿2效果，此后只要将他放在快捷栏就会生效恢复同样在快捷栏放置的拔刀剑 |   |   |
| 抱元守一，神闲气定\n如此就能做到反复以饥饿为代偿获得破碎的耀魂                                | 玄奥的三八面魂可以合成得到新的破碎的耀魂，而本身会变回三八彼面魂                  |   |   |

2024-01-07 10:08 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +}
无实装效果

2024-01-07 10:20 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.exeffect.feather_falling.desc": "缓降的等级对应空中行动中缓降速度。"
并未实装

2024-01-08 10:05 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +
* 以高傲灵魂紫炎锻造的灵铁
上下文都是`灵魂之炎`，这里可能会被认为是错字，还得再改
不如说自这个阶段`灵魂之炎`在原文中都没有体现了……要不然就灵魂之炎、紫色之炎、虚幻之炎这样

* 摇摇欲坠的骄傲的末路
缩句的话，是“摇摇欲坠的末路”（形容`末路`摇摇欲坠）、还是“骄傲的末路”（限定`骄傲`走到头了）、还是“骄傲的末路”（形容`末路`是一条骄傲的道路）？
这里原文`誇り`我感觉有代指（骄傲/高傲的）刀魂的成分，不如咱换个`荣耀`之类的更偏向名词属性的词？
或者不必拘泥于`末路`，改成`之末`也行

* 潜行并右键使用以激活耀偏方三八面魂
`右键`不能在这里作谓语。`右键`什么？右键单击？右键长按？右键松开？

* 如此就能做到反复以饥饿为代偿获得破碎的耀魂
有点啰嗦，翻译腔过重
就能做到=就可/便可，代偿→代价

顺带一提解释翻译思路最好一并附上对原文的剖析（如果需要）

2024-01-09 04:32 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +
原文有种诗意（中二）的感觉，骄傲的末路和摇摇欲坠的末路我觉得都不太好，这两者结合一句话我觉得太臃肿，正好看到你说的用荣耀，我就感觉“骄傲的末路，摇摇欲坠的荣耀”刚刚好的感觉

2024-01-09 07:52 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.combo_a.desc": "键位:\n攻击(♠):%s\n指令:\n地面\n♠-♠-♠-♠",
```suggestion
  "adv.slashblade.combo_a.desc": "键位：\n攻击(♠)：%s\n指令：\n地面\n♠-♠-♠-♠",
```
请使用全角标点
此类问题请全文通查

2024-01-09 07:52 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +
`"adv.slashblade.proudsoul_trapezohedron":"強化限界無し\n燻煙\n揺蕩う誇りの末路",`
原文先放这，感觉回头还得讨论

2024-01-09 07:52 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.exeffect.feather_falling": "Slow Fall",
还是翻出来吧

2024-01-09 07:52 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "attribute.name.generic.reachDistance":"Reach",
感觉还是翻出来比较好

2024-01-10 06:24 UTC, luoxueyasha requested changes

2024-01-10 06:24 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "slashblade.tooltip.material.killcount": "杀敌数 ≧%1$s",
```suggestion
  "slashblade.tooltip.material.killcount": "杀敌数≧%1$s",
```
标点与汉字之间不需要加空格
此类问题请全文通查

2024-01-10 06:24 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "attribute.name.generic.reachDistance":"触及距离",
原版术语
```suggestion
  "attribute.name.generic.reachDistance":"攻击距离",
```

2024-01-10 06:24 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.exeffect.feather_falling.desc": "缓降的等级对应滞空时缓降速度"
你这不是没翻吗

2024-01-10 10:17 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.exeffect.feather_falling.desc": "空中行动时降落速度收到缓降效果等级的影响"
```suggestion
  "adv.slashblade.exeffect.feather_falling.desc": "缓解效果的等级将减缓空中行动的下落速度"
```
`空中`行动建议和出招表统一（这里可以替换为`滞空`，不过最好还是统一

2024-01-10 10:25 UTC, luoxueyasha submitted a review, later dismissed
可算是解决一个硬茬
耀魂的命名？就让它继续错下去吧（

2024-01-10 10:27 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.proudsoul_activated":"唤醒它的代价是无尽的饥饿\n潜行并单击右键使用以激活耀偏方三八面魂\n放在快捷栏时会被饥饿所侵袭\n饥饿状态下将继续以饥饿修复刀剑",
```suggestion
  "adv.slashblade.proudsoul_activated":"唤醒它的代价是无尽的饥饿\n潜行并右击使用以激活耀偏方三八面魂\n放在快捷栏时会被饥饿所侵袭\n饥饿状态下将继续以饥饿修复刀剑",
```
啊还有个这个小问题
保不保留`使用`（右击以激活 or 右击使用以激活）看你了

2024-01-10 10:42 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.proudsoul_activated":"唤醒它的代价是无尽的饥饿\n潜行并单击右键使用以激活耀偏方三八面魂\n放在快捷栏时会被饥饿所侵袭\n饥饿状态下将继续以饥饿修复刀剑",
前者吧，简短不冗余

2024-01-10 10:45 UTC, luoxueyasha approved these changes

2024-01-12 10:02 UTC, luoxueyasha commented
@Cactusstudent 仙人掌看看这个要不要公示

2024-01-14 05:01 UTC, luoxueyasha requested changes

2024-01-14 05:01 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.combo_a_ex.desc": "键位：\n攻击 ♠：%s\n指令：\n地面\n在饥饿效果时\n♠-♠-♠-♠-♠",
漏翻
```suggestion
  "adv.slashblade.combo_a_ex.desc": "键位：\n攻击 ♠：%s\n指令：\n地面\n在力量或饥饿效果时\n♠-♠-♠-♠-♠",
```

2024-01-14 05:14 UTC, luoxueyasha requested changes
实际玩了一下，感觉涉及左ctrl的指令都有点难按

2024-01-14 05:14 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.quick_charge.desc": "键位：\n攻击(♠)：%s\n指令：\n♠ 在纳刀的瞬间按下攻击 ♠",
```suggestion
  "adv.slashblade.quick_charge.desc": "键位：\n攻击(♠)：%s\n指令：\n在纳刀的瞬间按下 ♠",
```

2024-01-14 05:14 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.guard.desc": "消耗耐久度将敌人的远程攻击无效\n'行走'中无法发动\n键位：\n潜行(⚪)：%s\n指令：\n⚪",
```suggestion
  "adv.slashblade.guard.desc": "消耗耐久度将敌人的远程攻击无效\n“行走”中无法发动\n键位：\n潜行(⚪)：%s\n指令：\n⚪",
```
全角标点问题
请全文通查

2024-01-14 05:14 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.heavy_rain_swords.desc": "消耗5点经验值，将幻影剑如同五月雨般在敌人头上降下\n键位：\n%s(♠)：%s\n后退(ᐁ)：%s\n前进(ᐃ)：%s\n潜行(⚪)：%s\n指令：\n⚪+ᐁ to ᐃ+♠ 按住",
五月雨=绵延不绝
```suggestion
  "adv.slashblade.heavy_rain_swords.desc": "消耗5点经验值，将幻影剑绵延不绝地在敌人头上降下\n键位：\n%s(♠)：%s\n后退(ᐁ)：%s\n前进(ᐃ)：%s\n潜行(⚪)：%s\n指令：\n⚪+ᐁ to ᐃ+♠ 按住",
```

2024-01-14 05:14 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.combo_b_max.desc": "撕碎！",
这条的具体触发条件？

2024-01-14 05:47 UTC, luoxueyasha requested changes

2024-01-14 05:47 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "slashblade.tooltip.refine": "强化等级：%1$s",
```suggestion
  "slashblade.tooltip.refine": "重铸次数：%1$s",
```
实际玩下来，这玩意还得叫重铸
至于是`重铸次数`还是`重铸等级`得看你了

2024-01-14 08:27 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "slashblade.tooltip.refine": "强化等级：%1$s",
重铸次数吧 ，等级感觉比较容易模糊

2024-01-14 08:27 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "slashblade.tooltip.material.level": "等级≧%1$s",
同理改重铸次数

2024-01-14 08:45 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.quick_charge.desc": "键位：\n攻击(♠)：%s\n指令：\n♠ 在纳刀的瞬间按下攻击 ♠",
这个确实== ，但是也没有办法，拔刀剑2的所有按键都是绑定的mc的默认按键。也就是说，你要想按键舒服得把疾跑键改到其他键位，我这个刚开始用的那个输入法mod，因为某些ui界面强制英文又换了美式键盘和拼音搜索mod玩。。
只能说键位确实难受

2024-01-14 09:16 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.combo_b_max.desc": "撕碎！",
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/1b9b6d9a-ae16-4ecc-b90d-89048949d707)
https://github.com/flammpfeil/SlashBlade_2/blob/master/src/main/java/mods/flammpfeil/slashblade/capability/slashblade/combo/Extra.java#L380
相关代码

2024-01-14 09:18 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.combo_b_max.desc": "撕碎！",
看着像是右击7次（或者8次）后再顿一下，右击
反正resolved就是了，感觉好难打

2024-01-14 09:36 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.combo_b_max.desc": "撕碎！",
测试了下，就字面意思....完成一次连击B，这个成就就触发了
攻击-攻击-攻击，停顿  连续点击攻击

2024-01-14 10:04 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.heavy_rain_swords.desc": "消耗5点经验值，将幻影剑如同五月雨般在敌人头上降下\n键位：\n%s(♠)：%s\n后退(ᐁ)：%s\n前进(ᐃ)：%s\n潜行(⚪)：%s\n指令：\n⚪+ᐁ to ᐃ+♠ 按住",
连绵不绝怎么样，五月雨差不多就这个意思
延绵不绝感觉情景不对

2024-01-14 10:05 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "adv.slashblade.heavy_rain_swords.desc": "消耗5点经验值，将幻影剑如同五月雨般在敌人头上降下\n键位：\n%s(♠)：%s\n后退(ᐁ)：%s\n前进(ᐃ)：%s\n潜行(⚪)：%s\n指令：\n⚪+ᐁ to ᐃ+♠ 按住",
可

2024-01-14 10:08 UTC, luoxueyasha approved these changes

2024-01-17 14:14 UTC, luoxueyasha commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "item.slashblade.simple.iron": "大太刀「」",
查资料的时候发现这玩意现在叫`抜刀剣「」`了
要改吗

2024-01-17 14:25 UTC, Lmy1503 commented on projects/1.20/assets/slashblade/slashblade/lang/zh_cn.json
> +  "item.slashblade.simple.iron": "大太刀「」",
我觉得可以不用改

2024-01-18 00:47 UTC, luoxueyasha approved these changes
希望没有需要再改的地方了

2024-10-13 03:00 UTC, luoxueyasha commented
已公示：https://bbs.mcmod.cn/forum.php?mod=viewthread&tid=19893
可于14+7日（2024.11.4 0点后）合并

2024-11-05 08:01 UTC, merged