Candlelight 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #4039
Opened 2023-12-31 05:51 UTC by sillymoon

2023-12-31 06:12 UTC, sillymoon commented
事之前交给官译更新的，先搬过来。

2023-12-31 06:15 UTC, sillymoon commented
> 事之前交给官译更新的，先搬过来。

注：不知道某个版本把`西兰花`图标和名称改为了`生菜`，导致有些物品名称有点生草【x】

2024-01-17 11:51 UTC, ChuijkYahus requested changes

2024-01-17 11:51 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/lets-do-candlelight/candlelight/lang/zh_cn.json
> +  "block.candlelight.bamboo_big_table": "竹木大桌",
竹一般不加木吧（）

2024-01-17 11:51 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/lets-do-candlelight/candlelight/lang/zh_cn.json
> +  "block.candlelight.chocolate_box.tooltip": "两人间最完美的礼物 - 或着说甜点",
```suggestion
  "block.candlelight.chocolate_box.tooltip": "两人间最完美的礼物——或者说甜点",
```

2024-01-17 11:51 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/lets-do-candlelight/candlelight/lang/zh_cn.json
> +  "block.candlelight.hearth": "Hearth",
这是啥（）

2024-01-17 11:51 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/lets-do-candlelight/candlelight/lang/zh_cn.json
> +  "block.candlelight.decoration.tool_rack": "厨具和平底锅的墙面收纳",
```suggestion
  "block.candlelight.decoration.tool_rack": "厨具和平底锅的墙面收纳架",
```
微调

2024-01-17 11:51 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/lets-do-candlelight/candlelight/lang/zh_cn.json
> +  "item.candlelight.thankyou1.press_shift": "这些画不仅描绘了lex和Steve，也包括 “Let's Do” 系列模组的贡献者们。",
```suggestion
  "item.candlelight.thankyou1.press_shift": "这些画不仅描绘了lex和Steve，也包括“Let's Do”系列模组的贡献者们。",
```

2024-01-17 11:51 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/lets-do-candlelight/candlelight/lang/zh_cn.json
> +  "item.candlelight.thankyou2.press_shift": "感谢所有为 “Let's Do” 系列模组的制作做出过贡献的人们：",
```suggestion
  "item.candlelight.thankyou2.press_shift": "感谢所有为“Let's Do”系列模组的制作做出过贡献的人们：",
```

2024-01-17 11:51 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/lets-do-candlelight/candlelight/lang/zh_cn.json
> +  "block.candlelight.lettuce_crate": "满袋生菜",
```suggestion
  "block.candlelight.lettuce_crate": "袋装生菜",
```
不知道这样会不会好一点

2024-02-14 15:51 UTC, ChuijkYahus requested changes
其余应该OK了

2024-02-14 15:51 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/lets-do-candlelight/candlelight/lang/zh_cn.json
> +  "block.candlelight.chocolate_box.tooltip": "两人间最完美的礼物——或着说甜点",
```suggestion
  "block.candlelight.chocolate_box.tooltip": "两人间最完美的礼物——或者说甜点",
```

2024-02-20 07:46 UTC, merged