Dtbop
CFPAOrg/Minecraft-Mod-Language-Package pull request #4044
Opened 2024-01-05 15:05 UTC by cocollk

2024-01-05 20:08 UTC, ChuijkYahus requested changes

2024-01-05 20:08 UTC, ChuijkYahus commented on projects/1.19/assets/dtbop/dtbop/lang/zh_cn.json
> +  "species.dtbop.yellow_autumn":"秋天的桦树",
请注意参照BOP自身的翻译

2024-01-05 20:08 UTC, ChuijkYahus commented on projects/1.19/assets/dtbop/dtbop/lang/zh_cn.json
> +  "species.dtbop.dying":"垂死的树",
同上

2024-01-05 20:08 UTC, ChuijkYahus commented on projects/1.19/assets/dtbop/dtbop/lang/zh_cn.json
> +  "species.dtbop.redwood":"红木",
同上
此处用词不统一

2024-01-06 03:03 UTC, luoxueyasha commented
请将pr标题修改为如“模组英文全名 翻译提交”等格式，具体可以参照其他pr

2024-01-06 03:04 UTC, luoxueyasha commented on projects/1.19/assets/dtbop/dtbop/lang/fr_fr.json
> +  "item.dtbop.poplar_seed":"Graine de peuplier",
可以问一下为什么有法语文件吗？作者的第一语言是法语吗？

2024-01-14 01:38 UTC, luoxueyasha commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

@cocollk 

此外，你对审阅者的回复可能处于pending状态（如下图），其他人是看不见的。这些回复需要通过在网页端github点击“Files Changed” - “Finish your review” - "Submit Review"以公开你的回复。
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/500f0931-df30-431f-a9b4-57193eaa84d4)

2024-01-21 06:15 UTC, cocollk reviewed
111

2024-01-21 06:19 UTC, ChuijkYahus commented
> 111

自带不重要，重要的是作者的母语或者模组的源语言是不是法语
如果不是就请删除

2024-01-31 08:31 UTC, luoxueyasha requested changes

2024-01-31 08:31 UTC, luoxueyasha commented on projects/1.19/assets/dtbop/dtbop/lang/zh_cn.json
> +  "item.dtbop.poplar_seed":"白杨木柳絮",
杨树不会有“柳”絮
此类问题请全文通查

2024-02-04 01:01 UTC, luoxueyasha commented on projects/1.19/assets/dtbop/dtbop/lang/zh_cn.json
> +  "item.dtbop.poplar_seed":"白杨木葇荑花序",
还是麻烦发一下游戏内截图吧，首先需要确定是种子（絮）还是花（葇荑花序）
其次，葇荑花序这个词也在生活中不常见，考虑换成别的更通用的称呼方法
再有，树上长出来的东西都是X树XX，如原版的`橡树树叶`（而不是`橡木树叶`）

2024-02-11 23:11 UTC, luoxueyasha commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

@cocollk

2024-02-20 08:08 UTC, closed without merging