enlightend自用的汉化
CFPAOrg/Minecraft-Mod-Language-Package pull request #4050
Opened 2024-01-07 05:11 UTC by WYW290

2024-01-07 05:35 UTC, qznfbnj commented
一般对于MCreator都是直接使用 sort-keys 命令的，顶着乱序翻译想必很辛苦吧hhh

2024-01-07 05:37 UTC, WYW290 commented
> 一般对于MCreator都是直接使用 sort-keys 命令的，顶着乱序翻译想必很辛苦吧hhh

你不说都没注意，我说怎么这么乱。难受死我了😭

2024-01-21 08:57 UTC, ChuijkYahus commented
/sort-keys projects/1.19/assets/enlightend/enlightened_end/lang/en_us.json
/sort-keys projects/1.19/assets/enlightend/enlightened_end/lang/zh_cn.json

2024-04-02 12:56 UTC, SlimeSB requested changes
希望没有漏的

2024-04-02 12:56 UTC, SlimeSB commented on projects/1.19/assets/enlightend/enlightened_end/lang/zh_cn.json
> +  "block.enlightened_end.xenon_gas": "Xenon Gas",
请补

2024-04-02 12:56 UTC, SlimeSB commented on projects/1.19/assets/enlightend/enlightened_end/lang/zh_cn.json
> +  "block.enlightened_end.offering_statue": "被供奉的雕像",
```suggestion
  "block.enlightened_end.offering_statue": "贡像",
```

2024-04-02 12:56 UTC, SlimeSB commented on projects/1.19/assets/enlightend/enlightened_end/lang/zh_cn.json
> +  "block.enlightened_end.springleaf": "喷泉叶",
```suggestion
  "block.enlightened_end.springleaf": "弹簧叶",
```

2024-04-02 12:56 UTC, SlimeSB commented on projects/1.19/assets/enlightend/enlightened_end/lang/zh_cn.json
> +  "block.enlightened_end.indigo_hyphae": "末地凝胶木",
这里是hyphae，请译作菌核（1.19.2）

2024-04-02 12:56 UTC, SlimeSB commented on projects/1.19/assets/enlightend/enlightened_end/lang/zh_cn.json
> +  "entity.enlightened_end.disturbed_helium_gas": "被扰动的氦气",
被玩家破坏而非装瓶会生成这个，受扰或者逸散 ，不带“的”

2024-04-02 12:56 UTC, SlimeSB commented on projects/1.19/assets/enlightend/enlightened_end/lang/zh_cn.json
> +  "entity.enlightened_end.squelcher": "Squelcher",
请补，静噪或者压制之类的。我版本不一致没看见这个

2024-04-02 12:56 UTC, SlimeSB commented on projects/1.19/assets/enlightend/enlightened_end/lang/zh_cn.json
> +  "entity.enlightened_end.dewcrawl": "Dewcrawl",
请补

2024-04-02 12:56 UTC, SlimeSB commented on projects/1.19/assets/enlightend/enlightened_end/lang/zh_cn.json
> +  "gui.enlightened_end.nuclear_furnace_screen.label_nuclear_furnace": "核",
```suggestion
  "gui.enlightened_end.nuclear_furnace_screen.label_nuclear_furnace": "核能",
```

2024-04-02 12:56 UTC, SlimeSB commented on projects/1.19/assets/enlightend/enlightened_end/lang/zh_cn.json
> +  "item_group.enlightened_end.compatability": "Enlightend : Compatability",
```suggestion
  "item_group.enlightened_end.compatability": "Enlightend : 兼容",
```

2024-04-02 12:56 UTC, SlimeSB commented on projects/1.19/assets/enlightend/enlightened_end/lang/zh_cn.json
> +  "item.enlightened_end.final_sword": "§6Apex",
```suggestion
  "item.enlightened_end.final_sword": "§6顶点",
```
顶点、顶峰、至高

2024-04-02 12:56 UTC, SlimeSB commented on projects/1.19/assets/enlightend/enlightened_end/lang/zh_cn.json
> +  "item.enlightened_end.gas_jar": "Gas Jar",
请补

2024-04-02 12:56 UTC, SlimeSB commented on projects/1.19/assets/enlightend/enlightened_end/lang/zh_cn.json
> +  "painting.enlightened_end.ringling_painting.title": "环灵绘画",
不译

2024-04-02 12:56 UTC, SlimeSB commented on projects/1.19/assets/enlightend/enlightened_end/lang/zh_cn.json
> +  "subtitles.dart_hit": "Dart hit",
```suggestion
  "subtitles.dart_hit": "飞镖：击中",
```
下同

2024-04-02 12:56 UTC, SlimeSB commented on projects/1.19/assets/enlightend/enlightened_end/lang/zh_cn.json
> +  "subtitles.dashing_leggings_dash": "东西被打碎",
```suggestion
  "subtitles.dashing_leggings_dash": "冲刺护腿：冲刺",
```

2024-04-02 12:56 UTC, SlimeSB commented on projects/1.19/assets/enlightend/enlightened_end/lang/zh_cn.json
> +  "subtitles.laser_off": "Laser Deactivates",
请补

2024-04-02 12:56 UTC, SlimeSB commented on projects/1.19/assets/enlightend/enlightened_end/lang/zh_cn.json
> +  "subtitles.radiant_emission": "Radiant Emission",
辐射：外泄？

2024-04-02 12:56 UTC, SlimeSB commented on projects/1.19/assets/enlightend/enlightened_end/lang/zh_cn.json
> +  "subtitles.squelcher_spit": "Squelcher Spits",
喷吐

2024-04-02 12:57 UTC, SlimeSB commented
关于模组译名：enlightend可以看做enlighten+end。末地启明？

2024-04-13 06:00 UTC, SlimeSB commented
@WYW290 在吗，本来应该在7日前催的但是我忘了……请在4.21前回复。

2024-04-13 12:08 UTC, SlimeSB commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。
@WYW290

2024-05-02 13:19 UTC, SlimeSB approved these changes

2024-05-02 13:21 UTC, merged