additional-lanterns 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4056
Opened 2024-01-10 17:47 UTC by 258654aun

2024-01-16 10:11 UTC, ChuijkYahus requested changes

2024-01-16 10:11 UTC, ChuijkYahus commented on projects/1.20/assets/additional-lanterns/additionallanterns/lang/zh_cn.json
> +  "block.additionallanterns.crimson_lantern": "绯红灯笼",
这里的材料应该是绯红木？

2024-01-16 10:11 UTC, ChuijkYahus commented on projects/1.20/assets/additional-lanterns/additionallanterns/lang/zh_cn.json
> +  "block.additionallanterns.stone_lantern": "石灯笼",
```suggestion
  "block.additionallanterns.stone_lantern": "石头灯笼",
```
可不改

2024-01-16 10:11 UTC, ChuijkYahus commented on projects/1.20/assets/additional-lanterns/additionallanterns/lang/zh_cn.json
> +  "block.additionallanterns.warped_lantern": "诡异灯笼",
同上方绯红木，此处应该是诡异木？

2024-01-16 10:11 UTC, ChuijkYahus commented on projects/1.20/assets/additional-lanterns/additionallanterns/lang/zh_cn.json
> +  "block.additionallanterns.waxed_exposed_copper_lantern": "斑驳的涂蜡铜灯笼",
```suggestion
  "block.additionallanterns.waxed_exposed_copper_lantern": "涂蜡的斑驳铜灯笼",
```
1.20中采用`涂蜡的铜xx` `涂蜡的斑驳铜xx` `涂蜡的锈蚀铜xx` `涂蜡的氧化铜xx`
请注意全部修改

2024-01-22 16:40 UTC, 258654aun commented on projects/1.20/assets/additional-lanterns/additionallanterns/lang/zh_cn.json
> +  "block.additionallanterns.stone_lantern": "石灯笼",
这里原本是翻译成石头灯笼的，但感觉石灯笼读起来更顺口

2024-01-22 17:02 UTC, 258654aun reviewed
已修正完毕

2024-01-22 19:34 UTC, ChuijkYahus approved these changes

2024-01-23 06:17 UTC, merged