Oreganized 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4061
Opened 2024-01-11 19:35 UTC by HySand

2024-01-12 14:28 UTC, qznfbnj commented
可能有用的东西：
一潭死水的官库的PR：[Simplified Chinese Support](https://github.com/Xaidee/oreganised/pull/26)（可能修改自mc百科评论区野生汉化）
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/100760086/258b6d8e-f227-4f0f-a922-55db88567d7a)
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/100760086/952767cb-c193-400a-8205-235757df0903)

2024-01-16 10:01 UTC, ChuijkYahus requested changes

2024-01-16 10:01 UTC, ChuijkYahus commented on projects/1.19/assets/oreganized/oreganized/lang/zh_cn.json
> +  "effect.oreganized.stunning.description": "随机间隔地麻痹目标",
```suggestion
  "effect.oreganized.stunning.description": "每过随机间隔麻痹目标",
```

2024-01-16 10:01 UTC, ChuijkYahus commented on projects/1.19/assets/oreganized/oreganized/lang/zh_cn.json
> +  "item.oreganized.electrum_pickaxe": "琥珀金稿",
```suggestion
  "item.oreganized.electrum_pickaxe": "琥珀金镐",
```

2024-01-16 10:01 UTC, ChuijkYahus commented on projects/1.19/assets/oreganized/oreganized/lang/zh_cn.json
> +  "block.oreganized.waxed_red_concrete_powder": "红色涂蜡混凝土粉末",
这个涂蜡不知道`涂蜡的xx色混凝土粉末`怎么样，不改也可

~~算是严格按照现在原版最新的用法了~~

2024-01-22 06:53 UTC, ChuijkYahus approved these changes

2024-01-23 06:19 UTC, merged