Create: Bells & Whistles 翻译更新提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4063
Opened 2024-01-11 21:53 UTC by HySand

翻译来源于本项目1.20的翻译
但是车头那玩意叫桩柱（原翻译）么
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/77628540/ee027fe5-af5a-4671-a129-30e747c0f3b6)

2024-01-13 16:18 UTC, dovisutu commented
看起来还是排障器更合理些
（不过弄不好原翻译是个什么神奇术语...得查查看）
别的应该没什么问题，除了材料名我不太清楚

2024-01-16 09:52 UTC, ChuijkYahus requested changes
就是排障器，其他应该问题不大

2024-01-16 09:52 UTC, ChuijkYahus commented on projects/1.19/assets/bellsandwhistles/bellsandwhistles/lang/zh_cn.json
> +  "block.bellsandwhistles.andesite_grab_rails": "安山岩梯杆",
```suggestion
  "block.bellsandwhistles.andesite_grab_rails": "安山梯杆",
```
参照机械动力本体
这里的合成材料应该是安山合金

2024-01-16 10:01 UTC, HySand commented
其实按照机械动力的话casing应该翻译成机壳？但它好像没有机壳的功能
那个window其实也是个中间是玻璃的活板门

2024-01-16 10:03 UTC, ChuijkYahus commented
之前1.20提交的时候有讨论过这个casing，和机械动力本体的几种机壳制作方式不同

也就因此没有统一，不知道现在制作方式改了没有

2024-01-16 10:03 UTC, ChuijkYahus commented
> 其实按照机械动力的话casing应该翻译成机壳？但它好像没有机壳的功能 那个window其实也是个中间是玻璃的活板门

window就这样吧（）

2024-01-16 11:03 UTC, ChuijkYahus commented
话说现在的metro casing的制作方式是怎样的

2024-01-16 11:18 UTC, HySand commented
> 话说现在的metro casing的制作方式是怎样的

还是工作台里铁板加绿色染料，跟机壳不大一样

2024-01-16 11:24 UTC, ChuijkYahus commented
那就这样吧（）

2024-01-16 11:25 UTC, ChuijkYahus commented on projects/1.20/assets/bellsandwhistles/bellsandwhistles/lang/zh_cn.json
> +  "block.bellsandwhistles.andesite_pilot":"安山岩排障器",
```suggestion
  "block.bellsandwhistles.andesite_pilot":"安山排障器",
```

2024-01-16 11:25 UTC, ChuijkYahus commented on projects/1.19/assets/bellsandwhistles/bellsandwhistles/lang/zh_cn.json
> +  "block.bellsandwhistles.andesite_pilot": "安山岩排障器",
```suggestion
  "block.bellsandwhistles.andesite_pilot": "安山排障器",
```
这两个如果是安山合金做的就需要改

2024-01-16 11:34 UTC, HySand commented on projects/1.19/assets/bellsandwhistles/bellsandwhistles/lang/zh_cn.json
> +  "block.bellsandwhistles.andesite_pilot": "安山岩排障器",
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/77628540/d36240f5-956e-43ff-8c00-3a936c863cee)
都要呢

2024-01-16 12:02 UTC, ChuijkYahus commented on projects/1.19/assets/bellsandwhistles/bellsandwhistles/lang/zh_cn.json
> +  "block.bellsandwhistles.andesite_pilot": "安山岩排障器",
材质上应该更倾向于安山合金一些？

2024-01-16 12:10 UTC, ChuijkYahus approved these changes

2024-01-17 09:32 UTC, merged