Create: Design n' Decor 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4067
Opened 2024-01-12 13:36 UTC by HySand

Castel 不知道怎么翻译
Block of Industrial Plating看起来和机械动力的工业铁块是一样的?

2024-01-16 10:19 UTC, ChuijkYahus commented
这个完工了吗（）
如果是忘记设置ready for review可以说一下

2024-01-16 10:54 UTC, ChuijkYahus commented
也没找到，装饰模组一般都是这样的，干脆按照花纹来吧
`错叠` `错砌`这种

2024-01-16 11:50 UTC, HySand commented
原版的话应该是砖？但是机械动力翻译成砖块，怎么搞

2024-01-16 12:03 UTC, ChuijkYahus commented
> 原版的话应该是砖？但是机械动力翻译成砖块，怎么搞

那按机械动力来吧

2024-01-22 09:50 UTC, ChuijkYahus requested changes

2024-01-22 09:50 UTC, ChuijkYahus commented on projects/1.19/assets/create-design-n-decor/design_decor/lang/zh_cn.json
> +  "block.design_decor.deepslate_castel_bricks": "交错深板岩砖块s",
```suggestion
  "block.design_decor.deepslate_castel_bricks": "交错深板岩砖块",
```

2024-01-22 09:50 UTC, ChuijkYahus commented on projects/1.19/assets/create-design-n-decor/design_decor/lang/zh_cn.json
> +  "block.design_decor.hepatizon_large_chain": "大型科林斯青铜锁链",
这个有对应合成材料吗
匠魂3中此材料名称为`黑色科林斯青铜`

2024-01-22 09:50 UTC, ChuijkYahus commented on projects/1.19/assets/create-design-n-decor/design_decor/lang/zh_cn.json
> +  "block.design_decor.invar_large_chain": "大型因瓦合金锁链",
```suggestion
  "block.design_decor.invar_large_chain": "大型殷钢锁链",
```

2024-01-22 09:50 UTC, ChuijkYahus commented on projects/1.19/assets/create-design-n-decor/design_decor/lang/zh_cn.json
> +  "block.design_decor.queen_slime_large_chain": "大型黏钢锁链",
```suggestion
  "block.design_decor.queen_slime_large_chain": "大型皇后史莱姆锁链",
```
匠魂3材料

2024-01-22 09:50 UTC, ChuijkYahus commented on projects/1.19/assets/create-design-n-decor/design_decor/lang/zh_cn.json
> +  "block.design_decor.industrial_plating_block": "工业镀铁块",
这个有合成方式吗

2024-01-23 12:45 UTC, HySand commented on projects/1.19/assets/create-design-n-decor/design_decor/lang/zh_cn.json
> +  "block.design_decor.industrial_plating_block": "工业镀铁块",
前面是用工业铁块或工业镀铁块合成的，镀铁块是用铁锭合成的，跟工业铁块很像，功能大概是工业铁块的子集

2024-01-23 12:55 UTC, ChuijkYahus approved these changes

2024-01-25 07:19 UTC, merged