GolDelight 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4068
Opened 2024-01-12 17:27 UTC by 258654aun

由 CFPA-Helper 提交。

2024-01-16 09:48 UTC, ChuijkYahus requested changes

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "block.goldelight.budding_golden_tomatoes": "含苞待放的金番茄",
```suggestion
  "block.goldelight.budding_golden_tomatoes": "萌芽的金番茄藤蔓",
```
与库内的农夫乐事统一

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "block.goldelight.golden_cabinet": "金橱柜",
```suggestion
  "block.goldelight.golden_cabinet": "金厨柜",
```
农夫乐事用词

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "block.goldelight.golden_carved_pumpkin": "金雕刻南瓜",
```suggestion
  "block.goldelight.golden_carved_pumpkin": "雕刻金南瓜",
```

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "block.goldelight.golden_chocolate_pie": "金巧克力馅饼",
```suggestion
  "block.goldelight.golden_chocolate_pie": "金巧克力派",
```
农夫乐事用词

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "block.goldelight.golden_fungus_colony": "金真菌菌落",
```suggestion
  "block.goldelight.golden_fungus": "金黄菌",
  "block.goldelight.golden_fungus_colony": "金黄菌菌落",
```
微调，可不改，但推荐看一下

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "block.goldelight.golden_glazed_ham_block": "金火腿",
```suggestion
  "block.goldelight.golden_glazed_ham_block": "金蜜汁火腿",
```
农夫乐事用词

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "block.goldelight.golden_hanging_sign": "金悬挂式告示牌",
```suggestion
  "block.goldelight.golden_hanging_sign": "悬挂式金告示牌",
```

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "block.goldelight.golden_hay_block": "金干草块",
```suggestion
  "block.goldelight.golden_hay_block": "金干草捆",
```
原版用词

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "block.goldelight.golden_nether_bricks": "金下界砖",
```suggestion
  "block.goldelight.golden_nether_bricks": "金下界砖块",
```
参照原版的下界砖和下界砖块的区别

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "block.goldelight.golden_onion_crate": "金箱装洋葱",
```suggestion
  "block.goldelight.golden_onion_crate": "箱装金洋葱",
```
语序

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "block.goldelight.golden_potato_crate": "金箱装马铃薯",
```suggestion
  "block.goldelight.golden_potato_crate": "箱装金马铃薯",
```

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "block.goldelight.golden_rice_bale": "金稻米块",
```suggestion
  "block.goldelight.golden_rice_bale": "金稻米捆",
```
参照原版用词

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "block.goldelight.golden_slab": "金半砖",
```suggestion
  "block.goldelight.golden_slab": "金台阶",
```
原版用词

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "block.goldelight.golden_tomato_crate": "金箱装番茄",
```suggestion
  "block.goldelight.golden_tomato_crate": "箱装金番茄",
```

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "block.goldelight.golden_wall_sign": "金墙上的告示牌",
```suggestion
  "block.goldelight.golden_wall_hanging_sign": "墙上的悬挂式金告示牌",
  "block.goldelight.golden_wall_sign": "墙上的金告示牌",
```

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "block.goldelight.groomlight": "Groomlight",
```suggestion
  "block.goldelight.groomlight": "金菌光体",
```

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "block.goldelight.potted_golden_fungus": "金真菌盆栽",
上方的金真菌如果修改则此处也需修改

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "enchantment.goldelight.midas_touch": "Midas触摸",
```suggestion
  "enchantment.goldelight.midas_touch": "迈达斯之触",
```
Midas一般叫弥达斯，不过神话中的用词是迈达斯

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "farmersdelight.tooltip.golden_horse_feed.when_feeding": "喂给驯服的坐骑时:",
```suggestion
  "farmersdelight.tooltip.golden_dog_food.when_feeding": "喂给已驯服的狗时：",
  "farmersdelight.tooltip.golden_horse_feed.when_feeding": "喂给已驯服的马时：",
```
农夫乐事用法，同时将冒号修改为全角

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "farmersdelight.tooltip.golden_hot_cocoa": "保护您免受冻结",
```suggestion
  "farmersdelight.tooltip.golden_hot_cocoa": "保护你免受冻结",
```
不要用`您`

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "farmersdelight.tooltip.golden_milk_bottle": "清除一个效果",
```suggestion
  "farmersdelight.tooltip.golden_milk_bottle": "清除1个效果",
```
农夫乐事用法

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "goldelight.advancement.get_golden_mushroom_colony.desc": "剪掉一个完全成熟的金蘑菇菌落。要种植它们，你需要一个非常非常肥沃的土壤......",
```suggestion
  "goldelight.advancement.get_golden_mushroom_colony.desc": "剪掉一个完全成熟的金蘑菇菌落。要种植它们，你需要一个非常非常肥沃的土壤……",
```
中文省略号

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "goldelight.advancement.enchanted_midas_knife.desc": "拔出王者的力量。那些爱黄金的人会帮助你。",
这个不知道是不是`获得国王的力量`
神话中就是迈达斯国王

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "goldelight.advancement.get_ancient_gold_upgrade_smithing_template": "史密斯的宝藏",
这里的Smith应该是铁匠吧

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "goldelight.advancement.give_golden_horse_feed.desc": "给驯服的马喂食金马饲料",
```suggestion
  "goldelight.advancement.give_golden_horse_feed.desc": "给驯服的马喂食金马食",
```
统一物品名

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "goldelight.advancement.place_golden_cooking_pot.desc": "你可以把食物的效果拉出来！",
```suggestion
  "goldelight.advancement.place_golden_cooking_pot.desc": "你可以提取出食物的效果！",
```

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "goldelight.container.golden_cooking_pot.served_on": "服务于: %s",
```suggestion
  "goldelight.container.golden_cooking_pot.served_on": "需盛装于：%s",
```
农夫乐事用词
serve一词有“上菜”的意思

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "goldelight.tooltip.golden_cooking_pot.single_serving": "可容纳 1 份:",
```suggestion
  "goldelight.tooltip.golden_cooking_pot.many_servings": "装有%s份：",
  "goldelight.tooltip.golden_cooking_pot.single_serving": "装有1份：",
```

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "item.goldelight.gapple_cider": "苹果酒",
```suggestion
  "item.goldelight.gapple_cider": "金苹果酒",
```

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "item.goldelight.golden_barbecue_stick": "金烤串",
```suggestion
  "item.goldelight.golden_barbecue_stick": "金烧烤串",
```

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "item.goldelight.golden_broth": "金汤",
```suggestion
  "item.goldelight.golden_broth": "金大骨汤",
```

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "item.goldelight.golden_pasta_with_mutton_chop": "金羊排意大利面",
```suggestion
  "item.goldelight.golden_pasta_with_mutton_chop": "金羊排意面",
```

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "item.goldelight.golden_popsicle": "金雪糕",
```suggestion
  "item.goldelight.golden_popsicle": "金冰棍",
```
农夫乐事用词

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "item.goldelight.golden_rice": "金稻米饭",
```suggestion
  "item.goldelight.golden_rice": "金米饭",
```

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "item.goldelight.golden_roast_chicken": "一盘金烤鸡",
```suggestion
  "item.goldelight.golden_roast_chicken": "盘装金烤鸡",
```

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "item.goldelight.golden_shepherds_pie": "一盘金牧羊人派",
```suggestion
  "item.goldelight.golden_shepherds_pie": "盘装金牧羊人派",
```

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "item.goldelight.midas_potion": "Midas药水",
```suggestion
  "item.goldelight.midas_knife": "迈达斯刀",
  "item.goldelight.midas_potion": "迈达斯药水",
```

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "item.goldelight.rotten_golden_tomato": "金马铃薯",
```suggestion
  "item.goldelight.rotten_golden_tomato": "毒金马铃薯",
```

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "item.goldelight.smithing_template.ancient_gold_upgrade.additions_slot_description": "添加远古金锭",
```suggestion
  "item.goldelight.smithing_template.ancient_gold_upgrade.additions_slot_description": "放入远古金锭",
```
原版用词

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "item.goldelight.smithing_template.ancient_gold_upgrade.base_slot_description": "添加下界合金刀",
```suggestion
  "item.goldelight.smithing_template.ancient_gold_upgrade.base_slot_description": "放入下界合金刀",
```
原版用词

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "item.goldelight.stuffed_golden_pumpkin": "一盘填馅金南瓜",
```suggestion
  "item.goldelight.stuffed_golden_pumpkin": "盘装金填馅南瓜",
```

2024-01-16 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "trim_material.goldelight.ancient_gold": "远古黄金材料",
```suggestion
  "trim_material.goldelight.ancient_gold": "远古金质",
```
原版用词

2024-01-22 18:05 UTC, 258654aun reviewed
已修正

2024-01-22 19:33 UTC, ChuijkYahus requested changes

2024-01-22 19:33 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "enchantment.goldelight.midas_touch.desc": "一些水滴会变成黄金。",
```suggestion
  "enchantment.goldelight.midas_touch.desc": "一些掉落物会变成黄金。",
```

2024-01-22 19:33 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "goldelight.advancement.drink_golden_hot_cocoa": "无论如何，寒冷从未困扰过我",
```suggestion
  "goldelight.advancement.drink_golden_hot_cocoa": "寒意再也不会困扰我了",
```
出典《冰雪奇缘》片中曲《Let It Go》
说实话这句歌词可能还是英文更广为人知？（）
采用网易云翻译

2024-01-22 19:33 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "goldelight.advancement.get_midas_knife.desc": "它看起来是锁定的",
```suggestion
  "goldelight.advancement.get_midas_knife.desc": "它看上去锁死了",
```
微调

2024-01-22 19:33 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "goldelight.advancement.give_golden_horse_feed": "比蝾螈快得多",
```suggestion
  "goldelight.advancement.give_golden_horse_feed": "比沙拉曼达还要快",
```
出典《游戏人生》
算是成为梗了

2024-01-22 19:33 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "block.goldelight.golden_compost": "金肥料",
```suggestion
  "block.goldelight.golden_compost": "金堆肥",
```
统一用词

2024-01-22 19:33 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "goldelight.advancement.place_golden_compost": "这是分解的吗？",
```suggestion
  "goldelight.advancement.place_golden_compost": "这东西分解了吗？",
```

2024-01-22 19:33 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "goldelight.container.golden_cooking_pot.served_on": "需盛装于: %s",
```suggestion
  "goldelight.container.golden_cooking_pot.served_on": "需盛装于：%s",
```
全角冒号注意修改

2024-01-23 08:36 UTC, Narux04 reviewed
翻译的很好，很接近很接近了！！！加油！！

2024-01-23 08:36 UTC, Narux04 commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "goldelight.advancement.drink_golden_hot_cocoa": "无论如何，寒冷从未困扰过我",
事实上，网易云一如既往地在翻译上拉了跨
曲子的措辞偏日常，所以实际上最好就用日常措辞翻译，比如
“反正我本来也不怕冷”

2024-01-23 08:36 UTC, Narux04 commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "goldelight.advancement.avarice.desc": "吃下一顿黄金套餐！",
```suggestion
  "goldelight.advancement.avarice.desc": "吃下每一种黄金餐点！",
```
需契合原文语义，着重表达“每一种”

2024-01-23 08:36 UTC, Narux04 commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "goldelight.advancement.drink_golden_hot_cocoa": "无论如何，寒冷从未困扰过我",
但是Chui这里的译文实际上契合了模组本身的属性，所以还是译者自己看着办吧

2024-01-23 08:36 UTC, Narux04 commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "item.goldelight.ancient_gold_nugget": "远古金块",
```suggestion
  "item.goldelight.ancient_gold_nugget": "远古金粒",
```
nugget: 粒

2024-01-23 08:36 UTC, Narux04 commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "item.goldelight.golden_broth": "金大骨汤",
```suggestion
  "item.goldelight.golden_broth": "金汤汁",
```
broth原意，请酌情采用

2024-01-23 08:36 UTC, Narux04 commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "item.goldelight.golden_glazed_ham": "盘装金火腿",
```suggestion
  "item.goldelight.golden_glazed_ham": "盘装金蜜汁火腿",
```
上下文保持同样译法

2024-01-23 08:36 UTC, Narux04 commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "item.goldelight.golden_horse_feed": "金马食",
```suggestion
  "item.goldelight.golden_horse_feed": "金马料",
```
马的饲料不应译为“马食”

2024-01-23 08:36 UTC, Narux04 commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "goldelight.advancement.give_golden_horse_feed.desc": "给驯服的马喂食金马食",
```suggestion
  "goldelight.advancement.give_golden_horse_feed.desc": "给驯服的马喂食金马料",
```

2024-01-23 08:36 UTC, Narux04 commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "item.goldelight.golden_ink_pasta": "金鱿鱼意面",
```suggestion
  "item.goldelight.golden_ink_pasta": "金墨鱼汁意面",
```
不知道译者吃没吃过那种会爆浆的煮墨鱼，老香了

2024-01-23 08:51 UTC, 258654aun commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "item.goldelight.golden_horse_feed": "金马食",
农夫乐事里Horse Feed被译作马食，这里保持一致比较好

2024-01-23 08:52 UTC, 258654aun commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "goldelight.advancement.give_golden_horse_feed.desc": "给驯服的马喂食金马食",
同上

2024-01-23 08:59 UTC, 258654aun commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "item.goldelight.golden_broth": "金大骨汤",
该物品的材质和合成表都与农夫乐事中的大骨汤相似，这样翻译没问题

2024-01-23 09:10 UTC, ChuijkYahus commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "item.goldelight.golden_ink_pasta": "金鱿鱼意面",
农夫乐事译法，作为农夫乐事附属还是需要遵照原模组的翻译

2024-01-23 09:23 UTC, 258654aun reviewed
已修正

2024-01-23 09:23 UTC, 258654aun commented on projects/1.20/assets/goldelight/goldelight/lang/zh_cn.json
> +  "item.goldelight.golden_ink_pasta": "金鱿鱼意面",
没吃过这种的
修改为金鱿鱼墨面，与农夫乐事中一致

2024-01-23 11:05 UTC, ChuijkYahus approved these changes
可以和农夫乐事的翻译再对照一遍
我看大致可以了

建议不要频繁request review

2024-01-25 07:20 UTC, merged