Vic's Point Blank 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4076
Opened 2024-01-18 02:27 UTC by KLjiana

提交自 CFPA-Helper

2024-01-18 02:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=4076) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=4076) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=4076) it.</sub>

2024-01-23 06:39 UTC, Narux04 reviewed
除译名建议外，我认为已经基本完成了

2024-01-23 06:39 UTC, Narux04 commented on projects/1.20/assets/vics-point-blank/pointblank/lang/zh_cn.json
> +  "itemGroup.pointblank.items": "Point Blank",
```suggestion
  "itemGroup.pointblank.items": "搏枪斗械",
```
译名建议，因Point Blank在英文中指“(of a shot, bullet, or other [missile] fired from very close to its target.” 即（子弹，或其他弹射物在极近距离射向目标）。该译名之所以契合，是因为其中的“搏”“斗”部分暗示了近距离，而”枪“”械“部分扣及了本模组的主题，故而提出此建议。

2024-01-28 16:44 UTC, KLjiana commented on projects/1.20/assets/vics-point-blank/pointblank/lang/zh_cn.json
> +  "itemGroup.pointblank.items": "Point Blank",
我觉得这是个不错的译名

2024-02-26 08:41 UTC, luoxueyasha approved these changes

2024-02-26 08:41 UTC, luoxueyasha commented on projects/1.20/assets/vics-point-blank/pointblank/lang/zh_cn.json
> +  "item.pointblank.g36c": "G36C 突击步枪",
```suggestion
  "item.pointblank.g36c": "G36C突击步枪",
```
武器命名是有什么特殊规范吗

在1.16或更高版本下，英文字母、阿拉伯数字等非中文文本无需在前后添加空格。
具体可见我们的 [翻译规范](https://cfpa.site/TransRules/) 中 **04.排版** 一节下。
诸如这类的问题请在您翻译的所有文件中全部查明并修改。

2024-02-26 08:42 UTC, luoxueyasha requested changes
怎么点成approved了，尴尬

2024-03-06 06:48 UTC, luoxueyasha approved these changes

2024-03-07 04:21 UTC, merged