Traveler's Backpack 语言文件更新及汉化翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #4077
Opened 2024-01-18 06:21 UTC by RookiesTwo

根据mod官方汉化(有误)修正

2024-01-18 06:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=4077) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=4077) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=4077) it.</sub>

2024-01-18 06:24 UTC, RookiesTwo commented
/update-en travelers-backpack 1.18

2024-01-20 11:50 UTC, nageih commented
为什么前缀和旅行背包之间要加空格

2024-01-22 09:51 UTC, ChuijkYahus requested changes
请注意将标点符号改为全角

2024-02-03 20:07 UTC, closed without merging