fantasys-furniture 翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #4081
Opened 2024-01-19 15:25 UTC by a1497014378

haol79175@gmail.com

2024-01-20 06:55 UTC, ChuijkYahus commented
若作者的母语和模组的源语言不是日语，请删除日语文件
同时，英语文件请仅保留en_us
其余文件注意删除

@a1497014378

2024-01-21 08:53 UTC, ChuijkYahus requested changes
不知道老滚里Nordic有没有代指特定群体

2024-01-21 08:53 UTC, ChuijkYahus commented on projects/1.16/assets/fantasys-furniture/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.decorations.berry_basket_sweetberry": "甜莓篮",
```suggestion
  "block.fantasyfurniture.decorations.berry_basket_sweetberry": "甜浆果篮",
```
原版词汇

2024-01-21 08:53 UTC, ChuijkYahus commented on projects/1.16/assets/fantasys-furniture/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.decorations.berry_basket_blueberry": "蓝梅篮",
```suggestion
  "block.fantasyfurniture.decorations.berry_basket_blueberry": "蓝莓篮",
```
请全文通查

2024-01-21 08:53 UTC, ChuijkYahus commented on projects/1.16/assets/fantasys-furniture/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.decorations.book_stack.stacked": "堆积的书堆",
```suggestion
  "block.fantasyfurniture.decorations.book_stack": "书堆",
  "block.fantasyfurniture.decorations.book_stack.stacked": "可堆积",
```

2024-01-21 08:53 UTC, ChuijkYahus commented on projects/1.16/assets/fantasys-furniture/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.decorations.bowl_beetroot_soup": "",
未翻译

2024-01-21 08:53 UTC, ChuijkYahus commented on projects/1.16/assets/fantasys-furniture/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.decorations.dunmer.pottery_1": "丹莫陶器 2",
```suggestion
  "block.fantasyfurniture.decorations.dunmer.pottery_0": "丹莫陶器1",
  "block.fantasyfurniture.decorations.dunmer.pottery_1": "丹莫陶器2",
```
删除空格

2024-01-21 08:53 UTC, ChuijkYahus commented on projects/1.16/assets/fantasys-furniture/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.decorations.muffins_blueberry.stacked": "堆积的蓝莓",
```suggestion
  "block.fantasyfurniture.decorations.muffins_blueberry.stacked": "可堆积",
```
这里的Stackable应当是说明文本之一？
可以先放一张游戏内截图，如果是请全部修改为`可堆积`

2024-01-21 08:53 UTC, ChuijkYahus commented on projects/1.16/assets/fantasys-furniture/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.decorations.muffins_blueberry": "蓝莓松饼",
```suggestion
  "block.fantasyfurniture.decorations.muffins_blueberry": "蓝莓杯状松糕",
```
应该是杯状的马芬这种吧

2024-01-21 08:53 UTC, ChuijkYahus commented on projects/1.16/assets/fantasys-furniture/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.decorations.mushrooms_red": "红蘑菇",
```suggestion
  "block.fantasyfurniture.decorations.mushrooms_red": "红色蘑菇",
```
原版用词

2024-01-21 08:53 UTC, ChuijkYahus commented on projects/1.16/assets/fantasys-furniture/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.decorations.tankards_milk": "牛奶啤酒",
```suggestion
  "block.fantasyfurniture.decorations.tankards_milk": "酒杯牛奶",
```
```suggestion
  "block.fantasyfurniture.decorations.tankards_milk": "牛奶酒杯",
```
tankard不一定是酒杯就是了，不过这样也行
同时所有语言文件中的Tankard最好译出

2024-01-21 08:53 UTC, ChuijkYahus commented on projects/1.16/assets/fantasys-furniture/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.dunmer.dresser": "邓默德莱瑟",
```suggestion
  "block.fantasyfurniture.dunmer.dresser": "邓默梳妆台",
```
德莱瑟是啥

2024-01-21 08:53 UTC, ChuijkYahus commented on projects/1.16/assets/fantasys-furniture/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.dunmer.table_large": "邓默大桌子",
```suggestion
  "block.fantasyfurniture.dunmer.table_large": "邓默大桌",
```
统一称呼

2024-01-21 08:53 UTC, ChuijkYahus commented on projects/1.16/assets/fantasys-furniture/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.dunmer.wardrobe_top": "邓默衣柜上衣",
```suggestion
  "block.fantasyfurniture.dunmer.wardrobe_top": "邓默衣柜上部",
```
应当是一个上下两格高整体的上班部分

2024-01-21 08:53 UTC, ChuijkYahus commented on projects/1.16/assets/fantasys-furniture/fantasyfurniture/lang/zh_cn.json
> +  "itemGroup.category.fantasyfurniture:item_category/nordic": "北欧的",
```suggestion
  "itemGroup.category.fantasyfurniture:item_category/nordic": "北欧",
```

2024-01-23 05:56 UTC, Narux04 reviewed
没什么大问题，稍微改改就好了，应该有一键改这种功能吧，我不太懂电脑说实话（碎碎念

2024-01-23 05:56 UTC, Narux04 commented on projects/1.16/assets/fantasys-furniture/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.dunmer.bed_double": "邓默双人床",
```suggestion
  "block.fantasyfurniture.dunmer.bed_double": "丹默双人床",
```
邓莫实应译为“丹莫“，以契合主流翻译，此问题请全文通查

2024-01-23 05:56 UTC, Narux04 commented on projects/1.16/assets/fantasys-furniture/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.nordic.bed_double": "北欧双人床",
```suggestion
  "block.fantasyfurniture.nordic.bed_double": "诺德双人床",
```
以更加符合本模组特点，此处对Nordic的翻译应采取《上古卷轴》系列中对Nord的翻译而译为“诺德”，而非现实中的北欧，此问题请全文通查

2024-01-23 05:56 UTC, Narux04 commented on projects/1.16/assets/fantasys-furniture/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.dunmer.painting_wide": "邓默宽幅绘画",
```suggestion
  "block.fantasyfurniture.dunmer.painting_wide": "宽幅丹默绘画",
```
应将邓莫改为丹莫（前文提过原因），同时，将绘画改为小幅xx绘画和宽幅xx绘画会在句式同一性以及语序上更恰当

2024-03-04 06:11 UTC, luoxueyasha commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

@a1497014378

2024-03-12 14:06 UTC, closed without merging