Wizardry Tales 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4085
Opened 2024-01-21 15:23 UTC by entarogoat

由 CFPA-Helper 提交。

2024-01-21 15:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=4085) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=4085) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=4085) it.</sub>

2024-01-21 23:16 UTC, luoxueyasha requested changes

2024-01-21 23:16 UTC, luoxueyasha commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +spell.wizardry_tales:focused_teleportation.desc=副手拿上一个传送卷轴，用主手施放这个咒语来传送到你绑定的地点!
```suggestion
spell.wizardry_tales:focused_teleportation.desc=副手拿上一个传送卷轴，用主手施放这个咒语来传送到你绑定的地点！
```
请使用全角符号
此类问题请全文通查

2024-01-22 00:43 UTC, Narux04 reviewed
一点拙见，请酌情采用 :)

2024-01-22 00:43 UTC, Narux04 commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +spell.wizardry_tales:water_healing.desc=用魔法产生的水流缓慢地治疗自己。
```suggestion
spell.wizardry_tales:water_healing.desc=用法力产生的水流缓慢地治疗自己。
```
mana=法力

2024-01-22 00:43 UTC, Narux04 commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +spell.wizardry_tales:vile_blood=邪恶之血
```suggestion
spell.wizardry_tales:vile_blood=秽浊之血
```
更契合语境

2024-01-22 00:43 UTC, Narux04 commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +spell.wizardry_tales:locating.comment=世界回应了你……
```suggestion
spell.wizardry_tales:locating.comment=世界回应着你……
```
时态对应

2024-01-22 00:43 UTC, Narux04 commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +spell.wizardry_tales:focused_teleportation=集中传送
```suggestion
spell.wizardry_tales:focused_teleportation=专注传送
```
语义契合

2024-01-22 00:43 UTC, Narux04 commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +spell.wizardry_tales:focused_teleportation.desc=副手拿上一个传送卷轴，用主手施放这个咒语来传送到你绑定的地点!
```suggestion
spell.wizardry_tales:focused_teleportation.desc=副手持有一个传送卷轴时用主手施放这个咒语来传送到你绑定的地点!
```
更加通顺

2024-01-22 00:43 UTC, Narux04 commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +spell.wizardry_tales:burning_disease.desc=使目标的身体充满火焰。这些火焰会让烧伤对目标造成更大的伤害。
```suggestion
spell.wizardry_tales:burning_disease.desc=使目标的身体充满火焰。灼烧此魔法造成的内伤会让目标承受更多持续伤害。
```
原译文表述不完整

2024-01-22 00:43 UTC, Narux04 commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +spell.wizardry_tales:chanting=Chanting吟唱
```suggestion
spell.wizardry_tales:chanting=吟唱
```
应该没删干净

2024-01-22 00:43 UTC, Narux04 commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +spell.wizardry_tales:chanting.desc=在这个槽里写上咒语，然后加上咒语的条件。这将允许你施放自制法术。
```suggestion
spell.wizardry_tales:chanting.desc=在这个槽里写上咒语，然后加上咒语的条件。这将允许你施放该自制法术。
```
“said……”此处应译为“该……”

2024-01-22 00:43 UTC, Narux04 commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +spell.wizardry_tales:conjure_ice_halberd.desc=召唤一把冰霜戟，用它攻击可以叠加冻伤持续时间。
```suggestion
spell.wizardry_tales:conjure_ice_halberd.desc=召唤一把冰霜戟，其攻击可以叠加冻伤持续时间。
```
应尽量简洁

2024-01-22 00:43 UTC, Narux04 commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +spell.wizardry_tales:conjure_ice_halberd.desc=召唤一把冰霜戟，用它攻击可以叠加冻伤持续时间。
在不破坏原文含义的情况下

2024-01-22 00:43 UTC, Narux04 commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +spell.wizardry_tales:storm_armour.desc=在遥远的过去，于雷鸣的回响之中，一套风暴盔甲被召唤而出。它曾为一位著名的英雄，一位人民的领袖所用。
```suggestion
spell.wizardry_tales:storm_armour.desc=于遥远的过去的雷鸣回响之中，一套风暴盔甲被召唤而出。它曾为一位著名的英雄，一位人民的领袖所用。
```
符合原文句式，更加简洁

2024-01-22 00:43 UTC, Narux04 commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +spell.wizardry_tales:mana_bomb=魔法炸弹
```suggestion
spell.wizardry_tales:mana_bomb=法力炸弹
```
mana=法力

2024-01-22 00:43 UTC, Narux04 commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +spell.wizardry_tales:mana_bomb.desc=投掷一枚魔法炸弹，在撞击时释放一股气体，对目标产生随机的元素反应。
```suggestion
spell.wizardry_tales:mana_bomb.desc=投掷一枚法力炸弹，在撞击时释放一股气体，对目标产生随机的元素反应。
```
同上

2024-01-22 01:17 UTC, luoxueyasha commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +item.wizardry_tales:ring_new_moon.desc=也被称为新生的月亮戒指。这些是给nox教团的新成员的，帮助他们度过一些夜晚……
```suggestion
item.wizardry_tales:ring_new_moon.desc=也被称为新生的月亮戒指。这些是给 Nox 教团的新成员的，帮助他们度过一些夜晚……
```
也可直译为暗夜教团之类的
注意1.12下数字、字母应与汉字直接留有空格，此类问题请全文通查

2024-01-22 01:21 UTC, luoxueyasha commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +spell.wizardry_tales:focused_teleportation.desc=副手拿上一个传送卷轴，用主手施放这个咒语来传送到你绑定的地点!
```suggestion
spell.wizardry_tales:focused_teleportation.desc=副手持有传送卷轴时，用主手施放这个咒语以传送到你绑定的地点！
```
“一个”多少是有点翻译腔
全角标点问题请全文通查

2024-01-22 06:50 UTC, entarogoat commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +spell.wizardry_tales:focused_teleportation.desc=副手拿上一个传送卷轴，用主手施放这个咒语来传送到你绑定的地点!
已经把译文中所有标点改为全角

2024-01-22 06:51 UTC, entarogoat commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +item.wizardry_tales:ring_new_moon.desc=也被称为新生的月亮戒指。这些是给nox教团的新成员的，帮助他们度过一些夜晚……
最终决定译为暗夜教团

2024-01-22 06:51 UTC, entarogoat commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +item.wizardry_tales:ring_poison_entangle.desc=曾被“执骨者”Melissa佩戴的戒指。使缠绕的敌人中毒。
音译为梅丽莎

2024-01-22 08:50 UTC, luoxueyasha commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +item.wizardry_tales:ring_protector.desc=当佩戴者的生命值低于70%%时，如果快捷栏中的魔杖绑定了钻石之躯/钢筋铁骨/橡木之躯，则会自动触发。
```suggestion
item.wizardry_tales:ring_protector.desc=当佩戴者的生命值低于 70%%时，如果快捷栏中的魔杖绑定了钻石之躯/钢筋铁骨/橡木之躯，则会自动触发。
```
空格问题，数字与汉字有且仅有1个空格，与符号间无需空格
此问题请全文通查

2024-01-22 08:50 UTC, luoxueyasha commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +item.wizardry_tales:pool_flask.desc=饮用可以恢复你的法力。(不恢复魔杖或装备的法力)
```suggestion
item.wizardry_tales:pool_flask.desc=饮用可以恢复你的法力。（不恢复魔杖或装备的法力）
```
符号问题

2024-01-22 08:50 UTC, luoxueyasha commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +item.wizardry_tales:mana_dust.desc=用于变形术的物品。
变形术原文`Transmutations`
这个在西幻、特别是炼金上一般是译为`嬗变`的，请问在模组里的具体效果是？

2024-01-22 08:50 UTC, luoxueyasha commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +mana.keep_trying1=§o法术已掌握 10 %%！
```suggestion
mana.keep_trying1=§o法术已掌握 10%%！
```

2024-01-22 08:50 UTC, luoxueyasha commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +commands.wizardry_tales:checkMana.usage=/%1$s <player>
这几条指令用法应在正常显示的情况下译出来

2024-01-22 08:50 UTC, luoxueyasha commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +item.wizardry_tales:small_pool_flask.name=小型魔瓶
这里的mana有考虑过和上下文统一吗

2024-01-22 08:50 UTC, luoxueyasha commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +potion.wizardry_tales:leaf_disguise.desc=你和树叶混在一起，如果你足够狡猾，就伏击你的敌人！
感觉“如果…就伏击”一股翻译腔
有没有更好的意见？
我个人建议是“就能伏击”、“就可伏击”

2024-01-22 08:50 UTC, luoxueyasha commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +potion.wizardry_tales:wrapped.desc=噢，不！潜行并尝试逃脱！
```suggestion
potion.wizardry_tales:wrapped.desc=噢，不！潜行以尝试逃脱！
```
用“并”感觉是在潜行时同时做别的进行逃脱
具体内游戏效果是？

2024-01-22 08:50 UTC, luoxueyasha commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +potion.wizardry_tales:storm_armour.desc=曾经被一个著名的英雄身穿——闪电……？
```suggestion
potion.wizardry_tales:storm_armour.desc=曾经被一位著名的英雄身穿——闪电……？
```

2024-01-22 08:50 UTC, luoxueyasha commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +potion.wizardry_tales:teleportation_curse.desc=噢，不！每隔 10 秒，你就会遭到随机传送！
```suggestion
potion.wizardry_tales:teleportation_curse.desc=噢，不！每隔 10 秒，你就会被随机传送！
```
“你就会遭到”读着有点怪

2024-01-22 08:59 UTC, entarogoat commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +item.wizardry_tales:mana_dust.desc=用于变形术的物品。
在模组里表现为可以在工作台与其他物品合成铁锭、金锭、红石、青色染料和本模组的法术书

2024-01-22 09:43 UTC, entarogoat commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +item.wizardry_tales:small_pool_flask.name=小型魔瓶
考虑了一下，应该译为法力瓶

2024-01-22 09:50 UTC, entarogoat commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +potion.wizardry_tales:wrapped.desc=噢，不！潜行并尝试逃脱！
游戏中找不到任何方式来造成这个效果，我用effect指令给予效果之后，感觉没有任何变化，潜行也没有跟这个效果有什么影响

2024-01-22 10:40 UTC, entarogoat commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +potion.wizardry_tales:leaf_disguise.desc=你和树叶混在一起，如果你足够狡猾，就伏击你的敌人！
改为了“就可伏击”

2024-01-22 10:41 UTC, entarogoat commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +item.wizardry_tales:mana_dust.desc=用于变形术的物品。
已译为“用于进行嬗变的物品”

2024-01-22 10:47 UTC, entarogoat commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +potion.wizardry_tales:teleportation_curse.desc=噢，不！每隔 10 秒，你就会遭到随机传送！
已采用建议

2024-01-22 10:47 UTC, entarogoat commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +potion.wizardry_tales:storm_armour.desc=曾经被一个著名的英雄身穿——闪电……？
已采用建议

2024-01-22 10:47 UTC, entarogoat commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +potion.wizardry_tales:wrapped.desc=噢，不！潜行并尝试逃脱！
已采用建议

2024-01-22 10:49 UTC, entarogoat commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +commands.wizardry_tales:checkMana.usage=/%1$s <player>
在后面加了个括号写上了

2024-01-22 12:46 UTC, luoxueyasha commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +commands.wizardry_tales:setMana.usage=/%1$s <player> [amount]（设置玩家当前法力值）
游戏里实际显示效果？需要截图

2024-01-22 15:46 UTC, entarogoat commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +commands.wizardry_tales:setMana.usage=/%1$s <player> [amount]（设置玩家当前法力值）
checkmana指令及其使用效果
使用后检查了玩家当前的法力值
![2024-01-22_23 30 23](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/80139722/5a6c63a4-c865-4c0d-a6c2-41bcefe7bbf7)

其余三个指令，此时我已经用setMaxMana把我的法力值上限调整为1000，在饥饿值上方的法力值图标明显增加了
![2024-01-22_23 32 30](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/80139722/1a1374c7-e2b0-4066-a99d-fac4755302c3)

setMana指令可以调整当前法力值，这里我使用它把法力值调整到500
![2024-01-22_23 43 57](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/80139722/53754ad6-e441-4d12-823c-213f8e817f88)

setRace指令可以在作者给出的天使、人类、史莱姆三个种族里选择，不过游戏内给出的手册没有显示该内容，可能功能还未完成。实际是有效果的，至少选择了史莱姆之后我的角色不再受到摔落伤害，并且降落之后如同在粘液块上一样弹润。
![2024-01-22_23 41 41](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/80139722/047fd97c-a0f2-4ea3-be4e-c9b401c719dd)

2024-01-22 22:10 UTC, luoxueyasha commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +commands.wizardry_tales:setMana.usage=/%1$s <player> [amount]（设置玩家当前法力值）
截取这些截图时，你游戏内的这些指令的文本是你修改后的，还是修改前的%1$s？
正常来说%1$s是文本占位符，如果能正常显示的话不需修改。

2024-01-22 22:12 UTC, entarogoat commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +commands.wizardry_tales:setMana.usage=/%1$s <player> [amount]（设置玩家当前法力值）
是修改后的，如果不修改就没办法正常显示
![2024-01-22_23 17 09](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/80139722/e9ed0603-a0f9-438d-a695-7dc545e44fd1)
不修改就是这个样子 ，没有显示出对应的指令

2024-01-23 04:56 UTC, luoxueyasha requested changes

2024-01-23 05:03 UTC, luoxueyasha commented
另外请不要频繁request review（

2024-01-23 06:37 UTC, entarogoat commented on projects/1.12.2/assets/wizardry-tales/wizardry_tales/lang/zh_cn.lang
> +commands.wizardry_tales:checkMana.usage=/checkMana <player>（检查玩家当前法力值）
哦哦懂了，已修改，现在是这样的效果

![2024-01-23_14 26 27](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/80139722/e3e9bb93-5a7d-4a6d-98b2-16abc0700ec3)
![2024-01-23_14 26 36](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/80139722/ba413056-9d9f-4c0d-8c16-392f89ab12b8)

2024-01-24 22:14 UTC, merged