[Forked] Easy Emerald Tools & More [FORGE] 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4086
Opened 2024-01-22 03:18 UTC by EnchantGapple233

由 CFPA-Helper 提交。

2024-01-22 03:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=4086) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=4086) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=4086) it.</sub>

2024-01-22 09:36 UTC, ChuijkYahus commented
请注意签署CLA

@EnchantGapple233

2024-01-22 09:38 UTC, ChuijkYahus requested changes

2024-01-22 09:38 UTC, ChuijkYahus commented on projects/1.20/assets/forked-easy-emerald-tools-more-forge/easy_emerald/lang/zh_cn.json
> +  "item.easy_emerald.gold_treeaxe": "金质伐木斧",
```suggestion
  "item.easy_emerald.wooden_excavator": "木开掘铲",
  "item.easy_emerald.wooden_hammer": "木锤",
  "item.easy_emerald.wooden_paxel": "木多功能工具",
  "item.easy_emerald.wooden_treeaxe": "木伐木斧",

  "item.easy_emerald.iron_excavator": "铁开掘铲",
  "item.easy_emerald.iron_hammer": "铁锤",
  "item.easy_emerald.iron_paxel": "铁多功能工具",
  "item.easy_emerald.iron_treeaxe": "铁伐木斧",

  "item.easy_emerald.gold_excavator": "金开掘铲",
  "item.easy_emerald.gold_hammer": "金锤",
  "item.easy_emerald.gold_paxel": "金多功能工具",
  "item.easy_emerald.gold_treeaxe": "金伐木斧",
```
与原版格式统一

2024-01-22 09:38 UTC, ChuijkYahus commented on projects/1.20/assets/forked-easy-emerald-tools-more-forge/easy_emerald/lang/zh_cn.json
> +  "itemGroup.easy_emerald" : "简单工具"
```suggestion
  "itemGroup.easy_emerald" : "简单绿宝石"
```
```suggestion
  "itemGroup.easy_emerald" : "Easy Emerald"
```
遵循原文，或模组名不翻译

2024-01-22 09:38 UTC, EnchantGapple233 commented
> 请注意签署CLA
> 
> @EnchantGapple233

已签署

2024-01-22 09:39 UTC, EnchantGapple233 commented on projects/1.20/assets/forked-easy-emerald-tools-more-forge/easy_emerald/lang/zh_cn.json
> +  "itemGroup.easy_emerald" : "简单工具"
以上为1.18.2版本该翻译，我在翻译时将旧版本已有其复制过来的

2024-01-22 09:42 UTC, ChuijkYahus commented on projects/1.20/assets/forked-easy-emerald-tools-more-forge/easy_emerald/lang/zh_cn.json
> +  "itemGroup.easy_emerald" : "简单工具"
可以直接改1182（）
这模组之前的模组名翻译就有问题，建议改一下

2024-03-09 12:44 UTC, luoxueyasha commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

@EnchantGapple233

2024-06-01 11:35 UTC, luoxueyasha commented
请注意回应审查人的审查意见，若 24 小时内不回应，该 PR 即将被关闭。相关规则见[贡献方针](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#搁置规则)。

2024-06-03 01:42 UTC, luoxueyasha commented
因为超时所以pr已被关闭
如有reopen的需求请联系我们

2024-06-03 01:42 UTC, closed without merging