Small Ships 汉化更新至1.19
CFPAOrg/Minecraft-Mod-Language-Package pull request #4091
Opened 2024-01-22 08:12 UTC by RCqaq

2024-01-22 08:35 UTC, ChuijkYahus requested changes

2024-01-22 08:35 UTC, ChuijkYahus commented on projects/1.19/assets/small-ships/smallships/lang/zh_cn.json
> +  "tooltip.plane.throttle": "功率：%s %%",
```suggestion
  "tooltip.plane.damage": "损伤：%s%%",
  "tooltip.plane.throttle": "功率：%s%%",
```

2024-01-22 09:27 UTC, ChuijkYahus approved these changes
没有port和starboard没内味（）

2024-01-22 09:27 UTC, ChuijkYahus commented
确认与对应版本语言文件符合即可

2024-01-23 06:16 UTC, luoxueyasha commented
中英文key不一致，确定游戏内可以被正常读取吗

2024-01-24 09:57 UTC, ChuijkYahus approved these changes

2024-01-24 22:14 UTC, merged