expanded storage 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4110
Opened 2024-01-25 18:52 UTC by 258654aun

由 CFPA-Helper 提交。

2024-02-22 09:10 UTC, 502y requested changes
另外，curseforge及Gitlab链接均无法访问，烦请确认模组是否仍然存在

2024-02-22 09:10 UTC, 502y commented on projects/1.20/assets/expanded-storage/expandedstorage/lang/zh_cn.json
> +  "tooltip.expandedstorage.stores_x_stacks": "能储存 %s 格物品",
```suggestion
  "container.expandedstorage.generic_double": "大%s",
  "tooltip.expandedstorage.alt_use": "%1$s+%2$s",
  "tooltip.expandedstorage.added_by": "增加：%s",
  "tooltip.expandedstorage.stores_x_stacks": "能储存%s格物品",
```

2024-02-22 09:10 UTC, 502y commented on projects/1.20/assets/expanded-storage/expandedstorage/lang/zh_cn.json
> +  "tooltip.expandedstorage.storage_mutator.tool_mode": "模式: %s",
```suggestion
  "tooltip.expandedstorage.storage_mutator.tool_mode": "模式：%s",
```

2024-02-22 09:10 UTC, 502y commented on projects/1.20/assets/expanded-storage/expandedstorage/lang/zh_cn.json
> +  "tooltip.expandedstorage.storage_mutator.description_merge": "%s 点击两个相邻的箱子来合并它们",
```suggestion
  "tooltip.expandedstorage.storage_mutator.description_merge": "%s点击两个相邻的箱子来合并它们",
```

2024-02-22 09:10 UTC, 502y commented on projects/1.20/assets/expanded-storage/expandedstorage/lang/zh_cn.json
> +  "tooltip.expandedstorage.storage_mutator.merge_start": "合并开始，请 %s 点击另一个箱子。",
```suggestion
  "tooltip.expandedstorage.storage_mutator.merge_start": "合并开始，请%s点击另一个箱子。",
```

2024-02-22 09:10 UTC, 502y commented on projects/1.20/assets/expanded-storage/expandedstorage/lang/zh_cn.json
> +  "tooltip.expandedstorage.storage_mutator.description_rotate": "%s 点击箱子来改变它的方向。",
```suggestion
  "tooltip.expandedstorage.storage_mutator.description_rotate": "%s点击箱子来改变它的方向。",
```

2024-02-22 09:10 UTC, 502y commented on projects/1.20/assets/expanded-storage/expandedstorage/lang/zh_cn.json
> +  "tooltip.expandedstorage.storage_mutator.description_split": "%s 点击一个大箱子来把它分离成两个箱子。",
```suggestion
  "tooltip.expandedstorage.storage_mutator.description_split": "%s点击一个大箱子来把它分离成两个箱子。",
```

2024-02-22 09:10 UTC, 502y commented on projects/1.20/assets/expanded-storage/expandedstorage/lang/zh_cn.json
> +  "tooltip.expandedstorage.conversion_kit_wood_copper_1": "%s 点击木箱子",
```suggestion
  "tooltip.expandedstorage.storage_mutator.description_swap_theme": "%s点击一个箱子来更换它的样式",
  "tooltip.expandedstorage.conversion_kit_wood_copper_1": "%s点击木箱子",
```

2024-02-22 09:10 UTC, 502y commented on projects/1.20/assets/expanded-storage/expandedstorage/lang/zh_cn.json
> +  "tooltip.expandedstorage.conversion_kit_wood_iron_1": "%s 点击木箱子",
```suggestion
  "tooltip.expandedstorage.conversion_kit_wood_iron_1": "%s点击木箱子",
```

2024-02-22 09:10 UTC, 502y commented on projects/1.20/assets/expanded-storage/expandedstorage/lang/zh_cn.json
> +  "tooltip.expandedstorage.conversion_kit.need_x_upgrades": "升级失败，您需要 %s 次以上的升级。",
```suggestion
  "tooltip.expandedstorage.conversion_kit_wood_gold_1": "%s点击木箱子",
  "tooltip.expandedstorage.conversion_kit_wood_gold_2": "来把它升级成金箱子。",
  "tooltip.expandedstorage.conversion_kit_wood_diamond_1": "%s点击木箱子",
  "tooltip.expandedstorage.conversion_kit_wood_diamond_2": "来把它升级成钻石箱子。",
  "tooltip.expandedstorage.conversion_kit_wood_obsidian_1": "%s点击木箱子",
  "tooltip.expandedstorage.conversion_kit_wood_obsidian_2": "来把它升级成黑曜石箱子。",
  "tooltip.expandedstorage.conversion_kit_wood_netherite_1": "%s点击木箱子",
  "tooltip.expandedstorage.conversion_kit_wood_netherite_2": "来把它升级成下界合金箱子。",
  "tooltip.expandedstorage.conversion_kit_copper_iron_1": "%s点击铜箱子",
  "tooltip.expandedstorage.conversion_kit_copper_iron_2": "来把它升级成铁箱子。",
  "tooltip.expandedstorage.conversion_kit_copper_gold_1": "%s点击铜箱子",
  "tooltip.expandedstorage.conversion_kit_copper_gold_2": "来把它升级成金箱子。",
  "tooltip.expandedstorage.conversion_kit_copper_diamond_1": "%s点击铜箱子",
  "tooltip.expandedstorage.conversion_kit_copper_diamond_2": "来把它升级成钻石箱子。",
  "tooltip.expandedstorage.conversion_kit_copper_obsidian_1": "%s 点击铜箱子",
  "tooltip.expandedstorage.conversion_kit_copper_obsidian_2": "来把它升级成黑曜石箱子。",
  "tooltip.expandedstorage.conversion_kit_copper_netherite_1": "%s点击铜箱子",
  "tooltip.expandedstorage.conversion_kit_copper_netherite_2": "来把它升级成下界合金箱子。",
  "tooltip.expandedstorage.conversion_kit_iron_gold_1": "%s点击铁箱子",
  "tooltip.expandedstorage.conversion_kit_iron_gold_2": "来把它升级成金箱子。",
  "tooltip.expandedstorage.conversion_kit_iron_diamond_1": "%s点击铁箱子",
  "tooltip.expandedstorage.conversion_kit_iron_diamond_2": "来把它升级成钻石箱子。",
  "tooltip.expandedstorage.conversion_kit_iron_obsidian_1": "%s点击铁箱子",
  "tooltip.expandedstorage.conversion_kit_iron_obsidian_2": "来把它升级成黑曜石箱子。",
  "tooltip.expandedstorage.conversion_kit_iron_netherite_1": "%s点击铁箱子",
  "tooltip.expandedstorage.conversion_kit_iron_netherite_2": "来把它升级成下界合金箱子。",
  "tooltip.expandedstorage.conversion_kit_gold_diamond_1": "%s点击金箱子",
  "tooltip.expandedstorage.conversion_kit_gold_diamond_2": "来把它升级成钻石箱子。",
  "tooltip.expandedstorage.conversion_kit_gold_obsidian_1": "%s点击金箱子",
  "tooltip.expandedstorage.conversion_kit_gold_obsidian_2": "来把它升级成黑曜石箱子。",
  "tooltip.expandedstorage.conversion_kit_gold_netherite_1": "%s 点击金箱子",
  "tooltip.expandedstorage.conversion_kit_gold_netherite_2": "来把它升级成下界合金箱子。",
  "tooltip.expandedstorage.conversion_kit_diamond_obsidian_1": "%s点击钻石箱子",
  "tooltip.expandedstorage.conversion_kit_diamond_obsidian_2": "来把它升级成黑曜石箱子。",
  "tooltip.expandedstorage.conversion_kit_diamond_netherite_1": "%s点击钻石箱子",
  "tooltip.expandedstorage.conversion_kit_diamond_netherite_2": "来把它升级成下界合金箱子。",
  "tooltip.expandedstorage.conversion_kit_obsidian_netherite_1": "%s点击黑曜石箱子",
  "tooltip.expandedstorage.conversion_kit_obsidian_netherite_2": "来把它升级成下界合金箱子。",
  "tooltip.expandedstorage.conversion_kit.need_x_upgrades": "升级失败，您需要%s次以上的升级。",
```

2024-02-22 09:10 UTC, 502y commented on projects/1.20/assets/expanded-storage/expandedstorage/lang/zh_cn.json
> +  "chat.ellemes_container_lib.cannot_display_screen": "无法打开 \"%s\" 类型的库存，请尝试其他类型。",
```suggestion
  "chat.ellemes_container_lib.cannot_display_screen": "无法打开“%s”类型的库存，请尝试其他类型。",
```

2024-02-22 13:17 UTC, 258654aun reviewed
已修正

2024-02-27 06:42 UTC, 502y commented
> 那现在这个PR还要继续吗？

@258654aun 疑似相同作者继任，你可以看看这个https://legacy.curseforge.com/minecraft/mc-mods/expanded-storage

2024-02-28 13:00 UTC, 258654aun commented
> > 那现在这个PR还要继续吗？
> 
> @258654aun 疑似相同作者继任，你可以看看这个https://legacy.curseforge.com/minecraft/mc-mods/expanded-storage

看了一下，应该是同一个模组，但语言文件多了十几行，等我更新一下

2024-03-06 11:18 UTC, 502y requested changes

2024-03-06 11:18 UTC, 502y commented on projects/1.20/assets/expanded-storage/expandedstorage/lang/zh_cn.json
> +  "block.expandedstorage.waxed_oxidized_copper_barrel": "涂蜡的氧化的铜桶",
```suggestion
  "block.expandedstorage.waxed_exposed_copper_barrel": "涂蜡的斑驳铜桶",
  "block.expandedstorage.waxed_weathered_copper_barrel": "涂蜡的锈蚀铜桶",
  "block.expandedstorage.waxed_oxidized_copper_barrel": "涂蜡的氧化铜桶",
```
与原版对齐

2024-03-06 11:18 UTC, 502y commented on projects/1.20/assets/expanded-storage/expandedstorage/lang/zh_cn.json
> +  "block.expandedstorage.waxed_oxidized_copper_mini_barrel": "涂蜡的氧化的铜迷你桶",
```suggestion
  "block.expandedstorage.waxed_exposed_copper_mini_barrel": "涂蜡的斑驳铜迷你桶",
  "block.expandedstorage.waxed_weathered_copper_mini_barrel": "涂蜡的锈蚀铜迷你桶",
  "block.expandedstorage.waxed_oxidized_copper_mini_barrel": "涂蜡的氧化铜迷你桶",
```

2024-03-06 13:23 UTC, 258654aun reviewed
已修正

2024-03-29 00:35 UTC, luoxueyasha commented on projects/1.20/assets/expanded-storage/expandedstorage/lang/zh_cn.json
> +  "tooltip.expandedstorage.storage_mutator.description_merge": "%s点击两个相邻的箱子来合并它们",
游戏内实际显示效果？

2024-03-29 01:58 UTC, 258654aun commented on projects/1.20/assets/expanded-storage/expandedstorage/lang/zh_cn.json
> +  "tooltip.expandedstorage.storage_mutator.description_merge": "%s点击两个相邻的箱子来合并它们",
这个东西没有实装

2024-05-19 07:47 UTC, 258654aun commented on projects/1.20/assets/expanded-storage/expandedstorage/lang/zh_cn.json
> +  "entity.expandedstorage.pumpkin_chest_minecart": "南瓜箱运输矿车",
但是删掉箱之后，前面的材质像是在修饰矿车而不是矿车里的箱子，感觉还是留着更好

2024-05-19 07:52 UTC, 258654aun commented on projects/1.20/assets/expanded-storage/expandedstorage/lang/zh_cn.json
> +  "tooltip.expandedstorage.conversion_kit.need_x_upgrades": "升级失败，您需要%s次以上的升级。",
在升级工具的使用对象与描述不符（例如对木箱子使用铁→金升级工具）时会出现此提示，在最新版本中已被“This conversion kit does not work on that block.（此升级工具不适用于该方块。）”代替

2024-05-19 07:53 UTC, 258654aun commented
已修正

2024-05-27 08:18 UTC, luoxueyasha commented on projects/1.20/assets/expanded-storage/expandedstorage/lang/zh_cn.json
> +  "tooltip.expandedstorage.storage_mutator.description_swap_theme": "%s点击一个箱子来更换它的样式",
```suggestion
  "tooltip.expandedstorage.storage_mutator.description_swap_theme": "%s点击一个箱子来更换它的样式。",
```

2024-05-27 08:18 UTC, luoxueyasha commented on projects/1.20/assets/expanded-storage/expandedstorage/lang/zh_cn.json
> +  "screen.expandedstorage.off_screen_warning_2": "如果你选择此选项。",
这两句的实际显示效果？
建议更换语序

2024-05-27 10:17 UTC, 258654aun commented on projects/1.20/assets/expanded-storage/expandedstorage/lang/zh_cn.json
> +  "screen.expandedstorage.off_screen_warning_2": "如果你选择此选项。",
![QQ截图20240527181615](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/129575695/e748cada-0343-47a3-a136-35712f454e8b)
已修改

2024-05-27 10:21 UTC, 258654aun commented
已修正

2024-05-27 12:35 UTC, mc-kaishixiaxue approved these changes
翻译没有问题；另外，本PR还有一个对话没有设为resolved。

2024-05-27 15:09 UTC, 258654aun commented
> 翻译没有问题；另外，本PR还有一个对话没有设为resolved。
改了

2024-05-27 15:52 UTC, luoxueyasha approved these changes

2024-05-29 12:39 UTC, merged