Missing Wilds 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #4113
Opened 2024-01-26 08:14 UTC by ChuijkYahus

1.20版本中新增的兼容里有三个为quilt独占模组
- Aurora's Decoration (Curseforge, Modrinth, GitHub)
- Softer Pastel ([Modrinth](https://modrinth.com/mod/softer-pastels), GitHub)
- Wandering Wizardry ([GitHub](https://github.com/Sweet-Berry-Collective/Wandering-Wizardry))

2024-03-16 15:09 UTC, Cyl18 submitted a review, later dismissed
ai告诉我没问题

2024-04-21 14:30 UTC, SlimeSB requested changes

2024-04-21 14:30 UTC, SlimeSB commented on projects/1.20/assets/missing-wilds-forge/missingwilds/lang/zh_cn.json
> +  "stat.missingwilds.log_crawl_one_cm": "在原木中爬行距离",
```suggestion
  "stat.missingwilds.log_crawl_one_cm": "原木中爬行距离",

```
向旧版本同步，统计数据的话加个“在”还是有些画蛇添足

2024-04-22 00:21 UTC, SlimeSB approved these changes

2024-04-23 13:36 UTC, merged