Dank Storage翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4120
Opened 2024-01-27 13:00 UTC by fishlanding

2024-01-27 13:04 UTC, ChuijkYahus commented
PR重复，请注意合并

2024-02-02 15:03 UTC, Cactusstudent reviewed
请先全文通查，同时对部分不合适的译文进行更改

2024-02-02 15:03 UTC, Cactusstudent commented on projects/1.16/assets/dank-storage/dankstorage/lang/zh_cn.json
> +  "text.dankstorage.in_use": "此坞正在使用中",
```suggestion
  "text.dankstorage.in_use": "此坞已被占用",

```

2024-02-02 15:03 UTC, Cactusstudent commented on projects/1.16/assets/dank-storage/dankstorage/lang/zh_cn.json
> +  "text.dankstorage.formatcontaineditems": "%s %s",
```suggestion
  "text.dankstorage.formatcontaineditems": "%s%s",

```

2024-02-02 15:03 UTC, Cactusstudent commented on projects/1.16/assets/dank-storage/dankstorage/lang/zh_cn.json
> +  "item.dankstorage.dank_1": "黑盒 Lv1",
对Dank n不同版本的翻译不一致，请进行统一

2024-02-02 15:03 UTC, Cactusstudent commented on projects/1.16/assets/dank-storage/dankstorage/lang/zh_cn.json
> +  "text.dankstorage.shift": "按 %s 查看信息",
中文与英文字符之间不需留空格

2024-02-19 09:44 UTC, ChuijkYahus approved these changes

2024-02-19 09:45 UTC, ChuijkYahus requested changes

2024-02-19 09:45 UTC, ChuijkYahus commented on projects/1.16/assets/dank-storage/dankstorage/lang/zh_cn.json
> +  "item.dankstorage.dank_1": "黑盒 Lv1",
这些Lv前的空格需要保留吗

2024-02-20 07:46 UTC, merged