more-crossbows-cj ，more-bows-cj，Gilded Netherite CJ Edition翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4131
Opened 2024-01-31 10:44 UTC by DBDBS

翻译提交

2024-01-31 15:47 UTC, qznfbnj commented
这俩文件的路径怎么回事
![S40131-23461896_com kiwibrowser browser](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/100760086/4ffeb85f-444c-42f8-99dc-b487bb6b13a6)

2024-02-01 06:00 UTC, luoxueyasha commented
文件路径不正确，请注意修改
具体文件路径请参考仓库内其他pr或已在仓库中的内容

2024-02-02 05:03 UTC, ChuijkYahus commented
> > 我提交的是两个模组的翻译（
> 
> 还是需要更改的对吗？

![Y}ZRMJUH1JZUG 5)Q0Y$S9M](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/3967cadc-7205-4333-8452-cfa1e62e7daf)
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md#%E4%BB%93%E5%BA%93%E7%BB%93%E6%9E%84
现有的文件结构路径明显错误，请注意修改

2024-02-02 09:40 UTC, luoxueyasha requested changes
请不要spam评论

2024-02-02 09:40 UTC, luoxueyasha commented on projects/1.20/assets/more-bows-cj/morebows/lang/zh_cn.json
> +	"item.morebows.smithing_template.bow_upgrade.ingredients": "铜, 铁, 金, 绿宝石, 钻石 块",
```suggestion
	"item.morebows.smithing_template.bow_upgrade.ingredients": "铜、铁、金、绿宝石、钻石 块",
```
应使用全角标点，此类问题请全文通查
并列的词汇之间应使用顿号而非逗号
这条在游戏内的具体显示情况？感觉单拿出一个“块”放在句尾是不是不太妥

2024-02-02 09:40 UTC, luoxueyasha commented on projects/1.20/assets/more-bows-cj/morebows/lang/zh_cn.json
> +	"advancements.adventure.morebows.obtain_copper_bow.description": "一把铜质的弓!",
```suggestion
	"advancements.adventure.morebows.obtain_copper_bow.description": "一把铜质的弓！",
```
全角标点
此类问题请全文通查

2024-02-03 05:20 UTC, ChuijkYahus commented
![YZ1%M_98`9XQI0UJODVDW}K](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/ba725619-4a8c-4053-b158-d6f5c4e0a191)
路径再次有误，缺失lang文件夹

2024-02-04 01:10 UTC, luoxueyasha requested changes

2024-02-04 01:10 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "item.enderite.raw_enderite": "末影合金粗矿",
合金一般不会以矿的形式出现在天然环境下
这玩意是怎么获得的？

2024-02-04 01:10 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "tooltip.enderite.enderite_sword_teleport_range": "区块范围",
是方块还是区块

2024-02-04 01:10 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "tooltip.enderite.enderite_sword_teleport_charges_info1": "请在你的物品清单中放入珍珠，然后按下鼠标右键进行充能",
inventory：物品栏
一般情况下第二人称可省略
原版术语问题请全文通查

```suggestion
  "tooltip.enderite.enderite_sword_teleport_charges_info1": "在物品栏中放入末影珍珠，然后按下鼠标右键进行充能",
```

2024-02-04 01:10 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "tooltip.enderite.enderite_armor_set_bonus_is_endermite_peaceful": "使注视不会激怒末影人",
endermite是末影人吗

2024-02-04 03:30 UTC, luoxueyasha requested changes

2024-02-04 03:30 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "item.enderite.raw_enderite": "末影合金粗矿",
```suggestion
  "item.enderite.raw_enderite": "粗末影合金",
```
请参照原版翻译
**此类问题请全文通查**

2024-02-05 22:14 UTC, luoxueyasha requested changes

2024-02-05 22:14 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "tooltip.enderite.enderite_pickaxe_configurable": "你可以在 “data/forge/tags/blocks/end_stones.json”中配置可以让末影合金镐破坏更快的方块",
“你可以在X中配置可以让镐破坏更快的方块”
这读着不太流畅啊

2024-02-05 22:14 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "tooltip.enderite.enderite_armor_set_bonus": "套装效果:",
```suggestion
  "tooltip.enderite.enderite_armor_set_bonus": "套装效果：",
```
全角符号问题
全文通查谢谢

2024-02-05 22:14 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "tooltip.enderite.enderite_armor_set_bonus_slow_falling": "按下 “Shift”,获得缓降效果",
```suggestion
  "tooltip.enderite.enderite_armor_set_bonus_slow_falling": "按下“Shift”，获得缓降效果",
```

```suggestion
  "tooltip.enderite.enderite_armor_set_bonus_slow_falling": "按下“Shift”以获得缓降效果",
```
全角符号问题
此外英文单词左右或是引号左右不需要留空格
这两类问题请全文通查

2024-02-05 22:14 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "item.enderite.gilded_enderite_helmet": "镶金的末影合金头盔",
```suggestion
  "item.enderite.gilded_enderite_helmet": "镶金末影合金头盔",
```

见原版`镶金黑石`
[原版译名标准化](https://zh.minecraft.wiki/w/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96)

原本译名问题请全文通查，所有内容都要查，确保没有不一致的情况

2024-02-05 22:14 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "tooltip.enderite.enderite_boots_op_mode": "允许你在末地更快地移动",
上下两行一个让你在一个允许你 英文都是allows you to
这类翻译请全文统一

此外中英文文件请对齐行数

2024-02-06 02:34 UTC, luoxueyasha requested changes
原版术语、标点符号这类问题已经不是第一次在本pr中提醒了。
这样下去审查会变得很难进行，请务必仔细阅读我们仓库的 [贡献方针](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md) 。

2024-02-06 02:34 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "item.enderite.enderite_shovel": "末影合金铲",
```suggestion
  "item.enderite.enderite_shovel": "末影合金锹",
```
建议还是先对着bot的diff术语提示，把你翻译的所有内容都查一遍吧
已经是第四次提示“原版术语翻译问题请全文通查”了，错误太多真的没法逐一指出

2024-02-06 02:34 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "tooltip.enderite.enderite_boots_configurable": "您可以在“data/forge/tags/blocks/enderite_boots_walks_faster_on_blocks.json”中配置玩家在上方获得速度增益的方块",
```suggestion
  "tooltip.enderite.enderite_boots_configurable": "你可以在“data/forge/tags/blocks/enderite_boots_walks_faster_on_blocks.json”中配置玩家在上方获得速度增益的方块",
```

```suggestion
  "tooltip.enderite.enderite_boots_configurable": "可以在“data/forge/tags/blocks/enderite_boots_walks_faster_on_blocks.json”中配置玩家在上方获得速度增益的方块列表",
```


说明性文本中一般不用“您”，并尽量避免第一、第二人称
后半段主要是减少歧义，我们配置的是一个list而不是一个block

2024-02-06 02:34 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "tooltip.enderite.enderite_leggings_press_shift": "按下“Shift”,解除已经获得的漂浮效果",
```suggestion
  "tooltip.enderite.enderite_leggings_press_shift": "按下“Shift”，解除已经获得的漂浮效果",
```
标点问题只知其一不知其二是吧
_**在翻译的所有文件里，所有的标点符号都应遵守 [Minecraft 模组简体中文翻译规范与指南](https://cfpa.site/TransRules/) 的标点符号一节的规范。**_

2024-02-07 10:15 UTC, ChuijkYahus requested changes

2024-02-07 10:15 UTC, ChuijkYahus commented on projects/1.20/assets/gilded-netherite-cj-edition/gildednetherite/lang/zh_cn.json
> +  "tooltip.gildednetherite.golden_core_from_nether_chests": "在下界的箱子中可被找到",
```suggestion
  "tooltip.gildednetherite.golden_core_from_nether_chests": "可在下界的箱子中找到",
```
去掉被动

2024-02-07 10:15 UTC, ChuijkYahus commented on projects/1.20/assets/gilded-netherite-cj-edition/gildednetherite/lang/zh_cn.json
> +  "item.gildednetherite.gilded_netherite_shovel": "镶金下界合金铲",
```suggestion
  "item.gildednetherite.gilded_netherite_shovel": "镶金下界合金锹",
```
请全文件通查

2024-02-07 10:15 UTC, ChuijkYahus commented on projects/1.20/assets/more-bows-cj/morebows/lang/zh_cn.json
> +	"item.morebows.smithing_template.bow_upgrade.ingredients": "铜、铁、金、绿宝石、或钻石块",
```suggestion
	"item.morebows.smithing_template.bow_upgrade.ingredients": "铜、铁、金、绿宝石、钻石块",
```
这里都是各种矿物块吗

2024-02-07 10:15 UTC, ChuijkYahus commented on projects/1.20/assets/more-bows-cj/morebows/lang/zh_cn.json
> +	"upgrade.morebows.bow_upgrade": "升级弓",
```suggestion
	"upgrade.morebows.bow_upgrade": "弓升级",
```
这个在游戏中是在锻造模板之类的说明文本里吗

2024-02-07 10:15 UTC, ChuijkYahus commented on projects/1.20/assets/more-bows-cj/morebows/lang/zh_cn.json
> +	"advancements.adventure.morebows.obtain_gilded_netherite_bow.description": "一把镶金下界合金质弓！",
```suggestion
	"advancements.adventure.morebows.obtain_gilded_netherite_bow.description": "一把镶金下界合金质的弓！",
```
请统一进度描述的格式

2024-02-19 09:37 UTC, ChuijkYahus commented on projects/1.20/assets/gilded-netherite-cj-edition/gildednetherite/lang/zh_cn.json
> +  "item.gildednetherite.gilded_netherite_shovel": "镶金下界合金铲",
请注意查看是否已经提交
@DBDBS

2024-06-25 02:23 UTC, closed without merging