Furnish 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4138
Opened 2024-02-02 17:58 UTC by QuincyZhang03

2024-02-06 01:42 UTC, Rinko1231 commented on projects/1.20/assets/furnish/furnish/lang/zh_cn.json
> +  "msg.furnish.mailbox.invalid_mail": "无法寄这个",
```suggestion
  "msg.furnish.mailbox.invalid_mail": "无法寄出此物",

```

2024-03-21 14:01 UTC, ChuijkYahus requested changes
可以重新排一下zh_cn，和en_us键序一致

2024-03-21 14:01 UTC, ChuijkYahus commented on projects/1.20/assets/furnish/furnish/lang/zh_cn.json
> +  "block.furnish.bamboo_log_bench": "竹原木长椅",
```suggestion
  "block.furnish.bamboo_log_bench": "竹原木椅",
```
木制品请统一称呼
建议全文检查所有木制品的名称

2024-03-21 14:53 UTC, QuincyZhang03 commented on projects/1.20/assets/furnish/furnish/lang/zh_cn.json
> +  "block.furnish.bamboo_log_bench": "竹原木长椅",
本mod中同时有chair（椅），bench（长椅）和stool（凳），已按原内容进行区分

2024-03-21 15:23 UTC, QuincyZhang03 commented on projects/1.20/assets/furnish/furnish/lang/zh_cn.json
> +  "block.furnish.bamboo_log_bench": "竹原木长椅",
已进行检查

2024-03-21 16:22 UTC, ChuijkYahus reviewed
建议缩进和空行也统一，不过随意了

2024-03-21 16:22 UTC, ChuijkYahus commented on projects/1.20/assets/furnish/furnish/lang/zh_cn.json
> +	"subtitle.furnish.mail_received": "收到邮件",
```suggestion
	"subtitle.furnish.mail_received": "邮件：接收",
```

2024-03-21 16:22 UTC, ChuijkYahus commented on projects/1.20/assets/furnish/furnish/lang/zh_cn.json
> +	"tooltip.furnish.letter.attachment": "附件: %s",
```suggestion
	"tooltip.furnish.letter.attachment": "附件：%s",
```
全角冒号

2024-03-21 16:22 UTC, ChuijkYahus commented on projects/1.20/assets/furnish/furnish/lang/zh_cn.json
> +	"block.furnish.brick_chimney_conduit": "砖烟囱管",
```suggestion
	"block.furnish.brick_chimney_conduit": "红砖烟囱管",
```
同样，1.20原版术语，请注意全文通查

2024-03-21 16:22 UTC, ChuijkYahus commented on projects/1.20/assets/furnish/furnish/lang/zh_cn.json
> +	"block.furnish.blackstone_chimney_conduit": "黑石砖烟囱管",
```suggestion
	"block.furnish.blackstone_chimney_conduit": "黑石烟囱管",
```
原文没有砖，在游戏内时怎么合成的

2024-03-21 16:22 UTC, ChuijkYahus commented on projects/1.20/assets/furnish/furnish/lang/zh_cn.json
> +	"msg.furnish.recycle_bin_full": "这个垃圾桶满了！Shift右击可清空垃圾桶",
```suggestion
	"msg.furnish.recycle_bin_full": "这个垃圾桶满了！Shift右击可清空垃圾桶。",
```

2024-03-22 03:36 UTC, QuincyZhang03 commented on projects/1.20/assets/furnish/furnish/lang/zh_cn.json
> +	"block.furnish.brick_chimney_conduit": "砖烟囱管",
经检查全文仅此一处出现brick

2024-03-22 03:41 UTC, QuincyZhang03 commented on projects/1.20/assets/furnish/furnish/lang/zh_cn.json
> +	"block.furnish.blackstone_chimney_conduit": "黑石砖烟囱管",
经查验，游戏中配方原料为[磨制黑石砖]

2024-03-23 02:49 UTC, ChuijkYahus requested changes

2024-03-23 02:49 UTC, ChuijkYahus commented on projects/1.20/assets/furnish/furnish/lang/zh_cn.json
> +	"tooltip.furnish.letter.attachment": "附件: %s",
未修改

2024-03-26 07:59 UTC, ChuijkYahus approved these changes

2024-03-29 00:28 UTC, merged