Croparia v4 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4148
Opened 2024-02-06 16:24 UTC by Hoshie-official

2024-02-08 02:49 UTC, luoxueyasha commented
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/38830216/3f1e808f-0d0f-49a5-bc61-2b3c46e36d61)
请问您提交的语言文件对应的模组版本是？

2024-02-08 03:55 UTC, Hoshie-official commented
提交的语言文件对应的版本为：forge1.19.2,游戏版本4.0.1。机器人的提示我看是用fabric下的4.1.1版本进行的对比，而这个模组4.1之前与4.1之后有较大改动。

2024-02-08 03:58 UTC, Hoshie-official commented
> 提交的语言文件对应的版本为：forge1.19.2,游戏版本4.0.1。机器人的提示我看是用fabric下的4.1.1版本进行的对比，而这个模组4.1之前与4.1之后有较大改动。

不好意思，写得有点歧义。模组版本是4.0.1，在forge1.19.2下使用的版本。[FORGE] Croparia-4.0.1 MC 1.19.2

2024-02-08 04:23 UTC, luoxueyasha requested changes

2024-02-08 04:23 UTC, luoxueyasha commented on projects/1.19/assets/croparia/croparia/lang/zh_cn.json
> +  "item.croparia.obsidian_axe": "黑曜石斧头",
```suggestion
  "item.croparia.obsidian_axe": "黑曜石斧",
```
原版的固有名词应与Minecraft原版一致，如有特殊用法请指出。
具体可见我们的 [翻译规范](https://cfpa.site/TransRules/) 中 **06.专有名词** 一节。
你也可以通过上方评论中，bot生成的对比（diff）文件或 [Minecraft 译名标准化](https://zh.minecraft.wiki/w/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96) 以获取更多的原版翻译帮助。
诸如这类的问题请在您翻译的所有文件中全部查明并修改。

2024-02-08 04:23 UTC, luoxueyasha commented on projects/1.19/assets/croparia/croparia/lang/zh_cn.json
> +  "item.croparia.wood_multitool": "木制万用工具",
```suggestion
  "item.croparia.wood_multitool": "木制多功能工具",
```
继承自库内1.16 1.18的croparia
建议看看库内已有的翻译

2024-02-08 04:23 UTC, luoxueyasha commented on projects/1.19/assets/croparia/croparia/lang/zh_cn.json
> +  "item.croparia.wood_knife": "木质小刀",
```suggestion
  "item.croparia.wood_knife": "木小刀",
```
同上
此类问题请全文通查

2024-02-19 09:52 UTC, ChuijkYahus requested changes

2024-02-26 22:10 UTC, luoxueyasha commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

@Hoshie-official

2024-03-05 02:51 UTC, Hoshie-official commented on projects/1.19/assets/croparia/croparia/lang/zh_cn.json
> +  "block.croparia.block_crop_firework": "烟火之星作物",
是烟火之星

2024-03-16 02:03 UTC, ChuijkYahus requested changes
请务必注意全文统一和原版用语

2024-03-16 02:03 UTC, ChuijkYahus commented on projects/1.19/assets/croparia/croparia/lang/zh_cn.json
> +  "item.croparia.fruit_crystal": "海晶沙粒果实",
```suggestion
  "item.croparia.fruit_crystal": "海晶砂粒果实",
```

2024-03-16 02:03 UTC, ChuijkYahus commented on projects/1.19/assets/croparia/croparia/lang/zh_cn.json
> +  "block.croparia.block_crop_crystal": "海晶砂砾作物",
```suggestion
  "block.croparia.block_crop_crystal": "海晶砂粒作物",
```

2024-03-16 02:03 UTC, ChuijkYahus commented on projects/1.19/assets/croparia/croparia/lang/zh_cn.json
> +  "item.croparia.seed_crop_crystal": "海晶沙粒种子",
```suggestion
  "item.croparia.seed_crop_crystal": "海晶砂粒种子",
```

2024-03-16 02:18 UTC, ChuijkYahus approved these changes

2024-03-25 13:32 UTC, luoxueyasha approved these changes

2024-03-25 13:32 UTC, merged