Handcrafted 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4150
Opened 2024-02-08 12:32 UTC by QuincyZhang03

官方有自带zh_cn语言文件但并不完善，已将遗漏项进行补全后提交。
以“painting.”开头的键为画的名称，已根据画的实际内容进行翻译。

2024-02-08 13:54 UTC, dovisutu commented
库里面的handcrafted来源#4136 ，现在看可能是把1.19也给1.20的弄了一份
（当时合并完了感觉有点怪，结果还真是......）
那正好，把正确的语言文件弄好就行

2024-02-08 13:56 UTC, QuincyZhang03 commented
> 库里面的handcrafted来源#4136 ，现在看可能是把1.19也给1.20的弄了一份 （当时合并完了感觉有点怪，结果还真是......） 那正好，把正确的语言文件弄好就行

@dovisutu 确实，原有的那个语言文件里的内容在1.20已经被移除了，至少英文语言文件里是没看到的

2024-02-11 16:55 UTC, mamaruo commented on projects/1.20/assets/handcrafted/handcrafted/lang/zh_cn.json
> +	"tooltip.handcrafted.sheet": "手持床单右键单击，可以更改外观"
| **审查级别** | 备注 |
|--------------|----|
| 🔵 一般 / **阻止合并** |  /  |

都缺少句号。

部分行与原文有出入，请斟酌。
如336行原文并未提及“颜色”。
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/37480168/9e7575ac-ff41-4f8d-be90-6079138d5356)
又如后几行是否需要指出动作对象block?
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/37480168/1b8f075b-1bc5-477e-a3d3-db22171bdbd9)

2024-02-11 17:25 UTC, QuincyZhang03 commented on projects/1.20/assets/handcrafted/handcrafted/lang/zh_cn.json
> +	"tooltip.handcrafted.sheet": "手持床单右键单击，可以更改外观"
感谢审阅。
- 句号已经进行补充。
- “颜色”为笔误，抱歉。
- block个人认为不是很需要指出，因为这些文本的出现场景是家具方块的tooltips（描述）上，“更改外观”的对象必然是该方块。

2024-03-21 14:07 UTC, ChuijkYahus requested changes

2024-03-21 14:07 UTC, ChuijkYahus commented on projects/1.20/assets/handcrafted/handcrafted/lang/zh_cn.json
> +	"block.handcrafted.bricks_pillar_trim": "砖块柱饰",
```suggestion
	"block.handcrafted.bricks_corner_trim": "红砖檐饰",
	"block.handcrafted.bricks_pillar_trim": "红砖柱饰",
```
1.20标准用语

2024-03-21 14:07 UTC, ChuijkYahus commented on projects/1.20/assets/handcrafted/handcrafted/lang/zh_cn.json
> +	"block.handcrafted.wood_plate": "木质盘子",
建议不要加`质`

2024-03-21 14:07 UTC, ChuijkYahus commented on projects/1.20/assets/handcrafted/handcrafted/lang/zh_cn.json
> +	"painting.handcrafted.ad_astra.title": "达到星辰",
画作的名称不应翻译，请注意改回

2024-03-21 14:07 UTC, ChuijkYahus commented on projects/1.20/assets/handcrafted/handcrafted/lang/zh_cn.json
> +	"block.handcrafted.yellow_crockery_combo": "黄色餐具组合",
话说`餐具套组`怎么样

2024-03-21 14:43 UTC, ChuijkYahus commented on projects/1.20/assets/handcrafted/handcrafted/lang/zh_cn.json
> +	"block.handcrafted.terracotta_thin_pot": "陶瓦瘦型罐子",
这个用`细型`觉得怎么样

2024-03-21 14:44 UTC, QuincyZhang03 commented on projects/1.20/assets/handcrafted/handcrafted/lang/zh_cn.json
> +	"block.handcrafted.terracotta_thin_pot": "陶瓦瘦型罐子",
可以的，这个好像是官方自带的zh_cn文件的内容

2024-03-29 00:28 UTC, merged