提交翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #4154
Opened 2024-02-09 05:57 UTC by north-dt

2024-02-09 07:17 UTC, luoxueyasha commented
pr标题应为“模组英文原名 翻译提交”
请修改pr标题

2024-02-09 07:18 UTC, luoxueyasha commented
拔刀剑本体#4036
拔刀剑官方附属#4033
可以看一下那边我们的讨论意见

2024-02-11 08:53 UTC, north-dt commented
啊？我CLA签了啊
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/122965323/bd3de181-0329-4620-9d2a-598e7576c638)

2024-02-11 11:09 UTC, luoxueyasha commented
需要等我们的审阅意见才能合并

2024-02-11 23:11 UTC, luoxueyasha requested changes

2024-02-11 23:11 UTC, luoxueyasha commented on projects/1.16/assets/relics-of-gaming/rogblades/lang/zh_cn.json
> +   "item.slashblade.ex.beastlord": "遗物「兽王」",
```suggestion
   "item.slashblade.ex.beastlord": "百兽剑王",
```
库内的拔刀剑2完全遵循原文翻译，不再延续拔刀剑1的命名模式
英语里的`--`等同于中文里的`「」`
刀、刀组件的格式问题请在所有翻译文件中查明并修改

此外武器neta了尼尔系列的百兽剑王：https://www.bilibili.com/read/cv11251513/

2024-02-11 23:11 UTC, luoxueyasha commented on projects/1.16/assets/relics-of-gaming/rogblades/lang/zh_cn.json
> +   "item.slashblade.ex.virtuous": "遗物「贞洁」",
```suggestion
   "item.slashblade.ex.virtuous": "纯白契约",
```
同上，来自尼尔系列
刀名原neta可以查看curseforge简介，这类问题请在翻译文件中全部查明并修改
对于此类问题不再指出

2024-02-11 23:11 UTC, luoxueyasha commented on projects/1.16/assets/relics-of-gaming/rogblades/lang/zh_cn.json
> +   "item.slashblade.ex.rogboken": "遗物「木刀」",
合成表是？

2024-02-19 09:33 UTC, ChuijkYahus commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@north-dt

2024-02-27 20:06 UTC, closed without merging