waystones 1.20翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #4159
Opened 2024-02-10 14:47 UTC by ahuai6

以前的翻译过于陈旧，我翻译了一个最新版本＋汉化模组配置的

2024-02-10 15:10 UTC, lrcno6 commented
你从哪里弄的翻译？有很多译名应该和现在所用的不符，例如指路石，*色同族指路石

2024-02-10 15:38 UTC, ahuai6 commented
@lrcno6 确实，指路石更贴近原文，但我觉得那有点像机翻，因为直接机翻waystones是路石，游戏内它的作用也是传送而非指路/路标，所以我选择了传送石碑这个更符合游戏内的叫法，*色同组指路石我也将其改成了*色族传送石碑（无色同族指路石翻译为同族传送石碑），为什么有色的去掉“同”是因为我觉得既然都称作“族”了，那么叫做白色族，黑色族，应该更贴近中文遇境

2024-02-10 15:41 UTC, lrcno6 commented
那好，我问你，攀藤是什么东西？翻成苔石、附苔都要好点吧？

2024-02-10 15:42 UTC, lrcno6 commented
个人建议是waystone的翻译维持原翻译。如果你对某个具体的译名有意见可以进群讨论

2024-02-10 15:42 UTC, ahuai6 commented
@lrcno6 因为合成它用到的是普通传送石碑和藤蔓，之前考虑过苔石和附苔，甚至附藤

2024-02-10 15:43 UTC, ahuai6 commented
@lrcno6 好的，那我将waystone做了修改后再行提交

2024-02-10 15:48 UTC, lrcno6 commented
> @lrcno6 确实，指路石更贴近原文，但我觉得那有点像机翻，因为直接机翻waystones是路石，游戏内它的作用也是传送而非指路/路标，所以我选择了传送石碑这个更符合游戏内的叫法，_色同组指路石我也将其改成了_色族传送石碑（无色同族指路石翻译为同族传送石碑），为什么有色的去掉“同”是因为我觉得既然都称作“族”了，那么叫做白色族，黑色族，应该更贴近中文遇境

我不太理解指路石像机翻是什么意思。可能指路石确实没有传送石碑更能反映其功能（事实上这也是早期社区的译名），但我认为这不是能以一句“像机翻”能攻击的。
之后是*色族……其原文是 * sharestone，同族是对sharestone的翻译，颜色是属于sharestone（同族指路石）的而非*族的

2024-02-10 15:48 UTC, lrcno6 commented
> @lrcno6 因为合成它用到的是普通传送石碑和藤蔓，之前考虑过苔石和附苔，甚至附藤

原版苔石不也是这样的吗……

2024-02-10 15:55 UTC, ahuai6 commented
@lrcno6 非常抱歉，实际上我并不想攻击指路石这个翻译本身像机翻，或者暗示它是机翻，而是我个人认为它不太贴合实际，有种机翻的感觉，后续说的问题我也已经明白，再次表达歉意

2024-02-10 15:55 UTC, lrcno6 commented
还有就是，如无必要的话，PR内容最好整合到一个commit后再提交PR（与本项目无关只是关于Git的建议

2024-02-10 15:56 UTC, ahuai6 commented
多谢指导

2024-02-10 16:00 UTC, lrcno6 commented
> @lrcno6 非常抱歉，实际上我并不想攻击指路石这个翻译本身像机翻，或者暗示它是机翻，而是我个人认为它不太贴合实际，有种机翻的感觉，后续说的问题我也已经明白，再次表达歉意

我可能有些话说重了……事实上个人其实一般也是说传送石碑的。但我个人并不反对指路石这个译名，个人并不认为指路石会对其功能有过多的曲解（路牌具有传送功能的游戏太多了）。至于敲定这个译名的过程……我当时没入汉化圈わかりません

2024-02-10 16:02 UTC, lrcno6 commented
还有，你更的是fabric 1.20吧，在标题里说明fabric（不然一般默认forge），还有你1.20和fabric的label去哪了

2024-02-11 02:04 UTC, lrcno6 commented
@ahuai6 不是啊？版本和fabric的label是会由bot自动打的啊？你发布pr之后bot不就给打上了吗？什么时候被点掉了？

2024-02-11 02:08 UTC, ahuai6 commented
@lrcno6 刚才更新了之后我看label自己就打上去了，之前确实是没有的，不是我故意点掉的（不小心也说不定）总之现在应该是有label了吧？

2024-02-11 02:11 UTC, lrcno6 commented
![IMG_20240211_101027](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/42689208/2d396ed6-b094-4cb0-85d5-e23e44cd47e8)
有内鬼（

2024-02-11 16:38 UTC, mamaruo commented
我对比了“库内1.19”和“本PR”的翻译，结果如下：

### 两者皆有且中文有差异

<details><summary>点击展开/收起</summary>
<p>

| **键** | **英文** | **库内1.19** | **本PR** |
|---|---|---|---|
| block.waystones.sandy_waystone | Sandy Waystone | 砂岩指路石 | 雕纹砂岩指路石 |
| block.waystones.pink_sharestone | Pink Sharestone | 粉红色同族指路石 | 粉色同族指路石 |
| block.waystones.warp_plate | Warp Plate | 传送石盘 | 传送石板 |
| block.waystones.portstone | Portstone | 传送石座 | 单向传送石台 |
| item.waystones.return_scroll | Return Scroll | 回程卷轴 | 传回卷轴 |
| item.waystones.warp_dust | Warp Dust | 传送粉尘 | 传送粉 |
| container.waystones.waystone_selection | Select your destination: | 选择你的目的地： | 选择目的地： |
| container.waystones.warp_plate | Warp Plate | 传送石盘 | 传送石板 |
| gui.waystones.waystone_selection.next_page | Next | 下一页 | 下一个 |
| gui.waystones.waystone_selection.previous_page | Previous | 上一页 | 历史 |
| gui.waystones.waystone_selection.current_location | Current Location: %s | 当前位置： | 当前位置：%s |
| gui.waystones.waystone_selection.unnamed_waystone | <unnamed> | 【未命名】 | <未命名> |
| gui.waystones.waystone_selection.hold_shift_to_delete | Hold shift and click to delete | 按住Shift并点击以删除 | 按住shift点击以删除 |
| gui.waystones.waystone_selection.click_to_delete | Click to delete | 点击以删除 | 点击删除 |
| gui.waystones.waystone_selection.deleting_global_for_all | This will remove the waystone for everyone\. | 该操作将为所有玩家移除此全局指路石。 | 这将移除所有指路石 |
| gui.waystones.waystone_selection.no_waystones_activated | You have not activated any waystones yet\. | 你尚未激活任何指路石。 | 你还未激活任何指路石 |
| gui.waystones.waystone_selection.level_requirement | Level Cost: %d | 需花费%d级经验 | 等级消耗：%d |
| gui.waystones.inventory.no_waystones_activated | You have not activated any waystones yet\. | 你尚未激活任何指路石。 | 你还未激活任何指路石 |
| gui.waystones.inventory.confirm_return | Do you really want to warp back to this waystone? | 是否确定传送回该指路石？ | 确定回到这个指路石吗？ |
| gui.waystones.inventory.confirm_return_bound_to | Bound to: %s | 绑定至：%s | 范围：%s |
| gui.waystones.inventory.return_to_waystone | Return to Waystone \.\.\. | 返回指路石…… | 返回指路石\.\.\. |
| chat.waystones.waystone_activated | Activated Waystone: %s | 指路石%s已激活 | 激活的指路石：%s |
| chat.waystones.scroll_bound | Scroll bound: %s | 卷轴已绑定至指路石%s | 卷轴范围：%s |
| chat.waystones.scroll_not_yet_bound | This scroll is not bound to a waystone\. | 该卷轴未绑定至指路石。 | 此卷轴尚未绑定指路石 |
| chat.waystones.cannot_dimension_warp | You cannot warp between these worlds\. | 无法跨维度传送。 | 你不能在这些维度间穿梭 |
| chat.waystones.waystone_missing | The waystone you tried to teleport to is currently being moved or has gone missing\. | 目标指路石已丢失。 | 你正尝试传送到的指路石正在移动或已丢失 |
| chat.waystones.cannot_transport_leashed | You cannot take leashed mobs with you | 无法与拴绳生物一同进行传送 | 你不能带着拴着的生物一起传送 |
| chat.waystones.cannot_transport_leashed_dimensional | You cannot take leashed mobs with you between worlds | 无法与拴绳生物一同进行跨维度传送 | 你不能在传送其他维度之时携带被拴住的生物 |
| chat.waystones.cannot_transport_this_leashed | You cannot take this mob with you | 无法与该生物一同进行传送 | 你不能携带此生物传送 |
| chat.waystones.only_owner_can_edit | Waystones can only be renamed by whoever placed them\. | 指路石只能被其放置者重命名。 | 指路石只能由放置它们的人命名 |
| chat.waystones.only_creative_can_edit | You have to be in creative mode to edit a global waystone\. | 仅在创造模式下方可编辑全局指路石。 | 你必须处于创造模式才能进行编辑全局指路石 |
| chat.waystones.waystone_to_waystone_disabled | You touch the waystone, but nothing happens\. | 你触碰了这块指路石，但无济于事。 | 你触碰了指路石，但什么都没有发生 |
| chat.waystones.warp_plate_has_no_target | This warp plate is not bound to another warp plate yet\. | 这块传送石盘尚未与另一块绑定。 | 此传送石板尚未与其他传送石板绑定 |
| chat.waystones.warp_plate_has_invalid_target | The shard inside this warp plate has lost its attunement\. | 这块传送石盘中的燧石丢失了传送调谐。 | 这块传送石板内的调谐燧石已经失去了调谐 |
| tooltip.waystones.cooldown_left | Cooldown: %d seconds | 冷却时间：%d秒 | 冷却时间：%d 秒 |
| tooltip.waystones.bound_to | Bound to: %s | 绑定至：%s | 范围：%s |
| tooltip.waystones.portstone | Can not be teleported to\. | 无法传送至目标。 | 无法被用作传送目标 |
| tooltip.waystones.sharestone | Teleport to any other colorless Sharestone | 可传送至其他任一无色同族指路石 | 传送到其他任何无色同族指路石 |
| tooltip.waystones.white_sharestone | Teleport to any other White Sharestone | 可传送至其他任一白色同族指路石 | 传送到其他任何白色同族指路石 |
| tooltip.waystones.orange_sharestone | Teleport to any other Orange Sharestone | 可传送至其他任一橙色同族指路石 | 传送到其他任何橙色同族指路石 |
| tooltip.waystones.magenta_sharestone | Teleport to any other Magenta Sharestone | 可传送至其他任一品红色同族指路石 | 传送到其他任何品红色同族指路石 |
| tooltip.waystones.light_blue_sharestone | Teleport to any other Light Blue Sharestone | 可传送至其他任一淡蓝色同族指路石 | 传送到其他任何淡蓝色同族指路石 |
| tooltip.waystones.yellow_sharestone | Teleport to any other Yellow Sharestone | 可传送至其他任一黄色同族指路石 | 传送到其他任何黄色同族指路石 |
| tooltip.waystones.lime_sharestone | Teleport to any other Lime Sharestone | 可传送至其他任一黄绿色同族指路石 | 传送到其他任何黄绿色同族指路石 |
| tooltip.waystones.pink_sharestone | Teleport to any other Pink Sharestone | 可传送至其他任一粉红色同族指路石 | 传送到其他任何粉色同族指路石 |
| tooltip.waystones.gray_sharestone | Teleport to any other Gray Sharestone | 可传送至其他任一灰色同族指路石 | 传送到其他任何灰色同族指路石 |
| tooltip.waystones.light_gray_sharestone | Teleport to any other Light Gray Sharestone | 可传送至其他任一淡灰色同族指路石 | 传送到其他任何淡灰色同族指路石 |
| tooltip.waystones.cyan_sharestone | Teleport to any other Cyan Sharestone | 可传送至其他任一青色同族指路石 | 传送到其他任何青色同族指路石 |
| tooltip.waystones.purple_sharestone | Teleport to any other Purple Sharestone | 可传送至其他任一紫色同族指路石 | 传送到其他任何紫色同族指路石 |
| tooltip.waystones.blue_sharestone | Teleport to any other Blue Sharestone | 可传送至其他任一蓝色同族指路石 | 传送到其他任何蓝色同族指路石 |
| tooltip.waystones.brown_sharestone | Teleport to any other Brown Sharestone | 可传送至其他任一棕色同族指路石 | 传送到其他任何棕色同族指路石 |
| tooltip.waystones.green_sharestone | Teleport to any other Green Sharestone | 可传送至其他任一绿色同族指路石 | 传送到其他任何绿色同族指路石 |
| tooltip.waystones.red_sharestone | Teleport to any other Red Sharestone | 可传送至其他任一红色同族指路石 | 传送到其他任何红色同族指路石 |
| tooltip.waystones.black_sharestone | Teleport to any other Black Sharestone | 可传送至其他任一黑色同族指路石 | 传送到其他任何黑色同族指路石 |
| tooltip.waystones.attuned_shard.move_to_other_warp_plate | Bring this shard to another warp plate\. | 将它带去另一块传送石盘那里。 | 将此调谐燧石带到另一个传送石板上 |
| tooltip.waystones.attuned_shard.plug_into_warp_plate | Insert this shard into a warp plate\. | 将它放入另一块传送石盘之中。 | 将此调谐燧石放入到其他传送石板中 |
| tooltip.waystones.attuned_shard.attunement_lost | This shard has lost its attunement\. | 这块燧石丢失了传送调谐。 | 这个调谐燧石已经失去了调谐 |
| tooltip.waystones.not_enough_xp | Not enough experience\! \(%d levels needed\) | 经验不足！（需要%d级经验） | 经验不足！（需要 %d 级） |
| tooltip.waystones.undiscovered | Undiscovered | 未探明 | 未被发现 |
| waystones:warp_plate | Warp Plate | 传送石盘 | 传送石板 |
| waystones.iconCredits | Icons by JoeCreates \(CC\-BY\-SA 3\.0\) | 图标作者是JoeCreates（CC\-BY\-SA 3\.0） | 图标来自JoeCreates（CC\-BY\-SA 3\.0） |
| waystones.map.untitled_waystone | Untitled Waystone | 未命名的指路石 | 未命名指路石 |

</p>
</details>

### 只在 库内1.19 中有

<details><summary>点击展开/收起</summary>
<p>

| **键** | **英文** | **库内1.19** | **本PR** |
|---|---|---|---|
| container.waystones.waystone_settings | 🚫 | 输入指路石名称： | 🚫 |
| gui.waystones.waystone_settings.is_global | 🚫 | 设为全局 | 🚫 |
| chat.waystones.warpstone_not_charged | 🚫 | 传送石尚未完成充能。 | 🚫 |
| text.autoconfig.waystones.title | 🚫 | 指路石 | 🚫 |
| text.autoconfig.waystones.option.xpCost | 🚫 | 经验消耗选项 | 🚫 |
| text.autoconfig.waystones.option.xpCost.inverseXpCost | 🚫 | 反转经验消耗 | 🚫 |
| text.autoconfig.waystones.option.xpCost.blocksPerXpLevel | 🚫 | 每级经验的方块 | 🚫 |
| text.autoconfig.waystones.option.xpCost.minimumBaseXpCost | 🚫 | 最小基础经验消耗 | 🚫 |
| text.autoconfig.waystones.option.xpCost.maximumBaseXpCost | 🚫 | 最大基础经验消耗 | 🚫 |
| text.autoconfig.waystones.option.xpCost.xpCostPerLeashed | 🚫 | 每个拴绳生物经验消耗 | 🚫 |
| text.autoconfig.waystones.option.xpCost.dimensionalWarpXpCost | 🚫 | 维度传送经验消耗 | 🚫 |
| text.autoconfig.waystones.option.xpCost.globalWaystoneXpCostMultiplier | 🚫 | 全局指路石经验消耗倍数 | 🚫 |
| text.autoconfig.waystones.option.xpCost.warpStoneXpCostMultiplier | 🚫 | 传送石经验消耗倍数 | 🚫 |
| text.autoconfig.waystones.option.xpCost.sharestoneXpCostMultiplier | 🚫 | 同族指路石经验消耗倍数 | 🚫 |
| text.autoconfig.waystones.option.xpCost.waystoneXpCostMultiplier | 🚫 | 指路石经验消耗倍数 | 🚫 |
| text.autoconfig.waystones.option.xpCost.portstone [...]

2024-02-12 01:57 UTC, ahuai6 commented
不一样的其中有两个我觉得我这错了，已经改了（

2024-03-06 11:34 UTC, 502y requested changes

2024-03-06 11:34 UTC, 502y commented on projects/1.20-fabric/assets/waystones/waystones/lang/zh_cn.json
> +  "tooltip.waystones.cooldown_left": "冷却时间：%d 秒",
```suggestion
  "tooltip.waystones.cooldown_left": "冷却时间：%d秒",
```

无需空格

2024-03-06 11:34 UTC, 502y commented on projects/1.20-fabric/assets/waystones/waystones/lang/zh_cn.json
> +  "tooltip.waystones.not_enough_xp": "经验不足！（需要 %d 级）",
```suggestion
  "tooltip.waystones.not_enough_xp": "经验不足！（需要%d级）",
```

同上

2024-03-06 11:34 UTC, 502y commented on projects/1.20-fabric/assets/waystones/waystones/lang/zh_cn.json
> +  "commands.waystones.list.all.footer": "总共 %d 个指路石， %d 个拥有",
```suggestion
  "commands.waystones.count": "%s已激活了%d个指路石并拥有其中%d个",
  "commands.waystones.list.header": "%s的指路石（x，y，z）（仅拥有）：",
  "commands.waystones.list.entry.owned": "-     拥有%s（%s）：%s",
  "commands.waystones.list.entry.activated": "- 已激活 %s（%s）：%s",
  "commands.waystones.list.footer": "拥有%d个指路石",
  "commands.waystones.list.all.header": " %s的指路石（x，y，z）：",
  "commands.waystones.list.all.footer": "总共%d个指路石，%d个拥有",
```

2024-03-06 11:34 UTC, 502y commented on projects/1.20-fabric/assets/waystones/waystones/lang/zh_cn.json
> +  "config.waystones.general.warpStoneUseTime": "传送石的使用时间",
```suggestion
  "config.waystones.general.warpStoneUseTime": "传送石使用时间",
```

下文类似翻译没有”的“

2024-03-06 11:34 UTC, 502y commented on projects/1.20-fabric/assets/waystones/waystones/lang/zh_cn.json
> +  "config.waystones.teleports.enableCosts.tooltip": "设置为 false 可以简单地禁用所有传送时的经验消耗，参阅传送要求以获得更精细的控制功能",
```suggestion
  "config.waystones.teleports.enableCosts.tooltip": "设置为false可以简单地禁用所有传送时的经验消耗，参阅传送要求以获得更精细的控制功能",
```

2024-03-06 11:34 UTC, 502y commented on projects/1.20-fabric/assets/waystones/waystones/lang/zh_cn.json
> +  "config.waystones.teleports.enableCooldowns.tooltip": "设置为 false 可以简单地禁用所有冷却时间，参阅传送要求以获得更精细的控制功能",
```suggestion
  "config.waystones.teleports.enableCooldowns.tooltip": "设置为false可以简单地禁用所有冷却时间，参阅传送要求以获得更精细的控制功能",
```

2024-03-06 11:34 UTC, 502y commented on projects/1.20-fabric/assets/waystones/waystones/lang/zh_cn.json
> +  "config.waystones.teleports.transportPets.tooltip": "设为”ENABLED“时可使附近的宠物与你一起传送，设置为 SAME_DIMENSION 时仅当你的传送不改变维度时附近的宠物才会与你一起传送，设置为 DISABLED 以禁用",
混乱的空格与引号，请保持一致

2024-03-06 11:34 UTC, 502y commented on projects/1.20-fabric/assets/waystones/waystones/lang/zh_cn.json
> +  "config.waystones.teleports.transportLeashed.tooltip": "设为“ENABLED”时可让拴着的生物与你一起传送，设置为 SAME_DIMENSION 时，仅当你的传送不改变维度时拴着的生物才能与你一起传送，设置为 DISABLED 以禁用",
混乱的空格与引号，请保持一致

2024-03-06 11:34 UTC, 502y commented on projects/1.20-fabric/assets/waystones/waystones/lang/zh_cn.json
> +  "config.waystones.inventoryButton.creativeInventoryButtonY.tooltip": "物品栏按钮在创造模式物品栏中的 Y 轴位置",
```suggestion
  "config.waystones.inventoryButton.inventoryButtonX": "传送按钮的X轴位置",
  "config.waystones.inventoryButton.inventoryButtonX.tooltip": "物品栏按钮在物品栏中的X轴位置",
  "config.waystones.inventoryButton.inventoryButtonY": "传送按钮Y轴位置",
  "config.waystones.inventoryButton.inventoryButtonY.tooltip": "物品栏按钮在物品栏中的Y轴位置",
  "config.waystones.inventoryButton.creativeInventoryButtonX": "创造模式传送按钮的X轴位置",
  "config.waystones.inventoryButton.creativeInventoryButtonX.tooltip": "物品栏按钮在创造模式物品栏中的X轴位置",
  "config.waystones.inventoryButton.creativeInventoryButtonY": "创造模式传送按钮的Y轴位置",
  "config.waystones.inventoryButton.creativeInventoryButtonY.tooltip": "物品栏按钮在创造模式物品栏中的Y轴位置",
```

2024-03-06 11:34 UTC, 502y commented on projects/1.20-fabric/assets/waystones/waystones/lang/zh_cn.json
> +  "config.waystones.worldGen.chunksBetweenWildWaystones.tooltip": "生成的野外指路石之间的区块间隔，设置为 0 以禁用野外生成",
```suggestion
  "config.waystones.worldGen.chunksBetweenWildWaystones.tooltip": "生成的野外指路石之间的区块间隔，设置为0以禁用野外生成",
```

2024-03-06 11:34 UTC, 502y commented on projects/1.20-fabric/assets/waystones/waystones/lang/zh_cn.json
> +  "config.waystones.worldGen.wildWaystonesDimensionAllowList.tooltip": "允许生成野外指路石的维度列表，如果留空则使用除 野外指路石维度黑名单 中的维度之外的所有维度",
```suggestion
  "config.waystones.worldGen.wildWaystonesDimensionAllowList.tooltip": "允许生成野外指路石的维度列表，如果留空则使用除野外指路石维度黑名单中的维度之外的所有维度",
```

如果要强调请使用引号，下文同，不再赘述

2024-04-17 01:19 UTC, luoxueyasha commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

@ahuai6

2024-04-25 14:03 UTC, closed without merging