Farmer's Utils 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4163
Opened 2024-02-11 15:25 UTC by wwjdmm

2024-02-11 17:20 UTC, wwjdmm commented
> ## [![](https://private-user-images.githubusercontent.com/14993992/286531248-5f597afc-ee3d-4285-addc-9f9561b4a252.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NzIzMTMsIm5iZiI6MTcwNzY3MjAxMywicGF0aCI6Ii8xNDk5Mzk5Mi8yODY1MzEyNDgtNWY1OTdhZmMtZWUzZC00Mjg1LWFkZGMtOWY5NTYxYjRhMjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDE3MjAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MTEzOWVlYjJjYTI3YmVhZTQwNjhjMmNhYmJmZTg2NDMwMDczMGZkNDI2MTgzODgyMWNhNTdmNGM5MzhjMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YIYe2FK8LdqWnIg5m8mpTnyVwAx6QinAkLaW-HaGNLk)](https://github.com/Cyl18/CFPABot)
> 模组	🔗 链接	🎨 相关文件
> <img alt="" width="32" src="https://camo.githubusercontent.com/48281466181f6f48fe2b8aafb4f1df11333ebaa9b34799ec664845f0b5ea9757/68747470733a2f2f636670612e6379616e2e636166652f7374617469632f3633383430373339373132333637393732352e706e67">	[**Aether Delight (A Farmer's Delight Add-on)**](https://www.curseforge.com/minecraft/mc-mods/aether-delight)	🔍无源代码 | [🟩 MCMOD](https://cn.bing.com/search?q=site:mcmod.cn%20Aether+Delight+(A+Farmer%27s+Delight+Add-on)) | [📁 对比(Azusa)](https://cfpa.cyan.cafe/Azusa/Diff/4163/aether-delight)	
> 最新模组文件
> 语言文件链接
> <img alt="" width="32" src="https://camo.githubusercontent.com/947dcc2c9885db672f0f30cb0c63374fb900a6bbdbf63a02445fbe1d82def876/68747470733a2f2f636670612e6379616e2e636166652f7374617469632f3633383139343137313137343230333935332e706e67">	依赖-[_The Aether_](https://www.curseforge.com/minecraft/mc-mods/aether)	🔍无源代码 | [🟩 MCMOD](https://cn.bing.com/search?q=site:mcmod.cn%20The+Aether) |   *	
> 最新模组文件
> <img alt="" width="32" src="https://camo.githubusercontent.com/43437b383ceaa734dad0a71a11fc4bcd8ab20eac599759017b8fcafb63189a41/68747470733a2f2f636670612e6379616e2e636166652f7374617469632f3633373539353030353631353137393337302e706e67">	依赖-[_Farmer's Delight_](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)	🔍无源代码 | [🟩 MCMOD](https://cn.bing.com/search?q=site:mcmod.cn%20Farmer%27s+Delight) |   *	
> 最新模组文件
> <img alt="" width="32" src="https://camo.githubusercontent.com/9946bae90fc16937c32670666dc691ad5753a458241df34dc15ea7be37ded222/68747470733a2f2f636670612e6379616e2e636166652f7374617469632f3633383430393338323733323431313939382e706e67">	[**Aquaculture Delight (A Farmer's Delight Add-on)**](https://www.curseforge.com/minecraft/mc-mods/aquaculture-delight)	🔍无源代码 | [🟩 MCMOD](https://cn.bing.com/search?q=site:mcmod.cn%20Aquaculture+Delight+(A+Farmer%27s+Delight+Add-on)) | [📁 对比(Azusa)](https://cfpa.cyan.cafe/Azusa/Diff/4163/aquaculture-delight)	
> 最新模组文件
> 语言文件链接
> <img alt="" width="32" src="https://camo.githubusercontent.com/43437b383ceaa734dad0a71a11fc4bcd8ab20eac599759017b8fcafb63189a41/68747470733a2f2f636670612e6379616e2e636166652f7374617469632f3633373539353030353631353137393337302e706e67">	依赖-[_Farmer's Delight_](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)	🔍无源代码 | [🟩 MCMOD](https://cn.bing.com/search?q=site:mcmod.cn%20Farmer%27s+Delight) |   *	
> 最新模组文件
> <img alt="" width="32" src="https://camo.githubusercontent.com/a719c91f397f81dfd1992858728f1f7040ba519010993bd97363e36d1d98a861/68747470733a2f2f636670612e6379616e2e636166652f7374617469632f3633373035393930393034323036343031362e706e67">	依赖-[_Aquaculture 2_](https://www.curseforge.com/minecraft/mc-mods/aquaculture)	🔍无源代码 | [🟩 MCMOD](https://cn.bing.com/search?q=site:mcmod.cn%20Aquaculture+2) |   *	
> 最新模组文件
> <img alt="" width="32" src="https://camo.githubusercontent.com/8c824c4b067d0cbc2d824b29044b9ea0ddefc619f9f00064a3e3f8df662ad679/68747470733a2f2f636670612e6379616e2e636166652f7374617469632f3633383338343135373735323338393635382e706e67">	[**Farmer's Utils**](https://www.curseforge.com/minecraft/mc-mods/farmers-utils)	[🔍 源代码](https://github.com/EndilCrafter/FarmersUtils)   | [🟩 MCMOD](https://cn.bing.com/search?q=site:mcmod.cn%20Farmer%27s+Utils) | [📁 对比(Azusa)](https://cfpa.cyan.cafe/Azusa/Diff/4163/farmers-utils)	
> 最新模组文件
> 语言文件链接
> <img alt="" width="32" src="https://camo.githubusercontent.com/43437b383ceaa734dad0a71a11fc4bcd8ab20eac599759017b8fcafb63189a41/68747470733a2f2f636670612e6379616e2e636166652f7374617469632f3633373539353030353631353137393337302e706e67">	依赖-[_Farmer's Delight_](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)	[🔍 源代码](https://github.com/EndilCrafter/FarmersUtils)   | [🟩 MCMOD](https://cn.bing.com/search?q=site:mcmod.cn%20Farmer%27s+Delight) |   *	
> 最新模组文件
> 💾 基于此 PR 所打包的资源包：
> 
> * [Minecraft-Mod-Language-Package-1.19.zip](https://nightly.link/CFPAOrg/Minecraft-Mod-Language-Package/actions/artifacts/1236713763.zip)
> 
> ✔ `aetherdelight` Mod Domain 验证通过。 ℹ aetherdelight-1.19 语言文件验证通过。 ℹ aetherdelight-1.19 模组内语言文件验证通过。
> 
> ✔ `aquaculturedelight` Mod Domain 验证通过。 ℹ aquaculturedelight-1.19 语言文件验证通过。 ⚠ 警告：PR 中 aquaculturedelight-1.19 的英文语言文件与最新模组 `aquaculture_delight_1.0.0_forge_1.19.4.jar` 内的英文语言文件不对应。自动获取的文件只能反映大多数情况，可能并不需要更新文件。如果你认为英文语言文件**确实**需要更新到**上面的版本**，可以使用命令 `/update-en aquaculture-delight 1.19` 来更新。
> 
> * 模组内语言文件有 1 个 Key 多于英文语言文件。例如：
>   
>   * 行 11-`item_group.aquaculturedelight.aquaculture_delight_tab`
> 
> ✔ `farmersutils` Mod Domain 验证通过。 ℹ farmersutils-1.19 语言文件验证通过。 ℹ farmersutils-1.19 模组内语言文件验证通过。
> 
> 详细检查报告
> 报告也可以在 [这里](https://cfpa.cyan.cafe/static/4163-855f6f8.txt) 查看。在 PR 更新时这里的检查也会自动更新。
> 
> 🔛 Diff：
> 
> aether-delight/1.19
> aether-delight/1.19-keys
> aether-delight/1.19-术语检查
> aquaculture-delight/1.19
> aquaculture-delight/1.19-keys
> aquaculture-delight/1.19-术语检查
> farmers-utils/1.19
> farmers-utils/1.19-keys
> farmers-utils/1.19-术语检查
> ℹ [机器人的命令列表](https://cfpa.cyan.cafe/Azusa/CommandList)
> 
> * [x]  🔄 勾选这个复选框来强制刷新

2024-02-11 22:56 UTC, luoxueyasha reviewed
天境乐事和水产乐事没啥问题
下次引用库内翻译时请附带说明谢谢

2024-02-11 22:58 UTC, luoxueyasha commented
@ChuijkYahus 麻烦看一下Farmers' Utils的基本名词

2024-02-11 23:00 UTC, luoxueyasha commented on projects/1.19/assets/farmers-utils/farmersutils/lang/zh_cn.json
> +  "config.farmersutils.general_settings.enable_nethersdelight_storages": "启用 Nether's Delight 材料压缩成块存储",
要不要把下界乐事也翻出来？

```suggestion
  "config.farmersutils.general_settings.enable_nethersdelight_storages": "启用Nether's Delight材料压缩成块存储",
```
如果保留原文的话：在1.16或更高版本下，英文字母、阿拉伯数字等非中文文本无需在前后添加空格。
具体可见我们的 [翻译规范](https://cfpa.site/TransRules/) 中 **04.排版** 一节下。
诸如这类的问题请在您翻译的所有文件中全部查明并修改。

2024-02-12 09:56 UTC, wwjdmm commented
其中aether-delight，aquaculture-delight，festive-delight，maturi-delight，quark-delight为库内翻译搬运
值得注意的是 Italian Delight 位于 curseforge 地址改变，建议更改1.18的内容
[Italian Delight](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/4163/commits/43054debe84df2d3dfef10262322aa0f37e7aea8)
另外，Italian Delight 的部分翻译参照了库内翻译

2024-02-14 04:41 UTC, ChuijkYahus requested changes
另外两个是引用库内的版本吧，应该没有问题

2024-02-14 04:41 UTC, ChuijkYahus commented on projects/1.19/assets/farmers-utils/farmersutils/lang/zh_cn.json
> +  "config.farmersutils.general_settings.enable_nethersdelight_storages": "启用 Nether's Delight 材料压缩成块存储",
```suggestion
  "config.farmersutils.general_settings.enable_nethersdelight_storages": "启用Nether's Delight材料压缩成块存储",
```

2024-02-14 04:41 UTC, ChuijkYahus commented on projects/1.19/assets/farmers-utils/farmersutils/lang/zh_cn.json
> +  "config.farmersutils.compats": "兼容 MOD",
```suggestion
  "config.farmersutils.compats": "兼容模组",
```

2024-02-14 04:41 UTC, ChuijkYahus commented on projects/1.19/assets/farmers-utils/farmersutils/lang/zh_cn.json
> +  "item.farmersutils.dried_golden_apple_slice": "金风干苹果片",
```suggestion
  "item.farmersutils.dried_golden_apple_slice": "风干金苹果片",
```
语序

2024-02-14 04:41 UTC, ChuijkYahus commented on projects/1.19/assets/farmers-utils/farmersutils/lang/zh_cn.json
> +  "block.farmersutils.sugar_cane_bale": "甘蔗捆",
```suggestion
  "block.farmersutils.sugar_cane_bale": "甘蔗块",
```
`捆`这一称呼适用于1.19.3及以上版本

2024-02-14 04:41 UTC, ChuijkYahus commented on projects/1.19/assets/farmers-utils/farmersutils/lang/zh_cn.json
> +  "block.farmersutils.propelplant_cane_bale": "枪药杆捆",
```suggestion
  "block.farmersutils.propelplant_cane_bale": "枪药杆块",
```
下方启用xx统一修改

2024-02-14 04:41 UTC, ChuijkYahus commented on projects/1.19/assets/farmers-utils/farmersutils/lang/ja_jp.json
> +{
如作者母语或模组主语言不是日语，则请注意删除本文件

2024-02-14 11:43 UTC, luoxueyasha commented on projects/1.19/assets/farmers-utils/farmersutils/lang/ja_jp.json
> +{
作者母语是日语，没啥问题

2024-02-18 01:33 UTC, luoxueyasha approved these changes
我觉得没问题了

2024-02-19 07:29 UTC, merged