Cracker's Wither Storm Mod 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4173
Opened 2024-02-14 03:06 UTC by CharamitasSaMa

由 CFPA-Helper 提交。

2024-02-14 03:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=4173) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=4173) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=4173) it.</sub>

2024-02-20 01:16 UTC, CharamitasSaMa commented
😇

2024-03-04 12:45 UTC, FridayAnubis requested changes
先修改/统一下术语

2024-03-04 12:45 UTC, FridayAnubis commented on projects/1.20/assets/crackers-wither-storm-mod/witherstormmod/lang/zh_cn.json
> +	"witherstormmod.jei.super_beacon.requiresFullBeacon": "需要主信标为最大等级IV",
“需要完整的四级信标”是否更准确

2024-03-04 14:35 UTC, CharamitasSaMa commented on projects/1.20/assets/crackers-wither-storm-mod/witherstormmod/lang/zh_cn.json
> +	"item.witherstormmod.command_block_book": "指令附魔书",
这些包括后面的都是没动的疑似官译

2024-03-04 14:37 UTC, CharamitasSaMa commented on projects/1.20/assets/crackers-wither-storm-mod/witherstormmod/lang/zh_cn.json
> +	"block.witherstormmod.tainted_zombie_sitting": "坐着的腐化僵尸",
确实

2024-03-04 14:39 UTC, CharamitasSaMa commented on projects/1.20/assets/crackers-wither-storm-mod/witherstormmod/lang/zh_cn.json
> +	"witherstormmod.jei.super_beacon.requiresFullBeacon": "需要主信标为最大等级IV",
这个条件只需要主信标为最大等级，可简化为需要满级的主信标，但不能简化为需要完整的四级信标，因为本模组的完整信标视为四个支援信标均激活

2024-03-04 15:56 UTC, FridayAnubis requested changes

2024-03-04 15:56 UTC, FridayAnubis commented on projects/1.20/assets/crackers-wither-storm-mod/witherstormmod/lang/zh_cn.json
> +	"block.witherstormmod.potted_tainted_mushroom": "凋零菇盆栽",
这里还是错译，建议全文通查下

2024-03-04 15:56 UTC, FridayAnubis commented on projects/1.20/assets/crackers-wither-storm-mod/witherstormmod/lang/zh_cn.json
> +	"commands.witherstormmod.chunks.error": "风暴区块追踪器无法被检测",
这里直译为“风暴区块追踪器不存在”，是不是这样或者翻译成“检测不到……”比较通畅

2024-03-04 15:56 UTC, FridayAnubis commented on projects/1.20/assets/crackers-wither-storm-mod/witherstormmod/lang/zh_cn.json
> +	"gui.witherstormmod.screen.playingDeadOptions.title": "世界选项 > 死亡逻辑",
这里“Play dead”直译为装死，需要确认下实际游戏内容是否与之相关，确认翻译没问题可以不改
同时第324行又将本词译为“死亡动画”，矛盾点请确认下。

2024-03-04 15:56 UTC, FridayAnubis commented on projects/1.20/assets/crackers-wither-storm-mod/witherstormmod/lang/zh_cn.json
> +	"gui.witherstormmod.button.debrisOptions.title": "残骸云选项",
“云”这一含义从何而来？原文看不出来，若为模组内特性可以不修改，后文同理

2024-03-04 15:56 UTC, FridayAnubis commented on projects/1.20/assets/crackers-wither-storm-mod/witherstormmod/lang/zh_cn.json
> +	"gui.witherstormmod.config.blockClustersDropItems.title": "集群方块掉落物",
此处原文有歧义，可能意为 集群方块 会掉落物品，请核对实际模组内容所指。

2024-03-04 15:56 UTC, FridayAnubis commented on projects/1.20/assets/crackers-wither-storm-mod/witherstormmod/lang/zh_cn.json
> +	"gui.witherstormmod.config.playerPickupChance.title": "玩家选择概率",
“被选择的概率”更符合原文

2024-03-04 15:56 UTC, FridayAnubis commented on projects/1.20/assets/crackers-wither-storm-mod/witherstormmod/lang/zh_cn.json
> +	"gui.witherstormmod.config.shouldDropFromInventory.title": "从物品栏中掉出",
这一大部分看起来是配置文件选项一类的东西。翻译这些内容时应当注意判断性语气，例如此处译为“是否从物品栏掉出”或“能够从物品栏掉出”才符合配置文件的描述规范（配置项为true or false），最好把此类翻译都修改为判断语气，请全文通查。

2024-03-04 15:56 UTC, FridayAnubis commented on projects/1.20/assets/crackers-wither-storm-mod/witherstormmod/lang/zh_cn.json
> +	"gui.witherstormmod.config.distantFog.title": "渲染远距离雾",
此处为计算机图形学专有名词“距离模糊”。配置文件中此类专有名词尤其多，最好是按照正确名词来翻译。

2024-03-05 02:57 UTC, CharamitasSaMa commented on projects/1.20/assets/crackers-wither-storm-mod/witherstormmod/lang/zh_cn.json
> +	"gui.witherstormmod.button.debrisOptions.title": "残骸云选项",
确实为模组内特性

2024-03-05 03:23 UTC, FridayAnubis approved these changes

2024-03-05 03:31 UTC, FridayAnubis approved these changes

2024-03-05 09:19 UTC, ChuijkYahus approved these changes

2024-03-07 04:21 UTC, merged