1.19 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4178
Opened 2024-02-17 09:50 UTC by wwjdmm

2024-02-19 08:26 UTC, ChuijkYahus commented
/sort-keys projects/1.19/assets/egg-delight/eggdelight/lang/zh_cn.json
/sort-keys projects/1.19/assets/egg-delight/eggdelight/lang/en_us.json

2024-02-19 09:11 UTC, ChuijkYahus requested changes

2024-02-19 09:11 UTC, ChuijkYahus commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.fish_taco": "鱼炸玉米饼",
```suggestion
  "item.suchadelight.fish_taco": "鱼肉炸玉米饼",
```

2024-02-19 09:11 UTC, ChuijkYahus commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.fried_chicken_dinner_plate": "炸鸡餐盘",
这个物品是怎样获得的
```suggestion
  "item.suchadelight.fried_chicken_dinner_plate": "盘装炸鸡晚餐",
```

2024-02-19 09:11 UTC, ChuijkYahus commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.gyros": "陀螺",
这个的合成表是什么样的

2024-02-19 09:11 UTC, ChuijkYahus commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.moussaka": "穆萨卡",
```suggestion
  "item.suchadelight.moussaka": "茄子千层饼",
```
```suggestion
  "item.suchadelight.moussaka": "希腊茄子千层面",
```

2024-02-19 09:11 UTC, ChuijkYahus commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.muffuletta": "穆富莱塔",
这个……找中文名有点难顶了（）

2024-02-19 09:11 UTC, ChuijkYahus commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.pina_colada": "凤梨可乐达",
```suggestion
  "item.suchadelight.pina_colada": "椰林飘香",
```
建议

2024-02-19 09:11 UTC, ChuijkYahus commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.pizza_tower_take": "披萨塔服务",
serving指“一份”
这个在游戏中是怎样获得的
```suggestion
  "item.suchadelight.pizza_tower_take": "单份披萨塔",
```

2024-02-19 09:11 UTC, ChuijkYahus commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.salmon_en_croute_plate": "三文鱼皮面团",
```suggestion
  "item.suchadelight.salmon_en_croute_plate": "盘装鲑鱼烤面包",
```
这个在游戏中是怎么获得的

2024-02-19 09:11 UTC, ChuijkYahus commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.salsa": "酱",
```suggestion
  "item.suchadelight.salsa": "莎莎酱",
```

2024-02-19 09:11 UTC, ChuijkYahus commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.snickerdoodle": "士力架涂鸦",
```suggestion
  "item.suchadelight.snickerdoodle": "肉桂饼",
```

2024-02-19 09:11 UTC, ChuijkYahus commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.sloppy_joe": "肉夹馍",
```suggestion
  "item.suchadelight.sloppy_joe": "邋遢乔三明治",
```

2024-02-19 09:11 UTC, ChuijkYahus commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.upside_down_cake_slice": "颠倒蛋糕片",
```suggestion
  "item.suchadelight.upside_down_cake_slice": "颠倒蛋糕切片",
```

2024-02-19 09:11 UTC, ChuijkYahus commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.egg_substitute": "鸡蛋替代品"
这个是怎么合成的

2024-02-19 09:11 UTC, ChuijkYahus commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "block.suchadelight.salmon_en_croute": "鲑鱼三明治",
```suggestion
  "block.suchadelight.salmon_en_croute": "鲑鱼烤面包",
```

2024-02-19 09:11 UTC, ChuijkYahus commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.pineapple_curry_rice_serving": "菠萝咖喱饭",
```suggestion
  "item.suchadelight.pineapple_curry_rice_serving": "单份菠萝咖喱饭",
```

2024-02-20 00:59 UTC, 502y requested changes
大文件在网页review好卡

2024-02-20 00:59 UTC, 502y commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.chili": "辣椒",
```suggestion
  "item.suchadelight.chili": "辣椒酱",
```
游戏内是酱

2024-02-20 00:59 UTC, 502y commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.chocolate_bark": "巧克力树皮",
> 建议

确实是脆片

2024-02-20 00:59 UTC, 502y commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.elotes": "Elotes",
> 合成表和材质是怎么样的

奶酪、蛋黄酱、玉米、辣椒，奶酪烤玉米挺好的

2024-02-20 00:59 UTC, 502y commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.fajitas": "法吉塔斯",
```suggestion
  "item.suchadelight.fajitas": "墨西哥烤肉卷",
```
墨西哥烤肉来源维基百科，卷是因为游戏内确实是个卷，长得挺像老北京鸡肉卷（

2024-02-20 00:59 UTC, 502y commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.gyros": "陀螺",
```suggestion
  "item.suchadelight.gyros": "希腊烤肉卷",
```

2024-02-20 00:59 UTC, 502y commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.muffuletta": "穆富莱塔",
有个叫法是意大利三明治

2024-02-20 01:02 UTC, 502y commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.pizza_tower_take": "披萨塔服务",
> serving指“一份” 这个在游戏中是怎样获得的

三张披萨+铁栅栏+其他，确实是塔

2024-02-22 08:31 UTC, wwjdmm commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.egg_substitute": "鸡蛋替代品"
**
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/30591475/d90d5578-e21c-4536-9ec4-f524733f4d7e)
是这样合成的**

2024-02-22 08:34 UTC, wwjdmm commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "advancements.crop_quaternion.description": "种植 多是一件乐事 的所有农作物",
多是一件乐事这个是MOD名，要保留英文原文还是怎么说，感觉直接套用上有歧义

2024-02-22 10:14 UTC, wwjdmm commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.fried_chicken_dinner_plate": "炸鸡餐盘",
用碗右键装一个“Fried Chicken Dinner”的东西装出来，感觉挺合适的

2024-02-22 10:14 UTC, wwjdmm commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "block.suchadelight.cinnamon_sack": "肉桂捆",
```suggestion
  "block.suchadelight.cinnamon_sack": "袋装肉桂棒",
```

2024-02-22 10:16 UTC, wwjdmm commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "block.suchadelight.olive_cask": "箱装橄榄",
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/30591475/76825c8e-c17b-4b21-8a71-8db2c23cfd1f)
这样

2024-02-22 10:17 UTC, wwjdmm commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "block.suchadelight.mystic_fruit_cask_gold": "箱装金色神秘果实",
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/30591475/a03627b0-a53c-4e8a-a4cd-9b6bf57bcbaa)
差不多都这样

2024-02-22 10:20 UTC, wwjdmm commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.muffuletta": "穆富莱塔",
```suggestion
  "item.suchadelight.muffuletta": "意大利三明治",
```

2024-02-22 12:32 UTC, ChuijkYahus commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "block.suchadelight.cinnamon_sack": "肉桂捆",
蛮好的，直接改就行（）

2024-02-22 12:32 UTC, ChuijkYahus commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "item.suchadelight.muffuletta": "穆富莱塔",
就这个吧（）

2024-02-22 12:32 UTC, ChuijkYahus commented on projects/1.19/assets/such-a-delight/suchadelight/lang/zh_cn.json
> +  "block.suchadelight.olive_cask": "箱装橄榄",
要不改成`桶装xx`？

2024-02-22 12:42 UTC, ChuijkYahus commented on projects/1.19/assets/enders-delight/endersdelight/lang/zh_cn.json
> +  "endersdelight.block.stuffed_shulker.use_shulker_bowl": "你需要一个碗才能吃这个",
```suggestion
  "endersdelight.block.stuffed_shulker.use_shulker_bowl": "你需要一个碗以食用它",
```
农夫乐事用语

2024-02-22 12:42 UTC, ChuijkYahus commented on projects/1.19/assets/enders-delight/endersdelight/lang/zh_cn.json
> +  "block.endersdelight.endstone_stove": "末地石炉",
```suggestion
  "block.endersdelight.endstone_stove": "末地石炉灶",
```
类似下界乐事的译法

2024-02-22 12:42 UTC, ChuijkYahus commented on projects/1.19/assets/enders-delight/endersdelight/lang/zh_cn.json
> +  "item.endersdelight.chorus_stew_wood": "紫颂炖菜",
```suggestion
  "item.endersdelight.chorus_stew": "紫颂煲",
  "item.endersdelight.chorus_stew_wood": "紫颂煲",
```
```suggestion
  "item.endersdelight.chorus_stew": "紫颂炖",
  "item.endersdelight.chorus_stew_wood": "紫颂炖",
```
上方为原版译法，下方为农夫乐事译法，推荐原版

2024-02-22 12:42 UTC, ChuijkYahus commented on projects/1.19/assets/enders-delight/endersdelight/lang/zh_cn.json
> +  "item.endersdelight.endermite_stew_wood": "末影炖肉",
```suggestion
  "item.endersdelight.endermite_stew": "末影螨煲",
  "item.endersdelight.endermite_stew_wood": "末影螨煲",
```
```suggestion
  "item.endersdelight.endermite_stew": "末影螨炖",
  "item.endersdelight.endermite_stew_wood": "末影螨炖",
```
上方为原版译法，下方为农夫乐事译法，推荐原版
endermite为原版术语

2024-02-22 12:42 UTC, ChuijkYahus commented on projects/1.19/assets/enders-delight/endersdelight/lang/zh_cn.json
> +  "item.endersdelight.pearl_pasta_wood": "珍珠面",
```suggestion
  "item.endersdelight.pearl_pasta": "珍珠意面",
  "item.endersdelight.pearl_pasta_wood": "珍珠意面",
```
pasta还是译成意面，农夫乐事译法

2024-02-22 12:42 UTC, ChuijkYahus commented on projects/1.19/assets/enders-delight/endersdelight/lang/zh_cn.json
> +  "item.endersdelight.twisted_cereal_wood": "扭曲麦片",
```suggestion
  "item.endersdelight.twisted_cereal": "扭曲麦片粥",
  "item.endersdelight.twisted_cereal_wood": "扭曲麦片粥",
```
建议

2024-02-22 12:42 UTC, ChuijkYahus commented on projects/1.19/assets/enders-delight/endersdelight/lang/zh_cn.json
> +  "item.endersdelight.stuffed_shulker_bowl": "一碗潜影贝馅",
```suggestion
  "item.endersdelight.stuffed_shulker_bowl": "碗装填馅潜影贝",
```
农夫乐事译法
这种方块形态放下来再用餐具取的，一般都是`碗装+原菜名` `盘装+原菜名`

2024-02-22 12:42 UTC, ChuijkYahus commented on projects/1.19/assets/enders-delight/endersdelight/lang/zh_cn.json
> +  "item.endersdelight.strange_eclair": "奇怪的油酥饼",
```suggestion
  "item.endersdelight.strange_eclair": "奇异手指泡芙",
```
手指泡芙是从广坦那里看来的叫法（）
法式点心，形如手指，馅有巧克力等
也叫闪电泡芙，算是法语éclair的直译，来源应该是“像闪电一样给吃完了”（也是从广坦那里看的）

2024-02-22 12:42 UTC, ChuijkYahus commented on projects/1.19/assets/enders-delight/endersdelight/lang/zh_cn.json
> +  "item.endersdelight.uncanny_cookies": "奇特饼干",
```suggestion
  "item.endersdelight.uncanny_cookies": "奇特曲奇",
```
虽然和原版的曲奇不太一样吧（）
uncanny一般有令人不适的意味，可以考虑换一个词，仅建议

2024-03-12 04:54 UTC, ChuijkYahus reviewed
EggDelight的文件需要更新吗
其他应该没什么问题了

2024-03-16 02:40 UTC, ChuijkYahus reviewed
是否还要更新EggDelight，没有近期就合并了

@wwjdmm

2024-07-22 01:39 UTC, ChuijkYahus reviewed
才发现有地方没有统一

2024-07-22 01:39 UTC, ChuijkYahus commented on projects/1.19/assets/cozy-foods-milk-tea/cozyfoods/lang/zh_cn.json
> +    "block.cozyfoods.mango_cabinet": "芒果木柜子",
```suggestion
    "block.cozyfoods.mango_cabinet": "芒果木厨柜",
```

2024-12-28 05:26 UTC, luoxueyasha commented
不对啊 @ChuijkYahus 
EndersDelight的官译不是你吗

2024-12-28 07:49 UTC, ChuijkYahus commented
> 不对啊 @ChuijkYahus EndersDelight的官译不是你吗 就是作者好像不接新语言pr了 干脆把官译搬过来再resolve？

是这样的，但是实在翻不动了，投过一次后没再维护
这个PR里的EndersDelight部分是直接先不管，我这边投个PR吗

2024-12-28 17:40 UTC, luoxueyasha commented
> 这个PR里的EndersDelight部分是直接先不管，我这边投个PR吗

搬过来之后这个pr的EndersDelight就因为重复所以关掉吧……

2024-12-28 17:55 UTC, ChuijkYahus commented
那我新投一个PR吗，这边就删掉？

2024-12-29 01:36 UTC, luoxueyasha commented
> 那我新投一个PR吗，这边就删掉？

对，删掉这边的endersdelight，你单开一个分支，这样就不用resolve conflict了

2024-12-29 11:49 UTC, ChuijkYahus commented
投了，这边直接删吧

2024-12-30 00:01 UTC, luoxueyasha approved these changes

2024-12-30 08:51 UTC, ChuijkYahus approved these changes

2024-12-31 11:15 UTC, merged