寄生虫翻译更新和补齐
CFPAOrg/Minecraft-Mod-Language-Package pull request #4203
Opened 2024-02-26 14:38 UTC by krzj

2024-02-26 14:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=4203) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=4203) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CFPAOrg/Minecraft-Mod-Language-Package?pullRequest=4203) it.</sub>

2024-02-26 14:44 UTC, krzj commented
SRParasites-1.12.2v1.9.18.jar/update-en scape-and-run-parasites 1.12.2

2024-02-26 14:54 UTC, krzj commented
/update-en scape-and-run-parasites 1.12.2

2024-02-27 02:08 UTC, TUsama commented
就算官库无人维护，这个PR也不可能入库。先是整体参杂个人发挥过多，令人摸不着头脑；其次是改动太多可有可无之处，此等改动最多允许在跨版本更新时做出，平常更新不允许这种改动，综上所述close。

2024-02-27 03:09 UTC, luoxueyasha commented
@TUsama 咱还是对first-time contributor友善一些

2024-02-27 03:10 UTC, krzj commented
> 就算官库无人维护，这个PR也不可能入库。先是整体参杂个人发挥过多，令人摸不着头脑；其次是改动太多可有可无之处，此等改动最多允许在跨版本更新时做出，平常更新不允许这种改动，综上所述close。

这不是更新了许多新东西吗？就添加了一些个人的东西

2024-02-27 03:13 UTC, krzj commented
> 就算官库无人维护，这个PR也不可能入库。先是整体参杂个人发挥过多，令人摸不着头脑；其次是改动太多可有可无之处，此等改动最多允许在跨版本更新时做出，平常更新不允许这种改动，综上所述close。

可以加个QQ聊下吗

2024-02-27 03:14 UTC, luoxueyasha requested changes

2024-02-27 03:14 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites/srparasites/lang/zh_cn.lang
> +entity.srparasites.sim_dragone.name=寄染巅峰——瘟疫之龙
这行是怎么翻出来的？我没看见原文有这条

2024-02-27 03:14 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites/srparasites/lang/zh_cn.lang
> +entity.srparasites.anc_dreadnaut.name=空中霸主——上古惧魔
同上

2024-02-27 03:14 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites/srparasites/lang/zh_cn.lang
> +tile.srparasites.infestedbush_grass1.name=寄染草须
可以解释一下为什么这么改吗
我记得原译文译为草脉是有原因的

2024-02-27 03:14 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites/srparasites/lang/zh_cn.lang
> +tile.srparasites.evolutionlure_one.name=诱饵（§4孱弱§f）
原则情况下应遵从原文，不加入非必要的格式代码
此类问题请全文通查

2024-02-27 03:31 UTC, krzj commented on projects/1.12.2/assets/scape-and-run-parasites/srparasites/lang/zh_cn.lang
> +entity.srparasites.sim_dragone.name=寄染巅峰——瘟疫之龙
更新下英文文件，我从游戏文件里下的

2024-02-27 13:42 UTC, luoxueyasha commented on projects/1.12.2/assets/scape-and-run-parasites/srparasites/lang/zh_cn.lang
> +entity.srparasites.sim_dragone.name=寄染巅峰——瘟疫之龙
原文`Assimilated Ender Dragon`

2024-03-06 07:27 UTC, luoxueyasha commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

@krzj

2024-03-14 08:08 UTC, closed without merging