提交五个模组语言文件与翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #4211
Opened 2024-02-29 03:22 UTC by CLcongut

2024-03-01 16:38 UTC, QiuShui1012 commented
兄啊，你CC:C Bridge的配置部分怎么没翻译啊（）

2024-03-16 02:10 UTC, ChuijkYahus commented
/sort-keys projects/1.20-fabric/assets/cccbridge/cccbridge/lang/en_us.json

2024-03-16 02:35 UTC, ChuijkYahus requested changes

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/cccbridge/cccbridge/lang/zh_cn.json
> +    "block.cccbridge.source_block":"来源方块",
```suggestion
    "block.cccbridge.source_block":"源方块",
```
库内1182版本
也可此处不改，更改1182的文件

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/cccbridge/cccbridge/lang/zh_cn.json
> +    "block.cccbridge.scroller_block":"滚轮方块",
```suggestion
    "block.cccbridge.scroller_block":"滚轮面板",
```
库内1182版本

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/cccbridge/cccbridge/lang/zh_cn.json
> +    "itemGroup.cccbridge.cccbridge_group":"Peripherals (CC:C Bridge)",
```suggestion
    "itemGroup.cccbridge.cccbridge_group":"外设（CC:C Bridge）",
```

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/cccbridge/cccbridge/lang/zh_cn.json
> +    "subtitles.cccbridge.cage_unlock":"滚轮解锁",
```suggestion
    "subtitles.cccbridge.cage_lock":"滚轮面板：锁定",
    "subtitles.cccbridge.cage_unlock":"滚轮面板：解锁",
```
库内1182版本，且请注意原版字幕格式

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/cccbridge/cccbridge/lang/zh_cn.json
> +    "cccbridge.general.unit.scroller":"Lua Number",
```suggestion
    "cccbridge.general.unit.scroller":"Lua数",
```

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/cccbridge/cccbridge/lang/zh_cn.json
> +    "cccbridge.tooltip.holdForDescription":"§8按住 [{0}Shift§8] 以获得更多细节",
```suggestion
    "cccbridge.tooltip.holdForDescription":"§8按住[{0}Shift§8]以获得更多细节",
```

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/cccbridge/cccbridge/lang/zh_cn.json
> +    "block.cccbridge.animatronic_block.description":"§6它的面部表情乃至整个身体都能够通过一台§e计算机§r§6来改变和定位\n\n§7当推送时\n §6将§o旋转§r§6参数缓冲用于§e动画制作假人§r",
这里的推送/Pushing是指什么操作

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/cccbridge/cccbridge/lang/zh_cn.json
> +    "block.cccbridge.scroller_block.description":"§6提供一个可以选择数字的接口\n§6能被一台§e计算机§r§6用于读取，控制和操作",
```suggestion
    "block.cccbridge.scroller_block.description":"§6提供一个可以选择数字的接口\n§6可被§e计算机§r§6读取，控制和操作",
```

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/cccbridge/cccbridge/lang/zh_cn.json
> +    "advancements.cccbridge.placed_animatronic.title":"Minecraft内五个夜晚",
```suggestion
    "advancements.cccbridge.placed_animatronic.title":"Minecraft的五夜惊魂",
```
FNAF

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/cccbridge/cccbridge/lang/zh_cn.json
> +    "cccbridge.general.unit.scroller.negative":"Lua Num. -",
```suggestion
    "cccbridge.general.unit.scroller.positive":"Lua数增加",
    "cccbridge.general.unit.scroller.negative":"Lua数减小",
```
这个在游戏内具体是怎么显示的

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/create-diesel-generators-fabric/createdieselgenerators/lang/zh_cn.json
> +  "createdieselgenerators.ponder.basin_fermenting_station.text_2": "向工作盆内投入一些糖与适量骨粉...",
```suggestion
  "createdieselgenerators.ponder.basin_fermenting_station.text_2": "向工作盆内投入一些糖与适量骨粉……",
```
注意使用中文省略号

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/create-diesel-generators-fabric/createdieselgenerators/lang/zh_cn.json
> +  "createdieselgenerators.ponder.diesel_engine.header": "设定一台柴油机",
```suggestion
  "createdieselgenerators.ponder.diesel_engine.header": "配置柴油机",
```
参照create原版中类似结构语句翻译

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/create-diesel-generators-fabric/createdieselgenerators/lang/zh_cn.json
> +  "createdieselgenerators.ponder.diesel_engine.text_1": "使用柴油机是一种紧凑的产生动能方法",
```suggestion
  "createdieselgenerators.ponder.diesel_engine.text_1": "柴油机是一种紧凑的动能产生机器",
```

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/create-diesel-generators-fabric/createdieselgenerators/lang/zh_cn.json
> +  "createdieselgenerators.ponder.diesel_engine.text_2": "给予柴油机一写燃料，它就能够产生动能",
```suggestion
  "createdieselgenerators.ponder.diesel_engine.text_2": "给予柴油机一些燃料，它就能够产生动能",
```

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/create-diesel-generators-fabric/createdieselgenerators/lang/zh_cn.json
> +  "createdieselgenerators.ponder.basin_fermenting_station.text_1": "利用工作盆盖可使你生产乙醇",
```suggestion
  "createdieselgenerators.ponder.basin_fermenting_station.text_1": "工作盆盖可用于生产乙醇",
```
微调

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/create-diesel-generators-fabric/createdieselgenerators/lang/zh_cn.json
> +  "createdieselgenerators.ponder.basin_fermenting_station.text_3": "...乙醇就可被生产出来",
```suggestion
  "createdieselgenerators.ponder.basin_fermenting_station.text_3": "...就可生产乙醇",
```

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/expanding-technologies/expandingtechnologies/lang/zh_cn.json
> +	"expandingtechnologies.ponder.railroad_lights_example.text_2": "将二者用一个转换锁存器连接以此来使用红石信号激活控制器",
```suggestion
	"expandingtechnologies.ponder.railroad_lights_example.text_2": "用无线红石信号终端将二者连接至激活的转换锁存器，即可激活控制器",
```
参照原文

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/create-jetpack/create_jetpack/lang/zh_cn.json
> +  "block.create_jetpack.netherite_jetpack": "下界合金喷漆背包",
```suggestion
  "block.create_jetpack.netherite_jetpack": "下界合金喷气背包",
```

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/create-jetpack/create_jetpack/lang/zh_cn.json
> +  "item.create_jetpack.netherite_jetpack": "下界合金喷漆背包",
```suggestion
  "item.create_jetpack.netherite_jetpack": "下界合金喷气背包",
```

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/expanding-technologies/expandingtechnologies/lang/zh_cn.json
> +	"subtitles.block.railroad_light_controller.crossing_bell": "铁路道口钟声",
```suggestion
	"subtitles.block.railroad_light_controller.crossing_bell": "铁路道口钟：鸣响",
```

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/expanding-technologies/expandingtechnologies/lang/zh_cn.json
> +	"expandingtechnologies.ponder.railroad_lights_instruction.text_4": "如果你在其上方放置一个音符盒，一段荷兰铁路钟声就会随着控制器被打开而响起",
这里的Dutch Railroad Bell有特殊指代吗
```suggestion
	"expandingtechnologies.ponder.railroad_lights_instruction.text_4": "在其上方放置音符盒，控制器打开时就会响起一段荷兰铁路钟声",
```

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/create-diesel-generators-fabric/createdieselgenerators/lang/zh_cn.json
> +  "createdieselgenerators.ponder.large_diesel_engine.text_2": "一旦你提供给它们些许燃料，它们就会产生动能...",
```suggestion
  "createdieselgenerators.ponder.large_diesel_engine.text_2": "为其提供些许燃料，它们就会产生动能……",
```

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/create-diesel-generators-fabric/createdieselgenerators/lang/zh_cn.json
> +  "createdieselgenerators.ponder.large_diesel_engine.text_3": "...他们能够首尾相连",
```suggestion
  "createdieselgenerators.ponder.large_diesel_engine.text_3": "……它们能够首尾相连",
```

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/create-diesel-generators-fabric/createdieselgenerators/lang/zh_cn.json
> +  "createdieselgenerators.ponder.large_diesel_engine.text_4": "它们会产生与你连接的数量成比例的应力",
```suggestion
  "createdieselgenerators.ponder.large_diesel_engine.text_4": "它们产生的应力与你连接的数量成比例",
```
微调

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/create-diesel-generators-fabric/createdieselgenerators/lang/zh_cn.json
> +  "createdieselgenerators.ponder.engine_silencer.text_2": "一旦你放下一台引擎消音器，柴油机将不会产生任何噪音",
```suggestion
  "createdieselgenerators.ponder.engine_silencer.text_2": "放下引擎消音器后，柴油机将不会产生任何噪音",
```

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/toms-peripherals/toms_peripherals/lang/zh_cn.json
> +	"item.toms_peripherals.gpu_chip_raw": "原始GPU芯片",
```suggestion
	"item.toms_peripherals.gpu_chip_raw": "待加工的GPU芯片",
```

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/toms-peripherals/toms_peripherals/lang/zh_cn.json
> +	"label.toms_peripherals.wdt.timeLimit": "超时: %s",
```suggestion
	"label.toms_peripherals.wdt.timeLimit": "超时：%s",
```
全角标点

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/toms-peripherals/toms_peripherals/lang/zh_cn.json
> +	"label.toms_peripherals.keyboard.ccmon": "左键点击来激活显示器",
```suggestion
	"label.toms_peripherals.keyboard.ccmon": "左击激活显示器",
```

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/toms-peripherals/toms_peripherals/lang/zh_cn.json
> +	"tooltip.toms_peripherals.portable_keyboard.info": "潜行+右键来绑定一个无线键盘接收器",
```suggestion
	"tooltip.toms_peripherals.portable_keyboard.info": "潜行+右击来绑定一个无线键盘接收器",
```

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/toms-peripherals/toms_peripherals/lang/zh_cn.json
> +	"tooltip.toms_peripherals.monitor": "GPU必须紧贴显示器的底部左侧箭头指向远离这个方块的方向",
```suggestion
	"tooltip.toms_peripherals.monitor": "GPU必须紧贴显示器的左侧底部，箭头会指离方块",
```
微调

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/toms-peripherals/toms_peripherals/lang/zh_cn.json
> +	"tooltip.toms_peripherals.gpu": "驱动显示器并且能执行图像操作功能函数列表请参考wiki",
```suggestion
	"tooltip.toms_peripherals.gpu": "驱动显示器并且能执行图像操作功能，函数列表请参考wiki",
```

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/toms-peripherals/toms_peripherals/lang/zh_cn.json
> +	"tooltip.toms_peripherals.wdt": "如果运行的程序因某种原因崩溃或者超时，则重新启动连接的计算机更多信息请参考wiki",
```suggestion
	"tooltip.toms_peripherals.wdt": "如果运行的程序因某种原因崩溃或者超时，则重新启动连接的计算机，更多信息请参考wiki",
```
这些键是不是漏标点了

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/toms-peripherals/toms_peripherals/lang/zh_cn.json
> +	"tooltip.toms_peripherals.redstone_port": "将更多红石信号控制面提供给计算机",
```suggestion
	"tooltip.toms_peripherals.redstone_port": "为计算机提供更多红石信号控制面",
```

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/toms-peripherals/toms_peripherals/lang/zh_cn.json
> +	"label.toms_peripherals.wdt.timer": "自重启以来的时间: %s",
```suggestion
	"label.toms_peripherals.wdt.timer": "自重启以来的时间：%s",
```

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/create-diesel-generators-fabric/createdieselgenerators/lang/zh_cn.json
> +  "createdieselgenerators.ponder.basin_fermenting_station.header": "设定一个工作盆发酵器",
```suggestion
  "createdieselgenerators.ponder.basin_fermenting_station.header": "配置工作盆发酵器",
```

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/create-diesel-generators-fabric/createdieselgenerators/lang/zh_cn.json
> +  "createdieselgenerators.ponder.large_diesel_engine.header": "设定一台模块化柴油机",
```suggestion
  "createdieselgenerators.ponder.large_diesel_engine.header": "配置模块化柴油机",
```

2024-03-16 02:35 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/create-diesel-generators-fabric/createdieselgenerators/lang/zh_cn.json
> +  "createdieselgenerators.ponder.engine_silencer.header": "设定一台引擎消音器",
```suggestion
  "createdieselgenerators.ponder.engine_silencer.header": "配置引擎消音器",
```

2024-03-31 09:12 UTC, luoxueyasha commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。
@CLcongut

2024-05-10 03:16 UTC, closed without merging