Create Deco 1.20.1翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4217
Opened 2024-03-05 13:27 UTC by SGK2401

## 对1.20.1的Create Deco汉化
- 尽量保持了原版风格
- 描述方块外观(颜色) 及制作材料特点, 而非直译方块名称
- 对部分可能带有歧义的翻译做了微妙的改动, 如 '淡蓝色黄铜灯笼' -> '淡蓝色黄铜**笼灯**'

2024-03-05 14:14 UTC, SGK2401 commented
/update-en create-deco 1.20

2024-03-07 04:21 UTC, 502y requested changes

2024-03-07 04:21 UTC, 502y commented on projects/1.20/assets/create-deco/createdeco/lang/zh_cn.json
> +    "block.createdeco.long_umber_brick_slab": "条状棕 砖台阶",
```suggestion
    "block.createdeco.long_umber_brick_slab": "条状棕砖台阶",
```

上面没空格，这几个有，统一一下？

2024-03-07 04:21 UTC, 502y commented on projects/1.20/assets/create-deco/createdeco/lang/zh_cn.json
> +    "block.createdeco.long_umber_brick_stairs": "条状棕 砖楼梯",
```suggestion
    "block.createdeco.long_umber_brick_stairs": "条状棕砖楼梯",
```

2024-03-07 04:21 UTC, 502y commented on projects/1.20/assets/create-deco/createdeco/lang/zh_cn.json
> +    "block.createdeco.long_verdant_brick_stairs": "条状绿 砖楼梯",
```suggestion
    "block.createdeco.long_verdant_brick_slab": "条状绿砖台阶",
    "block.createdeco.long_verdant_brick_stairs": "条状绿砖楼梯",
```

2024-03-07 18:00 UTC, SGK2401 commented on projects/1.20/assets/create-deco/createdeco/lang/zh_cn.json
> +    "block.createdeco.long_verdant_brick_stairs": "条状绿 砖楼梯",
我的问题, 检查的时候大意了...
已修正

2024-03-16 09:16 UTC, Cyl18 commented
chatgpt审核：

安山岩相关条目中“安山”应改为“安山岩”。
蓝色砖块相关条目中，“蓝砖”应改为“蓝色砖块”。
黄砖块相关条目中，“黄砖”应改为“黄色砖块”，“Dean Brick”可能是特定类型的砖块名称，需确认原文意图。
“栏板”、“网栏”等术语应统一为“栏杆”和“栅栏”。
箭头装饰中的“箭头”翻译不一致，应统一为“箭头装饰”或“方向键”。
“锁上的”翻译应统一为“上锁的”或“已锁定的”。
“密集”、“条状”、“网格”前的砖块颜色和类型翻译需确认是否准确，如“密集蓝砖”应为“密集蓝色砖块”。
“覆苔”砖块翻译应保持一致性，确认是否指“生苔的”或特定类型砖块。

2024-03-17 16:46 UTC, SGK2401 commented
不这么做的主要原因是 '安山' 特指机械动力中的 '安山合金' 制造的物品, 相当于前缀. 一开始确实打算用安山岩, 但是考虑到一致性以及原材料, 就决定还是 '安山' 了.

2024-03-17 16:47 UTC, SGK2401 commented
另, 这真的不是机翻... 哪家机翻翻译得这么整洁啊喂!

2024-03-19 11:37 UTC, Cyl18 commented
> Author

机翻是我点错了 抱歉

2024-03-19 11:44 UTC, Cyl18 submitted a review, later dismissed
我不知道 #4206 要怎么处理 @Cactusstudent @ChuijkYahus 
其它没有问题了
另外还有fabric版本

2024-03-19 11:52 UTC, Cactusstudent commented
> 我不知道 #4206 要怎么处理 @Cactusstudent @ChuijkYahus 其它没有问题了 另外还有fabric版本

一般合并翻译覆盖面积广的且质量高的并打上另一PR作者的协作，但是两个PR同时审核。

2024-03-19 18:18 UTC, SGK2401 commented
> 我不知道 #4206 要怎么处理 @Cactusstudent @ChuijkYahus 其它没有问题了 另外还有fabric版本

我再搞一下Fabric版本的? 还是怎么说.

2024-03-31 10:15 UTC, QiuShui1012 commented
> > 我不知道 #4206 要怎么处理 @Cactusstudent @ChuijkYahus 其它没有问题了 另外还有fabric版本
> 
> 我再搞一下Fabric版本的? 还是怎么说.

你加油搞Fabric的吧，我close #4206 了

2024-04-01 12:46 UTC, SlimeSB submitted a review, later dismissed
修改后同意合并

2024-04-01 12:46 UTC, SlimeSB commented on projects/1.20/assets/create-deco/createdeco/lang/zh_cn.json
> +    "block.createdeco.brass_support": "黄铜支撑",
所有“支撑”译作“支架”
支撑是动词吧，工程上也有做名词的，比如钢支撑，但是是一根独立且粗壮的柱子。
不论如何，译作支架更好。

2024-04-03 04:37 UTC, SGK2401 commented on projects/1.20/assets/create-deco/createdeco/lang/zh_cn.json
> +    "block.createdeco.brass_support": "黄铜支撑",
游戏内这个方块可以各种方向放置所以就没有翻译为支架了, 因为把贴着墙和地板的物件叫做支架总感觉不对. 毕竟支架通常来说指架起上方的物体的支撑件, 大概.

2024-04-03 08:58 UTC, SlimeSB commented on projects/1.20/assets/create-deco/createdeco/lang/zh_cn.json
> +    "block.createdeco.brass_support": "黄铜支撑",
倒也不只局限于抵抗重力的，这里如鞋架一类的分层；抵抗侧向力的也有很多，比如血管支架……。
再一个例子就是大型的塔吊，塔臂和塔身也被叫做支架或者桁架，尤其是桁架与物品贴图最为贴切，这里为了避其他的讳也可以译作支架。

而“支撑”则较少将其用于对抗侧向力？总之放置的方向问题不能够说服我认同“支撑”一词

2024-04-05 02:46 UTC, ChuijkYahus commented on projects/1.20/assets/create-deco/createdeco/lang/zh_cn.json
> +    "block.createdeco.decal_down_right": "右下图案装饰",
```suggestion
    "block.createdeco.decal_down_right": "右下箭头图案装饰",
```
统一格式

2024-04-05 02:46 UTC, ChuijkYahus commented on projects/1.20/assets/create-deco/createdeco/lang/zh_cn.json
> +    "block.createdeco.red_zinc_lamp": "红锌笼灯",
```suggestion
    "block.createdeco.red_industrial_iron_lamp": "红色工业铁笼灯",
    "block.createdeco.red_iron_lamp": "红色铁笼灯",
    "block.createdeco.red_placard": "红色置物牌",
    "block.createdeco.red_shipping_container": "红色集装箱",
    "block.createdeco.red_zinc_lamp": "红色锌笼灯",
```
统一格式

2024-04-21 14:19 UTC, SlimeSB commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。
@SGK2401

2024-04-28 03:15 UTC, SlimeSB approved these changes

2024-04-28 03:22 UTC, SlimeSB approved these changes
合并前请看一下争议更改

2024-04-28 04:14 UTC, luoxueyasha commented
我觉得如果create原文是这些且两边相关的话，就没啥争议

2024-05-02 15:01 UTC, merged