Gadgets Against Grind模组翻译修正及润色
CFPAOrg/Minecraft-Mod-Language-Package pull request #4238
Opened 2024-03-13 14:03 UTC by Maton-py

2024-03-13 14:49 UTC, Cactusstudent requested changes
问题蛮大的，译后翻译的效果较差，请根据原文全文通查翻译的术语问题

2024-03-13 14:49 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "item.gag.time_sand": "时之砂",
沙与砂请注意辨析（没看原文）

2024-03-13 14:49 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "item.gag.time_sand_pouch": "时之袋",
连同L7，请解释时间->时的原因

2024-03-13 14:49 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "item.gag.hearthstone.warmup": "将在%s秒后进行传送...",
```suggestion
  "item.gag.hearthstone.warmup": "将在%s秒后进行传送……",
```
统一使用六个点的中文省略号

2024-03-13 14:49 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "item.gag.hearthstone.target.respawn": "您的重生点",
您->你，不需要敬语，之后的译后翻译也请注意

2024-03-13 14:49 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "item.gag.pigment_jar.info.filled.1": "在标签工具中使用，用来改变物品名称的颜色",
标签工具？

2024-03-13 14:49 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "block.gag.no_solicitors": "'闲人免进！' 告示牌",
```suggestion
  "block.gag.no_solicitors": "“闲人免进！”告示牌",
```

2024-03-13 14:49 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "subtitles.gag.item.repelling.apply": "正在驱散"
subtitle翻译格式不正确，应为`主体：动作`

2024-03-16 15:12 UTC, Cyl18 approved these changes
ai告诉我没有问题了

2024-03-16 15:48 UTC, Cactusstudent requested changes
@Cyl18 那看来AI就是在胡诌，和人类译者/审核相比那简直是比不了

2024-03-16 15:48 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "item.gag.time_sand_pouch": "时间之袋",
```suggestion
  "item.gag.time_sand_pouch": "时间之袋",
```

2024-03-16 15:48 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "item.gag.time_sand_pouch.info.1": "放在玩家的背包中累积时间",
```suggestion
  "item.gag.time_sand_pouch.info.1": "放在玩家的物品栏中累积时间",
```

2024-03-16 15:48 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "item.gag.hearthstone.no_target": "无法找到可以传送的地方，你设置了重生点吗？",
```suggestion
  "item.gag.hearthstone.no_target": "找不到可以传送的地点，你是否已设置重生点？",
```
原意更好，我建议回退

2024-03-16 15:48 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "item.gag.hearthstone.too_weak": "这块炉石看起来太弱了，不足将这里设置为家",
原文：**It seems this hearthstone is too weak to call home from this place.**

2024-03-16 15:48 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "item.gag.hearthstone.info": "将玩家传送到其重生点，否则传送到世界出生点。",
原文：**Teleports a player to their personal spawn point, or, if enabled, the world spawn.**

2024-03-16 15:48 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "item.gag.hearthstone.info_adv_2": "现在它可以用来传送到任意的绑定地点！(潜行时右击绑定）",
```suggestion
  "item.gag.hearthstone.info_adv_2": "现在它可以用来传送到任意的绑定地点！（潜行时右击绑定）",

```

2024-03-16 15:48 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "item.gag.hearthstone.info_adv_3": "注意，如果要重置绑定位置，你需要使闪电再次击中它",
```suggestion
  "item.gag.hearthstone.info_adv_3": "注意，如果要重新绑定，你需要让闪电再次击中它。",
```

2024-03-16 15:48 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "item.gag.pigment_jar.contents": "剩余%s次颜色代码为%s的染料",
原文：**Contains %s charges of %s**

2024-03-16 15:48 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "item.gag.pigment_jar.contents.empty": "空空如也",
请解释原因？空单字我认为表现的已经十分恰当了

2024-03-16 15:48 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "item.gag.pigment_jar.info.empty.2": "提示：用燧石磨碎一些染料，然后加入牛奶（将这些与染料罐合成）",
```suggestion
  "item.gag.pigment_jar.info.empty.2": "提示：用燧石研磨染料，然后加入奶。",
```

2024-03-16 15:48 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "item.gag.pigment_jar.info.filled.1": "在标签工具中使用，用于改变物品名称的颜色",
原文：**Can be used in a labeling tool to change the color of the item's name.**

2024-03-16 15:48 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "item.gag.pigment_jar.info.filled.2": "提示：与其他染料罐合成以混合颜色",
```suggestion
  "item.gag.pigment_jar.info.filled.2": "提示：与其他染料罐混合以调配颜色。",
```

2024-03-16 15:48 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "block.gag.no_solicitors.silent": "静音模式%s",
```suggestion
  "block.gag.no_solicitors.silent": "静音模式：%s",
```

2024-03-16 15:48 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "item.gag.sacred_salve.extra": "比神圣之盐的效果更持久，且适用范围更大",
```suggestion
  "item.gag.sacred_salve.extra": "比神圣之盐的效果更持久，且作用范围更大",
```

2024-03-16 15:48 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "commands.gag.give_time.no_pouch": "%s的背包中没有时间之袋！",
```suggestion
  "commands.gag.give_time.no_pouch": "%s的物品栏中没有时间之袋！",
```

2024-03-16 15:48 UTC, Cactusstudent commented on projects/1.20/assets/gag/gag/lang/zh_cn.json
> +  "item.gag.fishing_dynamite.info": "只能在水中使用的可投掷爆炸物，增加对鱼造成的伤害。如果你不喜欢钓鱼，那就再好不过了！",
原文：**Throwable explosive that only works underwater and deals increased damage to fish. Perfect if you don't like fishing!**

2024-03-16 15:58 UTC, zeeeeeeeeeero commented
毁灭吧，赶紧的

2024-03-16 15:58 UTC, closed without merging