0-modrinth-mod A Cold Day In The Nether 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4253
Opened 2024-03-16 14:56 UTC by zeeeeeeeeeero

2024-03-17 02:48 UTC, Cyl18 commented
/sort-keys projects/1.20/assets/0-modrinth-mod/a-cold-day-in-the-nether/lang/zh_cn.json

2024-03-17 04:15 UTC, ChuijkYahus commented
/sort-keys projects/1.20/assets/0-modrinth-mod/a-cold-day-in-the-nether/lang/en_us.json

2024-03-17 04:19 UTC, ChuijkYahus requested changes

2024-03-17 04:19 UTC, ChuijkYahus commented on projects/1.20/assets/0-modrinth-mod/a-cold-day-in-the-nether/lang/zh_cn.json
> +  "biome.acd_nether.aspen_forests": "白杨树森林",
```suggestion
  "biome.acd_nether.aspen_forests": "白杨森林",
```

2024-03-17 04:19 UTC, ChuijkYahus commented on projects/1.20/assets/0-modrinth-mod/a-cold-day-in-the-nether/lang/zh_cn.json
> +  "block.acd_nether.aspen_planks": "白杨木木板",
```suggestion
  "block.acd_nether.aspen_log": "白杨原木",
  "block.acd_nether.aspen_planks": "白杨木板",
```

2024-03-17 04:19 UTC, ChuijkYahus commented on projects/1.20/assets/0-modrinth-mod/a-cold-day-in-the-nether/lang/zh_cn.json
> +  "block.acd_nether.aspen_slab": "白杨木半砖",
```suggestion
  "block.acd_nether.aspen_slab": "白杨木台阶",
```

2024-03-17 04:19 UTC, ChuijkYahus commented on projects/1.20/assets/0-modrinth-mod/a-cold-day-in-the-nether/lang/zh_cn.json
> +  "block.acd_nether.everfreeze_log": "永冻木原木",
```suggestion
  "block.acd_nether.everfreeze_log": "永冻原木",
```

2024-03-17 04:19 UTC, ChuijkYahus commented on projects/1.20/assets/0-modrinth-mod/a-cold-day-in-the-nether/lang/zh_cn.json
> +  "block.acd_nether.everfreeze_slab": "永冻木半砖",
```suggestion
  "block.acd_nether.everfreeze_slab": "永冻木台阶",
```

2024-03-17 04:19 UTC, ChuijkYahus commented on projects/1.20/assets/0-modrinth-mod/a-cold-day-in-the-nether/lang/zh_cn.json
> +  "block.acd_nether.prismatic_pad": "棱冰平台",
这个在游戏内是什么样的

2024-03-17 04:19 UTC, ChuijkYahus commented on projects/1.20/assets/0-modrinth-mod/a-cold-day-in-the-nether/lang/zh_cn.json
> +  "block.acd_nether.stripped_everfreeze_log": "去皮永冻木原木",
```suggestion
  "block.acd_nether.stripped_aspen_log": "去皮白杨原木",
  "block.acd_nether.stripped_aspen_wood": "去皮白杨木",
  "block.acd_nether.stripped_everfreeze_log": "去皮永冻原木",
```

2024-03-17 04:19 UTC, ChuijkYahus commented on projects/1.20/assets/0-modrinth-mod/a-cold-day-in-the-nether/lang/zh_cn.json
> +  "item.acd_nether.flame_twin_blade": "烈焰双锋",
这个在游戏内是什么样的

2024-03-17 11:24 UTC, zeeeeeeeeeero commented on projects/1.20/assets/0-modrinth-mod/a-cold-day-in-the-nether/lang/zh_cn.json
> +  "item.acd_nether.flame_twin_blade": "烈焰双锋",
和烈焰人一个配色

2024-03-17 11:35 UTC, zeeeeeeeeeero commented on projects/1.20/assets/0-modrinth-mod/a-cold-day-in-the-nether/lang/zh_cn.json
> +  "block.acd_nether.prismatic_pad": "棱冰平台",
是冰的样子，但名字里有prismatic

2024-03-17 11:36 UTC, zeeeeeeeeeero commented on projects/1.20/assets/0-modrinth-mod/a-cold-day-in-the-nether/lang/zh_cn.json
> +  "block.acd_nether.prismatic_pad": "棱冰平台",
和蓝冰类似

2024-03-17 17:27 UTC, ChuijkYahus approved these changes

2024-03-18 07:26 UTC, ChuijkYahus requested changes
这应该是把之前修过的部分重新改回去了
记得修改

2024-03-20 16:05 UTC, ChuijkYahus approved these changes

2024-03-31 08:37 UTC, merged