提交Akisephila's Bosses翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #4259
Opened 2024-03-18 08:39 UTC by RedVanguard1692

https://www.curseforge.com/minecraft/mc-mods/akisephilas-bosses
基于游戏版本1.16.5，mod版本1.10翻译。此Mod作者已永久停更。

这个是我2021年的存货了，当时是出于要跟朋友们一起玩才翻的。不过现在早就各奔东西了……
mod本身就不正经，而且有大量非标准用词，所以我基本没做什么细致考证和二次查验。
比起躺在硬盘里那天数据损坏，还是发上来比较好，至少汉化是做完了。

2024-04-13 14:15 UTC, luoxueyasha commented
/sort-keys projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/en_us.json

2024-04-13 14:15 UTC, luoxueyasha commented
/sort-keys projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json

2024-04-13 14:18 UTC, luoxueyasha commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.akisephilas_bosses.title": "Akisephilaの奇妙生物",
| **审查级别**   |
|:-:|
| 🔴 严重 / **阻止合并，刻不容缓** |

**原文: Akisephila's Bosses**

```suggestion
  "advancements.akisephilas_bosses.title": "Akisephila's Bosses",
```

2024-04-13 14:18 UTC, luoxueyasha commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.akisephilas_bosses.title": "Akisephilaの奇妙生物",
| **审查级别**   |
|:-:|
| 🔴 严重 / **阻止合并，刻不容缓** |

**原文: Akisephila's Bosses**

```suggestion
  "advancements.akisephilas_bosses.title": "Akisephila's Bosses",
```

2024-04-13 14:19 UTC, luoxueyasha commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.adorn_me_in_purple.descr": "装备一整套康明“石”护甲",
| **审查级别**    |
|:-:|
| ❓疑问 / 需要作者确认 |

**原文: Wear a full set of Culminite Armor**

```suggestion
  "advancements.adorn_me_in_purple.descr": "装备一整套康明“石”护甲",
```

2024-04-13 14:20 UTC, luoxueyasha commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.chlorophyll.descr": "打败一个被命名为 Cloronog 或 Bob 的贝奥兰迪",
| **审查级别** |
|:-:|
| 🔵 一般 / **阻止合并** |

**原文: Defeat a Biollante that has been nametagged either "Cloronog" or "Bob"**

```suggestion
  "advancements.chlorophyll.descr": "打败一个被命名为“Cloronog”或“Bob”的贝奥兰迪",
```

2024-04-13 14:22 UTC, luoxueyasha commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.chlorophyll.title": "葉 綠 素",
| **审查级别**    |
|:-:|
| ❓疑问 / 需要作者确认 |

**原文: Chlorophyll**

2024-04-13 14:24 UTC, luoxueyasha commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.veganism_unchallenged.descr": "连续500个游戏日不往物品栏里塞任何动物制品和肉类，你这段时间吃了多少个烤土豆啊。。",
| **审查级别**   |
|:-:|
| 🔴 严重 / **阻止合并，刻不容缓** |

**原文: Avoid having animal products in your inventory or eating meat for 500 days**

```suggestion
  "advancements.veganism_unchallenged.descr": "在连续500个游戏日内，物品栏中不含有且不食用动物制品",
```

2024-04-13 15:41 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.adorn_me_in_purple.descr": "装备一整套康明“石”护甲",
大概率是不标准的音译，译名更换为DeepL提供的“烛石”

2024-04-13 15:41 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.akisephilas_bosses.title": "Akisephilaの奇妙生物",
Roger that

2024-04-13 15:41 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.chlorophyll.title": "葉 綠 素",
等会，有这个样子的？已修正

2024-04-13 15:42 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.veganism_unchallenged.descr": "连续500个游戏日不往物品栏里塞任何动物制品和肉类，你这段时间吃了多少个烤土豆啊。。",
已修，不过原作者已失联且原帖未提供关于此成就的任何资料，触发条件尚不明确……

2024-04-13 15:58 UTC, RedVanguard1692 commented
另外在成套盔甲中会有部分装备前后译名不一致，这是因为英文原文便是如此内容，不做修正

2024-04-14 06:24 UTC, luoxueyasha commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.adorn_me_in_purple.descr": "装备一整套康明“石”护甲",
所以可以解释一下这类矿石在游戏中是怎么获取的吗？
机翻不一定准确

2024-04-15 10:20 UTC, luoxueyasha approved these changes

2024-04-15 10:20 UTC, luoxueyasha commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.transmodium_rights.title": "谷氨酸钠之力",
没懂，和味精哪里有关系了

2024-04-15 10:20 UTC, luoxueyasha commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.culminite_block": "潜影合金块",
再次询问译者对于`culminite`的理解，这是一种什么材料、如何获得、什么材质？为何前后取了这些译名，又是为何修改？
需要译者在这条conversation里回复相关内容

2024-04-15 10:20 UTC, luoxueyasha requested changes
尴尬，点成approve了

2024-04-26 11:49 UTC, luoxueyasha commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

@RedVanguard1692

2024-05-06 09:04 UTC, luoxueyasha commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.culminite_block": "潜影合金块",
我看不见你这条conversation的回复，请确认你的回复是否在pending状态。（可以通过退出github登录来确认）
在pending状态下的回复可以通过网页端右上角的finish review按钮来公开

2024-05-10 11:41 UTC, RedVanguard1692 commented
草，我直到今天才发现原来从提交pull request到现在有四个回复都没显示出来，全在pending状态。之前几乎没有使用github的经验导致的

2024-05-10 11:49 UTC, SlimeSB commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.culminite_block": "潜影合金块",
culminite 可能是 culminate 的变形。可考虑译作终结合金、终点合金

2024-05-10 12:20 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.culminite_block": "潜影合金块",
> culminite 可能是 culminate 的变形。可考虑译作终结合金、终点合金

这个思路很不错啊，这块也是我之前没有考虑过的方向
不过以“终结”、“终点”的字面意义来说，有可能会引起玩家对材料定位的误解（这个材料在本模组中有上位替代品）

我对物品主语暂时持保留意见，不过考虑修改成就译名以体现“收束”、“终点”这层释义

2024-05-10 13:36 UTC, SlimeSB reviewed
未完成

2024-05-10 13:36 UTC, SlimeSB commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.adorn_me_in_purple.title": "终局战士",
画蛇添足

2024-05-10 13:36 UTC, SlimeSB commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.scaley_power.title": "恐惧之力",
Scaley 有鳞的
鳞片、鳞甲之力

2024-05-10 13:36 UTC, SlimeSB commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.transmodium_rights.title": "眩光之力",
transmodium 可能由 plasmodium 演绎而来
plasma 塑造物（富有“塑造”这一特质） plasmodium -odium = like 所以是变形体、疟原虫
transm(?) 可能表传输、跨越、变换等意
以此我倾向译作富变、变形、**传变**（这个可能最准确）丨金属、合金、体

2024-05-10 14:20 UTC, luoxueyasha commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.transmodium_rights.title": "眩光之力",
这里翻cf页面就知道了，trans-这里是跨性别/变性

2024-05-10 14:21 UTC, luoxueyasha commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.culminite_block": "潜影合金块",
github评论可以传图的

2024-05-10 14:25 UTC, SlimeSB commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.transmodium_rights.title": "眩光之力",
草了，虽然我还是想隐晦的译作“转变”。因为我是激进的保守主义者

2024-05-10 14:25 UTC, luoxueyasha commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.culminite_block": "潜影合金块",
看cf页面的图片，我倾向于culminate的变体
是一种能在“终末”之地找到的矿物

2024-05-10 14:27 UTC, luoxueyasha commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.transmodium_rights.title": "谷氨酸钠之力",
蓝白粉，外加作者停更的原因，我倾向于是“transgender”相关

2024-05-10 14:52 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.scaley_power.title": "恐惧之力",
OK,已采纳

2024-05-10 15:07 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "item.akisephilas_bosses.tubifex_boots": "遗传物质靴子",
这套装备来自于红怪（boss），和《红怪》游戏的内容有关，我倾向于保留这个翻译（

2024-05-10 15:13 UTC, SlimeSB commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "item.akisephilas_bosses.tubifex_boots": "遗传物质靴子",
无需修改

2024-05-10 15:30 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.adorn_me_in_purple.title": "终局战士",
已退回到第一版翻译

2024-05-10 15:40 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.represium_block": "重塑合金块",
以实际功能来说应该更贴近于重现吧，这种东西相当于盔甲的“骨架”
把一个represium制作的盔甲部件放在锻造台中，加上一个对应的材料，就能“变换”成对应的盔甲

重现这译名听起来好一些，已修改

2024-05-10 16:23 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.transmodium_rights.title": "眩光之力",
我去……这某种意义上算真正的争议内容了，我没仔细阅览cf页面导致完全漏掉了这点，确实令人头疼
对这种内容我倾向于在翻译逻辑优先级中暂时绕过作者和原文

这个东西其实没有很复杂的性质，定位和用途都跟前述的`culminite`系列差不多
区别在于`culminite`依靠采集矿物烧制获取，而`transmodium`属于人造物品，不用烧就能用
![捕获](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/51277234/02c88c8f-b75b-4b77-b25a-5806243ddc44)
![捕获](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/51277234/5df4d993-dfc8-45ea-9716-aa14bddec122)
`传变合金`应是个合适的正式译名

（另外`潜影合金`也得一道换掉，超平坦查证之后`culminite`这东西是跟铁锭金锭一道的性质，并不是合金）

2024-05-10 16:24 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.transmodium_rights.title": "眩光之力",
![捕获](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/51277234/295b21e5-29c7-4aff-8c4c-5c548e5435ef)

2024-05-10 17:07 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.represium_block": "重塑合金块",
等等，我顺道测试了下，其实不是这么作用的

`represium`这东西只能依靠钓鱼获取，它能且只能在原版与这个mod提供的护甲上作用
`represium护甲`并非通过传统方式合成获得，而是“更改”护甲材质的半成品，于锻造台合成后能完整保留原护甲的NBT数据（猜测）
![捕获](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/51277234/4d458458-d069-41fb-996d-052df1514068)


这种半成品虽然能穿，但是不提供任何盔甲值和护甲韧性，使用其与对应材料合成会转换成相应的形态
![捕获](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/51277234/87ea26bf-6347-4801-a760-588b3d69b9dd)


而且过程完全可逆
![捕获](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/51277234/d6bf919f-bab6-4f58-b56e-cc6dcf0183a2)


！：综上所述我认为初版翻译`重塑金属`最为准确

2024-05-10 17:13 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.transmodium_compound": "§d变幻钔复合体",
`transmodium_compound` → `传变化合物`

2024-05-10 17:31 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.orchestra_door": "紫颂门",
呃…………其实是这作者的问题，这个系列并不是一种新的树木
这东西其实就是原版紫颂果子/精准采集砍下来的紫颂花造出来的

![捕获](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/51277234/f0d8df2b-0bc9-4d0d-8951-08dae35adc46)


而且实际有的`Orchestra`物品也只有下面这些
![捕获](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/51277234/f0197344-403b-44dd-8607-a3a52794664c)


鉴于停更导致作者的真实意图无从查验，我持一个保留意见（

2024-05-11 01:01 UTC, SlimeSB commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.orchestra_door": "紫颂门",
叫管弦乐队而非合唱有作者自己的考量。无论如何务必尽量贴近原文。译作奏鸣木版，奏鸣木门之类即可

2024-05-11 01:01 UTC, SlimeSB commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.represium_block": "重塑合金块",
同意

2024-05-11 01:05 UTC, SlimeSB commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.transmodium_compound": "§d变幻钔复合体",
好的，但转变化合物吧。虽然我反对跨性别但仍捍卫准确性。

2024-05-12 10:04 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.culminite_block": "潜影合金块",
我有个想法是把`止境`作为主语，例如`止境镐`、`止境锭`这样
要是感觉不太行就用`终点`了

2024-05-12 10:04 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.orchestra_door": "紫颂门",
got it，已修改

2024-05-12 10:09 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.transmodium_rights.title": "眩光之力",
改好了，主语全换了`转变`

2024-05-12 10:09 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.orchestra_door": "紫颂门",
got it，已修正

2024-05-12 10:13 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.adorn_me_in_purple.title": "终局战士",
我对`adorn_me_in_purple`的翻译是`浓妆紫染`，如果准确性不够我就直译`用紫色装点我`了

2024-05-12 10:16 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.transmodium_compound": "§d变幻钔复合体",
OK

2024-05-12 10:17 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.culminite_block": "潜影合金块",
> 看cf页面的图片，我倾向于culminate的变体 是一种能在“终末”之地找到的矿物

我有个想法是把`止境`作为culminite系列的主语，例如`止境镐`、`止境锭`这样
要是感觉不太行就用`终点`了

2024-05-12 10:22 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.transmodium_rights.title": "谷氨酸钠之力",
嗯哼，我把它统一成了上下文的`转变之力`

2024-05-12 11:54 UTC, SlimeSB commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "advancements.adorn_me_in_purple.title": "终局战士",
无需。
今日休，仅回复不讨论。

2024-05-13 08:52 UTC, SlimeSB commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.xp_ore": "经验矿石",
```suggestion
  "block.akisephilas_bosses.xp_ore": "精华矿石",
```
Essence

2024-05-13 08:52 UTC, SlimeSB commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "entity.akisephilas_bosses.decoy_biollante": "畸变苦力怕诱饵",
我希望得到更多信息。对于一种生物译作“诱饵”听起来不太好。
兽如其名就算了

2024-05-13 08:54 UTC, SlimeSB commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.culminite_ore": "止境矿石",
然后单开一层楼聊聊culminite

2024-05-13 08:57 UTC, SlimeSB commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.culminite_ore": "止境矿石",
前情提要：culminite ~可能~就是 culminate 的变形。

我对止境一词还是不满意，巅峰与高潮，山的最高峰，虽然极其隐晦的表达了“到此为止”的意味，但不能说culminate = 止境，因为已经有 end, limit 一类词语指代

2024-05-13 15:08 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "entity.akisephilas_bosses.decoy_biollante": "畸变苦力怕诱饵",
> Biollante is the second post-enderdragon boss in 
this mod. It can be summoned by killing a Decoy Biollante, which will 
spawn in the Creeper Woods biome and Jungle biomes after the Queen Bee 
has been defeated. 

> 在打爆末影龙和女王蜂之后，`Decoy Biollante`将会在苦力怕森林与热带雨林中刷出。如果其以任意方式被击杀，将会在原位召唤一只畸变苦力怕
![捕获](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/51277234/df45c3c5-308d-431c-a120-cba2db4268fb)
左一的绿色四脚生物即为`Decoy Biollante`



经实测它的AI为中立生物，不会主动攻击，被打了也会反击
直译成诱饵确实有失偏颇，改成`畸变苦力怕幼体`怎么样？

2024-05-13 15:09 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.xp_ore": "经验矿石",
got it，下次修正时一并更改

2024-05-13 15:16 UTC, SlimeSB commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "entity.akisephilas_bosses.decoy_biollante": "畸变苦力怕诱饵",
不再要求更改，感谢你的补充。这样是恰当的。

2024-05-13 15:38 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.culminite_ore": "止境矿石",
其实`止境`是在准确性和应用性之间经过大量权衡之后的想法
先略过最早的两个翻译，`潜影合金`其实是这么来的
> “Culminite is a new ore that generates in the End dimension, and can be used to upgrade Netherite. When a full set is worn, the player will be immune to Poison, and can hover above the void (But don't go jumping in all willy-nilly)”

> 穿戴全套`Culminite`盔甲可以免疫中毒，并会在Y值处于0及以下时提供漂浮II的buff
以它的外形和上述提到的功能来说，感觉与潜影贝比较相似，我考虑采用`潜影合金`一词


我还考虑过`天顶`、`极点`、`端点`一类的称呼，但是都觉得跟`终结`、`终点`的问题类似，很难体现出它相关联的功能性

不过我同意以CFPA的方针为先，如果在词义精准性这一点上完全不能妥协的话，可以不作异议地敲定成`culminate`的一个变体词汇
（终结、终点……嗯，还有什么来着？）

2024-05-15 15:43 UTC, SlimeSB commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.culminite_ore": "止境矿石",
是的，如果不是极其难寻找词源词根的生造词，都务必贴合原意。

我之后又查看了相关例句，可以作为“以某种方式告结”使用。在此提出与“末地”有关的译名：`终末`。我认为可以同时兼顾最高和最终的意思。

最后补充一点，我的身份就是服务员而已，服务于译者和译文，力求无错。

2024-05-16 02:58 UTC, luoxueyasha commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.culminite_ore": "止境矿石",
我放一个`结末`在这作为备选
~~杀戮尖塔玩多了~~

2024-05-16 12:21 UTC, RedVanguard1692 commented on projects/1.16/assets/akisephilas-bosses/akisephilas_bosses/lang/zh_cn.json
> +  "block.akisephilas_bosses.culminite_ore": "止境矿石",
了解，`Culminite`现在的最终翻译就敲定成`终末`了

~结末其实也不错，不过我主观上更喜欢终末一些~

2024-05-16 12:59 UTC, SlimeSB submitted a review, later dismissed

2024-05-17 08:07 UTC, SlimeSB approved these changes

2024-05-19 06:48 UTC, merged