Redstone Repository Revolved 汉化更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #4264
Opened 2024-03-23 13:26 UTC by RuiXuqi

2.0版本更新了很多key，故提交
同时修缮了很多原来的问题
向下兼容1.0版本，所以可能对比出来多了几个key
（这么久了还没人搞这个是我没想到的）

2024-03-23 14:25 UTC, Cyl18 commented
/diff

2024-04-06 14:32 UTC, SlimeSB requested changes

2024-04-06 14:32 UTC, SlimeSB commented on projects/1.12.2/assets/redstone-repository-revolved/redstonerepository/lang/zh_cn.lang
> +info.redstonerepository.tooltip.damage.flux=+%d 充能伤害
通量伤害→充能伤害 请补充修改理由

2024-04-06 14:32 UTC, SlimeSB commented on projects/1.12.2/assets/redstone-repository-revolved/redstonerepository/lang/zh_cn.lang
> +info.redstonerepository.tooltip.active=目前%s启用%s。按下（%s）键禁用。
这里是什么占位符，只是颜色吗？

2024-04-06 14:32 UTC, SlimeSB commented on projects/1.12.2/assets/redstone-repository-revolved/redstonerepository/lang/zh_cn.lang
> +info.redstonerepository.tooltip.empower=按下（%s）键充能
这里是增加或减少攻击伤害的方式吗？
可译作赋能与抑制。
如果是打开和关闭也不要译作充能，因为在这里被滥用了，译作启动、唤醒即可

2024-04-06 14:32 UTC, SlimeSB commented on projects/1.12.2/assets/redstone-repository-revolved/redstonerepository/lang/zh_cn.lang
> +info.redstonerepository.feeder.title=启用时可提供饥饿值恢复，必须装备在饰品栏以生效。
```suggestion
info.redstonerepository.feeder.title=启用时自动补充饥饿值与饱食度，必须装备在饰品栏才能生效。

```

2024-04-06 14:32 UTC, SlimeSB commented on projects/1.12.2/assets/redstone-repository-revolved/redstonerepository/lang/zh_cn.lang
> +info.redstonerepository.tooltip.clearskies=物品充能时，潜行时右击以绑定到物品栏。
这几行在英文中没有找到，请更新英文语言文件

2024-04-06 14:32 UTC, SlimeSB commented on projects/1.12.2/assets/redstone-repository-revolved/redstonerepository/lang/zh_cn.lang
> +gui.redstonerepository.food.1=HP/个物品：
```suggestion
gui.redstonerepository.food.1=单物品HP：

```

2024-04-06 14:32 UTC, SlimeSB commented on projects/1.12.2/assets/redstone-repository-revolved/redstonerepository/lang/zh_cn.lang
> +info.redstonerepository.tooltip.peruse=%d RF/次使用
```suggestion
info.redstonerepository.tooltip.peruse=每次使用消耗 %d RF

```
下同，异议请提出。

2024-04-06 14:32 UTC, SlimeSB commented on projects/1.12.2/assets/redstone-repository-revolved/redstonerepository/lang/zh_cn.lang
> +info.redstonerepository.tooltip.perdamage=%d RF/次伤害
可能是每点的意思，具体进游戏看。

2024-04-13 12:08 UTC, SlimeSB commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。
@RuiXuqi

2024-04-13 13:39 UTC, RuiXuqi commented on projects/1.12.2/assets/redstone-repository-revolved/redstonerepository/lang/zh_cn.lang
> +info.redstonerepository.tooltip.peruse=%d RF/次使用
无异议，但因为这行是从Redstone Arsenal(RSA)里取的，它也需同步更改

2024-04-13 13:39 UTC, RuiXuqi commented on projects/1.12.2/assets/redstone-repository-revolved/redstonerepository/lang/zh_cn.lang
> +info.redstonerepository.tooltip.empower=按下（%s）键充能
支持，但RSA也需同步

2024-04-21 07:43 UTC, SlimeSB commented on projects/1.12.2/assets/redstone-repository-revolved/redstonerepository/lang/zh_cn.lang
> +info.redstonerepository.tooltip.peruse=%d RF/次使用
因先前的编码形式，无需更改

2024-04-21 07:44 UTC, SlimeSB commented on projects/1.12.2/assets/redstone-repository-revolved/redstonerepository/lang/zh_cn.lang
> +info.redstonerepository.tooltip.empower=按下（%s）键充能
所以是这个意思吗

2024-07-05 14:52 UTC, SlimeSB approved these changes

2024-07-05 23:26 UTC, luoxueyasha commented on projects/1.12.2/assets/redstone-repository-revolved/redstonerepository/lang/zh_cn.lang
> +gui.redstonerepository.food.1=单物品HP：
```suggestion
gui.redstonerepository.food.1=单物品 HP：
```

在1.12版本下，当遇到英文字母、阿拉伯数字等非中文文本时，应在该段文本开头与结尾处加空格与中文文本分开。
非中文文本与标点符号之间无需添加空格。
具体可见我们的 [翻译规范](https://cfpa.site/TransRules/) 中 **04.排版** 一节下 **1.12.2 及以下版本特有规则** 一处。
诸如这类的问题请在您翻译的所有文件中全部查明并修改。

如果影响了gui显示的话可以不改

2024-07-05 23:26 UTC, luoxueyasha commented on projects/1.12.2/assets/redstone-repository-revolved/redstonerepository/lang/zh_cn.lang
> +info.redstonerepository.ring.mining.title=在空中挖掘速度不减慢。
```suggestion
info.redstonerepository.ring.mining.title=在空中不减慢挖掘速度。
```
可不改，一个状语后置的小事

2024-07-05 23:26 UTC, luoxueyasha commented on projects/1.12.2/assets/redstone-repository-revolved/redstonerepository/lang/zh_cn.lang
> +item.redstonerepository.material.ingotGelidEnderium.name=极寒末影锭
确定enderium定为末影了吗
有没有其他的联动

2024-07-05 23:26 UTC, luoxueyasha commented on projects/1.12.2/assets/redstone-repository-revolved/redstonerepository/lang/zh_cn.lang
> +item.redstonerepository.bauble.ring.mining.name=空中速掘指环
这玩意是祖宗之法了吗
按功能命名也行

2024-07-06 03:19 UTC, SlimeSB commented on projects/1.12.2/assets/redstone-repository-revolved/redstonerepository/lang/zh_cn.lang
> +info.redstonerepository.ring.mining.title=在空中挖掘速度不减慢。
这里不是状语而是谓语，无需修改

2024-07-06 23:40 UTC, SlimeSB approved these changes

2024-07-07 23:14 UTC, merged