文件路径更改 & Modrinth 路径支持
CFPAOrg/Minecraft-Mod-Language-Package pull request #4276
Opened 2024-03-30 11:53 UTC by Cactusstudent

2024-05-02 02:50 UTC, 502y requested changes
ubes-delight未添加modrinth-前缀

2024-05-02 02:58 UTC, SlimeSB commented on CONTRIBUTING.md
> +  - 把该模组的 `CurseForge 项目名称`或`命名空间`中的加入相应的 `modNameBlackList` 或 `domainBlackList`（二者取其一）。
改名了，这里要不要改

2024-05-02 03:08 UTC, Cactusstudent commented on CONTRIBUTING.md
> +  - 把该模组的 `CurseForge 项目名称`或`命名空间`中的加入相应的 `modNameBlackList` 或 `domainBlackList`（二者取其一）。
改！感谢勘误

2024-05-02 03:08 UTC, Cactusstudent commented
> ubes-delight未添加modrinth-前缀

CF上有该模组，所以不符合独占的要求

2024-05-02 03:17 UTC, 502y commented
> > ubes-delight未添加modrinth-前缀
> 
> CF上有该模组，所以不符合独占的要求

如果非独占模组，什么样的模组上传到默认目录，什么样的模组上传到modrinth文件夹呢？随意？

2024-05-02 03:22 UTC, Cactusstudent commented
非Modrinth独占模组应当全部上传至默认目录

2024-05-08 04:45 UTC, QiuShui1012 commented
Ube's Delight 在 Modrinth 路径下的汉化可以删掉了，我没给那边更新，覆盖了会出问题

2024-06-24 00:53 UTC, dovisutu reviewed
看看有没有新增的0-modrinth模组要移

2024-06-24 00:53 UTC, dovisutu commented on CONTRIBUTING.md
> +搁置规则是解决由于 PR 作者迟迟不出面响应审查要求而导致的 PR 积压问题。
宾语掉了

2024-06-24 00:53 UTC, dovisutu commented on CONTRIBUTING.md
> +- 不同版本的同一模组可通过[自定义文件检索策略](./Packer-Doc.md)同步翻译。
```suggestion
- 如果文件路径不包含语言标记 `zh_cn`，一般需要**修改全局或局域的 Packer 配置**，否则它们会被打包器排除，不会进入用户使用的资源包。
  - 如果这些文件放置在 `font` 或 `textures` 中，无需修改配置；默认已经对这两处进行了特殊处理。
- 不同版本的同一模组可通过[自定义文件检索策略](./Packer-Doc.md)同步翻译。
```
先这样吧，等我有时间再仔细改下

2024-07-04 07:33 UTC, dovisutu commented on CONTRIBUTING.md
> +搁置规则是解决由于 PR 作者迟迟不出面响应审查要求而导致的 PR 积压问题。
```suggestion
搁置规则用于解决由于 PR 作者迟迟不出面响应审查要求而导致的 PR 积压问题。
```

2024-07-04 07:37 UTC, dovisutu commented on CONTRIBUTING.md
> +- 不同版本的同一模组可通过[自定义文件检索策略](./Packer-Doc.md)同步翻译。
额，还是来点链接吧
```suggestion
- 如果文件路径不包含语言标记 `zh_cn`，一般需要**修改全局或局域的 Packer 配置**，否则它们会被打包器排除，不会进入用户使用的资源包。具体操作参见[文档](Packer-Doc.md#添加无语言标识的文件)。
  - 如果这些文件放置在 `font` 或 `textures` 中，无需修改配置；默认已经对这两处进行了特殊处理。
- 不同版本的同一模组可通过[自定义文件检索策略](./Packer-Doc.md#检索策略)同步翻译。
```

2024-07-04 07:37 UTC, dovisutu commented on CONTRIBUTING.md
> +若有不明白的地方，可[前往 QQ 群](https://jq.qq.com/?_wv=1027&k=5geO1T21)（630943368）
```suggestion
若有不明白的地方，可[前往 QQ 群](https://jq.qq.com/?_wv=1027&k=5geO1T21)（630943368）。
```
可以吗

2024-07-04 07:41 UTC, dovisutu commented on Packer-Doc.md
> +    **若 `type` 的值为 `composition`：** 从给定的*组合文件*，直接生成语言文件（或部分）。这些组合文件可能不会被自动排除；可以考虑使用*局域配置*处理。<!--示例：macaws-->
```suggestion
    **若 `type` 的值为 `composition`：** 从给定的*组合文件*，直接生成语言文件（或部分）。这些组合文件可能不会被自动排除；可以考虑使用*局域配置*处理。（[示例](projects/1.16/assets/macaws-bridges/mcwbridges/packer-policy.json)的第二条；[组合文件示例](projects/1.16/assets/macaws-bridges/mcwbridges/lang/zh_cn-composition.json)）
```

2024-07-29 09:18 UTC, dovisutu approved these changes
我觉得没多少问题了
主要还是看0-modrinth，可能得去未合并的pr里轰炸一下

2024-07-29 09:18 UTC, dovisutu commented on CONTRIBUTING.md
> +  - 修改`characterReplacement`，格式与已有文本一致。对于**基础多语种平面（BMP）**以外的字符，最好用 **UTF-16 代理对**书写
```suggestion
  - 修改`characterReplacement`，格式与已有文本一致。对于基础多语种平面（BMP）以外的字符，最好用 **UTF-16 代理对**书写。
```

2024-07-29 09:23 UTC, dovisutu approved these changes
我觉得没多少问题了
主要还是看0-modrinth，可能得去未合并的pr里轰炸一下

2024-08-02 01:58 UTC, SlimeSB commented on CONTRIBUTING.md
> +2. 若所有小版本都活跃更新，则Minecraft 版本高者优先。
```suggestion
2. 若所有小版本都活跃更新，则 Minecraft 版本高者优先。

```

2024-08-02 01:58 UTC, SlimeSB commented on CONTRIBUTING.md
> +2. 关于“木制品名称”的翻译，可参考[此处](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/2715#discussion_r1056901664>)的解决方法。
```suggestion
2. 关于“木制品名称”的翻译，可参考 #4525 的解决方法。

```

2024-08-03 11:10 UTC, SlimeSB reviewed
拟同意，要不要喊mamaruo看看

2024-08-03 11:10 UTC, SlimeSB approved these changes

2024-08-03 11:11 UTC, Cactusstudent commented
我现在在想，要不要把公示的部分先单拎出来，扔到另一个里面

2024-08-09 07:28 UTC, SlimeSB commented
他不看就合了

2024-08-12 06:13 UTC, mamaruo approved these changes

2024-08-12 07:53 UTC, merged