Dawn of Time 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4285
Opened 2024-04-03 07:16 UTC by ChuijkYahus

2024-04-08 13:25 UTC, SlimeSB requested changes

2024-04-08 13:25 UTC, SlimeSB commented on projects/1.20/assets/dawn-of-time/dawnoftimebuilder/lang/zh_cn.json
> +    "block.dawnoftimebuilder.fireplace": "篝火",
壁炉？篝火的话原版叫营火

2024-04-08 13:25 UTC, SlimeSB commented on projects/1.20/assets/dawn-of-time/dawnoftimebuilder/lang/zh_cn.json
> +    "block.dawnoftimebuilder.jungle_support_slab": "丛林木栈台",
竖板、条阶、栈台
如果之前在游戏里看过就忽略此评审。

2024-04-08 13:25 UTC, SlimeSB commented on projects/1.20/assets/dawn-of-time/dawnoftimebuilder/lang/zh_cn.json
> +    "block.dawnoftimebuilder.boxwood_bush": "黄杨灌木",
丛？

2024-04-08 13:25 UTC, SlimeSB commented on projects/1.20/assets/dawn-of-time/dawnoftimebuilder/lang/zh_cn.json
> +    "block.dawnoftimebuilder.planter_geranium_pink_bottom": "粉红色天竺葵花盒",
希望补充

2024-04-08 13:25 UTC, SlimeSB commented on projects/1.20/assets/dawn-of-time/dawnoftimebuilder/lang/zh_cn.json
> +    "block.dawnoftimebuilder.moraq_mosaic_recess": "浇筑马赛克退台",
退台？壁龛？

2024-04-08 13:25 UTC, SlimeSB commented on projects/1.20/assets/dawn-of-time/dawnoftimebuilder/lang/zh_cn.json
> +    "tooltip.dawnoftimebuilder.silk_worm_eggs": "蚕卵中的幼虫孵化出来后需要吃桑叶……",
这里时态没写清楚。虽然译文是符合逻辑的但多问一下。

2024-04-08 13:25 UTC, SlimeSB commented on projects/1.20/assets/dawn-of-time/dawnoftimebuilder/lang/zh_cn.json
> +    "tooltip.dawnoftimebuilder.silk_cocoons": "蚕木枝束上结好了漂亮的蚕茧。多个蚕茧合成即可缫出蚕丝。"
```suggestion
    "tooltip.dawnoftimebuilder.silk_cocoons": "木枝束上结好了漂亮的蚕茧。将多个蚕茧合成即可缫出蚕丝。"
```

2024-04-08 13:25 UTC, SlimeSB commented on projects/1.20/assets/dawn-of-time/dawnoftimebuilder/lang/zh_cn.json
> +    "block.dawnoftimebuilder.thatch_wheat_stairs": "茅草楼梯",
块

2024-04-08 16:02 UTC, ChuijkYahus commented on projects/1.20/assets/dawn-of-time/dawnoftimebuilder/lang/zh_cn.json
> +    "block.dawnoftimebuilder.thatch_wheat": "茅草快",
```suggestion
    "block.dawnoftimebuilder.thatch_wheat": "茅草块",
```

2024-04-08 16:25 UTC, ChuijkYahus commented on projects/1.20/assets/dawn-of-time/dawnoftimebuilder/lang/zh_cn.json
> +    "block.dawnoftimebuilder.fireplace": "篝火",
![2024-04-09_00 24 18](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/37573437-017a-46ce-9666-99271de945e2)
游戏内表现，确实是“开放式”壁炉

2024-04-08 16:30 UTC, ChuijkYahus commented on projects/1.20/assets/dawn-of-time/dawnoftimebuilder/lang/zh_cn.json
> +    "block.dawnoftimebuilder.boxwood_bush": "黄杨灌木",
![2024-04-09_00 29 52](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/61250a8e-2591-4ce6-b52b-5932625dbbbb)
和原版的甜浆果丛差距非常大，也不会结果
就是个看上去透明的完整方块（）

2024-04-08 16:33 UTC, ChuijkYahus commented on projects/1.20/assets/dawn-of-time/dawnoftimebuilder/lang/zh_cn.json
> +    "block.dawnoftimebuilder.moraq_mosaic_recess": "浇筑马赛克退台",
![2024-04-09_00 33 35](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/e89b5b5e-bca2-4e75-a6d1-d5301c69926b)
其实更像是变种楼梯

2024-04-08 16:52 UTC, ChuijkYahus commented on projects/1.20/assets/dawn-of-time/dawnoftimebuilder/lang/zh_cn.json
> +    "tooltip.dawnoftimebuilder.silk_worm_eggs": "蚕卵中的幼虫孵化出来后需要吃桑叶……",
![2024-04-09_00 41 55](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/d98c955b-5f94-4cf2-8851-0acb037fb0f4)
![2024-04-09_00 42 56](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/1c650292-dc49-4f8a-85e1-452ea6ffd348)
![2024-04-09_00 41 25](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/1e3c80d0-1825-4585-a557-d46151fabead)
![2024-04-09_00 43 02](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/ed9e4ef1-c033-46a0-a78e-a6a0da318531)
这模组里的养蚕比较暴躁
这里我想的是改成需求的叙述，原句怎么直接逐词都不太对劲，算是妥协
~~应该是我水平不太好~~

2024-04-13 05:49 UTC, SlimeSB commented on projects/1.20/assets/dawn-of-time/dawnoftimebuilder/lang/zh_cn.json
> +    "tooltip.dawnoftimebuilder.silk_worm_eggs": "蚕卵中的幼虫孵化出来后需要吃桑叶……",
```suggestion
    "tooltip.dawnoftimebuilder.silk_worm_eggs": "蚕卵中的幼虫在孵化时需要桑叶……",

```
时态是指这个。看上去是这样？蚕卵下面垫了桑叶。

2024-04-13 06:11 UTC, SlimeSB commented on projects/1.20/assets/dawn-of-time/dawnoftimebuilder/lang/zh_cn.json
> +    "block.dawnoftimebuilder.moraq_mosaic_recess": "浇筑马赛克退台",
没有更多意见

2024-04-13 13:44 UTC, ChuijkYahus commented on projects/1.20/assets/dawn-of-time/dawnoftimebuilder/lang/zh_cn.json
> +
```suggestion
```

2024-04-19 12:03 UTC, SlimeSB approved these changes

2024-04-21 04:20 UTC, merged