Tool leveling plus翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4311
Opened 2024-04-20 03:05 UTC by FantasyClouds

2024-05-06 13:45 UTC, SlimeSB commented on projects/1.18/assets/tool-leveling-plus/toolleveling/lang/zh_cn.json
这个和英文语言文件对不上

2024-05-06 14:05 UTC, SlimeSB requested changes

2024-05-08 08:12 UTC, SlimeSB commented on projects/1.20/assets/tool-leveling-plus/toolleveling/lang/zh_cn.json
> +	"screen.toolleveling.tool_leveling_table.summary.field_text":"增加%s级的附魔等级，每个特殊物品提升%s个等级。",
此二者游戏内如何？

2024-05-08 08:20 UTC, SlimeSB commented on projects/1.20/assets/tool-leveling-plus/toolleveling/lang/zh_cn.json
> +	"screen.toolleveling.tool_leveling_table.help.field_text":"1、在中间放上附魔过的物品\n\n2、在左边的槽里放足够的附魔书 (至少%s本)\n\n3、附魔台周围有书架能提升成功概率\n\n4、右边放上特殊物品可以让附魔等级更高\n\n5、按下“升级”按钮。",
此处是“应该如何使用？”的说明文字
这里的4、…… 也请修改

2024-05-08 08:22 UTC, SlimeSB commented on projects/1.20/assets/tool-leveling-plus/toolleveling/lang/zh_cn.json
> +	"commands.toolleveling.config.path":"配置文件总信息可以在%s找到。",
同样的，是“配置文件%s……”还是“%s的配置文件”或其他句式取决于游戏中实际显示的占位符。

2024-05-10 11:50 UTC, FantasyClouds commented on projects/1.20/assets/tool-leveling-plus/toolleveling/lang/zh_cn.json
> +	"screen.toolleveling.tool_leveling_table.summary.field_text":"增加%s级的附魔等级，每个特殊物品提升%s个等级。",
这个是给附魔提升等级，特殊物品额外增加等级，
比如四个锋利附魔书+锋利5钻剑=锋利6钻剑

2024-05-10 11:50 UTC, FantasyClouds commented on projects/1.20/assets/tool-leveling-plus/toolleveling/lang/zh_cn.json
> +	"screen.toolleveling.tool_leveling_table.summary.field_text":"增加%s级的附魔等级，每个特殊物品提升%s个等级。",
四个锋利附魔书+锋利5钻剑+3个特殊物品（可在配置文件修改，默认下界星）=锋利9钻剑

2024-05-10 12:12 UTC, SlimeSB commented on projects/1.18/assets/tool-leveling-plus/toolleveling/lang/zh_cn.json
> +	"screen.toolleveling.tool_leveling_table.summary.field_text.multi":"增加%s级的附魔等级，每个特殊物品提升 %s 个等级。",
```suggestion
	"screen.toolleveling.tool_leveling_table.summary.field_text":"最多提升%s魔咒等级，每个特殊物品增加%s级。",
	"screen.toolleveling.tool_leveling_table.summary.field_text.multi":"最多提升%s魔咒等级，每个特殊物品增加%s到%s级。",

```

2024-05-10 12:12 UTC, SlimeSB commented on projects/1.20/assets/tool-leveling-plus/toolleveling/lang/zh_cn.json
> +	"commands.toolleveling.config.path":"对于%s的配置文件可在%s处找到。",
```suggestion
	"commands.toolleveling.config.path":"配置文件%s可在此处找到：%s",

```

2024-05-10 12:14 UTC, SlimeSB commented on projects/1.20/assets/tool-leveling-plus/toolleveling/lang/zh_cn.json
> +	"screen.toolleveling.tool_leveling_table.summary.field_text.multi":"增加%s级的附魔等级，每个特殊物品提升 %s 个等级。",
等会！

2024-05-10 12:44 UTC, SlimeSB commented
1.18版目前只有1.4.5，是旧版的界面，语言文件错了！

2024-05-10 13:05 UTC, SlimeSB commented on projects/1.20/assets/tool-leveling-plus/toolleveling/lang/zh_cn.json
> +	"screen.toolleveling.tool_leveling_table.summary.field_text.multi":"增加%s级的附魔等级，每个特殊物品提升 %s 个等级。",
what item is required to increase the amount of enchantments that can be added to an item
提升魔咒可以被添加到物品的数量
what item is required to increase the amount of levels that can be added to an enchantment
提升等级可以被添加到魔咒的数量

2024-05-20 12:06 UTC, SlimeSB commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。
@FantasyClouds

2024-06-17 06:49 UTC, luoxueyasha commented
@SlimeSB 关不关

2024-06-25 08:39 UTC, SlimeSB commented
我把1.20改了合，1.18删掉

2024-07-13 02:10 UTC, SlimeSB approved these changes

2024-07-14 11:37 UTC, merged