Bygone nether翻译补充
CFPAOrg/Minecraft-Mod-Language-Package pull request #4319
Opened 2024-04-20 05:09 UTC by FantasyClouds

2024-04-20 15:51 UTC, ChuijkYahus requested changes

2024-04-20 15:51 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"item.bygonenether.chiseled_withered_blackstone": "錾制凋零黑石",
```suggestion
	"item.bygonenether.chiseled_withered_blackstone": "雕纹凋零黑石",
```
原版术语

2024-04-20 15:51 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"item.bygonenether.chiseled_warped_nether_bricks": "錾制诡异下界砖",
```suggestion
	"item.bygonenether.chiseled_warped_nether_bricks": "雕纹诡异下界砖块",
```
这个是类似原版红砖的物品吗

2024-04-20 15:51 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"item.bygonenether.gilded_netherite_shield": "镀金合金盾",
```suggestion
	"item.bygonenether.gilded_netherite_shield": "镶金下界合金盾",
```
这个`Gilded Netherite`是怎么合成的

2024-04-20 15:51 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"item.bygonenether.wither_skeleton_horse_spawn_egg": "凋灵骷髅马刷怪蛋",
```suggestion
	"item.bygonenether.wraither_spawn_egg": "凋灵死士刷怪蛋",
	"item.bygonenether.corpor_spawn_egg": "凋灵蛮兵刷怪蛋",
	"item.bygonenether.wither_skeleton_knight_spawn_egg": "凋灵骷髅骑士刷怪蛋",
	"item.bygonenether.wither_skeleton_horse_spawn_egg": "凋灵骷髅马刷怪蛋",
```
上方两个游戏内是什么样的

2024-04-20 15:51 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"item.bygonenether.warped_ender_pearl": "扭曲的末影珍珠",
```suggestion
	"item.bygonenether.warped_ender_pearl": "诡异末影珍珠",
```
与诡异相关的方块是否存在关系

2024-04-20 15:51 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"item.bygonenether.wither_waltz_music_disc.desc": "izofar - 凋灵华尔兹",
乐曲名除非现实存在且中译常用，不然不建议翻译

2024-04-20 15:51 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"item.bygonenether.crushed_withered_debris": "裂纹凋零残骸",
是否是与Create的联动

2024-04-20 15:51 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"item.bygonenether.withered_blackstone_vertical_slab": "竖直凋零黑石台阶",
```suggestion
	"item.bygonenether.withered_blackstone_vertical_slab": "凋零黑石竖直台阶",
```

2024-04-20 15:51 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"item.bygonenether.cracked_withered_blackstone_vertical_slab": "裂纹凋零黑石台阶",
```suggestion
	"item.bygonenether.cracked_withered_blackstone_vertical_slab": "裂纹凋零黑石竖直台阶",
```

2024-04-20 15:51 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"item.bygonenether.warped_nether_brick_vertical_slab": "扭曲的竖直下界砖台阶",
```suggestion
	"item.bygonenether.warped_nether_brick_vertical_slab": "诡异下界砖竖直台阶",
```

2024-04-20 15:51 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"block.bygonenether.chiseled_withered_blackstone": "錾制凋零黑石",
```suggestion
	"block.bygonenether.chiseled_withered_blackstone": "雕纹凋零黑石",
```

2024-04-20 15:51 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"block.bygonenether.chiseled_warped_nether_bricks": "錾制诡异下界砖",
```suggestion
	"block.bygonenether.chiseled_warped_nether_bricks": "雕纹诡异下界砖块",
```

2024-04-20 15:51 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"block.bygonenether.warped_nether_bricks": "诡异下界砖",
```suggestion
	"block.bygonenether.warped_nether_bricks": "诡异下界砖块",
```

2024-04-20 15:51 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"item.bygonenether.warped_nether_bricks": "诡异下界砖",
```suggestion
	"item.bygonenether.warped_nether_bricks": "诡异下界砖块",
```
这个是类似原版红砖的物品吗

2024-04-20 15:51 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"advancements.bygonenether.catacomb.title": "生存还是凋零...",
```suggestion
	"advancements.bygonenether.catacomb.title": "生存还是凋零……",
```
```suggestion
	"advancements.bygonenether.catacomb.title": "凋零与否……",
```
省略号必须修改

2024-04-20 15:51 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"advancements.bygonenether.ride_wither_skeleton_horse.description": "骑行一匹凋零骷髅马",
```suggestion
	"advancements.bygonenether.ride_wither_skeleton_horse.description": "骑行一匹凋灵骷髅马",
```

2024-04-20 15:51 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"advancements.bygonenether.root.title": "光辉重现",
这个模组的模组名是什么

2024-04-21 06:35 UTC, FantasyClouds commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"item.bygonenether.chiseled_withered_blackstone": "錾制凋零黑石",
已改

2024-04-21 17:09 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"item.bygonenether.gilded_netherite_boots": "镀金下界合金靴子",
```suggestion
	"item.bygonenether.gilded_netherite_helmet": "镶金下界合金头盔",
	"item.bygonenether.gilded_netherite_chestplate": "镶金下界合金胸甲",
	"item.bygonenether.gilded_netherite_leggings": "镶金下界合金护腿",
	"item.bygonenether.gilded_netherite_boots": "镶金下界合金靴子",
```
统一镶金和镀金
原版有`镶金黑石`，可以看下两者有无关联

2024-04-21 17:09 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"item.bygonenether.crushed_withered_debris": "裂纹凋灵残骸",
是否是与Create的兼容

2024-04-21 17:09 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"advancements.bygonenether.piglin_manor.title": "小心身后",
```suggestion
	"advancements.bygonenether.piglin_manor.title": "小心追击",
```
找了这东西的出典，仅建议，我也不知道怎么把“庄园”这个概念放进去

2024-04-21 17:09 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"block.bygonenether.chiseled_warped_nether_bricks": "雕纹诡异下界砖",
```suggestion
	"block.bygonenether.chiseled_warped_nether_bricks": "雕纹诡异下界砖块",
```

2024-04-25 18:40 UTC, ChuijkYahus requested changes

2024-04-25 18:40 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"item.bygonenether.gilded_netherite_helmet": "镶金金下界合金头盔",
```suggestion
	"item.bygonenether.gilded_netherite_helmet": "镶金下界合金头盔",
```

2024-04-25 18:40 UTC, ChuijkYahus commented on projects/1.20/assets/bygone-nether/bygonenether/lang/zh_cn.json
> +	"item.bygonenether.gilded_netherite_shield": "镶金下界合金盾",
```suggestion
	"item.bygonenether.gilded_netherite_shield": "镶金下界合金盾牌",
```
原版译名为`盾牌`

2024-04-27 07:22 UTC, ChuijkYahus approved these changes

2024-04-28 11:33 UTC, merged