Comforts翻译提交1.20
CFPAOrg/Minecraft-Mod-Language-Package pull request #4320
Opened 2024-04-20 05:36 UTC by FantasyClouds

2024-04-20 15:37 UTC, ChuijkYahus requested changes
请注意句末句号，与原文保持一致
未审核部分注意参照库内同模组已有翻译修改

2024-04-20 15:37 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/comforts/comforts/lang/zh_cn.json
> +  "gui.comforts.config.hammockUse.description": "可以使用吊床的时间",
```suggestion
  "gui.comforts.config.hammockUse.description": "可以使用吊床的时间。",
```

2024-04-20 15:37 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/comforts/comforts/lang/zh_cn.json
> +  "gui.comforts.config.sleepingBagUse.description": "可以使用睡袋的时间",
```suggestion
  "gui.comforts.config.sleepingBagUse.description": "可以使用睡袋的时间。",
```

2024-04-20 15:37 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/comforts/comforts/lang/zh_cn.json
> +  "gui.comforts.config.sleepingBagBreakChance.description": "一个睡袋使用后破掉的几率",
```suggestion
  "gui.comforts.config.sleepingBagBreakChance.description": "睡袋使用后破损的概率。",
```

2024-04-20 15:37 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/comforts/comforts/lang/zh_cn.json
> +  "gui.comforts.config.sleepingBagBreakChance.name": "睡袋破掉概率",
```suggestion
  "gui.comforts.config.sleepingBagBreakChance.name": "睡袋破损概率",
```

2024-04-20 15:37 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/comforts/comforts/lang/zh_cn.json
> +  "gui.comforts.config.sleepingBagEffects.description": "使用睡袋后玩家获得的药水效果\n格式：效果;时间(s);等级"
```suggestion
  "gui.comforts.config.sleepingBagEffects.description": "使用睡袋后玩家获得的状态效果。\n格式：<效果>;<时间（秒）>;<等级>"
```

2024-04-20 15:37 UTC, ChuijkYahus commented on projects/1.20-fabric/assets/comforts/comforts/lang/zh_cn.json
> +  "gui.comforts.config.sleepingBagBreakChanceLuckMultiplier.description": "这个参数将乘上玩家的幸运值，然后加到睡袋破掉概率上。",
```suggestion
  "gui.comforts.config.sleepingBagBreakChanceLuckMultiplier.description": "这个参数将乘上玩家的幸运值，然后加到睡袋破损概率上。",
```

2024-04-21 10:17 UTC, CodfishSnow commented on projects/1.20/assets/comforts/comforts/lang/zh_cn.json
> +  "gui.comforts.config.autoUse.name": "自动使用睡袋。",
```suggestion
  "gui.comforts.config.autoUse.description": "如果启用，玩家在放置睡袋时会自动尝试睡眠。",
```
或者按原文“自动使用”。

2024-04-21 10:20 UTC, CodfishSnow commented on projects/1.20/assets/comforts/comforts/lang/zh_cn.json
> +  "gui.comforts.config.restMultiplier.description": "如果开启阻止连续睡眠，这个参数将决定什么时候能再次入睡。（更大的数字更快入睡）",
应为“吊床”。

2024-04-21 10:24 UTC, CodfishSnow commented on projects/1.20/assets/comforts/comforts/lang/zh_cn.json
> +  "gui.comforts.config.sleepingBagEffects.name": "睡袋药水效果",
掉了个句号。

2024-04-21 17:10 UTC, ChuijkYahus requested changes
后半部分没有修改
是有特殊理由吗

2024-04-22 02:46 UTC, FantasyClouds commented
> 后半部分没有修改 是有特殊理由吗

已改，可能上次未保存

2024-05-26 14:21 UTC, ChuijkYahus reviewed
改动还是没有保存啊
同时建议检查标点，不强制改

2024-06-17 06:48 UTC, luoxueyasha commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

@FantasyClouds

2024-06-25 08:10 UTC, closed without merging