Sons of sins翻译提交1.20
CFPAOrg/Minecraft-Mod-Language-Package pull request #4329
Opened 2024-04-21 07:11 UTC by FantasyClouds

2024-04-21 10:10 UTC, FantasyClouds commented
翻译文件为最新版，不存在Key不匹配问题

2024-05-25 08:54 UTC, luoxueyasha requested changes
通篇问题严重，需要修改

2024-05-25 08:54 UTC, luoxueyasha commented on projects/1.20/assets/sons-of-sins/sons_of_sins/lang/zh_cn.json
> +  "advancements.ash_diamond.descr": "在血液中投掷16个灰烬",
```suggestion
  "advancements.ash_diamond.descr": "向血液中投掷灰烬",
```
原文`Throw ashes in blood`
是否要求玩家位于血液中再投掷灰烬？还是玩家在血液内/外，向血液中投掷灰烬？
`16个`是哪里来的？看key名像是进度描述，应该不需要技术性的具体解释；
如果防止玩家“只投一个”的话，可以用不定量描述词，如`一些`、`大量`

2024-05-25 08:54 UTC, luoxueyasha commented on projects/1.20/assets/sons-of-sins/sons_of_sins/lang/zh_cn.json
> +  "advancements.freddys_favorite_alloy.descr": "做出灵魂钢",
```suggestion
  "advancements.freddys_favorite_alloy.descr": "构建一块灵魂钢锭",
```
原文`Construct a Soul Steel Ingot`
但是我看前后文是没有锭的，具体是？

2024-05-25 08:54 UTC, luoxueyasha commented on projects/1.20/assets/sons-of-sins/sons_of_sins/lang/zh_cn.json
> +  "advancements.freddys_favorite_alloy.title": "Freddy's 最爱的合金",
Freddy's 是个完整的人名吗

2024-05-25 08:54 UTC, luoxueyasha commented on projects/1.20/assets/sons-of-sins/sons_of_sins/lang/zh_cn.json
> +  "advancements.ghost_like_paxel.title": "鬼一样的Paxel?",
```suggestion
  "advancements.ghost_like_paxel.title": "鬼一样的Paxel？",
```
标点符号应使用规范的汉语全角标点符号，具体要求请阅读我们的 [翻译规范](https://cfpa.site/TransRules/) 中 **03.标点符号** 这一节。
诸如这类的问题请在您翻译的所有文件中全部查明并修改。

2024-05-25 08:54 UTC, luoxueyasha commented on projects/1.20/assets/sons-of-sins/sons_of_sins/lang/zh_cn.json
> +  "advancements.its_morbin_time.title": "莫尔宾' 时刻",
原文`Morbin' Time`

https://www.yystv.cn/p/9218

暂无好翻译，这里做讨论。

2024-05-25 08:54 UTC, luoxueyasha commented on projects/1.20/assets/sons-of-sins/sons_of_sins/lang/zh_cn.json
> +  "advancements.original_sin.title": "它's……还活着?",
？

2024-06-01 02:14 UTC, luoxueyasha commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。
@FantasyClouds

2024-06-09 02:28 UTC, closed without merging