Epic Fight 官译拉取并修补
CFPAOrg/Minecraft-Mod-Language-Package pull request #4340
Opened 2024-04-28 13:40 UTC by nageih

2024-04-28 14:46 UTC, SlimeSB requested changes

2024-04-28 14:46 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"gamerule.weightPenalty": "重量惩罚适用于攻击速度。",
```suggestion
	"gamerule.weightPenalty": "重量惩罚作用于攻击速度。",

```
或施加、应用

2024-04-28 14:46 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"gui.epicfight.long_press_counter.tooltip": "判定长按所需的多少刻，用于武器的特殊攻击和闪避",
```suggestion
	"gui.epicfight.long_press_counter.tooltip": "判定为长按所需的刻，用于武器的特殊攻击和闪避",

```
主要修改意见在于how many在陈述句中译作x的数量
ticks不译？需要其他审阅人员帮助。

2024-04-28 14:46 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"gui.epicfight.aim_helper.tooltip": "在使用弓或弩瞄准时渲染瞄准辅助线，与极佳图形设置和一些着色器不兼容",
```suggestion
	"gui.epicfight.aim_helper.tooltip": "在使用弓或弩瞄准时渲染瞄准辅助线，与“极佳”图形设置和一些着色器不兼容",

```

2024-04-28 14:46 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"gui.epicfight.auto_switching_items.tooltip": "编辑自动切换战斗/采矿模式的物品列表",
```suggestion
	"gui.epicfight.auto_switching_items.tooltip": "编辑自动切换战斗/挖掘模式的物品列表",

```

2024-04-28 14:46 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"itemGroup.epicfight.items": "史诗战斗物品",
```suggestion
	"itemGroup.epicfight.items": "史诗战斗丨物品",

```

2024-04-28 14:46 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"key.epicfight.gui": "史诗战斗-GUI",
其他审阅人员看一下，按键设置是否需要加丨

2024-04-28 14:46 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"key.epicfight.weapon_innate_skill": "武器进阶技能",
特殊攻击or进阶技能？
我倾向于特殊攻击/技能，以及line128

2024-04-28 14:46 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"skill.epicfight.sweeping_edge.tooltip": "、以强力的斩击劈开附近的敌人。",
```suggestion
	"skill.epicfight.sweeping_edge.tooltip": "以强力的斩击劈开附近的敌人。",

```

2024-04-28 14:46 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"skill.epicfight.liechtenauer": "扎实剑法",
防御剑术
🔽
扎实剑法
希望能补充相关资料

2024-04-28 14:46 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"skill.epicfight.liechtenauer.tooltip": "采取%s秒的防御姿势。你可以在攻击时偏移你前方的所有攻击。击杀敌人会增加%s秒的防御姿势持续时间。当此效果生效时，你无法疾跑。",
```suggestion
	"skill.epicfight.liechtenauer.tooltip": "摆出%s秒的防御姿势。你可以在攻击时偏移你前方的所有攻击。击杀敌人会增加%s秒的防御姿势持续时间。当此效果生效时，你无法疾跑。",

```
有点吹毛求疵，我认为这样更好。

2024-04-28 14:46 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"skill.epicfight.blade_rush.tooltip": "斩杀敌人，施加趔趄状态5秒。趔趄达到3层就会处决目标。",
```suggestion
	"skill.epicfight.blade_rush.tooltip": "斜着砍向敌人，施加趔趄状态5秒。趔趄达到3层就会处决目标。",

```
非斩杀，斜着砍向可以修改为别的。对敌人释放斜斩？斩向敌人？

2024-04-28 14:46 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"skill.epicfight.roll.tooltip": "朝你移动的方向翻滚。闪避所有打来的攻击。\n\n（耐力：%d）",
```suggestion
	"skill.epicfight.roll.tooltip": "朝你移动的方向翻滚。闪避所有袭来的攻击。\n\n（耐力：%d）",

```

2024-04-28 14:46 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"skill.epicfight.step.tooltip": "朝你移动的方向快速移动一小段距离。闪避所有打来的攻击。\n\n（耐力：%d）",
```suggestion
	"skill.epicfight.step.tooltip": "朝你移动的方向快速移动一小段距离。闪避所有袭来的攻击。\n\n（耐力：%d）",

```

2024-04-28 14:46 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"skill.epicfight.technician.tooltip": "在敌人攻击击中你之前进行闪避，即可恢复耐力。",
```suggestion
	"skill.epicfight.technician.tooltip": "在敌人的攻击击中你之前恰好闪避，即可恢复耐力。",

```

2024-04-28 14:46 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"skill.epicfight.guard.category": "防守技能",
防守反击我倾向于译作防御。即先前的译名

2024-04-28 14:46 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"entity.epicfight.wither_skeleton_minion": "凋零眷族",
```suggestion
	"entity.epicfight.wither_skeleton_minion": "凋灵眷族",

```

2024-04-28 14:49 UTC, SlimeSB commented
然后空格记得删

2024-04-29 14:00 UTC, nageih commented
空格指的是哪些？

2024-04-29 14:54 UTC, SlimeSB requested changes

2024-04-29 14:54 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"attribute.name.epicfight.armor_negation": "%s 穿甲",
这里

2024-04-29 14:54 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"damage_source.epicfight.stun_long": "§8运用 §6长 §8击晕",
```suggestion
	"damage_source.epicfight.stun_short": "§8造成§a短时§8击晕",
	"damage_source.epicfight.stun_long": "§8造成§6长时§8击晕",

```

2024-04-29 14:54 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"damage_source.epicfight.stun_hold": "§c持有 §8目标",
是否是锁定目标

2024-04-29 14:54 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"skill.epicfight.guard": "防守",
```suggestion
	"skill.epicfight.guard": "防御",

```

2024-04-29 14:55 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"skill.epicfight.step.tooltip": "朝你移动的方向快速移动一小段距离。闪避所有打来的攻击。\n\n（耐力：%d）",
这里

2024-04-30 13:30 UTC, nageih commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"attribute.name.epicfight.armor_negation": "%s 穿甲",
这个地方是武器属性，特意加的空格

2024-04-30 13:30 UTC, nageih commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"skill.epicfight.guard": "防守",
下文的防御技能指的是一大类，这个防守是具体的一个技能

2024-04-30 13:30 UTC, nageih commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"damage_source.epicfight.stun_hold": "§c持有 §8目标",
待我去游戏中测试一下

2024-04-30 13:42 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"skill.epicfight.guard": "防守",
此处不必避讳，原文均为Guard

2024-04-30 15:51 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"attribute.name.epicfight.armor_negation": "%s 穿甲",
好像明白了

2024-04-30 15:52 UTC, SlimeSB commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"key.epicfight.gui": "史诗战斗-GUI",
还是改成丨吧

2024-05-01 03:41 UTC, nageih commented on projects/1.18/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"damage_source.epicfight.stun_hold": "§c持有 §8目标",
游戏内未找到出现的地方，找了下我朋友看了下源码，他给出的翻译建议是`固定目标`

2024-05-01 05:05 UTC, SlimeSB commented
辛苦了，有时间可以再往上游提交一下修改。

2024-05-01 05:05 UTC, SlimeSB approved these changes

2024-05-01 05:11 UTC, SlimeSB commented on projects/1.19/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"damage_source.epicfight.stun_long": "§8运用§6长§8击晕",
```suggestion
	"damage_source.epicfight.stun_short": "§8造成§a短时§8击晕",
	"damage_source.epicfight.stun_long": "§8造成§6长时§8击晕",

```

2024-05-01 05:11 UTC, SlimeSB commented on projects/1.20/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"damage_source.epicfight.stun_long": "§8运用§6长§8击晕",
```suggestion
	"damage_source.epicfight.stun_short": "§8造成§a短时§8击晕",
	"damage_source.epicfight.stun_long": "§8造成§6长时§8击晕",

```

2024-05-01 05:11 UTC, SlimeSB commented on projects/1.20/assets/epic-fight-mod/epicfight/lang/zh_cn.json
> +	"gamerule.weightPenalty": "重量惩罚作用于于攻击速度。",
```suggestion
	"gamerule.weightPenalty": "重量惩罚作用于攻击速度。",

```

2024-05-01 05:12 UTC, SlimeSB approved these changes

2024-05-02 13:59 UTC, merged