Scape and Run Parasites Addon: Cotesia Glomerata 翻译提交、Scape And Run: Parasite Vaccine翻译修改
CFPAOrg/Minecraft-Mod-Language-Package pull request #4355
Opened 2024-05-05 04:38 UTC by PioneerFlame

狠狠整了某虫群之心mod的汉化，有参考MCmod百科@平心 的个人翻译，不知道还收不收总之先丢在这
顺便悄悄把某SRP附属的专有名词改了
可能还有没检查到的错误，拷打就完了（OTZ）

2024-05-10 07:47 UTC, SlimeSB requested changes
此外，在1.12版本中英文数字与中文间需要空格。
英文标点需改成中文标点。
以上批量替换，不一一指出。

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.item.disruptor=§f中止§1演化§f
与上文相同的Phasing

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.factory.desc3=潜行时右键它会使其分解。如果已有绑定，则会首先解除绑定。
右键→右击
潜行时右击会使它分解

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.factory.desc4=它可以放在地上，或是与寄生体绑定，又或是通过交互——通常用鼠标右键——将寄生体转化为生物质。
```suggestion
tooltip.srpcotesia.factory.desc4=它可以放在地上，或是与寄生体绑定，又或是通过一般交互将寄生体转化为生物质（通常是右击）。

```

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.factory.desc5=你和寄生巢穴都需要有足够高的阶段才能恰当利用它。
阶段or等级？请全文通查

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.factory.desc7=生物质可以分别通过徒手攻击或空手使用来移除或添加。潜行可以使转移效率提高。
```suggestion
tooltip.srpcotesia.factory.desc7=生物质可通过空手攻击或交互来移除或添加。潜行可以使转移效率提高五倍。

```

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.factory.desc8=已有绑定的寄生巢穴会吸收较低级别的寄生体，亦可以用剑或者刮刀借此制造备件。
```suggestion
tooltip.srpcotesia.factory.desc8=已绑定的寄生巢穴会吸收较低级别的寄生体，可以用剑或者刮刀制造备件。

```
刮刀or手术刀？

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +item.srpcotesia.dirty_needle.name=§4污浊针头
Dirty Needle在前面出现过，可能需要注意一致性

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +item.srpcotesia.scalpel.name=§e活体刮刀
刮刀or手术刀、解剖刀

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +item.srpcotesia.well_divining_rod.name=§6井口指示仗
仗？杖、棒

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.well_divining_rod1=§f朝最近的§6井口§f发射火花。
的方向

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +message.srpcotesia.well.created.multiple=几个§6井口§f已经形成。
数个

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +message.srpcotesia.wellhere=一处§6井口§f在这，且§6封井器§f可以利用它。
这里有一个井口，可以对其使用封井器

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +message.srpcotesia.well.destroyed=一个在%s的§6井口§f已被摧毁！
一个位于x的……

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.parasitelightsource2=§f使光源可被接受。
bordering 是？

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tile.srpcotesia.inf_crafting_table.name=§e“寄生工作台”
工作台

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.craftingtable1=§4旧性难易。
本性难移、旧习难改。

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.osmosis1=§f根据放入的§9反应物§f对§9酿造囊§f进行改造。右键点击酿造囊或者§9反应物§f将之放入。
……。用酿造囊或反应物右键点击……
反应物or试剂？

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.soulless_core2=§f持有与所需的寄生体互动。
while 持有时……与……交互
互动or交互 用语需统一

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +item.srpcotesia.moldered_segments.name=§e腐化片段
节段
segments of spinal cord 脊髓节段

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +message.srpcotesia.trade.more=还需要更多生物质……
%d biomass is needed.
还需要x点生物质

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +message.srpcotesia.unlock.latch=寄生胞已解锁。
寄染索，总之一致

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +gui.jei.category.srpcotesia.factory.tierabove=等级%d
“+”

2024-05-10 07:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +enchantment.srpcotesia.breaching=§5抗逆
？

2024-05-10 13:56 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +effect.latched=§7寄生
理论上这个效果只有生物被玩家释放的Latch（翻译里写的寄染索）栓住才会有——默认配置是对非寄生体打秒伤，被杀死时概率同化；对寄生体则是挂防火和恢复效果（不是原版生命恢复，是mod恢复效果）
不过本身的效果似乎只有在某个寄生体持有这一效果时周边巢穴等级大于这个寄生体时，保证这个寄生体不会被消化——和作为给予寄生体效果的前置）

2024-05-10 14:30 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +effect.latched=§7寄生
latched可考虑译作牵连、缠绕。它在大部分情况下等于“catch”

2024-05-10 15:38 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +effect.phasing=§1同步
Scrying-击杀带有此效果的生物会额外获得他们经验值*效果倍率的生物质/玩家进化经验；一般是通过酿造囊附加这个效果
Phasing-不仅会让部分被给予该效果的寄生体穿过硬度较小的方块，而且会把他们移向攻击目标——遇到末地方块和一些边缘方块的时候会失效；遇到寄生体无法破坏的过硬方块时效果会被驱散；由树突体强化过的调度柱给予（作为不破坏影响范围内方块的替代）
——这个效果估计还是翻译成“相位”更好吧，会一起改

2024-05-10 15:57 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +effect.watched=被监视
这个效果是玩家进入第三人称假死状态过场看信息时给予的一个效果，我怀疑用被动语态更好

2024-05-10 16:14 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +effect.gravity=§b重力
原效果是末日适应因子对怪物的药水附魔，在离固体方块三格高的时候会给他们一个短暂的重力效果——带着附魔坠落时会对地面生物造成伤害（一级为10，该伤害只与附魔等级挂钩），并不是吸引x

2024-05-10 16:46 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +commands.srpcotesia.srpcwell.empty=当前没有活动的井口。
Well-和另一条所述的世界末日系统挂钩的另一机制，满世界刷的不可见实体，放置不管会丢演化点数——摧毁了会导致世界末日时刻加速
（因为玩家完全不可见，确认位置只能靠那个井口指示仗，伤害只能靠封井器造成伤害，只能姑且字面意思翻了OTZZZZZ）

2024-05-10 17:06 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +commands.srpcotesia.ante.disabled=适应因子已被禁用。
Armageddon System-世界末日系统，作者的补充说法是寄生体试图压住一些怪东西（which forces the parasites to keep an eldritch presence at bay），实际上则是一个平衡机制——随着时间进展和摧毁的“井口（wells）”会增加适应因子（Ante），给生物上药水效果和伤害加成护甲之类——且Ante到七阶会导致寄生体在阳光下燃烧

2024-05-10 17:19 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +overlay.srpcotesia.getdrops=按下%s制取掉落
![QQ图片20240511011108](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/101743100/c38e15ed-2616-48c5-8826-0c1be89b5884)
这个版本的汉化暂时没加空格，替换键值姑且参考一下好了x

2024-05-10 17:22 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.brew_sac.ammo=%d/%d掷出
确实是

2024-05-10 17:27 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +brew.srpcotesia.harm.name=瞬间伤害
（似乎在哪见过类似对harm效果的翻译OTZ……实际效果也确实和瞬间伤害药水完全一致）

2024-05-10 17:42 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +effect.embolism=§4栓塞
Embolism-在mod某些配置开启时，会以最高5点伤害每次将生物削到50%hp的寄巢之唤的生效阈值（这是这个mod的一个小改动）_（……尽管实际测试的时候并没有成功触发）_，与此同时会令寄巢之唤生效时间缩短（默认倍率是15倍）

2024-05-10 18:06 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +item.srpcotesia.mortifying_tentacle.name=§2殉葬卷须
_……我可以说是没检查到导致_……不，也有不太清楚怎么翻的缘故，所以用的原案翻译x这个确实很需要建议拜托了

2024-05-10 18:31 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +brew.srpcotesia.poisonBane.name=淬毒杀手
参考的是原版节肢杀手的翻法其实x

2024-05-10 18:46 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.factory.desc5=你和寄生巢穴都需要有足够高的阶段才能恰当利用它。
SRP本体的**演化阶段**和本mod寄生体玩家的**进化等级**是分开计算的，这部分没什么问题
_尽管前者会限制后者的上限_

2024-05-10 20:19 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.osmosis1=§f根据放入的§9反应物§f对§9酿造囊§f进行改造。右键点击酿造囊或者§9反应物§f将之放入。
反应物更好一点吧，毕竟使用的材料包括但不限于各种寄生体掉落物，凋灵骷髅头颅之类的x

2024-05-10 21:06 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +item.srpcotesia.mortifying_tentacle.name=§2殉葬卷须
暂定为“坏死”，取了mortify的坏疽意义

2024-05-10 21:13 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +item.srpcotesia.dirty_needle.name=§4污浊针头
感觉药水效果附魔和物品用同一个词怪怪的……不如说我确实很难理解为什么效果命名也是dirty needle

2024-05-10 21:26 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.parasitelightsource2=§f使光源可被接受。
说实在话——我也不知道
不论是游戏测试还是更新日志表现上那两个方块都是个可以生虫的光源，因此我确实不知道那个bordering乃至这个额外的注释有何用意

2024-05-11 09:58 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +effect.latched=§7寄生
应该说“拉住的”、“拉住不放的”后演变为门闩。
那么……叫什么好呢……
捕获我还是不满意，距离原意有些远了

2024-05-11 10:00 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +effect.embolism=§4栓塞
好吧我没有更好的叫法

2024-05-11 10:02 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +effect.phasing=§1同步
考虑译作 相位变换？

2024-05-11 10:03 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +effect.watched=被监视
叫旁观吧，虽然下面更适合叫旁观，

2024-05-11 10:27 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +commands.srpcotesia.srpcwell.empty=当前没有活动的井口。
就这样叫吧

2024-05-11 10:28 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +commands.srpcotesia.ante.disabled=适应因子已被禁用。
就这样叫吧，我想不出更好的。

2024-05-11 11:43 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +effect.latched=§7寄生
这个效果本身是个平衡性效果，不用指令都不一定调的出来——那……栓锁吗？

2024-05-11 11:47 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +effect.latched=§7寄生
好极了就这样

2024-05-11 14:57 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +effect.phasing=§1同步
有点想翻成相跃，不过多少有点意味不明x
相位跃迁？
（备注：带着这效果的寄生体是真的会卡在墙里而且不会窒息的）

2024-05-11 15:01 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +effect.phasing=§1同步
听着好高大上，都是科幻什么虫洞这那的，寄生虫真的能做到吗。

2024-05-11 15:14 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +effect.phasing=§1同步
也是呢，毕竟是个附属mod，还是稍微收敛一点吧
（其实只是尝逝缩减字数而已）
_不过，其实寄生体本体设定原参考有个光环洪魔的成分，再加上QA作者表示“寄生体要是把这颗星球扬了说不定就会上天找另外一个星球”的口嗨，嗯……不太好说_

2024-05-11 15:27 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +effect.phasing=§1同步
不对，其实光光是涉及到“相位”这个词已经够科幻的了，更别提相位变换了（。）

2024-05-11 15:29 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +effect.phasing=§1同步
就相位变换吧先

2024-05-12 21:29 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +overlay.srpcotesia.factory.bindto=按下%s绑定%s
非寄生虫玩家打开创造栏看到寄生巢穴的备注。

2024-05-12 21:46 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.parasitelightsource2=§f使边界光源可被接受。
虽然意味不明但还是按照原文翻译

2024-05-12 21:48 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.faustian_note2=§4又一个？
可靠的信函默认配置下需要寄生体0级演化以下才可开启，但这个不用。

2024-05-13 08:40 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +key.srpcotesia.mallmenu=打开增幅页面
malleability后文被译作了“延展性”，请确认是否是术语

2024-05-13 08:40 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +overlay.srpcotesia.factory.bindto=按下%s绑定%s
```suggestion
overlay.srpcotesia.factory.bindto=按下%s以绑定至%s

```

2024-05-13 08:40 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.factory.discard=%s分解
```suggestion
tooltip.srpcotesia.factory.discard=%s以分解

```
to

2024-05-13 08:40 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +overlay.srpcotesia.getdrops=按下%s制取掉落
```suggestion
overlay.srpcotesia.getdrops=按下%s制作掉落物

```
字面意思

2024-05-13 08:40 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.factory.discard=%s分解
取决于上下文

2024-05-13 08:40 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.brew_sac.ammo=%d/%d 掷出
```suggestion
tooltip.srpcotesia.brew_sac.ammo=%d/%d 投掷次数

```
具体根据实际情况

2024-05-13 08:40 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.brew_sac.refill=长按右键来重装
```suggestion
tooltip.srpcotesia.brew_sac.refill=长按右键重装

```

2024-05-13 08:40 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.reagent.via=§f当放入§b渗透活化器§f:
```suggestion
tooltip.srpcotesia.reagent.via=§f当放入§b渗透活化器§f时：

```

2024-05-13 08:40 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.reagent.adds=§f增加药水效果：%s
我觉得这里的brew是名词酿液的意思，这几句可能都要修改
修改与否取决于是否有相应的“brew”液体、物品。只是中间产物可不改

2024-05-13 08:40 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.macabre_pearl1=§f说服寄生体，使其更轻易地跟随你。
Can be used to convince parasites to follow you much more readily.
此句根据实际情况重译。“follow you”可能意为“追随你”等

2024-05-13 08:40 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.factory_drop2=§4达到如此程度的可塑性也会带来相应的代价，尽管我们不否认其效用。
此句可能需要重译

2024-05-13 08:40 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +item.srpcotesia.fetid_canister.name=§a腥臭“罐体”
是 滤毒罐 的讽刺双引号。本来是滤毒的但是放毒了，所以双引号。
可不更改，目前在及格线。

2024-05-13 08:40 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.craftingtable1=§4旧习难易。
依然是“全”或“无”的本土译法。习语不要发挥。

2024-05-13 08:40 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.booster.flair4=§c荒谬。
检查颜色符号

2024-05-13 08:40 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +message.srpcotesia.hasmaxbiomass=你无法持有更多生物质了。
store ?

2024-05-13 08:40 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +message.srpcotesia.notfollowing=这只寄生体已不再跟随你。
我不清楚是宠物那样的跟着还是另有所指，总之先指出

2024-05-13 08:42 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +overlay.srpcotesia.factory.bindto=按下%s绑定%s
这个是和寄生体互动绑定的信息，或许“按X以绑定XX”会更好？

2024-05-13 08:47 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +key.srpcotesia.mallmenu=打开增幅页面
这个是打开一个放增幅器的菜单，和那个吐槽巢穴掉落残余的……应该……不是一个东西……吧（心虚）

2024-05-13 09:09 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +overlay.srpcotesia.factory.bindto=按下%s绑定%s
不再要求更改

2024-05-13 09:32 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.reagent.adds=§f增加药水效果：%s
难说，毕竟不做别的效果附加这东西是丢不出去的，甚至最后塞进囊泡的最终产物究竟是不是液体都不好说（尽管扔出并爆开的时候很像是丢了个喷溅式药水）

2024-05-13 09:59 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.macabre_pearl1=§f说服寄生体，使其更轻易地跟随你。
调整他们物理上追随与否的状态（确信）_（虽然你寄生体是会自动跟随高阶玩家的）_，现在的调整是“令寄生体折服，使其更加轻易地追随你”

2024-05-13 10:13 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +message.srpcotesia.hasmaxbiomass=你无法持有更多生物质了。
这是自己存生物质到上限还要试图从巢穴拿的消息弹出.jpg

2024-05-13 10:26 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +message.srpcotesia.notfollowing=这只寄生体已不再跟随你。
物理上的跟随，宠物……嗯……可以是？
真的是和驯服的狼差不多的操作方式（）

2024-05-13 10:33 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.factory_drop2=§4达到如此程度的可塑性也会带来相应的代价，尽管我们不否认其效用。
这里的MALLEABILITY并不是专有名词
备注：这是一段虫群对巢穴内脏的吐槽，又及，这个掉落物对寄生虫玩家是没有什么用的

2024-05-13 10:33 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.craftingtable1=§4旧习难易。
改成原来的了.jpg

2024-05-13 10:59 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +message.srpcotesia.masticator.empty=你需要腥臭罐体使其运转。
```suggestion
message.srpcotesia.masticator.empty=你需要腥臭“滤毒罐”使其运转。

```

2024-05-13 11:01 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.macabre_pearl1=§f说服寄生体，使其更轻易地跟随你。
不知所云，但就这样吧

2024-05-13 11:01 UTC, SlimeSB approved these changes

2024-05-13 17:01 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.macabre_pearl2=§f对寄生体使用以切换其行动模式。
重新再改了一下，虽然略有些脱离原文但算是人话了（……）

2024-05-14 01:29 UTC, SlimeSB approved these changes

2024-05-15 13:35 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.scalpel1=§f经由精心制作，它似乎很满足。
我知道254和255行有点意味不明，其实暂时用的官中格式（只删了两三个字的微调）

2024-05-15 14:30 UTC, SlimeSB commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.scalpel1=§f经由精心制作，它似乎很满足。
三行改四句。
然后你应该在相应行评论，按shift可以选择多行

2024-05-15 17:36 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.tool_pickaxe=§f重塑寄生体的各身体部位，最终得到了这把武器。其内命火灼灼，光华闪耀。
可能备注打歪了，但我还是必须说明一下之前那个“命火灼灼”完全是官中方案，纯粹是因为群里未定官中内容修改，所以我才犹豫了一下还是使用目前使用量更多的官中方案
毕竟现在的SRP1.9.20官汉问题还是我在群里提出的，要为那个背锅我真的会很困扰，希望你能理解^^;;;

2024-05-15 17:38 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.tool_pickaxe1=§f§c破甲正如采掘一般。尤其易于挖掘被寄生的方块。
嗯确实是，寄生矿物这类的都算

2024-05-15 17:46 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.scalpel1=§f经由精心制作，它似乎很满足。
我可以说这是备注打歪的血案吗^q^

2024-05-15 17:58 UTC, PioneerFlame commented on projects/1.12.2/assets/srp-addon-cotesia-glomerata/srpcotesia/lang/zh_cn.lang
> +tooltip.srpcotesia.tool_pickaxe_sentient=§f悄无声息之间，活体镐斧§f灵智已开§b，完成了进化。
^q^;;;;;感谢审核大佬的建议，虽然有点欲哭无泪吧
因为这整句话同样是保留官中的结果，具体原因在前一句有解释
虽然这确实四舍五入确实等于我有问题，毕竟这算是在知情的情况下把明明就有问题的段落留下来了不是么……

2024-05-16 01:25 UTC, SlimeSB approved these changes

2024-05-18 03:36 UTC, merged