My Nether's Delight 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4361
Opened 2024-05-08 17:32 UTC by ChuijkYahus

2024-05-09 04:20 UTC, SlimeSB commented on projects/1.20/assets/my-nethers-delight/mynethersdelight/lang/zh_cn.json
> +  "item.mynethersdelight.hot_cream": "辛味膏",
辛淇淋

2024-05-09 04:20 UTC, SlimeSB commented on projects/1.20/assets/my-nethers-delight/mynethersdelight/lang/zh_cn.json
> +  "mynethersdelight.jei.info.strider_egg": "等下……炽足兽原来是卵生生物？不可思议……\n\n不管怎么说，这种蛋只能通过小心谨慎地捕猎获得。\n外壳很硬，也许只有破开才能吃了……",
不管怎么说，这种蛋在捕猎/狩猎时需要小心谨慎

2024-05-09 05:44 UTC, SlimeSB submitted a review, later dismissed

2024-05-10 05:37 UTC, SlimeSB submitted a review, later dismissed

2024-05-10 05:38 UTC, SlimeSB commented
虽然听着很别扭但我挑不出错来

2024-05-10 05:57 UTC, SlimeSB commented on projects/1.20/assets/my-nethers-delight/mynethersdelight/lang/zh_cn.json
> +  "block.mynethersdelight.letios_compost": "忘魂肥料",
[Lethe](https://www.quword.com/etym/s/Lethe)
river of Hades (whose water when drunk caused forgetfulness of the past), from Greek lethe, literally "forgetfulness, oblivion," related to lethargos "forgetful," lathre "secretly, by stealth," lathrios "stealthy," lanthanein "to be hidden." Cognate with Latin latere "to be hidden" (see [latent](https://www.quword.com/etym/s/latent)). Related: Lethean.

补充一些词源演变

2024-05-10 13:18 UTC, ChuijkYahus commented on projects/1.20/assets/my-nethers-delight/mynethersdelight/lang/zh_cn.json
> +  "block.mynethersdelight.letios_compost": "忘魂肥料",
来个古希腊语的拼写，方便找资料：
Λήθη（Lethe，勒忒河，忘川）
λήθιος（lethios，causing forgetfulness，“导致健忘”）

2024-05-10 16:36 UTC, ChuijkYahus commented
![%UZ`4_K9E_I%26XSD6ATC)I](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/94828194/f96906e3-8831-4ad5-8779-64f7ab511f9a)

审核留档
感谢@RaymondBlaze 的审核
~~ping一下应该不会没礼貌吧（）~~

2024-05-10 16:41 UTC, RaymondBlaze requested changes

2024-05-11 00:53 UTC, SlimeSB commented on projects/1.20/assets/my-nethers-delight/mynethersdelight/lang/zh_cn.json
> +  "block.mynethersdelight.powdery_cane": "焰药竹秆",
![Screenshot_2024-05-11-08-51-35-126_mark.via.jpg](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/86453765/d26ae9af-6030-43a0-be98-84f2d68ad6fc)

用秆而不用竿。先前查看频率的时候是秆最多。开始也感觉很奇怪但是还是不能因没见过而否认。

2024-05-11 10:44 UTC, SlimeSB commented on projects/1.20/assets/my-nethers-delight/mynethersdelight/lang/zh_cn.json
> +  "block.mynethersdelight.powdery_cane": "焰药竹秆",
不再要求回退，或许可以考虑译作烟药茎或者茎秆？

2024-05-11 11:35 UTC, ChuijkYahus commented on projects/1.20/assets/my-nethers-delight/mynethersdelight/lang/zh_cn.json
> +  "block.mynethersdelight.powdery_cane": "焰药竹秆",
个人其实觉得`茎`就OK

2024-05-11 11:45 UTC, SlimeSB commented on projects/1.20/assets/my-nethers-delight/mynethersdelight/lang/zh_cn.json
> +  "block.mynethersdelight.powdery_cane": "焰药竹秆",
不改了！就这样！

2024-05-12 15:28 UTC, RaymondBlaze requested changes

2024-05-12 15:28 UTC, RaymondBlaze commented on projects/1.20/assets/my-nethers-delight/mynethersdelight/lang/zh_cn.json
> +  "mynethersdelight.jei.info.wild_powdery": "烟药竹秆是绯红森林中极具侵略性的作物。\n\n它结出的浆果一触即爆，还是割断红色的茎好些……"
```suggestion
  "mynethersdelight.jei.info.wild_powdery": "烟药秆是绯红森林中极具侵略性的作物。\n\n它结出的浆果一触即爆，还是割断红色的茎好些……"
```
需要和修改后的 Powdery Cane 译名统一。

2024-05-12 15:28 UTC, RaymondBlaze commented on projects/1.20/assets/my-nethers-delight/mynethersdelight/lang/zh_cn.json
> +  "block.mynethersdelight.bullet_pepper": "烟药弹椒",
```suggestion
  "block.mynethersdelight.bullet_pepper": "爆弹椒",
```
原文 Bullet Pepper 不含 Powdery 前缀，译名中无需保留“烟药”前缀，且“烟药弹椒”四个字不是很顺口。在保持和烟药竹的相关性的前提下，可译为“烟弹椒”。
但从纹理角度上看，其实 Bullet Pepper 作为果实和烟药竹的整体外观实际上差异较大，译名完全放弃和烟药竹的相关性也未尝不可（先例：橡树和苹果），根据其“一触即爆”的描述，建议译为“爆弹椒”。

2024-05-12 15:40 UTC, ChuijkYahus commented on projects/1.20/assets/my-nethers-delight/mynethersdelight/lang/zh_cn.json
> +  "mynethersdelight.jei.info.wild_powdery": "烟药竹秆是绯红森林中极具侵略性的作物。\n\n它结出的浆果一触即爆，还是割断红色的茎好些……"
悲，这个地方提交出错了

2024-05-12 15:41 UTC, ChuijkYahus commented on projects/1.20/assets/my-nethers-delight/mynethersdelight/lang/zh_cn.json
> +  "block.mynethersdelight.potted_bullet_pepper": "烟药弹椒盆栽",
```suggestion
  "block.mynethersdelight.potted_bullet_pepper": "爆弹椒盆栽",
```

2024-05-12 16:02 UTC, RaymondBlaze approved these changes

2024-05-12 16:08 UTC, SlimeSB approved these changes

2024-05-13 08:59 UTC, ChuijkYahus commented
由@RaymondBlaze 转投官方
此PR关闭，感谢各位审核人员！

2024-06-02 13:21 UTC, SlimeSB commented
reopen and merge

2024-06-03 01:40 UTC, luoxueyasha commented
啊？不是转官译了吗

2024-06-03 01:44 UTC, SlimeSB commented
那边一直挂着，这边先合吧

2024-06-03 04:59 UTC, luoxueyasha approved these changes

2024-06-03 05:00 UTC, luoxueyasha commented
不知道为啥我手机上没有合并入库的按钮，是还有没有resolved的内容吗

2024-06-03 06:44 UTC, merged