Powah! (Rearchitected) 补充翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4387
Opened 2024-05-22 05:50 UTC by ZHAY10086

只提交了官库缺失的部分，主要为了避免1.18项目覆盖

2024-05-26 08:59 UTC, Cactusstudent requested changes
总之就是问题很多，这个红牌不得不给了，目前审到的问题如下：
1. 语句不通顺，存在很多中文不常用的被动
2. 翻译风格奇异，颇有译后翻译的味道

那就只能麻烦ZY修了

2024-05-26 08:59 UTC, Cactusstudent commented on projects/1.20/assets/powah-rearchitected/powah/lang/zh_cn.json
> +    "item.powah.book": "手册（Powah!）",
```suggestion
    "item.powah.book": "Powah! 手册",
```

2024-05-26 08:59 UTC, Cactusstudent commented on projects/1.20/assets/powah-rearchitected/powah/lang/zh_cn.json
> +    "wiki.powah.binding_card_1": "你首先需要将自己绑定与之绑定。右击以完成。",
原文：**You need to link it with you before adding it to the player transmitter, Right-click it to bind.**

2024-05-26 08:59 UTC, Cactusstudent commented on projects/1.20/assets/powah-rearchitected/powah/lang/zh_cn.json
> +    "wiki.powah.binding_card_dim_1": "你首先需要将自己绑定与之绑定。右击以完成。",
原文：**You need to link it with you before adding it to the player transmitter, Right-click it to bind.**

2024-05-26 08:59 UTC, Cactusstudent commented on projects/1.20/assets/powah-rearchitected/powah/lang/zh_cn.json
> +    "wiki.powah.dry_ice_0": "干冰主要被用于降低反应堆的温度。它生成于Y=64以下，但也可以通过同时充能两个蓝冰获得。",
```suggestion
    "wiki.powah.dry_ice_0": "干冰主要用于降低反应堆的温度。它生成于Y=64以下，但同时也可以通过充能两个蓝冰获得。",
```

2024-05-26 08:59 UTC, Cactusstudent commented on projects/1.20/assets/powah-rearchitected/powah/lang/zh_cn.json
> +    "wiki.powah.ender_cell_0": "末影单元可被用于为其拥有者在末影网络的特定频道内存储FE能量。",
原文：**The Ender Cell its a block used to store energy (FE) to a specific channel of the ender network of the owner.**
完了，看得我不会说话了

2024-05-26 08:59 UTC, Cactusstudent commented on projects/1.20/assets/powah-rearchitected/powah/lang/zh_cn.json
> +    "wiki.powah.energy_cable_0": "线缆可被用于转移能量。",
转移->传输，这官译译后翻译的可能性很大啊

2024-05-26 08:59 UTC, Cactusstudent commented on projects/1.20/assets/powah-rearchitected/powah/lang/zh_cn.json
> +    "wiki.powah.reactor_0": "反应堆是一种以晶质铀为燃料的多方块FE产能器。",
产……能器？->发电机好些吧

2024-08-01 12:18 UTC, mamaruo reviewed
这丫长文本都得重译。没看完，随手挑的。

2024-08-01 12:18 UTC, mamaruo commented on projects/1.20/assets/powah-rearchitected/powah/lang/zh_cn.json
> +    "wiki.powah.uraninite_0": "晶质铀矿石是一种稀有的矿石。其贫瘠变种生成于Y=64以下，普通变种生成于Y=20以下，致密变种生成于Y=0以下，矿团大小为1-5。",
| **审阅级别** |
|:--------------:|
|⚪ **轻微** / 不阻止合并但需三思|

原文：
- **Uraninite Ore is an ore rarely found underground at levels below 64 for poor, below 20 for the normal, and below 0 for dense, and is found in 1 - 5 block deposits.**
```suggestion
    "wiki.powah.uraninite_0": "晶质铀矿石是一种稀有的矿石。其贫瘠变种生成于Y=64以下，普通变种生成于Y=20以下，致密变种生成于Y=0以下，矿团大小为1-5个方块。",
```

2024-08-01 12:18 UTC, mamaruo commented on projects/1.20/assets/powah-rearchitected/powah/lang/zh_cn.json
> +    "wiki.powah.solar_panel_0": "太阳能板在阳光存在时会产出FE能量。更高等级每刻产出的FE能量更多。任何位于太阳能板上方阻挡其阳光的方块都会使其停止产出。",
| **审阅级别** |
|:--------------:|
|🔵 **一般** / 阻止合并|

原文：
- **The Solar Panel is an FE generator that generates energy when exposed to sunlight, high tiers generates more FE/t, any block that stop light above the Solar panel will stop its production.**
```suggestion
    "wiki.powah.solar_panel_0": "太阳能板在阳光下产出FE能量。等级越高产能越快。上方有方块阻挡阳光时停止产能。",
```

2025-03-25 14:08 UTC, Cactusstudent commented on projects/1.20/assets/powah-rearchitected/powah/lang/zh_cn.json
> +    "item.powah.book": "手册（Powah!）",
是否考虑把所有后置的括号全部去掉，将其中的内容作为原文的修饰成分放在原文当中

2025-03-25 14:08 UTC, ZHAY10086 commented on projects/1.20/assets/powah-rearchitected/powah/lang/zh_cn.json
> +    "item.powah.book": "手册（Powah!）",
目前准备先全按全文格式过一遍

2025-03-25 14:09 UTC, ZHAY10086 commented on projects/1.20/assets/powah-rearchitected/powah/lang/zh_cn.json
> +    "tag.item.c.raw_uraninite_ores": "粗晶质铀矿",
Uraninite是晶质铀，不是晶质铀矿

2025-03-25 16:18 UTC, ZHAY10086 commented on projects/1.20/assets/powah-rearchitected/powah/lang/zh_cn.json
> +    "block.powah.deepslate_uraninite_ore_poor": "深层贫瘠晶质铀矿石",
全改了

2025-04-09 04:47 UTC, mamaruo commented
本周四或周六来看

2025-04-10 14:59 UTC, mamaruo commented on projects/1.20/assets/powah-rearchitected/powah/lang/zh_cn.json
> +    "wiki.powah.ender_cell_0": "末影单元用于为玩家末影网络的特定频道存储能量（FE）。",
| **审阅级别** |
|:--------------:|
|🔵 **一般** / 阻止合并|

原文：
- **The Ender Cell its a block used to store energy (FE) to a specific channel of the ender network of the owner.**
```suggestion
    "wiki.powah.ender_cell_0": "末影单元是存储存储能量（FE）的方块，其中能量专属与方块主人的特定末影网络频道。",
```
owner

2025-04-19 17:59 UTC, mamaruo reviewed
都怪GitHub的batch comment

2025-04-19 17:59 UTC, mamaruo commented on projects/1.20/assets/powah-rearchitected/powah/lang/zh_cn.json
> +    "wiki.powah.energy_discharger_0": "能量提取器可提取含能物品中的能量（FE），并存储在自身缓存中。使用线缆连接能量提取器以再次利用这些能量。",
| **审阅级别** |
|:--------------:|
|⚪ **轻微** / 不阻止合并但需三思|

原文：
- **The Energy Discharger its a block used to drain energy (FE) out of charged items and then store it to an internal buffer if then connected via cables to extract that stored power and re-using it again.**
```suggestion
    "wiki.powah.energy_discharger_0": "能量提取器可提取含能物品中的能量（FE），并存储在自身缓存中。之后，如果通过线缆连接，就可以从中提取这些储存的能量并重新使用。",
```

2025-04-19 17:59 UTC, mamaruo commented on projects/1.20/assets/powah-rearchitected/powah/lang/zh_cn.json
> +    "wiki.powah.energy_cell_1": "也可在末影单元GUI中，通过Shift单击将其添加到选定末影网络频道中，为其增加能量容量，其中存储的能量会一并添加到频道中。",
| **审阅级别** |
|:--------------:|
|🔵 **一般** / 阻止合并|

原文：
- **Can Also be used to add capacity to an Ender Network channel by Shift-clicking it to an Ender Cell GUI, if the Energy Cell contains energy then will also be applied to the ender network channel.**
```suggestion
    "wiki.powah.energy_cell_1": "1",
```
前半句同步192行

2025-04-19 17:59 UTC, mamaruo commented on projects/1.20/assets/powah-rearchitected/powah/lang/zh_cn.json
> +    "info.powah.gen.mode.desc": "反应堆会在能量缓存满的时候停止\n并在能量少于70%时启动",
| **审阅级别** |
|:--------------:|
|⚪ **轻微** / 不阻止合并但需三思|

原文：
**The reactor will stop when is full and start 
when has less than 70% of energy.**
```suggestion
    "info.powah.gen.mode.desc": "反应堆会在能量缓存满的时候停止\n并在能量少于70%时启动。",
```

2025-04-21 03:19 UTC, ZHAY10086 commented on projects/1.20/assets/powah-rearchitected/powah/lang/zh_cn.json
> +    "wiki.powah.ender_cell_2": "你可以在末影单元GUI中，按Shift单击能量单元或电池，来将其添加至所选频道。",
放到下一行了，这行句子感觉已经够冗长了，再加读起来不太顺

2025-04-21 03:22 UTC, ZHAY10086 commented on projects/1.20/assets/powah-rearchitected/powah/lang/zh_cn.json
> +    "wiki.powah.reactor_1": "要建造反应堆，需持有36个反应堆方块，一块3x4x3大小的可建造区域。在该区域的中心放置一个反应堆方块后，它会自动完成建造。",
因为原文疏漏吧，确实就是需要3x4x3的建造空间

2025-04-21 03:46 UTC, ZHAY10086 commented on projects/1.20/assets/powah-rearchitected/powah/lang/zh_cn.json
> +    "wiki.powah.reactor_3": "保证反应堆的缓存充满燃料以使其更好地产出能量。",
缓存越满产能越高应该

2025-04-23 02:22 UTC, mamaruo reviewed
已完成对1.20的审阅，同步其他版本，即可合并。

2025-04-25 03:29 UTC, ZHAY10086 commented
我之后抽空搞一下其他版本，近期可能没啥时间

2025-04-25 14:39 UTC, mamaruo reviewed
有什么好办法能验证GuideMe的格式正确性。

传一下 GuideMe 的英文版。

2025-04-25 14:39 UTC, mamaruo commented on projects/1.18/assets/powah/powah/lang/zh_cn.json
这个文件得改一下 CurseForge Slug `powah-rearchitected`

2025-04-25 14:48 UTC, ZHAY10086 commented on projects/1.18/assets/powah/powah/lang/zh_cn.json
已修改

2025-05-15 07:38 UTC, ZHAY10086 commented
> 传一下 GuideMe 的英文版。

抱歉都忘了这茬了

2025-07-24 14:52 UTC, ChuijkYahus reviewed
表头的空格如果愿意可以改下（只是强迫症而已

没看旧版本这句有没有问题，如果有需要同步改

2025-07-24 14:52 UTC, ChuijkYahus commented on projects/1.21/assets/powah-rearchitected/powah/guides/powah/book/_zh_cn/items/binding_card_dim.md
> +绑定卡用于链接位于同一维度的玩家与玩家供电仪。
```suggestion
绑定卡（跨维度）用于跨维度链接玩家与玩家供电仪。 
```

2025-07-24 15:18 UTC, ChuijkYahus approved these changes
只看了新的GuideME部分，这部分没问题了

2025-07-24 15:19 UTC, ChuijkYahus commented on projects/1.21/assets/powah-rearchitected/powah/guides/powah/book/_zh_cn/energy_blocks/energizing.md
> +充能台用于充能物品，周围9X9范围内至少需要存在一台充能棒才能工作，充能速度取决于充能棒的数量和等级（能量传输速率）。
```suggestion
充能台用于充能物品，周围9x9范围内至少需要存在一台充能棒才能工作，充能速度取决于充能棒的数量和等级（能量传输速率）。
```
算是统一手册内的乘号

2025-07-24 15:24 UTC, ChuijkYahus submitted a review, later dismissed

2025-07-25 15:01 UTC, Cactusstudent reviewed
还是有点小问题，记得其他版本也顺便一修

2025-07-25 15:01 UTC, Cactusstudent commented on projects/1.16/assets/powah/powah/lang/zh_cn.json
> +  "wiki.powah.thermo_generator_0": "热力发电机在熔岩等高温流体或方块上方时会产出FE能量。需要消耗流体冷却剂（例如水）。",
和L192统一一下吧，不用括号了。后半句直接改为：需要消耗水等流体冷却剂？

2025-07-25 15:01 UTC, Cactusstudent commented on projects/1.16/assets/powah/powah/lang/zh_cn.json
> +  "wiki.powah.ender_cell_0": "末影单元是存储存储能量（FE）的方块，其中能量专属于方块主人的特定末影网络频道。",
```suggestion
  "wiki.powah.ender_cell_0": "末影单元是存储能量（FE）的方块，其中能量专属于方块主人的特定末影网络频道。",
```
方块主人 -> 方块所有者 可能好些？

2025-07-25 15:01 UTC, Cactusstudent commented on projects/1.16/assets/powah/powah/lang/zh_cn.json
> +  "wiki.powah.uraninite_0": "晶质铀矿石是一种稀有的矿石。其贫瘠变种生成于1-64高度，普通变种生成于1-32高度，致密变种生成于1-16高度，以1-4个方块大小的矿团形式生成。。",
```suggestion
  "wiki.powah.uraninite_0": "晶质铀矿石是一种稀有的矿石。其贫瘠变种生成于1-64高度，普通变种生成于1-32高度，致密变种生成于1-16高度，以1-4个方块大小的矿团形式生成。",
```

2025-07-25 15:01 UTC, Cactusstudent commented on projects/1.21/assets/powah-rearchitected/powah/guides/powah/book/_zh_cn/generators/thermo_generator.md
> +热力发电机在熔岩等高温流体或方块上方时会产出FE能量。需要消耗流体冷却剂（例如水）。
同上

2025-07-25 15:01 UTC, Cactusstudent commented on projects/1.21/assets/powah-rearchitected/powah/guides/powah/book/_zh_cn/materials/uraninite.md
> +需要铁镐及更高等级的镐来挖掘。挖掘时会根据矿石种类掉落1-4个粗晶质铀（受时运影响）。
和 zh_cn.json 的说法统一下？

2025-07-25 15:01 UTC, Cactusstudent commented on projects/1.21/assets/powah-rearchitected/powah/guides/powah/book/_zh_cn/storage_transfer/ender_cell.md
> +末影单元是存储存储能量（FE）的方块，其中能量专属于方块主人的特定末影网络频道。
同上

2025-07-25 15:13 UTC, ZHAY10086 commented on projects/1.21/assets/powah-rearchitected/powah/guides/powah/book/_zh_cn/materials/uraninite.md
> +需要铁镐及更高等级的镐来挖掘。挖掘时会根据矿石种类掉落1-4个粗晶质铀（受时运影响）。
1.16的粗晶质铀也分普通贫瘠致密，和更高版本不同

2025-07-25 20:04 UTC, mamaruo requested changes
结合对1.21的手册文本做了完整的审校；若原文无异请同步到其他版本

2025-07-25 20:04 UTC, mamaruo commented on projects/1.21/assets/powah-rearchitected/powah/guides/powah/book/_zh_cn/materials/dry_ice.md
> +干冰主要用于降低反应堆的温度。它生成于Y=64以下，但同时也可以通过充能两个蓝冰获得。
但同时？
you can also obtain it by energizing two pieces of blue ice.

2025-07-25 20:04 UTC, mamaruo commented on projects/1.21/assets/powah-rearchitected/powah/guides/powah/book/_zh_cn/materials/uraninite.md
> +需要铁镐及更高等级的镐来挖掘。挖掘时会根据矿石种类掉落1-4个粗晶质铀矿（受时运影响）。
An iron or better pickaxe is needed to mine it, and when mined it will drop 1 piece of Raw Uraninite based on the ore type (the amount dropped are effected by fortune). 
与原文不符

2025-07-25 20:04 UTC, mamaruo commented on projects/1.21/assets/powah-rearchitected/powah/guides/powah/book/_zh_cn/storage_transfer/ender_cell.md
> +只要用于能量传输的末影单元拥有处于激活状态且容量有效的频道，你就可以在任何位置访问该频道中储存的能量。
不好，长定语

2025-07-25 20:04 UTC, mamaruo commented on projects/1.21/assets/powah-rearchitected/powah/guides/powah/book/_zh_cn/storage_transfer/ender_cell.md
> +只要用于能量传输的末影单元拥有处于激活状态且容量有效的频道，你就可以在任何位置访问该频道中储存的能量。
只要末影单元已激活某个频道，并且该频道具有有效容量，你就可以从任意位置地方访问该频道中存储的能量，并实现能量的传输。

2025-07-25 20:04 UTC, mamaruo commented on projects/1.21/assets/powah-rearchitected/powah/guides/powah/book/_zh_cn/storage_transfer/energy_cell.md
> +能量单元可存储能量（FE）。
方块丢了
The Energy Cell its a block used to store energy (FE).

2025-07-25 20:04 UTC, mamaruo commented on projects/1.21/assets/powah-rearchitected/powah/guides/powah/book/_zh_cn/storage_transfer/energy_cell.md
> +也可在末影单元的GUI中，Shift单击电池可为末影网络的频道提升储量，其中存储的能量会一并添加到频道中。
电池-单元

Can Also be used to add capacity to an Ender Network channel by Shift-clicking it to an Ender Cell GUI, if the Energy Cell contains energy then will also be applied to the ender network channel.

2025-07-26 02:30 UTC, ZHAY10086 commented on projects/1.21/assets/powah-rearchitected/powah/guides/powah/book/_zh_cn/materials/uraninite.md
> +需要铁镐及更高等级的镐来挖掘。挖掘时会根据矿石种类掉落1-4个粗晶质铀矿（受时运影响）。
1.16：不同变种矿石分别掉落1个对应种类的粗晶质铀矿
1.18-1.21：[贫瘠, 普通, 致密] 掉落的粗晶质铀矿为 [1, 2, 4]
这里是原文有误

2025-07-26 02:32 UTC, ZHAY10086 commented on projects/1.21/assets/powah-rearchitected/powah/guides/powah/book/_zh_cn/storage_transfer/energy_cell.md
> +能量单元可存储能量（FE）。
已改

2025-07-26 02:32 UTC, ZHAY10086 commented on projects/1.21/assets/powah-rearchitected/powah/guides/powah/book/_zh_cn/storage_transfer/energy_cell.md
> +也可在末影单元的GUI中，Shift单击电池可为末影网络的频道提升储量，其中存储的能量会一并添加到频道中。
已改

2025-07-26 02:32 UTC, ZHAY10086 commented on projects/1.21/assets/powah-rearchitected/powah/guides/powah/book/_zh_cn/materials/dry_ice.md
> +干冰主要用于降低反应堆的温度。它生成于Y=64以下，但同时也可以通过充能两个蓝冰获得。
已改

2025-07-26 02:35 UTC, ZHAY10086 commented on projects/1.21/assets/powah-rearchitected/powah/guides/powah/book/_zh_cn/storage_transfer/ender_cell.md
> +只要用于能量传输的末影单元拥有处于激活状态且容量有效的频道，你就可以在任何位置访问该频道中储存的能量。
已改

2025-07-26 02:36 UTC, ZHAY10086 commented
@mamaruo 已修改完毕

2025-07-26 12:37 UTC, mamaruo approved these changes
044e76cf3aaf1f1eeba43475d9fe4ce1dcdd55e9

上面的commit的参考信息：晶质铀矿是术语，依据[新指南](https://bbs.mcmod.cn/thread-21955-1-1.html)，所以不能省略“矿”。
参考来源：http://www.nimrf.net.cn/kwx/detail/2776 - [webarchive 备份](https://web.archive.org/web/20250726122247/http://www.nimrf.net.cn/kwx/detail/2776)

2025-07-27 16:43 UTC, Cactusstudent approved these changes

2025-07-27 16:44 UTC, merged