提交The Flesh That Hates翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #4414
Opened 2024-05-31 11:02 UTC by Xinshou233

2024-05-31 11:07 UTC, Xinshou233 reviewed
修正json语法错误

2024-06-01 03:43 UTC, SlimeSB commented
![22e89c041a0a87e92ce6807ab482211d](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/86453765/c9876832-d127-4c15-9443-5b412dbb8c25)
等我期末考完看

2024-06-25 10:26 UTC, SlimeSB requested changes
可能有遗漏，此份译文质量较差，且有机翻的嫌疑。
请完成修改，并自查自纠，最好进游戏看以确保准确。
@Xinshou233

2024-06-25 10:26 UTC, SlimeSB commented on projects/1.20/assets/the-flesh-that-hates/the_flesh_that_hates/lang/zh_cn.json
> +  "entity.the_flesh_that_hates.flesh_hunter_two": "血肉猎手 等级二",
等级二→二

2024-06-25 10:26 UTC, SlimeSB commented on projects/1.20/assets/the-flesh-that-hates/the_flesh_that_hates/lang/zh_cn.json
> +  "entity.the_flesh_that_hates.flesh_suffer": "血肉磨难者",
```suggestion
  "entity.the_flesh_that_hates.flesh_suffer": "血肉受难者",

```
译出“受”意更好

2024-06-25 10:26 UTC, SlimeSB commented on projects/1.20/assets/the-flesh-that-hates/the_flesh_that_hates/lang/zh_cn.json
> +  "entity.the_flesh_that_hates.plaqueincubatorone": "血肉传染者 起源阶段",
Incubator 考虑译作温床等，与上文避讳。此二者务必重译

2024-06-25 10:26 UTC, SlimeSB commented on projects/1.20/assets/the-flesh-that-hates/the_flesh_that_hates/lang/zh_cn.json
> +  "entity.the_flesh_that_hates.plaquethreelegcreature": "血肉子宫",
应为hysteric变体，不知道怎么个变法。重译

2024-06-25 10:26 UTC, SlimeSB commented on projects/1.20/assets/the-flesh-that-hates/the_flesh_that_hates/lang/zh_cn.json
> +  "item.the_flesh_that_hates.logo": "乐高",
...

2024-06-25 10:26 UTC, SlimeSB commented on projects/1.20/assets/the-flesh-that-hates/the_flesh_that_hates/lang/zh_cn.json
> +  "item.the_flesh_that_hates.nervous_system": "神经",
```suggestion
  "item.the_flesh_that_hates.nervous_system": "神经系统",

```

2024-06-25 10:26 UTC, SlimeSB commented on projects/1.20/assets/the-flesh-that-hates/the_flesh_that_hates/lang/zh_cn.json
> +  "item.the_flesh_that_hates.piece_of_flesh_cooked": "煮熟的肉块",
与line 106保持一致。建议均改为血肉碎块

2024-06-25 10:26 UTC, SlimeSB commented on projects/1.20/assets/the-flesh-that-hates/the_flesh_that_hates/lang/zh_cn.json
> +  "item.the_flesh_that_hates.fossa_disc": "腘窝碎片",
唉disc……重译

2024-06-25 10:26 UTC, SlimeSB commented on projects/1.20/assets/the-flesh-that-hates/the_flesh_that_hates/lang/zh_cn.json
> +  "block.the_flesh_that_hates.flesh_canals": "瘘管",
canal也指消化道，似乎并未实装。
考虑重译

2024-06-25 10:26 UTC, SlimeSB commented on projects/1.20/assets/the-flesh-that-hates/the_flesh_that_hates/lang/zh_cn.json
> +  "block.the_flesh_that_hates.flesh_coublestone": "血肉浸染的圆石",
方块的 血肉浸染→血肉 吧。特别是树一类是自然长的，没有“浸染”
生物的可保留

2024-06-25 10:26 UTC, SlimeSB commented on projects/1.20/assets/the-flesh-that-hates/the_flesh_that_hates/lang/zh_cn.json
> +  "block.the_flesh_that_hates.tumor": "肿块",
purulent译作脓块
purulent tumor译作脓瘤块
tumor译作瘤块
上文没仔细推敲导致的。

2024-07-13 02:13 UTC, SlimeSB commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。
- @Xinshou233

2024-08-23 07:31 UTC, SlimeSB approved these changes

2024-08-26 18:03 UTC, merged