Embeddium 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4444
Opened 2024-06-19 18:04 UTC by 258654aun

2024-06-23 16:09 UTC, DrIceTea123 commented
疑似机翻，有意移除部分机翻痕迹（如`块->方块`），但仍有较强机翻风格
证据如下：
L15：
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/111784151/0a6628bb-cbce-44d0-a349-92105a1bf136)
L16：
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/111784151/731a8f60-cd7a-4d93-8155-585d30e2c661)
L35：
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/111784151/75095a5f-2e56-4b35-91c3-b887b2e2ecd7)
L37：
![image](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/111784151/3a412f85-4338-4ed7-a3f0-7bea64680a76)

疑似使用类似OpenAI的API和某语料库生成。建议拒绝此pr提交，同时检查该作者其他pr和既往贡献内容，排查AI机翻可能。
由于语料库的存在，相对而言长难句更适合鉴别AI机翻，可从此方面着手。个人初查#4111 同样有疑似机翻痕迹，但不确定。

2024-06-23 16:15 UTC, qznfbnj commented
仅供参考：https://github.com/embeddedt/embeddium/pull/151/commits/d8536609a6c999c6e274746dbb066a75ee411e61

2024-06-23 16:29 UTC, 258654aun commented
我英语不是很好，所以有些地方是使用机器翻译+人工修改

2024-06-23 16:36 UTC, DrIceTea123 commented
依然不是提交疑似生成式AI内容pr的理由
请修改或关闭此pr

2024-06-23 17:08 UTC, 258654aun commented
参考了已有的rubidium翻译和实际效果,重新对中文翻译进行了润色

2024-06-23 17:44 UTC, 258654aun commented
第36~39行是直接使用的模组自带的翻译

2024-06-23 17:53 UTC, qznfbnj commented
> 第36~39行是直接使用的模组自带的翻译

对，我干的

2024-08-01 11:49 UTC, 258654aun commented
更新语言文件及翻译至0.3.28版本

2024-08-10 11:02 UTC, 258654aun reviewed
添加1.21版本语言文件及翻译

2024-09-05 02:39 UTC, luoxueyasha requested changes

2024-09-05 02:39 UTC, luoxueyasha commented on projects/1.20/assets/embeddium/embeddium/lang/zh_cn.json
> +	"embeddium.options.added_by_mod_string": "由下列模组添加: %s",
```suggestion
	"embeddium.options.added_by_mod_string": "由下列模组添加：%s",
```
标点符号应使用规范的汉语全角标点符号，具体要求请阅读我们的 [翻译规范](https://cfpa.site/TransRules/) 中 **03.标点符号** 这一节。
诸如这类的问题请在您翻译的所有文件中全部查明并修改。

2024-09-05 02:39 UTC, luoxueyasha commented on projects/1.20/assets/embeddium/sodium/lang/zh_cn.json
> +	"sodium.option_impact.extreme": "极限",
？
解释一下为何翻译成极限，什么语境下出现这个key

2024-09-05 02:39 UTC, luoxueyasha commented on projects/1.20/assets/embeddium/sodium/lang/zh_cn.json
> +	"sodium.options.gui_scale.tooltip": "设置用于用户界面的最大缩放比例。 如果使用“自动”，则将始终使用最大比例。",
`使用“自动”`指？

2024-09-05 02:39 UTC, luoxueyasha commented on projects/1.20/assets/embeddium/sodium/lang/zh_cn.json
> +	"sodium.options.biome_blend.value": "%s区块",
确定是区块？

2024-09-05 04:22 UTC, qznfbnj commented on projects/1.20/assets/embeddium/sodium/lang/zh_cn.json
> +	"sodium.options.gui_scale.tooltip": "设置用于用户界面的最大缩放比例。 如果使用“自动”，则将始终使用最大比例。",
选中“自动”选项=使用“自动”=设置为“自动”

2024-09-05 04:24 UTC, qznfbnj commented on projects/1.20/assets/embeddium/sodium/lang/zh_cn.json
> +	"sodium.options.biome_blend.value": "%s区块",
Block=区块，但是非MC语境

2024-09-05 06:39 UTC, 258654aun commented on projects/1.20/assets/embeddium/sodium/lang/zh_cn.json
> +	"sodium.option_impact.extreme": "极限",
性能影响，在一些选项的介绍里出现，但是extreme没出现过，所以之前没注意，应该翻译成“极高”

2024-09-05 06:41 UTC, 258654aun commented on projects/1.20/assets/embeddium/sodium/lang/zh_cn.json
> +	"sodium.options.gui_scale.tooltip": "设置用于用户界面的最大缩放比例。 如果使用“自动”，则将始终使用最大比例。",
使用“自动”选项

2024-09-05 06:49 UTC, 258654aun commented on projects/1.20/assets/embeddium/sodium/lang/zh_cn.json
> +	"sodium.options.biome_blend.value": "%s区块",
是方块

2024-09-05 07:37 UTC, luoxueyasha requested changes
我们的库里**拒绝**接收机器翻译（含生成式 AI）、生硬翻译。（见[贡献方针](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)）。

请自行查明全文可能存在的生硬翻译与语病问题并修改。您可能需要[翻译资源库](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/README.md)或[翻译腔修正帮助](https://zh.m.wikipedia.org/wiki/Wikipedia:%E7%BF%BB%E8%AF%91%E8%85%94)。

2024-09-05 07:37 UTC, luoxueyasha commented on projects/1.20/assets/embeddium/embeddium/lang/zh_cn.json
> +	"embeddium.search_bar_empty": "搜索选项……",
游戏内的显示效果？（需要截图）
原版有三个点的省略号的情况，具体看情况而定

2024-09-05 07:37 UTC, luoxueyasha commented on projects/1.20/assets/embeddium/embeddium/lang/zh_cn.json
> +  	"embeddium.options.use_quad_normals_for_lighting.name": "使用精确的四边形着色",
这里留个疑问，可能需要对渲染术语熟悉的人看一眼
原文`Use Accurate Quad Shading`，key名          `use_quad_normals_for_lighting`

2024-09-05 07:37 UTC, luoxueyasha commented on projects/1.20/assets/embeddium/embeddium/lang/zh_cn.json
> +	"embeddium.options.use_quad_normals_for_lighting.tooltip": "启用后，Embeddium将根据非原版方块面朝向的真实方向（而不是其轴对齐方向）对它们应用阴影。当禁用Forge实验光源管线时，此选项可以提高光照质量（建议开启以获得最佳性能）。\n\n如果启用了实验光源管线，则此选项不起作用。"
同上，里面apply shading
可能是阴影，也可能是着色器

2024-09-05 07:37 UTC, luoxueyasha commented on projects/1.20/assets/embeddium/sodium/lang/zh_cn.json
> +	"sodium.options.biome_blend.tooltip": "控制对生物群落进行采样以进行方块着色的范围。较高的值会大大增加加载区块所需的时间，从而减少质量改进。",
“从而减少质量改进“

2024-09-05 07:37 UTC, luoxueyasha commented on projects/1.20/assets/embeddium/sodium/lang/zh_cn.json
> +	"sodium.options.entity_distance.tooltip": "控制实体可以渲染到离玩家的最大距离。值越高，渲染距离越长，但会降低帧率。",
“控制实体可以渲染到离玩家的最大距离”

2024-09-05 07:37 UTC, luoxueyasha commented on projects/1.20/assets/embeddium/sodium/lang/zh_cn.json
> +	"sodium.options.vignette.tooltip": "如果启用，将在玩家的视图上呈现晕影效果。除非像素填充率受到限制，否则不太可能对帧率产生影响。",
“像素填充率”

2024-09-05 09:12 UTC, 258654aun commented on projects/1.20/assets/embeddium/embeddium/lang/zh_cn.json
> +	"embeddium.search_bar_empty": "搜索选项……",
![QQ20240905-171218](https://github.com/user-attachments/assets/a7aef72c-c938-440a-a566-bafe337f29c7)

2024-09-05 09:26 UTC, 258654aun commented on projects/1.20/assets/embeddium/sodium/lang/zh_cn.json
> +	"sodium.options.vignette.tooltip": "如果启用，将在玩家的视图上呈现晕影效果。除非像素填充率受到限制，否则不太可能对帧率产生影响。",
fill-rate一般指的就是像素填充率

2024-09-05 09:31 UTC, 258654aun commented on projects/1.20/assets/embeddium/embeddium/lang/zh_cn.json
> +  	"embeddium.options.use_quad_normals_for_lighting.name": "使用精确的四边形着色",
这个之前查过，指的应该就是四边形着色器，下面那个阴影确实搞错了

2024-09-05 09:47 UTC, 258654aun commented on projects/1.20/assets/embeddium/sodium/lang/zh_cn.json
> +	"sodium.options.vignette.tooltip": "如果启用，将在玩家的视图上呈现晕影效果。除非像素填充率受到限制，否则不太可能对帧率产生影响。",
但有的时候也指纹理填充率，这里我还是就写成填充率吧

2024-09-05 09:54 UTC, 258654aun commented on projects/1.20/assets/embeddium/embeddium/lang/zh_cn.json
> +	"embeddium.options.use_quad_normals_for_lighting.tooltip": "启用后，Embeddium将根据非原版方块面朝向的真实方向（而不是其轴对齐方向）对它们应用阴影。当禁用Forge实验光源管线时，此选项可以提高光照质量（建议开启以获得最佳性能）。\n\n如果启用了实验光源管线，则此选项不起作用。"
是着色器

2024-10-12 07:04 UTC, luoxueyasha reviewed
平时忙 处理消息不及时抱歉

2024-10-12 07:04 UTC, luoxueyasha commented on projects/1.20/assets/embeddium/sodium/lang/zh_cn.json
> +	"sodium.options.use_compact_vertex_format.tooltip": "启用后，游戏将使用更紧凑的顶点格式来渲染区块。这可以显著减少显存使用和带宽需求，尤其是对于集成显卡而言。但是，由于它降低了位置和纹理坐标属性的精度，可能会导致一些资源包出现深度冲突（z-fighting）的问题。",
漏翻
原文最后`Disabling this has no effect if Oculus is installed.`

2024-10-12 07:04 UTC, luoxueyasha commented on projects/1.20/assets/embeddium/sodium/lang/zh_cn.json
> +	"sodium.options.mipmap_levels.tooltip": "控制用于方块模型纹理的MipMap的数量。较高的值可以更好地呈现远处的方块，但可能会对许多纹理动画的性能产生不利影响。",
```suggestion
	"sodium.options.mipmap_levels.tooltip": "控制用于方块模型纹理的Mipmap的数量。较高的值可以更好地呈现远处的方块，但可能会对许多纹理动画的性能产生不利影响。",
```
一般来说mipmap纯小写
大写也仅大写首字母

2024-10-13 12:38 UTC, 258654aun commented
已修正

2024-10-13 14:22 UTC, luoxueyasha submitted a review, later dismissed
我觉得可了

2024-10-15 14:32 UTC, SlimeSB reviewed
跨版本一致性问题，顺便干掉typo

2024-10-15 14:32 UTC, SlimeSB commented on projects/1.20/assets/embeddium/sodium/lang/zh_cn.json
> +	"sodium.options.gui_scale.tooltip": "设置用于用户界面的最大缩放比例。 如果设置为“自动”，则将始终使用最大比例。",
```suggestion
	"sodium.options.gui_scale.tooltip": "设置用于用户界面的最大缩放比例。如果设置为“自动”，则将始终使用最大比例。",
```

2024-10-15 14:32 UTC, SlimeSB commented on projects/1.21/assets/embeddium/embeddium/lang/zh_cn.json
> +	"sodium.options.use_fog_occlusion.tooltip": "如果启用，则不会渲染被雾完全隐藏的方块，这有助于提高性能。当雾效果较重时（例如在水下），性能提升可能会更加显著。但在某些情况下可能会导致天空和雾之间出现不良的视觉伪影。",
```suggestion
	"sodium.options.use_fog_occlusion.tooltip": "如果启用，则不会渲染被雾完全隐藏的方块，这有助于提升性能。当雾效果较重时（例如在水下），性能提升可能会更加显著。但在某些情况下可能会导致天空和雾之间出现不良的视觉伪影。",
```

2024-10-15 14:32 UTC, SlimeSB commented on projects/1.20/assets/embeddium/sodium/lang/zh_cn.json
> +	"sodium.options.use_fog_occlusion.tooltip": "如果启用，则不会渲染被雾完全隐藏的方块，这有助于提升性能。当雾效果较重时（例如在水下），性能提升可能会更加显着。但在某些情况下，它可能会导致天空和雾之间出现不良的视觉伪影。",
```suggestion
	"sodium.options.use_fog_occlusion.tooltip": "如果启用，则不会渲染被雾完全隐藏的方块，这有助于提升性能。当雾效果较重时（例如在水下），性能提升可能会更加显著。但在某些情况下可能会导致天空和雾之间出现不良的视觉伪影。",
```

2024-10-15 14:32 UTC, SlimeSB commented on projects/1.21/assets/embeddium/embeddium/lang/zh_cn.json
> +	"sodium.options.use_persistent_mapping.tooltip": "如果启用，少量内存将持久映射为区块上传的暂存缓冲区，有助于减少加载或更新区块时的CPU占用和帧生成时间的不稳定。\n\n需要OpenGL 4.4或ARB_buffer_storage。",
```suggestion
	"sodium.options.use_persistent_mapping.tooltip": "如果启用，少量内存将持久映射为区块上传的暂存缓冲区，有助于减少加载或更新区块时的CPU占用和帧生成时间的不稳定的情况。\n\n需要OpenGL 4.4或ARB_buffer_storage。",
```

2024-10-15 14:32 UTC, SlimeSB commented on projects/1.21/assets/embeddium/embeddium/lang/zh_cn.json
> +	"sodium.console.pojav_launcher": "Embeddium不支持PojavLauncher。\n  * 你很可能会遇到极端的性能问题、图形错误和崩溃。\n  * 如果决定继续，你将独自一人⸺我们不会帮助你解决任何错误或崩溃！",
```suggestion
	"sodium.console.pojav_launcher": "Embeddium不支持PojavLauncher。\n  * 你很可能会遇到极端的性能问题、图形错误和崩溃。\n  * 如果决定继续，你将独自一人——我们不会帮助你解决任何错误或崩溃！",
```

2024-10-15 15:26 UTC, 258654aun reviewed
已修正

2024-10-15 16:05 UTC, SlimeSB approved these changes

2024-10-17 06:38 UTC, merged