资源蜜蜂 Productive Bees 1.20汉化（本体+帕秋莉手册）
CFPAOrg/Minecraft-Mod-Language-Package pull request #4457
Opened 2024-06-25 11:50 UTC by Sunday40847

基于1.19的文件新增了1.20的新内容。
暂存的问题：两只蜜蜂的名字 WannaBee 和 Sky Steel Bee 怎么翻译？

帕秋莉手册大体基于 #4111 的内容（基本是机翻），我在这个基础上加以润色。

2024-07-19 03:19 UTC, luoxueyasha reviewed
看不动

2024-07-19 03:19 UTC, luoxueyasha commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "advancements.husbandry.fishy_bees.title": "可疑嗡嗡",
原文`Fishy Bees-ness`
谐音fishy business，这个双关需要讨论

2024-07-19 03:23 UTC, Sunday40847 commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "advancements.husbandry.fishy_bees.title": "可疑嗡嗡",
这是直接从旧版本拷来的，没动过。你们看看要改不

2024-07-19 07:21 UTC, luoxueyasha commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "advancements.husbandry.fishy_bees.title": "可疑嗡嗡",
应该得新帐旧帐一起算……？
要不然先看新增的得了

2024-09-04 18:16 UTC, ChuijkYahus reviewed
主文件到L756

2024-09-04 18:16 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.bohrium_bee": "𬭛蜜蜂",
```suggestion
  "entity.productivebees.bohrium_bee": "[[钅波]]蜜蜂",
```
等一个审核看海需不需要换成这样，先不改

2024-09-04 18:16 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.nihonium_bee": "镍蜜蜂",
```suggestion
  "entity.productivebees.nihonium_bee": "[[钅尔]]蜜蜂",
```

2024-09-04 18:16 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.ludicrite_bee": "纯镥蜜蜂",
```suggestion
  "entity.productivebees.ludicrite_bee": "镠蜜蜂",
```
Big Reactors的镠

2024-09-04 18:16 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.insanite_bee": "含水蜜蜂",
这三种蜜蜂对应物品的中文翻译缺失，均来自Extreme Reactors或Big Reactors

2024-09-04 18:16 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.arcane_crystal_bee": "奥秘蜜蜂",
```suggestion
  "entity.productivebees.arcane_crystal_bee": "神秘蜜蜂",
```
Forbidden & Arcanus的神秘水晶

2024-09-04 18:16 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.deorum_bee": "迪奥鲁姆蜜蜂",
```suggestion
  "entity.productivebees.deorum_bee": "圣金蜜蜂",
```
Forbidden & Arcanus的圣金

2024-09-04 18:16 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.stellarite_bee": "流星蜜蜂",
```suggestion
  "entity.productivebees.stellarite_bee": "陨星蜜蜂",
```
FAA的陨星

2024-09-04 18:16 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.soul_infused_bee": "灵魂注入蜜蜂",
```suggestion
  "entity.productivebees.soul_infused_bee": "注灵蜜蜂",
```
Thermal Extra的注灵

2024-09-04 18:16 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.twinite_bee": "双子蜜蜂",
```suggestion
  "entity.productivebees.twinite_bee": "双子物质蜜蜂",
```
Thermal Extra的双子物质

2024-09-04 18:16 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.sky_steel_bee": "Sky Steel蜜蜂",
```suggestion
  "entity.productivebees.sky_steel_bee": "陨钢蜜蜂",
```
MEGA Cells的陨钢

2024-09-04 18:18 UTC, ChuijkYahus commented
请注意更新英文文件，同时统一中文文件缩进

2024-09-04 23:32 UTC, Sunday40847 commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.neon_cuckoo_bee": "杜鹃蜜蜂",
这应该是资源蜜蜂原创的一个，而且不是干活生产蜜脾的。我直接从旧版本的汉化复制过来，它当时就叫这个

2024-09-05 07:11 UTC, luoxueyasha commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "block.productivebees.slimy_nest": "史莱姆蜂巢",
黏液or粘液

2024-09-05 07:13 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "block.productivebees.slimy_nest": "史莱姆蜂巢",
![494bd4a0d507b5e2ff554c0ad1b790d1](https://github.com/user-attachments/assets/32df37bb-8fa9-4b32-9184-e0c5748d3e51)
是用黏液块做的

2024-09-05 08:30 UTC, ChuijkYahus reviewed
元素名建议

2024-09-05 08:30 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.bohrium_bee": "𬭛蜜蜂",
结果出来了，最好改下，虽然有部分不改也没问题

2024-09-05 08:30 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.copernicium_bee": "钅哥蜜蜂",
```suggestion
  "entity.productivebees.copernicium_bee": "[[钅哥]]蜜蜂",
```

2024-09-05 08:30 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.darmstadtium_bee": "鐽蜜蜂",
```suggestion
  "entity.productivebees.darmstadtium_bee": "[[钅达]]蜜蜂",
```

2024-09-05 08:30 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.dubnium_bee": "𬭊蜜蜂",
```suggestion
  "entity.productivebees.dubnium_bee": "[[钅杜]]蜜蜂",
```

2024-09-05 08:30 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.flerovium_bee": "𫓧蜜蜂",
```suggestion
  "entity.productivebees.flerovium_bee": "[[钅夫]]蜜蜂",
```

2024-09-05 08:30 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.hassium_bee": "𬭶蜜蜂",
```suggestion
  "entity.productivebees.hassium_bee": "[[钅黑]]蜜蜂",
```

2024-09-05 08:30 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.livermorium_bee": "𫟷蜜蜂",
```suggestion
  "entity.productivebees.livermorium_bee": "[[钅立]]蜜蜂",
```

2024-09-05 08:30 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.meitnerium_bee": "䥑蜜蜂",
```suggestion
  "entity.productivebees.meitnerium_bee": "[[钅麦]]蜜蜂",
```

2024-09-05 08:30 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.oganesson_bee": "鿫蜜蜂",
```suggestion
  "entity.productivebees.oganesson_bee": "[[奥气]]蜜蜂",
```

2024-09-05 08:30 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.roentgenium_bee": "𬬭蜜蜂",
```suggestion
  "entity.productivebees.roentgenium_bee": "[[钅仑]]蜜蜂",
```

2024-09-05 08:30 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.rutherfordium_bee": "鑪蜜蜂",
```suggestion
  "entity.productivebees.rutherfordium_bee": "[[钅卢]]蜜蜂",
```

2024-09-05 08:30 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.seaborgium_bee": "𨭎蜜蜂",
```suggestion
  "entity.productivebees.seaborgium_bee": "[[钅喜]]蜜蜂",
```

2024-09-05 08:30 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.tennessine_bee": "鿬蜜蜂",
```suggestion
  "entity.productivebees.tennessine_bee": "[[石田]]蜜蜂",
```

2024-09-05 09:00 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "productivebees.information.bee_helmet.info3": "击打有%s%%的几率生成一只“神风特攻队”蜜蜂",
```suggestion
  "productivebees.information.bee_helmet.info3": "击打有%s%%的概率生成一只“神风特攻队”蜜蜂",
```
请全文件通查，后续不再指出

2024-09-05 09:00 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "productivebees.information.bee_helmet.info3": "击打有%s%%的几率生成一只“神风特攻队”蜜蜂",
```suggestion
  "productivebees.information.bee_helmet.info3": "受击时有%s%%的概率生成一只“神风特攻队”蜜蜂",
```
`概率`请全文件通查，后续不再指出

2024-09-05 09:00 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "productivebees.information.breeding_item": "繁殖需求: %s",
```suggestion
  "productivebees.information.breeding_item": "繁殖需求：%s",
```
半角标点请全文件通查，后续不再指出

2024-09-05 09:02 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "productivebees.information.jar.fill_tip": "用漏斗或管道把一个装有想展示蜜蜂的蜜蜂笼转移到罐子里面。",
```suggestion
  "productivebees.information.jar.fill_tip": "用漏斗或管道把内有蜜蜂的蜜蜂笼转移到罐子里面。",
```

2024-09-05 09:03 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "productivebees.information.upgrade.upgrade_bee_sampler": "慢慢地从来访蜜蜂身上提取基因而在过程中完全不伤害它们。\n可以安装多个升级来提升提取几率。",
```suggestion
  "productivebees.information.upgrade.upgrade_bee_sampler": "慢慢地从来访蜜蜂身上提取基因，过程中完全不会伤害它们。\n可以安装多个升级来提升提取概率。",
```

2024-09-05 09:04 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "productivebees.ingredient.description.ashy_mining_bee": "这种蜜蜂比较孤僻，它一般都独自生活在主世界的蜂巢里。查阅关于它的合成表来看看他会在哪些蜂巢中生成。",
```suggestion
  "productivebees.ingredient.description.ashy_mining_bee": "这种蜜蜂比较孤僻，它一般都独自生活在主世界的蜂巢里。查阅有关配方以了解它会在哪些蜂巢中生成。",
```
同句式统一修改，注意代词

2024-09-05 09:05 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "productivebees.ingredient.description.creeper_bee": "爆炸！当它生气的时候\n⋯⋯也可能是节食的时候。\n\n你应该把它单独隔离起来。",
```suggestion
  "productivebees.ingredient.description.creeper_bee": "它生气的时候会爆炸！\n……节食的时候也有可能。\n\n你应该把它单独隔离起来。",
```
省略号修改，全文件通查

2024-09-05 09:06 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "productivebees.ingredient.description.hoarder_bee": "如果你把东西放在地上，这只蜜蜂会把它们收集起来并储存在蜂箱里。可以携带比它的小表亲⸺⸺收集者蜜蜂更多的东西。",
```suggestion
  "productivebees.ingredient.description.hoarder_bee": "如果你把东西放在地上，这只蜜蜂会把它们收集起来并储存在蜂箱里。能比它的收集者蜜蜂小表亲携带更多的东西。",
```
注意破折号修改，全文件通查

2024-09-05 09:08 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "productivebees.ingredient.description.dragon_egg_hive": "一种为末影龙蜜蜂设计的特殊蜂箱，使得使用者可以收获到原本难以获得的末影龙蜜脾。\n生活在末地的龙蛋蜂巢中的末影龙蜜蜂不需要采蜜，因为它们会从空气中吸收到末影龙的精华。当在任意其他蜂巢工作时，末影龙蜜蜂就必须有另一个授粉来源。",
多出许多句，注意删除

2024-09-05 09:09 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "productivebees.ingredient.description.farmer_bee": "庄稼收获后留下一片狼藉。为了保持农场清洁，你可能想投资一只囤积者蜜蜂。",
```suggestion
  "productivebees.ingredient.description.farmer_bee": "会收割庄稼，但同时也留下一地狼藉。为了保持农场清洁，你可能想投资一只囤积者蜜蜂。",
```

2024-09-05 09:12 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "productivebees.ingredient.description.lumber_bee": "对原木有着巨大痴迷。",
```suggestion
  "productivebees.ingredient.description.lumber_bee": "对原木极为痴迷。",
```
微调，注意修改同句式

2024-09-05 09:12 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "productivebees.ingredient.description.nether_quartz_nest": "吸引下界的下界石英蜜蜂。为了吸引蜜蜂，蜂巢必须放在下界。",
```suggestion
  "productivebees.ingredient.description.nether_brick_nest": "吸引下界的岩浆蜜蜂。为了吸引蜜蜂，蜂巢必须放在下界。",
  "productivebees.ingredient.description.nether_quartz_nest": "吸引下界的石英蜜蜂。为了吸引蜜蜂，蜂巢必须放在下界。",
```
译名统一

2024-09-05 09:13 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "productivebees.ingredient.description.obsidian_nest": "艰苦的生活环境只适合一些末地原生的蜜蜂。",
```suggestion
  "productivebees.ingredient.description.obsidian_nest": "生活环境艰苦，只适合一些末地原生的蜜蜂。",
```

2024-09-05 09:15 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "productivebees.ingredient.description.rancher_bee": "在蜜蜂学校，它的绰号是“布比”。",
```suggestion
  "productivebees.ingredient.description.rancher_bee": "在蜜蜂学校，它的绰号是“奶香蜂”。",
```
BooBee音同boobie，指“胸部；乳房”

2024-09-05 09:16 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "productivebees.ingredient.description.skeletal_bee": "一定要让你的蜂箱保持明亮的光照，防止这家伙搬进来。",
```suggestion
  "productivebees.ingredient.description.skeletal_bee": "确保你的蜂箱照明良好，防止这家伙搬进来。",
```
与下方统一

2024-09-05 13:32 UTC, dovisutu commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "advancements.husbandry.fishy_bees.title": "可疑嗡嗡",
腥味十足的*蜂蜜*？
（还是有点牵强）

2024-09-05 13:42 UTC, dovisutu reviewed
感觉进度有的还是怪
提供了一点个人想法，可能也不算好

2024-09-05 13:42 UTC, dovisutu commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "advancements.husbandry.nest_locator.title": "找到嗡嗡声了",
不知道有没有*buzzword*的意思
*聚焦嗡点*

2024-09-05 13:42 UTC, dovisutu commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "advancements.husbandry.treat_on_stick.title": "带方向盘的嗡嗡",
*蜂向标*

2024-09-05 13:42 UTC, dovisutu commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "advancements.husbandry.calm_bee.title": "让它们头脑清醒",
*蜂口费*

2024-09-05 13:42 UTC, dovisutu commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "advancements.husbandry.convert_egg.title": "好消息：它不会孵出小龙",
```suggestion
  "advancements.husbandry.convert_egg.title": "幸好孵不出龙来",
```
稍微缩一下

2024-09-05 13:42 UTC, dovisutu commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "advancements.husbandry.feeding_slab.title": "我想要那个，那个，还有那个",
考虑表意
*(这花?)我全都要*
（来源：“小孩子才作选择”（

2024-09-05 13:42 UTC, dovisutu commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "advancements.husbandry.hive_upgrades.title": "计算一下，1，2，4",
原文：*Make it count, 1, 2, 4.*
但是我没看懂（

2024-09-06 01:29 UTC, Sunday40847 commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "block.productivebees.cherry_wood_nest": "樱木蜂巢",
总之都是自然生成的、蜜蜂居住的地方。都叫“巢”没有问题吧。 :P

2024-09-11 07:31 UTC, Sunday40847 commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "block.productivebees.cryo_stasis": "Cryo Stasis",
问了作者，这个方块尚未实装，我也不知道这是干嘛的。就不翻译了

2024-09-11 10:07 UTC, Sunday40847 commented
/update-en productivebees 1.20

2024-10-11 03:58 UTC, Sunday40847 commented
/update-en productivebees 1.21

2024-10-11 04:00 UTC, Sunday40847 commented
/update-en productivebees 1.21

2024-10-11 04:14 UTC, Sunday40847 commented
/update-en productivebees 1.21
~~前两次没创建文件夹就要更新语言文件，我是铸币~~

2024-10-11 16:51 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +	"item.productivebees.upgrade_productivity_4": "升级：产量Ω",
都行吧，阿尔法、贝塔、伽马、欧米伽，或者希腊字母直接上也行

2024-10-11 16:53 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "advancements.husbandry.hive_upgrades.title": "计算一下，1，2，4",
快来快来数一数，二四六七八（）

2024-10-11 18:47 UTC, ChuijkYahus requested changes
建议先自查一遍手册的翻译

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/blocks/breeding_chamber.json
> +            "text": "在这台机器里，您可以在安全的环境中繁殖蜜蜂。为机器提供两只亲本蜜蜂、它们各自的繁殖物品以及能量和为后代提供的空蜜蜂笼。您可以使用“升级：速度”来加快该过程。"
```suggestion
            "text": "这台机器能在安全的环境中繁殖蜜蜂。为机器提供两只亲本蜜蜂、它们各自的繁殖物品、能量，以及用于容纳子代的空蜜蜂笼。可以使用“升级：速度”来加快该过程。"
```

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/blocks/catcher.json
> +            "text": "捕捉器接受三种升级;$(l:items/upgrades#babee)升级：繁殖$(/l)将过滤掉成年蜜蜂，只捕捉幼蜂。$(l:items/upgrades#filter)升级：过滤$(/l)将只捕获过滤器上的蜜蜂。$(l:items/upgrades#range)升级：范围$(/l)将增加工作范围。可以安装多个“升级：范围”。"
```suggestion
            "text": "捕捉器接受三种升级。$(l:items/upgrades#babee)升级：繁殖$(/l)将过滤掉成年蜜蜂，只捕捉幼蜂。$(l:items/upgrades#filter)升级：过滤$(/l)将只捕获过滤器上的蜜蜂。$(l:items/upgrades#range)升级：范围$(/l)将增加工作范围。可以安装多个“升级：范围”。"
```

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/blocks/centrifuge.json
> +            "text": "将资源蜜脾分离成资源和蜂蜜。可容纳 10 桶可抽取的液体。离心机也能自动将流体输出到旁边的任何流体储存方块。动力离心机需要FE来以更高的速度运行。离心机还可用于将蜜蜂材料瓶中的遗传物质分离成$(l:genetics/transferring)基因$(/l)。"
```suggestion
            "text": "将资源蜜脾分离成资源和蜂蜜。可容纳 10 桶可抽取的液体。离心机也能自动将流体输出到旁边的任何流体储存方块。为动力离心机提供 FE，可让其以更高的速度运转。离心机还可将蜜蜂碾膏瓶中的遗传物质分离成$(l:genetics/transferring)基因$(/l)。"
```
蜜蜂碾膏为同步zh_cn中的译文，如采纳其他建议则跟随其更改

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/blocks/feeder.json
> +            "text": "喂食板可以倒上蜂蜜，如此就为蜜蜂提供了一个泡泡脚、从一天的漫长工作中恢复过来的好地方，即给予它们再生效果。"
```suggestion
            "text": "喂食板可以倒上蜂蜜，蜜蜂在经历一整天的辛劳后能在里面泡泡脚，好好休息。也即，给予它们生命恢复效果。"
```
生命恢复为原版术语

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/blocks/feeder.json
> +            "text": "由于$(l:items/upgrades#simulator)升级：模拟$(/l)只有 1 个花块位置，饲养板可以与它达成很好的配合，让您有最多 3 只不同的蜜蜂在蜂巢中工作。"
这里的flowerblock是专用名称吗

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/blocks/gene_indexer.json
> +            "text": "用你身边的所有基因装满这个额外的大容器，扳下拉杆，看着自动化的内部基因索引器为你组合基因。这可能不是最有效的方法……但它是自动化的！\n需要红石信号。"
```suggestion
            "text": "这个超大容器足够装下散落一地的基因样本，扳下开关，然后静待内部的基因索引器自动为你组合基因就好了。可能并不高效……但它能自动运作！$(br2)需要红石信号。"
```

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/blocks/gene_indexer.json
> +            "text": "你是否淹没在基因样本中？你还在通过通过合并基因来获得 RSI吗？那么这个方块就是为你准备的！"
```suggestion
            "text": "基因样本是不是多到完全无法招架？长时间手动组合基因有没有让你劳累不堪？那么这个方块就是为你准备的！"
```
RSI可能指重复性劳损（Repetitive strain injury）

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/blocks/honey_generator.json
> +            "text": "蜂蜜发电机接受两种升级： $(l:items/upgrades#productivity)升级：产量$(/l) 将降低蜂蜜消耗量。$(l:items/upgrades#speed)升级：速度$(/l) 将增加……速度。"
```suggestion
            "text": "蜂蜜发电机接受两种升级。$(l:items/upgrades#productivity)升级：产量$(/l)将降低蜂蜜消耗量。$(l:items/upgrades#speed)升级：速度$(/l)将增加……显然能增加速度。"
```

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/blocks/honey_generator.json
> +            "text": "燃烧蜂蜜以产生电力。蜂蜜可以通过管道输送，也可以在 GUI 中放入蜂蜜瓶、块和桶"
```suggestion
            "text": "燃烧蜂蜜以产生电力。蜂蜜可以通过管道输送，也可以在 GUI 中放入蜂蜜瓶、蜂蜜块和蜂蜜桶。"
```
可能还是写全好点

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +	"productivebees.honey_treat.invalid_use": "含有类型基因的蜂蜜小食不能喂给蜜蜂。",
```suggestion
	"productivebees.honey_treat.invalid_use": "含有类型基因的蜜蜂小食不能喂给蜜蜂。",
```
统一称呼

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/blocks/incubator.json
> +            "text": "厌倦了等待那些脆弱的小宝宝长大？使用培养箱来加速这个过程。只需将幼蜂放入笼子中，然后将其与一堆蜂蜜小食一起放入小蜜蜂孵化器里。"
```suggestion
            "text": "等那些脆弱的小宝宝长大等到昏天黑地？培养箱能够加速这个过程。将幼蜂放入笼子中，再将其与一堆蜜蜂小食一起放入小蜜蜂孵化器里即可。"
```

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/blocks/incubator.json
> +            "text": "孵化器的另一个用途是向卵中注入特定蜜蜂类型的$(l:genetics/collecting#crystalline)基因$(/l)以获得该蜜蜂类型的刷怪蛋。你获得的蜜蜂基因型会贯穿整个基因设置的过程。$(br)在制作刷怪蛋时只会使用这一种基因型，而蜂蜜小食上的任何其他基因都会丢失。"
```suggestion
            "text": "孵化器还有另一个用途，它能向卵中注入特定的蜜蜂类型$(l:genetics/collecting#crystalline)基因$(/l)，以获得该类型蜜蜂的刷怪蛋。这里的蜜蜂类型基因需在遗传学设施中制作。$(br)制作刷怪蛋时只会使用类型基因，蜜蜂小食上其他所有的基因都会丢失。"
```
真的是卵吗

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/genetics/attributes.json
> +            "text": "生产力水平较高的蜜蜂每次授粉会产生更多的蜜脾。$(br2)生产力水平分为:$(br)正常$(br)中$(br)高$(br)非常高"
```suggestion
            "text": "产量较高的蜜蜂每次授粉会产生更多的蜜脾。$(br2)生产力水平分为：$(br)正常$(br)中$(br)高$(br)很高"
```
全角冒号，本文件中不再指出，记得对照zh_cn中的译文

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/genetics/attributes.json
> +            "title": "生产力",
```suggestion
            "title": "产量",
```
title和zh_cn统一称呼，本文件通查

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/genetics/attributes.json
> +            "text": "通过将分离出来的基因放在蜜蜂小食上并将其喂给蜜蜂，可以将蜜蜂的属性从一只转移到另一只。$(br)请参阅有关$(l:genetics/collecting#crystalline)收集基因$(/l)的页面。"
```suggestion
            "text": "把分离出来的基因放在蜜蜂小食上，再喂给蜜蜂，即可将蜜蜂的属性从一只转移到另一只。$(br)请参阅有关$(l:genetics/collecting#crystalline)收集基因$(/l)的页面。"
```

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/genetics/collecting.json
> +            "text": "装瓶机配合活塞可用于装瓶蜜蜂。在中间放置一只蜜蜂并拉下拉杆。确保装瓶机里有空瓶子。将瓶装蜜蜂放入离心机中，将有用的东西与垃圾分离。"
```suggestion
            "text": "装瓶机配合活塞可用于装瓶蜜蜂。在中间放置一只蜜蜂并拉下拉杆。确保装瓶机里有空瓶子。将瓶装蜜蜂放入离心机中，就能从无用的垃圾中分离出有用的东西。"
```

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/genetics/transferring.json
> +            "text": "要将基因转移到蜜蜂身上，您需要将基因与蜜蜂小食相结合。将蜂蜜小食喂给蜜蜂，根据基因的纯度，蜜蜂将有机会获得新的属性。"
```suggestion
            "text": "要将基因转移到蜜蜂身上，需要把基因放到蜜蜂小食上。将蜜蜂小食喂给蜜蜂，蜜蜂将有机会获得新的属性，概率根据基因的纯度变化而变。"
```

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/genetics/transferring.json
> +            "text": "可以通过结合两个或更多相同的基因放入蜂蜜小食中来增加基因的纯度。"
```suggestion
            "text": "可以结合两个相同基因来增加基因纯度，也可选择放入更多同种基因。"
```

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/guide/start.json
> +            "text": "除了原版蜜蜂之外，你还会遇到一系列新蜜蜂，它们生活在极其隐蔽的$(l:hives/nests)蜂巢$(/l)中，位于主世界的不同生物群系里。这些蜜蜂是独居的，这意味着它们不会生活在蜂箱中。然而，它们的遗传学允许繁殖不同类型的蜜蜂，而且它们看起来很酷。"
```suggestion
            "text": "除了原版蜜蜂之外，你还会遇到一系列新蜜蜂，它们生活在极其隐蔽的$(l:hives/nests)蜂巢$(/l)中，位于主世界的不同生物群系里。这些蜜蜂是独居的，这意味着它们不会生活在蜂箱中。然而，它们的基因允许它们繁殖不同类型的蜜蜂，而且它们看起来很酷。"
```

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/hives/advanced_hives.json
> +            "text": "有许多高级蜂箱可供选择，具体取决于您的背包中是否有其他木材。"
```suggestion
            "text": "有许多高级蜂箱可供选择，具体取决于整合包中有何种木材。"
```

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/hives/nests.json
> +            "text": "蜂巢散布在世界各地，每个蜂巢都是一只独居蜜蜂的住处。可以直接打破蜂巢，蜜蜂会保留在蜂巢内，无需精准采集。要清除蜂巢内含有的蜜蜂和蛋，只需要把它自我合成一遍即可。"
这里是蛋吗

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/hives/nests.json
> +            "text": "如果你在空蜂巢中放入一份或多份蜜蜂小食，就会吸引来新的蜜蜂。手持蜂蜜小食右键点击来开始蜜蜂生成计时。"
```suggestion
            "text": "如果你在空蜂巢中放入一份或多份蜜蜂小食，就会吸引来新的蜜蜂。手持蜜蜂小食右击可让蜜蜂生成进入冷却。"
```

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/items/bee_helmet.json
> +            "text": "将蜂巢压在你绚丽的钻石头盔上，让它变得粘稠。巢中的蜜蜂肯定会习惯你，甚至会在你处于危险之中时保护你。穿上这件衣服也会向其他蜜蜂展示你的善意，并防止你收到它们的攻击。"
```suggestion
            "text": "往你绚丽的钻石头盔上压嵌一个蜂巢，能让头盔变得黏性十足。巢中的蜜蜂会与你成为朋友，甚至会在你处于危险之中时保护你。戴上它也能向其他蜜蜂展示善意，避免它们攻击你。"
```

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/items/honey_treat.json
> +            "text": "蜜蜂小食可以喂给愤怒的蜜蜂，让它们平静下来。将它们喂给小蜜蜂会使它们长得更快。$(br2)蜜蜂小食还可以与基因相结合，将遗传形状从一只蜜蜂转移到另一只蜜蜂。在$(l:genetics/transferring)遗传学$(/l)页面上阅读更多内容。"
```suggestion
            "text": "蜜蜂小食可以喂给愤怒的蜜蜂，让它们平静下来。喂给小蜜蜂会使它们长得更快。$(br2)蜜蜂小食还可以与基因相结合，以在蜜蜂间转移遗传性状。更多内容参阅$(l:genetics/transferring)遗传学$(/l)页面。"
```

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/items/nest_locator.json
> +            "text": "可以识别附近蜂巢的微弱嗡嗡声。按住Shift键并右键单击要查找的蜂巢或同种方块。如果要查找沙子蜂巢，可以右键单击沙子蜂巢或沙子。再次右键单击将找到附近任何该类型的蜂巢。"
```suggestion
            "text": "可以识别附近蜂巢的微弱嗡嗡声。使用需先 Shift 右击要搜查的蜂巢或同种方块。如果要搜查沙子蜂巢，可以右击沙子蜂巢或沙子。再次右击将会定位附近所有该类型的蜂巢。"
```

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/items/upgrades.json
> +            "text": "可用于:$(l:hives/advanced_hives#expanded)扩容盒$(/l),$(l:blocks/catcher)捕捉器$(/l)。",
```suggestion
            "text": "可用于：$(l:hives/advanced_hives#expanded)扩容盒$(/l)、$(l:blocks/catcher)捕捉器$(/l)。",
```
全角标点

2024-10-11 18:47 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/items/upgrades.json
> +            "text": "当安装在蜂巢中时，升级：繁殖将为生活在蜂巢内的蜜蜂提供很小的机会，无需您的参与即可繁殖和产生新的后代。请注意，通常情况下无法繁殖的蜜蜂不适用于此升级。$(br)当安装在$(l:blocks/catcher)捕捉器$(/l)中时，只有幼蜂会被捕获并放入笼子中。"
```suggestion
            "text": "在蜂巢中安装“升级：繁殖”后，其中蜜蜂有小概率自行繁殖并产生新的后代，无需你监督。请注意，通常情况下无法繁殖的蜜蜂不适用于此升级。$(br)当安装在$(l:blocks/catcher)捕捉器$(/l)中时，只有幼蜂会被捕获并放入笼子中。"
```

2024-10-11 18:49 UTC, ChuijkYahus commented
部分蜜蜂有现实物种对应，但大多数物种没有中文名，甚至有些的属也没有中文名
这些是按照俗名翻还是根据现有的属名造一个出来

2024-10-11 18:50 UTC, ChuijkYahus commented
部分蜜蜂有现实物种对应，但大多数物种没有中文名，甚至有些的属也没有中文名
这些是按照俗名翻还是根据现有的属名造一个出来

2025-03-01 15:54 UTC, Sunday40847 commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.insanite_bee": "含水蜜蜂",
我看了#2761 里这三个中前两个，分别叫“悖谬”和“空想”；MC百科上一篇Extreme Reactors模组1.16.5的教程对这两个材料维持当前叫法；第三个拿去搜，有一个法语词典网站把它翻译为“精神错乱”。对于一个材料名称来讲好怪啊！真的要这么翻译吗？

2025-03-01 16:02 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.insanite_bee": "含水蜜蜂",
很麻烦，但目前确实没有其他选项了

重晶石是barite，一种现实存在的矿物，肯定不行
inan翻译成无生命大概是用了inanimate在语法中的缩写，不知道语源是什么，但直接这么处理应该是不行的
insanite极大概率来自insane，含水不知从何而来，肯定不行

主要还是要这三种材料通过一个译名

2025-03-01 16:23 UTC, Sunday40847 commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/bees/worker/farmer.json
> +            "text": "收割附近的农作物并将其产物留在地上。它的收获半径是其所居住的蜂巢周围的4格方块，这个数值可以通过范围升级来增加。如果你安装了加入右键收获功能的模组，蜜蜂也会这样做。"
用第一个吧，然后 要不再额外加个括号说明一下是收割产物自动补种这样的

2025-03-01 16:25 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/bees/worker/farmer.json
> +            "text": "收割附近的农作物并将其产物留在地上。它的收获半径是其所居住的蜂巢周围的4格方块，这个数值可以通过范围升级来增加。如果你安装了加入右键收获功能的模组，蜜蜂也会这样做。"
原文如果没有，不用额外说明就好

2025-03-01 16:36 UTC, Sunday40847 commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/genetics/attributes.json
> +            "text": "通过将分离出来的基因放在蜜蜂小食上并将其喂给蜜蜂，可以将蜜蜂的属性从一只转移到另一只。$(br)请参阅有关$(l:genetics/collecting#crystalline)收集基因$(/l)的页面。"
这个实际上是把基因与蜜蜂小食合成。我自己改

2025-03-01 16:38 UTC, Sunday40847 commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/bees/hive/coal.json
> +            "text": "由$(l:bees/hive/redstone)红石蜜蜂$(/l)和$(l:bees/solitary/leafcutter)切叶蜜蜂$(/l)繁殖得到。",
是熔岩蜜蜂。对不起我自裁orz

2025-03-01 16:48 UTC, Sunday40847 commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/blocks/feeder.json
> +            "text": "由于$(l:items/upgrades#simulator)升级：模拟$(/l)只有 1 个花块位置，饲养板可以与它达成很好的配合，让您有最多 3 只不同的蜜蜂在蜂巢中工作。"
应该是说给蜂箱装了模拟升级后，蜂箱里的蜜蜂就只探测蜂箱面前这一格方块正下方是否是饲养板，这一格方块就叫flowerblock。可能是这样吧😥

2025-03-01 16:53 UTC, Sunday40847 commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/hives/nests.json
> +            "text": "蜂巢散布在世界各地，每个蜂巢都是一只独居蜜蜂的住处。可以直接打破蜂巢，蜜蜂会保留在蜂巢内，无需精准采集。要清除蜂巢内含有的蜜蜂和蛋，只需要把它自我合成一遍即可。"
额 改成“卵”吧

2025-03-01 16:55 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/blocks/feeder.json
> +            "text": "由于$(l:items/upgrades#simulator)升级：模拟$(/l)只有 1 个花块位置，饲养板可以与它达成很好的配合，让您有最多 3 只不同的蜜蜂在蜂巢中工作。"
可能还需要再测试
没关系先改别的位置，改完叫我我再看一遍

2025-03-01 17:13 UTC, Sunday40847 commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/bees/hive/coal.json
> +            "text": "由$(l:bees/hive/redstone)红石蜜蜂$(/l)和$(l:bees/solitary/leafcutter)切叶蜜蜂$(/l)繁殖得到。",
JEI里看是熔岩蜜蜂，而英文书里写的是烈焰蜜蜂，然后挂着红石蜜蜂的超链接😅

2025-03-01 17:15 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/bees/hive/coal.json
> +            "text": "由$(l:bees/hive/redstone)红石蜜蜂$(/l)和$(l:bees/solitary/leafcutter)切叶蜜蜂$(/l)繁殖得到。",
按实际表现来就行

2025-03-01 18:33 UTC, Sunday40847 commented
已经改正了除了核反应堆蜜蜂之外所有的文本！
此外还传了1.21的翻译，其中350，358~368，657~663，867，884~897，918，960，978~982，1047~1051行是新增的，有几条我不知道怎么搞，辛苦检查。🙏 @ChuijkYahus

2025-03-01 18:36 UTC, ChuijkYahus commented
明天来看

2025-03-02 03:33 UTC, Sunday40847 commented
/update-en productivebees 1.21

2025-03-02 14:15 UTC, ChuijkYahus reviewed
草了先发一下1211的极小部分审核意见
其余的可能需要装包进游戏测一下，大概明晚或者后天晚上？

2025-03-02 14:15 UTC, ChuijkYahus commented on projects/1.21/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.sky_osmium_bee": "Sky锇蜜蜂",
```suggestion
  "entity.productivebees.sky_bronze_bee": "陨青铜蜜蜂",
  "entity.productivebees.sky_osmium_bee": "陨锇蜜蜂",
```
来自MEGACells

2025-03-02 14:57 UTC, Sunday40847 commented on projects/1.21/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.phil_bee": "Philbee",
作者说此蜜蜂可以把石头转变成白色混凝土

2025-03-05 18:50 UTC, ChuijkYahus requested changes

2025-03-05 18:50 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/categories/bees_solitary.json
> +    "description": "独居蜜蜂的卵可以从在主世界的独居巢穴。$(br2)$(l:hives/nests)点此阅读蜂巢有关信息$(/l)。",
```suggestion
    "description": "独居蜜蜂的卵可以从主世界的独居巢穴中获取。$(br2)$(l:hives/nests)点此阅读蜂巢有关信息$(/l)。",
```

2025-03-05 18:50 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/categories/bees_worker.json
> +    "description": "除了生产资源的蜜蜂外，还有一些蜜蜂有特殊的任务。",
```suggestion
    "description": "除了生产资源的蜜蜂外，还有一些蜜蜂有特殊的本领。",
```

2025-03-05 18:50 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/bees/hive/withered.json
> +            "text": "通过向$(l:bees/hive/skeletal)骷髅蜜蜂$(/l)喂食一朵凋零玫瑰转化而来。",
```suggestion
            "text": "通过向$(l:bees/hive/skeletal)骷髅蜜蜂$(/l)喂食一朵凋灵玫瑰转化而来。",
```
全文件通查

2025-03-05 18:50 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/bees/hive/zombie.json
> +            "text": "如果将空的高级蜂箱放置在暗处，它会进入其中。",
```suggestion
            "text": "将空的高级蜂箱放置在暗处后，它会主动进入。",
```
与骷髅蜜蜂页面统一用语

2025-03-05 18:50 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/bees/solitary/reed.json
> +    "name": "甘蔗蜜蜂",
```suggestion
    "name": "芦苇蜜蜂",
```
这个应该更正为芦苇蜜蜂，注意en_us中的也应当修改，不要改漏

2025-03-05 18:50 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/bees/wild/magmatic.json
> +    "name": "熔岩蜜蜂",
```suggestion
    "name": "岩浆蜜蜂",
```
记得全文件通查，已经在其他文件里看见过错误位置了

2025-03-05 18:50 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/bees/worker/hoarder.json
> +            "text": "收集地上的物品并将它们放入蜂巢中，这是一种更酷、更好的$(l:bees/worker/collector)收集者蜜蜂$(/l)。$(br)与农夫蜜蜂相结合，可以形成一个自动化农场。"
```suggestion
            "text": "收集地上的物品并将它们放入蜂巢中，这是一种更酷、更好的$(l:bees/worker/collector)收集者蜜蜂$(/l)。$(br)与农夫蜜蜂配合，可以让农场自动化运作。"
```
与收集者蜜蜂页面统一用语

2025-03-05 18:50 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/blocks/catcher.json
> +            "text": "捕捉器接受三种升级。$(l:items/upgrades#babee)升级：繁殖$(/l)将过滤掉成年蜜蜂，只捕捉幼蜂。$(l:items/upgrades#filter)升级：过滤$(/l)将只捕获过滤器上的蜜蜂。$(l:items/upgrades#range)升级：范围$(/l)将增加工作范围。可以安装多个“升级：范围”。"
```suggestion
            "text": "捕捉器接受三种升级。$(l:items/upgrades#babee)升级：幼年蜂$(/l)将过滤掉成年蜜蜂，只捕捉幼蜂。$(l:items/upgrades#filter)升级：过滤$(/l)将只捕获过滤器中的蜜蜂。$(l:items/upgrades#range)升级：范围$(/l)将增加工作范围。可以安装多个“升级：范围”。"
```

2025-03-05 18:50 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/blocks/feeder.json
> +            "text": "由于$(l:items/upgrades#simulator)升级：模拟$(/l)只有 1 个花块位置，饲养板可以与它达成很好的配合，让您有最多 3 只不同的蜜蜂在蜂巢中工作。"
不改了，确保各个文件统一即可
```suggestion
            "text": "由于$(l:items/upgrades#simulator)升级：模拟$(/l)只有 1 个花块位置，饲养板可以与它达成很好的配合，让你有最多 3 只不同的蜜蜂在蜂巢中工作。"
```
求求了别再用您了

2025-03-05 18:50 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/blocks/incubator.json
> +            "text": "孵化器还有另一个用途，它能向卵中注入特定的蜜蜂类型$(l:genetics/collecting#crystalline)基因$(/l)，以获得该类型蜜蜂的刷怪蛋。这里的蜜蜂类型基因需在遗传学设施中制作。$(br)制作刷怪蛋时只会使用类型基因，蜜蜂小食上其他所有的基因都会丢失。"
```suggestion
            "text": "孵化器还有另一个用途，它能向蛋中注入特定的蜜蜂类型$(l:genetics/collecting#crystalline)基因$(/l)，以获得该类型蜜蜂的刷怪蛋。这里的蜜蜂类型基因需在遗传学设施中制作。$(br)制作刷怪蛋时只会使用类型基因，蜜蜂小食上其他所有的基因都会丢失。"
```
经检验，此处接受的是蛋的标签，鸡蛋之类的都可以

2025-03-05 18:50 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "config.jade.plugin_productivebees.bee_attributes": "特性",
```suggestion
  "config.jade.plugin_productivebees.bee_attributes": "属性",
```
与手册统一称呼

2025-03-05 18:50 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/genetics/attributes.json
> +            "text": "通常，蜜蜂会在下雨和雷暴时回到安全的蜂巢中。可以在恶劣天气下将蜜蜂拴在外面，从而使它们对恶劣的天气条件产生耐受性。但要注意，在它们习惯之前，它们有受到伤害和死亡的风险，所以要注意它们和手头的蜂蜜小食。"
```suggestion
            "text": "通常，蜜蜂会在下雨和雷暴时回到安全的蜂巢中。可以在恶劣天气下将蜜蜂拴在外面，从而使它们对恶劣的天气条件产生耐受性。但要注意，在它们变得耐受之前，它们有受到伤害和死亡的风险，所以要时刻保持注意，也要时刻备着蜜蜂小食。"
```

2025-03-05 18:50 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/genetics/attributes.json
> +            "text": "大多数蜜蜂只在白天工作，但这是可以改变的。在夜间拴住昼行蜜蜂，有机会让其变成夜行蜜蜂$(br)白天拴住夜行蜜蜂，有机会让它变成昼行蜜蜂$(br)小心，因为它们可能会在他们不习惯的环境中受到伤害。"
```suggestion
            "text": "大多数蜜蜂只在白天工作，但这是可以改变的。在夜间拴住昼行蜜蜂，有机会让其变成夜行蜜蜂。$(br)白天拴住夜行蜜蜂，有机会让它变成昼夜双行蜜蜂。$(br)小心，因为它们可能会在不习惯的环境中受到伤害。"
```

2025-03-05 18:50 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/genetics/attributes.json
> +            "text": "气候耐受度级别分为:$(br)无 - 只能在晴朗的天气下工作$(br)下雨 - 可以在下雨时工作$(br)任意 - 可以在任何天气下工作"
```suggestion
            "text": "气候耐受度级别分为：$(br)无 - 只能在晴朗的天气下工作$(br)下雨 - 可以在下雨时工作$(br)任意 - 可以在任何天气下工作"
```

2025-03-05 18:50 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/genetics/attributes.json
> +            "text": "习性级别分为:$(br)昼行 - 仅在白天工作$(br)夜行 - 仅在夜间工作$(br)昼夜双行 - 整天工作"
```suggestion
            "text": "习性级别分为：$(br)昼行 - 仅在白天工作$(br)夜行 - 仅在夜间工作$(br)昼夜双行 - 整天工作"
```

2025-03-05 18:53 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/genetics/attributes.json
> +            "text": "影响蜜蜂的最大生命值。$(br)凭借高耐力，蜜蜂有机会在攻击时不失去毒刺。$(br)耐力级别分为:$(br)虚弱$(br)正常$(br)中等$(br)强壮"
```suggestion
            "text": "影响蜜蜂的最大生命值。$(br)高耐力的蜜蜂在攻击时有概率不失去螫针。$(br)耐力级别分为：$(br)弱$(br)正常$(br)中$(br)强"
```

2025-03-05 18:54 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/genetics/attributes.json
> +            "text": "蜜蜂有不同的脾气，有些会一旦对上眼就攻击，有些会完全避免进行有害的互动。喂食了大量蜜蜂小食的蜜蜂会改善它的脾气。$(br)脾气级别分为:$(br)被动$(br)正常$(br)攻击性$(br)敌对"
```suggestion
            "text": "蜜蜂有不同的脾气，有些会一旦对上眼就攻击，有些会完全避免进行有害的互动。喂食了大量蜜蜂小食的蜜蜂会改善它的脾气。$(br)脾气级别分为：$(br)友好$(br)正常$(br)好斗$(br)敌意"
```

2025-03-05 19:00 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/hives/nests.json
> +            "text": "如果你在空蜂巢中放入一份或多份蜂蜜小食，就会吸引来新的蜜蜂。手持蜜蜂小食右击可让蜜蜂生成进入冷却。"
```suggestion
            "text": "如果你在空蜂巢中放入一份或多份蜜蜂小食，就会吸引来新的蜜蜂。手持蜜蜂小食右击可让蜜蜂生成进入冷却。"
```

2025-03-05 19:04 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/items/upgrades.json
> +            "text": "在蜂巢中安装“升级：繁殖”后，其中蜜蜂有小概率自行繁殖并产生新的后代，无需你监督。请注意，通常情况下无法繁殖的蜜蜂不适用于此升级。$(br)当安装在$(l:blocks/catcher)捕捉器$(/l)中时，只有幼蜂会被捕获并放入笼子中。"
```suggestion
            "text": "在蜂巢中安装“升级：幼年蜂”后，其中蜜蜂有小概率自行繁殖并产生新的后代，无需你监督。请注意，通常情况下无法繁殖的蜜蜂不适用于此升级。$(br)当安装在$(l:blocks/catcher)捕捉器$(/l)中时，只有幼蜂会被捕获并放入笼子中。"
```

2025-03-05 19:05 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/items/upgrades.json
> +            "text": "当安装在蜂箱中时，升级：产量将增加蜜蜂每次旅行产生的蜜脾数量。可以安装多个升级：产量。"
```suggestion
            "text": "当安装在蜂箱中时，升级：产量将增加蜜蜂每次旅行产生的蜜脾数量。可以安装多个“升级：产量”。"
```

2025-03-05 19:05 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/items/upgrades.json
> +            "text": "可用于：$(l:hives/advanced_hives#expanded)扩容盒$(/l), $(l:blocks/honey_generator)蜂蜜发电机$(/l)。",
```suggestion
            "text": "可用于：$(l:hives/advanced_hives#expanded)扩容盒$(/l)、$(l:blocks/honey_generator)蜂蜜发电机$(/l)。",
```

2025-03-05 19:06 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/items/upgrades.json
> +            "text": "可用于：$(l:hives/advanced_hives#expanded)扩容盒$(/l), $(l:blocks/centrifuge)离心机$(/l), $(l:blocks/incubator)小蜜蜂孵化器$(/l), $(l:blocks/honey_generator)蜂蜜发电机(/l)。",
```suggestion
            "text": "可用于：$(l:hives/advanced_hives#expanded)扩容盒$(/l)、$(l:blocks/centrifuge)离心机$(/l)、$(l:blocks/incubator)小蜜蜂孵化器$(/l)、$(l:blocks/honey_generator)蜂蜜发电机(/l)。",
```

2025-03-05 19:06 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/items/upgrades.json
> +            "text": "当安装在蜂巢中时，升级：速度将减少蜜蜂在蜂巢内停留的时间。$(br)当安装在$(l:blocks/centrifuge)离心机$(/l)或$(l:blocks/incubator)小蜜蜂孵化器$(/l)中时，将提高处理速度。"
```suggestion
            "text": "当安装在蜂巢中时，“升级：速度”将减少蜜蜂在蜂巢内停留的时间。$(br)当安装在$(l:blocks/centrifuge)离心机$(/l)或$(l:blocks/incubator)小蜜蜂孵化器$(/l)中时，将提高处理速度。"
```

2025-03-05 19:06 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/items/upgrades.json
> +            "text": "可用于：$(l:hives/advanced_hives#expanded)扩容盒$(/l),$(l:blocks/catcher)捕捉器$(/l)。",
```suggestion
            "text": "可用于：$(l:hives/advanced_hives#expanded)扩容盒$(/l)、$(l:blocks/catcher)捕捉器$(/l)。",
```

2025-03-05 19:10 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/items/upgrades.json
> +            "text": "当安装在蜂箱中时，可以传送的蜜蜂在生活在升级后的蜂箱中时将不再传送。"
```suggestion
            "text": "当安装在蜂箱中时，会传送的蜜蜂将不再传送。"
```

2025-03-05 19:11 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/items/upgrades.json
> +            "text": "当安装在蜂箱中时，每次访问都会提取一小块授粉蜜蜂样本，且不会伤害他们。可以在同一配置单元中安装多个以提高速率。"
```suggestion
            "text": "当安装在蜂箱中时，授粉蜜蜂每次造访都会被提取一小块样本，此过程不会伤害它们。可以在同一蜂箱中安装多个以提高速率。"
```

2025-03-05 19:13 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/misc/performance.json
> +            "text": "蜜蜂是世界上的实体，而不仅仅是一个方块或物品，它本质上会使用更多的电脑资源。来自实体的一大资源消耗是路径和 AI，其中蜜蜂的 AI 性能并不好。为了防止不必要的 AI 计算，请确保所有蜜蜂都有一个居住的地方和它们所需的采花点。还要把蜜蜂关在一个不太大的围栏里，否则它们会开始徘徊。或者，您可以在蜂巢中使用模拟器升级来防止蜜蜂实体出现在世界上。"
```suggestion
            "text": "蜜蜂是世界上的实体，而不仅仅是一个方块或物品，它本质上会使用更多的电脑资源。实体的寻路和 AI 会占用大量资源，其中蜜蜂的 AI 性能并不好。为了防止不必要的 AI 计算，请确保所有蜜蜂都有居住的地方和它们所需的采花点。还要把蜜蜂关在一个不太大的围栏里，不然它们会飞远。或者，可以在蜂巢中使用“升级：模拟”来防止蜜蜂实体出现在世界上。"
```

2025-03-05 19:25 UTC, ChuijkYahus requested changes
记得同步1.20.1和1.21.1
然后记得把zh_cn里每行的缩进对齐求求了，不要一边Tab一边空格

2025-03-05 19:25 UTC, ChuijkYahus commented on projects/1.21/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.chaotic_bee": "混沌蜜蜂",
我一开始居然没发现，记得同步到1.20.1
```suggestion
  "entity.productivebees.chaos_bee": "混沌蜜蜂",
  "entity.productivebees.chaotic_bee": "混沌锭蜜蜂",
```
混沌蜜蜂来自龙之进化，混沌锭蜜蜂来自L2

2025-03-05 19:25 UTC, ChuijkYahus commented on projects/1.21/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.phil_bee": "Philbee",
这个是某位油管主，建议“Phil蜜蜂”
https://www.youtube.com/watch?v=mpkd7FF1fYU

2025-03-05 19:25 UTC, ChuijkYahus commented on projects/1.21/assets/productivebees/productivebees/lang/zh_cn.json
> +  "productivebees.top.solitary.repopulation_countdown_inactive": "蜂巢是空的。对蜂巢使用蜂蜜小食来吸引蜜蜂。",
```suggestion
  "productivebees.top.solitary.repopulation_countdown_inactive": "蜂巢是空的。对蜂巢使用蜜蜂小食来吸引蜜蜂。",
```
建议enus整体查一遍

2025-03-06 00:10 UTC, Sunday40847 commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/blocks/feeder.json
> +            "text": "由于$(l:items/upgrades#simulator)升级：模拟$(/l)只有 1 个花块位置，饲养板可以与它达成很好的配合，让您有最多 3 只不同的蜜蜂在蜂巢中工作。"
WTF这个您替换漏了

2025-03-06 11:45 UTC, Sunday40847 commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/bees/solitary/reed.json
> +    "name": "甘蔗蜜蜂",
en_us为什么要改？那不是原文吗

2025-03-06 12:11 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/bees/solitary/reed.json
> +    "name": "甘蔗蜜蜂",
淦打错了，指的是zh_cn（）

2025-03-06 12:12 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/patchouli_books/guide/zh_cn/entries/blocks/incubator.json
> +            "text": "孵化器还有另一个用途，它能向卵中注入特定的蜜蜂类型$(l:genetics/collecting#crystalline)基因$(/l)，以获得该类型蜜蜂的刷怪蛋。这里的蜜蜂类型基因需在遗传学设施中制作。$(br)制作刷怪蛋时只会使用类型基因，蜜蜂小食上其他所有的基因都会丢失。"
其他位置不需要，但这个位置是因为拿来加工的物品是鸡蛋等，所以需要用蛋

2025-03-06 12:33 UTC, Sunday40847 commented on projects/1.21/assets/productivebees/productivebees/lang/zh_cn.json
> +  "productivebees.top.solitary.repopulation_countdown_inactive": "蜂巢是空的。对蜂巢使用蜂蜜小食来吸引蜜蜂。",
这怎么又是蜜蜂小食了

2025-03-06 12:44 UTC, ChuijkYahus commented on projects/1.21/assets/productivebees/productivebees/lang/zh_cn.json
> +  "productivebees.top.solitary.repopulation_countdown_inactive": "蜂巢是空的。对蜂巢使用蜂蜜小食来吸引蜜蜂。",
奇怪了，我在GitHubDev里看还有些位置是蜜蜂小食，这条当没看到吧，确定手册里所有都改过就行

2025-03-06 12:48 UTC, Sunday40847 commented
还有个WannaBee

2025-03-06 12:49 UTC, Sunday40847 commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.wanna_bee": "WannaBee",
还有这个

2025-03-06 13:48 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.wanna_bee": "WannaBee",
确实很难取，不知道“战利蜜蜂”怎么样

2025-03-06 13:49 UTC, Sunday40847 commented on projects/1.21/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.villager_bee": "Mistake",
关于这个……
![image](https://github.com/user-attachments/assets/304d672f-cf4e-4c9a-b88a-7cd3f3f4f579)

2025-03-06 15:22 UTC, ChuijkYahus commented
群内目前觉得进度还是按原样来先

2025-03-06 15:24 UTC, ChuijkYahus commented on projects/1.20/assets/productivebees/productivebees/lang/zh_cn.json
> +  "entity.productivebees.insanite_bee": "含水蜜蜂",
insanite群内讨论暂定为“癫狂”

2025-03-11 08:10 UTC, merged