TACZ:Plus 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4461
Opened 2024-06-26 16:06 UTC by liyuxiang-lyx

2024-06-27 01:06 UTC, liyuxiang-lyx commented
ps:第一次用，没想到更改会到pr来，随便写的更改

2024-06-27 01:07 UTC, liyuxiang-lyx commented
ps:第一次用，没想到新更改会同步到pr，随便写的更改

2024-06-27 01:44 UTC, luoxueyasha commented
需要移除.vscode/settings.json

2024-06-27 01:47 UTC, luoxueyasha commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "subtitles.exitdeadeye": "死神之眼退出",
```suggestion
    "subtitles.exitdeadeye": "死神之眼：退出",
```
字幕格式参考原版
此类问题请全文通查并修改

2024-06-27 01:47 UTC, luoxueyasha commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "gamerule.shakeDisable": "抖动",
游戏内的显示效果？
需要截图，github评论区可以直接贴

2024-06-27 04:07 UTC, liyuxiang-lyx commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "gamerule.shakeDisable": "抖动",
这b玩意(开着效果开不了物品栏)不好测试，等下

2024-06-27 04:15 UTC, liyuxiang-lyx commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "gamerule.shakeDisable": "抖动",
![屏幕截图 2024-06-27 121448](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/84612542/8eac17ff-aad1-4822-8ac9-ff79e717b89b)
效果

2024-06-27 04:20 UTC, liyuxiang-lyx commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "gamerule.shakeDisable": "抖动",
屑作者，en_us没写全

2024-06-27 04:28 UTC, liyuxiang-lyx commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "gamerule.shakeDisable": "抖动",
![屏幕截图 2024-06-27 122810](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/84612542/ba0982e4-6386-483d-a9b1-6a364c09ac73)
![Uploading 屏幕截图 2024-06-27 122757.png…]()

2024-06-27 04:32 UTC, liyuxiang-lyx commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "gamerule.shakeDisable": "抖动",
不是，这作者写的医疗包会出focus effect，但是又没用（）

2024-06-27 04:40 UTC, liyuxiang-lyx commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "gamerule.shakeDisable": "抖动",
![屏幕截图 2024-06-27 124002](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/84612542/c41a7d9d-570a-435b-95b8-080a45636585)

2024-06-27 05:06 UTC, liyuxiang-lyx commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "subtitles.exitdeadeye": "死神之眼退出",
改了

2024-06-27 08:13 UTC, luoxueyasha commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "gamerule.shakeDisable": "抖动",
我想看到的是`gamerule.shakeDisable`的显示位置及截图，及其功能
不是药水效果的显示情况

2024-06-27 08:20 UTC, luoxueyasha commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "subtitles.deadeyebeat": "死神之眼",
这个deadeyebeat和别的deadeye有啥区别吗

2024-06-27 08:20 UTC, luoxueyasha commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "gamerule.deadeyeDisable": "禁用左倾",
原文`disables the deadeye time freeze mechanic`
显示位置，实际启用效果？
死神之眼的效果是？
为什么翻译成`死神之眼`？

2024-06-27 08:20 UTC, luoxueyasha commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "item.taczplus.stim": "AI-2 医疗包"
```suggestion
    "item.taczplus.stim": "AI-2医疗包"
```
    在1.16或更高版本下，英文字母、阿拉伯数字等非中文文本无需在前后添加空格。
具体可见我们的 [翻译规范](https://cfpa.site/TransRules/) 中 **04.排版** 一节下。
诸如这类的问题请在您翻译的所有文件中全部查明并修改。

2024-06-27 13:14 UTC, liyuxiang-lyx commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "gamerule.shakeDisable": "抖动",
![Uploading 屏幕截图 2024-06-27 211357.png…]()

2024-06-27 13:14 UTC, liyuxiang-lyx commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "gamerule.shakeDisable": "抖动",
![屏幕截图 2024-06-27 211357](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/84612542/7a5ef9c4-9393-4d7f-80ef-76197d0f2b6c)

2024-06-27 13:16 UTC, liyuxiang-lyx commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "subtitles.deadeyebeat": "死神之眼",
我不到啊，mod作者写的是Deadeye(怀疑已弃用，正在测试)

2024-06-27 13:25 UTC, liyuxiang-lyx commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "subtitles.deadeyebeat": "死神之眼",
![屏幕截图 2024-06-27 212137](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/84612542/9e58a3c1-7d01-452d-989a-69d33f2e31e4)

2024-06-27 13:33 UTC, liyuxiang-lyx commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "gamerule.shakeDisable": "抖动",
![屏幕截图 2024-06-27 212137](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/84612542/f8254a68-33c3-4b06-ac46-da5c2aa87c36)

2024-06-27 13:40 UTC, liyuxiang-lyx commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "gamerule.deadeyeDisable": "禁用左倾",
![屏幕截图 2024-06-27 211357](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/84612542/a4d259e0-0961-4f3f-aa87-6b47e05d7e79)
实际启用效果是按死神之眼对应的按键没效果(甚至连特效都没了)
死神之眼效果:
![1](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/assets/84612542/e79c92b2-67e1-4b07-83d4-84b28a1f6788)
为什么翻译成死神之眼:作者说这个技能是受了荒野大镖客2的启发，按原游戏技能翻译(但是有的说是死神之眼，有的说是死亡之眼)

2024-06-27 13:49 UTC, liyuxiang-lyx commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "subtitles.deadeyebeat": "死神之眼",
"subtitles.deadeyebeat" "subtitles.deadeye"都没用
只有"subtitlesdeadeyebeatlouder"会出现

2024-06-27 13:59 UTC, liyuxiang-lyx commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "gamerule.shakeDisable": "抖动",
但是这个真没测出来，不知道干什么的，我按原文翻译的

2024-06-28 02:41 UTC, luoxueyasha requested changes

2024-06-28 02:41 UTC, luoxueyasha commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +{
不要删除没使用的key
哪怕你保留原文或者都翻了，也不要删除
因为假设有岁月史书，后面都是可以从这些文件和github记录里查到的

2024-06-28 10:44 UTC, liyuxiang-lyx commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +{
ok

2024-07-03 07:44 UTC, luoxueyasha submitted a review, later dismissed

2024-07-03 07:44 UTC, luoxueyasha commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "key.taczplus.deadeye": "死神之眼",
```suggestion
    "key.taczplus.deadeye": "死亡之眼",
```
看大表哥2一般是这么翻的
可不改

2024-07-03 07:44 UTC, luoxueyasha commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "gamerule.shakeDisable": "抖动禁用",
```suggestion
    "gamerule.shakeDisable": "禁用抖动",
```
应和原版格式保持同步
全文通查

2024-07-03 07:44 UTC, luoxueyasha commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +    "gamerule.deadeyeDisable.description": "死神之眼禁用",
漏翻原文，请全文通查

2024-07-03 12:47 UTC, liyuxiang-lyx commented
最近没时间搞了，暑假再搞

2024-07-03 13:27 UTC, luoxueyasha commented
算了，我来直接commit吧

2024-07-03 13:53 UTC, SlimeSB approved these changes

2024-07-03 13:54 UTC, ChuijkYahus commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +  "gamerule.deadeyeDisable.description": "禁用死神之眼以及其子弹时间效果",
确定会连效果本身也禁用吗

2024-07-03 13:55 UTC, luoxueyasha commented on projects/1.20/assets/tacz-plus-timeless-and-classics-feature-addon/taczplus/lang/zh_cn.json
> +  "gamerule.deadeyeDisable.description": "禁用死神之眼以及其子弹时间效果",
确定

2024-07-03 15:09 UTC, ChuijkYahus approved these changes

2024-07-12 23:44 UTC, merged