Integrated Scripting 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4472
Opened 2024-06-30 10:04 UTC by ChuijkYahus

使用的术语不一定准确
读起来可能会很不像中文

2024-07-14 14:53 UTC, ChuijkYahus commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "valuetype.integratedscripting.error.translation.unsupported_translateToNbt": "%s“%s”至NBT的转化不合法。",
`整型`“`100`”至NBT的转化不合法
`<变量类型名>`“`<变量值>`”至NBT的转化不合法

https://github.com/CyclopsMC/IntegratedScripting/blob/master-1.20/src/main/java/org/cyclops/integratedscripting/evaluate/translation/translator/ValueTranslatorObjectAdapter.java#L121

2024-07-14 14:54 UTC, ChuijkYahus commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "info_book.integratedscripting.introduction.text3": "比如，本模组可以极方便地定义复杂的物品列表过滤器；形如&o“可损失耐久度的、模组X添加的、对应只可由钻石镐破坏的方块的物品”“获取列表中堆叠数第二大的物品”&r的描述，均在其列。",
`只可由钻石镐破坏的方块所对应的物品`怎么样

2024-07-14 14:56 UTC, ChuijkYahus commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "script.integratedscripting.error.invalid_type": "磁盘%3$s的脚本文件“%2$s”中带有成员“%1$s”的脚本预期将暴露类型为%4$s的变量，而实际为%5$s。",
基本是指“将某个东西开放给外部访问”，不同地方意义不太一样，但习惯叫“暴露”，或者说我身边统计法统计出来是“暴露”

2024-07-14 14:57 UTC, ChuijkYahus commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "advancement.integratedscripting.scripting_drive": "他们看到我开着驱动器飙车",
鉴定为原歌词就蛮难整

2024-07-14 22:39 UTC, SlimeSB commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "info_book.integratedscripting.introduction.text3": "比如，本模组可以极方便地定义复杂的物品列表过滤器；形如&o“可损失耐久度的、模组X添加的、对应只可由钻石镐破坏的方块的物品”“获取列表中堆叠数第二大的物品”&r的描述，均在其列。",
```suggestion
  "info_book.integratedscripting.introduction.text3": "比如，本模组可以极方便地定义复杂的物品列表过滤器；形如&o“可损失耐久度的、模组X添加的、只可由钻石镐破坏的方块所对应的物品”“获取列表中堆叠数第二大的物品”&r的描述，均在其列。",

```

2024-07-15 03:49 UTC, SlimeSB commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "script.integratedscripting.error.invalid_type": "磁盘%3$s的脚本文件“%2$s”中带有成员“%1$s”的脚本预期将暴露类型为%4$s的变量，而实际为%5$s。",
后文译作了开放，是否需要统一

2024-07-15 04:59 UTC, ChuijkYahus commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "script.integratedscripting.error.invalid_type": "磁盘%3$s的脚本文件“%2$s”中带有成员“%1$s”的脚本预期将暴露类型为%4$s的变量，而实际为%5$s。",
那就统一吧
这里使用`暴露`的一个原因是模仿报错信息（）
```suggestion
  "script.integratedscripting.error.invalid_type": "磁盘%3$s的脚本文件“%2$s”中带有成员“%1$s”的脚本预期将开放类型为%4$s的变量，而实际为%5$s。",
```

2024-07-15 05:00 UTC, ChuijkYahus commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "info_book.integratedscripting.tutorials.introduction.text1": "本节包含了几份教程，可帮助你了解和学习&l联合脚本&r，也即用于创建脚本处理复杂操作的&l动态联合&r附加组件。",
```suggestion
  "info_book.integratedscripting.tutorials.introduction.text1": "本节包含了几份教程，可帮助你了解和学习&l联合脚本&r——用于创建脚本处理复杂操作的&l动态联合&r附加组件。",
```

2024-07-16 19:38 UTC, mamaruo requested changes
1-164 已阅

2024-07-16 19:38 UTC, mamaruo commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "info_book.integratedscripting.advanced.transient_storage.text5": "这些变量存在一个缺陷：它们的状态是瞬时的。也即，任何时刻的变量卡重插入，以及网络服务重启，都可能改变它们的值。",
| **审查级别** |
|--------------|
| 🔵 一般 / **阻止合并** |

原文：**An important catch to these variables is that their state is only transient. Concretely, this means that their values can be reset any time a variable card in the network is re-inserted, or when the server restarted.**
```suggestion
  "info_book.integratedscripting.advanced.transient_storage.text5": "这些变量存在一个重大缺陷：它们的状态是瞬时的。也即，其值会随着重新插拔变量卡和重启服务器而重置。",
```

2024-07-16 19:40 UTC, ChuijkYahus commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "script.integratedscripting.error.invalid_type": "磁盘%3$s的脚本文件“%2$s”中带有成员“%1$s”的脚本预期将开放类型为%4$s的变量，而实际为%5$s。",
“预期”这个是ID本体的翻译
expose改了

2024-07-16 19:44 UTC, ChuijkYahus commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "info_book.integratedscripting.disk.text1": "&l脚本磁盘&r的职能是存储脚本，使用时应当插入&l脚本驱动器&r。将几张&l变量卡&r和&l门山岩&r组合可制成此物品。",
后者
```suggestion
  "info_book.integratedscripting.disk.text1": "&l脚本磁盘&r的职能是存储脚本，使用时应当插入&l脚本驱动器&r。由一个&l门山岩&r和几张&l变量卡&r合成。",
```

2024-07-16 19:46 UTC, ChuijkYahus commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "info_book.integratedscripting.writing.variables.text2": "在JavaScript中创建值，再把它变成静态的&l变量卡&r，完成这一点的最简单方式便是：在JavaScript中使用&olet&r或&oconst&r声明一个变量。",
```suggestion
  "info_book.integratedscripting.writing.variables.text2": "在JavaScript中创建值，再把它变成静态的&l变量卡&r值，最直截了当的操作方式便是：在JavaScript中使用&olet&r或&oconst&r声明一个变量。",
```
删多了

2024-07-18 19:02 UTC, mamaruo reviewed
165-结束

2024-07-19 02:45 UTC, ChuijkYahus commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "info_book.integratedscripting.advanced.external_editing.text4": "如果你的文本编辑器有对应支持（现代IDE基本都有），在&l脚本终端&r内更新脚本文件后，外部编辑器中的文件也会同步更新。",
草是输入法问题

2024-07-19 02:46 UTC, ChuijkYahus commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "info_book.integratedscripting.tutorials.terminal.text2": "首先，合成一块&l脚本终端&r，放到连接至&l脚本驱动器&r的线缆上，再右击打开&l脚本终端&r。",
怪，可能打顺了

2024-07-19 18:41 UTC, mamaruo commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "info_book.integratedscripting.disk.text1": "&l脚本磁盘&r的职能是存储脚本，使用时应当插入&l脚本驱动器&r。将几张&l变量卡&r和&l门山岩&r组合可制成此物品。",
```suggestion
  "info_book.integratedscripting.disk.text1": "&l脚本磁盘&r的职能是存储脚本，使用时应当插入&l脚本驱动器&r。由&l门山岩&r和几张&l变量卡&r合成。",
```
最大化尊重原文且最小化歧义（（（
随意，都行，所谓尊重原文也有个度

2024-07-19 18:41 UTC, mamaruo approved these changes

2024-07-19 19:51 UTC, SlimeSB commented
审不了，我对编程教程写法一窍不通。

2024-07-24 10:40 UTC, mamaruo approved these changes

2024-07-29 06:00 UTC, mamaruo commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "advancement.integratedscripting.scripting_drive.desc": "制作一台脚本驱动器，可由此将脚本加载至网络。",
| **审阅级别** |
|:--------------:|
|🔵 **一般** / 阻止合并|

原文：
- **------ On the Dynamics of Integration contents ------**
- **Mendesite Galore**
- **Craft a Mendesite block, which is a basic resource for Integrated Scripting.**
- **Not a floppy disk!**
- **Craft a Scripting Disk, which is used to store scripting data.**
- **They see me drivin'**
- **Craft a Scripting Drive, so you can load scripts into your network.**
```suggestion
  "_comment": "Achievements",
  "advancement.integratedscripting.mendesite": "门山岩井喷",
  "advancement.integratedscripting.mendesite.desc": "合成一块门山岩，它是联合脚本的基础资源。",
  "advancement.integratedscripting.scripting_disk": "不是软盘！",
  "advancement.integratedscripting.scripting_disk.desc": "合成一张脚本磁盘，用来存储脚本数据。",
  "advancement.integratedscripting.scripting_drive": "我，驱动",
  "advancement.integratedscripting.scripting_drive.desc": "合成一台脚本驱动器，可由此将脚本加载至网络。",
```

2024-07-29 06:26 UTC, SlimeSB commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "advancement.integratedscripting.scripting_drive.desc": "制作一台脚本驱动器，可由此将脚本加载至网络。",
制作与合成可不细究

2024-08-07 07:56 UTC, ChuijkYahus commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "advancement.integratedscripting.scripting_drive.desc": "制作一台脚本驱动器，可由此将脚本加载至网络。",
此处为参照库内IntegratedDynamics的翻译
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/projects/1.18/assets/integrated-dynamics/integrateddynamics/lang/zh_cn.json#L143

2024-08-09 11:36 UTC, SlimeSB submitted a review, later dismissed
看不懂，24h后合了

2024-08-12 06:15 UTC, mamaruo submitted a review, later dismissed

2024-08-12 06:55 UTC, dovisutu reviewed
javascript
后边集结等会看，先把这几个交了

2024-08-12 06:55 UTC, dovisutu commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "info_book.integratedscripting.writing.methods.text5": "接受两个及以上参数的全局函数，均可用作对象的方法，其中各参数的次序均向前移动一位。比如，全局函数&oitemstackStrength&r接受一个&8物品&0和一个&8方块&0参数，它同样也可作为&8物品&0的方法使用，此时只接受单个&8方块&0参数。",
```suggestion
  "info_book.integratedscripting.writing.methods.text1": "全局函数的语法较为繁琐。使用更为紧凑的&l对象方法&r有时可以简化脚本",
  "info_book.integratedscripting.writing.methods.text2": "在JavaScript中使用时，&8方块&0、&8物品s&0和&8流体s&0等对象类型均有对应&l方法&r。",
  "info_book.integratedscripting.writing.methods.text3": "对象方法与相应的普通函数一致，但在调用时会将对象绑定到首个参数上。",
  "info_book.integratedscripting.writing.methods.text4": "例如，全局函数&oitemstackStackable&r接受单个&8物品&0参数，并返回一个&9布尔型&0。相应的对象方法为&ostackable&r，不接受参数。",
  "info_book.integratedscripting.writing.methods.text5": "接受两个及以上参数的全局函数也有相应的对象方法：首个参数绑定至对象，其余参数顺延。比如，全局函数&oitemstackStrength&r接受一个&8物品&0和一个&8方块&0参数；在&8物品&0上的相应方法只接受后一&8方块&0参数",
```

2024-08-12 06:55 UTC, dovisutu commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "info_book.integratedscripting.writing.variables.text5": "在创建定值长字符串这种复杂值时，用JavaScript创建变量尤为实用，同样的任务&l逻辑编程器&r则很难做到。下方是创建此类变量的一些示例。",
```suggestion
  "info_book.integratedscripting.writing.variables.text1": "动态联合中常见的类型（比如&6整型&0、&9布尔型&0、&8物品&0）在JavaScript中均有对应类型，反之亦然。",
  "info_book.integratedscripting.writing.variables.text2": "要在JavaScript中创建值，再把它变成静态的&l变量卡&r值，最直截了当的操作方式便是在使用&olet&r或&oconst&r声明一个变量。",
  "info_book.integratedscripting.writing.variables.text3": "&olet&r声明的变量可在后续脚本中重新赋值。&oconst&r声明的变量无法再次赋值。",
  "info_book.integratedscripting.writing.variables.text4": "要在&l变量卡&r中使用该变量，需在脚本终端的编辑器中选中该变量的名称，然后往右侧槽位插入空&l变量卡&r。这张&l变量卡&r后续就可像其他变量卡一样使用，比如在&l显示器&r中展示。",
  "info_book.integratedscripting.writing.variables.text5": "用JavaScript创建变量适合用于难以用&l逻辑编程器&r编写的复杂值，例如定值长字符串。下方是创建此类变量的一些示例。",
```

2024-08-12 06:55 UTC, dovisutu commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "info_book.integratedscripting.writing.functions.text6": "下方是不同类型函数的创建示例。",
```suggestion
  "info_book.integratedscripting.writing.functions.text1": "作为动态联合的首要元素，&2运算符&0可以用JavaScript函数创建。",
  "info_book.integratedscripting.writing.functions.text2": "JavaScript中所有的函数创建方式都可用来创建&2运算符&0，&ofunction&r关键字和lambda函数均可。",
  "info_book.integratedscripting.writing.functions.text3": "函数接受一定数量的参数。在动态联合中运行时，传入的JavaScript值均由动态联合的变量转化而来。",
  "info_book.integratedscripting.writing.functions.text4": "要将JavaScript函数绑定为&2运算符&0，所需的操作过程与常量和变量无二：在脚本终端的编辑器中选中函数名，再绑定至&l变量卡&r。所有接受&2运算符&0的地方都能使用该值。",
  "info_book.integratedscripting.writing.functions.text5": "比如说，创建接受单个&8物品&0参数、返回&9布尔型&0的函数，在读取箱子中物品列表时，就可用作过滤&2运算符&0。",
  "info_book.integratedscripting.writing.functions.text6": "下方是不同类型函数的创建示例。",
```

2024-08-12 06:55 UTC, dovisutu commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "info_book.integratedscripting.writing.globals.text4": "通过&oidContext&r调用函数比较费空间，可以考虑将这些运算符存储到自定义的常量中去，示例见后。此外，还可以使用&o对象方法&r，这一内容详见下一条目。",
```suggestion
  "info_book.integratedscripting.writing.globals.text1": "编写JavaScript代码时，可以通过全局变量&oidContext&r下的&oops&r字段访问所有动态联合运算符。这些运算符均已转译为函数。在写新运算符时，可以借此方式使用自带的运算符。",
  "info_book.integratedscripting.writing.globals.text2": "比如，可以编写一个&8物品&0过滤器，以检验物品可堆叠，且堆叠数至少为16。示例如下。",
  "info_book.integratedscripting.writing.globals.text3": "如需查询运算符的名称，可以在&l逻辑编程器&r中查看运算符说明里的全局名称，或在本书的“逻辑编程”条目下查找。",
  "info_book.integratedscripting.writing.globals.text4": "通过&oidContext&r调用函数比较繁琐。可以考虑将这些运算符存储到自定义的常量中去，如后所示；此外，还可以使用&o对象方法&r，如下一条目所示。",
```

2024-08-12 06:55 UTC, dovisutu commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "info_book.integratedscripting.advanced.transient_storage.text6": "因此，这些值无法保证能永久存在。如果需要持久的数据存储方式，最好还是使用&l延迟器&r。",
transient暂态 --- persistent持久态
```suggestion
  "info_book.integratedscripting.advanced.transient_storage": "暂态存储",
  "info_book.integratedscripting.advanced.transient_storage.text1": "动态联合的设计基于函数式编程的原则，因此基本不存在记录状态的手段，除非使用&l延迟器&r等外部方式绕过这一限制。",
  "info_book.integratedscripting.advanced.transient_storage.text2": "JavaScript语言允许混用函数式编程和命令式编程，这一特性便可用于临时记录状态。",
  "info_book.integratedscripting.advanced.transient_storage.text3": "具体说来，如果在函数外部声明了可变变量（比如说用了&olet&r），该变量就可通过后续函数调用而修改。",
  "info_book.integratedscripting.advanced.transient_storage.text4": "基于这些暂态变量，可以做到统计函数调用次数、实时统计一系列值的平均数等工作。",
  "info_book.integratedscripting.advanced.transient_storage.text5": "需要强调的是，这些变量是暂态的而非持久的；具体而言，其值会随着重新插拔变量卡和重启服务器而重置。",
  "info_book.integratedscripting.advanced.transient_storage.text6": "因此，这些值无法保证能永久存在。如果需要持久的数据存储方式，最好还是使用&l延迟器&r。",
```

2024-08-15 09:56 UTC, dovisutu reviewed
typo小改，改完应该就可了

2024-08-15 09:56 UTC, dovisutu commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "info_book.integratedscripting.writing.variables.text2": "要在JavaScript中创建值，再把它变成静态的&l变量卡&r值，最直截了当的操作方式便是在使用&olet&r或&oconst&r声明一个变量。",
```suggestion
  "info_book.integratedscripting.writing.variables.text2": "要在JavaScript中创建值，再把它变成静态的&l变量卡&r值，最直截了当的操作方式便是使用&olet&r或&oconst&r声明一个变量。",
```
坏 删漏一个字

2024-08-15 09:56 UTC, dovisutu commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "info_book.integratedscripting.writing.methods.text1": "全局函数的语法较为繁琐。使用更为紧凑的&l对象方法&r有时可以简化脚本",
```suggestion
  "info_book.integratedscripting.writing.methods.text1": "全局函数的语法较为繁琐。使用更为紧凑的&l对象方法&r有时可以简化脚本。",
```

2024-08-15 09:56 UTC, dovisutu commented on projects/1.20/assets/integrated-scripting/integratedscripting/lang/zh_cn.json
> +  "info_book.integratedscripting.writing.methods.text5": "接受两个及以上参数的全局函数也有相应的对象方法：首个参数绑定至对象，其余参数顺延。比如，全局函数&oitemstackStrength&r接受一个&8物品&0和一个&8方块&0参数；在&8物品&0上的相应方法只接受后一&8方块&0参数",
```suggestion
  "info_book.integratedscripting.writing.methods.text5": "接受两个及以上参数的全局函数也有相应的对象方法：首个参数绑定至对象，其余参数顺延。比如，全局函数&oitemstackStrength&r接受一个&8物品&0和一个&8方块&0参数；在&8物品&0上的相应方法只接受后一&8方块&0参数。",
```

2024-08-15 11:27 UTC, dovisutu approved these changes

2024-08-17 08:39 UTC, merged