Tropicraft 1.18-1.20 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4487
Opened 2024-07-08 15:47 UTC by SummerFleur2997

2024-07-20 05:51 UTC, ChuijkYahus commented on projects/1.20/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "block.tropicraft.bamboo_potted_wither_rose": "竹制凋零玫瑰盆栽",
```suggestion
  "block.tropicraft.bamboo_potted_wither_rose": "竹制凋灵玫瑰盆栽",
```
此改动在1.19.3版本进行

2024-07-20 05:51 UTC, ChuijkYahus commented on projects/1.20/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "block.tropicraft.eel_grass": "鳗草",
是这个吗
https://www.iplant.cn/info/%E5%A4%A7%E5%8F%B6%E8%97%BB%E5%B1%9E

2024-07-20 05:51 UTC, ChuijkYahus commented on projects/1.20/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "block.tropicraft.sickle_seagrass": "木秆藻",
是这个吗
https://www.iplant.cn/info/Thalassia%20hemprichii

2024-07-20 05:51 UTC, ChuijkYahus commented on projects/1.20/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "tropicraft.container.bambooChest": "竹箱",
```suggestion
  "tropicraft.container.bambooChest": "竹箱子",
```
建议使用原版的`箱子`

2024-07-20 09:48 UTC, SummerFleur2997 commented on projects/1.20/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "block.tropicraft.sickle_seagrass": "木秆藻",
![屏幕截图 2024-07-20 174541](https://github.com/user-attachments/assets/32c5bfee-b112-44a1-9c39-f597c7e513e2)
此处参考 https://zh.wikipedia.org/wiki/%E4%B8%9D%E7%B2%89%E8%97%BB%E7%A7%91

2024-07-20 09:54 UTC, SummerFleur2997 commented on projects/1.20/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "block.tropicraft.eel_grass": "鳗草",
![屏幕截图 2024-07-20 175024](https://github.com/user-attachments/assets/7dce0d82-bd3d-4431-8a83-26d5297cae7a)
“eel grass” 在 bing 词典上是叫做 “鳗草”
后查阅其拉丁学名 https://zh.wikipedia.org/wiki/%E6%B5%B7%E8%8F%96%E8%92%B2%E5%B1%9E
似乎是采用 “海菖蒲” 更为合适。

2024-07-20 10:19 UTC, SummerFleur2997 commented on projects/1.20/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "block.tropicraft.bamboo_potted_wither_rose": "竹制凋零玫瑰盆栽",
该mod在minecraft各大版本下，均只适用于热门小版本（例如1.16.5, 1.18.2， 1.19.2），故仅在1.20版本内更改此选项

2024-07-21 07:36 UTC, SummerFleur2997 commented on projects/1.18/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "block.tropicraft.palm_leaves": "棕榈叶",
```suggestion
  "block.tropicraft.palm_leaves": "棕榈树叶",
```

2024-07-21 07:38 UTC, SummerFleur2997 commented on projects/1.19/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "block.tropicraft.palm_leaves": "棕榈叶",
```suggestion
  "block.tropicraft.palm_leaves": "棕榈树叶",
```

2024-07-21 07:38 UTC, SummerFleur2997 commented on projects/1.18/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "block.tropicraft.palm_leaves": "棕榈叶",
```suggestion
  "block.tropicraft.palm_leaves": "棕榈树叶",
```

2024-07-21 07:38 UTC, SummerFleur2997 commented on projects/1.20/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "block.tropicraft.palm_leaves": "棕榈叶",
```suggestion
  "block.tropicraft.palm_leaves": "棕榈树叶",
```

2024-07-28 15:30 UTC, mamaruo reviewed
中英键序不一样，审着费劲

2024-07-28 15:30 UTC, mamaruo commented on projects/1.20/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "block.tropicraft.fern_seagrass": "喜盐草",
| **审阅级别** |
|:--------------:|
|❓ **疑问** / 不阻止合并|

原文：**Fern Seagrass**

存疑，未查到确切资料

2024-07-28 15:30 UTC, mamaruo commented on projects/1.20/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "block.tropicraft.jigarbov_spruce_wall_torch": "Jigarbov云杉木红石火把",
| **审阅级别** |
|:--------------:|
|ℹ️ **信息** / 不阻止合并|

原文：**Jigarbov Acacia Wall Torch┃Jigarbov Birch Wall Torch┃Jigarbov Black Mangrove Wall Torch┃Jigarbov Dark Oak Wall Torch┃Jigarbov Jungle Wall Torch┃Jigarbov Light Mangrove Wall Torch┃Jigarbov Oak Wall Torch┃Jigarbov Red Mangrove Wall Torch┃Jigarbov Spruce Wall Torch**

[Minecraft Marketplace | Jigarbov Productions](https://www.minecraft.net/en-us/marketplace/creator?name=jigarbov%20productions)

[Jigarbov - YouTube](https://www.youtube.com/channel/UCyShGnwbY3dNV11LpEjgNWQ)

2024-07-28 15:30 UTC, mamaruo commented on projects/1.20/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "block.tropicraft.teleport_water": "热带世界传送门",
| **审阅级别** |
|:--------------:|
|❓ **疑问** / 不阻止合并|

原文：**Teleport Water**
```suggestion
  "block.tropicraft.teleport_water": "热带世界传送门",
```
为什么

2024-07-28 18:21 UTC, SummerFleur2997 commented on projects/1.20/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "item.tropicraft.cowktail_spawn_egg": "哞葩刷怪蛋",
此处详见 pull/4486 已与多人达成一致意见，具体可在q群搜索聊天记录“哞葩”

2024-07-28 18:22 UTC, SummerFleur2997 commented on projects/1.20/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "item.tropicraft.frox_conch": "Frox海螺",
赞助者名字不翻译

2024-07-28 18:23 UTC, SummerFleur2997 commented on projects/1.20/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "block.tropicraft.jigarbov_spruce_wall_torch": "Jigarbov云杉木红石火把",
该方块只能使用setblock命令放置，似乎是不能自然生成/手工合成

2024-07-28 18:24 UTC, SummerFleur2997 commented on projects/1.20/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "block.tropicraft.teleport_water": "热带世界传送门",
因为传送门介质就是水，泡在这个水里面就会传送到该维度

2024-07-28 18:29 UTC, SummerFleur2997 commented
该pull是根据已经审阅完毕的该mod 1.16版本同步而来，详见pull/4486
因#4486已经确认无误合并了，个人认为可能部分内容需要同4486的审阅者进行沟通

2024-07-28 18:34 UTC, SummerFleur2997 commented on projects/1.20/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "item.tropicraft.coconut_chunk": "椰子片",
因贴图更符合`椰子片`，故舍弃原文采用`片`的描述

2024-07-28 18:39 UTC, SummerFleur2997 commented on projects/1.20/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "item.tropicraft.caipirinha": "卡琵利亚",
鸡尾酒名称，坊间译法较为繁多，考虑到更改可能涉及已合并内容的返工，个人建议为不更改

2024-07-28 18:44 UTC, SummerFleur2997 commented on projects/1.20/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "block.tropicraft.fern_seagrass": "喜盐草",
此处游戏内给出了确切的学名，请参考 [wikipedia喜盐草属](https://zh.wikipedia.org/wiki/%E5%96%9C%E7%9B%90%E8%8D%89%E5%B1%9E)
![0B64963FA4AA8716A97BD5A54229B909](https://github.com/user-attachments/assets/01c1908a-06cc-4f02-bb3a-3f39ece6c28b)

2024-07-28 18:45 UTC, SummerFleur2997 commented on projects/1.20/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "block.tropicraft.fern_seagrass": "喜盐草",
因未能查询到“种”级别的信息，故采用“属”的名称进行翻译

2024-07-28 18:46 UTC, SummerFleur2997 commented on projects/1.20/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "item.tropicraft.exploding_coconut": "椰子炸弹",
可投掷的，落地后能爆炸的椰子

2024-07-28 18:53 UTC, SummerFleur2997 commented on projects/1.20/assets/tropicraft/tropicraft/lang/zh_cn.json
> +  "entity.tropicraft.wall_item": "墙壁物品",
该方块不可通过/give获得且使用/setblock放置后不可见，因不清楚他到底是什么，故采取直译

2024-08-02 07:03 UTC, SlimeSB requested changes
WIP

2024-08-15 14:22 UTC, SlimeSB commented
我了个豆啊我改一半还没push被你抢了。
不用管了我之后直接在上面改然后approve。没有原文更改了，只是改用打包器配置复用语言文件。

2024-08-15 14:26 UTC, SummerFleur2997 commented
> 我了个豆啊我改一半还没push被你抢了。 不用管了我之后直接在上面改然后approve。没有原文更改了，只是改用打包器配置复用语言文件。

ok QAQ

2024-08-17 08:39 UTC, merged