Main
CFPAOrg/Minecraft-Mod-Language-Package pull request #4535
Opened 2024-08-04 17:28 UTC by Pastel-97

2024-08-20 01:46 UTC, luoxueyasha requested changes

2024-08-20 01:46 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "enchantment.enderite.void_floating.desc": "保护物品不受虚空伤害",
```suggestion
  "enchantment.enderite.void_floating.desc": "保护物品不被虚空吞噬",
```
库里应该有这条，建议比对一下
但是虚空理论上是不会对物品造成伤害的

2024-08-20 01:46 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "item.enderite.enderite_shovel": "末影合金铲",
```suggestion
  "item.enderite.enderite_shovel": "末影合金锹",
```

2024-08-20 01:46 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "block.enderite.cracked_enderite_ore": "破碎的末影合金矿",
游戏里长什么样（需要截图），是否和裂纹类石头类似？

2024-08-20 01:46 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "block.enderite.ender_crystal_block": "末影水晶矿石",
确定是矿石吗
原文`Block of Ender Crystal`

2024-08-20 01:46 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "tooltip.enderite.enderite_sword_teleport": "将你传送到指针所选方块处",
```suggestion
  "tooltip.enderite.enderite_sword_teleport": "将你传送到看向的方块处",
```
按原文走吧

2024-08-20 01:46 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "tooltip.enderite.enderite_sword_teleport_charges_info1": "想要充能，请在你的物品栏中放入珍珠，然后点击鼠标右键",
```suggestion
  "tooltip.enderite.enderite_sword_teleport_charges_info1": "在物品栏中放入珍珠并右击以充能",
```
减少翻译腔

2024-08-20 01:46 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "tooltip.enderite.enderite_sword_teleport_charges_info2": "潜行+右键点击传送",
```suggestion
  "tooltip.enderite.enderite_sword_teleport_charges_info2": "潜行+右击传送",
```
右击or右键点击，需要上下文统一

2024-08-20 01:46 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "tooltip.enderite.enderite_sword_health_boost": "攻击时短暂增加自身生命值",
是原版的生命提升吗

2024-08-20 01:46 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "tooltip.enderite.enderite_pickaxe_configurable": "你可以在 'data/forge/tags/blocks/end_stones.json'中配置被镐破坏得更快的方块",
```suggestion
  "tooltip.enderite.enderite_pickaxe_configurable": "你可以在'data/forge/tags/blocks/end_stones.json'中配置被镐破坏得更快的方块",
```
单引号的符号问题这里开一条，别resolve，需要讨论

2024-08-20 01:46 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "tooltip.enderite.enderite_armor_set_bonus": "装备增益:",
```suggestion
  "tooltip.enderite.enderite_armor_set_bonus": "装备增益：",
```
标点符号应使用规范的汉语全角标点符号，具体要求请阅读我们的 [翻译规范](https://cfpa.site/TransRules/) 中 **03.标点符号** 这一节。
诸如这类的问题请在您翻译的所有文件中全部查明并修改。

2024-08-20 01:46 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "tooltip.enderite.enderite_armor_set_bonus_slow_falling": "如果按下 'Shift' ,你会得到缓降的效果",
```suggestion
  "tooltip.enderite.enderite_armor_set_bonus_slow_falling": "按下Shift以获得缓降效果",
```
此类问题请全文通查并修改
可以适当参考 维基百科:翻译腔

2024-08-20 01:46 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "tooltip.enderite.enderite_boots_configurable": "您可以在 'data/forge/tags/blocks/enderite_boots_walks_faster_on_blocks.json'中配置获得速度的区块",
获得速度的区块？
认真的？

2024-08-20 01:46 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "advancement.end.enderite.charge_end_respawn_anchor.title": "好奇心害死锚",
解释一下为什么这么翻
原文`Feels Like Home!`

2024-08-20 01:46 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "item.enderite.gilded_enderite_pickaxe": "镶金末影合金稿",
```suggestion
  "item.enderite.gilded_enderite_pickaxe": "镶金末影合金镐",
```

2024-08-20 01:46 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "item.enderite.gilded_enderite_shovel": "镶金末影合金铲",
```suggestion
  "item.enderite.gilded_enderite_shovel": "镶金末影合金锹",
```

2024-08-20 01:46 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "item.enderite.smithing_template.enderite_upgrade.base_slot_description_without_elytra": "在这里放一件下界合金盔甲、武器或工具",
这些（以及上文）翻的有点怪，有游戏内截图吗

2024-09-13 01:21 UTC, Pastel-97 commented
@luoxueyasha 大大可以再看一下我这篇么 已经过去很久啦 有什么错误我都会改的

2024-09-18 02:51 UTC, luoxueyasha commented
这边上班忙，可能审阅不及时，先道个歉（

我这边看不到你对审阅意见的回复，它们可能处于pending状态，你需要一并提交这些回复意见（解决方法可参考https://github.com/orgs/community/discussions/10369）。
以及解决完的内容记得resolve

2024-09-21 07:04 UTC, Pastel-97 reviewed
update

2024-09-21 07:05 UTC, Pastel-97 commented
@luoxueyasha 大大我已经resolve了 现在能看到了吗？ file change也提交了

2024-09-21 08:00 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "block.enderite.cracked_enderite_ore": "破碎的末影合金矿",
原文是ore，矿石
请全文通查并修改

2024-09-21 08:01 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "tooltip.enderite.enderite_sword_teleport_charges_info2": "潜行+右键点击传送",
`右键`不是一个完整的谓语，书面上不能单独作为动作使用。
右键什么？`右键点击`？`右键长按？``扣掉右键？`
（日常右键1/1）

2024-09-21 08:03 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "tooltip.enderite.enderite_pickaxe_configurable": "你可以在 'data/forge/tags/blocks/end_stones.json'中配置被镐破坏得更快的方块",
不需要加空格
但是按照标点符号规范，引号推荐改为全角双引号
主要是这里是个路径，感觉应该放群里问一句

2024-09-21 08:05 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "item.enderite.smithing_template.enderite_upgrade.base_slot_description_without_elytra": "在这里放一件下界合金盔甲、武器或工具",
这几句你自己修一下吧

2024-09-24 15:56 UTC, Pastel-97 reviewed
ore

2024-09-27 01:11 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "tooltip.enderite.enderite_boots_configurable": "你可以在'data/forge/tags/blocks/enderite_boots_walks_faster_on_blocks.json'中配置获得速度的方块",
```suggestion
  "tooltip.enderite.enderite_boots_configurable": "你可以在'data/forge/tags/blocks/enderite_boots_walks_faster_on_blocks.json'中配置增加行走速度的方块",
```
方块获得速度 有歧义

2024-09-27 01:11 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "trim_material.enderite.enderite": "末影合金材料（类似飘浮I）",
```suggestion
  "trim_material.enderite.enderite": "末影合金材料（效果类似虚空飘浮I）",
```
漏翻
可以不译出`效果`，但飘浮会和原版levitation撞

2024-09-27 01:11 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "tooltip.enderite.enderite_boots_configurable": "你可以在'data/forge/tags/blocks/enderite_boots_walks_faster_on_blocks.json'中配置获得速度的方块",
再开一条单引号的，别resolve
群里讨论后我会把修改意见放这

2024-09-27 04:26 UTC, luoxueyasha commented on projects/1.20/assets/enderite-cj-edition/enderite/lang/zh_cn.json
> +  "tooltip.enderite.enderite_boots_configurable": "你可以在'data/forge/tags/blocks/enderite_boots_walks_faster_on_blocks.json'中配置获得速度的方块",
建议全部改成全角双引号
无论采用何种符号，引号前后都不应该有空格
请全文通查

2024-10-06 02:17 UTC, luoxueyasha approved these changes

2024-10-06 07:05 UTC, Pastel-97 commented
总算通过了 万分感谢大大校正！ @luoxueyasha

2024-10-11 06:36 UTC, merged