Morerbowcj翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #4542
Opened 2024-08-04 19:40 UTC by Pastel-97

2024-08-15 04:44 UTC, Cactusstudent requested changes
存在过于偏离原文的情况，请将进度名称进行修改，同时存在标点符号问题（应该使用中文标点）

2024-08-15 04:44 UTC, Cactusstudent commented on projects/1.20/assets/more-bows-cj/morebows/lang/zh_cn.json
> +	"item.morebows.smithing_template.bow_upgrade.additions_slot_description": "放一块金属",
```suggestion
	"item.morebows.smithing_template.bow_upgrade.additions_slot_description": "在此处放置一块下一等级的金属。",
```

2024-08-15 04:44 UTC, Cactusstudent commented on projects/1.20/assets/more-bows-cj/morebows/lang/zh_cn.json
> +	"item.morebows.smithing_template.bow_upgrade.base_slot_description": "放一把弓.",
```suggestion
	"item.morebows.smithing_template.bow_upgrade.base_slot_description": "在此处放一把弓。",
```

2024-08-15 04:44 UTC, Cactusstudent commented on projects/1.20/assets/more-bows-cj/morebows/lang/zh_cn.json
> +	"item.morebows.smithing_template.bow_upgrade.ingredients": "铜,铁,金,绿宝石,钻石块等",
```suggestion
	"item.morebows.smithing_template.bow_upgrade.ingredients": "铜块，铁块，金块，绿宝石块，钻石块",
```

2024-08-15 06:44 UTC, Pastel-97 commented on projects/1.20/assets/more-bows-cj/morebows/lang/zh_cn.json
> +	"item.morebows.smithing_template.bow_upgrade.additions_slot_description": "放一块金属",
已更改

2024-08-15 06:44 UTC, Pastel-97 commented on projects/1.20/assets/more-bows-cj/morebows/lang/zh_cn.json
> +	"item.morebows.smithing_template.bow_upgrade.base_slot_description": "放一把弓.",
同上

2024-08-15 06:46 UTC, Pastel-97 commented on projects/1.20/assets/more-bows-cj/morebows/lang/zh_cn.json
> +	"item.morebows.smithing_template.bow_upgrade.ingredients": "铜,铁,金,绿宝石,钻石块等",
已订正

2024-08-15 07:27 UTC, Cactusstudent approved these changes

2024-08-16 08:18 UTC, SlimeSB approved these changes

2024-08-17 08:41 UTC, merged