Netheritehorse翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #4543
Opened 2024-08-04 20:05 UTC by Pastel-97

2024-08-06 06:58 UTC, luoxueyasha requested changes

2024-08-06 06:58 UTC, luoxueyasha commented on projects/1.20/assets/netherite-horse-armor-cj/netheritehorsearmor/lang/zh_cn.json
> +	"tooltip.netheritehorsearmor.protection": "马儿保护",
游戏里的显示是什么样的（需要截图）？
效果是？

2024-08-06 06:58 UTC, luoxueyasha commented on projects/1.20/assets/netherite-horse-armor-cj/netheritehorsearmor/lang/zh_cn.json
> +	"advancements.husbandry.netheritehorsearmor.obtain_netherite_horse_armor.title": "俺的爱马！",
原文：`True Love!`
翻译应以原文为准。请不要加私货
此类问题请全文通查并修改

```suggestion
	"advancements.husbandry.netheritehorsearmor.obtain_netherite_horse_armor.title": "真爱！",
```

2024-08-06 06:58 UTC, luoxueyasha commented on projects/1.20/assets/netherite-horse-armor-cj/netheritehorsearmor/lang/zh_cn.json
> +	"advancements.husbandry.netheritehorsearmor.obtain_enderite_horse_armor.title": "真的是俺的爱马！",
```suggestion
	"advancements.husbandry.netheritehorsearmor.obtain_enderite_horse_armor.title": "更真的爱！",
```
同上

2024-08-06 15:45 UTC, Pastel-97 commented on projects/1.20/assets/netherite-horse-armor-cj/netheritehorsearmor/lang/zh_cn.json
> +	"advancements.husbandry.netheritehorsearmor.obtain_netherite_horse_armor.title": "俺的爱马！",
好的

2024-08-06 15:45 UTC, Pastel-97 commented on projects/1.20/assets/netherite-horse-armor-cj/netheritehorsearmor/lang/zh_cn.json
> +	"tooltip.netheritehorsearmor.protection": "马儿保护",
![3d25efd1-fbc2-4387-9eb4-a847510c5baa](https://github.com/user-attachments/assets/807eb5ef-cb58-4ff6-9c1a-b2fee7efa4ba)
效果就是给马儿保护 和保护一样

2024-08-06 16:06 UTC, Pastel-97 commented on projects/1.20/assets/netherite-horse-armor-cj/netheritehorsearmor/lang/zh_cn.json
> +	"advancements.husbandry.netheritehorsearmor.obtain_enderite_horse_armor.title": "真的是俺的爱马！",
已更正

2024-08-06 16:08 UTC, Pastel-97 commented on projects/1.20/assets/netherite-horse-armor-cj/netheritehorsearmor/lang/zh_cn.json
> +	"tooltip.netheritehorsearmor.protection": "马儿保护",
更换为马匹保护

2024-08-07 16:08 UTC, Pastel-97 commented on projects/1.20/assets/netherite-horse-armor-cj/netheritehorsearmor/lang/zh_cn.json
> +	"advancements.husbandry.netheritehorsearmor.obtain_netherite_horse_armor.description": "给马儿找一件下界合金马铠",
好的感谢指正，第一次上传相关汉化见谅

2024-08-08 05:59 UTC, ChuijkYahus approved these changes

2024-08-09 12:14 UTC, luoxueyasha approved these changes

2024-08-11 13:13 UTC, merged