提交WeaponOfMiracle模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #4545
Opened 2024-08-06 08:04 UTC by AZhe1029

2024-08-06 08:07 UTC, AZhe1029 commented
/mv "projects/1.20/assets/WeaponsOfMiracles/" "projects/1.20/assets/Weapons of Miracles - epic fight/"

2024-08-06 08:12 UTC, AZhe1029 commented
/mv "projects/1.20/assets/WeaponsOfMiracles/" "projects/1.20/assets/weapons-of-miracles-epicfight/"

2024-08-06 08:13 UTC, AZhe1029 commented
/mv "projects/1.20/assets/Weapons of Miracles - epic fight/" "projects/1.20/assets/weapons-of-miracles-epicfight/"

2024-08-06 08:19 UTC, AZhe1029 commented
/add-mapping weapons-of-miracles-epicfight 918614

2024-10-24 06:32 UTC, luoxueyasha requested changes

2024-10-24 06:32 UTC, luoxueyasha commented on projects/1.20/assets/weapons-of-miracles-epicfight/wom/lang/zh_cn.json
> +	"skill.wom.agony_plunge.tooltip" : "\"向上空瞬移，然后对下方的敌人进行极为迅猛的一击。\"\n攻击敌人将为此充能最多3次\n最终伤害将根据能量次数进行倍增。",
```suggestion
	"skill.wom.agony_plunge.tooltip" : "“向上空瞬移，然后对下方的敌人进行极为迅猛的一击。”\n攻击敌人将为此充能最多3次。\n最终伤害将根据能量次数进行倍增。",
```

标点符号应使用规范的汉语全角标点符号，具体要求请阅读我们的 [翻译规范](https://cfpa.site/TransRules/) 中 **03.标点符号** 这一节。
诸如这类的问题请在您翻译的所有文件中全部查明并修改。

此外有无句号应与原文一致

2024-10-24 06:32 UTC, luoxueyasha commented on projects/1.20/assets/weapons-of-miracles-epicfight/wom/lang/zh_cn.json
> +	"item.wom.ruine.tooltip" : "一把古老的武器，锻造于被遗忘的知识之中，并注入了末影人的力量。\n其平衡和设计在战斗中能够实现最大的效率和精准。",
```suggestion
	"item.wom.ruine.tooltip" : "一把古老的武器，锻造于被遗忘的知识之中，并注入了末影人的力量。\n其平衡和设计在战斗中能够实现最高的效率和精准。",
```
最大效率 最高效率
最大精准 最高精准
个人语感上赞同后者

2024-10-24 06:32 UTC, luoxueyasha commented on projects/1.20/assets/weapons-of-miracles-epicfight/wom/lang/zh_cn.json
> +	"skill.wom.plunder_perdition.tooltip" : "“执行末影仪式。”\n剑柄中的浓缩末影之力将从区域内的所有敌人中窃取生命力。\n每次命中敌人都会给您5%的最大体力和1点生命值回复（每个扫击等级额外+1颗心）。\n然后，水晶将在10秒内提供您增加的总体速度，速度的强度取决于命中敌人的数量。",
原文第一句漏翻`of stealing the essence of others.`
第二人称用“你”即可，无需用谦称

2024-10-24 06:32 UTC, luoxueyasha commented on projects/1.20/assets/weapons-of-miracles-epicfight/wom/lang/zh_cn.json
> +	"skill.wom.ender_blast.tooltip" : "末地技术力量的巅峰\n这把枪由12个腔室组成。\n动能将被储存在其中并转化为末影之力。\n当扳机被扣下时，转化的末影之力的一半凝聚成末影子弹。\n另一半被转移到粒子加速器中对末影之力进行过载充能，以巨大的力量和极高的精度发射子弹。\n所有这些都在短短的一瞬间内完成……令人叹为观止！",
漏翻

2024-10-24 06:32 UTC, luoxueyasha commented on projects/1.20/assets/weapons-of-miracles-epicfight/wom/lang/zh_cn.json
> +	"item.wom.antitheus" : "魔镰·撒旦",
原文`Antitheus`
无论是按希腊语原意还是其英语引申义，都扯不到基督教或延伸的`撒旦`上（哪怕是希伯来语Satan的本意：敌对、使敌对）。
需要重翻

2024-10-25 08:42 UTC, AZhe1029 commented on projects/1.20/assets/weapons-of-miracles-epicfight/wom/lang/zh_cn.json
> +	"skill.wom.agony_plunge.tooltip" : "\"向上空瞬移，然后对下方的敌人进行极为迅猛的一击。\"\n攻击敌人将为此充能最多3次\n最终伤害将根据能量次数进行倍增。",
已修改

2024-10-25 08:43 UTC, AZhe1029 commented on projects/1.20/assets/weapons-of-miracles-epicfight/wom/lang/zh_cn.json
> +	"item.wom.ruine.tooltip" : "一把古老的武器，锻造于被遗忘的知识之中，并注入了末影人的力量。\n其平衡和设计在战斗中能够实现最大的效率和精准。",
已修改

2024-10-25 08:43 UTC, AZhe1029 commented on projects/1.20/assets/weapons-of-miracles-epicfight/wom/lang/zh_cn.json
> +	"skill.wom.plunder_perdition.tooltip" : "“执行末影仪式。”\n剑柄中的浓缩末影之力将从区域内的所有敌人中窃取生命力。\n每次命中敌人都会给您5%的最大体力和1点生命值回复（每个扫击等级额外+1颗心）。\n然后，水晶将在10秒内提供您增加的总体速度，速度的强度取决于命中敌人的数量。",
已修改，我才发现这玩意原文描述在新版本有改动

2024-10-25 08:45 UTC, AZhe1029 commented on projects/1.20/assets/weapons-of-miracles-epicfight/wom/lang/zh_cn.json
> +	"item.wom.antitheus" : "魔镰·撒旦",
已修改（曾译名的思路来自于逆卡巴拉邪恶树的“无神论”质点对应撒旦）

2024-10-25 08:48 UTC, AZhe1029 commented on projects/1.20/assets/weapons-of-miracles-epicfight/wom/lang/zh_cn.json
> +	"skill.wom.ender_blast.tooltip" : "末地技术力量的巅峰\n这把枪由12个腔室组成。\n动能将被储存在其中并转化为末影之力。\n当扳机被扣下时，转化的末影之力的一半凝聚成末影子弹。\n另一半被转移到粒子加速器中对末影之力进行过载充能，以巨大的力量和极高的精度发射子弹。\n所有这些都在短短的一瞬间内完成……令人叹为观止！",
已修改

2024-10-25 09:37 UTC, luoxueyasha requested changes

2024-10-25 09:37 UTC, luoxueyasha commented on projects/1.20/assets/weapons-of-miracles-epicfight/wom/lang/zh_cn.json
> +	"enchantment.wom.invigoration.desc" : "每级加2点最大耐力值",
```suggestion
	"enchantment.wom.invigoration.desc" : "每级增加2点最大耐力值。",
```
不清楚附魔描述模组一般是什么格式，这里暂以英文原文带句号的模式审阅

全文通查

2024-10-25 09:37 UTC, luoxueyasha commented on projects/1.20/assets/weapons-of-miracles-epicfight/wom/lang/zh_cn.json
> +	"skill.wom.agony_plunge.tooltip" : "“在俯冲攻击敌人之前向空中闪现。”\n攻击敌人将为俯冲攻击充能最多3次\n最终伤害将根据能量次数进行倍增。",
`闪现`需商议，原文`disappear`没有`现`的部分

2024-10-25 09:37 UTC, luoxueyasha commented on projects/1.20/assets/weapons-of-miracles-epicfight/wom/lang/zh_cn.json
> +	"skill.wom.true_berserk.tooltip" : "“愿神明敬畏你······”\n折磨巨斧的愤怒将使战技充能值无法阅读。",
```suggestion
	"skill.wom.true_berserk.tooltip" : "“愿神明敬畏你······”\n折磨巨斧的愤怒将使战技充能槽无法阅读。",
```
实际游戏内截图是？
unreadable 疑似生硬翻译

2024-10-25 09:37 UTC, luoxueyasha commented on projects/1.20/assets/weapons-of-miracles-epicfight/wom/lang/zh_cn.json
> +	"item.wom.ruine.tooltip" : "一把古老的武器，锻造于被遗忘的知识之中，并注入了末影人的力量。\n其平衡和设计在战斗中能够实现最高的精度与效率。",
```suggestion
	"item.wom.ruine.tooltip" : "一把古老的武器，由被遗忘的知识所锻造，并注入了末影人的力量。\n其配重与设计在战斗中能够发挥出最高的精度与效率。",
```
第一句错译
`balance and design`指看上去很匀称，用起来也很均衡，设计也很精妙，但是我想不到合适的形容词
实现……对allow有点生硬

2024-10-25 09:37 UTC, luoxueyasha commented on projects/1.20/assets/weapons-of-miracles-epicfight/wom/lang/zh_cn.json
> +	"skill.wom.plunder_perdition.tooltip" : "“执行末影仪式，窃取敌手精元。”\n\n该技能可从1层至多叠加到10层。\n冲刺或跳跃时的技能总是可用，但技能效果会根据堆叠的数量发生变化。2层时，你将在短时间内获得较低的移速。3层时，你将根据你的位置和方向传送至最后击中的目标。\n10层时，可以在行走或站立时使用技能，将剑插入地面并在你周围的所有敌人下方召唤破
精元~~个大头鬼~~ 在这个语境下不是很好的翻译，你也不想Zeus（宙斯）被翻译成雷公、Athena（雅典娜）被翻译成观音吧
无需润色，正常翻译即可

剩下的长句也翻的比较生硬（冲刺…时的技能总是可用、……每个横刀之刃等级），建议学习[维基百科:翻译腔](https://zh.m.wikipedia.org/wiki/Wikipedia:%E7%BF%BB%E8%AF%91%E8%85%94) 并全文通查

2024-10-25 09:37 UTC, luoxueyasha commented on projects/1.20/assets/weapons-of-miracles-epicfight/wom/lang/zh_cn.json
> +	"skill.wom.sakura_state.tooltip" : "在绝对的宁静中斩出至锐的一击。\n向前方释放一次樱花斩。在奔跑时释放变为樱花冲刺斩，快速穿越身前的敌人并斩击他们。技能释放次数可以叠加总共8次。\n每拥有一个横扫之刃魔咒等级，将增加1/3的初始叠加次数。\n在首次释放樱花斩/樱花冲刺斩后，你将进入斩樱形态。\n如果在4秒内不再进行樱花斩/樱花冲刺斩，将失去所有的技能释放次
技能释放次数的stack是指？初始冷却可以储存8次，还是和叠buff一样可以叠8层？

2024-10-25 09:37 UTC, luoxueyasha commented on projects/1.20/assets/weapons-of-miracles-epicfight/wom/lang/zh_cn.json
> +	"skill.wom.regierung" : "二重统治",
德Regierung，词源拉丁rego→拉丁变格regere→古法reger→古德regieren，没有`二重`的意思

2024-10-25 09:37 UTC, luoxueyasha commented on projects/1.20/assets/weapons-of-miracles-epicfight/wom/lang/zh_cn.json
> +	"skill.wom.lunar_eclipse.tooltip" : "斩断光芒，收割生命······散播绝望。\n空袭你面前的敌人并让他们发光7秒\n明月模式下:\n击中发光的目标会叠加你造成的伤害并增加被击中目标的发光等级\n击中失明的目标会叠加你造成的伤害并移除被击中目标的失明效果\n暗月模式中:\n击中发光的目标会叠加你造成的伤害并移除被击中目标的发光效果\n击中失明的目标会叠加你造
```suggestion
	"skill.wom.lunar_eclipse.tooltip" : "“斩断光芒，收割生命······散播绝望。”\n空袭你面前的敌人并让他们发光7秒\n明月模式下：\n击中发光的目标会叠加你造成的伤害并增加被击中目标的发光等级\n击中失明的目标会叠加你造成的伤害并移除被击中目标的失明效果\n暗月模式下：\n击中发光的目标会叠加你造成的伤害并移除被击中目标的发光效果\n击中失明的目标会叠加你造成的伤害并增加被击中目标的失明等级\n明月模式跳跃攻击（新月残光）：释放对目标所有叠加的伤害\n如果它杀死了目标，将会反射到最近的目标，并减少5%的伤害\n发光会增加反射范围，失明会增加伤害\n暗月模式跳跃攻击（满月凌空）：以AOE释放对目标叠加的70%伤害。\n失明会增加伤害。",
```
`空袭你面前`的空袭是怎么翻的？

标点符号问题 全文通查（就改了一部分
加戏太多 全文自查

2025-02-06 02:55 UTC, luoxueyasha commented
@AZhe1029 

- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

2025-02-14 14:07 UTC, closed without merging