Dynamic Electricity 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4559
Opened 2024-08-08 09:16 UTC by QiuShui1012

2024-08-08 09:46 UTC, QiuShui1012 commented
机器人把最老的算成最新的了 没绷住

2024-08-25 01:15 UTC, luoxueyasha requested changes

2024-08-25 01:15 UTC, luoxueyasha commented on projects/1.18/assets/dynamic-electricity/dynamicelectricity/lang/zh_cn.json
> +  "guidebook.dynamicelectricity.chapter.acmotors.l1": "交流电动机能够将电动力学焦耳（J）转换为Forge能量单位（FE）。它能够以100%的效率实现这一点。存在三级电机，提供不同的吞吐率以满足您的要求。",
```suggestion
  "guidebook.dynamicelectricity.chapter.acmotors.l1": "交流电动机能够将电动力学焦耳（J）转换为Forge能量单位（FE）。它能够以100%的效率实现这一点。存在三级电机，提供不同的吞吐率以满足您的需求。",
```
是手册？
手册的话就不追究谦称（您）了

2024-08-25 01:15 UTC, luoxueyasha commented on projects/1.18/assets/dynamic-electricity/dynamicelectricity/lang/zh_cn.json
> +  "guidebook.dynamicelectricity.chapter.dcmotors.l1": "直流电动机能够将Forge能量单位（FE）转换为电动力学焦耳（J）。它以95%的效率实现了这一目标。与交流电动机不同，直流电动机需要一个名为导体刷的额外组件来运行。刷子的耐用性有限，但可以通过从电机顶部使用漏斗漏下更多来轻松补充。存在三层电机，提供不同的吞吐率以满足您的要求。",
```suggestion
  "guidebook.dynamicelectricity.chapter.dcmotors.l1": "直流电动机能够将Forge能量单位（FE）以95%的效率转换为电动力学焦耳（J）。与交流电动机不同，直流电动机需要一个名为导体刷的额外组件来运行。刷子的耐久度有限，但可以通过从电机顶部使用漏斗来轻松补充。存在三层电机，提供不同的吞吐率以满足您的需求。",
```
疑似机翻，好多不通顺的地方
3 tiers翻成三层？

上下文通查吧

2024-08-25 01:15 UTC, luoxueyasha commented on projects/1.18/assets/dynamic-electricity/dynamicelectricity/lang/zh_cn.json
> +  "tooltip.dynamicelectricity.motorachv.conversion": "100 kJ @ 480V → 100 kFE",
一定要改成右箭头吗
->和→在游戏里的显示情况分别是？

2024-08-25 02:17 UTC, QiuShui1012 commented on projects/1.18/assets/dynamic-electricity/dynamicelectricity/lang/zh_cn.json
> +  "tooltip.dynamicelectricity.motorachv.conversion": "100 kJ @ 480V → 100 kFE",
![image](https://github.com/user-attachments/assets/569e7260-3d4f-44b6-b8b3-99036d8729ef)
![image](https://github.com/user-attachments/assets/bc86443a-8619-451e-a3f0-c8a018f475c7)
感觉→比->好看点，就是稍微小一些

2024-08-25 03:26 UTC, SlimeSB commented on projects/1.18/assets/dynamic-electricity/dynamicelectricity/lang/zh_cn.json
> +  "guidebook.dynamicelectricity.chapter.industrialreborn.hv": "HV : 超级",
```suggestion
  "guidebook.dynamicelectricity.chapter.industrialreborn.hv": "HV：超级",
```

2024-08-25 03:26 UTC, SlimeSB commented on projects/1.18/assets/dynamic-electricity/dynamicelectricity/lang/zh_cn.json
> +  "guidebook.dynamicelectricity.chapter.industrialreborn.mv": "MV : 高级",
```suggestion
  "guidebook.dynamicelectricity.chapter.industrialreborn.lv": "LV：标准",
  "guidebook.dynamicelectricity.chapter.industrialreborn.mv": "MV：高级",
```

2024-08-28 16:05 UTC, SlimeSB commented on projects/1.18/assets/dynamic-electricity/dynamicelectricity/lang/zh_cn.json
> +  "guidebook.dynamicelectricity.chapter.dynamicelectricity.l1": "Dynamic Electricity面向大规模能源转换。电动力学的电池箱可以自然地将FE转换为焦耳。它们也能够为FE机器供电，但仅限于FE机器的电压额定为120V。然而，电池箱的输入和输出速率有限。Dynamic Electricity提供了一系列电动机，其吞吐量值
```suggestion
  "guidebook.dynamicelectricity.chapter.dynamicelectricity.l1": "Dynamic Electricity旨在解决大规模能源转换问题。尽管电动力学的电池箱可以自行将FE转换为焦耳，也能够为额定电压为120V的FE机器供电，但输入和输出速率有限。Dynamic Electricity提供了一系列电动机，提供远高于电池箱的吞吐量值。然而，虽然电动机提供了更高的吞吐量，但它们需要多加保养才能运作，包括提供润滑油来保持其运行。幸运的是，润滑油的制造成本相当低，可以简单地通过管道输送到电动机底部。不论是否使用，电动机都将持续转换能量。不过幸运的是，它们可以通过红石信号开关，这意味着你可以根据需要控制它们的启停。",
```
1. geared towards 指某个事物或活动是为了满足某个特定目标或人群的需求而设计或调整的。在此需要灵活翻译，不能一味译作“面向”。
2. can naturally 虚指，务必不要逐字译出。
3. 2、3、4句主语一致，句意连贯，合并为一个句子。
4. capable of 能达到的、能够做到的。此处原译有语病，吞吐量值和能力不是同类事物，不可比较。应当说吞吐能力。直译应当是“提供了远高于电池箱所能提供的吞吐量值”。
5. 看见whether首先想到调整语序。regardless of强调，忽略即可。
> I'm going whether you like it or not. 不管你愿意不愿意，我都要走了。
6. 仍然存在一些翻译腔问题。长文本尤其要求理解和再创作，同时兼顾准确性。

2024-08-28 16:15 UTC, QiuShui1012 commented on projects/1.18/assets/dynamic-electricity/dynamicelectricity/lang/zh_cn.json
> +  "guidebook.dynamicelectricity.chapter.dynamicelectricity.l1": "Dynamic Electricity面向大规模能源转换。电动力学的电池箱可以自然地将FE转换为焦耳。它们也能够为FE机器供电，但仅限于FE机器的电压额定为120V。然而，电池箱的输入和输出速率有限。Dynamic Electricity提供了一系列电动机，其吞吐量值
感谢指正🙇‍我再去看看其它条目

2024-08-28 16:31 UTC, SlimeSB approved these changes
就这样就行

2024-08-30 08:41 UTC, merged