Project Expansion 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4561
Opened 2024-08-08 12:49 UTC by jian3712

由 CFPA-Helper 提交。

2024-08-08 13:14 UTC, jian3712 commented
projectexpansion的原文件key少了黄燃料有关的进度中英文件补上了

2024-08-15 14:38 UTC, CreateCN commented
我看了一下，有些好像是机翻，还有些不太符合规范......

2024-08-15 16:13 UTC, jian3712 commented
@CreateCN 哪里机翻，不符合规范指出来我好继续改改

2024-08-16 00:01 UTC, CreateCN commented
“附魔书籍”之类的，还有些数字、英文需要和中文有个空格（翻译规范有）

2024-08-16 00:14 UTC, CreateCN commented
抱歉有些说错了，规范在这：https://cfpa.site/TransRules/

2024-08-19 15:41 UTC, jian3712 commented
还有哪些符号没全角？

2024-08-20 08:06 UTC, luoxueyasha reviewed
建议自查一遍全文，错译太多

2024-08-20 08:06 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"advancements.projectexpansion.compact_sun": "汝掌心中者，太阳之力也。",
```suggestion
	"advancements.projectexpansion.compact_sun": "太阳的能量，聚集在我的掌心里。",
```
蜘蛛侠2的台词梗

2024-08-20 08:06 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"advancements.projectexpansion.blinded_by_the_light.description": "你被警告了。",
```suggestion
	"advancements.projectexpansion.blinded_by_the_light.description": "早就警告过你了。",
```
语义错误

2024-08-20 08:06 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"advancements.projectexpansion.blinded_by_the_light": "被光芒蒙蔽",
有同名电影，建议参考译名

2024-08-20 08:06 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"block.projectexpansion.advanced_alchemical_chest.tooltip": "就像炼金术之袋一样，但以箱子的形式呈现。按住shfit键点击炼金术之袋来设置颜色。",
```suggestion
	"block.projectexpansion.advanced_alchemical_chest.tooltip": "和炼金术之袋类似的箱子。手持炼金术之袋，按住Shift并点击来设置颜色。",
```
前半句减少生硬翻译，后半句语义整个就错了

2024-08-21 21:38 UTC, jian3712 commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"advancements.projectexpansion.infinite_fuel.description": "那是一个十字架吗？管它呢，扔进熔炉里看它工作。",
![{ABF1A046-F39D-43DB-888A-5BA96743EBAE}](https://github.com/user-attachments/assets/9316e6cd-77a5-404c-b04e-414fce01659b)
游戏中的纹理是这样的

2024-08-21 21:40 UTC, jian3712 commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"advancements.projectexpansion.compressed_collector.description": "现在它们没用了，直到它们被制作成别的东西。",
算它们吧，一共有16级压缩收集器

2024-08-22 03:19 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"advancements.projectexpansion.compressed_collector.description": "现在它们没用了，直到它们被制作成别的东西。",
我觉得这里them指的是被压缩的9个方块，不是16级的统称

2024-08-22 03:28 UTC, jian3712 commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"advancements.projectexpansion.compressed_collector.description": "现在它们没用了，直到它们被制作成别的东西。",
行吧，那就它

2024-08-22 03:42 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"advancements.projectexpansion.infinite_steak": "无限牛排！！！",
原文`Unlimited Steak!!1!11!!!`
标点是否与原文一致？（`！！1！11！！！`）

2024-08-22 03:42 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"advancements.projectexpansion.infinite_steak.description": "面包？那是为农民准备的。",
```suggestion
	"advancements.projectexpansion.infinite_steak.description": "面包？那是为贫农准备的。",
```
原文peasants，mc里有farmer所以得避讳

2024-08-22 03:42 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"advancements.projectexpansion.infinite_fuel.description": "那是一个十字架吗？管它呢，扔进熔炉里看它工作。",
什么恒星十字架，明显错译了

就是普通的星星和十字

2024-08-22 03:42 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"advancements.projectexpansion.compressed_collector.description": "现在它们暂时没用了，除非它们被制作成力量花盆栽罐。",
```suggestion
	"advancements.projectexpansion.compressed_collector.description": "现在这玩意儿暂时没用了，除非被制作成别的东西。",
```
个人观点，可能有点口语化
应当以原文为准，原文没说是做盆栽，文本与游戏内容一致的情况下，就不要加戏

2024-08-22 03:42 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"block.projectexpansion.collector.tooltip": "在阳光下会生产EMC。",
确定是阳光吗
我记得萤石/火把等也行？

2024-08-22 03:42 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"block.projectexpansion.collector.EMC": "最大生产EMC：%s/s",
缺少原文

2024-08-22 03:42 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"block.projectexpansion.basic_collector": "基本收集器1型",
所有的MK X，都建议库里参考以前的翻译文本
需要全文通查

2024-08-22 03:42 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"block.projectexpansion.emc_link.empty_hand": "清空你的手来取回物品。",
```suggestion
	"block.projectexpansion.emc_link.empty_hand": "需要空手来取回物品。",
```
机翻嫌疑

2024-08-22 03:42 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"block.projectexpansion.emc_link.no_emc_value": "%s没有EMC。",
原文emc value
要不要考虑翻译出`emc值`？

2024-08-22 03:42 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"block.projectexpansion.emc_link.no_export_remaining": "物品输出限制已经达到，请稍等。",
```suggestion
	"block.projectexpansion.emc_link.no_export_remaining": "已达到物品输出限制，请稍等。",
```
倒装我了个

2024-08-22 03:42 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"block.projectexpansion.power_flower.tooltip": "每%stick生产一次EMC%s。（20/秒）",
```suggestion
	"block.projectexpansion.power_flower.tooltip": "每%s刻生产一次EMC%s。（20/秒）",
```
tick建议翻译出来
游戏里的显示情况？好奇为啥会有俩插入字符串

2024-08-22 03:42 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"block.projectexpansion.power_flower.EMC": "生产EMC：%s/秒",
缺原文
建议看bot提示/azusa 自查一遍

2024-08-22 03:42 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"command.projectexpansion.book.click_to_copy": "点击复制。这可以用来提供给开发人员进行调试。",
```suggestion
	"command.projectexpansion.book.click_to_copy": "点击复制。这些信息可以提供开发者以进行调试。",
```
有点生硬

2024-08-22 03:42 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"command.projectexpansion.book.bound_to_player.dump": "此书绑定于%s。要转储这些位置，请使用%s。",
游戏内显示效果？
确定dump要翻译成转储吗，看下文更像是一种备份？
可以讨论一下

2024-08-22 03:42 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"command.projectexpansion.EMC.invalid": "你提供的值（\"%s\"）无效，必须为正整数。",
缺原文

2024-08-22 03:42 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"command.projectexpansion.knowledge.clear.fail": "%s没有任何知识可清除。",
```suggestion
	"command.projectexpansion.knowledge.clear.fail": "%s没有任何可清除的知识。",
```
我了个句子を倒装勒

2024-08-23 13:02 UTC, CreateCN commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"block.projectexpansion.collector.tooltip": "在阳光下会生产EMC。",
原文应该是sunshine，所以被机翻为阳光

2024-08-24 05:56 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"block.projectexpansion.collector.tooltip": "在阳光下会生产EMC。",
原文是`Generates EMC when exposed to light.`
不太可能是机翻，感觉是人工错译的问题

**库里拒绝接收机器翻译（含生成式 AI）、生硬翻译。**
请自行严查译文

2024-08-25 02:21 UTC, jian3712 commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"block.projectexpansion.basic_collector": "基本收集器1型",
![image](https://github.com/user-attachments/assets/f22484a6-26e0-498b-b5e7-f3e40ba9f2b1)
现在的PE名称是X型确定要改成MK X有些不统一

2024-08-25 02:23 UTC, jian3712 commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"command.projectexpansion.EMC.invalid": "你提供的值（\"%s\"）无效，必须为正整数。",
缺什么原文了

2024-08-25 04:38 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"block.projectexpansion.basic_collector": "基本收集器1型",
那就X型吧

2024-08-28 08:45 UTC, jian3712 commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"gui.projectexpansion.config.enable_fluid_efficiency.desc": "是否启用流体效率。",
不清楚，游戏内也打不开配置文件，可能高版本玩少了

2024-08-28 15:33 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"advancements.projectexpansion.infinite_steak": "无限牛排！！1！11！！！",
反驳，原文我个人认为是打感叹号的一种网络表达方式

2024-08-29 04:16 UTC, jian3712 commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"item.projectexpansion.matter_upgrader.done": "升级完成，已消耗%EMC。",
原文就这样，要翻译成物品名

2024-08-29 04:16 UTC, jian3712 commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"item.projectexpansion.matter_upgrader.done": "升级完成，已消耗%EMC。",
原文就这样，要翻译成物品名？

2024-08-29 05:13 UTC, jian3712 commented
> 进度的问题很大，需要进一步修改
> 
> ![image](https://private-user-images.githubusercontent.com/137207191/362401253-36f686c4-f740-4243-b47b-9cb31417ce80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MDg2MzQsIm5iZiI6MTcyNDkwODMzNCwicGF0aCI6Ii8xMzcyMDcxOTEvMzYyNDAxMjUzLTM2ZjY4NmM0LWY3NDAtNDI0My1iNDdiLTljYjMxNDE3Y2U4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwNTEyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YWY0Mzg5ZWU2Nzg2YTRlM2MyODA1M2RmNjRiYjRjYzM3NWNjNDMxNjcyMTJhOGE1NDNiZWZkNWEyNDExM2I1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4blcPL-dB2V1spQNgqWX8eNI5NAxu4D4gkBf_3u1ab0)“终极之星” ![图像](https://private-user-images.githubusercontent.com/137207191/362401298-a1a657d4-3e6f-414f-95a5-60360c8b089c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MDg2MzQsIm5iZiI6MTcyNDkwODMzNCwicGF0aCI6Ii8xMzcyMDcxOTEvMzYyNDAxMjk4LWExYTY1N2Q0LTNlNmYtNDE0Zi05NWE1LTYwMzYwYzhiMDg5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwNTEyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZGY2MDkwYjYzNWFkZGI5MzRlNzE5NjRjN2U1ZjcwOWFkNzQ1ODJkNjUzZTEzMTU5YTBhMTlmZDQ0ZTVhZjE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.chCiDRJXwTpAO6GWfuo8z85OSugdqmlbY_vGJjMPei8) “高级炼金术箱子” ![图像](https://private-user-images.githubusercontent.com/137207191/362398915-a21c5e56-5699-49f1-a2ab-6620f8c95064.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MDg2MzQsIm5iZiI6MTcyNDkwODMzNCwicGF0aCI6Ii8xMzcyMDcxOTEvMzYyMzk4OTE1LWEyMWM1ZTU2LTU2OTktNDlmMS1hMmFiLTY2MjBmOGM5NTA2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwNTEyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzcyYjdjNjQwODdmN2UzMGI2ZTA1ZGFlNTE5NmYwM2I1NDU4MmFjMWU0YzlmMGE5ODgzYTllMThkZWVlNjJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RhTByw2jaMfDd8AMXIll4wFWjT_WXUA2HMfiPdE4yLk) “站在压缩太阳上” ![图像](https://private-user-images.githubusercontent.com/137207191/362401374-a9d5948d-0417-4fc0-9d3d-a4b8bc33e1ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MDg2MzQsIm5iZiI6MTcyNDkwODMzNCwicGF0aCI6Ii8xMzcyMDcxOTEvMzYyNDAxMzc0LWE5ZDU5NDhkLTA0MTctNGZjMC05ZDNkLWE0YjhiYzMzZTFlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwNTEyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OTllY2E4MGNhYzZkNmM2NWQyOWE5ZjZlNTc3N2ZkYTdjODRmZTM4YzgzODU1YjBiNzI0YWJkMzJkZGU4NDcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vg8yZwCsBQV1Ey9x87vCKnIUNl3RJhU4fkVh_UH3Xtw) ![图像](https://private-user-images.githubusercontent.com/137207191/362400347-fcbd752e-9aa6-482d-8386-7fd97b4e0161.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MDg2MzQsIm5iZiI6MTcyNDkwODMzNCwicGF0aCI6Ii8xMzcyMDcxOTEvMzYyNDAwMzQ3LWZjYmQ3NTJlLTlhYTYtNDgyZC04Mzg2LTdmZDk3YjRlMDE2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwNTEyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMTgyYzhkOTkzZGY5NTRjY2FmNzQyN2MzOWNmOTNlMGFhNjI0OGIyYTg3ZjFkOTMxZGJlMjhjYjRiMjM3MDQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BXElFICVDWHOkDNTj5q-4IlfE-uBLJ0eYFzwB59_wN8) “无限燃料”

原文就这样，确定要改成物品名吗？

2024-08-30 10:07 UTC, luoxueyasha requested changes

2024-08-30 10:07 UTC, luoxueyasha commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"advancements.projectexpansion.infinite_fuel.description": "那是一个十字架吗？管它呢，扔进熔炉里看它燃烧。",
还是生硬，cross和star就是本意
其他问题见@Fish-cat-cat 的指出，请自行订正修改

2024-08-30 10:32 UTC, jian3712 commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"advancements.projectexpansion.infinite_fuel.description": "那是一个十字架吗？管它呢，扔进熔炉里看它燃烧。",
现在看看

2024-09-02 11:44 UTC, jian3712 commented on projects/1.20/assets/project-expansion/projectexpansion/lang/zh_cn.json
> +	"advancements.projectexpansion.infinite_fuel.description": "那是一个十字架吗？管它呢，扔进熔炉里看它燃烧。",
改好了

2024-09-16 15:33 UTC, closed without merging