Jack's Economy翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4568
Opened 2024-08-11 11:03 UTC by zizunsi

2024-11-06 02:44 UTC, luoxueyasha requested changes

2024-11-06 02:44 UTC, luoxueyasha commented on projects/1.21/assets/flapjacks-economy/jackseconomy/lang/zh_cn.json
> +  "jackseconomy.sell_price": "售价(%s): %s",
```suggestion
  "jackseconomy.sell_price": "售价（%s）： %s",
```
标点符号应使用规范的汉语全角标点符号，具体要求请阅读我们的 [翻译规范](https://cfpa.site/TransRules/) 中 **03.标点符号** 这一节。
诸如这类的问题请在您翻译的所有文件中全部查明并修改。

除非ui实在太挤，否则还是建议使用全角标点

2024-11-06 02:44 UTC, luoxueyasha commented on projects/1.21/assets/flapjacks-economy/jackseconomy/lang/zh_cn.json
> +  "block.jackseconomy.currency_converter": "货币转换者",
确定是`转换者`吗

2024-11-06 02:44 UTC, luoxueyasha commented on projects/1.21/assets/flapjacks-economy/jackseconomy/lang/zh_cn.json
> +  "jackseconomy.subtitle.coin": "硬币的叮当声",
字幕格式见原版wiki
全文通查

2024-12-23 06:28 UTC, luoxueyasha commented on projects/1.21/assets/flapjacks-economy/jackseconomy/lang/zh_cn.json
> +  "block.jackseconomy.importer": "进口者",
我觉得这俩玩意应该不是XX者……XX器、XX机会更好一点
【要求】此类问题请全文通查并修改
例如空调 air conditioner

2024-12-23 06:28 UTC, luoxueyasha commented on projects/1.21/assets/flapjacks-economy/jackseconomy/lang/zh_cn.json
> +  "jackseconomy.max_storage": "大存储量: %s（已使用: %s）",
```suggestion
  "jackseconomy.max_storage": "大存储量：%s（已使用：%s）",
```
【要求】标点符号应使用规范的汉语全角标点符号，具体要求请阅读我们的 [翻译规范](https://cfpa.site/TransRules/) 中 **03.标点符号** 这一节。
诸如这类的问题请在您翻译的所有文件中全部查明并修改。

2024-12-31 02:37 UTC, luoxueyasha commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

@zizunsi

2025-01-13 15:39 UTC, SlimeSB requested changes

2025-01-13 15:39 UTC, SlimeSB requested changes
请注意查看先前未解决的建议

2025-02-06 02:54 UTC, luoxueyasha commented
@zizunsi 

- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

2025-02-14 14:07 UTC, closed without merging