MrCrayfish's Furniture Mod: Refurbished 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4604
Opened 2024-08-18 04:59 UTC by The-2070

2024-08-20 09:13 UTC, qznfbnj commented
路过，闲来无事，比较了三份翻译
https://gist.github.com/qznfbnj/abd4299dd308bf087bd08799e1e1e9ae

2024-09-05 13:10 UTC, mc-kaishixiaxue requested changes

2024-09-05 13:10 UTC, mc-kaishixiaxue commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "block.refurbished_furniture.azalea_hedge": "Azalea树篱",
树篱是用木头做的？
此外，`Azalea树篱`中的`Azalea`不就是原版的杜鹃花丛吗？这是用杜鹃花丛还是杜鹃树叶合成的？树篱的译名可以参考[这个](https://www.mcmod.cn/item/list/263-1.html?key=hedge)。

2024-09-05 13:10 UTC, mc-kaishixiaxue commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "gui.refurbished_furniture.progress": "%s %s %s",
这3个`%s`分别是什么？

2024-10-06 10:05 UTC, ChuijkYahus commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第二阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。审阅人将**直接**应用确定性的审查意见，若在7天内仍未做出任何实质性回应，则PR会被打上即将拒收标签并于24小时后关闭。

@The-2070 

虽然过了这么长时间才来看……

2024-10-14 14:08 UTC, closed without merging