Create more features1.20.1汉化文件提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4695
Opened 2024-10-02 13:21 UTC by Ballon-zzx

2024-10-02 13:23 UTC, Ballon-zzx commented
这个模组尚未上传到curseforge里面，只有modrith有

2024-10-03 02:07 UTC, dovisutu commented
/mv projects/1.20/assets/create_more_features/create_more_features projects/1.20/assets/modrinth-create_more_features/create_more_features

2024-10-03 02:09 UTC, Ballon-zzx commented
> /mv projects/1.20/assets/create_more_features/create_more_features projects/1.20/assets/modrinth-create_more_features/create_more_features

?

2024-10-03 02:10 UTC, Ballon-zzx commented
> /mv projects/1.20/assets/create_more_features/create_more_features projects/1.20/assets/modrinth-create_more_features/create_more_features

!感谢，我前面只上传过curseforge上面模组的汉化，modrith还没整过

2024-10-03 02:11 UTC, Ballon-zzx commented
> /mv projects/1.20/assets/create_more_features/create_more_features projects/1.20/assets/modrinth-create_more_features/create_more_features

是改成这个格式吗

2024-10-03 02:12 UTC, dovisutu commented
/mv projects/1.20/assets/modrinth-create_more_features/create_more_features projects/1.20/assets/modrinth-create-more-features/create_more_features/lang

2024-10-06 08:28 UTC, ChuijkYahus commented
/sort-keys projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/en_us.json
/sort-keys projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json

2024-10-06 09:48 UTC, ChuijkYahus requested changes

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "block.create_more_features.incomplete_signalling": "不完整的信号装置",
```suggestion
  "block.create_more_features.incomplete_dimmable_rose_quartz_lamp": "可调节玫瑰石英灯（半成品）",
  "block.create_more_features.incomplete_railway_decorative_casing": "列车装饰机壳（半成品）",
  "block.create_more_features.incomplete_signalling": "信号装置（半成品）",
```

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "block.create_more_features.railway_decorative_casing_wall": "铁路装饰护墙板",
```suggestion
  "block.create_more_features.railway_decorative_casing": "列车装饰机壳",
  "block.create_more_features.railway_decorative_casing_fence": "列车装饰机壳栅栏",
  "block.create_more_features.railway_decorative_casing_fence_gate": "列车装饰机壳栅栏门",
  "block.create_more_features.railway_decorative_casing_slab": "列车装饰机壳台阶",
  "block.create_more_features.railway_decorative_casing_stairs": "列车装饰机壳楼梯",
  "block.create_more_features.railway_decorative_casing_trapdoor": "列车装饰机壳活板门",
  "block.create_more_features.railway_decorative_casing_wall": "列车装饰机壳墙",
```

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "block.create_more_features.sulfur_basalt_ore": "硫磺玄武岩矿",
```suggestion
  "block.create_more_features.sulfur_basalt_ore": "玄武岩硫磺矿石",
```

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "block.create_more_features.sulfur_ore": "硫磺矿",
```suggestion
  "block.create_more_features.sulfur_ore": "硫磺矿石",
```

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "block.create_more_features.velcro": "velcro",
未翻译

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "item.create_more_features.incomplete_refined_radiance_sword": "半成品光辉石剑",
```suggestion
  "item.create_more_features.incomplete_diamond": "钻石（半成品）",
  "item.create_more_features.incomplete_gravitron": "引力仪（半成品）",
  "item.create_more_features.incomplete_refined_radiance_axe": "光辉石斧（半成品）",
  "item.create_more_features.incomplete_refined_radiance_pickaxe": "光辉石镐（半成品）",
  "item.create_more_features.incomplete_refined_radiance_shovel": "光辉石锹（半成品）",
  "item.create_more_features.incomplete_refined_radiance_sword": "光辉石剑（半成品）",
```

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "item.create_more_features.gravitron_base": "引力发生器基础",
```suggestion
  "item.create_more_features.gravitron_base": "引力仪基件",
```
gravitron与上方统一，这个方块在游戏内有什么用途

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "item_group.create_more_features.create_more_features_tab": "机械动力：更多村民",
features为何翻译成村民

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "item.create_more_features.refined_radiance_shovel": "光辉石铲",
```suggestion
  "item.create_more_features.refined_radiance_shovel": "光辉石锹",
```

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "item.create_more_features.refined_radiance_storage": "光辉水盒",
这个方块有什么用途

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "item.create_more_features.void_storage": "黑暗存储",
这个方块有什么用途

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "item.create_more_features.saltpeter": "盐酸",
```suggestion
  "item.create_more_features.saltpeter": "硝石",
```

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "painting.create_more_features.mr_fire.title": "火焰先生",
画作的名称和作者不翻译，请改回英语

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "block.create_more_features.refined_radiance_casing_stairs": "光辉石机壳楼梯",
```suggestion
  "block.create_more_features.refined_radiance_casing": "光辉机壳",
  "block.create_more_features.refined_radiance_casing_slab": "光辉机壳台阶",
  "block.create_more_features.refined_radiance_casing_stairs": "光辉机壳楼梯",
```
建议参照现有译名

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "item.create_more_features.shadow_ingot": "暗影石",
```suggestion
  "item.create_more_features.shadow_ingot": "暗影锭",
```
建议

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "msg.create_more_features.item_tooltip_fluids_storages_water_level": "水位等级",
```suggestion
  "msg.create_more_features.item_tooltip_fluids_storages_lava_level": "熔岩含量：",
  "msg.create_more_features.item_tooltip_fluids_storages_water_level": "水含量：",
```

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "msg.create_more_features.item_tooltip_cultural_sapling": "栽培树的幼苗是专门为工业树采伐而培育的，可以通过手动折断获得其树叶，此外，这种树的高度仅可达到3个方块，这使其非常适合自动化",
```suggestion
  "msg.create_more_features.item_tooltip_cultural_sapling": "栽培树的幼苗是专门为工业伐木而培育的，其树叶可以直接由空手破坏获得。此外，这种树最多只会长到3格高，非常适合自动化。",
```

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "msg.create_more_features.item_tooltip_fluids_storages": "这是一个可重复使用的容器，用于储存水或岩浆，按下【RС】键进行设置（【RС】+【Shift】），这些水箱不能从泵中填充，以保持平衡",
```suggestion
  "msg.create_more_features.item_tooltip_fluids_storages": "这是一个可重复使用的容器，用于储存水或熔岩。右击取出可流体，Shift右击放入流体。这些容器不能通过泵填充，以保持游戏平衡。",
```

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "msg.create_more_features.item_tooltip_flying_block": "该方块可以安装在空中，即无需支撑，在各种情况下都非常有用",
```suggestion
  "msg.create_more_features.item_tooltip_flying_block": "该方块可以直接在空中放置，无需存在其他方块，在各种情况下都非常有用",
```

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "msg.create_more_features.item_tooltip_graphite": "一种非常强大的燃料，但只有在堆栈中有超过10根石墨的情况下才会燃烧（作为燃料）！",
```suggestion
  "msg.create_more_features.item_tooltip_graphite": "一种非常强大的燃料，但只在同槽位中有超过10根石墨时可燃！",
```

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "msg.create_more_features.item_tooltip_gravitron_tooltip": "按住【Shift】键进行总结",
```suggestion
  "msg.create_more_features.item_tooltip_gravitron_tooltip": "按住 [Shift] 可查看概要",
```
create本体译法

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "msg.create_more_features.item_tooltip_gravitron": "此物品允许你在生存模式中像在创造模式中一样飞行。在此情况下，该物品的强度将被浪费，我建议对物品进行附魔。该物品可以用阴影锭进行修复！",
```suggestion
  "msg.create_more_features.item_tooltip_gravitron": "此物品可让你在生存模式中像创造模式一样飞行，如此会消耗该物品的耐久度，我建议进行附魔。该物品可以用暗影锭进行修复！",
```

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "msg.create_more_features.item_tooltip_lamp": "如果你多次发出红石信号，可调灯会逐渐打开和关闭，脉冲次数越多，闪烁次数越多。",
游戏内的实际表现是什么

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "msg.create_more_features.item_tooltip_lava": "用于创造下界石英，与水相互作用时有1/3的几率生成花岗岩",
```suggestion
  "msg.create_more_features.item_tooltip_lava": "用于制造下界岩，与水相互作用时有1/3的概率生成花岗岩",
```

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "advancements.dark_matter.descr": "通过用伊拉克拉降落到地牢的深渊中，然后拾取精致的光芒来制造阴影铸块",
```suggestion
  "advancements.dark_matter.descr": "携带光辉石时借助鞘翅飞入末地的深渊，以获得暗影锭",
```
翻译后记得检查译文

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "advancements.dazzling_beauty.title": "光辉石",
```suggestion
  "advancements.dazzling_beauty.descr": "制造一块光辉石",
  "advancements.dazzling_beauty.title": "光彩夺目",
```

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "advancements.domestication.descr": "种植培育树苗",
```suggestion
  "advancements.domestication.descr": "制造一株栽培树苗",
```

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "advancements.explosive_things.descr": "收集所有原料制作火药",
```suggestion
  "advancements.explosive_things.descr": "收集所有火药原料以制作火药",
```

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "advancements.legal_creativity.title": "合法创造",
```suggestion
  "advancements.legal_creativity.descr": "制造一台引力仪",
  "advancements.legal_creativity.title": "合法创造",
```

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "advancements.time_to_shop.descr": "创造任何新的",
```suggestion
  "advancements.time_to_shop.descr": "制造任一“机械动力”村民工作方块",
```

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "entity.minecraft.villager.create_more_features.buyer_of_mechanisms": "零件工",
```suggestion
  "entity.minecraft.villager.create_more_features.buyer_of_mechanisms": "构件购买员",
```

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "entity.minecraft.villager.create_more_features.contraptionstrader": "大机械师",
```suggestion
  "entity.minecraft.villager.create_more_features.contraptionstrader": "机构商",
```

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "entity.minecraft.villager.create_more_features.exchangerofmechanisms": "机械交换器",
```suggestion
  "entity.minecraft.villager.create_more_features.exchangerofmechanisms": "构件交易员",
```

2024-10-06 09:48 UTC, ChuijkYahus commented on projects/1.20/assets/modrinth-create-more-features/create_more_features/lang/zh_cn.json
> +  "entity.minecraft.villager.create_more_features.sellerofmechanisms": "机械师",
```suggestion
  "entity.minecraft.villager.create_more_features.sellerofmechanisms": "机构售卖员",
```

2024-10-29 03:18 UTC, dovisutu commented
ping @Ballon-zzx 请及时查阅并回应审查意见。

2024-10-29 09:00 UTC, luoxueyasha commented
- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

@Ballon-zzx 


@dovisutu 以后7+7用这套话术，加`即将被搁置`，否则bot不进处理流程

2024-11-06 20:09 UTC, closed without merging