MrCrayfish's Furniture Mod: Refurbished 翻译提交（另一个pr已关闭）
CFPAOrg/Minecraft-Mod-Language-Package pull request #4710
Opened 2024-10-07 05:39 UTC by CaptBK13

https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/4604
上一个提交翻译的pr已经关闭了
根据这位提供的对比https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/4604#issuecomment-2298371304
以及百科看到的另一份翻译
经过我自己排查，以及上一个pr所提到修改建议，整体应该是没什么问题了
subtitle都已修正（可能有错误）
桌子，椅子，我对比了旧版mod的最新翻译，确实就是桌和椅，而不是桌子椅子
（我也觉得两者皆可吧，秉持着遵循传统我就写桌椅了）
至于提到的三个%s是什么，原英文文件就这样
本人只是做了一部分整理和修改，感谢前人栽树

2024-10-07 05:48 UTC, CaptBK13 commented
coin_miner究竟是什么我属实不太明白，翻译大体应该是没什么大毛病的

2024-10-07 11:17 UTC, mc-kaishixiaxue requested changes

2024-10-07 11:17 UTC, mc-kaishixiaxue commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "block.refurbished_furniture.oak_bath": "橡木木浴缸",
```suggestion
    "block.refurbished_furniture.oak_bath": "橡木浴缸",
```

2024-10-07 11:17 UTC, mc-kaishixiaxue commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "computer_program.refurbished_furniture.home_control.info": "家用控制允许你控制连接在电力网络上的设备的电源。设备必须连接到与计算机相同的网络才能被发现。在放置前使用铁砧重命名设备，以便在应用中更容易识别。",
第468行的`Computer`翻译的是`电脑`，这里却是`计算机`。

2024-10-07 11:30 UTC, CaptBK13 commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "computer_program.refurbished_furniture.home_control.info": "家用控制允许你控制连接在电力网络上的设备的电源。设备必须连接到与计算机相同的网络才能被发现。在放置前使用铁砧重命名设备，以便在应用中更容易识别。",
修正468行，改为计算机

2024-10-08 12:18 UTC, mc-kaishixiaxue requested changes

2024-10-08 16:24 UTC, CaptBK13 commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "computer_program.refurbished_furniture.home_control.info": "家用控制允许你控制连接在电力网络上的设备的电源。设备必须连接到与计算机相同的网络才能被发现。在放置前使用铁砧重命名设备，以便在应用中更容易识别。",
采用家居控制

2024-10-09 14:05 UTC, mc-kaishixiaxue approved these changes
现在的译名没有问题了

2024-10-09 14:06 UTC, mc-kaishixiaxue approved these changes
现在的译名没有问题了

2024-10-13 11:00 UTC, ChuijkYahus reviewed
“抽屉”可以改成“抽屉柜”或者“排柜”，不过是否更改都随意

话说能改成组合文件吗，实在不行我来改（）

2024-10-13 11:00 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "filterCategory.refurbished_furniture.general.desc": "所有基础家具。椅子、桌子等等",
```suggestion
    "filterCategory.refurbished_furniture.general.desc": "所有基础家具，椅子、桌子等等",
```
为改硬改的产物，后方如有键中句号键尾无句号的情况建议同样更改

2024-10-13 11:00 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "block.refurbished_furniture.cherry_crate": "樱花木箱",
CFM版本和下方容器名译文为`板条箱`，建议同步

2024-10-13 11:00 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "block.refurbished_furniture.cherry_cutting_board": "樱花木切菜板",
仅建议，“砧板”怎么样

2024-10-13 11:00 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "block.refurbished_furniture.stone_stepping_stones": "石质踏脚石",
```suggestion
    "block.refurbished_furniture.stone_stepping_stones": "石头踏脚石",
```

2024-10-13 11:00 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "block.refurbished_furniture.black_basin": "黑色洗脸盆",
仅建议，“洗手池”怎么样

2024-10-13 11:00 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "block.refurbished_furniture.cherry_lattice_fence_gate": "樱花木格子栅栏门",
仅建议，把“格子”改为“格饰”怎么样

2024-10-13 11:00 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "block.refurbished_furniture.milk": "牛奶",
```suggestion
    "block.refurbished_furniture.milk": "奶",
```
原版译名更改

2024-10-13 11:00 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "gui.refurbished_furniture.search": "搜索...",
```suggestion
    "gui.refurbished_furniture.search": "搜索……",
```
全角省略号，全文通查

2024-10-13 11:00 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "block.refurbished_furniture.black_lamp": "黑色灯",
仅建议，可以改成“台灯”，避免和原版红石灯之类的冲突

2024-10-13 11:00 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "gui.refurbished_furniture.package_open": "右键打开",
```suggestion
    "gui.refurbished_furniture.package_open": "右击打开",
```

2024-10-13 11:00 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "gui.refurbished_furniture.jei_campfire_info": "继承自篝火烹饪",
```suggestion
    "gui.refurbished_furniture.jei_campfire_info": "继承自营火烹饪",
```
原版术语

2024-10-13 11:00 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "gui.refurbished_furniture.progress": "%s %s %s",
这个键的实际显示是怎么样的

2024-10-13 11:00 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "gui.refurbished_furniture.placeable": "可放置",
这些是显示在原版配方界面的吗

2024-10-13 11:00 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "subtitle.refurbished_furniture.recycle_bin_engine": "碾压声",
```suggestion
    "subtitle.refurbished_furniture.recycle_bin_engine": "碾压",
```
这些个人建议不需要“声”字，原版的`啜饮`等也没有

2024-10-13 11:00 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "subtitle.refurbished_furniture.lightswitch_flick": "开关声",
```suggestion
    "subtitle.refurbished_furniture.lightswitch_flick": "开关：拨动",
```
算是妥协了，其他键也可以这样处理，但不推荐

2024-10-13 11:00 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "block.refurbished_furniture.black_cooler": "黑色冷却器",
要求改为“冷藏箱”，与后文统一，全文通查

2024-10-13 11:00 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "subtitle.refurbished_furniture.stove.close": "烤箱：关闭",
Stove一词现有“烤箱”“炉灶”“炉子”三个译名，要求统一
游戏内看应该是烤箱和电磁炉合一块，推荐“炉灶”

2024-10-13 11:00 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "smart_device.refurbished_furniture.freezer": "冰箱",
```suggestion
    "smart_device.refurbished_furniture.freezer": "冰柜",
```
与上方统一

2024-10-13 11:02 UTC, ChuijkYahus commented
桌子椅子个人觉得可以更改，没什么问题，问就是大更改翻译（）

2024-10-13 11:04 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "gui.refurbished_furniture.progress": "%s %s %s",
经检验，这些对应“1 / 64”等进度显示，无需更改

2024-10-13 12:04 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "gui.refurbished_furniture.placeable": "可放置",
![0c30e3e00ff33197dc6c4e6269170a72](https://github.com/user-attachments/assets/53522661-f486-41e7-b9e7-bf27128dbe41)
启用配置后显示
![77d0c26e7e84a67f3ad599d51aecc2e0](https://github.com/user-attachments/assets/4896d1a8-3b48-4df3-9255-0eeda843aebb)
![db1273b97af4e4d7c569d79ac9422d4b](https://github.com/user-attachments/assets/51b7ce38-3a3a-4737-b08d-d721dfb7ec7a)
无需更改

2024-10-13 14:13 UTC, mc-kaishixiaxue requested changes

2024-10-13 14:13 UTC, mc-kaishixiaxue commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "block.refurbished_furniture.red_lamp": "红色台台灯",
你是怎么多打一个字的？

2024-10-13 15:30 UTC, ChuijkYahus commented
先更改为组合文件模式，暂时不要推更新

`台灯`这个我给一起改了，之后注意 @CaptBK13

2024-10-13 16:04 UTC, ChuijkYahus commented
组合文件经检验无误，可以推更新了

2024-10-13 16:45 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn-base.json
> +    "filterCategory.refurbished_furniture.bathroom.desc": "马桶、洗手盆等等",
```suggestion
    "filterCategory.refurbished_furniture.bathroom.desc": "马桶、洗手池等等",
```
统一译名

2024-10-13 16:45 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn-base.json
> +    "filterCategory.refurbished_furniture.outdoors.desc": "邮箱、树篱、围栏等等",
```suggestion
    "filterCategory.refurbished_furniture.outdoors.desc": "邮箱、树篱、栅栏等等",
```
原版术语，也为与模组内统一名称

2024-10-13 16:45 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn-base.json
> +    "block.refurbished_furniture.workbench": "工作台",
```suggestion
    "block.refurbished_furniture.workbench": "工作站",
```
与原版工作台区分，全文通查

2024-10-13 16:45 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn-base.json
> +    "block.refurbished_furniture.recycle_bin": "回收桶",
建议（可不更改）
这个印象中直接叫“垃圾桶”更多，改则全文更改

2024-10-13 16:45 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn-base.json
> +    "item.refurbished_furniture.glow_berry_jam_toast": "发光浆果酱吐司",
```suggestion
    "item.refurbished_furniture.glow_berry_jam": "发光浆果果酱",
    "item.refurbished_furniture.glow_berry_jam_toast": "发光浆果果酱吐司",
```
与甜浆果果酱统一命名格式
是我之前没说清楚

2024-10-13 16:45 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn-base.json
> +    "container.refurbished_furniture.freezer": "冰柜",
```suggestion
    "container.refurbished_furniture.freezer": "冷冻室",
```
建议改为“冷冻室”，实际表现是两格高的冰箱的下方那格，全文通查
冰柜一般指的是小卖部里那些用来装冰棍雪糕的冷藏柜子，和这个不太符合

2024-10-13 16:45 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn-base.json
> +    "gui.refurbished_furniture.package_message": "包裹消息",
```suggestion
    "gui.refurbished_furniture.enter_message": "输入留言……",
    "gui.refurbished_furniture.package_message": "包裹留言",
```

2024-10-13 16:45 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn-base.json
> +    "gui.refurbished_furniture.post_box_info": "从列表中选择一个邮箱，你可以通过名称搜索邮箱，或者通过在名称前加上@来搜索玩家，将物品放入包裹槽中，并可选择包含一条消息，点击发送按钮以递送包裹。",
```suggestion
    "gui.refurbished_furniture.post_box_info": "选择列表中的一个信箱。可以按名称搜索信箱，也可附带“@”前缀搜索玩家名。在包裹槽位中放入物品，留言可选。单击发送按钮即会送出包裹。",
```
来自库内此部分游戏内容的前身
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/projects/1.20/assets/mighty-mail/mighty_mail/lang/zh_cn.json

可以不更改，但如果上方“消息”一条选择更改，此句中的“消息”也需改为“留言”

2024-10-13 16:45 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn-base.json
> +    "gui.refurbished_furniture.link_outside_area": "链路超出供电区域",
```suggestion
    "gui.refurbished_furniture.link_unpowerable": "链接无法供电",
    "gui.refurbished_furniture.link_outside_area": "链接超出供电区域",
```
建议（可不更改但推荐更改）
与上方L101统一名称，链路这个名称比较偏通信吧，如改则全文通查

2024-10-13 16:45 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn-base.json
> +    "subtitle.refurbished_furniture.frying_pan.step": "金属：脚步",
```suggestion
    "subtitle.refurbished_furniture.frying_pan.place": "金属：被放置",
    "subtitle.refurbished_furniture.frying_pan.step": "金属：脚步声",
```
经检查为放置平底锅和在平底锅上行走时的音效，故根据原版字幕更改

2024-10-13 16:45 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn-base.json
> +    "subtitle.refurbished_furniture.frying_pan.sizzling": "嘶嘶",
```suggestion
    "subtitle.refurbished_furniture.frying_pan.sizzling": "滋滋",
```
换了个拟声词，形容煎肉烤肉时更常用

2024-10-13 16:45 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn-base.json
> +    "subtitle.refurbished_furniture.cutting_board.place_ingredient": "物品：放置",
```suggestion
    "subtitle.refurbished_furniture.cutting_board.place_ingredient": "物品：被放置",
```
同上理由

2024-10-13 16:45 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn-base.json
> +    "subtitle.refurbished_furniture.stove.close": "炉灶：关闭",
```suggestion
    "subtitle.refurbished_furniture.stove.open": "烤箱：打开",
    "subtitle.refurbished_furniture.stove.close": "烤箱：关闭",
```
算是遵循原文，毕竟炉灶下方有个烤箱，也确实是打开或关上烤箱时的音效

2024-10-13 16:45 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn-base.json
> +    "subtitle.refurbished_furniture.workbench.craft": "物品：建造",
```suggestion
    "subtitle.refurbished_furniture.workbench.craft": "物品：组装",
```

2024-10-13 16:45 UTC, ChuijkYahus commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn-base.json
> +    "computer_program.refurbished_furniture.home_control.info": "家居控制允许你控制连接在电力网络上的设备的电源，设备必须连接到与电脑相同的网络才能被发现，在放置前使用铁砧重命名设备，以便在应用中更容易识别。",
```suggestion
    "computer_program.refurbished_furniture.home_control.info": "“家居控制”用于控制接电设备的电源。设备需与电脑处于同一网络才可控制。在放置设备前可使用铁砧重命名，以便在应用中识别。",
```
建议（可不更改）
算是整体乱改了一通

如不更改，也建议`家居控制`两侧加上中文双引号

2024-10-13 20:11 UTC, CaptBK13 commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn-base.json
> +    "block.refurbished_furniture.recycle_bin": "回收桶",
他在游戏里有通过往里面放物品回收成经验的功能，我个人认为回收还是更合适一点

2024-10-13 20:16 UTC, CaptBK13 commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn.json
> +    "block.refurbished_furniture.red_lamp": "红色台台灯",
大概是我批量替换的时候……

2024-10-14 04:29 UTC, ChuijkYahus approved these changes

2024-10-15 11:53 UTC, ChuijkYahus commented
标签已打，等待合并了

2024-10-15 14:39 UTC, SlimeSB commented on projects/1.20/assets/refurbished-furniture/refurbished_furniture/lang/zh_cn-base.json
> +    "gui.refurbished_furniture.experience_points": "%s 点",
```suggestion
    "gui.refurbished_furniture.experience_level": "%s/%s级",
    "gui.refurbished_furniture.experience_points": "%s点",
```

2024-10-15 17:04 UTC, ChuijkYahus approved these changes

2024-10-17 06:39 UTC, merged