统一库内“土豆”丨“马铃薯”的翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #4738
Opened 2024-10-22 09:42 UTC by AnzhiZhang

根据 #3935 中各位仓库维护者的指示精神，提出此相关问题联动 PR

早上好CFPA，现在我有~土豆~ 马铃薯！

2011年/2016年的《现代汉语词典》推荐规范字形为`马铃薯`，且2020年《食品科学技术名词》规定为`马铃薯`。 本pr因此将库内的`土豆`统一进行修改为`马铃薯`。

---

根据 #3935 中各位仓库维护者的指示精神，补充以下依据：

- 《[现代汉语词典](https://cd.hwxnet.com/view/ahjnmjmpjmcefmkb.html)》在线查询结果：
  - 土豆：词典解释 马铃薯。[potato] [口]∶马铃薯
  - 马铃薯：词典解释 又称“土豆”、“洋山芋”等。双子叶植物，茄科。多年生草本。作一年生栽培。地下茎膨大成块茎，有黄、白、淡红、紫色，呈圆、卵圆、椭圆形，表皮有芽眼。多用块茎繁殖。原产南美洲，中国普遍栽培。块茎富含淀粉，除作粮食和蔬菜外，也用于制造酒精。(1) [potato]
- 《食品科学技术名词》在线检索
  - [土豆](https://termonline.cn/search?searchText=%E5%9C%9F%E8%B1%86)：抱歉，您搜索的词尚未审定。
  - [马铃薯](https://termonline.cn/search?searchText=%E9%A9%AC%E9%93%83%E8%96%AF)：英文对照：potato 学科领域： 「农学名词」「食品科学技术名词」
- 根据[CCL语料库检索系统](http://ccl.pku.edu.cn:8080/ccl_corpus)的搜索结果，“马铃薯”一词在 **9180** 个文档中出现，而“土豆”共在 **26309** 个文档中出现。
> 根据国内版必应使用“马铃薯”与“土豆”作为关键词并排除对方后的搜索结果，搜索“马铃薯”只有**159,000**条结果，搜索“土豆”有**382,000**条结果。

---

根据以上信息，权威标准对翻译用词没有争议，而根据 https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/3935#issuecomment-2426472961 提出的 `使用词频、行业标准乃至原文上下文亦应该是影响因素`，“土豆” 是词频使用更多的用词。

2024-10-22 11:08 UTC, luoxueyasha reviewed
![OIP-C(2).jpg](https://github.com/user-attachments/assets/e371b220-412d-4f22-a316-50c62728820e)

2024-10-22 11:08 UTC, luoxueyasha commented on projects/1.12.2/assets/avaritia-tweaks/avaritiatweaks/lang/zh_cn.lang
> +botania.lexicon.infinitato=无尽小马铃薯
`小土豆`是人名以及固定术语，植魔情境下应当维持原译
请全文通查并修改

```suggestion
botania.lexicon.infinitato=无尽小土豆
```

2024-10-22 11:08 UTC, luoxueyasha commented on projects/1.12.2/assets/botania-tweaks/botania_tweaks/lang/zh_cn.lang
> +tile.botania_tweaks.compressed_tiny_potato_1.name=微型马铃薯
需要讨论和结合游戏实际情况
暂时别resolve

2024-10-22 11:08 UTC, luoxueyasha commented on projects/1.12.2/assets/crossroads-mc/crossroads/lang/zh_cn.lang
> +lore.grindstone.post_recipe=§r§r磨石有一个I=1的内部齿轮。磨石在运行时每 tick 都使 用来自内部齿轮的全部能量，因此它在更高的速度下运行得更快（每 tick 中齿轮 里的能量更多）。齿轮可以从顶部连接到磨石。磨碎一个物品需要消耗100能量。物品可以从除了底部的任何面插入。早期，一个手摇曲柄就足以运行磨石，尽管很慢。磨石的可用配方如下：铜矿石->2个铜粉+沙子
口语情景 建议不替换

2024-10-22 11:08 UTC, luoxueyasha commented on projects/1.12.2/assets/electroblobs-wizardry/ebwizardry/lang/zh_cn.lang
> +config.ebwizardry.use_shaders.false=关闭——我用马铃薯玩MC
需要确认原文
口语情景 疑似无需替换

2024-10-22 12:01 UTC, SlimeSB commented
基本上和原版马铃薯相关的确实需要改成马铃薯，不过修改范围应该只包括物品名和长句中引用的物品名。
对于落雪标记出（以及未标记出但确实是）的“口语语境”部分使用二者均可，可不更改，也不会对搜索产生影响。
在网络上用来指代“电脑配置差”的语境下使用“土豆”更多，也可使用“马铃薯”彰显“假正经”的风味。
请你重新自校一遍，而非批量ctrl+h。

2024-10-22 12:05 UTC, AnzhiZhang commented on projects/1.12.2/assets/electroblobs-wizardry/ebwizardry/lang/zh_cn.lang
> +config.ebwizardry.use_shaders.false=关闭——我用马铃薯玩MC
```suggestion
config.ebwizardry.use_shaders.false=关闭——我用土豆玩MC
```

2024-10-22 12:07 UTC, AnzhiZhang commented on projects/1.12.2/assets/electroblobs-wizardry/ebwizardry/lang/zh_cn.lang
> +config.ebwizardry.use_shaders.false=关闭——我用马铃薯玩MC
No - I'm running this on a potato

2024-10-22 12:10 UTC, AnzhiZhang commented on projects/1.12.2/assets/botania-tweaks/botania_tweaks/lang/zh_cn.lang
> +tile.botania_tweaks.compressed_tiny_potato_1.name=微型马铃薯
原文 Little Potato，不存在 "在网络上用来指代“电脑配置差”的语境下" 的问题

2024-10-22 12:12 UTC, AnzhiZhang commented
关于口语语境问题，应当推广使用马铃薯，替换土豆的表达。

另附群内的观点：

> 国务院于1987年8月12日明确批示，经全国自然科学名词审定委员会审定公布的名词具有权威性和约束力，全国各科研、教学、生产经营以及新闻出版等单位应遵照使用。

2024-10-22 12:30 UTC, SlimeSB commented
细究二者有区别，在于：
ice cream 是纯粹的泊来词，冰淇淋/冰激凌的统一是一个“一致性”问题，且该词语历史短，有统一的可能性，面临的争议也少。
土豆/马铃薯/洋芋 自明朝传入，经过长时间的发展已经产生了“方言化”而成为地道中文的一部分。三者（或更多）不存在孰优孰劣，也可作为风味文本保留，统一仅为了方便搜索等。我想原版敲定为“马铃薯”也是本PR开头提到的原因（术语+规范等）。
尽管如此，却可以加特例，甚至在术语在线也可以查到的“hot potato algorithm”热土豆算法。所以我认为“土豆”在非食品领域发挥余地很大。

2024-10-22 12:53 UTC, AnzhiZhang commented on projects/1.12.2/assets/crossroads-mc/crossroads/lang/zh_cn.lang
> +lore.grindstone.post_recipe=§r§r磨石有一个I=1的内部齿轮。磨石在运行时每 tick 都使 用来自内部齿轮的全部能量，因此它在更高的速度下运行得更快（每 tick 中齿轮 里的能量更多）。齿轮可以从顶部连接到磨石。磨碎一个物品需要消耗100能量。物品可以从除了底部的任何面插入。早期，一个手摇曲柄就足以运行磨石，尽管很慢。磨石的可用配方如下：铜矿石->2个铜粉+沙子
口语情景也可以使用 “马铃薯” ，推广规范化语言。

> 土豆/马铃薯/洋芋 自明朝传入，经过长时间的发展已经产生了“方言化”而成为地道中文的一部分。三者（或更多）不存在孰优孰劣，也可作为风味文本保留，统一仅为了方便搜索等。我想原版敲定为“马铃薯”也是本PR开头提到的原因（术语+规范等）。

2024-10-22 12:56 UTC, SlimeSB commented on projects/1.12.2/assets/crossroads-mc/crossroads/lang/zh_cn.lang
> +lore.grindstone.post_recipe=§r§r磨石有一个I=1的内部齿轮。磨石在运行时每 tick 都使 用来自内部齿轮的全部能量，因此它在更高的速度下运行得更快（每 tick 中齿轮 里的能量更多）。齿轮可以从顶部连接到磨石。磨碎一个物品需要消耗100能量。物品可以从除了底部的任何面插入。早期，一个手摇曲柄就足以运行磨石，尽管很慢。磨石的可用配方如下：铜矿石->2个铜粉+沙子
有待讨论

2024-10-22 14:14 UTC, luoxueyasha commented on projects/1.12.2/assets/botania-tweaks/botania_tweaks/lang/zh_cn.lang
> +tile.botania_tweaks.compressed_tiny_potato_1.name=微型马铃薯
https://www.mcmod.cn/item/47844.html
原版植物魔法的`Little Potato`是作者特意留下的一个彩蛋，`小土豆`作为社区广为流传的俗名，不应修改（先来后到原则，毕竟这个在玩家群体的压力下是真的动不得）。

2024-10-22 15:11 UTC, AnzhiZhang commented on projects/1.12.2/assets/botania-tweaks/botania_tweaks/lang/zh_cn.lang
> +tile.botania_tweaks.compressed_tiny_potato_1.name=微型马铃薯
明白，和那夸达一样，以社区习惯为准

2024-10-24 03:22 UTC, Cyl18 requested changes
<!---->

2024-11-18 23:23 UTC, luoxueyasha commented
#关于#3935 及相关PR的处理

关于#3935 与 #4738 #4739 #4740 （下文称“相关PR”）的相关问题讨论如下：
* #3935 与相关PR的改动本质不同，#3935 为同一汉语词汇的两种字形的变更，相关PR为两个同义或近义汉语词汇的相互替换。从语义上来讲，相关PR的相互替换会构成一定程度的语义变更，而#3935 不会。
* #3935 出于统一游戏内搜索关键词、统一模组翻译用语的目的提出；但就目前的汉语语言环境，“冰淇淋”“冰激凌”均有较高的使用频率，各方标准的推荐字形也不一致（数据见#3935 内的讨论）。其中近年网络交流环境与食品工业环境推倡“冰淇淋”，而《现代汉语词典》与出版业推倡“冰激凌”。
* 相关PR内具有大量的忽略原文内容、强制统一而做出的修改，例如“小土豆”→“小马铃薯”（“Tiny Potato”, Botania（植物魔法）），这是违反《[翻译规范](https://cfpa.site/TransRules/)》 06. 专有名词 一节的。
* 相关PR的数据支持与论据不足。例如#4738 在已给出“土豆”为词频使用更多的情况下，仍然选择强制统一为“马铃薯”（不论语境），自相矛盾。
* 相关PR具有破坏嫌疑，表现为借用#3935 内的讨论格式，通过全库批量替换提出大量的修改请求。
* 库内原版名词不统一（例如土豆→马铃薯）的问题客观存在。

经内部协商讨论，关于#3935 相关 Pull Request 及 Issue 处理结果如下：
* 基于实际语言环境与“铁质/铁制”原则，不强制模组间统一“冰激凌”/“冰淇淋”。#3935 的改动只有6行，影响较小；库内标准化为“冰淇淋”的理由充足（见#3935 讨论），可以保留此PR。但其提交的模组文本落后于模组最新版文本，可能面临进入3+7流程。若需要合并，则仍需公示。
* 因为破坏性，关闭相关PR（#4738、#4379、#4740）。若@AnzhiZhang 仍需提交对“土豆/马铃薯”在合理语境（如：Minecraft原版）下的术语统一，需另开Pull Request，且仍需审阅后公示。相关pr内交流时，各方应注意讨论礼仪。
* 另提交对贡献方针中“铁质/铁制”原则的扩充Pull Request，由@luoxueyasha 提交。
* CFPA对于“Icecream”的译法，以及“冰激凌”/“冰淇淋”的字形没有推荐。在合理的语境下，可以使用“冰激凌”、“冰淇淋”、“雪糕”、“冰棍”、“冻奶油”等译名（需要做到模组内/联动、附属模组间统一）。

特此公告。有异议请于#3935 下提出。

2024-11-18 23:23 UTC, closed without merging