modrinth-Deep Drilling 翻译提交
CFPAOrg/Minecraft-Mod-Language-Package pull request #4748
Opened 2024-10-24 03:47 UTC by JsMkSmStf

2024-11-25 02:50 UTC, luoxueyasha requested changes

2024-11-25 02:50 UTC, luoxueyasha commented on projects/1.20/assets/modrinth-deepdrilling/deepdrilling/lang/zh_cn.json
> +  "block.deepdrilling.blank_module.tooltip.behaviour1": "_没什么用_... 但可以用来_连接_其他模块。",
```suggestion
  "block.deepdrilling.blank_module.tooltip.behaviour1": "_没什么用_……但可以用来_连接_其他模块。",
```
标点符号应使用规范的汉语全角标点符号，具体要求请阅读我们的 [翻译规范](https://cfpa.site/TransRules/) 中 **03.标点符号** 这一节。
诸如这类的问题请在您翻译的所有文件中全部查明并修改。

需要实际检查游戏内是否存在显示问题，如果存在则需要在省略号后加空格或者使用三个英文句点代替

2024-11-25 02:50 UTC, luoxueyasha commented on projects/1.20/assets/modrinth-deepdrilling/deepdrilling/lang/zh_cn.json
> +  "block.deepdrilling.collection_filter.tooltip.behaviour1": "可以_收集采掘出的矿物_，但存储有上限，多余的矿物会从侧面的孔中_溢出_。",
这个存储上限指的是存储模块的上限还是钻头的上限？
原文`_Collects items_ that would otherwise be _dropped on the ground_.`
看着像是指如果不加模块，那么掉落物就会被扔到地上

2024-11-25 02:50 UTC, luoxueyasha commented on projects/1.20/assets/modrinth-deepdrilling/deepdrilling/lang/zh_cn.json
> +  "block.deepdrilling.collection_filter.tooltip.condition2": "对此模块右键",
`右键`不是一个完整的状语，需要一个动作补全

```suggestion
  "block.deepdrilling.collection_filter.tooltip.condition2": "对此模块右击",
```

2024-11-26 00:47 UTC, luoxueyasha commented on projects/1.20/assets/modrinth-deepdrilling/deepdrilling/lang/zh_cn.json
> +  "block.deepdrilling.collection_filter.tooltip.behaviour1": "可以_收集采掘出的矿物_，但存储有上限，多余的矿物会从侧面的孔中_溢出_。",
这条讨论需要被pr提交者回复。
你的回复可能处于pending状态，这会导致其他人看不到你的评论。具体解决方法可以参考[Github社区讨论](https://github.com/orgs/community/discussions/10369)。

最好是根据原文翻译。

2024-11-27 06:36 UTC, luoxueyasha commented on projects/1.20/assets/modrinth-deepdrilling/deepdrilling/lang/zh_cn.json
> +  "block.deepdrilling.collection_filter.tooltip.behaviour1": "可以_收集采掘出的矿物_，但存储有上限，多余的矿物会从侧面的孔中_溢出_。",
不是你别resolve这条啊，我这边手机审没法开游戏，需要你回复来确认游戏内的具体内容

2024-11-27 06:40 UTC, JsMkSmStf commented on projects/1.20/assets/modrinth-deepdrilling/deepdrilling/lang/zh_cn.json
> +  "block.deepdrilling.collection_filter.tooltip.behaviour1": "可以_收集采掘出的矿物_，但存储有上限，多余的矿物会从侧面的孔中_溢出_。",
"block.deepdrilling.collection_filter.tooltip.behaviour1": "能够_收集_本会_掉落在地上_的产物。",
这样回复吗
以前没整过不知道不好意思

2024-11-27 06:41 UTC, luoxueyasha commented on projects/1.20/assets/modrinth-deepdrilling/deepdrilling/lang/zh_cn.json
> +  "deepdrilling.loot.rare": "富集矿石",
这几个稀有度的显示位置？需要游戏内截图

2024-11-27 06:41 UTC, luoxueyasha commented on projects/1.20/assets/modrinth-deepdrilling/deepdrilling/lang/zh_cn.json
> +  "block.deepdrilling.sludge_pump.tooltip.behaviour1": "_提高采掘效率_的同时_小幅增加钻头的损耗_，但会降低采掘产物的_质量和数量_且积累_淤泥_。",
原文reduces damage taken……增加损耗？

2024-11-27 06:45 UTC, JsMkSmStf commented on projects/1.20/assets/modrinth-deepdrilling/deepdrilling/lang/zh_cn.json
> +  "deepdrilling.loot.rare": "富集矿石",
![Snipaste_2024-11-27_14-45-32](https://github.com/user-attachments/assets/e9e89fc3-5c77-48f2-9189-59daba9e9555)

2024-11-27 07:29 UTC, luoxueyasha commented on projects/1.20/assets/modrinth-deepdrilling/deepdrilling/lang/zh_cn.json
> +  "block.deepdrilling.collection_filter.tooltip.behaviour1": "可以_收集采掘出的矿物_，但存储有上限，多余的矿物会从侧面的孔中_溢出_。",
不是，就是好奇为啥之前这么翻译，不按原文走；你拿截图和白话解释清楚就行
我想知道这个模块在游戏内的功能和表现是什么样的，因为我上班忙摸不到游戏，目前就用手机审pr，所以需要翻译者自述（算是答辩的一种

2024-11-27 07:34 UTC, luoxueyasha commented on projects/1.20/assets/modrinth-deepdrilling/deepdrilling/lang/zh_cn.json
> +  "deepdrilling.loot.rare": "富集矿石",
那L41的`surface deposit`和这里的`Earth`的关系是？

2024-11-30 07:49 UTC, komeiji-koyomi commented on projects/1.20/assets/modrinth-deepdrilling/deepdrilling/lang/zh_cn.json
> +  "deepdrilling.loot.rare": "富集矿石",
L41那个结构包含的方块基本就是此处“零碎矿渣”的产出，同时机械动力本体自带的矿脉也是由这些方块构成

2024-12-12 04:49 UTC, luoxueyasha commented on projects/1.20/assets/modrinth-deepdrilling/deepdrilling/lang/zh_cn.json
> +  "deepdrilling.ponder.tag.drilling.description": "与从地脉深处提取产物物相关的模块……",
```suggestion
  "deepdrilling.ponder.tag.drilling.description": "与从地脉深处提取产物相关的模块……",
```
这个deep drilling也是模块吗
原文Components related to extracting resources from deep within the earth

2024-12-13 02:24 UTC, luoxueyasha commented on projects/1.20/assets/modrinth-deepdrilling/deepdrilling/lang/zh_cn.json
> +  "deepdrilling.ponder.tag.drilling.description": "与从地脉深处提取产物物相关的模块……",
我看不到您的回复，请检查您的回复是否在pending状态。
您可以参考https://github.com/orgs/community/discussions/10369 来放出pending状态的回复。

2024-12-15 08:27 UTC, JsMkSmStf commented on projects/1.20/assets/modrinth-deepdrilling/deepdrilling/lang/zh_cn.json
> +  "deepdrilling.ponder.tag.drilling.description": "与从地脉深处提取产物物相关的模块……",
现在能看到了吗
前几次回复没确认也能看见 我以为不用确认

2024-12-16 11:12 UTC, luoxueyasha commented on projects/1.20/assets/modrinth-deepdrilling/deepdrilling/lang/zh_cn.json
> +  "deepdrilling.ponder.tag.drilling.description": "与从地脉深处提取产物物相关的模块……",
可以了

2024-12-16 11:14 UTC, luoxueyasha commented on projects/1.20/assets/modrinth-deepdrilling/deepdrilling/lang/zh_cn.json
> +  "deepdrilling.ponder.tag.drilling.description": "与从地脉深处提取产物物相关的模块……",
```suggestion
  "deepdrilling.ponder.tag.drilling.description": "与从地脉深处提取产物相关的各类组件……",
```
按组件翻吧

2024-12-17 12:45 UTC, JsMkSmStf commented on projects/1.20/assets/modrinth-deepdrilling/deepdrilling/lang/zh_cn.json
> +  "deepdrilling.ponder.tag.drilling.description": "与从地脉深处提取产物物相关的模块……",
改了

2024-12-18 02:28 UTC, luoxueyasha commented on projects/1.20/assets/modrinth-deepdrilling/deepdrilling/lang/zh_cn.json
> +  "block.deepdrilling.blank_module": "空白组件",
```suggestion
  "block.deepdrilling.blank_module": "空白模块",
```
不是，那里按组件翻是因为原文是component，没有模块module
其他的module就是module，按模块翻

2024-12-19 08:31 UTC, JsMkSmStf commented on projects/1.20/assets/modrinth-deepdrilling/deepdrilling/lang/zh_cn.json
> +  "block.deepdrilling.blank_module": "空白组件",
行

2024-12-27 09:24 UTC, merged