Just Enough Effect Descriptions (JEED) 翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #4829
Opened 2024-12-03 08:29 UTC by ChuijkYahus

Nether Extension未找到现在还开放的下载链接，推测是Abnormals系列中一个已经放弃开发的模组，故未翻译

2025-01-09 05:10 UTC, mamaruo requested changes

2025-01-09 05:10 UTC, mamaruo commented on projects/1.21/assets/just-enough-effect-descriptions-jeed/jeed/lang/zh_cn.json
> +  "effect.botania.feather_feet.description": "抵消摔落带来的伤害。此效果不会影响摔落伤害，但会抵消末影珍珠等其他来源的伤害。",
| **审阅级别** |
|:--------------:|
|🔴 **严重** / 阻止合并，刻不容缓|

原文：
- **Negated damaged cause by falling. This effect doesn't prevent fall damage from other causes like Ender Pearls**
```suggestion
  "effect.botania.feather_feet.description": "抵消摔落带来的伤害。无法防止由其他方式（如使用末影珍珠传送）造成的摔落伤害。",
```
理解有误

2025-01-09 05:57 UTC, ChuijkYahus commented on projects/1.21/assets/just-enough-effect-descriptions-jeed/jeed/lang/zh_cn.json
> +  "effect.minecraft.glowing.description": "使实体发光，带有可以穿过非透明方块看到的轮廓线。",
```suggestion
  "effect.minecraft.glowing.description": "以轮廓线辉光标记受影响实体，其他实体可以透过方块看见它们。",
```

2025-01-09 06:15 UTC, ChuijkYahus commented on projects/1.21/assets/just-enough-effect-descriptions-jeed/jeed/lang/zh_cn.json
> +  "effect.species.birtd.description": "令受影响实体眩晕，阻止其移动，但不会进行反击。",
```suggestion
  "effect.species.birtd.description": "令受影响实体眩晕，阻止其移动，但不会阻止其反击。",
```
误读，原文有些奇怪

此效果的enus是“Birt'd”，向实体投掷Birt蛋给予，令实体无法移动、无法击退3秒
还专门有向监守者投掷Birt蛋的进度，确实是会反击的

2025-01-11 15:17 UTC, mamaruo approved these changes

2025-01-13 04:51 UTC, merged