Arcane Essentials 汉化更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #4844
Opened 2024-12-16 20:10 UTC by OoRmikooO

2024-12-23 01:15 UTC, luoxueyasha commented on projects/1.12.2/assets/arcane-essentials/arcane_essentials/lang/zh_cn.lang
> +spell.arcane_essentials:storm_blink.desc=向着你所的敌人突进一段距离,并且将会短暂的点燃你的敌人。
```suggestion
spell.arcane_essentials:storm_blink.desc=向着你所的敌人突进一段距离，并且将会短暂的点燃你的敌人。
```
【要求】标点符号应使用规范的汉语全角标点符号，具体要求请阅读我们的 [翻译规范](https://cfpa.site/TransRules/) 中 **03.标点符号** 这一节。
诸如这类的问题请在您翻译的所有文件中全部查明并修改。


不是……这玩意当年怎么入库的？

2024-12-23 01:15 UTC, luoxueyasha commented on projects/1.12.2/assets/arcane-essentials/arcane_essentials/lang/zh_cn.lang
> +item.arcane_essentials:sword.removeally=%1$s 已被移除从你的对友列表
【疑问】对友？
【要求】应当使用正常的汉语语序。此类问题请全文通查

```suggestion
item.arcane_essentials:sword.removeally=%1$s 已从你的队友列表里被移除
```

2024-12-23 01:15 UTC, luoxueyasha commented on projects/1.12.2/assets/arcane-essentials/arcane_essentials/lang/zh_cn.lang
> +spell.arcane_essentials:fire_pledge.desc=焚毁一切！在你面前召唤出一列间歇的火焰柱。
原文`BBBBBBBBBBBBBBBBBBBBBBUUUUUUUUUUUUUUUURRRRRRNNNNNNNNNNNNNNNN! Summon geysers of fire in front of you, like the pokemon move! Gen 6, anybody?`

漏译一个彩蛋，
【建议】要不干脆就……顺带翻出来？

2024-12-24 04:55 UTC, OoRmikooO commented on projects/1.12.2/assets/arcane-essentials/arcane_essentials/lang/zh_cn.lang
> +spell.arcane_essentials:fire_pledge.desc=焚毁一切！在你面前召唤出一列间歇的火焰柱。
是"Gen 6, anybody?"吗

2024-12-24 04:59 UTC, OoRmikooO commented on projects/1.12.2/assets/arcane-essentials/arcane_essentials/lang/zh_cn.lang
> +spell.arcane_essentials:fire_pledge.desc=焚毁一切！在你面前召唤出一列间歇的火焰柱。
这句如果没找到有原型出处我就直译了

2024-12-24 05:08 UTC, OoRmikooO commented on projects/1.12.2/assets/arcane-essentials/arcane_essentials/lang/zh_cn.lang
> +spell.arcane_essentials:fire_pledge.desc=焚毁一切！在你面前召唤出一列间歇的火焰柱。
草,才看清楚是宝可梦

2024-12-24 06:37 UTC, luoxueyasha commented on projects/1.12.2/assets/arcane-essentials/arcane_essentials/lang/zh_cn.lang
> +spell.arcane_essentials:fire_pledge.desc=焚毁一切！在你面前召唤出一列间歇的火焰柱，就像宝可梦一样。（有人玩第六世代吗?）
```suggestion
spell.arcane_essentials:fire_pledge.desc=焚毁一切！在你面前召唤出一列间歇的火焰柱，就像宝可梦里的一样。（有人玩第六世代吗？）
```
【要求】语义错译，宝可梦有同名招式
【要求】标点符号应使用规范的汉语全角标点符号，具体要求请阅读我们的 [翻译规范](https://cfpa.site/TransRules/) 中 **03.标点符号** 这一节。
诸如这类的问题请在您翻译的所有文件中全部查明并修改。

2024-12-24 06:37 UTC, luoxueyasha commented on projects/1.12.2/assets/arcane-essentials/arcane_essentials/lang/zh_cn.lang
> +spell.arcane_essentials:wave_of_relief.desc=释放一道温和的波动， 移除所有负面药水效果， 并轻微治疗周围的友军！
```suggestion
spell.arcane_essentials:wave_of_relief.desc=释放一道温和的波动，移除所有负面药水效果，并轻微治疗周围的友军！
```
【要求】全角符号后不需要加空格，此类问题请全文通查并修改

2024-12-24 06:37 UTC, luoxueyasha commented on projects/1.12.2/assets/arcane-essentials/arcane_essentials/lang/zh_cn.lang
> +spell.arcane_essentials:whirlpool.desc=在世界之中创造旋涡，摇摆，破碎，激荡.所有被困住的敌人都只能做无用的困兽之斗！
与原文文本语义不对应。
【询问】是否要全文通查，修复所有的错译问题？
【要求】标点符号应使用规范的汉语全角标点符号，具体要求请阅读我们的 [翻译规范](https://cfpa.site/TransRules/) 中 **03.标点符号** 这一节。
诸如这类的问题请在您翻译的所有文件中全部查明并修改。

2024-12-24 17:48 UTC, OoRmikooO commented on projects/1.12.2/assets/arcane-essentials/arcane_essentials/lang/zh_cn.lang
> +spell.arcane_essentials:whirlpool.desc=在世界之中创造旋涡，摇摆，破碎，激荡.所有被困住的敌人都只能做无用的困兽之斗！
按要求修改完之后尽量会根据现有pr内的汉化文件与最新英文原文翻译校对以检查版本落后翻译等情况

2024-12-24 18:06 UTC, OoRmikooO commented on projects/1.12.2/assets/arcane-essentials/arcane_essentials/lang/zh_cn.lang
> +spell.arcane_essentials:wave_of_relief.desc=释放一道温和的波动， 移除所有负面药水效果， 并轻微治疗周围的友军！
上一任翻译每个中文逗号全都有空格无语

2024-12-27 19:33 UTC, OoRmikooO commented
已重译旧汉化内容防止出现过时翻译情况

2024-12-28 03:22 UTC, luoxueyasha commented on projects/1.12.2/assets/arcane-essentials/arcane_essentials/lang/zh_cn.lang
> +spell.arcane_essentials:absolute_zero.desc=释放一道来自极地的寒气，立即冻住 3 个方块范围内的所有敌人！
1

2024-12-28 03:22 UTC, luoxueyasha commented on projects/1.12.2/assets/arcane-essentials/arcane_essentials/lang/zh_cn.lang
> +spell.arcane_essentials:cyclone_bolt.desc=向着你所指的地方发射一个强力的空气弹！
```suggestion
spell.arcane_essentials:cyclone_bolt.desc=向着你所指的地方发射一颗强力的空气弹！
```
在翻译时，应注意中文的量词的使用，不应滥用“一个”。
此类问题请在您的翻译文件中全文通查并修改。

2024-12-28 03:22 UTC, luoxueyasha commented on projects/1.12.2/assets/arcane-essentials/arcane_essentials/lang/zh_cn.lang
> +spell.arcane_essentials:cyclone_shield.desc=在你所站立的地方创造一场风暴气旋，气旋可以偏转弹射物并缓慢的对附近的敌人造成伤害。
漏翻
原文`Create a spinning tornado of air around where you're standing! Deflects projectiles, slowly hits enemies repeatedly, then shoots all nearby enemies away on death.`
【要求】全文通查并修正

2024-12-28 03:24 UTC, luoxueyasha commented
我们认为您的翻译比较生硬或者使用了生成式AI，抑或是您对PR的反复修正仍无法满足修改需求。
此类翻译因为违反了我们的[贡献方针](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md)，我们希望您能够予以修改，否则我们可能会关闭您的PR。

您可以参考[维基百科-翻译腔](https://zh.wikipedia.org/wiki/Wikipedia:%E7%BF%BB%E8%AF%91%E8%85%94)来获取更多的翻译上的帮助。

2025-01-04 01:24 UTC, luoxueyasha reviewed
审不动了，全文自查吧

2025-01-04 01:24 UTC, luoxueyasha commented on projects/1.12.2/assets/arcane-essentials/arcane_essentials/lang/zh_cn.lang
> +spell.arcane_essentials:absolute_zero.desc=释放一道来自极地的寒气，立即冻住 3 个方块范围内的所有敌人！
```suggestion
spell.arcane_essentials:absolute_zero.desc=释放一道来自极地的寒气，立即冻住3个方块半径范围内的所有敌人！
```
【要求】漏译，**请全文通查**
【要求】在1.16或更高版本下，英文字母、阿拉伯数字等非中文文本无需在前后添加空格。
具体可见我们的 [翻译规范](https://cfpa.site/TransRules/) 中 **04.排版** 一节下。
诸如这类的问题请在您翻译的所有文件中全部查明并修改。

2025-01-04 01:24 UTC, luoxueyasha commented on projects/1.12.2/assets/arcane-essentials/arcane_essentials/lang/zh_cn.lang
> +spell.arcane_essentials:frost_fan.desc=向你的敌人发射冰锥阵列！剑类魔具左键释放，杖类魔具右键释放。
**右键**不是一个完整的谓语，不能作为一个动作使用。
例如，`右键单击` 或 `右击` 、`右键长按` 或 `长按右键`都是可以的。但 `右键` 缺少语言成分。
诸如这类的问题请在您翻译的所有文件中全部查明并修改。

2025-01-15 06:38 UTC, luoxueyasha requested changes
请您对您提交的译文进行全文通查，遵循我们的贡献方针，并修复任何有可能的、指出或未指出的错译、漏译、生硬翻译、格式问题、标点符号问题等。

2025-01-15 06:38 UTC, luoxueyasha commented on projects/1.12.2/assets/arcane-essentials/arcane_essentials/lang/zh_cn.lang
> +spell.arcane_essentials:zoom.desc=短暂充能后，你可以从世界中的任何地点传送到出生点！你必须能看到天空才能释放该法术，在水里无法释放该法术。
```suggestion
spell.arcane_essentials:zoom.desc=短暂充能后，你可以从世界中的任何地点传送到出生点！施放该法术时你必须能看到天空，且不能在水里。
```
原文and的并列关系，以及语序修正

2025-01-15 06:38 UTC, luoxueyasha commented on projects/1.12.2/assets/arcane-essentials/arcane_essentials/lang/zh_cn.lang
> +spell.arcane_essentials:whirlpool.desc=在你目视的几个方块内制造一个水漩涡，亦或是你周围！将敌人拉入内部并缓慢伤害他们————非常适合在爆炸时困住生物！
```suggestion
spell.arcane_essentials:whirlpool.desc=在你目视的几个方块内制造一处水漩涡，亦或是你身边！向内拉扯并缓慢伤害敌人——非常适合在爆炸时困住生物！
```
标点符号修正、量词修复、语序调整
【疑问】原文`Create a swirling vortex of water where you're looking within a couple blocks, OR around you! `
这个within a couple blocks，是指水漩涡的漩涡影响范围、还是指施法距离？

2025-01-15 06:38 UTC, luoxueyasha commented on projects/1.12.2/assets/arcane-essentials/arcane_essentials/lang/zh_cn.lang
> +spell.arcane_essentials:unrelenting_force.desc=Fus Ro Dah! 释放一股纯粹推力，将敌人击飞飞飞飞飞————并造成伤害！
```suggestion
spell.arcane_essentials:unrelenting_force.desc=Fus Ro Dah! 释放一股纯粹的力量，将敌人远远击飞飞飞飞飞，并造成伤害！
```
生硬翻译与标点问题

2025-01-15 06:38 UTC, luoxueyasha commented on projects/1.12.2/assets/arcane-essentials/arcane_essentials/lang/zh_cn.lang
> +spell.arcane_essentials:storm_blink.desc=向着你半径 60 个方块内看着的地方突进一段距离，向目标释放一小束闪电。
错译严重
格式问题
全文通查

2025-02-05 02:46 UTC, luoxueyasha commented
@mamaruo 你还审吗，不审我就7+7了

2025-07-29 12:43 UTC, luoxueyasha commented
@OoRmikooO 

- [7+7](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/2658)时限进入第一阶段，从该评论发出的时间开始计时，届时请注意查看审查意见。若在7天内仍未做出任何实质性回应，则7+7时限自动进入下一阶段。

2025-08-06 20:11 UTC, closed without merging