添加古代咒法
CFPAOrg/Minecraft-Mod-Language-Package pull request #826
Opened 2020-10-02 09:02 UTC by TUsama

- [ ] 我已确认文件路径正确，即 `project/assets/模组id/lang/zh_cn.lang`；
- [ ] 我已确认语言文件名大小写正确，所有的语言文件全为小写；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2020-10-02 11:20 UTC, TUsama commented
@ChirenCQR

2020-10-02 11:29 UTC, ChirenCQR approved these changes

2020-10-11 09:20 UTC, Determancer commented on projects/1.12.2/assets/so-many-enchantments/somanyenchantments/lang/zh_cn.lang
> +enchantment.somanyenchantments.advancedpower.desc=力量的进阶版本.
```suggestion
enchantment.somanyenchantments.advancedpower.desc=力量的进阶版本。
```

2020-10-16 05:58 UTC, baka-gourd commented on projects/1.12.2/assets/pewter/pewter/lang/zh_cn.lang
> +[]
？这是啥

2020-10-16 05:59 UTC, baka-gourd commented on projects/1.12.2/assets/so-many-enchantments/somanyenchantments/lang/zh_cn.lang
> +enchantment.somanyenchantments.wateraspect.desc=会对那些遇水受伤的生物造成额外伤害，譬如烈焰人，末影人，岩浆怪。在水中，你的伤害也会增加. The damage stacks provided they meet the requirements
这个英语是不能汉化嘛

2020-10-16 06:00 UTC, baka-gourd commented on projects/1.12.2/assets/so-many-enchantments/somanyenchantments/lang/zh_cn.lang
> +enchantment.MagmaWalker=岩浆行者
统一成熔岩是不是更好

2020-10-16 06:01 UTC, baka-gourd reviewed
在改改？

2020-10-16 06:06 UTC, TUsama commented on projects/1.12.2/assets/so-many-enchantments/somanyenchantments/lang/zh_cn.lang
> +enchantment.MagmaWalker=岩浆行者
这个是magma，不是lava

2020-10-16 06:06 UTC, TUsama commented
稍等

2020-10-16 06:08 UTC, TUsama commented on projects/1.12.2/assets/so-many-enchantments/somanyenchantments/lang/zh_cn.lang
> +enchantment.somanyenchantments.wateraspect.desc=会对那些遇水受伤的生物造成额外伤害，譬如烈焰人，末影人，岩浆怪。在水中，你的伤害也会增加. The damage stacks provided they meet the requirements
批量替换，这个好像是很古早的事情了（虽然也是我提交的）

2020-11-02 01:48 UTC, baka-gourd requested changes

2020-11-02 01:48 UTC, baka-gourd commented on projects/1.12.2/assets/botania/botania/lang/zh_cn.lang
> +botania.armorset.manasteel.desc=魔力工具消耗魔力减免10%%
?多了%

2020-11-02 01:48 UTC, baka-gourd commented on projects/1.12.2/assets/botania/botania/lang/zh_cn.lang
> +botania.armorset.manaweave.desc0=减少35%%魔力损耗
这是什么问题？千分之一？

2020-11-02 02:19 UTC, TUsama commented on projects/1.12.2/assets/botania/botania/lang/zh_cn.lang
> +botania.armorset.manasteel.desc=魔力工具消耗魔力减免10%%
你好，就是要多一个，要不然format error。

2020-11-02 02:19 UTC, TUsama commented on projects/1.12.2/assets/botania/botania/lang/zh_cn.lang
> +botania.armorset.manaweave.desc0=减少35%%魔力损耗
同上。

2020-11-02 02:29 UTC, baka-gourd commented on projects/1.12.2/assets/botania/botania/lang/zh_cn.lang
> +botania.armorset.manaweave.desc0=减少35%%魔力损耗
那这个有点怪

2020-11-02 02:29 UTC, baka-gourd approved these changes

2020-11-02 06:55 UTC, baka-gourd commented
还有两个mod，争取今晚merge(

2020-11-02 06:55 UTC, TUsama commented
你今天不上课？

2020-11-02 09:50 UTC, baka-gourd approved these changes

2020-11-02 09:50 UTC, merged