Update zh_cn.lang
CFPAOrg/Minecraft-Mod-Language-Package pull request #827
Opened 2020-10-03 12:43 UTC by TaoismDeepLake

现有lang和游戏中自带的比多了不少没有东西，还少了不少该有的东西
特此补充，并对原有翻译做一些修订

- [ √] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是: `projects/1.12.2/assets/curseforge 域名/模组资源 id/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是: `projects/1.16.1/assets/curseforge 域名/模组资源 id/lang/zh_cn.json`
- [ √] 我已确认语言文件名大小写正确，所有的语言文件全为小写；
- [ √] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2020-10-03 12:44 UTC, TaoismDeepLake commented
一开始不知道有这么个写作项目，个人对着新版lang汉化了一波。接着发现了这个项目，然后发现已有汉化，并且和我的构成了一定程度的互补关系……

2020-10-03 12:45 UTC, TaoismDeepLake commented
多了不少没有*的*东西。多了的我就没有删，也许是老版本里有

2020-10-04 15:34 UTC, TUsama commented
能不能把新版的en也贴上来？这样好作比对，要不然 review起来有点麻烦。

2020-10-05 00:45 UTC, WuzgXY-GitHub approved these changes

2020-10-05 00:45 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +item.dungeontactics:boots_of_blinding_speed.name=飞毛腿之靴
请问它的实际作用是什么

2020-10-05 00:45 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +tile.dungeontactics:trap_boom.name=轰隆陷阱
似乎有点不大正式

2020-10-05 00:45 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +tile.dungeontactics:mushroom_秘银.name=秘银凳菇
它的键值......

2020-10-05 00:45 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +enchantment.dungeontactics:smite=天打雷劈
请问实际效果

2020-10-05 00:45 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  enchantment.dungeontactics:trinket_gills=鳃
是否应取用字数更多的译名？或与统一性相关

2020-10-05 00:45 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +advancements.dungeoneering.discount_trapper.title=游牧101
中国许多玩家其实并不清楚 101 的含义，或许可以进行一点小小的改动

2020-10-05 00:45 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  advancements.dungeoneering.getalltomes.title=动的大图书馆
看起来有点生硬

2020-10-05 00:45 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  tile.dungeontactics:bush_cherrybomb.name=樱桃炸弹树丛
建议与「焚莓」字数保持统一

2020-10-05 00:45 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  item.dungeontactics:dungeonpedia.name=腐朽发霉的书籍
请问原文

2020-10-05 01:00 UTC, TUsama commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +advancements.dungeoneering.discount_trapper.title=游牧101
之前和chroma的讨论意见是“二三事”

2020-10-05 08:19 UTC, ChromaPIE commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +item.dungeontactics:scroll_dud.name=啊这！意大利面了吧唧
_**啊这！**_
不要整烂活。

2020-10-05 08:24 UTC, ChromaPIE approved these changes
除了那个啊这啊这我觉得属实不行以外 我个人好喜欢这版新的翻译 你可以酌情做一下修改 其他的完全ok

2020-10-05 08:24 UTC, ChromaPIE commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +tile.dungeontactics:trap_boom.name=轰隆陷阱
我更喜欢轰隆陷阱

2020-10-05 08:24 UTC, ChromaPIE commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +tile.dungeontactics:mushroom_秘银.name=秘银凳菇
爽快replace的后果

2020-10-05 08:24 UTC, ChromaPIE commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  tile.dungeontactics:bush_cherrybomb.name=樱桃炸弹树丛
字数统一的必要性何在

2020-10-05 08:26 UTC, ChromaPIE requested changes
> tile.dungeontactics:mushroom_**秘银**.name=秘银凳菇

错误的key一定要改的

2020-10-05 08:33 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  tile.dungeontactics:bush_cherrybomb.name=樱桃炸弹树丛
看着舒服罢了

此外「焚莓」有并不完全是白话的风格，而「樱桃炸弹」与之风格并不相符。

如果另有致敬的话那当我没说，那样风格被统一的可能就是另一个了.jpg

2020-10-08 13:13 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +item.dungeontactics:boots_of_blinding_speed.name=飞毛腿之靴
盲速在中文里比较费解。

2020-10-08 13:13 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +tile.dungeontactics:mushroom_秘银.name=秘银凳菇
我的锅

2020-10-08 13:13 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +enchantment.dungeontactics:smite=天打雷劈
Smite这个东西在手册里表示是会引雷。故此

2020-10-08 13:15 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +tile.dungeontactics:trap_boom.name=轰隆陷阱
是这样的：如果原文是Explosive之类的，我会用爆炸；但这是拟声词boom，我就参考了万智牌Goblin Kaboomist译作轰隆陷阱的方式

2020-10-08 13:16 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +tile.dungeontactics:trap_boom.name=轰隆陷阱
呸，Goblin Kaboomist是轰隆鬼怪，打错了

2020-10-08 13:21 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  item.dungeontactics:dungeonpedia.name=腐朽发霉的书籍
这个是这样的：MC百科里这mod已经起名叫地牢了。此外，原版的dungeon也使用了地牢这个翻译。
英语原文：

itemGroup.dungeontacticsmain=Dungeon Tactics
itemGroup.dungeontacticsweapons=Dungeon Tactics Weapons
itemGroup.dungeontacticsarmour=Dungeon Tactics Armour
itemGroup.dungeontacticsblocks=Dungeon Tactics Blocks

2020-10-08 13:27 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  tile.dungeontactics:bush_cherrybomb.name=樱桃炸弹树丛
这个问题有点难受。樱桃炸弹跟植物大战僵尸显然是有点关系，这个我不好修改。
这个东西不知道两者是共同致敬了同一东西，还是一者致敬另一者，但肯定是有关系。
用一个字表达“樱桃”是在是有点难。

至于incindiberry，游戏里这个莓吃了就着火，显然是跟火有关。“Incindi”疑似为“Incinerate”的变体，后者在万智牌里译作“焚化”。这也是我选字的来源。incindi是半个词，所以我也只用了一个字。如果他写的是IncinerateBerry我就会
翻译成焚烧莓之类的了。

2020-10-08 13:28 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +advancements.dungeoneering.discount_trapper.title=游牧101
可，改

2020-10-08 13:28 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  enchantment.dungeontactics:trinket_gills=鳃
啊这个效率确实是不对，应该是急迫

2020-10-08 13:34 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +item.dungeontactics:boots_of_blinding_speed.name=飞毛腿之靴
我sb了，没有实测这个道具，目前看来还是暂时保留盲速吧

2020-10-08 13:36 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  advancements.dungeoneering.getalltomes.title=动的大图书馆
嘛，这个是因为我觉得“真令人满意”太西式了才改的，我再斟酌

2020-10-08 13:37 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  advancements.dungeoneering.getalltomes.title=动的大图书馆
此外这里原版Hubble Bubble被翻译成了“冒泡泡泡泡泡泡“”其实丢了一部分双关，但这个双关实在太难救回来，我也就没管了

2020-10-08 13:39 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +item.dungeontactics:scroll_dud.name=啊这！意大利面了吧唧
哦呼，这个词我理解的是表示爽快；但“啊哦”表蛋疼，所以我才考虑改了这个。但后面那半句我着实没谱……那个词好像是双关了魔兽一个套装的名字，但我查不到那个套装的翻译，我本人也不玩魔兽，所以……

2020-10-08 14:22 UTC, TaoismDeepLake commented
已提交新的修订。
关于焚莓那个，如果作者用的不是incinerate这种比较复杂的词，而是用的burn、fire、flame之类的，我直接就火莓怼上去了。但不管怎么说，肯定比纯粹音译好，因为体现了关键的“火”。这玩意一吃就着火。

在这里给出几个更白话的参考方案：
保留“焚烧”的意象
- 红烧莓  （但是会让人误以为已经被烤熟了）
- 火烧莓  （会让人联想火烧云、驴肉火烧）

放弃“焚烧”，退而只保留“火”的方案：
- 火球莓、火焰莓  
- 火辣莓   （原文没有“辣味”的意思，但考虑到“火辣”也不一定表示“辣”，也是可以忍的）
- 赤炎莓  （也可做赤焰莓、炽焰莓，虽然还是文绉绉，但是比焚莓好一点 ）


固然，glowcurrent翻译成流光、光流等更书面一些的词汇很容易，但是“樱桃炸弹”想保留《植物大战僵尸》的联想还要书面化，实在是太难了。要想同一三者的书面化程度，我宁可三个都白话，也不想把cherrybomb给书面化丢掉联想。

2020-10-08 14:24 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  enchantment.dungeontactics:trinket_gills=鳃
啊但是急迫提升很蠢，急迫的话又少了两个字，疯了

2020-10-08 16:30 UTC, TUsama commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +enchantment.dungeontactics:smite=天打雷劈
smite不一般都是承接的意思吗。。虽然这里不是对亡灵生物造成额外伤害，但惩戒也包含了某种类似于神/天对凡间的惩罚的意思，对应于此就是打雷。

2020-10-08 16:39 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  enchantment.dungeontactics:trinket_gills=鳃
我想说的其实是鳃

2020-10-08 16:40 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  advancements.dungeoneering.getalltomes.title=动的大图书馆
我其实想说的是动的大图书馆

2020-10-08 16:41 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  tile.dungeontactics:bush_cherrybomb.name=樱桃炸弹树丛
有致敬的话那请便，这个问题不大

2020-10-08 16:41 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  item.dungeontactics:dungeonpedia.name=腐朽发霉的书籍
我说的是腐朽发霉的书籍

2020-10-08 16:43 UTC, WuzgXY-GitHub commented
> 钉锤
锅拍

这两个条目麻烦修一下

2020-10-09 01:39 UTC, TUsama commented
review针对的行数都是显示的那几行的最后一行，可不要搞混了。

2020-10-09 07:32 UTC, TaoismDeepLake reviewed
> review针对的行数都是显示的那几行的最后一行，可不要搞混了。

啊这，抱歉……我这两天再看下

2020-10-09 09:31 UTC, TUsama commented
自己发的对话有上角有三个点，点进去有个edit，觉得说的不妥当可以改的。。。所以完全不用急躁。。。

2020-10-10 08:22 UTC, TUsama requested changes

2020-10-10 08:22 UTC, TUsama commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  item.dungeontactics:peg_hammer.name=钉锤（Lygrimul）
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

建议把原文移除

2020-10-10 08:22 UTC, TUsama commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +tile.dungeontactics:powered_bars.name=电网
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

你确定是“电”？

2020-10-10 08:22 UTC, TUsama commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  enchantment.dungeontactics:trinket_gills=鳃
我感觉水下呼吸更好。

2020-10-10 08:22 UTC, TUsama commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +enchantment.dungeontactics:trinket_resistance=铜头铁臂
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

如果原文是rockskin之类的，那建议就是“石肤”

2020-10-10 08:22 UTC, TUsama commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  enchantment.dungeontactics:poison_fade=平凡
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

上面的fade flower你译成了消逝叶，这里怎么还是“平凡”？

2020-10-10 08:22 UTC, TUsama commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +enchantment.dungeontactics.sonicboom.desc=使便携开路器用魔法输出，不再需要火药。
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

“用魔法输出”显得比较不妥当，可以换词。

2020-10-10 08:22 UTC, TUsama commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +enchantment.dungeontactics.clustered.desc=导致平底炮的子弹命中后产生跳弹。
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

```suggestion
enchantment.dungeontactics.clustered.desc=使得平底炮的子弹命中后产生跳弹。
```

2020-10-10 08:22 UTC, TUsama commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  enchantment.dungeontactics.smelting.desc=开采时冶炼。
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

```suggestion
enchantment.dungeontactics.smelting.desc=开采时对掉落物进行冶炼。
```

2020-10-10 08:22 UTC, TUsama commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  enchantment.dungeontactics.berserking.desc=使用者护甲越少，额外伤害越高。
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

```suggestion
enchantment.dungeontactics.berserking.desc=使用者护甲越少，造成的额外伤害就越高。
```

2020-10-10 08:22 UTC, TUsama commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +enchantment.dungeontactics.restoration.desc=参阅地牢百科卷四：《魔法·炼金》
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

我不清楚原文为何，但是如果原文是祈使句，请把祈使语气翻译出来，下面的十几行同样如此。

2020-10-10 08:22 UTC, TUsama commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +advancements.dungeoneering.eatpotionfish.description=便宜没好货。
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

请出示原文。

2020-10-10 14:23 UTC, ChromaPIE commented
请再次确认“potshot”的释义并做相应更改

2020-10-10 14:55 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  advancements.dungeoneering.getalltomes.title=动的大图书馆
> 我其实想说的是动的大图书馆

不知道英文是什么，我没有找到lang里对应的英文。要删去吗？
一般这种蛋疼翻译，如果我保留了，大概就是我的私人汉化里没有这个key，不然我肯定覆盖掉……

2020-10-10 14:56 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  item.dungeontactics:dungeonpedia.name=腐朽发霉的书籍
> 我说的是腐朽发霉的书籍

新版本没有这个key，目前尚不清楚本来是什么……

2020-10-10 15:08 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +tile.dungeontactics:powered_bars.name=电网
在现实里和其他游戏里，这种一碰就造成伤害的一般是电网。
本mod实测，这个东西不需要红石块功能，所以肯定不是红石能量。
至于要不要通俗地翻译成电网嘛……

2020-10-10 15:10 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +enchantment.dungeontactics:trinket_resistance=铜头铁臂
enchantment.dungeontactics:trinket_resistance=Stone Skin
所以比起钢筋铁骨、铜头铁臂这种的，直接上石肤吗？

2020-10-10 15:31 UTC, TUsama commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +tile.dungeontactics:powered_bars.name=电网
虽然我也没有比电网更好的翻译，但很明显这里不是通俗不通俗的问题，这个仅仅只是这个东西到底是什么东西的问题。

2020-10-10 15:33 UTC, TUsama commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +enchantment.dungeontactics:trinket_resistance=铜头铁臂
石肤，因为原文里面既没有钢也没有铁，石肤作为其它游戏也存在的翻译，没道理这里就变成了意译。

如果直译已经可以足够表达这个词的意思，那么就不要意译了，这是恨不尊重原文的。

2020-10-10 15:38 UTC, TUsama commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +enchantment.dungeontactics:trinket_resistance=铜头铁臂
@ChromaPIE 就是这个，如果你觉得钢筋铁骨可以的话，那就可以不改了，虽然对我来说这个是很没有必要的，短文本还好，长文本这个 习惯有点害人。

2020-10-10 15:45 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  enchantment.dungeontactics:poison_fade=平凡
改为消逝了。这个淬毒的效果是被打的目标会被瞬移，我目前还没太理解fade这个词在这指什么。

2020-10-10 15:48 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +enchantment.dungeontactics.restoration.desc=参阅地牢百科卷四：《魔法·炼金》
enchantment.dungeontactics.restoration.desc=Please refer to the Dungeonpedia Volume 4: "Magic and Alchemy". 
原文如上，的确祈使句，那我改一下

2020-10-10 15:50 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +advancements.dungeoneering.eatpotionfish.description=便宜没好货。
advancements.dungeoneering.getlootbag.title=Phat Loots
advancements.dungeoneering.getlootbag.description=RNGesus got yo back.

……

advancements.dungeoneering.eatpotionfish.title=Any Pot in a Storm
advancements.dungeoneering.eatpotionfish.description=Less effective, but cheaper.

2020-10-10 15:52 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  enchantment.dungeontactics:poison_fade=平凡
之前估计是因为这些在新版的lang里没有（但加入后会有效果），就看漏了……

2020-10-10 15:53 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +tile.dungeontactics:powered_bars.name=电网
Power is energy, especially electricity, that is obtained in large quantities from a fuel source and used to operate lights, heating, and machinery.
这里我再考虑一下。他就是一个网状栅栏，生物一碰就掉血

2020-10-10 15:57 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  enchantment.dungeontactics.berserking.desc=使用者护甲越少，额外伤害越高。
已按建议修改

2020-10-10 15:58 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  enchantment.dungeontactics.smelting.desc=开采时冶炼。
已按建议修改

> Feedback Priority
> ⏳ Sand / Non-blocking but requires future consideration

2020-10-10 15:59 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  enchantment.dungeontactics:trinket_gills=鳃
已改为：水下呼吸

2020-10-10 16:00 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +enchantment.dungeontactics:smite=天打雷劈
已改为：天罚

2020-10-11 01:25 UTC, TUsama commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +advancements.dungeoneering.eatpotionfish.description=便宜没好货。
便宜没好货与Less effective, but cheaper是完全两个意思吧。。。原文是“一分钱一分货”吧。。

2020-10-11 02:24 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  advancements.dungeoneering.getalltomes.title=动的大图书馆
没有的话那看看之前的版本？毕竟虽然这么做很麻烦，但 CFPA 的资源包是服务各种版本的，可能还是得斟酌一下

2020-10-11 02:33 UTC, TUsama commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  advancements.dungeoneering.getalltomes.title=动的大图书馆
在history查不到这个key。

2020-10-11 06:09 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +advancements.dungeoneering.eatpotionfish.description=便宜没好货。
我当时考虑过这个问题。在我看来，英语里这要表达“虽然变垃圾了，但是也变便宜了”，而汉语里常用的“一分钱一分货”一般表示“这个东西很贵，但它很好”，另一个常用词“物美价廉”则意思不对……假如有个“孬货却便宜”，我就用了，可惜我想不到这种常用语。不行就“效果打折了，造价也是？”

2020-10-11 06:10 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  item.dungeontactics:peg_hammer.name=钉锤（Lygrimul）
已改成“钉锤”

2020-10-11 06:14 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
>  advancements.dungeoneering.getalltomes.title=动的大图书馆
> 在history查不到这个key。

那么接下来开始考古吗……
这个翻译是由TartaricAcid两年前提交的，要不要调查那时起所有的jar，顺便问问他本人？

2020-10-11 09:25 UTC, Determancer commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +advancements.dungeoneering.eatpotionfish.description=便宜没好货。
```suggestion
advancements.dungeoneering.eatpotionfish.description=物不美，但价廉。
```

```suggestion
advancements.dungeoneering.eatpotionfish.description=物欠美，但价更廉。
```

“便宜没好货”偏理原意过于严重，信达雅三者首先要满足前两个再说别的，不必强求俗语来达到末项。
与其生硬使用，倒不如直译。

2020-10-11 09:28 UTC, Determancer commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +tile.dungeontactics:powered_bars.name=电网
```suggestion
tile.dungeontactics:powered_bars.name=带电栏杆
```

2020-10-11 09:30 UTC, Determancer commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +enchantment.dungeontactics.sonicboom.desc=使便携开路器用魔法输出，不再需要火药。
```suggestion
enchantment.dungeontactics.sonicboom.desc=使便携开路器用魔法产生爆炸，不再需要火药。
```

2020-10-11 11:12 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +tile.dungeontactics:powered_bars.name=电网
> 最好看看材质，电网的孔是很细密的。
> 如果原材质孔洞密度近似于原版铁栏杆，那么电网就不太妥当。

比原版铁栏杆要密一倍左右，不过我觉得这其实是个问题不大的事。就带电栏杆吧。

2020-10-11 11:14 UTC, TaoismDeepLake commented
> > tile.dungeontactics:mushroom_**秘银**.name=秘银凳菇
> 
> 错误的key一定要改的

改了

2020-10-11 13:47 UTC, TUsama approved these changes

2020-10-13 10:09 UTC, TaoismDeepLake commented
所以那俩陈年老key怎么办？

2020-10-13 10:11 UTC, TUsama commented
我个人建议是删掉也无妨。

2020-10-18 04:05 UTC, TUsama commented
无线电这个讨论过之后应该就可以merge了。

2020-10-20 07:43 UTC, TaoismDeepLake commented on projects/1.12.2/assets/dungeon-tactics/dungeontactics/lang/zh_cn.lang
> +tile.dungeontactics:radio.name=无线电
已如此修改

2020-10-20 07:44 UTC, TaoismDeepLake commented
> 无线电这个讨论过之后应该就可以merge了。

已经这么修改了，merge吧。第一次提交翻译，终于完事了……

2020-10-20 09:28 UTC, TUsama approved these changes
可以merge了

2020-10-22 10:37 UTC, ChromaPIE approved these changes

2020-10-22 10:39 UTC, merged