神秘进阶翻译更新 & QMD模组专有名词修正
CFPAOrg/Minecraft-Mod-Language-Package pull request #831
Opened 2020-10-09 15:29 UTC by Determancer

- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是: `projects/1.12.2/assets/curseforge 域名/模组资源 id/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是: `projects/1.16.1/assets/curseforge 域名/模组资源 id/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件全为小写；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2020-10-10 04:46 UTC, TUsama requested changes
15分钟，有些句子肉眼可见的翻译腔，论初代译者的重要性

2020-10-10 04:46 UTC, TUsama commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.card.rift_jar.text=凝视着身旁缸中安然漂浮的裂隙，你意识到了一点，那即是结合神秘术多个方面的知识，便可以将曾经不可逾越的障碍转化为全新的机遇。在3个随机的可用分支获得随机点数的进度，在理论研究完成时额外的2个分支会获得全额奖励。
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

第一句莫名不流畅

2020-10-10 04:46 UTC, TUsama commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.card.rift_monitor.text=裂隙检测仪醒目的全息图使你能够远距离研究邪术学，并且思想变得前所未有的清晰。获得20-40点邪术学进度，与此同时不会获得扭曲值。
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

```suggestion
thaumicaugmentation.research.card.rift_monitor.text=裂隙检测仪醒目的全息图能够帮助你远距离研究邪术学，并且你感到你的思想变得前所未有的清晰。获得20-40点邪术学进度，与此同时不会获得扭曲值。
```

2020-10-10 04:46 UTC, TUsama commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.gauntlet_void.2=看来我先前的猜想已经被证明是正确的。将魔力谐振器替换为虚空预言者的珍珠后，我能感觉到护手与周围灵气场的联系变得更加紧密。事实上，这联系无比紧密，使得如今的护手比起我的法师护手原型有了30%的Vis减免，还能吸收更大范围内的Vis。希望这意味着我能够在使用复杂的法术时，不像以前那样过于快速地耗尽周边的灵气。<
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
thaumicaugmentation.research.gauntlet_void.2=看来我先前的猜想已经被证明是正确的。将魔力谐振器替换为虚空预言者的珍珠后，我能感觉到护手与周围灵气场的联系变得更加紧密。事实上，这联系无比紧密，使得如今的护手比起我的法师护手原型多了30%的Vis减免，还能吸收更大范围内的Vis。希望这意味着我能够在使用复杂的法术时，不像以前那样过于快速地耗尽周边的灵气。<BR>看起来虽然这个护手在冷却时间方面胜过了原来的法具，但神秘护手却仍要更胜一筹。我不得不在更少的Vis消耗和更短的冷却时间之间做出选择，判断哪一个对我而言更有价值。幸运的是，虚空预言者法师护手仍然保持着其前身的染色能力。染料的使用和移除方法与神秘护手相同。
```

2020-10-10 04:57 UTC, Determancer commented
> 15分钟，有些句子肉眼可见的翻译腔，论初代译者的重要性

“初代译者”表示老翻译腔了。

2020-10-10 05:01 UTC, Determancer commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.gauntlet_void.2=看来我先前的猜想已经被证明是正确的。将魔力谐振器替换为虚空预言者的珍珠后，我能感觉到护手与周围灵气场的联系变得更加紧密。事实上，这联系无比紧密，使得如今的护手比起我的法师护手原型有了30%的Vis减免，还能吸收更大范围内的Vis。希望这意味着我能够在使用复杂的法术时，不像以前那样过于快速地耗尽周边的灵气。<
我觉得“多了”暗含某种原先就已经减免的意思，但原本的法师护手是没有减免效果的。
“有了”在这里是适用的，例子：费用有了一定的减免。

2020-10-10 05:02 UTC, Determancer commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.card.rift_jar.text=凝视着身旁缸中安然漂浮的裂隙，你意识到了一点，那即是结合神秘术多个方面的知识，便可以将曾经不可逾越的障碍转化为全新的机遇。在3个随机的可用分支获得随机点数的进度，在理论研究完成时额外的2个分支会获得全额奖励。
```suggestion
thaumicaugmentation.research.card.rift_jar.text=凝视着在身旁的罐子中安然漂浮的裂隙，你意识到了一点，那即是结合神秘术多个方面的知识，便可以将曾经不可逾越的障碍转化为全新的机遇。在3个随机的可用分支获得随机点数的进度，在理论研究完成时额外的2个分支会获得全额奖励。
```

2020-10-10 05:04 UTC, Determancer commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.card.rift_monitor.text=裂隙检测仪醒目的全息图使你能够远距离研究邪术学，并且思想变得前所未有的清晰。获得20-40点邪术学进度，与此同时不会获得扭曲值。
```suggestion
thaumicaugmentation.research.card.rift_monitor.text=裂隙监测仪醒目的全息图使你能够远距离研究邪术学，并让你的思想变得前所未有的清晰。获得20-40点邪术学进度，与此同时不会获得扭曲值。
```

2020-10-10 06:08 UTC, TUsama commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.card.rift_jar.text=凝视着身旁缸中安然漂浮的裂隙，你意识到了一点，那即是结合神秘术多个方面的知识，便可以将曾经不可逾越的障碍转化为全新的机遇。在3个随机的可用分支获得随机点数的进度，在理论研究完成时额外的2个分支会获得全额奖励。
> 你意识到了一点，那即是结合神秘术多个方面的知识，便可以将曾经不可逾越的障碍转化为全新的机遇。

说实话，我没看懂

2020-10-10 06:11 UTC, TUsama commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.gauntlet_void.2=看来我先前的猜想已经被证明是正确的。将魔力谐振器替换为虚空预言者的珍珠后，我能感觉到护手与周围灵气场的联系变得更加紧密。事实上，这联系无比紧密，使得如今的护手比起我的法师护手原型有了30%的Vis减免，还能吸收更大范围内的Vis。希望这意味着我能够在使用复杂的法术时，不像以前那样过于快速地耗尽周边的灵气。<
我还以为原先就有，绝了。

2020-10-10 06:11 UTC, Determancer commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.card.rift_jar.text=凝视着身旁缸中安然漂浮的裂隙，你意识到了一点，那即是结合神秘术多个方面的知识，便可以将曾经不可逾越的障碍转化为全新的机遇。在3个随机的可用分支获得随机点数的进度，在理论研究完成时额外的2个分支会获得全额奖励。
不太清楚哪里没懂……

> 你是意识到……结合……多方面知识……可以将……障碍转化为……机遇。

这样提取词语能理解吗？

2020-10-10 06:14 UTC, TUsama commented
反正我个人会极力避免“使得”“以”这种词，这种我感觉真的好怪，一般我都是直接拆句，把这些变成状语或者其它的，读起来会比较通顺一点。

譬如：

> 事实上，这联系无比紧密，使得如今的护手比起我的法师护手原型有了30%的Vis减免，

我就会翻译成：

> 事实上，由于这无比紧密的联系，如今的护手比起我的法师护手有了30%的Vis减免。

2020-10-10 06:17 UTC, Determancer commented
> 反正我个人会极力避免“使得”“以”这种词，这种我感觉真的好怪，一般我都是直接拆句，把这些变成状语或者其它的，读起来会比较通顺一点。
> 
> 譬如：
> 
> > 事实上，这联系无比紧密，使得如今的护手比起我的法师护手原型有了30%的Vis减免，
> 
> 我就会翻译成：
> 
> > 事实上，由于这无比紧密的联系，如今的护手比起我的法师护手有了30%的Vis减免。

确实，略显翻译腔。但类似的用法在该PR中范围较广且变种较多，改动性价比有限。我以后会注意一下。

2020-10-10 06:24 UTC, TUsama commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.gauntlet_void.2=看来我先前的猜想已经被证明是正确的。将魔力谐振器替换为虚空预言者的珍珠后，我能感觉到护手与周围灵气场的联系变得更加紧密。事实上，这联系无比紧密，使得如今的护手比起我的法师护手原型有了30%的Vis减免，还能吸收更大范围内的Vis。希望这意味着我能够在使用复杂的法术时，不像以前那样过于快速地耗尽周边的灵气。<
但你这还是有点怪啊，你这个句子扩一扩，就变成了：

> 相较于xxx，如今的费用有了一定的减免。

它前面最好是加一个比较的状语，你这个句子里面，“使得”让整个句子全部捏成了一块，成为一整个结果声明，句内虽然已经包括了比较，但是总觉得不够明显。

```suggestion
thaumicaugmentation.research.gauntlet_void.2=看来我先前的猜想已经被证明是正确的。将魔力谐振器替换为虚空预言者的珍珠后，我能感觉到护手与周围灵气场的联系变得更加紧密。事实上，由于这无比紧密的联系，相较于原先的法师护手原型，如今的护手有了30%的Vis减免，还能吸收更大范围内的Vis。希望这意味着我能够在使用复杂的法术时，不像以前那样过于快速地耗尽周边的灵气。<BR>看起来虽然这个护手在冷却时间方面胜过了原来的法具，但神秘护手却仍要更胜一筹。我不得不在更少的Vis消耗和更短的冷却时间之间做出选择，判断哪一个对我而言更有价值。幸运的是，虚空预言者法师护手仍然保持着其前身的染色能力。染料的使用和移除方法与神秘护手相同。
```

2020-10-10 06:25 UTC, TUsama commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.card.rift_jar.text=凝视着身旁缸中安然漂浮的裂隙，你意识到了一点，那即是结合神秘术多个方面的知识，便可以将曾经不可逾越的障碍转化为全新的机遇。在3个随机的可用分支获得随机点数的进度，在理论研究完成时额外的2个分支会获得全额奖励。
这样就没问题了，应该是“那”干扰的有点大。

```suggestion
thaumicaugmentation.research.card.rift_jar.text=凝视着身旁缸中安然漂浮的裂隙，你意识到了一点，若能结合神秘术多个方面的知识，便可以将曾经不可逾越的障碍转化为全新的机遇。在3个随机的可用分支获得随机点数的进度，在理论研究完成时额外的2个分支会获得全额奖励。
```

2020-10-10 07:36 UTC, Determancer commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.gauntlet_void.2=看来我先前的猜想已经被证明是正确的。将魔力谐振器替换为虚空预言者的珍珠后，我能感觉到护手与周围灵气场的联系变得更加紧密。事实上，这联系无比紧密，使得如今的护手比起我的法师护手原型有了30%的Vis减免，还能吸收更大范围内的Vis。希望这意味着我能够在使用复杂的法术时，不像以前那样过于快速地耗尽周边的灵气。<
> So connected, in fact, that not only have I measured a 30% vis discount over my original prototype,...
原文这里在强调联系的紧密性（So connected, in fact），句子改写后虽然感觉上更流畅了，但这种微妙的强调却消失了（指“事实上”一语在修改后已经变得可有可无）。

2020-10-10 15:40 UTC, Determancer commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.gauntlet_void.2=看来我先前的猜想已经被证明是正确的。将魔力谐振器替换为虚空预言者的珍珠后，我能感觉到护手与周围灵气场的联系变得更加紧密。事实上，这联系无比紧密，使得如今的护手比起我的法师护手原型有了30%的Vis减免，还能吸收更大范围内的Vis。希望这意味着我能够在使用复杂的法术时，不像以前那样过于快速地耗尽周边的灵气。<
```suggestion
thaumicaugmentation.research.gauntlet_void.2=看来我先前的猜想已经被证明是正确的。将魔力谐振器替换为虚空预言者的珍珠后，我能感觉到护手与周围灵气场的联系变得更加紧密。事实上，其联系之紧密远胜以往，以至于相比原先的法师护手原型，如今的护手有了30%的Vis减免，还能吸收更大范围内的Vis。希望这意味着我能够在使用复杂的法术时，不像以前那样过于快速地耗尽周边的灵气。<BR>看起来虽然这个护手在冷却时间方面胜过了原来的法具，但神秘护手却仍要更胜一筹。我不得不在更少的Vis消耗和更短的冷却时间之间做出选择，判断哪一个对我而言更有价值。幸运的是，虚空预言者法师护手仍然保持着其前身的染色能力。染料的使用和移除方法与神秘护手相同。
```

2020-10-10 15:41 UTC, TUsama commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.gauntlet_void.2=看来我先前的猜想已经被证明是正确的。将魔力谐振器替换为虚空预言者的珍珠后，我能感觉到护手与周围灵气场的联系变得更加紧密。事实上，这联系无比紧密，使得如今的护手比起我的法师护手原型有了30%的Vis减免，还能吸收更大范围内的Vis。希望这意味着我能够在使用复杂的法术时，不像以前那样过于快速地耗尽周边的灵气。<
勉强可以，结果最后还是用了以至于。

2020-10-10 15:56 UTC, Determancer commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.card.rift_jar.text=凝视着身旁缸中安然漂浮的裂隙，你意识到了一点，那即是结合神秘术多个方面的知识，便可以将曾经不可逾越的障碍转化为全新的机遇。在3个随机的可用分支获得随机点数的进度，在理论研究完成时额外的2个分支会获得全额奖励。
```suggestion
thaumicaugmentation.research.card.rift_jar.text=凝视着身旁缸中安然漂浮的裂隙，你意识到，综合神秘术多个方面的知识，即可将曾经不可逾越的障碍转化为全新的机遇。在3个随机的可用分支获得随机点数的进度，在理论研究完成时额外的2个分支会获得全额奖励。
```

2020-10-11 06:28 UTC, dovisutu reviewed
qmd那个看了一下，确实该这样改
~之前审查加qmd翻译的时候为什么我没看到...~
神秘进阶这边我大概看了一下，结果看到一半不小心给回退了（

2020-10-11 06:28 UTC, dovisutu commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.morphic_tool.1=我发明了一种能有效地将两件物品组合到同一空间的方法。借助一颗元始珍珠和少量的Vacuos源质，我可以让两件物品存在于同一空间，但其中只有一个物品对外界观察者而言是可见的。另一件物品则为这个幻形工具提供属性，例如攻击力和耐久度。在这种状态下，用于装饰的物品会保持某种虚无缥缈的状态，这意味着它不会损坏，同时无法通
这些源质是有标准译名的来着...
```suggestion
thaumicaugmentation.research.morphic_tool.1=我发明了一种能有效地将两件物品组合到同一空间的方法。借助一颗元始珍珠和少量的虚空源质，我可以让两件物品存在于同一空间，但其中只有一个物品对外界观察者而言是可见的。另一件物品则为这个幻形工具提供属性，例如攻击力和耐久度。在这种状态下，用于装饰的物品会保持某种虚无缥缈的状态，这意味着它不会损坏，同时无法通过任何方式与这个世界相互作用。<BR>要制造这种工具，我需要使用奥术注魔，把我想保持原有性质的物品放在中央，把装饰用途的物品放在外围的基座上（当然还需要其它必备物品）。如果我想分离这两件物品，我只需要把工具放到奥术工作台中分解——似乎分开它们所需的能量比起将它们合在一起所需的能量要少得多。<BR>如我之前所提到的，功能性的物品在通过玄异方式与装饰性物品绑定后依然有损坏的风险。而它处于混合状态时，无法通过传统的方法进行修复。不过，像虚空金属这样的材料仍然可以保持它们的再生性质。我也确信更加复杂的物品在幻形工具中将会无法正常工作——虽然基本的工具即使附上了常规和注魔所得的魔咒，看起来依然表现正常，但像盔甲之类的物品却无法正常发挥作用。<BR>最后，幻形工具似乎提供了轻微的绝缘效果，可以抵挡功能性物品所造成的扭曲。或许我将来应该重新审视这一现象，以确定我是否可以使其更加有效。
```

2020-10-11 06:28 UTC, dovisutu commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.rift_studies.1=通过将大量的Vitium源质集中到一个虚空种子之中，其产生的咒波不久就会被吸收到灵气场之内，几乎肯定能产生一个裂隙。我应该非常小心地对待这些咒波种子——“种植”它们会瞬间释放其中所储存的咒波，同时消耗掉种子。<BR>看起来将种子中的源质种类严格限制为只有Vitium时，每单位的源质能产生更多的咒波，比起将它们
同上
```suggestion
thaumicaugmentation.research.rift_studies.1=通过将大量的腐化源质集中到一个虚空种子之中，其产生的咒波不久就会被吸收到灵气场之内，几乎肯定能产生一个裂隙。我应该非常小心地对待这些咒波种子——“种植”它们会瞬间释放其中所储存的咒波，同时消耗掉种子。<BR>看起来将种子中的源质种类严格限制为只有腐化源质时，每单位的源质能产生更多的咒波，比起将它们随意地倾泻到灵气场中要高效得多。如果我想利用这种现象来制造更大的裂隙，那么我应该将更多的腐化源质注入更小的咒波种子中。然而，随着腐化源质量的增加，注魔风险也会上升，并且我似乎仅能对给定的咒波种子进行一次安全的注魔。
```
不过这样一改感觉又有点奇怪了......看着办吧

2020-10-11 06:28 UTC, dovisutu commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.text.bound_to_type=绑定方块： %s
~不小心一划导致之前这里做的review丢掉了...~
> 对于英文标点符号前或后的空格，请在修改标点符号为中文时删除
> （翻译守则）
毕竟全角冒号已经有一个间隔了，再加一个间隔未免太远了
如果魔导手册的排版问题导致这么写的那当我没说
```suggestion
thaumicaugmentation.text.bound_to_type=绑定方块：%s
```

2020-10-11 06:28 UTC, dovisutu commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.text.entered_void=你已造访广阔无垠的虚域.
请用全角符号。
```suggestion
thaumicaugmentation.text.entered_void=你已造访广阔无垠的虚域。
```

2020-10-11 06:28 UTC, dovisutu commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.text.research_notes_eldritch=这段文字晦涩难懂,但字里行间暗藏玄机......
请用全角符号。
```suggestion
thaumicaugmentation.text.research_notes_eldritch=这段文字晦涩难懂，但字里行间暗藏玄机......
```

2020-10-11 06:51 UTC, Determancer commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.text.bound_to_type=绑定方块： %s
是排版需要，如果没有空格的话看着很挤

2020-10-11 06:53 UTC, Determancer commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.morphic_tool.1=我发明了一种能有效地将两件物品组合到同一空间的方法。借助一颗元始珍珠和少量的Vacuos源质，我可以让两件物品存在于同一空间，但其中只有一个物品对外界观察者而言是可见的。另一件物品则为这个幻形工具提供属性，例如攻击力和耐久度。在这种状态下，用于装饰的物品会保持某种虚无缥缈的状态，这意味着它不会损坏，同时无法通
实际使用时源质译名不会显示，游戏内实装的是拉丁文名（可能是A哥整成了硬编码）。所以一概按照原文处理了。

2020-10-11 06:55 UTC, Determancer commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.rift_studies.1=通过将大量的Vitium源质集中到一个虚空种子之中，其产生的咒波不久就会被吸收到灵气场之内，几乎肯定能产生一个裂隙。我应该非常小心地对待这些咒波种子——“种植”它们会瞬间释放其中所储存的咒波，同时消耗掉种子。<BR>看起来将种子中的源质种类严格限制为只有Vitium时，每单位的源质能产生更多的咒波，比起将它们
> 实际使用时源质译名不会显示，游戏内实装的是拉丁文名（可能是A哥整成了硬编码）。所以一概按照原文处理了。

2020-10-11 06:55 UTC, Determancer commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.text.bound_to_type=绑定方块： %s
全角冒号游戏内实际显示是没有间隔的 = =
所以出于排版需要加了空格。

2020-10-11 06:56 UTC, Determancer commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.text.entered_void=你已造访广阔无垠的虚域.
初稿译者的遗留物，感谢指出。

2020-10-11 07:11 UTC, dovisutu commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.text.bound_to_type=绑定方块： %s
ok

2020-10-11 07:12 UTC, dovisutu commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.text.bound_to_type=绑定方块： %s
此外，这行review竟然还是重复的
（看来以为被回退掉的review竟然没被回退掉......

2020-10-11 09:00 UTC, TUsama requested changes

2020-10-11 09:00 UTC, TUsama commented
空行你删一下，这个应该是我的脚本的问题。

2020-10-11 09:01 UTC, Determancer commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.harness_base.1=我设计了一件简单且相对舒适的背带，其上带有许多搭扣、绑带和连接器，专门用于连接不同的奥术装置和部件。但以其现有形式，穿戴它毫无意义，因为它只是空白的底板，用于附着各种飞行设备。<BR>随着进一步的研究，我只能想象有多少种可能的飞行方式。但我应该格外小心，以免我自己在某个谷底变成神秘使形状的浅坑。
我读着觉得正常

2020-10-11 09:03 UTC, Determancer commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.focus_water.2=因为水在下界等烈火炙烤的环境中几乎会瞬间蒸发，所以我预计在这些区域水之核心效能会大幅降低。它仍将有能力扑灭火焰，但我怀疑它能否影响此类世界中的其他食物，例如熔岩。
```suggestion
thaumicaugmentation.research.focus_water.2=因为水在下界等烈火炙烤的环境中几乎会瞬间蒸发，所以我预计在这些区域水之核心效能会大幅降低。它仍将有能力扑灭火焰，但我怀疑它能否影响此类世界中的其他事物，例如熔岩。
```

2020-10-11 09:03 UTC, Determancer commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.fortified_glass.1=虽然由于已知信息非常有限，所以完整的守护玻璃在目前而言仍是一个梦想，但我已经基本接近这一目标了。这种被我称之为奥术强化玻璃的材料基本上使用了生产源质罐子时相同的工艺，但规格被扩大到了一格完整的方块。<BR>这种玻璃并非坚不可摧，但它能抵御寻常的伤害。例如爆炸就对它造成损坏。此外我还发现它相当美观，所以我
```suggestion
thaumicaugmentation.research.fortified_glass.1=虽然由于已知信息非常有限，所以完整的守护玻璃在目前而言仍是一个梦想，但我已经基本接近这一目标了。这种被我称之为奥术强化玻璃的材料基本上使用了生产源质罐子时相同的工艺，但规格被扩大到了一格完整的方块。<BR>这种玻璃并非坚不可摧，但它能抵御寻常的伤害。例如，爆炸就无法对它造成损坏。此外我还发现它相当美观，所以我应该能为它找到装饰用途。<BR>我既然已设法制造了完整的立方玻璃，制造其相应的玻璃板就更简单了。除了尺寸上有所减小，奥术强化玻璃板仍然保留原型的所有物理属性。
```
输入法当初抽了什么风🤔

2020-10-11 09:11 UTC, Determancer commented
> 空行你删一下，这个应该是我的脚本的问题。

你那个神秘插件提交的修改建议好像无法显示具体修改了哪一处，还得自己手动对比。

2020-10-11 09:24 UTC, TUsama commented
主要是那两行空行成功让GitHub的垃圾diff辨认不出来了。

2020-10-11 10:06 UTC, TUsama commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.eldritch_spire.0=虚域所藏远超我的预期。一个人很容易会猜想，如此接近虚空的世界应当除荒芜废土之外别无他物，但在腐化侵袭地区的边缘，不可名状的存在令我为之战栗。某种存在刺穿了这一地带，就像是次元边界的表面之中刺入的尖锐碎片。我惊异万分，因为此处的现实已经由于此处蕴存的不尽其数的裂缝而变得扭曲易塑，而一时失足将会导致我躲入万劫
```suggestion
thaumicaugmentation.research.eldritch_spire.0=虚域所藏远超我的预期。人们往往会以为，这一世界如此接近虚空，应当除荒芜废土之外别无他物，但在这腐化侵袭地区的边缘，仍有着令我为之战栗的、不可名状的存在。某种存在刺穿了这一地带，就像是次元边界的表面之中刺入的尖锐碎片。我惊异万分，由于此处蕴存着不尽其数的裂缝，此处的现实已经变得扭曲易塑，一时失足便会使我堕入万劫不复的深渊。在这变幻不定的现实中，我几乎可以确信，某种充满恶意的存在将会出现，或是抵达此处——如果其最初并非在此诞生的话。<BR>在一段时间的研究后，我逐渐意识到，邪术远不止是神秘学的一个分支，也不只是一种扭曲人们智识的知识。特别是血腥仪式，是对“邪术”这一词无比精妙的实践阐释，揭示了邪术在何种程度上远远超越了它本身的意涵，也暗示着“这一切存在”的事实仅为超越凡俗之世的存在者所知晓。对这些存在而言，只是提到这一词汇便近乎亵渎，哪怕是寻常的生灵都不被允许做出这番举动，何况是像我一样的神秘使。<BR>没错，邪术绝不仅仅是围绕虚空展开的魔法分支。我相信它指的是一个亘古长存的种族，它们对世界的影响塑造了我如今看做现实并熟视无睹的森罗万象。如果它们确实存在，那么我发现的诸多古怪现象将会获得解答，尤其是魔法原理中的古怪之处、为什么世界中会出现某种生物，以及一些人是如何彻底失去理智并堕入疯狂，献身于毫无益处的恐怖仪式之中。<BR>如果我想真正理解这一切，我必须更为深入地探索虚域，探寻是什么造成了灵气场的混乱。这种邪术影响极有可能对我这样相对渺小的存在抱有敌意，但知识总伴随着危险，我已无法回头。我将一往无前，直到取得这些知识所能赐给我的强大力量。

```

2020-10-11 10:07 UTC, TUsama commented
好像本地的那个插件有bug了，怪事。

2020-10-11 10:17 UTC, TUsama requested changes

2020-10-11 10:17 UTC, TUsama commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.eldritch_spire.2=这个房间......这个祭坛......我曾见过它！血腥仪式中的寥寥数页绘有图画，描绘着某种奇异之物，那些图像都是围绕这个祭坛刻画的！我已明了，此处便是旋塔的核心，它维持着遗迹的守护奥术，与此同时腐蚀着周边的灵气场。然而，这个祭坛坚不可摧，所以我必须寻找其他办法来消解这些影响。<BR>......我知道我
```suggestion
thaumicaugmentation.research.eldritch_spire.2=这个房间......这个祭坛......我曾见过它！血腥仪式中的寥寥数页绘有图画，描绘着某种奇异之物，那些图像都是围绕这个祭坛刻画的！我已明了，此处便是旋塔的核心，它维持着遗迹的守护奥术，与此同时腐蚀着周边的灵气场。然而，这个祭坛坚不可摧，所以我必须寻找其他办法来消解这些影响。<BR>......我知道我要做什么了。名为“Apertis Oculis”的开眼仪式。我必须开启祭坛的眼睛。我对这一仪式一无所知，甚至不知道进行仪式后会发生什么，但我很能看出来祭坛已经准备完毕，所以我只需对中心的基座使用法师护手，完成仪式的最后一步。<BR>我应当准备好迎接可能会发生的一切，无论会有什么，都绝非善类。某种强大的存在于此注视着我。我能感受到它。
```

2020-10-11 10:17 UTC, TUsama commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.eldritch_spire.3=当我在祭坛进行了“Apertis Oculis”仪式之后，我不太清楚会发生什么。也许我当时简单地认为这会终止旋塔对周边区域的影响。说真的，我本该更加深思熟虑一点。我早该意识到事情没有这么简单。<BR>开眼仪式后在传送门处现身的强大生物，正是遗迹腐蚀效应的根源，祭坛只不过是其在维度位面上的一个锚点。不过，在
```suggestion
thaumicaugmentation.research.eldritch_spire.3=当我在祭坛进行了“Apertis Oculis”仪式之后，我不太清楚会发生什么。也许我当时简单地认为这会终止旋塔对周边区域的影响。说真的，我本该考虑的更周全一些。我早该意识到事情没有这么简单。<BR>开眼仪式启动后，在传送门处出现了强大的生物，它正是遗迹腐蚀效应的根源，祭坛只不过是其在维度位面上的一个锚点。不过，在通过仪式迫使其进入虚域之后，我得以将其击杀，现在我能感受到次元边界已经变得更加稳定了，这意味着阻止我破坏建筑的守护奥术也已经消散。如果我乐意，我可以更加自由地探索遗迹，挖掘组成它们的各种方块；我也能找到一些额外的饰品，并收集各种新的建筑材料为我所用。<BR>除此之外，我发现了旋塔之主所遗留的有趣物品：一套破旧的卷轴。我不知道这些卷轴为何会从这种存在身上掉落，也不知道如此古老的卷轴如何经行洪荒岁月遗留至今，但在扫描这些卷轴后，我发现它们包含有对我来说用处非凡的知识，大多与神秘学和元动学有关。它们将是我推进研究的关键；我会在接下来的条目中记述这些破旧卷轴。<BR>尽管我在阻止这些遗迹所代表的充满恶意的力量时取得了成功，我能感受到虚域的灵气场依然是扭曲的。我确信在那里还能找到更多的邪术旋塔，每一个都贮存着仪式祭坛，将其他恶意充盈的存在锚定于彼处。如果我愿意，我可以继续之前的所作所为，一个接一个的击败它们。虽然这会令人心生疲倦，但我相当肯定这样能拿到更多有用的饰品和资源。为了方便以后查阅：第一扇门可通过法师护手释放元动能量打开，其他各种门则需要用在旋塔中各部分找到的钥匙打开，在核心房间中的仪式祭坛可以通过使用法师护手来强制召唤旋塔之主。<BR>经历这一切之后，我仍有一些问题没有解决。旋塔的真正目的是什么？为何它们储存着这些有用的饰品和资源？我还能找到更多远古卷轴的更进一步的副本吗？这些存在究竟是何物，它们何以如此强大？我相信我找到这些笔记绝非偶然，但我不能就此停止。
```

2020-10-11 12:23 UTC, Determancer commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.eldritch_spire.3=当我在祭坛进行了“Apertis Oculis”仪式之后，我不太清楚会发生什么。也许我当时简单地认为这会终止旋塔对周边区域的影响。说真的，我本该更加深思熟虑一点。我早该意识到事情没有这么简单。<BR>开眼仪式后在传送门处现身的强大生物，正是遗迹腐蚀效应的根源，祭坛只不过是其在维度位面上的一个锚点。不过，在
```suggestion
thaumicaugmentation.research.eldritch_spire.3=当我在祭坛进行了“Apertis Oculis”仪式之后，我不太清楚会发生什么。也许我当时简单地认为这会终止旋塔对周边区域的影响。说真的，我本该考虑的更周全一些。我早该意识到事情没有这么简单。<BR>开眼仪式后在传送门处现身的强大生物，正是遗迹腐蚀效应的根源，祭坛只不过是其在维度位面上的一个锚点。不过，在通过仪式迫使其进入虚域之后，我得以将其击杀，现在我能感受到次元边界已经变得更加稳定了，这意味着阻止我破坏建筑的守护奥术也已经消散。如果我乐意，我可以更加自由地探索遗迹，挖掘组成它们的各种方块；我也能找到一些额外的饰品，并收集各种新的建筑材料为我所用。<BR>除此之外，我发现了旋塔之主所遗留的有趣物品：一套破旧的卷轴。我不知道这些卷轴为何会从这种存在身上掉落，也不知道如此古老的卷轴如何经行洪荒岁月遗留至今，但在扫描这些卷轴后，我发现它们包含有对我来说用处非凡的知识，大多与神秘学和元动学有关。它们将是我推进研究的关键；我会在接下来的条目中记述这些破旧卷轴。<BR>尽管我在阻止这些遗迹所具有的充满恶意的力量时取得了成功，我能感受到虚域的灵气场依然是扭曲的。我确信在那里还能找到更多的邪术旋塔，每一个都贮存着仪式祭坛，将其他恶意充盈的存在锚定于彼处。如果我愿意，我可以继续之前的所作所为，一个接一个的击败它们。虽然这会令人疲倦，但我相当肯定这样能拿到更多有用的饰品和资源。为了方便以后查阅：第一扇门可通过法师护手释放元动能量打开，其他各种门则需要用在旋塔中各部分找到的钥匙打开，在核心房间中的仪式祭坛可以通过使用法师护手来强制召唤旋塔之主。<BR>经历这一切之后，我仍有一些问题没有解决。旋塔的真正目的是什么？为何它们储存着这些有用的饰品和资源？我还能找到更多远古卷轴的更进一步的副本吗？这些存在究竟是何物，它们何以如此强大？我相信我找到这些笔记绝非偶然，但我不能就此停止。
```

2020-10-11 12:26 UTC, Determancer commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.eldritch_spire.2=这个房间......这个祭坛......我曾见过它！血腥仪式中的寥寥数页绘有图画，描绘着某种奇异之物，那些图像都是围绕这个祭坛刻画的！我已明了，此处便是旋塔的核心，它维持着遗迹的守护奥术，与此同时腐蚀着周边的灵气场。然而，这个祭坛坚不可摧，所以我必须寻找其他办法来消解这些影响。<BR>......我知道我
```suggestion
thaumicaugmentation.research.eldritch_spire.2=这个房间......这个祭坛......我曾见过它！血腥仪式中的寥寥数页绘有图画，描绘着某种奇异之物，那些图像都是围绕这个祭坛刻画的！我已明了，此处便是旋塔的核心，它维持着遗迹的守护奥术，与此同时腐蚀着周边的灵气场。然而，这个祭坛坚不可摧，所以我必须寻找其他办法来消解这些影响。<BR>......我知道我要做什么了。名为“Apertis Oculis”的开眼仪式。我必须开启祭坛的眼睛。我对这个仪式一无所知，甚至不知道进行仪式后会发生什么，但我很能看出来祭坛已经准备完毕，所以我只需对中心的基座使用法师护手，完成仪式的最后一步。<BR>我应当准备好迎接可能会发生的一切，无论会有什么，都绝非善类。某种强大的存在于此注视着我。我能感受到它。
```

2020-10-11 12:44 UTC, Determancer commented on projects/1.12.2/assets/thaumic-augmentation/thaumicaugmentation/lang/zh_cn.lang
> +thaumicaugmentation.research.eldritch_spire.0=虚域所藏远超我的预期。一个人很容易会猜想，如此接近虚空的世界应当除荒芜废土之外别无他物，但在腐化侵袭地区的边缘，不可名状的存在令我为之战栗。某种存在刺穿了这一地带，就像是次元边界的表面之中刺入的尖锐碎片。我惊异万分，因为此处的现实已经由于此处蕴存的不尽其数的裂缝而变得扭曲易塑，而一时失足将会导致我躲入万劫
```suggestion
thaumicaugmentation.research.eldritch_spire.0=虚域所藏远超我的预期。人们往往会认为，在如此接近虚空的世界中，除荒芜废土之外应当别无他物，但在腐化侵袭地区的边缘，却有不可名状的存在令我为之战栗。某种存在刺穿了这一地带，就像是次元边界的表面之中刺入的尖锐碎片。我惊异万分，因为这是片险恶之地，其中蕴存的不尽其数的裂缝已经使此处的现实变得扭曲易塑，在这里一时失足也会导致我堕入万劫不复的深渊。在这变幻不定的现实中，几乎可以确信，某种充满恶意的影响将会出现，或是抵达此处——如果其最初并非在此诞生的话。<BR>如今，我逐渐意识到，邪术远不止是神秘术的一个分支，也不止是扭曲人们智识的知识。特别是血腥仪式，其间充斥着对“邪术”这一词汇的运用，运用时的方式所呈现的涵义远超表面意义本身，暗示着这一切仅为超越凡俗之世的存在者所知晓。对这些存在而言，只是提到这一词汇便近乎亵渎，哪怕是寻常的生灵都不被允许做出这番举动，何况是像我一样的神秘使。<BR>没错，邪术绝不仅仅是围绕虚空展开的魔法分支。我相信它指的是一亘古长存的种族，它们对世界的影响塑造了我如今看作现实并视若寻常的森罗万象。如果它们确实存在，那么我发现的诸多古怪现象将会获得解答，尤其是魔法原理中的古怪之处、为什么世界中会出现某种生物，以及一些人是如何彻底失去理智并堕入疯狂，献身于毫无益处的恐怖仪式之中。<BR>如果我想真正理解这一切，我必须更为深入地探索虚域，探寻是什么造成了灵气场的混乱。这种邪术影响极有可能对我这样相对渺小的存在抱有敌意，但知识总伴随着危险，我已无法回头。我将一往无前，直到取得这些知识所能赐给我的强大力量。
```

2020-10-20 10:47 UTC, TUsama approved these changes

2020-10-21 13:38 UTC, Determancer commented on projects/1.12.2/assets/thaumic-wands/thaumicwands/lang/zh_cn.lang
> -item.wand.mithminite.cap=秘金闪耀
```suggestion
item.wand.mithrillium.cap=秘银谐鸣
item.wand.adaminite.cap=精金镶饰
item.wand.mithminite.cap=秘金华缀
```

2020-11-10 08:12 UTC, TUsama approved these changes

2020-11-10 15:13 UTC, merged