添加元素秘学
CFPAOrg/Minecraft-Mod-Language-Package pull request #833
Opened 2020-10-11 07:53 UTC by TUsama

- [ ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是: `projects/1.12.2/assets/curseforge 域名/模组资源 id/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是: `projects/1.16.1/assets/curseforge 域名/模组资源 id/lang/zh_cn.json`
- [ ] 我已确认语言文件名大小写正确，所有的语言文件全为小写；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2020-10-11 07:57 UTC, TUsama commented
严格来说是我第一次独立翻译帕秋莉，然而没有完成。。

@ChromaPIE 您有时间可以帮忙看看，glory一节难度奇高，虽然之前和Ex讨论过但还是有点不放心，所以还请帮忙瞄两眼。

2020-10-11 09:16 UTC, Determancer commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/energy/entry_combustion.json
> +      "text": "$(item)神秘燃烧产能室$() 使用 $(item)火之元素$()产生OE。$(br)每个火之元素的可以燃烧100ticks，产能速率为 10 OE/t。$(br)如果没有其它的机器消耗它的能量，它会自动停止工作。"
```suggestion
      "text": "$(item)神秘燃烧产能室$() 使用 $(item)火之元素$()产生OE。$(br)每个火之元素的可以燃烧 100 刻，产能速率为 10 OE/刻。$(br)如果没有其它的机器消耗它的能量，它会自动停止工作。"
```
你这个提交量过于离谱（X
不过好在上古天坑的精卫又回来了（）

2020-10-11 10:19 UTC, TUsama commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/energy/entry_combustion.json
> +      "text": "$(item)神秘燃烧产能室$() 使用 $(item)火之元素$()产生OE。$(br)每个火之元素的可以燃烧100ticks，产能速率为 10 OE/t。$(br)如果没有其它的机器消耗它的能量，它会自动停止工作。"
艹

2020-10-16 06:08 UTC, baka-gourd commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/energy/entry_accumulator.json
> +      "text": "$(item)源力积聚室$()由OE驱动。$(br)它会将储存于它的内部缓存的OE转化为源力，如果你想要它这样干的话 (100 OE = 1 源力)。$(br)它会提升源力0.1每刻的再生速率。$(br2)它可以被任何能够储存OE的方块充能，你只需要将其连接在一起即可。或者是站在其旁也可充能(只有装备它的时候才能这样)。"
改成0.1源力/t，试试

2020-10-16 06:08 UTC, baka-gourd commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/energy/entry_combustion.json
> +      "text": "$(item)神秘燃烧产能室$() 使用$(item)火之源质$()产生OE。$(br)每单位火之源质的可以燃烧100刻，产能速率为 10 OE/刻。$(br)如果没有其它的机器消耗它的能量，它会自动停止工作。"
同理，刻感觉并没有tick好

2020-10-16 06:10 UTC, TUsama commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/energy/entry_combustion.json
> +      "text": "$(item)神秘燃烧产能室$() 使用$(item)火之源质$()产生OE。$(br)每单位火之源质的可以燃烧100刻，产能速率为 10 OE/刻。$(br)如果没有其它的机器消耗它的能量，它会自动停止工作。"
艹，到底要哪个

2020-11-22 07:01 UTC, baka-gourd requested changes
没汉化的都没删。

2020-11-22 07:01 UTC, baka-gourd commented on projects/1.12.2/assets/elementaristics/lang/zh_cn.lang
> +advancement.elementaristics.tunneler=Whoosh!
是梗的话可以到群里问问，下面也是

2020-11-22 08:22 UTC, TUsama commented
~needmerge

2020-11-22 08:26 UTC, baka-gourd approved these changes

2020-11-22 09:23 UTC, fansi2020 commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/categories/vis_vitalis.json
> +  "description": "生命灵气是每个活物都拥有的能量，这种能量由灵魂与大地共振而产生。这种能量可以在很多方面得到利用，譬如植物以及其它人工生命形式。",
共振似乎是个关于周期震动专业名词

2020-11-22 13:40 UTC, ChromaPIE requested changes
翻译的文字基本没有问题。当然，因为不可能一条一条跟原文对照，所以不排除有用典/玩梗没翻出来的情况。留日后玩家来发掘。

主要的问题两个：

- 标点符号。全角的、半角的、全角半角混用的、前全后半前半后全的都有；
- 翻译没有完成。确实，这个PR拖了一个多月，没有翻译完的部分显然也留了一个多月。

2020-11-22 13:40 UTC, ChromaPIE commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/categories/arcane_lessons.json
> +  "description": "我厌倦了去探寻星辰之力 $(t:讽刺的是，这本书依然包含了这些内容)或者书籍中的知识$(); 我开始聆听我的血液的低语 —— 那是它的教诲。",
_我血液的低语_

可以不改，但是下次如果有这种多重所属/修饰关系导致A的B的C，可以先看看AB的C或者A的BC是不是顺口，特别是A是人称代词的时候。譬如我妈的朋友、你的工作进展、酒石酸的视频播放量等等

2020-11-22 13:40 UTC, ChromaPIE commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/categories/energy.json
> +  "description": "是什么支撑着我们所孜孜不倦地探求的事物？ 这对于整个神秘学的研究而言，是最本质的问题。",
_是什么支撑着我们孜孜不倦探求的事物？_

其实没有问题，但是如果这句话出现在我初中的改病句题里，我绝对会很怀疑。

2020-11-22 13:40 UTC, ChromaPIE commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/alchemy/entry_base_materials.json
> +      "text": "$(item)星尘$() 就是星尘。它是太阳的血液 —— 腐烂后的。$(br)这就是我们。一个名字，一个占据着一部分空间的身体，就我们能看到的而言，外在的表现与其内在总是有着联系。$(br)它几乎就是$(item)萤石粉$()的反面。。。或者其实是一个东西，神秘学的悖论诡计，不是么。"
_反面 **。。。**_

通篇所有省略号都采用了。。。的形式吗

2020-11-22 13:40 UTC, ChromaPIE commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/alchemy/entry_gem.json
> +      "text": "$(item)神秘宝石$()不仅在许多关于$(marked)神秘能量$()的配方中扮演了关键角色，并且还能作为$(marked)仪式材料$()。$(br2)由于这些宝石往往价值昂贵，人们往往热衷于探索，a宝石往往可以在村庄，矿坑，以及其它地方中发现。"
_，以及其它地方**中**发现。_

不必要

2020-11-22 13:40 UTC, ChromaPIE commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/alchemy/entry_vacuum.json
> +      "text": "$(o)谁搞出了这玩意???$()"
**---全角---**

2020-11-22 13:40 UTC, ChromaPIE commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/glory/entry_gods.json
> +      "text": "一般来说，当神性发挥作用时（buff，元素增益，又或者其它的形式），必须使用到OE。如果没有OE，那它就不会生效.$(br2)印记的升级版本，$(o)雕像$()，会比印记得效率更高。你同样可以向其祈祷，只要与其交互一下就可以了。如果祈祷生效了，那么你通常会获得一些有趣的增益。"
这里反而解释了buff的含义 是因为这一页是第一页出现buff这个词的吗

2020-11-22 13:40 UTC, ChromaPIE commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/glory/entry_hour_12.json
> +      "text": "$(o)\"光，只有光，还有辉煌无比的神耀，以及那一轮太阳，所有的灵魂，a throne and a ray of radiance! 太阳不是最初的，但祂是最崇高的，祂的光芒始终沐浴着我们。太阳的的威严为别的神裁定了秩序，并从其祂神那里取来她所需要的，因此她的光芒（herself）就能就能存在的更久一些。\"$()"
_因此她的光芒（herself）**就能就能**存在的更久一些。_

2020-11-22 13:40 UTC, ChromaPIE commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/lessons/lesson_collection.json
> +      "text": "生命(life)元素..。如此的生机勃勃。它的活力能使它的源质在最残酷的环境下也能生存，同时生命元素还留存有部分归属于混沌，当然，秩序是占主导地位的..。直到死亡."
_地位的 **..。**_

2020-11-22 13:40 UTC, ChromaPIE commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/lessons/lesson_collection.json
> +      "text": "火创造了光明，并由大气及大气运动维持了光的存在，..。就连上帝都无法忽视光的瑰丽奇妙."
这个“..。”是有什么含义吗

以及逗号用了全角 句号没用

2020-11-22 13:40 UTC, ChromaPIE commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/lessons/lesson_hours.json
> +}
翻完

2020-11-22 13:40 UTC, ChromaPIE commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/lessons/lesson_multiverse.json
> +      "text": "$(marked)多元宇宙$()..。在那里，我们通常所说的一些基础的，关于时空的概念都是不存在的，环顾我们的认知范围，只有少部分‘地方’拥有如此特性，但换句话说，也有可能只是我们无法理解其中的奥秘，就像其它的许多事那样。如果忽略我们现在所接受的宇宙环境，我们可以粗略的将多元宇宙比作星系."
彻查 **..。**

2020-11-22 13:40 UTC, ChromaPIE commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/souls/dream_truer.json
> +      "text": "我梦见了舞。我梦见了两个舞者，它们与对方一起舞蹈。$(br)其中一个是我，另外一个是“我之为我”。$(br)我所主导下的舞姿令人生厌。错误很多，我逐渐学会忍受，但我可以窥见这支舞蹈的潜力，那动人心弦的美。我也看见了真正应该主导这支舞的人是谁."
从这里你应该可以联系上辰时14的and this king is watching a dancer in a mirror woven out of a single thread来完成它的翻译

2020-11-22 13:49 UTC, TUsama commented on projects/1.12.2/assets/elementaristics/lang/zh_cn.lang
> +elementaristics.potion.silence=寂静
我个人认为这里谈论的是情绪上的古波无井，沉默我不太确定能不能用作为情绪，尤其是沉默有着言辞消失的含义，但是这里谈论的不是言辞的消失，而是情绪的消失，所以最后我翻译成了“寂静”，描写这种情绪消失的情况。

2020-11-22 13:53 UTC, TUsama commented on projects/1.12.2/assets/elementaristics/lang/zh_cn.lang
> +item.thaumagral_diamond.name=Diamond Thaumagral
用来施法的，但是我找了半天不知道到这个的后半截是从哪里弄来的。

2020-11-22 13:54 UTC, TUsama commented on projects/1.12.2/assets/elementaristics/lang/zh_cn.lang
> +tooltip.poison_wintersbreath.name=首先袭来的是来自寒冬的吐息, 紧随其后的是无比的饥饿
遗漏了。

我用正则找找还有没有遗漏的标点。

2020-11-22 14:01 UTC, TUsama commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/categories/energy.json
> +  "description": "是什么支撑着我们所孜孜不倦地探求的事物？ 这对于整个神秘学的研究而言，是最本质的问题。",
奇怪的“所”，可能是我当初漏删了。

2020-11-22 14:02 UTC, TUsama commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/alchemy/entry_base_materials.json
> +      "text": "$(item)星尘$() 就是星尘。它是太阳的血液 —— 腐烂后的。$(br)这就是我们。一个名字，一个占据着一部分空间的身体，就我们能看到的而言，外在的表现与其内在总是有着联系。$(br)它几乎就是$(item)萤石粉$()的反面。。。或者其实是一个东西，神秘学的悖论诡计，不是么。"
基本上，除了一处，我把那一处改了吧。

2020-11-22 14:06 UTC, TUsama commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/glory/entry_gods.json
> +      "text": "一般来说，当神性发挥作用时（buff，元素增益，又或者其它的形式），必须使用到OE。如果没有OE，那它就不会生效.$(br2)印记的升级版本，$(o)雕像$()，会比印记得效率更高。你同样可以向其祈祷，只要与其交互一下就可以了。如果祈祷生效了，那么你通常会获得一些有趣的增益。"
不，这里指的是buff，或者元素增益（不在buff栏），或者一些其它稀奇古怪的效果（比如产能）。

2020-11-22 14:10 UTC, TUsama commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/lessons/lesson_collection.json
> +      "text": "火创造了光明，并由大气及大气运动维持了光的存在，..。就连上帝都无法忽视光的瑰丽奇妙."
单纯的替换问题。。。。

2020-11-22 14:29 UTC, TUsama commented on projects/1.12.2/assets/elementaristics/patchouli_books/liber_elementium/zh_cn/entries/souls/dream_truer.json
> +      "text": "我梦见了舞。我梦见了两个舞者，它们与对方一起舞蹈。$(br)其中一个是我，另外一个是“我之为我”。$(br)我所主导下的舞姿令人生厌。错误很多，我逐渐学会忍受，但我可以窥见这支舞蹈的潜力，那动人心弦的美。我也看见了真正应该主导这支舞的人是谁."
主要是这个作者私设太多了，混了很多爱手艺的东西，我很多都问了Ex，但是这个mirror和dancer似乎在洛的文章里从未出现过，所以我们一直都不太敢直接翻。

我这里直接翻了，毕竟一直空着也不太好。

2020-12-13 15:21 UTC, baka-gourd approved these changes

2020-12-13 15:35 UTC, ChromaPIE approved these changes

2020-12-13 15:38 UTC, merged