添加8个模组翻译，修复/更新3个模组翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #841
Opened 2020-10-26 13:37 UTC by 10935336

添加 advancedchat、bbor 、chesttracker、durabilityviewer、inventoryprofiles、itemscroller、malilib、replaymod 翻译，修复/更新 minihud、tweakeroo、litematica 翻译。
注意：replaymod不在curseforge上。
经测试 mini-hud 可以正确使用 json 文件翻译，已删除 lang 文件（之前作者给的是lang）。

- [ ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是: `projects/1.12.2/assets/curseforge 域名/模组资源 id/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是: `projects/1.16.1/assets/curseforge 域名/模组资源 id/lang/zh_cn.json`
- [ ] 我已确认语言文件名大小写正确，所有的语言文件全为小写；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2020-10-27 11:14 UTC, TUsama commented
。。。？请上传英文文件。

2020-10-27 11:29 UTC, TUsama requested changes

2020-10-27 11:29 UTC, TUsama commented on projects/1.16.1/assets/advancedchat/advancedchat/lang/zh_cn.json
> +  "config.advancedchat.info.visibility.always": "聊天栏在任何时候都会§6整个渲染窗口§r(不会消失)",
```suggestion
  "config.advancedchat.info.visibility.always": "聊天栏在任何时候都会§6整个的渲染窗口§r(不会消失)",  
```
或者：
```suggestion
  "config.advancedchat.info.visibility.always": "聊天栏在任何时候都会渲染§6整个窗口§r(不会消失)",  
```

2020-10-27 11:29 UTC, TUsama commented on projects/1.16.1/assets/chest-tracker/chesttracker/lang/zh_cn.json
> +{
请将文件内的半角标点更改为全角标点。

省略号不用。

2020-10-27 11:29 UTC, TUsama commented on projects/1.16.1/assets/giselbaers-durability-viewer/durabilityviewer/lang/zh_cn.json
> +    "durabilityviewer.config.tt.showdamagepercent": "在装备仍高于此百分比的情况下,显示的是损耗值而不是剩余耐久值",
```suggestion
    "durabilityviewer.config.tt.showdamagepercent": "在装备仍高于此百分比的情况下，显示的是损耗值而不是剩余耐久值",
```

2020-10-27 11:29 UTC, TUsama commented on projects/1.16.1/assets/giselbaers-durability-viewer/durabilityviewer/lang/zh_cn.json
> +    "durabilityviewer.config.tt.showalltrinkets": "如果您有饰品mod,即使没有耐久值/损耗值,也要显示所有的饰品"
```suggestion
    "durabilityviewer.config.tt.showalltrinkets": "如果您有饰品mod，即使没有耐久值/损耗值，也要显示所有的饰品"    
```

2020-10-27 11:29 UTC, TUsama commented on projects/1.16.1/assets/item-scroller/itemscroller/lang/zh_cn.json
> +	"Enables special handling for the Villager GUIs.\n(Normally you can't shift click items in them.)\nHold shift and scroll up/down over the trade output slot.": "启用为村民交易 GUI 进行特殊处理(一般情况下，你不能在交易界面 Shif
```suggestion
	"Enables special handling for the Villager GUIs.\n(Normally you can't shift click items in them.)\nHold shift and scroll up/down over the trade output slot.": "启用为村民交易 GUI 所进行特殊处理(一般情况下，你不能在交易界面 Shift 点击物品)，可以对购买物品进行滚动",
```

2020-10-27 11:29 UTC, TUsama commented on projects/1.16.1/assets/item-scroller/itemscroller/lang/zh_cn.json
> +	"Enables moving all matching stacks at once by holding\nshift while placing items to an empty slot": "启用在将物品放置到一个空槽时，按住 Shift 键，可以一次移动所有匹配的物品",
为什么上面的enable是允许，这里的是启用？

2020-10-30 06:39 UTC, TUsama approved these changes

2020-10-30 06:54 UTC, TUsama requested changes
~我不知道这么多的奇怪的key错误是怎么出现的。。。但是与 https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/807  几乎是一样的问题。。。我之前已经回滚了一遍litematica的问题，这里估计也需要你回滚一下。

顺便@baka-gourd @exzhawk 这个问题在https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/4b0518a7d1679e384f479e9d6306589bd2206471/projects/1.16.1/assets/tweakeroo/tweakeroo/lang/zh_cn.json 中也存在，可能是爬虫确实出现了什么问题，或者是wl那边的问题。~

神必至极，这个新出的key居然真的能工作。。

2020-10-30 06:54 UTC, TUsama commented on projects/1.16.1/assets/item-scroller/itemscroller/lang/zh_cn.json
> +{
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

等等。。。为什么英文文件只有12行，但中文文件却有124行？？？

2020-10-30 06:54 UTC, TUsama commented on projects/1.16.1/assets/malilib/malilib/lang/zh_cn.json
> +    "malilib.error.invalid_directory": "Invalid directory name '%s'",
漏翻？

2020-10-30 06:54 UTC, TUsama commented on projects/1.16.1/assets/malilib/malilib/lang/zh_cn.json
> +    "malilib.message.moved_layer_range": "整体移动 by §a%s§r on the §a%s§r axis",
这里需要翻译吗？

2020-10-30 06:54 UTC, TUsama commented on projects/1.16.1/assets/malilib/malilib/lang/zh_cn.json
> +    "Enables scrolling items to and from crafting grids,\nwith a built-in 18 recipe memory.\nHold down the Recipe key to see the stored recipes and\nto change the selection. While holding the Recipe
这个key究竟是怎么回事。。。？

2020-11-01 16:41 UTC, baka-gourd commented
#847

2020-11-02 01:40 UTC, merged