更新rpghud模组的zh_cn.lang
CFPAOrg/Minecraft-Mod-Language-Package pull request #842
Opened 2020-10-27 09:44 UTC by RisingInIris2017

- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是: `projects/1.12.2/assets/curseforge 域名/模组资源 id/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是: `projects/1.16.1/assets/curseforge 域名/模组资源 id/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件全为小写；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2020-10-27 11:22 UTC, WuzgXY-GitHub commented
麻烦上传一下英文文件以便对照 ..(:з」∠)..

2020-10-27 12:32 UTC, ChromaPIE requested changes
请一并上传en_us.lang

2020-11-02 01:52 UTC, baka-gourd commented
@RisingInIris2017 请上传enus

2020-11-10 08:11 UTC, TUsama requested changes

2020-11-10 08:11 UTC, TUsama commented on projects/1.12.2/assets/rpg-hud/rpghud/lang/zh_cn.lang
> +name.face_position=Face Pos
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

？

2020-11-11 10:35 UTC, RisingInIris2017 commented
补上了缺失的 Face Pos 翻译。

2020-11-11 13:53 UTC, merged