原始核心翻译更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #876
Opened 2020-11-21 08:58 UTC by mcBegins2Snow

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [x] 我已确认文件路径、分支均正确：
    - 是 1.12 翻译，应该是: `projects/1.12.2/assets/primalcore/primal/lang/zh_cn.lang`
- [x] 我已确认语言文件名大小写正确，所有的语言文件全为小写；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2020-11-23 00:06 UTC, baka-gourd commented
请手动与主仓库同步一次。

2020-11-23 00:40 UTC, mcBegins2Snow commented
怎么操作

2020-11-23 13:49 UTC, TUsama requested changes
今晚的量

2020-11-23 13:49 UTC, TUsama commented on projects/1.12.2/assets/primalcore/primal/lang/zh_cn.lang
>  chat.message.primal.cannot_sleep_monster=一身冷汗将你惊醒了
```suggestion
chat.message.primal.cannot_sleep_monster=你在一身冷汗中惊醒
```

冷汗不能把人惊醒吧（

2020-11-23 13:49 UTC, TUsama commented on projects/1.12.2/assets/primalcore/primal/lang/zh_cn.lang
> +chat.message.primal.cauldron_heat_cold=是凉的
为啥把 is 移到这边来了？

2020-11-23 13:49 UTC, TUsama commented on projects/1.12.2/assets/primalcore/primal/lang/zh_cn.lang
> +chat.message.primal.cauldron_heat_too_hot=太热
```suggestion
chat.message.primal.cauldron_heat_too_hot=很热
```
如果是“太热”，整句就会变成“坩埚太热”，有轻微的古怪感，况且too hot在key顺序上是比super hot要前的，太热是否有超过超级热的嫌疑？

2020-11-23 13:49 UTC, TUsama commented on projects/1.12.2/assets/primalcore/primal/lang/zh_cn.lang
>  chat.message.primal.set_spawn=床的位置已设置
```suggestion
chat.message.primal.set_spawn=已设置床的位置
```
可有可无的修改

2020-11-23 13:49 UTC, TUsama commented on projects/1.12.2/assets/primalcore/primal/lang/zh_cn.lang
>  jei.info.primal.cauldron=坩埚可用于烹饪或混合物品。使用桶和水瓶来添加液体，物品需要从顶部扔入坩埚，使用锅勺来查看当前状态。
```suggestion
jei.info.primal.cauldron=坩埚可用于烹饪或混合物品。你可以使用桶和水瓶来向其中添加液体。从顶部将物品扔入坩埚内。对其使用锅勺可以查看当前状态。
```
祈使句，若直翻则缺失主语。

2020-11-23 13:49 UTC, TUsama commented on projects/1.12.2/assets/primalcore/primal/lang/zh_cn.lang
>  jei.info.primal.charcoal=是通过燃烧埋在地下的原木堆来生产不同等级木炭。木堆可以组合在一起，但必须完全被覆盖。
```suggestion
jei.info.primal.charcoal=燃烧埋在地下的原木堆，可生产出不同等级木炭。木堆可以堆叠着摆放，但在燃烧时必须将它们完全埋起来。
```

2020-11-23 13:49 UTC, TUsama commented on projects/1.12.2/assets/primalcore/primal/lang/zh_cn.lang
>  jei.info.primal.cineris_fiber=狱火绒纤毛会掉落狱火绒纤维，主要在下界被找到。
```suggestion
jei.info.primal.cineris_fiber=狱火绒纤毛会掉落狱火绒纤维，多见于下界。
```

2020-11-23 13:49 UTC, TUsama commented on projects/1.12.2/assets/primalcore/primal/lang/zh_cn.lang
>  jei.info.primal.debug_dirt_stick=这个调试物品能够显示晾晒架和火盆进度，能够重置这些类似方块的停滞事件。
```suggestion
jei.info.primal.debug_dirt_stick=这个调试物品能够显示晾晒架和火盆进度，并能够在事件更新停止时重置这些以及类似方块的进度。
```

我不太确定这是不是 the event updates have been stalled 的意思。仅做参考。

2020-11-23 13:49 UTC, TUsama commented on projects/1.12.2/assets/primalcore/primal/lang/zh_cn.lang
>  jei.info.primal.drying_rack=将要干燥的物品放在顶部的板条上。远离雨水并靠近热源和光源以获得让你满意的效果。
```suggestion
jei.info.primal.drying_rack=将待干燥的物品放在顶部的板条上。若想让其达到最佳工作效率，晾晒时请远离雨水并靠近热源和光源。
```

2020-11-24 01:15 UTC, mcBegins2Snow commented on projects/1.12.2/assets/primalcore/primal/lang/zh_cn.lang
> +chat.message.primal.cauldron_heat_cold=是凉的
不移过来的话，后面的super hot和too hot就对不上

2020-11-25 02:03 UTC, baka-gourd commented on projects/1.12.2/assets/primalcore/primal/lang/zh_cn.lang
> +jei.info.primal.nethergrowth=
删除

2020-11-25 02:04 UTC, baka-gourd commented on projects/1.12.2/assets/primalcore/primal/lang/zh_cn.lang
> +primal.lighting.tooltip=
空key全部删除

2020-11-25 02:44 UTC, TUsama approved these changes

2020-11-25 10:32 UTC, merged