[NR]1.16
CFPAOrg/Minecraft-Mod-Language-Package pull request #883
Opened 2020-11-27 01:49 UTC by LucunJi

***注：这个作者的 GitHub repo 没有跟上发布版本，参考用的英文语言文件是从 `tetra-1.16.4-3.3.1` 里面扒出来的。自己进游戏大致检查过，但是有点不放心就标了个 NR***

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [x] 我已标记PR以便审查（见`CONTRIBUTING.md`）
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是: `projects/1.12.2/assets/curseforge 域名/模组资源 id/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是: `projects/1.16.1/assets/curseforge 域名/模组资源 id/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件全为小写；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2020-11-27 02:54 UTC, baka-gourd commented
是112上来的吗

2020-11-27 02:55 UTC, yanxiangrong commented
1.16.3

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Nullpinter <notifications@github.com>
Sent: Friday, November 27, 2020 10:54:16 AM
To: CFPAOrg/Minecraft-Mod-Language-Package <Minecraft-Mod-Language-Package@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [CFPAOrg/Minecraft-Mod-Language-Package] [NR]1.16 (#883)


是112上来的吗

―
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/883#issuecomment-734593705>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AJQ3MJ25JFFGPG3SHFB2RP3SR4IFRANCNFSM4UEKU6RQ>.

2020-11-27 18:55 UTC, LucunJi commented
> 是112上来的吗

跟 1.12 的比起来算是大改了。没怎么接触过 GitHub 的标签系统，不太懂该怎么操作。

2020-11-29 06:37 UTC, WuzgXY-GitHub commented
[英文文件](https://github.com/LWHK/LWHK-Simplified-Chinese-Translation/blob/master/translation/tetra/en_us%20for%20%23883.json)

2020-11-29 07:39 UTC, WuzgXY-GitHub approved these changes
100 行 100 行地 review

2020-11-29 07:39 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.tool.pry.requirement": "这一步需要一个 %d 级的撬具。\n§7羊角头可以被用于撬。",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

「撬」字似乎不够自然，不过为了统一性可以理解。能换就换，不换也成

2020-11-29 07:39 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.tool.available": "你有一 个%d 级的",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
    "tetra.tool.available": "你有一个 %d 级的",
```

2020-11-29 07:39 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.holo.craft.materials.stat.secondary.tooltip": "材料的密度、刚性或重量。被挥动时携带的动大小。",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

```suggestion
    "tetra.holo.craft.materials.stat.secondary.tooltip": "材料的密度、刚性或重量。被挥动时携带的动能大小",
```

2020-11-29 07:39 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.stats.speed.tooltip_extended": "挥动“冷却”由屏幕中央的指示条显示。可以在冷却完毕前挥动，但是攻击会造成更少的伤害。横扫或急速打击之类的效果只有在攻击指示条完全充满时才会被触发。§7速度值相当于采集效率的倍率。取决于大于或小于 1,它会增加或减少方块被破坏的速度。倍率计算方式如下：§f§o倍率 = 速度 * 0.5 + 0.5§r§7",
|Feedback Priority|
|---|
|🌫 Dust / Non-blocking, “take it or leave it”|

```suggestion
    "tetra.stats.speed.tooltip_extended": "挥动“冷却”由屏幕中央的指示条显示。可以在冷却完毕前挥动，但是攻击会造成更少的伤害。横扫或急速打击之类的效果只有在攻击指示条完全充满时才会被触发。§7速度值相当于采集效率的倍率。取决于大于或小于 1，它会增加或减少方块被破坏的速度。倍率计算方式如下：§f§o倍率 = 速度 * 0.5 + 0.5§r§7",
```

2020-11-29 07:39 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.stats.draw_strength.tooltip_extended": "伤害计算基于原版的弹射物行为。伤害的下限取决于模块与升级，上限是：§f§o上限 = 下限 * 1.5 + 1§r§7。由不完全拉开的弓射出的弹射物伤害基于下限计算，例如：从 50%% 拉开的弓射出的弹射物会造成 50%% 的伤害下限。",
|Feedback Priority|
|---|
|🌫 Dust / Non-blocking, “take it or leave it”|

```suggestion
    "tetra.stats.draw_strength.tooltip_extended": "伤害计算基于原版的弹射物行为。伤害的下限取决于模块与升级，上限计算方法如下：§f§o上限 = 下限 * 1.5 + 1§r§7。由不完全拉开的弓射出的弹射物伤害基于下限计算，例如：从 50%% 拉开的弓射出的弹射物会造成 50%% 的伤害下限。",
```

2020-11-29 11:15 UTC, WuzgXY-GitHub requested changes
(200/2083)

2020-11-29 11:15 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.stats.bleeding.tooltip": "攻击生物时有 30%% 的概率使它们以 §e%s§r 的伤害持续流血 2 秒",
|Feedback Priority|
|---|
|🌫 Dust / Non-blocking, “take it or leave it”|

```suggestion
    "tetra.stats.bleeding.tooltip": "攻击生物时有 30%% 的概率使它们以 §e%s§r 点的伤害持续流血 2 秒",
```

2020-11-29 11:15 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.stats.backstab.tooltip": "从背后击中目标会造成致命一击，造成 §e%s§r 点额外伤害",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
    "tetra.stats.backstab.tooltip": "从背后击中目标会产生暴击，并造成 §e%s§r 点额外伤害",
```

2020-11-29 11:15 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.stats.armor.tooltip": "持有时提供 §e%s§r 点护甲值",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
    "tetra.stats.armor.tooltip": "装备时提供 §e%s§r 点护甲值",
```

2020-11-29 11:15 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.stats.toughness.tooltip": "在持有时提供 §e%s§r 点坚韧值",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
    "tetra.stats.toughness.tooltip": "装备时提供 §e%s§r 点盔甲韧性",
```

2020-11-29 11:15 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.stats.unarmoredDamage.tooltip": "攻击无护甲的生物时造成 §e%s§r 的额外伤害",
|Feedback Priority|
|---|
|🌫 Dust / Non-blocking, “take it or leave it”|

```suggestion
    "tetra.stats.unarmoredDamage.tooltip": "攻击无护甲的生物时造成 §e%s§r 点的额外伤害",
```

本段各行描述需要统一行尾句号的去留。如果有我没看出来的「点」相关问题，也最好改一改。

2020-11-29 11:15 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.stats.fortune.tooltip": "在采集或回收方块时增加掉落几率",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

回收？这个的英文我也没看懂

2020-11-29 11:15 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.stats.flame.tooltip": "击中实体时使它着火 §e%s§r 秒，弹射物会点燃tnt和营火一类的方块",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

```suggestion
    "tetra.stats.flame.tooltip": "击中实体时使它着火 §e%s§r 秒，弹射物会点燃 TNT 与营火一类的方块",
```

2020-11-29 11:15 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.stats.speed.tooltip_extended": "挥动“冷却”由屏幕中央的指示条显示。可以在冷却完毕前挥动，但是攻击会造成更少的伤害。横扫或急速打击之类的效果只有在攻击指示条完全充满时才会被触发。§7速度值相当于采集效率的倍率。取决于大于或小于 1,它会增加或减少方块被破坏的速度。倍率计算方式如下：§f§o倍率 = 速度 * 0.5 + 0.5§r§7",
除此之外，「之类的」一词明显不够书面。

2020-11-29 11:15 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.stats.toolbelt.quickslot.tooltip": "有 §e%s§r 个快速插槽",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
    "tetra.stats.toolbelt.quickslot.tooltip": "有 §e%s§r 个快捷栏槽位",
```

2020-11-29 11:15 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.stats.zoom.tooltip": "当瞄准或按住 [shift] 时放大 §e%sx§r 倍",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

请统一是否添加方括号。

2020-11-29 11:15 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.stats.earthbind.tooltip": "攻击生物时有 §e10%%§r 的概率将它锁在原地 §e%s 秒§r。更容易出现在更低的高度，概率在基岩处达到最大的 §e50%%§r。",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

```suggestion
    "tetra.stats.earthbind.tooltip": "攻击生物时有 §e10%%§r 的概率将它锁在原地 §e%s 秒§r。高度越低，生效概率越大，概率在基岩处达到最大的 §e50%%§r。",
```

2020-11-29 11:34 UTC, WuzgXY-GitHub requested changes
300 / 2083

2020-11-29 11:34 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.stats.workable.tooltip": "打磨这个物品的耗时减少 §e%s§r 次",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

```suggestion
    "tetra.stats.workable.tooltip": "打磨这个物品的需要次数减少 §e%s§r",
```
```suggestion
    "tetra.stats.workable.tooltip": "打磨这个物品的耗时减少 §e%s§r",
```

我没玩过这个模组，需要从这两个当中选一个。

2020-11-29 11:34 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.stats.hoe.tooltip": "这个物品可被用于采集植物\n %s\n§7锄等级：§e%s\n§7锄效率：§e%s",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

```suggestion
    "tetra.stats.hoe.tooltip": "这个物品可被用于收获作物\n %s\n§7锄等级：§e%s\n§7锄效率：§e%s",
```

2020-11-29 11:34 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.material.acacia": "金合欢",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

金合欢木。下同。

2020-11-29 11:45 UTC, WuzgXY-GitHub requested changes
367 / 2083

2020-11-29 11:45 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.material.wither_bone": "凋零之骨",
|Feedback Priority|
|---|
|⛰ Mountain / **You must make this correct**|

```suggestion
    "tetra.material.wither_bone": "凋灵之骨",
```

2020-11-29 11:45 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.material.wither_bone.prefix": "凋零之骨",
|Feedback Priority|
|---|
|⛰ Mountain / **You must make this correct**|

```suggestion
    "tetra.material.wither_bone.prefix": "凋灵之骨",
```

2020-11-29 12:27 UTC, WuzgXY-GitHub requested changes
400 / 2083

2020-11-29 12:27 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "block.tetra.basic_workbench": "工作台",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

与原版冲突。此 PR 目前不能被合并。

2020-11-29 12:27 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "block.tetra.basic_workbench.description": "用锤子右击合成台以创建工作台",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

表述略怪

2020-11-29 12:27 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "block.tetra.rack.description": "物品可以被挂在架子上。用右键放入或取出物品。\n在工作台附近挂在架子上的工具就像在玩家背包里一样可以用于合成，架子需要在 3x3x3 的范围内才能起效（以工作台向上一个方块为中心）。",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

所有「工作台」都需要被更改。下同。

2020-11-29 12:27 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "item.tetra.metal_scrap.description": "奇形怪状的金属，它们的并无用处或用途未知，等待你赋予它们全新的价值",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
    "item.tetra.metal_scrap.description": "奇形怪状的金属，它们用途未知或已无用处，并在等待你赋予它们全新的价值",
```

2020-11-29 12:27 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "item.tetra.metal_scrap": "金属废料",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

废料还是碎片？

2020-11-29 12:27 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "item.tetra.vent_plate.description": "连接到锻造锤或传输单元上能稍微提高效率",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

```suggestion
    "item.tetra.vent_plate.description": "连接到锻造锤或传输单元上可以提高效率",
```

2020-11-29 12:27 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "item.tetra.planar_stabilizer.description": "可以被连接到锻造锤上，让用锻造锤合成的主要组件略微增加属性",
|Feedback Priority|
|---|
|🌫 Dust / Non-blocking, “take it or leave it”|

```suggestion
    "item.tetra.planar_stabilizer.description": "可以被连接到锻造锤上，让用锻造锤合成的主要组件略微提高属性",
```
不够通顺

2020-11-29 12:27 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "item.tetra.modular.settle_progress_cost.description": "当物品在被使用时这个组件会被缓慢地固定下来，当被固定后它的完整度消耗会下降。\n \n§7进度：§e%s§7/§e%s\n \n§7基础要求：§e%s\n§7耐久惩罚：§e%s",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
    "item.tetra.modular.settle_progress_gain.description": "物品被使用时这个组件会缓慢地固定下来，固定住后它会提供额外的完整度。\n \n§7进度：§e%s§7/§e%s\n \n§7基础要求：§e%s\n§7耐久惩罚：§e%s",
    "item.tetra.modular.settle_progress_cost.description": "物品被使用时这个组件会缓慢地固定下来，固定住后它的完整度消耗会下降。\n \n§7进度：§e%s§7/§e%s\n \n§7基础要求：§e%s\n§7耐久惩罚：§e%s",
```

2020-11-29 12:27 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.material.wither_bone.prefix": "凋零之骨",
```suggestion
    "tetra.material.wither_bone": "凋灵之骨",
    "tetra.material.wither_bone.prefix": "凋灵之骨",
```

2020-11-29 12:27 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.improvement.quality.description": "这个组件质量不错，它提供少量的伤害与采集效率增益",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

```suggestion
    "tetra.improvement.quality.description": "这个组件质量较高，它可以提供少量的伤害与采集效率增益",
```

2020-11-29 12:27 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.improvement.settled.description": "为了增加用处，这个组件被固定了。这能提供额外的完整度",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

此处原文
> Due to extended use

并非目的为用处增加，而是由于已有的（extend**ed**）用处增加此组件才被固定的。

2020-11-29 13:17 UTC, WuzgXY-GitHub requested changes
1042 / 2083

2020-11-29 13:17 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra/schematic/sword/shared_blade/hone_damage_2.description": "进一步打磨组件的伤害增益，使伤害增益从 0.5 增加到 1。",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

我觉得你不能打磨一个增益。下同。

2020-11-29 13:17 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra/schematic/double/basic_handle/wrap_handle.description": "使用给定材料裹柄。轻微增加攻击和攻速，并减少手柄可能导致的负面效果。",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
    "tetra/schematic/double/basic_handle/wrap_handle.description": "使用给定材料裹柄。较小地增加伤害和挥动速度，并且减少手柄可能导致的负面效果。",
```
同 L582

2020-11-29 13:17 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra/schematic/single/handle/wrap_handle.description": "使用给定材料裹柄。轻微增加攻击和攻速，并减少手柄可能导致的负面效果。",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
    "tetra/schematic/single/handle/wrap_handle.description": "使用给定材料裹柄。较小地增加伤害和挥动速度，并且减少手柄可能导致的负面效果。",
```
同 L582 和 L811

2020-11-29 18:20 UTC, LucunJi commented
我熬夜做的翻译 bug 好多，辛苦校对了。剩下一些没解决的 commit 我空下来仔细想想……

2020-12-05 01:04 UTC, WuzgXY-GitHub commented
全部做完记得 squash，不然太多了

2020-12-08 22:48 UTC, Water-Moon commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.improvement.settled.description": "为了增加用处，这个组件被固定了。这能提供额外的完整度",
根据实际使用，这个事件是发生在大量使用同一个工具之后，和Tinkers Tool Leveling的工具升级类似。
除此之外，`Extended`一词也有【长远的】之意，符合游戏内效果。

因此，提议将这个改为
```长期使用之后，这个组件被固定了。```

2020-12-08 22:50 UTC, Water-Moon commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.improvement.settled.description": "为了增加用处，这个组件被固定了。这能提供额外的完整度",
根据实际使用，这个事件是发生在大量使用同一个工具之后，和Tinkers Tool Leveling的工具升级类似。
除此之外，`Extended`一词也有【长远的】之意，符合游戏内效果。

因此，提议将这个改为
```长期使用之后，这个组件被固定了。```

2020-12-24 06:04 UTC, EnterFor commented
今天mod更新了。

2020-12-25 14:51 UTC, LucunJi commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "item.tetra.holo.tooltip2": "§8[§7右键§8] §7使用",
改了，但是后面有几处“Holding down right-click”还是翻译成右键了。因为感觉“按住右键”比“按住（保持）右击”更好一点。

2020-12-25 14:55 UTC, LucunJi commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra.stats.zoom.tooltip": "当瞄准或按住 [shift] 时放大 §e%sx§r 倍",
我这里的方括号是按照原文加的。需要帮作者统一一下格式吗？

2020-12-25 14:59 UTC, LucunJi commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "item.tetra.metal_scrap": "金属废料",
改成碎片了，和 Netherite Scrap 一样

2020-12-25 15:09 UTC, LucunJi commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "block.tetra.rack.description": "物品可以被挂在架子上。用右键放入或取出物品。\n在工作台附近挂在架子上的工具就像在玩家背包里一样可以用于合成，架子需要在 3x3x3 的范围内才能起效（以工作台向上一个方块为中心）。",
加工台？

2020-12-25 15:10 UTC, LucunJi commented on projects/1.16.1/assets/tetra/tetra/lang/zh_cn.json
> +    "tetra/schematic/sword/shared_blade/hone_damage_2.description": "进一步打磨组件的伤害增益，使伤害增益从 0.5 增加到 1。",
那把 hone 直接翻译成改良或者提升？

2020-12-25 16:20 UTC, TartaricAcid commented
看了下应该没什么大问题了，我就先 squash merge 了啊

2020-12-25 16:22 UTC, merged