安全工艺1.16.4的汉化文件 第二版
CFPAOrg/Minecraft-Mod-Language-Package pull request #891
Opened 2020-12-10 05:03 UTC by long100941

安全工艺1.16.4的汉化文件 第二版

2020-12-10 07:10 UTC, TUsama requested changes

2020-12-10 07:10 UTC, TUsama commented on projects/1.16.1/assets/security-craft/securitycraft/lang/zh_cn.json
> +	"block.securitycraft.reinforced_yellow_wool":"强化黄羊毛",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

漏字

2020-12-10 07:10 UTC, TUsama commented on projects/1.16.1/assets/security-craft/securitycraft/lang/zh_cn.json
> +	"block.securitycraft.reinforced_nether_brick_stairs":"强化下城砖楼梯",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

错字

2020-12-10 07:10 UTC, TUsama commented on projects/1.16.1/assets/security-craft/securitycraft/lang/zh_cn.json
> +	"block.securitycraft.reinforced_chiseled_nether_bricks":"强化錾制刻的下界砖块",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

錾制下界砖块

2020-12-10 07:10 UTC, TUsama commented on projects/1.16.1/assets/security-craft/securitycraft/lang/zh_cn.json
> +	"block.securitycraft.keypad_furnace":"密码炉",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

这两项存疑。

2020-12-10 07:10 UTC, TUsama commented on projects/1.16.1/assets/security-craft/securitycraft/lang/zh_cn.json
> +	"block.securitycraft.laser_block":"激光块",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

？

2020-12-10 07:10 UTC, TUsama commented on projects/1.16.1/assets/security-craft/securitycraft/lang/zh_cn.json
> +	"block.securitycraft.laser_active":"主动激光",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

确定是主动，而不是激活吗，如果是的话这条 review 作废。

2020-12-10 07:10 UTC, TUsama commented on projects/1.16.1/assets/security-craft/securitycraft/lang/zh_cn.json
> +	"block.securitycraft.reinforced_netherite_block":"轻巧的灵巧石块",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

你自己看看你翻译的这是什么。

2020-12-10 14:34 UTC, ChromaPIE requested changes
第二版修正了部分错误，但是依然错误横生，没有达到承诺的标准。
另外几个注意：

- 所有继承自1.12.2安全工艺的内容，名称必须与之统一；
- 所有翻译文本内的标点符号，无特殊情况则全部使用全角符号；
- 修改翻译时，翻译文件内所有引用到的表述必须统一。

2020-12-10 14:34 UTC, ChromaPIE commented on projects/1.16.1/assets/security-craft/securitycraft/lang/zh_cn.json
> +	"block.securitycraft.reinforced_glowstone":"强化萤石",
荧石

2020-12-10 14:34 UTC, ChromaPIE commented on projects/1.16.1/assets/security-craft/securitycraft/lang/zh_cn.json
> +	"block.securitycraft.reinforced_gravel":"强化砾石",
砾石是什么

2020-12-10 14:34 UTC, ChromaPIE commented on projects/1.16.1/assets/security-craft/securitycraft/lang/zh_cn.json
> +	"block.securitycraft.trophy_system":"奖杯系统",
主动防御系统

2020-12-10 14:34 UTC, ChromaPIE commented on projects/1.16.1/assets/security-craft/securitycraft/lang/zh_cn.json
> +	"block.securitycraft.block_pocket_manager":"方块口袋管理器",
控制器/控制中枢

2020-12-10 14:34 UTC, ChromaPIE commented on projects/1.16.1/assets/security-craft/securitycraft/lang/zh_cn.json
> +	"item.securitycraft.taser_powered":"PoweredTaser",
漏翻

2020-12-10 14:34 UTC, ChromaPIE commented on projects/1.16.1/assets/security-craft/securitycraft/lang/zh_cn.json
> +	"item.securitycraft.scanner_door_item":"扫描仪门",
安全门

2020-12-10 14:34 UTC, ChromaPIE commented on projects/1.16.1/assets/security-craft/securitycraft/lang/zh_cn.json
> +	"item.securitycraft.sentry":"哨兵",
战斗哨石（下同）

2020-12-10 14:34 UTC, ChromaPIE commented on projects/1.16.1/assets/security-craft/securitycraft/lang/zh_cn.json
> +	"help.securitycraft.reinforced_glass_pane.info":"强化染色玻璃板与原版玻璃相同,不同之处在于只有将其放下的人才能使用Universalblock去除剂将其破坏。",
**_Universalblock去除剂_** 是什么？

2020-12-10 14:34 UTC, ChromaPIE commented on projects/1.16.1/assets/security-craft/securitycraft/lang/zh_cn.json
> +	"help.securitycraft.reinforced_iron_bars.info":"强化铁棒与原版铁棒相同,只不过放下铁棒的人才可以使用通用卸妆器将其摧毁。",
**_通用卸妆器_** 是什么？
Iron Bars是 **_铁棒_** 吗？

2020-12-10 14:34 UTC, ChromaPIE commented on projects/1.16.1/assets/security-craft/securitycraft/lang/zh_cn.json
> +	"help.securitycraft.trophy_system.info":"该奖杯系统受到Activision发布的《使命召唤:现代战争3》中首次出现的小工具的启发,瞄准敌人的箭和火球,并在半个目标后将其摧毁第二次充电时间。",
统一：主动防御系统

2020-12-10 14:34 UTC, ChromaPIE commented on projects/1.16.1/assets/security-craft/securitycraft/lang/zh_cn.json
> +	"gui.securitycraft:keycardSetup.explanation.5":"dem",
漏

2020-12-10 14:34 UTC, ChromaPIE commented on projects/1.16.1/assets/security-craft/securitycraft/lang/zh_cn.json
> +	"gui.securitycraft:logger.date":"Date:%s",
漏

2020-12-10 14:34 UTC, ChromaPIE commented on projects/1.16.1/assets/security-craft/securitycraft/lang/zh_cn.json
> +	"gui.securitycraft:mrat.defuse":"Defuse",
漏

2020-12-10 14:34 UTC, ChromaPIE commented on projects/1.16.1/assets/security-craft/securitycraft/lang/zh_cn.json
> +	"gui.securitycraft:blockReinforcer.title":"UniversalblockReinforcer",
漏

2020-12-12 05:28 UTC, GreyElaina commented
算了吧.

2020-12-12 05:28 UTC, closed without merging