update 1.16 pamsseries
CFPAOrg/Minecraft-Mod-Language-Package pull request #913
Opened 2021-01-07 14:42 UTC by rainsillwood

pamhc2crops-1.16.3-1.0.1
pamhc2foodcore-1.16.3-1.0.0
pamhc2foodextended-1.16.3-1.0.0
pamhc2trees-1.16.3-1.0.0

2021-01-07 14:54 UTC, baka-gourd commented on projects/1.16.1/assets/pams-harvestcraft-2-food-extended/pamhc2foodextended/lang/en_us.json
> +//fruits 4
去除所以的//开头的注释

2021-01-07 15:19 UTC, rainsillwood commented on projects/1.16.1/assets/pams-harvestcraft-2-food-extended/pamhc2foodextended/lang/en_us.json
> +//fruits 4
这是mod自带的……

2021-01-18 06:04 UTC, TUsama requested changes

2021-01-18 06:04 UTC, TUsama commented on projects/1.16.1/assets/pams-harvestcraft-2-food-extended/pamhc2foodextended/lang/zh_cn.json
> +	"item.pamhc2foodextended.ediblerootitem": "食用块根",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

原料是啥，乍一看有点瘆人。

2021-01-18 06:04 UTC, TUsama commented on projects/1.16.1/assets/pams-harvestcraft-2-trees/pamhc2trees/lang/zh_cn.json
> +  "block.pamhc2trees.pampawpaw": "巴婆果",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

待讨论。

2021-01-18 06:04 UTC, TUsama commented on projects/1.16.1/assets/pams-harvestcraft-2-food-extended/pamhc2foodextended/lang/zh_cn.json
> +	"item.pamhc2foodextended.candiedgingeritem": "蜜饯姜片",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

待讨论。

2021-01-18 06:05 UTC, TUsama commented
@hackwellfox 我感觉你有必要来这边看一眼。。

2021-01-18 06:17 UTC, TUsama commented on projects/1.16.1/assets/pams-harvestcraft-2-food-extended/pamhc2foodextended/lang/zh_cn.json
> +	"item.pamhc2foodextended.candiedgingeritem": "蜜饯姜片",
糖渍柠檬，琥珀核桃/山核桃，红薯糖。

2021-01-18 06:23 UTC, hackwellfox commented on projects/1.16.1/assets/pams-harvestcraft-2-food-extended/pamhc2foodextended/lang/zh_cn.json
> +	"item.pamhc2foodextended.candiedgingeritem": "蜜饯姜片",
烧烤味薯片是不是更精准一点

2021-01-18 06:24 UTC, hackwellfox commented
> @hackwellfox 我感觉你有必要来这边看一眼。。

来了来了（上班摸鱼中）

2021-01-18 06:55 UTC, hackwellfox commented on projects/1.16.1/assets/pams-harvestcraft-2-food-core/pamhc2foodcore/lang/zh_cn.json
> +    "item.pamhc2foodcore.chocolatecaramelfudgeitem": "巧克力牛奶软糖",
虽然有个繁体页面是把它叫做【巧克力牛奶软糖】但是【caramel】焦糖是不是应该翻译进去

2021-01-18 06:59 UTC, hackwellfox commented on projects/1.16.1/assets/pams-harvestcraft-2-food-core/pamhc2foodcore/lang/zh_cn.json
> +    "item.pamhc2foodcore.smoresitem": "巧克力夹心饼干",
斯莫尔饼干的棉花糖夹心是特有的，直接叫巧克力夹心饼干是不是太宽泛了

2021-01-18 07:20 UTC, hackwellfox commented on projects/1.16.1/assets/pams-harvestcraft-2-trees/pamhc2trees/lang/zh_cn.json
> +  "block.pamhc2trees.paperbark_sapling": "千层木树苗 ",
沿用【白千层木】是否更精准？（千层属还有其他色的）

2021-01-18 07:40 UTC, hackwellfox commented on projects/1.16.1/assets/pams-harvestcraft-2-trees/pamhc2trees/lang/zh_cn.json
> +  "block.pamhc2trees.pampaperbark": "千层木",
```suggestion
  "block.pamhc2trees.pampaperbark": "白千层木",
```

2021-01-22 14:18 UTC, rainsillwood commented
没时间推敲，且有多个版本翻译更新，放弃orz

2021-01-22 14:18 UTC, closed without merging