update storagetech-1.16.4-R1.2
CFPAOrg/Minecraft-Mod-Language-Package pull request #917
Opened 2021-01-07 15:39 UTC by rainsillwood

update storagetech-1.16.4-R1.2

2021-01-09 04:41 UTC, dovisutu requested changes
首先，在创建多个branch的时候建议采用如下方法：
```
git checkout -b your-branch
# do work
git commit .....
git checkout 1.16
git checkout -b your-branch-2
# do work
```
其次，提出了几个问题

2021-01-09 04:41 UTC, dovisutu commented on projects/1.16.1/assets/storage-tech/storagetech/lang/zh_cn.json
> +  "tooltip.storagetech.structurecopier.place": "在 %d %d %d 放置了 %s",
原文：
> Place %s at %d %d %d

其中`%s`和`%d`的顺序和目前翻译的顺序不同
格式符不是随便就可以调换位置的，按照目前语序需要加入位置标记：
```suggestion
  "tooltip.storagetech.structurecopier.place": "在 %2$d %3$d %4$d 放置了 %1$s",
```
下一行同样

2021-01-09 04:41 UTC, dovisutu commented on projects/1.16.1/assets/storage-tech/storagetech/lang/zh_cn.json
> +  "tooltip.storagetech.structurecopier.drop": "在 %d %d %d 丢下了 %s",
除去上一行以外，这里的`drop`恐怕不是`丢下`的意思

2021-01-09 12:27 UTC, TUsama commented
这怎么 conflict 的(

2021-01-09 13:52 UTC, rainsillwood commented on projects/1.16.1/assets/storage-tech/storagetech/lang/zh_cn.json
> +  "tooltip.storagetech.structurecopier.drop": "在 %d %d %d 丢下了 %s",
这里的drop是类似玩家的q键，以掉落物形式输出。用掉落？抛出？

2021-01-09 15:31 UTC, GreyElaina commented
@TUsama 发生啥事

2021-01-09 16:36 UTC, TUsama commented
> @TUsama 发生啥事

没啥事啊

2021-01-10 11:33 UTC, 1478599553 commented on projects/1.16.1/assets/storage-tech/storagetech/lang/zh_cn.json
> +  "item.storagetech.400k_energy_storage_part": "100k 能量存储元件",
此处应为400K

2021-01-10 11:33 UTC, 1478599553 commented on projects/1.16.1/assets/storage-tech/storagetech/lang/zh_cn.json
> +  "item.storagetech.400k_energy_storage_part": "100k 能量存储元件",
第8行

2021-01-10 11:40 UTC, 1478599553 commented on projects/1.16.1/assets/storage-tech/storagetech/lang/zh_cn.json
> +  "info.storagetech.chemicalgrid.l1": "左击放入，右键取出。",
“right click”应为“右击”，“右键”是名词“鼠标右边的按键”

2021-01-10 13:10 UTC, 1478599553 commented on projects/1.16.1/assets/storage-tech/storagetech/lang/zh_cn.json
> +  "block.storagetech.poefurnace": "集成电炉",
建议改为“POE磁盘驱动器”
后面的也把“能量”改为“POE”吧
因为POE不能断然理解为能量，保留原文

2021-01-16 13:39 UTC, dovisutu approved these changes

2021-01-16 13:41 UTC, merged