[NR][1.16] 深暗之园丨The Undergarden
CFPAOrg/Minecraft-Mod-Language-Package pull request #937
Opened 2021-01-24 15:43 UTC by WuzgXY-GitHub

- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：CC BY-NC-SA 4.0

2021-01-24 15:45 UTC, WuzgXY-GitHub commented
@TUsama 来帮忙 review 吧 ..(:зゝ∠)..

2021-01-25 01:35 UTC, TUsama requested changes

2021-01-25 01:35 UTC, TUsama commented on projects/1.16.1/assets/the-undergarden/undergarden/lang/zh_cn.json
> +    "advancement.otherside_root.title": "痴狂之域",
你是把desc和title故意倒转过来了吗？

2021-01-25 01:35 UTC, TUsama commented on projects/1.16.1/assets/the-undergarden/undergarden/lang/zh_cn.json
> +    "advancement.shard_torch.title": "病区设备",
```suggestion
    "advancement.shard_torch.title": "防卫器具",
```

2021-01-25 01:35 UTC, TUsama commented on projects/1.16.1/assets/the-undergarden/undergarden/lang/zh_cn.json
> +    "advancement.slay_all_rotspawn.title": "腐衰克星",
bane 如果和原版统一，那得是“xx杀手”。

2021-01-25 01:35 UTC, TUsama commented on projects/1.16.1/assets/the-undergarden/undergarden/lang/zh_cn.json
> +    "advancement.slay_scintling.desc": "你杀死了一个无辜的微光蚙蜒。你个怪物……",
```suggestion
    "advancement.slay_scintling.desc": "你杀死了一个无辜的微光蚙蜒。真是毫无人性……",
```
你个怪物总觉的像是在夸一个人力量很强。

2021-01-25 01:35 UTC, TUsama commented on projects/1.16.1/assets/the-undergarden/undergarden/lang/zh_cn.json
> +    "advancement.slay_scintling.title": "可怕的人",
或许可以改一个更好的，可怕不等于没有同情心。

2021-01-25 01:35 UTC, TUsama commented on projects/1.16.1/assets/the-undergarden/undergarden/lang/zh_cn.json
> +    "advancement.summon_minion.title": "建造一个哨兵",
```suggestion
    "advancement.summon_minion.title": "哨卫初立",
```

2021-01-25 01:40 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/the-undergarden/undergarden/lang/zh_cn.json
> +    "advancement.otherside_root.title": "痴狂之域",
是的，因为异面才是那个世界的名字，我觉得应该把精准的描述放在 desc 里

2021-01-25 01:41 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/the-undergarden/undergarden/lang/zh_cn.json
> +    "advancement.slay_scintling.desc": "你杀死了一个无辜的微光蚙蜒。你个怪物……",
我完全不认为会有人这么认为

2021-01-25 01:42 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/the-undergarden/undergarden/lang/zh_cn.json
> +    "advancement.slay_all_rotspawn.title": "腐衰克星",
？绝了，我是想到魔戒模组的「克星」一词才这么翻的

2021-01-25 01:42 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/the-undergarden/undergarden/lang/zh_cn.json
> +    "advancement.slay_all_rotspawn.title": "腐衰克星",
？绝了，我是想到魔戒模组的「克星」一词才这么翻的

2021-01-25 01:42 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/the-undergarden/undergarden/lang/zh_cn.json
> +    "advancement.slay_scintling.desc": "你杀死了一个无辜的微光蚙蜒。你个怪物……",
我完全不认为会有人这么认为

2021-01-25 01:43 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/the-undergarden/undergarden/lang/zh_cn.json
> +    "advancement.slay_all_rotspawn.title": "腐衰克星",
```suggestion
    "advancement.slay_all_rotspawn.title": "腐衰杀手",
```

2021-01-26 00:11 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/the-undergarden/undergarden/lang/zh_cn.json
> +    "advancement.slay_scintling.title": "可怕的人",
```suggestion
    "advancement.slay_scintling.title": "灾难般的人",
```

2021-01-26 00:11 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/the-undergarden/undergarden/lang/zh_cn.json
> +    "advancement.summon_minion.title": "建造一个哨兵",
我觉得有点雅过头以至丧失本意了

2021-01-26 06:23 UTC, LucunJi commented on projects/1.16.1/assets/the-undergarden/undergarden/lang/zh_cn.json
> +    "advancement.slay_scintling.title": "可怕的人",
terrible 感觉偏口语一点，所以改成“坏蛋”（？

2021-01-26 06:25 UTC, LucunJi commented on projects/1.16.1/assets/the-undergarden/undergarden/lang/zh_cn.json
> +    "advancement.summon_minion.title": "建造一个哨兵",
如果要原文

> Buildin' a Sentry

的非正式感的话，“造个哨兵”这样更简短的翻译会更好？

2021-01-26 08:45 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/the-undergarden/undergarden/lang/zh_cn.json
> +    "advancement.summon_minion.title": "建造一个哨兵",
> 如果要原文
> 
> 
> 
> > Buildin' a Sentry
> 
> 
> 
> 的非正式感的话，“造个哨兵”这样更简短的翻译会更好？

确实，我当时还在想如何翻译这个 in'，感谢帮助

2021-01-26 08:45 UTC, WuzgXY-GitHub commented on projects/1.16.1/assets/the-undergarden/undergarden/lang/zh_cn.json
> +    "advancement.summon_minion.title": "建造一个哨兵",
```suggestion
    "advancement.slay_scintling.title": "造个哨兵",
```

2021-01-26 11:22 UTC, TUsama approved these changes

2021-01-31 03:06 UTC, merged