先进科技翻译，交错次元3.7.2版本汉化更新
CFPAOrg/Minecraft-Mod-Language-Package pull request #939
Opened 2021-01-25 06:58 UTC by lunareclipse-64

- [ ] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [ ] 我已标记PR以便审查（见`CONTRIBUTING.md`）
- [ ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是: `projects/1.12.2/assets/curseforge 域名/模组资源 id/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是: `projects/1.16.1/assets/curseforge 域名/模组资源 id/lang/zh_cn.json`
- [ ] 我已确认语言文件名大小写正确，所有的语言文件全为小写；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-01-26 11:14 UTC, WuzgXY-GitHub approved these changes

2021-01-26 11:14 UTC, WuzgXY-GitHub commented on projects/1.12.2/assets/emergingtechnology/lang/zh_cn.lang
> +info.emergingtechnology.growth.required=每个周期提供%s的增长率；
|Feedback Priority|
|---|
|🌫 Dust / Non-blocking, “take it or leave it”|

```suggestion
info.emergingtechnology.growth.required=每个周期提供%s的增长率。
```

2021-01-26 11:32 UTC, TUsama requested changes
大问题不多，可商榷的挺多。

2021-01-26 11:32 UTC, TUsama commented on projects/1.12.2/assets/angry-pixel-the-betweenlands-mod/thebetweenlands/lang/zh_cn.lang
> +tooltip.bl.simulacrum.effect.sanctuary=荫蔽
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

是荫蔽还是庇佑（

2021-01-26 11:32 UTC, TUsama commented on projects/1.12.2/assets/angry-pixel-the-betweenlands-mod/thebetweenlands/lang/zh_cn.lang
> +chat.simulacrum.blessed=你感觉自己受到了保佑
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

```suggestion
chat.simulacrum.blessed=你感觉自己受到了护佑
```

2021-01-26 11:32 UTC, TUsama commented on projects/1.12.2/assets/angry-pixel-the-betweenlands-mod/thebetweenlands/lang/zh_cn.lang
> +advancements.thebetweenlands.adventurer.queen_of_the_hill.title=落草为寇
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

最终怎么要这个了，绝。

2021-01-26 11:32 UTC, TUsama commented on projects/1.12.2/assets/angry-pixel-the-betweenlands-mod/thebetweenlands/lang/zh_cn.lang
> +advancements.thebetweenlands.survivalist.hashtag_blessed.title=#护佑
|Feedback Priority|
|---|
|🌫 Dust / Non-blocking, “take it or leave it”|

这个#是格式吗

2021-01-26 11:32 UTC, TUsama commented on projects/1.12.2/assets/emergingtechnology/lang/zh_cn.lang
> +item.emergingtechnology.fabricator.name=3D打印机
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

可以考虑加个空格。

2021-01-26 11:32 UTC, TUsama commented on projects/1.12.2/assets/emergingtechnology/lang/zh_cn.lang
> +item.emergingtechnology.machinecase.name=基本机壳
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

基本还是基础？

2021-01-26 12:12 UTC, lunareclipse-64 commented on projects/1.12.2/assets/angry-pixel-the-betweenlands-mod/thebetweenlands/lang/zh_cn.lang
> +advancements.thebetweenlands.survivalist.hashtag_blessed.title=#护佑
原文如此，hashtag_blessed

2021-01-26 12:19 UTC, lunareclipse-64 commented on projects/1.12.2/assets/angry-pixel-the-betweenlands-mod/thebetweenlands/lang/zh_cn.lang
> +tooltip.bl.simulacrum.effect.sanctuary=荫蔽
后文有护佑了，我把这个改成荫庇吧

2021-01-26 12:21 UTC, lunareclipse-64 commented on projects/1.12.2/assets/emergingtechnology/lang/zh_cn.lang
> +item.emergingtechnology.machinecase.name=基本机壳
已修改

2021-01-26 12:21 UTC, TUsama commented on projects/1.12.2/assets/angry-pixel-the-betweenlands-mod/thebetweenlands/lang/zh_cn.lang
> +tooltip.bl.simulacrum.effect.sanctuary=荫蔽
主要是荫蔽没有保护的意思。

> 【释义】（枝叶）遮蔽；隐蔽。

2021-01-26 12:29 UTC, TUsama approved these changes

2021-01-27 02:11 UTC, TUsama approved these changes

2021-02-01 04:09 UTC, merged