[NR] 1.16 - Water Strainer
CFPAOrg/Minecraft-Mod-Language-Package pull request #944
Opened 2021-01-27 04:00 UTC by Peanuuutz

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [x] 我已标记PR以便审查（见`CONTRIBUTING.md`）
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是: `projects/1.12.2/assets/curseforge 域名/模组资源 id/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是: `projects/1.16.1/assets/curseforge 域名/模组资源 id/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件全为小写；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)
---
那个 Worm Bin 可以再改。

2021-01-27 09:28 UTC, TUsama requested changes

2021-01-27 09:28 UTC, TUsama commented on projects/1.16.1/assets/water-strainer/waterstrainer/lang/zh_cn.json
> +	"item.waterstrainer.garden_trowel": "园林铲",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

```suggestion
	"item.waterstrainer.garden_trowel": "园艺铲",
```

2021-01-27 09:28 UTC, TUsama commented on projects/1.16.1/assets/water-strainer/waterstrainer/lang/zh_cn.json
> +	"block.waterstrainer.worm_bin": "生饵桶",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

这个“生”从何而来？

2021-01-27 09:28 UTC, TUsama commented on projects/1.16.1/assets/water-strainer/waterstrainer/lang/zh_cn.json
> +	"itemGroup.waterstrainer.main": "Water Strainer",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

在模组名字比较好翻译的时候，可以考虑将其翻译。

2021-01-27 09:28 UTC, TUsama commented on projects/1.16.1/assets/water-strainer/waterstrainer/lang/zh_cn.json
> +	"item.waterstrainer.strainer_survivalist_solid": "固态生存者滤网",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

这个“solid”指的是硬度吗？如果是硬度的话，那显然不能翻译为固态，而为“坚硬”。

2021-01-27 11:13 UTC, Peanuuutz commented on projects/1.16.1/assets/water-strainer/waterstrainer/lang/zh_cn.json
> +	"item.waterstrainer.strainer_survivalist_solid": "固态生存者滤网",
这个是沿用的 1.12.2 的译名，我可以改成“硬化”

2021-01-27 11:18 UTC, Peanuuutz commented on projects/1.16.1/assets/water-strainer/waterstrainer/lang/zh_cn.json
> +	"block.waterstrainer.worm_bin": "生饵桶",
根据它的作用取“生成”之意。如果直译成“鱼饵桶”“蚯蚓桶”，一可能会与“鱼饵罐”混淆，二也看不明白有什么作用。
<sub>（想不出其他主意了）</sub>

2021-01-28 08:53 UTC, ChromaPIE commented on projects/1.16.1/assets/water-strainer/waterstrainer/lang/zh_cn.json
> +	"block.waterstrainer.worm_bin": "生饵桶",
**产饵桶**呢？“生”除了generate、produce，还可以歧义成“raw”。

2021-01-28 09:25 UTC, Peanuuutz commented on projects/1.16.1/assets/water-strainer/waterstrainer/lang/zh_cn.json
> +	"block.waterstrainer.worm_bin": "生饵桶",
可的

2021-01-31 03:07 UTC, TUsama approved these changes

2021-02-01 04:15 UTC, TUsama commented
可了

2021-02-06 11:32 UTC, merged