[W,R]1.16 若干mod汉化
CFPAOrg/Minecraft-Mod-Language-Package pull request #945
Opened 2021-01-27 11:53 UTC by zorc

mod清单：
betterendforge-完全汉化+润色
biomesoplenty-完全汉化+润色
chiselsandbits-部分汉化，长文本未汉化个人不打算补完
extlights-完全汉化+润色
jousting-完全汉化+润色
mcw全家桶-汉化补完+润色
morered-完全汉化+润色
simplefarming-修改山药为紫薯
vampiresneedumbrellas-完全汉化+润色
vampirism-完全汉化，长文本有一半是机翻未润色（好过没有）个人不打算补完
vampirismguide-完全汉化，长文本有一半是机翻未润色（好过没有）个人不打算补完

- [ x ] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [ x ] 我已标记PR以便审查（见`CONTRIBUTING.md`）
- [ x ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是: `projects/1.12.2/assets/curseforge 域名/模组资源 id/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是: `projects/1.16.1/assets/curseforge 域名/模组资源 id/lang/zh_cn.json`
- [ x ] 我已确认语言文件名大小写正确，所有的语言文件全为小写；
- [ x ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-01-29 07:18 UTC, TUsama commented on projects/1.16.1/assets/biomes-o-plenty/biomesoplenty/lang/zh_cn.json
>  {
由于项目连续性问题，麻烦请移除 BOP 项目。

2021-01-29 07:23 UTC, TUsama requested changes

2021-01-29 07:23 UTC, TUsama commented on projects/1.16.1/assets/chisels-bits/chiselsandbits/lang/zh_cn.json
> +
由于项目连续性问题，麻烦请移除 CAB 项目。

2021-01-29 07:23 UTC, TUsama commented on projects/1.16.1/assets/extended-lights-mod/extlights/lang/zh_cn.json
> +  "item.extlights.glowstone_bulb": "萤石灯泡",
```suggestion
  "item.extlights.glowstone_bulb": "荧石灯泡",
```

2021-01-29 07:23 UTC, TUsama commented on projects/1.16.1/assets/extended-lights-mod/extlights/lang/zh_cn.json
> +  "block.extlights.light_mini_jack_happy": "迷你Jack灯-快乐",
Jack o'Lantern 南瓜灯

2021-01-29 07:23 UTC, TUsama commented on projects/1.16.1/assets/vampirism-become-a-vampire/vampirism/lang/zh_cn.json
> +{
本组织不接收机翻内容，你可以考虑删除机翻内容或删除 吸血鬼 这个项目。

2021-01-29 07:23 UTC, TUsama commented on projects/1.16.1/assets/vampirism-become-a-vampire/vampirismguide/lang/zh_cn.json
> +{
本项目不接收机翻内容，你可以考虑删除机翻内容或删除 吸血鬼 这个项目。

2021-02-01 04:16 UTC, TUsama commented
或许可了，但最好还是来几个再看看。

2021-02-01 07:36 UTC, TUsama commented on projects/1.16.1/assets/betterend-forge-port/betterendforge/lang/zh_cn.json
> +	"block.betterendforge.flavolite": "香料石",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

问一下，这个香料你是从哪查证来的。

2021-02-03 13:36 UTC, zorc commented on projects/1.16.1/assets/betterend-forge-port/betterendforge/lang/zh_cn.json
> +	"block.betterendforge.flavolite": "香料石",
直译为黄铁矿，但是此方块看上去并不是一种矿物，也不具有矿物性质，所以之前我参考该mod的fabric上一版翻译为香料石，刚才查看fabric版新翻译为苍黄石，我稍候修改为一致

2021-02-03 14:11 UTC, TUsama commented on projects/1.16.1/assets/betterend-forge-port/betterendforge/lang/zh_cn.json
> +	"block.betterendforge.flavolite": "香料石",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

问一下，这个香料你是从哪查证来的。

2021-02-03 14:12 UTC, TUsama commented on projects/1.16.1/assets/betterend-forge-port/betterendforge/lang/zh_cn.json
> +	"block.betterendforge.flavolite": "香料石",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

问一下，这个香料你是从哪查证来的。

2021-02-03 14:13 UTC, TUsama commented
还请检查一下其它的名词是否有改动。苍黄石为1.12.2的翻译，可以考虑将该mod内的名词都替换为1.12.2的版本。

2021-02-04 11:56 UTC, TUsama commented
我突然意识到你把库里原来的NOP和CAB对的文件都给删掉了。。。还请将原先的文件还原回来。

2021-02-06 01:57 UTC, TUsama approved these changes

2021-02-07 13:48 UTC, merged

2021-02-07 15:03 UTC, dovisutu commented
emm...
请重新再投一遍。这里的翻译有颇多问题；刚才的合并是误合并。