Create zh_cn.json
CFPAOrg/Minecraft-Mod-Language-Package pull request #948
Opened 2021-01-29 13:16 UTC by Hokorizero

UAD 翻译

- [ ] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [ ] 我已标记PR以便审查（见`CONTRIBUTING.md`）
- [ ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是: `projects/1.12.2/assets/curseforge 域名/模组资源 id/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是: `projects/1.16.1/assets/curseforge 域名/模组资源 id/lang/zh_cn.json`
- [ ] 我已确认语言文件名大小写正确，所有的语言文件全为小写；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-01-29 14:20 UTC, Hokorizero commented
@TUsama  @WuzgXY-GitHub

2021-01-30 04:01 UTC, TUsama approved these changes

2021-01-30 09:38 UTC, WuzgXY-GitHub requested changes
~~有一些已被私信的小改动需要被作出~~
已经私信了一些小问题，可以看着改

2021-02-01 04:07 UTC, baka-gourd commented
所以能merge了吗

2021-02-01 04:08 UTC, TUsama commented
可

2021-02-01 05:59 UTC, WuzgXY-GitHub commented
不可，还没改我让他改的，连 commit 都无

2021-02-01 13:06 UTC, Hokorizero commented
Done

2021-02-07 12:51 UTC, dovisutu commented
> 不可，还没改我让他改的，连 commit 都无

现在似乎加了，你在看一下？

2021-02-07 13:34 UTC, WuzgXY-GitHub approved these changes

2021-02-07 13:48 UTC, merged