[NR] 英文版的 README 以及一些提醒
CFPAOrg/Minecraft-Mod-Language-Package pull request #952
Opened 2021-01-31 04:55 UTC by LucunJi

如题，我对自己的英文水平不是很有信心，麻烦 merge 之前检查一下。

另外几点提醒：
- logo 在夜间模式下观感很差。
- 目前应该是支持 1.16.x 版本的，但是 GitHub 和 CurseForge 上面都没有标明。
- README 里的链接没有检查过有没有断链。

2021-01-31 06:45 UTC, Peanuuutz requested changes
OK quite a lot.

2021-01-31 06:45 UTC, Peanuuutz commented on README-en.md
> +Before translating, you should first learn important things from here: [*Regulations and Guidelines for Simplified Chinese Translation of Minecraft Mods*](https://github.com/Meow-J/Mod-Translation-St
```suggestion
Before you start, check the important tips from us here: [*Regulations and Guidelines for Simplified Chinese Translation of Minecraft Mods*](https://github.com/Meow-J/Mod-Translation-Styleguide/blob/master/README.md).
```

2021-01-31 06:45 UTC, Peanuuutz commented on README-en.md
> +This work is licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/)([Simplified Chinese](https://creati
```suggestion
This project is under the license of [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/)([Simplified Chinese](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh)). Detail can be found [here](./LICENSE).<br>
```

2021-01-31 06:45 UTC, Peanuuutz commented on README-en.md
> +To apply the localization, you need only to load this pack like any other resource pack. In case of some issues, restarting the game after loading  is recommended.
```suggestion
Download the *released* version on CurseForge or [here](https://minecraft.curseforge.com/projects/simplified-chinese-localization-resource-package) portal.<br>
Download the *snapshot* version [here](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/releases/latest) portal.<br>
To apply, simply load this pack like any other resource pack. In case of some issues, restarting Minecraft after loading  is recommended.
```

2021-01-31 06:45 UTC, Peanuuutz commented on README-en.md
> +There are some detailed publicity on [the MCBBS page](http://www.mcbbs.net/thread-774087-1-1.html).
```suggestion
We have been propagating this project on [the MCBBS page](http://www.mcbbs.net/thread-774087-1-1.html).
```

2021-01-31 06:45 UTC, Peanuuutz commented on README-en.md
> +Currently, according to the popularity on CurseForge, we have chosen the 1.12.2 version and are tracking over 1000 mods. If you want any additional mod to be translated, you can suggest your ideas th
```suggestion
Currently, according to the popularity on CurseForge, we have chosen Minecraft 1.12.2 for the majority of our work, with over 1000 mods in the project. If you want any other mod to be translated, you can suggest through our [issue tracker](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues), or email us directly.<br>
```

2021-01-31 06:45 UTC, Peanuuutz commented on README-en.md
> +The whole story of this project can be seen in [TartaricAcid's blog post](https://baka943.coding.me/2018/01/03/2018-01-03-AnIntroForWeblate/).
```suggestion
The history of this project can be seen in [TartaricAcid's blog](https://baka943.coding.me/2018/01/03/2018-01-03-AnIntroForWeblate/).
```

2021-01-31 06:45 UTC, Peanuuutz commented on README-en.md
> +**How is it possible for your guys to achieve such a pipelining translating style?**<br>
```suggestion
**How did you guys set up the workflow?**<br>
```

2021-01-31 06:45 UTC, Peanuuutz commented on README-en.md
> +- Get the updates from GitHub automatically when Weblate detects changes in repositories.
```suggestion
- Pull the updates from GitHub to Weblate automatically when detecting changes in the repository.
```

2021-01-31 06:45 UTC, Peanuuutz commented on README-en.md
> +See all the contributors in the [Contributors](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/graphs/contributors) page of this repository.
```suggestion
## Credits

* `phi` for setting up the Weblate server and integration with Google Translate.
* `Summpot` and`Nullpinter` for a better version of the C# web scraper.
* `PeakXing` for making the logo.
* `雪尼`、`FledgeXu`、`asdflj` and others who give suggestions and ideas.
* Pioneers of this project: `Aemande123`，`DYColdWind`，`Snownee`，`yuanjie000`，`forestbat`，`3TUSK`，`SihenZhang`，`MoXiaoFreak`，`gloomy_banana`，`yuanjie000`，`exia00125`，`luckyu19` for early localizations (in no particular order).
* `R_liu`  for the localization of SlashBalde.
* `3TUSK` for [fixing the display of full-width punctuation](./project/assets/minecraft/readme.md) which are embedded in the resource pack.
* Finally, give thanks to every single player who engages in providing and spreading localizations.
See all the contributors in the [Contributors](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/graphs/contributors) page.
```

2021-01-31 13:47 UTC, LucunJi commented on README-en.md
> +It is also fine to submit pull requests to this repository.
"with your translated version" 可以省略？

2021-01-31 13:51 UTC, Peanuuutz commented on README-en.md
> +It is also fine to submit pull requests to this repository.
随便你，我只是**建议**

2021-01-31 13:52 UTC, LucunJi commented on README-en.md
> +- Get the updates from GitHub automatically when Weblate detects changes in repositories.
我的理解是“the repository”指 mod 作者的仓库，所以应该是复数

2021-01-31 13:57 UTC, Peanuuutz commented on README-en.md
> +- Get the updates from GitHub automatically when Weblate detects changes in repositories.
等等，咱们 Weblate 不是拉取的这个库里的资料嘛。

2021-01-31 14:07 UTC, LucunJi commented on README-en.md
> +- Get the updates from GitHub automatically when Weblate detects changes in repositories.
想了下应该是我理解错了，已 commit

2021-02-04 07:57 UTC, LucunJi commented
很尴尬，之前误操作 force push 了一个有英文 readme 之前的版本，现在应该恢复了

2021-02-04 08:00 UTC, Peanuuutz commented
![](https://i.loli.net/2021/02/04/D5rVaZnGf7sE4vK.jpg)

2021-02-05 02:16 UTC, WuzgXY-GitHub approved these changes

2021-02-05 02:16 UTC, WuzgXY-GitHub commented on README-en.md
> +* `3TUSK` for [fixing the display of full-width punctuation](./project/assets/minecraft/readme.md). This is originally involved in the pack.
|Feedback Priority|
|---|
|🌫 Dust / Non-blocking, “take it or leave it”|

```suggestion
* `3TUSK` for [fixing the display of full-width punctuation](./project/assets/minecraft/readme.md). This is originally involved in the pack.
* `LucunJi` for the internationalization of this readme file.
```

2021-03-24 12:01 UTC, merged