[M]新增 Sophisticated Backpacks
CFPAOrg/Minecraft-Mod-Language-Package pull request #954
Opened 2021-02-04 08:11 UTC by LucunJi

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [x] 我已标记PR以便审查（见`CONTRIBUTING.md`）
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是: `projects/1.12.2/assets/curseforge 域名/模组资源 id/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是: `projects/1.16.1/assets/curseforge 域名/模组资源 id/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件全为小写；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

---

我只是对 @PigeonNian 的汉化文件进行修订并帮助提交，理论上应该可以直接合并。
另外，“俄罗斯套娃”是对 inception （盗梦空间）的以梗翻梗。

2021-02-05 02:17 UTC, TUsama requested changes

2021-02-05 02:17 UTC, TUsama commented on projects/1.16.1/assets/sophisticatedbackpacks/sophisticatedbackpacks/lang/zh_cn.json
> +    "item.sophisticatedbackpacks.void_upgrade.tooltip": "清空过滤器中选定的项目",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

item 翻译成了 项目，下方同理。

2021-02-05 02:17 UTC, TUsama commented on projects/1.16.1/assets/sophisticatedbackpacks/sophisticatedbackpacks/lang/zh_cn.json
> +    "item.sophisticatedbackpacks.restock_upgrade.tooltip": "手持背包 Shift 右击容器从中存入物品",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
    "item.sophisticatedbackpacks.restock_upgrade.tooltip": "手持背包 Shift 右击容器可补充背包内物品",
```

2021-02-05 02:17 UTC, TUsama commented on projects/1.16.1/assets/sophisticatedbackpacks/sophisticatedbackpacks/lang/zh_cn.json
> +    "item.sophisticatedbackpacks.advanced_restock_upgrade.tooltip": "手持背包 Shift 右击容器从中取出物品\n有更多的筛选项",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

你这上下完全不一致。

2021-02-05 02:17 UTC, TUsama commented on projects/1.16.1/assets/sophisticatedbackpacks/sophisticatedbackpacks/lang/zh_cn.json
> +    "item.sophisticatedbackpacks.deposit_upgrade.tooltip": "手持背包 Shift 右击容器向内放置物品",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

参考我的上述表述，自己把这个再改改。

2021-02-05 02:17 UTC, TUsama commented on projects/1.16.1/assets/sophisticatedbackpacks/sophisticatedbackpacks/lang/zh_cn.json
> +    "item.sophisticatedbackpacks.refill_upgrade.tooltip": "保持补充玩家物品栏中所选物品数量",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
    "item.sophisticatedbackpacks.refill_upgrade.tooltip": "不断地补充玩家物品栏中所选物品的数量",
```

2021-02-05 02:17 UTC, TUsama commented on projects/1.16.1/assets/sophisticatedbackpacks/sophisticatedbackpacks/lang/zh_cn.json
> +    "item.sophisticatedbackpacks.smelting_upgrade.tooltip": "在升级卡插槽中熔炼（不会着火吗）",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

```suggestion
    "item.sophisticatedbackpacks.smelting_upgrade.tooltip": "在升级卡插槽中熔炼",
```

2021-02-05 02:17 UTC, TUsama commented
还好没merge。

2021-02-06 01:27 UTC, dovisutu commented on projects/1.16.1/assets/sophisticatedbackpacks/sophisticatedbackpacks/lang/zh_cn.json
> +    "item.sophisticatedbackpacks.inception_upgrade": "套娃升级",
说实话，这个*套娃*我看着怎么总有一点奇怪的感觉.....
我可能更偏向于*嵌套*升级这样的，虽说作者似乎也在玩梗，但是按照in+-ception的结构解释也可行
或者想一个更好的翻译出来...~？~

2021-02-11 14:20 UTC, LucunJi commented on projects/1.16.1/assets/sophisticatedbackpacks/sophisticatedbackpacks/lang/zh_cn.json
> +    "item.sophisticatedbackpacks.inception_upgrade": "套娃升级",
内嵌升级？

2021-02-11 14:45 UTC, dovisutu commented on projects/1.16.1/assets/sophisticatedbackpacks/sophisticatedbackpacks/lang/zh_cn.json
> +    "item.sophisticatedbackpacks.inception_upgrade": "套娃升级",
我觉得可以

2021-02-13 07:12 UTC, LucunJi commented
改好了， 麻烦再看一下吧@TUsama 
翻译做这么烂还摸鱼的我爬了orz

2021-02-13 08:48 UTC, PigeonNian commented
> [， ]@TUsama]

这个该怪我底子没打好

2021-02-19 03:42 UTC, PigeonNian commented
mod本体已经汉化了（

2021-02-23 01:46 UTC, TUsama approved these changes

2021-02-27 02:38 UTC, dovisutu commented
（...本来说是现在打上merge的，感觉有点不妥~（因为只是大概翻了一下~
等别人打merge标签吧

2021-02-27 02:49 UTC, PigeonNian commented
> （...自控自有自有，多为多，多为多（~前身为~
> 鲁比斯·鲁比斯·鲁比特）。

没必要了 mod已经自带汉化了

2021-02-27 18:40 UTC, LucunJi commented
@baka-gourd 不用标记 obsolete 吧，官方的那个翻译是没有校对的版本

2021-03-03 15:44 UTC, TUsama requested changes
除此之外，应该无较大问题，完全修改过版本与原先版本相比已有了较大改进，可以入库了。

2021-03-03 15:44 UTC, TUsama commented on projects/1.16.1/assets/sophisticatedbackpacks/sophisticatedbackpacks/lang/zh_cn.json
> +    "itemGroup.sophisticatedbackpacks": "复杂背包",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

或为“精巧”更为妥当。

2021-03-03 15:44 UTC, TUsama commented on projects/1.16.1/assets/sophisticatedbackpacks/sophisticatedbackpacks/lang/zh_cn.json
> +    "item.sophisticatedbackpacks.advanced_pickup_upgrade.tooltip": "使背包捡起物品\n有更多的筛选项",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

将“筛选项”改为“过滤选项”，filter业界共识为“过滤”。

2021-03-06 09:21 UTC, merged

2021-03-06 09:21 UTC, baka-gourd commented
问题不大是吧，那先入库好了