[R]更新Crossroads翻译
CFPAOrg/Minecraft-Mod-Language-Package pull request #963
Opened 2021-02-08 02:53 UTC by kappa-maintainer

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [x] 我已标记PR以便审查（见`CONTRIBUTING.md`）
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是: `projects/1.12.2/assets/curseforge 域名/模组资源 id/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是: `projects/1.16.1/assets/curseforge 域名/模组资源 id/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件全为小写；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)
还是原来的译者，只是换ID了
原文更新至最新，改了几个易混淆或让人迷惑的翻译，改了一个错译
流体虚空后来才发现属于bobo物品，个人觉得这个名字是有意为之，就该成了直译

2021-02-10 03:25 UTC, TUsama commented on projects/1.16.1/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +    "book.crossroads_essentials.name": "交错道途与Essentials的指导手册"
```suggestion
    "book.crossroads_essentials.name": "交错道途与 Essentials 的指导手册"
```

2021-02-10 03:26 UTC, TUsama commented on projects/1.16.1/assets/crossroads-mc/crossroads/lang/zh_cn.json
>  	"reagent.anti_densus": "反密素",
上文的“下届石英”改一改。

2021-02-10 03:34 UTC, TUsama commented on projects/1.16.1/assets/crossroads-mc/crossroads/lang/zh_cn.json
>  	"tt.crossroads.steamer.water": "产出：运行时%1$dmB/t蒸馏水",
```suggestion
	"tt.crossroads.steamer.water": "产出：工作时蒸馏水产出速率%1$dmB/t",
```

2021-02-10 03:34 UTC, TUsama commented on projects/1.16.1/assets/crossroads-mc/crossroads/lang/zh_cn.json
>  	"tt.crossroads.steamer.steam": "消耗：运行时%1$dmB/t蒸汽",
```suggestion
	"tt.crossroads.steamer.steam": "消耗：工作时蒸汽消耗速率%1$dmB/t",
```

2021-02-10 03:38 UTC, TUsama commented on projects/1.16.1/assets/crossroads-mc/crossroads/lang/zh_cn.json
>  	"tt.crossroads.spring_gun.quip": "如果发条代替了火药，枪就是这样",
这个是在哪里显示的。

2021-02-10 03:38 UTC, TUsama commented on projects/1.16.1/assets/crossroads-mc/crossroads/lang/zh_cn.json
>  	"tt.crossroads.winding_table.desc": "使用旋转能给特点物品上发条；I：%1$s",
```suggestion
	"tt.crossroads.winding_table.desc": "使用旋转能给特定物品上发条；I：%1$s",
```

2021-02-10 03:46 UTC, TUsama commented on projects/1.16.1/assets/crossroads-mc/crossroads/lang/zh_cn.json
>  	"tt.crossroads.solar_heater.desc": "产出：直接阳光光照下%1$d°C/t",
我不太确定这里可以用“产出”这个词，尤其是当考虑到温度它不是一个可被生产的东西。这里的produce更多的意思是“产生”，你可以再考虑考虑。

还有后半段的改法和下面的那个改法差不多，你自己加一点上去。

2021-02-10 03:48 UTC, TUsama commented on projects/1.16.1/assets/crossroads-mc/crossroads/lang/zh_cn.json
>  	"tt.crossroads.heat_battery.reds": "电路可读取温度",
我想知道这个“可”是怎么来的，还有下文610行的那个也是。

2021-02-10 03:53 UTC, TUsama commented on projects/1.16.1/assets/crossroads-mc/crossroads/lang/zh_cn.json
>  	"tt.crossroads.heat_battery.info": "作为缓存减少温度变化",
```suggestion
	"tt.crossroads.heat_battery.info": "行为类似于缓存，可以减少温度变化",
```
原句一下子塞了三个实义句子成分，所以可以考虑把句子拆分，中文在句子内表述过多实义成分的时候会让阅读者的阅读难度直线上升，所以遇到这种情况可以拆句。比较典型的就是英语句子中的定语部分拆分，一个是定语从句，另一个是非谓语动词做定语，这些定语往往非常长，有时甚至相当复杂，这时候肯定是需要把这些定语拆分出来，单独成一个小句子。

2021-02-10 04:36 UTC, kappa-maintainer commented on projects/1.16.1/assets/crossroads-mc/crossroads/lang/zh_cn.json
>  	"tt.crossroads.spring_gun.quip": "如果发条代替了火药，枪就是这样",
弹簧加压弩的quip

2021-02-10 04:41 UTC, kappa-maintainer commented on projects/1.16.1/assets/crossroads-mc/crossroads/lang/zh_cn.json
>  	"tt.crossroads.heat_battery.reds": "电路可读取温度",
总不能“电路读取温度”，要不改成“可用电路读取温度”

2021-02-10 04:53 UTC, TUsama commented on projects/1.16.1/assets/crossroads-mc/crossroads/lang/zh_cn.json
>  	"tt.crossroads.heat_battery.reds": "电路可读取温度",
可。

2021-02-10 12:35 UTC, kappa-maintainer commented
模组名要改成道途交错吗，我个人觉得两个都可以

2021-02-10 12:54 UTC, TUsama commented
都可，取决于你。

2021-02-11 07:31 UTC, kappa-maintainer commented
改了一点

2021-02-19 04:54 UTC, baka-gourd requested changes

2021-02-19 04:54 UTC, baka-gourd commented on projects/1.16.1/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"itemGroup.heat_cable": "交错道途 | 热导管",
```suggestion
	"itemGroup.heat_cable": "交错道途丨热导管",
```
使用丨，并且两边不用空格，下面同上

2021-02-19 04:54 UTC, baka-gourd commented on projects/1.16.1/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"tt.crossroads.cheat_heat.cold": "Shift 右击移除%1$d °C",
```suggestion
	"tt.crossroads.cheat_heat.cold": "使用 Shift 右击移除%1$d °C",
```
其实最好看一下是shift还是潜行

2021-02-19 04:54 UTC, baka-gourd commented on projects/1.16.1/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"tt.crossroads.cheat_rotary.back": "Shift 右击移除 %1$d J",
同上

2021-02-19 04:54 UTC, baka-gourd commented on projects/1.16.1/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"tt.crossroads.wind_turbine.env": "需要能看见天空和 5x5 的空间",
```suggestion
	"tt.crossroads.wind_turbine.env": "需要露天的 5x5 的空间",
```

2021-02-19 04:54 UTC, baka-gourd commented on projects/1.16.1/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"tt.crossroads.quartz_stabilizer.wrench": "可手持扳手 shift 右击配置输出功率",
```suggestion
	"tt.crossroads.quartz_stabilizer.wrench": "可使用扳手 shift 右击配置输出功率",
```
同上检查是shift还是潜行

2021-02-19 10:12 UTC, kappa-maintainer commented on projects/1.16.1/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"tt.crossroads.cheat_heat.cold": "Shift 右击移除%1$d °C",
全部都是原文怎么写就怎么翻，书里有写sneak的都翻成潜行了

2021-02-19 10:12 UTC, kappa-maintainer commented on projects/1.16.1/assets/crossroads-mc/crossroads/lang/zh_cn.json
> +	"tt.crossroads.wind_turbine.env": "需要能看见天空和 5x5 的空间",
当时瞬间找不到词，感谢

2021-02-19 10:22 UTC, kappa-maintainer commented
en_us.json里只有两处sneak，都翻成潜行了

2021-02-23 01:44 UTC, TUsama approved these changes

2021-02-23 03:29 UTC, baka-gourd approved these changes

2021-02-23 03:29 UTC, merged