1.16
CFPAOrg/Minecraft-Mod-Language-Package pull request #972
Opened 2021-02-11 14:52 UTC by fansi2020

- [ √] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [√ ] 我已标记PR以便审查（见`CONTRIBUTING.md`）
- [√ ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是: `projects/1.12.2/assets/curseforge 域名/模组资源 id/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是: `projects/1.16.1/assets/curseforge 域名/模组资源 id/lang/zh_cn.json`
- [ √] 我已确认语言文件名大小写正确，所有的语言文件全为小写；
- [√ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-02-12 05:28 UTC, TUsama commented
看一看https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/CONTRIBUTING.md ，前缀不是这么用的（

2021-02-12 05:34 UTC, TUsama requested changes

2021-02-12 05:34 UTC, TUsama commented on projects/1.16.1/assets/a-v-a-in-minecraft/ava/lang/zh_cn.json
> +    "ava.gui.description.standard_armour_3": "盔甲強度",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
    "ava.gui.description.standard_armour_3": "盔甲强度",
```

2021-02-12 05:34 UTC, TUsama commented on projects/1.16.1/assets/a-v-a-in-minecraft/ava/lang/zh_cn.json
> +    "death.attack.ava.killed.weapon": "%1$s 被 %3$s 杀了",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

这里直接从1跳到了3，可疑查证一下吗？看key似乎指的是武器，所以这里的%3$s可能是武器。

2021-02-12 05:34 UTC, TUsama commented on projects/1.16.1/assets/a-v-a-in-minecraft/ava/lang/zh_cn.json
> +    "ava.uav_captured": "你被敌人的UAV发現了!",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
    "ava.uav_captured": "你被敌人的UAV发现了!",
```
你是不是用的繁体转过来的啊，是的话请自检一边繁体字并全部替换。

2021-02-12 05:34 UTC, TUsama commented on projects/1.16.1/assets/a-v-a-in-minecraft/ava/lang/zh_cn.json
> +    "block.ava.health_boost_block": "生命提升块",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

疑似机翻。

2021-02-12 05:34 UTC, TUsama commented on projects/1.16.1/assets/a-v-a-in-minecraft/ava/lang/zh_cn.json
> +    "item.ava.m116a1": "M116A1震!撼!弹!",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

中文符号。

2021-02-12 08:30 UTC, fansi2020 commented on projects/1.16.1/assets/a-v-a-in-minecraft/ava/lang/zh_cn.json
> +    "death.attack.ava.killed.weapon": "%1$s 被 %3$s 杀了",
有道理

2021-02-12 08:36 UTC, fansi2020 commented on projects/1.16.1/assets/a-v-a-in-minecraft/ava/lang/zh_cn.json
> +    "block.ava.health_boost_block": "生命提升块",
那就是个方块 我再看看吧

2021-02-12 16:11 UTC, fansi2020 commented on projects/1.16.1/assets/a-v-a-in-minecraft/ava/lang/zh_cn.json
> +    "block.ava.health_boost_block": "生命提升块",
这个是手持后能增加能力上限的 原版模组英语就是 "Attack Damage Boost Block""Health Boost Block"
你觉得怎么翻译

2021-02-13 00:38 UTC, TUsama commented on projects/1.16.1/assets/a-v-a-in-minecraft/ava/lang/zh_cn.json
> +    "block.ava.health_boost_block": "生命提升块",
主要是block，一般来说都是翻译成“方块”，只有机器会翻译成“块”。
当然也有例外，煤炭块就是例外之一，但是这里的例外是因为现实生活中确有这种说法，如无这种xx块的惯有说法，block翻译成方块则更令人明晰。

2021-02-15 14:58 UTC, fansi2020 commented on projects/1.16.1/assets/a-v-a-in-minecraft/ava/lang/zh_cn.json
> +    "death.attack.ava.killed.weapon": "%1$s 被 %3$s 杀了",
通过游戏里用武器自杀 在看这个【"death.attack.ava.bullet.weapon": "%1$s 被 %2$s 用 %3$s 射杀了"】, %3$s确实是武器。这样问题应该解决的差不多了

2021-02-23 01:47 UTC, TUsama approved these changes
或许可了？那些枪的我不是很懂，我只把我能看得懂的看了。

2021-02-27 04:18 UTC, merged