Arkif's Hoverboard Mod的汉化
CFPAOrg/Minecraft-Mod-Language-Package pull request #973
Opened 2021-02-12 11:10 UTC by xiaomipe

- [ ] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [ ] 我已标记PR以便审查（见`CONTRIBUTING.md`）
- [ ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是: `projects/1.12.2/assets/curseforge 域名/模组资源 id/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是: `projects/1.16.1/assets/curseforge 域名/模组资源 id/lang/zh_cn.json`
- [ ] 我已确认语言文件名大小写正确，所有的语言文件全为小写；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-02-12 11:30 UTC, dovisutu reviewed
有点问题。
值得注意的是，翻译从来不是把专有名词翻译对就完事的。把这些翻译对了自然很好；但是这并不是一切。

个人的建议：在真正熟悉之前不要标[M]。或者说。永远不要标[M]：
因为个体永远存在偏差。

当然，如果下面的 review comment 之中有我所不知道的原因，当我没说。

2021-02-12 11:30 UTC, dovisutu commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/en_us.lang
> +< en_GB.lang - English localisation file for Arkif's Hoverboard Mod >
等等...这个确定是合法的注释吗......

2021-02-12 11:30 UTC, dovisutu commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +key.categories.hoverboard=Arkif的Hoverboard Mod操作
如果要翻译 mod 名，请保持上下文（亦见 Line 3）一致。

2021-02-12 11:30 UTC, dovisutu commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +key.hoverboard.down=下降悬浮滑板
下降不是不及物吗......这样读起来比较怪
下面的 Line 10 处同理

2021-02-12 11:30 UTC, dovisutu commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +tile.melt_spinner.name=熔融纺丝器
这个名字怎么总是给我一种“这是通过纺丝器在高温下熔融形成的流体”的感觉......
当然如果这是专有名词，当我没说

2021-02-12 11:30 UTC, dovisutu commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +container.hoverboard.options.rockets =发射％d火箭
> 发射％d火箭 
请将全角百分号改为半角百分号。

2021-02-12 11:30 UTC, dovisutu commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +container.hoverboard.information.status.boost=水压: %s
这个 boost...真的是水压吗
如果真的是，当我没说

2021-02-12 11:30 UTC, dovisutu commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +info.hoverboardmod.item.owner=所有者为： %s.
全角标点之后不要再打空格。
如果是排版问题（注意在打了全角标点修复后仍存在）当我没说。
```suggestion
info.hoverboardmod.item.owner=所有者为：%s.
```

2021-02-12 11:30 UTC, dovisutu commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +subtitles.entity.hoverboard.engage=悬浮滑板合同
合同？不会吧
注意这里是 Minecraft 添加字幕时的文本。尽量与原版的格式靠齐。

2021-02-12 11:35 UTC, dovisutu commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +tile.melt_spinner.name=熔融纺丝器
确实是专有名词...resolve了

2021-02-12 11:55 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/en_us.lang
> +< en_GB.lang - English localisation file for Arkif's Hoverboard Mod >
即使是也得删掉吧（

2021-02-12 11:56 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +subtitles.entity.hoverboard.engage=悬浮滑板合同
原版字幕格式为

> 物品：声音

例如：
> 羊：咩~

2021-02-12 12:03 UTC, dovisutu commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +subtitles.entity.hoverboard.engage=悬浮滑板合同
当然，`声音`也不一定是拟声词，描述动作同样可行
例如：
> 活塞：移动
> 溺尸：投掷三叉戟

2021-02-12 12:04 UTC, dovisutu commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +subtitles.entity.hoverboard.engage=悬浮滑板合同
也就是说，这一部分的多数条目看上去是名词结尾实则动词结尾

2021-02-12 12:28 UTC, TUsama requested changes

2021-02-12 12:28 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +key.hoverboard.inventory=悬浮滑板存储
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

如果此处指的是“打开悬浮滑板的储存界面”，那么此处的“inventory”就得翻译为“物品栏”。这个是**原版词汇**。

2021-02-12 12:28 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +key.hoverboard.down=下降悬浮滑板
附议，此处应为“悬浮滑板下降”。

2021-02-12 12:28 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +item.rocket_ammunition.name=捆绑火箭
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

怎么把“bundle”翻译为”捆绑“的？

2021-02-12 12:28 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +item.upgrade_storage.name=悬浮滑板升级（存储）
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

此处同理。

2021-02-12 12:28 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +container.energy=%1$,d / %2$,d RF
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

这个 ,d 是啥。

2021-02-12 12:28 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +container.hoverboardDocker.status.unloading.short=正在卸载 %s's 的悬浮滑板
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

漏删除 's 。

2021-02-12 12:28 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +container.hoverboardDocker.status.unloading.medium=正在卸载 %s的悬浮滑板
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

占位符前后的空务必保持一致，要不就都有空格，要不就都没有空格。

2021-02-12 12:28 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +container.hoverboardDocker.unloader=悬浮滑板卸载程序
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

名词统一。

2021-02-12 12:28 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +container.hoverboard.options.owner.storage=仅自己打开库存
|Feedback Priority|
|---|
|🌫 Dust / Non-blocking, “take it or leave it”|

或可改为”私人储存“，如果改，则下面的都要改。

2021-02-12 12:28 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +container.hoverboard.options.owner.pilot=仅自己
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

此处的pilot为啥没了。且此处和下面的那个 No pilot 都有一样的疑问：动物能不能骑上去。

如果动物不可以骑上去，那么这里为”私人驾驶“更为妥当。

2021-02-12 12:28 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +container.hoverboard.options.owner.dock=仅自己停靠
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

station是名词，指的是否是一个停靠站点？如果是的话那么这里翻译成停靠可能是不对的。

2021-02-12 12:28 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +container.hoverboard.information.averages.title=测量平均值
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

原文为”Estimated“，有不精确的意味，这里翻译为”测量“和词义不符。

2021-02-12 12:28 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +container.hoverboard.information.averages.heat=温度增益: %.1f
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

此处的”gain“翻译为”增益“，似有不妥，如果指的是温度增长的速度，那应该用温度”增值“较好。如果指的是温度对速度的增益，那此处尚可。

2021-02-12 12:28 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +container.hoverboard.information.status.heat.hot=过热
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

”hot“，热就是热，到时候作者再整一个”super hot“，再改就麻烦了。

2021-02-12 12:28 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +container.hoverboard.information.status.any.noPilot=没有玩家
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

似为”没有驾驶员“。

因不确定动物是否能乘上去。

2021-02-12 12:28 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +hoverboard.upgrade.cooling=更好的冷却
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

可为”冷却增强“。

2021-02-12 12:28 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +info.hoverboardmod.item.wrench=右键悬浮滑板以将其拾起。
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

请改为”右击“，”右键“为鼠标的一个键位。以下同理。

2021-02-12 12:28 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +info.hoverboardmod.need.wrench=您的背包中需要一个悬浮滑板扳手才能进行维修。
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
info.hoverboardmod.need.wrench=你需要在物品栏中准备一个悬浮滑板扳手才能进行维修。
```

2021-02-12 12:28 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +info.hoverboardmod.aerogel=此物品可以在地牢箱箱子，废弃矿井箱和丛林神殿箱中找到。
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
info.hoverboardmod.aerogel=此物品可以在地牢箱子，废弃矿井箱子和丛林神殿箱子中找到。 
```

2021-02-12 12:40 UTC, 1478599553 commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +info.hoverboardmod.aerogel=此物品可以在地牢箱箱子，废弃矿井箱和丛林神殿箱中找到。
不是要塞？

2021-02-12 13:52 UTC, dovisutu commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +container.energy=%1$,d / %2$,d RF
刚刚查了一下，此处是 Java 格式符中设置 locale-specific 的数位分隔符的标记
> If the ',' ('\u002c') flag is given, then the locale-specific grouping separator is inserted by scanning the integer part of the string from least significant to most significant digits and inserting a separator at intervals defined by the locale's grouping size.

2021-02-12 13:53 UTC, dovisutu commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +container.hoverboard.options.owner.storage=仅自己打开库存
库存可还行......

2021-02-12 13:55 UTC, ChromaPIE commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +key.hoverboard.down=下降悬浮滑板
“悬浮滑板下降”不适合作为键位名。建议是“拉低”（同时需对应拉高）或者“下倾”（同时需对应上倾）

2021-02-12 14:00 UTC, xiaomipe commented
难道不能用库存吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "dovisutu"<notifications@github.com&gt;; 
发送时间: 2021年2月12日(星期五) 晚上9:53
收件人: "CFPAOrg/Minecraft-Mod-Language-Package"<Minecraft-Mod-Language-Package@noreply.github.com&gt;; 
抄送: "初二"<1049576175@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CFPAOrg/Minecraft-Mod-Language-Package] [R]Arkif&#39;s Hoverboard Mod的汉化 (#973)





 
@dovisutu commented on this pull request.
 
 
In projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang:
 &gt; +container.hoverboard.button.options=选项... +container.hoverboard.button.info=信息... +container.hoverboard.hover.power=%1$,d / %2$,d RF +container.hoverboard.hover.rockets=%1$,d / %2$,d Rockets + + + +container.hoverboard.options.title=选项 +container.hoverboard.options.hoverMode=悬停模式 +container.hoverboard.options.caveLight=探照灯 +container.hoverboard.options.collectItems=收集物品 +container.hoverboard.options.shield=护盾 +container.hoverboard.options.miningMode=采矿模式 +container.hoverboard.options.particles=粒子  +container.hoverboard.options.owner.title=所有者选项 +container.hoverboard.options.owner.storage=仅自己打开库存  
库存可还行......
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-02-12 14:02 UTC, dovisutu commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +info.hoverboardmod.aerogel=此物品可以在地牢箱箱子，废弃矿井箱和丛林神殿箱中找到。
**地牢**（`dungeon`）是在主世界生成的带有刷怪笼的7\*5\*7的结构。
**要塞**（`stronghold`）是在主世界生成的带有末地传送门的大型结构，~常被用于刷沙机~。
**下界要塞**（`nether fortress`）是在下界生成的带有烈焰人刷怪笼的大型结构，具有特殊的怪物生成判定。

原文是`dungeon`，所以应该是地牢箱子。

2021-02-13 00:38 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +key.hoverboard.down=下降悬浮滑板
可。

2021-02-13 00:39 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +info.hoverboardmod.aerogel=此物品可以在地牢箱箱子，废弃矿井箱和丛林神殿箱中找到。
猫猫擦脸.jpg

2021-02-13 00:39 UTC, TUsama commented
不可，除非你能把原版MC的词汇给改了。

2021-02-13 00:40 UTC, TUsama commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +container.hoverboard.options.owner.storage=仅自己打开库存
敏感词汇，凡是出现这个要不就是机翻，要不就是不熟悉mc原版词汇，绝大多数情况下两者兼具。

2021-02-13 01:27 UTC, 1478599553 commented on projects/1.12.2/assets/arkifs-hoverboard-mod/hoverboardmod/lang/zh_cn.lang
> +info.hoverboardmod.aerogel=此物品可以在地牢箱箱子，废弃矿井箱和丛林神殿箱中找到。
那没事了，我弄错了

2021-02-13 01:30 UTC, closed without merging