[WIP]末影接口小修
CFPAOrg/Minecraft-Mod-Language-Package pull request #995
Opened 2021-03-03 14:31 UTC by Lyaiya

- [x] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [x] 我已标记PR以便审查（见`CONTRIBUTING.md`）
- [x] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是: `projects/1.12.2/assets/curseforge 域名/模组资源 id/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是: `projects/1.16.1/assets/curseforge 域名/模组资源 id/lang/zh_cn.json`
- [x] 我已确认语言文件名大小写正确，所有的语言文件全为小写；
- [x] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

1. 删除 1UNKNOWN 末影接口相关的语言文件，解决 key 覆盖问题，日后只需维护完整包，不在完整包的单独维护
2. 小改旧有翻译并添加末影接口存储模块的翻译

2021-03-03 15:55 UTC, TUsama requested changes

2021-03-03 15:55 UTC, TUsama commented on projects/1.12.2/assets/ender-io-zoo/enderio/lang/zh_cn.lang
> +entity.enderiozoo.voidslime.name=Infinity Spawn
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

此处？

2021-03-03 15:55 UTC, TUsama commented on projects/1.12.2/assets/ender-io/enderio/lang/zh_cn.lang
>  item.item_dark_steel_shears.tooltip.multiHarvest=充能时修剪多个方块/羊
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

“时”还是“后”？

2021-03-03 15:55 UTC, TUsama commented on projects/1.12.2/assets/ender-io/enderio/lang/zh_cn.lang
> +item.item_dark_steel_boots.tooltip.line1=充能后可免疫掉落伤害
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

“摔落伤害”，下同

2021-03-03 15:55 UTC, TUsama commented on projects/1.12.2/assets/ender-io/enderio/lang/zh_cn.lang
> +item.item_magnet.tooltip.detailed.line2=Shift 右击来开关
|Feedback Priority|
|---|
|🌫 Dust / Non-blocking, “take it or leave it”|

```suggestion
item.item_magnet.tooltip.detailed.line2=Shift 右击切换开关状态
```

2021-03-15 01:43 UTC, TUsama commented on projects/1.12.2/assets/ender-io/enderio/lang/zh_cn.lang
>  enderio.loot.capacitor.green=绿化的 %s
下方“干净整洁的”后面怎么没有空格？

2021-03-15 01:45 UTC, TUsama commented on projects/1.12.2/assets/ender-io/enderio/lang/zh_cn.lang
>  tile.block_travel_anchor.tooltip.detailed.line1=允许在锚点之间传送
```suggestion
tile.block_travel_anchor.tooltip.detailed.line1=可让你在锚点之间传送
```

2021-03-15 01:51 UTC, TUsama approved these changes

2021-03-15 09:21 UTC, TUsama approved these changes

2021-03-26 14:03 UTC, Lyaiya commented
解决冲突了，可以合了。

2021-03-28 08:33 UTC, merged