1.16
CFPAOrg/Minecraft-Mod-Language-Package pull request #996
Opened 2021-03-03 17:53 UTC by Quaerere-Git

- [ ] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [ ] 我已标记PR以便审查（见`CONTRIBUTING.md`）
- [ ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是: `projects/1.12.2/assets/curseforge 域名/模组资源 id/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是: `projects/1.16.1/assets/curseforge 域名/模组资源 id/lang/zh_cn.json`
- [ ] 我已确认语言文件名大小写正确，所有的语言文件全为小写；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-03-04 02:29 UTC, TUsama requested changes

2021-03-04 02:29 UTC, TUsama commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"effect.atmospheric.spitting": "吐种子",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

可以说一说效果吗

2021-03-04 02:29 UTC, TUsama commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"biome.atmospheric.rainforest_mountains": "雨林山地",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

应为“地形+雨林”，词义应为“生长在xx中的雨林”，此处倒转不妥。

2021-03-04 02:29 UTC, TUsama commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"death.attack.fumarole.player": "%1$s在试图逃离%2$s时试图靠近喷泉",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

两个试图，不妥。

```suggestion
	"death.attack.fumarole.player": "%1$s在逃离%2$s时试图靠近喷泉",

```

2021-03-04 02:29 UTC, TUsama commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"block.atmospheric.barrel_cactus_batch": "成批桶仙人掌",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

似为“一捆”较为妥帖。直译“批”不太符合中文额两次习惯。

2021-03-04 02:29 UTC, TUsama commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"block.atmospheric.arid_sand": "干燥沙",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

若要求与原版严格对照，此处为“干燥沙子”最为恰当。
```suggestion
	"block.atmospheric.arid_sand": "干燥沙子",
```

2021-03-04 02:29 UTC, TUsama commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"advancements.husbandry.finish_gateau.title": "何不食……蛋糕？",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
	"advancements.husbandry.finish_gateau.title": "何不食...蛋糕？",
```

2021-03-04 05:24 UTC, Quaerere-Git commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"death.attack.fumarole.player": "%1$s在试图逃离%2$s时试图靠近喷泉",
已修正

2021-03-04 05:27 UTC, Quaerere-Git commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"block.atmospheric.arid_sand": "干燥沙",
已修正

2021-03-04 05:30 UTC, Quaerere-Git commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"advancements.husbandry.finish_gateau.title": "何不食……蛋糕？",
已修正

2021-03-04 05:30 UTC, Quaerere-Git commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"block.atmospheric.barrel_cactus_batch": "成批桶仙人掌",
OK

2021-03-04 05:40 UTC, Quaerere-Git commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"effect.atmospheric.spitting": "吐种子",
Relief效果是当受到伤害≥效果等级时治愈玩家，Worsening效果是当受到伤害≥效果等级时增加伤害，Spitting效果通过吃百香果获得，就是一直向前吐出能够伤害生物的百香果种子

2021-03-04 06:06 UTC, Lyaiya commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"block.atmospheric.arid_sand": "干燥沙子",
```suggestion
	"block.atmospheric.arid_sand": "干旱沙子",

```
**干燥**一般形容气候，此处用**干旱**会比较合适，下同。

2021-03-04 06:12 UTC, Lyaiya reviewed
参考原版的云杉，白桦相关翻译

2021-03-04 06:12 UTC, Lyaiya commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"block.atmospheric.grimwood_log": "阴郁木原木",
```suggestion
	"block.atmospheric.grimwood_log": "阴郁原木",

```

2021-03-04 06:12 UTC, Lyaiya commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"block.atmospheric.stripped_grimwood_log": "去皮阴郁木原木",
```suggestion
	"block.atmospheric.stripped_grimwood_log": "去皮阴郁原木",

```

2021-03-04 06:12 UTC, Lyaiya commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"block.atmospheric.grimwood_planks": "阴郁木木板",
```suggestion
	"block.atmospheric.grimwood_planks": "阴郁木板",

```

2021-03-04 06:12 UTC, Lyaiya commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"block.atmospheric.grimwood_sapling": "阴郁树树苗",
```suggestion
	"block.atmospheric.grimwood_sapling": "阴郁树苗",

```

2021-03-04 06:12 UTC, Lyaiya commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"block.atmospheric.grimwood_leaves": "阴郁树树叶",
```suggestion
	"block.atmospheric.grimwood_leaves": "阴郁树叶",

```

2021-03-04 06:12 UTC, Lyaiya commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"block.atmospheric.grimwood_leaf_carpet": "阴郁树树叶地毯",
```suggestion
	"block.atmospheric.grimwood_leaf_carpet": "阴郁树叶地毯",

```

2021-03-04 06:12 UTC, Lyaiya commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"block.atmospheric.potted_grimwood_sapling": "阴郁树树苗盆栽",
```suggestion
	"block.atmospheric.potted_grimwood_sapling": "阴郁树苗盆栽",

```

2021-03-04 06:12 UTC, Lyaiya commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"block.atmospheric.vertical_grimwood_planks": "竖直阴郁木木板",
```suggestion
	"block.atmospheric.vertical_grimwood_planks": "竖直阴郁木板",

```

2021-03-04 06:19 UTC, Quaerere-Git commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"block.atmospheric.grimwood_log": "阴郁木原木",
阴郁木的原文"Grimwood"包含"Wood"，参考原版的白桦、云杉可能不合适

2021-03-04 06:22 UTC, Lyaiya commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"block.atmospheric.grimwood_log": "阴郁木原木",
没注意到，就按你的来吧

2021-03-04 06:31 UTC, Quaerere-Git commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"block.atmospheric.arid_sand": "干燥沙子",
已修正

2021-03-05 04:45 UTC, TUsama commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"block.atmospheric.arid_sand": "干燥沙子",
> 干燥(drying)是利用热能使湿物料中的湿分(水分或其他溶剂)气化，并利用气流或真空带走气化了的湿分，从而获得干燥物料的操作。如湿法制粒中物料的干燥、溶液的喷雾干燥、流浸膏的干燥等。

> 干旱是指淡水总量少，不足以满足人的生存和经济发展的气候现象，一般是长期的现象。

完全反了，这里指的是单个方块的湿润程度，使用干燥合情合理，干旱是气候用语。

2021-03-05 04:48 UTC, Quaerere-Git commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"block.atmospheric.arid_sand": "干燥沙子",
。。。好吧

2021-03-09 13:09 UTC, TUsama approved these changes

2021-03-09 13:09 UTC, TUsama commented on projects/1.16.1/assets/atmospheric/atmospheric/lang/zh_cn.json
> +	"biome.atmospheric.rainforest_mountains": "山地雨林",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

我仔细思考了一下，以下这几种是不是雨林的变种群系？如果是的话，那就得改成雨林xx了。

我好像在哪里说过这个问题，但是我翻不到review记录了。。。

2021-03-12 10:48 UTC, TUsama approved these changes

2021-03-12 11:06 UTC, merged