Artifacts汉化修正
CFPAOrg/Minecraft-Mod-Language-Package pull request #998
Opened 2021-03-04 12:11 UTC by Quaerere-Git

- [ ] 我已阅读注意事项 [#847](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/847)
- [ ] 我已标记PR以便审查（见`CONTRIBUTING.md`）
- [ ] 我已确认文件路径、分支均正确：
    - 如果是 1.12 翻译，应该是: `projects/1.12.2/assets/curseforge 域名/模组资源 id/lang/zh_cn.lang`
    - 如果是 1.15-1.16 翻译，应该是: `projects/1.16.1/assets/curseforge 域名/模组资源 id/lang/zh_cn.json`
- [ ] 我已确认语言文件名大小写正确，所有的语言文件全为小写；
- [ ] 我已阅读相关协议，同意对于本项目的贡献的许可协议：[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/1.10.2/LICENSE)

2021-03-05 05:44 UTC, ChromaPIE requested changes
除文中提到的问题，en_us中第43、44、77、78行内容未翻译

2021-03-05 05:44 UTC, ChromaPIE commented on projects/1.16.1/assets/artifacts/artifacts/lang/zh_cn.json
> +  "item.artifacts.novelty_drinking_hat.tooltip": "'嘿！我可是头号产品，我能操控重力，让饮料更快地流入你的胃里！'\n降低饮用物品所需时间",
理解错误。可以是“借助重力”。

2021-03-05 05:44 UTC, ChromaPIE commented on projects/1.16.1/assets/artifacts/artifacts/lang/zh_cn.json
> +  "item.artifacts.obsidian_skull.tooltip": "受到火焰伤害后暂时内免疫活跃伤害",
错别字

2021-03-05 05:44 UTC, ChromaPIE commented on projects/1.16.1/assets/artifacts/artifacts/lang/zh_cn.json
> +  "item.artifacts.cloud_in_a_bottle.tooltip": "维吉尔都不会的二段跳",
修改

2021-03-05 07:02 UTC, Quaerere-Git commented on projects/1.16.1/assets/artifacts/artifacts/lang/zh_cn.json
> +  "item.artifacts.cloud_in_a_bottle.tooltip": "维吉尔都不会的二段跳",
？

2021-03-09 04:32 UTC, SettingDust approved these changes

2021-03-09 04:32 UTC, SettingDust commented on projects/1.16.1/assets/artifacts/artifacts/lang/zh_cn.json
> +  "item.artifacts.obsidian_skull": "黑曜石头颅",
既然是“致敬”Terraria，是否可以使用官中的 “黑曜石骷髅头” 呢？

2021-03-09 13:02 UTC, TUsama requested changes

2021-03-11 08:44 UTC, Quaerere-Git commented on projects/1.16.1/assets/artifacts/artifacts/lang/zh_cn.json
> +  "item.artifacts.running_shoes.tooltip": "增加冲刺时的移速和自动跳跃高度",
已改

2021-03-11 08:44 UTC, Quaerere-Git commented on projects/1.16.1/assets/artifacts/artifacts/lang/zh_cn.json
> +  "item.artifacts.obsidian_skull": "黑曜石头颅",
可

2021-03-12 11:13 UTC, ChromaPIE approved these changes

2021-03-12 11:14 UTC, merged